## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-14-13-32 +0000,bbc,SpaceX's stock market blast-off could be Musk'...,https://www.bbc.com/news/articles/cy8d9e4lzv1o...
1,2026-06-11-14-13-22 +0000,nypost,Trump admin yanks funding from LA homeless age...,https://nypost.com/2026/06/11/us-news/trump-ad...
2,2026-06-11-14-12-28 +0000,nyt,Iran War Live Updates: U.S.-Iran Strikes Risk ...,https://www.nytimes.com/live/2026/06/11/world/...
3,2026-06-11-14-12-27 +0000,nyt,U.S. Strikes on Ships Off Oman Continue After ...,https://www.nytimes.com/2026/06/11/world/asia/...
4,2026-06-11-14-10-17 +0000,nypost,NYC was absolutely electric after Knicks’ hist...,https://nypost.com/2026/06/11/sports/nyc-was-e...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
9   trump     38
22   iran     33
29    new     29
81  world     25
23    war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
283,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...,143
238,2026-06-10-21-48-11 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,139
2,2026-06-11-14-12-28 +0000,nyt,Iran War Live Updates: U.S.-Iran Strikes Risk ...,https://www.nytimes.com/live/2026/06/11/world/...,134
25,2026-06-11-13-44-18 +0000,nyt,Oil Prices Fluctuate as Trump Issues New Threa...,https://www.nytimes.com/2026/06/10/business/oi...,129
300,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
283,143,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...
300,96,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...
299,72,2026-06-10-19-31-12 +0000,latimes,L.A. is hosting free World Cup watch parties a...,https://www.latimes.com/california/story/2026-...
82,67,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...
367,48,2026-06-10-15-13-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
88,45,2026-06-11-11-00-00 +0000,nypost,This mom of five struggled when her kids were ...,https://nypost.com/2026/06/11/us-news/this-mom...
268,42,2026-06-10-20-58-10 +0000,nyt,Graham Platner’s Victory in Maine Senate Prima...,https://www.nytimes.com/2026/06/10/us/politics...
0,40,2026-06-11-14-13-32 +0000,bbc,SpaceX's stock market blast-off could be Musk'...,https://www.bbc.com/news/articles/cy8d9e4lzv1o...
57,34,2026-06-11-12-40-22 +0000,nypost,NY Knicks fans waving Palestinian flag seen sm...,https://nypost.com/2026/06/11/us-news/knicks-f...
56,33,2026-06-11-12-46-03 +0000,nypost,Trump says US ‘will be taking Kharg Island’ oi...,https://nypost.com/2026/06/11/us-news/trump-sa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)