## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-07-02-42 +0000,bbc,Badenoch says she is instructing lawyers to ch...,https://www.bbc.co.uk/news/articles/cw4gq87ed6...
1,2026-09-18-07-00-07 +0000,nyt,How Karaoke Became a Healing Balm for the Exon...,https://www.nytimes.com/2026/09/18/us/karaoke-...
2,2026-09-18-06-57-33 +0000,nypost,Alabama killer’s last words before he’s execut...,https://nypost.com/2026/09/18/us-news/alabama-...
3,2026-09-18-06-57-00 +0000,wsj,Malaysia’s Former Prime Minister Can Serve Res...,https://www.wsj.com/world/africa/malaysias-for...
4,2026-09-18-06-52-47 +0000,bbc,Healey to ask EU finance ministers to let UK i...,https://www.bbc.co.uk/news/articles/cr6240ej07...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
164  trump     43
293     ai     24
313    new     24
230  rates     18
36   house     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
78,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,163
353,2026-09-17-11-00-00 +0000,wsj,The trillion-dollar question: Did Fed Chairman...,https://www.wsj.com/politics/policy/the-trilli...,115
192,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...,115
63,2026-09-18-01-00-00 +0000,wsj,"The price of eating out, filling a gas tank an...",https://www.wsj.com/economy/weeks-before-the-m...,107
356,2026-09-17-10-40-44 +0000,nypost,Mark Carney welcomes proposal for Canada to be...,https://nypost.com/2026/09/17/world-news/mark-...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
78,163,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...
214,76,2026-09-17-17-46-14 +0000,nypost,"Chinese AI labs must accelerate development, s...",https://nypost.com/2026/09/17/business/chinese...
120,76,2026-09-17-21-41-19 +0000,bbc,US to allow Iran delegation to attend UN meeti...,https://www.bbc.co.uk/news/articles/c6n8m72r13...
63,73,2026-09-18-01-00-00 +0000,wsj,"The price of eating out, filling a gas tank an...",https://www.wsj.com/economy/weeks-before-the-m...
240,58,2026-09-17-16-38-02 +0000,nypost,Pregnant newlywed found dead after Venice boat...,https://nypost.com/2026/09/17/world-news/pregn...
356,56,2026-09-17-10-40-44 +0000,nypost,Mark Carney welcomes proposal for Canada to be...,https://nypost.com/2026/09/17/world-news/mark-...
195,56,2026-09-17-18-54-41 +0000,cbc,Judge orders Kennedy Center to give 30-day not...,https://www.cbc.ca/news/world/kennedy-center-t...
139,45,2026-09-17-20-59-09 +0000,nypost,California AG Rob Bonta talks tough on Paramou...,https://nypost.com/2026/09/17/media/california...
309,44,2026-09-17-13-30-00 +0000,wsj,Here’s What the World Is Doing (and Not Doing)...,https://www.wsj.com/business/energy-oil/heres-...
126,43,2026-09-17-21-36-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)