## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-09-10-23 +0000,nypost,Online fundraiser for Boston police officer ch...,https://nypost.com/2026/03/24/us-news/online-f...
1,2026-03-24-09-02-20 +0000,nyt,Stephen Miller Asks Why Texas Pays to Teach Un...,https://www.nytimes.com/2026/03/24/us/politics...
2,2026-03-24-09-02-15 +0000,nyt,A Veteran Group Jumps In for a Democrat in Iow...,https://www.nytimes.com/2026/03/24/us/politics...
3,2026-03-24-09-02-02 +0000,nyt,Chavez Revelations Force Teachers to Rethink H...,https://www.nytimes.com/2026/03/24/us/chavez-s...
4,2026-03-24-09-01-59 +0000,nyt,Should You Need to Prove Citizenship to Vote? ...,https://www.nytimes.com/2026/03/24/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2621/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
175   iran     45
51   trump     44
68     war     25
228    oil     16
514    new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
347,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,140
332,2026-03-23-13-16-13 +0000,nypost,"Dow rallies 600 points, oil tumbles below $100...",https://nypost.com/2026/03/23/business/dow-fut...,136
319,2026-03-23-14-08-41 +0000,nypost,Trump says ‘we don’t know’ if Iran’s new Supre...,https://nypost.com/2026/03/23/us-news/trump-sa...,132
214,2026-03-23-19-47-08 +0000,wapo,Trump says U.S. is postponing some strikes as ...,https://www.washingtonpost.com/politics/2026/0...,129
124,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
347,140,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...
276,94,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
71,65,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
178,63,2026-03-23-21-13-47 +0000,bbc,'Like the plane got cut in half': LaGuardia cr...,https://www.bbc.com/news/articles/c78rdze8zvjo...
202,62,2026-03-23-20-21-51 +0000,bbc,Oil falls and shares rebound after Trump says ...,https://www.bbc.com/news/articles/czex56kwxxzo...
195,43,2026-03-23-20-43-02 +0000,nypost,Anti-communist dance troupe Shen Yun claims CC...,https://nypost.com/2026/03/23/world-news/shen-...
59,41,2026-03-24-04-52-28 +0000,nypost,Sheriff Chris Nanos shrugs off missteps in Nan...,https://nypost.com/2026/03/24/us-news/sheriff-...
233,37,2026-03-23-18-41-00 +0000,wsj,ICE Agents—Many Unmasked—Deploy to Airports Am...,https://www.wsj.com/us-news/trump-asks-ice-age...
116,36,2026-03-24-00-31-12 +0000,nypost,Senate confirms Sen. Markwayne Mullin to repla...,https://nypost.com/2026/03/23/us-news/senate-c...
298,35,2026-03-23-15-12-31 +0000,nypost,Blackrock CEO Larry Fink warns of ‘costly’ glo...,https://nypost.com/2026/03/23/business/blackro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)