## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-29-04-07-47 +0000,nypost,Allison Reid lived secret double life at Hofst...,https://nypost.com/2026/05/29/sports/allison-r...
1,2026-05-29-04-01-07 +0000,nyt,Europe is Edging Closer to a Trade War With Ch...,https://www.nytimes.com/2026/05/29/world/europ...
2,2026-05-29-03-59-17 +0000,nyt,Scripps Spelling Bee 2026 Takeaways: Shrey Par...,https://www.nytimes.com/live/2026/05/28/us/scr...
3,2026-05-29-03-39-31 +0000,nypost,Long Island sixth-grader dies in rafting accid...,https://nypost.com/2026/05/28/us-news/long-isl...
4,2026-05-29-03-33-00 +0000,wsj,"With Caesars Deal, Tilman Fertitta Doubles Dow...",https://www.wsj.com/business/hospitality/with-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
128   iran     30
140  trump     28
18     bee     19
66     new     19
36    deal     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...,139
50,2026-05-29-01-10-16 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,138
38,2026-05-29-01-47-48 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,138
74,2026-05-29-00-11-26 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,138
44,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,139,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...
153,103,2026-05-28-21-04-00 +0000,wsj,The Trump administration has been holding talk...,https://www.wsj.com/politics/policy/putting-tr...
180,96,2026-05-28-20-07-00 +0000,wsj,"Reports of an Iran deal boost markets, new-car...",https://www.wsj.com/business/autos/iran-deal-r...
258,62,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
63,59,2026-05-29-00-42-00 +0000,wsj,Shares in Dell soared nearly 40% in after-hour...,https://www.wsj.com/tech/dell-stock-soars-on-d...
56,55,2026-05-29-01-00-00 +0000,wsj,Labor’s share of economic output just hit an a...,https://www.wsj.com/finance/stocks/the-record-...
61,50,2026-05-29-00-46-41 +0000,nypost,3-year-old California girl hospitalized with a...,https://nypost.com/2026/05/28/us-news/californ...
312,45,2026-05-28-11-44-55 +0000,nypost,Iran fires ballistic missile at American base ...,https://nypost.com/2026/05/28/world-news/iran-...
324,41,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...
316,38,2026-05-28-11-06-20 +0000,nypost,"Dame Helen Mirren, 80, called ‘evil Zionist b—...",https://nypost.com/2026/05/28/world-news/dame-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)