## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-23-17-54-22 +0000,nyt,"Iran Will Not Be Bullied, President Masoud Pez...",https://www.nytimes.com/2026/09/23/world/middl...
1,2026-09-23-17-53-56 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/09/23/world/...
2,2026-09-23-17-53-00 +0000,wsj,"With Putin, Trump’s G-20 Would Be Summit Spect...",https://www.wsj.com/politics/policy/with-putin...
3,2026-09-23-17-49-31 +0000,nyt,U.N. Live Updates: Iran’s President Accuses U....,https://www.nytimes.com/live/2026/09/23/world/...
4,2026-09-23-17-46-46 +0000,nyt,Argentina’s Milei assails the U.N. as a ‘usele...,https://www.nytimes.com/live/2026/09/23/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2336/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
10       trump     87
107        new     28
0         iran     25
1         will     21
3    president     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
272,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,196
446,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...,193
266,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...,183
399,2026-09-22-20-10-43 +0000,nyt,Zelensky Says He Hopes Trump Will Help to End ...,https://www.nytimes.com/2026/09/22/world/europ...,182
274,2026-09-23-01-57-25 +0000,nyt,Trump Threatens Annihilation in Iran in UN Spe...,https://www.nytimes.com/2026/09/22/us/politics...,173

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
272,196,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
399,95,2026-09-22-20-10-43 +0000,nyt,Zelensky Says He Hopes Trump Will Help to End ...,https://www.nytimes.com/2026/09/22/world/europ...
64,88,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
266,85,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...
200,66,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
146,66,2026-09-23-13-53-50 +0000,nypost,China lays out ‘red lines’ for Trump-Xi meetin...,https://nypost.com/2026/09/23/us-news/china-la...
299,51,2026-09-23-00-00-00 +0000,wsj,HHS moved money from a minority health office ...,https://www.wsj.com/politics/policy/rfk-jr-hhs...
287,48,2026-09-23-01-10-41 +0000,latimes,California deal on Paramount-Warner Bros. merg...,https://www.latimes.com/politics/story/2026-09...
451,48,2026-09-22-18-15-23 +0000,nypost,30-year-old Praxis CEO planning AI-powered uto...,https://nypost.com/2026/09/22/business/30-year...
69,46,2026-09-23-16-24-00 +0000,wsj,Energy Secretary Chris Wright on Wednesday sai...,https://www.wsj.com/politics/policy/energy-sec...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)