## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-01-10-28 +0000,nyt,House Passes Defense Bill Amid Iran War Divide,https://www.nytimes.com/2026/07/22/us/politics...
1,2026-07-23-01-07-59 +0000,nyt,"Man Found Guilty in 2 California Stabbings, an...",https://www.nytimes.com/2026/07/22/us/uc-davis...
2,2026-07-23-01-07-58 +0000,latimes,O.C. gang members convicted of murder while ca...,https://www.latimes.com/california/story/2026-...
3,2026-07-23-01-07-00 +0000,nypost,US carrying out new wave of Iran strikes as mi...,https://nypost.com/2026/07/22/world-news/us-ca...
4,2026-07-23-01-00-00 +0000,wsj,This AI Tech Billionaire Just Doubled His Net ...,https://www.wsj.com/world/asia/nvidia-sk-hynix...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
68     trump     45
24       new     35
180     deal     27
5       iran     26
179  nuclear     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
371,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,141
285,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,133
6,2026-07-23-00-56-00 +0000,nyt,Iran War Live Updates: Iran Digs In After Late...,https://www.nytimes.com/live/2026/07/22/world/...,131
104,2026-07-22-21-29-58 +0000,nypost,House GOP passes $95B budget proposal on party...,https://nypost.com/2026/07/22/us-news/mike-joh...,127
100,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
371,141,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...
260,100,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
46,59,2026-07-22-23-23-44 +0000,nypost,Man who was killed after mom found him hiding ...,https://nypost.com/2026/07/22/us-news/man-alle...
297,59,2026-07-22-14-14-00 +0000,wsj,"R. James Woolsey, CIA director in Clinton admi...",https://www.wsj.com/politics/national-security...
92,52,2026-07-22-21-50-39 +0000,nyt,House Republicans Pass Stock Trading Bill Tied...,https://www.nytimes.com/2026/07/22/us/politics...
225,45,2026-07-22-17-07-05 +0000,bbc,I travel four hours on a bus per day - the bus...,https://www.bbc.co.uk/news/articles/clyv4y3xdv...
311,44,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
324,43,2026-07-22-12-44-44 +0000,cbc,Austria turns Hitler's first home into police ...,https://www.cbc.ca/news/world/austria-hitler-h...
81,42,2026-07-22-22-08-35 +0000,nypost,Ex-NFL kicker Jay Feely likely to face off aga...,https://nypost.com/2026/07/22/us-news/ex-nfl-k...
304,40,2026-07-22-13-36-11 +0000,nypost,OpenAI agent goes rogue in ‘unprecedented cybe...,https://nypost.com/2026/07/22/business/openai-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)