## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-15-10-49-10 +0000,nypost,Trump calls ‘incredible’ UFC event ‘one of the...,https://nypost.com/2026/06/15/us-news/trump-ca...
1,2026-06-15-10-47-31 +0000,nyt,Iran War Live Updates: U.S.-Iran Framework Bri...,https://www.nytimes.com/live/2026/06/15/world/...
2,2026-06-15-10-47-30 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/15/world/...
3,2026-06-15-10-46-00 +0000,wsj,"Stock Futures Rally, Oil Drops After U.S.-Iran...",https://www.wsj.com/finance/u-s-futures-global...
4,2026-06-15-10-39-15 +0000,nyt,"China Moves the Price of Oil, Even When It Buy...",https://www.nytimes.com/2026/06/15/business/ch...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     39
12    iran     35
28    deal     26
156  world     14
26     oil     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
221,2026-06-14-12-12-46 +0000,nypost,"Iran agrees not to build a nuke, will reopen S...",https://nypost.com/2026/06/14/world-news/iran-...,143
151,2026-06-14-21-36-06 +0000,nypost,Trump announces US and Iran have reached peace...,https://nypost.com/2026/06/14/world-news/trump...,138
15,2026-06-15-10-10-09 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,136
152,2026-06-14-21-35-16 +0000,startribune,Trump says a deal has been reached with Iran a...,https://www.startribune.com/trump-says-a-deal-...,136
208,2026-06-14-15-05-43 +0000,nypost,Trump says Iran peace deal will be signed in n...,https://nypost.com/2026/06/14/us-news/trump-cr...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
221,143,2026-06-14-12-12-46 +0000,nypost,"Iran agrees not to build a nuke, will reopen S...",https://nypost.com/2026/06/14/world-news/iran-...
93,56,2026-06-15-03-28-00 +0000,wsj,President Trump hosted a cage match at the Whi...,https://www.wsj.com/politics/trump-white-house...
159,45,2026-06-14-20-32-34 +0000,cbc,"Ahead of G7, Carney says no one country will c...",https://www.cbc.ca/news/politics/g7-carney-ire...
145,38,2026-06-14-22-17-16 +0000,wapo,U.S. singer Oliver Tree among six killed in he...,https://www.washingtonpost.com/world/2026/06/1...
137,38,2026-06-14-22-44-20 +0000,nypost,California man accused of ISIS terror plot wit...,https://nypost.com/2026/06/14/us-news/californ...
115,34,2026-06-15-00-22-00 +0000,bbc,Royal Marines board Russian shadow fleet oil t...,https://www.bbc.com/news/articles/clyek039l2vo...
135,29,2026-06-14-23-03-55 +0000,bbc,"Olé, olé, olé, olé - What makes a memorable Wo...",https://www.bbc.com/news/articles/c5yz434v7nro...
215,28,2026-06-14-13-05-33 +0000,nypost,Bungee jumper plummets to her death as she’s t...,https://nypost.com/2026/06/14/world-news/bunge...
8,26,2026-06-15-10-27-20 +0000,bbc,Norwegian crown princess's son found guilty of...,https://www.bbc.com/news/articles/cly9d10l5p4o...
82,25,2026-06-15-05-07-22 +0000,nypost,Trump warns France in exclusive interview with...,https://nypost.com/2026/06/15/business/trump-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)