## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-29-01-09-00 +0000,wsj,Morgan Stanley Bankers Were Pressured to Appro...,https://www.wsj.com/finance/banking/morgan-sta...
1,2026-07-29-01-08-39 +0000,nyt,Houthis Claim Strike on Another Saudi Oil Tanker,https://www.nytimes.com/2026/07/28/world/middl...
2,2026-07-29-01-03-00 +0000,wsj,Gold Drops Amid Hawkish Monetary Policy Backdrop,https://www.wsj.com/finance/commodities-future...
3,2026-07-29-01-00-06 +0000,startribune,GM Jeremy Zoll: Twins will be buyers at the tr...,https://www.startribune.com/minnesota-twins-ml...
4,2026-07-29-01-00-03 +0000,startribune,Powerful tornado leaves widespread damage in W...,https://www.startribune.com/tornado-that-carve...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2320/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
100   trump     42
103     new     23
94     iran     20
156  graham     19
260      ai     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
111,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,132
340,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,117
185,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,102
222,2026-07-28-17-39-53 +0000,nypost,Senate confirms Manhattan US Attorney Jay Clay...,https://nypost.com/2026/07/28/us-news/senate-c...,102
251,2026-07-28-16-31-19 +0000,chitri,Benjamin Netanyahu praises first meeting with ...,https://www.chicagotribune.com/2026/07/28/trum...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
111,132,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
249,71,2026-07-28-16-32-23 +0000,nypost,Gavin Newsom responds to Ruby Rippey’s claims ...,https://nypost.com/2026/07/28/us-news/gavin-ne...
18,70,2026-07-29-00-36-00 +0000,wsj,"With the Iran war continuing, Israeli Prime Mi...",https://www.wsj.com/world/middle-east/netanyah...
102,50,2026-07-28-21-41-00 +0000,wsj,The Trump administration plans to halt a Medic...,https://www.wsj.com/politics/policy/medicare-d...
144,46,2026-07-28-20-43-16 +0000,startribune,Elon Musk’s AI company seeks to block Minnesot...,https://www.startribune.com/elon-musks-ai-comp...
7,43,2026-07-29-01-00-00 +0000,wsj,"By the time the Federal Reserve meets, Wall St...",https://www.wsj.com/economy/central-banking/wh...
159,43,2026-07-28-20-07-09 +0000,cbc,15-year-old arrested in Seattle festival shoot...,https://www.cbc.ca/news/world/seattle-shooting...
210,41,2026-07-28-18-08-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
348,39,2026-07-28-10-00-00 +0000,latimes,Court monitor cites laundry list of healthcare...,https://www.latimes.com/california/story/2026-...
153,39,2026-07-28-20-18-34 +0000,nyt,Boeing Reports Loss on $280 Million Hit to Tro...,https://www.nytimes.com/2026/07/28/business/bo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)