## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-16-02-18-47 +0000,nypost,Virginia State University mass shooting suspec...,https://nypost.com/2026/08/15/us-news/virginia...
1,2026-08-16-02-09-33 +0000,nypost,Travel chaos at LAX as hurricane cancels Hawai...,https://nypost.com/2026/08/15/us-news/hurrican...
2,2026-08-16-02-08-10 +0000,nypost,Gun-toting granny chases off shoplifting suspe...,https://nypost.com/2026/08/15/us-news/based-gr...
3,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...
4,2026-08-16-02-00-00 +0000,wsj,This Sprawling Chinese Refinery Is Bankrolling...,https://www.wsj.com/world/china/hengli-china-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2483/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
130       trump     17
78          new      8
366  earthquake      7
106  california      7
27          her      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
64,2026-08-15-19-39-00 +0000,wsj,Trump Family’s World Liberty Financial Gets Pr...,https://www.wsj.com/finance/trump-familys-worl...,39
143,2026-08-15-09-38-51 +0000,nypost,"At least 38 dead, buildings toppled after magn...",https://nypost.com/2026/08/15/world-news/indon...,38
142,2026-08-15-10-00-00 +0000,latimes,Arellano: Shock gloves on immigrants? Trump gi...,https://www.latimes.com/california/story/2026-...,37
97,2026-08-15-15-44-40 +0000,nypost,Trump posts AI image of himself seizing Irania...,https://nypost.com/2026/08/15/us-news/trump-po...,37
117,2026-08-15-12-00-00 +0000,nypost,‘Iran’s black widow’ faces multiple death sent...,https://nypost.com/2026/08/15/us-news/irans-bl...,35

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
64,39,2026-08-15-19-39-00 +0000,wsj,Trump Family’s World Liberty Financial Gets Pr...,https://www.wsj.com/finance/trump-familys-worl...
143,38,2026-08-15-09-38-51 +0000,nypost,"At least 38 dead, buildings toppled after magn...",https://nypost.com/2026/08/15/world-news/indon...
58,30,2026-08-15-20-08-06 +0000,nypost,Acting Navy secretary salutes USS Abraham Linc...,https://nypost.com/2026/08/15/us-news/dire-rep...
117,30,2026-08-15-12-00-00 +0000,nypost,‘Iran’s black widow’ faces multiple death sent...,https://nypost.com/2026/08/15/us-news/irans-bl...
3,28,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...
19,26,2026-08-15-23-45-44 +0000,bbc,I survived two years as prime minister in a hi...,https://www.bbc.co.uk/news/articles/cq56pzqy6j...
17,24,2026-08-16-00-01-41 +0000,nypost,Bloodied Marine pilot seen walking away from f...,https://nypost.com/2026/08/15/us-news/bloodied...
72,23,2026-08-15-18-52-26 +0000,nypost,Wisconsin Dem calls out party for abandoning r...,https://nypost.com/2026/08/15/us-news/dem-cand...
35,23,2026-08-15-22-27-37 +0000,nypost,Putin loses 43K soldiers on Ukraine battlefiel...,https://nypost.com/2026/08/15/world-news/putin...
0,22,2026-08-16-02-18-47 +0000,nypost,Virginia State University mass shooting suspec...,https://nypost.com/2026/08/15/us-news/virginia...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)