## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-20-21-15-14 +0000,nyt,Mideast Live Updates: Vance Heads to Talks as ...,https://www.nytimes.com/live/2026/06/20/world/...
1,2026-06-20-21-13-11 +0000,nypost,3 more instructors arrested in harrowing death...,https://nypost.com/2026/06/20/world-news/3-mor...
2,2026-06-20-21-11-57 +0000,bbc,Iran says it has closed Strait of Hormuz over ...,https://www.bbc.com/news/articles/cwyekkwm1mmo...
3,2026-06-20-21-10-10 +0000,wapo,Chaotic run-up to U.S.-Iran talks signals stee...,https://www.washingtonpost.com/world/2026/06/2...
4,2026-06-20-21-05-58 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/20/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
48   trump     15
21    iran     11
143  world     10
28      up      8
152    new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
91,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...,51
2,2026-06-20-21-11-57 +0000,bbc,Iran says it has closed Strait of Hormuz over ...,https://www.bbc.com/news/articles/cwyekkwm1mmo...,43
22,2026-06-20-19-39-58 +0000,nypost,Son of FDNY hero killed on 9/11 carries World ...,https://nypost.com/2026/06/20/us-news/son-of-f...,40
38,2026-06-20-17-57-56 +0000,nypost,Trump says vandals used chemicals to damage ne...,https://nypost.com/2026/06/20/us-news/trump-sa...,40
53,2026-06-20-17-25-21 +0000,nypost,Italian PM claps back at Trump for ‘senseless’...,https://nypost.com/2026/06/20/us-news/italian-...,38

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
91,51,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...
2,40,2026-06-20-21-11-57 +0000,bbc,Iran says it has closed Strait of Hormuz over ...,https://www.bbc.com/news/articles/cwyekkwm1mmo...
22,40,2026-06-20-19-39-58 +0000,nypost,Son of FDNY hero killed on 9/11 carries World ...,https://nypost.com/2026/06/20/us-news/son-of-f...
58,33,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...
15,29,2026-06-20-19-58-16 +0000,nypost,American Olympic canoeist arrested for alleged...,https://nypost.com/2026/06/20/us-news/american...
94,26,2026-06-20-12-47-10 +0000,nypost,Italian mom killed in Dominican Republic resor...,https://nypost.com/2026/06/20/world-news/itali...
98,26,2026-06-20-12-00-00 +0000,latimes,Lopez: They found a new park hiding in plain s...,https://www.latimes.com/california/story/2026-...
54,23,2026-06-20-17-15-24 +0000,nypost,California gender-secrecy law for students suf...,https://nypost.com/2026/06/20/us-news/court-bl...
41,22,2026-06-20-17-55-55 +0000,nypost,"NYC pols demanding Congress to get MLB, other ...",https://nypost.com/2026/06/20/us-news/nyc-pols...
44,22,2026-06-20-17-52-20 +0000,nypost,World Cup brings temporary peace to violence-r...,https://nypost.com/2026/06/20/world-news/mexic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)