## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-11-16-52-50 +0000,nyt,Pope Leo Will Have Surgery to Remove Growth on...,https://www.nytimes.com/2026/10/11/world/europ...
1,2026-10-11-16-48-36 +0000,nypost,Nearly 396K Florida and Alabama residents lose...,https://nypost.com/2026/10/11/us-news/nearly-3...
2,2026-10-11-16-45-14 +0000,nypost,Berkeley engineer caught on video poisoning co...,https://nypost.com/2026/10/11/us-news/berkeley...
3,2026-10-11-16-41-37 +0000,bbc,Saudi capital airport hit by second strike in ...,https://www.bbc.co.uk/news/articles/cr93znyk44...
4,2026-10-11-16-41-30 +0000,startribune,Live: Unbeaten Vikings get Justin Jefferson ba...,https://www.startribune.com/minnesota-vikings-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2325/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
50     trump     32
60       new     16
47   ukraine     12
323   killed     11
29     saudi     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
192,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...,87
41,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,85
146,2026-10-11-01-41-29 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...,85
201,2026-10-10-19-28-55 +0000,nyt,"Rebuking Ukraine Over Oil Strikes, Trump Says ...",https://www.nytimes.com/2026/10/10/world/europ...,82
12,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
192,87,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...
148,62,2026-10-11-01-08-07 +0000,wapo,"12 killed, hundreds injured in Saudi Arabia ai...",https://www.washingtonpost.com/world/2026/10/1...
63,51,2026-10-11-11-31-16 +0000,nypost,Man mauled to death by tiger was happily danci...,https://nypost.com/2026/10/11/world-news/man-m...
55,47,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
217,45,2026-10-10-18-08-00 +0000,wsj,"Kimberly Guilfoyle, as America’s newly minted ...",https://www.wsj.com/politics/policy/at-davos-k...
176,37,2026-10-10-21-20-01 +0000,bbc,Two children and pregnant woman among 8 shot d...,https://www.bbc.co.uk/news/articles/cmed3njg5d...
178,33,2026-10-10-21-15-00 +0000,wsj,California Gov. Gavin Newsom has long opposed ...,https://www.wsj.com/politics/newsom-backs-meas...
126,31,2026-10-11-08-00-00 +0000,cbc,What happens when a Google data centre comes t...,https://www.cbc.ca/news/world/ai-data-centre-g...
169,29,2026-10-10-22-13-08 +0000,bbc,Young men live in fear of being snatched off t...,https://www.bbc.co.uk/news/articles/c680zlny0g...
1,25,2026-10-11-16-48-36 +0000,nypost,Nearly 396K Florida and Alabama residents lose...,https://nypost.com/2026/10/11/us-news/nearly-3...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)