## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-18-50-47 +0000,nyt,What to know about the Fed’s decision.,https://www.nytimes.com/live/2026/09/16/busine...
1,2026-09-16-18-50-07 +0000,nyt,The World Economy Is Becoming Wary of the U.S.,https://www.nytimes.com/2026/09/16/business/tr...
2,2026-09-16-18-49-34 +0000,nyt,Gold Mine Collapse in Sudan Kills at Least 70,https://www.nytimes.com/2026/09/16/world/afric...
3,2026-09-16-18-48-22 +0000,nyt,Fed Signals Another Rate Increase Could Be Coming,https://www.nytimes.com/2026/09/16/business/fe...
4,2026-09-16-18-47-03 +0000,nyt,E.U.-Canada Ambitions Face Reality Check,https://www.nytimes.com/2026/09/16/world/canad...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2473/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     45
215     ai     29
0      fed     20
319    war     19
47     new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
374,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,201
359,2026-09-15-22-39-00 +0000,wsj,The Kennedy Center’s board voted on Tuesday to...,https://www.wsj.com/us-news/law/trumps-name-ca...,116
431,2026-09-15-19-50-00 +0000,wsj,President Trump said Tuesday that the three Su...,https://www.wsj.com/politics/policy/trumps-fru...,106
189,2026-09-16-11-25-05 +0000,chitri,US-Canada trade war further taxes small busine...,https://www.chicagotribune.com/2026/09/16/us-c...,102
34,2026-09-16-18-13-13 +0000,nypost,EU boss proposes making Canada associate membe...,https://nypost.com/2026/09/16/world-news/eu-bo...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
374,201,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
436,89,2026-09-15-19-36-30 +0000,nypost,10-year Treasury yield hits highest level sinc...,https://nypost.com/2026/09/15/business/10-year...
400,76,2026-09-15-20-47-00 +0000,wsj,The U.S. is pressuring Mexico to accept new ru...,https://www.wsj.com/economy/trade/u-s-pressure...
258,65,2026-09-16-08-49-19 +0000,cbc,EU chief says she wants Canada to become the b...,https://www.cbc.ca/news/politics/eu-canada-ass...
431,61,2026-09-15-19-50-00 +0000,wsj,President Trump said Tuesday that the three Su...,https://www.wsj.com/politics/policy/trumps-fru...
231,59,2026-09-16-10-00-00 +0000,wsj,Security gaps at Utah Valley University last S...,https://www.wsj.com/us-news/charlie-kirks-wido...
135,57,2026-09-16-14-43-23 +0000,nyt,News Helicopter Crash and Bus Accident in Los ...,https://www.nytimes.com/2026/09/15/us/los-ange...
363,48,2026-09-15-22-15-45 +0000,nypost,Senate fails to advance Clarity Act in blow to...,https://nypost.com/2026/09/15/business/senate-...
414,45,2026-09-15-20-18-00 +0000,wsj,A broad measure of American incomes reached a ...,https://www.wsj.com/economy/consumers/american...
31,43,2026-09-16-18-17-18 +0000,chitri,First Fed rate hike in 3 years may push borrow...,https://www.chicagotribune.com/2026/09/16/fede...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)