## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-10-16-03-45 +0000,nyt,Iran Responds to Latest U.S. Plan to End War,https://www.nytimes.com/2026/05/10/us/politics...
1,2026-05-10-16-00-06 +0000,bbc,Rayner delivers 'last chance' warning to Starmer,https://www.bbc.com/news/articles/c5yekp5j36zo...
2,2026-05-10-16-00-00 +0000,wsj,The Simple Fix Small-Town Schools Are Using to...,https://www.wsj.com/personal-finance/the-simpl...
3,2026-05-10-16-00-00 +0000,wsj,Higher Gas Prices Are Seeping Into the Produce...,https://www.wsj.com/business/logistics/higher-...
4,2026-05-10-16-00-00 +0000,wsj,Israel’s Clandestine War Base in Iraq,https://www.wsj.com/world/middle-east/israels-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2662/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0          iran     14
55        trump     11
156  hantavirus     10
5           war     10
120        ship      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
50,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,66
117,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...,51
160,2026-05-09-20-03-22 +0000,nypost,Trump ready to ship US delegation to Moscow to...,https://nypost.com/2026/05/09/world-news/trump...,51
24,2026-05-10-14-57-57 +0000,nypost,17 Americans anxiously awaiting evacuation fro...,https://nypost.com/2026/05/10/us-news/17-ameri...,47
138,2026-05-10-00-38-46 +0000,nyt,Passengers on Hantavirus Cruise Ship Will Dise...,https://www.nytimes.com/2026/05/09/world/afric...,46

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
50,66,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
117,42,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...
154,42,2026-05-09-21-21-22 +0000,nypost,Vladimir Putin suggests war in Ukraine is ‘com...,https://nypost.com/2026/05/09/world-news/vladi...
12,35,2026-05-10-15-32-42 +0000,nypost,Kristin Smart’s remains not found at house bel...,https://nypost.com/2026/05/10/us-news/kristin-...
140,33,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
113,29,2026-05-10-07-41-36 +0000,nypost,Texas cold-case fugitive busted in Mexico as n...,https://nypost.com/2026/05/10/us-news/texas-fu...
124,27,2026-05-10-03-13-06 +0000,nypost,Trans athlete dominates California girls’ trac...,https://nypost.com/2026/05/09/us-news/trans-at...
86,26,2026-05-10-10-00-44 +0000,wapo,N.J. World Cup games will be in a county that ...,https://www.washingtonpost.com/nation/2026/05/...
13,25,2026-05-10-15-28-57 +0000,nyt,Lebanese Mourn Eight Members of One Family Kil...,https://www.nytimes.com/2026/05/10/world/middl...
84,25,2026-05-10-10-06-32 +0000,nypost,NYPD captain’s transfer after viral rant bashi...,https://nypost.com/2026/05/10/us-news/nypd-cap...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)