## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-06-19-02-00 +0000,wsj,Boston Fed President Collins Argues for Holdin...,https://www.wsj.com/economy/central-banking/bo...
1,2026-03-06-19-00-15 +0000,nyt,Live Updates: Trump Says There Will Be ‘No Dea...,https://www.nytimes.com/live/2026/03/06/world/...
2,2026-03-06-19-00-11 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/06/world/...
3,2026-03-06-19-00-06 +0000,nyt,Top National Symphony Leader Quits in New Blow...,https://www.nytimes.com/2026/03/06/arts/music/...
4,2026-03-06-18-58-55 +0000,cbc,"Alberta, Ottawa agree on deal that would see p...",https://www.cbc.ca/news/canada/calgary/alberta...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2494/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19    iran     73
10   trump     60
112    war     32
202   dies     27
27     new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
295,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...,229
380,2026-03-05-22-56-23 +0000,nypost,Trump kicks Tucker Carlson out of MAGA movemen...,https://nypost.com/2026/03/05/media/trump-kick...,199
32,2026-03-06-18-16-05 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...,197
361,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...,190
1,2026-03-06-19-00-15 +0000,nyt,Live Updates: Trump Says There Will Be ‘No Dea...,https://www.nytimes.com/live/2026/03/06/world/...,188

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
295,229,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...
401,152,2026-03-05-21-51-00 +0000,wsj,"Oil Prices Surge, Stocks Fall on Widening Iran...",https://www.wsj.com/finance/stocks/oil-prices-...
361,74,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...
32,64,2026-03-06-18-16-05 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...
294,63,2026-03-06-05-05-00 +0000,wsj,"Rep. Tony Gonzales (R., Texas) said he wouldn’...",https://www.wsj.com/politics/elections/texas-t...
14,60,2026-03-06-18-39-00 +0000,wsj,The Fed’s biggest fear has always been having ...,https://www.wsj.com/economy/central-banking/jo...
54,59,2026-03-06-17-45-01 +0000,nyt,"From 2019: Agnès Varda, Influential French New...",https://www.nytimes.com/2026/03/06/movies/agne...
64,56,2026-03-06-17-39-35 +0000,nypost,Americans stuck in Middle East open up about s...,https://nypost.com/2026/03/06/world-news/ameri...
5,49,2026-03-06-18-58-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
76,42,2026-03-06-17-27-01 +0000,nypost,California’s green gas fees set to cost more t...,https://nypost.com/2026/03/06/us-news/fees-to-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)