## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-11-18-59-04 +0000,nyt,"In the Senate, Collins Often Defies Trump but ...",https://www.nytimes.com/2026/10/11/us/politics...
1,2026-10-11-18-54-00 +0000,wsj,Opinion | Republican Senate Losses Will Hurt L...,https://www.wsj.com/opinion/republican-senate-...
2,2026-10-11-18-51-10 +0000,nyt,Flamingos at a Florida Zoo Rode Out Hurricane ...,https://www.nytimes.com/2026/10/11/us/flamingo...
3,2026-10-11-18-48-58 +0000,nypost,Nithya Raman’s LAPD shake-up could put ousted ...,https://nypost.com/2026/10/11/us-news/ousted-d...
4,2026-10-11-18-42-48 +0000,nyt,"In Unlikely Turn, Law and Order Heats Up L.A. ...",https://www.nytimes.com/2026/10/11/us/los-ange...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
4      trump     35
55       new     16
138  ukraine     15
69     saudi     12
106  airport     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
218,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...,99
171,2026-10-11-01-41-29 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...,94
75,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,92
227,2026-10-10-19-28-55 +0000,nyt,"Rebuking Ukraine Over Oil Strikes, Trump Says ...",https://www.nytimes.com/2026/10/10/world/europ...,90
49,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
218,99,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...
173,67,2026-10-11-01-08-07 +0000,wapo,"12 killed, hundreds injured in Saudi Arabia ai...",https://www.washingtonpost.com/world/2026/10/1...
92,53,2026-10-11-11-31-16 +0000,nypost,Man mauled to death by tiger was happily danci...,https://nypost.com/2026/10/11/world-news/man-m...
85,47,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
27,46,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
23,43,2026-10-11-17-47-18 +0000,cbc,Children among at least 139 dead after migrant...,https://www.cbc.ca/news/world/migrant-boat-cap...
204,36,2026-10-10-21-15-00 +0000,wsj,California Gov. Gavin Newsom has long opposed ...,https://www.wsj.com/politics/newsom-backs-meas...
153,33,2026-10-11-08-00-00 +0000,cbc,What happens when a Google data centre comes t...,https://www.cbc.ca/news/world/ai-data-centre-g...
109,30,2026-10-11-10-00-03 +0000,chitri,"Illinois Senate race: Juliana Stratton, F-bomb...",https://www.chicagotribune.com/2026/10/11/illi...
40,27,2026-10-11-16-48-36 +0000,nypost,Nearly 396K Florida and Alabama residents lose...,https://nypost.com/2026/10/11/us-news/nearly-3...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)