## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-29-11-53-12 +0000,nyt,"With Kennedy Center Closed, National Symphony ...",https://www.nytimes.com/2026/09/28/arts/music/...
1,2026-09-29-11-51-00 +0000,wsj,Oura Postpones IPO Over Market Uncertainty,https://www.wsj.com/tech/oura-postpones-ipo-ov...
2,2026-09-29-11-47-00 +0000,wsj,Dollar Rises to 2-Month High on Growing Prospe...,https://www.wsj.com/economy/central-banking/do...
3,2026-09-29-11-45-00 +0000,wapo,Brisket is missing from Texas menus. A Democra...,https://www.washingtonpost.com/politics/2026/0...
4,2026-09-29-11-36-49 +0000,nyt,The Rescuers Keeping Two Ukrainian ‘Fortress C...,https://www.nytimes.com/2026/09/29/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
105  trump     40
226    new     27
185     ai     15
295     uk     14
597    oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
233,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...,210
290,2026-09-28-19-37-09 +0000,chitri,President Trump announces a new $15B Iowa stee...,https://www.chicagotribune.com/2026/09/28/trum...,111
302,2026-09-28-19-15-55 +0000,wapo,Trump says new fuel economy rules will cut car...,https://www.washingtonpost.com/transportation/...,109
248,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...,90
206,2026-09-28-22-46-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
233,210,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...
395,70,2026-09-28-13-54-08 +0000,nypost,Farmer who foiled suspected Iran terror plot o...,https://nypost.com/2026/09/28/world-news/farme...
21,56,2026-09-29-11-00-57 +0000,chitri,News organizations ask court to bar White Hous...,https://www.chicagotribune.com/2026/09/29/news...
365,48,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
156,46,2026-09-29-03-07-25 +0000,nypost,"Trans NYT exec threatened to kill wife, scared...",https://nypost.com/2026/09/28/us-news/nyt-exec...
291,46,2026-09-28-19-37-01 +0000,latimes,Senate OKs a sweeping college sports bill. Her...,https://www.latimes.com/politics/story/2026-09...
164,46,2026-09-29-02-30-00 +0000,nypost,Hundreds of lefties link arms for bizarre ‘han...,https://nypost.com/2026/09/28/us-news/hundreds...
386,45,2026-09-28-14-22-00 +0000,wsj,Inflation in the eurozone is expected to rise ...,https://www.wsj.com/economy/central-banking/eu...
144,43,2026-09-29-04-23-18 +0000,nypost,Lone woman death row inmate Christa Pike says ...,https://nypost.com/2026/09/29/us-news/lone-wom...
105,39,2026-09-29-08-19-57 +0000,wsj,"Stock Market Today: Treasury Selloff Pauses, B...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)