## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-29-02-38-00 +0000,wsj,How Pakistan Wooed Trump and Styled Itself as ...,https://www.wsj.com/world/middle-east/pakistan...
1,2026-03-29-02-36-44 +0000,startribune,"Live: Chaska holds on, wins Class 4A title 63-...",https://www.startribune.com/minnesota-boys-bas...
2,2026-03-29-02-31-01 +0000,nypost,Hundreds pack NYC suburb to remember Loyola Un...,https://nypost.com/2026/03/28/us-news/hundreds...
3,2026-03-29-02-25-54 +0000,nyt,No Kings Protests Held Across the U.S.: Photos...,https://www.nytimes.com/2026/03/28/us/no-kings...
4,2026-03-29-02-13-11 +0000,startribune,Takeaways: Wild lose for sixth time in nine ga...,https://www.startribune.com/takeaways-wild-los...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
2   trump     21
87    war     20
7    iran     16
31     no     14
32  kings     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
88,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...,103
87,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...,81
21,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...,77
44,2026-03-28-22-48-02 +0000,bbc,No Kings protests across the US rally against ...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...,72
10,2026-03-29-01-06-22 +0000,nyt,Iran War Live Updates: U.S. Marines Arrive in ...,https://www.nytimes.com/live/2026/03/28/world/...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
88,103,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...
172,38,2026-03-28-03-51-00 +0000,wsj,President Trump signed an executive order to p...,https://www.wsj.com/politics/policy/house-gop-...
68,32,2026-03-28-20-02-09 +0000,wapo,Iran-backed Houthis in Yemen launch attack on ...,https://www.washingtonpost.com/world/2026/03/2...
8,27,2026-03-29-01-40-32 +0000,nypost,Wild San Francisco street fight shows young pu...,https://nypost.com/2026/03/28/us-news/wild-san...
87,27,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...
30,26,2026-03-29-00-00-00 +0000,wsj,Investigators searched the office of a FEMA co...,https://www.wsj.com/politics/national-security...
43,26,2026-03-28-23-00-00 +0000,wsj,President Trump’s tax cuts are delivering bigg...,https://www.wsj.com/politics/policy/trump-salt...
117,26,2026-03-28-14-53-53 +0000,nypost,NYC Mayor Zohran Mamdani’s new deputy for comm...,https://nypost.com/2026/03/28/us-news/mamdanis...
127,26,2026-03-28-13-06-30 +0000,nypost,Noa Argamani and Avinatan Or –the Israeli coup...,https://nypost.com/2026/03/28/world-news/israe...
35,24,2026-03-28-23-37-16 +0000,nypost,JD Vance wins 2028 CPAC GOP presidential straw...,https://nypost.com/2026/03/28/us-news/rubio-cu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)