## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-24-00-00-00 +0000,wsj,Trump Is Running Out of European Friends—Even ...,https://www.wsj.com/world/europe/trump-is-runn...
1,2026-06-23-23-59-30 +0000,nypost,Florida man allegedly raped teen girl then loc...,https://nypost.com/2026/06/23/us-news/florida-...
2,2026-06-23-23-58-20 +0000,nyt,U.S. and Iran Offer Conflicting Accounts of Nu...,https://www.nytimes.com/live/2026/06/23/world/...
3,2026-06-23-23-58-19 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...
4,2026-06-23-23-57-23 +0000,nypost,Bay Area hospitality group abruptly closes all...,https://nypost.com/2026/06/23/us-news/bay-area...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2623/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     38
17    iran     30
65     new     18
147     ai     18
27     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
15,2026-06-23-23-28-13 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...,128
3,2026-06-23-23-58-19 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...,121
66,2026-06-23-21-56-42 +0000,nyt,Trump Is Making Big Claims About the Iran Talk...,https://www.nytimes.com/2026/06/23/us/politics...,119
62,2026-06-23-22-01-03 +0000,nypost,Israel furious with Trump for being left out o...,https://nypost.com/2026/06/23/world-news/israe...,111
113,2026-06-23-20-30-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/policy/senate-pas...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
15,128,2026-06-23-23-28-13 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...
180,81,2026-06-23-17-41-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
325,60,2026-06-23-09-00-00 +0000,wsj,A generational battle is playing out in the De...,https://www.wsj.com/politics/elections/the-gen...
120,47,2026-06-23-20-15-44 +0000,nyt,"As Chinese Tech Pulls Ahead, U.S. Fears It Wil...",https://www.nytimes.com/2026/06/23/business/ec...
14,46,2026-06-23-23-29-25 +0000,latimes,Family says police fatally shot teen during me...,https://www.latimes.com/california/story/2026-...
75,41,2026-06-23-21-41-53 +0000,nypost,‘Amazing’ security guard fights off masked pun...,https://nypost.com/2026/06/23/us-news/amazing-...
229,41,2026-06-23-15-41-52 +0000,latimes,Inmates may not sue prison officials who viola...,https://www.latimes.com/politics/story/2026-06...
123,39,2026-06-23-20-12-41 +0000,latimes,Savannah Guthrie tearfully pleads for help aft...,https://www.latimes.com/california/story/2026-...
143,39,2026-06-23-19-17-40 +0000,nypost,"Montreal shooter ranted about Zionists, capita...",https://nypost.com/2026/06/23/world-news/montr...
139,39,2026-06-23-19-26-27 +0000,cbc,Ronaldo makes World Cup history with 2-goal ef...,https://www.cbc.ca/sports/soccer/worldcup/fifa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)