## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-17-05-58 +0000,nyt,Iran Live Updates: Global Markets Tumble After...,https://www.nytimes.com/live/2026/03/03/world/...
1,2026-03-03-17-05-24 +0000,nyt,A Danish Program Takes On the Stigma of Mental...,https://www.nytimes.com/2026/03/03/health/ment...
2,2026-03-03-17-05-00 +0000,missionlocal,SF celebrates 50 years of punk at iconic Mabuh...,https://missionlocal.org/2026/03/sf-celebrates...
3,2026-03-03-17-01-55 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/03/world/...
4,2026-03-03-17-01-03 +0000,nypost,Georgia father who gifted gun to alleged schoo...,https://nypost.com/2026/03/03/us-news/georgia-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     93
83    trump     59
7       war     41
41  strikes     25
45      oil     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
366,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,321
363,2026-03-02-20-15-54 +0000,nypost,Trump ordered Iran war — then ordered ‘hamburg...,https://nypost.com/2026/03/02/us-news/trump-or...,237
405,2026-03-02-18-15-39 +0000,latimes,News Analysis: Trump is rewriting the 'you bre...,https://www.latimes.com/politics/story/2026-03...,218
253,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...,217
371,2026-03-02-19-47-40 +0000,nypost,UK Prime Minister Starmer hits back at Trump o...,https://nypost.com/2026/03/02/world-news/uk-pr...,211

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
366,321,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
300,89,2026-03-02-22-57-08 +0000,nyt,Iranian Strikes Hit Qatar and Saudi Energy Sit...,https://www.nytimes.com/2026/03/02/world/middl...
175,78,2026-03-03-10-30-00 +0000,wsj,Americans weary of high prices have recently b...,https://www.wsj.com/business/energy-oil/what-t...
91,64,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
34,52,2026-03-03-16-24-27 +0000,wapo,Live updates: Iran strikes prompt closure of U...,https://www.washingtonpost.com/world/2026/03/0...
270,52,2026-03-03-00-45-00 +0000,wsj,Here are some key moments from the depositions...,https://www.wsj.com/politics/bill-hillary-clin...
16,48,2026-03-03-16-45-40 +0000,startribune,"1 of 3 people killed in Austin, Texas, mass sh...",https://www.startribune.com/1-of-3-people-kill...
278,46,2026-03-03-00-15-58 +0000,nypost,Supreme Court blocks California law that stopp...,https://nypost.com/2026/03/02/us-news/supreme-...
229,44,2026-03-03-03-42-00 +0000,wsj,Asian Government Bonds Fall as Middle East Con...,https://www.wsj.com/finance/investing/asian-go...
368,41,2026-03-02-20-02-51 +0000,nypost,US military blasts Iranian warship in new vide...,https://nypost.com/2026/03/02/world-news/us-mi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)