## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-17-14-59-24 +0000,nyt,Trump Lashes Out as Preliminary Deal With Iran...,https://www.nytimes.com/2026/08/17/us/politics...
1,2026-08-17-14-59-02 +0000,bbc,Trump threatens to bomb Oman if it 'gets in th...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...
2,2026-08-17-14-58-16 +0000,nypost,Melania Trump reunites 34th Ukrainian child wi...,https://nypost.com/2026/08/17/us-news/melania-...
3,2026-08-17-14-51-19 +0000,nyt,Killings Plunge in a City Once Known for Violence,https://www.nytimes.com/2026/08/17/us/baltimor...
4,2026-08-17-14-47-44 +0000,nypost,"US tourist struck by lightning, dies hiking ac...",https://nypost.com/2026/08/17/world-news/touri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2443/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     38
5     iran     18
287    new     13
217  south     12
177    war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
100,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,125
153,2026-08-17-06-24-31 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,115
182,2026-08-17-00-20-54 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,91
200,2026-08-16-21-57-01 +0000,nypost,Trump instructs Pentagon to reduce military ex...,https://nypost.com/2026/08/16/world-news/trump...,84
154,2026-08-17-06-16-21 +0000,nyt,Trump Orders Pentagon to Curtail Military Exer...,https://www.nytimes.com/2026/08/16/us/politics...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
100,125,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
81,58,2026-08-17-11-03-00 +0000,wsj,One of the most sensitive stories in this near...,https://www.wsj.com/politics/pentagon-rotates-...
254,43,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...
251,42,2026-08-16-17-50-32 +0000,chitri,US envoy Kushner meets Hamas’ leader in push f...,https://www.chicagotribune.com/2026/08/16/kush...
152,34,2026-08-17-06-49-53 +0000,nypost,"Louisiana husband allegedly killed wife, propp...",https://nypost.com/2026/08/17/us-news/louisian...
68,33,2026-08-17-11-57-08 +0000,nypost,Trump warns US will ‘bomb the s–t’ out of Oman...,https://nypost.com/2026/08/17/us-news/trump-wa...
268,30,2026-08-16-15-19-52 +0000,nypost,Ex-Mamdani campaign staffer makes outrageous c...,https://nypost.com/2026/08/16/us-news/ex-mamda...
23,29,2026-08-17-14-08-10 +0000,nypost,Listen to Hayden Panettiere 911 dispatch audio...,https://nypost.com/2026/08/17/us-news/hayden-p...
137,28,2026-08-17-08-42-01 +0000,cbc,Major energy announcement coming as prime mini...,https://www.cbc.ca/news/canada/newfoundland-la...
190,28,2026-08-16-23-21-37 +0000,bbc,'I want my brother back' - Tupac’s brother tel...,https://www.bbc.co.uk/news/videos/cj4kglpl55lo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)