## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-16-14-47 +0000,nypost,Cops fire on suspect with a weapon during rush...,https://nypost.com/2026/06/11/us-news/cops-fir...
1,2026-06-11-16-14-42 +0000,nyt,Iran War Live Updates: U.S.-Iran Strikes Risk ...,https://www.nytimes.com/live/2026/06/11/world/...
2,2026-06-11-16-13-00 +0000,wsj,Opening of U.S.-Canada Bridge Delayed Due to T...,https://www.wsj.com/world/americas/opening-of-...
3,2026-06-11-16-12-00 +0000,nypost,Everything is bigger in Texas — including its ...,https://nypost.com/2026/06/11/us-news/everythi...
4,2026-06-11-16-10-42 +0000,nyt,Vance Boelter Pleads Guilty in Assassination o...,https://www.nytimes.com/2026/06/11/us/minnesot...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41   trump     38
8     iran     35
15     new     29
123  world     25
124    cup     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
308,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...,144
1,2026-06-11-16-14-42 +0000,nyt,Iran War Live Updates: U.S.-Iran Strikes Risk ...,https://www.nytimes.com/live/2026/06/11/world/...,140
323,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...,134
266,2026-06-10-21-48-11 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,134
53,2026-06-11-14-58-13 +0000,nyt,Oil Prices Fluctuate as Trump Issues New Threa...,https://www.nytimes.com/2026/06/10/business/oi...,131

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
308,144,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...
323,99,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...
322,78,2026-06-10-19-31-12 +0000,latimes,L.A. is hosting free World Cup watch parties a...,https://www.latimes.com/california/story/2026-...
133,55,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...
286,51,2026-06-10-21-09-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...
72,41,2026-06-11-14-13-32 +0000,bbc,SpaceX's stock market blast-off could be Musk'...,https://www.bbc.com/news/articles/cy8d9e4lzv1o...
50,38,2026-06-11-15-00-00 +0000,nypost,First car show since devastating Palisades Fir...,https://nypost.com/2026/06/11/us-news/pacific-...
115,36,2026-06-11-12-46-03 +0000,nypost,Trump says US ‘will be taking Kharg Island’ oi...,https://nypost.com/2026/06/11/us-news/trump-sa...
149,34,2026-06-11-10-14-05 +0000,nypost,House Dem lashes out at GOP efforts to probe f...,https://nypost.com/2026/06/11/us-news/house-de...
11,34,2026-06-11-16-01-20 +0000,latimes,LA County DA claims four in five cases in $4 b...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)