## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-18-52-00 +0000,wsj,The controversy over Sen. John Fetterman’s sur...,https://www.wsj.com/politics/elections/sen-joh...
1,2026-09-10-18-50-06 +0000,wapo,"At least 1,000 ‘forgotten children’ who died i...",https://www.washingtonpost.com/nation/2026/09/...
2,2026-09-10-18-49-27 +0000,wapo,Sending armed ICE agents to polling places wou...,https://www.washingtonpost.com/politics/2026/0...
3,2026-09-10-18-47-24 +0000,nypost,New Cesar Chavez accuser claims California lab...,https://nypost.com/2026/09/10/us-news/new-sexu...
4,2026-09-10-18-47-10 +0000,nyt,Moscow Claims Ukraine Planned to Start a War B...,https://www.nytimes.com/2026/09/10/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
63       trump     67
33         new     28
9   convention     21
48         war     19
7          gop     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
295,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...,180
108,2026-09-10-16-04-45 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...,177
213,2026-09-10-10-55-00 +0000,wsj,There were scores of empty seats at the RNC co...,https://www.wsj.com/politics/if-trump-cant-fil...,151
288,2026-09-10-04-16-36 +0000,wapo,"Trump makes case for Iran war, promises $5,000...",https://www.washingtonpost.com/politics/2026/0...,148
280,2026-09-10-05-09-24 +0000,nyt,Republican Senate Candidates Avoid Tariffs and...,https://www.nytimes.com/2026/09/09/us/politics...,146

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
295,180,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...
74,81,2026-09-10-16-52-51 +0000,wapo,New Mexico leaders ask Apple and Google not to...,https://www.washingtonpost.com/politics/2026/0...
321,70,2026-09-10-01-35-35 +0000,nyt,"“You know, we had zero for the last — zero peo...",https://www.nytimes.com/live/2026/09/09/us/rnc...
427,69,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI-safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
248,67,2026-09-10-09-30-00 +0000,nypost,Charlie Kirk’s murder left a void that will ‘1...,https://nypost.com/2026/09/10/us-news/charlie-...
142,66,2026-09-10-14-44-00 +0000,wsj,"Saudi Oil Output Slumps as Iran War, Houthi Th...",https://www.wsj.com/business/energy-oil/opec-f...
153,64,2026-09-10-14-00-00 +0000,wsj,Home sales in August fell to their lowest leve...,https://www.wsj.com/economy/housing/home-sales...
326,62,2026-09-10-01-23-43 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
92,57,2026-09-10-16-31-30 +0000,bbc,Pilot warned Amazon cargo plane going too fast...,https://www.bbc.co.uk/news/articles/cj4jynv59d...
333,57,2026-09-10-01-00-00 +0000,wsj,The Fed’s next rate decision could hinge on Fr...,https://www.wsj.com/economy/central-banking/in...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)