## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-26-20-31-02 +0000,nyt,Live Updates: Hundreds Missing as Wall of Wate...,https://www.nytimes.com/live/2026/08/26/world/...
1,2026-08-26-20-31-00 +0000,wapo,Judge lifts block on Trump changes to mail vot...,https://www.washingtonpost.com/politics/2026/0...
2,2026-08-26-20-29-56 +0000,nyt,Judge Sides With Texas Over Minnesota on Extra...,https://www.nytimes.com/2026/08/26/us/ice-chri...
3,2026-08-26-20-29-00 +0000,wsj,Nvidia’s Blowout Second Quarter Leaves Investo...,https://www.wsj.com/tech/nvidia-earnings-q2-20...
4,2026-08-26-20-24-22 +0000,startribune,Judge rules ICE agent arrested for shooting in...,https://www.startribune.com/judge-rules-ice-ag...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2312/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
14    trump     40
280  parton     19
279   dolly     19
209   trade     19
363  canada     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
304,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...,139
272,2026-08-26-09-03-57 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,137
321,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...,125
309,2026-08-26-03-02-19 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,124
328,2026-08-26-01-02-53 +0000,nyt,"Darline Graham, Backed By Trump, Wins Primary ...",https://www.nytimes.com/2026/08/25/us/politics...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
304,139,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...
265,98,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...
321,85,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...
59,69,2026-08-26-18-55-31 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
145,67,2026-08-26-15-20-00 +0000,wapo,Judge channels Dolly Parton in blocking Texas ...,https://www.washingtonpost.com/nation/2026/08/...
89,58,2026-08-26-17-51-37 +0000,nypost,Pro-life group offers to pay legal fees for ac...,https://nypost.com/2026/08/26/us-news/pro-life...
7,51,2026-08-26-20-22-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
47,50,2026-08-26-19-14-31 +0000,wapo,"Scores dead, hundreds missing in flash floods ...",https://www.washingtonpost.com/world/2026/08/2...
195,50,2026-08-26-12-50-33 +0000,chitri,Iran warns of military ship ban in Hormuz unde...,https://www.chicagotribune.com/2026/08/26/iran...
161,38,2026-08-26-14-42-03 +0000,bbc,Door was locked at Pakistan hospital where fir...,https://www.bbc.co.uk/news/articles/czdz13elez...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)