## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-00-15-23 +0000,nypost,DeSantis announces closure of Alligator Alcatr...,https://nypost.com/2026/06/25/us-news/desantis...
1,2026-06-26-00-13-39 +0000,nypost,Bizarre jury twist in trial of accused Palisad...,https://nypost.com/2026/06/25/us-news/jury-in-...
2,2026-06-26-00-06-45 +0000,bbc,Paris restricts alcohol consumption and sales ...,https://www.bbc.co.uk/news/articles/cwy0pdq89z...
3,2026-06-26-00-04-03 +0000,nyt,Venezuela Live Updates: Search for Survivors G...,https://www.nytimes.com/live/2026/06/25/world/...
4,2026-06-26-00-03-00 +0000,wsj,Oil Futures Fall on Likely Technical Correction,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
64       trump     38
333        new     27
95       court     25
28   venezuela     24
443    supreme     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
248,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...,127
235,2026-06-25-14-49-39 +0000,latimes,"Trump may end legal protection for 350,000 Hai...",https://www.latimes.com/politics/story/2026-06...,120
55,2026-06-25-22-10-20 +0000,nyt,Supreme Court Expands Trump’s Power Over Immig...,https://www.nytimes.com/2026/06/25/us/politics...,110
189,2026-06-25-17-06-15 +0000,nyt,Supreme Court Allows Trump to Block Asylum See...,https://www.nytimes.com/2026/06/25/us/politics...,106
242,2026-06-25-14-39-46 +0000,nypost,Supreme Court rules Trump can remove deportati...,https://nypost.com/2026/06/25/us-news/supreme-...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
248,127,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...
40,93,2026-06-25-22-54-42 +0000,nypost,New York state orders new school election afte...,https://nypost.com/2026/06/25/us-news/new-york...
392,75,2026-06-25-01-33-43 +0000,cbc,Venezuela earthquakes: Canada will provide $5M...,https://www.cbc.ca/news/world/livestory/venezu...
171,63,2026-06-25-17-59-55 +0000,nyt,Inflation Accelerated in May as Iran War Pushe...,https://www.nytimes.com/2026/06/25/business/in...
379,53,2026-06-25-03-22-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
141,45,2026-06-25-19-19-12 +0000,bbc,UN pauses Strait of Hormuz evacuation plan aft...,https://www.bbc.co.uk/news/articles/cjwg9np904...
188,44,2026-06-25-17-10-22 +0000,nyt,See Record-Breaking Extreme Heat Wave Across E...,https://www.nytimes.com/2026/06/24/world/europ...
236,43,2026-06-25-14-48-37 +0000,nypost,Apple hikes prices by as much as $500 due to m...,https://nypost.com/2026/06/25/business/apple-h...
318,36,2026-06-25-10-12-04 +0000,bbc,Celebrations as South Africa reach World Cup k...,https://www.bbc.co.uk/news/videos/cr5je3rgpq6o...
109,34,2026-06-25-20-56-00 +0000,wsj,The Florida immigration-detention center known...,https://www.wsj.com/politics/policy/floridas-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)