## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-17-10-18 +0000,nyt,Iran War Live Updates: B-52s Start Flying Miss...,https://www.nytimes.com/live/2026/03/31/world/...
1,2026-03-31-17-07-16 +0000,nyt,TMZ Sics Its Tipsters on a New Breed of Celebr...,https://www.nytimes.com/2026/03/31/us/politics...
2,2026-03-31-17-06-43 +0000,nyt,U.S. Assures Colombian President Petro He Does...,https://www.nytimes.com/2026/03/31/world/ameri...
3,2026-03-31-17-06-17 +0000,startribune,The pelican survived Lake Superior’s cold — bu...,https://www.startribune.com/ashland-wi-pelican...
4,2026-03-31-17-06-05 +0000,bbc,"King's state visit to US to go ahead in April,...",https://www.bbc.com/news/articles/cjd8nkezdyxo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     51
41    trump     44
1       war     37
137     oil     18
49   prices     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
80,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...,182
5,2026-03-31-17-05-02 +0000,startribune,Trump lashes out at allies as Iran war and str...,https://www.startribune.com/us-attacks-iranian...,181
0,2026-03-31-17-10-18 +0000,nyt,Iran War Live Updates: B-52s Start Flying Miss...,https://www.nytimes.com/live/2026/03/31/world/...,150
125,2026-03-31-13-02-00 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,146
47,2026-03-31-16-05-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
80,182,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...
97,70,2026-03-31-14-14-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
212,53,2026-03-31-07-40-08 +0000,wsj,Stock Market Today: Dow Advances on Hopes War ...,https://www.wsj.com/livecoverage/stock-market-...
31,51,2026-03-31-16-30-02 +0000,startribune,Supreme Court rules against Colorado ban on ‘c...,https://www.startribune.com/supreme-court-rule...
154,51,2026-03-31-11-03-31 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
325,45,2026-03-30-20-18-59 +0000,nypost,Fed’s Powell says no need to hike interest rat...,https://nypost.com/2026/03/30/business/feds-po...
150,40,2026-03-31-11-26-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
206,39,2026-03-31-08-02-03 +0000,nypost,Iran strikes Kuwaiti oil tanker in drone attac...,https://nypost.com/2026/03/31/world-news/iran-...
315,38,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...
81,35,2026-03-31-14-55-27 +0000,nypost,Lefty SF Supervisor had been absent for severa...,https://nypost.com/2026/03/31/us-news/sf-super...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)