## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-27-21-12-51 +0000,bbc,'Every person saved is a miracle': Families ca...,https://www.bbc.co.uk/news/articles/cp8l451420...
1,2026-06-27-21-11-54 +0000,nypost,Ukraine pummels key oil hub supplying Moscow f...,https://nypost.com/2026/06/27/world-news/ukrai...
2,2026-06-27-21-10-22 +0000,nyt,Trump Taps Former Oklahoma Trooper as New ICE ...,https://www.nytimes.com/2026/06/27/us/politics...
3,2026-06-27-21-02-09 +0000,latimes,"Before Venezuela earthquakes, engineers warned...",https://www.latimes.com/california/story/2026-...
4,2026-06-27-21-01-57 +0000,nypost,"Venezuela death toll tops 1,400 — with rising ...",https://nypost.com/2026/06/27/world-news/venez...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
10    venezuela     25
63         iran     16
26        trump     15
35  earthquakes     11
59        world      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...,63
171,2026-06-27-00-52-00 +0000,wsj,Venezuela’s Earthquakes Test Trump’s Bet on De...,https://www.wsj.com/world/americas/venezuelas-...,62
85,2026-06-27-13-53-33 +0000,nypost,Heartwarming video shows moment firefighters r...,https://nypost.com/2026/06/27/world-news/video...,57
73,2026-06-27-15-00-48 +0000,nypost,Miracle baby born on street beside earthquake ...,https://nypost.com/2026/06/27/world-news/mirac...,53
217,2026-06-26-21-44-54 +0000,bbc,"Watch: BBC reports from La Guaira, one of Vene...",https://www.bbc.co.uk/news/videos/cwy0lw84p3go...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,63,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...
144,47,2026-06-27-07-03-45 +0000,nyt,"At World Cup, Iran-Egypt ‘Pride Match’ Stirs C...",https://www.nytimes.com/2026/06/27/us/world-cu...
11,46,2026-06-27-20-34-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...
169,36,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
221,35,2026-06-26-21-41-00 +0000,wsj,Millions of people who signed up for Affordabl...,https://www.wsj.com/politics/policy/millions-o...
61,33,2026-06-27-17-01-45 +0000,bbc,Burnham will need a Moscow test as well as Mak...,https://www.bbc.co.uk/news/articles/cdxdwr0xk5...
73,28,2026-06-27-15-00-48 +0000,nypost,Miracle baby born on street beside earthquake ...,https://nypost.com/2026/06/27/world-news/mirac...
51,28,2026-06-27-17-43-18 +0000,nypost,Knicks slap Mamdani-backed NY Senate candidate...,https://nypost.com/2026/06/27/us-news/knicks-s...
212,28,2026-06-26-21-52-00 +0000,wsj,U.S. Strikes Iran After Its Attack on Ship in ...,https://www.wsj.com/arts-culture/books/u-s-str...
27,26,2026-06-27-19-42-41 +0000,nypost,Wild drone footage capture great white feeding...,https://nypost.com/2026/06/27/us-news/wild-dro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)