## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-02-19-56-49 +0000,nyt,Iran War Live Updates: Lebanon Peace Talks Res...,https://www.nytimes.com/live/2026/06/02/world/...
1,2026-06-02-19-54-47 +0000,nyt,Blanche Expected to Address Concerns Over $1.8...,https://www.nytimes.com/2026/06/02/us/politics...
2,2026-06-02-19-54-29 +0000,nyt,Immigration Bill Teeters as G.O.P. Awaits Clar...,https://www.nytimes.com/2026/06/02/us/politics...
3,2026-06-02-19-52-14 +0000,nypost,Anti-Israel Texas businessman bankrolling PAC ...,https://nypost.com/2026/06/02/us-news/anti-isr...
4,2026-06-02-19-51-03 +0000,nyt,Trans Minors Sue to Stop Justice Department Ac...,https://www.nytimes.com/2026/06/02/us/transgen...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
23        trump     41
202  california     25
103         new     24
0          iran     19
212        race     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
277,2026-06-02-01-21-18 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...,112
280,2026-06-02-01-15-00 +0000,nypost,Steve Hilton says it’s ‘now or never for Calif...,https://nypost.com/2026/06/01/us-news/steve-hi...,107
84,2026-06-02-17-01-30 +0000,nypost,Trump will attend new White House Corresponden...,https://nypost.com/2026/06/02/us-news/white-ho...,107
18,2026-06-02-19-24-00 +0000,wsj,Republican leaders say they believe the Trump ...,https://www.wsj.com/politics/policy/gop-leader...,105
66,2026-06-02-17-39-00 +0000,nypost,"Steve Hilton gets backing from JD Vance, Donal...",https://nypost.com/2026/06/02/us-news/steve-hi...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
277,112,2026-06-02-01-21-18 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...
229,78,2026-06-02-09-02-22 +0000,nyt,California Primary Elections: What to Watch in...,https://www.nytimes.com/2026/06/02/us/election...
0,63,2026-06-02-19-56-49 +0000,nyt,Iran War Live Updates: Lebanon Peace Talks Res...,https://www.nytimes.com/live/2026/06/02/world/...
125,61,2026-06-02-15-58-23 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
74,57,2026-06-02-17-23-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...
18,53,2026-06-02-19-24-00 +0000,wsj,Republican leaders say they believe the Trump ...,https://www.wsj.com/politics/policy/gop-leader...
164,44,2026-06-02-14-16-45 +0000,nypost,Jill Biden claims White House docs ‘missed’ Jo...,https://nypost.com/2026/06/02/us-news/jill-bid...
359,42,2026-06-01-20-34-11 +0000,nypost,NJ congressional candidate Adam Hamawy ‘lied’ ...,https://nypost.com/2026/06/01/world-news/nj-co...
281,36,2026-06-02-01-10-00 +0000,cbc,"At least 22 dead, dozens wounded as Russia lau...",https://www.cbc.ca/news/world/kyiv-attack-russ...
57,36,2026-06-02-17-56-48 +0000,nypost,Art influencer Jerry Gogosian posted haunting ...,https://nypost.com/2026/06/02/us-news/haunting...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)