## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-12-20-59-00 +0000,wsj,Lennar First-Quarter Sales Fall as Tough Housi...,https://www.wsj.com/business/earnings/lennar-f...
1,2026-03-12-20-58-28 +0000,startribune,Live: Benilde-St. Margaret’s defeats Marshall ...,https://www.startribune.com/mn-girls-basketbal...
2,2026-03-12-20-57-33 +0000,nyt,"Drone Strike in Congo Kills 3, Including U.N. ...",https://www.nytimes.com/2026/03/12/world/afric...
3,2026-03-12-20-56-57 +0000,nyt,Iran War Live Updates: Israel Bombs Central Be...,https://www.nytimes.com/live/2026/03/12/world/...
4,2026-03-12-20-56-00 +0000,wsj,Suspect Who Rammed Vehicle Into Michigan Synag...,https://www.wsj.com/us-news/michigan-synagogue...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
24    iran     59
25     war     38
38     oil     38
116  trump     37
106    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...,201
327,2026-03-12-01-39-01 +0000,wapo,Nations agree to release oil reserves as war i...,https://www.washingtonpost.com/world/2026/03/1...,166
189,2026-03-12-13-57-56 +0000,bbc,How Iran war laid bare the world's reliance on...,https://www.bbc.com/news/articles/c15x1y8d37vo...,161
83,2026-03-12-18-08-03 +0000,nyt,Fallout From Iran War and Oil Shock Deliver An...,https://www.nytimes.com/2026/03/12/business/ec...,157
169,2026-03-12-15-11-14 +0000,nypost,"Dow falls over 700 points, oil hits $100 as Ir...",https://nypost.com/2026/03/12/business/dow-fal...,149

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,201,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...
82,81,2026-03-12-18-14-00 +0000,wsj,When Kash Patel said in one of his first video...,https://www.wsj.com/politics/policy/ufc-fighte...
384,75,2026-03-11-22-06-00 +0000,wsj,"Commercial ships near Strait or Hormuz hit, ne...",https://www.wsj.com/politics/policy/commercial...
345,62,2026-03-12-00-28-08 +0000,nypost,Two oil tankers explode – leaving at least 1 p...,https://nypost.com/2026/03/11/world-news/two-o...
321,58,2026-03-12-02-38-00 +0000,wsj,"In a matter of hours, the White House changed ...",https://www.wsj.com/business/energy-oil/presid...
64,48,2026-03-12-19-20-20 +0000,cbc,Israeli military drops charges against soldier...,https://www.cbc.ca/news/world/israel-drops-cha...
185,43,2026-03-12-14-03-00 +0000,wsj,Sen. John Cornyn of Texas reversed himself and...,https://www.wsj.com/politics/policy/john-corny...
363,42,2026-03-11-23-14-21 +0000,nyt,World Leaders Will Release 400 Million Barrels...,https://www.nytimes.com/2026/03/11/business/en...
227,38,2026-03-12-11-10-00 +0000,wsj,There are now enough lawmakers refusing to run...,https://www.wsj.com/politics/clyburn-85-might-...
110,38,2026-03-12-17-13-40 +0000,nypost,Iran supreme leader Mojtaba Khamenei had chill...,https://nypost.com/2026/03/12/world-news/iran-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)