## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-10-03-22 +0000,nyt,"Iran Made Secret Outreach After Strikes, Highl...",https://www.nytimes.com/2026/03/04/us/politics...
1,2026-03-04-10-03-19 +0000,nyt,"On Iran, Vance Balances Between Trump and the ...",https://www.nytimes.com/2026/03/04/us/politics...
2,2026-03-04-10-03-08 +0000,nyt,"After U.S. Attacks on Iran, FIFA Grapples With...",https://www.nytimes.com/2026/03/04/world/middl...
3,2026-03-04-10-02-25 +0000,nypost,Israeli stealth fighter shoots down Iranian je...,https://nypost.com/2026/03/04/world-news/israe...
4,2026-03-04-10-01-59 +0000,nyt,Global Leaders Brace for the Fallout From Trum...,https://www.nytimes.com/2026/03/04/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     92
6     trump     48
41      war     36
50    texas     29
4   strikes     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
22,2026-03-04-09-16-06 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...,236
275,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,203
12,2026-03-04-09-58-00 +0000,wsj,Spain’s Sanchez Reiterates Opposition to Iran ...,https://www.wsj.com/world/europe/spains-sanche...,202
347,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...,195
349,2026-03-03-17-41-27 +0000,nypost,Trump shares ‘worst case’ scenario of someone ...,https://nypost.com/2026/03/03/us-news/trump-sa...,190

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
22,236,2026-03-04-09-16-06 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...
233,132,2026-03-03-22-25-24 +0000,latimes,"Oil jumps, stocks fall, as Trump presses into ...",https://www.latimes.com/politics/story/2026-03...
106,116,2026-03-04-04-03-33 +0000,nypost,Complaining Rep. Jasmine Crockett leaves own T...,https://nypost.com/2026/03/03/us-news/rep-jasm...
258,88,2026-03-03-21-42-00 +0000,wsj,Minneapolis Fed President Neel Kashkari said t...,https://www.wsj.com/economy/central-banking/ka...
3,68,2026-03-04-10-02-25 +0000,nypost,Israeli stealth fighter shoots down Iranian je...,https://nypost.com/2026/03/04/world-news/israe...
103,67,2026-03-04-04-41-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
395,61,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
353,55,2026-03-03-17-28-00 +0000,wsj,U.S. Troops Killed in Kuwait Had No Warning of...,https://www.wsj.com/world/middle-east/u-s-troo...
116,52,2026-03-04-03-44-09 +0000,nyt,"Beyond a Trade War, China, Japan and Others in...",https://www.nytimes.com/2026/03/02/business/us...
248,43,2026-03-03-22-10-00 +0000,wsj,Middle East Conflict Circles the World’s Marke...,https://www.wsj.com/finance/stocks/middle-east...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)