## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-07-23-00 +0000,wsj,Oil Falls After Trump Strikes Deal With Russia...,https://www.wsj.com/finance/commodities-future...
1,2026-10-12-07-22-00 +0000,wsj,Volkswagen Vehicle Deliveries Fall on Continue...,https://www.wsj.com/business/autos/volkswagen-...
2,2026-10-12-07-18-00 +0000,wsj,Rupee Jumps After India Central Bank Unveils C...,https://www.wsj.com/finance/currencies/rupee-j...
3,2026-10-12-07-17-00 +0000,wsj,China’s Auto Sales Fall Despite Traditional Pe...,https://www.wsj.com/business/autos/chinas-auto...
4,2026-10-12-07-15-18 +0000,bbc,Healey faces £35bn Budget challenge to meet sp...,https://www.bbc.co.uk/news/articles/cm78pwdp3n...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2575/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
2      trump     36
5     russia     12
555  airport     11
736     will     10
181      out     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
163,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,91
154,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,83
143,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,81
162,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...,80
124,2026-10-11-18-10-58 +0000,chitri,Pres. Donald Trump says Russia and Ukraine rea...,https://www.chicagotribune.com/2026/10/11/trum...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
163,91,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...
154,47,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...
173,46,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
131,42,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
179,38,2026-10-11-11-31-16 +0000,nypost,Man mauled to death by tiger was happily danci...,https://nypost.com/2026/10/11/world-news/man-m...
193,36,2026-10-11-10-00-03 +0000,chitri,"Illinois Senate race: Juliana Stratton, F-bomb...",https://www.chicagotribune.com/2026/10/11/illi...
81,28,2026-10-11-22-01-48 +0000,nypost,Roaring flash floods wipe out entire bridge in...,https://nypost.com/2026/10/11/world-news/flash...
231,28,2026-10-11-08-55-27 +0000,nyt,"Saudi Arabia’s Riyadh Airport Attacked Again, ...",https://www.nytimes.com/2026/10/10/world/middl...
218,26,2026-10-11-09-07-31 +0000,nypost,Poland says police got information about possi...,https://nypost.com/2026/10/11/world-news/polan...
192,26,2026-10-11-10-00-14 +0000,chitri,A North Side race tests competing visions for ...,https://www.chicagotribune.com/2026/10/11/chic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)