## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-16-16-19-05 +0000,bbc,MoD investigating reports Russian warship fire...,https://www.bbc.com/news/articles/c20yzm84r7lo...
1,2026-06-16-16-17-28 +0000,nypost,"Stretch of 60 Freeway remains closed, evacuati...",https://nypost.com/2026/06/16/us-news/shore-fi...
2,2026-06-16-16-17-11 +0000,nyt,The Iran War Permanently Altered the Global Ec...,https://www.nytimes.com/2026/06/16/business/ec...
3,2026-06-16-16-14-27 +0000,nyt,Russian Navy Ship Accused of Firing Warning Sh...,https://www.nytimes.com/2026/06/16/world/europ...
4,2026-06-16-16-14-13 +0000,nypost,Knicks turncoat who sold ‘fanhood’ on eBay rev...,https://nypost.com/2026/06/16/us-news/knicks-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
85   trump     58
22    iran     52
86    deal     39
128    new     20
23     war     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-06-16-01-00-00 +0000,wsj,"In one weekend, President Trump veered from th...",https://www.wsj.com/world/middle-east/trump-ir...,210
360,2026-06-15-17-34-00 +0000,wsj,Trump Says Strait of Hormuz Will Be Fully Open...,https://www.wsj.com/world/middle-east/question...,203
352,2026-06-15-18-27-23 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,197
56,2026-06-16-14-52-36 +0000,nypost,Trump says he’ll read the text of Iran deal al...,https://nypost.com/2026/06/16/us-news/trump-sa...,176
49,2026-06-16-15-06-14 +0000,nypost,Trump admin rejected Israel’s request to see I...,https://nypost.com/2026/06/16/us-news/trump-ad...,175

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,210,2026-06-16-01-00-00 +0000,wsj,"In one weekend, President Trump veered from th...",https://www.wsj.com/world/middle-east/trump-ir...
232,80,2026-06-16-00-57-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
17,66,2026-06-16-15-55-16 +0000,nypost,Dog dating app sniffs out new furry friends — ...,https://nypost.com/2026/06/16/lifestyle/dog-da...
72,55,2026-06-16-14-19-50 +0000,bbc,UK will play full part in reopening Strait of ...,https://www.bbc.com/news/articles/cvgj1g6e5d3o...
369,54,2026-06-15-17-14-33 +0000,nypost,Top Anthropic staffers rush to DC in bid to re...,https://nypost.com/2026/06/15/business/top-ant...
183,51,2026-06-16-09-00-00 +0000,wsj,The Liberty Justice Center won its biggest-eve...,https://www.wsj.com/politics/policy/how-a-cons...
200,47,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
74,42,2026-06-16-14-18-26 +0000,nypost,"Missing California girl, 5, found in Mexico af...",https://nypost.com/2026/06/16/us-news/missing-...
168,42,2026-06-16-09-42-29 +0000,nypost,Macron tells Zelensky he had ‘difficult’ meeti...,https://nypost.com/2026/06/16/us-news/macron-s...
245,41,2026-06-15-23-29-08 +0000,cbc,Ghana takes Thomas Partey's World Cup entry fi...,https://www.cbc.ca/sports/soccer/worldcup/thom...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)