## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-17-14-19-08 +0000,nyt,Live Updates: Thousands of Lebanese Try to Hea...,https://www.nytimes.com/live/2026/04/17/world/...
1,2026-04-17-14-18-33 +0000,nyt,Iran War Live Updates: Iran Declares Strait ‘O...,https://www.nytimes.com/live/2026/04/17/world/...
2,2026-04-17-14-18-18 +0000,bbc,Three charged with arson on Persian media offi...,https://www.bbc.com/news/articles/cwyv24lx1r8o...
3,2026-04-17-14-17-31 +0000,nyt,Israel-Lebanon Cease-Fire: What to Know,https://www.nytimes.com/2026/04/17/world/middl...
4,2026-04-17-14-17-00 +0000,wsj,San Diego Padres to be Sold for an MLB-Record ...,https://www.wsj.com/sports/baseball/san-diego-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2456/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     52
9      iran     42
10      war     22
7   lebanon     19
26     fire     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-17-14-18-33 +0000,nyt,Iran War Live Updates: Iran Declares Strait ‘O...,https://www.nytimes.com/live/2026/04/17/world/...,215
109,2026-04-17-09-02-18 +0000,cbc,10-day ceasefire in Lebanon takes effect as Tr...,https://www.cbc.ca/news/world/lebanon-israel-c...,166
29,2026-04-17-13-17-05 +0000,nypost,Strait of Hormuz ‘completely open’ until cease...,https://nypost.com/2026/04/17/world-news/strai...,147
148,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,141
137,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,215,2026-04-17-14-18-33 +0000,nyt,Iran War Live Updates: Iran Declares Strait ‘O...,https://www.nytimes.com/live/2026/04/17/world/...
29,75,2026-04-17-13-17-05 +0000,nypost,Strait of Hormuz ‘completely open’ until cease...,https://nypost.com/2026/04/17/world-news/strai...
151,71,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
251,55,2026-04-16-20-48-00 +0000,wsj,President Trump says he will nominate Dr. Eric...,https://www.wsj.com/politics/policy/trump-says...
93,48,2026-04-17-10-00-00 +0000,latimes,"Used EV sales charge up on high gas prices, ev...",https://www.latimes.com/business/story/2026-04...
152,47,2026-04-17-02-36-12 +0000,wapo,ICE agent charged with assault for allegedly p...,https://www.washingtonpost.com/nation/2026/04/...
304,44,2026-04-16-18-16-24 +0000,nypost,Europe could run out of jet fuel in 6 weeks — ...,https://nypost.com/2026/04/16/world-news/europ...
72,39,2026-04-17-10-46-15 +0000,nypost,UK PM Keir Starmer under pressure to quit over...,https://nypost.com/2026/04/17/world-news/uk-pm...
310,37,2026-04-16-18-01-20 +0000,nypost,Germany eyes harsher sick leave rules amid abs...,https://nypost.com/2026/04/16/world-news/germa...
154,37,2026-04-17-02-00-00 +0000,wsj,The fight between President Trump and Pope Leo...,https://www.wsj.com/politics/trump-pope-leo-am...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)