## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-08-11-00-00 +0000,wsj,The water system in Braham was one of dozens a...,https://www.wsj.com/politics/national-security...
1,2026-08-08-11-00-00 +0000,missionlocal,"More than 4,000 unaccompanied immigrant childr...",https://missionlocal.org/2026/08/immigrant-chi...
2,2026-08-08-11-00-00 +0000,wsj,The Cyberattack That Brought a Distant War to ...,https://www.wsj.com/politics/national-security...
3,2026-08-08-10-38-00 +0000,wsj,EU’s Internal Borders Start to Harden as Dispu...,https://www.wsj.com/world/europe/eus-internal-...
4,2026-08-08-10-31-10 +0000,nyt,"As Thailand Gets Known for Mass Shootings, Fre...",https://www.nytimes.com/2026/08/08/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
65    trump     40
240   court     20
605     new     18
222  senate     14
131      he     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
147,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,161
235,2026-08-07-17-15-00 +0000,wsj,A federal appeals court on Friday halted const...,https://www.wsj.com/politics/policy/white-hous...,147
261,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...,120
169,2026-08-07-20-22-38 +0000,wapo,Trump says he’ll bring ballroom fight to Supre...,https://www.washingtonpost.com/politics/2026/0...,119
190,2026-08-07-19-25-36 +0000,wapo,Trump renews effort to fire Fed governor Lisa ...,https://www.washingtonpost.com/business/2026/0...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
147,161,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
261,80,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...
336,65,2026-08-07-11-16-00 +0000,wsj,It seems like political scandals are happening...,https://www.wsj.com/politics/policy/is-misbeha...
156,65,2026-08-07-20-50-01 +0000,nypost,"Saudi Arabia, Turkey and Pakistan forge ‘attac...",https://nypost.com/2026/08/07/world-news/saudi...
278,63,2026-08-07-15-33-00 +0000,wsj,"The U.S. labor market shed jobs in July, an un...",https://www.wsj.com/economy/jobs/july-jobs-rep...
159,58,2026-08-07-20-47-19 +0000,chitri,Senate passes sweeping Russia sanctions bill n...,https://www.chicagotribune.com/2026/08/07/sena...
76,57,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...
202,36,2026-08-07-18-50-02 +0000,latimes,Meta ordered by New Mexico judge to pay $567 m...,https://www.latimes.com/business/story/2026-08...
240,35,2026-08-07-17-03-31 +0000,nypost,"Gavin Newsom rolls out $3,500 EV rebates for f...",https://nypost.com/2026/08/07/us-news/gavin-ne...
86,35,2026-08-08-00-54-27 +0000,nypost,Ex-Miss North Carolina USA Brittany Boltinhous...,https://nypost.com/2026/08/07/us-news/ex-miss-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)