## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-21-18-56-11 +0000,nypost,Lots of unsold units remain at One Wall Street...,https://nypost.com/2026/09/21/business/lots-of...
1,2026-09-21-18-55-00 +0000,cbc,Paramount settles with U.S. states over Warner...,https://www.cbc.ca/news/entertainment/paramoun...
2,2026-09-21-18-54-06 +0000,startribune,Minnesota’s biggest firms are getting tariff r...,https://www.startribune.com/minnesotas-biggest...
3,2026-09-21-18-53-07 +0000,nypost,Notorious Irish band nabs Guinness World Recor...,https://nypost.com/2026/09/21/us-news/the-prod...
4,2026-09-21-18-52-52 +0000,nypost,Sephora moves to new Meatpacking home right ne...,https://nypost.com/2026/09/21/business/sephora...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
123  trump     37
64   house     16
41     new     15
344  china     13
92    will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
328,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,123
116,2026-09-21-15-58-53 +0000,bbc,"CNN, MS NOW and Politico file lawsuit against ...",https://www.bbc.co.uk/news/articles/cm0e32rwvr...,102
155,2026-09-21-13-36-06 +0000,cbc,"MS NOW, CNN and Politico sue Trump administrat...",https://www.cbc.ca/news/world/trump-white-hous...,94
21,2026-09-21-18-31-17 +0000,nypost,Trump cuts ribbon on latest White House constr...,https://nypost.com/2026/09/21/us-news/trump-cu...,94
124,2026-09-21-15-36-00 +0000,wsj,"Illinois Gov. JB Pritzker, whose weight has be...",https://www.wsj.com/politics/policy/jb-pritzke...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
328,123,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
41,74,2026-09-21-18-05-18 +0000,nypost,Illinois Gov. JB Pritzker says he’s lost 80 po...,https://nypost.com/2026/09/21/us-news/illinois...
13,71,2026-09-21-18-42-44 +0000,bbc,"Paramount settles lawsuit with US states, help...",https://www.bbc.co.uk/news/articles/cm4gjr1qep...
43,60,2026-09-21-18-02-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
298,48,2026-09-20-22-06-44 +0000,nypost,Ex-NFL reporter Michele Tafoya hammers Minneso...,https://nypost.com/2026/09/20/us-news/ex-nfl-r...
172,48,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
133,45,2026-09-21-14-54-19 +0000,nypost,US pitches China on AI notification deal ahead...,https://nypost.com/2026/09/21/us-news/us-pitch...
322,40,2026-09-20-20-35-51 +0000,chitri,Russia wraps up first wartime parliamentary el...,https://www.chicagotribune.com/2026/09/20/russ...
199,40,2026-09-21-10-48-40 +0000,nypost,Five networks refuse to distribute footage of ...,https://nypost.com/2026/09/21/us-news/cnn-ms-n...
276,38,2026-09-21-01-00-00 +0000,wsj,Republicans are pumping money into Senate and ...,https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)