## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-00-08-41 +0000,nypost,Nithya Raman knocks Spencer Pratt off second p...,https://nypost.com/2026/06/07/us-news/nithya-r...
1,2026-06-08-00-03-07 +0000,nypost,Gasbuddy releases doomsday outlook for summer ...,https://nypost.com/2026/06/07/us-news/americas...
2,2026-06-08-00-02-52 +0000,startribune,"Patiently waiting in the wings, Kaelen Culpepp...",https://www.startribune.com/minnesota-twins-to...
3,2026-06-08-00-02-00 +0000,nypost,Lawsuit seeks to stop the UFC fight on the Whi...,https://nypost.com/2026/06/07/us-news/lawsuit-...
4,2026-06-08-00-00-00 +0000,wsj,The Hidden Figure With Close Ties to Bill Gate...,https://www.wsj.com/us-news/the-hidden-figure-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
35    trump     20
59     iran     16
49   israel     15
45      new     12
165   world      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-06-07-23-51-20 +0000,nyt,Live Updates: Iran Fires Missiles at Israel fo...,https://www.nytimes.com/live/2026/06/07/world/...,66
52,2026-06-07-21-02-06 +0000,nypost,Trump tells The Post ‘things are going well’ a...,https://nypost.com/2026/06/07/us-news/trump-te...,64
47,2026-06-07-21-10-43 +0000,nyt,Iran Fires Missiles at Israel for First Time S...,https://www.nytimes.com/2026/06/07/world/middl...,63
28,2026-06-07-22-12-16 +0000,wapo,Iran launches missiles at Israel for first tim...,https://www.washingtonpost.com/politics/2026/0...,57
66,2026-06-07-20-19-52 +0000,nyt,Trump Defends Compensation Fund and Iran War i...,https://www.nytimes.com/2026/06/07/us/politics...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,66,2026-06-07-23-51-20 +0000,nyt,Live Updates: Iran Fires Missiles at Israel fo...,https://www.nytimes.com/live/2026/06/07/world/...
112,57,2026-06-07-15-48-19 +0000,nypost,Trump storms off ‘Meet The Press’ interview af...,https://nypost.com/2026/06/07/us-news/trump-st...
176,38,2026-06-07-08-00-00 +0000,cbc,The FIFA World Cup is brought to you by Saudi ...,https://www.cbc.ca/radio/whatonearth/fifa-worl...
40,37,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
118,35,2026-06-07-15-21-34 +0000,nypost,Bombshell LA mayor’s race projection changes e...,https://nypost.com/2026/06/07/us-news/la-mayor...
174,34,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
137,30,2026-06-07-12-55-49 +0000,cbc,Russian drone hit nuclear fuel storage facilit...,https://www.cbc.ca/news/world/russian-drone-ch...
50,27,2026-06-07-21-04-25 +0000,nypost,Hero NYC cop who nabbed killer behind Post’s f...,https://nypost.com/2026/06/07/us-news/hero-nyc...
58,26,2026-06-07-20-48-10 +0000,nypost,GOP gov hopeful Bruce Blakeman will join Trump...,https://nypost.com/2026/06/07/us-news/gop-gov-...
19,25,2026-06-07-23-01-04 +0000,bbc,Spain's visitor numbers hit new highs as touri...,https://www.bbc.com/news/articles/c4gvndd2qelo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)