## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-01-10-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
1,2026-09-02-01-07-00 +0000,wsj,Nothing in this week’s G-20 suggested an end t...,https://www.wsj.com/economy/the-bond-market-is...
2,2026-09-02-01-07-00 +0000,wsj,The Bond Market Issues World Leaders a Failing...,https://www.wsj.com/economy/the-bond-market-is...
3,2026-09-02-01-05-52 +0000,wapo,Trump says he’ll nominate Hung Cao as Navy sec...,https://www.washingtonpost.com/politics/2026/0...
4,2026-09-02-01-04-58 +0000,48hills,Let’s just say it: The SF Democratic Party has...,https://48hills.org/2026/09/lets-just-say-it-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2294/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
28        trump     32
119  california     21
56         iran     21
330         new     18
577       house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-09-02-00-16-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,118
380,2026-09-01-09-00-00 +0000,wapo,Lake Ontario is now Lake America. Residents of...,https://www.washingtonpost.com/politics/2026/0...,94
130,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...,93
25,2026-09-02-00-36-24 +0000,bbc,Apple Maps changes Lake Ontario to Lake Americ...,https://www.bbc.co.uk/news/articles/cddvyyz0e4...,91
418,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,118,2026-09-02-00-16-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
130,93,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...
33,83,2026-09-02-00-24-10 +0000,nypost,"Tyler Robinson will go to trial, face possible...",https://nypost.com/2026/09/01/us-news/tyler-ro...
45,65,2026-09-01-23-50-56 +0000,cbc,"Apple Maps follows Google, changes name of Lak...",https://www.cbc.ca/news/world/apple-maps-lake-...
171,65,2026-09-01-19-51-00 +0000,wsj,Oil Prices Push Global Bond Market Closer to t...,https://www.wsj.com/finance/investing/oil-pric...
19,64,2026-09-02-00-43-00 +0000,wsj,Massachusetts Sen. Ed Markey beat back a Democ...,https://www.wsj.com/politics/elections/sen-ed-...
300,61,2026-09-01-13-32-03 +0000,wapo,17-year-old girl charged with murder in live-s...,https://www.washingtonpost.com/nation/2026/08/...
404,55,2026-09-01-04-43-45 +0000,nypost,Georgia mom missing after Nepal-Tibet floods l...,https://nypost.com/2026/09/01/world-news/georg...
418,51,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...
291,50,2026-09-01-14-21-00 +0000,wsj,Vice President JD Vance warned of ”growing sus...,https://www.wsj.com/politics/policy/three-take...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)