## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-21-14-36-01 +0000,nyt,BTS’s Comeback Show Was Heavy on Their New Album,https://www.nytimes.com/live/2026/03/21/world/...
1,2026-03-21-14-28-00 +0000,wsj,More TSA Workers Expected to Skip Work if They...,https://www.wsj.com/business/airlines/tsa-agen...
2,2026-03-21-14-24-24 +0000,nyt,Iran War Live Updates: U.S. Has Bombed Thousan...,https://www.nytimes.com/live/2026/03/21/world/...
3,2026-03-21-14-16-51 +0000,nyt,These BTS Fans Waited 15 Hours to See Their Idols,https://www.nytimes.com/2026/03/21/world/asia/...
4,2026-03-21-14-14-53 +0000,nyt,What to Know About Electric Cars When Gas Pric...,https://www.nytimes.com/2026/03/21/business/en...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2474/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
58        trump     27
15         iran     25
16          war     22
0           bts     11
446  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-21-14-24-24 +0000,nyt,Iran War Live Updates: U.S. Has Bombed Thousan...,https://www.nytimes.com/live/2026/03/21/world/...,110
202,2026-03-20-20-27-24 +0000,nypost,"Trump vows no cease-fire with Iran, predicts S...",https://nypost.com/2026/03/20/world-news/trump...,86
247,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...,81
70,2026-03-21-09-01-47 +0000,nyt,"High Gas Prices, Driven Up by the Iran War, Lo...",https://www.nytimes.com/2026/03/21/us/politics...,80
272,2026-03-20-16-56-35 +0000,nyt,Iran War Underscores the Diverging Aims of Tru...,https://www.nytimes.com/2026/03/20/world/europ...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,110,2026-03-21-14-24-24 +0000,nyt,Iran War Live Updates: U.S. Has Bombed Thousan...,https://www.nytimes.com/live/2026/03/21/world/...
247,81,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...
137,50,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...
145,50,2026-03-20-23-53-34 +0000,nypost,US pauses sanctions on Iranian oil ‘stranded a...,https://nypost.com/2026/03/20/us-news/us-pause...
112,42,2026-03-21-02-40-33 +0000,48hills,CBS workers in SF walk off the job as Bari Wei...,https://48hills.org/2026/03/cbs-workers-in-sf-...
182,39,2026-03-20-21-03-18 +0000,nypost,University of Alabama student James Gracey was...,https://nypost.com/2026/03/20/world-news/unive...
131,36,2026-03-21-01-00-00 +0000,wsj,Some Democrats on Capitol Hill are discussing ...,https://www.wsj.com/politics/policy/chuck-schu...
179,35,2026-03-20-21-18-38 +0000,latimes,The worst heat wave to hit Southern California...,https://www.latimes.com/california/story/2026-...
90,34,2026-03-21-07-04-51 +0000,bbc,BTS Arirang review: K-pop idols rekindle their...,https://www.bbc.com/news/articles/c070eg32dryo...
29,33,2026-03-21-12-31-16 +0000,nypost,Teen squatters got past lax security before st...,https://nypost.com/2026/03/21/us-news/teen-squ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)