## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-22-57-00 +0000,bbc,Fort Hood attacker's execution by firing squad...,https://www.bbc.co.uk/news/articles/cmy0r96xyg...
1,2026-10-08-22-54-42 +0000,nypost,Fruits and vegetables 50% less nutritious than...,https://nypost.com/2026/10/08/us-news/fruits-a...
2,2026-10-08-22-54-38 +0000,nypost,Josh Shapiro refuses to commit to finishing te...,https://nypost.com/2026/10/08/us-news/josh-sha...
3,2026-10-08-22-52-35 +0000,startribune,Arrest made in Eden Prairie homecoming footbal...,https://www.startribune.com/arrest-made-in-ede...
4,2026-10-08-22-52-24 +0000,startribune,Four finalists chosen for next Minneapolis pol...,https://www.startribune.com/minneapolis-police...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2376/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
106     trump     48
136    school     35
137     board     27
135   chicago     27
335  district     26

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
66,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...,190
172,2026-10-08-18-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...,150
382,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...,144
84,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...,144
380,2026-10-08-10-00-14 +0000,chitri,2026 Chicago school board races: District 2A,https://www.chicagotribune.com/2026/10/08/chic...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
66,190,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...
172,150,2026-10-08-18-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...
84,96,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...
153,62,2026-10-08-18-38-59 +0000,nypost,Gavin Newsom weighs taking 563 inmates off dea...,https://nypost.com/2026/10/08/us-news/gavin-ne...
304,61,2026-10-08-13-55-12 +0000,nypost,"Oil prices jump 5%, pushing Treasury yields hi...",https://nypost.com/2026/10/08/business/oil-pri...
277,57,2026-10-08-15-02-36 +0000,wapo,Search warrants against former prince Andrew w...,https://www.washingtonpost.com/world/2026/10/0...
112,48,2026-10-08-19-58-02 +0000,missionlocal,"IA, el tema candente en el primer debate entre...",https://missionlocal.org/2026/10/san-francisco...
193,48,2026-10-08-17-24-14 +0000,nypost,Walmart exec speaks out on dynamic pricing aga...,https://nypost.com/2026/10/08/lifestyle/walmar...
398,47,2026-10-08-09-54-12 +0000,nypost,Spanish woman whose eviction sparked housing p...,https://nypost.com/2026/10/08/world-news/spani...
254,46,2026-10-08-15-51-21 +0000,nyt,Tropical Storm Isaias Could Become the First A...,https://www.nytimes.com/2026/10/07/weather/tro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)