## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-05-01-16-36 +0000,startribune,Souhan: Timberwolves boss Tim Connelly correct...,https://www.startribune.com/timberwolves-boss-...
1,2026-04-05-01-10-04 +0000,nyt,Iran War Live Updates: U.S. Races to Rescue Mi...,https://www.nytimes.com/live/2026/04/04/world/...
2,2026-04-05-01-09-00 +0000,wsj,Striking Beef Plant Workers to Resume Work,https://www.wsj.com/business/striking-beef-pla...
3,2026-04-05-01-05-08 +0000,nyt,Here’s What Happened in the War in the Middle ...,https://www.nytimes.com/2026/04/04/world/middl...
4,2026-04-05-01-00-00 +0000,wsj,Research shows that the ranks of the affluent ...,https://www.wsj.com/economy/more-americans-are...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
16        trump     28
7          iran     23
8           war     13
489  california     10
196         new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-05-01-10-04 +0000,nyt,Iran War Live Updates: U.S. Races to Rescue Mi...,https://www.nytimes.com/live/2026/04/04/world/...,91
104,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,77
5,2026-04-05-01-00-00 +0000,wsj,President Trump’s repeated declarations that t...,https://www.wsj.com/politics/national-security...,75
85,2026-04-04-17-29-57 +0000,nyt,"Trump Pledged a Quick End to the Iran War, but...",https://www.nytimes.com/2026/04/04/us/politics...,74
140,2026-04-04-09-30-00 +0000,wsj,President Trump didn’t attack Iran to help the...,https://www.wsj.com/economy/the-iran-war-is-ma...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,91,2026-04-05-01-10-04 +0000,nyt,Iran War Live Updates: U.S. Races to Rescue Mi...,https://www.nytimes.com/live/2026/04/04/world/...
82,37,2026-04-04-17-42-39 +0000,nypost,Gavin Newsom to spend $19M in taxpayer funds o...,https://nypost.com/2026/04/04/us-news/gavin-ne...
21,33,2026-04-04-23-35-32 +0000,nypost,Notorious Gen. Soleimani’s sultry grandniece l...,https://nypost.com/2026/04/04/us-news/soleiman...
87,33,2026-04-04-17-20-48 +0000,nyt,"Houston Cheers on Artemis II Moon Mission, Rec...",https://www.nytimes.com/2026/04/04/us/artemis-...
104,26,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...
98,25,2026-04-04-15-44-35 +0000,cbc,Virginia Giuffre's family 'strongly' urges Kin...,https://www.cbc.ca/news/world/virginia-giuffre...
122,24,2026-04-04-11-01-00 +0000,startribune,Helicopter owner’s lawsuit fails against East ...,https://www.startribune.com/east-gull-lake-min...
180,23,2026-04-04-02-00-00 +0000,wsj,He Turned Down Ken Griffin to Run His Own Fund...,https://www.wsj.com/finance/investing/hamza-le...
90,23,2026-04-04-16-46-04 +0000,cbc,U.K. police arrest 4th suspect in connection w...,https://www.cbc.ca/news/world/fourth-person-ar...
163,21,2026-04-04-06-49-48 +0000,nypost,"One killed, dozens hurt as Peru soccer stadium...",https://nypost.com/2026/04/04/sports/peru-socc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)