## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-20-15-00 +0000,wsj,Three Dead and Four People Wounded in Seattle ...,https://www.wsj.com/us-news/two-dead-and-five-...
1,2026-07-27-20-14-03 +0000,nyt,Shots Fired Outside U.S. Consulate in Canada f...,https://www.nytimes.com/2026/07/27/world/canad...
2,2026-07-27-20-14-00 +0000,wsj,Luxury Titan Bernard Arnault Is Changing the P...,https://www.wsj.com/business/media/luxury-tita...
3,2026-07-27-20-13-10 +0000,nyt,Iran War Enters 6th Month and a Period of Grea...,https://www.nytimes.com/2026/07/27/us/politics...
4,2026-07-27-20-08-17 +0000,nyt,Oil Prices Sink After U.S. and Iran Pause Figh...,https://www.nytimes.com/2026/07/26/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2518/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
74        new     22
21       iran     20
47      trump     16
71  wildfires     13
78     france     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-07-27-19-59-32 +0000,nyt,Wildfires Live Updates: New Heat Wave Could Wo...,https://www.nytimes.com/live/2026/07/27/world/...,80
154,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...,68
174,2026-07-27-13-22-42 +0000,nyt,New Heat Wave Could Intensify Wildfires in Fra...,https://www.nytimes.com/2026/07/27/world/europ...,67
292,2026-07-26-22-25-29 +0000,nypost,"Trump likes daily strikes on Iran, Sen. Kenned...",https://nypost.com/2026/07/26/world-news/trump...,61
215,2026-07-27-10-27-57 +0000,nypost,Iran ramps up threats on Ukraine over Caspian ...,https://nypost.com/2026/07/27/world-news/iran-...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,80,2026-07-27-19-59-32 +0000,nyt,Wildfires Live Updates: New Heat Wave Could Wo...,https://www.nytimes.com/live/2026/07/27/world/...
154,68,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...
242,53,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
22,44,2026-07-27-19-41-57 +0000,cbc,Police arrest 15-year-old after Seattle festiv...,https://www.cbc.ca/news/world/police-arrest-se...
171,41,2026-07-27-13-30-55 +0000,cbc,German chancellor Merz questions why suspect i...,https://www.cbc.ca/news/world/germany-berlin-a...
206,39,2026-07-27-11-02-00 +0000,wsj,Chip Maker Soars 466% on Debut to Become No. 1...,https://www.wsj.com/tech/cxmts-strong-debut-bo...
21,35,2026-07-27-19-42-00 +0000,wapo,"NYC-run grocery stores will sell meat, other b...",https://www.washingtonpost.com/business/2026/0...
173,35,2026-07-27-13-24-08 +0000,nypost,Cracker Barrel CEO Julie Felss Masino steps do...,https://nypost.com/2026/07/27/business/cracker...
97,34,2026-07-27-16-40-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
115,33,2026-07-27-16-19-39 +0000,latimes,Feds drop case against California labor leader...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)