## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-21-52-55 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/31/us/mid...
1,2026-10-31-21-50-29 +0000,nyt,"Clashes Erupt Again in France, After Festive S...",https://www.nytimes.com/2026/10/31/world/europ...
2,2026-10-31-21-50-29 +0000,nyt,Newsom Issues Warning to Judges About Election...,https://www.nytimes.com/2026/10/31/us/newsom-c...
3,2026-10-31-21-44-34 +0000,startribune,Live: No. 4 Indiana pulls ailing starting QB a...,https://www.startribune.com/minnesota-gophers-...
4,2026-10-31-21-43-34 +0000,nyt,‘We Are Coming From Hell’: A Ukrainian City’s ...,https://www.nytimes.com/2026/10/31/todayspaper...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2423/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
15        trump     26
13     election     14
120  california     11
82    halloween     11
245        race      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
33,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...,64
83,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...,63
56,2026-10-31-18-40-05 +0000,nypost,President Trump lauds LA’s top federal prosecu...,https://nypost.com/2026/10/31/us-news/trump-ba...,63
8,2026-10-31-21-22-42 +0000,nypost,Trump ask to set aside ‘Decoy Dan’ Alaska Sena...,https://nypost.com/2026/10/31/us-news/trump-as...,61
16,2026-10-31-21-01-29 +0000,nyt,Judge Tosses Trump’s $10 Billion Suit Against ...,https://www.nytimes.com/2026/10/31/business/me...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
33,64,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...
117,47,2026-10-31-12-00-00 +0000,latimes,Your last-minute guide to the L.A. city attorn...,https://www.latimes.com/california/story/2026-...
98,45,2026-10-31-14-00-00 +0000,wsj,"Polling data remains at issue after Brazil, Se...",https://www.wsj.com/politics/elections/predict...
24,44,2026-10-31-20-33-20 +0000,nypost,Harrowing video captures California Halloween ...,https://nypost.com/2026/10/31/us-news/spirit-h...
106,40,2026-10-31-13-10-33 +0000,nypost,Abdul El-Sayed tells Rep. Haley Stevens to sta...,https://nypost.com/2026/10/31/us-news/abdul-el...
225,38,2026-10-30-23-14-08 +0000,nypost,Feds ‘surge’ law enforcement to Alaska after ‘...,https://nypost.com/2026/10/30/us-news/feds-sur...
163,36,2026-10-31-08-00-00 +0000,cbc,'No one is safe' as Ebola outbreak surges to m...,https://www.cbc.ca/news/health/africa-top-doct...
165,33,2026-10-31-07-29-01 +0000,nypost,France heads into third weekend of protests as...,https://nypost.com/2026/10/31/world-news/franc...
21,31,2026-10-31-20-44-33 +0000,nypost,"If Iran war erupts, Israel may be plotting ano...",https://nypost.com/2026/10/31/world-news/israe...
86,29,2026-10-31-15-19-25 +0000,nypost,UK PM Andy Burnham says he is ‘open’ to formal...,https://nypost.com/2026/10/31/world-news/uk-pm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)