## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-26-17-03-19 +0000,nyt,Social Media Captures the Chaos and Mundane of...,https://www.nytimes.com/2026/04/26/us/politics...
1,2026-04-26-17-00-14 +0000,nyt,"In Deep Blue California, a G.O.P.-Backed Voter...",https://www.nytimes.com/2026/04/25/us/politics...
2,2026-04-26-16-59-00 +0000,wsj,Opinion | Cutting Law Degree Convolution,https://www.wsj.com/opinion/cutting-law-degree...
3,2026-04-26-16-55-02 +0000,startribune,Media dinner shooting suspect wrote about targ...,https://www.startribune.com/gunman-at-trump-di...
4,2026-04-26-16-50-13 +0000,nyt,"After Shooting, Trump Demands Approval for His...",https://www.nytimes.com/2026/04/26/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

              word  score
25           trump     46
7           dinner     33
6   correspondents     29
5         shooting     26
29           house     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-04-26-05-18-00 +0000,wsj,President Trump is safe after what he describe...,https://www.wsj.com/us-news/trump-evacuated-wh...,230
37,2026-04-26-15-22-31 +0000,nypost,Trump recounts political unity after White Hou...,https://nypost.com/2026/04/26/us-news/trump-re...,205
29,2026-04-26-15-38-13 +0000,nypost,Read White House Correspondents’ Dinner gunman...,https://nypost.com/2026/04/26/us-news/read-whc...,194
122,2026-04-26-04-43-30 +0000,nypost,White House Correspondents’ Dinner shooting ‘t...,https://nypost.com/2026/04/26/us-news/melania-...,194
140,2026-04-26-01-12-57 +0000,latimes,Trump rushed off stage after shooting at White...,https://www.latimes.com/california/story/2026-...,194

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,230,2026-04-26-05-18-00 +0000,wsj,President Trump is safe after what he describe...,https://www.wsj.com/us-news/trump-evacuated-wh...
7,51,2026-04-26-16-47-42 +0000,nypost,WHCD shooting suspect Cole Allen mocked lack o...,https://nypost.com/2026/04/26/us-news/whcd-sho...
18,50,2026-04-26-16-18-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
65,47,2026-04-26-12-29-41 +0000,wapo,"Trump calls off Witkoff, Kushner trip to Pakis...",https://www.washingtonpost.com/world/2026/04/2...
17,35,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...
12,33,2026-04-26-16-32-00 +0000,wsj,Sen. Thom Tillis said he would support Kevin W...,https://www.wsj.com/politics/policy/tillis-dro...
136,32,2026-04-26-01-58-52 +0000,nypost,White House Correspondents’ Dinner gunman ‘ass...,https://nypost.com/2026/04/25/us-news/white-ho...
151,29,2026-04-25-23-24-57 +0000,nyt,Al Qaeda-Linked Militants Launch Major Attacks...,https://www.nytimes.com/2026/04/25/world/afric...
165,26,2026-04-25-21-41-29 +0000,nypost,Mamdani releases propaganda video promoting So...,https://nypost.com/2026/04/25/us-news/mamdani-...
87,23,2026-04-26-10-00-00 +0000,startribune,Champlin 82-year-old in high spirits after Wal...,https://www.startribune.com/champlin-82-year-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)