## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-03-15-07-14 +0000,nypost,"DOT Secretary Duffy blames Biden admin, Pete B...",https://nypost.com/2026/05/03/us-news/dot-secr...
1,2026-05-03-14-50-48 +0000,nyt,Blanche Says Others Who Post ‘86 47’ Message W...,https://www.nytimes.com/2026/05/03/us/politics...
2,2026-05-03-14-47-18 +0000,bbc,Tories pledge to tighten household benefit cap...,https://www.bbc.com/news/articles/cm2pm41z1nxo...
3,2026-05-03-14-45-35 +0000,nyt,"OPEC Plus, in Symbolic Gesture, to Increase Oi...",https://www.nytimes.com/2026/05/03/business/op...
4,2026-05-03-14-44-04 +0000,bbc,Concern for jailed Iranian Nobel laureate as b...,https://www.bbc.com/news/articles/c362pd8epw9o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
340     trump     17
230       new     11
9    airlines     10
8      spirit      9
375      iran      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...,63
67,2026-05-03-09-00-00 +0000,wsj,Secret Service Director Sean Curran has earned...,https://www.wsj.com/politics/policy/he-rescued...,52
126,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,51
159,2026-05-02-17-48-47 +0000,nypost,Outrage as California vice mayor posts vile ‘d...,https://nypost.com/2026/05/02/us-news/californ...,48
160,2026-05-02-17-39-43 +0000,wapo,"Spirit Airlines, low-cost innovator, shuts dow...",https://www.washingtonpost.com/politics/2026/0...,47

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,63,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
98,41,2026-05-03-03-00-00 +0000,wsj,A mammoth economic stimulus passed last year i...,https://www.wsj.com/world/europe/germany-has-t...
9,40,2026-05-03-14-25-27 +0000,nypost,Former top Biden official all but admits admin...,https://nypost.com/2026/05/03/us-news/ex-biden...
133,34,2026-05-02-21-50-29 +0000,nypost,London’s top cop warns British Jews face great...,https://nypost.com/2026/05/02/world-news/londo...
162,32,2026-05-02-17-10-00 +0000,wsj,The number of food-stamp recipients is falling...,https://www.wsj.com/politics/policy/more-than-...
104,31,2026-05-03-02-00-00 +0000,wsj,The U.S. is striving to dominate the drone evo...,https://www.wsj.com/politics/national-security...
169,27,2026-05-02-16-50-23 +0000,cbc,Jailed Nobel laureate's life at risk if she is...,https://www.cbc.ca/news/world/nobel-peace-priz...
145,27,2026-05-02-20-21-15 +0000,nypost,Zelensky warns of ‘unusual activity’ on Belaru...,https://nypost.com/2026/05/02/world-news/zelen...
28,26,2026-05-03-12-06-34 +0000,bbc,In five charts: How UAE's exit could affect Op...,https://www.bbc.com/news/articles/c70vjpny0dno...
67,23,2026-05-03-09-00-00 +0000,wsj,Secret Service Director Sean Curran has earned...,https://www.wsj.com/politics/policy/he-rescued...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)