## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-20-04-49-41 +0000,nypost,"Massive fire rips through NYC restaurants, inj...",https://nypost.com/2026/09/20/us-news/massive-...
1,2026-09-20-04-49-11 +0000,bbc,Ed Sheeran admits 'mistakes' as he addresses M...,https://www.bbc.co.uk/news/articles/cm780ll1de...
2,2026-09-20-04-35-16 +0000,nypost,Justice Department charges 16 across multiple ...,https://nypost.com/2026/09/20/us-news/doj-char...
3,2026-09-20-04-31-27 +0000,missionlocal,Valkyries win last home game of regular season,https://missionlocal.org/2026/09/valkyries-win...
4,2026-09-20-04-06-12 +0000,nypost,New Jersey mom charged with obstruction after ...,https://nypost.com/2026/09/20/us-news/nj-mom-j...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2313/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
86        trump     40
78           ai     15
146  california     12
85        house     12
34          new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
133,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...,98
124,2026-09-19-14-51-03 +0000,cbc,"CNN, MS NOW, Politico say journalists denied a...",https://www.cbc.ca/news/world/cnn-journalists-...,95
59,2026-09-19-21-41-39 +0000,wapo,"CNN, MS NOW, Politico say journalists blocked ...",https://www.washingtonpost.com/politics/2026/0...,91
88,2026-09-19-18-47-00 +0000,wsj,Three News Outlets Denied Entry to White House...,https://www.wsj.com/politics/policy/ms-now-den...,85
143,2026-09-19-12-14-43 +0000,nypost,"GOP control of House, Senate odds fade as Trum...",https://nypost.com/2026/09/19/us-news/republic...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
133,98,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...
154,51,2026-09-19-11-32-48 +0000,nypost,Anthropic splashes out $40M in fight over AI r...,https://nypost.com/2026/09/19/us-news/anthropi...
50,40,2026-09-19-22-42-44 +0000,nypost,Gavin Newsom signs bill to create new film and...,https://nypost.com/2026/09/19/us-news/gavin-ne...
66,35,2026-09-19-20-38-00 +0000,wsj,Yemen’s Houthis Claim Attack on Saudi Capital ...,https://www.wsj.com/world/middle-east/air-atta...
19,34,2026-09-20-02-00-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
32,33,2026-09-20-00-11-50 +0000,nypost,Michael Goodwin: Iran will be top of mind at t...,https://nypost.com/2026/09/19/us-news/un-week-...
23,29,2026-09-20-01-25-23 +0000,nypost,Mourners flood funeral held for tragic NYC mom...,https://nypost.com/2026/09/19/us-news/funeral-...
200,27,2026-09-19-05-07-52 +0000,nypost,Cuba hit with another blackout as millions acr...,https://nypost.com/2026/09/19/world-news/cuba-...
58,23,2026-09-19-21-43-54 +0000,nypost,German synagogue fire arson suspect arrested a...,https://nypost.com/2026/09/19/world-news/arson...
86,22,2026-09-19-19-11-00 +0000,wsj,"With less than 50 days until Election Day, her...",https://www.wsj.com/politics/elections/primari...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)