## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-14-01-15-10 +0000,nyt,"U.S. Attacks Iran’s Kharg Island, a Key Port f...",https://www.nytimes.com/2026/03/13/world/middl...
1,2026-03-14-01-10-20 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: U...,https://www.nytimes.com/live/2026/03/13/world/...
2,2026-03-14-01-08-29 +0000,missionlocal,6 people hospitalized after car crash in Missi...,https://missionlocal.org/2026/03/6-people-hosp...
3,2026-03-14-01-01-21 +0000,nypost,Sheriff alerted Michigan synagogue to potentia...,https://nypost.com/2026/03/13/us-news/sheriff-...
4,2026-03-14-01-00-00 +0000,wsj,Traders Tell Us How They’re Dealing With the F...,https://www.wsj.com/finance/markets-oil-iran-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
1    iran     53
8   trump     46
11    war     43
6     oil     25
79    new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-14-01-10-20 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: U...,https://www.nytimes.com/live/2026/03/13/world/...,306
6,2026-03-14-00-57-55 +0000,latimes,Trump administration orders restart of oil dri...,https://www.latimes.com/california/story/2026-...,197
378,2026-03-13-01-32-01 +0000,nyt,Trump Removes Sanctions on Russia to Help Oil ...,https://www.nytimes.com/2026/03/12/us/politics...,164
5,2026-03-14-01-00-00 +0000,wsj,Trump Knew the Risk of Iran Blocking the Strai...,https://www.wsj.com/politics/national-security...,163
205,2026-03-13-16-17-58 +0000,nyt,Trump-Iran Timeline: Key Moments Leading Up to...,https://www.nytimes.com/2026/03/13/us/politics...,158

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,306,2026-03-14-01-10-20 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: U...,https://www.nytimes.com/live/2026/03/13/world/...
255,65,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
50,55,2026-03-13-23-03-39 +0000,wapo,New dime to celebrate America’s birthday takes...,https://www.washingtonpost.com/business/2026/0...
136,54,2026-03-13-19-50-01 +0000,nypost,"Pentagon sending assault ship, at least 2,500 ...",https://nypost.com/2026/03/13/us-news/pentagon...
149,47,2026-03-13-18-58-00 +0000,wsj,"TotalEnergies Shutting Production in Qatar, Ir...",https://www.wsj.com/business/energy-oil/totale...
65,43,2026-03-13-22-15-23 +0000,nypost,Charges dropped against five students involved...,https://nypost.com/2026/03/13/us-news/charges-...
237,43,2026-03-13-15-00-06 +0000,bbc,UK urges allies to keep up pressure on Russia ...,https://www.bbc.com/news/articles/cvg3yxd49xno...
85,42,2026-03-13-21-39-00 +0000,wsj,"In a major victory for the Fed, a judge threw ...",https://www.wsj.com/economy/central-banking/ju...
282,40,2026-03-13-11-47-09 +0000,bbc,'No-one will hire women' - India's top court r...,https://www.bbc.com/news/articles/c0436qkegdqo...
28,36,2026-03-14-00-07-57 +0000,nypost,Flights at three DC-area airports halted over ...,https://nypost.com/2026/03/13/us-news/flights-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)