## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-31-18-18-50 +0000,nyt,Live Updates: Most of the Migrants Who Crossed...,https://www.nytimes.com/live/2026/07/31/world/...
1,2026-07-31-18-17-11 +0000,nyt,Companies Rush to Close Daring Deals Under Trump,https://www.nytimes.com/2026/07/31/business/co...
2,2026-07-31-18-16-45 +0000,nypost,Trump warns migrant ‘catastrophe’ in Spain wou...,https://nypost.com/2026/07/31/world-news/trump...
3,2026-07-31-18-13-53 +0000,chitri,As heat and dry conditions fan wildfires in Fr...,https://www.chicagotribune.com/2026/07/31/fran...
4,2026-07-31-18-13-48 +0000,nyt,Far-right politicians seize on Ceuta,https://www.nytimes.com/2026/07/31/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
14      trump     38
435      plan     17
3    migrants     15
69        new     15
508      iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
354,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...,116
193,2026-07-31-10-23-17 +0000,cbc,Hamas will honour Trump's Gaza peace deal if I...,https://www.cbc.ca/news/world/hamas-israel-dis...,107
303,2026-07-30-22-29-53 +0000,nypost,Trump demands Iran agree to a cease-fire — and...,https://nypost.com/2026/07/30/us-news/cease-fi...,94
55,2026-07-31-16-52-25 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,90
289,2026-07-30-23-30-00 +0000,cbc,Trump says 'Board of Peace' reaches deal for H...,https://www.cbc.ca/news/world/board-of-peace-g...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
354,116,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...
310,70,2026-07-30-22-18-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
229,70,2026-07-31-08-47-45 +0000,cbc,At least 57 migrants dead after thousands brea...,https://www.cbc.ca/news/world/ceuta-migrants-m...
193,69,2026-07-31-10-23-17 +0000,cbc,Hamas will honour Trump's Gaza peace deal if I...,https://www.cbc.ca/news/world/hamas-israel-dis...
291,59,2026-07-30-23-07-01 +0000,chitri,European nations vow World Cup boycott and Nor...,https://www.chicagotribune.com/2026/07/30/euro...
125,56,2026-07-31-14-19-00 +0000,wsj,Three Fed policymakers said stubborn inflation...,https://www.wsj.com/economy/central-banking/tw...
68,48,2026-07-31-16-30-24 +0000,nypost,LA gas stations where you can still get cheap ...,https://nypost.com/2026/07/31/business/where-t...
38,44,2026-07-31-17-23-15 +0000,nypost,A great day out in NYC for $0 — in this econom...,https://nypost.com/2026/07/31/lifestyle/the-be...
261,44,2026-07-31-03-21-37 +0000,nypost,Netflix star Nirmal Purja among 10 missing aft...,https://nypost.com/2026/07/30/world-news/world...
273,42,2026-07-31-01-00-00 +0000,wsj,Dr. Anthony Fauci’s lawyers advised him to inv...,https://www.wsj.com/politics/faucis-turn-from-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)