## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-17-22-50-59 +0000,nypost,Mom of innocent 12-year-old gunned down by car...,https://nypost.com/2026/09/17/us-news/mom-of-i...
1,2026-09-17-22-46-33 +0000,nypost,Mamdani brags about repairing 200K potholes — ...,https://nypost.com/2026/09/17/us-news/mamdani-...
2,2026-09-17-22-45-14 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-wa...
3,2026-09-17-22-44-03 +0000,nyt,Yemen War Intensifies as Houthi Militia Advanc...,https://www.nytimes.com/2026/09/17/world/middl...
4,2026-09-17-22-43-00 +0000,wsj,Tech Companies’ Staff Knew Their AI Tools Pose...,https://www.wsj.com/tech/ai/tech-companies-sta...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
24   trump     44
73     new     23
44      ai     22
529    fed     19
74   house     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
372,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...,161
371,2026-09-17-00-59-00 +0000,wapo,Trump says he told Fed chief to ‘do what you w...,https://www.washingtonpost.com/business/2026/0...,129
388,2026-09-16-23-16-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...,127
288,2026-09-17-11-00-00 +0000,wsj,The trillion-dollar question: Did Fed Chairman...,https://www.wsj.com/politics/policy/the-trilli...,119
118,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
372,161,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...
142,104,2026-09-17-17-47-52 +0000,nypost,White House issues explosive response to UN-ba...,https://nypost.com/2026/09/17/us-news/white-ho...
291,73,2026-09-17-10-40-44 +0000,nypost,Mark Carney welcomes proposal for Canada to be...,https://nypost.com/2026/09/17/world-news/mark-...
144,70,2026-09-17-17-46-14 +0000,nypost,"Chinese AI labs must accelerate development, s...",https://nypost.com/2026/09/17/business/chinese...
280,62,2026-09-17-11-15-00 +0000,wsj,A Treasurer’s Playbook Following a Fed Rate Hi...,https://www.wsj.com/cfo-journal/a-treasurers-p...
388,61,2026-09-16-23-16-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...
37,48,2026-09-17-21-36-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...
121,45,2026-09-17-18-54-41 +0000,cbc,Judge orders Kennedy Center to give 30-day not...,https://www.cbc.ca/news/world/kennedy-center-t...
90,39,2026-09-17-20-06-23 +0000,startribune,"After delay, ICE agent charged with shooting i...",https://www.startribune.com/after-delay-ice-ag...
385,38,2026-09-16-23-33-28 +0000,chitri,House passes bill aimed at addressing impact o...,https://www.chicagotribune.com/2026/09/16/hous...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)