## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-05-36-00 +0000,wsj,"Heineken Says Higher Pricing, Volume Recovery ...",https://www.wsj.com/business/earnings/heineken...
1,2026-04-23-05-35-53 +0000,startribune,"Live from Game 3: Wild, Stars tied 3-3 in doub...",https://www.startribune.com/minnesota-wild-dal...
2,2026-04-23-05-35-00 +0000,wsj,U.S. Treasury Yields Rise Amid Standoff Over S...,https://www.wsj.com/finance/investing/jgbs-con...
3,2026-04-23-05-33-00 +0000,wsj,Roche Backs Full-Year View as Quarterly Sales ...,https://www.wsj.com/business/retail/roche-back...
4,2026-04-23-05-31-00 +0000,wsj,Nestle Reports Drop in Sales Amid Strategic Ov...,https://www.wsj.com/business/nestle-reports-dr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
82         iran     38
98        trump     34
79          war     23
88          new     22
157  california     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
361,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,143
43,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,125
122,2026-04-22-21-43-54 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...,125
323,2026-04-22-10-45-39 +0000,bbc,Oil prices fluctuate as Trump extends Iran war...,https://www.bbc.com/news/articles/c995dkl4dvvo...,123
283,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
361,143,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...
283,81,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...
28,65,2026-04-23-03-16-00 +0000,bbc,"Court pauses redistricting in Virginia, day af...",https://www.bbc.com/news/articles/c5ywnjw7qj2o...
216,56,2026-04-22-18-07-17 +0000,nyt,California’s Governor Candidates to Meet in Fi...,https://www.nytimes.com/2026/04/22/us/californ...
359,49,2026-04-22-08-00-00 +0000,cbc,John Ternus is replacing Tim Cook as Apple CEO...,https://www.cbc.ca/news/business/john-ternus-a...
117,45,2026-04-22-21-52-00 +0000,wsj,Here are the key takeaways after Health Secret...,https://www.wsj.com/politics/policy/lawmakers-...
30,42,2026-04-23-02-57-59 +0000,latimes,"Santa Monica nonprofit official, wife found de...",https://www.latimes.com/california/story/2026-...
287,39,2026-04-22-14-21-12 +0000,cbc,At least 5 killed in Israeli strikes on south ...,https://www.cbc.ca/news/world/israel-lebanon-t...
238,35,2026-04-22-16-58-00 +0000,wsj,More than a year into President Trump’s immigr...,https://www.wsj.com/economy/jobs/immigration-c...
353,35,2026-04-22-08-51-58 +0000,nypost,Mexico pyramid shooter Julio César Jasso plann...,https://nypost.com/2026/04/22/world-news/mexic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)