## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-20-04-25 +0000,nypost,"Ex-NY cop, D.A.R.E. officer admits to selling ...",https://nypost.com/2026/03/05/us-news/ex-ny-co...
1,2026-03-05-20-04-15 +0000,nyt,Trump Says He Should Have Role in Picking Iran...,https://www.nytimes.com/2026/03/05/us/politics...
2,2026-03-05-20-03-51 +0000,nyt,Republicans Toil to Avoid Saying ‘War’ as Iran...,https://www.nytimes.com/2026/03/05/us/politics...
3,2026-03-05-20-01-52 +0000,nyt,Live Updates: Trump Says He Should Have Role i...,https://www.nytimes.com/live/2026/03/05/world/...
4,2026-03-05-20-01-00 +0000,wsj,Iran Conflict: Five Things to Know,https://www.wsj.com/world/middle-east/iran-con...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2609/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
16       iran     75
11      trump     48
22        war     42
178   iranian     21
23   conflict     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
52,2026-03-05-19-26-01 +0000,startribune,Trump says he wants to be involved in picking ...,https://www.startribune.com/iran-launches-new-...,199
316,2026-03-05-05-07-22 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,185
372,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,181
417,2026-03-04-21-16-50 +0000,wapo,Spanish prime minister rebukes Trump’s war in ...,https://www.washingtonpost.com/world/2026/03/0...,177
380,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...,175

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
52,199,2026-03-05-19-26-01 +0000,startribune,Trump says he wants to be involved in picking ...,https://www.startribune.com/iran-launches-new-...
76,106,2026-03-05-19-02-00 +0000,wsj,House Speaker Mike Johnson and other top GOP l...,https://www.wsj.com/politics/texas-tony-gonzal...
288,72,2026-03-05-08-52-04 +0000,nypost,Iranian bombers came within ‘two minutes’ of s...,https://nypost.com/2026/03/05/world-news/irani...
30,49,2026-03-05-19-40-00 +0000,wsj,The Defense Department has officially told Ant...,https://www.wsj.com/politics/national-security...
429,49,2026-03-04-20-43-00 +0000,wsj,Early 2026 data have painted an economy on ste...,https://www.wsj.com/economy/central-banking/fe...
176,49,2026-03-05-15-51-35 +0000,cbc,Ukraine support remains front and centre amid ...,https://www.cbc.ca/news/world/rutte-zelenskyy-...
73,44,2026-03-05-19-03-33 +0000,wapo,Live updates: Israel urges evacuation of south...,https://www.washingtonpost.com/world/2026/03/0...
78,43,2026-03-05-19-01-00 +0000,wsj,President Trump said Kristi Noem is no longer ...,https://www.wsj.com/politics/policy/trump-dhs-...
11,41,2026-03-05-19-56-00 +0000,wsj,"For the First Time, U.S. Sides With Russia and...",https://www.wsj.com/world/for-the-first-time-u...
211,40,2026-03-05-14-09-00 +0000,wsj,Oil Futures Rise As Persian Gulf Conflict Cont...,https://www.wsj.com/finance/commodities-future...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)