## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-19-22-11 +0000,startribune,"Frey wants O’Hara for another term as chief, b...",https://www.startribune.com/mayor-jacob-frey-n...
1,2026-05-07-19-19-43 +0000,nyt,Trump to Host Brazil’s President Lula at White...,https://www.nytimes.com/2026/05/07/world/ameri...
2,2026-05-07-19-18-31 +0000,nyt,Iran War Live Updates: U.S. Awaits Tehran’s Re...,https://www.nytimes.com/live/2026/05/07/world/...
3,2026-05-07-19-18-23 +0000,nypost,Iranian president reportedly met with still mi...,https://nypost.com/2026/05/07/world-news/irani...
4,2026-05-07-19-18-03 +0000,nypost,MTA worker forged parking placards so he could...,https://nypost.com/2026/05/07/us-news/mta-work...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
9         trump     34
19         iran     29
20          war     29
103  hantavirus     17
107        ship     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
286,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,139
262,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...,105
55,2026-05-07-17-57-11 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...,102
363,2026-05-06-20-16-58 +0000,nyt,Oil Prices Fall on Hope U.S.-Iran War Turmoil ...,https://www.nytimes.com/2026/05/06/business/oi...,93
221,2026-05-07-09-38-04 +0000,bbc,Shell latest oil giant to see profits surge du...,https://www.bbc.com/news/articles/ce3p0x54drwo...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
286,139,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
178,67,2026-05-07-12-06-25 +0000,nypost,Eerie moment cruise passengers told about firs...,https://nypost.com/2026/05/07/world-news/eerie...
222,61,2026-05-07-09-33-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
44,51,2026-05-07-18-23-53 +0000,nypost,Spencer Pratt’s debate truth bombs earn praise...,https://nypost.com/2026/05/07/us-news/spencer-...
46,47,2026-05-07-18-22-13 +0000,nypost,"Voters overwhelmingly back age, term limits fo...",https://nypost.com/2026/05/07/us-news/voters-o...
6,46,2026-05-07-19-17-56 +0000,nypost,California gas station chain offering 40 cents...,https://nypost.com/2026/05/07/business/califor...
156,39,2026-05-07-13-29-41 +0000,nypost,Trump halted ‘Project Freedom’ Hormuz plan aft...,https://nypost.com/2026/05/07/us-news/trump-ha...
169,35,2026-05-07-12-32-50 +0000,wapo,Rubio visits Rome aiming to repair White House...,https://www.washingtonpost.com/world/2026/05/0...
55,34,2026-05-07-17-57-11 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...
183,33,2026-05-07-11-53-06 +0000,nypost,Hochul bungles budget deal rollout as NYS lead...,https://nypost.com/2026/05/07/us-news/hochul-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)