## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-19-19-10-18 +0000,nypost,Ex-cop who derided socialist NYC pols now cozy...,https://nypost.com/2026/04/19/us-news/ex-cop-w...
1,2026-04-19-19-08-13 +0000,nyt,Iran War Live Updates: Tehran Pushes Back Afte...,https://www.nytimes.com/live/2026/04/19/world/...
2,2026-04-19-19-08-11 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/19/world/...
3,2026-04-19-19-06-33 +0000,nypost,Husband of beloved coffee shop owner reveals s...,https://nypost.com/2026/04/19/us-news/husband-...
4,2026-04-19-19-06-10 +0000,nypost,Iran refuses to join latest round of peace tal...,https://nypost.com/2026/04/19/world-news/iran-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2518/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
19     trump     26
13      iran     18
14       war     13
64  shooting     12
21       new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
75,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...,88
131,2026-04-19-03-49-45 +0000,nypost,JD Vance ‘grateful’ to Pope Leo for easing ten...,https://nypost.com/2026/04/18/world-news/jd-va...,87
1,2026-04-19-19-08-13 +0000,nyt,Iran War Live Updates: Tehran Pushes Back Afte...,https://www.nytimes.com/live/2026/04/19/world/...,79
138,2026-04-19-01-00-00 +0000,wsj,Behind Trump’s public bravado on the war in Ir...,https://www.wsj.com/politics/national-security...,71
50,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
75,88,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...
22,45,2026-04-19-18-01-59 +0000,nyt,8 Children Killed in Domestic Mass Shooting in...,https://www.nytimes.com/2026/04/19/us/shrevepo...
143,31,2026-04-19-00-00-00 +0000,wsj,Virginians face a ballot measure asking them w...,https://www.wsj.com/politics/elections/virgini...
31,29,2026-04-19-17-25-12 +0000,nypost,Ex-hotel still houses sex offenders near NYC p...,https://nypost.com/2026/04/19/us-news/ex-hotel...
50,29,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
169,27,2026-04-18-20-55-28 +0000,nypost,Iran’s maimed Supreme Leader Khamenei issues n...,https://nypost.com/2026/04/18/world-news/supre...
161,23,2026-04-18-21-29-29 +0000,nypost,Iran doesn’t need a navy to choke the world’s ...,https://nypost.com/2026/04/18/world-news/iran-...
67,23,2026-04-19-13-48-26 +0000,nypost,Energy Secretary reveals when gas prices are e...,https://nypost.com/2026/04/19/us-news/chris-wr...
4,21,2026-04-19-19-06-10 +0000,nypost,Iran refuses to join latest round of peace tal...,https://nypost.com/2026/04/19/world-news/iran-...
28,21,2026-04-19-17-47-09 +0000,nypost,Elementary school teacher caught sending truly...,https://nypost.com/2026/04/19/us-news/long-bea...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)