## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-19-11-00-00 +0000,missionlocal,"Doug Rhodes, Clarion Alley’s only open studio ...",https://missionlocal.org/2026/04/doug-rhodes-c...
1,2026-04-19-10-59-16 +0000,bbc,Rat poison found in HiPP jarred baby food in A...,https://www.bbc.com/news/articles/cvg07lq5ql4o...
2,2026-04-19-10-53-38 +0000,nypost,‘Multiple victims’ injured after gunfire break...,https://nypost.com/2026/04/19/us-news/iowa-sho...
3,2026-04-19-10-44-56 +0000,nypost,Chicago mayor links restaurant industry to ‘sl...,https://nypost.com/2026/04/19/us-news/chicago-...
4,2026-04-19-10-37-45 +0000,nyt,"Book Review: ‘When We See You Again,’ by Rache...",https://www.nytimes.com/2026/04/19/books/revie...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
65   trump     23
167   iran     15
168    war     11
546    new      9
247   pope      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
62,2026-04-19-03-49-45 +0000,nypost,JD Vance ‘grateful’ to Pope Leo for easing ten...,https://nypost.com/2026/04/18/world-news/jd-va...,81
150,2026-04-18-16-53-30 +0000,nypost,Pope Leo says it is ‘not in my interest at all...,https://nypost.com/2026/04/18/world-news/pope-...,74
20,2026-04-19-09-06-41 +0000,nyt,Iran War Live Updates: Strait of Hormuz Largel...,https://www.nytimes.com/live/2026/04/19/world/...,61
78,2026-04-19-01-00-00 +0000,wsj,Behind Trump’s public bravado on the war in Ir...,https://www.wsj.com/politics/national-security...,61
85,2026-04-19-00-02-30 +0000,nyt,U.S. Installs a Trump Loyalist to Lead ‘Grand ...,https://www.nytimes.com/2026/04/18/us/politics...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
62,81,2026-04-19-03-49-45 +0000,nypost,JD Vance ‘grateful’ to Pope Leo for easing ten...,https://nypost.com/2026/04/18/world-news/jd-va...
158,47,2026-04-18-16-00-00 +0000,wsj,Actual factory output is up sharply and may be...,https://www.wsj.com/economy/america-is-in-the-...
86,38,2026-04-19-00-00-00 +0000,wsj,Virginians face a ballot measure asking them w...,https://www.wsj.com/politics/elections/virgini...
151,35,2026-04-18-16-52-36 +0000,cbc,"Gunman who killed at least 6, took hostages in...",https://www.cbc.ca/news/world/ukraine-fatal-sh...
118,33,2026-04-18-20-55-28 +0000,nypost,Iran’s maimed Supreme Leader Khamenei issues n...,https://nypost.com/2026/04/18/world-news/supre...
142,29,2026-04-18-17-19-00 +0000,wsj,President Trump signed an executive order Satu...,https://www.wsj.com/politics/policy/how-joe-ro...
147,27,2026-04-18-17-10-11 +0000,nypost,NJ Transit CEO defends massive World Cup fare ...,https://nypost.com/2026/04/18/world-news/nj-tr...
2,24,2026-04-19-10-53-38 +0000,nypost,‘Multiple victims’ injured after gunfire break...,https://nypost.com/2026/04/19/us-news/iowa-sho...
123,24,2026-04-18-20-35-10 +0000,wapo,Iran closes Strait of Hormuz again; 2 ships re...,https://www.washingtonpost.com/world/2026/04/1...
56,22,2026-04-19-05-05-54 +0000,nypost,Elon Musk fulfills teen’s last wish in touchin...,https://nypost.com/2026/04/19/us-news/elon-mus...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)