## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-11-11-48-00 +0000,wsj,American Hantavirus Cruise Passengers Flown to...,https://www.wsj.com/world/u-s-hantavirus-cruis...
1,2026-05-11-11-41-23 +0000,nyt,Starmer Promises Urgent Change as He Battles t...,https://www.nytimes.com/2026/05/11/world/europ...
2,2026-05-11-11-36-56 +0000,nyt,Democratic Angst Could Lead California to Chan...,https://www.nytimes.com/2026/05/10/us/californ...
3,2026-05-11-11-35-52 +0000,nypost,High school counselor busted for allegedly hav...,https://nypost.com/2026/05/11/us-news/high-sch...
4,2026-05-11-11-34-11 +0000,nyt,"Sara Duterte, Philippine Vice President, Is Im...",https://www.nytimes.com/2026/05/11/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2490/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
113       trump     32
87         iran     23
1    hantavirus     17
88          war     15
188         new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
26,2026-05-11-10-51-48 +0000,nyt,Iran War Live Updates: Iran Lists Demands That...,https://www.nytimes.com/live/2026/05/11/world/...,105
236,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,101
129,2026-05-11-01-55-13 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,97
76,2026-05-11-09-01-41 +0000,bbc,Oil prices jump after Trump dismisses Iran pro...,https://www.bbc.com/news/articles/ckgp4ev4yg4o...,97
102,2026-05-11-06-52-00 +0000,wsj,Oil Climbs as Trump Rejects Iran’s Response to...,https://www.wsj.com/finance/commodities-future...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
26,105,2026-05-11-10-51-48 +0000,nyt,Iran War Live Updates: Iran Lists Demands That...,https://www.nytimes.com/live/2026/05/11/world/...
188,63,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...
127,40,2026-05-11-02-00-00 +0000,wsj,Women are playing a bigger role in the America...,https://www.wsj.com/economy/jobs/a-changing-jo...
236,36,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
48,34,2026-05-11-10-00-00 +0000,nypost,Inside Meta’s threat to exit New Mexico over k...,https://nypost.com/2026/05/11/business/inside-...
101,33,2026-05-11-06-55-06 +0000,nypost,50-year-old missing persons cold case cracked ...,https://nypost.com/2026/05/11/us-news/missing-...
147,30,2026-05-10-23-32-40 +0000,bbc,"This couple lost £1,000 after their flight was...",https://www.bbc.com/news/articles/cx215yldr13o...
33,28,2026-05-11-10-28-00 +0000,wsj,"U.S. Treasury Yields, Dollar Edge Up as Odds o...",https://www.wsj.com/finance/investing/jgb-futu...
57,28,2026-05-11-09-30-00 +0000,nypost,Families of Americans imprisoned in China have...,https://nypost.com/2026/05/11/us-news/family-o...
140,27,2026-05-11-00-30-56 +0000,bbc,Chris Mason: Another crunch moment for Starmer...,https://www.bbc.com/news/articles/cevp4kr79e4o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)