## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-03-50-54 +0000,nyt,U.S. Sends Plane to Cuba to Get Child in Trans...,https://www.nytimes.com/2026/04/21/world/ameri...
1,2026-04-22-03-48-00 +0000,nyt,Two Drugs Stir Hope for Treatment of Deadly Pa...,https://www.nytimes.com/2026/04/21/business/pa...
2,2026-04-22-03-45-17 +0000,nyt,Man Is Charged With Providing Gun to Louisiana...,https://www.nytimes.com/2026/04/21/us/man-char...
3,2026-04-22-03-28-52 +0000,bbc,World's biggest condom maker to raise prices d...,https://www.bbc.com/news/articles/cy71zj1381po...
4,2026-04-22-03-26-28 +0000,nyt,Iran War Live Updates: Trump Extends Cease-Fir...,https://www.nytimes.com/live/2026/04/21/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2503/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
31      trump     36
27       iran     35
261       new     21
35   virginia     16
352        up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,170
4,2026-04-22-03-26-28 +0000,nyt,Iran War Live Updates: Trump Extends Cease-Fir...,https://www.nytimes.com/live/2026/04/21/world/...,147
60,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,132
314,2026-04-21-13-14-14 +0000,nypost,Trump doesn’t want to extend Iran cease-fire —...,https://nypost.com/2026/04/21/us-news/trump-do...,112
146,2026-04-21-21-04-48 +0000,nyt,Trump Extends Iran Cease-Fire Before Deadline ...,https://www.nytimes.com/2026/04/21/us/politics...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,170,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
33,64,2026-04-22-01-52-00 +0000,nyt,Here’s What the New Virginia House Map Looks Like,https://www.nytimes.com/2026/04/21/us/election...
31,57,2026-04-22-01-58-00 +0000,wsj,President Trump’s pick to lead the Federal Res...,https://www.wsj.com/economy/central-banking/wa...
218,53,2026-04-21-18-15-31 +0000,nypost,Rep. Sheila Cherfilus-McCormick resigns from C...,https://nypost.com/2026/04/21/us-news/rep-shei...
211,48,2026-04-21-18-54-04 +0000,nyt,Two Palestinians Killed in Israeli Shooting Ne...,https://www.nytimes.com/2026/04/21/world/middl...
240,39,2026-04-21-17-16-29 +0000,nypost,Mexico temple gunman ranted about ancient buil...,https://nypost.com/2026/04/21/world-news/mexic...
152,37,2026-04-21-20-57-34 +0000,nypost,"Gates Foundation cutting 20% of staff, launche...",https://nypost.com/2026/04/21/business/gates-f...
116,36,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
25,35,2026-04-22-02-22-51 +0000,nypost,NYPD identifies teen who allegedly gunned down...,https://nypost.com/2026/04/21/us-news/nypd-ide...
339,35,2026-04-21-11-38-36 +0000,wapo,Japan lifts post-World War II ban on lethal we...,https://www.washingtonpost.com/world/2026/04/2...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)