## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-17-13-40 +0000,bbc,"More than 250,000 flee wildfires in France and...",https://www.bbc.co.uk/news/articles/cd7le0d53y...
1,2026-07-25-17-10-00 +0000,wsj,Maine Democrats choose Troy Jackson to replace...,https://www.wsj.com/politics/maine-democrats-c...
2,2026-07-25-17-08-30 +0000,nyt,"After Democratic Shake-Up, Susan Collins Holds...",https://www.nytimes.com/2026/07/25/us/politics...
3,2026-07-25-17-07-41 +0000,nyt,India’s Education Minister Steps Down in Victo...,https://www.nytimes.com/2026/07/25/world/asia/...
4,2026-07-25-17-04-58 +0000,nypost,Arizona woman sues after food delivery robot a...,https://nypost.com/2026/07/25/us-news/arizona-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2727/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
55    trump     36
50     iran     25
46      new     21
51      war     11
240  market      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,97
7,2026-07-25-16-56-32 +0000,nyt,"Iran War Live Updates: U.S. Strikes Abate, Eve...",https://www.nytimes.com/live/2026/07/25/world/...,90
194,2026-07-24-21-41-12 +0000,nyt,Trump Meets With Top Advisers as He Weighs a M...,https://www.nytimes.com/2026/07/24/us/politics...,87
230,2026-07-24-20-11-48 +0000,nypost,US ‘locked and loaded’ for ‘massive attack’ on...,https://nypost.com/2026/07/24/us-news/us-locke...,85
105,2026-07-25-09-01-58 +0000,nyt,President Trump’s New Air Force One Poses Pote...,https://www.nytimes.com/video/us/1000000110477...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,97,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...
23,63,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...
192,51,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
10,45,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...
67,40,2026-07-25-12-30-22 +0000,cbc,Tour de France final stage shortened to redepl...,https://www.cbc.ca/news/world/wildfire-evacuat...
28,34,2026-07-25-15-33-08 +0000,wapo,Houthis claim attack on Saudi oil refinery as ...,https://www.washingtonpost.com/world/2026/07/2...
214,32,2026-07-24-20-49-00 +0000,wsj,The U.S. will consider applying additional tar...,https://www.wsj.com/economy/trade/trump-threat...
123,31,2026-07-25-04-36-00 +0000,wsj,During a gala Friday celebrating press freedom...,https://www.wsj.com/politics/elections/five-ma...
211,31,2026-07-24-21-02-30 +0000,bbc,ICC top prosecutor removed over sexual miscond...,https://www.bbc.co.uk/news/articles/cqjxddx12q...
31,30,2026-07-25-15-15-42 +0000,nypost,91% of NYC high rises skip 13th floor — and bu...,https://nypost.com/2026/07/25/world-news/unluc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)