## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-15-22-30-52 +0000,bbc,Eight feared dead after US Air Force B-52 bomb...,https://www.bbc.com/news/articles/cqx10yql319o...
1,2026-06-15-22-30-01 +0000,nypost,Iran could ‘access’ $300B for rebuilding under...,https://nypost.com/2026/06/15/world-news/heres...
2,2026-06-15-22-26-58 +0000,nypost,Lefty challenger to Queens Rep. Grace Meng tak...,https://nypost.com/2026/06/15/us-news/lefty-ch...
3,2026-06-15-22-26-14 +0000,cbc,Government abruptly suspends citizenship certi...,https://www.cbc.ca/news/politics/canadian-citi...
4,2026-06-15-22-22-42 +0000,nyt,Iran War Live Updates: U.S. and Iran Sign Prel...,https://www.nytimes.com/live/2026/06/15/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
8      iran     61
46    trump     53
12     deal     50
97    world     16
111  hormuz     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
206,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...,251
126,2026-06-15-18-27-23 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,230
138,2026-06-15-17-34-00 +0000,wsj,Trump Says Strait of Hormuz Will Be Fully Open...,https://www.wsj.com/world/middle-east/question...,227
192,2026-06-15-14-41-16 +0000,nypost,Why Strait of Hormuz still hasn’t reopened to ...,https://nypost.com/2026/06/15/world-news/why-s...,210
4,2026-06-15-22-22-42 +0000,nyt,Iran War Live Updates: U.S. and Iran Sign Prel...,https://www.nytimes.com/live/2026/06/15/world/...,202

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
206,251,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...
45,70,2026-06-15-21-11-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
202,58,2026-06-15-14-17-00 +0000,wsj,"A rowdy, controversial evening of mixed-martia...",https://www.wsj.com/arts-culture/books/trump-u...
11,55,2026-06-15-22-03-04 +0000,nypost,More travel chaos set to plague Tuesday’s Worl...,https://nypost.com/2026/06/15/us-news/more-tra...
242,47,2026-06-15-11-45-22 +0000,wapo,Britain announces sweeping ban on most social ...,https://www.washingtonpost.com/world/2026/06/1...
237,44,2026-06-15-12-15-46 +0000,nypost,Video shows helicopter in crash that killed Ol...,https://nypost.com/2026/06/15/world-news/video...
227,42,2026-06-15-12-50-18 +0000,cbc,Global stocks soar and oil prices drop as U.S....,https://www.cbc.ca/news/business/stock-oil-mar...
175,40,2026-06-15-15-41-43 +0000,nyt,Two Men Found Guilty in Arson Attacks Targetin...,https://www.nytimes.com/2026/06/15/world/europ...
167,36,2026-06-15-16-22-54 +0000,startribune,Gas prices are dropping in Minnesota. It’s ‘ha...,https://www.startribune.com/gas-prices-are-dro...
74,34,2026-06-15-20-30-14 +0000,nypost,Historic NBA Championship fuels record-breakin...,https://nypost.com/2026/06/15/business/histori...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)