## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-23-10-53-00 +0000,wsj,Russia’s Central Bank Sees Only Modest Further...,https://www.wsj.com/pro/central-banking/russia...
1,2026-10-23-10-49-36 +0000,bbc,Earnings limit of up to £140K for first-time b...,https://www.bbc.co.uk/news/articles/c6n8dex0ze...
2,2026-10-23-10-46-00 +0000,wsj,"U.S. Dollar, Treasury Yields Rise",https://www.wsj.com/finance/currencies/dollar-...
3,2026-10-23-10-43-04 +0000,cbc,Carney defends doing business with countries t...,https://www.cbc.ca/news/politics/canada-turkey...
4,2026-10-23-10-38-00 +0000,wsj,WTI Climbs Above $101 a Barrel on U.S.-Iran Es...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2398/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
57        trump     37
185         new     24
196          ai     18
176  california     17
12           up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
143,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,109
404,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...,105
396,2026-10-22-11-53-48 +0000,chitri,Deportations climb under President Donald Trum...,https://www.chicagotribune.com/2026/10/22/depo...,104
41,2026-10-23-09-30-00 +0000,wsj,Capital Account: President Trump once called “...,https://www.wsj.com/economy/trade/how-tariffs-...,99
141,2026-10-23-01-38-03 +0000,nypost,Trump administration raises stakes in bombshel...,https://nypost.com/2026/10/22/us-news/trump-do...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
143,109,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
93,75,2026-10-23-06-20-45 +0000,nypost,Sister of American held in Russia says he didn...,https://nypost.com/2026/10/23/us-news/freed-am...
401,70,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...
336,68,2026-10-22-15-54-08 +0000,nypost,"Oil soars above $113, Nasdaq plummets in worst...",https://nypost.com/2026/10/22/business/oil-soa...
332,59,2026-10-22-16-00-00 +0000,nypost,Fed-up LA voters rage about Karen Bass — but f...,https://nypost.com/2026/10/22/us-news/karen-ba...
287,49,2026-10-22-18-26-56 +0000,bbc,Zuckerberg wins Meta deal to help him foot bil...,https://www.bbc.co.uk/news/articles/cky83vwnyg...
179,48,2026-10-22-22-23-00 +0000,wsj,The Justice Department is examining allegation...,https://www.wsj.com/politics/policy/corey-lewa...
275,46,2026-10-22-19-00-13 +0000,nypost,Trump tells Elon Musk to lift any limits on St...,https://nypost.com/2026/10/22/us-news/trump-ca...
386,42,2026-10-22-13-02-59 +0000,nyt,Covert Russian Group Targets James Talarico Wi...,https://www.nytimes.com/2026/10/22/us/texas-se...
12,41,2026-10-23-10-26-06 +0000,bbc,Five Israelis wounded and two suspected Palest...,https://www.bbc.co.uk/news/articles/cq4g1p974w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)