## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-16-14-39 +0000,nyt,Iran War Live Updates: U.S. Begins Blockade in...,https://www.nytimes.com/live/2026/04/13/world/...
1,2026-04-13-16-14-00 +0000,wsj,Opinion | It Is No Surprise Young Israelis Are...,https://www.wsj.com/opinion/it-is-no-surprise-...
2,2026-04-13-16-13-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
3,2026-04-13-16-12-31 +0000,nypost,Top Trump official roasts gloating California ...,https://nypost.com/2026/04/13/us-news/top-trum...
4,2026-04-13-16-11-36 +0000,nyt,Two Iran-linked Ships Passed Through Strait of...,https://www.nytimes.com/2026/04/13/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
14     trump     50
0       iran     42
5   blockade     29
7     hormuz     23
31  swalwell     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,180
113,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,178
180,2026-04-13-06-48-00 +0000,wsj,"Gold Falls as Trump Hormuz Blockade Threats, F...",https://www.wsj.com/finance/commodities-future...,178
289,2026-04-12-17-52-32 +0000,nypost,Iran issues dire warning about President Trump...,https://nypost.com/2026/04/12/world-news/iran-...,177
2,2026-04-13-16-13-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,170

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,180,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...
216,110,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
123,76,2026-04-13-11-03-00 +0000,wsj,Two of the most recognizable people on the pla...,https://www.wsj.com/politics/the-showdown-betw...
243,60,2026-04-12-22-24-01 +0000,nyt,Hungary Election Results: Viktor Orban Concede...,https://www.nytimes.com/2026/04/12/world/europ...
269,53,2026-04-12-19-43-08 +0000,nyt,"Israel Launches New Attacks in Lebanon, Days A...",https://www.nytimes.com/2026/04/12/world/middl...
272,37,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
290,37,2026-04-12-17-47-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
22,33,2026-04-13-15-50-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
212,33,2026-04-13-01-36-13 +0000,nypost,"Trump blasts Pope Leo as ‘weak on crime,’ says...",https://nypost.com/2026/04/12/us-news/trump-bl...
262,28,2026-04-12-21-01-09 +0000,nypost,UK regulators rushing to assess risks of lates...,https://nypost.com/2026/04/12/business/uk-regu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)