## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-13-15-35 +0000,nypost,Top aides to under-fire Labor Secretary Lori C...,https://nypost.com/2026/03/03/us-news/top-aide...
1,2026-03-03-13-13-54 +0000,nyt,Live Updates: U.S. Closes 2 Gulf Embassies; Is...,https://www.nytimes.com/live/2026/03/03/world/...
2,2026-03-03-13-13-52 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/03/world/...
3,2026-03-03-13-12-00 +0000,wsj,"On Holding Posts Higher Profit, Sales; Outlook...",https://www.wsj.com/business/earnings/on-holdi...
4,2026-03-03-13-11-46 +0000,nyt,Global Markets Tumble as Iran War Intensifies,https://www.nytimes.com/2026/03/03/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2657/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
34      iran     93
127    trump     59
35       war     41
52   strikes     24
159      oil     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
314,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,318
310,2026-03-02-20-15-54 +0000,nypost,Trump ordered Iran war — then ordered ‘hamburg...,https://nypost.com/2026/03/02/us-news/trump-or...,236
356,2026-03-02-18-15-39 +0000,latimes,News Analysis: Trump is rewriting the 'you bre...,https://www.latimes.com/politics/story/2026-03...,219
194,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...,213
176,2026-03-03-02-36-25 +0000,nyt,Melania Trump Promotes ‘Peace Through Educatio...,https://www.nytimes.com/2026/03/02/us/politics...,209

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
314,318,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
245,87,2026-03-02-22-57-08 +0000,nyt,Iranian Strikes Hit Qatar and Saudi Energy Sit...,https://www.nytimes.com/2026/03/02/world/middl...
93,75,2026-03-03-10-30-00 +0000,wsj,Americans weary of high prices have recently b...,https://www.wsj.com/business/energy-oil/what-t...
94,69,2026-03-03-10-30-00 +0000,wsj,"A tight, three-way race for a Texas Senate sea...",https://www.wsj.com/politics/elections/what-to...
7,53,2026-03-03-13-10-36 +0000,wapo,Live updates: U.S. closes two gulf embassies a...,https://www.washingtonpost.com/world/2026/03/0...
220,51,2026-03-03-00-15-58 +0000,nypost,Supreme Court blocks California law that stopp...,https://nypost.com/2026/03/02/us-news/supreme-...
54,48,2026-03-03-11-32-52 +0000,nypost,Austin mass shooter was not on the FBI’s radar...,https://nypost.com/2026/03/03/us-news/austin-m...
385,46,2026-03-02-16-46-23 +0000,cbc,U.S. military leaders lay out timeline of atta...,https://www.cbc.ca/news/world/us-pentagon-iran...
211,44,2026-03-03-00-45-00 +0000,wsj,Here are some key moments from the depositions...,https://www.wsj.com/politics/key-moments-from-...
389,38,2026-03-02-16-34-18 +0000,wapo,Videos appear to show the moments U.S. fighter...,https://www.washingtonpost.com/investigations/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)