## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-02-22-57-46 +0000,nypost,911 calls from Tiger Woods’ rollover DUI crash...,https://nypost.com/2026/04/02/sports/911-calls...
1,2026-04-02-22-57-37 +0000,bbc,Hegseth asks US Army Chief of Staff to step down,https://www.bbc.com/news/articles/cn8d63v058zo...
2,2026-04-02-22-50-59 +0000,startribune,Taj Bradley’s strong outing helps Twins salvag...,https://www.startribune.com/twins-beat-royals-...
3,2026-04-02-22-49-15 +0000,missionlocal,Sunday Streets meets fundraising goal to host ...,https://missionlocal.org/2026/04/sunday-street...
4,2026-04-02-22-48-00 +0000,wsj,Blake Lively ‘It Ends With Us’ Sexual- Harassm...,https://www.wsj.com/business/media/blake-livel...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2566/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
70     trump     82
78      iran     50
77       war     36
365      new     15
59   general     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-04-02-16-18-14 +0000,latimes,"Trump speech on Iran war, recent remarks on oi...",https://www.latimes.com/politics/story/2026-04...,207
330,2026-04-02-02-48-00 +0000,wsj,President Trump sought to reassure skeptical A...,https://www.wsj.com/politics/national-security...,201
101,2026-04-02-20-20-20 +0000,nyt,Trump Says He’ll End the Iran War in Weeks. Wh...,https://www.nytimes.com/2026/04/02/us/politics...,200
28,2026-04-02-22-11-12 +0000,wapo,"As Trump doubles down on Iran war, markets shu...",https://www.washingtonpost.com/world/2026/04/0...,198
343,2026-04-02-01-39-31 +0000,latimes,"In major speech, Trump says Iran war will be o...",https://www.latimes.com/politics/story/2026-04...,192

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,207,2026-04-02-16-18-14 +0000,latimes,"Trump speech on Iran war, recent remarks on oi...",https://www.latimes.com/politics/story/2026-04...
6,86,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...
126,61,2026-04-02-19-20-01 +0000,nypost,Pam Bondi speaks out for the first time after ...,https://nypost.com/2026/04/02/us-news/pam-bond...
275,60,2026-04-02-10-00-00 +0000,latimes,This California 8-year-old designed a 'zero gr...,https://www.latimes.com/california/story/2026-...
180,50,2026-04-02-16-36-00 +0000,wsj,President Trump has used tariffs to remake U.S...,https://www.wsj.com/politics/policy/how-trump-...
83,47,2026-04-02-20-55-15 +0000,nypost,Tanker ships must pay Iran’s Revolutionary Gua...,https://nypost.com/2026/04/02/world-news/tanke...
309,40,2026-04-02-07-35-02 +0000,nypost,"Earthquake off Indonesia topples buildings, ki...",https://nypost.com/2026/04/02/world-news/indon...
246,40,2026-04-02-12-40-00 +0000,wsj,Trump endorsed a two-part plan to quickly fund...,https://www.wsj.com/politics/policy/trump-lays...
173,39,2026-04-02-17-02-47 +0000,nyt,"In Supreme Court Birthright Citizenship Case, ...",https://www.nytimes.com/2026/04/02/us/politics...
36,37,2026-04-02-21-49-21 +0000,nypost,‘Dictator’ Mamdani has even his far-left NYC C...,https://nypost.com/2026/04/02/us-news/dictator...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)