## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-18-23-02-48 +0000,bbc,Scammers are becoming ever more sophisticated ...,https://www.bbc.com/news/articles/cj60pl5g4z4o...
1,2026-04-18-23-01-08 +0000,bbc,I'm a carer but I can't afford to go to work b...,https://www.bbc.com/news/articles/cx2d1jpl543o...
2,2026-04-18-23-00-00 +0000,wsj,The Seaside Town Trying to Reclaim Its Title a...,https://www.wsj.com/us-news/the-seaside-town-t...
3,2026-04-18-22-57-32 +0000,nypost,Terrifying mutant dog-bots with Elon Musk and ...,https://nypost.com/2026/04/18/us-news/terrifyi...
4,2026-04-18-22-55-11 +0000,startribune,Live from Dallas: Wild take 3-0 lead over Star...,https://www.startribune.com/minnesota-wild-liv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
79    trump     24
50     iran     23
159     new     12
51      war     10
56   hormuz      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
78,2026-04-18-16-53-30 +0000,nypost,Pope Leo says it is ‘not in my interest at all...,https://nypost.com/2026/04/18/world-news/pope-...,79
173,2026-04-18-02-04-38 +0000,nyt,Trump Frames Iran War as All but Over in Optim...,https://www.nytimes.com/2026/04/17/world/middl...,71
6,2026-04-18-22-46-24 +0000,nyt,Iran War Live Updates: Tensions Rise in Strait...,https://www.nytimes.com/live/2026/04/18/world/...,67
32,2026-04-18-20-55-28 +0000,nypost,Iran’s maimed Supreme Leader Khamenei issues n...,https://nypost.com/2026/04/18/world-news/supre...,63
158,2026-04-18-06-51-28 +0000,wapo,Iran disputes claims of new agreements with Trump,https://www.washingtonpost.com/world/2026/04/1...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
78,79,2026-04-18-16-53-30 +0000,nypost,Pope Leo says it is ‘not in my interest at all...,https://nypost.com/2026/04/18/world-news/pope-...
176,42,2026-04-18-01-38-00 +0000,wsj,New York City doormen and building owners reac...,https://www.wsj.com/economy/housing/the-week-n...
88,36,2026-04-18-16-00-00 +0000,wsj,Actual factory output is up sharply and may be...,https://www.wsj.com/economy/america-is-in-the-...
46,35,2026-04-18-20-15-40 +0000,nypost,FDNY changes policy after clout-chasing models...,https://nypost.com/2026/04/18/us-news/fdny-cha...
79,35,2026-04-18-16-52-36 +0000,cbc,"Gunman who killed at least 6, took hostages in...",https://www.cbc.ca/news/world/ukraine-fatal-sh...
6,34,2026-04-18-22-46-24 +0000,nyt,Iran War Live Updates: Tensions Rise in Strait...,https://www.nytimes.com/live/2026/04/18/world/...
89,29,2026-04-18-15-58-44 +0000,nypost,"US planning to seize Iran-linked oil tankers, ...",https://nypost.com/2026/04/18/world-news/us-pl...
32,26,2026-04-18-20-55-28 +0000,nypost,Iran’s maimed Supreme Leader Khamenei issues n...,https://nypost.com/2026/04/18/world-news/supre...
190,24,2026-04-18-00-21-57 +0000,latimes,"Teen on electric motorcycle hits 81-year-old, ...",https://www.latimes.com/california/story/2026-...
69,24,2026-04-18-17-19-00 +0000,wsj,President Trump signed an executive order Satu...,https://www.wsj.com/politics/policy/how-joe-ro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)