## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-23-16-58-03 +0000,nypost,Chucky mask sicko Zymire Hughes could be lurki...,https://nypost.com/2026/08/23/us-news/chucky-m...
1,2026-08-23-16-40-28 +0000,nypost,Pacific Palisades residents build blockade ami...,https://nypost.com/2026/08/23/us-news/pacific-...
2,2026-08-23-16-30-58 +0000,latimes,Thousands evacuated as Hawk fire burns over 10...,https://www.latimes.com/california/story/2026-...
3,2026-08-23-16-30-00 +0000,wsj,Opinion | The Brave Witness of Chow Hang-tung,https://www.wsj.com/opinion/the-brave-witness-...
4,2026-08-23-16-30-00 +0000,wsj,Opinion | AOC’s Craaazy Economic Theory Lives On,https://www.wsj.com/opinion/aocs-craaazy-econo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2473/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
59    trump     22
179   trade     15
178  canada     13
290     new     12
95      war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
177,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,97
48,2026-08-23-13-22-13 +0000,nypost,Canadian PM Mark Carney claims country ‘at war...,https://nypost.com/2026/08/23/us-news/canadian...,79
121,2026-08-23-07-15-52 +0000,nyt,Carney Stands Up to Trump in U.S.-Canada Trade...,https://www.nytimes.com/2026/08/22/world/canad...,76
60,2026-08-23-12-33-01 +0000,cbc,Trump says Canada 'wants the benefits' of bein...,https://www.cbc.ca/news/canada/trump-canada-tr...,70
159,2026-08-22-21-27-04 +0000,wapo,Trump’s new tariffs on Canada will hit everyth...,https://www.washingtonpost.com/business/2026/0...,69

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
177,97,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
12,67,2026-08-23-16-02-38 +0000,nypost,Iran’s top civilian leaders push for cutting a...,https://nypost.com/2026/08/23/us-news/irans-to...
13,33,2026-08-23-16-01-28 +0000,nypost,Iranian-linked hackers shut down British power...,https://nypost.com/2026/08/23/world-news/irani...
126,31,2026-08-23-05-58-07 +0000,nypost,Alaska Dem Senate hopeful Mary Peltola racked ...,https://nypost.com/2026/08/23/us-news/alaska-d...
78,30,2026-08-23-10-00-37 +0000,chitri,Data centers near O’Hare win nearly $100M in l...,https://www.chicagotribune.com/2026/08/23/spec...
110,28,2026-08-23-09-00-34 +0000,nyt,Someone Was Impersonating Collien Fernandes On...,https://www.nytimes.com/2026/08/23/magazine/co...
65,27,2026-08-23-12-04-46 +0000,nypost,Driver who died crashing SUV into Long Island ...,https://nypost.com/2026/08/23/us-news/driver-w...
27,26,2026-08-23-15-07-35 +0000,chitri,Mark Carney warned about economic coercion. No...,https://www.chicagotribune.com/2026/08/23/mark...
30,26,2026-08-23-15-00-00 +0000,wsj,Dozens of IndyCars will blaze through the hear...,https://www.wsj.com/us-news/147-laps-around-th...
151,24,2026-08-22-22-36-03 +0000,nypost,New footage of El Chapo’s first hours in capti...,https://nypost.com/2026/08/22/world-news/new-v...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)