## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-08-19-04-40 +0000,nyt,"Iran Issues List of Demands, Dampening Hopes o...",https://www.nytimes.com/2026/08/08/world/middl...
1,2026-08-08-19-01-48 +0000,nypost,Iran’s top security official threatens Hormuz ...,https://nypost.com/2026/08/08/world-news/iran-...
2,2026-08-08-19-00-22 +0000,bbc,"Australia is the planet's extinction hotspot, ...",https://www.bbc.co.uk/news/articles/c9q94lxqrz...
3,2026-08-08-18-57-33 +0000,nyt,Does the Fifth Amendment Protect Fauci?,https://www.nytimes.com/video/us/politics/1000...
4,2026-08-08-18-56-45 +0000,nypost,Iran’s Pickaxe Mountain in Trump’s sights,https://nypost.com/2026/08/08/us-news/irans-pi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
35    trump     29
174  senate     15
0      iran     13
120     new     11
796   court     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,106
215,2026-08-07-20-46-00 +0000,wsj,Trump revives effort to oust Fed governor Lisa...,https://www.wsj.com/politics/white-house-reviv...,97
245,2026-08-07-19-25-36 +0000,wapo,Trump renews effort to fire Fed governor Lisa ...,https://www.washingtonpost.com/business/2026/0...,89
123,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...,87
231,2026-08-07-20-11-19 +0000,nypost,Trump revives bid to fire Fed Gov. Lisa Cook a...,https://nypost.com/2026/08/07/business/trump-r...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,106,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
145,59,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...
123,58,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...
25,42,2026-08-08-17-44-34 +0000,nypost,Miss North Carolina USA producers deny Brittan...,https://nypost.com/2026/08/08/us-news/miss-nor...
46,39,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
211,38,2026-08-07-20-50-01 +0000,nypost,"Saudi Arabia, Turkey and Pakistan forge ‘attac...",https://nypost.com/2026/08/07/world-news/saudi...
246,37,2026-08-07-19-22-00 +0000,wsj,The U.S. Army is expanding access to its test ...,https://www.wsj.com/politics/national-security...
214,35,2026-08-07-20-47-19 +0000,chitri,Senate passes sweeping Russia sanctions bill n...,https://www.chicagotribune.com/2026/08/07/sena...
9,29,2026-08-08-18-51-08 +0000,nypost,California beauty queen fighting for her life ...,https://nypost.com/2026/08/08/us-news/beauty-q...
111,28,2026-08-08-09-24-02 +0000,nypost,Russian attacks kill 4 in Kyiv and surrounding...,https://nypost.com/2026/08/08/world-news/russi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)