## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-21-59-24 +0000,nyt,House Turns Back Bid to Restrict Trump’s War P...,https://www.nytimes.com/2026/03/05/us/politics...
1,2026-03-05-21-59-23 +0000,nyt,Here is the latest.,https://www.nytimes.com/live/2026/03/05/world/...
2,2026-03-05-21-59-00 +0000,wsj,"What to know about Markwayne Mullin, the Repub...",https://www.wsj.com/politics/policy/markwayne-...
3,2026-03-05-21-54-45 +0000,nyt,Live Updates: Trump Says He Should Have a Role...,https://www.nytimes.com/live/2026/03/05/world/...
4,2026-03-05-21-54-22 +0000,nyt,Australia’s Sydney Jewish Museum to Memorializ...,https://www.nytimes.com/2026/03/05/world/austr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7       iran     67
4      trump     48
5        war     43
205      new     19
370  iranian     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
14,2026-03-05-21-46-06 +0000,bbc,House rejects bid to curb Trump's war powers o...,https://www.bbc.com/news/articles/c98qm5m8dj6o...,187
0,2026-03-05-21-59-24 +0000,nyt,House Turns Back Bid to Restrict Trump’s War P...,https://www.nytimes.com/2026/03/05/us/politics...,186
347,2026-03-05-05-07-22 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,185
399,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,177
309,2026-03-05-10-03-58 +0000,nyt,Trump Wants a Quick Victory in Iran. But the W...,https://www.nytimes.com/2026/03/05/us/politics...,168

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
14,187,2026-03-05-21-46-06 +0000,bbc,House rejects bid to curb Trump's war powers o...,https://www.bbc.com/news/articles/c98qm5m8dj6o...
63,99,2026-03-05-20-32-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...
130,96,2026-03-05-19-02-00 +0000,wsj,House Speaker Mike Johnson and other top GOP l...,https://www.wsj.com/politics/texas-tony-gonzal...
324,72,2026-03-05-08-52-04 +0000,nypost,Iranian bombers came within ‘two minutes’ of s...,https://nypost.com/2026/03/05/world-news/irani...
218,57,2026-03-05-15-51-35 +0000,cbc,Ukraine support remains front and centre amid ...,https://www.cbc.ca/news/world/rutte-zelenskyy-...
8,49,2026-03-05-21-50-02 +0000,wapo,Live updates: Israel warns Lebanese to flee fo...,https://www.washingtonpost.com/world/2026/03/0...
12,43,2026-03-05-21-48-00 +0000,wsj,The Defense Department has officially told Ant...,https://www.wsj.com/politics/national-security...
85,41,2026-03-05-19-56-00 +0000,wsj,"For the First Time, U.S. Sides With Russia and...",https://www.wsj.com/world/for-the-first-time-u...
390,40,2026-03-05-00-09-17 +0000,latimes,"Ex-water polo player alleges racist slurs, sex...",https://www.latimes.com/california/story/2026-...
70,36,2026-03-05-20-18-21 +0000,nypost,White House vows to ‘vigorously defend’ tariff...,https://nypost.com/2026/03/05/us-news/trumps-n...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)