## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
1,2026-07-01-14-44-00 +0000,wsj,Opinion | Tocqueville at the World Cup,https://www.wsj.com/opinion/tocqueville-at-the...
2,2026-07-01-14-44-00 +0000,wsj,Trump Made More Than $1 Billion on Crypto Deal...,https://www.wsj.com/politics/policy/trump-made...
3,2026-07-01-14-43-32 +0000,nyt,Trump Pulled In About $1.4 Billion From Crypto...,https://www.nytimes.com/2026/06/30/us/politics...
4,2026-07-01-14-43-24 +0000,nyt,The Birthright Decision Was Surprisingly Close...,https://www.nytimes.com/2026/07/01/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
1      trump     43
223    court     30
222  supreme     29
115      new     19
8       year     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
395,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,147
298,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,138
169,2026-07-01-05-32-26 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,137
227,2026-06-30-23-15-01 +0000,nyt,Trump Says It’s ‘Too Bad’ Supreme Court Upheld...,https://www.nytimes.com/2026/06/30/us/politics...,137
81,2026-07-01-11-10-00 +0000,wsj,Three places where this Supreme Court fenced T...,https://www.wsj.com/politics/three-places-wher...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
395,147,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...
127,80,2026-07-01-09-30-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
0,54,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
197,49,2026-07-01-01-24-59 +0000,nyt,Driver Is Reported Dead Days After Plowing Int...,https://www.nytimes.com/2026/06/30/world/ameri...
148,46,2026-07-01-07-59-24 +0000,wsj,"Stock Market Today: Nasdaq Slips, Warsh Dodges...",https://www.wsj.com/livecoverage/stock-market-...
323,43,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
295,43,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
179,42,2026-07-01-04-15-11 +0000,nypost,Socialist congressional candidate Melat Kiros ...,https://nypost.com/2026/07/01/us-news/socialis...
320,37,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
61,35,2026-07-01-12-27-06 +0000,nypost,Harrowing 911 call reveals fight to save Britt...,https://nypost.com/2026/07/01/us-news/harrowin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)