## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-01-09-11 +0000,startribune,Live: Kirill Kaprizov strikes twice as Wild ba...,https://www.startribune.com/minnesota-wild-win...
1,2026-10-14-01-07-33 +0000,nypost,Jewish educators told to condemn Israel before...,https://nypost.com/2026/10/13/world-news/itali...
2,2026-10-14-01-05-47 +0000,startribune,"Minneapolis superintendent reverses course, re...",https://www.startribune.com/minneapolis-school...
3,2026-10-14-01-05-00 +0000,wsj,Gold Steady Ahead of U.S. Inflation Data,https://www.wsj.com/finance/commodities-future...
4,2026-10-14-01-00-00 +0000,wsj,Failure of Australia’s Largest IPO in Decades ...,https://www.wsj.com/finance/firmus-ipo-ai-trad...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2636/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
140      trump     37
38          ai     18
100        new     17
51    kimberly     15
52   guilfoyle     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
272,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,130
241,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,113
224,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,110
87,2026-10-13-21-54-45 +0000,nypost,Trump personally prepped Katie Zacharia for fi...,https://nypost.com/2026/10/13/us-news/trump-pe...,106
115,2026-10-13-21-13-00 +0000,wsj,Kimberly Guilfoyle resigned as the U.S. ambass...,https://www.wsj.com/politics/policy/kimberly-g...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
272,130,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...
80,83,2026-10-13-21-59-26 +0000,nypost,Off-duty NYPD cop stabbed in mugging reveals w...,https://nypost.com/2026/10/13/us-news/off-duty...
100,74,2026-10-13-21-34-51 +0000,latimes,Disney strikes $20-million deal for Character....,https://www.latimes.com/business/story/2026-10...
290,69,2026-10-13-13-12-18 +0000,wapo,Six Flags shuts roller coasters at six parks a...,https://www.washingtonpost.com/business/2026/1...
241,60,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...
123,55,2026-10-13-21-00-34 +0000,nypost,Rep. Ilhan Omar’s staff got her birthdate chan...,https://nypost.com/2026/10/13/us-news/rep-ilha...
323,51,2026-10-13-11-12-24 +0000,chitri,Vatican says Pope Leo XIV has lung cancer and ...,https://www.chicagotribune.com/2026/10/13/pope...
330,51,2026-10-13-10-41-00 +0000,wsj,Medicare for All has become a defining policy ...,https://www.wsj.com/politics/policy/medicare-f...
233,48,2026-10-13-16-04-03 +0000,nyt,MI5 Chief Warns of Escalating Hybrid Threats F...,https://www.nytimes.com/2026/10/13/world/europ...
189,47,2026-10-13-18-10-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)