## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-14-13-14 +0000,nypost,Israel imposes further airport restrictions fo...,https://nypost.com/2026/03/23/world-news/israe...
1,2026-03-23-14-12-48 +0000,nyt,Iran War Live Updates: Trump Postpones Deadlin...,https://www.nytimes.com/live/2026/03/23/world/...
2,2026-03-23-14-12-45 +0000,nyt,Oil Prices Tumble and Stocks Rise as Trump Bac...,https://www.nytimes.com/2026/03/23/business/oi...
3,2026-03-23-14-10-23 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/23/us/sup...
4,2026-03-23-14-09-40 +0000,nyt,The mail-in ballot rules have divided Republic...,https://www.nytimes.com/live/2026/03/23/us/sup...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
13  trump     42
9    iran     37
45    new     18
10    war     16
19    oil     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-23-14-12-48 +0000,nyt,Iran War Live Updates: Trump Postpones Deadlin...,https://www.nytimes.com/live/2026/03/23/world/...,157
34,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...,129
224,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,126
69,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,125
10,2026-03-23-14-05-04 +0000,startribune,US won't strike Iran's power plants for 5 days...,https://www.startribune.com/iran-threatens-to-...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,157,2026-03-23-14-12-48 +0000,nyt,Iran War Live Updates: Trump Postpones Deadlin...,https://www.nytimes.com/live/2026/03/23/world/...
120,72,2026-03-23-08-52-19 +0000,cbc,2 pilots killed after Air Canada plane collide...,https://www.cbc.ca/news/world/livestory/air-ca...
151,62,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
34,50,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...
262,39,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
149,35,2026-03-23-03-34-34 +0000,nyt,Israel’s Missile Defense Under Scrutiny After ...,https://www.nytimes.com/2026/03/22/world/middl...
31,31,2026-03-23-13-24-30 +0000,nyt,These 14 states could be affected by the Supre...,https://www.nytimes.com/live/2026/03/23/us/sup...
163,29,2026-03-23-01-30-48 +0000,nypost,TSA chaos hits California — as Gavin Newsom is...,https://nypost.com/2026/03/22/us-news/travel-n...
67,28,2026-03-23-11-29-26 +0000,bbc,France's former Socialist Prime Minister Lione...,https://www.bbc.com/news/articles/cp861v8mj8mo...
171,27,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)