## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-14-19-52 +0000,nyt,The early exception to birthright citizenship ...,https://www.nytimes.com/live/2026/04/01/us/sup...
1,2026-04-01-14-18-37 +0000,nyt,Placing U.S. Troops in Middle East Hotels May ...,https://www.nytimes.com/2026/04/01/us/politics...
2,2026-04-01-14-18-11 +0000,nyt,Iran War Live Updates: Trump Berates Allies Wh...,https://www.nytimes.com/live/2026/04/01/world/...
3,2026-04-01-14-18-10 +0000,nyt,Trump Says Europe Is On Its Own in Securing th...,https://www.nytimes.com/2026/04/01/world/middl...
4,2026-04-01-14-18-00 +0000,wsj,"Oil Eases, But Holds Around $100 on Hormuz Unc...",https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
19  trump     59
16   iran     49
15    war     42
38  court     19
24   will     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-01-14-18-11 +0000,nyt,Iran War Live Updates: Trump Berates Allies Wh...,https://www.nytimes.com/live/2026/04/01/world/...,231
82,2026-04-01-11-00-00 +0000,nypost,Families of American hostages — including one ...,https://nypost.com/2026/04/01/us-news/family-o...,208
296,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,182
151,2026-04-01-08-49-19 +0000,bbc,Oil briefly falls below $100 and shares jump o...,https://www.bbc.com/news/articles/c2489v97842o...,174
6,2026-04-01-14-13-00 +0000,wsj,Trump Raises NATO Withdrawal as Allies Push Ba...,https://www.wsj.com/world/trump-raises-nato-wi...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,231,2026-04-01-14-18-11 +0000,nyt,Iran War Live Updates: Trump Berates Allies Wh...,https://www.nytimes.com/live/2026/04/01/world/...
90,86,2026-04-01-10-58-00 +0000,wsj,"Even by the Supreme Court’s lofty standards, W...",https://www.wsj.com/politics/is-this-the-bigge...
111,78,2026-04-01-10-00-00 +0000,nypost,Bruce Blakeman takes page out of MAGA playbook...,https://nypost.com/2026/04/01/us-news/bruce-bl...
32,63,2026-04-01-13-40-54 +0000,nypost,NASA’s historic Artemis II mission shows space...,https://nypost.com/2026/04/01/science/potentia...
301,63,2026-03-31-20-18-00 +0000,wsj,The Trump administration can’t end federal fun...,https://www.wsj.com/politics/policy/trumps-ord...
271,50,2026-03-31-21-34-47 +0000,nypost,Iran’s parliament approves plan to impose toll...,https://nypost.com/2026/03/31/world-news/iran-...
350,45,2026-03-31-18-05-15 +0000,nypost,Shocking pictures of Kristi Noem’s cross-dress...,https://nypost.com/2026/03/31/us-news/pictures...
122,42,2026-04-01-09-54-00 +0000,wsj,U.K.’s Food Inflation Could Triple by Year End...,https://www.wsj.com/economy/central-banking/u-...
130,39,2026-04-01-09-30-00 +0000,wsj,The U.S. economy made it through Covid inflati...,https://www.wsj.com/economy/economic-tail-risk...
101,37,2026-04-01-10-33-35 +0000,bbc,Israel intensifies Lebanon attacks and hits ar...,https://www.bbc.com/news/articles/cvg07j6yeweo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)