## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-18-47-43 +0000,chitri,President Trump delivers brief remarks ahead o...,https://www.chicagotribune.com/2026/09/27/trum...
1,2026-09-27-18-47-33 +0000,missionlocal,Christine Pelosi vows not to ‘ever’ run agains...,https://missionlocal.org/2026/09/christine-pel...
2,2026-09-27-18-41-00 +0000,wsj,Opinion | The AfD’s Rise Is Angela Merkel’s Le...,https://www.wsj.com/opinion/the-afds-rise-is-a...
3,2026-09-27-18-39-11 +0000,nyt,5 Arrested on Suspicion of Terrorism Near RAF ...,https://www.nytimes.com/2026/09/27/world/europ...
4,2026-09-27-18-38-00 +0000,wsj,Opinion | The Ph.D. Job Crisis Is a Needed Mar...,https://www.wsj.com/opinion/the-ph-d-job-crisi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
1    trump     29
154    war     13
69    iran     11
108  china     10
93     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
58,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...,77
71,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...,75
70,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...,71
26,2026-09-27-17-30-46 +0000,wapo,"Trump says U.S., Iran slated for indirect talk...",https://www.washingtonpost.com/world/2026/09/2...,65
64,2026-09-27-15-16-22 +0000,nyt,Trump’s War With Iran Drags Down Republicans i...,https://www.nytimes.com/2026/09/27/us/politics...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
58,77,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...
25,52,2026-09-27-17-33-20 +0000,nypost,War-wounded military veterans peddling cheap p...,https://nypost.com/2026/09/27/world-news/wound...
81,41,2026-09-27-12-34-26 +0000,bbc,One dead as nor'easter storm pummels New York ...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
70,39,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...
56,38,2026-09-27-15-56-15 +0000,nypost,‘Home-wrecker’ Sen. Kyrsten Sinema’s ex-bodygu...,https://nypost.com/2026/09/27/us-news/kyrsten-...
135,33,2026-09-27-06-47-34 +0000,nypost,"27 killed, dozens wounded in horror mass shoot...",https://nypost.com/2026/09/27/world-news/south...
182,31,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
30,30,2026-09-27-17-24-26 +0000,nypost,One normally quiet Texas race shows 2026 will ...,https://nypost.com/2026/09/27/us-news/how-texa...
51,29,2026-09-27-16-00-34 +0000,chitri,Tensions run high in Northern Ireland after co...,https://www.chicagotribune.com/2026/09/27/nort...
86,29,2026-09-27-11-25-00 +0000,wsj,A scandal inside the Philadelphia DA’s office ...,https://www.wsj.com/politics/policy/vance-puts...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)