## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-01-01-27-59 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/09/30/us/cal...
1,2026-10-01-01-21-39 +0000,nyt,Plane to Israel Narrowly Averts Disaster After...,https://www.nytimes.com/live/2026/09/30/world/...
2,2026-10-01-01-21-37 +0000,nyt,FlyDubai Passenger Who Helped Subdue Pilot Des...,https://www.nytimes.com/2026/09/30/world/middl...
3,2026-10-01-01-20-12 +0000,nyt,"Newsom, Eager for a Higher Perch, Climbs the G...",https://www.nytimes.com/2026/09/30/us/newsom-g...
4,2026-10-01-01-20-00 +0000,wsj,Democratic Senators Challenge Trump Officials ...,https://www.wsj.com/politics/national-security...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2371/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
27        trump     39
154          ai     22
76   california     21
7         pilot     17
201         new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...,188
351,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,130
279,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...,107
423,2026-09-30-08-01-44 +0000,nypost,"Israel-bound plane pilot stabbed by co-pilot, ...",https://nypost.com/2026/09/30/world-news/israe...,100
35,2026-10-01-00-12-00 +0000,wsj,OpenAI co-founder and President Greg Brockman ...,https://www.wsj.com/tech/ai/openai-president-b...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,188,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...
35,95,2026-10-01-00-12-00 +0000,wsj,OpenAI co-founder and President Greg Brockman ...,https://www.wsj.com/tech/ai/openai-president-b...
255,80,2026-09-30-17-12-26 +0000,nypost,Trump to announce $54 billion Alaska LNG plant...,https://nypost.com/2026/09/30/us-news/trump-to...
351,68,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...
41,67,2026-09-30-23-57-35 +0000,latimes,In-N-Out forces Northern California high schoo...,https://www.latimes.com/california/story/2026-...
63,51,2026-09-30-23-14-32 +0000,nyt,Supreme Court Allows Execution of Christa Pike...,https://www.nytimes.com/2026/09/30/us/christa-...
5,50,2026-10-01-01-20-00 +0000,wsj,Senate Democrats are challenging the legality ...,https://www.wsj.com/politics/national-security...
245,47,2026-09-30-17-37-51 +0000,nypost,OpenAI considered partnering with China and Ru...,https://nypost.com/2026/09/30/business/openai-...
120,47,2026-09-30-21-31-42 +0000,nyt,UK Believes Iran Played a Part in RAF Fairford...,https://www.nytimes.com/2026/09/30/world/europ...
393,46,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)