## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-20-16-33 +0000,startribune,Man dies after two Minneapolis shootings injur...,https://www.startribune.com/shooting-outside-m...
1,2026-07-20-20-15-48 +0000,bbc,Louise Haigh: Labour power broker behind Burnh...,https://www.bbc.co.uk/news/articles/c87n0x974v...
2,2026-07-20-20-14-57 +0000,bbc,Trump warns Iran will pay 'many times over' fo...,https://www.bbc.co.uk/news/articles/cly52xzjd3...
3,2026-07-20-20-13-00 +0000,wsj,Ex-Army Soldier Ignited Gasoline Outside a Fed...,https://www.wsj.com/us-news/ex-army-soldier-ig...
4,2026-07-20-20-11-39 +0000,nyt,Oil Markets on Edge as Houthi Rebels Threaten ...,https://www.nytimes.com/2026/07/19/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2612/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
31      new     27
14  burnham     26
18     iran     26
60    world     25
61      cup     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
48,2026-07-20-18-57-40 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,112
324,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,106
282,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...,104
330,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...,97
228,2026-07-20-10-42-53 +0000,nypost,Trump says new Qatar-donated Air Force One to ...,https://nypost.com/2026/07/20/us-news/trump-sa...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
48,112,2026-07-20-18-57-40 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
324,106,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...
55,64,2026-07-20-18-50-59 +0000,nyt,Pentagon Identifies 2 U.S. Soldiers Killed in ...,https://www.nytimes.com/2026/07/20/us/iran-war...
145,52,2026-07-20-15-25-35 +0000,nypost,Ex-logger Troy Jackson set to succeed Graham P...,https://nypost.com/2026/07/20/us-news/ex-logge...
256,51,2026-07-20-09-30-00 +0000,wsj,He Bought a House ‘Sight Unseen.’ Then He Foun...,https://www.wsj.com/real-estate/he-bought-a-ho...
62,46,2026-07-20-18-44-00 +0000,wsj,The Qatari-gifted luxury jet that President Tr...,https://www.wsj.com/politics/policy/trump-air-...
38,42,2026-07-20-19-15-03 +0000,startribune,Judge says Paramount and Warner must halt merg...,https://www.startribune.com/judge-says-paramou...
15,37,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...
330,36,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
265,35,2026-07-20-09-00-00 +0000,wsj,Many wealthy Texas Republicans can’t stomach t...,https://www.wsj.com/politics/elections/ken-pax...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)