## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-01-11-33 +0000,nypost,Connecticut OnlyFans model who made $3 million...,https://nypost.com/2026/09/15/us-news/connecti...
1,2026-09-16-01-09-25 +0000,nyt,How the Postal Service Became Central to U.S. ...,https://www.nytimes.com/2026/09/15/us/politics...
2,2026-09-16-01-04-42 +0000,startribune,Minneapolis Public School District reveals pla...,https://www.startribune.com/minneapolis-public...
3,2026-09-16-01-04-38 +0000,nypost,SUV gets lodged inside Metro bus in deadly LA ...,https://nypost.com/2026/09/15/us-news/dramatic...
4,2026-09-16-01-00-00 +0000,wsj,Americans Have Spent $100 Billion More on Fuel...,https://www.wsj.com/business/energy-oil/americ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
119  trump     47
337    new     27
60      ai     26
39    iran     21
266  court     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
85,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,205
295,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,139
294,2026-09-15-13-54-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,134
95,2026-09-15-21-16-25 +0000,chitri,Illinois Democrats cheer Supreme Court mail-in...,https://www.chicagotribune.com/2026/09/15/supr...,125
63,2026-09-15-22-39-00 +0000,wsj,The Kennedy Center’s board voted on Tuesday to...,https://www.wsj.com/us-news/law/trumps-name-ca...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
85,205,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
295,92,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
165,65,2026-09-15-19-36-30 +0000,nypost,10-year Treasury yield hits highest level sinc...,https://nypost.com/2026/09/15/business/10-year...
60,64,2026-09-15-22-40-00 +0000,nypost,Meet Anthropic CEO Dario Amodei’s handpicked s...,https://nypost.com/2026/09/15/business/anthrop...
35,54,2026-09-15-23-30-00 +0000,wsj,American business owners are grappling with a ...,https://www.wsj.com/business/american-business...
69,51,2026-09-15-22-15-45 +0000,nypost,Senate fails to advance Clarity Act in blow to...,https://nypost.com/2026/09/15/business/senate-...
11,49,2026-09-16-00-34-32 +0000,nypost,Plot forms against California tech companies w...,https://nypost.com/2026/09/15/us-news/silicon-...
206,47,2026-09-15-18-14-00 +0000,wsj,Nick Reiner Won’t Face Death Penalty if Convic...,https://www.wsj.com/us-news/law/l-a-district-a...
316,41,2026-09-15-12-49-55 +0000,cbc,Canada's 4 largest airports to be opened up to...,https://www.cbc.ca/news/politics/carney-airpor...
63,40,2026-09-15-22-39-00 +0000,wsj,The Kennedy Center’s board voted on Tuesday to...,https://www.wsj.com/us-news/law/trumps-name-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)