## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-03-01-06-52 +0000,nypost,"‘Sexology 101’ truck hits NJ colleges, handing...",https://nypost.com/2026/05/02/us-news/sexology...
1,2026-05-03-01-01-44 +0000,nypost,Naked man screams threats as neighbors say the...,https://nypost.com/2026/05/02/us-news/naked-ma...
2,2026-05-03-01-00-00 +0000,wsj,Inside the big spending and internal drama at ...,https://www.wsj.com/politics/elections/inside-...
3,2026-05-03-01-00-00 +0000,wsj,ChatGPT Wrestles With Its Most Chilling Conver...,https://www.wsj.com/us-news/chatgpt-mass-shoot...
4,2026-05-03-01-00-00 +0000,wsj,The Fuel-Price Crunch That’s Turning Into a Di...,https://www.wsj.com/business/airlines/iran-war...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
63      trump     23
66       iran     17
315       new     13
154       war     13
50   airlines     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
28,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,73
118,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,72
119,2026-05-02-13-14-37 +0000,nyt,"As Iran War Reaches 60-Day Mark, Republicans i...",https://www.nytimes.com/2026/05/01/us/politics...,66
146,2026-05-02-09-41-47 +0000,cbc,Trump says U.S. reviewing new Iranian proposal...,https://www.cbc.ca/news/world/strait-of-hormuz...,62
65,2026-05-02-19-53-55 +0000,nyt,Trump ‘Not Satisfied’ With Iran’s Proposal on ...,https://www.nytimes.com/2026/05/01/world/middl...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
28,73,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...
58,38,2026-05-02-20-32-00 +0000,wsj,‘I Was Devastated.’ Spirit Passengers Rush to ...,https://www.wsj.com/lifestyle/travel/i-was-dev...
94,34,2026-05-02-16-50-23 +0000,cbc,Jailed Nobel laureate's life at risk if she is...,https://www.cbc.ca/news/world/nobel-peace-priz...
131,33,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
35,30,2026-05-02-22-13-11 +0000,nypost,Shocking cost to fuel world’s largest flying f...,https://nypost.com/2026/05/02/us-news/cal-fire...
56,30,2026-05-02-20-33-10 +0000,nypost,Alabama frat boy accused of beating ex-girlfri...,https://nypost.com/2026/05/02/us-news/universi...
34,27,2026-05-02-22-16-17 +0000,nypost,Hezbollah launches rockets at IDF troops as US...,https://nypost.com/2026/05/02/world-news/hezbo...
38,25,2026-05-02-21-50-29 +0000,nypost,London’s top cop warns British Jews face great...,https://nypost.com/2026/05/02/world-news/londo...
90,24,2026-05-02-16-57-00 +0000,wsj,Spirit Airlines Is Shutting Down. Here’s What ...,https://www.wsj.com/business/airlines/if-you-b...
87,23,2026-05-02-17-10-00 +0000,wsj,The number of food-stamp recipients is falling...,https://www.wsj.com/politics/policy/more-than-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)