## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-17-54-23 +0000,bbc,US singer D4vd's celebrity lawyers withdraw fr...,https://www.bbc.co.uk/news/articles/crr451lpl4...
1,2026-08-31-17-53-50 +0000,nypost,Trump admin orders 270 trucking schools to shu...,https://nypost.com/2026/08/31/us-news/trump-ad...
2,2026-08-31-17-52-03 +0000,nyt,‘The Nest of Snakes’: Warring Cartels Target W...,https://www.nytimes.com/2026/08/31/world/ameri...
3,2026-08-31-17-50-29 +0000,wapo,"Iran, accustomed to sanctions, cites pain of n...",https://www.washingtonpost.com/world/2026/08/3...
4,2026-08-31-17-48-32 +0000,wapo,Trump says voters who oppose data centers will...,https://www.washingtonpost.com/politics/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2317/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7    trump     19
25    iran     18
299  first     14
91   nepal     14
111     up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...,97
147,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...,83
50,2026-08-31-16-26-55 +0000,nypost,Haunting photo of Grand Canyon hiker before he...,https://nypost.com/2026/08/31/us-news/grand-ca...,77
17,2026-08-31-17-13-39 +0000,bbc,Two dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...,77
120,2026-08-31-12-28-07 +0000,nypost,Trump calls for leaders of ‘failed nation’ Ira...,https://nypost.com/2026/08/31/world-news/trump...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,97,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...
50,77,2026-08-31-16-26-55 +0000,nypost,Haunting photo of Grand Canyon hiker before he...,https://nypost.com/2026/08/31/us-news/grand-ca...
227,58,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
98,57,2026-08-31-13-59-16 +0000,nypost,Oil prices jump 3% to over $90 after US-Iran e...,https://nypost.com/2026/08/31/business/oil-pri...
150,43,2026-08-31-10-16-50 +0000,cbc,Hundreds feared stuck in hydropower tunnels as...,https://www.cbc.ca/news/world/nepal-tibet-floo...
38,38,2026-08-31-16-34-00 +0000,wsj,Kalshi permanently banned George Santos after ...,https://www.wsj.com/politics/ex-congressman-ge...
267,34,2026-08-30-19-33-47 +0000,chitri,Death toll rises to 38 from Russia’s deadliest...,https://www.chicagotribune.com/2026/08/30/russ...
23,32,2026-08-31-16-58-33 +0000,nypost,D4vd drops high-powered lawyers for public def...,https://nypost.com/2026/08/31/us-news/d4vd-dro...
44,32,2026-08-31-16-32-21 +0000,nypost,Bessent taunts Canada amid trade war: ‘What ar...,https://nypost.com/2026/08/31/us-news/scott-be...
79,31,2026-08-31-14-50-36 +0000,bbc,'She slipped out of my hand' - children missin...,https://www.bbc.co.uk/news/articles/c1mv5ggg1l...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)