## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-21-21-54-57 +0000,startribune,Minneapolis mental health crisis response prog...,https://www.startribune.com/minneapolis-mental...
1,2026-10-21-21-49-07 +0000,bbc,Meta fined $25bn for 'lies' over user data pri...,https://www.bbc.co.uk/news/articles/cqdr8zxrr3...
2,2026-10-21-21-48-34 +0000,nypost,French leftists plan major Paris protest Satur...,https://nypost.com/2026/10/21/world-news/frenc...
3,2026-10-21-21-48-00 +0000,wsj,Mattel Adds Board Member As Activist Investor ...,https://www.wsj.com/business/mattel-adds-board...
4,2026-10-21-21-46-49 +0000,nypost,SF nightlife institution known as the oldest b...,https://nypost.com/2026/10/21/business/san-fra...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2371/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
153   trump     34
57      new     26
53       ai     15
60   spacex     14
409   putin     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
106,2026-10-21-19-25-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...,121
120,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...,105
356,2026-10-21-01-37-00 +0000,wsj,President Trump is relying on a new strategy t...,https://www.wsj.com/politics/elections/trump-m...,96
29,2026-10-21-21-11-00 +0000,wsj,President Trump said he is requiring companies...,https://www.wsj.com/politics/policy/trump-says...,94
309,2026-10-21-09-03-22 +0000,nyt,Trump Approval Hits New Low Two Weeks Before M...,https://www.nytimes.com/2026/10/21/us/politics...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
106,121,2026-10-21-19-25-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...
120,105,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...
39,73,2026-10-21-21-03-00 +0000,wsj,An ad featuring Amy Acton’s estranged mother a...,https://www.wsj.com/politics/elections/ohio-go...
229,67,2026-10-21-14-05-18 +0000,chitri,Russia President Vladimir Putin agrees to resu...,https://www.chicagotribune.com/2026/10/21/russ...
31,61,2026-10-21-21-10-49 +0000,nyt,Tesla Profit Slumps as Elon Musk’s Car Company...,https://www.nytimes.com/2026/10/21/business/te...
7,52,2026-10-21-21-37-00 +0000,wsj,Meta Ordered to Pay $25 Billion to New Mexico ...,https://www.wsj.com/tech/meta-ordered-to-pay-2...
286,48,2026-10-21-10-15-16 +0000,cbc,Australian MP loses both legs after alleged ve...,https://www.cbc.ca/news/world/australian-polit...
103,43,2026-10-21-19-28-44 +0000,chitri,Pope Leo’s doctors say tests show he needs no ...,https://www.chicagotribune.com/2026/10/21/pope...
88,40,2026-10-21-19-50-54 +0000,nypost,Google faces Senate grilling over education AI...,https://nypost.com/2026/10/21/business/google-...
117,39,2026-10-21-19-02-58 +0000,nypost,Gavin Newsom gets brutal exit report card as 6...,https://nypost.com/2026/10/21/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)