## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-13-17-30-04 +0000,startribune,12 states challenge Paramount's takeover of Wa...,https://www.startribune.com/california-11-othe...
1,2026-07-13-17-28-49 +0000,nyt,Authorities Investigate Fatal Shooting in Bidd...,https://www.nytimes.com/2026/07/13/us/biddefor...
2,2026-07-13-17-27-00 +0000,wsj,Appeals Court Revives Lawsuits Alleging Tyleno...,https://www.wsj.com/us-news/law/appeals-court-...
3,2026-07-13-17-26-37 +0000,nypost,"5 family members killed, 2 others gravely woun...",https://nypost.com/2026/07/13/us-news/5-family...
4,2026-07-13-17-26-22 +0000,nyt,Trump Is Snapping Up Stakes in Private Compani...,https://www.nytimes.com/2026/07/13/business/ec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2451/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
182   graham     36
181  lindsey     33
39     trump     24
56      iran     21
124    death     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
81,2026-07-13-15-22-00 +0000,wsj,President Trump is pushing Darline Graham Nord...,https://www.wsj.com/politics/elections/lindsey...,192
169,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...,163
264,2026-07-12-20-07-03 +0000,nypost,Lindsey Graham’s sudden death could hamstring ...,https://nypost.com/2026/07/12/us-news/lindsey-...,144
84,2026-07-13-15-12-21 +0000,nypost,Sen. Lindsey Graham’s sister Darline reacts to...,https://nypost.com/2026/07/13/us-news/lindsey-...,139
118,2026-07-13-13-10-11 +0000,nypost,Trump reveals Lindsey Graham’s ‘one bad moment...,https://nypost.com/2026/07/13/us-news/trump-re...,134

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
81,192,2026-07-13-15-22-00 +0000,wsj,President Trump is pushing Darline Graham Nord...,https://www.wsj.com/politics/elections/lindsey...
61,67,2026-07-13-16-10-10 +0000,nypost,California’s war on Paramount ramps up as stat...,https://nypost.com/2026/07/13/business/califor...
169,65,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...
240,59,2026-07-12-23-10-00 +0000,wsj,U.S. and Iran Trade New Rounds of Attacks in F...,https://www.wsj.com/world/middle-east/u-s-laun...
136,45,2026-07-13-12-10-38 +0000,bbc,A versatile actor whose roles went far beyond ...,https://www.bbc.co.uk/news/articles/cx2wrvqq9r...
163,45,2026-07-13-10-13-03 +0000,wapo,Fire at Bangkok bar kills 27; exits may have b...,https://www.washingtonpost.com/world/2026/07/1...
31,34,2026-07-13-16-40-58 +0000,cbc,U.K. counterterrorism police now leading murde...,https://www.cbc.ca/news/world/uk-investigation...
245,33,2026-07-12-22-19-00 +0000,wsj,Sen. Lindsey Graham of South Carolina died of ...,https://www.wsj.com/us-news/law/what-dispatch-...
172,31,2026-07-13-09-30-00 +0000,wsj,New economic research might be pointing toward...,https://www.wsj.com/economy/jobs/the-next-labo...
75,29,2026-07-13-15-45-32 +0000,nypost,Suspect in murder of NY mom Jamey Carney had m...,https://nypost.com/2026/07/13/world-news/suspe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)