## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-21-16-59-04 +0000,nypost,Rambo-like Sen. Markwayne Mullin was ‘huge pro...,https://nypost.com/2026/03/21/us-news/markwayn...
1,2026-03-21-16-54-10 +0000,nypost,Tiny Jersey Shore town getting parking meters ...,https://nypost.com/2026/03/21/us-news/tiny-jer...
2,2026-03-21-16-47-54 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...
3,2026-03-21-16-47-50 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/21/world/...
4,2026-03-21-16-46-09 +0000,nyt,Iran’s Missiles Strike Far-Off Diego Garcia Ba...,https://www.nytimes.com/2026/03/21/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
22      iran     29
167    trump     22
23       war     21
28   iranian     12
119      bts     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-21-16-47-54 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...,119
218,2026-03-20-20-27-24 +0000,nypost,"Trump vows no cease-fire with Iran, predicts S...",https://nypost.com/2026/03/20/world-news/trump...,88
41,2026-03-21-14-06-20 +0000,nyt,War in Iran Reveals Strait of Hormuz’s Weaknes...,https://www.nytimes.com/2026/03/21/business/ir...,81
24,2026-03-21-15-29-09 +0000,cbc,Iranian Kurdish fighters find themselves in th...,https://www.cbc.ca/news/world/iranian-kurdish-...,79
263,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,119,2026-03-21-16-47-54 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...
263,78,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...
154,50,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...
130,39,2026-03-21-02-40-33 +0000,48hills,CBS workers in SF walk off the job as Bari Wei...,https://48hills.org/2026/03/cbs-workers-in-sf-...
162,38,2026-03-20-23-53-34 +0000,nypost,US pauses sanctions on Iranian oil ‘stranded a...,https://nypost.com/2026/03/20/us-news/us-pause...
59,37,2026-03-21-12-31-16 +0000,nypost,Teen squatters got past lax security before st...,https://nypost.com/2026/03/21/us-news/teen-squ...
12,37,2026-03-21-16-17-48 +0000,nyt,BTS’s Comeback Show Was Heavy on Their New Album,https://www.nytimes.com/live/2026/03/21/world/...
148,36,2026-03-21-01-00-00 +0000,wsj,Some Democrats on Capitol Hill are discussing ...,https://www.wsj.com/politics/policy/chuck-schu...
196,31,2026-03-20-21-18-38 +0000,latimes,The worst heat wave to hit Southern California...,https://www.latimes.com/california/story/2026-...
209,29,2026-03-20-20-45-00 +0000,nypost,Super Micro shares plunge as US charges co-fou...,https://nypost.com/2026/03/20/business/super-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)