## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-21-54-05 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/25/world/...
1,2026-10-25-21-43-27 +0000,nypost,LA actor linked to A-listers brutally beat lov...,https://nypost.com/2026/10/25/us-news/actor-el...
2,2026-10-25-21-39-45 +0000,nyt,Saudi Arabia Reopens Riyadh Airport Even as Ho...,https://www.nytimes.com/2026/10/25/world/middl...
3,2026-10-25-21-38-35 +0000,nyt,A Fight Over Felon Voting Prompts a Free Speec...,https://www.nytimes.com/2026/10/23/business/me...
4,2026-10-25-21-37-42 +0000,nyt,"In Texas Senate Race, Talarico Leans Into Grow...",https://www.nytimes.com/2026/10/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
92      trump     25
64   election     15
173       new     12
58         he     11
358     first      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
218,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,72
192,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,68
17,2026-10-25-21-02-05 +0000,startribune,Trump escalates rhetoric against El-Sayed as h...,https://www.startribune.com/trumps-midterm-swi...,64
199,2026-10-25-00-33-41 +0000,nypost,Obama rips Trump for tariffs and White House r...,https://nypost.com/2026/10/24/us-news/obama-ri...,63
10,2026-10-25-21-17-42 +0000,nyt,María Corina Machado on Venezuela’s Future and...,https://www.nytimes.com/2026/10/19/world/ameri...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
218,72,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...
196,61,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
49,49,2026-10-25-19-38-58 +0000,nypost,Venezuelan opposition leader María Corina Mach...,https://nypost.com/2026/10/25/world-news/venez...
207,43,2026-10-24-23-35-22 +0000,chitri,"Brazil’s Lula, Bolsonaro close arguments to vo...",https://www.chicagotribune.com/2026/10/24/braz...
17,39,2026-10-25-21-02-05 +0000,startribune,Trump escalates rhetoric against El-Sayed as h...,https://www.startribune.com/trumps-midterm-swi...
105,36,2026-10-25-15-20-17 +0000,nypost,Musk confirms SpaceX was behind thwarting of U...,https://nypost.com/2026/10/25/us-news/musk-con...
52,35,2026-10-25-19-34-12 +0000,nypost,"Thomas Markle’s home had trove of child porn, ...",https://nypost.com/2026/10/25/world-news/thoma...
22,30,2026-10-25-20-58-39 +0000,bbc,British Columbia's new premier lucks into the ...,https://www.bbc.co.uk/news/articles/cxj0ln19j3...
106,29,2026-10-25-15-08-34 +0000,latimes,Mystery Ohio news site boosting Ramaswamy's Am...,https://www.latimes.com/california/story/2026-...
57,28,2026-10-25-19-10-17 +0000,nypost,NYC’s ‘Big Brother’ red light cameras up to 60...,https://nypost.com/2026/10/25/us-news/nycs-big...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)