## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-23-15-00 +0000,wsj,Iran Says It Is Pausing Talks After Trump Threats,https://www.wsj.com/world/middle-east/war-in-l...
1,2026-06-21-23-10-16 +0000,bbc,Fake romance to missed deliveries: How to prot...,https://www.bbc.com/news/articles/cx2xq1vngvdo...
2,2026-06-21-22-57-33 +0000,nypost,Daughter of Cuban revolution ‘hero’ busted by ...,https://nypost.com/2026/06/21/us-news/daughter...
3,2026-06-21-22-50-26 +0000,latimes,"Another day of smoky air, nasty smells and man...",https://www.latimes.com/california/story/2026-...
4,2026-06-21-22-46-57 +0000,nyt,"Abelardo De La Espriella, Trump-Backed Rightis...",https://www.nytimes.com/2026/06/21/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     26
3    trump     23
2    talks     16
137  world     10
97     new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,101
110,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...,101
9,2026-06-21-22-36-02 +0000,wapo,JD Vance holds peace talks with Iran as Trump ...,https://www.washingtonpost.com/world/2026/06/2...,94
149,2026-06-21-09-13-54 +0000,cbc,Trump threats shake up U.S.-Iran talks in Swit...,https://www.cbc.ca/news/world/jd-vance-switzer...,91
183,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,101,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
76,40,2026-06-21-17-32-12 +0000,nypost,NYC voters are fed up with the Democratic Part...,https://nypost.com/2026/06/21/us-news/nyc-vote...
145,33,2026-06-21-09-45-57 +0000,bbc,Dutch royals enjoy two big results in one Worl...,https://www.bbc.com/sport/football/articles/c4...
24,31,2026-06-21-21-24-35 +0000,nypost,"Race against time in fight with 500,000-square...",https://nypost.com/2026/06/21/us-news/85m-poun...
114,27,2026-06-21-13-41-12 +0000,nypost,Vance says US willing to ‘fundamentally transf...,https://nypost.com/2026/06/21/us-news/vance-sa...
159,24,2026-06-21-09-00-00 +0000,wsj,Jay Clayton has been a loyal ally and golf bud...,https://www.wsj.com/politics/policy/the-would-...
100,23,2026-06-21-15-46-09 +0000,nypost,Sore loser Texas Rep. Jasmine Crockett says sh...,https://nypost.com/2026/06/21/us-news/jasmine-...
88,22,2026-06-21-16-23-36 +0000,nyt,Keir Starmer Reflects on ‘Political Challenges...,https://www.nytimes.com/2026/06/21/world/europ...
87,21,2026-06-21-16-48-18 +0000,nypost,Great-grandson of bushy-browed Soviet leader ...,https://nypost.com/2026/06/21/world-news/sovie...
72,21,2026-06-21-17-59-08 +0000,nypost,Christian cop suspended for asking questions a...,https://nypost.com/2026/06/21/world-news/chris...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)