## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-30-17-10-03 +0000,nypost,News of the World: What you missed this week i...,https://nypost.com/2026/05/30/world-news/news-...
1,2026-05-30-17-09-39 +0000,nyt,What to Know About the Ebola Outbreak,https://www.nytimes.com/2026/05/17/world/afric...
2,2026-05-30-17-01-48 +0000,nyt,The Russian Drone That Hit Romania Also Hit Eu...,https://www.nytimes.com/2026/05/30/world/europ...
3,2026-05-30-17-00-00 +0000,nypost,Kelsey Grammer reveals his nasty nickname for ...,https://nypost.com/2026/05/30/us-news/kelsey-g...
4,2026-05-30-16-58-56 +0000,bbc,"Ebola spread in DR Congo 'alarming', charity w...",https://www.bbc.com/news/articles/c99ldxykz4zo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
37         trump     44
49           new     12
1012       judge     11
588   california     11
46           out     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...,94
68,2026-05-30-11-23-00 +0000,wsj,President Trump “remains in excellent physical...,https://www.wsj.com/politics/trump-remains-in-...,91
183,2026-05-29-22-14-11 +0000,nypost,Trump wants to give Kennedy Center to Congress...,https://nypost.com/2026/05/29/us-news/trump-an...,88
161,2026-05-30-00-18-00 +0000,wsj,Trump’s Name Must Be Removed From Kennedy Cent...,https://www.wsj.com/politics/policy/judge-bloc...,87
236,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,94,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...
55,52,2026-05-30-12-45-00 +0000,nypost,"Escort demand surges ahead of NYC, NJ World Cu...",https://nypost.com/2026/05/30/us-news/world-cu...
183,44,2026-05-29-22-14-11 +0000,nypost,Trump wants to give Kennedy Center to Congress...,https://nypost.com/2026/05/29/us-news/trump-an...
236,43,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...
132,39,2026-05-30-03-10-00 +0000,wsj,The Trump administration recently announced a ...,https://www.wsj.com/politics/policy/green-card...
2,35,2026-05-30-17-01-48 +0000,nyt,The Russian Drone That Hit Romania Also Hit Eu...,https://www.nytimes.com/2026/05/30/world/europ...
252,35,2026-05-29-18-54-40 +0000,latimes,Former California mayor pleads guilty to secre...,https://www.latimes.com/california/story/2026-...
121,35,2026-05-30-06-43-02 +0000,nypost,White House releases doctor’s memo from Trump’...,https://nypost.com/2026/05/30/us-news/trump-in...
13,34,2026-05-30-16-34-30 +0000,nyt,"As Trump Mulls Decision About Iran War Deal, a...",https://www.nytimes.com/2026/05/30/world/middl...
258,29,2026-05-29-18-21-11 +0000,bbc,First of five men found alive in flooded Laos ...,https://www.bbc.com/news/articles/cvgzxjrkvn8o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)