## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-29-16-59-27 +0000,nyt,Iran War Live Updates: Israel Strikes Tehran a...,https://www.nytimes.com/live/2026/03/29/world/...
1,2026-03-29-16-47-48 +0000,nyt,Hundreds Gather for Funeral of 3 Lebanese Kill...,https://www.nytimes.com/2026/03/29/world/middl...
2,2026-03-29-16-45-44 +0000,nypost,California gubernatorial candidates’ salaries ...,https://nypost.com/2026/03/29/us-news/californ...
3,2026-03-29-16-42-36 +0000,cbc,The NDP has a new leader. What does Avi Lewis'...,https://www.cbc.ca/news/politics/ndp-new-leade...
4,2026-03-29-16-42-17 +0000,bbc,Israeli police block Latin Patriarch from Palm...,https://www.bbc.com/news/articles/cvg0128z41eo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
197  trump     20
0     iran     18
193     no     18
1      war     18
194  kings     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
161,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...,108
112,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...,86
160,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...,84
101,2026-03-29-04-11-27 +0000,bbc,No Kings protesters across the US rally agains...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...,73
35,2026-03-29-15-13-13 +0000,nypost,Fetishist ‘No Kings’ protester in mask drags ‘...,https://nypost.com/2026/03/29/us-news/atlanta-...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
161,108,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...
41,42,2026-03-29-14-35-49 +0000,nypost,Air Canada flight attendant who was ejected du...,https://nypost.com/2026/03/29/world-news/air-c...
12,28,2026-03-29-16-23-26 +0000,nypost,Lawyer for LI creep accused of kidnapping 4-ye...,https://nypost.com/2026/03/29/us-news/lawyer-f...
1,27,2026-03-29-16-47-48 +0000,nyt,Hundreds Gather for Funeral of 3 Lebanese Kill...,https://www.nytimes.com/2026/03/29/world/middl...
23,27,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...
76,27,2026-03-29-09-30-00 +0000,wsj,Fed policymakers suggest interest rates could ...,https://www.wsj.com/economy/central-banking/fe...
123,26,2026-03-28-23-37-16 +0000,nypost,JD Vance wins 2028 CPAC GOP presidential straw...,https://nypost.com/2026/03/28/us-news/rubio-cu...
160,23,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...
70,23,2026-03-29-10-00-00 +0000,latimes,Barabak: Will or won't he? A lot rides on a Tr...,https://www.latimes.com/politics/story/2026-03...
3,22,2026-03-29-16-42-36 +0000,cbc,The NDP has a new leader. What does Avi Lewis'...,https://www.cbc.ca/news/politics/ndp-new-leade...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)