## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-23-20-30-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/policy/senate-pas...
1,2026-06-23-20-28-17 +0000,nypost,Ex-JPMorgan banker Chirayu Rana dealt major bl...,https://nypost.com/2026/06/23/us-news/ex-jpmor...
2,2026-06-23-20-27-11 +0000,nyt,Mideast Live Updates: U.S. and Iran Offer Conf...,https://www.nytimes.com/live/2026/06/23/world/...
3,2026-06-23-20-27-00 +0000,wsj,FedEx Revenue Rises on Growth in Package Yield...,https://www.wsj.com/business/earnings/fedex-re...
4,2026-06-23-20-26-50 +0000,nypost,Lone holdout juror in first Etan Patz trial ri...,https://nypost.com/2026/06/23/us-news/holdout-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2309/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     35
10    iran     29
114    new     23
240    war     15
115     ai     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
25,2026-06-23-20-06-12 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...,105
0,2026-06-23-20-30-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/policy/senate-pas...,103
313,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...,100
181,2026-06-23-14-23-41 +0000,nyt,How Will Colombia’s New President Fuel Trump’s...,https://www.nytimes.com/2026/06/22/world/ameri...,95
92,2026-06-23-17-52-50 +0000,nypost,IAEA backs Trump in latest dispute with Iran —...,https://nypost.com/2026/06/23/us-news/iaea-bac...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
25,105,2026-06-23-20-06-12 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...
95,82,2026-06-23-17-41-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
313,53,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...
27,48,2026-06-23-20-01-32 +0000,bbc,UN says it will evacuate sailors stranded in S...,https://www.bbc.co.uk/news/articles/c24yr796em...
154,44,2026-06-23-15-41-52 +0000,latimes,Inmates may not sue prison officials who viola...,https://www.latimes.com/politics/story/2026-06...
16,43,2026-06-23-20-14-51 +0000,nyt,Markets Recoil in Global Sell-Off Driven by Te...,https://www.nytimes.com/2026/06/23/business/st...
31,41,2026-06-23-19-51-05 +0000,nypost,Shocking DA decision hours before maniac choke...,https://nypost.com/2026/06/23/us-news/shocking...
63,38,2026-06-23-18-58-57 +0000,nypost,Local businesses charge World Cup partiers tho...,https://nypost.com/2026/06/23/lifestyle/local-...
1,35,2026-06-23-20-28-17 +0000,nypost,Ex-JPMorgan banker Chirayu Rana dealt major bl...,https://nypost.com/2026/06/23/us-news/ex-jpmor...
99,35,2026-06-23-17-37-00 +0000,wsj,Top-ranking Senate Democrats are calling for h...,https://www.wsj.com/politics/policy/senate-dem...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)