## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-25-20-55-21 +0000,nypost,Homeowner’s horrifying discovery in crawl spac...,https://nypost.com/2026/09/25/us-news/big-bear...
1,2026-09-25-20-53-00 +0000,wsj,U.S. Troops Are Now Fighting the Drug War on t...,https://www.wsj.com/world/americas/u-s-troops-...
2,2026-09-25-20-51-38 +0000,nypost,"Twisted store owner beat, sexually assaulted r...",https://nypost.com/2026/09/25/us-news/warped-k...
3,2026-09-25-20-50-00 +0000,wsj,"Yields Subside, Stocks Breathe Easier",https://www.wsj.com/pro/cybersecurity/yields-s...
4,2026-09-25-20-49-47 +0000,nypost,Hanging of Black woman found after drug disput...,https://nypost.com/2026/09/25/us-news/hanging-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
162  trump     84
163     xi     36
626  house     24
27     new     22
185  court     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,210
101,2026-09-25-18-26-18 +0000,nypost,White House plays ‘Les Miserables’ hit censore...,https://nypost.com/2026/09/25/us-news/white-ho...,203
420,2026-09-24-21-11-30 +0000,nypost,Here’s the menu for the Trump-Xi state dinner ...,https://nypost.com/2026/09/24/us-news/heres-th...,196
333,2026-09-25-02-16-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...,179
379,2026-09-24-22-41-37 +0000,cbc,Fanfare surrounds Trump-Xi summit at White Hou...,https://www.cbc.ca/news/world/trump-xi-summit-...,176

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,210,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...
406,87,2026-09-24-21-30-00 +0000,wsj,The White House is pressing China about suspec...,https://www.wsj.com/politics/elections/trump-a...
152,84,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...
277,73,2026-09-25-09-30-00 +0000,wsj,Cracks in Oracle’s AI Data-Center Build-Out Ap...,https://www.wsj.com/finance/investing/cracks-i...
319,49,2026-09-25-03-28-00 +0000,wsj,A pro-Trump ad that said it was paid for by th...,https://www.wsj.com/politics/u-s-government-ai...
227,48,2026-09-25-12-40-02 +0000,chitri,Pope Leo XIV warns a ‘paradise of machines’ co...,https://www.chicagotribune.com/2026/09/25/pope...
297,47,2026-09-25-08-52-23 +0000,wsj,Stock Market Today: Bond Yields Drop With Oil ...,https://www.wsj.com/livecoverage/stock-market-...
258,47,2026-09-25-10-00-01 +0000,wapo,"‘Be your own mayor’: For $4.75 million, you co...",https://www.washingtonpost.com/nation/2026/09/...
179,45,2026-09-25-15-49-16 +0000,chitri,Chicago City Council approves campaign ethics ...,https://www.chicagotribune.com/2026/09/25/chic...
325,40,2026-09-25-02-29-00 +0000,wsj,New Jersey Gov. Mikie Sherrill has called for ...,https://www.wsj.com/politics/policy/new-jersey...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)