## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-23-14-57-28 +0000,nypost,"Evil soldier mom beat daughter, 2, to death — ...",https://nypost.com/2026/08/23/us-news/evil-sol...
1,2026-08-23-14-43-23 +0000,nyt,Trump’s Top Trade Representative Details Offer...,https://www.nytimes.com/2026/08/22/business/ec...
2,2026-08-23-14-32-06 +0000,nyt,Mexican Governor Accused by U.S. of Aiding Car...,https://www.nytimes.com/2026/08/23/world/ameri...
3,2026-08-23-14-31-12 +0000,nyt,America’s Desert Metropolis Is on the Short Li...,https://www.nytimes.com/2026/08/23/us/arizona-...
4,2026-08-23-14-29-36 +0000,nyt,Iran Warns Gulf States Not to Join Trump’s Eco...,https://www.nytimes.com/2026/08/23/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     20
14   trade     17
18  canada     15
50     new     12
40     war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
157,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,113
17,2026-08-23-13-22-13 +0000,nypost,Canadian PM Mark Carney claims country ‘at war...,https://nypost.com/2026/08/23/us-news/canadian...,82
93,2026-08-23-07-15-52 +0000,nyt,Carney Stands Up to Trump in U.S.-Canada Trade...,https://www.nytimes.com/2026/08/22/world/canad...,77
29,2026-08-23-12-33-01 +0000,cbc,Trump says Canada 'wants the benefits' of bein...,https://www.cbc.ca/news/canada/trump-canada-tr...,74
101,2026-08-23-05-46-43 +0000,bbc,Trump says Canada wants 'benefits' of being US...,https://www.bbc.co.uk/news/articles/cx272np7vg...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
157,113,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
17,56,2026-08-23-13-22-13 +0000,nypost,Canadian PM Mark Carney claims country ‘at war...,https://nypost.com/2026/08/23/us-news/canadian...
115,44,2026-08-23-02-14-11 +0000,nypost,NYC mom recalls escaping with her life after e...,https://nypost.com/2026/08/22/us-news/nyc-mom-...
182,35,2026-08-22-16-00-00 +0000,wsj,"Ashley Hinson has never lost an election. Now,...",https://www.wsj.com/politics/elections/the-for...
174,30,2026-08-22-16-38-45 +0000,nypost,10 killed in Russian and Ukrainian attacks a d...,https://nypost.com/2026/08/22/world-news/10-ki...
129,27,2026-08-22-22-36-03 +0000,nypost,New footage of El Chapo’s first hours in capti...,https://nypost.com/2026/08/22/world-news/new-v...
99,26,2026-08-23-05-58-07 +0000,nypost,Alaska Dem Senate hopeful Mary Peltola racked ...,https://nypost.com/2026/08/23/us-news/alaska-d...
48,25,2026-08-23-10-00-37 +0000,chitri,Data centers near O’Hare win nearly $100M in l...,https://www.chicagotribune.com/2026/08/23/spec...
76,25,2026-08-23-09-02-03 +0000,nyt,Sean Duffy’s Reality Show: From ‘The Real Worl...,https://www.nytimes.com/2026/08/23/arts/televi...
23,24,2026-08-23-12-52-11 +0000,nyt,"Harry and Meghan See Their California Dreams, ...",https://www.nytimes.com/2026/08/22/us/meghan-h...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)