## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-03-51-59 +0000,nyt,"Ishmael Jaffree, Who Won Case Rejecting School...",https://www.nytimes.com/2026/04/14/us/ishmael-...
1,2026-04-15-03-50-00 +0000,wsj,Iran Ports Are Quiet As Strait Blockade Holds Up,https://www.wsj.com/world/middle-east/iran-por...
2,2026-04-15-03-42-54 +0000,nypost,Nebraska police fatally shoot woman seen slash...,https://nypost.com/2026/04/14/us-news/nebraska...
3,2026-04-15-03-37-00 +0000,wsj,Erica Schwartz is expected to be selected by t...,https://www.wsj.com/politics/policy/trump-admi...
4,2026-04-15-03-29-08 +0000,nypost,Police investigate sexual assault claim agains...,https://nypost.com/2026/04/14/us-news/katy-per...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
8        iran     37
30      trump     32
69        war     22
51   swalwell     20
122       new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-04-15-02-58-25 +0000,bbc,Trump hints Iran talks could resume this week ...,https://www.bbc.com/news/articles/c20ddnz4w5lo...,104
7,2026-04-15-03-12-04 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...,102
280,2026-04-14-13-53-29 +0000,nyt,Two Iran-Linked Ships Passed Through Strait of...,https://www.nytimes.com/2026/04/13/world/middl...,101
311,2026-04-14-11-14-54 +0000,nypost,"US, Iran may resume war talks this week despit...",https://nypost.com/2026/04/14/world-news/us-ir...,99
236,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,104,2026-04-15-02-58-25 +0000,bbc,Trump hints Iran talks could resume this week ...,https://www.bbc.com/news/articles/c20ddnz4w5lo...
20,77,2026-04-15-02-35-13 +0000,nypost,Special Victims Bureau will handle case of wom...,https://nypost.com/2026/04/14/us-news/la-speci...
24,70,2026-04-15-02-24-00 +0000,wsj,Prosecutors from U.S. Attorney Jeanine Pirro’s...,https://www.wsj.com/us-news/law/jeanine-pirros...
367,67,2026-04-14-04-34-00 +0000,wsj,China’s export momentum slowed sharply in Marc...,https://www.wsj.com/economy/trade/china-export...
347,57,2026-04-14-08-51-49 +0000,nypost,JD Vance accuses Iran of ‘economic terrorism’ ...,https://nypost.com/2026/04/14/world-news/jd-va...
26,48,2026-04-15-02-11-00 +0000,wsj,"Voters in South Hadley, Mass., rejected a stee...",https://www.wsj.com/us-news/massachusetts-town...
56,45,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
338,41,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...
121,41,2026-04-14-21-05-47 +0000,nypost,Millionaire who sheltered Eric Swalwell as sex...,https://nypost.com/2026/04/14/us-news/milliona...
29,41,2026-04-15-02-00-00 +0000,wsj,"So far, it is President Trump—and not Pope Leo...",https://www.wsj.com/politics/trump-pope-leo-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)