## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-04-22-34 +0000,nyt,Why China Loves A.I.,https://www.nytimes.com/2026/08/26/world/china...
1,2026-08-27-04-22-04 +0000,missionlocal,S.F. Dems endorse Manny Yekutiel in contentiou...,https://missionlocal.org/2026/08/s-f-dems-endo...
2,2026-08-27-04-19-18 +0000,nyt,Live Updates: Hundreds Missing as Wall of Wate...,https://www.nytimes.com/live/2026/08/26/world/...
3,2026-08-27-04-18-46 +0000,nyt,"Yayoi Kusama, Japanese Pop Artist Known for Po...",https://www.nytimes.com/2026/08/26/arts/yayoi-...
4,2026-08-27-04-18-39 +0000,48hills,How cities are going to lose all control over ...,https://48hills.org/2026/08/how-cities-are-goi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2522/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
205       trump     35
443  california     19
89        trade     18
129      parton     18
128       dolly     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,119
57,2026-08-26-23-55-41 +0000,wapo,"Canada, pressured by Trump, wants new trade pa...",https://www.washingtonpost.com/world/2026/08/2...,95
181,2026-08-26-19-08-11 +0000,cbc,Trump's trade war: Fact-checking Canada's natu...,https://www.cbc.ca/news/world/trade-war-natura...,91
366,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...,90
95,2026-08-26-22-32-12 +0000,cbc,Where Trump’s trade war with Canada could back...,https://www.cbc.ca/player/play/9.7321982?cmp=rss,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,119,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
88,83,2026-08-26-22-49-36 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
366,72,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...
257,70,2026-08-26-15-20-00 +0000,wapo,Judge channels Dolly Parton in blocking Texas ...,https://www.washingtonpost.com/nation/2026/08/...
150,63,2026-08-26-20-22-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
228,55,2026-08-26-16-37-47 +0000,latimes,"California, other states sue again to block ne...",https://www.latimes.com/politics/story/2026-08...
143,54,2026-08-26-20-53-00 +0000,wsj,"Hundreds Missing, 157 Dead, as Likely Ice-Rock...",https://www.wsj.com/world/asia/foreign-tourist...
101,53,2026-08-26-22-10-00 +0000,wsj,The surprise visit by the director of the Cent...,https://www.wsj.com/politics/policy/cia-chiefs...
63,45,2026-08-26-23-30-00 +0000,nypost,Disturbing past of 15 year old accused of gunn...,https://nypost.com/2026/08/26/us-news/bakersfi...
44,41,2026-08-27-00-52-04 +0000,nypost,"NYC bar owner files $6M suit against city, ex-...",https://nypost.com/2026/08/26/us-news/nyc-bar-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)