## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-10-52-29 +0000,bbc,Ex-Tory campaign chief pleads guilty over elec...,https://www.bbc.co.uk/news/articles/cde0rk4r5j...
1,2026-09-10-10-51-14 +0000,nypost,"August was Earth’s hottest month on record, sc...",https://nypost.com/2026/09/10/us-news/august-w...
2,2026-09-10-10-50-03 +0000,nypost,Grandpa whose 16 grandchildren found living in...,https://nypost.com/2026/09/10/us-news/ohio-gra...
3,2026-09-10-10-50-00 +0000,wsj,Bill’s CFO on Going AI-First—and Cutting Jobs—...,https://www.wsj.com/cfo-journal/bills-cfo-on-g...
4,2026-09-10-10-49-54 +0000,nyt,Russian Drone Incursion Delayed Zelensky Fligh...,https://www.nytimes.com/2026/09/10/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2333/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
53        trump     65
153         new     27
63          war     20
553  convention     19
491     midterm     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
130,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...,167
101,2026-09-10-05-35-19 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...,166
107,2026-09-10-05-09-24 +0000,nyt,Republican Senate Candidates Avoid Tariffs and...,https://www.nytimes.com/2026/09/09/us/politics...,147
279,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,141
285,2026-09-09-20-20-01 +0000,nypost,"Trump claims oil, gas prices will fall ‘right ...",https://nypost.com/2026/09/09/business/trump-c...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
130,167,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...
421,91,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
150,86,2026-09-10-01-54-25 +0000,nyt,"“We gave you no tax on tips, no tax on overtim...",https://www.nytimes.com/live/2026/09/09/us/rnc...
273,76,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
424,71,2026-09-09-12-20-40 +0000,bbc,Petrol prices rise by 5p over a week as Iran w...,https://www.bbc.co.uk/news/articles/cj4jwlx77l...
45,58,2026-09-10-09-30-00 +0000,nypost,Charlie Kirk’s murder left a void that will ‘1...,https://nypost.com/2026/09/10/us-news/charlie-...
345,58,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
138,55,2026-09-10-02-48-00 +0000,wsj,The Trump administration is proposing eliminat...,https://www.wsj.com/us-news/trump-administrati...
161,55,2026-09-10-01-23-42 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
279,49,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)