## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-15-18-17-07 +0000,nyt,"A ‘Man With No Country,’ Cassidy Fights for Po...",https://www.nytimes.com/2026/05/15/us/politics...
1,2026-05-15-18-16-00 +0000,wsj,Judge Declares Mistrial in Harvey Weinstein’s ...,https://www.wsj.com/us-news/law/judge-declares...
2,2026-05-15-18-16-00 +0000,wsj,Opinion | The World Was Watching Ted Turner’s CNN,https://www.wsj.com/opinion/the-world-was-watc...
3,2026-05-15-18-15-36 +0000,nyt,"Back From China, Trump Faces Decision on Wheth...",https://www.nytimes.com/2026/05/15/us/politics...
4,2026-05-15-18-15-35 +0000,nyt,Large Ebola Outbreak Is Declared in Congo,https://www.nytimes.com/2026/05/15/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     55
21   china     33
161     xi     27
12     new     22
28    iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
229,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...,160
123,2026-05-15-14-22-07 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,153
243,2026-05-15-06-04-46 +0000,nypost,Extravagant Trump-Xi tea menu revealed — as th...,https://nypost.com/2026/05/15/us-news/extravag...,149
23,2026-05-15-17-50-59 +0000,bbc,Trump warns Taiwan against declaring independe...,https://www.bbc.com/news/articles/ce8p61v7l68o...,145
212,2026-05-15-09-00-24 +0000,nypost,6 key takeaways from historic Trump-Xi China s...,https://nypost.com/2026/05/15/us-news/trump-xi...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
229,160,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...
261,73,2026-05-15-02-08-00 +0000,wsj,New York Governor Says Fewer Second Homes to P...,https://www.wsj.com/us-news/n-y-gov-hochul-say...
123,58,2026-05-15-14-22-07 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
230,44,2026-05-15-07-34-35 +0000,nypost,Supreme Court preserves access to widely used ...,https://nypost.com/2026/05/15/us-news/supreme-...
49,41,2026-05-15-16-58-18 +0000,nypost,CBS News anchor Tony Dokoupil barred from broa...,https://nypost.com/2026/05/15/media/cbs-news-a...
86,41,2026-05-15-15-45-53 +0000,nypost,AI scammer tricks ‘lonely’ retiree into giving...,https://nypost.com/2026/05/15/us-news/ai-scamm...
378,38,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
217,37,2026-05-15-08-48-55 +0000,nypost,"Oxygen toxicity, panic may have led to deaths ...",https://nypost.com/2026/05/15/world-news/oxyge...
246,33,2026-05-15-05-03-31 +0000,bbc,"Claim, counter-claim and tech's seedy side exp...",https://www.bbc.com/news/articles/cg7pj8p5mv4o...
271,32,2026-05-15-01-00-00 +0000,wsj,Homeland Security Secretary Markwayne Mullin f...,https://www.wsj.com/politics/policy/the-new-bo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)