## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-04-10-32 +0000,startribune,Live from Game 1: Wild can’t keep up with NHL’...,https://www.startribune.com/minnesota-wild-col...
1,2026-05-04-04-01-36 +0000,nyt,‘City of Glass’ Is Under Threat From Iran War,https://www.nytimes.com/2026/05/04/business/in...
2,2026-05-04-04-01-27 +0000,nyt,School Cellphone Ban Study Finds Mixed Results,https://www.nytimes.com/2026/05/04/us/did-scho...
3,2026-05-04-04-01-20 +0000,nyt,"Chizi, Standup Comic Exiled in China, Wants to...",https://www.nytimes.com/2026/05/04/business/ch...
4,2026-05-04-04-01-19 +0000,nyt,How the Kremlin Lures Africans Into Russia’s W...,https://www.nytimes.com/2026/05/04/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
104  trump     25
170    oil     12
13    iran     11
115    new     10
105   will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
193,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...,74
147,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...,72
102,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...,69
130,2026-05-03-16-49-30 +0000,cbc,Trump says operation will start Monday to help...,https://www.cbc.ca/news/world/cargo-ship-strai...,66
78,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
193,74,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
102,44,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...
105,39,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
147,37,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...
59,31,2026-05-03-22-42-10 +0000,nypost,Nail-biting video shows reckless NYC drivers g...,https://nypost.com/2026/05/03/us-news/nail-bit...
77,30,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
36,30,2026-05-04-00-29-21 +0000,nypost,Two major California insurers plot massive rat...,https://nypost.com/2026/05/03/us-news/two-majo...
159,30,2026-05-03-14-25-27 +0000,nypost,Former top Biden official all but admits admin...,https://nypost.com/2026/05/03/us-news/ex-biden...
130,26,2026-05-03-16-49-30 +0000,cbc,Trump says operation will start Monday to help...,https://www.cbc.ca/news/world/cargo-ship-strai...
39,25,2026-05-04-00-09-38 +0000,nypost,Entitled Delta passenger causes plane to retur...,https://nypost.com/2026/05/03/us-news/entitled...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)