## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-18-50-19 +0000,nypost,Suffolk County delays controversial rollout of...,https://nypost.com/2026/09/18/us-news/suffolk-...
1,2026-09-18-18-49-48 +0000,wapo,California governor signs order pushing for an...,https://www.washingtonpost.com/politics/2026/0...
2,2026-09-18-18-47-54 +0000,nyt,Uber to Pay $40 Million to Parents of Woman Fa...,https://www.nytimes.com/2026/09/18/business/ub...
3,2026-09-18-18-47-23 +0000,wapo,Immigrants using food stamps or Medicaid can n...,https://www.washingtonpost.com/business/2026/0...
4,2026-09-18-18-41-17 +0000,nyt,Protests Erupt in Nigeria After Police Pack 66...,https://www.nytimes.com/2026/09/18/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
97   trump     32
155    new     24
14      ai     18
117   iran     16
172  house     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
297,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,111
394,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...,103
306,2026-09-17-23-20-15 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-pu...,96
249,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...,95
346,2026-09-17-21-21-50 +0000,nypost,Trump says he has a ‘big decision’ coming up o...,https://nypost.com/2026/09/17/world-news/trump...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
297,111,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...
299,73,2026-09-17-23-40-47 +0000,latimes,Uber must pay $40 million to family of woman k...,https://www.latimes.com/california/story/2026-...
394,71,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...
334,52,2026-09-17-21-47-05 +0000,wapo,Microsoft exec called AI the ‘largest theft of...,https://www.washingtonpost.com/business/2026/0...
306,52,2026-09-17-23-20-15 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-pu...
319,51,2026-09-17-22-48-50 +0000,latimes,Governor's race heats up as Becerra meets fire...,https://www.latimes.com/california/story/2026-...
220,47,2026-09-18-09-59-52 +0000,wapo,"Their Gaza home was damaged, but they had nowh...",https://www.washingtonpost.com/world/2026/09/1...
343,46,2026-09-17-21-36-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...
89,44,2026-09-18-15-59-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
200,43,2026-09-18-10-54-02 +0000,nypost,Warren Buffett steps down as Berkshire chairma...,https://nypost.com/2026/09/18/business/berkshi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)