## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-10-19-18-59 +0000,nypost,Almost half of Muslim Americans have favorable...,https://nypost.com/2026/07/10/us-news/almost-h...
1,2026-07-10-19-15-00 +0000,wsj,Oil Posts Weekly Gains on Renewed Middle East ...,https://www.wsj.com/finance/commodities-future...
2,2026-07-10-19-14-20 +0000,nyt,Trump Cuts Habitat Protections for Endangered ...,https://www.nytimes.com/2026/07/10/climate/end...
3,2026-07-10-19-08-03 +0000,nyt,SK Hynix Stock Rises on First Day of US Trading,https://www.nytimes.com/2026/07/10/business/sk...
4,2026-07-10-19-01-16 +0000,nyt,Dinaw Mengestu Resigns as PEN America Presiden...,https://www.nytimes.com/2026/07/10/arts/pen-am...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
18   trump     36
155   iran     22
221     up     15
7      new     15
477  china     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
317,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...,117
9,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...,113
136,2026-07-10-14-25-14 +0000,nypost,Trump tells The Post he’s ‘left instructions’ ...,https://nypost.com/2026/07/10/us-news/trump-te...,106
318,2026-07-09-21-56-00 +0000,wsj,"Iran Planned New Trump Assassination Attempt, ...",https://www.wsj.com/politics/iran-planned-new-...,89
119,2026-07-10-15-16-05 +0000,nyt,Trump Says Negotiations With Iran Will Continu...,https://www.nytimes.com/2026/07/10/us/politics...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
317,117,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...
315,67,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...
9,62,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...
288,56,2026-07-10-00-07-58 +0000,bbc,Charlie Kirk murder suspect told roommate 'he ...,https://www.bbc.co.uk/news/articles/c621v466y9...
50,47,2026-07-10-17-45-24 +0000,nypost,Private-equity giant Apollo launches $7.7B off...,https://nypost.com/2026/07/10/business/private...
19,46,2026-07-10-18-36-33 +0000,nypost,Troubled son accused of killing mom in posh NY...,https://nypost.com/2026/07/10/us-news/troubled...
307,45,2026-07-09-22-33-54 +0000,latimes,California will see its first monsoon storms o...,https://www.latimes.com/california/story/2026-...
237,37,2026-07-10-08-22-11 +0000,wsj,Stock Market Today: SK Hynix Rallies in U.S. T...,https://www.wsj.com/livecoverage/stock-market-...
200,35,2026-07-10-10-55-38 +0000,nypost,Ryanair passenger’s head and shoulders hang fr...,https://nypost.com/2026/07/10/world-news/ryana...
114,35,2026-07-10-15-27-46 +0000,nyt,Gaza Aid Worker on His Way to Watch World Cup ...,https://www.nytimes.com/2026/07/09/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)