## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-10-53-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
1,2026-08-31-10-52-00 +0000,wsj,India’s Economy Posts Robust Growth Despite Mi...,https://www.wsj.com/economy/central-banking/in...
2,2026-08-31-10-51-00 +0000,wsj,Aon Strikes Roughly $17 Billion Deal for Insur...,https://www.wsj.com/finance/aon-nears-roughly-...
3,2026-08-31-10-50-30 +0000,nyt,What Is Phantom Ranch? Inside the Grand Canyon...,https://www.nytimes.com/2026/08/31/us/grand-ca...
4,2026-08-31-10-50-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2485/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
79   trump     18
43    iran     15
111  nepal     13
73      up     12
88   first     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...,73
72,2026-08-31-08-17-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...,61
138,2026-08-30-22-58-12 +0000,cbc,Grand Canyon flash flood leaves 1 dead and sev...,https://www.cbc.ca/news/world/grand-canyon-fla...,57
207,2026-08-30-16-31-00 +0000,wsj,Opinion | Trump’s New Iran Sanctions Put China...,https://www.wsj.com/opinion/trumps-new-iran-sa...,57
200,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,73,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...
72,61,2026-08-31-08-17-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
124,43,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
67,41,2026-08-31-08-53-10 +0000,nypost,Death toll tops 900 in Nepal-Tibet flooding as...,https://nypost.com/2026/08/31/world-news/death...
242,40,2026-08-30-12-22-38 +0000,cbc,At least 8 dead after ferry carrying nearly 27...,https://www.cbc.ca/news/world/ferry-capsize-cy...
209,38,2026-08-30-16-13-37 +0000,nypost,Google swaps Lake Ontario maps to ‘Lake Americ...,https://nypost.com/2026/08/30/us-news/google-m...
77,36,2026-08-31-07-14-21 +0000,wsj,Stock Market Today: Oil Climbs on Fresh Mideas...,https://www.wsj.com/livecoverage/stock-market-...
34,30,2026-08-31-10-00-00 +0000,nypost,Long Island Dems locked in civil war as member...,https://nypost.com/2026/08/31/us-news/long-isl...
46,30,2026-08-31-09-21-00 +0000,wsj,U.S. Treasury Yields Fall but 10-Year German B...,https://www.wsj.com/finance/investing/u-s-trea...
87,27,2026-08-31-05-15-00 +0000,wsj,China’s Biggest Airlines Post Over $1 Billion ...,https://www.wsj.com/business/airlines/chinas-b...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)