## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-07-13-00 +0000,wsj,"U.S. Treasury Yields Rise, Markets Remain Vola...",https://www.wsj.com/finance/investing/jgbs-mix...
1,2026-03-26-07-13-00 +0000,wsj,German Consumer Confidence Sinks to Two-Year L...,https://www.wsj.com/economy/german-consumer-co...
2,2026-03-26-07-07-00 +0000,wsj,Monte dei Paschi Board Revokes CEO’s Powers Am...,https://www.wsj.com/business/monte-dei-paschi-...
3,2026-03-26-07-05-00 +0000,wsj,Hapag-Lloyd Warns of Earnings Slump as Iran Wa...,https://www.wsj.com/business/earnings/hapag-ll...
4,2026-03-26-07-02-37 +0000,startribune,What a game! Timberwolves stage incredible ove...,https://www.startribune.com/minnesota-timberwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
32    iran     54
177  trump     45
13     war     26
457    oil     17
132     up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...,174
141,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...,155
270,2026-03-25-15-36-56 +0000,nyt,Oil Prices Rise After Iran Denies Talks With T...,https://www.nytimes.com/2026/03/24/business/oi...,145
65,2026-03-26-01-00-00 +0000,wsj,Trump Tells Aides He Wants Speedy End to Iran War,https://www.wsj.com/politics/elections/trump-t...,142
140,2026-03-25-21-23-15 +0000,nyt,Oil Prices Fall as Trump Shows Eagerness to Ta...,https://www.nytimes.com/2026/03/24/business/oi...,140

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,174,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...
143,78,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...
159,74,2026-03-25-20-50-44 +0000,nypost,Kristi Noem keeps her lover Corey Lewandowski ...,https://nypost.com/2026/03/25/us-news/kristi-n...
240,67,2026-03-25-17-06-24 +0000,nypost,"Meta, YouTube found liable for woman’s debilit...",https://nypost.com/2026/03/25/us-news/jury-tak...
244,64,2026-03-25-16-59-00 +0000,wsj,The Federal Reserve ran an operating loss of $...,https://www.wsj.com/economy/central-banking/fe...
297,59,2026-03-25-14-19-00 +0000,wsj,Trump plans to install some of the biggest nam...,https://www.wsj.com/politics/policy/trump-to-n...
141,56,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...
104,39,2026-03-25-22-29-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
222,39,2026-03-25-18-02-00 +0000,wsj,Democrat Emily Gregory beat a Trump-backed Rep...,https://www.wsj.com/politics/elections/democra...
151,37,2026-03-25-21-01-00 +0000,wsj,Lawmakers accused each other Wednesday of bein...,https://www.wsj.com/politics/policy/lawmakers-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)