## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-20-14-46-18 +0000,bbc,Lib Dems sleepwalking to irrelevance under Dav...,https://www.bbc.co.uk/news/articles/cq8r64r7d5...
1,2026-09-20-14-45-07 +0000,nyt,American Yom Kippur: How Jews Across the U.S. ...,https://www.nytimes.com/2026/09/20/us/yom-kipp...
2,2026-09-20-14-42-42 +0000,bbc,Ed Davey calls for immediate 10p cut to fuel duty,https://www.bbc.co.uk/news/articles/cr89j514dl...
3,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...
4,2026-09-20-14-32-27 +0000,nyt,Trump Says His D.C. Arch Would Be a ‘Military ...,https://www.nytimes.com/2026/09/20/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2523/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
23    trump     38
535      ai     11
74      new     11
31   drones     10
78      out     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...,99
8,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...,99
17,2026-09-20-13-57-21 +0000,nypost,Trump says his Triumphal Arch in Washington wi...,https://nypost.com/2026/09/20/us-news/trump-sa...,84
23,2026-09-20-12-46-09 +0000,wapo,Trump says planned arch will be ‘military comp...,https://www.washingtonpost.com/politics/2026/0...,83
12,2026-09-20-14-10-03 +0000,startribune,Trump says his planned arch would become a 'mi...,https://www.startribune.com/trump-says-his-pla...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,99,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...
141,48,2026-09-19-21-34-24 +0000,cbc,Saudi Arabia confirms Yemen's Houthi rebels tr...,https://www.cbc.ca/news/world/houthi-rebels-sa...
161,39,2026-09-19-19-13-51 +0000,wapo,"Trump to form ‘AI Force,’ name AI czar but rej...",https://www.washingtonpost.com/politics/2026/0...
8,38,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...
91,35,2026-09-20-05-01-47 +0000,bbc,Watch: Fans react as Ed Sheeran speaks out ove...,https://www.bbc.co.uk/news/videos/ck980m0pr1e0...
34,32,2026-09-20-11-42-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
98,30,2026-09-20-04-06-12 +0000,nypost,New Jersey mom charged with obstruction after ...,https://nypost.com/2026/09/20/us-news/nj-mom-j...
67,29,2026-09-20-09-24-24 +0000,nypost,Arizona ‘goon’ gang member arrested for 3rd ti...,https://nypost.com/2026/09/20/us-news/arizona-...
178,25,2026-09-19-16-53-42 +0000,cbc,Canada's top general loses election to become ...,https://www.cbc.ca/news/politics/canada-nato-j...
77,25,2026-09-20-09-00-00 +0000,wapo,"After losing their Voice of America jobs, jour...",https://www.washingtonpost.com/business/2026/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)