## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-12-15-00-13 +0000,nyt,Iran War Live Updates: Trump Says U.S. Will ‘B...,https://www.nytimes.com/live/2026/04/12/world/...
1,2026-04-12-15-00-09 +0000,bbc,Justin Bieber headlines Coachella with nostalg...,https://www.bbc.com/news/articles/c75kx5dw395o...
2,2026-04-12-15-00-00 +0000,wsj,How Oklahoma Landed America’s First Aluminum S...,https://www.wsj.com/business/how-oklahoma-land...
3,2026-04-12-15-00-00 +0000,nypost,Lying teen reinvented himself as an oligarch’s...,https://nypost.com/2026/04/12/world-news/secre...
4,2026-04-12-14-58-43 +0000,nypost,Kin of killed LI cop reap $200G from more than...,https://nypost.com/2026/04/12/us-news/officer-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2497/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
0        iran     35
4       trump     18
74      talks     18
119  swalwell     13
1         war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
35,2026-04-12-12-27-21 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...,119
0,2026-04-12-15-00-13 +0000,nyt,Iran War Live Updates: Trump Says U.S. Will ‘B...,https://www.nytimes.com/live/2026/04/12/world/...,110
10,2026-04-12-14-25-08 +0000,startribune,Trump threatens Strait of Hormuz blockade afte...,https://www.startribune.com/us-and-iran-end-ce...,110
26,2026-04-12-13-19-52 +0000,cbc,Trump vows to blockade Strait of Hormuz after ...,https://www.cbc.ca/news/world/trump-strait-of-...,104
22,2026-04-12-13-44-29 +0000,wapo,Trump announces naval blockade of Iran after I...,https://www.washingtonpost.com/world/2026/04/1...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
35,119,2026-04-12-12-27-21 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...
131,82,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
128,51,2026-04-11-23-42-55 +0000,nyt,"As Election Looms, Will Alito Retire, Giving T...",https://www.nytimes.com/2026/04/11/us/politics...
138,51,2026-04-11-23-00-00 +0000,wsj,"Before taking office, RFK Jr. promised to end ...",https://www.wsj.com/politics/policy/rfk-jr-raw...
60,33,2026-04-12-09-42-57 +0000,cbc,Fuel protests in Ireland continue as pumps run...,https://www.cbc.ca/news/world/ireland-fuel-pro...
64,32,2026-04-12-09-30-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
29,26,2026-04-12-12-55-17 +0000,cbc,"Ukraine, Russia accuse each other of violating...",https://www.cbc.ca/news/world/ukraine-russia-e...
81,26,2026-04-12-09-00-00 +0000,wsj,Jeanine Pirro’s ability to manage a mercurial ...,https://www.wsj.com/politics/policy/judge-jean...
184,26,2026-04-11-17-25-51 +0000,nypost,Zohran Mamdani’s legal advisor boasts anti-Isr...,https://nypost.com/2026/04/11/us-news/mamdani-...
22,21,2026-04-12-13-44-29 +0000,wapo,Trump announces naval blockade of Iran after I...,https://www.washingtonpost.com/world/2026/04/1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)