## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-18-46-08 +0000,nyt,Iran War Live Updates: Trump Says Israel and H...,https://www.nytimes.com/live/2026/06/01/world/...
1,2026-06-01-18-43-14 +0000,nyt,"To Understand the American Revolution, a Write...",https://www.nytimes.com/2026/05/27/travel/amer...
2,2026-06-01-18-42-59 +0000,nyt,Scott Pelley Accuses CBS News Boss of ‘Murderi...,https://www.nytimes.com/2026/06/01/business/me...
3,2026-06-01-18-41-00 +0000,wsj,Trump Says Israel and Hezbollah Have Agreed ‘A...,https://www.wsj.com/world/middle-east/u-s-stri...
4,2026-06-01-18-39-51 +0000,nypost,McDonald’s unveils new corporate strategy that...,https://nypost.com/2026/06/01/business/mcdonal...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     20
0     iran     16
121     ai     15
10     new     14
1      war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-06-01-18-46-08 +0000,nyt,Iran War Live Updates: Trump Says Israel and H...,https://www.nytimes.com/live/2026/06/01/world/...,102
188,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...,88
119,2026-06-01-14-00-11 +0000,nypost,Trump claims ‘I really don’t care’ if ‘very bo...,https://nypost.com/2026/06/01/world-news/iran-...,76
211,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...,63
209,2026-06-01-02-00-00 +0000,wsj,California Democrats head to a primary electio...,https://www.wsj.com/politics/elections/how-cal...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,102,2026-06-01-18-46-08 +0000,nyt,Iran War Live Updates: Trump Says Israel and H...,https://www.nytimes.com/live/2026/06/01/world/...
211,56,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...
72,54,2026-06-01-16-34-49 +0000,latimes,"AI company Anthropic files to list shares, hea...",https://www.latimes.com/business/story/2026-06...
149,51,2026-06-01-11-02-00 +0000,wsj,"If Democrats want to win the Senate, they like...",https://www.wsj.com/politics/graham-platner-sc...
157,44,2026-06-01-10-35-20 +0000,nypost,Jill Biden takes swipe at Kamala Harris’ claim...,https://nypost.com/2026/06/01/us-news/jill-bid...
11,33,2026-06-01-18-32-20 +0000,nypost,Iraqi terror suspect accused of plotting to bo...,https://nypost.com/2026/06/01/us-news/iraqi-te...
185,33,2026-06-01-08-18-41 +0000,nypost,"Iran shoots down US drone, attacks Kuwait — as...",https://nypost.com/2026/06/01/world-news/us-la...
16,31,2026-06-01-18-21-01 +0000,nypost,Oil prices jump after US and Iran exchange str...,https://nypost.com/2026/06/01/business/oil-pri...
251,30,2026-05-31-21-12-00 +0000,wsj,Incoming Fed Chairman Kevin Warsh wants the ce...,https://www.wsj.com/economy/central-banking/ke...
248,29,2026-05-31-21-27-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)