## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-19-26-03 +0000,nypost,Macy’s July 4 fireworks will shoot off from bo...,https://nypost.com/2026/06/30/us-news/macys-ju...
1,2026-06-30-19-19-25 +0000,nyt,U.S. and Iran to Meet with Mediators in Qatar,https://www.nytimes.com/live/2026/06/30/world/...
2,2026-06-30-19-19-23 +0000,nyt,"After U.S.-Iran War, Oman Is Said to Propose S...",https://www.nytimes.com/2026/06/30/world/middl...
3,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
4,2026-06-30-19-18-00 +0000,wsj,Oil Futures Post Sharpest Quarterly Drop Since...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
74        court     41
201     supreme     37
48        trump     31
104         new     20
168  birthright     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
325,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...,160
74,2026-06-30-17-15-04 +0000,startribune,"Supreme Court upholds birthright citizenship, ...",https://www.startribune.com/supreme-court-upho...,148
150,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,146
58,2026-06-30-18-01-22 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,145
153,2026-06-30-14-41-59 +0000,cbc,U.S. Supreme Court rules against Trump executi...,https://www.cbc.ca/news/world/us-scotus-ruling...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
325,160,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...
282,82,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
7,55,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
125,46,2026-06-30-16-02-50 +0000,nypost,NPR erroneously reports Samuel Alito is retiri...,https://nypost.com/2026/06/30/us-news/npr-erro...
190,44,2026-06-30-12-47-52 +0000,bbc,Cape Verde will beat Argentina 1-0 in World Cu...,https://www.bbc.co.uk/news/articles/c4gyez6z34...
2,38,2026-06-30-19-19-23 +0000,nyt,"After U.S.-Iran War, Oman Is Said to Propose S...",https://www.nytimes.com/2026/06/30/world/middl...
152,36,2026-06-30-14-43-47 +0000,nypost,Wife of Ukrainian oligarch with ties to Russia...,https://nypost.com/2026/06/30/world-news/wife-...
295,34,2026-06-29-23-08-47 +0000,nyt,"Andy Burnham, the UK’s Likely Next Prime Minis...",https://www.nytimes.com/2026/06/29/world/europ...
128,33,2026-06-30-15-53-59 +0000,latimes,Supreme Court rules states may ban trans athle...,https://www.latimes.com/politics/story/2026-06...
57,31,2026-06-30-18-02-00 +0000,wsj,Warsh Wants the Fed to Talk Less. That Only Ge...,https://www.wsj.com/finance/investing/kevin-wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)