## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-22-12-20 +0000,nyt,A Sherpa Survived 6 Days Alone on Everest. His...,https://www.nytimes.com/2026/06/05/world/asia/...
1,2026-06-05-22-09-52 +0000,nyt,"Trump Arch Will Need Red Lights, F.A.A. Says",https://www.nytimes.com/2026/06/05/us/politics...
2,2026-06-05-22-05-19 +0000,nypost,GOP firebrand rips lefty silence on NYC DSA po...,https://nypost.com/2026/06/05/us-news/gop-fire...
3,2026-06-05-22-04-34 +0000,nyt,"Ebola Cases May Top 20,000 in Three Months, C....",https://www.nytimes.com/2026/06/05/us/politics...
4,2026-06-05-22-02-16 +0000,latimes,Santa Monica man pleads guilty to 'doxing' ICE...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2458/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
9     trump     24
91      new     16
86   senate     14
186  market     14
167   putin     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,89
116,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,85
194,2026-06-05-13-12-51 +0000,nyt,Graham Platner Denies Hurting Ex-Girlfriend an...,https://www.nytimes.com/2026/06/04/us/politics...,77
124,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,74
185,2026-06-05-13-47-48 +0000,nypost,"Graham Platner, Susan Collins tied in Maine Se...",https://nypost.com/2026/06/05/us-news/graham-p...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,89,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
185,70,2026-06-05-13-47-48 +0000,nypost,"Graham Platner, Susan Collins tied in Maine Se...",https://nypost.com/2026/06/05/us-news/graham-p...
23,59,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
297,49,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
53,41,2026-06-05-20-21-38 +0000,nyt,Stocks Slide as Investors See Rates Rising Aft...,https://www.nytimes.com/2026/06/05/business/st...
64,38,2026-06-05-19-58-54 +0000,nypost,Mamdani-backed NY House candidate refuses to a...,https://nypost.com/2026/06/05/us-news/mamdani-...
230,36,2026-06-05-10-32-00 +0000,wsj,Eurozone Economy Shrank in First Quarter as Ir...,https://www.wsj.com/economy/eurozone-economy-s...
309,34,2026-06-05-00-00-00 +0000,wsj,Milei’s Online Trolling Fueled His Rise. It’s ...,https://www.wsj.com/world/americas/mileis-onli...
277,34,2026-06-05-05-17-13 +0000,bbc,Xi Jinping to meet Kim Jong Un in rare visit t...,https://www.bbc.com/news/articles/clypym3q7p1o...
49,34,2026-06-05-20-31-05 +0000,nyt,’60 Minutes’ Stars Will Stay After Pelley’s Fi...,https://www.nytimes.com/2026/06/05/business/me...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)