## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-18-16-24 +0000,nyt,Republicans Brace for Brutal Midterms as Trump...,https://www.nytimes.com/2026/04/28/us/politics...
1,2026-04-28-18-14-57 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/28/us/kin...
2,2026-04-28-18-13-55 +0000,nypost,Wild video shows hot air balloon slam into Sac...,https://nypost.com/2026/04/28/us-news/video-sh...
3,2026-04-28-18-13-29 +0000,nyt,What to Know About the Kimmel vs. Trump Feud,https://www.nytimes.com/2026/04/28/arts/televi...
4,2026-04-28-18-11-52 +0000,cbc,Former Fauci adviser indicted for allegedly co...,https://www.cbc.ca/news/health/fauci-adviser-i...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2582/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
4      trump     63
160     iran     26
34      king     21
35   charles     17
119      new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
209,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,216
24,2026-04-28-17-45-20 +0000,nypost,President Trump & Melania put on historic Whit...,https://nypost.com/2026/04/28/us-news/presiden...,165
67,2026-04-28-16-27-08 +0000,nypost,President Trump gives first lady Melania a pla...,https://nypost.com/2026/04/28/us-news/presiden...,157
231,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,154
44,2026-04-28-17-06-15 +0000,nyt,President and First Lady Melania Trump Demand ...,https://www.nytimes.com/2026/04/27/us/politics...,151

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
209,216,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
139,100,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
24,83,2026-04-28-17-45-20 +0000,nypost,President Trump & Melania put on historic Whit...,https://nypost.com/2026/04/28/us-news/presiden...
302,57,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...
373,54,2026-04-27-20-08-59 +0000,latimes,OpenAI CEO Sam Altman apologizes for not alert...,https://www.latimes.com/business/story/2026-04...
30,51,2026-04-28-17-26-59 +0000,nypost,California Dems plot bombshell new abortion sh...,https://nypost.com/2026/04/28/us-news/californ...
126,44,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
370,41,2026-04-27-20-12-55 +0000,nyt,Iran Offers Plan to Focus on Strait of Hormuz ...,https://www.nytimes.com/2026/04/27/world/middl...
194,40,2026-04-28-11-44-00 +0000,wsj,"Pushing past a third assassination attempt, th...",https://www.wsj.com/politics/policy/pushing-pa...
133,39,2026-04-28-14-21-00 +0000,wsj,China’s Ban on Meta-Manus Deal Shows Strains i...,https://www.wsj.com/world/china/chinas-ban-on-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)