## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-26-09-06-00 +0000,wsj,The U.S. Is Trying to Strangle Iran’s Economy....,https://www.wsj.com/world/middle-east/the-u-s-...
1,2026-08-26-09-04-14 +0000,nyt,"Even as Trump’s Standing Slips, He Slingshots ...",https://www.nytimes.com/2026/08/26/us/politics...
2,2026-08-26-09-04-09 +0000,nyt,Their Children Want to Play Football. Parents ...,https://www.nytimes.com/2026/08/26/us/parents-...
3,2026-08-26-09-04-03 +0000,nyt,‘Honeymoon’s Over’: Warsh Under Pressure as Fe...,https://www.nytimes.com/2026/08/26/business/ke...
4,2026-08-26-09-04-00 +0000,wsj,European Chip Stocks Mixed Ahead of Nvidia Ear...,https://www.wsj.com/finance/stocks/nikkei-fall...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2493/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
8     trump     51
169  canada     23
454   trade     18
2      iran     18
346     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
276,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...,158
325,2026-08-25-12-33-40 +0000,nypost,Trump threatens to rename Lake Ontario as ‘Lak...,https://nypost.com/2026/08/25/us-news/trump-th...,151
268,2026-08-25-16-25-46 +0000,wapo,Trump says U.S. could rename Lake Ontario as L...,https://www.washingtonpost.com/politics/2026/0...,147
55,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...,140
68,2026-08-26-03-02-19 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
276,158,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...
55,89,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...
255,69,2026-08-25-17-06-00 +0000,wsj,CIA Director John Ratcliffe made a surprise vi...,https://www.wsj.com/world/cia-director-john-ra...
162,64,2026-08-25-21-10-05 +0000,nypost,Oil tanker attacked as it tried to sneak throu...,https://nypost.com/2026/08/25/world-news/hormu...
74,60,2026-08-26-02-09-20 +0000,nyt,Dolly Parton’s Death Hits Home for Tennesseans...,https://www.nytimes.com/2026/08/25/us/nashvill...
113,49,2026-08-25-23-33-14 +0000,nyt,Supreme Court Ruling on Mail-in Voting Could A...,https://www.nytimes.com/2026/08/25/us/mail-in-...
347,48,2026-08-25-11-14-00 +0000,wsj,Michigan’s Abdul El-Sayed will need to win ove...,https://www.wsj.com/politics/elections/four-ta...
267,47,2026-08-25-16-29-51 +0000,chitri,Ex-Loretto Hospital CEO gets diversion deal am...,https://www.chicagotribune.com/2026/08/25/ex-l...
75,44,2026-08-26-02-08-47 +0000,nypost,California lawmaker’s unprecedented attack on ...,https://nypost.com/2026/08/25/us-news/californ...
33,35,2026-08-26-07-48-50 +0000,bbc,Household energy bills to hit three-year high ...,https://www.bbc.co.uk/news/articles/cqjkl1xvgw...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)