## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-22-57-58 +0000,nyt,Justice Dept. Drops Prosecution of Veteran Who...,https://www.nytimes.com/2026/03/13/us/politics...
1,2026-03-13-22-56-28 +0000,nyt,Messi Meets Trump and Argentina Is Divided,https://www.nytimes.com/2026/03/13/world/ameri...
2,2026-03-13-22-53-58 +0000,nyt,The Fall of Noma’s Chef Reverberates in the Re...,https://www.nytimes.com/2026/03/13/dining/rene...
3,2026-03-13-22-50-29 +0000,nyt,"Kennedy Center’s President, Richard Grenell, I...",https://www.nytimes.com/2026/03/13/arts/kenned...
4,2026-03-13-22-45-16 +0000,nyt,Judge Temporarily Blocks Trump Demand for Stud...,https://www.nytimes.com/2026/03/13/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2483/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
107   iran     53
114    war     41
10   trump     39
117    oil     23
140    new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-03-13-22-32-22 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: O...,https://www.nytimes.com/live/2026/03/13/world/...,225
354,2026-03-13-01-32-01 +0000,nyt,Trump Removes Sanctions on Russia to Help Oil ...,https://www.nytimes.com/2026/03/12/us/politics...,156
180,2026-03-13-16-17-58 +0000,nyt,Trump-Iran Timeline: Key Moments Leading Up to...,https://www.nytimes.com/2026/03/13/us/politics...,152
164,2026-03-13-17-09-48 +0000,nypost,Trump says US seizing Kharg Island ‘not high o...,https://nypost.com/2026/03/13/us-news/trump-sa...,144
243,2026-03-13-13-00-58 +0000,nyt,Trump’s Iran War Is Causing Problems For His A...,https://www.nytimes.com/2026/03/12/world/europ...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,225,2026-03-13-22-32-22 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: O...,https://www.nytimes.com/live/2026/03/13/world/...
49,86,2026-03-13-21-37-00 +0000,wsj,Trump signed two executive orders that aim to ...,https://www.wsj.com/politics/policy/trump-targ...
230,57,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
122,45,2026-03-13-18-58-00 +0000,wsj,"TotalEnergies Shutting Production in Qatar, Ir...",https://www.wsj.com/business/energy-oil/totale...
109,45,2026-03-13-19-50-01 +0000,nypost,"Pentagon sending assault ship, at least 2,500 ...",https://nypost.com/2026/03/13/us-news/pentagon...
185,42,2026-03-13-16-06-47 +0000,nypost,"Stocks fall, oil holds above $100 after tempor...",https://nypost.com/2026/03/13/business/stocks-...
248,42,2026-03-13-12-39-28 +0000,cbc,"Canada's economy lost 84,000 jobs in February,...",https://www.cbc.ca/news/business/canada-labour...
264,39,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
110,38,2026-03-13-19-47-21 +0000,nypost,Pirro slams ‘activist judge’ for blocking DOJ ...,https://nypost.com/2026/03/13/us-news/federal-...
291,36,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)