## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-01-11-02-00 +0000,nyt,Search Continues for Missing Climbers After Pa...,https://www.nytimes.com/2026/08/01/world/asia/...
1,2026-08-01-11-00-05 +0000,bbc,Spain attacks 'selfish' response of some EU co...,https://www.bbc.co.uk/news/articles/cx2v91xn1z...
2,2026-08-01-11-00-00 +0000,wapo,U.S. general warns Pentagon he lacks sufficien...,https://www.washingtonpost.com/national-securi...
3,2026-08-01-11-00-00 +0000,missionlocal,The Richmond’s Picture Machine is the place to...,https://missionlocal.org/2026/08/richmond-olde...
4,2026-08-01-10-58-22 +0000,nyt,Kuwait Says It Downed Iranian Drones as Mideas...,https://www.nytimes.com/2026/08/01/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
109       trump     34
182        iran     16
12        ceuta     14
250         new     14
97   california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
217,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,89
271,2026-07-31-16-21-46 +0000,nypost,Trump orders more strikes on Iran after ‘losin...,https://nypost.com/2026/07/31/us-news/trump-pr...,83
28,2026-08-01-09-02-16 +0000,nyt,Fact-Checking Trump’s Claims About the Effect ...,https://www.nytimes.com/2026/08/01/us/politics...,82
142,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...,82
139,2026-07-31-22-19-00 +0000,wsj,Trump Orders Fresh Attack Against Iran as War ...,https://www.wsj.com/world/middle-east/trump-so...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
217,89,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...
337,69,2026-07-31-12-57-09 +0000,chitri,Senior FIFA executive says staff was deceived ...,https://www.chicagotribune.com/2026/07/31/fifa...
142,67,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...
156,62,2026-07-31-21-33-06 +0000,nypost,Jeanine Pirro drops Reflecting Pool vandalism ...,https://nypost.com/2026/07/31/us-news/jeanine-...
324,59,2026-07-31-13-27-35 +0000,chitri,Major oil companies reap massive profits as US...,https://www.chicagotribune.com/2026/07/31/majo...
287,53,2026-07-31-15-48-34 +0000,bbc,Watch: Tens of thousands of migrants enter Spa...,https://www.bbc.co.uk/news/videos/cnvnml1pen6o...
263,48,2026-07-31-16-49-00 +0000,wsj,Richmond Fed President Tom Barkin said it is “...,https://www.wsj.com/economy/central-banking/to...
253,46,2026-07-31-17-20-50 +0000,nypost,California Gov. Gavin Newsom releases long-awa...,https://nypost.com/2026/07/31/us-news/gavin-ne...
90,40,2026-08-01-01-01-00 +0000,wsj,"In purple Michigan, Rep. Haley Stevens and Abd...",https://www.wsj.com/politics/elections/michiga...
301,37,2026-07-31-14-53-12 +0000,nypost,Sen. Bernie Moreno demands national security p...,https://nypost.com/2026/07/31/us-news/sen-bern...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)