## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-30-02-56-00 +0000,wsj,"A divided committee, external political pressu...",https://www.wsj.com/economy/central-banking/po...
1,2026-04-30-02-53-37 +0000,cbc,Report into Bondi Beach mass shooting calls fo...,https://www.cbc.ca/news/world/bondi-beach-shoo...
2,2026-04-30-02-49-00 +0000,wsj,"Yen Crosses Key Threshold, But Don’t Count on ...",https://www.wsj.com/finance/currencies/yen-cro...
3,2026-04-30-02-47-13 +0000,nyt,House Adopts Budget to Unlock $70 Billion for ...,https://www.nytimes.com/2026/04/29/us/politics...
4,2026-04-30-02-41-40 +0000,startribune,Minnesota Frost vs. Montreal Victoire playoff ...,https://www.startribune.com/minnesota-frost-mo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2710/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
187    trump     44
99     court     32
195      new     32
98   supreme     23
448     iran     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
424,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...,187
398,2026-04-29-09-00-00 +0000,wsj,In a bid to keep construction of the White Hou...,https://www.wsj.com/politics/national-security...,150
270,2026-04-29-16-28-37 +0000,nyt,Florida Lawmakers Were Debating New Congressio...,https://www.nytimes.com/2026/04/29/us/election...,149
144,2026-04-29-21-26-00 +0000,wsj,"Powell said he’ll stay on the Fed board, the S...",https://www.wsj.com/politics/policy/powelland-...,147
248,2026-04-29-17-46-06 +0000,nyt,All Six Conservative Supreme Court Justices At...,https://www.nytimes.com/2026/04/29/us/politics...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
424,187,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...
100,111,2026-04-29-22-40-00 +0000,wsj,In his first public testimony since the war in...,https://www.wsj.com/politics/national-security...
109,94,2026-04-29-22-23-00 +0000,wsj,The Fed held rates steady; but in a contentiou...,https://www.wsj.com/economy/central-banking/fe...
270,92,2026-04-29-16-28-37 +0000,nyt,Florida Lawmakers Were Debating New Congressio...,https://www.nytimes.com/2026/04/29/us/election...
134,68,2026-04-29-21-36-00 +0000,wsj,The U.S. charged the governor of Mexico’s Sina...,https://www.wsj.com/world/americas/u-s-charges...
144,56,2026-04-29-21-26-00 +0000,wsj,"Powell said he’ll stay on the Fed board, the S...",https://www.wsj.com/politics/policy/powelland-...
170,55,2026-04-29-20-43-00 +0000,wsj,MGM Resorts Reports Lower First-Quarter Profit...,https://www.wsj.com/business/earnings/mgm-reso...
26,51,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...
215,48,2026-04-29-18-55-00 +0000,wsj,Two California ballot initiatives funded in pa...,https://www.wsj.com/politics/policy/sergey-bri...
269,46,2026-04-29-16-30-04 +0000,nypost,Uber will let you book hotels in deal with Exp...,https://nypost.com/2026/04/29/business/uber-wi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)