## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-03-49-22 +0000,nyt,Iran War Live Updates: Trump Says U.S. Militar...,https://www.nytimes.com/live/2026/03/31/world/...
1,2026-04-01-03-40-18 +0000,nypost,Republic Airways pilots mistakenly contact JFK...,https://nypost.com/2026/03/31/us-news/republic...
2,2026-04-01-03-35-16 +0000,nypost,Trump wages war on California insurance giants...,https://nypost.com/2026/03/31/us-news/trump-wa...
3,2026-04-01-03-33-52 +0000,nypost,Identity of homeless man who randomly stabbed ...,https://nypost.com/2026/03/31/us-news/identity...
4,2026-04-01-03-29-00 +0000,wsj,"Japan Firms Stay Upbeat Under Pressure, Keepin...",https://www.wsj.com/economy/central-banking/ja...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2510/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     56
0     iran     48
1      war     38
95     end     16
126  judge     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
285,2026-03-31-14-15-31 +0000,latimes,Trump says he expects U.S. to end involvement ...,https://www.latimes.com/politics/story/2026-03...,184
164,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,178
26,2026-04-01-02-12-45 +0000,bbc,Asia stocks jump after Trump suggests Iran war...,https://www.bbc.com/news/articles/c2489v97842o...,174
0,2026-04-01-03-49-22 +0000,nyt,Iran War Live Updates: Trump Says U.S. Militar...,https://www.nytimes.com/live/2026/03/31/world/...,166
54,2026-04-01-00-33-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,155

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
285,184,2026-03-31-14-15-31 +0000,latimes,Trump says he expects U.S. to end involvement ...,https://www.latimes.com/politics/story/2026-03...
145,61,2026-03-31-21-10-50 +0000,startribune,Supreme Court strikes down Colorado’s conversi...,https://www.startribune.com/supreme-court-stri...
286,59,2026-03-31-14-14-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
132,57,2026-03-31-21-34-47 +0000,nypost,Iran’s parliament approves plan to impose toll...,https://nypost.com/2026/03/31/world-news/iran-...
353,50,2026-03-31-09-39-27 +0000,nypost,Gas prices rise above $4 a gallon for first ti...,https://nypost.com/2026/03/31/business/gas-pri...
319,50,2026-03-31-12-11-09 +0000,cbc,Hegseth lifts U.S. Army's suspension of 2 mili...,https://www.cbc.ca/news/world/us-kid-rock-army...
62,49,2026-04-01-00-10-00 +0000,wsj,President Trump signed an executive order Tues...,https://www.wsj.com/politics/policy/trump-orde...
259,45,2026-03-31-15-46-18 +0000,nypost,Kristi Noem weighs in on report husband lives ...,https://nypost.com/2026/03/31/us-news/kristi-n...
88,43,2026-03-31-23-15-12 +0000,latimes,MAHA says red meat and beef tallow will make y...,https://www.latimes.com/science/story/2026-03-...
375,40,2026-03-31-07-40-08 +0000,wsj,"Stock Market News, March 31, 2026: Nasdaq Lead...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)