## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-21-07-46 +0000,wapo,Families of children killed in strike on Irani...,https://www.washingtonpost.com/world/2026/07/0...
1,2026-07-05-21-04-55 +0000,bbc,Super typhoon Bavi nears Pacific islands with ...,https://www.bbc.co.uk/news/articles/cr7xpgx50j...
2,2026-07-05-21-02-44 +0000,nypost,Goon opens fire near children on NYC playgroun...,https://nypost.com/2026/07/05/us-news/goon-ope...
3,2026-07-05-20-56-08 +0000,nypost,Terrifying moment Waymo drives through explodi...,https://nypost.com/2026/07/05/us-news/waymo-dr...
4,2026-07-05-20-51-57 +0000,latimes,L.A. County heat advisory: When will high temp...,https://www.latimes.com/entertainment-arts/bus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
54     trump     24
75      july     18
499       th     15
68      iran     13
8    funeral     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,81
165,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...,78
164,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,76
153,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,75
163,2026-07-05-05-02-36 +0000,nyt,"In Fourth of July Speech, Trump Celebrates Ame...",https://www.nytimes.com/2026/07/05/us/politics...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,81,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
153,75,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...
121,67,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...
51,39,2026-07-05-18-30-38 +0000,nypost,Long Island man killed when firework blows up ...,https://nypost.com/2026/07/05/us-news/long-isl...
26,34,2026-07-05-19-19-06 +0000,nypost,Pictures show aftermath of Paul Pelosi’s alleg...,https://nypost.com/2026/07/05/us-news/pictures...
17,27,2026-07-05-20-07-25 +0000,nypost,Harrowing video captures moment inside seaplan...,https://nypost.com/2026/07/05/us-news/harrowin...
196,26,2026-07-04-23-09-11 +0000,nypost,Rep. Mike Lawler predicts midterms will be dec...,https://nypost.com/2026/07/04/us-news/rep-mike...
95,25,2026-07-05-14-37-30 +0000,nypost,Pa. Gov. Josh Shapiro slams socialist NY Dem D...,https://nypost.com/2026/07/05/us-news/pa-gov-j...
154,24,2026-07-05-07-19-08 +0000,bbc,Scorching heat and delays: How Washington DC m...,https://www.bbc.co.uk/news/videos/cwyk2ypj014o...
173,24,2026-07-05-02-55-07 +0000,latimes,Fans scram: Fireworks head into the stands at ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)