## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-27-13-15-49 +0000,nyt,Safety Experts Considered LaGuardia Challengin...,https://www.nytimes.com/2026/03/26/business/la...
1,2026-03-27-13-14-41 +0000,nyt,Iran War Live Updates: Israel and Iran Exchang...,https://www.nytimes.com/live/2026/03/27/world/...
2,2026-03-27-13-11-59 +0000,bbc,Savannah Guthrie to return to Today show as se...,https://www.bbc.com/news/articles/c79jd4x572qo...
3,2026-03-27-13-10-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
4,2026-03-27-13-09-03 +0000,nyt,‘No Kings’ Protests Across U.S. Cities: What W...,https://www.nytimes.com/2026/03/27/us/no-kings...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6     iran     55
13   trump     53
7      war     39
111    new     20
51    will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-27-13-14-41 +0000,nyt,Iran War Live Updates: Israel and Iran Exchang...,https://www.nytimes.com/live/2026/03/27/world/...,230
368,2026-03-26-16-18-00 +0000,wsj,President Trump has told associates in recent ...,https://www.wsj.com/politics/elections/trump-t...,210
70,2026-03-27-10-42-00 +0000,wsj,If there is one constant in Trump’s Washington...,https://www.wsj.com/politics/for-trump-a-deadl...,178
329,2026-03-26-18-05-00 +0000,cbc,"Iran is 'begging to make a deal' to end war, s...",https://www.cbc.ca/news/world/trump-iran-war-d...,170
356,2026-03-26-16-54-14 +0000,latimes,"Trump projects confidence, claims Iran is 'beg...",https://www.latimes.com/world-nation/story/202...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,230,2026-03-27-13-14-41 +0000,nyt,Iran War Live Updates: Israel and Iran Exchang...,https://www.nytimes.com/live/2026/03/27/world/...
164,79,2026-03-27-03-33-00 +0000,wsj,President Trump said he would sign an executiv...,https://www.wsj.com/politics/policy/republican...
144,65,2026-03-27-06-40-44 +0000,nypost,End to airport misery in sight as Senate appro...,https://nypost.com/2026/03/27/us-news/senate-a...
104,57,2026-03-27-09-01-44 +0000,nyt,Will ICE Change Under Its New Leader?,https://www.nytimes.com/video/us/politics/1000...
308,55,2026-03-26-18-52-16 +0000,nypost,Iran wants to charge ships for safe passage th...,https://nypost.com/2026/03/26/business/iran-wa...
207,51,2026-03-27-00-11-00 +0000,wsj,A U.S. federal judge on Thursday halted the Tr...,https://www.wsj.com/politics/policy/anthropic-...
378,43,2026-03-26-15-50-00 +0000,wsj,World governments were buried in public debt o...,https://www.wsj.com/economy/global/energy-pric...
55,42,2026-03-27-11-00-00 +0000,wsj,China opened two probes into U.S. trade practi...,https://www.wsj.com/economy/trade/china-initia...
222,40,2026-03-26-23-18-22 +0000,nypost,Paralyzed gang rape victim’s best friend made ...,https://nypost.com/2026/03/26/world-news/paral...
339,37,2026-03-26-17-50-51 +0000,wapo,Pentagon considers diverting Ukraine military ...,https://www.washingtonpost.com/national-securi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)