## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-23-12-37 +0000,wapo,"Trump’s $100,000 fee on H-1B visas for highly ...",https://www.washingtonpost.com/business/2026/0...
1,2026-06-08-23-06-30 +0000,bbc,Could humanoid robots be heading for the battl...,https://www.bbc.com/news/articles/cedpxwe26l1o...
2,2026-06-08-23-06-07 +0000,bbc,How driving test booking is changing for learn...,https://www.bbc.com/news/articles/ckgpl9zdw3po...
3,2026-06-08-23-05-32 +0000,bbc,Driving test booking rules tightened after tho...,https://www.bbc.com/news/articles/c4gyel9n02zo...
4,2026-06-08-23-05-21 +0000,nypost,Sports store company to close 175 US locations...,https://nypost.com/2026/06/08/business/hibbett...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2442/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     30
112    iran     29
113  israel     22
122     new     15
396      up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
33,2026-06-08-21-53-17 +0000,nyt,Live Updates: Israel Halts Iran Strikes After ...,https://www.nytimes.com/live/2026/06/08/world/...,110
166,2026-06-08-16-39-22 +0000,nypost,Netanyahu says Israel will ‘hold fire’ on Iran...,https://nypost.com/2026/06/08/us-news/netanyah...,101
228,2026-06-08-11-42-45 +0000,latimes,Trump tells Iran and Israel to stop 'shooting'...,https://www.latimes.com/world-nation/story/202...,94
87,2026-06-08-20-28-25 +0000,nyt,Netanyahu Called Off Iran Strikes After Trump ...,https://www.nytimes.com/2026/06/08/us/politics...,93
78,2026-06-08-20-55-01 +0000,startribune,Israel and Iran appear to pause strikes after ...,https://www.startribune.com/israel-says-it-has...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
33,110,2026-06-08-21-53-17 +0000,nyt,Live Updates: Israel Halts Iran Strikes After ...,https://www.nytimes.com/live/2026/06/08/world/...
273,64,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
90,53,2026-06-08-20-16-00 +0000,wsj,A federal judge invalidated the Trump administ...,https://www.wsj.com/politics/policy/judge-stri...
219,48,2026-06-08-12-15-14 +0000,nypost,Two dead as private jet crashes in Dominican R...,https://nypost.com/2026/06/08/world-news/priva...
177,43,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
79,42,2026-06-08-20-54-29 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
111,41,2026-06-08-19-11-20 +0000,nypost,Spencer Pratt issues bold rallying cry after N...,https://nypost.com/2026/06/08/us-news/spencer-...
80,39,2026-06-08-20-50-00 +0000,wsj,Many primary races around the U.S. have turned...,https://www.wsj.com/politics/elections/midterm...
210,39,2026-06-08-13-47-47 +0000,nyt,Mexico City’s Airport Got a $500 Million Renov...,https://www.nytimes.com/2026/06/07/world/ameri...
38,33,2026-06-08-21-47-54 +0000,nypost,Under-the-radar Supreme Court case could end C...,https://nypost.com/2026/06/08/us-news/under-th...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)