## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-16-56-43 +0000,nypost,French police detain 14-year-old suspected of ...,https://nypost.com/2026/10/12/world-news/frenc...
1,2026-10-12-16-55-14 +0000,bbc,Motion of no-confidence in Sinn Féin ministers...,https://www.bbc.co.uk/news/articles/c68jz0282r...
2,2026-10-12-16-53-00 +0000,bbc,Six Ukrainian energy sites hit by Russia since...,https://www.bbc.co.uk/news/articles/cvlyd4pdlw...
3,2026-10-12-16-53-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
4,2026-10-12-16-53-00 +0000,wsj,Ilhan Omar’s Home Is Searched by Federal Agents,https://www.wsj.com/politics/policy/ilhan-omar...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
26     trump     37
21    energy     18
24    russia     17
213    saudi     13
207  ukraine     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...,130
111,2026-10-12-11-47-59 +0000,nypost,Zelensky says Russia still striking energy fac...,https://nypost.com/2026/10/12/world-news/zelen...,110
269,2026-10-11-18-10-58 +0000,chitri,Pres. Donald Trump says Russia and Ukraine rea...,https://www.chicagotribune.com/2026/10/11/trum...,110
237,2026-10-11-21-22-00 +0000,wsj,Trump Pushes Russia-Ukraine Energy Ceasefire a...,https://www.wsj.com/world/trump-declares-a-rus...,108
2,2026-10-12-16-53-00 +0000,bbc,Six Ukrainian energy sites hit by Russia since...,https://www.bbc.co.uk/news/articles/cvlyd4pdlw...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,130,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...
117,50,2026-10-12-11-14-24 +0000,nypost,Disturbing video shows moment Houthi terrorist...,https://nypost.com/2026/10/12/world-news/distu...
147,45,2026-10-12-10-00-00 +0000,nypost,AI safety ‘doomers’ pouring cash into Minnesot...,https://nypost.com/2026/10/12/business/ai-safe...
70,43,2026-10-12-14-25-38 +0000,nypost,San Francisco’s former top female cop and daug...,https://nypost.com/2026/10/12/us-news/ex-calif...
3,40,2026-10-12-16-53-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
219,38,2026-10-11-23-39-12 +0000,bbc,Robert Pattinson on new film Primetime and how...,https://www.bbc.co.uk/news/articles/cmn5d92423...
136,37,2026-10-12-10-27-34 +0000,nypost,Family of Thai teen sex worker found stuffed ...,https://nypost.com/2026/10/12/world-news/famil...
54,35,2026-10-12-15-20-24 +0000,nypost,Mom launches furious tirade on dad who shot th...,https://nypost.com/2026/10/12/us-news/mom-laun...
92,32,2026-10-12-13-22-27 +0000,wapo,Judge blocks Trump administration from airing ...,https://www.washingtonpost.com/politics/2026/1...
64,32,2026-10-12-14-58-48 +0000,chitri,Elon Musk quietly becomes biggest known donor ...,https://www.chicagotribune.com/2026/10/12/elon...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)