## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-22-14-55-50 +0000,bbc,Police should not be scared to wade in to stop...,https://www.bbc.co.uk/news/articles/cj5yn079w7...
1,2026-10-22-14-53-24 +0000,nyt,Powerful Virginia Lawmaker Indicted Over Marij...,https://www.nytimes.com/2026/10/22/us/louise-l...
2,2026-10-22-14-52-27 +0000,nypost,Earthquake rocks California city overnight Wed...,https://nypost.com/2026/10/22/us-news/magnitud...
3,2026-10-22-14-44-11 +0000,nypost,Looksmaxxing influencer Clavicular brings bark...,https://nypost.com/2026/10/22/us-news/looksmax...
4,2026-10-22-14-44-00 +0000,wsj,NYC to Vote on Horse-Carriage Ban,https://www.wsj.com/us-news/nyc-to-vote-on-hor...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2674/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
271         new     29
141       trump     22
95           ai     20
285      senate     18
14   california     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...,114
410,2026-10-21-16-48-37 +0000,nypost,Speculation — and anxiety — growing that Mark ...,https://nypost.com/2026/10/21/business/will-ma...,101
97,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...,97
245,2026-10-21-23-59-30 +0000,nypost,Mike Rogers says Abdul El-Sayed is a national ...,https://nypost.com/2026/10/21/us-news/rogers-a...,96
275,2026-10-21-22-12-19 +0000,nypost,Meta stock surges on strong earnings report; t...,https://nypost.com/2026/10/21/business/meta-st...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,114,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...
410,101,2026-10-21-16-48-37 +0000,nypost,Speculation — and anxiety — growing that Mark ...,https://nypost.com/2026/10/21/business/will-ma...
361,95,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...
114,73,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...
145,57,2026-10-22-10-00-00 +0000,latimes,Behind Elon Musk's plans for a mega-merger of ...,https://www.latimes.com/business/story/2026-10...
293,53,2026-10-21-21-25-00 +0000,nypost,Persian Gulf oil exports surpass pre-war high ...,https://nypost.com/2026/10/21/world-news/persi...
227,49,2026-10-22-01-18-45 +0000,nypost,Ilhan Omar gives head-scratching response when...,https://nypost.com/2026/10/21/us-news/ilhan-om...
86,48,2026-10-22-12-00-00 +0000,nypost,"LA voters scorch state of the city, huge numbe...",https://nypost.com/2026/10/22/us-news/karen-ba...
95,47,2026-10-22-11-39-49 +0000,cbc,Russia pounds Ukraine's capital Kyiv with miss...,https://www.cbc.ca/news/world/ukraine-russia-m...
97,46,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)