## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-18-55-02 +0000,startribune,2 dead from storm as Isaias brings threat of f...,https://www.startribune.com/hundreds-of-thousa...
1,2026-10-10-18-53-59 +0000,nyt,"One Philadelphia Police Officer Killed, Anothe...",https://www.nytimes.com/2026/10/10/us/philadel...
2,2026-10-10-18-53-00 +0000,wsj,Saudi Arabia Closes Airport in Riyadh After Da...,https://www.wsj.com/world/middle-east/iran-bac...
3,2026-10-10-18-51-38 +0000,nyt,Christa Pike Discharged From Hospital After Su...,https://www.nytimes.com/2026/10/10/us/politics...
4,2026-10-10-18-45-20 +0000,nyt,"Clara Wu Tsai, the Billionaire Who Wants Brook...",https://www.nytimes.com/2026/10/09/style/clara...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
44       trump     46
25         new     22
119         he     15
32   execution     13
70   president     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
223,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,185
235,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,133
35,2026-10-10-17-35-33 +0000,chitri,Pres. Donald Trump says Ukraine should get a n...,https://www.chicagotribune.com/2026/10/10/trum...,127
168,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...,123
9,2026-10-10-18-36-23 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
223,185,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
202,78,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
23,60,2026-10-10-18-08-00 +0000,wsj,"Kimberly Guilfoyle, as America’s newly minted ...",https://www.wsj.com/politics/policy/at-davos-k...
166,51,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...
29,46,2026-10-10-17-44-26 +0000,bbc,US murderer Christa Pike discharged from hospi...,https://www.bbc.co.uk/news/articles/cmlyle97pq...
103,43,2026-10-10-10-06-23 +0000,bbc,Rogue Anthropic AI agent gave police fake tip ...,https://www.bbc.co.uk/news/articles/cqkg50j1yd...
30,37,2026-10-10-17-41-47 +0000,nypost,Cornell handed students raunchy sex checklist ...,https://nypost.com/2026/10/10/us-news/cornell-...
94,34,2026-10-10-11-24-25 +0000,nypost,Israeli mom whose son was murdered on Oct. 7 n...,https://nypost.com/2026/10/10/world-news/israe...
196,33,2026-10-09-22-38-00 +0000,wsj,The planned execution of Nidal Hasan has spark...,https://www.wsj.com/politics/national-security...
56,33,2026-10-10-16-15-08 +0000,nypost,‘Drunk’ off-duty ICE agent shot after he’s rou...,https://nypost.com/2026/10/10/us-news/off-duty...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)