## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-19-00-00 +0000,missionlocal,Excelsior Buzz: Lucha Libre and Salvadoran her...,https://missionlocal.org/2026/10/lucha-libre-a...
1,2026-10-08-19-00-00 +0000,missionlocal,"Sunset Buzz: Farewell to poke, hello to Yemeni...",https://missionlocal.org/2026/10/sf-sunset-pok...
2,2026-10-08-18-59-06 +0000,nypost,Mayor Karen Bass slams ‘irresponsible’ Nithya ...,https://nypost.com/2026/10/08/us-news/la-mayor...
3,2026-10-08-18-56-27 +0000,nyt,Canadian Poet Anne Carson Is Awarded Nobel Pri...,https://www.nytimes.com/2026/10/08/books/nobel...
4,2026-10-08-18-56-09 +0000,nyt,New to Anne Carson’s Books? Start Here.,https://www.nytimes.com/2026/10/08/books/revie...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2600/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
129     trump     56
59     school     33
253   chicago     27
255     board     24
299  district     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-10-08-18-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...,143
279,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...,140
54,2026-10-08-17-30-00 +0000,wapo,No new attack on Iran before the midterm elect...,https://www.washingtonpost.com/politics/2026/1...,136
266,2026-10-08-10-00-42 +0000,chitri,2026 Chicago school board races: District 4A,https://www.chicagotribune.com/2026/10/08/chic...,130
436,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,143,2026-10-08-18-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...
436,130,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
441,122,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
12,74,2026-10-08-18-38-59 +0000,nypost,Gavin Newsom weighs taking 563 inmates off dea...,https://nypost.com/2026/10/08/us-news/gavin-ne...
226,67,2026-10-08-11-47-52 +0000,nypost,Arizona congressional candidate alleges she wa...,https://nypost.com/2026/10/08/us-news/arizona-...
197,62,2026-10-08-13-55-12 +0000,nypost,"Oil prices jump 5%, pushing Treasury yields hi...",https://nypost.com/2026/10/08/business/oil-pri...
194,58,2026-10-08-14-04-14 +0000,cbc,"Ousted Venezuelan president Nicolás Maduro, wi...",https://www.cbc.ca/news/world/livestory/maduro...
151,51,2026-10-08-15-41-18 +0000,wapo,At least 30 dead in Russian bus strike as Mosc...,https://www.washingtonpost.com/world/2026/10/0...
169,49,2026-10-08-15-02-36 +0000,wapo,Search warrants against former prince Andrew w...,https://www.washingtonpost.com/world/2026/10/0...
297,46,2026-10-08-09-54-12 +0000,nypost,Spanish woman whose eviction sparked housing p...,https://nypost.com/2026/10/08/world-news/spani...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)