## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-20-20-00 +0000,wsj,He Spent Billions Reviving Downtown Detroit. N...,https://www.wsj.com/real-estate/he-spent-billi...
1,2026-08-05-20-19-19 +0000,nyt,U.S. Cuts Ties With Organ Donor Group After Re...,https://www.nytimes.com/2026/08/05/us/organ-do...
2,2026-08-05-20-17-56 +0000,nyt,El-Sayed’s Michigan Senate Primary Win Sets Up...,https://www.nytimes.com/2026/08/05/us/politics...
3,2026-08-05-20-16-37 +0000,nyt,El-Sayed Got a Big Win for the Left. Can It Wi...,https://www.nytimes.com/2026/08/05/upshot/demo...
4,2026-08-05-20-15-29 +0000,nypost,Google’s Jeff Dean — chief scientist for 27 ye...,https://nypost.com/2026/08/05/business/googles...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2328/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
17     michigan     42
73        trump     35
19      primary     31
18       senate     27
107  democratic     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
162,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...,210
191,2026-08-05-13-55-22 +0000,nyt,Abdul El-Sayed Wins Democratic Senate Primary ...,https://www.nytimes.com/2026/08/05/us/politics...,206
189,2026-08-05-13-57-05 +0000,nypost,Far-left Michigan Dem Abdul El-Sayed beats Rep...,https://nypost.com/2026/08/05/us-news/michigan...,203
132,2026-08-05-16-12-00 +0000,wsj,Progressive Abdul El-Sayed won the Michigan De...,https://www.wsj.com/politics/elections/michiga...,201
178,2026-08-05-14-15-00 +0000,wsj,Some things to know about progressive firebran...,https://www.wsj.com/politics/five-things-to-kn...,193

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
162,210,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...
313,101,2026-08-05-03-44-30 +0000,bbc,Trump says Iran will be 'hit very hard' if Hor...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
179,93,2026-08-05-14-15-00 +0000,wsj,Rep. Chuck Edwards said he wouldn’t seek re-el...,https://www.wsj.com/politics/elections/embattl...
418,85,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
161,71,2026-08-05-15-03-44 +0000,nypost,"Disney earnings boosted by ‘Toy Story 5’, them...",https://nypost.com/2026/08/05/business/disney-...
38,58,2026-08-05-19-14-31 +0000,chitri,No evidence? No problem. President Donald Trum...,https://www.chicagotribune.com/2026/08/05/trum...
422,54,2026-08-04-20-30-00 +0000,wsj,"What’s Next for Democrats? Join a real-time, ...",https://www.wsj.com/politics/elections/live-q-...
324,45,2026-08-05-02-28-13 +0000,nypost,GOP Rep. John James to face off against Democr...,https://nypost.com/2026/08/04/us-news/gop-rep-...
403,44,2026-08-04-21-20-40 +0000,nypost,Mamdani is nothing but hostile to NYC business...,https://nypost.com/2026/08/04/business/mamdani...
329,44,2026-08-05-01-38-53 +0000,wapo,Armed man arrested at Trump golf course near L...,https://www.washingtonpost.com/nation/2026/08/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)