## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-18-12-00-00 +0000,missionlocal,Chan and Chakrabarti’s fight for No. 2 could c...,https://missionlocal.org/2026/05/chan-chakraba...
1,2026-05-18-11-56-25 +0000,nyt,The Villain of This Year’s Commencement Speech...,https://www.nytimes.com/2026/05/18/business/de...
2,2026-05-18-11-55-38 +0000,nyt,Trump Warns Iran the ‘Clock Is Ticking’ as Ten...,https://www.nytimes.com/2026/05/18/world/middl...
3,2026-05-18-11-55-34 +0000,nyt,2 Americans Detained in Japan After Entering P...,https://www.nytimes.com/2026/05/18/world/asia/...
4,2026-05-18-11-55-16 +0000,nyt,Bodies of Four Italian Divers Found in Maldive...,https://www.nytimes.com/2026/05/18/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     30
14    iran     14
137    new     12
324    war     10
195  house      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
122,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...,83
218,2026-05-17-15-53-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,81
161,2026-05-17-20-50-38 +0000,nypost,Drone strikes UAE nuke plant as Trump warns Ir...,https://nypost.com/2026/05/17/world-news/drone...,80
180,2026-05-17-19-00-00 +0000,wsj,House Democratic leader Hakeem Jeffries has be...,https://www.wsj.com/politics/elections/the-tru...,80
15,2026-05-18-11-37-38 +0000,bbc,Global oil prices and bond yields rise after T...,https://www.bbc.com/news/articles/czx2ne2ryppo...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
122,83,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...
213,52,2026-05-17-16-01-00 +0000,wsj,Authorities play catch-up with suspicious wage...,https://www.wsj.com/politics/policy/washington...
228,52,2026-05-17-14-02-27 +0000,cbc,U.A.E. reports drone strike at nuclear power p...,https://www.cbc.ca/news/world/uae-drone-strike...
30,44,2026-05-18-10-46-34 +0000,bbc,At least six Americans exposed to Ebola during...,https://www.bbc.com/news/articles/cq6pz60p996o...
188,40,2026-05-17-18-20-28 +0000,nypost,Spencer Pratt says he’ll move family out of Lo...,https://nypost.com/2026/05/17/us-news/spencer-...
204,37,2026-05-17-17-26-51 +0000,nypost,World’s best divers in race against time to re...,https://nypost.com/2026/05/17/world-news/world...
15,31,2026-05-18-11-37-38 +0000,bbc,Global oil prices and bond yields rise after T...,https://www.bbc.com/news/articles/czx2ne2ryppo...
181,31,2026-05-17-18-45-00 +0000,wsj,Ukraine Increases Pressure on Russia With Bigg...,https://www.wsj.com/world/russia/ukraine-incre...
119,31,2026-05-18-02-43-49 +0000,nypost,American who was on doomed MV Hondius cruise r...,https://nypost.com/2026/05/17/us-news/american...
132,31,2026-05-18-00-49-25 +0000,bbc,Moment two fighter jets collide mid-air at US ...,https://www.bbc.com/news/videos/ce8pzkg7klgo?a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)