## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-15-12-53-37 +0000,nyt,Son of Norway’s Crown Princess Is Convicted of...,https://www.nytimes.com/2026/06/15/world/europ...
1,2026-06-15-12-51-36 +0000,nyt,Iran War Live Updates: U.S.-Iran Framework Bri...,https://www.nytimes.com/live/2026/06/15/world/...
2,2026-06-15-12-49-00 +0000,wsj,U.S. Natural Gas Futures Start Week Lower,https://www.wsj.com/finance/commodities-future...
3,2026-06-15-12-46-30 +0000,nyt,SpaceX’s Stock Rises Ahead of First Full Day o...,https://www.nytimes.com/2026/06/15/business/sp...
4,2026-06-15-12-46-00 +0000,wsj,Truist Financial Names Fiserv’s Michael Lyons ...,https://www.wsj.com/business/c-suite/truist-fi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6     iran     39
72   trump     34
37    deal     32
60   world     14
308    new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
188,2026-06-14-21-36-06 +0000,nypost,Trump announces US and Iran have reached peace...,https://nypost.com/2026/06/14/world-news/trump...,144
241,2026-06-14-15-05-43 +0000,nypost,Trump says Iran peace deal will be signed in n...,https://nypost.com/2026/06/14/us-news/trump-cr...,141
73,2026-06-15-10-10-09 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,141
12,2026-06-15-12-36-11 +0000,nyt,Oil Tumbles and Stocks Surge After Trump Annou...,https://www.nytimes.com/2026/06/14/business/oi...,125
174,2026-06-14-23-19-00 +0000,wsj,WSJ Politics Special Edition: Trump’s Iran Dea...,https://www.wsj.com/world/middle-east/wsj-poli...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
188,144,2026-06-14-21-36-06 +0000,nypost,Trump announces US and Iran have reached peace...,https://nypost.com/2026/06/14/world-news/trump...
194,57,2026-06-14-20-32-34 +0000,cbc,"Ahead of G7, Carney says no one country will c...",https://www.cbc.ca/news/politics/g7-carney-ire...
139,55,2026-06-15-03-28-00 +0000,wsj,President Trump hosted a cage match at the Whi...,https://www.wsj.com/politics/trump-white-house...
24,50,2026-06-15-12-15-46 +0000,nypost,Video shows helicopter in crash that killed Ol...,https://nypost.com/2026/06/15/world-news/video...
48,38,2026-06-15-11-12-33 +0000,nypost,Britain will ban under-16s from using social m...,https://nypost.com/2026/06/15/world-news/brita...
86,36,2026-06-15-09-52-21 +0000,cbc,"Russian attacks kill 11 across Ukraine, set ce...",https://www.cbc.ca/news/world/kyiv-cathedral-r...
111,33,2026-06-15-08-35-26 +0000,wsj,"Stock Market Today: Stock Futures Rally, Oil D...",https://www.wsj.com/livecoverage/stock-market-...
49,29,2026-06-15-11-09-03 +0000,bbc,Norwegian crown princess's son found guilty of...,https://www.bbc.com/news/articles/cly9d10l5p4o...
58,29,2026-06-15-10-58-23 +0000,bbc,"Olé, olé, olé, olé - What makes a memorable Wo...",https://www.bbc.com/news/articles/c5yz434v7nro...
248,29,2026-06-14-13-05-33 +0000,nypost,Bungee jumper plummets to her death as she’s t...,https://nypost.com/2026/06/14/world-news/bunge...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)