## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-01-16-13-57 +0000,nypost,Terrifying moment masked thugs ransack store i...,https://nypost.com/2026/09/01/us-news/masked-g...
1,2026-09-01-16-13-48 +0000,bbc,Germany says Russia behind Leipzig airport dro...,https://www.bbc.co.uk/news/articles/c5ylm3m67n...
2,2026-09-01-16-13-03 +0000,bbc,Trump says US position on Falklands 'one of ma...,https://www.bbc.co.uk/news/articles/cm2q1qgg54...
3,2026-09-01-16-12-46 +0000,nyt,How the Pentagon Is Getting Into the Venezuela...,https://www.nytimes.com/2026/08/31/us/politics...
4,2026-09-01-16-09-41 +0000,nyt,Whistle-Blower Says USPS Is Secretly Proceedin...,https://www.nytimes.com/2026/09/01/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2296/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
17        trump     42
314         new     21
10   california     20
203      murder     17
294        iran     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
429,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...,143
275,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...,114
245,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...,108
310,2026-08-31-22-23-00 +0000,wsj,Army Secretary Dan Driscoll has submitted his ...,https://www.wsj.com/politics/national-security...,107
357,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
429,143,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...
88,73,2026-09-01-13-32-03 +0000,wapo,17-year-old girl charged with murder in live-s...,https://www.washingtonpost.com/nation/2026/08/...
245,66,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...
383,64,2026-08-31-19-24-05 +0000,nypost,UAE says current state of Iran war is not ‘sus...,https://nypost.com/2026/08/31/world-news/iran-...
287,64,2026-08-31-23-33-00 +0000,wsj,Vice President JD Vance attacked Abdul El-Saye...,https://www.wsj.com/politics/elections/vance-t...
228,64,2026-09-01-04-43-45 +0000,nypost,Georgia mom missing after Nepal-Tibet floods l...,https://nypost.com/2026/09/01/world-news/georg...
357,62,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...
310,53,2026-08-31-22-23-00 +0000,wsj,Army Secretary Dan Driscoll has submitted his ...,https://www.wsj.com/politics/national-security...
295,51,2026-08-31-23-05-41 +0000,latimes,Flash flood in Grand Canyon left two dead. Ext...,https://www.latimes.com/california/story/2026-...
48,49,2026-09-01-14-59-00 +0000,wsj,Global Bond Yields Surge as Oil Prices Fuel In...,https://www.wsj.com/economy/global/global-bond...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)