## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-20-19-34-17 +0000,bbc,Makerfield by-election candidates announced,https://www.bbc.com/news/articles/cgrp1z8n4w2o...
1,2026-05-20-19-31-25 +0000,nyt,Cuba Says the Trump Administration Is Not Nego...,https://www.nytimes.com/2026/05/20/world/ameri...
2,2026-05-20-19-30-07 +0000,bbc,Austrian ex-intelligence officer found guilty ...,https://www.bbc.com/news/articles/cwy21541dz4o...
3,2026-05-20-19-30-00 +0000,startribune,"Borough is closing, but a new restaurant will ...",https://www.startribune.com/borough-closing-re...
4,2026-05-20-19-30-00 +0000,wsj,Raúl Castro Charged With Murder in U.S. Court,https://www.wsj.com/politics/policy/raul-castr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
5         trump     63
21          new     22
106        iran     17
662  republican     17
692     primary     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
329,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...,229
297,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...,173
298,2026-05-20-02-28-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,161
62,2026-05-20-17-51-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...,155
192,2026-05-20-13-17-42 +0000,nypost,"Vladimir Putin, Xi Jinping praise high-level t...",https://nypost.com/2026/05/20/world-news/putin...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
329,229,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...
285,86,2026-05-20-04-45-00 +0000,wsj,A Georgia congressman and a former college foo...,https://www.wsj.com/politics/elections/georgia...
297,78,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...
37,64,2026-05-20-18-28-00 +0000,wsj,Fed officials all but retired the question tha...,https://www.wsj.com/economy/central-banking/fe...
266,62,2026-05-20-08-54-44 +0000,cbc,"Xi calls for end to Middle East hostilities, s...",https://www.cbc.ca/news/world/putin-china-xi-j...
122,60,2026-05-20-16-09-00 +0000,wsj,"James Murdoch to Buy New York Magazine, Other ...",https://www.wsj.com/business/media/vox-media-s...
226,52,2026-05-20-10-48-00 +0000,wsj,EU negotiators reached a provisional deal to r...,https://www.wsj.com/economy/trade/eu-reaches-a...
36,50,2026-05-20-18-30-42 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
176,44,2026-05-20-13-52-32 +0000,nypost,WHO says risk of Ebola outbreak spreading glob...,https://nypost.com/2026/05/20/world-news/who-s...
177,37,2026-05-20-13-50-30 +0000,nypost,Stalker gets death sentence for ‘cold-blooded ...,https://nypost.com/2026/05/20/world-news/stalk...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)