## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-10-23-00 +0000,wsj,"U.S., Iran Exchange Fire, With Drone Attack Cl...",https://www.wsj.com/world/middle-east/u-s-iran...
1,2026-06-03-10-20-00 +0000,wsj,Zara Owner Shrugs Off Middle East Turmoil to P...,https://www.wsj.com/business/retail/inditex-sa...
2,2026-06-03-10-16-26 +0000,nyt,What to Know About South Korea’s Elections,https://www.nytimes.com/2026/06/02/world/asia/...
3,2026-06-03-10-13-42 +0000,bbc,US announces new tariffs over forced labour co...,https://www.bbc.com/news/articles/cq6pe7nvldmo...
4,2026-06-03-10-11-23 +0000,nyt,Oil Prices Rise as Iran and U.S. Exchange Strikes,https://www.nytimes.com/2026/06/03/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
32        trump     41
23          new     27
165  california     25
220        race     23
331    governor     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
168,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,144
257,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,126
82,2026-06-03-05-25-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...,123
29,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...,122
98,2026-06-03-04-26-53 +0000,nypost,Trump’s pick for Iowa governor Randy Feenstra ...,https://nypost.com/2026/06/03/us-news/trump-pi...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
168,144,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
29,122,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
90,75,2026-06-03-04-50-52 +0000,nyt,Zach Lahn Wins Republican Primary for Iowa Gov...,https://www.nytimes.com/2026/06/03/us/iowa-gov...
61,60,2026-06-03-07-39-32 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
95,58,2026-06-03-04-33-25 +0000,missionlocal,Lopsided early S.F. election results: Big lead...,https://missionlocal.org/2026/06/san-francisco...
13,53,2026-06-03-10-01-35 +0000,nyt,Iran War Live Updates: Kuwait Says Iranian Att...,https://www.nytimes.com/live/2026/06/03/world/...
137,49,2026-06-03-02-29-59 +0000,cbc,CBS News fires veteran journalist Scott Pelley...,https://www.cbc.ca/news/world/scott-pelley-fir...
165,42,2026-06-03-01-04-06 +0000,nypost,Rebecca Bennett wins Democratic primary for NJ...,https://nypost.com/2026/06/02/us-news/rebecca-...
67,41,2026-06-03-07-02-38 +0000,nyt,"Even if Oil Prices Peak Soon, the Global Econo...",https://www.nytimes.com/2026/06/03/business/ir...
220,39,2026-06-02-22-06-19 +0000,nypost,Biz group shells out $200K for NBA Finals ad r...,https://nypost.com/2026/06/02/business/biz-gro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)