## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-28-00-11-37 +0000,nypost,Pelosi’s heir apparent Scott Wiener breaks sil...,https://nypost.com/2026/06/27/us-news/pelosis-...
1,2026-06-28-00-09-59 +0000,nypost,Police search for two runaway NJ teenagers who...,https://nypost.com/2026/06/27/us-news/police-s...
2,2026-06-28-00-09-51 +0000,nypost,California city faces staggering $35M lawsuit ...,https://nypost.com/2026/06/27/us-news/stunning...
3,2026-06-28-00-02-29 +0000,nypost,News of the World: What you missed this week i...,https://nypost.com/2026/06/27/world-news/news-...
4,2026-06-28-00-01-23 +0000,nypost,Expect DEI to be a non-factor in the horse rac...,https://nypost.com/2026/06/27/business/expect-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2613/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
77     venezuela     23
65          iran     14
103        trump     13
94           new     10
388  earthquakes      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
51,2026-06-27-21-01-57 +0000,nypost,"Venezuela earthquake death toll tops 1,400 — w...",https://nypost.com/2026/06/27/world-news/venez...,55
187,2026-06-27-00-52-00 +0000,wsj,Venezuela’s Earthquakes Test Trump’s Bet on De...,https://www.wsj.com/world/americas/venezuelas-...,55
93,2026-06-27-15-00-48 +0000,nypost,Miracle baby born on street beside earthquake ...,https://nypost.com/2026/06/27/world-news/mirac...,54
12,2026-06-27-23-42-00 +0000,wsj,U.S. Carries Out New Strikes on Iran as Tit-fo...,https://www.wsj.com/world/middle-east/mideast-...,48
104,2026-06-27-13-53-33 +0000,nypost,Heartwarming video shows moment firefighters r...,https://nypost.com/2026/06/27/world-news/video...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
51,55,2026-06-27-21-01-57 +0000,nypost,"Venezuela earthquake death toll tops 1,400 — w...",https://nypost.com/2026/06/27/world-news/venez...
12,48,2026-06-27-23-42-00 +0000,wsj,U.S. Carries Out New Strikes on Iran as Tit-fo...,https://www.wsj.com/world/middle-east/mideast-...
39,44,2026-06-27-21-31-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...
40,34,2026-06-27-21-26-36 +0000,nypost,James Carville calls for formal Democratic par...,https://nypost.com/2026/06/27/media/james-carv...
185,34,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
166,30,2026-06-27-03-41-58 +0000,bbc,How Cape Verde stunned World Cup to set up Arg...,https://www.bbc.co.uk/sport/football/articles/...
34,28,2026-06-27-21-39-15 +0000,bbc,Burnham will need a Moscow test as well as Mak...,https://www.bbc.co.uk/news/articles/cdxdwr0xk5...
104,25,2026-06-27-13-53-33 +0000,nypost,Heartwarming video shows moment firefighters r...,https://nypost.com/2026/06/27/world-news/video...
37,23,2026-06-27-21-35-19 +0000,nypost,Lefty California teacher declares she married ...,https://nypost.com/2026/06/27/us-news/far-left...
163,23,2026-06-27-04-50-35 +0000,nypost,JD Vance tells Bill Maher how ‘America wins’ w...,https://nypost.com/2026/06/27/us-news/jd-vance...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)