## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-02-45-06 +0000,nyt,"Despite Problems, Boeing Sought Less Inspectio...",https://www.nytimes.com/2026/05/20/us/boeing-i...
1,2026-05-21-02-44-33 +0000,nypost,Muslim university in Texas ordered to shut dow...,https://nypost.com/2026/05/20/us-news/muslim-u...
2,2026-05-21-02-43-40 +0000,nyt,Colorado Governor Censured for Commuting Sente...,https://www.nytimes.com/2026/05/20/us/politics...
3,2026-05-21-02-37-31 +0000,nypost,Woman who inspired name for rock band Greta Va...,https://nypost.com/2026/05/20/us-news/woman-wh...
4,2026-05-21-02-35-28 +0000,nypost,Owner of San Diego’s ‘Trump House’ fighting fo...,https://nypost.com/2026/05/20/us-news/owner-of...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
39        trump     55
276         new     21
141        iran     15
285  california     15
115        cuba     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...,131
68,2026-05-20-23-26-30 +0000,nyt,Trump’s Government Moves to Spare an Unhappy T...,https://www.nytimes.com/2026/05/20/us/politics...,121
52,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,114
289,2026-05-20-13-17-42 +0000,nypost,"Vladimir Putin, Xi Jinping praise high-level t...",https://nypost.com/2026/05/20/world-news/putin...,109
229,2026-05-20-16-57-10 +0000,nypost,Trump says Netanyahu will do ‘whatever I want ...,https://nypost.com/2026/05/20/world-news/trump...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,131,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...
223,71,2026-05-20-17-11-00 +0000,wsj,The GOP-controlled House passed a new version ...,https://www.wsj.com/politics/policy/newly-pass...
363,59,2026-05-20-04-45-00 +0000,wsj,A Georgia congressman and a former college foo...,https://www.wsj.com/politics/elections/georgia...
52,59,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
314,56,2026-05-20-10-48-00 +0000,wsj,EU negotiators reached a provisional deal to r...,https://www.wsj.com/economy/trade/eu-reaches-a...
145,53,2026-05-20-20-18-32 +0000,nypost,Feds probe suspicious oil trades worth $800M m...,https://nypost.com/2026/05/20/business/feds-pr...
289,49,2026-05-20-13-17-42 +0000,nypost,"Vladimir Putin, Xi Jinping praise high-level t...",https://nypost.com/2026/05/20/world-news/putin...
159,41,2026-05-20-19-46-00 +0000,wsj,Federal Reserve officials all but retired the ...,https://www.wsj.com/economy/central-banking/fe...
56,41,2026-05-20-23-51-15 +0000,nypost,Seattle Mayor Katie Wilson walks back stinging...,https://nypost.com/2026/05/20/us-news/seattles...
78,40,2026-05-20-22-47-55 +0000,nypost,Elon Musk’s SpaceX readies for Wall Street bla...,https://nypost.com/2026/05/20/business/elon-mu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)