## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-02-15-04-30 +0000,nyt,Live Updates: Mideast Conflict Widens as U.S. ...,https://www.nytimes.com/live/2026/03/02/world/...
1,2026-03-02-15-04-01 +0000,nyt,"After Attack on Iran by the U.S. and Israel, S...",https://www.nytimes.com/2026/02/28/world/middl...
2,2026-03-02-15-02-42 +0000,nyt,America’s Billionaires Continue to Flock to Wy...,https://www.nytimes.com/2026/03/02/us/billiona...
3,2026-03-02-15-02-03 +0000,startribune,"Energy prices surge as tanker disruptions, fac...",https://www.startribune.com/oil-prices-surge-a...
4,2026-03-02-15-00-20 +0000,bbc,Limited flights leave UAE but disruption conti...,https://www.bbc.com/news/articles/c3v7ele1k4zo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
5      iran     87
140   trump     27
14   middle     22
15     east     22
48      war     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-03-02-13-08-28 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,244
182,2026-03-02-01-17-20 +0000,latimes,Thousands rally in Westwood as U.S.-Iran war e...,https://www.latimes.com/california/story/2026-...,207
239,2026-03-01-20-15-06 +0000,nyt,Middle East Airspace Closes as U.S.-Israeli St...,https://www.nytimes.com/2026/02/28/world/middl...,168
225,2026-03-01-20-59-43 +0000,bbc,UK troops and civilians in Middle East put at ...,https://www.bbc.com/news/articles/crrxkjxg1zpo...,167
163,2026-03-02-03-49-59 +0000,nyt,Iran Strikes U.S. Military Facilities in Dubai...,https://www.nytimes.com/2026/03/01/world/middl...,165

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,244,2026-03-02-13-08-28 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
141,93,2026-03-02-07-45-00 +0000,wsj,Middle East Conflict Sparks Surge in Oil Prices,https://www.wsj.com/world/middle-east/middle-e...
203,58,2026-03-01-22-24-27 +0000,bbc,Nine dead in missile attack on Israel as Iran ...,https://www.bbc.com/news/articles/c363zkp1pgxo...
104,53,2026-03-02-10-30-00 +0000,wsj,Berkshire’s New CEO Lays Out How He Will Pick ...,https://www.wsj.com/finance/berkshires-new-ceo...
71,52,2026-03-02-12-27-21 +0000,nypost,Huge fire as one of the world’s largest oil re...,https://nypost.com/2026/03/02/world-news/drone...
109,44,2026-03-02-10-30-00 +0000,wsj,The Texas Republican Senate primary is getting...,https://www.wsj.com/politics/elections/texas-p...
268,39,2026-03-01-17-28-50 +0000,nypost,Israelis and Iranians celebrate together in st...,https://nypost.com/2026/03/01/world-news/israe...
160,32,2026-03-02-04-50-36 +0000,nypost,Video shows self-driving Waymo car blocking em...,https://nypost.com/2026/03/01/us-news/video-sh...
24,31,2026-03-02-14-12-27 +0000,wapo,"U.S. troops killed amid Iranian counterattack,...",https://www.washingtonpost.com/national-securi...
195,31,2026-03-01-23-18-27 +0000,bbc,Watch: Retaliations continue on day two of US-...,https://www.bbc.com/news/videos/cvgk8vj56v1o?a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)