## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-03-43-43 +0000,nypost,Senate unanimously agrees to oppose pardon for...,https://nypost.com/2026/07/29/us-news/senate-u...
1,2026-07-30-03-33-19 +0000,nypost,Bombshell FBI raids target SoCal officials as ...,https://nypost.com/2026/07/29/us-news/fbi-raid...
2,2026-07-30-03-33-01 +0000,bbc,US launches 'heavy' strikes on Iran after atte...,https://www.bbc.co.uk/news/articles/c74gwdzywm...
3,2026-07-30-03-21-35 +0000,nypost,Hero 16-year-old lifeguard breaks silence on d...,https://nypost.com/2026/07/29/us-news/hero-16-...
4,2026-07-30-03-14-56 +0000,nyt,Sick of A.I.-Generated Content? The ‘Slop Jani...,https://www.nytimes.com/2026/07/29/business/de...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2673/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
176  trump     31
26    iran     25
185    new     23
196    fed     17
160  fauci     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
60,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,102
306,2026-07-29-12-46-38 +0000,nypost,Trump says US will ‘beat the f–king s–t’ out o...,https://nypost.com/2026/07/29/us-news/trump-sa...,101
175,2026-07-29-20-10-38 +0000,nypost,Trump and Netanyahu discussed ‘big three’ op...,https://nypost.com/2026/07/29/us-news/trump-an...,89
5,2026-07-30-03-13-48 +0000,nyt,Iran War Live Updates: U.S. Strikes Iran as Fi...,https://www.nytimes.com/live/2026/07/28/world/...,87
21,2026-07-30-02-28-38 +0000,nyt,"U.S. Strikes Iran Again, as Trump Encounters a...",https://www.nytimes.com/2026/07/29/us/trump-ir...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
60,102,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
322,82,2026-07-29-11-06-00 +0000,wsj,"New York City Mayor Zohran Mamdani, not even e...",https://www.wsj.com/politics/mamdani-digs-back...
26,77,2026-07-30-02-10-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...
152,73,2026-07-29-20-57-00 +0000,wsj,The Fed held interest rates steady on a 9-3 vo...,https://www.wsj.com/economy/central-banking/fe...
296,70,2026-07-29-13-01-38 +0000,nypost,Dr. Anthony Fauci repeatedly pleads the Fifth ...,https://nypost.com/2026/07/29/us-news/anthony-...
376,53,2026-07-29-07-20-21 +0000,nypost,Russia charges Telegram founder Pavel Durov wi...,https://nypost.com/2026/07/29/world-news/teleg...
226,41,2026-07-29-17-15-25 +0000,cbc,"Ottawa plans to end 'Netflix tax,' replace wit...",https://www.cbc.ca/news/politics/cancon-online...
305,40,2026-07-29-12-50-05 +0000,chitri,US military launches strikes on Iranian target...,https://www.chicagotribune.com/2026/07/29/iran...
196,37,2026-07-29-18-43-17 +0000,latimes,Viral California teen lifeguard rescue capture...,https://www.latimes.com/california/story/2026-...
106,35,2026-07-29-22-05-04 +0000,nypost,Hims & Hers sent users’ health data to social ...,https://nypost.com/2026/07/29/business/hims-he...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)