## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-07-03-00-00 +0000,wsj,A High-Stakes Gambit Clinched Paramount’s Warn...,https://www.wsj.com/business/media/paramount-w...
1,2026-10-07-02-58-32 +0000,nypost,"Wild video shows allegedly boozed-up driver, 6...",https://nypost.com/2026/10/06/us-news/wild-vid...
2,2026-10-07-02-58-30 +0000,bbc,Incredible or catastrophe? Jaguar unveils its ...,https://www.bbc.co.uk/news/articles/c6je50ydld...
3,2026-10-07-02-53-08 +0000,nypost,Pakistan provides financial aid to 9 million l...,https://nypost.com/2026/10/06/world-news/pakis...
4,2026-10-07-02-50-00 +0000,wsj,LG Electronics’ Preliminary Earnings Miss Stre...,https://www.wsj.com/business/earnings/lg-elect...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
85    trump     38
130     out     17
137     new     17
49    first     15
187  russia     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,123
348,2026-10-06-13-12-31 +0000,nypost,White House rips ‘media freakout’ over Trump s...,https://nypost.com/2026/10/06/us-news/gavin-ne...,101
270,2026-10-06-16-53-00 +0000,wsj,"Disney’s top lawyer, Horacio Gutiérrez, is tak...",https://www.wsj.com/business/media/disneys-top...,101
174,2026-10-06-20-15-31 +0000,bbc,White House defends Trump comment to let Iran ...,https://www.bbc.co.uk/news/articles/c6r7yn8pkn...,100
126,2026-10-06-21-14-28 +0000,latimes,Lopez: 'Take out' L.A. or San Diego? This buff...,https://www.latimes.com/california/story/2026-...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,123,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
49,82,2026-10-07-00-18-00 +0000,wsj,The civil lawsuit a young woman recently filed...,https://www.wsj.com/us-news/law/cornell-sexual...
21,70,2026-10-07-01-57-14 +0000,nypost,"Troy Jackson trashes voter ID policy, relies o...",https://nypost.com/2026/10/06/us-news/troy-jac...
72,69,2026-10-06-23-04-37 +0000,nypost,Russia accused of covering up plague outbreak ...,https://nypost.com/2026/10/06/world-news/russi...
348,63,2026-10-06-13-12-31 +0000,nypost,White House rips ‘media freakout’ over Trump s...,https://nypost.com/2026/10/06/us-news/gavin-ne...
297,63,2026-10-06-15-39-52 +0000,nypost,"Police fire tear gas as students, parents, tea...",https://nypost.com/2026/10/06/world-news/stude...
322,62,2026-10-06-14-32-26 +0000,latimes,"Paramount-Warner Bros. transaction closes, cre...",https://www.latimes.com/entertainment-arts/bus...
128,56,2026-10-06-21-12-30 +0000,nyt,S&P 500 Hits Record High Amid Rising Interest ...,https://www.nytimes.com/2026/10/06/business/st...
43,51,2026-10-07-00-35-35 +0000,nypost,Transgender Washington resident fueled trans e...,https://nypost.com/2026/10/06/us-news/transgen...
118,51,2026-10-06-21-29-32 +0000,missionlocal,‘We need a jingle’: Will voters know the ‘Yes-...,https://missionlocal.org/2026/10/california-bi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)