## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-10-22-09-59 +0000,nypost,Mamdani tries to downplay top official’s attem...,https://nypost.com/2026/07/10/us-news/mamdani-...
1,2026-07-10-22-09-42 +0000,nypost,Erika Kirk demands fast ruling on whether Tyle...,https://nypost.com/2026/07/10/us-news/erika-ki...
2,2026-07-10-22-09-30 +0000,nypost,"Parents who duct-taped adopted son, 4, face do...",https://nypost.com/2026/07/10/us-news/north-ca...
3,2026-07-10-22-09-07 +0000,bbc,What to know about 'explosive diarrhoea' paras...,https://www.bbc.co.uk/news/articles/c621m66qm7...
4,2026-07-10-22-06-37 +0000,nyt,"Overlooked No More: Garrincha, Brazil’s Brilli...",https://www.nytimes.com/2026/07/10/obituaries/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2681/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
69   trump     37
7     iran     20
132     up     16
303    ice     13
198    new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...,120
95,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...,108
198,2026-07-10-14-25-14 +0000,nypost,Trump tells The Post he’s ‘left instructions’ ...,https://nypost.com/2026/07/10/us-news/trump-te...,103
64,2026-07-10-20-27-02 +0000,nypost,Oil giants to gain ‘billions’ from Iran war — ...,https://nypost.com/2026/07/10/business/oil-gia...,94
181,2026-07-10-15-16-05 +0000,nyt,Trump Says Negotiations With Iran Will Continu...,https://www.nytimes.com/2026/07/10/us/politics...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,120,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...
198,66,2026-07-10-14-25-14 +0000,nypost,Trump tells The Post he’s ‘left instructions’ ...,https://nypost.com/2026/07/10/us-news/trump-te...
82,45,2026-07-10-19-37-19 +0000,nypost,DSA urging members to ice out Mamdani adviser ...,https://nypost.com/2026/07/10/us-news/dsa-urgi...
292,45,2026-07-10-08-22-11 +0000,wsj,Stock Market Today: SK Hynix Finishes Higher i...,https://www.wsj.com/livecoverage/stock-market-...
303,45,2026-07-10-05-38-35 +0000,nypost,NY mom Jamey Carney suffocated to death in Ire...,https://nypost.com/2026/07/10/world-news/ny-mo...
111,41,2026-07-10-18-05-52 +0000,nypost,Ex-Parliament member Ann Widdecombe murdered i...,https://nypost.com/2026/07/10/world-news/uk-po...
176,40,2026-07-10-15-27-46 +0000,nyt,Gaza Aid Worker on His Way to Watch World Cup ...,https://www.nytimes.com/2026/07/09/world/middl...
95,37,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...
1,36,2026-07-10-22-09-42 +0000,nypost,Erika Kirk demands fast ruling on whether Tyle...,https://nypost.com/2026/07/10/us-news/erika-ki...
332,35,2026-07-10-01-01-00 +0000,wsj,Here’s a guide to some of the socialists who c...,https://www.wsj.com/politics/elections/democra...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)