## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-16-11-13 +0000,nypost,LAPD officer’s life saved by bulletproof vest ...,https://nypost.com/2026/06/10/us-news/lapd-off...
1,2026-06-10-16-09-21 +0000,bbc,Trump and Iran trade new threats after strikes...,https://www.bbc.com/news/articles/ce371kw2ex2o...
2,2026-06-10-16-08-43 +0000,nyt,Iran War Live Updates: After U.S. and Iran Exc...,https://www.nytimes.com/live/2026/06/10/world/...
3,2026-06-10-16-08-08 +0000,nyt,What to know about the report.,https://www.nytimes.com/live/2026/06/10/busine...
4,2026-06-10-16-07-52 +0000,nyt,Dallas Judge Blocks City Council Vote on Futur...,https://www.nytimes.com/2026/06/09/us/dallas-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
11        trump     35
12         iran     24
95        maine     22
256  california     20
166       world     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-06-10-16-08-43 +0000,nyt,Iran War Live Updates: After U.S. and Iran Exc...,https://www.nytimes.com/live/2026/06/10/world/...,131
217,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,123
60,2026-06-10-14-47-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...,108
128,2026-06-10-11-17-09 +0000,bbc,Trump-backed candidate Steve Hilton advances i...,https://www.bbc.com/news/articles/c77yl1p0vvxo...,104
258,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,131,2026-06-10-16-08-43 +0000,nyt,Iran War Live Updates: After U.S. and Iran Exc...,https://www.nytimes.com/live/2026/06/10/world/...
217,123,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
138,85,2026-06-10-10-52-26 +0000,bbc,"Graham Platner wins Maine primary, setting up ...",https://www.bbc.com/news/articles/c79yzzvddnlo...
45,80,2026-06-10-15-13-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
107,70,2026-06-10-13-00-00 +0000,missionlocal,Where can you watch the World Cup in San Franc...,https://missionlocal.org/2026/06/san-francisco...
258,69,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
43,57,2026-06-10-15-15-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...
33,44,2026-06-10-15-28-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
60,40,2026-06-10-14-47-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...
239,35,2026-06-09-23-35-20 +0000,bbc,Sea drone rescues US army helicopter crew near...,https://www.bbc.com/news/articles/cwy0l44ex5wo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)