## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-21-10-00 +0000,nyt,U.S. Begins a Blockade of the Strait of Hormuz,https://www.nytimes.com/2026/04/13/world/middl...
1,2026-04-13-21-07-38 +0000,nypost,"Nearly 1,000 Hollywood stars issue brutal lett...",https://nypost.com/2026/04/13/us-news/hollywoo...
2,2026-04-13-21-05-51 +0000,nypost,Machete-wielding nut in NYC Grand Central atta...,https://nypost.com/2026/04/13/us-news/machete-...
3,2026-04-13-21-05-45 +0000,nyt,Iran War Live Updates: Trump and Iran Trade Th...,https://www.nytimes.com/live/2026/04/13/world/...
4,2026-04-13-21-05-34 +0000,nyt,Police Arrest Woman Accused of Stalking Lindse...,https://www.nytimes.com/2026/04/13/us/fleetwoo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
33     trump     52
29      iran     41
1   blockade     28
30       war     22
3     hormuz     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-04-13-21-05-45 +0000,nyt,Iran War Live Updates: Trump and Iran Trade Th...,https://www.nytimes.com/live/2026/04/13/world/...,204
111,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...,180
265,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,173
215,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,172
293,2026-04-13-01-36-13 +0000,nypost,"Trump blasts Pope Leo as ‘weak on crime,’ says...",https://nypost.com/2026/04/12/us-news/trump-bl...,167

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,204,2026-04-13-21-05-45 +0000,nyt,Iran War Live Updates: Trump and Iran Trade Th...,https://www.nytimes.com/live/2026/04/13/world/...
297,97,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
119,77,2026-04-13-17-05-41 +0000,nypost,Here’s how the US blockade of Strait of Hormuz...,https://nypost.com/2026/04/13/world-news/how-w...
222,69,2026-04-13-11-03-00 +0000,wsj,Two of the most recognizable people on the pla...,https://www.wsj.com/politics/the-showdown-betw...
44,53,2026-04-13-19-56-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
24,51,2026-04-13-20-39-58 +0000,nypost,Major oil group demands Dems rise up against G...,https://nypost.com/2026/04/13/us-news/oil-grou...
160,50,2026-04-13-15-30-02 +0000,cbc,EU president calls Hungary election a 'victory...,https://www.cbc.ca/news/world/hungary-magyar-w...
83,39,2026-04-13-18-55-29 +0000,cbc,Judge throws out Trump's $10B US lawsuit again...,https://www.cbc.ca/news/world/trump-lawsuit-di...
147,38,2026-04-13-16-06-41 +0000,nypost,"Trump posts, then deletes AI image of himself ...",https://nypost.com/2026/04/13/us-news/trump-po...
190,33,2026-04-13-13-38-44 +0000,cbc,Israel launches attack to seize Lebanon border...,https://www.cbc.ca/news/world/israel-lebanon-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)