## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-05-31-17 +0000,nyt,Hawaii Lt. Gov. Is Indicted in Corruption Inve...,https://www.nytimes.com/2026/07/25/us/hawaii-i...
1,2026-07-25-05-29-48 +0000,nypost,"Lou Koller, frontman for NY hardcore icons Sic...",https://nypost.com/2026/07/25/us-news/lou-koll...
2,2026-07-25-05-12-57 +0000,bbc,Trump pokes fun at press during White House Co...,https://www.bbc.co.uk/news/articles/cd7le4ylev...
3,2026-07-25-04-48-40 +0000,bbc,Saudi Arabia and Houthis exchange fire as US a...,https://www.bbc.co.uk/news/articles/cj9d27v70j...
4,2026-07-25-04-36-00 +0000,wsj,During a gala Friday celebrating press freedom...,https://www.wsj.com/politics/elections/five-ma...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2467/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
15     trump     53
177      new     31
194     iran     23
228      war     19
291  tariffs     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
242,2026-07-24-14-52-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,138
363,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,134
110,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,131
25,2026-07-25-01-58-53 +0000,nyt,Iran War Updates: Trump Meets With Cabinet Ove...,https://www.nytimes.com/live/2026/07/24/world/...,127
224,2026-07-24-15-39-28 +0000,chitri,President Trump addresses journalists at resch...,https://www.chicagotribune.com/2026/07/24/whit...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
242,138,2026-07-24-14-52-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...
39,108,2026-07-25-00-59-00 +0000,wsj,A Democratic Party panel selected South Caroli...,https://www.wsj.com/politics/elections/democra...
102,69,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
224,61,2026-07-24-15-39-28 +0000,chitri,President Trump addresses journalists at resch...,https://www.chicagotribune.com/2026/07/24/whit...
246,56,2026-07-24-14-45-22 +0000,bbc,"Dancing with Shakira at World Cup was 'very, v...",https://www.bbc.co.uk/news/articles/cly5j2gq58...
7,51,2026-07-25-04-14-07 +0000,nypost,"UWS stabbing suspect’s mom cries out in court,...",https://nypost.com/2026/07/25/us-news/nyc-uws-...
363,50,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
193,38,2026-07-24-17-30-54 +0000,nypost,"Miami dethrones NYC, Bay Area as America’s hot...",https://nypost.com/2026/07/24/business/miami-d...
72,38,2026-07-24-23-10-36 +0000,startribune,Live: Lynx stars take center stage as WNBA con...,https://www.startribune.com/minnesota-lynx-wnb...
261,37,2026-07-24-14-14-58 +0000,cbc,Canada celebrates long-awaited opening of Gord...,https://www.cbc.ca/news/canada/windsor/livesto...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)