## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-06-02-38-23 +0000,startribune,Takeaways: Home ice to open playoffs still in ...,https://www.startribune.com/takeaways-home-ice...
1,2026-04-06-02-24-23 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
2,2026-04-06-02-10-09 +0000,nypost,"Florida dad, 39, finally receives heart transp...",https://nypost.com/2026/04/05/us-news/florida-...
3,2026-04-06-02-01-00 +0000,wsj,Asian Currencies Likely Under Pressure on U.S....,https://www.wsj.com/finance/currencies/u-s-dol...
4,2026-04-06-01-56-49 +0000,nypost,Neal Schon and bandmate Jonathan Cain battle l...,https://nypost.com/2026/04/05/us-news/neal-sch...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
9      iran     34
13    trump     26
10      war     13
176  rescue     13
299  easter     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-06-02-24-23 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...,111
63,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...,111
130,2026-04-05-14-31-37 +0000,nypost,Trump heralds ‘Easter Miracle’ after daring re...,https://nypost.com/2026/04/05/us-news/trump-he...,108
95,2026-04-05-18-12-38 +0000,nypost,Trump gives Iran Tuesday evening deadline to o...,https://nypost.com/2026/04/05/us-news/trump-gi...,100
138,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,111,2026-04-06-02-24-23 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
137,49,2026-04-05-12-35-36 +0000,bbc,Pope Leo calls for global leaders to choose pe...,https://www.bbc.com/news/articles/crk1zgjj7y1o...
63,43,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...
135,39,2026-04-05-12-50-51 +0000,nypost,"How US used SEAL Team 6, a CIA ruse and death ...",https://nypost.com/2026/04/05/world-news/us-re...
156,35,2026-04-05-09-30-00 +0000,wsj,Central banks live in fear of their last mista...,https://www.wsj.com/economy/central-banking/pa...
5,30,2026-04-06-01-49-31 +0000,nypost,California’s fuel crisis hits terrifying new h...,https://nypost.com/2026/04/05/us-news/sky-high...
60,29,2026-04-05-21-30-14 +0000,nypost,Hollywood director’s son accused of lewd acts ...,https://nypost.com/2026/04/05/us-news/hollywoo...
39,27,2026-04-05-22-34-00 +0000,wsj,"For nearly two days, injured and alone, a U.S....",https://www.wsj.com/politics/national-security...
77,24,2026-04-05-20-18-50 +0000,nypost,GOP Senator John Kennedy claims modern Dems wo...,https://nypost.com/2026/04/05/us-news/gop-sena...
123,23,2026-04-05-15-33-59 +0000,nypost,Late-night shooting near the White House puts ...,https://nypost.com/2026/04/05/us-news/late-nig...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)