## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-06-01-20-47 +0000,bbc,From 'a beautiful night' to 'world's greatest ...,https://www.bbc.co.uk/news/articles/clyxxr9n2k...
1,2026-07-06-01-00-42 +0000,cbc,Trump targets Obamas again with doctored image...,https://www.cbc.ca/news/world/trump-barack-mic...
2,2026-07-06-01-00-00 +0000,wsj,‘There Is No Going Back’: The Inside Story of ...,https://www.wsj.com/world/europe/european-rupt...
3,2026-07-06-00-55-00 +0000,wsj,Genesis Minerals Makes Rival $3.9 Billion Bid ...,https://www.wsj.com/business/deals/genesis-min...
4,2026-07-06-00-52-33 +0000,nyt,How Trump Put Himself in the Middle of America...,https://www.nytimes.com/2026/07/05/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2630/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
10     trump     21
79      july     13
420     iran     12
391  funeral     12
35        th     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
50,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...,86
182,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,73
193,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...,70
151,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...,64
192,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
50,86,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...
182,73,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...
96,48,2026-07-05-17-52-11 +0000,latimes,"Woman killed, several injured in Fourth of Jul...",https://www.latimes.com/california/story/2026-...
193,43,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
151,37,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...
159,29,2026-07-05-10-00-00 +0000,latimes,"Barabak: Happy Birthday, America! You've weath...",https://www.latimes.com/politics/story/2026-07...
126,27,2026-07-05-14-37-30 +0000,nypost,Pa. Gov. Josh Shapiro slams socialist NY Dem D...,https://nypost.com/2026/07/05/us-news/pa-gov-j...
66,26,2026-07-05-20-07-25 +0000,nypost,Harrowing video captures moment inside seaplan...,https://nypost.com/2026/07/05/us-news/harrowin...
19,25,2026-07-06-00-00-00 +0000,wsj,"On the California Coast, a Picture-Perfect Cit...",https://www.wsj.com/business/hospitality/on-th...
130,24,2026-07-05-13-59-00 +0000,wsj,Germany before World War I provoked backlash b...,https://www.wsj.com/economy/trade/how-to-win-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)