## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-14-17-15-03 +0000,bbc,Row after Tory bid to make Burnham face MPs be...,https://www.bbc.co.uk/news/articles/cj6g61y6lp...
1,2026-07-14-17-13-27 +0000,bbc,Israeli strike on police post in north Gaza ki...,https://www.bbc.co.uk/news/articles/cqj1jqeyl5...
2,2026-07-14-17-09-22 +0000,nypost,ICE told to halt vehicle stops after 2 fatal s...,https://nypost.com/2026/07/14/us-news/ice-told...
3,2026-07-14-17-08-06 +0000,nypost,Stop eating salad? Lettuce may be to blame for...,https://nypost.com/2026/07/14/health/should-yo...
4,2026-07-14-17-08-06 +0000,startribune,ICE ordered to cease most vehicle stops after ...,https://www.startribune.com/ice-ordered-to-cea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
41    trump     37
108    iran     29
395  graham     17
103  hormuz     15
340     new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...,129
259,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...,116
138,2026-07-14-11-08-00 +0000,wsj,Will President Trump reimposing his “blockade”...,https://www.wsj.com/politics/for-whom-the-stra...,116
50,2026-07-14-16-06-00 +0000,wsj,The Battle for Hormuz: Trump Shifts Into Dange...,https://www.wsj.com/world/middle-east/the-batt...,108
237,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,129,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...
24,80,2026-07-14-16-40-54 +0000,nypost,"Iran claims attacks on Bahrain, Jordan, Strait...",https://nypost.com/2026/07/14/world-news/iran-...
49,73,2026-07-14-16-06-00 +0000,wsj,Chairman Kevin Warsh pledged to lawmakers that...,https://www.wsj.com/economy/central-banking/wa...
237,53,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...
200,49,2026-07-14-03-51-12 +0000,nyt,Paramount-Warner Bros. Merger Is Challenged in...,https://www.nytimes.com/2026/07/13/business/pa...
18,41,2026-07-14-16-45-54 +0000,bbc,ICE told to halt most vehicle stops after pair...,https://www.bbc.co.uk/news/articles/cly8yrw597...
259,41,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...
178,39,2026-07-14-09-00-00 +0000,wsj,New York Set to Temporarily Ban Large New Data...,https://www.wsj.com/us-news/new-york-set-to-te...
315,37,2026-07-13-19-08-37 +0000,latimes,Two men try to rob off-duty Long Beach police ...,https://www.latimes.com/california/story/2026-...
318,34,2026-07-13-18-53-43 +0000,nypost,Iran-backed Houthis fire missile at Saudi Arab...,https://nypost.com/2026/07/13/world-news/houth...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)