## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-25-01-16-27 +0000,nypost,Abdul El-Sayed asks Fox News’ Jesse Watters ‘A...,https://nypost.com/2026/08/24/us-news/abdul-el...
1,2026-08-25-01-13-32 +0000,nypost,Kids as young as 11 among the illegal vendors ...,https://nypost.com/2026/08/24/us-news/kids-as-...
2,2026-08-25-01-10-23 +0000,nyt,Trump’s Attempt to Strangle Iran’s Economy Dep...,https://www.nytimes.com/2026/08/24/us/politics...
3,2026-08-25-01-08-48 +0000,wapo,Trump’s trade ‘war’ with Canada has Carney fac...,https://www.washingtonpost.com/world/2026/08/2...
4,2026-08-25-01-06-18 +0000,bbc,Fast-moving wildfire forces thousands to evacu...,https://www.bbc.co.uk/news/articles/c4gqlp0yzy...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2489/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
27    trump     48
30     iran     26
195     new     24
37   canada     20
101    plan     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,143
163,2026-08-24-18-37-48 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,138
91,2026-08-24-21-38-04 +0000,latimes,Supreme Court for now allows Trump to plan new...,https://www.latimes.com/politics/story/2026-08...,129
61,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...,123
196,2026-08-24-16-50-00 +0000,wsj,The Trump administration is proposing a new si...,https://www.wsj.com/politics/policy/government...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,143,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
189,116,2026-08-24-17-27-14 +0000,nypost,Trump unleashes ‘Operation Economic Outcast’ a...,https://nypost.com/2026/08/24/world-news/trump...
32,64,2026-08-24-23-52-00 +0000,wsj,A super PAC aligned with President Trump is op...,https://www.wsj.com/politics/elections/trump-a...
91,57,2026-08-24-21-38-04 +0000,latimes,Supreme Court for now allows Trump to plan new...,https://www.latimes.com/politics/story/2026-08...
21,53,2026-08-25-00-09-33 +0000,nypost,911 call reveals moment dad who let daughter d...,https://nypost.com/2026/08/24/us-news/911-call...
81,45,2026-08-24-21-59-20 +0000,nypost,Dem NY mayor whizzes off to Martha’s Vineyard ...,https://nypost.com/2026/08/24/us-news/albany-m...
0,36,2026-08-25-01-16-27 +0000,nypost,Abdul El-Sayed asks Fox News’ Jesse Watters ‘A...,https://nypost.com/2026/08/24/us-news/abdul-el...
320,36,2026-08-24-08-58-03 +0000,cbc,"Fast-moving wildfire threatens Reno, Nevada, f...",https://www.cbc.ca/news/world/wildfire-nevada-...
102,36,2026-08-24-21-21-29 +0000,nypost,Canoodling Central Park lawyer getting forced ...,https://nypost.com/2026/08/24/business/wachtel...
74,35,2026-08-24-22-19-00 +0000,wsj,“He has a lot of room to kiss my ass”: The war...,https://www.wsj.com/politics/policy/he-has-a-l...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)