## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-28-14-55-41 +0000,nypost,AI porn star ‘twins’ chat with fans and make c...,https://nypost.com/2026/03/28/us-news/ai-porn-...
1,2026-03-28-14-55-08 +0000,nyt,Iran War Live Updates: Iran-Backed Houthis Ent...,https://www.nytimes.com/live/2026/03/28/world/...
2,2026-03-28-14-55-06 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/28/world/...
3,2026-03-28-14-53-53 +0000,nypost,Mamdani’s new deputy for community safety help...,https://nypost.com/2026/03/28/us-news/mamdanis...
4,2026-03-28-14-51-23 +0000,nypost,Stalker of ‘Bad Guy’ singer Billie Eilish kill...,https://nypost.com/2026/03/28/us-news/stalker-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2477/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
9     iran     38
10     war     37
120  trump     23
22     new     13
442   will     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-28-14-55-08 +0000,nyt,Iran War Live Updates: Iran-Backed Houthis Ent...,https://www.nytimes.com/live/2026/03/28/world/...,184
14,2026-03-28-14-08-48 +0000,wapo,Iran-backed Houthis in Yemen launch attack on ...,https://www.washingtonpost.com/world/2026/03/2...,121
13,2026-03-28-14-10-04 +0000,startribune,Iran-backed Houthis claim first missile launch...,https://www.startribune.com/israel-says-it-int...,119
55,2026-03-28-09-03-26 +0000,nyt,"In an Asymmetrical War, Iran Seeks an Edge Wit...",https://www.nytimes.com/2026/03/28/business/ir...,117
17,2026-03-28-13-46-25 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,184,2026-03-28-14-55-08 +0000,nyt,Iran War Live Updates: Iran-Backed Houthis Ent...,https://www.nytimes.com/live/2026/03/28/world/...
260,88,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...
258,43,2026-03-27-17-00-00 +0000,wsj,About a year into the full-blown trade war bet...,https://www.wsj.com/economy/trade/how-trumps-t...
99,40,2026-03-28-03-25-00 +0000,wsj,California Gov. Gavin Newsom signed an executi...,https://www.wsj.com/politics/policy/newsom-ban...
226,39,2026-03-27-18-33-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
230,37,2026-03-27-18-28-28 +0000,nypost,"Gang-rape victim Noelia Castillo, who died of ...",https://nypost.com/2026/03/27/world-news/gang-...
292,37,2026-03-27-15-18-40 +0000,nypost,Austria plans to ban social media use for unde...,https://nypost.com/2026/03/27/world-news/austr...
29,36,2026-03-28-12-45-00 +0000,nypost,‘Evil’ NYC kingpin who allegedly ran drug empi...,https://nypost.com/2026/03/28/us-news/crooked-...
21,33,2026-03-28-13-05-32 +0000,nypost,"JD Vance, Marco Rubio skipping CPAC as Ted Cru...",https://nypost.com/2026/03/28/us-news/republic...
98,32,2026-03-28-03-51-00 +0000,wsj,President Trump signed an executive order to p...,https://www.wsj.com/politics/policy/house-gop-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)