## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-16-58-56 +0000,nypost,Dem Amy Klobuchar gets brutal reality check af...,https://nypost.com/2026/08/22/us-news/amy-klob...
1,2026-08-22-16-57-21 +0000,nypost,Young mom killed in SoCal street racing crash ...,https://nypost.com/2026/08/22/us-news/young-mo...
2,2026-08-22-16-45-02 +0000,bbc,Carney calls Trump's fresh tariffs a 'miscalcu...,https://www.bbc.co.uk/news/articles/cx272np7vg...
3,2026-08-22-16-42-28 +0000,nyt,Police Chief in Mississippi Regularly Used Rac...,https://www.nytimes.com/2026/08/22/us/police-c...
4,2026-08-22-16-42-00 +0000,wsj,Canada Announces New Post-Labor Day Tariffs,https://www.wsj.com/world/asia/canada-announce...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2443/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
29    trump     39
47   canada     13
49      new     13
33    trade     12
31  tariffs     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...,113
256,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,112
213,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,111
103,2026-08-22-09-00-00 +0000,wsj,President Trump is quietly making plans for an...,https://www.wsj.com/politics/policy/trump-new-...,102
117,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,113,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...
117,96,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
138,50,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
5,45,2026-08-22-16-38-45 +0000,nypost,10 killed in Russian and Ukrainian attacks a d...,https://nypost.com/2026/08/22/world-news/10-ki...
93,44,2026-08-22-09-03-47 +0000,nyt,How a Progressive Democrat in Florida Gave Her...,https://www.nytimes.com/2026/08/22/us/politics...
202,36,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
172,36,2026-08-21-22-08-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
63,34,2026-08-22-12-30-00 +0000,nypost,Father-son duo at center of Penn State frat ho...,https://nypost.com/2026/08/22/us-news/father-s...
260,33,2026-08-21-18-22-00 +0000,nyt,"Prince Harry, Elton John and Others Told to Pa...",https://www.nytimes.com/2026/08/21/world/europ...
19,29,2026-08-22-16-00-00 +0000,wsj,"Ashley Hinson has never lost an election. Now,...",https://www.wsj.com/politics/elections/the-for...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)