## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-22-56-01 +0000,bbc,Keir Starmer's government discussed moving out...,https://www.bbc.co.uk/news/articles/cqd093gk1r...
1,2026-10-26-22-54-12 +0000,nyt,Bob Woodward Criticizes Jeff Bezos in New Memoir,https://www.nytimes.com/2026/10/26/us/politics...
2,2026-10-26-22-52-47 +0000,nypost,Jewish rights group calls on Trump admin to pr...,https://nypost.com/2026/10/26/us-news/jewish-r...
3,2026-10-26-22-52-27 +0000,nyt,Ohio State Professor Who Tackled a Filmmaker o...,https://www.nytimes.com/2026/10/26/us/ohio-sta...
4,2026-10-26-22-49-02 +0000,startribune,Trump administration attempting to prosecute f...,https://www.startribune.com/trump-administrati...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2366/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
19      trump     37
59   election     30
237      lula     22
243    brazil     18
13        new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
345,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva mobilized millions t...,https://www.chicagotribune.com/2026/10/25/braz...,149
319,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,123
83,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,117
177,2026-10-26-15-57-12 +0000,nypost,"Brazil markets, currency reel from leftist Lui...",https://nypost.com/2026/10/26/business/brazil-...,99
253,2026-10-26-11-06-00 +0000,wsj,The Morning Risk Report: Lula Wins Fourth Term...,https://www.wsj.com/risk-compliance-journal/th...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
345,149,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva mobilized millions t...,https://www.chicagotribune.com/2026/10/25/braz...
164,67,2026-10-26-16-51-12 +0000,nypost,Pro-Abdul El-Sayed ad sparks fury with false c...,https://nypost.com/2026/10/26/us-news/pro-abdu...
254,62,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
26,55,2026-10-26-21-53-41 +0000,nypost,Ex-FBI Director James Comey facing new crimina...,https://nypost.com/2026/10/26/us-news/ex-fbi-d...
230,53,2026-10-26-13-26-07 +0000,chitri,Anthropic files for potentially the biggest IP...,https://www.chicagotribune.com/2026/10/26/anth...
326,48,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
330,45,2026-10-26-01-00-00 +0000,wsj,California’s proposed billionaire tax sparked ...,https://www.wsj.com/politics/california-billio...
217,42,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...
136,39,2026-10-26-18-28-40 +0000,nypost,"Yankees World Series champion Mark Teixeira, n...",https://nypost.com/2026/10/26/us-news/yankees-...
10,37,2026-10-26-22-37-54 +0000,cbc,First Nations-first ministers' meeting brings ...,https://www.cbc.ca/news/indigenous/first-natio...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)