## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-30-16-11-19 +0000,nyt,Lawsuit Accuses Americans of Political Killing...,https://www.nytimes.com/2026/03/30/world/middl...
1,2026-03-30-16-05-58 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...
2,2026-03-30-16-05-37 +0000,nyt,Texas Border Wall Plan in Big Bend Draws Oppos...,https://www.nytimes.com/2026/03/30/us/a-border...
3,2026-03-30-16-05-00 +0000,bbc,Welsh Labour manifesto explained in under 60 s...,https://www.bbc.com/news/videos/c0mj9pdw4pno?a...
4,2026-03-30-16-04-37 +0000,nypost,NYC sues ride hailing app Empower for operatin...,https://nypost.com/2026/03/30/business/nyc-sue...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
11   trump     36
7     iran     30
8      war     20
222    oil     17
156    new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-30-16-05-58 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...,125
48,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...,124
189,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...,107
160,2026-03-30-08-33-12 +0000,nypost,Trump says he could ‘take the oil in Iran’ as ...,https://nypost.com/2026/03/30/world-news/trump...,104
243,2026-03-29-18-00-56 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,125,2026-03-30-16-05-58 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...
48,58,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...
102,43,2026-03-30-12-30-58 +0000,cbc,Air Canada CEO Michael Rousseau to retire late...,https://www.cbc.ca/news/business/air-canada-ce...
189,41,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...
167,36,2026-03-30-05-38-26 +0000,bbc,Fuel tax halved and free public transport offe...,https://www.bbc.com/news/articles/c937n0yxggeo...
29,34,2026-03-30-15-34-02 +0000,nypost,"Thieves snatch $10M worth of Renoir, Cézanne a...",https://nypost.com/2026/03/30/world-news/thiev...
157,33,2026-03-30-08-58-42 +0000,nypost,US allows Russian oil tanker to reach Cuba ami...,https://nypost.com/2026/03/30/world-news/us-al...
79,31,2026-03-30-13-30-32 +0000,bbc,Latin Patriarch will have access to Jerusalem ...,https://www.bbc.com/news/articles/cvg0128z41eo...
37,29,2026-03-30-15-15-36 +0000,nyt,Analysis shows where a new U.S. missile hit an...,https://www.nytimes.com/live/2026/world/us-isr...
13,27,2026-03-30-15-51-00 +0000,wsj,Fed Chair Jerome Powell said the central bank ...,https://www.wsj.com/economy/central-banking/po...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)