## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-17-19-13-09 +0000,nyt,Iran War Live Updates: ‘Open’ Strait Renews Ho...,https://www.nytimes.com/live/2026/04/17/world/...
1,2026-04-17-19-12-12 +0000,nyt,Federal Appeals Court Opens Door to Moving Tra...,https://www.nytimes.com/2026/04/17/us/politics...
2,2026-04-17-19-11-16 +0000,bbc,Ontario Premier Doug Ford criticised for $21m ...,https://www.bbc.com/news/articles/cvg354r158go...
3,2026-04-17-19-10-41 +0000,nypost,California political insiders ‘should feel dir...,https://nypost.com/2026/04/17/us-news/californ...
4,2026-04-17-19-10-12 +0000,nyt,"Optimism Rises for Iran Talks, but Hard Work A...",https://www.nytimes.com/2026/04/17/us/strait-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20     trump     41
0       iran     39
1        war     19
227      new     17
92   lebanon     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
35,2026-04-17-18-30-02 +0000,startribune,"Iran reopens Strait of Hormuz, but Trump says ...",https://www.startribune.com/a-10-day-ceasefire...,130
97,2026-04-17-15-59-42 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,124
241,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,123
232,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...,122
357,2026-04-16-19-34-42 +0000,nyt,House Again Thwarts Challenge to Trump’s Autho...,https://www.nytimes.com/2026/04/16/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
35,130,2026-04-17-18-30-02 +0000,startribune,"Iran reopens Strait of Hormuz, but Trump says ...",https://www.startribune.com/a-10-day-ceasefire...
232,81,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...
243,74,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
324,62,2026-04-16-21-10-00 +0000,wsj,"Nearly two months into the Iran war, Republica...",https://www.wsj.com/politics/gop-anxiety-iran-...
128,51,2026-04-17-14-54-56 +0000,nyt,New York New Jersey Stadium? Why MetLife Is Ch...,https://www.nytimes.com/2026/04/17/nyregion/fi...
336,47,2026-04-16-20-48-00 +0000,wsj,President Trump says he will nominate Dr. Eric...,https://www.wsj.com/politics/policy/trump-says...
34,45,2026-04-17-18-32-21 +0000,bbc,Oil prices plunge as Iran says Strait of Hormu...,https://www.bbc.com/news/articles/ckg045z73z1o...
188,42,2026-04-17-10-46-15 +0000,nypost,UK PM Keir Starmer under pressure to quit over...,https://nypost.com/2026/04/17/world-news/uk-pm...
315,38,2026-04-16-21-33-01 +0000,nypost,JD Vance AI memes flood Pakistan after his vis...,https://nypost.com/2026/04/16/us-news/jd-vance...
200,38,2026-04-17-10-00-00 +0000,latimes,Powerful California institutions backed Swalwe...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)