## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-04-10-45-50 +0000,nyt,Houthis Claim Attack on Aramco as Yemen Confli...,https://www.nytimes.com/2026/10/04/world/middl...
1,2026-10-04-10-14-45 +0000,bbc,"Badenoch unveils plan to end £100,000 childcar...",https://www.bbc.co.uk/news/articles/cmn06l362y...
2,2026-10-04-10-11-32 +0000,bbc,Kyiv bridge hit in further Russian drone attac...,https://www.bbc.co.uk/news/articles/ckreyjzzzy...
3,2026-10-04-10-00-38 +0000,chitri,"Illinois Senate race: Republican Don Tracy, a ...",https://www.chicagotribune.com/2026/10/04/illi...
4,2026-10-04-10-00-20 +0000,chitri,"The office is back, but some Chicagoans have a...",https://www.chicagotribune.com/2026/10/04/chic...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2395/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
54      trump     20
152  flydubai     16
86        new     13
334     pilot     11
251       off     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
207,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...,80
187,2026-10-03-14-52-27 +0000,nyt,FlyDubai Co-Pilot Used Crash Ax in ‘Terrorist’...,https://www.nytimes.com/2026/10/03/world/middl...,65
113,2026-10-03-22-59-27 +0000,wapo,FlyDubai co-pilot used crash ax to attempt ter...,https://www.washingtonpost.com/world/2026/10/0...,59
168,2026-10-03-16-50-36 +0000,nypost,Trump gushes over blue-collar flydubai hero wh...,https://nypost.com/2026/10/03/us-news/trump-gu...,56
70,2026-10-04-03-15-01 +0000,nypost,Longtime aviation pal of stabbed flydubai pilo...,https://nypost.com/2026/10/03/world-news/longt...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
207,80,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...
122,53,2026-10-03-22-18-41 +0000,chitri,Pres. Donald Trump rallies in Ohio to boost Jo...,https://www.chicagotribune.com/2026/10/03/trum...
138,53,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...
176,46,2026-10-03-16-20-59 +0000,cbc,Tennessee prisons chief to resign after failed...,https://www.cbc.ca/news/world/tennessee-prison...
83,40,2026-10-04-01-35-10 +0000,nypost,Debris from vanished Boston-bound plane found ...,https://nypost.com/2026/10/03/world-news/debri...
110,34,2026-10-03-23-20-56 +0000,nypost,"Cornell knew of drug arrest, overdose at Chi P...",https://nypost.com/2026/10/03/us-news/cornell-...
76,33,2026-10-04-02-14-00 +0000,wsj,A new White House task force will have 120 day...,https://www.wsj.com/tech/ai/new-ai-task-force-...
120,31,2026-10-03-22-25-01 +0000,nypost,"Streetwear giant Supreme — beloved by Bieber, ...",https://nypost.com/2026/10/03/us-news/trendy-s...
82,30,2026-10-04-01-49-51 +0000,nypost,4 teens arrested in fatal shooting of Nashvill...,https://nypost.com/2026/10/03/us-news/4-teens-...
55,28,2026-10-04-05-59-45 +0000,nypost,North Carolina woman speaks out as NASCAR driv...,https://nypost.com/2026/10/04/us-news/north-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)