## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-23-03-25 +0000,nyt,Iran War Live Updates: 2 U.S. Soldiers Killed ...,https://www.nytimes.com/live/2026/07/18/world/...
1,2026-07-18-23-03-24 +0000,nyt,Why Jordan Is Becoming a New Focus in the U.S....,https://www.nytimes.com/2026/07/18/world/middl...
2,2026-07-18-23-03-10 +0000,nypost,Wild videos show hotel employee attacking gues...,https://nypost.com/2026/07/18/world-news/wild-...
3,2026-07-18-22-59-31 +0000,nypost,Body found at home owned by ‘Squad’ Rep. Ayann...,https://nypost.com/2026/07/18/us-news/body-fou...
4,2026-07-18-22-57-00 +0000,wapo,U.S. strikes Iran after 2 service members kill...,https://www.washingtonpost.com/world/2026/07/1...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2675/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
88    trump     19
0      iran     14
68    world     13
13      new     12
36  strikes      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
171,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...,71
53,2026-07-18-17-29-50 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...,63
0,2026-07-18-23-03-25 +0000,nyt,Iran War Live Updates: 2 U.S. Soldiers Killed ...,https://www.nytimes.com/live/2026/07/18/world/...,61
4,2026-07-18-22-57-00 +0000,wapo,U.S. strikes Iran after 2 service members kill...,https://www.washingtonpost.com/world/2026/07/1...,59
28,2026-07-18-20-22-23 +0000,nypost,New Iranian billboard threatens Trump is ‘next...,https://nypost.com/2026/07/18/world-news/new-i...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
171,71,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...
0,61,2026-07-18-23-03-25 +0000,nyt,Iran War Live Updates: 2 U.S. Soldiers Killed ...,https://www.nytimes.com/live/2026/07/18/world/...
40,47,2026-07-18-19-04-16 +0000,nypost,World’s most livable city tops global list sec...,https://nypost.com/2026/07/18/world-news/world...
53,44,2026-07-18-17-29-50 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...
123,35,2026-07-18-10-00-00 +0000,latimes,West Hollywood faces long recovery from massiv...,https://www.latimes.com/california/story/2026-...
89,28,2026-07-18-13-08-17 +0000,nypost,Eight killed after Ukraine launches wave of dr...,https://nypost.com/2026/07/18/world-news/eight...
47,25,2026-07-18-18-19-08 +0000,nyt,These AIPAC-Backed Democrats Voted to Nix Isra...,https://www.nytimes.com/2026/07/18/us/politics...
143,25,2026-07-18-07-20-20 +0000,nypost,DSA member says she has no problem supporting ...,https://nypost.com/2026/07/18/us-news/dsa-memb...
125,24,2026-07-18-09-30-00 +0000,wsj,The popularity of prediction markets such as P...,https://www.wsj.com/politics/policy/dc-governm...
167,24,2026-07-18-01-32-17 +0000,nypost,Olive Garden becomes unlikely face of voter ID...,https://nypost.com/2026/07/17/us-news/olive-ga...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)