## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-13-21-11-08 +0000,bbc,Burnham cements Labour leadership with backing...,https://www.bbc.co.uk/news/articles/c05y3rj09q...
1,2026-07-13-21-09-54 +0000,nypost,Lifeline for Venice Beach as World Cup transfo...,https://nypost.com/2026/07/13/us-news/world-cu...
2,2026-07-13-21-09-00 +0000,wsj,Opinion | Schumer’s Tragedy—and Ours,https://www.wsj.com/opinion/schumers-tragedyan...
3,2026-07-13-21-08-04 +0000,nyt,Live Updates: U.S. to Resume Shipping Blockade...,https://www.nytimes.com/live/2026/07/13/world/...
4,2026-07-13-21-07-20 +0000,nyt,Democratic Senate Candidate in South Carolina ...,https://www.nytimes.com/2026/07/13/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
37    graham     35
25     trump     33
36   lindsey     31
24      iran     28
266    death     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
41,2026-07-13-20-26-00 +0000,wsj,President Trump is pushing Darline Graham Nord...,https://www.wsj.com/politics/elections/lindsey...,211
231,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...,167
169,2026-07-13-15-12-21 +0000,nypost,Sen. Lindsey Graham’s sister Darline reacts to...,https://nypost.com/2026/07/13/us-news/lindsey-...,155
187,2026-07-13-13-10-11 +0000,nypost,Trump reveals Lindsey Graham’s ‘one bad moment...,https://nypost.com/2026/07/13/us-news/trump-re...,142
65,2026-07-13-19-42-52 +0000,nypost,Sen. John Thune chokes up over death of Lindse...,https://nypost.com/2026/07/13/us-news/senate-g...,133

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
41,211,2026-07-13-20-26-00 +0000,wsj,President Trump is pushing Darline Graham Nord...,https://www.wsj.com/politics/elections/lindsey...
154,75,2026-07-13-16-10-10 +0000,nypost,California’s war on Paramount ramps up as stat...,https://nypost.com/2026/07/13/business/califor...
231,69,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...
167,69,2026-07-13-15-16-09 +0000,bbc,US and Iran trade fire as tensions rise over S...,https://www.bbc.co.uk/news/articles/cevlr112pm...
42,54,2026-07-13-20-24-33 +0000,nyt,"Sam Neill, New Zealand Actor Known for ‘Jurass...",https://www.nytimes.com/2026/07/13/movies/sam-...
79,41,2026-07-13-19-08-37 +0000,latimes,Two men try to rob off-duty Long Beach police ...,https://www.latimes.com/california/story/2026-...
163,41,2026-07-13-15-45-32 +0000,nypost,Suspect in murder of NY mom Jamey Carney had m...,https://nypost.com/2026/07/13/world-news/suspe...
83,36,2026-07-13-19-02-37 +0000,nypost,Latest NYC Legionnaires’ disease outbreak rise...,https://nypost.com/2026/07/13/us-news/latest-n...
281,33,2026-07-13-00-49-28 +0000,nypost,27 dead and dozens injured after massive blaze...,https://nypost.com/2026/07/12/world-news/27-de...
255,33,2026-07-13-07-22-43 +0000,wsj,"Stock Market Today: Oil Jumps, While AI Jitter...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)