## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-18-17-35 +0000,nypost,Hubby turned in cheating Nashville cop wife af...,https://nypost.com/2026/07/21/us-news/hubby-tu...
1,2026-07-21-18-15-22 +0000,nypost,Trump says Israel has begun withdrawing from L...,https://nypost.com/2026/07/21/world-news/trump...
2,2026-07-21-18-13-44 +0000,nyt,Houthis in Yemen Edge Closer to Entering U.S.-...,https://www.nytimes.com/2026/07/21/world/middl...
3,2026-07-21-18-12-57 +0000,nyt,Pentagon Identifies Soldier Killed in Iran War...,https://www.nytimes.com/2026/07/21/us/pentagon...
4,2026-07-21-18-12-12 +0000,nypost,Gruesome photos of Celeste Rivas’ decapitated ...,https://nypost.com/2026/07/21/us-news/gruesome...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2566/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
14     trump     44
196      new     39
27      iran     32
287  burnham     22
20      will     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
193,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...,127
386,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...,123
356,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,118
58,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,113
114,2026-07-21-15-40-27 +0000,nypost,"US, Mexico resume USMCA trade talks as Trump s...",https://nypost.com/2026/07/21/world-news/us-me...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
193,127,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...
58,113,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
356,74,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
285,61,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
408,50,2026-07-20-18-59-07 +0000,nypost,California gas suffers another huge setback as...,https://nypost.com/2026/07/20/us-news/californ...
47,41,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
386,40,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...
81,38,2026-07-21-16-30-00 +0000,missionlocal,After a family was killed at a West Portal bus...,https://missionlocal.org/2026/07/san-francisco...
231,38,2026-07-21-10-00-39 +0000,chitri,Illinois SNAP costs: State wins one-year delay...,https://www.chicagotribune.com/2026/07/21/snap...
296,36,2026-07-21-01-31-29 +0000,wapo,Nearly 100 U.S. troops injured in last two wee...,https://www.washingtonpost.com/world/2026/07/2...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)