## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-21-13-00 +0000,wsj,SAP Second-Quarter Revenue Up on Cloud Busines...,https://www.wsj.com/business/earnings/sap-seco...
1,2026-07-23-21-12-55 +0000,nypost,Wisconsin anti-cop protesters flash sign threa...,https://nypost.com/2026/07/23/us-news/wisconsi...
2,2026-07-23-21-12-41 +0000,nypost,GOP Rep. Mike Lawler leads Dem challenger Cait...,https://nypost.com/2026/07/23/us-news/gop-rep-...
3,2026-07-23-21-12-36 +0000,startribune,"Twins salvage end of road trip, outlast Guardi...",https://www.startribune.com/minnesota-twins-be...
4,2026-07-23-21-08-32 +0000,nyt,Bear Dies After Getting Stranded Atop Electric...,https://www.nytimes.com/2026/07/23/us/new-mexi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2447/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
146    trump     47
51       new     28
430    saudi     23
92      iran     23
508  nuclear     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...,153
91,2026-07-23-19-04-00 +0000,wapo,Saudi nuclear deal in doubt as Trump adds new ...,https://www.washingtonpost.com/politics/2026/0...,152
98,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...,150
231,2026-07-23-12-23-41 +0000,nypost,Trump says Saudi Arabia nuclear deal ‘totally ...,https://nypost.com/2026/07/23/us-news/trump-sa...,140
302,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,153,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...
91,82,2026-07-23-19-04-00 +0000,wapo,Saudi nuclear deal in doubt as Trump adds new ...,https://www.washingtonpost.com/politics/2026/0...
152,71,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
134,64,2026-07-23-16-51-00 +0000,wsj,A Democratic-backed measure to rein in Preside...,https://www.wsj.com/politics/gop-lawmakers-bac...
380,62,2026-07-22-21-55-29 +0000,nypost,Tesla profit disappoints as Elon Musk’s AI spe...,https://nypost.com/2026/07/22/business/tesla-p...
166,55,2026-07-23-15-20-03 +0000,nypost,Brent crude oil surges to $100 a barrel for fi...,https://nypost.com/2026/07/23/business/brent-c...
327,52,2026-07-23-02-45-00 +0000,wsj,Mayor Zohran Mamdani’s appointment of Lina Kha...,https://www.wsj.com/politics/policy/can-lina-k...
353,49,2026-07-22-23-55-25 +0000,latimes,D4vd's garage had signs of blood where girl's ...,https://www.latimes.com/california/story/2026-...
1,46,2026-07-23-21-12-55 +0000,nypost,Wisconsin anti-cop protesters flash sign threa...,https://nypost.com/2026/07/23/us-news/wisconsi...
292,43,2026-07-23-08-10-32 +0000,wsj,Stock Market Today: Oil Prices Hit $100 a Barr...,https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)