## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-11-00-00 +0000,nypost,School principal’s American dream fulfilled: b...,https://nypost.com/2026/06/07/us-news/daughter...
1,2026-06-07-11-00-00 +0000,nypost,Son of Nigerian immigrants credits parents for...,https://nypost.com/2026/06/07/us-news/the-amer...
2,2026-06-07-11-00-00 +0000,wsj,How David Grutman Became the King of the Vibes...,https://www.wsj.com/business/liv-nightclub-dav...
3,2026-06-07-10-56-00 +0000,wsj,Telecom Companies to Buy Patrick Drahi’s SFR f...,https://www.wsj.com/business/telecom/telecom-c...
4,2026-06-07-10-50-04 +0000,bbc,Lammy says he told JD Vance his Nowak comments...,https://www.bbc.com/news/articles/cjwg387040wo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
197   world     14
162   trump     13
198     cup     11
365  killed      8
55     pope      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
76,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...,65
160,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...,56
60,2026-06-07-01-16-24 +0000,nypost,Here are the best NYC bars to watch the ‘beaut...,https://nypost.com/2026/06/06/us-news/the-best...,48
118,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,45
155,2026-06-06-12-27-17 +0000,cbc,"Palestinian baby killed, parents hurt in Israe...",https://www.cbc.ca/news/world/israeli-palestin...,42

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
76,65,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
160,50,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...
155,35,2026-06-06-12-27-17 +0000,cbc,"Palestinian baby killed, parents hurt in Israe...",https://www.cbc.ca/news/world/israeli-palestin...
34,30,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
42,25,2026-06-07-05-09-14 +0000,nypost,Long Island’s Robert Moses State Park ramping ...,https://nypost.com/2026/06/07/us-news/long-isl...
8,24,2026-06-07-10-00-01 +0000,wapo,A wounded Lebanese journalist died as rescuers...,https://www.washingtonpost.com/business/2026/0...
145,24,2026-06-06-13-56-04 +0000,nypost,Ukraine drone attack targets St. Petersburg ag...,https://nypost.com/2026/06/06/world-news/ukrai...
125,22,2026-06-06-17-13-25 +0000,nypost,Steve Hilton roasts Xavier Becerra with sitcom...,https://nypost.com/2026/06/06/us-news/steve-hi...
50,22,2026-06-07-02-52-23 +0000,nypost,Family of killer California mom who slaughtere...,https://nypost.com/2026/06/06/us-news/family-o...
82,21,2026-06-06-23-38-51 +0000,nyt,"Bernadette Chirac, Formidable Ex-First Lady of...",https://www.nytimes.com/2026/06/06/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)