## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-16-14-14-19 +0000,bbc,Freight train and bus crash kills at least eig...,https://www.bbc.com/news/articles/c98rez3x0nwo...
1,2026-05-16-14-09-21 +0000,nyt,Man Stole Medieval Skull From Church and Seale...,https://www.nytimes.com/2026/05/16/world/europ...
2,2026-05-16-14-00-00 +0000,nypost,LA’s $30 minimum wage pushes hotel owners to b...,https://nypost.com/2026/05/16/us-news/la-hotel...
3,2026-05-16-13-55-14 +0000,bbc,Toddlers among more than 50 schoolchildren kid...,https://www.bbc.com/news/articles/c202vrxlwqgo...
4,2026-05-16-13-53-59 +0000,nyt,How a Nature Cruise Turned Into a Nightmare,https://www.nytimes.com/2026/05/16/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2497/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
40    trump     37
34    china     20
129     new     18
98   killed     16
521    iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
197,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,95
77,2026-05-16-08-44-47 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...,87
86,2026-05-16-05-53-41 +0000,bbc,Trump warns Taiwan against declaring independe...,https://www.bbc.com/news/articles/ce8p61v7l68o...,86
125,2026-05-15-23-27-15 +0000,nypost,Trump: Xi ‘surprised’ by America’s AI advances...,https://nypost.com/2026/05/15/us-news/trump-xi...,85
278,2026-05-15-16-05-17 +0000,nypost,Trump says he’ll decide on Taiwan arms sale so...,https://nypost.com/2026/05/15/us-news/trump-cl...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
197,95,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
159,61,2026-05-15-21-29-00 +0000,wsj,Elon Musk’s SpaceX aims to go public on June 1...,https://www.wsj.com/economy/central-banking/sp...
108,57,2026-05-16-00-48-06 +0000,nyt,Supreme Court Rejects Virginia Democrats’ Effo...,https://www.nytimes.com/2026/05/15/us/politics...
77,50,2026-05-16-08-44-47 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...
278,47,2026-05-15-16-05-17 +0000,nypost,Trump says he’ll decide on Taiwan arms sale so...,https://nypost.com/2026/05/15/us-news/trump-cl...
17,34,2026-05-16-13-31-32 +0000,nypost,Hochul and Mamdani’s new fees may cause chaos ...,https://nypost.com/2026/05/16/us-news/hochul-m...
204,34,2026-05-15-19-51-00 +0000,wsj,So You Think You Own Shares in a Hot Startup? ...,https://www.wsj.com/finance/investing/so-you-t...
139,32,2026-05-15-22-15-24 +0000,nyt,"Tina Peters, Colorado Election Denier, Will Be...",https://www.nytimes.com/2026/05/15/us/politics...
262,32,2026-05-15-16-37-30 +0000,nypost,Arizona school district accused of letting kid...,https://nypost.com/2026/05/15/us-news/arizona-...
186,30,2026-05-15-20-30-00 +0000,wsj,Republican and Democratic lawmakers on Friday ...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)