## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-24-23-13-47 +0000,nypost,France bans Zyns and other nicotine pouches — ...,https://nypost.com/2026/05/24/world-news/franc...
1,2026-05-24-23-12-37 +0000,nypost,"Swimmer chokes, scratches boy at water park af...",https://nypost.com/2026/05/24/us-news/swimmer-...
2,2026-05-24-23-09-43 +0000,nypost,Wave of lawsuits over toxic Orange County chem...,https://nypost.com/2026/05/24/us-news/wave-of-...
3,2026-05-24-23-06-46 +0000,nyt,Iran War Live Updates: U.S.-Iran Peace Deal Ne...,https://www.nytimes.com/live/2026/05/24/world/...
4,2026-05-24-23-06-12 +0000,nyt,What to Know About the Potential U.S.-Iran Pea...,https://www.nytimes.com/2026/05/24/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
30    iran     26
97   trump     25
35    deal     21
247  house     10
63      up      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
108,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...,139
167,2026-05-24-02-52-55 +0000,nypost,Iran agrees to give up ‘nuclear dust’ stockpil...,https://nypost.com/2026/05/23/us-news/iran-agr...,97
3,2026-05-24-23-06-46 +0000,nyt,Iran War Live Updates: U.S.-Iran Peace Deal Ne...,https://www.nytimes.com/live/2026/05/24/world/...,96
174,2026-05-24-01-18-31 +0000,bbc,Trump says Iran deal 'largely negotiated' incl...,https://www.bbc.com/news/articles/crmp121z3z8o...,95
50,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
108,139,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...
146,48,2026-05-24-09-00-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
66,46,2026-05-24-17-44-53 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
10,42,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
50,35,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
88,33,2026-05-24-15-44-50 +0000,nypost,California governor candidate Xavier Becerra m...,https://nypost.com/2026/05/24/us-news/californ...
76,27,2026-05-24-16-50-46 +0000,bbc,Large-scale Russian attack on Ukraine leaves f...,https://www.bbc.com/news/articles/clyp6831yp5o...
41,26,2026-05-24-21-02-08 +0000,bbc,She was told to marry in a country which bans ...,https://www.bbc.com/news/articles/ce3pgn48wnqo...
1,24,2026-05-24-23-12-37 +0000,nypost,"Swimmer chokes, scratches boy at water park af...",https://nypost.com/2026/05/24/us-news/swimmer-...
53,22,2026-05-24-19-48-30 +0000,nypost,Male cops cross-dress as sexy dancers to catch...,https://nypost.com/2026/05/24/world-news/thai-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)