## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-17-12-57-06 +0000,nypost,‘Cornell 7’ fraternity brother’s family’s ties...,https://nypost.com/2026/10/17/us-news/cornell-...
1,2026-10-17-12-55-52 +0000,nyt,A Wayward Shark Becomes a Celebrity in South K...,https://www.nytimes.com/2026/10/16/world/asia/...
2,2026-10-17-12-53-07 +0000,nyt,Can Cereal Be Healthy? Big Companies Are Trying.,https://www.nytimes.com/2026/10/17/dining/brea...
3,2026-10-17-12-46-51 +0000,cbc,Widespread protests taking place across France...,https://www.cbc.ca/news/world/livestory/france...
4,2026-10-17-12-39-10 +0000,nyt,Why Are There Protests in France?,https://www.nytimes.com/2026/10/17/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
34    trump     39
55      new     23
244  school     15
335   white     13
336   house     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
105,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,139
86,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...,108
174,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...,107
93,2026-10-17-02-20-27 +0000,nyt,"Katie Zacharia, Trump’s New Press Secretary, I...",https://www.nytimes.com/2026/10/16/us/politics...,99
9,2026-10-17-12-27-41 +0000,cbc,Zelenskyy urges support for new U.S. sanctions...,https://www.cbc.ca/news/world/zelenskyy-trump-...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
105,139,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
86,63,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...
111,57,2026-10-17-01-12-39 +0000,nyt,Teacher Killed in Oregon School Shooting Was W...,https://www.nytimes.com/2026/10/16/us/bend-sch...
183,50,2026-10-16-20-35-28 +0000,nypost,AI stock sell-off ramps up over debt-fueled da...,https://nypost.com/2026/10/16/business/ai-stoc...
94,40,2026-10-17-02-10-04 +0000,nypost,"Pope Leo XIV calls Putin, urges cease-fire as ...",https://nypost.com/2026/10/16/world-news/pope-...
63,38,2026-10-17-07-45-17 +0000,nypost,UK ambulance staff viewed medical records of e...,https://nypost.com/2026/10/17/world-news/willi...
276,36,2026-10-16-14-34-39 +0000,cbc,"Israeli settlers attack Palestinians, American...",https://www.cbc.ca/news/world/israeli-settlers...
136,36,2026-10-16-23-48-38 +0000,nypost,Michele Tafoya schools Peggy Flanagan in Senat...,https://nypost.com/2026/10/16/us-news/michelle...
17,35,2026-10-17-12-00-00 +0000,latimes,"Lopez: It's been a great romance, but it's tim...",https://www.latimes.com/california/story/2026-...
118,32,2026-10-17-00-48-52 +0000,nypost,Ukraine’s strikes on Russian oil refineries is...,https://nypost.com/2026/10/16/world-news/ukrai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)