## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-13-01-19-02 +0000,nypost,Cops issue urgent plea as West Coast ‘cat boat...,https://nypost.com/2026/08/12/us-news/dozens-o...
1,2026-08-13-01-17-24 +0000,nypost,Teenage suspect in custody after injuring stud...,https://nypost.com/2026/08/12/us-news/teenage-...
2,2026-08-13-01-04-00 +0000,wsj,What We Learned Tracing North Korea’s Hidden W...,https://www.wsj.com/world/asia/what-we-learned...
3,2026-08-13-01-03-00 +0000,wsj,Gold Gains on Reduced Fed Rate Hike Expectations,https://www.wsj.com/finance/commodities-future...
4,2026-08-13-01-01-51 +0000,bbc,Travis Kelce shares first details from his wed...,https://www.bbc.co.uk/news/articles/cx2r179e23...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2456/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
259      trump     39
249    eclipse     24
106  wisconsin     23
108        new     19
663    primary     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
441,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,161
90,2026-08-12-22-02-00 +0000,wsj,"White House press secretary Karoline Leavitt, ...",https://www.wsj.com/politics/policy/white-hous...,132
162,2026-08-12-20-14-22 +0000,cbc,White House press secretary Karoline Leavitt t...,https://www.cbc.ca/news/world/karoline-leavitt...,122
62,2026-08-12-22-58-45 +0000,bbc,Trump says White House press secretary Karolin...,https://www.bbc.co.uk/news/articles/cvglzrvyrz...,118
77,2026-08-12-22-28-48 +0000,nyt,"Karoline Leavitt, Trump’s White House Press Se...",https://www.nytimes.com/2026/08/12/us/politics...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
441,161,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...
384,108,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...
253,94,2026-08-12-16-30-43 +0000,cbc,Millions gather to watch total solar eclipse i...,https://www.cbc.ca/news/world/livestory/total-...
175,86,2026-08-12-19-45-06 +0000,nypost,Karoline Leavitt leaving White House press sec...,https://nypost.com/2026/08/12/us-news/karoline...
146,66,2026-08-12-20-36-18 +0000,bbc,New indictment alleges Nick Reiner was lying i...,https://www.bbc.co.uk/news/articles/cx2l13p6g3...
156,59,2026-08-12-20-18-00 +0000,wsj,A former director at the Southern Poverty Law ...,https://www.wsj.com/politics/policy/former-sou...
267,54,2026-08-12-15-56-00 +0000,wsj,July’s inflation report was close enough to ex...,https://www.wsj.com/economy/central-banking/in...
281,48,2026-08-12-15-19-30 +0000,nypost,"Trump calls Iran ‘all talk and no action,’ tou...",https://nypost.com/2026/08/12/us-news/trump-ca...
225,45,2026-08-12-17-51-58 +0000,chitri,Los Angeles Lakers to be sold for 2nd time in ...,https://www.chicagotribune.com/2026/08/12/los-...
6,42,2026-08-13-01-00-00 +0000,wsj,The ascendant far-left is hitting turbulence i...,https://www.wsj.com/politics/elections/midwest...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)