## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-11-54-15 +0000,nyt,Israel Launches Crackdown in West Bank City Af...,https://www.nytimes.com/2026/10/24/world/middl...
1,2026-10-24-11-43-08 +0000,nyt,"In U.S. Gas Talks With Kremlin, Hidden Financi...",https://www.nytimes.com/2026/10/23/us/politics...
2,2026-10-24-11-42-55 +0000,nyt,Live Updates: France Deploys Vast Security For...,https://www.nytimes.com/live/2026/10/24/world/...
3,2026-10-24-11-39-06 +0000,nypost,Biden ‘autopen’ attorney and anti-Trump lawyer...,https://nypost.com/2026/10/24/us-news/ilhan-om...
4,2026-10-24-11-23-59 +0000,bbc,Arrest made after fire at Hitler's mountaintop...,https://www.bbc.co.uk/news/articles/cr93zwjw1k...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
30      trump     45
64    ukraine     15
476       new     15
429  election     14
18     france     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
159,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,163
226,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,105
308,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...,101
293,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,93
110,2026-10-24-02-35-00 +0000,wsj,The Trump administration has asked a federal c...,https://www.wsj.com/politics/elections/justice...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
159,163,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
320,58,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls o...,https://nypost.com/2026/10/23/business/oil-pri...
125,58,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
308,56,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...
5,54,2026-10-24-11-21-50 +0000,nypost,NJ middle school teacher busted in prostitutio...,https://nypost.com/2026/10/24/us-news/nj-teach...
124,47,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
293,37,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...
211,37,2026-10-23-19-54-02 +0000,missionlocal,Excelsior Buzz: Grab a free Mission Local spec...,https://missionlocal.org/2026/10/excelsior-buz...
24,36,2026-10-24-10-16-55 +0000,nypost,Man killed in suspected racist attack near Par...,https://nypost.com/2026/10/24/world-news/paris...
248,36,2026-10-23-17-58-18 +0000,nypost,Ohio Dem Amy Acton’s estranged mom left five-d...,https://nypost.com/2026/10/23/us-news/amy-acto...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)