## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-19-47-22 +0000,nyt,110 Trucking Schools Closed for English-Langua...,https://www.nytimes.com/2026/08/31/us/politics...
1,2026-08-31-19-47-05 +0000,nypost,Bombshell suit claims Amazon cheated advertise...,https://nypost.com/2026/08/31/business/ftc-cla...
2,2026-08-31-19-44-33 +0000,startribune,The Vikings’ 53-man roster is already changing...,https://www.startribune.com/minnesota-vikings-...
3,2026-08-31-19-40-00 +0000,wsj,Two Deaths in Grand Canyon Floods; Over a Doze...,https://www.wsj.com/us-news/climate-environmen...
4,2026-08-31-19-35-31 +0000,nypost,Trump unveils more prescription drug pricing d...,https://nypost.com/2026/08/31/us-news/trump-un...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2419/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
32   trump     19
114   iran     16
142     up     14
213  flood     12
137  nepal     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
95,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...,97
99,2026-08-31-16-26-55 +0000,nypost,Haunting photo of Grand Canyon hiker before he...,https://nypost.com/2026/08/31/us-news/grand-ca...,79
26,2026-08-31-18-58-16 +0000,bbc,Two dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...,78
181,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...,78
64,2026-08-31-17-50-29 +0000,wapo,Trump vows to hit Iran hard as strikes and eco...,https://www.washingtonpost.com/world/2026/08/3...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
95,97,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...
99,79,2026-08-31-16-26-55 +0000,nypost,Haunting photo of Grand Canyon hiker before he...,https://nypost.com/2026/08/31/us-news/grand-ca...
138,54,2026-08-31-13-59-16 +0000,nypost,Oil prices jump 3% to over $90 after US-Iran e...,https://nypost.com/2026/08/31/business/oil-pri...
258,53,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
115,45,2026-08-31-15-24-45 +0000,chitri,Kalshi bans ex-Congressman George Santos for l...,https://www.chicagotribune.com/2026/08/31/kals...
184,42,2026-08-31-10-16-50 +0000,cbc,Hundreds feared stuck in hydropower tunnels as...,https://www.cbc.ca/news/world/nepal-tibet-floo...
58,35,2026-08-31-18-00-16 +0000,cbc,"America 'not at war' with Canada, insists U.S....",https://www.cbc.ca/news/politics/bessent-carne...
80,32,2026-08-31-16-58-33 +0000,nypost,D4vd drops high-powered lawyers for public def...,https://nypost.com/2026/08/31/us-news/d4vd-dro...
124,32,2026-08-31-14-50-36 +0000,bbc,'She slipped out of my hand' - children missin...,https://www.bbc.co.uk/news/articles/c1mv5ggg1l...
177,32,2026-08-31-10-55-00 +0000,wsj,The Texas Senate race is shaping up to be a co...,https://www.wsj.com/politics/ken-paxton-is-in-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)