## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-17-16-58-07 +0000,nyt,American Hiker Dies After Lightning Strike on ...,https://www.nytimes.com/2026/08/17/world/europ...
1,2026-08-17-16-54-42 +0000,nypost,"Lindsay Clancy cried about Andrea Yates case, ...",https://nypost.com/2026/08/17/us-news/lindsay-...
2,2026-08-17-16-48-00 +0000,wsj,Trump Says Israel Should Stop Striking Gaza,https://www.wsj.com/world/middle-east/trump-sa...
3,2026-08-17-16-47-45 +0000,bbc,"Boy, seven, among four injured after crash tha...",https://www.bbc.co.uk/news/articles/ce8lx172ke...
4,2026-08-17-16-47-36 +0000,missionlocal,"Soccer, Spiderman backpack, purple outfit: Kid...",https://missionlocal.org/2026/08/sf-back-to-sc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2602/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19   trump     45
65    iran     20
271    new     15
66     war     14
531  south     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
139,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,134
185,2026-08-17-06-24-31 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,128
73,2026-08-17-14-00-02 +0000,startribune,Supreme Court again rebuffs Trump's push to to...,https://www.startribune.com/supreme-court-agai...,103
211,2026-08-17-00-20-54 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,98
17,2026-08-17-16-26-34 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
139,134,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
121,64,2026-08-17-11-03-00 +0000,wsj,One of the most sensitive stories in this near...,https://www.wsj.com/politics/pentagon-rotates-...
73,58,2026-08-17-14-00-02 +0000,startribune,Supreme Court again rebuffs Trump's push to to...,https://www.startribune.com/supreme-court-agai...
281,46,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...
74,38,2026-08-17-13-57-39 +0000,wapo,"Kushner meets with Netanyahu in Israel, aiming...",https://www.washingtonpost.com/world/2026/08/1...
8,38,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
248,31,2026-08-16-19-56-39 +0000,nypost,Gavin Newsom wildfire plan faces revolt over w...,https://nypost.com/2026/08/16/us-news/gavin-ne...
13,31,2026-08-17-16-33-17 +0000,nypost,White House takes victory lap as drug prices d...,https://nypost.com/2026/08/17/us-news/white-ho...
201,29,2026-08-17-02-00-00 +0000,wsj,"With the Iowa State Fair in full swing, Republ...",https://www.wsj.com/politics/elections/rural-e...
219,27,2026-08-16-23-21-37 +0000,bbc,'I want my brother back' - Tupac’s brother tel...,https://www.bbc.co.uk/news/videos/cj4kglpl55lo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)