## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-23-15-01 +0000,nyt,Trump Says It’s ‘Too Bad’ Supreme Court Upheld...,https://www.nytimes.com/2026/06/30/us/politics...
1,2026-06-30-23-13-00 +0000,wsj,"Trump’s Friends Gave Him Tickets to World Cup,...",https://www.wsj.com/sports/trumps-friends-gave...
2,2026-06-30-23-07-33 +0000,nypost,Bloods affiliate NYC street gang started war s...,https://nypost.com/2026/06/30/us-news/bloods-a...
3,2026-06-30-23-06-28 +0000,nypost,Missing Massachusetts cat miraculously found u...,https://nypost.com/2026/06/30/us-news/missing-...
4,2026-06-30-23-05-19 +0000,bbc,Why Gen Z are planning for life without a stat...,https://www.bbc.co.uk/news/articles/c8e2yp1gg3...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2531/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
4        court     39
3      supreme     37
0        trump     30
35         new     17
6   birthright     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
229,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,150
236,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...,147
233,2026-06-30-14-41-59 +0000,cbc,U.S. Supreme Court denies Trump bid to end bir...,https://www.cbc.ca/news/world/us-scotus-ruling...,146
160,2026-06-30-18-01-22 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,145
108,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
229,150,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...
135,49,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
1,47,2026-06-30-23-13-00 +0000,wsj,"Trump’s Friends Gave Him Tickets to World Cup,...",https://www.wsj.com/sports/trumps-friends-gave...
37,41,2026-06-30-22-21-04 +0000,nypost,Gavin Newsom finally stumps up the cash to spe...,https://nypost.com/2026/06/30/us-news/gavin-ne...
101,41,2026-06-30-20-22-00 +0000,wsj,"Stocks rise, the yen slides and a quiet Fed on...",https://www.wsj.com/finance/stocks/stocks-rise...
45,40,2026-06-30-22-11-00 +0000,wsj,Wall Street’s Best Quarter in Six Years Will B...,https://www.wsj.com/finance/stocks/wall-street...
17,38,2026-06-30-22-53-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
208,35,2026-06-30-15-53-59 +0000,latimes,Supreme Court rules that states may ban trans ...,https://www.latimes.com/politics/story/2026-06...
34,34,2026-06-30-22-24-16 +0000,nypost,‘State sanctioned’ Russian mob ran $1B Medicar...,https://nypost.com/2026/06/30/us-news/russian-...
24,34,2026-06-30-22-36-08 +0000,nypost,Chirayu Rana dealt another humiliating legal b...,https://nypost.com/2026/06/30/us-news/chirayu-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)