## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-16-23-42 +0000,nyt,Tech Stocks Tumble on Worries Over A.I. Spendi...,https://www.nytimes.com/2026/07/28/business/st...
1,2026-07-28-16-22-36 +0000,nyt,"In This Costa Rican Forest, Monkeys Come Face-...",https://www.nytimes.com/2026/07/28/science/cos...
2,2026-07-28-16-22-11 +0000,nypost,Sleazy six-word comment Gavin Newsom allegedly...,https://nypost.com/2026/07/28/us-news/ruby-rip...
3,2026-07-28-16-22-00 +0000,wsj,How a $140 Million Crypto Real Estate Empire F...,https://www.wsj.com/real-estate/how-a-140-mill...
4,2026-07-28-16-18-58 +0000,nyt,Aide Who Had Affair With Newsom 20 Years Ago D...,https://www.nytimes.com/2026/07/28/us/gavin-ne...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
124   trump     39
49      new     23
133    iran     22
138  market     14
444      ai     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...,118
157,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,112
14,2026-07-28-16-00-08 +0000,startribune,Trump expresses frustrations with Netanyahu be...,https://www.startribune.com/netanyahus-first-m...,108
296,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,93
99,2026-07-28-13-00-50 +0000,nypost,Trump publicly rebukes Netanyahu ahead of crit...,https://nypost.com/2026/07/28/us-news/trump-re...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,118,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...
281,57,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
261,51,2026-07-27-23-26-53 +0000,nypost,Xavier Becerra leads Democrats’ all-out war ag...,https://nypost.com/2026/07/27/us-news/xavier-b...
233,48,2026-07-28-01-29-25 +0000,bbc,BBC outside court as judge rules singer D4vd w...,https://www.bbc.co.uk/news/videos/cy745x171rjo...
121,46,2026-07-28-11-18-00 +0000,wsj,Perhaps no one has a tougher job in Washington...,https://www.wsj.com/politics/the-save-america-...
283,44,2026-07-27-21-46-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
366,43,2026-07-27-17-20-27 +0000,bbc,What you need to know if you're travelling to ...,https://www.bbc.co.uk/news/videos/c89npw4q3g4o...
27,41,2026-07-28-15-24-52 +0000,nypost,"Trump, Zelensky hold crucial behind-closed-doo...",https://nypost.com/2026/07/28/us-news/trump-ze...
305,40,2026-07-27-20-36-12 +0000,bbc,US mother's mental health spiralled before her...,https://www.bbc.co.uk/news/articles/cg5lv82058...
253,38,2026-07-28-00-00-00 +0000,wsj,"Francesca Hong, a member of the Democratic Soc...",https://www.wsj.com/politics/elections/a-democ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)