## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-30-06-44-00 +0000,wsj,French Economy Shrinks as Debt Worries Mount,https://www.wsj.com/economy/french-economy-shr...
1,2026-10-30-06-44-00 +0000,wsj,Credit Agricole Profit Climbs on Boost From In...,https://www.wsj.com/business/earnings/credit-a...
2,2026-10-30-06-39-19 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/29/us/mid...
3,2026-10-30-06-36-00 +0000,wsj,"Amazon Stock Drops on Wall Street Miss, Despit...",https://www.wsj.com/tech/amazon-amzn-q3-earnin...
4,2026-10-30-06-34-00 +0000,wsj,"Bank of Japan Declares Inflation Win, Clearing...",https://www.wsj.com/economy/central-banking/ba...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2442/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
389       trump     31
43     election     26
237         new     25
478  california     20
61           up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
70,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home hea...",https://www.wsj.com/politics/elections/how-ala...,146
91,2026-10-29-23-51-40 +0000,nypost,Feds hit California election officials with fr...,https://nypost.com/2026/10/29/us-news/trumps-d...,99
347,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,97
192,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...,89
246,2026-10-29-17-51-41 +0000,nypost,California High-Speed Rail Authority names new...,https://nypost.com/2026/10/29/us-news/gavin-ne...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
70,146,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home hea...",https://www.wsj.com/politics/elections/how-ala...
91,99,2026-10-29-23-51-40 +0000,nypost,Feds hit California election officials with fr...,https://nypost.com/2026/10/29/us-news/trumps-d...
292,68,2026-10-29-15-59-34 +0000,cbc,Canada's new national security strategy will s...,https://www.cbc.ca/news/politics/national-secu...
431,64,2026-10-29-09-01-00 +0000,wsj,Most Americans—including many Iranian American...,https://www.wsj.com/politics/elections/i-went-...
379,60,2026-10-29-11-32-00 +0000,wsj,"The Morning Risk Report: Tech, Social Media Co...",https://www.wsj.com/risk-compliance-journal/th...
384,58,2026-10-29-11-09-09 +0000,chitri,Prime Minister Benjamin Netanyahu’s party ampl...,https://www.chicagotribune.com/2026/10/29/isra...
352,50,2026-10-29-13-18-29 +0000,nypost,Feds found evidence Ilhan Omar was in sham mar...,https://nypost.com/2026/10/29/us-news/feds-fou...
387,49,2026-10-29-11-07-35 +0000,bbc,Audio reveals exchanges between Spain train op...,https://www.bbc.co.uk/news/articles/cmqxnl312v...
284,43,2026-10-29-16-13-06 +0000,nypost,Conservative groups warn letting AI giants ‘re...,https://nypost.com/2026/10/29/business/conserv...
253,40,2026-10-29-17-16-01 +0000,nypost,Wall Street con man used 87-year-old Obama don...,https://nypost.com/2026/10/29/business/wall-st...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)