## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-10-16-43 +0000,nyt,Live Updates: Iran and Israel Trade Strikes as...,https://www.nytimes.com/live/2026/06/08/world/...
1,2026-06-08-10-13-58 +0000,bbc,Armenia's pro-West government wins election de...,https://www.bbc.com/news/articles/cvgel990n51o...
2,2026-06-08-10-13-00 +0000,wsj,Intesa Bids $35 Billion for Monte dei Paschi,https://www.wsj.com/business/deals/intesa-make...
3,2026-06-08-10-13-00 +0000,wsj,German Factory Orders Fell Back in April as Ir...,https://www.wsj.com/economy/german-factory-ord...
4,2026-06-08-10-04-21 +0000,nypost,"Trump says Israel, Iran must ‘stop shooting’ a...",https://nypost.com/2026/06/08/us-news/trump-sa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2698/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
2      iran     22
6     trump     22
3    israel     20
191     new     17
239   world     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...,90
0,2026-06-08-10-16-43 +0000,nyt,Live Updates: Iran and Israel Trade Strikes as...,https://www.nytimes.com/live/2026/06/08/world/...,85
4,2026-06-08-10-04-21 +0000,nypost,"Trump says Israel, Iran must ‘stop shooting’ a...",https://nypost.com/2026/06/08/us-news/trump-sa...,73
15,2026-06-08-09-54-00 +0000,wsj,Trump Tells Israel and Iran to Stop Exchanges ...,https://www.wsj.com/world/middle-east/iran-fir...,71
160,2026-06-07-20-19-53 +0000,nyt,Trump Defends Compensation Fund and Iran War i...,https://www.nytimes.com/2026/06/07/us/politics...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,90,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...
73,61,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
110,47,2026-06-08-01-00-00 +0000,wsj,"Most rankings of companies look backward, meas...",https://www.wsj.com/economy/jobs/best-companie...
113,46,2026-06-08-00-08-41 +0000,nypost,Nithya Raman knocks Spencer Pratt off second p...,https://nypost.com/2026/06/07/us-news/nithya-r...
141,41,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
88,37,2026-06-08-02-24-02 +0000,nypost,Fears for LA’s opening World Cup game as exper...,https://nypost.com/2026/06/07/us-news/fears-fo...
201,35,2026-06-07-15-48-19 +0000,nypost,Trump storms off ‘Meet The Press’ interview af...,https://nypost.com/2026/06/07/us-news/trump-st...
204,32,2026-06-07-15-37-00 +0000,wsj,"OPEC, Allies Pledge Oil-Output Hike Even as Mi...",https://www.wsj.com/business/energy-oil/opec-a...
101,29,2026-06-08-01-37-19 +0000,cbc,"Powerful earthquake kills at least 19, destroy...",https://www.cbc.ca/news/world/philippines-eart...
74,27,2026-06-08-04-29-34 +0000,nypost,NYPD cop appears to slam Knicks fan’s head int...,https://nypost.com/2026/06/08/us-news/nypd-cop...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)