## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-04-22-12-00 +0000,wsj,A divided Senate Judiciary Committee advanced ...,https://www.wsj.com/politics/policy/senate-jud...
1,2026-08-04-22-10-39 +0000,nypost,Dad and 2 daughters found dead hours after div...,https://nypost.com/2026/08/04/us-news/dad-and-...
2,2026-08-04-22-08-54 +0000,nyt,"Todd Blanche Clears Committee Vote, Nearing Co...",https://www.nytimes.com/2026/08/04/us/politics...
3,2026-08-04-22-08-04 +0000,nyt,"To prevail, Stevens will need to overcome Demo...",https://www.nytimes.com/live/2026/08/04/us/mid...
4,2026-08-04-22-08-00 +0000,wsj,Antitrust Trial Over Paramount-Warner Merger S...,https://www.wsj.com/business/media/antitrust-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
116   trump     30
474     new     27
81     iran     23
341    deal     21
543  hormuz     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
303,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,127
363,2026-08-04-01-19-29 +0000,nyt,An Emerging Deal Between Iran and Oman to Reop...,https://www.nytimes.com/2026/08/03/us/politics...,117
156,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...,106
280,2026-08-04-11-05-47 +0000,nypost,"Iran, Oman near deal to reopen Strait of Hormu...",https://nypost.com/2026/08/04/us-news/iran-oma...,96
248,2026-08-04-13-43-38 +0000,nypost,US may have deal with Iran to reopen Strait of...,https://nypost.com/2026/08/04/us-news/us-may-h...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
303,127,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...
279,73,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...
74,68,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
0,64,2026-08-04-22-12-00 +0000,wsj,A divided Senate Judiciary Committee advanced ...,https://www.wsj.com/politics/policy/senate-jud...
156,56,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
284,47,2026-08-04-10-59-00 +0000,wsj,President Trump told embattled Rep. Max Miller...,https://www.wsj.com/politics/elections/trump-w...
375,47,2026-08-04-00-00-00 +0000,wsj,A little-used Fed backstop is being put to a u...,https://www.wsj.com/economy/central-banking/wh...
6,41,2026-08-04-22-05-49 +0000,nypost,Mamdani shrugs off ballooning cost of NYC free...,https://nypost.com/2026/08/04/us-news/mamdani-...
144,41,2026-08-04-19-00-43 +0000,bbc,Oil prices fall on hopes Strait of Hormuz coul...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
234,40,2026-08-04-14-44-50 +0000,chitri,"McDonald’s posts strong second quarter profit,...",https://www.chicagotribune.com/2026/08/04/mcdo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)