## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-29-23-52-41 +0000,nyt,Cornell’s Chi Phi Chapter Faces Scrutiny Over ...,https://www.nytimes.com/2026/09/29/us/chi-phi-...
1,2026-09-29-23-47-10 +0000,bbc,OpenAI unveils AI assistant 'dots' while safet...,https://www.bbc.co.uk/news/articles/cw7v42rp08...
2,2026-09-29-23-46-00 +0000,wsj,Ellison Picks HBO Content Chief to Run Paramou...,https://www.wsj.com/business/media/ellison-pic...
3,2026-09-29-23-45-32 +0000,nypost,Xavier Becerra’s excruciating interview sees h...,https://nypost.com/2026/09/29/us-news/xavier-b...
4,2026-09-29-23-41-41 +0000,nyt,"A.I. Is ‘Better Informed’ Than Doctors, Kenned...",https://www.nytimes.com/2026/09/29/health/maha...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
60        trump     49
16          new     24
10           ai     20
111  california     14
132        will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...,197
224,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...,134
198,2026-09-29-17-27-33 +0000,chitri,President Trump says top tech firms have signe...,https://www.chicagotribune.com/2026/09/29/dona...,107
279,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...,104
33,2026-09-29-22-53-47 +0000,latimes,Can California stop Trump from drilling off it...,https://www.latimes.com/environment/story/2026...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,197,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...
160,72,2026-09-29-19-10-00 +0000,wsj,New York Fed President John Williams said that...,https://www.wsj.com/economy/central-banking/ne...
200,70,2026-09-29-17-22-18 +0000,nyt,Prime Minister Andy Burnham Lays Out Plan to C...,https://www.nytimes.com/2026/09/29/world/europ...
330,56,2026-09-29-11-00-57 +0000,chitri,News organizations ask court to bar White Hous...,https://www.chicagotribune.com/2026/09/29/news...
279,55,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...
387,51,2026-09-29-08-19-57 +0000,wsj,Stock Market Today: 10-Year Treasury Yield Pus...,https://www.wsj.com/livecoverage/stock-market-...
57,48,2026-09-29-21-55-00 +0000,cbc,Trump says top tech firms have signed accord t...,https://www.cbc.ca/news/world/ai-trump-agreeme...
30,47,2026-09-29-23-00-00 +0000,wsj,He Was Rejected by Goldman Out of College. Now...,https://www.wsj.com/finance/investing/he-was-r...
257,38,2026-09-29-15-17-31 +0000,nypost,Former DSA member gives bleak warning about fa...,https://nypost.com/2026/09/29/us-news/former-d...
421,37,2026-09-29-02-29-41 +0000,latimes,'Bomb-like' marine marker among unusual items ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)