## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-12-00-01-46 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/08/11/us/ele...
1,2026-08-12-00-01-43 +0000,nyt,Iran Said to Have Known Details of Trump’s Sta...,https://www.nytimes.com/2026/08/11/us/politics...
2,2026-08-12-00-00-00 +0000,wsj,"After a streak of good fortune, Mayor Zohran M...",https://www.wsj.com/us-news/mamdanis-honeymoon...
3,2026-08-12-00-00-00 +0000,wsj,Mamdani’s Honeymoon With New York Is Over,https://www.wsj.com/us-news/mamdanis-honeymoon...
4,2026-08-11-23-56-25 +0000,nyt,"Judge Awards $250,000 to Musician Who Fled Tru...",https://www.nytimes.com/2026/08/11/arts/music/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
5      trump     52
18       new     26
2       iran     17
59     death     15
61  colombia     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...,188
44,2026-08-11-22-50-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,146
369,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,141
236,2026-08-11-15-14-04 +0000,nypost,Stunning details emerge of Trump’s catering-tr...,https://nypost.com/2026/08/11/us-news/video-ap...,120
247,2026-08-11-14-40-32 +0000,cbc,Trump was shuttled between planes in a caterin...,https://www.cbc.ca/news/world/us-trump-plane-n...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,188,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...
369,89,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
385,63,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
330,62,2026-08-11-09-27-28 +0000,nypost,Ex-Syrian ruler Bashar al-Assad sentenced to d...,https://nypost.com/2026/08/11/world-news/ex-sy...
7,43,2026-08-11-23-48-47 +0000,nyt,As Death Toll From Colombia Earthquake Rises t...,https://www.nytimes.com/2026/08/11/world/ameri...
205,41,2026-08-11-16-36-49 +0000,nypost,LA council president issues scathing four-word...,https://nypost.com/2026/08/11/us-news/la-counc...
177,41,2026-08-11-17-57-52 +0000,nypost,Michigan Dem Senate candidate Abdul El-Sayed s...,https://nypost.com/2026/08/11/us-news/michigan...
128,39,2026-08-11-20-17-28 +0000,chitri,Looking to see the solar eclipse from North Am...,https://www.chicagotribune.com/2026/08/11/sola...
227,38,2026-08-11-15-53-42 +0000,nypost,Nvidia partners with major Wall Street players...,https://nypost.com/2026/08/11/business/nvidia-...
165,38,2026-08-11-18-23-12 +0000,nyt,What to Watch in Tuesday’s Primary Elections i...,https://www.nytimes.com/2026/08/11/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)