## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-09-04-05 +0000,nyt,Family of Epstein Victim Appears in Ad Targeti...,https://www.nytimes.com/2026/10/05/us/politics...
1,2026-10-05-09-03-50 +0000,nyt,Who’s Winning the Battle for Congress?,https://www.nytimes.com/2026/10/05/us/politics...
2,2026-10-05-09-03-30 +0000,bbc,Why has Spain's PM called a snap election?,https://www.bbc.co.uk/news/videos/c83vqk2k2k20...
3,2026-10-05-09-03-24 +0000,nyt,Supreme Court to Hear Major Environmental Lawsuit,https://www.nytimes.com/2026/10/05/us/politics...
4,2026-10-05-09-03-20 +0000,nyt,Will Midterm Elections Complicate the Supreme ...,https://www.nytimes.com/video/us/1000000111847...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
14   election     15
53      trump     14
25        new     14
380    brazil      9
275       oil      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
102,2026-10-05-00-26-14 +0000,cbc,"Lula, Bolsonaro head to run-off after neither ...",https://www.cbc.ca/news/world/lula-bolsonaro-b...,61
79,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...,61
206,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,57
144,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...,56
99,2026-10-05-00-34-02 +0000,chitri,The Latest: Brazil heads to runoff presidentia...,https://www.chicagotribune.com/2026/10/04/braz...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
102,61,2026-10-05-00-26-14 +0000,cbc,"Lula, Bolsonaro head to run-off after neither ...",https://www.cbc.ca/news/world/lula-bolsonaro-b...
206,57,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
144,51,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...
132,45,2026-10-04-22-07-54 +0000,nypost,Russian drone slams into key Kyiv bridge durin...,https://nypost.com/2026/10/04/world-news/russi...
54,41,2026-10-05-06-47-00 +0000,wsj,Ithaca Energy to Buy Offshore Canada Oil Asset...,https://www.wsj.com/business/energy-oil/ithaca...
55,37,2026-10-05-06-45-01 +0000,nypost,"Former ‘Survivor’ star faces arrest, FBI probe...",https://nypost.com/2026/10/05/us-news/fbi-inve...
159,36,2026-10-04-19-56-00 +0000,wsj,Americans are facing a multifront squeeze from...,https://www.wsj.com/politics/elections/energy-...
76,32,2026-10-05-03-22-37 +0000,nypost,High school runners stumble upon human remains...,https://nypost.com/2026/10/04/us-news/high-sch...
45,31,2026-10-05-07-34-00 +0000,wsj,Spain’s Prime Minister Sanchez Calls Snap Elec...,https://www.wsj.com/world/europe/spains-prime-...
44,31,2026-10-05-07-34-16 +0000,nypost,Indiana murder suspect arrested 20 years after...,https://nypost.com/2026/10/05/us-news/indiana-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)