## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-10-16-07-51 +0000,nyt,Live Updates: U.S. Warns of ‘Most Intense’ Str...,https://www.nytimes.com/live/2026/03/10/world/...
1,2026-03-10-16-07-42 +0000,nyt,U.S. Eases Limits on Russian Energy as Oil Pri...,https://www.nytimes.com/2026/03/10/world/middl...
2,2026-03-10-16-07-00 +0000,wsj,"Gold Rises Above $5,200 on Easing Inflation Co...",https://www.wsj.com/finance/commodities-future...
3,2026-03-10-16-07-00 +0000,wsj,Opinion | A War by Any Other Name,https://www.wsj.com/opinion/a-war-by-any-other...
4,2026-03-10-16-04-10 +0000,bbc,'What is the height of the London Eye?' minist...,https://www.bbc.com/news/videos/c89k2z8vy93o?a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2615/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
6    iran     59
49  trump     43
20    war     40
10    oil     31
97    new     26

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
144,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...,210
215,2026-03-10-03-15-14 +0000,nyt,Trump Seeks to Calm Oil and Gas Markets but Sa...,https://www.nytimes.com/2026/03/09/us/politics...,203
213,2026-03-10-03-24-00 +0000,wsj,"Oil Retreats, Asia Equities Rebound After Trum...",https://www.wsj.com/finance/stocks/oil-retreat...,191
351,2026-03-09-18-53-40 +0000,nypost,US sends Cold War heavy-hitter B-52 bombers to...,https://nypost.com/2026/03/09/world-news/us-se...,182
212,2026-03-10-03-32-18 +0000,nyt,"Trump’s War in Iran, and Rising Gas Prices, Co...",https://www.nytimes.com/2026/03/09/us/politics...,177

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
144,210,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...
65,83,2026-03-10-14-22-37 +0000,nypost,Happiest cities in the US revealed — we have g...,https://nypost.com/2026/03/10/lifestyle/happie...
16,60,2026-03-10-15-49-10 +0000,nypost,Disgraced Ohio State president boasted he was ...,https://nypost.com/2026/03/10/us-news/disgrace...
370,53,2026-03-09-17-20-45 +0000,nypost,Trump urges Australia to grant asylum to Irani...,https://nypost.com/2026/03/09/world-news/trump...
107,51,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...
141,40,2026-03-10-10-30-00 +0000,nypost,Why even Ayatollah Khamenei opposed his impote...,https://nypost.com/2026/03/10/world-news/ayato...
297,38,2026-03-09-21-52-00 +0000,wsj,Lawrence Summers has lost his affiliation with...,https://www.wsj.com/us-news/education/national...
116,38,2026-03-10-11-43-50 +0000,cbc,"Dozens of Haitian civilians killed by police, ...",https://www.cbc.ca/news/world/haiti-drones-hum...
328,36,2026-03-09-20-17-00 +0000,wsj,Tokenized Stocks Are Coming to a Market Near Y...,https://www.wsj.com/finance/stocks/tokenized-s...
82,35,2026-03-10-13-36-51 +0000,nypost,"Girl, 12, dies after savage fight with fellow ...",https://nypost.com/2026/03/10/us-news/girl-12-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)