## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-01-23-00 +0000,wsj,Trump Strikes Deal With Putin for Russian Diesel,https://www.wsj.com/politics/policy/trump-stri...
1,2026-10-10-01-15-01 +0000,nypost,US judge rules DOJ using state voter rolls unc...,https://nypost.com/2026/10/09/us-news/us-judge...
2,2026-10-10-01-12-57 +0000,startribune,Live: Moorhead leads Eden Prairie in high-scor...,https://www.startribune.com/minnesota-high-sch...
3,2026-10-10-01-00-00 +0000,wsj,A growing group of Republicans are privately—a...,https://www.wsj.com/politics/elections/trump-m...
4,2026-10-10-00-45-51 +0000,bbc,Trump announces deal for Russian diesel as Zel...,https://www.bbc.co.uk/news/articles/cm1dwgr666...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2632/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     50
106    new     24
349  prize     21
347  nobel     20
348  peace     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
83,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,221
221,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...,146
96,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,136
106,2026-10-09-21-00-22 +0000,wapo,Trump hits International Criminal Court with s...,https://www.washingtonpost.com/world/2026/10/0...,127
171,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
83,221,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
171,117,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...
388,101,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...
58,87,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
261,65,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
195,58,2026-10-09-16-29-36 +0000,nypost,Trump backs firing squad execution of Fort Hoo...,https://nypost.com/2026/10/09/us-news/trump-ba...
251,51,2026-10-09-14-13-06 +0000,nypost,Dow soars as tech shares rebound on SpaceX dea...,https://nypost.com/2026/10/09/business/stocks-...
371,47,2026-10-09-07-29-42 +0000,nypost,‘The View’ co-host Sunny Hostin predicts Texas...,https://nypost.com/2026/10/09/media/the-view-c...
314,43,2026-10-09-10-24-27 +0000,nyt,Labour Holds Off Green Party in Election for S...,https://www.nytimes.com/2026/10/09/world/europ...
226,43,2026-10-09-15-04-02 +0000,nypost,3 killed in Russian strikes across Ukraine as ...,https://nypost.com/2026/10/09/world-news/3-kil...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)