## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-20-56-53 +0000,nyt,Trump Witnesses Return of Bodies of U.S. Servi...,https://www.nytimes.com/2026/03/07/us/politics...
1,2026-03-07-20-50-12 +0000,nypost,Ford recalling nearly 2 million cars due to re...,https://nypost.com/2026/03/07/us-news/ford-rec...
2,2026-03-07-20-48-38 +0000,nypost,California gas prices soar above $5 a gallon —...,https://nypost.com/2026/03/07/us-news/californ...
3,2026-03-07-20-48-00 +0000,nypost,Hawaii national park death exposes repeated ru...,https://nypost.com/2026/03/07/us-news/hawaii-n...
4,2026-03-07-20-45-37 +0000,nyt,Runners at Los Angeles Marathon Can Get a Fini...,https://www.nytimes.com/2026/03/07/us/los-ange...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3226/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
97    iran     55
0    trump     46
110    war     25
27     new     14
216   year     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
177,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,182
60,2026-03-07-16-55-50 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,147
41,2026-03-07-18-28-48 +0000,wapo,"Trump to honor U.S. troops killed in war, says...",https://www.washingtonpost.com/world/2026/03/0...,146
250,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,142
235,2026-03-06-22-39-00 +0000,wsj,"Trump wants Iran’s unconditional surrender, a ...",https://www.wsj.com/politics/policy/trump-want...,142

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
177,182,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
43,65,2026-03-07-18-03-09 +0000,nypost,New video shows SF mayor’s security guard laun...,https://nypost.com/2026/03/07/us-news/new-vide...
244,53,2026-03-06-22-17-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
178,51,2026-03-07-02-00-00 +0000,wsj,Iran’s High-Risk Strategy for a No-Limits Midd...,https://www.wsj.com/world/middle-east/iran-def...
35,43,2026-03-07-18-59-47 +0000,nypost,10-year-old California whiz kid wraps up first...,https://nypost.com/2026/03/07/us-news/10-year-...
114,39,2026-03-07-11-00-00 +0000,latimes,"Gas prices soaring, Trump administration sets ...",https://www.latimes.com/california/story/2026-...
32,37,2026-03-07-19-05-37 +0000,nypost,Israel slams Lebanon with wave of attacks to r...,https://nypost.com/2026/03/07/world-news/israe...
105,34,2026-03-07-11-37-43 +0000,nypost,Trump claims Iran will be hit ‘very hard’ toda...,https://nypost.com/2026/03/07/us-news/trump-wa...
58,31,2026-03-07-17-00-00 +0000,wsj,Some Republicans complain Virginia’s most prom...,https://www.wsj.com/politics/elections/virgini...
219,29,2026-03-06-23-13-33 +0000,nypost,Beaming Newsom schmoozes Dem heavyweights at J...,https://nypost.com/2026/03/06/us-news/gavin-ne...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)