## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-15-18-11-57 +0000,bbc,SpaceX share price drops below stock market debut,https://www.bbc.co.uk/news/articles/clyl33q0yl...
1,2026-07-15-18-11-53 +0000,nyt,One Dead and Three Missing in San Francisco Ba...,https://www.nytimes.com/2026/07/14/us/boat-fir...
2,2026-07-15-18-08-57 +0000,nyt,China’s Chip Champion to Raise Billions in Rac...,https://www.nytimes.com/2026/07/15/business/ch...
3,2026-07-15-18-08-33 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/07/15/world/...
4,2026-07-15-18-07-29 +0000,bbc,Union backing to seal Labour crown for Burnham,https://www.bbc.co.uk/news/articles/c0mym3339n...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41   trump     43
26    iran     39
698    new     19
19   china     16
27     war     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
337,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...,155
199,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...,147
307,2026-07-14-22-43-47 +0000,nypost,Trump warns US will ‘knock out’ Iran’s power p...,https://nypost.com/2026/07/14/us-news/trump-sa...,136
299,2026-07-14-23-17-27 +0000,bbc,Trump retreat over Hormuz tolls suggests he is...,https://www.bbc.co.uk/news/articles/crele3r8j1...,133
179,2026-07-15-11-48-07 +0000,nyt,What Trump’s New Iran Blockade Could Mean for ...,https://www.nytimes.com/2026/07/15/business/tr...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
337,155,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...
199,108,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...
321,82,2026-07-14-22-13-00 +0000,wsj,The House passed legislation supported by Pres...,https://www.wsj.com/politics/policy/house-pass...
389,65,2026-07-14-19-38-00 +0000,wsj,"President Trump’s pick for attorney general, T...",https://www.wsj.com/politics/policy/attorney-g...
124,64,2026-07-15-14-08-00 +0000,wsj,The economy has added jobs for four straight m...,https://www.wsj.com/economy/jobs/unemployment-...
347,49,2026-07-14-21-19-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...
87,47,2026-07-15-15-51-44 +0000,nypost,Intrusive way California will target billionai...,https://nypost.com/2026/07/15/us-news/intrusiv...
1,47,2026-07-15-18-11-53 +0000,nyt,One Dead and Three Missing in San Francisco Ba...,https://www.nytimes.com/2026/07/14/us/boat-fir...
171,46,2026-07-15-12-20-59 +0000,cbc,Trump says ICE won't halt traffic stops after ...,https://www.cbc.ca/news/world/trump-ice-traffi...
238,45,2026-07-15-08-47-32 +0000,nypost,Ex-UK government minister Ann Widdecombe kille...,https://nypost.com/2026/07/15/world-news/uk-po...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)