## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-21-11-49-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
1,2026-09-21-11-47-15 +0000,nyt,Bessent and China Hail Progress on A.I. Talks....,https://www.nytimes.com/2026/09/21/business/de...
2,2026-09-21-11-47-06 +0000,wapo,"CNN, MS NOW, Politico to sue over White House ...",https://www.washingtonpost.com/business/2026/0...
3,2026-09-21-11-46-39 +0000,bbc,Seven Ethiopian rebel groups form new alliance,https://www.bbc.co.uk/news/articles/ckp84pj8zp...
4,2026-09-21-11-43-21 +0000,bbc,Families missing out on NHS money for healthy ...,https://www.bbc.co.uk/news/articles/cme30e8zyv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2320/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
37      trump     37
25        new     20
18      house     15
337      will     13
389  election     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
206,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,129
260,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...,110
218,2026-09-20-18-29-32 +0000,chitri,President Donald Trump suggests his arch will ...,https://www.chicagotribune.com/2026/09/20/trum...,103
263,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...,103
20,2026-09-21-11-09-00 +0000,wsj,"CNN, MS NOW and Politico are suing the Trump a...",https://www.wsj.com/politics/policy/cnn-ms-now...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
206,129,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
260,73,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...
244,64,2026-09-20-16-09-01 +0000,nypost,GOP’s Bruce Blakeman admits it’s ‘surreal’ his...,https://nypost.com/2026/09/20/us-news/bruce-bl...
200,44,2026-09-20-20-35-51 +0000,chitri,Russia wraps up first wartime parliamentary el...,https://www.chicagotribune.com/2026/09/20/russ...
20,39,2026-09-21-11-09-00 +0000,wsj,"CNN, MS NOW and Politico are suing the Trump a...",https://www.wsj.com/politics/policy/cnn-ms-now...
152,38,2026-09-21-00-45-57 +0000,nypost,Nithya Raman reveals how she’ll co-govern with...,https://nypost.com/2026/09/20/us-news/nithya-r...
247,37,2026-09-20-15-59-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
53,35,2026-09-21-10-00-00 +0000,nypost,Hochul’s funding for extra NYC subway cops has...,https://nypost.com/2026/09/21/us-news/hochuls-...
19,33,2026-09-21-11-12-00 +0000,wsj,"Polling has been spotty this year, but as of t...",https://www.wsj.com/politics/policy/the-midter...
118,32,2026-09-21-05-50-56 +0000,bbc,US and China discuss AI safety plan ahead of T...,https://www.bbc.co.uk/news/articles/c8vgyzn2d3...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)