## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-16-49-56 +0000,nyt,Tell Us How You Observe Yom Kippur,https://www.nytimes.com/2026/09/02/us/observe-...
1,2026-09-02-16-49-00 +0000,bbc,EU and Nato vow to step up pressure on Russia ...,https://www.bbc.co.uk/news/articles/ce9e810pg7...
2,2026-09-02-16-48-43 +0000,nyt,Two More Oil Tankers Are Attacked in the Strai...,https://www.nytimes.com/2026/09/01/business/sh...
3,2026-09-02-16-42-48 +0000,nypost,Manhunt for Georgia cop killer after he ‘targe...,https://nypost.com/2026/09/02/us-news/manhunt-...
4,2026-09-02-16-40-00 +0000,wsj,Opinion | The Navy’s Overstretched Carrier Fleet,https://www.wsj.com/opinion/the-navys-overstre...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2458/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
243  trump     30
184   iran     22
217  house     20
256   will     19
12     new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
70,2026-09-02-14-55-45 +0000,nypost,Dramatic video shows US strikes raining on Ira...,https://nypost.com/2026/09/02/us-news/dramatic...,105
258,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,96
352,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...,95
362,2026-09-01-21-04-00 +0000,wsj,"U.S. Stocks Fall as Oil, Bond Yields Spike, U....",https://www.wsj.com/finance/investing/u-s-stoc...,90
257,2026-09-02-01-32-24 +0000,bbc,Apple Maps renames Lake Ontario as Lake Americ...,https://www.bbc.co.uk/news/articles/cddvyyz0e4...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
70,105,2026-09-02-14-55-45 +0000,nypost,Dramatic video shows US strikes raining on Ira...,https://nypost.com/2026/09/02/us-news/dramatic...
400,75,2026-09-01-18-51-00 +0000,wsj,A Fed governor says the central bank should ac...,https://www.wsj.com/economy/central-banking/a-...
247,73,2026-09-02-02-31-16 +0000,nyt,Former Biden White House Aide Wins Massachuset...,https://www.nytimes.com/2026/09/01/us/politics...
251,72,2026-09-02-01-59-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
258,66,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
288,60,2026-09-01-23-50-56 +0000,cbc,"Apple Maps follows Google, changes name of Lak...",https://www.cbc.ca/news/world/apple-maps-lake-...
401,59,2026-09-01-18-51-00 +0000,wsj,U.S. Stocks Fall as Oil Surges After New Middl...,https://www.wsj.com/finance/investing/u-s-stoc...
358,56,2026-09-01-21-08-16 +0000,wapo,Bessent downplays bond market concerns amid gl...,https://www.washingtonpost.com/business/2026/0...
171,52,2026-09-02-10-00-00 +0000,startribune,Reusse: Kyler Murray will be fine. Here’s what...,https://www.startribune.com/minnesota-vikings-...
311,51,2026-09-01-22-56-00 +0000,wsj,The House voted overwhelmingly to censure Rep....,https://www.wsj.com/politics/chuck-edwards-hou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)