## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-09-14-59-23 +0000,nyt,Live Updates: Human Rights Lawyer Navi Pillay ...,https://www.nytimes.com/live/2026/10/09/world/...
1,2026-10-09-14-58-45 +0000,nyt,Palestinian Authority Says Elections Are to Be...,https://www.nytimes.com/2026/10/09/world/middl...
2,2026-10-09-14-56-54 +0000,nyt,Trump Announces White House Inquiry Into Fed G...,https://www.nytimes.com/2026/10/09/business/tr...
3,2026-10-09-14-53-49 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/09/world/...
4,2026-10-09-14-53-11 +0000,cbc,Judge orders U.S. government to return Arizona...,https://www.cbc.ca/news/world/us-deportation-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
15   trump     41
41     new     26
10   prize     18
8    nobel     17
417   will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
316,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...,144
305,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...,143
36,2026-10-09-14-13-06 +0000,nypost,Stocks rise as tech shares rebound on SpaceX d...,https://nypost.com/2026/10/09/business/stocks-...,133
220,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...,123
399,2026-10-08-17-30-00 +0000,wapo,No new attack on Iran before the midterm elect...,https://www.washingtonpost.com/politics/2026/1...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
316,144,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...
220,123,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...
174,102,2026-10-09-09-08-51 +0000,nypost,Former UN human rights chief Navanethem ‘Navi...,https://nypost.com/2026/10/09/world-news/navan...
305,102,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...
59,62,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
374,62,2026-10-08-18-38-59 +0000,nypost,Gavin Newsom weighs taking 563 inmates off dea...,https://nypost.com/2026/10/08/us-news/gavin-ne...
476,51,2026-10-08-15-02-36 +0000,wapo,Search warrants against former prince Andrew w...,https://www.washingtonpost.com/world/2026/10/0...
228,50,2026-10-09-02-12-58 +0000,missionlocal,‘Necesitamos un jingle’: ¿Sabrán los votantes ...,https://missionlocal.org/2026/10/california-bi...
405,47,2026-10-08-17-25-00 +0000,wsj,With affordability emerging as a top issue for...,https://www.wsj.com/politics/elections/conserv...
36,47,2026-10-09-14-13-06 +0000,nypost,Stocks rise as tech shares rebound on SpaceX d...,https://nypost.com/2026/10/09/business/stocks-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)