## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-17-05-37-34 +0000,nyt,Live Updates: Lebanon-Israel Cease-Fire Goes I...,https://www.nytimes.com/live/2026/04/16/world/...
1,2026-04-17-05-34-48 +0000,bbc,What we know about the ceasefire between Leban...,https://www.bbc.com/news/articles/cwy32277e58o...
2,2026-04-17-05-33-53 +0000,startribune,"Live: Napheesa Collier receives one-year, $1.4...",https://www.startribune.com/minnesota-lynx-wnb...
3,2026-04-17-05-27-41 +0000,bbc,Singer D4vd arrested on suspicion of murdering...,https://www.bbc.com/news/articles/c20d22ev21wo...
4,2026-04-17-05-21-57 +0000,nypost,"Boy, 13, stabbed with large knife during suspe...",https://nypost.com/2026/04/17/us-news/boy-13-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3256/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41   trump     43
46    iran     40
71     war     24
145    ice     12
224  house     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,135
168,2026-04-16-19-34-42 +0000,nyt,House Again Thwarts Challenge to Trump’s Autho...,https://www.nytimes.com/2026/04/16/us/politics...,123
125,2026-04-16-21-10-00 +0000,wsj,"Nearly two months into the Iran war, Republica...",https://www.wsj.com/politics/gop-anxiety-iran-...,120
331,2026-04-16-09-04-25 +0000,nyt,"Jesus Memes, Threats and a War in Iran: A Port...",https://www.nytimes.com/2026/04/16/us/politics...,118
291,2026-04-16-12-35-29 +0000,nyt,"Trump Breaks With Meloni, Italy’s Leader, Amid...",https://www.nytimes.com/2026/04/15/world/europ...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,135,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...
139,62,2026-04-16-20-48-00 +0000,wsj,President Trump says he will nominate Dr. Eric...,https://www.wsj.com/politics/policy/trump-says...
327,60,2026-04-16-09-09-00 +0000,wsj,Rep. Eric Swalwell of California earned endors...,https://www.wsj.com/politics/elections/swalwel...
81,54,2026-04-16-22-40-18 +0000,nyt,10-Day Cease-Fire Between Israel and Lebanon G...,https://www.nytimes.com/2026/04/16/world/middl...
155,54,2026-04-16-20-12-23 +0000,startribune,ICE agent charged with two felonies for allege...,https://www.startribune.com/ice-agent-charged-...
26,50,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
173,43,2026-04-16-19-19-07 +0000,bbc,"Europe has 'maybe six weeks of jet fuel left',...",https://www.bbc.com/news/articles/czjw2kz0l22o...
178,42,2026-04-16-19-04-00 +0000,wsj,Former Virginia Lt. Gov. Justin Fairfax Kills ...,https://www.wsj.com/us-news/former-virginia-lt...
270,38,2026-04-16-14-15-08 +0000,nypost,Pope Leo decries world ‘ravaged by tyrants’ am...,https://nypost.com/2026/04/16/world-news/pope-...
147,38,2026-04-16-20-28-15 +0000,latimes,Netflix co-founder Reed Hastings to leave the ...,https://www.latimes.com/entertainment-arts/bus...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)