## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-14-06-32-00 +0000,wsj,FedEx Overtakes UPS as the New King of Delivery,https://www.wsj.com/business/logistics/fedex-o...
1,2026-03-14-06-32-00 +0000,wsj,Opinion | Advice to Trump: Leave the Oil Marke...,https://www.wsj.com/opinion/advice-to-trump-le...
2,2026-03-14-06-32-00 +0000,wsj,Traders Tell Us How They’re Dealing With the F...,https://www.wsj.com/finance/markets-oil-iran-t...
3,2026-03-14-06-32-00 +0000,wsj,"Opinion | Carter, the Iran Hostages and a Tens...",https://www.wsj.com/opinion/carter-the-iran-ho...
4,2026-03-14-06-32-00 +0000,wsj,Opinion | You Can’t Duck and Cover From the Mu...,https://www.wsj.com/opinion/you-cant-duck-and-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
19   iran     54
7   trump     46
17    war     40
9     oil     29
3     new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-03-14-05-28-40 +0000,nyt,Israel-Iran Conflict: U.S. Military Attacks Ir...,https://www.nytimes.com/live/2026/03/13/world/...,209
48,2026-03-14-00-57-55 +0000,latimes,Trump administration orders restart of oil dri...,https://www.latimes.com/california/story/2026-...,196
47,2026-03-14-01-00-00 +0000,wsj,Trump Knew the Risk of Iran Blocking the Strai...,https://www.wsj.com/politics/national-security...,162
218,2026-03-13-17-09-48 +0000,nypost,Trump says US seizing Kharg Island ‘not high o...,https://nypost.com/2026/03/13/us-news/trump-sa...,160
34,2026-03-14-01-53-54 +0000,wapo,"Trump says U.S. bombed Kharg Island, striking ...",https://www.washingtonpost.com/politics/2026/0...,158

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,209,2026-03-14-05-28-40 +0000,nyt,Israel-Iran Conflict: U.S. Military Attacks Ir...,https://www.nytimes.com/live/2026/03/13/world/...
353,86,2026-03-13-08-45-00 +0000,wsj,German Chemical Industry Warns of Supply-Chain...,https://www.wsj.com/world/europe/german-chemic...
282,63,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
214,50,2026-03-13-17-16-00 +0000,bbc,"New US trade probe targets EU, Canada, UK over...",https://www.bbc.com/news/articles/cgrzvdqze5xo...
168,49,2026-03-13-19-50-01 +0000,nypost,"Pentagon sending assault ship, at least 2,500 ...",https://nypost.com/2026/03/13/us-news/pentagon...
169,43,2026-03-13-19-47-21 +0000,nypost,Pirro slams ‘activist judge’ for blocking DOJ ...,https://nypost.com/2026/03/13/us-news/federal-...
342,39,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
237,37,2026-03-13-16-06-47 +0000,nypost,"Stocks fall, oil holds above $100 after tempor...",https://nypost.com/2026/03/13/business/stocks-...
315,37,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
13,32,2026-03-14-04-37-23 +0000,nypost,Psycho teen accused of fatally stabbing ICU nu...,https://nypost.com/2026/03/14/us-news/massachu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)