## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-01-24-29 +0000,nypost,Vaccine expert lusted after Northwell Health s...,https://nypost.com/2026/06/06/us-news/vaccine-...
1,2026-06-07-01-16-24 +0000,nypost,Here are the best NYC bars to watch the ‘beaut...,https://nypost.com/2026/06/06/us-news/the-best...
2,2026-06-07-01-03-25 +0000,bbc,Multiple people shot near festival in Ohio wit...,https://www.bbc.com/news/articles/c4gyqzkgwn2o...
3,2026-06-07-01-00-00 +0000,wsj,The Cattle Empire That Turned Out to Be a Gian...,https://www.wsj.com/finance/cattle-empire-ponz...
4,2026-06-07-01-00-00 +0000,wsj,"When Trump Jawbones the Market, Bet Against Hi...",https://www.wsj.com/economy/when-trump-jawbone...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
40    trump     16
21    world     15
22      cup     12
295    iran      9
195  killed      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
21,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...,64
112,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...,60
1,2026-06-07-01-16-24 +0000,nypost,Here are the best NYC bars to watch the ‘beaut...,https://nypost.com/2026/06/06/us-news/the-best...,51
68,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,48
36,2026-06-06-22-38-36 +0000,bbc,Iran says staff blocked from entering US after...,https://www.bbc.com/news/articles/cy8286nqz87o...,44

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
21,64,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
112,54,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...
107,36,2026-06-06-12-27-17 +0000,cbc,"Palestinian baby killed, parents hurt in Israe...",https://www.cbc.ca/news/world/israeli-palestin...
178,33,2026-06-06-01-57-00 +0000,wsj,Steve Hilton mounts unlikely California govern...,https://www.wsj.com/politics/elections/the-bri...
141,30,2026-06-06-09-14-00 +0000,wsj,Mass Ukrainian Drone Strikes Target Russian Mi...,https://www.wsj.com/world/russia/mass-ukrainia...
88,26,2026-06-06-15-00-45 +0000,nypost,"Bernadette Chirac, France’s former first lady ...",https://nypost.com/2026/06/06/world-news/berna...
166,24,2026-06-06-04-22-25 +0000,bbc,Canada bans Texas cattle over flesh-eating scr...,https://www.bbc.com/news/articles/cevpv3r7jmpo...
97,24,2026-06-06-13-49-03 +0000,nyt,"Israeli Strike Kills 3 Lebanese Soldiers, Days...",https://www.nytimes.com/2026/06/06/world/middl...
7,23,2026-06-07-00-56-06 +0000,nypost,Pete Hegseth warns of boat migrants and ‘dange...,https://nypost.com/2026/06/06/world-news/pete-...
58,23,2026-06-06-19-59-13 +0000,nypost,‘Complete hypocrite:’ Mamdani-backed Congress ...,https://nypost.com/2026/06/06/us-news/complete...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)