## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-21-18-58-22 +0000,nyt,Russia Releases American Stephen Hubbard From ...,https://www.nytimes.com/2026/10/21/us/politics...
1,2026-10-21-18-56-31 +0000,nypost,China skeptics raise alarm over Hochul’s plan ...,https://nypost.com/2026/10/21/us-news/china-sk...
2,2026-10-21-18-56-12 +0000,chitri,Ed Soliday faces two challengers for House Dis...,https://www.chicagotribune.com/2026/10/21/soli...
3,2026-10-21-18-55-03 +0000,chitri,Meta ordered to pay New Mexico $25 billion for...,https://www.chicagotribune.com/2026/10/21/meta...
4,2026-10-21-18-54-12 +0000,nyt,A.I. Discovered a Critical Security Flaw Under...,https://www.nytimes.com/2026/10/21/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2450/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
96        trump     43
33          new     34
113  california     16
0        russia     14
139      spacex     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
39,2026-10-21-17-59-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...,120
400,2026-10-20-19-40-00 +0000,wsj,Trump announced a new program that will pay pe...,https://www.wsj.com/politics/policy/trump-to-o...,120
299,2026-10-21-01-37-00 +0000,wsj,President Trump is relying on a new strategy t...,https://www.wsj.com/politics/elections/trump-m...,114
246,2026-10-21-09-03-22 +0000,nyt,Trump Approval Hits New Low Two Weeks Before M...,https://www.nytimes.com/2026/10/21/us/politics...,110
142,2026-10-21-14-47-00 +0000,wsj,President Trump said he is requiring companies...,https://www.wsj.com/politics/policy/trump-says...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
39,120,2026-10-21-17-59-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...
51,93,2026-10-21-17-46-09 +0000,bbc,US citizen Stephen Hubbard freed by Russia as ...,https://www.bbc.co.uk/news/articles/c6m24l9v37...
42,76,2026-10-21-17-57-00 +0000,wsj,An ad featuring Amy Acton’s estranged mother a...,https://www.wsj.com/politics/elections/ohio-go...
415,68,2026-10-20-19-01-56 +0000,cbc,No Canada-U.S. trade deal expected before Amer...,https://www.cbc.ca/news/politics/carney-trump-...
334,68,2026-10-20-22-42-43 +0000,nypost,SpaceX stock soars on blowout earnings that se...,https://nypost.com/2026/10/20/business/spacex-...
22,54,2026-10-21-18-24-00 +0000,wsj,Meta Ordered to Pay $25 Billion to New Mexico ...,https://www.wsj.com/tech/meta-ordered-to-pay-2...
291,48,2026-10-21-02-50-16 +0000,latimes,Your guide to the L.A. County Superior Court J...,https://www.latimes.com/california/story/2026-...
230,48,2026-10-21-10-00-00 +0000,nypost,Todd Blanche tells ‘Pod Force One’ Ilhan Omar ...,https://nypost.com/2026/10/21/us-news/todd-bla...
186,47,2026-10-21-12-44-00 +0000,wsj,Minnesota’s Democratic U.S. Senate nominee Peg...,https://www.wsj.com/politics/policy/minnesotas...
329,44,2026-10-20-22-53-44 +0000,nypost,Elon Musk chose to throttle Ukraine’s access t...,https://nypost.com/2026/10/20/world-news/elon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)