## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-03-14-45-29 +0000,nypost,"Nauru, the world’s third-smallest country, cha...",https://nypost.com/2026/08/03/world-news/nauru...
1,2026-08-03-14-44-49 +0000,nyt,Here’s Why the US Is Helping Prop Up the Japan...,https://www.nytimes.com/2026/08/03/business/us...
2,2026-08-03-14-44-41 +0000,nypost,Teen’s three-word joke turns his life upside-d...,https://nypost.com/2026/08/03/us-news/teen-wro...
3,2026-08-03-14-42-16 +0000,nyt,Spokane Wildfires Destroy Hundreds of Building...,https://www.nytimes.com/2026/08/02/us/spokane-...
4,2026-08-03-14-40-06 +0000,startribune,GOP holdouts say they will vote to advance Bla...,https://www.startribune.com/blanche-rescinds-f...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2569/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
114  trump     28
117   iran     19
116    new     14
119  talks     13
138    out     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
262,2026-08-02-15-40-24 +0000,chitri,President Trump says he will order halt to Ira...,https://www.chicagotribune.com/2026/08/02/trum...,97
188,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...,96
73,2026-08-03-11-20-12 +0000,nypost,Iran denies Trump claim new peace talks planne...,https://nypost.com/2026/08/03/world-news/iran-...,95
29,2026-08-03-13-38-30 +0000,chitri,President Donald Trump claims Iran talks will ...,https://www.chicagotribune.com/2026/08/03/trum...,94
13,2026-08-03-14-20-54 +0000,nypost,"Dow soars 500 points, oil slides over 5% after...",https://nypost.com/2026/08/03/business/dow-soa...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
262,97,2026-08-02-15-40-24 +0000,chitri,President Trump says he will order halt to Ira...,https://www.chicagotribune.com/2026/08/02/trum...
62,69,2026-08-03-12-09-00 +0000,wsj,Acting Attorney General Todd Blanche said he f...,https://www.wsj.com/politics/policy/blanche-fo...
217,65,2026-08-02-19-02-00 +0000,wsj,"Sen. Bernie Moreno says his former son-in-law,...",https://www.wsj.com/politics/elections/domesti...
188,49,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...
255,45,2026-08-02-16-00-00 +0000,wsj,Trump said he wants a Qatari-donated jet used ...,https://www.wsj.com/politics/national-security...
185,38,2026-08-02-23-39-00 +0000,wsj,California Democrats endorse a proposed billio...,https://www.wsj.com/politics/policy/california...
161,37,2026-08-03-03-32-21 +0000,bbc,'My only son was shot standing up for justice'...,https://www.bbc.co.uk/news/articles/c5yvqk69en...
138,36,2026-08-03-07-58-14 +0000,wsj,"Stock Market Today: Stocks Rally, Oil Slides o...",https://www.wsj.com/livecoverage/stock-market-...
243,33,2026-08-02-17-00-00 +0000,wsj,Cori Bush is trying to overcome millions in sp...,https://www.wsj.com/politics/elections/cori-bu...
261,32,2026-08-02-15-40-34 +0000,nypost,Horror moment 2 firefighting helicopters colli...,https://nypost.com/2026/08/02/world-news/horro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)