## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-16-17-14-09 +0000,nyt,How a Nature Cruise Turned Into a Nightmare,https://www.nytimes.com/2026/05/16/world/europ...
1,2026-05-16-17-05-20 +0000,nypost,Exotic snakes surprise officers chasing slithe...,https://nypost.com/2026/05/16/us-news/exotic-s...
2,2026-05-16-17-01-53 +0000,bbc,Taiwan insists it is independent after Trump w...,https://www.bbc.com/news/articles/cx2132w81jqo...
3,2026-05-16-17-01-36 +0000,nyt,"Rival Protests Take Place in London, With a Ma...",https://www.nytimes.com/2026/05/16/world/europ...
4,2026-05-16-17-01-28 +0000,bbc,Whale found dead near Danish island after Germ...,https://www.bbc.com/news/articles/c1l28lql137o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2658/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
17    trump     34
133     new     19
47    china     18
79     iran     14
198  leader     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
215,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,89
26,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,80
111,2026-05-16-03-55-42 +0000,nypost,US and Nigerian forces kill top ISIS leader hi...,https://nypost.com/2026/05/15/us-news/us-and-n...,79
51,2026-05-16-14-42-43 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...,78
6,2026-05-16-17-01-10 +0000,nyt,Trump Calls Xi a ‘Friend.’ But He Left China W...,https://www.nytimes.com/2026/05/16/world/europ...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
215,89,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
129,56,2026-05-16-00-48-07 +0000,nyt,Supreme Court Rejects Virginia Democrats’ Effo...,https://www.nytimes.com/2026/05/15/us/politics...
178,53,2026-05-15-21-29-00 +0000,wsj,Elon Musk’s SpaceX aims to go public on June 1...,https://www.wsj.com/economy/central-banking/sp...
26,46,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...
113,38,2026-05-16-03-07-33 +0000,nypost,"Eric Trump accuses Jen Psaki, MS NOW of airing...",https://nypost.com/2026/05/15/us-news/eric-tru...
204,32,2026-05-15-20-30-00 +0000,wsj,Republican and Democratic lawmakers on Friday ...,https://www.wsj.com/politics/national-security...
160,29,2026-05-15-22-15-25 +0000,nyt,"Tina Peters, Colorado Election Denier, Will Be...",https://www.nytimes.com/2026/05/15/us/politics...
221,29,2026-05-15-19-51-00 +0000,wsj,So You Think You Own Shares in a Hot Startup? ...,https://www.wsj.com/finance/investing/so-you-t...
13,28,2026-05-16-16-42-27 +0000,nypost,Terror not ruled out as nearly a dozen injured...,https://nypost.com/2026/05/16/world-news/many-...
117,28,2026-05-16-02-06-00 +0000,wsj,With under six months to go before the midterm...,https://www.wsj.com/politics/elections/trump-r...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)