## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-00-07-49 +0000,nyt,Long-Term Energy Crisis Looms as Trump Says Tr...,https://www.nytimes.com/live/2026/05/11/world/...
1,2026-05-12-00-07-11 +0000,cbc,Trump administration asks trade court to pause...,https://www.cbc.ca/news/world/trump-administra...
2,2026-05-12-00-03-41 +0000,nyt,"After Capturing Maduro, Trump Celebrated Victo...",https://www.nytimes.com/2026/05/10/world/ameri...
3,2026-05-12-00-03-27 +0000,nypost,UAE launched secret counter-strike against Ira...,https://nypost.com/2026/05/11/world-news/uae-l...
4,2026-05-12-00-02-58 +0000,bbc,China should stop hoarding food and fertiliser...,https://www.bbc.com/news/articles/cwy2rnyg50zo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2660/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
4         trump     44
29         iran     22
60   hantavirus     19
84          new     17
235         out     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
21,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,121
72,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,107
194,2026-05-11-16-10-02 +0000,nypost,Trump says Iran cease-fire ‘on life support’ —...,https://nypost.com/2026/05/11/us-news/trump-sa...,104
162,2026-05-11-17-55-01 +0000,startribune,Trump says Iran ceasefire is on 'life support'...,https://www.startribune.com/iran-and-the-us-ar...,102
315,2026-05-11-01-55-13 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
21,121,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
180,75,2026-05-11-16-39-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
156,72,2026-05-11-18-21-50 +0000,nypost,Hantavirus cruise ship captain bids emotional ...,https://nypost.com/2026/05/11/world-news/hanta...
57,41,2026-05-11-22-15-38 +0000,nypost,"1-year-old killed, two other kids critically i...",https://nypost.com/2026/05/11/us-news/1-year-o...
61,40,2026-05-11-22-06-21 +0000,nypost,Meta planning to take their Ray-Ban Display gl...,https://nypost.com/2026/05/11/business/ai-take...
314,39,2026-05-11-02-00-00 +0000,wsj,Women are playing a bigger role in the America...,https://www.wsj.com/economy/jobs/jobs-men-empl...
182,37,2026-05-11-16-34-44 +0000,nypost,Elon Musk to join Trump in China for high-stak...,https://nypost.com/2026/05/11/us-news/elon-mus...
300,36,2026-05-11-07-53-53 +0000,bbc,BBC tests out England and Argentina's World Cu...,https://www.bbc.com/news/videos/clypw107dqzo?a...
3,35,2026-05-12-00-03-27 +0000,nypost,UAE launched secret counter-strike against Ira...,https://nypost.com/2026/05/11/world-news/uae-l...
119,34,2026-05-11-19-54-40 +0000,latimes,"Arcadia mayor, accused of being Chinese foreig...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)