## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-12-10-02-00 +0000,wsj,David Crowley’s Wisconsin Victory Beats Back a...,https://www.wsj.com/world/david-crowleys-wisco...
1,2026-08-12-10-01-00 +0000,wsj,Japanese Yen Stays Weak as Interventions Fail ...,https://www.wsj.com/finance/currencies/asian-c...
2,2026-08-12-10-00-01 +0000,wapo,Takeaways from the primaries in South Carolina...,https://www.washingtonpost.com/politics/2026/0...
3,2026-08-12-10-00-01 +0000,chitri,Nonprofit CEO appealed to Mayor Brandon Johnso...,https://www.chicagotribune.com/2026/08/12/accl...
4,2026-08-12-10-00-01 +0000,startribune,Tuesday's takeaways: No clear direction for Wi...,https://www.startribune.com/what-to-watch-tues...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2688/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
48        trump     58
86      primary     27
78          new     25
2     wisconsin     22
202  democratic     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
211,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...,193
150,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,176
81,2026-08-12-07-55-03 +0000,startribune,David Crowley wins Democratic primary for Wisc...,https://www.startribune.com/democratic-sociali...,131
42,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...,129
125,2026-08-12-03-34-56 +0000,nypost,Walz Lt. Gov. Peggy Flanagan wins Minnesota De...,https://nypost.com/2026/08/11/us-news/tim-walz...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
211,193,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...
81,131,2026-08-12-07-55-03 +0000,startribune,David Crowley wins Democratic primary for Wisc...,https://www.startribune.com/democratic-sociali...
150,92,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...
147,73,2026-08-12-01-54-19 +0000,nypost,Former NFL sideline reporter Michele Tafoya sc...,https://nypost.com/2026/08/11/us-news/former-n...
139,58,2026-08-12-02-30-00 +0000,wsj,Sen. Darline Graham advanced to a runoff later...,https://www.wsj.com/politics/elections/sen-dar...
287,48,2026-08-11-19-27-17 +0000,bbc,Houthis reportedly kill six in first deadly at...,https://www.bbc.co.uk/news/articles/ckg9wpmzml...
177,44,2026-08-12-00-44-28 +0000,nyt,As Death Toll From Colombia Earthquake Rises t...,https://www.nytimes.com/2026/08/11/world/ameri...
318,44,2026-08-11-17-57-52 +0000,nypost,Michigan Dem Senate candidate Abdul El-Sayed s...,https://nypost.com/2026/08/11/us-news/michigan...
275,41,2026-08-11-20-17-28 +0000,chitri,Looking to see the solar eclipse from North Am...,https://www.chicagotribune.com/2026/08/11/sola...
346,40,2026-08-11-16-19-34 +0000,bbc,Watch: U's fans told house prices put players off,https://www.bbc.co.uk/news/videos/cwymddx1el3o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)