## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-29-20-55-55 +0000,nyt,Iran War Live Updates: Israel Vows to Seize Mo...,https://www.nytimes.com/live/2026/03/29/world/...
1,2026-03-29-20-54-53 +0000,nyt,Catholic Leaders Barred From Jerusalem Holy Si...,https://www.nytimes.com/2026/03/29/world/middl...
2,2026-03-29-20-54-13 +0000,nypost,Man stabbed to death steps from mobile NYC pot...,https://nypost.com/2026/03/29/us-news/man-stab...
3,2026-03-29-20-46-00 +0000,wsj,Zelensky Tours Bombarded Middle Eastern Countr...,https://www.wsj.com/world/zelensky-tours-bomba...
4,2026-03-29-20-43-00 +0000,wsj,How Long Before Airport Security Lines Go Back...,https://www.wsj.com/lifestyle/travel/how-long-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
58  trump     24
0    iran     19
49     no     15
1     war     15
50  kings     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
143,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...,80
49,2026-03-29-18-00-56 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,67
5,2026-03-29-20-42-32 +0000,bbc,No Kings protests draw large crowds to rally a...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...,66
74,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...,66
155,2026-03-28-23-24-03 +0000,startribune,The latest: Flagship ‘No Kings’ rally at the S...,https://www.startribune.com/live-flagship-no-k...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
143,80,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...
74,66,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...
83,42,2026-03-29-14-35-49 +0000,nypost,Air Canada flight attendant who was ejected du...,https://nypost.com/2026/03/29/world-news/air-c...
23,32,2026-03-29-19-49-54 +0000,nypost,LA’s homeless crisis hits shocking new low — h...,https://nypost.com/2026/03/29/us-news/las-home...
112,30,2026-03-29-09-30-00 +0000,wsj,Fed policymakers suggest interest rates could ...,https://www.wsj.com/economy/central-banking/fe...
158,28,2026-03-28-23-00-00 +0000,wsj,President Trump’s tax cuts are delivering bigg...,https://www.wsj.com/politics/policy/trump-salt...
105,28,2026-03-29-10-00-00 +0000,latimes,Barabak: Will or won't he? A lot rides on a Tr...,https://www.latimes.com/politics/story/2026-03...
153,26,2026-03-28-23-37-16 +0000,nypost,JD Vance wins 2028 CPAC GOP presidential straw...,https://nypost.com/2026/03/28/us-news/rubio-cu...
150,24,2026-03-29-00-00-00 +0000,wsj,Investigators searched the office of a FEMA co...,https://www.wsj.com/politics/national-security...
57,22,2026-03-29-17-35-43 +0000,nypost,Two India-flagged gas tankers crossing the Str...,https://nypost.com/2026/03/29/business/two-gas...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)