## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-14-10-25-00 +0000,wsj,Tower Semiconductor Shares Surge Premarket on ...,https://www.wsj.com/tech/tower-semiconductor-s...
1,2026-07-14-10-23-29 +0000,nyt,China Purges Top Official Over Corruption and ...,https://www.nytimes.com/2026/07/14/world/asia/...
2,2026-07-14-10-17-11 +0000,bbc,California leads lawsuit to block Paramount Wa...,https://www.bbc.co.uk/news/articles/cgev34lvgp...
3,2026-07-14-10-16-00 +0000,wsj,U.S. Small Business Confidence Improved in June,https://www.wsj.com/business/entrepreneurship/...
4,2026-07-14-10-13-59 +0000,bbc,South East Water must pay £30.5m for supply fa...,https://www.bbc.co.uk/news/articles/cevlvxgggx...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
109    trump     34
306     iran     29
744   graham     22
766  lindsey     19
380    death     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...,155
126,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...,129
290,2026-07-13-15-12-21 +0000,nypost,Sen. Lindsey Graham’s sister Darline reacts to...,https://nypost.com/2026/07/13/us-news/lindsey-...,121
154,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...,121
132,2026-07-13-23-27-44 +0000,nyt,Lindsey Graham’s Sister Appointed to Finish Hi...,https://www.nytimes.com/2026/07/13/us/politics...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,155,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...
154,87,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...
276,81,2026-07-13-16-10-10 +0000,nypost,California’s war on Paramount ramps up as stat...,https://nypost.com/2026/07/13/business/califor...
126,62,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...
40,51,2026-07-14-09-00-00 +0000,nypost,Gov. Kathy Hochul orders election year ‘pause’...,https://nypost.com/2026/07/14/us-news/hochul-o...
19,46,2026-07-14-09-47-59 +0000,nypost,Wife who held onto husband’s legs to stop him ...,https://nypost.com/2026/07/14/world-news/wife-...
251,43,2026-07-13-17-17-01 +0000,nypost,"Dow slides, oil rises to nearly $80 a barrel o...",https://nypost.com/2026/07/13/business/dow-sli...
167,42,2026-07-13-21-26-28 +0000,bbc,Ann Widdecombe suspect not known to Prevent as...,https://www.bbc.co.uk/news/articles/c0mydjl12m...
324,36,2026-07-13-11-45-36 +0000,cbc,"Europe recorded 10,000 excess deaths during la...",https://www.cbc.ca/news/science/europe-heat-ex...
9,35,2026-07-14-10-00-00 +0000,latimes,Arellano: Two Lorenzos from Mexico. One fulfil...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)