## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-09-18-55-24 +0000,nyt,Private Medicare Plans Are Raising Costs And F...,https://www.nytimes.com/2026/10/09/business/me...
1,2026-10-09-18-54-52 +0000,nyt,Some G.O.P. Lawmakers Pan Hegseth’s Plan to St...,https://www.nytimes.com/2026/10/09/us/politics...
2,2026-10-09-18-54-08 +0000,nyt,China and Europe Step Back From Trade War With...,https://www.nytimes.com/2026/10/09/business/ch...
3,2026-10-09-18-53-36 +0000,nypost,Flydubai co-pilot was inspired by 9/11 when he...,https://nypost.com/2026/10/09/world-news/flydu...
4,2026-10-09-18-53-18 +0000,wapo,ICE didn’t know 5-year-old boy was in car when...,https://www.washingtonpost.com/immigration/202...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
133  trump     36
8      new     25
165  prize     22
163  nobel     20
164  peace     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
113,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...,133
42,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...,130
378,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...,124
295,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...,122
388,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
113,133,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...
295,122,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...
378,88,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...
388,84,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...
155,67,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
300,60,2026-10-09-02-29-35 +0000,nypost,Outraged Susan Collins demands apology after r...,https://nypost.com/2026/10/08/us-news/susan-co...
303,54,2026-10-09-02-12-58 +0000,missionlocal,‘Necesitamos un jingle’: ¿Sabrán los votantes ...,https://missionlocal.org/2026/10/california-bi...
135,52,2026-10-09-14-30-42 +0000,nypost,Rubio slaps fresh sanctions on ‘rogue’ Interna...,https://nypost.com/2026/10/09/us-news/rubio-sl...
21,51,2026-10-09-18-28-00 +0000,wsj,President Trump has formed a committee to eval...,https://www.wsj.com/economy/central-banking/tr...
80,50,2026-10-09-16-29-36 +0000,nypost,Trump backs firing squad execution of Fort Hoo...,https://nypost.com/2026/10/09/us-news/trump-ba...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)