## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-15-01-17-59 +0000,nyt,Iran War Live Updates: U.S. Tells Citizens to ...,https://www.nytimes.com/live/2026/03/14/world/...
1,2026-03-15-01-17-57 +0000,nyt,F.C.C. Chair Threatens to Revoke Broadcasters’...,https://www.nytimes.com/2026/03/14/world/middl...
2,2026-03-15-01-11-47 +0000,startribune,"Live: Hopkins, Rosemount trade baskets in back...",https://www.startribune.com/mn-girls-basketbal...
3,2026-03-15-01-09-55 +0000,nypost,Chilling graffiti at San Jose State calls for ...,https://nypost.com/2026/03/14/us-news/antisemi...
4,2026-03-15-01-07-37 +0000,nyt,"For Trump, a Promised Economic Boom Collides W...",https://www.nytimes.com/2026/03/14/business/ec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     37
37    trump     31
1       war     28
334     oil     21
98   killed      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
30,2026-03-14-23-44-05 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...,111
209,2026-03-14-01-22-17 +0000,nyt,"U.S. Attacks Iran’s Kharg Island, a Key Port f...",https://www.nytimes.com/2026/03/13/world/middl...,111
95,2026-03-14-17-18-24 +0000,nypost,Lindsey Graham praises Trump’s ‘bold’ takeover...,https://nypost.com/2026/03/14/us-news/lindsey-...,110
102,2026-03-14-16-29-25 +0000,wapo,"Trump says U.S. struck Kharg Island, core of I...",https://www.washingtonpost.com/politics/2026/0...,110
47,2026-03-14-22-04-27 +0000,wapo,FCC chief threatens broadcasters as Trump crit...,https://www.washingtonpost.com/business/2026/0...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
30,111,2026-03-14-23-44-05 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...
159,55,2026-03-14-09-30-00 +0000,wsj,A slew of data released Friday portrayed an ec...,https://www.wsj.com/economy/oil-shock-hits-an-...
95,42,2026-03-14-17-18-24 +0000,nypost,Lindsey Graham praises Trump’s ‘bold’ takeover...,https://nypost.com/2026/03/14/us-news/lindsey-...
135,38,2026-03-14-12-00-00 +0000,latimes,Lopez: My promise to you: AI didn't write this...,https://www.latimes.com/california/story/2026-...
180,37,2026-03-14-08-00-00 +0000,cbc,Former NATO chief says he doesn't think allies...,https://www.cbc.ca/news/politics/nato-iran-isr...
139,33,2026-03-14-11-00-00 +0000,wsj,A court ruling throwing out a pair of criminal...,https://www.wsj.com/economy/central-banking/th...
123,32,2026-03-14-14-00-00 +0000,missionlocal,"New year, new cup and a taller ask for El Faro...",https://missionlocal.org/2026/03/new-year-new-...
0,30,2026-03-15-01-17-59 +0000,nyt,Iran War Live Updates: U.S. Tells Citizens to ...,https://www.nytimes.com/live/2026/03/14/world/...
26,29,2026-03-15-00-00-00 +0000,wsj,The AI boom has sparked a frenzied real-estate...,https://www.wsj.com/economy/housing/san-franci...
9,25,2026-03-15-00-56-27 +0000,nypost,"Twisted Missouri couple, wannabe Christian inf...",https://nypost.com/2026/03/14/us-news/missouri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)