## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-17-04-03 +0000,bbc,Petrol retailers in row with government over '...,https://www.bbc.com/news/articles/crk83e2g65no...
1,2026-03-13-17-00-00 +0000,startribune,With an obscure old video game and a livestrea...,https://www.startribune.com/with-an-obscure-ol...
2,2026-03-13-17-00-00 +0000,startribune,Anderson: Fleeing Iran after his father was ki...,https://www.startribune.com/anderson-fleeing-i...
3,2026-03-13-16-59-00 +0000,wsj,Stocks Mostly Lower as Oil Prices Rise Above $100,https://www.wsj.com/finance/investing/oil-hold...
4,2026-03-13-16-57-30 +0000,bbc,"Michigan synagogue attack was 'hate, plain and...",https://www.bbc.com/news/articles/cdxz0jpzk4do...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2503/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
18    iran     63
45     war     40
177  trump     30
32     oil     24
182    new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-03-13-16-53-13 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: H...,https://www.nytimes.com/live/2026/03/13/world/...,256
324,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,177
262,2026-03-13-01-32-01 +0000,nyt,Trump Removes Sanctions on Russia to Help Oil ...,https://www.nytimes.com/2026/03/12/us/politics...,156
29,2026-03-13-16-17-58 +0000,nyt,Trump-Iran Timeline: Key Moments Leading Up to...,https://www.nytimes.com/2026/03/13/us/politics...,156
376,2026-03-12-18-08-03 +0000,nyt,Fallout From Iran War and Oil Shock Deliver An...,https://www.nytimes.com/2026/03/12/business/ec...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,256,2026-03-13-16-53-13 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: H...,https://www.nytimes.com/live/2026/03/13/world/...
375,88,2026-03-12-18-14-00 +0000,wsj,When Kash Patel said in one of his first video...,https://www.wsj.com/politics/policy/ufc-fighte...
234,85,2026-03-13-05-07-14 +0000,nypost,Trump says Iran’s new Supreme Leader Mojtaba K...,https://nypost.com/2026/03/13/us-news/trump-sa...
104,74,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
189,61,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
74,47,2026-03-13-15-00-06 +0000,bbc,UK urges allies to keep up pressure on Russia ...,https://www.bbc.com/news/articles/cvg3yxd49xno...
157,41,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
86,41,2026-03-13-14-36-32 +0000,wapo,Trump administration allows for Russian oil sa...,https://www.washingtonpost.com/business/2026/0...
182,35,2026-03-13-10-00-00 +0000,nypost,Pentagon AI chief Emil Michael says it’s ‘tota...,https://nypost.com/2026/03/13/business/pentago...
253,33,2026-03-13-02-00-00 +0000,wsj,Illinois Gov. JB Pritzker’s deep financial inv...,https://www.wsj.com/politics/policy/illinois-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)