## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-18-26-06 +0000,startribune,"Dow drops 1,000 points as oil prices climb more",https://www.startribune.com/asian-shares-jump-...
1,2026-03-05-18-26-00 +0000,wsj,Victoria’s Secret Sales Recover But Shares Fal...,https://www.wsj.com/business/retail/victorias-...
2,2026-03-05-18-25-52 +0000,nypost,Feds bust LA’s most notorious ‘supergang’ in r...,https://nypost.com/2026/03/05/us-news/fbi-bust...
3,2026-03-05-18-25-03 +0000,bbc,UK firms pull fixed energy deals as Iran war p...,https://www.bbc.com/news/articles/c3ewwej0p13o...
4,2026-03-05-18-22-19 +0000,nypost,Mamdani moves to close NYC’s largest men’s hom...,https://nypost.com/2026/03/05/us-news/mamdani-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
33      iran     72
68     trump     41
34       war     38
63   iranian     22
94  conflict     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
326,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...,183
251,2026-03-05-05-07-22 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,170
313,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,169
321,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...,164
205,2026-03-05-10-03-58 +0000,nyt,Trump Wants a Quick Victory in Iran. But the W...,https://www.nytimes.com/2026/03/05/us/politics...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
326,183,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...
176,76,2026-03-05-11-59-14 +0000,nypost,"Declan Coady, youngest of six US soldiers kill...",https://nypost.com/2026/03/05/world-news/decla...
38,67,2026-03-05-17-43-48 +0000,nypost,California’s special oil blend threatens to dr...,https://nypost.com/2026/03/05/us-news/californ...
275,55,2026-03-05-02-15-00 +0000,wsj,"Sen. Steve Daines of Montana, a close ally of ...",https://www.wsj.com/politics/elections/trump-a...
321,54,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...
109,49,2026-03-05-15-34-18 +0000,nypost,"Trump goes off on ‘loser’ Spain, tells The Pos...",https://nypost.com/2026/03/05/us-news/trump-go...
330,44,2026-03-04-22-28-44 +0000,latimes,Top tech companies sign Trump's pledge to prov...,https://www.latimes.com/environment/story/2026...
136,43,2026-03-05-14-24-48 +0000,nyt,NATO’s chief downplays the risks that the alli...,https://www.nytimes.com/live/2026/03/05/world/...
32,42,2026-03-05-17-57-45 +0000,wapo,Live updates: Israel urges evacuation of south...,https://www.washingtonpost.com/world/2026/03/0...
252,38,2026-03-05-04-57-30 +0000,nyt,James Talarico Says ‘New Politics Is Being Bor...,https://www.nytimes.com/2026/03/04/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)