## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-07-03-39-56 +0000,nyt,Elisabeth Waldo Dies at 107; Fused Indigenous ...,https://www.nytimes.com/2026/04/06/arts/music/...
1,2026-04-07-03-38-56 +0000,nypost,Woman leaps into action to save struggling swi...,https://nypost.com/2026/04/06/us-news/woman-le...
2,2026-04-07-03-28-56 +0000,nyt,Iran War Live Updates: Trump Renews Threat of ...,https://www.nytimes.com/live/2026/04/06/world/...
3,2026-04-07-03-28-30 +0000,nypost,Audi driver in Orange County demands $55 in fr...,https://nypost.com/2026/04/06/us-news/driver-a...
4,2026-04-07-03-22-47 +0000,nyt,"Offset, Former Migos Rapper, Is Shot Outside F...",https://www.nytimes.com/2026/04/06/us/offset-m...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
23      trump     55
19       iran     49
20        war     21
266       new     15
78   deadline     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
221,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...,176
2,2026-04-07-03-28-56 +0000,nyt,Iran War Live Updates: Trump Renews Threat of ...,https://www.nytimes.com/live/2026/04/06/world/...,153
83,2026-04-06-21-55-50 +0000,bbc,Trump threatens to take out Iran in 'one night...,https://www.bbc.com/news/articles/cqj8ep9w1pno...,150
106,2026-04-06-21-03-16 +0000,wapo,Trump threatens new rampage as Iran deal deadl...,https://www.washingtonpost.com/national-securi...,149
144,2026-04-06-19-06-00 +0000,wsj,Crude Futures Edge Up As Trump’s Iran Deadline...,https://www.wsj.com/finance/commodities-future...,142

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
221,176,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...
227,84,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-annual...
251,55,2026-04-06-07-21-36 +0000,wsj,"Stock Market News, April 6, 2026: Stocks, Oil ...",https://www.wsj.com/livecoverage/stock-market-...
58,53,2026-04-06-23-24-00 +0000,wsj,A new Goldman Sachs report analyzing past tech...,https://www.wsj.com/economy/jobs/ai-displaced-...
204,42,2026-04-06-14-23-41 +0000,nypost,Supreme Court sets stage for DOJ to toss crimi...,https://nypost.com/2026/04/06/us-news/supreme-...
178,32,2026-04-06-16-48-58 +0000,nypost,Disgraced GOP Rep. Tony Gonzales sent lewd tex...,https://nypost.com/2026/04/06/us-news/disgrace...
183,31,2026-04-06-16-29-51 +0000,nypost,"Trump, first lady Melania tell children of Ira...",https://nypost.com/2026/04/06/us-news/trump-fi...
253,31,2026-04-06-06-33-20 +0000,nypost,Two top Iranian military leaders wiped out dur...,https://nypost.com/2026/04/06/world-news/us-is...
18,27,2026-04-07-02-11-02 +0000,nypost,ICE arrests ‘sicko’ illegal migrant accused of...,https://nypost.com/2026/04/06/us-news/ice-arre...
174,27,2026-04-06-17-00-00 +0000,latimes,$110-million donation seeks to address shortag...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)