## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-22-01-11-08 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/21/us/kan...
1,2026-10-22-01-07-55 +0000,nypost,Trump admin ending legal fight to overhaul stu...,https://nypost.com/2026/10/21/us-news/trump-ad...
2,2026-10-22-01-06-00 +0000,wsj,One Person Killed and 8 Injured in Airport Att...,https://www.wsj.com/world/middle-east/one-pers...
3,2026-10-22-01-03-26 +0000,nypost,Touching tribute to reporter killed in fiery c...,https://nypost.com/2026/10/21/us-news/chapman-...
4,2026-10-22-01-00-00 +0000,wsj,It Looks Like a Music Festival. It’s Really a ...,https://www.wsj.com/finance/investing/private-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
2     trump     33
152     new     27
199      he     16
155      ai     16
38   spacex     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
163,2026-10-21-19-25-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...,130
175,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...,104
394,2026-10-21-01-37-00 +0000,wsj,President Trump is relying on a new strategy t...,https://www.wsj.com/politics/elections/trump-m...,98
105,2026-10-21-21-11-00 +0000,wsj,President Trump said he is requiring companies...,https://www.wsj.com/politics/policy/trump-says...,96
72,2026-10-21-22-12-19 +0000,nypost,Meta stock surges on strong earnings report; t...,https://nypost.com/2026/10/21/business/meta-st...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
163,130,2026-10-21-19-25-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...
175,104,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...
127,76,2026-10-21-20-41-37 +0000,nypost,Tesla surprises Wall Street with lower-than-ex...,https://nypost.com/2026/10/21/business/elon-mu...
113,74,2026-10-21-21-03-00 +0000,wsj,An ad featuring Amy Acton’s estranged mother a...,https://www.wsj.com/politics/elections/ohio-go...
309,61,2026-10-21-11-40-03 +0000,cbc,U.S. envoy Witkoff meets with Putin in Russia ...,https://www.cbc.ca/news/world/russia-ukraine-w...
25,53,2026-10-21-23-59-30 +0000,nypost,Mike Rogers says Abdul El-Sayed is a national ...,https://nypost.com/2026/10/21/us-news/rogers-a...
162,52,2026-10-21-19-28-44 +0000,chitri,Pope Leo’s doctors say tests show he needs no ...,https://www.chicagotribune.com/2026/10/21/pope...
87,52,2026-10-21-21-37-00 +0000,wsj,Meta Ordered to Pay $25 Billion to New Mexico ...,https://www.wsj.com/tech/meta-ordered-to-pay-2...
387,48,2026-10-21-02-50-16 +0000,latimes,Your guide to the L.A. County Superior Court J...,https://www.latimes.com/california/story/2026-...
50,47,2026-10-21-23-02-13 +0000,nypost,Critically injured teacher blasted by Oregon s...,https://nypost.com/2026/10/21/us-news/teacher-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)