## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-21-01-17-18 +0000,nypost,Ex-teacher and Texas Senate candidate James Ta...,https://nypost.com/2026/03/20/us-news/ex-teach...
1,2026-03-21-01-12-24 +0000,nyt,How Geopolitics Threaten K-Pop’s Ambitions in ...,https://www.nytimes.com/2026/03/20/world/asia/...
2,2026-03-21-01-08-23 +0000,nyt,Iran War Live Updates: Trump Says U.S. Is Cons...,https://www.nytimes.com/live/2026/03/20/world/...
3,2026-03-21-01-08-21 +0000,nyt,U.S. Pauses Sanctions on Some Iranian Oil to G...,https://www.nytimes.com/2026/03/20/world/middl...
4,2026-03-21-01-05-03 +0000,bbc,Russia's school propaganda was highlighted by...,https://www.bbc.com/news/articles/c7vq5g64y98o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2614/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
19   iran     37
23  trump     36
20    war     22
47    new     15
29    oil     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-21-01-08-23 +0000,nyt,Iran War Live Updates: Trump Says U.S. Is Cons...,https://www.nytimes.com/live/2026/03/20/world/...,126
104,2026-03-20-20-27-24 +0000,nypost,"Trump vows no cease-fire with Iran, predicts S...",https://nypost.com/2026/03/20/world-news/trump...,113
248,2026-03-20-13-20-07 +0000,nypost,Saudi Arabia warns oil prices could spike past...,https://nypost.com/2026/03/20/business/saudi-a...,104
153,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...,103
285,2026-03-20-10-47-00 +0000,wsj,"In Nearly 90 Truth Social Posts, Trump Narrate...",https://www.wsj.com/politics/policy/in-nearly-...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,126,2026-03-21-01-08-23 +0000,nyt,Iran War Live Updates: Trump Says U.S. Is Cons...,https://www.nytimes.com/live/2026/03/20/world/...
29,71,2026-03-20-23-53-34 +0000,nypost,US pauses sanctions on Iranian oil ‘stranded a...,https://nypost.com/2026/03/20/us-news/us-pause...
153,60,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...
6,57,2026-03-21-01-00-00 +0000,wsj,Some Democrats on Capitol Hill are discussing ...,https://www.wsj.com/politics/policy/chuck-schu...
83,54,2026-03-20-21-03-18 +0000,nypost,University of Alabama student James Gracey was...,https://nypost.com/2026/03/20/world-news/unive...
18,41,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...
93,41,2026-03-20-20-49-57 +0000,latimes,California reaches proposed settlement with sc...,https://www.latimes.com/california/story/2026-...
190,40,2026-03-20-16-30-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
54,39,2026-03-20-22-17-10 +0000,nypost,Media veterans outraged as Bari Weiss shuts 10...,https://nypost.com/2026/03/20/media/media-vete...
291,39,2026-03-20-10-30-00 +0000,nypost,Are soaring beef prices busting your grocery b...,https://nypost.com/2026/03/20/lifestyle/soarin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)