## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-10-00-06-55 +0000,nypost,"Straphanger, 33, stabbed multiple times in NYC...",https://nypost.com/2026/05/09/us-news/straphan...
1,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
2,2026-05-09-23-50-13 +0000,nypost,CBS bows to pressure from Spencer Pratt over i...,https://nypost.com/2026/05/09/us-news/cbs-bows...
3,2026-05-09-23-46-26 +0000,nypost,Karen Bass called out for stunning mayoral deb...,https://nypost.com/2026/05/09/us-news/karen-ba...
4,2026-05-09-23-36-50 +0000,startribune,"Live from Game 3: Joel Eriksson Ek sidelined, ...",https://www.startribune.com/minnesota-wild-col...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2758/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
79      war     10
320     new     10
264  labour     10
154   trump     10
157    iran      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
166,2026-05-09-08-26-02 +0000,nypost,"Putin attends tiny WW2 victory parade, strippe...",https://nypost.com/2026/05/09/world-news/putin...,51
30,2026-05-09-21-21-22 +0000,nypost,Vladimir Putin suggests war in Ukraine is ‘com...,https://nypost.com/2026/05/09/world-news/vladi...,50
6,2026-05-09-23-10-03 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...,50
44,2026-05-09-20-03-22 +0000,nypost,Trump ready to ship US delegation to Moscow to...,https://nypost.com/2026/05/09/world-news/trump...,47
16,2026-05-09-22-22-08 +0000,nypost,Trump waits for answer from Iran on peace prop...,https://nypost.com/2026/05/09/world-news/trump...,42

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
166,51,2026-05-09-08-26-02 +0000,nypost,"Putin attends tiny WW2 victory parade, strippe...",https://nypost.com/2026/05/09/world-news/putin...
16,42,2026-05-09-22-22-08 +0000,nypost,Trump waits for answer from Iran on peace prop...,https://nypost.com/2026/05/09/world-news/trump...
194,41,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
124,37,2026-05-09-12-00-00 +0000,nypost,‘Patient Zero’ in deadly hantavirus cruise shi...,https://nypost.com/2026/05/09/world-news/hanta...
1,32,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
100,31,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
68,30,2026-05-09-16-30-54 +0000,bbc,SNP leader John Swinney rules out Holyrood tal...,https://www.bbc.com/news/articles/cddpevvv97jo...
116,30,2026-05-09-12-15-00 +0000,nypost,Ex-Olympics security boss warns Iranian ‘sleep...,https://nypost.com/2026/05/09/us-news/sleeper-...
13,25,2026-05-09-22-39-09 +0000,nypost,California school trustees in hot water for ‘O...,https://nypost.com/2026/05/09/us-news/temecula...
64,25,2026-05-09-17-28-59 +0000,bbc,'We just hit somebody' - Frontier Airlines pla...,https://www.bbc.com/news/articles/c5y95782wyko...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)