## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-06-05-46-00 +0000,wsj,Germany’s Merck KGaA Raises Outlook on Robust ...,https://www.wsj.com/business/earnings/germanys...
1,2026-08-06-05-44-00 +0000,wsj,Commerzbank CEO Calls For Dialogue With UniCredit,https://www.wsj.com/business/earnings/commerzb...
2,2026-08-06-05-37-51 +0000,nyt,Perez Hilton Is Hospitalized After Appearing t...,https://www.nytimes.com/2026/08/05/us/perez-hi...
3,2026-08-06-05-34-00 +0000,wsj,Deutsche Telekom Lifts Buyback by Up to $3.5 B...,https://www.wsj.com/business/earnings/deutsche...
4,2026-08-06-05-27-31 +0000,nypost,Wendy’s worker Thalles DeSouza accepted into Y...,https://nypost.com/2026/08/06/us-news/wendys-w...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2433/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
230     trump     30
592        el     26
587  michigan     25
57        new     24
593     sayed     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
164,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...,194
295,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...,165
80,2026-08-05-23-34-00 +0000,wsj,"Poll after poll had signaled Abdul El-Sayed, a...",https://www.wsj.com/politics/elections/pollste...,162
96,2026-08-05-22-49-05 +0000,nyt,Abdul El-Sayed Wins Democratic Senate Primary ...,https://www.nytimes.com/2026/08/05/us/politics...,156
269,2026-08-05-16-12-00 +0000,wsj,Progressive Abdul El-Sayed won the Michigan De...,https://www.wsj.com/politics/elections/michiga...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
164,194,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...
50,98,2026-08-06-01-00-00 +0000,wsj,President Trump has spoken repeatedly with Kev...,https://www.wsj.com/politics/policy/trump-has-...
294,71,2026-08-05-15-03-44 +0000,nypost,"Disney earnings boosted by ‘Toy Story 5’, them...",https://nypost.com/2026/08/05/business/disney-...
118,63,2026-08-05-21-58-00 +0000,wsj,The Senate confirmed Dr. Erica Schwartz as dir...,https://www.wsj.com/politics/policy/senate-con...
309,62,2026-08-05-14-15-00 +0000,wsj,Rep. Chuck Edwards said he wouldn’t seek re-el...,https://www.wsj.com/politics/elections/embattl...
316,52,2026-08-05-14-04-43 +0000,bbc,SpaceX shares sink after first earnings report...,https://www.bbc.co.uk/news/articles/c0qvpveg20...
388,49,2026-08-05-10-00-00 +0000,latimes,Energy company profits are soaring with the Ir...,https://www.latimes.com/environment/story/2026...
208,48,2026-08-05-19-14-31 +0000,chitri,No evidence? No problem. President Donald Trum...,https://www.chicagotribune.com/2026/08/05/trum...
28,45,2026-08-06-02-58-23 +0000,nypost,Meteor shower dubbed ‘the Perseids’ will follo...,https://nypost.com/2026/08/05/us-news/meteor-s...
276,42,2026-08-05-15-57-11 +0000,nypost,America’s most expensive rental market just go...,https://nypost.com/2026/08/05/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)