## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-02-46-10 +0000,nypost,Husband of US woman Lynette Hooker who went mi...,https://nypost.com/2026/04/09/us-news/husband-...
1,2026-04-10-02-42-00 +0000,wsj,Singapore Dollar Weakens Amid Fluctuating Mark...,https://www.wsj.com/finance/currencies/asian-c...
2,2026-04-10-02-40-06 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
3,2026-04-10-02-40-00 +0000,wsj,Brent-WTI Front-Month Spread Could Normalize I...,https://www.wsj.com/finance/commodities-future...
4,2026-04-10-02-32-27 +0000,bbc,White House staff told not to place bets on pr...,https://www.bbc.com/news/articles/cgld65x396go...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
99  trump     45
20   iran     42
37   fire     26
21    war     25
36  cease     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...,185
110,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,160
313,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,155
113,2026-04-09-21-51-17 +0000,nypost,"Trump goes off on ‘NUT JOBS’ Tucker Carlson, ...",https://nypost.com/2026/04/09/us-news/trump-go...,137
66,2026-04-09-23-11-02 +0000,nyt,"Amid Trump’s Threats, NATO Labors to Survive t...",https://www.nytimes.com/2026/04/09/us/politics...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,185,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...
156,84,2026-04-09-20-18-00 +0000,wsj,First lady Melania Trump denied having ties to...,https://www.wsj.com/politics/melania-trump-den...
2,82,2026-04-10-02-40-06 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
177,55,2026-04-09-19-17-15 +0000,nypost,Meta rolls out new AI model in ‘fundamental sh...,https://nypost.com/2026/04/09/business/meta-ro...
110,54,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
99,54,2026-04-09-22-16-15 +0000,latimes,Man was shot at by ICE agents in Northern Cali...,https://www.latimes.com/california/story/2026-...
95,46,2026-04-09-22-23-35 +0000,latimes,A sea turtle named Meatloaf is fighting to kee...,https://www.latimes.com/california/story/2026-...
75,46,2026-04-09-23-01-47 +0000,bbc,"Ceasefire or no ceasefire, the Middle East's r...",https://www.bbc.com/news/articles/cp3l4yk5rlgo...
230,38,2026-04-09-16-33-13 +0000,nypost,Supreme Court Justice Sonia Sotomayor claims c...,https://nypost.com/2026/04/09/us-news/supreme-...
153,36,2026-04-09-20-36-41 +0000,bbc,OpenAI pauses UK data centre deal over energy ...,https://www.bbc.com/news/articles/clyd032ej70o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)