## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-09-13-00 +0000,wsj,Eurozone Inflation Jumps as Iran War Cranks En...,https://www.wsj.com/economy/global/eurozone-in...
1,2026-03-31-09-12-40 +0000,nyt,A Cat-and-Mouse Game of Russian Internet Restr...,https://www.nytimes.com/2026/03/31/world/europ...
2,2026-03-31-09-12-17 +0000,nyt,Putin’s Internet Blackout: A Chaotic Drive to ...,https://www.nytimes.com/2026/03/31/world/europ...
3,2026-03-31-09-06-55 +0000,nyt,"Whoop, a Wearable Health Device Maker, Raises ...",https://www.nytimes.com/2026/03/31/business/de...
4,2026-03-31-09-04-24 +0000,nypost,Texas judge berates IT worker who helped him w...,https://nypost.com/2026/03/31/us-news/texas-ju...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
3     iran     44
44   trump     44
4      war     27
62     oil     24
6   energy     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
300,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...,156
188,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...,154
49,2026-03-31-07-09-00 +0000,wsj,Oil Ticks Higher After Trump Tells Aides He’s ...,https://www.wsj.com/finance/commodities-future...,133
68,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...,132
5,2026-03-31-09-04-05 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
300,156,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...
277,72,2026-03-30-15-51-00 +0000,wsj,Fed Chair Jerome Powell said the central bank ...,https://www.wsj.com/economy/central-banking/po...
68,58,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
330,54,2026-03-30-12-30-58 +0000,cbc,Air Canada CEO Michael Rousseau to retire late...,https://www.cbc.ca/news/business/air-canada-ce...
22,54,2026-03-31-08-50-05 +0000,cbc,U.S. attacks Iranian nuclear site as Tehran st...,https://www.cbc.ca/news/world/iran-u-s-conflic...
85,50,2026-03-31-02-20-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
94,40,2026-03-31-01-50-03 +0000,nypost,Disturbing video shows man get into police squ...,https://nypost.com/2026/03/30/us-news/video-sh...
26,33,2026-03-31-08-43-00 +0000,wsj,European Gas Prices Fall as Traders Weigh Pote...,https://www.wsj.com/opinion/european-gas-price...
287,33,2026-03-30-15-34-02 +0000,nypost,"Thieves snatch $10M worth of Renoir, Cézanne a...",https://nypost.com/2026/03/30/world-news/thiev...
224,31,2026-03-30-19-10-41 +0000,nypost,"While you endured hourslong travel nightmares,...",https://nypost.com/2026/03/30/us-news/lawmaker...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)