## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-14-56-37 +0000,startribune,Fury in California after Trump suggests Iran c...,https://www.startribune.com/fury-in-california...
1,2026-10-06-14-55-29 +0000,nyt,Live Updates: Protests Spread Across France as...,https://www.nytimes.com/live/2026/10/06/world/...
2,2026-10-06-14-55-29 +0000,nyt,"Short on Cash, Democrats Weigh Big Bets to Uns...",https://www.nytimes.com/2026/10/06/us/politics...
3,2026-10-06-14-55-28 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/06/world/...
4,2026-10-06-14-55-14 +0000,nypost,12 arrested in Vietnam after citywide cat meat...,https://nypost.com/2026/10/06/world-news/12-ar...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2458/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
2    trump     38
104    new     23
775     de     16
579    oil     13
262   dies     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
310,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,161
265,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,134
26,2026-10-06-14-15-06 +0000,bbc,White House defends Trump comment to let Iran ...,https://www.bbc.co.uk/news/articles/c6r7yn8pkn...,110
393,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,99
158,2026-10-06-10-00-00 +0000,wsj,"Disney’s top lawyer, Horacio Gutiérrez, is tak...",https://www.wsj.com/business/media/disneys-top...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
310,161,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
265,134,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
393,99,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
230,70,2026-10-06-04-18-00 +0000,nyt,Potential Iranian Drone Attack Led to Exit of ...,https://www.nytimes.com/2026/10/05/us/politics...
281,58,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
330,51,2026-10-05-20-42-19 +0000,bbc,Flávio Bolsonaro rides right-wing wave to win ...,https://www.bbc.co.uk/news/articles/cqj6je4jen...
29,46,2026-10-06-14-09-24 +0000,nypost,Terror suspect arrested charges in probe into ...,https://nypost.com/2026/10/06/world-news/uk-po...
262,44,2026-10-06-01-00-00 +0000,wsj,Republicans are binding their Senate hopes on ...,https://www.wsj.com/politics/elections/rjohn-s...
70,43,2026-10-06-12-59-44 +0000,cbc,"Police in France use tear gas, water cannons a...",https://www.cbc.ca/news/world/france-student-p...
452,41,2026-10-05-15-09-00 +0000,wsj,Paramount Names Leadership Team for Combined E...,https://www.wsj.com/business/media/paramount-n...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)