## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-16-40-18 +0000,nyt,Former Detroit Mayor Duggan Drops Out of Race ...,https://www.nytimes.com/2026/05/21/us/mike-dug...
1,2026-05-21-16-39-12 +0000,startribune,Live: Aimee Bock sentenced to more than 41 yea...,https://www.startribune.com/aimee-bock-sentenc...
2,2026-05-21-16-37-15 +0000,nyt,Uganda Restricts Travel with Congo Over Ebola ...,https://www.nytimes.com/2026/05/21/world/afric...
3,2026-05-21-16-34-27 +0000,nyt,2 Minnesota Autism Therapy Providers to Be Cha...,https://www.nytimes.com/2026/05/21/us/politics...
4,2026-05-21-16-34-13 +0000,startribune,RandBall: Timberwolves have plenty to learn fr...,https://www.startribune.com/minnesota-timberwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
39   trump     51
100    new     22
535   cuba     17
329   iran     15
127    was     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
295,2026-05-20-22-44-00 +0000,wsj,President Trump’s settlement with the IRS come...,https://www.wsj.com/politics/policy/trump-fami...,154
342,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...,129
277,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,124
71,2026-05-21-15-05-37 +0000,bbc,"Vanessa Trump, former wife of Donald Trump Jr,...",https://www.bbc.com/news/articles/c93xve8w4yyo...,114
49,2026-05-21-15-44-38 +0000,nyt,Trump’s Government Moves to Spare an Unhappy T...,https://www.nytimes.com/2026/05/20/us/politics...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
295,154,2026-05-20-22-44-00 +0000,wsj,President Trump’s settlement with the IRS come...,https://www.wsj.com/politics/policy/trump-fami...
167,86,2026-05-21-11-06-00 +0000,wsj,"Jeff Bezos wades into politics, and New York C...",https://www.wsj.com/politics/policy/bezos-wade...
277,73,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
350,64,2026-05-20-19-46-00 +0000,wsj,Federal Reserve officials all but retired the ...,https://www.wsj.com/economy/central-banking/fe...
339,54,2026-05-20-20-18-32 +0000,nypost,Feds probe suspicious oil trades worth $800M m...,https://nypost.com/2026/05/20/business/feds-pr...
53,54,2026-05-21-15-36-19 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...
223,51,2026-05-21-07-47-06 +0000,wsj,Stock Market Today: Tech-Stock Rebound Loses S...,https://www.wsj.com/livecoverage/stock-market-...
400,50,2026-05-20-17-11-00 +0000,wsj,The GOP-controlled House passed a new version ...,https://www.wsj.com/politics/policy/newly-pass...
293,45,2026-05-20-22-47-55 +0000,nypost,Elon Musk’s SpaceX readies for Wall Street bla...,https://nypost.com/2026/05/20/business/elon-mu...
280,44,2026-05-20-23-51-15 +0000,nypost,Socialist Seattle Mayor Katie Wilson walks bac...,https://nypost.com/2026/05/20/us-news/seattles...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)