## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-30-17-15-23 +0000,startribune,‘We’re all drowning’: Fraud allegations swamp ...,https://www.startribune.com/were-all-drowning-...
1,2026-04-30-17-14-35 +0000,nyt,Venice Biennale Jury Resigns Amid Tension Over...,https://www.nytimes.com/2026/04/30/arts/design...
2,2026-04-30-17-12-09 +0000,nyt,How the War in Iran is Affecting Africa’s Econ...,https://www.nytimes.com/2026/04/30/world/afric...
3,2026-04-30-17-11-00 +0000,wsj,President Trump is withdrawing his nomination ...,https://www.wsj.com/politics/policy/trump-with...
4,2026-04-30-17-10-51 +0000,nyt,House Passes Stalled Homeland Security Funding...,https://www.nytimes.com/2026/04/30/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
23   trump     40
16    iran     31
359    new     24
15     war     20
35   house     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
303,2026-04-29-22-40-00 +0000,wsj,In his first public testimony since the war in...,https://www.wsj.com/politics/national-security...,147
174,2026-04-30-10-43-45 +0000,nypost,Oil prices briefly hit wartime high as Trump w...,https://nypost.com/2026/04/30/us-news/oil-pric...,145
258,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...,137
120,2026-04-30-14-29-13 +0000,bbc,Oil price hits highest since 2022 after report...,https://www.bbc.com/news/articles/cx21m88rd14o...,132
19,2026-04-30-16-47-49 +0000,nypost,Fed’s preferred inflation gauge hits 3-year hi...,https://nypost.com/2026/04/30/business/feds-pr...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
303,147,2026-04-29-22-40-00 +0000,wsj,In his first public testimony since the war in...,https://www.wsj.com/politics/national-security...
258,137,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...
337,111,2026-04-29-21-26-00 +0000,wsj,"Powell said he’ll stay on the Fed board, the S...",https://www.wsj.com/politics/policy/powelland-...
165,102,2026-04-30-11-27-08 +0000,cbc,"Oil prices hit new wartime high before easing,...",https://www.cbc.ca/news/world/iran-war-oil-pri...
61,62,2026-04-30-16-00-00 +0000,wsj,The Justice Department is launching a West Coa...,https://www.wsj.com/politics/policy/doj-launch...
230,60,2026-04-30-05-00-04 +0000,bbc,'We will kill you and burn your house': Counci...,https://www.bbc.com/news/articles/cdxplq92rx1o...
309,55,2026-04-29-22-23-00 +0000,wsj,The Fed held rates steady; but in a contentiou...,https://www.wsj.com/economy/central-banking/fe...
360,53,2026-04-29-20-43-00 +0000,wsj,MGM Resorts Reports Lower First-Quarter Profit...,https://www.wsj.com/business/earnings/mgm-reso...
287,47,2026-04-29-23-27-51 +0000,nypost,Meta shares slide as tech giant hikes AI spend...,https://nypost.com/2026/04/29/business/meta-sh...
244,47,2026-04-30-02-53-37 +0000,cbc,Report into Bondi Beach mass shooting calls fo...,https://www.cbc.ca/news/world/bondi-beach-shoo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)