## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-23-12-00-31 +0000,missionlocal,People We Meet: Jeff Murray documents the Exce...,https://missionlocal.org/2026/05/people-we-mee...
1,2026-05-23-12-00-00 +0000,startribune,Souhan: The Vikings’ GM search should end with...,https://www.startribune.com/minnesota-vikings-...
2,2026-05-23-12-00-00 +0000,nypost,NYC DSA-backed Assembly candidate supports kee...,https://nypost.com/2026/05/23/us-news/nyc-dsa-...
3,2026-05-23-11-57-16 +0000,nyt,U.S. Ebola Travel Ban Faces Criticism From Con...,https://www.nytimes.com/2026/05/23/world/afric...
4,2026-05-23-11-55-39 +0000,bbc,Rubio meets Modi during India visit with energ...,https://www.bbc.com/news/articles/c87qrwyyrn2o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2401/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
159  trump     44
56     new     17
30   ebola     17
384   iran     14
28     out     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
112,2026-05-23-00-00-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,139
227,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...,136
190,2026-05-22-20-25-00 +0000,wsj,Tulsi Gabbard resigned as director of national...,https://www.wsj.com/politics/tulsi-gabbard-is-...,111
130,2026-05-22-23-06-58 +0000,nypost,Trump touts GOP backed-tax cuts for New Yorker...,https://nypost.com/2026/05/22/us-news/trump-to...,96
84,2026-05-23-02-44-15 +0000,nyt,Trump Weighs His Options in Carrying Out New S...,https://www.nytimes.com/2026/05/22/us/politics...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
112,139,2026-05-23-00-00-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...
227,76,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...
190,57,2026-05-22-20-25-00 +0000,wsj,Tulsi Gabbard resigned as director of national...,https://www.wsj.com/politics/tulsi-gabbard-is-...
255,56,2026-05-22-16-30-51 +0000,cbc,No Ebola cases in Canada and no new hantavirus...,https://www.cbc.ca/news/health/livestory/phac-...
273,53,2026-05-22-15-08-54 +0000,nypost,Dow soars 300 points to an all-time high — fir...,https://nypost.com/2026/05/22/business/dow-soa...
65,44,2026-05-23-06-04-46 +0000,cbc,Gas explosion at coal mine in China kills 82 p...,https://www.cbc.ca/news/world/gas-explosion-ch...
234,43,2026-05-22-17-43-00 +0000,wsj,Most green-card applicants will need to go abr...,https://www.wsj.com/politics/policy/trump-admi...
86,38,2026-05-23-02-37-57 +0000,cbc,"40,000 people under evacuation orders in Calif...",https://www.cbc.ca/news/world/california-chemi...
134,35,2026-05-22-22-47-45 +0000,cbc,911 audio reveals NASCAR's Kyle Busch was shor...,https://www.cbc.ca/sports/kyle-busch-death-fol...
130,35,2026-05-22-23-06-58 +0000,nypost,Trump touts GOP backed-tax cuts for New Yorker...,https://nypost.com/2026/05/22/us-news/trump-to...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)