## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-06-16-04 +0000,nypost,Texas woman pulled from sewage-filled ravine a...,https://nypost.com/2026/07/07/us-news/texas-wo...
1,2026-07-07-05-54-18 +0000,nypost,1985 cold case murder solved after Ohio suspec...,https://nypost.com/2026/07/07/us-news/1985-col...
2,2026-07-07-05-45-00 +0000,wsj,"U.S. Treasury Yields Rise, Curve Steepens Slig...",https://www.wsj.com/finance/investing/jgbs-mix...
3,2026-07-07-05-40-34 +0000,bbc,E-bike injury payouts top £110m and push up in...,https://www.bbc.co.uk/news/articles/c05y9pe5p1...
4,2026-07-07-05-38-18 +0000,nyt,At Least 15 Dead in China After Severe Floodin...,https://www.nytimes.com/2026/07/07/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
96   trump     47
99   world     22
105   nato     18
424     he     14
195   iran     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...,168
317,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...,127
43,2026-07-07-02-06-02 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,121
351,2026-07-06-09-00-11 +0000,nyt,Emil Bove Defended Trump in Court. Then Trump ...,https://www.nytimes.com/2026/07/06/us/emil-bov...,121
284,2026-07-06-14-21-08 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,168,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
63,83,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
211,65,2026-07-06-17-47-41 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
209,52,2026-07-06-17-57-00 +0000,wsj,Canada CPI Expectations Ramped Up Prior to U.S...,https://www.wsj.com/economy/central-banking/ca...
85,49,2026-07-06-23-10-21 +0000,nyt,New Videos of Charlie Kirk’s Killing Emerge in...,https://www.nytimes.com/2026/07/06/us/charlie-...
317,40,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...
31,39,2026-07-07-03-04-36 +0000,bbc,Top Democrats press Maine senate candidate to ...,https://www.bbc.co.uk/news/articles/cm2004nx8v...
306,39,2026-07-06-12-26-20 +0000,nyt,China Test Fires Long-Range Ballistic Missile ...,https://www.nytimes.com/2026/07/06/world/asia/...
208,38,2026-07-06-17-58-04 +0000,nypost,Father of teen found dead in suitcase issues d...,https://nypost.com/2026/07/06/world-news/fathe...
296,36,2026-07-06-13-25-13 +0000,nyt,"With $8 Billion in Venezuelan Oil Money, U.S. ...",https://www.nytimes.com/2026/07/06/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)