## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-25-22-54-40 +0000,chitri,Gov. JB Pritzker names new Illinois Prisoner R...,https://www.chicagotribune.com/2026/09/25/new-...
1,2026-09-25-22-51-30 +0000,nyt,Saudi Arabia Open to Possibly Developing Nucle...,https://www.nytimes.com/2026/09/25/us/politics...
2,2026-09-25-22-51-23 +0000,nypost,Bombshell new poll shows major shift in Califo...,https://nypost.com/2026/09/25/us-news/californ...
3,2026-09-25-22-49-04 +0000,nypost,Grandfather pummels brute convicted of murderi...,https://nypost.com/2026/09/25/us-news/grandfat...
4,2026-09-25-22-48-44 +0000,nyt,Supreme Court Once Again Blocks Republican-Bac...,https://www.nytimes.com/2026/09/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2414/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
168  trump     74
211     xi     32
4      new     24
39   court     20
202    was     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
165,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,178
147,2026-09-25-18-26-18 +0000,nypost,White House plays ‘Les Miserables’ hit censore...,https://nypost.com/2026/09/25/us-news/white-ho...,172
98,2026-09-25-20-02-20 +0000,nypost,Trump told China’s Xi that support for Iran wa...,https://nypost.com/2026/09/25/us-news/trump-to...,158
193,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...,157
278,2026-09-25-11-06-26 +0000,chitri,President Donald Trump’s state dinner for Xi J...,https://www.chicagotribune.com/2026/09/25/dona...,153

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
165,178,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...
193,83,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...
360,72,2026-09-25-02-29-00 +0000,wsj,New Jersey Gov. Mikie Sherrill has called for ...,https://www.wsj.com/politics/policy/new-jersey...
332,61,2026-09-25-08-52-23 +0000,wsj,Stock Market Today: Bond Yields Drop With Oil ...,https://www.wsj.com/livecoverage/stock-market-...
40,61,2026-09-25-21-16-59 +0000,bbc,Black woman found hanging from tree was dead b...,https://www.bbc.co.uk/news/articles/cwp933nzpp...
106,51,2026-09-25-19-42-00 +0000,wsj,Iran War Is Driving Up the Cost of Your Next O...,https://www.wsj.com/business/retail/iran-war-i...
143,47,2026-09-25-18-36-09 +0000,nypost,Costco to land in yet another California city ...,https://nypost.com/2026/09/25/business/new-nor...
128,47,2026-09-25-18-52-04 +0000,nypost,AI ‘doomer’ PR firm worked for Jacob Coxon as ...,https://nypost.com/2026/09/25/business/ai-doom...
281,47,2026-09-25-11-01-00 +0000,wsj,Chinese flags are waving everywhere in Washing...,https://www.wsj.com/politics/trump-xi-summit-g...
264,40,2026-09-25-12-40-02 +0000,chitri,Pope Leo XIV warns a ‘paradise of machines’ co...,https://www.chicagotribune.com/2026/09/25/pope...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)