## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-09-01-19-37 +0000,nyt,Latest on the Iran War: U.S. Fires on Tankers ...,https://www.nytimes.com/live/2026/05/08/world/...
1,2026-05-09-01-17-55 +0000,bbc,International cyber attack disrupts swathe of ...,https://www.bbc.com/news/articles/ce3pq0136eqo...
2,2026-05-09-01-02-43 +0000,latimes,Judge rejects no-jail plea in case of man who ...,https://www.latimes.com/california/story/2026-...
3,2026-05-09-01-02-28 +0000,bbc,What latest election results show us in maps a...,https://www.bbc.com/news/articles/c0ljrp76ywxo...
4,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
91        trump     36
1          iran     27
48          new     22
2           war     17
158  hantavirus     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,115
263,2026-05-08-13-12-34 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...,91
4,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...,91
90,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...,91
239,2026-05-08-14-37-00 +0000,wsj,Consumer Sentiment Falls to New Record Lows Am...,https://www.wsj.com/economy/consumers/consumer...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,115,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
90,91,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...
289,66,2026-05-08-11-43-45 +0000,nypost,UK PM Keir Starmer says he won’t resign after ...,https://nypost.com/2026/05/08/world-news/uk-pr...
4,62,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
191,62,2026-05-08-16-55-56 +0000,nyt,Health Officials Race to Track Hantavirus Crui...,https://www.nytimes.com/2026/05/07/world/europ...
56,43,2026-05-08-22-34-46 +0000,bbc,Reform election gains show historic shift in B...,https://www.bbc.com/news/articles/c0r255xlr59o...
156,41,2026-05-08-18-38-40 +0000,nypost,Trump announces three-day Ukraine-Russia cease...,https://nypost.com/2026/05/08/us-news/trump-an...
64,40,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...
18,39,2026-05-09-00-08-37 +0000,nypost,Tax hike on California employers spurs plea fo...,https://nypost.com/2026/05/08/us-news/tax-hike...
77,39,2026-05-08-21-54-51 +0000,wapo,U.S. strikes two Iranian-flagged vessels as te...,https://www.washingtonpost.com/national-securi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)