## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-04-01-05 +0000,nyt,Gallows Humor Provides Respite From Mideast Wars,https://www.nytimes.com/2026/04/29/world/middl...
1,2026-04-29-04-01-02 +0000,nyt,"Global Deforestation Slows, W.R.I. Report Find...",https://www.nytimes.com/2026/04/29/climate/wri...
2,2026-04-29-03-50-36 +0000,nypost,Legendary Lakers family matriarch makes max pa...,https://nypost.com/2026/04/28/us-news/lakers-j...
3,2026-04-29-03-32-52 +0000,nypost,Extremely rare piebald deer couple found roami...,https://nypost.com/2026/04/28/us-news/extremel...
4,2026-04-29-03-31-57 +0000,48hills,"Drama Masks: ‘Hamnet’ is gorgeous, but how was...",https://48hills.org/2026/04/drama-masks-hamnet...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2639/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
137    trump     57
96      iran     22
41      king     22
132  charles     17
260      new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
358,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,189
24,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...,149
379,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,142
264,2026-04-28-16-27-08 +0000,nypost,President Trump gives first lady Melania a pla...,https://nypost.com/2026/04/28/us-news/presiden...,134
30,2026-04-29-01-22-32 +0000,bbc,In pictures: King joins Trump for White House ...,https://www.bbc.com/news/articles/c86e6z26xdpo...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
358,189,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
313,113,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
24,86,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...
372,58,2026-04-28-10-00-00 +0000,latimes,Supreme Court will hear Trump's bid to end leg...,https://www.latimes.com/politics/story/2026-04...
221,50,2026-04-28-18-07-51 +0000,nypost,Ex-FBI Director James Comey indicted for threa...,https://nypost.com/2026/04/28/us-news/justice-...
302,48,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
89,47,2026-04-28-22-05-30 +0000,nypost,Musk kicks off explosive OpenAI trial by slamm...,https://nypost.com/2026/04/28/business/musk-ki...
40,44,2026-04-29-00-57-08 +0000,nypost,California’s high-speed rail now ‘worst proje...,https://nypost.com/2026/04/28/us-news/californ...
353,42,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...
383,38,2026-04-28-09-30-00 +0000,wsj,Federal Reserve officials are watching how the...,https://www.wsj.com/economy/central-banking/th...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)