## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-27-17-53-50 +0000,nypost,California kayaker is knocked into ocean by sh...,https://nypost.com/2026/10/27/us-news/californ...
1,2026-10-27-17-53-46 +0000,nypost,Dad kills mom before turning gun on himself in...,https://nypost.com/2026/10/27/us-news/dad-kill...
2,2026-10-27-17-53-09 +0000,nypost,Meta schemed ‘whisper strategy’ to discredit i...,https://nypost.com/2026/10/27/business/meta-sc...
3,2026-10-27-17-52-16 +0000,startribune,Trump claims cheating is the only way Tafoya c...,https://www.startribune.com/trump-claims-cheat...
4,2026-10-27-17-51-33 +0000,nypost,"Homeless mom shoots daughter, 2, in murder sui...",https://nypost.com/2026/10/27/us-news/homeless...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
34      trump     38
57   election     30
149    israel     18
176       new     16
246     first     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
354,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,111
294,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...,90
32,2026-10-27-16-49-33 +0000,nypost,"Trump, Rubio expected to greet first shipment ...",https://nypost.com/2026/10/27/us-news/trump-ru...,87
31,2026-10-27-16-51-20 +0000,nyt,Election Officials Fear Trump Administration’s...,https://www.nytimes.com/2026/10/27/us/election...,85
229,2026-10-27-08-25-46 +0000,nypost,Polls open in Israel for country’s first elect...,https://nypost.com/2026/10/27/world-news/elect...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
354,111,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...
73,63,2026-10-27-15-31-59 +0000,nypost,Man allegedly killed by rabbi at California Co...,https://nypost.com/2026/10/27/us-news/californ...
115,52,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
220,51,2026-10-27-09-21-34 +0000,wsj,Stock Market Today: Tech Stocks Extend Gains A...,https://www.wsj.com/livecoverage/stock-market-...
315,46,2026-10-26-22-11-18 +0000,nypost,Israeli PM Netanyahu and challenger Gadi Eisen...,https://nypost.com/2026/10/26/world-news/how-n...
133,45,2026-10-27-13-00-00 +0000,nypost,Katie Zacharia reveals lesson her brief White ...,https://nypost.com/2026/10/27/us-news/katie-za...
352,41,2026-10-26-20-30-07 +0000,nyt,Israel Has Committed Genocidal Acts in Gaza Si...,https://www.nytimes.com/2026/10/26/world/middl...
281,41,2026-10-27-01-00-00 +0000,wsj,"Running for Senate in Texas, Democrat James Ta...",https://www.wsj.com/politics/elections/texas-s...
294,40,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...
207,40,2026-10-27-10-00-00 +0000,wsj,Fed Chairman Kevin Warsh wants to stop preview...,https://www.wsj.com/economy/central-banking/ke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)