## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-13-05-16 +0000,nyt,Mideast Fighting: Live Updates: Trump Vows to ...,https://www.nytimes.com/live/2026/03/07/world/...
1,2026-03-07-13-00-11 +0000,wapo,An American road trip with his French grandmot...,https://www.washingtonpost.com/lifestyle/inter...
2,2026-03-07-13-00-02 +0000,nyt,Big Tech’s Uncertain Future in the Persian Gulf,https://www.nytimes.com/2026/03/07/business/de...
3,2026-03-07-13-00-00 +0000,startribune,Modern Times cafe in Minneapolis makes pay-wha...,https://www.startribune.com/modern-times-cafe-...
4,2026-03-07-13-00-00 +0000,wsj,Troops Mass as Landlocked Ethiopia Chases Acce...,https://www.wsj.com/world/africa/troops-mass-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2625/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7     iran     66
4    trump     62
134   dies     29
172    war     27
199     up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
122,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,227
197,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,181
27,2026-03-07-11-09-29 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,175
182,2026-03-06-22-39-00 +0000,wsj,"Trump wants Iran’s unconditional surrender, a ...",https://www.wsj.com/politics/policy/trump-want...,174
176,2026-03-06-22-44-51 +0000,nyt,Trump Demands Iran’s ‘Unconditional Surrender’...,https://www.nytimes.com/2026/03/06/world/middl...,172

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
122,227,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
225,82,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
341,61,2026-03-06-16-52-53 +0000,nyt,"From 2011: Madame Nhu, Vietnam War Lightning R...",https://www.nytimes.com/2026/03/06/world/asia/...
185,54,2026-03-06-22-35-00 +0000,wsj,How Robinhood’s New $695-a-Year Credit Card St...,https://www.wsj.com/finance/investing/how-robi...
191,52,2026-03-06-22-17-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
47,49,2026-03-07-10-01-47 +0000,nyt,Russia Revels in a Sudden Reversal in Fortunes...,https://www.nytimes.com/2026/03/07/world/europ...
85,42,2026-03-07-06-01-03 +0000,nypost,Sen. John Kennedy reveals why Kristi Noem was ...,https://nypost.com/2026/03/07/us-news/kristi-n...
234,42,2026-03-06-20-06-24 +0000,nypost,SF mayor under fire for response to street att...,https://nypost.com/2026/03/06/us-news/san-fran...
311,42,2026-03-06-17-03-32 +0000,nypost,Trump-tariff refund system will be ready in 45...,https://nypost.com/2026/03/06/business/trump-t...
294,41,2026-03-06-17-36-06 +0000,nypost,White House releases wild video montages pairi...,https://nypost.com/2026/03/06/us-news/white-ho...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)