## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-23-04-06-27 +0000,missionlocal,S.F. supervisor Jackie Fielder to return to Ci...,https://missionlocal.org/2026/06/jackie-fielde...
1,2026-06-23-04-05-02 +0000,startribune,"Timberwolves trade Julius Randle to Brooklyn, ...",https://www.startribune.com/minnesota-timberwo...
2,2026-06-23-04-03-04 +0000,nypost,21-year-old fatally shot in the head on NYC st...,https://nypost.com/2026/06/23/us-news/21-year-...
3,2026-06-23-04-01-41 +0000,latimes,Federal judge dismisses Trump administration l...,https://www.latimes.com/california/story/2026-...
4,2026-06-23-04-01-09 +0000,nyt,Those British Strawberries Are Being Picked by...,https://www.nytimes.com/2026/06/23/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
215     iran     29
26     trump     20
575  starmer     19
56       new     17
547     will     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
76,2026-06-22-22-32-53 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,93
248,2026-06-22-14-10-10 +0000,nypost,US waives Iran oil sanctions for two months in...,https://nypost.com/2026/06/22/world-news/us-wa...,81
313,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...,80
72,2026-06-22-22-47-27 +0000,nyt,Iran Team Leaves Locker Room Note: The ‘Spirit...,https://www.nytimes.com/2026/06/22/world/middl...,75
60,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
76,93,2026-06-22-22-32-53 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
248,81,2026-06-22-14-10-10 +0000,nypost,US waives Iran oil sanctions for two months in...,https://nypost.com/2026/06/22/world-news/us-wa...
217,63,2026-06-22-15-30-00 +0000,wsj,The Supreme Court is about to decide four case...,https://www.wsj.com/politics/policy/the-suprem...
172,61,2026-06-22-17-38-00 +0000,wsj,Alan Greenspan’s legacy explained: how the Fed...,https://www.wsj.com/economy/central-banking/al...
288,49,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
60,43,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...
321,40,2026-06-22-04-58-42 +0000,nypost,2 students arrested after deadly high school s...,https://nypost.com/2026/06/22/world-news/phili...
70,40,2026-06-22-22-57-02 +0000,nypost,Florida real estate mogul accused of homicide ...,https://nypost.com/2026/06/22/us-news/florida-...
6,38,2026-06-23-03-55-00 +0000,bbc,Australia's coal and gas exports violate our h...,https://www.bbc.com/news/articles/cn8q5nx6jw6o...
115,36,2026-06-22-20-47-37 +0000,nyt,Vance Claims Progress in First Day of Iran Talks,https://www.nytimes.com/2026/06/22/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)