## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-01-23-10-05 +0000,nypost,Goon brutalizes defenseless nun in daylight as...,https://nypost.com/2026/05/01/world-news/goon-...
1,2026-05-01-23-07-00 +0000,wsj,Americans are pouring a lot more money into th...,https://www.wsj.com/economy/consumers/american...
2,2026-05-01-23-07-00 +0000,wsj,Americans Spent $125 Million More on Gas Frida...,https://www.wsj.com/economy/consumers/american...
3,2026-05-01-23-06-00 +0000,wsj,"Trump Orders the Withdrawal of 5,000 U.S. Troo...",https://www.wsj.com/world/europe/trump-orders-...
4,2026-05-01-23-05-51 +0000,nypost,Gavin Newsom’s top allies flood Xavier Becerra...,https://nypost.com/2026/05/01/us-news/gavin-ne...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
22    trump     41
414    your     39
1029  guide     35
358    race     35
267    iran     32

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
287,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,186
293,2026-05-01-10-00-00 +0000,latimes,Your guide to the California state schools sup...,https://www.latimes.com/california/story/2026-...,184
285,2026-05-01-10-00-00 +0000,latimes,Your guide to the L.A. City Council District 1...,https://www.latimes.com/california/story/2026-...,179
297,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,178
176,2026-05-01-16-33-27 +0000,latimes,Your guide to the L.A. City Council District 5...,https://www.latimes.com/california/story/2026-...,176

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
287,186,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...
70,129,2026-05-01-21-05-43 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...
124,82,2026-05-01-19-21-00 +0000,wsj,Trump’s new Air Force One will arrive this sum...,https://www.wsj.com/politics/national-security...
72,60,2026-05-01-21-00-02 +0000,nypost,NYC lawmakers push plan to set up 23K free dog...,https://nypost.com/2026/05/01/us-news/nyc-coun...
224,57,2026-05-01-13-54-56 +0000,nypost,Chirayu Rana — former JPMorgan banker at cente...,https://nypost.com/2026/05/01/business/chirayu...
242,53,2026-05-01-12-36-00 +0000,wsj,The Minneapolis Fed president wrote that heigh...,https://www.wsj.com/economy/central-banking/ri...
372,49,2026-05-01-04-11-53 +0000,bbc,Myanmar ex-leader Aung San Suu Kyi moved to ho...,https://www.bbc.com/news/articles/cz72j8eex4eo...
131,44,2026-05-01-19-06-01 +0000,nypost,Nithya Raman whines about LA police union atta...,https://nypost.com/2026/05/01/us-news/nithya-r...
388,39,2026-05-01-01-33-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
393,37,2026-05-01-01-00-00 +0000,wsj,“This is a warning. We know you live right her...,https://www.wsj.com/politics/policy/immigratio...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)