## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-14-46-02 +0000,nypost,Supreme Court reinstates murder conviction in ...,https://nypost.com/2026/06/22/us-news/supreme-...
1,2026-06-22-14-45-29 +0000,nyt,Mideast Live Updates: Vance Points to Progress...,https://www.nytimes.com/live/2026/06/22/world/...
2,2026-06-22-14-45-28 +0000,nyt,"Abelardo De La Espriella, Right-Wing Outsider,...",https://www.nytimes.com/2026/06/20/world/ameri...
3,2026-06-22-14-45-27 +0000,nyt,The Guardrails Designed to Protect U.S.-Iran T...,https://www.nytimes.com/2026/06/22/world/middl...
4,2026-06-22-14-43-18 +0000,nyt,U.S. Temporarily Lifts Sanctions on Iranian Oil,https://www.nytimes.com/2026/06/22/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
21      iran     31
80   starmer     21
22     talks     19
9        new     15
240    trump     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,108
97,2026-06-22-11-20-37 +0000,nypost,"Iran will let UN nuke inspectors back in, coul...",https://nypost.com/2026/06/22/us-news/jd-vance...,93
1,2026-06-22-14-45-29 +0000,nyt,Mideast Live Updates: Vance Points to Progress...,https://www.nytimes.com/live/2026/06/22/world/...,84
150,2026-06-22-08-08-51 +0000,wsj,Stock Market Today: Oil Slides on Signs of Pro...,https://www.wsj.com/livecoverage/stock-market-...,81
210,2026-06-21-21-30-03 +0000,nypost,Iran brags that negotiators snubbed Vance duri...,https://nypost.com/2026/06/21/world-news/iran-...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,108,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
147,74,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...
93,54,2026-06-22-11-35-00 +0000,wsj,"Alan Greenspan, who piloted the economy throug...",https://www.wsj.com/economy/central-banking/al...
101,52,2026-06-22-11-01-00 +0000,wsj,"In Washington and around the world, political ...",https://www.wsj.com/politics/in-washington-and...
251,48,2026-06-21-17-32-12 +0000,nypost,NYC voters are fed up with the Democratic Part...,https://nypost.com/2026/06/21/us-news/nyc-vote...
109,39,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
195,39,2026-06-21-23-54-20 +0000,cbc,Abelardo De La Espriella wins Colombia electio...,https://www.cbc.ca/news/world/colombia-preside...
1,34,2026-06-22-14-45-29 +0000,nyt,Mideast Live Updates: Vance Points to Progress...,https://www.nytimes.com/live/2026/06/22/world/...
20,30,2026-06-22-14-22-05 +0000,latimes,Boyle Heights fire expected to keep burning fo...,https://www.latimes.com/california/story/2026-...
89,28,2026-06-22-11-46-17 +0000,nypost,Oliver Tree’s body back in US after deadly Bra...,https://nypost.com/2026/06/22/world-news/olive...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)