## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-14-13-21-00 +0000,wsj,U.K. Economy Accelerates to Outpace U.S. as Wa...,https://www.wsj.com/economy/u-k-economy-accele...
1,2026-05-14-13-20-06 +0000,nypost,Israel to sue New York Times over article alle...,https://nypost.com/2026/05/14/world-news/israe...
2,2026-05-14-13-18-24 +0000,bbc,In pictures: Trump hosted by Xi Jinping in Bei...,https://www.bbc.com/news/articles/cdxp0g4q3q2o...
3,2026-05-14-13-18-00 +0000,wsj,Retailers’ Sales Growth Cooled Last Month,https://www.wsj.com/business/retail/retailers-...
4,2026-05-14-13-17-22 +0000,nyt,What People in China Say of Trump,https://www.nytimes.com/2026/05/14/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2374/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
23  trump     72
35  china     43
25     xi     29
8     new     27
3     war     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...,189
111,2026-05-14-09-23-29 +0000,nypost,"Taiwan says no surprises from Trump-Xi summit,...",https://nypost.com/2026/05/14/us-news/taiwan-s...,187
87,2026-05-14-10-47-10 +0000,nypost,Trump sets date for Xi Jinping White House vis...,https://nypost.com/2026/05/14/us-news/trump-in...,187
199,2026-05-14-02-08-48 +0000,nypost,Trump greets Xi in Beijing to kick off histori...,https://nypost.com/2026/05/13/us-news/trump-gr...,183
172,2026-05-14-04-40-36 +0000,nypost,Xi raises prospect of a future US-China war in...,https://nypost.com/2026/05/14/us-news/xi-raise...,181

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,189,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...
281,129,2026-05-13-21-29-00 +0000,wsj,"Kevin Warsh is officially the new Fed chair, t...",https://www.wsj.com/politics/policy/warsh-conf...
246,66,2026-05-13-23-03-15 +0000,bbc,Warning higher Europe air fares 'inevitable' d...,https://www.bbc.com/news/articles/clyprnelzxzo...
147,59,2026-05-14-08-01-50 +0000,wsj,Stock Market Today: Stock Futures Tick Up With...,https://www.wsj.com/livecoverage/stock-market-...
262,51,2026-05-13-22-29-26 +0000,latimes,Vance says $1.3 billion in Medicaid payments t...,https://www.latimes.com/california/story/2026-...
305,47,2026-05-13-20-43-00 +0000,wsj,Boston Fed President Susan Collins flagged the...,https://www.wsj.com/economy/central-banking/bo...
382,44,2026-05-13-17-13-37 +0000,wapo,Court overturns Alex Murdaugh’s murder convict...,https://www.washingtonpost.com/nation/2026/05/...
100,41,2026-05-14-10-00-00 +0000,latimes,Another Californian was exposed to hantavirus ...,https://www.latimes.com/california/story/2026-...
203,39,2026-05-14-01-44-00 +0000,wsj,The Pentagon abruptly canceled deployment of a...,https://www.wsj.com/politics/national-security...
242,39,2026-05-13-23-12-29 +0000,nypost,South Carolina gov expected to demand special ...,https://nypost.com/2026/05/13/us-news/south-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)