## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-16-13-24 +0000,nypost,Deranged mom knifes 14-year-old daughter to de...,https://nypost.com/2026/03/31/us-news/wisconsi...
1,2026-03-31-16-11-55 +0000,bbc,UK and France extend talks over new small boat...,https://www.bbc.com/news/articles/c3exveglpe3o...
2,2026-03-31-16-11-49 +0000,nyt,New Book by JD Vance Will Explore His Conversi...,https://www.nytimes.com/2026/03/31/us/politics...
3,2026-03-31-16-08-55 +0000,bbc,US Supreme Court strikes down Colorado's ban o...,https://www.bbc.com/news/articles/c1j75rz77x5o...
4,2026-03-31-16-08-00 +0000,wsj,Opinion | Trump Is Right on Birthright Citizen...,https://www.wsj.com/opinion/trump-is-right-on-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2481/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41    iran     51
33   trump     48
48     war     34
78     oil     19
145    gas     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
46,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...,186
298,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...,153
8,2026-03-31-16-00-45 +0000,nyt,Iran War Live Updates: B-52s Start Flying Miss...,https://www.nytimes.com/live/2026/03/31/world/...,147
102,2026-03-31-13-02-00 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,146
6,2026-03-31-16-05-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,146

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
46,186,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...
68,70,2026-03-31-14-14-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
298,54,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...
64,51,2026-03-31-14-26-52 +0000,nypost,"Supreme Court sides with Christian counselor, ...",https://nypost.com/2026/03/31/us-news/supreme-...
163,48,2026-03-31-09-39-27 +0000,nypost,Gas prices rise above $4 a gallon for first ti...,https://nypost.com/2026/03/31/business/gas-pri...
131,48,2026-03-31-11-03-31 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
127,41,2026-03-31-11-26-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
187,41,2026-03-31-08-02-03 +0000,nypost,Iran strikes Kuwaiti oil tanker in drone attac...,https://nypost.com/2026/03/31/world-news/iran-...
327,38,2026-03-30-19-10-41 +0000,nypost,"While you endured hourslong travel nightmares,...",https://nypost.com/2026/03/30/us-news/lawmaker...
49,37,2026-03-31-14-55-27 +0000,nypost,Lefty SF Supervisor had been absent for severa...,https://nypost.com/2026/03/31/us-news/sf-super...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)