## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-20-53-41 +0000,nyt,Big Tech’s Data Center Blitz Is Burning Throug...,https://www.nytimes.com/2026/10/29/technology/...
1,2026-10-29-20-53-18 +0000,nypost,DOJ ramps up criminal probe into Alaska’s ‘Dec...,https://nypost.com/2026/10/29/us-news/doj-ramp...
2,2026-10-29-20-53-05 +0000,nypost,The hidden ways debt gets more expensive — eve...,https://nypost.com/business/why-credit-card-mi...
3,2026-10-29-20-52-00 +0000,wsj,Cornell Investigation Puts Letitia James Back ...,https://www.wsj.com/us-news/law/cornell-invest...
4,2026-10-29-20-49-28 +0000,nyt,Justice Dept. Pressures California With Expand...,https://www.nytimes.com/2026/10/29/us/trump-do...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2656/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
50       trump     32
88         new     23
42  california     22
44    election     22
12          up     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-10-29-20-41-45 +0000,nypost,California’s Prop. 3 tax on top earners holds ...,https://nypost.com/2026/10/29/us-news/californ...,117
241,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,94
384,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...,90
322,2026-10-29-10-00-00 +0000,latimes,A new president takes charge at Caltech as unc...,https://www.latimes.com/california/story/2026-...,90
119,2026-10-29-17-51-41 +0000,nypost,California High-Speed Rail Authority names new...,https://nypost.com/2026/10/29/us-news/gavin-ne...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,117,2026-10-29-20-41-45 +0000,nypost,California’s Prop. 3 tax on top earners holds ...,https://nypost.com/2026/10/29/us-news/californ...
384,90,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...
195,75,2026-10-29-15-15-01 +0000,nypost,Key inflation gauge heats up thanks to high g...,https://nypost.com/2026/10/29/business/feds-pr...
342,74,2026-10-29-09-01-00 +0000,wsj,Most Americans—including many Iranian American...,https://www.wsj.com/politics/elections/i-went-...
294,54,2026-10-29-10-57-14 +0000,nypost,Alaska governor orders probe of Mary Peltola S...,https://nypost.com/2026/10/29/us-news/alaska-g...
165,53,2026-10-29-16-13-06 +0000,nypost,Conservative groups warn letting AI giants ‘re...,https://nypost.com/2026/10/29/business/conserv...
391,52,2026-10-29-01-12-00 +0000,wsj,Fed Chairman Kevin Warsh said higher rates are...,https://www.wsj.com/economy/central-banking/th...
129,45,2026-10-29-17-16-01 +0000,nypost,Wall Street con man used 87-year-old Obama don...,https://nypost.com/2026/10/29/business/wall-st...
247,45,2026-10-29-13-18-29 +0000,nypost,Feds found evidence Ilhan Omar was in sham mar...,https://nypost.com/2026/10/29/us-news/feds-fou...
114,42,2026-10-29-18-05-52 +0000,cbc,Netanyahu's party amplifies unproven claims th...,https://www.cbc.ca/news/world/israel-election-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)