## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-14-11-38-35 +0000,nyt,Iran War Live Updates: Israel and Hezbollah Ex...,https://www.nytimes.com/live/2026/06/14/world/...
1,2026-06-14-11-38-34 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/14/world/...
2,2026-06-14-11-36-00 +0000,wsj,Swiss Voters Reject Population Cap to Manage I...,https://www.wsj.com/world/europe/swiss-voters-...
3,2026-06-14-11-33-56 +0000,nyt,Net Gain,https://www.nytimes.com/2026/06/14/briefing/ne...
4,2026-06-14-11-31-32 +0000,bbc,"Swiss voters reject 10 million population cap,...",https://www.bbc.com/news/articles/c20ygjem17zo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
27    trump     30
143   world     17
144     cup     13
0      iran     12
299  knicks      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-06-13-12-54-19 +0000,cbc,Trump says peace deal with Iran will be signed...,https://www.cbc.ca/news/world/pakistan-us-iran...,75
144,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...,75
5,2026-06-14-11-23-36 +0000,bbc,Trump says US-Iran deal to be signed on Sunday...,https://www.bbc.com/news/articles/cvglmn49xz0o...,64
157,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...,64
130,2026-06-13-19-14-50 +0000,wapo,"U.S. and Iran to close deal within a day, Trum...",https://www.washingtonpost.com/world/2026/06/1...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,75,2026-06-13-12-54-19 +0000,cbc,Trump says peace deal with Iran will be signed...,https://www.cbc.ca/news/world/pakistan-us-iran...
87,51,2026-06-14-00-00-54 +0000,nypost,Mexican trade group leader fired after racist ...,https://nypost.com/2026/06/13/world-news/mexic...
55,34,2026-06-14-07-21-26 +0000,bbc,New York Knicks win NBA championship for first...,https://www.bbc.com/news/articles/c78yw4zw19do...
157,34,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...
105,27,2026-06-13-22-05-24 +0000,bbc,Vincent's parents 'never say he's good enough'...,https://www.bbc.com/news/articles/cpq3dnr5vlzo...
120,24,2026-06-13-20-39-10 +0000,nypost,NYC Councilwoman failed to disclose free rent ...,https://nypost.com/2026/06/13/us-news/nyc-coun...
69,24,2026-06-14-03-07-41 +0000,nypost,Unhinged California raisin heir arrested after...,https://nypost.com/2026/06/13/us-news/raisin-h...
54,23,2026-06-14-07-24-35 +0000,nypost,Knicks fans set school bus on fire in Times Sq...,https://nypost.com/2026/06/14/us-news/knicks-f...
4,22,2026-06-14-11-31-32 +0000,bbc,"Swiss voters reject 10 million population cap,...",https://www.bbc.com/news/articles/c20ygjem17zo...
76,22,2026-06-14-01-31-09 +0000,startribune,Hennepin County Sheriff Dawanna Witt fails to ...,https://www.startribune.com/hennepin-county-df...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)