## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-30-07-32-23 +0000,startribune,Lynx thump Chicago 79-58 for fourth consecutiv...,https://www.startribune.com/minnesota-lynx-chi...
1,2026-05-30-07-22-19 +0000,nyt,Iran War Updates: Trump Puts Off ‘Final Determ...,https://www.nytimes.com/live/2026/05/29/world/...
2,2026-05-30-06-43-02 +0000,nypost,White House releases doctor’s memo from Trump’...,https://nypost.com/2026/05/30/us-news/trump-in...
3,2026-05-30-06-40-29 +0000,startribune,"The latest: At conventions, parties wrestle wi...",https://www.startribune.com/live-battle-for-go...
4,2026-05-30-06-27-11 +0000,nypost,Russian nuclear-capable Oreshnik missile fired...,https://nypost.com/2026/05/30/world-news/russi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
9         trump     41
151         new     19
6          iran     14
123  california     14
105        deal     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
275,2026-05-29-10-56-00 +0000,wsj,President Trump’s face could appear on a $250 ...,https://www.wsj.com/politics/policy/white-hous...,108
218,2026-05-29-15-18-42 +0000,nypost,Trump convenes Situation Room meeting for ‘fin...,https://nypost.com/2026/05/29/us-news/trump-sa...,108
145,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...,104
81,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...,93
1,2026-05-30-07-22-19 +0000,nyt,Iran War Updates: Trump Puts Off ‘Final Determ...,https://www.nytimes.com/live/2026/05/29/world/...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
275,108,2026-05-29-10-56-00 +0000,wsj,President Trump’s face could appear on a $250 ...,https://www.wsj.com/politics/policy/white-hous...
145,63,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...
143,58,2026-05-29-19-57-08 +0000,nyt,Judge Tosses Citizenship Law Aimed at New Vote...,https://www.nytimes.com/2026/05/29/us/new-hamp...
1,51,2026-05-30-07-22-19 +0000,nyt,Iran War Updates: Trump Puts Off ‘Final Determ...,https://www.nytimes.com/live/2026/05/29/world/...
233,46,2026-05-29-14-21-44 +0000,nypost,Dems ‘simply don’t believe’ Jill Biden’s claim...,https://nypost.com/2026/05/29/media/dems-simpl...
164,46,2026-05-29-18-54-40 +0000,latimes,Former California mayor pleads guilty to secre...,https://www.latimes.com/california/story/2026-...
81,45,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...
25,43,2026-05-30-03-10-00 +0000,wsj,The Trump administration recently announced a ...,https://www.wsj.com/politics/policy/green-card...
224,41,2026-05-29-14-50-14 +0000,nypost,NATO vows to ‘defend every inch of Allied terr...,https://nypost.com/2026/05/29/world-news/nato-...
6,35,2026-05-30-05-57-33 +0000,nypost,Virginia Gov. Spanberger ripped over ignored I...,https://nypost.com/2026/05/30/us-news/virginia...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)