## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-05-01-22 +0000,bbc,Rejecting closer EU ties would be dereliction ...,https://www.bbc.co.uk/news/articles/c6lyk8e3lx...
1,2026-10-12-05-00-52 +0000,bbc,Documents falsified to evade tax on Abramovich...,https://www.bbc.co.uk/news/articles/c64g1l5389...
2,2026-10-12-05-00-09 +0000,nyt,What Kim Jones Did Next,https://www.nytimes.com/2026/10/12/style/kim-j...
3,2026-10-12-04-57-35 +0000,nyt,Fugitive in Venezuela Money Laundering Cases t...,https://www.nytimes.com/2026/10/12/us/venezeul...
4,2026-10-12-04-46-59 +0000,nypost,Karen Bass tears into Nithya Raman over flip-f...,https://nypost.com/2026/10/12/us-news/karen-ba...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2669/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
115    trump     35
69    russia     12
432  airport     11
632     will     10
344      out     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,89
139,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,81
147,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...,80
128,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,79
109,2026-10-11-18-10-58 +0000,chitri,Pres. Donald Trump says Russia and Ukraine rea...,https://www.chicagotribune.com/2026/10/11/trum...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,89,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...
158,48,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
139,46,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...
165,40,2026-10-11-11-31-16 +0000,nypost,Man mauled to death by tiger was happily danci...,https://nypost.com/2026/10/11/world-news/man-m...
116,39,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
6,36,2026-10-12-04-37-00 +0000,wsj,China Plays Critical Role in Global AI Supply ...,https://www.wsj.com/finance/stocks/china-plays...
179,36,2026-10-11-10-00-03 +0000,chitri,"Illinois Senate race: Juliana Stratton, F-bomb...",https://www.chicagotribune.com/2026/10/11/illi...
222,31,2026-10-11-08-00-00 +0000,cbc,What happens when a Google data centre comes t...,https://www.cbc.ca/news/world/ai-data-centre-g...
93,26,2026-10-11-19-41-43 +0000,chitri,Six senators call for Trump administration to ...,https://www.chicagotribune.com/2026/10/11/six-...
217,26,2026-10-11-08-55-27 +0000,nyt,"Saudi Arabia’s Riyadh Airport Attacked Again, ...",https://www.nytimes.com/2026/10/10/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)