## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-11-20-59-57 +0000,nypost,Bodycam video reveals tragic last minutes of h...,https://nypost.com/2026/03/11/us-news/bodycam-...
1,2026-03-11-20-59-07 +0000,nypost,Trump signals he will tap into Strategic Petro...,https://nypost.com/2026/03/11/us-news/trump-si...
2,2026-03-11-20-58-46 +0000,nypost,LA ballet hilariously trolls Timothée Chalamet...,https://nypost.com/2026/03/11/us-news/la-balle...
3,2026-03-11-20-57-21 +0000,nypost,Texas high school student dies in ‘tragic acci...,https://nypost.com/2026/03/11/us-news/texas-hi...
4,2026-03-11-20-57-00 +0000,wsj,"UiPath Profit, Revenue Rise as AI Adoption Spr...",https://www.wsj.com/business/earnings/uipath-p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
54     iran     66
55      war     44
12    trump     35
115     oil     24
22   prices     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
237,2026-03-11-11-36-18 +0000,nypost,Record 400M oil barrels to be released from em...,https://nypost.com/2026/03/11/world-news/iea-t...,173
355,2026-03-10-23-02-07 +0000,cbc,How high will the U.S.-Israel war with Iran pu...,https://www.cbc.ca/player/play/9.7123237?cmp=rss,170
190,2026-03-11-14-54-00 +0000,wsj,The economic shock waves of the Iran war are l...,https://www.wsj.com/business/energy-oil/the-ec...,166
18,2026-03-11-20-52-30 +0000,nyt,Iran’s New Supreme Leader Was Wounded Early in...,https://www.nytimes.com/2026/03/11/world/middl...,164
331,2026-03-11-01-00-00 +0000,wsj,Trump Says the Iran War Is Nearly Won but Isra...,https://www.wsj.com/world/middle-east/trump-sa...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
237,173,2026-03-11-11-36-18 +0000,nypost,Record 400M oil barrels to be released from em...,https://nypost.com/2026/03/11/world-news/iea-t...
244,79,2026-03-11-11-06-58 +0000,nyt,"A Trump-Xi Summit Nears, but China Doesn’t Kno...",https://www.nytimes.com/2026/03/11/world/asia/...
218,68,2026-03-11-13-19-52 +0000,nypost,Iranian women’s soccer team member flip-flops ...,https://nypost.com/2026/03/11/world-news/irani...
190,56,2026-03-11-14-54-00 +0000,wsj,The economic shock waves of the Iran war are l...,https://www.wsj.com/business/energy-oil/the-ec...
266,49,2026-03-11-09-30-00 +0000,wsj,Europe’s New Energy Crisis Will Mean a Bull Ma...,https://www.wsj.com/business/energy-oil/europe...
317,48,2026-03-11-02-07-39 +0000,nypost,House Oversight Committee wants to interview E...,https://nypost.com/2026/03/10/us-news/house-ov...
41,46,2026-03-11-20-17-00 +0000,wsj,Sen. John Cornyn of Texas reversed himself and...,https://www.wsj.com/politics/policy/john-corny...
175,43,2026-03-11-15-24-57 +0000,bbc,French aid worker among three killed in drone ...,https://www.bbc.com/news/articles/cvgj8veg0gno...
200,42,2026-03-11-14-13-52 +0000,bbc,EU and UK demand Israel stop surge in West Ban...,https://www.bbc.com/news/articles/c620vwl97vyo...
13,40,2026-03-11-20-54-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)