## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-16-13-45 +0000,nyt,Iran’s New Security Chief Is a Hard-Line Forme...,https://www.nytimes.com/2026/03/24/world/middl...
1,2026-03-24-16-13-09 +0000,nypost,Good Samaritans stop homeless pervert attempti...,https://nypost.com/2026/03/24/us-news/nyc-good...
2,2026-03-24-16-11-16 +0000,wapo,Rubio testifies against friend accused of secr...,https://www.washingtonpost.com/politics/2026/0...
3,2026-03-24-16-09-24 +0000,startribune,Live: Tartan builds double-digit lead over Bla...,https://www.startribune.com/minnesota-boys-bas...
4,2026-03-24-16-09-24 +0000,nyt,"Mel Schilling, Dating Expert on ‘Married at Fi...",https://www.nytimes.com/2026/03/24/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     41
169  trump     35
49     war     24
537  crash     16
1      new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
80,2026-03-24-13-35-55 +0000,nypost,US serviceman’s harrowing final words to dad b...,https://nypost.com/2026/03/24/us-news/us-servi...,126
85,2026-03-24-13-17-18 +0000,nypost,Pete Hegseth was ‘the first’ to push for war w...,https://nypost.com/2026/03/24/us-news/pete-heg...,123
26,2026-03-24-15-34-19 +0000,nyt,Trump’s Threat to ‘Obliterate’ Iran’s Power St...,https://www.nytimes.com/2026/03/24/us/politics...,122
321,2026-03-23-19-47-08 +0000,wapo,Trump says U.S. is postponing some strikes as ...,https://www.washingtonpost.com/politics/2026/0...,117
246,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
80,126,2026-03-24-13-35-55 +0000,nypost,US serviceman’s harrowing final words to dad b...,https://nypost.com/2026/03/24/us-news/us-servi...
56,83,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
311,74,2026-03-23-20-21-51 +0000,bbc,Oil falls and shares rebound after Trump says ...,https://www.bbc.com/news/articles/czex56kwxxzo...
203,63,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
305,49,2026-03-23-20-43-02 +0000,nypost,Anti-communist dance troupe Shen Yun claims CC...,https://nypost.com/2026/03/23/world-news/shen-...
322,42,2026-03-23-19-44-00 +0000,wsj,The Supreme Court seems inclined to block stat...,https://www.wsj.com/politics/elections/supreme...
95,42,2026-03-24-13-01-35 +0000,nypost,"LaGuardia Airport crippled by cancellations, d...",https://nypost.com/2026/03/24/us-news/laguardi...
335,35,2026-03-23-18-41-00 +0000,wsj,ICE Agents—Many Unmasked—Deploy to Airports Am...,https://www.wsj.com/us-news/trump-asks-ice-age...
32,33,2026-03-24-15-28-22 +0000,wapo,"Israel, Iran trade strikes as U.S. says it is ...",https://www.washingtonpost.com/world/2026/03/2...
235,33,2026-03-24-00-47-00 +0000,wsj,The Defense Department introduced new restrict...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)