## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-07-12-05-24 +0000,nyt,Thailand School Shooting Leaves at Least Eight...,https://www.nytimes.com/2026/08/07/world/asia/...
1,2026-08-07-12-05-09 +0000,bbc,Republican Lisa Murkowski opposes Todd Blanche...,https://www.bbc.co.uk/news/articles/c0kme3114x...
2,2026-08-07-12-02-45 +0000,nyt,"Abdul El-Sayed Talks About His Victory, Chuck ...",https://www.nytimes.com/2026/08/07/us/politics...
3,2026-08-07-12-02-28 +0000,bbc,"Saudi Arabia, Turkey and Pakistan sign defence...",https://www.bbc.co.uk/news/articles/c30418m4mj...
4,2026-08-07-12-02-00 +0000,wsj,Take-Two Logs Higher Sales but Loss Widens,https://www.wsj.com/business/earnings/take-two...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2263/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
407   trump     34
87      new     25
511  senate     12
497    deal     12
898   fauci     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
215,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...,108
176,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...,104
233,2026-08-06-20-46-15 +0000,nypost,Trump signs new executive order to ban ‘birth ...,https://nypost.com/2026/08/06/us-news/trump-si...,94
330,2026-08-06-14-56-00 +0000,wsj,A Republican-led Senate panel voted to hold Dr...,https://www.wsj.com/politics/policy/senate-pan...,94
58,2026-08-07-10-00-00 +0000,wsj,A key Republican senator said she would oppose...,https://www.wsj.com/politics/policy/second-rep...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
215,108,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...
176,104,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...
149,65,2026-08-07-01-03-00 +0000,wsj,Rep. Max Miller is lending his re-election cam...,https://www.wsj.com/politics/elections/max-mil...
17,55,2026-08-07-11-16-00 +0000,wsj,It seems like political scandals are happening...,https://www.wsj.com/politics/policy/is-misbeha...
58,51,2026-08-07-10-00-00 +0000,wsj,A key Republican senator said she would oppose...,https://www.wsj.com/politics/policy/second-rep...
214,46,2026-08-06-21-34-00 +0000,wsj,"Trump targets birthright citizenship (again), ...",https://www.wsj.com/politics/policy/trump-trie...
328,44,2026-08-06-14-58-00 +0000,wsj,Democratic candidates on the far left are upen...,https://www.wsj.com/politics/elections/this-de...
369,42,2026-08-06-13-09-00 +0000,wsj,Warner Bros. CEO Confident Paramount Deal Will...,https://www.wsj.com/business/earnings/warner-b...
336,39,2026-08-06-14-46-00 +0000,wsj,A Senate panel investigating Dr. Anthony Fauci...,https://www.wsj.com/politics/policy/anthony-fa...
121,38,2026-08-07-04-01-34 +0000,nypost,"Bay Area fans left stunned as Lionel Richie, E...",https://nypost.com/2026/08/07/us-news/lionel-r...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)