## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-04-16-29-29 +0000,bbc,Oil prices fall on hopes Strait of Hormuz coul...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
1,2026-08-04-16-28-37 +0000,nypost,"Dad poses as daughter, 11, on TikTok to lure h...",https://nypost.com/2026/08/04/us-news/dad-pose...
2,2026-08-04-16-28-00 +0000,wsj,Health Care Roundup: Market Talk,https://www.wsj.com/business/health-care-round...
3,2026-08-04-16-27-56 +0000,nyt,Talks With Iran to Reopen Strait of Hormuz Mak...,https://www.nytimes.com/2026/08/04/world/middl...
4,2026-08-04-16-27-12 +0000,nyt,What to Watch in Washington State’s Primaries ...,https://www.nytimes.com/2026/08/04/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2636/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
602   trump     45
23     iran     25
304     new     24
120    deal     15
5    hormuz     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
327,2026-08-03-19-16-37 +0000,nypost,Trump gives Iran ‘last chance’ to sign deal be...,https://nypost.com/2026/08/03/us-news/trump-gi...,133
169,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,133
274,2026-08-03-21-49-00 +0000,wsj,"Trump discusses Jeanine Pirro’s removal, Iran ...",https://www.wsj.com/politics/policy/trump-disc...,128
272,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...,123
236,2026-08-04-01-19-29 +0000,nyt,An Emerging Deal Between Iran and Oman to Reop...,https://www.nytimes.com/2026/08/03/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
327,133,2026-08-03-19-16-37 +0000,nypost,Trump gives Iran ‘last chance’ to sign deal be...,https://nypost.com/2026/08/03/us-news/trump-gi...
137,85,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...
48,82,2026-08-04-15-22-00 +0000,wsj,A divided Senate Judiciary Committee advanced ...,https://www.wsj.com/politics/policy/senate-jud...
52,65,2026-08-04-15-14-22 +0000,nypost,McDonald’s US sales miss estimates as CEO taps...,https://nypost.com/2026/08/04/business/mcdonal...
316,61,2026-08-03-19-49-32 +0000,nypost,Trump says Jeanine Pirro ‘choked’ by tossing o...,https://nypost.com/2026/08/03/us-news/trump-sa...
238,48,2026-08-04-01-00-00 +0000,wsj,From data centers to the massive increase in s...,https://www.wsj.com/economy/the-ai-boom-is-tra...
343,47,2026-08-03-18-28-49 +0000,nypost,GOP Rep. Chuck Edwards’ ‘inappropriate conduct...,https://nypost.com/2026/08/03/us-news/gop-rep-...
246,45,2026-08-04-00-00-00 +0000,wsj,A little-used Fed backstop is being put to a u...,https://www.wsj.com/economy/central-banking/wh...
159,44,2026-08-04-10-18-51 +0000,nyt,Oil Giant Saudi Aramco Reports 33% Profit Surg...,https://www.nytimes.com/2026/08/04/business/sa...
355,43,2026-08-03-17-27-27 +0000,cbc,European soccer body UEFA warns FIFA of legal ...,https://www.cbc.ca/sports/soccer/uefa-warns-fi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)