## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-18-56-19 +0000,nypost,Wannabe LA mayor Nithya Raman claims she suffe...,https://nypost.com/2026/10/14/us-news/nithya-r...
1,2026-10-14-18-54-07 +0000,nyt,Higher Energy Prices Pushed U.S. Inflation Up ...,https://www.nytimes.com/2026/10/14/business/ec...
2,2026-10-14-18-52-04 +0000,cbc,Ottawa to announce over $350M for skilled trad...,https://www.cbc.ca/news/politics/zerucelli-tra...
3,2026-10-14-18-50-31 +0000,nyt,6 Dead in Wisconsin Plane Crash,https://www.nytimes.com/2026/10/14/us/wisconsi...
4,2026-10-14-18-48-49 +0000,nyt,U.S. Is Sending Hundreds of Troops to Latin Am...,https://www.nytimes.com/2026/10/14/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
61       trump     40
174        new     19
233         ai     17
19   inflation     16
20          up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,149
126,2026-10-14-15-25-31 +0000,nyt,Democrats Blame Trump After CPI Report Shows E...,https://www.nytimes.com/2026/10/14/business/ec...,120
81,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...,116
210,2026-10-14-11-26-27 +0000,nypost,"Russian strikes kill 3, knock out power for 60...",https://nypost.com/2026/10/14/world-news/russi...,100
226,2026-10-14-10-50-00 +0000,wsj,"Eroding support from working-class, white vote...",https://www.wsj.com/politics/policy/the-workin...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,149,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
81,116,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...
340,90,2026-10-14-01-00-00 +0000,wsj,"Trying to save her job, Kimberly Guilfoyle cla...",https://www.wsj.com/politics/policy/kimberly-g...
206,79,2026-10-14-11-45-00 +0000,wsj,The Morning Risk Report: Bank of America to Pa...,https://www.wsj.com/risk-compliance-journal/th...
65,66,2026-10-14-17-02-21 +0000,nyt,A New World of Lung Cancer Therapy Awaits Pope...,https://www.nytimes.com/2026/10/14/science/pop...
230,66,2026-10-14-10-31-04 +0000,nypost,Russell Brand admits he’s ‘concerned’ at start...,https://nypost.com/2026/10/14/world-news/russe...
315,51,2026-10-14-03-52-38 +0000,latimes,Bass and Raman trade blows over police chief i...,https://www.latimes.com/california/story/2026-...
239,47,2026-10-14-10-00-48 +0000,chitri,Chicago Media Report: Mike Ditka made The Scor...,https://www.chicagotribune.com/2026/10/14/chic...
405,46,2026-10-13-21-13-00 +0000,wsj,Kimberly Guilfoyle resigned as the U.S. ambass...,https://www.wsj.com/politics/policy/kimberly-g...
341,46,2026-10-14-00-56-54 +0000,nyt,Saudi Energy Giant Struck as War Spikes Betwee...,https://www.nytimes.com/2026/10/13/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)