## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-21-07-54 +0000,nypost,NY judge approves temporary pause of Mamdani’s...,https://nypost.com/2026/08/10/us-news/ny-judge...
1,2026-08-10-21-07-13 +0000,nypost,John Gotti’s grandson ordered to prison after ...,https://nypost.com/2026/08/10/us-news/john-got...
2,2026-08-10-21-04-53 +0000,nypost,Anti-ICE mob films attack on innocent workers ...,https://nypost.com/2026/08/10/us-news/la-feder...
3,2026-08-10-21-03-00 +0000,wsj,AST SpaceMobile Raises Revenue Outlook as Sate...,https://www.wsj.com/business/earnings/ast-spac...
4,2026-08-10-21-02-49 +0000,nyt,D.C.-Area Airport to Close for 3 Hours for Gra...,https://www.nytimes.com/2026/08/10/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2423/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
72      trump     34
159       new     18
89   colombia     12
226       out     11
222      race     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
317,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...,119
130,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...,90
311,2026-08-09-23-19-35 +0000,wapo,Trump picks longtime aide Will Scharf as new t...,https://www.washingtonpost.com/politics/2026/0...,87
294,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...,83
161,2026-08-10-15-18-28 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
317,119,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...
231,67,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...
216,53,2026-08-10-11-10-00 +0000,wsj,The U.S. and Israeli militaries have pounded I...,https://www.wsj.com/politics/elections/why-is-...
168,45,2026-08-10-14-55-02 +0000,nypost,Massive 7.4-magnitude earthquake strikes Colom...,https://nypost.com/2026/08/10/world-news/massi...
28,42,2026-08-10-20-34-56 +0000,nypost,Dem bigwigs rush to embrace El-Sayed in critic...,https://nypost.com/2026/08/10/us-news/dem-bigw...
63,41,2026-08-10-19-53-07 +0000,nypost,‘Captain’ in fatal NY Harbor tragedy didn’t ha...,https://nypost.com/2026/08/10/us-news/captain-...
169,40,2026-08-10-14-52-12 +0000,nypost,Ex-Wisconsin Gov. Scott Walker warns Republica...,https://nypost.com/2026/08/10/us-news/ex-wisco...
90,37,2026-08-10-18-49-02 +0000,nypost,Fauci privately warned of miscarriage risk lin...,https://nypost.com/2026/08/10/us-news/fauci-wa...
83,35,2026-08-10-19-05-59 +0000,latimes,"With Big Bear bald eagle Jackie gone, we want ...",https://www.latimes.com/environment/story/2026...
221,35,2026-08-10-10-59-10 +0000,nypost,Meta’s Mark Zuckerberg pushes positive AI mess...,https://nypost.com/2026/08/10/us-news/meta-lau...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)