## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-02-30-11 +0000,nypost,California woman accused of running fake anima...,https://nypost.com/2026/07/24/us-news/accused-...
1,2026-07-25-02-29-36 +0000,bbc,"More than 220,000 evacuated in France and Spai...",https://www.bbc.co.uk/news/articles/czjlenp0xk...
2,2026-07-25-02-28-23 +0000,nypost,Trump plays comedian-in-chief at rescheduled W...,https://nypost.com/2026/07/24/us-news/trump-re...
3,2026-07-25-02-23-09 +0000,bbc,Trump orders Smithsonian to post warnings abou...,https://www.bbc.co.uk/news/articles/c1w10gwnj7...
4,2026-07-25-02-17-07 +0000,nypost,Family of grandma killed in senseless stabbing...,https://nypost.com/2026/07/24/us-news/new-deta...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20     trump     53
42       new     33
64      iran     27
99       war     20
165  tariffs     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-07-24-14-52-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,139
100,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,139
10,2026-07-25-01-58-53 +0000,nyt,Iran War Updates: Trump Meets With Cabinet Ove...,https://www.nytimes.com/live/2026/07/24/world/...,137
353,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,136
184,2026-07-24-17-29-56 +0000,nyt,Iran War and Trump’s Tariffs Threaten a Resili...,https://www.nytimes.com/2026/07/24/business/ir...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,139,2026-07-24-14-52-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...
24,115,2026-07-25-00-59-00 +0000,wsj,A Democratic Party panel selected South Caroli...,https://www.wsj.com/politics/elections/democra...
92,69,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
236,58,2026-07-24-14-45-22 +0000,bbc,"Dancing with Shakira at World Cup was 'very, v...",https://www.bbc.co.uk/news/articles/cly5j2gq58...
353,50,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
5,44,2026-07-25-02-16-45 +0000,nypost,"Trump cracks jokes, honors heroes of White Hou...",https://nypost.com/2026/07/24/us-news/trump-cr...
183,40,2026-07-24-17-30-54 +0000,nypost,"Miami dethrones NYC, Bay Area as America’s hot...",https://nypost.com/2026/07/24/business/miami-d...
0,38,2026-07-25-02-30-11 +0000,nypost,California woman accused of running fake anima...,https://nypost.com/2026/07/24/us-news/accused-...
61,38,2026-07-24-23-10-36 +0000,startribune,Live: Lynx stars take center stage as WNBA con...,https://www.startribune.com/minnesota-lynx-wnb...
42,38,2026-07-24-23-57-49 +0000,nypost,Ex-Supreme Court litigator gets prison time fo...,https://nypost.com/2026/07/24/us-news/ex-supre...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)