## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-01-25-29 +0000,nypost,Construction worker returns $30K found in Wawa...,https://nypost.com/2026/05/24/us-news/florida-...
1,2026-05-25-01-24-30 +0000,bbc,Education secretary to order review of hidden ...,https://www.bbc.com/news/articles/c4g7d6ngjldo...
2,2026-05-25-01-23-00 +0000,wsj,Oil Futures Edge Down as Ships Move Toward Hormuz,https://www.wsj.com/business/energy-oil/oil-ma...
3,2026-05-25-01-21-00 +0000,wsj,Asian Currencies Mostly Strengthen Amid Risk-O...,https://www.wsj.com/finance/currencies/risk-as...
4,2026-05-25-01-19-18 +0000,48hills,New Melgar-Lurie plan for affordable housing i...,https://48hills.org/2026/05/new-melgar-lurie-p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
58        iran     26
54       trump     23
43        deal     22
88  california      9
62       peace      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
136,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...,139
7,2026-05-25-01-01-31 +0000,nyt,Iran War Live Updates: U.S.-Iran Peace Deal Ne...,https://www.nytimes.com/live/2026/05/24/world/...,100
194,2026-05-24-02-52-55 +0000,nypost,Iran agrees to give up ‘nuclear dust’ stockpil...,https://nypost.com/2026/05/23/us-news/iran-agr...,94
140,2026-05-24-11-14-00 +0000,wsj,Trump Says a Deal for Talks With Iran to End W...,https://www.wsj.com/world/middle-east/trump-an...,90
77,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
136,139,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...
174,48,2026-05-24-09-00-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
94,43,2026-05-24-17-44-53 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
46,35,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
77,32,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
196,31,2026-05-24-01-50-43 +0000,nypost,California governor candidate Xavier Becerra’s...,https://nypost.com/2026/05/23/us-news/xavier-b...
104,28,2026-05-24-16-50-46 +0000,bbc,Large-scale Russian attack on Ukraine leaves f...,https://www.bbc.com/news/articles/clyp6831yp5o...
33,24,2026-05-24-23-28-15 +0000,nypost,Hero Purple Heart vet whom Graham Platner said...,https://nypost.com/2026/05/24/us-news/purple-h...
70,24,2026-05-24-21-02-08 +0000,bbc,She was told to marry in a country which bans ...,https://www.bbc.com/news/articles/ce3pgn48wnqo...
37,23,2026-05-24-23-12-37 +0000,nypost,"Swimmer, 68, chokes, scratches boy at water pa...",https://nypost.com/2026/05/24/us-news/swimmer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)