## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-08-16-59-56 +0000,nyt,The U.S. Is Burning Through Weapons in Iran. R...,https://www.nytimes.com/2026/08/08/us/politics...
1,2026-08-08-16-42-30 +0000,nypost,Trump posts image of fortified ‘drone port’ at...,https://nypost.com/2026/08/08/us-news/trump-po...
2,2026-08-08-16-40-49 +0000,chitri,Zelenskyy visits Moscow-friendly Serbia as Rus...,https://www.chicagotribune.com/2026/08/08/zele...
3,2026-08-08-16-34-18 +0000,bbc,US offers $1bn to Colombia on new right-wing p...,https://www.bbc.co.uk/news/articles/cy9wy3y0e5...
4,2026-08-08-16-29-43 +0000,nypost,Mom’s robbery inspired Dominican immigrant’s r...,https://nypost.com/2026/08/08/us-news/moms-rob...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
8     trump     38
705   court     18
181  senate     16
3      iran     12
33      new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,143
272,2026-08-07-17-15-00 +0000,wsj,A federal appeals court on Friday halted const...,https://www.wsj.com/politics/policy/white-hous...,135
229,2026-08-07-19-25-36 +0000,wapo,Trump renews effort to fire Fed governor Lisa ...,https://www.washingtonpost.com/business/2026/0...,111
199,2026-08-07-20-46-00 +0000,wsj,Trump revives effort to oust Fed governor Lisa...,https://www.wsj.com/politics/white-house-reviv...,109
208,2026-08-07-20-22-38 +0000,wapo,Trump says he’ll bring ballroom fight to Supre...,https://www.washingtonpost.com/politics/2026/0...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,143,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
107,71,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...
129,58,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...
269,49,2026-08-07-17-23-50 +0000,nypost,"Late Lindsey Graham’s Russia, Iran sanctions b...",https://nypost.com/2026/08/07/us-news/senate-p...
241,42,2026-08-07-18-50-02 +0000,latimes,Meta ordered by New Mexico judge to pay $567 m...,https://www.latimes.com/business/story/2026-08...
12,36,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
272,34,2026-08-07-17-15-00 +0000,wsj,A federal appeals court on Friday halted const...,https://www.wsj.com/politics/policy/white-hous...
18,32,2026-08-08-15-50-23 +0000,nypost,Chemical fumes linger inside NYC grade school ...,https://nypost.com/2026/08/08/us-news/chemical...
126,30,2026-08-08-02-28-32 +0000,latimes,Searing heat on tap for SoCal this weekend — a...,https://www.latimes.com/california/story/2026-...
195,30,2026-08-07-20-50-01 +0000,nypost,"Saudi Arabia, Turkey and Pakistan forge ‘attac...",https://nypost.com/2026/08/07/world-news/saudi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)