## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-17-13-22 +0000,nypost,Amazon sued for allegedly sabotaging Fire TV S...,https://nypost.com/2026/04/15/business/amazon-...
1,2026-04-15-17-12-47 +0000,nyt,"Amid Iran War, Companies Look to Extend a Reco...",https://www.nytimes.com/2026/04/15/business/ec...
2,2026-04-15-17-12-07 +0000,nypost,Shower cap-wearing woman hacks man to death wi...,https://nypost.com/2026/04/15/us-news/man-38-f...
3,2026-04-15-17-11-31 +0000,nypost,Big advertisers agree to settle FTC probe of a...,https://nypost.com/2026/04/15/media/big-advert...
4,2026-04-15-17-10-00 +0000,wsj,Jane Street Invests $1 Billion in CoreWeave,https://www.wsj.com/tech/ai/jane-street-invest...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
11    iran     42
172  trump     35
12     war     25
222    new     21
97      up     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
129,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,152
186,2026-04-15-10-00-00 +0000,nypost,Trump needs ‘four- or five-month window’ betwe...,https://nypost.com/2026/04/15/us-news/trump-ne...,135
14,2026-04-15-16-53-31 +0000,nyt,Iran War Live Updates: Iran Threatens Retaliat...,https://www.nytimes.com/live/2026/04/15/world/...,135
159,2026-04-15-11-39-31 +0000,nypost,Trump predicts Iran war is ‘very close to bein...,https://nypost.com/2026/04/15/us-news/trump-pr...,129
74,2026-04-15-15-27-22 +0000,bbc,Starmer says he's 'not going to yield' to pres...,https://www.bbc.com/news/articles/cdxdd7ddzgdo...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
129,152,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
14,135,2026-04-15-16-53-31 +0000,nyt,Iran War Live Updates: Iran Threatens Retaliat...,https://www.nytimes.com/live/2026/04/15/world/...
66,69,2026-04-15-15-34-22 +0000,nypost,Eric Swalwell’s hotshot lawyer comes out swing...,https://nypost.com/2026/04/15/us-news/eric-swa...
191,56,2026-04-15-10-00-00 +0000,latimes,L.A.'s Blue Era: How popular are the Dodgers? ...,https://www.latimes.com/sports/dodgers/story/2...
267,51,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
79,44,2026-04-15-15-17-29 +0000,nypost,Disgraced Ex-Rep. Tony Gonzales begged another...,https://nypost.com/2026/04/15/us-news/ex-rep-t...
110,41,2026-04-15-14-15-50 +0000,bbc,Israel and Hezbollah continue attacks after Is...,https://www.bbc.com/news/articles/c87ww2z0z3zo...
53,36,2026-04-15-16-07-00 +0000,wsj,See the breakdown of economists’ responses to ...,https://www.wsj.com/economy/central-banking/th...
219,33,2026-04-15-08-23-13 +0000,nypost,US internet ‘troll’ Johnny Somali sentenced to...,https://nypost.com/2026/04/15/world-news/ameri...
300,33,2026-04-14-22-00-20 +0000,nyt,Carney Suspends Gas Tax in Canada as War Drive...,https://www.nytimes.com/2026/04/14/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)