## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-02-11-09 +0000,bbc,Mangione state murder trial postponed after fe...,https://www.bbc.co.uk/news/articles/cqjxkqppz5...
1,2026-08-18-02-09-57 +0000,nyt,House Panel Investigates Charges a Democrat Ha...,https://www.nytimes.com/2026/08/17/us/politics...
2,2026-08-18-02-09-00 +0000,wsj,BHP Annual Profit Rises on Record Copper Prices,https://www.wsj.com/business/earnings/bhp-annu...
3,2026-08-18-02-06-04 +0000,bbc,Tupac murder trial: 'All hell broke loose' nig...,https://www.bbc.co.uk/news/articles/cp3r0kz775...
4,2026-08-18-02-01-32 +0000,nyt,Hegseth Campaigns for Republican Zach Nunn in ...,https://www.nytimes.com/2026/08/17/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2366/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     52
125   iran     21
8    house     14
282    new     14
120     he     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
286,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,136
158,2026-08-17-18-39-39 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,127
162,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...,116
145,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...,112
44,2026-08-17-23-24-59 +0000,nyt,"Facing Quagmire in Iran, Trump Turns to a Fami...",https://www.nytimes.com/2026/08/17/us/politics...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
286,136,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
270,65,2026-08-17-11-03-00 +0000,wsj,One of the most sensitive stories in this near...,https://www.wsj.com/politics/pentagon-rotates-...
162,64,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...
186,59,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
159,52,2026-08-17-18-32-30 +0000,nypost,House Ethics panel probing Dem Rep. Jimmy Gome...,https://nypost.com/2026/08/17/us-news/house-et...
173,45,2026-08-17-17-47-48 +0000,chitri,How Chuck E. Cheese is reinventing itself for ...,https://www.chicagotribune.com/2026/08/17/chuc...
80,43,2026-08-17-21-44-32 +0000,nypost,Jared Kushner: Hamas said ‘all the right thing...,https://nypost.com/2026/08/17/world-news/jared...
41,42,2026-08-17-23-29-08 +0000,nypost,Inside Brooklyn’s seedy Penn Track sex market ...,https://nypost.com/2026/08/17/us-news/inside-b...
145,39,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...
132,38,2026-08-17-20-03-42 +0000,chitri,Trump administration briefly pauses contentiou...,https://www.chicagotribune.com/2026/08/17/big-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)