## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-27-21-26-15 +0000,nypost,Steve Hilton says California should be world’s...,https://nypost.com/2026/05/27/us-news/steve-hi...
1,2026-05-27-21-25-00 +0000,wsj,"Salesforce First-Quarter Sales, Profit Rise Am...",https://www.wsj.com/business/earnings/salesfor...
2,2026-05-27-21-24-00 +0000,wsj,Opinion | Prolonged Conflict Hurts Us,https://www.wsj.com/opinion/prolonged-conflict...
3,2026-05-27-21-23-00 +0000,wsj,Fed’s Cook Ready To Raise Rates If Disinflatio...,https://www.wsj.com/economy/central-banking/fe...
4,2026-05-27-21-19-05 +0000,nyt,Where Time Is Always 15 Minutes Apart From Eve...,https://www.nytimes.com/2026/05/27/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
164  trump     39
182  texas     24
272    new     21
50    deal     19
279   iran     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
255,2026-05-27-10-57-00 +0000,wsj,Texas Attorney General Ken Paxton might end up...,https://www.wsj.com/politics/trump-remakes-gop...,135
30,2026-05-27-20-58-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,123
256,2026-05-27-10-54-27 +0000,cbc,Trump's scandal-plagued pick wins Texas Senate...,https://www.cbc.ca/news/world/us-texas-republi...,111
261,2026-05-27-10-27-10 +0000,nyt,"Endorsed by Trump, Paxton Crushes Cornyn: Take...",https://www.nytimes.com/2026/05/26/us/politics...,96
269,2026-05-27-10-00-00 +0000,latimes,Barabak: Texas is where Democratic dreams die....,https://www.latimes.com/politics/story/2026-05...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
255,135,2026-05-27-10-57-00 +0000,wsj,Texas Attorney General Ken Paxton might end up...,https://www.wsj.com/politics/trump-remakes-gop...
286,64,2026-05-27-09-03-26 +0000,nypost,Israel kills new Hamas military chief who was...,https://nypost.com/2026/05/27/world-news/israe...
214,63,2026-05-27-13-38-04 +0000,nypost,Oil plunges to $89 per barrel after Iran repor...,https://nypost.com/2026/05/27/business/oil-plu...
30,54,2026-05-27-20-58-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
373,53,2026-05-26-22-18-28 +0000,nypost,Possible serial killer is latest horror to upe...,https://nypost.com/2026/05/26/world-news/possi...
249,45,2026-05-27-11-03-03 +0000,nypost,Race against time to rescue villagers trapped ...,https://nypost.com/2026/05/27/world-news/race-...
336,42,2026-05-27-02-00-00 +0000,wsj,Europe Is Starting to Think Putin Will Expand ...,https://www.wsj.com/world/europe/russia-ukrain...
268,38,2026-05-27-10-00-00 +0000,latimes,'Monster who killed him': Matthew Perry's form...,https://www.latimes.com/california/story/2026-...
170,38,2026-05-27-15-52-33 +0000,nypost,New York Times accused of using AI to spy on u...,https://nypost.com/2026/05/27/media/new-york-t...
60,38,2026-05-27-20-28-26 +0000,nypost,Jill Biden shockingly admits she thought Joe w...,https://nypost.com/2026/05/27/us-news/jill-bid...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)