## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-11-23-45-12 +0000,nyt,Saudi and Yemeni Airports Hit in New Round of ...,https://www.nytimes.com/2026/10/11/world/middl...
1,2026-10-11-23-33-27 +0000,startribune,"Scoggins: Kyler Murray, Justin Jefferson show ...",https://www.startribune.com/minnesota-vikings-...
2,2026-10-11-23-28-09 +0000,nyt,Waves From Powerful Storm Pound Beach Homes in...,https://www.nytimes.com/2026/10/11/us/longbeac...
3,2026-10-11-23-25-18 +0000,nypost,Daughters of the American Revolution axes chap...,https://nypost.com/2026/10/11/us-news/daughter...
4,2026-10-11-23-19-49 +0000,bbc,Roofing scammers con homeowners out of thousan...,https://www.bbc.co.uk/news/articles/c6x29kydnz...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2360/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
46     trump     33
53    russia     12
117  airport     12
35       out     11
4        new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,87
116,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...,80
108,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,79
97,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,77
25,2026-10-11-21-22-00 +0000,wsj,Trump Pushes Russia-Ukraine Energy Ceasefire a...,https://www.wsj.com/world/trump-declares-a-rus...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,87,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...
127,48,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
116,47,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...
215,45,2026-10-11-00-52-59 +0000,nypost,‘Tiger King’ star Carole Baskin tells Post tha...,https://nypost.com/2026/10/10/world-news/carol...
85,39,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
211,32,2026-10-11-01-41-29 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...
56,31,2026-10-11-19-12-43 +0000,nypost,Horror as person dies after being pulled out t...,https://nypost.com/2026/10/11/us-news/horror-a...
150,31,2026-10-11-10-00-03 +0000,chitri,"Illinois Senate race: Juliana Stratton, F-bomb...",https://www.chicagotribune.com/2026/10/11/illi...
109,30,2026-10-11-14-38-10 +0000,bbc,Ukraine strikes Yandex data centre in third at...,https://www.bbc.co.uk/news/articles/cw0k0g57mk...
123,29,2026-10-11-12-50-00 +0000,wsj,Justice Department Probes TV Networks Over Sus...,https://www.wsj.com/business/media/justice-dep...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)