## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-25-09-11-29 +0000,nyt,Iran War Live Updates: Witkoff and Kushner to ...,https://www.nytimes.com/live/2026/04/25/world/...
1,2026-04-25-09-08-57 +0000,nypost,Louisiana high school senior Martha Odom kille...,https://nypost.com/2026/04/25/us-news/louisian...
2,2026-04-25-09-02-52 +0000,nyt,Trump Seeks to Abolish Iran’s Atomic Stockpile...,https://www.nytimes.com/2026/04/25/us/politics...
3,2026-04-25-09-02-45 +0000,nyt,Tennessee Passed a Slate of Immigration Bills....,https://www.nytimes.com/2026/04/25/us/politics...
4,2026-04-25-09-02-36 +0000,nyt,"Under Trump, Green Card Seekers Face New Scrut...",https://www.nytimes.com/2026/04/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2603/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
26  trump     28
0    iran     20
47    new     16
1     war     14
32     he     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
168,2026-04-24-19-29-21 +0000,cbc,Trump dispatches U.S. envoys to Pakistan for n...,https://www.cbc.ca/news/world/u-s-pakistan-ira...,84
268,2026-04-24-14-30-32 +0000,nypost,Trump DOJ dropping criminal probe of Fed Chair...,https://nypost.com/2026/04/24/us-news/trump-do...,83
107,2026-04-24-21-54-00 +0000,wsj,The Justice Department said it would end its c...,https://www.wsj.com/economy/central-banking/ju...,79
12,2026-04-25-09-00-00 +0000,wsj,"In an interview, Carlson says Trump’s war in I...",https://www.wsj.com/politics/tucker-carlson-tr...,79
0,2026-04-25-09-11-29 +0000,nyt,Iran War Live Updates: Witkoff and Kushner to ...,https://www.nytimes.com/live/2026/04/25/world/...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
168,84,2026-04-24-19-29-21 +0000,cbc,Trump dispatches U.S. envoys to Pakistan for n...,https://www.cbc.ca/news/world/u-s-pakistan-ira...
107,79,2026-04-24-21-54-00 +0000,wsj,The Justice Department said it would end its c...,https://www.wsj.com/economy/central-banking/ju...
275,58,2026-04-24-14-00-00 +0000,wsj,The road to war last year featured rising prof...,https://www.wsj.com/politics/national-security...
56,47,2026-04-25-01-00-00 +0000,wsj,The Trump administration has lobbied against l...,https://www.wsj.com/politics/policy/trump-repu...
85,44,2026-04-24-22-54-14 +0000,bbc,'My living nightmare' - Rob Reiner's son bares...,https://www.bbc.com/news/articles/c74v2enw8l7o...
1,42,2026-04-25-09-08-57 +0000,nypost,Louisiana high school senior Martha Odom kille...,https://nypost.com/2026/04/25/us-news/louisian...
114,40,2026-04-24-21-42-00 +0000,wsj,The Justice Department will end its Powell pro...,https://www.wsj.com/politics/policy/with-powel...
88,38,2026-04-24-22-42-22 +0000,missionlocal,Oculto de la vista: la mitad de los arrestos l...,https://missionlocal.org/2026/04/oculto-de-la-...
42,34,2026-04-25-02-09-41 +0000,nypost,California police warn of app-driven ‘assassin...,https://nypost.com/2026/04/24/us-news/redding-...
32,32,2026-04-25-04-09-50 +0000,nypost,Fed up Venice Beach residents mock city’s home...,https://nypost.com/2026/04/25/us-news/fed-up-v...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)