## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-30-08-15-40 +0000,bbc,Three killed as unfinished building collapses ...,https://www.bbc.com/news/articles/ckgex51zzd8o...
1,2026-03-30-08-15-00 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...
2,2026-03-30-08-12-54 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/30/world/...
3,2026-03-30-08-07-00 +0000,wsj,European Gas Rises on Supply Concerns Ahead of...,https://www.wsj.com/articles/european-gas-rise...
4,2026-03-30-08-03-00 +0000,wsj,Euro Looks Vulnerable to Further Rise in Energ...,https://www.wsj.com/finance/currencies/dollar-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     24
8     iran     22
9      war     19
241     no     12
68      up     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-30-08-15-00 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...,114
150,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...,87
129,2026-03-29-18-00-56 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,75
61,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...,74
25,2026-03-30-05-09-05 +0000,nyt,Trump Says Iran Agreed to Allow 20 More Ships ...,https://www.nytimes.com/2026/03/29/world/middl...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,114,2026-03-30-08-15-00 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...
150,46,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...
186,44,2026-03-29-09-30-00 +0000,wsj,Fed policymakers suggest interest rates could ...,https://www.wsj.com/economy/central-banking/fe...
157,43,2026-03-29-14-35-49 +0000,nypost,Air Canada flight attendant who was ejected du...,https://nypost.com/2026/03/29/world-news/air-c...
179,32,2026-03-29-10-00-00 +0000,latimes,Barabak: Will or won't he? A lot rides on a Tr...,https://www.latimes.com/politics/story/2026-03...
61,28,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...
21,27,2026-03-30-05-38-26 +0000,bbc,Fuel tax halved and free public transport offe...,https://www.bbc.com/news/articles/c937n0yxggeo...
60,27,2026-03-30-01-09-44 +0000,nypost,Scale of carnage at LA’s ‘No Kings’ protest la...,https://nypost.com/2026/03/29/us-news/no-kings...
56,26,2026-03-30-01-22-36 +0000,nypost,"NYC fire that killed child, 3 others in proble...",https://nypost.com/2026/03/29/us-news/nyc-fire...
111,25,2026-03-29-20-11-58 +0000,nypost,"F-16 fighter jets scramble, deploy flares afte...",https://nypost.com/2026/03/29/us-news/palm-bea...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)