## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-24-17-12-28 +0000,nypost,Connecticut school system lets students hide t...,https://nypost.com/2026/04/24/us-news/connecti...
1,2026-04-24-17-12-00 +0000,wsj,Canadian Retail Sales Improve Ahead of Expecte...,https://www.wsj.com/economy/consumers/canadian...
2,2026-04-24-17-11-17 +0000,missionlocal,Over $1M backing Supervisor Stephen Sherrill i...,https://missionlocal.org/2026/04/sf-district-2...
3,2026-04-24-17-10-02 +0000,startribune,Appeals court says Trump's asylum ban at the b...,https://www.startribune.com/appeals-court-says...
4,2026-04-24-17-09-35 +0000,nypost,Teen near $100K goal to bring free swim lesson...,https://nypost.com/2026/04/24/us-news/ali-wrig...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2533/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
30   trump     43
47    iran     22
48     war     21
44     new     16
96  israel     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-04-24-06-56-27 +0000,nypost,"Israel, Lebanon extend cease-fire as Trump see...",https://nypost.com/2026/04/24/world-news/israe...,110
92,2026-04-24-14-30-32 +0000,nypost,Trump DOJ dropping criminal probe of Fed Chair...,https://nypost.com/2026/04/24/us-news/trump-do...,98
227,2026-04-24-03-18-26 +0000,nyt,Trump Says Israel and Lebanon Agree to Extend ...,https://www.nytimes.com/2026/04/23/us/politics...,89
103,2026-04-24-13-59-00 +0000,wsj,The Trump administration announced criminal ch...,https://www.wsj.com/politics/policy/u-s-steps-...,84
310,2026-04-23-21-23-43 +0000,nypost,Trump threatens to ‘finish it up militarily’ i...,https://nypost.com/2026/04/23/us-news/trump-th...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,110,2026-04-24-06-56-27 +0000,nypost,"Israel, Lebanon extend cease-fire as Trump see...",https://nypost.com/2026/04/24/world-news/israe...
100,76,2026-04-24-14-00-00 +0000,wsj,The road to war last year featured rising prof...,https://www.wsj.com/politics/national-security...
92,55,2026-04-24-14-30-32 +0000,nypost,Trump DOJ dropping criminal probe of Fed Chair...,https://nypost.com/2026/04/24/us-news/trump-do...
56,48,2026-04-24-16-01-00 +0000,wsj,The unemployment rate is low. The stock market...,https://www.wsj.com/economy/most-americans-thi...
346,45,2026-04-23-19-19-00 +0000,wsj,Ex-Police Officer Is Accused of Planning Mass ...,https://www.wsj.com/us-news/new-orleans-louisi...
117,43,2026-04-24-13-15-28 +0000,nypost,Benjamin Netanyahu reveals he was quietly trea...,https://nypost.com/2026/04/24/world-news/benja...
363,43,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
283,40,2026-04-23-22-34-54 +0000,nypost,US special forces soldier used secret intel fo...,https://nypost.com/2026/04/23/us-news/us-speci...
21,38,2026-04-24-16-48-45 +0000,nypost,Mamdani to veto NYC schools ‘buffer zone’ bill...,https://nypost.com/2026/04/24/us-news/zohran-m...
194,37,2026-04-24-08-48-30 +0000,nypost,Trump threatens UK PM Starmer with ‘big tariff...,https://nypost.com/2026/04/24/business/trump-t...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)