## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-01-02-57-43 +0000,bbc,Japan raises residency fee for foreign nationa...,https://www.bbc.co.uk/news/articles/c6y8z8xeg8...
1,2026-10-01-02-55-41 +0000,nypost,"Christa Pike still alive, ‘snoring’ after 2 le...",https://nypost.com/2026/09/30/us-news/christa-...
2,2026-10-01-02-51-46 +0000,latimes,'Blowout': Here's who won the Hilton-Becerra d...,https://www.latimes.com/politics/story/2026-09...
3,2026-10-01-02-48-00 +0000,wsj,"Singapore Dollar Edges Lower, Weighed by Highe...",https://www.wsj.com/finance/currencies/yen-con...
4,2026-10-01-02-45-46 +0000,latimes,Lopez: The California I grew up in was full of...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2411/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
195       trump     39
25   california     23
328          ai     22
64        pilot     19
51     flydubai     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
133,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...,192
362,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,144
292,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...,113
435,2026-09-30-08-01-44 +0000,nypost,"Israel-bound plane pilot stabbed by co-pilot, ...",https://nypost.com/2026/09/30/world-news/israe...,109
17,2026-10-01-02-02-55 +0000,nypost,Netanyahu credits heroic Israeli plumber on fl...,https://nypost.com/2026/09/30/world-news/netan...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
133,192,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...
17,102,2026-10-01-02-02-55 +0000,nypost,Netanyahu credits heroic Israeli plumber on fl...,https://nypost.com/2026/09/30/world-news/netan...
58,98,2026-10-01-00-12-00 +0000,wsj,OpenAI co-founder and President Greg Brockman ...,https://www.wsj.com/tech/ai/openai-president-b...
268,80,2026-09-30-17-12-26 +0000,nypost,Trump to announce $54 billion Alaska LNG plant...,https://nypost.com/2026/09/30/us-news/trump-to...
23,66,2026-10-01-01-42-36 +0000,nypost,California governor race heats up as Becerra a...,https://nypost.com/2026/09/30/us-news/steve-hi...
433,62,2026-09-30-08-25-01 +0000,wsj,"Stock Market News, Sept. 30, 2026: 10-Year Tre...",https://www.wsj.com/livecoverage/stock-market-...
12,53,2026-10-01-02-24-58 +0000,nyt,Supreme Court Allows Execution of Christa Pike...,https://www.nytimes.com/2026/09/30/us/christa-...
30,50,2026-10-01-01-20-00 +0000,wsj,Senate Democrats are challenging the legality ...,https://www.wsj.com/politics/national-security...
218,47,2026-09-30-19-14-41 +0000,nypost,CEO of ‘hot girl’ insurance startup Corgi thre...,https://nypost.com/2026/09/30/business/ceo-of-...
405,46,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)