## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-22-14-39 +0000,nypost,"Tree falls on woman, crushes multiple cars in ...",https://nypost.com/2026/05/25/us-news/tree-fal...
1,2026-05-25-22-12-04 +0000,nypost,Nassau Exec Bruce Blakeman vows to keep local ...,https://nypost.com/2026/05/25/us-news/nassau-e...
2,2026-05-25-22-10-41 +0000,nyt,Iran War Live Updates: Negotiations to End the...,https://www.nytimes.com/live/2026/05/25/world/...
3,2026-05-25-22-05-29 +0000,bbc,"Deal with US not imminent, Iran says",https://www.bbc.com/news/articles/cglpp2yk336o...
4,2026-05-25-21-58-35 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/25/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
28    iran     30
294  trump     18
19    deal     18
21     new     10
29     war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
172,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...,103
70,2026-05-25-19-07-57 +0000,wapo,"As new Iran deal faces sharp criticism, Trump ...",https://www.washingtonpost.com/world/2026/05/2...,87
133,2026-05-25-13-51-50 +0000,nypost,Trump demands six Muslim countries join Abraha...,https://nypost.com/2026/05/25/us-news/presiden...,86
83,2026-05-25-17-57-08 +0000,nyt,Trump Urges More Countries to Normalize Relati...,https://www.nytimes.com/2026/05/25/us/politics...,83
123,2026-05-25-15-05-11 +0000,nyt,Trump’s Pressure Had Little Effect on Iran’s T...,https://www.nytimes.com/2026/05/25/world/middl...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
172,103,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...
160,58,2026-05-25-11-01-39 +0000,nypost,Pope Leo issues dire warning on ‘anti-human’ A...,https://nypost.com/2026/05/25/world-news/pope-...
33,43,2026-05-25-21-07-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
27,36,2026-05-25-21-16-21 +0000,nypost,Wet Memorial Day scares off NYC beach crowds —...,https://nypost.com/2026/05/25/us-news/wet-memo...
232,35,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
128,31,2026-05-25-14-20-10 +0000,nypost,Oil prices drop more than 5% after Trump says ...,https://nypost.com/2026/05/25/business/oil-pri...
178,29,2026-05-25-09-01-55 +0000,nyt,He Name-Drops Ocasio-Cortez in His Bid for Con...,https://www.nytimes.com/2026/05/25/us/politics...
112,29,2026-05-25-15-45-27 +0000,bbc,White House gunman had previous run-ins with S...,https://www.bbc.com/news/articles/c1l22pg12mpo...
5,27,2026-05-25-21-56-14 +0000,nypost,Man fatally shot near Yankee Stadium — minutes...,https://nypost.com/2026/05/25/us-news/man-fata...
90,25,2026-05-25-17-16-20 +0000,nypost,Spencer Pratt’s latest campaign ad puts LA’s f...,https://nypost.com/2026/05/25/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)