## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-01-40-09 +0000,nyt,Barn Fire Kills 17 Horses at Harness Track in ...,https://www.nytimes.com/2026/06/16/us/saratoga...
1,2026-06-17-01-38-55 +0000,nypost,"Oklahoma girl, 15, brain dead after dangerous ...",https://nypost.com/2026/06/16/us-news/benadryl...
2,2026-06-17-01-30-00 +0000,nypost,Fans rage at insane Teenage Mutant Ninja Turtl...,https://nypost.com/2026/06/16/us-news/teenage-...
3,2026-06-17-01-28-31 +0000,nypost,Chicago cross-burning feared to be hateful rac...,https://nypost.com/2026/06/16/us-news/chicago-...
4,2026-06-17-01-27-26 +0000,bbc,Musk's SpaceX overtakes Amazon to become world...,https://www.bbc.com/news/articles/cvgd5g7d7gyo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
40   trump     38
61    iran     32
134    new     26
353   deal     19
62     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...,125
6,2026-06-17-01-15-32 +0000,nyt,Iran War Live Updates: Trump Says He Hopes to ...,https://www.nytimes.com/live/2026/06/16/world/...,121
236,2026-06-16-14-53-12 +0000,nypost,Trump says he ‘never cared’ about Iran regime ...,https://nypost.com/2026/06/16/us-news/trump-sa...,120
94,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...,116
238,2026-06-16-14-52-36 +0000,nypost,Trump says he’ll read the text of Iran deal al...,https://nypost.com/2026/06/16/us-news/trump-sa...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,125,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...
202,78,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
345,63,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
22,62,2026-06-17-00-47-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
94,57,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
13,50,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
332,48,2026-06-16-09-00-00 +0000,wsj,The Liberty Justice Center won its biggest-eve...,https://www.wsj.com/politics/policy/how-a-cons...
121,47,2026-06-16-20-59-31 +0000,cbc,Ghanaian midfielder Thomas Partey loses bid to...,https://www.cbc.ca/news/canada/ghana-partey-ca...
191,47,2026-06-16-17-14-32 +0000,nypost,Terrified woman backed out of bungee jump mome...,https://nypost.com/2026/06/16/world-news/woman...
31,40,2026-06-17-00-25-39 +0000,bbc,'It was surreal': British couple describe havi...,https://www.bbc.com/news/articles/c20yzm84r7lo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)