## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-20-53-13 +0000,nypost,150 rally against ‘Zohran the moron’ and antis...,https://nypost.com/2026/09/18/us-news/150-rall...
1,2026-09-18-20-53-02 +0000,wapo,Spanberger takes unusual step to limit data ce...,https://www.washingtonpost.com/politics/2026/0...
2,2026-09-18-20-51-46 +0000,wapo,"African IPO turns people into oil tycoons, and...",https://www.washingtonpost.com/world/2026/09/1...
3,2026-09-18-20-51-43 +0000,nyt,"Trump Says He Has Banned CNN, MS NOW and Polit...",https://www.nytimes.com/2026/09/18/business/me...
4,2026-09-18-20-50-50 +0000,missionlocal,Museum of Craft and Design honors exhibit that...,https://missionlocal.org/2026/09/museum-of-cra...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
25   trump     43
106     ai     21
46     new     20
32   house     19
26      he     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-09-18-19-57-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...,139
346,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,133
76,2026-09-18-18-56-47 +0000,nyt,Judge Who Struck Down Trump’s Compensation Fun...,https://www.nytimes.com/2026/09/18/us/politics...,119
13,2026-09-18-20-34-01 +0000,latimes,"Trump says he's banning CNN, MS NOW and Politi...",https://www.latimes.com/entertainment-arts/bus...,118
11,2026-09-18-20-35-12 +0000,wapo,"Trump says he’s banning CNN, MS NOW and Politi...",https://www.washingtonpost.com/business/2026/0...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,139,2026-09-18-19-57-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...
104,82,2026-09-18-17-51-00 +0000,wsj,A new Federal Reserve inquiry into the 2023 co...,https://www.wsj.com/economy/central-banking/ne...
348,75,2026-09-17-23-40-47 +0000,latimes,Uber must pay $40 million to family of woman k...,https://www.latimes.com/california/story/2026-...
29,73,2026-09-18-20-11-46 +0000,nypost,"Inside the phony, incestuous web of woke AI ‘w...",https://nypost.com/2026/09/18/business/inside-...
250,57,2026-09-18-10-54-02 +0000,nypost,Warren Buffett steps down as Berkshire chairma...,https://nypost.com/2026/09/18/business/berkshi...
290,52,2026-09-18-08-56-00 +0000,wsj,The Bank of Japan lifted its benchmark interes...,https://www.wsj.com/economy/central-banking/ba...
366,51,2026-09-17-22-48-50 +0000,latimes,Governor's race heats up as Becerra meets fire...,https://www.latimes.com/california/story/2026-...
354,49,2026-09-17-23-20-15 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-pu...
147,45,2026-09-18-15-59-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
64,42,2026-09-18-19-11-43 +0000,latimes,Driver accused in fatal Metro bus crash had mu...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)