## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-10-00-37 +0000,bbc,Record temperatures drives up home air conditi...,https://www.bbc.co.uk/news/articles/c1wyl2glg9...
1,2026-06-26-09-56-55 +0000,nyt,Venezuela Live Updates: More Rescuers Join Urg...,https://www.nytimes.com/live/2026/06/26/world/...
2,2026-06-26-09-56-53 +0000,nyt,Venezuelans Search Desperately for Loved Ones ...,https://www.nytimes.com/2026/06/25/world/ameri...
3,2026-06-26-09-54-49 +0000,nyt,Stocks in Asia Tumble as A.I. Uncertainty Jolt...,https://www.nytimes.com/2026/06/26/business/oi...
4,2026-06-26-09-54-00 +0000,wsj,"Evonik Raises Guidance on Higher Prices, Cost ...",https://www.wsj.com/business/earnings/evonik-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
137      trump     37
60         new     23
150      court     23
607    supreme     22
7    venezuela     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
326,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...,121
313,2026-06-25-14-49-39 +0000,latimes,"Trump may end legal protection for 350,000 Hai...",https://www.latimes.com/politics/story/2026-06...,111
155,2026-06-25-22-10-20 +0000,nyt,Supreme Court Expands Trump’s Power Over Immig...,https://www.nytimes.com/2026/06/25/us/politics...,106
267,2026-06-25-17-06-15 +0000,nyt,Supreme Court Allows Trump to Block Asylum See...,https://www.nytimes.com/2026/06/25/us/politics...,103
320,2026-06-25-14-39-46 +0000,nypost,Supreme Court rules Trump can remove deportati...,https://nypost.com/2026/06/25/us-news/supreme-...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
326,121,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...
103,80,2026-06-26-01-08-00 +0000,wsj,California’s proposed billionaire tax will app...,https://www.wsj.com/politics/policy/california...
106,74,2026-06-26-01-00-00 +0000,wsj,New York City’s business elites are overhaulin...,https://www.wsj.com/politics/policy/wall-stree...
87,63,2026-06-26-02-27-09 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/2026/06/25/world/ameri...
81,59,2026-06-26-02-56-25 +0000,nypost,"Iran, Egypt outraged over ‘Pride Match’ design...",https://nypost.com/2026/06/25/sports/iran-egyp...
266,49,2026-06-25-17-10-22 +0000,nyt,See Record-Breaking Extreme Heat Wave Across E...,https://www.nytimes.com/2026/06/24/world/europ...
201,47,2026-06-25-20-27-32 +0000,nyt,Oil Prices Jump After Attack Halts Shipping in...,https://www.nytimes.com/2026/06/25/business/oi...
307,41,2026-06-25-15-16-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
221,36,2026-06-25-19-41-00 +0000,wsj,Watch how American and British sailors test so...,https://www.wsj.com/politics/national-security...
352,35,2026-06-25-12-56-53 +0000,nypost,JPMorgan sets up new horse race to succeed CEO...,https://nypost.com/2026/06/25/business/jpmorga...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)