## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-14-21-09-00 +0000,wsj,Alcoa Receives International Approval for Gall...,https://www.wsj.com/business/alcoa-receives-in...
1,2026-07-14-21-08-00 +0000,wsj,Auto & Transport Roundup: Market Talk,https://www.wsj.com/business/auto-transport-ro...
2,2026-07-14-21-07-32 +0000,nyt,5 New Roller Coasters to Make You Scream This ...,https://www.nytimes.com/2026/07/13/travel/new-...
3,2026-07-14-21-07-00 +0000,wsj,New York City Officials Inspecting Other Build...,https://www.wsj.com/us-news/new-york-city-offi...
4,2026-07-14-21-06-25 +0000,nypost,Frightening footage shows insanity at Yosemite...,https://nypost.com/2026/07/14/us-news/yosemite...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
110      trump     29
172       iran     18
13         new     16
74   inflation     15
243        ice     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-07-14-17-15-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...,104
215,2026-07-14-11-08-00 +0000,wsj,Will President Trump reimposing his “blockade”...,https://www.wsj.com/politics/for-whom-the-stra...,101
301,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...,94
147,2026-07-14-16-06-00 +0000,wsj,The Battle for Hormuz: Trump Shifts Into Dange...,https://www.wsj.com/world/middle-east/the-batt...,90
28,2026-07-14-20-29-00 +0000,wsj,"Trump Reverses 20% Strait of Hormuz Toll, U.S....",https://www.wsj.com/world/middle-east/trump-ir...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,104,2026-07-14-17-15-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...
37,79,2026-07-14-20-15-00 +0000,wsj,Chairman Kevin Warsh pledged to lawmakers that...,https://www.wsj.com/economy/central-banking/wa...
64,59,2026-07-14-19-31-03 +0000,nypost,NYC fiend who killed ex as she pushed their ba...,https://nypost.com/2026/07/14/us-news/nyc-fien...
135,57,2026-07-14-16-40-54 +0000,nypost,"Iran claims attacks on Bahrain, Jordan, Strait...",https://nypost.com/2026/07/14/world-news/iran-...
304,57,2026-07-14-00-00-00 +0000,wsj,"In Washington, He Was a Power Broker. In South...",https://www.wsj.com/us-news/in-washington-he-w...
86,39,2026-07-14-18-54-17 +0000,bbc,ICE told to halt most vehicle stops after pair...,https://www.bbc.co.uk/news/articles/cly8yrw597...
272,37,2026-07-14-03-51-12 +0000,nyt,Paramount-Warner Bros. Merger Is Challenged in...,https://www.nytimes.com/2026/07/13/business/pa...
26,32,2026-07-14-20-32-00 +0000,wsj,"Americans got a break on inflation in June, wi...",https://www.wsj.com/economy/cpi-inflation-repo...
222,32,2026-07-14-10-44-14 +0000,cbc,Death toll from Bangkok music bar fire rises t...,https://www.cbc.ca/news/world/bangkok-bar-fire...
80,31,2026-07-14-19-02-00 +0000,wsj,Columbia University protester Mahmoud Khalil h...,https://www.wsj.com/us-news/law/mahmoud-khalil...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)