## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-11-23-00 +0000,wsj,"U.S. Treasury Yields Edge Up, Dollar Weakens",https://www.wsj.com/finance/investing/jgb-futu...
1,2026-04-27-11-22-00 +0000,wsj,Re/Max Is Being Sold to a Tech-Focused Real-Es...,https://www.wsj.com/business/deals/re-max-near...
2,2026-04-27-11-20-00 +0000,wsj,Nordex Shares Hit 24-year High after Earnings ...,https://www.wsj.com/business/earnings/nordex-s...
3,2026-04-27-11-17-15 +0000,bbc,Labour figures criticise calls for inquiry int...,https://www.bbc.com/news/articles/c3r3r2vzjp1o...
4,2026-04-27-11-11-09 +0000,nyt,"Dinner, Interrupted: Over Brunch, Journalists ...",https://www.nytimes.com/2026/04/26/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

               word  score
99            trump     33
312        shooting     26
30           dinner     24
67   correspondents     16
194             war     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
125,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,168
257,2026-04-26-12-50-33 +0000,cbc,Trump says he 'wasn't worried' during correspo...,https://www.cbc.ca/news/world/livestory/white-...,139
236,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...,130
167,2026-04-26-21-46-52 +0000,nypost,Witness describes the moment gunman Cole Allen...,https://nypost.com/2026/04/26/us-news/witness-...,129
119,2026-04-27-04-24-19 +0000,bbc,Trump says he 'wasn't worried' during Washingt...,https://www.bbc.com/news/articles/c2d8dg57rzdo...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
125,168,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
151,83,2026-04-26-23-04-26 +0000,nypost,King Charles’s royal visit to Washington still...,https://nypost.com/2026/04/26/world-news/king-...
23,59,2026-04-27-10-57-18 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
63,49,2026-04-27-09-30-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
13,48,2026-04-27-11-00-00 +0000,nypost,Do you have what it takes to be an NYC bus dri...,https://nypost.com/2026/04/27/lifestyle/the-po...
231,43,2026-04-26-16-47-42 +0000,nypost,WHCD shooting suspect Cole Allen mocked lack o...,https://nypost.com/2026/04/26/us-news/whcd-sho...
236,36,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...
97,32,2026-04-27-07-56-56 +0000,nypost,Texas nurse Sarah Danh’s family shares health ...,https://nypost.com/2026/04/27/us-news/texas-nu...
52,31,2026-04-27-10-00-00 +0000,startribune,Minnesota 12-year-old is first in new trial of...,https://www.startribune.com/minnesota-12-year-...
67,31,2026-04-27-09-27-55 +0000,nypost,Elon Musk and OpenAI CEO Sam Altman head to co...,https://nypost.com/2026/04/27/business/elon-mu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)