## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-01-19-48 +0000,nypost,US military launches airstrikes on Iran after ...,https://nypost.com/2026/07/29/us-news/us-milit...
1,2026-07-30-01-16-41 +0000,nyt,Iran War Live Updates: U.S. Begins New Wave of...,https://www.nytimes.com/live/2026/07/28/world/...
2,2026-07-30-01-15-51 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/28/world/...
3,2026-07-30-01-15-01 +0000,nyt,Senators Cornyn and Tillis Threaten to Block B...,https://www.nytimes.com/2026/07/29/us/politics...
4,2026-07-30-01-08-06 +0000,nypost,Video shows quick-thinking mom using gas pump ...,https://nypost.com/2026/07/29/us-news/video-sh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2444/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
24  trump     33
3    iran     26
12    new     23
58    fed     17
42  fauci     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
287,2026-07-29-12-46-38 +0000,nypost,Trump says US will ‘beat the f–king s–t’ out o...,https://nypost.com/2026/07/29/us-news/trump-sa...,106
1,2026-07-30-01-16-41 +0000,nyt,Iran War Live Updates: U.S. Begins New Wave of...,https://www.nytimes.com/live/2026/07/28/world/...,103
27,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,102
154,2026-07-29-20-10-38 +0000,nypost,Trump and Netanyahu discussed ‘big three’ op...,https://nypost.com/2026/07/29/us-news/trump-an...,92
157,2026-07-29-19-56-01 +0000,wapo,Trump threatens to hit Iran ‘hard’ following m...,https://www.washingtonpost.com/national-securi...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
287,106,2026-07-29-12-46-38 +0000,nypost,Trump says US will ‘beat the f–king s–t’ out o...,https://nypost.com/2026/07/29/us-news/trump-sa...
305,77,2026-07-29-11-06-00 +0000,wsj,"New York City Mayor Zohran Mamdani, not even e...",https://www.wsj.com/politics/mamdani-digs-back...
130,74,2026-07-29-20-57-00 +0000,wsj,The Fed held interest rates steady on a 9-3 vo...,https://www.wsj.com/economy/central-banking/fe...
27,67,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
198,66,2026-07-29-17-51-00 +0000,wsj,Dr. Anthony Fauci invoked the Fifth Amendment ...,https://www.wsj.com/politics/policy/anthony-fa...
359,53,2026-07-29-07-20-21 +0000,nypost,Russia charges Telegram founder Pavel Durov wi...,https://nypost.com/2026/07/29/world-news/teleg...
8,44,2026-07-30-00-56-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...
205,40,2026-07-29-17-15-25 +0000,cbc,"Ottawa plans to end 'Netflix tax,' replace wit...",https://www.cbc.ca/news/politics/cancon-online...
376,40,2026-07-29-03-10-20 +0000,chitri,Rescuers search for the missing after Japan ea...,https://www.chicagotribune.com/2026/07/28/kuma...
145,37,2026-07-29-20-23-21 +0000,nyt,Oil Prices Rise as Iran and U.S. Strikes Slow ...,https://www.nytimes.com/2026/07/29/business/oi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)