## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-12-23-02-18 +0000,nypost,"Atlanta teen, 14, arrested for fatal shooting ...",https://nypost.com/2026/04/12/us-news/atlanta-...
1,2026-04-12-22-57-22 +0000,bbc,Trump's blockade threat raises risks and leave...,https://www.bbc.com/news/articles/c8dl5mly2rzo...
2,2026-04-12-22-55-24 +0000,nyt,Iran War Live Updates: U.S. to Blockade Ships ...,https://www.nytimes.com/live/2026/04/12/world/...
3,2026-04-12-22-55-23 +0000,nyt,Iran’s Top Negotiator Says Talks Failed Becaus...,https://www.nytimes.com/2026/04/12/world/middl...
4,2026-04-12-22-48-22 +0000,bbc,Democrats join calls to expel Eric Swalwell fr...,https://www.bbc.com/news/articles/cn0wz1k9ekeo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2582/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
15      iran     37
7      trump     23
24     talks     21
34  swalwell     14
16       war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...,132
5,2026-04-12-22-38-11 +0000,wapo,Trump announces naval blockade of Iran after I...,https://www.washingtonpost.com/world/2026/04/1...,106
87,2026-04-12-17-52-32 +0000,nypost,Iran issues dire warning about President Trump...,https://nypost.com/2026/04/12/world-news/iran-...,102
133,2026-04-12-13-16-09 +0000,nypost,Trump announces blockade of Strait of Hormuz a...,https://nypost.com/2026/04/12/us-news/trump-an...,101
16,2026-04-12-22-19-00 +0000,wsj,Trump Weighs Limited Strikes Against Iran Afte...,https://www.wsj.com/world/middle-east/trump-we...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,132,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...
206,85,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
59,82,2026-04-12-19-50-52 +0000,nypost,Hungary’s Viktor Orbán concedes defeat after ‘...,https://nypost.com/2026/04/12/world-news/hunga...
88,37,2026-04-12-17-47-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
157,35,2026-04-12-09-30-00 +0000,wsj,Recent months have been marked by slower growt...,https://www.wsj.com/economy/inflation-growth-a...
183,32,2026-04-12-04-01-32 +0000,nyt,Many Polls Say Orban Will Lose. But He Has an ...,https://www.nytimes.com/2026/04/12/world/europ...
168,31,2026-04-12-09-00-00 +0000,wsj,Jeanine Pirro’s ability to manage a mercurial ...,https://www.wsj.com/politics/policy/judge-jean...
63,29,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
32,26,2026-04-12-21-40-30 +0000,startribune,Four arrested at protest outside Whipple Build...,https://www.startribune.com/turning-point-jour...
135,24,2026-04-12-12-55-17 +0000,cbc,"Ukraine, Russia accuse each other of violating...",https://www.cbc.ca/news/world/ukraine-russia-e...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)