## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-14-41-49 +0000,bbc,'Childhood memories' - why nostalgia wasn't en...,https://www.bbc.com/news/articles/cdxkxxvd3z4o...
1,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
2,2026-04-28-14-38-00 +0000,wsj,There’s a Revolution in Cancer. But Can Big Ph...,https://www.wsj.com/finance/investing/theres-a...
3,2026-04-28-14-37-36 +0000,startribune,Live: FBI raids 22 sites in Minnesota fraud probe,https://www.startribune.com/fbi-fraud-raid-min...
4,2026-04-28-14-36-16 +0000,nyt,One Person Who Appears to Be Missing From King...,https://www.nytimes.com/2026/04/28/us/prince-h...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2436/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
82      trump     50
84       iran     23
201     house     17
234  shooting     15
33       king     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
106,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,173
135,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,122
193,2026-04-28-04-19-15 +0000,nypost,Jimmy Kimmel repeats ‘hateful’ joke about ‘exp...,https://nypost.com/2026/04/28/us-news/jimmy-ki...,122
86,2026-04-28-11-44-00 +0000,wsj,"Pushing past a third assassination attempt, th...",https://www.wsj.com/politics/policy/pushing-pa...,115
210,2026-04-28-02-07-55 +0000,nypost,Mentalist Oz Pearlman won’t appear on ‘Jimmy K...,https://nypost.com/2026/04/27/us-news/mentalis...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
106,173,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
23,93,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
185,74,2026-04-28-05-33-17 +0000,bbc,In pictures: King Charles and Queen Camilla at...,https://www.bbc.com/news/articles/c86e6z26xdpo...
217,56,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...
295,54,2026-04-27-20-08-59 +0000,latimes,OpenAI CEO Sam Altman apologizes for not alert...,https://www.latimes.com/business/story/2026-04...
1,43,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
292,40,2026-04-27-20-12-55 +0000,nyt,Iran Offers Plan to Focus on Strait of Hormuz ...,https://www.nytimes.com/2026/04/27/world/middl...
130,38,2026-04-28-10-00-00 +0000,latimes,Supreme Court will hear Trump's bid to end leg...,https://www.latimes.com/politics/story/2026-04...
12,36,2026-04-28-14-21-00 +0000,wsj,China’s Ban on Meta-Manus Deal Shows Strains i...,https://www.wsj.com/world/china/chinas-ban-on-...
316,36,2026-04-27-18-07-33 +0000,nypost,California’s billionaire tax gamble — insiders...,https://nypost.com/2026/04/27/business/billion...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)