## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-05-44-43 +0000,latimes,"Cars, parking lot set ablaze in Wilmington — f...",https://www.latimes.com/california/story/2026-...
1,2026-07-04-05-38-26 +0000,nyt,"At Mount Rushmore, Trump Veers From Patriotism...",https://www.nytimes.com/2026/07/03/us/politics...
2,2026-07-04-05-25-47 +0000,nypost,"Iranians mourn late Ayatollah Khamenei, whose ...",https://nypost.com/2026/07/04/us-news/iranians...
3,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
4,2026-07-04-04-44-52 +0000,nypost,Astronomers discover Earth’s new ‘next-door ne...,https://nypost.com/2026/07/04/us-news/earths-n...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     23
102     th     13
82   world     11
46     new      9
72    iran      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...,71
19,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,67
173,2026-07-03-11-55-27 +0000,nypost,What to expect at Trump’s epic 4th of July ‘Sa...,https://nypost.com/2026/07/03/us-news/what-to-...,65
79,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...,63
12,2026-07-04-03-51-20 +0000,nypost,Trump rails against ‘mortal threat’ of communi...,https://nypost.com/2026/07/03/us-news/trump-ra...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,71,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
168,54,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
49,48,2026-07-04-00-00-00 +0000,wsj,Capital Account: The 250th anniversary of the ...,https://www.wsj.com/economy/american-instituti...
26,43,2026-07-04-01-55-12 +0000,nypost,"Tourists stumble upon Taylor Swift, Travis Kel...",https://nypost.com/2026/07/03/us-news/tourists...
79,40,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
128,33,2026-07-03-15-20-57 +0000,bbc,Ukrainian suspect hunted by police after Monac...,https://www.bbc.co.uk/news/articles/c4gy603z2q...
127,30,2026-07-03-15-31-54 +0000,nypost,Americans hit the road in record numbers for 4...,https://nypost.com/2026/07/03/business/america...
111,29,2026-07-03-16-40-03 +0000,nypost,Russia deploying new jet-powered drones that r...,https://nypost.com/2026/07/03/world-news/russi...
68,28,2026-07-03-21-26-53 +0000,bbc,Starmer tells of 'intensely personal' decision...,https://www.bbc.co.uk/news/articles/c0qy2zxjkw...
152,27,2026-07-03-13-29-04 +0000,nyt,Cape Verde Faces Argentina’s World Cup Juggern...,https://www.nytimes.com/2026/07/03/world/afric...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)