## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-11-55-12 +0000,bbc,Hurricane Isaias downgraded after making landf...,https://www.bbc.co.uk/news/articles/c3vgx4450v...
1,2026-10-10-11-51-00 +0000,wsj,Hurricane Isaias Makes Landfall in Florida,https://www.wsj.com/us-news/climate-environmen...
2,2026-10-10-11-39-58 +0000,nypost,Five dead after late-night mass shooting in Ge...,https://nypost.com/2026/10/10/us-news/five-fou...
3,2026-10-10-11-30-00 +0000,bbc,Money Box,https://www.bbc.co.uk/sounds/play/m0032qlk?at_...
4,2026-10-10-11-24-25 +0000,nypost,Israeli mom whose son was murdered on Oct. 7 n...,https://nypost.com/2026/10/10/world-news/israe...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2384/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
71   trump     49
205    new     23
77   nobel     17
79   prize     16
216     he     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
160,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,221
98,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...,143
172,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,136
291,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...,126
181,2026-10-09-21-00-22 +0000,wapo,Trump hits International Criminal Court with s...,https://www.washingtonpost.com/world/2026/10/0...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
160,221,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
244,96,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...
138,83,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
132,61,2026-10-09-22-38-00 +0000,wsj,The planned execution of Nidal Hasan has spark...,https://www.wsj.com/politics/national-security...
328,57,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
206,54,2026-10-09-19-55-00 +0000,wapo,Ocasio-Cortez will stump for Abdul El-Sayed in...,https://www.washingtonpost.com/politics/2026/1...
320,47,2026-10-09-14-13-06 +0000,nypost,Dow soars as tech shares rebound on SpaceX dea...,https://nypost.com/2026/10/09/business/stocks-...
62,46,2026-10-10-06-44-48 +0000,nypost,Hurricane Isaias hit Florida ‘like a freight t...,https://nypost.com/2026/10/10/us-news/hurrican...
225,43,2026-10-09-18-53-36 +0000,nypost,Flydubai co-pilot was inspired by 9/11 when he...,https://nypost.com/2026/10/09/world-news/flydu...
14,42,2026-10-10-10-06-23 +0000,bbc,Rogue Anthropic AI agent gave police fake tip ...,https://www.bbc.co.uk/news/articles/cqkg50j1yd...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)