## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-26-17-11-30 +0000,nypost,Netanyahu claims Mamdani ‘celebrated’ Oct. 7 a...,https://nypost.com/2026/07/26/us-news/netanyah...
1,2026-07-26-17-09-30 +0000,nypost,Final minutes of ex-NYPD cop’s innocent 12-yea...,https://nypost.com/2026/07/26/us-news/final-mi...
2,2026-07-26-17-08-00 +0000,wsj,Opinion | Keiko Fujimori and Peru’s China Chal...,https://www.wsj.com/opinion/keiko-fujimori-and...
3,2026-07-26-17-07-00 +0000,wsj,Opinion | How to Beat China and Make AI Safe,https://www.wsj.com/opinion/how-to-beat-china-...
4,2026-07-26-17-00-00 +0000,wsj,"How different groups of Democrats—leadership, ...",https://www.wsj.com/politics/policy/israel-aid...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
179   trump     18
57     iran     11
274  attack     11
275  berlin     10
173     war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
22,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,57
54,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,57
163,2026-07-25-19-40-41 +0000,nypost,Trump pauses Iran strikes as US weighs next mo...,https://nypost.com/2026/07/25/world-news/trump...,54
34,2026-07-26-15-17-33 +0000,chitri,German police hunt suspect in attack near Berl...,https://www.chicagotribune.com/2026/07/26/berl...,49
36,2026-07-26-15-09-44 +0000,nyt,Officials Call Attack Near Berlin Pride Celebr...,https://www.nytimes.com/2026/07/26/world/europ...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
22,57,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
34,49,2026-07-26-15-17-33 +0000,chitri,German police hunt suspect in attack near Berl...,https://www.chicagotribune.com/2026/07/26/berl...
27,38,2026-07-26-16-02-54 +0000,nypost,NY pols ripped for cozying up to accused crimi...,https://nypost.com/2026/07/26/us-news/ny-pols-...
8,31,2026-07-26-16-52-07 +0000,nyt,Live Updates: Extreme Heat and Strong Winds Fu...,https://www.nytimes.com/live/2026/07/26/world/...
144,30,2026-07-25-21-52-05 +0000,nypost,"Kids YouTuber Ms. Rachel gave $3,000 to anti-I...",https://nypost.com/2026/07/25/us-news/kids-you...
65,28,2026-07-26-12-49-15 +0000,nyt,U.S.-Iran War Pauses for 2nd Straight Day With...,https://www.nytimes.com/2026/07/26/world/middl...
83,25,2026-07-26-10-00-00 +0000,wsj,A documentary filmmaker followed Sen. Lindsey ...,https://www.wsj.com/politics/national-security...
16,24,2026-07-26-16-45-54 +0000,nypost,"Up-and-coming NYC real estate broker, 29, kill...",https://nypost.com/2026/07/26/us-news/up-and-c...
24,23,2026-07-26-16-09-43 +0000,cbc,2 mosques in the West Bank set on fire during ...,https://www.cbc.ca/news/world/west-bank-mosque...
134,23,2026-07-26-00-00-00 +0000,wsj,A WSJ midterms profile: Traditional liberal Sh...,https://www.wsj.com/politics/elections/ohio-se...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)