## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-21-03-41 +0000,bbc,Republicans unveil plan to end partial governm...,https://www.bbc.com/news/articles/cly63j5y97yo...
1,2026-04-01-21-02-38 +0000,nyt,Tennessee Library Director Luanne James Fired ...,https://www.nytimes.com/2026/04/01/us/tennesse...
2,2026-04-01-21-00-04 +0000,nypost,Cops rush to Nicki Minaj’s mansion as man stal...,https://nypost.com/2026/04/01/entertainment/co...
3,2026-04-01-21-00-00 +0000,wsj,Opinion | A Mideast Moment of Hope,https://www.wsj.com/opinion/a-mideast-moment-o...
4,2026-04-01-20-58-00 +0000,wsj,Opinion | A Canadian CEO Is Lost in Translation,https://www.wsj.com/opinion/a-canadian-ceo-is-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
57        trump     59
88         iran     54
47          war     44
55   birthright     22
56  citizenship     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
26,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...,202
263,2026-04-01-08-49-19 +0000,bbc,Oil briefly falls below $100 and shares jump o...,https://www.bbc.com/news/articles/c2489v97842o...,178
13,2026-04-01-20-44-51 +0000,nyt,Iran War Live Updates: Hours Before Speech to ...,https://www.nytimes.com/live/2026/04/01/world/...,176
49,2026-04-01-19-11-50 +0000,bbc,Rachel Reeves says she's angry at Trump's deci...,https://www.bbc.com/news/articles/c625v1l4l29o...,174
97,2026-04-01-17-16-58 +0000,nypost,Iran rejects Trump’s claim of cease-fire reque...,https://nypost.com/2026/04/01/world-news/iran-...,174

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
26,202,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...
157,107,2026-04-01-14-51-47 +0000,nyt,Lawyer Arguing at Supreme Court to Save Birthr...,https://www.nytimes.com/2026/04/01/us/politics...
35,67,2026-04-01-19-52-00 +0000,wsj,President Trump endorsed Senate Republicans’ t...,https://www.wsj.com/politics/policy/trump-lays...
376,52,2026-03-31-21-17-00 +0000,wsj,Stocks Cap March With ‘Hormuz Hope’ Rally on P...,https://www.wsj.com/finance/stocks/wall-street...
322,50,2026-04-01-00-10-00 +0000,wsj,President Trump signed an executive order Tues...,https://www.wsj.com/politics/policy/trump-orde...
147,46,2026-04-01-15-16-14 +0000,nypost,Kristi Noem’s hometown pals in disbelief over ...,https://nypost.com/2026/04/01/us-news/kristi-n...
350,46,2026-03-31-22-39-56 +0000,latimes,"He killed girlfriend's lover in SoCal, then ki...",https://www.latimes.com/california/story/2026-...
213,46,2026-04-01-11-00-00 +0000,nypost,Space boss rep teases plans to transform moon ...,https://nypost.com/2026/04/01/us-news/space-bo...
356,40,2026-03-31-22-15-00 +0000,nypost,What you’re *actually* buying when you buy Bit...,https://nypost.com/business/bitcoin-investment...
64,40,2026-04-01-18-49-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)