## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-17-31-24 +0000,bbc,From tourist tax to digital ID: BBC correspond...,https://www.bbc.com/news/articles/c1j2nr8kgk3o...
1,2026-05-13-17-28-55 +0000,nyt,U.S. and Mexican Officials Deny C.I.A. Had Let...,https://www.nytimes.com/2026/05/12/world/ameri...
2,2026-05-13-17-28-32 +0000,nypost,NYU Langone Health hit with federal grand jury...,https://nypost.com/2026/05/13/us-news/nyu-lang...
3,2026-05-13-17-28-00 +0000,wsj,Geothermal-Champion Fervo Energy’s Shares Soar...,https://www.wsj.com/business/energy-oil/geothe...
4,2026-05-13-17-26-10 +0000,nyt,King’s Speech Comes at an Awkward Time for Sta...,https://www.nytimes.com/2026/05/13/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
200  trump     56
202  china     21
61    iran     21
62     war     20
134    new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
368,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,140
91,2026-05-13-15-04-52 +0000,nyt,Trump Is in China as Iran War Continues With N...,https://www.nytimes.com/2026/05/13/world/middl...,130
288,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,128
30,2026-05-13-16-53-28 +0000,nyt,"For Trump, the Iran War Looms Over China Summit",https://www.nytimes.com/2026/05/13/us/politics...,128
23,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
368,140,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...
288,72,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
314,69,2026-05-12-22-09-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
266,62,2026-05-13-01-20-35 +0000,nypost,Cindy Burbank — who plans to drop out of gener...,https://nypost.com/2026/05/12/us-news/cindy-bu...
261,52,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
75,46,2026-05-13-15-33-23 +0000,nyt,Alex Murdaugh Murder Convictions Overturned by...,https://www.nytimes.com/2026/05/13/us/murdaugh...
378,44,2026-05-12-18-39-39 +0000,nypost,WHO warns that more hantavirus cases are likel...,https://nypost.com/2026/05/12/world-news/who-s...
85,43,2026-05-13-15-12-25 +0000,nypost,Epstein victim says he raped her while he was ...,https://nypost.com/2026/05/13/us-news/epstein-...
118,41,2026-05-13-14-00-00 +0000,wsj,Vice President JD Vance is planning to deliver...,https://www.wsj.com/politics/policy/trump-jd-v...
354,36,2026-05-12-20-20-20 +0000,nyt,Inflation Jumps as War-Driven Energy Costs Dri...,https://www.nytimes.com/2026/05/12/business/oi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)