## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
1,2026-07-06-17-35-00 +0000,cbc,Republican bill targets Canada's provincial bo...,https://www.cbc.ca/news/world/provincial-restr...
2,2026-07-06-17-33-43 +0000,bbc,Charlie Kirk's family attends hearing for susp...,https://www.bbc.co.uk/news/articles/c1myyyyjvx...
3,2026-07-06-17-26-04 +0000,nypost,White House tears into ‘extreme political acti...,https://nypost.com/2026/07/06/us-news/white-ho...
4,2026-07-06-17-25-35 +0000,nypost,Erika Kirk exits courtroom as witness describe...,https://nypost.com/2026/07/06/us-news/erika-ki...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
1      trump     37
22     world     18
278      cup     11
378     nato     11
271  funeral     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...,141
254,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...,119
148,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...,110
187,2026-07-06-09-00-11 +0000,nyt,Emil Bove Defended Trump in Court. Then Trump ...,https://www.nytimes.com/2026/07/06/us/emil-bov...,97
93,2026-07-06-14-43-53 +0000,nypost,Trump says he asked FIFA for review of Folarin...,https://nypost.com/2026/07/06/sports/trump-say...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,141,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
280,51,2026-07-05-18-20-53 +0000,nypost,Ex-Dem activist Calla Walsh attends Khamenei’s...,https://nypost.com/2026/07/05/world-news/calla...
173,49,2026-07-06-09-31-20 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
254,47,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...
63,39,2026-07-06-15-36-27 +0000,nypost,Erika Kirk wipes away tears as she confronts h...,https://nypost.com/2026/07/06/us-news/erika-ki...
61,39,2026-07-06-15-42-23 +0000,nypost,Body found in search for football player Nolan...,https://nypost.com/2026/07/06/us-news/body-fou...
193,32,2026-07-06-08-09-00 +0000,wsj,Comcast’s Sky to Buy ITV’s Media and Entertain...,https://www.wsj.com/business/deals/comcasts-sk...
105,31,2026-07-06-14-24-12 +0000,nypost,"25 dead, nearly 100 injured in violent clashes...",https://nypost.com/2026/07/06/world-news/25-de...
11,30,2026-07-06-17-13-00 +0000,wsj,"What to know about ‘Trump Accounts,’ the new s...",https://www.wsj.com/personal-finance/trump-acc...
230,30,2026-07-06-00-08-09 +0000,latimes,California woman killed by Florida alligator. ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)