## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-17-47-09 +0000,bbc,"Nor'easter storm brings coastal flooding, as N...",https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
1,2026-09-26-17-45-31 +0000,nypost,Ukraine airdrops killer robots behind enemy li...,https://nypost.com/2026/09/26/world-news/ukrai...
2,2026-09-26-17-39-41 +0000,nypost,"Teen dies, 12 injured after car full of firewo...",https://nypost.com/2026/09/26/world-news/car-f...
3,2026-09-26-17-30-15 +0000,nypost,LA mayoral candidate Nithya Raman backs Donald...,https://nypost.com/2026/09/26/us-news/nithya-r...
4,2026-09-26-17-27-38 +0000,nypost,Pope Leo draws record-breaking crowd of 800K a...,https://nypost.com/2026/09/26/world-news/pope-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2321/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41   trump     58
6      new     19
445     xi     15
103   iran     13
321    was     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...,149
56,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...,128
60,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...,121
242,2026-09-25-20-02-20 +0000,nypost,Trump told China’s Xi that support for Iran wa...,https://nypost.com/2026/09/25/us-news/trump-to...,118
120,2026-09-26-07-03-34 +0000,nypost,Ukraine’s Zelensky says he urged Trump to enli...,https://nypost.com/2026/09/26/world-news/ukrai...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,149,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...
60,63,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...
242,60,2026-09-25-20-02-20 +0000,nypost,Trump told China’s Xi that support for Iran wa...,https://nypost.com/2026/09/25/us-news/trump-to...
130,50,2026-09-26-02-36-07 +0000,chitri,President Trump said he would campaign in midt...,https://www.chicagotribune.com/2026/09/25/trum...
53,47,2026-09-26-14-24-32 +0000,nypost,Russian attacks kill 4 across Ukraine days aft...,https://nypost.com/2026/09/26/world-news/russi...
59,41,2026-09-26-14-05-01 +0000,cbc,Hundreds of thousands turn out for Pope Leo al...,https://www.cbc.ca/news/world/pope-leo-parade-...
165,40,2026-09-25-23-10-33 +0000,nyt,Report Finds Security Failings at Event Where ...,https://www.nytimes.com/2026/09/25/us/utah-val...
180,40,2026-09-25-22-30-36 +0000,latimes,"For third time, Supreme Court rejects Missouri...",https://www.latimes.com/politics/story/2026-09...
277,33,2026-09-25-18-36-09 +0000,nypost,Costco to land in yet another California city ...,https://nypost.com/2026/09/25/business/new-nor...
23,31,2026-09-26-15-53-09 +0000,nypost,Trump to attend major Texas vs. Tennessee coll...,https://nypost.com/2026/09/26/sports/trump-to-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)