## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-21-12-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...
1,2026-05-07-21-11-59 +0000,nypost,Child sex abuse probe launched at posh NYC pre...,https://nypost.com/2026/05/07/us-news/child-se...
2,2026-05-07-21-10-00 +0000,wsj,Mattel Shareholder Wants Company to Sell,https://www.wsj.com/business/mattel-shareholde...
3,2026-05-07-21-08-35 +0000,bbc,Five killed in huge fire at packed Mexico fair...,https://www.bbc.com/news/articles/cq6py38q81ro...
4,2026-05-07-21-05-05 +0000,nypost,Forget the naysayers — earnings surge means a ...,https://nypost.com/2026/05/07/business/corpora...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
38        trump     35
40         iran     29
41          war     26
227  hantavirus     20
327        ship     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
327,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,135
82,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...,127
304,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...,103
119,2026-05-07-17-57-11 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...,102
34,2026-05-07-20-35-20 +0000,nypost,"Iran casts a long, dark shadow over Trump’s tr...",https://nypost.com/2026/05/07/us-news/iran-cas...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
327,135,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
229,76,2026-05-07-12-06-25 +0000,nypost,Eerie moment cruise passengers told about firs...,https://nypost.com/2026/05/07/world-news/eerie...
266,63,2026-05-07-09-33-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
332,53,2026-05-07-00-45-00 +0000,wsj,Commerce Secretary Howard Lutnick told a congr...,https://www.wsj.com/politics/policy/lutnick-sa...
112,46,2026-05-07-18-22-13 +0000,nypost,"Voters overwhelmingly back age, term limits fo...",https://nypost.com/2026/05/07/us-news/voters-o...
79,44,2026-05-07-19-17-56 +0000,nypost,California gas station chain offering 40 cents...,https://nypost.com/2026/05/07/business/califor...
67,41,2026-05-07-19-38-04 +0000,nyt,"McDonald’s, Burger King and Taco Bell Report S...",https://www.nytimes.com/2026/05/07/business/mc...
313,38,2026-05-07-02-24-48 +0000,latimes,"Bass, Raman and Pratt square off on Palisades ...",https://www.latimes.com/california/story/2026-...
218,38,2026-05-07-12-37-16 +0000,nyt,"Kalshi, the Prediction Market, Raises $1 Billi...",https://www.nytimes.com/2026/05/07/business/de...
243,37,2026-05-07-10-45-51 +0000,nypost,Rubio meets with Pope Leo XIV days after lates...,https://nypost.com/2026/05/07/us-news/rubio-ar...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)