## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-25-19-05-02 +0000,startribune,"Dolly Parton, music star, actor and beloved fi...",https://www.startribune.com/dolly-parton-music...
1,2026-08-25-18-57-15 +0000,nypost,Honda says it may not build new plant in North...,https://nypost.com/2026/08/25/business/honda-s...
2,2026-08-25-18-56-56 +0000,nypost,Trump claims Strait of Hormuz is de-mined — an...,https://nypost.com/2026/08/25/us-news/trump-cl...
3,2026-08-25-18-52-18 +0000,nypost,Dolly Parton abruptly canceled Dollywood event...,https://nypost.com/2026/08/25/us-news/dolly-pa...
4,2026-08-25-18-52-16 +0000,chitri,Construction underway on Orland Park Costco ro...,https://www.chicagotribune.com/2026/08/25/cons...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
21   trump     55
67    iran     28
92  canada     26
13     new     22
18   trade     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...,172
246,2026-08-25-03-57-01 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,164
163,2026-08-25-12-33-40 +0000,nypost,Trump threatens to rename Lake Ontario as ‘Lak...,https://nypost.com/2026/08/25/us-news/trump-th...,160
18,2026-08-25-18-42-58 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,156
303,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,172,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...
303,97,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...
186,75,2026-08-25-11-14-00 +0000,wsj,Michigan’s Abdul El-Sayed will need to win ove...,https://www.wsj.com/politics/elections/four-ta...
314,63,2026-08-24-21-54-06 +0000,nypost,Iran’s rial currency plunges to record low as ...,https://nypost.com/2026/08/24/world-news/irans...
66,56,2026-08-25-17-06-00 +0000,wsj,CIA Director John Ratcliffe made a surprise vi...,https://www.wsj.com/world/cia-director-john-ra...
306,44,2026-08-24-22-26-45 +0000,chitri,Canada will announce retaliatory tariffs again...,https://www.chicagotribune.com/2026/08/24/trum...
89,42,2026-08-25-16-29-51 +0000,chitri,Ex-Loretto Hospital CEO gets diversion deal am...,https://www.chicagotribune.com/2026/08/25/ex-l...
257,40,2026-08-25-02-14-00 +0000,wsj,The Trump administration is planning what may ...,https://www.wsj.com/politics/policy/trump-admi...
228,39,2026-08-25-08-19-42 +0000,wsj,Stock Market Today: Stocks Advance as Effects ...,https://www.wsj.com/livecoverage/stock-market-...
0,37,2026-08-25-19-05-02 +0000,startribune,"Dolly Parton, music star, actor and beloved fi...",https://www.startribune.com/dolly-parton-music...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)