## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-17-12-03-00 +0000,wsj,State Street Profit Rises On Fee Growth,https://www.wsj.com/business/earnings/state-st...
1,2026-04-17-12-00-00 +0000,nypost,Mary Louis Academy’s softball phenom finally e...,https://nypost.com/2026/04/17/sports/mary-loui...
2,2026-04-17-12-00-00 +0000,missionlocal,They want to represent S.F. in Congress. Here’...,https://missionlocal.org/2026/04/sf-congress-c...
3,2026-04-17-12-00-00 +0000,nypost,Beyond the memes: Understanding the unique rol...,https://nypost.com/business/gold-vs-bitcoin-in...
4,2026-04-17-11-58-00 +0000,wsj,U.K.’s Starmer Under Fresh Scrutiny Over Epste...,https://www.wsj.com/world/uk/u-k-s-starmer-und...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
133    trump     51
92      iran     35
82       war     23
53   lebanon     16
55      fire     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-04-17-09-02-18 +0000,cbc,10-day ceasefire in Lebanon takes effect as Tr...,https://www.cbc.ca/news/world/lebanon-israel-c...,154
121,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,134
102,2026-04-17-07-14-38 +0000,nypost,"Israel, Lebanon 10-day cease-fire begins after...",https://nypost.com/2026/04/17/world-news/israe...,132
252,2026-04-16-19-34-42 +0000,nyt,House Again Thwarts Challenge to Trump’s Autho...,https://www.nytimes.com/2026/04/16/us/politics...,128
319,2026-04-16-15-54-21 +0000,nypost,"Israel, Lebanon agree to 10-day cease-fire, Tr...",https://nypost.com/2026/04/16/world-news/israe...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,154,2026-04-17-09-02-18 +0000,cbc,10-day ceasefire in Lebanon takes effect as Tr...,https://www.cbc.ca/news/world/lebanon-israel-c...
124,70,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
170,65,2026-04-16-22-39-47 +0000,nyt,The cease-fire goes into effect after Israel a...,https://www.nytimes.com/2026/04/16/world/middl...
53,55,2026-04-17-10-00-00 +0000,latimes,"Used EV sales charge up on high gas prices, ev...",https://www.latimes.com/business/story/2026-04...
225,54,2026-04-16-20-48-00 +0000,wsj,President Trump says he will nominate Dr. Eric...,https://www.wsj.com/politics/policy/trump-says...
280,46,2026-04-16-18-16-24 +0000,nypost,Europe could run out of jet fuel in 6 weeks — ...,https://nypost.com/2026/04/16/world-news/europ...
125,46,2026-04-17-02-36-12 +0000,wapo,ICE agent charged with assault for allegedly p...,https://www.washingtonpost.com/nation/2026/04/...
261,40,2026-04-16-19-04-00 +0000,wsj,Former Virginia Lt. Gov. Justin Fairfax Kills ...,https://www.wsj.com/us-news/former-virginia-lt...
127,40,2026-04-17-02-00-00 +0000,wsj,The fight between President Trump and Pope Leo...,https://www.wsj.com/politics/elections/trump-p...
48,37,2026-04-17-10-00-00 +0000,latimes,Powerful California institutions backed Swalwe...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)