## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-20-21-51-00 +0000,wsj,Opinion | Gen Z Is ‘Just Asking Questions’,https://www.wsj.com/opinion/gen-z-is-just-aski...
1,2026-10-20-21-50-41 +0000,bbc,Elon Musk says Tesla-SpaceX merger would be a ...,https://www.bbc.co.uk/news/articles/cmlyl09xjk...
2,2026-10-20-21-50-06 +0000,nyt,Alabama Governor Commutes Death Sentence of Ma...,https://www.nytimes.com/2026/10/20/us/death-se...
3,2026-10-20-21-49-34 +0000,missionlocal,"Election Extra! Gary McCoy nets contributions,...",https://missionlocal.org/2026/10/san-francisco...
4,2026-10-20-21-49-31 +0000,nyt,China Condemns U.S. Ban on DeepSeek A.I. in Go...,https://www.nytimes.com/2026/10/20/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2452/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
73    trump     38
37      new     24
253      ai     14
181  france     12
105  police     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
151,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...,103
102,2026-10-20-19-40-00 +0000,wsj,Trump announced a new program that will pay pe...,https://www.wsj.com/politics/policy/trump-to-o...,101
360,2026-10-19-22-57-19 +0000,nyt,Venezuela’s Opposition Leader Calls Trump’s Ne...,https://www.nytimes.com/2026/10/15/world/ameri...,80
91,2026-10-20-19-59-36 +0000,cbc,Lawsuit challenging Trump's tariffs against Ca...,https://www.cbc.ca/news/world/trump-tariffs-la...,76
15,2026-10-20-21-32-26 +0000,nypost,CNN threatens lawsuit against Trump administra...,https://nypost.com/2026/10/20/us-news/cnn-thre...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
151,103,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...
102,63,2026-10-20-19-40-00 +0000,wsj,Trump announced a new program that will pay pe...,https://www.wsj.com/politics/policy/trump-to-o...
285,59,2026-10-20-10-00-00 +0000,nypost,"Kansas Dem Adam Hamilton, who made millions on...",https://nypost.com/2026/10/20/us-news/kansas-d...
244,51,2026-10-20-12-19-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
235,44,2026-10-20-12-48-52 +0000,nypost,Far-left French rioter on national security wa...,https://nypost.com/2026/10/20/world-news/far-l...
241,42,2026-10-20-12-34-57 +0000,nyt,UK to Send Fighter Jets to Help Defend Saudi A...,https://www.nytimes.com/2026/10/20/world/europ...
343,42,2026-10-20-00-53-37 +0000,bbc,Police used 'justified' force in fatal shootin...,https://www.bbc.co.uk/news/articles/cwj0l72d5p...
129,42,2026-10-20-19-01-56 +0000,cbc,No Canada-U.S. trade deal expected before Amer...,https://www.cbc.ca/news/politics/carney-trump-...
273,41,2026-10-20-10-54-00 +0000,wsj,There is plenty of GOP hand-wringing about the...,https://www.wsj.com/politics/elections/the-cas...
283,35,2026-10-20-10-00-00 +0000,latimes,"SpaceX, Anthropic plan to share wealth with th...",https://www.latimes.com/business/story/2026-10...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)