## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-21-22-57-44 +0000,nypost,Stephen A. Smith explodes over Trump’s Army-Na...,https://nypost.com/2026/03/21/us-news/stephen-...
1,2026-03-21-22-53-03 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...
2,2026-03-21-22-52-35 +0000,nypost,"Florida lunatic beats pregnant driver, attacks...",https://nypost.com/2026/03/21/us-news/florida-...
3,2026-03-21-22-51-44 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/21/world/...
4,2026-03-21-22-36-24 +0000,nyt,Iranian missile strikes Israeli city near main...,https://www.nytimes.com/live/2026/03/21/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
3     trump     23
8      iran     22
9       war     16
98      bts     11
14  iranian     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-03-21-22-53-03 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...,89
201,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...,73
70,2026-03-21-17-57-34 +0000,nypost,Trump blasts Robert Mueller after news of ex-F...,https://nypost.com/2026/03/21/us-news/trump-bl...,72
8,2026-03-21-22-12-04 +0000,bbc,Trump administration at crossroads in US-Israe...,https://www.bbc.com/news/articles/clyxv87zwwpo...,71
6,2026-03-21-22-28-56 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,89,2026-03-21-22-53-03 +0000,nyt,Iran War Live Updates: U.S. Bombed Thousands o...,https://www.nytimes.com/live/2026/03/21/world/...
201,73,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...
70,49,2026-03-21-17-57-34 +0000,nypost,Trump blasts Robert Mueller after news of ex-F...,https://nypost.com/2026/03/21/us-news/trump-bl...
94,38,2026-03-21-15-07-30 +0000,wapo,K-pop stars BTS thrill Seoul with comeback con...,https://www.washingtonpost.com/world/2026/03/2...
38,30,2026-03-21-20-27-20 +0000,nypost,Reckless driver who killed two Miami Beach spr...,https://nypost.com/2026/03/21/us-news/reckless...
195,30,2026-03-21-01-00-00 +0000,wsj,Some Democrats on Capitol Hill are discussing ...,https://www.wsj.com/politics/policy/chuck-schu...
87,29,2026-03-21-16-00-00 +0000,wsj,"Even if You’re Not Driving, You’re Probably Us...",https://www.wsj.com/business/energy-oil/even-i...
22,27,2026-03-21-21-23-48 +0000,nyt,Iran Fires Missiles at Far-Off Diego Garcia Ba...,https://www.nytimes.com/2026/03/21/us/politics...
59,26,2026-03-21-19-08-04 +0000,startribune,Meet the man pledging to donate $16 million to...,https://www.startribune.com/minneapolis-rent-h...
21,26,2026-03-21-21-27-08 +0000,nypost,Epstein prison guard will testify before Congr...,https://nypost.com/2026/03/21/us-news/epstein-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)