## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-14-46-00 +0000,wsj,‘Expectations on Every Calorie’—PepsiCo’s CEO ...,https://www.wsj.com/business/retail/expectatio...
1,2026-07-09-14-41-54 +0000,bbc,Traffic through Strait of Hormuz falls steeply...,https://www.bbc.co.uk/news/articles/c621k5r876...
2,2026-07-09-14-40-12 +0000,nypost,"Ebola death toll in Congo reaches 600, as new ...",https://nypost.com/2026/07/09/world-news/ebola...
3,2026-07-09-14-37-58 +0000,cbc,Olympian Trump accused of vandalizing the refl...,https://www.cbc.ca/news/world/trump-reflecting...
4,2026-07-09-14-37-56 +0000,nyt,Live Updates: U.S. and Iran Sink Into Violent ...,https://www.nytimes.com/live/2026/07/09/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
28     trump     49
15      iran     40
43   platner     22
47    senate     17
296     nato     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...,157
209,2026-07-09-00-16-02 +0000,nypost,Accused rapist Graham Platner finally announce...,https://nypost.com/2026/07/08/us-news/graham-p...,126
191,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...,125
235,2026-07-08-22-18-21 +0000,nyt,"Iran Truce ‘Over,’ Trump Says, as He Threatens...",https://www.nytimes.com/2026/07/08/world/middl...,119
312,2026-07-08-18-57-06 +0000,cbc,"As Trump declares ceasefire over, Iran's leade...",https://www.cbc.ca/news/world/iran-khamenei-tr...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,157,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...
209,126,2026-07-09-00-16-02 +0000,nypost,Accused rapist Graham Platner finally announce...,https://nypost.com/2026/07/08/us-news/graham-p...
23,57,2026-07-09-14-11-32 +0000,nypost,New footage reveals destruction of Ayatollah K...,https://nypost.com/2026/07/09/world-news/ayato...
383,54,2026-07-08-15-20-00 +0000,wsj,The IMF trimmed its global growth forecast to ...,https://www.wsj.com/economy/global/imf-drops-r...
304,50,2026-07-08-19-26-00 +0000,wsj,Fed officials weighed rate hikes last month as...,https://www.wsj.com/economy/central-banking/fe...
117,48,2026-07-09-10-00-00 +0000,latimes,California soccer fans sue StubHub after it fa...,https://www.latimes.com/business/story/2026-07...
219,47,2026-07-08-23-31-53 +0000,bbc,It was 'love at first sight' with their adopte...,https://www.bbc.co.uk/news/articles/czxq4ge246...
225,40,2026-07-08-23-10-10 +0000,bbc,"I run the UK's biggest bank, here are five way...",https://www.bbc.co.uk/news/articles/cd7wldr3pr...
163,39,2026-07-09-05-38-45 +0000,nypost,NJ cop in charge of K-9 unit charged after lea...,https://nypost.com/2026/07/09/us-news/nj-cop-i...
238,38,2026-07-08-22-09-12 +0000,nypost,United Airlines must face lawsuit after allege...,https://nypost.com/2026/07/08/business/united-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)