## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-15-42-54 +0000,nyt,What Would Taylor Swift and Travis Kelce’s Pre...,https://www.nytimes.com/2026/07/01/business/ta...
1,2026-07-01-15-40-01 +0000,startribune,Trump filing shows he took in about $1.2 billi...,https://www.startribune.com/trump-filing-shows...
2,2026-07-01-15-38-42 +0000,nypost,Sony to stop releasing PlayStation games on di...,https://nypost.com/2026/07/01/business/sony-to...
3,2026-07-01-15-37-29 +0000,nypost,From lavish dinners to rooftop fireworks parti...,https://nypost.com/2026/07/01/lifestyle/nycs-h...
4,2026-07-01-15-34-10 +0000,bbc,Man guilty of attempted murder of three childr...,https://www.bbc.co.uk/news/articles/c78yjgpr5j...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9      trump     41
47     court     26
46   supreme     25
17      year     17
350      new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
313,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,123
247,2026-06-30-23-15-01 +0000,nyt,Trump Says It’s ‘Too Bad’ Supreme Court Upheld...,https://www.nytimes.com/2026/06/30/us/politics...,123
191,2026-07-01-05-32-26 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,123
33,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,115
108,2026-07-01-11-10-00 +0000,wsj,Three places where this Supreme Court fenced T...,https://www.wsj.com/politics/three-places-wher...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
313,123,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...
151,79,2026-07-01-09-30-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
33,57,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
310,54,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
121,52,2026-07-01-10-49-02 +0000,nypost,Dog missing for month in Mexico found partying...,https://nypost.com/2026/07/01/world-news/dog-m...
171,46,2026-07-01-07-59-24 +0000,wsj,"Stock Market Today: Nasdaq Slips, Warsh Dodges...",https://www.wsj.com/livecoverage/stock-market-...
201,45,2026-07-01-04-15-11 +0000,nypost,Socialist congressional candidate Melat Kiros ...,https://nypost.com/2026/07/01/us-news/socialis...
338,39,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
335,37,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
295,36,2026-06-30-21-03-05 +0000,nypost,California Dems push wartime price gouging cra...,https://nypost.com/2026/06/30/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)