## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-07-06-16 +0000,bbc,Five missing after fire in Swiss Alpine town,https://www.bbc.co.uk/news/articles/cy8e6g1349...
1,2026-08-21-06-59-20 +0000,nyt,What to Know About Iran’s Economic Ties With G...,https://www.nytimes.com/2026/08/19/world/middl...
2,2026-08-21-06-58-00 +0000,wsj,U.K. Government Borrowing Rose Despite Record ...,https://www.wsj.com/world/uk/u-k-government-bo...
3,2026-08-21-06-56-11 +0000,bbc,Starmer donates biography of himself to Downin...,https://www.bbc.co.uk/news/articles/czdm6m939e...
4,2026-08-21-06-52-07 +0000,nyt,The New York Times Loses Defamation Lawsuit in...,https://www.nytimes.com/2026/08/20/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
312       trump     37
282          up     20
292  california     17
318      meghan     16
317       harry     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
92,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...,115
329,2026-08-20-11-58-09 +0000,cbc,North Korea fires up to 10 ballistic missiles ...,https://www.cbc.ca/news/world/north-korea-miss...,93
392,2026-08-20-09-00-00 +0000,wsj,Trump’s half-built White House ballroom is a 9...,https://www.wsj.com/politics/policy/build-firs...,91
354,2026-08-20-10-50-00 +0000,wsj,The Morning Risk Report: Trump Threatens Iran ...,https://www.wsj.com/risk-compliance-journal/th...,88
36,2026-08-21-02-58-51 +0000,nyt,The Message Behind Trump’s Threats of ‘Economi...,https://www.nytimes.com/2026/08/20/world/europ...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
92,115,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...
382,73,2026-08-20-09-30-00 +0000,wsj,After 66-year-old Lynn Lee was laid off last y...,https://www.wsj.com/lifestyle/careers/the-66-y...
166,70,2026-08-20-20-41-36 +0000,nyt,As Prince Harry and Meghan Depart California f...,https://www.nytimes.com/2026/08/20/us/prince-h...
154,57,2026-08-20-21-03-30 +0000,bbc,FBI arrests woman over alleged plot to bomb Ne...,https://www.bbc.co.uk/news/articles/c5y615l2w4...
263,52,2026-08-20-16-12-52 +0000,nypost,Bessent tells US allies ‘you’re either with us...,https://nypost.com/2026/08/20/us-news/bessent-...
208,47,2026-08-20-18-57-51 +0000,nypost,Dow plunges 700 points as surging Treasury yie...,https://nypost.com/2026/08/20/business/dow-plu...
355,41,2026-08-20-10-47-37 +0000,nypost,North Korea fires about 10 short-range ballist...,https://nypost.com/2026/08/20/world-news/north...
183,41,2026-08-20-20-04-52 +0000,nyt,Bond Market Stress Returns and Oil Rises in Ed...,https://www.nytimes.com/2026/08/20/business/ir...
30,40,2026-08-21-03-57-19 +0000,nypost,Pilot killed in crash with Pennsylvania State ...,https://nypost.com/2026/08/20/us-news/pilot-ki...
299,40,2026-08-20-13-57-27 +0000,nypost,FBI seizes Eric Swalwell’s devices at Californ...,https://nypost.com/2026/08/20/us-news/fbi-conf...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)