## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-20-18-09-55 +0000,nyt,Michigan Gas Clerk Helps Save Kidnapped Teen G...,https://www.nytimes.com/2026/04/19/us/michigan...
1,2026-04-20-18-09-12 +0000,nyt,Justices to Hear Case on Catholic Preschools T...,https://www.nytimes.com/2026/04/20/us/politics...
2,2026-04-20-18-08-00 +0000,nyt,Democrat Betty Yee Leaves the California Gover...,https://www.nytimes.com/2026/04/20/us/californ...
3,2026-04-20-18-06-50 +0000,bbc,Officials deliberately withheld Mandelson vett...,https://www.bbc.com/news/articles/cx2wllel54no...
4,2026-04-20-18-06-50 +0000,nyt,Israel-Lebanon Cease-Fire: What to Know,https://www.nytimes.com/2026/04/17/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2569/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
37      iran     23
60     trump     21
44       new     14
431  iranian     12
522       he     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...,97
99,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...,96
141,2026-04-20-13-22-31 +0000,nypost,Trump tells The Post he’s willing to meet with...,https://nypost.com/2026/04/20/us-news/jd-vance...,90
17,2026-04-20-17-38-47 +0000,nypost,Dramatic video shows US Marines rappelling ont...,https://nypost.com/2026/04/20/world-news/drama...,73
94,2026-04-20-15-37-29 +0000,nyt,Trump says he might go to Pakistan if an Iran ...,https://www.nytimes.com/live/2026/04/17/world/...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,97,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...
99,73,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...
244,43,2026-04-19-23-07-52 +0000,bbc,'They told me he was dead': Children born near...,https://www.bbc.com/news/articles/c895k3537kgo...
205,40,2026-04-20-09-00-07 +0000,wapo,Gas prices threaten GOP in race that could hel...,https://www.washingtonpost.com/business/2026/0...
61,37,2026-04-20-16-32-34 +0000,nypost,"FBI Director Kash Patel sues The Atlantic, rep...",https://nypost.com/2026/04/20/media/fbi-direct...
22,35,2026-04-20-17-30-00 +0000,wsj,The Justice Department’s antitrust division is...,https://www.wsj.com/politics/policy/justice-de...
238,34,2026-04-19-23-45-21 +0000,nyt,U.S. Attacks Iranian Cargo Ship as Both Countr...,https://www.nytimes.com/2026/04/19/world/middl...
32,32,2026-04-20-17-11-45 +0000,nypost,D4vd lay in wait for Celeste Rivas before kill...,https://nypost.com/2026/04/20/us-news/singer-d...
268,31,2026-04-19-19-49-34 +0000,nypost,Chinese robot smashes human world record in ha...,https://nypost.com/2026/04/19/world-news/chine...
57,30,2026-04-20-16-39-11 +0000,nypost,California’s best city for college grads revea...,https://nypost.com/2026/04/20/lifestyle/san-di...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)