## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-20-06-07-00 +0000,wsj,Taiwan Presses Its Case After Trump Puts Arms ...,https://www.wsj.com/world/asia/taiwan-presses-...
1,2026-05-20-06-02-29 +0000,nypost,Three stabbed as hundreds take over Rhode Isla...,https://nypost.com/2026/05/20/us-news/rhode-is...
2,2026-05-20-05-56-49 +0000,bbc,UK loosens Russian oil sanctions as fuel price...,https://www.bbc.com/news/articles/cy42x3g7r89o...
3,2026-05-20-05-51-00 +0000,wsj,U.S. Treasury Yields Edge Lower in Fragile Pos...,https://www.wsj.com/finance/investing/jgbs-mix...
4,2026-05-20-05-48-23 +0000,bbc,'Ghost brokers' targeting 16 to 25 year-olds w...,https://www.bbc.com/news/articles/c1w29zw0q44o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
3         trump     55
117  republican     22
47         iran     22
105     primary     21
78       senate     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...,221
32,2026-05-20-02-28-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,171
31,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...,162
72,2026-05-20-00-32-19 +0000,cbc,Trump pick Ed Gallrein projected to win Republ...,https://www.cbc.ca/news/world/kentucky-republi...,141
110,2026-05-19-23-00-49 +0000,nyt,Senate Votes to Take Up Measure to Force Trump...,https://www.nytimes.com/2026/05/19/us/politics...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,221,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...
11,98,2026-05-20-04-45-00 +0000,wsj,A Georgia congressman and a former college foo...,https://www.wsj.com/politics/elections/georgia...
31,85,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...
244,61,2026-05-19-18-03-38 +0000,latimes,Hilton and Becerra lead in a tightening race i...,https://www.latimes.com/california/story/2026-...
34,47,2026-05-20-02-19-51 +0000,nypost,San Diego mosque shooter Caleb Vasquez encoura...,https://nypost.com/2026/05/19/us-news/san-dieg...
38,47,2026-05-20-01-59-05 +0000,nypost,‘Widowed’ Wisconsin husband allegedly killed w...,https://nypost.com/2026/05/19/us-news/widowed-...
191,46,2026-05-19-20-33-16 +0000,nypost,Wall Street titans fail to stand up to Mamdani...,https://nypost.com/2026/05/19/business/wall-st...
211,46,2026-05-19-19-32-22 +0000,bbc,Ebola outbreak may be spreading faster than fi...,https://www.bbc.com/news/articles/ceqp11gn1l8o...
2,38,2026-05-20-05-56-49 +0000,bbc,UK loosens Russian oil sanctions as fuel price...,https://www.bbc.com/news/articles/cy42x3g7r89o...
240,35,2026-05-19-18-15-12 +0000,bbc,Three Canadian off-duty officers arrested in S...,https://www.bbc.com/news/articles/c8e8983kjy5o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)