## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-25-22-58-03 +0000,nyt,U.S. ‘Economic D-Day’ Targets More Than Just I...,https://www.nytimes.com/2026/08/25/world/middl...
1,2026-08-25-22-56-46 +0000,nyt,When to Expect Results in South Carolina and O...,https://www.nytimes.com/2026/08/25/us/politics...
2,2026-08-25-22-52-58 +0000,nypost,Long Island jail guard who repeatedly sexually...,https://nypost.com/2026/08/25/us-news/long-isl...
3,2026-08-25-22-52-13 +0000,nypost,Better Bakehouse recalls mislabeled chocolate-...,https://nypost.com/2026/08/25/business/better-...
4,2026-08-25-22-51-44 +0000,nypost,NY sheriffs sue over Hochul’s anti-ICE law as ...,https://nypost.com/2026/08/25/us-news/ny-sheri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2333/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
164   trump     53
139  canada     28
140   trade     19
393    iran     19
141     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...,170
230,2026-08-25-12-33-40 +0000,nypost,Trump threatens to rename Lake Ontario as ‘Lak...,https://nypost.com/2026/08/25/us-news/trump-th...,163
166,2026-08-25-16-25-46 +0000,wapo,Trump says U.S. could rename Lake Ontario as L...,https://www.washingtonpost.com/politics/2026/0...,157
311,2026-08-25-03-57-01 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,157
116,2026-08-25-18-42-58 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,151

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,170,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...
151,70,2026-08-25-17-06-00 +0000,wsj,CIA Director John Ratcliffe made a surprise vi...,https://www.wsj.com/world/cia-director-john-ra...
246,63,2026-08-25-11-53-36 +0000,bbc,China hits out at 'illegal' new US sanctions o...,https://www.bbc.co.uk/news/articles/clyl8965j5...
252,58,2026-08-25-11-14-00 +0000,wsj,Michigan’s Abdul El-Sayed will need to win ove...,https://www.wsj.com/politics/elections/four-ta...
55,50,2026-08-25-21-01-29 +0000,nypost,Ex-Southern Poverty Law Center’s ringleader no...,https://nypost.com/2026/08/25/us-news/ex-south...
134,47,2026-08-25-18-10-54 +0000,wapo,"Dolly Parton, country music singer and cultura...",https://www.washingtonpost.com/obituaries/2026...
165,46,2026-08-25-16-29-51 +0000,chitri,Ex-Loretto Hospital CEO gets diversion deal am...,https://www.chicagotribune.com/2026/08/25/ex-l...
10,42,2026-08-25-22-31-07 +0000,nypost,Chilling details released about ‘random’ mass ...,https://nypost.com/2026/08/25/us-news/oakland-...
345,40,2026-08-24-23-52-00 +0000,wsj,A super PAC aligned with President Trump is op...,https://www.wsj.com/politics/elections/trump-a...
212,37,2026-08-25-13-43-29 +0000,nypost,Angry Canada slaps tariffs of up to 50% agains...,https://nypost.com/2026/08/25/us-news/canada-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)