## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-03-19-14-44 +0000,nyt,How A.I. Is Transforming China’s Entertainment...,https://www.nytimes.com/2026/05/03/world/asia/...
1,2026-05-03-19-09-02 +0000,bbc,Three dead in suspected virus outbreak on Atla...,https://www.bbc.com/news/articles/cy0294829ndo...
2,2026-05-03-19-08-28 +0000,nyt,‘Devil Wears Prada’ Sequel Leads Box Office Wi...,https://www.nytimes.com/2026/05/03/business/de...
3,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
4,2026-05-03-19-02-14 +0000,nypost,Redondo Beach Pier evacuated due to ‘suspiciou...,https://nypost.com/2026/05/03/us-news/redondo-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2641/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
63        trump     22
48         iran     12
118    airlines     11
23          oil     10
73   california      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...,73
60,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...,63
162,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,58
116,2026-05-03-09-00-00 +0000,wsj,Secret Service Director Sean Curran has earned...,https://www.wsj.com/politics/policy/he-rescued...,56
152,2026-05-03-00-34-18 +0000,nypost,Trump says he’s reviewing latest Iran proposal...,https://nypost.com/2026/05/02/world-news/trump...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,73,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
38,48,2026-05-03-16-49-30 +0000,cbc,Cargo ship near Strait of Hormuz reports being...,https://www.cbc.ca/news/world/cargo-ship-strai...
140,45,2026-05-03-03-00-00 +0000,wsj,A mammoth economic stimulus passed last year i...,https://www.wsj.com/world/europe/germany-has-t...
74,45,2026-05-03-14-25-27 +0000,nypost,Former top Biden official all but admits admin...,https://nypost.com/2026/05/03/us-news/ex-biden...
3,36,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
143,28,2026-05-03-02-00-00 +0000,wsj,The U.S. is striving to dominate the drone evo...,https://www.wsj.com/politics/national-security...
26,26,2026-05-03-17-27-21 +0000,bbc,Two US service members reported missing in Mor...,https://www.bbc.com/news/articles/cn7prznmllko...
96,26,2026-05-03-10-00-00 +0000,latimes,"Barabak: Not too early, not too late. Here's t...",https://www.latimes.com/politics/story/2026-05...
181,26,2026-05-02-20-21-15 +0000,nypost,Zelensky warns of ‘unusual activity’ on Belaru...,https://nypost.com/2026/05/02/world-news/zelen...
65,25,2026-05-03-15-16-40 +0000,nypost,Haunting final texts emerge after CHP captain ...,https://nypost.com/2026/05/03/us-news/final-te...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)