## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-22-54-49 +0000,nypost,Wildfire explodes across Nevada border as Cali...,https://nypost.com/2026/08/22/us-news/hawk-fir...
1,2026-08-22-22-50-00 +0000,wsj,After weeks of marathon talks between U.S. and...,https://www.wsj.com/economy/trade/canada-annou...
2,2026-08-22-22-50-00 +0000,wsj,Canada Announces New Tariffs on U.S. as Trade ...,https://www.wsj.com/economy/trade/canada-annou...
3,2026-08-22-22-47-27 +0000,nyt,Trump’s Top Trade Representative Details Offer...,https://www.nytimes.com/2026/08/22/business/ec...
4,2026-08-22-22-43-32 +0000,nypost,NBA hopeful who survived heart attack allowed ...,https://nypost.com/2026/08/22/us-news/nba-hope...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2467/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
27   trump     24
14   trade     18
11   talks     15
21  canada     15
23     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,135
153,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...,122
38,2026-08-22-20-10-00 +0000,bbc,Carney calls Trump's fresh tariffs a 'miscalcu...,https://www.bbc.co.uk/news/articles/cx272np7vg...,83
58,2026-08-22-18-00-54 +0000,nyt,Carney Stands Up to Trump in U.S.-Canada Trade...,https://www.nytimes.com/2026/08/22/world/canad...,80
23,2026-08-22-21-27-04 +0000,wapo,Trump’s new tariffs on Canada will hit everyth...,https://www.washingtonpost.com/business/2026/0...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,135,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
173,72,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
153,43,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
4,37,2026-08-22-22-43-32 +0000,nypost,NBA hopeful who survived heart attack allowed ...,https://nypost.com/2026/08/22/us-news/nba-hope...
71,31,2026-08-22-16-38-45 +0000,nypost,10 killed in Russian and Ukrainian attacks a d...,https://nypost.com/2026/08/22/world-news/10-ki...
6,30,2026-08-22-22-36-03 +0000,nypost,New footage of El Chapo’s first hours in capti...,https://nypost.com/2026/08/22/world-news/new-v...
79,30,2026-08-22-16-00-00 +0000,wsj,"Ashley Hinson has never lost an election. Now,...",https://www.wsj.com/politics/elections/the-for...
86,30,2026-08-22-14-55-24 +0000,nyt,"Harry and Meghan See Their California Dreams, ...",https://www.nytimes.com/2026/08/22/us/meghan-h...
140,28,2026-08-22-09-00-00 +0000,wsj,President Trump is quietly making plans for an...,https://www.wsj.com/politics/policy/trump-new-...
29,26,2026-08-22-20-53-30 +0000,nypost,Former football standout identified as teen sh...,https://nypost.com/2026/08/22/us-news/victim-1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)