## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-02-14-13-03 +0000,nyt,Iran War Live Updates: Oil Prices Surge After ...,https://www.nytimes.com/live/2026/04/02/world/...
1,2026-04-02-14-13-00 +0000,wsj,Trump Iran Speech Sends Treasury Yields Higher,https://www.wsj.com/finance/investing/jgbs-fal...
2,2026-04-02-14-13-00 +0000,wsj,"Tesla Sales Jumped in First Quarter, Reboundin...",https://www.wsj.com/business/autos/tesla-sales...
3,2026-04-02-14-10-21 +0000,nyt,Here’s How Major Markets Are Moving,https://www.nytimes.com/2026/04/01/business/oi...
4,2026-04-02-14-04-57 +0000,bbc,What nearly went wrong on Nasa's space mission...,https://www.bbc.com/news/articles/c36rxe9w97zo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2522/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

             word  score
7           trump     68
0            iran     54
1             war     41
1187   birthright     16
1188  citizenship     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
171,2026-04-02-02-48-00 +0000,wsj,President Trump sought to reassure skeptical A...,https://www.wsj.com/politics/national-security...,205
262,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...,205
0,2026-04-02-14-13-03 +0000,nyt,Iran War Live Updates: Oil Prices Surge After ...,https://www.nytimes.com/live/2026/04/02/world/...,201
89,2026-04-02-10-27-01 +0000,startribune,Trump uses Iran war address to urge an increas...,https://www.startribune.com/trump-uses-iran-wa...,188
186,2026-04-02-01-39-31 +0000,latimes,"In major speech, Trump says Iran war will be o...",https://www.latimes.com/politics/story/2026-04...,185

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
171,205,2026-04-02-02-48-00 +0000,wsj,President Trump sought to reassure skeptical A...,https://www.wsj.com/politics/national-security...
258,76,2026-04-01-20-30-25 +0000,cbc,Artemis II astronauts lift off for NASA's 10-d...,https://www.cbc.ca/news/science/livestory/arte...
239,73,2026-04-01-21-39-38 +0000,nyt,Immigrant Families Are Cautiously Hopeful Over...,https://www.nytimes.com/2026/04/01/us/politics...
228,60,2026-04-01-22-05-00 +0000,wsj,The Trump administration has lifted sanctions ...,https://www.wsj.com/world/americas/u-s-lifts-s...
50,43,2026-04-02-12-40-00 +0000,wsj,Trump endorsed a two-part plan to quickly fund...,https://www.wsj.com/politics/policy/trump-lays...
229,41,2026-04-01-22-02-00 +0000,wsj,New DNA Testing Links Ted Bundy to 1974 Murder...,https://www.wsj.com/us-news/law/new-dna-testin...
84,41,2026-04-02-10-30-00 +0000,nypost,Kristi Noem said she was ‘blindsided’ by husba...,https://nypost.com/2026/04/02/us-news/kristi-n...
136,39,2026-04-02-07-43-19 +0000,nypost,Beyoncé and Drake producer Sidney ‘Omen’ Brown...,https://nypost.com/2026/04/02/us-news/beyonce-...
340,36,2026-04-01-15-50-00 +0000,wsj,The drone having its moment in the Middle East...,https://www.wsj.com/politics/national-security...
135,36,2026-04-02-07-47-34 +0000,wsj,"Stock Market Today: Dow Opens Lower, Oil Jumps...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)