## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-14-14-24-13 +0000,nyt,Ricky Cobb Has Built a Mini-Empire Through ’70...,https://www.nytimes.com/2026/04/14/business/ri...
1,2026-04-14-14-23-57 +0000,bbc,Carney says Canadians trust his plan after he ...,https://www.bbc.com/news/articles/cp9vmepn010o...
2,2026-04-14-14-22-12 +0000,nypost,North Korea tests cruise and anti-ship missile...,https://nypost.com/2026/04/14/world-news/north...
3,2026-04-14-14-21-40 +0000,nypost,Iran-linked ships transit through Strait of Ho...,https://nypost.com/2026/04/14/world-news/iran-...
4,2026-04-14-14-20-04 +0000,nypost,Paris raffle offers $1M Picasso painting for l...,https://nypost.com/2026/04/14/world-news/paris...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
31     trump     52
23      iran     43
53       war     29
32  blockade     26
58  swalwell     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-04-14-14-21-40 +0000,nypost,Iran-linked ships transit through Strait of Ho...,https://nypost.com/2026/04/14/world-news/iran-...,182
234,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,177
337,2026-04-13-17-15-47 +0000,nyt,"To Open the Strait of Hormuz, Trump Wants to B...",https://www.nytimes.com/2026/04/13/world/middl...,164
188,2026-04-14-03-56-00 +0000,wsj,Trump’s Blockade on Iran in Strait Begins,https://www.wsj.com/world/middle-east/trumps-b...,142
382,2026-04-13-14-31-56 +0000,nypost,"Dow jumps 300 points, oil below $100 after Tru...",https://nypost.com/2026/04/13/business/dow-fal...,141

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,182,2026-04-14-14-21-40 +0000,nypost,Iran-linked ships transit through Strait of Ho...,https://nypost.com/2026/04/14/world-news/iran-...
68,94,2026-04-14-12-31-52 +0000,nypost,New Eric Swalwell victim speaks out for first ...,https://nypost.com/2026/04/14/us-news/eric-swa...
29,77,2026-04-14-13-50-21 +0000,nyt,Middle East War Will Slow Global Economic Grow...,https://www.nytimes.com/2026/04/14/business/ir...
208,67,2026-04-14-01-00-00 +0000,wsj,Trump’s post of an AI-generated image depictin...,https://www.wsj.com/politics/policy/trump-jesu...
193,56,2026-04-14-02-47-00 +0000,wsj,Canadian Prime Minister Mark Carney has secure...,https://www.wsj.com/world/americas/canadas-car...
88,52,2026-04-14-11-38-24 +0000,bbc,Oil prices ease on hopes of new US-Iran peace ...,https://www.bbc.com/news/articles/cjr9qrnp821o...
235,52,2026-04-13-22-55-00 +0000,wsj,Democratic Rep. Eric Swalwell of California an...,https://www.wsj.com/politics/house-removal-vot...
143,51,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...
265,47,2026-04-13-21-28-14 +0000,bbc,Hungary's next PM would pick up if Putin calls...,https://www.bbc.com/news/articles/cd6lzezp4zvo...
80,47,2026-04-14-12-03-46 +0000,nypost,Eric Swalwell victims reveal powerful reason w...,https://nypost.com/2026/04/14/us-news/eric-swa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)