## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-24-18-21-55 +0000,nypost,Wendy’s surges over 40% after viral Reddit pos...,https://nypost.com/2026/06/24/business/wendys-...
1,2026-06-24-18-16-55 +0000,wapo,Hegseth thwarted internal efforts to extend to...,https://www.washingtonpost.com/national-securi...
2,2026-06-24-18-16-01 +0000,nyt,Support Builds on the Right for Prosecuting Wo...,https://www.nytimes.com/2026/06/24/us/politics...
3,2026-06-24-18-14-00 +0000,wsj,Camp Mystic Files for Bankruptcy Nearly a Year...,https://www.wsj.com/us-news/texas-camp-mystic-...
4,2026-06-24-18-08-01 +0000,startribune,Two formula recalls raise doubts about booming...,https://www.startribune.com/two-formula-recall...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
134    trump     40
105      new     27
56      iran     25
103      war     18
140  housing     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
165,2026-06-24-12-10-09 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...,122
16,2026-06-24-17-50-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...,121
114,2026-06-24-14-57-21 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...,118
240,2026-06-24-03-22-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/national-security...,117
151,2026-06-24-13-24-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/elections/key-tak...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
165,122,2026-06-24-12-10-09 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...
151,112,2026-06-24-13-24-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/elections/key-tak...
16,81,2026-06-24-17-50-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
40,61,2026-06-24-17-17-17 +0000,nypost,Oil prices drop near $70 a barrel — lowest lev...,https://nypost.com/2026/06/24/business/oil-pri...
319,56,2026-06-23-21-53-00 +0000,wsj,Opinion | Will the World Cup Make America Love...,https://www.wsj.com/opinion/will-the-world-cup...
39,52,2026-06-24-17-21-20 +0000,nyt,Europe Heat Wave Latest News: After France’s H...,https://www.nytimes.com/2026/06/24/weather/eur...
197,43,2026-06-24-10-00-00 +0000,latimes,"In echoes of Palisades fire, Boyle Heights fir...",https://www.latimes.com/california/story/2026-...
355,43,2026-06-23-20-14-00 +0000,wsj,Tech Stocks Retreat on Concerns over AI Spendi...,https://www.wsj.com/finance/stocks/tech-stocks...
331,42,2026-06-23-21-25-48 +0000,nypost,Sable Offshore lashes out after ruling — threa...,https://nypost.com/2026/06/23/us-news/gas-and-...
286,39,2026-06-23-23-29-25 +0000,latimes,Family says police fatally shot teen during me...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)