## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-04-22-56-46 +0000,nypost,Major oil group drops truth bomb on Gavin News...,https://nypost.com/2026/04/04/us-news/major-oi...
1,2026-04-04-22-54-17 +0000,startribune,Frost clinch PWHL playoff spot with 6-5 victor...,https://www.startribune.com/frost-clinch-pwhl-...
2,2026-04-04-22-54-06 +0000,bbc,US and Iran trade threats to unleash 'hell' as...,https://www.bbc.com/news/articles/c5y90jl8veyo...
3,2026-04-04-22-47-00 +0000,wsj,The U.S.-Europe Alliance Is Reaching a Breakin...,https://www.wsj.com/world/europe/the-u-s-europ...
4,2026-04-04-22-44-14 +0000,nypost,Driver smashes into crowd at Louisiana festiva...,https://nypost.com/2026/04/04/us-news/driver-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2523/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
50     trump     29
17      iran     22
31       war     13
23   missing     10
407      new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-04-04-22-32-49 +0000,nyt,Iran War Live Updates: U.S. Races to Find Miss...,https://www.nytimes.com/live/2026/04/04/world/...,96
84,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,76
67,2026-04-04-17-29-57 +0000,nyt,"Trump Pledged a Quick End to the Iran War, but...",https://www.nytimes.com/2026/04/04/us/politics...,74
172,2026-04-04-00-02-20 +0000,nyt,War With Iran Clarifies Trump’s Spending Prior...,https://www.nytimes.com/2026/04/02/us/politics...,73
121,2026-04-04-09-30-00 +0000,wsj,President Trump didn’t attack Iran to help the...,https://www.wsj.com/economy/the-iran-war-is-ma...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,96,2026-04-04-22-32-49 +0000,nyt,Iran War Live Updates: U.S. Races to Find Miss...,https://www.nytimes.com/live/2026/04/04/world/...
65,35,2026-04-04-17-42-39 +0000,nypost,Gavin Newsom to spend $19M in taxpayer funds o...,https://nypost.com/2026/04/04/us-news/gavin-ne...
69,29,2026-04-04-17-20-48 +0000,nyt,"Houston Cheers on Artemis II Moon Mission, Rec...",https://www.nytimes.com/2026/04/04/us/artemis-...
82,25,2026-04-04-15-21-52 +0000,nypost,"Niece, grandniece of slain notorious Iranian G...",https://nypost.com/2026/04/04/us-news/ice-arre...
155,25,2026-04-04-02-11-17 +0000,latimes,Pip pip hooray! One of Jackie and Shadow's chi...,https://www.latimes.com/environment/story/2026...
29,24,2026-04-04-20-09-53 +0000,latimes,Man convicted of murdering his girlfriend four...,https://www.latimes.com/california/story/2026-...
103,23,2026-04-04-11-01-00 +0000,startribune,Helicopter owner’s lawsuit fails against East ...,https://www.startribune.com/east-gull-lake-min...
32,21,2026-04-04-19-46-55 +0000,nypost,NYC mom of two ID’d after being killed by Broo...,https://nypost.com/2026/04/04/us-news/the-hosp...
121,20,2026-04-04-09-30-00 +0000,wsj,President Trump didn’t attack Iran to help the...,https://www.wsj.com/economy/the-iran-war-is-ma...
122,20,2026-04-04-09-30-00 +0000,wsj,"The labor market is holding together, but the ...",https://www.wsj.com/economy/jobs/how-to-interp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)