## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-02-49-37 +0000,nypost,Social Security recipients may get bigger bene...,https://nypost.com/2026/09/21/business/social-...
1,2026-09-22-02-43-52 +0000,bbc,Watch: Six-year-old girl from China sets new R...,https://www.bbc.co.uk/news/videos/cmvgyzgnq9e3...
2,2026-09-22-02-42-00 +0000,wsj,Singapore Dollar Steady; Geopolitics in Focus ...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-09-22-02-40-37 +0000,nypost,‘Disgruntled’ car owner slaps ‘shame sticker’ ...,https://nypost.com/2026/09/21/us-news/disgrunt...
4,2026-09-22-02-39-09 +0000,nyt,Why a Law to Help Prisoners Became a New Secta...,https://www.nytimes.com/2026/09/21/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
102  trump     52
13     new     20
345  house     19
234     ai     18
11   china     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
79,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...,144
45,2026-09-22-00-16-06 +0000,bbc,"CNN, MS NOW and Politico file lawsuit against ...",https://www.bbc.co.uk/news/articles/cm0e32rwvr...,128
197,2026-09-21-18-31-17 +0000,nypost,Trump cuts ribbon on latest White House constr...,https://nypost.com/2026/09/21/us-news/trump-cu...,128
145,2026-09-21-20-38-00 +0000,wsj,President Trump has discussed kicking journali...,https://www.wsj.com/politics/policy/trump-has-...,128
96,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
79,144,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...
210,86,2026-09-21-18-05-18 +0000,nypost,Illinois Gov. JB Pritzker says he’s lost 80 po...,https://nypost.com/2026/09/21/us-news/illinois...
96,71,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...
186,69,2026-09-21-18-55-00 +0000,cbc,Paramount settles with U.S. states over Warner...,https://www.cbc.ca/news/entertainment/paramoun...
152,64,2026-09-21-20-25-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
62,48,2026-09-21-23-26-57 +0000,chitri,Appeals court favors Trump-backed Missouri con...,https://www.chicagotribune.com/2026/09/21/trum...
305,47,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
36,47,2026-09-22-00-45-00 +0000,nypost,California tech exec says she’s found 5 ‘Mr. R...,https://nypost.com/2026/09/21/us-news/brooke-l...
27,46,2026-09-22-01-05-46 +0000,wapo,Major TV networks halt video coverage of Trump...,https://www.washingtonpost.com/business/2026/0...
10,46,2026-09-22-02-15-15 +0000,nyt,Man Shot by ICE Agent Says His Car Was Struck ...,https://www.nytimes.com/2026/09/21/us/ice-shoo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)