## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-24-15-06-32 +0000,nypost,Pedestrian miraculously walks away after being...,https://nypost.com/2026/08/24/world-news/pedes...
1,2026-08-24-15-03-26 +0000,chitri,"People can sense mental decline, says new rese...",https://www.chicagotribune.com/2026/08/24/ment...
2,2026-08-24-15-01-20 +0000,bbc,Graduate job vacancies drop by almost 50% in a...,https://www.bbc.co.uk/news/articles/crerd8l3pw...
3,2026-08-24-15-00-04 +0000,nyt,U.S. to Unveil ‘Economic D-Day’ Sanctions Targ...,https://www.nytimes.com/2026/08/24/us/politics...
4,2026-08-24-14-59-34 +0000,nypost,Psychiatrist admits Lindsay Clancy ‘was in a s...,https://nypost.com/2026/08/24/us-news/psychiat...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2623/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
78        trump     26
32         iran     18
15          new     11
293  california     10
93        trade     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-08-24-14-46-47 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,80
240,2026-08-23-17-00-10 +0000,nyt,Iran Warns Gulf States Not to Join Trump’s Eco...,https://www.nytimes.com/2026/08/23/world/europ...,67
145,2026-08-24-08-49-48 +0000,nyt,Which Countries Could Be Hurt Most by Trump’s ...,https://www.nytimes.com/article/us-iran-econom...,66
32,2026-08-24-14-00-29 +0000,nypost,Trump revs up tariffs on Canada to 50% on auto...,https://nypost.com/2026/08/24/us-news/trump-re...,63
109,2026-08-24-10-30-37 +0000,nypost,‘Economic D-Day’ sanctions against Iran will b...,https://nypost.com/2026/08/24/us-news/iran-eco...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,80,2026-08-24-14-46-47 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...
109,63,2026-08-24-10-30-37 +0000,nypost,‘Economic D-Day’ sanctions against Iran will b...,https://nypost.com/2026/08/24/us-news/iran-eco...
183,42,2026-08-24-01-00-00 +0000,wsj,Kevin Warsh’s reluctance to signal where inter...,https://www.wsj.com/economy/central-banking/wa...
40,38,2026-08-24-13-48-12 +0000,nypost,California calls off Paramount settlement meet...,https://nypost.com/2026/08/24/business/califor...
233,36,2026-08-23-18-11-55 +0000,nypost,Ex-Mayor Dan Sullivan backs Dan Sullivan to be...,https://nypost.com/2026/08/23/us-news/dan-sull...
124,35,2026-08-24-10-00-00 +0000,nypost,Chinatown leaders fire warning shot at Mamdani...,https://nypost.com/2026/08/24/us-news/chinatow...
51,30,2026-08-24-13-34-37 +0000,nyt,Someone Was Impersonating Collien Fernandes On...,https://www.nytimes.com/2026/08/23/magazine/co...
86,30,2026-08-24-12-06-22 +0000,nyt,UK Prime Minister Burnham Arrives in Ukraine a...,https://www.nytimes.com/2026/08/24/world/europ...
116,25,2026-08-24-10-00-00 +0000,wsj,Nvidia’s Earnings Will Test Wall Street’s Fait...,https://www.wsj.com/articles/nvidias-earnings-...
217,25,2026-08-23-19-45-56 +0000,nypost,Lefty Dem tipped as next House-incumbent slaye...,https://nypost.com/2026/08/23/us-news/lefty-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)