## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-16-02-38-00 +0000,wsj,Singapore Dollar Strengthens Slightly Amid Mil...,https://www.wsj.com/finance/currencies/asian-c...
1,2026-04-16-02-35-13 +0000,nyt,China’s Economy Leans on Infrastructure as Con...,https://www.nytimes.com/2026/04/15/business/ch...
2,2026-04-16-02-34-46 +0000,startribune,"Simeon Woods Richardson roughed up, Twins’ win...",https://www.startribune.com/boston-red-sox-bea...
3,2026-04-16-02-31-13 +0000,nyt,Lawyer John Eastman Disbarred for Efforts to O...,https://www.nytimes.com/2026/04/15/us/john-eas...
4,2026-04-16-02-29-44 +0000,bbc,China's economy grows faster than expected des...,https://www.bbc.com/news/articles/c4gxjpekk19o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
36    iran     44
192  trump     43
37     war     31
393    new     16
197     he     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-04-16-02-15-24 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...,152
315,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,151
102,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...,150
278,2026-04-15-15-27-22 +0000,bbc,Starmer says he's 'not going to yield' to pres...,https://www.bbc.com/news/articles/cdxdd7ddzgdo...,140
155,2026-04-15-20-07-09 +0000,nyt,Senate Republicans Again Block Bid to Limit Tr...,https://www.nytimes.com/2026/04/15/us/politics...,134

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,152,2026-04-16-02-15-24 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...
315,151,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
272,67,2026-04-15-15-34-22 +0000,nypost,Eric Swalwell’s hotshot lawyer comes out swing...,https://nypost.com/2026/04/15/us-news/eric-swa...
81,52,2026-04-15-22-40-26 +0000,nyt,Live Nation and Ticketmaster Illegally Monopol...,https://www.nytimes.com/2026/04/15/arts/music/...
362,50,2026-04-15-10-00-00 +0000,latimes,L.A.'s Blue Era: How popular are the Dodgers? ...,https://www.latimes.com/sports/dodgers/story/2...
32,49,2026-04-16-01-19-48 +0000,nypost,NYC first lady Rama Duwaji apologizes for past...,https://nypost.com/2026/04/15/us-news/nyc-firs...
180,45,2026-04-15-19-28-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
72,43,2026-04-15-23-00-00 +0000,wsj,The Trump administration wants automakers and ...,https://www.wsj.com/politics/national-security...
53,43,2026-04-16-00-00-00 +0000,wsj,Gov. Kathy Hochul has thrown New York City May...,https://www.wsj.com/politics/policy/new-york-g...
56,42,2026-04-15-23-52-35 +0000,nypost,Airline drops Los Angeles routes as rising fue...,https://nypost.com/2026/04/15/us-news/budget-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)