## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-03-15-04-39 +0000,bbc,Italy's famed Uffizi admits cyber-attack but d...,https://www.bbc.com/news/articles/cy51wzeq6g5o...
1,2026-04-03-15-04-31 +0000,bbc,M&S boss calls for more action on crime and ab...,https://www.bbc.com/news/articles/crk16j2j1ygo...
2,2026-04-03-15-03-20 +0000,nyt,Ancient Artifacts Stolen in Dutch Museum Heist...,https://www.nytimes.com/2026/04/02/world/europ...
3,2026-04-03-15-02-34 +0000,nyt,Iran War Live Updates: American Fighter Jet Do...,https://www.nytimes.com/live/2026/04/03/world/...
4,2026-04-03-15-02-32 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/03/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
109  trump     63
22    iran     41
23     war     34
414  bondi     14
464   will     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
73,2026-04-03-11-28-34 +0000,bbc,When will the Iran war end? Tracing the Trump ...,https://www.bbc.com/news/articles/c4g4e6z9960o...,167
213,2026-04-02-22-11-12 +0000,wapo,"As Trump doubles down on Iran war, markets shu...",https://www.washingtonpost.com/world/2026/04/0...,163
202,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...,163
261,2026-04-02-20-20-20 +0000,nyt,Trump Says He’ll End the Iran War in Weeks. Wh...,https://www.nytimes.com/2026/04/02/us/politics...,161
320,2026-04-02-16-18-14 +0000,latimes,"Trump speech on Iran war, recent remarks on oi...",https://www.latimes.com/politics/story/2026-04...,160

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
73,167,2026-04-03-11-28-34 +0000,bbc,When will the Iran war end? Tracing the Trump ...,https://www.bbc.com/news/articles/c4g4e6z9960o...
202,94,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...
108,73,2026-04-03-09-30-00 +0000,wsj,The March jobs report due Friday morning will ...,https://www.wsj.com/economy/jobs/march-jobs-re...
93,66,2026-04-03-10-16-02 +0000,nypost,The four words Trump said to Pam Bondi the day...,https://nypost.com/2026/04/03/us-news/trump-to...
249,47,2026-04-02-20-55-15 +0000,nypost,Tanker ships must pay Iran’s Revolutionary Gua...,https://nypost.com/2026/04/02/world-news/tanke...
38,44,2026-04-03-13-40-00 +0000,wsj,President Trump released a summary of his budg...,https://www.wsj.com/politics/policy/trump-budg...
225,41,2026-04-02-21-34-00 +0000,wsj,The U.S. will impose tariffs of up to 100% on ...,https://www.wsj.com/politics/policy/trump-phar...
128,36,2026-04-03-08-00-00 +0000,cbc,Liberal bill would force companies to simplify...,https://www.cbc.ca/news/politics/csis-rcmp-dat...
267,33,2026-04-02-19-55-00 +0000,wsj,Blue Owl Investors Seek to Pull $5.4 Billion F...,https://www.wsj.com/finance/investing/blue-owl...
176,31,2026-04-03-00-05-36 +0000,nypost,Road trip favorite In-N-Out to open new locati...,https://nypost.com/2026/04/02/business/in-n-ou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)