## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-19-30-18 +0000,nypost,San Diego mosque shooters were ‘radicalized on...,https://nypost.com/2026/05/19/us-news/san-dieg...
1,2026-05-19-19-26-51 +0000,nypost,Tom Steyer makes shocking flip flop on water-h...,https://nypost.com/2026/05/19/us-news/californ...
2,2026-05-19-19-26-50 +0000,bbc,Grant Shapps quits aerospace firm after watchd...,https://www.bbc.com/news/articles/cvgzjlqv1q9o...
3,2026-05-19-19-25-01 +0000,nyt,Tickle Me Elmo and the ‘Elmo-Mania’ That Consu...,https://www.nytimes.com/2026/05/19/obituaries/...
4,2026-05-19-19-24-38 +0000,nyt,"Greg Hyman, Co-Creator of Tickle Me Elmo, Dies...",https://www.nytimes.com/2026/05/19/business/gr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
44   trump     48
199   iran     20
95     new     19
0      san     18
1    diego     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
352,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,124
57,2026-05-19-18-17-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,124
316,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,117
107,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...,106
47,2026-05-19-18-34-16 +0000,nyt,Trump Endorses Ken Paxton in Texas Senate Runo...,https://www.nytimes.com/2026/05/19/us/politics...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
352,124,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
18,83,2026-05-19-19-07-58 +0000,nypost,Fundraiser for hero security guard killed in S...,https://nypost.com/2026/05/19/us-news/fundrais...
57,76,2026-05-19-18-17-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...
235,46,2026-05-19-11-01-00 +0000,wsj,The nearly $1.8 billion “anti-weaponization fu...,https://www.wsj.com/politics/how-trumps-1-776-...
56,45,2026-05-19-18-17-41 +0000,bbc,Ebola outbreak may be spreading faster than fi...,https://www.bbc.com/news/articles/ceqp11gn1l8o...
258,45,2026-05-19-10-00-00 +0000,latimes,Forced treatment and jail: Spencer Pratt's ple...,https://www.latimes.com/california/story/2026-...
197,39,2026-05-19-13-32-35 +0000,nyt,"As OpenAI Celebrates Court Win Against Musk, O...",https://www.nytimes.com/2026/05/19/technology/...
316,38,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
195,35,2026-05-19-13-35-54 +0000,nypost,Starbucks Korea CEO fired after ‘Tank Day’ pro...,https://nypost.com/2026/05/19/world-news/starb...
107,35,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)