## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-27-07-01-00 +0000,wsj,Nvidia to Invest $3 Billion in Meta’s Equity O...,https://www.wsj.com/tech/ai/nvidia-to-invest-3...
1,2026-10-27-06-59-20 +0000,nyt,Flurry of Diplomacy in Iran Amid Reports of U....,https://www.nytimes.com/2026/10/26/world/middl...
2,2026-10-27-06-49-19 +0000,bbc,Healey pledges cheaper marmalade and gherkins ...,https://www.bbc.co.uk/news/articles/c6d93gq1xd...
3,2026-10-27-06-48-50 +0000,bbc,"'I'm a single mum on £41,000 and limit my week...",https://www.bbc.co.uk/news/articles/cmx235r9wr...
4,2026-10-27-06-36-28 +0000,nypost,Trump admin slams CBS for leaving out ‘absurd ...,https://nypost.com/2026/10/27/us-news/trump-ad...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2430/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
37        trump     35
95     election     24
237         new     16
268  california     14
154      brazil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
156,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,104
202,2026-10-26-18-40-02 +0000,nyt,Trump’s Election Attacks Enter New Pre-emptive...,https://www.nytimes.com/2026/10/25/us/politics...,86
241,2026-10-26-16-26-22 +0000,nypost,"Maurene Comey, daughter of ex-FBI director, un...",https://nypost.com/2026/10/26/us-news/maurene-...,81
85,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...,80
253,2026-10-26-15-10-00 +0000,wsj,Allies worry Senate Majority Leader John Thune...,https://www.wsj.com/politics/elections/a-bruis...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
156,104,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...
314,71,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
231,69,2026-10-26-16-51-12 +0000,nypost,Pro-Abdul El-Sayed ad sparks fury with false c...,https://nypost.com/2026/10/26/us-news/pro-abdu...
354,59,2026-10-26-08-24-19 +0000,wsj,"Stock Market News, Oct. 26, 2026: Tech Shares ...",https://www.wsj.com/livecoverage/stock-market-...
112,58,2026-10-26-21-53-41 +0000,nypost,Ex-FBI Director James Comey facing new crimina...,https://nypost.com/2026/10/26/us-news/ex-fbi-d...
77,56,2026-10-27-00-11-23 +0000,nypost,California judges deal huge blow to DOJ’s bid ...,https://nypost.com/2026/10/26/us-news/federal-...
277,41,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...
104,41,2026-10-26-22-37-54 +0000,cbc,First Nations-first ministers' meeting brings ...,https://www.cbc.ca/news/indigenous/first-natio...
97,40,2026-10-26-23-08-45 +0000,nypost,Rick Caruso backs former rival Karen Bass for ...,https://nypost.com/2026/10/26/us-news/rick-car...
188,38,2026-10-26-19-20-45 +0000,nypost,Microsoft announces buyouts for 60K employees ...,https://nypost.com/2026/10/26/tech/microsoft-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)