## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-02-14-12-15 +0000,nypost,Iran signaled it would allow Hormuz to reopen ...,https://nypost.com/2026/08/02/us-news/iran-sig...
1,2026-08-02-14-10-17 +0000,nyt,"Trump Says He Canceled Strikes on Iran, Claimi...",https://www.nytimes.com/2026/08/02/world/middl...
2,2026-08-02-14-03-24 +0000,nyt,How a Top Law Firm Went From Standing Up to Tr...,https://www.nytimes.com/2026/08/02/us/politics...
3,2026-08-02-14-03-03 +0000,nyt,Chicago’s Mayoral Race Is Taking Shape. But Wh...,https://www.nytimes.com/2026/08/02/us/chicago-...
4,2026-08-02-14-00-00 +0000,nypost,Hero sheepdog takes charge of SoCal rescue — w...,https://nypost.com/2026/08/02/us-news/heroic-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2520/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7    trump     23
0     iran     11
143    new      9
240  spain      8
96    dead      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
58,2026-08-02-08-50-02 +0000,startribune,Trump says he will order halt to Iran strikes ...,https://www.startribune.com/trump-says-he-will...,58
126,2026-08-01-21-28-51 +0000,chitri,Jeanine Pirro refutes President Donald Trump’s...,https://www.chicagotribune.com/2026/08/01/hear...,52
0,2026-08-02-14-12-15 +0000,nypost,Iran signaled it would allow Hormuz to reopen ...,https://nypost.com/2026/08/02/us-news/iran-sig...,51
81,2026-08-02-03-56-00 +0000,wsj,"Trump Calls Off Planned Attack on Iran, Citing...",https://www.wsj.com/world/middle-east/iran-sto...,51
85,2026-08-02-02-34-48 +0000,nypost,Trump says Iran agreed to ‘perimeters’ of a pe...,https://nypost.com/2026/08/01/us-news/trump-sa...,51

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
58,58,2026-08-02-08-50-02 +0000,startribune,Trump says he will order halt to Iran strikes ...,https://www.startribune.com/trump-says-he-will...
17,42,2026-08-02-12-01-35 +0000,nypost,Hero armed citizen opened fire on Idaho In-N-O...,https://nypost.com/2026/08/02/us-news/hero-arm...
159,35,2026-08-01-16-50-51 +0000,cbc,"Nirmal Purja, 'inspirational' Nepali climber, ...",https://www.cbc.ca/news/world/nepal-climber-ni...
151,32,2026-08-01-17-22-00 +0000,wsj,"U.S. Drops Vandalism Case Against Olympian, Sa...",https://www.wsj.com/us-news/law/prosecutors-dr...
9,30,2026-08-02-13-50-26 +0000,nyt,Far-Right Leaders Step Up Calls for Expelling ...,https://www.nytimes.com/2026/08/02/world/europ...
170,29,2026-08-01-16-00-00 +0000,wsj,A Tech Founder Wanted to Start a New Country. ...,https://www.wsj.com/tech/a-tech-founder-wanted...
93,28,2026-08-02-01-00-00 +0000,wsj,High-profile donors have given little or no mo...,https://www.wsj.com/politics/elections/democra...
63,27,2026-08-02-08-22-24 +0000,nypost,"Homemade bomb carried by woman kills 3, injure...",https://nypost.com/2026/08/02/world-news/russi...
11,25,2026-08-02-13-30-00 +0000,nypost,Tech bro’s $45 billion AI fund collapses days ...,https://nypost.com/2026/08/02/us-news/tech-bro...
114,25,2026-08-01-23-06-46 +0000,nypost,Spain installs floating barrier as death toll ...,https://nypost.com/2026/08/01/world-news/spain...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)