## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-04-50-35 +0000,48hills,Fall Arts Preview: 10 live music shows to ring...,https://48hills.org/2026/09/fall-arts-preview-...
1,2026-09-08-04-48-15 +0000,startribune,"Joe Ryan’s return to rotation is promising, bu...",https://www.startribune.com/minnesota-twins-de...
2,2026-09-08-04-42-47 +0000,nyt,"Philippines Lawmaker, Cousin of Marcos, Charge...",https://www.nytimes.com/2026/09/07/world/asia/...
3,2026-09-08-04-26-19 +0000,nyt,Containing Germany’s Far Right,https://www.nytimes.com/2026/09/07/world/germa...
4,2026-09-08-04-09-07 +0000,latimes,Two killed in plane crash at corporate airfiel...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2524/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
51     new     21
47   trump     21
33   plane     16
18     day     13
145  miami     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
112,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...,108
184,2026-09-07-13-26-01 +0000,nyt,Trump Posts Map Suggesting New Mexico Be Renam...,https://www.nytimes.com/2026/09/07/us/politics...,81
151,2026-09-07-15-15-14 +0000,chitri,Fuel prices at record Labor Day high in US tha...,https://www.chicagotribune.com/2026/09/07/fuel...,67
152,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...,67
40,2026-09-08-01-06-19 +0000,nyt,Officials Search for Answers After Fatal Miami...,https://www.nytimes.com/2026/09/07/us/miami-ai...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
112,108,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
152,67,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...
40,60,2026-09-08-01-06-19 +0000,nyt,Officials Search for Answers After Fatal Miami...,https://www.nytimes.com/2026/09/07/us/miami-ai...
155,44,2026-09-07-15-03-22 +0000,chitri,AfD party’s landslide win in eastern Germany t...,https://www.chicagotribune.com/2026/09/07/afd-...
251,36,2026-09-07-08-46-42 +0000,nypost,North Korea and Russia open their first road b...,https://nypost.com/2026/09/07/world-news/north...
62,35,2026-09-07-22-29-10 +0000,nypost,"Pregnant California mom, 22, has life support ...",https://nypost.com/2026/09/07/us-news/pregnant...
134,31,2026-09-07-16-27-54 +0000,nypost,OpenAI hires Chuck Schumer’s daughter as Big T...,https://nypost.com/2026/09/07/business/openai-...
29,30,2026-09-08-01-47-07 +0000,nypost,Wild dashcam video shows crossing guard shield...,https://nypost.com/2026/09/07/us-news/wild-das...
8,30,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...
193,29,2026-09-07-12-23-21 +0000,nypost,Iran says it plans to create new ‘restricted z...,https://nypost.com/2026/09/07/world-news/iran-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)