## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-09-36-01 +0000,bbc,Key points as MPs question former Foreign Offi...,https://www.bbc.com/news/articles/cn8p7vn759xo...
1,2026-04-28-09-30-00 +0000,wsj,Chip Startup Aims to Shatter AI’s Dreaded Memo...,https://www.wsj.com/tech/chip-startup-aims-to-...
2,2026-04-28-09-30-00 +0000,wsj,There’s a Revolution in Cancer. But Can Big Ph...,https://www.wsj.com/finance/investing/theres-a...
3,2026-04-28-09-30-00 +0000,wsj,Can Social-Media Fame Power an IPO? Bill Ackma...,https://www.wsj.com/finance/investing/can-soci...
4,2026-04-28-09-30-00 +0000,wsj,Federal Reserve officials are watching how the...,https://www.wsj.com/economy/central-banking/th...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2480/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
107     trump     42
52       iran     22
148     court     18
447  shooting     14
102        up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
48,2026-04-28-07-40-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...,158
78,2026-04-28-04-19-15 +0000,nypost,Jimmy Kimmel repeats ‘hateful’ joke about ‘exp...,https://nypost.com/2026/04/28/us-news/jimmy-ki...,115
197,2026-04-27-20-18-06 +0000,nyt,President and First Lady Melania Trump Demand ...,https://www.nytimes.com/2026/04/27/us/politics...,111
100,2026-04-28-02-07-55 +0000,nypost,Mentalist Oz Pearlman won’t appear on ‘Jimmy K...,https://nypost.com/2026/04/27/us-news/mentalis...,110
65,2026-04-28-05-48-17 +0000,bbc,Inside Trump press dinner shooting suspect's c...,https://www.bbc.com/news/videos/cj6p277r3k4o?a...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
48,158,2026-04-28-07-40-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...
232,69,2026-04-27-17-57-06 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
111,60,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...
206,58,2026-04-27-20-08-59 +0000,latimes,OpenAI CEO Sam Altman apologizes for not alert...,https://www.latimes.com/business/story/2026-04...
318,56,2026-04-27-11-02-00 +0000,wsj,The gunman at the White House Correspondents’ ...,https://www.wsj.com/politics/what-the-wsj-saw-...
286,55,2026-04-27-14-08-53 +0000,nyt,China Will Require Meta to Unwind Acquisition ...,https://www.nytimes.com/2026/04/27/business/ch...
205,42,2026-04-27-20-12-17 +0000,nyt,"Oil Rises, and Stocks Tick Higher, as Iran Mak...",https://www.nytimes.com/2026/04/26/business/oi...
51,38,2026-04-28-07-34-09 +0000,nypost,Trial of Austrian man accused of plotting to a...,https://nypost.com/2026/04/28/world-news/trial...
282,36,2026-04-27-14-36-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
177,36,2026-04-27-21-07-56 +0000,wapo,King Charles’s rare state visit offers U.K. a ...,https://www.washingtonpost.com/politics/2026/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)