## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-25-15-46-48 +0000,nypost,North Carolina man admits orchestrating health...,https://nypost.com/2026/06/25/us-news/north-ca...
1,2026-06-25-15-45-10 +0000,startribune,Supreme Court strikes down Hawaii law requirin...,https://www.startribune.com/supreme-court-stri...
2,2026-06-25-15-44-37 +0000,nyt,Venezuela Live Updates: Death Toll Rises as Re...,https://www.nytimes.com/live/2026/06/25/world/...
3,2026-06-25-15-44-20 +0000,nyt,Turkey or Türkiye? Who Is the U.S. Playing?,https://www.nytimes.com/2026/06/25/world/europ...
4,2026-06-25-15-42-11 +0000,bbc,Supreme Court allows Trump to end protected st...,https://www.bbc.co.uk/news/articles/c4g8ym422l...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
38       trump     39
110        new     27
78        iran     25
22   venezuela     18
12       court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
97,2026-06-25-13-13-25 +0000,nypost,Rubio warns Iran of Strait of Hormuz toll ‘fan...,https://nypost.com/2026/06/25/us-news/rubio-wa...,116
67,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...,107
44,2026-06-25-14-49-39 +0000,latimes,Supreme Court rules Trump may end legal protec...,https://www.latimes.com/politics/story/2026-06...,107
322,2026-06-24-20-25-00 +0000,wsj,Tuesday’s primary results make clear that New ...,https://www.wsj.com/politics/elections/mamdani...,105
341,2026-06-24-18-57-41 +0000,nypost,Trump gets into shouting match with Sen. Bill ...,https://nypost.com/2026/06/24/us-news/trump-ge...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
97,116,2026-06-25-13-13-25 +0000,nypost,Rubio warns Iran of Strait of Hormuz toll ‘fan...,https://nypost.com/2026/06/25/us-news/rubio-wa...
322,105,2026-06-24-20-25-00 +0000,wsj,Tuesday’s primary results make clear that New ...,https://www.wsj.com/politics/elections/mamdani...
56,82,2026-06-25-14-35-51 +0000,latimes,"Gun owners may carry a weapon into stores, Sup...",https://www.latimes.com/politics/story/2026-06...
261,63,2026-06-24-23-06-52 +0000,nypost,Venezuela rocked by strongest earthquakes in o...,https://nypost.com/2026/06/24/world-news/venez...
325,58,2026-06-24-20-21-38 +0000,cbc,"While focus remains on men's World Cup, clock ...",https://www.cbc.ca/sports/soccer/worldcup/worl...
225,56,2026-06-25-03-22-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
45,52,2026-06-25-14-48-37 +0000,nypost,"Apple hikes MacBook, iPad prices by as much as...",https://nypost.com/2026/06/25/business/apple-h...
242,41,2026-06-25-01-33-44 +0000,nypost,Trump kicks off Great American State Fair cele...,https://nypost.com/2026/06/24/us-news/trump-sa...
17,39,2026-06-25-15-25-32 +0000,nyt,See Record-Breaking Extreme Heat Wave Across E...,https://www.nytimes.com/2026/06/24/world/europ...
160,34,2026-06-25-10-08-00 +0000,wsj,Germany’s Merck to Boost Life-Sciences Busines...,https://www.wsj.com/business/deals/germanys-me...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)