## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-17-08-00 +0000,wsj,France’s TotalEnergies Walks Away From U.S. Of...,https://www.wsj.com/business/frances-totalener...
1,2026-03-23-17-07-56 +0000,nypost,LaGuardia Airport has experienced two tragedie...,https://nypost.com/2026/03/23/us-news/laguardi...
2,2026-03-23-17-07-36 +0000,nyt,Iran War Live Updates: Iran Disputes Trump’s C...,https://www.nytimes.com/live/2026/03/23/world/...
3,2026-03-23-17-07-32 +0000,bbc,PM warns against 'false comfort' of thinking I...,https://www.bbc.com/news/articles/cy01l49kkgdo...
4,2026-03-23-17-07-03 +0000,startribune,Killings of 2 Minnesota women raise questions ...,https://www.startribune.com/killings-of-2-minn...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2603/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
7   trump     40
18   iran     36
19    war     18
47    new     15
73    oil     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-23-17-07-36 +0000,nyt,Iran War Live Updates: Iran Disputes Trump’s C...,https://www.nytimes.com/live/2026/03/23/world/...,145
277,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,130
123,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...,126
148,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,122
84,2026-03-23-14-58-16 +0000,nyt,Oil Prices Tumble and Stocks Rise as Trump Bac...,https://www.nytimes.com/2026/03/23/business/oi...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,145,2026-03-23-17-07-36 +0000,nyt,Iran War Live Updates: Iran Disputes Trump’s C...,https://www.nytimes.com/live/2026/03/23/world/...
216,74,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
32,72,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
134,63,2026-03-23-12-38-54 +0000,nypost,Newark Airport issues ground stop due to smoke...,https://nypost.com/2026/03/23/us-news/newark-a...
123,48,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...
93,39,2026-03-23-14-40-20 +0000,nypost,US negotiating with Iranian parliament speaker...,https://nypost.com/2026/03/23/us-news/us-negot...
168,38,2026-03-23-10-00-00 +0000,latimes,Data centers under scrutiny by California lawm...,https://www.latimes.com/california/story/2026-...
160,31,2026-03-23-10-47-30 +0000,nypost,Trump ties deal reopening DHS to passage of SA...,https://nypost.com/2026/03/23/us-news/trump-ti...
141,29,2026-03-23-12-12-49 +0000,nyt,London Arson Attack on Jewish Ambulance Servic...,https://www.nytimes.com/2026/03/23/world/europ...
127,29,2026-03-23-13-08-50 +0000,nypost,OnlyFans owner Leonid Radvinsky dies at 43 fol...,https://nypost.com/2026/03/23/business/onlyfan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)