## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-02-44-02 +0000,bbc,Henry Nowak arrest footage raises 'serious que...,https://www.bbc.com/news/articles/cq8pn9ng5zlo...
1,2026-06-03-02-41-01 +0000,nyt,Who Can Vote for Mayor of Los Angeles?,https://www.nytimes.com/2026/06/02/us/politics...
2,2026-06-03-02-40-52 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/02/us/pri...
3,2026-06-03-02-40-05 +0000,nyt,Late-Arriving Ballots Could Lean Democratic in...,https://www.nytimes.com/2026/06/02/us/election...
4,2026-06-03-02-39-34 +0000,nyt,Supreme Court Clears the Way for Republican-Fr...,https://www.nytimes.com/2026/06/02/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2524/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
45        trump     34
31          new     20
123        iran     19
19   california     19
95     governor     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,122
155,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,107
77,2026-06-02-23-59-00 +0000,wsj,The Trump administration is abandoning its $1....,https://www.wsj.com/politics/policy/gop-leader...,91
212,2026-06-02-17-39-00 +0000,nypost,"Steve Hilton gets backing from JD Vance, Donal...",https://nypost.com/2026/06/02/us-news/steve-hi...,84
205,2026-06-02-18-12-52 +0000,nypost,Rubio insists Trump’s proposed deal with Iran ...,https://nypost.com/2026/06/02/us-news/rubio-in...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,122,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
72,69,2026-06-03-00-00-03 +0000,nypost,Little talked about California election race t...,https://nypost.com/2026/06/02/us-news/why-cali...
22,63,2026-06-03-02-04-38 +0000,nyt,Iran War Live Updates: Iran Targets Neighbors ...,https://www.nytimes.com/live/2026/06/02/world/...
45,57,2026-06-03-01-04-06 +0000,nypost,Rebecca Bennett wins Democratic primary for NJ...,https://nypost.com/2026/06/02/us-news/rebecca-...
317,51,2026-06-02-09-30-00 +0000,wsj,Berkshire Hathaway’s $6.8 billion deal to acqu...,https://www.wsj.com/economy/housing/berkshire-...
26,50,2026-06-03-01-57-42 +0000,nypost,"Iowa Dem Josh Turek takes down lefty foe, teei...",https://nypost.com/2026/06/02/us-news/iowa-dem...
247,44,2026-06-02-15-58-23 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
77,40,2026-06-02-23-59-00 +0000,wsj,The Trump administration is abandoning its $1....,https://www.wsj.com/politics/policy/gop-leader...
10,39,2026-06-03-02-29-59 +0000,cbc,CBS News fires veteran journalist Scott Pelley...,https://www.cbc.ca/news/world/scott-pelley-fir...
170,35,2026-06-02-20-08-23 +0000,nyt,"Murder of Henry Nowak, Who Was Handcuffed by P...",https://www.nytimes.com/2026/06/02/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)