## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-01-30-56 +0000,nypost,New Skid Row footage shows homeless making stu...,https://nypost.com/2026/06/11/us-news/skid-row...
1,2026-06-12-01-28-16 +0000,nyt,"In a Trump-Endorsed Presidential Candidate, Co...",https://www.nytimes.com/2026/06/11/us/abelardo...
2,2026-06-12-01-22-57 +0000,nyt,Supreme Court Blocks Alabama from Executing In...,https://www.nytimes.com/2026/06/11/us/supreme-...
3,2026-06-12-01-22-14 +0000,missionlocal,Mexico fans gather in the Mission for World Cu...,https://missionlocal.org/2026/06/san-francisco...
4,2026-06-12-01-21-25 +0000,nyt,"As World Cup Begins, Mexico City Becomes a Glo...",https://www.nytimes.com/2026/06/11/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
11    trump     37
181    iran     32
35    world     29
36      cup     21
137  spacex     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
21,2026-06-12-00-42-00 +0000,nyt,Iran War Live Updates: Trump Again Claims Deal...,https://www.nytimes.com/live/2026/06/11/world/...,124
194,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...,123
39,2026-06-11-23-37-00 +0000,wsj,"Trump Cancels Iran Strikes, Says Peace Deal Co...",https://www.wsj.com/world/middle-east/trump-ir...,112
289,2026-06-11-12-46-03 +0000,nypost,Trump says US ‘will be taking Kharg Island’ oi...,https://nypost.com/2026/06/11/us-news/trump-sa...,108
154,2026-06-11-19-09-47 +0000,nypost,Dow jumps 900 points after Trump calls off Ira...,https://nypost.com/2026/06/11/business/dow-jum...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
21,124,2026-06-12-00-42-00 +0000,nyt,Iran War Live Updates: Trump Again Claims Deal...,https://www.nytimes.com/live/2026/06/11/world/...
35,95,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...
41,61,2026-06-11-23-30-52 +0000,bbc,Elon Musk's SpaceX raises $75bn ahead of recor...,https://www.bbc.com/news/articles/cwy034q89j4o...
13,56,2026-06-12-01-00-00 +0000,wsj,When Trump meets his counterparts at next week...,https://www.wsj.com/economy/global/the-global-...
53,55,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
199,51,2026-06-11-17-34-06 +0000,nypost,Minnesota assassin Vance Boelter admits murder...,https://nypost.com/2026/06/11/us-news/minnesot...
7,48,2026-06-12-01-12-16 +0000,nypost,Another California city launches all-out war o...,https://nypost.com/2026/06/11/us-news/santa-ba...
297,47,2026-06-11-11-58-14 +0000,bbc,Knicks fans go wild as New York team makes big...,https://www.bbc.com/news/articles/cr47lyzr4q9o...
116,40,2026-06-11-20-51-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/policy/showdown-b...
291,39,2026-06-11-12-31-26 +0000,bbc,Three Indian sailors killed in US strike on oi...,https://www.bbc.com/news/articles/cy73dr081p8o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)