## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-13-14-03 +0000,nyt,Iran War Live Updates: Oil Climbs Back Above $...,https://www.nytimes.com/live/2026/04/13/world/...
1,2026-04-13-13-08-44 +0000,nyt,"Hungary May No Longer Be Putin’s Ally, but It ...",https://www.nytimes.com/2026/04/13/world/europ...
2,2026-04-13-13-07-12 +0000,bbc,Peru election drags into second day after ball...,https://www.bbc.com/news/articles/c4gd0l2x8j2o...
3,2026-04-13-13-06-29 +0000,nyt,"In the Desert, a ‘Cleaning Station’ for Ants",https://www.nytimes.com/2026/04/13/science/har...
4,2026-04-13-13-05-23 +0000,nypost,Lynette Hooker told friend she was scared of b...,https://nypost.com/2026/04/13/us-news/lynette-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2490/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0       iran     46
45     trump     39
9   blockade     25
8     hormuz     21
73  swalwell     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
67,2026-04-13-10-49-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,175
127,2026-04-13-06-48-00 +0000,wsj,"Gold Falls as Trump Hormuz Blockade Threats, F...",https://www.wsj.com/finance/commodities-future...,165
125,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,163
23,2026-04-13-12-15-03 +0000,startribune,"Pope Leo says he does not fear Trump, citing G...",https://www.startribune.com/trump-lambasts-pop...,162
265,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
67,175,2026-04-13-10-49-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
294,108,2026-04-12-13-19-52 +0000,cbc,U.S. says Strait of Hormuz blockade will start...,https://www.cbc.ca/news/world/trump-strait-of-...
172,108,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
224,57,2026-04-12-19-50-52 +0000,nypost,Hungary’s Viktor Orbán concedes defeat after ‘...,https://nypost.com/2026/04/12/world-news/hunga...
251,42,2026-04-12-17-47-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
228,40,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
57,34,2026-04-13-11-01-00 +0000,missionlocal,Will a new state law put teeth into S.F. supe ...,https://missionlocal.org/2026/04/sober-housing...
121,29,2026-04-13-07-57-36 +0000,nypost,"Strikes on alleged drug boats kill 5, leave 1 ...",https://nypost.com/2026/04/13/us-news/strikes-...
148,27,2026-04-13-03-21-14 +0000,nypost,Swalwell’s sex scandal explodes into all-out p...,https://nypost.com/2026/04/12/us-news/swalwell...
39,25,2026-04-13-11-41-12 +0000,nypost,Husband of missing mom Lynette Hooker in ‘extr...,https://nypost.com/2026/04/13/us-news/husband-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)