## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-11-17-01-58 +0000,bbc,UK shelves Chagos deal after Trump opposition,https://www.bbc.com/news/articles/c04x1lg1lygo...
1,2026-04-11-17-00-00 +0000,startribune,Maltreatment deaths of Minnesota seniors promp...,https://www.startribune.com/maltreatment-death...
2,2026-04-11-16-56-57 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Hist...,https://www.nytimes.com/live/2026/04/11/world/...
3,2026-04-11-16-56-55 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/11/world/...
4,2026-04-11-16-55-55 +0000,nyt,Pentagon Asks Court to Keep Its Restrictions o...,https://www.nytimes.com/2026/04/11/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
13       iran     48
4       trump     35
14        war     25
22      talks     22
128  swalwell     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-11-16-56-57 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Hist...,https://www.nytimes.com/live/2026/04/11/world/...,169
133,2026-04-11-01-21-53 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,138
9,2026-04-11-16-40-02 +0000,startribune,Historic US-Iran direct talks begin in Pakista...,https://www.startribune.com/us-iran-talks-set-...,118
213,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...,115
50,2026-04-11-13-00-59 +0000,wapo,How college students who study war view Trump’...,https://www.washingtonpost.com/nation/2026/04/...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,169,2026-04-11-16-56-57 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Hist...,https://www.nytimes.com/live/2026/04/11/world/...
115,100,2026-04-11-04-38-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
195,70,2026-04-10-20-58-00 +0000,wsj,President Trump has repeatedly promised his to...,https://www.wsj.com/politics/policy/trump-prom...
56,49,2026-04-11-12-10-04 +0000,nypost,China plans to deliver air defense systems to ...,https://nypost.com/2026/04/11/world-news/china...
37,46,2026-04-11-14-14-36 +0000,nypost,Iran threatens to attack US Navy ships enterin...,https://nypost.com/2026/04/11/world-news/iran-...
255,43,2026-04-10-18-31-35 +0000,missionlocal,SFPD arrests young suspect who allegedly threw...,https://missionlocal.org/2026/04/sfpd-arson-su...
213,42,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...
125,36,2026-04-11-02-28-16 +0000,nypost,"Four women detail horrific sexual assault, mis...",https://nypost.com/2026/04/10/us-news/four-wom...
141,31,2026-04-11-00-38-44 +0000,bbc,Artemis II mission was a triumph - now comes t...,https://www.bbc.com/news/articles/cj0v119zp19o...
167,28,2026-04-10-22-37-00 +0000,wsj,MAHA activists visit the White House as Republ...,https://www.wsj.com/politics/policy/white-hous...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)