## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-28-23-47-29 +0000,missionlocal,"Muni stabbing suspect pleads not guilty, order...",https://missionlocal.org/2026/09/muni-stabbing...
1,2026-09-28-23-45-49 +0000,missionlocal,Meet the S.F. congressional candidates: What w...,https://missionlocal.org/2026/09/sf-congress-o...
2,2026-09-28-23-44-49 +0000,bbc,Journalist to be crowned king in Uganda after ...,https://www.bbc.co.uk/news/articles/cx7v4glz50...
3,2026-09-28-23-43-48 +0000,bbc,Hurricane Polo unleashes threatening winds as ...,https://www.bbc.co.uk/news/articles/cw8d3z5y79...
4,2026-09-28-23-37-00 +0000,wsj,Samsung Commits $1.0 Billion to AI Infrastruct...,https://www.wsj.com/tech/ai/samsung-commits-1-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2338/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
196       trump     37
98          new     21
285          uk     14
92   california     12
34      billion     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
61,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...,193
133,2026-09-28-19-37-09 +0000,chitri,President Trump announces a new $15B Iowa stee...,https://www.chicagotribune.com/2026/09/28/trum...,99
146,2026-09-28-19-15-55 +0000,wapo,Trump says new fuel economy rules will cut car...,https://www.washingtonpost.com/transportation/...,94
78,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...,91
22,2026-09-28-22-46-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
61,193,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...
228,68,2026-09-28-14-42-32 +0000,nypost,Five British nationals already out on bail aft...,https://nypost.com/2026/09/28/world-news/five-...
38,48,2026-09-28-22-02-24 +0000,nypost,California city cracks top 3 in America’s best...,https://nypost.com/2026/09/28/lifestyle/5-cali...
214,46,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
195,43,2026-09-28-16-54-00 +0000,wsj,A Federal Reserve employee transferred potenti...,https://www.wsj.com/economy/central-banking/fe...
346,43,2026-09-28-03-44-18 +0000,latimes,Brokers gobble up tee times at public golf cou...,https://www.latimes.com/california/story/2026-...
78,40,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...
187,40,2026-09-28-17-10-56 +0000,nypost,Oil soars above $107 after Trump rejects Iran ...,https://nypost.com/2026/09/28/business/oil-soa...
255,38,2026-09-28-13-07-00 +0000,wsj,Ahead of the release of his book “This Cursed ...,https://www.wsj.com/world/how-evan-gershkovich...
16,36,2026-09-28-22-56-47 +0000,nypost,Slain New York Times exec was in vicious fight...,https://nypost.com/2026/09/28/us-news/slain-ny...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)