## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-25-20-31-22 +0000,nyt,OpenAI Leans Toward Holding Up I.P.O. Until Ne...,https://www.nytimes.com/2026/06/25/technology/...
1,2026-06-25-20-27-32 +0000,nyt,Oil Prices Jump After Attack Halts Shipping in...,https://www.nytimes.com/2026/06/25/business/oi...
2,2026-06-25-20-23-00 +0000,wsj,The Long Race to Succeed Jamie Dimon Heats Up,https://www.wsj.com/finance/stocks/the-long-ra...
3,2026-06-25-20-19-53 +0000,nyt,Venezuela Live Updates: Rescuers Search for Su...,https://www.nytimes.com/live/2026/06/25/world/...
4,2026-06-25-20-18-45 +0000,nyt,Medical Journal Retracts Study Claiming Cancer...,https://www.nytimes.com/2026/06/25/business/ch...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
61       trump     43
109        new     26
227       iran     23
59       court     23
22   venezuela     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...,127
171,2026-06-25-14-49-39 +0000,latimes,Supreme Court rules Trump may end legal protec...,https://www.latimes.com/politics/story/2026-06...,120
354,2026-06-24-23-06-52 +0000,nypost,Venezuela rocked by strongest earthquakes in o...,https://nypost.com/2026/06/24/world-news/venez...,120
86,2026-06-25-18-17-35 +0000,wapo,Rubio’s new job? Selling Trump’s Iran deal to ...,https://www.washingtonpost.com/national-securi...,114
11,2026-06-25-20-13-03 +0000,nypost,Dems erupt in fury after Supreme Court hands T...,https://nypost.com/2026/06/25/us-news/democrat...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,127,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...
364,83,2026-06-24-22-31-00 +0000,wsj,The Pentagon awarded Lockheed Martin a contrac...,https://www.wsj.com/politics/national-security...
76,62,2026-06-25-18-30-24 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/2026/06/25/world/ameri...
99,61,2026-06-25-17-44-34 +0000,nypost,Second lady Usha Vance claps back at New York ...,https://nypost.com/2026/06/25/lifestyle/usha-v...
164,58,2026-06-25-15-16-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
1,52,2026-06-25-20-27-32 +0000,nyt,Oil Prices Jump After Attack Halts Shipping in...,https://www.nytimes.com/2026/06/25/business/oi...
17,43,2026-06-25-20-04-00 +0000,wsj,The U.S. Army is leasing land on bases across ...,https://www.wsj.com/politics/national-security...
320,42,2026-06-25-03-22-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
313,40,2026-06-25-04-24-24 +0000,latimes,Violence erupted near World Cup watch party in...,https://www.latimes.com/california/story/2026-...
195,38,2026-06-25-13-33-17 +0000,nyt,Some Museums in the UK and France Reduce Their...,https://www.nytimes.com/2026/06/25/arts/europe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)