## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-14-18-26 +0000,nypost,Scott Peterson deserves another trial after ‘n...,https://nypost.com/2026/07/18/us-news/scott-pe...
1,2026-07-18-14-16-12 +0000,nyt,Kuwait accuses Iran of targeting civilian site...,https://www.nytimes.com/live/2026/07/18/world/...
2,2026-07-18-14-10-15 +0000,nypost,"NYPD cop’s relative, 24, fatally shot in the e...",https://nypost.com/2026/07/18/us-news/nypd-cop...
3,2026-07-18-14-08-00 +0000,wsj,Turkey Aims to Offload Russian Air-Defense Sys...,https://www.wsj.com/world/turkey-aims-to-offlo...
4,2026-07-18-14-07-52 +0000,nyt,Surrogacy Scandal Upends German Politics,https://www.nytimes.com/2026/07/18/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3140/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
127  trump     35
5      new     14
119     he     13
13    iran     12
147  world     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
119,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...,113
17,2026-07-18-13-13-39 +0000,nypost,Kai Trump reveals what she’s giving her grandf...,https://nypost.com/2026/07/18/us-news/kai-trum...,88
237,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...,87
147,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...,83
261,2026-07-17-16-31-00 +0000,wsj,President Trump wants the Republican-controlle...,https://www.wsj.com/politics/policy/save-act-v...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
119,113,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...
237,52,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...
147,48,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...
114,46,2026-07-18-01-29-47 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...
86,45,2026-07-18-08-00-00 +0000,cbc,This World Cup photographer used a 96-year-old...,https://www.cbc.ca/news/canada/world-cup-photo...
26,42,2026-07-18-13-00-00 +0000,nypost,Southern California beach city to increase par...,https://nypost.com/2026/07/18/us-news/manhatta...
69,41,2026-07-18-10-00-00 +0000,latimes,West Hollywood faces long recovery from massiv...,https://www.latimes.com/california/story/2026-...
159,34,2026-07-17-21-38-00 +0000,wsj,China’s Moonshot AI Adds More Fuel to Wall Str...,https://www.wsj.com/finance/stocks/chinas-moon...
257,34,2026-07-17-16-43-32 +0000,nypost,Dem-run ‘Dear White Staffers’ X account joins ...,https://nypost.com/2026/07/17/us-news/dem-run-...
229,33,2026-07-17-18-12-54 +0000,bbc,Magnitude 7.3 earthquake quake strikes off Mex...,https://www.bbc.co.uk/news/articles/cwyjv3815y...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)