## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-14-19-58 +0000,48hills,Live Shots: Lamb of God took the Masonic ‘Into...,https://48hills.org/2026/04/live-shots-lamb-of...
1,2026-04-15-14-15-50 +0000,bbc,Israel and Hezbollah continue attacks after Is...,https://www.bbc.com/news/articles/c87ww2z0z3zo...
2,2026-04-15-14-14-41 +0000,bbc,Trump threatens to fire Fed chair Powell if he...,https://www.bbc.com/news/articles/c9qddrdd8w2o...
3,2026-04-15-14-14-03 +0000,nyt,Trump’s Blockade Risks Upending an Emerging Dé...,https://www.nytimes.com/2026/04/14/us/politics...
4,2026-04-15-14-13-33 +0000,nyt,How China’s Weapons Transfers to Iran Have Evo...,https://www.nytimes.com/2026/04/15/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2497/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
31    iran     39
13   trump     37
42     new     26
56     war     22
196     up     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
26,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,150
73,2026-04-15-11-39-31 +0000,nypost,Trump predicts Iran war is ‘very close to bein...,https://nypost.com/2026/04/15/us-news/trump-pr...,134
107,2026-04-15-10-00-00 +0000,nypost,Trump needs ‘four- or five-month window’ betwe...,https://nypost.com/2026/04/15/us-news/trump-ne...,127
8,2026-04-15-14-07-38 +0000,nyt,Iran War Live Updates: Iran Threatens Retaliat...,https://www.nytimes.com/live/2026/04/15/world/...,126
59,2026-04-15-12-15-08 +0000,nypost,Trump says China agrees not to send Iran weapo...,https://nypost.com/2026/04/15/us-news/trump-sa...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
26,150,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
8,126,2026-04-15-14-07-38 +0000,nyt,Iran War Live Updates: Iran Threatens Retaliat...,https://www.nytimes.com/live/2026/04/15/world/...
185,74,2026-04-15-02-24-00 +0000,wsj,Prosecutors from U.S. Attorney Jeanine Pirro’s...,https://www.wsj.com/us-news/law/jeanine-pirros...
86,55,2026-04-15-11-01-00 +0000,wsj,With Eric Swalwell’s resignation from Congress...,https://www.wsj.com/politics/is-swalwell-the-s...
186,51,2026-04-15-02-11-00 +0000,wsj,"Voters in South Hadley, Mass., rejected a stee...",https://www.wsj.com/us-news/massachusetts-town...
1,50,2026-04-15-14-15-50 +0000,bbc,Israel and Hezbollah continue attacks after Is...,https://www.bbc.com/news/articles/c87ww2z0z3zo...
204,46,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
221,37,2026-04-14-23-25-47 +0000,nypost,Erika Kirk pulls out of huge Turning Point USA...,https://nypost.com/2026/04/14/us-news/erika-ki...
189,37,2026-04-15-02-00-00 +0000,wsj,"So far, it is President Trump—and not Pope Leo...",https://www.wsj.com/politics/trump-pope-leo-ca...
59,35,2026-04-15-12-15-08 +0000,nypost,Trump says China agrees not to send Iran weapo...,https://nypost.com/2026/04/15/us-news/trump-sa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)