## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-23-18-53-04 +0000,bbc,Why is the price of protein powder rising?,https://www.bbc.co.uk/news/videos/cmq8j1nk2wnx...
1,2026-09-23-18-51-12 +0000,bbc,Harvey Weinstein sentenced to 15 years in pris...,https://www.bbc.co.uk/news/articles/cm98626n26...
2,2026-09-23-18-51-02 +0000,nyt,Officials Investigating Mississippi Student De...,https://www.nytimes.com/2026/09/23/us/kratom-o...
3,2026-09-23-18-49-38 +0000,nyt,U.N. Live Updates: Zelensky Warns Russian Aggr...,https://www.nytimes.com/live/2026/09/23/world/...
4,2026-09-23-18-49-37 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/09/23/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2491/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
50       trump     86
165        new     30
174       iran     21
242  president     19
278       will     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
302,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,193
296,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...,182
428,2026-09-22-20-10-43 +0000,nyt,Zelensky Says He Hopes Trump Will Help to End ...,https://www.nytimes.com/2026/09/22/world/europ...,174
379,2026-09-22-21-55-04 +0000,chitri,"‘You should not be here,’ President Trump tell...",https://www.chicagotribune.com/2026/09/22/trum...,172
384,2026-09-22-21-44-00 +0000,wsj,Delegates from Iran and Cuba walked out during...,https://www.wsj.com/politics/policy/trump-thre...,170

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
302,193,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
65,92,2026-09-23-17-37-43 +0000,nypost,Energy Secretary Chris Wright rejects outright...,https://nypost.com/2026/09/23/business/us-ener...
109,91,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
428,88,2026-09-22-20-10-43 +0000,nyt,Zelensky Says He Hopes Trump Will Help to End ...,https://www.nytimes.com/2026/09/22/world/europ...
231,67,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
379,67,2026-09-22-21-55-04 +0000,chitri,"‘You should not be here,’ President Trump tell...",https://www.chicagotribune.com/2026/09/22/trum...
180,65,2026-09-23-13-53-50 +0000,nypost,China lays out ‘red lines’ for Trump-Xi meetin...,https://nypost.com/2026/09/23/us-news/china-la...
317,51,2026-09-23-01-10-41 +0000,latimes,California deal on Paramount-Warner Bros. merg...,https://www.latimes.com/politics/story/2026-09...
328,44,2026-09-23-00-00-00 +0000,wsj,HHS moved money from a minority health office ...,https://www.wsj.com/politics/policy/rfk-jr-hhs...
52,42,2026-09-23-17-58-27 +0000,nypost,Son of Israel’s US ambassador injured in West ...,https://nypost.com/2026/09/23/world-news/son-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)