## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-14-53-19 +0000,nypost,Severe storms target 100M from Texas to Maine ...,https://nypost.com/2026/05/19/us-news/strong-s...
1,2026-05-19-14-52-25 +0000,bbc,How would a Labour leadership contest work?,https://www.bbc.com/news/articles/c3631k30xjlo...
2,2026-05-19-14-51-24 +0000,nypost,Nancy Pelosi endorses Connie Chan to succeed h...,https://nypost.com/2026/05/19/us-news/nancy-pe...
3,2026-05-19-14-50-21 +0000,nypost,Disneyland targeted in class-action lawsuit cl...,https://nypost.com/2026/05/19/us-news/disneyla...
4,2026-05-19-14-49-58 +0000,nyt,"U.S. Envoy, Looking for Friends in Greenland, ...",https://www.nytimes.com/2026/05/19/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
153  trump     43
29     new     23
95    iran     22
126     he     15
206  ebola     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
252,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,126
305,2026-05-18-19-35-00 +0000,cbc,Trump says he called off Tuesday Iran strike a...,https://www.cbc.ca/news/world/trump-iran-strik...,108
208,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,107
296,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...,100
311,2026-05-18-19-16-09 +0000,nypost,Trump pulls back on plan to attack Iran tomorr...,https://nypost.com/2026/05/18/us-news/trump-pu...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
252,126,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
170,73,2026-05-19-07-08-06 +0000,nypost,Texas mother sobs in court after allegedly kil...,https://nypost.com/2026/05/19/us-news/texas-mo...
159,66,2026-05-19-08-32-21 +0000,nypost,Terrifying moment small children evacuated fro...,https://nypost.com/2026/05/19/us-news/terrifyi...
26,50,2026-05-19-14-20-15 +0000,bbc,Ebola outbreak may be spreading faster than fi...,https://www.bbc.com/news/articles/ceqp11gn1l8o...
327,49,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
208,49,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
306,45,2026-05-18-19-32-10 +0000,nypost,Kentucky battle for Rep. Thomas Massie’s seat ...,https://nypost.com/2026/05/18/us-news/kentucky...
352,42,2026-05-18-16-40-26 +0000,nypost,Carl’s Jr. crushed by California’s high minimu...,https://nypost.com/2026/05/18/business/carls-j...
216,39,2026-05-19-01-11-59 +0000,nyt,Justice Dept. Sets Up $1.8 Billion Fund That C...,https://www.nytimes.com/2026/05/18/us/politics...
50,37,2026-05-19-13-35-54 +0000,nypost,Starbucks Korea CEO fired after ‘Tank Day’ pro...,https://nypost.com/2026/05/19/world-news/starb...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)