## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-04-14-42 +0000,nyt,Vance Heads to Talks as Strait of Hormuz Re-em...,https://www.nytimes.com/live/2026/06/20/world/...
1,2026-06-21-04-01-18 +0000,nyt,Luxury Kushner Project Collides With Albanian ...,https://www.nytimes.com/2026/06/21/world/europ...
2,2026-06-21-04-01-14 +0000,nyt,The Women Running Businesses Under Taliban Rules,https://www.nytimes.com/2026/06/21/world/asia/...
3,2026-06-21-03-49-30 +0000,nyt,"In Southeast Asia, Switching to Solar Offers R...",https://www.nytimes.com/2026/06/18/world/asia/...
4,2026-06-21-03-27-41 +0000,nyt,Huge Blaze Ravages Dominican Republic Beach Re...,https://www.nytimes.com/2026/06/20/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
85   trump     12
202  world     10
140     up      8
29    iran      8
246    new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
20,2026-06-21-00-15-38 +0000,nypost,Vance jets to Switzerland for talks on Iran pe...,https://nypost.com/2026/06/20/world-news/vance...,49
45,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...,48
125,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...,46
41,2026-06-20-22-34-00 +0000,wsj,"Vance Heads to Peace Talks, After Iran Says It...",https://www.wsj.com/world/middle-east/fighting...,42
13,2026-06-21-01-46-31 +0000,bbc,US-Iran talks to begin in Switzerland as Tehra...,https://www.bbc.com/news/articles/cwyekkwm1mmo...,37

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
20,49,2026-06-21-00-15-38 +0000,nypost,Vance jets to Switzerland for talks on Iran pe...,https://nypost.com/2026/06/20/world-news/vance...
45,48,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...
125,38,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...
92,31,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...
129,24,2026-06-20-12-00-00 +0000,latimes,Lopez: They found a new park hiding in plain s...,https://www.latimes.com/california/story/2026-...
48,23,2026-06-20-21-54-15 +0000,nypost,Astonishing move from LAPD as no arrests made ...,https://nypost.com/2026/06/20/us-news/wild-str...
113,20,2026-06-20-15-05-19 +0000,nypost,Obama Center engineer reveals former president...,https://nypost.com/2026/06/20/us-news/obama-ce...
34,20,2026-06-20-23-07-46 +0000,nypost,UK Prime Minister Keir Starmer set to resign a...,https://nypost.com/2026/06/20/world-news/uk-pr...
61,20,2026-06-20-20-18-32 +0000,nypost,"Conflict erupts in Lebanon between Israel, Hez...",https://nypost.com/2026/06/20/world-news/confl...
59,19,2026-06-20-20-40-47 +0000,nypost,Dem senators urge FCC to put Paramount-Warner ...,https://nypost.com/2026/06/20/business/dem-sen...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)