## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-10-44-50 +0000,bbc,People trapped inside Japan shopping centre af...,https://www.bbc.co.uk/news/articles/cgewg24qgn...
1,2026-07-28-10-42-23 +0000,nyt,Fresh Clashes Erupt in Pakistani Kashmir on Fi...,https://www.nytimes.com/2026/07/28/world/asia/...
2,2026-07-28-10-38-42 +0000,nyt,‘We Are Not Learning Anything’: India’s Gen Z ...,https://www.nytimes.com/2026/07/28/world/asia/...
3,2026-07-28-10-37-21 +0000,nyt,Tech Stocks Tumble on Worries About A.I. Spend...,https://www.nytimes.com/2026/07/28/business/st...
4,2026-07-28-10-36-14 +0000,nypost,Bryan Kohberger’s victim’s dad ‘would love’ re...,https://nypost.com/2026/07/28/us-news/bryan-ko...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2329/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
99    trump     40
211    iran     26
332     new     23
117  france     13
212     war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
44,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...,123
25,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,113
203,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,102
343,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...,99
205,2026-07-27-21-06-42 +0000,bbc,"As the US pauses the war with Iran, is Trump r...",https://www.bbc.co.uk/news/articles/c0qvnk2ezp...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
44,123,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...
17,63,2026-07-28-10-01-03 +0000,nyt,France and Spain Race to Tamp Down Wildfires B...,https://www.nytimes.com/2026/07/28/world/europ...
188,57,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
168,56,2026-07-27-23-26-53 +0000,nypost,Xavier Becerra leads Democrats’ all-out war ag...,https://nypost.com/2026/07/27/us-news/xavier-b...
136,50,2026-07-28-01-29-25 +0000,bbc,BBC outside court as judge rules singer D4vd w...,https://www.bbc.co.uk/news/videos/cy745x171rjo...
190,47,2026-07-27-21-46-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
135,39,2026-07-28-01-32-41 +0000,nyt,Seattle Police Search for 3rd Shooter in Deadl...,https://www.nytimes.com/2026/07/27/us/seattle-...
358,38,2026-07-27-13-24-08 +0000,nypost,Cracker Barrel CEO Julie Felss Masino steps do...,https://nypost.com/2026/07/27/business/cracker...
298,38,2026-07-27-16-40-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
373,37,2026-07-27-12-24-59 +0000,nypost,Dozens of Democrat-led states still taxing tip...,https://nypost.com/2026/07/27/us-news/dozens-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)