## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-24-04-37-47 +0000,bbc,Ethiopia and Tigray accuse each of launching o...,https://www.bbc.co.uk/news/articles/cry8zwwq21...
1,2026-09-24-04-28-00 +0000,nypost,Climber who plummeted 500 feet down notorious ...,https://nypost.com/2026/09/24/us-news/san-jose...
2,2026-09-24-04-27-09 +0000,nypost,Pentagon ‘actively working’ to retrieve F-35 f...,https://nypost.com/2026/09/24/us-news/pentagon...
3,2026-09-24-04-05-31 +0000,nypost,Heroic NYC delivery worker honored for helping...,https://nypost.com/2026/09/24/us-news/heroic-n...
4,2026-09-24-04-01-09 +0000,nyt,Inside France’s Push to Stop Migrant Boats to ...,https://www.nytimes.com/2026/09/24/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2348/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
77   trump     75
8      new     35
345     ai     22
75   house     19
82      xi     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
48,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...,158
439,2026-09-23-08-00-00 +0000,cbc,"'Nuclear' threat or market boom? Either way, A...",https://www.cbc.ca/news/world/donald-trump-xi-...,158
111,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,157
350,2026-09-23-13-53-50 +0000,nypost,China lays out ‘red lines’ for Trump-Xi meetin...,https://nypost.com/2026/09/23/us-news/china-la...,151
387,2026-09-23-11-11-02 +0000,chitri,Economic frustration tests President Donald Tr...,https://www.chicagotribune.com/2026/09/23/dona...,146

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
48,158,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...
51,116,2026-09-24-00-43-00 +0000,wsj,The last time Venezuelan leader Delcy Rodrígue...,https://www.wsj.com/world/americas/u-n-visit-s...
262,99,2026-09-23-17-37-43 +0000,nypost,Energy Secretary Chris Wright rejects outright...,https://nypost.com/2026/09/23/business/us-ener...
288,96,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
271,68,2026-09-23-17-04-19 +0000,nypost,Trump’s Board of Peace announces $2.45B first-...,https://nypost.com/2026/09/23/us-news/trumps-b...
42,52,2026-09-24-01-00-00 +0000,wsj,"The AI build-out is making history, dwarfing t...",https://www.wsj.com/economy/the-ai-build-out-i...
167,51,2026-09-23-20-45-00 +0000,wsj,Canada’s Carney Open to U.S. Trade Deal but Wo...,https://www.wsj.com/world/europe/canadas-carne...
395,50,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
336,50,2026-09-23-14-44-03 +0000,wapo,Another U.S. service member dies amid Iran war...,https://www.washingtonpost.com/politics/2026/0...
74,46,2026-09-23-23-40-10 +0000,nypost,California’s oldest continuously family-owned ...,https://nypost.com/2026/09/23/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)