## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-15-47-43 +0000,nyt,Senate Primary in Massachusetts Is a Generatio...,https://www.nytimes.com/2026/08/31/us/markey-m...
1,2026-08-31-15-47-38 +0000,nyt,Kalshi Permanently Bars George Santos From the...,https://www.nytimes.com/2026/08/31/business/ka...
2,2026-08-31-15-45-12 +0000,nyt,This Marine Died in the Iraq War. His Mother A...,https://www.nytimes.com/2026/08/31/us/politics...
3,2026-08-31-15-42-55 +0000,cbc,"Argentina soccer legend Lionel Messi, 39, reti...",https://www.cbc.ca/sports/soccer/lionel-messi-...
4,2026-08-31-15-42-20 +0000,nyt,Nonstop Russian Drones Make for Dangerous New ...,https://www.nytimes.com/2026/08/31/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2328/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
135  trump     19
34    iran     19
109  first     16
277     up     14
31     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
108,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...,86
75,2026-08-31-12-28-07 +0000,nypost,Trump calls for leaders of ‘failed nation’ Ira...,https://nypost.com/2026/08/31/world-news/trump...,75
271,2026-08-30-16-13-37 +0000,nypost,Google swaps Lake Ontario maps to ‘Lake Americ...,https://nypost.com/2026/08/30/us-news/google-m...,67
262,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,67
51,2026-08-31-13-59-16 +0000,nypost,Oil prices jump 3% to over $90 after US-Iran e...,https://nypost.com/2026/08/31/business/oil-pri...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
108,86,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...
70,62,2026-08-31-12-55-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
196,59,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
100,50,2026-08-31-10-55-00 +0000,wsj,The Texas Senate race is shaping up to be a co...,https://www.wsj.com/politics/ken-paxton-is-in-...
271,48,2026-08-30-16-13-37 +0000,nypost,Google swaps Lake Ontario maps to ‘Lake Americ...,https://nypost.com/2026/08/30/us-news/google-m...
263,41,2026-08-30-16-48-13 +0000,bbc,Head teacher evacuated 900 children minutes be...,https://www.bbc.co.uk/news/articles/c5ymvdm552...
11,39,2026-08-31-15-24-45 +0000,chitri,Kalshi bans ex-Congressman George Santos for l...,https://www.chicagotribune.com/2026/08/31/kals...
130,34,2026-08-31-10-00-00 +0000,nypost,Long Island Dems locked in civil war as member...,https://nypost.com/2026/08/31/us-news/long-isl...
236,33,2026-08-30-19-33-47 +0000,chitri,Death toll rises to 38 from Russia’s deadliest...,https://www.chicagotribune.com/2026/08/30/russ...
22,31,2026-08-31-14-50-36 +0000,bbc,'She slipped out of my hand' - children missin...,https://www.bbc.co.uk/news/articles/c1mv5ggg1l...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)