## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-07-07-18 +0000,nypost,Horror as young mom mauled to death by three d...,https://nypost.com/2026/03/04/us-news/mother-m...
1,2026-03-04-07-02-00 +0000,wsj,Bayer Net Loss Widens on Weedkiller Litigation...,https://www.wsj.com/business/earnings/bayer-ne...
2,2026-03-04-06-57-00 +0000,wsj,Germany’s Continental Expects Earnings to Incr...,https://www.wsj.com/business/earnings/germanys...
3,2026-03-04-06-49-56 +0000,nyt,Here is the latest.,https://www.nytimes.com/live/2026/03/04/world/...
4,2026-03-04-06-46-11 +0000,bbc,Asia stocks slump and oil rises for third day ...,https://www.bbc.com/news/articles/cwy884ekn0jo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
34      iran     91
296    trump     48
35       war     38
95     texas     29
132  strikes     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
17,2026-03-04-06-12-46 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...,233
232,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,204
415,2026-03-03-09-57-15 +0000,bbc,Trump voters back him on Iran - but that could...,https://www.bbc.com/news/articles/cvg35401nrqo...,188
312,2026-03-03-17-41-27 +0000,nypost,Trump shares ‘worst case’ scenario of someone ...,https://nypost.com/2026/03/03/us-news/trump-sa...,187
367,2026-03-03-13-41-43 +0000,bbc,Zelensky fears Trump's Iran war could hurt Ukr...,https://www.bbc.com/news/articles/clyv10dre79o...,187

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
17,233,2026-03-04-06-12-46 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...
50,147,2026-03-04-04-40-00 +0000,wsj,The heated Republican Senate primary in Texas ...,https://www.wsj.com/politics/elections/john-co...
190,127,2026-03-03-22-25-24 +0000,latimes,"Oil jumps, stocks fall, as Trump presses into ...",https://www.latimes.com/politics/story/2026-03...
216,93,2026-03-03-21-42-00 +0000,wsj,Minneapolis Fed President Neel Kashkari said t...,https://www.wsj.com/economy/central-banking/ka...
360,74,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
49,66,2026-03-04-04-41-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
317,53,2026-03-03-17-28-00 +0000,wsj,U.S. Troops Killed in Kuwait Had No Warning of...,https://www.wsj.com/world/middle-east/u-s-troo...
66,51,2026-03-04-03-44-09 +0000,nyt,"Beyond a Trade War, China, Japan and Others in...",https://www.nytimes.com/2026/03/02/business/us...
270,42,2026-03-03-19-48-00 +0000,wsj,Georgia Dad Colin Gray Found Guilty in Son’s S...,https://www.wsj.com/us-news/georgia-dad-colin-...
221,39,2026-03-03-21-34-00 +0000,wsj,"News Corp, Meta in AI Content Licensing Deal W...",https://www.wsj.com/business/media/news-corp-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)