## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-09-22-55-10 +0000,nypost,DSA civil war brewing over Mamdani’s Oct. 7 re...,https://nypost.com/2026/10/09/us-news/dsa-civi...
1,2026-10-09-22-55-07 +0000,nyt,Inside Erik Prince’s Mercenary Deal in Congo,https://www.nytimes.com/2026/10/09/world/afric...
2,2026-10-09-22-47-10 +0000,nyt,Big Controversy Upends a Contest About Microsc...,https://www.nytimes.com/2026/10/09/science/nik...
3,2026-10-09-22-42-20 +0000,nyt,Donor Says Kimberly Guilfoyle Sought Money Fro...,https://www.nytimes.com/2026/10/09/us/politics...
4,2026-10-09-22-41-21 +0000,bbc,Commentator Katie Zacharia picked as new White...,https://www.bbc.co.uk/news/articles/c5rmy73zr0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2501/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
70    trump     48
35      new     23
141   prize     21
139   nobel     20
75   senate     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
47,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,212
202,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...,145
60,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,137
149,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...,130
51,2026-10-09-21-37-17 +0000,nyt,Katie Zacharia Picked as Trump’s New White Hou...,https://www.nytimes.com/2026/10/09/us/politics...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
47,212,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
149,119,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...
370,118,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...
19,89,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
242,68,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
375,68,2026-10-09-02-29-35 +0000,nypost,Outraged Susan Collins demands apology after r...,https://nypost.com/2026/10/08/us-news/susan-co...
176,64,2026-10-09-16-29-36 +0000,nypost,Trump backs firing squad execution of Fort Hoo...,https://nypost.com/2026/10/09/us-news/trump-ba...
352,47,2026-10-09-07-29-42 +0000,nypost,‘The View’ co-host Sunny Hostin predicts Texas...,https://nypost.com/2026/10/09/media/the-view-c...
232,46,2026-10-09-14-13-06 +0000,nypost,Dow soars as tech shares rebound on SpaceX dea...,https://nypost.com/2026/10/09/business/stocks-...
207,43,2026-10-09-15-04-02 +0000,nypost,3 killed in Russian strikes across Ukraine as ...,https://nypost.com/2026/10/09/world-news/3-kil...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)