## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-31-04-16-52 +0000,nypost,NYC Schools chancellor makes whopping $363K — ...,https://nypost.com/2026/05/31/us-news/nyc-scho...
1,2026-05-31-04-06-47 +0000,nypost,Two women found stabbed to death in Park Slope...,https://nypost.com/2026/05/31/us-news/women-fo...
2,2026-05-31-04-04-05 +0000,startribune,Kendall Qualls secures GOP endorsement for Min...,https://www.startribune.com/kendall-qualls-win...
3,2026-05-31-04-01-07 +0000,nyt,"In Taiwan, ‘Mainland Spouses’ From China Becom...",https://www.nytimes.com/2026/05/31/world/asia/...
4,2026-05-31-03-53-45 +0000,nypost,Florida man charged with wife’s violent murder...,https://nypost.com/2026/05/30/us-news/florida-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2322/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
174   trump     27
176  health     11
50      out      9
80      new      8
541     war      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
62,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...,74
134,2026-05-30-11-23-00 +0000,wsj,President Trump “remains in excellent physical...,https://www.wsj.com/politics/trump-remains-in-...,69
110,2026-05-30-15-06-01 +0000,bbc,Trump's doctor says he's in excellent health -...,https://www.bbc.com/news/articles/c9q39dx778zo...,67
177,2026-05-30-06-43-02 +0000,nypost,White House releases doctor’s memo from Trump’...,https://nypost.com/2026/05/30/us-news/trump-in...,67
119,2026-05-30-13-39-00 +0000,wsj,President Trump’s no-audits promise from his a...,https://www.wsj.com/politics/policy/a-controve...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
62,74,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...
75,47,2026-05-30-19-16-00 +0000,wsj,The wife of Maine Democratic Senate candidate ...,https://www.wsj.com/politics/elections/graham-...
134,42,2026-05-30-11-23-00 +0000,wsj,President Trump “remains in excellent physical...,https://www.wsj.com/politics/trump-remains-in-...
9,39,2026-05-31-02-39-00 +0000,wsj,China’s manufacturing activity stayed flat in ...,https://www.wsj.com/economy/china-manufacturin...
119,36,2026-05-30-13-39-00 +0000,wsj,President Trump’s no-audits promise from his a...,https://www.wsj.com/politics/policy/a-controve...
5,34,2026-05-31-03-08-58 +0000,nypost,"Mayhem breaks out between anti-ICE protesters,...",https://nypost.com/2026/05/30/us-news/mayhem-b...
94,33,2026-05-30-17-00-00 +0000,nypost,Kelsey Grammer reveals his nasty nickname for ...,https://nypost.com/2026/05/30/us-news/kelsey-g...
53,31,2026-05-30-22-22-29 +0000,nypost,Six Flags’ new roller coaster will be among to...,https://nypost.com/2026/05/30/us-news/six-flag...
90,31,2026-05-30-17-20-00 +0000,wsj,Disclosure documents show Josh Gruenbaum was a...,https://www.wsj.com/politics/doge-official-dis...
87,30,2026-05-30-17-34-30 +0000,bbc,'No-one feels safe now': Residents of Romanian...,https://www.bbc.com/news/articles/cvgzyp93jq1o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)