## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-18-19-19-53 +0000,nyt,Ebola Was Identified in Congo Weeks Before W.H...,https://www.nytimes.com/2026/05/18/world/afric...
1,2026-05-18-19-18-58 +0000,bbc,Jury tosses Elon Musk's lawsuit against OpenAI...,https://www.bbc.com/news/articles/cewpyv79pw1o...
2,2026-05-18-19-18-31 +0000,nyt,"In Massie’s Kentucky Primary, Fidelity to Trum...",https://www.nytimes.com/2026/05/18/us/politics...
3,2026-05-18-19-16-09 +0000,nypost,Trump pulls back on plan to attack Iran tomorr...,https://nypost.com/2026/05/18/us-news/trump-pu...
4,2026-05-18-19-15-11 +0000,nypost,Cops swarm San Diego Islamic Center after acti...,https://nypost.com/2026/05/18/us-news/cops-rus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     28
190    new     16
27    iran     14
0    ebola     11
312     ai     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
234,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...,84
130,2026-05-18-14-32-21 +0000,nypost,Iran offers new 14-point peace proposal after ...,https://nypost.com/2026/05/18/us-news/iran-sub...,73
20,2026-05-18-18-53-59 +0000,bbc,Trump administration unveils $1.7bn fund to co...,https://www.bbc.com/news/articles/cvgzr7vr203o...,66
63,2026-05-18-17-32-00 +0000,wsj,President Trump will host a swearing-in ceremo...,https://www.wsj.com/economy/central-banking/tr...,66
3,2026-05-18-19-16-09 +0000,nypost,Trump pulls back on plan to attack Iran tomorr...,https://nypost.com/2026/05/18/us-news/trump-pu...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
234,84,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...
248,49,2026-05-17-23-02-56 +0000,bbc,'This may be the last time you hear my voice':...,https://www.bbc.com/news/articles/cn8p392nl7yo...
39,45,2026-05-18-18-21-53 +0000,nypost,"College grad, 22, was shot dead by boyfriend’s...",https://nypost.com/2026/05/18/us-news/college-...
91,42,2026-05-18-16-20-30 +0000,bbc,At least 100 deaths reported in Ebola outbreak...,https://www.bbc.com/news/articles/cq6pz60p996o...
58,36,2026-05-18-17-41-00 +0000,wsj,Justice Department Drops Criminal Case Against...,https://www.wsj.com/us-news/law/gautam-adani-f...
44,34,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
242,34,2026-05-18-00-49-25 +0000,bbc,Moment two fighter jets collide mid-air at US ...,https://www.bbc.com/news/videos/ce8pzkg7klgo?a...
81,34,2026-05-18-16-40-26 +0000,nypost,Carl’s Jr. crushed by California’s high minimu...,https://nypost.com/2026/05/18/business/carls-j...
160,32,2026-05-18-11-46-14 +0000,nypost,"Ex-CIA chief, Defense Secretary Robert Gates p...",https://nypost.com/2026/05/18/world-news/ex-ci...
131,32,2026-05-18-14-29-11 +0000,nypost,American tourists arrested after breaking into...,https://nypost.com/2026/05/18/world-news/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)