## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-01-19-51-00 +0000,wsj,Oil Prices Push Global Bond Market Closer to t...,https://www.wsj.com/finance/investing/oil-pric...
1,2026-09-01-19-50-10 +0000,missionlocal,S.F. Board of Appeals just voted to save a 25-...,https://missionlocal.org/2026/09/sf-board-of-a...
2,2026-09-01-19-50-05 +0000,startribune,Iranian official says two people were killed w...,https://www.startribune.com/us-military-says-i...
3,2026-09-01-19-50-05 +0000,bbc,US launches more strikes on Iran as state medi...,https://www.bbc.co.uk/news/articles/cj06q4ynpm...
4,2026-09-01-19-47-32 +0000,nyt,Canada’s Carney Ties Resuming Trade Talks to T...,https://www.nytimes.com/2026/09/01/world/canad...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2533/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
42        trump     46
145         new     25
32         iran     22
177  california     18
27        house     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
418,2026-08-31-20-30-24 +0000,chitri,President Trump has asked Apple to change Lake...,https://www.chicagotribune.com/2026/08/31/trum...,121
338,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...,116
308,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...,113
373,2026-08-31-22-23-00 +0000,wsj,Army Secretary Dan Driscoll has submitted his ...,https://www.wsj.com/politics/national-security...,112
416,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
418,121,2026-08-31-20-30-24 +0000,chitri,President Trump has asked Apple to change Lake...,https://www.chicagotribune.com/2026/08/31/trum...
274,79,2026-09-01-08-25-50 +0000,wsj,Stock Market Today: Oil Surges After New Middl...,https://www.wsj.com/livecoverage/stock-market-...
58,79,2026-09-01-18-11-26 +0000,nypost,California dad raped 14-year-old daughter befo...,https://nypost.com/2026/09/01/us-news/californ...
35,71,2026-09-01-18-51-00 +0000,wsj,A Fed governor says the central bank should ac...,https://www.wsj.com/economy/central-banking/a-...
87,65,2026-09-01-17-19-49 +0000,nypost,Will Lindsay Clancy trial end in a mistrial? H...,https://nypost.com/2026/09/01/us-news/will-lin...
354,61,2026-08-31-23-17-46 +0000,wapo,Supreme Court clears way for White House ballr...,https://www.washingtonpost.com/politics/2026/0...
431,58,2026-08-31-20-11-10 +0000,nyt,"Summit With Russia, India and Iran Shows Lever...",https://www.nytimes.com/2026/08/31/world/asia/...
165,55,2026-09-01-14-21-00 +0000,wsj,Vice President JD Vance warned of ”growing sus...,https://www.wsj.com/politics/policy/three-take...
390,47,2026-08-31-21-58-00 +0000,wsj,The Mamdani administration faced sharp questio...,https://www.wsj.com/politics/policy/judge-pres...
248,47,2026-09-01-10-00-00 +0000,latimes,Reputed Latino gang member charged with killin...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)