## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-02-47-00 +0000,wsj,China Central Bank Warns on Imported Inflation...,https://www.wsj.com/economy/central-banking/ch...
1,2026-05-12-02-44-33 +0000,startribune,Live from Game 4: Parker Kelly’s goal gives Av...,https://www.startribune.com/live-minnesota-wil...
2,2026-05-12-02-29-24 +0000,nyt,"Sara Duterte, Philippine Vice President, Is Im...",https://www.nytimes.com/2026/05/11/world/asia/...
3,2026-05-12-02-27-47 +0000,startribune,Game 5 between Frost and Montreal Victoire pos...,https://www.startribune.com/minnesota-frost-mo...
4,2026-05-12-02-27-35 +0000,startribune,Scoggins: Timberwolves need Julius Randle to t...,https://www.startribune.com/julius-randle-minn...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
108       trump     41
102        iran     20
253         new     19
161  hantavirus     19
555         out     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,112
108,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,100
30,2026-05-12-00-43-00 +0000,wsj,The new battleship to be named after Trump wil...,https://www.wsj.com/politics/national-security...,98
11,2026-05-12-02-00-24 +0000,nyt,Iran War Updates: Long-Term Energy Crisis Loom...,https://www.nytimes.com/live/2026/05/11/world/...,96
109,2026-05-11-21-38-00 +0000,nyt,Nations Brace for Long-Term Economic Woes as T...,https://www.nytimes.com/2026/05/11/world/middl...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,112,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
207,71,2026-05-11-16-39-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
18,69,2026-05-12-01-39-11 +0000,bbc,What comes next for US and Canada passengers e...,https://www.bbc.com/news/articles/cn4pq1y1zjgo...
12,43,2026-05-12-02-00-00 +0000,wsj,An effort from Democrats to redraw maps in mor...,https://www.wsj.com/politics/elections/democra...
140,42,2026-05-11-20-30-20 +0000,nypost,Arcadia mayor Eileen Wang admits acting as Chi...,https://nypost.com/2026/05/11/us-news/eileen-w...
98,40,2026-05-11-22-06-21 +0000,nypost,Meta planning to take their Ray-Ban Display gl...,https://nypost.com/2026/05/11/business/ai-take...
46,39,2026-05-12-00-03-27 +0000,nypost,UAE launched secret counter-strike against Ira...,https://nypost.com/2026/05/11/world-news/uae-l...
30,38,2026-05-12-00-43-00 +0000,wsj,The new battleship to be named after Trump wil...,https://www.wsj.com/politics/national-security...
209,37,2026-05-11-16-34-44 +0000,nypost,Elon Musk to join Trump in China for high-stak...,https://nypost.com/2026/05/11/us-news/elon-mus...
320,36,2026-05-11-07-53-53 +0000,bbc,BBC tests out England and Argentina's World Cu...,https://www.bbc.com/news/videos/clypw107dqzo?a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)