## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-12-22-58-19 +0000,nypost,Horror as California Eagle Scout dies after be...,https://nypost.com/2026/03/12/us-news/californ...
1,2026-03-12-22-51-16 +0000,nyt,Ukraine to Make Drone Videos Available for Tra...,https://www.nytimes.com/2026/03/12/world/europ...
2,2026-03-12-22-50-52 +0000,nyt,Florida Republicans Pass Bill Requiring Proof ...,https://www.nytimes.com/2026/03/12/us/election...
3,2026-03-12-22-50-24 +0000,nypost,US refueling aircraft crashes in Iraq after in...,https://nypost.com/2026/03/12/us-news/us-refue...
4,2026-03-12-22-48-47 +0000,nyt,Trump Tempers María Corina Machado’s Political...,https://www.nytimes.com/2026/03/12/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
66   iran     61
33  trump     38
67    war     36
73    oil     34
79    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-03-12-22-42-12 +0000,nyt,Iran War Live Updates: U.S. Officials Say Iran...,https://www.nytimes.com/live/2026/03/12/world/...,206
167,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...,195
72,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,168
361,2026-03-12-01-39-01 +0000,wapo,Nations agree to release oil reserves as war i...,https://www.washingtonpost.com/world/2026/03/1...,159
229,2026-03-12-13-57-56 +0000,bbc,How Iran war laid bare the world's reliance on...,https://www.bbc.com/news/articles/c15x1y8d37vo...,154

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,206,2026-03-12-22-42-12 +0000,nyt,Iran War Live Updates: U.S. Officials Say Iran...,https://www.nytimes.com/live/2026/03/12/world/...
389,92,2026-03-11-23-25-00 +0000,wsj,Trump heaped scorn on longtime GOP nemesis Rep...,https://www.wsj.com/politics/policy/trump-bash...
235,84,2026-03-12-13-30-37 +0000,nypost,Iran’s new impotent Supreme Leader Mojtaba Kha...,https://nypost.com/2026/03/12/world-news/irans...
267,56,2026-03-12-11-04-30 +0000,nypost,Oil prices surge above $100 per barrel as seve...,https://nypost.com/2026/03/12/world-news/oil-p...
355,52,2026-03-12-02-38-00 +0000,wsj,"In a matter of hours, the White House changed ...",https://www.wsj.com/business/energy-oil/presid...
392,51,2026-03-11-23-17-29 +0000,nyt,Newsom Sees No Imminent Threat After F.B.I. Wa...,https://www.nytimes.com/2026/03/11/world/middl...
127,47,2026-03-12-19-20-20 +0000,cbc,Israeli military drops charges against soldier...,https://www.cbc.ca/news/world/israel-drops-cha...
83,46,2026-03-12-21-05-49 +0000,nypost,Scott Bessent meeting China’s vice premier in ...,https://nypost.com/2026/03/12/us-news/scott-be...
226,42,2026-03-12-14-02-55 +0000,bbc,Iran steps up attacks on energy targets as tan...,https://www.bbc.com/news/articles/c743gpd9z72o...
61,40,2026-03-12-21-28-41 +0000,nypost,"Wild video shows Long Island man bite cop, cal...",https://nypost.com/2026/03/12/us-news/long-isl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)