## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-23-22-10-24 +0000,bbc,Trump says Iran deal 'largely negotiated' incl...,https://www.bbc.com/news/articles/crmp121z3z8o...
1,2026-05-23-22-07-00 +0000,wsj,California Braces for Toxic Chemical Leak,https://www.wsj.com/us-news/california-braces-...
2,2026-05-23-22-05-35 +0000,nyt,A Lull in Fighting Gave Time to Bury Their Dead,https://www.nytimes.com/2026/05/23/world/europ...
3,2026-05-23-21-49-01 +0000,nypost,Cuba warns US it has ‘full and exclusive sover...,https://nypost.com/2026/05/23/world-news/cuba-...
4,2026-05-23-21-44-49 +0000,nypost,First nonstop flight from California to legend...,https://nypost.com/2026/05/23/us-news/first-no...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2659/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
0        trump     28
1         iran     15
12    chemical     11
190      ebola     11
106  explosion      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...,91
87,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,87
44,2026-05-23-18-09-12 +0000,nypost,Iran war agreement being ‘fine-tuned’ as Trump...,https://nypost.com/2026/05/23/world-news/iran-...,80
0,2026-05-23-22-10-24 +0000,bbc,Trump says Iran deal 'largely negotiated' incl...,https://www.bbc.com/news/articles/crmp121z3z8o...,70
11,2026-05-23-21-04-14 +0000,nypost,Trump says Iran agreement ‘largely negotiated’...,https://nypost.com/2026/05/23/us-news/trump-sa...,69

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,91,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...
23,47,2026-05-23-20-07-01 +0000,bbc,California declares state of emergency as fire...,https://www.bbc.com/news/articles/c3w2l249j8go...
14,46,2026-05-23-20-45-31 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
113,38,2026-05-23-11-46-38 +0000,nypost,Dead Maldives divers were just minutes away fr...,https://nypost.com/2026/05/23/world-news/maldi...
207,37,2026-05-22-22-47-45 +0000,cbc,911 audio reveals NASCAR's Kyle Busch was shor...,https://www.cbc.ca/sports/kyle-busch-death-fol...
171,34,2026-05-23-01-35-27 +0000,nyt,Mob Burns Congo Ebola Center Amid Rare Strain ...,https://www.nytimes.com/2026/05/22/world/afric...
85,31,2026-05-23-15-00-47 +0000,nypost,Hakeem Jeffries’ re-election bid boosted by ‘s...,https://nypost.com/2026/05/23/us-news/hakeem-j...
87,31,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...
42,27,2026-05-23-18-20-02 +0000,nypost,Protester pulls knife on Tom Steyer staffer at...,https://nypost.com/2026/05/23/us-news/proteste...
48,26,2026-05-23-17-49-31 +0000,nypost,Jersey Shore beach roped off to protect nestin...,https://nypost.com/2026/05/23/us-news/large-st...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)