## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-12-57-07 +0000,nyt,AfD’s Far Right Win Puts New Pressure on Germa...,https://www.nytimes.com/2026/09/08/world/europ...
1,2026-09-08-12-50-00 +0000,wsj,"U.S Stock Futures, Treasurys Weaken as Brent A...",https://www.wsj.com/finance/commodities-future...
2,2026-09-08-12-50-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
3,2026-09-08-12-50-00 +0000,wsj,"NextEra Energy, DOE Close on $1.9 Billion Loan...",https://www.wsj.com/business/energy-oil/nexter...
4,2026-09-08-12-49-14 +0000,nyt,UK Imposes Sanctions on Israeli Settlements in...,https://www.nytimes.com/2026/09/08/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5      new     24
81   trump     22
110  trade     13
693  plane     12
43     oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
246,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...,122
311,2026-09-07-13-26-01 +0000,nyt,Trump Posts Map Suggesting New Mexico Be Renam...,https://www.nytimes.com/2026/09/07/us/politics...,87
40,2026-09-08-11-27-19 +0000,cbc,Trump trade rep says U.S. may impose more tari...,https://www.cbc.ca/news/livestory/canada-u-s-r...,74
165,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...,72
145,2026-09-08-06-56-41 +0000,nyt,"Canada Imposes New Tariffs on U.S. Goods, as T...",https://www.nytimes.com/2026/09/08/business/ca...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
246,122,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
282,60,2026-09-07-15-15-14 +0000,chitri,Fuel prices at record Labor Day high in US tha...,https://www.chicagotribune.com/2026/09/07/fuel...
102,53,2026-09-08-09-31-26 +0000,bbc,Five killed in Miami plane crash were in two v...,https://www.bbc.co.uk/news/articles/ce8e32n8ep...
79,52,2026-09-08-10-00-00 +0000,nypost,Pete Davidson was a kid when he lost his dad o...,https://nypost.com/2026/09/08/entertainment/pe...
40,52,2026-09-08-11-27-19 +0000,cbc,Trump trade rep says U.S. may impose more tari...,https://www.cbc.ca/news/livestory/canada-u-s-r...
285,45,2026-09-07-15-03-22 +0000,chitri,AfD party’s landslide win in eastern Germany t...,https://www.chicagotribune.com/2026/09/07/afd-...
108,43,2026-09-08-09-10-00 +0000,wsj,Oil Nears $100 a Barrel as Fresh Attacks on Sa...,https://www.wsj.com/world/middle-east/oil-near...
269,42,2026-09-07-16-20-04 +0000,chitri,King Charles clarifies status of Prince Harry ...,https://www.chicagotribune.com/2026/09/07/king...
26,39,2026-09-08-12-01-07 +0000,startribune,Minnesota closed three addiction treatment cen...,https://www.startribune.com/mn-addiction-treat...
204,36,2026-09-07-21-59-12 +0000,nypost,Mainstream TV vague about airing first-ever GO...,https://nypost.com/2026/09/07/us-news/tv-netwo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)