## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-07-30-00 +0000,wsj,Spanish Inflation Rises Further as Iran War Dr...,https://www.wsj.com/economy/central-banking/sp...
1,2026-04-29-07-29-00 +0000,wsj,Oil Rises on Fears of Prolonged Hormuz Blockade,https://www.wsj.com/finance/commodities-future...
2,2026-04-29-07-26-00 +0000,wsj,Gold’s Underlying Demand Remains Intact Amid B...,https://www.wsj.com/finance/commodities-future...
3,2026-04-29-07-25-07 +0000,nyt,Full Guest List for Trump’s State Dinner With ...,https://www.nytimes.com/2026/04/28/us/politics...
4,2026-04-29-07-24-00 +0000,wsj,Finland’s Kone to Buy German Rival TK Elevator...,https://www.wsj.com/business/deals/finlands-ko...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2642/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
27    trump     57
66     king     26
4      iran     23
29  charles     20
69      new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...,202
74,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...,162
295,2026-04-28-16-27-08 +0000,nypost,President Trump gives first lady Melania a pla...,https://nypost.com/2026/04/28/us-news/presiden...,145
405,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,141
78,2026-04-29-01-22-32 +0000,bbc,In pictures: King joins Trump for White House ...,https://www.bbc.com/news/articles/c86e6z26xdpo...,132

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,202,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...
342,116,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
379,68,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...
127,54,2026-04-28-22-05-30 +0000,nypost,Musk kicks off explosive OpenAI trial by slamm...,https://nypost.com/2026/04/28/business/musk-ki...
221,50,2026-04-28-19-10-36 +0000,nypost,Trump’s State Dept. will include president’s f...,https://nypost.com/2026/04/28/us-news/trumps-s...
253,49,2026-04-28-18-07-51 +0000,nypost,Ex-FBI Director James Comey indicted for threa...,https://nypost.com/2026/04/28/us-news/justice-...
72,48,2026-04-29-02-00-00 +0000,wsj,War has imposed a heavy cost on Iran’s economy...,https://www.wsj.com/world/middle-east/iranians...
240,44,2026-04-28-18-37-44 +0000,nypost,Indian villager digs up sister’s corpse and ca...,https://nypost.com/2026/04/28/world-news/india...
233,41,2026-04-28-18-49-33 +0000,cbc,U.S. special forces soldier pleads not guilty ...,https://www.cbc.ca/news/world/polymarket-us-so...
16,40,2026-04-29-06-34-38 +0000,nypost,Kevin O’Leary calls Mamdani’s NYC tax plan ‘sh...,https://nypost.com/2026/04/29/us-news/kevin-ol...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)