## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-26-01-17-35 +0000,startribune,Live from Game 4: Timberwolves’ Donte DiVincen...,https://www.startribune.com/minnesota-timberwo...
1,2026-04-26-01-16-00 +0000,wsj,President Trump was evacuated from the White H...,https://www.wsj.com/us-news/trump-evacuated-wh...
2,2026-04-26-01-14-05 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/25/us/tru...
3,2026-04-26-01-13-22 +0000,startribune,Live from Game 4: Matt Boldy scores in overtim...,https://www.startribune.com/minnesota-wild-dal...
4,2026-04-26-01-07-47 +0000,nyt,Trump Fires Board Members of Group That Overse...,https://www.nytimes.com/2026/04/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2500/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     25
98    iran     18
108  talks     11
99     war     10
14   house     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-04-26-00-33-41 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...,96
59,2026-04-25-19-57-12 +0000,wapo,"Trump calls off Witkoff, Kushner trip to Pakis...",https://www.washingtonpost.com/world/2026/04/2...,82
42,2026-04-25-21-34-12 +0000,bbc,Trump cancels US envoys' trip to Pakistan for ...,https://www.bbc.com/news/articles/c4g6nyvl29po...,81
1,2026-04-26-01-16-00 +0000,wsj,President Trump was evacuated from the White H...,https://www.wsj.com/us-news/trump-evacuated-wh...,77
93,2026-04-25-16-09-47 +0000,nypost,Trump cancels US delegation’s Pakistan trip as...,https://nypost.com/2026/04/25/world-news/trump...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,96,2026-04-26-00-33-41 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...
1,52,2026-04-26-01-16-00 +0000,wsj,President Trump was evacuated from the White H...,https://www.wsj.com/us-news/trump-evacuated-wh...
43,42,2026-04-25-21-31-01 +0000,nypost,Wild bodycam footage shows California cop’s li...,https://nypost.com/2026/04/25/us-news/antioch-...
21,35,2026-04-25-23-24-57 +0000,nyt,Al Qaeda-Linked Militants Launch Major Attacks...,https://www.nytimes.com/2026/04/25/world/afric...
15,30,2026-04-26-00-06-02 +0000,startribune,North Dakota state legislator one of two kille...,https://www.startribune.com/small-plane-crashe...
152,25,2026-04-25-05-25-54 +0000,nypost,Florida Dem Sheila Cherfilus-McCormick filed f...,https://nypost.com/2026/04/25/us-news/florida-...
53,23,2026-04-25-21-05-32 +0000,nypost,Jihadist ex-Columbia prof on vile college tour...,https://nypost.com/2026/04/25/us-news/jihadist...
120,23,2026-04-25-11-00-03 +0000,wapo,Lionel Rosenblatt is dead at 82. He defied his...,https://www.washingtonpost.com/obituaries/2026...
46,23,2026-04-25-21-14-06 +0000,nypost,Opportunist or socialist? Mamdani-backed NYC C...,https://nypost.com/2026/04/25/us-news/mamdani-...
0,22,2026-04-26-01-17-35 +0000,startribune,Live from Game 4: Timberwolves’ Donte DiVincen...,https://www.startribune.com/minnesota-timberwo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)