## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-12-22-08-07 +0000,bbc,US senator and close Trump ally Lindsey Graham...,https://www.bbc.co.uk/news/articles/cvgj25j6nm...
1,2026-07-12-22-07-26 +0000,nyt,Leaders From Home and Abroad Remember Senator ...,https://www.nytimes.com/2026/07/12/us/politics...
2,2026-07-12-22-06-19 +0000,nyt,Graham’s Death Highlights Congress’s Age Issue,https://www.nytimes.com/2026/07/12/us/politics...
3,2026-07-12-22-06-05 +0000,nyt,Live Updates: Cease-Fire Unraveling as U.S. an...,https://www.nytimes.com/live/2026/07/12/us/ira...
4,2026-07-12-22-05-04 +0000,startribune,Sen. Lindsey Graham likely died after aorta ru...,https://www.startribune.com/us-senator-lindsey...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2622/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
5    graham     30
4   lindsey     28
2     trump     21
23     iran     16
13    death     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-07-12-14-10-02 +0000,nypost,Defiant Sen. Lindsey Graham laughed off Iran p...,https://nypost.com/2026/07/12/us-news/defiant-...,119
93,2026-07-12-15-58-00 +0000,wsj,"Longtime Republican Sen. Lindsey Graham dies, ...",https://www.wsj.com/articles/lindsey-graham-in...,118
46,2026-07-12-20-07-03 +0000,nypost,Lindsey Graham’s sudden death could hamstring ...,https://nypost.com/2026/07/12/us-news/lindsey-...,117
0,2026-07-12-22-08-07 +0000,bbc,US senator and close Trump ally Lindsey Graham...,https://www.bbc.co.uk/news/articles/cvgj25j6nm...,114
20,2026-07-12-21-18-00 +0000,wsj,Longtime Republican Sen. Lindsey Graham has di...,https://www.wsj.com/politics/lindsey-graham-re...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,119,2026-07-12-14-10-02 +0000,nypost,Defiant Sen. Lindsey Graham laughed off Iran p...,https://nypost.com/2026/07/12/us-news/defiant-...
179,60,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
93,48,2026-07-12-15-58-00 +0000,wsj,"Longtime Republican Sen. Lindsey Graham dies, ...",https://www.wsj.com/articles/lindsey-graham-in...
20,37,2026-07-12-21-18-00 +0000,wsj,Longtime Republican Sen. Lindsey Graham has di...,https://www.wsj.com/politics/lindsey-graham-re...
71,34,2026-07-12-17-52-00 +0000,wsj,U.S. and Iran Ramp Up Attacks in Fight Over St...,https://www.wsj.com/world/middle-east/u-s-laun...
30,29,2026-07-12-20-45-50 +0000,nypost,Moment NBA star Brandon Clarke is caught with ...,https://nypost.com/2026/07/12/sports/moment-nb...
89,28,2026-07-12-16-23-19 +0000,nypost,GOP gov candidate Bruce Blakeman compares NYC ...,https://nypost.com/2026/07/12/us-news/bruce-bl...
87,26,2026-07-12-16-35-50 +0000,bbc,Former Emir of Qatar Sheikh Hamad bin Khalifa ...,https://www.bbc.co.uk/news/articles/cql1qdq14x...
128,26,2026-07-12-09-30-00 +0000,wsj,The good news from the WSJ survey of economist...,https://www.wsj.com/economy/central-banking/wa...
154,25,2026-07-12-03-56-02 +0000,bbc,At least two killed in Toronto street festival...,https://www.bbc.co.uk/news/articles/ce3e66e1x3...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)