## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-21-12-53 +0000,nyt,"ICE Arrests Surge at Airports, Opening New Fro...",https://www.nytimes.com/2026/07/28/us/ice-arre...
1,2026-07-28-21-11-00 +0000,wsj,"Value Outperforms Growth This Year, Powered By...",https://www.wsj.com/finance/stocks/value-outpe...
2,2026-07-28-21-10-07 +0000,startribune,Tornado that carved a path of destruction in W...,https://www.startribune.com/tornado-that-carve...
3,2026-07-28-21-09-30 +0000,nyt,Houthis Claim Strike on Another Saudi Oil Tanker,https://www.nytimes.com/2026/07/28/world/middl...
4,2026-07-28-21-09-21 +0000,bbc,Bystander video shows teen lifeguard's dramati...,https://www.bbc.co.uk/news/videos/c4g3600xw5ko...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
91    trump     37
5       new     20
44     iran     16
211  graham     15
14       ai     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
269,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,108
42,2026-07-28-20-23-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,108
289,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...,96
172,2026-07-28-16-31-19 +0000,chitri,Donald Trump and Benjamin Netanyahu meet for t...,https://www.chicagotribune.com/2026/07/28/trum...,92
103,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
269,108,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...
42,71,2026-07-28-20-23-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
170,67,2026-07-28-16-32-23 +0000,nypost,Gavin Newsom responds to Ruby Rippey’s claims ...,https://nypost.com/2026/07/28/us-news/gavin-ne...
172,55,2026-07-28-16-31-19 +0000,chitri,Donald Trump and Benjamin Netanyahu meet for t...,https://www.chicagotribune.com/2026/07/28/trum...
44,49,2026-07-28-20-21-15 +0000,nypost,California couple flee monster wildfire in Fra...,https://nypost.com/2026/07/28/us-news/eaton-fi...
30,48,2026-07-28-20-43-16 +0000,startribune,Elon Musk’s AI company seeks to block Minnesot...,https://www.startribune.com/elon-musks-ai-comp...
135,42,2026-07-28-17-57-29 +0000,cbc,FIFA plan for Kushner-backed $20 billion US op...,https://www.cbc.ca/sports/soccer/fifa-ownershi...
329,39,2026-07-28-04-01-20 +0000,nyt,He Served China’s Police State of Xinjiang. He...,https://www.nytimes.com/2026/07/28/business/ch...
321,39,2026-07-28-05-45-29 +0000,wsj,"Stock Market Today: Dow Rallies, Chip Stocks S...",https://www.wsj.com/livecoverage/stock-market-...
360,38,2026-07-28-00-00-00 +0000,wsj,"Francesca Hong, a member of the Democratic Soc...",https://www.wsj.com/politics/elections/a-democ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)