## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-14-22-54-42 +0000,nypost,Arrest ordered for high-flying sports betting ...,https://nypost.com/2026/08/14/us-news/influenc...
1,2026-08-14-22-52-25 +0000,nypost,"Tesla plows into NJ home, ends up in the kitch...",https://nypost.com/2026/08/14/us-news/tesla-pl...
2,2026-08-14-22-52-23 +0000,nypost,Major road closed for $114M wildlife crossing ...,https://nypost.com/2026/08/14/us-news/agoura-r...
3,2026-08-14-22-44-21 +0000,nypost,Horrific video appears to show Las Vegas cop k...,https://nypost.com/2026/08/14/us-news/las-vega...
4,2026-08-14-22-43-39 +0000,nyt,A Silicon Valley Dirt Farmer Hangs Up His Shears,https://www.nytimes.com/2026/08/14/business/an...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2333/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
74    trump     40
109     new     19
385   court     14
708  farage     11
284     was     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
340,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...,125
137,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...,114
26,2026-08-14-21-47-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...,112
139,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...,111
47,2026-08-14-21-13-51 +0000,latimes,Trump says USS Abraham Lincoln deployment 'not...,https://www.latimes.com/politics/story/2026-08...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
340,125,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...
137,74,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...
284,71,2026-08-14-09-41-00 +0000,wsj,A new report led by White House trade adviser ...,https://www.wsj.com/economy/trade/white-house-...
185,56,2026-08-14-15-26-04 +0000,cbc,Luigi Mangione admits to shooting health insur...,https://www.cbc.ca/news/world/us-federal-heari...
34,53,2026-08-14-21-32-00 +0000,nypost,Family of dead ex-Cambridge professor Jason Ar...,https://nypost.com/2026/08/14/world-news/famil...
139,49,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...
299,46,2026-08-14-08-51-39 +0000,cbc,Reform UK leader Nigel Farage beats Count Binf...,https://www.cbc.ca/news/world/uk-clacton-byele...
131,44,2026-08-14-18-14-02 +0000,wapo,"Retail sales tumble in July, their biggest dro...",https://www.washingtonpost.com/business/2026/0...
170,36,2026-08-14-16-25-00 +0000,wapo,Michigan’s marquee Senate race close in first ...,https://www.washingtonpost.com/politics/2026/0...
222,34,2026-08-14-13-00-00 +0000,wapo,American missionary kidnapped in Niger release...,https://www.washingtonpost.com/world/2026/08/1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)