## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-15-17-54-03 +0000,nyt,Canadian Petition to Expel U.S. Ambassador Pet...,https://www.nytimes.com/2026/08/15/world/canad...
1,2026-08-15-17-51-45 +0000,nypost,New Iranian billboard depicts dead US soldier ...,https://nypost.com/2026/08/15/world-news/irani...
2,2026-08-15-17-47-42 +0000,bbc,Firefighters battle wildfire tearing through B...,https://www.bbc.co.uk/news/articles/cp8eex1nmp...
3,2026-08-15-17-45-00 +0000,wsj,Why Buy It When You Can Print It? A DIY Nation...,https://www.wsj.com/style/design/why-buy-it-wh...
4,2026-08-15-17-42-36 +0000,bbc,Multiple suspects at large after five shot at ...,https://www.bbc.co.uk/news/articles/c0l5583903...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2477/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
74   trump     35
8      new     17
12    dead     10
76    iran      9
89  family      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
174,2026-08-14-21-47-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...,86
227,2026-08-14-20-08-50 +0000,nypost,Trump says he’ll declare Strait of Hormuz a US...,https://nypost.com/2026/08/14/us-news/trump-sa...,80
192,2026-08-14-21-13-51 +0000,latimes,Trump says USS Abraham Lincoln deployment 'not...,https://www.latimes.com/politics/story/2026-08...,79
199,2026-08-14-21-05-56 +0000,chitri,Trump says record-setting Navy deployment to s...,https://www.chicagotribune.com/2026/08/14/trum...,72
245,2026-08-14-19-19-15 +0000,wapo,Trump dismisses families’ concerns about USS A...,https://www.washingtonpost.com/politics/2026/0...,69

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
174,86,2026-08-14-21-47-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...
181,67,2026-08-14-21-32-00 +0000,nypost,Family of dead ex-Cambridge professor Jason Ar...,https://nypost.com/2026/08/14/world-news/famil...
164,44,2026-08-14-22-13-32 +0000,nypost,New York Mag fires Mamdani-loving writer Ross ...,https://nypost.com/2026/08/14/media/new-york-m...
61,38,2026-08-15-12-00-00 +0000,nypost,‘Iran’s black widow’ faces multiple death sent...,https://nypost.com/2026/08/15/us-news/irans-bl...
18,37,2026-08-15-16-41-12 +0000,nypost,Terrifying moment deranged driver tries to run...,https://nypost.com/2026/08/15/us-news/la-drive...
209,35,2026-08-14-20-53-00 +0000,wapo,"Mangione admits to shooting insurance CEO, ple...",https://www.washingtonpost.com/nation/2026/08/...
30,29,2026-08-15-15-44-40 +0000,nypost,Trump posts AI image of himself seizing Irania...,https://nypost.com/2026/08/15/us-news/trump-po...
7,28,2026-08-15-17-28-51 +0000,nypost,SoCal leaders weigh extreme measures after tee...,https://nypost.com/2026/08/15/us-news/la-jolla...
182,28,2026-08-14-21-30-06 +0000,chitri,Palestinians besieged in West Bank village fea...,https://www.chicagotribune.com/2026/08/14/isra...
141,27,2026-08-14-23-44-21 +0000,nypost,Tsunami warning issued after massive 7.7-magni...,https://nypost.com/2026/08/14/world-news/tsuna...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)