## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-21-51-52 +0000,nypost,California highway renamed for Hollywood icon ...,https://nypost.com/2026/10/03/us-news/californ...
1,2026-10-03-21-49-45 +0000,nypost,"Democrats hit 50% or more in Texas, Alaska pol...",https://nypost.com/2026/10/03/us-news/democrat...
2,2026-10-03-21-43-02 +0000,startribune,"Live: After season-opening win, Wild take on B...",https://www.startribune.com/minnesota-wild-bos...
3,2026-10-03-21-41-46 +0000,nyt,Search Underway for Missing Plane Heading From...,https://www.nytimes.com/2026/10/03/us/medical-...
4,2026-10-03-21-41-12 +0000,nypost,Couple tied the knot in ‘golden moment’ ceremo...,https://nypost.com/2026/10/03/us-news/couple-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
295       trump     27
280    flydubai     15
0    california     11
292   execution     10
443         was      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
213,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...,74
120,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...,74
72,2026-10-03-16-50-36 +0000,nypost,Trump gushes over blue-collar flydubai hero wh...,https://nypost.com/2026/10/03/us-news/trump-gu...,63
95,2026-10-03-14-52-27 +0000,nyt,FlyDubai Co-Pilot Used Crash Ax in ‘Terrorist’...,https://www.nytimes.com/2026/10/03/world/middl...,59
203,2026-10-03-00-59-50 +0000,chitri,FlyDubai co-pilot who nearly crashed plane was...,https://www.chicagotribune.com/2026/10/02/flyd...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
213,74,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...
41,57,2026-10-03-19-34-43 +0000,nypost,Trump’s attempted assassin sent mysterious tex...,https://nypost.com/2026/10/03/us-news/trumps-a...
63,53,2026-10-03-17-48-42 +0000,bbc,Tennessee prison chief to resign after Christa...,https://www.bbc.co.uk/news/articles/c8zxl62yzx...
32,48,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...
46,33,2026-10-03-19-16-40 +0000,nypost,Russia pushes fake AI-generated images claimin...,https://nypost.com/2026/10/03/world-news/kyiv-...
49,32,2026-10-03-18-59-11 +0000,nypost,California school board erupts over sinister d...,https://nypost.com/2026/10/03/us-news/temecula...
128,31,2026-10-03-10-27-57 +0000,bbc,Kemi Badenoch has cemented her image. Now she ...,https://www.bbc.co.uk/news/articles/cmn8e88771...
120,31,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...
16,26,2026-10-03-21-11-50 +0000,nypost,Al Qaeda calls for copycats to target US citiz...,https://nypost.com/2026/10/03/world-news/al-qa...
54,26,2026-10-03-18-39-43 +0000,nypost,Michael McDonald’s long-lost son reveals heart...,https://nypost.com/2026/10/03/entertainment/mi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)