## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-02-00-11-28 +0000,nyt,Explosions Rock Kyiv,https://www.nytimes.com/2026/07/01/world/europ...
1,2026-07-02-00-06-00 +0000,wsj,South Korea Inflation Accelerates to 30-Month ...,https://www.wsj.com/economy/south-korea-inflat...
2,2026-07-02-00-04-47 +0000,missionlocal,S.F. hopes to expand RESET center if pilot pro...,https://missionlocal.org/2026/07/s-f-open-to-e...
3,2026-07-02-00-04-38 +0000,nyt,Nine Arrested in Federal Crackdown on L.A.’s S...,https://www.nytimes.com/2026/07/01/us/los-ange...
4,2026-07-02-00-00-53 +0000,cbc,Soccer fans file class-action lawsuit against ...,https://www.cbc.ca/news/world/stubhub-cancelle...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
50     trump     49
35     world     17
300       ai     14
190  billion     14
255     year     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,117
29,2026-07-01-23-08-00 +0000,wsj,Crypto Bets and Real Estate Deals: Inside Trum...,https://www.wsj.com/finance/trump-investments-...,99
49,2026-07-01-22-17-27 +0000,nypost,Inside the new Air Force One: Trump’s Qatari j...,https://nypost.com/2026/07/01/us-news/inside-t...,99
66,2026-07-01-21-33-43 +0000,nypost,Trump gets ‘fantastic’ advice from AI-powered ...,https://nypost.com/2026/07/01/us-news/trump-ge...,97
163,2026-07-01-17-27-05 +0000,nypost,Trump won’t renew USMCA deal with Canada and M...,https://nypost.com/2026/07/01/us-news/trump-wo...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,117,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
286,64,2026-07-01-10-49-02 +0000,nypost,Dog missing for month in Mexico found partying...,https://nypost.com/2026/07/01/world-news/dog-m...
306,60,2026-07-01-09-30-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
79,55,2026-07-01-21-05-04 +0000,nypost,Iran war drives wedge between US and Saudi Ara...,https://nypost.com/2026/07/01/world-news/iran-...
153,46,2026-07-01-17-58-05 +0000,nypost,"Kamala Harris reaches out to Mamdani, anti-Isr...",https://nypost.com/2026/07/01/us-news/kamala-h...
358,42,2026-07-01-02-00-00 +0000,wsj,The Supreme Court has wrapped up one of its mo...,https://www.wsj.com/politics/policy/how-suprem...
325,41,2026-07-01-07-18-26 +0000,bbc,Chris Mason: Starmer's defence plan leaves cru...,https://www.bbc.co.uk/news/articles/c3vy7z35ve...
131,41,2026-07-01-18-54-00 +0000,wsj,Kevin Warsh declined to say how the Fed will a...,https://www.wsj.com/economy/central-banking/in...
203,38,2026-07-01-15-54-01 +0000,nypost,Child sex offender drops outrageous claim afte...,https://nypost.com/2026/07/01/us-news/register...
166,37,2026-07-01-17-24-00 +0000,wsj,We asked five experts across the political spe...,https://www.wsj.com/us-news/law/us-constitutio...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)