## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-11-19-16-52 +0000,cbc,Census day arrives Tuesday. Have you submitted...,https://www.cbc.ca/news/politics/census-day-ma...
1,2026-05-11-19-16-42 +0000,nypost,Nancy Pelosi breaks silence on SF race to repl...,https://nypost.com/2026/05/11/us-news/nancy-pe...
2,2026-05-11-19-15-54 +0000,bbc,PM under pressure as aides quit and MPs call f...,https://www.bbc.com/news/articles/c7v9r38d24do...
3,2026-05-11-19-12-58 +0000,nypost,Motorcycle flies onto traffic light pole after...,https://nypost.com/2026/05/11/world-news/canad...
4,2026-05-11-19-11-15 +0000,nypost,"Southern California oil rig catches fire, work...",https://nypost.com/2026/05/11/us-news/southern...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
92        trump     39
84         iran     21
53   hantavirus     19
85          war     15
384      market     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
32,2026-05-11-18-27-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,118
9,2026-05-11-19-02-56 +0000,nyt,Iran War Live Updates: Long-Term Energy Crisis...,https://www.nytimes.com/live/2026/05/11/world/...,102
46,2026-05-11-17-55-01 +0000,startribune,Trump says Iran ceasefire is on 'life support'...,https://www.startribune.com/iran-and-the-us-ar...,96
241,2026-05-11-01-55-13 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,90
98,2026-05-11-16-10-02 +0000,nypost,Trump says Iran cease-fire ‘on massive life su...,https://nypost.com/2026/05/11/us-news/trump-sa...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
32,118,2026-05-11-18-27-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
49,68,2026-05-11-17-45-07 +0000,nypost,3 New Yorkers among 17 Americans evacuated fro...,https://nypost.com/2026/05/11/us-news/3-new-yo...
77,54,2026-05-11-16-39-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
240,43,2026-05-11-02-00-00 +0000,wsj,Women are playing a bigger role in the America...,https://www.wsj.com/economy/jobs/jobs-men-empl...
79,42,2026-05-11-16-34-44 +0000,nypost,Elon Musk to join Trump in China for high-stak...,https://nypost.com/2026/05/11/us-news/elon-mus...
23,41,2026-05-11-18-43-51 +0000,latimes,Oil rig off Southern California coast catches ...,https://www.latimes.com/california/story/2026-...
42,37,2026-05-11-18-03-29 +0000,nypost,Insane ‘turf war’ brawl breaks out between fem...,https://nypost.com/2026/05/11/us-news/insane-t...
251,29,2026-05-11-00-35-41 +0000,latimes,'Extremely scary': Specter of an all-GOP gover...,https://www.latimes.com/politics/story/2026-05...
46,29,2026-05-11-17-55-01 +0000,startribune,Trump says Iran ceasefire is on 'life support'...,https://www.startribune.com/iran-and-the-us-ar...
163,29,2026-05-11-12-59-03 +0000,nypost,Heart-stopping video shows toddler fall from 4...,https://nypost.com/2026/05/11/world-news/toddl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)