## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-13-17-50-06 +0000,nypost,California parents demand cameras in special e...,https://nypost.com/2026/09/13/us-news/californ...
1,2026-09-13-17-48-00 +0000,wsj,Opinion | Awarding Courage and Honesty in Acad...,https://www.wsj.com/opinion/awarding-courage-a...
2,2026-09-13-17-47-00 +0000,wsj,Opinion | Nonprofits Rely on Wealth From Free ...,https://www.wsj.com/opinion/nonprofits-rely-on...
3,2026-09-13-17-46-00 +0000,wsj,Opinion | Aluminum Tariffs Spur Domestic Inves...,https://www.wsj.com/opinion/aluminum-tariffs-s...
4,2026-09-13-17-45-00 +0000,wsj,Opinion | More Credentialed Teachers Don’t Mea...,https://www.wsj.com/opinion/more-credentialed-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2295/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
37   trump     25
275    new     12
199     ai     10
90    iran      9
536    out      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,80
59,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...,68
44,2026-09-13-15-31-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...,68
6,2026-09-13-17-41-22 +0000,chitri,President Donald Trump calls on Ukraine to hal...,https://www.chicagotribune.com/2026/09/13/trum...,61
86,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,80,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
44,61,2026-09-13-15-31-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
62,41,2026-09-13-13-55-08 +0000,nypost,Speaker Johnson says AI leaders must meet with...,https://nypost.com/2026/09/13/us-news/speaker-...
183,40,2026-09-12-20-51-49 +0000,nypost,Lindsay Clancy case eerily similar to bipolar ...,https://nypost.com/2026/09/12/us-news/lindsay-...
86,33,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...
89,31,2026-09-13-10-36-25 +0000,wapo,"Six dead, over 100 missing after Indonesian pa...",https://www.washingtonpost.com/world/2026/09/1...
6,29,2026-09-13-17-41-22 +0000,chitri,President Donald Trump calls on Ukraine to hal...,https://www.chicagotribune.com/2026/09/13/trum...
132,27,2026-09-13-08-00-00 +0000,cbc,Canada's oil windfall may yet wipe out its los...,https://www.cbc.ca/news/politics/canada-oil-pr...
190,26,2026-09-12-20-07-48 +0000,chitri,Saudi Arabia has few options as it faces mount...,https://www.chicagotribune.com/2026/09/12/saud...
104,25,2026-09-13-10-00-00 +0000,latimes,California prison towns grasp for new jobs aft...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)