## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-29-19-51-40 +0000,nypost,News of the World: What you missed this week i...,https://nypost.com/2026/08/29/world-news/news-...
1,2026-08-29-19-50-52 +0000,nyt,Nepal Rescuers Bore Through Tunnels to Reach 9...,https://www.nytimes.com/2026/08/29/world/asia/...
2,2026-08-29-19-49-54 +0000,nyt,Thieves Smash Museum Case for Diamond Necklace...,https://www.nytimes.com/2026/08/29/world/europ...
3,2026-08-29-19-44-54 +0000,bbc,Former Ecuadorian president imprisoned for cor...,https://www.bbc.co.uk/news/articles/cvgym9rz07...
4,2026-08-29-19-37-49 +0000,nypost,West Hollywood lesbian bar SweetWater cancels ...,https://nypost.com/2026/08/29/us-news/west-hol...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2311/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
203       trump     38
5         nepal     18
38        china     11
115         new     11
108  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
212,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...,98
150,2026-08-29-07-11-04 +0000,bbc,Ex-White House teleprompter operator ordered t...,https://www.bbc.co.uk/news/articles/c4gj2dl4x5...,72
25,2026-08-29-18-35-56 +0000,chitri,Noncitizen voting claims animate President Tru...,https://www.chicagotribune.com/2026/08/29/nonc...,69
189,2026-08-28-23-31-03 +0000,cbc,Trump says U.S. makes deal to control 65 billi...,https://www.cbc.ca/news/world/trump-venezuela-...,67
59,2026-08-29-16-53-10 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
212,98,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...
66,61,2026-08-29-16-02-52 +0000,chitri,Nepal-China flood survivors reach safe areas a...,https://www.chicagotribune.com/2026/08/29/nepa...
215,57,2026-08-28-21-43-00 +0000,wsj,Fed Chairman Kevin Warsh spoke today and the o...,https://www.wsj.com/economy/warsh-speaks-and-r...
58,41,2026-08-29-16-53-44 +0000,nypost,‘Illegal alien’ Milo Yiannopoulos kicked out o...,https://nypost.com/2026/08/29/us-news/milo-yia...
111,37,2026-08-29-10-12-15 +0000,chitri,New Oak Park police station plan hits ‘substan...,https://www.chicagotribune.com/2026/08/29/new-...
160,37,2026-08-29-02-15-00 +0000,wsj,The White House teleprompter operator under in...,https://www.wsj.com/politics/policy/white-hous...
31,36,2026-08-29-18-20-32 +0000,nyt,"For LGBTQ Fans, Dolly Parton Inspired Their Wi...",https://www.nytimes.com/2026/08/29/us/dolly-pa...
171,33,2026-08-29-01-00-00 +0000,wsj,The U.S. has rushed so many munitions to the M...,https://www.wsj.com/politics/national-security...
127,33,2026-08-29-09-30-00 +0000,wsj,Scientists monitoring data from satellites and...,https://www.wsj.com/economy/global/the-stronge...
26,30,2026-08-29-18-33-03 +0000,nypost,135 wild animals seized from cartel zoo as Mex...,https://nypost.com/2026/08/29/world-news/mexic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)