## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-21-07-06-10 +0000,bbc,Chris Mason: Jackdaw approved but tricky energ...,https://www.bbc.co.uk/news/articles/cked35dz47...
1,2026-10-21-06-56-00 +0000,wsj,U.K. Inflation Jumps Again on Rising Energy Costs,https://www.wsj.com/economy/central-banking/u-...
2,2026-10-21-06-55-45 +0000,nyt,The Mayor of a City in Haiti Warned of a Massa...,https://www.nytimes.com/2026/10/20/world/ameri...
3,2026-10-21-06-53-25 +0000,bbc,Surging fuel prices push UK inflation rate to ...,https://www.bbc.co.uk/news/articles/c6gel2xv44...
4,2026-10-21-06-53-00 +0000,wsj,U.K. Government on Track to Cut Borrowing Ahea...,https://www.wsj.com/world/uk/uk-government-on-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2421/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
115       trump     43
76          new     21
47       france     14
309  california     13
143          ai     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
252,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...,106
60,2026-10-21-01-37-00 +0000,wsj,President Trump is relying on a new strategy t...,https://www.wsj.com/politics/elections/trump-m...,98
210,2026-10-20-19-40-00 +0000,wsj,Trump announced a new program that will pay pe...,https://www.wsj.com/politics/policy/trump-to-o...,98
363,2026-10-20-10-30-00 +0000,wsj,"Ex-officials from the Trump, Biden and Obama a...",https://www.wsj.com/politics/policy/u-s-risks-...,85
203,2026-10-20-19-59-36 +0000,cbc,Lawsuit challenging Trump's tariffs against Ca...,https://www.cbc.ca/news/world/trump-tariffs-la...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
252,106,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...
189,58,2026-10-20-20-30-32 +0000,chitri,New gunshot detection system debuting in six C...,https://www.chicagotribune.com/2026/10/20/chic...
232,57,2026-10-20-19-01-56 +0000,cbc,No Canada-U.S. trade deal expected before Amer...,https://www.cbc.ca/news/politics/carney-trump-...
334,55,2026-10-20-12-19-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
50,54,2026-10-21-02-29-05 +0000,nypost,Violent California rapist could be released in...,https://nypost.com/2026/10/20/us-news/santa-cr...
292,51,2026-10-20-15-20-11 +0000,nypost,UK will deploy Typhoon fighter jets to defend ...,https://nypost.com/2026/10/20/world-news/uk-wi...
134,50,2026-10-20-21-57-00 +0000,wsj,National Democrats are making a million-dollar...,https://www.wsj.com/politics/elections/democra...
371,48,2026-10-20-10-00-00 +0000,latimes,"SpaceX, Anthropic plan to share wealth with th...",https://www.latimes.com/business/story/2026-10...
193,47,2026-10-20-20-10-16 +0000,nypost,Woke French student mocked owners who lost sto...,https://nypost.com/2026/10/20/world-news/frenc...
105,40,2026-10-20-22-53-44 +0000,nypost,Elon Musk chose to throttle Ukraine’s access t...,https://nypost.com/2026/10/20/world-news/elon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)