## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-07-14-22-14 +0000,nypost,"Dow falls 300 points, oil jumps as Trump’s Ira...",https://nypost.com/2026/04/07/business/dow-fal...
1,2026-04-07-14-19-31 +0000,startribune,Joe Ryan steps up after 39-pitch inning in Twi...,https://www.startribune.com/joe-ryan-steps-up-...
2,2026-04-07-14-18-57 +0000,nyt,Iran War Live Updates: Trump Issues Grave Thre...,https://www.nytimes.com/live/2026/04/07/world/...
3,2026-04-07-14-16-57 +0000,nyt,Gunman Killed in Shootout Near Israeli Consula...,https://www.nytimes.com/2026/04/07/world/middl...
4,2026-04-07-14-15-03 +0000,nyt,Wireless Festival Canceled After U.K. Blocks K...,https://www.nytimes.com/2026/04/07/arts/music/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
5       trump     63
6        iran     55
20        war     26
8    deadline     24
189       new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
70,2026-04-07-11-00-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...,240
2,2026-04-07-14-18-57 +0000,nyt,Iran War Live Updates: Trump Issues Grave Thre...,https://www.nytimes.com/live/2026/04/07/world/...,186
223,2026-04-06-21-55-50 +0000,bbc,Trump threatens to take out Iran in 'one night...,https://www.bbc.com/news/articles/cqj8ep9w1pno...,184
246,2026-04-06-21-03-16 +0000,wapo,"Trump threatens to attack bridges, power plant...",https://www.washingtonpost.com/national-securi...,182
52,2026-04-07-12-25-05 +0000,nypost,Trump warns Iran that ‘a whole civilization wi...,https://nypost.com/2026/04/07/us-news/trump-wa...,180

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
70,240,2026-04-07-11-00-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...
133,80,2026-04-07-08-15-00 +0000,wsj,China Caps Rise in Fuel Prices as Middle East ...,https://www.wsj.com/finance/commodities-future...
54,61,2026-04-07-12-14-23 +0000,nypost,US strikes Iran’s oil-critical Kharg Island — ...,https://nypost.com/2026/04/07/world-news/us-st...
201,51,2026-04-06-23-24-00 +0000,wsj,A new Goldman Sachs report analyzing past tech...,https://www.wsj.com/economy/jobs/ai-displaced-...
39,48,2026-04-07-13-03-54 +0000,bbc,One gunman killed and two injured in shooting ...,https://www.bbc.com/news/articles/c3exp8j7yz4o...
150,44,2026-04-07-05-43-44 +0000,nypost,Son of Gilgo Beach victim files wrongful death...,https://nypost.com/2026/04/07/us-news/son-of-g...
160,39,2026-04-07-04-26-59 +0000,nyt,Trump Calls Artemis II Astronauts After Their ...,https://www.nytimes.com/2026/04/07/us/politics...
136,35,2026-04-07-07-43-31 +0000,nypost,American woman missing in Bahamas after going ...,https://nypost.com/2026/04/07/us-news/american...
246,35,2026-04-06-21-03-16 +0000,wapo,"Trump threatens to attack bridges, power plant...",https://www.washingtonpost.com/national-securi...
217,33,2026-04-06-22-21-00 +0000,wsj,Supreme Court Paves Way for Dismissal of Steve...,https://www.wsj.com/us-news/law/supreme-court-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)