## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-02-47-24 +0000,nyt,"In San Francisco’s A.I. Era, Even $180,000 Tec...",https://www.nytimes.com/2026/06/29/technology/...
1,2026-07-05-02-42-01 +0000,nyt,U.S. Ambassador to Canada Hosts July 4 Party A...,https://www.nytimes.com/live/2026/07/04/us/ame...
2,2026-07-05-02-30-35 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/04/us/ame...
3,2026-07-05-02-17-00 +0000,nyt,This California Town Banned Fireworks. Then Ca...,https://www.nytimes.com/2026/07/04/us/politics...
4,2026-07-05-02-14-07 +0000,cbc,Ambassador Hoekstra wants American booze back ...,https://www.cbc.ca/news/politics/us-ambassador...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
12      july     22
49     trump     22
123  funeral     15
106  america     13
88        th     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,101
118,2026-07-04-11-43-17 +0000,nyt,"Will Iran’s New Supreme Leader, Mojtaba Khamen...",https://www.nytimes.com/2026/07/04/world/middl...,81
17,2026-07-05-01-00-38 +0000,nyt,TV coverage of the Fourth of July will emphasi...,https://www.nytimes.com/live/2026/07/04/us/ame...,75
21,2026-07-05-00-46-17 +0000,cbc,Trump vows to still deliver Fourth of July spe...,https://www.cbc.ca/news/world/national-mall-ev...,71
36,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,101,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
36,70,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
123,42,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
44,38,2026-07-04-22-30-18 +0000,latimes,America at 250: A day to celebrate the country...,https://www.latimes.com/california/story/2026-...
41,32,2026-07-04-22-49-53 +0000,nypost,State-run facility for disabled New Yorkers ha...,https://nypost.com/2026/07/04/us-news/state-ru...
30,26,2026-07-04-23-37-10 +0000,nypost,DC’s National Mall evacuated as storms move in...,https://nypost.com/2026/07/04/us-news/washingt...
167,26,2026-07-04-04-50-06 +0000,bbc,Watch: Taylor Swift and Travis Kelce wed in NY...,https://www.bbc.co.uk/news/videos/cewqpdgqj0ko...
40,24,2026-07-04-22-52-34 +0000,latimes,Paul Pelosi faces possible hit-and-run charge ...,https://www.latimes.com/california/story/2026-...
168,24,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
141,24,2026-07-04-09-45-55 +0000,bbc,Large crowds gather in Tehran on first day of ...,https://www.bbc.co.uk/news/articles/c0ky2zen1k...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)