## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-27-01-31-26 +0000,nyt,Minneapolis Police Chief Brian O’Hara Resigns ...,https://www.nytimes.com/2026/05/26/us/minneapo...
1,2026-05-27-01-31-13 +0000,nypost,Father and 18-month-old son airlifted from sno...,https://nypost.com/2026/05/26/us-news/father-a...
2,2026-05-27-01-28-43 +0000,nypost,Married judge had sex with cop in courthouse —...,https://nypost.com/2026/05/26/us-news/married-...
3,2026-05-27-01-24-00 +0000,wsj,State Attorney General Ken Paxton clinched the...,https://www.wsj.com/politics/elections/paxton-...
4,2026-05-27-01-21-50 +0000,nyt,Christian Menefee Defeats Al Green in Texas De...,https://www.nytimes.com/2026/05/26/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
239     iran     31
44     trump     30
34     texas     19
210  strikes     16
258       up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-05-27-01-24-00 +0000,wsj,State Attorney General Ken Paxton clinched the...,https://www.wsj.com/politics/elections/paxton-...,128
304,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,115
11,2026-05-27-01-02-25 +0000,nypost,Ken Paxton swamps John Cornyn in Texas GOP Sen...,https://nypost.com/2026/05/26/us-news/ken-paxt...,99
34,2026-05-27-00-03-57 +0000,nyt,Iran War Updates: U.S. Saw Threats From Iran B...,https://www.nytimes.com/live/2026/05/26/world/...,97
296,2026-05-26-11-58-30 +0000,wapo,Iran threatens retaliation after U.S. strikes ...,https://www.washingtonpost.com/world/2026/05/2...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,128,2026-05-27-01-24-00 +0000,wsj,State Attorney General Ken Paxton clinched the...,https://www.wsj.com/politics/elections/paxton-...
34,97,2026-05-27-00-03-57 +0000,nyt,Iran War Updates: U.S. Saw Threats From Iran B...,https://www.nytimes.com/live/2026/05/26/world/...
32,52,2026-05-27-00-07-48 +0000,nypost,Supreme Court denies NFL’s bid to keep former ...,https://nypost.com/2026/05/26/us-news/supreme-...
211,52,2026-05-26-17-20-59 +0000,nypost,Joe Rogan floats bold back up plan for Spencer...,https://nypost.com/2026/05/26/us-news/joe-roga...
309,43,2026-05-26-10-35-00 +0000,wsj,War with Iran has halted a hard-won improvemen...,https://www.wsj.com/economy/housing/how-the-ir...
80,43,2026-05-26-22-18-28 +0000,nypost,Possible serial killer is latest horror to upe...,https://nypost.com/2026/05/26/world-news/possi...
341,42,2026-05-26-08-00-00 +0000,cbc,'Race against time' to contain Ebola outbreak ...,https://www.cbc.ca/news/health/ebola-outbreak-...
113,41,2026-05-26-21-13-12 +0000,nypost,"Starbucks sees sales drop, mass protests in So...",https://nypost.com/2026/05/26/world-news/starb...
219,39,2026-05-26-16-51-30 +0000,nypost,Ferrari’s new $640K electric car already a mas...,https://nypost.com/2026/05/26/business/ferrari...
148,36,2026-05-26-20-17-40 +0000,nyt,Canada Strikes Landmark Deal to Export Liquefi...,https://www.nytimes.com/2026/05/26/world/canad...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)