## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-18-16-56-57 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...
1,2026-04-18-16-54-22 +0000,bbc,HiPP recalls jarred baby food in Austria over ...,https://www.bbc.com/news/articles/c4gly4qkx1go...
2,2026-04-18-16-53-30 +0000,nypost,Pope Leo says ‘not in my interest at all’ to f...,https://nypost.com/2026/04/18/world-news/pope-...
3,2026-04-18-16-52-36 +0000,cbc,"Gunman who killed at least 6, took hostages in...",https://www.cbc.ca/news/world/ukraine-fatal-sh...
4,2026-04-18-16-48-05 +0000,nypost,French paratrooper killed in suspected Hezboll...,https://nypost.com/2026/04/18/world-news/frenc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2533/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     35
25    trump     28
176     new     17
8    strait     14
9    hormuz     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-18-16-56-57 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...,122
2,2026-04-18-16-53-30 +0000,nypost,Pope Leo says ‘not in my interest at all’ to f...,https://nypost.com/2026/04/18/world-news/pope-...,101
188,2026-04-17-21-50-49 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,93
137,2026-04-18-02-04-38 +0000,nyt,Trump Frames Iran War as All but Over in Optim...,https://www.nytimes.com/2026/04/17/world/middl...,91
26,2026-04-18-16-03-41 +0000,nypost,Dems challenge Trump’s ‘illegal war’ with Iran...,https://nypost.com/2026/04/18/us-news/dems-sid...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,122,2026-04-18-16-56-57 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...
23,61,2026-04-18-16-11-28 +0000,nypost,Pam Bondi market bullish even after Trump push...,https://nypost.com/2026/04/18/us-news/bondi-ma...
140,53,2026-04-18-01-38-00 +0000,wsj,New York City doormen and building owners reac...,https://www.wsj.com/economy/housing/the-week-n...
28,52,2026-04-18-16-00-00 +0000,wsj,Actual factory output is up sharply and may be...,https://www.wsj.com/economy/america-is-in-the-...
182,42,2026-04-17-22-19-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota said s...,https://www.wsj.com/politics/policy/ilhan-omar...
215,36,2026-04-17-20-29-00 +0000,wsj,The DOJ is preparing to file an antitrust laws...,https://www.wsj.com/politics/policy/justice-de...
178,35,2026-04-17-22-39-33 +0000,nyt,‘I Just Want to Be Back’: Thousands Rush South...,https://www.nytimes.com/2026/04/17/world/middl...
29,32,2026-04-18-15-58-44 +0000,nypost,"US planning to seize Iran-linked oil tankers, ...",https://nypost.com/2026/04/18/world-news/us-pl...
154,31,2026-04-18-00-25-00 +0000,cbc,U.S. Commerce Secretary Howard Lutnick takes a...,https://www.cbc.ca/news/world/howard-lutnick-c...
252,28,2026-04-17-18-25-12 +0000,bbc,Thousands celebrate open-air Mass with Pope Le...,https://www.bbc.com/news/articles/cdj7kwn1d78o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)