## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-20-51-44 +0000,nypost,Plane carrying DHS Secretary Markwayne Mullin ...,https://nypost.com/2026/09/02/us-news/plane-ca...
1,2026-09-02-20-50-00 +0000,wsj,U.S. Stocks Rise as Oil Gains on Iran Escalation,https://www.wsj.com/finance/stocks/u-s-stocks-...
2,2026-09-02-20-48-19 +0000,nyt,Deadlocked Jury in Lindsay Clancy Trial Again ...,https://www.nytimes.com/2026/09/02/us/lindsay-...
3,2026-09-02-20-46-17 +0000,nypost,Bay Area city manager resigns after bizarre ya...,https://nypost.com/2026/09/02/us-news/bay-area...
4,2026-09-02-20-46-12 +0000,nypost,Rubio urges House to pass Russia sanctions bil...,https://nypost.com/2026/09/02/us-news/rubio-ur...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2300/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
42   trump     38
15    iran     22
239    new     20
301     up     16
318   lake     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
348,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,104
43,2026-09-02-19-53-54 +0000,latimes,"Apple, Google rename Lake Ontario to Lake Amer...",https://www.latimes.com/business/story/2026-09...,102
347,2026-09-02-01-32-24 +0000,bbc,Apple Maps renames Lake Ontario as Lake Americ...,https://www.bbc.co.uk/news/articles/cddvyyz0e4...,100
74,2026-09-02-18-58-00 +0000,wapo,El-Sayed blames Trump for global bond market s...,https://www.washingtonpost.com/politics/2026/0...,96
364,2026-09-02-00-40-34 +0000,nyt,Map Apps Are Handling Trump’s Renaming of Lake...,https://www.nytimes.com/2026/09/01/us/lake-ont...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
348,104,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
443,87,2026-09-01-21-04-00 +0000,wsj,"U.S. Stocks Fall as Oil, Bond Yields Spike, U....",https://www.wsj.com/finance/investing/u-s-stoc...
214,83,2026-09-02-12-55-00 +0000,wapo,"Watch Ontario, New York, residents sound off o...",https://www.washingtonpost.com/politics/2026/0...
341,73,2026-09-02-01-59-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
236,66,2026-09-02-11-35-00 +0000,wsj,Massachusetts Sen. Ed Markey beat back a Democ...,https://www.wsj.com/politics/elections/sen-ed-...
433,59,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...
65,50,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
393,47,2026-09-01-23-07-08 +0000,chitri,"Whole Foods Market is coming to Old Town, and ...",https://www.chicagotribune.com/2026/09/01/whol...
56,42,2026-09-02-19-25-12 +0000,nypost,Wealthy California city votes to ban all tobac...,https://nypost.com/2026/09/02/us-news/bay-area...
397,42,2026-09-01-22-56-00 +0000,wsj,The House voted overwhelmingly to censure Rep....,https://www.wsj.com/politics/chuck-edwards-hou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)