## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-19-18-25 +0000,nypost,Arizona mass shooter fires wildly into crowd i...,https://nypost.com/2026/07/28/us-news/arizona-...
1,2026-07-28-19-16-38 +0000,nyt,Ukraine’s Strike on an Iranian Ship Could Brin...,https://www.nytimes.com/2026/07/28/world/middl...
2,2026-07-28-19-10-06 +0000,nyt,Biden Acknowledges Keeping Classified Material...,https://www.nytimes.com/2026/07/28/us/politics...
3,2026-07-28-19-08-00 +0000,wsj,Opinion | Jay Bhattacharya: How NIH Will End D...,https://www.wsj.com/opinion/jay-bhattacharya-h...
4,2026-07-28-19-07-35 +0000,nyt,Gibson Dunn Hires Rival Wachtell Lipton’s Co-C...,https://www.nytimes.com/2026/07/28/business/de...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2332/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
56    trump     38
314    iran     21
219     new     21
215      ai     16
452  market     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
217,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,111
107,2026-07-28-16-31-19 +0000,chitri,Donald Trump expresses frustrations with Benja...,https://www.chicagotribune.com/2026/07/28/trum...,110
236,2026-07-28-09-29-10 +0000,nyt,Trump Backs New Iran Talks but It’s Unclear Wh...,https://www.nytimes.com/2026/07/27/us/politics...,109
348,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,92
131,2026-07-28-15-11-00 +0000,wsj,Big Oil Is Raking In Billions From the Iran Wa...,https://www.wsj.com/business/energy-oil/big-oi...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
217,111,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...
107,72,2026-07-28-16-31-19 +0000,chitri,Donald Trump expresses frustrations with Benja...,https://www.chicagotribune.com/2026/07/28/trum...
335,70,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
105,65,2026-07-28-16-32-23 +0000,nypost,Gavin Newsom responds to Ruby Rippey’s claims ...,https://nypost.com/2026/07/28/us-news/gavin-ne...
115,46,2026-07-28-16-14-02 +0000,chitri,FIFA plan for Kushner-backed $20 billion opera...,https://www.chicagotribune.com/2026/07/28/fifa...
46,45,2026-07-28-18-02-13 +0000,nypost,High school football standout jumps to his dea...,https://nypost.com/2026/07/28/us-news/high-sch...
191,44,2026-07-28-11-18-00 +0000,wsj,Perhaps no one has a tougher job in Washington...,https://www.wsj.com/politics/the-save-america-...
291,43,2026-07-28-01-29-25 +0000,bbc,BBC outside court as judge rules singer D4vd w...,https://www.bbc.co.uk/news/videos/cy745x171rjo...
41,43,2026-07-28-18-08-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
100,41,2026-07-28-16-39-20 +0000,nypost,Fourth major heatwave expected to hit France a...,https://nypost.com/2026/07/28/world-news/fourt...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)