## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-13-48-35 +0000,nyt,"Rick Jackson, Georgia Governor Candidate, Is A...",https://www.nytimes.com/2026/06/12/us/election...
1,2026-06-12-13-46-52 +0000,nyt,Scientists Measure Earth’s Vast Underground Fu...,https://www.nytimes.com/2026/06/11/science/eco...
2,2026-06-12-13-46-06 +0000,nyt,The World Cup Could Be the Biggest Sports Gamb...,https://www.nytimes.com/2026/06/12/business/wo...
3,2026-06-12-13-45-54 +0000,nypost,South Korean ex-President Yoon Suk Yeol senten...,https://nypost.com/2026/06/12/world-news/south...
4,2026-06-12-13-45-12 +0000,nyt,Iran War Live Updates: Tense Calm Grips Mideas...,https://www.nytimes.com/live/2026/06/12/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
45    trump     35
37     iran     29
17    world     29
172  spacex     25
18      cup     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...,115
127,2026-06-12-08-09-37 +0000,bbc,Tehran says 'nothing' finalised after Trump cl...,https://www.bbc.com/news/articles/c78y6w78828o...,114
259,2026-06-11-20-51-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/policy/showdown-b...,111
9,2026-06-12-13-40-12 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...,111
4,2026-06-12-13-45-12 +0000,nyt,Iran War Live Updates: Tense Calm Grips Mideas...,https://www.nytimes.com/live/2026/06/12/world/...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,115,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...
33,100,2026-06-12-12-52-55 +0000,bbc,Elon Musk's SpaceX raises $75bn ahead of world...,https://www.bbc.com/news/articles/cwy034q89j4o...
220,80,2026-06-11-22-21-02 +0000,nypost,How 3 million missing barrels of oil are keepi...,https://nypost.com/2026/06/11/world-news/how-3...
213,66,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
196,61,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...
362,58,2026-06-11-15-42-00 +0000,nypost,Lesley Stahl signs new two-year deal to stay a...,https://nypost.com/2026/06/11/media/lesley-sta...
126,47,2026-06-12-08-16-52 +0000,nypost,White House fires back at Ariana Grande after ...,https://nypost.com/2026/06/12/us-news/white-ho...
182,46,2026-06-12-01-00-00 +0000,wsj,When Trump meets his counterparts at next week...,https://www.wsj.com/economy/global/the-global-...
219,38,2026-06-11-22-31-00 +0000,wsj,Man Charged With Killing Minnesota Lawmaker Pl...,https://www.wsj.com/us-news/law/man-charged-wi...
377,37,2026-06-11-14-58-00 +0000,wsj,The ECB became the first major central bank to...,https://www.wsj.com/economy/central-banking/ec...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)