## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...
1,2026-05-18-20-19-59 +0000,nypost,California shopper sues fashion retailer for t...,https://nypost.com/2026/05/18/us-news/californ...
2,2026-05-18-20-19-21 +0000,nyt,Oil Prices Climb and Bonds Falter as Iran War ...,https://www.nytimes.com/2026/05/18/business/oi...
3,2026-05-18-20-17-11 +0000,nyt,What is Trump’s $1.776 Billion ‘Anti-Weaponiza...,https://www.nytimes.com/2026/05/18/us/politics...
4,2026-05-18-20-14-18 +0000,nypost,Spencer Pratt channels Will Smith for ‘fresh’ ...,https://nypost.com/2026/05/18/us-news/spencer-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
3   trump     32
43    new     17
7    iran     16
4      he     13
54  ebola     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-05-18-19-43-45 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,102
17,2026-05-18-19-48-00 +0000,wsj,Trump Says He Will Hold Off on Iran Attack as ...,https://www.wsj.com/world/middle-east/trump-sa...,95
24,2026-05-18-19-35-00 +0000,cbc,Trump says he's called off Tuesday Iran strike...,https://www.cbc.ca/news/world/trump-iran-strik...,89
251,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...,87
0,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,102,2026-05-18-19-43-45 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
63,52,2026-05-18-18-34-46 +0000,cbc,American tests positive for Ebola virus amid o...,https://www.cbc.ca/news/health/american-tests-...
74,43,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
92,41,2026-05-18-17-32-00 +0000,wsj,President Trump will host a swearing-in ceremo...,https://www.wsj.com/economy/central-banking/tr...
264,37,2026-05-17-23-02-56 +0000,bbc,'This may be the last time you hear my voice':...,https://www.bbc.com/news/articles/cn8p392nl7yo...
258,36,2026-05-18-00-49-25 +0000,bbc,Moment two fighter jets collide mid-air at US ...,https://www.bbc.com/news/videos/ce8pzkg7klgo?a...
46,36,2026-05-18-19-05-07 +0000,startribune,Justice Department announces a $1.7B fund to c...,https://www.startribune.com/trump-moves-to-dis...
274,35,2026-05-17-21-07-19 +0000,latimes,Tustin police arrest man accused of fatally sh...,https://www.latimes.com/california/story/2026-...
1,32,2026-05-18-20-19-59 +0000,nypost,California shopper sues fashion retailer for t...,https://nypost.com/2026/05/18/us-news/californ...
163,30,2026-05-18-13-52-32 +0000,nypost,Military diver who died trying to recover Ital...,https://nypost.com/2026/05/18/world-news/milit...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)