## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-16-10-51-56 +0000,bbc,Burnham asks for 'manual trawl' of records for...,https://www.bbc.co.uk/news/articles/c6x2ve4nr9...
1,2026-10-16-10-51-25 +0000,bbc,"Action needed to save water, minister urges",https://www.bbc.co.uk/news/articles/cq0ld4g030...
2,2026-10-16-10-50-03 +0000,nyt,5 Takeaways From the Senate Debate in Maine,https://www.nytimes.com/2026/10/15/us/politics...
3,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...
4,2026-10-16-10-45-55 +0000,nyt,What Life Is Like in Kyiv as Russia Tries to M...,https://www.nytimes.com/2026/10/16/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18     trump     37
20   ukraine     24
108      new     21
46    school     20
15    senate     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...,185
350,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...,136
221,2026-10-15-20-46-18 +0000,chitri,Ukraine abandons truce and attacks Russian oil...,https://www.chicagotribune.com/2026/10/15/ukra...,125
3,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...,107
94,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,185,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...
345,92,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...
6,82,2026-10-16-10-39-21 +0000,nypost,Hero gunman who ran into Oregon elementary sch...,https://nypost.com/2026/10/16/us-news/hero-gun...
354,74,2026-10-15-14-19-00 +0000,wsj,Florida’s Democratic Senate nominee Angie Nixo...,https://www.wsj.com/politics/elections/the-int...
350,58,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...
94,57,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...
353,56,2026-10-15-14-25-16 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/15/us-news/new-whit...
99,55,2026-10-16-04-41-00 +0000,wsj,Fed Chairman Kevin Warsh declined to endorse o...,https://www.wsj.com/economy/central-banking/wa...
182,48,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
236,43,2026-10-15-20-13-23 +0000,nypost,Eric Swalwell breaks 6 months of hiding as he’...,https://nypost.com/2026/10/15/us-news/eric-swa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)