## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-02-17-06-19 +0000,bbc,Bars close and hundreds lose jobs as US firm b...,https://www.bbc.com/news/articles/c05v0p1d0peo...
1,2026-03-02-17-06-00 +0000,wsj,Opinion | The Case for Cautious Optimism About...,https://www.wsj.com/opinion/the-case-for-cauti...
2,2026-03-02-17-05-54 +0000,wapo,Live updates: War with Iran expands across reg...,https://www.washingtonpost.com/world/2026/03/0...
3,2026-03-02-17-05-54 +0000,wapo,Trump says he’s not ruling out sending ground ...,https://www.washingtonpost.com
4,2026-03-02-17-05-31 +0000,nyt,Live Updates: Trump Defends Strikes on Iran as...,https://www.nytimes.com/live/2026/03/02/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
14       iran     88
12      trump     31
13        war     22
31    strikes     21
196  conflict     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-03-02-13-08-28 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,252
228,2026-03-02-01-17-20 +0000,latimes,Thousands rally in Westwood as U.S.-Iran war e...,https://www.latimes.com/california/story/2026-...,208
73,2026-03-02-15-17-25 +0000,nypost,Trump won’t rule out sending US troops into Ir...,https://nypost.com/2026/03/02/us-news/trump-wo...,177
275,2026-03-01-20-43-28 +0000,nypost,Trump reveals how long he expects Iran campaig...,https://nypost.com/2026/03/01/world-news/trump...,166
270,2026-03-01-20-59-43 +0000,bbc,UK troops and civilians in Middle East put at ...,https://www.bbc.com/news/articles/crrxkjxg1zpo...,163

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,252,2026-03-02-13-08-28 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
197,86,2026-03-02-07-45-00 +0000,wsj,Middle East Conflict Sparks Surge in Oil Prices,https://www.wsj.com/world/middle-east/middle-e...
16,77,2026-03-02-16-46-23 +0000,cbc,U.S. military leaders lay out timeline of atta...,https://www.cbc.ca/news/world/us-pentagon-iran...
248,62,2026-03-01-22-24-27 +0000,bbc,Nine dead in missile attack on Israel as Iran ...,https://www.bbc.com/news/articles/c363zkp1pgxo...
163,51,2026-03-02-10-30-00 +0000,wsj,Berkshire’s New CEO Lays Out How He Will Pick ...,https://www.wsj.com/finance/berkshires-new-ceo...
168,46,2026-03-02-10-30-00 +0000,wsj,The Texas Republican Senate primary is getting...,https://www.wsj.com/politics/elections/texas-p...
131,37,2026-03-02-12-27-21 +0000,nypost,Huge fire as one of the world’s largest oil re...,https://nypost.com/2026/03/02/world-news/drone...
42,33,2026-03-02-16-11-16 +0000,nypost,First victim of Austin mass shooting identifie...,https://nypost.com/2026/03/02/us-news/first-vi...
23,32,2026-03-02-16-34-18 +0000,wapo,Videos appear to show the moments U.S. fighter...,https://www.washingtonpost.com/investigations/...
162,30,2026-03-02-10-34-00 +0000,wsj,"Canada, India Strike $1.9 Billion Uranium Supp...",https://www.wsj.com/economy/canada-india-strik...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)