## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-07-13-23 +0000,nyt,Ukraine’s Top General Becomes a Target of Prot...,https://www.nytimes.com/2026/07/18/world/europ...
1,2026-07-19-06-48-03 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes A...,https://www.nytimes.com/live/2026/07/18/world/...
2,2026-07-19-05-51-24 +0000,nypost,Second death reported in NYC’s Legionnaires’ c...,https://nypost.com/2026/07/19/us-news/nyc-legi...
3,2026-07-19-05-43-19 +0000,nypost,US ambassador to UN slaps down Zohran Mamdani’...,https://nypost.com/2026/07/19/us-news/us-ambas...
4,2026-07-19-05-10-57 +0000,bbc,US and Iran exchange strikes after two US sold...,https://www.bbc.co.uk/news/articles/cgk417jp83...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7       iran     16
432    trump     14
51     world     13
12   strikes     10
98       new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
58,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...,68
1,2026-07-19-06-48-03 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes A...,https://www.nytimes.com/live/2026/07/18/world/...,62
55,2026-07-18-22-57-00 +0000,wapo,U.S. strikes Iran after 2 service members kill...,https://www.washingtonpost.com/world/2026/07/1...,60
5,2026-07-19-04-53-22 +0000,nypost,Spanish legend Joan Capdevila will be allowed ...,https://nypost.com/2026/07/19/us-news/spanish-...,55
57,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
58,68,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
75,44,2026-07-18-19-04-16 +0000,nypost,World’s most livable city tops global list sec...,https://nypost.com/2026/07/18/world-news/world...
39,41,2026-07-19-00-18-47 +0000,bbc,Two US troops killed and one missing after Ira...,https://www.bbc.co.uk/news/articles/cn8nynv8ze...
87,39,2026-07-18-17-29-50 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...
3,36,2026-07-19-05-43-19 +0000,nypost,US ambassador to UN slaps down Zohran Mamdani’...,https://nypost.com/2026/07/19/us-news/us-ambas...
42,32,2026-07-19-00-00-00 +0000,wsj,He Ran a Strip Club. Now He Wants to Build Cal...,https://www.wsj.com/us-news/he-ran-a-strip-clu...
125,27,2026-07-18-13-08-17 +0000,nypost,Eight killed after Ukraine launches wave of dr...,https://nypost.com/2026/07/18/world-news/eight...
5,26,2026-07-19-04-53-22 +0000,nypost,Spanish legend Joan Capdevila will be allowed ...,https://nypost.com/2026/07/19/us-news/spanish-...
162,25,2026-07-18-09-30-00 +0000,wsj,The popularity of prediction markets such as P...,https://www.wsj.com/politics/policy/dc-governm...
24,24,2026-07-19-01-33-02 +0000,nypost,NYC homeless man hurls cell phone at baby in s...,https://nypost.com/2026/07/18/us-news/bryant-p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)