## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-07-10-33 +0000,bbc,Sadiq Khan says Labour should pledge to rejoin EU,https://www.bbc.com/news/articles/c62g2e08jpno...
1,2026-03-19-07-10-00 +0000,wsj,Oil Prices Could Stay Elevated for Some Time,https://www.wsj.com/finance/commodities-future...
2,2026-03-19-07-01-00 +0000,wsj,U.S. Treasury Yields Rise as Oil Price Leaps,https://www.wsj.com/finance/investing/jgb-futu...
3,2026-03-19-07-00-07 +0000,nyt,E.U. Loan for Ukraine Becomes Election Leverag...,https://www.nytimes.com/2026/03/19/world/europ...
4,2026-03-19-06-58-53 +0000,nyt,Missile Attack Kills at Least 3 in West Bank,https://www.nytimes.com/live/2026/03/18/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
71     iran     59
72      war     36
246   trump     36
399  chavez     25
398   cesar     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
369,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,166
152,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...,165
270,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,156
262,2026-03-18-17-07-48 +0000,nyt,Trump’s Next Decision in War: Whether to Retri...,https://www.nytimes.com/2026/03/17/us/politics...,154
46,2026-03-19-02-19-22 +0000,nyt,Senate G.O.P. Again Blocks Bid to Stop Iran Wa...,https://www.nytimes.com/2026/03/18/us/politics...,150

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
369,166,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...
54,91,2026-03-19-02-02-49 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
325,86,2026-03-18-14-35-35 +0000,nypost,Oil spikes after Iran says world’s largest gas...,https://nypost.com/2026/03/18/world-news/oil-s...
69,67,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
21,66,2026-03-19-04-48-51 +0000,nypost,New details emerge about New Mexico US Air For...,https://nypost.com/2026/03/19/us-news/new-deta...
340,60,2026-03-18-13-51-07 +0000,cbc,Bank of Canada holds key interest rate at 2.25...,https://www.cbc.ca/news/business/bank-of-canad...
370,52,2026-03-18-10-59-42 +0000,nypost,Israel says it assassinated Iranian intelligen...,https://nypost.com/2026/03/18/world-news/israe...
272,44,2026-03-18-16-58-36 +0000,startribune,Minnesota house prices decline for first time ...,https://www.startribune.com/minnesota-house-pr...
31,42,2026-03-19-03-54-00 +0000,wsj,Oil Rises After Attacks on Middle East Energy ...,https://www.wsj.com/finance/oil-rises-amid-wid...
228,41,2026-03-18-18-51-07 +0000,bbc,Five takeaways from Markwayne Mullin's Homelan...,https://www.bbc.com/news/articles/c2k8kp7d832o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)