## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-19-59-15 +0000,nyt,Keir Starmer Resigns as UK Prime Minister,https://www.nytimes.com/2026/06/22/world/europ...
1,2026-06-22-19-50-01 +0000,startribune,Lionel Messi breaks World Cup scoring record w...,https://www.startribune.com/lionel-messi-misse...
2,2026-06-22-19-50-00 +0000,wsj,Treasury Yields Rise as Middle East Talks Cont...,https://www.wsj.com/finance/investing/jgb-yiel...
3,2026-06-22-19-46-27 +0000,nyt,Shootout Suspect Is Dead After Killing Montrea...,https://www.nytimes.com/2026/06/22/world/canad...
4,2026-06-22-19-44-27 +0000,bbc,Starmer quits as Labour leader and paves way f...,https://www.bbc.com/news/articles/cdxd00lg599o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
84      iran     23
1    starmer     19
5   minister     16
38       new     15
22     talks     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
191,2026-06-22-12-51-52 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,90
249,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...,83
229,2026-06-22-10-09-12 +0000,cbc,U.K. Prime Minister Keir Starmer announces res...,https://www.cbc.ca/news/world/livestory/starme...,75
4,2026-06-22-19-44-27 +0000,bbc,Starmer quits as Labour leader and paves way f...,https://www.bbc.com/news/articles/cdxd00lg599o...,75
211,2026-06-22-11-01-00 +0000,wsj,U.K. Prime Minister Keir Starmer Quits After P...,https://www.wsj.com/world/uk/u-k-prime-ministe...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
191,90,2026-06-22-12-51-52 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
10,69,2026-06-22-19-39-15 +0000,nyt,Vance Claims Progress in First Day of Iran Talks,https://www.nytimes.com/2026/06/22/world/middl...
128,62,2026-06-22-15-30-00 +0000,wsj,The Supreme Court is about to decide four case...,https://www.wsj.com/politics/policy/the-suprem...
204,60,2026-06-22-11-35-00 +0000,wsj,"Alan Greenspan, who piloted the economy throug...",https://www.wsj.com/economy/central-banking/al...
210,49,2026-06-22-11-01-00 +0000,wsj,"In Washington and around the world, political ...",https://www.wsj.com/politics/in-washington-and...
260,43,2026-06-22-04-58-42 +0000,nypost,2 students arrested after deadly high school s...,https://nypost.com/2026/06/22/world-news/phili...
290,42,2026-06-21-23-54-20 +0000,cbc,Abelardo De La Espriella wins Colombia electio...,https://www.cbc.ca/news/world/colombia-preside...
53,42,2026-06-22-18-11-56 +0000,bbc,"Clive Davis, music mogul behind Whitney Housto...",https://www.bbc.com/news/articles/c3vy3e6q90qo...
66,37,2026-06-22-17-31-13 +0000,nypost,Real-life ‘Succession’ rocks Ray-Ban dynasty a...,https://nypost.com/2026/06/22/business/ray-ban...
1,36,2026-06-22-19-50-01 +0000,startribune,Lionel Messi breaks World Cup scoring record w...,https://www.startribune.com/lionel-messi-misse...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)