## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-19-24-00 +0000,nypost,Trans gunman caught in alleged casino terror p...,https://nypost.com/2026/07/01/us-news/trans-gu...
1,2026-07-01-19-23-55 +0000,nyt,Sea Hawk Helicopter Makes Emergency Landing in...,https://www.nytimes.com/2026/07/01/us/navy-hel...
2,2026-07-01-19-23-21 +0000,startribune,Live as NHL free agency begins: Wild lose Mats...,https://www.startribune.com/minnesota-wild-nhl...
3,2026-07-01-19-17-23 +0000,nypost,Fourth of July ruined for thousands as Pocket ...,https://nypost.com/2026/07/01/lifestyle/massiv...
4,2026-07-01-19-16-20 +0000,nypost,Grieving dad rips Florida officials for not ad...,https://nypost.com/2026/07/01/us-news/grieving...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
122  trump     49
230    new     16
58   world     16
645  court     15
59     cup     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
142,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,112
320,2026-06-30-23-13-00 +0000,wsj,"Trump’s Friends Gave Him Tickets to World Cup,...",https://www.wsj.com/sports/trumps-friends-gave...,108
244,2026-07-01-09-00-00 +0000,nypost,Trump takes new Qatari jet for test flight to ...,https://nypost.com/2026/07/01/us-news/trump-ta...,100
268,2026-07-01-05-32-26 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,100
114,2026-07-01-15-57-38 +0000,nyt,Trump Takes First Flight on New Air Force One ...,https://www.nytimes.com/2026/07/01/us/politics...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
142,112,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
289,77,2026-07-01-02-00-00 +0000,wsj,The Supreme Court has wrapped up one of its mo...,https://www.wsj.com/politics/policy/how-suprem...
210,65,2026-07-01-10-49-02 +0000,nypost,Dog missing for month in Mexico found partying...,https://nypost.com/2026/07/01/world-news/dog-m...
278,52,2026-07-01-04-15-11 +0000,nypost,Socialist congressional candidate Melat Kiros ...,https://nypost.com/2026/07/01/us-news/socialis...
370,51,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
28,43,2026-07-01-18-39-11 +0000,nyt,Trump Administration Sues Over New Gun Bans in...,https://www.nytimes.com/2026/07/01/us/politics...
33,43,2026-07-01-18-28-01 +0000,wapo,Fate of $2 trillion North American trade deal ...,https://www.washingtonpost.com/business/2026/0...
72,42,2026-07-01-17-25-54 +0000,nypost,1 airman missing after MH-60S Sea Hawk helicop...,https://nypost.com/2026/07/01/us-news/1-airman...
37,40,2026-07-01-18-20-18 +0000,latimes,Chabria: Birthright citizenship ruling was a w...,https://www.latimes.com/california/story/2026-...
80,40,2026-07-01-17-12-00 +0000,wsj,Elizabeth Warren asked the Fed’s inspector gen...,https://www.wsj.com/economy/central-banking/wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)