## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-14-56-35 +0000,nypost,Harrowing moment kayaker is pulled from Pacifi...,https://nypost.com/2026/10/10/us-news/kayaker-...
1,2026-10-10-14-52-41 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/09/world/...
2,2026-10-10-14-51-21 +0000,nyt,"From a Sikh Sanctuary to Chaotic Streets, Prot...",https://www.nytimes.com/2026/10/10/world/asia/...
3,2026-10-10-14-49-32 +0000,bbc,Drone strike by Sudan paramilitary kills 41 ne...,https://www.bbc.co.uk/news/articles/c8vgx9ew57...
4,2026-10-10-14-45-03 +0000,startribune,Isaias weakens but flooding threat persists as...,https://www.startribune.com/hundreds-of-thousa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
67    trump     50
435     new     19
253      he     14
205   nobel     14
369  senate     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
183,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,214
195,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,131
124,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...,131
126,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...,128
111,2026-10-10-03-09-00 +0000,nyt,Trump Says He Will Import Russian Diesel Fuel ...,https://www.nytimes.com/2026/10/09/us/politics...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
183,214,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
267,78,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...
161,77,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
155,61,2026-10-09-22-38-00 +0000,wsj,The planned execution of Nidal Hasan has spark...,https://www.wsj.com/politics/national-security...
229,49,2026-10-09-19-55-00 +0000,wapo,Ocasio-Cortez will stump for Abdul El-Sayed in...,https://www.washingtonpost.com/politics/2026/1...
319,42,2026-10-09-15-04-02 +0000,nypost,3 killed in Russian strikes across Ukraine as ...,https://nypost.com/2026/10/09/world-news/3-kil...
123,42,2026-10-10-01-44-09 +0000,latimes,Off-duty ICE agent found sleeping on Fresno la...,https://www.latimes.com/california/story/2026-...
95,41,2026-10-10-06-44-48 +0000,nypost,Hurricane Isaias hit Florida ‘like a freight t...,https://nypost.com/2026/10/10/us-news/hurrican...
248,40,2026-10-09-18-53-36 +0000,nypost,Flydubai co-pilot was inspired by 9/11 when he...,https://nypost.com/2026/10/09/world-news/flydu...
147,37,2026-10-09-23-01-29 +0000,nypost,Madrid bus campaign from pro-Israel group link...,https://nypost.com/2026/10/09/world-news/madri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)