## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-18-18-49-27 +0000,nypost,NYC’s deadly Legionnaires’ outbreak linked to ...,https://nypost.com/2026/10/18/us-news/busted-v...
1,2026-10-18-18-38-22 +0000,nypost,Soho retail going strong with Fujifilm deal fo...,https://nypost.com/2026/10/18/business/soho-re...
2,2026-10-18-18-34-21 +0000,nyt,Obama Defends Rep. Ilhan Omar Amid Trump Admin...,https://www.nytimes.com/2026/10/18/us/politics...
3,2026-10-18-18-28-00 +0000,wsj,Trump Endorses Israel’s Netanyahu for Re-Election,https://www.wsj.com/world/middle-east/trump-en...
4,2026-10-18-18-26-16 +0000,nyt,France in Shock After Protests Turn Into Riots...,https://www.nytimes.com/2026/10/18/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
23       trump     29
41          he     11
105     russia     10
140  president      9
88         out      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
183,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...,91
173,2026-10-17-20-57-00 +0000,wsj,President Trump is halting implementation of m...,https://www.wsj.com/politics/policy/trump-waiv...,76
24,2026-10-18-17-07-58 +0000,nypost,GOP Senate candidate Mike Rogers breaks with T...,https://nypost.com/2026/10/18/us-news/gop-sen-...,72
23,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...,69
175,2026-10-17-20-47-54 +0000,chitri,President Donald Trump touts his power at Kent...,https://www.chicagotribune.com/2026/10/17/trum...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
183,91,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...
135,48,2026-10-18-02-00-00 +0000,wsj,Republicans across the most competitive House ...,https://www.wsj.com/politics/elections/republi...
23,40,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...
13,37,2026-10-18-17-43-02 +0000,nyt,Carney Says Fire at Canadian Forces Base Wainw...,https://www.nytimes.com/2026/10/18/world/canad...
145,32,2026-10-18-00-49-42 +0000,bbc,Watch: Moment historic French town hall spire ...,https://www.bbc.co.uk/news/videos/c6e3xjw37wn7...
46,30,2026-10-18-16-00-00 +0000,wsj,"From firehouses to farms, Pennsylvania locals ...",https://www.wsj.com/politics/elections/pennsyl...
11,29,2026-10-18-17-45-09 +0000,chitri,Photographer attacked by settlers in the West ...,https://www.chicagotribune.com/2026/10/18/phot...
86,28,2026-10-18-11-09-32 +0000,bbc,Pope Leo XIV thanks wellwishers in first event...,https://www.bbc.co.uk/news/videos/cq70px6pjkg5...
178,28,2026-10-17-20-06-07 +0000,nypost,"Violent rioters flood the streets of France, b...",https://nypost.com/2026/10/17/world-news/franc...
166,27,2026-10-17-21-52-25 +0000,nypost,Abdul El-Sayed remains close to terror-linked ...,https://nypost.com/2026/10/17/us-news/abdul-el...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)