## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-21-17-28 +0000,nypost,Aerospace company behind toxic Orange County t...,https://nypost.com/2026/06/04/us-news/garden-g...
1,2026-06-04-21-17-21 +0000,nyt,Mideast Live Updates: Hezbollah Rejects Cease-...,https://www.nytimes.com/live/2026/06/04/world/...
2,2026-06-04-21-16-21 +0000,nyt,Wall Street Is Going Gaga for SpaceX,https://www.nytimes.com/2026/06/04/business/wa...
3,2026-06-04-21-14-40 +0000,missionlocal,Alan Wong the candidate didn’t win the electio...,https://missionlocal.org/2026/06/sf-daniel-lur...
4,2026-06-04-21-13-19 +0000,cbc,Cross-border tunnel drug bust | About That,https://www.cbc.ca/player/play/9.7224019?cmp=rss

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
54         trump     41
158          new     20
1127        iran     12
224   california     12
178           up     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
351,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...,109
22,2026-06-04-20-56-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...,103
347,2026-06-03-21-43-00 +0000,wsj,Some GOP lawmakers are pushing to kill the adm...,https://www.wsj.com/politics/policy/fight-to-k...,98
346,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,98
309,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
351,109,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
1,64,2026-06-04-21-17-21 +0000,nyt,Mideast Live Updates: Hezbollah Rejects Cease-...,https://www.nytimes.com/live/2026/06/04/world/...
346,57,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...
22,55,2026-06-04-20-56-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...
49,51,2026-06-04-20-21-14 +0000,nypost,NY set to pass one-year pause on data centers ...,https://nypost.com/2026/06/04/us-news/ny-set-t...
186,43,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...
120,40,2026-06-04-17-47-09 +0000,cbc,FIFA no longer letting fans bring refillable w...,https://www.cbc.ca/news/canada/toronto/fifa-ba...
315,38,2026-06-04-01-00-00 +0000,wsj,"Amaryllis Fox Kennedy, a former Trump administ...",https://www.wsj.com/politics/national-security...
314,37,2026-06-04-01-00-00 +0000,wsj,Top AI executives are joining security experts...,https://www.wsj.com/politics/policy/top-ai-ceo...
9,34,2026-06-04-21-01-54 +0000,latimes,Spencer Pratt claims L.A.'s homeless will move...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)