## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-20-16-58-21 +0000,nypost,Why whales are being drawn to ‘feeding frenzie...,https://nypost.com/2026/08/20/world-news/why-w...
1,2026-08-20-16-58-08 +0000,chitri,No Democratic National Convention repeat for C...,https://www.chicagotribune.com/2026/08/20/demo...
2,2026-08-20-16-57-29 +0000,nyt,A Prince at 26: Once-Secret Son of Belgian Roy...,https://www.nytimes.com/2026/08/20/world/europ...
3,2026-08-20-16-53-35 +0000,nypost,Karmelo Anthony prosecutor reveals trove of ev...,https://nypost.com/2026/08/20/us-news/karmelo-...
4,2026-08-20-16-53-20 +0000,bbc,Como mayor bans 'beasts' in city centre after ...,https://www.bbc.co.uk/news/articles/cn8n077vxd...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2473/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
69    trump     56
71      new     22
204  meghan     18
241    iran     17
203   harry     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
254,2026-08-20-01-56-53 +0000,nypost,Trump announces ‘Economic D-Day’ against Iran:...,https://nypost.com/2026/08/19/us-news/trump-an...,122
274,2026-08-19-23-13-53 +0000,chitri,Missouri court allows new Trump-backed US Hous...,https://www.chicagotribune.com/2026/08/19/miss...,116
206,2026-08-20-09-00-00 +0000,wsj,Trump’s half-built White House ballroom is a 9...,https://www.wsj.com/politics/policy/build-firs...,111
264,2026-08-20-00-52-14 +0000,cbc,Trump says he'll launch 'most crushing economi...,https://www.cbc.ca/news/world/trump-economic-a...,109
128,2026-08-20-11-58-09 +0000,cbc,North Korea fires up to 10 ballistic missiles ...,https://www.cbc.ca/news/world/north-korea-miss...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
254,122,2026-08-20-01-56-53 +0000,nypost,Trump announces ‘Economic D-Day’ against Iran:...,https://nypost.com/2026/08/19/us-news/trump-an...
192,79,2026-08-20-09-30-00 +0000,wsj,After 66-year-old Lynn Lee was laid off last y...,https://www.wsj.com/lifestyle/careers/the-66-y...
106,73,2026-08-20-13-19-24 +0000,chitri,A timeline of Prince Harry and Meghan’s relati...,https://www.chicagotribune.com/2026/08/20/prin...
274,60,2026-08-19-23-13-53 +0000,chitri,Missouri court allows new Trump-backed US Hous...,https://www.chicagotribune.com/2026/08/19/miss...
371,53,2026-08-19-19-05-24 +0000,nypost,Telemundo exec killed in Kenya helicopter cras...,https://nypost.com/2026/08/19/us-news/telemund...
217,52,2026-08-20-08-12-24 +0000,wsj,Stock Market Today: Bessent Signals Treasury B...,https://www.wsj.com/livecoverage/stock-market-...
410,47,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...
159,45,2026-08-20-10-47-37 +0000,nypost,North Korea fires about 10 short-range ballist...,https://nypost.com/2026/08/20/world-news/north...
45,44,2026-08-20-15-36-46 +0000,nypost,"Evergrande founder Hui Ka Yan, once Asia’s ric...",https://nypost.com/2026/08/20/business/evergra...
255,41,2026-08-20-01-54-00 +0000,wsj,Angie Nixon pulled off her upset in the Democr...,https://www.wsj.com/politics/elections/how-dem...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)