## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-19-11-39 +0000,nypost,American and wife who recently ‘self-deported’...,https://nypost.com/2026/07/25/world-news/body-...
1,2026-07-25-19-06-38 +0000,nyt,Inside the Rushed Effort to Get Trump His New ...,https://www.nytimes.com/2026/07/25/us/politics...
2,2026-07-25-19-04-49 +0000,nypost,"Massive fire ravages NYC home, injuring 21 and...",https://nypost.com/2026/07/25/us-news/21-hurt-...
3,2026-07-25-19-03-07 +0000,nyt,"After Democratic Shake-Up, Susan Collins Holds...",https://www.nytimes.com/2026/07/25/us/politics...
4,2026-07-25-18-57-53 +0000,nypost,49ers give update after head coach Kyle Shanah...,https://nypost.com/2026/07/25/us-news/san-fran...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2468/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
11   trump     32
103   iran     22
12     new     17
104    war     11
17    fire      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
211,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,86
13,2026-07-25-18-28-42 +0000,nyt,"Iran War Live Updates: U.S. Strikes Abate, Eve...",https://www.nytimes.com/live/2026/07/25/world/...,81
206,2026-07-24-21-41-12 +0000,nyt,Trump Meets With Top Advisers as He Weighs a M...,https://www.nytimes.com/2026/07/24/us/politics...,76
41,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...,75
119,2026-07-25-09-01-58 +0000,nyt,President Trump’s New Air Force One Poses Pote...,https://www.nytimes.com/video/us/1000000110477...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
211,86,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...
53,60,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...
204,50,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
41,43,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...
199,33,2026-07-24-21-57-04 +0000,nypost,ICC’s chief prosecutor removed from position f...,https://nypost.com/2026/07/24/world-news/iccs-...
84,32,2026-07-25-12-18-59 +0000,cbc,Youth protesters celebrate after India's educa...,https://www.cbc.ca/news/world/india-education-...
225,31,2026-07-24-20-49-00 +0000,wsj,The U.S. will consider applying additional tar...,https://www.wsj.com/economy/trade/trump-threat...
82,30,2026-07-25-12-30-22 +0000,cbc,Man's death reported in Spain as wildfires als...,https://www.cbc.ca/news/world/wildfire-evacuat...
64,30,2026-07-25-14-47-25 +0000,nypost,"US-Iran war spreads as Saudi Arabia, Houthis t...",https://nypost.com/2026/07/25/world-news/us-ir...
46,29,2026-07-25-16-19-39 +0000,nypost,49ers’ Kyle Shanahan suffers horrific injuries...,https://nypost.com/2026/07/25/us-news/49ers-co...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)