## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-20-03-58 +0000,nyt,"Unusual Greenpeace Lawsuit May Proceed, Dutch ...",https://www.nytimes.com/2026/06/03/climate/gre...
1,2026-06-03-20-02-00 +0000,wsj,"Energy Costs Continue to Feed Inflation, Fed’s...",https://www.wsj.com/economy/central-banking/en...
2,2026-06-03-19-59-37 +0000,wapo,"Iranian attack leaves 1 dead, dozens injured i...",https://www.washingtonpost.com/world/2026/06/0...
3,2026-06-03-19-59-00 +0000,wsj,Precious Metals Slide as Dollar Gets Stronger,https://www.wsj.com/finance/commodities-future...
4,2026-06-03-19-56-51 +0000,nyt,Iran War Live Updates: Iran Attacks Gulf Natio...,https://www.nytimes.com/live/2026/06/03/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
72        trump     41
48          new     24
149  california     20
29         iran     17
111          he     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
279,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,134
82,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...,111
335,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,107
180,2026-06-03-11-03-00 +0000,wsj,Trump’s choice of Bill Pulte as his top intell...,https://www.wsj.com/politics/pulte-pick-shows-...,95
138,2026-06-03-14-17-36 +0000,nyt,"Out of Time to Delay, House to Vote on Trump’s...",https://www.nytimes.com/2026/06/03/us/politics...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
279,134,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
204,81,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
4,69,2026-06-03-19-56-51 +0000,nyt,Iran War Live Updates: Iran Attacks Gulf Natio...,https://www.nytimes.com/live/2026/06/03/world/...
82,62,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...
261,57,2026-06-03-02-29-59 +0000,cbc,CBS News fires veteran 60 Minutes corresponden...,https://www.cbc.ca/news/world/scott-pelley-fir...
81,56,2026-06-03-17-06-25 +0000,cbc,Ukrainian drones hit St. Petersburg oil termin...,https://www.cbc.ca/news/world/ukraine-drones-s...
281,47,2026-06-03-00-43-22 +0000,nypost,US carries out ‘self-defense’ strikes against ...,https://nypost.com/2026/06/02/world-news/us-ca...
294,43,2026-06-02-23-38-53 +0000,nypost,DOJ probing George Santos over insider trading...,https://nypost.com/2026/06/02/us-news/doj-prob...
223,39,2026-06-03-07-39-32 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
40,35,2026-06-03-18-30-21 +0000,nypost,Idaho murder victim’s parents reveal heartbrea...,https://nypost.com/2026/06/03/us-news/idaho-mu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)