## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-09-19-13-18 +0000,nypost,NJ ex-fireman ‘ready for war’ when he launched...,https://nypost.com/2026/05/09/us-news/nj-ex-fi...
1,2026-05-09-19-09-31 +0000,startribune,Three Democrats battle for endorsement to repl...,https://www.startribune.com/second-district-de...
2,2026-05-09-19-08-45 +0000,bbc,What the election results show us in maps and ...,https://www.bbc.com/news/articles/c0ljrp76ywxo...
3,2026-05-09-19-04-31 +0000,nypost,"Kenyan conservationists reintroduce rare, crit...",https://nypost.com/2026/05/09/world-news/kenya...
4,2026-05-09-18-57-43 +0000,bbc,Election results at a glance,https://www.bbc.com/news/articles/cvgz155y9exo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
270  trump     21
46     new     17
71    iran     14
152  court     13
4      war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
203,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...,62
167,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...,61
96,2026-05-09-11-38-19 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...,57
138,2026-05-09-08-26-02 +0000,nypost,"Putin attends tiny WW2 victory parade, strippe...",https://nypost.com/2026/05/09/world-news/putin...,56
175,2026-05-09-00-05-00 +0000,wsj,President Trump and top aides are pressuring R...,https://www.wsj.com/politics/policy/trumps-tea...,51

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
203,62,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...
167,61,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
96,57,2026-05-09-11-38-19 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...
184,50,2026-05-08-23-12-00 +0000,wsj,Trump has signed off on a plan to fire FDA Com...,https://www.wsj.com/health/healthcare/trump-pl...
93,41,2026-05-09-12-00-00 +0000,nypost,‘Patient Zero’ in deadly hantavirus cruise shi...,https://nypost.com/2026/05/09/world-news/hanta...
68,35,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
28,32,2026-05-09-16-58-07 +0000,nypost,LA man who killed police cadet in wrong-way cr...,https://nypost.com/2026/05/09/us-news/la-man-w...
222,32,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...
175,28,2026-05-09-00-05-00 +0000,wsj,President Trump and top aides are pressuring R...,https://www.wsj.com/politics/policy/trumps-tea...
22,26,2026-05-09-17-28-59 +0000,bbc,'We just hit somebody' - Frontier Airlines pla...,https://www.bbc.com/news/articles/c5y95782wyko...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)