## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-08-13-17-17 +0000,nyt,Many Russians in No Mood for Celebration on Kr...,https://www.nytimes.com/2026/05/08/world/europ...
1,2026-05-08-13-17-15 +0000,bbc,Russia and Ukraine accuse each other of breach...,https://www.bbc.com/news/articles/c202zn5gg0lo...
2,2026-05-08-13-15-14 +0000,bbc,Huge plumes of ash rise as Indonesia's Mount D...,https://www.bbc.com/news/videos/c5y7gmmp8pdo?a...
3,2026-05-08-13-14-00 +0000,bbc,"Labour says it's lost Senedd election, and Elu...",https://www.bbc.com/news/articles/cdrpxvz61vko...
4,2026-05-08-13-13-46 +0000,bbc,Tough election results hurt but don't weaken m...,https://www.bbc.com/news/articles/cz62dwe30wdo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
137       trump     44
57         iran     31
58          war     22
205  hantavirus     18
307       court     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...,134
306,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...,131
212,2026-05-07-23-02-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,130
202,2026-05-07-23-51-58 +0000,nypost,Trump downplays US-Iran attacks as ‘love tap’ ...,https://nypost.com/2026/05/07/world-news/trump...,120
146,2026-05-08-05-57-08 +0000,bbc,Trump says US-Iran ceasefire still in place af...,https://www.bbc.com/news/articles/c626zyywxjno...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,134,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...
6,107,2026-05-08-13-12-34 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...
230,70,2026-05-07-22-08-00 +0000,wsj,The Centers for Disease Control and Prevention...,https://www.wsj.com/politics/policy/cdc-coordi...
56,68,2026-05-08-11-43-45 +0000,nypost,UK PM Keir Starmer says he won’t resign after ...,https://nypost.com/2026/05/08/world-news/uk-pr...
324,54,2026-05-07-18-37-27 +0000,nypost,White House lashes out at ‘Star Wars’ actor Ma...,https://nypost.com/2026/05/07/us-news/white-ho...
231,52,2026-05-07-22-06-55 +0000,nypost,US launches ‘self-defense’ strikes after Iran ...,https://nypost.com/2026/05/07/us-news/us-launc...
277,49,2026-05-07-20-52-12 +0000,nypost,Argentina will start testing rats for hantavir...,https://nypost.com/2026/05/07/world-news/argen...
374,46,2026-05-07-15-16-51 +0000,nypost,McDonald’s posts strong earnings — but viral C...,https://nypost.com/2026/05/07/business/mcdonal...
315,38,2026-05-07-18-56-26 +0000,nypost,Trump could revive ‘Project Freedom’ to reopen...,https://nypost.com/2026/05/07/us-news/trump-co...
384,36,2026-05-07-13-48-17 +0000,nyt,Starmer Braces for Local Election Losses Amid ...,https://www.nytimes.com/2026/05/07/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)