## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-14-45-43 +0000,nyt,"In Texas, Talarico’s Strength in Senate Polls ...",https://www.nytimes.com/2026/10/03/us/politics...
1,2026-10-03-14-44-45 +0000,startribune,Live: P.J. Fleck already crowd surfing as Goph...,https://www.startribune.com/minnesota-gophers-...
2,2026-10-03-14-37-31 +0000,nyt,American High School Students Are Selling Guns...,https://www.nytimes.com/2026/10/03/world/ameri...
3,2026-10-03-14-34-08 +0000,nyt,Coast Guard Says It Stopped Ships Carrying Fue...,https://www.nytimes.com/2026/10/02/world/ameri...
4,2026-10-03-14-29-39 +0000,wapo,Trump announces plan to send $90 payments to m...,https://www.washingtonpost.com/politics/2026/1...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
32     trump     35
39  flydubai     17
41     pilot     14
58       new     13
50       was     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
239,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...,93
43,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...,87
154,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...,86
238,2026-10-02-20-26-03 +0000,nypost,Trump says ‘Cornell 7’ frat boys ‘won’t get a ...,https://nypost.com/2026/10/02/us-news/trump-sa...,76
142,2026-10-03-00-59-50 +0000,chitri,FlyDubai co-pilot who nearly crashed plane was...,https://www.chicagotribune.com/2026/10/02/flyd...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
239,93,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
43,87,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...
124,69,2026-10-03-03-48-51 +0000,nypost,Christa Pike thought her arm would ‘burst open...,https://nypost.com/2026/10/02/us-news/christa-...
229,67,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
332,58,2026-10-02-15-21-30 +0000,cbc,G7 nations agree to release 100 million barrel...,https://www.cbc.ca/news/business/g7-trump-dies...
320,46,2026-10-02-15-50-14 +0000,nyt,Soft Jobs Report Boosts Market Bets Fed Will S...,https://www.nytimes.com/2026/10/02/business/ec...
154,46,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...
238,41,2026-10-02-20-26-03 +0000,nypost,Trump says ‘Cornell 7’ frat boys ‘won’t get a ...,https://nypost.com/2026/10/02/us-news/trump-sa...
10,37,2026-10-03-14-00-00 +0000,nypost,Iconic California company scoops up empty Yama...,https://nypost.com/2026/10/03/business/disney-...
122,36,2026-10-03-03-57-42 +0000,nypost,Illegal immigrant with long rap sheet arrested...,https://nypost.com/2026/10/02/us-news/brewster...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)