## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-20-54-10 +0000,chitri,US stocks slip after the Fed hikes interest ra...,https://www.chicagotribune.com/2026/09/16/us-s...
1,2026-09-16-20-52-07 +0000,nyt,The Canaduropean Union?,https://www.nytimes.com/2026/09/16/world/canad...
2,2026-09-16-20-51-27 +0000,chitri,"Dr. Nicole Saphier, President Trump’s 3rd surg...",https://www.chicagotribune.com/2026/09/16/dr-n...
3,2026-09-16-20-49-18 +0000,nypost,Moment SUV smashes into LA Metro bus triggerin...,https://nypost.com/2026/09/16/us-news/exclusiv...
4,2026-09-16-20-46-32 +0000,nypost,Sicko worker at upstate NY Santa’s Workshop th...,https://nypost.com/2026/09/16/us-news/sicko-up...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2258/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
16    trump     38
2       fed     23
614      ai     21
360  canada     16
644     new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
156,2026-09-16-15-59-54 +0000,nyt,Trump’s Latest Threats Loom Over Fed’s Interes...,https://www.nytimes.com/2026/09/16/business/ec...,97
101,2026-09-16-18-13-13 +0000,nypost,EU boss proposes making Canada associate membe...,https://nypost.com/2026/09/16/world-news/eu-bo...,94
190,2026-09-16-14-19-58 +0000,chitri,Trump administration hits South Africa with ne...,https://www.chicagotribune.com/2026/09/16/trum...,87
98,2026-09-16-18-17-18 +0000,chitri,First Fed rate hike in 3 years may push borrow...,https://www.chicagotribune.com/2026/09/16/fede...,86
67,2026-09-16-19-12-48 +0000,bbc,Trump's Chief of Staff Susie Wiles announces s...,https://www.bbc.co.uk/news/articles/c6j9xrx80e...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
156,97,2026-09-16-15-59-54 +0000,nyt,Trump’s Latest Threats Loom Over Fed’s Interes...,https://www.nytimes.com/2026/09/16/business/ec...
236,81,2026-09-16-11-25-05 +0000,chitri,US-Canada trade war further taxes small busine...,https://www.chicagotribune.com/2026/09/16/us-c...
45,79,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
184,59,2026-09-16-14-43-23 +0000,nyt,News Helicopter Crash and Bus Accident in Los ...,https://www.nytimes.com/2026/09/15/us/los-ange...
398,57,2026-09-15-22-16-14 +0000,nypost,Houthis are the world’s biggest new threat to ...,https://nypost.com/2026/09/15/world-news/houth...
394,56,2026-09-15-22-40-00 +0000,nypost,Meet Anthropic CEO Dario Amodei’s handpicked s...,https://nypost.com/2026/09/15/business/anthrop...
59,55,2026-09-16-19-21-00 +0000,wsj,The Fed voted unanimously to raise rates for t...,https://www.wsj.com/economy/central-banking/fe...
275,52,2026-09-16-10-00-00 +0000,wsj,Security gaps at Utah Valley University last S...,https://www.wsj.com/us-news/charlie-kirks-wido...
114,43,2026-09-16-17-27-09 +0000,chitri,Fencing goes up around the main Kennedy Center...,https://www.chicagotribune.com/2026/09/16/kenn...
2,40,2026-09-16-20-51-27 +0000,chitri,"Dr. Nicole Saphier, President Trump’s 3rd surg...",https://www.chicagotribune.com/2026/09/16/dr-n...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)