## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-05-17-44-00 +0000,wapo,U.S. military says it hit 3 Iranian tankers af...,https://www.washingtonpost.com/world/2026/09/0...
1,2026-09-05-17-41-27 +0000,nypost,Hijacking history: Woke teachers offer twisted...,https://nypost.com/2026/09/05/us-news/schools-...
2,2026-09-05-17-38-39 +0000,nyt,Trump Officials Draft Plan to Pay At-Home Pare...,https://www.nytimes.com/2026/09/05/us/politics...
3,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...
4,2026-09-05-17-28-21 +0000,chitri,Justin Ishbia unveils his plan for a new White...,https://www.chicagotribune.com/2026/09/05/just...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18     trump     35
135   clancy     19
38       new     18
134  lindsay     18
303      was     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
281,2026-09-04-19-09-01 +0000,nypost,"New York, New Jersey Hasidic leaders meet Trum...",https://nypost.com/2026/09/04/us-news/new-york...,94
47,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...,93
278,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...,91
190,2026-09-04-22-58-11 +0000,latimes,Judge again halts Postal Service mail ballot p...,https://www.latimes.com/politics/story/2026-09...,88
241,2026-09-04-20-44-26 +0000,bbc,Watch: Inside court as judge declares a mistri...,https://www.bbc.co.uk/news/videos/c2l8z4rx5xro...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
281,94,2026-09-04-19-09-01 +0000,nypost,"New York, New Jersey Hasidic leaders meet Trum...",https://nypost.com/2026/09/04/us-news/new-york...
241,81,2026-09-04-20-44-26 +0000,bbc,Watch: Inside court as judge declares a mistri...,https://www.bbc.co.uk/news/videos/c2l8z4rx5xro...
57,55,2026-09-05-14-03-43 +0000,chitri,US military hits 3 Iranian oil tankers after s...,https://www.chicagotribune.com/2026/09/05/us-m...
250,48,2026-09-04-20-33-00 +0000,wsj,Democrats criticized Sen. John Fetterman after...,https://www.wsj.com/politics/policy/democrats-...
221,46,2026-09-04-21-09-00 +0000,wsj,The Supreme Court cleared the way for politica...,https://www.wsj.com/politics/policy/supreme-co...
103,45,2026-09-05-09-30-00 +0000,wsj,How do you view the major components of Americ...,https://www.wsj.com/politics/young-people-see-...
61,42,2026-09-05-13-10-33 +0000,nypost,Putin declares 3-day cease-fire in Ukraine war...,https://nypost.com/2026/09/05/world-news/putin...
91,41,2026-09-05-10-00-00 +0000,wapo,Her work was key to a landmark experiment. She...,https://www.washingtonpost.com/obituaries/2026...
251,35,2026-09-04-20-30-00 +0000,wapo,"Trump says he will spend some, not all, super ...",https://www.washingtonpost.com/politics/2026/0...
217,33,2026-09-04-21-18-00 +0000,wsj,U.S. Stocks Fall as Robust August Jobs Data Sp...,https://www.wsj.com/finance/investing/u-s-stoc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)