## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-31-09-46-26 +0000,nyt,Live Updates: Spanish Leader Rushes to Ceuta A...,https://www.nytimes.com/live/2026/07/31/world/...
1,2026-07-31-09-45-00 +0000,wsj,When HPE’s Antonio Neri Leaves His Team Alone,https://www.wsj.com/business/when-hpes-antonio...
2,2026-07-31-09-44-48 +0000,bbc,AC Milan and Italy great Baresi dies aged 66,https://www.bbc.co.uk/sport/football/articles/...
3,2026-07-31-09-43-09 +0000,bbc,BP puts North Sea business up for sale,https://www.bbc.co.uk/news/articles/c62q7w003l...
4,2026-07-31-09-38-51 +0000,nyt,Iran Says It Targeted U.S. Military in Kuwait ...,https://www.nytimes.com/2026/07/31/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
49   trump     41
31    iran     20
334    new     17
171    war     14
67      ai     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
219,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...,138
154,2026-07-30-22-29-53 +0000,nypost,Cease-fire Trump wants must begin with Iran — ...,https://nypost.com/2026/07/30/us-news/cease-fi...,108
162,2026-07-30-22-18-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,99
356,2026-07-30-13-14-00 +0000,wsj,Many business leaders are getting used to the ...,https://www.wsj.com/economy/trade/are-tariffs-...,90
303,2026-07-30-16-19-08 +0000,bbc,Burnham says he told Trump UK will be pragmati...,https://www.bbc.co.uk/news/articles/c70gr75xzg...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
219,138,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...
162,86,2026-07-30-22-18-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
54,67,2026-07-31-08-02-28 +0000,nypost,At least 18 migrants dead as thousands breache...,https://nypost.com/2026/07/31/world-news/at-le...
355,63,2026-07-30-13-15-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
142,54,2026-07-30-23-07-01 +0000,chitri,European nations vow World Cup boycott and Nor...,https://www.chicagotribune.com/2026/07/30/euro...
314,49,2026-07-30-16-00-00 +0000,wsj,Mortgage rates jumped to their highest level i...,https://www.wsj.com/economy/housing/mortgage-r...
245,48,2026-07-30-18-41-32 +0000,nypost,Meta shares tumble 9% in record losing streak ...,https://nypost.com/2026/07/30/business/metas-r...
154,47,2026-07-30-22-29-53 +0000,nypost,Cease-fire Trump wants must begin with Iran — ...,https://nypost.com/2026/07/30/us-news/cease-fi...
116,46,2026-07-31-01-00-00 +0000,wsj,Dr. Anthony Fauci’s lawyers advised him to inv...,https://www.wsj.com/politics/faucis-turn-from-...
210,46,2026-07-30-20-41-52 +0000,startribune,New allegations of inappropriate behavior surf...,https://www.startribune.com/st-paul-mayor-her-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)