## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-07-41-00 +0000,wsj,Heineken Upbeat for Full Year After Volumes Pi...,https://www.wsj.com/business/earnings/heineken...
1,2026-08-05-07-36-55 +0000,bbc,Afghan boxer arrives at Greek court in connect...,https://www.bbc.co.uk/news/articles/cq56qejll6...
2,2026-08-05-07-34-49 +0000,nypost,Russian missile and drone barrage in Ukrainian...,https://nypost.com/2026/08/05/world-news/russi...
3,2026-08-05-07-34-00 +0000,wsj,Coca-Cola HBC Net Profit Rises on Higher Volumes,https://www.wsj.com/business/earnings/coca-col...
4,2026-08-05-07-26-44 +0000,nyt,John James Wins Republican Nomination for Mich...,https://www.nytimes.com/2026/08/04/us/election...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2698/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
68        trump     41
40     michigan     27
215         new     27
153  democratic     24
115     primary     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
28,2026-08-05-05-44-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...,153
266,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...,142
405,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,140
383,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...,126
45,2026-08-05-03-44-30 +0000,bbc,Trump says Iran will be 'hit very hard' if Hor...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
28,153,2026-08-05-05-44-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...
405,140,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...
212,74,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
412,70,2026-08-04-10-00-00 +0000,latimes,Is Los Angeles the world's best biking city? H...,https://www.latimes.com/lifestyle/story/2026-0...
266,65,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
48,63,2026-08-05-03-26-23 +0000,nypost,Trump reacts to arrest of heavily armed suspec...,https://nypost.com/2026/08/04/us-news/trump-re...
218,58,2026-08-04-20-30-00 +0000,wsj,"What’s Next for Democrats? Join a real-time, ...",https://www.wsj.com/politics/elections/live-q-...
84,56,2026-08-05-01-06-38 +0000,nypost,Rep. Wesley Bell holds off ex-‘Squad’ member C...,https://nypost.com/2026/08/04/us-news/rep-wesl...
45,51,2026-08-05-03-44-30 +0000,bbc,Trump says Iran will be 'hit very hard' if Hor...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
111,49,2026-08-05-00-15-00 +0000,wsj,The Trump administration is revoking the visa ...,https://www.wsj.com/politics/policy/u-s-revoke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)