## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-28-07-53-20 +0000,bbc,Luxury cruise passengers stranded in Cambodia ...,https://www.bbc.co.uk/news/articles/cwj342k62e...
1,2026-10-28-07-51-00 +0000,wsj,Oil Prices Rise as Houthi Militants Target Sau...,https://www.wsj.com/world/middle-east/oil-pric...
2,2026-10-28-07-49-28 +0000,nyt,How Pastors Mobilize Communities in Congo’s Fi...,https://www.nytimes.com/2026/10/23/world/afric...
3,2026-10-28-07-48-48 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/28/world/...
4,2026-10-28-07-44-36 +0000,nyt,Rivals in Israel Election Strike Tone of Trium...,https://www.nytimes.com/live/2026/10/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2387/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
28   election     30
309     trump     28
27     israel     20
150       out     12
312      will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
349,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...,98
48,2026-10-28-04-00-03 +0000,startribune,Exit polls suggest no clear winner in Israel's...,https://www.startribune.com/voters-in-israel-w...,96
188,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,95
57,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...,84
73,2026-10-28-02-09-11 +0000,bbc,Israeli exit polls suggest no clear winner in ...,https://www.bbc.co.uk/news/articles/cq1kdgxw30...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
349,98,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...
57,84,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...
314,55,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
384,54,2026-10-27-10-00-00 +0000,wsj,Fed Chairman Kevin Warsh wants to stop preview...,https://www.wsj.com/economy/central-banking/ke...
114,54,2026-10-27-23-40-43 +0000,nypost,Ex-FBI official weeps as she appears in court ...,https://nypost.com/2026/10/27/us-news/ex-fbi-o...
395,51,2026-10-27-09-21-34 +0000,wsj,"Stock Market News, Oct. 27, 2026: Tech Stocks ...",https://www.wsj.com/livecoverage/stock-market-...
54,46,2026-10-28-03-27-41 +0000,nypost,LAPD Chief Jim McDonnell slams Nithya Raman’s ...,https://nypost.com/2026/10/27/us-news/lapd-chi...
308,40,2026-10-27-14-18-59 +0000,nypost,Feds raid billionaire’s Beverly Hills mansion ...,https://nypost.com/2026/10/27/us-news/eric-swa...
27,38,2026-10-28-06-27-12 +0000,nypost,Son read dad last rites before knifing him in ...,https://nypost.com/2026/10/28/us-news/missouri...
375,37,2026-10-27-10-00-22 +0000,chitri,"Clocks fall back this weekend, reigniting deba...",https://www.chicagotribune.com/2026/10/27/dayl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)