## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-13-17-56 +0000,bbc,Virtual interviews don't show bosses your pers...,https://www.bbc.co.uk/news/articles/c4g4dkr40d...
1,2026-07-30-13-17-23 +0000,nypost,"Boy, 5, suddenly dies on family vacation just ...",https://nypost.com/2026/07/30/us-news/boy-5-su...
2,2026-07-30-13-15-22 +0000,nyt,DOJ Seeks to Use Court to Deport Mother of Con...,https://www.nytimes.com/2026/07/30/us/doj-isis...
3,2026-07-30-13-15-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
4,2026-07-30-13-14-00 +0000,wsj,Many business leaders are getting used to the ...,https://www.wsj.com/economy/trade/are-tariffs-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2345/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
59   trump     30
66    iran     27
240    new     23
101    fed     21
67     war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
209,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,113
186,2026-07-30-02-28-39 +0000,nyt,"U.S. Strikes Iran Again, as Trump Encounters a...",https://www.nytimes.com/2026/07/29/us/trump-ir...,92
30,2026-07-30-12-41-03 +0000,nyt,Fed’s Preferred Inflation Gauge Eased During P...,https://www.nytimes.com/2026/07/30/business/fe...,90
302,2026-07-29-20-21-56 +0000,nypost,US has used up two-thirds of its critical Patr...,https://nypost.com/2026/07/29/world-news/us-ha...,85
310,2026-07-29-20-10-38 +0000,nypost,Trump and Netanyahu discussed ‘big three’ op...,https://nypost.com/2026/07/29/us-news/trump-an...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
209,113,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
144,82,2026-07-30-09-00-00 +0000,wsj,Capital Account: Fed Chairman Kevin Warsh says...,https://www.wsj.com/economy/central-banking/th...
188,75,2026-07-30-02-10-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...
351,69,2026-07-29-17-51-00 +0000,wsj,Dr. Anthony Fauci invoked the Fifth Amendment ...,https://www.wsj.com/politics/policy/anthony-fa...
3,63,2026-07-30-13-15-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
154,49,2026-07-30-08-01-55 +0000,nypost,School employee accused of secretly filming 12...,https://nypost.com/2026/07/30/us-news/maryland...
96,46,2026-07-30-10-30-00 +0000,wsj,"U.S. Treasury Yields Rise, 30-Year Yield at 19...",https://www.wsj.com/finance/currencies/foreign...
77,43,2026-07-30-11-00-00 +0000,nypost,How NYC brothers’ $400M summer camp empire fel...,https://nypost.com/2026/07/30/us-news/how-nyc-...
169,43,2026-07-30-05-11-37 +0000,bbc,My son's not just a champion South African swi...,https://www.bbc.co.uk/news/articles/cvgl59egq5...
329,43,2026-07-29-18-43-17 +0000,latimes,Viral California teen lifeguard rescue capture...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)