## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-02-17-08-44 +0000,nyt,Mexican Governor Accused by U.S. of Aiding Dru...,https://www.nytimes.com/2026/05/02/world/ameri...
1,2026-05-02-17-08-27 +0000,nypost,"New School strips funding for Hillel chapter, ...",https://nypost.com/2026/05/02/us-news/new-scho...
2,2026-05-02-16-57-00 +0000,wsj,Spirit Airlines Is Shutting Down. Here’s What ...,https://www.wsj.com/business/airlines/if-you-b...
3,2026-05-02-16-55-13 +0000,nyt,Everyone Who Could Be in Trump’s ‘Garden of He...,https://www.nytimes.com/2026/05/02/us/politics...
4,2026-05-02-16-54-14 +0000,latimes,"California, Arizona and Nevada announce new wa...",https://www.latimes.com/environment/story/2026...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2525/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
28      trump     42
150      iran     28
151       war     19
19     spirit     13
20   airlines     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...,135
17,2026-05-02-16-29-06 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,125
133,2026-05-02-01-30-23 +0000,nypost,Trump administration pulling 5K troops out of ...,https://nypost.com/2026/05/01/world-news/trump...,118
174,2026-05-01-22-00-01 +0000,nyt,Trump Tells Congress Why He Doesn’t Need Its A...,https://www.nytimes.com/2026/05/01/us/politics...,116
56,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,135,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...
239,49,2026-05-01-19-21-00 +0000,wsj,Trump’s new Air Force One will arrive this sum...,https://www.wsj.com/politics/national-security...
72,48,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
251,41,2026-05-01-18-43-04 +0000,nypost,"Chirayu Rana, ex-JPMorgan staffer accused of ‘...",https://nypost.com/2026/05/01/business/male-ex...
17,36,2026-05-02-16-29-06 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...
108,32,2026-05-02-09-00-00 +0000,wapo,You could be losing thousands every time you c...,https://www.washingtonpost.com/business/2026/0...
137,32,2026-05-02-01-00-00 +0000,wsj,California voters are heading toward a stark c...,https://www.wsj.com/politics/elections/califor...
109,31,2026-05-02-08-58-09 +0000,nypost,US warns shipping firms they could face sancti...,https://nypost.com/2026/05/02/world-news/us-wa...
82,30,2026-05-02-10-58-03 +0000,nypost,Humpback whale ‘Timmy’ released in the North S...,https://nypost.com/2026/05/02/world-news/timmy...
10,28,2026-05-02-16-40-09 +0000,nypost,Wigging out: DMV forces ultra-Orthodox NYC wom...,https://nypost.com/2026/05/02/us-news/dmv-forc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)