## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-22-55-11 +0000,nypost,Bomb threat at California Montessori school pr...,https://nypost.com/2026/10/06/us-news/californ...
1,2026-10-06-22-53-52 +0000,nypost,Hochul holds event with AOC in campaign’s fina...,https://nypost.com/2026/10/06/us-news/hochul-h...
2,2026-10-06-22-51-13 +0000,nypost,Florida teen strangled to death after shirt ge...,https://nypost.com/2026/10/06/us-news/florida-...
3,2026-10-06-22-49-07 +0000,nypost,Sister of Caleb Flynn’s slain wife torches kil...,https://nypost.com/2026/10/06/us-news/sister-o...
4,2026-10-06-22-48-56 +0000,nyt,How a Maryland Shipyard Turned Into a Squabble...,https://www.nytimes.com/2026/10/06/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2360/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
48    trump     43
218     new     18
479     out     15
191  russia     14
369  france     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
149,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,147
301,2026-10-06-13-12-31 +0000,nypost,White House rips ‘media freakout’ over Trump s...,https://nypost.com/2026/10/06/us-news/gavin-ne...,108
123,2026-10-06-20-15-31 +0000,bbc,White House defends Trump comment to let Iran ...,https://www.bbc.co.uk/news/articles/c6r7yn8pkn...,105
283,2026-10-06-14-03-23 +0000,nyt,Trump Suggests Iran Could ‘Take Out’ L.A. or S...,https://www.nytimes.com/2026/10/06/world/asia/...,102
430,2026-10-06-03-17-28 +0000,latimes,Trump suggests letting Iran 'take out' Los Ang...,https://www.latimes.com/california/story/2026-...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
149,147,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
454,70,2026-10-06-01-00-00 +0000,wsj,Republicans are binding their Senate hopes on ...,https://www.wsj.com/politics/elections/rjohn-s...
301,65,2026-10-06-13-12-31 +0000,nypost,White House rips ‘media freakout’ over Trump s...,https://nypost.com/2026/10/06/us-news/gavin-ne...
63,64,2026-10-06-21-22-22 +0000,bbc,Watch: Riot police clash with school protester...,https://www.bbc.co.uk/news/videos/cwm26078pkep...
31,62,2026-10-06-22-00-43 +0000,bbc,US death row inmate Christa Pike awake and spe...,https://www.bbc.co.uk/news/articles/c8kgezxn54...
237,58,2026-10-06-16-10-20 +0000,nypost,Kenya confirms first Ebola case imported from ...,https://nypost.com/2026/10/06/world-news/kenya...
60,53,2026-10-06-21-29-32 +0000,missionlocal,‘We need a jingle’: Will voters know the ‘Yes-...,https://missionlocal.org/2026/10/california-bi...
72,53,2026-10-06-21-12-30 +0000,nyt,S&P 500 Hits Record High Amid Rising Interest ...,https://www.nytimes.com/2026/10/06/business/st...
319,50,2026-10-06-12-16-57 +0000,chitri,Ukraine fires nearly 900 drones at Russia as K...,https://www.chicagotribune.com/2026/10/06/ukra...
61,48,2026-10-06-21-27-59 +0000,bbc,What the Paramount and Warner Bros deal means ...,https://www.bbc.co.uk/news/videos/cq70p4llze5j...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)