## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-00-51-38 +0000,nyt,Could El Salvador’s Bukele Be Haiti’s Savior?,https://www.nytimes.com/2026/10/30/world/ameri...
1,2026-10-31-00-50-07 +0000,nyt,Judge Blocks Expediting Migrant Children’s Asy...,https://www.nytimes.com/2026/10/30/us/politics...
2,2026-10-31-00-49-11 +0000,nypost,High school basketball coach arrested after tr...,https://nypost.com/2026/10/30/sports/high-scho...
3,2026-10-31-00-45-20 +0000,nypost,Aspiring NYPD officer killed by twice-removed ...,https://nypost.com/2026/10/30/us-news/aspiring...
4,2026-10-31-00-40-58 +0000,startribune,Live: Scores and updates from Class 6A first-r...,https://www.startribune.com/minnesota-class-6a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
171  election     27
164     trump     26
534   binance     17
215       new     17
135     court     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
414,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...,120
296,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,89
268,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,80
163,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,79
33,2026-10-30-23-26-03 +0000,missionlocal,"Election Extra! Gary Locke, first Chinese-Amer...",https://missionlocal.org/2026/10/gary-locke-ba...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
414,120,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...
296,89,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
158,75,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
350,64,2026-10-30-09-33-51 +0000,bbc,Crypto giant Binance hit by $6.3bn hack suspec...,https://www.bbc.co.uk/news/articles/cwg7xp8kx4...
322,55,2026-10-30-10-50-00 +0000,wsj,Bayer Shares Rise After Win in First Roundup T...,https://www.wsj.com/us-news/law/bayer-wins-fir...
359,52,2026-10-30-09-01-01 +0000,nypost,"Canadian CEO, daughters shot and wife attacked...",https://nypost.com/2026/10/30/world-news/canad...
61,44,2026-10-30-22-10-55 +0000,nypost,NYC home health aide charged in death of 81-ye...,https://nypost.com/2026/10/30/us-news/nyc-home...
394,43,2026-10-30-03-32-44 +0000,bbc,New York police will now investigate Cornell s...,https://www.bbc.co.uk/news/articles/cmwy42j9we...
285,40,2026-10-30-12-04-57 +0000,nypost,Disgraced ex-Prince Andrew under fresh investi...,https://nypost.com/2026/10/30/world-news/disgr...
352,40,2026-10-30-09-10-12 +0000,nypost,"Nancy Pelosi slams Mamdani, El-Sayed over ‘wro...",https://nypost.com/2026/10/30/us-news/nancy-pe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)