## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-19-17-10 +0000,nypost,Moped-riding goons shoot NYC teen dead outside...,https://nypost.com/2026/06/07/us-news/moped-ri...
1,2026-06-07-19-06-53 +0000,bbc,Israel strikes Beirut suburb days after US-bro...,https://www.bbc.com/news/articles/c0qyevk8139o...
2,2026-06-07-19-01-53 +0000,nypost,Former Gotham restaurant site in Manhattan has...,https://nypost.com/2026/06/07/business/former-...
3,2026-06-07-19-00-38 +0000,nypost,Hakeem Jeffries dodges key questions about Gra...,https://nypost.com/2026/06/07/us-news/hakeem-j...
4,2026-06-07-18-51-34 +0000,nypost,Long Island bishop using Knicks’ NBA Finals ru...,https://nypost.com/2026/06/07/us-news/long-isl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
71   trump     18
198  world     11
199    cup     10
243   iran     10
21     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...,59
8,2026-06-07-18-48-01 +0000,latimes,President Trump storms off NBC interview after...,https://www.latimes.com/california/story/2026-...,55
54,2026-06-07-15-48-19 +0000,nypost,Trump storms off ‘Meet The Press’ interview af...,https://nypost.com/2026/06/07/us-news/trump-st...,50
64,2026-06-07-15-13-43 +0000,nyt,Trump Defends Compensation Fund and Iran War i...,https://www.nytimes.com/2026/06/07/us/politics...,48
113,2026-06-07-09-02-06 +0000,nyt,Trump Says Iran Has Made a ‘Big’ Nuclear Promi...,https://www.nytimes.com/2026/06/07/us/politics...,47

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,59,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
8,55,2026-06-07-18-48-01 +0000,latimes,President Trump storms off NBC interview after...,https://www.latimes.com/california/story/2026-...
71,44,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...
121,32,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
60,32,2026-06-07-15-21-34 +0000,nypost,Bombshell LA mayor’s race projection changes e...,https://nypost.com/2026/06/07/us-news/la-mayor...
37,30,2026-06-07-17-09-20 +0000,nypost,New Espaillat ad attacks Mamdani-backed foe fo...,https://nypost.com/2026/06/07/us-news/new-espa...
32,28,2026-06-07-17-20-43 +0000,nypost,Filmmakers claim they’ve caught America’s Loch...,https://nypost.com/2026/06/07/us-news/filmmake...
57,27,2026-06-07-15-37-00 +0000,wsj,"OPEC, Allies Pledge Oil-Output Hike Even as Mi...",https://www.wsj.com/business/energy-oil/opec-a...
171,26,2026-06-06-21-23-03 +0000,bbc,Lebanese general among three soldiers killed i...,https://www.bbc.com/news/articles/cj0g8jymg92o...
72,25,2026-06-07-14-12-39 +0000,nypost,Russian drone hits nuclear fuel storage facili...,https://nypost.com/2026/06/07/world-news/russi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)