## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-21-33-02 +0000,nyt,Federal Citizenship Data Tool Cannot Be Used t...,https://www.nytimes.com/2026/06/22/us/politics...
1,2026-06-22-21-33-00 +0000,wsj,U.S. Allows Iran to Sell Oil in Dollars for Fi...,https://www.wsj.com/world/middle-east/vance-sa...
2,2026-06-22-21-31-10 +0000,nyt,Keir Starmer Resigns as UK Prime Minister,https://www.nytimes.com/2026/06/22/world/europ...
3,2026-06-22-21-31-00 +0000,wsj,Domino’s Pizza Picks Insider as New CEO,https://www.wsj.com/us-news/dominos-pizza-pick...
4,2026-06-22-21-30-54 +0000,nypost,Florida church worker arrested for allegedly r...,https://nypost.com/2026/06/22/us-news/florida-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
10       iran     24
18    starmer     20
27        new     18
22   minister     16
163      will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
219,2026-06-22-12-51-52 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,97
272,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...,86
72,2026-06-22-19-44-27 +0000,bbc,Starmer quits as Labour leader and paves way f...,https://www.bbc.com/news/articles/cdxd00lg599o...,82
253,2026-06-22-10-09-12 +0000,cbc,U.K. Prime Minister Keir Starmer announces res...,https://www.cbc.ca/news/world/livestory/starme...,79
237,2026-06-22-11-01-00 +0000,wsj,U.K. Prime Minister Keir Starmer Quits After P...,https://www.wsj.com/world/uk/u-k-prime-ministe...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
219,97,2026-06-22-12-51-52 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
200,71,2026-06-22-14-10-10 +0000,nypost,US waives Iran oil sanctions for two months in...,https://nypost.com/2026/06/22/world-news/us-wa...
163,58,2026-06-22-15-30-00 +0000,wsj,The Supreme Court is about to decide four case...,https://www.wsj.com/politics/policy/the-suprem...
115,55,2026-06-22-17-38-00 +0000,wsj,Alan Greenspan’s legacy explained: how the Fed...,https://www.wsj.com/economy/central-banking/al...
243,51,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
284,45,2026-06-22-03-48-31 +0000,cbc,Egypt downs New Zealand 3-1 for first World Cu...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
145,42,2026-06-22-16-09-49 +0000,cbc,"Music industry giant Clive Davis, who signed B...",https://www.cbc.ca/news/entertainment/clive-da...
133,36,2026-06-22-16-58-36 +0000,nyt,"Abelardo De La Espriella, Trump-Backed Rightis...",https://www.nytimes.com/2026/06/21/world/ameri...
37,35,2026-06-22-20-47-37 +0000,nyt,Vance Claims Progress in First Day of Iran Talks,https://www.nytimes.com/2026/06/22/world/middl...
213,35,2026-06-22-13-19-59 +0000,nypost,Dad of YouTuber killed alongside Oliver Tree i...,https://nypost.com/2026/06/22/world-news/dad-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)