## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-28-16-55-27 +0000,bbc,Budget 2026: Key points at a glance,https://www.bbc.co.uk/news/articles/c6x2zrjl7k...
1,2026-10-28-16-55-20 +0000,nypost,Two college students missing after going on Ic...,https://nypost.com/2026/10/28/us-news/two-coll...
2,2026-10-28-16-55-04 +0000,nyt,What Does the Cheesecake Factory’s Designer Th...,https://www.nytimes.com/2026/10/28/dining/chee...
3,2026-10-28-16-55-03 +0000,bbc,The one thing that didn't change that will aff...,https://www.bbc.co.uk/news/articles/clydn7r5pn...
4,2026-10-28-16-54-00 +0000,wsj,Retailers Cracked Down on In-Store Theft. Gift...,https://www.wsj.com/business/retail/retailers-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2642/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
21      trump     30
142  election     26
172    israel     20
28       will     17
0      budget     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
90,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...,99
369,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,98
180,2026-10-28-11-08-29 +0000,chitri,Donald Trump’s cure for Republicans’ midterm w...,https://www.chicagotribune.com/2026/10/28/dona...,94
26,2026-10-28-16-34-01 +0000,nyt,Netanyahu Didn’t Win Israel’s Election. But He...,https://www.nytimes.com/2026/10/28/world/middl...,92
269,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
90,99,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...
369,98,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...
336,59,2026-10-27-21-40-20 +0000,chitri,Brazil’s Flávio Bolsonaro and family will get ...,https://www.chicagotribune.com/2026/10/27/braz...
210,55,2026-10-28-10-00-00 +0000,latimes,Your last-minute guide to California governor ...,https://www.latimes.com/california/story/2026-...
61,54,2026-10-28-15-55-02 +0000,nypost,"Civil rights legend Dolores Huerta, who aired ...",https://nypost.com/2026/10/28/us-news/californ...
219,52,2026-10-28-09-57-00 +0000,wsj,Global Government Bond Yields Rise Ahead of Fe...,https://www.wsj.com/finance/investing/u-s-trea...
305,49,2026-10-27-23-40-43 +0000,nypost,Ex-FBI official weeps as she appears in court ...,https://nypost.com/2026/10/27/us-news/ex-fbi-o...
148,49,2026-10-28-13-30-12 +0000,nypost,Hundreds of cruise passengers — including canc...,https://nypost.com/2026/10/28/world-news/hundr...
269,48,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...
193,44,2026-10-28-10-47-00 +0000,wsj,Are Democrats drawing up a new map in the Sout...,https://www.wsj.com/politics/elections/are-dem...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)