## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-19-33-41 +0000,nypost,Karmelo Anthony convicted of fatally stabbing ...,https://nypost.com/2026/06/09/us-news/karmelo-...
1,2026-06-09-19-28-59 +0000,nypost,Labor Dept. watchdog to claw back more than $9...,https://nypost.com/2026/06/09/us-news/labor-de...
2,2026-06-09-19-28-54 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...
3,2026-06-09-19-28-00 +0000,wsj,U.S. Natural Gas Futures Slip in Rangebound Trade,https://www.wsj.com/finance/commodities-future...
4,2026-06-09-19-27-36 +0000,nypost,Bitcoin sinks to $61K as Wall Street braces fo...,https://nypost.com/2026/06/09/business/bitcoin...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2647/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
26        trump     36
22         iran     27
19          new     17
106  california     14
52        world     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-06-09-19-28-54 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...,126
219,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,117
89,2026-06-09-17-01-09 +0000,nypost,Trump vows to retaliate against Iran after rev...,https://nypost.com/2026/06/09/us-news/iran-sho...,114
249,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...,92
77,2026-06-09-17-43-19 +0000,nyt,Trump Says Iran Shot Down U.S. Helicopter and ...,https://www.nytimes.com/2026/06/09/us/politics...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,126,2026-06-09-19-28-54 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...
254,63,2026-06-09-01-19-28 +0000,bbc,Spencer Pratt out of LA mayor race as left-win...,https://www.bbc.com/news/articles/cx219kxkj1jo...
203,59,2026-06-09-10-00-00 +0000,latimes,This new law could create a million new apartm...,https://www.latimes.com/business/story/2026-06...
56,57,2026-06-09-18-06-40 +0000,latimes,SoFi Stadium workers union announces labor dea...,https://www.latimes.com/sports/soccer/story/20...
224,54,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
194,46,2026-06-09-10-10-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
249,42,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...
219,39,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...
164,37,2026-06-09-13-35-50 +0000,nypost,"Vance refers Minnesota Gov. Tim Walz, AG Keith...",https://nypost.com/2026/06/09/us-news/vance-re...
263,35,2026-06-09-00-16-29 +0000,nypost,Ex-Graham Platner campaign director says embat...,https://nypost.com/2026/06/08/us-news/ex-graha...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)