## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-04-13-03 +0000,nypost,At least 19 suspected heat-related deaths in N...,https://nypost.com/2026/07/05/us-news/at-least...
1,2026-07-05-04-05-29 +0000,nyt,The Brooklyn Bridge Briefly Catches Fire Durin...,https://www.nytimes.com/2026/07/04/nyregion/fi...
2,2026-07-05-04-05-28 +0000,nypost,"5 shot, including 2 kids, while watching firew...",https://nypost.com/2026/07/05/us-news/brooklyn...
3,2026-07-05-04-01-22 +0000,nyt,Rebel Catholics Defy Vatican’s Calls to Return...,https://www.nytimes.com/2026/07/05/world/europ...
4,2026-07-05-04-01-20 +0000,nyt,Ordering Objects at V&E East Storehouse: From ...,https://www.nytimes.com/2026/07/05/arts/design...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9       july     24
57     trump     22
235  funeral     15
10        th     14
427     iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
103,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,100
12,2026-07-05-03-38-32 +0000,nypost,Trump has one of the country’s first flags on ...,https://nypost.com/2026/07/04/us-news/trump-ha...,89
7,2026-07-05-03-59-05 +0000,nypost,Trump recognizes Artemis II astronauts during ...,https://nypost.com/2026/07/04/us-news/trump-re...,83
126,2026-07-04-11-43-17 +0000,nyt,"Will Iran’s New Supreme Leader, Mojtaba Khamen...",https://www.nytimes.com/2026/07/04/world/middl...,81
32,2026-07-05-01-00-38 +0000,nyt,TV coverage of the Fourth of July will emphasi...,https://www.nytimes.com/live/2026/07/04/us/ame...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
103,100,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
51,73,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
131,45,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
176,40,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
174,35,2026-07-04-05-25-47 +0000,nypost,Iranians chant ‘Death to America’ as crowds mo...,https://nypost.com/2026/07/04/us-news/iranians...
90,32,2026-07-04-17-17-52 +0000,nypost,NYC Council to honor first-responder heroes ki...,https://nypost.com/2026/07/04/us-news/nyc-coun...
9,28,2026-07-05-03-54-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
54,28,2026-07-04-22-52-34 +0000,latimes,Paul Pelosi faces possible hit-and-run charge ...,https://www.latimes.com/california/story/2026-...
150,27,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...
167,25,2026-07-04-08-24-17 +0000,bbc,In pictures: Stars and fans celebrate Taylor S...,https://www.bbc.co.uk/news/articles/c7vyqgy4r5...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)