## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-09-17-51-26 +0000,nyt,Police Expand Investigation Into Reform U.K. A...,https://www.nytimes.com/2026/09/09/world/europ...
1,2026-09-09-17-50-56 +0000,startribune,Opinion | The laws to stop the Loring Park sho...,https://www.startribune.com/minneapolis-mass-s...
2,2026-09-09-17-50-43 +0000,nyt,"Trump’s PAC Unloads War Chest, With $47 Millio...",https://www.nytimes.com/2026/09/09/us/politics...
3,2026-09-09-17-50-29 +0000,wapo,Trump administration proposes changes to censu...,https://www.washingtonpost.com/politics/2026/0...
4,2026-09-09-17-46-52 +0000,nypost,"Secretive, high-security LA landmark will open...",https://nypost.com/2026/09/09/lifestyle/socal-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     54
199     new     26
250     oil     24
122  canada     17
87       up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
23,2026-09-09-17-09-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,132
353,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...,125
266,2026-09-09-03-47-00 +0000,wsj,"President Trump gave cash gifts of $45,000 api...",https://www.wsj.com/politics/policy/trump-gift...,120
273,2026-09-09-02-51-00 +0000,wsj,President Trump signed orders to ban the impor...,https://www.wsj.com/economy/trade/trump-says-h...,117
13,2026-09-09-17-23-21 +0000,nyt,Trump’s Midterm Pitch Clouded by Iran War and ...,https://www.nytimes.com/2026/09/09/business/ca...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
23,132,2026-09-09-17-09-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
356,105,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
140,80,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
314,78,2026-09-08-23-42-00 +0000,wsj,The Supreme Court rejected Missouri’s bid to u...,https://www.wsj.com/politics/policy/supreme-co...
419,70,2026-09-08-18-17-04 +0000,cbc,"Canada, U.K., France to ban trade of goods fro...",https://www.cbc.ca/news/world/canada-uk-france...
12,62,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
322,56,2026-09-08-23-26-00 +0000,wsj,The latest Canadian tariffs on $20 billion of ...,https://www.wsj.com/economy/trade/the-states-o...
380,49,2026-09-08-20-46-58 +0000,nypost,California union threatens strike in war over ...,https://nypost.com/2026/09/08/us-news/californ...
181,48,2026-09-09-10-42-00 +0000,wsj,The two-day GOP midterm convention kicks off W...,https://www.wsj.com/politics/elections/everyth...
312,40,2026-09-08-23-52-28 +0000,bbc,Chris Mason: Burnham looks to show he will go ...,https://www.bbc.co.uk/news/articles/c3v439n5xl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)