## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-10-53-58 +0000,startribune,"After message from Anthony Edwards, Timberwolv...",https://www.startribune.com/minnesota-timberwo...
1,2026-10-31-10-00-18 +0000,chitri,Cook County Dems trying for blue sweep in boar...,https://www.chicagotribune.com/2026/10/31/cook...
2,2026-10-31-10-00-18 +0000,chitri,Tangle with Springfield forms crux of school b...,https://www.chicagotribune.com/2026/10/31/scho...
3,2026-10-31-10-00-08 +0000,nyt,"75 Years On, the National Ballet of Canada ‘Re...",https://www.nytimes.com/2026/10/31/world/canad...
4,2026-10-31-10-00-00 +0000,latimes,Election night TV coverage goes full nerd,https://www.latimes.com/entertainment-arts/bus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2433/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
34     election     26
111       trump     23
50   california     18
520     binance     16
413         new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
356,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,91
64,2026-10-31-03-30-57 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...,86
236,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,80
335,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,74
359,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to obscure but importan...,https://www.latimes.com/california/story/2026-...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
356,91,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
231,63,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
185,62,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...
103,55,2026-10-31-00-29-58 +0000,bbc,Alaska Senate candidate denies knowing about a...,https://www.bbc.co.uk/news/articles/cmwyq2gg1y...
148,51,2026-10-30-21-48-01 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
250,50,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
299,41,2026-10-30-15-09-29 +0000,nyt,Democrats and Republicans Share Dueling Health...,https://www.nytimes.com/2026/10/30/us/politics...
97,41,2026-10-31-00-45-20 +0000,nypost,University of New Haven hockey captain with NY...,https://nypost.com/2026/10/30/us-news/aspiring...
348,40,2026-10-30-12-04-57 +0000,nypost,Disgraced ex-Prince Andrew under fresh investi...,https://nypost.com/2026/10/30/world-news/disgr...
46,39,2026-10-31-07-14-40 +0000,nypost,"One dead, 6 injured in shooting inside Spirit ...",https://nypost.com/2026/10/31/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)