## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-12-05-32-41 +0000,nypost,Lil Durk acquitted in LA murder-for-hire plot ...,https://nypost.com/2026/09/12/us-news/lil-durk...
1,2026-09-12-04-58-44 +0000,nypost,Trump demands Smithsonian replace ‘strange mod...,https://nypost.com/2026/09/12/us-news/trump-de...
2,2026-09-12-04-43-10 +0000,bbc,Saudi Arabia shuts key oil pipeline after dron...,https://www.bbc.co.uk/news/articles/c62m933465...
3,2026-09-12-04-03-16 +0000,nypost,Engineer with close ties to Fox News hosts sta...,https://nypost.com/2026/09/12/us-news/engineer...
4,2026-09-12-04-02-49 +0000,nyt,"As Oil Prices Rise, BRICS Leaders Have What U....",https://www.nytimes.com/2026/09/12/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
12        trump     35
30          oil     18
53         iran     16
102          ai     16
136  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
48,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...,118
85,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...,105
150,2026-09-11-18-19-00 +0000,wsj,The annual inflation rate stalled out last mon...,https://www.wsj.com/economy/cpi-inflation-repo...,93
149,2026-09-11-18-19-00 +0000,wsj,"GOP Sen. Susan Collins, who faces a tough re-e...",https://www.wsj.com/politics/policy/embattled-...,85
170,2026-09-11-17-38-21 +0000,nypost,Fed Chair Kevin Warsh under pressure to hike r...,https://nypost.com/2026/09/11/business/fed-cha...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
48,118,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...
85,87,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...
57,62,2026-09-11-23-15-00 +0000,wsj,New Jersey Gov. Mikie Sherrill is facing the s...,https://www.wsj.com/politics/misconduct-inquir...
8,61,2026-09-12-03-45-43 +0000,nypost,Chinese entities gave Iran satellite images of...,https://nypost.com/2026/09/11/us-news/chinese-...
63,55,2026-09-11-22-52-05 +0000,missionlocal,Meet the S.F. school board candidates: Do you ...,https://missionlocal.org/2026/09/san-francisco...
186,45,2026-09-11-16-56-21 +0000,nypost,California’s most powerful union boss threaten...,https://nypost.com/2026/09/11/us-news/californ...
124,45,2026-09-11-19-36-00 +0000,wsj,A CIA official who authorities said walked out...,https://www.wsj.com/politics/national-security...
158,42,2026-09-11-18-04-51 +0000,nypost,"Ontario premier wants GOP to lose House, Senat...",https://nypost.com/2026/09/11/world-news/ontar...
67,41,2026-09-11-22-22-16 +0000,nyt,"Houthis Seize a Key Red Sea Island, Threatenin...",https://www.nytimes.com/2026/09/11/world/middl...
60,41,2026-09-11-23-00-23 +0000,nypost,Michigan Dem Abdul El-Sayed condemns ‘cruel’ ...,https://nypost.com/2026/09/11/us-news/abdul-el...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)