## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-20-02-54-05 +0000,bbc,'Our worst nightmare': Threats to Australian p...,https://www.bbc.co.uk/news/articles/cq398rk4p3...
1,2026-10-20-02-41-51 +0000,nyt,Oil-Rich Alberta Votes on its Future in Canada,https://www.nytimes.com/2026/10/19/world/canad...
2,2026-10-20-02-38-13 +0000,nypost,Gruesome shark attack details emerge after fai...,https://nypost.com/2026/10/19/us-news/californ...
3,2026-10-20-02-37-48 +0000,nyt,Trump Rallies Red States Amid Fears About G.O....,https://www.nytimes.com/2026/10/19/us/politics...
4,2026-10-20-02-35-00 +0000,wsj,Singapore Dollar Consolidates Amid Mixed Signals,https://www.wsj.com/finance/currencies/asian-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
29        trump     28
239         new     17
424          up     15
27   california     15
166      russia     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...,152
303,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...,103
82,2026-10-19-21-49-41 +0000,nyt,DOJ Charges 28 California Residents With Votin...,https://www.nytimes.com/2026/10/19/us/politics...,82
52,2026-10-19-23-06-10 +0000,nypost,Susie Wiles teams up with Melania Trump for ne...,https://nypost.com/2026/10/19/us-news/susie-wi...,82
235,2026-10-19-15-31-08 +0000,nypost,Donald Trump signs executive order creating NI...,https://nypost.com/2026/10/19/us-news/donald-t...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,152,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...
218,55,2026-10-19-16-42-59 +0000,nypost,Christiane Amanpour to exit CNN amid staffer c...,https://nypost.com/2026/10/19/media/christiane...
291,54,2026-10-19-11-41-24 +0000,bbc,Personal attacks fire up debate before Brazil'...,https://www.bbc.co.uk/news/articles/ck98zlzyql...
75,53,2026-10-19-22-04-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
13,47,2026-10-20-02-00-00 +0000,nypost,Halloween horror as shooting breaks out during...,https://nypost.com/2026/10/19/us-news/gunfire-...
159,46,2026-10-19-19-31-37 +0000,nypost,Sweat pants-clad video game store worker prais...,https://nypost.com/2026/10/19/world-news/frenc...
183,42,2026-10-19-18-31-55 +0000,cbc,Police issue curfew in Paris after weekend rio...,https://www.cbc.ca/news/world/paris-france-pro...
248,42,2026-10-19-14-24-00 +0000,nypost,Rubio slaps down Zelensky’s claims of US cutti...,https://nypost.com/2026/10/19/us-news/rubio-sa...
233,41,2026-10-19-15-44-00 +0000,wsj,Economists surveyed by The Wall Street Journal...,https://www.wsj.com/finance/see-what-71-econom...
168,39,2026-10-19-19-04-42 +0000,nypost,Supreme Court rejects bid by 9/11 mastermind K...,https://nypost.com/2026/10/19/us-news/supreme-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)