## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-18-14-00 +0000,wsj,Stocks Mixed After Signs of Progress in U.S.-I...,https://www.wsj.com/finance/oil-falls-on-progr...
1,2026-06-22-18-13-00 +0000,wsj,ABC Launches On-Air Campaign Against FCC Inves...,https://www.wsj.com/business/media/abc-launche...
2,2026-06-22-18-12-13 +0000,nypost,"Facing wildly high costs, NYC parents pivot to...",https://nypost.com/2026/06/22/lifestyle/nyc-pa...
3,2026-06-22-18-11-56 +0000,bbc,"Clive Davis, music mogul behind Whitney Housto...",https://www.bbc.com/news/articles/c3vy3e6q90qo...
4,2026-06-22-18-09-06 +0000,nyt,"Clive Davis, Music Industry Titan Who Signed W...",https://www.nytimes.com/2026/06/22/arts/music/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
4        iran     22
124   starmer     21
161  minister     15
221      will     15
173     trump     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
295,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,103
167,2026-06-22-12-51-52 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,94
225,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...,83
204,2026-06-22-10-09-12 +0000,cbc,U.K. Prime Minister Keir Starmer announces res...,https://www.cbc.ca/news/world/livestory/starme...,75
105,2026-06-22-15-17-00 +0000,bbc,Starmer quits as Labour leader and paves way f...,https://www.bbc.com/news/articles/cdxd00lg599o...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
295,103,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
225,83,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...
179,61,2026-06-22-11-35-00 +0000,wsj,"Alan Greenspan, who piloted the economy throug...",https://www.wsj.com/economy/central-banking/al...
185,48,2026-06-22-11-01-00 +0000,wsj,"In Washington and around the world, political ...",https://www.wsj.com/politics/in-washington-and...
3,44,2026-06-22-18-11-56 +0000,bbc,"Clive Davis, music mogul behind Whitney Housto...",https://www.bbc.com/news/articles/c3vy3e6q90qo...
233,42,2026-06-22-04-58-42 +0000,nypost,2 students arrested after deadly high school s...,https://nypost.com/2026/06/22/world-news/phili...
39,40,2026-06-22-17-17-00 +0000,wsj,Supreme Court Reinstates Conviction in Murder ...,https://www.wsj.com/us-news/law/scotus-etan-pa...
263,38,2026-06-21-23-54-20 +0000,cbc,Abelardo De La Espriella wins Colombia electio...,https://www.cbc.ca/news/world/colombia-preside...
73,38,2026-06-22-16-10-04 +0000,nypost,NYC coffee shop bans pro-Israel politician in ...,https://nypost.com/2026/06/22/us-news/nyc-coff...
6,37,2026-06-22-18-07-49 +0000,nyt,Mideast Live Updates: U.S. Eases Sanctions on ...,https://www.nytimes.com/live/2026/06/22/world/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)