## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-21-24-32 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...
1,2026-06-09-21-23-19 +0000,nyt,"In Maine, a Senate race provokes complex emoti...",https://www.nytimes.com/live/2026/06/09/us/ele...
2,2026-06-09-21-23-00 +0000,wsj,Opinion | Is California’s Election ‘Rigged’?,https://www.wsj.com/opinion/los-angeles-mayora...
3,2026-06-09-21-22-00 +0000,nypost,Accused Penn Station slasher’s ex-wife breaks ...,https://nypost.com/2026/06/09/us-news/accused-...
4,2026-06-09-21-21-00 +0000,wsj,Trump Says U.S. Must Respond After Blaming Ira...,https://www.wsj.com/world/middle-east/apache-h...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
4         trump     33
0          iran     23
16   california     17
442         new     14
224       world     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-06-09-21-24-32 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...,114
249,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,108
277,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...,92
129,2026-06-09-17-01-09 +0000,nypost,Trump claims Iran shooting down US helicopter ...,https://nypost.com/2026/06/09/us-news/iran-sho...,89
119,2026-06-09-17-43-19 +0000,nyt,Trump Says Iran Shot Down U.S. Helicopter and ...,https://www.nytimes.com/2026/06/09/us/politics...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,114,2026-06-09-21-24-32 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...
282,62,2026-06-09-01-19-28 +0000,bbc,Spencer Pratt out of LA mayor race as left-win...,https://www.bbc.com/news/articles/cx219kxkj1jo...
277,59,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...
34,57,2026-06-09-20-39-00 +0000,wsj,Los Angeles Stadium Workers Reach Deal to Head...,https://www.wsj.com/business/los-angeles-stadi...
254,46,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
177,45,2026-06-09-14-35-13 +0000,nypost,US Navy uses cutting-edge new drone boat to re...,https://nypost.com/2026/06/09/us-news/us-navy-...
64,41,2026-06-09-19-33-41 +0000,nypost,Karmelo Anthony sobs as he’s convicted of murd...,https://nypost.com/2026/06/09/us-news/karmelo-...
224,40,2026-06-09-10-10-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
161,38,2026-06-09-15-10-57 +0000,nyt,Maine Elections Test Democrats’ Support for Pl...,https://www.nytimes.com/2026/06/09/us/politics...
272,36,2026-06-09-03-25-54 +0000,missionlocal,San Francisco’s ‘Overpaid CEO’ tax measure fai...,https://missionlocal.org/2026/06/sf-overpaid-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)