## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-20-56-08 +0000,nyt,"Saudi Arabia’s Riyadh Airport Attacked Again, ...",https://www.nytimes.com/2026/10/10/world/middl...
1,2026-10-10-20-56-06 +0000,nypost,Trump rips into Volodymyr Zelensky — insisting...,https://nypost.com/2026/10/10/us-news/trump-ri...
2,2026-10-10-20-51-12 +0000,bbc,Russian glide bomb attack on Zaporizhzhia kill...,https://www.bbc.co.uk/news/articles/cwvgdpv642...
3,2026-10-10-20-50-11 +0000,nypost,Trump says he ‘wasn’t involved’ in plan to liv...,https://nypost.com/2026/10/10/us-news/trump-no...
4,2026-10-10-20-49-53 +0000,nypost,Iran-backed Houthis strike Riyadh airport in S...,https://nypost.com/2026/10/10/world-news/iran-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2325/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
8       trump     38
15        new     19
24         he     14
16  president     12
29  execution     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-10-10-17-35-33 +0000,chitri,Pres. Donald Trump says Ukraine should get a n...,https://www.chicagotribune.com/2026/10/10/trum...,119
185,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...,109
29,2026-10-10-19-28-28 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...,108
13,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...,106
103,2026-10-10-12-56-05 +0000,cbc,"Trump says Ukraine should get a new president,...",https://www.cbc.ca/news/world/russia-strikes-u...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,119,2026-10-10-17-35-33 +0000,chitri,Pres. Donald Trump says Ukraine should get a n...,https://www.chicagotribune.com/2026/10/10/trum...
59,54,2026-10-10-18-08-00 +0000,wsj,"Kimberly Guilfoyle, as America’s newly minted ...",https://www.wsj.com/politics/policy/at-davos-k...
4,44,2026-10-10-20-49-53 +0000,nypost,Iran-backed Houthis strike Riyadh airport in S...,https://nypost.com/2026/10/10/world-news/iran-...
183,44,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...
121,41,2026-10-10-10-06-23 +0000,bbc,Rogue Anthropic AI agent gave police fake tip ...,https://www.bbc.co.uk/news/articles/cqkg50j1yd...
65,40,2026-10-10-17-44-26 +0000,bbc,US murderer Christa Pike discharged from hospi...,https://www.bbc.co.uk/news/articles/cmlyle97pq...
66,37,2026-10-10-17-41-47 +0000,nypost,Cornell handed students raunchy sex checklist ...,https://nypost.com/2026/10/10/us-news/cornell-...
185,37,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...
188,31,2026-10-10-01-00-00 +0000,wsj,A growing group of Republicans are privately—a...,https://www.wsj.com/politics/elections/trump-m...
228,30,2026-10-09-21-58-00 +0000,wsj,DHS Secretary Criticizes New York Mayor After ...,https://www.wsj.com/us-news/ice-agent-shoots-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)