## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-13-43-00 +0000,wsj,The Fashion Heir Facing Suspicion After Father...,https://www.wsj.com/business/the-fashion-scion...
1,2026-05-21-13-40-00 +0000,wsj,Extended Hold Might Be Enough to Contain Infla...,https://www.wsj.com/pro/central-banking/extend...
2,2026-05-21-13-37-15 +0000,bbc,Cheaper theme park tickets and children's meal...,https://www.bbc.com/news/articles/cd7pzr88de1o...
3,2026-05-21-13-35-43 +0000,bbc,'I've worked too hard to feel impostor syndrome',https://www.bbc.com/news/videos/c9q3pr15dedo?a...
4,2026-05-21-13-31-59 +0000,nyt,Trump’s Fund Shows Blanche Choosing Loyalty Ov...,https://www.nytimes.com/2026/05/21/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
32   trump     50
201    new     24
487   cuba     16
229   iran     15
89   ebola     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
294,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...,124
215,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,116
226,2026-05-20-23-26-30 +0000,nyt,Trump’s Government Moves to Spare an Unhappy T...,https://www.nytimes.com/2026/05/20/us/politics...,111
94,2026-05-21-10-36-32 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...,106
300,2026-05-20-19-52-30 +0000,nyt,Castro Indictment Is Trump’s Latest Move Again...,https://www.nytimes.com/2026/05/20/us/politics...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
294,124,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...
78,89,2026-05-21-11-06-00 +0000,wsj,"Jeff Bezos wades into politics, and New York C...",https://www.wsj.com/politics/policy/bezos-wade...
215,66,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
305,62,2026-05-20-19-46-00 +0000,wsj,Federal Reserve officials all but retired the ...,https://www.wsj.com/economy/central-banking/fe...
94,56,2026-05-21-10-36-32 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...
291,49,2026-05-20-20-18-32 +0000,nypost,Feds probe suspicious oil trades worth $800M m...,https://nypost.com/2026/05/20/business/feds-pr...
238,45,2026-05-20-22-33-35 +0000,nypost,Nvidia’s revenue hits record $81B — easily top...,https://nypost.com/2026/05/20/business/nvidias...
359,43,2026-05-20-17-11-00 +0000,wsj,The GOP-controlled House passed a new version ...,https://www.wsj.com/politics/policy/newly-pass...
13,42,2026-05-21-13-17-31 +0000,bbc,DR Congo cancels World Cup training camp over ...,https://www.bbc.com/news/articles/c8d80856q2go...
222,42,2026-05-20-23-40-43 +0000,latimes,SpaceX files to go public in huge IPO deal,https://www.latimes.com/business/story/2026-05...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)