## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-01-15-16 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/02/world/...
1,2026-03-03-01-13-48 +0000,nypost,New details of Colorado QB Dominiq Ponder’s de...,https://nypost.com/2026/03/02/us-news/new-deta...
2,2026-03-03-01-11-58 +0000,nyt,Iran Live Updates: Rubio Says ‘Hardest Hits Ar...,https://www.nytimes.com/live/2026/03/02/world/...
3,2026-03-03-01-11-20 +0000,nyt,In First Appearance Since Taking the Country t...,https://www.nytimes.com/2026/03/02/us/politics...
4,2026-03-03-01-09-37 +0000,nyt,"In Republican Win, Supreme Court Retains G.O.P...",https://www.nytimes.com/2026/03/02/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
13       iran     95
21      trump     52
24        war     36
88    strikes     26
154  conflict     26

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
159,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,303
25,2026-03-03-00-27-07 +0000,startribune,Trump pushes back on mounting criticism about ...,https://www.startribune.com/trump-pushes-back-...,224
155,2026-03-02-20-15-54 +0000,nypost,Trump ordered Iran war — then ordered ‘hamburg...,https://nypost.com/2026/03/02/us-news/trump-or...,222
275,2026-03-02-15-17-25 +0000,nypost,Trump won’t rule out sending US troops into Ir...,https://nypost.com/2026/03/02/us-news/trump-wo...,221
327,2026-03-02-10-30-00 +0000,wsj,President Trump and his allies offered at leas...,https://www.wsj.com/politics/national-security...,214

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
159,303,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
38,109,2026-03-03-00-01-21 +0000,bbc,Heating oil prices rise by more than £100 amid...,https://www.bbc.com/news/articles/cq57ylzz4dlo...
322,73,2026-03-02-10-30-00 +0000,wsj,Berkshire’s New CEO Lays Out How He Will Pick ...,https://www.wsj.com/finance/berkshires-new-ceo...
74,71,2026-03-02-22-57-08 +0000,nyt,Iranian Strikes Hit Qatar and Saudi Energy Sit...,https://www.nytimes.com/2026/03/02/world/middl...
288,59,2026-03-02-13-54-20 +0000,bbc,'They hit so hard the house was shaking': Iran...,https://www.bbc.com/news/articles/cx2jyv3jp01o...
326,53,2026-03-02-10-30-00 +0000,wsj,The Texas Republican Senate primary is getting...,https://www.wsj.com/politics/elections/texas-p...
20,49,2026-03-03-00-33-09 +0000,latimes,Supreme Court: California parents may be told ...,https://www.latimes.com/politics/story/2026-03...
327,41,2026-03-02-10-30-00 +0000,wsj,President Trump and his allies offered at leas...,https://www.wsj.com/politics/national-security...
248,40,2026-03-02-16-34-18 +0000,wapo,Videos appear to show the moments U.S. fighter...,https://www.washingtonpost.com/investigations/...
325,39,2026-03-02-10-30-00 +0000,wsj,Think Tech Has Taken Over Your Portfolio? You ...,https://www.wsj.com/finance/investing/think-te...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)