## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-16-07-21-29 +0000,nyt,Trump Turns Taiwan Arms Sales Into Bargaining ...,https://www.nytimes.com/2026/05/16/world/asia/...
1,2026-05-16-07-16-27 +0000,nypost,Swimmer killed in shark attack off Australian ...,https://nypost.com/2026/05/16/world-news/austr...
2,2026-05-16-07-13-29 +0000,nypost,Louisiana Sen. John Kennedy introduces America...,https://nypost.com/2026/05/16/us-news/louisian...
3,2026-05-16-07-10-45 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...
4,2026-05-16-07-04-36 +0000,bbc,Man killed by 13ft great white shark in Wester...,https://www.bbc.com/news/articles/c1m2xy3dr20o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     50
7    china     28
105    new     18
47      xi     17
244   iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
139,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,119
63,2026-05-15-23-27-15 +0000,nypost,Trump: Xi ‘surprised’ by America’s AI advances...,https://nypost.com/2026/05/15/us-news/trump-xi...,116
10,2026-05-16-05-53-41 +0000,bbc,Trump warns Taiwan against declaring independe...,https://www.bbc.com/news/articles/ce8p61v7l68o...,114
296,2026-05-15-12-12-03 +0000,nyt,Nvidia’s Future in China Remains Unclear After...,https://www.nytimes.com/2026/05/15/business/nv...,110
195,2026-05-15-17-15-21 +0000,nyt,What to Watch at Trump and Xi’s U.S.-China Summit,https://www.nytimes.com/2026/05/13/business/ec...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
139,119,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
99,65,2026-05-15-21-29-00 +0000,wsj,Elon Musk’s SpaceX aims to go public on June 1...,https://www.wsj.com/economy/central-banking/sp...
42,58,2026-05-16-00-48-06 +0000,nyt,Supreme Court Rejects Virginia Democrats’ Effo...,https://www.nytimes.com/2026/05/15/us/politics...
267,55,2026-05-15-14-00-00 +0000,nypost,Neighbors of SoCal mayor who worked as secret ...,https://nypost.com/2026/05/15/us-news/ex-mayor...
30,40,2026-05-16-01-52-00 +0000,wsj,The Federal Reserve said that outgoing Chair J...,https://www.wsj.com/economy/central-banking/po...
291,38,2026-05-15-12-53-57 +0000,bbc,Prisoner swap goes ahead as Kyiv mourns 24 kil...,https://www.bbc.com/news/articles/c5y049w8nqwo...
158,33,2026-05-15-19-23-34 +0000,nypost,Tom Steyer defends sneaky move to boost his bi...,https://nypost.com/2026/05/15/us-news/tom-stey...
26,32,2026-05-16-02-06-00 +0000,wsj,With under six months to go before the midterm...,https://www.wsj.com/politics/elections/trump-r...
146,32,2026-05-15-19-51-00 +0000,wsj,So You Think You Own Shares in a Hot Startup? ...,https://www.wsj.com/finance/investing/so-you-t...
207,32,2026-05-15-16-37-30 +0000,nypost,Arizona school district accused of letting kid...,https://nypost.com/2026/05/15/us-news/arizona-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)