## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-20-13-21 +0000,nyt,"Houthis Threaten Red Sea Blockade, Putting Oil...",https://www.nytimes.com/2026/07/21/business/oi...
1,2026-07-21-20-13-00 +0000,wsj,OpenAI Is Adding Two Independent Board Members...,https://www.wsj.com/tech/ai/openai-is-adding-t...
2,2026-07-21-20-10-13 +0000,nyt,Troy Jackson Tightens Hold on Democratic Senat...,https://www.nytimes.com/2026/07/21/us/politics...
3,2026-07-21-20-10-06 +0000,bbc,Sir Chris Bryant outlines 'checklist' of issue...,https://www.bbc.co.uk/news/articles/c20e5x4dy9...
4,2026-07-21-20-09-47 +0000,nyt,Lebanese Army Accuses Israeli Troops of Firing...,https://www.nytimes.com/2026/07/21/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
172    trump     35
63       new     29
133     iran     27
48   burnham     16
495     will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
225,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...,110
376,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,96
152,2026-07-21-15-40-27 +0000,nypost,"US, Mexico resume USMCA trade talks as Trump s...",https://nypost.com/2026/07/21/world-news/us-me...,94
34,2026-07-21-19-12-00 +0000,wsj,Canada’s Carney Says Trump Agrees to Talks to ...,https://www.wsj.com/world/americas/canadas-car...,90
130,2026-07-21-16-22-24 +0000,nypost,Trump warns Iran of much greater destruction i...,https://nypost.com/2026/07/21/us-news/trump-wa...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
225,110,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...
108,85,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
376,61,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
312,50,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
60,46,2026-07-21-18-17-44 +0000,latimes,California wouldn't be the right place to laun...,https://www.latimes.com/business/story/2026-07...
100,42,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
279,37,2026-07-21-09-08-00 +0000,wsj,SBI Funds Management Shares Rise After India’s...,https://www.wsj.com/finance/investing/sbi-fund...
315,36,2026-07-21-02-16-05 +0000,bbc,'Anti-ICE' army veteran started fire outside M...,https://www.bbc.co.uk/news/articles/c1m1rr90dz...
43,34,2026-07-21-19-03-00 +0000,wsj,New Jersey has removed thousands of non-U.S. c...,https://www.wsj.com/politics/policy/new-jersey...
46,34,2026-07-21-19-00-14 +0000,nypost,NYC mom stabbed to death hours before hubby’s ...,https://nypost.com/2026/07/21/us-news/nyc-mom-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)