## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-14-41-48 +0000,nyt,CPI Shows Inflation Accelerating to 3.8% Annua...,https://www.nytimes.com/2026/05/12/business/ec...
1,2026-05-12-14-41-13 +0000,nyt,What to know about the report.,https://www.nytimes.com/live/2026/05/12/busine...
2,2026-05-12-14-38-48 +0000,bbc,Jess Phillips resigns as minister adding press...,https://www.bbc.com/news/articles/cx21jkmxd42o...
3,2026-05-12-14-37-47 +0000,nyt,"Jen Kiggans, Virginia Republican, Faces Uproar...",https://www.nytimes.com/2026/05/12/us/politics...
4,2026-05-12-14-37-00 +0000,wsj,Dollar Little Moved by Inflation Data as Its U...,https://www.wsj.com/finance/currencies/yen-con...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
163       trump     38
8          iran     30
7           war     25
433  hantavirus     17
16      starmer     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
228,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,150
262,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,123
23,2026-05-12-14-08-43 +0000,nyt,Iran War Updates: Long-Term Energy Crisis Loom...,https://www.nytimes.com/live/2026/05/11/world/...,115
36,2026-05-12-13-44-00 +0000,wsj,Consumer prices rose 3.8% in April from a year...,https://www.wsj.com/economy/cpi-inflation-repo...,114
37,2026-05-12-13-30-04 +0000,startribune,US consumer prices jump as Iran war sends ener...,https://www.startribune.com/us-consumer-prices...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
228,150,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
329,65,2026-05-11-18-21-50 +0000,nypost,Hantavirus cruise ship captain bids emotional ...,https://nypost.com/2026/05/11/world-news/hanta...
347,55,2026-05-11-16-39-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
190,54,2026-05-12-02-26-06 +0000,nyt,Starmer Faces Mounting Calls From Own Party to...,https://www.nytimes.com/2026/05/11/world/europ...
181,48,2026-05-12-03-20-00 +0000,wsj,OpenAI’s Sam Altman’s personal investments are...,https://www.wsj.com/tech/ai/sam-altmans-busine...
349,47,2026-05-11-16-34-44 +0000,nypost,Elon Musk to join Trump in China for high-stak...,https://nypost.com/2026/05/11/us-news/elon-mus...
171,44,2026-05-12-04-30-04 +0000,nypost,Michael Jackson’s ‘secret family’ reveals dist...,https://nypost.com/2026/05/12/us-news/michael-...
289,44,2026-05-11-20-30-20 +0000,nypost,Arcadia mayor Eileen Wang admits acting as Chi...,https://nypost.com/2026/05/11/us-news/eileen-w...
239,38,2026-05-11-22-38-31 +0000,nypost,Supreme Court allows Alabama to redraw congres...,https://nypost.com/2026/05/11/us-news/supreme-...
321,36,2026-05-11-18-43-51 +0000,latimes,Oil rig off the SoCal coast catches fire; 'no ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)