## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-25-11-47-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
1,2026-09-25-11-44-44 +0000,bbc,Netanyahu defends Israeli military action as d...,https://www.bbc.co.uk/news/articles/c3y0z7kxle...
2,2026-09-25-11-40-24 +0000,nyt,A Quiet ICE Surge That Unfolded ‘Everywhere Al...,https://www.nytimes.com/2026/09/25/us/ice-surg...
3,2026-09-25-11-39-00 +0000,wsj,ArcelorMittal Drops Plan to Restart Ukrainian ...,https://www.wsj.com/world/europe/arcelormittal...
4,2026-09-25-11-38-47 +0000,startribune,Meet the Lynx: The WNBA’s top playoff seed is ...,https://www.startribune.com/minnesota-lynx-ros...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
50   trump     89
57      xi     41
192    new     35
362  house     23
812  white     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
125,2026-09-25-04-29-00 +0000,nypost,Trump gifts Xi a bald eagle sculpture — invite...,https://nypost.com/2026/09/25/us-news/trump-gi...,245
165,2026-09-25-01-31-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,237
260,2026-09-24-21-03-33 +0000,nypost,Trump charms Xi Jinping during White House sta...,https://nypost.com/2026/09/24/us-news/trump-pu...,228
171,2026-09-25-01-17-00 +0000,wsj,President Trump hosted Chinese leader Xi Jinpi...,https://www.wsj.com/world/china/five-takeaways...,218
256,2026-09-24-21-11-30 +0000,nypost,Here’s the menu for the Trump-Xi state dinner ...,https://nypost.com/2026/09/24/us-news/heres-th...,208

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
125,245,2026-09-25-04-29-00 +0000,nypost,Trump gifts Xi a bald eagle sculpture — invite...,https://nypost.com/2026/09/25/us-news/trump-gi...
242,106,2026-09-24-21-30-00 +0000,wsj,The White House is pressing China about suspec...,https://www.wsj.com/politics/elections/trump-a...
1,69,2026-09-25-11-44-44 +0000,bbc,Netanyahu defends Israeli military action as d...,https://www.bbc.co.uk/news/articles/c3y0z7kxle...
153,68,2026-09-25-02-16-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...
342,58,2026-09-24-18-31-54 +0000,latimes,California woman missing since 2007 found buri...,https://www.latimes.com/california/story/2026-...
96,56,2026-09-25-08-53-00 +0000,wsj,Eurozone Bond Yields Fall as Oil Prices Declin...,https://www.wsj.com/finance/investing/u-s-trea...
279,54,2026-09-24-20-25-59 +0000,chitri,Trump administration asks the Supreme Court to...,https://www.chicagotribune.com/2026/09/24/trum...
413,53,2026-09-24-16-00-00 +0000,wsj,Average 30-year mortgage rates hit 7.03% this ...,https://www.wsj.com/economy/housing/mortgage-r...
171,51,2026-09-25-01-17-00 +0000,wsj,President Trump hosted Chinese leader Xi Jinpi...,https://www.wsj.com/world/china/five-takeaways...
23,45,2026-09-25-11-00-27 +0000,nypost,Canada PM Mark Carney confirms he’s prepped fo...,https://nypost.com/2026/09/25/us-news/canada-p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)