## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-05-20-50-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
1,2026-09-05-20-46-57 +0000,nypost,California’s off-road paradise threatened as d...,https://nypost.com/2026/09/05/science/californ...
2,2026-09-05-20-45-58 +0000,wapo,Trump removes White House shrouds as he prepar...,https://www.washingtonpost.com/politics/2026/0...
3,2026-09-05-20-41-59 +0000,bbc,US hits three Iranian oil tankers after saying...,https://www.bbc.co.uk/news/articles/cj64rrne64...
4,2026-09-05-20-41-16 +0000,nypost,Victims in horrific Wrightwood ejection crash ...,https://nypost.com/2026/09/05/us-news/victims-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     28
278      new     16
62    clancy     13
61   lindsay     13
83      will     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
68,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...,77
205,2026-09-04-22-58-11 +0000,latimes,Judge again halts Postal Service mail ballot p...,https://www.latimes.com/politics/story/2026-09...,76
0,2026-09-05-20-50-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,67
36,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...,65
199,2026-09-04-23-10-01 +0000,nyt,Trump Says He Will Spend Some of His War Chest...,https://www.nytimes.com/2026/09/04/us/politics...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
68,77,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...
77,50,2026-09-05-14-03-43 +0000,chitri,US military hits 3 Iranian oil tankers after s...,https://www.chicagotribune.com/2026/09/05/us-m...
159,47,2026-09-05-03-25-58 +0000,bbc,What happens next after Lindsay Clancy's murde...,https://www.bbc.co.uk/news/articles/cj9x248npw...
81,46,2026-09-05-13-10-33 +0000,nypost,Putin declares 3-day cease-fire in Ukraine war...,https://nypost.com/2026/09/05/world-news/putin...
122,42,2026-09-05-09-30-00 +0000,wsj,How do you view the major components of Americ...,https://www.wsj.com/politics/young-people-see-...
0,39,2026-09-05-20-50-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
31,37,2026-09-05-18-15-56 +0000,nyt,Nepal Floods Buried a House. The Woman Inside ...,https://www.nytimes.com/2026/09/05/world/asia/...
205,32,2026-09-04-22-58-11 +0000,latimes,Judge again halts Postal Service mail ballot p...,https://www.latimes.com/politics/story/2026-09...
234,31,2026-09-04-21-09-00 +0000,wsj,The Supreme Court cleared the way for politica...,https://www.wsj.com/politics/policy/supreme-co...
73,30,2026-09-05-14-26-37 +0000,bbc,Nigel Farage tells BBC he 'wasn't listening' d...,https://www.bbc.co.uk/news/articles/c0qxgn7q1v...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)