## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-11-09-00 +0000,wsj,Vietnam’s Factories Thrive Amid Trade Upheaval,https://www.wsj.com/logistics-report/vietnams-...
1,2026-08-27-11-09-00 +0000,wsj,Best Buy Raises Outlook as Sales Grow,https://www.wsj.com/business/retail/best-buy-r...
2,2026-08-27-11-08-09 +0000,nyt,Live Updates: Rescuers Scour Himalayan Valleys...,https://www.nytimes.com/live/2026/08/27/world/...
3,2026-08-27-11-07-52 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/08/27/world/...
4,2026-08-27-11-06-16 +0000,nyt,"In Japan, Yayoi Kusama Is Remembered as a Visi...",https://www.nytimes.com/2026/08/27/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
170   trump     36
82    nepal     24
247     new     19
4     trade     18
88   canada     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
235,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,126
165,2026-08-26-23-55-41 +0000,wapo,"Canada, pressured by Trump, wants new trade pa...",https://www.washingtonpost.com/world/2026/08/2...,100
275,2026-08-26-19-08-11 +0000,cbc,Trump's trade war: Fact-checking Canada's natu...,https://www.cbc.ca/news/world/trade-war-natura...,94
358,2026-08-26-14-50-16 +0000,cbc,Canada’s resistance to Trump’s trade demands o...,https://www.cbc.ca/news/world/canadas-resistan...,91
195,2026-08-26-22-32-12 +0000,cbc,Where Trump’s trade war with Canada could back...,https://www.cbc.ca/player/play/9.7321982?cmp=rss,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
235,126,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
24,88,2026-08-27-10-13-00 +0000,nypost,NY doctor’s desperate plea for her parents who...,https://nypost.com/2026/08/27/us-news/ny-docs-...
189,86,2026-08-26-22-49-36 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
246,66,2026-08-26-20-22-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
173,63,2026-08-26-23-22-21 +0000,latimes,'A voluptuous sex symbol.' Judge invokes Dolly...,https://www.latimes.com/california/story/2026-...
300,57,2026-08-26-17-45-44 +0000,latimes,Southern California's scorching heat wave peak...,https://www.latimes.com/california/story/2026-...
393,49,2026-08-26-12-37-13 +0000,nypost,47 Americans among hundreds missing after dead...,https://nypost.com/2026/08/26/world-news/flood...
49,46,2026-08-27-09-30-00 +0000,wsj,The selloff in U.S. Treasurys has captured glo...,https://www.wsj.com/economy/global/think-treas...
201,46,2026-08-26-22-10-00 +0000,wsj,The surprise visit by the director of the Cent...,https://www.wsj.com/politics/policy/cia-chiefs...
324,43,2026-08-26-16-29-03 +0000,nypost,Trump doubts Iran’s Supreme Leader Mojtaba Kha...,https://nypost.com/2026/08/26/us-news/trump-do...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)