## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-18-13-41 +0000,nyt,Trump Attacks Pope Leo as Too Liberal and ‘Wea...,https://www.nytimes.com/2026/04/12/us/politics...
1,2026-04-13-18-11-56 +0000,nyt,Trump Attack on Pope and Posting of Jesus Imag...,https://www.nytimes.com/2026/04/13/us/trump-po...
2,2026-04-13-18-11-35 +0000,nypost,Killer FedEx driver Tanner Horner wrote note t...,https://nypost.com/2026/04/13/us-news/killer-f...
3,2026-04-13-18-10-42 +0000,wapo,"Lambasting Pope Leo, Trump risks alienating co...",https://www.washingtonpost.com/world/2026/04/1...
4,2026-04-13-18-09-59 +0000,nyt,Iran War Live Updates: U.S. Begins Blockade of...,https://www.nytimes.com/live/2026/04/13/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     48
35      iran     41
40  blockade     26
42    hormuz     19
36       war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
28,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...,178
217,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,167
162,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,166
31,2026-04-13-17-20-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,164
246,2026-04-13-01-36-13 +0000,nypost,"Trump blasts Pope Leo as ‘weak on crime,’ says...",https://nypost.com/2026/04/12/us-news/trump-bl...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
28,178,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...
250,103,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
40,102,2026-04-13-17-05-41 +0000,nypost,Here’s how the US blockade of Strait of Hormuz...,https://nypost.com/2026/04/13/world-news/how-w...
277,60,2026-04-12-22-24-01 +0000,nyt,Hungary Election Results: Viktor Orban Concede...,https://www.nytimes.com/2026/04/12/world/europ...
91,52,2026-04-13-15-50-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
170,45,2026-04-13-11-03-00 +0000,wsj,Two of the most recognizable people on the pla...,https://www.wsj.com/politics/the-showdown-betw...
304,35,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
89,33,2026-04-13-15-56-00 +0000,wapo,Judge dismisses Trump’s lawsuit against Wall S...,https://www.washingtonpost.com/business/2026/0...
137,31,2026-04-13-13-38-44 +0000,cbc,Israel launches attack to seize Lebanon border...,https://www.cbc.ca/news/world/israel-lebanon-c...
19,31,2026-04-13-17-44-31 +0000,nypost,NY GOP gubernatorial candidate Bruce Blakeman ...,https://nypost.com/2026/04/13/us-news/ny-gop-g...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)