## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-01-17-08-00 +0000,wsj,The U.S. will raise tariffs on automobiles fro...,https://www.wsj.com/economy/trade/trump-threat...
1,2026-05-01-17-05-58 +0000,nyt,U.S. Indictment of Sinaloa’s Governor Is a Rec...,https://www.nytimes.com/2026/05/01/world/ameri...
2,2026-05-01-17-04-45 +0000,nyt,Jury Convicts Florida Ex-Rep. David Rivera in ...,https://www.nytimes.com/2026/05/01/us/david-ri...
3,2026-05-01-17-03-19 +0000,bbc,The Real Greek rescued by Cote Brasserie-owner,https://www.bbc.com/news/articles/c93xqnlq33qo...
4,2026-05-01-17-03-11 +0000,bbc,Israeli police arrest man after nun attacked i...,https://www.bbc.com/news/articles/cy02gnzlvkko...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2652/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7    trump     42
75    your     38
80    race     37
76   guide     35
119    new     31

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,188
174,2026-05-01-10-00-00 +0000,latimes,Your guide to the California state schools sup...,https://www.latimes.com/california/story/2026-...,187
194,2026-05-01-10-00-00 +0000,latimes,Your guide to the L.A. City Council District 1...,https://www.latimes.com/california/story/2026-...,181
191,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,178
27,2026-05-01-16-33-27 +0000,latimes,Your guide to the L.A. City Council District 5...,https://www.latimes.com/california/story/2026-...,177

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,188,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...
415,129,2026-04-30-18-05-26 +0000,bbc,Oil price hits highest since 2022 after report...,https://www.bbc.com/news/articles/cx21m88rd14o...
366,87,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...
127,74,2026-05-01-12-36-00 +0000,wsj,The Minneapolis Fed president wrote that heigh...,https://www.wsj.com/economy/central-banking/ri...
353,54,2026-04-30-21-46-00 +0000,wsj,President Trump said he would remove tariffs o...,https://www.wsj.com/economy/trade/trump-says-u...
307,51,2026-05-01-00-00-00 +0000,wsj,Republican leaders are pushing Southern states...,https://www.wsj.com/politics/policy/republican...
287,49,2026-05-01-01-33-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
268,47,2026-05-01-04-11-53 +0000,bbc,Myanmar ex-leader Aung San Suu Kyi moved to ho...,https://www.bbc.com/news/articles/cz72j8eex4eo...
106,46,2026-05-01-13-54-56 +0000,nypost,Chirayu Rana — former JPMorgan banker at cente...,https://nypost.com/2026/05/01/business/chirayu...
396,45,2026-04-30-19-26-32 +0000,nyt,Camp Mystic Says It Will Not Reopen This Summe...,https://www.nytimes.com/2026/04/30/us/camp-mys...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)