## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-11-22-05-01 +0000,nypost,Mysterious masked man at Khamenei’s funeral re...,https://nypost.com/2026/07/11/world-news/myste...
1,2026-07-11-22-00-41 +0000,startribune,Olivia Miles ‘doesn’t shy away from the moment...,https://www.startribune.com/minnesota-lynx-new...
2,2026-07-11-21-56-58 +0000,nypost,Father and son killed when their plane crashes...,https://nypost.com/2026/07/11/us-news/father-a...
3,2026-07-11-21-56-52 +0000,bbc,Polish PM pledges memorial to victims of WW2 '...,https://www.bbc.co.uk/news/articles/cze94x4361...
4,2026-07-11-21-56-46 +0000,nypost,LA supermarket’s despicable act after shopper ...,https://nypost.com/2026/07/11/us-news/la-super...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
51   trump     29
41     new     23
228  world     14
229    cup     12
61   times     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,112
158,2026-07-11-04-00-00 +0000,wsj,A lack of defensive capabilities aboard Presid...,https://www.wsj.com/politics/national-security...,106
63,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,105
65,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,105
81,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,112,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
70,51,2026-07-11-15-37-30 +0000,nypost,Fan collects beer from all 48 countries in Wor...,https://nypost.com/2026/07/11/sports/fan-colle...
128,44,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
9,36,2026-07-11-21-23-38 +0000,nypost,Ro Khanna blew off offer to meet former Israel...,https://nypost.com/2026/07/11/world-news/ro-kh...
114,35,2026-07-11-10-56-43 +0000,nypost,Iran’s Supreme Leader Mojtaba Khamenei vows re...,https://nypost.com/2026/07/11/world-news/irans...
199,33,2026-07-10-22-52-00 +0000,wsj,Investigators found evidence that Corey Lewand...,https://www.wsj.com/politics/policy/dhs-corey-...
61,32,2026-07-11-16-50-06 +0000,nypost,Maine event: Dems descend into chaos over Plat...,https://nypost.com/2026/07/11/us-news/maine-de...
154,32,2026-07-11-04-37-00 +0000,wsj,A landmark housing bill designed to address vo...,https://www.wsj.com/politics/policy/trump-says...
23,28,2026-07-11-20-22-06 +0000,nypost,Family National Tennis Center creator claims U...,https://nypost.com/2026/07/11/us-news/family-o...
184,28,2026-07-11-00-23-01 +0000,nypost,10 killed in Bahamas plane crash as frightenin...,https://nypost.com/2026/07/10/world-news/10-ki...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)