## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-10-00-00 +0000,wsj,Hasbro’s ‘Aging Up’ Strategy Continues With a ...,https://www.wsj.com/cmo-today/hasbros-aging-up...
1,2026-07-09-10-00-00 +0000,nypost,Thirty state treasurers urge Trump to release ...,https://nypost.com/2026/07/09/business/thirty-...
2,2026-07-09-09-56-20 +0000,nyt,A Landfill in Indonesia Caught Fire Over a Wee...,https://www.nytimes.com/2026/07/09/world/asia/...
3,2026-07-09-09-53-21 +0000,bbc,US and Iran trade strikes for second night in ...,https://www.bbc.co.uk/news/articles/cz75zjj5wp...
4,2026-07-09-09-51-04 +0000,nyt,"U.S. Launches New Strikes on Iran, Military Says",https://www.nytimes.com/live/2026/07/08/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
12     trump     57
25      iran     44
36      nato     21
159  platner     21
39       out     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” Trump said of the ...",https://www.wsj.com/world/middle-east/inside-t...,173
359,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...,160
392,2026-07-08-11-27-45 +0000,cbc,Carney backs latest U.S. strikes on Iran as Tr...,https://www.cbc.ca/news/politics/iran-war-us-c...,150
282,2026-07-08-17-27-18 +0000,nypost,"Trump ditches new Air Force One in Turkey, sto...",https://nypost.com/2026/07/08/us-news/trump-wo...,147
3,2026-07-09-09-53-21 +0000,bbc,US and Iran trade strikes for second night in ...,https://www.bbc.co.uk/news/articles/cz75zjj5wp...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,173,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” Trump said of the ...",https://www.wsj.com/world/middle-east/inside-t...
359,160,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...
237,54,2026-07-08-19-26-00 +0000,wsj,Fed officials weighed rate hikes last month as...,https://www.wsj.com/economy/central-banking/fe...
104,52,2026-07-09-01-46-27 +0000,nypost,Scarsdale 26-year-old charged with stabbing an...,https://nypost.com/2026/07/08/us-news/scarsdal...
162,52,2026-07-08-22-09-12 +0000,nypost,United Airlines must face lawsuit after allege...,https://nypost.com/2026/07/08/business/united-...
69,50,2026-07-09-04-16-08 +0000,nypost,Ex-Redlands deputy police chief was California...,https://nypost.com/2026/07/09/us-news/former-r...
194,47,2026-07-08-20-58-21 +0000,bbc,"Justin Bieber joins Madonna, Shakira and BTS f...",https://www.bbc.co.uk/news/articles/c1wyx7g9e1...
219,41,2026-07-08-19-57-32 +0000,nypost,Here’s why Trump threatened to cut off trade w...,https://nypost.com/2026/07/08/us-news/heres-wh...
361,40,2026-07-08-14-11-00 +0000,wsj,ADP to Launch Monthly Pay Tracking Indicator i...,https://www.wsj.com/economy/jobs/adp-to-launch...
216,37,2026-07-08-20-06-00 +0000,wsj,Treasury Yields Rise Sharply as War Flare Up R...,https://www.wsj.com/finance/jgbs-fall-tracking...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)