## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-01-17-14 +0000,nypost,Wrexham AFC making Yankee Stadium debut during...,https://nypost.com/2026/03/04/sports/wrexham-m...
1,2026-03-05-01-17-13 +0000,nyt,Progressive Challenger Concedes in N.C.’s Blue...,https://www.nytimes.com/2026/03/04/us/election...
2,2026-03-05-01-16-12 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/04/us/pri...
3,2026-03-05-01-15-00 +0000,wsj,Oil Rises on Prospects of Prolonged Supply Dis...,https://www.wsj.com/finance/commodities-future...
4,2026-03-05-01-12-07 +0000,startribune,Live updates from boys hockey Class 1A quarter...,https://www.startribune.com/minnesota-boys-hoc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
91       iran     82
45        war     48
74      trump     37
286     texas     22
242  conflict     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
78,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...,213
330,2026-03-04-13-53-32 +0000,cbc,Two Blocks from the White House: Trump’s ‘no r...,https://www.cbc.ca/news/politics/two-blocks-fr...,198
71,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...,198
50,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,197
91,2026-03-04-22-32-09 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,196

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
78,213,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...
308,123,2026-03-04-15-10-00 +0000,wsj,Incumbent Sen. John Cornyn and Texas Attorney ...,https://www.wsj.com/politics/elections/john-co...
409,77,2026-03-04-07-09-00 +0000,wsj,"Asian Equities Fall, Oil Rises Amid Ongoing Mi...",https://www.wsj.com/finance/stocks/asian-equit...
300,74,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
232,65,2026-03-04-18-19-00 +0000,wsj,Global authorities must step up their surveill...,https://www.wsj.com/economy/central-banking/re...
350,52,2026-03-04-12-30-52 +0000,nypost,US sub sinks Iranian warship named after terro...,https://nypost.com/2026/03/04/world-news/irani...
422,44,2026-03-04-03-44-09 +0000,nyt,"Beyond a Trade War, China, Japan and Others in...",https://www.nytimes.com/2026/03/02/business/us...
93,44,2026-03-04-22-28-44 +0000,latimes,Top tech companies sign Trump's pledge to prov...,https://www.latimes.com/environment/story/2026...
166,43,2026-03-04-20-26-24 +0000,nypost,Cartel boss El Mencho’s daughter found running...,https://nypost.com/2026/03/04/world-news/carte...
316,40,2026-03-04-14-55-30 +0000,bbc,Israel tells people in large parts of southern...,https://www.bbc.com/news/articles/cvg11pne0rro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)