## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-03-44-43 +0000,bbc,Indonesia airports reopen after volcano erupti...,https://www.bbc.co.uk/news/articles/czezydp4l9...
1,2026-09-08-03-20-15 +0000,nypost,Outrage as Georgetown students reportedly plan...,https://nypost.com/2026/09/07/us-news/georgeto...
2,2026-09-08-03-15-00 +0000,wsj,Yen Strengthens Further; Sentiment Toward Curr...,https://www.wsj.com/finance/currencies/yen-str...
3,2026-09-08-03-13-00 +0000,wsj,Yen Hits Six-Month High Against Dollar on BOJ ...,https://www.wsj.com/finance/currencies/yen-hit...
4,2026-09-08-03-12-00 +0000,wsj,"Now 25 years after 9/11, can American politics...",https://www.wsj.com/politics/how-the-unity-of-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
158  trump     21
298    new     20
53   plane     14
81     day     13
197  cargo     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
105,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...,104
177,2026-09-07-13-26-01 +0000,nyt,Trump Posts Map Suggesting New Mexico Be Renam...,https://www.nytimes.com/2026/09/07/us/politics...,78
145,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...,68
69,2026-09-07-21-03-56 +0000,nypost,Amazon cargo jet pilot miraculously escapes fi...,https://nypost.com/2026/09/07/us-news/amazon-c...,67
144,2026-09-07-15-15-14 +0000,chitri,Fuel prices at record Labor Day high in US tha...,https://www.chicagotribune.com/2026/09/07/fuel...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
105,104,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
145,68,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...
69,67,2026-09-07-21-03-56 +0000,nypost,Amazon cargo jet pilot miraculously escapes fi...,https://nypost.com/2026/09/07/us-news/amazon-c...
148,46,2026-09-07-15-03-22 +0000,chitri,AfD party’s landslide win in eastern Germany t...,https://www.chicagotribune.com/2026/09/07/afd-...
79,34,2026-09-07-20-11-43 +0000,cbc,Trump to Canadian plane maker Bombardier: You ...,https://www.cbc.ca/news/canada/trump-bombardie...
56,32,2026-09-07-21-59-12 +0000,nypost,Mainstream TV vague about airing first-ever GO...,https://nypost.com/2026/09/07/us-news/tv-netwo...
130,32,2026-09-07-16-20-04 +0000,chitri,King Charles clarifies status of Prince Harry ...,https://www.chicagotribune.com/2026/09/07/king...
186,29,2026-09-07-12-23-21 +0000,nypost,Iran says it plans to create new ‘restricted z...,https://nypost.com/2026/09/07/world-news/iran-...
50,29,2026-09-07-22-29-10 +0000,nypost,"Pregnant California mom, 22, has life support ...",https://nypost.com/2026/09/07/us-news/pregnant...
59,28,2026-09-07-21-43-04 +0000,nypost,NYC Council Speaker Menin launches PAC to aid ...,https://nypost.com/2026/09/07/us-news/nyc-coun...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)