## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-23-12-46 +0000,nypost,"California wildfire survivor rips insurers, st...",https://nypost.com/2026/05/13/us-news/californ...
1,2026-05-13-23-12-29 +0000,nypost,South Carolina gov expected to demand special ...,https://nypost.com/2026/05/13/us-news/south-ca...
2,2026-05-13-23-12-10 +0000,nypost,American Airlines flight gets two flat tires a...,https://nypost.com/2026/05/13/us-news/american...
3,2026-05-13-23-10-51 +0000,nyt,New Mexico Diocese Tries to Block Government F...,https://www.nytimes.com/2026/05/13/us/politics...
4,2026-05-13-23-08-37 +0000,bbc,Why big tech is betting on cute mascots,https://www.bbc.com/news/articles/c99l1zzp8xzo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2673/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
88        trump     55
31          new     29
91        china     25
0    california     20
107        iran     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...,130
64,2026-05-13-21-29-00 +0000,wsj,"Kevin Warsh is officially the new Fed chair, t...",https://www.wsj.com/politics/policy/warsh-conf...,125
236,2026-05-13-15-04-52 +0000,nyt,Trump Is in China as Iran War Continues With N...,https://www.nytimes.com/2026/05/13/world/middl...,122
204,2026-05-13-16-53-28 +0000,nyt,"For Trump, the Iran War Looms Over China Summit",https://www.nytimes.com/2026/05/13/us/politics...,119
405,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,130,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...
64,125,2026-05-13-21-29-00 +0000,wsj,"Kevin Warsh is officially the new Fed chair, t...",https://www.wsj.com/politics/policy/warsh-conf...
32,61,2026-05-13-22-29-26 +0000,latimes,Vance says $1.3 billion in Medicaid payments t...,https://www.latimes.com/california/story/2026-...
386,47,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
167,46,2026-05-13-18-19-07 +0000,nyt,Alex Murdaugh Murder Convictions Overturned by...,https://www.nytimes.com/2026/05/13/us/murdaugh...
405,45,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
286,43,2026-05-13-13-00-00 +0000,missionlocal,One S.F. judge candidate is out raising her op...,https://missionlocal.org/2026/05/s-f-judge-can...
152,42,2026-05-13-18-58-39 +0000,nypost,Immigrant-led business group builds $1M war ch...,https://nypost.com/2026/05/13/business/mamdani...
96,41,2026-05-13-20-47-18 +0000,cbc,FAA adding transponders to all its airport veh...,https://www.cbc.ca/news/world/transponders-air...
24,40,2026-05-13-22-42-00 +0000,wsj,The Pentagon abruptly canceled deployment of a...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)