## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-10-03-39 +0000,nypost,Contender’s latest ping reveals location of la...,https://nypost.com/2026/07/01/us-news/contende...
1,2026-07-01-10-02-57 +0000,bbc,Refunds: Hidden Tricks,https://www.bbc.co.uk/videos/cj6gd0j702go?at_m...
2,2026-07-01-10-01-38 +0000,bbc,Burnham's chancellor will have to find extra £...,https://www.bbc.co.uk/news/articles/cy9rgg9ddw...
3,2026-07-01-10-00-01 +0000,nyt,3 People Die During World Cup Celebrations in ...,https://www.nytimes.com/2026/07/01/world/ameri...
4,2026-07-01-10-00-00 +0000,nypost,Ex-NYT journo Alex Berenson tells ‘Pod Force O...,https://nypost.com/2026/07/01/us-news/ex-nyt-j...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2645/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
133        trump     41
259        court     38
258      supreme     37
165          new     19
66   citizenship     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
351,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...,168
344,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,166
79,2026-07-01-05-32-26 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,160
279,2026-06-30-18-01-23 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,160
234,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
351,168,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...
21,78,2026-07-01-09-30-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
347,53,2026-06-30-14-43-47 +0000,nypost,Russia-linked Ukrainian oligarch injured in Mo...,https://nypost.com/2026/06/30/world-news/wife-...
230,50,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
120,47,2026-07-01-01-24-59 +0000,nyt,Driver Is Reported Dead Days After Plowing Int...,https://www.nytimes.com/2026/06/30/world/ameri...
332,38,2026-06-30-15-21-52 +0000,nypost,GOP Rep. Tom Kean Jr. reveals reason behind my...,https://nypost.com/2026/06/30/us-news/gop-rep-...
141,38,2026-07-01-00-05-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
257,37,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
212,37,2026-06-30-21-03-05 +0000,nypost,California Dems push wartime price gouging cra...,https://nypost.com/2026/06/30/us-news/californ...
228,37,2026-06-30-20-22-00 +0000,wsj,"Stocks rise, the yen slides and a quiet Fed on...",https://www.wsj.com/finance/stocks/stocks-rise...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)