## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-04-07-42-56 +0000,bbc,Five dead in Moscow as Ukraine continues wareh...,https://www.bbc.co.uk/news/articles/c151pkww79...
1,2026-08-04-07-31-44 +0000,nyt,Saudi Aramco Reports 33% Profit Surge Despite ...,https://www.nytimes.com/2026/08/04/business/sa...
2,2026-08-04-07-25-51 +0000,wsj,Stock Market Today: Stocks Poised to Extend Ga...,https://www.wsj.com/livecoverage/stock-market-...
3,2026-08-04-07-25-00 +0000,wsj,"European Indexes Rise in Strong Open as AI, De...",https://www.wsj.com/finance/stocks/nikkei-rise...
4,2026-08-04-07-22-25 +0000,nypost,Dashcam shows Florida trooper chasing alleged ...,https://nypost.com/2026/08/04/us-news/dashcam-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
63   trump     55
103   iran     24
117    new     16
126    oil     15
282    out     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
123,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...,140
271,2026-08-03-14-20-54 +0000,nypost,"Dow soars nearly 700 points to record, oil sli...",https://nypost.com/2026/08/03/business/dow-soa...,137
280,2026-08-03-13-38-30 +0000,chitri,President Trump optimistic Iran talks will reo...,https://www.chicagotribune.com/2026/08/03/trum...,132
79,2026-08-04-00-17-48 +0000,bbc,Why is Trump Media selling early access to Tru...,https://www.bbc.co.uk/news/videos/c74g0q8eey9o...,128
126,2026-08-03-21-49-00 +0000,wsj,"Trump discusses Jeanine Pirro’s removal, Iran ...",https://www.wsj.com/politics/policy/trump-disc...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
123,140,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...
161,97,2026-08-03-20-40-00 +0000,wsj,Two holdout GOP senators who were blocking act...,https://www.wsj.com/politics/policy/blanche-fo...
76,58,2026-08-04-00-25-00 +0000,wsj,"Trump has discussed ousting Jeanine Pirro, the...",https://www.wsj.com/politics/policy/trump-says...
44,57,2026-08-04-03-08-00 +0000,wsj,President Trump told embattled Rep. Max Miller...,https://www.wsj.com/politics/elections/trump-w...
226,57,2026-08-03-16-56-02 +0000,nypost,Elon Musk’s SpaceX aims to shake off AI spendi...,https://nypost.com/2026/08/03/business/elon-mu...
50,56,2026-08-04-02-38-00 +0000,nypost,Hasan Piker marvels at ‘white dude bros’ suppo...,https://nypost.com/2026/08/03/us-news/abdul-el...
273,50,2026-08-03-14-17-36 +0000,nypost,NJ diners fume over new ‘Skip the Stuff’ law a...,https://nypost.com/2026/08/03/us-news/nj-diner...
189,47,2026-08-03-19-16-37 +0000,nypost,Trump gives Iran ‘last chance’ to sign deal be...,https://nypost.com/2026/08/03/us-news/trump-gi...
84,42,2026-08-04-00-00-00 +0000,wsj,A little-used Fed backstop is being put to a u...,https://www.wsj.com/economy/central-banking/wh...
23,41,2026-08-04-05-52-00 +0000,wsj,"HSBC Posts Sharply Higher Quarterly Profit, Pl...",https://www.wsj.com/business/earnings/hsbc-pos...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)