## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-10-05-32 +0000,nyt,Fire Destroys Sacred Buddhist Hall in Japan th...,https://www.nytimes.com/2026/05/21/world/asia/...
1,2026-05-21-10-00-01 +0000,wapo,Subpoena bill would curtail secretive tool use...,https://www.washingtonpost.com/nation/2026/05/...
2,2026-05-21-10-00-00 +0000,wsj,U.S. to Award Quantum Computing Firms $2 Billi...,https://www.wsj.com/tech/u-s-to-award-quantum-...
3,2026-05-21-10-00-00 +0000,nypost,Son of Sam killer David Berkowitz predicts he’...,https://nypost.com/2026/05/21/us-news/son-of-s...
4,2026-05-21-09-59-13 +0000,wapo,"In rare clash, North Korea defeats South Korea...",https://www.washingtonpost.com/world/2026/05/2...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2652/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
54   trump     52
57     new     24
163   iran     16
56    cuba     15
80   ebola     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...,131
137,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,117
150,2026-05-20-23-26-30 +0000,nyt,Trump’s Government Moves to Spare an Unhappy T...,https://www.nytimes.com/2026/05/20/us/politics...,116
306,2026-05-20-16-57-10 +0000,nypost,Trump says Netanyahu will do ‘whatever I want ...,https://nypost.com/2026/05/20/world-news/trump...,105
114,2026-05-21-02-00-00 +0000,wsj,"With Castro Indictment, Trump Bets His Venezue...",https://www.wsj.com/world/americas/with-castro...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,131,2026-05-20-20-03-00 +0000,wsj,Q&A: Here’s what to know about the Trump admin...,https://www.wsj.com/politics/policy/what-to-kn...
300,74,2026-05-20-17-11-00 +0000,wsj,The GOP-controlled House passed a new version ...,https://www.wsj.com/politics/policy/newly-pass...
137,65,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
385,57,2026-05-20-10-48-00 +0000,wsj,EU negotiators reached a provisional deal to r...,https://www.wsj.com/economy/trade/eu-reaches-a...
166,57,2026-05-20-22-21-10 +0000,nypost,Mango CEO Isak Andic’s son learned father was ...,https://nypost.com/2026/05/20/world-news/mango...
377,49,2026-05-20-11-29-42 +0000,nypost,Iran vows to attack nations outside Middle Eas...,https://nypost.com/2026/05/20/world-news/iran-...
239,49,2026-05-20-19-46-00 +0000,wsj,Federal Reserve officials all but retired the ...,https://www.wsj.com/economy/central-banking/fe...
162,46,2026-05-20-22-33-35 +0000,nypost,Nvidia’s revenue hits record $81B — easily top...,https://nypost.com/2026/05/20/business/nvidias...
3,46,2026-05-21-10-00-00 +0000,nypost,Son of Sam killer David Berkowitz predicts he’...,https://nypost.com/2026/05/21/us-news/son-of-s...
352,45,2026-05-20-13-52-32 +0000,nypost,WHO says risk of Ebola outbreak spreading glob...,https://nypost.com/2026/05/20/world-news/who-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)