## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-29-18-56-00 +0000,wsj,Opinion | How the U.S. Can Strengthen Its Dies...,https://www.wsj.com/opinion/how-the-u-s-can-st...
1,2026-09-29-18-56-00 +0000,wsj,Opinion | Rethinking Political Polling in the ...,https://www.wsj.com/opinion/rethinking-politic...
2,2026-09-29-18-55-15 +0000,nypost,"Violent pair pistol-whips man, steals luxury w...",https://nypost.com/2026/09/29/us-news/violent-...
3,2026-09-29-18-55-14 +0000,nyt,Chartering a Boat on the Kuskokwim River to Re...,https://www.nytimes.com/2026/09/29/us/charteri...
4,2026-09-29-18-55-00 +0000,wsj,Opinion | AI Regulation Needs to Look Beyond A...,https://www.wsj.com/opinion/ai-regulation-need...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3178/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
57   trump     43
52     new     24
7       ai     18
635    oil     14
96    will     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
376,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...,209
93,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...,117
436,2026-09-28-19-15-55 +0000,wapo,Trump says new fuel economy rules will cut car...,https://www.washingtonpost.com/transportation/...,114
424,2026-09-28-19-37-09 +0000,chitri,President Trump announces a new $15B Iowa stee...,https://www.chicagotribune.com/2026/09/28/trum...,111
163,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
376,209,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...
55,68,2026-09-29-17-22-18 +0000,nyt,Prime Minister Andy Burnham Lays Out Plan to C...,https://www.nytimes.com/2026/09/29/world/europ...
282,56,2026-09-29-08-19-57 +0000,wsj,Stock Market Today: Treasury Yields Push Highe...,https://www.wsj.com/livecoverage/stock-market-...
223,56,2026-09-29-11-00-57 +0000,chitri,News organizations ask court to bar White Hous...,https://www.chicagotribune.com/2026/09/29/news...
163,52,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...
43,51,2026-09-29-17-47-07 +0000,nypost,Baby girl with six toes is found dead in dumps...,https://nypost.com/2026/09/29/us-news/baby-gir...
441,46,2026-09-28-19-01-59 +0000,nypost,AI agents could spark bank runs by yanking cas...,https://nypost.com/2026/09/28/business/ai-agen...
27,46,2026-09-29-18-14-48 +0000,chitri,Pete Hegseth says national security and milita...,https://www.chicagotribune.com/2026/09/29/pete...
24,44,2026-09-29-18-22-23 +0000,nypost,Tennessee’s first female death row inmate in 2...,https://nypost.com/2026/09/29/us-news/tennesse...
409,42,2026-09-28-20-05-26 +0000,nyt,Release of Suspects in U.K. Prompts New Questi...,https://www.nytimes.com/2026/09/28/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)