## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-23-07-40-53 +0000,bbc,Putin vows retaliation after accusing Ukraine ...,https://www.bbc.com/news/articles/c5y74lwx395o...
1,2026-05-23-07-25-28 +0000,nypost,‘Illicit’ version of fentanyl linked to deadly...,https://nypost.com/2026/05/23/us-news/illicit-...
2,2026-05-23-07-23-55 +0000,bbc,Attorney general to review teen boys' rape sen...,https://www.bbc.com/news/articles/cwy2x7wxjego...
3,2026-05-23-07-13-53 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
4,2026-05-23-07-01-49 +0000,nypost,At least 90 dead in China coal mine explosion,https://nypost.com/2026/05/23/world-news/china...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2303/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
51   trump     44
13     new     24
82    iran     17
114  ebola     15
622     up     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...,138
62,2026-05-23-00-00-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,136
307,2026-05-22-10-00-01 +0000,wapo,Trump offered White South Africans a new life....,https://www.washingtonpost.com/nation/2026/05/...,105
289,2026-05-22-11-00-00 +0000,nypost,How Kevin Warsh will navigate his tricky new p...,https://nypost.com/2026/05/22/business/how-kev...,105
80,2026-05-22-23-06-58 +0000,nypost,Trump touts GOP backed-tax cuts for New Yorker...,https://nypost.com/2026/05/22/us-news/trump-to...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,138,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...
232,59,2026-05-22-15-08-54 +0000,nypost,Dow soars 300 points to an all-time high — fir...,https://nypost.com/2026/05/22/business/dow-soa...
294,59,2026-05-22-10-52-48 +0000,nypost,Feds dramatically drop charges against Illinoi...,https://nypost.com/2026/05/22/us-news/feds-dro...
212,53,2026-05-22-16-30-51 +0000,cbc,No Ebola cases in Canada and no new hantavirus...,https://www.cbc.ca/news/health/livestory/phac-...
189,52,2026-05-22-17-43-00 +0000,wsj,Most green-card applicants will need to go abr...,https://www.wsj.com/politics/policy/trump-admi...
200,44,2026-05-22-17-13-00 +0000,wsj,China and Russia have in recent years expanded...,https://www.wsj.com/politics/national-security...
84,42,2026-05-22-22-47-45 +0000,cbc,911 audio reveals NASCAR's Kyle Busch was shor...,https://www.cbc.ca/sports/kyle-busch-death-fol...
62,38,2026-05-23-00-00-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...
80,34,2026-05-22-23-06-58 +0000,nypost,Trump touts GOP backed-tax cuts for New Yorker...,https://nypost.com/2026/05/22/us-news/trump-to...
173,33,2026-05-22-18-33-08 +0000,nypost,Putin accuses Ukraine of drone attack on stude...,https://nypost.com/2026/05/22/world-news/putin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)