## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-08-08-41-00 +0000,wsj,"Oil Rises, U.S. Stock Futures Lower as Sentime...",https://www.wsj.com/finance/stocks/oil-rises-u...
1,2026-07-08-08-38-24 +0000,bbc,Virgin Media fined £28m for preventing custome...,https://www.bbc.co.uk/news/articles/c982vm2jzl...
2,2026-07-08-08-38-21 +0000,nypost,"Trump says Iran cease-fire is ‘over,’ vows to ...",https://nypost.com/2026/07/08/us-news/trump-sa...
3,2026-07-08-08-35-27 +0000,wapo,Trump declares ceasefire with Iran has ended,https://www.washingtonpost.com/world/2026/07/0...
4,2026-07-08-08-22-00 +0000,wsj,"U.S., European Government Bond Yields Rise as ...",https://www.wsj.com/finance/investing/u-s-euro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2390/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
14      iran     27
13     trump     26
50       new     21
185     nato     17
453  platner     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
130,2026-07-07-22-37-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...,144
312,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...,137
65,2026-07-08-02-50-01 +0000,startribune,"US launches new strikes on Iran, revokes oil s...",https://www.startribune.com/tanker-set-ablaze-...,100
317,2026-07-07-13-21-21 +0000,cbc,French far-right leader Marine Le Pen to run f...,https://www.cbc.ca/news/world/france-court-mar...,91
308,2026-07-07-13-47-57 +0000,nypost,Nigel Farage reveals he’s quitting parliament ...,https://nypost.com/2026/07/07/world-news/nigel...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
130,144,2026-07-07-22-37-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...
317,91,2026-07-07-13-21-21 +0000,cbc,French far-right leader Marine Le Pen to run f...,https://www.cbc.ca/news/world/france-court-mar...
13,83,2026-07-08-07-45-37 +0000,wsj,Stock Market Today: Oil Jumps After Trump Says...,https://www.wsj.com/livecoverage/stock-market-...
308,66,2026-07-07-13-47-57 +0000,nypost,Nigel Farage reveals he’s quitting parliament ...,https://nypost.com/2026/07/07/world-news/nigel...
298,57,2026-07-07-14-31-57 +0000,bbc,"Next PM needs to wake UK up to threat of war, ...",https://www.bbc.co.uk/news/articles/cddljy1y3n...
17,44,2026-07-08-07-26-49 +0000,bbc,Watch: Gaza football fans watch World Cup from...,https://www.bbc.co.uk/news/videos/c8r2nmm7xeeo...
312,44,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
65,40,2026-07-08-02-50-01 +0000,startribune,"US launches new strikes on Iran, revokes oil s...",https://www.startribune.com/tanker-set-ablaze-...
103,35,2026-07-08-00-15-56 +0000,wapo,Foreign media were granted rare visas to cover...,https://www.washingtonpost.com/world/2026/07/0...
23,34,2026-07-08-06-36-42 +0000,nypost,"Scuba diving instructor charged after tourist,...",https://nypost.com/2026/07/08/world-news/scuba...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)