## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-13-00-00 +0000,wsj,A SpaceX Vehicle Is This Island’s Most Talked ...,https://www.wsj.com/science/space-astronomy/a-...
1,2026-08-22-13-00-00 +0000,missionlocal,"A second sun rises in San Francisco, on Philip...",https://missionlocal.org/2026/08/sf-philippine...
2,2026-08-22-13-00-00 +0000,missionlocal,A garden of delights,https://missionlocal.org/2026/08/a-garden-of-d...
3,2026-08-22-12-56-47 +0000,nyt,How the Billionaire Joe Lonsdale Shaped Trump’...,https://www.nytimes.com/2026/08/22/us/politics...
4,2026-08-22-12-50-24 +0000,nyt,Why Polling Chaos Could Create Big Problems fo...,https://www.nytimes.com/2026/08/22/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2600/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18     trump     51
33    canada     14
640    court     12
45        up     11
28   tariffs     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
121,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...,131
184,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,129
227,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,128
64,2026-08-22-09-00-00 +0000,wsj,President Trump is quietly making plans for an...,https://www.wsj.com/politics/policy/trump-new-...,118
109,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
121,131,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...
81,98,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
109,53,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
232,41,2026-08-21-18-22-00 +0000,nyt,"Prince Harry, Elton John and Others Told to Pa...",https://www.nytimes.com/2026/08/21/world/europ...
51,40,2026-08-22-09-03-47 +0000,nyt,How a Progressive Democrat in Florida Gave Her...,https://www.nytimes.com/2026/08/22/us/politics...
174,37,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
143,35,2026-08-21-22-08-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
283,34,2026-08-21-14-41-40 +0000,nyt,Iran Must Plan to Overcome U.S. Sanctions Afte...,https://www.nytimes.com/2026/08/21/world/middl...
79,33,2026-08-22-05-33-59 +0000,nypost,Parents of Pennsylvania soccer player Karoline...,https://nypost.com/2026/08/22/us-news/pennwest...
88,32,2026-08-22-03-59-37 +0000,nypost,California Dem earning $207K taxpayer salary t...,https://nypost.com/2026/08/21/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)