## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-08-41-20 +0000,bbc,Most bus fares in England to be capped at £2 f...,https://www.bbc.co.uk/news/articles/cz64l78n5v...
1,2026-07-22-08-39-11 +0000,nyt,K-pop’s NewJeans Hints at Comeback After Month...,https://www.nytimes.com/2026/07/22/world/asia/...
2,2026-07-22-08-39-00 +0000,wsj,Airbus Shares Climb on Midterm Profitability Goal,https://www.wsj.com/business/earnings/airbus-s...
3,2026-07-22-08-38-21 +0000,bbc,Police station opens at Hitler's birthplace in...,https://www.bbc.co.uk/news/articles/cy5d36e752...
4,2026-07-22-08-37-13 +0000,bbc,More Russian online retailer Wildberries sites...,https://www.bbc.co.uk/news/articles/c36de9n4px...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2527/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
121       trump     48
256        iran     36
122         new     23
54          war     21
406  california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
157,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,149
103,2026-07-22-00-01-00 +0000,wsj,Defense Secretary Pete Hegseth estimated the l...,https://www.wsj.com/politics/national-security...,132
396,2026-07-21-09-49-42 +0000,nyt,Trump Administration and Iran Officials Risk a...,https://www.nytimes.com/2026/07/20/world/middl...,119
284,2026-07-21-16-22-24 +0000,nypost,Trump warns Iran of much greater destruction i...,https://nypost.com/2026/07/21/us-news/trump-wa...,119
16,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
157,149,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
16,115,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...
99,59,2026-07-22-00-29-59 +0000,nypost,Fourth soldier believed to be killed in Iran a...,https://nypost.com/2026/07/21/us-news/fourth-s...
268,48,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
261,47,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
371,41,2026-07-21-11-30-00 +0000,missionlocal,S.F. high-tech police surveillance center gets...,https://missionlocal.org/2026/07/san-francisco...
387,40,2026-07-21-10-00-39 +0000,chitri,Illinois SNAP costs: State wins one-year delay...,https://www.chicagotribune.com/2026/07/21/snap...
153,39,2026-07-21-21-31-13 +0000,nyt,Trump Officials Withhold $1 Billion in Medicai...,https://www.nytimes.com/2026/07/21/us/politics...
183,36,2026-07-21-20-45-37 +0000,cbc,Zelenskyy replaces head of Ukraine's army amid...,https://www.cbc.ca/news/world/zelenskyy-syrsky...
14,34,2026-07-22-08-02-04 +0000,bbc,India's Modi government under growing pressure...,https://www.bbc.co.uk/news/articles/c9d8p88lyj...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)