## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-20-08-58-26 +0000,bbc,Suspect arrested after historic town hall set ...,https://www.bbc.co.uk/news/articles/cw5yn5e8me...
1,2026-10-20-08-56-00 +0000,wsj,Oil Prices Rise with Brent Futures Above $110 ...,https://www.wsj.com/business/energy-oil/oil-pr...
2,2026-10-20-08-55-02 +0000,bbc,Burnham vows end to 'rip-off parking charges' ...,https://www.bbc.co.uk/news/articles/ck87ze7wl4...
3,2026-10-20-08-55-00 +0000,wsj,Gold Slips as Investors Await Fed Meeting Next...,https://www.wsj.com/finance/commodities-future...
4,2026-10-20-08-53-27 +0000,nyt,Houthi Strikes Kill Dozens in Yemeni Desert Mi...,https://www.nytimes.com/2026/10/19/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2605/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
111       trump     28
29          new     17
173          up     16
390  california     15
8        french     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
133,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...,144
329,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...,104
177,2026-10-19-20-00-16 +0000,nypost,"Trump again blows up on Zelensky, insists Russ...",https://nypost.com/2026/10/19/us-news/trump-ri...,80
118,2026-10-19-21-49-41 +0000,nyt,DOJ Charges 28 California Residents With Votin...,https://www.nytimes.com/2026/10/19/us/politics...,79
266,2026-10-19-15-31-08 +0000,nypost,Donald Trump signs executive order creating NI...,https://nypost.com/2026/10/19/us-news/donald-t...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
133,144,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...
318,57,2026-10-19-11-41-24 +0000,bbc,Personal attacks fire up debate before Brazil'...,https://www.bbc.co.uk/news/articles/ck98zlzyql...
249,53,2026-10-19-16-42-59 +0000,nypost,Christiane Amanpour to exit CNN amid staffer c...,https://nypost.com/2026/10/19/media/christiane...
111,53,2026-10-19-22-04-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
60,50,2026-10-20-02-00-00 +0000,nypost,Halloween horror as shooting breaks out during...,https://nypost.com/2026/10/19/us-news/gunfire-...
192,45,2026-10-19-19-31-37 +0000,nypost,Sweat pants-clad video game store worker prais...,https://nypost.com/2026/10/19/world-news/frenc...
279,41,2026-10-19-14-24-00 +0000,nypost,Rubio slaps down Zelensky’s claims of US cutti...,https://nypost.com/2026/10/19/us-news/rubio-sa...
265,40,2026-10-19-15-44-00 +0000,wsj,Economists surveyed by The Wall Street Journal...,https://www.wsj.com/finance/see-what-71-econom...
235,39,2026-10-19-17-24-12 +0000,nypost,Why Obama admin put Abdul El-Sayed’s sister-in...,https://nypost.com/2026/10/19/us-news/heres-wh...
198,39,2026-10-19-19-22-36 +0000,nypost,Ex-boss of Italy’s oldest bank accused of tryi...,https://nypost.com/2026/10/19/business/ex-boss...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)