## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-11-00-00 +0000,wsj,Why Your Condo Association Might Be Raising Yo...,https://www.wsj.com/finance/regulation/why-you...
1,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...
2,2026-08-09-11-00-00 +0000,missionlocal,"Of the thousands who attend Outside Lands, som...",https://missionlocal.org/2026/08/sf-outside-la...
3,2026-08-09-10-02-52 +0000,bbc,Suspected crime boss Daniel Kinahan returning ...,https://www.bbc.co.uk/news/articles/c62qd5plzp...
4,2026-08-09-10-00-17 +0000,chitri,Patients in Illinois starting to receive exper...,https://www.chicagotribune.com/2026/08/09/dara...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2334/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     15
14      iran     10
11    hormuz      7
201  blanche      6
422      new      6

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...,49
132,2026-08-08-15-45-32 +0000,chitri,Todd Blanche is narrowly confirmed as Trump’s ...,https://www.chicagotribune.com/2026/08/08/todd...,42
104,2026-08-08-18-56-45 +0000,nypost,Trump could consider taking out Pickaxe Mounta...,https://nypost.com/2026/08/08/us-news/irans-pi...,42
98,2026-08-08-19-18-57 +0000,bbc,"Hormuz talks positive, Oman says, as Iran warn...",https://www.bbc.co.uk/news/articles/c934j5y2lq...,41
130,2026-08-08-15-56-39 +0000,bbc,Trump's ex-lawyer Todd Blanche narrowly confir...,https://www.bbc.co.uk/news/articles/cewr898jy8...,39

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,49,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...
127,36,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
152,30,2026-08-08-12-53-31 +0000,wapo,"Senate narrowly approves Todd Blanche as AG, c...",https://www.washingtonpost.com/national-securi...
36,26,2026-08-09-06-10-47 +0000,nypost,Indian national allegedly killed Arizona girlf...,https://nypost.com/2026/08/09/us-news/indian-n...
55,26,2026-08-09-01-00-53 +0000,nypost,California housing crisis laid bare in shockin...,https://nypost.com/2026/08/08/us-news/californ...
62,24,2026-08-09-00-13-02 +0000,nypost,"NYC woman warns against getting painful, blist...",https://nypost.com/2026/08/08/us-news/margarit...
142,23,2026-08-08-14-39-26 +0000,nyt,Canada Offers U.S. Concessions in Trade Talks ...,https://www.nytimes.com/2026/08/07/world/canad...
13,21,2026-08-09-09-19-40 +0000,nypost,Naked champion swimmer accused of beating secu...,https://nypost.com/2026/08/09/us-news/hawaii-n...
97,20,2026-08-08-19-27-36 +0000,nypost,Billionaire heiress who backed Mamdani now sho...,https://nypost.com/2026/08/08/us-news/billiona...
149,20,2026-08-08-13-22-43 +0000,nyt,Democrats Vow to Unite Behind Abdul El-Sayed i...,https://www.nytimes.com/2026/08/08/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)