## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-20-20-58-00 +0000,wsj,Deepening Energy Crisis Sends Stocks to Fourth...,https://www.wsj.com/finance/stocks/deepening-e...
1,2026-03-20-20-57-47 +0000,startribune,"There are 100,000 traffic cases in Hennepin Co...",https://www.startribune.com/there-are-100000-t...
2,2026-03-20-20-57-00 +0000,wsj,Opinion | Why the Trump FCC Cares About Your S...,https://www.wsj.com/opinion/why-the-trump-fcc-...
3,2026-03-20-20-57-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-oil/energy...
4,2026-03-20-20-57-00 +0000,wsj,"Heavy Rains Flood Oahu, Threatening Wahiawa Dam",https://www.wsj.com/us-news/hawaii-flood-oahu-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19   trump     41
70    iran     41
71     war     25
1   energy     16
15     new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
332,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...,156
356,2026-03-19-23-19-00 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...,137
24,2026-03-20-20-27-24 +0000,nypost,"Trump vows no cease-fire with Iran, predicts S...",https://nypost.com/2026/03/20/world-news/trump...,122
8,2026-03-20-20-55-01 +0000,nyt,Iran War Live Updates: U.S. Steps Up Attacks i...,https://www.nytimes.com/live/2026/03/20/world/...,120
234,2026-03-20-10-47-00 +0000,wsj,"In Nearly 90 Truth Social Posts, Trump Narrate...",https://www.wsj.com/politics/policy/in-nearly-...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
332,156,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...
326,66,2026-03-20-01-00-00 +0000,wsj,A New York congressional race has a new X fact...,https://www.wsj.com/politics/policy/ai-lobbyin...
8,54,2026-03-20-20-55-01 +0000,nyt,Iran War Live Updates: U.S. Steps Up Attacks i...,https://www.nytimes.com/live/2026/03/20/world/...
133,51,2026-03-20-16-30-54 +0000,nyt,"Educators, How Will You Teach Cesar Chavez’s S...",https://www.nytimes.com/2026/03/20/us/cesar-ch...
355,44,2026-03-19-23-23-00 +0000,wsj,A federal panel approved a commemorative gold ...,https://www.wsj.com/politics/policy/trump-gold...
304,42,2026-03-20-03-22-17 +0000,nypost,Japanese prime minister wishes ‘good looking’ ...,https://nypost.com/2026/03/19/us-news/japanese...
231,41,2026-03-20-10-55-24 +0000,nypost,University of Alabama student James Gracey see...,https://nypost.com/2026/03/20/world-news/unive...
135,40,2026-03-20-16-30-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
88,39,2026-03-20-18-19-51 +0000,nypost,UK to let US use its bases for strikes to help...,https://nypost.com/2026/03/20/world-news/uk-to...
184,38,2026-03-20-14-22-00 +0000,wsj,Tech Exec Accused of Smuggling High-End Nvidia...,https://www.wsj.com/tech/super-micro-computer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)