## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-06-19-13-00 +0000,wsj,U.S. Natural Gas Edges Up in Rangebound Trade,https://www.wsj.com/articles/u-s-natural-gas-f...
1,2026-04-06-19-10-18 +0000,nyt,Iran War Live Updates: Trump Renews Threat of ...,https://www.nytimes.com/live/2026/04/06/world/...
2,2026-04-06-19-09-00 +0000,wsj,Treasury Yields Decline as a Belligerent Trump...,https://www.wsj.com/finance/jgbs-fall-on-growi...
3,2026-04-06-19-06-00 +0000,wsj,Crude Futures Edge Up As Trump’s Iran Deadline...,https://www.wsj.com/finance/commodities-future...
4,2026-04-06-19-04-00 +0000,startribune,Newcomers heighten St. Paul’s Lowertown Sounds...,https://www.startribune.com/newcomers-heighten...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2457/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
6      iran     40
10    trump     37
7       war     19
3        up     11
374  easter      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
121,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...,145
201,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...,139
154,2026-04-06-07-21-36 +0000,wsj,Stock Market Today: Stocks Edge Higher Amid Tr...,https://www.wsj.com/livecoverage/stock-market-...,122
129,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-annual...,119
1,2026-04-06-19-10-18 +0000,nyt,Iran War Live Updates: Trump Renews Threat of ...,https://www.nytimes.com/live/2026/04/06/world/...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
121,145,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...
129,79,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-annual...
46,37,2026-04-06-17-28-10 +0000,nypost,Trump reveals amazing new details of the rescu...,https://nypost.com/2026/04/06/us-news/trump-re...
67,35,2026-04-06-16-29-51 +0000,nypost,"Trump, first lady Melania tell children of Ira...",https://nypost.com/2026/04/06/us-news/trump-fi...
156,35,2026-04-06-06-33-20 +0000,nypost,Two top Iranian military leaders wiped out dur...,https://nypost.com/2026/04/06/world-news/us-is...
210,32,2026-04-05-20-22-21 +0000,nypost,Ex-California governor makes bold prediction o...,https://nypost.com/2026/04/05/us-news/gray-dav...
99,32,2026-04-06-14-23-41 +0000,nypost,Supreme Court sets stage for DOJ to toss crimi...,https://nypost.com/2026/04/06/us-news/supreme-...
98,27,2026-04-06-14-27-23 +0000,nypost,"Oil prices seesaw, gas creeps further past $4 ...",https://nypost.com/2026/04/06/business/oil-pri...
47,25,2026-04-06-17-24-15 +0000,nypost,Dramatic moment Israeli woman knocked to the g...,https://nypost.com/2026/04/06/world-news/video...
19,23,2026-04-06-18-31-12 +0000,nypost,Sicko stayed coldly silent in sex attack on NY...,https://nypost.com/2026/04/06/us-news/sicko-st...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)