## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-05-16-17-00 +0000,wsj,Opinion | A Tax Break for Foreigners and Trial...,https://www.wsj.com/opinion/a-tax-break-for-fo...
1,2026-05-05-16-15-06 +0000,nyt,"With Free Vodka, and a Few Protests, Russia Re...",https://www.nytimes.com/2026/05/05/arts/design...
2,2026-05-05-16-14-16 +0000,bbc,Hate crime prosecutions to be fast-tracked aft...,https://www.bbc.com/news/articles/cz72eye5zzeo...
3,2026-05-05-16-10-46 +0000,nyt,Iran War Live Updates: U.S. and Iran Both Clai...,https://www.nytimes.com/live/2026/05/05/world/...
4,2026-05-05-16-08-17 +0000,nyt,Maersk Ship Passed Strait of Hormuz Under U.S....,https://www.nytimes.com/2026/05/05/business/ma...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
257   trump     30
20     iran     24
326     new     17
27   strait     15
28   hormuz     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
216,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...,132
66,2026-05-05-14-33-10 +0000,nypost,Iran hits UAE with drones and missile attacks ...,https://nypost.com/2026/05/05/world-news/iran-...,112
3,2026-05-05-16-10-46 +0000,nyt,Iran War Live Updates: U.S. and Iran Both Clai...,https://www.nytimes.com/live/2026/05/05/world/...,101
43,2026-05-05-15-04-00 +0000,wsj,President Trump escalated his public feud with...,https://www.wsj.com/politics/national-security...,91
218,2026-05-04-23-52-35 +0000,nypost,Trump is trying to force the Strait of Hormuz ...,https://nypost.com/2026/05/04/world-news/trump...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
216,132,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...
6,65,2026-05-05-15-59-44 +0000,nypost,Cruise ship infected with terrifying hantaviru...,https://nypost.com/2026/05/05/world-news/cruis...
265,61,2026-05-04-21-30-31 +0000,nypost,Ex-JPMorgan banker Chirayu Rana files wild new...,https://nypost.com/2026/05/04/business/ex-jpmo...
188,51,2026-05-05-04-25-49 +0000,bbc,Deadly China plane crash was caused by fuel cu...,https://www.bbc.com/news/articles/ckgpy223y9go...
186,45,2026-05-05-04-34-15 +0000,bbc,US strikes Iranian fast boats as Iran attacks ...,https://www.bbc.com/news/articles/cjwp432d0v5o...
332,40,2026-05-04-17-52-47 +0000,nypost,Elon Musk pressured OpenAI’s Greg Brockman to ...,https://nypost.com/2026/05/04/business/elon-mu...
142,37,2026-05-05-10-00-00 +0000,nypost,Ron DeSantis making moves for 2028 White House...,https://nypost.com/2026/05/05/us-news/ron-desa...
317,35,2026-05-04-18-40-26 +0000,nypost,New Mexico’s proposed kids safety fixes for In...,https://nypost.com/2026/05/04/business/new-mex...
295,35,2026-05-04-20-03-07 +0000,nypost,Gap co‑founder Doris Fisher — driving force be...,https://nypost.com/2026/05/04/business/gap-cof...
292,33,2026-05-04-20-09-35 +0000,nypost,California governor’s race on a knife edge as ...,https://nypost.com/2026/05/04/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)