## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-03-01-17-20 +0000,nyt,Many Children Don’t Have ‘Trump Accounts.’ Som...,https://www.nytimes.com/2026/07/02/upshot/trum...
1,2026-07-03-01-10-37 +0000,nypost,Popular outdoor retailer announces ‘mega adven...,https://nypost.com/2026/07/02/us-news/popular-...
2,2026-07-03-01-08-51 +0000,missionlocal,The Valkyries are nearly halfway through the s...,https://missionlocal.org/2026/07/golden-state-...
3,2026-07-03-01-00-00 +0000,wsj,"Halfway through the year, the labor market is ...",https://www.wsj.com/economy/jobs/this-years-jo...
4,2026-07-03-01-00-00 +0000,wsj,How Bezos Learned to Love Trump—and Win More C...,https://www.wsj.com/business/jeff-bezos-donald...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
2         trump     38
281         new     15
42   california     12
339          up     12
571      russia     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
25,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...,118
285,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,90
311,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...,83
340,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...,83
121,2026-07-02-20-08-00 +0000,wsj,"What to know about ‘Trump Accounts,’ the new s...",https://www.wsj.com/personal-finance/trump-acc...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
25,118,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...
197,59,2026-07-02-15-32-34 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
217,58,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
156,53,2026-07-02-18-23-50 +0000,nyt,June Jobs Report Shows US Labor Market Making ...,https://www.nytimes.com/2026/07/02/business/ec...
288,49,2026-07-02-10-21-05 +0000,cbc,"Deadly, large-scale Russian attack shakes Kyiv...",https://www.cbc.ca/news/world/missile-drone-at...
22,44,2026-07-03-00-04-16 +0000,nypost,Costco announces all California stores to shut...,https://nypost.com/2026/07/02/business/costco-...
51,44,2026-07-02-22-57-52 +0000,nypost,"Up-and-coming NYC drill rapper, dad of 3-year-...",https://nypost.com/2026/07/02/us-news/nyc-dril...
335,42,2026-07-02-03-00-00 +0000,wsj,Europe Learns It’s Hard to Start a Trade War W...,https://www.wsj.com/world/china/europe-learns-...
123,41,2026-07-02-20-06-19 +0000,nyt,Putin Retaliates With New Strikes After Ukrain...,https://www.nytimes.com/2026/07/02/world/europ...
311,38,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)