## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-25-17-04-52 +0000,nypost,Harrowing 911 call reveals horror details of B...,https://nypost.com/2026/08/25/us-news/harrowin...
1,2026-08-25-17-04-11 +0000,nypost,Bitcoin briefly surges past $80K as crypto ral...,https://nypost.com/2026/08/25/business/bitcoin...
2,2026-08-25-17-02-00 +0000,wsj,Dick’s Sporting Goods Bet Big on Sneakers With...,https://www.wsj.com/business/retail/dicks-spor...
3,2026-08-25-17-00-00 +0000,wapo,Most of northwestern Indiana now has power res...,https://www.washingtonpost.com/nation/2026/08/...
4,2026-08-25-16-56-39 +0000,nypost,"Teen charged 17 months after his mom, half-bro...",https://nypost.com/2026/08/25/us-news/utah-tee...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2510/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
70    trump     53
424    iran     28
123  canada     26
414     new     22
64       up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
43,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...,162
204,2026-08-25-03-57-01 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,156
22,2026-08-25-16-34-25 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,149
116,2026-08-25-12-33-40 +0000,nypost,Trump threatens to rename Lake Ontario as ‘Lak...,https://nypost.com/2026/08/25/us-news/trump-th...,149
263,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...,143

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
43,162,2026-08-25-15-45-57 +0000,nyt,Trump Threatens to Rename Lake Ontario to Lake...,https://www.nytimes.com/2026/08/25/us/politics...
263,90,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...
138,78,2026-08-25-11-14-00 +0000,wsj,Michigan’s Abdul El-Sayed will need to win ove...,https://www.wsj.com/politics/elections/four-ta...
298,65,2026-08-24-21-05-13 +0000,latimes,"To further isolate Iran's economy, U.S. rolls ...",https://www.latimes.com/politics/story/2026-08...
266,43,2026-08-24-22-26-45 +0000,chitri,Canada will announce retaliatory tariffs again...,https://www.chicagotribune.com/2026/08/24/trum...
76,41,2026-08-25-14-40-52 +0000,nypost,CIA Director John Ratcliffe secretly traveled ...,https://nypost.com/2026/08/25/us-news/cia-dire...
215,41,2026-08-25-02-14-00 +0000,wsj,The Trump administration is planning what may ...,https://www.wsj.com/politics/policy/trump-admi...
186,37,2026-08-25-08-19-42 +0000,wsj,Stock Market Today: Stocks Advance as Effects ...,https://www.wsj.com/livecoverage/stock-market-...
242,34,2026-08-24-23-52-00 +0000,wsj,A super PAC aligned with President Trump is op...,https://www.wsj.com/politics/elections/trump-a...
244,34,2026-08-24-23-45-34 +0000,nyt,Someone Was Impersonating Collien Fernandes On...,https://www.nytimes.com/2026/08/23/magazine/co...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)