## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-23-11-50-36 +0000,bbc,Kenya minister halts construction of US-backed...,https://www.bbc.co.uk/news/articles/c4gy6vk44p...
1,2026-06-23-11-50-18 +0000,nyt,40 People Drown in France as Heat Wave Persists,https://www.nytimes.com/2026/06/23/world/europ...
2,2026-06-23-11-42-34 +0000,bbc,Farage says £5m gift spending details 'not pub...,https://www.bbc.co.uk/news/articles/cn0vx2edk0...
3,2026-06-23-11-40-57 +0000,bbc,Reflecting Pool to be drained as Trump again b...,https://www.bbc.co.uk/news/articles/c5yzpjd1nj...
4,2026-06-23-11-40-30 +0000,nyt,Charisma Alone Can’t Fix Britain,https://www.nytimes.com/2026/06/22/world/brita...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2582/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
22     trump     29
233     iran     27
182      new     19
201  starmer     14
351     will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
146,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...,92
265,2026-06-22-17-00-39 +0000,nyt,How Will Colombia’s New President Fuel Trump’s...,https://www.nytimes.com/2026/06/22/world/ameri...,83
164,2026-06-22-21-51-37 +0000,bbc,What does Trump want from a new UK prime minis...,https://www.bbc.co.uk/news/videos/c2kyz2eqxwvo...,82
295,2026-06-22-15-30-00 +0000,wsj,The Supreme Court is about to decide four case...,https://www.wsj.com/politics/policy/the-suprem...,80
50,2026-06-23-09-48-33 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
146,92,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...
50,78,2026-06-23-09-48-33 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
154,70,2026-06-22-22-47-27 +0000,nyt,Iran Team Leaves Locker Room Note: The ‘Spirit...,https://www.nytimes.com/2026/06/22/world/middl...
249,61,2026-06-22-17-38-00 +0000,wsj,Alan Greenspan’s legacy explained: how the Fed...,https://www.wsj.com/economy/central-banking/al...
260,58,2026-06-22-17-17-00 +0000,wsj,Supreme Court Reinstates Conviction in Murder ...,https://www.wsj.com/us-news/law/scotus-etan-pa...
224,47,2026-06-22-19-08-00 +0000,bbc,Messi becomes World Cup all-time leading score...,https://www.bbc.co.uk/sport/football/articles/...
355,47,2026-06-22-12-00-00 +0000,wsj,Chevron Strikes Power Deal With Microsoft for ...,https://www.wsj.com/business/energy-oil/chevro...
297,44,2026-06-22-15-23-41 +0000,cbc,"U.S. to permit Iranian oil sales, easing decad...",https://www.cbc.ca/news/world/united-states-ir...
71,43,2026-06-23-09-00-00 +0000,wsj,A generational battle is playing out in the De...,https://www.wsj.com/politics/elections/the-gen...
279,41,2026-06-22-16-09-49 +0000,cbc,"Music industry giant Clive Davis, who signed B...",https://www.cbc.ca/news/entertainment/clive-da...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)