## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-10-18-07 +0000,nyt,Live Updates: G7 Leaders Praise Trump for U.S....,https://www.nytimes.com/live/2026/06/17/world/...
1,2026-06-17-10-09-00 +0000,wsj,ECB’s Tracker Continues to Point to Slower Wag...,https://www.wsj.com/pro/central-banking/ecbs-t...
2,2026-06-17-10-08-44 +0000,bbc,Streeting suggests he would be prepared to tri...,https://www.bbc.com/news/articles/c4gyeg2207yo...
3,2026-06-17-10-01-42 +0000,bbc,Israel launches fresh strikes on Lebanon despi...,https://www.bbc.com/news/articles/c7vyn17g832o...
4,2026-06-17-10-00-00 +0000,latimes,"Barabak: Gerrymanders, judges and an alley-oop...",https://www.latimes.com/politics/story/2026-06...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     31
339    new     25
5     iran     24
475    war     15
6     deal     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
216,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...,103
181,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...,96
129,2026-06-17-00-38-52 +0000,nyt,"Mike Collins, Endorsed by Trump, Wins Georgia ...",https://www.nytimes.com/2026/06/16/us/politics...,93
95,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...,89
369,2026-06-16-10-33-20 +0000,nypost,Trump says Israel taking ‘too long’ to fight H...,https://nypost.com/2026/06/16/us-news/trump-is...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
216,103,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...
95,89,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
181,69,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
234,64,2026-06-16-19-29-38 +0000,cbc,"The Grammys add 5 new categories, announce cha...",https://www.cbc.ca/news/entertainment/grammys-...
101,57,2026-06-17-02-50-36 +0000,nypost,Bungee instructors who tossed student off 130-...,https://nypost.com/2026/06/16/world-news/bunge...
121,50,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
207,45,2026-06-16-20-59-31 +0000,cbc,Ghanaian midfielder Thomas Partey loses bid to...,https://www.cbc.ca/news/canada/ghana-partey-ca...
29,41,2026-06-17-09-21-00 +0000,wsj,Oil Supply Could Far Outstrip Demand Growth if...,https://www.wsj.com/business/energy-oil/oil-su...
22,40,2026-06-17-09-46-31 +0000,bbc,Group planned to attack White House UFC event ...,https://www.bbc.com/news/articles/cqx10xlje1lo...
120,38,2026-06-17-01-01-33 +0000,nyt,Kevin Hern Wins Republican Primary for Oklahom...,https://www.nytimes.com/2026/06/16/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)