## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-10-16-56-32 +0000,bbc,Several injured in attack on airport in Saudi ...,https://www.bbc.co.uk/news/articles/cw33x4y8k8...
1,2026-10-10-16-52-13 +0000,nyt,Palestinian Authority Formally Delays Election...,https://www.nytimes.com/2026/10/10/world/middl...
2,2026-10-10-16-51-39 +0000,nypost,Kratom industry engaged in multimillion lobbyi...,https://nypost.com/2026/10/10/us-news/kratom-i...
3,2026-10-10-16-50-45 +0000,nyt,Indian Police Round Up Protest Leaders and Loc...,https://www.nytimes.com/2026/10/10/world/asia/...
4,2026-10-10-16-48-57 +0000,nypost,Weather service issues terrifying warning for ...,https://nypost.com/2026/10/10/us-news/bay-area...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
62       trump     44
60         new     18
49   execution     16
111         he     15
530     senate     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...,181
212,2026-10-09-21-24-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,121
143,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...,117
141,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...,114
204,2026-10-09-21-37-18 +0000,nyt,Katie Zacharia Picked as Trump’s New White Hou...,https://www.nytimes.com/2026/10/09/us/politics...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,181,2026-10-09-21-45-00 +0000,wsj,President Trump says he struck a deal with Rus...,https://www.wsj.com/politics/policy/trump-says...
178,74,2026-10-09-22-23-48 +0000,nypost,Kalshi probes shady bets on new White House pr...,https://nypost.com/2026/10/09/business/kalshi-...
172,57,2026-10-09-22-38-00 +0000,wsj,The planned execution of Nidal Hasan has spark...,https://www.wsj.com/politics/national-security...
141,55,2026-10-10-01-41-44 +0000,nypost,Trump goes off on Norway for awarding Nobel Pe...,https://nypost.com/2026/10/09/us-news/trump-go...
246,45,2026-10-09-19-55-00 +0000,wapo,Ocasio-Cortez will stump for Abdul El-Sayed in...,https://www.washingtonpost.com/politics/2026/1...
75,43,2026-10-10-10-06-23 +0000,bbc,Rogue Anthropic AI agent gave police fake tip ...,https://www.bbc.co.uk/news/articles/cqkg50j1yd...
23,41,2026-10-10-15-31-00 +0000,wsj,Iran-Backed Houthis Hit Saudi Capital’s Airpor...,https://www.wsj.com/world/middle-east/iran-bac...
143,37,2026-10-10-01-23-00 +0000,wsj,President Trump said his administration has re...,https://www.wsj.com/politics/policy/trump-stri...
251,35,2026-10-09-19-33-00 +0000,wsj,Oil Prices Steady After Trump Appears to Rule ...,https://www.wsj.com/business/energy-oil/oil-pr...
30,35,2026-10-10-15-00-00 +0000,wsj,While pushback against data centers is well-kn...,https://www.wsj.com/politics/elections/will-vo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)