## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-15-23-07-09 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/07/15/world/...
1,2026-07-15-23-05-24 +0000,nypost,State senator fearlessly breaks up bloody NYC ...,https://nypost.com/2026/07/15/us-news/state-se...
2,2026-07-15-23-03-58 +0000,nyt,"Ukraine’s Minister of Defense, a Proponent of ...",https://www.nytimes.com/2026/07/15/world/europ...
3,2026-07-15-23-03-34 +0000,nyt,Boat That Sank Near Alcatraz Rolled After Wave...,https://www.nytimes.com/2026/07/15/us/alcatraz...
4,2026-07-15-23-02-36 +0000,nyt,U.S. Military Again Blockades Iranian Ports Af...,https://www.nytimes.com/2026/07/15/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     42
0     iran     35
292  china     17
1      war     17
410    new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...,146
380,2026-07-14-23-17-27 +0000,bbc,Trump retreat over Hormuz tolls suggests he is...,https://www.bbc.co.uk/news/articles/crele3r8j1...,119
104,2026-07-15-20-26-19 +0000,nypost,"Trump doesn’t rule out decimating IRGC, warns ...",https://nypost.com/2026/07/15/us-news/trump-do...,119
293,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...,119
164,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,146,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...
164,76,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...
293,67,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...
232,62,2026-07-15-14-08-00 +0000,wsj,The economy has added jobs for four straight m...,https://www.wsj.com/economy/jobs/unemployment-...
13,50,2026-07-15-22-50-00 +0000,wsj,Homeland Security Secretary Markwayne Mullin a...,https://www.wsj.com/politics/policy/trump-was-...
204,47,2026-07-15-15-51-44 +0000,nypost,Intrusive way California will target billionai...,https://nypost.com/2026/07/15/us-news/intrusiv...
155,42,2026-07-15-18-11-53 +0000,nyt,One Dead and Three Missing in San Francisco Ba...,https://www.nytimes.com/2026/07/14/us/boat-fir...
329,40,2026-07-15-08-47-32 +0000,nypost,Ex-UK government minister Ann Widdecombe kille...,https://nypost.com/2026/07/15/world-news/uk-po...
80,39,2026-07-15-21-08-26 +0000,cbc,Argentina makes late comeback to secure World ...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
160,38,2026-07-15-18-01-00 +0000,wsj,SpaceX Shares Fall Below IPO Price for the Fir...,https://www.wsj.com/finance/stocks/spacex-shar...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)