## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-10-21-00-47 +0000,missionlocal,DA: S.F. man who fought Mayor Lurie’s security...,https://missionlocal.org/2026/03/daniel-lurie-...
1,2026-03-10-21-00-27 +0000,nypost,Wealthy summer hotspot hires patrol ‘docents’ ...,https://nypost.com/2026/03/10/us-news/wealthy-...
2,2026-03-10-20-56-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/finance/investing/tech-med...
3,2026-03-10-20-54-12 +0000,nyt,"ChatGPT, Other Chatbots Approved for Official ...",https://www.nytimes.com/2026/03/10/us/politics...
4,2026-03-10-20-54-02 +0000,nyt,U.S. Showers Iran With Bombs in Most Intense S...,https://www.nytimes.com/2026/03/10/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
32    iran     71
37     war     50
52   trump     39
186    oil     31
400    new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
231,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...,229
294,2026-03-10-03-15-14 +0000,nyt,Trump Seeks to Calm Oil and Gas Markets but Sa...,https://www.nytimes.com/2026/03/09/us/politics...,225
292,2026-03-10-03-24-00 +0000,wsj,"Oil Retreats, Asia Equities Rebound After Trum...",https://www.wsj.com/finance/stocks/oil-retreat...,208
291,2026-03-10-03-32-18 +0000,nyt,"Trump’s War in Iran, and Rising Gas Prices, Co...",https://www.nytimes.com/2026/03/09/us/politics...,196
205,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...,192

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
231,229,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...
205,64,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...
217,55,2026-03-10-11-24-12 +0000,nypost,Trump says he doesn’t think new Iran leader Mo...,https://nypost.com/2026/03/10/us-news/trump-sa...
258,52,2026-03-10-09-16-08 +0000,nypost,Five members of Iranian women’s soccer team gr...,https://nypost.com/2026/03/10/world-news/austr...
243,42,2026-03-10-10-00-00 +0000,latimes,DTLA law firm co-founder faces California Stat...,https://www.latimes.com/california/story/2026-...
32,40,2026-03-10-20-11-56 +0000,nypost,15-year-old NYC boy wanted for assault busted ...,https://nypost.com/2026/03/10/us-news/boy-15-w...
213,40,2026-03-10-11-42-00 +0000,wsj,Saudi Arabia Pushes East-West Pipeline Toward ...,https://www.wsj.com/business/energy-oil/saudi-...
371,38,2026-03-09-21-52-00 +0000,wsj,Lawrence Summers has lost his affiliation with...,https://www.wsj.com/us-news/education/national...
264,34,2026-03-10-08-57-00 +0000,wsj,Lego Sales Outpace Global Toy Market to Hit Ne...,https://www.wsj.com/business/earnings/lego-sal...
378,33,2026-03-09-21-37-51 +0000,cbc,What do you get when you win the U.K. Wife Car...,https://www.cbc.ca/radio/asithappens/uk-wife-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)