## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-16-59-28 +0000,missionlocal,「我們需要一首短歌」：要通過加州財富稅，選民會知道要投「贊成—反對—反對」嗎？,https://missionlocal.org/2026/10/california-bi...
1,2026-10-08-16-58-23 +0000,missionlocal,三藩市最富有的人士對市內政治的掌控前所未有,https://missionlocal.org/2026/10/san-francisco...
2,2026-10-08-16-56-13 +0000,nyt,Indian Opposition Leaders Detained as Protests...,https://www.nytimes.com/2026/10/08/world/asia/...
3,2026-10-08-16-55-21 +0000,nypost,Trans NYT exec was pregnant but had miscarriag...,https://nypost.com/2026/10/08/us-news/nyt-exec...
4,2026-10-08-16-54-37 +0000,bbc,Outspoken Indian actor Nana Patekar dies sudde...,https://www.bbc.co.uk/news/articles/cj3vqr5rkn...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
63       trump     56
31      school     32
943    chicago     27
1151     board     25
1128  district     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
229,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...,141
233,2026-10-08-10-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...,140
232,2026-10-08-10-00-08 +0000,chitri,2026 Chicago school board races: District 6A,https://www.chicagotribune.com/2026/10/08/chic...,131
234,2026-10-08-10-00-04 +0000,chitri,2026 Chicago school board races: District 2B,https://www.chicagotribune.com/2026/10/08/chic...,131
228,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: District 9A,https://www.chicagotribune.com/2026/10/08/chic...,131

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
229,141,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...
390,127,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
395,111,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
204,75,2026-10-08-10-15-58 +0000,chitri,Will County 2nd District race is a repeat of 2...,https://www.chicagotribune.com/2026/10/08/will...
139,61,2026-10-08-13-55-12 +0000,nypost,"Oil prices jump 5%, pushing Treasury yields hi...",https://nypost.com/2026/10/08/business/oil-pri...
323,59,2026-10-08-03-02-06 +0000,bbc,Texas carries out first US execution since Chr...,https://www.bbc.co.uk/news/articles/cw4g1j2z5z...
454,52,2026-10-07-19-42-35 +0000,cbc,'Canada is not our enemy': Michigan Republican...,https://www.cbc.ca/news/world/michigan-republi...
484,51,2026-10-07-18-24-00 +0000,wsj,Fed officials didn’t make an urgent case for a...,https://www.wsj.com/economy/central-banking/fe...
79,49,2026-10-08-15-41-18 +0000,wapo,At least 30 dead in Russian bus strike as Mosc...,https://www.washingtonpost.com/world/2026/10/0...
102,49,2026-10-08-15-02-36 +0000,wapo,Search warrants against former prince Andrew w...,https://www.washingtonpost.com/world/2026/10/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)