## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-00-06-24 +0000,nyt,Pentagon Changes How It Reports Casualties in ...,https://www.nytimes.com/2026/07/26/us/politics...
1,2026-07-27-00-00-00 +0000,wsj,Waymo Is Racking Up Thousands of Dollars of Pa...,https://www.wsj.com/business/autos/waymo-is-ra...
2,2026-07-26-23-58-00 +0000,wsj,"Gold Gains as U.S., Iran Pause Fighting Over W...",https://www.wsj.com/finance/commodities-future...
3,2026-07-26-23-48-04 +0000,nypost,"Blakeman, Jewish leaders slam Mamdani at NYC r...",https://nypost.com/2026/07/26/us-news/blakeman...
4,2026-07-26-23-44-00 +0000,wsj,Oil Falls Amid Easing Supply-Disruption Concerns,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2659/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
154   trump     19
4      iran     16
214  berlin     10
215   pride     10
5       war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
100,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,61
118,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,60
125,2026-07-26-12-49-15 +0000,nyt,U.S.-Iran War Pauses for 2nd Straight Day With...,https://www.nytimes.com/2026/07/26/world/middl...,57
106,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...,54
124,2026-07-26-13-00-01 +0000,cbc,Suspect in deadly Berlin Pride attack killed i...,https://www.cbc.ca/news/world/berlin-pride-att...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
100,61,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
106,54,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...
125,31,2026-07-26-12-49-15 +0000,nyt,U.S.-Iran War Pauses for 2nd Straight Day With...,https://www.nytimes.com/2026/07/26/world/middl...
21,29,2026-07-26-22-18-27 +0000,nyt,Extreme Heat and Strong Winds Fuel New Wildfir...,https://www.nytimes.com/live/2026/07/26/world/...
79,29,2026-07-26-18-22-19 +0000,nypost,Jeffries won’t rule out vote to abolish ICE if...,https://nypost.com/2026/07/26/us-news/jeffries...
65,25,2026-07-26-19-26-56 +0000,nypost,Teen handyman accused of killing ‘sweetest’ el...,https://nypost.com/2026/07/26/us-news/troubled...
138,24,2026-07-26-10-00-00 +0000,wsj,A documentary filmmaker followed Sen. Lindsey ...,https://www.wsj.com/politics/national-security...
69,24,2026-07-26-19-07-31 +0000,nypost,Raging DNC boss Ken Martin threw phone at aide...,https://nypost.com/2026/07/26/us-news/raging-d...
178,22,2026-07-26-00-49-13 +0000,nypost,Mamdani’s municipal bond mess will only get wo...,https://nypost.com/2026/07/25/business/mamdani...
57,22,2026-07-26-20-24-41 +0000,nypost,Smoking gun letter reveals LAUSD ignored dire ...,https://nypost.com/2026/07/26/us-news/smoking-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)