## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-23-42-35 +0000,nyt,"U.N. Live Updates: As Trump Threatens Iran, Ot...",https://www.nytimes.com/live/2026/09/22/world/...
1,2026-09-22-23-36-12 +0000,bbc,US judge blocks deportation of DoorDash driver...,https://www.bbc.co.uk/news/articles/cr62418257...
2,2026-09-22-23-34-12 +0000,nypost,California high-speed rail suffers fresh blow ...,https://nypost.com/2026/09/22/us-news/californ...
3,2026-09-22-23-33-24 +0000,nyt,"Trump Officials Eject 750,000 From Obamacare M...",https://www.nytimes.com/2026/09/22/us/politics...
4,2026-09-22-23-29-52 +0000,nyt,Rollerblading Norwegian Dies After Being Hit b...,https://www.nytimes.com/2026/09/22/us/rollerbl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
2    trump     89
4     iran     31
186    new     28
211     he     24
122   will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...,211
132,2026-09-22-20-27-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,210
73,2026-09-22-21-44-00 +0000,wsj,Delegates from Iran and Cuba walked out during...,https://www.wsj.com/politics/policy/trump-thre...,196
343,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...,196
32,2026-09-22-22-49-15 +0000,nyt,Trump Threatens Annihilation in Iran in UN Spe...,https://www.nytimes.com/2026/09/22/us/politics...,189

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,211,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...
132,90,2026-09-22-20-27-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
413,74,2026-09-22-02-43-52 +0000,bbc,Watch: Six-year-old girl from China sets new R...,https://www.bbc.co.uk/news/videos/cmvgyzgnq9e3...
343,64,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...
66,47,2026-09-22-21-55-04 +0000,chitri,"‘You should not be here,’ President Trump tell...",https://www.chicagotribune.com/2026/09/22/trum...
16,45,2026-09-22-23-10-16 +0000,nypost,Rare sea turtle lays eggs on OC beach for firs...,https://nypost.com/2026/09/22/us-news/rare-sea...
48,44,2026-09-22-22-29-52 +0000,nypost,California high school mysteriously pulls its ...,https://nypost.com/2026/09/22/us-news/central-...
389,43,2026-09-22-08-37-04 +0000,wsj,"Stock Market News, Sept. 22, 2026: Oil Sinks B...",https://www.wsj.com/livecoverage/stock-market-...
54,43,2026-09-22-22-21-19 +0000,cbc,Man shot by ICE agent in Texas being treated f...,https://www.cbc.ca/news/world/venezuelan-natio...
44,41,2026-09-22-22-31-25 +0000,nypost,Zelensky calls on Trump to use Graham Sanction...,https://nypost.com/2026/09/22/us-news/zelensky...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)