## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-06-04-06-11 +0000,nyt,Park Ranger Dies After Falling Into a Crevasse...,https://www.nytimes.com/2026/06/05/us/national...
1,2026-06-06-04-01-18 +0000,nyt,"Laboring Under Delhi’s Harsh Heat, Workers Mus...",https://www.nytimes.com/2026/06/06/world/asia/...
2,2026-06-06-04-01-13 +0000,nypost,"Brush fire scorches 1,600 acres across LA and ...",https://nypost.com/2026/06/06/us-news/macy-fir...
3,2026-06-06-04-01-08 +0000,nyt,Mali Conflict Escalates as Rebel Alliance Seiz...,https://www.nytimes.com/2026/06/06/world/afric...
4,2026-06-06-04-01-06 +0000,nyt,"A President, His Prime Minister and the Bitter...",https://www.nytimes.com/2026/06/06/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
122       trump     26
607      market     12
262         new     12
91        putin     11
177  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,90
163,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,82
146,2026-06-05-18-17-24 +0000,nypost,Trump must ‘accept the reality’ there is no I...,https://nypost.com/2026/06/05/world-news/jack-...,74
171,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,73
62,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,90,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
31,59,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...
83,51,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
72,48,2026-06-05-21-51-59 +0000,nyt,"Amid Graham Platner Controversy, Where Does th...",https://www.nytimes.com/2026/06/05/us/politics...
62,45,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...
34,44,2026-06-06-01-00-00 +0000,wsj,Kevin Warsh faces early Fed pressure as strong...,https://www.wsj.com/economy/central-banking/ke...
220,36,2026-06-05-14-15-02 +0000,nyt,How the Job Market Is Leaving New Graduates Be...,https://www.nytimes.com/video/business/1000000...
194,33,2026-06-05-15-58-12 +0000,nypost,Ex-Prince Andrew made money subletting 3 cotta...,https://nypost.com/2026/06/05/world-news/ex-pr...
59,33,2026-06-05-22-39-52 +0000,nypost,First images of ‘Top Gun: Maverick’ actor’s al...,https://nypost.com/2026/06/05/us-news/video-sh...
5,32,2026-06-06-03-46-01 +0000,nypost,Minnesota driver accused of killing 82-year-ol...,https://nypost.com/2026/06/05/us-news/minnesot...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)