## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-06-14-39-01 +0000,nypost,Lindsay Clancy’s sobs heard in courtroom as me...,https://nypost.com/2026/08/06/us-news/lindsay-...
1,2026-08-06-14-34-40 +0000,nyt,What Is Fauci Being Accused of and Why Is He B...,https://www.nytimes.com/2026/08/05/us/politics...
2,2026-08-06-14-33-29 +0000,bbc,EasyJet agrees to £5.7bn takeover by US firm,https://www.bbc.co.uk/news/articles/cjejzjpy98...
3,2026-08-06-14-32-00 +0000,wsj,Dollar Could Retrace Recent Falls But Only in ...,https://www.wsj.com/finance/currencies/asian-c...
4,2026-08-06-14-28-59 +0000,wapo,Senate panel votes to hold Anthony Fauci in co...,https://www.washingtonpost.com/politics/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
396     new     28
29   senate     28
161   trump     27
494      el     23
495   sayed     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
284,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...,177
218,2026-08-05-23-34-00 +0000,wsj,"Poll after poll had signaled Abdul El-Sayed, a...",https://www.wsj.com/politics/elections/pollste...,156
399,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...,154
76,2026-08-06-12-07-58 +0000,nyt,El-Sayed’s Michigan Senate Primary Win Sets Up...,https://www.nytimes.com/2026/08/05/us/politics...,146
378,2026-08-05-16-12-00 +0000,wsj,Progressive Abdul El-Sayed won the Michigan De...,https://www.wsj.com/politics/elections/michiga...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
284,177,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...
15,94,2026-08-06-14-00-00 +0000,wsj,A Republican-led Senate panel voted to hold Dr...,https://www.wsj.com/politics/policy/senate-pan...
202,89,2026-08-06-01-00-00 +0000,wsj,President Trump has spoken repeatedly with Kev...,https://www.wsj.com/politics/policy/trump-has-...
398,68,2026-08-05-15-03-44 +0000,nypost,"Disney earnings boosted by ‘Toy Story 5’, them...",https://nypost.com/2026/08/05/business/disney-...
323,52,2026-08-05-19-14-31 +0000,chitri,No evidence? No problem. President Donald Trum...,https://www.chicagotribune.com/2026/08/05/trum...
248,52,2026-08-05-21-58-00 +0000,wsj,The Senate confirmed Dr. Erica Schwartz as dir...,https://www.wsj.com/politics/policy/senate-con...
196,46,2026-08-06-02-03-14 +0000,nypost,Donald Trump fires up Vegas crowd with tax cut...,https://nypost.com/2026/08/05/us-news/presiden...
305,37,2026-08-05-20-12-41 +0000,latimes,"She stabbed her husband to death, then, decade...",https://www.latimes.com/california/story/2026-...
393,37,2026-08-05-15-31-37 +0000,nyt,Russia’s Deadly Missile Attack on Kyiv Exploit...,https://www.nytimes.com/2026/08/05/world/europ...
125,37,2026-08-06-10-00-00 +0000,startribune,"A house, a car, a little breathing room: Why m...",https://www.startribune.com/middle-class-incom...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)