## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-19-22-55-37 +0000,bbc,Australia 'outraged' after Israeli decision no...,https://www.bbc.co.uk/news/articles/cp87g29r71...
1,2026-08-19-22-52-58 +0000,nyt,Senate Health Panel Chairman Voices Strong Res...,https://www.nytimes.com/2026/08/19/us/politics...
2,2026-08-19-22-46-24 +0000,nypost,City takes prospective vendors for Mamdani’s p...,https://nypost.com/2026/08/19/us-news/city-tak...
3,2026-08-19-22-46-23 +0000,nypost,California political candidate accused of elec...,https://nypost.com/2026/08/19/us-news/californ...
4,2026-08-19-22-43-57 +0000,nypost,Blueberry recall over deadly E. coli fears hit...,https://nypost.com/2026/08/19/lifestyle/greenw...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
123    trump     63
121  florida     29
400  primary     16
169       up     15
9     senate     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
402,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...,154
179,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...,148
374,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...,148
404,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...,139
30,2026-08-19-21-51-21 +0000,latimes,"Trump-backed candidates struggle, and other ta...",https://www.latimes.com/politics/story/2026-08...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
402,154,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...
400,83,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...
77,66,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
387,62,2026-08-19-02-04-32 +0000,nyt,Cory Mills Loses Republican Primary Amid Assau...,https://www.nytimes.com/2026/08/18/us/politics...
347,61,2026-08-19-08-10-01 +0000,wsj,Stock Market Today: Bond Yields Dive After Bes...,https://www.wsj.com/livecoverage/stock-market-...
222,60,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
272,51,2026-08-19-12-37-06 +0000,cbc,Israel opens criminal probes over killings of ...,https://www.cbc.ca/news/world/israel-criminal-...
30,45,2026-08-19-21-51-21 +0000,latimes,"Trump-backed candidates struggle, and other ta...",https://www.latimes.com/politics/story/2026-08...
186,45,2026-08-19-17-07-33 +0000,nypost,Five Americans killed in fiery Kenya helicopte...,https://nypost.com/2026/08/19/world-news/ameri...
146,45,2026-08-19-18-33-36 +0000,nypost,Data center backlash poised to play critical r...,https://nypost.com/2026/08/19/business/data-ce...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)