## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-02-43-41 +0000,nyt,Platner Wins Maine Senate Primary After a Turb...,https://www.nytimes.com/2026/06/09/us/politics...
1,2026-06-10-02-42-42 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes o...,https://www.nytimes.com/live/2026/06/09/world/...
2,2026-06-10-02-42-40 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/09/world/...
3,2026-06-10-02-41-00 +0000,wsj,Sigma Healthcare in Preliminary Talks to Buy U...,https://www.wsj.com/business/sigma-healthcare-...
4,2026-06-10-02-39-07 +0000,nyt,Lawyers Barred for A.I.-Generated Citations to...,https://www.nytimes.com/2026/06/09/us/ai-lawye...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
64        trump     32
8          iran     27
128  california     19
256       world     18
2         maine     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
17,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,114
335,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,113
91,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,111
217,2026-06-09-17-01-09 +0000,nypost,Trump claims Iran shooting down US helicopter ...,https://nypost.com/2026/06/09/us-news/iran-sho...,95
1,2026-06-10-02-42-42 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes o...,https://www.nytimes.com/live/2026/06/09/world/...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
17,114,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
335,113,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...
91,79,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
11,69,2026-06-10-02-09-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
22,68,2026-06-10-01-38-00 +0000,wsj,Democrats in Maine set aside the controversies...,https://www.wsj.com/politics/elections/maine-p...
46,58,2026-06-10-00-30-20 +0000,nypost,Shocking number of World Cup tickets still ava...,https://nypost.com/2026/06/09/us-news/world-cu...
316,40,2026-06-09-10-00-00 +0000,latimes,This new law could create a million new apartm...,https://www.latimes.com/business/story/2026-06...
204,40,2026-06-09-17-47-41 +0000,bbc,Israeli air strikes hit Lebanese city of Tyre ...,https://www.bbc.com/news/articles/c36y16nkr5no...
7,37,2026-06-10-02-29-57 +0000,nypost,Baby-faced killer Karmelo Anthony seen in firs...,https://nypost.com/2026/06/09/us-news/baby-fac...
340,35,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)