## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-14-05-28-40 +0000,nyt,Israel-Iran Conflict: U.S. Military Attacks Ir...,https://www.nytimes.com/live/2026/03/13/world/...
1,2026-03-14-05-26-50 +0000,startribune,Final results from state semifinals: Providenc...,https://www.startribune.com/mn-girls-basketbal...
2,2026-03-14-05-22-57 +0000,nyt,What to Know About Iran’s Kharg Island,https://www.nytimes.com/2026/03/14/world/middl...
3,2026-03-14-05-08-55 +0000,nyt,Here is the latest.,https://www.nytimes.com/live/2026/03/14/world/...
4,2026-03-14-05-06-30 +0000,nypost,Rep. Jasmine Crockett’s fugitive security guar...,https://nypost.com/2026/03/14/us-news/texas-re...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
1     iran     54
8    trump     47
256    war     41
5      oil     30
114    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-14-05-28-40 +0000,nyt,Israel-Iran Conflict: U.S. Military Attacks Ir...,https://www.nytimes.com/live/2026/03/13/world/...,211
42,2026-03-14-00-57-55 +0000,latimes,Trump administration orders restart of oil dri...,https://www.latimes.com/california/story/2026-...,200
41,2026-03-14-01-00-00 +0000,wsj,Trump Knew the Risk of Iran Blocking the Strai...,https://www.wsj.com/politics/national-security...,164
218,2026-03-13-17-09-48 +0000,nypost,Trump says US seizing Kharg Island ‘not high o...,https://nypost.com/2026/03/13/us-news/trump-sa...,163
27,2026-03-14-01-53-54 +0000,wapo,"Trump says U.S. bombed Kharg Island, striking ...",https://www.washingtonpost.com/politics/2026/0...,160

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,211,2026-03-14-05-28-40 +0000,nyt,Israel-Iran Conflict: U.S. Military Attacks Ir...,https://www.nytimes.com/live/2026/03/13/world/...
353,88,2026-03-13-08-45-00 +0000,wsj,German Chemical Industry Warns of Supply-Chain...,https://www.wsj.com/world/europe/german-chemic...
282,63,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
214,51,2026-03-13-17-16-00 +0000,bbc,"New US trade probe targets EU, Canada, UK over...",https://www.bbc.com/news/articles/cgrzvdqze5xo...
165,49,2026-03-13-19-50-01 +0000,nypost,"Pentagon sending assault ship, at least 2,500 ...",https://nypost.com/2026/03/13/us-news/pentagon...
100,48,2026-03-13-22-15-23 +0000,nypost,Charges dropped against five students involved...,https://nypost.com/2026/03/13/us-news/charges-...
115,43,2026-03-13-21-39-00 +0000,wsj,"In a major victory for the Fed, a judge threw ...",https://www.wsj.com/economy/central-banking/ju...
342,39,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
237,38,2026-03-13-16-06-47 +0000,nypost,"Stocks fall, oil holds above $100 after tempor...",https://nypost.com/2026/03/13/business/stocks-...
315,38,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)