## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-22-52-57 +0000,nypost,UChicago frat bro’s campus social life went on...,https://nypost.com/2026/10/29/us-news/uchicago...
1,2026-10-29-22-51-50 +0000,nypost,SoCal woman develops scary symptoms months aft...,https://nypost.com/2026/10/29/us-news/landfill...
2,2026-10-29-22-49-00 +0000,nyt,Cuba’s Foreign Minister: We’ll Outlast Trump,https://www.nytimes.com/2026/10/29/world/ameri...
3,2026-10-29-22-46-45 +0000,nyt,California’s High-Speed Rail Chief Quits Amid ...,https://www.nytimes.com/2026/10/29/us/choudri-...
4,2026-10-29-22-33-00 +0000,wsj,Intel Shares Plunge More Than 20% on Weak PC-M...,https://www.wsj.com/business/earnings/intel-sh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2418/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
28        trump     33
150         new     26
134    election     22
29   california     19
114          up     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
87,2026-10-29-20-41-45 +0000,nypost,California’s Prop. 3 tax on top earners holds ...,https://nypost.com/2026/10/29/us-news/californ...,115
279,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,94
353,2026-10-29-10-00-00 +0000,latimes,A new president takes charge at Caltech as unc...,https://www.latimes.com/california/story/2026-...,93
416,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...,90
112,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
87,115,2026-10-29-20-41-45 +0000,nypost,California’s Prop. 3 tax on top earners holds ...,https://nypost.com/2026/10/29/us-news/californ...
416,90,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...
376,70,2026-10-29-09-01-00 +0000,wsj,Most Americans—including many Iranian American...,https://www.wsj.com/politics/elections/i-went-...
207,63,2026-10-29-16-26-00 +0000,wsj,U.S. economic growth picked up steam in the th...,https://www.wsj.com/economy/us-gdp-report-q3-2...
322,61,2026-10-29-11-09-09 +0000,chitri,Prime Minister Benjamin Netanyahu’s party ampl...,https://www.chicagotribune.com/2026/10/29/isra...
329,56,2026-10-29-10-57-14 +0000,nypost,Alaska governor orders probe of Mary Peltola S...,https://nypost.com/2026/10/29/us-news/alaska-g...
210,56,2026-10-29-16-13-06 +0000,nypost,Conservative groups warn letting AI giants ‘re...,https://nypost.com/2026/10/29/business/conserv...
325,50,2026-10-29-11-07-35 +0000,bbc,Audio reveals exchanges between Spain train op...,https://www.bbc.co.uk/news/articles/cmqxnl312v...
285,44,2026-10-29-13-18-29 +0000,nypost,Feds found evidence Ilhan Omar was in sham mar...,https://nypost.com/2026/10/29/us-news/feds-fou...
403,43,2026-10-29-04-44-00 +0000,wsj,"In a comeback attempt, Democrat Keisha Lance B...",https://www.wsj.com/politics/elections/the-ex-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)