## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-19-10-55 +0000,bbc,PM warns against 'false comfort' of thinking I...,https://www.bbc.com/news/articles/cy01l49kkgdo...
1,2026-03-23-19-06-33 +0000,nypost,Jewish man allegedly targeted with Nazi salute...,https://nypost.com/2026/03/23/world-news/jewis...
2,2026-03-23-19-05-00 +0000,wsj,"Treasury Yields, Dollar on Path for Daily Decline",https://www.wsj.com/finance/bonds-decoupling-f...
3,2026-03-23-19-04-15 +0000,bbc,Colombian Air Force plane crashes with 125 peo...,https://www.bbc.com/news/articles/c8dlmrjn1l2o...
4,2026-03-23-19-04-00 +0000,wsj,LaGuardia Airport Reopens Hours After Deadly R...,https://www.wsj.com/us-news/faa-issues-ground-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2485/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
39   trump     43
6     iran     39
7      war     20
212    new     15
497    oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-03-23-19-00-51 +0000,nyt,Iran War Live Updates: Iran Disputes Trump’s A...,https://www.nytimes.com/live/2026/03/23/world/...,156
190,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,133
172,2026-03-23-13-16-13 +0000,nypost,"Dow rallies 745 points, oil tumbles below $100...",https://nypost.com/2026/03/23/business/dow-fut...,128
156,2026-03-23-14-08-41 +0000,nypost,Trump says ‘we don’t know’ if Iran’s new Supre...,https://nypost.com/2026/03/23/us-news/trump-sa...,122
231,2026-03-23-08-18-20 +0000,wsj,"Stock Market Today: Dow Gains, Oil Skids After...",https://www.wsj.com/livecoverage/stock-market-...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,156,2026-03-23-19-00-51 +0000,nyt,Iran War Live Updates: Iran Disputes Trump’s A...,https://www.nytimes.com/live/2026/03/23/world/...
92,78,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
250,68,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
151,57,2026-03-23-14-26-20 +0000,nypost,Air Canada flight attendant on LaGuardia plane...,https://nypost.com/2026/03/23/us-news/air-cana...
190,48,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...
262,41,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...
41,37,2026-03-23-17-54-49 +0000,nypost,TSA crisis hits Long Beach Airport as staggeri...,https://nypost.com/2026/03/23/us-news/1-in-5-t...
248,34,2026-03-23-03-34-34 +0000,nyt,Israel’s Missile Defense Under Scrutiny After ...,https://www.nytimes.com/2026/03/22/world/middl...
66,33,2026-03-23-17-12-46 +0000,nypost,OnlyFans star Sophie Rain mourns Leo Radvinsky...,https://nypost.com/2026/03/23/business/onlyfan...
24,31,2026-03-23-18-20-21 +0000,cbc,Colombian military cargo plane crashes near Pe...,https://www.cbc.ca/news/world/colombia-militar...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)