## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-12-00-00 +0000,missionlocal,"One year in, plans to expand Bayview shelter f...",https://missionlocal.org/2026/06/jerrold-commo...
1,2026-06-18-11-58-40 +0000,nypost,All the viewing areas for Knicks ticker-tape p...,https://nypost.com/2026/06/18/us-news/all-the-...
2,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...
3,2026-06-18-11-54-23 +0000,bbc,British man dies in paragliding accident in Spain,https://www.bbc.com/news/articles/c1dye3e9gnwo...
4,2026-06-18-11-54-12 +0000,nyt,Ukraine Strikes Moscow Refinery in Large-Scale...,https://www.nytimes.com/2026/06/18/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
34    iran     51
32   trump     51
35    deal     41
132    new     25
329    fed     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,228
334,2026-06-17-16-31-02 +0000,nypost,Trump says Iran laughed at ‘stupid son of a bi...,https://nypost.com/2026/06/17/us-news/trump-sa...,207
2,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...,198
154,2026-06-18-01-48-17 +0000,nyt,Trump’s Deal With Iran Opens New Rifts in G.O.P.,https://www.nytimes.com/2026/06/17/us/politics...,171
309,2026-06-17-17-44-50 +0000,nypost,Trump jokingly reveals whom he’ll blame if Ira...,https://nypost.com/2026/06/17/us-news/trump-jo...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,228,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
245,135,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
22,86,2026-06-18-11-06-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
37,58,2026-06-18-10-49-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
44,49,2026-06-18-10-25-11 +0000,cbc,"Ukraine hits Moscow oil refinery again, part o...",https://www.cbc.ca/news/world/drone-attack-mos...
172,43,2026-06-17-23-54-00 +0000,wsj,President Trump said he is delaying the nomina...,https://www.wsj.com/politics/policy/trump-dela...
98,42,2026-06-18-08-14-38 +0000,wsj,"Stock Market Today: Stocks Set for Rebound, Ga...",https://www.wsj.com/livecoverage/stock-market-...
319,41,2026-06-17-17-16-11 +0000,nypost,Bungee-jump employee took GoPro camera off stu...,https://nypost.com/2026/06/17/world-news/bunge...
268,41,2026-06-17-19-43-10 +0000,bbc,The designer behind DR Congo's World Cup suit:...,https://www.bbc.com/news/videos/crkvxp731e2o?a...
68,37,2026-06-18-09-35-01 +0000,startribune,"US and Iran sign initial deal to end war, ease...",https://www.startribune.com/iran-will-reopen-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)