## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-13-11-27-01 +0000,nypost,Sharks circling around Samuels after disastrou...,https://nypost.com/2026/06/13/us-news/sharks-c...
1,2026-06-13-11-22-07 +0000,nypost,NYC shells out $6M in taxpayer dollars for shr...,https://nypost.com/2026/06/13/us-news/nyc-shel...
2,2026-06-13-11-18-21 +0000,nyt,Iran War Live Updates: Middle East Awaits Late...,https://www.nytimes.com/live/2026/06/13/world/...
3,2026-06-13-11-15-18 +0000,bbc,"Israel carries out air strikes on Lebanon, sta...",https://www.bbc.com/news/articles/c39y02x98k8o...
4,2026-06-13-11-05-13 +0000,nyt,Wages Are Falling. Wealth Is Surging. No Wonde...,https://www.nytimes.com/2026/06/13/business/ec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
145   world     31
574  spacex     27
93    trump     24
178     cup     20
21     iran     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
249,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...,129
116,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...,125
153,2026-06-12-20-38-48 +0000,nyt,Elon Musk Becomes World’s First Trillionaire a...,https://www.nytimes.com/2026/06/12/technology/...,117
65,2026-06-13-02-15-27 +0000,nypost,Trump expected to attend World Cup final in Ne...,https://nypost.com/2026/06/12/us-news/trump-ex...,93
142,2026-06-12-20-56-54 +0000,nypost,Elon Musk just became world’s first trillionai...,https://nypost.com/2026/06/12/us-news/with-elo...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
249,129,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...
165,82,2026-06-12-20-14-32 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...
282,50,2026-06-12-14-16-19 +0000,nypost,California Democrats slammed for bizarre World...,https://nypost.com/2026/06/12/us-news/californ...
173,45,2026-06-12-19-57-16 +0000,bbc,UK vows to phase out Russian diesel and jet fu...,https://www.bbc.com/news/articles/ceqdl8xre7qo...
197,44,2026-06-12-18-33-52 +0000,nypost,Spencer Pratt drops bombshell clip with claims...,https://nypost.com/2026/06/12/us-news/spencer-...
84,37,2026-06-13-00-57-17 +0000,nypost,Crazed homeless Penn Station slasher stabbed o...,https://nypost.com/2026/06/12/us-news/crazed-p...
46,35,2026-06-13-06-02-29 +0000,nypost,Shipping heiress killed on family’s luxury wil...,https://nypost.com/2026/06/13/world-news/germa...
80,34,2026-06-13-01-06-34 +0000,nyt,Judge Dismisses Republican Group’s Case Agains...,https://www.nytimes.com/2026/06/12/us/politics...
258,33,2026-06-12-15-09-44 +0000,nyt,Drones Flown Over North Korea Were Part of Mar...,https://www.nytimes.com/2026/06/11/world/asia/...
81,31,2026-06-13-01-00-00 +0000,wsj,Trump at 80: He and advisers have decided to m...,https://www.wsj.com/politics/elections/trump-b...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)