## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-13-10-57 +0000,bbc,US and Iran trade fire after two US soldiers k...,https://www.bbc.co.uk/news/articles/cgk417jp83...
1,2026-07-19-13-06-21 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...
2,2026-07-19-13-00-47 +0000,nyt,Misery in the Epicenter of Cyclospora: ‘A Base...,https://www.nytimes.com/2026/07/19/us/cyclospo...
3,2026-07-19-13-00-00 +0000,missionlocal,Sunset supper,https://missionlocal.org/2026/07/sunset-supper/
4,2026-07-19-12-57-10 +0000,nyt,Politicians Are Trying to Change What Chatbots...,https://www.nytimes.com/2026/07/19/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     18
44   world     16
238  trump     14
45     cup     14
248    new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-07-19-13-06-21 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...,79
121,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...,73
120,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,69
75,2026-07-19-04-53-22 +0000,nypost,Spanish legend Joan Capdevila will be allowed ...,https://nypost.com/2026/07/19/us-news/spanish-...,68
119,2026-07-18-22-57-00 +0000,wapo,U.S. strikes Iran after 2 service members kill...,https://www.washingtonpost.com/world/2026/07/1...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,79,2026-07-19-13-06-21 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...
138,56,2026-07-18-18-43-24 +0000,cbc,Hazy skies from wildfire smoke unlikely to can...,https://www.cbc.ca/news/world/air-quality-worl...
53,46,2026-07-19-09-12-35 +0000,nypost,"US blitzes Iranian missile depots, air defense...",https://nypost.com/2026/07/19/world-news/us-bl...
121,37,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
92,34,2026-07-19-01-33-02 +0000,nypost,NYC homeless man hurls cell phone at baby in s...,https://nypost.com/2026/07/18/us-news/bryant-p...
110,28,2026-07-19-00-00-00 +0000,wsj,He Ran a Strip Club. Now He Wants to Build Cal...,https://www.wsj.com/us-news/he-ran-a-strip-clu...
135,24,2026-07-18-19-04-16 +0000,nypost,World’s most livable city tops global list sec...,https://nypost.com/2026/07/18/world-news/world...
157,23,2026-07-18-15-54-28 +0000,nypost,Hochul backed NY data-center ban to satisfy DS...,https://nypost.com/2026/07/18/us-news/hochul-b...
73,23,2026-07-19-05-43-19 +0000,nypost,US ambassador to UN slaps down Zohran Mamdani’...,https://nypost.com/2026/07/19/us-news/us-ambas...
170,20,2026-07-18-14-32-48 +0000,bbc,Ruthless plotter? Flip-flopper? Dad dancer? In...,https://www.bbc.co.uk/news/articles/c3043vl2l7...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)