## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-20-58-09 +0000,nypost,Biden FBI tracked Melania and Barron Trump’s t...,https://nypost.com/2026/10/05/us-news/biden-fb...
1,2026-10-05-20-54-31 +0000,nyt,Nigeria Military Helicopter Crashes With 32 On...,https://www.nytimes.com/2026/10/05/world/afric...
2,2026-10-05-20-50-35 +0000,nypost,"The ‘Cornell 7’ members expelled, suspended, b...",https://nypost.com/2026/10/05/us-news/the-corn...
3,2026-10-05-20-49-15 +0000,nyt,Nashville Symphony Receives $10 Million Lifeli...,https://www.nytimes.com/2026/10/05/arts/music/...
4,2026-10-05-20-48-00 +0000,wsj,Opinion | The Fraud of White Guilt,https://www.wsj.com/opinion/the-fraud-of-white...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2363/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
438       new     25
59   election     21
150     house     19
5       trump     19
99      court     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
77,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,96
109,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,88
262,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,84
273,2026-10-05-10-21-41 +0000,nyt,Will Midterm Elections Complicate the Supreme ...,https://www.nytimes.com/video/us/1000000111847...,80
255,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
77,96,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...
109,88,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
342,71,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...
209,66,2026-10-05-14-24-08 +0000,wapo,Former White House press secretary Karoline Le...,https://www.washingtonpost.com/business/2026/1...
44,57,2026-10-05-19-55-56 +0000,nypost,Trump calls reported pneumatic plague outbreak...,https://nypost.com/2026/10/05/us-news/trump-ca...
116,49,2026-10-05-17-36-21 +0000,nypost,Gulf oil exports top pre-war levels as Saudi-b...,https://nypost.com/2026/10/05/world-news/gulf-...
34,45,2026-10-05-20-07-39 +0000,nypost,Carl Heastie parties in Rio with high-profile ...,https://nypost.com/2026/10/05/us-news/ny-speak...
42,43,2026-10-05-20-00-00 +0000,wsj,The U.S. moved a dozen B-1 bomber aircraft fro...,https://www.wsj.com/politics/national-security...
10,39,2026-10-05-20-41-47 +0000,nypost,‘American Idol’ alum Caleb Flynn sobs as he ma...,https://nypost.com/2026/10/05/us-news/american...
45,39,2026-10-05-19-55-43 +0000,nypost,"Woman, 35, found dead with bruises all over he...",https://nypost.com/2026/10/05/us-news/woman-35...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)