## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-21-04-56-35 +0000,bbc,Baby bank helping more parents in full-time work,https://www.bbc.co.uk/news/articles/ckge4848pz...
1,2026-09-21-04-43-56 +0000,nypost,Tourists stranded on isolated Oregon beach aft...,https://nypost.com/2026/09/21/us-news/tourists...
2,2026-09-21-04-23-10 +0000,nypost,First female Archbishop of Canterbury revokes ...,https://nypost.com/2026/09/21/world-news/archb...
3,2026-09-21-04-21-36 +0000,nyt,Spain’s Preppy Conservatives Are Having a Moment,https://www.nytimes.com/2026/09/18/world/europ...
4,2026-09-21-04-20-14 +0000,nyt,Why Israel Wants More One-Ton Bombs From the U.S.,https://www.nytimes.com/2026/09/16/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2395/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
140     trump     25
74        new     16
680    drones     11
100  election      9
423      will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
101,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,104
160,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...,87
115,2026-09-20-18-29-32 +0000,chitri,President Donald Trump suggests his arch will ...,https://www.chicagotribune.com/2026/09/20/trum...,75
140,2026-09-20-16-36-43 +0000,bbc,Trump says triumphal arch will be military com...,https://www.bbc.co.uk/news/articles/cqdj4pez00...,71
97,2026-09-20-20-14-28 +0000,wapo,Trump says planned 250-foot arch will be ‘mili...,https://www.washingtonpost.com/politics/2026/0...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
101,104,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
16,51,2026-09-21-02-46-37 +0000,nypost,Patrick Clancy said ex-wife Lindsay never aske...,https://nypost.com/2026/09/20/us-news/patrick-...
160,45,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...
36,41,2026-09-21-00-45-57 +0000,nypost,Nithya Raman reveals how she’ll co-govern with...,https://nypost.com/2026/09/20/us-news/nithya-r...
12,37,2026-09-21-03-22-44 +0000,bbc,German Chancellor Merz calls state election a ...,https://www.bbc.co.uk/news/articles/cvwyz29n0n...
144,37,2026-09-20-15-59-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
135,35,2026-09-20-17-25-10 +0000,chitri,Moscow refinery hit as Russia reports largest ...,https://www.chicagotribune.com/2026/09/20/mosc...
26,31,2026-09-21-01-35-28 +0000,nypost,California gubernatorial candidate Steve Hilto...,https://nypost.com/2026/09/20/us-news/californ...
34,29,2026-09-21-01-00-00 +0000,wsj,Republicans are pumping money into Senate and ...,https://www.wsj.com/politics/elections/republi...
158,29,2026-09-20-14-30-07 +0000,nypost,Trump warns he’s close to Iran decision as Mid...,https://nypost.com/2026/09/20/us-news/trump-re...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)