## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-14-35-51 +0000,bbc,Burnham pledges to end rough sleeping in first...,https://www.bbc.co.uk/news/articles/c0jl839j6z...
1,2026-07-20-14-32-04 +0000,48hills,"Trans community, allies condemn Wiener for exp...",https://48hills.org/2026/07/trans-community-al...
2,2026-07-20-14-32-00 +0000,wsj,U.S. Leading Indicators Ticked Down in June,https://www.wsj.com/economy/central-banking/u-...
3,2026-07-20-14-29-10 +0000,nypost,Yemen’s Houthis declare naval blockade on Saud...,https://nypost.com/2026/07/20/world-news/yemen...
4,2026-07-20-14-27-51 +0000,nyt,Did This World Cup Change Soccer Forever?,https://www.nytimes.com/2026/07/19/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
37     world     27
57      iran     27
38       cup     25
112      new     20
0    burnham     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
241,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,109
239,2026-07-19-19-25-24 +0000,chitri,Donald Trump celebrates the World Cup as a US ...,https://www.chicagotribune.com/2026/07/19/trum...,104
214,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,96
220,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...,92
195,2026-07-20-00-44-03 +0000,bbc,"Trump, Bieber and Shakira - a World Cup final ...",https://www.bbc.co.uk/sport/football/articles/...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
241,109,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...
192,76,2026-07-20-01-00-00 +0000,wsj,Jordan Becomes New Flashpoint in U.S.-Iran War...,https://www.wsj.com/world/middle-east/jordan-b...
207,63,2026-07-19-23-25-00 +0000,wsj,"Usha Vance gave birth to a baby boy on Sunday,...",https://www.wsj.com/us-news/second-lady-usha-v...
171,56,2026-07-20-04-01-05 +0000,nyt,Five of the Main Challenges Awaiting Andy Burn...,https://www.nytimes.com/2026/07/20/world/europ...
247,48,2026-07-19-18-35-33 +0000,nypost,Chilling video shows Monaco bomb attack that n...,https://nypost.com/2026/07/19/world-news/video...
150,46,2026-07-20-09-00-00 +0000,wsj,Many wealthy Texas Republicans can’t stomach t...,https://www.wsj.com/politics/elections/ken-pax...
170,46,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
220,36,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
103,28,2026-07-20-11-00-00 +0000,startribune,Police searched Twin Cities license plate came...,https://www.startribune.com/police-search-immi...
36,28,2026-07-20-13-30-48 +0000,nypost,Texas Dem House hopeful creeped on women in Sp...,https://nypost.com/2026/07/20/us-news/texas-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)