## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-11-00-00 +0000,wsj,Brands Are ‘Maxxing’ and ‘Mogging’ as They Co-...,https://www.wsj.com/cmo-today/brands-are-maxxi...
1,2026-08-21-11-00-00 +0000,nypost,"Mamdani, the DSA and the Teamsters are lining ...",https://nypost.com/2026/08/21/business/mamdani...
2,2026-08-21-10-53-53 +0000,nyt,"Iran Must Plan to Overcome ‘Unjust Sanctions,’...",https://www.nytimes.com/2026/08/21/world/middl...
3,2026-08-21-10-52-00 +0000,wsj,The Morning Risk Report: Rainmakers in Talks t...,https://www.wsj.com/risk-compliance-journal/th...
4,2026-08-21-10-48-01 +0000,bbc,'We are devastated' - Nigerian villagers bury ...,https://www.bbc.co.uk/news/articles/cj035jg256...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2626/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
413       trump     31
117         new     19
11           up     18
133       harry     17
181  california     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
162,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...,105
392,2026-08-20-11-58-09 +0000,cbc,North Korea fires up to 10 ballistic missiles ...,https://www.cbc.ca/news/world/north-korea-miss...,74
115,2026-08-21-02-58-51 +0000,nyt,The Message Behind Trump’s Threats of ‘Economi...,https://www.nytimes.com/2026/08/20/world/europ...,73
233,2026-08-20-20-41-36 +0000,nyt,As Prince Harry and Meghan Depart California f...,https://www.nytimes.com/2026/08/20/us/prince-h...,73
374,2026-08-20-13-19-24 +0000,chitri,A timeline of Prince Harry and Meghan’s relati...,https://www.chicagotribune.com/2026/08/20/prin...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
162,105,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...
233,73,2026-08-20-20-41-36 +0000,nyt,As Prince Harry and Meghan Depart California f...,https://www.nytimes.com/2026/08/20/us/prince-h...
112,62,2026-08-21-03-29-11 +0000,nypost,ISIS-linked New Yorker caught plotting to blow...,https://nypost.com/2026/08/20/us-news/isis-lin...
327,53,2026-08-20-16-12-52 +0000,nypost,Bessent tells US allies ‘you’re either with us...,https://nypost.com/2026/08/20/us-news/bessent-...
37,47,2026-08-21-09-35-54 +0000,cbc,Charter plane crash kills 8 near remote radar ...,https://www.cbc.ca/news/world/alaska-plane-cra...
347,42,2026-08-20-15-07-29 +0000,nypost,Walmart shares sink 9% — slowest sales growth ...,https://nypost.com/2026/08/20/business/walmart...
274,41,2026-08-20-18-57-37 +0000,startribune,North Loop residents blast developer’s data ce...,https://www.startribune.com/north-loop-residen...
248,40,2026-08-20-20-04-52 +0000,nyt,Bond Market Stress Returns and Oil Rises in Ed...,https://www.nytimes.com/2026/08/20/business/ir...
335,40,2026-08-20-15-46-14 +0000,nypost,Coffee shop owner who’s gotten ‘nonstop death ...,https://nypost.com/2026/08/20/business/idaho-c...
107,40,2026-08-21-04-13-02 +0000,nypost,Long Island sicko undressed pair of young girl...,https://nypost.com/2026/08/21/us-news/long-isl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)