## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-15-14-55-21 +0000,bbc,Nandy 'minded to intervene' in Sky's £1.6bn ta...,https://www.bbc.co.uk/news/articles/cm79pe5yej...
1,2026-10-15-14-54-16 +0000,nyt,Migrant Children Without Lawyers Face Fast-Tra...,https://www.nytimes.com/2026/10/15/us/lawyers-...
2,2026-10-15-14-52-18 +0000,bbc,Trump calls off livestream for Fort Hood shoot...,https://www.bbc.co.uk/news/articles/crx23qlnj2...
3,2026-10-15-14-51-30 +0000,bbc,Seven crew missing after drone attack leaves t...,https://www.bbc.co.uk/news/articles/c60qkgpp59...
4,2026-10-15-14-51-18 +0000,nyt,"OpenAI Engineer, Who Is Charged With Planting ...",https://www.nytimes.com/2026/10/14/technology/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2393/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
18        trump     31
73          new     24
171     ukraine     17
388   inflation     15
322  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...,113
25,2026-10-15-14-25-16 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/15/us-news/new-whit...,104
407,2026-10-14-15-25-31 +0000,nyt,Democrats Blame Trump After CPI Report Shows E...,https://www.nytimes.com/2026/10/14/business/ec...,100
8,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...,96
38,2026-10-15-14-05-12 +0000,nyt,Katie Zacharia Is Trump’s New Press Secretary....,https://www.nytimes.com/2026/10/14/us/politics...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,113,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...
25,104,2026-10-15-14-25-16 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/15/us-news/new-whit...
207,81,2026-10-15-03-25-00 +0000,wsj,Texas Democrat and Senate hopeful James Talari...,https://www.wsj.com/politics/elections/five-ta...
8,72,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...
42,63,2026-10-15-14-00-00 +0000,nypost,Dire warning in California city as mass layoff...,https://nypost.com/2026/10/15/us-news/holliste...
228,60,2026-10-15-00-28-58 +0000,nyt,"Inflation Data Shows Prices Are Up, Worrying R...",https://www.nytimes.com/2026/10/14/us/politics...
122,54,2026-10-15-10-58-00 +0000,wsj,A WSJ poll finds resistance among Democrats to...,https://www.wsj.com/politics/how-liberal-is-th...
253,52,2026-10-14-22-39-46 +0000,chitri,Chicago prays for native son Pope Leo XIV as h...,https://www.chicagotribune.com/2026/10/14/chic...
21,50,2026-10-15-14-28-11 +0000,chitri,President Donald Trump says Pentagon won’t liv...,https://www.chicagotribune.com/2026/10/15/dona...
341,43,2026-10-14-18-39-00 +0000,wsj,"For years, China flooded Europe with exports t...",https://www.wsj.com/economy/trade/with-china-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)