## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-20-17-52-27 +0000,nypost,‘Strange sound’ leads homeowner to unearth mas...,https://nypost.com/2026/09/20/world-news/homeo...
1,2026-09-20-17-48-26 +0000,cbc,Germany's Merz vows to press on with reforms d...,https://www.cbc.ca/news/world/friedrich-merz-g...
2,2026-09-20-17-48-01 +0000,startribune,Live: Vikings and Bears battling themselves an...,https://www.startribune.com/minnesota-vikings-...
3,2026-09-20-17-46-57 +0000,bbc,German Chancellor Merz calls state election a ...,https://www.bbc.co.uk/news/articles/cvwyz29n0n...
4,2026-09-20-17-43-00 +0000,wsj,Opinion | What Is Saudi Arabia’s Plan for the ...,https://www.wsj.com/opinion/what-is-saudi-arab...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2341/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
174   trump     32
10      new     15
98       ai     10
115  attack     10
217  drones     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...,89
58,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...,85
33,2026-09-20-16-15-40 +0000,nypost,Obama glosses over his own attempt to block me...,https://nypost.com/2026/09/20/us-news/obama-gl...,77
30,2026-09-20-16-36-43 +0000,bbc,Trump says triumphal arch will be military com...,https://www.bbc.co.uk/news/articles/cqdj4pez00...,73
66,2026-09-20-13-57-21 +0000,nypost,Trump says his Triumphal Arch in Washington wi...,https://nypost.com/2026/09/20/us-news/trump-sa...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,89,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...
16,50,2026-09-20-17-27-07 +0000,nypost,Ukraine deploys new 6-ton missile to hit Mosco...,https://nypost.com/2026/09/20/world-news/ukrai...
173,46,2026-09-19-21-34-24 +0000,cbc,Saudi Arabia confirms Yemen's Houthi rebels tr...,https://www.cbc.ca/news/world/houthi-rebels-sa...
35,43,2026-09-20-16-09-01 +0000,nypost,GOP’s Bruce Blakeman admits it’s ‘surreal’ his...,https://nypost.com/2026/09/20/us-news/bruce-bl...
193,38,2026-09-19-19-13-51 +0000,wapo,"Trump to form ‘AI Force,’ name AI czar but rej...",https://www.washingtonpost.com/politics/2026/0...
133,35,2026-09-20-05-01-47 +0000,bbc,Watch: Fans react as Ed Sheeran speaks out ove...,https://www.bbc.co.uk/news/videos/ck980m0pr1e0...
34,32,2026-09-20-16-13-15 +0000,nypost,NYC teen seen in eerie Citi Bike photo year be...,https://nypost.com/2026/09/20/us-news/nyc-teen...
58,31,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...
40,29,2026-09-20-15-41-23 +0000,nypost,German leader’s party gets worst election resu...,https://nypost.com/2026/09/20/world-news/germa...
38,26,2026-09-20-15-59-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)