## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-04-46-45 +0000,nypost,‘SNL’ roasts Mayor Zohran Mamdani with ‘urgent...,https://nypost.com/2026/09/27/us-news/snl-roas...
1,2026-09-27-04-45-08 +0000,bbc,Bangkok roads submerged as flood disaster decl...,https://www.bbc.co.uk/news/articles/ck1wxx8n2x...
2,2026-09-27-04-33-52 +0000,startribune,Live: Gophers take halftime lead over Washingt...,https://www.startribune.com/minnesota-gophers-...
3,2026-09-27-04-23-09 +0000,bbc,Nor'easter brings flooding as New York and New...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
4,2026-09-27-04-11-46 +0000,nypost,Paranoid owner of woke Mass. lesbian bar puts ...,https://nypost.com/2026/09/27/us-news/mask-fre...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
85        trump     32
7           new     12
106  california      9
98        house      8
37         mass      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...,80
25,2026-09-27-00-52-12 +0000,nypost,Trump’s new superintelligence czar: Here’s who...,https://nypost.com/2026/09/26/us-news/trumps-n...,77
175,2026-09-26-07-03-34 +0000,nypost,Ukraine’s Zelensky says he urged Trump to enli...,https://nypost.com/2026/09/26/world-news/ukrai...,70
121,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...,66
94,2026-09-26-16-01-28 +0000,chitri,President Trump rejects Iran’s proposal to reo...,https://www.chicagotribune.com/2026/09/26/trum...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,80,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
3,46,2026-09-27-04-23-09 +0000,bbc,Nor'easter brings flooding as New York and New...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
116,43,2026-09-26-14-24-32 +0000,nypost,Russian attacks kill 4 across Ukraine days aft...,https://nypost.com/2026/09/26/world-news/russi...
120,38,2026-09-26-14-05-01 +0000,cbc,Hundreds of thousands turn out for Pope Leo al...,https://www.cbc.ca/news/world/pope-leo-parade-...
64,36,2026-09-26-20-09-51 +0000,cbc,"China, U.S. agree to AI dialogue, tariff cuts ...",https://www.cbc.ca/news/world/china-united-sta...
121,34,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...
62,34,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
99,28,2026-09-26-15-45-00 +0000,wsj,"How Jordan Campbell, a Texas business litigato...",https://www.wsj.com/politics/policy/how-a-busi...
123,27,2026-09-26-14-00-00 +0000,latimes,A baby was found by a dumpster in the rain mor...,https://www.latimes.com/california/story/2026-...
37,25,2026-09-26-22-49-39 +0000,nypost,Husband of missing California coffee shop owne...,https://nypost.com/2026/09/26/us-news/new-clue...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)