## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-20-17-57 +0000,nypost,Liberal meltdown over ‘racist’ AI ad showing C...,https://nypost.com/2026/05/25/us-news/liberal-...
1,2026-05-25-20-16-02 +0000,nypost,Furious LA firefighters take rarely seen step ...,https://nypost.com/2026/05/25/us-news/los-ange...
2,2026-05-25-20-10-06 +0000,nyt,"Ferrari Unveils Luce, Its First Fully Electric...",https://www.nytimes.com/2026/05/25/business/fe...
3,2026-05-25-20-10-00 +0000,wsj,"Ferrari Launches $640,000, Jony Ive-Designed, ...",https://www.wsj.com/business/autos/ferrari-lau...
4,2026-05-25-20-06-50 +0000,nyt,Threat of Explosion From Toxic Chemical Tank L...,https://www.nytimes.com/2026/05/25/us/chemical...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
46    iran     28
96   trump     20
47    deal     18
111    new     10
3       ai      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
147,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...,100
21,2026-05-25-19-07-57 +0000,wapo,"As new Iran deal faces sharp criticism, Trump ...",https://www.washingtonpost.com/world/2026/05/2...,87
103,2026-05-25-13-51-50 +0000,nypost,Trump demands six Muslim countries join Abraha...,https://nypost.com/2026/05/25/us-news/presiden...,87
44,2026-05-25-17-57-08 +0000,nyt,Trump Urges More Countries to Normalize Relati...,https://www.nytimes.com/2026/05/25/us/politics...,81
97,2026-05-25-14-20-10 +0000,nypost,Oil prices drop more than 5% after Trump says ...,https://nypost.com/2026/05/25/business/oil-pri...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
147,100,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...
134,57,2026-05-25-11-01-39 +0000,nypost,Pope Leo issues dire warning on ‘anti-human’ A...,https://nypost.com/2026/05/25/world-news/pope-...
184,37,2026-05-25-02-32-08 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
209,37,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
33,32,2026-05-25-18-22-50 +0000,nypost,Gary Sinise says his money would be ‘moving a ...,https://nypost.com/2026/05/25/us-news/gary-sin...
161,29,2026-05-25-08-45-00 +0000,wsj,Global Markets Gain and Oil Prices Retreat as ...,https://www.wsj.com/finance/commodities-future...
43,28,2026-05-25-17-57-32 +0000,nypost,Resistance grows against New York’s 18 planned...,https://nypost.com/2026/05/25/us-news/resistan...
154,26,2026-05-25-09-01-55 +0000,nyt,He Name-Drops Ocasio-Cortez in His Bid for Con...,https://www.nytimes.com/2026/05/25/us/politics...
54,25,2026-05-25-17-16-20 +0000,nypost,Spencer Pratt’s latest campaign ad puts LA’s f...,https://nypost.com/2026/05/25/us-news/spencer-...
110,22,2026-05-25-13-01-13 +0000,bbc,Cambodia's former opposition leader receives r...,https://www.bbc.com/news/articles/cm2ppv1r3xzo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)