## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-19-15-00 +0000,wsj,Why Everyone Hates the Ivy League,https://www.wsj.com/us-news/education/why-ever...
1,2026-04-15-19-14-50 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...
2,2026-04-15-19-14-00 +0000,wsj,Live Nation Illegally Monopolized Concerts and...,https://www.wsj.com/us-news/law/live-nation-il...
3,2026-04-15-19-11-26 +0000,nyt,Yale Report Finds Colleges Deserve Blame for H...,https://www.nytimes.com/2026/04/15/us/yale-rep...
4,2026-04-15-19-10-04 +0000,nyt,Senate Republicans Again Block Bid to Limit Tr...,https://www.nytimes.com/2026/04/15/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2380/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
4    iran     44
34  trump     40
5     war     29
96    new     22
41     up     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
181,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,151
233,2026-04-15-10-00-00 +0000,nypost,Trump needs ‘four- or five-month window’ betwe...,https://nypost.com/2026/04/15/us-news/trump-ne...,151
208,2026-04-15-11-39-31 +0000,nypost,Trump predicts Iran war is ‘very close to bein...,https://nypost.com/2026/04/15/us-news/trump-pr...,143
1,2026-04-15-19-14-50 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...,141
139,2026-04-15-15-27-22 +0000,bbc,Starmer says he's 'not going to yield' to pres...,https://www.bbc.com/news/articles/cdxdd7ddzgdo...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
181,151,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
1,141,2026-04-15-19-14-50 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...
133,69,2026-04-15-15-34-22 +0000,nypost,Eric Swalwell’s hotshot lawyer comes out swing...,https://nypost.com/2026/04/15/us-news/eric-swa...
310,54,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
238,54,2026-04-15-10-00-00 +0000,latimes,L.A.'s Blue Era: How popular are the Dodgers? ...,https://www.latimes.com/sports/dodgers/story/2...
141,43,2026-04-15-15-17-29 +0000,nypost,Disgraced Ex-Rep. Tony Gonzales begged another...,https://nypost.com/2026/04/15/us-news/ex-rep-t...
18,42,2026-04-15-18-53-10 +0000,nypost,Chinese oil tanker’s retreat from the Strait o...,https://nypost.com/2026/04/15/world-news/chine...
233,38,2026-04-15-10-00-00 +0000,nypost,Trump needs ‘four- or five-month window’ betwe...,https://nypost.com/2026/04/15/us-news/trump-ne...
235,36,2026-04-15-10-00-00 +0000,latimes,The price of LAUSD union peace will be $1.2 bi...,https://www.latimes.com/california/story/2026-...
338,35,2026-04-14-22-00-20 +0000,nyt,Carney Suspends Gas Tax in Canada as War Drive...,https://www.nytimes.com/2026/04/14/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)