## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-19-00-05 +0000,nypost,Duane ‘Keffe D’ Davis sentenced for mastermind...,https://nypost.com/2026/10/13/us-news/duane-ke...
1,2026-10-13-18-58-37 +0000,nyt,"The Oct. 7 Attack Changed Israel, but Not Its ...",https://www.nytimes.com/2026/10/13/world/middl...
2,2026-10-13-18-56-56 +0000,nyt,Judge Prohibits Further Tree Cutting at East P...,https://www.nytimes.com/2026/10/13/us/politics...
3,2026-10-13-18-55-59 +0000,nypost,Kips Bay AMC breaks silence on NYU Langone pro...,https://nypost.com/2026/10/13/us-news/kips-bay...
4,2026-10-13-18-55-50 +0000,bbc,Saudi coalition strikes fuel depot near Yemen'...,https://www.bbc.co.uk/news/articles/crx2d60y1p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2405/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
152     trump     43
153        he     17
302    russia     14
59        six     13
156  kimberly     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
305,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,129
134,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,113
102,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,105
83,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,104
322,2026-10-12-22-55-42 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/12/us-news/new-whit...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
305,129,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...
21,70,2026-10-13-18-27-47 +0000,nypost,Six Flags Over Georgia’s Goliath roller coaste...,https://nypost.com/2026/10/13/us-news/six-flag...
103,61,2026-10-13-15-52-15 +0000,bbc,"MI5 chief warns of threats to UK from Russia, ...",https://www.bbc.co.uk/news/articles/c60rl5vwpk...
300,60,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
180,55,2026-10-13-11-48-06 +0000,nypost,Ukraine got no warning about latest Russian st...,https://nypost.com/2026/10/13/world-news/ukrai...
25,50,2026-10-13-18-23-00 +0000,wsj,Kimberly Guilfoyle’s resignation feeds into De...,https://www.wsj.com/politics/policy/guilfoyles...
136,46,2026-10-13-14-00-00 +0000,wsj,Home sales in September rose for the first tim...,https://www.wsj.com/economy/housing/home-sales...
18,44,2026-10-13-18-32-25 +0000,cbc,Cornell suspends all frat parties as alleged g...,https://www.cbc.ca/news/world/cornell-suspends...
31,44,2026-10-13-18-10-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
174,42,2026-10-13-12-09-00 +0000,wsj,Oil Prices Fall as Traders Weigh Middle East R...,https://www.wsj.com/world/middle-east/oil-pric...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)