## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-16-18-53 +0000,bbc,Uefa to boycott World Cups if Fifa plans approved,https://www.bbc.co.uk/sport/football/articles/...
1,2026-07-30-16-18-15 +0000,nyt,Senators Cornyn and Tillis Force Delay of Blan...,https://www.nytimes.com/2026/07/29/us/politics...
2,2026-07-30-16-17-53 +0000,nyt,Trump Says He May Drop Blanche’s Attorney Gene...,https://www.nytimes.com/2026/07/30/us/politics...
3,2026-07-30-16-17-00 +0000,wsj,The Trump administration is considering attach...,https://www.wsj.com/politics/policy/u-s-weighs...
4,2026-07-30-16-15-33 +0000,bbc,Oprah Winfrey to close her school for girls in...,https://www.bbc.co.uk/news/articles/c75gre70vr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2694/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14   trump     34
109   iran     28
199    fed     22
148    new     21
110    war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-07-30-16-14-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...,144
258,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,119
240,2026-07-30-02-10-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...,96
358,2026-07-29-19-56-01 +0000,wapo,Trump threatens to hit Iran ‘hard’ following m...,https://www.washingtonpost.com/national-securi...,96
238,2026-07-30-02-28-39 +0000,nyt,"U.S. Strikes Iran Again, as Trump Encounters a...",https://www.nytimes.com/2026/07/29/us/trump-ir...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,144,2026-07-30-16-14-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...
258,108,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
201,81,2026-07-30-09-00-00 +0000,wsj,Capital Account: Fed Chairman Kevin Warsh says...,https://www.wsj.com/economy/central-banking/th...
95,69,2026-07-30-13-15-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
22,65,2026-07-30-16-00-00 +0000,wsj,Mortgage rates jumped to their highest level i...,https://www.wsj.com/economy/housing/mortgage-r...
56,55,2026-07-30-14-45-20 +0000,nypost,Under-fire Nancy Guthrie sheriff lashes out at...,https://nypost.com/2026/07/30/us-news/nancy-gu...
394,51,2026-07-29-17-51-00 +0000,wsj,Dr. Anthony Fauci invoked the Fifth Amendment ...,https://www.wsj.com/politics/policy/anthony-fa...
239,47,2026-07-30-02-21-44 +0000,nypost,Boeing takes massive hit as costs for new Air ...,https://nypost.com/2026/07/29/us-news/boeings-...
37,41,2026-07-30-15-20-19 +0000,bbc,At least five members of same family killed in...,https://www.bbc.co.uk/news/articles/cy8mk59l5j...
96,40,2026-07-30-13-14-00 +0000,wsj,Many business leaders are getting used to the ...,https://www.wsj.com/economy/trade/are-tariffs-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)