## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-20-59-35 +0000,nyt,U.S. Stocks Have Their Biggest Drop Since Star...,https://www.nytimes.com/2026/03/26/business/oi...
1,2026-03-26-20-58-00 +0000,wsj,Bank of Mexico Cuts Benchmark Interest Rate in...,https://www.wsj.com/economy/central-banking/ba...
2,2026-03-26-20-55-03 +0000,startribune,Live: DeLaSalle holds lead over Richfield with...,https://www.startribune.com/minnesota-boys-bas...
3,2026-03-26-20-53-23 +0000,nyt,Iran War Live Updates: Trump Again Gives Iran ...,https://www.nytimes.com/live/2026/03/26/world/...
4,2026-03-26-20-53-22 +0000,startribune,"Live from Baltimore: Twins, Orioles scoreless ...",https://www.startribune.com/live-from-baltimor...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3210/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6     iran     64
28   trump     48
7      war     36
232     up     12
197   will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-03-26-20-53-23 +0000,nyt,Iran War Live Updates: Trump Again Gives Iran ...,https://www.nytimes.com/live/2026/03/26/world/...,244
113,2026-03-26-17-39-06 +0000,wapo,"Iran rejects Trump proposal to end war, leavin...",https://www.washingtonpost.com/world/2026/03/2...,171
150,2026-03-26-16-18-00 +0000,wsj,Trump Tells Aides He Wants Speedy End to Iran War,https://www.wsj.com/politics/elections/trump-t...,170
131,2026-03-26-16-54-14 +0000,latimes,"Trump projects confidence, claims Iran is 'beg...",https://www.latimes.com/world-nation/story/202...,169
294,2026-03-26-09-00-00 +0000,wapo,Gulf countries want Trump to end Iran war — bu...,https://www.washingtonpost.com/world/2026/03/2...,166

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,244,2026-03-26-20-53-23 +0000,nyt,Iran War Live Updates: Trump Again Gives Iran ...,https://www.nytimes.com/live/2026/03/26/world/...
48,73,2026-03-26-19-27-00 +0000,wsj,Several Senate Republicans are pressing the Wh...,https://www.wsj.com/politics/policy/republican...
192,57,2026-03-26-14-05-29 +0000,nypost,"Gang-rape victim, 25, whose suicide attempt le...",https://nypost.com/2026/03/26/world-news/gang-...
404,47,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...
276,46,2026-03-26-09-40-00 +0000,wsj,Norges Bank Expects to Lift Borrowing Costs Th...,https://www.wsj.com/articles/norges-bank-expec...
239,44,2026-03-26-11-27-02 +0000,nypost,Trump warns Iran to ‘get serious’ about peace ...,https://nypost.com/2026/03/26/us-news/trump-wa...
62,41,2026-03-26-18-57-20 +0000,nypost,"Meta, Google face ‘Big Tobacco’-like reckoning...",https://nypost.com/2026/03/26/business/meta-go...
144,40,2026-03-26-16-29-20 +0000,eltecolote,New S.F. law could push street food vendors ou...,https://eltecolote.org/content/en/sf-food-stre...
270,39,2026-03-26-10-00-00 +0000,latimes,He was busted for gun possession. Now he's run...,https://www.latimes.com/california/story/2026-...
163,39,2026-03-26-15-50-00 +0000,wsj,World governments were buried in public debt o...,https://www.wsj.com/economy/global/energy-pric...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)