## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-02-42-44 +0000,bbc,Tropical Storm Bertha threatens US Gulf coast,https://www.bbc.co.uk/news/articles/cqjxzzdrl4...
1,2026-07-21-02-41-28 +0000,bbc,"US launches fresh strikes on Iran, as Trump wa...",https://www.bbc.co.uk/news/articles/cx25wg2x26...
2,2026-07-21-02-39-00 +0000,startribune,3 dead in St. Paul apartment shooting,https://www.startribune.com/3-dead-in-st-paul-...
3,2026-07-21-02-34-54 +0000,nyt,Epidemics and Rage,https://www.nytimes.com/2026/07/20/world/epide...
4,2026-07-21-02-28-31 +0000,nyt,Inside the Deadly U.S. Airstrike on a Shadow F...,https://www.nytimes.com/2026/07/20/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
10     trump     40
9       iran     32
209      new     29
382  burnham     26
383     will     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
373,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...,139
324,2026-07-20-10-42-53 +0000,nypost,Trump says new Qatar-donated Air Force One to ...,https://nypost.com/2026/07/20/us-news/trump-sa...,126
118,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,125
177,2026-07-20-18-57-41 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,120
226,2026-07-20-17-07-50 +0000,nypost,Enraged Trump warns Iran each US soldier kille...,https://nypost.com/2026/07/20/us-news/enraged-...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
373,139,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
374,95,2026-07-20-04-01-05 +0000,nyt,Five of the Main Challenges Awaiting Andy Burn...,https://www.nytimes.com/2026/07/20/world/europ...
118,71,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
5,70,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
25,66,2026-07-21-01-31-29 +0000,wapo,Nearly 100 U.S. troops injured in last two wee...,https://www.washingtonpost.com/world/2026/07/2...
176,47,2026-07-20-18-59-07 +0000,nypost,California gas suffers another huge setback as...,https://nypost.com/2026/07/20/us-news/californ...
221,41,2026-07-20-17-16-29 +0000,chitri,Ex-Mexican drug lord Ismael ‘El Mayo’ Zambada ...,https://www.chicagotribune.com/2026/07/20/mexi...
276,41,2026-07-20-13-30-48 +0000,nypost,Texas Dem House hopeful creeped on women in Sp...,https://nypost.com/2026/07/20/us-news/texas-de...
155,39,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...
350,38,2026-07-20-09-29-11 +0000,cbc,"27 bodies recovered, dozens feared dead after ...",https://www.cbc.ca/news/world/ferry-sinks-guya...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)