## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-14-32-18 +0000,bbc,What is expected to happen to UK interest rates?,https://www.bbc.com/news/articles/c3dky111m40o...
1,2026-04-29-14-30-48 +0000,wapo,Senate panel advances Trump’s pick for Federal...,https://www.washingtonpost.com/business/2026/0...
2,2026-04-29-14-30-00 +0000,wsj,Oil Up 5% as U.S.-Iran Deadlock Signals Longer...,https://www.wsj.com/finance/commodities-future...
3,2026-04-29-14-29-33 +0000,nypost,Girlfriend allegedly stabbed beau to death for...,https://nypost.com/2026/04/29/us-news/girlfrie...
4,2026-04-29-14-27-12 +0000,nypost,Woman who plunged 50 feet to death at Indianap...,https://nypost.com/2026/04/29/us-news/woman-wh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
8      trump     51
319     king     26
14      iran     24
163      new     20
320  charles     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
192,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...,193
207,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...,160
157,2026-04-29-09-00-00 +0000,wsj,In a bid to keep construction of the White Hou...,https://www.wsj.com/politics/national-security...,149
83,2026-04-29-11-46-13 +0000,nyt,"At State Dinner, King Charles Charms the Court...",https://www.nytimes.com/2026/04/29/us/politics...,125
210,2026-04-29-01-22-32 +0000,bbc,In pictures: King joins Trump for White House ...,https://www.bbc.com/news/articles/c86e6z26xdpo...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
192,193,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...
389,88,2026-04-28-16-51-51 +0000,nyt,UAE Says It Will Leave OPEC as Iran War Strain...,https://www.nytimes.com/2026/04/28/world/middl...
352,57,2026-04-28-18-37-44 +0000,nypost,Indian villager digs up sister’s corpse and ca...,https://nypost.com/2026/04/28/world-news/india...
99,56,2026-04-29-11-00-00 +0000,nypost,King Charles takes in NYC for first time in 19...,https://nypost.com/2026/04/29/us-news/king-cha...
250,55,2026-04-28-22-05-30 +0000,nypost,Musk kicks off explosive OpenAI trial by slamm...,https://nypost.com/2026/04/28/business/musk-ki...
107,48,2026-04-29-10-46-00 +0000,wsj,War has imposed a heavy cost on Iran’s economy...,https://www.wsj.com/world/middle-east/iranians...
264,46,2026-04-28-21-40-00 +0000,wsj,A seashell photo gets Comey charged with threa...,https://www.wsj.com/politics/policy/seashell-p...
375,43,2026-04-28-17-16-12 +0000,nypost,FCC orders a review of ABC’s broadcast license...,https://nypost.com/2026/04/28/media/fcc-preps-...
345,38,2026-04-28-18-49-33 +0000,cbc,U.S. special forces soldier pleads not guilty ...,https://www.cbc.ca/news/world/polymarket-us-so...
150,37,2026-04-29-09-01-07 +0000,nyt,San Antonio Poverty Rate Remains High Despite ...,https://www.nytimes.com/2026/04/29/us/san-anto...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)