## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-27-14-55-35 +0000,nyt,How Billionaires Are Fighting the Prop 40 Cali...,https://www.nytimes.com/2026/10/27/technology/...
1,2026-10-27-14-55-00 +0000,wsj,Don’t Let Politics Poison Your Portfolio,https://www.wsj.com/finance/investing/dont-let...
2,2026-10-27-14-54-00 +0000,wsj,General Motors Moving Stock Listing to Nasdaq ...,https://www.wsj.com/finance/stocks/general-mot...
3,2026-10-27-14-48-09 +0000,nypost,Furious Florida girlfriend tracks cheating bea...,https://nypost.com/2026/10/27/us-news/furious-...
4,2026-10-27-14-47-46 +0000,nyt,Votes from Israel’s Arab citizens could help d...,https://www.nytimes.com/live/2026/10/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2375/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
76       trump     38
36    election     28
31      israel     18
331        new     16
278  anthropic     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
308,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,111
348,2026-10-26-18-40-02 +0000,nyt,Trump’s Election Attacks Enter New Pre-emptive...,https://www.nytimes.com/2026/10/25/us/politics...,92
246,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...,86
175,2026-10-27-08-25-46 +0000,nypost,Polls open in Israel for country’s first elect...,https://nypost.com/2026/10/27/world-news/elect...,85
9,2026-10-27-14-38-02 +0000,nyt,Election Officials Fear Trump Administration’s...,https://www.nytimes.com/2026/10/27/us/election...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
308,111,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...
175,57,2026-10-27-08-25-46 +0000,nypost,Polls open in Israel for country’s first elect...,https://nypost.com/2026/10/27/world-news/elect...
270,56,2026-10-26-21-53-41 +0000,nypost,Ex-FBI Director James Comey facing new crimina...,https://nypost.com/2026/10/26/us-news/ex-fbi-d...
33,51,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
162,50,2026-10-27-09-21-34 +0000,wsj,Stock Market Today: Tech Stocks Extend Gains A...,https://www.wsj.com/livecoverage/stock-market-...
268,49,2026-10-26-22-11-18 +0000,nypost,Israeli PM Netanyahu and challenger Gadi Eisen...,https://nypost.com/2026/10/26/world-news/how-n...
246,48,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...
56,46,2026-10-27-13-00-00 +0000,nypost,Katie Zacharia reveals lesson her brief White ...,https://nypost.com/2026/10/27/us-news/katie-za...
204,44,2026-10-27-04-07-00 +0000,wsj,Judge Ana Reyes issued a preliminary injunctio...,https://www.wsj.com/politics/policy/judge-bars...
138,41,2026-10-27-10-00-22 +0000,chitri,"Clocks fall back this weekend, reigniting deba...",https://www.chicagotribune.com/2026/10/27/dayl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)