## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-06-13-53-41 +0000,nypost,Airline passenger who had to be duct-taped to ...,https://nypost.com/2026/09/06/us-news/airline-...
1,2026-09-06-13-41-36 +0000,wapo,Deadly Iran wedding strike likely due to U.S. ...,https://www.washingtonpost.com/world/2026/09/0...
2,2026-09-06-13-38-26 +0000,nyt,Families Turn to Symbolic Cremation After Nepa...,https://www.nytimes.com/2026/09/04/world/asia/...
3,2026-09-06-13-28-53 +0000,nyt,Iran’s Attacks Keep the Strait of Hormuz in a ...,https://www.nytimes.com/2026/09/06/business/ir...
4,2026-09-06-13-27-40 +0000,wapo,Alternative for Germany looks for big boost in...,https://www.washingtonpost.com/world/2026/09/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
83    trump     20
85      new     11
53  ukraine     11
50   envoys      8
54    talks      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
160,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...,63
130,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,59
181,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...,53
88,2026-09-06-07-22-19 +0000,nypost,Trump’s super PAC pours $10M into Ken Paxton’s...,https://nypost.com/2026/09/06/us-news/trumps-s...,52
146,2026-09-05-20-27-59 +0000,nyt,Trump’s Super PAC Will Spend $10 Million on Te...,https://www.nytimes.com/2026/09/05/us/politics...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
160,63,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...
177,39,2026-09-05-15-17-15 +0000,cbc,U.S. military hits 3 Iranian oil tankers after...,https://www.cbc.ca/news/world/iran-united-stat...
130,39,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
117,34,2026-09-06-00-08-44 +0000,nypost,Iran plotting new Oct. 7-style attack against ...,https://nypost.com/2026/09/05/world-news/iran-...
90,27,2026-09-06-06-20-08 +0000,nypost,"Ex-Team USA triathlete, NYC dad drowns while s...",https://nypost.com/2026/09/06/us-news/ex-team-...
102,25,2026-09-06-02-30-00 +0000,nypost,California’s free ride means illegal migrants ...,https://nypost.com/2026/09/05/us-news/inside-c...
116,23,2026-09-06-00-17-05 +0000,bbc,'He was a lifeline' - Families at a loss after...,https://www.bbc.co.uk/news/articles/cg491zp13q...
108,23,2026-09-06-01-39-56 +0000,nypost,South Carolina magistrate rips into Saylor Hay...,https://nypost.com/2026/09/05/us-news/south-ca...
27,22,2026-09-06-11-00-00 +0000,missionlocal,Meet the 71-year-old keeping tabs on Concord’s...,https://missionlocal.org/2026/09/concord-immig...
105,21,2026-09-06-01-55-36 +0000,nypost,Flock cameras could turn American neighborhood...,https://nypost.com/2026/09/05/tech/flock-camer...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)