## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-10-00-00 +0000,nypost,How Islanders diehard became ‘Cookie Lady’ aft...,https://nypost.com/2026/03/24/us-news/islander...
1,2026-03-24-10-00-00 +0000,nypost,Three meteorites crashed into Earth this month...,https://nypost.com/2026/03/24/us-news/meteorit...
2,2026-03-24-09-59-00 +0000,wsj,"Eurozone, Asian Business Activity Slows as Ira...",https://www.wsj.com/economy/eurozone-asian-bus...
3,2026-03-24-09-58-00 +0000,wsj,"Sterling Remains Weaker, Gilt Yields Lower Aft...",https://www.wsj.com/finance/currencies/asian-c...
4,2026-03-24-09-55-00 +0000,wsj,Apollo to Acquire Nippon Sheet Glass in $3.7 B...,https://www.wsj.com/business/deals/apollo-to-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2630/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
180  trump     44
26    iran     43
27     war     26
178  court     15
45     oil     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
353,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,136
325,2026-03-23-14-08-41 +0000,nypost,Trump says ‘we don’t know’ if Iran’s new Supre...,https://nypost.com/2026/03/23/us-news/trump-sa...,130
338,2026-03-23-13-16-13 +0000,nypost,"Dow rallies 600 points, oil tumbles below $100...",https://nypost.com/2026/03/23/business/dow-fut...,130
220,2026-03-23-19-47-08 +0000,wapo,Trump says U.S. is postponing some strikes as ...,https://www.washingtonpost.com/politics/2026/0...,129
133,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
353,136,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...
282,94,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
81,65,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
208,64,2026-03-23-20-21-51 +0000,bbc,Oil falls and shares rebound after Trump says ...,https://www.bbc.com/news/articles/czex56kwxxzo...
184,62,2026-03-23-21-13-47 +0000,bbc,'Like the plane got cut in half': LaGuardia cr...,https://www.bbc.com/news/articles/c78rdze8zvjo...
201,42,2026-03-23-20-43-02 +0000,nypost,Anti-communist dance troupe Shen Yun claims CC...,https://nypost.com/2026/03/23/world-news/shen-...
267,40,2026-03-23-17-12-46 +0000,nypost,OnlyFans star Sophie Rain mourns Leo Radvinsky...,https://nypost.com/2026/03/23/business/onlyfan...
104,36,2026-03-24-01-54-00 +0000,wsj,"Sen. Markwayne Mullin (R., Okla.) won confirma...",https://www.wsj.com/politics/policy/markwayne-...
239,36,2026-03-23-18-41-00 +0000,wsj,ICE Agents—Many Unmasked—Deploy to Airports Am...,https://www.wsj.com/us-news/trump-asks-ice-age...
70,34,2026-03-24-04-52-28 +0000,nypost,Sheriff Chris Nanos shrugs off missteps in Nan...,https://nypost.com/2026/03/24/us-news/sheriff-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)