## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-21-45-54 +0000,startribune,Live: Vikings lead Buccaneers in Kyler Murray’...,https://www.startribune.com/minnesota-vikings-...
1,2026-09-27-21-44-51 +0000,startribune,Lynx star Olivia Miles conquered her rookie se...,https://www.startribune.com/olivia-miles-stats...
2,2026-09-27-21-40-23 +0000,startribune,Trump looms large in Little-Pratt race for Ang...,https://www.startribune.com/mn-cd2-debates-eri...
3,2026-09-27-21-38-59 +0000,nypost,Airbnb renter turns tables on armed Florida ho...,https://nypost.com/2026/09/27/us-news/airbnb-r...
4,2026-09-27-21-36-22 +0000,nyt,Iran Still Awaits ‘Official’ U.S. Response Des...,https://www.nytimes.com/2026/09/27/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2328/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
24   trump     29
123    war     14
180    new     10
47    iran     10
56   china      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
101,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...,81
112,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...,74
113,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...,73
75,2026-09-27-17-30-46 +0000,wapo,"Trump says U.S., Iran slated for indirect talk...",https://www.washingtonpost.com/world/2026/09/2...,64
5,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
101,81,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...
112,56,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...
78,40,2026-09-27-17-24-26 +0000,nypost,One normally quiet Texas race shows 2026 will ...,https://nypost.com/2026/09/27/us-news/how-texa...
166,34,2026-09-27-08-00-00 +0000,cbc,"Unions have new leverage, not less, under Libe...",https://www.cbc.ca/news/politics/section-107-c...
114,34,2026-09-27-14-16-04 +0000,cbc,OpenAI pauses training of latest models after ...,https://www.cbc.ca/news/business/openai-pause-...
170,32,2026-09-27-06-47-34 +0000,nypost,"27 killed, dozens wounded in horror mass shoot...",https://nypost.com/2026/09/27/world-news/south...
5,31,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...
97,31,2026-09-27-16-00-34 +0000,chitri,Tensions run high in Northern Ireland after co...,https://www.chicagotribune.com/2026/09/27/nort...
54,29,2026-09-27-19-08-34 +0000,cbc,"Vucic resigns as Serbia's president, setting u...",https://www.cbc.ca/news/world/vucic-resigns-se...
186,28,2026-09-27-00-57-46 +0000,nypost,Ex-Trump official Alina Habba weds Turkish bil...,https://nypost.com/2026/09/26/us-news/ex-trump...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)