## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-02-05-43-51 +0000,nypost,"Raging wildfire torches Spokane homes, turns n...",https://nypost.com/2026/08/02/us-news/spokane-...
1,2026-08-02-05-40-42 +0000,bbc,Three killed after bomb detonated at Moscow re...,https://www.bbc.co.uk/news/articles/c86n4ljxp6...
2,2026-08-02-05-29-22 +0000,nyt,More Than a Dozen Wildfires Burn in Washington...,https://www.nytimes.com/2026/08/01/us/wildfire...
3,2026-08-02-05-26-39 +0000,bbc,Mountaineer Nirmal Purja killed in Pakistan av...,https://www.bbc.co.uk/news/articles/clyljq79kd...
4,2026-08-02-05-17-45 +0000,nyt,"After Most Migrants Leave Ceuta, Exhausted Hol...",https://www.nytimes.com/2026/08/02/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
38        trump     23
94        spain     11
395         new     10
140  california     10
42         iran      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
71,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...,53
15,2026-08-02-03-05-16 +0000,bbc,Trump says he is cancelling strikes on Iran su...,https://www.bbc.co.uk/news/articles/cjwx74qgld...,53
72,2026-08-01-21-28-51 +0000,chitri,Jeanine Pirro refutes President Donald Trump’s...,https://www.chicagotribune.com/2026/08/01/hear...,53
104,2026-08-01-17-16-51 +0000,bbc,Trump administration drops Reflecting Pool van...,https://www.bbc.co.uk/news/articles/cz05yx5dd7...,51
5,2026-08-02-05-02-29 +0000,nyt,"Trump Says He Is Canceling Strikes on Iran, Pe...",https://www.nytimes.com/2026/08/02/world/middl...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
71,53,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...
111,40,2026-08-01-16-50-51 +0000,cbc,"Nirmal Purja, 'inspirational' Nepali climber, ...",https://www.cbc.ca/news/world/nepal-climber-ni...
121,39,2026-08-01-16-08-45 +0000,cbc,Hunger and hostility cited by migrants as reas...,https://www.cbc.ca/news/world/ceuta-morocco-mi...
123,33,2026-08-01-16-00-00 +0000,wsj,A Tech Founder Wanted to Start a New Country. ...,https://www.wsj.com/tech/a-tech-founder-wanted...
15,30,2026-08-02-03-05-16 +0000,bbc,Trump says he is cancelling strikes on Iran su...,https://www.bbc.co.uk/news/articles/cjwx74qgld...
16,29,2026-08-02-03-04-00 +0000,wsj,"Three Dead, at Least Five Injured in Idaho Sho...",https://www.wsj.com/us-news/three-dead-at-leas...
180,26,2026-08-01-10-00-00 +0000,latimes,The percentage of homes surviving California w...,https://www.latimes.com/environment/story/2026...
27,25,2026-08-02-01-00-00 +0000,wsj,High-profile donors have given little or no mo...,https://www.wsj.com/politics/elections/democra...
152,24,2026-08-01-12-41-17 +0000,bbc,Faisal Islam: Four reasons why Fifa's World Cu...,https://www.bbc.co.uk/news/articles/clyvd8363w...
199,23,2026-08-01-05-53-27 +0000,nypost,Oprah Winfrey says she will close her school f...,https://nypost.com/2026/08/01/world-news/oprah...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)