## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-17-10-09-08 +0000,bbc,Typical mortgage costs £788 a year more than b...,https://www.bbc.com/news/articles/c0mgd3z1e9ko...
1,2026-03-17-10-04-57 +0000,nyt,Trump Says He Wants to Delay Visit to China Be...,https://www.nytimes.com/live/2026/03/16/world/...
2,2026-03-17-10-04-56 +0000,nyt,Trump’s Threat to Delay Summit With Xi Casts N...,https://www.nytimes.com/2026/03/16/world/middl...
3,2026-03-17-10-00-31 +0000,wapo,A state’s rule for housing that promotes diver...,https://www.washingtonpost.com/nation/2026/03/...
4,2026-03-17-10-00-16 +0000,nyt,"In Maine, Janet Mills Slams Graham Platner in ...",https://www.nytimes.com/2026/03/17/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
7   trump     62
5    iran     36
6     war     29
20    new     19
81    oil     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-03-16-21-17-23 +0000,nypost,"Vance denies ‘wedge’ with Trump over Iran war,...",https://nypost.com/2026/03/16/us-news/vance-de...,192
301,2026-03-16-14-53-29 +0000,nyt,"With Iran War, Trump Risks Stepping on Gains F...",https://www.nytimes.com/2026/03/16/us/politics...,142
9,2026-03-17-09-52-59 +0000,nypost,Top Iran security official who warned Trump he...,https://nypost.com/2026/03/17/world-news/israe...,142
210,2026-03-16-20-48-32 +0000,cbc,The broken economic argument for Trump’s war o...,https://www.cbc.ca/player/play/9.7131000?cmp=rss,131
261,2026-03-16-17-57-14 +0000,latimes,Oil flows through Santa Barbara coastal pipeli...,https://www.latimes.com/california/story/2026-...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,192,2026-03-16-21-17-23 +0000,nypost,"Vance denies ‘wedge’ with Trump over Iran war,...",https://nypost.com/2026/03/16/us-news/vance-de...
303,65,2026-03-16-14-50-49 +0000,nypost,Gas prices reach highest level since October 2...,https://nypost.com/2026/03/16/business/gas-pri...
186,60,2026-03-16-21-38-51 +0000,nypost,"Trump slams China, US allies for not jumping a...",https://nypost.com/2026/03/16/world-news/trump...
65,57,2026-03-17-06-33-00 +0000,wsj,President Trump said White House chief of staf...,https://www.wsj.com/politics/policy/susie-wile...
334,53,2026-03-16-11-49-14 +0000,nypost,Iranian drone strike takes out fuel tank at Du...,https://nypost.com/2026/03/16/world-news/irani...
127,52,2026-03-17-01-00-00 +0000,wsj,"For the fifth year running, Fed officials find...",https://www.wsj.com/economy/central-banking/fe...
1,43,2026-03-17-10-04-57 +0000,nyt,Trump Says He Wants to Delay Visit to China Be...,https://www.nytimes.com/live/2026/03/16/world/...
261,43,2026-03-16-17-57-14 +0000,latimes,Oil flows through Santa Barbara coastal pipeli...,https://www.latimes.com/california/story/2026-...
79,37,2026-03-17-04-21-44 +0000,nypost,Rep. Jasmine Crockett insists she ‘followed al...,https://nypost.com/2026/03/17/us-news/rep-jasm...
132,30,2026-03-17-00-42-09 +0000,nypost,Grief author Kouri Richins found guilty of fat...,https://nypost.com/2026/03/16/us-news/grief-au...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)