## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-11-44-22 +0000,nypost,Santa Claus among 11 busted in Louisiana child...,https://nypost.com/2026/06/30/us-news/santa-cl...
1,2026-06-30-11-43-59 +0000,nyt,Prominent Tech Founder in Indonesia Is Found G...,https://www.nytimes.com/2026/06/30/business/in...
2,2026-06-30-11-43-00 +0000,wsj,How Companies Are Managing AI Token Spend,https://www.wsj.com/cio-journal/how-companies-...
3,2026-06-30-11-41-24 +0000,nyt,Mideast Live Updates: U.S. and Iran Gear Up fo...,https://www.nytimes.com/live/2026/06/30/world/...
4,2026-06-30-11-36-05 +0000,bbc,Manhunt under way after bomb injures Ukrainian...,https://www.bbc.co.uk/news/articles/cpv37wx03v...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
74     trump     39
104    court     37
103  supreme     34
149      new     15
27        up     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
274,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...,183
190,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...,179
336,2026-06-29-14-19-39 +0000,nypost,Supreme Court blocks Trump bid to fire Fed gov...,https://nypost.com/2026/06/29/us-news/supreme-...,167
175,2026-06-29-22-18-20 +0000,nyt,Trump Renews Threat to Fire Fed Governor Lisa ...,https://www.nytimes.com/2026/06/29/us/politics...,161
292,2026-06-29-16-51-52 +0000,bbc,Supreme Court blocks Trump's attempt to fire F...,https://www.bbc.co.uk/news/articles/cy4wwy0nke...,160

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
274,183,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...
144,68,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
267,49,2026-06-29-18-04-54 +0000,nypost,"Witkoff, Kushner to head to Qatar for Iran tal...",https://nypost.com/2026/06/29/world-news/irani...
190,49,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...
58,44,2026-06-30-09-38-34 +0000,nypost,Helicopter pilot reports near miss with remote...,https://nypost.com/2026/06/30/us-news/helicopt...
264,42,2026-06-29-18-16-57 +0000,bbc,New 'No 10 North' plan will rebalance power in...,https://www.bbc.co.uk/news/articles/cx2jw5q5pd...
107,40,2026-06-30-04-25-00 +0000,nypost,Dave Portnoy says he ‘would love’ to run again...,https://nypost.com/2026/06/30/us-news/dave-por...
156,35,2026-06-29-23-09-18 +0000,nyt,Sex Abuse Survivors Reach $395 Million Settlem...,https://www.nytimes.com/2026/06/29/us/san-fran...
172,35,2026-06-29-22-28-24 +0000,bbc,Canada hero's historic World Cup goal was forg...,https://www.bbc.co.uk/news/articles/cn4r0r0ryl...
96,34,2026-06-30-06-02-00 +0000,wsj,"Yen Falls to 40-Year Low Versus Dollar, Trader...",https://www.wsj.com/finance/currencies/yen-fal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)