## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-20-34-07 +0000,nypost,Jeff Bezos told Trump the Washington Post was ...,https://nypost.com/2026/06/17/us-news/jeff-bez...
1,2026-06-17-20-33-05 +0000,nyt,Elon Musk’s Next Move May Be a Mega-Merger of ...,https://www.nytimes.com/2026/06/17/business/sp...
2,2026-06-17-20-32-36 +0000,nypost,Inspector gives key update on missing South Ca...,https://nypost.com/2026/06/17/us-news/inspecto...
3,2026-06-17-20-30-00 +0000,wsj,Markets Rattled by Warsh Poker Face,https://www.wsj.com/finance/investing/markets-...
4,2026-06-17-20-29-49 +0000,nypost,Skywatchers could see the crescent moon specta...,https://nypost.com/2026/06/17/us-news/skywatch...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2521/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
3    trump     51
92    iran     32
101   deal     24
114    fed     21
217    new     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
83,2026-06-17-18-41-12 +0000,bbc,Fed holds US interest rates steady as uncertai...,https://www.bbc.com/news/articles/cdjkl78vd7lo...,155
139,2026-06-17-16-31-02 +0000,nypost,Trump says Iran laughed at ‘stupid son of a bi...,https://nypost.com/2026/06/17/us-news/trump-sa...,150
111,2026-06-17-17-44-50 +0000,nypost,Trump jokingly reveals whom he’ll blame if Ira...,https://nypost.com/2026/06/17/us-news/trump-jo...,145
44,2026-06-17-19-44-00 +0000,wsj,"Trump Defends Iran Deal, Says He Wants to Avoi...",https://www.wsj.com/world/trump-defends-iran-d...,135
73,2026-06-17-18-58-25 +0000,nyt,Trump Administration Shares Terms of Iran Deal...,https://www.nytimes.com/2026/06/17/world/middl...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
83,155,2026-06-17-18-41-12 +0000,bbc,Fed holds US interest rates steady as uncertai...,https://www.bbc.com/news/articles/cdjkl78vd7lo...
319,87,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
302,75,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
365,70,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
146,52,2026-06-17-16-21-35 +0000,startribune,Minnesota town sets new rules for public speak...,https://www.startribune.com/small-town-sets-ne...
306,51,2026-06-17-02-50-36 +0000,nypost,Bungee instructors who tossed student off 130-...,https://nypost.com/2026/06/16/world-news/bunge...
61,49,2026-06-17-19-14-00 +0000,wsj,President Trump tied together fights over poli...,https://www.wsj.com/politics/policy/trump-has-...
127,45,2026-06-17-17-09-21 +0000,nypost,Final 14-point US-Iran peace deal reveals sign...,https://nypost.com/2026/06/17/us-news/complete...
312,39,2026-06-17-02-00-00 +0000,wsj,Rep. Debbie Wasserman Schultz’s move to run in...,https://www.wsj.com/politics/elections/florida...
225,38,2026-06-17-11-53-40 +0000,nypost,Hot mics at the G7 capture Meloni telling othe...,https://nypost.com/2026/06/17/world-news/itali...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)