## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-28-07-10-02 +0000,startribune,Israel says it intercepted first incoming miss...,https://www.startribune.com/israel-launches-ne...
1,2026-03-28-06-58-37 +0000,bbc,Nepal's ex-PM arrested over fatal protest crac...,https://www.bbc.com/news/articles/cn89ry7y835o...
2,2026-03-28-06-51-34 +0000,nyt,12 U.S. Troops Injured in Attack on Saudi Base...,https://www.nytimes.com/live/2026/03/27/world/...
3,2026-03-28-06-49-26 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/28/world/...
4,2026-03-28-06-47-48 +0000,bbc,Free prom hire boutique set up for two schools,https://www.bbc.com/news/articles/c17ve1n8njgo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
244   iran     40
6      war     33
183  trump     25
55    will     14
29     two     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
206,2026-03-27-16-43-10 +0000,latimes,"Iran war rages on heading into fifth week, as ...",https://www.latimes.com/world-nation/story/202...,105
203,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...,101
94,2026-03-27-22-00-42 +0000,nypost,Trump considers renaming Strait of Hormuz afte...,https://nypost.com/2026/03/27/us-news/trump-co...,100
262,2026-03-27-13-50-03 +0000,nypost,"Dow enters correction territory, oil jumps abo...",https://nypost.com/2026/03/27/business/dow-fal...,99
252,2026-03-27-14-05-39 +0000,nypost,Israel warns attacks on Iran ‘will escalate an...,https://nypost.com/2026/03/27/world-news/israe...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
206,105,2026-03-27-16-43-10 +0000,latimes,"Iran war rages on heading into fifth week, as ...",https://www.latimes.com/world-nation/story/202...
203,76,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...
201,56,2026-03-27-17-00-00 +0000,wsj,About a year into the full-blown trade war bet...,https://www.wsj.com/economy/trade/how-trumps-t...
70,49,2026-03-27-23-40-40 +0000,nypost,"Ten Americans wounded in Iranian missile, dron...",https://nypost.com/2026/03/27/us-news/ten-amer...
166,43,2026-03-27-18-33-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
23,41,2026-03-28-03-51-00 +0000,wsj,President Trump signed an executive order to p...,https://www.wsj.com/politics/policy/house-gop-...
170,41,2026-03-27-18-28-28 +0000,nypost,"Gang-rape victim Noelia Castillo, who died of ...",https://nypost.com/2026/03/27/world-news/gang-...
111,38,2026-03-27-21-12-54 +0000,nypost,Trump speaks on close friend Tiger Woods’ Flor...,https://nypost.com/2026/03/27/sports/trump-spe...
67,37,2026-03-27-23-58-00 +0000,wsj,Bank of America Agrees to Pay $72.5 Million to...,https://www.wsj.com/finance/banking/bank-of-am...
237,37,2026-03-27-15-18-40 +0000,nypost,Austria plans to ban social media use for unde...,https://nypost.com/2026/03/27/world-news/austr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)