## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-16-19-13-43 +0000,nyt,White House Teleprompter Operator Bet on Trump...,https://www.nytimes.com/2026/07/16/technology/...
1,2026-07-16-19-12-26 +0000,nypost,Survivor of deadly Alcatraz boat accident reve...,https://nypost.com/2026/07/16/us-news/survivor...
2,2026-07-16-19-12-22 +0000,nypost,Lefty actress Cynthia Nixon appointed to panel...,https://nypost.com/2026/07/16/us-news/cynthia-...
3,2026-07-16-19-11-24 +0000,nyt,Settlement Reached in Ugly Fight Over Election...,https://www.nytimes.com/2026/07/16/us/election...
4,2026-07-16-19-09-06 +0000,nypost,Ex-NFL players say they lost $1M in alleged fa...,https://nypost.com/2026/07/16/business/ex-nfl-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
5         trump     44
111        iran     29
19          new     22
112         war     16
123  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
173,2026-07-16-13-46-46 +0000,nypost,Kai Trump pinpoints personality trait she got ...,https://nypost.com/2026/07/16/us-news/kai-trum...,127
383,2026-07-15-20-26-19 +0000,nypost,"Trump doesn’t rule out decimating IRGC, warns ...",https://nypost.com/2026/07/15/us-news/trump-do...,116
178,2026-07-16-13-20-24 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...,114
342,2026-07-15-22-32-37 +0000,nyt,"At War With Iran Again, Trump Finds an Opponen...",https://www.nytimes.com/2026/07/14/us/politics...,105
129,2026-07-16-15-52-31 +0000,nyt,Maker of Drone Boats Used in Iran War Will Ope...,https://www.nytimes.com/2026/07/16/business/ma...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
173,127,2026-07-16-13-46-46 +0000,nypost,Kai Trump pinpoints personality trait she got ...,https://nypost.com/2026/07/16/us-news/kai-trum...
129,100,2026-07-16-15-52-31 +0000,nyt,Maker of Drone Boats Used in Iran War Will Ope...,https://www.nytimes.com/2026/07/16/business/ma...
11,61,2026-07-16-18-58-13 +0000,nypost,Wild video shows pitiful NYC street fight betw...,https://nypost.com/2026/07/16/us-news/wild-vid...
339,51,2026-07-15-22-46-37 +0000,nyt,"For Argentina, a World Cup Semifinal Against E...",https://www.nytimes.com/2026/07/15/world/ameri...
60,50,2026-07-16-17-58-40 +0000,nypost,Your guide on NYC’s air quality: What the Cana...,https://nypost.com/2026/07/16/health/what-the-...
15,46,2026-07-16-18-52-35 +0000,bbc,White House teleprompter operator accused of m...,https://www.bbc.co.uk/news/articles/cjrvdqyr5d...
338,45,2026-07-15-22-50-00 +0000,wsj,Homeland Security Secretary Markwayne Mullin a...,https://www.wsj.com/politics/policy/trump-was-...
40,44,2026-07-16-18-27-34 +0000,nypost,Another California city plots becoming sanctua...,https://nypost.com/2026/07/16/us-news/another-...
116,44,2026-07-16-16-19-50 +0000,nyt,Ukraine’s Ousted Defense Minister Attacks the ...,https://www.nytimes.com/2026/07/16/world/europ...
261,39,2026-07-16-08-34-51 +0000,wsj,Stock Market Today: Nasdaq Slips as Chip Stock...,https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)