## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-11-46-00 +0000,wsj,"U.S. Treasury Yields, Dollar Rise Amid Fresh M...",https://www.wsj.com/finance/jgbs-mixed-ahead-o...
1,2026-07-07-11-44-21 +0000,nyt,Estonia Won the War on Fentanyl. What Came Nex...,https://www.nytimes.com/2026/07/07/world/europ...
2,2026-07-07-11-42-40 +0000,bbc,Woman suspected of Monaco bomb attack found de...,https://www.bbc.co.uk/news/articles/c5yz3770yg...
3,2026-07-07-11-36-38 +0000,nyt,"U.S. Loss to Belgium Is Gut Punch, but Bright ...",https://www.nytimes.com/2026/07/06/us/world-cu...
4,2026-07-07-11-35-29 +0000,bbc,One million more UK homeowners set to face hi...,https://www.bbc.co.uk/news/articles/cze9kpxx6d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
168  trump     46
95   world     26
96     cup     18
200   nato     17
216     up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
291,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...,178
96,2026-07-07-07-33-41 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,132
352,2026-07-06-14-21-08 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...,129
262,2026-07-06-19-19-15 +0000,nyt,Trump Defends Asking FIFA to Review Folarin Ba...,https://www.nytimes.com/2026/07/06/us/politics...,123
159,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
291,178,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
159,94,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
89,62,2026-07-07-08-00-00 +0000,cbc,Alberta's new pipeline deal could allow Canadi...,https://www.cbc.ca/news/science/pipeline-asia-...
288,61,2026-07-06-17-47-41 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
24,54,2026-07-07-10-49-02 +0000,nypost,Massive brawl breaks out inside FIFA Fanzone o...,https://nypost.com/2026/07/07/us-news/massive-...
278,50,2026-07-06-18-21-25 +0000,nyt,The Funeral of Iran’s Supreme Leader Ayatollah...,https://www.nytimes.com/2026/07/04/world/middl...
326,44,2026-07-06-15-26-29 +0000,bbc,Nigeria says two nationals killed in South Afr...,https://www.bbc.co.uk/news/articles/cqj11lxwnn...
285,41,2026-07-06-17-58-04 +0000,nypost,Father of teen found dead in suitcase issues d...,https://nypost.com/2026/07/06/world-news/fathe...
109,38,2026-07-07-06-36-31 +0000,nypost,Cuba plunges into island wide blackout power o...,https://nypost.com/2026/07/07/world-news/cuba-...
153,37,2026-07-07-00-57-46 +0000,wapo,China test-fires long-range missile into Pacif...,https://www.washingtonpost.com/national-securi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)