## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-19-15-00-38 +0000,nypost,Archaeologists unveil skeletal remains they be...,https://nypost.com/2026/08/19/world-news/archa...
1,2026-08-19-14-59-16 +0000,bbc,"Florida picks nominees for governor, and other...",https://www.bbc.co.uk/news/articles/cpvwgym9xl...
2,2026-08-19-14-58-08 +0000,wapo,Darline Graham stumbles over national security...,https://www.washingtonpost.com/politics/2026/0...
3,2026-08-19-14-57-22 +0000,wapo,UAE says it is suspending trade with Iran afte...,https://www.washingtonpost.com/world/2026/08/1...
4,2026-08-19-14-57-00 +0000,wsj,The Meal-Kit Industry Is in Disarray After a M...,https://www.wsj.com/business/retail/the-meal-k...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2370/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
118    trump     50
8    florida     34
912  primary     17
102      new     15
223     bond     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...,140
232,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...,139
234,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...,137
242,2026-08-18-23-56-32 +0000,nyt,"Sydney Gruters, Wife of R.N.C. Chair, Wins Hou...",https://www.nytimes.com/2026/08/18/us/politics...,126
230,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,140,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...
191,84,2026-08-19-03-39-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...
329,55,2026-08-18-20-46-00 +0000,wsj,U.S. Tech Stocks Slip as Bond Yields Hit Decad...,https://www.wsj.com/finance/stocks/u-s-tech-st...
66,53,2026-08-19-12-37-06 +0000,cbc,Israel opens criminal probes over killings of ...,https://www.cbc.ca/news/world/israel-criminal-...
186,50,2026-08-19-03-56-35 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
25,47,2026-08-19-14-24-38 +0000,nypost,Dad of NJ kids killed by grandpa in DUI boatin...,https://nypost.com/2026/08/19/us-news/dad-of-n...
91,45,2026-08-19-11-17-00 +0000,wsj,The Morning Risk Report: Pivotal Child Safety ...,https://www.wsj.com/risk-compliance-journal/th...
203,44,2026-08-19-02-58-35 +0000,nyt,Eric Barlow Wins Wyoming’s Republican Governor...,https://www.nytimes.com/2026/08/18/us/politics...
369,43,2026-08-18-18-28-42 +0000,nypost,Rep. Young Kim donates campaign contributions ...,https://nypost.com/2026/08/18/us-news/young-ki...
131,39,2026-08-19-10-00-00 +0000,latimes,AI hallucinated case law in insurance company'...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)