## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-14-11-54-38 +0000,nyt,Tech Stocks Shudder in Response to Calls to Sl...,https://www.nytimes.com/2026/09/14/business/te...
1,2026-09-14-11-53-20 +0000,nyt,Money Is Flowing Into Space Start-Ups. Some In...,https://www.nytimes.com/2026/09/14/business/de...
2,2026-09-14-11-53-19 +0000,nyt,"Why Is Danny Meyer, the Happy Face of Hospital...",https://www.nytimes.com/2026/09/14/dining/dann...
3,2026-09-14-11-53-13 +0000,nyt,"Modi Served World Leaders a Meatless Meal, and...",https://www.nytimes.com/2026/09/14/world/asia/...
4,2026-09-14-11-48-55 +0000,nypost,"Trump slams ‘terrible’ AOC, Mamdani after DSA ...",https://nypost.com/2026/09/14/us-news/trump-sl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2474/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
32     trump     37
71        ai     21
152      new     12
134  ukraine     11
22        up     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
203,2026-09-13-18-13-12 +0000,chitri,President Donald Trump downplays the need to c...,https://www.chicagotribune.com/2026/09/13/trum...,106
239,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...,105
184,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...,98
178,2026-09-13-20-25-00 +0000,wsj,President Trump made a surprise trade announce...,https://www.wsj.com/economy/trade/trump-pledge...,97
182,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
203,106,2026-09-13-18-13-12 +0000,chitri,President Donald Trump downplays the need to c...,https://www.chicagotribune.com/2026/09/13/trum...
24,65,2026-09-14-11-04-00 +0000,wsj,"The price of gasoline—and, by proxy, the Iran ...",https://www.wsj.com/politics/policy/with-50-da...
170,65,2026-09-13-21-30-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
182,48,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...
208,45,2026-09-13-17-41-22 +0000,chitri,President Donald Trump calls on Ukraine to hal...,https://www.chicagotribune.com/2026/09/13/trum...
64,36,2026-09-14-09-10-00 +0000,wsj,"U.S. Treasury Yields Edge Lower, German 10-Yea...",https://www.wsj.com/economy/central-banking/u-...
184,34,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...
107,32,2026-09-14-06-59-04 +0000,nypost,Amazon halts use of cargo company involved in ...,https://nypost.com/2026/09/14/us-news/amazon-h...
99,28,2026-09-14-07-53-28 +0000,nypost,"Indonesia ferry disaster leaves six dead, 129 ...",https://nypost.com/2026/09/14/world-news/indon...
119,27,2026-09-14-03-38-13 +0000,bbc,Russia hits Ukrainian train shortly after Bori...,https://www.bbc.co.uk/news/articles/cy5zg41dkq...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)