## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-01-17-20 +0000,48hills,Femmes rock fiercely at Doll Fest,https://48hills.org/2026/03/femmes-rock-fierce...
1,2026-03-26-01-11-07 +0000,nypost,LIV Golf sued by Long Island distillery over a...,https://nypost.com/2026/03/25/sports/liv-golf-...
2,2026-03-26-01-10-47 +0000,nypost,Fourth Labor Dept. staffer leaves during IG pr...,https://nypost.com/2026/03/25/us-news/fourth-l...
3,2026-03-26-01-04-58 +0000,startribune,Live: Pequot Lakes beats Blake in first 2A qua...,https://www.startribune.com/minnesota-boys-bas...
4,2026-03-26-01-04-57 +0000,missionlocal,Bayview Buzz: Harvard Business School comes to...,https://missionlocal.org/2026/03/bayview-buzz-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
54   iran     52
42  trump     43
55    war     23
98    oil     19
91     up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
135,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...,173
106,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...,154
160,2026-03-25-19-17-42 +0000,nypost,Trump ‘prepared to unleash hell’ if Iran won’t...,https://nypost.com/2026/03/25/world-news/leavi...,145
241,2026-03-25-15-36-56 +0000,nyt,Oil Prices Rise After Iran Denies Talks With T...,https://www.nytimes.com/2026/03/24/business/oi...,144
105,2026-03-25-21-23-15 +0000,nyt,Oil Prices Fall as Trump Shows Eagerness to Ta...,https://www.nytimes.com/2026/03/24/business/oi...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
135,173,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...
108,86,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...
125,83,2026-03-25-20-50-44 +0000,nypost,Kristi Noem keeps her lover Corey Lewandowski ...,https://nypost.com/2026/03/25/us-news/kristi-n...
210,71,2026-03-25-17-06-24 +0000,nypost,"Meta, YouTube found liable for woman’s debilit...",https://nypost.com/2026/03/25/us-news/jury-tak...
270,60,2026-03-25-14-19-00 +0000,wsj,Trump plans to install some of the biggest nam...,https://www.wsj.com/politics/policy/trump-to-n...
106,59,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...
214,58,2026-03-25-16-59-00 +0000,wsj,The Federal Reserve ran an operating loss of $...,https://www.wsj.com/economy/central-banking/fe...
389,45,2026-03-25-02-00-00 +0000,wsj,Consumers around the U.S. say they are rejigge...,https://www.wsj.com/economy/consumers/how-amer...
192,43,2026-03-25-18-02-00 +0000,wsj,Democrat Emily Gregory beat a Trump-backed Rep...,https://www.wsj.com/politics/elections/democra...
201,42,2026-03-25-17-27-23 +0000,nypost,Supreme Court sides with internet service prov...,https://nypost.com/2026/03/25/business/scotus-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)