## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-15-13-03-38 +0000,nyt,Where Future Champions Race Against the Tide,https://www.nytimes.com/2026/08/15/world/europ...
1,2026-08-15-13-01-39 +0000,nyt,At Least 47 Dead as 7.7-Magnitude Earthquake R...,https://www.nytimes.com/2026/08/15/world/asia/...
2,2026-08-15-13-00-00 +0000,missionlocal,The 1077,https://missionlocal.org/2026/08/the-1077/
3,2026-08-15-12-56-11 +0000,nypost,Iran’s top commander boasts that war efforts p...,https://nypost.com/2026/08/15/world-news/irans...
4,2026-08-15-12-45-00 +0000,nypost,How a squeegee saved six men trapped on an ele...,https://nypost.com/2026/08/15/us-news/how-a-sq...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2390/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
90      trump     42
28        new     18
1085    court     12
7        dead     11
672   lincoln      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
242,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...,113
146,2026-08-14-21-47-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...,107
164,2026-08-14-21-13-51 +0000,latimes,Trump says USS Abraham Lincoln deployment 'not...,https://www.latimes.com/politics/story/2026-08...,97
244,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...,95
316,2026-08-14-13-13-34 +0000,chitri,President Donald Trump set to highlight violen...,https://www.chicagotribune.com/2026/08/14/trum...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
242,113,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...
153,64,2026-08-14-21-32-00 +0000,nypost,Family of dead ex-Cambridge professor Jason Ar...,https://nypost.com/2026/08/14/world-news/famil...
288,55,2026-08-14-15-26-04 +0000,cbc,Luigi Mangione admits to shooting health insur...,https://www.cbc.ca/news/world/us-federal-heari...
244,53,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...
234,44,2026-08-14-18-32-44 +0000,nypost,Better.com’s new CEO vacations in France as co...,https://nypost.com/2026/08/14/business/better-...
14,42,2026-08-15-12-00-00 +0000,nypost,‘Iran’s black widow’ faces multiple death sent...,https://nypost.com/2026/08/15/us-news/irans-bl...
154,40,2026-08-14-21-30-06 +0000,chitri,Palestinians besieged in West Bank village fea...,https://www.chicagotribune.com/2026/08/14/isra...
275,37,2026-08-14-16-25-00 +0000,wapo,Michigan’s marquee Senate race close in first ...,https://www.washingtonpost.com/politics/2026/0...
302,36,2026-08-14-14-49-00 +0000,wsj,"Sales at U.S. retailers slid in July, the late...",https://www.wsj.com/economy/weak-retail-sales-...
7,34,2026-08-15-12-30-00 +0000,nypost,NYC designer found dead on Montauk yacht ‘hara...,https://nypost.com/2026/08/15/us-news/nyc-desi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)