## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-27-01-27-02 +0000,nyt,"C.F.T.C. Begins Investigating Polymarket, a Te...",https://www.nytimes.com/2026/06/26/us/politics...
1,2026-06-27-01-22-49 +0000,startribune,Moorhead’s Wyatt Cullen taken 10th in NHL draf...,https://www.startribune.com/wyatt-cullen-draft...
2,2026-06-27-01-12-00 +0000,nypost,‘Central figure’ in $250M Minnesota fraud case...,https://nypost.com/2026/06/26/us-news/suspect-...
3,2026-06-27-01-09-51 +0000,nyt,Venezuela Live Updates: Trump’s Vow to ‘Run’ V...,https://www.nytimes.com/live/2026/06/26/world/...
4,2026-06-27-01-09-49 +0000,nyt,Nations Send Rescue Teams and Aid to Venezuela...,https://www.nytimes.com/2026/06/26/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2477/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
24    venezuela     27
27        trump     27
44   california     20
54          new     18
133        iran     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-06-27-01-09-51 +0000,nyt,Venezuela Live Updates: Trump’s Vow to ‘Run’ V...,https://www.nytimes.com/live/2026/06/26/world/...,97
211,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...,97
189,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...,88
176,2026-06-26-18-03-32 +0000,bbc,Trump accuses Iran of ceasefire breach after S...,https://www.bbc.co.uk/news/articles/ckg54g0ry0...,76
181,2026-06-26-17-48-35 +0000,nyt,"John Bolton, Former Trump Adviser, Pleads Guil...",https://www.nytimes.com/2026/06/26/us/politics...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,97,2026-06-27-01-09-51 +0000,nyt,Venezuela Live Updates: Trump’s Vow to ‘Run’ V...,https://www.nytimes.com/live/2026/06/26/world/...
211,70,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...
139,65,2026-06-26-19-22-24 +0000,nypost,Gavin Newsom’s billionaire tax two-step: squee...,https://nypost.com/2026/06/26/us-news/gavin-ne...
189,61,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...
190,49,2026-06-26-17-11-00 +0000,wsj,Former Trump Adviser John Bolton Pleads Guilty...,https://www.wsj.com/us-news/law/john-bolton-pl...
8,48,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
196,43,2026-06-26-17-00-00 +0000,wsj,The search for a new leader of the Federal Res...,https://www.wsj.com/economy/central-banking/at...
59,41,2026-06-26-22-23-12 +0000,missionlocal,San Francisco kicks off Pride weekend with Wor...,https://missionlocal.org/2026/06/san-francisco...
278,41,2026-06-26-11-49-23 +0000,nypost,NY diplomat found dead in Myanmar was stabbed ...,https://nypost.com/2026/06/26/world-news/ameri...
77,39,2026-06-26-21-41-00 +0000,wsj,Millions of people who signed up for Affordabl...,https://www.wsj.com/politics/policy/millions-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)