## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-19-03-54 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...
1,2026-03-13-19-02-46 +0000,nyt,Read Some of John F. Burns’s Reporting From Ar...,https://www.nytimes.com/2026/03/13/world/middl...
2,2026-03-13-19-02-16 +0000,wapo,Hegseth vows thorough probe of school strike t...,https://www.washingtonpost.com/national-securi...
3,2026-03-13-18-58-00 +0000,wsj,"TotalEnergies Shutting Production in Qatar, Ir...",https://www.wsj.com/business/energy-oil/totale...
4,2026-03-13-18-58-00 +0000,wsj,Cuba Acknowledges Negotiations With Washington,https://www.wsj.com/world/cuba-acknowledges-ne...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
1     iran     61
3      war     39
6    trump     34
95     oil     24
415    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-13-19-03-54 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...,229
350,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,167
293,2026-03-13-01-32-01 +0000,nyt,Trump Removes Sanctions on Russia to Help Oil ...,https://www.nytimes.com/2026/03/12/us/politics...,159
89,2026-03-13-16-17-58 +0000,nyt,Trump-Iran Timeline: Key Moments Leading Up to...,https://www.nytimes.com/2026/03/13/us/politics...,156
66,2026-03-13-17-09-48 +0000,nypost,Trump says US seizing Kharg Island ‘not high o...,https://nypost.com/2026/03/13/us-news/trump-sa...,143

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,229,2026-03-13-19-03-54 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...
355,73,2026-03-12-21-04-34 +0000,nyt,New Iranian Leader Vows to Keep Global Oil Gat...,https://www.nytimes.com/2026/03/12/world/middl...
152,72,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
223,50,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
128,50,2026-03-13-15-00-06 +0000,bbc,UK urges allies to keep up pressure on Russia ...,https://www.bbc.com/news/articles/cvg3yxd49xno...
192,41,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
184,37,2026-03-13-11-47-09 +0000,bbc,'No-one will hire women' - India's top court r...,https://www.bbc.com/news/articles/c0436qkegdqo...
136,36,2026-03-13-14-36-32 +0000,wapo,Trump administration allows for Russian oil sa...,https://www.washingtonpost.com/business/2026/0...
127,33,2026-03-13-15-01-00 +0000,wsj,The Commerce Department said GDP grew at just ...,https://www.wsj.com/economy/consumers/economy-...
216,33,2026-03-13-10-00-00 +0000,nypost,Pentagon AI chief Emil Michael says it’s ‘tota...,https://nypost.com/2026/03/13/business/pentago...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)