## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
1,2026-07-07-00-09-00 +0000,wsj,Locals Are Clashing With Scientologists Over t...,https://www.wsj.com/us-news/locals-are-clashin...
2,2026-07-07-00-09-00 +0000,wsj,Oil Rises on Possible Position Adjustments Bef...,https://www.wsj.com/finance/commodities-future...
3,2026-07-07-00-08-14 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/06/us/pla...
4,2026-07-07-00-06-50 +0000,bbc,"AI chip boom lifts Samsung profits by 1,800%",https://www.bbc.co.uk/news/articles/c1kyy8yrpx...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
75   trump     49
65   world     25
66     cup     14
13      he     14
316   nato     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
173,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...,172
278,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...,132
244,2026-07-06-14-21-08 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...,124
8,2026-07-06-23-51-27 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,123
313,2026-07-06-09-00-11 +0000,nyt,Emil Bove Defended Trump in Court. Then Trump ...,https://www.nytimes.com/2026/07/06/us/emil-bov...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
173,172,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
0,66,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
170,60,2026-07-06-17-47-41 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
330,47,2026-07-06-05-29-00 +0000,bbc,"After a year of ICE raids, Southern California...",https://www.bbc.co.uk/sport/football/articles/...
168,47,2026-07-06-17-57-00 +0000,wsj,Canada CPI Expectations Ramped Up Prior to U.S...,https://www.wsj.com/economy/central-banking/ca...
27,44,2026-07-06-23-10-21 +0000,nyt,New Videos of Charlie Kirk’s Killing Emerge in...,https://www.nytimes.com/2026/07/06/us/charlie-...
54,41,2026-07-06-21-58-08 +0000,nypost,"Boy, 6, whose dad was fatally shot before he w...",https://nypost.com/2026/07/06/us-news/boy-6-wh...
278,40,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...
256,37,2026-07-06-13-25-13 +0000,nyt,"With $8 Billion in Venezuelan Oil Money, U.S. ...",https://www.nytimes.com/2026/07/06/world/ameri...
266,36,2026-07-06-12-26-20 +0000,nyt,China Test Fires Long-Range Ballistic Missile ...,https://www.nytimes.com/2026/07/06/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)