## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-04-01-19 +0000,nyt,Can King Charles Help Heal the U.S.-British Ru...,https://www.nytimes.com/2026/04/27/world/europ...
1,2026-04-27-04-01-12 +0000,nyt,8 Memorable Moments From Past British Royal Vi...,https://www.nytimes.com/2026/04/27/world/europ...
2,2026-04-27-04-01-11 +0000,nyt,The Rising Chinese Automaker Not Named BYD,https://www.nytimes.com/2026/04/27/business/ge...
3,2026-04-27-03-50-54 +0000,nypost,13 malnourished sloths rescued from bankrupt F...,https://nypost.com/2026/04/26/us-news/13-malno...
4,2026-04-27-03-49-00 +0000,wsj,China’s Industrial Profits Jump Despite Tighte...,https://www.wsj.com/economy/chinas-industrial-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

               word  score
33            trump     43
42           dinner     32
128        shooting     32
40   correspondents     24
38            white     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
5,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,204
162,2026-04-26-15-22-31 +0000,nypost,Trump recounts political unity after White Hou...,https://nypost.com/2026/04/26/us-news/trump-re...,199
88,2026-04-26-20-25-08 +0000,nyt,What We Know About the Shooting at the White H...,https://www.nytimes.com/2026/04/26/us/politics...,186
158,2026-04-26-15-38-13 +0000,nypost,Read White House Correspondents’ Dinner gunman...,https://nypost.com/2026/04/26/us-news/read-whc...,181
203,2026-04-26-09-20-15 +0000,nyt,Trump Describes His Mind-Set After Shooting at...,https://www.nytimes.com/2026/04/26/us/politics...,177

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
5,204,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
143,97,2026-04-26-16-47-42 +0000,nypost,WHCD shooting suspect Cole Allen mocked lack o...,https://nypost.com/2026/04/26/us-news/whcd-sho...
149,48,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...
180,37,2026-04-26-12-29-41 +0000,wapo,"Trump calls off Witkoff, Kushner trip to Pakis...",https://www.washingtonpost.com/world/2026/04/2...
150,34,2026-04-26-16-18-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
91,32,2026-04-26-19-52-11 +0000,nyt,Shooting Prompts Discussions About King Charle...,https://www.nytimes.com/2026/04/26/us/politics...
12,30,2026-04-27-03-00-00 +0000,wsj,Keep DNA a state secret. No motorcade snubs. A...,https://www.wsj.com/politics/how-to-avoid-fist...
57,29,2026-04-26-22-25-15 +0000,nypost,Rodeo announcer has brutal prank played on him...,https://nypost.com/2026/04/26/us-news/rodeo-an...
147,26,2026-04-26-16-32-00 +0000,wsj,Sen. Thom Tillis said he would support Kevin W...,https://www.wsj.com/politics/policy/tillis-dro...
221,25,2026-04-26-04-55-38 +0000,nyt,"A Gunman Got Close to Trump Again, Raising Mor...",https://www.nytimes.com/2026/04/26/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)