## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-02-14-59-59 +0000,nyt,How Germany May Have Misjudged Trump’s Anger o...,https://www.nytimes.com/2026/05/02/world/europ...
1,2026-05-02-14-58-29 +0000,nyt,U.S. Fast-Tracks Arms Deals Valued at $8.6 Bil...,https://www.nytimes.com/2026/05/02/world/middl...
2,2026-05-02-14-57-59 +0000,nypost,Leapin’ lizards! Cops stop man with 13 zip-tie...,https://nypost.com/2026/05/02/us-news/leapin-l...
3,2026-05-02-14-57-05 +0000,nyt,Spirit Airlines Shuts Down After Years of Stru...,https://www.nytimes.com/2026/05/02/business/sp...
4,2026-05-02-14-47-58 +0000,nyt,Secret Service Avoids Hearings for Now on Corr...,https://www.nytimes.com/2026/05/01/us/secret-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
3       trump     45
5        iran     31
141       war     19
22     spirit     12
23   airlines     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...,138
127,2026-05-02-00-41-43 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,130
18,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,120
162,2026-05-01-22-00-00 +0000,nyt,Trump Tells Congress Why He Doesn’t Need Its A...,https://www.nytimes.com/2026/05/01/us/politics...,120
118,2026-05-02-01-30-23 +0000,nypost,Trump administration pulling 5K troops out of ...,https://nypost.com/2026/05/01/world-news/trump...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,138,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...
228,49,2026-05-01-19-21-00 +0000,wsj,Trump’s new Air Force One will arrive this sum...,https://www.wsj.com/politics/national-security...
42,48,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
240,42,2026-05-01-18-43-04 +0000,nypost,"Chirayu Rana, ex-JPMorgan staffer accused of ‘...",https://nypost.com/2026/05/01/business/male-ex...
127,35,2026-05-02-00-41-43 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...
110,35,2026-05-02-02-21-42 +0000,latimes,Thousands rally in L.A. for May Day to protest...,https://www.latimes.com/california/story/2026-...
67,33,2026-05-02-09-50-13 +0000,nypost,Teen suspect in murder of 2 Kentucky bank empl...,https://nypost.com/2026/05/02/us-news/kentucky...
88,32,2026-05-02-08-58-09 +0000,nypost,US warns shipping firms they could face sancti...,https://nypost.com/2026/05/02/world-news/us-wa...
272,30,2026-05-01-16-35-37 +0000,nypost,"Blackburn, Klobuchar slam Mark Zuckerberg for ...",https://nypost.com/2026/05/01/business/blackbu...
277,30,2026-05-01-16-22-11 +0000,cbc,10 killed in Israeli strikes in south Lebanon ...,https://www.cbc.ca/news/world/israel-south-leb...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)