## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-21-00-42 +0000,nypost,Iran airs rare clip of supreme leader — but he...,https://nypost.com/2026/08/09/world-news/iran-...
1,2026-08-09-20-58-18 +0000,bbc,Suspected crime boss Daniel Kinahan appears in...,https://www.bbc.co.uk/news/articles/c62qd5plzp...
2,2026-08-09-20-57-59 +0000,nyt,"Senate Bows to Reality, Leaving Trump’s Voting...",https://www.nytimes.com/2026/08/08/us/politics...
3,2026-08-09-20-57-13 +0000,nyt,Still Waiting for Peace in Gaza,https://www.nytimes.com/2026/08/09/world/gaza-...
4,2026-08-09-20-48-28 +0000,nypost,"Man, 30, shot dead in hail of bullets at NYC p...",https://nypost.com/2026/08/09/us-news/man-30-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
24    trump     18
125    plan      9
20   senate      7
30     gaza      7
75      out      6

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-08-09-20-01-50 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,57
90,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...,57
82,2026-08-09-14-18-10 +0000,bbc,"Israel rejects Trump's 15-point plan for Gaza,...",https://www.bbc.co.uk/news/articles/c5yw4lpe0y...,54
29,2026-08-09-18-58-00 +0000,wsj,Israel Rejects Next Phase of Trump’s Gaza Peac...,https://www.wsj.com/world/middle-east/israel-r...,52
18,2026-08-09-19-48-53 +0000,nyt,Israel Rejects Trump’s 15-Point Plan to Disarm...,https://www.nytimes.com/2026/08/09/world/middl...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,57,2026-08-09-20-01-50 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
65,43,2026-08-09-15-30-00 +0000,wsj,After notching a narrow victory in Michigan’s ...,https://www.wsj.com/politics/elections/michiga...
26,26,2026-08-09-19-14-55 +0000,nypost,AOC pushes voters to assess what Francesca Hon...,https://nypost.com/2026/08/09/us-news/aoc-push...
7,24,2026-08-09-20-25-22 +0000,nypost,Rich kid driving souped-up McLaren goes ballis...,https://nypost.com/2026/08/09/us-news/rich-kid...
101,24,2026-08-09-12-24-04 +0000,cbc,14-year-old accused in deadly school shooting ...,https://www.cbc.ca/news/world/accused-thai-sch...
0,21,2026-08-09-21-00-42 +0000,nypost,Iran airs rare clip of supreme leader — but he...,https://nypost.com/2026/08/09/world-news/iran-...
9,21,2026-08-09-20-19-19 +0000,nypost,Mamdani mum on icy relationship with rival Esp...,https://nypost.com/2026/08/09/us-news/mamdani-...
27,21,2026-08-09-19-04-22 +0000,nypost,Dope fresh NY weed data show fans were flying ...,https://nypost.com/2026/08/09/us-news/dope-fre...
162,20,2026-08-08-22-17-33 +0000,nyt,Blackbird Mountain Guides Report on Lake Tahoe...,https://www.nytimes.com/2026/08/08/us/tahoe-av...
124,19,2026-08-09-09-30-00 +0000,wsj,"If You Get in a Car Crash, the Risk Is Growing...",https://www.wsj.com/finance/if-you-get-in-a-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)