## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-29-08-39-52 +0000,nyt,Live Updates: Scale of Flood Disaster Grows as...,https://www.nytimes.com/live/2026/08/28/world/...
1,2026-08-29-08-30-10 +0000,chitri,Today in History: Hurricane Katrina struck,https://www.chicagotribune.com/2026/08/29/toda...
2,2026-08-29-08-12-45 +0000,nypost,New York’s Erie County axes DHS job fair over ...,https://nypost.com/2026/08/29/us-news/new-york...
3,2026-08-29-08-08-36 +0000,nypost,Norway mourns King Harald as crowds gather at ...,https://nypost.com/2026/08/29/world-news/norwa...
4,2026-08-29-08-00-00 +0000,cbc,Carney government asks court to strike down cl...,https://www.cbc.ca/news/politics/climate-feder...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
67   trump     47
6    nepal     22
13     new     17
650  warsh     16
339    war     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
93,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...,133
353,2026-08-28-09-00-00 +0000,wapo,Trump promised a short Iran war. Six months la...,https://www.washingtonpost.com/politics/2026/0...,108
98,2026-08-28-21-43-00 +0000,wsj,Fed Chairman Kevin Warsh spoke today and the o...,https://www.wsj.com/economy/warsh-speaks-and-r...,99
152,2026-08-28-19-41-00 +0000,wsj,A West Point for Space? Trump Calls for New Ac...,https://www.wsj.com/politics/national-security...,98
70,2026-08-28-23-20-50 +0000,nypost,Trump announces ‘biggest oil deal in world his...,https://nypost.com/2026/08/28/us-news/trump-an...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
93,133,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...
98,99,2026-08-28-21-43-00 +0000,wsj,Fed Chairman Kevin Warsh spoke today and the o...,https://www.wsj.com/economy/warsh-speaks-and-r...
317,73,2026-08-28-10-35-06 +0000,bbc,Watch: Why rescuers fear new barrier lake coul...,https://www.bbc.co.uk/news/videos/cj06j16vpr5o...
151,62,2026-08-28-19-41-00 +0000,wsj,The U.S. will develop an academy to train pers...,https://www.wsj.com/politics/national-security...
321,52,2026-08-28-10-09-00 +0000,wsj,"Tech firms are courting Democrats, the South f...",https://www.wsj.com/politics/policy/corporate-...
70,49,2026-08-28-23-20-50 +0000,nypost,Trump announces ‘biggest oil deal in world his...,https://nypost.com/2026/08/28/us-news/trump-an...
47,45,2026-08-29-01-00-00 +0000,wsj,The U.S. has rushed so many munitions to the M...,https://www.wsj.com/politics/national-security...
83,44,2026-08-28-22-23-21 +0000,wapo,The labor market was weaker early in Trump’s t...,https://www.washingtonpost.com/business/2026/0...
344,44,2026-08-28-09-27-17 +0000,bbc,Norway's King Harald dies aged 89: A beloved m...,https://www.bbc.co.uk/news/articles/clykn5p517...
189,43,2026-08-28-18-23-07 +0000,nypost,California BBQ spot shutters after 20-year run...,https://nypost.com/2026/08/28/business/storied...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)