## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-24-16-36-17 +0000,nypost,NY GOP gov hopeful Bruce Blakeman calls for ‘c...,https://nypost.com/2026/06/24/us-news/ny-gop-g...
1,2026-06-24-16-35-04 +0000,nyt,Europe Is Sweltering. Here’s What That Looks Like,https://www.nytimes.com/2026/06/24/world/europ...
2,2026-06-24-16-34-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
3,2026-06-24-16-34-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/articles/energy-utilities-...
4,2026-06-24-16-33-14 +0000,nypost,Dallas OKs incentive package for $1.3B Morgan ...,https://nypost.com/2026/06/24/business/dallas-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
20   trump     40
136    new     27
153   iran     26
197    war     19
71    tech     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-06-24-16-34-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...,124
126,2026-06-24-12-10-09 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...,124
69,2026-06-24-14-57-21 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...,120
212,2026-06-24-03-22-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/national-security...,117
111,2026-06-24-13-24-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/elections/key-tak...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,124,2026-06-24-16-34-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
111,114,2026-06-24-13-24-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/elections/key-tak...
348,88,2026-06-23-19-17-09 +0000,nypost,Unsettling ‘jellyfish’ drones spotted by downe...,https://nypost.com/2026/06/23/world-news/irans...
293,56,2026-06-23-21-53-00 +0000,wsj,Opinion | Will the World Cup Make America Love...,https://www.wsj.com/opinion/will-the-world-cup...
305,55,2026-06-23-21-25-48 +0000,nypost,Sable Offshore lashes out after ruling — threa...,https://nypost.com/2026/06/23/us-news/gas-and-...
5,52,2026-06-24-16-31-42 +0000,nyt,Europe Heat Wave Latest News: After France’s H...,https://www.nytimes.com/2026/06/24/weather/eur...
378,48,2026-06-23-17-41-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
163,44,2026-06-24-10-00-00 +0000,latimes,"In echoes of Palisades fire, Boyle Heights fir...",https://www.latimes.com/california/story/2026-...
259,44,2026-06-23-23-29-25 +0000,latimes,Family says police fatally shot teen during me...,https://www.latimes.com/california/story/2026-...
228,38,2026-06-24-01-49-00 +0000,wsj,Congress passed its most-ambitious housing leg...,https://www.wsj.com/economy/housing/a-landmark...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)