## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-09-00-28 +0000,wapo,Live updates: Israel and Iran escalate attacks...,https://www.washingtonpost.com/world/2026/03/0...
1,2026-03-04-09-00-00 +0000,cbc,U.S. could hold a 'red card' over Canada's Gri...,https://www.cbc.ca/news/politics/canada-f35-gr...
2,2026-03-04-09-00-00 +0000,cbc,Saab sees Canada as 'great' partner to design ...,https://www.cbc.ca/news/politics/saab-canada-f...
3,2026-03-04-08-53-17 +0000,nyt,Where Are China’s A.I. Doomers?,https://www.nytimes.com/2026/03/04/world/asia/...
4,2026-03-04-08-53-09 +0000,bbc,Asia stock markets slump and oil rises on fear...,https://www.bbc.com/news/articles/cwy884ekn0jo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
3      iran     92
44    trump     47
37      war     38
80    texas     31
53  strikes     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-03-04-08-52-03 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...,237
258,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,205
332,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...,191
387,2026-03-03-13-41-43 +0000,bbc,Zelensky fears Trump's Iran war could hurt Ukr...,https://www.bbc.com/news/articles/clyv10dre79o...,189
434,2026-03-03-09-57-15 +0000,bbc,Trump voters back him on Iran - but that could...,https://www.bbc.com/news/articles/cvg35401nrqo...,188

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,237,2026-03-04-08-52-03 +0000,nyt,Iran Live Updates: Israel Begins ‘Broad Wave o...,https://www.nytimes.com/live/2026/03/03/world/...
216,131,2026-03-03-22-25-24 +0000,latimes,"Oil jumps, stocks fall, as Trump presses into ...",https://www.latimes.com/politics/story/2026-03...
9,122,2026-03-04-08-44-00 +0000,wsj,"State Rep. James Talarico, a 36-year-old with ...",https://www.wsj.com/politics/elections/john-co...
98,89,2026-03-04-03-44-09 +0000,nyt,"Beyond a Trade War, China, Japan and Others in...",https://www.nytimes.com/2026/03/02/business/us...
85,67,2026-03-04-04-41-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
380,65,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
145,59,2026-03-04-00-50-02 +0000,startribune,White Bear Lake woman identified as one of the...,https://www.startribune.com/white-bear-lake-wo...
137,51,2026-03-04-01-10-05 +0000,nypost,Masked driver of car loaded with ammunition de...,https://nypost.com/2026/03/03/us-news/suspicio...
25,48,2026-03-04-08-02-45 +0000,nypost,US hits nearly 2K Iranian targets in first 100...,https://nypost.com/2026/03/04/world-news/us-op...
362,41,2026-03-03-15-37-23 +0000,bbc,"No new tax rises in Spring Statement, but don'...",https://www.bbc.com/news/articles/cj6dwg4deewo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)