## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-16-16-35 +0000,nyt,Trump Administration Pressures Some Immigrants...,https://www.nytimes.com/2026/07/22/us/immigrat...
1,2026-07-22-16-12-22 +0000,startribune,Live: Gophers football unofficially kicks off ...,https://www.startribune.com/minnesota-gophers-...
2,2026-07-22-16-11-23 +0000,bbc,"Burkina Faso, Mali and Niger launch bid for 20...",https://www.bbc.co.uk/sport/football/articles/...
3,2026-07-22-16-07-15 +0000,bbc,Ex-Southern Water boss among four charged over...,https://www.bbc.co.uk/news/articles/c36d0njy7j...
4,2026-07-22-16-05-18 +0000,nypost,Trump tech official accuses China’s Moonshot A...,https://nypost.com/2026/07/22/business/chinas-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     59
88          new     31
131        iran     28
71          war     19
124  california     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-07-22-15-51-16 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...,165
317,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,144
211,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...,140
186,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,129
52,2026-07-22-14-55-17 +0000,nypost,Trump attends dignified transfer of 4 US troop...,https://nypost.com/2026/07/22/us-news/trump-at...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,165,2026-07-22-15-51-16 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...
20,98,2026-07-22-15-48-56 +0000,cbc,Canada urges U.K. under new PM to reconsider j...,https://www.cbc.ca/news/world/canada-push-uk-j...
317,97,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
110,68,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
61,52,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
27,50,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
399,47,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
284,45,2026-07-21-23-14-21 +0000,nypost,Zelensky fires Ukraine military chief and name...,https://nypost.com/2026/07/21/world-news/zelen...
343,44,2026-07-21-20-42-24 +0000,chitri,Canadian PM Mark Carney says he and Trump will...,https://www.chicagotribune.com/2026/07/21/trum...
377,44,2026-07-21-18-17-44 +0000,latimes,California wouldn't be the right place to laun...,https://www.latimes.com/business/story/2026-07...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)