## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-15-22-54-57 +0000,nypost,Heart-stopping photos show huge wave sweep man...,https://nypost.com/2026/03/15/us-news/heart-st...
1,2026-03-15-22-54-12 +0000,nypost,Off-Duty NYPD captain charged after pummeling ...,https://nypost.com/2026/03/15/us-news/off-duty...
2,2026-03-15-22-52-00 +0000,wsj,White House Tries to Build Coalition on Iran t...,https://www.wsj.com/politics/national-security...
3,2026-03-15-22-51-19 +0000,nyt,Iran War Live Updates: ‘No Guarantees’ Oil Pri...,https://www.nytimes.com/live/2026/03/15/world/...
4,2026-03-15-22-50-20 +0000,nyt,Is Latin America Ready to Abandon Cuba?,https://www.nytimes.com/2026/03/14/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2613/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
24     iran     31
27      war     26
81    trump     21
258  israel     10
70      her      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
73,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...,97
182,2026-03-15-00-29-36 +0000,nypost,Trump says Iran wants to end the war – but ter...,https://nypost.com/2026/03/14/world-news/trump...,93
169,2026-03-15-01-37-45 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...,92
137,2026-03-15-10-00-00 +0000,latimes,Trump is searching for an endgame to the Iran war,https://www.latimes.com/politics/story/2026-03...,81
3,2026-03-15-22-51-19 +0000,nyt,Iran War Live Updates: ‘No Guarantees’ Oil Pri...,https://www.nytimes.com/live/2026/03/15/world/...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
73,97,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...
35,43,2026-03-15-21-09-33 +0000,cbc,Israel says Michigan synagogue attacker was br...,https://www.cbc.ca/news/world/michigan-synagog...
86,42,2026-03-15-17-06-25 +0000,nypost,Captain of Iranian women’s soccer team is late...,https://nypost.com/2026/03/15/world-news/capta...
112,31,2026-03-15-14-19-14 +0000,nypost,Americans will feel pain of high gas prices fo...,https://nypost.com/2026/03/15/us-news/oil-pric...
113,28,2026-03-15-14-12-56 +0000,nypost,Maine Dem Senate hopeful Graham Platner done a...,https://nypost.com/2026/03/15/us-news/maine-de...
186,28,2026-03-15-00-00-00 +0000,wsj,The AI boom has sparked a frenzied real-estate...,https://www.wsj.com/economy/housing/san-franci...
37,27,2026-03-15-20-58-20 +0000,nypost,Disney chief behind Star Wars games drops expl...,https://nypost.com/2026/03/15/us-news/jay-ong-...
129,27,2026-03-15-10-38-22 +0000,bbc,Israeli forces kill Palestinian couple and two...,https://www.bbc.com/news/articles/cqxdndz75zvo...
177,27,2026-03-15-00-42-18 +0000,bbc,An eccentric new friend entered her life. Then...,https://www.bbc.com/news/articles/c5yvpl9jlpeo...
23,24,2026-03-15-21-44-08 +0000,nypost,Another ski resort closes early as heat wave c...,https://nypost.com/2026/03/15/us-news/another-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)