## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-09-33-02 +0000,nypost,Seattle beer garden employee found dead as sus...,https://nypost.com/2026/05/13/us-news/seattle-...
1,2026-05-13-09-30-40 +0000,bbc,Wes Streeting: Ambitious minister at centre of...,https://www.bbc.com/news/articles/c172w9pvw44o...
2,2026-05-13-09-30-00 +0000,nypost,Divorcée accused of blackmailing billionaire B...,https://nypost.com/2026/05/13/us-news/wesley-e...
3,2026-05-13-09-30-00 +0000,wsj,A Spending Splurge by Baltimore City Hall Is S...,https://www.wsj.com/us-news/a-spending-splurge...
4,2026-05-13-09-30-00 +0000,wsj,"The Boxing Ring Where Fighters Trade Crypto, N...",https://www.wsj.com/finance/the-boxing-ring-wh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2466/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
117       trump     47
216        iran     28
110         war     26
218  hantavirus     16
191       china     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
244,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,135
141,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,121
109,2026-05-13-01-50-00 +0000,wsj,Senior leaders in the White House concluded th...,https://www.wsj.com/politics/policy/inside-mar...,117
60,2026-05-13-07-05-21 +0000,nyt,Here’s How Trump’s Trade War on China Ended Up...,https://www.nytimes.com/2026/05/13/business/tr...,115
166,2026-05-12-22-25-12 +0000,nyt,Trump Says Americans’ Economic Pain Is Not a C...,https://www.nytimes.com/2026/05/12/us/politics...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
244,135,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...
141,74,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
173,71,2026-05-12-22-09-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
115,63,2026-05-13-01-20-35 +0000,nypost,Cindy Burbank — who plans to drop out of gener...,https://nypost.com/2026/05/12/us-news/cindy-bu...
259,58,2026-05-12-18-39-39 +0000,nypost,WHO warns that more hantavirus cases are likel...,https://nypost.com/2026/05/12/world-news/who-s...
292,51,2026-05-12-17-25-14 +0000,nypost,Sam Altman faces heat as he takes witness stan...,https://nypost.com/2026/05/12/business/altman-...
110,48,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
127,48,2026-05-13-00-36-41 +0000,cbc,Sexual violence was 'deliberate tactic' and in...,https://www.cbc.ca/news/world/sexual-violence-...
345,45,2026-05-12-14-18-21 +0000,nyt,UK Bond Yields Rise With Starmer’s Future as P...,https://www.nytimes.com/2026/05/12/business/br...
211,42,2026-05-12-20-47-55 +0000,nypost,Timeline: Eileen Wang’s fall from California m...,https://nypost.com/2026/05/12/us-news/timeline...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)