## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-07-10-49-33 +0000,wapo,A German politician with a MAGA touch lifts hi...,https://www.washingtonpost.com/world/2026/09/0...
1,2026-09-07-10-46-24 +0000,nyt,Germany’s AfD Could Win Its First State Govern...,https://www.nytimes.com/2026/09/06/world/europ...
2,2026-09-07-10-42-50 +0000,nyt,Building Housing Students Collapses in New Del...,https://www.nytimes.com/2026/09/07/world/asia/...
3,2026-09-07-10-41-11 +0000,bbc,"Jaguar Land Rover to cut 4,000 jobs over next ...",https://www.bbc.co.uk/news/articles/c36lx560jj...
4,2026-09-07-10-41-00 +0000,nyt,They Went to Ukraine on the ‘Peace Express.’ D...,https://www.nytimes.com/2026/09/07/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
197  trump     23
18     new     13
106  right     12
39    iran     11
216  miami     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-09-06-19-25-00 +0000,wsj,Trump Envoys Visit Ukraine in New Push for Pea...,https://www.wsj.com/world/europe/trump-envoys-...,73
146,2026-09-06-19-46-40 +0000,cbc,At least 5 dead after Amazon cargo plane barre...,https://www.cbc.ca/news/world/amazon-cargo-pla...,63
160,2026-09-06-17-34-57 +0000,cbc,Far-right AfD wins German state election but f...,https://www.cbc.ca/news/world/afd-germany-elec...,59
15,2026-09-07-10-14-51 +0000,bbc,Germany's far-right AfD says 'democracy demand...,https://www.bbc.co.uk/news/articles/cpd0113082...,58
144,2026-09-06-20-08-57 +0000,nypost,Trump posts map that renames New Mexico ‘New A...,https://nypost.com/2026/09/06/us-news/trump-po...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,73,2026-09-06-19-25-00 +0000,wsj,Trump Envoys Visit Ukraine in New Push for Pea...,https://www.wsj.com/world/europe/trump-envoys-...
146,63,2026-09-06-19-46-40 +0000,cbc,At least 5 dead after Amazon cargo plane barre...,https://www.cbc.ca/news/world/amazon-cargo-pla...
160,59,2026-09-06-17-34-57 +0000,cbc,Far-right AfD wins German state election but f...,https://www.cbc.ca/news/world/afd-germany-elec...
161,39,2026-09-06-17-24-41 +0000,nyt,OPEC Plus Holds Oil Production Steady as U.S.-...,https://www.nytimes.com/2026/09/06/business/op...
60,33,2026-09-07-08-46-42 +0000,nypost,North Korea and Russia open their first road b...,https://nypost.com/2026/09/07/world-news/north...
159,31,2026-09-06-17-44-24 +0000,nypost,Trump asks Supreme Court to allow mail-in ball...,https://nypost.com/2026/09/06/us-news/trump-re...
19,29,2026-09-07-10-00-00 +0000,nypost,Former Missouri high school valedictorian bust...,https://nypost.com/2026/09/07/us-news/former-u...
143,29,2026-09-06-20-35-26 +0000,nypost,‘Vampire’ so feared she was locked in booby-tr...,https://nypost.com/2026/09/06/world-news/vampi...
181,26,2026-09-06-15-17-00 +0000,wsj,As President Trump’s approval rating hovers ne...,https://www.wsj.com/politics/in-trumps-second-...
174,26,2026-09-06-15-56-00 +0000,wsj,Retail investors hand control of stock portfol...,https://www.wsj.com/politics/policy/retail-inv...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)