## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-12-15-10-12 +0000,nyt,Iran War Live Updates: New Supreme Leader Issu...,https://www.nytimes.com/live/2026/03/12/world/...
1,2026-03-12-15-09-41 +0000,nyt,"James Clyburn to Run for House Again, Defying ...",https://www.nytimes.com/2026/03/12/us/politics...
2,2026-03-12-15-06-46 +0000,nyt,Here is the latest.,https://www.nytimes.com/live/2026/03/12/world/...
3,2026-03-12-15-04-00 +0000,wsj,The AI Trade That’s Separating Wall Street’s W...,https://www.wsj.com/finance/investing/the-ai-t...
4,2026-03-12-15-03-58 +0000,nypost,Horrific video shows moment alleged bully fata...,https://nypost.com/2026/03/12/us-news/video-sh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2624/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     60
1       war     42
210   trump     40
14      oil     37
58   prices     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-12-15-10-12 +0000,nyt,Iran War Live Updates: New Supreme Leader Issu...,https://www.nytimes.com/live/2026/03/12/world/...,199
217,2026-03-12-01-39-01 +0000,wapo,Nations agree to release oil reserves as war i...,https://www.washingtonpost.com/world/2026/03/1...,175
38,2026-03-12-13-57-56 +0000,bbc,How Iran war laid bare the world's reliance on...,https://www.bbc.com/news/articles/c15x1y8d37vo...,167
313,2026-03-11-20-52-30 +0000,nyt,Iran’s New Supreme Leader Was Wounded Early in...,https://www.nytimes.com/2026/03/11/world/middl...,159
373,2026-03-11-16-53-31 +0000,nypost,"Dow sinks 300 points, oil heads to $90 as Iran...",https://nypost.com/2026/03/11/business/dow-sin...,159

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,199,2026-03-12-15-10-12 +0000,nyt,Iran War Live Updates: New Supreme Leader Issu...,https://www.nytimes.com/live/2026/03/12/world/...
251,99,2026-03-11-23-25-00 +0000,wsj,Trump heaped scorn on longtime GOP nemesis Rep...,https://www.wsj.com/politics/policy/trump-bash...
256,64,2026-03-11-23-14-21 +0000,nyt,World Leaders Will Release 400 Million Barrels...,https://www.nytimes.com/2026/03/11/business/en...
279,54,2026-03-11-22-06-00 +0000,wsj,"Commercial ships near Strait or Hormuz hit, ne...",https://www.wsj.com/politics/policy/commercial...
354,51,2026-03-11-18-23-34 +0000,nypost,Faulty US targeting intel was to blame for str...,https://nypost.com/2026/03/11/us-news/faulty-u...
211,46,2026-03-12-02-38-00 +0000,wsj,"In a matter of hours, the White House changed ...",https://www.wsj.com/business/energy-oil/presid...
53,42,2026-03-12-13-19-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
45,41,2026-03-12-13-39-00 +0000,wsj,"The U.S. trade deficit declined in January, co...",https://www.wsj.com/economy/trade/u-s-trade-de...
235,41,2026-03-12-00-28-08 +0000,nypost,Two oil tankers explode – leaving at least 1 p...,https://nypost.com/2026/03/11/world-news/two-o...
62,38,2026-03-12-12-59-09 +0000,nypost,Chaotic video shows car fly across street and ...,https://nypost.com/2026/03/12/us-news/wild-vid...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)