## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-01-06-56-44 +0000,bbc,Kenya aviation workers call off strike that di...,https://www.bbc.co.uk/news/articles/c783x05nnl...
1,2026-09-01-06-50-54 +0000,bbc,"Nepal death toll nears 1,000 as rescuers race ...",https://www.bbc.co.uk/news/articles/c5ylvgq9q7...
2,2026-09-01-06-50-00 +0000,wsj,"Dollar Firms on Rate-Rise Bets, Middle East Wo...",https://www.wsj.com/finance/currencies/asian-c...
3,2026-09-01-06-46-15 +0000,nypost,Bernie Sanders claims some Democrats may want ...,https://nypost.com/2026/09/01/us-news/bernie-s...
4,2026-09-01-06-43-06 +0000,bbc,Zambia's president to be sworn in for second t...,https://www.bbc.co.uk/news/articles/c62m7vp589...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
331   trump     44
183    iran     20
227  murder     18
375     new     17
380      up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
282,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...,140
193,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...,107
192,2026-08-31-20-32-52 +0000,nypost,Supreme Court lets Trump resume White House ba...,https://nypost.com/2026/08/31/us-news/supreme-...,106
260,2026-08-31-17-50-29 +0000,wapo,Trump vows to hit Iran hard as strikes and eco...,https://www.washingtonpost.com/world/2026/08/3...,105
333,2026-08-31-12-28-07 +0000,nypost,Trump calls for leaders of ‘failed nation’ Ira...,https://nypost.com/2026/08/31/world-news/trump...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
282,140,2026-08-31-16-31-00 +0000,wsj,President Trump said that communities that don...,https://www.wsj.com/politics/policy/trump-says...
138,69,2026-08-31-22-21-16 +0000,latimes,Ex-Compton gang leader found guilty in murder ...,https://www.latimes.com/california/story/2026-...
193,63,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...
317,63,2026-08-31-13-59-16 +0000,nypost,Oil prices jump 3% to over $90 after US-Iran e...,https://nypost.com/2026/08/31/business/oil-pri...
188,63,2026-08-31-20-47-38 +0000,bbc,Two dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
53,58,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...
174,57,2026-08-31-21-02-43 +0000,nypost,Vance attacks ‘very evil’ Abdul el-Sayed at Mi...,https://nypost.com/2026/08/31/us-news/jd-vance...
296,55,2026-08-31-15-24-45 +0000,chitri,Kalshi bans ex-Congressman George Santos for l...,https://www.chicagotribune.com/2026/08/31/kals...
257,51,2026-08-31-18-00-16 +0000,cbc,"America 'not at war' with Canada, insists U.S....",https://www.cbc.ca/news/politics/bessent-carne...
123,50,2026-08-31-22-47-20 +0000,wapo,17-year-old girl charged with murder in livest...,https://www.washingtonpost.com/nation/2026/08/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)