## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-14-14-54-14 +0000,nypost,Witness reveals horrifying new details of McLa...,https://nypost.com/2026/09/14/us-news/new-info...
1,2026-09-14-14-52-25 +0000,nypost,Paramount’s threat to flee California could co...,https://nypost.com/2026/09/14/business/paramou...
2,2026-09-14-14-50-21 +0000,nyt,Tech Stocks Tumble After AI Leaders Call for I...,https://www.nytimes.com/2026/09/14/business/te...
3,2026-09-14-14-50-02 +0000,startribune,"Trump dismisses new AI guardrails, says there ...",https://www.startribune.com/trump-dismisses-ne...
4,2026-09-14-14-49-12 +0000,nyt,Trump Administration Moves to Integrate A.I. I...,https://www.nytimes.com/2026/09/14/health/ai-d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
33     trump     40
29        ai     23
3        new     15
287       up     13
239  ukraine     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
25,2026-09-14-14-18-53 +0000,chitri,President Donald Trump dismisses new AI guardr...,https://www.chicagotribune.com/2026/09/14/dona...,139
3,2026-09-14-14-50-02 +0000,startribune,"Trump dismisses new AI guardrails, says there ...",https://www.startribune.com/trump-dismisses-ne...,123
250,2026-09-13-18-13-12 +0000,chitri,President Donald Trump downplays the need to c...,https://www.chicagotribune.com/2026/09/13/trum...,114
210,2026-09-13-22-02-00 +0000,wsj,President Trump defended the administration’s ...,https://www.wsj.com/tech/ai/trump-defends-whit...,105
225,2026-09-13-20-25-00 +0000,wsj,President Trump made a surprise trade announce...,https://www.wsj.com/economy/trade/trump-pledge...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
25,139,2026-09-14-14-18-53 +0000,chitri,President Donald Trump dismisses new AI guardr...,https://www.chicagotribune.com/2026/09/14/dona...
217,70,2026-09-13-21-30-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
95,68,2026-09-14-11-04-00 +0000,wsj,"The price of gasoline—and, by proxy, the Iran ...",https://www.wsj.com/politics/policy/with-50-da...
229,47,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...
111,47,2026-09-14-10-14-31 +0000,nypost,Russian drone hits train near Ukraine-Poland b...,https://nypost.com/2026/09/14/world-news/russi...
40,40,2026-09-14-13-41-00 +0000,wsj,Oil Prices Rise as Saudi East-West Pipeline At...,https://www.wsj.com/business/energy-oil/oil-pr...
131,37,2026-09-14-09-10-00 +0000,wsj,"U.S. Treasury Yields Edge Lower, German 10-Yea...",https://www.wsj.com/economy/central-banking/u-...
226,35,2026-09-13-20-23-48 +0000,nyt,King Charles Will Convene A.I. Leaders Amid Ca...,https://www.nytimes.com/2026/09/13/world/europ...
0,35,2026-09-14-14-54-14 +0000,nypost,Witness reveals horrifying new details of McLa...,https://nypost.com/2026/09/14/us-news/new-info...
211,31,2026-09-13-21-53-33 +0000,nypost,Hardline Iran faction launched attack to derai...,https://nypost.com/2026/09/13/world-news/hardl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)