## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-14-43-03 +0000,nypost,Plane crashes into Beijing’s tallest skyscrape...,https://nypost.com/2026/06/26/world-news/plane...
1,2026-06-26-14-42-53 +0000,nyt,Small Plane Crashes Into Tallest Building in B...,https://www.nytimes.com/2026/06/26/world/asia/...
2,2026-06-26-14-42-07 +0000,nyt,Venezuela Live Updates: Death Toll Rises to 58...,https://www.nytimes.com/live/2026/06/26/world/...
3,2026-06-26-14-39-37 +0000,nypost,"Bikini-clad Kentucky teen, 19, vanishes from b...",https://nypost.com/2026/06/26/us-news/bikini-c...
4,2026-06-26-14-32-00 +0000,wsj,Consumer Sentiment Improves in June as Gasolin...,https://www.wsj.com/economy/consumers/consumer...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2578/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
40       trump     30
183        new     23
10   venezuela     20
219       iran     19
194      court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
314,2026-06-25-18-17-35 +0000,wapo,Rubio’s new job? Selling Trump’s Iran deal to ...,https://www.washingtonpost.com/national-securi...,88
374,2026-06-25-14-49-39 +0000,latimes,"Trump may end legal protection for 350,000 Hai...",https://www.latimes.com/politics/story/2026-06...,85
25,2026-06-26-14-00-00 +0000,wsj,Bayer Gets New Life After Supreme Court’s Roun...,https://www.wsj.com/business/bayer-gets-new-li...,85
231,2026-06-25-22-10-20 +0000,nyt,Supreme Court Expands Trump’s Power Over Immig...,https://www.nytimes.com/2026/06/25/us/politics...,85
205,2026-06-25-23-40-00 +0000,wsj,"Iran Attacks Cargo Ship, Testing Trump’s Deal ...",https://www.wsj.com/world/middle-east/iran-att...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
314,88,2026-06-25-18-17-35 +0000,wapo,Rubio’s new job? Selling Trump’s Iran deal to ...,https://www.washingtonpost.com/national-securi...
183,78,2026-06-26-01-08-00 +0000,wsj,California’s proposed billionaire tax will app...,https://www.wsj.com/politics/policy/california...
76,63,2026-06-26-11-25-52 +0000,nypost,Neighbors dig through Venezuela rubble in desp...,https://nypost.com/2026/06/26/world-news/neigh...
25,62,2026-06-26-14-00-00 +0000,wsj,Bayer Gets New Life After Supreme Court’s Roun...,https://www.wsj.com/business/bayer-gets-new-li...
273,51,2026-06-25-20-27-32 +0000,nyt,Oil Prices Jump After Attack Halts Shipping in...,https://www.nytimes.com/2026/06/25/business/oi...
100,45,2026-06-26-10-16-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
279,43,2026-06-25-20-10-00 +0000,wsj,New York Fed President John Williams said the ...,https://www.wsj.com/economy/central-banking/fe...
268,38,2026-06-25-20-56-00 +0000,wsj,The Florida immigration-detention center known...,https://www.wsj.com/politics/policy/floridas-a...
75,37,2026-06-26-11-27-09 +0000,nypost,Kim Jong Un demands ‘destructive’ military pos...,https://nypost.com/2026/06/26/world-news/kim-j...
46,36,2026-06-26-13-14-07 +0000,nyt,Iran’s Long World Cup Journey Defined by War a...,https://www.nytimes.com/2026/06/26/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)