## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-14-54-22 +0000,bbc,Hezbollah rejects renewed ceasefire agreed by ...,https://www.bbc.com/news/articles/c052343r812o...
1,2026-06-04-14-53-21 +0000,nypost,Jury selection in Karmelo Anthony murder case ...,https://nypost.com/2026/06/04/us-news/jury-sel...
2,2026-06-04-14-52-52 +0000,bbc,NHS staff should be banned from wearing politi...,https://www.bbc.com/news/articles/cn0plkd4wdno...
3,2026-06-04-14-52-03 +0000,bbc,PM vows to speed up housebuilding projects,https://www.bbc.com/news/videos/c87q7g4r4p7o?a...
4,2026-06-04-14-51-19 +0000,bbc,Hinge boss on her green and red flags in life,https://www.bbc.com/news/videos/c98r8y410d4o?a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2533/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
54   trump     43
78    iran     25
172    new     21
31      up     15
167    war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
249,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,120
254,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...,118
243,2026-06-03-22-07-07 +0000,nypost,House defies Trump and passes war powers resol...,https://nypost.com/2026/06/03/us-news/house-de...,118
24,2026-06-04-14-20-09 +0000,nyt,Iran War Live Updates: Israel Trades Strikes W...,https://www.nytimes.com/live/2026/06/04/world/...,113
193,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
249,120,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...
254,75,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
222,57,2026-06-03-23-23-38 +0000,nypost,NATO chief warns young Russians against signin...,https://nypost.com/2026/06/03/world-news/nato-...
24,53,2026-06-04-14-20-09 +0000,nyt,Iran War Live Updates: Israel Trades Strikes W...,https://www.nytimes.com/live/2026/06/04/world/...
357,52,2026-06-03-15-32-30 +0000,bbc,Ex-UK political aide and Biden cabinet secreta...,https://www.bbc.com/news/articles/cn8p0yz512no...
200,44,2026-06-04-01-00-00 +0000,wsj,"Amaryllis Fox Kennedy, a former Trump administ...",https://www.wsj.com/politics/national-security...
269,43,2026-06-03-20-58-49 +0000,nypost,Ebola fears prompt Spanish city to cancel Cong...,https://nypost.com/2026/06/03/sports/ebola-fea...
295,43,2026-06-03-20-05-58 +0000,bbc,One killed and dozens injured in Iranian drone...,https://www.bbc.com/news/articles/c5yx135yg53o...
250,42,2026-06-03-21-43-00 +0000,wsj,Some GOP lawmakers are pushing to kill the adm...,https://www.wsj.com/politics/policy/fight-to-k...
23,40,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)