## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-16-10-00 +0000,wsj,Opinion | Justice Kagan Stands Up for the Court,https://www.wsj.com/opinion/elena-kagan-suprem...
1,2026-07-25-16-09-11 +0000,nyt,Live Updates: Hundreds of Thousands Flee as Fi...,https://www.nytimes.com/live/2026/07/25/world/...
2,2026-07-25-16-08-26 +0000,chitri,How do you run for reelection in a messy Congr...,https://www.chicagotribune.com/2026/07/25/mess...
3,2026-07-25-16-08-18 +0000,nyt,Troy Jackson Picked to Replace Platner as Demo...,https://www.nytimes.com/2026/07/25/us/politics...
4,2026-07-25-16-08-00 +0000,wsj,Suspect in Manhattan Stabbings Faces Hate-Crim...,https://www.wsj.com/us-news/suspect-in-upper-w...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
56    trump     38
51     iran     27
47      new     26
52      war     13
62  tariffs     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
195,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,108
7,2026-07-25-16-02-49 +0000,nyt,"Iran War Live Updates: U.S. Strikes Abate, Eve...",https://www.nytimes.com/live/2026/07/25/world/...,97
189,2026-07-24-21-41-12 +0000,nyt,Trump Meets With Top Advisers as He Weighs a M...,https://www.nytimes.com/2026/07/24/us/politics...,94
273,2026-07-24-17-29-56 +0000,nyt,Iran War and Trump’s Tariffs Threaten a Resili...,https://www.nytimes.com/2026/07/24/business/ir...,94
136,2026-07-25-00-59-00 +0000,wsj,A Democratic Party panel selected South Caroli...,https://www.wsj.com/politics/elections/democra...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
195,108,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...
9,63,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...
187,56,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
272,41,2026-07-24-17-30-54 +0000,nypost,"Miami dethrones NYC, Bay Area as America’s hot...",https://nypost.com/2026/07/24/business/miami-d...
283,38,2026-07-24-16-45-34 +0000,cbc,Deadly clash near West Bank village kills 4 Pa...,https://www.cbc.ca/news/world/israel-west-bank...
265,37,2026-07-24-17-47-49 +0000,nypost,Democrats pick South Carolina for first primar...,https://nypost.com/2026/07/24/us-news/south-ca...
16,35,2026-07-25-15-33-08 +0000,wapo,Houthis claim attack on Saudi oil refinery as ...,https://www.washingtonpost.com/world/2026/07/2...
59,34,2026-07-25-12-30-22 +0000,cbc,Tour de France final stage shortened to redepl...,https://www.cbc.ca/news/world/wildfire-evacuat...
209,34,2026-07-24-20-49-00 +0000,wsj,The U.S. will consider applying additional tar...,https://www.wsj.com/economy/trade/trump-threat...
134,31,2026-07-25-01-04-17 +0000,latimes,Street homelessness went up in Los Angeles. In...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)