## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-16-17-24 +0000,nypost,UK teen jailed for gun threat over wrong sauce...,https://nypost.com/2026/04/09/world-news/uk-te...
1,2026-04-09-16-14-13 +0000,nyt,"On Social Media, Democratic Politicians Are Le...",https://www.nytimes.com/2026/04/09/us/politics...
2,2026-04-09-16-13-21 +0000,cbc,Canada pushing for Lebanon inclusion into ceas...,https://www.cbc.ca/news/politics/cbc-ca-politi...
3,2026-04-09-16-12-56 +0000,nyt,Iran War Live Updates: Europe Presses for Broa...,https://www.nytimes.com/live/2026/04/09/world/...
4,2026-04-09-16-12-42 +0000,wapo,"In Texas, a state hearing on social studies be...",https://www.washingtonpost.com/nation/2026/04/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
23    iran     80
31    fire     42
30   cease     38
106  trump     31
24     war     30

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...,236
3,2026-04-09-16-12-56 +0000,nyt,Iran War Live Updates: Europe Presses for Broa...,https://www.nytimes.com/live/2026/04/09/world/...,232
124,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,218
374,2026-04-08-16-56-31 +0000,nypost,Iran blocks ships in the Strait of Hormuz with...,https://nypost.com/2026/04/08/world-news/iran-...,217
319,2026-04-08-20-03-41 +0000,nyt,"Even as They Praise Iran Cease-Fire, World Lea...",https://www.nytimes.com/2026/04/08/world/europ...,214

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,236,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...
342,76,2026-04-08-18-55-05 +0000,cbc,"Despite ceasefire with Iran, Israel's aggressi...",https://www.cbc.ca/news/lebanon-israel-attacks...
18,64,2026-04-09-16-00-00 +0000,wsj,Iran is demanding that oil tankers passing thr...,https://www.wsj.com/finance/currencies/iran-cr...
92,53,2026-04-09-13-10-00 +0000,wsj,Fed’s Preferred Inflation Metric Was Stubborn ...,https://www.wsj.com/economy/central-banking/fe...
338,50,2026-04-08-19-14-54 +0000,nypost,Woke Gavin Newsom ‘green’ jet fuel plan could ...,https://nypost.com/2026/04/08/lifestyle/gavin-...
247,43,2026-04-08-23-37-00 +0000,wsj,A federal appeals court has denied Anthropic’s...,https://www.wsj.com/politics/national-security...
98,39,2026-04-09-12-59-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
217,37,2026-04-09-02-55-05 +0000,nypost,Former top Biden aide urges Va. Gov. Abigail S...,https://nypost.com/2026/04/08/us-news/former-t...
76,37,2026-04-09-13-54-13 +0000,cbc,K-pop supergroup BTS kick off world tour in So...,https://www.cbc.ca/news/entertainment/bts-worl...
36,34,2026-04-09-15-37-15 +0000,nypost,Wild video shows quadruple amputee cornhole pr...,https://nypost.com/2026/04/09/us-news/wild-vid...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)