## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-11-01-11-00 +0000,wsj,Hollywood’s Horror-Meme Gold Rush Is Minting M...,https://www.wsj.com/business/media/hollywoods-...
1,2026-07-11-01-05-47 +0000,nypost,Tiger rescued from ‘worst roadside zoo in Amer...,https://nypost.com/2026/07/10/us-news/oakland-...
2,2026-07-11-01-00-54 +0000,nyt,Trump Tried to Block Canada’s New Bridge to De...,https://www.nytimes.com/2026/07/10/world/canad...
3,2026-07-11-01-00-05 +0000,nyt,Graham Platner Files Paperwork to Withdraw Fro...,https://www.nytimes.com/2026/07/10/us/politics...
4,2026-07-11-01-00-00 +0000,wsj,The War in Ukraine Is Shifting Against Putin b...,https://www.wsj.com/world/russia/the-war-in-uk...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2472/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
16   trump     35
14     new     23
308   iran     19
52      up     16
162   will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...,128
134,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...,112
230,2026-07-10-14-25-14 +0000,nypost,Trump tells The Post he’s ‘left instructions’ ...,https://nypost.com/2026/07/10/us-news/trump-te...,96
112,2026-07-10-20-27-02 +0000,nypost,Oil giants to gain ‘billions’ from Iran war — ...,https://nypost.com/2026/07/10/business/oil-gia...,93
213,2026-07-10-15-16-05 +0000,nyt,Trump Says Negotiations With Iran Will Continu...,https://www.nytimes.com/2026/07/10/us/politics...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,128,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...
134,62,2026-07-10-18-59-00 +0000,wsj,A lack of defensive capabilities aboard Trump’...,https://www.wsj.com/politics/national-security...
230,54,2026-07-10-14-25-14 +0000,nypost,Trump tells The Post he’s ‘left instructions’ ...,https://nypost.com/2026/07/10/us-news/trump-te...
15,47,2026-07-11-00-17-15 +0000,bbc,'Devastating' evidence against Charlie Kirk mu...,https://www.bbc.co.uk/news/articles/c4gy12gqzp...
125,40,2026-07-10-19-35-02 +0000,latimes,Gunman in deadly California high school gradua...,https://www.latimes.com/california/story/2026-...
209,39,2026-07-10-15-27-46 +0000,nyt,Gaza Aid Worker on His Way to Watch World Cup ...,https://www.nytimes.com/2026/07/09/world/middl...
319,38,2026-07-10-08-59-00 +0000,wsj,SK Hynix to Debut on Wall Street After Biggest...,https://www.wsj.com/tech/sk-hynix-raises-26-51...
97,38,2026-07-10-21-00-23 +0000,nypost,Accused rapist Graham Platner formally withdra...,https://nypost.com/2026/07/10/us-news/accused-...
7,37,2026-07-11-00-38-00 +0000,wsj,"The New York Times countersued the EEOC, claim...",https://www.wsj.com/business/media/new-york-ti...
329,35,2026-07-10-06-44-21 +0000,bbc,"China lands reusable rocket for first time, st...",https://www.bbc.co.uk/news/articles/cm2rmmx86p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)