## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-11-11-56-09 +0000,nyt,Live Updates: At Least 3 Ships Come Under Atta...,https://www.nytimes.com/live/2026/03/11/world/...
1,2026-03-11-11-53-46 +0000,wapo,Cargo ships hit in Persian Gulf shipping lane ...,https://www.washingtonpost.com/world/2026/03/1...
2,2026-03-11-11-51-54 +0000,nyt,Why Did the UK Police Repeatedly Decline to In...,https://www.nytimes.com/2026/03/11/world/europ...
3,2026-03-11-11-49-00 +0000,wsj,Sterling at Risk of Downward Correction,https://www.wsj.com/finance/currencies/asian-c...
4,2026-03-11-11-43-00 +0000,wsj,Campbell’s Cuts Outlook as Snack Sales Fall,https://www.wsj.com/business/retail/campbells-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
62      iran     65
63       war     47
9        oil     34
86     trump     29
251  iranian     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
152,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...,224
8,2026-03-11-11-36-18 +0000,nypost,IEA to recommend release of record 400M oil ba...,https://nypost.com/2026/03/11/world-news/iea-t...,183
244,2026-03-10-20-23-00 +0000,wsj,"As Iran War Pushes Up Oil Prices, Putin Can Ba...",https://www.wsj.com/world/russia/as-iran-war-p...,176
167,2026-03-11-01-00-00 +0000,wsj,Trump’s suggestions that the war with Iran mig...,https://www.wsj.com/world/middle-east/trump-sa...,170
151,2026-03-11-02-00-00 +0000,wsj,Iran’s Control of Hormuz Means It’s Exporting ...,https://www.wsj.com/world/middle-east/irans-co...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
152,224,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...
24,70,2026-03-11-11-06-57 +0000,nyt,"A Trump-Xi Summit Nears, but China Doesn’t Kno...",https://www.nytimes.com/2026/03/11/world/asia/...
327,50,2026-03-10-16-15-20 +0000,nypost,Iranian women’s soccer player refuses to board...,https://nypost.com/2026/03/10/world-news/irani...
23,47,2026-03-11-11-08-00 +0000,wsj,"Bond Yields Jump as Oil Prices Rise, Middle Ea...",https://www.wsj.com/economy/central-banking/bo...
202,47,2026-03-10-22-24-14 +0000,nypost,GOP gubernatorial hopeful Steve Hilton issues ...,https://nypost.com/2026/03/10/us-news/steve-hi...
105,46,2026-03-11-06-33-00 +0000,wsj,Lego Sales Outpace Global Toy Market to Hit Ne...,https://www.wsj.com/business/earnings/lego-sal...
126,41,2026-03-11-05-09-45 +0000,nypost,Ex-University of Kentucky cheerleader Laken Sn...,https://nypost.com/2026/03/11/us-news/ex-unive...
234,39,2026-03-10-20-44-38 +0000,nyt,Democrats Sued to Find Out Whether Trump Will ...,https://www.nytimes.com/2026/03/10/us/politics...
0,38,2026-03-11-11-56-09 +0000,nyt,Live Updates: At Least 3 Ships Come Under Atta...,https://www.nytimes.com/live/2026/03/11/world/...
270,36,2026-03-10-19-21-10 +0000,latimes,"Florida woman charged with attempted murder, a...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)