## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-22-59-18 +0000,nypost,"Alaska Airlines, FedEx cargo planes narrowly a...",https://nypost.com/2026/03/19/us-news/alaska-a...
1,2026-03-19-22-58-11 +0000,nypost,Upstate NY man pleads guilty to cyberstalking ...,https://nypost.com/2026/03/19/us-news/upstate-...
2,2026-03-19-22-55-32 +0000,nyt,Iran War Live Updates: As Attacks Shake Market...,https://www.nytimes.com/live/2026/03/19/world/...
3,2026-03-19-22-55-31 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/19/world/...
4,2026-03-19-22-54-57 +0000,nyt,Body of Missing University of Alabama Student ...,https://www.nytimes.com/2026/03/19/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
23     iran     61
30    trump     43
24      war     41
101     gas     17
502  prices     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
122,2026-03-19-19-31-21 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...,200
70,2026-03-19-21-11-06 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...,196
89,2026-03-19-20-48-00 +0000,wsj,Trump’s Iran War Frays Ties With Allies as Oil...,https://www.wsj.com/world/trumps-iran-war-fray...,185
2,2026-03-19-22-55-32 +0000,nyt,Iran War Live Updates: As Attacks Shake Market...,https://www.nytimes.com/live/2026/03/19/world/...,172
286,2026-03-19-10-37-36 +0000,bbc,Trump threatens to blow up 'entirety' of majo...,https://www.bbc.com/news/articles/c93j37egjdeo...,168

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
122,200,2026-03-19-19-31-21 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...
305,74,2026-03-19-09-48-00 +0000,wsj,Oil Nears $120 as Key Gulf Energy Hubs Come Un...,https://www.wsj.com/finance/commodities-future...
229,71,2026-03-19-14-26-24 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
369,63,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
328,59,2026-03-19-08-52-13 +0000,nyt,"Gas Prices in Japan Hit Record High, Testing L...",https://www.nytimes.com/2026/03/19/business/ja...
267,54,2026-03-19-12-13-34 +0000,nypost,Barcelona police found missing Alabama student...,https://nypost.com/2026/03/19/world-news/barce...
314,48,2026-03-19-09-20-00 +0000,wsj,Sweden’s Central Bank Holds Key Rate as Middle...,https://www.wsj.com/articles/swedens-central-b...
55,46,2026-03-19-21-33-00 +0000,wsj,"A capital rules win for banks, the $100 millio...",https://www.wsj.com/politics/policy/big-banks-...
206,42,2026-03-19-15-38-16 +0000,bbc,Three Palestinian women killed in beauty salon...,https://www.bbc.com/news/articles/c0ljl23plpzo...
117,38,2026-03-19-19-59-14 +0000,cbc,"Canada, allies say they're ready to help secur...",https://www.cbc.ca/news/world/canada-joint-sta...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)