## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-16-19-17-05 +0000,nyt,Iran War Live Updates: Israel Agrees to 10-Day...,https://www.nytimes.com/live/2026/04/16/world/...
1,2026-04-16-19-13-39 +0000,startribune,Daniel del Prado’s Cardamom will close amid wo...,https://www.startribune.com/rally-for-workers-...
2,2026-04-16-19-13-18 +0000,nypost,Iran has just weeks of oil storage left before...,https://nypost.com/2026/04/16/world-news/iran-...
3,2026-04-16-19-13-00 +0000,wsj,Opinion | The Populism Numbers Game Doesn’t Work,https://www.wsj.com/opinion/the-populism-numbe...
4,2026-04-16-19-07-07 +0000,startribune,Here’s why tornado sirens will blare across Mi...,https://www.startribune.com/heres-why-tornado-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
148    trump     49
0       iran     49
1        war     32
99       new     15
1010  nation     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
334,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...,162
375,2026-04-15-20-07-10 +0000,nyt,Senate Republicans Again Block Bid to Limit Tr...,https://www.nytimes.com/2026/04/15/us/politics...,149
42,2026-04-16-18-26-35 +0000,nypost,House resolution to curtail Trump’s war powers...,https://nypost.com/2026/04/16/us-news/house-re...,147
91,2026-04-16-16-52-03 +0000,nyt,House Again Thwarts Challenge to Trump’s Autho...,https://www.nytimes.com/2026/04/16/us/politics...,144
222,2026-04-16-09-04-25 +0000,nyt,"Jesus Memes, Threats and a War in Iran: A Port...",https://www.nytimes.com/2026/04/16/us/politics...,143

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
334,162,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...
166,61,2026-04-16-13-18-42 +0000,nyt,Live Nation and Ticketmaster Illegally Monopol...,https://www.nytimes.com/2026/04/15/arts/music/...
84,57,2026-04-16-16-59-01 +0000,nypost,Justin Fairfax was a raging drunk who bought g...,https://nypost.com/2026/04/16/us-news/justin-f...
309,50,2026-04-15-23-00-00 +0000,wsj,The Trump administration wants automakers and ...,https://www.wsj.com/politics/national-security...
329,50,2026-04-15-22-03-57 +0000,nypost,Iran using cease-fire to dig out bombed missil...,https://nypost.com/2026/04/15/world-news/iran-...
247,49,2026-04-16-06-42-51 +0000,bbc,"Big energy shock will push up prices, Bank bos...",https://www.bbc.com/news/articles/cn5330l73y2o...
218,47,2026-04-16-09-09-00 +0000,wsj,Rep. Eric Swalwell of California earned endors...,https://www.wsj.com/politics/elections/swalwel...
199,45,2026-04-16-10-30-00 +0000,wsj,"Next Time You Order a Dairy Queen Blizzard, Yo...",https://www.wsj.com/business/hospitality/next-...
227,44,2026-04-16-09-00-00 +0000,wsj,The law doesn’t clearly say what happens when ...,https://www.wsj.com/economy/central-banking/th...
56,43,2026-04-16-18-01-20 +0000,nypost,Germany eyes harsher sick leave rules amid abs...,https://nypost.com/2026/04/16/world-news/germa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)