## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-25-13-08-00 +0000,wsj,U.S. Home Price Growth Rose in June,https://www.wsj.com/economy/housing/u-s-home-p...
1,2026-08-25-13-07-23 +0000,nyt,Many N.F.L. Players Get Brain Disease. Why Has...,https://www.nytimes.com/2026/08/25/us/nfl-cte-...
2,2026-08-25-13-07-00 +0000,wsj,Good Good Golf and Callaway Apologize for ‘Sca...,https://www.wsj.com/cmo-today/good-good-golf-a...
3,2026-08-25-13-06-00 +0000,wsj,10 of the Best Financial Advisor Companies: We...,https://www.wsj.com/buyside/personal-finance/f...
4,2026-08-25-13-06-00 +0000,wsj,Best High-Yield Savings Accounts for August 20...,https://www.wsj.com/buyside/personal-finance/b...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
58    trump     51
82     iran     31
78      new     27
64   canada     23
107   trade     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
298,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,156
137,2026-08-25-03-57-01 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,153
78,2026-08-25-10-00-01 +0000,wapo,Farmers say they face a new crisis as Trump’s ...,https://www.washingtonpost.com/business/2026/0...,142
201,2026-08-24-22-35-00 +0000,wsj,The Supreme Court removed a legal obstacle tha...,https://www.wsj.com/politics/elections/supreme...,139
315,2026-08-24-16-50-00 +0000,wsj,The Trump administration is proposing a new si...,https://www.wsj.com/politics/policy/government...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
298,156,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
309,125,2026-08-24-17-27-14 +0000,nypost,Trump unleashes ‘Operation Economic Outcast’ a...,https://nypost.com/2026/08/24/world-news/trump...
44,81,2026-08-25-11-14-00 +0000,wsj,Michigan’s Abdul El-Sayed will need to win ove...,https://www.wsj.com/politics/elections/four-ta...
178,65,2026-08-24-23-52-00 +0000,wsj,A super PAC aligned with President Trump is op...,https://www.wsj.com/politics/elections/trump-a...
220,55,2026-08-24-21-38-04 +0000,latimes,Supreme Court for now allows Trump to plan new...,https://www.latimes.com/politics/story/2026-08...
50,51,2026-08-25-11-01-38 +0000,nypost,NJ billionaire at center of record-breaking di...,https://nypost.com/2026/08/25/us-news/nj-billi...
16,45,2026-08-25-12-33-40 +0000,nypost,Trump threatens to rename Lake Ontario as ‘Lak...,https://nypost.com/2026/08/25/us-news/trump-th...
152,42,2026-08-25-02-14-00 +0000,wsj,The Trump administration is planning what may ...,https://www.wsj.com/politics/policy/trump-admi...
111,37,2026-08-25-08-19-42 +0000,wsj,"Stock Market Today: Stock Futures Rise, Shrugg...",https://www.wsj.com/livecoverage/stock-market-...
213,37,2026-08-24-21-54-06 +0000,nypost,Iran’s rial currency plunges to record low as ...,https://nypost.com/2026/08/24/world-news/irans...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)