## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-13-45-37 +0000,nyt,Can Trump’s Arch Be So Tall? A Panel May Redef...,https://www.nytimes.com/2026/07/09/us/politics...
1,2026-07-09-13-45-21 +0000,nyt,Live Updates: U.S. and Iran Sink Into Violent ...,https://www.nytimes.com/live/2026/07/09/world/...
2,2026-07-09-13-45-19 +0000,nyt,Final Stage of Ayatollah Ali Khamenei’s Funera...,https://www.nytimes.com/2026/07/09/world/middl...
3,2026-07-09-13-42-07 +0000,nyt,"Trump’s NATO Summit, and Everyone Else’s",https://www.nytimes.com/2026/07/09/world/europ...
4,2026-07-09-13-39-36 +0000,nyt,Clues Behind a Cracker Barrel and in 2 Other S...,https://www.nytimes.com/2026/07/08/us/ohio-col...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2365/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     49
11      iran     41
135  platner     23
140   senate     18
25      nato     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
398,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...,171
181,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...,160
331,2026-07-08-17-27-18 +0000,nypost,"Trump ditches new Air Force One in Turkey, sto...",https://nypost.com/2026/07/08/us-news/trump-wo...,140
172,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...,126
394,2026-07-08-14-32-13 +0000,nypost,"Dow falls 500 points, oil surges after Trump s...",https://nypost.com/2026/07/08/business/dow-fal...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
398,171,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...
181,160,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...
373,57,2026-07-08-15-20-00 +0000,wsj,The IMF trimmed its global growth forecast to ...,https://www.wsj.com/economy/global/imf-drops-r...
289,52,2026-07-08-19-26-00 +0000,wsj,Fed officials weighed rate hikes last month as...,https://www.wsj.com/economy/central-banking/fe...
142,47,2026-07-09-04-16-08 +0000,nypost,Ex-Redlands deputy police chief was California...,https://nypost.com/2026/07/09/us-news/former-r...
52,46,2026-07-09-11-59-18 +0000,cbc,Ukraine claims hits on more Russian fuel tanke...,https://www.cbc.ca/news/world/ukraine-russian-...
250,46,2026-07-08-20-58-21 +0000,bbc,"Justin Bieber joins Madonna, Shakira and BTS f...",https://www.bbc.co.uk/news/articles/c1wyx7g9e1...
400,41,2026-07-08-14-11-00 +0000,wsj,ADP to Launch Monthly Pay Tracking Indicator i...,https://www.wsj.com/economy/jobs/adp-to-launch...
273,41,2026-07-08-19-57-32 +0000,nypost,Here’s why Trump threatened to cut off trade w...,https://nypost.com/2026/07/08/us-news/heres-wh...
133,36,2026-07-09-05-38-45 +0000,nypost,NJ cop in charge of K-9 unit charged after lea...,https://nypost.com/2026/07/09/us-news/nj-cop-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)