## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-11-17-52-58 +0000,nypost,Boy thanks 9/11 victim grandfather he never me...,https://nypost.com/2026/09/11/us-news/boy-than...
1,2026-09-11-17-50-00 +0000,wsj,Canada Pins Hope for Economic Turbocharge on H...,https://www.wsj.com/world/americas/canada-pins...
2,2026-09-11-17-49-34 +0000,nyt,Afghan Woman Deported in First Use of Obscure ...,https://www.nytimes.com/2026/09/11/us/afghan-w...
3,2026-09-11-17-49-28 +0000,wapo,Stubborn inflation leaves GOP with higher pric...,https://www.washingtonpost.com/business/2026/0...
4,2026-09-11-17-49-03 +0000,nypost,‘Call of Duty’ maker hit with explosive sex ha...,https://nypost.com/2026/09/11/business/call-of...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2308/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
49        trump     61
257  convention     31
203          ai     24
256     midterm     21
33          gop     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
265,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...,173
256,2026-09-11-02-51-48 +0000,nypost,Trump leads GOP midterm convention attendees i...,https://nypost.com/2026/09/10/us-news/trump-le...,165
371,2026-09-10-20-26-00 +0000,wsj,President Trump offered a pricey promise in hi...,https://www.wsj.com/politics/policy/5-000-chec...,152
246,2026-09-11-05-02-20 +0000,nypost,JD Vance steals 2028 show at GOP convention — ...,https://nypost.com/2026/09/11/us-news/jd-vance...,148
117,2026-09-11-14-39-39 +0000,nyt,"Inside the Republican Midterm Convention, Wher...",https://www.nytimes.com/2026/09/10/us/politics...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
265,173,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...
272,128,2026-09-11-01-58-47 +0000,nypost,"Protester heckles JD Vance, spices up his GOP ...",https://nypost.com/2026/09/10/us-news/proteste...
267,91,2026-09-11-02-08-00 +0000,wsj,"After years of inaction, Congress is suddenly ...",https://www.wsj.com/politics/policy/congress-i...
114,87,2026-09-11-14-52-00 +0000,wsj,The annual inflation rate stalled out last mon...,https://www.wsj.com/economy/cpi-inflation-repo...
268,80,2026-09-11-02-05-07 +0000,nyt,“When Medicaid programs for homeless or expect...,https://www.nytimes.com/live/2026/09/10/us/tru...
60,60,2026-09-11-16-27-41 +0000,nyt,"Houthis Seize a Key Red Sea Island, Threatenin...",https://www.nytimes.com/2026/09/11/world/middl...
65,58,2026-09-11-16-21-34 +0000,nypost,Iran-backed rebels in Yemen tried using Anthro...,https://nypost.com/2026/09/11/business/iran-ba...
80,55,2026-09-11-16-02-00 +0000,wsj,"GOP Sen. Susan Collins, who faces a tough re-e...",https://www.wsj.com/politics/policy/embattled-...
96,47,2026-09-11-15-36-02 +0000,nypost,Baby dies in hot car after dad leaves him to w...,https://nypost.com/2026/09/11/us-news/baby-die...
306,44,2026-09-10-22-47-00 +0000,wsj,California is cracking down on social-media fe...,https://www.wsj.com/politics/policy/california...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)