## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-04-17-41 +0000,nypost,Cops rush drug-addled zombies in new blitz on ...,https://nypost.com/2026/06/18/us-news/cops-rus...
1,2026-06-18-04-05-53 +0000,nyt,Boyle Heights Warehouse Fire Prompts Thousands...,https://www.nytimes.com/2026/06/17/us/los-ange...
2,2026-06-18-04-01-12 +0000,nyt,"In Southeast Asia, Switching to Solar Offers R...",https://www.nytimes.com/2026/06/18/world/asia/...
3,2026-06-18-04-01-09 +0000,nyt,Why the By-Election in Makerfield Will Have Gi...,https://www.nytimes.com/2026/06/18/world/europ...
4,2026-06-18-03-56-59 +0000,nypost,Schizophrenic woman who fatally stabbed newlyw...,https://nypost.com/2026/06/17/world-news/schiz...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2597/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
85   trump     53
28    iran     42
87    deal     37
285    fed     24
5      new     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
130,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,209
196,2026-06-17-18-41-12 +0000,bbc,Fed holds US interest rates steady as uncertai...,https://www.bbc.com/news/articles/cdjkl78vd7lo...,186
244,2026-06-17-16-31-02 +0000,nypost,Trump says Iran laughed at ‘stupid son of a bi...,https://nypost.com/2026/06/17/us-news/trump-sa...,185
218,2026-06-17-17-44-50 +0000,nypost,Trump jokingly reveals whom he’ll blame if Ira...,https://nypost.com/2026/06/17/us-news/trump-jo...,168
36,2026-06-18-01-48-17 +0000,nyt,Trump’s Deal With Iran Opens New Rifts in G.O.P.,https://www.nytimes.com/2026/06/17/us/politics...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
130,209,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
148,124,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
341,51,2026-06-17-10-00-00 +0000,latimes,He graduated high school with honors. ICE deta...,https://www.latimes.com/california/story/2026-...
266,48,2026-06-17-15-17-08 +0000,nypost,Why Jeff Bezos predicts AI will create labor s...,https://nypost.com/2026/06/17/business/why-jef...
181,46,2026-06-17-19-14-00 +0000,wsj,President Trump tied together fights over poli...,https://www.wsj.com/politics/policy/trump-has-...
267,44,2026-06-17-15-14-55 +0000,nypost,Iranian tankers loaded with oil sail past US N...,https://nypost.com/2026/06/17/world-news/irani...
377,43,2026-06-17-05-12-54 +0000,nyt,The World Cup Gives Kansas City a Rare Turn in...,https://www.nytimes.com/2026/06/17/us/world-cu...
90,38,2026-06-17-22-36-13 +0000,bbc,Japan ramping up defence is 'critical' to prev...,https://www.bbc.com/news/articles/cly8qd4595eo...
229,35,2026-06-17-17-16-11 +0000,nypost,Bungee-jump employee took GoPro camera off stu...,https://nypost.com/2026/06/17/world-news/bunge...
290,33,2026-06-17-13-41-21 +0000,bbc,'It was surreal': British couple describe havi...,https://www.bbc.com/news/articles/c20yzm84r7lo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)