## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-28-12-00-00 +0000,missionlocal,David Lee is the Westside’s forever candidate:...,https://missionlocal.org/2026/05/sf-sunset-dis...
1,2026-05-28-12-00-00 +0000,missionlocal,"After cousin’s killing in Potrero Hill, 20-yea...",https://missionlocal.org/2026/05/cornelius-wig...
2,2026-05-28-11-58-03 +0000,bbc,Jury in Donaldson trial hears victim claim she...,https://www.bbc.com/news/articles/c0q2yxdp45po...
3,2026-05-28-11-57-16 +0000,nyt,Pressure Grows on Spain’s Leader After Police ...,https://www.nytimes.com/2026/05/28/world/europ...
4,2026-05-28-11-54-48 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Str...,https://www.nytimes.com/live/2026/05/28/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
65    trump     41
38     iran     26
304     new     23
711    deal     18
683  canada     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
363,2026-05-27-14-37-09 +0000,cbc,U.S. strikes Iran again after Trump denies rep...,https://www.cbc.ca/news/world/iran-war-day-89-...,116
166,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,106
285,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...,105
175,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,99
306,2026-05-27-17-47-51 +0000,nypost,Trump threatens to ‘blow up’ Oman if it sides ...,https://nypost.com/2026/05/27/us-news/trump-th...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
363,116,2026-05-27-14-37-09 +0000,cbc,U.S. strikes Iran again after Trump denies rep...,https://www.cbc.ca/news/world/iran-war-day-89-...
344,65,2026-05-27-15-52-33 +0000,nypost,New York Times accused of using AI to spy on u...,https://nypost.com/2026/05/27/media/new-york-t...
175,58,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
107,44,2026-05-28-08-00-00 +0000,cbc,Canada mulls legal action against Colombia ove...,https://www.cbc.ca/news/world/canada-colombia-...
262,43,2026-05-27-20-28-26 +0000,nypost,Jill Biden shockingly admits she thought Joe w...,https://nypost.com/2026/05/27/us-news/jill-bid...
227,42,2026-05-27-21-26-15 +0000,nypost,Steve Hilton says California should be world’s...,https://nypost.com/2026/05/27/us-news/steve-hi...
359,39,2026-05-27-15-00-25 +0000,nypost,"New details on 3 women found dead, partially n...",https://nypost.com/2026/05/27/world-news/prose...
72,36,2026-05-28-10-00-00 +0000,latimes,Aerospace company behind Garden Grove chemical...,https://www.latimes.com/business/story/2026-05...
55,35,2026-05-28-10-13-52 +0000,nypost,Truck driver goes off on Delaney Hall anti-ICE...,https://nypost.com/2026/05/28/us-news/truck-dr...
319,34,2026-05-27-17-00-23 +0000,nypost,‘60 Minutes’ journo Sharyn Alfonsi loses CBS N...,https://nypost.com/2026/05/27/media/60-minutes...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)