## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-11-03-31 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
1,2026-03-31-11-02-00 +0000,wsj,Health Care Roundup: Market Talk,https://www.wsj.com/business/health-care-round...
2,2026-03-31-11-01-11 +0000,wapo,Israel mandates death penalty for West Bank Pa...,https://www.washingtonpost.com/world/2026/03/3...
3,2026-03-31-11-00-00 +0000,missionlocal,Meet the people driving trans visibility in Sa...,https://missionlocal.org/2026/03/mission-local...
4,2026-03-31-11-00-00 +0000,wsj,Delta to Tap Amazon Satellite-Internet Service...,https://www.wsj.com/business/airlines/delta-to...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
96    iran     43
178  trump     43
97     war     26
151    oil     24
8      new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
326,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...,154
216,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...,152
88,2026-03-31-07-09-00 +0000,wsj,Oil Ticks Higher After Trump Tells Aides He’s ...,https://www.wsj.com/finance/commodities-future...,130
104,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...,130
44,2026-03-31-09-25-03 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
326,154,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...
303,71,2026-03-30-15-51-00 +0000,wsj,Fed Chair Jerome Powell said the central bank ...,https://www.wsj.com/economy/central-banking/po...
104,57,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
275,54,2026-03-30-17-27-00 +0000,wsj,Air Canada CEO Exit Comes After Language Backl...,https://www.wsj.com/articles/air-canada-ceo-mi...
65,53,2026-03-31-08-50-05 +0000,cbc,U.S. attacks Iranian nuclear site as Tehran st...,https://www.cbc.ca/news/world/iran-u-s-conflic...
121,47,2026-03-31-02-20-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
38,39,2026-03-31-09-39-27 +0000,nypost,Gas prices rise above $4 a gallon for first ti...,https://nypost.com/2026/03/31/business/gas-pri...
129,39,2026-03-31-01-50-03 +0000,nypost,Disturbing video shows man get into police squ...,https://nypost.com/2026/03/30/us-news/video-sh...
25,39,2026-03-31-10-00-00 +0000,nypost,Supreme Court toes ‘glaring red line’ with Tru...,https://nypost.com/2026/03/31/us-news/supreme-...
6,34,2026-03-31-10-57-00 +0000,wsj,TMZ asked people to send in photos of lawmaker...,https://www.wsj.com/politics/tmz-to-vacationin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)