## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-16-22-07-43 +0000,nypost,Popular ice cream brand recalls several flavor...,https://nypost.com/2026/05/16/us-news/straus-f...
1,2026-05-16-22-06-30 +0000,nyt,Kansas Judge Blocks Law Banning Gender-Transit...,https://www.nytimes.com/2026/05/16/us/kansas-t...
2,2026-05-16-22-05-42 +0000,startribune,Hwy. 61 remains closed for several miles as No...,https://www.startribune.com/north-shore-wildfi...
3,2026-05-16-22-00-00 +0000,wsj,Iran’s Seizure of Chinese Security Ship Shows ...,https://www.wsj.com/world/china/irans-seizure-...
4,2026-05-16-21-52-34 +0000,nypost,‘Looksmaxxing’ influencer Clavicular avoids ja...,https://nypost.com/2026/05/16/us-news/looksmax...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2619/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
116   trump     25
112     new     17
135  killed     14
133  leader     12
465   china      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-05-16-21-03-29 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...,75
78,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,75
150,2026-05-16-03-55-42 +0000,nypost,US and Nigerian forces kill top ISIS leader hi...,https://nypost.com/2026/05/15/us-news/us-and-n...,70
13,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...,66
155,2026-05-16-02-06-00 +0000,wsj,With under six months to go before the midterm...,https://www.wsj.com/politics/elections/trump-r...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,75,2026-05-16-21-03-29 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...
167,54,2026-05-16-00-48-07 +0000,nyt,Supreme Court Rejects Virginia Democrats’ Effo...,https://www.nytimes.com/2026/05/15/us/politics...
20,35,2026-05-16-20-53-14 +0000,nypost,Suspected drunk driver mowed down long-time fr...,https://nypost.com/2026/05/16/us-news/suspecte...
155,31,2026-05-16-02-06-00 +0000,wsj,With under six months to go before the midterm...,https://www.wsj.com/politics/elections/trump-r...
70,30,2026-05-16-16-42-27 +0000,nypost,Terror not ruled out as 8 injured after suspec...,https://nypost.com/2026/05/16/world-news/many-...
151,29,2026-05-16-03-07-33 +0000,nypost,"Eric Trump accuses Jen Psaki, MS NOW of airing...",https://nypost.com/2026/05/15/us-news/eric-tru...
91,27,2026-05-16-15-01-40 +0000,bbc,Rescue diver dies during search for bodies of ...,https://www.bbc.com/news/articles/c1w2gv1gdnjo...
39,26,2026-05-16-19-25-21 +0000,nypost,Mamdani’s $124.7B budget cuts a third of NYC P...,https://nypost.com/2026/05/16/us-news/one-thir...
108,26,2026-05-16-12-14-05 +0000,cbc,Israel kills Hamas military wing leader in str...,https://www.cbc.ca/news/world/hamas-chief-gaza...
36,24,2026-05-16-19-33-40 +0000,nypost,Largest inflatable water park in North America...,https://nypost.com/2026/05/16/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)