## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-22-50-48 +0000,nyt,Mideast Fighting: Live Updates: Strikes Launch...,https://www.nytimes.com/live/2026/03/07/world/...
1,2026-03-07-22-49-17 +0000,nyt,Trump Assembles a New Coalition to ‘Eradicate’...,https://www.nytimes.com/2026/03/07/world/ameri...
2,2026-03-07-22-42-30 +0000,nypost,Loyal kitty sacrifices own life to save sleepi...,https://nypost.com/2026/03/07/us-news/loyal-ki...
3,2026-03-07-22-42-11 +0000,nypost,New Jersey woman arrested for fake dentistry a...,https://nypost.com/2026/03/07/us-news/new-jers...
4,2026-03-07-22-33-07 +0000,latimes,Laurel Canyon home burns as Santa Ana winds gu...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2461/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
79      iran     42
12     trump     36
144      war     23
49   iranian      8
14       new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,135
73,2026-03-07-16-55-50 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,118
24,2026-03-07-21-35-38 +0000,wapo,"Trump honors U.S. troops killed in war, says I...",https://www.washingtonpost.com/world/2026/03/0...,115
42,2026-03-07-20-09-24 +0000,nyt,Pakistan Praised Trump. Now It Risks Being Cau...,https://www.nytimes.com/2026/03/07/world/asia/...,112
16,2026-03-07-22-01-30 +0000,nyt,"With Iran, Trump Takes the U.S. to War Without...",https://www.nytimes.com/2026/03/06/us/politics...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,135,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
200,48,2026-03-07-00-32-35 +0000,bbc,AI-generated Iran war videos surge as creators...,https://www.bbc.com/news/articles/ckg8wvz427vo...
72,41,2026-03-07-17-00-00 +0000,wsj,Some Republicans complain Virginia’s most prom...,https://www.wsj.com/politics/elections/virgini...
23,40,2026-03-07-21-37-03 +0000,nypost,Senior Iranian leader issues chilling warning ...,https://nypost.com/2026/03/07/us-news/senior-i...
33,33,2026-03-07-20-48-38 +0000,nypost,California gas prices soar above $5 a gallon —...,https://nypost.com/2026/03/07/us-news/californ...
96,32,2026-03-07-13-45-00 +0000,nypost,‘Tax the Middle-Class?’ Zohran Mamdani’s DSA p...,https://nypost.com/2026/03/07/us-news/tax-the-...
58,31,2026-03-07-19-05-37 +0000,nypost,Israel slams Lebanon with wave of attacks to r...,https://nypost.com/2026/03/07/world-news/israe...
22,28,2026-03-07-21-37-37 +0000,nypost,Russian missile attack on apartment building k...,https://nypost.com/2026/03/07/world-news/russi...
115,27,2026-03-07-11-37-43 +0000,nypost,Trump claims Iran will be hit ‘very hard’ toda...,https://nypost.com/2026/03/07/us-news/trump-wa...
46,26,2026-03-07-19-55-32 +0000,nypost,Trump vows US military power toward eradicatin...,https://nypost.com/2026/03/07/us-news/trump-co...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)