## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-12-19-50-08 +0000,nypost,Bill Maher rips media for weak stance on ‘terr...,https://nypost.com/2026/09/12/us-news/bill-mah...
1,2026-09-12-19-41-51 +0000,nypost,"Shocking video shows wrong-way BMW racing off,...",https://nypost.com/2026/09/12/us-news/shocking...
2,2026-09-12-19-40-00 +0000,wsj,J&J Is In Talks to Sell Its Hips-and-Knees Bus...,https://www.wsj.com/business/deals/j-j-is-in-t...
3,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
4,2026-09-12-19-36-50 +0000,bbc,Fire at nursing home in Chile kills 16 residents,https://www.bbc.co.uk/news/articles/cy4zpp20w7...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
30   trump     32
70      ai     11
132    oil     11
202    war     10
164   iran      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
205,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...,83
88,2026-09-12-12-19-58 +0000,nypost,Trump claims Iran-backed Houthis don’t want to...,https://nypost.com/2026/09/12/us-news/trump-op...,75
3,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,75
196,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...,70
129,2026-09-12-08-19-29 +0000,nypost,Trump arrives in Ireland to meet leaders befor...,https://nypost.com/2026/09/12/world-news/trump...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
205,83,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...
175,54,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...
196,50,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...
179,45,2026-09-11-23-15-00 +0000,wsj,New Jersey Gov. Mikie Sherrill is facing the s...,https://www.wsj.com/politics/misconduct-inquir...
185,40,2026-09-11-22-52-05 +0000,missionlocal,Meet the S.F. school board candidates: Do you ...,https://missionlocal.org/2026/09/san-francisco...
3,35,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
210,35,2026-09-11-21-06-00 +0000,wsj,America marks a quarter-century since the Sept...,https://www.wsj.com/us-news/a-nation-remembers...
72,32,2026-09-12-14-26-02 +0000,nypost,Canada trade war jeopardizing key Senate battl...,https://nypost.com/2026/09/12/us-news/canada-t...
149,26,2026-09-12-02-52-51 +0000,latimes,Union leader behind billionaire tax measure al...,https://www.latimes.com/california/story/2026-...
7,25,2026-09-12-19-30-09 +0000,nypost,AI CEOs demand industry ‘slow the pace’ of adv...,https://nypost.com/2026/09/12/us-news/ai-ceos-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)