## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-25-07-08-05 +0000,bbc,UK inflation rate remained at 3% in February,https://www.bbc.com/news/articles/cx2w47e9v2vo...
1,2026-03-25-07-08-00 +0000,wsj,"U.S. Treasury Yields Fall on Lower Oil Prices,...",https://www.wsj.com/finance/investing/jgb-futu...
2,2026-03-25-07-07-04 +0000,nyt,San Francisco Killed 8th-Grade Algebra. Now It...,https://www.nytimes.com/2026/03/24/us/san-fran...
3,2026-03-25-07-00-05 +0000,nyt,Write It Up! How Fast Do Our Journalists Type?,https://www.nytimes.com/2026/03/25/insider/how...
4,2026-03-25-06-52-50 +0000,nypost,Washington state boyfriend accused of murderin...,https://nypost.com/2026/03/25/us-news/washingt...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
69    iran     46
65   trump     37
675    war     24
8      oil     18
221    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
187,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,143
122,2026-03-24-22-35-03 +0000,nypost,US sends 15-point plan to end war with Iran as...,https://nypost.com/2026/03/24/world-news/us-se...,136
20,2026-03-25-05-12-54 +0000,bbc,Oil price falls as Trump talks up Iran peace n...,https://www.bbc.com/news/articles/c995xp4jxj2o...,131
270,2026-03-24-16-40-35 +0000,nypost,$580M oil trades made minutes before Trump’s k...,https://nypost.com/2026/03/24/business/580m-oi...,125
85,2026-03-25-00-31-18 +0000,bbc,Oil traders bet millions minutes before Trump'...,https://www.bbc.com/news/articles/cg547ljepvzo...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
187,143,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...
311,78,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
168,54,2026-03-24-21-07-31 +0000,nyt,United States Said to Have Sent Iran a Plan to...,https://www.nytimes.com/2026/03/24/world/middl...
201,47,2026-03-24-20-06-31 +0000,startribune,Twin Cities TSA agents talk about working with...,https://www.startribune.com/why-no-long-lines-...
228,45,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
101,45,2026-03-24-23-33-00 +0000,wsj,The Defense Department introduced new restrict...,https://www.wsj.com/politics/national-security...
51,42,2026-03-25-02-40-23 +0000,nypost,Texas elementary school ‘dads club’ gifts Jeep...,https://nypost.com/2026/03/24/us-news/texas-el...
110,39,2026-03-24-23-14-38 +0000,cbc,Air Canada CEO summoned to Ottawa over English...,https://www.cbc.ca/news/canada/air-canada-ceo-...
317,36,2026-03-24-14-18-17 +0000,nypost,Chilling footage shows skydiver grinning for j...,https://nypost.com/2026/03/24/world-news/foota...
309,36,2026-03-24-14-44-28 +0000,nypost,UK will lead ‘Hormuz Coalition’ to reopen stra...,https://nypost.com/2026/03/24/world-news/iran-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)