## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-14-18-45 +0000,nypost,St Michael statue blocked from Massachusetts c...,https://nypost.com/2026/07/19/us-news/st-micha...
1,2026-07-19-14-14-31 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...
2,2026-07-19-14-13-19 +0000,nypost,Liam Payne pal finally off the hook for star’s...,https://nypost.com/2026/07/19/entertainment/li...
3,2026-07-19-14-09-25 +0000,chitri,Iran hits US allies as Israel warns missiles h...,https://www.chicagotribune.com/2026/07/19/iran...
4,2026-07-19-14-07-55 +0000,nyt,The ‘Bad Blood’ Between Polymarket’s Shayne Co...,https://www.nytimes.com/2026/07/19/technology/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2627/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
11     iran     19
52    world     17
89    trump     16
105     cup     14
20   killed     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-07-19-14-14-31 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...,83
128,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...,77
12,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...,73
85,2026-07-19-04-53-22 +0000,nypost,Spanish legend Joan Capdevila will be allowed ...,https://nypost.com/2026/07/19/us-news/spanish-...,72
127,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,83,2026-07-19-14-14-31 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...
12,73,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...
63,45,2026-07-19-09-12-35 +0000,nypost,"US blitzes Iranian missile depots, air defense...",https://nypost.com/2026/07/19/world-news/us-bl...
153,33,2026-07-18-17-18-47 +0000,bbc,"Toronto, New York and Washington top list of m...",https://www.bbc.co.uk/news/articles/c5ywdl9ne3...
101,32,2026-07-19-01-33-02 +0000,nypost,NYC homeless man hurls cell phone at baby in s...,https://nypost.com/2026/07/18/us-news/bryant-p...
122,27,2026-07-18-23-29-48 +0000,chitri,Social media influencers Andrew and Tristian T...,https://www.chicagotribune.com/2026/07/18/tate...
163,27,2026-07-18-15-54-28 +0000,nypost,Hochul backed NY data-center ban to satisfy DS...,https://nypost.com/2026/07/18/us-news/hochul-b...
128,23,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
176,21,2026-07-18-14-32-48 +0000,bbc,Ruthless plotter? Flip-flopper? Dad dancer? In...,https://www.bbc.co.uk/news/articles/c3043vl2l7...
92,20,2026-07-19-03-51-31 +0000,nypost,Tulsi Gabbard’s brother accused of trying to l...,https://nypost.com/2026/07/18/us-news/tulsi-ga...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)