## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-01-18-04 +0000,nyt,At Least 27 Dead in Guyana After Ferry Capsizes,https://www.nytimes.com/2026/07/20/world/ameri...
1,2026-07-21-01-07-05 +0000,latimes,'So demeaning.' United employee threatens to c...,https://www.latimes.com/california/story/2026-...
2,2026-07-21-01-00-15 +0000,nyt,Pentagon Identifies 2 U.S. Soldiers Killed in ...,https://www.nytimes.com/2026/07/20/us/iran-war...
3,2026-07-21-01-00-00 +0000,wsj,Israel Believes Iran Moved Nuclear Centrifuges...,https://www.wsj.com/world/middle-east/israel-b...
4,2026-07-21-01-00-00 +0000,wsj,The Man Who Runs the IRS Spied on Colleagues W...,https://www.wsj.com/finance/banking/irs-bisign...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3255/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
42     trump     39
21      iran     35
38       new     30
257  burnham     26
258     will     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
363,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...,141
313,2026-07-20-10-42-53 +0000,nypost,Trump says new Qatar-donated Air Force One to ...,https://nypost.com/2026/07/20/us-news/trump-sa...,128
101,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,124
164,2026-07-20-18-57-40 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,121
214,2026-07-20-17-07-50 +0000,nypost,Enraged Trump warns Iran each US soldier kille...,https://nypost.com/2026/07/20/us-news/enraged-...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
363,141,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
364,96,2026-07-20-04-01-05 +0000,nyt,Five of the Main Challenges Awaiting Andy Burn...,https://www.nytimes.com/2026/07/20/world/europ...
2,76,2026-07-21-01-00-15 +0000,nyt,Pentagon Identifies 2 U.S. Soldiers Killed in ...,https://www.nytimes.com/2026/07/20/us/iran-war...
121,69,2026-07-20-20-50-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
335,60,2026-07-20-09-30-00 +0000,wsj,"For the past month, soccer fans at home and fr...",https://www.wsj.com/business/hospitality/i-nev...
163,47,2026-07-20-18-59-07 +0000,nypost,California gas suffers another huge setback as...,https://nypost.com/2026/07/20/us-news/californ...
264,42,2026-07-20-13-30-48 +0000,nypost,Texas Dem House hopeful creeped on women in Sp...,https://nypost.com/2026/07/20/us-news/texas-de...
209,40,2026-07-20-17-16-29 +0000,chitri,Ex-Mexican drug lord Ismael ‘El Mayo’ Zambada ...,https://www.chicagotribune.com/2026/07/20/mexi...
68,40,2026-07-20-22-36-41 +0000,nyt,5 Found Dead in Ohio After Child Tells Driver ...,https://www.nytimes.com/2026/07/20/us/scioto-r...
141,39,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)