## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-15-57-12 +0000,nypost,"Brazil markets, currency reel from leftist Lui...",https://nypost.com/2026/10/26/business/brazil-...
1,2026-10-26-15-57-06 +0000,nyt,Norway Pushes Back After Trump Disparages It O...,https://www.nytimes.com/2026/10/26/world/europ...
2,2026-10-26-15-53-16 +0000,nyt,DraftKings Faces Growing Pressure Over How It ...,https://www.nytimes.com/2026/10/26/business/dr...
3,2026-10-26-15-48-38 +0000,chitri,On last day to turn in signatures for 2027 Chi...,https://www.chicagotribune.com/2026/10/26/sign...
4,2026-10-26-15-47-51 +0000,nypost,ICE nabs illegal migrant in NYC wanted for mur...,https://nypost.com/2026/10/26/us-news/ice-nabs...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
10  election     29
14     trump     26
7       lula     20
0     brazil     17
82       new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
193,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,122
222,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva declared winner of B...,https://www.chicagotribune.com/2026/10/25/braz...,101
106,2026-10-26-11-06-00 +0000,wsj,The Morning Risk Report: Lula Wins Fourth Term...,https://www.wsj.com/risk-compliance-journal/th...,93
0,2026-10-26-15-57-12 +0000,nypost,"Brazil markets, currency reel from leftist Lui...",https://nypost.com/2026/10/26/business/brazil-...,89
206,2026-10-26-00-51-25 +0000,nypost,"Trump critic Lula wins reelection in Brazil, s...",https://nypost.com/2026/10/25/world-news/trump...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
193,122,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...
258,68,2026-10-25-19-38-58 +0000,nypost,Venezuelan opposition leader María Corina Mach...,https://nypost.com/2026/10/25/world-news/venez...
17,57,2026-10-26-15-10-00 +0000,wsj,Allies worry Senate Majority Leader John Thune...,https://www.wsj.com/politics/elections/a-bruis...
91,44,2026-10-26-12-00-00 +0000,nypost,Inside California’s unlikely new boomtown wher...,https://nypost.com/2026/10/26/real-estate/fres...
290,41,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
103,36,2026-10-26-11-17-19 +0000,chitri,Serbia’s Aleksandar Vucic concedes defeat to t...,https://www.chicagotribune.com/2026/10/26/serb...
49,35,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...
107,34,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
43,33,2026-10-26-14-20-33 +0000,cbc,AI giant Anthropic files papers to sell shares...,https://www.cbc.ca/news/business/anthropic-ipo...
207,32,2026-10-26-00-45-21 +0000,chitri,Iranians fear a possible return to all-out war...,https://www.chicagotribune.com/2026/10/25/iran...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)