## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-11-47-31 +0000,nypost,Assistant principal busted for allegedly offer...,https://nypost.com/2026/06/05/us-news/assistan...
1,2026-06-05-11-34-16 +0000,nyt,"As Trump Toughens Rules on Cuba’s Economy, Hot...",https://www.nytimes.com/2026/06/04/world/ameri...
2,2026-06-05-11-32-51 +0000,bbc,Fury in France after child murder suspect's cr...,https://www.bbc.com/news/articles/c1424v7mk8go...
3,2026-06-05-11-30-00 +0000,nypost,Massapequa looks to stop rival Sachem from win...,https://nypost.com/2026/06/05/sports/massapequ...
4,2026-06-05-11-30-00 +0000,nypost,Senate health boss demands Mamdani answer for ...,https://nypost.com/2026/06/05/us-news/senate-h...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
10    trump     33
157     new     17
95       up     16
50   market     14
55   spacex     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
294,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...,89
297,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...,79
207,2026-06-04-21-36-37 +0000,latimes,"Chabria: No, Mr. Hilton, our elections are not...",https://www.latimes.com/california/story/2026-...,77
42,2026-06-05-10-09-00 +0000,wsj,GOP senators passed a $70 billion immigration-...,https://www.wsj.com/politics/policy/gop-senato...,72
317,2026-06-04-15-22-16 +0000,nyt,"John Bolton, Ex-Trump Adviser, Reaches Deal to...",https://www.nytimes.com/2026/06/04/us/politics...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
294,89,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...
147,67,2026-06-05-00-42-27 +0000,nypost,Graham Platner admits to sexting women ‘soon’ ...,https://nypost.com/2026/06/04/us-news/graham-p...
297,63,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
141,50,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
90,50,2026-06-05-08-27-21 +0000,wsj,Jobs Report Today: Stock Futures Dip as Invest...,https://www.wsj.com/livecoverage/may-jobs-repo...
36,45,2026-06-05-10-36-01 +0000,nypost,James Handy girlfriend’s son seen calmly walki...,https://nypost.com/2026/06/05/us-news/james-ha...
38,44,2026-06-05-10-32-00 +0000,wsj,Eurozone Economy Shrank in First Quarter as Ir...,https://www.wsj.com/economy/eurozone-economy-s...
300,41,2026-06-04-16-33-00 +0000,wsj,Live Q&A: Musk’s $75 Billion SpaceX IPO—Ask Us...,https://www.wsj.com/business/live-q-a-musks-75...
255,39,2026-06-04-19-41-33 +0000,nyt,Latest Israel-Lebanon Cease-Fire Shows Little ...,https://www.nytimes.com/2026/06/04/world/middl...
304,38,2026-06-04-16-26-24 +0000,nypost,Dow soars 900 points to all-time high on value...,https://nypost.com/2026/06/04/business/dow-soa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)