## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-24-17-04-50 +0000,bbc,"Nearly 90,000 told to evacuate as wildfire app...",https://www.bbc.co.uk/news/articles/c4gqlp0yzy...
1,2026-08-24-17-04-04 +0000,nyt,UK Prime Minister Burnham Arrives in Ukraine a...,https://www.nytimes.com/2026/08/24/world/europ...
2,2026-08-24-17-03-28 +0000,nyt,U.S. to Unveil ‘Economic D-Day’ Sanctions Targ...,https://www.nytimes.com/2026/08/24/us/politics...
3,2026-08-24-17-00-00 +0000,startribune,Where to find the new foods at the State Fair,https://www.startribune.com/where-to-find-the-...
4,2026-08-24-16-59-39 +0000,nypost,Young Florida pilot who survived crash-landing...,https://nypost.com/2026/08/24/us-news/florida-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
71   trump     29
22    iran     18
26     new     15
97  canada     10
98   trade     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
10,2026-08-24-16-44-43 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,95
8,2026-08-24-16-50-00 +0000,wsj,The Trump administration is proposing a new si...,https://www.wsj.com/politics/policy/government...,80
73,2026-08-24-14-00-29 +0000,nypost,Trump revs up tariffs on Canada to 50% on auto...,https://nypost.com/2026/08/24/us-news/trump-re...,71
110,2026-08-24-12-27-28 +0000,cbc,Trump threatens new 50% tariffs on Canadian ca...,https://www.cbc.ca/news/livestory/canada-u-s-t...,71
177,2026-08-24-08-49-48 +0000,nyt,Which Countries Could Be Hurt Most by Trump’s ...,https://www.nytimes.com/article/us-iran-econom...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
10,95,2026-08-24-16-44-43 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...
145,61,2026-08-24-10-30-37 +0000,nypost,‘Economic D-Day’ sanctions against Iran will b...,https://nypost.com/2026/08/24/us-news/iran-eco...
212,42,2026-08-24-01-00-00 +0000,wsj,Kevin Warsh’s reluctance to signal where inter...,https://www.wsj.com/economy/central-banking/wa...
261,36,2026-08-23-18-11-55 +0000,nypost,Ex-Mayor Dan Sullivan backs Dan Sullivan to be...,https://nypost.com/2026/08/23/us-news/dan-sull...
1,35,2026-08-24-17-04-04 +0000,nyt,UK Prime Minister Burnham Arrives in Ukraine a...,https://www.nytimes.com/2026/08/24/world/europ...
80,35,2026-08-24-13-48-12 +0000,nypost,California calls off Paramount settlement meet...,https://nypost.com/2026/08/24/business/califor...
35,32,2026-08-24-15-44-58 +0000,nypost,Utter pandemonium as mass street brawl between...,https://nypost.com/2026/08/24/us-news/utter-pa...
22,30,2026-08-24-16-14-48 +0000,nyt,Someone Was Impersonating Collien Fernandes On...,https://www.nytimes.com/2026/08/23/magazine/co...
176,30,2026-08-24-08-58-03 +0000,cbc,"Fast-moving wildfire threatens Reno, Nevada, f...",https://www.cbc.ca/news/world/wildfire-nevada-...
39,30,2026-08-24-15-30-00 +0000,wsj,Local Business Group Sues Over Mamdani’s Plan ...,https://www.wsj.com/us-news/local-business-gro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)