## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-15-04-01-29 +0000,startribune,No power? No problem! Scooter ride rolls on Fr...,https://www.startribune.com/no-power-no-proble...
1,2026-08-15-04-01-24 +0000,nypost,Tennessee death row inmate’s last words to son...,https://nypost.com/2026/08/15/us-news/tennesse...
2,2026-08-15-04-01-18 +0000,nyt,"Entrenched, Embattled and Defiant, the Taliban...",https://www.nytimes.com/2026/08/15/world/asia/...
3,2026-08-15-04-01-09 +0000,nyt,Heat Deaths in a ‘Cold’ Country Are a Warning ...,https://www.nytimes.com/2026/08/15/world/europ...
4,2026-08-15-04-01-08 +0000,nyt,"Wary of Trump, Europe Seeks Role in Eventual R...",https://www.nytimes.com/2026/08/15/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2449/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
32      trump     38
581       new     17
746     court     14
247        he     11
270  election     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...,109
184,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...,109
83,2026-08-14-21-47-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...,105
101,2026-08-14-21-13-51 +0000,latimes,Trump says USS Abraham Lincoln deployment 'not...,https://www.latimes.com/politics/story/2026-08...,98
260,2026-08-14-13-13-34 +0000,chitri,President Donald Trump set to highlight violen...,https://www.chicagotribune.com/2026/08/14/trum...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,109,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...
184,71,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...
90,63,2026-08-14-21-32-00 +0000,nypost,Family of dead ex-Cambridge professor Jason Ar...,https://nypost.com/2026/08/14/world-news/famil...
230,60,2026-08-14-15-26-04 +0000,cbc,Luigi Mangione admits to shooting health insur...,https://www.cbc.ca/news/world/us-federal-heari...
325,55,2026-08-14-09-41-00 +0000,wsj,A new report led by White House trade adviser ...,https://www.wsj.com/economy/trade/white-house-...
340,46,2026-08-14-08-51-39 +0000,cbc,Reform UK leader Nigel Farage beats Count Binf...,https://www.cbc.ca/news/world/uk-clacton-byele...
91,43,2026-08-14-21-30-06 +0000,chitri,Palestinians besieged in West Bank village fea...,https://www.chicagotribune.com/2026/08/14/isra...
244,40,2026-08-14-14-49-00 +0000,wsj,"Sales at U.S. retailers slid in July, the late...",https://www.wsj.com/economy/weak-retail-sales-...
216,38,2026-08-14-16-25-00 +0000,wapo,Michigan’s marquee Senate race close in first ...,https://www.washingtonpost.com/politics/2026/0...
248,33,2026-08-14-14-19-47 +0000,nypost,Suspect charged with vandalizing DC World War ...,https://nypost.com/2026/08/14/us-news/suspect-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)