## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-05-14-01-07 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
1,2026-04-05-13-53-13 +0000,cbc,"On Easter, Pope Leo urges world leaders to end...",https://www.cbc.ca/news/world/pope-leo-easter-...
2,2026-04-05-13-47-11 +0000,nyt,Some Voters Say Congress Is Too Old. These Bla...,https://www.nytimes.com/2026/04/04/us/voters-c...
3,2026-04-05-13-38-38 +0000,nyt,Iran’s Downing of Plane and U.S. Rescue Leave ...,https://www.nytimes.com/2026/04/05/world/middl...
4,2026-04-05-13-37-13 +0000,bbc,Starmer 'concerned' over Kanye West UK festiva...,https://www.bbc.com/news/articles/cp86942yj97o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0       iran     25
4      trump     17
124      new     12
1        war      9
8    iranian      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-05-14-01-07 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...,84
15,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...,79
11,2026-04-05-12-50-51 +0000,nypost,"How US used SEAL Team 6, a CIA ruse and death ...",https://nypost.com/2026/04/05/world-news/us-re...,65
159,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,64
9,2026-04-05-13-00-03 +0000,startribune,US aviator rescued as Trump vows strikes on Ir...,https://www.startribune.com/us-service-member-...,61

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,84,2026-04-05-14-01-07 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
76,46,2026-04-05-02-59-01 +0000,nypost,"Leo XIV celebrates first Easter vigil as pope,...",https://nypost.com/2026/04/04/world-news/pope-...
73,41,2026-04-05-03-48-19 +0000,nypost,"Inside secret SoCal lives of niece, grandniece...",https://nypost.com/2026/04/04/us-news/inside-t...
15,37,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...
11,33,2026-04-05-12-50-51 +0000,nypost,"How US used SEAL Team 6, a CIA ruse and death ...",https://nypost.com/2026/04/05/world-news/us-re...
43,31,2026-04-05-09-30-00 +0000,wsj,Central banks live in fear of their last mista...,https://www.wsj.com/economy/central-banking/pa...
144,26,2026-04-04-17-20-48 +0000,nyt,"Houston Cheers on Artemis II Moon Mission, Rec...",https://www.nytimes.com/2026/04/04/us/artemis-...
30,25,2026-04-05-10-00-00 +0000,latimes,"Barabak: For more than 30 years — day in, day ...",https://www.latimes.com/politics/story/2026-04...
22,23,2026-04-05-12-00-00 +0000,nypost,"Fastest, most luxurious vehicles on earth are ...",https://nypost.com/2026/04/05/us-news/fast-tim...
119,23,2026-04-04-20-09-53 +0000,latimes,Man convicted of murdering his girlfriend four...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)