## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-07-07-50 +0000,nyt,At Least 6 Injured in Stabbing in South Korea,https://www.nytimes.com/2026/10/13/world/asia/...
1,2026-10-13-07-00-00 +0000,wsj,CSG Buys Largest Stake in Canada’s MDA Space t...,https://www.wsj.com/finance/investing/csg-buys...
2,2026-10-13-06-58-20 +0000,bbc,India 'cockroach' leaders detained after enter...,https://www.bbc.co.uk/news/articles/cqz0v11n2v...
3,2026-10-13-06-57-00 +0000,wsj,Dollar Stays Firm After Hitting 18-Month High,https://www.wsj.com/finance/currencies/asian-c...
4,2026-10-13-06-56-41 +0000,nypost,Kentucky teen finishes Chicago Marathon less t...,https://nypost.com/2026/10/13/us-news/kentucky...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2382/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
184   trump     45
146  russia     17
185      he     16
106  energy     15
101     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
276,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...,127
75,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,110
271,2026-10-12-11-47-59 +0000,nypost,Zelensky says Russia still striking energy fac...,https://nypost.com/2026/10/12/world-news/zelen...,106
309,2026-10-12-09-21-38 +0000,wapo,Trump’s diesel deal with Russia shows how tied...,https://www.washingtonpost.com/politics/2026/1...,105
305,2026-10-12-09-48-16 +0000,cbc,Zelenskyy says Russia violating Trump's 'energ...,https://www.cbc.ca/news/world/zelenskyy-russia...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
276,127,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...
75,60,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...
67,58,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
81,50,2026-10-12-23-44-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
292,48,2026-10-12-10-27-34 +0000,nypost,Family of Thai teen sex worker found stuffed ...,https://nypost.com/2026/10/12/world-news/famil...
133,43,2026-10-12-21-19-00 +0000,wsj,Energy Stocks Rise as Global Conflicts Push Up...,https://www.wsj.com/finance/stocks/energy-stoc...
275,42,2026-10-12-11-14-24 +0000,nypost,Disturbing video shows moment Houthi terrorist...,https://nypost.com/2026/10/12/world-news/distu...
299,37,2026-10-12-10-00-00 +0000,nypost,AI safety ‘doomers’ pouring cash into Minnesot...,https://nypost.com/2026/10/12/business/ai-safe...
293,36,2026-10-12-10-14-45 +0000,chitri,Attorney and former Robbins police chief compe...,https://www.chicagotribune.com/2026/10/12/atto...
280,36,2026-10-12-11-02-40 +0000,chitri,2 American economists win Nobel prize for over...,https://www.chicagotribune.com/2026/10/12/nobe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)