## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-16-08-33 +0000,nypost,‘New York’ magazine investigating plagiarism c...,https://nypost.com/2026/05/17/us-news/new-york...
1,2026-05-17-16-07-16 +0000,nypost,Video shows Swatch psychos stampede Long Islan...,https://nypost.com/2026/05/17/us-news/watch-ps...
2,2026-05-17-16-06-39 +0000,nypost,Air Force intel vet Monica Witt allegedly spir...,https://nypost.com/2026/05/17/us-news/air-forc...
3,2026-05-17-16-01-08 +0000,nyt,W.H.O. Declares Ebola Outbreak a Global Health...,https://www.nytimes.com/2026/05/17/world/afric...
4,2026-05-17-16-01-00 +0000,wsj,Authorities play catch-up with suspicious wage...,https://www.wsj.com/politics/policy/washington...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2652/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
97        trump     31
432       world     10
395  eurovision      8
98        drone      8
0           new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
12,2026-05-17-15-53-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,90
102,2026-05-17-02-56-27 +0000,nypost,Republican Sen. Bill Cassidy — who voted to co...,https://nypost.com/2026/05/16/us-news/la-repub...,90
81,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...,76
96,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...,76
151,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
12,90,2026-05-17-15-53-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
30,39,2026-05-17-14-02-27 +0000,cbc,U.A.E. reports drone strike at nuclear power p...,https://www.cbc.ca/news/world/uae-drone-strike...
96,39,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...
4,35,2026-05-17-16-01-00 +0000,wsj,Authorities play catch-up with suspicious wage...,https://www.wsj.com/politics/policy/washington...
81,33,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...
122,29,2026-05-17-00-40-23 +0000,latimes,The world's largest wildlife crossing and five...,https://www.latimes.com/california/story/2026-...
43,28,2026-05-17-12-52-26 +0000,nypost,Climate group reverses course on doomsday pred...,https://nypost.com/2026/05/17/us-news/trump-ce...
163,28,2026-05-16-19-52-53 +0000,nypost,Recovery operation for Italian divers killed i...,https://nypost.com/2026/05/16/world-news/recov...
34,25,2026-05-17-13-39-00 +0000,wsj,WHO Declares Global Health Emergency After Ebo...,https://www.wsj.com/world/africa/who-declares-...
1,24,2026-05-17-16-07-16 +0000,nypost,Video shows Swatch psychos stampede Long Islan...,https://nypost.com/2026/05/17/us-news/watch-ps...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)