## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-11-21-05-10 +0000,nypost,"Earth, Wind & Fire members rally around drumme...",https://nypost.com/2026/08/11/us-news/earth-wi...
1,2026-08-11-21-05-00 +0000,cbc,CUSMA breakdown could mean hundreds of thousan...,https://www.cbc.ca/news/business/trade-renegot...
2,2026-08-11-21-02-44 +0000,nyt,"Deported From the U.S., Trapped in a Prison in...",https://www.nytimes.com/video/world/africa/100...
3,2026-08-11-21-02-21 +0000,chitri,Ultra rare Nintendo Super Mario Brothers Duck ...,https://www.chicagotribune.com/2026/08/11/rare...
4,2026-08-11-21-00-00 +0000,wsj,Opinion | The GAO Precedent for Fed Independence,https://www.wsj.com/opinion/the-gao-precedent-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2715/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
47       trump     50
216        new     31
69        iran     17
97          ai     15
143  president     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
39,2026-08-11-20-20-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...,186
34,2026-08-11-20-24-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,150
319,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,134
322,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,108
223,2026-08-11-13-10-26 +0000,chitri,President Donald Trump pivots back to sanction...,https://www.chicagotribune.com/2026/08/11/trum...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
39,186,2026-08-11-20-20-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...
319,84,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
338,67,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
280,61,2026-08-11-09-27-28 +0000,nypost,Ex-Syrian ruler Bashar al-Assad sentenced to d...,https://nypost.com/2026/08/11/world-news/ex-sy...
375,58,2026-08-10-21-47-00 +0000,wsj,"Nvidia, Wall Street Firms Strike AI Financing ...",https://www.wsj.com/business/deals/nvidia-wall...
340,46,2026-08-11-00-53-51 +0000,nypost,"NYC first lady Rama Duwaji traveling to Syria,...",https://nypost.com/2026/08/10/us-news/nyc-firs...
205,46,2026-08-11-14-00-00 +0000,wsj,"Home sales fell in July, getting the summer of...",https://www.wsj.com/economy/housing/july-home-...
292,44,2026-08-11-08-55-26 +0000,cbc,Colombia quake death toll tops 200 as rescuers...,https://www.cbc.ca/news/world/colombia-earthqu...
33,41,2026-08-11-20-25-05 +0000,nypost,Huge breakthrough for California gas as oil gi...,https://nypost.com/2026/08/11/us-news/californ...
347,40,2026-08-11-00-00-00 +0000,wsj,Two inflation reports over the next month are ...,https://www.wsj.com/economy/central-banking/in...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)