## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-11-01-22-47-20 +0000,nypost,NFL legend says he’s ditching his Tennessee ra...,https://nypost.com/2026/11/01/us-news/nfl-lege...
1,2026-11-01-22-44-56 +0000,nypost,Michigan Senate candidate Mike Rogers says he’...,https://nypost.com/2026/11/01/us-news/michigan...
2,2026-11-01-22-42-11 +0000,nyt,9 Dead in Small Plane Crash in Palm Beach Coun...,https://www.nytimes.com/2026/11/01/us/florida-...
3,2026-11-01-22-42-02 +0000,nypost,Iran’s boosted weapons capabilities have cause...,https://nypost.com/2026/11/01/world-news/irans...
4,2026-11-01-22-37-12 +0000,nyt,Shootings on Halloween Night Leave at Least 24...,https://www.nytimes.com/2026/11/01/us/hallowee...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2649/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
158     trump     20
13     senate     15
51       race     13
72   election     11
69     alaska     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-11-01-18-25-38 +0000,chitri,Democrat Haley Stevens endorses GOP’s Mike Rog...,https://www.chicagotribune.com/2026/11/01/demo...,80
54,2026-11-01-19-44-12 +0000,nyt,Judge Rejects Trump Officials’ Move to Challen...,https://www.nytimes.com/2026/11/01/us/alaska-s...,66
1,2026-11-01-22-44-56 +0000,nypost,Michigan Senate candidate Mike Rogers says he’...,https://nypost.com/2026/11/01/us-news/michigan...,64
46,2026-11-01-20-20-26 +0000,nypost,DOJ suit tossed as feds fought certification o...,https://nypost.com/2026/11/01/us-news/doj-suit...,61
74,2026-11-01-18-05-27 +0000,chitri,Judge dismisses lawsuit seeking to block certi...,https://www.chicagotribune.com/2026/11/01/laws...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,80,2026-11-01-18-25-38 +0000,chitri,Democrat Haley Stevens endorses GOP’s Mike Rog...,https://www.chicagotribune.com/2026/11/01/demo...
115,51,2026-11-01-15-15-00 +0000,wsj,Voters head to the polls on Tuesday as benefic...,https://www.wsj.com/economy/us-economic-data-g...
50,46,2026-11-01-20-02-00 +0000,wsj,Maybe the Democrats win big Tuesday. But the p...,https://www.wsj.com/politics/policy/democrats-...
70,46,2026-11-01-18-29-00 +0000,wsj,"Sen. Chris Murphy of Connecticut, a rising sta...",https://www.wsj.com/politics/sen-chris-murphy-...
51,41,2026-11-01-20-00-00 +0000,wsj,"In the Florida governor’s race, Democrat David...",https://www.wsj.com/politics/elections/democra...
166,41,2026-11-01-07-26-18 +0000,nypost,FBI visits ‘Decoy Dan’ Sullivan donors as feds...,https://nypost.com/2026/11/01/us-news/alaska-s...
37,35,2026-11-01-20-57-27 +0000,nypost,Ex-college football star killed by cops after ...,https://nypost.com/2026/11/01/us-news/ex-colle...
24,29,2026-11-01-21-37-49 +0000,nypost,California school staffers busted in $300K emb...,https://nypost.com/2026/11/01/us-news/californ...
110,28,2026-11-01-15-46-13 +0000,nypost,‘Gen Z Takes Charge’ protests across Germany t...,https://nypost.com/2026/11/01/world-news/gen-z...
111,27,2026-11-01-15-43-06 +0000,nypost,Katie Zacharia’s Halloween post humblebrags ab...,https://nypost.com/2026/11/01/us-news/katie-za...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)