## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-11-05-38 +0000,nyt,How Trump’s Deportation Policies Have Rocked a...,https://www.nytimes.com/2026/10/03/us/politics...
1,2026-10-03-11-00-00 +0000,missionlocal,People We Meet: The mayor of Caselli Avenue,https://missionlocal.org/2026/10/caselli-mayor...
2,2026-10-03-10-58-51 +0000,bbc,UK-Iranian dual national bailed after RAF Fair...,https://www.bbc.co.uk/news/articles/c6d095yggg...
3,2026-10-03-10-56-00 +0000,wsj,Xi’s Rest Breaks Cut Into His Summit With Trump,https://www.wsj.com/articles/xis-rest-breaks-c...
4,2026-10-03-10-27-57 +0000,bbc,Kemi Badenoch has cemented her image. Now she ...,https://www.bbc.co.uk/news/articles/cmn8e88771...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2641/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
0       trump     38
78   flydubai     20
659       was     14
80      pilot     14
265       new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
326,2026-10-02-14-22-23 +0000,nypost,Trump announces Europe will release ‘massive a...,https://nypost.com/2026/10/02/us-news/trump-an...,102
208,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...,99
121,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...,95
325,2026-10-02-14-25-52 +0000,nypost,Hero plumber who stopped co-pilot from crashin...,https://nypost.com/2026/10/02/world-news/hero-...,92
373,2026-10-02-11-20-46 +0000,chitri,‘I was fighting for my life’: Indian pilot hai...,https://www.chicagotribune.com/2026/10/02/indi...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
326,102,2026-10-02-14-22-23 +0000,nypost,Trump announces Europe will release ‘massive a...,https://nypost.com/2026/10/02/us-news/trump-an...
121,95,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...
197,70,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
82,64,2026-10-03-03-48-51 +0000,nypost,Christa Pike thought her arm would ‘burst open...,https://nypost.com/2026/10/02/us-news/christa-...
208,61,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
205,49,2026-10-02-20-29-00 +0000,wsj,"The U.S. added 29,000 jobs in September, far s...",https://www.wsj.com/economy/jobs/september-job...
369,47,2026-10-02-11-45-58 +0000,nypost,House Democrats add eight seats to midterm tar...,https://nypost.com/2026/10/02/us-news/house-de...
101,46,2026-10-03-01-32-36 +0000,nypost,Texas barber found $128K in cash on top of ban...,https://nypost.com/2026/10/02/us-news/texas-ba...
207,43,2026-10-02-20-26-03 +0000,nypost,Trump says ‘Cornell 7’ frat boys ‘won’t get a ...,https://nypost.com/2026/10/02/us-news/trump-sa...
91,41,2026-10-03-02-20-03 +0000,nypost,Gavin Newsom vetoes bill giving California hig...,https://nypost.com/2026/10/02/us-news/gavin-ne...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)