## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-29-13-37-07 +0000,nyt,Oil Prices Fall as U.S. and Iran Edge Closer t...,https://www.nytimes.com/2026/05/29/business/oi...
1,2026-05-29-13-34-48 +0000,nypost,Trump mocks Jill Biden over claim she thought ...,https://nypost.com/2026/05/29/us-news/trump-mo...
2,2026-05-29-13-33-00 +0000,wsj,Fed’s Bowman Wary of Reacting to Short-Term En...,https://www.wsj.com/economy/central-banking/fe...
3,2026-05-29-13-31-58 +0000,nyt,"After New Push by the Bolsonaros, U.S. Labels ...",https://www.nytimes.com/2026/05/28/world/ameri...
4,2026-05-29-13-30-53 +0000,nyt,Russian Drone Hits Romanian Apartment Building...,https://www.nytimes.com/2026/05/29/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
7       trump     28
3        iran     24
764       bee     21
763  spelling     19
529  national     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
138,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...,145
160,2026-05-29-01-47-48 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,144
163,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,144
186,2026-05-29-00-11-26 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,144
167,2026-05-29-01-10-16 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
138,145,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...
62,113,2026-05-29-10-56-00 +0000,wsj,President Trump’s face could appear on a $250 ...,https://www.wsj.com/politics/policy/white-hous...
285,67,2026-05-28-20-07-00 +0000,wsj,"Reports of an Iran deal boost markets, new-car...",https://www.wsj.com/business/autos/iran-deal-r...
173,62,2026-05-29-01-00-00 +0000,wsj,Labor’s share of economic output just hit an a...,https://www.wsj.com/finance/stocks/the-record-...
358,59,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
175,53,2026-05-29-00-42-00 +0000,wsj,Shares in Dell soared nearly 40% in after-hour...,https://www.wsj.com/tech/dell-stock-soars-on-d...
19,49,2026-05-29-13-00-00 +0000,wsj,You Won the Battle on Investment Fees. You’re ...,https://www.wsj.com/finance/investing/you-won-...
227,43,2026-05-28-22-05-54 +0000,nypost,Democrats enraged by Jill Biden’s book as ex-f...,https://nypost.com/2026/05/28/us-news/democrat...
133,43,2026-05-29-05-16-11 +0000,nypost,Armed Russian drone slams into Romanian apartm...,https://nypost.com/2026/05/29/us-news/armed-ru...
286,41,2026-05-28-20-02-58 +0000,nypost,Former NFL punter — a Democrat — rips Gavin Ne...,https://nypost.com/2026/05/28/us-news/former-n...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)