## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-23-11-01 +0000,nyt,King Charles III Cracks Jokes and Wins Over Co...,https://www.nytimes.com/2026/04/28/us/king-cha...
1,2026-04-28-23-07-25 +0000,bbc,"Reform is not racist, Welsh leader says in hea...",https://www.bbc.com/news/articles/c0r2w79n9w1o...
2,2026-04-28-23-02-15 +0000,bbc,Face serum advert banned over 'five years youn...,https://www.bbc.com/news/articles/c78kl05en7po...
3,2026-04-28-23-00-00 +0000,missionlocal,Meet the District 2 candidates: Where should S...,https://missionlocal.org/2026/04/sf-district-2...
4,2026-04-28-22-53-15 +0000,cbc,"San Francisco, Oakland finally land 2-year leg...",https://www.cbc.ca/news/world/san-francisco-oa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2610/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
59   trump     56
0     king     23
210   iran     21
150    new     17
211    war     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
325,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,191
347,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,141
224,2026-04-28-16-27-08 +0000,nypost,President Trump gives first lady Melania a pla...,https://nypost.com/2026/04/28/us-news/presiden...,139
319,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...,126
103,2026-04-28-20-34-42 +0000,bbc,In pictures: King meets Trump at White House a...,https://www.bbc.com/news/articles/c86e6z26xdpo...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
325,191,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
277,110,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
122,78,2026-04-28-20-02-26 +0000,nypost,King Charles III hails ‘irreplaceable and unbr...,https://nypost.com/2026/04/28/us-news/king-cha...
339,63,2026-04-28-10-00-00 +0000,latimes,Supreme Court will hear Trump's bid to end leg...,https://www.latimes.com/politics/story/2026-04...
183,59,2026-04-28-18-07-51 +0000,nypost,Ex-FBI Director James Comey indicted for threa...,https://nypost.com/2026/04/28/us-news/justice-...
314,51,2026-04-28-11-44-00 +0000,wsj,"Pushing past a third assassination attempt, th...",https://www.wsj.com/politics/policy/pushing-pa...
266,48,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
406,47,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...
34,47,2026-04-28-22-05-30 +0000,nypost,Musk kicks off explosive OpenAI trial by slamm...,https://nypost.com/2026/04/28/business/musk-ki...
319,44,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)