## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-18-23-46-56 +0000,nyt,"June 17, 1994: Millions Watched Police Chase O...",https://www.nytimes.com/2026/10/18/us/oj-simps...
1,2026-10-18-23-46-48 +0000,nypost,Activists wants sleazy NYC ‘Market of Sweethea...,https://nypost.com/2026/10/18/us-news/activist...
2,2026-10-18-23-46-21 +0000,nyt,Carney Says Fire at Canadian Forces Base Wainw...,https://www.nytimes.com/2026/10/18/world/canad...
3,2026-10-18-23-41-33 +0000,nypost,New details emerge about Alpha Phi sorority sc...,https://nypost.com/2026/10/18/us-news/new-deta...
4,2026-10-18-23-31-05 +0000,nypost,Bakersfield’s Foothill High School erupts afte...,https://nypost.com/2026/10/18/us-news/bakersfi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
94    trump     30
96   russia     12
26      new     12
17     fire      9
419    will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
14,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...,94
92,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...,81
93,2026-10-18-17-07-58 +0000,nypost,GOP Senate candidate Mike Rogers breaks with T...,https://nypost.com/2026/10/18/us-news/gop-sen-...,73
125,2026-10-18-14-30-49 +0000,nyt,Zelensky Says Trump Risks ‘Historic Mistake’ I...,https://www.nytimes.com/2026/10/18/world/europ...,66
53,2026-10-18-20-46-42 +0000,nyt,Trump Offers Putin Economic Relief in Hopes Th...,https://www.nytimes.com/2026/10/17/business/tr...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
14,94,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...
192,46,2026-10-18-02-00-00 +0000,wsj,Republicans across the most competitive House ...,https://www.wsj.com/politics/elections/republi...
137,45,2026-10-18-12-12-36 +0000,nypost,Canadian military forced to parachute troops i...,https://nypost.com/2026/10/18/world-news/canad...
57,43,2026-10-18-20-39-53 +0000,nypost,NYC nabe gets horde of brand new Citi Bikes go...,https://nypost.com/2026/10/18/us-news/nyc-nabe...
144,41,2026-10-18-11-27-23 +0000,nypost,Ukraine targets Putin’s hometown as it launche...,https://nypost.com/2026/10/18/world-news/blaze...
83,36,2026-10-18-18-25-56 +0000,nypost,Pope Leo says he will gradually resume duties ...,https://nypost.com/2026/10/18/world-news/pope-...
194,31,2026-10-18-01-58-57 +0000,nypost,French rioters torch historic Limoges Town Hal...,https://nypost.com/2026/10/17/world-news/limog...
24,27,2026-10-18-22-46-58 +0000,nypost,Priest gave sermon on spontaneity of death jus...,https://nypost.com/2026/10/18/world-news/pries...
108,27,2026-10-18-16-00-00 +0000,wsj,"From firehouses to farms, Pennsylvania locals ...",https://www.wsj.com/politics/elections/pennsyl...
85,24,2026-10-18-17-45-09 +0000,chitri,Photographer attacked by settlers in the West ...,https://www.chicagotribune.com/2026/10/18/phot...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)