## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-20-09-04-19 +0000,nyt,Trump’s Order to Cut Military Exercises With S...,https://www.nytimes.com/2026/08/20/us/politics...
1,2026-08-20-09-04-12 +0000,nyt,Moderna’s Shift to Cancer Company Lifts Stock ...,https://www.nytimes.com/2026/08/20/business/mo...
2,2026-08-20-09-04-01 +0000,nyt,Can We Do Anything About Tick-Borne Diseases L...,https://www.nytimes.com/2026/08/20/magazine/ti...
3,2026-08-20-09-03-41 +0000,nyt,The A.I.-Robotics Job Only a Human Can Do,https://www.nytimes.com/video/world/asia/10000...
4,2026-08-20-09-02-44 +0000,nyt,The Indian City Where AI Is Creating Jobs for ...,https://www.nytimes.com/2026/08/20/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2264/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     59
74      new     20
15       up     15
155    iran     13
131  killed     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
181,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...,123
224,2026-08-19-19-15-24 +0000,chitri,President Donald Trump picks Dr. Heidi Overton...,https://www.chicagotribune.com/2026/08/19/trum...,120
11,2026-08-20-09-00-00 +0000,wsj,Trump’s half-built White House ballroom is a 9...,https://www.wsj.com/politics/policy/build-firs...,120
310,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...,117
114,2026-08-19-23-13-53 +0000,chitri,Missouri court allows new Trump-backed US Hous...,https://www.chicagotribune.com/2026/08/19/miss...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
181,123,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
88,83,2026-08-20-01-54-00 +0000,wsj,Angie Nixon pulled off her upset in the Democr...,https://www.wsj.com/politics/elections/how-dem...
63,62,2026-08-20-04-17-53 +0000,bbc,Israel confirms soldiers fired at car in which...,https://www.bbc.co.uk/news/articles/crl7yjlpx2...
310,58,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
336,52,2026-08-19-14-18-00 +0000,wsj,"Gold Up 2% Amid Weaker Dollar, Falling Bond Yi...",https://www.wsj.com/finance/commodities-future...
189,49,2026-08-19-20-43-04 +0000,nypost,"Mark Zuckerberg’s Meta had ‘don’t ask, don’t t...",https://nypost.com/2026/08/19/business/mark-zu...
205,46,2026-08-19-20-06-51 +0000,wapo,Trump says he expects to meet with North Korea...,https://www.washingtonpost.com/politics/2026/0...
134,44,2026-08-19-22-16-41 +0000,chitri,Prince Harry and Meghan are returning to the U...,https://www.chicagotribune.com/2026/08/19/prin...
291,42,2026-08-19-16-34-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...
228,39,2026-08-19-19-05-24 +0000,nypost,Telemundo exec killed in Kenya helicopter cras...,https://nypost.com/2026/08/19/us-news/telemund...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)