## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-22-59-14 +0000,nyt,What’s a Threat? Gabbard Says It’s Up to Trump...,https://www.nytimes.com/2026/03/18/us/politics...
1,2026-03-18-22-57-46 +0000,nyt,Cesar Chavez Inspired California’s Latino Lead...,https://www.nytimes.com/2026/03/18/us/cesar-ch...
2,2026-03-18-22-56-56 +0000,nyt,"Retired Belgian Diplomat, 93, Faces Trial Over...",https://www.nytimes.com/2026/03/18/world/europ...
3,2026-03-18-22-56-55 +0000,nypost,Inside the cover-up of Cesar Chavez’s alleged ...,https://nypost.com/2026/03/18/us-news/inside-t...
4,2026-03-18-22-55-43 +0000,nyt,Trump’s Plans for America’s 250th Emphasize Re...,https://www.nytimes.com/2026/03/18/arts/design...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
4      iran     60
132     war     38
3     trump     36
7    chavez     22
6     cesar     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
254,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...,175
296,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,169
424,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,166
188,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,158
331,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
254,175,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...
73,84,2026-03-18-21-06-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
208,77,2026-03-18-16-25-32 +0000,nyt,Dolores Huerta Issues Statement on Cesar Chave...,https://www.nytimes.com/2026/03/18/us/dolores-...
331,59,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...
273,52,2026-03-18-13-01-27 +0000,nyt,Illinois Primary Election Takeaways: Stratton ...,https://www.nytimes.com/2026/03/18/us/election...
128,47,2026-03-18-19-29-00 +0000,wsj,An updated list shows House departures hitting...,https://www.wsj.com/politics/policy/why-a-reco...
294,45,2026-03-18-11-00-00 +0000,wsj,Israel Is Hunting Down Iranian Regime Members ...,https://www.wsj.com/world/middle-east/israel-i...
25,44,2026-03-18-22-27-58 +0000,nypost,Ex-NYC Mayor Bill de Blasio finally admits ‘de...,https://nypost.com/2026/03/18/us-news/bill-de-...
326,44,2026-03-18-09-30-00 +0000,nypost,Here’s who’s really leading Iran with supreme ...,https://nypost.com/2026/03/18/world-news/heres...
258,44,2026-03-18-14-00-00 +0000,wsj,He’s Leaving Citigroup to Be a CEO. Can He Lan...,https://www.wsj.com/finance/banking/hes-leavin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)