## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-06-07-33-07 +0000,bbc,Tributes to Buffy and Ted Lasso star Anthony H...,https://www.bbc.com/news/articles/cd0p0rz4n0mo...
1,2026-06-06-07-22-36 +0000,nyt,Iran Fired Drones Toward Strait of Hormuz With...,https://www.nytimes.com/2026/06/05/us/politics...
2,2026-06-06-07-08-01 +0000,nypost,Richard Gere says US is in ‘darkest moment’ he...,https://nypost.com/2026/06/06/us-news/richard-...
3,2026-06-06-07-06-43 +0000,bbc,Armenia braces for election as Russia piles pr...,https://www.bbc.com/news/articles/c3626n1epd5o...
4,2026-06-06-07-05-16 +0000,nypost,Passenger allegedly boards United Airlines fli...,https://nypost.com/2026/06/06/us-news/passenge...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2376/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
105       trump     26
60          new     12
718      market     12
301  california     11
221       putin     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,91
180,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,82
163,2026-06-05-18-17-24 +0000,nypost,Trump must ‘accept the reality’ there is no I...,https://nypost.com/2026/06/05/world-news/jack-...,71
188,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,71
78,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,91,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
48,60,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...
100,51,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
89,49,2026-06-05-21-51-59 +0000,nyt,"Amid Graham Platner Controversy, Where Does th...",https://www.nytimes.com/2026/06/05/us/politics...
51,45,2026-06-06-01-00-00 +0000,wsj,Kevin Warsh faces early Fed pressure as strong...,https://www.wsj.com/economy/central-banking/ke...
78,44,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...
6,39,2026-06-06-06-48-24 +0000,nypost,North Korean leader Kim Jong Un showcases new ...,https://nypost.com/2026/06/06/world-news/north...
21,37,2026-06-06-03-46-01 +0000,nypost,Minnesota driver accused of killing 82-year-ol...,https://nypost.com/2026/06/05/us-news/minnesot...
211,31,2026-06-05-15-58-12 +0000,nypost,Ex-Prince Andrew made money subletting 3 cotta...,https://nypost.com/2026/06/05/world-news/ex-pr...
101,31,2026-06-05-21-27-00 +0000,wsj,Carnage in Chip Stocks Hits Extra Hard in Top-...,https://www.wsj.com/finance/stocks/carnage-in-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)