## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-12-55-00 +0000,wsj,Producer-Price Inflation Accelerated Last Month,https://www.wsj.com/economy/central-banking/pr...
1,2026-09-10-12-54-28 +0000,nyt,Oil Prices Surge as Fighting in Middle East Es...,https://www.nytimes.com/2026/09/10/business/oi...
2,2026-09-10-12-51-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
3,2026-09-10-12-46-35 +0000,bbc,Russia to open more cultural centres in Africa...,https://www.bbc.co.uk/news/articles/c17j90jg0p...
4,2026-09-10-12-45-52 +0000,nypost,Wholesale inflation rises by most in 3 months ...,https://nypost.com/2026/09/10/business/wholesa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2341/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
215       trump     66
560         new     23
232  convention     20
226         war     18
405          ai     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
155,2026-09-10-05-35-19 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...,174
179,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...,170
65,2026-09-10-10-55-00 +0000,wsj,There were scores of empty seats at the RNC co...,https://www.wsj.com/politics/if-trump-cant-fil...,151
160,2026-09-10-05-09-24 +0000,nyt,Republican Senate Candidates Avoid Tariffs and...,https://www.nytimes.com/2026/09/09/us/politics...,143
318,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
155,174,2026-09-10-05-35-19 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...
179,104,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...
197,85,2026-09-10-01-54-25 +0000,nyt,"“We gave you no tax on tips, no tax on overtim...",https://www.nytimes.com/live/2026/09/09/us/rnc...
312,77,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
318,71,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
377,65,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
208,60,2026-09-10-01-23-42 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
215,57,2026-09-10-01-00-00 +0000,wsj,The Fed’s next rate decision could hinge on Fr...,https://www.wsj.com/economy/central-banking/in...
185,56,2026-09-10-02-48-00 +0000,wsj,The Trump administration is proposing eliminat...,https://www.wsj.com/us-news/trump-administrati...
294,50,2026-09-09-21-10-00 +0000,wsj,"U.S. Stocks Fall as War Escalation, Oil Spike ...",https://www.wsj.com/finance/stocks/u-s-stocks-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)