## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-15-17-29-16 +0000,bbc,Polls open on Thursday for the Makerfield by-e...,https://www.bbc.com/news/videos/c2lyjvxvdwno?a...
1,2026-06-15-17-28-06 +0000,nypost,Millionaire with ties to UK royal family accus...,https://nypost.com/2026/06/15/world-news/milli...
2,2026-06-15-17-26-27 +0000,wapo,Israelis denounce Trump’s deal with Iran,https://www.washingtonpost.com/world/2026/06/1...
3,2026-06-15-17-25-15 +0000,bbc,South African jazz legend Abdullah Ibrahim die...,https://www.bbc.com/news/articles/cy5vngrq3q5o...
4,2026-06-15-17-24-15 +0000,cbc,Owners of Santo Domingo nightclub to stand tri...,https://www.cbc.ca/news/world/santo-domingo-ni...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
23    iran     49
22    deal     41
21   trump     35
252  world     14
150   will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
99,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...,207
73,2026-06-15-14-59-22 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,177
259,2026-06-14-21-36-06 +0000,nypost,Trump announces US and Iran have reached peace...,https://nypost.com/2026/06/14/world-news/trump...,174
5,2026-06-15-17-22-13 +0000,nyt,Iran War Live Updates: U.S. and Iran Sign Prel...,https://www.nytimes.com/live/2026/06/15/world/...,163
78,2026-06-15-14-41-16 +0000,nypost,Why Strait of Hormuz still hasn’t reopened to ...,https://nypost.com/2026/06/15/world-news/why-s...,158

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
99,207,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...
92,66,2026-06-15-14-17-00 +0000,wsj,"A rowdy, controversial evening of mixed-martia...",https://www.wsj.com/arts-culture/books/trump-u...
137,62,2026-06-15-12-15-46 +0000,nypost,Video shows helicopter in crash that killed Ol...,https://nypost.com/2026/06/15/world-news/video...
151,61,2026-06-15-11-12-33 +0000,nypost,Britain will ban under-16s from using social m...,https://nypost.com/2026/06/15/world-news/brita...
199,48,2026-06-15-08-00-00 +0000,cbc,"War, sports collide as Iran's World Cup kicks ...",https://www.cbc.ca/news/world/world-cup-iran-l...
180,39,2026-06-15-09-52-21 +0000,cbc,"Russian attacks kill 11 across Ukraine, set ce...",https://www.cbc.ca/news/world/kyiv-cathedral-r...
28,35,2026-06-15-16-41-06 +0000,nypost,Beloved ABC New York anchor Bill Ritter reveal...,https://nypost.com/2026/06/15/media/abc-new-yo...
169,32,2026-06-15-10-08-42 +0000,nypost,"Israel refuses to leave Lebanon, vows to hit I...",https://nypost.com/2026/06/15/world-news/israe...
275,31,2026-06-14-19-44-00 +0000,wsj,"Sen. Mitch McConnell (R., Ky.) has been admitt...",https://www.wsj.com/politics/policy/sen-mitch-...
14,31,2026-06-15-17-10-30 +0000,bbc,Norwegian crown princess's son found guilty of...,https://www.bbc.com/news/articles/cly9d10l5p4o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)