## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-06-18-47-46 +0000,nyt,Live Updates: Germany’s Far Right Has Big Lead...,https://www.nytimes.com/live/2026/09/06/world/...
1,2026-09-06-18-47-42 +0000,nypost,How Republicans suddenly found themselves figh...,https://nypost.com/2026/09/06/us-news/how-repu...
2,2026-09-06-18-38-49 +0000,nypost,Amazon Boeing 767 jet crashes at Miami airport...,https://nypost.com/2026/09/06/us-news/amazon-b...
3,2026-09-06-18-33-50 +0000,bbc,Zelensky says he expects war to continue into ...,https://www.bbc.co.uk/news/articles/c6248nvqy8...
4,2026-09-06-18-32-53 +0000,bbc,AfD celebrate projected win in Saxony-Anhalt,https://www.bbc.co.uk/news/videos/c5yegd6ldy6o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2454/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
84     trump     23
30        he     12
341  ukraine     12
77      iran     11
136      new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
136,2026-09-06-07-22-19 +0000,nypost,Trump’s MAGA super PAC pours $10M into Ken Pax...,https://nypost.com/2026/09/06/us-news/trumps-s...,63
167,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,63
17,2026-09-06-17-48-16 +0000,nypost,Mike Lawler recounts how he stood up to Trump ...,https://nypost.com/2026/09/06/us-news/mike-law...,60
18,2026-09-06-17-44-24 +0000,nypost,Trump asks Supreme Court to allow mail-in ball...,https://nypost.com/2026/09/06/us-news/trump-re...,58
50,2026-09-06-15-17-00 +0000,wsj,As President Trump’s approval rating hovers ne...,https://www.wsj.com/politics/in-trumps-second-...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
136,63,2026-09-06-07-22-19 +0000,nypost,Trump’s MAGA super PAC pours $10M into Ken Pax...,https://nypost.com/2026/09/06/us-news/trumps-s...
44,54,2026-09-06-15-43-44 +0000,chitri,US envoys Witkoff and Kushner hold talks in Uk...,https://www.chicagotribune.com/2026/09/06/witk...
36,53,2026-09-06-16-21-42 +0000,nypost,Patrick Clancy spotted for first time since ex...,https://nypost.com/2026/09/06/us-news/patrick-...
21,36,2026-09-06-17-34-57 +0000,cbc,Far-right AfD party takes big lead in regional...,https://www.cbc.ca/news/world/afd-germany-elec...
154,36,2026-09-06-00-08-44 +0000,nypost,Iran plotting new Oct. 7-style attack against ...,https://nypost.com/2026/09/05/world-news/iran-...
41,32,2026-09-06-15-56-00 +0000,wsj,Retail investors hand control of stock portfol...,https://www.wsj.com/politics/policy/retail-inv...
45,27,2026-09-06-15-40-58 +0000,nypost,Hurricane Marie sparks mass flooding in Seal B...,https://nypost.com/2026/09/06/us-news/hurrican...
43,26,2026-09-06-15-48-28 +0000,cbc,Infantino to stand for re-election as FIFA pre...,https://www.cbc.ca/sports/soccer/fifa-infantin...
18,25,2026-09-06-17-44-24 +0000,nypost,Trump asks Supreme Court to allow mail-in ball...,https://nypost.com/2026/09/06/us-news/trump-re...
60,25,2026-09-06-14-03-52 +0000,cbc,Woman found alive in home destroyed by Nepal f...,https://www.cbc.ca/news/world/nepal-woman-foun...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)