## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-20-00-16-42 +0000,nypost,Mutant ‘super pig’ population spirals out of c...,https://nypost.com/2026/05/19/world-news/mutan...
1,2026-05-20-00-13-37 +0000,bbc,Thomas Massie loses to Trump-backed challenger...,https://www.bbc.com/news/articles/cwy2vw8j0ddo...
2,2026-05-20-00-13-00 +0000,wsj,Teen Suspects in San Diego Mosque Shooting Lik...,https://www.wsj.com/us-news/teen-suspects-in-s...
3,2026-05-20-00-11-27 +0000,bbc,Woman dies after falling into uncovered New Yo...,https://www.bbc.com/news/articles/cy02pzxejyno...
4,2026-05-20-00-10-23 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/19/us/mid...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2649/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
13        trump     60
110        iran     26
31          new     19
16   republican     18
41       senate     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...,231
10,2026-05-19-23-59-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,168
9,2026-05-20-00-00-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...,157
390,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,141
49,2026-05-19-23-00-49 +0000,nyt,Senate Votes to Take Up Measure to Force Trump...,https://www.nytimes.com/2026/05/19/us/politics...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,231,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...
9,79,2026-05-20-00-00-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...
229,67,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...
2,58,2026-05-20-00-13-00 +0000,wsj,Teen Suspects in San Diego Mosque Shooting Lik...,https://www.wsj.com/us-news/teen-suspects-in-s...
205,54,2026-05-19-18-03-38 +0000,latimes,Hilton and Becerra lead in a tightening race i...,https://www.latimes.com/california/story/2026-...
71,52,2026-05-19-22-16-49 +0000,nypost,LA City Council cuts new deal on Olympic wage ...,https://nypost.com/2026/05/19/us-news/la-counc...
146,52,2026-05-19-20-33-16 +0000,nypost,Wall Street titans fail to stand up to Mamdani...,https://nypost.com/2026/05/19/business/wall-st...
168,49,2026-05-19-19-32-22 +0000,bbc,Ebola outbreak may be spreading faster than fi...,https://www.bbc.com/news/articles/ceqp11gn1l8o...
390,42,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
289,40,2026-05-19-13-35-54 +0000,nypost,Starbucks Korea CEO fired after ‘Tank Day’ pro...,https://nypost.com/2026/05/19/world-news/starb...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)