## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-13-09-05-10 +0000,bbc,Dramatic insider warnings over AI fall flat wi...,https://www.bbc.co.uk/news/articles/cq635037g1...
1,2026-09-13-09-03-37 +0000,nyt,"As Fears of A.I. Catastrophe Magnify, Washingt...",https://www.nytimes.com/2026/09/13/us/politics...
2,2026-09-13-09-03-30 +0000,nyt,Inside the $440 Million Collapse of Guidepost ...,https://www.nytimes.com/2026/09/13/business/gu...
3,2026-09-13-09-03-29 +0000,nyt,What to Expect at the 2026 Emmy Awards,https://www.nytimes.com/2026/09/13/business/me...
4,2026-09-13-09-03-20 +0000,nyt,Every Word My Employee Writes Reeks of A.I.,https://www.nytimes.com/2026/09/13/business/em...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2674/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     21
46    iran     10
445  calls      7
107    war      7
118    out      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
105,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,64
51,2026-09-13-02-00-00 +0000,wsj,Trump insulted Texas Attorney General Ken Paxt...,https://www.wsj.com/politics/elections/republi...,54
162,2026-09-12-12-19-58 +0000,nypost,Trump claims Iran-backed Houthis don’t want to...,https://nypost.com/2026/09/12/us-news/trump-op...,54
150,2026-09-12-13-56-20 +0000,bbc,A united Ireland would be 'fantastic' says Tru...,https://www.bbc.co.uk/news/articles/cy0zvx15ry...,47
135,2026-09-12-16-02-54 +0000,chitri,President Donald Trump touches a nerve while i...,https://www.chicagotribune.com/2026/09/12/dona...,44

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
105,64,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
112,37,2026-09-12-18-42-25 +0000,nypost,Attack that closed key Saudi pipeline blamed o...,https://nypost.com/2026/09/12/world-news/attac...
51,33,2026-09-13-02-00-00 +0000,wsj,Trump insulted Texas Attorney General Ken Paxt...,https://www.wsj.com/politics/elections/republi...
168,31,2026-09-12-11-00-00 +0000,missionlocal,"For years, one of S.F.’s oldest barbershops ha...",https://missionlocal.org/2026/09/sf-shears-bar...
133,28,2026-09-12-16-16-16 +0000,nypost,"8 killed, dozens wounded in Russian strikes on...",https://nypost.com/2026/09/12/world-news/8-kil...
61,26,2026-09-13-00-13-06 +0000,nypost,Waymo calls cops on teen riders after detectin...,https://nypost.com/2026/09/12/us-news/waymo-ca...
156,25,2026-09-12-13-00-48 +0000,nypost,Iranians looking to use captured US Navy drone...,https://nypost.com/2026/09/12/us-news/iranians...
160,23,2026-09-12-12-47-51 +0000,nyt,"Why Mokha, Historic Port That Shaped the Coffe...",https://www.nytimes.com/2026/09/12/world/middl...
141,23,2026-09-12-15-09-55 +0000,bbc,Death toll from Philippines ferry fire rises t...,https://www.bbc.co.uk/news/articles/cwyz755yeg...
93,23,2026-09-12-20-51-49 +0000,nypost,Lindsay Clancy case eerily similar to bipolar ...,https://nypost.com/2026/09/12/us-news/lindsay-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)