## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-02-42-43 +0000,nypost,Republicans pile on James Talarico after he qu...,https://nypost.com/2026/09/15/us-news/republic...
1,2026-09-16-02-40-51 +0000,bbc,Japan to charge rescue fee on Mount Fuji durin...,https://www.bbc.co.uk/news/articles/cw8r6mvjdv...
2,2026-09-16-02-39-07 +0000,latimes,Navy sailor admits to selling fentanyl-laced p...,https://www.latimes.com/california/story/2026-...
3,2026-09-16-02-38-56 +0000,nyt,House Directs Trump to Halt War With Iran or S...,https://www.nytimes.com/2026/09/15/us/election...
4,2026-09-16-02-37-34 +0000,nyt,"For China, a Mock A.I. Attack on WeChat Signal...",https://www.nytimes.com/2026/09/11/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2500/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
32   trump     48
45     new     27
128     ai     25
35    iran     22
130  court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,210
310,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,142
309,2026-09-15-13-54-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,137
113,2026-09-15-21-16-25 +0000,chitri,Illinois Democrats cheer Supreme Court mail-in...,https://www.chicagotribune.com/2026/09/15/supr...,130
211,2026-09-15-18-34-00 +0000,wsj,"President Trump promised $5,000 to every Ameri...",https://www.wsj.com/politics/policy/republican...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,210,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
310,94,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
84,66,2026-09-15-22-40-00 +0000,nypost,Meet Anthropic CEO Dario Amodei’s handpicked s...,https://nypost.com/2026/09/15/business/anthrop...
182,63,2026-09-15-19-36-30 +0000,nypost,10-year Treasury yield hits highest level sinc...,https://nypost.com/2026/09/15/business/10-year...
61,56,2026-09-15-23-30-00 +0000,wsj,American business owners are grappling with a ...,https://www.wsj.com/business/american-business...
91,52,2026-09-15-22-15-45 +0000,nypost,Senate fails to advance Clarity Act in blow to...,https://nypost.com/2026/09/15/business/senate-...
37,51,2026-09-16-00-34-32 +0000,nypost,Plot forms against California tech companies w...,https://nypost.com/2026/09/15/us-news/silicon-...
222,47,2026-09-15-18-14-00 +0000,wsj,Nick Reiner Won’t Face Death Penalty if Convic...,https://www.wsj.com/us-news/law/l-a-district-a...
331,42,2026-09-15-12-49-55 +0000,cbc,Canada's 4 largest airports to be opened up to...,https://www.cbc.ca/news/politics/carney-airpor...
87,41,2026-09-15-22-39-00 +0000,wsj,The Kennedy Center’s board voted on Tuesday to...,https://www.wsj.com/us-news/law/trumps-name-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)