## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-01-15-20 +0000,nyt,Iran War Live Updates: Missile Attack Kills at...,https://www.nytimes.com/live/2026/03/18/world/...
1,2026-03-19-01-14-01 +0000,nypost,Inside the creepy California lair where Cesar ...,https://nypost.com/2026/03/18/us-news/inside-t...
2,2026-03-19-01-12-01 +0000,nyt,Pakistan Pauses Afghanistan Airstrikes for Eid,https://www.nytimes.com/2026/03/18/world/asia/...
3,2026-03-19-01-10-47 +0000,nyt,Bondi Doesn’t Commit to Deposition With House ...,https://www.nytimes.com/2026/03/18/us/politics...
4,2026-03-19-01-00-00 +0000,wsj,A U.S. Citizen Now Runs Mexico’s Top Drug Cart...,https://www.wsj.com/world/americas/mexican-dru...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2609/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     60
1       war     38
241   trump     33
16   chavez     30
15    cesar     27

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
339,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,167
32,2026-03-19-00-05-30 +0000,nyt,Senate G.O.P. Again Blocks Bid to Stop Iran Wa...,https://www.nytimes.com/2026/03/18/us/politics...,156
236,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,156
374,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...,156
227,2026-03-18-17-07-48 +0000,nyt,Trump’s Next Decision in War: Whether to Retri...,https://www.nytimes.com/2026/03/17/us/politics...,154

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
339,167,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...
7,97,2026-03-19-00-56-43 +0000,bbc,US civil rights leader Cesar Chavez accused of...,https://www.bbc.com/news/articles/cp8r8rggxmmo...
130,85,2026-03-18-21-06-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
374,58,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...
90,51,2026-03-18-22-33-50 +0000,wapo,Oil prices climb again after strikes in crucia...,https://www.washingtonpost.com/business/2026/0...
316,49,2026-03-18-13-01-27 +0000,nyt,Illinois Primary Election Takeaways: Stratton ...,https://www.nytimes.com/2026/03/18/us/election...
195,46,2026-03-18-18-41-58 +0000,nyt,"He Lost a Leg for Russia. Then, He Says, His C...",https://www.nytimes.com/2026/03/18/world/europ...
436,44,2026-03-18-01-23-59 +0000,latimes,California immigrant truckers face license cri...,https://www.latimes.com/california/story/2026-...
94,44,2026-03-18-22-27-58 +0000,nypost,Ex-NYC Mayor Bill de Blasio finally admits ‘de...,https://nypost.com/2026/03/18/us-news/bill-de-...
250,40,2026-03-18-16-47-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)