## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-21-15-22 +0000,nyt,Utah Children’s Book Author Who Poisoned Husba...,https://www.nytimes.com/2026/05/13/us/kouri-ri...
1,2026-05-13-21-14-45 +0000,bbc,Israeli strikes in southern Lebanon kill 22 pe...,https://www.bbc.com/news/articles/c1k2zekj8y9o...
2,2026-05-13-21-13-14 +0000,bbc,Alberta judge tosses out petition for province...,https://www.bbc.com/news/articles/clypn8py4zwo...
3,2026-05-13-21-13-10 +0000,nyt,Israel Says Netanyahu Made a Secret Trip to U....,https://www.nytimes.com/2026/05/13/world/middl...
4,2026-05-13-21-11-51 +0000,nyt,France Clears Cruise Ship to Sail After Norovi...,https://www.nytimes.com/2026/05/13/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
66   trump     55
149  china     25
112    new     22
102   iran     18
103    war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...,128
187,2026-05-13-15-04-52 +0000,nyt,Trump Is in China as Iran War Continues With N...,https://www.nytimes.com/2026/05/13/world/middl...,122
154,2026-05-13-16-53-28 +0000,nyt,"For Trump, the Iran War Looms Over China Summit",https://www.nytimes.com/2026/05/13/us/politics...,120
364,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,114
342,2026-05-13-01-50-00 +0000,wsj,Senior leaders in the White House concluded th...,https://www.wsj.com/politics/policy/inside-mar...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,128,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...
26,97,2026-05-13-20-51-00 +0000,wsj,The Senate confirmed Kevin Warsh as the Fed’s ...,https://www.wsj.com/economy/central-banking/ke...
343,56,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
116,49,2026-05-13-18-19-07 +0000,nyt,Alex Murdaugh Murder Convictions Overturned by...,https://www.nytimes.com/2026/05/13/us/murdaugh...
355,46,2026-05-13-00-36-41 +0000,cbc,Sexual violence was 'deliberate tactic' and in...,https://www.cbc.ca/news/world/sexual-violence-...
5,45,2026-05-13-21-10-00 +0000,wsj,Vice President JD Vance delivered an ultimatum...,https://www.wsj.com/politics/policy/trump-jd-v...
237,43,2026-05-13-13-00-00 +0000,missionlocal,One S.F. judge candidate is out raising her op...,https://missionlocal.org/2026/05/s-f-judge-can...
99,39,2026-05-13-18-58-39 +0000,nypost,Immigrant-led business group builds $1M war ch...,https://nypost.com/2026/05/13/business/mamdani...
364,39,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
34,38,2026-05-13-20-43-00 +0000,wsj,Boston Fed President Susan Collins flagged the...,https://www.wsj.com/economy/central-banking/bo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)