## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-08-19-31 +0000,nyt,Mideast Live Updates: New Round of U.S.-Iran T...,https://www.nytimes.com/live/2026/06/21/world/...
1,2026-06-21-08-10-26 +0000,nypost,FBI captures $1.2B Medicare fraud fugitive in ...,https://nypost.com/2026/06/21/us-news/fbi-most...
2,2026-06-21-08-00-00 +0000,cbc,Governors general can no longer bill governmen...,https://www.cbc.ca/news/politics/governor-gene...
3,2026-06-21-08-00-00 +0000,cbc,The Conservative Party recently released an AI...,https://www.cbc.ca/news/politics/conservative-...
4,2026-06-21-07-56-57 +0000,bbc,"'Uncertainty costs us', says former top civil ...",https://www.bbc.com/news/videos/ckg0d6xx0pyo?a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
196  trump     12
303  world     10
3      new      9
5     iran      9
304    cup      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
34,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...,49
58,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...,46
134,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...,44
55,2026-06-20-22-34-00 +0000,wsj,"Vance Heads to Peace Talks, After Iran Says It...",https://www.wsj.com/world/middle-east/fighting...,39
16,2026-06-21-04-34-00 +0000,bbc,US-Iran talks to begin in Switzerland as Tehra...,https://www.bbc.com/news/articles/cwyekkwm1mmo...,37

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
34,49,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...
58,46,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...
134,37,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...
101,29,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...
44,25,2026-06-20-23-18-55 +0000,bbc,Why an AI company cleaned my New York City apa...,https://www.bbc.com/news/articles/cpwerjy20kyo...
90,25,2026-06-20-17-45-53 +0000,latimes,Newsom and L.A. declare state of emergency as ...,https://www.latimes.com/business/story/2026-06...
15,22,2026-06-21-04-40-36 +0000,nypost,Florida man tries to steal medical helicopter ...,https://nypost.com/2026/06/21/us-news/florida-...
70,21,2026-06-20-20-18-32 +0000,nypost,"Conflict erupts in Lebanon between Israel, Hez...",https://nypost.com/2026/06/20/world-news/confl...
54,21,2026-06-20-22-41-34 +0000,wapo,Cyclist arrested at Reflecting Pool is former ...,https://www.washingtonpost.com/nation/2026/06/...
48,20,2026-06-20-23-07-46 +0000,nypost,UK Prime Minister Keir Starmer set to resign a...,https://nypost.com/2026/06/20/world-news/uk-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)