## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-16-12-03-06 +0000,nyt,Iran War Live Updates: Israel Expands Lebanon ...,https://www.nytimes.com/live/2026/03/16/world/...
1,2026-03-16-12-03-04 +0000,nyt,Trump’s Threat to Delay Summit With Xi Casts N...,https://www.nytimes.com/2026/03/16/world/middl...
2,2026-03-16-12-00-00 +0000,wsj,JBS Beef-Plant Workers Begin Industry’s Larges...,https://www.wsj.com/business/jbs-beef-plant-wo...
3,2026-03-16-11-59-45 +0000,bbc,Starmer announces £53m support to help with he...,https://www.bbc.com/news/articles/cp9mgpzn901o...
4,2026-03-16-11-58-42 +0000,bbc,"Ecuador deploys 75,000 soldiers and police to ...",https://www.bbc.com/news/articles/cp32vy321r7o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     34
8    trump     25
1      war     22
9      oil     13
246   will     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-16-12-03-06 +0000,nyt,Iran War Live Updates: Israel Expands Lebanon ...,https://www.nytimes.com/live/2026/03/16/world/...,117
197,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...,103
75,2026-03-16-08-52-15 +0000,nypost,Trump ‘thrilled’ by FCC chair Brendan Carr’s t...,https://nypost.com/2026/03/16/us-news/trump-th...,101
138,2026-03-16-01-19-41 +0000,wapo,Trump backs FCC chief’s threat to broadcasters...,https://www.washingtonpost.com/business/2026/0...,97
35,2026-03-16-10-58-14 +0000,wapo,Drone hits Dubai airport as Iran targets comme...,https://www.washingtonpost.com/world/2026/03/1...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,117,2026-03-16-12-03-06 +0000,nyt,Iran War Live Updates: Israel Expands Lebanon ...,https://www.nytimes.com/live/2026/03/16/world/...
229,44,2026-03-15-14-19-14 +0000,nypost,Americans will feel pain of high gas prices fo...,https://nypost.com/2026/03/15/us-news/oil-pric...
37,39,2026-03-16-10-58-00 +0000,wsj,The CIA turned to a former Chevron executive t...,https://www.wsj.com/politics/a-rare-peek-behin...
208,38,2026-03-15-17-06-25 +0000,nypost,Captain of Iranian women’s soccer team is late...,https://nypost.com/2026/03/15/world-news/capta...
104,34,2026-03-16-05-14-45 +0000,bbc,'A new norm': BBC visits Doha market starting ...,https://www.bbc.com/news/videos/cp32gez414yo?a...
5,32,2026-03-16-11-55-04 +0000,startribune,Fears of a global energy crisis rise as Iran k...,https://www.startribune.com/iran-hits-gulf-nei...
62,31,2026-03-16-09-29-01 +0000,bbc,Kpop Demon Hunters wins Oscars for best anima...,https://www.bbc.com/news/articles/cvg823zkx0go...
175,30,2026-03-15-21-09-33 +0000,cbc,Israel says Michigan synagogue attacker was br...,https://www.cbc.ca/news/world/michigan-synagog...
230,29,2026-03-15-14-12-56 +0000,nypost,Maine Dem Senate hopeful Graham Platner done a...,https://nypost.com/2026/03/15/us-news/maine-de...
137,27,2026-03-16-01-23-30 +0000,nypost,Trump warns of ‘very bad’ future if NATO allie...,https://nypost.com/2026/03/15/us-news/trump-wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)