## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-15-05-20 +0000,startribune,High winds knock out power to thousands as who...,https://www.startribune.com/mn-weather-near-me...
1,2026-03-13-15-02-57 +0000,bbc,France returns sacred 'talking drum' looted du...,https://www.bbc.com/news/articles/cvg3yv2e9p1o...
2,2026-03-13-15-02-16 +0000,wapo,Suspect in synagogue crash lost family in Isra...,https://www.washingtonpost.com/nation/2026/03/...
3,2026-03-13-15-01-36 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: H...,https://www.nytimes.com/live/2026/03/13/world/...
4,2026-03-13-15-01-00 +0000,wsj,The Commerce Department said GDP grew at just ...,https://www.wsj.com/economy/consumers/economy-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
31    iran     59
33     war     37
173  trump     29
44     oil     21
217    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-03-13-15-01-36 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: H...,https://www.nytimes.com/live/2026/03/13/world/...,236
363,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...,173
287,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,170
57,2026-03-13-13-41-35 +0000,bbc,US eases Russia oil sanctions as Iran war push...,https://www.bbc.com/news/articles/clyzj3g3pygo...,170
192,2026-03-13-05-07-14 +0000,nypost,Trump says Iran’s new Supreme Leader Mojtaba K...,https://nypost.com/2026/03/13/us-news/trump-sa...,148

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,236,2026-03-13-15-01-36 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: H...,https://www.nytimes.com/live/2026/03/13/world/...
192,89,2026-03-13-05-07-14 +0000,nypost,Trump says Iran’s new Supreme Leader Mojtaba K...,https://nypost.com/2026/03/13/us-news/trump-sa...
340,82,2026-03-12-18-14-00 +0000,wsj,When Kash Patel said in one of his first video...,https://www.wsj.com/politics/policy/ufc-fighte...
43,75,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
144,62,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
57,53,2026-03-13-13-41-35 +0000,bbc,US eases Russia oil sanctions as Iran war push...,https://www.bbc.com/news/articles/clyzj3g3pygo...
109,40,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
213,36,2026-03-13-02-00-00 +0000,wsj,Illinois Gov. JB Pritzker’s deep financial inv...,https://www.wsj.com/politics/policy/illinois-s...
135,35,2026-03-13-10-00-00 +0000,nypost,Pentagon AI chief Emil Michael says it’s ‘tota...,https://nypost.com/2026/03/13/business/pentago...
140,35,2026-03-13-10-00-00 +0000,nypost,‘Like our Super Bowl’: NYC’s hero St. Patrick’...,https://nypost.com/2026/03/13/lifestyle/nyc-st...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)