## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-14-18-23 +0000,bbc,Large-scale Ukrainian drone attack kills three...,https://www.bbc.com/news/articles/c5ye480kxpmo...
1,2026-05-17-14-16-00 +0000,bbc,Trump-backed challenger defeats Republican sen...,https://www.bbc.com/news/articles/cx21d4pxq23o...
2,2026-05-17-14-02-27 +0000,cbc,U.A.E. reports drone strike at nuclear power p...,https://www.cbc.ca/news/world/uae-drone-strike...
3,2026-05-17-14-00-00 +0000,nypost,Mexican Senator linked to Sinaloa Cartel repor...,https://nypost.com/2026/05/17/us-news/mexican-...
4,2026-05-17-13-58-38 +0000,nyt,"Wave of Ukrainian Strikes Kills at Least 4, Ru...",https://www.nytimes.com/2026/05/17/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2653/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
10        trump     32
247       world     12
225      killed      9
190  eurovision      8
20       strike      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
27,2026-05-17-11-08-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,95
83,2026-05-17-02-56-27 +0000,nypost,Republican Sen. Bill Cassidy — who voted to co...,https://nypost.com/2026/05/16/us-news/la-repub...,84
77,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...,78
59,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...,74
176,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
27,95,2026-05-17-11-08-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
77,46,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...
48,40,2026-05-17-09-04-10 +0000,nypost,At least 4 people killed in largest Ukrainian ...,https://nypost.com/2026/05/17/world-news/ukrai...
65,34,2026-05-17-08-00-00 +0000,cbc,Princess of Wales steps out on world stage — a...,https://www.cbc.ca/news/world/catherine-prince...
71,31,2026-05-17-06-48-51 +0000,nypost,Florida house sitter arrested weeks after alle...,https://nypost.com/2026/05/17/us-news/us-airma...
17,28,2026-05-17-12-52-26 +0000,nypost,Climate group reverses course on doomsday pred...,https://nypost.com/2026/05/17/us-news/trump-ce...
129,26,2026-05-16-22-25-58 +0000,nypost,Italian scuba divers weren’t authorized to div...,https://nypost.com/2026/05/16/world-news/veter...
7,25,2026-05-17-13-39-00 +0000,wsj,WHO Declares Global Health Emergency After Ebo...,https://www.wsj.com/world/africa/who-declares-...
137,25,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...
167,25,2026-05-16-17-01-10 +0000,nyt,Trump Calls Xi a ‘Friend.’ But He Left China W...,https://www.nytimes.com/2026/05/16/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)