## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-15-04-07-02 +0000,nyt,"What is Zhongnanhai, the Secretive Beijing Com...",https://www.nytimes.com/2026/05/14/world/asia/...
1,2026-05-15-04-06-28 +0000,nyt,5 Key Moments During the California Governor D...,https://www.nytimes.com/2026/05/15/us/californ...
2,2026-05-15-04-05-30 +0000,nypost,North Carolina couple accused of causing vultu...,https://nypost.com/2026/05/15/us-news/north-ca...
3,2026-05-15-04-01-19 +0000,nyt,Aging Palestinian Leader Boosting His Son’s Po...,https://www.nytimes.com/2026/05/15/world/middl...
4,2026-05-15-04-01-13 +0000,nyt,Inside the Congolese Hotel Where Trump Deporte...,https://www.nytimes.com/2026/05/15/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5    trump     61
47   china     30
7       xi     24
132    new     16
632   iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
239,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...,173
37,2026-05-15-01-30-15 +0000,nypost,Trump says China will ‘invest hundreds of bill...,https://nypost.com/2026/05/14/us-news/china-wi...,150
119,2026-05-14-21-36-36 +0000,nyt,Oil Prices Waver as Trump Meets China’s Xi to ...,https://www.nytimes.com/2026/05/14/business/oi...,148
280,2026-05-14-14-29-21 +0000,nyt,Beijing Tightens Security As Trump and Xi Meet...,https://www.nytimes.com/2026/05/13/world/asia/...,138
364,2026-05-14-09-12-03 +0000,nypost,"Trump, Xi agree Strait of Hormuz must stay ope...",https://nypost.com/2026/05/14/world-news/trump...,136

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
239,173,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...
364,75,2026-05-14-09-12-03 +0000,nypost,"Trump, Xi agree Strait of Hormuz must stay ope...",https://nypost.com/2026/05/14/world-news/trump...
26,66,2026-05-15-02-08-00 +0000,wsj,New York Governor Says Fewer Second Homes to P...,https://www.wsj.com/us-news/n-y-gov-hochul-say...
135,63,2026-05-14-21-04-21 +0000,nypost,Gavin Newsom speaks out on ex-aide’s guilty pl...,https://nypost.com/2026/05/14/us-news/gavin-ne...
352,52,2026-05-14-10-00-00 +0000,latimes,Hiltzik: Trump's 'weird war' on wind power wil...,https://www.latimes.com/business/story/2026-05...
158,44,2026-05-14-20-23-32 +0000,nyt,"Cerebras, A.I. Chip Maker, Rises 89% in Market...",https://www.nytimes.com/2026/05/14/technology/...
299,43,2026-05-14-13-36-51 +0000,nypost,Taiwan becomes flashpoint of Trump-Xi summit a...,https://nypost.com/2026/05/14/us-news/taiwan-b...
198,41,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
254,37,2026-05-14-15-40-37 +0000,startribune,Analysis: Wild’s collapse in playoff loss was ...,https://www.startribune.com/minnesota-wild-los...
154,36,2026-05-14-20-33-21 +0000,cbc,Cuba suffers partial grid failure hours after ...,https://www.cbc.ca/news/world/cuba-grid-partia...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)