## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-17-21-54-20 +0000,nypost,Abdul El-Sayed slammed for ‘racist’ Columbia ...,https://nypost.com/2026/10/17/us-news/el-sayed...
1,2026-10-17-21-53-12 +0000,nypost,Landlords demand NYC socialite sell her $30M B...,https://nypost.com/2026/10/17/us-news/nyc-soci...
2,2026-10-17-21-52-25 +0000,nypost,Abdul El-Sayed remains close to terror-linked ...,https://nypost.com/2026/10/17/us-news/abdul-el...
3,2026-10-17-21-51-57 +0000,missionlocal,This is Ballhalla! Valkyries win first ever WN...,https://missionlocal.org/2026/10/valkyries-wnb...
4,2026-10-17-21-49-00 +0000,wsj,Violent Protests Rip Through Cities Across France,https://www.wsj.com/world/europe/violent-prote...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
85       trump     29
194        new     20
8           he     16
167     school     11
122  president     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...,111
166,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...,111
32,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...,108
184,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,103
13,2026-10-17-20-57-00 +0000,wsj,President Trump is halting implementation of m...,https://www.wsj.com/politics/policy/trump-waiv...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,111,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...
32,68,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...
184,63,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
87,42,2026-10-17-15-38-04 +0000,nypost,Pope Leo released from hospital 4 days after l...,https://nypost.com/2026/10/17/world-news/who-r...
113,39,2026-10-17-12-46-51 +0000,cbc,Young protester's hand severed amid violent pr...,https://www.cbc.ca/news/world/livestory/france...
20,36,2026-10-17-20-43-00 +0000,wsj,Masked Israeli Settlers Attack European Diplom...,https://www.wsj.com/world/middle-east/masked-i...
66,36,2026-10-17-17-53-54 +0000,nypost,Hero dad who killed Oregon shooter stalked gun...,https://nypost.com/2026/10/17/us-news/hero-dad...
0,30,2026-10-17-21-54-20 +0000,nypost,Abdul El-Sayed slammed for ‘racist’ Columbia ...,https://nypost.com/2026/10/17/us-news/el-sayed...
60,30,2026-10-17-18-13-44 +0000,nypost,Billionaires’ tax getting dry-run in Californi...,https://nypost.com/2026/10/17/us-news/billiona...
154,26,2026-10-17-07-45-17 +0000,nypost,UK ambulance staff viewed medical records of e...,https://nypost.com/2026/10/17/world-news/willi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)