## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-19-26-33 +0000,nypost,"Iran is using Caspian Sea, highways and a rail...",https://nypost.com/2026/05/13/world-news/iran-...
1,2026-05-13-19-22-09 +0000,nyt,"Musk, Rubio, Hegseth: Who Is Traveling With Tr...",https://www.nytimes.com/2026/05/13/us/politics...
2,2026-05-13-19-20-47 +0000,nypost,4 California hospitals earn ‘D’ safety ratings...,https://nypost.com/2026/05/13/us-news/4-califo...
3,2026-05-13-19-20-41 +0000,nypost,$100K-per-week rental homes in Hamptons are em...,https://nypost.com/2026/05/13/business/100k-pe...
4,2026-05-13-19-19-51 +0000,nypost,Experts blast ‘distorted’ New York Times artic...,https://nypost.com/2026/05/13/us-news/experts-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2598/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14   trump     58
6    china     24
20     new     22
0     iran     19
333    war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...,129
331,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,127
143,2026-05-13-15-04-52 +0000,nyt,Trump Is in China as Iran War Continues With N...,https://www.nytimes.com/2026/05/13/world/middl...,124
100,2026-05-13-16-53-28 +0000,nyt,"For Trump, the Iran War Looms Over China Summit",https://www.nytimes.com/2026/05/13/us/politics...,124
281,2026-05-13-07-05-22 +0000,nyt,Here’s How Trump’s Trade War on China Ended Up...,https://www.nytimes.com/2026/05/13/business/tr...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,129,2026-05-13-17-00-12 +0000,bbc,"Trade, Iran and Taiwan on the agenda as Trump ...",https://www.bbc.com/news/articles/c1w28qw1e0xo...
18,89,2026-05-13-19-02-00 +0000,wsj,The Senate confirmed Kevin Warsh as the Fed’s ...,https://www.wsj.com/economy/central-banking/ke...
305,57,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
331,56,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
353,49,2026-05-12-22-09-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
320,47,2026-05-13-00-36-41 +0000,cbc,Sexual violence was 'deliberate tactic' and in...,https://www.cbc.ca/news/world/sexual-violence-...
310,47,2026-05-13-01-20-35 +0000,nypost,Cindy Burbank — who plans to drop out of gener...,https://nypost.com/2026/05/12/us-news/cindy-bu...
354,43,2026-05-12-22-08-43 +0000,nyt,Pentagon Puts Iran War Cost at $29 Billion as ...,https://www.nytimes.com/2026/05/12/us/politics...
52,38,2026-05-13-18-19-07 +0000,nyt,Alex Murdaugh Murder Convictions Overturned by...,https://www.nytimes.com/2026/05/13/us/murdaugh...
76,37,2026-05-13-17-40-27 +0000,nypost,Utah children’s author Kouri Richins pulls fac...,https://nypost.com/2026/05/13/us-news/utah-chi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)