## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-14-26-55 +0000,nypost,Health workers at the epicenter of Congo’s Ebo...,https://nypost.com/2026/06/07/world-news/healt...
1,2026-06-07-14-16-10 +0000,nypost,"Trump calls younger Khamenei ‘more rational,’ ...",https://nypost.com/2026/06/07/us-news/trump-ca...
2,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...
3,2026-06-07-14-12-44 +0000,nyt,Arab Gunman Kills One in Attack on Central Israel,https://www.nytimes.com/2026/06/07/world/middl...
4,2026-06-07-14-12-39 +0000,nypost,Russian drone hits nuclear fuel storage facili...,https://nypost.com/2026/06/07/world-news/russi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
93   world     15
10   trump     12
94     cup     12
16    iran      8
138    new      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...,64
145,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,50
11,2026-06-07-13-24-50 +0000,bbc,Iran's World Cup team lands in Mexico amid US ...,https://www.bbc.com/news/articles/c5yz3zdp3jqo...,46
65,2026-06-07-08-00-00 +0000,cbc,The FIFA World Cup is brought to you by Saudi ...,https://www.cbc.ca/radio/whatonearth/fifa-worl...,45
91,2026-06-07-01-16-24 +0000,nypost,Here are the best NYC bars to watch the ‘beaut...,https://nypost.com/2026/06/06/us-news/the-best...,45

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,64,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
2,35,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...
53,34,2026-06-07-09-02-06 +0000,nyt,Trump Says Iran Has Made a ‘Big’ Nuclear Promi...,https://www.nytimes.com/2026/06/07/us/politics...
63,32,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
128,25,2026-06-06-21-23-03 +0000,bbc,Lebanese general among three soldiers killed i...,https://www.bbc.com/news/articles/cj0g8jymg92o...
73,23,2026-06-07-05-09-14 +0000,nypost,Long Island’s Robert Moses State Park ramping ...,https://nypost.com/2026/06/07/us-news/long-isl...
81,23,2026-06-07-02-52-23 +0000,nypost,Family of killer California mom who slaughtere...,https://nypost.com/2026/06/06/us-news/family-o...
4,22,2026-06-07-14-12-39 +0000,nypost,Russian drone hits nuclear fuel storage facili...,https://nypost.com/2026/06/07/world-news/russi...
90,21,2026-06-07-01-24-29 +0000,nypost,Vaccine expert lusted after Northwell Health s...,https://nypost.com/2026/06/06/us-news/vaccine-...
7,20,2026-06-07-14-00-00 +0000,nypost,Die-hard Spencer Pratt supporters devastated b...,https://nypost.com/2026/06/07/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)