## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-09-14-11-55 +0000,bbc,Labour lose all seats on Kirklees Council,https://www.bbc.com/news/videos/cp8pk0g3gv4o?a...
1,2026-05-09-14-08-37 +0000,bbc,WHO chief reassures Tenerife residents ahead o...,https://www.bbc.com/news/articles/czr2vjmnlmpo...
2,2026-05-09-14-03-30 +0000,nyt,What to Know About the Hantavirus Outbreak on ...,https://www.nytimes.com/article/hantavirus-cru...
3,2026-05-09-14-00-00 +0000,nypost,Convicted rapist and murderer to soon be out o...,https://nypost.com/2026/05/09/us-news/convicte...
4,2026-05-09-14-00-00 +0000,nypost,Crazy fight pits AI boss worth $7.6B against h...,https://nypost.com/2026/05/09/us-news/socal-bi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2634/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
182     trump     27
47        new     20
590      iran     14
40      court     14
76   election     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
300,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,107
246,2026-05-08-18-38-40 +0000,nypost,Trump announces three-day Ukraine-Russia cease...,https://nypost.com/2026/05/08/us-news/trump-an...,75
131,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...,72
169,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...,69
243,2026-05-08-18-45-10 +0000,cbc,"Russia, Ukraine agree to 3-day ceasefire and p...",https://www.cbc.ca/news/world/russia-ukraine-c...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
300,107,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
50,59,2026-05-09-11-38-19 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...
169,55,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...
131,52,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
241,47,2026-05-08-18-51-17 +0000,nypost,California’s ‘abusive relationship’ with one-p...,https://nypost.com/2026/05/08/us-news/critics-...
10,46,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
207,41,2026-05-08-20-53-27 +0000,nypost,Oil spill uncovered off Iran’s central hub at ...,https://nypost.com/2026/05/08/us-news/oil-spil...
42,40,2026-05-09-12-00-00 +0000,nypost,‘Patient Zero’ in deadly hantavirus cruise shi...,https://nypost.com/2026/05/09/world-news/hanta...
109,39,2026-05-09-06-19-56 +0000,nyt,China’s Exports and Imports Set Records in Apr...,https://www.nytimes.com/2026/05/09/business/ch...
290,31,2026-05-08-16-12-08 +0000,nypost,"Lucky Strike snatched up local bowling alleys,...",https://nypost.com/2026/05/08/business/lucky-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)