## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...
1,2026-05-02-23-00-00 +0000,wsj,The Path to Student Loan Forgiveness Is Narrowing,https://www.wsj.com/personal-finance/the-path-...
2,2026-05-02-22-46-42 +0000,startribune,Frost open playoffs with 5-4 overtime victory ...,https://www.startribune.com/frost-open-playoff...
3,2026-05-02-22-43-27 +0000,nypost,Disney closing more attractions ahead of summe...,https://nypost.com/2026/05/02/us-news/disney-c...
4,2026-05-02-22-39-51 +0000,latimes,Raid on San Bernardino Sunshine Motel leads to...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     24
9      iran     13
117     new     12
10      war     11
196  spirit     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,69
0,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,65
99,2026-05-02-13-14-37 +0000,nyt,"As Iran War Reaches 60-Day Mark, Republicans i...",https://www.nytimes.com/2026/05/01/us/politics...,62
59,2026-05-02-17-48-47 +0000,nypost,Outrage as California vice mayor posts vile ‘d...,https://nypost.com/2026/05/02/us-news/californ...,56
88,2026-05-02-14-59-59 +0000,nyt,How Germany May Have Misjudged Trump’s Anger o...,https://www.nytimes.com/2026/05/02/world/europ...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,69,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...
111,38,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
32,36,2026-05-02-20-32-00 +0000,wsj,‘I Was Devastated.’ Spirit Passengers Rush to ...,https://www.wsj.com/lifestyle/travel/i-was-dev...
59,32,2026-05-02-17-48-47 +0000,nypost,Outrage as California vice mayor posts vile ‘d...,https://nypost.com/2026/05/02/us-news/californ...
144,31,2026-05-02-08-58-09 +0000,nypost,US warns shipping firms they could face sancti...,https://nypost.com/2026/05/02/world-news/us-wa...
41,29,2026-05-02-19-53-29 +0000,nypost,North West goes goth at LA pop-up to promote h...,https://nypost.com/2026/05/02/us-news/north-we...
159,29,2026-05-02-02-21-42 +0000,latimes,Thousands rally in L.A. for May Day to protest...,https://www.latimes.com/california/story/2026-...
57,28,2026-05-02-17-58-44 +0000,nyt,Supreme Court Asked to Restore Access to Abort...,https://www.nytimes.com/2026/05/02/us/politics...
100,26,2026-05-02-13-08-46 +0000,nypost,Gaza flotilla activists — including Greta Thun...,https://nypost.com/2026/05/02/world-news/gaza-...
68,25,2026-05-02-16-57-00 +0000,wsj,Spirit Airlines Is Shutting Down. Here’s What ...,https://www.wsj.com/business/airlines/if-you-b...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)