## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-18-10-01 +0000,nyt,Iran War Live Updates: Trump Delivers New Thre...,https://www.nytimes.com/live/2026/03/26/world/...
1,2026-03-26-18-09-22 +0000,nyt,Malaysia Says Iran Will Allow Its Ships to Pas...,https://www.nytimes.com/2026/03/26/world/asia/...
2,2026-03-26-18-07-50 +0000,nyt,"Under Carney, Canada Finally Hits NATO’s 2% Sp...",https://www.nytimes.com/2026/03/26/world/canad...
3,2026-03-26-18-06-31 +0000,nyt,Europeans Worry Russia Is Preparing to Deliver...,https://www.nytimes.com/2026/03/26/world/europ...
4,2026-03-26-18-05-41 +0000,cbc,Why regime change in Iran was never in the car...,https://www.cbc.ca/player/play/9.7142165?cmp=rss

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2636/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     70
4    trump     52
1      war     41
226    oil     14
182  court     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-26-18-10-01 +0000,nyt,Iran War Live Updates: Trump Delivers New Thre...,https://www.nytimes.com/live/2026/03/26/world/...,260
379,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...,225
81,2026-03-26-16-18-00 +0000,wsj,President Trump has told associates in recent ...,https://www.wsj.com/politics/elections/trump-t...,225
33,2026-03-26-17-39-06 +0000,wapo,"Iran rejects Trump proposal to end war, leavin...",https://www.washingtonpost.com/world/2026/03/2...,194
58,2026-03-26-16-54-14 +0000,latimes,"Trump projects confidence, claims Iran is 'beg...",https://www.latimes.com/world-nation/story/202...,187

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,260,2026-03-26-18-10-01 +0000,nyt,Iran War Live Updates: Trump Delivers New Thre...,https://www.nytimes.com/live/2026/03/26/world/...
361,65,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...
81,62,2026-03-26-16-18-00 +0000,wsj,President Trump has told associates in recent ...,https://www.wsj.com/politics/elections/trump-t...
242,60,2026-03-26-09-00-17 +0000,bbc,Chris Mason: How will the UK respond to US cou...,https://www.bbc.com/news/articles/c0q90kekw08o...
318,54,2026-03-25-22-58-00 +0000,wsj,RBA Warns Global Oil Shock Could Drive Up Infl...,https://www.wsj.com/economy/central-banking/rb...
97,48,2026-03-26-15-50-00 +0000,wsj,World governments were buried in public debt o...,https://www.wsj.com/economy/global/energy-pric...
203,45,2026-03-26-10-48-00 +0000,wsj,Surgeon-general nominee Dr. Casey Means lacks ...,https://www.wsj.com/politics/this-is-the-start...
167,41,2026-03-26-13-14-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
161,40,2026-03-26-13-24-00 +0000,wsj,Lawmakers accused each other Wednesday of bein...,https://www.wsj.com/politics/policy/lawmakers-...
392,39,2026-03-25-19-29-45 +0000,nypost,‘Big Tech invincibility is over:’ Historic soc...,https://nypost.com/2026/03/25/business/histori...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)