## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-24-19-04-05 +0000,nyt,Iran War Live Updates: U.S. and Iran Agree in ...,https://www.nytimes.com/live/2026/05/24/world/...
1,2026-05-24-19-04-04 +0000,nyt,Israeli Leader Says He and Trump Agree On Bloc...,https://www.nytimes.com/2026/05/24/world/middl...
2,2026-05-24-18-59-27 +0000,nyt,"With Big Decisions Ahead, the Supreme Court Co...",https://www.nytimes.com/2026/05/24/us/politics...
3,2026-05-24-18-56-47 +0000,nyt,U.S. and Iran Agree in Principle to Reopen the...,https://www.nytimes.com/2026/05/24/us/strait-o...
4,2026-05-24-18-54-13 +0000,nypost,Brainiac twin grads make history at prestigiou...,https://nypost.com/2026/05/24/us-news/brainiac...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2645/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0       iran     25
13     trump     22
95      deal     19
53     house     11
41  chemical     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
79,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...,135
169,2026-05-23-21-06-18 +0000,cbc,Deal with Iran to reopen Strait of Hormuz 'lar...,https://www.cbc.ca/news/world/strait-hormuz-ir...,93
144,2026-05-24-01-18-31 +0000,bbc,Trump says Iran deal 'largely negotiated' incl...,https://www.bbc.com/news/articles/crmp121z3z8o...,91
0,2026-05-24-19-04-05 +0000,nyt,Iran War Live Updates: U.S. and Iran Agree in ...,https://www.nytimes.com/live/2026/05/24/world/...,89
83,2026-05-24-11-14-00 +0000,wsj,Trump Says a Deal for Talks With Iran to End W...,https://www.wsj.com/world/middle-east/trump-an...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
79,135,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...
162,66,2026-05-23-22-34-04 +0000,nypost,Gunman who believed he was Jesus Christ opened...,https://nypost.com/2026/05/23/us-news/white-ho...
164,39,2026-05-23-22-14-35 +0000,nypost,Ukraine bracing for ‘significant air attack’ f...,https://nypost.com/2026/05/23/world-news/ukrai...
173,39,2026-05-23-20-45-32 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
8,38,2026-05-24-18-38-16 +0000,nypost,Orange County officials reveal ‘critical’ upda...,https://nypost.com/2026/05/24/us-news/oc-offic...
116,38,2026-05-24-09-00-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
54,32,2026-05-24-15-44-50 +0000,nypost,California governor candidate Xavier Becerra m...,https://nypost.com/2026/05/24/us-news/californ...
44,27,2026-05-24-16-11-11 +0000,nypost,Ex-Dem NY governor gives Hochul history lesson...,https://nypost.com/2026/05/24/us-news/ex-dem-n...
60,26,2026-05-24-15-22-06 +0000,nypost,Iran’s supreme leader has agreed ‘in principle...,https://nypost.com/2026/05/24/us-news/irans-su...
147,25,2026-05-24-01-00-00 +0000,wsj,The Stock Market Has Never Been So Good When P...,https://www.wsj.com/economy/consumers/stock-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)