## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-22-07-58 +0000,nyt,"At World Cup Final, Trump Seeks to Bask in Ano...",https://www.nytimes.com/2026/07/19/us/politics...
1,2026-07-19-22-03-36 +0000,nyt,Iran War Live Updates: Another U.S. Service Me...,https://www.nytimes.com/live/2026/07/19/world/...
2,2026-07-19-22-03-34 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/19/world/...
3,2026-07-19-22-02-22 +0000,cbc,Ferran Torres fires Spain past Argentina to wi...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
4,2026-07-19-22-02-00 +0000,wsj,U.S. Servicemember Killed in Iraq as Troop Dea...,https://www.wsj.com/world/middle-east/u-s-serv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2423/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    world     23
1      cup     19
9     iran     15
52     new     13
15  killed     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
103,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...,83
44,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,80
194,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,73
0,2026-07-19-22-07-58 +0000,nyt,"At World Cup Final, Trump Seeks to Bask in Ano...",https://www.nytimes.com/2026/07/19/us/politics...,71
40,2026-07-19-19-25-24 +0000,chitri,Trump celebrates the World Cup as a US victory...,https://www.chicagotribune.com/2026/07/19/trum...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
103,83,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...
194,73,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...
6,39,2026-07-19-21-43-54 +0000,bbc,Watch: Torrential rain hits New York and New J...,https://www.bbc.co.uk/news/videos/cq89veggnvqo...
195,34,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
159,30,2026-07-19-05-43-19 +0000,nypost,US ambassador to UN slaps down Zohran Mamdani’...,https://nypost.com/2026/07/19/us-news/us-ambas...
182,28,2026-07-19-00-00-00 +0000,wsj,He Ran a Strip Club. Now He Wants to Build Cal...,https://www.wsj.com/us-news/he-ran-a-strip-clu...
15,26,2026-07-19-21-11-47 +0000,nypost,Dr. Oz claims NY Medicaid program is being rip...,https://nypost.com/2026/07/19/us-news/chinese-...
12,22,2026-07-19-21-16-11 +0000,nypost,Chaotic bodycam video shows trans Florida stud...,https://nypost.com/2026/07/19/us-news/florida-...
189,22,2026-07-18-23-29-48 +0000,chitri,Social media influencers Andrew and Tristian T...,https://www.chicagotribune.com/2026/07/18/tate...
23,21,2026-07-19-20-34-19 +0000,startribune,"Air quality alert in effect across Minnesota, ...",https://www.startribune.com/persistent-minneso...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)