## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-22-52-19 +0000,nyt,U.S. Continues to Provide Intelligence to Ukra...,https://www.nytimes.com/2026/10/14/us/politics...
1,2026-10-14-22-49-04 +0000,nyt,U.S. Is Sending Hundreds of Troops to Latin Am...,https://www.nytimes.com/2026/10/14/us/politics...
2,2026-10-14-22-45-49 +0000,nypost,Suspect who barged into NYC synagogue yelling ...,https://nypost.com/2026/10/14/us-news/maniac-w...
3,2026-10-14-22-42-20 +0000,nyt,There’s a New Great Pumpkin to Rule Them All,https://www.nytimes.com/2026/10/14/us/rhode-is...
4,2026-10-14-22-40-59 +0000,cbc,Police investigating report of sexual assault ...,https://www.cbc.ca/news/world/university-of-ch...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2391/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
138      trump     39
3      ukraine     21
231  inflation     19
20         new     18
136     debate     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,147
189,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...,120
225,2026-10-14-15-25-31 +0000,nyt,Democrats Blame Trump After CPI Report Shows E...,https://www.nytimes.com/2026/10/14/business/ec...,120
297,2026-10-14-11-26-27 +0000,nypost,"Russian strikes kill 3, knock out power for 60...",https://nypost.com/2026/10/14/world-news/russi...,98
268,2026-10-14-13-08-00 +0000,wsj,Katie Zacharia’s first briefing leaves some Tr...,https://www.wsj.com/politics/policy/trumps-new...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,147,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
189,120,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...
9,82,2026-10-14-22-35-00 +0000,wsj,The federal investigation into Rep. Ilhan Omar...,https://www.wsj.com/politics/policy/ilhan-omar...
24,73,2026-10-14-22-04-31 +0000,nypost,McKinsey job applicants are facing off with an...,https://nypost.com/2026/10/14/business/mckinse...
5,72,2026-10-14-22-39-46 +0000,chitri,Chicago prays for native son Pope Leo XIV as h...,https://www.chicagotribune.com/2026/10/14/chic...
293,56,2026-10-14-11-45-00 +0000,wsj,The Morning Risk Report: Bank of America to Pa...,https://www.wsj.com/risk-compliance-journal/th...
264,55,2026-10-14-13-11-17 +0000,bbc,Starlink restrictions in Ukraine war linked to...,https://www.bbc.co.uk/news/articles/cm2d6e62p4...
395,53,2026-10-14-03-52-38 +0000,latimes,Bass and Raman trade blows over police chief i...,https://www.latimes.com/california/story/2026-...
284,50,2026-10-14-12-26-13 +0000,bbc,Houthi missile hits Aramco building after Saud...,https://www.bbc.co.uk/news/articles/crx2d60y1p...
37,45,2026-10-14-21-41-07 +0000,nypost,Rape reported at another elite college’s frat ...,https://nypost.com/2026/10/14/us-news/rape-rep...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)