## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-24-05-41-00 +0000,wsj,U.S. Treasury Yields Edge Up as Oil Price Rema...,https://www.wsj.com/finance/investing/jgbs-fal...
1,2026-04-24-05-39-00 +0000,wsj,Kuehne + Nagel Lifts Lower-End of Earnings Gui...,https://www.wsj.com/business/earnings/kuehne-n...
2,2026-04-24-05-38-26 +0000,nyt,Rubio Says Iran’s Soccer Team Can Attend World...,https://www.nytimes.com/2026/04/24/us/politics...
3,2026-04-24-05-34-56 +0000,nypost,Tennessee Rep. Tim Burchett says he’s seen UFO...,https://nypost.com/2026/04/24/us-news/tennesse...
4,2026-04-24-05-31-57 +0000,nyt,Iran War Live Updates: Trump Says Israel and L...,https://www.nytimes.com/live/2026/04/23/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35   trump     41
15    iran     26
32     war     20
327    new     17
3       up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-04-24-05-31-57 +0000,nyt,Iran War Live Updates: Trump Says Israel and L...,https://www.nytimes.com/live/2026/04/23/world/...,128
127,2026-04-23-21-23-43 +0000,nypost,Trump threatens to ‘finish it up militarily’ i...,https://nypost.com/2026/04/23/us-news/trump-th...,100
145,2026-04-23-20-45-51 +0000,bbc,US boards ship carrying Iran oil as Trump thre...,https://www.bbc.com/news/articles/cgldw5ekrjpo...,92
261,2026-04-23-16-02-26 +0000,wapo,Trump ally asked FIFA to have Italy replace Ir...,https://www.washingtonpost.com/world/2026/04/2...,89
24,2026-04-24-03-18-26 +0000,nyt,Trump Says Israel and Lebanon Agree to Extend ...,https://www.nytimes.com/2026/04/23/us/politics...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,128,2026-04-24-05-31-57 +0000,nyt,Iran War Live Updates: Trump Says Israel and L...,https://www.nytimes.com/live/2026/04/23/world/...
49,71,2026-04-24-01-14-13 +0000,nypost,California man accused of killing ex-wife and ...,https://nypost.com/2026/04/23/us-news/californ...
262,53,2026-04-23-15-57-53 +0000,nypost,Zohran Mamdani rips Warner Bros. Discovery’s P...,https://nypost.com/2026/04/23/business/zohran-...
209,49,2026-04-23-17-36-13 +0000,nypost,Microsoft offers voluntary employee buyouts fo...,https://nypost.com/2026/04/23/business/microso...
20,47,2026-04-24-03-50-41 +0000,nyt,He Was Exonerated in a Murder and Elected to O...,https://www.nytimes.com/2026/04/23/us/calvin-d...
376,45,2026-04-23-07-40-55 +0000,wsj,"Stock Market News, April 23, 2026: Oil Rises o...",https://www.wsj.com/livecoverage/stock-market-...
315,42,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
97,42,2026-04-23-22-34-54 +0000,nypost,US special forces soldier used secret intel fo...,https://nypost.com/2026/04/23/us-news/us-speci...
191,41,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
198,38,2026-04-23-18-08-12 +0000,nyt,Rodrigo Duterte Will Stand Trial for Crimes Ag...,https://www.nytimes.com/2026/04/23/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)