## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-05-12-07-36 +0000,nyt,Iran War Live Updates: Iranian Official Warns ...,https://www.nytimes.com/live/2026/05/05/world/...
1,2026-05-05-12-07-34 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/05/world/...
2,2026-05-05-12-07-03 +0000,nyt,Behind the Trump Administration’s Potential Re...,https://www.nytimes.com/2026/05/05/business/de...
3,2026-05-05-12-05-00 +0000,wsj,Rockwell Automation Raises Outlook on Higher S...,https://www.wsj.com/business/earnings/rockwell...
4,2026-05-05-12-00-00 +0000,missionlocal,Saikat Chakrabarti went after Democrats as AOC...,https://missionlocal.org/2026/05/sf-congress-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2629/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
14    trump     32
0      iran     21
93      new     17
1       war     15
237  cruise     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
156,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...,126
23,2026-05-05-11-07-01 +0000,nypost,Trump suggests Iran war could last ‘another tw...,https://nypost.com/2026/05/05/us-news/trump-su...,90
204,2026-05-04-21-33-45 +0000,nyt,China Seeks an Advantage With Both Trump and I...,https://www.nytimes.com/2026/05/03/us/politics...,85
159,2026-05-04-23-52-35 +0000,nypost,Trump is trying to force the Strait of Hormuz ...,https://nypost.com/2026/05/04/world-news/trump...,83
0,2026-05-05-12-07-36 +0000,nyt,Iran War Live Updates: Iranian Official Warns ...,https://www.nytimes.com/live/2026/05/05/world/...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
156,126,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...
330,65,2026-05-04-14-01-35 +0000,nypost,American cruise passenger sobs about being stu...,https://nypost.com/2026/05/04/world-news/cruis...
207,61,2026-05-04-21-30-31 +0000,nypost,Ex-JPMorgan banker Chirayu Rana files wild new...,https://nypost.com/2026/05/04/business/ex-jpmo...
90,48,2026-05-05-08-58-00 +0000,wsj,"China Steps Up U.S. Sanctions Fight, Defying B...",https://www.wsj.com/world/china/china-steps-up...
316,41,2026-05-04-15-22-38 +0000,nypost,Supreme Court restores access to abortion pill...,https://nypost.com/2026/05/04/us-news/supreme-...
279,40,2026-05-04-17-52-47 +0000,nypost,Elon Musk pressured OpenAI’s Greg Brockman to ...,https://nypost.com/2026/05/04/business/elon-mu...
239,38,2026-05-04-20-03-07 +0000,nypost,Gap co‑founder Doris Fisher — driving force be...,https://nypost.com/2026/05/04/business/gap-cof...
65,38,2026-05-05-10-00-00 +0000,nypost,$350M Mexican art collection secretly sold by ...,https://nypost.com/2026/05/05/world-news/mexic...
35,36,2026-05-05-10-56-53 +0000,bbc,Two killed and many injured after car driven i...,https://www.bbc.com/news/articles/ckgpzgxgz58o...
263,34,2026-05-04-18-40-26 +0000,nypost,New Mexico’s proposed kids safety fixes for In...,https://nypost.com/2026/05/04/business/new-mex...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)