## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-28-16-17-14 +0000,nypost,Viral moment tourists smash liquor bottles ove...,https://nypost.com/2026/05/28/world-news/shock...
1,2026-05-28-16-14-00 +0000,wsj,U.S. Stocks Rise as Investors Cling to Hope of...,https://www.wsj.com/finance/stocks/stocks-bond...
2,2026-05-28-16-12-18 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Str...,https://www.nytimes.com/live/2026/05/28/world/...
3,2026-05-28-16-11-24 +0000,nypost,Santa Rosa school district mulls massive raise...,https://nypost.com/2026/05/28/us-news/santa-ro...
4,2026-05-28-16-05-00 +0000,wsj,Hormel Foods Sales Rise as Turnaround Strategy...,https://www.wsj.com/business/earnings/hormel-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
58    trump     43
20     iran     30
239     new     25
19     deal     18
47   canada     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
241,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,111
341,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...,110
250,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,98
359,2026-05-27-17-47-51 +0000,nypost,Trump threatens to ‘blow up’ Oman if it sides ...,https://nypost.com/2026/05/27/us-news/trump-th...,96
364,2026-05-27-17-37-33 +0000,bbc,Trump says US 'not satisfied' with Iran deal yet,https://www.bbc.com/news/articles/c74dy9jw1q9o...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
241,111,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...
56,58,2026-05-28-14-41-56 +0000,nypost,New 2028 presidential election poll released —...,https://nypost.com/2026/05/28/us-news/new-2028...
250,49,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
34,46,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
67,44,2026-05-28-14-09-00 +0000,wsj,The U.S. economy grew more slowly during the f...,https://www.wsj.com/economy/q1-gross-domestic-...
36,43,2026-05-28-15-31-02 +0000,nypost,Fed’s preferred inflation gauge worsens as Ira...,https://nypost.com/2026/05/28/business/inflati...
196,43,2026-05-28-08-00-00 +0000,cbc,Canada mulls legal action against Colombia ove...,https://www.cbc.ca/news/world/canada-colombia-...
274,39,2026-05-27-22-11-08 +0000,bbc,What it was like inside court as Matthew Perry...,https://www.bbc.com/news/videos/ckgp8mrj5ggo?a...
112,38,2026-05-28-12-39-13 +0000,cbc,"Israel strikes Beirut suburb, at least 14 kill...",https://www.cbc.ca/news/world/lebanon-tyre-att...
371,37,2026-05-27-17-00-23 +0000,nypost,‘60 Minutes’ journo Sharyn Alfonsi loses CBS N...,https://nypost.com/2026/05/27/media/60-minutes...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)