## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-07-03-48-47 +0000,nypost,"Florida man arrested after climbing fence, sne...",https://nypost.com/2026/08/06/us-news/florida-...
1,2026-08-07-03-30-05 +0000,nypost,St. Anthony’s quarterback Anthony Diieso ready...,https://nypost.com/2026/08/06/sports/st-anthon...
2,2026-08-07-03-24-34 +0000,nypost,Port Washington ready for ‘once in a lifetime ...,https://nypost.com/2026/08/06/sports/port-wash...
3,2026-08-07-03-22-15 +0000,nyt,"In Upset, Andy Ogles Loses to a Republican Cha...",https://www.nytimes.com/2026/08/06/us/politics...
4,2026-08-07-03-07-56 +0000,nypost,Someone is living in a billboard high above Ho...,https://nypost.com/2026/08/06/us-news/netflix-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2523/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
167   trump     28
66      new     28
106    deal     16
832  senate     15
113   fauci     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...,116
254,2026-08-06-14-56-00 +0000,wsj,A Republican-led Senate panel voted to hold Dr...,https://www.wsj.com/politics/policy/senate-pan...,99
77,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...,95
144,2026-08-06-20-46-15 +0000,nypost,Trump signs new executive order to ban ‘birth ...,https://nypost.com/2026/08/06/us-news/trump-si...,90
262,2026-08-06-14-46-00 +0000,wsj,A Senate panel investigating Dr. Anthony Fauci...,https://www.wsj.com/politics/policy/anthony-fa...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,116,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...
77,95,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...
37,71,2026-08-07-01-03-00 +0000,wsj,Rep. Max Miller is lending his re-election cam...,https://www.wsj.com/politics/elections/max-mil...
159,53,2026-08-06-20-18-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
295,51,2026-08-06-13-09-00 +0000,wsj,Warner Bros. CEO Confident Paramount Deal Will...,https://www.wsj.com/business/earnings/warner-b...
116,50,2026-08-06-21-34-00 +0000,wsj,"Trump targets birthright citizenship (again), ...",https://www.wsj.com/politics/policy/trump-trie...
262,43,2026-08-06-14-46-00 +0000,wsj,A Senate panel investigating Dr. Anthony Fauci...,https://www.wsj.com/politics/policy/anthony-fa...
197,38,2026-08-06-18-14-51 +0000,chitri,Portillo’s lays off 18% of corporate employees...,https://www.chicagotribune.com/2026/08/06/port...
207,35,2026-08-06-17-26-56 +0000,bbc,Boxer charged with killing aid worker in Athen...,https://www.bbc.co.uk/news/articles/cj6390k0e2...
233,35,2026-08-06-16-00-59 +0000,nypost,FCC votes to ax rule limiting local TV station...,https://nypost.com/2026/08/06/media/fcc-votes-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)