## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-28-17-53-54 +0000,nyt,Trump Refiles $10 Billion Lawsuit Against The ...,https://www.nytimes.com/2026/05/28/business/me...
1,2026-05-28-17-52-22 +0000,nypost,Google engineer used confidential info to win ...,https://nypost.com/2026/05/28/business/google-...
2,2026-05-28-17-51-00 +0000,wsj,AI Is Changing How Consultants Get Paid—and Mu...,https://www.wsj.com/tech/ai/ai-is-changing-how...
3,2026-05-28-17-48-00 +0000,wsj,Americans Are Sick of High Prices. Companies A...,https://www.wsj.com/business/retail/americans-...
4,2026-05-28-17-48-00 +0000,wsj,"Kohl’s Turnaround Is Taking Hold, Driving Impr...",https://www.wsj.com/business/retail/kohls-narr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2503/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     42
164    new     28
51    iran     26
54    deal     17
97     war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
362,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...,108
270,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,105
278,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,93
177,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...,89
61,2026-05-28-15-56-32 +0000,nyt,"To Make a Deal With Trump, Iran Wants Billions...",https://www.nytimes.com/2026/05/27/world/middl...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
362,108,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...
111,74,2026-05-28-14-01-45 +0000,cbc,A strong Canada 'will help make America great ...,https://www.cbc.ca/news/politics/carney-new-yo...
80,54,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
367,50,2026-05-27-18-37-07 +0000,nyt,’60 Minutes’ Journalist Sharyn Alfonsi Loses D...,https://www.nytimes.com/2026/05/27/business/me...
177,47,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...
109,42,2026-05-28-14-09-00 +0000,wsj,The U.S. economy grew more slowly during the f...,https://www.wsj.com/economy/q1-gross-domestic-...
82,41,2026-05-28-15-31-02 +0000,nypost,Fed’s preferred inflation gauge worsens as Ira...,https://nypost.com/2026/05/28/business/inflati...
279,40,2026-05-27-23-55-24 +0000,latimes,Newsom vows to levy 100% tax on California rec...,https://www.latimes.com/california/story/2026-...
146,39,2026-05-28-12-39-13 +0000,cbc,"Israel strikes Beirut suburb, at least 14 kill...",https://www.cbc.ca/news/world/lebanon-tyre-att...
93,37,2026-05-28-14-56-07 +0000,nypost,Jill Biden wondered if husband Joe had been dr...,https://nypost.com/2026/05/28/us-news/jill-bid...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)