## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-22-12-22 +0000,nyt,Mideast Live Updates: Strains Emerge on First ...,https://www.nytimes.com/live/2026/06/21/world/...
1,2026-06-21-22-12-06 +0000,nyt,Oil Rises Amid Uncertainty Over Strait of Hormuz,https://www.nytimes.com/2026/06/21/business/oi...
2,2026-06-21-22-12-01 +0000,nypost,Mamdani and his alleged ‘Hamas slate’ of local...,https://nypost.com/2026/06/21/us-news/mamdani-...
3,2026-06-21-22-09-15 +0000,nypost,Nashville becomes another pro-business hub poi...,https://nypost.com/2026/06/21/us-news/nashvill...
4,2026-06-21-22-07-17 +0000,startribune,Target Field concessions workers to strike dur...,https://www.startribune.com/target-field-conce...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7     iran     27
112  trump     22
8    talks     17
27   world     10
23      up      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
41,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,107
100,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...,105
67,2026-06-21-17-30-40 +0000,wapo,Trump threatens Iran over Hormuz as JD Vance h...,https://www.washingtonpost.com/world/2026/06/2...,99
139,2026-06-21-09-13-54 +0000,cbc,Trump threats shake up U.S.-Iran talks in Swit...,https://www.cbc.ca/news/world/jd-vance-switzer...,93
173,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
41,107,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
66,44,2026-06-21-17-32-12 +0000,nypost,NYC voters are fed up with the Democratic Part...,https://nypost.com/2026/06/21/us-news/nyc-vote...
135,31,2026-06-21-09-45-57 +0000,bbc,Dutch royals enjoy two big results in one Worl...,https://www.bbc.com/sport/football/articles/c4...
11,28,2026-06-21-21-24-35 +0000,nypost,"Race against time in fight with 500,000-square...",https://nypost.com/2026/06/21/us-news/85m-poun...
104,28,2026-06-21-13-41-12 +0000,nypost,Vance says US willing to ‘fundamentally transf...,https://nypost.com/2026/06/21/us-news/vance-sa...
186,26,2026-06-20-22-41-34 +0000,wapo,Cyclist arrested at Reflecting Pool is former ...,https://www.washingtonpost.com/nation/2026/06/...
149,25,2026-06-21-09-00-00 +0000,wsj,Jay Clayton has been a loyal ally and golf bud...,https://www.wsj.com/politics/policy/the-would-...
79,25,2026-06-21-16-23-36 +0000,nyt,Keir Starmer Reflects on ‘Political Challenges...,https://www.nytimes.com/2026/06/21/world/europ...
91,23,2026-06-21-15-46-09 +0000,nypost,Sore loser Texas Rep. Jasmine Crockett says sh...,https://nypost.com/2026/06/21/us-news/jasmine-...
78,21,2026-06-21-16-48-18 +0000,nypost,Great-grandson of bushy-browed Soviet leader ...,https://nypost.com/2026/06/21/world-news/sovie...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)