## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-14-58-38 +0000,nypost,Jewelry store owner shoots at would-be thieves...,https://nypost.com/2026/10/08/us-news/washingt...
1,2026-10-08-14-56-12 +0000,nyt,Judge Throws Out Last Defendant’s Confession i...,https://www.nytimes.com/2026/10/07/us/politics...
2,2026-10-08-14-55-18 +0000,nyt,Examining Footage From the Night of Epstein's ...,https://www.nytimes.com/video/us/1000000112012...
3,2026-10-08-14-55-00 +0000,wsj,Israel Downgrades U.K. Consulate in Jerusalem ...,https://www.wsj.com/world/middle-east/israel-o...
4,2026-10-08-14-54-34 +0000,nyt,Was Jeffrey Epstein Really Suicidal?,https://www.nytimes.com/video/us/1000000112011...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2677/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
92      trump     47
224    school     30
477   chicago     27
769     board     25
738  district     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
147,2026-10-08-10-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...,137
143,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...,137
139,2026-10-08-10-00-19 +0000,chitri,2026 Chicago school board races: District 9B,https://www.chicagotribune.com/2026/10/08/chic...,129
127,2026-10-08-10-00-44 +0000,chitri,2026 Chicago school board races: District 4B,https://www.chicagotribune.com/2026/10/08/chic...,129
125,2026-10-08-10-00-51 +0000,chitri,2026 Chicago school board races: District 7B,https://www.chicagotribune.com/2026/10/08/chic...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
147,137,2026-10-08-10-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...
428,125,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...
325,115,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
251,69,2026-10-08-03-02-06 +0000,bbc,Texas carries out first US execution since Chr...,https://www.bbc.co.uk/news/articles/cw4g1j2z5z...
320,66,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
42,61,2026-10-08-13-55-12 +0000,nypost,"Oil prices jump 5%, pushing Treasury yields hi...",https://nypost.com/2026/10/08/business/oil-pri...
347,54,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
89,52,2026-10-08-11-18-20 +0000,chitri,Most Americans think artificial intelligence i...,https://www.chicagotribune.com/2026/10/08/arti...
80,51,2026-10-08-11-47-52 +0000,nypost,Arizona congressional candidate alleges she wa...,https://nypost.com/2026/10/08/us-news/arizona-...
111,50,2026-10-08-10-50-28 +0000,nypost,Missouri high schooler killed after being hit ...,https://nypost.com/2026/10/08/us-news/missouri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)