## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-23-44-35 +0000,nyt,"‘Digger,’ Warner Bros.’ Last Release Before Me...",https://www.nytimes.com/2026/10/03/business/me...
1,2026-10-03-23-37-46 +0000,bbc,Why pastors may not be seen - or heard - preac...,https://www.bbc.co.uk/news/articles/cwnvln99v2...
2,2026-10-03-23-30-06 +0000,bbc,Why Canada is preparing for a (long shot) US i...,https://www.bbc.co.uk/news/articles/c9m2mjj3yv...
3,2026-10-03-23-24-03 +0000,nypost,Mainlander blows off Hawaii coastline restrict...,https://nypost.com/2026/10/03/us-news/tourist-...
4,2026-10-03-23-23-52 +0000,nypost,Reservoir Dogs: These pups are protecting NYC’...,https://nypost.com/2026/10/03/us-news/reservoi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2386/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
107      trump     28
98    flydubai     16
100      pilot     11
461  execution     10
56         new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
130,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...,79
222,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...,78
85,2026-10-03-16-50-36 +0000,nypost,Trump gushes over blue-collar flydubai hero wh...,https://nypost.com/2026/10/03/us-news/trump-gu...,65
212,2026-10-03-00-59-50 +0000,chitri,FlyDubai co-pilot who nearly crashed plane was...,https://www.chicagotribune.com/2026/10/02/flyd...,64
105,2026-10-03-14-52-27 +0000,nyt,FlyDubai Co-Pilot Used Crash Ax in ‘Terrorist’...,https://www.nytimes.com/2026/10/03/world/middl...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
130,79,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...
23,56,2026-10-03-22-25-36 +0000,nyt,U.S.-Russia Talks on Ukraine Now Involve an Oi...,https://www.nytimes.com/2026/10/03/us/politics...
76,50,2026-10-03-17-48-42 +0000,bbc,Tennessee prison chief to resign after Christa...,https://www.bbc.co.uk/news/articles/c8zxl62yzx...
53,49,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...
222,42,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...
6,37,2026-10-03-23-19-00 +0000,wsj,A new White House task force will have 120 day...,https://www.wsj.com/tech/ai/new-ai-task-force-...
5,35,2026-10-03-23-20-56 +0000,nypost,"Cornell knew of drug arrest, overdose at Chi P...",https://nypost.com/2026/10/03/us-news/cornell-...
218,30,2026-10-03-00-00-00 +0000,wsj,One key to victory in the midterm elections co...,https://www.wsj.com/politics/elections/these-d...
80,29,2026-10-03-17-10-19 +0000,nypost,Rep. Burchett planning to block NYC socialist ...,https://nypost.com/2026/10/03/us-news/plan-to-...
26,27,2026-10-03-22-20-25 +0000,chitri,Pres. Donald Trump urges calls to Arkansas Sen...,https://www.chicagotribune.com/2026/10/03/trum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)