## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-11-15-06-57 +0000,nyt,U.S. Inflation Stayed Subdued Before Onset of ...,https://www.nytimes.com/2026/03/11/business/ec...
1,2026-03-11-15-05-35 +0000,nypost,Sen. Ron Johnson demands filibuster test vote ...,https://nypost.com/2026/03/11/us-news/sen-ron-...
2,2026-03-11-15-05-00 +0000,wsj,U.S. Crude Oil Stockpiles Rise for Third Strai...,https://www.wsj.com/business/energy-oil/u-s-cr...
3,2026-03-11-15-05-00 +0000,wsj,Lufthansa Says More Than Half of Flights Will ...,https://www.wsj.com/business/airlines/lufthans...
4,2026-03-11-15-04-47 +0000,bbc,"No evidence Swiss bus fire was terrorism, offi...",https://www.bbc.com/news/articles/c5y4wdlyy9xo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
5      iran     68
6       war     50
16      oil     32
140   trump     28
56   prices     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
204,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...,229
97,2026-03-11-11-36-18 +0000,nypost,IEA to recommend release of record 400M oil ba...,https://nypost.com/2026/03/11/world-news/iea-t...,199
292,2026-03-10-20-23-00 +0000,wsj,"As Iran War Pushes Up Oil Prices, Putin Can Ba...",https://www.wsj.com/world/russia/as-iran-war-p...,185
203,2026-03-11-02-00-00 +0000,wsj,Iran’s Control of Hormuz Means It’s Exporting ...,https://www.wsj.com/world/middle-east/irans-co...,174
13,2026-03-11-14-55-44 +0000,wapo,Nations agree to release oil reserves as war i...,https://www.washingtonpost.com/world/2026/03/1...,174

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
204,229,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...
107,66,2026-03-11-11-06-58 +0000,nyt,"A Trump-Xi Summit Nears, but China Doesn’t Kno...",https://www.nytimes.com/2026/03/11/world/asia/...
68,60,2026-03-11-13-19-52 +0000,nypost,Iranian women’s soccer team member flip-flops ...,https://nypost.com/2026/03/11/world-news/irani...
81,55,2026-03-11-12-33-43 +0000,wapo,February inflation was unchanged but predates ...,https://www.washingtonpost.com/business/2026/0...
17,54,2026-03-11-14-54-00 +0000,wsj,The economic shock waves of the Iran war are l...,https://www.wsj.com/business/energy-oil/the-ec...
250,45,2026-03-10-22-24-14 +0000,nypost,GOP gubernatorial hopeful Steve Hilton issues ...,https://nypost.com/2026/03/10/us-news/steve-hi...
30,42,2026-03-11-14-34-00 +0000,wsj,IEA Will Launch Largest-Ever Oil Release From ...,https://www.wsj.com/business/energy-oil/iea-pr...
338,38,2026-03-10-18-01-39 +0000,bbc,British Airways to suspend UK repatriation fli...,https://www.bbc.com/news/articles/c4ge52x4w37o...
315,38,2026-03-10-19-21-10 +0000,latimes,"Florida woman charged with attempted murder, a...",https://www.latimes.com/california/story/2026-...
109,35,2026-03-11-11-00-03 +0000,nypost,Sen. John Cornyn calls on Republicans to chang...,https://nypost.com/2026/03/11/us-news/sen-john...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)