## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-11-11-07-00 +0000,wsj,Insurance Risks Remain High as Wildfire Threat...,https://www.wsj.com/us-news/climate-environmen...
1,2026-08-11-11-04-00 +0000,wsj,U.S. Dollar Edges Higher,https://www.wsj.com/finance/currencies/yen-str...
2,2026-08-11-11-02-00 +0000,wsj,The Morning Risk Report: U.K. Discovers Compon...,https://www.wsj.com/cio-journal/the-morning-ri...
3,2026-08-11-11-01-00 +0000,wsj,An Oil Refiner That Fled California Is Back—Wi...,https://www.wsj.com/business/energy-oil/an-oil...
4,2026-08-11-11-00-00 +0000,missionlocal,S.F. supervisor wants city to improve data on ...,https://missionlocal.org/2026/08/sf-city-prope...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2396/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
165     trump     45
132       new     23
72   colombia     17
260      iran     13
23        oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
293,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...,109
114,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,104
266,2026-08-10-18-14-49 +0000,nypost,Iran’s ‘misery’ index hits record high — and a...,https://nypost.com/2026/08/10/world-news/irans...,94
119,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,93
316,2026-08-10-15-18-29 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
293,109,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...
137,64,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
195,49,2026-08-10-21-27-00 +0000,wsj,Earthquake Hits Colombia Days After New Presid...,https://www.wsj.com/world/americas/colombia-ea...
114,46,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
180,41,2026-08-10-21-51-38 +0000,latimes,Raman will lose homelessness committee chair a...,https://www.latimes.com/california/story/2026-...
255,40,2026-08-10-18-49-02 +0000,nypost,Fauci privately warned of miscarriage risk lin...,https://nypost.com/2026/08/10/us-news/fauci-wa...
48,38,2026-08-11-09-30-00 +0000,nypost,Luigi Mangione in NYC court today — potentiall...,https://nypost.com/2026/08/11/us-news/luigi-ma...
166,38,2026-08-10-22-30-01 +0000,startribune,Trump signs order calling for spacing out chil...,https://www.startribune.com/trump-to-sign-exec...
183,36,2026-08-10-21-47-00 +0000,wsj,"Nvidia, Wall Street Firms Strike AI Financing ...",https://www.wsj.com/business/deals/nvidia-wall...
147,36,2026-08-10-23-51-22 +0000,chitri,Judge temporarily blocks New York City Mayor Z...,https://www.chicagotribune.com/2026/08/10/new-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)