## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-10-07-33 +0000,nyt,Iran War Live Updates: Power Outages Are Repor...,https://www.nytimes.com/live/2026/03/23/world/...
1,2026-03-23-10-07-31 +0000,nyt,Iranians Fear Trump’s Threat to Strike Power P...,https://www.nytimes.com/2026/03/22/world/middl...
2,2026-03-23-10-06-00 +0000,wsj,Renewed Geopolitical Risk Puts Yen Back in Int...,https://www.wsj.com/finance/currencies/renewed...
3,2026-03-23-10-05-00 +0000,wsj,LaGuardia Airport Closed After Runway Collisio...,https://www.wsj.com/us-news/faa-issues-ground-...
4,2026-03-23-10-02-15 +0000,bbc,Stocks slide and oil rises as US and Iran thre...,https://www.bbc.com/news/articles/czex56kwxxzo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2637/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
13   trump     27
0     iran     27
1      war     17
108    new     12
35     oil     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,105
90,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...,104
87,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...,94
124,2026-03-22-23-49-25 +0000,nypost,California military families react as soldiers...,https://nypost.com/2026/03/22/us-news/socal-mi...,83
184,2026-03-22-17-51-18 +0000,wapo,Joe Kent says he wants Trump to hear MAGA oppo...,https://www.washingtonpost.com/national-securi...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,105,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...
87,59,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
73,55,2026-03-23-04-47-20 +0000,nypost,"Two pilots dead, 41 people hospitalized after ...",https://nypost.com/2026/03/23/us-news/air-cana...
13,52,2026-03-23-09-53-54 +0000,nypost,Iran threatens to start hitting Gulf power pla...,https://nypost.com/2026/03/23/world-news/iran-...
7,39,2026-03-23-10-00-00 +0000,latimes,Data centers under scrutiny by California lawm...,https://www.latimes.com/california/story/2026-...
109,38,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...
90,33,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...
217,32,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
225,31,2026-03-22-14-00-00 +0000,wsj,Small truck drivers in the U.S. are feeling so...,https://www.wsj.com/economy/truckers-are-the-f...
229,31,2026-03-22-12-52-00 +0000,wsj,South Korean President Lee Jae Myung has nomin...,https://www.wsj.com/economy/central-banking/so...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)