## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-17-09-08 +0000,nypost,Former NYC mayor Eric Adams granted Albanian c...,https://nypost.com/2026/04/10/us-news/former-n...
1,2026-04-10-17-07-03 +0000,nyt,Democrats Denounce Trump’s Plan to Use Foreign...,https://www.nytimes.com/2026/04/10/us/politics...
2,2026-04-10-17-06-15 +0000,nyt,Iran War Live Updates: Iran Adds New Condition...,https://www.nytimes.com/live/2026/04/10/world/...
3,2026-04-10-17-05-34 +0000,nyt,Iran Demands Release of ‘Blocked Assets’ Befor...,https://www.nytimes.com/live/2026/04/10/world/...
4,2026-04-10-17-04-00 +0000,wsj,Treasury Yields Choppy After CPI Report,https://www.wsj.com/finance/investing/jgbs-edg...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
18   iran     56
10  trump     45
19    war     29
23    new     20
28  talks     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-10-17-06-15 +0000,nyt,Iran War Live Updates: Iran Adds New Condition...,https://www.nytimes.com/live/2026/04/10/world/...,200
270,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,177
92,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,163
58,2026-04-10-15-28-35 +0000,nypost,Trump tells The Post he’s preparing military i...,https://nypost.com/2026/04/10/us-news/trump-te...,161
273,2026-04-09-21-51-17 +0000,nypost,"Trump goes off on ‘NUT JOBS’ Tucker Carlson, ...",https://nypost.com/2026/04/09/us-news/trump-go...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,200,2026-04-10-17-06-15 +0000,nyt,Iran War Live Updates: Iran Adds New Condition...,https://www.nytimes.com/live/2026/04/10/world/...
270,121,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
289,85,2026-04-09-21-13-41 +0000,nyt,Israel Says It Will Talk With Lebanon but Give...,https://www.nytimes.com/2026/04/09/world/middl...
82,56,2026-04-10-14-00-00 +0000,nypost,OnlyFans star reveals what reclusive billionai...,https://nypost.com/2026/04/10/us-news/onlyfans...
31,55,2026-04-10-16-14-00 +0000,wsj,"Consumer prices soared in March, pushed higher...",https://www.wsj.com/economy/cpi-inflation-repo...
310,52,2026-04-09-20-18-00 +0000,wsj,First lady Melania Trump denied having ties to...,https://www.wsj.com/politics/melania-trump-den...
61,45,2026-04-10-15-12-57 +0000,bbc,EU airline industry warns of fuel shortages if...,https://www.bbc.com/news/articles/c3w37ggp011o...
331,42,2026-04-09-19-07-15 +0000,nypost,"Keir Starmer lashes out at Trump, Putin as UK ...",https://nypost.com/2026/04/09/us-news/keir-sta...
244,42,2026-04-09-23-01-47 +0000,bbc,"Ceasefire or no ceasefire, the Middle East's r...",https://www.bbc.com/news/articles/cp3l4yk5rlgo...
95,38,2026-04-10-13-28-00 +0000,nypost,Arrested husband of missing US boater Lynette ...,https://nypost.com/2026/04/10/us-news/arrested...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)