## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-12-11-15-11 +0000,bbc,Badly burned British couple rescued from ravin...,https://www.bbc.co.uk/news/articles/cx2x744176...
1,2026-07-12-11-12-29 +0000,nyt,Here’s a look at the heavy strikes in recent d...,https://www.nytimes.com/live/2026/07/12/us/ira...
2,2026-07-12-11-08-12 +0000,bbc,Nothing to suggest Widdecombe killing was poli...,https://www.bbc.co.uk/news/articles/c8628q3eqd...
3,2026-07-12-11-07-55 +0000,nyt,"Senator Lindsey Graham, Republican of South Ca...",https://www.nytimes.com/2026/07/12/us/politics...
4,2026-07-12-11-00-00 +0000,missionlocal,"Three careers in, Chika Kuramoto makes the Jap...",https://missionlocal.org/2026/07/san-francisco...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
75   trump     23
141   iran     15
218    new     13
109  world     12
110    cup     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,89
131,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,83
85,2026-07-11-23-18-00 +0000,wsj,Trump Administration Subpoenas New York Times ...,https://www.wsj.com/politics/policy/trump-admi...,83
133,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,83
147,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,89,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
64,55,2026-07-12-01-08-40 +0000,nyt,U.S. Strikes Iran After Iran Fires on Ship in ...,https://www.nytimes.com/2026/07/11/world/middl...
6,49,2026-07-12-10-31-00 +0000,wsj,Longtime Republican Sen. Lindsey Graham has di...,https://www.wsj.com/politics/lindsey-graham-lo...
145,42,2026-07-11-14-28-53 +0000,nyt,"Kansas City, the Smallest World Cup Host, Has ...",https://www.nytimes.com/2026/07/11/business/ka...
100,32,2026-07-11-21-23-38 +0000,nypost,Ro Khanna blew off offer to meet former Israel...,https://nypost.com/2026/07/11/world-news/ro-kh...
18,31,2026-07-12-09-30-00 +0000,wsj,The good news from the WSJ survey of economist...,https://www.wsj.com/economy/central-banking/wa...
52,29,2026-07-12-03-56-02 +0000,bbc,At least two killed in Toronto street festival...,https://www.bbc.co.uk/news/articles/ce3e66e1x3...
151,25,2026-07-11-13-32-23 +0000,cbc,Typhoon Bavi makes landfall in China after bru...,https://www.cbc.ca/news/world/typhoon-bavi-eva...
129,24,2026-07-11-16-50-06 +0000,nypost,Maine event: Dems descend into chaos over Plat...,https://nypost.com/2026/07/11/us-news/maine-de...
45,24,2026-07-12-04-40-09 +0000,nypost,Heartbroken daughter reveals reason plane ende...,https://nypost.com/2026/07/12/us-news/heartbro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)