## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-27-23-15-48 +0000,nypost,Park Slope Coop rips Israeli products from sto...,https://nypost.com/2026/05/27/us-news/park-slo...
1,2026-05-27-23-12-47 +0000,nypost,"Violent crew pummels, slashes Knicks fan durin...",https://nypost.com/2026/05/27/us-news/violent-...
2,2026-05-27-23-07-50 +0000,nyt,"Iran War Live Updates: As Talks Drag On, Trump...",https://www.nytimes.com/live/2026/05/27/world/...
3,2026-05-27-23-07-49 +0000,nyt,"Trump Threatens Oman Over the Strait, Then Say...",https://www.nytimes.com/2026/05/27/world/middl...
4,2026-05-27-23-06-29 +0000,nypost,Member of Haiti’s national soccer team still a...,https://nypost.com/2026/05/27/sports/member-of...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2329/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35   trump     38
121    new     24
170  texas     19
253   deal     19
29    iran     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
14,2026-05-27-22-36-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,112
283,2026-05-27-10-54-27 +0000,cbc,Trump's scandal-plagued pick wins Texas Senate...,https://www.cbc.ca/news/world/us-texas-republi...,100
108,2026-05-27-20-26-52 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,91
140,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...,87
300,2026-05-27-10-00-00 +0000,latimes,Barabak: Texas is where Democratic dreams die....,https://www.latimes.com/politics/story/2026-05...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
14,112,2026-05-27-22-36-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
310,68,2026-05-27-09-03-26 +0000,nypost,Israel kills new Hamas military chief who was...,https://nypost.com/2026/05/27/world-news/israe...
245,63,2026-05-27-13-38-04 +0000,nypost,Oil plunges to $89 per barrel after Iran repor...,https://nypost.com/2026/05/27/business/oil-plu...
7,47,2026-05-27-22-56-00 +0000,wsj,“We’ve got to pivot” to support Ken Paxton to ...,https://www.wsj.com/politics/policy/thune-paxt...
186,43,2026-05-27-16-43-49 +0000,bbc,DR Congo seek World Cup ticket refunds after E...,https://www.bbc.com/sport/football/articles/c0...
298,42,2026-05-27-10-00-00 +0000,nypost,Newt Gingrich tells ‘Pod Force One’ that gas p...,https://nypost.com/2026/05/27/us-news/newt-gin...
366,41,2026-05-27-00-43-55 +0000,bbc,Champion ethical hacker warns AI tools like My...,https://www.bbc.com/news/articles/c3r2zjpryzro...
278,41,2026-05-27-11-03-03 +0000,nypost,Race against time to rescue villagers trapped ...,https://nypost.com/2026/05/27/world-news/race-...
297,40,2026-05-27-10-00-00 +0000,latimes,'Monster who killed him': Matthew Perry's form...,https://www.latimes.com/california/story/2026-...
361,39,2026-05-27-01-35-31 +0000,cbc,"1 dead, 9 others missing and feared dead in Wa...",https://www.cbc.ca/news/world/washington-paper...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)