## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-27-17-13-01 +0000,nyt,"Live Updates: Mideast Hostilities Flare, Testi...",https://www.nytimes.com/live/2026/06/27/world/...
1,2026-06-27-17-13-00 +0000,nyt,"Deal With Israel Divides Lebanese, Fueling Pro...",https://www.nytimes.com/2026/06/27/world/middl...
2,2026-06-27-17-09-15 +0000,nypost,Jersey Shore eatery is making a splash for its...,https://nypost.com/2026/06/27/us-news/jersey-s...
3,2026-06-27-17-07-39 +0000,nyt,U.S.-Iran Deal’s Vague Language Comes Back to ...,https://www.nytimes.com/2026/06/27/world/middl...
4,2026-06-27-17-06-57 +0000,nyt,Venezuela Live Updates: Rescuers Work as Windo...,https://www.nytimes.com/live/2026/06/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2328/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
39   venezuela     21
7         iran     16
107      trump     15
146      world     15
249        cup     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
51,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...,58
114,2026-06-27-07-03-45 +0000,nyt,"At World Cup, Iran-Egypt ‘Pride Match’ Stirs C...",https://www.nytimes.com/2026/06/27/us/world-cu...,57
226,2026-06-26-20-35-00 +0000,cbc,U.S. strikes Iran in retaliation for attack on...,https://www.cbc.ca/news/world/trump-blames-ira...,57
53,2026-06-27-13-06-38 +0000,nypost,NYC cops and feds crack down on ATM-skimming s...,https://nypost.com/2026/06/27/us-news/nypd-ups...,56
178,2026-06-26-22-23-12 +0000,missionlocal,San Francisco kicks off Pride weekend with Wor...,https://missionlocal.org/2026/06/san-francisco...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
51,58,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...
226,57,2026-06-26-20-35-00 +0000,cbc,U.S. strikes Iran in retaliation for attack on...,https://www.cbc.ca/news/world/trump-blames-ira...
53,56,2026-06-27-13-06-38 +0000,nypost,NYC cops and feds crack down on ATM-skimming s...,https://nypost.com/2026/06/27/us-news/nypd-ups...
140,43,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
218,42,2026-06-26-20-53-44 +0000,latimes,Trump administration takes aim at California C...,https://www.latimes.com/california/story/2026-...
192,36,2026-06-26-21-41-00 +0000,wsj,Millions of people who signed up for Affordabl...,https://www.wsj.com/politics/policy/millions-o...
264,32,2026-06-26-18-47-00 +0000,wsj,Vice President JD Vance compared himself to fo...,https://www.wsj.com/politics/policy/jd-vance-c...
247,29,2026-06-26-19-22-24 +0000,nypost,Gavin Newsom’s billionaire tax two-step: squee...,https://nypost.com/2026/06/26/us-news/gavin-ne...
224,28,2026-06-26-20-42-59 +0000,nypost,5 human heads found stuffed inside medical fre...,https://nypost.com/2026/06/26/world-news/5-hum...
219,28,2026-06-26-20-47-38 +0000,nypost,Pete Buttigieg briefly separated from his chil...,https://nypost.com/2026/06/26/us-news/pete-but...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)