## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-03-41-49 +0000,nypost,Two tugboat crew members dead after ‘confined ...,https://nypost.com/2026/03/18/us-news/2-tugboa...
1,2026-03-19-03-37-56 +0000,nypost,Trump admin considering deploying troops to Ir...,https://nypost.com/2026/03/18/us-news/trump-ad...
2,2026-03-19-03-31-39 +0000,nypost,Hundreds of thousands of LA students face stri...,https://nypost.com/2026/03/18/us-news/hundreds...
3,2026-03-19-03-26-00 +0000,wsj,Yen Weakens Slightly After BOJ Keeps Rate Unch...,https://www.wsj.com/finance/currencies/yen-lik...
4,2026-03-19-03-20-16 +0000,nyt,Iran War Live Updates: Missile Attack Kills at...,https://www.nytimes.com/live/2026/03/18/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
42     iran     63
43      war     38
12    trump     37
211  chavez     28
210   cesar     26

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
355,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,175
254,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,165
246,2026-03-18-17-07-48 +0000,nyt,Trump’s Next Decision in War: Whether to Retri...,https://www.nytimes.com/2026/03/17/us/politics...,161
16,2026-03-19-02-19-22 +0000,nyt,Senate G.O.P. Again Blocks Bid to Stop Iran Wa...,https://www.nytimes.com/2026/03/18/us/politics...,157
390,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...,156

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
355,175,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...
24,99,2026-03-19-02-02-49 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
150,86,2026-03-18-21-06-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
39,58,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
111,57,2026-03-18-22-33-50 +0000,wapo,Oil prices climb again after strikes in crucia...,https://www.washingtonpost.com/business/2026/0...
390,55,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...
200,49,2026-03-18-19-29-00 +0000,wsj,An updated list shows House departures hitting...,https://www.wsj.com/politics/policy/why-a-reco...
7,40,2026-03-19-03-11-00 +0000,wsj,Bank of Japan Holds Steady as Middle East Tens...,https://www.wsj.com/economy/central-banking/ba...
307,39,2026-03-18-14-42-52 +0000,latimes,"Cesar Chavez accused of abusing girls, raping ...",https://www.latimes.com/california/story/2026-...
211,38,2026-03-18-18-51-07 +0000,bbc,Five takeaways from Markwayne Mullin's Homelan...,https://www.bbc.com/news/articles/c2k8kp7d832o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)