## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-14-21-36 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...
1,2026-04-23-14-20-00 +0000,wsj,The Billionaire Trying to Build the ‘Next Grea...,https://www.wsj.com/business/media/the-billion...
2,2026-04-23-14-18-43 +0000,nyt,U.S. Seizes Second Tanker Carrying Iranian Oil,https://www.nytimes.com/2026/04/23/us/politics...
3,2026-04-23-14-17-31 +0000,nyt,Zelensky details deals Ukraine signed to bolst...,https://www.nytimes.com/live/2026/04/23/world/...
4,2026-04-23-14-16-30 +0000,nypost,MAHA school lunch program seeing ‘impressive r...,https://nypost.com/2026/04/23/health/new-healt...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     37
4    trump     33
1      war     24
67     new     23
11  hormuz     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-23-14-21-36 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...,152
46,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...,131
181,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,130
242,2026-04-22-21-43-55 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...,126
380,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,152,2026-04-23-14-21-36 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...
125,75,2026-04-23-10-00-00 +0000,latimes,California's rail systems need more riders. Hi...,https://www.latimes.com/california/story/2026-...
181,53,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
238,47,2026-04-22-21-52-00 +0000,wsj,Here are the key takeaways after Health Secret...,https://www.wsj.com/politics/policy/lawmakers-...
44,45,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
213,43,2026-04-22-23-07-43 +0000,nypost,Elon Musk says Tesla expenses will rise ‘subst...,https://nypost.com/2026/04/22/business/elon-mu...
128,40,2026-04-23-09-53-35 +0000,nypost,Alabama high school basketball coach Paige Ada...,https://nypost.com/2026/04/23/us-news/alabama-...
147,39,2026-04-23-08-12-48 +0000,nypost,"Senate passes $70B budget plan to fund ICE, Bo...",https://nypost.com/2026/04/23/us-news/senate-p...
340,38,2026-04-22-16-58-00 +0000,wsj,More than a year into President Trump’s immigr...,https://www.wsj.com/economy/jobs/immigration-c...
26,37,2026-04-23-13-46-00 +0000,wsj,The Trump administration is reclassifying mari...,https://www.wsj.com/politics/policy/trump-admi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)