## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-19-21-00 +0000,wsj,Oil Futures Rise as U.S.-Iran Stalemate Persists,https://www.wsj.com/finance/commodities-future...
1,2026-05-12-19-19-01 +0000,nyt,Iran War Live Updates: Truce Hangs in the Bala...,https://www.nytimes.com/live/2026/05/12/world/...
2,2026-05-12-19-17-56 +0000,nyt,"Britain’s Starmer Defies Calls to Resign, For Now",https://www.nytimes.com/live/2026/05/12/world/...
3,2026-05-12-19-13-44 +0000,nypost,Goldman Sachs exec touts plans to automate ‘hu...,https://nypost.com/2026/05/12/business/goldman...
4,2026-05-12-19-12-49 +0000,nyt,Man Who Stole Unreleased Beyoncé Music Is Sent...,https://www.nytimes.com/2026/05/12/us/beyonce-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
148       trump     37
3          iran     35
6           war     26
15      starmer     17
254  hantavirus     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
315,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,147
344,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,128
36,2026-05-12-18-29-40 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,127
1,2026-05-12-19-19-01 +0000,nyt,Iran War Live Updates: Truce Hangs in the Bala...,https://www.nytimes.com/live/2026/05/12/world/...,109
75,2026-05-12-17-31-00 +0000,wsj,Consumer prices rose 3.8% in April from a year...,https://www.wsj.com/economy/cpi-inflation-repo...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
315,147,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
102,57,2026-05-12-16-49-58 +0000,nypost,Spain reports new hantavirus case in passenger...,https://nypost.com/2026/05/12/health/spain-rep...
280,56,2026-05-12-02-26-06 +0000,nyt,Starmer Faces Mounting Calls From Own Party to...,https://www.nytimes.com/2026/05/11/world/europ...
24,53,2026-05-12-18-45-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
82,46,2026-05-12-17-20-00 +0000,wsj,OpenAI’s Sam Altman’s personal investments are...,https://www.wsj.com/tech/ai/sam-altmans-busine...
64,45,2026-05-12-17-41-56 +0000,nypost,California Democrats deploy risky strategy to ...,https://nypost.com/2026/05/12/us-news/californ...
246,44,2026-05-12-08-30-52 +0000,bbc,China should stop hoarding food and fertiliser...,https://www.bbc.com/news/articles/cwy2rnyg50zo...
325,42,2026-05-11-22-38-31 +0000,nypost,Supreme Court allows Alabama to redraw congres...,https://nypost.com/2026/05/11/us-news/supreme-...
91,41,2026-05-12-17-11-00 +0000,wsj,"Inflation is overtaking Americans’ pay gains, ...",https://www.wsj.com/economy/jobs/prices-at-the...
310,41,2026-05-11-23-45-00 +0000,wsj,The Senate took another procedural step toward...,https://www.wsj.com/economy/central-banking/se...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)