## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-12-16-10-04 +0000,nyt,Live Updates: Europe Counts Down to a Total So...,https://www.nytimes.com/live/2026/08/12/world/...
1,2026-08-12-16-06-08 +0000,nypost,Serial sex offender gets life sentence for dou...,https://nypost.com/2026/08/12/world-news/seria...
2,2026-08-12-16-04-37 +0000,nyt,"Inflation Eased Slightly in July, but Prices R...",https://www.nytimes.com/2026/08/12/business/ec...
3,2026-08-12-16-03-30 +0000,nyt,ICE Plans to Give Officers Gloves That Can Del...,https://www.nytimes.com/2026/08/12/us/politics...
4,2026-08-12-16-01-03 +0000,nyt,How Scientists Use Eclipses for Research,https://www.nytimes.com/2026/08/12/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2623/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
41        trump     46
149   wisconsin     25
267     primary     24
334   minnesota     20
280  democratic     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
249,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,151
231,2026-08-12-03-32-23 +0000,nyt,Lisa Demuth Defeats Trump-Endorsed Candidate M...,https://www.nytimes.com/2026/08/11/us/election...,130
177,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...,119
230,2026-08-12-03-34-56 +0000,nypost,Walz Lt. Gov. Peggy Flanagan wins Minnesota De...,https://nypost.com/2026/08/11/us-news/tim-walz...,116
28,2026-08-12-15-19-30 +0000,nypost,"Trump calls Iran ‘all talk and no action,’ tou...",https://nypost.com/2026/08/12/us-news/trump-ca...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
249,151,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...
177,119,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...
230,71,2026-08-12-03-34-56 +0000,nypost,Walz Lt. Gov. Peggy Flanagan wins Minnesota De...,https://nypost.com/2026/08/11/us-news/tim-walz...
28,59,2026-08-12-15-19-30 +0000,nypost,"Trump calls Iran ‘all talk and no action,’ tou...",https://nypost.com/2026/08/12/us-news/trump-ca...
241,59,2026-08-12-02-30-00 +0000,wsj,Sen. Darline Graham advanced to a runoff later...,https://www.wsj.com/politics/elections/sen-dar...
6,56,2026-08-12-15-56-00 +0000,wsj,July’s inflation report was close enough to ex...,https://www.wsj.com/economy/central-banking/in...
146,48,2026-08-12-10-31-36 +0000,nyt,"Zhu Rongji, Former Premier Who Pushed China to...",https://www.nytimes.com/2026/08/12/world/asia/...
330,47,2026-08-11-21-25-00 +0000,wsj,Mamdani Takes On Amazon in New Battle Over New...,https://www.wsj.com/business/logistics/mamdani...
341,41,2026-08-11-21-10-25 +0000,chitri,Chicago Mayor Brandon Johnson signs data cente...,https://www.chicagotribune.com/2026/08/11/chic...
160,41,2026-08-12-10-00-00 +0000,latimes,Google co-founder Sergey Brin spending more th...,https://www.latimes.com/business/story/2026-08...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)