## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-02-14-17-06 +0000,nyt,Iran War Live Updates: Israel Strikes Southern...,https://www.nytimes.com/live/2026/06/02/world/...
1,2026-06-02-14-17-04 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/02/world/...
2,2026-06-02-14-16-45 +0000,nypost,Jill Biden says White House docs ‘missed’ Joe’...,https://nypost.com/2026/06/02/us-news/jill-bid...
3,2026-06-02-14-11-37 +0000,nypost,Ex-MSNBC host Joy Reid rants she’s a ‘former’ ...,https://nypost.com/2026/06/02/media/joy-reid-r...
4,2026-06-02-14-11-04 +0000,nyt,New York Sues Trump Administration Over TotalE...,https://www.nytimes.com/2026/06/02/climate/new...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2510/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
40        trump     29
41          new     21
128  california     18
0          iran     15
270    election     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-06-02-01-21-18 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...,95
170,2026-06-02-01-15-00 +0000,nypost,Steve Hilton says it’s ‘now or never for Calif...,https://nypost.com/2026/06/01/us-news/steve-hi...,88
6,2026-06-02-14-10-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,75
126,2026-06-02-07-46-30 +0000,nypost,Trump makes late-night endorsements in six sta...,https://nypost.com/2026/06/02/us-news/trump-ma...,70
211,2026-06-01-22-17-37 +0000,cbc,Trump administration to pause controversial an...,https://www.cbc.ca/news/world/anti-weaponizati...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,95,2026-06-02-01-21-18 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...
35,64,2026-06-02-12-53-24 +0000,latimes,Your last-minute guide to election day challen...,https://www.latimes.com/california/story/2026-...
325,59,2026-06-01-16-34-49 +0000,latimes,"AI company Anthropic files to list shares, hea...",https://www.latimes.com/business/story/2026-06...
72,53,2026-06-02-10-53-37 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
0,51,2026-06-02-14-17-06 +0000,nyt,Iran War Live Updates: Israel Strikes Southern...,https://www.nytimes.com/live/2026/06/02/world/...
79,49,2026-06-02-10-33-06 +0000,bbc,He was a reality show villain. Can he be the m...,https://www.bbc.com/news/articles/c775x852rk1o...
260,41,2026-06-01-20-34-11 +0000,nypost,NJ congressional candidate Adam Hamawy ‘lied’ ...,https://nypost.com/2026/06/01/world-news/nj-co...
193,39,2026-06-01-23-23-10 +0000,nypost,Anti-ICE agitator who allegedly bit officers d...,https://nypost.com/2026/06/01/us-news/anti-ice...
105,38,2026-06-02-09-30-00 +0000,wsj,Berkshire Hathaway’s $6.8 billion deal to acqu...,https://www.wsj.com/economy/housing/berkshire-...
75,38,2026-06-02-10-43-29 +0000,nypost,Joe Biden told wife Jill ‘I just don’t feel we...,https://nypost.com/2026/06/02/us-news/joe-bide...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)