## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-17-43-00 +0000,wsj,Comex Gold Settles 0.03% Lower at $4335.90,https://www.wsj.com/finance/commodities-future...
1,2026-06-08-17-41-27 +0000,nyt,Live Updates: Iran and Israel Pull Back After ...,https://www.nytimes.com/live/2026/06/08/world/...
2,2026-06-08-17-41-25 +0000,nyt,Why Iran Risked an Attack on Israel,https://www.nytimes.com/2026/06/08/world/middl...
3,2026-06-08-17-39-06 +0000,bbc,Somali referee Artan barred from entering USA,https://www.bbc.com/sport/football/articles/cn...
4,2026-06-08-17-39-03 +0000,nypost,Pulitzer Prize-winning historian Gordon S. Woo...,https://nypost.com/2026/06/08/media/american-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5     iran     28
6   israel     27
55   trump     26
37     new     14
24    dead     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
250,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...,110
40,2026-06-08-16-39-22 +0000,nypost,Netanyahu says Israel will ‘hold fire’ on Iran...,https://nypost.com/2026/06/08/us-news/netanyah...,104
139,2026-06-08-11-42-45 +0000,latimes,Iran and Israel trade fire then halt after Tru...,https://www.latimes.com/world-nation/story/202...,95
158,2026-06-08-10-04-21 +0000,nypost,Iran says it’s halting Israel attacks after Tr...,https://nypost.com/2026/06/08/us-news/trump-sa...,94
23,2026-06-08-17-11-32 +0000,bbc,Iran and Israel say they have halted strikes a...,https://www.bbc.com/news/articles/cj6ge150z5go...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
250,110,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...
194,61,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
243,46,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
61,44,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
223,42,2026-06-08-01-00-00 +0000,wsj,"Most rankings of companies look backward, meas...",https://www.wsj.com/economy/jobs/best-companie...
98,40,2026-06-08-14-14-11 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
130,38,2026-06-08-12-15-14 +0000,nypost,Two dead as private jet crashes in Dominican R...,https://nypost.com/2026/06/08/world-news/priva...
114,37,2026-06-08-13-47-47 +0000,nyt,Mexico City’s Airport Got a $500 Million Renov...,https://www.nytimes.com/2026/06/07/world/ameri...
79,37,2026-06-08-15-24-29 +0000,nypost,"NYPD, Secret Service announce NBA Finals Game ...",https://nypost.com/2026/06/08/sports/nypd-secr...
28,35,2026-06-08-17-05-53 +0000,nypost,Cocky Karen Bass reacts to Nithya Raman jumpin...,https://nypost.com/2026/06/08/us-news/karen-ba...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)