## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-14-07-13-51 +0000,nyt,Farage Wins Special U.K. Election That He Init...,https://www.nytimes.com/2026/08/14/world/europ...
1,2026-08-14-07-11-11 +0000,bbc,Farage wins Clacton by-election but avoids res...,https://www.bbc.co.uk/news/articles/c62x1gr62m...
2,2026-08-14-07-02-22 +0000,nyt,"Another Day of Extreme Heat Bakes Europe, but ...",https://www.nytimes.com/2026/08/14/weather/eur...
3,2026-08-14-07-01-00 +0000,wsj,Aviva Posts Strong First-Half Profit Growth,https://www.wsj.com/business/earnings/aviva-po...
4,2026-08-14-07-00-56 +0000,bbc,'Unprecedented' rains in Japan kill six people,https://www.bbc.co.uk/news/articles/cq561gpen8...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2462/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
55        trump     38
118         new     18
303  california     18
87          out     13
4            he     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
60,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...,114
140,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...,107
51,2026-08-14-00-50-00 +0000,wsj,President Trump has directed the Navy to tear ...,https://www.wsj.com/us-news/trump-orders-navy-...,91
148,2026-08-13-20-15-57 +0000,cbc,Kennedy Center board votes to return Trump's n...,https://www.cbc.ca/news/world/kennedy-center-v...,89
19,2026-08-14-04-41-00 +0000,wsj,President Trump unveiled a slate of tariffs to...,https://www.wsj.com/economy/trade/trump-announ...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
60,114,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...
157,73,2026-08-13-20-01-00 +0000,wsj,The U.S. military is preparing to replace the ...,https://www.wsj.com/politics/national-security...
135,61,2026-08-13-20-42-17 +0000,chitri,Investigators find bird remains inside Ryanair...,https://www.chicagotribune.com/2026/08/13/ntsb...
140,61,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...
168,57,2026-08-13-19-19-55 +0000,nypost,California city accuses Gavin Newsom of ‘overr...,https://nypost.com/2026/08/13/us-news/newsom-i...
155,47,2026-08-13-20-05-52 +0000,latimes,"He was a star LAPD investigator, then he went ...",https://www.latimes.com/california/story/2026-...
315,45,2026-08-13-11-03-00 +0000,wsj,"During campaign season, it isn’t popular to ta...",https://www.wsj.com/politics/policy/no-one-wan...
359,43,2026-08-13-08-42-00 +0000,wsj,U.S. Army troops faced off against Ukrainian d...,https://www.wsj.com/politics/national-security...
164,42,2026-08-13-19-37-00 +0000,wsj,House Minority Leader Hakeem Jeffries on Thurs...,https://www.wsj.com/politics/policy/top-democr...
19,42,2026-08-14-04-41-00 +0000,wsj,President Trump unveiled a slate of tariffs to...,https://www.wsj.com/economy/trade/trump-announ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)