## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-02-45-02 +0000,startribune,"Integrity of World Cup is questioned as Trump,...",https://www.startribune.com/uefa-says-decision...
1,2026-07-07-02-41-57 +0000,nypost,Florida man pulls pistol on teens who mistaken...,https://nypost.com/2026/07/06/us-news/florida-...
2,2026-07-07-02-41-00 +0000,wsj,Chinese Nuclear Submarine Test-Launches Long-R...,https://www.wsj.com/world/asia/chinese-nuclear...
3,2026-07-07-02-36-31 +0000,48hills,Live Shots: Metric rode the indie sleaze reviv...,https://48hills.org/2026/07/live-shots-metric-...
4,2026-07-07-02-35-00 +0000,wsj,LG Electronics Expects Quarterly Earnings to M...,https://www.wsj.com/business/earnings/lg-elect...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     45
1    world     23
93    nato     15
251     he     15
2      cup     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...,167
299,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...,125
12,2026-07-07-02-06-01 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,120
265,2026-07-06-14-21-08 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...,116
333,2026-07-06-09-00-11 +0000,nyt,Emil Bove Defended Trump in Court. Then Trump ...,https://www.nytimes.com/2026/07/06/us/emil-bov...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,167,2026-07-06-17-42-00 +0000,wsj,President Trump confirmed he called FIFA Presi...,https://www.wsj.com/politics/policy/trump-conf...
37,76,2026-07-07-00-09-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
191,63,2026-07-06-17-47-41 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
60,49,2026-07-06-23-10-21 +0000,nyt,New Videos of Charlie Kirk’s Killing Emerge in...,https://www.nytimes.com/2026/07/06/us/charlie-...
189,49,2026-07-06-17-57-00 +0000,wsj,Canada CPI Expectations Ramped Up Prior to U.S...,https://www.wsj.com/economy/central-banking/ca...
350,43,2026-07-06-05-29-00 +0000,bbc,"After a year of ICE raids, Southern California...",https://www.bbc.co.uk/sport/football/articles/...
54,40,2026-07-06-23-17-04 +0000,nypost,Iranian loyalists vow to assassinate Trump dur...,https://nypost.com/2026/07/06/world-news/irani...
278,38,2026-07-06-13-25-13 +0000,nyt,"With $8 Billion in Venezuelan Oil Money, U.S. ...",https://www.nytimes.com/2026/07/06/world/ameri...
335,36,2026-07-06-08-21-54 +0000,wsj,"Stock Market News, July 6, 2026: Dow Rises to ...",https://www.wsj.com/livecoverage/stock-market-...
188,36,2026-07-06-17-58-04 +0000,nypost,Father of teen found dead in suitcase issues d...,https://nypost.com/2026/07/06/world-news/fathe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)