## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-30-23-53-23 +0000,nyt,Live Updates: Plane to Israel Narrowly Averts ...,https://www.nytimes.com/live/2026/09/30/world/...
1,2026-09-30-23-51-41 +0000,nyt,"Salah Sarsour, Islamic Leader in Wisconsin, Ca...",https://www.nytimes.com/2026/09/30/us/salah-sa...
2,2026-09-30-23-51-08 +0000,missionlocal,Survey says: San Franciscans feel city governm...,https://missionlocal.org/2026/09/san-francisco...
3,2026-09-30-23-49-24 +0000,nypost,Gavin Newsom targets ICE agents with shock-glo...,https://nypost.com/2026/09/30/us-news/californ...
4,2026-09-30-23-45-49 +0000,nypost,Pennsylvania records fifth measles death as co...,https://nypost.com/2026/09/30/health/pennsylva...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2384/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
93    trump     40
111      ai     22
235     new     17
3    israel     16
7     pilot     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
83,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...,190
321,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,123
248,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...,104
396,2026-09-30-08-01-44 +0000,nypost,"Israel-bound plane pilot stabbed by co-pilot, ...",https://nypost.com/2026/09/30/world-news/israe...,97
355,2026-09-30-10-15-54 +0000,cbc,Passengers foil bid to crash Dubai-Tel Aviv fl...,https://www.cbc.ca/news/world/flydubai-flight-...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
83,190,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...
329,86,2026-09-30-11-36-00 +0000,wsj,The Morning Risk Report: Trump Defends Light-T...,https://www.wsj.com/risk-compliance-journal/th...
321,70,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...
212,57,2026-09-30-17-42-44 +0000,nypost,Hero Israeli passenger reveals he saved flydub...,https://nypost.com/2026/09/30/world-news/flydu...
138,52,2026-09-30-20-28-00 +0000,wsj,Energy developers have clamored for years for ...,https://www.wsj.com/politics/policy/congress-w...
8,52,2026-09-30-23-40-53 +0000,nypost,Supreme Court clears the way for Christa Pike’...,https://nypost.com/2026/09/30/us-news/supreme-...
85,52,2026-09-30-21-31-42 +0000,nyt,UK Believes Iran Played a Part in RAF Fairford...,https://www.nytimes.com/2026/09/30/world/europ...
378,46,2026-09-30-09-30-00 +0000,wsj,China Has the Power to Bail Out the Diesel Mar...,https://www.wsj.com/business/energy-oil/china-...
339,44,2026-09-30-11-03-28 +0000,chitri,Hedge fund CEO Ken Griffin gives record $3B to...,https://www.chicagotribune.com/2026/09/30/ken-...
274,41,2026-09-30-14-37-42 +0000,nypost,Troy Jackson apologizes after saying Maine Jew...,https://nypost.com/2026/09/30/us-news/troy-jac...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)