## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-08-16-22-54 +0000,nypost,Three illegal immigrants carrying AK-style ass...,https://nypost.com/2026/07/08/us-news/three-il...
1,2026-07-08-16-18-38 +0000,nypost,"Trump, Italian Prime Minister Giorgia Meloni i...",https://nypost.com/2026/07/08/us-news/trump-it...
2,2026-07-08-16-18-09 +0000,wapo,"In shift, Trump praises Zelensky, will let Ukr...",https://www.washingtonpost.com/politics/2026/0...
3,2026-07-08-16-17-00 +0000,wsj,Opinion | Mamdani Emulates Elon Musk,https://www.wsj.com/opinion/mamdani-emulates-e...
4,2026-07-08-16-16-54 +0000,nyt,Live Updates: Trump Speaks After Lashing Out a...,https://www.nytimes.com/live/2026/07/08/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
11     trump     50
125     iran     36
360      new     18
20      nato     17
162  strikes     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
87,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...,141
97,2026-07-08-13-45-36 +0000,nypost,Trump promises he’ll hit Iran ‘hard’ for secon...,https://nypost.com/2026/07/08/world-news/trump...,140
146,2026-07-08-11-27-45 +0000,cbc,Carney backs latest U.S. strikes on Iran as Tr...,https://www.cbc.ca/news/politics/iran-war-us-c...,140
21,2026-07-08-15-59-29 +0000,nyt,Iran Live Updates: Trump Casts Doubt on Future...,https://www.nytimes.com/live/2026/07/08/world/...,128
53,2026-07-08-15-08-00 +0000,wsj,Oil Up 7% After Trump Warns of More Strikes on...,https://www.wsj.com/finance/commodities-future...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
87,141,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...
146,140,2026-07-08-11-27-45 +0000,cbc,Carney backs latest U.S. strikes on Iran as Tr...,https://www.cbc.ca/news/politics/iran-war-us-c...
338,65,2026-07-07-19-55-59 +0000,bbc,Marine Le Pen to run for French presidency and...,https://www.bbc.co.uk/news/articles/c7vygl3zym...
379,46,2026-07-07-17-27-23 +0000,nyt,Farage Says He Will Resign From UK’s Parliamen...,https://www.nytimes.com/live/2026/07/07/world/...
117,45,2026-07-08-13-03-34 +0000,nypost,"Family of Nolan Wells, teen football player fo...",https://nypost.com/2026/07/08/us-news/nolan-we...
38,40,2026-07-08-15-20-00 +0000,wsj,The IMF trimmed its global growth forecast to ...,https://www.wsj.com/economy/global/imf-drops-r...
347,39,2026-07-07-19-09-37 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...
90,37,2026-07-08-14-11-00 +0000,wsj,ADP to Launch Monthly Pay Tracking Indicator i...,https://www.wsj.com/economy/jobs/adp-to-launch...
260,36,2026-07-08-00-15-56 +0000,wapo,Foreign media were granted rare visas to cover...,https://www.washingtonpost.com/world/2026/07/0...
15,34,2026-07-08-16-05-01 +0000,startribune,"Oil prices rise 8%, and Dow drops 800 points a...",https://www.startribune.com/oil-prices-jump-af...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)