## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-16-23-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
1,2026-05-07-16-22-17 +0000,nypost,Mom has ‘very emotional’ meeting with woman wh...,https://nypost.com/2026/05/07/world-news/mom-h...
2,2026-05-07-16-21-01 +0000,nyt,Graham Platner and Susan Collins Duel in High-...,https://www.nytimes.com/2026/05/07/us/politics...
3,2026-05-07-16-20-52 +0000,bbc,Hantavirus outbreak on cruise ship not start o...,https://www.bbc.com/news/articles/cnvpzgn26edo...
4,2026-05-07-16-18-56 +0000,nyt,Iran War Live Updates: U.S. Awaits Tehran’s Re...,https://www.nytimes.com/live/2026/05/07/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
48       trump     31
38        iran     30
39         war     27
29  hantavirus     17
32        ship     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
239,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,139
23,2026-05-07-15-54-27 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...,110
212,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...,102
327,2026-05-06-20-16-58 +0000,nyt,Oil Prices Fall on Hope U.S.-Iran War Turmoil ...,https://www.nytimes.com/2026/05/06/business/oi...,99
165,2026-05-07-09-38-04 +0000,bbc,Shell latest oil giant to see profits surge du...,https://www.bbc.com/news/articles/ce3p0x54drwo...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
239,139,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
118,73,2026-05-07-12-06-25 +0000,nypost,Eerie moment cruise passengers told about firs...,https://nypost.com/2026/05/07/world-news/eerie...
166,66,2026-05-07-09-33-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
367,50,2026-05-06-17-38-42 +0000,nypost,Ex-JPMorgan banker Chirayu Rana was referred f...,https://nypost.com/2026/05/06/business/ex-jpmo...
46,46,2026-05-07-15-16-51 +0000,nypost,McDonald’s posts strong earnings — but viral C...,https://nypost.com/2026/05/07/business/mcdonal...
73,45,2026-05-07-14-16-02 +0000,nypost,UAE sneaked 4 oil tankers through Strait of Ho...,https://nypost.com/2026/05/07/world-news/uae-s...
245,45,2026-05-07-00-45-00 +0000,wsj,Commerce Secretary Howard Lutnick told a congr...,https://www.wsj.com/politics/policy/lutnick-sa...
58,45,2026-05-07-14-53-13 +0000,nypost,Ted Turner’s eerie CNN ‘doomsday video’ — only...,https://nypost.com/2026/05/07/media/ted-turner...
158,40,2026-05-07-10-00-00 +0000,latimes,"A shelter dog bit her 18 times. Now, Orange Co...",https://www.latimes.com/california/story/2026-...
292,38,2026-05-06-21-28-43 +0000,nypost,"Shivon Zilis, mother of Elon Musk’s kids and f...",https://nypost.com/2026/05/06/business/shivon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)