## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-06-00-09-00 +0000,wsj,Asian Currencies Consolidate Amid Wait-and-See...,https://www.wsj.com/finance/currencies/asian-c...
1,2026-08-06-00-08-45 +0000,nyt,Star Scholar Jason Arday Resigns From Cambridge,https://www.nytimes.com/2026/08/05/books/revie...
2,2026-08-06-00-06-49 +0000,nyt,Helicopter Carrying Trump Flew Near Passenger ...,https://www.nytimes.com/2026/08/05/us/politics...
3,2026-08-06-00-05-21 +0000,startribune,Minnesota woman hospitalized after eating Chip...,https://www.startribune.com/chipotle-salmonell...
4,2026-08-06-00-05-10 +0000,chitri,Speaker Welch told lawmakers he backed Harry B...,https://www.chicagotribune.com/2026/08/05/chri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2614/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
18      trump     35
87   michigan     34
92         el     27
148   primary     26
149    senate     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...,228
255,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...,202
36,2026-08-05-22-49-05 +0000,nyt,Abdul El-Sayed Wins Democratic Senate Primary ...,https://www.nytimes.com/2026/08/05/us/politics...,195
281,2026-08-05-13-57-05 +0000,nypost,Far-left Michigan Dem Abdul El-Sayed beats Rep...,https://nypost.com/2026/08/05/us-news/michigan...,193
16,2026-08-05-23-34-00 +0000,wsj,"Poll after poll had signaled Abdul El-Sayed, a...",https://www.wsj.com/politics/elections/pollste...,190

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,228,2026-08-05-20-56-00 +0000,wsj,Abdul El-Sayed’s victory in Michigan’s Democra...,https://www.wsj.com/politics/elections/progres...
166,100,2026-08-05-19-14-31 +0000,chitri,No evidence? No problem. President Donald Trum...,https://www.chicagotribune.com/2026/08/05/trum...
271,84,2026-08-05-14-15-00 +0000,wsj,Rep. Chuck Edwards said he wouldn’t seek re-el...,https://www.wsj.com/politics/elections/embattl...
254,66,2026-08-05-15-03-44 +0000,nypost,"Disney earnings boosted by ‘Toy Story 5’, them...",https://nypost.com/2026/08/05/business/disney-...
389,64,2026-08-05-03-44-30 +0000,bbc,Trump says Iran will be 'hit very hard' if Hor...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
67,60,2026-08-05-21-58-00 +0000,wsj,The Senate confirmed Dr. Erica Schwartz as dir...,https://www.wsj.com/politics/policy/senate-con...
278,47,2026-08-05-14-04-43 +0000,bbc,SpaceX shares sink after first earnings report...,https://www.bbc.co.uk/news/articles/c0qvpveg20...
179,43,2026-08-05-18-47-00 +0000,wsj,Missouri residents overwhelmingly defeated a b...,https://www.wsj.com/politics/policy/missouri-v...
353,40,2026-08-05-10-00-00 +0000,latimes,Energy company profits are soaring with the Ir...,https://www.latimes.com/environment/story/2026...
246,38,2026-08-05-15-31-36 +0000,nyt,Russia’s Deadly Missile Attack on Kyiv Exploit...,https://www.nytimes.com/2026/08/05/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)