## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-14-09-57-39 +0000,nyt,UK Forces Seize Russian Shadow Fleet Oil Tanker,https://www.nytimes.com/2026/06/14/world/europ...
1,2026-06-14-09-56-32 +0000,bbc,UK armed forces board Russian shadow fleet oil...,https://www.bbc.com/news/articles/clyek039l2vo...
2,2026-06-14-09-56-02 +0000,nypost,Influx of out-of-state agitators with links to...,https://nypost.com/2026/06/14/us-news/nj-delan...
3,2026-06-14-09-30-00 +0000,wsj,With endorsements in key New York City congres...,https://www.wsj.com/politics/elections/zohran-...
4,2026-06-14-09-30-00 +0000,wsj,A Guide to the Biggest Winners From the SpaceX...,https://www.wsj.com/finance/investing/spacex-i...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2575/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     28
113  world     16
143    cup     12
53    iran     10
28     new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
130,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...,74
164,2026-06-13-12-54-19 +0000,cbc,Trump says peace deal with Iran will be signed...,https://www.cbc.ca/news/world/pakistan-us-iran...,72
143,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...,62
146,2026-06-13-15-30-30 +0000,nypost,Trump set to meet with Middle East leaders nex...,https://nypost.com/2026/06/13/us-news/trump-se...,60
33,2026-06-14-07-55-16 +0000,bbc,Trump says US-Iran deal to be signed on Sunday...,https://www.bbc.com/news/articles/cvglmn49xz0o...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
130,74,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...
71,48,2026-06-14-00-00-54 +0000,nypost,Mexican trade group leader fired after racist ...,https://nypost.com/2026/06/13/world-news/mexic...
38,35,2026-06-14-07-21-26 +0000,bbc,New York Knicks win NBA championship for first...,https://www.bbc.com/news/articles/c78yw4zw19do...
143,34,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...
91,27,2026-06-13-22-05-24 +0000,bbc,Vincent's parents 'never say he's good enough'...,https://www.bbc.com/news/articles/cpq3dnr5vlzo...
1,26,2026-06-14-09-56-32 +0000,bbc,UK armed forces board Russian shadow fleet oil...,https://www.bbc.com/news/articles/clyek039l2vo...
106,25,2026-06-13-20-39-10 +0000,nypost,NYC Councilwoman failed to disclose free rent ...,https://nypost.com/2026/06/13/us-news/nyc-coun...
124,24,2026-06-13-18-17-28 +0000,nypost,Shocking three-word tweet aimed at Elon Musk u...,https://nypost.com/2026/06/13/tech/california-...
37,23,2026-06-14-07-24-35 +0000,nypost,Knicks fans set school bus on fire in Times Sq...,https://nypost.com/2026/06/14/us-news/knicks-f...
132,22,2026-06-13-16-50-47 +0000,nyt,A Tren de Aragua Leader Is Killed in a Joint S...,https://www.nytimes.com/2026/06/13/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)