## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-12-07-39-45 +0000,bbc,China evacuates nearly two million people as p...,https://www.bbc.co.uk/news/articles/cdxd3wkp2r...
1,2026-07-12-07-33-12 +0000,bbc,US Senator Lindsey Graham dies after 'brief an...,https://www.bbc.co.uk/news/articles/cvgj25j6nm...
2,2026-07-12-07-24-55 +0000,nyt,Oil Prices Set for More Volatility After Lates...,https://www.nytimes.com/2026/07/11/world/middl...
3,2026-07-12-07-17-40 +0000,nyt,"Typhoon Bavi Hits China, Causing Evacuations, ...",https://www.nytimes.com/2026/07/12/world/asia/...
4,2026-07-12-07-02-17 +0000,bbc,"Londoners face hidden poverty premium, study says",https://www.bbc.co.uk/news/articles/c33yxe2ey2...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2480/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
81   trump     22
44     new     13
55    iran     13
302  world     12
303    cup     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
56,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,89
105,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,84
57,2026-07-11-23-18-00 +0000,wsj,Trump Administration Subpoenas New York Times ...,https://www.wsj.com/politics/policy/trump-admi...,84
107,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,84
122,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
56,89,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
36,52,2026-07-12-01-08-40 +0000,nyt,U.S. Strikes Iran After Iran Fires on Ship in ...,https://www.nytimes.com/2026/07/11/world/middl...
6,45,2026-07-12-06-58-00 +0000,wsj,Longtime Republican Sen. Lindsey Graham has di...,https://www.wsj.com/politics/lindsey-graham-lo...
113,42,2026-07-11-15-26-13 +0000,cbc,South African midfielder Jayden Adams dies at ...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
167,36,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
72,34,2026-07-11-21-23-38 +0000,nypost,Ro Khanna blew off offer to meet former Israel...,https://nypost.com/2026/07/11/world-news/ro-kh...
24,32,2026-07-12-02-53-34 +0000,nypost,"Popular local musicians, DJ killed in fiery Ba...",https://nypost.com/2026/07/11/world-news/popul...
0,26,2026-07-12-07-39-45 +0000,bbc,China evacuates nearly two million people as p...,https://www.bbc.co.uk/news/articles/cdxd3wkp2r...
103,25,2026-07-11-16-50-06 +0000,nypost,Maine event: Dems descend into chaos over Plat...,https://nypost.com/2026/07/11/us-news/maine-de...
98,22,2026-07-11-17-34-03 +0000,nypost,Lefty California Dem drops veiled threat to ID...,https://nypost.com/2026/07/11/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)