## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-17-17-54-57 +0000,nypost,Man threatened to blow up LA Jewish Preschool ...,https://nypost.com/2026/10/17/us-news/la-man-f...
1,2026-10-17-17-54-05 +0000,nyt,Dispute Between Trump Allies Centers on Paymen...,https://www.nytimes.com/2026/10/17/us/politics...
2,2026-10-17-17-53-54 +0000,nypost,Hero dad who killed Oregon shooter stalked gun...,https://nypost.com/2026/10/17/us-news/hero-dad...
3,2026-10-17-17-51-27 +0000,nypost,Urgent warning as super-drug 10 times more pow...,https://nypost.com/2026/10/17/us-news/urgent-w...
4,2026-10-17-17-41-37 +0000,startribune,"Modern Times, the restaurant that had no price...",https://www.startribune.com/modern-times-the-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2391/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     37
248     new     20
30   school     18
190      he     14
429   white     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
143,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,134
28,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...,122
125,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...,116
207,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...,107
36,2026-10-17-15-25-00 +0000,wsj,President Trump is halting implementation of m...,https://www.wsj.com/politics/policy/trump-waiv...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
143,134,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
125,69,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...
149,59,2026-10-17-01-12-39 +0000,nyt,Teacher Killed in Oregon School Shooting Was W...,https://www.nytimes.com/2026/10/16/us/bend-sch...
133,45,2026-10-17-02-10-04 +0000,nypost,"Pope Leo XIV calls Putin, urges cease-fire as ...",https://nypost.com/2026/10/16/world-news/pope-...
216,41,2026-10-16-20-35-28 +0000,nypost,AI stock sell-off ramps up over debt-fueled da...,https://nypost.com/2026/10/16/business/ai-stoc...
114,32,2026-10-17-06-29-36 +0000,nypost,Ilhan Omar’s sister skips book tour event amid...,https://nypost.com/2026/10/17/us-news/ilhan-om...
261,32,2026-10-16-18-16-00 +0000,wsj,Elon Musk is putting a small fortune into Repu...,https://www.wsj.com/politics/elections/elon-mu...
155,29,2026-10-17-00-48-52 +0000,nypost,Ukraine’s strikes on Russian oil refineries is...,https://nypost.com/2026/10/16/world-news/ukrai...
207,28,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...
43,28,2026-10-17-15-00-00 +0000,nypost,Father’s execution of two sons leaves LA famil...,https://nypost.com/2026/10/17/us-news/disturbi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)