## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-22-54-25 +0000,wapo,U.S. orders more diplomats to leave Middle East,https://www.washingtonpost.com/national-securi...
1,2026-03-09-22-52-44 +0000,nypost,Ohio State President Ted Carter blew up $1.5M ...,https://nypost.com/2026/03/09/us-news/ohio-sta...
2,2026-03-09-22-52-26 +0000,nyt,Talent Agent Ari Emanuel Launches His Own Podc...,https://www.nytimes.com/2026/03/09/business/ar...
3,2026-03-09-22-52-20 +0000,nypost,Tragic NYPD cop who died in Mideast was highly...,https://nypost.com/2026/03/09/us-news/nypd-cop...
4,2026-03-09-22-51-56 +0000,nyt,Live Updates: Trump Sends Conflicting Messages...,https://www.nytimes.com/live/2026/03/09/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2631/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
49    iran     61
45     war     40
40   trump     32
120    new     29
50     oil     29

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
210,2026-03-09-14-48-23 +0000,wapo,Iran rallies around new leader after 10 days o...,https://www.washingtonpost.com/world/2026/03/0...,198
136,2026-03-09-18-53-40 +0000,nypost,US sends Cold War heavy-hitter B-52 bombers to...,https://nypost.com/2026/03/09/world-news/us-se...,188
195,2026-03-09-15-50-17 +0000,nypost,Trump tells The Post there’s no reason to pani...,https://nypost.com/2026/03/09/us-news/trump-te...,186
205,2026-03-09-14-54-27 +0000,nypost,Trump tells Post he’s ‘nowhere near’ ordering ...,https://nypost.com/2026/03/09/us-news/trump-te...,172
240,2026-03-09-12-24-11 +0000,nypost,Trump says he and Israel’s Netanyahu will make...,https://nypost.com/2026/03/09/us-news/trump-sa...,166

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
210,198,2026-03-09-14-48-23 +0000,wapo,Iran rallies around new leader after 10 days o...,https://www.washingtonpost.com/world/2026/03/0...
243,111,2026-03-09-12-21-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...
126,56,2026-03-09-19-31-04 +0000,nypost,Trump will back taking out Khamenei’s impotent...,https://nypost.com/2026/03/09/world-news/trump...
303,55,2026-03-09-03-56-54 +0000,wapo,Video appears to show U.S. Tomahawk hit naval ...,https://www.washingtonpost.com/investigations/...
275,47,2026-03-09-09-30-00 +0000,wsj,The surge in oil and gasoline prices last week...,https://www.wsj.com/economy/central-banking/is...
57,41,2026-03-09-21-29-00 +0000,wsj,Live Nation Reaches Tentative Deal With Justic...,https://www.wsj.com/us-news/law/live-nation-re...
253,40,2026-03-09-11-30-53 +0000,nypost,AI startup’s CEO threatened to call ex-NYC May...,https://nypost.com/2026/03/09/business/ai-star...
98,33,2026-03-09-20-39-36 +0000,nypost,Texas Dem Senate hopeful James Talarico ‘proud...,https://nypost.com/2026/03/09/us-news/james-ta...
41,33,2026-03-09-21-52-00 +0000,wsj,Lawrence Summers has lost his affiliation with...,https://www.wsj.com/us-news/education/national...
1,33,2026-03-09-22-52-44 +0000,nypost,Ohio State President Ted Carter blew up $1.5M ...,https://nypost.com/2026/03/09/us-news/ohio-sta...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)