## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-16-22-52-51 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...
1,2026-08-16-22-51-48 +0000,nypost,California farmer who sparked frenzied crowds ...,https://nypost.com/2026/08/16/us-news/californ...
2,2026-08-16-22-51-20 +0000,nypost,"Iran offering $30,000 bounty for the slaughter...",https://nypost.com/2026/08/16/world-news/iran-...
3,2026-08-16-22-46-48 +0000,nypost,Fauci was told about questions over COVID-19 v...,https://nypost.com/2026/08/16/us-news/fauci-wa...
4,2026-08-16-22-44-26 +0000,startribune,"Built to win now, the Phillies keep showing th...",https://www.startribune.com/minnesota-twins-ph...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
0        trump     22
40         new     13
24        iran     10
12  california      9
53         war      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
105,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...,70
5,2026-08-16-22-41-34 +0000,bbc,Trump says US to scale back military drills wi...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,66
42,2026-08-16-19-58-14 +0000,bbc,Trump envoy Kushner meets Hamas leader to push...,https://www.bbc.co.uk/news/articles/c77gg5vn44...,54
36,2026-08-16-20-26-22 +0000,nypost,Iran betting it can outlast Trump if Dems take...,https://nypost.com/2026/08/16/us-news/iran-bet...,49
0,2026-08-16-22-52-51 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
105,70,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...
85,44,2026-08-16-17-39-39 +0000,nyt,"As Iran War Turns Into Economic Battle, a New ...",https://www.nytimes.com/2026/08/16/world/middl...
83,36,2026-08-16-17-50-32 +0000,chitri,US envoy Kushner meets Hamas’ leader in push f...,https://www.chicagotribune.com/2026/08/16/kush...
178,32,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...
45,30,2026-08-16-19-56-39 +0000,nypost,Gavin Newsom wildfire plan faces revolt over w...,https://nypost.com/2026/08/16/us-news/gavin-ne...
102,30,2026-08-16-15-19-52 +0000,nypost,Ex-Mamdani campaign staffer makes outrageous c...,https://nypost.com/2026/08/16/us-news/ex-mamda...
15,26,2026-08-16-21-33-07 +0000,latimes,Judge nixes Meta's attempts to quash star witn...,https://www.latimes.com/california/story/2026-...
75,26,2026-08-16-18-23-50 +0000,nypost,GOP Rep. Mike Lawler eyes nuclear power plant ...,https://nypost.com/2026/08/16/us-news/gop-rep-...
138,26,2026-08-16-10-51-59 +0000,nypost,Four Renaissance paintings of ‘extraordinary v...,https://nypost.com/2026/08/16/world-news/anton...
86,25,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)