## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-16-14-20 +0000,bbc,Trump family's crypto firm sued over alleged '...,https://www.bbc.com/news/articles/c8x7kxjgq9xo...
1,2026-04-22-16-13-55 +0000,bbc,PM's ex-chief of staff to give evidence on Man...,https://www.bbc.com/news/articles/c5yjl1pmv55o...
2,2026-04-22-16-11-22 +0000,nypost,Revolutionary War artifacts discovered at site...,https://nypost.com/2026/04/22/us-news/revoluti...
3,2026-04-22-16-10-10 +0000,nyt,Iran War Live Updates: Iranian Forces Claim to...,https://www.nytimes.com/live/2026/04/22/world/...
4,2026-04-22-16-09-22 +0000,bbc,Red Rooster festival cancelled due to rising c...,https://www.bbc.com/news/articles/cvg0yg5l4leo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     45
24    iran     38
216    new     21
356     up     19
16     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
377,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,193
231,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,150
174,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,144
83,2026-04-22-13-18-40 +0000,nypost,Trump tells The Post news of fresh peace talks...,https://nypost.com/2026/04/22/us-news/trump-te...,144
127,2026-04-22-10-45-39 +0000,bbc,Oil prices fluctuate as Trump extends Iran war...,https://www.bbc.com/news/articles/c995dkl4dvvo...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
377,193,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
139,78,2026-04-22-10-00-00 +0000,latimes,He was the real Marty Supreme's landlord. Now ...,https://www.latimes.com/entertainment-arts/bus...
100,61,2026-04-22-12-50-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
364,48,2026-04-21-18-54-04 +0000,nyt,Two Palestinians Killed in Israeli Shooting Ne...,https://www.nytimes.com/2026/04/21/world/middl...
281,48,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
166,47,2026-04-22-08-51-58 +0000,nypost,Mexico pyramid shooter Julio César Jasso plann...,https://nypost.com/2026/04/22/world-news/mexic...
50,46,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...
17,43,2026-04-22-15-49-06 +0000,nyt,Crypto Entrepreneur Justin Sun Sues Trump Fami...,https://www.nytimes.com/2026/04/22/technology/...
174,42,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...
59,41,2026-04-22-14-12-22 +0000,nypost,"Teenager, 17, accused of heinous sex crimes ag...",https://nypost.com/2026/04/22/us-news/teen-cha...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)