## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-08-15-27 +0000,wsj,Stocks Waver With Shaky Cease-Fire in Focus,https://www.wsj.com/livecoverage/cpi-inflation...
1,2026-04-10-08-11-13 +0000,nypost,Chicago dad Alexander Kazanowski beaten to dea...,https://nypost.com/2026/04/10/us-news/chicago-...
2,2026-04-10-08-07-25 +0000,nyt,Oil Goes Higher and Stocks Rise Ahead of U.S. ...,https://www.nytimes.com/2026/04/10/business/oi...
3,2026-04-10-08-00-00 +0000,cbc,Saab dangles sovereign data centre in Montreal...,https://www.cbc.ca/news/politics/saab-lockheed...
4,2026-04-10-08-00-00 +0000,cbc,"Immigration Department informing some 30,000 a...",https://www.cbc.ca/news/politics/immigration-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
45    trump     39
60     iran     37
61      war     24
4      fire     20
67  lebanon     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
256,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...,156
137,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,149
8,2026-04-10-07-55-03 +0000,nyt,Iran War Live Updates: Israel Strikes Hezbolla...,https://www.nytimes.com/live/2026/04/10/world/...,146
335,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,137
140,2026-04-09-21-51-17 +0000,nypost,"Trump goes off on ‘NUT JOBS’ Tucker Carlson, ...",https://nypost.com/2026/04/09/us-news/trump-go...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
256,156,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...
180,80,2026-04-09-20-18-00 +0000,wsj,First lady Melania Trump denied having ties to...,https://www.wsj.com/politics/melania-trump-den...
40,75,2026-04-10-03-21-00 +0000,wsj,A surge in energy costs triggered by the war i...,https://www.wsj.com/world/china/middle-east-en...
113,66,2026-04-09-22-44-20 +0000,nypost,Israel launches new strikes on Lebanon as Kuwa...,https://nypost.com/2026/04/09/world-news/israe...
137,47,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
127,46,2026-04-09-22-16-15 +0000,latimes,Man was shot at by ICE agents in Northern Cali...,https://www.latimes.com/california/story/2026-...
123,45,2026-04-09-22-23-35 +0000,latimes,A sea turtle named Meatloaf is fighting to kee...,https://www.latimes.com/california/story/2026-...
27,43,2026-04-10-05-42-41 +0000,nypost,Texas lawyer no-shows jerk judge’s order to ap...,https://nypost.com/2026/04/10/us-news/lawyers-...
138,43,2026-04-09-21-53-20 +0000,cbc,Putin claims Russia will enact 32-hour ceasefi...,https://www.cbc.ca/news/world/ukraine-conflict...
304,34,2026-04-09-13-54-13 +0000,cbc,K-pop supergroup BTS kick off world tour in So...,https://www.cbc.ca/news/entertainment/bts-worl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)