## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-18-52-38 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/25/world/...
1,2026-10-25-18-52-31 +0000,nyt,María Corina Machado Returns to Venezuela,https://www.nytimes.com/2026/10/25/world/ameri...
2,2026-10-25-18-52-12 +0000,nypost,Alaska Dem Mary Peltola in car crash during fi...,https://nypost.com/2026/10/25/us-news/alaska-d...
3,2026-10-25-18-49-38 +0000,nyt,What’s at Stake in Brazil’s Elections?,https://www.nytimes.com/2026/10/25/world/ameri...
4,2026-10-25-18-48-52 +0000,nypost,"Troy Jackson officiated his wedding, but this ...",https://nypost.com/2026/10/25/us-news/troy-jac...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2337/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
39      trump     20
335        he     11
43        new     11
40   election     11
241       her      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
158,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...,66
154,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,65
181,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,64
147,2026-10-25-02-27-15 +0000,bbc,Obama attacks Trump as he campaigns for Democr...,https://www.bbc.co.uk/news/articles/cmj6jwe1j1...,57
199,2026-10-24-20-23-36 +0000,chitri,Elon Musk says he was behind Starlink speed re...,https://www.chicagotribune.com/2026/10/24/musk...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
158,66,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
181,64,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...
199,54,2026-10-24-20-23-36 +0000,chitri,Elon Musk says he was behind Starlink speed re...,https://www.chicagotribune.com/2026/10/24/musk...
169,40,2026-10-24-23-35-22 +0000,chitri,"Brazil’s Lula, Bolsonaro close arguments to vo...",https://www.chicagotribune.com/2026/10/24/braz...
29,30,2026-10-25-17-26-26 +0000,nypost,Ex-con former Dem Ill. Gov. Rod Blagojevich ur...,https://nypost.com/2026/10/25/us-news/ex-con-f...
15,29,2026-10-25-18-05-05 +0000,startribune,Venezuela's opposition leader Machado returns ...,https://www.startribune.com/opposition-leader-...
35,27,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
67,26,2026-10-25-14-00-37 +0000,nypost,Obama’s ‘Saddam Hussein’s Cheesecake Factory’ ...,https://nypost.com/2026/10/25/us-news/obamas-s...
131,26,2026-10-25-07-05-30 +0000,bbc,Will a new code end 'rip-off parking charges'?,https://www.bbc.co.uk/news/articles/ckjwe90z56...
189,26,2026-10-24-21-45-00 +0000,nypost,5 signs you may not know you’re drowning in cr...,https://nypost.com/business/credit-card-debt-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)