## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-11-01-22-31 +0000,nypost,Moment Frontier Airlines plane strikes person ...,https://nypost.com/2026/05/10/us-news/moment-f...
1,2026-05-11-01-22-00 +0000,bbc,"Thailand's divisive ex-PM is out of jail, but ...",https://www.bbc.com/news/articles/c99l1590kr0o...
2,2026-05-11-01-19-00 +0000,startribune,Live from Game 4: Timberwolves battle Spurs in...,https://www.startribune.com/live-from-game-4-t...
3,2026-05-11-01-15-17 +0000,48hills,San Francisco could tax the rich—locally—and a...,https://48hills.org/2026/05/san-francisco-coul...
4,2026-05-11-01-10-00 +0000,wsj,Yen Mostly Weakens Amid Mild Risk-on Sentiment,https://www.wsj.com/finance/currencies/yen-mos...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
96        trump     19
97         iran     15
314  hantavirus     11
111         war     10
249  california      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
151,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,71
61,2026-05-10-20-57-22 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,66
12,2026-05-11-00-48-29 +0000,nyt,Trump Says Iran’s Response to Latest U.S. Prop...,https://www.nytimes.com/2026/05/10/us/politics...,52
97,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...,50
154,2026-05-10-12-51-58 +0000,cbc,Trump calls ceasefire counter-proposal from Ir...,https://www.cbc.ca/news/world/iran-us-ceasefir...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
151,71,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
92,46,2026-05-10-19-09-51 +0000,nyt,"Fearing an All-Republican Governor’s Race, Dem...",https://www.nytimes.com/2026/05/10/us/californ...
97,41,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...
167,32,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...
29,30,2026-05-10-23-32-40 +0000,bbc,"This couple lost £1,000 after their flight was...",https://www.bbc.com/news/articles/cx215yldr13o...
175,30,2026-05-10-10-06-32 +0000,nypost,NYPD captain’s transfer after viral rant bashi...,https://nypost.com/2026/05/10/us-news/nypd-cap...
173,30,2026-05-10-10-35-13 +0000,nyt,"Punch, the Lonely Monkey Who Drew Crowds to a ...",https://www.nytimes.com/2026/05/09/world/asia/...
86,26,2026-05-10-19-50-47 +0000,nypost,Kennedy scion Jack Schlossberg opposes militar...,https://nypost.com/2026/05/10/us-news/jack-sch...
177,25,2026-05-10-10-00-44 +0000,wapo,N.J. World Cup games will be in a county that ...,https://www.washingtonpost.com/nation/2026/05/...
119,24,2026-05-10-16-00-00 +0000,wsj,The Simple Fix Small-Town Schools Are Using to...,https://www.wsj.com/personal-finance/the-simpl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)