## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-16-13-11 +0000,nypost,US wastewater will be screened for disease out...,https://nypost.com/2026/06/08/us-news/us-waste...
1,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
2,2026-06-08-16-07-00 +0000,wsj,"Gold Trims Losses After Israel, Iran Halt Exch...",https://www.wsj.com/finance/commodities-future...
3,2026-06-08-16-03-40 +0000,nyt,"In Maine, Supporters of Graham Platner Continu...",https://www.nytimes.com/2026/06/08/us/politics...
4,2026-06-08-16-03-29 +0000,startribune,"A rivalry begins: Gophers, St. Thomas to meet ...",https://www.startribune.com/minnesota-gophers-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
22     iran     27
21   israel     26
218   trump     21
154     new     14
316  market      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
219,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...,102
122,2026-06-08-10-04-21 +0000,nypost,Iran says it’s halting Israel attacks after Tr...,https://nypost.com/2026/06/08/us-news/trump-sa...,88
94,2026-06-08-11-42-45 +0000,latimes,Iran and Israel trade fire then halt after Tru...,https://www.latimes.com/world-nation/story/202...,88
30,2026-06-08-15-12-59 +0000,bbc,Iran says it has halted attacks on Israel afte...,https://www.bbc.com/news/articles/cj6ge150z5go...,80
216,2026-06-07-21-10-44 +0000,nyt,Iran Fires Missiles at Israel for First Time S...,https://www.nytimes.com/2026/06/07/world/middl...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
219,102,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...
162,60,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
211,45,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
22,42,2026-06-08-15-24-29 +0000,nypost,"NYPD, Secret Service announce NBA Finals Game ...",https://nypost.com/2026/06/08/us-news/nypd-sec...
191,42,2026-06-08-01-00-00 +0000,wsj,"Most rankings of companies look backward, meas...",https://www.wsj.com/economy/jobs/best-companie...
43,38,2026-06-08-14-14-11 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
1,37,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
39,35,2026-06-08-14-22-33 +0000,nypost,Father and 10-year-old twin sons shot dead in ...,https://nypost.com/2026/06/08/us-news/father-a...
62,33,2026-06-08-13-47-47 +0000,nyt,Mexico City’s Airport Got a $500 Million Renov...,https://www.nytimes.com/2026/06/07/world/ameri...
102,27,2026-06-08-11-09-00 +0000,wsj,Spencer Pratt’s L.A. mayor hopes fade as he sl...,https://www.wsj.com/politics/spencer-pratts-l-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)