## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-16-22-50-24 +0000,nyt,Bend Shooting Likely to Heighten Gun Debate in...,https://www.nytimes.com/2026/10/16/us/bend-ore...
1,2026-10-16-22-49-00 +0000,wsj,A Father and a Teacher Risked Their Lives to S...,https://www.wsj.com/us-news/a-father-and-a-tea...
2,2026-10-16-22-46-56 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/16/us/ben...
3,2026-10-16-22-46-44 +0000,nypost,Long Island Dem Tom Suozzi blows off Hochul ca...,https://nypost.com/2026/10/16/us-news/li-dem-t...
4,2026-10-16-22-45-38 +0000,nyt,What We Know About the Shooter at an Oregon Sc...,https://www.nytimes.com/2026/10/16/us/oregon-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
32    trump     35
15   school     25
6    oregon     16
130      up     15
40      new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
78,2026-10-16-19-51-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,139
42,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...,114
292,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...,109
25,2026-10-16-21-50-22 +0000,nypost,Press secretary Katie Zacharia was the shortes...,https://nypost.com/2026/10/16/us-news/press-se...,90
17,2026-10-16-22-10-04 +0000,nypost,"Teacher, 25, killed by Oregon school shooter I...",https://nypost.com/2026/10/16/us-news/teacher-...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
78,139,2026-10-16-19-51-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
17,89,2026-10-16-22-10-04 +0000,nypost,"Teacher, 25, killed by Oregon school shooter I...",https://nypost.com/2026/10/16/us-news/teacher-...
297,62,2026-10-16-04-41-00 +0000,wsj,Fed Chairman Kevin Warsh declined to endorse o...,https://www.wsj.com/economy/central-banking/wa...
42,61,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...
119,51,2026-10-16-18-16-00 +0000,wsj,Elon Musk is putting a small fortune into Repu...,https://www.wsj.com/politics/elections/elon-mu...
145,50,2026-10-16-16-16-07 +0000,chitri,Tesla’s new Roadster car can thrust itself in ...,https://www.chicagotribune.com/2026/10/16/tesl...
35,50,2026-10-16-21-39-00 +0000,wsj,Defense Secretary Pete Hegseth said the execut...,https://www.wsj.com/politics/national-security...
172,45,2026-10-16-14-34-39 +0000,cbc,"Israeli settlers attack Palestinians, American...",https://www.cbc.ca/news/world/israeli-settlers...
74,42,2026-10-16-20-01-00 +0000,wsj,"Oil Futures Rise on Middle East, Russia-Ukrain...",https://www.wsj.com/business/energy-oil/oil-pr...
252,38,2026-10-16-10-00-00 +0000,nypost,Amazon said it may move thousands of workers o...,https://nypost.com/2026/10/16/business/amazon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)