## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-11-23-54-20 +0000,nypost,Bouncy castle ‘superbug’ outbreak sickened 48 ...,https://nypost.com/2026/09/11/world-news/bounc...
1,2026-09-11-23-35-22 +0000,nypost,Masked ‘total stranger’ rapes woman making del...,https://nypost.com/2026/09/11/us-news/masked-t...
2,2026-09-11-23-30-00 +0000,nypost,UCLA chancellor hammers own college for hostin...,https://nypost.com/2026/09/11/us-news/ucla-cha...
3,2026-09-11-23-29-07 +0000,startribune,Byron Buxton’s season is over. With the Twins ...,https://www.startribune.com/minnesota-twins-by...
4,2026-09-11-23-27-18 +0000,bbc,Reform receives record £36m donation from cryp...,https://www.bbc.co.uk/news/articles/c3v4zvyde1...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
265       trump     38
780  convention     21
170          ai     18
288        iran     16
149         oil     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
346,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...,133
338,2026-09-11-02-51-48 +0000,nypost,Trump leads GOP midterm convention attendees i...,https://nypost.com/2026/09/10/us-news/trump-le...,118
335,2026-09-11-03-21-00 +0000,wsj,JD Vance delivered a future-looking speech on ...,https://www.wsj.com/politics/elections/key-tak...,108
329,2026-09-11-05-02-20 +0000,nypost,JD Vance steals 2028 show at GOP convention — ...,https://nypost.com/2026/09/11/us-news/jd-vance...,107
45,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
346,133,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...
351,100,2026-09-11-01-58-47 +0000,nypost,"Protester heckles JD Vance, spices up his GOP ...",https://nypost.com/2026/09/10/us-news/proteste...
124,96,2026-09-11-18-19-00 +0000,wsj,The annual inflation rate stalled out last mon...,https://www.wsj.com/economy/cpi-inflation-repo...
348,86,2026-09-11-02-08-00 +0000,wsj,"After years of inaction, Congress is suddenly ...",https://www.wsj.com/politics/policy/congress-i...
34,75,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...
349,72,2026-09-11-02-05-07 +0000,nyt,“When Medicaid programs for homeless or expect...,https://www.nytimes.com/live/2026/09/10/us/tru...
80,44,2026-09-11-20-06-50 +0000,nypost,Lindsay Clancy’s coworker reveals killer mom’s...,https://nypost.com/2026/09/11/us-news/lindsay-...
7,43,2026-09-11-23-15-00 +0000,wsj,New Jersey Gov. Mikie Sherrill is facing the s...,https://www.wsj.com/politics/policy/misconduct...
11,43,2026-09-11-23-00-23 +0000,nypost,Michigan Dem Abdul El-Sayed condemns ‘cruel’ ...,https://nypost.com/2026/09/11/us-news/abdul-el...
163,42,2026-09-11-16-56-21 +0000,nypost,California’s most powerful union boss threaten...,https://nypost.com/2026/09/11/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)