## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-15-11-54-35 +0000,nyt,"Meet Neha Bora, Activist and Face of India’s Y...",https://www.nytimes.com/2026/10/15/world/asia/...
1,2026-10-15-11-54-08 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...
2,2026-10-15-11-53-53 +0000,nyt,Why Does Saudi Arabia Struggle to Stop Houthi ...,https://www.nytimes.com/2026/10/15/world/middl...
3,2026-10-15-11-53-00 +0000,wsj,White House Press Secretary Katie Zacharia Did...,https://www.wsj.com/business/media/white-house...
4,2026-10-15-11-48-12 +0000,nypost,Girlfiend killed beau by deliberately crashing...,https://nypost.com/2026/10/15/us-news/girlfien...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2374/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
16       trump     29
125        new     21
9      ukraine     20
321  inflation     19
64          ai     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
345,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...,113
373,2026-10-14-15-25-31 +0000,nyt,Democrats Blame Trump After CPI Report Shows E...,https://www.nytimes.com/2026/10/14/business/ec...,109
1,2026-10-15-11-54-08 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...,86
195,2026-10-14-23-06-56 +0000,nypost,Elon Musk points to Trump for Starshield throt...,https://nypost.com/2026/10/14/world-news/elon-...,86
117,2026-10-15-08-00-08 +0000,nyt,Katie Zacharia Is Trump’s New Press Secretary....,https://www.nytimes.com/2026/10/14/us/politics...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
345,113,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...
1,86,2026-10-15-11-54-08 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...
154,85,2026-10-15-03-25-00 +0000,wsj,Texas Democrat and Senate hopeful James Talari...,https://www.wsj.com/politics/elections/five-ta...
209,78,2026-10-14-22-35-00 +0000,wsj,The federal investigation into Rep. Ilhan Omar...,https://www.wsj.com/politics/policy/ilhan-omar...
182,77,2026-10-15-00-02-03 +0000,cbc,New White House press secretary Katie Zacharia...,https://www.cbc.ca/news/world/katie-zacharia-r...
205,64,2026-10-14-22-39-46 +0000,chitri,Chicago prays for native son Pope Leo XIV as h...,https://www.chicagotribune.com/2026/10/14/chic...
7,52,2026-10-15-11-34-55 +0000,bbc,AI giant Anthropic woos potential investors ah...,https://www.bbc.co.uk/news/articles/cqzjx448vx...
272,51,2026-10-14-20-12-00 +0000,wsj,Oil Prices Rise as Traders Weigh Saudi Aramco ...,https://www.wsj.com/business/energy-oil/oil-pr...
35,50,2026-10-15-10-58-00 +0000,wsj,A WSJ poll finds resistance among Democrats to...,https://www.wsj.com/politics/how-liberal-is-th...
302,42,2026-10-14-18-39-00 +0000,wsj,"For years, China flooded Europe with exports t...",https://www.wsj.com/economy/trade/with-china-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)