## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-29-10-46-16 +0000,nyt,A Movie Night in Cuba’s Blackout,https://www.nytimes.com/video/world/americas/1...
1,2026-07-29-10-42-17 +0000,bbc,European wildfires in maps - and how they're b...,https://www.bbc.co.uk/news/articles/cj638jx0l5...
2,2026-07-29-10-41-04 +0000,nyt,Iran War Live Updates: U.S. and Saudi Airstrik...,https://www.nytimes.com/live/2026/07/28/world/...
3,2026-07-29-10-41-02 +0000,nyt,Global Oil Prices Jump as Attacks Resume in th...,https://www.nytimes.com/2026/07/29/business/oi...
4,2026-07-29-10-37-47 +0000,nyt,"Summer of Heat, Fires and Storms Is a Reckonin...",https://www.nytimes.com/2026/07/29/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2460/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
314   trump     33
138     new     25
347  graham     19
10     iran     18
20      oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
222,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,123
316,2026-07-28-17-39-53 +0000,nypost,Senate confirms Manhattan US Attorney Jay Clay...,https://nypost.com/2026/07/28/us-news/senate-c...,101
285,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,97
42,2026-07-29-09-07-40 +0000,bbc,Trump's new spy chief Jay Clayton confirmed by...,https://www.bbc.co.uk/news/articles/c0rd1kl182...,89
217,2026-07-28-21-38-37 +0000,bbc,Lindsey Graham remembered by Trump as 'giant o...,https://www.bbc.co.uk/news/articles/cwyj6xqn40...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
222,123,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
40,84,2026-07-29-09-30-00 +0000,wsj,New Mexico is now the country’s second-largest...,https://www.wsj.com/economy/new-mexico-is-divi...
154,68,2026-07-29-00-36-00 +0000,wsj,"With the Iran war continuing, Israeli Prime Mi...",https://www.wsj.com/world/middle-east/netanyah...
214,53,2026-07-28-21-41-00 +0000,wsj,The Trump administration plans to halt a Medic...,https://www.wsj.com/politics/policy/medicare-d...
343,52,2026-07-28-16-29-15 +0000,nypost,Gavin Newsom’s ex-mistress lashes out at gover...,https://nypost.com/2026/07/28/us-news/ruby-rip...
59,51,2026-07-29-08-50-39 +0000,cbc,Japan's PM says rescuers in 'race against time...,https://www.cbc.ca/news/world/japan-earthquake...
261,45,2026-07-28-20-07-09 +0000,cbc,15-year-old arrested in Seattle festival shoot...,https://www.cbc.ca/news/world/seattle-shooting...
348,41,2026-07-28-16-14-02 +0000,chitri,FIFA plan for Kushner-backed $20 billion opera...,https://www.chicagotribune.com/2026/07/28/fifa...
158,41,2026-07-29-00-24-16 +0000,nypost,California Dems target AI campaign ads after S...,https://nypost.com/2026/07/28/us-news/californ...
72,40,2026-07-29-08-13-59 +0000,wsj,Stock Market Today: Oil Rises on Mideast Flare...,https://www.wsj.com/livecoverage/fed-meeting-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)