## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-20-39-29 +0000,nyt,Vance Lashes Out at Israeli Critics of U.S.-Ir...,https://www.nytimes.com/2026/06/18/world/middl...
1,2026-06-18-20-38-42 +0000,nypost,Scandalous past of California comedian Carlos ...,https://nypost.com/2026/06/18/us-news/scandalo...
2,2026-06-18-20-32-33 +0000,bbc,'City united after so long': New Yorkers rejoi...,https://www.bbc.com/news/articles/cx24j89rgnxo...
3,2026-06-18-20-30-00 +0000,wsj,Trump Announces Intel-Apple Partnership,https://www.wsj.com/finance/trump-announces-in...
4,2026-06-18-20-28-40 +0000,nypost,Obama and Michelle take digs at Trump in 3-hou...,https://nypost.com/2026/06/18/us-news/obama-an...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2660/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5     iran     54
70    deal     40
29   trump     36
23     new     19
72  prices     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
355,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,207
208,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...,181
7,2026-06-18-20-22-51 +0000,nyt,Iran War Live Updates: Vance Issues Blunt Warn...,https://www.nytimes.com/live/2026/06/18/world/...,181
51,2026-06-18-19-05-00 +0000,wsj,Trump’s Deal Sidesteps Key Reasons He Went to ...,https://www.wsj.com/world/middle-east/trumps-d...,163
72,2026-06-18-18-25-12 +0000,nypost,Senate Armed Services chairman Roger Wicker ca...,https://nypost.com/2026/06/18/us-news/senate-a...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
355,207,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
195,75,2026-06-18-12-53-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
17,64,2026-06-18-20-03-35 +0000,nypost,Man sentenced to three years in prison after h...,https://nypost.com/2026/06/18/us-news/man-sent...
88,60,2026-06-18-17-37-44 +0000,cbc,Ivory Coast says striker Elye Wahi will be all...,https://www.cbc.ca/sports/soccer/worldcup/ivor...
334,57,2026-06-17-22-01-16 +0000,nyt,Fed Meeting Live Updates: Kevin Warsh to Addre...,https://www.nytimes.com/2026/06/17/business/fe...
18,49,2026-06-18-20-02-25 +0000,nypost,Lindsay Clancy makes grim-faced appearance in ...,https://nypost.com/2026/06/18/us-news/lindsay-...
11,48,2026-06-18-20-12-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
251,46,2026-06-18-08-51-35 +0000,nypost,"Ukraine hits Moscow oil refinery, disrupting c...",https://nypost.com/2026/06/18/world-news/ukrai...
0,40,2026-06-18-20-39-29 +0000,nyt,Vance Lashes Out at Israeli Critics of U.S.-Ir...,https://www.nytimes.com/2026/06/18/world/middl...
6,39,2026-06-18-20-23-54 +0000,nypost,Knicks heralded as kings of NYC in estimated l...,https://nypost.com/2026/06/18/us-news/knicks-h...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)