## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-14-01-10-31 +0000,nyt,Iran War Live Updates: Iran Proposes Suspendin...,https://www.nytimes.com/live/2026/04/13/world/...
1,2026-04-14-01-10-04 +0000,startribune,Trump says US military has blockaded Iranian p...,https://www.startribune.com/us-military-says-i...
2,2026-04-14-01-09-17 +0000,nyt,Michigan Man Is Released in Wife’s Disappearan...,https://www.nytimes.com/2026/04/13/us/brian-ho...
3,2026-04-14-01-08-55 +0000,nyt,Vance Says Pope Leo Should Stay Out of U.S. Af...,https://www.nytimes.com/2026/04/13/us/politics...
4,2026-04-14-01-06-38 +0000,nypost,Tulsi Gabbard exposes the flimsy ‘false narrat...,https://nypost.com/2026/04/13/us-news/tulsi-ga...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2499/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9      trump     55
0       iran     38
71  blockade     30
1        war     24
70    hormuz     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
187,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...,193
345,2026-04-13-01-36-13 +0000,nypost,"Trump blasts Pope Leo as ‘weak on crime,’ says...",https://nypost.com/2026/04/12/us-news/trump-bl...,182
319,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,181
272,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,180
51,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,179

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
187,193,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...
52,113,2026-04-13-22-55-00 +0000,wsj,Two members of Congress—Democratic Rep. Eric S...,https://www.wsj.com/politics/house-removal-vot...
193,108,2026-04-13-17-05-41 +0000,nypost,Here’s how the US blockade of Strait of Hormuz...,https://nypost.com/2026/04/13/world-news/how-w...
88,58,2026-04-13-21-28-14 +0000,bbc,Hungary's next PM would pick up if Putin calls...,https://www.bbc.com/news/articles/cd6lzezp4zvo...
132,56,2026-04-13-19-56-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
160,44,2026-04-13-18-55-29 +0000,cbc,Judge throws out Trump's $10B US lawsuit again...,https://www.cbc.ca/news/world/trump-lawsuit-di...
244,40,2026-04-13-14-26-35 +0000,nypost,Trump says gas prices may remain high through ...,https://nypost.com/2026/04/13/business/trump-s...
320,37,2026-04-13-06-54-56 +0000,wsj,"Stock Market Today: Nasdaq, S&P 500 and Dow Pu...",https://www.wsj.com/livecoverage/stock-market-...
349,35,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
277,34,2026-04-13-11-03-00 +0000,wsj,Two of the most recognizable people on the pla...,https://www.wsj.com/politics/the-showdown-betw...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)