## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-06-12-00-00 +0000,wsj,Pesticide Giant Syngenta Readies New Weapon Ag...,https://www.wsj.com/business/pesticide-giant-s...
1,2026-04-06-11-56-53 +0000,nypost,Knife-wielding lunatic shot by NYPD cop after ...,https://nypost.com/2026/04/06/us-news/knife-wi...
2,2026-04-06-11-56-16 +0000,nyt,Iran War Live Updates: As Trump’s New Ultimatu...,https://www.nytimes.com/live/2026/04/06/world/...
3,2026-04-06-11-55-14 +0000,bbc,Somalia set for 'historic' first offshore oil ...,https://www.bbc.com/news/articles/czrepkppnl1o...
4,2026-04-06-11-55-02 +0000,startribune,Israel hits Iran's South Pars petrochemical pl...,https://www.startribune.com/airstrikes-on-iran...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
17     iran     41
21    trump     33
18      war     17
406  easter     13
110  strait     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
15,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...,145
137,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...,144
2,2026-04-06-11-56-16 +0000,nyt,Iran War Live Updates: As Trump’s New Ultimatu...,https://www.nytimes.com/live/2026/04/06/world/...,123
166,2026-04-05-18-12-38 +0000,nypost,Trump gives Iran Tuesday evening deadline to o...,https://nypost.com/2026/04/05/us-news/trump-gi...,122
172,2026-04-05-17-19-53 +0000,nypost,Defiant Iran vows to escalate war after Trump’...,https://nypost.com/2026/04/05/world-news/defia...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
15,145,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...
36,66,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-warns-...
200,43,2026-04-05-14-31-37 +0000,nypost,Trump heralds ‘Easter Miracle’ after daring re...,https://nypost.com/2026/04/05/us-news/trump-he...
95,35,2026-04-06-01-49-31 +0000,nypost,California’s fuel crisis hits terrifying new h...,https://nypost.com/2026/04/05/us-news/sky-high...
119,31,2026-04-05-22-34-00 +0000,wsj,"For nearly two days, injured and alone, a U.S....",https://www.wsj.com/politics/national-security...
172,30,2026-04-05-17-19-53 +0000,nypost,Defiant Iran vows to escalate war after Trump’...,https://nypost.com/2026/04/05/world-news/defia...
14,27,2026-04-06-11-06-37 +0000,nypost,Trump endorses former British government aide ...,https://nypost.com/2026/04/06/us-news/trump-en...
118,26,2026-04-05-22-35-54 +0000,nyt,U.S. Rescues Missing Air Force Officer Whose F...,https://www.nytimes.com/2026/04/04/us/politics...
206,24,2026-04-05-12-35-36 +0000,bbc,Pope Leo calls for global leaders to choose pe...,https://www.bbc.com/news/articles/crk1zgjj7y1o...
38,23,2026-04-06-10-00-00 +0000,nypost,Mamdani signs ‘emergency’ order to block conce...,https://nypost.com/2026/04/06/us-news/mamdani-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)