## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-14-59-39 +0000,nypost,Gunman blasts California newsroom with barrage...,https://nypost.com/2026/10/13/us-news/gunman-o...
1,2026-10-13-14-57-47 +0000,nyt,Six Flags Closes Multiple Rides After Death on...,https://www.nytimes.com/2026/10/12/us/roller-c...
2,2026-10-13-14-57-21 +0000,bbc,Dating app Bumble bought for $1.3bn,https://www.bbc.co.uk/news/articles/cm9qzwjgnj...
3,2026-10-13-14-55-05 +0000,startribune,Trump asks Greece Ambassador Guilfoyle to resi...,https://www.startribune.com/trump-ambassador-t...
4,2026-10-13-14-55-00 +0000,wsj,"For Stocks, the Future Ain’t What It Used to Be",https://www.wsj.com/finance/investing/for-stoc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
23    trump     45
94       he     16
149  russia     16
33    house     12
312     new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
15,2026-10-13-14-42-00 +0000,wsj,The White House has asked Kimberly Guilfoyle t...,https://www.wsj.com/politics/policy/kimberly-g...,132
236,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,130
35,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly asks Kimberly Guilfoyle to...,https://nypost.com/2026/10/13/us-news/trump-as...,113
3,2026-10-13-14-55-05 +0000,startribune,Trump asks Greece Ambassador Guilfoyle to resi...,https://www.startribune.com/trump-ambassador-t...,108
283,2026-10-12-21-20-51 +0000,bbc,Six Ukrainian energy sites hit by Russia since...,https://www.bbc.co.uk/news/articles/cvlyd4pdlw...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
15,132,2026-10-13-14-42-00 +0000,wsj,The White House has asked Kimberly Guilfoyle t...,https://www.wsj.com/politics/policy/kimberly-g...
77,62,2026-10-13-12-18-00 +0000,nyt,He Would Be Florida’s First Black Governor. Ca...,https://www.nytimes.com/2026/10/13/us/byron-do...
69,61,2026-10-13-12-52-12 +0000,bbc,"MI5 chief warns of threats to UK from Russia, ...",https://www.bbc.co.uk/news/articles/c60rl5vwpk...
231,58,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
93,53,2026-10-13-11-48-06 +0000,nypost,Ukraine got no warning about latest Russian st...,https://nypost.com/2026/10/13/world-news/ukrai...
89,53,2026-10-13-11-58-12 +0000,nypost,Georgia Six Flags closes 9 rides after guest f...,https://nypost.com/2026/10/13/us-news/georgia-...
284,49,2026-10-12-21-19-00 +0000,wsj,Energy Stocks Rise as Global Conflicts Push Up...,https://www.wsj.com/finance/stocks/energy-stoc...
48,45,2026-10-13-13-26-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
240,45,2026-10-12-23-44-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
116,42,2026-10-13-10-41-00 +0000,wsj,Medicare for All has become a defining policy ...,https://www.wsj.com/politics/policy/medicare-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)