## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-01-22-06-23 +0000,cbc,Bombing near upscale Moscow restaurant kills 3...,https://www.cbc.ca/news/world/moscow-restauran...
1,2026-08-01-21-59-17 +0000,nypost,Minnesota assisted living facility gave mental...,https://nypost.com/2026/08/01/us-news/minnesot...
2,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...
3,2026-08-01-21-23-45 +0000,nyt,Improvised Bomb Kills 3 at an Upscale Moscow R...,https://www.nytimes.com/2026/08/01/world/europ...
4,2026-08-01-21-23-42 +0000,nyt,Spain Installs Floating Barrier in Ceuta After...,https://www.nytimes.com/2026/08/01/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
22        trump     20
40     migrants     11
55          new     11
341        will     10
66   california     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
209,2026-07-31-22-58-15 +0000,chitri,Justice Department drops criminal case against...,https://www.chicagotribune.com/2026/07/31/crim...,55
2,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...,52
205,2026-07-31-23-02-17 +0000,cbc,U.S. Justice Department dismisses case against...,https://www.cbc.ca/news/world/us-doj-drops-ref...,51
52,2026-08-01-17-16-51 +0000,bbc,Trump administration drops Reflecting Pool van...,https://www.bbc.co.uk/news/articles/cz05yx5dd7...,50
51,2026-08-01-17-22-00 +0000,wsj,"U.S. Drops Vandalism Case Against Olympian, Sa...",https://www.wsj.com/us-news/law/prosecutors-dr...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
209,55,2026-07-31-22-58-15 +0000,chitri,Justice Department drops criminal case against...,https://www.chicagotribune.com/2026/07/31/crim...
38,47,2026-08-01-19-30-50 +0000,nyt,Trump’s Polling Numbers Hit a New Low. Don’t E...,https://www.nytimes.com/2026/08/01/us/politics...
71,45,2026-08-01-16-08-45 +0000,cbc,Hunger and hostility cited by migrants as reas...,https://www.cbc.ca/news/world/ceuta-morocco-mi...
187,42,2026-08-01-00-44-41 +0000,chitri,Gianni Infantino abandons plans to sell FIFA W...,https://www.chicagotribune.com/2026/07/31/fifa...
61,40,2026-08-01-16-50-51 +0000,cbc,"Nirmal Purja, 'inspirational' Nepali climber, ...",https://www.cbc.ca/news/world/nepal-climber-ni...
10,33,2026-08-01-21-10-49 +0000,nypost,Teen lifeguard reveals near-death battle to sa...,https://nypost.com/2026/08/01/us-news/rookie-l...
15,31,2026-08-01-20-51-42 +0000,nypost,Millions of Ukrainian books incinerated in Ru...,https://nypost.com/2026/08/01/world-news/milli...
155,29,2026-08-01-05-53-27 +0000,nypost,Oprah Winfrey says she will close her school f...,https://nypost.com/2026/08/01/world-news/oprah...
39,27,2026-08-01-19-23-28 +0000,nypost,Iran executes 20-year-old protestor arrested d...,https://nypost.com/2026/08/01/us-news/iran-exe...
30,26,2026-08-01-20-07-26 +0000,nypost,Man finds Jersey Shore message tucked inside b...,https://nypost.com/2026/08/01/us-news/nj-man-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)