## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-04-08-39 +0000,nyt,What to Know About the Hantavirus Outbreak on ...,https://www.nytimes.com/article/hantavirus-cru...
1,2026-05-07-04-08-15 +0000,nypost,Popular Italian food brand accused of ‘tomato ...,https://nypost.com/2026/05/07/business/popular...
2,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...
3,2026-05-07-04-01-10 +0000,nyt,Starmer Braces for Local Election Losses Amid ...,https://www.nytimes.com/2026/05/07/world/europ...
4,2026-05-07-04-01-06 +0000,nyt,Starmer Faces a Major Test in a Set of UK Elec...,https://www.nytimes.com/2026/05/07/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2678/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14         iran     31
17        trump     25
12          new     23
18          war     21
135  california     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
51,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,127
246,2026-05-06-16-11-44 +0000,bbc,Oil prices drop and stock markets rise after r...,https://www.bbc.com/news/articles/c4g8zejyyr3o...,105
2,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...,95
189,2026-05-06-19-14-00 +0000,wsj,Oil Retreats As Market Weighs New Push for U.S...,https://www.wsj.com/finance/commodities-future...,94
298,2026-05-06-12-14-10 +0000,nypost,Trump tells Post ‘too soon’ to prep for Iran p...,https://nypost.com/2026/05/06/us-news/trump-te...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
51,127,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
280,85,2026-05-06-14-16-51 +0000,wapo,Hantavirus-hit cruise ship to head to Canary I...,https://www.washingtonpost.com/health/2026/05/...
369,67,2026-05-06-06-46-38 +0000,latimes,"Top takeaways from fiery, at times ugly, Calif...",https://www.latimes.com/california/story/2026-...
252,63,2026-05-06-15-28-00 +0000,wsj,The job market is starting to show glimmers of...,https://www.wsj.com/economy/jobs/jobs-payroll-...
220,53,2026-05-06-17-38-42 +0000,nypost,Ex-JPMorgan banker Chirayu Rana was referred f...,https://nypost.com/2026/05/06/business/ex-jpmo...
10,48,2026-05-07-03-38-32 +0000,nypost,Texas shopping mall shooter allegedly killed 2...,https://nypost.com/2026/05/06/us-news/texas-sh...
60,47,2026-05-07-00-45-00 +0000,wsj,Commerce Secretary Howard Lutnick told a congr...,https://www.wsj.com/politics/policy/lutnick-sa...
227,46,2026-05-06-17-21-15 +0000,nypost,"Trump, Ric Flair, Atlanta Braves, media perso...",https://nypost.com/2026/05/06/media/trump-ric-...
186,44,2026-05-06-19-28-42 +0000,startribune,Former Metro Transit police chief surrenders p...,https://www.startribune.com/former-metro-trans...
54,42,2026-05-07-00-59-32 +0000,nypost,"Spencer Pratt slugs it out over homelessness, ...",https://nypost.com/2026/05/06/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)