## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-25-01-15-15 +0000,nyt,"After Standing Up to Trump Over Greenland, Den...",https://www.nytimes.com/2026/03/24/world/europ...
1,2026-03-25-01-14-05 +0000,nyt,"Iran War Live Updates: Pentagon Orders 2,000 A...",https://www.nytimes.com/live/2026/03/24/world/...
2,2026-03-25-01-12-53 +0000,nyt,Pakistan Offers to Host Talks Between Iran and...,https://www.nytimes.com/2026/03/24/world/middl...
3,2026-03-25-01-12-37 +0000,nypost,‘It’s sick’ — terrifying footage shows masked ...,https://nypost.com/2026/03/24/us-news/its-sick...
4,2026-03-25-01-10-06 +0000,nyt,Democrat Emily Gregory Wins Florida Special El...,https://www.nytimes.com/2026/03/24/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
9      iran     49
2     trump     35
10      war     27
16   middle     18
368     new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
149,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,141
125,2026-03-24-21-11-12 +0000,wapo,Trump declares Iran war ‘won’ as Tehran denies...,https://www.washingtonpost.com/national-securi...,141
79,2026-03-24-22-35-03 +0000,nypost,US sends 15-point plan to end war with Iran as...,https://nypost.com/2026/03/24/world-news/us-se...,137
130,2026-03-24-21-07-31 +0000,nyt,United States Said to Have Sent Iran a Plan to...,https://www.nytimes.com/2026/03/24/world/middl...,131
115,2026-03-24-21-26-30 +0000,nyt,Trump’s Threat to ‘Obliterate’ Iran’s Power St...,https://www.nytimes.com/2026/03/24/us/politics...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
149,141,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...
273,79,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
371,57,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
130,55,2026-03-24-21-07-31 +0000,nyt,United States Said to Have Sent Iran a Plan to...,https://www.nytimes.com/2026/03/24/world/middl...
28,52,2026-03-25-00-19-13 +0000,nyt,T.S.A. Tipped Off ICE Agents Before Arrests at...,https://www.nytimes.com/2026/03/24/us/tsa-data...
48,50,2026-03-24-23-33-08 +0000,nypost,Toronto cafe owner recalls trying to text Air ...,https://nypost.com/2026/03/24/us-news/toronto-...
188,46,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
271,37,2026-03-24-14-44-28 +0000,nypost,UK will lead ‘Hormuz Coalition’ to reopen stra...,https://nypost.com/2026/03/24/world-news/iran-...
163,35,2026-03-24-20-06-31 +0000,startribune,Twin Cities TSA agents talk about working with...,https://www.startribune.com/why-no-long-lines-...
68,33,2026-03-24-23-05-34 +0000,nypost,Hawaii doctor who bashed wife’s head with rock...,https://nypost.com/2026/03/24/us-news/hawaii-d...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)