## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-03-01-13-03 +0000,nyt,Iran War Live Updates: Strikes Hit Infrastruct...,https://www.nytimes.com/live/2026/04/02/world/...
1,2026-04-03-01-09-00 +0000,wsj,The Toilet’s Working Again: Artemis Astronauts...,https://www.wsj.com/science/space-astronomy/th...
2,2026-04-03-01-02-09 +0000,latimes,L.A. Metro confirms it was hacked. Weeks later...,https://www.latimes.com/california/story/2026-...
3,2026-04-03-01-00-00 +0000,wsj,Attorney General Pam Bondi was always on the r...,https://www.wsj.com/politics/policy/i-think-it...
4,2026-04-03-01-00-00 +0000,wsj,Control Over Strait of Hormuz Will Determine W...,https://www.wsj.com/world/middle-east/control-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2603/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
8      trump     80
0       iran     54
1        war     42
183      new     16
27   general     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-03-01-13-03 +0000,nyt,Iran War Live Updates: Strikes Hit Infrastruct...,https://www.nytimes.com/live/2026/04/02/world/...,251
355,2026-04-02-02-48-00 +0000,wsj,President Trump sought to reassure skeptical A...,https://www.wsj.com/politics/national-security...,216
215,2026-04-02-16-18-14 +0000,latimes,"Trump speech on Iran war, recent remarks on oi...",https://www.latimes.com/politics/story/2026-04...,213
135,2026-04-02-20-20-20 +0000,nyt,Trump Says He’ll End the Iran War in Weeks. Wh...,https://www.nytimes.com/2026/04/02/us/politics...,207
78,2026-04-02-22-11-12 +0000,wapo,"As Trump doubles down on Iran war, markets shu...",https://www.washingtonpost.com/world/2026/04/0...,206

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,251,2026-04-03-01-13-03 +0000,nyt,Iran War Live Updates: Strikes Hit Infrastruct...,https://www.nytimes.com/live/2026/04/02/world/...
61,93,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...
3,65,2026-04-03-01-00-00 +0000,wsj,Attorney General Pam Bondi was always on the r...,https://www.wsj.com/politics/policy/i-think-it...
297,63,2026-04-02-10-00-00 +0000,latimes,This California 8-year-old designed a 'zero gr...,https://www.latimes.com/california/story/2026-...
331,53,2026-04-02-07-47-34 +0000,wsj,Stock Market Today: U.S. Oil Prices Post Large...,https://www.wsj.com/livecoverage/stock-market-...
121,49,2026-04-02-20-55-15 +0000,nypost,Tanker ships must pay Iran’s Revolutionary Gua...,https://nypost.com/2026/04/02/world-news/tanke...
93,46,2026-04-02-21-34-00 +0000,wsj,The U.S. will impose tariffs of up to 100% on ...,https://www.wsj.com/politics/policy/trump-phar...
23,43,2026-04-03-00-05-36 +0000,nypost,Road trip favorite In-N-Out to open new locati...,https://nypost.com/2026/04/02/business/in-n-ou...
201,41,2026-04-02-17-11-00 +0000,wsj,President Trump said he would sign an executiv...,https://www.wsj.com/politics/policy/trump-exec...
226,36,2026-04-02-15-49-43 +0000,nypost,Global airlines could go bankrupt as jet fuel ...,https://nypost.com/2026/04/02/business/global-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)