## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-26-22-45-26 +0000,nyt,"After Wasp Attack, a Canadian Rock Climber Is ...",https://www.nytimes.com/2026/08/26/world/canad...
1,2026-08-26-22-39-26 +0000,nypost,LAPD reveals plan to protect Olympic athletes ...,https://nypost.com/2026/08/26/us-news/lapd-fac...
2,2026-08-26-22-38-22 +0000,nypost,Crazed NYC son who allegedly killed mom charge...,https://nypost.com/2026/08/26/us-news/crazed-n...
3,2026-08-26-22-37-00 +0000,wsj,Here Are the Business Executives Who Have Mamd...,https://www.wsj.com/business/here-are-the-busi...
4,2026-08-26-22-35-49 +0000,nyt,A Deadly Flood Tears Through Nepal and Tibet,https://www.nytimes.com/2026/08/26/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2701/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
76        trump     40
300      parton     20
299       dolly     20
77        trade     19
164  california     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,134
354,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...,128
358,2026-08-26-03-02-19 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,125
368,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...,125
121,2026-08-26-19-08-11 +0000,cbc,Trump's trade war: Fact-checking Canada's natu...,https://www.cbc.ca/news/world/trade-war-natura...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,134,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
354,88,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...
12,88,2026-08-26-22-29-07 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
362,70,2026-08-26-02-09-21 +0000,nyt,Dolly Parton’s Death Hits Home for Tennesseans...,https://www.nytimes.com/2026/08/25/us/nashvill...
148,63,2026-08-26-17-45-44 +0000,latimes,Southern California's scorching heat wave peak...,https://www.latimes.com/california/story/2026-...
88,54,2026-08-26-20-22-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
256,52,2026-08-26-12-37-13 +0000,nypost,47 Americans among hundreds missing after dead...,https://nypost.com/2026/08/26/world-news/flood...
316,51,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...
5,49,2026-08-26-22-35-03 +0000,nypost,"9/11 mastermind KSM will finally stand trial, ...",https://nypost.com/2026/08/26/us-news/9-11-mas...
250,48,2026-08-26-12-50-33 +0000,chitri,Iran warns of military ship ban in Hormuz unde...,https://www.chicagotribune.com/2026/08/26/iran...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)