## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-17-05-43-00 +0000,wsj,U.S. Treasury Yields Decline,https://www.wsj.com/finance/investing/jgbs-mix...
1,2026-07-17-05-41-01 +0000,nypost,NFL employee injured in Park Avenue mass shoot...,https://nypost.com/2026/07/17/us-news/nfl-empl...
2,2026-07-17-05-41-00 +0000,wsj,Dollar-Yen Tipped to Move Gradually Toward 165...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-07-17-05-36-22 +0000,bbc,School bus crash kills at least 20 pupils in U...,https://www.bbc.co.uk/news/articles/c151gegwqv...
4,2026-07-17-05-35-00 +0000,bbc,China hits out at British Steel nationalisation,https://www.bbc.co.uk/news/articles/cjd4kvxpd3...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2482/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
93   trump     45
134   iran     25
173    war     20
132    new     19
103   will     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
32,2026-07-17-03-04-00 +0000,wsj,President Trump delivered an extraordinary pri...,https://www.wsj.com/politics/elections/trump-a...,130
322,2026-07-16-13-20-24 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...,117
182,2026-07-16-20-24-00 +0000,wsj,Ahead of President Trump’s scheduled prime-tim...,https://www.wsj.com/politics/elections/what-to...,115
372,2026-07-16-10-00-00 +0000,latimes,Trump seeks prime-time spotlight for election ...,https://www.latimes.com/politics/story/2026-07...,109
27,2026-07-17-03-34-00 +0000,wsj,President Trump addressed the nation from the ...,https://www.wsj.com/politics/policy/trump-spee...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
32,130,2026-07-17-03-04-00 +0000,wsj,President Trump delivered an extraordinary pri...,https://www.wsj.com/politics/elections/trump-a...
285,105,2026-07-16-15-52-31 +0000,nyt,Maker of Drone Boats Used in Iran War Will Ope...,https://www.nytimes.com/2026/07/16/business/ma...
103,90,2026-07-16-22-55-00 +0000,wsj,The Treasury’s top tax policy official was for...,https://www.wsj.com/politics/policy/top-treasu...
395,47,2026-07-16-08-34-51 +0000,wsj,"Stock Market News, July 16, 2026: Nasdaq Slips...",https://www.wsj.com/livecoverage/stock-market-...
114,45,2026-07-16-22-37-38 +0000,nypost,Zelensky fires defense minister credited with ...,https://nypost.com/2026/07/16/world-news/zelen...
296,43,2026-07-16-15-02-00 +0000,wsj,The Trump administration will limit how long a...,https://www.wsj.com/politics/policy/trump-admi...
78,41,2026-07-17-00-30-00 +0000,wsj,Well-off boomers are increasingly upsizing the...,https://www.wsj.com/economy/housing/baby-boome...
253,37,2026-07-16-17-13-52 +0000,cbc,"Republicans blast Canada over wildfire smoke, ...",https://www.cbc.ca/news/politics/widlfires-smo...
74,36,2026-07-17-00-36-01 +0000,nypost,Body pulled from San Francisco Bay after deadl...,https://nypost.com/2026/07/16/us-news/body-pul...
115,34,2026-07-16-22-35-49 +0000,nypost,Trump’s media firm will potentially charge for...,https://nypost.com/2026/07/16/media/trumps-med...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)