## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-22-55-48 +0000,startribune,"Judge, U.S. Attorney spar at contempt hearing ...",https://www.startribune.com/judge-us-attorney-...
1,2026-03-03-22-53-59 +0000,nypost,Taxpayers will fork over more than $36K per ch...,https://nypost.com/2026/03/03/us-news/taxpayer...
2,2026-03-03-22-53-03 +0000,nyt,Iran Live Updates: Countries Try to Help Natio...,https://www.nytimes.com/live/2026/03/03/world/...
3,2026-03-03-22-53-00 +0000,wsj,Opinion | The Bibi-Made-Trump-Do-It Canard,https://www.wsj.com/opinion/iran-israel-benjam...
4,2026-03-03-22-52-23 +0000,nypost,OpenAI’s Sam Altman fends off ‘painful’ backla...,https://nypost.com/2026/03/03/business/openais...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18      iran     85
30     trump     62
56       war     35
210  strikes     17
53      east     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
90,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,206
373,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...,200
358,2026-03-03-02-36-25 +0000,nyt,Melania Trump Promotes ‘Peace Through Educatio...,https://www.nytimes.com/2026/03/02/us/politics...,194
186,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...,193
315,2026-03-03-09-57-15 +0000,bbc,Trump voters back him on Iran - but that could...,https://www.bbc.com/news/articles/cvg35401nrqo...,192

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
90,206,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...
267,84,2026-03-03-12-32-12 +0000,bbc,Heating oil prices rise by more than £100 amid...,https://www.bbc.com/news/articles/cq57ylzz4dlo...
8,79,2026-03-03-22-48-00 +0000,wsj,Goldman Sachs’s departing general counsel Kath...,https://www.wsj.com/politics/policy/house-comm...
309,77,2026-03-03-10-30-00 +0000,wsj,"A tight, three-way race for a Texas Senate sea...",https://www.wsj.com/politics/elections/what-to...
389,55,2026-03-03-00-33-09 +0000,latimes,Supreme Court: California parents may be told ...,https://www.latimes.com/politics/story/2026-03...
69,49,2026-03-03-21-42-00 +0000,wsj,Minneapolis Fed President Neel Kashkari said t...,https://www.wsj.com/economy/central-banking/ka...
186,46,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...
194,43,2026-03-03-17-28-00 +0000,wsj,U.S. Troops Killed in Kuwait Had No Warning of...,https://www.wsj.com/world/middle-east/u-s-troo...
192,40,2026-03-03-17-29-23 +0000,nypost,Trump administration’s bids to end New York’s ...,https://nypost.com/2026/03/03/us-news/trump-ad...
243,40,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)