## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-10-07-59-30 +0000,nypost,Ex-youth pastor David Vander Meer who allegedl...,https://nypost.com/2026/07/10/us-news/pastor-d...
1,2026-07-10-07-50-50 +0000,nypost,Trump says Democrats replacing Graham Platner ...,https://nypost.com/2026/07/10/us-news/trump-sa...
2,2026-07-10-07-47-29 +0000,bbc,Would you swap homes with a stranger to get a ...,https://www.bbc.co.uk/news/articles/ce8kkerxz7...
3,2026-07-10-07-42-08 +0000,nypost,North Carolina father arrested several times f...,https://nypost.com/2026/07/10/us-news/north-ca...
4,2026-07-10-07-40-41 +0000,bbc,Police investigating Reform donations - reports,https://www.bbc.co.uk/news/articles/c3eyq2np7q...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2328/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
21     trump     33
75      iran     25
358      new     15
25   platner     15
411      war     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
109,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...,107
138,2026-07-09-20-56-28 +0000,nypost,Trump resolved to carry out Iran ‘bitch slap’ ...,https://nypost.com/2026/07/09/us-news/trump-re...,99
107,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...,95
110,2026-07-09-21-56-00 +0000,wsj,"Iran Planned New Trump Assassination Attempt, ...",https://www.wsj.com/politics/iran-planned-new-...,94
217,2026-07-09-16-51-45 +0000,nypost,Israel ready for more war on Iran should Trump...,https://nypost.com/2026/07/09/world-news/israe...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
109,107,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...
107,80,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...
75,65,2026-07-10-00-07-58 +0000,bbc,Charlie Kirk murder suspect told roommate 'he ...,https://www.bbc.co.uk/news/articles/c621v466y9...
0,56,2026-07-10-07-59-30 +0000,nypost,Ex-youth pastor David Vander Meer who allegedl...,https://nypost.com/2026/07/10/us-news/pastor-d...
268,46,2026-07-09-14-11-32 +0000,nypost,New footage reveals destruction of Ayatollah K...,https://nypost.com/2026/07/09/world-news/ayato...
178,41,2026-07-09-18-44-34 +0000,cbc,Canada takes issue with IOC loosening restrict...,https://www.cbc.ca/sports/olympics/canada-obje...
98,40,2026-07-09-22-33-54 +0000,latimes,California will see its first monsoon storms o...,https://www.latimes.com/california/story/2026-...
251,36,2026-07-09-14-58-23 +0000,nypost,"Dozens of Santas, Mrs. Clauses from around the...",https://nypost.com/2026/07/09/world-news/dozen...
187,36,2026-07-09-18-18-07 +0000,nypost,Air Force One swap was ‘distraction and misdir...,https://nypost.com/2026/07/09/us-news/trump-ai...
218,34,2026-07-09-16-50-00 +0000,wsj,U.S. Stocks Rise as Investors Pick AI Trade Ba...,https://www.wsj.com/finance/stocks/oil-steadie...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)