## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-30-19-14-39 +0000,nypost,Small border town goes to war with California ...,https://nypost.com/2026/04/30/us-news/el-cajon...
1,2026-04-30-19-14-39 +0000,nyt,Hegseth Says Iran Cease-Fire Stops Clock for C...,https://www.nytimes.com/2026/04/30/us/politics...
2,2026-04-30-19-13-57 +0000,bbc,"'Globalise the intifada' chant is racist, says...",https://www.bbc.com/news/articles/c78k1r7rd7ko...
3,2026-04-30-19-12-03 +0000,bbc,US House votes to end government shutdown over...,https://www.bbc.com/news/articles/ce3pw5x3z54o...
4,2026-04-30-19-10-00 +0000,wsj,Oil Futures Pull Back Amid U.S.-Iran Standstill,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2479/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
58   trump     41
13    iran     32
101    new     29
25   house     25
4      war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-04-30-10-43-45 +0000,nypost,Oil prices briefly hit wartime high as Trump w...,https://nypost.com/2026/04/30/us-news/oil-pric...,154
302,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...,144
347,2026-04-29-22-40-00 +0000,wsj,In his first public testimony since the war in...,https://www.wsj.com/politics/national-security...,143
46,2026-04-30-18-05-26 +0000,bbc,Oil price hits highest since 2022 after report...,https://www.bbc.com/news/articles/cx21m88rd14o...,140
10,2026-04-30-19-05-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,154,2026-04-30-10-43-45 +0000,nypost,Oil prices briefly hit wartime high as Trump w...,https://nypost.com/2026/04/30/us-news/oil-pric...
10,129,2026-04-30-19-05-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...
377,98,2026-04-29-21-26-00 +0000,wsj,"Powell said he’ll stay on the Fed board, the S...",https://www.wsj.com/politics/policy/powelland-...
347,79,2026-04-29-22-40-00 +0000,wsj,In his first public testimony since the war in...,https://www.wsj.com/politics/national-security...
116,69,2026-04-30-16-22-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
302,62,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...
125,53,2026-04-30-16-00-00 +0000,wsj,The Justice Department is launching a West Coa...,https://www.wsj.com/politics/policy/doj-launch...
353,52,2026-04-29-22-23-00 +0000,wsj,The Fed held rates steady; but in a contentiou...,https://www.wsj.com/economy/central-banking/fe...
240,44,2026-04-30-09-30-00 +0000,wsj,"If these were normal times, Jerome Powell woul...",https://www.wsj.com/economy/central-banking/wh...
96,43,2026-04-30-16-39-29 +0000,nyt,How the Voting Rights Decision May Block the R...,https://www.nytimes.com/2026/04/30/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)