## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-22-54-42 +0000,nyt,Pentagon Fires Editor and Publisher of Indepen...,https://www.nytimes.com/2026/08/21/us/politics...
1,2026-08-21-22-48-19 +0000,nyt,Defense Rests Case in Lindsay Clancy Murder Trial,https://www.nytimes.com/2026/08/21/us/lindsay-...
2,2026-08-21-22-47-24 +0000,nypost,Accused casino slasher flashes evil glare wear...,https://nypost.com/2026/08/21/us-news/alleged-...
3,2026-08-21-22-45-01 +0000,bbc,Two injured in stabbing attack at Canada Sikh ...,https://www.bbc.co.uk/news/articles/ce8l7w0n0j...
4,2026-08-21-22-36-12 +0000,bbc,TikTok to pay $400m to US in one of largest ch...,https://www.bbc.co.uk/news/articles/cwyr0l45xj...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
40        trump     42
24        court     13
192        iran     12
174         new     11
436  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
34,2026-08-21-21-34-00 +0000,wsj,A dismissal of several high-ranking officials ...,https://www.wsj.com/politics/policy/upheaval-a...,105
66,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,105
122,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,100
26,2026-08-21-21-44-10 +0000,latimes,Trump cites national security as Supreme Court...,https://www.latimes.com/politics/story/2026-08...,93
203,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
34,105,2026-08-21-21-34-00 +0000,wsj,A dismissal of several high-ranking officials ...,https://www.wsj.com/politics/policy/upheaval-a...
203,48,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...
242,46,2026-08-21-10-04-49 +0000,wapo,Five reasons no one saw Prince Harry’s return ...,https://www.washingtonpost.com/world/2026/08/2...
55,42,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
111,42,2026-08-21-19-06-41 +0000,nypost,New footage shows accused California casino at...,https://nypost.com/2026/08/21/us-news/footage-...
14,41,2026-08-21-22-08-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
184,40,2026-08-21-14-42-00 +0000,wsj,"Greg Mankiw, Thomas Sargent and William White ...",https://www.wsj.com/economy/central-banking/th...
305,38,2026-08-21-05-29-38 +0000,latimes,Former acting U.S. attorney found dead inside ...,https://www.latimes.com/california/story/2026-...
303,35,2026-08-21-05-47-32 +0000,bbc,Hong Kong's Tiananmen activists guilty in nati...,https://www.bbc.co.uk/news/articles/c1l10mdrld...
289,35,2026-08-21-08-00-00 +0000,cbc,Canadian bans on U.S. alcohol take centre stag...,https://www.cbc.ca/news/world/canada-us-alcoho...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)