## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-14-04-06-53 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...
1,2026-06-14-04-02-55 +0000,nypost,Crazed Knicks fans smash cop car as NBA Finals...,https://nypost.com/2026/06/14/us-news/crazed-k...
2,2026-06-14-04-01-20 +0000,nyt,Japan Is Running Out of Royals. Are More Men t...,https://www.nytimes.com/2026/06/14/world/asia/...
3,2026-06-14-04-01-15 +0000,nyt,"Germany and Japan Are Rearming Again, 80 Years...",https://www.nytimes.com/2026/06/14/world/europ...
4,2026-06-14-04-01-10 +0000,nyt,"In Venezuela, a 91-Year-Old Weaver Sticks to T...",https://www.nytimes.com/2026/06/14/arts/design...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     26
32   world     17
184    cup     14
0     iran     13
6     deal      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-06-14-04-06-53 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...,87
123,2026-06-13-12-54-19 +0000,cbc,Trump says peace deal with Iran will be signed...,https://www.cbc.ca/news/world/pakistan-us-iran...,78
88,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...,78
46,2026-06-13-22-07-05 +0000,nypost,Israel strikes dozens of Hezbollah targets in ...,https://nypost.com/2026/06/13/us-news/israel-s...,70
78,2026-06-13-18-39-26 +0000,bbc,Trump says US-Iran deal to be signed on Sunday...,https://www.bbc.com/news/articles/cvglmn49xz0o...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,87,2026-06-14-04-06-53 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...
77,50,2026-06-13-18-50-01 +0000,nypost,Restaurant owners in World Cup cities take mat...,https://nypost.com/2026/06/13/business/restaur...
101,33,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...
5,30,2026-06-14-03-32-59 +0000,nypost,Knicks fans go insane after first NBA Finals w...,https://nypost.com/2026/06/13/us-news/knicks-f...
76,28,2026-06-13-18-52-12 +0000,nypost,So long Khamenei! Funeral for slain Iranian su...,https://nypost.com/2026/06/13/world-news/funer...
81,26,2026-06-13-18-17-28 +0000,nypost,Shocking three-word tweet aimed at Elon Musk u...,https://nypost.com/2026/06/13/tech/california-...
63,24,2026-06-13-20-39-10 +0000,nypost,NYC Councilwoman failed to disclose free rent ...,https://nypost.com/2026/06/13/us-news/nyc-coun...
47,23,2026-06-13-22-05-24 +0000,bbc,Vincent's parents 'never say he's good enough'...,https://www.bbc.com/news/articles/cpq3dnr5vlzo...
95,22,2026-06-13-16-28-38 +0000,bbc,Anthropic suspends new AI tools over US govern...,https://www.bbc.com/news/articles/c932g3v3e13o...
97,22,2026-06-13-16-00-00 +0000,wsj,Trump turns the White House lawn into a UFC ar...,https://www.wsj.com/politics/trump-ufc-politic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)