## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-30-11-56-15 +0000,nyt,Live Updates: Flight to Israel Is Diverted Aft...,https://www.nytimes.com/live/2026/09/30/world/...
1,2026-09-30-11-49-26 +0000,nyt,FlyDubai operates up to 10 daily flights from ...,https://www.nytimes.com/live/2026/09/30/world/...
2,2026-09-30-11-47-27 +0000,bbc,Russia launches largest attack on Ukraine ener...,https://www.bbc.co.uk/news/articles/ckjw5jx2l3...
3,2026-09-30-11-47-22 +0000,bbc,Greggs to shut four factories and cut 740 jobs,https://www.bbc.co.uk/news/articles/cm7802ylq9...
4,2026-09-30-11-46-48 +0000,nypost,Ken Paxton admitted ‘everybody’s numbers dropp...,https://nypost.com/2026/09/30/us-news/ken-paxt...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2334/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
81     trump     52
85        ai     25
590      new     21
71   burnham     14
629     will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
242,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...,200
382,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...,137
356,2026-09-29-17-27-33 +0000,chitri,President Trump says top tech firms have signe...,https://www.chicagotribune.com/2026/09/29/dona...,119
237,2026-09-29-21-55-00 +0000,cbc,Trump says top tech firms have signed accord t...,https://www.cbc.ca/news/world/ai-trump-agreeme...,113
330,2026-09-29-18-51-31 +0000,nypost,Trump calls for ‘tremendous self-regulation’ a...,https://nypost.com/2026/09/29/us-news/trump-ca...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
242,200,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...
358,77,2026-09-29-17-22-18 +0000,nyt,Prime Minister Andy Burnham Lays Out Plan to C...,https://www.nytimes.com/2026/09/29/world/europ...
220,70,2026-09-29-23-00-00 +0000,wsj,Americans in both parties back government-impo...,https://www.wsj.com/politics/policy/americans-...
68,68,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...
294,49,2026-09-29-20-20-00 +0000,wsj,Long-Term Treasury Yields Push Higher Despite ...,https://www.wsj.com/finance/investing/long-ter...
164,48,2026-09-30-03-45-06 +0000,nypost,Cops descend on home of wife of slaughtered NY...,https://nypost.com/2026/09/29/us-news/police-r...
322,46,2026-09-29-19-10-00 +0000,wsj,New York Fed President John Williams said that...,https://www.wsj.com/economy/central-banking/ne...
340,44,2026-09-29-18-14-48 +0000,chitri,Pete Hegseth says national security and milita...,https://www.chicagotribune.com/2026/09/29/pete...
383,41,2026-09-29-16-26-52 +0000,latimes,Woman arrested after 4-month-old baby found de...,https://www.latimes.com/california/story/2026-...
61,40,2026-09-30-10-00-12 +0000,chitri,Chicago Media Report: Jarrett Payton’s 1st mon...,https://www.chicagotribune.com/2026/09/30/chic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)