## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-16-12-26-00 +0000,wsj,Yum Brands to Sell Pizza Hut for $2.7 Billion,https://www.wsj.com/business/deals/yum-brands-...
1,2026-06-16-12-25-59 +0000,bbc,Thames Water moves step closer to nationalisat...,https://www.bbc.com/news/articles/cly089d0wl7o...
2,2026-06-16-12-25-03 +0000,startribune,Multiple arrests as FBI disrupts 'planned atta...,https://www.startribune.com/multiple-arrests-a...
3,2026-06-16-12-19-21 +0000,bbc,UK will play full part in reopening Strait of ...,https://www.bbc.com/news/articles/cvgj1g6e5d3o...
4,2026-06-16-12-19-00 +0000,wsj,Sterling Looks Underpriced For U.K. Political ...,https://www.wsj.com/finance/currencies/yen-may...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
62    iran     56
52   trump     56
15    deal     46
195  world     19
156    war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
353,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...,243
154,2026-06-16-01-00-00 +0000,wsj,"In one weekend, President Trump veered from th...",https://www.wsj.com/world/middle-east/trump-ir...,226
297,2026-06-15-17-34-00 +0000,wsj,Trump Says Strait of Hormuz Will Be Fully Open...,https://www.wsj.com/world/middle-east/question...,223
287,2026-06-15-18-27-23 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,220
357,2026-06-15-13-37-14 +0000,nypost,Trump and Vance sign secret Iran deal — keep w...,https://nypost.com/2026/06/15/us-news/us-iran-...,191

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
353,243,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...
113,79,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
159,79,2026-06-16-00-57-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
291,56,2026-06-15-18-08-57 +0000,cbc,World Cup contender Spain and Cape Verde play ...,https://www.cbc.ca/sports/soccer/worldcup/cabo...
95,49,2026-06-16-09-00-00 +0000,wsj,The Liberty Justice Center won its biggest-eve...,https://www.wsj.com/politics/policy/how-a-cons...
11,48,2026-06-16-11-59-00 +0000,wsj,Equinor Doubles Share Buyback to $3 Billion Un...,https://www.wsj.com/business/energy-oil/equino...
132,47,2026-06-16-04-02-00 +0000,wsj,Health Secretary Robert F. Kennedy Jr. ordered...,https://www.wsj.com/politics/policy/rfk-jr-ord...
307,43,2026-06-15-17-14-33 +0000,nypost,Top Anthropic staffers rush to DC in bid to re...,https://nypost.com/2026/06/15/business/top-ant...
147,40,2026-06-16-01-53-00 +0000,wsj,Eight Crew Members Believed Dead in B-52 Bombe...,https://www.wsj.com/us-news/b-52-bomber-crashe...
235,38,2026-06-15-20-42-05 +0000,nypost,SpaceX shares jump 20% in first full day of tr...,https://nypost.com/2026/06/15/business/spacex-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)