## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-04-31-46 +0000,nyt,"News Helicopter Crashes in Los Angeles County,...",https://www.nytimes.com/2026/09/15/us/los-ange...
1,2026-09-16-04-23-13 +0000,nypost,Wounded survivor dials for help with her nose ...,https://nypost.com/2026/09/16/us-news/wounded-...
2,2026-09-16-04-20-00 +0000,nyt,The A.I. Doomsday Skeptics,https://www.nytimes.com/2026/09/15/world/ai-do...
3,2026-09-16-04-02-38 +0000,nyt,Denmark Says Russian Warship Fired Flares at M...,https://www.nytimes.com/2026/09/15/world/europ...
4,2026-09-16-04-01-30 +0000,nyt,OpenAI Considers New Financing at a $1.5 Trill...,https://www.nytimes.com/2026/09/16/business/de...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2507/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
109  trump     47
30     new     27
222     ai     25
112   iran     22
224  court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,210
322,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,141
321,2026-09-15-13-54-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,137
224,2026-09-15-18-34-00 +0000,wsj,"President Trump promised $5,000 to every Ameri...",https://www.wsj.com/politics/policy/republican...,130
127,2026-09-15-21-16-25 +0000,chitri,Illinois Democrats cheer Supreme Court mail-in...,https://www.chicagotribune.com/2026/09/15/supr...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,210,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
322,94,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
98,64,2026-09-15-22-40-00 +0000,nypost,Meet Anthropic CEO Dario Amodei’s handpicked s...,https://nypost.com/2026/09/15/business/anthrop...
195,63,2026-09-15-19-36-30 +0000,nypost,10-year Treasury yield hits highest level sinc...,https://nypost.com/2026/09/15/business/10-year...
224,58,2026-09-15-18-34-00 +0000,wsj,"President Trump promised $5,000 to every Ameri...",https://www.wsj.com/politics/policy/republican...
51,51,2026-09-16-00-34-32 +0000,nypost,Plot forms against California tech companies w...,https://nypost.com/2026/09/15/us-news/silicon-...
76,49,2026-09-15-23-30-00 +0000,wsj,American business owners are grappling with a ...,https://www.wsj.com/business/american-business...
280,47,2026-09-15-16-29-10 +0000,bbc,Nick Reiner will not face death penalty if con...,https://www.bbc.co.uk/news/articles/c6zxz18wlg...
86,47,2026-09-15-23-14-00 +0000,wsj,"In a setback for the crypto industry, a bill t...",https://www.wsj.com/politics/policy/landmark-c...
343,42,2026-09-15-12-49-55 +0000,cbc,Canada's 4 largest airports to be opened up to...,https://www.cbc.ca/news/politics/carney-airpor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)