## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-09-22-52-32 +0000,nypost,Houston Astros boss Jim Crane owns airline inv...,https://nypost.com/2026/09/09/us-news/houston-...
1,2026-09-09-22-50-36 +0000,nypost,Ailing NYC woman who stabbed health aide wants...,https://nypost.com/2026/09/09/us-news/ailing-n...
2,2026-09-09-22-48-20 +0000,wapo,Oil price spike from Iran attacks intrudes on ...,https://www.washingtonpost.com/politics/2026/0...
3,2026-09-09-22-46-11 +0000,nyt,Trump’s Census Overhaul Would Exclude Some Imm...,https://www.nytimes.com/2026/09/09/us/politics...
4,2026-09-09-22-45-34 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/09/09/us/rnc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2338/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
34        trump     64
239         new     31
32      midterm     21
33   convention     20
25          oil     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
95,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,146
334,2026-09-09-09-06-36 +0000,nyt,Will Trump’s Midterm Convention Help or Hurt R...,https://www.nytimes.com/2026/09/09/us/politics...,141
102,2026-09-09-20-20-01 +0000,nypost,"Trump claims oil, gas prices will fall ‘right ...",https://nypost.com/2026/09/09/business/trump-c...,140
401,2026-09-09-01-29-17 +0000,nypost,GOP to rail against ‘socialist’ Dems at Dallas...,https://nypost.com/2026/09/08/us-news/gop-to-r...,140
287,2026-09-09-11-28-05 +0000,chitri,Republicans gather in Dallas for two-day midte...,https://www.chicagotribune.com/2026/09/09/repu...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
95,146,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
298,103,2026-09-09-10-42-00 +0000,wsj,The two-day GOP midterm convention kicks off W...,https://www.wsj.com/politics/elections/everyth...
262,89,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
88,71,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
266,65,2026-09-09-12-20-40 +0000,bbc,Petrol prices rise by 5p over a week as Iran w...,https://www.bbc.co.uk/news/articles/cj4jwlx77l...
381,57,2026-09-09-02-51-42 +0000,nypost,Federal judge rules Missouri can use GOP-frien...,https://nypost.com/2026/09/08/us-news/federal-...
177,57,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
421,52,2026-09-08-23-52-28 +0000,bbc,Chris Mason: Burnham looks to show he will go ...,https://www.bbc.co.uk/news/articles/c3v439n5xl...
431,50,2026-09-08-23-26-00 +0000,wsj,The latest Canadian tariffs on $20 billion of ...,https://www.wsj.com/economy/trade/the-states-o...
232,46,2026-09-09-14-45-00 +0000,wsj,Facing a three-way arms race with Russia and C...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)