## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-06-15-46 +0000,nypost,NYPD searching for several hooligans who attac...,https://nypost.com/2026/06/10/us-news/nypd-sea...
1,2026-06-10-06-14-54 +0000,bbc,Twelve killed in mass shooting in Johannesburg...,https://www.bbc.com/news/articles/c79yzqw0z0wo...
2,2026-06-10-06-08-07 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes o...,https://www.nytimes.com/live/2026/06/09/world/...
3,2026-06-10-05-59-00 +0000,wsj,U.S. Treasury Yields Edge Up After Military Es...,https://www.wsj.com/finance/investing/jgbs-fal...
4,2026-06-10-05-52-25 +0000,nypost,"55 kids, teens charged in Hersheypark opening ...",https://nypost.com/2026/06/10/us-news/55-kids-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
217       trump     28
17         iran     23
69        maine     20
100  california     17
63        world     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
50,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,114
323,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,100
103,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,99
219,2026-06-09-17-01-09 +0000,nypost,Trump claims Iran shooting down US helicopter ...,https://nypost.com/2026/06/09/us-news/iran-sho...,84
33,2026-06-10-03-09-35 +0000,nyt,U.S. Strikes Iran After Trump Vowed to Retalia...,https://www.nytimes.com/2026/06/09/us/politics...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
50,114,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
323,100,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...
27,77,2026-06-10-03-36-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
34,74,2026-06-10-03-08-28 +0000,nypost,Sen. Susan Collins’ allies preview ‘the end fo...,https://nypost.com/2026/06/09/us-news/sen-susa...
103,71,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
8,50,2026-06-10-05-23-36 +0000,bbc,UK pint prices up 36% since last World Cup – h...,https://www.bbc.com/news/articles/c982107drq8o...
297,40,2026-06-09-10-10-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
207,37,2026-06-09-17-47-41 +0000,bbc,Israeli air strikes hit Lebanese city of Tyre ...,https://www.bbc.com/news/articles/c36y16nkr5no...
306,36,2026-06-09-10-00-00 +0000,latimes,This new law could create a million new apartm...,https://www.latimes.com/business/story/2026-06...
68,35,2026-06-10-00-51-07 +0000,nypost,Sobbing Karmelo Anthony learns his fate for mu...,https://nypost.com/2026/06/09/us-news/sobbing-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)