## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-27-23-06-59 +0000,nyt,Texas Has a New Way to Teach History: In Chron...,https://www.nytimes.com/2026/06/27/us/texas-te...
1,2026-06-27-23-06-55 +0000,nyt,Live Updates: Hostilities Flare Between U.S. a...,https://www.nytimes.com/live/2026/06/27/world/...
2,2026-06-27-23-02-27 +0000,nypost,LA’s iconic La Brea Tar Pits Museum to host di...,https://nypost.com/2026/06/27/us-news/las-la-b...
3,2026-06-27-23-00-00 +0000,wsj,One Man Tries to Make $2 Million Selling Coins...,https://www.wsj.com/business/retail/one-man-tr...
4,2026-06-27-22-53-01 +0000,nyt,"At Least 4 Dead in Kentucky Flooding, Governor...",https://www.nytimes.com/2026/06/27/us/kentucky...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
121    venezuela     23
11          iran     14
201        trump     13
250  earthquakes     11
1            new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
30,2026-06-27-21-24-08 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...,61
40,2026-06-27-21-01-57 +0000,nypost,"Venezuela earthquake death toll tops 1,400 — w...",https://nypost.com/2026/06/27/world-news/venez...,58
181,2026-06-27-00-52-00 +0000,wsj,Venezuela’s Earthquakes Test Trump’s Bet on De...,https://www.wsj.com/world/americas/venezuelas-...,57
87,2026-06-27-15-00-48 +0000,nypost,Miracle baby born on street beside earthquake ...,https://nypost.com/2026/06/27/world-news/mirac...,54
98,2026-06-27-13-53-33 +0000,nypost,Heartwarming video shows moment firefighters r...,https://nypost.com/2026/06/27/world-news/video...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
30,61,2026-06-27-21-24-08 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...
9,46,2026-06-27-22-37-00 +0000,wsj,U.S. Carries Out New Strikes on Iran as Tit-fo...,https://www.wsj.com/world/middle-east/mideast-...
26,45,2026-06-27-21-31-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...
179,35,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
27,34,2026-06-27-21-26-36 +0000,nypost,James Carville calls for formal Democratic par...,https://nypost.com/2026/06/27/media/james-carv...
160,29,2026-06-27-03-41-58 +0000,bbc,How Cape Verde stunned World Cup to set up Arg...,https://www.bbc.co.uk/sport/football/articles/...
21,28,2026-06-27-21-39-15 +0000,bbc,Burnham will need a Moscow test as well as Mak...,https://www.bbc.co.uk/news/articles/cdxdwr0xk5...
24,25,2026-06-27-21-35-19 +0000,nypost,Lefty California teacher declares she married ...,https://nypost.com/2026/06/27/us-news/far-left...
39,24,2026-06-27-21-02-00 +0000,missionlocal,🌈 San Francisco Pride live updates: The Dyke M...,https://missionlocal.org/2026/06/san-francisco...
157,23,2026-06-27-04-50-35 +0000,nypost,JD Vance tells Bill Maher how ‘America wins’ w...,https://nypost.com/2026/06/27/us-news/jd-vance...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)