## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-17-07-40 +0000,nypost,Delta airplane struck by firework mortar while...,https://nypost.com/2026/07/05/us-news/delta-ai...
1,2026-07-05-16-57-18 +0000,nypost,Egypt uncovers lost Byzantine-era city in late...,https://nypost.com/2026/07/05/world-news/egypt...
2,2026-07-05-16-56-00 +0000,wsj,The Democratic socialist and anti-Israel activ...,https://www.wsj.com/politics/elections/the-dem...
3,2026-07-05-16-45-30 +0000,nypost,"Mom investigated for cannibalism after son, 4,...",https://nypost.com/2026/07/05/world-news/austr...
4,2026-07-05-16-41-00 +0000,wsj,A Sudden Glut of Oil Threatens to Weaken Iran’...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2502/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
84     trump     26
134       th     19
8       july     16
107  funeral     13
40      iran     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
152,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,91
119,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...,83
118,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,79
60,2026-07-05-12-05-04 +0000,startribune,Trump mixes patriotism with partisanship as he...,https://www.startribune.com/fireworks-heat-and...,77
106,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
152,91,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
106,75,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...
66,65,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...
29,34,2026-07-05-15-10-52 +0000,nypost,California’s Fourth of July plunges into hell ...,https://nypost.com/2026/07/05/us-news/californ...
60,32,2026-07-05-12-05-04 +0000,startribune,Trump mixes patriotism with partisanship as he...,https://www.startribune.com/fireworks-heat-and...
34,28,2026-07-05-14-37-30 +0000,nypost,Pa. Gov. Josh Shapiro slams socialist NY Dem D...,https://nypost.com/2026/07/05/us-news/pa-gov-j...
38,26,2026-07-05-13-59-00 +0000,wsj,Germany before World War I provoked backlash b...,https://www.wsj.com/economy/trade/how-to-win-a...
119,25,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
13,24,2026-07-05-16-29-14 +0000,nypost,Trump admin will use same company to repair Re...,https://nypost.com/2026/07/05/us-news/trump-ad...
130,23,2026-07-05-02-55-07 +0000,latimes,Fans scram: Fireworks head into the stands at ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)