## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-06-22-59-21 +0000,nypost,NYC doesn’t have enough hotel rooms for FIFA W...,https://nypost.com/2026/03/06/business/nyc-doe...
1,2026-03-06-22-57-11 +0000,nyt,How Jeffrey Epstein Used Doctors to Control Women,https://www.nytimes.com/video/us/1000000107371...
2,2026-03-06-22-56-03 +0000,nyt,Here Is Mexico’s Plan to Keep the Country Safe...,https://www.nytimes.com/2026/03/06/world/ameri...
3,2026-03-06-22-56-00 +0000,wsj,Man Convicted of Assassination Plot With Trump...,https://www.wsj.com/us-news/man-convicted-of-a...
4,2026-03-06-22-49-43 +0000,nyt,"Talarico’s Social Media Paper Trail, the Jobs ...",https://www.nytimes.com/2026/03/06/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
47    iran     61
29   trump     61
390   dies     27
48     war     22
71     new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
355,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...,206
41,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,189
44,2026-03-06-22-01-03 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...,185
6,2026-03-06-22-44-51 +0000,nyt,Trump Demands Iran’s ‘Unconditional Surrender’...,https://www.nytimes.com/2026/03/06/world/middl...,169
235,2026-03-06-16-25-00 +0000,wsj,A promise to steady the economy helped Preside...,https://www.wsj.com/economy/consumers/how-war-...,167

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
355,206,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...
5,127,2026-03-06-22-47-57 +0000,nyt,Live Updates: Oil and Gas Prices Jump as Iran ...,https://www.nytimes.com/live/2026/03/06/world/...
83,85,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
356,66,2026-03-06-05-05-00 +0000,wsj,"Rep. Tony Gonzales (R., Texas) said he wouldn’...",https://www.wsj.com/politics/elections/texas-t...
44,63,2026-03-06-22-01-03 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...
41,62,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...
162,54,2026-03-06-17-39-35 +0000,nypost,Americans stuck in Middle East open up about s...,https://nypost.com/2026/03/06/world-news/ameri...
278,52,2026-03-06-13-49-00 +0000,wsj,The Justice Department said it released some E...,https://www.wsj.com/politics/policy/doj-says-e...
417,49,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...
187,44,2026-03-06-17-01-37 +0000,nyt,From 2000: Sirimavo Bandaranaike of Sri Lanka ...,https://www.nytimes.com/2026/03/06/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)