## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-08-49-52 +0000,nyt,Happy Birthday to Us,https://www.nytimes.com/2026/07/04/briefing/ha...
1,2026-07-05-08-43-29 +0000,nypost,New Jersey coastal city clashes over proposal ...,https://nypost.com/2026/07/05/us-news/new-jers...
2,2026-07-05-08-40-19 +0000,nyt,China Frees Pastor Detained in Crackdown on Re...,https://www.nytimes.com/2026/07/05/world/asia/...
3,2026-07-05-08-25-27 +0000,nypost,Pastor Ezra Jin Mingri freed from prison in Ch...,https://nypost.com/2026/07/05/us-news/china-fr...
4,2026-07-05-08-24-32 +0000,bbc,"US marks 250th birthday with fireworks, flyove...",https://www.bbc.co.uk/news/articles/cp9lppvkmz...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2358/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
81     july     26
19    trump     25
30       th     17
56  funeral     15
51     iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,105
28,2026-07-05-03-59-05 +0000,nypost,Trump recognizes Artemis II astronauts during ...,https://nypost.com/2026/07/04/us-news/trump-re...,88
65,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,87
17,2026-07-05-05-02-35 +0000,nyt,"In Fourth of July Speech, Trump Celebrates Ame...",https://www.nytimes.com/2026/07/05/us/politics...,86
18,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,105,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
65,87,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
146,46,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
70,33,2026-07-04-22-30-18 +0000,latimes,America at 250: A day to celebrate the country...,https://www.latimes.com/california/story/2026-...
105,31,2026-07-04-17-17-52 +0000,nypost,NYC Council to honor first-responder heroes ki...,https://nypost.com/2026/07/04/us-news/nyc-coun...
19,28,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
164,26,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...
134,23,2026-07-04-12-27-13 +0000,cbc,St. Petersburg oil terminal hit as Ukraine pre...,https://www.cbc.ca/news/world/st-petersburg-oi...
3,21,2026-07-05-08-25-27 +0000,nypost,Pastor Ezra Jin Mingri freed from prison in Ch...,https://nypost.com/2026/07/05/us-news/china-fr...
163,21,2026-07-04-09-45-55 +0000,bbc,Large crowds gather in Tehran on first day of ...,https://www.bbc.co.uk/news/articles/c0ky2zen1k...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)