## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-19-14-54-00 +0000,wsj,Reporters from CNN and MS NOW said their White...,https://www.wsj.com/politics/policy/ms-now-den...
1,2026-09-19-14-50-08 +0000,nyt,Trump Has Tried to Ban Reporters From Governme...,https://www.nytimes.com/2026/09/18/us/politics...
2,2026-09-19-14-49-30 +0000,nyt,CNN and MS NOW Reporters Barred From White Hou...,https://www.nytimes.com/live/2026/business/tru...
3,2026-09-19-14-42-49 +0000,nypost,Hasan Piker to speak at Cornell — as experts w...,https://nypost.com/2026/09/19/us-news/hasan-pi...
4,2026-09-19-14-41-49 +0000,nypost,Columbus Parade boss invites Italian-slighting...,https://nypost.com/2026/09/19/us-news/columbus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     64
5    house     23
231    new     19
111     ai     17
4    white     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
179,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...,181
169,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...,171
260,2026-09-18-18-56-47 +0000,nyt,Judge Who Struck Down Trump’s Compensation Fun...,https://www.nytimes.com/2026/09/18/us/politics...,162
213,2026-09-18-20-34-01 +0000,latimes,"Trump says he's banning CNN, MS NOW and Politi...",https://www.latimes.com/entertainment-arts/bus...,151
131,2026-09-19-01-07-46 +0000,wapo,"Trump says he’s banning CNN, MS NOW and Politi...",https://www.washingtonpost.com/business/2026/0...,151

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
179,181,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...
169,68,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...
44,58,2026-09-19-12-14-43 +0000,nypost,"GOP control of House, Senate odds fade as Trum...",https://nypost.com/2026/09/19/us-news/republic...
282,56,2026-09-18-17-51-00 +0000,wsj,A new Federal Reserve inquiry into the 2023 co...,https://www.wsj.com/economy/central-banking/ne...
178,46,2026-09-18-21-44-26 +0000,nypost,Trump announces Greenland deal with Denmark gi...,https://nypost.com/2026/09/18/us-news/trump-an...
197,38,2026-09-18-21-11-47 +0000,nypost,Trump claims Don Jr. paid back Russian oligarc...,https://nypost.com/2026/09/18/us-news/presiden...
138,37,2026-09-19-00-26-16 +0000,latimes,"Paramount, California settlement talks acceler...",https://www.latimes.com/entertainment-arts/bus...
201,35,2026-09-18-21-02-46 +0000,nyt,Belmont Park Got a $550 Million Makeover. Will...,https://www.nytimes.com/2026/09/18/business/be...
173,32,2026-09-18-22-05-21 +0000,chitri,Ban on selling handguns to young adults under ...,https://www.chicagotribune.com/2026/09/18/ban-...
20,30,2026-09-19-13-41-37 +0000,nypost,Going on a first date? Here are the best NYC o...,https://nypost.com/2026/09/19/us-news/west-vil...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)