## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-19-19-19-05 +0000,nypost,Measles case reported at LAX as global World C...,https://nypost.com/2026/06/19/us-news/measles-...
1,2026-06-19-19-17-53 +0000,nyt,Mideast Live Updates: Israel Commits to New Le...,https://www.nytimes.com/live/2026/06/19/world/...
2,2026-06-19-19-11-54 +0000,cbc,Ottawa adding $5.4B for child care to sustain ...,https://www.cbc.ca/news/politics/ottawa-adding...
3,2026-06-19-19-07-41 +0000,nyt,U.S. to End AIDS Funding for South Africa,https://www.nytimes.com/2026/06/19/world/afric...
4,2026-06-19-19-06-59 +0000,nypost,Aging Air Force One jet gets mothballed as Tru...,https://nypost.com/2026/06/19/us-news/aging-ai...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3131/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
57      iran     45
44     trump     32
58      deal     29
367  burnham     19
5      world     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
321,2026-06-18-21-14-00 +0000,wsj,Iran Deal Skirts Why Trump Went to War,https://www.wsj.com/business/iran-deal-skirts-...,127
213,2026-06-19-08-00-00 +0000,cbc,Trump routinely trashes the Obama-era Iran nuc...,https://www.cbc.ca/news/world/trump-iran-deal-...,126
244,2026-06-19-02-51-00 +0000,wsj,Vance Slams Israeli Critics of Trump’s Deal Wi...,https://www.wsj.com/world/middle-east/vance-to...,125
235,2026-06-19-04-12-07 +0000,bbc,"In Trump's shadow, Vance becomes face of Iran ...",https://www.bbc.com/news/articles/cx23jr133lwo...,123
349,2026-06-18-19-45-07 +0000,nyt,"Before Making a Deal, Trump Demanded Iran’s Su...",https://www.nytimes.com/2026/06/17/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
321,127,2026-06-18-21-14-00 +0000,wsj,Iran Deal Skirts Why Trump Went to War,https://www.wsj.com/business/iran-deal-skirts-...
184,78,2026-06-19-09-54-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...
55,71,2026-06-19-17-00-00 +0000,wsj,Warsh’s first test as Fed chairman will be rea...,https://www.wsj.com/economy/central-banking/fe...
87,67,2026-06-19-15-29-08 +0000,nypost,Chaos in LA streets — with one person shot — a...,https://nypost.com/2026/06/19/us-news/chaos-in...
256,61,2026-06-19-01-42-00 +0000,wsj,The architects of California’s proposed billio...,https://www.wsj.com/politics/policy/union-behi...
254,59,2026-06-19-01-50-00 +0000,wsj,What started as a series of promotional interv...,https://www.wsj.com/politics/policy/jd-vances-...
341,48,2026-06-18-20-12-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
41,47,2026-06-19-17-36-40 +0000,nypost,Russia mistakenly strikes own refinery in Mosc...,https://nypost.com/2026/06/19/world-news/russi...
18,41,2026-06-19-18-38-34 +0000,nypost,‘All My Children’ actor Paul Avery’s devastate...,https://nypost.com/2026/06/19/us-news/all-my-c...
81,39,2026-06-19-15-46-59 +0000,nypost,Houston TV meteorologist whines she never won ...,https://nypost.com/2026/06/19/media/houston-tv...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)