## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-05-05-21-43 +0000,nypost,Caribbean Airlines passenger gives birth aboar...,https://nypost.com/2026/04/05/us-news/caribbea...
1,2026-04-05-05-16-37 +0000,nyt,Iran War Live Updates: U.S. Rescues Downed Air...,https://www.nytimes.com/live/2026/04/04/world/...
2,2026-04-05-05-00-00 +0000,wsj,"Crashes, Ejections and a Frantic Search for a ...",https://www.wsj.com/world/middle-east/crashes-...
3,2026-04-05-04-58-21 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/04/world/...
4,2026-04-05-04-41-00 +0000,wsj,U.S. Forces Rescue Second American Aviator in ...,https://www.wsj.com/world/middle-east/u-s-forc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
14      iran     26
25     trump     22
15       war     12
304      new      9
58   iranian      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-05-05-16-37 +0000,nyt,Iran War Live Updates: U.S. Rescues Downed Air...,https://www.nytimes.com/live/2026/04/04/world/...,109
22,2026-04-05-01-00-00 +0000,wsj,President Trump’s repeated declarations that t...,https://www.wsj.com/politics/national-security...,70
113,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,70
94,2026-04-04-17-29-58 +0000,nyt,"Trump Pledged a Quick End to the Iran War, but...",https://www.nytimes.com/2026/04/04/us/politics...,69
149,2026-04-04-09-30-00 +0000,wsj,President Trump didn’t attack Iran to help the...,https://www.wsj.com/economy/the-iran-war-is-ma...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,109,2026-04-05-05-16-37 +0000,nyt,Iran War Live Updates: U.S. Rescues Downed Air...,https://www.nytimes.com/live/2026/04/04/world/...
14,46,2026-04-05-02-21-36 +0000,nypost,Niece of notorious Iranian Gen. Soleimani chee...,https://nypost.com/2026/04/04/us-news/niece-of...
31,36,2026-04-05-00-04-03 +0000,bbc,'Something we have never seen before': Artemis...,https://www.bbc.com/news/videos/ce3d5gkd2geo?a...
91,34,2026-04-04-17-42-39 +0000,nypost,Gavin Newsom to spend $19M in taxpayer funds o...,https://nypost.com/2026/04/04/us-news/gavin-ne...
7,25,2026-04-05-03-57-59 +0000,nypost,US Forces have rescued missing crew member of ...,https://nypost.com/2026/04/04/world-news/us-fo...
11,24,2026-04-05-02-59-01 +0000,nypost,"Leo XIV celebrates first Easter vigil as pope,...",https://nypost.com/2026/04/04/world-news/pope-...
25,23,2026-04-05-00-55-49 +0000,nypost,Bay Area police chief’s bizarre excuse for lea...,https://nypost.com/2026/04/04/us-news/bay-area...
167,23,2026-04-04-08-15-47 +0000,nypost,Three men charged over arson attack on Jewish ...,https://nypost.com/2026/04/04/world-news/uk-ch...
131,23,2026-04-04-11-01-00 +0000,startribune,Helicopter owner’s lawsuit fails against East ...,https://www.startribune.com/east-gull-lake-min...
113,22,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)