## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-10-06-08-36 +0000,bbc,Former Tory minister Ann Widdecombe dies at 78,https://www.bbc.co.uk/news/articles/ced47jqyg1...
1,2026-07-10-05-51-59 +0000,latimes,'Real Housewives of Orange County's' Jennifer ...,https://www.latimes.com/entertainment-arts/sto...
2,2026-07-10-05-49-00 +0000,wsj,"U.S. Treasury Yields Stable, Investors Take Mi...",https://www.wsj.com/finance/investing/jgbs-edg...
3,2026-07-10-05-38-35 +0000,nypost,NY mom Jamey Carney suffocated to death in Ire...,https://nypost.com/2026/07/10/world-news/ny-mo...
4,2026-07-10-05-24-47 +0000,nypost,"Black bear breaks into Alaskan mall, eats a pe...",https://nypost.com/2026/07/10/us-news/black-be...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2471/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
77     trump     33
132     iran     28
494  platner     16
226      new     15
267      war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...,115
126,2026-07-09-20-56-28 +0000,nypost,Trump resolved to carry out Iran ‘bitch slap’ ...,https://nypost.com/2026/07/09/us-news/trump-re...,102
96,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...,97
99,2026-07-09-21-56-00 +0000,wsj,"Iran Planned New Trump Assassination Attempt, ...",https://www.wsj.com/politics/iran-planned-new-...,96
204,2026-07-09-16-51-45 +0000,nypost,Israel ready for more war on Iran should Trump...,https://nypost.com/2026/07/09/world-news/israe...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,115,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...
96,82,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...
62,62,2026-07-10-00-07-58 +0000,bbc,Charlie Kirk murder suspect told roommate 'he ...,https://www.bbc.co.uk/news/articles/c621v466y9...
87,50,2026-07-09-22-33-54 +0000,latimes,California will see its first monsoon storms o...,https://www.latimes.com/california/story/2026-...
255,46,2026-07-09-14-11-32 +0000,nypost,New footage reveals destruction of Ayatollah K...,https://nypost.com/2026/07/09/world-news/ayato...
166,44,2026-07-09-18-44-34 +0000,cbc,Canada takes issue with IOC loosening restrict...,https://www.cbc.ca/sports/olympics/canada-obje...
113,42,2026-07-09-21-11-24 +0000,nypost,Trump ditches extravagant Qatar-gifted Air For...,https://nypost.com/2026/07/09/world-news/trump...
238,38,2026-07-09-14-58-23 +0000,nypost,"Dozens of Santas, Mrs. Clauses from around the...",https://nypost.com/2026/07/09/world-news/dozen...
205,35,2026-07-09-16-50-00 +0000,wsj,U.S. Stocks Rise as Investors Pick AI Trade Ba...,https://www.wsj.com/finance/stocks/oil-steadie...
3,34,2026-07-10-05-38-35 +0000,nypost,NY mom Jamey Carney suffocated to death in Ire...,https://nypost.com/2026/07/10/world-news/ny-mo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)