## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-02-19-09-10 +0000,nyt,How Trump Decided to Go to War With Iran,https://www.nytimes.com/2026/03/02/us/politics...
1,2026-03-02-19-09-05 +0000,nypost,Terrifying moment runaway boat careens across ...,https://nypost.com/2026/03/02/us-news/runaway-...
2,2026-03-02-19-06-20 +0000,nyt,Natural Gas Prices Surge After Attacks Hit Fac...,https://www.nytimes.com/2026/03/02/business/na...
3,2026-03-02-19-05-00 +0000,wsj,"Trump’s Mar-a-Lago Weekend: A Fundraiser, Vide...",https://www.wsj.com/politics/policy/trumps-wee...
4,2026-03-02-19-03-15 +0000,nyt,Texas Holds First Elections Since Starting the...,https://www.nytimes.com/2026/03/02/us/election...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2509/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
4        iran     95
0       trump     39
3         war     25
104   strikes     23
45   conflict     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
90,2026-03-02-17-23-04 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,273
277,2026-03-02-01-17-20 +0000,latimes,Thousands rally in Westwood as U.S.-Iran war e...,https://www.latimes.com/california/story/2026-...,226
155,2026-03-02-15-17-25 +0000,nypost,Trump won’t rule out sending US troops into Ir...,https://nypost.com/2026/03/02/us-news/trump-wo...,197
33,2026-03-02-18-32-05 +0000,startribune,War in the Mideast widens as Trump says strike...,https://www.startribune.com/war-widens-to-incl...,192
322,2026-03-01-20-43-28 +0000,nypost,Trump reveals how long he expects Iran campaig...,https://nypost.com/2026/03/01/world-news/trump...,183

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
90,273,2026-03-02-17-23-04 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
246,92,2026-03-02-07-45-00 +0000,wsj,Middle East Conflict Sparks Surge in Oil Prices,https://www.wsj.com/world/middle-east/middle-e...
111,74,2026-03-02-16-46-23 +0000,cbc,U.S. military leaders lay out timeline of atta...,https://www.cbc.ca/news/world/us-pentagon-iran...
296,66,2026-03-01-22-24-27 +0000,bbc,Nine dead in missile attack on Israel as Iran ...,https://www.bbc.com/news/articles/c363zkp1pgxo...
215,52,2026-03-02-10-30-00 +0000,wsj,Berkshire’s New CEO Lays Out How He Will Pick ...,https://www.wsj.com/finance/berkshires-new-ceo...
220,51,2026-03-02-10-30-00 +0000,wsj,The Texas Republican Senate primary is getting...,https://www.wsj.com/politics/elections/texas-p...
116,39,2026-03-02-16-34-18 +0000,wapo,Videos appear to show the moments U.S. fighter...,https://www.washingtonpost.com/investigations/...
218,37,2026-03-02-10-30-00 +0000,wsj,Think Tech Has Taken Over Your Portfolio? You ...,https://www.wsj.com/finance/investing/think-te...
191,36,2026-03-02-12-27-21 +0000,nypost,Huge fire as one of the world’s largest oil re...,https://nypost.com/2026/03/02/world-news/drone...
93,31,2026-03-02-17-19-09 +0000,nypost,Austin mass shooter Ndiaga Diagne once plowed ...,https://nypost.com/2026/03/02/us-news/austin-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)