## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-04-03-00 +0000,wsj,Japan Has Ample Yen Intervention Ammunition to...,https://www.wsj.com/finance/currencies/yen-int...
1,2026-06-30-04-01-06 +0000,nyt,Norway’s ‘Viking Row’ Is a Fan Phenomenon at t...,https://www.nytimes.com/2026/06/30/world/europ...
2,2026-06-30-03-53-37 +0000,nypost,CBS crew attacked by multiple men near Chicago...,https://nypost.com/2026/06/29/us-news/cbs-crew...
3,2026-06-30-03-42-14 +0000,bbc,India's biggest share sales tell the story of ...,https://www.bbc.co.uk/news/articles/cdej6ej7w4...
4,2026-06-30-03-35-32 +0000,nypost,Investigators scouring sewers below Philly hou...,https://nypost.com/2026/06/29/us-news/investig...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2355/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
279    court     41
150    trump     38
278  supreme     37
335      new     14
83      will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
207,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...,197
102,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...,184
250,2026-06-29-15-34-07 +0000,cbc,U.S. Supreme Court rules against Trump bid to ...,https://www.cbc.ca/news/world/us-scotus-ruling...,178
275,2026-06-29-14-19-39 +0000,nypost,Supreme Court blocks Trump bid to fire Fed gov...,https://nypost.com/2026/06/29/us-news/supreme-...,174
88,2026-06-29-22-18-20 +0000,nyt,Trump Renews Threat to Fire Fed Governor Lisa ...,https://www.nytimes.com/2026/06/29/us/politics...,171

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
207,197,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...
44,68,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
280,56,2026-06-29-14-09-52 +0000,nypost,Trump must pony up $5M to E. Jean Carroll afte...,https://nypost.com/2026/06/29/us-news/supreme-...
194,51,2026-06-29-18-16-57 +0000,bbc,New 'No 10 North' plan will rebalance power in...,https://www.bbc.co.uk/news/articles/cx2jw5q5pd...
102,46,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...
337,43,2026-06-29-10-00-00 +0000,startribune,Officials tried to protect a baby girl born at...,https://www.startribune.com/officials-tried-to...
160,42,2026-06-29-19-47-01 +0000,nypost,Woke Paris pol blames Americans and our air co...,https://nypost.com/2026/06/29/world-news/paris...
359,41,2026-06-29-07-51-05 +0000,bbc,Mum rescued from Venezuela rubble with newborn...,https://www.bbc.co.uk/news/articles/clyw3rkj2p...
281,38,2026-06-29-14-05-54 +0000,nypost,Supreme Court rules ballots arriving after Ele...,https://nypost.com/2026/06/29/us-news/supreme-...
292,37,2026-06-29-13-00-12 +0000,bbc,Inspired by Wimbledon and the World Cup? Here'...,https://www.bbc.co.uk/news/articles/crlw2xw1yy...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)