## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-07-16-08-53 +0000,bbc,US appeals court halts Trump ballroom project ...,https://www.bbc.co.uk/news/articles/cwyq80jqql...
1,2026-08-07-16-06-37 +0000,nyt,‘I Was So Wrong’: Iranians Say Trump’s Promise...,https://www.nytimes.com/2026/08/07/us/politics...
2,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...
3,2026-08-07-16-03-00 +0000,wsj,Puerto Rico Rations Water Amid Severe Drought,https://www.wsj.com/us-news/climate-environmen...
4,2026-08-07-16-02-09 +0000,missionlocal,Tenderloin apartment fires: how light wells ha...,https://missionlocal.org/2026/08/tenderloin-ap...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
3    trump     43
406    new     26
416     up     14
227   jobs     12
1    court     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
251,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...,118
309,2026-08-06-20-46-15 +0000,nypost,Trump signs new executive order to ban ‘birth ...,https://nypost.com/2026/08/06/us-news/trump-si...,115
2,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...,113
275,2026-08-06-22-10-35 +0000,wapo,Trump tries new tack against birthright citize...,https://www.washingtonpost.com/politics/2026/0...,110
212,2026-08-07-02-13-45 +0000,latimes,"After Supreme Court loss, Trump again targets ...",https://www.latimes.com/politics/story/2026-08...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
251,118,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...
291,80,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...
32,66,2026-08-07-15-33-00 +0000,wsj,"The U.S. labor market shed jobs in July, an un...",https://www.wsj.com/economy/jobs/july-jobs-rep...
321,57,2026-08-06-20-18-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
224,55,2026-08-07-01-03-00 +0000,wsj,Rep. Max Miller is lending his re-election cam...,https://www.wsj.com/politics/elections/max-mil...
290,52,2026-08-06-21-34-00 +0000,wsj,"Trump targets birthright citizenship (again), ...",https://www.wsj.com/politics/policy/trump-trie...
2,50,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...
0,44,2026-08-07-16-08-53 +0000,bbc,US appeals court halts Trump ballroom project ...,https://www.bbc.co.uk/news/articles/cwyq80jqql...
71,43,2026-08-07-13-56-45 +0000,nypost,"Turkey, Pakistan, Saudi Arabia sign mutual def...",https://nypost.com/2026/08/07/world-news/turke...
76,36,2026-08-07-13-46-41 +0000,nypost,Earth Wind & Fire band member in ‘critical con...,https://nypost.com/2026/08/07/us-news/earth-wi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)