## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-13-22-04-19 +0000,nyt,Homeland Security Paid $464 Million for Airpla...,https://www.nytimes.com/2026/08/13/us/politics...
1,2026-08-13-22-03-00 +0000,wsj,Opinion | UWM Is a Government Mortgage Canary,https://www.wsj.com/opinion/mat-ishbia-uwm-mor...
2,2026-08-13-22-03-00 +0000,wsj,Opinion | Russia Disqualifies an Antiwar Party,https://www.wsj.com/opinion/russia-disqualifie...
3,2026-08-13-22-02-54 +0000,bbc,Conditions on US aircraft carrier at sea for m...,https://www.bbc.co.uk/news/articles/cyvl2d5j52...
4,2026-08-13-22-01-00 +0000,wsj,"Opinion | Fauci, Covid Vaccines and Miscarriages",https://www.wsj.com/opinion/anthony-fauci-covi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2452/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
50        trump     31
30          new     19
266  california     15
43       market     10
106         out      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...,98
326,2026-08-13-02-25-00 +0000,wsj,Some U.S. officials thought the plan to evade ...,https://www.wsj.com/politics/national-security...,82
72,2026-08-13-20-15-57 +0000,cbc,Kennedy Center board votes to return Trump's n...,https://www.cbc.ca/news/world/kennedy-center-v...,75
13,2026-08-13-21-51-00 +0000,wsj,President Trump has directed the Navy to tear ...,https://www.wsj.com/us-news/trump-orders-navy-...,75
103,2026-08-13-19-04-56 +0000,latimes,Kennedy Center board votes to close venue for ...,https://www.latimes.com/entertainment-arts/sto...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,98,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...
96,56,2026-08-13-19-19-55 +0000,nypost,California city accuses Gavin Newsom of ‘overr...,https://nypost.com/2026/08/13/us-news/newsom-i...
56,50,2026-08-13-20-42-17 +0000,chitri,Investigators find bird remains inside Ryanair...,https://www.chicagotribune.com/2026/08/13/ntsb...
80,50,2026-08-13-20-05-52 +0000,latimes,"He was a star LAPD investigator, then he went ...",https://www.latimes.com/california/story/2026-...
300,50,2026-08-13-08-42-00 +0000,wsj,U.S. Army troops faced off against Ukrainian d...,https://www.wsj.com/politics/national-security...
253,45,2026-08-13-11-03-00 +0000,wsj,"During campaign season, it isn’t popular to ta...",https://www.wsj.com/politics/policy/no-one-wan...
89,43,2026-08-13-19-37-00 +0000,wsj,House Minority Leader Hakeem Jeffries on Thurs...,https://www.wsj.com/politics/policy/top-democr...
187,41,2026-08-13-15-15-31 +0000,nypost,Minnesota Dem Peggy Flanagan boasts she could ...,https://nypost.com/2026/08/13/us-news/minnesot...
83,38,2026-08-13-20-01-00 +0000,wsj,U.S. sending fresh aircraft carrier to Middle ...,https://www.wsj.com/politics/national-security...
337,35,2026-08-13-01-00-00 +0000,wsj,The ascendant far-left is hitting turbulence i...,https://www.wsj.com/politics/elections/midwest...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)