## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-20-17-15-24 +0000,nypost,California gender-secrecy law for students suf...,https://nypost.com/2026/06/20/us-news/court-bl...
1,2026-06-20-17-09-03 +0000,nypost,"World’s oldest living land animal, a 194-year-...",https://nypost.com/2026/06/20/world-news/world...
2,2026-06-20-17-06-21 +0000,nypost,Mamdani calls hater DSA House hopeful who bash...,https://nypost.com/2026/06/20/us-news/mamdani-...
3,2026-06-20-17-04-59 +0000,nyt,Mideast Live Updates: Strait of Hormuz Re-emer...,https://www.nytimes.com/live/2026/06/20/world/...
4,2026-06-20-17-00-00 +0000,wsj,Immigration Crackdown Lifts Private-Prison Stocks,https://www.wsj.com/business/immigration-crack...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2600/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
294  trump     18
39    iran     17
281    new      9
11   world      9
661   deal      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...,65
23,2026-06-20-16-07-44 +0000,bbc,Iran says Strait of Hormuz will be closed over...,https://www.bbc.com/news/articles/cwyekkwm1mmo...,54
59,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...,48
5,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...,46
89,2026-06-20-09-02-41 +0000,nyt,World Leaders Awaited Iran Deal for Months. He...,https://www.nytimes.com/2026/06/20/world/europ...,46

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,65,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...
23,54,2026-06-20-16-07-44 +0000,bbc,Iran says Strait of Hormuz will be closed over...,https://www.bbc.com/news/articles/cwyekkwm1mmo...
5,38,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...
198,36,2026-06-19-18-20-00 +0000,wsj,The Fed’s vice chair of supervision spoke at a...,https://www.wsj.com/economy/central-banking/to...
62,31,2026-06-20-12-47-10 +0000,nypost,Italian mom killed in Dominican Republic resor...,https://nypost.com/2026/06/20/world-news/itali...
82,31,2026-06-20-10-16-33 +0000,nypost,Canadian auto parts billionaire Frank Stronach...,https://nypost.com/2026/06/20/world-news/canad...
210,28,2026-06-19-17-36-40 +0000,nypost,Russia mistakenly strikes own refinery in Mosc...,https://nypost.com/2026/06/19/world-news/russi...
19,25,2026-06-20-16-23-03 +0000,nypost,At least 12 shot after SUV pulls up and opens ...,https://nypost.com/2026/06/20/us-news/at-least...
141,25,2026-06-19-23-40-59 +0000,bbc,Japanese pop group XG went from brutal five ye...,https://www.bbc.com/news/articles/cly8gj8pqz7o...
136,23,2026-06-20-00-00-00 +0000,wsj,California Gov. Gavin Newsom has turned a Just...,https://www.wsj.com/politics/policy/california...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)