## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-24-06-11-18 +0000,nyt,China Detained 2 Japanese on Suspicion of Smug...,https://www.nytimes.com/2026/06/24/world/asia/...
1,2026-06-24-05-57-55 +0000,nypost,"Boy, 12, killed after suspect opened fire duri...",https://nypost.com/2026/06/24/us-news/tennesse...
2,2026-06-24-05-41-00 +0000,wsj,U.S. Treasury Yields Edge Higher,https://www.wsj.com/finance/investing/jgb-futu...
3,2026-06-24-05-26-21 +0000,bbc,Burnham likely to replace Reeves if he becomes PM,https://www.bbc.co.uk/news/articles/cwyl91qlyr...
4,2026-06-24-05-24-27 +0000,nypost,NYC teen arsonist sentenced to 5 years in pris...,https://nypost.com/2026/06/24/us-news/nyc-teen...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
149  trump     37
80    iran     29
127    war     21
52     new     19
651     ai     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-06-24-03-57-59 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...,135
83,2026-06-23-23-58-19 +0000,nyt,"Senate Votes to Direct End to Iran War, Rebuki...",https://www.nytimes.com/2026/06/23/us/politics...,127
122,2026-06-23-22-01-03 +0000,nypost,Israel furious with Trump for being left out o...,https://nypost.com/2026/06/23/world-news/israe...,115
71,2026-06-24-00-38-49 +0000,nyt,Trump Is Making Big Claims About the Iran Talk...,https://www.nytimes.com/2026/06/23/us/politics...,115
26,2026-06-24-03-22-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/national-security...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,135,2026-06-24-03-57-59 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...
20,88,2026-06-24-03-48-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/policy/key-takeaw...
367,65,2026-06-23-09-00-00 +0000,wsj,A generational battle is playing out in the De...,https://www.wsj.com/politics/elections/the-gen...
372,63,2026-06-23-08-11-00 +0000,wsj,"Stock Market News, June 23, 2026: Tech Slide D...",https://www.wsj.com/livecoverage/stock-market-...
162,50,2026-06-23-20-49-00 +0000,wsj,President Trump’s push for stricter voter elig...,https://www.wsj.com/politics/policy/trump-on-c...
142,48,2026-06-23-21-25-48 +0000,nypost,Sable Offshore lashes out after ruling — threa...,https://nypost.com/2026/06/23/us-news/gas-and-...
89,43,2026-06-23-23-29-25 +0000,latimes,Family says police fatally shot teen during me...,https://www.latimes.com/california/story/2026-...
127,42,2026-06-23-21-53-00 +0000,wsj,Opinion | Will the World Cup Make America Love...,https://www.wsj.com/opinion/will-the-world-cup...
338,41,2026-06-23-10-23-22 +0000,cbc,France sees its hottest day on record amid ear...,https://www.cbc.ca/news/world/britain-western-...
51,37,2026-06-24-01-49-00 +0000,wsj,Congress passed its most-ambitious housing leg...,https://www.wsj.com/economy/housing/a-landmark...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)