## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-28-16-54-00 +0000,wsj,U.K. Releases Suspects in Terror Plot at Base ...,https://www.wsj.com/world/u-k-probes-possible-...
1,2026-09-28-16-54-00 +0000,wsj,A Federal Reserve employee transferred potenti...,https://www.wsj.com/economy/central-banking/fe...
2,2026-09-28-16-47-53 +0000,bbc,UK needs plan in case of 'unprecedented' AI jo...,https://www.bbc.co.uk/news/articles/cvj64jg5pr...
3,2026-09-28-16-46-59 +0000,nyt,Two of China’s EV Makers Announce a Deal as Au...,https://www.nytimes.com/2026/09/28/business/ch...
4,2026-09-28-16-46-57 +0000,nyt,German Town Votes to Stop Adding Memorials Out...,https://www.nytimes.com/2026/09/28/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
206  trump     38
27      uk     12
224   iran     11
37   china     10
165    new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
108,2026-09-28-12-51-00 +0000,wsj,President Trump will announce a Minnesota comp...,https://www.wsj.com/politics/trump-to-unveil-p...,85
59,2026-09-28-14-42-43 +0000,nypost,White House reporters predict which Republican...,https://nypost.com/2026/09/28/media/white-hous...,80
246,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...,73
222,2026-09-28-01-00-00 +0000,wsj,Trump came into office promising to fix the ec...,https://www.wsj.com/economy/trump-economy-infl...,72
92,2026-09-28-13-10-00 +0000,wsj,"In a letter to a defense-industry group, Democ...",https://www.wsj.com/politics/policy/possible-n...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
108,85,2026-09-28-12-51-00 +0000,wsj,President Trump will announce a Minnesota comp...,https://www.wsj.com/politics/trump-to-unveil-p...
83,57,2026-09-28-13-54-08 +0000,nypost,Farmer who foiled suspected Iran terror plot o...,https://nypost.com/2026/09/28/world-news/farme...
135,47,2026-09-28-11-01-00 +0000,wsj,We’ll explore what could happen if the Republi...,https://www.wsj.com/politics/heres-what-could-...
33,46,2026-09-28-16-00-27 +0000,nypost,New York Times tech exec is shot dead by his e...,https://nypost.com/2026/09/28/us-news/nyt-tech...
38,43,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
70,40,2026-09-28-14-22-00 +0000,wsj,Inflation in the eurozone is expected to rise ...,https://www.wsj.com/economy/central-banking/eu...
27,36,2026-09-28-16-18-57 +0000,cbc,SpaceX sends giant Starship into orbit for the...,https://www.cbc.ca/news/science/starship-fligh...
246,35,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...
96,33,2026-09-28-13-07-00 +0000,wsj,Ahead of the release of his book “This Cursed ...,https://www.wsj.com/world/how-evan-gershkovich...
222,32,2026-09-28-01-00-00 +0000,wsj,Trump came into office promising to fix the ec...,https://www.wsj.com/economy/trump-economy-infl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)