## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-30-19-53-43 +0000,nypost,The Gulf South emerges as the ‘new Silicon Val...,https://nypost.com/2026/08/30/business/the-gul...
1,2026-08-30-19-50-00 +0000,wsj,Opinion | Seattle Teachers Threaten an Illegal...,https://www.wsj.com/opinion/seattle-teachers-t...
2,2026-08-30-19-46-48 +0000,nyt,"Nepal Turns to Mass Burials, as Thousands Rema...",https://www.nytimes.com/2026/08/30/world/asia/...
3,2026-08-30-19-46-10 +0000,nyt,Ferry Carrying Hundreds Capsizes Off the Coast...,https://www.nytimes.com/2026/08/30/world/europ...
4,2026-08-30-19-45-05 +0000,nypost,Hunting addict ordered to shoot TikTok apology...,https://nypost.com/2026/08/30/us-news/hunting-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
43        trump     18
3           new     12
17        nepal     10
362         oil     10
118  california     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
198,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...,58
54,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,54
66,2026-08-30-16-13-37 +0000,nypost,Google swaps Lake Ontario maps to ‘Lake Americ...,https://nypost.com/2026/08/30/us-news/google-m...,52
164,2026-08-30-04-01-02 +0000,bbc,Trump hails 'historic' deal to control 65 bill...,https://www.bbc.co.uk/news/articles/cx2zlwe7qj...,51
77,2026-08-30-15-08-52 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
198,58,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...
208,37,2026-08-29-20-07-51 +0000,nyt,Nepal Rescuers Bore Through Tunnels to Try to ...,https://www.nytimes.com/2026/08/29/world/asia/...
0,36,2026-08-30-19-53-43 +0000,nypost,The Gulf South emerges as the ‘new Silicon Val...,https://nypost.com/2026/08/30/business/the-gul...
54,36,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...
47,36,2026-08-30-17-11-07 +0000,nypost,El-Sayed finally apologizes for lamenting deat...,https://nypost.com/2026/08/30/us-news/el-sayed...
160,36,2026-08-30-06-03-30 +0000,nypost,Switzerland rave shooting leaves 22-year-old w...,https://nypost.com/2026/08/30/world-news/switz...
65,31,2026-08-30-16-14-00 +0000,wsj,"James Talarico, the Democratic candidate for S...",https://www.wsj.com/politics/policy/talarico-i...
148,30,2026-08-30-09-00-00 +0000,wsj,Social Security’s looming insolvency is the co...,https://www.wsj.com/politics/policy/social-sec...
102,29,2026-08-30-12-41-05 +0000,nypost,Clinton foundation seeks intern with ‘high lev...,https://nypost.com/2026/08/30/us-news/bill-and...
188,29,2026-08-29-22-27-58 +0000,nypost,Muslim holy days of Eid al-Fitr and Eid al-Adh...,https://nypost.com/2026/08/29/us-news/eid-al-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)