## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-17-59-00 +0000,wsj,"Flying-Taxi Maker Archer Sues Joby, Accusing R...",https://www.wsj.com/business/flying-taxi-maker...
1,2026-03-09-17-58-51 +0000,nyt,Live Updates: Oil Price Surge Rattles Markets;...,https://www.nytimes.com/live/2026/03/09/world/...
2,2026-03-09-17-58-50 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/09/world/...
3,2026-03-09-17-57-53 +0000,nyt,"A $1,000 Dog Grooming Session? The Wellness In...",https://www.nytimes.com/2026/03/09/business/do...
4,2026-03-09-17-57-31 +0000,nyt,"As Oil Prices Rise, Trump’s War With Iran Beco...",https://www.nytimes.com/2026/03/09/business/ec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
18   iran     59
13    oil     31
34    war     30
39    new     28
33  trump     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
109,2026-03-09-14-48-23 +0000,wapo,Iran rallies around new leader after 10 days o...,https://www.washingtonpost.com/world/2026/03/0...,189
84,2026-03-09-15-50-17 +0000,nypost,Trump tells The Post there’s no reason to pani...,https://nypost.com/2026/03/09/us-news/trump-te...,175
259,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...,168
4,2026-03-09-17-57-31 +0000,nyt,"As Oil Prices Rise, Trump’s War With Iran Beco...",https://www.nytimes.com/2026/03/09/business/ec...,166
102,2026-03-09-14-54-27 +0000,nypost,Trump tells Post he’s ‘nowhere near’ ordering ...,https://nypost.com/2026/03/09/us-news/trump-te...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
109,189,2026-03-09-14-48-23 +0000,wapo,Iran rallies around new leader after 10 days o...,https://www.washingtonpost.com/world/2026/03/0...
155,90,2026-03-09-12-21-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...
270,68,2026-03-08-21-37-50 +0000,nypost,Ayatollah Ali Khamenei’s son Mojtaba Khamenei ...,https://nypost.com/2026/03/08/world-news/mojta...
194,50,2026-03-09-09-30-00 +0000,wsj,The surge in oil and gasoline prices last week...,https://www.wsj.com/economy/central-banking/is...
227,44,2026-03-09-03-56-54 +0000,wapo,Video appears to show U.S. Tomahawk hit naval ...,https://www.washingtonpost.com/investigations/...
166,40,2026-03-09-11-30-53 +0000,nypost,AI startup’s CEO threatened to call ex-NYC May...,https://nypost.com/2026/03/09/business/ai-star...
94,38,2026-03-09-15-13-14 +0000,nypost,Fraudster racked up a shocking $266K in fake H...,https://nypost.com/2026/03/09/lifestyle/frauds...
52,34,2026-03-09-16-33-34 +0000,nypost,Ticketmaster parent Live Nation strikes deal w...,https://nypost.com/2026/03/09/business/ticketm...
269,33,2026-03-08-21-47-41 +0000,nypost,Gavin Newsom plans to use $19M of your cash to...,https://nypost.com/2026/03/08/us-news/gov-news...
72,31,2026-03-09-16-12-37 +0000,nypost,Stephen A. Smith ends 2028 presidential talk a...,https://nypost.com/2026/03/09/sports/stephen-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)