## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-04-00-11 +0000,nyt,Syrians Want Justice for Assad-Era Killings an...,https://www.nytimes.com/2026/09/03/world/middl...
1,2026-09-03-03-53-10 +0000,nyt,Homeland Security Secretary’s Plane Makes Emer...,https://www.nytimes.com/2026/09/02/us/politics...
2,2026-09-03-03-39-53 +0000,bbc,Trump $1 coin makes him first living president...,https://www.bbc.co.uk/news/articles/c7507g9v99...
3,2026-09-03-03-37-59 +0000,startribune,The latest: Suspect identified in Minneapolis ...,https://www.startribune.com/shooting-multiple-...
4,2026-09-03-03-37-45 +0000,nypost,Trump details his ‘final 30 days’ strategy to ...,https://nypost.com/2026/09/02/us-news/trump-de...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14   trump     31
274   iran     19
59     new     18
56      up     14
181    oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
169,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...,79
150,2026-09-02-19-56-53 +0000,nyt,Trump Returns to a Familiar Playbook as the Wa...,https://www.nytimes.com/2026/09/02/us/politics...,78
175,2026-09-02-18-58-00 +0000,wapo,El-Sayed blames Trump for global bond market s...,https://www.washingtonpost.com/politics/2026/0...,74
22,2026-09-03-02-00-00 +0000,wsj,Why Trump’s Venezuela Oil Grab Is No Quick Fix...,https://www.wsj.com/business/energy-oil/why-tr...,74
224,2026-09-02-16-56-01 +0000,nypost,MapQuest surges to No. 1 in App Store after Go...,https://nypost.com/2026/09/02/business/mapques...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
169,79,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...
297,66,2026-09-02-12-55-00 +0000,wapo,"Watch Ontario, New York, residents sound off o...",https://www.washingtonpost.com/politics/2026/0...
392,62,2026-09-02-06-31-08 +0000,nypost,Battle-worn USS Abraham Lincoln sailors finall...,https://nypost.com/2026/09/02/world-news/uss-a...
31,50,2026-09-03-01-00-00 +0000,wsj,With conservative figures such as Steve Bannon...,https://www.wsj.com/politics/policy/bernie-aoc...
159,50,2026-09-02-19-33-25 +0000,nypost,Bessent says Ukraine causing high gas prices: ...,https://nypost.com/2026/09/02/us-news/scott-be...
167,47,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
65,46,2026-09-02-23-36-49 +0000,bbc,Uber launches UK's first robotaxis with a driv...,https://www.bbc.co.uk/news/articles/ce9e838jzp...
235,41,2026-09-02-16-22-36 +0000,nypost,Ex-pop star Gary Glitter pleads not guilty to ...,https://nypost.com/2026/09/02/world-news/forme...
122,39,2026-09-02-20-51-44 +0000,nypost,Plane carrying DHS Secretary Markwayne Mullin ...,https://nypost.com/2026/09/02/us-news/plane-ca...
261,38,2026-09-02-15-28-53 +0000,nypost,"Teacher, students sue OpenAI over deadly Canad...",https://nypost.com/2026/09/02/business/teacher...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)