## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...
1,2026-04-22-07-14-00 +0000,wsj,Gold Rises as Oil Prices Ease After U.S. Cease...,https://www.wsj.com/finance/commodities-future...
2,2026-04-22-07-13-45 +0000,bbc,UK inflation rises after Iran war pushes up fu...,https://www.bbc.com/news/articles/cnv8l17r51ro...
3,2026-04-22-07-12-45 +0000,bbc,World's biggest condom maker set to raise pric...,https://www.bbc.com/news/articles/cy71zj1381po...
4,2026-04-22-07-06-30 +0000,nypost,Mexico to beef up security at tourist sites af...,https://nypost.com/2026/04/22/world-news/mexic...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
0       trump     41
8        iran     39
14         up     20
515       new     19
79   virginia     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
252,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,188
97,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,145
0,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,131
6,2026-04-22-07-01-00 +0000,wsj,Oil Falls as Trump Extends Cease-Fire With Iran,https://www.wsj.com/finance/commodities-future...,128
81,2026-04-22-01-18-36 +0000,bbc,Oil prices dip as Trump extends Iran war cease...,https://www.bbc.com/news/articles/c995dkl4dvvo...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
252,188,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
148,65,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
59,62,2026-04-22-02-30-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
119,51,2026-04-21-23-19-00 +0000,wsj,New York Attorney General Letitia James has su...,https://www.wsj.com/politics/policy/new-york-s...
312,50,2026-04-21-14-52-47 +0000,cbc,"2 Palestinians, including 14-year-old, killed ...",https://www.cbc.ca/news/world/palestinians-kil...
246,46,2026-04-21-18-15-31 +0000,nypost,Rep. Sheila Cherfilus-McCormick resigns from C...,https://nypost.com/2026/04/21/us-news/rep-shei...
4,46,2026-04-22-07-06-30 +0000,nypost,Mexico to beef up security at tourist sites af...,https://nypost.com/2026/04/22/world-news/mexic...
129,44,2026-04-21-22-47-02 +0000,nypost,UK PM Starmer gets support from Trump as he fa...,https://nypost.com/2026/04/21/us-news/uk-pm-st...
38,36,2026-04-22-04-06-52 +0000,nypost,Ex-Ohio State president Ted Carter’s girlfrien...,https://nypost.com/2026/04/22/us-news/ex-ohio-...
328,36,2026-04-21-14-01-21 +0000,nypost,"Dow slumps nearly 300 points, oil prices surge...",https://nypost.com/2026/04/21/business/dow-jum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)