## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-03-37-03 +0000,nypost,Tennessee woman arrested for allegedly trying ...,https://nypost.com/2026/07/17/us-news/tennesse...
1,2026-07-18-03-33-57 +0000,nyt,AIPAC Closes Donor Portal to Democrats Who Vot...,https://www.nytimes.com/2026/07/17/us/politics...
2,2026-07-18-03-19-36 +0000,nyt,7 Americans Sent to Disputed Kenya Ebola Site ...,https://www.nytimes.com/2026/07/17/world/afric...
3,2026-07-18-03-06-42 +0000,nyt,Trump Threatens Canada With Tariffs for Wildfi...,https://www.nytimes.com/2026/07/17/weather/tru...
4,2026-07-18-03-02-01 +0000,bbc,US strikes hit Iran for seventh consecutive night,https://www.bbc.co.uk/news/articles/cy748n8zx8...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
24      trump     39
23        new     20
71   election     16
672   burnham     14
615    market     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
29,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...,128
287,2026-07-17-10-42-00 +0000,wsj,President Trump’s speech Thursday night set ou...,https://www.wsj.com/politics/policy/trumps-25-...,108
70,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...,103
166,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...,94
80,2026-07-17-21-38-56 +0000,nypost,Trump says Canada must pay new tariffs due to ...,https://nypost.com/2026/07/17/us-news/trump-sa...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
29,128,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...
332,77,2026-07-17-05-24-56 +0000,nypost,Andy Burnham declared leader of Britain’s Labo...,https://nypost.com/2026/07/17/world-news/manch...
70,64,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...
267,58,2026-07-17-12-34-28 +0000,nypost,NYC wakes up to ‘unhealthy’ air quality from C...,https://nypost.com/2026/07/17/us-news/nyc-has-...
166,55,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...
107,47,2026-07-17-20-51-50 +0000,missionlocal,Meet the billionaires behind $336M ‘explosion’...,https://missionlocal.org/2026/07/california-bi...
256,46,2026-07-17-13-00-00 +0000,wsj,"The Treasury market looks healthy, but underne...",https://www.wsj.com/finance/investing/how-sky-...
82,41,2026-07-17-21-38-00 +0000,wsj,China’s Moonshot AI Adds More Fuel to Wall Str...,https://www.wsj.com/finance/stocks/chinas-moon...
14,39,2026-07-18-02-02-23 +0000,nypost,Sunny Hostin tried to talk cops of out busting...,https://nypost.com/2026/07/17/us-news/sunny-ho...
245,36,2026-07-17-13-39-25 +0000,nypost,Iranian strikes hit major source of Kuwaiti dr...,https://nypost.com/2026/07/17/world-news/irani...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)