## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-19-23-09-54 +0000,nyt,Californians Get Stingier at the Ballot Box as...,https://www.nytimes.com/2026/06/19/us/californ...
1,2026-06-19-23-04-33 +0000,cbc,Inuit could pursue foreign partners if relatio...,https://www.cbc.ca/news/canada/north/inuit-sov...
2,2026-06-19-23-02-29 +0000,nypost,Disbelief as California drivers can’t buy chea...,https://nypost.com/2026/06/19/us-news/why-cali...
3,2026-06-19-23-00-00 +0000,wsj,America’s Economic Anxiety Is Rising Up the In...,https://www.wsj.com/economy/americas-economic-...
4,2026-06-19-22-56-47 +0000,nypost,White House turns on MAGA allies as Iran deal ...,https://nypost.com/2026/06/19/us-news/white-ho...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2632/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
36      iran     37
128    trump     26
37      deal     21
718  burnham     19
256    world     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
280,2026-06-19-02-51-00 +0000,wsj,Vance Slams Israeli Critics of Trump’s Deal Wi...,https://www.wsj.com/world/middle-east/vance-to...,101
289,2026-06-19-02-10-00 +0000,wsj,The Pentagon needs $80 billion to cover costs ...,https://www.wsj.com/politics/national-security...,99
273,2026-06-19-04-12-07 +0000,bbc,"In Trump's shadow, Vance becomes face of Iran ...",https://www.bbc.com/news/articles/cx23jr133lwo...,99
251,2026-06-19-08-00-00 +0000,cbc,Trump routinely trashes the Obama-era Iran nuc...,https://www.cbc.ca/news/world/trump-iran-deal-...,99
112,2026-06-19-16-37-27 +0000,nyt,Trump’s Iran Deal Is Off to a Chaotic Start,https://www.nytimes.com/2026/06/19/world/middl...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
280,101,2026-06-19-02-51-00 +0000,wsj,Vance Slams Israeli Critics of Trump’s Deal Wi...,https://www.wsj.com/world/middle-east/vance-to...
222,76,2026-06-19-09-54-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...
289,62,2026-06-19-02-10-00 +0000,wsj,The Pentagon needs $80 billion to cover costs ...,https://www.wsj.com/politics/national-security...
105,59,2026-06-19-17-00-00 +0000,wsj,Warsh’s first test as Fed chairman will be rea...,https://www.wsj.com/economy/central-banking/fe...
67,56,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...
292,54,2026-06-19-01-42-00 +0000,wsj,The architects of California’s proposed billio...,https://www.wsj.com/politics/policy/union-behi...
122,41,2026-06-19-15-46-59 +0000,nypost,Houston TV meteorologist whines she never won ...,https://nypost.com/2026/06/19/media/houston-tv...
141,41,2026-06-19-14-53-52 +0000,bbc,Lebanon says Israeli strikes kill 47 as Israel...,https://www.bbc.com/news/articles/c23ymz1n9rmo...
82,40,2026-06-19-18-20-00 +0000,wsj,The Fed’s vice chair of supervision spoke at a...,https://www.wsj.com/economy/central-banking/to...
309,38,2026-06-19-00-00-00 +0000,wsj,When Senate hopeful Ken Paxton attacks the mas...,https://www.wsj.com/politics/elections/texas-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)