## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-30-10-55-00 +0000,nyt,Live Updates: Passengers Intervene After Clash...,https://www.nytimes.com/live/2026/09/30/world/...
1,2026-09-30-10-50-00 +0000,wsj,Cal-Maine Swings to a Loss as Lower Egg Prices...,https://www.wsj.com/business/retail/cal-maine-...
2,2026-09-30-10-48-00 +0000,wsj,"With less than five weeks to the midterms, her...",https://www.wsj.com/politics/policy/three-surp...
3,2026-09-30-10-47-49 +0000,bbc,Household energy bills forecast to see biggest...,https://www.bbc.co.uk/news/articles/cwz0zvj4m1...
4,2026-09-30-10-44-00 +0000,wsj,Euro Unlikely to Extend Recent Losses Much Fur...,https://www.wsj.com/finance/currencies/asian-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
268    trump     52
93        ai     24
359      new     21
55   burnham     14
431     will     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
218,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...,206
360,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...,139
334,2026-09-29-17-27-33 +0000,chitri,President Trump says top tech firms have signe...,https://www.chicagotribune.com/2026/09/29/dona...,118
213,2026-09-29-21-55-00 +0000,cbc,Trump says top tech firms have signed accord t...,https://www.cbc.ca/news/world/ai-trump-agreeme...,112
308,2026-09-29-18-51-31 +0000,nypost,Trump calls for ‘tremendous self-regulation’ a...,https://nypost.com/2026/09/29/us-news/trump-ca...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
218,206,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...
336,74,2026-09-29-17-22-18 +0000,nyt,Prime Minister Andy Burnham Lays Out Plan to C...,https://www.nytimes.com/2026/09/29/world/europ...
195,71,2026-09-29-23-00-00 +0000,wsj,Americans in both parties back government-impo...,https://www.wsj.com/politics/policy/americans-...
28,67,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...
135,49,2026-09-30-03-45-06 +0000,nypost,Cops descend on home of wife of slaughtered NY...,https://nypost.com/2026/09/29/us-news/police-r...
300,49,2026-09-29-19-10-00 +0000,wsj,New York Fed President John Williams said that...,https://www.wsj.com/economy/central-banking/ne...
270,48,2026-09-29-20-20-00 +0000,wsj,Long-Term Treasury Yields Push Higher Despite ...,https://www.wsj.com/finance/investing/long-ter...
455,46,2026-09-29-11-00-57 +0000,chitri,News organizations ask court to bar White Hous...,https://www.chicagotribune.com/2026/09/29/news...
459,45,2026-09-29-11-00-00 +0000,missionlocal,He was waiting to board an SFO flight to Dalla...,https://missionlocal.org/2026/09/sfo-ice-arres...
361,45,2026-09-29-16-26-52 +0000,latimes,Woman arrested after 4-month-old baby found de...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)