## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-12-02-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...
1,2026-05-25-12-00-00 +0000,nypost,Knicks fans flock to Cleveland to watch team ‘...,https://nypost.com/2026/05/25/sports/knicks-fa...
2,2026-05-25-11-55-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
3,2026-05-25-11-49-00 +0000,wsj,Auto & Transport Roundup: Market Talk,https://www.wsj.com/business/auto-transport-ro...
4,2026-05-25-11-45-00 +0000,wsj,Oil Slides as Ships Move Toward Hormuz,https://www.wsj.com/business/energy-oil/oil-ma...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
85    iran     27
28    deal     18
263  trump     17
106  peace      7
20     oil      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
188,2026-05-24-14-33-01 +0000,nypost,Trump vows Iran can never have a nuke — and US...,https://nypost.com/2026/05/24/us-news/trump-vo...,79
161,2026-05-24-18-04-00 +0000,wsj,Trump Says He Is in No Rush for an Iran Deal T...,https://www.wsj.com/world/middle-east/middle-e...,78
191,2026-05-24-13-08-59 +0000,cbc,Details emerge about potential Iran deal as Tr...,https://www.cbc.ca/news/world/details-emerge-u...,75
148,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...,75
186,2026-05-24-15-22-06 +0000,nypost,Iran’s supreme leader has agreed ‘in principle...,https://nypost.com/2026/05/24/us-news/irans-su...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
188,79,2026-05-24-14-33-01 +0000,nypost,Trump vows Iran can never have a nuke — and US...,https://nypost.com/2026/05/24/us-news/trump-vo...
90,34,2026-05-25-02-32-08 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
126,34,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
11,32,2026-05-25-11-23-36 +0000,cbc,Pope Leo warns that AI challenges must be conf...,https://www.cbc.ca/news/world/pope-leo-magnifi...
47,30,2026-05-25-09-01-55 +0000,nyt,He Name-Drops Ocasio-Cortez in His Bid for Con...,https://www.nytimes.com/2026/05/25/us/politics...
56,29,2026-05-25-08-45-00 +0000,wsj,Global Markets Gain and Oil Prices Retreat as ...,https://www.wsj.com/finance/commodities-future...
148,29,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
76,24,2026-05-25-04-45-13 +0000,bbc,Large-scale Russian attack on Ukraine leaves f...,https://www.bbc.com/news/articles/clyp6831yp5o...
190,23,2026-05-24-13-31-09 +0000,bbc,Girl raped by boys spared jail tells BBC judge...,https://www.bbc.com/news/articles/cjrp98285yvo...
9,22,2026-05-25-11-30-00 +0000,nypost,Floyd Mayweather sues notorious NYC money mana...,https://nypost.com/2026/05/25/us-news/floyd-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)