## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-14-38-30 +0000,nypost,Woman arrested after 4 men stabbed at London’s...,https://nypost.com/2026/08/05/world-news/4-peo...
1,2026-08-05-14-36-53 +0000,nyt,Shri Thanedar Is Ousted by a Democratic Social...,https://www.nytimes.com/2026/08/05/us/politics...
2,2026-08-05-14-33-21 +0000,nypost,Olympic star Alysa Liu’s brother is transgende...,https://nypost.com/2026/08/05/us-news/olympic-...
3,2026-08-05-14-32-49 +0000,nyt,How Malta Became a Tax Haven for Crocs and Oth...,https://www.nytimes.com/2026/08/05/business/ec...
4,2026-08-05-14-32-27 +0000,nyt,The New York Times’s Revenue Rises 11%,https://www.nytimes.com/2026/08/05/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14     michigan     37
242       trump     32
16      primary     31
104      senate     27
12   democratic     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
23,2026-08-05-14-14-00 +0000,wsj,Progressive Abdul El-Sayed wins Michigan Democ...,https://www.wsj.com/politics/elections/michiga...,220
37,2026-08-05-13-57-05 +0000,nypost,Far-left Michigan Dem Abdul El-Sayed beats Rep...,https://nypost.com/2026/08/05/us-news/michigan...,175
39,2026-08-05-13-55-22 +0000,nyt,Abdul El-Sayed Wins Democratic Senate Primary ...,https://www.nytimes.com/2026/08/05/us/politics...,174
19,2026-08-05-14-15-00 +0000,wsj,Some things to know about progressive firebran...,https://www.wsj.com/politics/five-things-to-kn...,165
12,2026-08-05-14-25-03 +0000,startribune,Abdul El-Sayed wins Michigan Senate primary in...,https://www.startribune.com/el-sayed-campaign-...,163

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
23,220,2026-08-05-14-14-00 +0000,wsj,Progressive Abdul El-Sayed wins Michigan Democ...,https://www.wsj.com/politics/elections/michiga...
378,106,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
20,95,2026-08-05-14-15-00 +0000,wsj,Rep. Chuck Edwards said he wouldn’t seek re-el...,https://www.wsj.com/politics/elections/embattl...
331,87,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
340,78,2026-08-04-20-18-00 +0000,wsj,"Stocks Rally, Oil Drops after Bessent Signals ...",https://www.wsj.com/finance/stocks/stocks-rall...
146,56,2026-08-05-10-00-00 +0000,latimes,New Disney partnership with TikTok will bring ...,https://www.latimes.com/entertainment-arts/bus...
247,50,2026-08-05-00-15-00 +0000,wsj,The Trump administration is revoking the visa ...,https://www.wsj.com/politics/policy/u-s-revoke...
277,48,2026-08-04-23-09-19 +0000,nypost,Paramount CEO David Ellison confident about cl...,https://nypost.com/2026/08/04/media/paramount-...
336,47,2026-08-04-20-30-00 +0000,wsj,"What’s Next for Democrats? Join a real-time, ...",https://www.wsj.com/politics/elections/live-q-...
414,47,2026-08-04-16-20-00 +0000,wsj,Missouri residents are voting on whether to ph...,https://www.wsj.com/politics/policy/missouri-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)