## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-17-51-36 +0000,nyt,Bessent Blames Ukraine for High Energy Prices,https://www.nytimes.com/2026/09/03/business/be...
1,2026-09-03-17-51-27 +0000,nyt,Los Angeles District Bans Most A.I. for Students,https://www.nytimes.com/2026/09/03/us/lausd-sc...
2,2026-09-03-17-50-53 +0000,cbc,Government must release some secret material i...,https://www.cbc.ca/news/politics/federal-court...
3,2026-09-03-17-50-08 +0000,startribune,Fox News parts ways with longtime host Maria B...,https://www.startribune.com/fox-news-parts-way...
4,2026-09-03-17-50-00 +0000,wsj,Opinion | Handouts for Hollywood—Really?,https://www.wsj.com/opinion/donald-trump-holly...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2411/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
69    trump     51
108     new     23
174      up     15
352    iran     14
371  clancy     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
280,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,122
212,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,119
226,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...,109
410,2026-09-02-18-31-03 +0000,nypost,US Mint rolls out new $1 coins featuring Presi...,https://nypost.com/2026/09/02/business/us-mint...,103
53,2026-09-03-16-36-06 +0000,nyt,Schools Giving Aid to Minority Students Could ...,https://www.nytimes.com/2026/09/03/business/ec...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
280,122,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...
214,67,2026-09-03-10-00-00 +0000,nypost,Dem NY House candidate Cait Conley ripped over...,https://nypost.com/2026/09/03/us-news/ny-dem-c...
395,66,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
388,61,2026-09-02-19-33-25 +0000,nypost,Bessent says Ukraine causing high gas prices: ...,https://nypost.com/2026/09/02/us-news/scott-be...
290,55,2026-09-03-01-00-00 +0000,wsj,With conservative figures such as Steve Bannon...,https://www.wsj.com/politics/policy/bernie-aoc...
246,48,2026-09-03-08-00-00 +0000,cbc,Lindsay Clancy supporter arrested outside cour...,https://www.cbc.ca/news/world/lindsay-clancy-m...
396,45,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...
120,42,2026-09-03-14-50-00 +0000,wsj,The Dutch central bank said it moved around 86...,https://www.wsj.com/economy/central-banking/ne...
104,41,2026-09-03-15-30-22 +0000,nypost,Billionaire Leon Black sues House Oversight Co...,https://nypost.com/2026/09/03/us-news/billiona...
72,41,2026-09-03-16-16-49 +0000,bbc,Trump hints US would not back UK over Falkland...,https://www.bbc.co.uk/news/articles/c1kx4m70l4...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)