## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-12-18-36 +0000,bbc,Gary Lineker among millionaires asking Andy Bu...,https://www.bbc.co.uk/news/articles/cvgjp79m42...
1,2026-07-23-12-17-13 +0000,bbc,"France evacuates 20,000 as wildfires spread in...",https://www.bbc.co.uk/news/articles/cy4kmr82n4...
2,2026-07-23-12-15-00 +0000,wsj,Reigniting Inflation Heaps Pressure on Europea...,https://www.wsj.com/economy/central-banking/re...
3,2026-07-23-12-14-00 +0000,wsj,Dollar Hits 3-Week High But Strength Unlikely ...,https://www.wsj.com/finance/currencies/yen-con...
4,2026-07-23-12-12-53 +0000,nyt,Google Hit With $1 Billion Fine By EU Over Sea...,https://www.nytimes.com/2026/07/23/business/go...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2316/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
209    trump     44
172      new     26
55      deal     25
149     iran     22
59   nuclear     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
398,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,132
239,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,121
127,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,119
206,2026-07-22-23-05-44 +0000,nyt,"With Saudi Deal, Trump Loosens Nuclear Standar...",https://www.nytimes.com/2026/07/22/us/politics...,114
272,2026-07-22-20-36-21 +0000,chitri,House Republicans adopt $95 billion package fo...,https://www.chicagotribune.com/2026/07/22/hous...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
398,132,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
180,91,2026-07-23-01-07-00 +0000,nypost,US carrying out new wave of Iran strikes as mi...,https://nypost.com/2026/07/22/world-news/us-ca...
406,69,2026-07-22-14-14-00 +0000,wsj,"R. James Woolsey, CIA director in Clinton admi...",https://www.wsj.com/politics/national-security...
381,64,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
171,63,2026-07-23-02-00-00 +0000,wsj,Canada’s Mark Carney has tried the carrot and ...,https://www.wsj.com/world/americas/carney-has-...
417,58,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
161,52,2026-07-23-03-03-54 +0000,nypost,Twisted four-word message accused teen killer ...,https://nypost.com/2026/07/22/us-news/californ...
109,49,2026-07-23-08-10-32 +0000,wsj,Stock Market Today: Oil Prices Jump After Hout...,https://www.wsj.com/livecoverage/stock-market-...
195,48,2026-07-22-23-55-25 +0000,latimes,D4vd's garage had signs of blood where girl's ...,https://www.latimes.com/california/story/2026-...
230,48,2026-07-22-21-55-29 +0000,nypost,Tesla profit disappoints as Elon Musk’s AI spe...,https://nypost.com/2026/07/22/business/tesla-p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)