## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-03-02-47-51 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
1,2026-07-03-02-31-54 +0000,nypost,"Democrats must shake off unpatriotic label, To...",https://nypost.com/2026/07/02/us-news/democrat...
2,2026-07-03-02-27-12 +0000,nyt,Russia Hammers Ukraine’s Capital in Deadly Att...,https://www.nytimes.com/live/2026/07/02/world/...
3,2026-07-03-02-24-34 +0000,bbc,Dangerous heatwave scorches US ahead of Fourth...,https://www.bbc.co.uk/news/articles/cevlkzer7v...
4,2026-07-03-02-24-00 +0000,wsj,"Canada, Alberta Agree to Back New Crude Pipeli...",https://www.wsj.com/world/americas/canada-albe...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
119       trump     36
35          new     16
70           up     14
19       russia     12
40   california     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...,114
288,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,88
314,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...,80
126,2026-07-02-20-08-00 +0000,wsj,"What to know about ‘Trump Accounts,’ the new s...",https://www.wsj.com/personal-finance/trump-acc...,77
335,2026-07-02-03-11-06 +0000,nypost,Tucker Carlson says he’s starting a new politi...,https://nypost.com/2026/07/01/us-news/tucker-c...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,114,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...
11,60,2026-07-03-02-03-34 +0000,nypost,Nevada couple killed in first fatal crash invo...,https://nypost.com/2026/07/02/us-news/nevada-c...
220,56,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
316,54,2026-07-02-08-15-56 +0000,wsj,"Stock Market News, July 2, 2026: Dow Rises, Na...",https://www.wsj.com/livecoverage/june-jobs-rep...
338,51,2026-07-02-03-00-00 +0000,wsj,Europe Learns It’s Hard to Start a Trade War W...,https://www.wsj.com/world/china/europe-learns-...
291,48,2026-07-02-10-21-05 +0000,cbc,"Deadly, large-scale Russian attack shakes Kyiv...",https://www.cbc.ca/news/world/missile-drone-at...
63,46,2026-07-02-22-57-52 +0000,nypost,"Up-and-coming NYC drill rapper, dad of 3-year-...",https://nypost.com/2026/07/02/us-news/nyc-dril...
72,44,2026-07-02-22-29-20 +0000,nypost,Moment underage party girls try to lie their w...,https://nypost.com/2026/07/02/us-news/californ...
192,38,2026-07-02-16-11-00 +0000,wsj,Russia Pounds Ukraine’s Capital in One of War’...,https://www.wsj.com/world/europe/russia-ukrain...
238,36,2026-07-02-13-57-46 +0000,nypost,Michigan Dem Senate front-runner Dr. Abdul El-...,https://nypost.com/2026/07/02/us-news/michigan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)