## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-12-01-18-26 +0000,nypost,ICE planning to outfit officers with gloves th...,https://nypost.com/2026/08/11/us-news/ice-plan...
1,2026-08-12-01-17-56 +0000,bbc,What to know about Trump's Patriot Games for h...,https://www.bbc.co.uk/news/articles/c89n5p4g38...
2,2026-08-12-01-16-57 +0000,nyt,Darline Graham Advances to the Republican Sena...,https://www.nytimes.com/2026/08/11/us/politics...
3,2026-08-12-01-16-02 +0000,nyt,Minnesota Primary Election Polling Offers Few ...,https://www.nytimes.com/2026/08/11/us/politics...
4,2026-08-12-01-15-04 +0000,startribune,"The Latest: Darline Graham, Ralph Norman advan...",https://www.startribune.com/the-latest-primary...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     51
62     new     27
251   iran     17
126  death     13
22   south     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
79,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...,191
36,2026-08-12-00-14-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,141
396,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,138
264,2026-08-11-15-14-04 +0000,nypost,Stunning details emerge of Trump’s catering-tr...,https://nypost.com/2026/08/11/us-news/video-ap...,118
397,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
79,191,2026-08-11-22-49-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...
396,87,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
25,70,2026-08-12-00-34-00 +0000,wsj,Sen. Darline Graham advanced Tuesday to a runo...,https://www.wsj.com/politics/elections/sen-dar...
357,60,2026-08-11-09-27-28 +0000,nypost,Ex-Syrian ruler Bashar al-Assad sentenced to d...,https://nypost.com/2026/08/11/world-news/ex-sy...
206,52,2026-08-11-17-57-52 +0000,nypost,Michigan Dem Senate candidate Abdul El-Sayed s...,https://nypost.com/2026/08/11/us-news/michigan...
274,45,2026-08-11-14-41-19 +0000,nypost,Wisconsin socialist Francesca Hong voted again...,https://nypost.com/2026/08/11/us-news/wisconsi...
233,40,2026-08-11-16-36-49 +0000,nypost,LA council president issues scathing four-word...,https://nypost.com/2026/08/11/us-news/la-counc...
213,39,2026-08-11-17-41-00 +0000,wsj,Target Hires First Chief AI Officer in Retail’...,https://www.wsj.com/business/retail/target-hir...
20,37,2026-08-12-00-44-27 +0000,nyt,As Death Toll From Colombia Earthquake Rises t...,https://www.nytimes.com/2026/08/11/world/ameri...
239,37,2026-08-11-16-19-44 +0000,bbc,Russia using North Korean missiles to strike U...,https://www.bbc.co.uk/news/articles/c151dpzwnv...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)