## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
1,2026-08-22-18-54-49 +0000,nypost,Homeless fixture has spent nearly 20 years on ...,https://nypost.com/2026/08/22/us-news/homeless...
2,2026-08-22-18-54-31 +0000,nypost,Dems credit Mamdani with otter’s return to NYC...,https://nypost.com/2026/08/22/us-news/dems-cre...
3,2026-08-22-18-52-49 +0000,startribune,Live: Max Brosmer takes over at QB for Vikings...,https://www.startribune.com/minnesota-vikings-...
4,2026-08-22-18-51-09 +0000,nypost,Dad’s DNA search uncovers ‘devastating’ secret...,https://nypost.com/2026/08/22/us-news/dna-sear...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
119    trump     38
5      trade     18
4     canada     17
1    tariffs     16
0        new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,139
131,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...,126
36,2026-08-22-16-42-00 +0000,wsj,Prime Minister Mark Carney on Saturday said Ca...,https://www.wsj.com/economy/trade/canada-annou...,103
225,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,102
162,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,139,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
225,102,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...
36,54,2026-08-22-16-42-00 +0000,wsj,Prime Minister Mark Carney on Saturday said Ca...,https://www.wsj.com/economy/trade/canada-annou...
150,50,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
49,37,2026-08-22-16-00-00 +0000,wsj,"Ashley Hinson has never lost an election. Now,...",https://www.wsj.com/politics/elections/the-for...
184,36,2026-08-21-22-08-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
38,35,2026-08-22-16-38-45 +0000,nypost,10 killed in Russian and Ukrainian attacks a d...,https://nypost.com/2026/08/22/world-news/10-ki...
214,35,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
61,32,2026-08-22-14-55-24 +0000,nyt,"Harry and Meghan See Their California Dreams, ...",https://www.nytimes.com/2026/08/22/us/meghan-h...
209,31,2026-08-21-21-13-46 +0000,missionlocal,Meet the S.F. school board candidates: Do you ...,https://missionlocal.org/2026/08/san-francisco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)