## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-07-21-05-45 +0000,bbc,"Sophia Laforteza steps away from Katseye, the ...",https://www.bbc.co.uk/news/articles/c4g305dz0y...
1,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
2,2026-08-07-21-04-00 +0000,wsj,Fed Governor Lisa Cook Is Back in Trump’s Cros...,https://www.wsj.com/politics/policy/fed-govern...
3,2026-08-07-21-01-43 +0000,missionlocal,Tenderloin Buzz: The Tenderloin Museum will be...,https://missionlocal.org/2026/08/tenderloin-bu...
4,2026-08-07-20-59-43 +0000,nypost,Nancy Guthrie investigators experiencing incre...,https://nypost.com/2026/08/07/us-news/nancy-gu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
12    trump     51
136     new     30
15    court     19
655  market     14
232      up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,166
115,2026-08-07-17-15-00 +0000,wsj,A federal appeals court on Friday halted const...,https://www.wsj.com/politics/policy/white-hous...,161
346,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...,142
370,2026-08-06-22-10-35 +0000,wapo,Trump tries new tack against birthright citize...,https://www.washingtonpost.com/politics/2026/0...,132
59,2026-08-07-19-25-36 +0000,wapo,Trump renews effort to fire Fed governor Lisa ...,https://www.washingtonpost.com/business/2026/0...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,166,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
346,91,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...
166,72,2026-08-07-15-33-00 +0000,wsj,"The U.S. labor market shed jobs in July, an un...",https://www.wsj.com/economy/jobs/july-jobs-rep...
320,62,2026-08-07-01-03-00 +0000,wsj,Rep. Max Miller is lending his re-election cam...,https://www.wsj.com/politics/elections/max-mil...
148,62,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...
12,55,2026-08-07-20-50-01 +0000,nypost,"Saudi Arabia, Turkey and Pakistan forge ‘attac...",https://nypost.com/2026/08/07/world-news/saudi...
372,51,2026-08-06-22-05-00 +0000,cbc,Man accused of starting Spokane wildfire looke...,https://www.cbc.ca/news/world/spokane-wildfire...
15,46,2026-08-07-20-47-19 +0000,chitri,Senate passes sweeping Russia sanctions bill n...,https://www.chicagotribune.com/2026/08/07/sena...
58,45,2026-08-07-19-28-29 +0000,chitri,Lawsuit filed against planned Grayslake data c...,https://www.chicagotribune.com/2026/08/07/gray...
350,38,2026-08-06-23-03-00 +0000,wsj,Airbnb Boosts Full-Year Forecast on Strong Dem...,https://www.wsj.com/business/earnings/airbnb-b...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)