## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-24-05-45-23 +0000,nypost,Michigan concertgoer attacked at music festiva...,https://nypost.com/2026/07/24/us-news/michigan...
1,2026-07-24-05-22-37 +0000,bbc,How much money do you give for a wedding gift?,https://www.bbc.co.uk/news/videos/c0jlnw825w8o...
2,2026-07-24-05-07-57 +0000,nyt,Iran War Live Updates: Iran Rejected a U.S. Ce...,https://www.nytimes.com/live/2026/07/23/world/...
3,2026-07-24-05-02-00 +0000,nypost,Plane with 11 on board bursts into flames afte...,https://nypost.com/2026/07/24/us-news/plane-ca...
4,2026-07-24-04-52-34 +0000,nyt,Modi Caught Off Guard as India’s Economic Fail...,https://www.nytimes.com/2026/07/23/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
79   trump     47
95     new     35
15    iran     29
344    oil     22
16     war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
318,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...,153
43,2026-07-24-01-00-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,143
198,2026-07-23-19-04-00 +0000,wapo,Saudi nuclear deal in doubt as Trump adds new ...,https://www.washingtonpost.com/politics/2026/0...,142
205,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...,139
146,2026-07-23-21-00-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,132

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
318,153,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...
146,85,2026-07-23-21-00-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
334,70,2026-07-23-11-02-24 +0000,chitri,US is ready to help end the ‘senseless war’ in...,https://www.chicagotribune.com/2026/07/23/us-w...
250,66,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
46,65,2026-07-24-01-00-00 +0000,wsj,Inside China’s All-Out Push to Catch Up With A...,https://www.wsj.com/world/china/china-ai-chips...
28,53,2026-07-24-02-00-00 +0000,wsj,Capital Account: When the Supreme Court struck...,https://www.wsj.com/politics/policy/trumps-tra...
264,52,2026-07-23-15-20-03 +0000,nypost,Brent crude oil surges to $100 a barrel for fi...,https://nypost.com/2026/07/23/business/brent-c...
373,45,2026-07-23-08-10-32 +0000,wsj,Stock Market Today: Oil Prices Hit $100 a Barr...,https://www.wsj.com/livecoverage/stock-market-...
276,39,2026-07-23-14-42-00 +0000,wsj,Working-class Americans have experienced a pay...,https://www.wsj.com/economy/jobs/paycheck-boos...
6,38,2026-07-24-04-41-05 +0000,nypost,Mystery girl talking to Nolan Wells before he ...,https://nypost.com/2026/07/24/us-news/female-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)