## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-18-54-42 +0000,nypost,‘Devastated’ shark attack survivor who lost an...,https://nypost.com/2026/09/22/world-news/shark...
1,2026-09-22-18-54-03 +0000,nyt,U.N. Live Updates: Trump Says He Faces Choice ...,https://www.nytimes.com/live/2026/09/22/world/...
2,2026-09-22-18-51-38 +0000,cbc,"ShinyHunters hackers say they breached FBI, st...",https://www.cbc.ca/news/world/shinyhunters-bre...
3,2026-09-22-18-47-52 +0000,nyt,An Army of Paid Creators Is Carpeting the Web ...,https://www.nytimes.com/2026/09/22/us/politics...
4,2026-09-22-18-43-29 +0000,bbc,US to build two military bases in Greenland un...,https://www.bbc.co.uk/news/articles/c9dr74g32g...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2300/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
15      trump     81
42        new     27
21       iran     25
16         he     19
60  president     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...,188
7,2026-09-22-18-39-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,184
346,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...,178
27,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...,175
226,2026-09-22-10-47-55 +0000,chitri,"In UN speech, President Donald Trump defends d...",https://www.chicagotribune.com/2026/09/22/dona...,171

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,188,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...
346,97,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...
7,77,2026-09-22-18-39-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
361,70,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...
88,62,2026-09-22-16-57-52 +0000,nypost,Gunman who sparked terror in small California ...,https://nypost.com/2026/09/22/us-news/californ...
159,52,2026-09-22-14-34-16 +0000,cbc,No charges in death of Black Mississippi teen ...,https://www.cbc.ca/news/world/grand-jury-no-ch...
92,50,2026-09-22-16-51-29 +0000,nyt,UK Leader Burnham to Hold First Meeting With T...,https://www.nytimes.com/2026/09/22/world/europ...
27,50,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...
362,47,2026-09-21-22-07-38 +0000,nypost,How the Ellisons pulled off Paramount-WBD sett...,https://nypost.com/2026/09/21/media/how-the-el...
209,42,2026-09-22-11-23-04 +0000,nypost,"GOP senator calls for Donald Trump Jr., Hunter...",https://nypost.com/2026/09/22/us-news/gop-sena...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)