## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-02-07-15-55 +0000,nypost,"Texas ‘firefighter of the year,’ two others ch...",https://nypost.com/2026/04/02/us-news/dallas-f...
1,2026-04-02-07-06-00 +0000,wsj,Swiss Inflation Rises to Highest Level in a Ye...,https://www.wsj.com/economy/swiss-inflation-ri...
2,2026-04-02-07-05-05 +0000,bbc,Elon Musk's SpaceX set to go public in $1 tril...,https://www.bbc.com/news/articles/c2k35lg92dpo...
3,2026-04-02-07-00-51 +0000,nyt,Trump Claims Military Success but Offers No Cl...,https://www.nytimes.com/live/2026/04/01/world/...
4,2026-04-02-07-00-49 +0000,nyt,Oil Prices Spike and Stocks Tumble After Trump...,https://www.nytimes.com/2026/04/01/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
30         trump     70
46          iran     59
56           war     42
542   birthright     27
543  citizenship     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
156,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...,214
31,2026-04-02-04-05-02 +0000,startribune,Trump says US forces will 'finish the job' soo...,https://www.startribune.com/iran-hits-tanker-o...,211
45,2026-04-02-02-48-00 +0000,wsj,President Trump sought to reassure skeptical A...,https://www.wsj.com/politics/national-security...,211
63,2026-04-02-01-39-31 +0000,latimes,"In major speech, Trump says Iran war will be o...",https://www.latimes.com/politics/story/2026-04...,198
361,2026-04-01-08-49-19 +0000,bbc,Oil briefly falls below $100 and shares jump o...,https://www.bbc.com/news/articles/c2489v97842o...,196

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
156,214,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...
261,126,2026-04-01-14-51-47 +0000,nyt,Lawyer Arguing at Supreme Court to Save Birthr...,https://www.nytimes.com/2026/04/01/us/politics...
152,65,2026-04-01-20-30-25 +0000,cbc,Artemis II astronauts lift off for NASA's 10-d...,https://www.cbc.ca/news/science/livestory/arte...
116,49,2026-04-01-22-05-00 +0000,wsj,The Trump administration has lifted sanctions ...,https://www.wsj.com/world/americas/u-s-lifts-s...
246,45,2026-04-01-15-50-00 +0000,wsj,The drone having its moment in the Middle East...,https://www.wsj.com/politics/national-security...
0,44,2026-04-02-07-15-55 +0000,nypost,"Texas ‘firefighter of the year,’ two others ch...",https://nypost.com/2026/04/02/us-news/dallas-f...
260,44,2026-04-01-14-52-16 +0000,nypost,Iran’s new supreme leader vows to support anti...,https://nypost.com/2026/04/01/world-news/irans...
253,38,2026-04-01-15-16-14 +0000,nypost,Kristi Noem’s hometown pals in disbelief over ...,https://nypost.com/2026/04/01/us-news/kristi-n...
371,37,2026-04-01-07-31-03 +0000,wsj,"Stock Market News, April 1, 2026: Dow Advances...",https://www.wsj.com/livecoverage/stock-market-...
93,36,2026-04-01-23-29-00 +0000,wsj,Trump endorsed a two-part plan to quickly fund...,https://www.wsj.com/politics/policy/trump-lays...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)