## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-10-35-20 +0000,nypost,Jill Biden claims she was ‘shocked’ Kamala Har...,https://nypost.com/2026/06/01/us-news/jill-bid...
1,2026-06-01-10-33-27 +0000,bbc,UK wins court case over collapsed Rwanda asylu...,https://www.bbc.com/news/articles/cy526klrk20o...
2,2026-06-01-10-32-54 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/06/01/world/...
3,2026-06-01-10-27-00 +0000,wsj,Castlelake Values Potential easyJet Offer at M...,https://www.wsj.com/business/castlelake-says-a...
4,2026-06-01-10-26-08 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/01/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
9         trump     23
22         iran     16
90   california     13
56       israel     11
313       china     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
66,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...,81
104,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...,62
2,2026-06-01-10-32-54 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/06/01/world/...,59
173,2026-05-31-19-50-13 +0000,nypost,Bitter California Republican feud turns toxic ...,https://nypost.com/2026/05/31/us-news/bitter-c...,59
0,2026-06-01-10-35-20 +0000,nypost,Jill Biden claims she was ‘shocked’ Kamala Har...,https://nypost.com/2026/06/01/us-news/jill-bid...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
66,81,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...
104,56,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...
214,45,2026-05-31-15-36-53 +0000,nypost,Israel captures medieval Crusader castle durin...,https://nypost.com/2026/05/31/world-news/israe...
68,40,2026-06-01-06-55-09 +0000,nypost,New York corrections officer was on duty when ...,https://nypost.com/2026/06/01/us-news/new-york...
194,40,2026-05-31-16-34-09 +0000,nypost,NJ Gov. Sherrill claims victory on ICE detenti...,https://nypost.com/2026/05/31/us-news/nj-gov-s...
58,35,2026-06-01-08-18-41 +0000,nypost,"Iran shoots down US drone, attacks Kuwait — as...",https://nypost.com/2026/06/01/world-news/us-la...
149,33,2026-05-31-21-27-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...
101,32,2026-06-01-02-12-56 +0000,nypost,Far-left influencer Hasan Piker defends pro-Ch...,https://nypost.com/2026/05/31/us-news/hasan-pi...
225,28,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...
188,28,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)