## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-21-16-14 +0000,nypost,Driver dies after plunging 500 feet off cliff ...,https://nypost.com/2026/05/19/us-news/californ...
1,2026-05-19-21-16-09 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/19/us/mid...
2,2026-05-19-21-13-18 +0000,nypost,NY lawmakers debate $250K gift for Taylor Swif...,https://nypost.com/2026/05/19/us-news/ny-lawma...
3,2026-05-19-21-11-24 +0000,nyt,What to Know About Tuesday’s Most Interesting ...,https://www.nytimes.com/2026/05/19/us/politics...
4,2026-05-19-21-11-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
41   trump     50
36    iran     25
201    new     18
64     san     17
65   diego     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
375,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,134
70,2026-05-19-19-42-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,127
343,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,118
153,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...,110
48,2026-05-19-20-26-32 +0000,nyt,Trump Endorses Ken Paxton in Texas Senate Runo...,https://www.nytimes.com/2026/05/19/us/politics...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
375,134,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
70,77,2026-05-19-19-42-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...
324,73,2026-05-19-03-48-21 +0000,nyt,San Diego Mosque Shooting Comes Amid Rising Re...,https://www.nytimes.com/2026/05/18/us/san-dieg...
286,52,2026-05-19-10-00-00 +0000,latimes,Forced treatment and jail: Spencer Pratt's ple...,https://www.latimes.com/california/story/2026-...
285,47,2026-05-19-10-00-00 +0000,latimes,"For the first time, a warm winter just wiped o...",https://www.latimes.com/environment/story/2026...
265,46,2026-05-19-11-01-00 +0000,wsj,The nearly $1.8 billion “anti-weaponization fu...,https://www.wsj.com/politics/how-trumps-1-776-...
380,42,2026-05-18-22-08-37 +0000,bbc,Musk loses OpenAI court battle after jury find...,https://www.bbc.com/news/articles/cewpyv79pw1o...
343,37,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
50,36,2026-05-19-20-25-15 +0000,nypost,Mango fashion tycoon embroiled in bitter dispu...,https://nypost.com/2026/05/19/world-news/mango...
227,35,2026-05-19-13-35-54 +0000,nypost,Starbucks Korea CEO fired after ‘Tank Day’ pro...,https://nypost.com/2026/05/19/world-news/starb...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)