## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-28-13-01-55 +0000,nyt,"Trump Brought Venezuelan Gold to the U.S., but...",https://www.nytimes.com/2026/09/28/world/ameri...
1,2026-09-28-13-01-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
2,2026-09-28-13-00-26 +0000,nyt,Capable but complicated: The dual realities of...,https://www.nytimes.com/live/2026/09/28/us/mid...
3,2026-09-28-13-00-00 +0000,wsj,Senate Investigation Finds Rampant Use of Teth...,https://www.wsj.com/finance/currencies/senate-...
4,2026-09-28-13-00-00 +0000,missionlocal,"Low, rider",https://missionlocal.org/2026/09/low-rider-3/

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2510/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     41
201   iran     16
258  china     12
53      uk     12
180    war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
259,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...,117
94,2026-09-28-09-09-39 +0000,wsj,"Stock Market Today: Oil, Yields Rise After Tru...",https://www.wsj.com/livecoverage/stock-market-...,93
271,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...,88
237,2026-09-27-17-30-46 +0000,wapo,"Trump says U.S., Iran slated for indirect talk...",https://www.washingtonpost.com/world/2026/09/2...,81
10,2026-09-28-12-51-00 +0000,wsj,President Trump will announce a Minnesota comp...,https://www.wsj.com/politics/trump-to-unveil-p...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
259,117,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...
270,50,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...
240,48,2026-09-27-17-24-26 +0000,nypost,One normally quiet Texas race shows 2026 will ...,https://nypost.com/2026/09/27/us-news/how-texa...
45,41,2026-09-28-11-01-00 +0000,wsj,We’ll explore what could happen if the Republi...,https://www.wsj.com/politics/heres-what-could-...
166,38,2026-09-27-23-37-26 +0000,bbc,One dead as nor'easter storm pummels New York ...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
185,36,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...
255,36,2026-09-27-16-00-34 +0000,chitri,Tensions run high in Northern Ireland after co...,https://www.chicagotribune.com/2026/09/27/nort...
145,34,2026-09-28-03-44-18 +0000,latimes,Brokers gobble up tee times at public golf cou...,https://www.latimes.com/california/story/2026-...
94,32,2026-09-28-09-09-39 +0000,wsj,"Stock Market Today: Oil, Yields Rise After Tru...",https://www.wsj.com/livecoverage/stock-market-...
10,31,2026-09-28-12-51-00 +0000,wsj,President Trump will announce a Minnesota comp...,https://www.wsj.com/politics/trump-to-unveil-p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)