## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-15-16-24-53 +0000,nypost,Fidelity Investments makes $2.5M class action ...,https://nypost.com/2026/05/15/lifestyle/fideli...
1,2026-05-15-16-24-36 +0000,bbc,"Mandelson papers being withheld, says intellig...",https://www.bbc.com/news/articles/c98rewjjwg9o...
2,2026-05-15-16-24-00 +0000,wsj,Bill Ackman’s Pershing Square Bets on Microsof...,https://www.wsj.com/finance/investing/ackman-s...
3,2026-05-15-16-19-41 +0000,nyt,Replacing a Royal Hand-Me-Down That Finally Fr...,https://www.nytimes.com/2026/05/15/arts/music/...
4,2026-05-15-16-17-06 +0000,nypost,Husband killer Kouri Richins psychotic behavio...,https://nypost.com/2026/05/15/us-news/husband-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
108  trump     57
129     xi     31
154  china     31
24     new     16
22      ai     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...,159
208,2026-05-15-06-04-46 +0000,nypost,Extravagant Trump-Xi tea menu revealed — as th...,https://nypost.com/2026/05/15/us-news/extravag...,158
76,2026-05-15-14-22-07 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,156
234,2026-05-15-01-30-15 +0000,nypost,Trump says China will ‘invest hundreds of bill...,https://nypost.com/2026/05/14/us-news/china-wi...,148
291,2026-05-14-21-36-36 +0000,nyt,Oil Prices Waver as Trump Meets China’s Xi to ...,https://www.nytimes.com/2026/05/14/business/oi...,147

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,159,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...
355,58,2026-05-14-18-13-00 +0000,wsj,Pentagon leaders say they could start running ...,https://www.wsj.com/politics/national-security...
76,56,2026-05-15-14-22-07 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
25,42,2026-05-15-15-45-53 +0000,nypost,AI scammer tricks ‘lonely’ retiree into giving...,https://nypost.com/2026/05/15/us-news/ai-scamm...
182,38,2026-05-15-08-48-55 +0000,nypost,"Oxygen toxicity, panic may have led to deaths ...",https://nypost.com/2026/05/15/world-news/oxyge...
361,38,2026-05-14-17-52-46 +0000,nyt,Iran Lets Chinese Ships Through Strait of Horm...,https://www.nytimes.com/live/2026/05/14/us/tru...
195,36,2026-05-15-07-34-35 +0000,nypost,Supreme Court preserves access to widely used ...,https://nypost.com/2026/05/15/us-news/supreme-...
352,33,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
48,30,2026-05-15-15-03-00 +0000,wsj,So You Think You Own Shares in a Hot Startup? ...,https://www.wsj.com/finance/investing/so-you-t...
319,30,2026-05-14-20-23-32 +0000,nyt,"Cerebras, A.I. Chip Maker, Rises 89% in Market...",https://www.nytimes.com/2026/05/14/technology/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)