## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-25-19-11-42 +0000,nypost,NYC preschool boss embezzled nearly $3M to buy...,https://nypost.com/2026/03/25/us-news/nyc-pres...
1,2026-03-25-19-09-00 +0000,wsj,Meta and YouTube Lose Landmark Social-Media Ad...,https://www.wsj.com/tech/meta-and-youtube-lose...
2,2026-03-25-19-08-14 +0000,nyt,Iran War Live Updates: Tehran Dismisses Cease-...,https://www.nytimes.com/live/2026/03/25/world/...
3,2026-03-25-19-06-48 +0000,nypost,Saks CEO faces ‘conflict of interest’ complain...,https://nypost.com/2026/03/25/business/saks-ce...
4,2026-03-25-19-05-49 +0000,nyt,Iran’s Attacks Force U.S. Troops to Work Remotely,https://www.nytimes.com/2026/03/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2470/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
20    iran     52
56   trump     45
21     war     26
222    oil     20
290    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
78,2026-03-25-16-57-53 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...,175
384,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,166
220,2026-03-25-10-00-00 +0000,nypost,Trump has given Israel’s Netanyahu ‘the busine...,https://nypost.com/2026/03/25/us-news/trump-ha...,158
333,2026-03-24-22-35-03 +0000,nypost,US sends 15-point plan to end war with Iran as...,https://nypost.com/2026/03/24/world-news/us-se...,155
40,2026-03-25-18-18-16 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...,153

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
78,175,2026-03-25-16-57-53 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...
165,80,2026-03-25-13-27-50 +0000,bbc,UK inflation rate stays at 3% before Iran war ...,https://www.bbc.com/news/articles/cx2w47e9v2vo...
202,75,2026-03-25-11-02-00 +0000,wsj,That the top congressional Democrats both hail...,https://www.wsj.com/politics/chuck-schumers-ot...
73,63,2026-03-25-17-06-24 +0000,nypost,"Meta, YouTube found liable for woman’s debilit...",https://nypost.com/2026/03/25/us-news/jury-tak...
77,58,2026-03-25-16-59-00 +0000,wsj,The Federal Reserve ran an operating loss of $...,https://www.wsj.com/economy/central-banking/fe...
48,57,2026-03-25-18-02-00 +0000,wsj,Democrat Emily Gregory beat a Trump-backed Rep...,https://www.wsj.com/politics/elections/democra...
369,53,2026-03-24-21-07-31 +0000,nyt,U.S. Said to Have Sent Iran a 15-Point Plan to...,https://www.nytimes.com/2026/03/24/world/middl...
151,52,2026-03-25-14-19-00 +0000,wsj,Trump plans to install some of the biggest nam...,https://www.wsj.com/politics/policy/trump-to-n...
321,48,2026-03-24-23-14-38 +0000,cbc,Air Canada CEO summoned to Ottawa over English...,https://www.cbc.ca/news/canada/air-canada-ceo-...
350,45,2026-03-24-21-56-00 +0000,wsj,GOP senators have made an offer to Democrats t...,https://www.wsj.com/politics/policy/gop-senato...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)