## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-30-17-53-30 +0000,nyt,"Democrats, Hopeful All Over the Senate Map, Re...",https://www.nytimes.com/2026/10/30/us/politics...
1,2026-10-30-17-53-01 +0000,nyt,"Tech Stocks Tumble, Putting Pressure on Broade...",https://www.nytimes.com/2026/10/30/business/st...
2,2026-10-30-17-52-18 +0000,nyt,"After Crash, Spain Asks if Its Train System Is...",https://www.nytimes.com/2026/10/29/world/europ...
3,2026-10-30-17-47-07 +0000,nyt,Binance’s $6.3 Billion Hack Is Just the Start ...,https://www.nytimes.com/2026/10/30/technology/...
4,2026-10-30-17-47-01 +0000,bbc,US tech stocks see sharp falls as AI spending ...,https://www.bbc.co.uk/news/articles/cvwy72e0n7...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2659/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
312       trump     34
110    election     29
30          new     20
3        senate     16
94   california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
308,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...,143
402,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...,109
340,2026-10-29-22-51-00 +0000,chitri,President Trump lends support for Darline Grah...,https://www.chicagotribune.com/2026/10/29/trum...,93
219,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...,87
169,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
308,143,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...
169,85,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
348,65,2026-10-29-22-20-53 +0000,nypost,Starbucks CEO Brian Niccol reveals new ideas t...,https://nypost.com/2026/10/29/business/stabuck...
235,58,2026-10-30-09-33-51 +0000,bbc,Crypto giant Binance hit by $6.3bn hack suspec...,https://www.bbc.co.uk/news/articles/cwg7xp8kx4...
342,55,2026-10-29-22-31-20 +0000,nypost,Florida first-responder couple survives Spain ...,https://nypost.com/2026/10/29/world-news/coupl...
402,47,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...
136,44,2026-10-30-13-13-52 +0000,nypost,HELOC vs. home equity loans: Which should you ...,https://nypost.com/business/heloc-vs-home-equi...
105,43,2026-10-30-14-42-04 +0000,nypost,Cheating wife caught in bed with lover and two...,https://nypost.com/2026/10/30/us-news/wife-at-...
237,43,2026-10-30-09-10-12 +0000,nypost,"Nancy Pelosi slams Mamdani, El-Sayed over ‘wro...",https://nypost.com/2026/10/30/us-news/nancy-pe...
224,39,2026-10-30-10-00-00 +0000,nypost,Here’s when top Wall Street executives expect ...,https://nypost.com/2026/10/30/business/heres-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)