## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-14-52-37 +0000,nypost,Hofstra professor facing possible termination ...,https://nypost.com/2026/08/22/us-news/hofstra-...
1,2026-08-22-14-38-44 +0000,nyt,How a Trump Envoy Uses Vodka and Dirty Jokes t...,https://www.nytimes.com/2026/08/22/world/europ...
2,2026-08-22-14-35-23 +0000,nyt,Harvard’s A.I. Clones Will Hear Your Start-Up ...,https://www.nytimes.com/2026/08/22/business/de...
3,2026-08-22-14-35-11 +0000,bbc,Father leaves 7-year-old son alone on Mount Fu...,https://www.bbc.co.uk/news/articles/c93403wg28...
4,2026-08-22-14-10-49 +0000,nypost,Five passengers burned after laptop bursts int...,https://nypost.com/2026/08/22/us-news/five-pas...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2486/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
8      trump     45
123   canada     13
152  tariffs     12
60       new     11
725    court     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...,120
194,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,119
237,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,117
80,2026-08-22-09-00-00 +0000,wsj,President Trump is quietly making plans for an...,https://www.wsj.com/politics/policy/trump-new-...,107
119,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,120,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...
97,98,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
119,51,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
10,41,2026-08-22-13-50-11 +0000,nypost,Ohio mom ‘devastated’ after son killed in car ...,https://nypost.com/2026/08/22/us-news/mom-lear...
184,36,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
32,35,2026-08-22-12-18-43 +0000,nyt,"Harry and Meghan See Their California Dreams, ...",https://www.nytimes.com/2026/08/22/us/meghan-h...
69,35,2026-08-22-09-03-47 +0000,nyt,How a Progressive Democrat in Florida Gave Her...,https://www.nytimes.com/2026/08/22/us/politics...
153,34,2026-08-21-22-08-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
128,31,2026-08-21-23-56-56 +0000,latimes,"If Dodgers are put up for sale, previous runne...",https://www.latimes.com/sports/dodgers/story/2...
66,29,2026-08-22-09-11-27 +0000,nypost,Iryna Zarutska’s family files wrongful death l...,https://nypost.com/2026/08/22/us-news/iryna-za...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)