## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-24-14-19-46 +0000,bbc,The assisted dying bill has failed - but the d...,https://www.bbc.com/news/articles/cm2k59l2l02o...
1,2026-04-24-14-18-00 +0000,wsj,Western Union Profit Falls as Immigration Poli...,https://www.wsj.com/business/earnings/western-...
2,2026-04-24-14-17-42 +0000,bbc,Assisted dying bill runs out of time to become...,https://www.bbc.com/news/articles/cgk0vz5e2zxo...
3,2026-04-24-14-17-39 +0000,nyt,Iran War Live Updates: U.S. Blockade Will Last...,https://www.nytimes.com/live/2026/04/24/world/...
4,2026-04-24-14-17-38 +0000,bbc,No 10 says Falklands sovereignty rests with UK...,https://www.bbc.com/news/articles/cde51y0zgjyo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35   trump     46
19    iran     26
20     war     25
48     new     15
228     he     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-04-24-06-56-27 +0000,nypost,"Israel, Lebanon extend cease-fire as Trump see...",https://nypost.com/2026/04/24/world-news/israe...,119
254,2026-04-23-21-23-43 +0000,nypost,Trump threatens to ‘finish it up militarily’ i...,https://nypost.com/2026/04/23/us-news/trump-th...,98
371,2026-04-23-16-02-26 +0000,wapo,Trump ally asked FIFA to have Italy replace Ir...,https://www.washingtonpost.com/world/2026/04/2...,94
268,2026-04-23-20-45-51 +0000,bbc,US boards ship carrying Iran oil as Trump thre...,https://www.bbc.com/news/articles/cgldw5ekrjpo...,93
169,2026-04-24-03-18-26 +0000,nyt,Trump Says Israel and Lebanon Agree to Extend ...,https://www.nytimes.com/2026/04/23/us/politics...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,119,2026-04-24-06-56-27 +0000,nypost,"Israel, Lebanon extend cease-fire as Trump see...",https://nypost.com/2026/04/24/world-news/israe...
11,82,2026-04-24-14-00-00 +0000,wsj,The road to war last year featured rising prof...,https://www.wsj.com/politics/national-security...
365,47,2026-04-23-16-09-12 +0000,nypost,Lululemon shares dive on new CEO pick — as inv...,https://nypost.com/2026/04/23/business/lululem...
311,44,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
30,43,2026-04-24-13-15-28 +0000,nypost,Benjamin Netanyahu reveals he was quietly trea...,https://nypost.com/2026/04/24/world-news/benja...
276,43,2026-04-23-20-26-30 +0000,nypost,"Meta to ax 8,000 jobs as Zuckerberg doubles do...",https://nypost.com/2026/04/23/business/meta-to...
200,40,2026-04-23-23-51-41 +0000,nypost,As US soldier is charged for alleged Maduro be...,https://nypost.com/2026/04/23/business/as-us-s...
337,36,2026-04-23-17-00-11 +0000,wapo,"Once accused of election fraud, former small-t...",https://www.washingtonpost.com/nation/2026/04/...
126,36,2026-04-24-08-48-30 +0000,nypost,Trump threatens UK PM Starmer with ‘big tariff...,https://nypost.com/2026/04/24/business/trump-t...
94,35,2026-04-24-10-00-00 +0000,latimes,California's jet fuel stockpile hits two-year ...,https://www.latimes.com/business/story/2026-04...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)