## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-11-01-00 +0000,wsj,President Trump has hinted that there’s a big ...,https://www.wsj.com/politics/policy/what-might...
1,2026-10-12-11-00-00 +0000,missionlocal,‘Proof we were there’: A reporter’s SoMa homec...,https://missionlocal.org/2026/10/soma-reporter...
2,2026-10-12-10-57-00 +0000,wsj,Dollar Strength Could Continue on Fed Rate-Ris...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-10-12-10-55-00 +0000,wsj,"Trump’s Russian-Diesel Move Draws Pushback, Sk...",https://www.wsj.com/logistics-report/trumps-ru...
4,2026-10-12-10-53-26 +0000,wapo,The 401(k) choice many don’t know they’re making,https://www.washingtonpost.com/business/2026/1...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2569/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
1      trump     37
220   russia     13
29    diesel     10
224  ukraine     10
874  airport      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
216,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,93
207,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,89
215,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...,88
142,2026-10-11-21-22-00 +0000,wsj,Trump Pushes Russia-Ukraine Energy Ceasefire a...,https://www.wsj.com/world/trump-declares-a-rus...,88
43,2026-10-12-09-01-16 +0000,wsj,Stock Market Today: Diesel Prices Slip on Trum...,https://www.wsj.com/livecoverage/stock-market-...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
216,93,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...
184,56,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
207,52,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...
226,44,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
66,41,2026-10-12-07-58-00 +0000,wsj,Oil Prices Fall as Traders Weigh Russian Diese...,https://www.wsj.com/business/energy-oil/oil-pr...
23,39,2026-10-12-10-00-00 +0000,nypost,AI safety ‘doomers’ pouring cash into Minnesot...,https://nypost.com/2026/10/12/business/ai-safe...
232,36,2026-10-11-11-31-16 +0000,nypost,Man mauled to death by tiger was happily danci...,https://nypost.com/2026/10/11/world-news/man-m...
24,30,2026-10-12-10-00-00 +0000,latimes,"Republican Steve Hilton leans on cheeky ads, v...",https://www.latimes.com/california/story/2026-...
214,29,2026-10-11-14-00-00 +0000,wsj,"When companies stop driving a hard bargain, Cl...",https://www.wsj.com/finance/investing/beth-ham...
87,27,2026-10-12-05-13-45 +0000,nypost,2 victims of Pa. grandpa’s murder-suicide that...,https://nypost.com/2026/10/12/us-news/2-victim...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)