## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-09-17-00-08 +0000,bbc,How Reform won votes from Swansea to Sunderland,https://www.bbc.com/news/articles/cwy2nz4gwj5o...
1,2026-05-09-16-58-07 +0000,nypost,LA man who killed police cadet in wrong-way cr...,https://nypost.com/2026/05/09/us-news/la-man-w...
2,2026-05-09-16-36-22 +0000,nypost,Subway shove suspect flashes smile in court af...,https://nypost.com/2026/05/09/us-news/subway-s...
3,2026-05-09-16-34-07 +0000,nypost,"Betty Broderick, convicted in infamous killing...",https://nypost.com/2026/05/09/us-news/betty-br...
4,2026-05-09-16-27-52 +0000,nyt,Frontier Jet Hits Person on Runway During Take...,https://www.nytimes.com/2026/05/09/us/frontier...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
66   trump     25
34     new     18
119   iran     13
23   court     13
120    war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
263,2026-05-08-18-38-40 +0000,nypost,Trump announces three-day Ukraine-Russia cease...,https://nypost.com/2026/05/08/us-news/trump-an...,71
152,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...,65
260,2026-05-08-18-45-10 +0000,cbc,"Russia, Ukraine agree to 3-day ceasefire and p...",https://www.cbc.ca/news/world/russia-ukraine-c...,65
188,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...,64
238,2026-05-08-20-16-00 +0000,wsj,Russia and Ukraine Agree to Three-Day Ceasefir...,https://www.wsj.com/world/russia-and-ukraine-a...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
263,71,2026-05-08-18-38-40 +0000,nypost,Trump announces three-day Ukraine-Russia cease...,https://nypost.com/2026/05/08/us-news/trump-an...
152,65,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
188,64,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...
207,45,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...
31,43,2026-05-09-14-45-38 +0000,nypost,WHO to oversee evacuations from hantavirus-str...,https://nypost.com/2026/05/09/world-news/who-h...
234,43,2026-05-08-20-27-18 +0000,cbc,Putin oversees scaled-back WW II Victory Day p...,https://www.cbc.ca/news/world/russia-victory-d...
258,42,2026-05-08-18-51-17 +0000,nypost,California’s ‘abusive relationship’ with one-p...,https://nypost.com/2026/05/08/us-news/critics-...
43,36,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
29,33,2026-05-09-14-51-51 +0000,cbc,Pedestrian dies after being hit by plane takin...,https://www.cbc.ca/news/world/denver-airport-p...
1,32,2026-05-09-16-58-07 +0000,nypost,LA man who killed police cadet in wrong-way cr...,https://nypost.com/2026/05/09/us-news/la-man-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)