## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-04-17-58-34 +0000,nypost,Laguna Beach ‘Karen’ hijacks California couple...,https://nypost.com/2026/10/04/us-news/laguna-b...
1,2026-10-04-17-53-18 +0000,nyt,How Kansas Suddenly Became a Battleground Stat...,https://www.nytimes.com/2026/10/04/us/politics...
2,2026-10-04-17-53-18 +0000,nyt,"Shooting in Vienna, Ga., Leaves 2 Dead and Doz...",https://www.nytimes.com/2026/10/04/us/shooting...
3,2026-10-04-17-50-59 +0000,bbc,Green Party members back 'Zionism is racism' m...,https://www.bbc.co.uk/news/articles/c6jdm5n1vy...
4,2026-10-04-17-49-03 +0000,nyt,Israeli Authorities Trade Blame for Failure to...,https://www.nytimes.com/2026/10/04/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2624/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
207     trump     24
132       new     15
33   flydubai     12
138        up      9
99        oil      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
47,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,65
188,2026-10-03-22-20-25 +0000,chitri,Pres. Donald Trump urges calls to Arkansas Sen...,https://www.chicagotribune.com/2026/10/03/trum...,65
189,2026-10-03-22-18-41 +0000,chitri,Pres. Donald Trump rallies in Ohio to boost Jo...,https://www.chicagotribune.com/2026/10/03/trum...,62
43,2026-10-04-14-55-38 +0000,nypost,"Police, firefighter unions back Dem NY Rep. To...",https://nypost.com/2026/10/04/us-news/police-f...,60
203,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
47,65,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
148,44,2026-10-04-03-15-01 +0000,nypost,Longtime aviation pal of stabbed flydubai pilo...,https://nypost.com/2026/10/03/world-news/longt...
86,41,2026-10-04-10-00-38 +0000,chitri,"Illinois Senate race: Republican Don Tracy, a ...",https://www.chicagotribune.com/2026/10/04/illi...
188,41,2026-10-03-22-20-25 +0000,chitri,Pres. Donald Trump urges calls to Arkansas Sen...,https://www.chicagotribune.com/2026/10/03/trum...
17,39,2026-10-04-16-57-36 +0000,chitri,Germany’s Merz announces new aid for Ukraine i...,https://www.chicagotribune.com/2026/10/04/germ...
83,36,2026-10-04-10-49-14 +0000,wapo,"U.S. Marine accused of killing woman in Japan,...",https://www.washingtonpost.com/world/2026/10/0...
139,35,2026-10-04-05-33-22 +0000,nypost,Shooting near Baltimore youth football event l...,https://nypost.com/2026/10/04/us-news/shooting...
158,33,2026-10-04-01-35-10 +0000,nypost,Debris from vanished Boston-bound plane found ...,https://nypost.com/2026/10/03/world-news/debri...
90,33,2026-10-04-10-00-01 +0000,wapo,Should Big Oil pay for climate change? A Supre...,https://www.washingtonpost.com/politics/2026/1...
173,30,2026-10-04-00-00-00 +0000,wsj,GOP congressman Byron Donalds is poised to bec...,https://www.wsj.com/politics/elections/byron-d...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)