## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-02-46-13 +0000,startribune,Live: Timberwolves come up short vs Warriors i...,https://www.startribune.com/minnesota-timberwo...
1,2026-10-29-02-42-50 +0000,nyt,Judge Rejects Trump Officials’ Bid to Set Asid...,https://www.nytimes.com/2026/10/28/us/politics...
2,2026-10-29-02-34-17 +0000,nyt,Fire Breaks Out at South Carolina Nuclear Site,https://www.nytimes.com/2026/10/28/us/nuclear-...
3,2026-10-29-02-28-50 +0000,nypost,Chilling final texts of Long Island mom of fou...,https://nypost.com/2026/10/28/us-news/final-te...
4,2026-10-29-02-27-45 +0000,nyt,Israel’s Parties Gird for Wrangling to Form a ...,https://www.nytimes.com/2026/10/28/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2660/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14        trump     31
298    election     31
39       israel     24
17   california     20
387      budget     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
107,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...,137
300,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...,106
267,2026-10-28-16-34-01 +0000,nyt,Netanyahu Didn’t Win Israel’s Election. But He...,https://www.nytimes.com/2026/10/28/world/middl...,102
345,2026-10-28-12-38-03 +0000,nyt,Israel’s Election: When Will We Know Who Will ...,https://www.nytimes.com/2026/10/25/world/middl...,101
104,2026-10-28-21-28-00 +0000,wsj,Flávio Bolsonaro landed in Miami after losing ...,https://www.wsj.com/world/americas/flavio-bols...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
107,137,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...
324,83,2026-10-28-13-57-54 +0000,chitri,High-speed train collision kills at least 68 i...,https://www.chicagotribune.com/2026/10/28/high...
345,70,2026-10-28-12-38-03 +0000,nyt,Israel’s Election: When Will We Know Who Will ...,https://www.nytimes.com/2026/10/25/world/middl...
26,68,2026-10-29-01-12-00 +0000,wsj,Fed Chairman Kevin Warsh said higher rates are...,https://www.wsj.com/economy/central-banking/th...
104,68,2026-10-28-21-28-00 +0000,wsj,Flávio Bolsonaro landed in Miami after losing ...,https://www.wsj.com/world/americas/flavio-bols...
300,63,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...
384,56,2026-10-28-10-00-00 +0000,latimes,Your last-minute guide to California governor ...,https://www.latimes.com/california/story/2026-...
299,48,2026-10-28-15-10-32 +0000,cbc,Russell Brand denies all charges as he takes t...,https://www.cbc.ca/news/world/russell-brand-ra...
367,47,2026-10-28-10-47-00 +0000,wsj,Are Democrats drawing up a new map in the Sout...,https://www.wsj.com/politics/elections/are-dem...
169,47,2026-10-28-19-42-42 +0000,bbc,US central bank holds interest rates steady ah...,https://www.bbc.co.uk/news/articles/cr15jxzv4w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)