## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-26-02-45-04 +0000,startribune,Trump says suspect was armed with multiple wea...,https://www.startribune.com/close-watch-on-how...
1,2026-04-26-02-44-29 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/25/us/tru...
2,2026-04-26-02-24-28 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...
3,2026-04-26-02-20-18 +0000,nyt,Trump Seeks to Abolish Iran’s Nuclear Stockpil...,https://www.nytimes.com/2026/04/25/us/politics...
4,2026-04-26-02-19-26 +0000,startribune,Live from Game 4: Timberwolves’ Donte DiVincen...,https://www.startribune.com/minnesota-timberwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2631/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

              word  score
0            trump     26
12            iran     16
7            house     15
6            white     12
8   correspondents     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-04-26-00-56-40 +0000,nypost,Trump rushed out of White House Correspondents...,https://nypost.com/2026/04/25/us-news/shots-fi...,100
2,2026-04-26-02-24-28 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...,93
10,2026-04-26-01-59-28 +0000,nypost,Chaos at the White House Correspondents’ Dinne...,https://nypost.com/2026/04/25/us-news/chaos-at...,93
17,2026-04-26-01-12-57 +0000,latimes,Trump rushed off stage after shooting at White...,https://www.latimes.com/california/story/2026-...,93
81,2026-04-25-19-12-29 +0000,nyt,"At White House Correspondents Dinner, Trump Wi...",https://www.nytimes.com/2026/04/25/us/politics...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,100,2026-04-26-00-56-40 +0000,nypost,Trump rushed out of White House Correspondents...,https://nypost.com/2026/04/25/us-news/shots-fi...
2,67,2026-04-26-02-24-28 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...
55,45,2026-04-25-21-31-01 +0000,nypost,Wild bodycam footage shows California cop’s li...,https://nypost.com/2026/04/25/us-news/antioch-...
32,36,2026-04-25-23-24-57 +0000,nyt,Al Qaeda-Linked Militants Launch Major Attacks...,https://www.nytimes.com/2026/04/25/world/afric...
26,31,2026-04-26-00-06-02 +0000,startribune,North Dakota state legislator one of two kille...,https://www.startribune.com/small-plane-crashe...
157,27,2026-04-25-05-25-54 +0000,nypost,Florida Dem Sheila Cherfilus-McCormick filed f...,https://nypost.com/2026/04/25/us-news/florida-...
44,24,2026-04-25-22-21-25 +0000,nyt,Chicago Hospital Shooting Leaves 1 Officer Dea...,https://www.nytimes.com/2026/04/25/us/chicago-...
58,23,2026-04-25-21-14-06 +0000,nypost,Opportunist or socialist? Mamdani-backed NYC C...,https://nypost.com/2026/04/25/us-news/mamdani-...
97,21,2026-04-25-16-45-12 +0000,nypost,King Charles will be treated to historic milit...,https://nypost.com/2026/04/25/us-news/king-cha...
124,19,2026-04-25-12-00-00 +0000,latimes,"Lopez: Fraud is rampant, but good hospice care...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)