## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-21-16-13-46 +0000,nyt,"Moya Brennan, Whose Gaelic Pop Band Won Worldw...",https://www.nytimes.com/2026/04/19/obituaries/...
1,2026-04-21-16-13-27 +0000,bbc,Israeli soldiers punished over vandalism of Je...,https://www.bbc.com/news/articles/cew790ppn8jo...
2,2026-04-21-16-12-21 +0000,nyt,"Iran War Live Updates: Cease-Fire Nears End, a...",https://www.nytimes.com/live/2026/04/21/world/...
3,2026-04-21-16-12-19 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/21/world/...
4,2026-04-21-16-12-00 +0000,nyt,Oil Prices Climb and Stocks Wobble as Investor...,https://www.nytimes.com/2026/04/21/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     30
17    iran     26
609    new     16
18     war     15
139   year     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
230,2026-04-21-01-14-06 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,106
232,2026-04-21-01-00-00 +0000,wsj,President Trump picked Kevin Warsh for Fed cha...,https://www.wsj.com/economy/central-banking/wa...,99
193,2026-04-21-07-26-13 +0000,nypost,Iran ‘prepared to reveal new cards on the batt...,https://nypost.com/2026/04/21/world-news/iran-...,90
102,2026-04-21-13-14-14 +0000,nypost,Trump doesn’t want to extend Iran cease-fire —...,https://nypost.com/2026/04/21/us-news/trump-do...,82
258,2026-04-20-21-52-12 +0000,bbc,Trump says US will not lift Hormuz blockade un...,https://www.bbc.com/news/articles/cdxd88r2wjzo...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
230,106,2026-04-21-01-14-06 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...
232,69,2026-04-21-01-00-00 +0000,wsj,President Trump picked Kevin Warsh for Fed cha...,https://www.wsj.com/economy/central-banking/wa...
202,66,2026-04-21-05-57-56 +0000,bbc,New era as Apple names new boss to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
255,55,2026-04-20-22-16-55 +0000,wapo,Two teens killed after planned fight near Nort...,https://www.washingtonpost.com/nation/2026/04/...
117,45,2026-04-21-12-34-39 +0000,nypost,Chilling video shows moment Mexico pyramid sho...,https://nypost.com/2026/04/21/world-news/mexic...
267,44,2026-04-20-21-32-00 +0000,wsj,Singer D4vd Pleads Not Guilty in Murder of 14-...,https://www.wsj.com/us-news/singer-d4vd-charge...
269,44,2026-04-20-21-23-13 +0000,nypost,Labor Secretary Lori Chavez-DeRemer resigns fr...,https://nypost.com/2026/04/20/us-news/labor-se...
160,40,2026-04-21-10-18-45 +0000,cbc,Ex-official blames pressure from U.K. prime mi...,https://www.cbc.ca/news/world/uk-prime-ministe...
28,39,2026-04-21-15-42-47 +0000,nypost,California public school district ranked in to...,https://nypost.com/2026/04/21/us-news/2-califo...
350,38,2026-04-20-17-11-43 +0000,cbc,Kenya's Korir successfully defends Boston Mara...,https://www.cbc.ca/sports/olympics/summer/athl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)