## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-08-55-00 +0000,wsj,EU Accepts Sanofi’s Concessions to End Antitru...,https://www.wsj.com/business/eu-accepts-sanofi...
1,2026-10-14-08-55-00 +0000,wsj,Swisscom Wins Appeal Against Swiss Antitrust F...,https://www.wsj.com/business/telecom/swisscom-...
2,2026-10-14-08-53-40 +0000,bbc,Pope diagnosed with lung cancer but had succes...,https://www.bbc.co.uk/news/articles/ck1wvd9dvv...
3,2026-10-14-08-50-39 +0000,cbc,"Saudi Aramco administrative building attacked,...",https://www.cbc.ca/news/world/saudi-arabia-ara...
4,2026-10-14-08-48-42 +0000,cbc,"Russian strikes kill 3 in Ukraine, damage doze...",https://www.cbc.ca/news/world/russia-attacks-u...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2397/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
139      trump     43
95          ai     20
253        new     17
670   kimberly     15
671  guilfoyle     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,161
345,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,135
314,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,123
165,2026-10-13-21-54-45 +0000,nypost,Trump personally prepped Katie Zacharia for fi...,https://nypost.com/2026/10/13/us-news/trump-pe...,118
299,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,161,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
191,100,2026-10-13-21-13-00 +0000,wsj,Kimberly Guilfoyle resigned as the U.S. ambass...,https://www.wsj.com/politics/policy/kimberly-g...
90,86,2026-10-14-02-17-29 +0000,nypost,Six Flags’ ‘Goliath’ coaster rider who fell to...,https://nypost.com/2026/10/13/us-news/six-flag...
176,80,2026-10-13-21-34-51 +0000,latimes,Disney strikes $20-million deal for Character....,https://www.latimes.com/business/story/2026-10...
131,71,2026-10-13-23-21-01 +0000,nypost,Ilhan Omar’s husband spotted for first time si...,https://nypost.com/2026/10/13/us-news/ilhan-om...
87,61,2026-10-14-02-31-00 +0000,wsj,Georgia’s Democratic senator Jon Ossoff says h...,https://www.wsj.com/politics/elections/jon-oss...
314,58,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...
34,57,2026-10-14-07-22-00 +0000,wsj,Oil Prices Rise as Traders Weigh Saudi Aramco ...,https://www.wsj.com/business/energy-oil/oil-pr...
394,56,2026-10-13-11-12-24 +0000,chitri,Vatican says Pope Leo XIV has lung cancer and ...,https://www.chicagotribune.com/2026/10/13/pope...
55,46,2026-10-14-05-01-09 +0000,nypost,Texas man finds live World War II grenades in ...,https://nypost.com/2026/10/14/us-news/live-wor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)