## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-22-13-00 +0000,nypost,Bosses of canoodling Central Park lawyers were...,https://nypost.com/2026/07/30/us-news/bosses-o...
1,2026-07-30-22-12-45 +0000,nypost,"Apple revenue, profits beat expectations on iP...",https://nypost.com/2026/07/30/business/apple-r...
2,2026-07-30-22-08-48 +0000,nyt,A.I. Hedge Fund Situational Awareness Rescued ...,https://www.nytimes.com/2026/07/30/business/ar...
3,2026-07-30-22-08-35 +0000,nyt,Was Your Trip to Europe Affected by Heat or Wi...,https://www.nytimes.com/2026/07/30/travel/euro...
4,2026-07-30-22-08-34 +0000,nyt,Two More Appeals Courts Rule Against Trump Det...,https://www.nytimes.com/2026/07/30/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2315/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
46    trump     35
170    iran     22
238     new     18
171     war     16
72   attack     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...,149
369,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,105
353,2026-07-30-02-10-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...,102
140,2026-07-30-17-55-06 +0000,chitri,President Donald Trump floats pulling Todd Bla...,https://www.chicagotribune.com/2026/07/30/trum...,84
351,2026-07-30-02-28-39 +0000,nyt,"U.S. Strikes Iran Again, as Trump Encounters a...",https://www.nytimes.com/2026/07/29/us/trump-ir...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,149,2026-07-30-20-17-00 +0000,wsj,President Trump signaled he had no plans to ne...,https://www.wsj.com/politics/policy/trump-thre...
369,94,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
240,54,2026-07-30-13-15-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
317,53,2026-07-30-09-00-00 +0000,wsj,Capital Account: Fed Chairman Kevin Warsh says...,https://www.wsj.com/economy/central-banking/th...
75,51,2026-07-30-20-41-52 +0000,startribune,New allegations of inappropriate behavior surf...,https://www.startribune.com/st-paul-mayor-her-...
116,50,2026-07-30-18-41-32 +0000,nypost,Meta shares tumble 9% in record losing streak ...,https://nypost.com/2026/07/30/business/metas-r...
195,49,2026-07-30-16-00-00 +0000,wsj,Mortgage rates jumped to their highest level i...,https://www.wsj.com/economy/housing/mortgage-r...
272,45,2026-07-30-11-09-00 +0000,wsj,What Anthony Fauci’s refusal to answer Senate ...,https://www.wsj.com/politics/what-fauci-pleadi...
265,42,2026-07-30-12-05-29 +0000,bbc,Jenrick urges Burnham to rule out tax rises to...,https://www.bbc.co.uk/news/articles/cx2mj4768k...
204,40,2026-07-30-15-20-19 +0000,bbc,At least five members of same family killed in...,https://www.bbc.co.uk/news/articles/cy8mk59l5j...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)