## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-14-16-46 +0000,nypost,Nancy Pelosi’s post-Congress job revealed: ‘Li...,https://nypost.com/2026/06/29/us-news/former-h...
1,2026-06-29-14-10-45 +0000,bbc,DR Congo bans mass gatherings in the capital ...,https://www.bbc.co.uk/news/articles/c992k7zk98...
2,2026-06-29-14-10-00 +0000,wsj,Supreme Court Lets States Count Mailed Ballots...,https://www.wsj.com/us-news/law/supreme-court-...
3,2026-06-29-14-09-52 +0000,nypost,Supreme Court refuses to review E. Jean Carrol...,https://nypost.com/2026/06/29/us-news/supreme-...
4,2026-06-29-14-09-47 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/29/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
59        iran     15
35       trump     13
167         he     12
424  venezuela     11
17       court      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-06-29-13-46-31 +0000,latimes,Supreme Court refuses Trump's appeal of E. Jea...,https://www.latimes.com/politics/story/2026-06...,59
22,2026-06-29-13-43-17 +0000,nyt,Supreme Court Rejects Trump’s Request to Appea...,https://www.nytimes.com/2026/06/29/us/politics...,58
10,2026-06-29-14-04-24 +0000,bbc,US Supreme Court rejects Trump's appeal of E J...,https://www.bbc.co.uk/news/articles/cn8q2z5wpn...,56
6,2026-06-29-14-09-00 +0000,wsj,Supreme Court Won’t Hear Trump Appeal of E. Je...,https://www.wsj.com/us-news/law/supreme-court-...,56
3,2026-06-29-14-09-52 +0000,nypost,Supreme Court refuses to review E. Jean Carrol...,https://nypost.com/2026/06/29/us-news/supreme-...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,59,2026-06-29-13-46-31 +0000,latimes,Supreme Court refuses Trump's appeal of E. Jea...,https://www.latimes.com/politics/story/2026-06...
190,51,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...
229,46,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...
241,42,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...
130,38,2026-06-29-09-00-00 +0000,wsj,"The University of California, Berkeley plans t...",https://www.wsj.com/us-news/education/nancy-pe...
112,33,2026-06-29-10-00-00 +0000,startribune,Officials tried to protect a baby girl born at...,https://www.startribune.com/officials-tried-to...
247,33,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
41,32,2026-06-29-12-56-49 +0000,nyt,"Andy Burnham, the UK’s Likely Next Prime Minis...",https://www.nytimes.com/2026/06/29/world/europ...
13,31,2026-06-29-13-52-19 +0000,nypost,Nearly half of Maine voters say Graham Platner...,https://nypost.com/2026/06/29/us-news/nearly-h...
226,29,2026-06-28-17-41-33 +0000,nyt,Dozens of Dogs Join Search for Venezuela Earth...,https://www.nytimes.com/2026/06/28/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)