## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-07-13-16 +0000,nyt,Kuwaiti Tanker Full of Oil Struck Off Dubai Da...,https://www.nytimes.com/live/2026/03/30/world/...
1,2026-03-31-07-12-41 +0000,bbc,Sexual violence part of 'everyday life' in par...,https://www.bbc.com/news/articles/c5ywgn2n3nqo...
2,2026-03-31-07-09-00 +0000,wsj,Rheinmetall and Boeing Australia to Supply Com...,https://www.wsj.com/business/deals/rheinmetall...
3,2026-03-31-07-09-00 +0000,wsj,Oil Ticks Higher After Trump Tells Aides He’s ...,https://www.wsj.com/finance/commodities-future...
4,2026-03-31-07-07-11 +0000,nyt,When Will Japan’s Cherry Blossoms Bloom? A.I. ...,https://www.nytimes.com/2026/03/31/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
8     trump     43
223    iran     39
33      war     23
3       oil     22
367  energy     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...,149
267,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...,146
340,2026-03-30-08-59-18 +0000,cbc,Trump threatens to seize Kharg Island oil term...,https://www.cbc.ca/news/world/iran-us-troops-i...,141
26,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...,129
3,2026-03-31-07-09-00 +0000,wsj,Oil Ticks Higher After Trump Tells Aides He’s ...,https://www.wsj.com/finance/commodities-future...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,149,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...
26,86,2026-03-31-04-03-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
3,63,2026-03-31-07-09-00 +0000,wsj,Oil Ticks Higher After Trump Tells Aides He’s ...,https://www.wsj.com/finance/commodities-future...
261,52,2026-03-30-15-15-36 +0000,nyt,Analysis shows where a new U.S. missile hit an...,https://www.nytimes.com/live/2026/world/us-isr...
30,44,2026-03-31-03-35-08 +0000,startribune,When will Vikings hire a GM? Mark Wilf says pr...,https://www.startribune.com/when-will-vikings-...
134,37,2026-03-30-21-11-37 +0000,bbc,Palestinians convicted of deadly attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
146,36,2026-03-30-20-56-45 +0000,cbc,Human rights group says at least 70 killed in ...,https://www.cbc.ca/news/world/haiti-massacre-a...
187,35,2026-03-30-19-12-56 +0000,nypost,Eric Swalwell insists Chinese spy case ‘is clo...,https://nypost.com/2026/03/30/us-news/eric-swa...
254,33,2026-03-30-15-34-02 +0000,nypost,"Thieves snatch $10M worth of Renoir, Cézanne a...",https://nypost.com/2026/03/30/world-news/thiev...
163,32,2026-03-30-20-18-59 +0000,nypost,Fed’s Powell says no need to hike interest rat...,https://nypost.com/2026/03/30/business/feds-po...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)