## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-14-18-23-38 +0000,nypost,Long Island school pays student $125K after th...,https://nypost.com/2026/05/14/us-news/long-isl...
1,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
2,2026-05-14-18-23-00 +0000,wsj,Crypto Industry Notches Win in Washington Afte...,https://www.wsj.com/politics/policy/crypto-ind...
3,2026-05-14-18-18-32 +0000,nyt,Wes Streeting Resigns and Calls for Leadership...,https://www.nytimes.com/2026/05/14/world/europ...
4,2026-05-14-18-18-28 +0000,nyt,"After Xi’s Warning on Taiwan, He and Trump Str...",https://www.nytimes.com/live/2026/05/13/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2575/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
43   trump     68
194  china     37
39      xi     27
75     new     26
165    war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...,193
253,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...,178
213,2026-05-14-10-47-10 +0000,nypost,Trump sets date for Xi Jinping White House vis...,https://nypost.com/2026/05/14/us-news/trump-in...,172
271,2026-05-14-04-40-36 +0000,nypost,Xi raises prospect of a future US-China war in...,https://nypost.com/2026/05/14/us-news/xi-raise...,166
79,2026-05-14-16-17-32 +0000,nypost,Xi Jinping said China ‘would love to be a help...,https://nypost.com/2026/05/14/us-news/xi-jinpi...,163

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,193,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...
362,127,2026-05-13-21-29-00 +0000,wsj,"Kevin Warsh is officially the new Fed chair, t...",https://www.wsj.com/politics/policy/warsh-conf...
253,73,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...
327,58,2026-05-13-23-03-15 +0000,bbc,Warning higher Europe air fares 'inevitable' d...,https://www.bbc.com/news/articles/clyprnelzxzo...
344,47,2026-05-13-22-29-26 +0000,latimes,Vance says $1.3 billion in Medicaid payments t...,https://www.latimes.com/california/story/2026-...
39,45,2026-05-14-17-16-45 +0000,nyt,"Cerebras, A.I. Chip Maker, Rises 89% in Market...",https://www.nytimes.com/2026/05/14/technology/...
221,43,2026-05-14-10-00-00 +0000,latimes,Another Californian was exposed to hantavirus ...,https://www.latimes.com/california/story/2026-...
66,39,2026-05-14-16-28-09 +0000,nypost,Gavin Newsom’s ex-aide Dana Williamson pleads ...,https://nypost.com/2026/05/14/us-news/gavin-ne...
331,39,2026-05-13-23-00-36 +0000,bbc,Alberta judge tosses out petition for province...,https://www.bbc.com/news/articles/clypn8py4zwo...
18,39,2026-05-14-17-52-46 +0000,nyt,Iran Lets Chinese Ships Through Strait of Horm...,https://www.nytimes.com/2026/05/14/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)