## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-09-03-20 +0000,nyt,Why This Jump in Gas Prices Feels Different,https://www.nytimes.com/2026/03/18/upshot/gas-...
1,2026-03-18-09-03-15 +0000,nyt,Trump’s Pick for Homeland Security Secretary t...,https://www.nytimes.com/2026/03/18/us/politics...
2,2026-03-18-09-02-19 +0000,nyt,Intelligence Officials to Face Questions on Iran,https://www.nytimes.com/2026/03/18/us/politics...
3,2026-03-18-09-02-14 +0000,nyt,California Heat Wave Makes Winter Feel Like Su...,https://www.nytimes.com/2026/03/18/us/californ...
4,2026-03-18-09-02-04 +0000,nyt,What to Watch at the Federal Reserve’s March M...,https://www.nytimes.com/2026/03/18/business/fe...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2662/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
14       iran     50
5       trump     48
47        war     32
174  illinois     18
468       top     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
154,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,197
339,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,189
99,2026-03-18-02-12-16 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,176
128,2026-03-18-01-00-00 +0000,wsj,"The resignation of Joe Kent, the Trump adminis...",https://www.wsj.com/politics/national-security...,160
223,2026-03-17-20-41-00 +0000,wsj,"The top U.S. counterterrorism official, Joe Ke...",https://www.wsj.com/politics/national-security...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
154,197,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...
93,89,2026-03-18-02-44-31 +0000,nypost,Lt. Gov. Juliana Stratton wins Illinois Senate...,https://nypost.com/2026/03/17/us-news/juliana-...
164,63,2026-03-17-22-49-03 +0000,bbc,Iranian security chief Ali Larijani killed in ...,https://www.bbc.com/news/articles/c24deezq6meo...
323,55,2026-03-17-15-07-00 +0000,wsj,President Trump has made tightening voter-elig...,https://www.wsj.com/politics/policy/what-is-sa...
60,54,2026-03-18-05-27-39 +0000,nypost,Comedy club owner with terminal cancer guns do...,https://nypost.com/2026/03/18/us-news/alaska-c...
38,49,2026-03-18-07-46-00 +0000,wsj,Oil Falls as Iraq Strikes Oil Exports Deal But...,https://www.wsj.com/finance/commodities-future...
98,49,2026-03-18-02-16-40 +0000,latimes,SoCal school psychologist thought he was meeti...,https://www.latimes.com/california/story/2026-...
117,48,2026-03-18-01-23-03 +0000,nypost,GOP senator pitches plan to slash California’s...,https://nypost.com/2026/03/17/us-news/gop-sena...
321,43,2026-03-17-15-15-02 +0000,nypost,"Amazon launches 1-hour, 3-hour delivery option...",https://nypost.com/2026/03/17/business/amazon-...
226,43,2026-03-17-20-22-51 +0000,startribune,"Walz pitches child care tax credit, new social...",https://www.startribune.com/walz-pitches-child...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)