## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-12-00-00 +0000,wsj,OpenAI Taps Former Meta Executive to Lead Ad Push,https://www.wsj.com/tech/ai/openai-taps-former...
1,2026-03-23-11-58-04 +0000,bbc,Starmer to consider options over Iran cost-of-...,https://www.bbc.com/news/articles/c98kdyye33no...
2,2026-03-23-11-57-00 +0000,wsj,Protein Drink Maker Huel Agrees to $1.2 Billio...,https://www.wsj.com/business/danone-to-buy-nut...
3,2026-03-23-11-56-20 +0000,nyt,Iran War Live Updates: Trump Says U.S. and Ira...,https://www.nytimes.com/live/2026/03/23/world/...
4,2026-03-23-11-54-14 +0000,bbc,Oil prices plunge after Trump says talks have ...,https://www.bbc.com/news/articles/czex56kwxxzo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2611/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
26  trump     37
11   iran     34
23    war     18
58    new     15
84  power     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-03-23-11-56-20 +0000,nyt,Iran War Live Updates: Trump Says U.S. and Ira...,https://www.nytimes.com/live/2026/03/23/world/...,140
118,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...,128
197,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,126
11,2026-03-23-11-45-03 +0000,startribune,US will hold off on Iran power plant strikes f...,https://www.startribune.com/iran-threatens-to-...,121
19,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,140,2026-03-23-11-56-20 +0000,nyt,Iran War Live Updates: Trump Says U.S. and Ira...,https://www.nytimes.com/live/2026/03/23/world/...
115,71,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
39,69,2026-03-23-10-27-13 +0000,cbc,Israel launches new wave of attacks on Tehran;...,https://www.cbc.ca/news/world/israel-new-attac...
101,65,2026-03-23-04-47-20 +0000,nypost,"Two pilots dead, 41 people hospitalized after ...",https://nypost.com/2026/03/23/us-news/air-cana...
248,44,2026-03-22-12-52-56 +0000,bbc,Energy bills rise 'inescapable' if oil prices ...,https://www.bbc.com/news/articles/c77mx575k4vo...
237,36,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
118,34,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...
152,34,2026-03-22-23-49-25 +0000,nypost,California military families react as soldiers...,https://nypost.com/2026/03/22/us-news/socal-mi...
249,33,2026-03-22-12-52-00 +0000,wsj,South Korean President Lee Jae Myung has nomin...,https://www.wsj.com/economy/central-banking/so...
245,31,2026-03-22-14-00-00 +0000,wsj,Small truck drivers in the U.S. are feeling so...,https://www.wsj.com/economy/truckers-are-the-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)