## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-09-08-53-45 +0000,nyt,"Before Oct. 7 Attack, Netanyahu Was Warned, Re...",https://www.nytimes.com/2026/09/08/world/middl...
1,2026-09-09-08-50-02 +0000,bbc,Learner drivers still waiting 20 weeks to book...,https://www.bbc.co.uk/news/articles/cx2z421xe0...
2,2026-09-09-08-44-00 +0000,wsj,Nordic Energy Company Fortum Shares Jump on Go...,https://www.wsj.com/business/energy-oil/nordic...
3,2026-09-09-08-42-36 +0000,bbc,Oil hits $100 a barrel for first time since Ju...,https://www.bbc.co.uk/news/articles/cyvznqypz0...
4,2026-09-09-08-39-18 +0000,nyt,Iran Signals Readiness to Escalate War With U....,https://www.nytimes.com/2026/09/09/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
357    trump     50
66       new     30
25       oil     25
69    canada     20
568  tariffs     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
113,2026-09-09-00-53-50 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,129
168,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...,125
123,2026-09-09-00-10-38 +0000,nyt,"Anthony DiLorenzo, a Trump-Backed Auto Executi...",https://www.nytimes.com/2026/09/08/us/politics...,118
72,2026-09-09-02-51-00 +0000,wsj,President Trump signed orders to ban the impor...,https://www.wsj.com/economy/trade/trump-says-h...,116
171,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
113,129,2026-09-09-00-53-50 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...
171,115,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
99,79,2026-09-09-01-28-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
317,76,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...
127,60,2026-09-08-23-42-00 +0000,wsj,The Supreme Court rejected Missouri’s bid to u...,https://www.wsj.com/politics/policy/supreme-co...
0,56,2026-09-09-08-53-45 +0000,nyt,"Before Oct. 7 Attack, Netanyahu Was Warned, Re...",https://www.nytimes.com/2026/09/08/world/middl...
204,52,2026-09-08-20-46-58 +0000,nypost,California union threatens strike in war over ...,https://nypost.com/2026/09/08/us-news/californ...
41,51,2026-09-09-05-55-01 +0000,nypost,Data shows Amazon jet’s key braking systems di...,https://nypost.com/2026/09/09/us-news/data-sho...
407,45,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
397,44,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)