## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-10-03-07 +0000,nyt,It Was the Vatican’s ‘Trial of the Century.’ N...,https://www.nytimes.com/2026/03/17/world/europ...
1,2026-03-18-10-00-00 +0000,wsj,"Body Scrub, Concealer and Shoe Trinkets Star i...",https://www.wsj.com/cmo-today/body-scrub-conce...
2,2026-03-18-10-00-00 +0000,wapo,How lawyers got their hands on thousands of pr...,https://www.washingtonpost.com/health/2026/03/...
3,2026-03-18-10-00-00 +0000,nypost,Prenuvo CEO bets he can save lives and major h...,https://nypost.com/2026/03/18/business/prenuvo...
4,2026-03-18-10-00-00 +0000,nypost,Storm tears open historic Rye Playland music t...,https://nypost.com/2026/03/18/us-news/storm-te...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
94       iran     51
44      trump     46
237       war     30
67   illinois     18
153       top     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,194
352,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,186
117,2026-03-18-02-12-16 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,173
144,2026-03-18-01-00-00 +0000,wsj,"The resignation of Joe Kent, the Trump adminis...",https://www.wsj.com/politics/national-security...,156
237,2026-03-17-20-41-00 +0000,wsj,"The top U.S. counterterrorism official, Joe Ke...",https://www.wsj.com/politics/national-security...,153

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,194,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...
111,88,2026-03-18-02-44-31 +0000,nypost,Lt. Gov. Juliana Stratton wins Illinois Senate...,https://nypost.com/2026/03/17/us-news/juliana-...
180,65,2026-03-17-22-49-03 +0000,bbc,Iranian security chief Ali Larijani killed in ...,https://www.bbc.com/news/articles/c24deezq6meo...
336,57,2026-03-17-15-07-00 +0000,wsj,President Trump has made tightening voter-elig...,https://www.wsj.com/politics/policy/what-is-sa...
262,54,2026-03-17-19-14-20 +0000,nyt,"Flight Prices Are Up Amid Soaring Fuel Costs, ...",https://www.nytimes.com/2026/03/17/business/ai...
116,51,2026-03-18-02-16-40 +0000,latimes,SoCal school psychologist thought he was meeti...,https://www.latimes.com/california/story/2026-...
60,50,2026-03-18-07-46-00 +0000,wsj,Oil Falls as Iraq Strikes Oil Exports Deal But...,https://www.wsj.com/finance/commodities-future...
358,48,2026-03-17-13-54-55 +0000,nypost,"Iran’s brutal anti-protest enforcer is dead, I...",https://nypost.com/2026/03/17/world-news/irans...
5,43,2026-03-18-10-00-00 +0000,nypost,"Trump will ‘rebalance’ media, FCC boss Brendan...",https://nypost.com/2026/03/18/us-news/fcc-boss...
133,37,2026-03-18-01-23-03 +0000,nypost,GOP senator pitches plan to slash California’s...,https://nypost.com/2026/03/17/us-news/gop-sena...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)