## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-23-00-00 +0000,wsj,This Billionaire Became China’s Charles Schwab...,https://www.wsj.com/world/china/this-billionai...
1,2026-08-09-22-50-00 +0000,wsj,Trump Names Will Scharf as New White House Cou...,https://www.wsj.com/politics/policy/trump-name...
2,2026-08-09-22-44-58 +0000,nypost,AG Letitia James steers $54M in taxpayer funds...,https://nypost.com/2026/08/09/us-news/ag-letit...
3,2026-08-09-22-38-47 +0000,nypost,Democrats let down majority black NY city as p...,https://nypost.com/2026/08/09/us-news/democrat...
4,2026-08-09-22-35-19 +0000,nypost,NY police arrest ‘armed and dangerous’ fugitiv...,https://nypost.com/2026/08/09/us-news/ny-polic...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
8     trump     19
81       el      8
78   senate      8
108    plan      8
161  israel      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...,62
108,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...,57
10,2026-08-09-22-07-40 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,54
22,2026-08-09-21-25-04 +0000,bbc,"Israel rejects Trump's 15-point plan for Gaza,...",https://www.bbc.co.uk/news/articles/c5yw4lpe0y...,54
55,2026-08-09-18-58-00 +0000,wsj,Israel Rejects Next Phase of Trump’s Gaza Peac...,https://www.wsj.com/world/middle-east/israel-r...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,62,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...
9,39,2026-08-09-22-10-00 +0000,wsj,Former President Joe Biden’s cancer has spread...,https://www.wsj.com/politics/hunter-bidens-com...
108,38,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...
3,28,2026-08-09-22-38-47 +0000,nypost,Democrats let down majority black NY city as p...,https://nypost.com/2026/08/09/us-news/democrat...
2,26,2026-08-09-22-44-58 +0000,nypost,AG Letitia James steers $54M in taxpayer funds...,https://nypost.com/2026/08/09/us-news/ag-letit...
53,26,2026-08-09-19-14-55 +0000,nypost,AOC pushes voters to assess what Francesca Hon...,https://nypost.com/2026/08/09/us-news/aoc-push...
102,25,2026-08-09-14-00-00 +0000,wsj,President Trump’s endorsement of 26-year-old M...,https://www.wsj.com/politics/elections/nepotis...
82,25,2026-08-09-15-51-04 +0000,nypost,Iran-backed Houthis attack Aramco refinery in ...,https://nypost.com/2026/08/09/world-news/iran-...
38,24,2026-08-09-20-25-22 +0000,nypost,Rich kid driving souped-up McLaren goes ballis...,https://nypost.com/2026/08/09/us-news/rich-kid...
16,23,2026-08-09-21-42-34 +0000,nypost,New Orleans becomes first major US city to use...,https://nypost.com/2026/08/09/us-news/new-orle...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)