## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-01-21-04 +0000,nypost,California inks nefarious deal with Canadians ...,https://nypost.com/2026/07/08/business/califor...
1,2026-07-09-01-20-50 +0000,nyt,Iran War Live Updates: U.S. Launches New Strik...,https://www.nytimes.com/live/2026/07/08/world/...
2,2026-07-09-01-20-01 +0000,startribune,"US launches new airstrikes on Iran, with Tehra...",https://www.startribune.com/kuwait-and-bahrain...
3,2026-07-09-01-20-00 +0000,wsj,Oil Prices Rise After Fresh U.S. Attacks in th...,https://www.wsj.com/finance/oil-prices-rise-af...
4,2026-07-09-01-19-18 +0000,nypost,Who is Valli Geiger? Meet the Maine Dem in lin...,https://nypost.com/2026/07/08/us-news/who-is-v...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
56    trump     57
10     iran     44
77     nato     22
15      new     17
16  strikes     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” Trump said of the ...",https://www.wsj.com/world/middle-east/inside-t...,170
313,2026-07-08-11-27-45 +0000,cbc,Carney backs latest U.S. strikes on Iran as Tr...,https://www.cbc.ca/news/politics/iran-war-us-c...,160
43,2026-07-08-23-48-00 +0000,wsj,U.S. Launches New Strikes on Iran After Trump ...,https://www.wsj.com/world/middle-east/u-s-laun...,155
199,2026-07-08-17-27-18 +0000,nypost,"Trump ditches new Air Force One in Turkey, sto...",https://nypost.com/2026/07/08/us-news/trump-wo...,153
277,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...,147

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,170,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” Trump said of the ...",https://www.wsj.com/world/middle-east/inside-t...
277,147,2026-07-08-14-13-00 +0000,wsj,Democrats are rushing to find a candidate to r...,https://www.wsj.com/politics/elections/graham-...
154,59,2026-07-08-19-26-00 +0000,wsj,Fed officials weighed rate hikes last month as...,https://www.wsj.com/economy/central-banking/fe...
49,58,2026-07-08-23-22-03 +0000,nypost,"Judge, mom of friend explains why Nolan Wells ...",https://nypost.com/2026/07/08/us-news/judge-mo...
279,48,2026-07-08-14-11-00 +0000,wsj,ADP to Launch Monthly Pay Tracking Indicator i...,https://www.wsj.com/economy/jobs/adp-to-launch...
363,47,2026-07-08-05-05-31 +0000,bbc,Russian fuel shortages bite – but will Putin c...,https://www.bbc.co.uk/news/articles/cr7xk8j0j2...
110,44,2026-07-08-20-58-21 +0000,bbc,"Justin Bieber joins Madonna, Shakira and BTS f...",https://www.bbc.co.uk/news/articles/c1wyx7g9e1...
137,42,2026-07-08-19-56-54 +0000,nypost,California approves ‘largest tax hike in histo...,https://nypost.com/2026/07/08/business/califor...
236,41,2026-07-08-15-56-49 +0000,cbc,Massive crowds move through Iran and Iraq for ...,https://www.cbc.ca/news/world/ayatollah-ali-kh...
79,40,2026-07-08-22-09-12 +0000,nypost,United Airlines must face lawsuit after allege...,https://nypost.com/2026/07/08/business/united-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)