## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-25-00-15-08 +0000,nyt,Venezuela Hit by 7.1-Magnitude Earthquake,https://www.nytimes.com/live/2026/06/24/world/...
1,2026-06-25-00-07-31 +0000,nypost,Quantum computers will supercharge the world —...,https://nypost.com/2026/06/24/us-news/quantum-...
2,2026-06-25-00-05-44 +0000,nyt,Dolly Parton’s Fans Were Worried. She Came to ...,https://www.nytimes.com/2026/06/24/us/dolly-pa...
3,2026-06-25-00-05-00 +0000,wsj,Things Are Getting Awkward in England as Roads...,https://www.wsj.com/lifestyle/things-are-getti...
4,2026-06-25-00-03-06 +0000,nyt,"In New York Election Results, More Evidence of...",https://www.nytimes.com/2026/06/24/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     41
146   iran     28
32     new     23
8    world     20
524    cup     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
107,2026-06-24-20-25-00 +0000,wsj,Tuesday’s primary results make clear that New ...,https://www.wsj.com/politics/elections/mamdani...,127
224,2026-06-24-14-57-21 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...,115
135,2026-06-24-18-57-41 +0000,nypost,Trump gets into shouting match with Sen. Bill ...,https://nypost.com/2026/06/24/us-news/trump-ge...,114
87,2026-06-24-21-22-00 +0000,bbc,"Congress has told Trump to stop the Iran war, ...",https://www.bbc.co.uk/news/videos/cx24793rx4lo...,111
339,2026-06-24-03-22-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/national-security...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
107,127,2026-06-24-20-25-00 +0000,wsj,Tuesday’s primary results make clear that New ...,https://www.wsj.com/politics/elections/mamdani...
224,115,2026-06-24-14-57-21 +0000,bbc,Congress passes war powers measure for first t...,https://www.bbc.co.uk/news/articles/ce8j6g3v3r...
109,85,2026-06-24-20-21-38 +0000,cbc,"While focus remains on men's World Cup, clock ...",https://www.cbc.ca/sports/soccer/worldcup/worl...
41,65,2026-06-24-22-34-00 +0000,wsj,President Trump abruptly canceled plans to sig...,https://www.wsj.com/politics/policy/trump-abru...
171,50,2026-06-24-17-17-17 +0000,nypost,Oil prices drop near $70 a barrel — lowest lev...,https://nypost.com/2026/06/24/business/oil-pri...
99,46,2026-06-24-20-44-53 +0000,nyt,Europe Heat Wave Latest News: After France’s H...,https://www.nytimes.com/2026/06/24/weather/eur...
257,45,2026-06-24-13-24-00 +0000,wsj,Zohran Mamdani’s allies notched key wins in Ne...,https://www.wsj.com/politics/elections/key-tak...
10,41,2026-06-24-23-59-47 +0000,latimes,Teen falls 50 feet on Disneyland ride with no ...,https://www.latimes.com/california/story/2026-...
45,39,2026-06-24-22-31-00 +0000,wsj,The Pentagon awarded Lockheed Martin a contrac...,https://www.wsj.com/politics/national-security...
339,36,2026-06-24-03-22-00 +0000,wsj,The Senate voted to limit President Trump’s ab...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)