## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-01-13-24 +0000,nypost,Trump rejects Iran’s seven-day cease-fire prop...,https://nypost.com/2026/09/25/us-news/trump-re...
1,2026-09-26-01-08-22 +0000,nyt,Mississippi Hanging Was Staged After Drug Disp...,https://www.nytimes.com/2026/09/25/us/mississi...
2,2026-09-26-01-06-25 +0000,nypost,LA County sales tax increase goes into effect ...,https://nypost.com/2026/09/25/us-news/la-count...
3,2026-09-26-01-05-34 +0000,nyt,Trump Proposes $810 Million in Education and H...,https://www.nytimes.com/2026/09/25/us/politics...
4,2026-09-26-01-05-09 +0000,nyt,A Fatal Stabbing Leaves a Quiet Neighborhood E...,https://www.nytimes.com/2026/09/25/us/pittsbur...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     74
133     xi     29
8      new     27
92   court     21
212  house     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
197,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,178
179,2026-09-25-18-26-18 +0000,nypost,White House plays ‘Les Miserables’ hit censore...,https://nypost.com/2026/09/25/us-news/white-ho...,169
225,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...,161
397,2026-09-25-02-16-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...,156
132,2026-09-25-20-02-20 +0000,nypost,Trump told China’s Xi that support for Iran wa...,https://nypost.com/2026/09/25/us-news/trump-to...,154

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
197,178,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...
225,87,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...
0,78,2026-09-26-01-13-24 +0000,nypost,Trump rejects Iran’s seven-day cease-fire prop...,https://nypost.com/2026/09/25/us-news/trump-re...
85,59,2026-09-25-21-16-59 +0000,bbc,Black woman found hanging from tree was dead b...,https://www.bbc.co.uk/news/articles/cwp933nzpp...
362,58,2026-09-25-08-52-23 +0000,wsj,"Stock Market News, Sept. 25, 2026: Bond Yields...",https://www.wsj.com/livecoverage/stock-market-...
296,49,2026-09-25-12-40-02 +0000,chitri,Pope Leo XIV warns a ‘paradise of machines’ co...,https://www.chicagotribune.com/2026/09/25/pope...
175,46,2026-09-25-18-36-09 +0000,nypost,Costco to land in yet another California city ...,https://nypost.com/2026/09/25/business/new-nor...
343,43,2026-09-25-09-30-00 +0000,wsj,Cracks in Oracle’s AI Data-Center Build-Out Ap...,https://www.wsj.com/finance/investing/cracks-i...
350,43,2026-09-25-09-14-34 +0000,nypost,Miss Jamaica sues Miss Universe after brutal s...,https://nypost.com/2026/09/25/world-news/miss-...
142,43,2026-09-25-19-36-38 +0000,nyt,"South Carolinians: Do You Have a Short-Term, H...",https://www.nytimes.com/2026/09/25/us/south-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)