## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
1,2026-07-26-16-10-07 +0000,nyt,Employers Fear Labor Shortage as Many Immigran...,https://www.nytimes.com/2026/07/26/us/trump-tp...
2,2026-07-26-16-06-31 +0000,nypost,Top NYT journo calls on reporters to ‘rethink’...,https://nypost.com/2026/07/26/us-news/top-nyt-...
3,2026-07-26-16-03-50 +0000,nyt,Live Updates: Extreme Heat and Strong Winds Fu...,https://www.nytimes.com/live/2026/07/26/world/...
4,2026-07-26-16-03-46 +0000,nyt,Wildfire Smoke Chokes Skies in Spain and France,https://www.nytimes.com/2026/07/25/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2336/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     20
106  attack     11
3      iran     11
107  berlin     10
207  senate      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
32,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,59
0,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,57
148,2026-07-25-19-40-41 +0000,nypost,Trump pauses Iran strikes as US weighs next mo...,https://nypost.com/2026/07/25/world-news/trump...,55
12,2026-07-26-15-17-33 +0000,chitri,German police hunt suspect in attack near Berl...,https://www.chicagotribune.com/2026/07/26/berl...,50
42,2026-07-26-13-08-59 +0000,cbc,Fatal Berlin Pride attack believed to be an ac...,https://www.cbc.ca/news/world/berlin-pride-att...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
32,59,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...
12,50,2026-07-26-15-17-33 +0000,chitri,German police hunt suspect in attack near Berl...,https://www.chicagotribune.com/2026/07/26/berl...
166,42,2026-07-25-17-10-00 +0000,wsj,Maine Democrats choose Troy Jackson to replace...,https://www.wsj.com/politics/maine-democrats-c...
3,33,2026-07-26-16-03-50 +0000,nyt,Live Updates: Extreme Heat and Strong Winds Fu...,https://www.nytimes.com/live/2026/07/26/world/...
44,27,2026-07-26-12-41-43 +0000,nypost,"Cop’s son, 12, ID’d after being shot dead in N...",https://nypost.com/2026/07/26/us-news/jacob-fr...
36,26,2026-07-26-13-39-20 +0000,nypost,Fetterman perplexed why he’s so popular with G...,https://nypost.com/2026/07/26/us-news/fetterma...
171,26,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...
61,23,2026-07-26-10-00-00 +0000,wsj,A documentary filmmaker followed Sen. Lindsey ...,https://www.wsj.com/politics/national-security...
7,22,2026-07-26-15-48-19 +0000,nypost,Businessman suffers horrific injuries after to...,https://nypost.com/2026/07/26/us-news/business...
135,22,2026-07-25-21-01-25 +0000,nypost,"Ukraine strikes set fire to ‘Russia’s Amazon,’...",https://nypost.com/2026/07/25/world-news/ukrai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)