## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-11-07-11-00 +0000,wsj,Intel Increases Size of Stock Offering to Rais...,https://www.wsj.com/tech/intel-increases-size-...
1,2026-08-11-07-08-00 +0000,wsj,"Gold Set to Rebound Further Toward $4,500 an O...",https://www.wsj.com/articles/gold-price-could-...
2,2026-08-11-07-05-03 +0000,bbc,Watch: Huge blaze after attack on petrol tank ...,https://www.bbc.co.uk/news/videos/c8xn7d2zy75o...
3,2026-08-11-07-04-00 +0000,wsj,Eurozone Bond Yields Climb as Middle East Conf...,https://www.wsj.com/articles/treasury-yields-r...
4,2026-08-11-07-00-00 +0000,wsj,"Treasury Yields Rise, Dollar Steady as Iran Wa...",https://www.wsj.com/articles/yen-strengthens-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2616/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
38      trump     44
173       new     22
34       iran     16
179  colombia     14
508      race     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
228,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...,111
31,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,99
201,2026-08-10-18-14-49 +0000,nypost,Iran’s ‘misery’ index hits record high — and a...,https://nypost.com/2026/08/10/world-news/irans...,97
251,2026-08-10-15-18-29 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,95
37,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
228,111,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...
57,66,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
317,61,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...
157,46,2026-08-10-20-17-23 +0000,chitri,President Trump signs executive order calling ...,https://www.chicagotribune.com/2026/08/10/trum...
257,45,2026-08-10-14-55-02 +0000,nypost,Massive 7.4-magnitude earthquake strikes Colom...,https://nypost.com/2026/08/10/world-news/massi...
226,40,2026-08-10-16-59-59 +0000,nypost,OpenAI hits pause on new bot testing over ‘cri...,https://nypost.com/2026/08/10/business/openai-...
31,39,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
17,39,2026-08-11-04-19-38 +0000,nyt,"Jake Whisenant, Who Raced Up Yosemite’s El Cap...",https://www.nytimes.com/2026/08/11/us/jake-whi...
120,36,2026-08-10-21-41-28 +0000,nypost,DSA darling Francesca Hong doesn’t just want t...,https://nypost.com/2026/08/10/us-news/dsa-darl...
314,35,2026-08-10-10-28-24 +0000,nypost,Australian PM Anthony Albanese denies ‘melons’...,https://nypost.com/2026/08/10/world-news/austr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)