## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-14-41-59 +0000,cbc,U.S. Supreme Court rules against Trump executi...,https://www.cbc.ca/news/world/us-scotus-ruling...
1,2026-06-30-14-41-38 +0000,nypost,SoCal dad killed in massive Venezuela earthqua...,https://nypost.com/2026/06/30/us-news/southern...
2,2026-06-30-14-40-30 +0000,nyt,Mideast Live Updates: U.S. and Iran Gear Up fo...,https://www.nytimes.com/live/2026/06/30/world/...
3,2026-06-30-14-38-46 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/30/us/sup...
4,2026-06-30-14-38-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
1      court     42
0    supreme     38
4      trump     34
133      new     18
165    world     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
316,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...,179
232,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...,172
218,2026-06-29-22-18-20 +0000,nyt,Trump Renews Threat to Fire Fed Governor Lisa ...,https://www.nytimes.com/2026/06/29/us/politics...,156
334,2026-06-29-16-51-52 +0000,bbc,Supreme Court blocks Trump's attempt to fire F...,https://www.bbc.co.uk/news/articles/cy4wwy0nke...,155
259,2026-06-29-20-25-00 +0000,wsj,Supreme Court Blocks Trump From Firing Fed Gov...,https://www.wsj.com/us-news/law/supreme-court-...,150

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
316,179,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...
185,72,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
309,43,2026-06-29-18-04-54 +0000,nypost,"Witkoff, Kushner to head to Qatar for Iran tal...",https://nypost.com/2026/06/29/world-news/irani...
46,42,2026-06-30-13-30-09 +0000,nypost,Family of English soccer fan who vanished on w...,https://nypost.com/2026/06/30/world-news/fears...
232,42,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...
305,39,2026-06-29-18-16-57 +0000,bbc,New 'No 10 North' plan will rebalance power in...,https://www.bbc.co.uk/news/articles/cx2jw5q5pd...
177,35,2026-06-30-00-58-37 +0000,nypost,DOJ investigating Dem Sen. Ruben Gallego after...,https://nypost.com/2026/06/29/us-news/doj-inve...
278,32,2026-06-29-19-47-01 +0000,nypost,Woke Paris pol blames Americans and our air co...,https://nypost.com/2026/06/29/world-news/paris...
19,32,2026-06-30-14-22-00 +0000,wsj,Japanese Yen Hits New 40-Year Low Against Dollar,https://www.wsj.com/finance/currencies/yen-int...
290,31,2026-06-29-18-58-23 +0000,nypost,Man accused of killing Thai teen found in sui...,https://nypost.com/2026/06/29/world-news/man-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)