## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-17-06-55-00 +0000,wsj,Fed Policy Outlook Weighs on Yen Ahead of Bank...,https://www.wsj.com/finance/currencies/fed-pol...
1,2026-09-17-06-46-31 +0000,bbc,Abducted South African journalist found dead w...,https://www.bbc.co.uk/news/articles/c52e047wpw...
2,2026-09-17-06-46-19 +0000,bbc,Climate change likely played role in Nepal-Tib...,https://www.bbc.co.uk/news/articles/cmlyrzve5p...
3,2026-09-17-06-38-43 +0000,bbc,Tech treating AI like humans is mistaken and m...,https://www.bbc.co.uk/news/articles/c6n07ypqz8...
4,2026-09-17-06-34-00 +0000,wsj,Dollar Remains Elevated After Fed Rate Rise,https://www.wsj.com/finance/currencies/global-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2311/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
85      trump     42
0         fed     33
197       new     20
29         ai     19
43   interest     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
143,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...,198
58,2026-09-17-00-59-00 +0000,wapo,Trump says he told Fed chief to ‘do what you w...,https://www.washingtonpost.com/business/2026/0...,155
59,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...,154
240,2026-09-16-18-02-32 +0000,nypost,Fed hikes interest rates for first time in thr...,https://nypost.com/2026/09/16/business/fed-hik...,140
63,2026-09-17-00-38-50 +0000,bbc,Why Trump's hand-picked Fed chair defied him b...,https://www.bbc.co.uk/news/videos/c54g7wg1l3d3...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
143,198,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...
192,91,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
353,81,2026-09-16-11-25-05 +0000,chitri,US-Canada trade war further taxes small busine...,https://www.chicagotribune.com/2026/09/16/us-c...
142,80,2026-09-16-21-16-00 +0000,wsj,"The Fed raised rates, a top Democrat opposes a...",https://www.wsj.com/politics/policy/the-fed-is...
383,67,2026-09-16-10-00-00 +0000,latimes,"Prompted by new California and U.S. laws, two ...",https://www.latimes.com/california/story/2026-...
59,55,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...
301,48,2026-09-16-15-16-00 +0000,wsj,EU Chief Backs Canada’s Push to Become Bloc’s ...,https://www.wsj.com/world/europe/eu-chief-floa...
118,44,2026-09-16-22-06-41 +0000,chitri,Recent AI worries behind Gary mayor’s one-year...,https://www.chicagotribune.com/2026/09/16/gary...
162,43,2026-09-16-20-38-07 +0000,nyt,Senate Takes Up Bill to Regulate ‘Wild West’ o...,https://www.nytimes.com/2026/09/16/us/politics...
302,38,2026-09-16-15-15-12 +0000,nyt,Global Oil Prices Could Hit Highest Levels in ...,https://www.nytimes.com/2026/09/16/business/sa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)