## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-18-15-10 +0000,nypost,US Supreme Court lets Texas keep key GOP-boost...,https://nypost.com/2026/04/27/us-news/us-supre...
1,2026-04-27-18-13-26 +0000,bbc,Canada's Carney launches a sovereign wealth fu...,https://www.bbc.com/news/articles/c98m800r28qo...
2,2026-04-27-18-13-07 +0000,nypost,WHCD shooting suspect Cole Allen charged with ...,https://nypost.com/2026/04/27/us-news/whcd-sho...
3,2026-04-27-18-12-03 +0000,nypost,Prosecutors in Johnny Gaudreau DUI case hit ba...,https://nypost.com/2026/04/27/us-news/prosecut...
4,2026-04-27-18-10-09 +0000,startribune,Man charged with attempted assassination of Tr...,https://www.startribune.com/washington-media-d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2614/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
24      trump     34
16   shooting     23
100      iran     16
50     dinner     15
259      king     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
217,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,134
88,2026-04-27-14-43-17 +0000,nypost,Melania Trump marks quiet birthday day after ‘...,https://nypost.com/2026/04/27/us-news/melania-...,119
4,2026-04-27-18-10-09 +0000,startribune,Man charged with attempted assassination of Tr...,https://www.startribune.com/washington-media-d...,111
5,2026-04-27-18-09-42 +0000,bbc,White House to review Trump's security after s...,https://www.bbc.com/news/articles/cgj0j9439vlo...,107
256,2026-04-26-21-46-52 +0000,nypost,Witness describes the moment gunman Cole Allen...,https://nypost.com/2026/04/26/us-news/witness-...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
217,134,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
241,79,2026-04-26-23-04-26 +0000,nypost,King Charles’s royal visit to Washington still...,https://nypost.com/2026/04/26/world-news/king-...
13,65,2026-04-27-17-57-06 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
178,58,2026-04-27-09-27-55 +0000,nypost,Elon Musk and OpenAI CEO Sam Altman head to co...,https://nypost.com/2026/04/27/business/elon-mu...
92,48,2026-04-27-14-36-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
168,45,2026-04-27-10-00-00 +0000,startribune,Minnesota 12-year-old is first in new trial of...,https://www.startribune.com/minnesota-12-year-...
99,44,2026-04-27-14-01-30 +0000,nypost,Mass exodus fears as California billionaire ta...,https://nypost.com/2026/04/27/us-news/californ...
230,38,2026-04-27-00-15-40 +0000,nypost,Ex-President Barack Obama claims ‘we don’t hav...,https://nypost.com/2026/04/26/us-news/ex-presi...
3,31,2026-04-27-18-12-03 +0000,nypost,Prosecutors in Johnny Gaudreau DUI case hit ba...,https://nypost.com/2026/04/27/us-news/prosecut...
137,31,2026-04-27-11-44-00 +0000,wsj,China Bans Meta’s Acquisition of Manus on Nati...,https://www.wsj.com/world/china/china-bans-met...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)