## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-22-04-17-17 +0000,nypost,Venezuelan migrant arrested after New York tee...,https://nypost.com/2026/03/22/us-news/venezuel...
1,2026-03-22-04-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...
2,2026-03-22-04-04-47 +0000,nypost,Florida woman allegedly peed all over Airbnb r...,https://nypost.com/2026/03/22/us-news/fla-woma...
3,2026-03-22-04-01-29 +0000,nyt,Election in Slovenia Will Test Europe’s Politi...,https://www.nytimes.com/2026/03/22/world/europ...
4,2026-03-22-04-01-28 +0000,nyt,A Brussels Community Moves on From Terrorist A...,https://www.nytimes.com/2026/03/22/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
139    trump     25
14      iran     21
15       war     14
468      bts     11
18   iranian     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
106,2026-03-21-17-57-34 +0000,nypost,Trump blasts Robert Mueller after news of ex-F...,https://nypost.com/2026/03/21/us-news/trump-bl...,73
32,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...,70
97,2026-03-21-19-06-00 +0000,wsj,"Robert Mueller, Former FBI Chief Who Led Trump...",https://www.wsj.com/us-news/law/robert-mueller...,69
37,2026-03-22-00-50-15 +0000,wapo,Trump threatens to ‘obliterate’ Iran’s power p...,https://www.washingtonpost.com/world/2026/03/2...,66
1,2026-03-22-04-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
106,73,2026-03-21-17-57-34 +0000,nypost,Trump blasts Robert Mueller after news of ex-F...,https://nypost.com/2026/03/21/us-news/trump-bl...
1,66,2026-03-22-04-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...
38,41,2026-03-22-00-47-52 +0000,nypost,Over 100 Israeli civilians wounded by new Ira...,https://nypost.com/2026/03/21/world-news/over-...
130,38,2026-03-21-15-07-30 +0000,wapo,K-pop stars BTS thrill Seoul with comeback con...,https://www.washingtonpost.com/world/2026/03/2...
14,27,2026-03-22-03-09-49 +0000,nypost,Anti-police pol Eunisses Hernandez voted again...,https://nypost.com/2026/03/21/us-news/lefty-eu...
59,27,2026-03-21-22-52-35 +0000,nypost,"Unhinged Florida woman beats pregnant driver, ...",https://nypost.com/2026/03/21/us-news/florida-...
86,25,2026-03-21-19-45-18 +0000,latimes,More than half a million ballots seized by top...,https://www.latimes.com/california/story/2026-...
154,25,2026-03-21-12-00-37 +0000,wapo,These people used AI to help find their lost pets,https://www.washingtonpost.com/lifestyle/2026/...
121,24,2026-03-21-16-01-36 +0000,nypost,Trump threatens to unleash ICE agents on US ai...,https://nypost.com/2026/03/21/us-news/trump-th...
123,24,2026-03-21-16-00-00 +0000,wsj,"Even if You’re Not Driving, You’re Probably Us...",https://www.wsj.com/business/energy-oil/even-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)