## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-09-01-30 +0000,nyt,‘Absolute Nightmare’: Inside the Russian Wareh...,https://www.nytimes.com/2026/10/08/world/europ...
1,2026-10-08-09-01-00 +0000,nyt,"At a Potato Festival, Our Berlin Reporter Deep...",https://www.nytimes.com/2026/10/08/world/europ...
2,2026-10-08-09-00-50 +0000,nyt,Can Your College Affect Your Income?,https://www.nytimes.com/video/business/1000000...
3,2026-10-08-09-00-40 +0000,nyt,How the Trump Administration Is Eroding Airlin...,https://www.nytimes.com/2026/10/08/travel/airl...
4,2026-10-08-09-00-00 +0000,wapo,"War-ravaged Gaza is frozen in misery, a year i...",https://www.washingtonpost.com/world/2026/10/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20     trump     44
14       new     18
264      her     16
217     pike     15
216  christa     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
289,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...,125
199,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...,113
175,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...,105
170,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...,102
423,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
289,125,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...
175,105,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
90,73,2026-10-08-03-02-06 +0000,bbc,Texas carries out first US execution since Chr...,https://www.bbc.co.uk/news/articles/cw4g1j2z5z...
199,69,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
74,62,2026-10-08-04-22-26 +0000,nypost,LAPD makes bold new claim amid investigation i...,https://nypost.com/2026/10/08/us-news/lapd-say...
423,55,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...
424,50,2026-10-07-10-00-00 +0000,latimes,Mother is arrested in case of 14-year-old alle...,https://www.latimes.com/california/story/2026-...
170,49,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
237,48,2026-10-07-19-49-00 +0000,wsj,Oil Prices Fall Back As Supply Optimism Outwei...,https://www.wsj.com/business/energy-oil/oil-pr...
217,43,2026-10-07-20-29-00 +0000,wsj,"In a speech framed by ancient Greek ruins, Sec...",https://www.wsj.com/politics/policy/rubio-turn...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)