## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-07-45-49 +0000,nyt,Southeast Asian Resort Towns Suffer as Iran Wa...,https://www.nytimes.com/2026/07/28/world/asia/...
1,2026-07-28-07-40-54 +0000,nyt,"India’s ‘Cockroach’ Protesters Disperse, But Q...",https://www.nytimes.com/2026/07/27/world/asia/...
2,2026-07-28-07-37-41 +0000,nypost,Major Hurricane Genevieve roars in the Pacific...,https://nypost.com/2026/07/28/us-news/hurrican...
3,2026-07-28-07-33-12 +0000,bbc,Chip stocks slide in US and Asia as AI jitters...,https://www.bbc.co.uk/news/articles/cly8zng43n...
4,2026-07-28-07-33-05 +0000,nypost,"Nolan Wells drank heavily, chose to stay on re...",https://nypost.com/2026/07/28/us-news/nolan-we...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
130      trump     33
5         iran     27
532        new     23
264  wildfires     13
6          war     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
140,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,97
282,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...,94
91,2026-07-28-00-21-41 +0000,nyt,Trump Backs New Talks but It’s Unclear What He...,https://www.nytimes.com/2026/07/27/us/politics...,90
142,2026-07-27-21-06-42 +0000,bbc,"As the US pauses the war with Iran, is Trump r...",https://www.bbc.co.uk/news/articles/c0qvnk2ezp...,88
284,2026-07-27-14-06-19 +0000,cbc,"Trump says U.S. having 'good talks' with Iran,...",https://www.cbc.ca/news/world/us-iran-war-saud...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
140,97,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...
299,67,2026-07-27-13-22-42 +0000,nyt,New Heat Wave Could Intensify Wildfires in Fra...,https://www.nytimes.com/2026/07/27/world/europ...
358,55,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
125,52,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
243,50,2026-07-27-16-23-15 +0000,nypost,Dr. Anthony Fauci ruled out Wuhan market origi...,https://nypost.com/2026/07/27/us-news/dr-antho...
94,47,2026-07-28-00-00-00 +0000,wsj,"Francesca Hong, a member of the Democratic Soc...",https://www.wsj.com/politics/elections/a-democ...
68,46,2026-07-28-01-29-25 +0000,bbc,BBC outside court as judge rules singer D4vd w...,https://www.bbc.co.uk/news/videos/cy745x171rjo...
81,42,2026-07-28-01-00-00 +0000,wsj,The Fed meets this week with an outcome that i...,https://www.wsj.com/economy/central-banking/ke...
67,40,2026-07-28-01-32-41 +0000,nyt,Seattle Police Search for 3rd Shooter in Deadl...,https://www.nytimes.com/2026/07/27/us/seattle-...
237,38,2026-07-27-16-40-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)