## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-07-17-00 +0000,wsj,Eurozone Bond Yields Fall Amid Middle East Pea...,https://www.wsj.com/finance/investing/jgbs-mix...
1,2026-04-15-07-15-46 +0000,nypost,Nevada mom Haleigh Knight faked cancer diagnos...,https://nypost.com/2026/04/15/us-news/nevada-m...
2,2026-04-15-07-14-00 +0000,wsj,"Oil Falls, With WTI at $90 on Hopes for Second...",https://www.wsj.com/finance/commodities-future...
3,2026-04-15-07-10-53 +0000,nyt,U.S. Says Israel and Lebanon Agree to More Pea...,https://www.nytimes.com/live/2026/04/14/world/...
4,2026-04-15-07-10-02 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/15/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2629/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
25       iran     36
255     trump     31
69        new     22
152       war     21
318  swalwell     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
258,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...,104
33,2026-04-15-04-04-15 +0000,bbc,Trump hints Iran talks could resume this week ...,https://www.bbc.com/news/articles/c20ddnz4w5lo...,102
302,2026-04-14-13-53-29 +0000,nyt,Two Iran-Linked Ships Passed Through Strait of...,https://www.nytimes.com/2026/04/13/world/middl...,100
332,2026-04-14-11-14-54 +0000,nypost,"US, Iran may resume war talks this week despit...",https://nypost.com/2026/04/14/world-news/us-ir...,96
314,2026-04-14-13-00-00 +0000,wapo,Iran war already taking a toll on the global e...,https://www.washingtonpost.com/business/2026/0...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
258,104,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...
97,89,2026-04-14-23-30-00 +0000,wsj,The Trump administration is expected to start ...,https://www.wsj.com/politics/policy/process-to...
296,72,2026-04-14-14-21-40 +0000,nypost,US boasts no ships moved through Strait of Hor...,https://nypost.com/2026/04/14/world-news/iran-...
52,72,2026-04-15-02-35-13 +0000,nypost,Special Victims Bureau will handle case of wom...,https://nypost.com/2026/04/14/us-news/la-speci...
119,67,2026-04-14-22-00-20 +0000,nyt,Carney Suspends Gas Tax in Canada as War Drive...,https://www.nytimes.com/2026/04/14/world/middl...
309,50,2026-04-14-13-03-00 +0000,wsj,A prolonged Middle East conflict could slash g...,https://www.wsj.com/economy/global/imf-warns-o...
274,47,2026-04-14-15-29-59 +0000,nypost,JPMorgan CEO Jamie Dimon urges Senate to vote ...,https://nypost.com/2026/04/14/business/jpmorga...
79,45,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
220,42,2026-04-14-18-06-57 +0000,nypost,"Israel, Lebanon agree Hezbollah must go: ‘Unit...",https://nypost.com/2026/04/14/world-news/israe...
360,42,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)