## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-10-15-50 +0000,bbc,Manslaughter charges laid over deadly Hong Kon...,https://www.bbc.com/news/articles/c04yldyezyeo...
1,2026-06-10-10-15-09 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Str...,https://www.nytimes.com/live/2026/06/10/world/...
2,2026-06-10-10-14-08 +0000,nypost,Pregnant Indiana mom found dead in Mexico afte...,https://nypost.com/2026/06/10/us-news/pregnant...
3,2026-06-10-10-10-24 +0000,nyt,Visiting a Soldier’s Funeral in Ukraine,https://www.nytimes.com/video/world/1000000108...
4,2026-06-10-10-07-00 +0000,wsj,Oil Prices Set to Keep Rising Even After Iran ...,https://www.wsj.com/business/energy-oil/oil-pr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
256       trump     33
7          iran     24
287       world     21
72   california     20
309       maine     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
116,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,116
166,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,111
1,2026-06-10-10-15-09 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Str...,https://www.nytimes.com/live/2026/06/10/world/...,102
101,2026-06-10-03-09-35 +0000,nyt,U.S. Strikes Iran After Trump Vowed to Retalia...,https://www.nytimes.com/2026/06/09/us/politics...,91
289,2026-06-09-17-01-09 +0000,nypost,Trump claims Iran shooting down US helicopter ...,https://nypost.com/2026/06/09/us-news/iran-sho...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
116,116,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
166,111,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
1,102,2026-06-10-10-15-09 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Str...,https://www.nytimes.com/live/2026/06/10/world/...
96,79,2026-06-10-03-36-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
122,68,2026-06-10-01-31-11 +0000,nypost,Scandal-plagued Graham Platner clinches Dem Ma...,https://nypost.com/2026/06/09/us-news/scandal-...
266,63,2026-06-09-18-06-40 +0000,latimes,SoFi Stadium workers union announces labor dea...,https://www.latimes.com/sports/soccer/story/20...
145,40,2026-06-09-23-35-20 +0000,bbc,Sea drone rescues US army helicopter crew near...,https://www.bbc.com/news/articles/cwy0l44ex5wo...
110,40,2026-06-10-02-29-57 +0000,nypost,Baby-faced killer Karmelo Anthony seen in firs...,https://nypost.com/2026/06/09/us-news/baby-fac...
62,38,2026-06-10-08-31-20 +0000,wsj,Stock Market Today: Tech Stocks Slide as Inves...,https://www.wsj.com/livecoverage/stock-market-...
254,35,2026-06-09-18-52-14 +0000,nypost,Air Canada pilot flew under the radar for 16 y...,https://nypost.com/2026/06/09/world-news/air-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)