## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-13-10-39 +0000,bbc,Five missing after fire in Swiss Alpine town,https://www.bbc.co.uk/news/articles/cy8e6g1349...
1,2026-08-21-13-09-00 +0000,wsj,"Bitcoin Surges as Institutional Demand, Short ...",https://www.wsj.com/finance/currencies/bitcoin...
2,2026-08-21-13-07-00 +0000,bbc,Rosenberg: Shortage of petrol but not patrioti...,https://www.bbc.co.uk/news/articles/c4gknzgje7...
3,2026-08-21-13-01-35 +0000,nyt,Stocks and Bonds Steady at the End of a Tumult...,https://www.nytimes.com/2026/08/21/business/st...
4,2026-08-21-13-00-05 +0000,nyt,Hurricane Season Has Been Calm. Should You Hav...,https://www.nytimes.com/2026/08/21/your-money/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2331/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
70        trump     29
342         new     18
42   california     16
299          up     14
234       harry     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
190,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...,103
146,2026-08-21-02-58-51 +0000,nyt,The Message Behind Trump’s Threats of ‘Economi...,https://www.nytimes.com/2026/08/20/world/europ...,66
348,2026-08-20-16-23-41 +0000,nypost,Bitcoin surges above $70K as Trump backs Clari...,https://nypost.com/2026/08/20/business/bitcoin...,62
246,2026-08-20-21-07-04 +0000,nypost,Morgan Stanley picks Dallas for expansion outs...,https://nypost.com/2026/08/20/business/morgan-...,60
124,2026-08-21-06-08-50 +0000,nypost,Laughing Florida sicko tells court he wants de...,https://nypost.com/2026/08/21/us-news/florida-...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
190,103,2026-08-20-23-40-00 +0000,wsj,Michael Cohen said before the last presidentia...,https://www.wsj.com/politics/policy/trump-talk...
259,59,2026-08-20-20-41-36 +0000,nyt,As Prince Harry and Meghan Depart California f...,https://www.nytimes.com/2026/08/20/us/prince-h...
71,56,2026-08-21-10-00-00 +0000,latimes,Bass hit brakes on new bike lanes near Forest ...,https://www.latimes.com/california/story/2026-...
246,53,2026-08-20-21-07-04 +0000,nypost,Morgan Stanley picks Dallas for expansion outs...,https://nypost.com/2026/08/20/business/morgan-...
351,51,2026-08-20-16-12-52 +0000,nypost,Bessent tells US allies ‘you’re either with us...,https://nypost.com/2026/08/20/us-news/bessent-...
371,48,2026-08-20-15-07-29 +0000,nypost,Walmart shares sink 9% — slowest sales growth ...,https://nypost.com/2026/08/20/business/walmart...
144,46,2026-08-21-03-57-19 +0000,nypost,Pilot killed in crash with Pennsylvania State ...,https://nypost.com/2026/08/20/us-news/pilot-ki...
124,38,2026-08-21-06-08-50 +0000,nypost,Laughing Florida sicko tells court he wants de...,https://nypost.com/2026/08/21/us-news/florida-...
282,37,2026-08-20-19-48-45 +0000,chitri,Will County executive proposes budget with no ...,https://www.chicagotribune.com/2026/08/20/will...
321,35,2026-08-20-17-39-22 +0000,latimes,Eric Swalwell briefly detained as feds seize h...,https://www.latimes.com/politics/story/2026-08...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)