## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-13-01-00 +0000,wsj,Disney’s ABC Sues FCC Over Challenge to Its Br...,https://www.wsj.com/business/media/disneys-abc...
1,2026-08-18-13-00-32 +0000,nypost,Heroic mom of three dies after jumping into ri...,https://nypost.com/2026/08/18/us-news/illinois...
2,2026-08-18-13-00-00 +0000,wapo,Fewer American adults say they’re gambling,https://www.washingtonpost.com/business/2026/0...
3,2026-08-18-13-00-00 +0000,wsj,American Is Adding Seat-Back Screens to More T...,https://www.wsj.com/business/airlines/american...
4,2026-08-18-13-00-00 +0000,nypost,The super-rich are building Swiss bunkers to s...,https://nypost.com/2026/08/18/business/inside-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
56   trump     42
96    iran     15
153    new     15
129  trial     12
394  house     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
275,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...,98
272,2026-08-17-18-45-59 +0000,bbc,Supreme Court again rejects Trump's bid to ove...,https://www.bbc.co.uk/news/articles/c74gekjgrl...,90
316,2026-08-17-16-00-31 +0000,wapo,Supreme Court rebuffs Trump’s bid to overturn ...,https://www.washingtonpost.com/politics/2026/0...,88
273,2026-08-17-18-39-39 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,86
262,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
275,98,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...
274,56,2026-08-17-18-32-30 +0000,nypost,House Ethics panel probing Dem Rep. Jimmy Gome...,https://nypost.com/2026/08/17/us-news/house-et...
299,56,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
70,49,2026-08-18-10-00-00 +0000,startribune,"After an 11-year-old stabbed a stranger, Minne...",https://www.startribune.com/st-cloud-assault-m...
204,45,2026-08-17-21-44-32 +0000,nypost,Jared Kushner: Hamas said ‘all the right thing...,https://nypost.com/2026/08/17/world-news/jared...
262,43,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...
38,40,2026-08-18-11-02-53 +0000,cbc,Russian missile attack in Kharkiv kills at lea...,https://www.cbc.ca/news/world/ukraine-war-1638...
143,39,2026-08-18-03-32-56 +0000,bbc,What to know about Tupac's murder trial and th...,https://www.bbc.co.uk/news/articles/cgmkl1j3dw...
249,38,2026-08-17-20-03-42 +0000,chitri,Trump administration briefly pauses contentiou...,https://www.chicagotribune.com/2026/08/17/big-...
269,33,2026-08-17-18-53-12 +0000,nypost,DSA Florida House candidate appears to cut int...,https://nypost.com/2026/08/17/us-news/dsa-flor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)