## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-23-13-29 +0000,missionlocal,Market Street shooting leaves one injured,https://missionlocal.org/2026/07/sf-market-str...
1,2026-07-27-23-13-13 +0000,nyt,"After Watching Luxury Cars Drag Race, Trump Bl...",https://www.nytimes.com/2026/07/27/us/politics...
2,2026-07-27-23-11-22 +0000,bbc,Trump defends tariffs in hard-hit Michigan as ...,https://www.bbc.co.uk/news/articles/cy0jknp3e6...
3,2026-07-27-23-08-13 +0000,wapo,"Betye Saar, artist who shattered stereotypes o...",https://www.washingtonpost.com/obituaries/2026...
4,2026-07-27-23-06-58 +0000,nypost,Oblivious Yellowstone fisherman has close call...,https://nypost.com/2026/07/27/us-news/yellowst...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2635/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
11       trump     30
282       iran     25
63         new     23
493  wildfires     13
0       market     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
213,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...,87
62,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,85
65,2026-07-27-21-06-42 +0000,bbc,"As the US pauses the war with Iran, is Trump r...",https://www.bbc.co.uk/news/articles/c0qvnk2ezp...,80
215,2026-07-27-14-06-19 +0000,cbc,"Trump says U.S. having 'good talks' with Iran,...",https://www.cbc.ca/news/world/us-iran-war-saud...,75
7,2026-07-27-23-02-35 +0000,nyt,Europe WildfiresUpdates: New Heat Wave Could W...,https://www.nytimes.com/live/2026/07/27/world/...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
213,87,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...
7,73,2026-07-27-23-02-35 +0000,nyt,Europe WildfiresUpdates: New Heat Wave Could W...,https://www.nytimes.com/live/2026/07/27/world/...
19,69,2026-07-27-22-30-37 +0000,nypost,Gut-wrenching video shows Lindsay Clancy on fa...,https://nypost.com/2026/07/27/us-news/lindsay-...
16,69,2026-07-27-22-42-25 +0000,nypost,15-year-old busted after deadly Seattle Center...,https://nypost.com/2026/07/27/us-news/15-year-...
41,52,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
297,50,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
55,49,2026-07-27-21-22-08 +0000,nypost,Heart-stopping moment little boy is battered b...,https://nypost.com/2026/07/27/us-news/heroic-s...
44,41,2026-07-27-21-46-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
305,37,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Chip Stocks Fall, Weighing...",https://www.wsj.com/livecoverage/stock-market-...
60,36,2026-07-27-21-14-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)