## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-14-51-18 +0000,nypost,Your guide to snagging a Midtown Manhattan apa...,https://nypost.com/2026/03/07/real-estate/how-...
1,2026-03-07-14-51-06 +0000,wapo,Trump says U.S. to expand Iran targets as Tehr...,https://www.washingtonpost.com/world/2026/03/0...
2,2026-03-07-14-49-55 +0000,nyt,Mideast Fighting: Live Updates: Trump Vows to ...,https://www.nytimes.com/live/2026/03/07/world/...
3,2026-03-07-14-46-06 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/07/world/...
4,2026-03-07-14-40-20 +0000,nyt,"At Trump’s Summit in Miami, Bolivia Makes a Po...",https://www.nytimes.com/2026/03/07/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2608/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
9     iran     63
7    trump     59
259   dies     28
202    war     28
649   dead     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,215
205,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,174
44,2026-03-07-11-09-29 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,171
190,2026-03-06-22-39-00 +0000,wsj,"Trump wants Iran’s unconditional surrender, a ...",https://www.wsj.com/politics/policy/trump-want...,167
278,2026-03-06-18-27-47 +0000,nyt,Why a G.O.P. War Powers Hawk Was a No on Reini...,https://www.nytimes.com/2026/03/06/us/politics...,165

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,215,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
25,74,2026-03-07-12-51-00 +0000,startribune,Trump will join grieving families for the retu...,https://www.startribune.com/trump-will-join-gr...
233,71,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
296,53,2026-03-06-17-45-01 +0000,nyt,"From 2019: Agnès Varda, Influential French New...",https://www.nytimes.com/2026/03/06/movies/agne...
199,51,2026-03-06-22-17-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
191,45,2026-03-06-22-37-17 +0000,latimes,Honey is wrapping up her first course at San B...,https://www.latimes.com/california/story/2026-...
173,45,2026-03-06-23-14-33 +0000,bbc,Oil price at two-year high after Qatar warns a...,https://www.bbc.com/news/articles/cy031ylgepro...
302,43,2026-03-06-17-36-06 +0000,nypost,White House releases wild video montages pairi...,https://nypost.com/2026/03/06/us-news/white-ho...
102,42,2026-03-07-06-01-03 +0000,nypost,Sen. John Kennedy reveals why Kristi Noem was ...,https://nypost.com/2026/03/07/us-news/kristi-n...
17,40,2026-03-07-13-15-00 +0000,nypost,Epstein prison guard googled him minutes befor...,https://nypost.com/2026/03/07/us-news/prison-g...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)