## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-11-02-49 +0000,nyt,Iran War Live Updates: Israel Targets Hezbolla...,https://www.nytimes.com/live/2026/03/13/world/...
1,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
2,2026-03-13-11-00-57 +0000,nyt,Phones ‘Ringing Off the Hook’ for Ukraine Defe...,https://www.nytimes.com/2026/03/13/world/europ...
3,2026-03-13-11-00-33 +0000,bbc,Starmer and Martin to tackle cost-of-living an...,https://www.bbc.com/news/articles/cvg3yly7gxpo...
4,2026-03-13-11-00-00 +0000,nypost,Why a cartful of massive gold bars was spotted...,https://nypost.com/2026/03/13/business/why-a-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     56
1      war     31
78   trump     28
75     oil     26
455    new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
302,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...,167
217,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,163
40,2026-03-13-09-54-52 +0000,bbc,US eases Russia oil sanctions as Iran war push...,https://www.bbc.com/news/articles/clyzj3g3pygo...,157
103,2026-03-13-05-07-14 +0000,nypost,Trump says Iran’s new Supreme Leader Mojtaba K...,https://nypost.com/2026/03/13/us-news/trump-sa...,147
364,2026-03-12-13-30-37 +0000,nypost,Iran’s new impotent Supreme Leader Mojtaba Kha...,https://nypost.com/2026/03/12/world-news/irans...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
302,167,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...
364,88,2026-03-12-13-30-37 +0000,nypost,Iran’s new impotent Supreme Leader Mojtaba Kha...,https://nypost.com/2026/03/12/world-news/irans...
15,72,2026-03-13-10-29-42 +0000,nypost,FBI raids Michigan home of wannabe car bomber ...,https://nypost.com/2026/03/13/us-news/fbi-raid...
42,54,2026-03-13-09-49-30 +0000,nypost,4 crew members killed as US Air Force refuelin...,https://nypost.com/2026/03/13/us-news/4-crew-m...
33,47,2026-03-13-10-00-00 +0000,latimes,"Fuel, energy prices raise the pressure as Cali...",https://www.latimes.com/environment/story/2026...
289,43,2026-03-12-17-46-12 +0000,cbc,FBI investigating Detroit-area synagogue attac...,https://www.cbc.ca/news/world/detroit-synagogu...
1,42,2026-03-13-11-01-00 +0000,wsj,A court’s order that the government must pay b...,https://www.wsj.com/politics/the-tariff-pandor...
278,41,2026-03-12-18-14-00 +0000,wsj,When Kash Patel said in one of his first video...,https://www.wsj.com/politics/policy/ufc-fighte...
363,39,2026-03-12-13-39-00 +0000,wsj,"The U.S. trade deficit declined in January, co...",https://www.wsj.com/economy/trade/u-s-trade-de...
72,39,2026-03-13-08-16-00 +0000,wsj,Dollar Rises to 3.5-Month High Amid Growing Mi...,https://www.wsj.com/finance/currencies/asian-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)