## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-03-51-15 +0000,nyt,Trump Attacks Pope Leo as Too Liberal and ‘Wea...,https://www.nytimes.com/2026/04/12/us/politics...
1,2026-04-13-03-42-41 +0000,nypost,‘The Swalwell Stink’: Rage and relief after co...,https://nypost.com/2026/04/12/us-news/the-swal...
2,2026-04-13-03-40-00 +0000,wsj,Shorter Timeline to Onshore Inventory ‘Angst’ ...,https://www.wsj.com/finance/commodities-future...
3,2026-04-13-03-39-45 +0000,latimes,Riverside cop seemingly on dating app amid sta...,https://www.latimes.com/california/story/2026-...
4,2026-04-13-03-37-42 +0000,nyt,Iran War Live Updates: U.S. to Blockade Ships ...,https://www.nytimes.com/live/2026/04/12/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
35       iran     41
0       trump     25
82      talks     25
8    swalwell     20
131      eric     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
154,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...,151
25,2026-04-13-02-09-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,132
184,2026-04-12-13-19-52 +0000,cbc,U.S. says Strait of Hormuz blockade will start...,https://www.cbc.ca/news/world/trump-strait-of-...,130
77,2026-04-12-22-38-11 +0000,wapo,Trump announces naval blockade of Iran after I...,https://www.washingtonpost.com/world/2026/04/1...,121
185,2026-04-12-13-16-09 +0000,nypost,Trump announces blockade of Strait of Hormuz a...,https://nypost.com/2026/04/12/us-news/trump-an...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
154,151,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...
37,104,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
25,88,2026-04-13-02-09-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
112,49,2026-04-12-19-50-52 +0000,nypost,Hungary’s Viktor Orbán concedes defeat after ‘...,https://nypost.com/2026/04/12/world-news/hunga...
141,37,2026-04-12-17-47-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
2,35,2026-04-13-03-40-00 +0000,wsj,Shorter Timeline to Onshore Inventory ‘Angst’ ...,https://www.wsj.com/finance/commodities-future...
116,29,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
72,28,2026-04-12-23-04-10 +0000,nypost,NYC’s first city-owned grocery store under lef...,https://nypost.com/2026/04/12/us-news/nycs-fir...
215,28,2026-04-12-09-00-00 +0000,wsj,Jeanine Pirro’s ability to manage a mercurial ...,https://www.wsj.com/politics/policy/judge-jean...
158,23,2026-04-12-16-00-00 +0000,wsj,The immigration crackdown and tepid interest a...,https://www.wsj.com/economy/jobs/restaurants-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)