## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-17-00-00 +0000,wsj,Trump’s Hold on Republicans Tested in Race to ...,https://www.wsj.com/politics/elections/trumps-...
1,2026-08-09-16-58-20 +0000,nyt,"The ‘Furthur’ Bus’s Long, Strange Trip, and Wh...",https://www.nytimes.com/2026/08/09/us/kesey-fu...
2,2026-08-09-16-46-18 +0000,bbc,Man arrested after boat capsizes near Statue o...,https://www.bbc.co.uk/news/articles/c935w1d05d...
3,2026-08-09-16-43-23 +0000,bbc,Puerto Rico rations water supplies due to inte...,https://www.bbc.co.uk/news/articles/cqlxgk7r2v...
4,2026-08-09-16-39-14 +0000,nyt,Israel Rejects Trump’s 15-Point Plan to Disarm...,https://www.nytimes.com/2026/08/09/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2293/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     17
121    iran     10
36     plan      8
260  hormuz      7
33   israel      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
24,2026-08-09-15-16-21 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,56
51,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/us-news/israel-r...,51
41,2026-08-09-14-18-10 +0000,bbc,"Israel rejects Trump's 15-point plan for Gaza,...",https://www.bbc.co.uk/news/articles/c5yw4lpe0y...,50
79,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...,50
4,2026-08-09-16-39-14 +0000,nyt,Israel Rejects Trump’s 15-Point Plan to Disarm...,https://www.nytimes.com/2026/08/09/world/middl...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
24,56,2026-08-09-15-16-21 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
20,38,2026-08-09-15-30-00 +0000,wsj,After notching a narrow victory in Michigan’s ...,https://www.wsj.com/politics/elections/michiga...
5,36,2026-08-09-16-33-50 +0000,nypost,Tragic New York Harbor boat crash victims ID’d...,https://nypost.com/2026/08/09/us-news/tragic-n...
150,34,2026-08-08-19-18-57 +0000,bbc,"Hormuz talks positive, Oman says, as Iran warn...",https://www.bbc.co.uk/news/articles/c934j5y2lq...
110,29,2026-08-09-06-10-47 +0000,nypost,Indian national allegedly killed Arizona girlf...,https://nypost.com/2026/08/09/us-news/indian-n...
66,24,2026-08-09-12-24-04 +0000,cbc,14-year-old accused in deadly school shooting ...,https://www.cbc.ca/news/world/accused-thai-sch...
40,23,2026-08-09-14-34-50 +0000,nypost,Port Washington two wins from Little League Wo...,https://nypost.com/2026/08/09/sports/port-wash...
8,18,2026-08-09-16-23-18 +0000,nypost,Deranged criminal’s own family fears his relea...,https://nypost.com/2026/08/09/us-news/north-ca...
48,18,2026-08-09-13-29-23 +0000,nypost,LI stripper sues doctor who sought restraining...,https://nypost.com/2026/08/09/us-news/li-strip...
52,18,2026-08-09-13-08-21 +0000,bbc,Residents warned to brace for the worst as Can...,https://www.bbc.co.uk/news/articles/cx25dkwk3e...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)