## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-11-11-06 +0000,bbc,Minimum wage rises to £12.71 an hour as firms ...,https://www.bbc.com/news/articles/c36r7jk6093o...
1,2026-04-01-11-01-51 +0000,nypost,Video shows accused bomb fiend hurling device ...,https://nypost.com/2026/04/01/us-news/ny-pipe-...
2,2026-04-01-11-00-51 +0000,nyt,The Fall of a Cambodian Money-Laundering Giant,https://www.nytimes.com/2026/04/01/world/asia/...
3,2026-04-01-11-00-00 +0000,nypost,Space boss rep teases plans to transform moon ...,https://nypost.com/2026/04/01/us-news/space-bo...
4,2026-04-01-11-00-00 +0000,nypost,Families of American hostages — including one ...,https://nypost.com/2026/04/01/us-news/family-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
46  trump     60
47   iran     50
48    war     41
51   will     20
79  court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-04-01-11-00-00 +0000,nypost,Families of American hostages — including one ...,https://nypost.com/2026/04/01/us-news/family-o...,205
365,2026-03-31-14-15-31 +0000,latimes,Trump says he expects U.S. to end involvement ...,https://www.latimes.com/politics/story/2026-03...,196
249,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,186
80,2026-04-01-08-49-19 +0000,bbc,Oil briefly falls below $100 and shares jump o...,https://www.bbc.com/news/articles/c2489v97842o...,175
384,2026-03-31-13-02-00 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,205,2026-04-01-11-00-00 +0000,nypost,Families of American hostages — including one ...,https://nypost.com/2026/04/01/us-news/family-o...
406,82,2026-03-31-11-26-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
30,67,2026-04-01-10-00-00 +0000,latimes,Supreme Court weighs Trump's bid to revise the...,https://www.latimes.com/politics/story/2026-04...
132,55,2026-04-01-02-32-30 +0000,nyt,Trump Lashes Out at Europe Over Strait of Horm...,https://www.nytimes.com/2026/03/31/world/middl...
397,53,2026-03-31-12-11-09 +0000,cbc,Hegseth lifts U.S. Army's suspension of 2 mili...,https://www.cbc.ca/news/world/us-kid-rock-army...
248,52,2026-03-31-20-32-12 +0000,wapo,Gas hits $4 a gallon for first time since 2022...,https://www.washingtonpost.com/business/2026/0...
254,51,2026-03-31-20-18-00 +0000,wsj,The Trump administration can’t end federal fun...,https://www.wsj.com/politics/policy/trumps-ord...
199,44,2026-03-31-22-15-00 +0000,nypost,What you’re *actually* buying when you buy Bit...,https://nypost.com/business/bitcoin-investment...
45,40,2026-04-01-09-54-00 +0000,wsj,U.K.’s Food Inflation Could Triple by Year End...,https://www.wsj.com/economy/central-banking/u-...
3,39,2026-04-01-11-00-00 +0000,nypost,Space boss rep teases plans to transform moon ...,https://nypost.com/2026/04/01/us-news/space-bo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)