## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-21-53-00 +0000,wsj,Excavation work on President Trump’s 250-foot-...,https://www.wsj.com/politics/policy/work-on-tr...
1,2026-09-03-21-53-00 +0000,wsj,Work on Trump’s 250-Foot Arch in Washington to...,https://www.wsj.com/politics/policy/work-on-tr...
2,2026-09-03-21-51-49 +0000,nyt,JD Vance Says He Wouldn’t Call Iran Conflict a...,https://www.nytimes.com/2026/09/03/us/politics...
3,2026-09-03-21-47-55 +0000,nyt,"Hillary Clinton, Meghan Markle, Lena Dunham an...",https://www.nytimes.com/2026/09/03/us/gloria-s...
4,2026-09-03-21-46-53 +0000,nypost,Tesla on autopilot halts on busy highway befor...,https://nypost.com/2026/09/03/us-news/tesla-dr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2516/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
2      trump     43
197      new     22
306   clancy     18
376       up     16
305  lindsay     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
371,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,123
124,2026-09-03-18-34-16 +0000,nypost,Vance says no ‘security concern’ behind Trump ...,https://nypost.com/2026/09/03/us-news/vance-sa...,111
310,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,103
323,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...,101
0,2026-09-03-21-53-00 +0000,wsj,Excavation work on President Trump’s 250-foot-...,https://www.wsj.com/politics/policy/work-on-tr...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
371,123,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...
63,93,2026-09-03-20-22-43 +0000,wapo,Vance says he doesn’t know when Iran conflict ...,https://www.washingtonpost.com/politics/2026/0...
312,71,2026-09-03-10-00-00 +0000,nypost,Dem NY House candidate Cait Conley ripped over...,https://nypost.com/2026/09/03/us-news/ny-dem-c...
84,67,2026-09-03-19-52-59 +0000,bbc,Watch: Defence calls for one juror to be dismi...,https://www.bbc.co.uk/news/videos/c3v49926063o...
6,66,2026-09-03-21-45-00 +0000,wsj,The odds of an interest-rate hike are now a co...,https://www.wsj.com/politics/policy/fed-rate-w...
153,54,2026-09-03-17-43-33 +0000,latimes,"Fox News cuts ties with Maria Bartiromo, weeks...",https://www.latimes.com/entertainment-arts/bus...
7,51,2026-09-03-21-44-12 +0000,nypost,NYC’s AI in schools policy is first step in pr...,https://nypost.com/2026/09/03/opinion/nycs-ai-...
323,47,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...
216,47,2026-09-03-15-30-22 +0000,nypost,Billionaire Leon Black sues House Oversight Co...,https://nypost.com/2026/09/03/us-news/billiona...
41,46,2026-09-03-20-59-00 +0000,wsj,The surprise defections of two Democrats on a ...,https://www.wsj.com/politics/shock-defections-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)