## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-11-00-09 +0000,bbc,South East Water faces £22m fine for supply fa...,https://www.bbc.com/news/articles/c3v77yzn5gxo...
1,2026-03-05-11-00-03 +0000,bbc,Defence minister in Cyprus after criticism of ...,https://www.bbc.com/news/articles/c0e55y0pzgwo...
2,2026-03-05-11-00-00 +0000,wsj,DoorDash Is Tapping Ziwe and Rob Rausch for So...,https://www.wsj.com/cmo-today/doordash-is-tapp...
3,2026-03-05-11-00-00 +0000,wapo,Trump calls on Kurds to aid U.S. effort in Ira...,https://www.washingtonpost.com/national-securi...
4,2026-03-05-11-00-00 +0000,nypost,Zohran Mamdani ditches campaign pledge on NYC ...,https://nypost.com/2026/03/05/us-news/zohran-m...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2615/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
29      iran     77
64       war     49
24     trump     38
92   iranian     22
623    texas     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...,205
408,2026-03-04-13-53-32 +0000,cbc,Two Blocks from the White House: Trump’s ‘no r...,https://www.cbc.ca/news/politics/two-blocks-fr...,196
335,2026-03-04-17-49-43 +0000,nypost,US lawmakers to vote on war powers resolution ...,https://nypost.com/2026/03/04/world-news/us-la...,191
98,2026-03-05-05-07-22 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,190
183,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,190

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,205,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...
387,116,2026-03-04-15-10-00 +0000,wsj,Incumbent Sen. John Cornyn and Texas Attorney ...,https://www.wsj.com/politics/elections/john-co...
39,81,2026-03-05-09-50-00 +0000,wsj,U.S. Economic Data Boosts Global Market Sentim...,https://www.wsj.com/finance/stocks/u-s-economi...
380,73,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
135,67,2026-03-05-02-17-10 +0000,nypost,Two remaining soldiers killed in Iranian drone...,https://nypost.com/2026/03/04/world-news/two-r...
136,62,2026-03-05-02-15-00 +0000,wsj,"Sen. Steve Daines of Montana, a close ally of ...",https://www.wsj.com/politics/elections/trump-a...
321,54,2026-03-04-18-19-00 +0000,wsj,Global authorities must step up their surveill...,https://www.wsj.com/economy/central-banking/re...
45,46,2026-03-05-09-17-35 +0000,nypost,Ex-NJ mayor Gina LaPlaca admits to driving dru...,https://nypost.com/2026/03/05/us-news/nj-mayor...
376,46,2026-03-04-15-55-00 +0000,wsj,GOP Rep. Dan Crenshaw became the first House i...,https://www.wsj.com/politics/elections/rep-dan...
421,43,2026-03-04-12-45-24 +0000,bbc,South Africa's long-serving former defence min...,https://www.bbc.com/news/articles/clyzzdgv2k0o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)