## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-13-15-44-37 +0000,nypost,"Waymo recalls nearly 4,000 robotaxis due to da...",https://nypost.com/2026/05/13/lifestyle/waymo-...
1,2026-05-13-15-44-00 +0000,wsj,Gulf Countries Tout Operations Targeting Alleg...,https://www.wsj.com/world/middle-east/gulf-cou...
2,2026-05-13-15-42-11 +0000,nypost,New LA mayor’s race poll shows undecided voter...,https://nypost.com/2026/05/13/us-news/new-la-m...
3,2026-05-13-15-36-38 +0000,bbc,Court overturns Alex Murdaugh's murder convict...,https://www.bbc.com/news/articles/cedpvnq7wn1o...
4,2026-05-13-15-35-15 +0000,bbc,Philippine Senate in lockdown after gunshots f...,https://www.bbc.com/news/articles/cnvp730yd52o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
79   trump     55
60     war     22
80   china     20
108   iran     20
17     new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-05-13-13-35-01 +0000,startribune,Trump arrives in Beijing for talks with China'...,https://www.startribune.com/trump-set-to-meet-...,145
348,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,138
25,2026-05-13-15-04-52 +0000,nyt,Trump Is in China as Iran War Continues With N...,https://www.nytimes.com/2026/05/13/world/middl...,132
255,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,123
202,2026-05-13-07-05-22 +0000,nyt,Here’s How Trump’s Trade War on China Ended Up...,https://www.nytimes.com/2026/05/13/business/tr...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,145,2026-05-13-13-35-01 +0000,startribune,Trump arrives in Beijing for talks with China'...,https://www.startribune.com/trump-set-to-meet-...
282,76,2026-05-12-22-09-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
255,68,2026-05-12-23-20-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
232,65,2026-05-13-01-20-35 +0000,nypost,Cindy Burbank — who plans to drop out of gener...,https://nypost.com/2026/05/12/us-news/cindy-bu...
359,56,2026-05-12-18-39-39 +0000,nypost,WHO warns that more hantavirus cases are likel...,https://nypost.com/2026/05/12/world-news/who-s...
227,55,2026-05-13-01-46-00 +0000,wsj,The Trump administration will designate David ...,https://www.wsj.com/politics/policy/trump-to-n...
18,52,2026-05-13-15-12-25 +0000,nypost,Epstein victim says he raped her while he was ...,https://nypost.com/2026/05/13/us-news/epstein-...
379,51,2026-05-12-17-31-00 +0000,wsj,Consumer prices rose 3.8% in April from a year...,https://www.wsj.com/economy/cpi-inflation-repo...
5,51,2026-05-13-15-33-23 +0000,nyt,Alex Murdaugh Murder Convictions Overturned by...,https://www.nytimes.com/2026/05/13/us/murdaugh...
67,41,2026-05-13-14-00-00 +0000,wsj,Vice President JD Vance is planning to deliver...,https://www.wsj.com/politics/policy/trump-jd-v...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)