## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-08-58-44 +0000,bbc,Suppliers pile pressure on government over ene...,https://www.bbc.co.uk/news/articles/cq0ld88kzx...
1,2026-10-03-08-58-11 +0000,nypost,Four of 11 suspected sex offenders arrested in...,https://nypost.com/2026/10/03/us-news/indiana-...
2,2026-10-03-08-44-29 +0000,bbc,Widdecombe suspect charged with planning terro...,https://www.bbc.co.uk/news/articles/cv1j3lgrl6...
3,2026-10-03-08-40-40 +0000,wapo,FlyDubai co-pilot used crash ax to attack capt...,https://www.washingtonpost.com/world/2026/10/0...
4,2026-10-03-08-37-00 +0000,wsj,"FlyDubai Co-Pilot Used Crash Ax in Attack, Say...",https://www.wsj.com/world/flydubai-co-pilot-us...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2375/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
160     trump     37
24   flydubai     22
26      pilot     18
389       was     18
509    market     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
369,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...,132
370,2026-10-02-09-08-06 +0000,bbc,'I was not going to let others die' - pilot of...,https://www.bbc.co.uk/news/articles/c639m98gde...,120
330,2026-10-02-11-20-46 +0000,chitri,‘I was fighting for my life’: Indian pilot hai...,https://www.chicagotribune.com/2026/10/02/indi...,109
360,2026-10-02-09-36-47 +0000,cbc,'I was fighting for my life': Indian pilot hai...,https://www.cbc.ca/news/world/flydubai-pilot-i...,109
159,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
369,132,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...
159,107,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
260,66,2026-10-02-15-21-30 +0000,cbc,G7 nations agree to release 100 million barrel...,https://www.cbc.ca/news/business/g7-trump-dies...
148,65,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
247,65,2026-10-02-15-50-14 +0000,nyt,Soft Jobs Report Boosts Market Bets Fed Will S...,https://www.nytimes.com/2026/10/02/business/ec...
34,55,2026-10-03-03-48-51 +0000,nypost,Christa Pike thought her arm would ‘burst open...,https://nypost.com/2026/10/02/us-news/christa-...
359,50,2026-10-02-09-58-00 +0000,wsj,Police score big bucks with little work in Tru...,https://www.wsj.com/politics/policy/democratic...
42,46,2026-10-03-02-20-03 +0000,nypost,Gavin Newsom vetoes bill giving California hig...,https://nypost.com/2026/10/02/us-news/gavin-ne...
318,44,2026-10-02-12-20-56 +0000,cbc,Cornell 7: Governor vows to change N.Y. rape l...,https://www.cbc.ca/news/world/cornell-investig...
100,43,2026-10-02-22-11-41 +0000,nypost,Bari Weiss’ fate up in the air as Paramount pr...,https://nypost.com/2026/10/02/media/bari-weiss...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)