## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-16-15-52-50 +0000,nyt,Houthi Attacks on Saudi Arabia Put In Doubt Ki...,https://www.nytimes.com/2026/10/16/world/middl...
1,2026-10-16-15-52-34 +0000,nypost,NYC mom charged with murdering her 5-year-old ...,https://nypost.com/2026/10/16/us-news/nyc-mom-...
2,2026-10-16-15-46-19 +0000,nyt,"Trump Ally, Paolo Zampolli, Leaves State Depar...",https://www.nytimes.com/2026/10/15/us/politics...
3,2026-10-16-15-46-11 +0000,bbc,Housing loans granted while Burnham was mayor ...,https://www.bbc.co.uk/news/articles/ck5yn70v2y...
4,2026-10-16-15-45-37 +0000,cbc,See the Amazon rainforest wildfires that have ...,https://www.cbc.ca/news/world/amazon-wildfires...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2384/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
21     trump     35
74   ukraine     21
66    school     20
444      new     19
53    market     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
281,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...,162
294,2026-10-15-20-46-18 +0000,chitri,Ukraine abandons truce and attacks Russian oil...,https://www.chicagotribune.com/2026/10/15/ukra...,110
191,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...,100
123,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...,97
202,2026-10-16-02-48-41 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
281,162,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...
125,79,2026-10-16-10-39-21 +0000,nypost,Hero who ran into Oregon elementary school to ...,https://nypost.com/2026/10/16/us-news/hero-gun...
314,70,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...
191,65,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...
196,61,2026-10-16-04-41-00 +0000,wsj,Fed Chairman Kevin Warsh declined to endorse o...,https://www.wsj.com/economy/central-banking/wa...
264,50,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
79,49,2026-10-16-13-00-00 +0000,nypost,Outrageous moment sleeping Tesla driver gets r...,https://nypost.com/2026/10/16/us-news/sleeping...
310,48,2026-10-15-20-09-35 +0000,chitri,Will County Board rejects solar farm near Mone...,https://www.chicagotribune.com/2026/10/15/will...
36,44,2026-10-16-14-22-00 +0000,wsj,Elon Musk is putting a small fortune into Repu...,https://www.wsj.com/politics/elections/elon-mu...
74,42,2026-10-16-13-04-00 +0000,wsj,"Canada Housing Starts Rise in September, Thoug...",https://www.wsj.com/economy/housing/canada-hou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)