## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-19-17-18 +0000,nypost,Taco Bell sells $1 lettuce-free enchiritos to ...,https://nypost.com/2026/07/22/business/taco-be...
1,2026-07-22-19-14-35 +0000,nyt,Laredo’s Future Rides on Trump’s Next Trade Move,https://www.nytimes.com/2026/07/22/business/ec...
2,2026-07-22-19-12-53 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...
3,2026-07-22-19-12-00 +0000,wsj,U.S. Natural Gas Gains With Eyes on Storage Da...,https://www.wsj.com/finance/commodities-future...
4,2026-07-22-19-11-38 +0000,wapo,Why is Zelensky firing top leaders as Ukraine’...,https://www.washingtonpost.com/world/2026/07/2...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2336/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
13   trump     51
17    iran     24
131    new     24
375   deal     17
18     war     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-07-22-19-12-53 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...,145
381,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,133
266,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,125
290,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...,121
156,2026-07-22-14-55-17 +0000,nypost,Trump attends dignified transfer of 4 US troop...,https://nypost.com/2026/07/22/us-news/trump-at...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,145,2026-07-22-19-12-53 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...
381,93,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
135,79,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
196,66,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
162,63,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
64,49,2026-07-22-17-39-12 +0000,nypost,Nolan Wells had been drinking alcohol but seem...,https://nypost.com/2026/07/22/us-news/nolan-we...
352,47,2026-07-21-23-14-21 +0000,nypost,Zelensky fires Ukraine military chief and name...,https://nypost.com/2026/07/21/world-news/zelen...
301,44,2026-07-22-05-44-17 +0000,nypost,"Trump-backed candidates, including ex-Giants, ...",https://nypost.com/2026/07/22/us-news/trump-ba...
387,40,2026-07-21-21-13-05 +0000,cbc,Canada will celebrate Gordie Howe bridge openi...,https://www.cbc.ca/news/canada/windsor/windsor...
40,39,2026-07-22-18-26-49 +0000,nyt,"Daniel Siad, Model Scout Who Connected Women t...",https://www.nytimes.com/2026/07/22/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)