## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-18-00-11 +0000,nyt,"As She Divorces Ken Paxton, His Wife Urges Tex...",https://www.nytimes.com/2026/10/03/us/politics...
1,2026-10-03-17-59-34 +0000,nypost,Horrific moment shots ring out inside packed L...,https://nypost.com/2026/10/03/us-news/horrific...
2,2026-10-03-17-58-43 +0000,nyt,Ex-Sheriff’s Deputy Acquitted in Fatal Shootin...,https://www.nytimes.com/2026/10/03/us/air-forc...
3,2026-10-03-17-58-09 +0000,nypost,Knife-wielding stranger stabs man to death on ...,https://nypost.com/2026/10/03/us-news/queens-m...
4,2026-10-03-17-53-35 +0000,nypost,Poaching suspect reeled in staggering amount o...,https://nypost.com/2026/10/03/us-news/californ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2395/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
199      trump     32
101   flydubai     16
68   execution     15
66        pike     12
170        new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...,81
268,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...,78
90,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...,77
6,2026-10-03-17-48-42 +0000,bbc,Tennessee prison chief to resign after Christa...,https://www.bbc.co.uk/news/articles/c8zxl62yzx...,73
52,2026-10-03-15-34-53 +0000,nypost,Tennessee prison chief resigns after Christa P...,https://nypost.com/2026/10/03/us-news/tennesse...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,81,2026-10-02-23-51-47 +0000,nypost,Co-pilot accused of trying to hijack Israel-bo...,https://nypost.com/2026/10/02/world-news/omani...
268,78,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
6,73,2026-10-03-17-48-42 +0000,bbc,Tennessee prison chief to resign after Christa...,https://www.bbc.co.uk/news/articles/c8zxl62yzx...
259,53,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
267,37,2026-10-02-20-26-03 +0000,nypost,Trump says ‘Cornell 7’ frat boys ‘won’t get a ...,https://nypost.com/2026/10/02/us-news/trump-sa...
1,36,2026-10-03-17-59-34 +0000,nypost,Horrific moment shots ring out inside packed L...,https://nypost.com/2026/10/03/us-news/horrific...
68,34,2026-10-03-14-00-00 +0000,nypost,Iconic California company scoops up empty Yama...,https://nypost.com/2026/10/03/business/disney-...
265,33,2026-10-02-20-29-00 +0000,wsj,"The U.S. added 29,000 jobs in September, far s...",https://www.wsj.com/economy/jobs/september-job...
16,33,2026-10-03-17-10-19 +0000,nypost,Rep. Burchett planning to block NYC socialist ...,https://nypost.com/2026/10/03/us-news/plan-to-...
90,32,2026-10-03-11-50-04 +0000,nypost,Flydubai co-pilot used crash ax to hack at pil...,https://nypost.com/2026/10/03/world-news/flydu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)