## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-07-45-32 +0000,nyt,Iran War Live Updates: Another U.S. Service Me...,https://www.nytimes.com/live/2026/07/19/world/...
1,2026-07-20-07-45-30 +0000,nyt,Global Oil Price Crosses $90 a Barrel as U.S.-...,https://www.nytimes.com/2026/07/19/business/oi...
2,2026-07-20-07-45-00 +0000,wsj,Sterling Rises as Burnham to Become U.K. PM,https://www.wsj.com/opinion/asian-currencies-c...
3,2026-07-20-07-37-00 +0000,wsj,Gold Slips After Brent Rises Back Above $90 a ...,https://www.wsj.com/finance/commodities-future...
4,2026-07-20-07-36-59 +0000,nyt,India’s CJP Party Leads Protest March to Parli...,https://www.nytimes.com/2026/07/20/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2511/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
142    world     28
143      cup     25
0       iran     18
66       new     16
18   burnham     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,102
84,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,94
170,2026-07-19-13-41-14 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/article/tension-looms-...,92
93,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...,88
115,2026-07-19-19-25-24 +0000,chitri,Trump celebrates the World Cup as a US victory...,https://www.chicagotribune.com/2026/07/19/trum...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,102,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...
73,60,2026-07-19-23-25-00 +0000,wsj,"Usha Vance gave birth to a baby boy on Sunday,...",https://www.wsj.com/us-news/second-lady-usha-v...
53,58,2026-07-20-01-00-00 +0000,wsj,Jordan Becomes New Flashpoint in U.S.-Iran War...,https://www.wsj.com/world/middle-east/jordan-b...
25,41,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
123,39,2026-07-19-18-35-33 +0000,nypost,Chilling video shows Monaco bomb attack that n...,https://nypost.com/2026/07/19/world-news/video...
60,32,2026-07-20-00-27-18 +0000,nypost,Jubilant Spain fans flock to NYC landmarks to ...,https://nypost.com/2026/07/19/us-news/spain-fa...
85,30,2026-07-19-22-50-22 +0000,nypost,California city chief arrested on a yacht just...,https://nypost.com/2026/07/19/us-news/californ...
27,26,2026-07-20-04-01-05 +0000,nyt,Five of the Main Challenges Awaiting Andy Burn...,https://www.nytimes.com/2026/07/20/world/europ...
77,24,2026-07-19-23-18-13 +0000,nypost,Taco Bell customer reveals excruciating sympto...,https://nypost.com/2026/07/19/us-news/taco-bel...
71,24,2026-07-19-23-43-00 +0000,wsj,Oil Rises on Rising Concerns Over Supply Disru...,https://www.wsj.com/finance/commodities-future...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)