## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-10-46-45 +0000,bbc,First round of US-Iran talks ends with encoura...,https://www.bbc.com/news/articles/cwy0q41v1lzo...
1,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
2,2026-06-22-10-44-00 +0000,wsj,"Healthcare Investors GHO, CBC Weigh New Global...",https://www.wsj.com/finance/investing/healthca...
3,2026-06-22-10-34-49 +0000,bbc,Watch: PM's emotional tribute to his wife and ...,https://www.bbc.com/news/videos/cq6185zgpdro?a...
4,2026-06-22-10-34-27 +0000,nypost,Abortion pill advertisement at US Open leaves ...,https://nypost.com/2026/06/22/us-news/abortion...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
2       iran     26
3      talks     16
401    trump     16
89   starmer     13
32       new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
164,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,99
213,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...,92
74,2026-06-22-06-56-00 +0000,wsj,Oil Falls on Signs of Progress in U.S.-Iran Pe...,https://www.wsj.com/finance/commodities-future...,75
191,2026-06-21-17-04-26 +0000,nyt,As Vance Offers Iran ‘Outstretched Hand’ in Ta...,https://www.nytimes.com/2026/06/21/world/middl...,72
8,2026-06-22-10-31-26 +0000,nyt,Mideast Live Updates: Mediators Point to Progr...,https://www.nytimes.com/live/2026/06/22/world/...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
164,99,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
59,50,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...
184,41,2026-06-21-17-32-12 +0000,nypost,NYC voters are fed up with the Democratic Part...,https://nypost.com/2026/06/21/us-news/nyc-vote...
1,35,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
99,34,2026-06-22-01-53-23 +0000,bbc,One of World Cup's great stories - can Cape Ve...,https://www.bbc.com/sport/football/articles/c0...
97,31,2026-06-22-01-57-34 +0000,nypost,LA suffocates under ‘toxic’ smoke as massive w...,https://nypost.com/2026/06/21/us-news/los-ange...
8,26,2026-06-22-10-31-26 +0000,nyt,Mideast Live Updates: Mediators Point to Progr...,https://www.nytimes.com/live/2026/06/22/world/...
118,24,2026-06-21-23-57-59 +0000,bbc,Russian troop build-up threatens city seen as ...,https://www.bbc.com/news/articles/c9w2g0ewk95o...
88,23,2026-06-22-03-31-40 +0000,bbc,Trump-backed political outsider wins Colombia ...,https://www.bbc.com/news/articles/clye4ky2yzpo...
205,22,2026-06-21-15-46-09 +0000,nypost,Sore loser Texas Rep. Jasmine Crockett says sh...,https://nypost.com/2026/06/21/us-news/jasmine-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)