## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-26-12-49-10 +0000,nyt,"To Understand Pope Leo’s Efforts on A.I., Look...",https://www.nytimes.com/2026/05/26/us/pope-leo...
1,2026-05-26-12-44-12 +0000,bbc,Ferry frustrations and housing concerns in Gorey,https://www.bbc.com/news/articles/c4g000d4l45o...
2,2026-05-26-12-43-50 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...
3,2026-05-26-12-40-00 +0000,wsj,Mango Says Late Founder’s Son Is Stepping Down...,https://www.wsj.com/business/retail/mango-says...
4,2026-05-26-12-36-48 +0000,bbc,BP chairman removed over 'serious' conduct con...,https://www.bbc.com/news/articles/cjrppppwvwlo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2375/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
12      iran     40
61     trump     21
234     deal     15
21   strikes     10
229      oil      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-05-26-12-43-50 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...,122
43,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,104
22,2026-05-26-11-58-30 +0000,wapo,Iran threatens retaliation after U.S. strikes ...,https://www.washingtonpost.com/world/2026/05/2...,97
261,2026-05-25-13-51-50 +0000,nypost,Trump demands six Muslim countries join Abraha...,https://nypost.com/2026/05/25/us-news/presiden...,94
205,2026-05-25-19-07-57 +0000,wapo,"As new Iran deal faces sharp criticism, Trump ...",https://www.washingtonpost.com/world/2026/05/2...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,122,2026-05-26-12-43-50 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...
43,64,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...
168,40,2026-05-25-21-40-23 +0000,nyt,Oil Prices Fall Sharply on News of Possible Ir...,https://www.nytimes.com/2026/05/24/business/oi...
108,33,2026-05-26-07-45-06 +0000,nypost,Carney warns Alberta independence vote from Ca...,https://nypost.com/2026/05/26/world-news/carne...
18,31,2026-05-26-12-00-00 +0000,nypost,Save Californians thousands — then fire up Sac...,https://nypost.com/2026/05/26/us-news/steve-hi...
52,29,2026-05-26-10-35-00 +0000,wsj,War with Iran has halted a hard-won improvemen...,https://www.wsj.com/economy/housing/how-the-ir...
256,29,2026-05-25-14-23-00 +0000,wsj,Pope Leo Compares AI Threat to Biblical ‘Tower...,https://www.wsj.com/world/pope-leo-ai-encyclic...
241,28,2026-05-25-15-45-27 +0000,bbc,White House gunman had previous run-ins with S...,https://www.bbc.com/news/articles/c1l22pg12mpo...
95,27,2026-05-26-08-39-04 +0000,nypost,Mom of two missing Utah boys issues desperate ...,https://nypost.com/2026/05/26/us-news/mother-l...
127,26,2026-05-26-04-55-47 +0000,nypost,Lefty Senate candidate Graham Platner makes un...,https://nypost.com/2026/05/26/us-news/lefty-se...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)