## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-13-28-15 +0000,nyt,Psychiatrist Who Killed Six at German Christma...,https://www.nytimes.com/2026/06/26/world/europ...
1,2026-06-26-13-28-00 +0000,wsj,Oil Futures Fall With Focus on Increasing Supply,https://www.wsj.com/finance/commodities-future...
2,2026-06-26-13-23-06 +0000,nyt,Venezuela Live Updates: Death Toll Rises to 58...,https://www.nytimes.com/live/2026/06/26/world/...
3,2026-06-26-13-22-39 +0000,cbc,Driver in Christmas vehicle attack in Germany ...,https://www.cbc.ca/news/world/germany-sentenci...
4,2026-06-26-13-20-48 +0000,nyt,Oil Prices Return to Prewar Levels After Four ...,https://www.nytimes.com/2026/06/26/business/en...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2498/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
485       trump     35
393         new     22
673       court     22
1022    supreme     21
14    venezuela     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
373,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...,116
361,2026-06-25-14-49-39 +0000,latimes,"Trump may end legal protection for 350,000 Hai...",https://www.latimes.com/politics/story/2026-06...,106
213,2026-06-25-22-10-20 +0000,nyt,Supreme Court Expands Trump’s Power Over Immig...,https://www.nytimes.com/2026/06/25/us/politics...,102
317,2026-06-25-17-06-15 +0000,nyt,Supreme Court Allows Trump to Block Asylum See...,https://www.nytimes.com/2026/06/25/us/politics...,98
368,2026-06-25-14-39-46 +0000,nypost,Supreme Court rules Trump can remove deportati...,https://nypost.com/2026/06/25/us-news/supreme-...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
373,116,2026-06-25-14-20-34 +0000,nypost,Supreme Court rules Trump can turn back asylum...,https://nypost.com/2026/06/25/us-news/supreme-...
167,79,2026-06-26-01-08-00 +0000,wsj,California’s proposed billionaire tax will app...,https://www.wsj.com/politics/policy/california...
169,69,2026-06-26-01-00-00 +0000,wsj,New York City’s business elites are overhaulin...,https://www.wsj.com/politics/policy/wall-stree...
154,62,2026-06-26-02-56-25 +0000,nypost,"Iran, Egypt outraged over ‘Pride Match’ design...",https://nypost.com/2026/06/25/sports/iran-egyp...
11,58,2026-06-26-13-13-03 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/2026/06/25/world/ameri...
256,47,2026-06-25-20-27-32 +0000,nyt,Oil Prices Jump After Attack Halts Shipping in...,https://www.nytimes.com/2026/06/25/business/oi...
115,44,2026-06-26-08-11-08 +0000,nypost,Saudi doctor sentenced to life in prison for d...,https://nypost.com/2026/06/26/world-news/saudi...
265,39,2026-06-25-20-04-00 +0000,wsj,The U.S. Army is leasing land on bases across ...,https://www.wsj.com/politics/national-security...
276,36,2026-06-25-19-41-00 +0000,wsj,Watch how American and British sailors test so...,https://www.wsj.com/politics/national-security...
377,36,2026-06-25-14-08-49 +0000,nyt,Traveling to Europe in a Heat Wave? Here’s Wha...,https://www.nytimes.com/2026/06/25/travel/euro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)