## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-12-27-36 +0000,nyt,Artists Threaten to Sue Venice Biennale for In...,https://www.nytimes.com/2026/06/03/arts/design...
1,2026-06-03-12-25-31 +0000,bbc,The end of Trump's 'weaponisation' fund is ano...,https://www.bbc.com/news/articles/c87q9d7r57yo...
2,2026-06-03-12-25-00 +0000,wsj,EU Makes Bid to Cut Reliance On U.S. Tech Infr...,https://www.wsj.com/world/europe/eu-makes-bid-...
3,2026-06-03-12-21-06 +0000,nyt,European Union Outlines Plan to Reduce Depende...,https://www.nytimes.com/2026/06/03/technology/...
4,2026-06-03-12-18-47 +0000,nyt,Iran War Live Updates: Kuwait Says Iranian Att...,https://www.nytimes.com/live/2026/06/03/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
9         trump     44
138         new     30
340  california     28
382        race     23
30         iran     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
206,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,155
127,2026-06-03-05-25-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...,126
283,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,126
80,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...,123
140,2026-06-03-04-26-53 +0000,nypost,Trump’s pick for Iowa governor Randy Feenstra ...,https://nypost.com/2026/06/03/us-news/trump-pi...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
206,155,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
80,123,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
133,76,2026-06-03-04-50-52 +0000,nyt,Zach Lahn Wins Republican Primary for Iowa Gov...,https://www.nytimes.com/2026/06/03/us/iowa-gov...
94,66,2026-06-03-08-25-40 +0000,nypost,"Iranian drone attack destroys Kuwait airport, ...",https://nypost.com/2026/06/03/world-news/irani...
110,62,2026-06-03-07-39-32 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
137,55,2026-06-03-04-33-25 +0000,missionlocal,Lopsided early S.F. election results: Big lead...,https://missionlocal.org/2026/06/san-francisco...
358,46,2026-06-02-15-55-41 +0000,nypost,Ex-’60 Minutes’ boss Bill Owens praises Scott ...,https://nypost.com/2026/06/02/media/ex-60-minu...
251,43,2026-06-02-22-06-19 +0000,nypost,Biz group shells out $200K for NBA Finals ad r...,https://nypost.com/2026/06/02/business/biz-gro...
203,43,2026-06-03-01-04-06 +0000,nypost,Rebecca Bennett wins Democratic primary for NJ...,https://nypost.com/2026/06/02/us-news/rebecca-...
168,40,2026-06-03-02-54-03 +0000,missionlocal,San Francisco polls close: Will tonight’s big ...,https://missionlocal.org/2026/06/san-francisco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)