## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-05-11-00-00 +0000,wsj,The Number of Law-School Grads Getting Extra T...,https://www.wsj.com/us-news/education/bar-exam...
1,2026-04-05-11-00-00 +0000,missionlocal,My Excelsior: Jay Pham knows his dive bars and...,https://missionlocal.org/2026/04/my-excelsior-...
2,2026-04-05-10-58-12 +0000,nyt,Iran War Live Updates: U.S. Rescues Officer Fr...,https://www.nytimes.com/live/2026/04/05/world/...
3,2026-04-05-10-57-05 +0000,bbc,Keir Starmer 'concerned' over Kanye West UK fe...,https://www.bbc.com/news/articles/cp86942yj97o...
4,2026-04-05-10-07-16 +0000,bbc,What we know so far about rescue of US airman ...,https://www.bbc.com/news/articles/cm2k1dgz142o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20      iran     21
29     trump     16
180      new     10
240  iranian      9
21       war      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-05-10-58-12 +0000,nyt,Iran War Live Updates: U.S. Rescues Officer Fr...,https://www.nytimes.com/live/2026/04/05/world/...,84
144,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,56
37,2026-04-05-07-03-49 +0000,nyt,U.S. Rescues Downed Air Force Officer Deep Ins...,https://www.nytimes.com/2026/04/04/us/politics...,55
60,2026-04-05-01-00-00 +0000,wsj,President Trump’s repeated declarations that t...,https://www.wsj.com/politics/national-security...,54
47,2026-04-05-03-48-19 +0000,nypost,"Inside secret SoCal lives of niece, grandniece...",https://nypost.com/2026/04/04/us-news/inside-t...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,84,2026-04-05-10-58-12 +0000,nyt,Iran War Live Updates: U.S. Rescues Officer Fr...,https://www.nytimes.com/live/2026/04/05/world/...
47,54,2026-04-05-03-48-19 +0000,nypost,"Inside secret SoCal lives of niece, grandniece...",https://nypost.com/2026/04/04/us-news/inside-t...
15,32,2026-04-05-09-30-00 +0000,wsj,Central banks live in fear of their last mista...,https://www.wsj.com/economy/central-banking/pa...
68,32,2026-04-05-00-04-03 +0000,bbc,'Absolutely spectacular': Artemis II crew see ...,https://www.bbc.com/news/videos/ce3d5gkd2geo?a...
123,30,2026-04-04-17-42-39 +0000,nypost,Gavin Newsom to spend $19M in taxpayer funds o...,https://nypost.com/2026/04/04/us-news/gavin-ne...
50,24,2026-04-05-02-59-01 +0000,nypost,"Leo XIV celebrates first Easter vigil as pope,...",https://nypost.com/2026/04/04/world-news/pope-...
63,23,2026-04-05-00-55-49 +0000,nypost,Bay Area police chief’s bizarre excuse for lea...,https://nypost.com/2026/04/04/us-news/bay-area...
9,22,2026-04-05-10-00-00 +0000,latimes,"Barabak: For more than 30 years — day in, day ...",https://www.latimes.com/politics/story/2026-04...
101,22,2026-04-04-20-09-53 +0000,latimes,Man convicted of murdering his girlfriend four...,https://www.latimes.com/california/story/2026-...
72,22,2026-04-04-23-39-56 +0000,nypost,"American CEO, mom of 3 killed in Nicaragua hor...",https://nypost.com/2026/04/04/us-news/american...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)