## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-11-13-14-19 +0000,bbc,US wants Iran to pledge to stop shooting at sh...,https://www.bbc.co.uk/news/articles/crelyq79x7...
1,2026-07-11-13-11-52 +0000,bbc,US pays out $3m to victims of mystery Havana S...,https://www.bbc.co.uk/news/articles/cr7xyl78vn...
2,2026-07-11-13-10-09 +0000,nyt,Boat Carrying Dozens of Tourists Capsizes in V...,https://www.nytimes.com/2026/07/11/world/asia/...
3,2026-07-11-13-00-00 +0000,missionlocal,Mariposa,https://missionlocal.org/2026/07/mariposa/
4,2026-07-11-13-00-00 +0000,missionlocal,Re-opening the Great Highway to cars could cos...,https://missionlocal.org/2026/07/great-highway...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
47   trump     39
64     new     22
0     iran     19
118     up     13
462   will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
168,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...,124
96,2026-07-11-04-00-00 +0000,wsj,A lack of defensive capabilities aboard Presid...,https://www.wsj.com/politics/national-security...,116
89,2026-07-11-04-42-18 +0000,nypost,Trump warns US military will ‘destroy all area...,https://nypost.com/2026/07/11/us-news/trump-wa...,100
52,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...,93
200,2026-07-10-20-27-02 +0000,nypost,Oil giants to gain ‘billions’ from Iran war — ...,https://nypost.com/2026/07/10/business/oil-gia...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
168,124,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...
96,64,2026-07-11-04-00-00 +0000,wsj,A lack of defensive capabilities aboard Presid...,https://www.wsj.com/politics/national-security...
89,61,2026-07-11-04-42-18 +0000,nypost,Trump warns US military will ‘destroy all area...,https://nypost.com/2026/07/11/us-news/trump-wa...
52,54,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
54,46,2026-07-11-09-28-03 +0000,nypost,UK police release man arrested over killing of...,https://nypost.com/2026/07/11/world-news/ann-w...
186,44,2026-07-10-21-00-23 +0000,nypost,Accused rapist Graham Platner formally withdra...,https://nypost.com/2026/07/10/us-news/accused-...
144,42,2026-07-10-22-52-00 +0000,wsj,Investigators found evidence that Corey Lewand...,https://www.wsj.com/politics/policy/dhs-corey-...
292,39,2026-07-10-15-27-46 +0000,nyt,Gaza Aid Worker on His Way to Watch World Cup ...,https://www.nytimes.com/2026/07/09/world/middl...
129,36,2026-07-11-00-17-15 +0000,bbc,'Devastating' evidence against Charlie Kirk mu...,https://www.bbc.co.uk/news/articles/c4gy12gqzp...
192,35,2026-07-10-20-53-55 +0000,nypost,Trillion-dollar South Korean chipmaker SK Hyni...,https://nypost.com/2026/07/10/business/south-k...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)