## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-11-10-01-00 +0000,wsj,U.S. Hantavirus Cruise Passengers Fly to Quara...,https://www.wsj.com/world/china/u-s-hantavirus...
1,2026-05-11-10-00-09 +0000,nyt,A Single Infusion Could Suppress H.I.V. for Ye...,https://www.nytimes.com/2026/05/11/health/hiv-...
2,2026-05-11-10-00-00 +0000,nypost,Texas Gov. Abbott welcomes NY companies after ...,https://nypost.com/2026/05/11/us-news/texas-go...
3,2026-05-11-10-00-00 +0000,missionlocal,S.F. nurses demanding Kaiser help colleague wh...,https://missionlocal.org/2026/05/kaiser-nurse-...
4,2026-05-11-10-00-00 +0000,nypost,Hong Kong helped bankroll Iran’s terror networ...,https://nypost.com/2026/05/11/business/hong-ko...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2635/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
75        trump     32
41         iran     22
0    hantavirus     16
110         war     15
120       china     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-05-11-09-01-41 +0000,bbc,Oil prices jump after Trump dismisses Iran pro...,https://www.bbc.com/news/articles/ckgp4ev4yg4o...,99
218,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,96
99,2026-05-11-01-55-13 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,95
69,2026-05-11-06-52-00 +0000,wsj,Oil Climbs as Trump Rejects Iran’s Response to...,https://www.wsj.com/finance/commodities-future...,83
108,2026-05-11-00-48-30 +0000,nyt,Trump Says Iran’s Response to Latest U.S. Prop...,https://www.nytimes.com/2026/05/10/us/politics...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,99,2026-05-11-09-01-41 +0000,bbc,Oil prices jump after Trump dismisses Iran pro...,https://www.bbc.com/news/articles/ckgp4ev4yg4o...
168,61,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...
233,43,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...
5,37,2026-05-11-10-00-00 +0000,nypost,Inside Meta’s threat to exit New Mexico over k...,https://nypost.com/2026/05/11/business/inside-...
96,34,2026-05-11-02-00-00 +0000,wsj,Women are playing a bigger role in the America...,https://www.wsj.com/economy/jobs/a-changing-jo...
68,34,2026-05-11-06-55-06 +0000,nypost,50-year-old missing persons cold case cracked ...,https://nypost.com/2026/05/11/us-news/missing-...
114,33,2026-05-11-00-30-56 +0000,bbc,Chris Mason: Another crunch moment for Starmer...,https://www.bbc.com/news/articles/cevp4kr79e4o...
123,32,2026-05-10-23-32-40 +0000,bbc,"This couple lost £1,000 after their flight was...",https://www.bbc.com/news/articles/cx215yldr13o...
61,30,2026-05-11-07-27-45 +0000,nypost,Terrifying videos show Frontier Airlines passe...,https://nypost.com/2026/05/11/us-news/terrifyi...
241,29,2026-05-10-10-06-32 +0000,nypost,NYPD captain’s transfer after viral rant bashi...,https://nypost.com/2026/05/10/us-news/nypd-cap...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)