## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-14-22-13-36 +0000,nyt,"In Israel, Broad Discontent Over the Emerging ...",https://www.nytimes.com/2026/06/14/world/middl...
1,2026-06-14-22-12-14 +0000,nypost,Trump says he’ll refuse FISA spy power extensi...,https://nypost.com/2026/06/14/us-news/trump-sa...
2,2026-06-14-22-07-42 +0000,nyt,Iran War Live Updates: Trump Announces Cease-F...,https://www.nytimes.com/live/2026/06/14/world/...
3,2026-06-14-22-07-08 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/14/world/...
4,2026-06-14-21-59-28 +0000,latimes,Historic swells continue to batter California ...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2467/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6    trump     27
134  world     20
135    cup     14
121    new     13
5     iran     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
93,2026-06-14-15-05-43 +0000,nypost,Trump says Iran peace deal will be signed in n...,https://nypost.com/2026/06/14/us-news/trump-cr...,84
106,2026-06-14-12-18-06 +0000,cbc,Trump warns Israel and Iran not to ‘blow it’ a...,https://www.cbc.ca/news/world/israeli-military...,78
107,2026-06-14-12-12-46 +0000,nypost,"Iran agrees not to build a nuke, will reopen S...",https://nypost.com/2026/06/14/world-news/iran-...,74
14,2026-06-14-21-36-06 +0000,nypost,Trump says Iran peace deal ‘is now complete’: ...,https://nypost.com/2026/06/14/world-news/trump...,61
112,2026-06-14-11-23-36 +0000,bbc,Trump says US-Iran deal to be signed on Sunday...,https://www.bbc.com/news/articles/cvglmn49xz0o...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
93,84,2026-06-14-15-05-43 +0000,nypost,Trump says Iran peace deal will be signed in n...,https://nypost.com/2026/06/14/us-news/trump-cr...
174,53,2026-06-14-00-00-54 +0000,nypost,Mexican trade group leader fired after racist ...,https://nypost.com/2026/06/13/world-news/mexic...
90,45,2026-06-14-15-15-19 +0000,cbc,Mayhem mars Knicks euphoria as New York City c...,https://www.cbc.ca/news/world/mayhem-euphoria-...
43,30,2026-06-14-19-44-00 +0000,wsj,"Sen. Mitch McConnell (R., Ky.) has been admitt...",https://www.wsj.com/politics/policy/sen-mitch-...
110,28,2026-06-14-11-54-55 +0000,nypost,Switzerland voters reject proposal to cap coun...,https://nypost.com/2026/06/14/world-news/switz...
11,23,2026-06-14-21-40-14 +0000,nypost,Russians using AI to recreate dead soldiers fo...,https://nypost.com/2026/06/14/world-news/russi...
181,23,2026-06-13-23-00-00 +0000,wsj,"As President Trump turns 80 this weekend, astr...",https://www.wsj.com/arts-culture/donald-trump-...
68,23,2026-06-14-17-25-09 +0000,bbc,Royal Marines board Russian shadow fleet oil t...,https://www.bbc.com/news/articles/clyek039l2vo...
183,22,2026-06-13-22-57-28 +0000,latimes,Spencer Pratt decries 'very suspicious fire' a...,https://www.latimes.com/california/story/2026-...
34,21,2026-06-14-20-30-55 +0000,nypost,Locals build park in one of NYC’s most barren ...,https://nypost.com/2026/06/14/us-news/communit...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)