## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-05-19-03-54 +0000,nypost,NPR didn’t quote a single member of Michigan s...,https://nypost.com/2026/04/05/us-news/npr-didn...
1,2026-04-05-19-01-07 +0000,nyt,Pepsi Drops Sponsorship of Wireless Festival H...,https://www.nytimes.com/2026/04/05/world/europ...
2,2026-04-05-19-00-48 +0000,nypost,NASA’s No. 1 guy poo-poohs critics over crapp...,https://nypost.com/2026/04/05/us-news/nasas-no...
3,2026-04-05-19-00-09 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
4,2026-04-05-19-00-03 +0000,startribune,Trump issues fiery new threat against Iran as ...,https://www.startribune.com/us-service-member-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
28      iran     28
32     trump     24
29       war     11
41    airman     10
176  missing     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-04-05-19-00-09 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...,99
68,2026-04-05-14-31-37 +0000,nypost,Trump heralds ‘Easter Miracle’ after daring re...,https://nypost.com/2026/04/05/us-news/trump-he...,91
77,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...,88
24,2026-04-05-17-19-53 +0000,nypost,Defiant Iran vows to escalate war after Trump’...,https://nypost.com/2026/04/05/world-news/defia...,81
12,2026-04-05-18-12-38 +0000,nypost,Trump gives Iran Tuesday evening deadline to o...,https://nypost.com/2026/04/05/us-news/trump-gi...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,99,2026-04-05-19-00-09 +0000,nyt,Iran War Live Updates: Trump Escalates Threat ...,https://www.nytimes.com/live/2026/04/05/world/...
117,45,2026-04-05-02-59-01 +0000,nypost,"Leo XIV celebrates first Easter vigil as pope,...",https://nypost.com/2026/04/04/world-news/pope-...
73,38,2026-04-05-12-50-51 +0000,nypost,"How US used SEAL Team 6, a CIA ruse and death ...",https://nypost.com/2026/04/05/world-news/us-re...
77,36,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...
97,31,2026-04-05-09-30-00 +0000,wsj,Central banks live in fear of their last mista...,https://www.wsj.com/economy/central-banking/pa...
16,27,2026-04-05-18-01-06 +0000,nypost,Sinister past of Iranian Gen. Soleimani’s niec...,https://nypost.com/2026/04/05/us-news/ex-boyfr...
44,25,2026-04-05-16-27-05 +0000,nypost,Artemis II crew releasing absolutely gobsmacki...,https://nypost.com/2026/04/05/us-news/artemis-...
98,23,2026-04-05-09-30-00 +0000,wsj,Congressional Race Takes a Strange Turn—One Gu...,https://www.wsj.com/lifestyle/bobby-pulido-tex...
47,22,2026-04-05-16-25-58 +0000,nypost,California college ranked top party school in ...,https://nypost.com/2026/04/05/us-news/californ...
15,19,2026-04-05-18-02-19 +0000,nypost,"Bone-headed bandits try to steal McClaren, G w...",https://nypost.com/2026/04/05/us-news/bone-hea...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)