## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-27-11-56-50 +0000,nyt,Samsung Unions Approve Pay Deal That Highlight...,https://www.nytimes.com/2026/05/27/world/asia/...
1,2026-05-27-11-53-06 +0000,bbc,Texas Attorney General Paxton routs veteran in...,https://www.bbc.com/news/articles/clypprglrlyo...
2,2026-05-27-11-52-46 +0000,bbc,Five people found alive after week trapped in ...,https://www.bbc.com/news/articles/crkpvxrxgp6o...
3,2026-05-27-11-51-00 +0000,wsj,Dick’s Sales Jump as Foot Locker Turnaround Ta...,https://www.wsj.com/business/retail/dicks-sale...
4,2026-05-27-11-46-00 +0000,wsj,Lululemon Settles Dispute With Founder,https://www.wsj.com/business/retail/lululemon-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
229  trump     35
8    texas     29
47    iran     26
355    new     18
4     deal     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
29,2026-05-27-10-57-00 +0000,wsj,Texas Attorney General Ken Paxton might end up...,https://www.wsj.com/politics/trump-remakes-gop...,152
175,2026-05-27-01-02-25 +0000,nypost,Ken Paxton swamps John Cornyn in Texas GOP Sen...,https://nypost.com/2026/05/26/us-news/ken-paxt...,128
59,2026-05-27-10-00-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,122
31,2026-05-27-10-54-27 +0000,cbc,Trump's scandal-plagued pick wins Texas Senate...,https://www.cbc.ca/news/world/us-texas-republi...,109
60,2026-05-27-10-00-00 +0000,latimes,Barabak: Texas is where Democratic dreams die....,https://www.latimes.com/politics/story/2026-05...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
29,152,2026-05-27-10-57-00 +0000,wsj,Texas Attorney General Ken Paxton might end up...,https://www.wsj.com/politics/trump-remakes-gop...
6,76,2026-05-27-11-36-57 +0000,nyt,Iran War Live Updates: Fighting Flares in Leba...,https://www.nytimes.com/live/2026/05/27/world/...
78,61,2026-05-27-09-03-26 +0000,nypost,Israel kills new Hamas military chief who was...,https://nypost.com/2026/05/27/world-news/israe...
356,54,2026-05-26-15-09-11 +0000,nypost,Ex-JPMorgan banker Chirayu Rana hit with major...,https://nypost.com/2026/05/26/business/ex-jpmo...
59,50,2026-05-27-10-00-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
243,49,2026-05-26-21-13-12 +0000,nypost,"Starbucks sees sales drop, mass protests in So...",https://nypost.com/2026/05/26/world-news/starb...
271,46,2026-05-26-20-17-40 +0000,nyt,Canada Strikes Landmark Deal to Export Liquefi...,https://www.nytimes.com/2026/05/26/world/canad...
20,45,2026-05-27-11-03-03 +0000,nypost,Race against time to rescue villagers trapped ...,https://nypost.com/2026/05/27/world-news/race-...
216,45,2026-05-26-22-18-28 +0000,nypost,Possible serial killer is latest horror to upe...,https://nypost.com/2026/05/26/world-news/possi...
307,35,2026-05-26-18-33-23 +0000,latimes,Tesla driver infamous for California road rage...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)