## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-28-03-52-35 +0000,nypost,Ex-Hunter Biden pal who testified against him ...,https://nypost.com/2026/10/27/us-news/ex-hunte...
1,2026-10-28-03-47-00 +0000,wsj,Singapore Dollar Steady as Investors Await Fed...,https://www.wsj.com/finance/currencies/asian-c...
2,2026-10-28-03-43-38 +0000,bbc,Luxury cruise passengers stranded in Cambodia ...,https://www.bbc.co.uk/news/articles/cwj342k62e...
3,2026-10-28-03-41-20 +0000,nyt,"Texas Senate Rivals Converge on Lubbock, With ...",https://www.nytimes.com/2026/10/27/us/election...
4,2026-10-28-03-36-13 +0000,nyt,Hong Kong’s Property Market Is (Literally) the...,https://www.nytimes.com/2026/10/27/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2411/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
33        trump     34
87     election     31
86       israel     21
149  california     12
131        will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
335,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...,103
8,2026-10-28-03-20-04 +0000,startribune,Exit polls suggest no clear winner in Israel's...,https://www.startribune.com/voters-in-israel-w...,101
163,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,100
10,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...,88
32,2026-10-28-01-59-00 +0000,wsj,Early Israeli Exit Polls Show No Clear Winner ...,https://www.wsj.com/world/middle-east/israel-e...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
335,103,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...
10,88,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...
81,55,2026-10-27-23-40-43 +0000,nypost,Ex-FBI official weeps as she appears in court ...,https://nypost.com/2026/10/27/us-news/ex-fbi-o...
296,54,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
370,52,2026-10-27-10-00-00 +0000,wsj,Fed Chairman Kevin Warsh wants to stop preview...,https://www.wsj.com/economy/central-banking/ke...
381,51,2026-10-27-09-21-34 +0000,wsj,"Stock Market News, Oct. 27, 2026: Tech Stocks ...",https://www.wsj.com/livecoverage/stock-market-...
6,45,2026-10-28-03-27-41 +0000,nypost,LAPD Chief Jim McDonnell slams Nithya Raman’s ...,https://nypost.com/2026/10/27/us-news/lapd-chi...
409,42,2026-10-27-04-07-00 +0000,wsj,Judge Ana Reyes issued a preliminary injunctio...,https://www.wsj.com/politics/policy/judge-bars...
400,40,2026-10-27-06-59-20 +0000,nyt,Flurry of Diplomacy in Iran Amid Reports of U....,https://www.nytimes.com/2026/10/26/world/middl...
307,40,2026-10-27-13-00-00 +0000,nypost,Katie Zacharia reveals lesson her brief White ...,https://nypost.com/2026/10/27/us-news/katie-za...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)