## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-05-35-38 +0000,nypost,Finnish Air Force cadets under fire for drawin...,https://nypost.com/2026/04/22/world-news/finla...
1,2026-04-22-05-31-00 +0000,wsj,Nordea Backs Guidance Despite Market Uncertainty,https://www.wsj.com/business/earnings/nordea-b...
2,2026-04-22-05-29-53 +0000,nyt,War Shock in Asia,https://www.nytimes.com/2026/04/21/world/iran-...
3,2026-04-22-05-28-01 +0000,bbc,"Starmer sends 'chill' through civil service, u...",https://www.bbc.com/news/articles/c1krxlvjezro...
4,2026-04-22-05-24-32 +0000,bbc,Price rise contingency plans 'ready if needed',https://www.bbc.com/news/articles/cd9v4j27nzjo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
40      trump     38
37       iran     36
389       new     21
183  virginia     16
44         up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
237,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,175
5,2026-04-22-05-23-23 +0000,nyt,Iran War Live Updates: Trump Extends Cease-Fir...,https://www.nytimes.com/live/2026/04/21/world/...,154
80,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,138
61,2026-04-22-01-18-36 +0000,bbc,Oil prices dip as Trump extends Iran war cease...,https://www.bbc.com/news/articles/c995dkl4dvvo...,117
327,2026-04-21-13-14-14 +0000,nypost,Trump doesn’t want to extend Iran cease-fire —...,https://nypost.com/2026/04/21/us-news/trump-do...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
237,175,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
132,66,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
402,64,2026-04-21-05-57-56 +0000,bbc,New era as Apple names new boss to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
39,61,2026-04-22-02-30-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
299,51,2026-04-21-14-52-47 +0000,cbc,"2 Palestinians, including 14-year-old, killed ...",https://www.cbc.ca/news/world/palestinians-kil...
231,46,2026-04-21-18-15-31 +0000,nypost,Rep. Sheila Cherfilus-McCormick resigns from C...,https://nypost.com/2026/04/21/us-news/rep-shei...
114,44,2026-04-21-22-47-02 +0000,nypost,UK PM Starmer gets support from Trump as he fa...,https://nypost.com/2026/04/21/us-news/uk-pm-st...
44,38,2026-04-22-02-22-51 +0000,nypost,NYPD identifies teen who allegedly gunned down...,https://nypost.com/2026/04/21/us-news/nypd-ide...
26,37,2026-04-22-03-11-57 +0000,bbc,Mexico officials say Teotihuacán gunman carrie...,https://www.bbc.com/news/articles/c393mped8zjo...
50,36,2026-04-22-01-58-00 +0000,wsj,President Trump’s pick to lead the Federal Res...,https://www.wsj.com/economy/central-banking/wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)