## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...
1,2026-03-23-13-15-42 +0000,bbc,Oil falls and shares rebound after Trump says ...,https://www.bbc.com/news/articles/czex56kwxxzo...
2,2026-03-23-13-15-04 +0000,nyt,Flights Grounded at LaGuardia Airport as New Y...,https://www.nytimes.com/live/2026/03/23/nyregi...
3,2026-03-23-13-13-41 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/23/us/sup...
4,2026-03-23-13-13-00 +0000,wsj,"‘Stop, Stop, Stop’: LaGuardia Airport Closed A...",https://www.wsj.com/us-news/faa-issues-ground-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
8   trump     38
12   iran     34
22    war     18
27    new     17
13  power     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-03-23-13-07-22 +0000,nyt,Iran War Live Updates: Trump Says U.S. and Ira...,https://www.nytimes.com/live/2026/03/23/world/...,141
132,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...,130
27,2026-03-23-12-25-03 +0000,startribune,US will hold off on Iran power plant strikes f...,https://www.startribune.com/iran-threatens-to-...,126
204,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,125
0,2026-03-23-13-16-13 +0000,nypost,"Dow futures rally nearly 1,000 points, oil tum...",https://nypost.com/2026/03/23/business/dow-fut...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,141,2026-03-23-13-07-22 +0000,nyt,Iran War Live Updates: Trump Says U.S. and Ira...,https://www.nytimes.com/live/2026/03/23/world/...
97,70,2026-03-23-08-52-19 +0000,cbc,2 pilots killed after Air Canada plane collide...,https://www.cbc.ca/news/world/livestory/air-ca...
129,64,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
132,58,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...
150,42,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...
68,39,2026-03-23-10-00-00 +0000,latimes,Data centers under scrutiny by California lawm...,https://www.latimes.com/california/story/2026-...
251,34,2026-03-22-14-00-00 +0000,wsj,Small truck drivers in the U.S. are feeling so...,https://www.wsj.com/economy/truckers-are-the-f...
209,34,2026-03-22-18-05-10 +0000,nyt,Residents in Southern Israel Are Shaken After ...,https://www.nytimes.com/2026/03/22/world/middl...
243,31,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
32,27,2026-03-23-12-12-49 +0000,nyt,London Arson Attack on Jewish Ambulance Servic...,https://www.nytimes.com/2026/03/23/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)