## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-30-23-07-00 +0000,bbc,'There were letters I didn't want to open': Ri...,https://www.bbc.com/news/articles/cwy2ldl1k7do...
1,2026-04-30-23-06-00 +0000,wsj,President Trump is withdrawing his nomination ...,https://www.wsj.com/politics/policy/trump-with...
2,2026-04-30-23-05-56 +0000,wapo,"Direct flights to Venezuela resume, but many s...",https://www.washingtonpost.com/world/2026/04/3...
3,2026-04-30-23-04-43 +0000,bbc,Apple hails 'extraordinary' iPhone demand as b...,https://www.bbc.com/news/articles/ce8pdk3l4d2o...
4,2026-04-30-23-03-08 +0000,bbc,Heating oil prices reached record high in NI,https://www.bbc.com/news/articles/crlp818ppp1o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2646/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     49
233   iran     31
80     new     27
244  house     20
310    war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
76,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...,165
314,2026-04-30-10-43-45 +0000,nypost,Oil prices briefly hit wartime high as Trump w...,https://nypost.com/2026/04/30/us-news/oil-pric...,163
386,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...,159
167,2026-04-30-18-05-26 +0000,bbc,Oil price hits highest since 2022 after report...,https://www.bbc.com/news/articles/cx21m88rd14o...,144
55,2026-04-30-21-46-00 +0000,wsj,President Trump said he would remove tariffs o...,https://www.wsj.com/economy/trade/trump-says-u...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
76,165,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...
314,114,2026-04-30-10-43-45 +0000,nypost,Oil prices briefly hit wartime high as Trump w...,https://nypost.com/2026/04/30/us-news/oil-pric...
221,75,2026-04-30-16-22-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
329,68,2026-04-30-09-30-00 +0000,wsj,"If these were normal times, Jerome Powell woul...",https://www.wsj.com/economy/central-banking/wh...
400,64,2026-04-29-23-48-07 +0000,latimes,5-year-old was brutally and repeatedly beaten ...,https://www.latimes.com/california/story/2026-...
228,61,2026-04-30-16-00-00 +0000,wsj,The Justice Department is launching a West Coa...,https://www.wsj.com/politics/policy/doj-launch...
386,54,2026-04-30-01-14-00 +0000,wsj,President Trump is leaning toward endorsing Re...,https://www.wsj.com/politics/elections/trump-l...
126,52,2026-04-30-19-56-03 +0000,nyt,Supreme Court Voting Rights Ruling Could Fuel ...,https://www.nytimes.com/2026/04/30/us/politics...
55,43,2026-04-30-21-46-00 +0000,wsj,President Trump said he would remove tariffs o...,https://www.wsj.com/economy/trade/trump-says-u...
143,41,2026-04-30-19-14-39 +0000,nypost,Small border town goes to war with California ...,https://nypost.com/2026/04/30/us-news/el-cajon...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)