## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-11-01-20-54-17 +0000,startribune,Live: Unbeaten Vikings trail Lions late after ...,https://www.startribune.com/minnesota-vikings-...
1,2026-11-01-20-53-53 +0000,startribune,Live: Wild jump out to early lead against Capi...,https://www.startribune.com/minnesota-wild-was...
2,2026-11-01-20-45-44 +0000,nyt,A Lesson From Germany,https://www.nytimes.com/2026/11/01/world/germa...
3,2026-11-01-20-44-57 +0000,nyt,9 Aboard a Small Plane That Crashed in Florida...,https://www.nytimes.com/2026/11/01/us/florida-...
4,2026-11-01-20-43-55 +0000,nypost,NYC crushes kid-led effort pushing for stop li...,https://nypost.com/2026/11/01/us-news/nyc-crus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2654/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
211   trump     24
104    race     13
103  senate     12
26      nyc     11
84   alaska     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
24,2026-11-01-19-44-11 +0000,nyt,Judge Rejects Trump Officials’ Move to Challen...,https://www.nytimes.com/2026/11/01/us/alaska-s...,68
45,2026-11-01-18-25-38 +0000,chitri,Democrat Haley Stevens endorses GOP’s Mike Rog...,https://www.chicagotribune.com/2026/11/01/demo...,68
201,2026-10-31-21-22-42 +0000,nypost,Trump ask to set aside ‘Decoy Dan’ Alaska Sena...,https://nypost.com/2026/10/31/us-news/trump-as...,64
48,2026-11-01-18-05-27 +0000,chitri,Judge dismisses lawsuit seeking to block certi...,https://www.chicagotribune.com/2026/11/01/laws...,60
19,2026-11-01-20-00-00 +0000,wsj,"In the Florida governor’s race, Democrat David...",https://www.wsj.com/politics/elections/democra...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
24,68,2026-11-01-19-44-11 +0000,nyt,Judge Rejects Trump Officials’ Move to Challen...,https://www.nytimes.com/2026/11/01/us/alaska-s...
19,57,2026-11-01-20-00-00 +0000,wsj,"In the Florida governor’s race, Democrat David...",https://www.wsj.com/politics/elections/democra...
18,49,2026-11-01-20-02-00 +0000,wsj,Maybe the Democrats win big Tuesday. But the p...,https://www.wsj.com/politics/policy/democrats-...
59,43,2026-11-01-17-37-01 +0000,nypost,Abdul El-Sayed’s ex-Dem opponent Rep. Haley St...,https://nypost.com/2026/11/01/us-news/abdul-el...
43,41,2026-11-01-18-29-00 +0000,wsj,"Sen. Chris Murphy of Connecticut, a rising sta...",https://www.wsj.com/politics/sen-chris-murphy-...
51,33,2026-11-01-17-59-51 +0000,nypost,Diehard fans pack near loneliest stretch of NY...,https://nypost.com/2026/11/01/us-news/diehard-...
90,28,2026-11-01-15-46-13 +0000,nypost,‘Gen Z Takes Charge’ protests across Germany t...,https://nypost.com/2026/11/01/world-news/gen-z...
148,28,2026-11-01-07-26-18 +0000,nypost,FBI visits ‘Decoy Dan’ Sullivan donors as feds...,https://nypost.com/2026/11/01/us-news/alaska-s...
95,26,2026-11-01-15-15-00 +0000,wsj,Voters head to the polls on Tuesday as benefic...,https://www.wsj.com/economy/us-economic-data-g...
127,26,2026-11-01-10-30-00 +0000,wsj,It’s the most expensive election in history. T...,https://www.wsj.com/politics/elections/midterm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)