## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-20-42-00 +0000,nypost,Justice Department opens sweeping ‘debanking’ ...,https://nypost.com/2026/06/10/business/justice...
1,2026-06-10-20-39-04 +0000,nypost,Jalen Brunson adopted his social media famous ...,https://nypost.com/2026/06/10/us-news/jalen-br...
2,2026-06-10-20-37-44 +0000,nypost,Fresh hell for California baseball star Daniel...,https://nypost.com/2026/06/10/us-news/fresh-he...
3,2026-06-10-20-31-27 +0000,nyt,Pro-Palestinian Activists at U. of Michigan In...,https://www.nytimes.com/2026/06/10/us/universi...
4,2026-06-10-20-29-00 +0000,wsj,Oracle Reports Higher Profit on Surging Cloud ...,https://www.wsj.com/business/earnings/oracle-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
63   trump     42
99    iran     25
217  world     22
110    new     19
52      he     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-06-10-16-25-02 +0000,nypost,Trump tells Post why he said ‘I love the infla...,https://nypost.com/2026/06/10/us-news/trump-br...,148
11,2026-06-10-20-13-42 +0000,nyt,Iran War Live Updates: A Day After Predicting ...,https://www.nytimes.com/live/2026/06/10/world/...,130
169,2026-06-10-15-00-57 +0000,cbc,How Donald Trump is making the FIFA World Cup ...,https://www.cbc.ca/news/politics/donald-trump-...,129
308,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,125
111,2026-06-10-17-08-44 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,148,2026-06-10-16-25-02 +0000,nypost,Trump tells Post why he said ‘I love the infla...,https://nypost.com/2026/06/10/us-news/trump-br...
308,92,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
165,80,2026-06-10-15-13-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
28,78,2026-06-10-19-46-56 +0000,cbc,FIFA president defends World Cup ticket prices...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
237,73,2026-06-10-10-52-26 +0000,bbc,"Graham Platner wins Maine primary, setting up ...",https://www.bbc.com/news/articles/c79yzzvddnlo...
43,63,2026-06-10-19-27-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...
345,53,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
221,48,2026-06-10-11-44-08 +0000,nypost,President Trump readying new strikes on Irania...,https://nypost.com/2026/06/10/us-news/presiden...
124,38,2026-06-10-16-40-31 +0000,nypost,All military personnel killed when Pakistan ar...,https://nypost.com/2026/06/10/world-news/all-o...
160,37,2026-06-10-15-28-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)