## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-20-11-01-14 +0000,nypost,California clan that swindled $18M from COVID ...,https://nypost.com/2026/08/20/us-news/californ...
1,2026-08-20-11-00-21 +0000,chitri,Today in Chicago History: First segment of the...,https://www.chicagotribune.com/2026/08/20/augu...
2,2026-08-20-11-00-00 +0000,wsj,Rainmakers in Talks to Leave Weil Gotshal Amid...,https://www.wsj.com/business/rainmakers-in-tal...
3,2026-08-20-11-00-00 +0000,wsj,"U.S. Considers Tariff Cuts on Metals, Autos in...",https://www.wsj.com/logistics-report/u-s-consi...
4,2026-08-20-11-00-00 +0000,nypost,"For decades, most American teens worked summer...",https://nypost.com/2026/08/20/us-news/only-a-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2488/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
60   trump     61
184    new     22
62    iran     17
141     up     17
243     ai     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
143,2026-08-20-01-56-53 +0000,nypost,Trump announces ‘Economic D-Day’ against Iran:...,https://nypost.com/2026/08/19/us-news/trump-an...,128
72,2026-08-20-09-04-00 +0000,wsj,Oil Gains Further as Trump Threatens to Launch...,https://www.wsj.com/finance/commodities-future...,127
80,2026-08-20-09-00-00 +0000,wsj,Trump’s half-built White House ballroom is a 9...,https://www.wsj.com/politics/policy/build-firs...,124
354,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...,123
231,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
143,128,2026-08-20-01-56-53 +0000,nypost,Trump announces ‘Economic D-Day’ against Iran:...,https://nypost.com/2026/08/19/us-news/trump-an...
56,90,2026-08-20-09-30-00 +0000,wsj,After 66-year-old Lynn Lee was laid off last y...,https://www.wsj.com/lifestyle/careers/the-66-y...
337,73,2026-08-19-16-34-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...
354,62,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
231,61,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
106,54,2026-08-20-06-42-55 +0000,nypost,"Illegal immigrant, 19, killed co-worker he had...",https://nypost.com/2026/08/20/us-news/salvador...
307,51,2026-08-19-17-53-08 +0000,wapo,"Bond yields fall, markets rally after Treasury...",https://www.washingtonpost.com/business/2026/0...
18,48,2026-08-20-10-30-52 +0000,wapo,Prince Harry and Meghan Markle will return to ...,https://www.washingtonpost.com/world/2026/08/1...
96,45,2026-08-20-08-00-00 +0000,cbc,Ex-defence minister's call for a wartime elect...,https://www.cbc.ca/news/world/zelenskyy-fedoro...
244,44,2026-08-19-20-18-49 +0000,nyt,Israel Opens Criminal Investigation Into Killi...,https://www.nytimes.com/2026/08/19/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)