## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-16-19-57-57 +0000,nypost,Brother of dead NFL war hero Pat Tillman learn...,https://nypost.com/2026/06/16/us-news/pat-till...
1,2026-06-16-19-54-13 +0000,nypost,Netflix eyes Lionsgate after losing to Fox on ...,https://nypost.com/2026/06/16/media/netflix-ey...
2,2026-06-16-19-54-00 +0000,nyt,Iran War Live Updates: Trump Says He Hopes to ...,https://www.nytimes.com/live/2026/06/16/world/...
3,2026-06-16-19-53-58 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/16/world/...
4,2026-06-16-19-53-44 +0000,nyt,"Ebola Outbreak Could Become Worst on Record, A...",https://www.nytimes.com/2026/06/16/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
25   trump     52
22    iran     44
20    deal     35
135    new     22
3      war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...,172
142,2026-06-16-14-52-36 +0000,nypost,Trump says he’ll read the text of Iran deal al...,https://nypost.com/2026/06/16/us-news/trump-sa...,160
137,2026-06-16-15-06-14 +0000,nypost,Trump admin rejected Israel’s request to see I...,https://nypost.com/2026/06/16/us-news/trump-ad...,155
251,2026-06-16-08-07-32 +0000,bbc,"Trump may release US-Iran deal before Friday, ...",https://www.bbc.com/news/articles/ce8mv6l6eezo...,154
286,2026-06-16-01-00-00 +0000,wsj,The Race to Land an Iran Deal Loomed Large Beh...,https://www.wsj.com/world/middle-east/trump-ir...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,172,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...
260,75,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
290,69,2026-06-16-00-57-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
102,64,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
89,55,2026-06-16-17-14-32 +0000,nypost,Terrified woman backed out of bungee jump mome...,https://nypost.com/2026/06/16/world-news/woman...
303,48,2026-06-15-23-29-08 +0000,cbc,Ghana takes Thomas Partey's World Cup entry fi...,https://www.cbc.ca/sports/soccer/worldcup/thom...
204,48,2026-06-16-10-38-31 +0000,nypost,FBI arrests 5 people in connection with drone ...,https://nypost.com/2026/06/16/us-news/fbi-arre...
230,42,2026-06-16-09-42-29 +0000,nypost,Macron tells Zelensky he had ‘difficult’ meeti...,https://nypost.com/2026/06/16/us-news/macron-s...
13,37,2026-06-16-19-32-43 +0000,nypost,Spencer Pratt sounds off on ‘commie’ architect...,https://nypost.com/2026/06/16/us-news/spencer-...
353,36,2026-06-15-20-42-05 +0000,nypost,SpaceX shares jump 20% in first full day of tr...,https://nypost.com/2026/06/15/business/spacex-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)