## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-16-24-50 +0000,bbc,Two killed and many injured after car driven i...,https://www.bbc.com/news/articles/ckgpzgxgz58o...
1,2026-05-04-16-21-13 +0000,nyt,What to Know About Elections in West Bengal an...,https://www.nytimes.com/2026/05/03/world/asia/...
2,2026-05-04-16-15-05 +0000,nyt,Europeans Prepare for a More Dangerous World i...,https://www.nytimes.com/2026/05/04/business/po...
3,2026-05-04-16-14-48 +0000,bbc,At least 23 injured in shooting at lake party ...,https://www.bbc.com/news/articles/cnvp3lnegqdo...
4,2026-05-04-16-14-41 +0000,nyt,Iran War Live Updates: Uncertainty Over Strait...,https://www.nytimes.com/live/2026/05/04/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2610/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
52   trump     28
28    iran     21
38  hormuz     15
33  strait     13
62    ship     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
64,2026-05-04-13-34-48 +0000,nyt,Oil Jumps as Iran Resists Trump’s Offer to Hel...,https://www.nytimes.com/2026/05/03/business/oi...,109
114,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...,105
205,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,95
223,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...,94
248,2026-05-03-16-49-30 +0000,cbc,Trump says operation will start Monday to help...,https://www.cbc.ca/news/world/cargo-ship-strai...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
64,109,2026-05-04-13-34-48 +0000,nyt,Oil Jumps as Iran Resists Trump’s Offer to Hel...,https://www.nytimes.com/2026/05/03/business/oi...
204,64,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
107,44,2026-05-04-11-00-00 +0000,nypost,NYC Italian enclaves left out of the party as ...,https://nypost.com/2026/05/04/us-news/nyc-ital...
34,35,2026-05-04-15-10-57 +0000,nypost,Ex-NYC Mayor Rudy Giuliani remains hospitalize...,https://nypost.com/2026/05/04/us-news/ex-nyc-m...
136,35,2026-05-04-09-02-13 +0000,nypost,House Democrats add eight new battleground tar...,https://nypost.com/2026/05/04/us-news/house-de...
29,34,2026-05-04-15-22-38 +0000,nypost,Supreme Court restores access to abortion pill...,https://nypost.com/2026/05/04/us-news/supreme-...
135,34,2026-05-04-09-04-37 +0000,bbc,One injured after plane hits truck while landi...,https://www.bbc.com/news/articles/cp8p3r8dek1o...
69,31,2026-05-04-13-24-04 +0000,nypost,"My darling boy was slain in cold blood. Now, t...",https://nypost.com/2026/05/04/us-news/grieving...
53,25,2026-05-04-14-17-47 +0000,nyt,How the Kremlin Lures Africans Into Russia’s W...,https://www.nytimes.com/2026/05/04/world/afric...
180,25,2026-05-04-00-56-53 +0000,nypost,WHCD shooting suspect Cole Allen no longer on ...,https://nypost.com/2026/05/03/world-news/whcd-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)