## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-29-13-10-10 +0000,nypost,Pope Leo issues strong rebuke on ‘atrocious’ I...,https://nypost.com/2026/03/29/world-news/pope-...
1,2026-03-29-13-05-02 +0000,startribune,Iran warns US against ground invasion as regio...,https://www.startribune.com/iran-backed-houthi...
2,2026-03-29-13-00-00 +0000,missionlocal,iCero miedo!,https://missionlocal.org/2026/03/icero-miedo/
3,2026-03-29-13-00-00 +0000,missionlocal,‘I want to see her back:’ District 9 closes ra...,https://missionlocal.org/2026/03/sf-jackie-fie...
4,2026-03-29-12-58-05 +0000,nyt,Iran War Live Updates: Israel Strikes Tehran a...,https://www.nytimes.com/live/2026/03/29/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7      war     22
169  trump     21
6     iran     21
201     no     16
202  kings     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...,115
130,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...,87
82,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...,83
125,2026-03-28-19-05-10 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,74
59,2026-03-29-04-11-27 +0000,bbc,No Kings protesters across the US rally agains...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,115,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...
58,33,2026-03-29-05-36-10 +0000,nypost,Thousands of New York’s Finest turn out for ‘T...,https://nypost.com/2026/03/29/us-news/thousand...
111,28,2026-03-28-20-02-09 +0000,wapo,Iranian-backed Houthis in Yemen attack Israel ...,https://www.washingtonpost.com/world/2026/03/2...
68,28,2026-03-29-02-31-01 +0000,nypost,Hundreds pack NYC suburb to remember Loyola Un...,https://nypost.com/2026/03/28/us-news/hundreds...
97,26,2026-03-28-23-00-00 +0000,wsj,President Trump’s tax cuts are delivering bigg...,https://www.wsj.com/politics/policy/trump-salt...
92,26,2026-03-28-23-37-16 +0000,nypost,JD Vance wins 2028 CPAC GOP presidential straw...,https://nypost.com/2026/03/28/us-news/rubio-cu...
28,24,2026-03-29-09-30-00 +0000,wsj,Fed policymakers suggest interest rates could ...,https://www.wsj.com/economy/central-banking/fe...
89,22,2026-03-29-00-00-00 +0000,wsj,Investigators searched the office of a FEMA co...,https://www.wsj.com/politics/national-security...
144,22,2026-03-28-16-44-11 +0000,nyt,Bank of America to Pay $72.5 Million to Settle...,https://www.nytimes.com/2026/03/27/business/ba...
71,22,2026-03-29-01-40-32 +0000,nypost,Wild San Francisco street fight shows young pu...,https://nypost.com/2026/03/28/us-news/wild-san...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)