## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-18-20-37 +0000,nypost,Shocking twist as legal fight over $12.8M winn...,https://nypost.com/2026/06/26/us-news/shocking...
1,2026-06-26-18-17-19 +0000,nyt,N.M. Governor Asks for Criminal Investigation ...,https://www.nytimes.com/2026/06/26/us/new-mexi...
2,2026-06-26-18-16-40 +0000,nyt,Congressional Panel Investigating Epstein Subp...,https://www.nytimes.com/2026/06/26/business/le...
3,2026-06-26-18-15-53 +0000,nyt,Venezuela Live Updates: Rescuers Search for Qu...,https://www.nytimes.com/live/2026/06/26/world/...
4,2026-06-26-18-14-36 +0000,bbc,Europe's deadly heatwave breaks German record ...,https://www.bbc.co.uk/news/articles/cx2knzzwpr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
80       trump     33
287        new     23
21   venezuela     20
82        iran     16
309      court     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
70,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...,100
36,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...,96
11,2026-06-26-18-03-32 +0000,bbc,Trump accuses Iran of ceasefire breach after S...,https://www.bbc.co.uk/news/articles/ckg54g0ry0...,82
303,2026-06-25-22-10-20 +0000,nyt,Supreme Court Expands Trump’s Power Over Immig...,https://www.nytimes.com/2026/06/25/us/politics...,82
277,2026-06-25-23-40-00 +0000,wsj,"Iran Attacks Cargo Ship, Testing Trump’s Deal ...",https://www.wsj.com/world/middle-east/iran-att...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
70,100,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...
49,80,2026-06-26-17-00-00 +0000,wsj,The search for a new leader of the Federal Res...,https://www.wsj.com/economy/central-banking/at...
256,78,2026-06-26-01-08-00 +0000,wsj,California’s proposed billionaire tax will app...,https://www.wsj.com/politics/policy/california...
366,57,2026-06-25-18-59-18 +0000,nyt,Supreme Court Rejects Lawsuit Against Bayer Al...,https://www.nytimes.com/2026/06/25/us/politics...
18,55,2026-06-26-17-56-15 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/2026/06/25/world/ameri...
66,49,2026-06-26-16-26-28 +0000,nypost,Ex-’60 Minutes’ boss Bill Owens blasts Paramou...,https://nypost.com/2026/06/26/media/ex-60-minu...
22,48,2026-06-26-17-48-34 +0000,nyt,"John Bolton, Former Trump Adviser, Pleads Guil...",https://www.nytimes.com/2026/06/26/us/politics...
217,46,2026-06-26-08-11-08 +0000,nypost,Saudi doctor sentenced to life in prison for d...,https://nypost.com/2026/06/26/world-news/saudi...
32,41,2026-06-26-17-21-00 +0000,wsj,Vice President JD Vance compared himself to fo...,https://www.wsj.com/politics/policy/jd-vance-c...
326,41,2026-06-25-21-08-00 +0000,wsj,Oil Prices Make a Stunning Retreat to Prewar L...,https://www.wsj.com/business/energy-oil/oil-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)