## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-23-15-45-27 +0000,nypost,Mystery as San Francisco supervisor suddenly r...,https://nypost.com/2026/06/23/us-news/san-fran...
1,2026-06-23-15-40-23 +0000,nyt,Ferraris and Shell Companies: Five Charged in ...,https://www.nytimes.com/2026/06/23/us/skin-sub...
2,2026-06-23-15-40-15 +0000,nypost,Supreme Court sides with Trump admin in green ...,https://nypost.com/2026/06/23/us-news/immigrat...
3,2026-06-23-15-38-42 +0000,nypost,Supreme Court bars Rastafari man from suing Lo...,https://nypost.com/2026/06/23/us-news/supreme-...
4,2026-06-23-15-37-55 +0000,nypost,‘Columbine-obsessed’ gunman who shot 2 dead in...,https://nypost.com/2026/06/23/us-news/teen-cal...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2456/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
24     trump     31
90      iran     30
353      new     18
120     will     15
202  starmer     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
209,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...,88
49,2026-06-23-14-23-41 +0000,nyt,How Will Colombia’s New President Fuel Trump’s...,https://www.nytimes.com/2026/06/22/world/ameri...,84
225,2026-06-22-21-51-37 +0000,bbc,What does Trump want from a new UK prime minis...,https://www.bbc.co.uk/news/videos/c2kyz2eqxwvo...,77
274,2026-06-22-19-24-12 +0000,nypost,MAGA base fractures over how Trump ended the I...,https://nypost.com/2026/06/22/us-news/maga-bas...,75
215,2026-06-22-22-47-27 +0000,nyt,Iran Team Leaves Locker Room Note: The ‘Spirit...,https://www.nytimes.com/2026/06/22/world/middl...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
209,88,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...
215,74,2026-06-22-22-47-27 +0000,nyt,Iran Team Leaves Locker Room Note: The ‘Spirit...,https://www.nytimes.com/2026/06/22/world/middl...
136,71,2026-06-23-09-48-33 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
312,53,2026-06-22-17-17-00 +0000,wsj,Supreme Court Reinstates Conviction in Murder ...,https://www.wsj.com/us-news/law/scotus-etan-pa...
71,47,2026-06-23-13-29-09 +0000,nypost,"Teen gunman bursts into California library, sh...",https://nypost.com/2026/06/23/us-news/18-year-...
159,46,2026-06-23-08-11-00 +0000,wsj,Stock Market Today: AI Spending Jitters Drag T...,https://www.wsj.com/livecoverage/stock-market-...
279,43,2026-06-22-19-08-00 +0000,bbc,Messi becomes World Cup all-time leading score...,https://www.bbc.co.uk/sport/football/articles/...
301,42,2026-06-22-17-38-00 +0000,wsj,Alan Greenspan’s legacy explained: how the Fed...,https://www.wsj.com/economy/central-banking/al...
153,39,2026-06-23-09-00-00 +0000,wsj,A generational battle is playing out in the De...,https://www.wsj.com/politics/elections/the-gen...
265,37,2026-06-22-20-10-53 +0000,nyt,Oil Prices Fall as U.S.-Iran Talks Show Signs ...,https://www.nytimes.com/2026/06/22/business/oi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)