## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-07-02-00 +0000,wsj,DHL Parent Deutsche Post Expects Earnings Grow...,https://www.wsj.com/business/earnings/dhl-pare...
1,2026-03-05-06-52-41 +0000,nypost,California ‘Party Mom’ learns fate for hosting...,https://nypost.com/2026/03/05/us-news/californ...
2,2026-03-05-06-52-36 +0000,bbc,"US sub sinks Iranian warship in Indian Ocean, ...",https://www.bbc.com/news/articles/c0e55g03v2zo...
3,2026-03-05-06-49-00 +0000,wsj,Dollar Strength Could Continue Weighing on Gold,https://www.wsj.com/finance/commodities-future...
4,2026-03-05-06-48-39 +0000,nyt,Live Updates: Senate Republicans Block War Pow...,https://www.nytimes.com/live/2026/03/04/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2624/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
97    iran     74
38     war     42
154  trump     36
175  texas     22
171    new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...,193
364,2026-03-04-13-53-32 +0000,cbc,Two Blocks from the White House: Trump’s ‘no r...,https://www.cbc.ca/news/politics/two-blocks-fr...,184
119,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,179
22,2026-03-05-05-07-21 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,179
286,2026-03-04-17-49-43 +0000,nypost,US lawmakers to vote on war powers resolution ...,https://nypost.com/2026/03/04/world-news/us-la...,178

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,193,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...
342,124,2026-03-04-15-10-00 +0000,wsj,Incumbent Sen. John Cornyn and Texas Attorney ...,https://www.wsj.com/politics/elections/john-co...
334,74,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
60,65,2026-03-05-02-17-10 +0000,nypost,Two remaining soldiers killed in Iranian drone...,https://nypost.com/2026/03/04/world-news/two-r...
271,63,2026-03-04-18-19-00 +0000,wsj,Global authorities must step up their surveill...,https://www.wsj.com/economy/central-banking/re...
62,61,2026-03-05-02-15-00 +0000,wsj,"Sen. Steve Daines of Montana, a close ally of ...",https://www.wsj.com/politics/elections/trump-a...
132,59,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...
399,47,2026-03-04-11-00-00 +0000,wapo,Trump voucher offers new money for public scho...,https://www.washingtonpost.com/education/2026/...
48,46,2026-03-05-03-06-11 +0000,nyt,Several of Labor Secretary Lori Chavez-DeRemer...,https://www.nytimes.com/2026/03/04/business/ec...
329,45,2026-03-04-15-55-00 +0000,wsj,GOP Rep. Dan Crenshaw became the first House i...,https://www.wsj.com/politics/elections/rep-dan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)