## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-21-00-00 +0000,bbc,Free Thinking,https://www.bbc.co.uk/sounds/play/live:bbc_rad...
1,2026-06-05-20-30-38 +0000,nyt,"Anthony Head, ‘Buffy the Vampire Slayer’ and ‘...",https://www.nytimes.com/2026/06/05/arts/televi...
2,2026-06-05-20-24-52 +0000,nypost,Karmelo Anthony asked to leave ‘15 times’ befo...,https://nypost.com/2026/06/05/us-news/karmelo-...
3,2026-06-05-20-21-38 +0000,nyt,Stocks Slide as Investors See Rates Rising Aft...,https://www.nytimes.com/2026/06/05/business/st...
4,2026-06-05-20-21-00 +0000,wsj,Strong Job Growth Weakens Stocks,https://www.wsj.com/finance/stocks/strong-job-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2575/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
137       trump     32
213         new     16
188      market     15
477  california     14
59           ai     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
41,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,99
84,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,92
93,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,84
275,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...,79
61,2026-06-05-18-17-24 +0000,nypost,Trump must ‘accept the reality’ there is no I...,https://nypost.com/2026/06/05/world-news/jack-...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
41,99,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
163,65,2026-06-05-13-47-48 +0000,nypost,"Graham Platner, Susan Collins tied in Maine Se...",https://nypost.com/2026/06/05/us-news/graham-p...
281,57,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
62,51,2026-06-05-18-16-15 +0000,bbc,Putin says there is 'no point' meeting Zelensk...,https://www.bbc.com/news/articles/cpqpqx5qe40o...
245,47,2026-06-05-08-27-21 +0000,wsj,Stock Market Today: Tech Stocks Sell Off as Ra...,https://www.wsj.com/livecoverage/may-jobs-repo...
275,40,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...
289,40,2026-06-05-00-05-45 +0000,nypost,Anthropic calls for global AI slowdown after $...,https://nypost.com/2026/06/04/business/anthrop...
140,38,2026-06-05-15-19-52 +0000,nypost,"Iran declares support for Hezbollah, demands I...",https://nypost.com/2026/06/05/world-news/iran-...
240,36,2026-06-05-08-56-17 +0000,cbc,Chinese leader Xi Jinping to visit North Korea...,https://www.cbc.ca/news/world/xi-jinping-north...
123,33,2026-06-05-15-58-12 +0000,nypost,Ex-Prince Andrew made money subletting 3 cotta...,https://nypost.com/2026/06/05/world-news/ex-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)