## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-17-13-05-00 +0000,wsj,New York Manufacturing Activity Accelerates in...,https://www.wsj.com/economy/central-banking/ne...
1,2026-08-17-13-04-30 +0000,nyt,Islamophobia’s Rise in Texas: ‘I Won’t Rest Un...,https://www.nytimes.com/2026/08/17/us/politics...
2,2026-08-17-13-03-03 +0000,chitri,The 60-day deadline for an Iran peace deal is ...,https://www.chicagotribune.com/2026/08/17/iran...
3,2026-08-17-13-01-07 +0000,chitri,Minnesota state senator went to bed thinking h...,https://www.chicagotribune.com/2026/08/17/mn-s...
4,2026-08-17-13-00-00 +0000,wapo,Want to know what people really think? Get the...,https://www.washingtonpost.com/politics/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2659/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
54   trump     33
17    iran     16
0      new     14
29      he     12
275    war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
67,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,122
245,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...,113
120,2026-08-17-06-24-31 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,108
153,2026-08-17-00-20-54 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,86
175,2026-08-16-21-57-01 +0000,nypost,Trump instructs Pentagon to reduce military ex...,https://nypost.com/2026/08/16/world-news/trump...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
67,122,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
45,58,2026-08-17-11-03-00 +0000,wsj,One of the most sensitive stories in this near...,https://www.wsj.com/politics/pentagon-rotates-...
229,46,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...
226,39,2026-08-16-17-50-32 +0000,chitri,US envoy Kushner meets Hamas’ leader in push f...,https://www.chicagotribune.com/2026/08/16/kush...
119,35,2026-08-17-06-49-53 +0000,nypost,"Louisiana husband allegedly killed wife, propp...",https://nypost.com/2026/08/17/us-news/louisian...
244,32,2026-08-16-15-19-52 +0000,nypost,Ex-Mamdani campaign staffer makes outrageous c...,https://nypost.com/2026/08/16/us-news/ex-mamda...
196,32,2026-08-16-19-56-39 +0000,nypost,Gavin Newsom wildfire plan faces revolt over w...,https://nypost.com/2026/08/16/us-news/gavin-ne...
162,29,2026-08-16-23-21-37 +0000,bbc,'I want my brother back' - Tupac’s brother tel...,https://www.bbc.co.uk/news/videos/cj4kglpl55lo...
245,29,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...
140,27,2026-08-17-02-00-00 +0000,wsj,"With the Iowa State Fair in full swing, Republ...",https://www.wsj.com/politics/elections/rural-e...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)