## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-09-05-25-52 +0000,startribune,Live replay: Victor Wembanyama too much for Ti...,https://www.startribune.com/live-blog-game3-mi...
1,2026-05-09-05-22-02 +0000,startribune,Sidney Morin scores twice as Frost force Game ...,https://www.startribune.com/sidney-morin-score...
2,2026-05-09-04-37-37 +0000,latimes,"Betty Broderick, convicted of killing ex-husba...",https://www.latimes.com/california/story/2026-...
3,2026-05-09-04-33-27 +0000,nypost,UFC boss Dana White reveals the rudest celebri...,https://nypost.com/2026/05/09/us-news/ufc-boss...
4,2026-05-09-04-21-58 +0000,nypost,Spencer Pratt goes coast-to-coast as billboard...,https://nypost.com/2026/05/09/us-news/spencer-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
102       trump     36
69         iran     25
26          new     22
388  hantavirus     15
70          war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,114
36,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...,94
113,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...,86
50,2026-05-09-00-05-00 +0000,wsj,President Trump and top aides are pressuring R...,https://www.wsj.com/politics/policy/trumps-tea...,85
279,2026-05-08-13-12-34 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,114,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
113,86,2026-05-08-21-23-36 +0000,nypost,JPMorgan warns $5 gas looks far more likely as...,https://nypost.com/2026/05/08/business/we-cant...
305,69,2026-05-08-11-43-45 +0000,nypost,UK PM Keir Starmer says he won’t resign after ...,https://nypost.com/2026/05/08/world-news/uk-pr...
36,65,2026-05-09-01-00-00 +0000,wsj,It’s a labor market unlike any other: Unemploy...,https://www.wsj.com/economy/jobs/job-market-un...
338,59,2026-05-08-08-50-49 +0000,cbc,Spain prepares for evacuations as hantavirus-h...,https://www.cbc.ca/news/world/cruise-ship-hant...
82,44,2026-05-08-22-34-46 +0000,bbc,Reform election gains show historic shift in B...,https://www.bbc.com/news/articles/c0r255xlr59o...
149,43,2026-05-08-20-11-51 +0000,cbc,"For Putin, Victory Day has been a time for Rus...",https://www.cbc.ca/news/world/russia-victory-d...
89,43,2026-05-08-22-15-00 +0000,wsj,Virginia’s highest court threw out Democrats’ ...,https://www.wsj.com/politics/elections/virgini...
49,40,2026-05-09-00-08-37 +0000,nypost,Tax hike on California employers spurs plea fo...,https://nypost.com/2026/05/08/us-news/tax-hike...
341,36,2026-05-08-08-43-55 +0000,bbc,Oil prices rise after US and Iran exchange fir...,https://www.bbc.com/news/articles/c86dp85g59xo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)