## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-12-05-43-14 +0000,nypost,"Former emir of Qatar, Sheikh Hamad bin Khalifa...",https://nypost.com/2026/07/12/world-news/qatar...
1,2026-07-12-05-33-31 +0000,nypost,Mick Jagger says fans don’t want political lec...,https://nypost.com/2026/07/12/us-news/mick-jag...
2,2026-07-12-05-00-15 +0000,bbc,How Aldi is taking on US supermarkets with its...,https://www.bbc.co.uk/news/articles/cly0l5d5xn...
3,2026-07-12-04-54-49 +0000,latimes,Second Antelope Valley fire burns 188 acres,https://www.latimes.com/california/story/2026-...
4,2026-07-12-04-40-09 +0000,nypost,Heartbroken daughter reveals reason plane ende...,https://nypost.com/2026/07/12/us-news/heartbro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
21    trump     23
59      new     14
49     iran     13
267   world     12
97   killed     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,90
50,2026-07-11-23-18-00 +0000,wsj,Trump Administration Subpoenas New York Times ...,https://www.wsj.com/politics/policy/trump-admi...,85
101,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,85
99,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,85
116,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,90,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
29,52,2026-07-12-01-08-40 +0000,nyt,U.S. Strikes Iran After Iran Fires on Ship in ...,https://www.nytimes.com/2026/07/11/world/middl...
105,43,2026-07-11-15-37-30 +0000,nypost,Fan collects beer from all 48 countries in Wor...,https://nypost.com/2026/07/11/sports/fan-colle...
161,40,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
65,34,2026-07-11-21-23-38 +0000,nypost,Ro Khanna blew off offer to meet former Israel...,https://nypost.com/2026/07/11/world-news/ro-kh...
92,29,2026-07-11-17-34-03 +0000,nypost,Lefty California Dem drops veiled threat to ID...,https://nypost.com/2026/07/11/us-news/californ...
15,27,2026-07-12-02-53-34 +0000,nypost,"Popular local musicians, DJ killed in fiery Ba...",https://nypost.com/2026/07/11/world-news/popul...
18,26,2026-07-12-02-19-48 +0000,nyt,Maine Democrats Will Replace Graham Platner. H...,https://www.nytimes.com/2026/07/11/us/politics...
53,23,2026-07-11-22-31-39 +0000,nypost,Ex-NJ GOP aide accused of staging slashing att...,https://nypost.com/2026/07/11/us-news/ex-nj-go...
120,23,2026-07-11-13-32-23 +0000,cbc,Typhoon Bavi makes landfall in China after bru...,https://www.cbc.ca/news/world/typhoon-bavi-eva...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)