## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-22-01-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...
1,2026-03-22-01-11-22 +0000,nyt,"Robert Mueller, Former FBI Director Who Led Tr...",https://www.nytimes.com/2026/03/21/us/politics...
2,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...
3,2026-03-22-01-00-00 +0000,wsj,Flights Are Still Taking Off as Missiles Rain ...,https://www.wsj.com/business/airlines/flights-...
4,2026-03-22-01-00-00 +0000,wsj,The Banner Year for International Stocks Has S...,https://www.wsj.com/finance/stocks/us-stocks-e...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18     trump     22
0       iran     20
1        war     13
4    iranian     11
291      bts     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...,69
89,2026-03-21-17-57-34 +0000,nypost,Trump blasts Robert Mueller after news of ex-F...,https://nypost.com/2026/03/21/us-news/trump-bl...,69
80,2026-03-21-19-06-00 +0000,wsj,"Robert Mueller, Former FBI Chief Who Led Trump...",https://www.wsj.com/us-news/law/robert-mueller...,68
0,2026-03-22-01-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...,64
53,2026-03-21-20-57-30 +0000,cbc,"Robert Mueller, 9/11-era FBI chief who later p...",https://www.cbc.ca/news/world/robert-mueller-o...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,69,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...
0,64,2026-03-22-01-15-36 +0000,nyt,Iran War Live Updates: Iranian Missiles Evade ...,https://www.nytimes.com/live/2026/03/21/world/...
75,38,2026-03-21-19-36-01 +0000,nyt,BTS’s Comeback Show Was Heavy on Their New Album,https://www.nytimes.com/live/2026/03/21/world/...
8,32,2026-03-22-00-47-52 +0000,nypost,Over 100 Israeli civilians wounded by new Ira...,https://nypost.com/2026/03/21/world-news/over-...
61,29,2026-03-21-20-27-20 +0000,nypost,Reckless driver who killed two Miami Beach spr...,https://nypost.com/2026/03/21/us-news/reckless...
194,28,2026-03-21-02-40-33 +0000,48hills,CBS workers in SF walk off the job as Bari Wei...,https://48hills.org/2026/03/cbs-workers-in-sf-...
106,27,2026-03-21-16-00-00 +0000,wsj,"Even if You’re Not Driving, You’re Probably Us...",https://www.wsj.com/business/energy-oil/even-i...
13,25,2026-03-22-00-27-45 +0000,nypost,Woman buys four winning scratch offs in one da...,https://nypost.com/2026/03/21/us-news/woman-bu...
49,25,2026-03-21-21-22-02 +0000,nypost,Extraordinary map shows how California’s extre...,https://nypost.com/2026/03/21/us-news/extraord...
78,25,2026-03-21-19-08-04 +0000,startribune,Meet the man pledging to donate $16 million to...,https://www.startribune.com/minneapolis-rent-h...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)