## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-27-17-09-38 +0000,nypost,New details of NJ teacher Ashley Fisler’s alle...,https://nypost.com/2026/03/27/us-news/new-deta...
1,2026-03-27-17-08-03 +0000,bbc,No evidence of 'family voting' in by-election,https://www.bbc.com/news/articles/clyxeqpzz2no...
2,2026-03-27-17-06-04 +0000,bbc,Asda boss rejects profiteering claims as petro...,https://www.bbc.com/news/articles/cdxdnd87v78o...
3,2026-03-27-17-05-49 +0000,nyt,"In Maine, Many Older Women Prefer Graham Platn...",https://www.nytimes.com/2026/03/27/us/graham-p...
4,2026-03-27-17-05-32 +0000,nyt,Iran War Live Updates: Tehran Moves to Assert ...,https://www.nytimes.com/live/2026/03/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2640/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
33    iran     57
137  trump     49
34     war     43
0      new     21
161   will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
169,2026-03-27-10-42-00 +0000,wsj,If there is one constant in Trump’s Washington...,https://www.wsj.com/politics/for-trump-a-deadl...,176
389,2026-03-26-18-05-00 +0000,cbc,"Iran is 'begging to make a deal' to end war, s...",https://www.cbc.ca/news/world/trump-iran-war-d...,167
16,2026-03-27-16-43-10 +0000,latimes,"Trump jokes, rants, talks price of pens as Ira...",https://www.latimes.com/world-nation/story/202...,163
275,2026-03-27-00-13-09 +0000,bbc,Three charts that are warning signs flashing f...,https://www.bbc.com/news/articles/c3w384px52no...,161
256,2026-03-27-01-00-29 +0000,nyt,"As Markets Revolt in the Face of War, Trump Ex...",https://www.nytimes.com/2026/03/26/world/middl...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
169,176,2026-03-27-10-42-00 +0000,wsj,If there is one constant in Trump’s Washington...,https://www.wsj.com/politics/for-trump-a-deadl...
7,73,2026-03-27-17-03-00 +0000,wsj,House Republican leaders on Friday rejected a ...,https://www.wsj.com/politics/policy/house-gop-...
239,66,2026-03-27-03-33-00 +0000,wsj,President Trump said he would sign an executiv...,https://www.wsj.com/politics/policy/republican...
109,63,2026-03-27-13-47-36 +0000,nypost,"Ashley Fisler, NJ teacher accused of having se...",https://nypost.com/2026/03/27/us-news/nj-teach...
211,61,2026-03-27-08-00-00 +0000,cbc,"At historic low point, New Democrats descend o...",https://www.cbc.ca/news/politics/ndp-leadershi...
227,58,2026-03-27-06-40-44 +0000,nypost,End to airport misery in sight as Senate appro...,https://nypost.com/2026/03/27/us-news/senate-a...
9,56,2026-03-27-17-00-00 +0000,wsj,About a year into the full-blown trade war bet...,https://www.wsj.com/economy/trade/how-trumps-t...
369,55,2026-03-26-18-52-16 +0000,nypost,Iran wants to charge ships for safe passage th...,https://nypost.com/2026/03/26/business/iran-wa...
42,46,2026-03-27-16-03-48 +0000,nypost,Sony jacking up PlayStation 5 prices for 2nd t...,https://nypost.com/2026/03/27/business/sony-ja...
278,42,2026-03-27-00-11-00 +0000,wsj,A U.S. federal judge on Thursday halted the Tr...,https://www.wsj.com/politics/policy/anthropic-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)