## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-19-14-50 +0000,nyt,‘The Odyssey’ Hired Their Viking Ship. They Sa...,https://www.nytimes.com/2026/07/23/movies/the-...
1,2026-07-23-19-14-25 +0000,nyt,Iran War Live Updates: Red Sea Turmoil Pushes ...,https://www.nytimes.com/live/2026/07/23/world/...
2,2026-07-23-19-12-00 +0000,wsj,Oil Futures Jump as Houthis Target Saudi Tankers,https://www.wsj.com/finance/commodities-future...
3,2026-07-23-19-10-00 +0000,wsj,Trump Says Iran Will Be Held Responsible for F...,https://www.wsj.com/world/middle-east/trump-sa...
4,2026-07-23-19-08-21 +0000,nypost,"Celeste Rivas’ rotting, insect-covered underga...",https://nypost.com/2026/07/23/us-news/celeste-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2442/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
24    trump     49
79     deal     24
22    saudi     23
7      iran     23
78  nuclear     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
181,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...,158
18,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...,148
185,2026-07-23-12-23-41 +0000,nypost,Trump says Saudi Arabia nuclear deal ‘totally ...,https://nypost.com/2026/07/23/us-news/trump-sa...,147
257,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,140
49,2026-07-23-17-29-32 +0000,nyt,"As Part of Nuclear Deal, Trump Demands Saudi A...",https://www.nytimes.com/2026/07/23/us/politics...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
181,158,2026-07-23-12-42-06 +0000,nypost,Trump threatens to retaliate against Iran for ...,https://nypost.com/2026/07/23/us-news/trump-wa...
18,76,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...
96,70,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
73,63,2026-07-23-16-51-00 +0000,wsj,A Democratic-backed measure to rein in Preside...,https://www.wsj.com/politics/gop-lawmakers-bac...
44,56,2026-07-23-17-50-29 +0000,nypost,Mom who murdered her ex while he picked up the...,https://nypost.com/2026/07/23/us-news/killer-m...
12,55,2026-07-23-18-56-23 +0000,nypost,South Korean AI billionaire faces $1 billion d...,https://nypost.com/2026/07/23/business/south-k...
112,49,2026-07-23-15-20-03 +0000,nypost,Brent crude oil surges to $100 a barrel for fi...,https://nypost.com/2026/07/23/business/brent-c...
126,44,2026-07-23-14-42-00 +0000,wsj,Working-class Americans have experienced a pay...,https://www.wsj.com/economy/jobs/paycheck-boos...
282,44,2026-07-23-02-45-00 +0000,wsj,Mayor Zohran Mamdani’s appointment of Lina Kha...,https://www.wsj.com/politics/policy/can-lina-k...
341,41,2026-07-22-21-55-29 +0000,nypost,Tesla profit disappoints as Elon Musk’s AI spe...,https://nypost.com/2026/07/22/business/tesla-p...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)