## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-23-00-50 +0000,nypost,Trump to sign emergency order to get TSA agent...,https://nypost.com/2026/03/26/us-news/trump-to...
1,2026-03-26-22-56-13 +0000,bbc,Trump's signature to appear on US dollars in f...,https://www.bbc.com/news/articles/cz0el909yp3o...
2,2026-03-26-22-52-08 +0000,nypost,Netflix hiking prices on all subscriptions aga...,https://nypost.com/2026/03/26/media/netflix-hi...
3,2026-03-26-22-45-06 +0000,startribune,Trump says he'll sign order to pay TSA agents ...,https://www.startribune.com/missed-paychecks-a...
4,2026-03-26-22-42-18 +0000,latimes,DOJ to investigate California over housing of ...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
56     iran     60
0     trump     54
103     war     34
152    will     15
57   energy     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
14,2026-03-26-22-37-06 +0000,nyt,Iran War Live Updates: Trump Again Extends Dea...,https://www.nytimes.com/live/2026/03/26/world/...,240
184,2026-03-26-16-54-14 +0000,latimes,"Trump projects confidence, claims Iran is 'beg...",https://www.latimes.com/world-nation/story/202...,171
200,2026-03-26-16-18-00 +0000,wsj,Trump Tells Aides He Wants Speedy End to Iran War,https://www.wsj.com/politics/elections/trump-t...,168
373,2026-03-26-02-07-44 +0000,nyt,Republicans in Congress Fret Over Trump Admini...,https://www.nytimes.com/2026/03/25/world/middl...,166
335,2026-03-26-09-00-00 +0000,wapo,Gulf countries want Trump to end Iran war — bu...,https://www.washingtonpost.com/world/2026/03/2...,165

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
14,240,2026-03-26-22-37-06 +0000,nyt,Iran War Live Updates: Trump Again Extends Dea...,https://www.nytimes.com/live/2026/03/26/world/...
74,79,2026-03-26-21-11-00 +0000,wsj,Several Senate Republicans are pressing the Wh...,https://www.wsj.com/politics/policy/republican...
239,58,2026-03-26-14-05-29 +0000,nypost,"Gang-rape victim, 25, whose suicide attempt le...",https://nypost.com/2026/03/26/world-news/gang-...
317,48,2026-03-26-09-40-00 +0000,wsj,Norges Bank Expects to Lift Borrowing Costs Th...,https://www.wsj.com/articles/norges-bank-expec...
309,45,2026-03-26-10-00-00 +0000,latimes,He was busted for gun possession. Now he's run...,https://www.latimes.com/california/story/2026-...
293,39,2026-03-26-10-48-00 +0000,wsj,Surgeon-general nominee Dr. Casey Means lacks ...,https://www.wsj.com/politics/this-is-the-start...
12,38,2026-03-26-22-39-00 +0000,wsj,The Trump administration plans to require high...,https://www.wsj.com/politics/policy/trump-admi...
10,38,2026-03-26-22-40-00 +0000,wsj,The Trump administration is putting President ...,https://www.wsj.com/politics/policy/trumps-sig...
187,37,2026-03-26-16-44-52 +0000,nypost,Pressure mounts on Congress to end the funding...,https://nypost.com/2026/03/26/us-news/pressure...
188,36,2026-03-26-16-44-21 +0000,nypost,UK man finds rare albino squirrel after mistak...,https://nypost.com/2026/03/26/world-news/uk-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)