## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-20-01-15-10 +0000,nyt,"Haunted by ‘Dark Thoughts,’ Louisiana Father K...",https://www.nytimes.com/2026/04/19/us/shrevepo...
1,2026-04-20-01-12-45 +0000,nypost,8 kids massacred by deranged Army vet dad Sham...,https://nypost.com/2026/04/19/us-news/8-kids-m...
2,2026-04-20-01-11-57 +0000,bbc,Oil prices jump after Trump says Iranian ship ...,https://www.bbc.com/news/articles/c5yjzy35825o...
3,2026-04-20-01-10-05 +0000,startribune,Jessie Diggins encourages fans to keep shining...,https://www.startribune.com/jessie-diggins-enc...
4,2026-04-20-01-00-19 +0000,nypost,California enclave named best small beach town...,https://nypost.com/2026/04/19/us-news/californ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2605/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20     trump     27
60      iran     15
21   iranian     12
99       war     11
105      new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
134,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...,86
12,2026-04-20-00-41-13 +0000,nyt,Iran War Live Updates: U.S. Attacks Iranian Ca...,https://www.nytimes.com/live/2026/04/19/world/...,76
82,2026-04-19-19-46-22 +0000,nypost,US Navy destroyer ‘blows a hole’ through Irani...,https://nypost.com/2026/04/19/world-news/us-na...,70
115,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...,69
73,2026-04-19-20-48-06 +0000,nyt,U.S. Installs a Trump Loyalist to Lead ‘Grand ...,https://www.nytimes.com/2026/04/18/us/politics...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
134,86,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...
24,38,2026-04-19-23-45-21 +0000,nyt,U.S. Attacks Iranian Cargo Ship as Both Countr...,https://www.nytimes.com/2026/04/19/world/middl...
33,36,2026-04-19-23-07-52 +0000,bbc,'They told me he was dead': Children born near...,https://www.bbc.com/news/articles/c895k3537kgo...
37,31,2026-04-19-23-00-00 +0000,wsj,A dispute between Defense Secretary Pete Hegse...,https://www.wsj.com/politics/national-security...
115,31,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
57,27,2026-04-19-21-43-40 +0000,nypost,"Cops fire rubber bullets, tear gas to fend off...",https://nypost.com/2026/04/19/us-news/cops-fir...
39,26,2026-04-19-22-54-51 +0000,bbc,"Eight children killed in Louisiana shooting, p...",https://www.bbc.com/news/articles/c0q9v1p2dd2o...
60,25,2026-04-19-21-35-09 +0000,nypost,Mom of 15-year old gunned down in NYC park has...,https://nypost.com/2026/04/19/us-news/mom-of-1...
65,23,2026-04-19-21-16-49 +0000,nypost,Dem Rep. Hillary Scholten fought to conceal di...,https://nypost.com/2026/04/19/us-news/dem-rep-...
66,22,2026-04-19-21-13-42 +0000,nypost,Inside glamorous arms dealer’s secret spy trip...,https://nypost.com/2026/04/19/us-news/iran-arm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)