## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-03-49-19 +0000,nypost,Jacob Frey praises Somali community as Minneso...,https://nypost.com/2026/06/28/us-news/jacob-fr...
1,2026-06-29-03-41-29 +0000,nypost,"Woman on motorcycle plows through NYC park, mo...",https://nypost.com/2026/06/28/us-news/woman-on...
2,2026-06-29-03-34-21 +0000,bbc,South Korea football coach quits as president ...,https://www.bbc.co.uk/news/articles/cdx7jk0kq4...
3,2026-06-29-03-17-55 +0000,nypost,Missing teen Marly Kinney ID’d as body found i...,https://nypost.com/2026/06/28/us-news/missing-...
4,2026-06-29-03-00-00 +0000,wsj,The Cutthroat Battle to Become America’s Rare-...,https://www.wsj.com/business/the-cutthroat-bat...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
105       iran     13
326      trump     10
157  venezuela      9
376        new      7
191        out      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
165,2026-06-28-08-05-07 +0000,wapo,"U.S., Iran launch new strikes, testing fragile...",https://www.washingtonpost.com/world/2026/06/2...,43
55,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...,42
168,2026-06-28-07-53-00 +0000,wsj,"U.S., Iran Carry Out New Strikes, Testing Frag...",https://www.wsj.com/world/middle-east/mideast-...,41
132,2026-06-28-13-31-18 +0000,nypost,Iran must develop nuclear bomb to protect ‘pea...,https://nypost.com/2026/06/28/world-news/iran-...,37
111,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...,35

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
165,43,2026-06-28-08-05-07 +0000,wapo,"U.S., Iran launch new strikes, testing fragile...",https://www.washingtonpost.com/world/2026/06/2...
111,35,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...
39,34,2026-06-28-23-09-14 +0000,nypost,GOP claims it will pick up NY House seats desp...,https://nypost.com/2026/06/28/us-news/gop-clai...
136,31,2026-06-28-12-10-56 +0000,nypost,At least 2 dead after Ukraine drone assault se...,https://nypost.com/2026/06/28/world-news/at-le...
117,30,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
101,29,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...
147,28,2026-06-28-10-08-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
47,27,2026-06-28-22-33-49 +0000,nyt,"In Venezuela, a Community Comes Together to Se...",https://www.nytimes.com/2026/06/28/world/ameri...
35,24,2026-06-28-23-33-42 +0000,nypost,NYPD commish stands with armed gay cops on sid...,https://nypost.com/2026/06/28/us-news/nypd-com...
139,24,2026-06-28-11-26-27 +0000,nyt,"Heat Wave Starts to Break in Western Europe, a...",https://www.nytimes.com/2026/06/28/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)