## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-08-07-16 +0000,bbc,"Starmer sends 'chill' through civil service, i...",https://www.bbc.com/news/articles/c1krxlvjezro...
1,2026-04-22-08-07-02 +0000,bbc,UK inflation rises after Iran war pushes up fu...,https://www.bbc.com/news/articles/cnv8l17r51ro...
2,2026-04-22-08-06-00 +0000,wsj,Euro’s Gains Could Prove Limited Without Real ...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-04-22-08-00-00 +0000,cbc,Washington demanding 'entry fee' from Ottawa b...,https://www.cbc.ca/news/politics/washington-de...
4,2026-04-22-08-00-00 +0000,cbc,Is it Mark Carney or is it AI?,https://www.cbc.ca/news/politics/carney-artifi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
11       iran     40
56      trump     40
14         up     20
571       new     18
155  virginia     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
258,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,191
105,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,146
13,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,132
89,2026-04-22-01-18-36 +0000,bbc,Oil prices dip as Trump extends Iran war cease...,https://www.bbc.com/news/articles/c995dkl4dvvo...,130
18,2026-04-22-07-01-00 +0000,wsj,Oil Falls as Trump Extends Cease-Fire With Iran,https://www.wsj.com/finance/commodities-future...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
258,191,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
80,64,2026-04-22-01-52-00 +0000,nyt,Here’s What the New Virginia House Map Looks Like,https://www.nytimes.com/2026/04/21/us/election...
79,63,2026-04-22-01-58-00 +0000,wsj,President Trump’s pick to lead the Federal Res...,https://www.wsj.com/economy/central-banking/wa...
252,48,2026-04-21-18-15-31 +0000,nypost,Rep. Sheila Cherfilus-McCormick resigns from C...,https://nypost.com/2026/04/21/us-news/rep-shei...
318,45,2026-04-21-14-52-47 +0000,cbc,"2 Palestinians, including 14-year-old, killed ...",https://www.cbc.ca/news/world/palestinians-kil...
16,42,2026-04-22-07-06-30 +0000,nypost,Mexico to beef up security at tourist sites af...,https://nypost.com/2026/04/22/world-news/mexic...
6,40,2026-04-22-08-00-00 +0000,cbc,John Ternus is replacing Tim Cook as Apple CEO...,https://www.cbc.ca/news/business/john-ternus-a...
52,38,2026-04-22-03-55-02 +0000,nypost,US warns it will run out of money to pay airpo...,https://nypost.com/2026/04/21/us-news/us-warns...
333,38,2026-04-21-14-01-21 +0000,nypost,"Dow slumps nearly 300 points, oil prices surge...",https://nypost.com/2026/04/21/business/dow-jum...
189,37,2026-04-21-20-57-34 +0000,nypost,"Gates Foundation cutting 20% of staff, launche...",https://nypost.com/2026/04/21/business/gates-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)