## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-14-12-00-00 +0000,wapo,Poland says it thwarted Russian assassination ...,https://www.washingtonpost.com/world/2026/08/1...
1,2026-08-14-11-56-55 +0000,nyt,Farage Wins Special U.K. Election That He Init...,https://www.nytimes.com/2026/08/14/world/europ...
2,2026-08-14-11-55-16 +0000,bbc,What do people in Clacton think of Farage's by...,https://www.bbc.co.uk/news/articles/cvg947z1we...
3,2026-08-14-11-54-48 +0000,bbc,Pardon for president's main rival in Chad,https://www.bbc.co.uk/news/articles/cn8nq561v1...
4,2026-08-14-11-54-15 +0000,nypost,Brave NJ mom died trying to save daughter in C...,https://nypost.com/2026/08/14/us-news/nj-mom-m...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2376/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
42        trump     39
268         new     17
368         out     16
441  california     16
10     election     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
157,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...,118
229,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...,111
151,2026-08-14-00-50-00 +0000,wsj,President Trump has directed the Navy to tear ...,https://www.wsj.com/us-news/trump-orders-navy-...,94
236,2026-08-13-20-15-57 +0000,cbc,Kennedy Center board votes to return Trump's n...,https://www.cbc.ca/news/world/kennedy-center-v...,90
259,2026-08-13-19-04-56 +0000,latimes,Kennedy Center board votes to close venue for ...,https://www.latimes.com/entertainment-arts/sto...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
157,118,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...
77,79,2026-08-14-09-41-00 +0000,wsj,A new report led by White House trade adviser ...,https://www.wsj.com/economy/trade/white-house-...
244,69,2026-08-13-20-01-00 +0000,wsj,The U.S. military is preparing to replace the ...,https://www.wsj.com/politics/national-security...
224,66,2026-08-13-20-42-17 +0000,chitri,Investigators find bird remains inside Ryanair...,https://www.chicagotribune.com/2026/08/13/ntsb...
229,63,2026-08-13-20-28-00 +0000,wsj,The Kennedy Center’s board of trustees has vot...,https://www.wsj.com/politics/policy/kennedy-ce...
104,49,2026-08-14-08-51-39 +0000,cbc,Reform UK leader Nigel Farage beats Count Binf...,https://www.cbc.ca/news/world/uk-clacton-byele...
242,47,2026-08-13-20-05-52 +0000,latimes,"He was a star LAPD investigator, then he went ...",https://www.latimes.com/california/story/2026-...
6,41,2026-08-14-11-46-00 +0000,wsj,President Trump unveiled a slate of tariffs to...,https://www.wsj.com/economy/trade/trump-announ...
250,39,2026-08-13-19-37-00 +0000,wsj,House Minority Leader Hakeem Jeffries on Thurs...,https://www.wsj.com/politics/policy/top-democr...
333,39,2026-08-13-15-15-31 +0000,nypost,Minnesota Dem Peggy Flanagan boasts she could ...,https://nypost.com/2026/08/13/us-news/minnesot...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)