## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-18-17-38-11 +0000,bbc,Farage facing new questions over home purchase...,https://www.bbc.com/news/articles/c936nqy00rwo...
1,2026-05-18-17-38-09 +0000,nypost,Pope and co-founder of Anthropic to launch pon...,https://nypost.com/2026/05/18/world-news/pope-...
2,2026-05-18-17-34-33 +0000,nypost,Prosecutors reveal twisted reason McDonald’s m...,https://nypost.com/2026/05/18/us-news/prosecut...
3,2026-05-18-17-34-00 +0000,wsj,The economy Kevin Warsh is inheriting isn't th...,https://www.wsj.com/economy/central-banking/th...
4,2026-05-18-17-32-27 +0000,cbc,World Gymnastics lifts all restrictions on Rus...,https://www.cbc.ca/sports/olympics/summer/gymn...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2457/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
45      trump     33
117      iran     15
2         new     14
12         ai      9
261  outbreak      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...,85
230,2026-05-17-20-50-38 +0000,nypost,Drone strikes UAE nuke plant as Trump warns Ir...,https://nypost.com/2026/05/17/world-news/drone...,80
90,2026-05-18-14-32-21 +0000,nypost,Iran offers new 14-point peace proposal after ...,https://nypost.com/2026/05/18/us-news/iran-sub...,75
250,2026-05-17-19-00-00 +0000,wsj,House Democratic leader Hakeem Jeffries has be...,https://www.wsj.com/politics/elections/the-tru...,73
5,2026-05-18-17-32-00 +0000,wsj,President Trump will host a swearing-in ceremo...,https://www.wsj.com/economy/central-banking/tr...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,85,2026-05-18-02-33-00 +0000,wsj,President Trump is discussing plans to install...,https://www.wsj.com/politics/policy/trumps-lat...
216,47,2026-05-17-23-02-56 +0000,bbc,'This may be the last time you hear my voice':...,https://www.bbc.com/news/articles/cn8p392nl7yo...
255,40,2026-05-17-18-20-28 +0000,nypost,Spencer Pratt says he’ll move family out of Lo...,https://nypost.com/2026/05/17/us-news/spencer-...
113,40,2026-05-18-13-17-32 +0000,nypost,Luigi Mangione fanatics line up outside courth...,https://nypost.com/2026/05/18/us-news/luigi-ma...
210,35,2026-05-18-00-49-25 +0000,bbc,Moment two fighter jets collide mid-air at US ...,https://www.bbc.com/news/videos/ce8pzkg7klgo?a...
104,35,2026-05-18-13-52-32 +0000,nypost,Military diver who died trying to recover Ital...,https://nypost.com/2026/05/18/world-news/milit...
99,34,2026-05-18-14-01-24 +0000,nypost,"Trump drops IRS suit in exchange for apology, ...",https://nypost.com/2026/05/18/us-news/trump-dr...
42,33,2026-05-18-16-20-30 +0000,bbc,At least 100 deaths reported in Ebola outbreak...,https://www.bbc.com/news/articles/cq6pz60p996o...
230,32,2026-05-17-20-50-38 +0000,nypost,Drone strikes UAE nuke plant as Trump warns Ir...,https://nypost.com/2026/05/17/world-news/drone...
31,28,2026-05-18-16-40-26 +0000,nypost,Carl’s Jr. crushed by California’s high minimu...,https://nypost.com/2026/05/18/business/carls-j...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)