## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-19-04-22 +0000,nypost,Dope fresh NY weed data show fans were flying ...,https://nypost.com/2026/08/09/us-news/dope-fre...
1,2026-08-09-18-58-19 +0000,cbc,"First Nations chiefs in B.C. call on Carney, S...",https://www.cbc.ca/news/politics/first-nations...
2,2026-08-09-18-58-00 +0000,wsj,Israel Rejects Next Phase of Trump’s Gaza Peac...,https://www.wsj.com/world/middle-east/israel-r...
3,2026-08-09-18-45-58 +0000,startribune,Review: Guns N’ Roses came fully loaded to Sha...,https://www.startribune.com/guns-n-roses-conce...
4,2026-08-09-18-44-54 +0000,nypost,Three in five Americans favor stronger oversig...,https://nypost.com/2026/08/09/business/three-i...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2496/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
30   trump     17
33    plan      9
60  senate      8
26  israel      7
31    gaza      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
49,2026-08-09-15-16-21 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,57
74,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...,56
64,2026-08-09-14-18-10 +0000,bbc,"Israel rejects Trump's 15-point plan for Gaza,...",https://www.bbc.co.uk/news/articles/c5yw4lpe0y...,54
2,2026-08-09-18-58-00 +0000,wsj,Israel Rejects Next Phase of Trump’s Gaza Peac...,https://www.wsj.com/world/middle-east/israel-r...,52
31,2026-08-09-16-39-14 +0000,nyt,Israel Rejects Trump’s 15-Point Plan to Disarm...,https://www.nytimes.com/2026/08/09/world/middl...,51

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
49,57,2026-08-09-15-16-21 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
45,41,2026-08-09-15-30-00 +0000,wsj,After notching a narrow victory in Michigan’s ...,https://www.wsj.com/politics/elections/michiga...
32,34,2026-08-09-16-33-50 +0000,nypost,Tragic New York Harbor boat crash victims ID’d...,https://nypost.com/2026/08/09/us-news/tragic-n...
87,24,2026-08-09-12-24-04 +0000,cbc,14-year-old accused in deadly school shooting ...,https://www.cbc.ca/news/world/accused-thai-sch...
0,23,2026-08-09-19-04-22 +0000,nypost,Dope fresh NY weed data show fans were flying ...,https://nypost.com/2026/08/09/us-news/dope-fre...
120,21,2026-08-09-08-30-29 +0000,chitri,Today in History: Jen Pawol becomes MLB’s firs...,https://www.chicagotribune.com/2026/08/09/toda...
40,21,2026-08-09-15-51-04 +0000,nypost,Iran-backed Houthis attack Aramco refinery in ...,https://nypost.com/2026/08/09/world-news/iran-...
149,20,2026-08-08-22-17-33 +0000,nyt,Blackbird Mountain Guides Report on Lake Tahoe...,https://www.nytimes.com/2026/08/08/us/tahoe-av...
34,19,2026-08-09-16-23-18 +0000,nypost,Deranged criminal’s own family fears his relea...,https://nypost.com/2026/08/09/us-news/north-ca...
71,18,2026-08-09-13-29-23 +0000,nypost,LI stripper sues doctor who sought restraining...,https://nypost.com/2026/08/09/us-news/li-strip...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)