## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-05-13-00 +0000,wsj,Bank of Japan Holds Steady as Middle East Tens...,https://www.wsj.com/economy/central-banking/ba...
1,2026-03-19-05-08-25 +0000,nyt,"As a Meningitis Outbreak Spreads in Kent, UK, ...",https://www.nytimes.com/2026/03/18/world/europ...
2,2026-03-19-05-06-58 +0000,nypost,Missing University of Alabama student James Gr...,https://nypost.com/2026/03/19/world-news/james...
3,2026-03-19-04-48-51 +0000,nypost,New details emerge about New Mexico US Air For...,https://nypost.com/2026/03/19/us-news/new-deta...
4,2026-03-19-04-42-00 +0000,wsj,Yen Could Weaken to 160 Per Dollar During BOJ ...,https://www.wsj.com/finance/currencies/yen-lik...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
58     iran     61
59      war     37
153   trump     37
314  chavez     26
313   cesar     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
361,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,170
143,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...,168
261,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,161
253,2026-03-18-17-07-48 +0000,nyt,Trump’s Next Decision in War: Whether to Retri...,https://www.nytimes.com/2026/03/17/us/politics...,158
31,2026-03-19-02-19-22 +0000,nyt,Senate G.O.P. Again Blocks Bid to Stop Iran Wa...,https://www.nytimes.com/2026/03/18/us/politics...,155

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
361,170,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...
39,95,2026-03-19-02-02-49 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
316,85,2026-03-18-14-35-35 +0000,nypost,Oil spikes after Iran says world’s largest gas...,https://nypost.com/2026/03/18/world-news/oil-s...
158,68,2026-03-18-21-06-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
3,63,2026-03-19-04-48-51 +0000,nypost,New details emerge about New Mexico US Air For...,https://nypost.com/2026/03/19/us-news/new-deta...
54,57,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
362,54,2026-03-18-10-59-42 +0000,nypost,Israel says it assassinated Iranian intelligen...,https://nypost.com/2026/03/18/world-news/israe...
331,50,2026-03-18-13-51-07 +0000,cbc,Bank of Canada holds key interest rate at 2.25...,https://www.cbc.ca/news/business/bank-of-canad...
15,45,2026-03-19-03-54-00 +0000,wsj,Oil Rises After Attacks on Middle East Energy ...,https://www.wsj.com/finance/oil-rises-amid-wid...
263,44,2026-03-18-16-58-36 +0000,startribune,Minnesota house prices decline for first time ...,https://www.startribune.com/minnesota-house-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)