## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-10-13-15-28 +0000,bbc,First passengers fly home from virus-hit cruis...,https://www.bbc.com/news/articles/cn7pzmg8zeno...
1,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
2,2026-05-10-13-11-55 +0000,nypost,AOC says her ‘ambition is way bigger than’ bec...,https://nypost.com/2026/05/10/us-news/aoc-says...
3,2026-05-10-13-00-00 +0000,missionlocal,Penthouse apartment,https://missionlocal.org/2026/05/penthouse-apa...
4,2026-05-10-12-52-31 +0000,bbc,Army parachutes onto remote island to help Bri...,https://www.bbc.com/news/articles/cvgzv77ldpdo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2684/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
7          iran     12
6          ship     10
229         war      9
41   hantavirus      9
51       labour      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,61
76,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...,53
104,2026-05-10-00-38-46 +0000,nyt,Passengers on Hantavirus Cruise Ship Will Dise...,https://www.nytimes.com/2026/05/09/world/afric...,46
132,2026-05-09-20-03-22 +0000,nypost,Trump ready to ship US delegation to Moscow to...,https://nypost.com/2026/05/09/world-news/trump...,46
172,2026-05-09-14-45-38 +0000,nypost,WHO to oversee evacuations from hantavirus-str...,https://nypost.com/2026/05/09/world-news/who-h...,42

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,61,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
76,43,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...
112,41,2026-05-09-23-10-03 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...
41,31,2026-05-10-10-00-44 +0000,wapo,N.J. World Cup games will be in a county that ...,https://www.washingtonpost.com/nation/2026/05/...
28,29,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...
149,27,2026-05-09-17-28-59 +0000,bbc,'We just hit somebody' - Frontier Airlines pla...,https://www.bbc.com/news/articles/c5y95782wyko...
108,27,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
182,26,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
153,25,2026-05-09-16-30-54 +0000,bbc,SNP leader John Swinney rules out Holyrood tal...,https://www.bbc.com/news/articles/cddpevvv97jo...
16,23,2026-05-10-12-00-00 +0000,nypost,Los Angeles mayoral candidate Spencer Pratt se...,https://nypost.com/2026/05/10/sports/los-angel...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)