## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-08-25-53 +0000,bbc,'I won't be able to afford to eat before long',https://www.bbc.com/news/articles/cd6ejwxjx28o...
1,2026-06-18-08-25-47 +0000,bbc,Gunfire heard at Niger capital's airport,https://www.bbc.com/news/articles/cdx7krkdqeno...
2,2026-06-18-08-21-08 +0000,nyt,Taiwan’s President Says He Trusts Trump to App...,https://www.nytimes.com/2026/06/18/world/asia/...
3,2026-06-18-08-19-57 +0000,bbc,'Scared to go to work': Shop assistant tells M...,https://www.bbc.com/news/articles/c621v4pmg31o...
4,2026-06-18-08-15-00 +0000,wsj,"Treasurys, Stock Futures Rebound on U.S.-Iran ...",https://www.wsj.com/finance/stocks/treasurys-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
15  trump     51
31   iran     46
38   deal     41
33    fed     25
79    new     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
160,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,219
272,2026-06-17-16-31-02 +0000,nypost,Trump says Iran laughed at ‘stupid son of a bi...,https://nypost.com/2026/06/17/us-news/trump-sa...,196
224,2026-06-17-18-41-12 +0000,bbc,Fed holds US interest rates steady as uncertai...,https://www.bbc.com/news/articles/cdjkl78vd7lo...,192
247,2026-06-17-17-44-50 +0000,nypost,Trump jokingly reveals whom he’ll blame if Ira...,https://nypost.com/2026/06/17/us-news/trump-jo...,175
82,2026-06-18-01-21-45 +0000,nyt,"Before Making a Deal, Trump Demanded Iran’s Su...",https://www.nytimes.com/2026/06/17/us/politics...,165

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
160,219,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
176,124,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
31,51,2026-06-18-05-53-00 +0000,wsj,Oil Prices Fall Amid Prospects of Fast Reopeni...,https://www.wsj.com/finance/commodities-future...
97,50,2026-06-17-23-54-00 +0000,wsj,President Trump said he is delaying the nomina...,https://www.wsj.com/politics/policy/trump-dela...
202,46,2026-06-17-19-43-10 +0000,bbc,The designer behind DR Congo's World Cup suit:...,https://www.bbc.com/news/videos/crkvxp731e2o?a...
269,46,2026-06-17-16-37-41 +0000,bbc,"AI will create more jobs for humans, not repla...",https://www.bbc.com/news/articles/ceqdrw2yy3vo...
120,38,2026-06-17-22-36-13 +0000,bbc,Japan ramping up defence is 'critical' to prev...,https://www.bbc.com/news/articles/cly8qd4595eo...
367,35,2026-06-17-10-00-00 +0000,latimes,He graduated high school with honors. ICE deta...,https://www.latimes.com/california/story/2026-...
192,35,2026-06-17-20-09-40 +0000,nypost,Dow tumbles 500 points as possible rate hike u...,https://nypost.com/2026/06/17/business/dow-tum...
260,34,2026-06-17-17-06-49 +0000,nypost,New Billionaire Tax odds reveals huge swing in...,https://nypost.com/2026/06/17/betting/will-cal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)