## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-15-55-35 +0000,nypost,Royals-linked London banker accused of being U...,https://nypost.com/2026/09/16/world-news/royal...
1,2026-09-16-15-53-03 +0000,nypost,Black luxury CEO says Nordstrom manager ‘stalk...,https://nypost.com/2026/09/16/business/fruitfu...
2,2026-09-16-15-50-25 +0000,nyt,Houthis and Saudis Trade Claims of Military At...,https://www.nytimes.com/2026/09/16/world/middl...
3,2026-09-16-15-50-23 +0000,nyt,News Choppers Gathered in the Los Angeles Sky....,https://www.nytimes.com/2026/09/16/us/los-ange...
4,2026-09-16-15-44-27 +0000,bbc,Nandy pledges crackdown on 'doxxing' after RNL...,https://www.bbc.co.uk/news/articles/c64gjr5l57...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2566/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
65   trump     49
151     ai     28
356    new     22
210    war     22
600   iran     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
305,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,221
289,2026-09-15-22-39-00 +0000,wsj,The Kennedy Center’s board voted on Tuesday to...,https://www.wsj.com/us-news/law/trumps-name-ca...,135
403,2026-09-15-18-34-00 +0000,wsj,"President Trump promised $5,000 to every Ameri...",https://www.wsj.com/politics/policy/republican...,128
370,2026-09-15-19-50-00 +0000,wsj,President Trump said Tuesday that the three Su...,https://www.wsj.com/politics/policy/trumps-fru...,121
298,2026-09-15-21-55-20 +0000,bbc,Trump says Kennedy Center to close as court ru...,https://www.bbc.co.uk/news/articles/c6y8zp3kv0...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
305,221,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
336,83,2026-09-15-20-47-00 +0000,wsj,The U.S. is pressuring Mexico to accept new ru...,https://www.wsj.com/economy/trade/u-s-pressure...
370,72,2026-09-15-19-50-00 +0000,wsj,President Trump said Tuesday that the three Su...,https://www.wsj.com/politics/policy/trumps-fru...
376,67,2026-09-15-19-36-30 +0000,nypost,10-year Treasury yield hits highest level sinc...,https://nypost.com/2026/09/15/business/10-year...
154,64,2026-09-16-10-00-00 +0000,wsj,Security gaps at Utah Valley University last S...,https://www.wsj.com/us-news/charlie-kirks-wido...
19,59,2026-09-16-15-16-00 +0000,wsj,EU Chief Backs Canada’s Push to Become Bloc’s ...,https://www.wsj.com/world/europe/eu-chief-floa...
269,57,2026-09-15-23-30-00 +0000,wsj,American business owners are grappling with a ...,https://www.wsj.com/business/american-business...
36,50,2026-09-16-14-37-51 +0000,nypost,Driver who smashed into Metro bus before NBC h...,https://nypost.com/2026/09/16/us-news/driver-w...
293,50,2026-09-15-22-15-45 +0000,nypost,Senate fails to advance Clarity Act in blow to...,https://nypost.com/2026/09/15/business/senate-...
0,42,2026-09-16-15-55-35 +0000,nypost,Royals-linked London banker accused of being U...,https://nypost.com/2026/09/16/world-news/royal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)