## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-04-23-52-13 +0000,nyt,Judge Will Not Block Pentagon Move to Fire Sta...,https://www.nytimes.com/2026/09/04/us/politics...
1,2026-09-04-23-52-03 +0000,nypost,‘Activist’ San Diego judge frees Machete-wield...,https://nypost.com/2026/09/04/us-news/san-dieg...
2,2026-09-04-23-49-01 +0000,missionlocal,Mayor Lurie will indefinitely continue ‘90 day...,https://missionlocal.org/2026/09/mayor-lurie-w...
3,2026-09-04-23-47-39 +0000,nyt,"In Complex Cases Like Lindsay Clancy’s, a Unan...",https://www.nytimes.com/2026/09/04/us/lindsay-...
4,2026-09-04-23-42-44 +0000,nyt,"The Heart Drug Pelacarsen Fails, Shocking Nova...",https://www.nytimes.com/2026/09/04/science/hea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
80     trump     41
34    clancy     23
33   lindsay     20
681   report     20
449     jobs     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
135,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...,105
238,2026-09-04-14-36-42 +0000,nypost,Trump threatens trade with dozens of countries...,https://nypost.com/2026/09/04/us-news/trump-de...,105
93,2026-09-04-20-44-26 +0000,bbc,Watch: Inside court as judge declares a mistri...,https://www.bbc.co.uk/news/videos/c2l8z4rx5xro...,98
23,2026-09-04-22-58-11 +0000,latimes,Judge again halts USPS mail ballot plan as Tru...,https://www.latimes.com/politics/story/2026-09...,96
399,2026-09-04-00-55-45 +0000,bbc,Watch: Inside court as Lindsay Clancy's lawyer...,https://www.bbc.co.uk/news/videos/c36l7jwjg1no...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
135,105,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...
106,93,2026-09-04-20-33-00 +0000,wsj,Democrats criticized Sen. John Fetterman after...,https://www.wsj.com/politics/policy/democrats-...
405,80,2026-09-04-00-34-00 +0000,wsj,Missouri’s Supreme Court ruled Thursday the st...,https://www.wsj.com/politics/policy/missouri-s...
62,64,2026-09-04-21-18-00 +0000,wsj,U.S. Stocks Fall as Robust August Jobs Data Sp...,https://www.wsj.com/finance/investing/u-s-stoc...
371,62,2026-09-04-05-58-19 +0000,nypost,Two trapped workers rescued from hydropower tu...,https://nypost.com/2026/09/04/world-news/nepal...
267,57,2026-09-04-13-00-00 +0000,nypost,New In-N-Out opens Friday — part of Southern C...,https://nypost.com/2026/09/04/business/new-in-...
282,52,2026-09-04-12-11-46 +0000,chitri,US diesel prices hit record high of $5.85 on a...,https://www.chicagotribune.com/2026/09/04/us-d...
8,43,2026-09-04-23-30-50 +0000,nypost,Obama-appointed judge extends block on Trump o...,https://nypost.com/2026/09/04/us-news/obama-ap...
343,40,2026-09-04-09-03-39 +0000,nyt,The Bond Markets Are Pushing Up Rates. Will Ce...,https://www.nytimes.com/2026/09/04/business/bo...
86,40,2026-09-04-20-53-00 +0000,wsj,The Justice Department’s antitrust division wa...,https://www.wsj.com/politics/policy/justice-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)