## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-05-15-06-00 +0000,wsj,Dollar Rises Amid Concerns of Conflict-Driven ...,https://www.wsj.com/finance/currencies/asian-c...
1,2026-03-05-15-05-00 +0000,wsj,BYD Launches New Fast-Charging Battery Amid Sl...,https://www.wsj.com/business/autos/byd-launche...
2,2026-03-05-15-03-09 +0000,nyt,Live Updates: Europe Ramps Up Response as Iran...,https://www.nytimes.com/live/2026/03/05/world/...
3,2026-03-05-15-00-27 +0000,nyt,How Jonathan Groff of ‘Just in Time’ Became Br...,https://www.nytimes.com/2026/03/05/theater/jon...
4,2026-03-05-15-00-00 +0000,missionlocal,Grandfather killed in brutal Potrero shooting ...,https://missionlocal.org/2026/03/sf-potrero-hi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2631/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
46       iran     78
86        war     42
181     trump     32
24    iranian     23
4    conflict     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
271,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...,187
204,2026-03-05-03-17-32 +0000,latimes,California soldier among those killed in Iran ...,https://www.latimes.com/california/story/2026-...,177
266,2026-03-04-23-10-49 +0000,nypost,Thousands of Americans are stranded in Middle ...,https://nypost.com/2026/03/04/business/thousan...,176
186,2026-03-05-05-07-22 +0000,nyt,Senate Thwarts Bid to Curb Trump’s War Powers ...,https://www.nytimes.com/2026/03/04/us/politics...,174
256,2026-03-04-23-42-08 +0000,bbc,US Senate vote fails to rein in Trump war powe...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,173

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
271,187,2026-03-04-22-53-24 +0000,nypost,Senate Republicans block Iran war powers resol...,https://nypost.com/2026/03/04/us-news/senate-r...
219,85,2026-03-05-01-50-00 +0000,wsj,Republican Rep. Tony Gonzales admitted to an a...,https://www.wsj.com/politics/embattled-gop-law...
433,80,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
150,71,2026-03-05-08-52-04 +0000,nypost,Iranian bombers came within ‘two minutes’ of s...,https://nypost.com/2026/03/05/world-news/irani...
381,66,2026-03-04-18-19-00 +0000,wsj,Global authorities must step up their surveill...,https://www.wsj.com/economy/central-banking/re...
377,48,2026-03-04-18-25-42 +0000,nyt,The conflict is choking off the world’s oil an...,https://www.nytimes.com/live/2026/world/us-isr...
23,48,2026-03-05-14-31-05 +0000,startribune,Iran is pummeled by airstrikes as it launches ...,https://www.startribune.com/iran-launches-new-...
429,46,2026-03-04-15-55-00 +0000,wsj,GOP Rep. Dan Crenshaw became the first House i...,https://www.wsj.com/politics/elections/rep-dan...
214,46,2026-03-05-02-15-00 +0000,wsj,"Sen. Steve Daines of Montana, a close ally of ...",https://www.wsj.com/politics/elections/trump-a...
274,44,2026-03-04-22-39-20 +0000,bbc,Tech firms pledge to pay for AI data centre po...,https://www.bbc.com/news/articles/cx244kdplnzo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)