## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-30-21-48-01 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
1,2026-10-30-21-46-47 +0000,missionlocal,Closed-door meetings and chatbot sermons: Insi...,https://missionlocal.org/2026/10/closed-door-m...
2,2026-10-30-21-46-00 +0000,wsj,Opinion | When Jews Ruled the Basketball Court,https://www.wsj.com/opinion/when-jews-ruled-th...
3,2026-10-30-21-44-55 +0000,nypost,LA sheriff’s dept probes its ties to $43M Wall...,https://nypost.com/2026/10/30/business/la-sher...
4,2026-10-30-21-44-00 +0000,wsj,WSJ Dollar Index Rises 0.04% This Month to 97.08,https://www.wsj.com/finance/currencies/singapo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2669/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
50      trump     32
144  election     30
277    senate     17
0     binance     17
21      court     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
376,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...,134
404,2026-10-29-22-51-00 +0000,chitri,President Trump lends support for Darline Grah...,https://www.chicagotribune.com/2026/10/29/trum...,92
248,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,90
223,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,85
365,2026-10-30-02-00-00 +0000,wsj,"Trump Administration, States Harden Battle Lin...",https://www.wsj.com/politics/elections/trump-a...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
376,134,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...
248,90,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
109,79,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
309,62,2026-10-30-09-33-51 +0000,bbc,Crypto giant Binance hit by $6.3bn hack suspec...,https://www.bbc.co.uk/news/articles/cwg7xp8kx4...
279,56,2026-10-30-10-50-00 +0000,wsj,Bayer Shares Rise After Win in First Roundup T...,https://www.wsj.com/us-news/law/bayer-wins-fir...
318,48,2026-10-30-09-01-01 +0000,nypost,"Canadian CEO, daughters shot and wife attacked...",https://nypost.com/2026/10/30/world-news/canad...
79,47,2026-10-30-20-13-31 +0000,nyt,El-Sayed’s Former Primary Rival Demands Apolog...,https://www.nytimes.com/2026/10/30/us/politics...
23,43,2026-10-30-21-25-31 +0000,nypost,Blakeman dares Hochul to sign ‘no new taxes’ p...,https://nypost.com/2026/10/30/us-news/blakeman...
192,42,2026-10-30-14-49-00 +0000,wsj,The balance of power in the House is on the li...,https://www.wsj.com/politics/elections/the-202...
42,41,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)