## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-11-58-04 +0000,bbc,Council considers extending food voucher scheme,https://www.bbc.com/news/articles/c5y5lvznj1eo...
1,2026-03-09-11-54-00 +0000,wsj,Saudi Arabia Reallocating Supply Not Cutting O...,https://www.wsj.com/finance/commodities-future...
2,2026-03-09-11-52-01 +0000,bbc,"Call off King's US visit over Iran, urge Lib Dems",https://www.bbc.com/news/articles/cz6evlwl68do...
3,2026-03-09-11-45-19 +0000,bbc,In maps: Ten days of strikes across the Middle...,https://www.bbc.com/news/articles/c4g0pnnj8xyo...
4,2026-03-09-11-44-13 +0000,nypost,Family of teacher killed in prank gone wrong w...,https://nypost.com/2026/03/09/us-news/family-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
16    iran     47
137    new     26
322  trump     24
46     oil     22
112    war     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-03-09-11-16-05 +0000,startribune,"Iran names Khamenei's son to succeed him, sign...",https://www.startribune.com/iran-names-former-...,147
153,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...,144
17,2026-03-09-11-07-47 +0000,wapo,Oil prices spike over fears of prolonged confl...,https://www.washingtonpost.com/world/2026/03/0...,141
56,2026-03-09-09-30-00 +0000,wsj,The surge in oil and gasoline prices last week...,https://www.wsj.com/economy/central-banking/is...,131
164,2026-03-08-21-37-50 +0000,nypost,Ayatollah Ali Khamenei’s son Mojtaba Khamenei ...,https://nypost.com/2026/03/08/world-news/mojta...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,147,2026-03-09-11-16-05 +0000,startribune,"Iran names Khamenei's son to succeed him, sign...",https://www.startribune.com/iran-names-former-...
46,105,2026-03-09-10-05-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...
153,52,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...
219,48,2026-03-08-16-39-17 +0000,nypost,"Gas will be below $3 soon, Energy Secretary Wr...",https://nypost.com/2026/03/08/us-news/gas-will...
56,40,2026-03-09-09-30-00 +0000,wsj,The surge in oil and gasoline prices last week...,https://www.wsj.com/economy/central-banking/is...
163,37,2026-03-08-21-47-41 +0000,nypost,Gavin Newsom plans to use $19M of your cash to...,https://nypost.com/2026/03/08/us-news/gov-news...
10,35,2026-03-09-11-30-53 +0000,nypost,AI startup’s CEO threatened to call ex-NYC May...,https://nypost.com/2026/03/09/business/ai-star...
224,31,2026-03-08-16-14-47 +0000,nyt,Israeli Strikes on Fuel Depots Send Black Clou...,https://www.nytimes.com/2026/03/08/world/middl...
102,26,2026-03-09-05-07-36 +0000,nypost,US military tests on secret weapon bought from...,https://nypost.com/2026/03/09/us-news/us-milit...
78,26,2026-03-09-08-26-25 +0000,nypost,Travelers fume over hours-long airport securit...,https://nypost.com/2026/03/09/us-news/departme...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)