## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-17-55-12 +0000,nyt,The ‘Miracle House’ That Survived Nepal’s Floods,https://www.nytimes.com/2026/09/02/world/asia/...
1,2026-09-02-17-54-27 +0000,nypost,‘Sandwich generation’ Americans taking care of...,https://nypost.com/2026/09/02/us-news/sandwich...
2,2026-09-02-17-53-13 +0000,nypost,"DOJ seizes over $560,000 in Hamas-linked crypt...",https://nypost.com/2026/09/02/world-news/doj-s...
3,2026-09-02-17-47-06 +0000,cbc,Low flypast over Cape Town stadium to be revie...,https://www.cbc.ca/news/world/cape-town-flyove...
4,2026-09-02-17-46-45 +0000,wapo,Orlando held a fight in its city-owned arena. ...,https://www.washingtonpost.com/politics/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
181  trump     31
132    new     21
104   iran     20
65      up     20
50    will     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
107,2026-09-02-14-55-45 +0000,nypost,Dramatic video shows US strikes raining on Ira...,https://nypost.com/2026/09/02/us-news/dramatic...,109
282,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,96
385,2026-09-01-21-04-00 +0000,wsj,"U.S. Stocks Fall as Oil, Bond Yields Spike, U....",https://www.wsj.com/finance/investing/u-s-stoc...,94
20,2026-09-02-17-24-23 +0000,wapo,El-Sayed blames Trump for global bond market s...,https://www.washingtonpost.com/politics/2026/0...,93
375,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
107,109,2026-09-02-14-55-45 +0000,nypost,Dramatic video shows US strikes raining on Ira...,https://nypost.com/2026/09/02/us-news/dramatic...
143,79,2026-09-02-12-55-00 +0000,wapo,"Watch Ontario, New York, residents sound off o...",https://www.washingtonpost.com/politics/2026/0...
422,77,2026-09-01-18-51-00 +0000,wsj,A Fed governor says the central bank should ac...,https://www.wsj.com/economy/central-banking/a-...
275,71,2026-09-02-01-59-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
271,67,2026-09-02-02-31-16 +0000,nyt,Former Biden White House Aide Wins Massachuset...,https://www.nytimes.com/2026/09/01/us/politics...
282,65,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
406,59,2026-09-01-19-51-00 +0000,wsj,Oil Prices Push Global Bond Market Closer to t...,https://www.wsj.com/finance/investing/oil-pric...
334,49,2026-09-01-22-56-00 +0000,wsj,The House voted overwhelmingly to censure Rep....,https://www.wsj.com/politics/chuck-edwards-hou...
198,49,2026-09-02-10-00-00 +0000,startribune,Reusse: Kyler Murray will be fine. Here’s what...,https://www.startribune.com/minnesota-vikings-...
54,45,2026-09-02-16-27-03 +0000,bbc,Burnham pressed on economy at first PMQs as UK...,https://www.bbc.co.uk/news/articles/cn9wv7pene...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)