## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-23-12-06 +0000,nyt,Cuban Pilot in Florida Is a Defendant in Raúl ...,https://www.nytimes.com/2026/05/21/world/ameri...
1,2026-05-21-23-11-01 +0000,nyt,Judge Appears Hesitant to Order Work Stopped o...,https://www.nytimes.com/2026/05/21/us/politics...
2,2026-05-21-22-59-10 +0000,nypost,Vandal beheads Jesus Christ statue at Long Isl...,https://nypost.com/2026/05/21/us-news/vandal-b...
3,2026-05-21-22-58-00 +0000,wsj,IMAX Is Exploring a Sale,https://www.wsj.com/business/media/imax-is-exp...
4,2026-05-21-22-57-31 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/21/us/dnc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
34   trump     46
144     he     16
422    new     16
166  china     15
227    was     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
60,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...,118
226,2026-05-21-15-36-20 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...,107
198,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...,105
393,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,104
170,2026-05-21-17-52-49 +0000,nypost,Trump says he postponed signing AI order becau...,https://nypost.com/2026/05/21/us-news/trump-sa...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
60,118,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...
305,93,2026-05-21-11-01-27 +0000,nypost,Queen Elizabeth was eager for Andrew to become...,https://nypost.com/2026/05/21/world-news/docum...
302,61,2026-05-21-11-06-00 +0000,wsj,"Jeff Bezos wades into politics, and New York C...",https://www.wsj.com/politics/policy/bezos-wade...
393,58,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
48,50,2026-05-21-21-40-00 +0000,wsj,Mortgage rates this week rose to the highest l...,https://www.wsj.com/economy/housing/mortgage-r...
29,44,2026-05-21-22-16-23 +0000,nypost,San Diego mosque shooter Caleb Vazquez walked ...,https://nypost.com/2026/05/21/us-news/san-dieg...
168,43,2026-05-21-17-54-40 +0000,bbc,DR Congo cancels World Cup training camp over ...,https://www.bbc.com/news/articles/c8d80856q2go...
358,41,2026-05-21-06-00-32 +0000,bbc,SpaceX files for stock market debut that could...,https://www.bbc.com/news/articles/cg4pe2953q1o...
90,41,2026-05-21-21-01-00 +0000,wsj,The DNC’s long awaited release of an autopsy r...,https://www.wsj.com/politics/elections/dnc-202...
199,40,2026-05-21-16-51-12 +0000,nyt,French Court Says Air France and Airbus Are Gu...,https://www.nytimes.com/2026/05/21/business/ai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)