## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-21-15-00 +0000,missionlocal,Meet the District 2 candidates: Where should b...,https://missionlocal.org/2026/05/sf-district-2...
1,2026-05-12-21-12-32 +0000,nypost,OC mom charged with manslaughter after teen so...,https://nypost.com/2026/05/12/us-news/mom-char...
2,2026-05-12-21-11-17 +0000,nyt,Iran War Live Updates: Trump Says Iran Must Ma...,https://www.nytimes.com/live/2026/05/12/world/...
3,2026-05-12-21-11-15 +0000,nyt,"Earthquake Shakes Tehran, Where Nerves Are Alr...",https://www.nytimes.com/2026/05/12/world/middl...
4,2026-05-12-21-09-30 +0000,nyt,"Claire Maurier, the Narcissistic Mother in ‘40...",https://www.nytimes.com/2026/05/12/movies/clai...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
23        trump     41
19         iran     35
20          war     32
244  hantavirus     18
276     starmer     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-05-12-21-11-17 +0000,nyt,Iran War Live Updates: Trump Says Iran Must Ma...,https://www.nytimes.com/live/2026/05/12/world/...,160
355,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,158
380,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,138
75,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,137
14,2026-05-12-20-59-40 +0000,nyt,Trump Says Americans’ Economic Pain Is Not a C...,https://www.nytimes.com/2026/05/12/us/politics...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,160,2026-05-12-21-11-17 +0000,nyt,Iran War Live Updates: Trump Says Iran Must Ma...,https://www.nytimes.com/live/2026/05/12/world/...
46,66,2026-05-12-20-23-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
291,61,2026-05-12-08-55-33 +0000,cbc,British PM Starmer tells cabinet meeting he in...,https://www.cbc.ca/news/world/starmer-uk-resig...
161,60,2026-05-12-16-49-58 +0000,nypost,Spain reports new hantavirus case in passenger...,https://nypost.com/2026/05/12/health/spain-rep...
296,48,2026-05-12-08-30-52 +0000,bbc,China should stop hoarding food and fertiliser...,https://www.bbc.com/news/articles/cwy2rnyg50zo...
341,45,2026-05-12-00-34-00 +0000,wsj,The Trump administration said it would delay a...,https://www.wsj.com/politics/policy/trump-clea...
142,45,2026-05-12-17-20-00 +0000,wsj,OpenAI’s Sam Altman’s personal investments are...,https://www.wsj.com/tech/ai/sam-altmans-busine...
352,41,2026-05-11-23-45-00 +0000,wsj,The Senate took another procedural step toward...,https://www.wsj.com/economy/central-banking/se...
339,40,2026-05-12-00-45-11 +0000,nyt,Arcadia Mayor Eileen Wang Will Plead Guilty to...,https://www.nytimes.com/2026/05/11/us/arcadia-...
150,39,2026-05-12-17-11-00 +0000,wsj,"Inflation is overtaking Americans’ pay gains, ...",https://www.wsj.com/economy/jobs/prices-at-the...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)