## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-08-54-35 +0000,nyt,"U.S.S. Abraham Lincoln Docks in Thailand, Givi...",https://www.nytimes.com/2026/09/02/world/asia/...
1,2026-09-02-08-53-00 +0000,wsj,Gold at Lowest in Three Weeks as Mideast Tensi...,https://www.wsj.com/finance/commodities-future...
2,2026-09-02-08-39-00 +0000,wsj,Oil Rises as U.S.-Iran Strikes Dim Hopes for H...,https://www.wsj.com/finance/commodities-future...
3,2026-09-02-08-37-00 +0000,wsj,"Euro Falls, Deemed Vulnerable Due to High Ener...",https://www.wsj.com/finance/currencies/yen-con...
4,2026-09-02-08-30-44 +0000,chitri,Today in History: Great Fire of London begins,https://www.chicagotribune.com/2026/09/02/toda...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2467/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
424       trump     32
20         iran     23
466  california     19
561       house     18
128         new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
91,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,107
199,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...,98
58,2026-09-02-03-35-03 +0000,startribune,US military completes latest strikes against I...,https://www.startribune.com/us-military-says-i...,92
181,2026-09-01-21-52-05 +0000,chitri,‘Stop trying to be tough’: PM Mark Carney fire...,https://www.chicagotribune.com/2026/09/01/mark...,89
123,2026-09-02-00-23-08 +0000,nyt,"U.S. Strikes Iran Over Strait of Hormuz Mines,...",https://www.nytimes.com/2026/09/01/us/politics...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
91,107,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
199,98,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...
82,74,2026-09-02-01-59-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
257,67,2026-09-01-18-51-00 +0000,wsj,A Fed governor says the central bank should ac...,https://www.wsj.com/economy/central-banking/a-...
52,62,2026-09-02-03-54-00 +0000,wsj,Massachusetts Sen. Ed Markey beat back a Democ...,https://www.wsj.com/politics/elections/sen-ed-...
207,60,2026-09-01-21-08-16 +0000,wapo,Bessent downplays bond market concerns amid gl...,https://www.washingtonpost.com/business/2026/0...
131,56,2026-09-01-23-50-56 +0000,cbc,"Apple Maps follows Google, changes name of Lak...",https://www.cbc.ca/news/world/apple-maps-lake-...
40,49,2026-09-02-05-14-09 +0000,bbc,Will new uniform rules save parents money?,https://www.bbc.co.uk/news/articles/c750np0726...
154,47,2026-09-01-23-00-52 +0000,nypost,California drivers could bankroll Gavin Newsom...,https://nypost.com/2026/09/01/us-news/californ...
233,44,2026-09-01-20-19-03 +0000,nyt,Two More Oil Tankers Are Attacked in the Strai...,https://www.nytimes.com/2026/09/01/business/sh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)