## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-04-15-52-18 +0000,nyt,"Gloria Steinem Stayed Positive, Even as the Ma...",https://www.nytimes.com/2026/09/04/us/politics...
1,2026-09-04-15-51-44 +0000,nyt,Argentina Is Ramping Up Its Claim to the Falkl...,https://www.nytimes.com/article/falkland-islan...
2,2026-09-04-15-49-02 +0000,bbc,Farage unveils small boats deal with French Na...,https://www.bbc.co.uk/news/articles/c4gk35qnzp...
3,2026-09-04-15-47-21 +0000,nyt,Trump Plans to Use Qatari Jet for Another Over...,https://www.nytimes.com/2026/09/04/us/politics...
4,2026-09-04-15-44-31 +0000,nyt,How to Define the ‘Reasonable’ in Reasonable D...,https://www.nytimes.com/2026/09/04/us/lindsay-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
23    trump     47
69   clancy     17
164    iran     16
237    jobs     15
853   court     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
290,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...,137
380,2026-09-03-18-34-16 +0000,nypost,Vance says no ‘security concern’ behind Trump ...,https://nypost.com/2026/09/03/us-news/vance-sa...,116
147,2026-09-04-11-01-00 +0000,wsj,Vice President JD Vance has many challenges he...,https://www.wsj.com/politics/vances-2028-audit...,113
309,2026-09-03-21-53-00 +0000,wsj,Excavation work on President Trump’s 250-foot-...,https://www.wsj.com/politics/policy/work-on-tr...,112
303,2026-09-03-22-06-54 +0000,chitri,Missouri’s highest court blocks Trump-backed U...,https://www.chicagotribune.com/2026/09/03/miss...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
290,137,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...
147,113,2026-09-04-11-01-00 +0000,wsj,Vice President JD Vance has many challenges he...,https://www.wsj.com/politics/vances-2028-audit...
117,76,2026-09-04-12-11-46 +0000,chitri,US diesel prices hit record high of $5.85 on a...,https://www.chicagotribune.com/2026/09/04/us-d...
254,74,2026-09-04-00-55-45 +0000,bbc,Watch: Inside court as Lindsay Clancy's lawyer...,https://www.bbc.co.uk/news/videos/c36l7jwjg1no...
73,70,2026-09-04-13-43-00 +0000,wsj,"Treasury Yields, Fed Rate-Hike Bets Rise After...",https://www.wsj.com/economy/global/u-s-europea...
230,67,2026-09-04-04-45-00 +0000,wsj,An internal investigation found former Labor S...,https://www.wsj.com/business/former-labor-secr...
221,63,2026-09-04-05-58-19 +0000,nypost,Two trapped workers rescued from hydropower tu...,https://nypost.com/2026/09/04/world-news/nepal...
448,54,2026-09-03-15-59-00 +0000,wsj,GOP leaders are putting Trump front and center...,https://www.wsj.com/politics/elections/trump-f...
404,52,2026-09-03-17-43-33 +0000,latimes,"Fox News cuts ties with Maria Bartiromo, weeks...",https://www.latimes.com/entertainment-arts/bus...
261,47,2026-09-04-00-34-00 +0000,wsj,Missouri’s Supreme Court ruled Thursday the st...,https://www.wsj.com/politics/policy/missouri-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)