## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-03-09-13-54 +0000,bbc,Airlines can cancel flights in advance over fu...,https://www.bbc.com/news/articles/c794zd1vqn4o...
1,2026-05-03-09-12-32 +0000,nyt,Trump Says He Is Reviewing Iran’s Latest Offer...,https://www.nytimes.com/2026/05/02/us/politics...
2,2026-05-03-09-01-34 +0000,nyt,Trump Faces the Complicated Reality of a Costl...,https://www.nytimes.com/2026/05/03/us/politics...
3,2026-05-03-09-01-33 +0000,nyt,The U.S. Set Off a Corruption Scandal That Is ...,https://www.nytimes.com/2026/05/03/world/ameri...
4,2026-05-03-09-01-28 +0000,nyt,Fear and Vigilance Are Now Constant Companions...,https://www.nytimes.com/2026/05/03/us/jewish-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
9   trump     22
12   iran     13
7     new     12
22    war     10
10     he      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
18,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...,69
85,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,67
156,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,66
125,2026-05-02-17-48-47 +0000,nypost,Outrage as California vice mayor posts vile ‘d...,https://nypost.com/2026/05/02/us-news/californ...,56
67,2026-05-03-00-34-18 +0000,nypost,Trump says he’s reviewing latest Iran proposal...,https://nypost.com/2026/05/02/world-news/trump...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
18,69,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
47,49,2026-05-03-03-00-00 +0000,wsj,A mammoth economic stimulus passed last year i...,https://www.wsj.com/world/europe/germany-has-t...
156,44,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...
122,34,2026-05-02-18-08-57 +0000,nyt,New Video Analysis Suggests Suspect in Corresp...,https://www.nytimes.com/2026/05/02/us/politics...
135,30,2026-05-02-16-50-23 +0000,cbc,Jailed Nobel laureate's life at risk if she is...,https://www.cbc.ca/news/world/nobel-peace-priz...
54,26,2026-05-03-02-00-00 +0000,wsj,The U.S. is striving to dominate the drone evo...,https://www.wsj.com/politics/national-security...
131,26,2026-05-02-16-57-00 +0000,wsj,Spirit Airlines Is Shutting Down. Here’s What ...,https://www.wsj.com/business/airlines/if-you-b...
167,26,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
157,24,2026-05-02-13-08-46 +0000,nypost,Gaza flotilla activists — including Greta Thun...,https://nypost.com/2026/05/02/world-news/gaza-...
81,23,2026-05-02-23-16-52 +0000,nyt,Supreme Court Asked to Restore Access to Abort...,https://www.nytimes.com/2026/05/02/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)