## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-00-11-46 +0000,nyt,Colombia Presidential Election Heads to a Runoff,https://www.nytimes.com/2026/05/31/world/ameri...
1,2026-06-01-00-05-00 +0000,wsj,Berkshire Hathaway to Buy Home Builder Taylor ...,https://www.wsj.com/business/deals/berkshire-h...
2,2026-05-31-23-53-50 +0000,bbc,Colombia presidential runoff pits leftist sena...,https://www.bbc.com/news/articles/c1w2xvwq8g9o...
3,2026-05-31-23-52-00 +0000,wsj,The Hedge Fund Veteran Trying to Make His Past...,https://www.wsj.com/finance/investing/the-hedg...
4,2026-05-31-23-39-28 +0000,cbc,Colombian presidential vote headed to run-off ...,https://www.cbc.ca/news/world/colombia-preside...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
17    trump     18
53    china      8
148    city      6
93     your      6
94   minute      5

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-05-31-23-53-50 +0000,bbc,Colombia presidential runoff pits leftist sena...,https://www.bbc.com/news/articles/c1w2xvwq8g9o...,38
4,2026-05-31-23-39-28 +0000,cbc,Colombian presidential vote headed to run-off ...,https://www.cbc.ca/news/world/colombia-preside...,37
124,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...,35
68,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...,34
138,2026-05-31-02-39-00 +0000,wsj,China’s manufacturing activity stayed flat in ...,https://www.wsj.com/economy/china-manufacturin...,34

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,38,2026-05-31-23-53-50 +0000,bbc,Colombia presidential runoff pits leftist sena...,https://www.bbc.com/news/articles/c1w2xvwq8g9o...
68,34,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...
138,34,2026-05-31-02-39-00 +0000,wsj,China’s manufacturing activity stayed flat in ...,https://www.wsj.com/economy/china-manufacturin...
29,30,2026-05-31-21-27-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...
67,26,2026-05-31-17-27-18 +0000,bbc,South Africa made to look like fools over Worl...,https://www.bbc.com/news/articles/c86dxvql3qno...
86,25,2026-05-31-16-00-00 +0000,wsj,"American capitalism is at a crossroads, facing...",https://www.wsj.com/economy/us-capitalism-econ...
101,22,2026-05-31-13-45-48 +0000,cbc,Israeli army captures strategic castle in Leba...,https://www.cbc.ca/news/world/israel-captures-...
32,22,2026-05-31-21-12-00 +0000,wsj,Incoming Fed Chairman Kevin Warsh wants the ce...,https://www.wsj.com/economy/central-banking/ke...
24,19,2026-05-31-21-52-58 +0000,nypost,Silicon Valley giant Meta slashes even more jo...,https://nypost.com/2026/05/31/tech/silicon-val...
20,18,2026-05-31-22-18-06 +0000,nyt,"Release of Tina Peters, Election Denier and Fo...",https://www.nytimes.com/2026/05/31/us/tina-pet...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)