## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-11-21-00-42 +0000,nypost,SI police ‘spread thin’ with less cops on the ...,https://nypost.com/2026/04/11/us-news/si-polic...
1,2026-04-11-21-00-19 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Mara...,https://www.nytimes.com/live/2026/04/11/world/...
2,2026-04-11-20-54-43 +0000,nyt,Someone Has to Be Happy. Why Not Lauren Sánche...,https://www.nytimes.com/2026/04/11/business/la...
3,2026-04-11-20-45-49 +0000,nypost,Eric Swalwell randomly slid into my DMs with b...,https://nypost.com/2026/04/11/us-news/eric-swa...
4,2026-04-11-20-39-30 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/11/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9       iran     33
16     talks     17
10       war     16
58     trump     16
25  swalwell     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-11-21-00-19 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Mara...,https://www.nytimes.com/live/2026/04/11/world/...,116
147,2026-04-11-04-38-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...,107
165,2026-04-11-01-21-53 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,96
152,2026-04-11-03-49-39 +0000,nypost,California Rep. Eric Swalwell slams sexual mis...,https://nypost.com/2026/04/10/us-news/californ...,89
79,2026-04-11-14-22-30 +0000,nyt,Iran Has Been Consistent in War. Will It Be Co...,https://www.nytimes.com/2026/04/11/world/middl...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,116,2026-04-11-21-00-19 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Mara...,https://www.nytimes.com/live/2026/04/11/world/...
147,107,2026-04-11-04-38-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
18,43,2026-04-11-19-58-53 +0000,nypost,Clout-chasing models turn NYC fire station int...,https://nypost.com/2026/04/11/us-news/burning-...
121,41,2026-04-11-09-02-13 +0000,nyt,"As Election Looms, Will Alito Retire, Giving T...",https://www.nytimes.com/2026/04/11/us/politics...
157,38,2026-04-11-02-28-16 +0000,nypost,"Four women detail horrific sexual assault, mis...",https://nypost.com/2026/04/10/us-news/four-wom...
81,36,2026-04-11-14-14-36 +0000,nypost,Iran threatens to attack US Navy ships enterin...,https://nypost.com/2026/04/11/world-news/iran-...
53,29,2026-04-11-17-37-03 +0000,startribune,Reusse: Can you stand them? Here’s one way to ...,https://www.startribune.com/most-popular-minne...
173,28,2026-04-11-00-38-44 +0000,bbc,Artemis II mission was a triumph - now comes t...,https://www.bbc.com/news/articles/cj0v119zp19o...
140,27,2026-04-11-06-50-24 +0000,nypost,Vance arrives in Pakistan for talks with Irani...,https://nypost.com/2026/04/11/us-news/jd-vance...
124,25,2026-04-11-09-00-38 +0000,nyt,"No Doors, No Roof, No Worries: A Tiny Racecar ...",https://www.nytimes.com/2026/04/11/business/ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)