## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-08-10-55-00 +0000,wsj,Fed Minutes Show No Urgency for October Hike,https://www.wsj.com/cfo-journal/fed-minutes-sh...
1,2026-10-08-10-52-50 +0000,bbc,"Russian strike on buses kills 33, say official...",https://www.bbc.co.uk/news/articles/c875pwq134...
2,2026-10-08-10-50-28 +0000,nypost,Missouri high schooler killed after being hit ...,https://nypost.com/2026/10/08/us-news/missouri...
3,2026-10-08-10-49-00 +0000,wsj,U.S. Dollar Trades Higher,https://www.wsj.com/finance/commodities-future...
4,2026-10-08-10-48-15 +0000,bbc,German chancellor greets Burnham with military...,https://www.bbc.co.uk/news/articles/cmwyq34qex...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
204     trump     43
154    school     30
153   chicago     28
155     board     25
117  district     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
40,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...,139
44,2026-10-08-10-00-06 +0000,chitri,Voting in Chicago’s school board elections? Fi...,https://www.chicagotribune.com/2026/10/08/chic...,131
30,2026-10-08-10-00-36 +0000,chitri,2026 Chicago school board races: District 6B,https://www.chicagotribune.com/2026/10/08/chic...,130
24,2026-10-08-10-00-44 +0000,chitri,2026 Chicago school board races: District 4B,https://www.chicagotribune.com/2026/10/08/chic...,130
27,2026-10-08-10-00-41 +0000,chitri,2026 Chicago school board races: District 1A,https://www.chicagotribune.com/2026/10/08/chic...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
40,139,2026-10-08-10-00-12 +0000,chitri,2026 Chicago school board races: Board president,https://www.chicagotribune.com/2026/10/08/2026...
358,119,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...
246,105,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
139,71,2026-10-08-05-50-49 +0000,nypost,Texas executes Jamaal Howard despite same leth...,https://nypost.com/2026/10/08/us-news/texas-ex...
15,68,2026-10-08-10-15-58 +0000,chitri,Will County 2nd District race is a repeat of 2...,https://www.chicagotribune.com/2026/10/08/will...
241,61,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
2,50,2026-10-08-10-50-28 +0000,nypost,Missouri high schooler killed after being hit ...,https://nypost.com/2026/10/08/us-news/missouri...
345,49,2026-10-07-18-24-00 +0000,wsj,Fed officials didn’t make an urgent case for a...,https://www.wsj.com/economy/central-banking/fe...
311,48,2026-10-07-19-42-35 +0000,cbc,'Canada is not our enemy': Michigan Republican...,https://www.cbc.ca/news/world/michigan-republi...
288,45,2026-10-07-20-29-00 +0000,wsj,"In a speech framed by ancient Greek ruins, Sec...",https://www.wsj.com/politics/policy/rubio-turn...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)