## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-16-20-45 +0000,bbc,Gary Lineker among millionaires asking Andy Bu...,https://www.bbc.co.uk/news/articles/cvgjp79m42...
1,2026-07-23-16-20-45 +0000,nyt,‘Odyssey’ Popcorn Buckets Help Fuel a $100 Mil...,https://www.nytimes.com/2026/07/23/business/me...
2,2026-07-23-16-17-44 +0000,bbc,"Saudis must recognise Israel for nuclear deal,...",https://www.bbc.co.uk/news/articles/cwye71yq8w...
3,2026-07-23-16-15-42 +0000,nypost,Trump expanding consumer protections for data ...,https://nypost.com/2026/07/23/us-news/trump-ex...
4,2026-07-23-16-15-41 +0000,nypost,Shocking video shows moment Wisconsin cop fata...,https://nypost.com/2026/07/23/us-news/shocking...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2371/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
22     trump     55
21      deal     27
42      iran     25
127    saudi     22
20   nuclear     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-07-23-12-23-41 +0000,nypost,Trump says Saudi Arabia nuclear deal ‘totally ...,https://nypost.com/2026/07/23/us-news/trump-sa...,157
15,2026-07-23-16-05-00 +0000,wsj,Trump Says Saudi Arabia Must Normalize Relatio...,https://www.wsj.com/world/middle-east/trump-ti...,149
18,2026-07-23-16-03-22 +0000,nyt,"As Part of Nuclear Deal, Trump Demands Saudi A...",https://www.nytimes.com/2026/07/23/us/politics...,148
212,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,147
308,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,157,2026-07-23-12-23-41 +0000,nypost,Trump says Saudi Arabia nuclear deal ‘totally ...,https://nypost.com/2026/07/23/us-news/trump-sa...
5,104,2026-07-23-16-14-02 +0000,nyt,Iran War Live Updates: Attacks in Red Sea Send...,https://www.nytimes.com/live/2026/07/23/world/...
294,72,2026-07-22-22-08-35 +0000,nypost,Ex-NFL kicker Jay Feely likely to face off aga...,https://nypost.com/2026/07/22/us-news/ex-nfl-k...
20,68,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
22,57,2026-07-23-15-57-00 +0000,wsj,A Democratic-backed measure to rein in Preside...,https://www.wsj.com/politics/gop-lawmakers-bac...
266,48,2026-07-22-23-55-25 +0000,latimes,D4vd's garage had signs of blood where girl's ...,https://www.latimes.com/california/story/2026-...
159,47,2026-07-23-10-48-47 +0000,nypost,Google hit with $1 billion EU fine over its Pl...,https://nypost.com/2026/07/23/business/google-...
299,46,2026-07-22-21-55-29 +0000,nypost,Tesla profit disappoints as Elon Musk’s AI spe...,https://nypost.com/2026/07/22/business/tesla-p...
172,39,2026-07-23-10-00-00 +0000,latimes,Hiltzik: Trump's selling Wall Street early acc...,https://www.latimes.com/business/story/2026-07...
59,38,2026-07-23-14-42-00 +0000,wsj,Working-class Americans have experienced a pay...,https://www.wsj.com/economy/jobs/paycheck-boos...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)