## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-24-11-14-29 +0000,nyt,Iran War Live Updates: U.S. and Iran Signal Mo...,https://www.nytimes.com/live/2026/05/24/world/...
1,2026-05-24-11-14-00 +0000,wsj,Trump Says a Deal for Talks With Iran to End W...,https://www.wsj.com/world/middle-east/trump-an...
2,2026-05-24-11-13-07 +0000,nyt,"They Started I.V.F., Then Split. Now Who Gets ...",https://www.nytimes.com/2026/05/24/us/ivf-embr...
3,2026-05-24-11-12-17 +0000,nyt,Israeli Leaders Say Little About Trump’s Poten...,https://www.nytimes.com/2026/05/24/world/middl...
4,2026-05-24-11-12-00 +0000,wsj,Kyiv Suffers One of Ukraine War’s Heaviest Rus...,https://www.wsj.com/world/kyiv-suffers-one-of-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
13       trump     29
0         iran     21
9         deal     15
98  california     11
90        fire      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...,105
146,2026-05-23-18-09-12 +0000,nypost,Iran war agreement being ‘fine-tuned’ as Trump...,https://nypost.com/2026/05/23/world-news/iran-...,96
180,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,90
123,2026-05-23-21-04-14 +0000,nypost,Trump says deal to end Iran war is ‘largely ne...,https://nypost.com/2026/05/23/us-news/trump-sa...,86
1,2026-05-24-11-14-00 +0000,wsj,Trump Says a Deal for Talks With Iran to End W...,https://www.wsj.com/world/middle-east/trump-an...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,105,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...
64,57,2026-05-24-05-13-11 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
45,46,2026-05-24-09-00-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
115,44,2026-05-23-22-14-35 +0000,nypost,Ukraine bracing for ‘significant air attack’ f...,https://nypost.com/2026/05/23/world-news/ukrai...
126,41,2026-05-23-20-45-32 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
97,35,2026-05-24-00-33-52 +0000,nypost,Vile video shows Israeli couple harassed by an...,https://nypost.com/2026/05/23/us-news/israeli-...
178,34,2026-05-23-15-00-47 +0000,nypost,Hakeem Jeffries’ re-election bid boosted by ‘s...,https://nypost.com/2026/05/23/us-news/hakeem-j...
180,30,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...
109,29,2026-05-23-23-20-19 +0000,latimes,Garden Grove's chemical crisis: Thousands flee...,https://www.latimes.com/california/story/2026-...
48,25,2026-05-24-08-23-29 +0000,nypost,AOC tells New Yorkers to ‘pull up’ to Alabama ...,https://nypost.com/2026/05/24/us-news/aoc-tell...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)