## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-13-11-52-17 +0000,nyt,Iran Will Meet With Gulf Arab States as Mideas...,https://www.nytimes.com/2026/09/13/world/middl...
1,2026-09-13-11-51-48 +0000,nyt,How One Man’s Quest for a Musketeer’s Bones Go...,https://www.nytimes.com/2026/09/13/world/europ...
2,2026-09-13-11-51-28 +0000,bbc,Reform's £72m donations 'entirely in line with...,https://www.bbc.co.uk/news/articles/ckgwkeg1vy...
3,2026-09-13-11-30-35 +0000,nyt,"Tom Tiffany, Wisconsin Representative, Sustain...",https://www.nytimes.com/2026/09/13/us/politics...
4,2026-09-13-11-23-42 +0000,bbc,Iran war reshapes Brics ties but also exposes ...,https://www.bbc.co.uk/news/articles/ce8767g4jd...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
69   trump     21
0     iran     12
44     new      8
65     out      7
375    oil      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
128,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,68
185,2026-09-12-12-19-58 +0000,nypost,Trump claims Iran-backed Houthis don’t want to...,https://nypost.com/2026/09/12/us-news/trump-op...,56
8,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...,52
77,2026-09-13-02-00-00 +0000,wsj,Trump insulted Texas Attorney General Ken Paxt...,https://www.wsj.com/politics/elections/republi...,52
161,2026-09-12-15-44-15 +0000,wapo,"As Iran proxies activate in Yemen and Iraq, Tr...",https://www.washingtonpost.com/world/2026/09/1...,47

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
128,68,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
135,38,2026-09-12-18-42-25 +0000,nypost,Attack that closed key Saudi pipeline blamed o...,https://nypost.com/2026/09/12/world-news/attac...
8,31,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...
77,31,2026-09-13-02-00-00 +0000,wsj,Trump insulted Texas Attorney General Ken Paxt...,https://www.wsj.com/politics/elections/republi...
116,31,2026-09-12-20-51-49 +0000,nypost,Lindsay Clancy case eerily similar to bipolar ...,https://nypost.com/2026/09/12/us-news/lindsay-...
114,28,2026-09-12-20-58-48 +0000,nypost,Ukraine is fighting Russian-propped military d...,https://nypost.com/2026/09/12/world-news/ukrai...
87,26,2026-09-13-00-13-06 +0000,nypost,Waymo calls cops on teen riders after detectin...,https://nypost.com/2026/09/12/us-news/waymo-ca...
29,25,2026-09-13-09-08-16 +0000,cbc,1 dead after Iranian commercial ship struck ne...,https://www.cbc.ca/news/world/iranian-commerci...
49,25,2026-09-13-08-00-00 +0000,cbc,Canada's oil windfall may yet wipe out its los...,https://www.cbc.ca/news/politics/canada-oil-pr...
18,24,2026-09-13-10-00-00 +0000,latimes,California prison towns grasp for new jobs aft...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)