## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-13-15-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
1,2026-04-10-13-14-51 +0000,bbc,US inflation jumps to highest level in almost ...,https://www.bbc.com/news/articles/cde56g80xp5o...
2,2026-04-10-13-14-45 +0000,wapo,"Inflation surged in March, fueled by Iran conf...",https://www.washingtonpost.com/business/2026/0...
3,2026-04-10-13-14-44 +0000,bbc,Dolce & Gabbana co-founder steps down as chair,https://www.bbc.com/news/articles/c77m3p8182no...
4,2026-04-10-13-13-47 +0000,nypost,Barron Trump preps for launch of Yerba Mate be...,https://nypost.com/2026/04/10/us-news/barron-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
19      iran     49
28     trump     41
36       war     24
42   lebanon     18
159      new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
5,2026-04-10-13-08-26 +0000,nyt,Iran War Live Updates: Vance Departs for Talks...,https://www.nytimes.com/live/2026/04/10/world/...,193
218,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,166
22,2026-04-10-12-01-20 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,141
221,2026-04-09-21-51-17 +0000,nypost,"Trump goes off on ‘NUT JOBS’ Tucker Carlson, ...",https://nypost.com/2026/04/09/us-news/trump-go...,138
184,2026-04-09-23-11-02 +0000,nyt,"Amid Trump’s Threats, NATO Labors to Survive t...",https://www.nytimes.com/2026/04/09/us/politics...,132

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
5,193,2026-04-10-13-08-26 +0000,nyt,Iran War Live Updates: Vance Departs for Talks...,https://www.nytimes.com/live/2026/04/10/world/...
258,122,2026-04-09-20-18-00 +0000,wsj,First lady Melania Trump denied having ties to...,https://www.wsj.com/politics/melania-trump-den...
218,58,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
136,56,2026-04-10-03-21-00 +0000,wsj,A surge in energy costs triggered by the war i...,https://www.wsj.com/world/china/middle-east-en...
24,55,2026-04-10-12-00-00 +0000,nypost,Beloved NYC restaurant owner’s world crumbled ...,https://nypost.com/2026/04/10/lifestyle/belove...
219,49,2026-04-09-21-53-20 +0000,cbc,Putin claims Russia will enact 32-hour ceasefi...,https://www.cbc.ca/news/world/ukraine-conflict...
278,47,2026-04-09-19-17-15 +0000,nypost,Meta rolls out new AI model in ‘fundamental sh...,https://nypost.com/2026/04/09/business/meta-ro...
206,47,2026-04-09-22-23-35 +0000,latimes,A sea turtle named Meatloaf is fighting to kee...,https://www.latimes.com/california/story/2026-...
365,36,2026-04-09-13-45-07 +0000,nypost,Dramatic video shows Israel bombing Al Jazeera...,https://nypost.com/2026/04/09/world-news/video...
297,35,2026-04-09-18-15-05 +0000,nypost,Missing boater Lynette Hooker was arrested aft...,https://nypost.com/2026/04/09/us-news/missing-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)