## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-14-07-18-25 +0000,bbc,Harry and Meghan arrive in Australia for four-...,https://www.bbc.com/news/articles/cvgk3vpyzdqo...
1,2026-04-14-07-10-00 +0000,wsj,Imperial Brands to Post Rise in Adjusted Opera...,https://www.wsj.com/business/earnings/imperial...
2,2026-04-14-07-09-00 +0000,wsj,Oil Eases on U.S.-Iran Dialogue Hopes Despite ...,https://www.wsj.com/finance/commodities-future...
3,2026-04-14-07-08-24 +0000,bbc,Former Nato chief warns UK's national security...,https://www.bbc.com/news/articles/cje4n5ppgw7o...
4,2026-04-14-07-07-00 +0000,bbc,Carney secures Liberal majority after by-elect...,https://www.bbc.com/news/articles/cp9vmepn010o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
245     trump     54
16       iran     39
20   blockade     31
19     hormuz     21
63        war     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
309,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,178
101,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,173
226,2026-04-13-17-15-47 +0000,nyt,"To Open the Strait of Hormuz, Trump Wants to B...",https://www.nytimes.com/2026/04/13/world/middl...,167
302,2026-04-13-12-13-38 +0000,cbc,Trump warns Iran attack ships will be 'elimina...,https://www.cbc.ca/news/world/livestory/us-isr...,163
326,2026-04-13-10-09-48 +0000,bbc,Starmer says UK will not join Trump's blockade...,https://www.bbc.com/news/articles/c393wxzw4yjo...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
309,178,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...
102,85,2026-04-13-22-55-00 +0000,wsj,Democratic Rep. Eric Swalwell of California an...,https://www.wsj.com/politics/house-removal-vot...
101,80,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
8,61,2026-04-14-06-57-52 +0000,bbc,Oil prices ease on hopes of new US-Iran peace ...,https://www.bbc.com/news/articles/cjr9qrnp821o...
46,58,2026-04-14-02-32-24 +0000,nypost,Trump reveals why he deleted AI post of himsel...,https://nypost.com/2026/04/13/us-news/trump-re...
43,57,2026-04-14-02-47-00 +0000,wsj,Canadian Prime Minister Mark Carney has secure...,https://www.wsj.com/world/americas/canadas-car...
134,55,2026-04-13-21-28-14 +0000,bbc,Hungary's next PM would pick up if Putin calls...,https://www.bbc.com/news/articles/cd6lzezp4zvo...
82,45,2026-04-13-23-49-55 +0000,cbc,How will the U.S. blockade of Iranian ports wo...,https://www.cbc.ca/news/world/us-iranian-ports...
176,36,2026-04-13-19-56-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
24,34,2026-04-14-04-34-00 +0000,wsj,China’s export momentum slowed sharply in Marc...,https://www.wsj.com/economy/trade/china-export...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)