## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-19-05-35 +0000,nypost,Hayden Panettiere’s estranged mom blasts tragi...,https://nypost.com/2026/08/18/us-news/hayden-p...
1,2026-08-18-19-02-39 +0000,nypost,Tungsten mine that surges at times of major wa...,https://nypost.com/2026/08/18/world-news/tungs...
2,2026-08-18-18-56-50 +0000,nyt,"In Los Angeles, the San Fernando Valley Celebr...",https://www.nytimes.com/2026/08/18/us/818-day-...
3,2026-08-18-18-56-00 +0000,wsj,Inside the Race to Build America’s First Nucle...,https://www.wsj.com/finance/investing/inside-t...
4,2026-08-18-18-55-44 +0000,nypost,"Ex-Florida state rep charged with kidnapping, ...",https://nypost.com/2026/08/18/us-news/ex-flori...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2386/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
157  trump     45
53    iran     18
62      up     17
126    new     17
344  trial     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...,115
84,2026-08-18-16-25-18 +0000,chitri,President Donald Trump says US has no talks pl...,https://www.chicagotribune.com/2026/08/18/trum...,95
95,2026-08-18-15-51-00 +0000,wsj,Oil Futures Rise as Trump Says No Iran Talks S...,https://www.wsj.com/finance/commodities-future...,95
124,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...,91
129,2026-08-18-13-47-18 +0000,nypost,"Trump says Strait of Hormuz has been de-mined,...",https://nypost.com/2026/08/18/us-news/trump-sa...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,115,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...
6,64,2026-08-18-18-53-00 +0000,wsj,Sexual misconduct cases are piling up in front...,https://www.wsj.com/politics/sexual-misconduct...
39,60,2026-08-18-17-56-19 +0000,nypost,Minnesota Attorney General Ellison sues Texas ...,https://nypost.com/2026/08/18/us-news/minnesot...
4,56,2026-08-18-18-55-44 +0000,nypost,"Ex-Florida state rep charged with kidnapping, ...",https://nypost.com/2026/08/18/us-news/ex-flori...
219,43,2026-08-18-08-10-32 +0000,wsj,Stock Market Today: Tech Stocks Slide With Bon...,https://www.wsj.com/livecoverage/stock-market-...
299,41,2026-08-17-21-44-32 +0000,nypost,Jared Kushner: Hamas said ‘all the right thing...,https://nypost.com/2026/08/17/world-news/jared...
124,37,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...
237,36,2026-08-18-04-16-42 +0000,bbc,Why Indian law students don't want top judge a...,https://www.bbc.co.uk/news/articles/c171j0k74d...
0,35,2026-08-18-19-05-35 +0000,nypost,Hayden Panettiere’s estranged mom blasts tragi...,https://nypost.com/2026/08/18/us-news/hayden-p...
26,33,2026-08-18-18-20-08 +0000,bbc,"Global borrowing costs hit fresh highs on oil,...",https://www.bbc.co.uk/news/articles/c1k1x1zdyw...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)