## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-18-50-02 +0000,bbc,Burnham announces scheme to help first-time bu...,https://www.bbc.co.uk/news/articles/cv8e33gdw1...
1,2026-09-26-18-40-05 +0000,nyt,Rahm Emanuel Makes His 2026 Play,https://www.nytimes.com/2026/09/26/us/politics...
2,2026-09-26-18-40-00 +0000,wsj,Pope Leo Receives Rockstar Welcome in Secular ...,https://www.wsj.com/world/europe/pope-leo-rece...
3,2026-09-26-18-38-42 +0000,nypost,Hurricane Polo threat remains as LA beaches br...,https://nypost.com/2026/09/26/us-news/hurrican...
4,2026-09-26-18-38-04 +0000,nypost,"Geezer gunners: Illegal Cuban migrants, 89 and...",https://nypost.com/2026/09/26/us-news/cuban-bo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
81   trump     51
77     new     16
384    was     13
477     xi     12
386  china     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
135,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...,134
61,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...,120
245,2026-09-25-20-02-20 +0000,nypost,Trump told China’s Xi that support for Iran wa...,https://nypost.com/2026/09/25/us-news/trump-to...,103
65,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...,101
134,2026-09-26-02-36-07 +0000,chitri,President Trump said he would campaign in midt...,https://www.chicagotribune.com/2026/09/25/trum...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
135,134,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...
61,58,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
65,50,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...
124,46,2026-09-26-07-03-34 +0000,nypost,Ukraine’s Zelensky says he urged Trump to enli...,https://nypost.com/2026/09/26/world-news/ukrai...
25,40,2026-09-26-16-30-10 +0000,nyt,Trump Rejects Iran’s Cease-Fire Proposal to Re...,https://www.nytimes.com/2026/09/26/us/politics...
64,40,2026-09-26-14-05-01 +0000,cbc,Hundreds of thousands turn out for Pope Leo al...,https://www.cbc.ca/news/world/pope-leo-parade-...
168,33,2026-09-25-23-10-33 +0000,nyt,Report Finds Security Failings at Event Where ...,https://www.nytimes.com/2026/09/25/us/utah-val...
127,31,2026-09-26-06-25-29 +0000,nyt,"You Get an Eagle, and You Get an Eagle: Xi Tak...",https://www.nytimes.com/2026/09/25/world/ameri...
37,30,2026-09-26-15-45-00 +0000,wsj,"How Jordan Campbell, a Texas business litigato...",https://www.wsj.com/politics/policy/how-a-busi...
156,29,2026-09-26-00-00-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota doesn’...,https://www.wsj.com/politics/ilhan-omar-is-the...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)