## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-17-17-19-19 +0000,nypost,Irish prime minister addresses how Europe feel...,https://nypost.com/2026/03/17/world-news/irish...
1,2026-03-17-17-17-19 +0000,bbc,"Focus must remain on Ukraine despite Iran war,...",https://www.bbc.com/news/articles/c15xeyny73wo...
2,2026-03-17-17-15-06 +0000,nyt,"In Maine, Janet Mills Slams Graham Platner in ...",https://www.nytimes.com/2026/03/17/us/politics...
3,2026-03-17-17-14-03 +0000,nypost,Celebrations break out across Iran over death ...,https://nypost.com/2026/03/17/world-news/celeb...
4,2026-03-17-17-12-13 +0000,nyt,Iran War Live Updates: Israel Says It Has Kill...,https://www.nytimes.com/live/2026/03/17/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2666/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
43   trump     66
6     iran     56
15     war     37
148    new     18
173    oil     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
18,2026-03-17-16-55-01 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...,279
328,2026-03-16-21-17-23 +0000,nypost,"Vance denies ‘wedge’ with Trump over Iran war,...",https://nypost.com/2026/03/16/us-news/vance-de...,226
9,2026-03-17-17-05-41 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/world/middl...,220
102,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,216
25,2026-03-17-16-43-34 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,208

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
18,279,2026-03-17-16-55-01 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...
70,80,2026-03-17-15-31-43 +0000,bbc,Israel says it killed Iranian security chief A...,https://www.bbc.com/news/articles/c24deezq6meo...
321,73,2026-03-16-21-38-51 +0000,nypost,"Trump slams China, US allies for not jumping a...",https://nypost.com/2026/03/16/world-news/trump...
382,62,2026-03-16-17-57-14 +0000,latimes,Oil flows through Santa Barbara coastal pipeli...,https://www.latimes.com/california/story/2026-...
342,53,2026-03-16-20-37-45 +0000,nypost,Average age of NYC homeowner jumps to stunning...,https://nypost.com/2026/03/16/business/average...
164,51,2026-03-17-11-02-00 +0000,wsj,"This could be a big, big deal: The Senate toda...",https://www.wsj.com/politics/its-showtime-for-...
269,47,2026-03-17-00-34-42 +0000,nypost,Energy secretary tears Gavin Newsom apart for ...,https://nypost.com/2026/03/16/us-news/energy-s...
51,43,2026-03-17-16-02-00 +0000,wsj,Zara Teams Up With Designer John Galliano to S...,https://www.wsj.com/business/retail/zara-teams...
114,38,2026-03-17-13-34-36 +0000,nypost,Mamdani rips Palestinian ‘genocide’ at St. Pat...,https://nypost.com/2026/03/17/us-news/nyc-mayo...
78,37,2026-03-17-15-15-02 +0000,nypost,"Amazon launches 1-hour, 3-hour delivery option...",https://nypost.com/2026/03/17/business/amazon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)