## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-05-41-51 +0000,nyt,How South Korea Uses A.I. to Check on Its Elderly,https://www.nytimes.com/2026/04/28/world/asia/...
1,2026-04-28-05-39-06 +0000,nypost,Colorado grandpa finishes world’s largest jigs...,https://nypost.com/2026/04/28/us-news/colorado...
2,2026-04-28-05-34-00 +0000,nypost,"Kid Rock, Pete Hegseth fly in Army Apache atta...",https://nypost.com/2026/04/28/us-news/kid-rock...
3,2026-04-28-05-33-17 +0000,bbc,In pictures: King Charles and Queen Camilla be...,https://www.bbc.com/news/articles/c86e6z26xdpo...
4,2026-04-28-05-28-00 +0000,wsj,Japan’s Central Bank Makes Hawkish Hold as Boa...,https://www.wsj.com/economy/central-banking/ja...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2523/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
77      trump     41
150      iran     22
118  shooting     17
510        ai     15
397     court     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
155,2026-04-27-19-43-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...,151
13,2026-04-28-04-19-15 +0000,nypost,Jimmy Kimmel repeats ‘hateful’ joke about ‘exp...,https://nypost.com/2026/04/28/us-news/jimmy-ki...,115
36,2026-04-28-02-07-55 +0000,nypost,Mentalist Oz Pearlman won’t appear on ‘Jimmy K...,https://nypost.com/2026/04/27/us-news/mentalis...,108
139,2026-04-27-20-18-06 +0000,nyt,President and First Lady Melania Trump Demand ...,https://www.nytimes.com/2026/04/27/us/politics...,106
228,2026-04-27-14-43-17 +0000,nypost,Melania Trump marks quiet birthday day after ‘...,https://nypost.com/2026/04/27/us-news/melania-...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
155,151,2026-04-27-19-43-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...
291,73,2026-04-27-09-27-55 +0000,nypost,Elon Musk and OpenAI CEO Sam Altman head to co...,https://nypost.com/2026/04/27/business/elon-mu...
178,69,2026-04-27-17-57-06 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
166,62,2026-04-27-19-12-44 +0000,bbc,Neighbours of White House correspondents' dinn...,https://www.bbc.com/news/videos/c77m77krx44o?a...
231,54,2026-04-27-14-36-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
120,48,2026-04-27-21-07-56 +0000,wapo,King Charles’s rare state visit offers U.K. a ...,https://www.washingtonpost.com/politics/2026/0...
147,41,2026-04-27-20-12-17 +0000,nyt,"Oil Rises, and Stocks Tick Higher, as Iran Mak...",https://www.nytimes.com/2026/04/26/business/oi...
99,39,2026-04-27-21-49-42 +0000,nyt,Billionaires Are Dominating California Politic...,https://www.nytimes.com/2026/04/27/us/politics...
48,38,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...
49,35,2026-04-28-01-00-00 +0000,wsj,"Pushing past a third assassination attempt, th...",https://www.wsj.com/politics/policy/pushing-pa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)