## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-17-54-22 +0000,nypost,Bank of America expanding Tunnels to Towers pa...,https://nypost.com/2026/09/08/business/bank-of...
1,2026-09-08-17-51-38 +0000,nyt,"After Causing Delays for 9/11 Health Claims, S...",https://www.nytimes.com/2026/09/08/us/politics...
2,2026-09-08-17-48-37 +0000,bbc,UK announces sanctions on West Bank settlement...,https://www.bbc.co.uk/news/articles/c4g7zen0vv...
3,2026-09-08-17-46-06 +0000,nyt,Patrick Clancy Plans Legal Action Against ‘Rel...,https://www.nytimes.com/2026/09/08/us/patrick-...
4,2026-09-08-17-45-59 +0000,nypost,Swimmer vanishes in ocean off Venice Beach ove...,https://nypost.com/2026/09/08/us-news/swimmer-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
57     trump     34
384      new     23
197    trade     14
95       oil     13
89   tariffs     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
266,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,91
91,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...,83
87,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...,82
188,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...,79
283,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
266,91,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...
91,71,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...
237,54,2026-09-08-09-10-00 +0000,wsj,Oil Nears $100 a Barrel as Fresh Attacks on Sa...,https://www.wsj.com/world/middle-east/oil-near...
94,49,2026-09-08-15-40-32 +0000,chitri,All 5 killed in Miami cargo jet crash were in ...,https://www.chicagotribune.com/2026/09/08/miam...
87,48,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...
36,41,2026-09-08-17-07-04 +0000,nypost,NASCAR legend spills on grand plans for $400M ...,https://nypost.com/2026/09/08/lifestyle/nascar...
264,37,2026-09-08-07-04-00 +0000,wsj,Australian Government to Allow Users to Opt ou...,https://www.wsj.com/economy/australian-govt-to...
188,35,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...
99,35,2026-09-08-15-25-05 +0000,nypost,Benjamin Netanyahu furiously disputes bombshel...,https://nypost.com/2026/09/08/world-news/benja...
200,35,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)