## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-10-06-55 +0000,nyt,Iran War Live Updates: Fighting Intensifies Wi...,https://www.nytimes.com/live/2026/07/18/world/...
1,2026-07-18-10-00-03 +0000,nyt,"Freedom Convoy Leader, Under House Arrest, Wan...",https://www.nytimes.com/2026/07/18/world/canad...
2,2026-07-18-10-00-01 +0000,wapo,"As Beijing ramps up exports, the world feels ‘...",https://www.washingtonpost.com/business/2026/0...
3,2026-07-18-10-00-01 +0000,wapo,He spotted a sports relic in the thrift store....,https://www.washingtonpost.com/nation/2026/07/...
4,2026-07-18-10-00-01 +0000,wapo,Red wolf litters bring hope of ‘incredible com...,https://www.washingtonpost.com/nation/2026/07/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
175   trump     33
127     new     16
25       he     13
129  market     11
0      iran     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...,111
116,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...,90
211,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...,85
126,2026-07-17-21-38-56 +0000,nypost,Trump says Canada must pay new tariffs due to ...,https://nypost.com/2026/07/17/us-news/trump-sa...,81
235,2026-07-17-16-31-00 +0000,wsj,President Trump wants the Republican-controlle...,https://www.wsj.com/politics/policy/save-act-v...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,111,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...
308,61,2026-07-17-12-34-28 +0000,nypost,NYC wakes up to ‘unhealthy’ air quality from C...,https://nypost.com/2026/07/17/us-news/nyc-has-...
116,57,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...
211,52,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...
33,48,2026-07-18-08-59-10 +0000,bbc,Burnham to announce plans for new North Sea oi...,https://www.bbc.co.uk/news/articles/c935yx2z9d...
9,46,2026-07-18-10-00-00 +0000,latimes,West Hollywood faces long recovery from massiv...,https://www.latimes.com/california/story/2026-...
297,45,2026-07-17-13-00-00 +0000,wsj,"The Treasury market looks healthy, but underne...",https://www.wsj.com/finance/investing/how-sky-...
128,39,2026-07-17-21-38-00 +0000,wsj,China’s Moonshot AI Adds More Fuel to Wall Str...,https://www.wsj.com/finance/stocks/chinas-moon...
134,34,2026-07-17-21-24-32 +0000,latimes,Orange County man charged with killing mom in ...,https://www.latimes.com/california/story/2026-...
287,33,2026-07-17-13-39-25 +0000,nypost,Iranian strikes hit major source of Kuwaiti dr...,https://nypost.com/2026/07/17/world-news/irani...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)