## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-12-21-09-10 +0000,nypost,Senator Lindsey Graham’s preliminary cause of ...,https://nypost.com/2026/07/12/us-news/senator-...
1,2026-07-12-21-07-41 +0000,nyt,Live Updates: Cease-Fire Unraveling as U.S. an...,https://www.nytimes.com/live/2026/07/12/us/ira...
2,2026-07-12-21-07-04 +0000,nypost,Woman dies in horror plunge off deadly Laguna ...,https://nypost.com/2026/07/12/us-news/woman-di...
3,2026-07-12-21-07-02 +0000,48hills,46th Jewish Film Fest embraces universal exper...,https://48hills.org/2026/07/46th-jewish-film-f...
4,2026-07-12-21-06-38 +0000,nyt,"Lindsey Graham, Republican Senator and Trump A...",https://www.nytimes.com/2026/07/12/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2539/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
2    graham     27
1   lindsey     25
33    trump     22
12     iran     16
86      new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
66,2026-07-12-17-40-34 +0000,bbc,US senator and close Trump ally Lindsey Graham...,https://www.bbc.co.uk/news/articles/cvgj25j6nm...,114
5,2026-07-12-21-05-09 +0000,startribune,"Sen. Lindsey Graham, a close Trump ally and fo...",https://www.startribune.com/us-senator-lindsey...,113
4,2026-07-12-21-06-38 +0000,nyt,"Lindsey Graham, Republican Senator and Trump A...",https://www.nytimes.com/2026/07/12/us/politics...,111
89,2026-07-12-15-58-00 +0000,wsj,"Longtime Republican Sen. Lindsey Graham dies, ...",https://www.wsj.com/articles/lindsey-graham-in...,109
100,2026-07-12-14-10-02 +0000,nypost,Defiant Sen. Lindsey Graham laughed off Iran p...,https://nypost.com/2026/07/12/us-news/defiant-...,109

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
66,114,2026-07-12-17-40-34 +0000,bbc,US senator and close Trump ally Lindsey Graham...,https://www.bbc.co.uk/news/articles/cvgj25j6nm...
162,58,2026-07-12-01-08-40 +0000,nyt,U.S. Strikes Iran After Iran Fires on Ship in ...,https://www.nytimes.com/2026/07/11/world/middl...
14,56,2026-07-12-20-46-47 +0000,nypost,"Move over, Jaws: Quaint New England beaches fa...",https://nypost.com/2026/07/12/us-news/lions-ma...
89,47,2026-07-12-15-58-00 +0000,wsj,"Longtime Republican Sen. Lindsey Graham dies, ...",https://www.wsj.com/articles/lindsey-graham-in...
15,37,2026-07-12-20-45-50 +0000,nypost,Moment NBA star Brandon Clarke is caught with ...,https://nypost.com/2026/07/12/sports/moment-nb...
85,36,2026-07-12-16-23-19 +0000,nypost,GOP gov candidate Bruce Blakeman compares NYC ...,https://nypost.com/2026/07/12/us-news/bruce-bl...
175,30,2026-07-11-23-18-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
83,27,2026-07-12-16-35-50 +0000,bbc,Former Emir of Qatar Sheikh Hamad bin Khalifa ...,https://www.bbc.co.uk/news/articles/cql1qdq14x...
124,27,2026-07-12-09-30-00 +0000,wsj,The good news from the WSJ survey of economist...,https://www.wsj.com/economy/central-banking/wa...
184,26,2026-07-11-21-29-51 +0000,nypost,Capitalists fight back: NY Dem launches campai...,https://nypost.com/2026/07/11/us-news/ny-democ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)