## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-21-55-04 +0000,chitri,"‘You should not be here,’ President Trump tell...",https://www.chicagotribune.com/2026/09/22/trum...
1,2026-09-22-21-54-53 +0000,nyt,"U.N. Live Updates: As Trump Threatens Iran, Ot...",https://www.nytimes.com/live/2026/09/22/world/...
2,2026-09-22-21-54-51 +0000,nyt,Macron Criticizes Israel and Russia in Final U...,https://www.nytimes.com/2026/09/22/world/europ...
3,2026-09-22-21-51-14 +0000,cbc,Trump flexes 'American power' on UN's biggest ...,https://www.cbc.ca/news/world/trump-un-general...
4,2026-09-22-21-50-31 +0000,bbc,Trump tells UN he has 'big decision' on whethe...,https://www.bbc.co.uk/news/articles/c52e0ywl9p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2270/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
4     trump     85
16     iran     28
129     new     26
34       he     23
27   speech     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
80,2026-09-22-20-27-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,196
154,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...,194
306,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...,188
8,2026-09-22-21-44-00 +0000,wsj,Delegates from Iran and Cuba walked out during...,https://www.wsj.com/politics/policy/trump-thre...,181
308,2026-09-22-10-47-55 +0000,chitri,President Trump says US and Iranian officials ...,https://www.chicagotribune.com/2026/09/22/dona...,178

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
80,196,2026-09-22-20-27-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
306,96,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...
229,70,2026-09-22-15-21-50 +0000,nypost,Trump reveals new nickname for AI — and lays o...,https://nypost.com/2026/09/22/us-news/trump-re...
90,63,2026-09-22-20-10-43 +0000,nyt,Zelensky Says He Hopes Trump Will Help to End ...,https://www.nytimes.com/2026/09/22/world/europ...
291,62,2026-09-22-11-23-04 +0000,nypost,"GOP senator calls for Donald Trump Jr., Hunter...",https://nypost.com/2026/09/22/us-news/gop-sena...
0,45,2026-09-22-21-55-04 +0000,chitri,"‘You should not be here,’ President Trump tell...",https://www.chicagotribune.com/2026/09/22/trum...
160,43,2026-09-22-18-15-23 +0000,nypost,30-year-old Praxis CEO planning AI-powered uto...,https://nypost.com/2026/09/22/business/30-year...
288,42,2026-09-22-11-25-00 +0000,wsj,The Morning Risk Report: Paramount Settles Sta...,https://www.wsj.com/risk-compliance-journal/th...
358,40,2026-09-22-08-24-15 +0000,nypost,Trump signs Greenland deal letting US take ove...,https://nypost.com/2026/09/22/world-news/us-to...
249,39,2026-09-22-14-34-16 +0000,cbc,Family of Black Mississippi teen Nolan Wells r...,https://www.cbc.ca/news/world/grand-jury-no-ch...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)