## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-04-58-13 +0000,nypost,Felon admits to importing radioactive material...,https://nypost.com/2026/10/06/us-news/felon-ad...
1,2026-10-06-04-54-32 +0000,bbc,Community supermarket opens in shopping centre,https://www.bbc.co.uk/news/articles/cqkgjnmx6l...
2,2026-10-06-04-46-11 +0000,nypost,Death row inmate spared after botched Christa ...,https://nypost.com/2026/10/06/us-news/death-ro...
3,2026-10-06-04-39-14 +0000,bbc,OpenAI admits response to Australian governmen...,https://www.bbc.co.uk/news/articles/cmx2qne2j8...
4,2026-10-06-04-33-00 +0000,wsj,Euro Might Weaken if Expectations Ease for ECB...,https://www.wsj.com/finance/currencies/asian-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2325/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
191       new     30
50      trump     28
358     house     20
79   election     18
159     court     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
126,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,175
68,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,116
200,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,102
359,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,92
227,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
126,175,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
68,116,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
227,90,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
94,71,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
152,63,2026-10-05-20-42-19 +0000,bbc,Flávio Bolsonaro rides right-wing wave to win ...,https://www.bbc.co.uk/news/articles/cqj6je4jen...
55,49,2026-10-06-01-30-00 +0000,nypost,Bay Area father leaves 3 young kids home alone...,https://nypost.com/2026/10/05/us-news/morgan-h...
381,44,2026-10-05-10-00-00 +0000,wsj,"Spanish Leader Calls for Elections, Riding Wav...",https://www.wsj.com/world/europe/spains-prime-...
196,42,2026-10-05-19-03-08 +0000,nypost,Sailors reportedly offered $25K per trip to mo...,https://nypost.com/2026/10/05/business/sailors...
353,39,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...
36,37,2026-10-06-02-22-24 +0000,bbc,Fort Hood shooter to be executed by firing squ...,https://www.bbc.co.uk/news/articles/cq8ezkkkrp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)