## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-17-02-33-17 +0000,nypost,Homeless man accused of attack on SF mayor’s b...,https://nypost.com/2026/03/16/us-news/homeless...
1,2026-03-17-02-32-05 +0000,nyt,Lululemon Scrambles to Revive Yoga Pants Empir...,https://www.nytimes.com/2026/03/16/business/lu...
2,2026-03-17-02-31-43 +0000,nypost,Felon posed as porn star while running racket ...,https://nypost.com/2026/03/16/sports/felon-pos...
3,2026-03-17-02-16-27 +0000,nyt,S.E.C.’s Enforcement Chief Abruptly Resigns,https://www.nytimes.com/2026/03/16/us/politics...
4,2026-03-17-02-04-48 +0000,bbc,Trump says presidents 'should not have learnin...,https://www.bbc.com/news/articles/c4gjnwmm984o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
37   trump     59
69    iran     40
70     war     26
240    new     16
297    oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-03-16-21-17-23 +0000,nypost,"Vance denies ‘wedge’ with Trump over Iran war,...",https://nypost.com/2026/03/16/us-news/vance-de...,181
8,2026-03-17-01-58-00 +0000,nyt,Iran War Live Updates: Trump Says He Wants to ...,https://www.nytimes.com/live/2026/03/16/world/...,157
284,2026-03-16-11-00-03 +0000,nypost,Trump briefed that Iran’s new Supreme Leader M...,https://nypost.com/2026/03/16/us-news/trump-br...,146
239,2026-03-16-14-53-29 +0000,nyt,"With Iran War, Trump Risks Stepping on Gains F...",https://www.nytimes.com/2026/03/16/us/politics...,142
136,2026-03-16-20-48-32 +0000,cbc,The broken economic argument for Trump’s war o...,https://www.cbc.ca/player/play/9.7131000?cmp=rss,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,181,2026-03-16-21-17-23 +0000,nypost,"Vance denies ‘wedge’ with Trump over Iran war,...",https://nypost.com/2026/03/16/us-news/vance-de...
187,67,2026-03-16-18-05-00 +0000,wsj,President Trump said White House chief of staf...,https://www.wsj.com/politics/policy/susie-wile...
287,61,2026-03-16-10-58-00 +0000,wsj,The CIA turned to a former Chevron executive t...,https://www.wsj.com/politics/a-rare-peek-behin...
110,57,2026-03-16-21-38-51 +0000,nypost,"Trump slams China, US allies for not jumping a...",https://nypost.com/2026/03/16/world-news/trump...
32,50,2026-03-17-01-00-00 +0000,wsj,"For the fifth year running, Fed officials find...",https://www.wsj.com/economy/central-banking/fe...
137,48,2026-03-16-20-47-27 +0000,nypost,Polymarket bettors allegedly barrage Israeli r...,https://nypost.com/2026/03/16/business/polymar...
193,44,2026-03-16-17-57-14 +0000,latimes,Oil flows through Santa Barbara coastal pipeli...,https://www.latimes.com/california/story/2026-...
42,40,2026-03-17-00-34-42 +0000,nypost,Energy secretary tears Gavin Newsom apart for ...,https://nypost.com/2026/03/16/us-news/energy-s...
330,37,2026-03-16-04-34-08 +0000,nyt,Oscars 2026 Takeaways: ‘One Battle After Anoth...,https://www.nytimes.com/2026/03/15/movies/osca...
309,32,2026-03-16-08-38-41 +0000,wsj,"Stock Market News, March 16, 2026: Dow Jumps, ...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)