## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-16-50-50 +0000,nyt,"Obama Returns to the Trail, Setting Up Dueling...",https://www.nytimes.com/2026/10/24/us/politics...
1,2026-10-24-16-46-26 +0000,chitri,Some US transit systems weigh whether to run t...,https://www.chicagotribune.com/2026/10/24/us-t...
2,2026-10-24-16-45-53 +0000,nyt,Live Updates: Protesters March in France Amid ...,https://www.nytimes.com/live/2026/10/24/world/...
3,2026-10-24-16-44-06 +0000,nypost,NYC-born fitness influencer arrested in Colomb...,https://nypost.com/2026/10/24/world-news/nyc-b...
4,2026-10-24-16-35-47 +0000,nypost,Slain daughter’s friends pen heartbreaking tri...,https://nypost.com/2026/10/24/us-news/sloane-g...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2566/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
8       trump     33
110  election     17
92        new     16
22     france     13
100   ukraine     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,130
250,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,84
244,2026-10-23-19-21-00 +0000,wsj,"Live Q&A: How the economy, inflation and tarif...",https://www.wsj.com/politics/elections/live-q-...,71
255,2026-10-23-18-49-14 +0000,bbc,Trump administration sues to block certificati...,https://www.bbc.co.uk/news/articles/c678pv4krx...,70
147,2026-10-24-01-12-02 +0000,chitri,President Trump at South Florida rally revives...,https://www.chicagotribune.com/2026/10/23/trum...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,130,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
151,57,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
61,52,2026-10-24-12-00-00 +0000,nypost,Bombshell poll finds California voters say sta...,https://nypost.com/2026/10/24/us-news/xavier-b...
150,48,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
38,42,2026-10-24-13-43-05 +0000,bbc,"'My daughter's bed was propped up on books,' s...",https://www.bbc.co.uk/news/articles/c933xpz1kd...
214,38,2026-10-23-20-42-15 +0000,chitri,Wall Street loses ground under pressure from r...,https://www.chicagotribune.com/2026/10/23/wall...
272,37,2026-10-23-17-58-18 +0000,nypost,Ohio Dem Amy Acton’s estranged mom left five-d...,https://nypost.com/2026/10/23/us-news/amy-acto...
147,35,2026-10-24-01-12-02 +0000,chitri,President Trump at South Florida rally revives...,https://www.chicagotribune.com/2026/10/23/trum...
79,35,2026-10-24-10-16-55 +0000,nypost,Man killed in suspected racist attack near Par...,https://nypost.com/2026/10/24/world-news/paris...
40,34,2026-10-24-13-33-23 +0000,chitri,France mobilizes thousands of police to curb v...,https://www.chicagotribune.com/2026/10/24/fran...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)