## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-19-15-42 +0000,nypost,"Trump flanked by Melania, FIFA president and t...",https://nypost.com/2026/07/19/us-news/trump-fl...
1,2026-07-19-19-07-40 +0000,bbc,World Cup final kicks-off with star-studded op...,https://www.bbc.co.uk/news/articles/clyxjl0wkl...
2,2026-07-19-19-07-22 +0000,nypost,CNN’s Van Jones warns far left: ‘STOP pooping ...,https://nypost.com/2026/07/19/us-news/cnns-van...
3,2026-07-19-19-06-37 +0000,nypost,Horror as woman plunges from Boyle Heights bri...,https://nypost.com/2026/07/19/us-news/woman-pl...
4,2026-07-19-18-47-23 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2385/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
7     world     17
39     iran     16
8       cup     15
47   killed     13
147     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
172,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,71
4,2026-07-19-18-47-23 +0000,nyt,Iran War Live Updates: U.S. and Iran Edge Clos...,https://www.nytimes.com/live/2026/07/19/world/...,70
80,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...,69
171,2026-07-18-22-57-00 +0000,wapo,U.S. strikes Iran after 2 service members kill...,https://www.washingtonpost.com/world/2026/07/1...,61
173,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
172,71,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...
80,69,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...
56,37,2026-07-19-15-53-04 +0000,nypost,Andrew Tate arrest video shows moment he tried...,https://nypost.com/2026/07/19/us-news/andrew-t...
173,35,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
66,29,2026-07-19-15-18-37 +0000,nypost,United worker has furious meltdown at Californ...,https://nypost.com/2026/07/19/us-news/united-a...
137,27,2026-07-19-05-43-19 +0000,nypost,US ambassador to UN slaps down Zohran Mamdani’...,https://nypost.com/2026/07/19/us-news/us-ambas...
38,25,2026-07-19-17-19-00 +0000,wsj,Boeing Needs to Shore Up Finances Before Launc...,https://www.wsj.com/business/airlines/boeing-n...
31,22,2026-07-19-17-36-29 +0000,latimes,'The Odyssey' is Christopher Nolan's biggest-e...,https://www.latimes.com/entertainment-arts/bus...
75,22,2026-07-19-14-13-19 +0000,nypost,Liam Payne pal finally off the hook for star’s...,https://nypost.com/2026/07/19/entertainment/li...
110,21,2026-07-19-10-00-00 +0000,startribune,"As Democrats move left, Klobuchar makes a busi...",https://www.startribune.com/klobuchars-governo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)