## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-30-00-10-16 +0000,nypost,Steve Hilton tied with Tom Steyer despite bill...,https://nypost.com/2026/05/29/us-news/steve-hi...
1,2026-05-30-00-05-28 +0000,nyt,Iran War Updates: Trump Puts Off ‘Final Determ...,https://www.nytimes.com/live/2026/05/29/world/...
2,2026-05-30-00-04-48 +0000,missionlocal,"Election Extra! Garry Tan starts spending, and...",https://missionlocal.org/2026/05/sf-garry-tan-...
3,2026-05-30-00-04-26 +0000,nyt,Canadian Man Pleads Guilty to Aiding 14 Suicides,https://www.nytimes.com/2026/05/29/world/canad...
4,2026-05-29-23-58-00 +0000,wsj,Judge Pauses Trump’s ‘Anti-Weaponization’ Fund...,https://www.wsj.com/politics/policy/judge-paus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
15       trump     39
520        new     19
12        iran     16
1564       bee     13
1563  spelling     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
300,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...,116
325,2026-05-29-01-10-16 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,115
320,2026-05-29-01-47-48 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,115
322,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,115
1,2026-05-30-00-05-28 +0000,nyt,Iran War Updates: Trump Puts Off ‘Final Determ...,https://www.nytimes.com/live/2026/05/29/world/...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
300,116,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...
252,112,2026-05-29-10-56-00 +0000,wsj,President Trump’s face could appear on a $250 ...,https://www.wsj.com/politics/policy/white-hous...
113,71,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...
193,59,2026-05-29-15-18-42 +0000,nypost,Trump convenes Situation Room meeting for ‘fin...,https://nypost.com/2026/05/29/us-news/trump-sa...
200,46,2026-05-29-14-50-14 +0000,nypost,NATO vows to ‘defend every inch of Allied terr...,https://nypost.com/2026/05/29/world-news/nato-...
26,44,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...
210,44,2026-05-29-14-21-44 +0000,nypost,Dems ‘simply don’t believe’ Jill Biden’s claim...,https://nypost.com/2026/05/29/media/dems-simpl...
227,42,2026-05-29-13-00-00 +0000,wsj,You Won the Battle on Investment Fees. You’re ...,https://www.wsj.com/finance/investing/you-won-...
29,39,2026-05-29-22-45-05 +0000,nypost,NYC will cut off traffic during 2026 World Cup...,https://nypost.com/2026/05/29/us-news/nyc-will...
132,38,2026-05-29-18-54-40 +0000,latimes,Former California mayor pleads guilty to secre...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)