## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-08-54-34 +0000,nyt,Elon Musk Says Ukraine Violated Starlink’s Rules,https://www.nytimes.com/2026/10/24/world/europ...
1,2026-10-25-08-47-19 +0000,nypost,"British man, 21, who founded his own country r...",https://nypost.com/2026/10/25/world-news/briti...
2,2026-10-25-08-38-03 +0000,nypost,Dramatic footage captures car smashing into ho...,https://nypost.com/2026/10/25/us-news/south-ca...
3,2026-10-25-08-36-47 +0000,bbc,'I cannot teach you integrity': How employee t...,https://www.bbc.co.uk/news/articles/cmz98plpjz...
4,2026-10-25-08-30-28 +0000,chitri,Today in History: Albert B. Fall convicted of ...,https://www.chicagotribune.com/2026/10/25/toda...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
276     trump     25
162  election     15
60        new     12
2     ukraine     12
82      ahead      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
91,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,72
88,2026-10-24-22-59-05 +0000,nypost,Melania Trump hints she could go to Ukraine to...,https://nypost.com/2026/10/24/us-news/melania-...,70
53,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,67
59,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...,62
63,2026-10-25-00-33-41 +0000,nypost,Obama rips Trump for tariffs and White House r...,https://nypost.com/2026/10/24/us-news/obama-ri...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
91,72,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...
59,62,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
109,54,2026-10-24-20-23-36 +0000,chitri,Elon Musk says he was behind Starlink speed re...,https://www.chicagotribune.com/2026/10/24/musk...
74,46,2026-10-24-23-35-22 +0000,chitri,"Brazil’s Lula, Bolsonaro close arguments to vo...",https://www.chicagotribune.com/2026/10/24/braz...
13,42,2026-10-25-06-43-22 +0000,nypost,Arson suspect arrested after fire engulfs Hitl...,https://nypost.com/2026/10/25/world-news/germa...
118,37,2026-10-24-19-16-21 +0000,nypost,NFL House in Paris closes ahead of Saints-Stee...,https://nypost.com/2026/10/24/sports/nfl-house...
57,33,2026-10-25-01-06-17 +0000,nyt,A New Level of Threat and Fear Risks Pushing t...,https://www.nytimes.com/2026/10/24/us/politics...
156,29,2026-10-24-13-33-23 +0000,chitri,France mobilizes thousands of police to curb v...,https://www.chicagotribune.com/2026/10/24/fran...
121,28,2026-10-24-19-09-47 +0000,chitri,Israelis hold final rally against Netanyahu be...,https://www.chicagotribune.com/2026/10/24/isra...
63,23,2026-10-25-00-33-41 +0000,nypost,Obama rips Trump for tariffs and White House r...,https://nypost.com/2026/10/24/us-news/obama-ri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)