## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-13-21-12-43 +0000,nypost,Dramatic scenes near SoFi Stadium as police ra...,https://nypost.com/2026/06/13/sports/snipers-s...
1,2026-06-13-21-02-16 +0000,bbc,"Healey wanted UK to join global defence bank, ...",https://www.bbc.com/news/articles/ce8jyd85ejeo...
2,2026-06-13-21-02-08 +0000,nypost,Top Puerto Rican NYPD chief reflects on climbi...,https://nypost.com/2026/06/13/us-news/top-puer...
3,2026-06-13-21-00-00 +0000,wsj,The Iranian Enforcer Driving Tehran’s Hard Bar...,https://www.wsj.com/world/middle-east/the-iran...
4,2026-06-13-20-57-13 +0000,nypost,NYC police watchdog launches internal review o...,https://nypost.com/2026/06/13/us-news/cop-prob...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
75  trump     28
9   world     18
10    cup     16
71   iran     14
61    new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-06-13-20-40-35 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...,88
145,2026-06-13-02-15-27 +0000,nypost,Trump expected to attend World Cup final in Ne...,https://nypost.com/2026/06/12/us-news/trump-ex...,80
48,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...,78
27,2026-06-13-19-14-50 +0000,wapo,"U.S. and Iran to close deal within a day, Trum...",https://www.washingtonpost.com/world/2026/06/1...,71
33,2026-06-13-18-39-26 +0000,bbc,Trump says US-Iran deal to be signed on Sunday...,https://www.bbc.com/news/articles/cvglmn49xz0o...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,88,2026-06-13-20-40-35 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...
0,61,2026-06-13-21-12-43 +0000,nypost,Dramatic scenes near SoFi Stadium as police ra...,https://nypost.com/2026/06/13/sports/snipers-s...
139,44,2026-06-13-03-38-00 +0000,nypost,Tren de Aragua leader killed in dramatic US ai...,https://nypost.com/2026/06/12/us-news/tren-de-...
65,35,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...
169,33,2026-06-12-23-56-52 +0000,latimes,A fugitive was wanted for 2 killings in Califo...,https://www.latimes.com/california/story/2026-...
150,29,2026-06-13-01-58-31 +0000,nypost,Humiliated Putin forced to cancel Russia Day i...,https://nypost.com/2026/06/12/world-news/humil...
162,26,2026-06-13-00-20-34 +0000,nyt,Two Dan Sullivans? Alaska Republicans Suggest ...,https://www.nytimes.com/2026/06/12/us/politics...
10,25,2026-06-13-20-39-10 +0000,nypost,NYC Councilwoman failed to disclose free rent ...,https://nypost.com/2026/06/13/us-news/nyc-coun...
183,23,2026-06-12-22-18-00 +0000,wsj,Justice Department Clears Paramount-Warner Bro...,https://www.wsj.com/business/media/justice-dep...
81,23,2026-06-13-13-05-24 +0000,nypost,"‘Biased’ Apple, Google, MSN, Yahoo news apps r...",https://nypost.com/2026/06/13/us-news/biased-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)