## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-29-02-47-08 +0000,bbc,Japan earthquake: What we know so far,https://www.bbc.co.uk/news/articles/cgewgxlpj3...
1,2026-07-29-02-41-08 +0000,nypost,Heart-pounding moment woman rescued from SoCal...,https://nypost.com/2026/07/28/us-news/dramatic...
2,2026-07-29-02-37-44 +0000,nyt,Japan Races to Reach People Trapped After Eart...,https://www.nytimes.com/2026/07/28/world/asia/...
3,2026-07-29-02-30-50 +0000,bbc,Trump administration bans new Chinese humanoid...,https://www.bbc.co.uk/news/articles/cp9e2ex3ek...
4,2026-07-29-02-26-00 +0000,wsj,Australia Inflation Cooled in Second Quarter,https://www.wsj.com/economy/central-banking/au...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
19    trump     42
22      new     22
46     iran     20
70   graham     19
400      ai     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
124,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,133
348,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,112
197,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,102
232,2026-07-28-17-39-53 +0000,nypost,Senate confirms Manhattan US Attorney Jay Clay...,https://nypost.com/2026/07/28/us-news/senate-c...,102
260,2026-07-28-16-31-19 +0000,chitri,Benjamin Netanyahu praises first meeting with ...,https://www.chicagotribune.com/2026/07/28/trum...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
124,133,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
42,72,2026-07-29-00-36-00 +0000,wsj,"With the Iran war continuing, Israeli Prime Mi...",https://www.wsj.com/world/middle-east/netanyah...
258,63,2026-07-28-16-32-23 +0000,nypost,Gavin Newsom responds to Ruby Rippey’s claims ...,https://nypost.com/2026/07/28/us-news/gavin-ne...
116,50,2026-07-28-21-41-00 +0000,wsj,The Trump administration plans to halt a Medic...,https://www.wsj.com/politics/policy/medicare-d...
156,46,2026-07-28-20-43-16 +0000,startribune,Elon Musk’s AI company seeks to block Minnesot...,https://www.startribune.com/elon-musks-ai-comp...
171,44,2026-07-28-20-07-09 +0000,cbc,15-year-old arrested in Seattle festival shoot...,https://www.cbc.ca/news/world/seattle-shooting...
220,40,2026-07-28-18-08-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
395,40,2026-07-28-05-45-29 +0000,wsj,"Stock Market July 28, 2026: Dow Rallies, Chip ...",https://www.wsj.com/livecoverage/stock-market-...
254,39,2026-07-28-16-39-20 +0000,nypost,Fourth major heatwave expected to hit France a...,https://nypost.com/2026/07/28/world-news/fourt...
32,39,2026-07-29-01-00-00 +0000,wsj,"By the time the Federal Reserve meets, Wall St...",https://www.wsj.com/economy/central-banking/wh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)