## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-07-17-05-49 +0000,nypost,Long Island motorist fatally runs down homeles...,https://nypost.com/2026/10/07/us-news/long-isl...
1,2026-10-07-17-00-00 +0000,wapo,Maryland candidate for governor disavows son’s...,https://www.washingtonpost.com/dc-md-va/2026/1...
2,2026-10-07-16-58-48 +0000,nyt,Man Posing as ICE Agent at Miami Polling Site ...,https://www.nytimes.com/2026/10/07/us/miami-ic...
3,2026-10-07-16-54-17 +0000,bbc,Canada suspends plans to expand assisted dying...,https://www.bbc.co.uk/news/articles/cqd09g0gj5...
4,2026-10-07-16-50-15 +0000,nypost,The world has nearly burned through its oil st...,https://nypost.com/2026/10/07/business/the-wor...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2317/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
109    trump     35
113      new     20
274  christa     13
174   russia     13
179   plague     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
411,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,118
29,2026-10-07-16-02-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...,101
68,2026-10-07-14-50-28 +0000,bbc,Trump to speak to Putin about plague lab worke...,https://www.bbc.co.uk/news/articles/cqgm0vrl3x...,88
347,2026-10-06-21-14-28 +0000,latimes,Lopez: 'Take out' L.A. or San Diego? This buff...,https://www.latimes.com/california/story/2026-...,82
266,2026-10-07-01-57-12 +0000,cbc,Trump says call scheduled with Putin to discus...,https://www.cbc.ca/news/world/pneumonic-plague...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
411,118,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
278,79,2026-10-07-00-18-00 +0000,wsj,The civil lawsuit a young woman recently filed...,https://www.wsj.com/us-news/law/cornell-sexual...
295,73,2026-10-06-23-04-37 +0000,nypost,Russia accused of covering up plague outbreak ...,https://nypost.com/2026/10/06/world-news/russi...
121,68,2026-10-07-12-41-55 +0000,nypost,New Cornell footage shows frat bros telling in...,https://nypost.com/2026/10/07/us-news/cornell-...
29,62,2026-10-07-16-02-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
333,58,2026-10-06-21-32-09 +0000,cbc,Tennessee inmate Christa Pike awake and speaki...,https://www.cbc.ca/news/world/christa-pike-spe...
339,57,2026-10-06-21-29-32 +0000,missionlocal,‘We need a jingle’: Will voters know the ‘Yes-...,https://missionlocal.org/2026/10/california-bi...
265,50,2026-10-07-01-57-14 +0000,nypost,"Troy Jackson trashes voter ID policy, relies o...",https://nypost.com/2026/10/06/us-news/troy-jac...
349,49,2026-10-06-21-12-30 +0000,nyt,S&P 500 Hits Record High Amid Rising Interest ...,https://www.nytimes.com/2026/10/06/business/st...
177,46,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)