## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-19-54-00 +0000,wsj,The House of Representatives voted to hold bil...,https://www.wsj.com/politics/policy/house-vote...
1,2026-09-16-19-51-44 +0000,nypost,Bone found on California beach linked to fishe...,https://nypost.com/2026/09/16/us-news/human-bo...
2,2026-09-16-19-50-53 +0000,nyt,What to know about the Fed’s decision.,https://www.nytimes.com/live/2026/09/16/busine...
3,2026-09-16-19-48-30 +0000,nypost,Muslim nations condemn ‘heinous attacks’ after...,https://nypost.com/2026/09/16/world-news/musli...
4,2026-09-16-19-47-09 +0000,nyt,At Least 21 Dead in Gaza After Building Collap...,https://www.nytimes.com/2026/09/16/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2337/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
37   trump     48
484     ai     27
18     fed     21
378    new     18
562    war     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
393,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...,201
80,2026-09-16-18-13-13 +0000,nypost,EU boss proposes making Canada associate membe...,https://nypost.com/2026/09/16/world-news/eu-bo...,106
138,2026-09-16-15-59-54 +0000,nyt,Trump’s Latest Threats Loom Over Fed’s Interes...,https://www.nytimes.com/2026/09/16/business/ec...,105
327,2026-09-16-03-01-01 +0000,nyt,House Directs Trump to Halt War With Iran or S...,https://www.nytimes.com/2026/09/15/us/election...,104
171,2026-09-16-14-19-58 +0000,chitri,Trump administration hits South Africa with ne...,https://www.chicagotribune.com/2026/09/16/trum...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
393,201,2026-09-15-21-35-00 +0000,wsj,Trump is threatening to block the Kennedy Cent...,https://www.wsj.com/politics/policy/the-kenned...
17,87,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
315,80,2026-09-16-05-14-00 +0000,wsj,"Oil Falls, Asian Stocks Rise Ahead of Fed Rate...",https://www.wsj.com/finance/stocks/oil-falls-a...
418,74,2026-09-15-20-47-00 +0000,wsj,The U.S. is pressuring Mexico to accept new ru...,https://www.wsj.com/economy/trade/u-s-pressure...
256,58,2026-09-16-10-00-00 +0000,wsj,Security gaps at Utah Valley University last S...,https://www.wsj.com/us-news/charlie-kirks-wido...
80,58,2026-09-16-18-13-13 +0000,nypost,EU boss proposes making Canada associate membe...,https://nypost.com/2026/09/16/world-news/eu-bo...
165,52,2026-09-16-14-43-23 +0000,nyt,News Helicopter Crash and Bus Accident in Los ...,https://www.nytimes.com/2026/09/15/us/los-ange...
31,47,2026-09-16-19-21-00 +0000,wsj,The Fed voted unanimously to raise rates for t...,https://www.wsj.com/economy/central-banking/fe...
302,44,2026-09-16-07-32-52 +0000,nypost,South Korean court orders North Korea to pay $...,https://nypost.com/2026/09/16/world-news/south...
65,40,2026-09-16-18-27-07 +0000,nypost,Worst guard dog in the world exposed by Ring c...,https://nypost.com/2026/09/16/us-news/golden-r...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)