## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-04-15-50 +0000,nypost,Disgraced Eric Swalwell must return $30k in do...,https://nypost.com/2026/06/17/us-news/disgrace...
1,2026-06-17-04-11-55 +0000,nypost,Massive barn blaze kills 17 horses in famous u...,https://nypost.com/2026/06/17/us-news/massive-...
2,2026-06-17-04-04-49 +0000,nypost,Voters pick replacement for disgraced ex-congr...,https://nypost.com/2026/06/17/us-news/voters-r...
3,2026-06-17-03-56-40 +0000,nypost,Mamdani-backed House hopeful Darializa Avila C...,https://nypost.com/2026/06/16/us-news/mamdani-...
4,2026-06-17-03-43-19 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/16/us/geo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     35
49    iran     29
247    new     22
50     war     17
511   deal     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
209,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...,117
6,2026-06-17-03-36-59 +0000,nyt,Iran War Live Updates: Trump Says He Hopes to ...,https://www.nytimes.com/live/2026/06/16/world/...,113
110,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...,112
142,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...,110
335,2026-06-16-08-07-32 +0000,bbc,"Trump may release US-Iran deal before Friday, ...",https://www.bbc.com/news/articles/ce8mv6l6eezo...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
209,117,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...
7,87,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
342,67,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
201,62,2026-06-16-17-14-32 +0000,nypost,Terrified woman backed out of bungee jump mome...,https://nypost.com/2026/06/16/world-news/woman...
212,54,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
110,49,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
43,48,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
331,45,2026-06-16-09-00-00 +0000,wsj,The Liberty Justice Center won its biggest-eve...,https://www.wsj.com/politics/policy/how-a-cons...
169,37,2026-06-16-18-53-45 +0000,nyt,"Merlin, the Duck in a Mexico World Cup Team Je...",https://www.nytimes.com/2026/06/16/world/ameri...
42,36,2026-06-17-01-01-33 +0000,nyt,Kevin Hern Wins Republican Primary for Oklahom...,https://www.nytimes.com/2026/06/16/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)