## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-01-22-55-21 +0000,missionlocal,Meet the District 6 candidate: What limits sho...,https://missionlocal.org/2026/09/meet-the-dist...
1,2026-09-01-22-47-40 +0000,nypost,Embattled Rep. Chuck Edwards censured for ‘ina...,https://nypost.com/2026/09/01/us-news/embattle...
2,2026-09-01-22-47-35 +0000,cbc,"Hannah Einbinder, Emma Seligman and others sig...",https://www.cbc.ca/news/entertainment/open-let...
3,2026-09-01-22-45-56 +0000,nyt,Some Allies Are Pushing Back on Trump’s Econom...,https://www.nytimes.com/2026/09/01/world/europ...
4,2026-09-01-22-42-28 +0000,nypost,Artists scooped up this SoCal beach retreat fo...,https://nypost.com/2026/09/01/real-estate/soca...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2321/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
41        trump     34
108        iran     23
128         new     23
97   california     18
53        house     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
401,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...,103
65,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...,97
373,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...,93
43,2026-09-01-21-52-05 +0000,chitri,‘Stop trying to be tough’: PM Mark Carney fire...,https://www.chicagotribune.com/2026/09/01/mark...,87
31,2026-09-01-22-17-32 +0000,nyt,"U.S. Strikes Iran Over Strait of Hormuz Mines,...",https://www.nytimes.com/2026/09/01/us/politics...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
401,103,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...
65,97,2026-09-01-21-22-00 +0000,wsj,Iran and the U.S. continued tit-for-tat strike...,https://www.wsj.com/politics/policy/u-s-launch...
52,75,2026-09-01-21-43-32 +0000,nypost,Bank of America exec killed by Times Square ma...,https://nypost.com/2026/09/01/us-news/bank-of-...
139,63,2026-09-01-18-51-00 +0000,wsj,A Fed governor says the central bank should ac...,https://www.wsj.com/economy/central-banking/a-...
250,61,2026-09-01-13-32-03 +0000,wapo,17-year-old girl charged with murder in live-s...,https://www.washingtonpost.com/nation/2026/08/...
75,54,2026-09-01-21-08-16 +0000,wapo,Bessent downplays bond market concerns amid gl...,https://www.washingtonpost.com/business/2026/0...
411,53,2026-08-31-23-33-00 +0000,wsj,Vice President JD Vance attacked Abdul El-Saye...,https://www.wsj.com/politics/elections/vance-t...
237,48,2026-09-01-14-24-02 +0000,nyt,"Keir Starmer, Former UK Prime Minister, Says H...",https://www.nytimes.com/2026/09/01/world/europ...
334,45,2026-09-01-09-00-00 +0000,wapo,Lake Ontario is now Lake America. Residents of...,https://www.washingtonpost.com/politics/2026/0...
80,45,2026-09-01-21-04-00 +0000,wsj,"U.S. Stocks Fall as Oil, Bond Yields Spike, U....",https://www.wsj.com/finance/investing/u-s-stoc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)