## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-31-23-15-17 +0000,bbc,Trump administration drops Reflecting Pool van...,https://www.bbc.co.uk/news/articles/cz05yx5dd7...
1,2026-07-31-23-11-04 +0000,wapo,"Migrants overrun a Spanish outpost, stirring E...",https://www.washingtonpost.com/world/2026/07/3...
2,2026-07-31-23-09-00 +0000,wsj,Prosecutors Drop Case Against Olympic Canoeist...,https://www.wsj.com/us-news/law/prosecutors-dr...
3,2026-07-31-23-08-41 +0000,nyt,Charges Dropped Against Ex-Olympian David Hear...,https://www.nytimes.com/2026/07/31/us/david-he...
4,2026-07-31-23-05-16 +0000,nyt,Trump and Netanyahu May Be at Odds Again Over ...,https://www.nytimes.com/2026/07/31/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2506/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
0       trump     42
10   migrants     17
37       plan     17
116      iran     15
334        up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
383,2026-07-30-23-30-00 +0000,cbc,Trump says 'Board of Peace' reaches deal for H...,https://www.cbc.ca/news/world/board-of-peace-g...,105
129,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,104
241,2026-07-31-13-29-17 +0000,chitri,President Donald Trump announces a deal for Ha...,https://www.chicagotribune.com/2026/07/31/trum...,100
292,2026-07-31-10-23-17 +0000,cbc,"Trump touts Gaza peace deal, though Hamas and ...",https://www.cbc.ca/news/world/hamas-israel-dis...,100
234,2026-07-31-14-04-38 +0000,nypost,Read full text of ‘Road Map’ to implement Trum...,https://nypost.com/2026/07/31/us-news/read-ful...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
383,105,2026-07-30-23-30-00 +0000,cbc,Trump says 'Board of Peace' reaches deal for H...,https://www.cbc.ca/news/world/board-of-peace-g...
334,79,2026-07-31-08-02-28 +0000,nypost,At least 18 migrants dead as 49K breached bord...,https://nypost.com/2026/07/31/world-news/at-le...
38,70,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...
231,66,2026-07-31-14-19-00 +0000,wsj,Three Fed policymakers said stubborn inflation...,https://www.wsj.com/economy/central-banking/tw...
256,63,2026-07-31-12-57-09 +0000,chitri,Senior FIFA executive says staff was deceived ...,https://www.chicagotribune.com/2026/07/31/fifa...
10,56,2026-07-31-22-58-15 +0000,chitri,Justice Department drops criminal case against...,https://www.chicagotribune.com/2026/07/31/crim...
245,53,2026-07-31-13-20-45 +0000,nyt,Europe Is Caught Between Low Gas Reserves and ...,https://www.nytimes.com/2026/07/31/business/eu...
356,43,2026-07-31-03-21-37 +0000,nypost,Netflix star Nirmal Purja among 10 missing aft...,https://nypost.com/2026/07/30/world-news/world...
219,43,2026-07-31-14-53-12 +0000,nypost,Sen. Bernie Moreno demands national security p...,https://nypost.com/2026/07/31/us-news/sen-bern...
366,43,2026-07-31-01-31-50 +0000,bbc,Amazon and Apple just told us more about their...,https://www.bbc.co.uk/news/articles/cp87m46g39...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)