## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-14-14-38-58 +0000,nypost,Stranger who battered male model while wearing...,https://nypost.com/2026/05/14/world-news/stran...
1,2026-05-14-14-36-44 +0000,bbc,Streeting resigns and criticises government's ...,https://www.bbc.com/news/articles/cgkpr6y3266o...
2,2026-05-14-14-36-24 +0000,nyt,"Live Updates: After Xi’s Warning on Taiwan, He...",https://www.nytimes.com/live/2026/05/13/world/...
3,2026-05-14-14-35-55 +0000,nypost,Disgraced ex-Newsom aide Dana Williamson to co...,https://nypost.com/2026/05/14/us-news/disgrace...
4,2026-05-14-14-35-28 +0000,bbc,Cost of living concerns in St Helier Central,https://www.bbc.com/news/articles/c5yepzkrdd1o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2655/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
21   trump     73
70   china     44
17      xi     31
317    new     28
197    war     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...,194
149,2026-05-14-09-23-29 +0000,nypost,"Taiwan says no surprises from Trump-Xi summit,...",https://nypost.com/2026/05/14/us-news/taiwan-s...,193
230,2026-05-14-02-08-48 +0000,nypost,Trump greets Xi in Beijing to kick off histori...,https://nypost.com/2026/05/13/us-news/trump-gr...,190
125,2026-05-14-10-47-10 +0000,nypost,Trump sets date for Xi Jinping White House vis...,https://nypost.com/2026/05/14/us-news/trump-in...,187
204,2026-05-14-04-40-36 +0000,nypost,Xi raises prospect of a future US-China war in...,https://nypost.com/2026/05/14/us-news/xi-raise...,184

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,194,2026-05-14-08-00-53 +0000,nypost,"‘Lion’-like Trump deploys ‘power move’ as he, ...",https://nypost.com/2026/05/14/us-news/lion-lik...
310,131,2026-05-13-21-29-00 +0000,wsj,"Kevin Warsh is officially the new Fed chair, t...",https://www.wsj.com/politics/policy/warsh-conf...
67,67,2026-05-14-13-00-05 +0000,nyt,A Fact Check of Trump’s Claims on Inflation an...,https://www.nytimes.com/2026/05/14/us/politics...
291,54,2026-05-13-22-29-26 +0000,latimes,Vance says $1.3 billion in Medicaid payments t...,https://www.latimes.com/california/story/2026-...
234,46,2026-05-14-01-44-00 +0000,wsj,The Pentagon abruptly canceled deployment of a...,https://www.wsj.com/politics/national-security...
233,45,2026-05-14-02-00-00 +0000,wsj,Jerome Powell is wrapping up eight hazard-fill...,https://www.wsj.com/economy/central-banking/ho...
39,44,2026-05-14-13-36-51 +0000,nypost,Taiwan becomes flashpoint of Trump-Xi summit a...,https://nypost.com/2026/05/14/us-news/taiwan-b...
17,41,2026-05-14-14-12-56 +0000,nyt,"Who Is Wes Streeting, the Cabinet Minister Who...",https://www.nytimes.com/2026/05/14/world/europ...
139,40,2026-05-14-10-00-00 +0000,latimes,Another Californian was exposed to hantavirus ...,https://www.latimes.com/california/story/2026-...
277,40,2026-05-13-23-00-36 +0000,bbc,Alberta judge tosses out petition for province...,https://www.bbc.com/news/articles/clypn8py4zwo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)