## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-02-43-52 +0000,nyt,Cassidy Fights to Hang on in Louisiana Race as...,https://www.nytimes.com/2026/05/16/us/politics...
1,2026-05-17-02-43-31 +0000,nyt,Senate Ruling Threatens Ballroom Funding in G....,https://www.nytimes.com/2026/05/16/us/politics...
2,2026-05-17-02-32-57 +0000,latimes,Woman killed in Santa Monica after crawling un...,https://www.latimes.com/california/story/2026-...
3,2026-05-17-02-32-50 +0000,nyt,How a Nature Cruise Turned Into a Nightmare,https://www.nytimes.com/2026/05/16/world/europ...
4,2026-05-17-02-30-31 +0000,nypost,Kevin Warsh’s first challenge as Fed Chair is ...,https://nypost.com/2026/05/16/business/kevin-w...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
5     trump     26
17   killed     10
327  strike      8
520  leader      8
267     new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-05-16-03-55-42 +0000,nypost,US and Nigerian forces kill top ISIS leader hi...,https://nypost.com/2026/05/15/us-news/us-and-n...,69
114,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,66
71,2026-05-16-21-03-29 +0000,nyt,Trump Says a Top ISIS Leader Was Killed in a U...,https://www.nytimes.com/2026/05/16/world/afric...,64
68,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...,57
103,2026-05-16-17-01-10 +0000,nyt,Trump Calls Xi a ‘Friend.’ But He Left China W...,https://www.nytimes.com/2026/05/16/world/europ...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,69,2026-05-16-03-55-42 +0000,nypost,US and Nigerian forces kill top ISIS leader hi...,https://nypost.com/2026/05/15/us-news/us-and-n...
44,40,2026-05-16-23-10-22 +0000,nypost,Hochul pushed LIRR strike to pick up votes on ...,https://nypost.com/2026/05/16/us-news/hochul-p...
84,38,2026-05-16-19-52-53 +0000,nypost,Recovery operation for Italian divers killed i...,https://nypost.com/2026/05/16/world-news/recov...
107,29,2026-05-16-16-42-27 +0000,nypost,Terror not ruled out as 8 injured after suspec...,https://nypost.com/2026/05/16/world-news/many-...
179,28,2026-05-16-03-07-33 +0000,nypost,"Eric Trump accuses Jen Psaki, MS NOW of airing...",https://nypost.com/2026/05/15/us-news/eric-tru...
23,27,2026-05-17-00-45-22 +0000,nypost,"‘Timmy’ the humpback whale, subject of heroic ...",https://nypost.com/2026/05/16/world-news/humpb...
25,25,2026-05-17-00-40-23 +0000,latimes,The world's largest wildlife crossing and five...,https://www.latimes.com/california/story/2026-...
131,23,2026-05-16-14-14-19 +0000,bbc,Freight train and bus crash kills at least eig...,https://www.bbc.com/news/articles/c98rez3x0nwo...
54,23,2026-05-16-22-25-58 +0000,nypost,Veteran Maldivian diver alleges Italian scuba ...,https://nypost.com/2026/05/16/world-news/veter...
153,22,2026-05-16-11-00-00 +0000,startribune,Bites from these northern Minnesota ticks can ...,https://www.startribune.com/mn-ticks-carry-alp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)