## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-14-28-51 +0000,nyt,Lebanese Army Accuses Israeli Troops of Firing...,https://www.nytimes.com/2026/07/21/world/middl...
1,2026-07-21-14-28-06 +0000,nypost,Horrific wrong-way crash in California kills o...,https://nypost.com/2026/07/21/us-news/horrific...
2,2026-07-21-14-25-22 +0000,bbc,VAT to be cut from household electricity bills...,https://www.bbc.co.uk/news/articles/cjwxll8jyz...
3,2026-07-21-14-24-29 +0000,nyt,"1,700 H.I.V. Treatment Sites Closed After Trum...",https://www.nytimes.com/2026/07/21/health/hiv-...
4,2026-07-21-14-22-31 +0000,nypost,College students get first payout in $284M fin...,https://nypost.com/2026/07/21/lifestyle/colleg...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
276      new     40
31     trump     37
143     iran     30
107  burnham     26
48      will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
168,2026-07-21-06-40-50 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,125
302,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...,116
110,2026-07-21-10-12-33 +0000,nyt,New UK Prime Minister Burnham Promises Hope an...,https://www.nytimes.com/2026/07/21/world/europ...,113
75,2026-07-21-12-01-06 +0000,nyt,"Burnham, UK’s New Prime Minister, Starts With ...",https://www.nytimes.com/2026/07/21/world/europ...,110
369,2026-07-20-17-07-50 +0000,nypost,Enraged Trump warns Iran each US soldier kille...,https://nypost.com/2026/07/20/us-news/enraged-...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
168,125,2026-07-21-06-40-50 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
369,106,2026-07-20-17-07-50 +0000,nypost,Enraged Trump warns Iran each US soldier kille...,https://nypost.com/2026/07/20/us-news/enraged-...
185,67,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
266,64,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
364,47,2026-07-20-17-17-51 +0000,nypost,Judge pauses Paramount’s $110B acquisition of ...,https://nypost.com/2026/07/20/business/judge-p...
19,43,2026-07-21-13-52-49 +0000,nypost,Newly unearthed video may be final footage of ...,https://nypost.com/2026/07/21/us-news/newly-un...
198,39,2026-07-21-01-31-29 +0000,wapo,Nearly 100 U.S. troops injured in last two wee...,https://www.washingtonpost.com/world/2026/07/2...
66,38,2026-07-21-12-17-55 +0000,nypost,Israel believes Iran moved nuclear material in...,https://nypost.com/2026/07/21/world-news/israe...
26,38,2026-07-21-13-43-33 +0000,nypost,FBI allowed EcoHealth Alliance boss through bo...,https://nypost.com/2026/07/21/us-news/fbi-allo...
365,37,2026-07-20-17-16-29 +0000,chitri,Ex-Mexican drug lord Ismael ‘El Mayo’ Zambada ...,https://www.chicagotribune.com/2026/07/20/mexi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)