## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-15-03-34 +0000,bbc,Demand for school uniform bank 'has never been...,https://www.bbc.co.uk/news/articles/c330k0gdkk...
1,2026-08-18-14-53-00 +0000,wsj,"Klarna Shares Tumble on Lower Outlook, CFO Search",https://www.wsj.com/business/earnings/klarna-s...
2,2026-08-18-14-52-52 +0000,cbc,"U.S., Iran each dig in on Strait of Hormuz pos...",https://www.cbc.ca/news/world/iran-memorandum-...
3,2026-08-18-14-51-04 +0000,nyt,A Mother’s Quest to Rescue Her Son From Russia...,https://www.nytimes.com/2026/08/18/world/europ...
4,2026-08-18-14-49-59 +0000,nyt,Judge Releases Woman Accused of Vandalizing Wo...,https://www.nytimes.com/2026/08/18/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
140  trump     47
13    iran     19
97     new     15
66      up     13
327  house     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
17,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...,110
303,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...,97
245,2026-08-17-21-20-35 +0000,wapo,"60 days after signing Iran deal, Trump stuck i...",https://www.washingtonpost.com/politics/2026/0...,96
301,2026-08-17-18-39-39 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,95
290,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
17,110,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...
302,58,2026-08-17-18-32-30 +0000,nypost,House Ethics panel probing Dem Rep. Jimmy Gome...,https://nypost.com/2026/08/17/us-news/house-et...
327,55,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
303,50,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...
234,43,2026-08-17-21-44-32 +0000,nypost,Jared Kushner: Hamas said ‘all the right thing...,https://nypost.com/2026/08/17/world-news/jared...
86,42,2026-08-18-11-02-53 +0000,cbc,Russian missile attack in Kharkiv kills at lea...,https://www.cbc.ca/news/world/ukraine-war-1638...
162,41,2026-08-18-06-25-56 +0000,nypost,Drunk Ohio couple arrested after allegedly att...,https://nypost.com/2026/08/18/us-news/cruise-p...
177,39,2026-08-18-03-32-56 +0000,bbc,What to know about Tupac's murder trial and th...,https://www.bbc.co.uk/news/articles/cgmkl1j3dw...
277,38,2026-08-17-20-03-42 +0000,chitri,Trump administration briefly pauses contentiou...,https://www.chicagotribune.com/2026/08/17/big-...
297,37,2026-08-17-18-53-12 +0000,nypost,DSA Florida House candidate appears to cut int...,https://nypost.com/2026/08/17/us-news/dsa-flor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)