## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-02-47-00 +0000,wsj,Long Island Rail Road Strike: What to Know,https://www.wsj.com/us-news/long-island-rail-r...
1,2026-05-19-02-42-16 +0000,startribune,Two wildfires are burning in northern Minnesot...,https://www.startribune.com/mn-wildfires-fland...
2,2026-05-19-02-41-57 +0000,bbc,Trump told Taiwan not to 'go independent' - bu...,https://www.bbc.com/news/articles/clyp9mk3mrgo...
3,2026-05-19-02-41-35 +0000,nyt,"Mamdani, the ‘Tax-the-Rich’ Mayor, Reaches Out...",https://www.nytimes.com/2026/05/18/nyregion/ma...
4,2026-05-19-02-40-57 +0000,bbc,Israeli forces board Gaza-bound flotilla near ...,https://www.bbc.com/news/articles/c142vz80553o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     41
72    iran     20
111    new     20
123     he     14
453  ebola     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,119
21,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,106
162,2026-05-18-19-35-00 +0000,cbc,Trump says he called off Tuesday Iran strike a...,https://www.cbc.ca/news/world/trump-iran-strik...,105
150,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...,96
249,2026-05-18-14-32-21 +0000,nypost,Iran offers new 14-point peace proposal after ...,https://nypost.com/2026/05/18/us-news/iran-sub...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,119,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
182,61,2026-05-18-18-34-46 +0000,cbc,American tests positive for Ebola virus amid o...,https://www.cbc.ca/news/health/american-tests-...
92,57,2026-05-18-22-15-48 +0000,nypost,San Diego mosque where mass shooting left 3 de...,https://nypost.com/2026/05/18/us-news/san-dieg...
21,51,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
190,48,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
34,39,2026-05-19-01-11-58 +0000,nyt,Justice Dept. Sets Up $1.8 Billion Fund That C...,https://www.nytimes.com/2026/05/18/us/politics...
164,37,2026-05-18-19-32-10 +0000,nypost,Kentucky battle for Rep. Thomas Massie’s seat ...,https://nypost.com/2026/05/18/us-news/kentucky...
259,35,2026-05-18-13-52-32 +0000,nypost,Military diver who died trying to recover Ital...,https://nypost.com/2026/05/18/world-news/milit...
216,34,2026-05-18-16-40-26 +0000,nypost,Carl’s Jr. crushed by California’s high minimu...,https://nypost.com/2026/05/18/business/carls-j...
43,34,2026-05-19-00-48-01 +0000,nypost,6-year-old twins critically injured in NYC apa...,https://nypost.com/2026/05/18/us-news/6-year-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)