## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-29-08-11-12 +0000,nyt,Russian Drone Hits Romanian Apartment Building...,https://www.nytimes.com/2026/05/29/world/europ...
1,2026-05-29-08-07-30 +0000,nypost,Bruce Springsteen halts gig to blast Newark’s ...,https://nypost.com/2026/05/29/us-news/bruce-sp...
2,2026-05-29-08-05-13 +0000,nyt,Young MC and Morris Day Pull Out of Freedom 25...,https://www.nytimes.com/2026/05/28/arts/music/...
3,2026-05-29-08-04-00 +0000,wsj,"Gold Rises as U.S., Iran Near Deal, Easing Inf...",https://www.wsj.com/finance/commodities-future...
4,2026-05-29-08-00-00 +0000,cbc,Got a World Cup ticket? Canadian officials war...,https://www.cbc.ca/news/canada/world-cup-fifa-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
31       iran     28
350     trump     28
156       bee     21
118       new     20
155  spelling     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...,142
76,2026-05-29-01-10-16 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,141
67,2026-05-29-01-47-48 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,141
71,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,141
96,2026-05-29-00-11-26 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,141

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,142,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...
173,102,2026-05-28-21-04-00 +0000,wsj,The Trump administration has been holding talk...,https://www.wsj.com/politics/policy/putting-tr...
200,91,2026-05-28-20-07-00 +0000,wsj,"Reports of an Iran deal boost markets, new-car...",https://www.wsj.com/business/autos/iran-deal-r...
85,57,2026-05-29-00-42-00 +0000,wsj,Shares in Dell soared nearly 40% in after-hour...,https://www.wsj.com/tech/dell-stock-soars-on-d...
82,56,2026-05-29-01-00-00 +0000,wsj,Labor’s share of economic output just hit an a...,https://www.wsj.com/finance/stocks/the-record-...
281,55,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
126,44,2026-05-28-22-43-16 +0000,nypost,Humiliation for California governor candidate ...,https://nypost.com/2026/05/28/us-news/los-ange...
335,43,2026-05-28-11-44-55 +0000,nypost,Iran fires ballistic missile at American base ...,https://nypost.com/2026/05/28/world-news/iran-...
324,39,2026-05-28-12-39-13 +0000,cbc,"Israel strikes Beirut suburb, at least 14 kill...",https://www.cbc.ca/news/world/lebanon-tyre-att...
347,38,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)