## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-20-17-04-12 +0000,nypost,NY trooper miraculously walks away after out-o...,https://nypost.com/2026/03/20/us-news/ny-troop...
1,2026-03-20-17-03-48 +0000,bbc,Border security chief to step down after 18 mo...,https://www.bbc.com/news/articles/cx2dn1x9l3jo...
2,2026-03-20-17-03-18 +0000,nyt,Iran War Live Updates: U.S. Steps Up Attacks i...,https://www.nytimes.com/live/2026/03/20/world/...
3,2026-03-20-17-03-16 +0000,nyt,NATO Withdraws Its Last Military Trainers From...,https://www.nytimes.com/2026/03/20/world/middl...
4,2026-03-20-17-00-00 +0000,wsj,"Week Ahead for FX, Bonds: PMI Data to Show Mid...",https://www.wsj.com/economy/week-ahead-for-fx-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
18     iran     49
76    trump     43
19      war     31
238     oil     19
26   energy     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
268,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...,183
343,2026-03-19-20-48-00 +0000,wsj,Trump’s Iran War Frays Ties With Allies as Oil...,https://www.wsj.com/world/trumps-iran-war-fray...,168
293,2026-03-19-23-19-00 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...,156
2,2026-03-20-17-03-18 +0000,nyt,Iran War Live Updates: U.S. Steps Up Attacks i...,https://www.nytimes.com/live/2026/03/20/world/...,136
348,2026-03-19-20-36-58 +0000,nypost,Netanyahu denies misleading Trump into Iran wa...,https://nypost.com/2026/03/19/us-news/netanyah...,136

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
268,183,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...
262,66,2026-03-20-01-00-00 +0000,wsj,A New York congressional race has a new X fact...,https://www.wsj.com/politics/policy/ai-lobbyin...
25,56,2026-03-20-16-30-54 +0000,nyt,"Educators, How Will You Teach Cesar Chavez’s S...",https://www.nytimes.com/2026/03/20/us/cesar-ch...
2,56,2026-03-20-17-03-18 +0000,nyt,Iran War Live Updates: U.S. Steps Up Attacks i...,https://www.nytimes.com/live/2026/03/20/world/...
292,46,2026-03-19-23-23-00 +0000,wsj,A federal panel approved a commemorative gold ...,https://www.wsj.com/politics/policy/trump-gold...
161,46,2026-03-20-10-55-24 +0000,nypost,University of Alabama student James Gracey see...,https://nypost.com/2026/03/20/world-news/unive...
323,46,2026-03-19-21-33-00 +0000,wsj,"A capital rules win for banks, the $100 millio...",https://www.wsj.com/politics/policy/big-banks-...
240,45,2026-03-20-03-22-17 +0000,nypost,Japanese prime minister wishes ‘good looking’ ...,https://nypost.com/2026/03/19/us-news/japanese...
27,41,2026-03-20-16-30-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
185,38,2026-03-20-09-55-19 +0000,bbc,Trump makes Pearl Harbor remark in meeting wit...,https://www.bbc.com/news/articles/c8dlpr074q3o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)