## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-13-19-15-02 +0000,bbc,Molly Russell's dad says PM rushing social med...,https://www.bbc.com/news/articles/cwykw759v3po...
1,2026-06-13-19-11-47 +0000,nyt,Scientists Race to Test Treatments as Ebola Ou...,https://www.nytimes.com/2026/06/12/health/ebol...
2,2026-06-13-18-56-13 +0000,nypost,Top California college quietly shuffles high-p...,https://nypost.com/2026/06/13/us-news/embattle...
3,2026-06-13-18-54-46 +0000,nyt,James Talarico Plays Up Spurs’ Past Glory in C...,https://www.nytimes.com/2026/06/13/us/politics...
4,2026-06-13-18-52-12 +0000,nypost,So long Khamenei! Funeral for slain Iranian su...,https://nypost.com/2026/06/13/world-news/funer...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
72  trump     30
56  world     23
67   iran     23
57    cup     18
68   deal     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
14,2026-06-13-17-48-10 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...,125
22,2026-06-13-17-07-58 +0000,nypost,Trump says Iran peace deal will be signed Sund...,https://nypost.com/2026/06/13/us-news/trump-sa...,101
131,2026-06-13-02-15-27 +0000,nypost,Trump expected to attend World Cup final in Ne...,https://nypost.com/2026/06/12/us-news/trump-ex...,90
172,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...,89
218,2026-06-12-20-14-32 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
14,125,2026-06-13-17-48-10 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal W...,https://www.nytimes.com/live/2026/06/13/world/...
172,89,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...
125,46,2026-06-13-03-38-00 +0000,nypost,Tren de Aragua leader killed in dramatic US ai...,https://nypost.com/2026/06/12/us-news/tren-de-...
238,40,2026-06-12-19-29-44 +0000,nypost,Head of Palestinian soccer group says he wasn’...,https://nypost.com/2026/06/12/sports/head-of-p...
46,37,2026-06-13-15-47-00 +0000,wsj,The Kennedy Center for the Performing Arts boa...,https://www.wsj.com/politics/policy/kennedy-ce...
136,31,2026-06-13-01-58-31 +0000,nypost,Humiliated Putin forced to cancel Russia Day i...,https://nypost.com/2026/06/12/world-news/humil...
166,30,2026-06-12-22-29-55 +0000,nypost,DOJ signs off on $111B Paramount takeover of W...,https://nypost.com/2026/06/12/business/justice...
155,30,2026-06-12-23-56-52 +0000,latimes,A fugitive was wanted for 2 killings in Califo...,https://www.latimes.com/california/story/2026-...
175,27,2026-06-12-21-54-58 +0000,nypost,Ukrainian woman allegedly held as sex slave by...,https://nypost.com/2026/06/12/world-news/ukrai...
7,26,2026-06-13-18-33-42 +0000,nypost,"House Dems claim race, jury selection may have...",https://nypost.com/2026/06/13/us-news/house-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)