## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-16-03-45-29 +0000,bbc,'Unprecedented' fire at Australian oil refiner...,https://www.bbc.com/news/articles/cj40pdw79z9o...
1,2026-04-16-03-45-19 +0000,startribune,The latest: Senate plans Thursday vote on reop...,https://www.startribune.com/live-us-senate-to-...
2,2026-04-16-03-40-00 +0000,wsj,Fire Damages Part of Viva Energy’s Geelong Ref...,https://www.wsj.com/business/energy-oil/fire-d...
3,2026-04-16-03-39-41 +0000,nypost,Iconic monument to old Hollywood could get sec...,https://nypost.com/2026/04/15/us-news/a-west-h...
4,2026-04-16-03-33-42 +0000,nypost,13-year-old suspect identified in violent shoo...,https://nypost.com/2026/04/15/us-news/13-year-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
42    iran     46
111  trump     42
45     war     33
28     new     16
30    year     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-04-16-03-30-08 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...,157
111,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...,152
322,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,147
285,2026-04-15-15-27-22 +0000,bbc,Starmer says he's 'not going to yield' to pres...,https://www.bbc.com/news/articles/cdxdd7ddzgdo...,142
164,2026-04-15-20-07-09 +0000,nyt,Senate Republicans Again Block Bid to Limit Tr...,https://www.nytimes.com/2026/04/15/us/politics...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,157,2026-04-16-03-30-08 +0000,nyt,Iran War Live Updates: Pakistani Mediators Arr...,https://www.nytimes.com/live/2026/04/15/world/...
322,147,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
64,61,2026-04-16-00-00-00 +0000,wsj,Gov. Kathy Hochul has thrown New York City May...,https://www.wsj.com/politics/policy/new-york-g...
36,55,2026-04-16-01-39-00 +0000,wsj,Rep. Eric Swalwell of California earned endors...,https://www.wsj.com/politics/elections/swalwel...
193,51,2026-04-15-19-21-54 +0000,cbc,"Jury finds Live Nation, Ticketmaster had anti-...",https://www.cbc.ca/news/entertainment/live-nat...
369,48,2026-04-15-10-00-00 +0000,latimes,L.A.'s Blue Era: How popular are the Dodgers? ...,https://www.latimes.com/sports/dodgers/story/2...
8,45,2026-04-16-03-15-00 +0000,wsj,China reported accelerating economic growth to...,https://www.wsj.com/economy/chinas-growth-acce...
34,45,2026-04-16-01-53-01 +0000,latimes,An immigration agent shot out his eye at a 'No...,https://www.latimes.com/california/story/2026-...
189,44,2026-04-15-19-28-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
42,44,2026-04-16-01-19-48 +0000,nypost,NYC first lady Rama Duwaji apologizes for past...,https://nypost.com/2026/04/15/us-news/nyc-firs...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)