## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-15-09-01-20 +0000,nyt,"In Texas, an Unyielding Gun Culture Jumps Off ...",https://www.nytimes.com/2026/03/15/us/politics...
1,2026-03-15-09-00-40 +0000,nyt,"In a Wild Corner of the West, Elk Are Everywhe...",https://www.nytimes.com/2026/03/15/us/elk-paci...
2,2026-03-15-09-00-34 +0000,wapo,"To criticize an American-led war, an American ...",https://www.washingtonpost.com/world/2026/03/1...
3,2026-03-15-09-00-18 +0000,nyt,Trump Administration Turns to Migrant Workers ...,https://www.nytimes.com/2026/03/15/us/politics...
4,2026-03-15-09-00-15 +0000,wapo,Iran wages economic war in hopes of outlasting...,https://www.washingtonpost.com/business/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2625/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
30     iran     32
18      war     24
22    trump     23
606     oil     13
55   killed     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-03-15-01-37-44 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...,95
126,2026-03-14-17-18-24 +0000,nypost,Lindsey Graham praises Trump’s ‘bold’ takeover...,https://nypost.com/2026/03/14/us-news/lindsey-...,94
63,2026-03-15-00-29-36 +0000,nypost,Trump says Iran wants to end the war – but ter...,https://nypost.com/2026/03/14/world-news/trump...,90
87,2026-03-14-22-04-27 +0000,wapo,FCC chief threatens broadcasters as Trump crit...,https://www.washingtonpost.com/business/2026/0...,90
114,2026-03-14-19-00-00 +0000,wsj,Five Takeaways From WSJ’s Reporting on Trump’s...,https://www.wsj.com/world/middle-east/five-tak...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,95,2026-03-15-01-37-44 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...
187,48,2026-03-14-09-30-00 +0000,wsj,A slew of data released Friday portrayed an ec...,https://www.wsj.com/economy/oil-shock-hits-an-...
120,40,2026-03-14-18-15-53 +0000,nypost,Any country except for US and Israel can pass ...,https://nypost.com/2026/03/14/world-news/any-c...
152,37,2026-03-14-14-00-00 +0000,missionlocal,"New year, new cup and a taller ask for El Faro...",https://missionlocal.org/2026/03/new-year-new-...
164,35,2026-03-14-12-00-00 +0000,latimes,Lopez: My promise to you: AI didn't write this...,https://www.latimes.com/california/story/2026-...
169,31,2026-03-14-11-00-00 +0000,wsj,A court ruling throwing out a pair of criminal...,https://www.wsj.com/economy/central-banking/th...
29,29,2026-03-15-03-20-27 +0000,nypost,California gov. candidate Matt Mahan urges end...,https://nypost.com/2026/03/14/us-news/californ...
39,28,2026-03-15-02-16-03 +0000,nypost,Ex-Memorial Sloan Kettering Cancer Center empl...,https://nypost.com/2026/03/14/us-news/ex-memor...
117,28,2026-03-14-18-47-24 +0000,nypost,Iran threatens to strike Ukraine after Zelensk...,https://nypost.com/2026/03/14/world-news/iran-...
79,26,2026-03-14-22-35-20 +0000,startribune,"Gophers earn top-16 seed, will play host to fi...",https://www.startribune.com/gophers-earn-top-1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)