## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-22-20-54-00 +0000,wsj,Trump Called Musk and Asked Him to Lift Ukrain...,https://www.wsj.com/world/trump-called-musk-an...
1,2026-10-22-20-52-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
2,2026-10-22-20-50-20 +0000,nyt,Florida Police Officer Is Accused in Scheme to...,https://www.nytimes.com/2026/10/22/us/florida-...
3,2026-10-22-20-49-30 +0000,nypost,NYC mom hit with murder charges in death of au...,https://nypost.com/2026/10/22/us-news/nyc-mom-...
4,2026-10-22-20-49-12 +0000,bbc,New York City ends a classic: Horse-drawn carr...,https://www.bbc.co.uk/news/articles/c6qjnwd1pg...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     27
34          new     20
80   california     18
73           ai     15
117          up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
39,2026-10-22-20-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,102
236,2026-10-22-11-53-48 +0000,chitri,Deportations climb under President Donald Trum...,https://www.chicagotribune.com/2026/10/22/depo...,94
245,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...,89
273,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...,83
253,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
39,102,2026-10-22-20-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
273,83,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...
388,79,2026-10-21-22-12-19 +0000,nypost,Meta stock surges on strong earnings report; t...,https://nypost.com/2026/10/21/business/meta-st...
343,77,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...
346,56,2026-10-22-01-18-45 +0000,nypost,Ilhan Omar gives head-scratching response when...,https://nypost.com/2026/10/21/us-news/ilhan-om...
253,55,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...
65,50,2026-10-22-19-29-00 +0000,wsj,"Oil Futures Rise as Attacks on Saudi Arabia, U...",https://www.wsj.com/business/energy-oil/oil-pr...
360,46,2026-10-22-00-05-00 +0000,wsj,Musk Says Tesla Aims to Begin Humanoid Robot S...,https://www.wsj.com/business/autos/tesla-tsla-...
94,45,2026-10-22-18-32-00 +0000,wsj,The Justice Department is examining allegation...,https://www.wsj.com/politics/policy/justice-de...
80,39,2026-10-22-19-04-41 +0000,nypost,Half-naked woman dumped outside NYC hospital w...,https://nypost.com/2026/10/22/us-news/fake-cos...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)