## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-22-17-28-09 +0000,nypost,Pint-sized Florida gangbanger gets hard time f...,https://nypost.com/2026/05/22/us-news/julio-fo...
1,2026-05-22-17-26-05 +0000,nyt,Regional Mediators Rush to Save U.S.-Iran Ceas...,https://www.nytimes.com/2026/05/22/world/middl...
2,2026-05-22-17-26-00 +0000,wsj,Tulsi Gabbard Is Preparing to Resign as U.S. I...,https://www.wsj.com/world/middle-east/tulsi-ga...
3,2026-05-22-17-25-35 +0000,bbc,UK sees hottest day of year as bank holiday tr...,https://www.bbc.com/news/articles/cpqpygjwywjo...
4,2026-05-22-17-20-55 +0000,nyt,Stocks and Oil Prices Tick Up Amid Impasse Ove...,https://www.nytimes.com/2026/05/22/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
277  trump     36
117    new     23
17    iran     18
219  ebola     13
310    war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
148,2026-05-22-11-00-00 +0000,nypost,How Kevin Warsh will navigate his tricky new p...,https://nypost.com/2026/05/22/business/how-kev...,91
170,2026-05-22-10-00-01 +0000,wapo,Trump offered White South Africans a new life....,https://www.washingtonpost.com/nation/2026/05/...,90
297,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...,86
234,2026-05-22-01-37-02 +0000,bbc,'No means no': Greenlanders protest against Tr...,https://www.bbc.com/news/articles/cwy2gxvnq1zo...,84
262,2026-05-21-23-22-38 +0000,nyt,GOP Pulls Measure on Trump’s War Powers in Ira...,https://www.nytimes.com/2026/05/21/us/iran-war...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
148,91,2026-05-22-11-00-00 +0000,nypost,How Kevin Warsh will navigate his tricky new p...,https://nypost.com/2026/05/22/business/how-kev...
73,62,2026-05-22-15-08-54 +0000,nypost,Dow soars 400 points to an all-time high — fir...,https://nypost.com/2026/05/22/business/dow-soa...
154,58,2026-05-22-10-52-48 +0000,nypost,Feds dramatically drop charges against Illinoi...,https://nypost.com/2026/05/22/us-news/feds-dro...
297,50,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...
350,46,2026-05-21-18-46-46 +0000,nypost,Don Lemon trashes ex-boss ahead of Colbert’s l...,https://nypost.com/2026/05/21/media/don-lemon-...
35,45,2026-05-22-16-37-12 +0000,latimes,A frantic two hours as police struggled to ass...,https://www.latimes.com/california/story/2026-...
16,43,2026-05-22-16-57-00 +0000,wsj,Kevin Warsh is to be sworn in as Fed chair on ...,https://www.wsj.com/economy/central-banking/tr...
11,38,2026-05-22-17-13-00 +0000,wsj,China and Russia have in recent years expanded...,https://www.wsj.com/politics/national-security...
310,37,2026-05-21-21-03-26 +0000,latimes,Scientists bet on AI to save gray whales from ...,https://www.latimes.com/california/story/2026-...
343,36,2026-05-21-19-00-43 +0000,nypost,Meta settles bellwether social media addiction...,https://nypost.com/2026/05/21/business/meta-se...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)