## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-06-04-07-15 +0000,nypost,Indiana firefighter duo return lost American f...,https://nypost.com/2026/05/06/us-news/indiana-...
1,2026-05-06-04-04-52 +0000,nyt,Trump Says U.S. Pausing Efforts to Guide Ships...,https://www.nytimes.com/2026/05/05/world/middl...
2,2026-05-06-04-02-33 +0000,startribune,Marie-Philip Poulin scores in third overtime t...,https://www.startribune.com/marie-philip-pouli...
3,2026-05-06-04-01-05 +0000,nyt,Guy Goma’s Accidental BBC Interview Lives On A...,https://www.nytimes.com/2026/05/06/business/me...
4,2026-05-06-04-00-06 +0000,nyt,Japan’s Takaichi Pitches Strength and Stabilit...,https://www.nytimes.com/2026/05/06/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2605/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
12        trump     44
50          new     24
20         iran     24
18       strait     15
745  hantavirus     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-05-05-22-35-56 +0000,nypost,Trump pauses Project Freedom rescue operation ...,https://nypost.com/2026/05/05/world-news/proje...,143
81,2026-05-05-23-10-33 +0000,nypost,Trump pauses ‘Project Freedom’ initiative in S...,https://nypost.com/2026/05/05/us-news/trump-pa...,122
124,2026-05-05-21-40-07 +0000,cbc,Trump pauses U.S. effort to guide vessels thro...,https://www.cbc.ca/news/world/rubio-hegseth-ir...,122
266,2026-05-05-15-04-00 +0000,wsj,President Trump escalated his public feud with...,https://www.wsj.com/politics/national-security...,120
63,2026-05-06-00-12-00 +0000,wsj,Trump Administration Sues New York Times Over ...,https://www.wsj.com/us-news/law/trump-administ...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,143,2026-05-05-22-35-56 +0000,nypost,Trump pauses Project Freedom rescue operation ...,https://nypost.com/2026/05/05/world-news/proje...
178,85,2026-05-05-20-05-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
340,64,2026-05-05-09-30-00 +0000,nypost,The two possible causes for the cruise ship ha...,https://nypost.com/2026/05/05/world-news/the-d...
127,56,2026-05-05-21-32-17 +0000,cbc,Prosecutors add assault charge to case against...,https://www.cbc.ca/news/world/assault-charge-w...
139,53,2026-05-05-21-13-00 +0000,wsj,"After pressure from Trump, the FDA OKs some fl...",https://www.wsj.com/politics/policy/after-trum...
66,51,2026-05-05-23-59-55 +0000,nypost,Vivek Ramaswamy wins GOP primary for Ohio gove...,https://nypost.com/2026/05/05/us-news/vivek-ra...
90,48,2026-05-05-22-48-22 +0000,nypost,Oil production won’t return to normal until af...,https://nypost.com/2026/05/05/world-news/oil-p...
334,45,2026-05-05-10-00-00 +0000,nypost,$350M Mexican art collection secretly sold by ...,https://nypost.com/2026/05/05/world-news/mexic...
171,44,2026-05-05-20-18-02 +0000,nypost,Gavin Newsom loses it on CNN analyst who calle...,https://nypost.com/2026/05/05/us-news/gavin-ne...
363,43,2026-05-05-04-58-11 +0000,nyt,Drone Hits a Moscow High-Rise Days Before a Ma...,https://www.nytimes.com/2026/05/04/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)