## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-15-14-59-05 +0000,nyt,Some Olympic Leaders Want to See Fixed Winter ...,https://www.nytimes.com/2026/03/15/world/europ...
1,2026-03-15-14-54-56 +0000,nyt,The Tax Bill Haunting Your 401(k) and I.R.A.,https://www.nytimes.com/2026/03/15/business/ro...
2,2026-03-15-14-52-24 +0000,nyt,Iran War Live Updates: Israel Launches New Str...,https://www.nytimes.com/live/2026/03/15/world/...
3,2026-03-15-14-50-44 +0000,nyt,This is what happened on March 14.,https://www.nytimes.com/live/2026/world/us-isr...
4,2026-03-15-14-49-38 +0000,startribune,Live: No travel advisory for portions of state...,https://www.startribune.com/live-winter-storm-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2627/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
13     iran     36
14      war     29
128   trump     23
17   israel     10
19      new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-15-14-52-24 +0000,nyt,Iran War Live Updates: Israel Launches New Str...,https://www.nytimes.com/live/2026/03/15/world/...,127
100,2026-03-15-01-37-44 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...,103
133,2026-03-14-22-04-27 +0000,wapo,FCC chief threatens broadcasters as Trump crit...,https://www.washingtonpost.com/business/2026/0...,101
13,2026-03-15-14-19-14 +0000,nypost,Oil prices will drop after Iran war ends ‘in t...,https://nypost.com/2026/03/15/us-news/oil-pric...,100
115,2026-03-15-00-29-36 +0000,nypost,Trump says Iran wants to end the war – but ter...,https://nypost.com/2026/03/14/world-news/trump...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,127,2026-03-15-14-52-24 +0000,nyt,Iran War Live Updates: Israel Launches New Str...,https://www.nytimes.com/live/2026/03/15/world/...
137,59,2026-03-14-21-31-10 +0000,nypost,Trump urges ‘team effort’ from allies to keep ...,https://nypost.com/2026/03/14/us-news/trump-ur...
12,32,2026-03-15-14-19-48 +0000,nyt,Pentagon Names 6 Military Members Killed in Ir...,https://www.nytimes.com/2026/03/14/us/names-of...
162,29,2026-03-14-18-47-24 +0000,nypost,Iran threatens to strike Ukraine after Zelensk...,https://nypost.com/2026/03/14/world-news/iran-...
119,27,2026-03-15-00-00-00 +0000,wsj,The AI boom has sparked a frenzied real-estate...,https://www.wsj.com/economy/housing/san-franci...
13,26,2026-03-15-14-19-14 +0000,nypost,Oil prices will drop after Iran war ends ‘in t...,https://nypost.com/2026/03/15/us-news/oil-pric...
14,25,2026-03-15-14-12-56 +0000,nypost,Maine Dem Senate hopeful Graham Platner done a...,https://nypost.com/2026/03/15/us-news/maine-de...
95,24,2026-03-15-02-16-03 +0000,nypost,Ex-Memorial Sloan Kettering Cancer Center empl...,https://nypost.com/2026/03/14/us-news/ex-memor...
40,23,2026-03-15-10-38-22 +0000,bbc,Israeli forces kill Palestinian couple and two...,https://www.bbc.com/news/articles/cqxdndz75zvo...
81,23,2026-03-15-05-26-37 +0000,nypost,Rep. Jasmine Crockett’s fugitive security guar...,https://nypost.com/2026/03/15/us-news/rep-jasm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)