## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-13-16-02-52 +0000,bbc,"Healey wanted UK to join global defence bank, ...",https://www.bbc.com/news/articles/ce8jyd85ejeo...
1,2026-06-13-16-00-00 +0000,wsj,Trump turns the White House lawn into a UFC ar...,https://www.wsj.com/politics/trump-ufc-politic...
2,2026-06-13-16-00-00 +0000,wsj,U.S. Poised to Lose Measles Elimination Status...,https://www.wsj.com/us-news/us-measles-elimina...
3,2026-06-13-16-00-00 +0000,wsj,SpaceX’s Engineering Secret? A College Car-Rac...,https://www.wsj.com/tech/spacex-engineering-co...
4,2026-06-13-15-58-35 +0000,nypost,Cops disguised themselves as World Cup mascots...,https://nypost.com/2026/06/13/world-news/cops-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
9    trump     29
43   world     25
33  spacex     23
67    iran     20
44     cup     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
159,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...,104
193,2026-06-12-20-38-48 +0000,nyt,Elon Musk Becomes World’s First Trillionaire a...,https://www.nytimes.com/2026/06/12/technology/...,96
116,2026-06-13-02-15-27 +0000,nypost,Trump expected to attend World Cup final in Ne...,https://nypost.com/2026/06/12/us-news/trump-ex...,91
205,2026-06-12-20-14-32 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...,86
13,2026-06-13-15-30-30 +0000,nypost,Trump set to meet with Middle East leaders nex...,https://nypost.com/2026/06/13/us-news/trump-se...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
159,104,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...
205,86,2026-06-12-20-14-32 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...
236,45,2026-06-12-18-33-52 +0000,nypost,Spencer Pratt drops bombshell clip with claims...,https://nypost.com/2026/06/12/us-news/spencer-...
110,45,2026-06-13-03-38-00 +0000,nypost,Tren de Aragua leader killed in dramatic US ai...,https://nypost.com/2026/06/12/us-news/tren-de-...
141,42,2026-06-12-23-56-52 +0000,latimes,A fugitive was wanted for 2 killings in Califo...,https://www.latimes.com/california/story/2026-...
37,39,2026-06-13-13-39-41 +0000,nypost,World Cup tourist gets hooked on American cond...,https://nypost.com/2026/06/13/us-news/crack-wo...
15,37,2026-06-13-15-25-08 +0000,nypost,Trump’s name comes off Kennedy Center building...,https://nypost.com/2026/06/13/us-news/trumps-n...
181,35,2026-06-12-21-00-00 +0000,wsj,One Ukrainian City’s Agonizing Year as the Rus...,https://www.wsj.com/world/druzhkivka-ukraine-r...
136,28,2026-06-13-00-06-14 +0000,nyt,Justice Dept. Clears Way for Paramount-Warner ...,https://www.nytimes.com/2026/06/12/business/me...
29,27,2026-06-13-14-32-48 +0000,nypost,Knicks’ art pops up all over NYC as fans paint...,https://nypost.com/2026/06/13/us-news/nyc-pain...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)