## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-24-14-26-01 +0000,nyt,"Phones in Hand, India’s Young Protesters Blast...",https://www.nytimes.com/2026/07/24/world/asia/...
1,2026-07-24-14-25-41 +0000,nypost,AI billionaire who left wife for younger lover...,https://nypost.com/2026/07/24/business/ai-bill...
2,2026-07-24-14-25-32 +0000,nypost,Grandma killed on way to identify her son’s bo...,https://nypost.com/2026/07/24/world-news/grand...
3,2026-07-24-14-24-00 +0000,wsj,Global Economy Picked Up Before Fresh Energy Hit,https://www.wsj.com/economy/global/global-econ...
4,2026-07-24-14-22-25 +0000,nypost,More than 25 million Americans under threat as...,https://nypost.com/2026/07/24/us-news/more-tha...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2508/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     48
130    new     38
93    iran     32
66     war     19
58     out     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-07-24-01-00-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,143
165,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,132
241,2026-07-23-22-08-32 +0000,chitri,"Next stop, Trump Station? Administration wants...",https://www.chicagotribune.com/2026/07/23/trum...,124
355,2026-07-23-16-51-00 +0000,wsj,A Democratic-backed measure to rein in Preside...,https://www.wsj.com/politics/gop-lawmakers-bac...,122
327,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,143,2026-07-24-01-00-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...
165,84,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
205,63,2026-07-24-01-00-00 +0000,wsj,Inside China’s All-Out Push to Catch Up With A...,https://www.wsj.com/world/china/china-ai-chips...
371,59,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
372,53,2026-07-23-15-57-43 +0000,nyt,Oil-Rich Saudi Arabia Isn’t Short on Energy. H...,https://www.nytimes.com/2026/07/23/world/middl...
171,46,2026-07-24-07-20-12 +0000,nypost,NY cops not ruling out another suspect may hav...,https://nypost.com/2026/07/24/us-news/ny-cops-...
323,45,2026-07-23-18-56-23 +0000,nypost,South Korean AI billionaire faces $1 billion d...,https://nypost.com/2026/07/23/business/south-k...
191,42,2026-07-24-02-00-00 +0000,wsj,Capital Account: When the Supreme Court struck...,https://www.wsj.com/politics/policy/trumps-tra...
255,38,2026-07-23-21-43-38 +0000,bbc,Justice dept withdraws subpoenas over New York...,https://www.bbc.co.uk/news/articles/cwyrjl04vn...
355,37,2026-07-23-16-51-00 +0000,wsj,A Democratic-backed measure to rein in Preside...,https://www.wsj.com/politics/gop-lawmakers-bac...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)