## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-01-18-36 +0000,bbc,Oil prices fluctuate as status of US-Iran peac...,https://www.bbc.com/news/articles/c995dkl4dvvo...
1,2026-04-22-01-15-02 +0000,startribune,Virginia voters approve redistricting plan tha...,https://www.startribune.com/virginia-voters-de...
2,2026-04-22-01-14-11 +0000,nyt,Virginia Passes New House Map in a Midterm Vic...,https://www.nytimes.com/2026/04/21/us/election...
3,2026-04-22-01-14-00 +0000,wsj,Asian Currencies Mostly Strengthen Amid U.S.-I...,https://www.wsj.com/finance/currencies/asian-c...
4,2026-04-22-01-10-49 +0000,bbc,"Virginia approves redistricting, giving Democr...",https://www.bbc.com/news/articles/c895j8zgqe4o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
39  trump     37
4    iran     33
19    new     20
84     up     15
6   talks     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,177
5,2026-04-22-01-09-19 +0000,nyt,Iran War Live Updates: Trump Extends Cease-Fir...,https://www.nytimes.com/live/2026/04/21/world/...,148
25,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,131
293,2026-04-21-13-14-14 +0000,nypost,Trump doesn’t want to extend Iran cease-fire —...,https://nypost.com/2026/04/21/us-news/trump-do...,114
124,2026-04-21-21-04-48 +0000,nyt,Trump Extends Iran Cease-Fire Before Deadline ...,https://www.nytimes.com/2026/04/21/us/politics...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,177,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
373,61,2026-04-21-05-57-56 +0000,bbc,New era as Apple names new boss to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
94,60,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
196,56,2026-04-21-18-15-31 +0000,nypost,Rep. Sheila Cherfilus-McCormick resigns from C...,https://nypost.com/2026/04/21/us-news/rep-shei...
264,50,2026-04-21-14-52-47 +0000,cbc,"2 Palestinians, including 14-year-old, killed ...",https://www.cbc.ca/news/world/palestinians-kil...
10,50,2026-04-22-01-01-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
75,40,2026-04-21-22-47-02 +0000,nypost,UK PM Starmer gets support from Trump as he fa...,https://nypost.com/2026/04/21/us-news/uk-pm-st...
388,38,2026-04-21-02-00-00 +0000,wsj,"Companies are getting hit up for money twice, ...",https://www.wsj.com/politics/policy/the-rival-...
304,37,2026-04-21-12-34-39 +0000,nypost,Chilling video shows moment Mexico pyramid sho...,https://nypost.com/2026/04/21/world-news/mexic...
280,35,2026-04-21-14-12-38 +0000,nypost,K-pop mogul behind BTS wanted by police for al...,https://nypost.com/2026/04/21/world-news/south...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)