## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-15-25-49 +0000,nyt,Prince William Is Still Silent About His Broth...,https://www.nytimes.com/2026/08/27/world/europ...
1,2026-08-27-15-24-14 +0000,nyt,"Ratko Mladic, Murderous ‘Butcher of Bosnia,’ D...",https://www.nytimes.com/2026/08/27/world/europ...
2,2026-08-27-15-23-04 +0000,wapo,We know you care about the environment because...,https://www.washingtonpost.com/politics/2026/0...
3,2026-08-27-15-21-59 +0000,bbc,"Burnham calls summit of Welsh, Scottish and No...",https://www.bbc.co.uk/news/articles/c14d8v83ny...
4,2026-08-27-15-21-56 +0000,nyt,Lindsay Clancy Murder Trial Closing Arguments ...,https://www.nytimes.com/2026/08/27/us/lindsay-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2518/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
33        trump     42
169  california     24
94        nepal     23
411         new     22
44          war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
315,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,131
251,2026-08-26-23-55-41 +0000,wapo,"Canada, pressured by Trump, wants new trade pa...",https://www.washingtonpost.com/world/2026/08/2...,102
350,2026-08-26-19-08-11 +0000,cbc,Trump's trade war: Fact-checking Canada's natu...,https://www.cbc.ca/news/world/trade-war-natura...,95
253,2026-08-26-23-36-56 +0000,latimes,Trump administration's wage cuts for seasonal ...,https://www.latimes.com/california/story/2026-...,95
154,2026-08-27-10-13-00 +0000,nypost,NY doctor’s desperate plea for her parents who...,https://nypost.com/2026/08/27/us-news/ny-docs-...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
315,131,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
154,93,2026-08-27-10-13-00 +0000,nypost,NY doctor’s desperate plea for her parents who...,https://nypost.com/2026/08/27/us-news/ny-docs-...
22,70,2026-08-27-14-51-00 +0000,wsj,California has made it easier to file civil cl...,https://www.wsj.com/politics/policy/california...
39,65,2026-08-27-14-29-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
273,62,2026-08-26-22-49-36 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
176,49,2026-08-27-09-30-00 +0000,wsj,The selloff in U.S. Treasurys has captured glo...,https://www.wsj.com/economy/global/think-treas...
283,49,2026-08-26-22-10-00 +0000,wsj,The surprise visit by the director of the Cent...,https://www.wsj.com/politics/policy/cia-chiefs...
258,49,2026-08-26-23-22-21 +0000,latimes,'A voluptuous sex symbol.' Judge invokes Dolly...,https://www.latimes.com/california/story/2026-...
393,43,2026-08-26-16-29-03 +0000,nypost,Trump doubts Iran’s Supreme Leader Mojtaba Kha...,https://nypost.com/2026/08/26/us-news/trump-do...
254,42,2026-08-26-23-28-05 +0000,nyt,Deadly Nepal Flood May Have Been Caused by ‘Ic...,https://www.nytimes.com/2026/08/26/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)