## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-08-20-56-28 +0000,nypost,Ford CEO gifts custom Explorer to Pope Leo XIV...,https://nypost.com/2026/03/08/business/ford-bu...
1,2026-03-08-20-52-48 +0000,wapo,U.S. military announces death of seventh servi...,https://www.washingtonpost.com/world/2026/03/0...
2,2026-03-08-20-51-09 +0000,nypost,Labubu maker will finally open a US headquarte...,https://nypost.com/2026/03/08/us-news/labubu-m...
3,2026-03-08-20-49-26 +0000,nypost,"Dr. Oz takes aim at Dem Govs. Hochul, Newsom o...",https://nypost.com/2026/03/08/us-news/dr-oz-ta...
4,2026-03-08-20-47-29 +0000,bbc,Swiss reject right-wing plan to cut licence fe...,https://www.bbc.com/news/articles/c0q32322wq8o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
18    iran     45
222  trump     30
17     war     24
263    new     12
473     he     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
172,2026-03-08-01-32-38 +0000,wapo,"Trump says Iran targets will expand, honors U....",https://www.washingtonpost.com/world/2026/03/0...,118
73,2026-03-08-17-06-53 +0000,latimes,7th U.S. service member dies in Iran war; Trum...,https://www.latimes.com/politics/story/2026-03...,116
108,2026-03-08-12-18-51 +0000,cbc,U.S.-Israeli war with Iran widens across Middl...,https://www.cbc.ca/news/world/livestory/iran-i...,113
180,2026-03-08-00-33-40 +0000,nyt,Iran’s De Facto Leader Says Iran Will Not Surr...,https://www.nytimes.com/2026/03/07/world/middl...,112
126,2026-03-08-10-00-00 +0000,latimes,What is Trump's true objective in the Iran war...,https://www.latimes.com/politics/story/2026-03...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
172,118,2026-03-08-01-32-38 +0000,wapo,"Trump says Iran targets will expand, honors U....",https://www.washingtonpost.com/world/2026/03/0...
108,44,2026-03-08-12-18-51 +0000,cbc,U.S.-Israeli war with Iran widens across Middl...,https://www.cbc.ca/news/world/livestory/iran-i...
80,41,2026-03-08-16-39-17 +0000,nypost,"Gas will be below $3 soon, Energy Secretary Wr...",https://nypost.com/2026/03/08/us-news/gas-will...
130,33,2026-03-08-09-30-00 +0000,wsj,The economy has seen an ugly week with the Ira...,https://www.wsj.com/economy/why-the-oil-shock-...
169,32,2026-03-08-01-54-43 +0000,nypost,Loud explosion rocks US embassy in Norway — af...,https://nypost.com/2026/03/07/world-news/loud-...
27,31,2026-03-08-19-34-44 +0000,nypost,Inside major sports business exec’s harrowing ...,https://nypost.com/2026/03/08/business/inside-...
41,27,2026-03-08-18-44-40 +0000,nypost,Popular NYC tattoo biz sues ex-workers for cal...,https://nypost.com/2026/03/08/us-news/popular-...
58,27,2026-03-08-17-55-54 +0000,nypost,Devices hurled at Gracie Mansion protest deter...,https://nypost.com/2026/03/08/us-news/explosiv...
38,26,2026-03-08-18-57-57 +0000,nypost,Heartbreaking details behind school prank that...,https://nypost.com/2026/03/08/us-news/details-...
182,26,2026-03-08-00-15-36 +0000,nypost,"US, South Korea to conduct joint military dril...",https://nypost.com/2026/03/07/world-news/unite...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)