## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-04-04-50-37 +0000,startribune,Justin: ‘SNL’s’ Tommy Brennan puts Minnesota f...,https://www.startribune.com/justin-snls-tommy-...
1,2026-09-04-04-48-20 +0000,nyt,Workers Rescued From Tunnel in Nepal 9 Days Af...,https://www.nytimes.com/2026/09/04/world/asia/...
2,2026-09-04-04-45-00 +0000,wsj,"Former Labor Secretary Oversaw a ‘Toxic, Intim...",https://www.wsj.com/business/former-labor-secr...
3,2026-09-04-04-39-26 +0000,bbc,Argentina to sanction oil firms as tensions he...,https://www.bbc.co.uk/news/articles/clyk18g1l8...
4,2026-09-04-04-31-46 +0000,nypost,Jesus camp booted from Burning Man in wild cul...,https://nypost.com/2026/09/04/us-news/christia...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2421/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
281   trump     48
161  clancy     19
106   court     17
158     new     15
433   house     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
102,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...,142
156,2026-09-03-20-33-39 +0000,chitri,President Trump again appeals to Supreme Court...,https://www.chicagotribune.com/2026/09/03/trum...,113
121,2026-09-03-21-53-00 +0000,wsj,Excavation work on President Trump’s 250-foot-...,https://www.wsj.com/politics/policy/work-on-tr...,113
385,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,112
115,2026-09-03-22-06-54 +0000,chitri,Missouri’s highest court blocks Trump-backed U...,https://www.chicagotribune.com/2026/09/03/miss...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
102,142,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...
160,80,2026-09-03-20-22-43 +0000,wapo,Vance says he doesn’t know when Iran conflict ...,https://www.washingtonpost.com/politics/2026/0...
48,74,2026-09-04-00-55-45 +0000,bbc,Watch: Inside court as Lindsay Clancy's lawyer...,https://www.bbc.co.uk/news/videos/c36l7jwjg1no...
250,69,2026-09-03-17-01-00 +0000,wsj,Billionaire Leon Black won’t appear before the...,https://www.wsj.com/politics/policy/leon-black...
125,68,2026-09-03-21-45-00 +0000,wsj,The odds of an interest-rate hike are now a co...,https://www.wsj.com/politics/policy/fed-rate-w...
121,57,2026-09-03-21-53-00 +0000,wsj,Excavation work on President Trump’s 250-foot-...,https://www.wsj.com/politics/policy/work-on-tr...
93,51,2026-09-03-22-46-58 +0000,nypost,Elon Musk launches steering-wheel-free Tesla C...,https://nypost.com/2026/09/03/business/elon-mu...
235,43,2026-09-03-17-43-33 +0000,latimes,"Fox News cuts ties with Maria Bartiromo, weeks...",https://www.latimes.com/entertainment-arts/bus...
360,42,2026-09-03-11-26-18 +0000,latimes,"Gloria Steinem, charismatic feminist and co-fo...",https://www.latimes.com/world-nation/story/202...
57,42,2026-09-04-00-34-00 +0000,wsj,Missouri’s Supreme Court ruled Thursday the st...,https://www.wsj.com/politics/policy/missouri-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)