## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-06-16-00-00 +0000,wsj,"More Top Horses Are Being Cloned, Rattling the...",https://www.wsj.com/world/horse-cloning-breede...
1,2026-06-06-15-59-11 +0000,nypost,NYC Schools Chancellor Kamar Samuels could fac...,https://nypost.com/2026/06/06/us-news/nyc-scho...
2,2026-06-06-15-49-09 +0000,nypost,Inside the California city where critics fear ...,https://nypost.com/2026/06/06/us-news/inside-t...
3,2026-06-06-15-44-43 +0000,wapo,Iran launched missiles and drones toward Strai...,https://www.washingtonpost.com/world/2026/06/0...
4,2026-06-06-15-44-40 +0000,nypost,"98-year-old beaten with broomstick, chair in N...",https://nypost.com/2026/06/06/us-news/woman-lo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
82        trump     25
32         iran     13
21   california     12
5         world     11
154     platner     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
234,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,81
48,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...,81
168,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...,73
264,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,72
160,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
234,81,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
141,54,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...
168,48,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...
179,46,2026-06-05-21-51-59 +0000,nyt,"Amid Graham Platner Controversy, Where Does th...",https://www.nytimes.com/2026/06/05/us/politics...
189,46,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
160,39,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...
102,35,2026-06-06-08-00-00 +0000,cbc,Frustrations on multiple fronts set to collide...,https://www.cbc.ca/news/world/conflict-fifa-wo...
12,35,2026-06-06-15-01-05 +0000,nyt,Infant Killed as Israeli Military Fires on Car...,https://www.nytimes.com/2026/06/06/world/middl...
144,34,2026-06-06-01-00-00 +0000,wsj,Kevin Warsh faces early Fed pressure as strong...,https://www.wsj.com/economy/central-banking/ke...
48,29,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)