## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-17-23-50 +0000,nypost,Trump vows Iran will never have nukes while mo...,https://nypost.com/2026/05/25/us-news/trump-vo...
1,2026-05-25-17-21-24 +0000,nypost,Raaw Energy issues recall on dozens of product...,https://nypost.com/2026/05/25/business/popular...
2,2026-05-25-17-17-10 +0000,bbc,This beach hut costs the same as a three-bedro...,https://www.bbc.com/news/videos/cg4pp1xdyk2o?a...
3,2026-05-25-17-16-20 +0000,nypost,Spencer Pratt’s latest campaign ad puts LA’s f...,https://nypost.com/2026/05/25/us-news/spencer-...
4,2026-05-25-17-16-19 +0000,nypost,Psycho banker pimped girlfriend out to ‘friend...,https://nypost.com/2026/05/25/world-news/psych...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
2        iran     31
0       trump     21
103      deal     21
146       new      9
53   chemical      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
116,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...,101
20,2026-05-25-16-32-51 +0000,wapo,"As new Iran deal faces sharp criticism, Trump ...",https://www.washingtonpost.com/world/2026/05/2...,93
67,2026-05-25-13-51-50 +0000,nypost,Trump demands six Muslim countries join Abraha...,https://nypost.com/2026/05/25/us-news/presiden...,91
213,2026-05-24-18-04-00 +0000,wsj,Trump Says He Is in No Rush for an Iran Deal T...,https://www.wsj.com/world/middle-east/middle-e...,88
54,2026-05-25-15-05-11 +0000,nyt,Trump’s Pressure Had Little Effect on Iran’s T...,https://www.nytimes.com/2026/05/25/world/middl...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
116,101,2026-05-25-09-55-01 +0000,cbc,Trump demands Arab countries sign Abraham Acco...,https://www.cbc.ca/news/world/iran-u-s-ceasefi...
8,43,2026-05-25-17-11-00 +0000,nypost,Florida student texted family to say she was c...,https://nypost.com/2026/05/25/us-news/florida-...
91,39,2026-05-25-11-23-36 +0000,cbc,Pope Leo warns that AI challenges must be conf...,https://www.cbc.ca/news/world/pope-leo-magnifi...
180,39,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
155,36,2026-05-25-02-32-08 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
61,35,2026-05-25-14-20-10 +0000,nypost,Oil prices drop 5% after Trump says Iran talks...,https://nypost.com/2026/05/25/business/oil-pri...
200,33,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
123,27,2026-05-25-09-01-55 +0000,nyt,He Name-Drops Ocasio-Cortez in His Bid for Con...,https://www.nytimes.com/2026/05/25/us/politics...
198,26,2026-05-24-20-37-07 +0000,nypost,Dem NJ Sen. Cory Booker trashes own party: ‘De...,https://nypost.com/2026/05/24/us-news/new-jers...
3,24,2026-05-25-17-16-20 +0000,nypost,Spencer Pratt’s latest campaign ad puts LA’s f...,https://nypost.com/2026/05/25/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)