## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-10-13-30-00 +0000,nypost,Trump launches national crackdown on teachers ...,https://nypost.com/2026/07/10/us-news/trump-ad...
1,2026-07-10-13-21-30 +0000,nypost,Wild video shows two cars almost hit pedestria...,https://nypost.com/2026/07/10/us-news/wild-vid...
2,2026-07-10-13-21-26 +0000,nypost,Comcast has been eyeing acquisition of cable r...,https://nypost.com/2026/07/10/media/comcast-ey...
3,2026-07-10-13-15-00 +0000,wsj,"Treasury Yields Rise Amid Data, Geopolitical Lull",https://www.wsj.com/finance/investing/jgbs-edg...
4,2026-07-10-13-14-31 +0000,nyt,How Terrorist Groups Are Using A.I. to Gain an...,https://www.nytimes.com/2026/07/10/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     35
74      iran     21
155      new     17
142  platner     15
141   graham     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
215,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...,109
240,2026-07-09-20-56-28 +0000,nypost,Trump resolved to carry out Iran ‘bitch slap’ ...,https://nypost.com/2026/07/09/us-news/trump-re...,99
213,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...,99
216,2026-07-09-21-56-00 +0000,wsj,"Iran Planned New Trump Assassination Attempt, ...",https://www.wsj.com/politics/iran-planned-new-...,91
315,2026-07-09-16-51-45 +0000,nypost,Israel ready for more war on Iran should Trump...,https://nypost.com/2026/07/09/world-news/israe...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
215,109,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...
213,82,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...
180,63,2026-07-10-00-07-58 +0000,bbc,Charlie Kirk murder suspect told roommate 'he ...,https://www.bbc.co.uk/news/articles/c621v466y9...
115,58,2026-07-10-07-59-30 +0000,nypost,Ex-youth pastor David Vander Meer who allegedl...,https://nypost.com/2026/07/10/us-news/pastor-d...
236,44,2026-07-09-21-03-49 +0000,nyt,"As U.S. Steps Up Attacks on Iran, Prospect of ...",https://www.nytimes.com/2026/07/09/world/middl...
327,42,2026-07-09-16-06-08 +0000,nypost,US existing home sales unexpectedly fall in Ju...,https://nypost.com/2026/07/09/business/us-exis...
230,38,2026-07-09-21-11-24 +0000,nypost,Trump ditches extravagant Qatar-gifted Air For...,https://nypost.com/2026/07/09/world-news/trump...
128,37,2026-07-10-05-38-35 +0000,nypost,NY mom Jamey Carney suffocated to death in Ire...,https://nypost.com/2026/07/10/world-news/ny-mo...
203,36,2026-07-09-22-33-54 +0000,latimes,California will see its first monsoon storms o...,https://www.latimes.com/california/story/2026-...
168,35,2026-07-10-01-01-00 +0000,wsj,Here’s a guide to some of the socialists who c...,https://www.wsj.com/politics/elections/democra...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)