## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-23-41-00 +0000,wsj,U.S. Has Reached Greenland Security Agreement,https://www.wsj.com/politics/national-security...
1,2026-09-18-23-41-00 +0000,wsj,President Trump said the U.S. and Denmark reac...,https://www.wsj.com/politics/national-security...
2,2026-09-18-23-38-51 +0000,nypost,California Marines deploy goats in first of it...,https://nypost.com/2026/09/18/us-news/san-dieg...
3,2026-09-18-23-38-22 +0000,nyt,A Central African Hotel Has Become a Nightmare...,https://www.nytimes.com/2026/09/18/world/afric...
4,2026-09-18-23-30-00 +0000,wsj,Lakers Buyers Lay Out Plans to Reach $30 Billi...,https://www.wsj.com/finance/lakers-buyers-lay-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5    trump     58
41      he     19
386     ai     19
108    new     17
46   house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...,168
59,2026-09-18-21-39-00 +0000,wsj,President Trump said that Donald Trump Jr. rei...,https://www.wsj.com/politics/trump-says-his-so...,162
38,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...,157
142,2026-09-18-18-56-47 +0000,nyt,Judge Who Struck Down Trump’s Compensation Fun...,https://www.nytimes.com/2026/09/18/us/politics...,154
393,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,168,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...
165,79,2026-09-18-17-51-00 +0000,wsj,A new Federal Reserve inquiry into the 2023 co...,https://www.wsj.com/economy/central-banking/ne...
38,72,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...
349,54,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...
393,50,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...
132,48,2026-09-18-19-11-43 +0000,latimes,Driver accused in fatal Metro bus crash had mu...,https://www.latimes.com/california/story/2026-...
203,45,2026-09-18-15-59-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
53,44,2026-09-18-21-44-26 +0000,nypost,Trump announces Greenland deal with Denmark gi...,https://nypost.com/2026/09/18/us-news/trump-an...
163,42,2026-09-18-17-57-30 +0000,bbc,'We simply don't know' - JP Morgan struggling ...,https://www.bbc.co.uk/news/articles/cq0m3gmv8n...
59,40,2026-09-18-21-39-00 +0000,wsj,President Trump said that Donald Trump Jr. rei...,https://www.wsj.com/politics/trump-says-his-so...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)