## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-06-14-51-10 +0000,nypost,Earthquake hits Los Angeles overnight Sunday,https://nypost.com/2026/09/06/us-news/earthqua...
1,2026-09-06-14-48-24 +0000,nypost,Woke rapper Macklemore sparks fury over anti-I...,https://nypost.com/2026/09/06/us-news/woke-rap...
2,2026-09-06-14-45-00 +0000,nypost,Swimmers to swarm hidden California gem as sta...,https://nypost.com/2026/09/06/us-news/californ...
3,2026-09-06-14-41-19 +0000,wapo,U.S. envoys in Kyiv for Russia-Ukraine peace t...,https://www.washingtonpost.com/world/2026/09/0...
4,2026-09-06-14-31-14 +0000,nyt,Trump Administration Again Asks Supreme Court ...,https://www.nytimes.com/2026/09/06/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2469/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
36     trump     20
31   ukraine     12
155      new     11
33     talks     10
28    envoys      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...,70
137,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,59
139,2026-09-05-22-29-37 +0000,wapo,"U.S. envoys meet Putin in Moscow, pressing Rus...",https://www.washingtonpost.com/world/2026/09/0...,57
188,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...,57
100,2026-09-06-07-22-19 +0000,nypost,Trump’s MAGA super PAC pours $10M into Ken Pax...,https://nypost.com/2026/09/06/us-news/trumps-s...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,70,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...
137,39,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
188,37,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...
184,34,2026-09-05-15-17-15 +0000,cbc,U.S. military hits 3 Iranian oil tankers after...,https://www.cbc.ca/news/world/iran-united-stat...
102,30,2026-09-06-06-20-08 +0000,nypost,"Ex-Team USA triathlete, NYC dad drowns while s...",https://nypost.com/2026/09/06/us-news/ex-team-...
32,25,2026-09-06-11-59-56 +0000,nypost,Iran claims strike on unmanned US vessel in St...,https://nypost.com/2026/09/06/world-news/iran-...
114,24,2026-09-06-02-30-00 +0000,nypost,California’s free ride means illegal migrants ...,https://nypost.com/2026/09/05/us-news/inside-c...
101,23,2026-09-06-06-27-16 +0000,nyt,Nepal Floods Buried a House. The Woman Inside ...,https://www.nytimes.com/2026/09/05/world/asia/...
58,22,2026-09-06-10-00-01 +0000,wapo,Trump is running out of time as he tries to re...,https://www.washingtonpost.com/politics/2026/0...
103,22,2026-09-06-06-06-42 +0000,nypost,North Carolina Dem Senate candidate added form...,https://nypost.com/2026/09/06/us-news/north-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)