## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-09-52-52 +0000,bbc,Burnham 'open' to calls for slavery apology bu...,https://www.bbc.co.uk/news/articles/c5398239je...
1,2026-10-31-09-19-29 +0000,nyt,Britain’s Prime Minister Says He’s Open to a F...,https://www.nytimes.com/2026/10/30/world/europ...
2,2026-10-31-09-16-14 +0000,bbc,"CCTV, zip ties and election watchers: How US m...",https://www.bbc.co.uk/news/videos/cw4g1vlj4v2j...
3,2026-10-31-09-06-08 +0000,nyt,Why Haley Stevens Can’t Stop Talking About Abd...,https://www.nytimes.com/2026/10/31/us/haley-st...
4,2026-10-31-09-06-03 +0000,nyt,"Train Disaster Is a Blow to Spain’s Leader, Al...",https://www.nytimes.com/2026/10/31/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2436/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14     election     25
74        trump     24
209  california     17
315         new     17
426     binance     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
343,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,89
48,2026-10-31-03-30-57 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...,85
220,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,81
319,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,75
311,2026-10-30-13-35-51 +0000,nypost,Pope Leo XIV makes history as first pope to vo...,https://nypost.com/2026/10/30/world-news/pope-...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
343,89,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
383,71,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...
215,67,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
87,55,2026-10-31-00-29-58 +0000,bbc,Alaska Senate candidate denies knowing about a...,https://www.bbc.co.uk/news/articles/cmwyq2gg1y...
241,53,2026-10-30-17-41-10 +0000,bbc,Binance's $6.3bn crypto hack biggest in history,https://www.bbc.co.uk/news/videos/c6m2dpz0yxn8...
234,51,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
369,42,2026-10-30-10-35-33 +0000,nyt,U.S. Oil Industry Earned Over $130 Billion in ...,https://www.nytimes.com/2026/10/30/business/en...
283,42,2026-10-30-15-09-29 +0000,nyt,Democrats and Republicans Share Dueling Health...,https://www.nytimes.com/2026/10/30/us/politics...
194,40,2026-10-30-20-17-54 +0000,chitri,Appeals court rejects Justice Department reque...,https://www.chicagotribune.com/2026/10/30/appe...
90,40,2026-10-31-00-17-24 +0000,nypost,Boozed-up driver who plowed into kids at NYPD ...,https://nypost.com/2026/10/30/us-news/boozed-u...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)