## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-14-24-19 +0000,nyt,Iran War Live Updates: Israel’s Strikes in Leb...,https://www.nytimes.com/live/2026/04/09/world/...
1,2026-04-09-14-24-02 +0000,nyt,European Leaders Demand That U.S. Cease-Fire W...,https://www.nytimes.com/2026/04/09/world/middl...
2,2026-04-09-14-24-00 +0000,wsj,Dollar Extends Losses Slightly After Key U.S. ...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-04-09-14-23-31 +0000,nyt,F.B.I. Arrests Ex-Army Employee Who Detailed H...,https://www.nytimes.com/2026/04/09/us/army-lea...
4,2026-04-09-14-21-15 +0000,nyt,Lebanon Mourns After Israeli Barrage Kills Mor...,https://www.nytimes.com/2026/04/09/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
0    iran     85
10   fire     44
9   cease     40
1     war     31
94  trump     31

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-09-14-24-19 +0000,nyt,Iran War Live Updates: Israel’s Strikes in Leb...,https://www.nytimes.com/live/2026/04/09/world/...,329
204,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...,246
347,2026-04-08-16-56-31 +0000,nypost,Iran blocks ships in the Strait of Hormuz with...,https://nypost.com/2026/04/08/world-news/iran-...,230
81,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,226
368,2026-04-08-15-42-15 +0000,nyt,World leaders welcome the Iran cease-fire but ...,https://www.nytimes.com/live/2026/04/08/world/...,223

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,329,2026-04-09-14-24-19 +0000,nyt,Iran War Live Updates: Israel’s Strikes in Leb...,https://www.nytimes.com/live/2026/04/09/world/...
317,78,2026-04-08-18-49-13 +0000,latimes,Iran ceasefire deal frays as attacks continue;...,https://www.latimes.com/politics/story/2026-04...
85,68,2026-04-09-11-13-14 +0000,nypost,Nancy Guthrie’s kidnappers likely didn’t know ...,https://nypost.com/2026/04/09/us-news/nancy-gu...
325,64,2026-04-08-18-25-25 +0000,nyt,Gas Prices Won’t Quickly Return to Prewar Leve...,https://www.nytimes.com/2026/04/08/business/en...
219,47,2026-04-08-23-37-00 +0000,wsj,A federal appeals court has denied Anthropic’s...,https://www.wsj.com/politics/national-security...
20,41,2026-04-09-13-59-16 +0000,nypost,Bahamas police may have tricked Lynette Hooker...,https://nypost.com/2026/04/09/us-news/bahamas-...
204,40,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...
153,40,2026-04-09-07-36-37 +0000,wsj,Stock Market Today: Oil Rebounds After Truce G...,https://www.wsj.com/livecoverage/stock-market-...
50,39,2026-04-09-12-59-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
338,38,2026-04-08-17-18-41 +0000,nypost,Delta scraps capacity growth plans as fuel pri...,https://nypost.com/2026/04/08/business/delta-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)