## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-19-05-53-53 +0000,bbc,"South Korea shortens war games with US, citing...",https://www.bbc.co.uk/news/articles/cnvn0j31qj...
1,2026-08-19-05-47-41 +0000,nypost,Ohio mom of 3 killed when massive tree crashes...,https://nypost.com/2026/08/19/us-news/ohio-mot...
2,2026-08-19-05-44-12 +0000,nypost,Arizona teen beaten to death while protecting ...,https://nypost.com/2026/08/19/us-news/arizona-...
3,2026-08-19-05-42-46 +0000,nypost,Florida carries out 13th execution this year a...,https://nypost.com/2026/08/19/us-news/florida-...
4,2026-08-19-05-36-03 +0000,nyt,A Stunning Win for the Left in Florida: 6 Take...,https://www.nytimes.com/2026/08/19/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2602/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
106    trump     53
34   florida     34
198  primary     19
169      new     18
95    senate     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
93,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...,145
40,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...,144
91,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...,137
101,2026-08-18-23-56-32 +0000,nyt,"Sydney Gruters, Wife of R.N.C. Chair, Wins Hou...",https://www.nytimes.com/2026/08/18/us/politics...,132
45,2026-08-19-02-58-35 +0000,nyt,Eric Barlow Wins Wyoming’s Republican Governor...,https://www.nytimes.com/2026/08/18/us/politics...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
93,145,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...
87,76,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...
395,65,2026-08-18-08-10-32 +0000,wsj,"Stock Market News, August 18, 2026: Tech Stock...",https://www.wsj.com/livecoverage/stock-market-...
66,64,2026-08-19-01-43-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
308,61,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...
91,50,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...
79,47,2026-08-19-00-54-47 +0000,cbc,Meta trial begins with states accusing social ...,https://www.cbc.ca/news/world/meta-trial-opens...
36,44,2026-08-19-03-18-00 +0000,wsj,"California Merlots, Kentucky bourbons and Tenn...",https://www.wsj.com/world/americas/why-canadas...
140,44,2026-08-18-21-48-15 +0000,nypost,"RFK Jr.’s son, Conor Kennedy, put on Russian w...",https://nypost.com/2026/08/18/world-news/rfk-j...
311,42,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)