## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-22-18-59-44 +0000,nypost,Here’s what ace cold-case detective has to say...,https://nypost.com/2026/03/22/us-news/cold-cas...
1,2026-03-22-18-52-43 +0000,nyt,BTS’s Comeback Show Was Heavy on Their New Album,https://www.nytimes.com/live/2026/03/21/world/...
2,2026-03-22-18-52-09 +0000,nyt,Israeli Officials Said U.S. Was Told About Sou...,https://www.nytimes.com/2026/03/19/world/middl...
3,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...
4,2026-03-22-18-49-05 +0000,nyt,Israel Thought It Could Spur Rebellion Inside ...,https://www.nytimes.com/2026/03/22/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
27   trump     31
31    iran     26
32     war     13
17     new     10
103  power      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,97
15,2026-03-22-18-21-01 +0000,startribune,Iran threatens to 'completely' close Strait of...,https://www.startribune.com/trump-threatens-at...,93
16,2026-03-22-18-19-17 +0000,nyt,Iran War Live Updates: Tehran Is Defiant After...,https://www.nytimes.com/live/2026/03/22/world/...,91
100,2026-03-22-10-06-06 +0000,wapo,Trump threatens to ‘obliterate’ Iran’s power p...,https://www.washingtonpost.com/world/2026/03/2...,86
27,2026-03-22-17-51-18 +0000,wapo,Joe Kent says he wants Trump to hear MAGA oppo...,https://www.washingtonpost.com/national-securi...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,97,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...
151,49,2026-03-22-00-47-52 +0000,nypost,Over 100 Israeli civilians wounded by new Ira...,https://nypost.com/2026/03/21/world-news/over-...
25,43,2026-03-22-17-58-52 +0000,nyt,ICE to Help TSA at Airports Amid Partial Shutd...,https://www.nytimes.com/2026/03/22/us/politics...
145,39,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...
15,36,2026-03-22-18-21-01 +0000,startribune,Iran threatens to 'completely' close Strait of...,https://www.startribune.com/trump-threatens-at...
88,35,2026-03-22-12-52-00 +0000,wsj,South Korean President Lee Jae Myung has nomin...,https://www.wsj.com/economy/central-banking/so...
172,31,2026-03-21-21-23-49 +0000,nyt,Iran Fires Missiles at Far-Off Diego Garcia Ba...,https://www.nytimes.com/2026/03/21/us/politics...
72,31,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
17,28,2026-03-22-18-16-01 +0000,nypost,Atlanta airport slammed with nearly 3-hour wai...,https://nypost.com/2026/03/22/us-news/this-us-...
60,25,2026-03-22-15-41-03 +0000,nypost,NYC kin of ‘perfect child’ slain in unsolved c...,https://nypost.com/2026/03/22/us-news/nyc-kin-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)