## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-07-16-00-12 +0000,nypost,University of Arizona halts fraternity activit...,https://nypost.com/2026/10/07/us-news/universi...
1,2026-10-07-16-00-00 +0000,missionlocal,What do you think of artificial intelligence?,https://missionlocal.org/2026/10/what-do-you-t...
2,2026-10-07-15-57-51 +0000,bbc,France halts use of stun grenades after boy's ...,https://www.bbc.co.uk/news/articles/cqzjx7z2r4...
3,2026-10-07-15-57-43 +0000,bbc,Boots sold in £7bn deal to Canadian billionair...,https://www.bbc.co.uk/news/articles/cwly0jyk2v...
4,2026-10-07-15-56-06 +0000,nyt,Christa Pike’s Lawyers Prepare to Argue Over P...,https://www.nytimes.com/2026/10/07/us/christa-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
47     trump     35
39       new     19
31   christa     13
183   plague     13
32      pike     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
391,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,114
36,2026-10-07-14-50-28 +0000,bbc,Trump to speak to Putin about plague lab worke...,https://www.bbc.co.uk/news/articles/cqgm0vrl3x...,86
256,2026-10-07-00-18-00 +0000,wsj,The civil lawsuit a young woman recently filed...,https://www.wsj.com/us-news/law/cornell-sexual...,83
91,2026-10-07-12-41-55 +0000,nypost,New Cornell footage shows frat bros telling in...,https://nypost.com/2026/10/07/us-news/cornell-...,82
153,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
391,114,2026-10-06-19-36-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
256,83,2026-10-07-00-18-00 +0000,wsj,The civil lawsuit a young woman recently filed...,https://www.wsj.com/us-news/law/cornell-sexual...
273,72,2026-10-06-23-04-37 +0000,nypost,Russia accused of covering up plague outbreak ...,https://nypost.com/2026/10/06/world-news/russi...
91,72,2026-10-07-12-41-55 +0000,nypost,New Cornell footage shows frat bros telling in...,https://nypost.com/2026/10/07/us-news/cornell-...
243,64,2026-10-07-01-57-14 +0000,nypost,"Troy Jackson trashes voter ID policy, relies o...",https://nypost.com/2026/10/06/us-news/troy-jac...
16,58,2026-10-07-15-32-46 +0000,cbc,"Lawyers for Christa Pike, 1st known person to ...",https://www.cbc.ca/news/world/livestory/christ...
318,55,2026-10-06-21-29-32 +0000,missionlocal,‘We need a jingle’: Will voters know the ‘Yes-...,https://missionlocal.org/2026/10/california-bi...
328,50,2026-10-06-21-12-30 +0000,nyt,S&P 500 Hits Record High Amid Rising Interest ...,https://www.nytimes.com/2026/10/06/business/st...
198,48,2026-10-07-08-34-56 +0000,wsj,"Stock Market Today: Dow Falls, Treasury Yields...",https://www.wsj.com/livecoverage/stock-market-...
227,45,2026-10-07-03-58-15 +0000,nypost,Wes Moore – potential 2028 White House hopeful...,https://nypost.com/2026/10/06/us-news/wes-moor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)