## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-16-05-50-00 +0000,wsj,Schneider Electric Boosts Outlook Again After ...,https://www.wsj.com/business/earnings/schneide...
1,2026-10-16-05-30-57 +0000,bbc,Fuel costs squeezing margins for some businesses,https://www.bbc.co.uk/news/articles/c9rky27ljr...
2,2026-10-16-05-28-00 +0000,wsj,Asia Stocks Recover Some Ground After Tech Rout,https://www.wsj.com/finance/stocks/asia-stocks...
3,2026-10-16-05-28-00 +0000,nypost,Cause of death revealed for Southwest flight a...,https://nypost.com/2026/10/16/us-news/southwes...
4,2026-10-16-05-17-00 +0000,wsj,Indonesian Stocks Dive as MSCI Weighs Downgrad...,https://www.wsj.com/finance/investing/indonesi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2377/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
68     trump     34
324      new     28
245  ukraine     22
134   school     18
37    market     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
135,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...,179
291,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...,123
155,2026-10-15-20-46-18 +0000,chitri,Ukraine abandons truce and attacks Russian oil...,https://www.chicagotribune.com/2026/10/15/ukra...,113
7,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...,98
31,2026-10-16-02-48-41 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
135,179,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...
286,93,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...
50,71,2026-10-16-01-45-00 +0000,wsj,Three Children and One Teacher Killed in Eleme...,https://www.wsj.com/us-news/three-children-and...
178,65,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...
295,64,2026-10-15-14-19-00 +0000,wsj,Florida’s Democratic Senate nominee Angie Nixo...,https://www.wsj.com/politics/elections/the-int...
13,57,2026-10-16-04-41-00 +0000,wsj,Fed Chairman Kevin Warsh declined to endorse o...,https://www.wsj.com/economy/central-banking/wa...
7,56,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...
291,51,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...
115,47,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
390,44,2026-10-15-08-17-42 +0000,wsj,"Stock Market News, Oct. 15, 2026: Investors Bo...",https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)