## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-02-19-17-17 +0000,nyt,Crew Member Is Missing After Helicopter’s Emer...,https://www.nytimes.com/2026/07/01/us/navy-hel...
1,2026-07-02-19-17-09 +0000,nypost,Grieving Ukrainian mom crouches over dead son ...,https://nypost.com/2026/07/02/world-news/gut-w...
2,2026-07-02-19-13-10 +0000,nypost,Swarm of bull sharks shut down NYC’s Rockaway ...,https://nypost.com/2026/07/02/us-news/swarm-of...
3,2026-07-02-19-12-42 +0000,nypost,Fresno hit with major peach heist — as suspect...,https://nypost.com/2026/07/02/us-news/thieves-...
4,2026-07-02-19-12-00 +0000,wsj,Treasury Yields Rise in Holiday Shortened Week,https://www.wsj.com/articles/jgbs-edge-lower-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2510/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
149   trump     41
652   world     13
192    iran     13
268  market     12
448     new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
245,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...,91
188,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,90
214,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...,85
259,2026-07-02-00-20-33 +0000,nypost,Ex-Trump adviser Kellogg says prez should brac...,https://nypost.com/2026/07/01/world-news/keith...,81
288,2026-07-01-22-17-27 +0000,nypost,Inside the new Air Force One: Trump’s Qatari j...,https://nypost.com/2026/07/01/us-news/inside-t...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
245,91,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...
114,70,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
241,51,2026-07-02-03-00-00 +0000,wsj,Europe Learns It’s Hard to Start a Trade War W...,https://www.wsj.com/world/china/europe-learns-...
67,51,2026-07-02-16-56-38 +0000,nypost,Texas mom’s chilling last post before she was ...,https://nypost.com/2026/07/02/us-news/texas-mo...
5,49,2026-07-02-19-10-58 +0000,nypost,California’s Fourth of July gas prices will dr...,https://nypost.com/2026/07/02/us-news/californ...
191,44,2026-07-02-10-21-05 +0000,cbc,"Deadly, large-scale Russian attack shakes Kyiv...",https://www.cbc.ca/news/world/missile-drone-at...
140,43,2026-07-02-13-36-04 +0000,bbc,World Cup boom falters as US hospitality jobs ...,https://www.bbc.co.uk/news/articles/cr471w6ykx...
20,39,2026-07-02-18-40-10 +0000,nypost,Goodyear Blimp sails above NYC like fleet of s...,https://nypost.com/2026/07/02/us-news/goodyear...
215,36,2026-07-02-08-44-07 +0000,wapo,Russia rocks Ukrainian capital with massive as...,https://www.washingtonpost.com/world/2026/07/0...
135,34,2026-07-02-13-54-28 +0000,nyt,Latest Jobs Report Shows Labor Market Is Not a...,https://www.nytimes.com/2026/07/02/business/ec...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)