## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-10-57-08 +0000,nypost,"Hochul, Blakeman square off in only NY gov deb...",https://nypost.com/2026/10/14/us-news/hochul-b...
1,2026-10-14-10-50-11 +0000,bbc,"Turkish police raid opposition TV station, hal...",https://www.bbc.co.uk/news/articles/crx23y3d97...
2,2026-10-14-10-50-00 +0000,wsj,"Eroding support from working-class, white vote...",https://www.wsj.com/politics/policy/the-workin...
3,2026-10-14-10-47-00 +0000,wsj,Ukraine Says New Starlink Speed Limit Is Disru...,https://www.wsj.com/world/europe/ukraine-says-...
4,2026-10-14-10-43-00 +0000,wsj,Malaysia Pharmacy Chain Braves Volatile Market...,https://www.wsj.com/business/malaysia-pharmacy...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
26       trump     42
37         new     19
247         ai     19
206   kimberly     16
207  guilfoyle     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
136,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,167
399,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,138
368,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,125
225,2026-10-13-21-54-45 +0000,nypost,Trump personally prepped Katie Zacharia for fi...,https://nypost.com/2026/10/13/us-news/trump-pe...,123
354,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
136,167,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
172,106,2026-10-14-01-00-00 +0000,wsj,"Trying to save her job, Kimberly Guilfoyle cla...",https://www.wsj.com/politics/policy/kimberly-g...
191,74,2026-10-13-23-21-01 +0000,nypost,Ilhan Omar’s husband spotted for first time si...,https://nypost.com/2026/10/13/us-news/ilhan-om...
382,72,2026-10-13-15-06-27 +0000,chitri,Six Flags Great America roller coaster closed ...,https://www.chicagotribune.com/2026/10/13/six-...
9,65,2026-10-14-10-31-04 +0000,nypost,Russell Brand admits he’s ‘concerned’ at start...,https://nypost.com/2026/10/14/world-news/russe...
368,58,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...
251,56,2026-10-13-21-13-00 +0000,wsj,Kimberly Guilfoyle resigned as the U.S. ambass...,https://www.wsj.com/politics/policy/kimberly-g...
105,56,2026-10-14-07-22-00 +0000,wsj,Oil Prices Rise as Traders Weigh Saudi Aramco ...,https://www.wsj.com/business/energy-oil/oil-pr...
321,51,2026-10-13-18-10-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
144,47,2026-10-14-03-52-38 +0000,latimes,Bass and Raman trade blows over police chief i...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)