## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-08-05-27-43 +0000,nyt,"Iran War Live Updates: U.S., Iran and Israel A...",https://www.nytimes.com/live/2026/04/07/world/...
1,2026-04-08-05-26-00 +0000,wsj,Asian Currencies Strengthen Amid Risk-on Senti...,https://www.wsj.com/finance/currencies/middle-...
2,2026-04-08-05-10-19 +0000,nypost,Pacific Surfliner debuts LA and SLO trips — ma...,https://nypost.com/2026/04/08/us-news/amtrak-p...
3,2026-04-08-05-09-56 +0000,bbc,Foodbank hub set to expand to meet growing demand,https://www.bbc.com/news/articles/cy01k55ygl7o...
4,2026-04-08-05-04-49 +0000,nyt,An 11th-Hour Deal,https://www.nytimes.com/2026/04/07/world/iran-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0          iran     70
164       trump     68
1           war     28
657    deadline     15
80   california     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
100,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...,264
22,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...,252
111,2026-04-07-22-42-19 +0000,nypost,Strait of Hormuz to reopen after Trump announc...,https://nypost.com/2026/04/07/world-news/trump...,202
262,2026-04-07-15-39-14 +0000,nypost,Iranian-American Dem pushes wild plot to impea...,https://nypost.com/2026/04/07/us-news/iranian-...,200
0,2026-04-08-05-27-43 +0000,nyt,"Iran War Live Updates: U.S., Iran and Israel A...",https://www.nytimes.com/live/2026/04/07/world/...,198

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
100,264,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...
22,107,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...
250,82,2026-04-07-16-07-18 +0000,nypost,"Russia, China reject resolution to reopen Stra...",https://nypost.com/2026/04/07/us-news/russia-c...
49,65,2026-04-08-01-53-00 +0000,wsj,Republican Clayton Fuller won the special elec...,https://www.wsj.com/politics/elections/republi...
28,48,2026-04-08-03-38-57 +0000,nypost,Gas pain won’t pump the brakes as Californians...,https://nypost.com/2026/04/07/us-news/gas-pain...
24,43,2026-04-08-03-54-35 +0000,nypost,California would fund lawyers for all illegal ...,https://nypost.com/2026/04/07/us-news/californ...
220,41,2026-04-07-17-47-20 +0000,nypost,"The secret, never-before-used CIA tool that he...",https://nypost.com/2026/04/07/us-news/ghost-mu...
271,38,2026-04-07-14-51-07 +0000,bbc,One gunman killed and two injured in shooting ...,https://www.bbc.com/news/articles/c3exp8j7yz4o...
358,37,2026-04-07-07-38-46 +0000,wsj,"Stock Market News, April 7, 2026: Stock Future...",https://www.wsj.com/livecoverage/stock-market-...
32,36,2026-04-08-03-16-14 +0000,nypost,ISIS-loving NYC bombing suspects mused about b...,https://nypost.com/2026/04/07/us-news/isis-lov...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)