## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-08-01-17-30 +0000,nyt,"Clay Fuller, Trump Ally, Will Take Marjorie Ta...",https://www.nytimes.com/2026/04/07/us/politics...
1,2026-04-08-01-13-00 +0000,wsj,Asian Currencies Strengthen as Cease-Fire Spur...,https://www.wsj.com/finance/currencies/middle-...
2,2026-04-08-01-12-17 +0000,nyt,Iran War Live Updates: U.S. and Iran Agree to ...,https://www.nytimes.com/live/2026/04/07/world/...
3,2026-04-08-01-11-40 +0000,nypost,Florida bookkeeper accused of embezeling hundr...,https://nypost.com/2026/04/07/us-news/florida-...
4,2026-04-08-01-10-46 +0000,wapo,"U.S. journalist Shelly Kittleson, kidnapped in...",https://www.washingtonpost.com/world/2026/04/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
2         trump     71
18         iran     70
19          war     29
357    deadline     19
51   california     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-08-01-12-17 +0000,nyt,Iran War Live Updates: U.S. and Iran Agree to ...,https://www.nytimes.com/live/2026/04/07/world/...,271
50,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...,270
64,2026-04-07-22-42-19 +0000,nypost,Strait of Hormuz to reopen after Trump announc...,https://nypost.com/2026/04/07/world-news/trump...,205
228,2026-04-07-15-39-14 +0000,nypost,Iranian-American Dem pushes wild plot to impea...,https://nypost.com/2026/04/07/us-news/iranian-...,205
202,2026-04-07-16-39-49 +0000,cbc,Carney urges 'all parties' in Iran war not to ...,https://www.cbc.ca/news/politics/carney-iran-w...,201

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,271,2026-04-08-01-12-17 +0000,nyt,Iran War Live Updates: U.S. and Iran Agree to ...,https://www.nytimes.com/live/2026/04/07/world/...
64,64,2026-04-07-22-42-19 +0000,nypost,Strait of Hormuz to reopen after Trump announc...,https://nypost.com/2026/04/07/world-news/trump...
326,58,2026-04-07-08-15-00 +0000,wsj,China Caps Rise in Fuel Prices as Middle East ...,https://www.wsj.com/finance/commodities-future...
274,54,2026-04-07-12-14-23 +0000,nypost,US strikes Iran’s oil-critical Kharg Island — ...,https://nypost.com/2026/04/07/world-news/us-st...
13,54,2026-04-08-00-52-00 +0000,wsj,Republican Clayton Fuller won the special elec...,https://www.wsj.com/politics/elections/republi...
346,43,2026-04-07-04-26-59 +0000,nyt,Trump Calls Artemis II Astronauts After Their ...,https://www.nytimes.com/2026/04/07/us/politics...
89,42,2026-04-07-21-46-06 +0000,latimes,ICE agents in Northern California shoot man af...,https://www.latimes.com/california/story/2026-...
238,39,2026-04-07-14-51-07 +0000,bbc,One gunman killed and two injured in shooting ...,https://www.bbc.com/news/articles/c3exp8j7yz4o...
218,37,2026-04-07-16-01-00 +0000,wsj,The U.S. labor market bounced back last month ...,https://www.wsj.com/economy/jobs/why-more-peop...
50,36,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)