## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-30-10-01-41 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...
1,2026-03-30-10-00-00 +0000,nypost,Blakeman accuses Hochul of pay-to-play scheme ...,https://nypost.com/2026/03/30/us-news/blakeman...
2,2026-03-30-10-00-00 +0000,nypost,Pepper spray would be easier to get under NY b...,https://nypost.com/2026/03/30/us-news/pepper-s...
3,2026-03-30-10-00-00 +0000,latimes,"Next to Joshua Tree National Park, a mining co...",https://www.latimes.com/california/story/2026-...
4,2026-03-30-10-00-00 +0000,latimes,A SoCal native is set to pilot NASA's lunar mi...,https://www.latimes.com/science/story/2026-03-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     27
0     iran     23
1      war     20
6      oil     15
84  killed     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-30-10-01-41 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...,124
188,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...,85
103,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...,84
68,2026-03-30-05-09-05 +0000,nyt,Trump Says Iran Agreed to Allow 20 More Ships ...,https://www.nytimes.com/2026/03/29/world/middl...,80
167,2026-03-29-18-00-56 +0000,nyt,Is Iran a Political Problem for Trump? Tell Me...,https://www.nytimes.com/2026/03/28/upshot/iran...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,124,2026-03-30-10-01-41 +0000,nyt,Iran War Live Updates: Trump Says Iran to Allo...,https://www.nytimes.com/live/2026/03/30/world/...
195,42,2026-03-29-14-35-49 +0000,nypost,Air Canada flight attendant who was ejected du...,https://nypost.com/2026/03/29/world-news/air-c...
188,42,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...
64,36,2026-03-30-05-38-26 +0000,bbc,Fuel tax halved and free public transport offe...,https://www.bbc.com/news/articles/c937n0yxggeo...
103,34,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...
102,34,2026-03-30-01-09-44 +0000,nypost,Scale of carnage at LA’s ‘No Kings’ protest la...,https://nypost.com/2026/03/29/us-news/no-kings...
89,31,2026-03-30-02-15-21 +0000,wapo,"U.S. will let Russian oil tanker reach Cuba, b...",https://www.washingtonpost.com/world/2026/03/2...
98,29,2026-03-30-01-22-36 +0000,nypost,"NYC fire that killed child, 3 others in proble...",https://nypost.com/2026/03/29/us-news/nyc-fire...
149,26,2026-03-29-20-11-58 +0000,nypost,"F-16 fighter jets scramble, deploy flares afte...",https://nypost.com/2026/03/29/us-news/palm-bea...
178,25,2026-03-29-16-42-36 +0000,cbc,The NDP has a new leader. What does Avi Lewis'...,https://www.cbc.ca/news/politics/ndp-new-leade...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)