## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-16-10-17-04 +0000,nyt,Iran War Live Updates: Pakistan’s Shuttle Dipl...,https://www.nytimes.com/live/2026/04/16/world/...
1,2026-04-16-10-17-02 +0000,nyt,Pakistan Looks to Play Peacemaker Between U.S....,https://www.nytimes.com/2026/04/16/world/asia/...
2,2026-04-16-10-14-00 +0000,wsj,Chip Maker TSMC Is More Bullish Than Ever on A...,https://www.wsj.com/business/earnings/tsmc-pos...
3,2026-04-16-10-10-21 +0000,bbc,UK prepares for food shortages in worst case s...,https://www.bbc.com/news/articles/cpvxp4xnrwdo...
4,2026-04-16-10-09-13 +0000,nyt,Trump Says Leaders From Israel and Lebanon Wil...,https://www.nytimes.com/2026/04/16/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     50
27   trump     46
1      war     33
245   year     17
259    new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
190,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...,162
356,2026-04-15-15-27-22 +0000,bbc,Starmer says he's 'not going to yield' to pres...,https://www.bbc.com/news/articles/cdxdd7ddzgdo...,150
391,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...,147
240,2026-04-15-20-07-10 +0000,nyt,Senate Republicans Again Block Bid to Limit Tr...,https://www.nytimes.com/2026/04/15/us/politics...,147
37,2026-04-16-09-04-25 +0000,nyt,"Jesus Memes, Threats and a War in Iran: A Port...",https://www.nytimes.com/2026/04/16/us/politics...,143

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
190,162,2026-04-15-21-44-37 +0000,cbc,Trump administration signals optimism about en...,https://www.cbc.ca/news/world/iran-trump-deal-...
391,101,2026-04-15-13-46-00 +0000,wsj,President Trump doubled down on the Justice De...,https://www.wsj.com/economy/central-banking/tr...
269,66,2026-04-15-19-21-54 +0000,cbc,"Jury finds Live Nation, Ticketmaster had anti-...",https://www.cbc.ca/news/entertainment/live-nat...
110,52,2026-04-16-03-33-42 +0000,nypost,13-year-old suspect identified in violent shoo...,https://nypost.com/2026/04/15/us-news/13-year-...
129,51,2026-04-16-01-53-01 +0000,latimes,An immigration agent shot out his eye at a 'No...,https://www.latimes.com/california/story/2026-...
29,49,2026-04-16-09-09-00 +0000,wsj,Rep. Eric Swalwell of California earned endors...,https://www.wsj.com/politics/elections/swalwel...
79,48,2026-04-16-06-42-51 +0000,bbc,"Big energy shock will push up prices, Bank bos...",https://www.bbc.com/news/articles/cn5330l73y2o...
162,46,2026-04-15-23-00-00 +0000,wsj,The Trump administration wants automakers and ...,https://www.wsj.com/politics/national-security...
265,42,2026-04-15-19-28-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
282,40,2026-04-15-18-53-10 +0000,nypost,Chinese oil tanker’s retreat from the Strait o...,https://nypost.com/2026/04/15/world-news/chine...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)