## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-15-06-54 +0000,bbc,Why are gas prices soaring and how could it af...,https://www.bbc.com/news/articles/cj6d66w0995o...
1,2026-03-19-15-06-49 +0000,nyt,Iran War Live Updates: U.S. Scrambles to Ease ...,https://www.nytimes.com/live/2026/03/19/world/...
2,2026-03-19-15-06-28 +0000,nyt,"In This Crisis, the Best Investors Can Expect ...",https://www.nytimes.com/2026/03/19/business/fe...
3,2026-03-19-15-04-27 +0000,wapo,Cities race to confront César Chavez’s legacy ...,https://www.washingtonpost.com/nation/2026/03/...
4,2026-03-19-15-04-21 +0000,nyt,Afroman Wins Civil Trial Over Use of Police Ra...,https://www.nytimes.com/2026/03/19/us/afroman-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2625/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
5      iran     66
6       war     35
314   trump     34
24   chavez     23
190   cesar     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
307,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...,197
42,2026-03-19-14-07-28 +0000,bbc,Are US and Israel in lockstep in Iran war? Dec...,https://www.bbc.com/news/articles/c8x7leknlywo...,191
138,2026-03-19-10-37-36 +0000,bbc,Trump threatens to blow up 'entirety' of majo...,https://www.bbc.com/news/articles/c93j37egjdeo...,166
278,2026-03-18-23-08-16 +0000,wapo,Israel steps up assassinations as Iran war wid...,https://www.washingtonpost.com/world/2026/03/1...,163
400,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,159

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
307,197,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...
34,94,2026-03-19-14-26-24 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
212,89,2026-03-19-04-05-00 +0000,wsj,Escalating Attacks on Gulf Energy Assets Plung...,https://www.wsj.com/world/middle-east/escalati...
235,64,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
102,59,2026-03-19-12-13-34 +0000,nypost,Barcelona police found missing Alabama student...,https://nypost.com/2026/03/19/world-news/barce...
189,57,2026-03-19-08-52-12 +0000,nyt,"Gas Prices in Japan Hit Record High, Testing L...",https://www.nytimes.com/2026/03/19/business/ja...
170,56,2026-03-19-09-20-00 +0000,wsj,Sweden’s Central Bank Holds Key Rate as Middle...,https://www.wsj.com/articles/swedens-central-b...
134,46,2026-03-19-10-55-00 +0000,wsj,"Tulsi Gabbard, a longtime foe of U.S. involvem...",https://www.wsj.com/politics/for-tulsi-gabbard...
32,45,2026-03-19-14-31-41 +0000,nypost,Spring break travelers face hourslong airport ...,https://nypost.com/2026/03/19/us-news/spring-b...
407,41,2026-03-18-16-48-00 +0000,wsj,6 of the Best Wealth Management Firms: Well-Kn...,https://www.wsj.com/buyside/personal-finance/f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)