## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-11-48-56 +0000,nyt,Why Are There Protests in France?,https://www.nytimes.com/article/france-student...
1,2026-10-31-11-42-16 +0000,nyt,"Train Disaster Is a Blow to Spain’s Leader, Al...",https://www.nytimes.com/2026/10/31/world/europ...
2,2026-10-31-11-41-34 +0000,nypost,Spirit Halloween shopper recounts heart-stoppi...,https://nypost.com/2026/10/31/us-news/spirit-h...
3,2026-10-31-11-21-17 +0000,nypost,House ‘Squad’ poised to double in size — and t...,https://nypost.com/2026/10/31/us-news/house-sq...
4,2026-10-31-11-21-14 +0000,nypost,Trump DOJ warns election officials of possible...,https://nypost.com/2026/10/31/us-news/trump-do...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2887/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
9      election     26
33        trump     25
18   california     19
600     binance     14
582        your     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
370,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,93
4,2026-10-31-11-21-14 +0000,nypost,Trump DOJ warns election officials of possible...,https://nypost.com/2026/10/31/us-news/trump-do...,89
78,2026-10-31-03-30-57 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...,88
244,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,84
342,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
370,93,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
193,63,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...
239,62,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
258,53,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
301,51,2026-10-30-15-47-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
180,48,2026-10-30-21-17-37 +0000,nyt,Binance’s $6.3 Billion Hack Is Just the Start ...,https://www.nytimes.com/2026/10/30/technology/...
60,42,2026-10-31-07-14-40 +0000,nypost,"One dead, 6 injured in shooting inside Spirit ...",https://nypost.com/2026/10/31/us-news/californ...
337,40,2026-10-30-13-16-17 +0000,nypost,Canadian family desperately ‘tried to fight of...,https://nypost.com/2026/10/30/world-news/canad...
355,38,2026-10-30-12-04-57 +0000,nypost,Disgraced ex-Prince Andrew under fresh investi...,https://nypost.com/2026/10/30/world-news/disgr...
96,38,2026-10-31-01-45-41 +0000,nypost,Nithya Raman accused of breaking the law with ...,https://nypost.com/2026/10/30/us-news/nithya-r...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)