## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-13-17-49 +0000,nypost,Migrant seen cooking a cat on makeshift fire a...,https://nypost.com/2026/04/22/world-news/migra...
1,2026-04-22-13-15-00 +0000,wsj,Why Gasoline Is So Much Cheaper in the U.S. Th...,https://www.wsj.com/economy/why-gasoline-is-so...
2,2026-04-22-13-15-00 +0000,wsj,American consumers are paying less for gas tha...,https://www.wsj.com/economy/why-gasoline-is-so...
3,2026-04-22-13-13-14 +0000,bbc,Starmer admits No 10 asked about job for aide ...,https://www.bbc.com/news/articles/cq59xx6n3j7o...
4,2026-04-22-13-13-02 +0000,nyt,Iran War Live Updates: Iranian Forces Claim Se...,https://www.nytimes.com/live/2026/04/22/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
43   trump     46
34    iran     41
74      up     19
126    new     18
35     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
332,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...,197
185,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,155
115,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,146
53,2026-04-22-10-45-39 +0000,bbc,Oil prices fluctuate as Trump extends Iran war...,https://www.bbc.com/news/articles/c995dkl4dvvo...,144
4,2026-04-22-13-13-02 +0000,nyt,Iran War Live Updates: Iranian Forces Claim Se...,https://www.nytimes.com/live/2026/04/22/world/...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
332,197,2026-04-21-17-51-00 +0000,nypost,Trump calls off Iran War peace talks and exten...,https://nypost.com/2026/04/21/us-news/vance-ar...
71,70,2026-04-22-10-00-00 +0000,latimes,He was the real Marty Supreme's landlord. Now ...,https://www.latimes.com/entertainment-arts/bus...
19,57,2026-04-22-12-50-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
236,56,2026-04-21-21-47-00 +0000,wsj,Here are the moments that stood out at the Sen...,https://www.wsj.com/economy/central-banking/ke...
386,52,2026-04-21-14-52-47 +0000,cbc,"2 Palestinians, including 14-year-old, killed ...",https://www.cbc.ca/news/world/palestinians-kil...
90,45,2026-04-22-09-14-00 +0000,wsj,Oil Rises After Attack on Two Ships in Strait ...,https://www.wsj.com/finance/commodities-future...
111,44,2026-04-22-08-00-00 +0000,cbc,John Ternus is replacing Tim Cook as Apple CEO...,https://www.cbc.ca/news/business/john-ternus-a...
2,42,2026-04-22-13-15-00 +0000,wsj,American consumers are paying less for gas tha...,https://www.wsj.com/economy/why-gasoline-is-so...
63,39,2026-04-22-10-06-17 +0000,nypost,"Dr. Oz touts ‘Fraud War Room,’ ending payments...",https://nypost.com/2026/04/22/us-news/dr-oz-to...
219,38,2026-04-21-22-47-00 +0000,wsj,OpenAI Under Criminal Probe in Florida Over Ma...,https://www.wsj.com/us-news/law/openai-under-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)