## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-00-00-00 +0000,wsj,The kids are “Nixonmaxxing”: More than half-a-...,https://www.wsj.com/politics/richard-nixon-soc...
1,2026-07-18-00-00-00 +0000,wsj,They Call Her ‘the Assassin’ on Wall Street—an...,https://www.wsj.com/finance/fahmi-quadir-indus...
2,2026-07-17-23-56-26 +0000,nypost,Shocking LA parking-ticket scheme squeezes jaw...,https://nypost.com/2026/07/17/us-news/los-ange...
3,2026-07-17-23-56-24 +0000,nyt,Iran War Live Updates: Bridges and Water Plant...,https://www.nytimes.com/live/2026/07/17/world/...
4,2026-07-17-23-56-08 +0000,bbc,What this desert city can teach the world abou...,https://www.bbc.co.uk/news/articles/cgl3lnpxy6...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2639/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
113     trump     47
305  election     20
18        new     17
62      china     15
501   burnham     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
267,2026-07-17-10-42-00 +0000,wsj,President Trump’s speech Thursday night set ou...,https://www.wsj.com/politics/policy/trumps-25-...,125
325,2026-07-17-03-04-00 +0000,wsj,President Trump delivered an extraordinary pri...,https://www.wsj.com/politics/elections/trump-a...,124
39,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...,116
254,2026-07-17-11-37-00 +0000,bbc,Trump alleges China meddled in 2020 election a...,https://www.bbc.co.uk/news/articles/cx2k9wvv5w...,108
161,2026-07-17-16-46-12 +0000,nypost,Trump claims California may have 190K non-citi...,https://nypost.com/2026/07/17/us-news/trump-ad...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
267,125,2026-07-17-10-42-00 +0000,wsj,President Trump’s speech Thursday night set ou...,https://www.wsj.com/politics/policy/trumps-25-...
313,78,2026-07-17-05-24-56 +0000,nypost,Andy Burnham declared leader of Britain’s Labo...,https://nypost.com/2026/07/17/world-news/manch...
247,69,2026-07-17-12-34-28 +0000,nypost,NYC wakes up to ‘unhealthy’ air quality from C...,https://nypost.com/2026/07/17/us-news/nyc-has-...
145,55,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...
53,49,2026-07-17-21-38-00 +0000,wsj,China’s Moonshot AI Adds More Fuel to Wall Str...,https://www.wsj.com/finance/stocks/chinas-moon...
236,48,2026-07-17-13-00-00 +0000,wsj,"The Treasury market looks healthy, but underne...",https://www.wsj.com/finance/investing/how-sky-...
39,47,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...
116,42,2026-07-17-19-19-07 +0000,startribune,A Twin Cities suburb says it needs a new $33 m...,https://www.startribune.com/mendota-heights-ci...
350,41,2026-07-17-00-30-00 +0000,wsj,Well-off boomers are increasingly upsizing the...,https://www.wsj.com/economy/housing/baby-boome...
131,40,2026-07-17-18-21-10 +0000,latimes,California-based Taylor Farms pulls iceberg le...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)