## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-14-02-53-04 +0000,nypost,11-year-old boy killed when go-kart overturns ...,https://nypost.com/2026/09/13/us-news/11-year-...
1,2026-09-14-02-43-12 +0000,nypost,Chick-fil-A is one of America’s toughest franc...,https://nypost.com/2026/09/13/business/chick-f...
2,2026-09-14-02-40-06 +0000,bbc,Amazon pauses work with cargo firm after fatal...,https://www.bbc.co.uk/news/articles/cx2zg554w9...
3,2026-09-14-02-14-34 +0000,nyt,The Bari Weiss Era of ‘60 Minutes’ Begins,https://www.nytimes.com/2026/09/13/business/me...
4,2026-09-14-02-12-03 +0000,nypost,Pol behind the GOP’s ‘common sense vs. communi...,https://nypost.com/2026/09/13/us-news/pol-behi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2268/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
344  trump     32
110     ai     17
84     new     12
527     he     10
347  irish      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
82,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...,94
84,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...,93
78,2026-09-13-20-25-00 +0000,wsj,President Trump made a surprise trade announce...,https://www.wsj.com/economy/trade/trump-pledge...,89
141,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...,89
105,2026-09-13-18-13-12 +0000,chitri,President Donald Trump downplays the need to c...,https://www.chicagotribune.com/2026/09/13/trum...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
82,94,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...
66,70,2026-09-13-21-30-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
141,57,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...
110,45,2026-09-13-17-41-22 +0000,chitri,President Donald Trump calls on Ukraine to hal...,https://www.chicagotribune.com/2026/09/13/trum...
101,38,2026-09-13-18-22-50 +0000,nypost,New York Times’ Gaza war coverage was clearly ...,https://nypost.com/2026/09/13/media/ny-times-g...
84,32,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...
29,29,2026-09-14-00-00-43 +0000,nypost,California high school football coach arrested...,https://nypost.com/2026/09/13/us-news/californ...
166,29,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...
216,29,2026-09-13-04-24-20 +0000,nypost,Ohio Dem Amy Acton’s handlers lash out when ca...,https://nypost.com/2026/09/13/us-news/ohio-gub...
168,28,2026-09-13-10-36-25 +0000,wapo,"Six dead, over 100 missing after Indonesian pa...",https://www.washingtonpost.com/world/2026/09/1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)