## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-01-17-52-09 +0000,nyt,"Israeli Raid in Gaza Kills 4, Palestinian Offi...",https://www.nytimes.com/2026/09/01/world/middl...
1,2026-09-01-17-52-05 +0000,wapo,Bessent downplays bond market concerns amid gl...,https://www.washingtonpost.com/business/2026/0...
2,2026-09-01-17-49-00 +0000,wsj,Opinion | Josh Shapiro Shows Democrats How to Win,https://www.wsj.com/opinion/josh-shapiro-shows...
3,2026-09-01-17-47-46 +0000,wapo,"College student steps into traffic, is killed ...",https://www.washingtonpost.com/immigration/202...
4,2026-09-01-17-44-29 +0000,eltecolote,Mission Muralists Push to Make Restoration a P...,https://eltecolote.org/content/en/mission-mura...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2327/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
181       trump     40
60          new     23
66         iran     23
98   california     18
550      murder     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
297,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...,114
380,2026-08-31-20-30-24 +0000,chitri,President Trump has asked Apple to change Lake...,https://www.chicagotribune.com/2026/08/31/trum...,110
332,2026-08-31-22-23-00 +0000,wsj,Army Secretary Dan Driscoll has submitted his ...,https://www.wsj.com/politics/national-security...,109
267,2026-09-01-02-00-00 +0000,wsj,Trump administration officials are escalating ...,https://www.wsj.com/politics/policy/trump-admi...,108
378,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
297,114,2026-09-01-00-00-00 +0000,wsj,"A Brazilian billionaire shareholder in JBS, th...",https://www.wsj.com/politics/policy/how-a-braz...
55,86,2026-09-01-16-28-00 +0000,wsj,Heard on the Street: The war-driven rise in oi...,https://www.wsj.com/opinion/oil-prices-push-gl...
330,70,2026-08-31-22-28-38 +0000,nypost,California midterms will decide fate of contro...,https://nypost.com/2026/08/31/us-news/californ...
264,65,2026-09-01-02-30-45 +0000,bbc,What it was like inside court for Tupac Shakur...,https://www.bbc.co.uk/news/videos/cz6zp2pwzx5o...
309,63,2026-08-31-23-33-00 +0000,wsj,Vice President JD Vance attacked Abdul El-Saye...,https://www.wsj.com/politics/elections/vance-t...
76,61,2026-09-01-15-54-13 +0000,chitri,Iran’s president says Iran would return to cea...,https://www.chicagotribune.com/2026/09/01/iran...
380,57,2026-08-31-20-30-24 +0000,chitri,President Trump has asked Apple to change Lake...,https://www.chicagotribune.com/2026/08/31/trum...
378,54,2026-08-31-20-32-45 +0000,chitri,Supreme Court lets White House continue constr...,https://www.chicagotribune.com/2026/08/31/supr...
150,53,2026-09-01-12-04-13 +0000,chitri,Rescuers comb through mud and debris as Nepal-...,https://www.chicagotribune.com/2026/09/01/nepa...
1,50,2026-09-01-17-52-05 +0000,wapo,Bessent downplays bond market concerns amid gl...,https://www.washingtonpost.com/business/2026/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)