## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-11-01-08-33 +0000,nyt,Hawaii Governor Asks Trump for Help as State C...,https://www.nytimes.com/2026/09/10/us/hurrican...
1,2026-09-11-01-07-01 +0000,nyt,Fears of a Democratic Wave Push Texas to Cente...,https://www.nytimes.com/live/2026/09/10/us/tru...
2,2026-09-11-01-06-44 +0000,wapo,See photos from the Republican midterm convention,https://www.washingtonpost.com/politics/intera...
3,2026-09-11-01-01-18 +0000,bbc,Coach crash kills several people in Swiss Alps,https://www.bbc.co.uk/news/articles/cx2z70xr0y...
4,2026-09-11-01-00-00 +0000,wsj,"After years of inaction, Congress is suddenly ...",https://www.wsj.com/politics/policy/congress-i...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2603/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
3         trump     68
259         new     24
31           ai     21
15   convention     21
101         gop     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
418,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...,181
262,2026-09-10-16-04-45 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...,175
141,2026-09-10-20-26-00 +0000,wsj,President Trump offered a pricey promise in hi...,https://www.wsj.com/politics/policy/5-000-chec...,147
411,2026-09-10-04-16-36 +0000,wapo,"Trump makes case for Iran war, promises $5,000...",https://www.washingtonpost.com/politics/2026/0...,135
21,2026-09-10-23-56-25 +0000,nyt,"Inside the Republican Midterm Convention, Wher...",https://www.nytimes.com/2026/09/10/us/politics...,134

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
418,181,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...
4,91,2026-09-11-01-00-00 +0000,wsj,"After years of inaction, Congress is suddenly ...",https://www.wsj.com/politics/policy/congress-i...
243,73,2026-09-10-16-52-51 +0000,wapo,New Mexico leaders ask Apple and Google not to...,https://www.washingtonpost.com/politics/2026/0...
440,67,2026-09-10-01-23-43 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
295,67,2026-09-10-14-00-00 +0000,wsj,Home sales in August fell to their lowest leve...,https://www.wsj.com/economy/housing/home-sales...
432,64,2026-09-10-01-54-25 +0000,nyt,"“We gave you no tax on tips, no tax on overtim...",https://www.nytimes.com/live/2026/09/09/us/rnc...
58,58,2026-09-10-22-29-06 +0000,nypost,"Beloved Long Island grandmother, 62, was kille...",https://nypost.com/2026/09/10/us-news/beloved-...
81,54,2026-09-10-21-34-00 +0000,wsj,"Trump’s promise of $5,000 checks faces hurdles...",https://www.wsj.com/politics/policy/a-trillion...
133,46,2026-09-10-20-39-51 +0000,nypost,JD Vance pays tribute to friend Charlie Kirk —...,https://nypost.com/2026/09/10/us-news/jd-vance...
67,46,2026-09-10-22-00-00 +0000,wsj,Cryptocurrency billionaire Fred Ehrsam has eme...,https://www.wsj.com/business/energy-oil/the-re...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)