## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-20-58-00 +0000,wsj,Opinion | TERA Puts an Indian Tribe in Charge ...,https://www.wsj.com/opinion/tera-puts-an-india...
1,2026-08-21-20-56-19 +0000,bbc,One killed in sword attack at Swedish school,https://www.bbc.co.uk/news/articles/c3r0g7gj2n...
2,2026-08-21-20-55-34 +0000,wapo,Supreme Court says Trump can continue ballroom...,https://www.washingtonpost.com/politics/2026/0...
3,2026-08-21-20-55-00 +0000,wsj,"Rubén Rocha, the embattled governor of Mexico’...",https://www.wsj.com/world/americas/mexican-gov...
4,2026-08-21-20-55-00 +0000,wsj,Mexican Governor Indicted by U.S. Vows Return ...,https://www.wsj.com/world/americas/mexican-gov...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14        trump     47
231        iran     13
369  california     13
407         new     12
166          up     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,104
167,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...,104
149,2026-08-21-14-41-39 +0000,nyt,Iran Must Plan to Overcome U.S. Sanctions Afte...,https://www.nytimes.com/2026/08/21/world/middl...,96
69,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,96
322,2026-08-20-23-40-00 +0000,wsj,Michael Cohen interviewed President Trump for ...,https://www.wsj.com/politics/policy/trump-talk...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,104,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...
373,58,2026-08-20-21-07-04 +0000,nypost,Morgan Stanley picks Dallas for expansion outs...,https://nypost.com/2026/08/20/business/morgan-...
167,51,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...
189,48,2026-08-21-11-19-54 +0000,chitri,A question looms over Harry’s return to the UK...,https://www.chicagotribune.com/2026/08/21/harr...
285,46,2026-08-21-02-27-25 +0000,latimes,Dead of a mosquito bite: L.A. records West Nil...,https://www.latimes.com/california/story/2026-...
73,42,2026-08-21-18-30-17 +0000,startribune,Four bodies found near Minneapolis waters in f...,https://www.startribune.com/four-bodies-found-...
322,40,2026-08-20-23-40-00 +0000,wsj,Michael Cohen interviewed President Trump for ...,https://www.wsj.com/politics/policy/trump-talk...
28,38,2026-08-21-20-06-46 +0000,nypost,Eric Swalwell accuser’s rep ‘caught off guard’...,https://nypost.com/2026/08/21/us-news/eric-swa...
148,35,2026-08-21-14-42-00 +0000,wsj,"Greg Mankiw, Thomas Sargent and William White ...",https://www.wsj.com/economy/central-banking/th...
337,35,2026-08-20-22-56-45 +0000,nypost,James Talarico accused of siding with teen kil...,https://nypost.com/2026/08/20/us-news/james-ta...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)