## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-26-13-07-16 +0000,nypost,Melania Trump has stunned reaction as gunfire ...,https://nypost.com/2026/04/26/us-news/melania-...
1,2026-04-26-13-00-00 +0000,missionlocal,Trippy,https://missionlocal.org/2026/04/trippy/
2,2026-04-26-12-58-04 +0000,nypost,Lawler foe championed secret ‘Gender Support’ ...,https://nypost.com/2026/04/26/us-news/mike-law...
3,2026-04-26-12-53-56 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/26/us/tru...
4,2026-04-26-12-52-38 +0000,nyt,Federal authorities swarm the suspect’s home i...,https://www.nytimes.com/live/2026/04/26/us/tru...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

             word  score
1           trump     37
9          dinner     28
8  correspondents     27
7           house     26
6           white     24

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-04-26-05-18-00 +0000,wsj,President Trump is safe after what he describe...,https://www.wsj.com/us-news/trump-evacuated-wh...,201
28,2026-04-26-10-58-40 +0000,nypost,White House Correspondents’ Dinner shooting su...,https://nypost.com/2026/04/26/us-news/white-ho...,196
100,2026-04-26-01-12-57 +0000,latimes,Trump rushed off stage after shooting at White...,https://www.latimes.com/california/story/2026-...,170
102,2026-04-26-00-56-40 +0000,nypost,Chaos at White House Correspondents’ Dinner as...,https://nypost.com/2026/04/25/us-news/shots-fi...,170
12,2026-04-26-12-05-41 +0000,nyt,What We Know About the Shooting at the White H...,https://www.nytimes.com/2026/04/26/us/politics...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,201,2026-04-26-05-18-00 +0000,wsj,President Trump is safe after what he describe...,https://www.wsj.com/us-news/trump-evacuated-wh...
128,51,2026-04-25-21-34-12 +0000,bbc,Trump cancels US envoys' trip to Pakistan for ...,https://www.bbc.com/news/articles/c4g6nyvl29po...
87,33,2026-04-26-03-01-49 +0000,nypost,"Cole Allen, 31-year-old California teacher, ID...",https://nypost.com/2026/04/25/us-news/gunman-a...
165,33,2026-04-25-16-45-12 +0000,nypost,King Charles will be treated to historic milit...,https://nypost.com/2026/04/25/us-news/king-cha...
111,31,2026-04-25-23-26-33 +0000,nypost,Netanyahu calls for IDF to strike Hezbollah ta...,https://nypost.com/2026/04/25/world-news/netan...
102,28,2026-04-26-00-56-40 +0000,nypost,Chaos at White House Correspondents’ Dinner as...,https://nypost.com/2026/04/25/us-news/shots-fi...
112,23,2026-04-25-23-24-57 +0000,nyt,Al Qaeda-Linked Militants Launch Major Attacks...,https://www.nytimes.com/2026/04/25/world/afric...
117,21,2026-04-25-23-01-11 +0000,bbc,BBC visits Chernobyl ghost city 40 years after...,https://www.bbc.com/news/videos/czjwrdgp98wo?a...
61,21,2026-04-26-09-00-00 +0000,wapo,Americans’ electricity was shut off 13 million...,https://www.washingtonpost.com/business/2026/0...
126,21,2026-04-25-21-55-18 +0000,nyt,Families of Iranian Children Killed in School ...,https://www.nytimes.com/2026/04/25/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)