## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-28-23-16-58 +0000,nypost,Shocking moment Amazon delivery driver snatche...,https://nypost.com/2026/05/28/us-news/shocking...
1,2026-05-28-23-16-20 +0000,nyt,Iran War Live Updates: U.S. Officials Say They...,https://www.nytimes.com/live/2026/05/28/world/...
2,2026-05-28-23-13-29 +0000,nypost,Erewhon owes $275K in unpaid rent to LA landlo...,https://nypost.com/2026/05/28/business/erewhon...
3,2026-05-28-23-12-41 +0000,bbc,US and Iran 'very close' to deal but 'not ther...,https://www.bbc.com/news/articles/c87qng40wz9o...
4,2026-05-28-23-09-12 +0000,nypost,Emily Moreno reveals Max Miller’s alleged ‘apo...,https://nypost.com/2026/05/28/us-news/emily-mo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
253   trump     32
12     iran     29
92      new     23
149  israel     14
34     deal     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-05-28-21-04-00 +0000,wsj,The Trump administration has been holding talk...,https://www.wsj.com/politics/policy/putting-tr...,110
119,2026-05-28-20-07-00 +0000,wsj,"Reports of an Iran deal boost markets, new-car...",https://www.wsj.com/business/autos/iran-deal-r...,98
40,2026-05-28-22-07-49 +0000,nypost,Bessent rejects ‘doomer view’ of Iran war fall...,https://nypost.com/2026/05/28/us-news/bessent-...,96
355,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,92
276,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,110,2026-05-28-21-04-00 +0000,wsj,The Trump administration has been holding talk...,https://www.wsj.com/politics/policy/putting-tr...
119,98,2026-05-28-20-07-00 +0000,wsj,"Reports of an Iran deal boost markets, new-car...",https://www.wsj.com/business/autos/iran-deal-r...
213,54,2026-05-28-14-56-07 +0000,nypost,Jill Biden wondered if husband Joe had been dr...,https://nypost.com/2026/05/28/us-news/jill-bid...
204,54,2026-05-28-15-34-00 +0000,wsj,Michigan Gov. Gretchen Whitmer said she won’t ...,https://www.wsj.com/politics/elections/michiga...
252,43,2026-05-28-12-39-13 +0000,cbc,"Israel strikes Beirut suburb, at least 14 kill...",https://www.cbc.ca/news/world/lebanon-tyre-att...
137,43,2026-05-28-18-52-41 +0000,latimes,Ex-California National Guard member sold ghost...,https://www.latimes.com/california/story/2026-...
263,41,2026-05-28-11-44-55 +0000,nypost,Iran fires ballistic missile at American base ...,https://nypost.com/2026/05/28/world-news/iran-...
226,39,2026-05-28-14-01-45 +0000,cbc,A strong Canada 'will help make America great ...,https://www.cbc.ca/news/politics/carney-new-yo...
276,38,2026-05-28-10-47-00 +0000,wsj,Sen. John Cornyn of Texas becomes a member of ...,https://www.wsj.com/politics/elections/the-yol...
160,36,2026-05-28-17-15-44 +0000,nypost,LA mayoral candidate Spencer Pratt’s epic put ...,https://nypost.com/2026/05/28/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)