## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-17-16-54-03 +0000,nypost,1 person shot in the chest inside NYC subway s...,https://nypost.com/2026/10/17/us-news/1-person...
1,2026-10-17-16-52-47 +0000,nyt,Uncertainty Over Pope’s Health Fuels Familiar ...,https://www.nytimes.com/2026/10/17/world/europ...
2,2026-10-17-16-46-14 +0000,nyt,Yemen Fighting Rages as Civilian Toll From Hou...,https://www.nytimes.com/2026/10/17/world/middl...
3,2026-10-17-16-33-36 +0000,nyt,Ilhan Omar’s Sister’s Phone Was Seized Before ...,https://www.nytimes.com/2026/10/16/us/politics...
4,2026-10-17-16-24-44 +0000,nypost,Obese bulldog who weighed same as baby hippo s...,https://nypost.com/2026/10/17/world-news/engli...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2397/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
103   trump     37
154     new     21
65   school     18
335   white     14
78       he     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
136,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,143
17,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...,119
118,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...,114
201,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...,110
49,2026-10-17-13-26-10 +0000,nypost,Katie Zacharia shares Instagram post praising ...,https://nypost.com/2026/10/17/us-news/katie-za...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
136,143,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
118,68,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...
142,59,2026-10-17-01-12-39 +0000,nyt,Teacher Killed in Oregon School Shooting Was W...,https://www.nytimes.com/2026/10/16/us/bend-sch...
126,47,2026-10-17-02-10-04 +0000,nypost,"Pope Leo XIV calls Putin, urges cease-fire as ...",https://nypost.com/2026/10/16/world-news/pope-...
210,41,2026-10-16-20-35-28 +0000,nypost,AI stock sell-off ramps up over debt-fueled da...,https://nypost.com/2026/10/16/business/ai-stoc...
105,34,2026-10-17-07-45-17 +0000,nypost,UK ambulance staff viewed medical records of e...,https://nypost.com/2026/10/17/world-news/willi...
255,33,2026-10-16-18-16-00 +0000,wsj,Elon Musk is putting a small fortune into Repu...,https://www.wsj.com/politics/elections/elon-mu...
6,32,2026-10-17-16-24-19 +0000,nypost,Woman found naked on Martha’s Vineyard road sa...,https://nypost.com/2026/10/17/us-news/boston-s...
58,32,2026-10-17-12-46-51 +0000,cbc,"Hundreds arrested, tear gas deployed in chaoti...",https://www.cbc.ca/news/world/livestory/france...
107,31,2026-10-17-06-29-36 +0000,nypost,Ilhan Omar’s sister skips book tour event amid...,https://nypost.com/2026/10/17/us-news/ilhan-om...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)