## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-20-23-10-20 +0000,nypost,Frightening incident at San Diego mosque one m...,https://nypost.com/2026/06/20/us-news/san-dieg...
1,2026-06-20-23-07-46 +0000,nypost,UK Prime Minister Keir Starmer set to resign a...,https://nypost.com/2026/06/20/world-news/uk-pr...
2,2026-06-20-23-05-39 +0000,nypost,Guests charged back into Dominican resort inf...,https://nypost.com/2026/06/20/world-news/guest...
3,2026-06-20-23-04-29 +0000,nypost,Boaters go ballistic after Coast Guard closes ...,https://nypost.com/2026/06/20/us-news/boaters-...
4,2026-06-20-23-00-15 +0000,nypost,Manhunt underway for Kansas City suspect of ma...,https://nypost.com/2026/06/20/us-news/manhunt-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
46   world     13
218  trump     12
221    new      9
119     up      8
47     cup      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...,51
103,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...,48
4,2026-06-20-23-00-15 +0000,nypost,Manhunt underway for Kansas City suspect of ma...,https://nypost.com/2026/06/20/us-news/manhunt-...,42
41,2026-06-20-19-39-58 +0000,nypost,Son of FDNY hero killed on 9/11 carries World ...,https://nypost.com/2026/06/20/us-news/son-of-f...,41
58,2026-06-20-17-52-20 +0000,nypost,World Cup brings temporary peace to violence-r...,https://nypost.com/2026/06/20/world-news/mexic...,38

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,51,2026-06-20-22-11-17 +0000,nypost,Brazil football boss allegedly uses federation...,https://nypost.com/2026/06/20/world-news/brazi...
103,40,2026-06-20-13-11-15 +0000,nypost,Trump doubles down attacks on Italian PM Giorg...,https://nypost.com/2026/06/20/us-news/trump-do...
8,36,2026-06-20-22-34-00 +0000,wsj,"Vance Heads to Peace Talks, After Iran Says It...",https://www.wsj.com/world/middle-east/fighting...
70,32,2026-06-20-16-56-31 +0000,nypost,Ukraine blasts one of Siberia’s largest oil re...,https://nypost.com/2026/06/20/world-news/ukrai...
46,29,2026-06-20-18-48-51 +0000,nypost,State of emergency declared in LA as warehouse...,https://nypost.com/2026/06/20/us-news/state-of...
38,28,2026-06-20-19-42-09 +0000,nypost,"New documentary honors paralyzed, late NYPD he...",https://nypost.com/2026/06/20/us-news/new-docu...
166,23,2026-06-20-00-53-46 +0000,latimes,Here's why the Lincoln Memorial Reflecting Poo...,https://www.latimes.com/environment/story/2026...
31,22,2026-06-20-20-18-32 +0000,nypost,"Conflict erupts in Lebanon between Israel, Hez...",https://nypost.com/2026/06/20/world-news/confl...
41,22,2026-06-20-19-39-58 +0000,nypost,Son of FDNY hero killed on 9/11 carries World ...,https://nypost.com/2026/06/20/us-news/son-of-f...
159,21,2026-06-20-01-05-29 +0000,nypost,Gavin Newsom ‘preparing’ to release long-delay...,https://nypost.com/2026/06/19/us-news/gavin-ne...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)