## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-19-17-17 +0000,nyt,"Wave of Ukrainian Strikes Kills at Least 4, Ru...",https://www.nytimes.com/2026/05/17/world/europ...
1,2026-05-17-19-13-59 +0000,nypost,Former Dodger Scott Erickson says he stepped o...,https://nypost.com/2026/05/17/us-news/former-d...
2,2026-05-17-19-00-00 +0000,wsj,House Democratic leader Hakeem Jeffries has be...,https://www.wsj.com/politics/elections/the-tru...
3,2026-05-17-18-58-35 +0000,nypost,Wildly popular NYC venue announces closure ami...,https://nypost.com/2026/05/17/us-news/brooklyn...
4,2026-05-17-18-55-36 +0000,nyt,What to Know About Letlow And Fleming in the L...,https://www.nytimes.com/2026/05/17/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2625/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
27       trump     31
26   president     10
132        out     10
85       world      9
164     strike      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
132,2026-05-17-02-56-27 +0000,nypost,Republican Sen. Bill Cassidy — who voted to co...,https://nypost.com/2026/05/16/us-news/la-repub...,95
62,2026-05-17-15-53-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,94
114,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...,86
126,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...,82
2,2026-05-17-19-00-00 +0000,wsj,House Democratic leader Hakeem Jeffries has be...,https://www.wsj.com/politics/elections/the-tru...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
132,95,2026-05-17-02-56-27 +0000,nypost,Republican Sen. Bill Cassidy — who voted to co...,https://nypost.com/2026/05/16/us-news/la-repub...
15,48,2026-05-17-18-20-28 +0000,nypost,Spencer Pratt says he’ll move family out of Lo...,https://nypost.com/2026/05/17/us-news/spencer-...
126,41,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...
75,38,2026-05-17-14-02-27 +0000,cbc,U.A.E. reports drone strike at nuclear power p...,https://www.cbc.ca/news/world/uae-drone-strike...
37,36,2026-05-17-17-26-51 +0000,nypost,World’s best divers in race against time to re...,https://nypost.com/2026/05/17/world-news/world...
5,28,2026-05-17-18-49-38 +0000,nypost,San Francisco DA Brooke Jenkins warns ‘devasta...,https://nypost.com/2026/05/17/us-news/sf-da-br...
74,28,2026-05-17-14-18-23 +0000,bbc,Large-scale Ukrainian drone attack kills three...,https://www.bbc.com/news/articles/c5ye480kxpmo...
55,26,2026-05-17-16-01-00 +0000,wsj,Authorities play catch-up with suspicious wage...,https://www.wsj.com/politics/policy/washington...
62,26,2026-05-17-15-53-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
52,25,2026-05-17-16-07-16 +0000,nypost,Video shows Swatch psychos stampede Long Islan...,https://nypost.com/2026/05/17/us-news/watch-ps...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)