## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-19-17-15 +0000,nypost,Meta rolls out new AI model in ‘fundamental sh...,https://nypost.com/2026/04/09/business/meta-ro...
1,2026-04-09-19-13-36 +0000,bbc,Melania Trump says rumours linking her to Epst...,https://www.bbc.com/news/articles/c3ex07l1qvpo...
2,2026-04-09-19-12-55 +0000,nyt,Michigan Man Is Arrested in Disappearance of W...,https://www.nytimes.com/2026/04/09/world/ameri...
3,2026-04-09-19-12-37 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
4,2026-04-09-19-12-36 +0000,nypost,Fight brewing as controversial bill to let Cal...,https://nypost.com/2026/04/09/us-news/bill-to-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2643/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
25   iran     63
14  trump     37
99   fire     35
98  cease     31
26    war     30

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
287,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...,215
191,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,201
98,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...,200
284,2026-04-09-01-51-08 +0000,nyt,Trump Finds Himself With Fragile Iran Cease-Fi...,https://www.nytimes.com/2026/04/08/us/politics...,185
355,2026-04-08-20-32-22 +0000,nyt,"For Trump, Resuming Combat in Iran Would Be Ri...",https://www.nytimes.com/2026/04/08/us/politics...,182

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
287,215,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...
3,97,2026-04-09-19-12-37 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
0,54,2026-04-09-19-17-15 +0000,nypost,Meta rolls out new AI model in ‘fundamental sh...,https://nypost.com/2026/04/09/business/meta-ro...
154,50,2026-04-09-13-58-43 +0000,bbc,Ships remain cautious approaching Strait of Ho...,https://www.bbc.com/news/articles/c3w39lg84w2o...
29,37,2026-04-09-18-34-14 +0000,nypost,Megyn Kelly rips ‘nutcase’ Jennifer Siebel New...,https://nypost.com/2026/04/09/media/megyn-kell...
39,36,2026-04-09-18-15-05 +0000,nypost,Missing boater Lynette Hooker was arrested aft...,https://nypost.com/2026/04/09/us-news/missing-...
77,36,2026-04-09-17-04-50 +0000,bbc,OpenAI pauses UK data centre deal over energy ...,https://www.bbc.com/news/articles/clyd032ej70o...
344,35,2026-04-08-21-22-00 +0000,wsj,The cease-fire between the U.S. and Iran offer...,https://www.wsj.com/economy/central-banking/fe...
276,35,2026-04-09-02-35-55 +0000,bbc,"Jim Whittaker, first American to Mount Everest...",https://www.bbc.com/news/articles/cx24n2v1v7wo...
156,34,2026-04-09-13-54-13 +0000,cbc,K-pop supergroup BTS kick off world tour in So...,https://www.cbc.ca/news/entertainment/bts-worl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)