## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-23-18-46 +0000,nypost,Illegal alleged to have stabbed a two week yea...,https://nypost.com/2026/06/01/us-news/illegal-...
1,2026-06-01-23-13-57 +0000,nyt,Trump Backs Off Plan for $1.8 Billion Fund Tha...,https://www.nytimes.com/2026/06/01/us/politics...
2,2026-06-01-23-12-00 +0000,wsj,Trump Pushes to End Lebanon Conflict in Hope o...,https://www.wsj.com/world/middle-east/u-s-stri...
3,2026-06-01-23-10-12 +0000,nyt,Hegseth Strikes Female and Black Navy Officers...,https://www.nytimes.com/2026/06/01/us/politics...
4,2026-06-01-23-09-24 +0000,nyt,Crested Ibises Get the Royal Treatment in Japa...,https://www.nytimes.com/2026/06/01/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
11      trump     25
27       iran     21
140       new     16
50         ai     15
48   election     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
219,2026-06-01-14-00-11 +0000,nypost,Trump claims ‘I really don’t care’ if ‘very bo...,https://nypost.com/2026/06/01/world-news/iran-...,90
39,2026-06-01-21-54-49 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...,83
25,2026-06-01-22-23-16 +0000,nyt,Iran War Live Updates: Israel and Iran Step Ba...,https://www.nytimes.com/live/2026/06/01/world/...,71
28,2026-06-01-22-17-37 +0000,cbc,Trump administration will pause controversial ...,https://www.cbc.ca/news/world/anti-weaponizati...,70
266,2026-06-01-09-27-47 +0000,cbc,Trump says talks with Iran continuing at 'rapi...,https://www.cbc.ca/news/world/iran-u-s-war-kuw...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
219,90,2026-06-01-14-00-11 +0000,nypost,Trump claims ‘I really don’t care’ if ‘very bo...,https://nypost.com/2026/06/01/world-news/iran-...
295,66,2026-06-01-02-00-00 +0000,wsj,California Democrats head to a primary electio...,https://www.wsj.com/politics/elections/how-cal...
39,58,2026-06-01-21-54-49 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...
244,57,2026-06-01-11-02-00 +0000,wsj,"If Democrats want to win the Senate, they like...",https://www.wsj.com/politics/graham-platner-sc...
183,51,2026-06-01-16-34-49 +0000,latimes,"AI company Anthropic files to list shares, hea...",https://www.latimes.com/business/story/2026-06...
100,44,2026-06-01-20-34-11 +0000,nypost,NJ congressional candidate Adam Hamawy ‘lied’ ...,https://nypost.com/2026/06/01/world-news/nj-co...
110,36,2026-06-01-19-49-13 +0000,nypost,‘Entourage’ creator records blistering video b...,https://nypost.com/2026/06/01/us-news/entourag...
59,34,2026-06-01-21-29-56 +0000,nypost,Inside the well-stocked anti-ICE coalition ten...,https://nypost.com/2026/06/01/us-news/inside-t...
147,34,2026-06-01-18-21-01 +0000,nypost,Oil prices jump after US and Iran exchange str...,https://nypost.com/2026/06/01/business/oil-pri...
250,32,2026-06-01-10-35-20 +0000,nypost,Jill Biden takes swipe at Kamala Harris’ claim...,https://nypost.com/2026/06/01/us-news/jill-bid...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)