## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-14-17-19 +0000,nypost,"Far-left, ‘Squad’-backed Dems crash and burn i...",https://nypost.com/2026/03/18/us-news/far-left...
1,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...
2,2026-03-18-14-14-20 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/18/us/ill...
3,2026-03-18-14-14-00 +0000,wsj,"Eurozone, U.K. Government Bond Yields Rise as ...",https://www.wsj.com/finance/jgb-futures-edge-h...
4,2026-03-18-14-13-26 +0000,nypost,Chilling surveillance shows stranger slashing ...,https://nypost.com/2026/03/18/us-news/chilling...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2597/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
17      iran     56
9      trump     43
18       war     32
7   illinois     22
43    israel     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
5,2026-03-18-14-12-51 +0000,nyt,Iran War Live Updates: Israel Says It Killed I...,https://www.nytimes.com/live/2026/03/18/world/...,197
246,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,187
80,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,175
197,2026-03-18-02-12-16 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,170
1,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
5,197,2026-03-18-14-12-51 +0000,nyt,Iran War Live Updates: Israel Says It Killed I...,https://www.nytimes.com/live/2026/03/18/world/...
222,116,2026-03-18-01-00-00 +0000,wsj,"The resignation of Joe Kent, the Trump adminis...",https://www.wsj.com/politics/national-security...
193,102,2026-03-18-02-44-31 +0000,nypost,Lt. Gov. Juliana Stratton wins Illinois Senate...,https://nypost.com/2026/03/17/us-news/juliana-...
366,58,2026-03-17-17-14-03 +0000,nypost,Iranian influencer celebrates death of of lead...,https://nypost.com/2026/03/17/world-news/celeb...
107,57,2026-03-18-10-00-00 +0000,nypost,"Trump will ‘rebalance’ media, FCC boss Brendan...",https://nypost.com/2026/03/18/us-news/fcc-boss...
363,55,2026-03-17-17-31-07 +0000,nypost,Dem challenger in Texas House race starred in ...,https://nypost.com/2026/03/17/us-news/dem-chal...
211,53,2026-03-18-01-23-03 +0000,nypost,GOP senator pitches plan to slash California’s...,https://nypost.com/2026/03/17/us-news/gop-sena...
169,47,2026-03-18-05-27-39 +0000,nypost,Comedy club owner with terminal cancer guns do...,https://nypost.com/2026/03/18/us-news/alaska-c...
393,45,2026-03-17-15-38-13 +0000,wapo,Trump has choked off Cuba’s oil supply. China ...,https://www.washingtonpost.com/world/2026/02/2...
371,36,2026-03-17-17-00-00 +0000,missionlocal,All Star Cafe shines amid Market St. skyscrape...,https://missionlocal.org/2026/03/all-star-cafe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)