## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-14-54-39 +0000,bbc,PM proposes NHS style social care system,https://www.bbc.co.uk/news/videos/cvlyldk7zek1...
1,2026-09-27-14-50-16 +0000,nyt,5 Men Arrested on Suspicion of Terrorism Offen...,https://www.nytimes.com/2026/09/27/world/europ...
2,2026-09-27-14-42-43 +0000,chitri,Pope Leo blasts assisted dying as ‘false compa...,https://www.chicagotribune.com/2026/09/27/pope...
3,2026-09-27-14-38-29 +0000,chitri,UK police arrest 5 men near an air base used b...,https://www.chicagotribune.com/2026/09/27/uk-p...
4,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
40     trump     27
148      new     13
39       war     10
36      iran      9
41   rejects      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...,74
104,2026-09-27-00-52-12 +0000,nypost,Trump’s new superintelligence czar: Here’s who...,https://nypost.com/2026/09/26/us-news/trumps-n...,74
132,2026-09-26-21-02-42 +0000,nyt,Trump Rejects Iran’s Cease-Fire Proposal to Re...,https://www.nytimes.com/2026/09/26/us/politics...,67
165,2026-09-26-16-01-28 +0000,chitri,President Trump rejects Iran’s proposal to reo...,https://www.chicagotribune.com/2026/09/26/trum...,62
7,2026-09-27-14-12-58 +0000,nyt,Iran Seeks U.S. Clarification After Trump Reje...,https://www.nytimes.com/2026/09/27/world/middl...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,74,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...
18,58,2026-09-27-12-34-26 +0000,bbc,One dead as nor'easter storm pummels New York ...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
3,45,2026-09-27-14-38-29 +0000,chitri,UK police arrest 5 men near an air base used b...,https://www.chicagotribune.com/2026/09/27/uk-p...
77,35,2026-09-27-06-47-34 +0000,nypost,"27 killed, dozens wounded in horror mass shoot...",https://nypost.com/2026/09/27/world-news/south...
6,33,2026-09-27-14-16-04 +0000,cbc,OpenAI pauses training of latest models after ...,https://www.cbc.ca/news/business/openai-pause-...
170,30,2026-09-26-15-45-00 +0000,wsj,"How Jordan Campbell, a Texas business litigato...",https://www.wsj.com/politics/policy/how-a-busi...
135,29,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
154,27,2026-09-26-17-45-31 +0000,nypost,Ukraine airdrops killer robots behind enemy li...,https://nypost.com/2026/09/26/world-news/ukrai...
178,26,2026-09-26-15-05-32 +0000,nypost,China beating US in race for top AI talent as ...,https://nypost.com/2026/09/26/world-news/china...
23,25,2026-09-27-11-25-00 +0000,wsj,A scandal inside the Philadelphia DA’s office ...,https://www.wsj.com/politics/policy/vance-puts...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)