## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-15-55-59 +0000,nypost,SpaceX shares begin trading in biggest IPO eve...,https://nypost.com/2026/06/12/business/spacex-...
1,2026-06-12-15-50-11 +0000,nyt,"SpaceX’s IPO Could Turn 4,400 Employees Into M...",https://www.nytimes.com/2026/06/10/technology/...
2,2026-06-12-15-49-16 +0000,nyt,Iran War Live Updates: Conflicting Accounts Em...,https://www.nytimes.com/live/2026/06/12/world/...
3,2026-06-12-15-45-28 +0000,cbc,Ex-South Korean president sentenced for sendin...,https://www.cbc.ca/news/world/south-korea-yoon...
4,2026-06-12-15-34-34 +0000,nypost,Dark reality of SoCal town where 5 teens kille...,https://nypost.com/2026/06/12/us-news/dark-rea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
225   trump     37
217   world     29
13     iran     29
0    spacex     23
218     cup     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-06-12-08-09-37 +0000,bbc,Tehran says 'nothing' finalised after Trump cl...,https://www.bbc.com/news/articles/c78y6w78828o...,121
58,2026-06-12-14-08-51 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...,117
120,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...,114
164,2026-06-12-08-37-17 +0000,wapo,Trump says he has canceled plans to strike Ira...,https://www.washingtonpost.com/world/2026/06/1...,113
295,2026-06-11-20-51-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/policy/showdown-b...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,121,2026-06-12-08-09-37 +0000,bbc,Tehran says 'nothing' finalised after Trump cl...,https://www.bbc.com/news/articles/c78y6w78828o...
86,90,2026-06-12-12-52-55 +0000,bbc,Elon Musk's SpaceX raises $75bn ahead of world...,https://www.bbc.com/news/articles/cwy034q89j4o...
120,77,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...
248,64,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
231,61,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...
129,52,2026-06-12-10-00-00 +0000,latimes,House Democrats ask new ICE director to roll b...,https://www.latimes.com/politics/story/2026-06...
216,49,2026-06-12-01-00-00 +0000,wsj,When Trump meets his counterparts at next week...,https://www.wsj.com/economy/global/the-global-...
111,45,2026-06-12-11-00-00 +0000,nypost,Texas Dem bragged about getting career crimina...,https://nypost.com/2026/06/12/us-news/texas-de...
3,41,2026-06-12-15-45-28 +0000,cbc,Ex-South Korean president sentenced for sendin...,https://www.cbc.ca/news/world/south-korea-yoon...
257,37,2026-06-11-22-18-46 +0000,nypost,Bombshell evidence White House fraud squad fou...,https://nypost.com/2026/06/11/us-news/bombshel...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)