## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-10-36-44 +0000,nyt,Diesel Crisis Puts Poor Farmers Around the Wor...,https://www.nytimes.com/2026/07/23/business/ba...
1,2026-07-23-10-30-51 +0000,bbc,Why are UK fuel prices rising again?,https://www.bbc.co.uk/news/articles/c20zgjzz0e...
2,2026-07-23-10-23-50 +0000,wapo,Oil prices leap after attacks in Red Sea,https://www.washingtonpost.com/world/2026/07/2...
3,2026-07-23-10-22-51 +0000,nyt,Global Oil Price Nears $100 a Barrel as Confli...,https://www.nytimes.com/2026/07/23/business/ir...
4,2026-07-23-10-21-49 +0000,nyt,A New Target for Ukraine’s Long-Range Attacks:...,https://www.nytimes.com/2026/07/23/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2634/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
86     trump     44
23       new     32
222     deal     26
21      iran     22
211  nuclear     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
375,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,131
208,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,120
84,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,119
244,2026-07-22-20-36-21 +0000,chitri,House Republicans adopt $95 billion package fo...,https://www.chicagotribune.com/2026/07/22/hous...,114
170,2026-07-22-23-05-44 +0000,nyt,"With Saudi Deal, Trump Loosens Nuclear Standar...",https://www.nytimes.com/2026/07/22/us/politics...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
375,131,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
355,102,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
59,72,2026-07-23-08-25-56 +0000,nyt,House Passes Defense Bill Amid Iran War Divide,https://www.nytimes.com/2026/07/22/us/politics...
66,65,2026-07-23-08-10-32 +0000,wsj,Stock Market Today: Oil Prices Jump After Hout...,https://www.wsj.com/livecoverage/stock-market-...
131,58,2026-07-23-02-00-00 +0000,wsj,Canada’s Mark Carney has tried the carrot and ...,https://www.wsj.com/world/americas/carney-has-...
120,53,2026-07-23-03-03-54 +0000,nypost,Twisted four-word message accused teen killer ...,https://nypost.com/2026/07/22/us-news/californ...
158,53,2026-07-22-23-55-25 +0000,latimes,D4vd's garage had signs of blood where girl's ...,https://www.latimes.com/california/story/2026-...
396,48,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
297,48,2026-07-22-18-26-49 +0000,nyt,"Daniel Siad, Model Scout Who Connected Women t...",https://www.nytimes.com/2026/07/22/world/europ...
205,46,2026-07-22-21-40-19 +0000,chitri,Adolf Hitler’s birthplace in Austria reopens a...,https://www.chicagotribune.com/2026/07/22/adol...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)