## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-01-21-52-12 +0000,nyt,"In the final months of his term, Tennessee’s g...",https://www.nytimes.com/live/2026/10/01/us/chr...
1,2026-10-01-21-52-03 +0000,nyt,Judge in Lindsay Clancy’s Case Declines to Fin...,https://www.nytimes.com/2026/10/01/us/lindsay-...
2,2026-10-01-21-51-04 +0000,missionlocal,Richmond Buzz: October means all the sausages ...,https://missionlocal.org/2026/10/richmond-buzz...
3,2026-10-01-21-50-02 +0000,48hills,Yekutiel under pressure to drop out of D8 race...,https://48hills.org/2026/10/yekutiel-under-pre...
4,2026-10-01-21-49-38 +0000,nypost,White House releases behind-the-scenes photos ...,https://nypost.com/2026/10/01/us-news/white-ho...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2349/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
69         trump     58
72          your     48
1770       guide     47
376   california     44
124     flydubai     30

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
361,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,207
367,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,207
396,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,207
358,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,206
359,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,206

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
361,207,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...
19,146,2026-10-01-21-36-00 +0000,wsj,Mortgage rates posted their largest increase i...,https://www.wsj.com/politics/policy/mortgage-r...
329,130,2026-10-01-11-19-09 +0000,chitri,Most Americans blame Donald Trump for high pri...,https://www.chicagotribune.com/2026/10/01/dona...
343,94,2026-10-01-10-17-37 +0000,cbc,Tennessee governor orders outside review after...,https://www.cbc.ca/news/world/christa-pike-fai...
390,70,2026-10-01-10-00-00 +0000,latimes,Your guide to L.A. City Charter Amendment EE: ...,https://www.latimes.com/california/story/2026-...
29,67,2026-10-01-21-25-00 +0000,wsj,Fed Vice Chair Philip Jefferson said officials...,https://www.wsj.com/economy/central-banking/an...
153,63,2026-10-01-18-38-35 +0000,nypost,Trump sends third aircraft carrier to Middle E...,https://nypost.com/2026/10/01/us-news/trump-se...
218,61,2026-10-01-16-30-00 +0000,wsj,"The WSJ mapped 24,000 TikTok creators with a n...",https://www.wsj.com/politics/elections/we-used...
23,58,2026-10-01-21-33-41 +0000,nypost,Woman missing in horror helicopter crash off C...,https://nypost.com/2026/10/01/us-news/avalon-w...
278,53,2026-10-01-14-00-00 +0000,wsj,Hedge-fund managers are losing their main stra...,https://www.wsj.com/politics/policy/hedge-fund...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)