## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-30-13-49-34 +0000,nyt,Police Investigate Former Prince Andrew and Ep...,https://www.nytimes.com/2026/10/30/world/europ...
1,2026-10-30-13-49-00 +0000,nypost,Vivek Ramaswamy pulls controversial attack ad ...,https://nypost.com/2026/10/30/us-news/vivek-ra...
2,2026-10-30-13-48-00 +0000,wsj,U.S. Natural Gas Futures Fall in Early Trading,https://www.wsj.com/finance/commodities-future...
3,2026-10-30-13-47-15 +0000,nyt,Why Cancer Is a Major Issue in Iowa’s Heated R...,https://www.nytimes.com/2026/10/30/us/iowa-gov...
4,2026-10-30-13-47-00 +0000,wsj,Eurozone Economy Slows as French Debt Worries ...,https://www.wsj.com/economy/french-economy-shr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2651/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
135       trump     34
78     election     31
119         new     25
89   california     19
57           up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
229,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...,143
331,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...,104
68,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,95
262,2026-10-29-22-51-00 +0000,chitri,President Trump lends support for Darline Grah...,https://www.chicagotribune.com/2026/10/29/trum...,95
126,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
229,143,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home-hea...",https://www.wsj.com/politics/elections/how-ala...
68,95,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...
272,72,2026-10-29-22-20-53 +0000,nypost,Starbucks CEO Brian Niccol reveals new ideas t...,https://nypost.com/2026/10/29/business/stabuck...
407,50,2026-10-29-16-26-00 +0000,wsj,U.S. economic growth picked up steam in the th...,https://www.wsj.com/economy/us-gdp-report-q3-2...
20,48,2026-10-30-13-13-52 +0000,nypost,HELOC vs. home equity loans: Which should you ...,https://nypost.com/business/heloc-vs-home-equi...
265,48,2026-10-29-22-31-20 +0000,nypost,Florida first-responder couple survives Spain ...,https://nypost.com/2026/10/29/world-news/coupl...
83,47,2026-10-30-11-28-25 +0000,nypost,North Korean hackers steal $6.3B from Binance ...,https://nypost.com/2026/10/30/business/north-k...
331,47,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...
129,45,2026-10-30-10-00-00 +0000,nypost,Here’s when top Wall Street executives expect ...,https://nypost.com/2026/10/30/business/heres-w...
376,39,2026-10-29-18-05-52 +0000,cbc,Netanyahu's party amplifies unproven claims th...,https://www.cbc.ca/news/world/israel-election-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)