## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-00-06-00 +0000,wsj,Oil Falls Amid Hopes for Reopening of Strait o...,https://www.wsj.com/finance/commodities-future...
1,2026-08-27-00-02-00 +0000,wsj,HP Revenue Rises as Higher Prices Offset Fewer...,https://www.wsj.com/business/earnings/hp-reven...
2,2026-08-26-23-56-29 +0000,nypost,Gavin Newsom claims he ‘didn’t even know’ abou...,https://nypost.com/2026/08/26/us-news/gavin-ne...
3,2026-08-26-23-55-41 +0000,wapo,"Canada, pressured by Trump, wants new trade pa...",https://www.washingtonpost.com/world/2026/08/2...
4,2026-08-26-23-51-00 +0000,nypost,Moment California cop is shot during gun battl...,https://nypost.com/2026/08/26/us-news/san-jose...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2738/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
27        trump     41
29        trade     20
157       dolly     19
158      parton     19
34   california     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
103,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,137
380,2026-08-26-03-02-19 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,130
389,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...,128
376,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...,117
150,2026-08-26-19-08-11 +0000,cbc,Trump's trade war: Fact-checking Canada's natu...,https://www.cbc.ca/news/world/trade-war-natura...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
103,137,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
40,91,2026-08-26-22-49-35 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
376,76,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...
35,75,2026-08-26-23-00-47 +0000,nypost,Let her fly! Petition to rename Nashville airp...,https://nypost.com/2026/08/26/us-news/petition...
340,66,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...
46,63,2026-08-26-22-35-03 +0000,nypost,"9/11 mastermind KSM will finally stand trial, ...",https://nypost.com/2026/08/26/us-news/9-11-mas...
197,57,2026-08-26-16-37-47 +0000,latimes,"California, other states sue again to block ne...",https://www.latimes.com/politics/story/2026-08...
57,54,2026-08-26-22-10-00 +0000,wsj,The surprise visit by the director of the Cent...,https://www.wsj.com/politics/policy/cia-chiefs...
117,53,2026-08-26-20-22-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
282,52,2026-08-26-12-37-13 +0000,nypost,47 Americans among hundreds missing after dead...,https://nypost.com/2026/08/26/world-news/flood...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)