## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-24-16-51-41 +0000,nypost,Alaska Democrat Mary Peltola accused of shovin...,https://nypost.com/2026/09/24/us-news/alaska-d...
1,2026-09-24-16-50-47 +0000,nyt,A Food Lover’s Tour of Toronto,https://www.nytimes.com/2026/09/18/travel/toro...
2,2026-09-24-16-50-00 +0000,wsj,Brent Climbs Above $107 After Houthi Attack Ag...,https://www.wsj.com/finance/commodities-future...
3,2026-09-24-16-49-22 +0000,nyt,The ‘Monster’ Behind Russia’s Global Effort to...,https://www.nytimes.com/2026/09/24/business/ru...
4,2026-09-24-16-49-00 +0000,wsj,What Is the White House Press Pool?,https://www.wsj.com/business/media/what-is-the...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2283/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
46   trump     84
112    new     34
43      xi     28
48   china     19
40   house     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-09-24-16-48-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...,216
126,2026-09-24-13-03-42 +0000,latimes,"CNN, MS NOW and Politico still shut out of Whi...",https://www.latimes.com/entertainment-arts/bus...,193
168,2026-09-24-10-59-00 +0000,wsj,As President Trump and China’s Xi Jinping prep...,https://www.wsj.com/politics/policy/as-trump-a...,184
331,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,183
17,2026-09-24-16-39-05 +0000,startribune,"CNN, MS NOW and Politico back at the White Hou...",https://www.startribune.com/judge-orders-white...,182

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,216,2026-09-24-16-48-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...
49,100,2026-09-24-16-10-06 +0000,nyt,5 Takeaways From a New Poll on the New Hampshi...,https://www.nytimes.com/2026/09/24/us/politics...
281,96,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...
284,77,2026-09-24-00-43-00 +0000,wsj,The last time Venezuelan leader Delcy Rodrígue...,https://www.wsj.com/world/americas/u-n-visit-s...
278,69,2026-09-24-01-00-00 +0000,wsj,"The AI build-out is making history, dwarfing t...",https://www.wsj.com/economy/the-ai-build-out-i...
154,68,2026-09-24-11-11-58 +0000,nypost,Grandma allegedly euthanized against her will ...,https://nypost.com/2026/09/24/world-news/grand...
149,54,2026-09-24-11-36-59 +0000,nypost,Eight sailors in USS Abraham Lincoln strike gr...,https://nypost.com/2026/09/24/us-news/eight-sa...
20,52,2026-09-24-16-36-50 +0000,nyt,Mortgage Rates Hit 7% as Iran War Fallout Crus...,https://www.nytimes.com/2026/09/24/business/mo...
375,47,2026-09-23-20-45-00 +0000,wsj,Canada’s Carney Open to U.S. Trade Deal but Wo...,https://www.wsj.com/world/europe/canadas-carne...
40,39,2026-09-24-16-17-34 +0000,nypost,Glamorous NYC designer’s family launches tip l...,https://nypost.com/2026/09/24/us-news/nyc-desi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)