## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-03-14-22-16 +0000,bbc,Police criticise timing of decision on pubs st...,https://www.bbc.co.uk/news/articles/cd95v388k5...
1,2026-07-03-14-18-52 +0000,nypost,"Boy, 13, rushed to hospital after shark attack...",https://nypost.com/2026/07/03/us-news/boy-atta...
2,2026-07-03-14-18-29 +0000,nypost,Trump roasts other presidents during children’...,https://nypost.com/2026/07/03/us-news/trump-ro...
3,2026-07-03-14-18-08 +0000,nypost,Street closures for Taylor Swift’s wedding add...,https://nypost.com/2026/07/03/us-news/street-c...
4,2026-07-03-14-17-40 +0000,bbc,Dangerous heatwave scorches US as Fourth of Ju...,https://www.bbc.co.uk/news/articles/cevlkzer7v...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
20    trump     34
357     new     14
78      was     12
387  russia     11
441     one     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
159,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...,111
133,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...,84
137,2026-07-03-02-51-34 +0000,nypost,Secret Service member was Googling rooftop loc...,https://nypost.com/2026/07/02/us-news/secret-s...,82
260,2026-07-02-18-34-02 +0000,nypost,"The top 10 most un-American, no-show states at...",https://nypost.com/2026/07/02/us-news/the-top-...,74
231,2026-07-02-20-08-00 +0000,wsj,"What to know about ‘Trump Accounts,’ the new s...",https://www.wsj.com/personal-finance/trump-acc...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
159,111,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...
318,66,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
49,59,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
133,50,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
157,46,2026-07-03-00-04-16 +0000,nypost,Costco announces all California stores to shut...,https://nypost.com/2026/07/02/business/costco-...
30,45,2026-07-03-13-12-52 +0000,bbc,Ukrainian suspect hunted by police after Monac...,https://www.bbc.co.uk/news/articles/c4gy603z2q...
281,43,2026-07-02-17-02-54 +0000,cbc,Alberta pitches new West Coast oil pipeline to...,https://www.cbc.ca/news/canada/livestory/energ...
312,42,2026-07-02-14-57-25 +0000,nypost,Man charged with murdering Thai teen sent dist...,https://nypost.com/2026/07/02/world-news/man-c...
3,40,2026-07-03-14-18-08 +0000,nypost,Street closures for Taylor Swift’s wedding add...,https://nypost.com/2026/07/03/us-news/street-c...
249,35,2026-07-02-19-17-09 +0000,nypost,Grieving Ukrainian mom crouches over dead son ...,https://nypost.com/2026/07/02/world-news/gut-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)