## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-01-17-42 +0000,nyt,"In His Resignation Letter, Joe Kent Spoke Abou...",https://www.nytimes.com/2026/03/17/us/politics...
1,2026-03-18-01-17-40 +0000,nyt,An Unexploded Bomb Near the Colombia-Ecuador B...,https://www.nytimes.com/2026/03/17/world/ameri...
2,2026-03-18-01-13-00 +0000,wsj,Brent Oil Price Likely to Stay Elevated Around...,https://www.wsj.com/finance/commodities-future...
3,2026-03-18-01-09-52 +0000,nypost,Trump doesn’t endorse candidate in heated GOP ...,https://nypost.com/2026/03/17/us-news/trump-do...
4,2026-03-18-01-09-05 +0000,nyt,Iran War Live Updates: Iran Confirms Israeli S...,https://www.nytimes.com/live/2026/03/17/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
27   trump     56
43    iran     53
44     war     31
51     top     21
71  israel     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
151,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...,263
55,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,217
270,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,209
4,2026-03-18-01-09-05 +0000,nyt,Iran War Live Updates: Iran Confirms Israeli S...,https://www.nytimes.com/live/2026/03/17/world/...,200
99,2026-03-17-21-48-08 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,195

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
151,263,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...
73,67,2026-03-17-22-49-03 +0000,bbc,Iranian security chief Ali Larijani killed in ...,https://www.bbc.com/news/articles/c24deezq6meo...
138,65,2026-03-17-20-43-35 +0000,nypost,Senate GOP moves on Save America Act — the lik...,https://nypost.com/2026/03/17/us-news/senate-g...
362,58,2026-03-17-08-07-54 +0000,wsj,"Stock Market News, March 17, 2026: Dow Jumps, ...",https://www.wsj.com/livecoverage/stock-market-...
303,57,2026-03-17-12-30-06 +0000,nyt,"AIPAC, the Pro-Israel Group, Becomes a Major I...",https://www.nytimes.com/2026/03/17/us/election...
144,48,2026-03-17-20-22-51 +0000,startribune,"Walz pitches child care tax credit, new social...",https://www.startribune.com/walz-pitches-child...
229,47,2026-03-17-16-11-15 +0000,nypost,Trump’s fiery response to NATO allies over Str...,https://nypost.com/2026/03/17/us-news/trump-sl...
189,44,2026-03-17-18-34-27 +0000,nyt,Trump Administration Seeks to Remove Cuba’s Pr...,https://www.nytimes.com/2026/03/16/world/ameri...
172,44,2026-03-17-19-14-20 +0000,nyt,"Flight Prices Are Up Amid Soaring Fuel Costs, ...",https://www.nytimes.com/2026/03/17/business/ai...
208,39,2026-03-17-17-31-07 +0000,nypost,Dem challenger in Texas House race starred in ...,https://nypost.com/2026/03/17/us-news/dem-chal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)