## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-07-22-49-00 +0000,wsj,Opinion | Celebrating Hamas on Oct. 7,https://www.wsj.com/opinion/oct-7-zohran-mamda...
1,2026-10-07-22-48-06 +0000,nypost,Ex-Marine Nigel Edge facing death penalty for ...,https://nypost.com/2026/10/07/us-news/ex-marin...
2,2026-10-07-22-48-00 +0000,wsj,Levi Strauss Uses Tariff Refunds to Rekindle C...,https://www.wsj.com/business/earnings/levi-str...
3,2026-10-07-22-45-58 +0000,nyt,Delta Passenger Steals and Crashes Airport Tug...,https://www.nytimes.com/2026/10/07/us/delta-pa...
4,2026-10-07-22-45-44 +0000,nypost,Civil war breaks out over 11 acres of stunning...,https://nypost.com/2026/10/07/us-news/townhome...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2613/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
132    trump     42
96       new     17
196       up     17
2        oct     15
120  christa     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
172,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...,121
71,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...,112
42,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...,107
79,2026-10-07-20-50-19 +0000,nypost,Trump tamps down speculation Russia plague lab...,https://nypost.com/2026/10/07/us-news/trump-ta...,98
83,2026-10-07-20-47-00 +0000,wsj,Democrats and anti-Trump Republicans are anxio...,https://www.wsj.com/politics/policy/lawmakers-...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
172,121,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...
42,107,2026-10-07-21-46-00 +0000,wsj,Bipartisan lawmakers want their colleagues to ...,https://www.wsj.com/politics/policy/bipartisan...
18,72,2026-10-07-22-24-15 +0000,nyt,"Christa Pike, Confused After Failed Tennessee ...",https://www.nytimes.com/2026/10/07/us/christa-...
71,70,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
38,61,2026-10-07-21-48-13 +0000,nypost,"Anti-Israel protests break out across NYC, wit...",https://nypost.com/2026/10/07/us-news/anti-isr...
421,51,2026-10-06-23-04-37 +0000,nypost,Russia accused of covering up plague outbreak ...,https://nypost.com/2026/10/06/world-news/russi...
313,51,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...
196,49,2026-10-07-16-37-26 +0000,latimes,A new Pixar film and the sequel to 'Michael' w...,https://www.latimes.com/entertainment-arts/bus...
32,46,2026-10-07-22-00-00 +0000,wsj,The Trump administration resurrected its globa...,https://www.wsj.com/economy/trade/trumps-tarif...
93,43,2026-10-07-20-29-00 +0000,wsj,"In a speech framed by ancient Greek ruins, Sec...",https://www.wsj.com/politics/policy/rubio-turn...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)