## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-28-01-16-00 +0000,wsj,"Court Hands Argentina’s Milei a Victory, Rejec...",https://www.wsj.com/world/americas/court-hands...
1,2026-03-28-01-14-05 +0000,startribune,Live: Gophers need huge fourth quarter against...,https://www.startribune.com/gophers-womens-bas...
2,2026-03-28-01-13-37 +0000,nyt,Bank of America Pays $72.5 Million to Settle L...,https://www.nytimes.com/2026/03/27/business/ba...
3,2026-03-28-01-13-28 +0000,nypost,Aubrey Plaza finds a buyer for $5.8M Californi...,https://nypost.com/2026/03/27/us-news/aubrey-p...
4,2026-03-28-01-12-09 +0000,startribune,Live: Top seed Goodhue holds off Albany at Wil...,https://www.startribune.com/minnesota-boys-bas...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
47    iran     43
48     war     36
355  trump     33
379    new     16
121   will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-03-27-16-43-10 +0000,latimes,"Iran war rages on heading into fifth week, as ...",https://www.latimes.com/world-nation/story/202...,120
242,2026-03-27-13-50-03 +0000,nypost,"Dow enters correction territory, oil jumps abo...",https://nypost.com/2026/03/27/business/dow-fal...,120
333,2026-03-27-06-48-56 +0000,nypost,Trump insists MAGA ‘loves’ his war on Iran: ‘M...,https://nypost.com/2026/03/27/us-news/trump-in...,119
66,2026-03-27-22-00-42 +0000,nypost,Trump considers renaming Strait of Hormuz afte...,https://nypost.com/2026/03/27/us-news/trump-co...,118
183,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,120,2026-03-27-16-43-10 +0000,latimes,"Iran war rages on heading into fifth week, as ...",https://www.latimes.com/world-nation/story/202...
183,80,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...
181,54,2026-03-27-17-00-00 +0000,wsj,About a year into the full-blown trade war bet...,https://www.wsj.com/economy/trade/how-trumps-t...
347,52,2026-03-27-03-33-00 +0000,wsj,President Trump said he would sign an executiv...,https://www.wsj.com/politics/policy/republican...
322,48,2026-03-27-08-00-00 +0000,cbc,"At historic low point, New Democrats descend o...",https://www.cbc.ca/news/politics/ndp-leadershi...
57,44,2026-03-27-22-17-07 +0000,nypost,Tiger Woods’ troubling history with prescripti...,https://nypost.com/2026/03/27/us-news/tiger-wo...
143,43,2026-03-27-18-33-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
346,42,2026-03-27-03-56-42 +0000,nyt,Rubio Says Allies Should Help Secure Strait by...,https://www.nytimes.com/2026/03/26/world/middl...
41,42,2026-03-27-23-13-00 +0000,wsj,California Gov. Gavin Newsom signed an executi...,https://www.wsj.com/politics/policy/newsom-ban...
217,40,2026-03-27-15-18-40 +0000,nypost,Austria plans to ban social media use for unde...,https://nypost.com/2026/03/27/world-news/austr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)