## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-26-05-49-11 +0000,nyt,Car Plows Into Crowd at Berlin Pride Event in ...,https://www.nytimes.com/2026/07/25/world/europ...
1,2026-07-26-05-31-48 +0000,nyt,"How Tā Moko, the Māori Tattoo Art, Made A Come...",https://www.nytimes.com/2026/07/25/world/austr...
2,2026-07-26-05-23-13 +0000,missionlocal,Woman hit by unicycle while crossing the Great...,https://missionlocal.org/2026/07/great-highway...
3,2026-07-26-05-09-59 +0000,nyt,U.S.-Iran Strikes Abate as War Enters Latest C...,https://www.nytimes.com/live/2026/07/25/world/...
4,2026-07-26-05-00-56 +0000,bbc,Andy Burnham rules out early election in exclu...,https://www.bbc.co.uk/news/videos/c935kzyq6r4o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2359/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
41    trump     19
23     iran     16
26      war     10
15      new      9
313  senate      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
34,2026-07-26-00-11-49 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,63
115,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...,58
81,2026-07-25-19-40-41 +0000,nypost,Trump pauses Iran strikes as US weighs next mo...,https://nypost.com/2026/07/25/world-news/trump...,57
122,2026-07-25-14-47-25 +0000,nypost,"US-Iran war spreads as Saudi Arabia, Houthis t...",https://nypost.com/2026/07/25/world-news/us-ir...,55
75,2026-07-25-20-14-19 +0000,wapo,Houthis claim attack on Saudi oil refinery as ...,https://www.washingtonpost.com/world/2026/07/2...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
34,63,2026-07-26-00-11-49 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...
115,58,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...
68,39,2026-07-25-21-01-25 +0000,nypost,"Ukraine strikes set fire to ‘Russia’s Amazon,’...",https://nypost.com/2026/07/25/world-news/ukrai...
139,37,2026-07-25-12-30-22 +0000,cbc,Man's death reported in Spain as wildfires als...,https://www.cbc.ca/news/world/wildfire-evacuat...
147,32,2026-07-25-12-00-00 +0000,nypost,How Trump’s presidential pardons became boomin...,https://nypost.com/2026/07/25/us-news/inside-t...
106,30,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...
141,30,2026-07-25-12-18-59 +0000,cbc,Youth protesters celebrate after India's educa...,https://www.cbc.ca/news/world/india-education-...
26,25,2026-07-26-00-49-13 +0000,nypost,Mamdani’s municipal bond mess will only get wo...,https://nypost.com/2026/07/25/business/mamdani...
122,25,2026-07-25-14-47-25 +0000,nypost,"US-Iran war spreads as Saudi Arabia, Houthis t...",https://nypost.com/2026/07/25/world-news/us-ir...
103,24,2026-07-25-16-59-25 +0000,wapo,Democrats pick new Senate candidate in Maine i...,https://www.washingtonpost.com/politics/2026/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)