## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-11-43-29 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/20/world/...
1,2026-07-20-11-38-33 +0000,nypost,‘Long Island Lolita’ Amy Fisher’s troubled son...,https://nypost.com/2026/07/20/us-news/long-isl...
2,2026-07-20-11-37-32 +0000,bbc,Scores feared dead after passenger ferry capsi...,https://www.bbc.co.uk/news/articles/cm2gm99nrm...
3,2026-07-20-11-33-45 +0000,wapo,A U.K. prime minister takes charge with a prom...,https://www.washingtonpost.com/world/2026/07/2...
4,2026-07-20-11-32-23 +0000,48hills,Live Shots: ‘Bohémienne’ glows with the ribald...,https://48hills.org/2026/07/live-shots-bohemie...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
263    world     27
264      cup     25
79      iran     24
193      new     18
58   burnham     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
183,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,109
234,2026-07-19-13-41-14 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/article/tension-looms-...,96
157,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,94
130,2026-07-20-00-44-03 +0000,bbc,"Trump, Bieber and Shakira - a World Cup final ...",https://www.bbc.co.uk/sport/football/articles/...,92
181,2026-07-19-19-25-24 +0000,chitri,Trump celebrates the World Cup as a US victory...,https://www.chicagotribune.com/2026/07/19/trum...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
183,109,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...
127,68,2026-07-20-01-00-00 +0000,wsj,Jordan Becomes New Flashpoint in U.S.-Iran War...,https://www.wsj.com/world/middle-east/jordan-b...
148,59,2026-07-19-23-25-00 +0000,wsj,"Usha Vance gave birth to a baby boy on Sunday,...",https://www.wsj.com/us-news/second-lady-usha-v...
189,47,2026-07-19-18-35-33 +0000,nypost,Chilling video shows Monaco bomb attack that n...,https://nypost.com/2026/07/19/world-news/video...
102,46,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
76,40,2026-07-20-09-00-00 +0000,wsj,Many wealthy Texas Republicans can’t stomach t...,https://www.wsj.com/politics/elections/ken-pax...
103,40,2026-07-20-04-01-05 +0000,nyt,Five of the Main Challenges Awaiting Andy Burn...,https://www.nytimes.com/2026/07/20/world/europ...
135,33,2026-07-20-00-27-18 +0000,nypost,Jubilant Spain fans flock to NYC landmarks to ...,https://nypost.com/2026/07/19/us-news/spain-fa...
52,26,2026-07-20-09-56-00 +0000,wsj,Oil Climbed Above $90 Before Paring Gains as U...,https://www.wsj.com/business/energy-oil/oil-cl...
20,25,2026-07-20-11-00-00 +0000,startribune,Police searched Twin Cities license plate came...,https://www.startribune.com/police-search-immi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)