## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-13-51-38 +0000,nypost,Vigilante teens caught on wild doorbell cam at...,https://nypost.com/2026/06/04/us-news/vigilant...
1,2026-06-04-13-50-21 +0000,nyt,"Marjane Satrapi, the Author of ‘Persepolis,’ D...",https://www.nytimes.com/2026/06/04/world/middl...
2,2026-06-04-13-50-11 +0000,nyt,"Fighting in Somalia’s Capital, Mogadishu: What...",https://www.nytimes.com/2026/06/04/world/afric...
3,2026-06-04-13-49-47 +0000,nyt,Iran War Live Updates: Israel Trades Strikes W...,https://www.nytimes.com/live/2026/06/04/world/...
4,2026-06-04-13-49-07 +0000,nyt,"Colombia’s Yellow World Cup Jersey, Once a Sym...",https://www.nytimes.com/2026/06/04/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
53        trump     48
24         iran     26
32          new     23
25          war     16
546  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
223,2026-06-03-22-07-07 +0000,nypost,House defies Trump and passes war powers resol...,https://nypost.com/2026/06/03/us-news/house-de...,136
229,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,134
210,2026-06-03-22-55-02 +0000,startribune,House approves war powers resolution to halt m...,https://www.startribune.com/house-again-consid...,132
234,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...,128
172,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
223,136,2026-06-03-22-07-07 +0000,nypost,House defies Trump and passes war powers resol...,https://nypost.com/2026/06/03/us-news/house-de...
234,80,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
352,61,2026-06-03-14-48-24 +0000,nypost,CBS News boss Bari Weiss sounds off on Scott P...,https://nypost.com/2026/06/03/media/cbs-news-b...
151,50,2026-06-04-04-54-57 +0000,nypost,"1 dead, 3 hurt at California high school gradu...",https://nypost.com/2026/06/04/us-news/1-dead-3...
279,48,2026-06-03-20-05-58 +0000,bbc,One killed and dozens injured in Iranian drone...,https://www.bbc.com/news/articles/c5yx135yg53o...
8,47,2026-06-04-13-41-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...
179,45,2026-06-04-01-00-00 +0000,wsj,"Amaryllis Fox Kennedy, a former Trump administ...",https://www.wsj.com/politics/national-security...
306,44,2026-06-03-18-07-48 +0000,nypost,Ukraine unleashes massive blitz on Russian oil...,https://nypost.com/2026/06/03/world-news/ukrai...
331,43,2026-06-03-16-34-00 +0000,wsj,Californians wrapped voting in their state’s p...,https://www.wsj.com/politics/elections/polls-c...
52,43,2026-06-04-11-35-57 +0000,nyt,"Israel and Lebanon Renew Cease-Fire, Calling f...",https://www.nytimes.com/2026/06/03/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)