## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-20-17-48-39 +0000,nypost,Video shows massive ‘smokenado’ tower over Ver...,https://nypost.com/2026/05/20/us-news/smokenad...
1,2026-05-20-17-47-08 +0000,nyt,Justice Dept. Charges Former Cuban President i...,https://www.nytimes.com/2026/05/20/us/raul-cas...
2,2026-05-20-17-46-48 +0000,bbc,Are supermarkets profiting from higher food pr...,https://www.bbc.com/news/videos/cd6pwgz21nvo?a...
3,2026-05-20-17-46-38 +0000,nyt,Raúl Castro Has Guided Cuba for Decades,https://www.nytimes.com/2026/05/20/us/politics...
4,2026-05-20-17-46-00 +0000,wsj,Los Angeles Tried to Tax Mansions. Apartment C...,https://www.wsj.com/economy/housing/los-angele...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
94        trump     57
136         new     22
321        iran     20
416     primary     20
385  republican     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
304,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...,240
270,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...,178
271,2026-05-20-02-28-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,167
183,2026-05-20-11-09-00 +0000,wsj,President Trump continued grinding through Rep...,https://www.wsj.com/politics/the-trump-machine...,154
197,2026-05-20-10-39-42 +0000,nypost,Senate advances Iran war powers resolution as ...,https://nypost.com/2026/05/20/us-news/senate-a...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
304,240,2026-05-19-23-59-00 +0000,wsj,Days after President Trump celebrated ousting ...,https://www.wsj.com/politics/policy/senate-adv...
257,99,2026-05-20-04-45-00 +0000,wsj,A Georgia congressman and a former college foo...,https://www.wsj.com/politics/elections/georgia...
270,85,2026-05-20-02-30-00 +0000,wsj,President Trump’s handpicked House candidate d...,https://www.wsj.com/politics/elections/thomas-...
83,76,2026-05-20-16-00-00 +0000,wsj,Two police officers who defended the Capitol d...,https://www.wsj.com/politics/policy/two-jan-6-...
237,64,2026-05-20-08-54-44 +0000,cbc,"Xi calls for end to Middle East hostilities, s...",https://www.cbc.ca/news/world/putin-china-xi-j...
77,63,2026-05-20-16-09-00 +0000,wsj,"James Murdoch to Buy New York Magazine, Other ...",https://www.wsj.com/business/media/vox-media-s...
193,51,2026-05-20-10-48-00 +0000,wsj,EU negotiators reached a provisional deal to r...,https://www.wsj.com/economy/trade/eu-reaches-a...
414,44,2026-05-19-18-03-38 +0000,latimes,Hilton and Becerra lead in a tightening race i...,https://www.latimes.com/california/story/2026-...
140,44,2026-05-20-13-52-32 +0000,nypost,WHO says risk of Ebola outbreak spreading glob...,https://nypost.com/2026/05/20/world-news/who-s...
6,44,2026-05-20-17-45-18 +0000,nypost,"Ex-Cuba leader Raul Castro, 94, charged with m...",https://nypost.com/2026/05/20/us-news/ex-cuba-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)