## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-02-11-53-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
1,2026-10-02-11-52-04 +0000,bbc,Who is the 'hero' Indian pilot who was stabbed...,https://www.bbc.co.uk/news/articles/cje3r3z7g0...
2,2026-10-02-11-50-00 +0000,nyt,Airlines Set to Bring Israelis Back From U.A.E...,https://www.nytimes.com/2026/10/02/world/middl...
3,2026-10-02-11-48-10 +0000,nyt,The Latest Challenge to Data Centers? Restive ...,https://www.nytimes.com/2026/10/02/business/de...
4,2026-10-02-11-48-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2399/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
74      trump     52
16   flydubai     29
107       new     19
12     flight     16
18     attack     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
244,2026-10-01-21-36-00 +0000,wsj,Mortgage rates posted their largest increase i...,https://www.wsj.com/politics/policy/mortgage-r...,137
66,2026-10-02-09-58-00 +0000,wsj,Police score big bucks with little work in Tru...,https://www.wsj.com/politics/policy/democratic...,132
161,2026-10-02-01-46-23 +0000,chitri,President Trump says Iran will be hit ‘very ha...,https://www.chicagotribune.com/2026/10/01/trum...,126
82,2026-10-02-09-08-06 +0000,bbc,'I was not going to let others die' - pilot of...,https://www.bbc.co.uk/news/articles/c639m98gde...,120
119,2026-10-02-07-28-29 +0000,nypost,Trump says Iran will be hit ‘very hard’ if it ...,https://nypost.com/2026/10/02/world-news/trump...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
244,137,2026-10-01-21-36-00 +0000,wsj,Mortgage rates posted their largest increase i...,https://www.wsj.com/politics/policy/mortgage-r...
333,116,2026-10-01-18-38-35 +0000,nypost,Trump sends third aircraft carrier to Middle E...,https://nypost.com/2026/10/01/us-news/trump-se...
387,87,2026-10-01-16-30-00 +0000,wsj,"The WSJ mapped 24,000 TikTok creators with a n...",https://www.wsj.com/politics/elections/we-used...
21,85,2026-10-02-11-14-32 +0000,nypost,Christa Pike laughed and sang during botched e...,https://nypost.com/2026/10/02/us-news/christa-...
76,68,2026-10-02-09-30-00 +0000,wsj,Heard on the Street: High government debt is a...,https://www.wsj.com/finance/investing/high-gov...
81,67,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...
186,63,2026-10-01-23-42-00 +0000,wsj,Fed Vice Chair Philip Jefferson said officials...,https://www.wsj.com/economy/central-banking/an...
157,57,2026-10-02-02-13-46 +0000,nypost,California mayor accused of running booze-soak...,https://nypost.com/2026/10/01/us-news/anaheim-...
335,51,2026-10-01-18-36-00 +0000,wsj,The top Democrats on the Senate and House fore...,https://www.wsj.com/politics/policy/lawmakers-...
161,50,2026-10-02-01-46-23 +0000,chitri,President Trump says Iran will be hit ‘very ha...,https://www.chicagotribune.com/2026/10/01/trum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)