## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-17-00-11-16 +0000,nyt,Wildfire Smokes Makes Air Hazardous for Millio...,https://www.nytimes.com/2026/07/16/us/wildfire...
1,2026-07-17-00-07-03 +0000,nyt,Iran War Live Updates: U.S. Launches New Strik...,https://www.nytimes.com/live/2026/07/16/world/...
2,2026-07-17-00-02-30 +0000,nypost,"Disney World guest, 54, died on iconic ride af...",https://nypost.com/2026/07/16/us-news/disney-w...
3,2026-07-17-00-00-35 +0000,nypost,Eric Swalwell drops another $50K on celebrity ...,https://nypost.com/2026/07/16/us-news/eric-swa...
4,2026-07-17-00-00-00 +0000,wsj,A Monster Pile of Airline Points Is Supercharg...,https://www.wsj.com/business/airlines/airline-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2611/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
128  trump     37
9     iran     30
14     new     23
10     war     21
368   will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
272,2026-07-16-13-20-24 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...,118
268,2026-07-16-13-46-46 +0000,nypost,Kai Trump pinpoints personality trait she got ...,https://nypost.com/2026/07/16/us-news/kai-trum...,115
235,2026-07-16-15-52-31 +0000,nyt,Maker of Drone Boats Used in Iran War Will Ope...,https://www.nytimes.com/2026/07/16/business/ma...,112
1,2026-07-17-00-07-03 +0000,nyt,Iran War Live Updates: U.S. Launches New Strik...,https://www.nytimes.com/live/2026/07/16/world/...,111
135,2026-07-16-19-57-10 +0000,nypost,Chevron weighs new Iraqi oil pipeline to avoid...,https://nypost.com/2026/07/16/business/chevron...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
272,118,2026-07-16-13-20-24 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...
30,84,2026-07-16-22-55-00 +0000,wsj,The Treasury’s top tax policy official was for...,https://www.wsj.com/politics/policy/top-treasu...
79,69,2026-07-16-21-44-24 +0000,bbc,Burnham to promise new path for UK when he bec...,https://www.bbc.co.uk/news/articles/c2lq12z1xd...
46,59,2026-07-16-22-37-38 +0000,nypost,Zelensky fires defense minister credited with ...,https://nypost.com/2026/07/16/world-news/zelen...
246,55,2026-07-16-15-02-00 +0000,wsj,The Trump administration will limit how long a...,https://www.wsj.com/politics/policy/trump-admi...
311,48,2026-07-16-10-45-00 +0000,wsj,There have been a lot of developments in the p...,https://www.wsj.com/politics/policy/what-to-kn...
134,48,2026-07-16-19-58-55 +0000,bbc,Hundreds of Canada wildfires prompt US air qua...,https://www.bbc.co.uk/news/articles/c0m7n427xd...
348,41,2026-07-16-08-34-51 +0000,wsj,Stock Market Today: Nasdaq Slips as Chip Stock...,https://www.wsj.com/livecoverage/stock-market-...
364,41,2026-07-16-05-24-49 +0000,nyt,India Is Moving Fast to Build A.I. Data Center...,https://www.nytimes.com/2026/07/16/world/asia/...
118,40,2026-07-16-20-43-59 +0000,nypost,FIFA sued for ‘deceptive’ World Cup ticket sal...,https://nypost.com/2026/07/16/business/fifa-su...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)