## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-18-07-59 +0000,nypost,Navy yanks promo photo of sailor wearing cheek...,https://nypost.com/2026/04/09/us-news/navy-yan...
1,2026-04-09-18-06-57 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
2,2026-04-09-18-06-47 +0000,nypost,‘Manosphere’ streamer Sneako says his offensiv...,https://nypost.com/2026/04/09/us-news/sneako-s...
3,2026-04-09-18-05-00 +0000,wsj,Sazerac Eyes Deal With Jack Daniel’s Maker Bro...,https://www.wsj.com/business/sazerac-eyes-deal...
4,2026-04-09-18-04-54 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/09/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
11   iran     75
23   fire     39
94  trump     36
22  cease     35
12    war     32

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-09-18-06-57 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...,238
268,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...,234
67,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...,223
168,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,216
353,2026-04-08-20-03-41 +0000,nyt,"Even as They Praise Iran Cease-Fire, World Lea...",https://www.nytimes.com/2026/04/08/world/europ...,210

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,238,2026-04-09-18-06-57 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
268,85,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...
129,56,2026-04-09-13-58-43 +0000,bbc,Ships remain cautious approaching Strait of Ho...,https://www.bbc.com/news/articles/c3w39lg84w2o...
370,46,2026-04-08-19-14-54 +0000,nypost,Woke Gavin Newsom ‘green’ jet fuel plan could ...,https://nypost.com/2026/04/08/lifestyle/gavin-...
282,40,2026-04-08-23-37-00 +0000,wsj,A federal appeals court has denied Anthropic’s...,https://www.wsj.com/politics/national-security...
253,40,2026-04-09-02-55-05 +0000,nypost,Former top Biden aide urges Va. Gov. Abigail S...,https://nypost.com/2026/04/08/us-news/former-t...
131,37,2026-04-09-13-54-13 +0000,cbc,K-pop supergroup BTS kick off world tour in So...,https://www.cbc.ca/news/entertainment/bts-worl...
72,36,2026-04-09-16-25-41 +0000,nypost,Insane moment cops deploy Batman-like gadget d...,https://nypost.com/2026/04/09/us-news/cops-dep...
43,35,2026-04-09-17-04-50 +0000,bbc,OpenAI pauses UK data centre deal over energy ...,https://www.bbc.com/news/articles/clyd032ej70o...
325,35,2026-04-08-21-22-00 +0000,wsj,The cease-fire between the U.S. and Iran offer...,https://www.wsj.com/economy/central-banking/fe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)