## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-16-14-49-21 +0000,nypost,Global corgis gather for cutest costume contes...,https://nypost.com/2026/08/16/lifestyle/annual...
1,2026-08-16-14-45-19 +0000,nypost,Ex-Sen. Kyrsten Sinema details repeated sex wi...,https://nypost.com/2026/08/16/us-news/ex-sen-k...
2,2026-08-16-14-44-44 +0000,nyt,Canadian Petition to Expel U.S. Ambassador Pet...,https://www.nytimes.com/2026/08/15/world/canad...
3,2026-08-16-14-40-05 +0000,nyt,Art Heist: 4 Antonello da Messina Paintings St...,https://www.nytimes.com/2026/08/16/world/europ...
4,2026-08-16-14-30-00 +0000,cbc,Conservative Leader Pierre Poilievre holds new...,https://www.cbc.ca/player/play/9.7309020?cmp=rss

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2406/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
103  trump     11
169    new      9
105   iran      8
113    her      7
150    war      6

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
56,2026-08-16-09-31-10 +0000,nyt,"As Iran War Turns Into Economic Battle, a New ...",https://www.nytimes.com/2026/08/16/world/middl...,35
31,2026-08-16-12-00-11 +0000,nypost,"At least one killed, four wounded in Hartford ...",https://nypost.com/2026/08/16/us-news/at-least...,34
88,2026-08-16-04-33-06 +0000,nypost,Hurricane Lala leaves thousands without power ...,https://nypost.com/2026/08/16/us-news/hurrican...,33
96,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...,32
58,2026-08-16-09-30-00 +0000,wsj,Two Guys Are Eating Their Way Around the World...,https://www.wsj.com/arts-culture/food-cooking/...,31

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
56,35,2026-08-16-09-31-10 +0000,nyt,"As Iran War Turns Into Economic Battle, a New ...",https://www.nytimes.com/2026/08/16/world/middl...
31,34,2026-08-16-12-00-11 +0000,nypost,"At least one killed, four wounded in Hartford ...",https://nypost.com/2026/08/16/us-news/at-least...
88,33,2026-08-16-04-33-06 +0000,nypost,Hurricane Lala leaves thousands without power ...,https://nypost.com/2026/08/16/us-news/hurrican...
96,32,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...
139,31,2026-08-15-19-39-00 +0000,wsj,Trump Family’s World Liberty Financial Gets Pr...,https://www.wsj.com/finance/trump-familys-worl...
167,27,2026-08-15-16-19-42 +0000,nypost,UK PM Andy Burnham urges ‘reflection’ after ex...,https://nypost.com/2026/08/15/world-news/uk-pr...
95,25,2026-08-16-02-08-10 +0000,nypost,Gun-toting granny chases off shoplifting suspe...,https://nypost.com/2026/08/15/us-news/based-gr...
133,25,2026-08-15-20-08-06 +0000,nypost,Acting Navy secretary salutes USS Abraham Linc...,https://nypost.com/2026/08/15/us-news/dire-rep...
147,22,2026-08-15-18-52-26 +0000,nypost,Wisconsin Dem calls out party for abandoning r...,https://nypost.com/2026/08/15/us-news/dem-cand...
104,21,2026-08-16-00-44-05 +0000,nypost,California AG’s block of Paramount-Warner Bros...,https://nypost.com/2026/08/15/business/califor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)