## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-20-31-16 +0000,nypost,Evil torturer learns his fate for heinous kill...,https://nypost.com/2026/06/30/us-news/evil-tor...
1,2026-06-30-20-30-38 +0000,nypost,Megyn Kelly torches Coney-Barrett for dissent ...,https://nypost.com/2026/06/30/us-news/megyn-ke...
2,2026-06-30-20-30-18 +0000,nyt,Court Halts Pentagon Rule Requiring Escorts fo...,https://www.nytimes.com/2026/06/30/business/me...
3,2026-06-30-20-25-53 +0000,bbc,Firefighters struggle to contain deadly Greek ...,https://www.bbc.co.uk/news/articles/c0qy3nkex0...
4,2026-06-30-20-24-25 +0000,nypost,Texas mom’s bloody last stand revealed before ...,https://nypost.com/2026/06/30/us-news/texas-mo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
23         court     39
132      supreme     35
134        trump     27
189          new     20
138  citizenship     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
348,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...,143
110,2026-06-30-17-15-04 +0000,startribune,"Supreme Court upholds birthright citizenship, ...",https://www.startribune.com/supreme-court-upho...,141
176,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,140
97,2026-06-30-18-01-22 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,139
182,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
348,143,2026-06-29-21-33-00 +0000,wsj,The Supreme Court blocks Trump’s firing of Lis...,https://www.wsj.com/politics/policy/supreme-co...
307,82,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
54,55,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
67,44,2026-06-30-19-01-48 +0000,nyt,Trump Urges Congress to Take Up Birthright Cit...,https://www.nytimes.com/2026/06/30/us/politics...
9,42,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
203,39,2026-06-30-13-30-09 +0000,nypost,Family of English soccer fan who vanished on w...,https://nypost.com/2026/06/30/world-news/fears...
49,35,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
155,35,2026-06-30-15-53-59 +0000,latimes,Supreme Court rules states may ban trans athle...,https://www.latimes.com/politics/story/2026-06...
7,33,2026-06-30-20-22-00 +0000,wsj,"Stocks rise, the yen slides and a quiet Fed on...",https://www.wsj.com/finance/stocks/stocks-rise...
178,32,2026-06-30-14-43-47 +0000,nypost,Wife of Ukrainian oligarch with ties to Russia...,https://nypost.com/2026/06/30/world-news/wife-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)