## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-04-16-17 +0000,nyt,Israel and Lebanon Agree to Renew Cease-Fire,https://www.nytimes.com/live/2026/06/03/world/...
1,2026-06-04-04-08-37 +0000,nyt,How Does LA Count Election Ballots? It Begins ...,https://www.nytimes.com/2026/06/03/us/election...
2,2026-06-04-04-04-25 +0000,48hills,Under the Stars: Wealthy Women are here to lay...,https://48hills.org/2026/06/under-the-stars-we...
3,2026-06-04-04-01-06 +0000,nyt,"Amid War, Iran’s Soccer Leader Works to Get Hi...",https://www.nytimes.com/2026/06/04/world/middl...
4,2026-06-04-03-54-48 +0000,latimes,Three people reported shot after high school g...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
53        trump     46
23         iran     27
173  california     20
59          new     19
22          war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
95,2026-06-03-22-33-00 +0000,wsj,GOP-led House voted to restrict President Trum...,https://www.wsj.com/politics/gop-led-house-vot...,188
63,2026-06-03-23-46-00 +0000,wsj,"In a 215-208 vote, the House of Representative...",https://www.wsj.com/politics/how-each-member-o...,153
102,2026-06-03-22-07-07 +0000,nypost,House defies Trump and passes war powers resol...,https://nypost.com/2026/06/03/us-news/house-de...,146
88,2026-06-03-22-55-02 +0000,startribune,House approves war powers resolution to halt m...,https://www.startribune.com/house-again-consid...,142
108,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,142

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
95,188,2026-06-03-22-33-00 +0000,wsj,GOP-led House voted to restrict President Trum...,https://www.wsj.com/politics/gop-led-house-vot...
316,82,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
113,77,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
140,72,2026-06-03-20-56-06 +0000,nypost,How CBS News boss Bari Weiss finally reached h...,https://nypost.com/2026/06/03/media/how-cbs-ne...
281,53,2026-06-03-13-04-26 +0000,bbc,He was a reality show villain. Can he be the m...,https://www.bbc.com/news/articles/c775x852rk1o...
218,53,2026-06-03-17-06-25 +0000,cbc,Ukrainian drones hit St. Petersburg oil termin...,https://www.cbc.ca/news/world/ukraine-drones-s...
219,42,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...
336,41,2026-06-03-07-39-32 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
39,39,2026-06-04-01-00-00 +0000,nypost,"California’s revolt: Spencer Pratt, Steve Hilt...",https://nypost.com/2026/06/03/us-news/spencer-...
170,37,2026-06-03-20-05-58 +0000,bbc,One killed and dozens injured in Iranian drone...,https://www.bbc.com/news/articles/c5yx135yg53o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)