## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-20-52-15 +0000,bbc,The ecstasy of buying our first home was short...,https://www.bbc.co.uk/news/articles/c2dyxg0zkp...
1,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
2,2026-09-26-20-26-30 +0000,nypost,Boeing scrambles to fix new 737 MAX software g...,https://nypost.com/2026/09/26/us-news/boeing-s...
3,2026-09-26-20-23-44 +0000,nypost,UN adds over 60 companies to Israel blacklist,https://nypost.com/2026/09/26/world-news/un-ad...
4,2026-09-26-20-18-31 +0000,nypost,Dine-and-dash suspect gets just desserts after...,https://nypost.com/2026/09/26/us-news/dine-and...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
155  trump     46
4      was     13
21     new     12
75      xi     11
171  house     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
149,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...,118
76,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...,117
80,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...,94
148,2026-09-26-02-36-07 +0000,chitri,President Trump said he would campaign in midt...,https://www.chicagotribune.com/2026/09/25/trum...,92
51,2026-09-26-16-01-28 +0000,chitri,President Trump rejects Iran’s proposal to reo...,https://www.chicagotribune.com/2026/09/26/trum...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
149,118,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...
76,60,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
80,48,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...
7,44,2026-09-26-20-09-51 +0000,cbc,"China, U.S. agree to AI dialogue, tariff cuts ...",https://www.cbc.ca/news/world/china-united-sta...
79,41,2026-09-26-14-05-01 +0000,cbc,Hundreds of thousands turn out for Pope Leo al...,https://www.cbc.ca/news/world/pope-leo-parade-...
73,41,2026-09-26-14-24-32 +0000,nypost,Russian attacks kill 4 across Ukraine days aft...,https://nypost.com/2026/09/26/world-news/russi...
47,40,2026-09-26-16-30-10 +0000,nyt,Trump Rejects Iran’s Cease-Fire Proposal to Re...,https://www.nytimes.com/2026/09/26/us/politics...
148,38,2026-09-26-02-36-07 +0000,chitri,President Trump said he would campaign in midt...,https://www.chicagotribune.com/2026/09/25/trum...
207,31,2026-09-25-21-50-00 +0000,wsj,Report Details Security Failures at School Whe...,https://www.wsj.com/us-news/report-details-sec...
169,30,2026-09-26-00-00-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota doesn’...,https://www.wsj.com/politics/ilhan-omar-is-the...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)