## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-05-48-00 +0000,bbc,Iran and Israel say they will pause strikes bu...,https://www.bbc.com/news/articles/cj6ge150z5go...
1,2026-06-09-05-44-59 +0000,bbc,Hundreds of aftershocks jolt Philippines as of...,https://www.bbc.com/news/articles/ckg50pypn2eo...
2,2026-06-09-05-43-48 +0000,nyt,Why a U.K. By-Election in Makerfield Could Top...,https://www.nytimes.com/2026/06/09/world/europ...
3,2026-06-09-05-39-56 +0000,nypost,"Diehard Knicks fans unfazed by Game 3 loss, re...",https://nypost.com/2026/06/09/us-news/diehard-...
4,2026-06-09-05-38-06 +0000,bbc,"Gabriel Raimondo, 18, wins deputy seat in elec...",https://www.bbc.com/news/articles/c8e2l651ywlo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
64     trump     34
0       iran     26
1     israel     20
16  election     14
54        up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-06-09-04-49-07 +0000,nyt,Israel Halts Iran Strikes After Trump Claims P...,https://www.nytimes.com/live/2026/06/08/world/...,104
207,2026-06-08-16-39-22 +0000,nypost,Netanyahu says Israel will ‘hold fire’ on Iran...,https://nypost.com/2026/06/08/us-news/netanyah...,100
267,2026-06-08-11-42-45 +0000,latimes,Trump tells Iran and Israel to stop 'shooting'...,https://www.latimes.com/world-nation/story/202...,90
134,2026-06-08-20-28-25 +0000,nyt,Netanyahu Called Off Iran Strikes After Trump ...,https://www.nytimes.com/2026/06/08/us/politics...,88
24,2026-06-09-02-00-00 +0000,wsj,Trump and his allies are escalating allegation...,https://www.wsj.com/politics/elections/trump-f...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,104,2026-06-09-04-49-07 +0000,nyt,Israel Halts Iran Strikes After Trump Claims P...,https://www.nytimes.com/live/2026/06/08/world/...
29,83,2026-06-09-01-19-28 +0000,bbc,Spencer Pratt out of LA mayor race as left-win...,https://www.bbc.com/news/articles/cx219kxkj1jo...
24,53,2026-06-09-02-00-00 +0000,wsj,Trump and his allies are escalating allegation...,https://www.wsj.com/politics/elections/trump-f...
137,52,2026-06-08-20-16-00 +0000,wsj,A federal judge invalidated the Trump administ...,https://www.wsj.com/politics/policy/judge-stri...
126,46,2026-06-08-20-54-29 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
44,45,2026-06-09-00-16-29 +0000,nypost,Ex-Graham Platner campaign director says embat...,https://nypost.com/2026/06/08/us-news/ex-graha...
258,43,2026-06-08-12-15-14 +0000,nypost,Two dead as private jet crashes in Dominican R...,https://nypost.com/2026/06/08/world-news/priva...
3,42,2026-06-09-05-39-56 +0000,nypost,"Diehard Knicks fans unfazed by Game 3 loss, re...",https://nypost.com/2026/06/09/us-news/diehard-...
164,42,2026-06-08-18-51-59 +0000,nypost,Apple reveals long-delayed Siri AI makeover at...,https://nypost.com/2026/06/08/business/apple-r...
215,40,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)