## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-12-17-51 +0000,nyt,See How Houthis Put the Red Sea at Risk as an ...,https://www.nytimes.com/2026/07/22/business/en...
1,2026-07-22-12-09-20 +0000,nypost,Louisiana Rep. Cleo Fields won’t seek re-elect...,https://nypost.com/2026/07/22/us-news/louisian...
2,2026-07-22-12-08-41 +0000,bbc,Modelling scout linked to Epstein found dead i...,https://www.bbc.co.uk/news/articles/cp8en38vpd...
3,2026-07-22-12-04-50 +0000,nyt,Saudis Reach Deal With U.S. That Could Let The...,https://www.nytimes.com/2026/07/21/us/politics...
4,2026-07-22-12-04-49 +0000,bbc,'Devastated' Millie Bobby Brown leads Kaylee H...,https://www.bbc.co.uk/news/articles/cm2glm5r18...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
63   trump     56
54    iran     33
64     new     21
55     war     19
127   will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
228,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,148
75,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,124
344,2026-07-21-16-22-24 +0000,nypost,Trump warns Iran of much greater destruction i...,https://nypost.com/2026/07/21/us-news/trump-wa...,123
59,2026-07-22-10-15-03 +0000,bbc,US renews strikes on Iran as Trump threatens t...,https://www.bbc.co.uk/news/articles/cdrv0p37k8...,121
177,2026-07-22-00-01-00 +0000,wsj,Defense Secretary Pete Hegseth estimated the l...,https://www.wsj.com/politics/national-security...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
228,148,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
112,120,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...
173,50,2026-07-22-00-29-59 +0000,nypost,Fourth soldier believed to be killed in Iran a...,https://nypost.com/2026/07/21/us-news/fourth-s...
324,46,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
330,43,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
12,41,2026-07-22-11-55-35 +0000,nyt,Expected U.S.-Saudi Nuclear Deal Fuels Israeli...,https://www.nytimes.com/2026/07/22/world/middl...
110,39,2026-07-22-08-02-04 +0000,bbc,India's Modi government under growing pressure...,https://www.bbc.co.uk/news/articles/c9d8p88lyj...
366,37,2026-07-21-15-38-22 +0000,nypost,Spanish soccer star Marc Cucurella shares 16-y...,https://nypost.com/2026/07/21/world-news/spani...
262,37,2026-07-21-20-20-24 +0000,bbc,Ethiopian police arrest alleged leader of mult...,https://www.bbc.co.uk/news/articles/c4gklwpv1w...
251,37,2026-07-21-20-45-37 +0000,cbc,Zelenskyy replaces head of Ukraine's army amid...,https://www.cbc.ca/news/world/zelenskyy-syrsky...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)