## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-16-03-21 +0000,nypost,"Small plane crashes into Phoenix backyard, inj...",https://nypost.com/2026/03/04/us-news/small-pl...
1,2026-03-04-16-02-02 +0000,nypost,House Republicans ask Bill Gates and Leon Blac...,https://nypost.com/2026/03/04/business/house-r...
2,2026-03-04-16-01-14 +0000,nypost,Nebraska AG accuses gaming giant Roblox of bec...,https://nypost.com/2026/03/04/us-news/nebraska...
3,2026-03-04-16-00-00 +0000,wsj,Meet the Companies Vibe Coding Their Own CRMs,https://www.wsj.com/cio-journal/meet-the-compa...
4,2026-03-04-15-58-38 +0000,nyt,Live Updates: Hegseth Says There Will Be No Le...,https://www.nytimes.com/live/2026/03/04/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
43       iran     89
127     trump     45
97        war     35
87      texas     35
205  conflict     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
434,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...,200
177,2026-03-04-09-58-00 +0000,wsj,Spain’s Sanchez Reiterates Opposition to Iran ...,https://www.wsj.com/world/europe/spains-sanche...,199
79,2026-03-04-14-06-31 +0000,nyt,"Spain’s Leader, Rejecting Iran War, Escalates ...",https://www.nytimes.com/2026/03/04/world/europ...,194
369,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,194
82,2026-03-04-13-58-51 +0000,bbc,UK stock market calms but oil prices rise over...,https://www.bbc.com/news/articles/cwy884ekn0jo...,183

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
434,200,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...
10,131,2026-03-04-15-55-00 +0000,wsj,GOP Rep. Dan Crenshaw became the first House i...,https://www.wsj.com/politics/elections/rep-dan...
82,94,2026-03-04-13-58-51 +0000,bbc,UK stock market calms but oil prices rise over...,https://www.bbc.com/news/articles/cwy884ekn0jo...
166,90,2026-03-04-10-11-14 +0000,wapo,4 U.S. soldiers killed in Iran conflict identi...,https://www.washingtonpost.com/world/2026/03/0...
46,81,2026-03-04-15-10-00 +0000,wsj,Incumbent Sen. John Cornyn and Texas Attorney ...,https://www.wsj.com/politics/elections/john-co...
436,66,2026-03-03-17-29-49 +0000,nypost,Some Amazon services in Middle East go offline...,https://nypost.com/2026/03/03/business/amazon-...
178,61,2026-03-04-09-46-35 +0000,nypost,Israel threatens Ayatollah Khamenei’s successo...,https://nypost.com/2026/03/04/world-news/iran-...
22,60,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
228,57,2026-03-04-04-03-33 +0000,nypost,Complaining Rep. Jasmine Crockett leaves own T...,https://nypost.com/2026/03/03/us-news/rep-jasm...
355,54,2026-03-03-21-42-00 +0000,wsj,Minneapolis Fed President Neel Kashkari said t...,https://www.wsj.com/economy/central-banking/ka...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)