## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-02-21-04-00 +0000,nypost,Terrifying doorbell cam captures knife-wieldin...,https://nypost.com/2026/05/02/us-news/ring-cam...
1,2026-05-02-20-55-48 +0000,nyt,"Spirit Airlines Cancels All Flights, Stranding...",https://www.nytimes.com/2026/05/02/business/sp...
2,2026-05-02-20-53-37 +0000,nyt,"Mace, Boebert and Luna Want Congress Members t...",https://www.nytimes.com/2026/05/02/us/politics...
3,2026-05-02-20-52-52 +0000,nyt,Trump’s Vision for D.C. ‘Garden of Heroes’ Sta...,https://www.nytimes.com/2026/05/02/us/politics...
4,2026-05-02-20-51-25 +0000,nypost,Putin declares war on aging with $26 billion v...,https://nypost.com/2026/05/02/world-news/putin...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
28      trump     31
188      iran     20
38        war     16
10     spirit     12
11   airlines     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...,108
153,2026-05-02-01-30-23 +0000,nypost,Trump administration pulling 5K troops out of ...,https://nypost.com/2026/05/01/world-news/trump...,94
59,2026-05-02-16-29-06 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,91
82,2026-05-02-13-40-25 +0000,nypost,"Iran war ‘likely’ to restart, senior Tehran of...",https://nypost.com/2026/05/02/world-news/iran-...,89
193,2026-05-01-22-00-01 +0000,nyt,Trump Tells Congress Why He Doesn’t Need Its A...,https://www.nytimes.com/2026/05/01/us/politics...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,108,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...
95,43,2026-05-02-12-00-00 +0000,wsj,"Despite Iowa’s history of voting Republican, n...",https://www.wsj.com/politics/elections/ruby-re...
47,39,2026-05-02-17-17-16 +0000,nypost,Crowd shrinks as Berkshire Hathaway’s new CEO ...,https://nypost.com/2026/05/02/business/crowd-s...
40,35,2026-05-02-17-48-47 +0000,nypost,Outrage as California vice mayor posts vile ‘d...,https://nypost.com/2026/05/02/us-news/californ...
128,33,2026-05-02-08-58-09 +0000,nypost,US warns shipping firms they could face sancti...,https://nypost.com/2026/05/02/world-news/us-wa...
64,31,2026-05-02-15-54-20 +0000,nypost,Commie-nator: ex-Harvard scientist defects to ...,https://nypost.com/2026/05/02/us-news/former-t...
9,29,2026-05-02-20-34-03 +0000,nyt,Abortion Providers Forced to Adapt After Court...,https://www.nytimes.com/2026/05/02/us/abortion...
63,29,2026-05-02-15-56-56 +0000,nyt,"U.S. to Withdraw 5,000 Troops From Germany. Bu...",https://www.nytimes.com/2026/05/02/world/europ...
21,28,2026-05-02-19-53-29 +0000,nypost,North West goes goth at LA pop-up to promote h...,https://nypost.com/2026/05/02/us-news/north-we...
84,25,2026-05-02-13-08-46 +0000,nypost,Gaza flotilla activists — including Greta Thun...,https://nypost.com/2026/05/02/world-news/gaza-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)