## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-12-58-21 +0000,nypost,Russian nuclear chief who ordered strike on Uk...,https://nypost.com/2026/09/03/world-news/russi...
1,2026-09-03-12-57-46 +0000,bbc,Feminist activist and journalist Gloria Steine...,https://www.bbc.co.uk/news/articles/clyeq3ngwe...
2,2026-09-03-12-57-18 +0000,nyt,China Boycotts a Top Art Festival Over Taiwan ...,https://www.nytimes.com/2026/09/03/world/asia/...
3,2026-09-03-12-55-06 +0000,startribune,"Gloria Steinem, a potent voice of US feminism ...",https://www.startribune.com/gloria-steinem-a-p...
4,2026-09-03-12-50-14 +0000,bbc,B&Q and Five Guys among firms that paid staff ...,https://www.bbc.co.uk/news/articles/c39mv4vm7e...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2472/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
355  trump     38
289    new     20
248   iran     16
190     up     14
17    dies     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
101,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...,95
171,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,94
88,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,94
295,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...,88
48,2026-09-03-11-05-00 +0000,wsj,The Morning Risk Report: Trump’s ‘Economic D-D...,https://www.wsj.com/risk-compliance-journal/th...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
101,95,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...
89,60,2026-09-03-10-00-00 +0000,nypost,Dem NY House candidate Cait Conley ripped over...,https://nypost.com/2026/09/03/us-news/ny-dem-c...
333,56,2026-09-02-17-31-00 +0000,wsj,New York City Temporarily Bans AI in Classroom...,https://www.wsj.com/us-news/new-york-city-temp...
287,52,2026-09-02-19-33-25 +0000,nypost,Bessent says Ukraine causing high gas prices: ...,https://nypost.com/2026/09/02/us-news/scott-be...
82,51,2026-09-03-10-07-44 +0000,nypost,"Gloria Steinem, pioneer of women’s liberation ...",https://nypost.com/2026/09/03/us-news/gloria-s...
294,50,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
130,46,2026-09-03-08-00-00 +0000,cbc,Lindsay Clancy supporter arrested outside cour...,https://www.cbc.ca/news/world/lindsay-clancy-m...
373,45,2026-09-02-15-50-27 +0000,nypost,Oil heir Sid Bass callously dumped partner of ...,https://nypost.com/2026/09/02/business/oil-hei...
301,43,2026-09-02-18-58-00 +0000,wapo,El-Sayed blames Trump for global bond market s...,https://www.washingtonpost.com/politics/2026/0...
379,41,2026-09-02-15-33-19 +0000,bbc,Iran says US strike killed four at wedding in ...,https://www.bbc.co.uk/news/articles/cj06q4ynpm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)