## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-16-22-50-16 +0000,nypost,San Francisco residents fume as iconic trees a...,https://nypost.com/2026/09/16/us-news/san-fran...
1,2026-09-16-22-50-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...
2,2026-09-16-22-49-01 +0000,nypost,Famed LA helicopter pilot reveals five-second ...,https://nypost.com/2026/09/16/us-news/la-helic...
3,2026-09-16-22-48-58 +0000,nyt,"Democrats Meet With El-Sayed, Putting Aside Ri...",https://www.nytimes.com/2026/09/16/us/election...
4,2026-09-16-22-45-00 +0000,wsj,Brazil’s Central Bank Lowers For Fifth Straigh...,https://www.wsj.com/economy/central-banking/br...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     35
304     fed     29
198      ai     20
16      new     20
77   canada     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
67,2026-09-16-21-15-02 +0000,nypost,Trump responds to his new Fed chairman Kevin W...,https://nypost.com/2026/09/16/us-news/trump-re...,130
168,2026-09-16-18-02-32 +0000,nypost,Fed hikes interest rates for first time in thr...,https://nypost.com/2026/09/16/business/fed-hik...,124
1,2026-09-16-22-50-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...,111
45,2026-09-16-21-42-37 +0000,nyt,Trump’s Latest Threats Loom Over Fed’s Interes...,https://www.nytimes.com/2026/09/16/business/ec...,107
130,2026-09-16-19-21-00 +0000,wsj,The Fed voted unanimously to raise rates for t...,https://www.wsj.com/economy/central-banking/fe...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
67,130,2026-09-16-21-15-02 +0000,nypost,Trump responds to his new Fed chairman Kevin W...,https://nypost.com/2026/09/16/us-news/trump-re...
117,84,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
294,79,2026-09-16-11-25-05 +0000,chitri,US-Canada trade war further taxes small busine...,https://www.chicagotribune.com/2026/09/16/us-c...
162,61,2026-09-16-18-17-18 +0000,chitri,First Fed rate hike in 3 years may push borrow...,https://www.chicagotribune.com/2026/09/16/fede...
242,60,2026-09-16-14-43-23 +0000,nyt,News Helicopter Crash and Bus Accident in Los ...,https://www.nytimes.com/2026/09/15/us/los-ange...
66,49,2026-09-16-21-16-00 +0000,wsj,"The Fed raised rates, a top Democrat opposes a...",https://www.wsj.com/politics/policy/the-fed-is...
318,46,2026-09-16-10-02-05 +0000,bbc,OpenAI boss says world 'right to be afraid' bu...,https://www.bbc.co.uk/news/articles/cqx2zpj4y5...
177,44,2026-09-16-17-27-09 +0000,chitri,Fencing goes up around the main Kennedy Center...,https://www.chicagotribune.com/2026/09/16/kenn...
130,42,2026-09-16-19-21-00 +0000,wsj,The Fed voted unanimously to raise rates for t...,https://www.wsj.com/economy/central-banking/fe...
1,41,2026-09-16-22-50-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)