## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-01-17-22 +0000,nyt,Iran War Live Updates: Cease-Fire Tested by Co...,https://www.nytimes.com/live/2026/04/08/world/...
1,2026-04-09-01-15-07 +0000,nyt,"Martin Gugino, Activist Shoved by Buffalo Poli...",https://www.nytimes.com/2026/04/08/us/martin-g...
2,2026-04-09-01-03-57 +0000,startribune,Police Chief Brian O’Hara wants a second term....,https://www.startribune.com/minneapolis-police...
3,2026-04-09-01-03-19 +0000,nypost,Massive car-killer pothole forces lane closure...,https://nypost.com/2026/04/08/us-news/massive-...
4,2026-04-09-01-02-00 +0000,wsj,Australian Dollar’s ‘Ceiling’ Likely Around $0...,https://www.wsj.com/finance/currencies/asian-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
0    iran     98
5    fire     47
4   cease     44
1     war     37
70  trump     36

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
323,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...,312
301,2026-04-08-08-38-12 +0000,nypost,Trump declares Iran cease-fire deal could lead...,https://nypost.com/2026/04/08/world-news/trump...,273
43,2026-04-08-23-00-00 +0000,wsj,"The fragile cease-fire between the U.S., Israe...",https://www.wsj.com/economy/whats-next-for-the...,271
0,2026-04-09-01-17-22 +0000,nyt,Iran War Live Updates: Cease-Fire Tested by Co...,https://www.nytimes.com/live/2026/04/08/world/...,261
342,2026-04-08-01-32-00 +0000,wsj,"Asian Markets Stage Relief Rally, Oil Drops on...",https://www.wsj.com/finance/stocks/asian-marke...,252

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
323,312,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...
43,82,2026-04-08-23-00-00 +0000,wsj,"The fragile cease-fire between the U.S., Israe...",https://www.wsj.com/economy/whats-next-for-the...
161,66,2026-04-08-18-25-24 +0000,nyt,Gas Prices Won’t Quickly Return to Prewar Leve...,https://www.nytimes.com/2026/04/08/business/en...
150,61,2026-04-08-18-55-05 +0000,cbc,"Despite ceasefire with Iran, Israel's aggressi...",https://www.cbc.ca/news/lebanon-israel-attacks...
175,44,2026-04-08-17-18-41 +0000,nypost,Delta scraps capacity growth plans as fuel pri...,https://nypost.com/2026/04/08/business/delta-s...
195,39,2026-04-08-16-37-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
31,38,2026-04-08-23-37-00 +0000,wsj,A federal appeals court has denied Anthropic’s...,https://www.wsj.com/politics/national-security...
220,38,2026-04-08-15-03-04 +0000,latimes,'Ketamine queen' gets lengthy prison sentence ...,https://www.latimes.com/california/story/2026-...
272,36,2026-04-08-10-58-00 +0000,wsj,A large team of Wall Street Journal reporters ...,https://www.wsj.com/politics/how-the-journal-c...
245,33,2026-04-08-13-01-00 +0000,wsj,Republican Clayton Fuller won the special elec...,https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)