## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-11-22-55-14 +0000,missionlocal,‘Violently assaulted’: Judge releases S.F. man...,https://missionlocal.org/2026/03/sf-mayor-dani...
1,2026-03-11-22-53-00 +0000,wsj,Amazon’s Win Against Perplexity Kicks AI Shopp...,https://www.wsj.com/business/retail/amazons-wi...
2,2026-03-11-22-46-44 +0000,bbc,Big Tech backs Anthropic in fight against Trum...,https://www.bbc.com/news/articles/c4g7k7zdd0zo...
3,2026-03-11-22-46-14 +0000,nypost,Trump brings Jake Paul on stage at Kentucky ra...,https://nypost.com/2026/03/11/us-news/trump-br...
4,2026-03-11-22-44-44 +0000,nyt,Slavery Photos of Renty Get a ‘Final Resting P...,https://www.nytimes.com/2026/03/11/us/renty-sl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2569/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
85     iran     61
22    trump     40
86      war     39
231     oil     23
391  prices     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
89,2026-03-11-20-52-30 +0000,nyt,Iran’s New Supreme Leader Was Wounded Early in...,https://www.nytimes.com/2026/03/11/world/middl...,163
280,2026-03-11-11-36-18 +0000,nypost,Record 400M oil barrels to be released from em...,https://nypost.com/2026/03/11/world-news/iea-t...,161
388,2026-03-10-23-02-07 +0000,cbc,How high will the U.S.-Israel war with Iran pu...,https://www.cbc.ca/player/play/9.7123237?cmp=rss,161
235,2026-03-11-14-54-00 +0000,wsj,The economic shock waves of the Iran war are l...,https://www.wsj.com/business/energy-oil/the-ec...,158
365,2026-03-11-01-00-00 +0000,wsj,Trump Says the Iran War Is Nearly Won but Isra...,https://www.wsj.com/world/middle-east/trump-sa...,156

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
89,163,2026-03-11-20-52-30 +0000,nyt,Iran’s New Supreme Leader Was Wounded Early in...,https://www.nytimes.com/2026/03/11/world/middl...
317,96,2026-03-11-08-33-53 +0000,wsj,Stock Market Today: Oil Prices Push Higher Des...,https://www.wsj.com/livecoverage/cpi-inflation...
287,89,2026-03-11-11-06-58 +0000,nyt,"A Trump-Xi Summit Nears, but China Doesn’t Kno...",https://www.nytimes.com/2026/03/11/world/asia/...
235,58,2026-03-11-14-54-00 +0000,wsj,The economic shock waves of the Iran war are l...,https://www.wsj.com/business/energy-oil/the-ec...
261,51,2026-03-11-13-19-52 +0000,nypost,Iranian women’s soccer team member flip-flops ...,https://nypost.com/2026/03/11/world-news/irani...
29,47,2026-03-11-22-06-00 +0000,wsj,"Commercial ships near Strait or Hormuz hit, ne...",https://www.wsj.com/politics/policy/commercial...
221,47,2026-03-11-15-24-57 +0000,bbc,French aid worker among three killed in drone ...,https://www.bbc.com/news/articles/cvgj8veg0gno...
107,47,2026-03-11-20-17-00 +0000,wsj,Sen. John Cornyn of Texas reversed himself and...,https://www.wsj.com/politics/policy/john-corny...
244,45,2026-03-11-14-13-52 +0000,bbc,EU and UK demand Israel stop surge in West Ban...,https://www.bbc.com/news/articles/c620vwl97vyo...
352,43,2026-03-11-02-07-39 +0000,nypost,House Oversight Committee wants to interview E...,https://nypost.com/2026/03/10/us-news/house-ov...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)