## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-18-17-08-41 +0000,nyt,MyPillow Founder Not Registered to Vote in Sta...,https://www.nytimes.com/2026/07/18/us/mypillow...
1,2026-07-18-17-05-56 +0000,nypost,NYC hit with flash flood warnings as downpours...,https://nypost.com/2026/07/18/us-news/nyc-hit-...
2,2026-07-18-17-00-24 +0000,nypost,Will smokey skies affect the much-anticipated ...,https://nypost.com/2026/07/18/us-news/will-smo...
3,2026-07-18-17-00-00 +0000,wsj,The Clock Is Now Ticking on Netanyahu’s Politi...,https://www.wsj.com/world/middle-east/the-cloc...
4,2026-07-18-17-00-00 +0000,wsj,Lego Strikes Back Against Screens—With Chips i...,https://www.wsj.com/business/lego-smart-play-i...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2609/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
62    trump     34
24      new     15
37     iran     13
3        he     13
32  strikes     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
142,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...,106
137,2026-07-18-01-29-47 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...,81
257,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...,81
177,2026-07-17-21-38-56 +0000,nypost,Trump says Canada must pay new tariffs due to ...,https://nypost.com/2026/07/17/us-news/trump-sa...,75
167,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
142,106,2026-07-18-01-00-00 +0000,wsj,"President Trump’s speech Thursday, in which he...",https://www.wsj.com/politics/policy/trumps-wee...
257,47,2026-07-17-17-25-00 +0000,wsj,House Republicans are plunging ahead with a pl...,https://www.wsj.com/politics/policy/gop-packag...
137,47,2026-07-18-01-29-47 +0000,bbc,Trump threatens new Canada tariffs over fires ...,https://www.bbc.co.uk/news/articles/cwyq93j34l...
19,43,2026-07-18-15-52-41 +0000,nypost,OnlyFans model Courtney Clenney plans to bring...,https://nypost.com/2026/07/18/us-news/onlyfans...
109,40,2026-07-18-08-00-00 +0000,cbc,This World Cup photographer used a 96-year-old...,https://www.cbc.ca/news/canada/world-cup-photo...
167,40,2026-07-17-22-01-28 +0000,nypost,States must take election security steps or lo...,https://nypost.com/2026/07/17/us-news/trump-ad...
55,31,2026-07-18-13-08-17 +0000,nypost,Eight killed after Ukraine launches wave of dr...,https://nypost.com/2026/07/18/world-news/eight...
18,29,2026-07-18-15-54-28 +0000,nypost,Hochul backed NY data-center ban to satisfy DS...,https://nypost.com/2026/07/18/us-news/hochul-b...
90,29,2026-07-18-10-00-00 +0000,latimes,West Hollywood faces long recovery from massiv...,https://www.latimes.com/california/story/2026-...
244,29,2026-07-17-18-21-10 +0000,latimes,California-based Taylor Farms pulls iceberg le...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)