## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-06-21-14-00 +0000,bbc,Hegseth attacks Europe over 'invasion' of migr...,https://www.bbc.com/news/articles/c802e7jk458o...
1,2026-06-06-21-09-49 +0000,nypost,NYC composer allegedly cheated out of ‘Wicked’...,https://nypost.com/2026/06/06/us-news/nyc-comp...
2,2026-06-06-21-03-16 +0000,nyt,"Alan Riding, Times Correspondent in Latin Amer...",https://www.nytimes.com/2026/06/06/business/me...
3,2026-06-06-21-00-36 +0000,nyt,Infant Killed as Israeli Military Fires on Car...,https://www.nytimes.com/2026/06/06/world/middl...
4,2026-06-06-20-59-45 +0000,nypost,US plans to use Iranian assets to rebuild Gulf...,https://nypost.com/2026/06/06/us-news/us-plans...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
275       trump     18
112       world     15
106        iran     13
113         cup     12
46   california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...,65
186,2026-06-05-22-36-13 +0000,nypost,Trump takes victory lap on hiring spike— vows ...,https://nypost.com/2026/06/05/us-news/trump-ta...,64
178,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...,63
36,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,56
193,2026-06-05-22-00-00 +0000,cbc,Iran's soccer players issued visas to play Wor...,https://www.cbc.ca/news/world/iran-world-cup-p...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,65,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...
160,53,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...
178,45,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...
145,44,2026-06-06-03-01-39 +0000,latimes,SoFi Stadium workers vote to authorize strike ...,https://www.latimes.com/sports/soccer/story/20...
197,35,2026-06-05-21-51-59 +0000,nyt,"Amid Graham Platner Controversy, Where Does th...",https://www.nytimes.com/2026/06/05/us/politics...
207,32,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
80,30,2026-06-06-12-27-17 +0000,cbc,"Palestinian baby killed, parents hurt in Israe...",https://www.cbc.ca/news/world/israeli-palestin...
164,29,2026-06-06-00-45-24 +0000,nypost,Spencer Pratt’s lead shrinks over Nithya Raman...,https://nypost.com/2026/06/05/us-news/spencer-...
39,27,2026-06-06-18-23-39 +0000,nypost,Five anti-ICE rioters arrested outside Delaney...,https://nypost.com/2026/06/06/us-news/anti-ice...
74,27,2026-06-06-13-31-21 +0000,nypost,Pope Leo urges country to stop ‘fanning flames...,https://nypost.com/2026/06/06/world-news/pope-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)