## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-26-12-06-06 +0000,nypost,Venezuelan dictator Nicolás Maduro heads to NY...,https://nypost.com/2026/03/26/us-news/venezuel...
1,2026-03-26-12-00-19 +0000,nyt,"After ‘Sausage Making,’ European Lawmakers App...",https://www.nytimes.com/2026/03/26/world/europ...
2,2026-03-26-12-00-00 +0000,nyt,Iran War Live Updates: Israel Says Iranian Nav...,https://www.nytimes.com/live/2026/03/26/world/...
3,2026-03-26-11-59-56 +0000,bbc,NS&I set to pay millions to customers over mis...,https://www.bbc.com/news/articles/c3w3eg4n9zwo...
4,2026-03-26-11-57-20 +0000,nyt,"Shield AI, a Start-Up Making Military Drones, ...",https://www.nytimes.com/2026/03/26/business/de...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22    iran     60
116  trump     47
23     war     31
6    court     14
242    oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
267,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...,197
242,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...,163
289,2026-03-25-19-17-42 +0000,nypost,Trump ‘prepared to unleash hell’ if Iran won’t...,https://nypost.com/2026/03/25/world-news/leavi...,162
244,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...,161
170,2026-03-26-01-00-00 +0000,wsj,Trump Tells Aides He Wants Speedy End to Iran War,https://www.wsj.com/politics/elections/trump-t...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
267,197,2026-03-25-20-27-51 +0000,nyt,Trump Says He’s Talking With Iran. Iran Says H...,https://www.nytimes.com/2026/03/25/world/middl...
244,101,2026-03-25-21-17-00 +0000,wsj,The prospects of a diplomatic deal ending the ...,https://www.wsj.com/world/middle-east/the-narr...
260,90,2026-03-25-20-50-44 +0000,nypost,Kristi Noem keeps her lover Corey Lewandowski ...,https://nypost.com/2026/03/25/us-news/kristi-n...
332,71,2026-03-25-17-06-24 +0000,nypost,"Meta, YouTube found liable for woman’s debilit...",https://nypost.com/2026/03/25/us-news/jury-tak...
335,64,2026-03-25-16-59-00 +0000,wsj,The Federal Reserve ran an operating loss of $...,https://www.wsj.com/economy/central-banking/fe...
383,63,2026-03-25-14-19-00 +0000,wsj,Trump plans to install some of the biggest nam...,https://www.wsj.com/politics/policy/trump-to-n...
242,56,2026-03-25-21-18-55 +0000,bbc,Oil prices volatile as Trump talks up Iran neg...,https://www.bbc.com/news/articles/c995xp4jxj2o...
120,45,2026-03-26-07-17-28 +0000,nypost,Canadian Prime Minister Mark Carney slams Air ...,https://nypost.com/2026/03/26/us-news/canadian...
115,44,2026-03-26-07-38-05 +0000,nypost,"NYC high school football star, honors student ...",https://nypost.com/2026/03/26/us-news/nyc-high...
38,42,2026-03-26-10-48-00 +0000,wsj,Surgeon-general nominee Dr. Casey Means lacks ...,https://www.wsj.com/politics/this-is-the-start...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)