## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-12-12-02-01 +0000,nyt,"Live Updates: In Europe, the Total Solar Eclip...",https://www.nytimes.com/live/2026/08/12/world/...
1,2026-08-12-12-01-34 +0000,bbc,At least 15 die as boat sinks in Zimbabwe's La...,https://www.bbc.co.uk/news/articles/czxe2vyxd7...
2,2026-08-12-12-00-59 +0000,nyt,"Europeans, Braced for 5th Heat Wave of 2026, H...",https://www.nytimes.com/2026/08/12/world/europ...
3,2026-08-12-12-00-00 +0000,nypost,Inside feds’ stealth mission to deport Califor...,https://nypost.com/2026/08/12/us-news/operatio...
4,2026-08-12-11-58-32 +0000,nyt,"Deported From the U.S., Trapped in a Prison in...",https://www.nytimes.com/video/world/africa/100...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2496/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
322       trump     56
190         new     24
41    wisconsin     22
430     primary     22
91   democratic     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
181,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,168
163,2026-08-12-03-32-23 +0000,nyt,Lisa Demuth Defeats Trump-Endorsed Candidate M...,https://www.nytimes.com/2026/08/11/us/election...,136
378,2026-08-11-15-53-53 +0000,bbc,Watch: Why was Trump smuggled out of Air Force...,https://www.bbc.co.uk/news/videos/cj3672ljgzro...,124
182,2026-08-12-01-42-35 +0000,chitri,President Trump says advisers wanted him off A...,https://www.chicagotribune.com/2026/08/11/trum...,123
92,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
181,168,2026-08-12-01-45-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...
92,116,2026-08-12-09-04-00 +0000,wsj,Here are our takeaways after the race between ...,https://www.wsj.com/politics/elections/electio...
263,71,2026-08-11-21-25-00 +0000,wsj,Mamdani Takes On Amazon in New Battle Over New...,https://www.wsj.com/business/logistics/mamdani...
179,66,2026-08-12-01-54-19 +0000,nypost,Former NFL sideline reporter Michele Tafoya sc...,https://nypost.com/2026/08/11/us-news/former-n...
173,58,2026-08-12-02-30-00 +0000,wsj,Sen. Darline Graham advanced to a runoff later...,https://www.wsj.com/politics/elections/sen-dar...
118,46,2026-08-12-08-25-27 +0000,wsj,CPI Report Today: Tech Earnings Buoy Stock Fut...,https://www.wsj.com/livecoverage/stock-market-...
309,45,2026-08-11-19-27-17 +0000,bbc,Houthis reportedly kill six in first deadly at...,https://www.bbc.co.uk/news/articles/ckg9wpmzml...
206,43,2026-08-12-00-44-28 +0000,nyt,As Death Toll From Colombia Earthquake Rises t...,https://www.nytimes.com/2026/08/11/world/ameri...
406,40,2026-08-11-14-00-00 +0000,wsj,"Home sales fell in July, getting the summer of...",https://www.wsj.com/economy/housing/july-home-...
383,40,2026-08-11-15-36-38 +0000,nypost,Trump says Putin freed Marine vet Robert Gilma...,https://nypost.com/2026/08/11/world-news/russi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)