## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-16-13-13 +0000,nypost,Tune in tonight for Discovery Channel and The ...,https://nypost.com/2026/04/01/us-news/tune-in-...
1,2026-04-01-16-12-45 +0000,bbc,UK will seek closer ties with EU in light of I...,https://www.bbc.com/news/articles/c62l6w03lwzo...
2,2026-04-01-16-12-26 +0000,nyt,"Robot Taxis Stop in Traffic in Chinese City, S...",https://www.nytimes.com/2026/04/01/business/ba...
3,2026-04-01-16-09-00 +0000,startribune,The 5 best new foods at Target Field for the T...,https://www.startribune.com/the-5-best-new-foo...
4,2026-04-01-16-08-21 +0000,nypost,FIFA World Cup tickets rush turns into chaos a...,https://nypost.com/2026/04/01/us-news/fifa-wor...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2624/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
68       trump     62
16        iran     48
17         war     40
81  birthright     19
71       court     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-04-01-16-00-26 +0000,nyt,Iran War Live Updates: Trump Berates Allies Wh...,https://www.nytimes.com/live/2026/04/01/world/...,202
328,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,181
184,2026-04-01-08-49-19 +0000,bbc,Oil briefly falls below $100 and shares jump o...,https://www.bbc.com/news/articles/c2489v97842o...,174
47,2026-04-01-14-59-06 +0000,bbc,Trump to give primetime address on Iran war as...,https://www.bbc.com/news/articles/c74vqd8k3g1o...,166
70,2026-04-01-14-13-00 +0000,wsj,Trump Raises NATO Withdrawal as Allies Push Ba...,https://www.wsj.com/world/trump-raises-nato-wi...,163

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,202,2026-04-01-16-00-26 +0000,nyt,Iran War Live Updates: Trump Berates Allies Wh...,https://www.nytimes.com/live/2026/04/01/world/...
132,110,2026-04-01-10-58-00 +0000,wsj,"Even by the Supreme Court’s lofty standards, W...",https://www.wsj.com/politics/is-this-the-bigge...
333,63,2026-03-31-20-18-00 +0000,wsj,The Trump administration can’t end federal fun...,https://www.wsj.com/politics/policy/trumps-ord...
90,62,2026-04-01-13-40-54 +0000,nypost,NASA’s historic Artemis II mission shows space...,https://nypost.com/2026/04/01/science/potentia...
224,58,2026-04-01-02-32-30 +0000,nyt,Trump Lashes Out at Europe Over Strait of Horm...,https://www.nytimes.com/2026/03/31/world/middl...
23,50,2026-04-01-15-50-00 +0000,wsj,The drone having its moment in the Middle East...,https://www.wsj.com/politics/national-security...
50,50,2026-04-01-14-52-16 +0000,nypost,Iran’s new supreme leader vows to support anti...,https://nypost.com/2026/04/01/world-news/irans...
37,45,2026-04-01-15-16-14 +0000,nypost,Kristi Noem’s hometown pals in disbelief over ...,https://nypost.com/2026/04/01/us-news/kristi-n...
327,42,2026-03-31-20-32-12 +0000,wapo,Gas hits $4 a gallon for first time since 2022...,https://www.washingtonpost.com/business/2026/0...
277,39,2026-03-31-22-39-56 +0000,latimes,"He killed girlfriend's lover in SoCal, then ki...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)