## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-18-31-11 +0000,nypost,"Andrew Tate, bro Tristan ordered to remain in ...",https://nypost.com/2026/07/20/us-news/andrew-t...
1,2026-07-20-18-29-55 +0000,bbc,Kuenssberg: 'Labour see Burnham as a winner',https://www.bbc.co.uk/news/videos/c3r0xr1x4xxo...
2,2026-07-20-18-29-18 +0000,bbc,Key takeaways as Andy Burnham becomes PM,https://www.bbc.co.uk/news/articles/c80nln7zgp...
3,2026-07-20-18-28-25 +0000,startribune,MnDOT will soon pilot speed cameras in work zones,https://www.startribune.com/mndot-will-soon-pi...
4,2026-07-20-18-24-47 +0000,bbc,John Healey becomes chancellor weeks after sho...,https://www.bbc.co.uk/news/articles/ce85y9lm81...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2349/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
73      iran     27
288    world     26
17   burnham     26
289      cup     24
107      new     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
313,2026-07-19-19-25-24 +0000,chitri,Donald Trump celebrates the World Cup as a US ...,https://www.chicagotribune.com/2026/07/19/trum...,108
16,2026-07-20-18-15-38 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,106
290,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,99
296,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...,94
271,2026-07-20-00-44-03 +0000,bbc,"Trump, Bieber and Shakira - a World Cup final ...",https://www.bbc.co.uk/sport/football/articles/...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
313,108,2026-07-19-19-25-24 +0000,chitri,Donald Trump celebrates the World Cup as a US ...,https://www.chicagotribune.com/2026/07/19/trum...
16,106,2026-07-20-18-15-38 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
283,75,2026-07-19-23-25-00 +0000,wsj,"Usha Vance gave birth to a baby boy on Sunday,...",https://www.wsj.com/us-news/second-lady-usha-v...
71,66,2026-07-20-16-47-32 +0000,nyt,Pentagon Identifies 2 U.S. Soldiers Killed in ...,https://www.nytimes.com/2026/07/20/us/iran-war...
230,50,2026-07-20-09-00-00 +0000,wsj,Many wealthy Texas Republicans can’t stomach t...,https://www.wsj.com/politics/elections/ken-pax...
221,47,2026-07-20-09-30-00 +0000,wsj,He Bought a House ‘Sight Unseen.’ Then He Foun...,https://www.wsj.com/real-estate/he-bought-a-ho...
248,45,2026-07-20-04-06-04 +0000,nyt,Trump Says New Air Force One Will Be Taken Out...,https://www.nytimes.com/2026/07/19/us/politics...
296,38,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
57,34,2026-07-20-17-16-29 +0000,chitri,Ex-Mexican drug lord Ismael ‘El Mayo’ Zambada ...,https://www.chicagotribune.com/2026/07/20/mexi...
41,34,2026-07-20-17-35-36 +0000,wapo,"U.S., Iran trade strikes as Houthis declare bl...",https://www.washingtonpost.com/world/2026/07/2...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)