## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-20-28-38 +0000,nypost,Wall Street reveals hugely bullish SpaceX call...,https://nypost.com/2026/07/07/business/wall-st...
1,2026-07-07-20-28-04 +0000,nypost,Gavin Newsom’s ex-chief of staff has key sente...,https://nypost.com/2026/07/07/us-news/dana-wil...
2,2026-07-07-20-27-56 +0000,nypost,Historic vessel mysteriously sinks in NYC – ju...,https://nypost.com/2026/07/07/us-news/historic...
3,2026-07-07-20-27-52 +0000,nypost,Terrifying moment armed kidnapper pistol-whips...,https://nypost.com/2026/07/07/us-news/terrifyi...
4,2026-07-07-20-27-37 +0000,nypost,Incredible new robot that stalks seabed for en...,https://nypost.com/us-news/san-diego-companys-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2531/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
54     trump     33
69   platner     22
365    world     18
153   graham     18
71        he     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...,159
317,2026-07-06-22-30-20 +0000,nyt,Who Might Replace Graham Platner if He Drops O...,https://www.nytimes.com/2026/07/06/us/politics...,101
144,2026-07-07-15-27-46 +0000,nypost,Mayor Zohran Mamdani tells Maine’s Graham Plat...,https://nypost.com/2026/07/07/us-news/mayor-zo...,96
255,2026-07-07-07-33-42 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,94
48,2026-07-07-19-09-37 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,159,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
48,94,2026-07-07-19-09-37 +0000,nyt,Trump’s World Cup Intervention Roils the Socce...,https://www.nytimes.com/2026/07/06/business/de...
183,80,2026-07-07-13-21-21 +0000,cbc,French far-right leader Marine Le Pen to run f...,https://www.cbc.ca/news/world/france-court-mar...
172,63,2026-07-07-13-47-57 +0000,nypost,Nigel Farage reveals he’s quitting parliament ...,https://nypost.com/2026/07/07/world-news/nigel...
162,60,2026-07-07-14-31-57 +0000,bbc,"Next PM needs to wake UK up to threat of war, ...",https://www.bbc.co.uk/news/articles/cddljy1y3n...
57,55,2026-07-07-18-56-17 +0000,nyt,Iran’s Strikes on Ships in Strait of Hormuz Te...,https://www.nytimes.com/2026/07/07/world/middl...
154,41,2026-07-07-15-00-00 +0000,latimes,35 indie movies and Disney's new animated film...,https://www.latimes.com/entertainment-arts/bus...
87,39,2026-07-07-17-58-48 +0000,bbc,Woman suspected of Monaco bomb attack found de...,https://www.bbc.co.uk/news/articles/c5yz3770yg...
204,37,2026-07-07-11-08-52 +0000,wapo,Foreign media were granted rare visas to cover...,https://www.washingtonpost.com/world/2026/07/0...
164,37,2026-07-07-14-22-03 +0000,nypost,"Trump lifts defense sanctions on Turkey, clear...",https://nypost.com/2026/07/07/us-news/trump-li...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)