## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-17-20-31 +0000,nyt,Wildfires Live Updates: Extreme Heat Threatens...,https://www.nytimes.com/live/2026/07/27/world/...
1,2026-07-27-17-20-27 +0000,bbc,What you need to know if you're travelling to ...,https://www.bbc.co.uk/news/videos/c89npw4q3g4o...
2,2026-07-27-17-20-00 +0000,wsj,"Ex-JPMorgan Banker Alleges Racism, Sexual Assa...",https://www.wsj.com/business/ex-jpmorgan-banke...
3,2026-07-27-17-19-55 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/27/world/...
4,2026-07-27-17-17-07 +0000,nyt,"Even Before Attack, Berlin’s Gay Community Fel...",https://www.nytimes.com/2026/07/27/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
90     iran     22
6       new     16
207   trump     16
291     out     12
9    france     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-07-27-17-20-31 +0000,nyt,Wildfires Live Updates: Extreme Heat Threatens...,https://www.nytimes.com/live/2026/07/27/world/...,66
237,2026-07-26-22-25-29 +0000,nypost,"Trump likes daily strikes on Iran, Sen. Kenned...",https://nypost.com/2026/07/26/world-news/trump...,66
159,2026-07-27-10-27-57 +0000,nypost,Iran ramps up threats on Ukraine over Caspian ...,https://nypost.com/2026/07/27/world-news/iran-...,60
264,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...,57
90,2026-07-27-14-10-53 +0000,nypost,Netanyahu heads to DC after warning Trump need...,https://nypost.com/2026/07/27/us-news/netanyah...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,66,2026-07-27-17-20-31 +0000,nyt,Wildfires Live Updates: Extreme Heat Threatens...,https://www.nytimes.com/live/2026/07/27/world/...
237,66,2026-07-26-22-25-29 +0000,nypost,"Trump likes daily strikes on Iran, Sen. Kenned...",https://nypost.com/2026/07/26/world-news/trump...
264,57,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...
62,48,2026-07-27-15-39-54 +0000,bbc,Three dead and several injured in shooting at ...,https://www.bbc.co.uk/news/articles/c78gjyx4q2...
186,40,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
251,38,2026-07-26-21-00-27 +0000,bbc,Badenoch says PM must rule out tax rises to fu...,https://www.bbc.co.uk/news/articles/c0jlzqe9z9...
149,37,2026-07-27-11-02-00 +0000,wsj,Chip Maker Soars 466% on Debut to Become No. 1...,https://www.wsj.com/tech/cxmts-strong-debut-bo...
265,32,2026-07-26-19-07-31 +0000,nypost,Raging DNC boss Ken Martin threw phone at aide...,https://nypost.com/2026/07/26/us-news/raging-d...
22,29,2026-07-27-16-41-23 +0000,nypost,Paramount CEO confident on Warner Bros. merger...,https://nypost.com/2026/07/27/media/paramount-...
23,27,2026-07-27-16-40-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)