## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-28-03-33-06 +0000,nypost,Democratic Senate hopeful Abdul El-Sayed defen...,https://nypost.com/2026/07/27/us-news/democrat...
1,2026-07-28-03-31-06 +0000,nyt,"Fauci, in Private Diary, Reflected on Covid’s ...",https://www.nytimes.com/2026/07/27/us/politics...
2,2026-07-28-03-20-20 +0000,bbc,'I just found all the classified stuff downsta...,https://www.bbc.co.uk/news/articles/cr49znlz5g...
3,2026-07-28-03-20-00 +0000,wsj,"Singapore Dollar Steady, Supported by Tighter ...",https://www.wsj.com/finance/currencies/asian-c...
4,2026-07-28-03-15-09 +0000,nyt,"India’s ‘Cockroach’ Protesters Disperse, But Q...",https://www.nytimes.com/2026/07/27/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
320      trump     30
333       iran     27
87         new     26
85   wildfires     14
189        out     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
257,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...,94
113,2026-07-27-21-10-56 +0000,bbc,Trump says Iran war talks taking place during ...,https://www.bbc.co.uk/news/articles/c62xn4vzmn...,91
10,2026-07-28-02-50-58 +0000,nyt,Europe Wildfires Updates: New Heat Wave Could ...,https://www.nytimes.com/live/2026/07/27/world/...,89
57,2026-07-28-00-21-41 +0000,nyt,Trump Backs New Talks but It’s Unclear What He...,https://www.nytimes.com/2026/07/27/us/politics...,89
116,2026-07-27-21-06-42 +0000,bbc,"As the US pauses the war with Iran, is Trump r...",https://www.bbc.co.uk/news/articles/c0qvnk2ezp...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
257,94,2026-07-27-14-10-53 +0000,nypost,"Trump praises ‘great’ Netanyahu, says they’re ...",https://nypost.com/2026/07/27/us-news/netanyah...
10,89,2026-07-28-02-50-58 +0000,nyt,Europe Wildfires Updates: New Heat Wave Could ...,https://www.nytimes.com/live/2026/07/27/world/...
98,59,2026-07-27-21-50-18 +0000,nypost,Nvidia in talks to back $500B OpenAI data cent...,https://nypost.com/2026/07/27/business/nvidia-...
338,55,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
73,52,2026-07-27-23-26-53 +0000,nypost,Xavier Becerra leads Democrats’ all-out war ag...,https://nypost.com/2026/07/27/us-news/xavier-b...
100,42,2026-07-27-21-46-00 +0000,wsj,GOP Sen. Rand Paul this weekend released writi...,https://www.wsj.com/politics/policy/key-takeaw...
61,41,2026-07-28-00-00-00 +0000,wsj,"Francesca Hong, a member of the Democratic Soc...",https://www.wsj.com/politics/elections/a-democ...
44,40,2026-07-28-01-00-00 +0000,wsj,The Fed meets this week with an outcome that i...,https://www.wsj.com/economy/central-banking/ke...
346,40,2026-07-27-08-06-20 +0000,wsj,"Stock Market News, July 27, 2026: Chip Stocks ...",https://www.wsj.com/livecoverage/stock-market-...
109,39,2026-07-27-21-16-47 +0000,chitri,Trump administration urges Supreme Court to al...,https://www.chicagotribune.com/2026/07/27/trum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)