## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-30-18-55-57 +0000,bbc,What we know about Cornell University frat hou...,https://www.bbc.co.uk/news/articles/cmpq0r1ljp...
1,2026-09-30-18-55-00 +0000,wsj,Treasury Yields Hit Fresh Highs,https://www.wsj.com/economy/central-banking/u-...
2,2026-09-30-18-54-30 +0000,nyt,55 Swatting Calls: A Couple’s Fight Against On...,https://www.nytimes.com/2026/09/30/us/swatting...
3,2026-09-30-18-53-43 +0000,nyt,"Donor Gives $3 Billion to Carnegie Mellon, the...",https://www.nytimes.com/2026/09/30/us/3-billio...
4,2026-09-30-18-52-24 +0000,nyt,He Was a Tech Investor Before There Was a Sili...,https://www.nytimes.com/2026/09/30/technology/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2608/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
63        trump     43
64          new     23
239          ai     22
48   california     15
57       israel     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
374,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...,172
202,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,102
357,2026-09-29-22-53-47 +0000,latimes,Can California stop Trump from drilling off it...,https://www.latimes.com/environment/story/2026...,97
370,2026-09-29-21-55-00 +0000,cbc,Trump says top tech firms have signed accord t...,https://www.cbc.ca/news/world/ai-trump-agreeme...,92
118,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
374,172,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...
202,96,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...
313,69,2026-09-30-02-39-57 +0000,nypost,New UK Prime Minister Andy Burnham hints at Eu...,https://nypost.com/2026/09/29/world-news/new-u...
250,62,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...
29,50,2026-09-30-18-22-54 +0000,nypost,‘American Idol’ alum Caleb Flynn’s wife saved ...,https://nypost.com/2026/09/30/us-news/american...
67,49,2026-09-30-17-25-19 +0000,nypost,Paramount-Warner Bros. expected to tap Mattel ...,https://nypost.com/2026/09/30/media/paramount-...
373,45,2026-09-29-21-47-52 +0000,nypost,Ukraine rolls out kamikaze ‘zombie cars’ to bl...,https://nypost.com/2026/09/29/world-news/ukrai...
356,45,2026-09-29-23-00-00 +0000,wsj,Americans in both parties back government-impo...,https://www.wsj.com/politics/policy/americans-...
55,42,2026-09-30-17-48-00 +0000,wsj,Senate Republicans made a late push to show vo...,https://www.wsj.com/politics/policy/senate-rep...
79,41,2026-09-30-17-01-42 +0000,nyt,"Court Pauses Execution of Christa Pike, Tennes...",https://www.nytimes.com/2026/09/30/us/christa-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)