## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-24-11-26-45 +0000,nyt,With Hopes High for New H.I.V. Prevention Pill...,https://www.nytimes.com/2026/07/24/us/politics...
1,2026-07-24-11-22-00 +0000,wsj,Switzerland Rejects Forced Labor Accusations A...,https://www.wsj.com/economy/trade/switzerland-...
2,2026-07-24-11-18-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
3,2026-07-24-11-14-51 +0000,nyt,Trump’s Global Tariffs: What’s the Latest on t...,https://www.nytimes.com/article/trump-tariffs-...
4,2026-07-24-11-11-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     49
2      new     37
365   iran     29
26     war     19
120    oil     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-07-24-01-00-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,144
87,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,136
275,2026-07-23-19-04-00 +0000,wapo,Saudi nuclear deal in doubt as Trump adds new ...,https://www.washingtonpost.com/politics/2026/0...,132
362,2026-07-23-14-15-16 +0000,nypost,US beefs up military might in Middle East as T...,https://nypost.com/2026/07/23/world-news/us-be...,130
282,2026-07-23-18-40-00 +0000,wsj,Trump Adds New Israel Hurdle to Saudi Nuclear ...,https://www.wsj.com/world/middle-east/trump-ti...,129

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,144,2026-07-24-01-00-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...
87,87,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
341,80,2026-07-23-15-20-03 +0000,nypost,Brent crude oil surges to $100 a barrel for fi...,https://nypost.com/2026/07/23/business/brent-c...
327,64,2026-07-23-16-00-00 +0000,wsj,Mortgage rates rose to their highest level in ...,https://www.wsj.com/economy/housing/mortgage-r...
140,64,2026-07-24-01-00-00 +0000,wsj,Inside China’s All-Out Push to Catch Up With A...,https://www.wsj.com/world/china/china-ai-chips...
357,54,2026-07-23-14-24-40 +0000,nyt,"For South Korea, U.S.-Saudi Nuclear Deal Expos...",https://www.nytimes.com/2026/07/23/world/asia/...
126,44,2026-07-24-02-00-00 +0000,wsj,Capital Account: When the Supreme Court struck...,https://www.wsj.com/politics/policy/trumps-tra...
54,39,2026-07-24-09-21-35 +0000,nypost,Black bear caught on video wandering into Cali...,https://nypost.com/2026/07/24/us-news/black-be...
93,39,2026-07-24-07-20-12 +0000,nypost,NY cops not ruling out another suspect may hav...,https://nypost.com/2026/07/24/us-news/ny-cops-...
399,38,2026-07-23-12-05-33 +0000,nypost,Mango heir’s son told by therapist to confront...,https://nypost.com/2026/07/23/world-news/mango...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)