## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-15-44-41 +0000,wapo,Iran war pushed inflation to highest rate in n...,https://www.washingtonpost.com/business/2026/0...
1,2026-05-12-15-43-02 +0000,nyt,Live Updates: Britain’s Starmer Defies Calls t...,https://www.nytimes.com/live/2026/05/12/world/...
2,2026-05-12-15-43-02 +0000,nyt,Iran War Live Updates: Truce Hangs in the Bala...,https://www.nytimes.com/live/2026/05/12/world/...
3,2026-05-12-15-39-22 +0000,bbc,Green Party admits Polanski may have failed to...,https://www.bbc.com/news/articles/cy02wdzrg6jo...
4,2026-05-12-15-36-07 +0000,nyt,China Sought Access to Anthropic’s Newest A.I....,https://www.nytimes.com/2026/05/12/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
196       trump     36
0          iran     31
1           war     25
579  hantavirus     16
11      starmer     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
238,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...,150
272,2026-05-11-21-39-00 +0000,wsj,President Trump privately complained to the ac...,https://www.wsj.com/politics/national-security...,123
19,2026-05-12-15-08-00 +0000,wsj,Consumer prices rose 3.8% in April from a year...,https://www.wsj.com/economy/cpi-inflation-repo...,109
2,2026-05-12-15-43-02 +0000,nyt,Iran War Live Updates: Truce Hangs in the Bala...,https://www.nytimes.com/live/2026/05/12/world/...,102
227,2026-05-12-00-12-01 +0000,nypost,Pentagon reveals location of secret Navy subma...,https://nypost.com/2026/05/11/us-news/pentagon...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
238,150,2026-05-11-23-24-00 +0000,wsj,President Trump said he supports suspending th...,https://www.wsj.com/politics/policy/federal-ga...
338,62,2026-05-11-18-21-50 +0000,nypost,Hantavirus cruise ship captain bids emotional ...,https://nypost.com/2026/05/11/world-news/hanta...
353,54,2026-05-11-16-39-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
202,51,2026-05-12-02-26-06 +0000,nyt,Starmer Faces Mounting Calls From Own Party to...,https://www.nytimes.com/2026/05/11/world/europ...
5,47,2026-05-12-15-34-00 +0000,wsj,OpenAI’s Sam Altman’s personal investments are...,https://www.wsj.com/tech/ai/sam-altmans-busine...
299,43,2026-05-11-20-30-20 +0000,nypost,Arcadia mayor Eileen Wang admits acting as Chi...,https://nypost.com/2026/05/11/us-news/eileen-w...
230,43,2026-05-12-00-03-27 +0000,nypost,UAE launched secret counter-strike against Ira...,https://nypost.com/2026/05/11/world-news/uae-l...
100,43,2026-05-12-11-12-09 +0000,nypost,Trump heads to China for Xi Jinping summit tha...,https://nypost.com/2026/05/12/us-news/trump-he...
29,42,2026-05-12-14-49-00 +0000,nypost,Hochul forks over another $4B to bail out Mamd...,https://nypost.com/2026/05/12/us-news/hochul-f...
60,37,2026-05-12-13-45-00 +0000,wsj,PayPal agrees to waive $30 million in fees to ...,https://www.wsj.com/politics/policy/paypal-rea...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)