## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-02-42-36 +0000,chitri,Takeaways from Tuesday’s elections: Democrats’...,https://www.chicagotribune.com/2026/08/04/tues...
1,2026-08-05-02-40-03 +0000,startribune,Michigan's Senate Democratic primary is latest...,https://www.startribune.com/michigan-democrats...
2,2026-08-05-02-36-30 +0000,chitri,Lawyers in Reflecting Pool case say Justice De...,https://www.chicagotribune.com/2026/08/04/refl...
3,2026-08-05-02-36-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...
4,2026-08-05-02-35-48 +0000,nypost,Indiana nutjob confessed to biting infant’s fa...,https://nypost.com/2026/08/04/us-news/indiana-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2475/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
126       trump     39
286         new     26
9    democratic     23
6      michigan     23
119        iran     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
239,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...,142
3,2026-08-05-02-36-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...,142
381,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,138
359,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...,119
363,2026-08-04-10-59-00 +0000,wsj,President Trump told embattled Rep. Max Miller...,https://www.wsj.com/politics/elections/trump-w...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
239,142,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
3,119,2026-08-05-02-36-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...
54,101,2026-08-05-00-25-00 +0000,wsj,Oil Falls Amid Prospects of U.S.-Iran Deal to ...,https://www.wsj.com/finance/commodities-future...
183,73,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
388,69,2026-08-04-10-00-00 +0000,latimes,Is Los Angeles the world's best biking city? H...,https://www.latimes.com/lifestyle/story/2026-0...
315,61,2026-08-04-14-44-50 +0000,chitri,"McDonald’s posts strong second quarter profit,...",https://www.chicagotribune.com/2026/08/04/mcdo...
190,55,2026-08-04-20-30-00 +0000,wsj,"What’s Next for Democrats? Join a real-time, ...",https://www.wsj.com/politics/elections/live-q-...
35,53,2026-08-05-01-06-38 +0000,nypost,Rep. Wesley Bell holds off ex-‘Squad’ member C...,https://nypost.com/2026/08/04/us-news/rep-wesl...
69,46,2026-08-05-00-15-00 +0000,wsj,The Trump administration is revoking the visa ...,https://www.wsj.com/politics/policy/u-s-revoke...
124,41,2026-08-04-22-32-46 +0000,latimes,Armed suspect arrested at Trump's Rancho Palos...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)