## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-26-14-19-15 +0000,nyt,"Trump Is Pushing Nuclear Energy, Including Sau...",https://www.nytimes.com/2026/07/26/us/politics...
1,2026-07-26-14-10-56 +0000,nyt,Live Updates: Extreme Heat and Strong Winds Fu...,https://www.nytimes.com/live/2026/07/26/world/...
2,2026-07-26-14-08-31 +0000,bbc,Gatwick Airport left without running water aft...,https://www.bbc.co.uk/news/articles/cdew2dnxlz...
3,2026-07-26-14-06-25 +0000,nyt,Inside the Rushed Effort to Get Trump His New ...,https://www.nytimes.com/2026/07/25/us/politics...
4,2026-07-26-14-00-18 +0000,nyt,"Paul Andrews, Founder of the Woodstock of U.F....",https://www.nytimes.com/2026/07/26/us/paul-and...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     20
61     iran     12
67   attack     11
150  senate     11
58      war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-07-26-13-57-38 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,59
170,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...,59
12,2026-07-26-13-39-44 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,58
172,2026-07-25-15-41-25 +0000,nypost,Maine Dems pick Troy Jackson to replace Graham...,https://nypost.com/2026/07/25/us-news/maine-de...,58
156,2026-07-25-17-10-00 +0000,wsj,Maine Democrats choose Troy Jackson to replace...,https://www.wsj.com/politics/maine-democrats-c...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,59,2026-07-26-13-57-38 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...
170,59,2026-07-25-15-58-00 +0000,wsj,Troy Jackson is taking Graham Platner’s place ...,https://www.wsj.com/politics/elections/maine-s...
10,48,2026-07-26-13-41-50 +0000,nyt,Officials Call Attack Near Berlin Pride Celebr...,https://www.nytimes.com/2026/07/26/world/europ...
23,37,2026-07-26-12-41-43 +0000,nypost,"Cop’s son, 12, ID’d after being shot dead in N...",https://nypost.com/2026/07/26/us-news/jacob-fr...
1,32,2026-07-26-14-10-56 +0000,nyt,Live Updates: Extreme Heat and Strong Winds Fu...,https://www.nytimes.com/live/2026/07/26/world/...
172,26,2026-07-25-15-41-25 +0000,nypost,Maine Dems pick Troy Jackson to replace Graham...,https://nypost.com/2026/07/25/us-news/maine-de...
42,25,2026-07-26-10-00-00 +0000,wsj,A documentary filmmaker followed Sen. Lindsey ...,https://www.wsj.com/politics/national-security...
125,25,2026-07-25-21-01-25 +0000,nypost,"Ukraine strikes set fire to ‘Russia’s Amazon,’...",https://nypost.com/2026/07/25/world-news/ukrai...
41,24,2026-07-26-10-00-13 +0000,chitri,Illinois Democrats’ single-party rule and dimi...,https://www.chicagotribune.com/2026/07/26/harr...
161,22,2026-07-25-16-40-20 +0000,nypost,"Trump hits Gavin Newsom, Kamala Harris with br...",https://nypost.com/2026/07/25/us-news/trump-mo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)