## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-31-20-19-10 +0000,nypost,Fauci walks away when pressed on Fifth Amendme...,https://nypost.com/2026/07/31/us-news/fauci-wa...
1,2026-07-31-20-19-05 +0000,nypost,Calif. Gov. Gavin Newsom’s office urges AG Bon...,https://nypost.com/2026/07/31/media/gavin-news...
2,2026-07-31-20-19-03 +0000,nyt,How the Michigan Primary Is Dividing Jewish Vo...,https://www.nytimes.com/video/us/elections/100...
3,2026-07-31-20-19-00 +0000,nyt,Nancy Guthrie Ransom Notes Released by Sheriff...,https://www.nytimes.com/2026/07/31/us/savannah...
4,2026-07-31-20-15-05 +0000,nypost,Debut novelist’s $2M deal for ‘amazing’ book c...,https://nypost.com/2026/07/31/media/debut-nove...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2531/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
99      trump     44
35        new     18
131      iran     18
265      plan     17
58   migrants     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-07-31-10-23-17 +0000,cbc,Hamas will honour Trump's Gaza peace deal if I...,https://www.cbc.ca/news/world/hamas-israel-dis...,117
324,2026-07-30-23-30-00 +0000,cbc,Trump says 'Board of Peace' reaches deal for H...,https://www.cbc.ca/news/world/board-of-peace-g...,103
41,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,103
337,2026-07-30-22-29-53 +0000,nypost,Trump demands Iran agree to a cease-fire — and...,https://nypost.com/2026/07/30/us-news/cease-fi...,102
177,2026-07-31-13-29-17 +0000,chitri,President Donald Trump announces a deal for Ha...,https://www.chicagotribune.com/2026/07/31/trum...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,117,2026-07-31-10-23-17 +0000,cbc,Hamas will honour Trump's Gaza peace deal if I...,https://www.cbc.ca/news/world/hamas-israel-dis...
343,83,2026-07-30-22-18-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
275,79,2026-07-31-08-02-28 +0000,nypost,At least 18 migrants dead as 49K breached bord...,https://nypost.com/2026/07/31/world-news/at-le...
326,60,2026-07-30-23-07-01 +0000,chitri,European nations vow World Cup boycott and Nor...,https://www.chicagotribune.com/2026/07/30/euro...
166,56,2026-07-31-14-19-00 +0000,wsj,Three Fed policymakers said stubborn inflation...,https://www.wsj.com/economy/central-banking/tw...
118,47,2026-07-31-16-30-24 +0000,nypost,LA gas stations where you can still get cheap ...,https://nypost.com/2026/07/31/business/where-t...
220,46,2026-07-31-11-00-00 +0000,wsj,President Trump’s aggressive immigration push ...,https://www.wsj.com/politics/policy/trumps-imm...
297,44,2026-07-31-03-21-37 +0000,nypost,Netflix star Nirmal Purja among 10 missing aft...,https://nypost.com/2026/07/30/world-news/world...
142,44,2026-07-31-15-39-00 +0000,wsj,New York Sues Kalshi After Talks to Rein In Pr...,https://www.wsj.com/tech/new-york-alleges-kals...
154,42,2026-07-31-14-53-12 +0000,nypost,Sen. Bernie Moreno demands national security p...,https://nypost.com/2026/07/31/us-news/sen-bern...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)