## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-19-53-48 +0000,nypost,California neighbors go ballistic at huge Hind...,https://nypost.com/2026/10/29/us-news/californ...
1,2026-10-29-19-53-00 +0000,wsj,Oil Prices Ease as U.S. Seeks to Renew Diploma...,https://www.wsj.com/business/energy-oil/oil-pr...
2,2026-10-29-19-49-00 +0000,wsj,Treasury Yields Fall Following Major Central B...,https://www.wsj.com/finance/jgb-yields-rise-am...
3,2026-10-29-19-40-58 +0000,missionlocal,Meet the District 8 candidates: Who will you v...,https://missionlocal.org/2026/10/san-francisco...
4,2026-10-29-19-33-06 +0000,nypost,Steve Hilton rips Xavier Becerra’s proposed mi...,https://nypost.com/2026/10/29/us-news/steve-hi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2648/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
67        trump     29
445    election     21
56          new     21
0    california     19
209          up     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
200,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,92
349,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...,89
63,2026-10-29-17-51-41 +0000,nypost,California High-Speed Rail Authority names new...,https://nypost.com/2026/10/29/us-news/gavin-ne...,84
285,2026-10-29-10-00-00 +0000,latimes,A new president takes charge at Caltech as unc...,https://www.latimes.com/california/story/2026-...,84
18,2026-10-29-19-13-00 +0000,wsj,The top U.S. commander in the Middle East brie...,https://www.wsj.com/politics/national-security...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
200,92,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...
63,84,2026-10-29-17-51-41 +0000,nypost,California High-Speed Rail Authority names new...,https://nypost.com/2026/10/29/us-news/gavin-ne...
349,78,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...
357,66,2026-10-29-01-12-00 +0000,wsj,Fed Chairman Kevin Warsh said higher rates are...,https://www.wsj.com/economy/central-banking/th...
244,61,2026-10-29-11-32-00 +0000,wsj,"The Morning Risk Report: Tech, Social Media Co...",https://www.wsj.com/risk-compliance-journal/th...
334,55,2026-10-29-04-44-00 +0000,wsj,"In a comeback attempt, Democrat Keisha Lance B...",https://www.wsj.com/politics/elections/the-ex-...
118,54,2026-10-29-16-13-06 +0000,nypost,Conservative groups warn letting AI giants ‘re...,https://nypost.com/2026/10/29/business/conserv...
47,53,2026-10-29-18-31-56 +0000,missionlocal,Union behind billionaire tax faces strike from...,https://missionlocal.org/2026/10/billionaire-t...
306,51,2026-10-29-09-01-00 +0000,wsj,Most Americans—including many Iranian American...,https://www.wsj.com/politics/elections/i-went-...
368,51,2026-10-29-00-49-53 +0000,nypost,Haley Stevens’ fiancé will vote for Mike Roger...,https://nypost.com/2026/10/28/us-news/haley-st...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)