## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-06-06-11-33 +0000,nyt,China Test Fires Missile in the Pacific for th...,https://www.nytimes.com/2026/07/06/world/asia/...
1,2026-07-06-06-11-29 +0000,bbc,China tests missiles in the Pacific after Aust...,https://www.bbc.co.uk/news/articles/c30yy6jj8p...
2,2026-07-06-06-04-00 +0000,wsj,Continental Agrees to Sell ContiTech Business ...,https://www.wsj.com/business/deals/continental...
3,2026-07-06-06-00-27 +0000,bbc,At least 10 killed in second Russian strikes o...,https://www.bbc.co.uk/news/articles/cewqqnd7zd...
4,2026-07-06-06-00-05 +0000,bbc,Crimea residents describe 'catastrophic' situa...,https://www.bbc.co.uk/news/videos/c2dy21549w1o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
48     trump     15
604  funeral     12
115     july     11
77      iran     11
381   leader     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
81,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...,74
205,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,72
116,2026-07-05-18-20-53 +0000,nypost,Ex-Dem activist Calla Walsh attends Khamenei’s...,https://nypost.com/2026/07/05/world-news/calla...,59
176,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...,53
94,2026-07-05-19-24-13 +0000,nyt,"The Funeral of Iran’s Supreme Leader, Ali Kham...",https://www.nytimes.com/2026/07/04/world/middl...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
81,74,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...
205,72,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...
122,44,2026-07-05-17-52-11 +0000,latimes,"Woman killed, several injured in Fourth of Jul...",https://www.latimes.com/california/story/2026-...
176,34,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...
183,32,2026-07-05-10-00-00 +0000,latimes,"Barabak: Happy Birthday, America! You've weath...",https://www.latimes.com/politics/story/2026-07...
15,29,2026-07-06-04-18-54 +0000,nypost,"Whale strikes, sinks NJ fire rescue ship retur...",https://nypost.com/2026/07/06/us-news/whale-st...
156,28,2026-07-05-13-59-00 +0000,wsj,Germany before World War I provoked backlash b...,https://www.wsj.com/economy/trade/how-to-win-a...
12,26,2026-07-06-04-37-01 +0000,nypost,"Neighbor arrested after girl, 11, vanishes dur...",https://nypost.com/2026/07/06/us-news/neighbor...
21,24,2026-07-06-02-57-11 +0000,nypost,Grown man allegedly whipped 12-year-old boy wi...,https://nypost.com/2026/07/05/us-news/grown-ma...
152,24,2026-07-05-14-37-30 +0000,nypost,Pa. Gov. Josh Shapiro slams socialist NY Dem D...,https://nypost.com/2026/07/05/us-news/pa-gov-j...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)