## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-16-08-04 +0000,nyt,Political Spotlight Shines on Warsh for His Fi...,https://www.nytimes.com/2026/06/17/business/ec...
1,2026-06-17-16-07-31 +0000,nyt,"Who is Kevin Warsh, the Fed’s new chairman?",https://www.nytimes.com/live/2026/06/17/busine...
2,2026-06-17-16-07-07 +0000,nyt,Live Updates: Trump Speaks at G7 Summit After ...,https://www.nytimes.com/live/2026/06/17/world/...
3,2026-06-17-16-07-06 +0000,nyt,Trump Pulls Back Intelligence Pick to Pressure...,https://www.nytimes.com/2026/06/17/us/politics...
4,2026-06-17-16-07-04 +0000,bbc,Streeting is prepared to trigger leadership race,https://www.bbc.com/news/videos/cq617j9eqdgo?a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
12   trump     36
17    iran     25
9      new     17
202   deal     16
72   world     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
309,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...,111
277,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...,102
233,2026-06-17-00-38-52 +0000,nyt,"Mike Collins, Endorsed by Trump, Wins Georgia ...",https://www.nytimes.com/2026/06/16/us/politics...,97
321,2026-06-16-19-53-00 +0000,wsj,The Trump-Iran Deal Allows Tehran to Immediate...,https://www.wsj.com/world/middle-east/the-trum...,96
28,2026-06-17-15-17-00 +0000,wsj,Oil Rises 2% After Trump Says Iran Deal Not Final,https://www.wsj.com/finance/commodities-future...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
309,111,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...
203,84,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
277,75,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
225,62,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
368,58,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
208,57,2026-06-17-02-50-36 +0000,nypost,Bungee instructors who tossed student off 130-...,https://nypost.com/2026/06/16/world-news/bunge...
70,51,2026-06-17-13-53-52 +0000,nypost,Dana White reveals that there were multiple th...,https://nypost.com/2026/06/17/us-news/dana-whi...
236,46,2026-06-17-00-27-30 +0000,cbc,"Erling Haaland scores twice, adds assist in Wo...",https://www.cbc.ca/sports/soccer/worldcup/fifa...
76,45,2026-06-17-13-41-21 +0000,bbc,'It was surreal': British couple describe havi...,https://www.bbc.com/news/articles/c20yzm84r7lo...
124,39,2026-06-17-11-00-00 +0000,wsj,Vice President JD Vance has been all over the ...,https://www.wsj.com/politics/can-vance-sell-th...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)