## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-22-50-29 +0000,nypost,Low testosterone crisis in American men could ...,https://nypost.com/2026/10/24/us-news/testoste...
1,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...
2,2026-10-24-22-41-56 +0000,startribune,Live: Gophers and Iowa are tied late. Who will...,https://www.startribune.com/minnesota-gophers-...
3,2026-10-24-22-41-27 +0000,nypost,NYC coffee shop serves up pumpkin spice lattes...,https://nypost.com/2026/10/24/us-news/queens-c...
4,2026-10-24-22-38-48 +0000,nyt,New York Archdiocese Agrees to Settle Sexual A...,https://www.nytimes.com/2026/10/24/us/archdioc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2834/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
7         trump     25
104    election     13
192      france     12
78   california     10
31           up      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,69
15,2026-10-24-21-58-08 +0000,bbc,Obama attacks Trump as he campaigns for Democr...,https://www.bbc.co.uk/news/articles/cmj6jwe1j1...,57
168,2026-10-24-07-17-44 +0000,bbc,White House says Melania Trump brokered truce ...,https://www.bbc.co.uk/news/articles/c6vgxkvl4w...,57
44,2026-10-24-19-21-11 +0000,nyt,Alaska Election Gambit Shows Justice Dept. Has...,https://www.nytimes.com/2026/10/24/us/politics...,54
173,2026-10-24-05-31-01 +0000,bbc,"Minneapolis withdrawal was 'surrender', Trump'...",https://www.bbc.co.uk/news/articles/ck20rery78...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,69,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...
60,47,2026-10-24-17-45-16 +0000,nyt,Netanyahu Is Up for Re-election After Years of...,https://www.nytimes.com/2026/10/24/world/middl...
192,47,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
34,46,2026-10-24-20-23-36 +0000,chitri,Elon Musk says he was behind Starlink speed re...,https://www.chicagotribune.com/2026/10/24/musk...
99,36,2026-10-24-13-33-23 +0000,chitri,France mobilizes thousands of police to curb v...,https://www.chicagotribune.com/2026/10/24/fran...
193,35,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
117,35,2026-10-24-11-14-00 +0000,wsj,Democrats weigh impeaching Defense Secretary P...,https://www.wsj.com/politics/the-ultrawealthy-...
48,27,2026-10-24-19-16-21 +0000,nypost,NFL House in Paris closes ahead of Saints-Stee...,https://nypost.com/2026/10/24/sports/nfl-house...
144,27,2026-10-24-09-32-00 +0000,wsj,Watch as sailors in the USS George Washington ...,https://www.wsj.com/politics/national-security...
171,27,2026-10-24-06-21-06 +0000,nyt,Justice Dept. Demands That California Counties...,https://www.nytimes.com/2026/10/23/us/justice-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)