## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-28-18-57-48 +0000,nypost,Workers free kittens from shredder that could ...,https://nypost.com/2026/09/28/us-news/workers-...
1,2026-09-28-18-55-00 +0000,wsj,Trump Unveils $15 Billion Iowa Steel Project,https://www.wsj.com/politics/trump-to-unveil-p...
2,2026-09-28-18-55-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...
3,2026-09-28-18-48-44 +0000,nyt,Proud Boys Convicted Over Jan. 6 Go From Prose...,https://www.nytimes.com/2026/09/28/us/politics...
4,2026-09-28-18-46-52 +0000,nypost,Viral student from Florida-Ole Miss game outs ...,https://nypost.com/2026/09/28/sports/viral-stu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2270/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
11        trump     36
377          uk     14
112         new     13
117  california     12
52         iran     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
55,2026-09-28-17-10-56 +0000,nypost,Oil soars above $107 after Trump rejects Iran ...,https://nypost.com/2026/09/28/business/oil-soa...,75
122,2026-09-28-14-42-43 +0000,nypost,White House reporters predict which Republican...,https://nypost.com/2026/09/28/media/white-hous...,75
2,2026-09-28-18-55-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...,73
263,2026-09-28-01-00-00 +0000,wsj,Trump came into office promising to fix the ec...,https://www.wsj.com/economy/trump-economy-infl...,71
286,2026-09-27-21-30-41 +0000,nypost,Trump asked China’s Xi Jinping if he’d ‘like t...,https://nypost.com/2026/09/27/us-news/trump-as...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
55,75,2026-09-28-17-10-56 +0000,nypost,Oil soars above $107 after Trump rejects Iran ...,https://nypost.com/2026/09/28/business/oil-soa...
23,65,2026-09-28-18-06-02 +0000,nypost,New York Times tech exec shot dead by in-laws ...,https://nypost.com/2026/09/28/us-news/nyt-exec...
123,55,2026-09-28-14-42-32 +0000,nypost,Five British nationals already out on bail aft...,https://nypost.com/2026/09/28/world-news/five-...
130,53,2026-09-28-14-22-00 +0000,wsj,Inflation in the eurozone is expected to rise ...,https://www.wsj.com/economy/central-banking/eu...
181,43,2026-09-28-11-01-00 +0000,wsj,We’ll explore what could happen if the Republi...,https://www.wsj.com/politics/heres-what-could-...
105,43,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
308,38,2026-09-27-19-55-07 +0000,cbc,McNulty first American to win elite road race ...,https://www.cbc.ca/sports/olympics/summer/cycl...
152,36,2026-09-28-13-07-00 +0000,wsj,Ahead of the release of his book “This Cursed ...,https://www.wsj.com/world/how-evan-gershkovich...
253,34,2026-09-28-03-44-18 +0000,latimes,Brokers gobble up tee times at public golf cou...,https://www.latimes.com/california/story/2026-...
175,31,2026-09-28-11-26-09 +0000,nypost,New map shows how key midterm states hit by US...,https://nypost.com/2026/09/28/us-news/new-map-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)