## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-20-14-20-30 +0000,bbc,Another flight leaves passengers behind due to...,https://www.bbc.com/news/articles/cvg3xzxpv32o...
1,2026-04-20-14-16-57 +0000,nypost,"Wealthy tourist, 21, allegedly stabs boat capt...",https://nypost.com/2026/04/20/us-news/wealthy-...
2,2026-04-20-14-16-56 +0000,nyt,A Decisive Win Raises Bulgarians’ Hopes for Ch...,https://www.nytimes.com/2026/04/20/world/europ...
3,2026-04-20-14-16-52 +0000,nypost,"Stocks fall, oil surges after US seizes cargo ...",https://nypost.com/2026/04/20/business/stocks-...
4,2026-04-20-14-16-49 +0000,nypost,House Oversight panel probes missing or dead n...,https://nypost.com/2026/04/20/us-news/house-ov...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
123    trump     19
63      iran     18
143      new     12
50   iranian     12
29       oil      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
28,2026-04-20-13-22-31 +0000,nypost,Trump brushes off Iran’s claims it won’t parti...,https://nypost.com/2026/04/20/us-news/jd-vance...,73
203,2026-04-19-19-06-10 +0000,nypost,Iran refuses to join latest round of peace tal...,https://nypost.com/2026/04/19/world-news/iran-...,72
225,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...,66
67,2026-04-20-11-23-04 +0000,bbc,Oil prices rise after Trump says Iranian ship ...,https://www.bbc.com/news/articles/c5yjzy35825o...,62
196,2026-04-19-19-46-22 +0000,nypost,US Navy destroyer ‘blows a hole’ through Irani...,https://nypost.com/2026/04/19/world-news/us-na...,61

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
28,73,2026-04-20-13-22-31 +0000,nypost,Trump brushes off Iran’s claims it won’t parti...,https://nypost.com/2026/04/20/us-news/jd-vance...
225,47,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
67,43,2026-04-20-11-23-04 +0000,bbc,Oil prices rise after Trump says Iranian ship ...,https://www.bbc.com/news/articles/c5yjzy35825o...
169,35,2026-04-19-23-07-52 +0000,bbc,'They told me he was dead': Children born near...,https://www.bbc.com/news/articles/c895k3537kgo...
22,33,2026-04-20-13-34-01 +0000,nyt,Vance Heads to New Talks With Iran. At Stake: ...,https://www.nytimes.com/2026/04/20/us/politics...
140,32,2026-04-20-05-24-03 +0000,nypost,Louisiana shooter Shamar Elkins made chilling ...,https://nypost.com/2026/04/20/us-news/louisian...
11,29,2026-04-20-14-00-14 +0000,nypost,Sable Offshore issues battle cry after Santa B...,https://nypost.com/2026/04/20/us-news/sable-of...
78,29,2026-04-20-10-58-00 +0000,wsj,There will be a lot of noise in the next few d...,https://www.wsj.com/politics/heres-what-to-kno...
136,29,2026-04-20-06-49-57 +0000,nypost,Marathon runner celebrates ‘win’ too early — j...,https://nypost.com/2026/04/20/us-news/delaware...
101,29,2026-04-20-10-00-00 +0000,wsj,Wheels Up Wants High-End Travelers to See Flyi...,https://www.wsj.com/business/airlines/wheels-u...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)