## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-09-20-54-35 +0000,nypost,$114M SoCal wildlife crossing to track whether...,https://nypost.com/2026/10/09/us-news/114m-cal...
1,2026-10-09-20-51-20 +0000,nyt,7.7-Magnitude Panama Earthquake Sets Off Serie...,https://www.nytimes.com/2026/10/09/world/ameri...
2,2026-10-09-20-51-00 +0000,wsj,U.S. Stocks Rise as Iran Escalation Fears Subside,https://www.wsj.com/finance/stocks/u-s-stocks-...
3,2026-10-09-20-48-53 +0000,nypost,Trump-backed Lukoil bid aims to restart refine...,https://nypost.com/2026/10/09/us-news/trump-ba...
4,2026-10-09-20-45-00 +0000,wsj,Trump Says He Has Struck Deal With Putin for R...,https://www.wsj.com/politics/policy/trump-stri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
23   trump     45
61     new     26
339  prize     21
337  nobel     19
338  peace     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
160,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...,140
421,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...,137
32,2026-10-09-20-20-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...,132
413,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...,127
105,2026-10-09-17-37-10 +0000,bbc,South Africa's Navi Pillay wins Nobel Peace Pr...,https://www.bbc.co.uk/news/articles/cm9wz5kng0...,126

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
160,140,2026-10-09-15-13-31 +0000,nypost,Trump boosts statement calling Nobel Peace Pri...,https://nypost.com/2026/10/09/us-news/trump-bo...
335,123,2026-10-09-02-51-00 +0000,wsj,Democrat Abdul El-Sayed and Republican Mike Ro...,https://www.wsj.com/politics/policy/abdul-el-s...
421,92,2026-10-08-21-05-33 +0000,nyt,Trump Says U.S. Will Not Strike Iran Again Bef...,https://www.nytimes.com/2026/10/08/us/politics...
413,82,2026-10-08-21-28-00 +0000,wsj,The Trump administration is suspending tech fi...,https://www.wsj.com/politics/policy/trump-admi...
202,69,2026-10-09-13-45-19 +0000,nypost,DHS boss rips Mamdani’s ‘dangerous’ words and ...,https://nypost.com/2026/10/09/us-news/trump-dh...
32,61,2026-10-09-20-20-00 +0000,wsj,"President Trump has appointed Katie Zacharia, ...",https://www.wsj.com/politics/policy/katie-zach...
133,56,2026-10-09-16-29-36 +0000,nypost,Trump backs firing squad execution of Fort Hoo...,https://nypost.com/2026/10/09/us-news/trump-ba...
340,55,2026-10-09-02-29-35 +0000,nypost,Outraged Susan Collins demands apology after r...,https://nypost.com/2026/10/08/us-news/susan-co...
182,52,2026-10-09-14-30-42 +0000,nypost,Rubio slaps fresh sanctions on ‘rogue’ Interna...,https://nypost.com/2026/10/09/us-news/rubio-sl...
26,46,2026-10-09-20-27-00 +0000,wsj,President Trump has formed a committee to eval...,https://www.wsj.com/economy/central-banking/tr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)