## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-26-16-15-17 +0000,nyt,Trump Administration Wants Billion-Dollar Busi...,https://www.nytimes.com/2026/08/26/business/ec...
1,2026-08-26-16-11-07 +0000,nyt,Live Updates: At Least 95 Killed and Hundreds ...,https://www.nytimes.com/live/2026/08/26/world/...
2,2026-08-26-16-10-43 +0000,nypost,California fruit giant in chaos as CEO steps d...,https://nypost.com/2026/08/26/business/califor...
3,2026-08-26-16-04-50 +0000,nypost,Ashley Flowers’ ‘Crime Junkie’ empire in turmo...,https://nypost.com/2026/08/26/media/ashley-flo...
4,2026-08-26-16-04-22 +0000,nyt,"Mike Mazzei, Backed by Trump, Wins Oklahoma Pr...",https://www.nytimes.com/2026/08/25/us/election...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2513/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     46
116       dolly     21
388      canada     20
117      parton     20
18   california     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
223,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...,150
190,2026-08-26-09-03-57 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,136
240,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...,130
228,2026-08-26-03-02-19 +0000,nyt,Canada Fires Back in Trade War Against Trump W...,https://www.nytimes.com/2026/08/25/world/canad...,124
401,2026-08-25-16-25-46 +0000,wapo,Trump says U.S. could rename Lake Ontario as L...,https://www.washingtonpost.com/politics/2026/0...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
223,150,2026-08-26-04-14-00 +0000,wsj,Sen. Darline Graham won South Carolina’s Repub...,https://www.wsj.com/politics/elections/trump-s...
182,98,2026-08-26-09-30-00 +0000,wsj,Kevin Warsh faces his biggest audience this we...,https://www.wsj.com/economy/central-banking/th...
240,84,2026-08-26-01-34-23 +0000,cbc,California governor 'absolutely' believes Trum...,https://www.cbc.ca/news/politics/trump-gavin-n...
390,78,2026-08-25-17-06-00 +0000,wsj,CIA Director John Ratcliffe made a surprise vi...,https://www.wsj.com/world/cia-director-john-ra...
233,70,2026-08-26-02-09-21 +0000,nyt,Dolly Parton’s Death Hits Home for Tennesseans...,https://www.nytimes.com/2026/08/25/us/nashvill...
70,65,2026-08-26-14-11-46 +0000,chitri,Meta reaches $17 billion settlement with state...,https://www.chicagotribune.com/2026/08/26/meta...
106,58,2026-08-26-12-50-33 +0000,chitri,Iran warns of military ship ban in Hormuz unde...,https://www.chicagotribune.com/2026/08/26/iran...
112,58,2026-08-26-12-37-13 +0000,nypost,Harrowing footage shows moment flood hits Chin...,https://nypost.com/2026/08/26/world-news/flood...
400,47,2026-08-25-16-29-51 +0000,chitri,Ex-Loretto Hospital CEO gets diversion deal am...,https://www.chicagotribune.com/2026/08/25/ex-l...
186,43,2026-08-26-09-24-52 +0000,nyt,Supreme Court Ruling on Mail-In Voting Could A...,https://www.nytimes.com/2026/08/25/us/mail-in-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)