## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-01-36-32 +0000,nypost,LA donut shop customer faces murder charges af...,https://nypost.com/2026/06/03/us-news/la-donut...
1,2026-06-04-01-33-35 +0000,nypost,"Mamdani-backed, socialist House candidate Clai...",https://nypost.com/2026/06/03/us-news/mamdani-...
2,2026-06-04-01-23-00 +0000,wsj,Dollar Likely Supported by Sticky U.S. Inflati...,https://www.wsj.com/finance/currencies/dollar-...
3,2026-06-04-01-21-11 +0000,nypost,Pilot allegedly dive bombs over crowded South ...,https://nypost.com/2026/06/03/us-news/pilot-al...
4,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2503/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
44       trump     47
51        iran     27
87  california     22
59         new     20
50         war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
74,2026-06-03-22-33-00 +0000,wsj,GOP-led House voted to restrict President Trum...,https://www.wsj.com/politics/gop-led-house-vot...,195
36,2026-06-03-23-46-00 +0000,wsj,"In a 215-208 vote, the House of Representative...",https://www.wsj.com/politics/how-each-member-o...,157
81,2026-06-03-22-07-07 +0000,nypost,House defies Trump and passes war powers resol...,https://nypost.com/2026/06/03/us-news/house-de...,149
87,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,145
67,2026-06-03-22-55-02 +0000,startribune,House approves war powers resolution to halt m...,https://www.startribune.com/house-again-consid...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
74,195,2026-06-03-22-33-00 +0000,wsj,GOP-led House voted to restrict President Trum...,https://www.wsj.com/politics/gop-led-house-vot...
300,95,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
92,83,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
119,82,2026-06-03-20-56-06 +0000,nypost,How CBS News boss Bari Weiss finally reached h...,https://nypost.com/2026/06/03/media/how-cbs-ne...
264,60,2026-06-03-13-04-26 +0000,bbc,He was a reality show villain. Can he be the m...,https://www.bbc.com/news/articles/c775x852rk1o...
199,52,2026-06-03-17-06-25 +0000,cbc,Ukrainian drones hit St. Petersburg oil termin...,https://www.cbc.ca/news/world/ukraine-drones-s...
200,50,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...
349,47,2026-06-03-03-37-49 +0000,latimes,L.A. Mayor Bass will face either Spencer Pratt...,https://www.latimes.com/california/story/2026-...
19,45,2026-06-04-00-39-01 +0000,missionlocal,Two found dead on San Francisco streets Wednes...,https://missionlocal.org/2026/06/two-found-dea...
339,39,2026-06-03-04-33-25 +0000,missionlocal,Lopsided early S.F. election results: Big lead...,https://missionlocal.org/2026/06/san-francisco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)