## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-04-20-53-34 +0000,nypost,Ukraine used record 7K robot operations to fig...,https://nypost.com/2026/04/04/world-news/ukrai...
1,2026-04-04-20-52-05 +0000,nypost,Outraged airline passengers left stranded on f...,https://nypost.com/2026/04/04/world-news/outra...
2,2026-04-04-20-45-15 +0000,nyt,Iran War Live Updates: U.S. Races to Find Miss...,https://www.nytimes.com/live/2026/04/04/world/...
3,2026-04-04-20-24-12 +0000,wapo,U.S. races to find missing airman as Iranian T...,https://www.washingtonpost.com/national-securi...
4,2026-04-04-20-17-02 +0000,latimes,Trump administration arrests relatives of dead...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
32        trump     38
23         iran     29
24          war     14
268         new     13
158  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-04-20-45-15 +0000,nyt,Iran War Live Updates: U.S. Races to Find Miss...,https://www.nytimes.com/live/2026/04/04/world/...,117
5,2026-04-04-20-15-02 +0000,startribune,Trump gives Iran 48 hours to open Strait of Ho...,https://www.startribune.com/us-presses-search-...,104
78,2026-04-04-14-30-58 +0000,nypost,Trump warns Iran has two days to open Strait o...,https://nypost.com/2026/04/04/us-news/trump-wa...,95
49,2026-04-04-17-29-57 +0000,nyt,"Trump Pledged a Quick End to the Iran War, but...",https://www.nytimes.com/2026/04/04/us/politics...,92
169,2026-04-04-00-02-20 +0000,nyt,War With Iran Clarifies Trump’s Spending Prior...,https://www.nytimes.com/2026/04/02/us/politics...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,117,2026-04-04-20-45-15 +0000,nyt,Iran War Live Updates: U.S. Races to Find Miss...,https://www.nytimes.com/live/2026/04/04/world/...
46,37,2026-04-04-17-42-39 +0000,nypost,Gavin Newsom to spend $19M in taxpayer funds o...,https://nypost.com/2026/04/04/us-news/gavin-ne...
172,30,2026-04-04-00-00-00 +0000,wsj,These AI Whiz Kids Dropped Out of College and ...,https://www.wsj.com/tech/ai/ai-college-dropout...
54,29,2026-04-04-16-54-30 +0000,nypost,Artemis II astronauts are more than halfway to...,https://nypost.com/2026/04/04/world-news/artem...
75,28,2026-04-04-15-21-52 +0000,nypost,"Niece, grandniece of slain notorious Iranian G...",https://nypost.com/2026/04/04/us-news/ice-arre...
188,27,2026-04-03-21-58-08 +0000,nyt,"Iran Shoots Down U.S. Fighter Jet, Setting Off...",https://www.nytimes.com/2026/04/03/world/middl...
11,26,2026-04-04-19-46-55 +0000,nypost,NYC mom of two ID’d after being killed by Broo...,https://nypost.com/2026/04/04/us-news/the-hosp...
68,26,2026-04-04-16-22-06 +0000,nypost,Hail Mary to resurrect beloved Queens church r...,https://nypost.com/2026/04/04/us-news/hail-mar...
71,24,2026-04-04-15-44-35 +0000,cbc,Virginia Giuffre's family 'strongly' urges Kin...,https://www.cbc.ca/news/world/virginia-giuffre...
134,24,2026-04-04-08-15-47 +0000,nypost,Three men charged over arson attack on Jewish ...,https://nypost.com/2026/04/04/world-news/uk-ch...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)