## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-16-00-00 +0000,wsj,Why Ukraine Is Ramping Up Its Aerial War Again...,https://www.wsj.com/world/why-ukraine-is-rampi...
1,2026-08-18-15-54-52 +0000,nyt,Judge Releases Woman Accused of Vandalizing Wo...,https://www.nytimes.com/2026/08/18/us/politics...
2,2026-08-18-15-51-00 +0000,wsj,Oil Futures Rise as Trump Says No Iran Talks S...,https://www.wsj.com/finance/commodities-future...
3,2026-08-18-15-47-14 +0000,chitri,CTA adding bus service to some routes starting...,https://www.chicagotribune.com/2026/08/18/cta-...
4,2026-08-18-15-39-46 +0000,nyt,"‘Posh George,’ the Convicted Fraudster in Nige...",https://www.nytimes.com/2026/08/17/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2626/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
18   trump     45
20    iran     20
142    new     15
2       up     15
426  house     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
35,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...,109
252,2026-08-17-21-20-35 +0000,wapo,"60 days after signing Iran deal, Trump stuck i...",https://www.washingtonpost.com/politics/2026/0...,96
308,2026-08-17-18-39-39 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,95
2,2026-08-18-15-51-00 +0000,wsj,Oil Futures Rise as Trump Says No Iran Talks S...,https://www.wsj.com/finance/commodities-future...,91
50,2026-08-18-13-47-18 +0000,nypost,"Trump says Strait of Hormuz has been de-mined,...",https://nypost.com/2026/08/18/us-news/trump-sa...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
35,109,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...
309,57,2026-08-17-18-32-30 +0000,nypost,House Ethics panel probing Dem Rep. Jimmy Gome...,https://nypost.com/2026/08/17/us-news/house-et...
334,54,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
99,45,2026-08-18-11-02-53 +0000,cbc,Russian missile attack in Kharkiv kills at lea...,https://www.cbc.ca/news/world/ukraine-war-1638...
174,43,2026-08-18-05-24-15 +0000,bbc,Tupac murder trial: 'All hell broke loose' nig...,https://www.bbc.co.uk/news/articles/cp3r0kz775...
43,38,2026-08-18-14-08-25 +0000,nypost,Warrant issued for Jill Stein after ex-preside...,https://nypost.com/2026/08/18/us-news/warrant-...
45,37,2026-08-18-14-05-01 +0000,nypost,Teen Camilla Fuentes goes missing just days be...,https://nypost.com/2026/08/18/us-news/teen-cam...
284,37,2026-08-17-20-03-42 +0000,chitri,Trump administration briefly pauses contentiou...,https://www.chicagotribune.com/2026/08/17/big-...
180,36,2026-08-18-04-16-42 +0000,bbc,Why Indian law students don't want top judge a...,https://www.bbc.co.uk/news/articles/c171j0k74d...
42,35,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)