## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-15-00-00 +0000,wsj,"U.S. Consumer Brands Say Chicken, Soap and Sna...",https://www.wsj.com/business/hospitality/u-s-c...
1,2026-08-09-14-59-44 +0000,nypost,"AOC starts process of freezing her eggs, hints...",https://nypost.com/2026/08/09/us-news/aoc-star...
2,2026-08-09-14-58-00 +0000,wsj,Alleged Irish Crime Boss Extradited from U.A.E...,https://www.wsj.com/world/europe/alleged-irish...
3,2026-08-09-14-57-00 +0000,wsj,Blockbuster Earnings Bolster Stocks’ Record Run,https://www.wsj.com/finance/stocks/blockbuster...
4,2026-08-09-14-52-48 +0000,wapo,"After bitter primary, El-Sayed faces daunting ...",https://www.washingtonpost.com/politics/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
106   trump     19
41     iran     11
44   hormuz      8
104  israel      8
60     plan      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
26,2026-08-09-13-10-42 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,63
56,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...,56
25,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/us-news/israel-r...,53
14,2026-08-09-14-18-10 +0000,bbc,"Israel rejects Trump's 15-point plan for Gaza,...",https://www.bbc.co.uk/news/articles/c5yw4lpe0y...,52
34,2026-08-09-12-57-23 +0000,nyt,Israel Rejects Trump’s 15-Point Plan to Disarm...,https://www.nytimes.com/2026/08/09/world/middl...,51

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
26,63,2026-08-09-13-10-42 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
139,39,2026-08-08-19-04-41 +0000,nyt,"Iran Issues List of Demands, Dampening Hopes o...",https://www.nytimes.com/2026/08/08/world/middl...
163,35,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
90,32,2026-08-09-04-06-37 +0000,nypost,"Two dead, including an infant, after boat caps...",https://nypost.com/2026/08/09/us-news/boat-ove...
13,29,2026-08-09-14-18-19 +0000,nyt,Obama and Abdul El-Sayed Spoke to Discuss Unit...,https://www.nytimes.com/2026/08/09/us/politics...
88,29,2026-08-09-06-10-47 +0000,nypost,Indian national allegedly killed Arizona girlf...,https://nypost.com/2026/08/09/us-news/indian-n...
42,24,2026-08-09-12-24-04 +0000,cbc,14-year-old accused in deadly school shooting ...,https://www.cbc.ca/news/world/accused-thai-sch...
10,22,2026-08-09-14-34-50 +0000,nypost,Port Washington two wins from Little League Wo...,https://nypost.com/2026/08/09/sports/port-wash...
22,19,2026-08-09-13-29-23 +0000,nypost,LI stripper sues doctor who sought restraining...,https://nypost.com/2026/08/09/us-news/li-strip...
166,19,2026-08-08-15-56-39 +0000,bbc,Trump's ex-lawyer Todd Blanche narrowly confir...,https://www.bbc.co.uk/news/articles/cewr898jy8...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)