## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-17-14-00-00 +0000,nypost,Insidious way cop-hating activists hijacked ca...,https://nypost.com/2026/06/17/us-news/national...
1,2026-06-17-13-58-01 +0000,nyt,Live Updates: After G7 Leaders Praise U.S.-Ira...,https://www.nytimes.com/live/2026/06/17/world/...
2,2026-06-17-13-55-00 +0000,wsj,Tech Stocks Advance as Investors Await Rate De...,https://www.wsj.com/finance/stocks/oil-below-8...
3,2026-06-17-13-54-10 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/17/world/...
4,2026-06-17-13-53-52 +0000,nypost,Dana White reveals there were multiple threats...,https://nypost.com/2026/06/17/us-news/dana-whi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19   trump     33
17    iran     23
66     new     20
18    deal     17
131     up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-06-17-13-58-01 +0000,nyt,Live Updates: After G7 Leaders Praise U.S.-Ira...,https://www.nytimes.com/live/2026/06/17/world/...,109
236,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...,103
269,2026-06-16-20-28-00 +0000,wsj,Many of the hawkish conservatives who rushed t...,https://www.wsj.com/politics/policy/trump-iran...,103
66,2026-06-17-11-00-00 +0000,wsj,Vice President JD Vance has been all over the ...,https://www.wsj.com/politics/can-vance-sell-th...,96
189,2026-06-17-00-38-52 +0000,nyt,"Mike Collins, Endorsed by Trump, Wins Georgia ...",https://www.nytimes.com/2026/06/16/us/politics...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,109,2026-06-17-13-58-01 +0000,nyt,Live Updates: After G7 Leaders Praise U.S.-Ira...,https://www.nytimes.com/live/2026/06/17/world/...
158,87,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
236,77,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
334,62,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
181,61,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
163,61,2026-06-17-02-50-36 +0000,nypost,Bungee instructors who tossed student off 130-...,https://nypost.com/2026/06/16/world-news/bunge...
4,51,2026-06-17-13-53-52 +0000,nypost,Dana White reveals there were multiple threats...,https://nypost.com/2026/06/17/us-news/dana-whi...
332,46,2026-06-16-16-53-20 +0000,latimes,Iranians divided on war unite to watch the Wor...,https://www.latimes.com/california/story/2026-...
12,41,2026-06-17-13-41-21 +0000,bbc,'It was surreal': British couple describe havi...,https://www.bbc.com/news/articles/c20yzm84r7lo...
43,39,2026-06-17-12-14-43 +0000,cbc,Iran-U.S. agreement leaks reveal plans to reop...,https://www.cbc.ca/news/world/iran-us-war-memo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)