## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-18-07-11-29 +0000,bbc,Iran war sees holidaymakers stay closer to home,https://www.bbc.com/news/articles/c1eq2xvlg9wo...
1,2026-04-18-06-51-28 +0000,wapo,Iran disputes claims of new agreements with Trump,https://www.washingtonpost.com/world/2026/04/1...
2,2026-04-18-06-49-59 +0000,nypost,Trump says first releases from Pentagon UFO st...,https://nypost.com/2026/04/18/us-news/trump-sa...
3,2026-04-18-06-48-13 +0000,nyt,Hopes for Peace Deal Rise After Iran Says Stra...,https://www.nytimes.com/live/2026/04/17/world/...
4,2026-04-18-06-39-03 +0000,nypost,Georgia Navy vet ‘had argument with roommate’ ...,https://nypost.com/2026/04/18/us-news/georgia-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     33
0     iran     31
8      new     22
25  strait     13
23    deal     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
101,2026-04-17-21-50-49 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,100
265,2026-04-17-13-17-05 +0000,nypost,Strait of Hormuz ‘completely open’ as Trump ce...,https://nypost.com/2026/04/17/world-news/strai...,97
100,2026-04-17-21-51-49 +0000,nyt,"Amid Conflicting Messages From Trump and Iran,...",https://www.nytimes.com/2026/04/17/world/middl...,97
8,2026-04-18-06-06-38 +0000,bbc,Oil prices plunge as Iran says Strait of Hormu...,https://www.bbc.com/news/articles/ckg045z73z1o...,96
305,2026-04-17-09-50-42 +0000,nyt,Trump says he might go to Pakistan if an Iran ...,https://www.nytimes.com/live/2026/04/17/world/...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
101,100,2026-04-17-21-50-49 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...
316,76,2026-04-17-09-00-12 +0000,nyt,Trump Tries to Stop Drug Smuggling From South ...,https://www.nytimes.com/2026/04/17/world/ameri...
95,52,2026-04-17-22-19-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota said s...,https://www.wsj.com/politics/policy/ilhan-omar...
204,47,2026-04-17-16-33-34 +0000,nypost,Anthropic CEO Dario Amodei set to meet White H...,https://nypost.com/2026/04/17/business/anthrop...
166,43,2026-04-17-18-45-40 +0000,nyt,Lutnick Says Canada Trade Deal Needs to Be Rew...,https://www.nytimes.com/2026/04/17/world/canad...
133,42,2026-04-17-20-29-00 +0000,wsj,The DOJ is preparing to file an antitrust laws...,https://www.wsj.com/politics/policy/justice-de...
263,38,2026-04-17-13-30-00 +0000,nypost,Trump rips Mayor Mamdani for ‘destroying’ NYC ...,https://nypost.com/2026/04/17/us-news/trump-ri...
60,38,2026-04-18-00-33-49 +0000,nypost,Long Beach Grand Prix hits full throttle this ...,https://nypost.com/2026/04/17/us-news/long-bea...
288,33,2026-04-17-10-46-15 +0000,nypost,UK PM Keir Starmer under pressure to quit over...,https://nypost.com/2026/04/17/world-news/uk-pm...
193,33,2026-04-17-17-07-00 +0000,wsj,"World leaders, bankers and investors who conve...",https://www.wsj.com/economy/global/iran-war-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)