## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-18-01-13-05 +0000,nypost,Cold front to follow record heat across the Ea...,https://nypost.com/2026/04/17/us-news/cold-fro...
1,2026-04-18-01-03-38 +0000,nyt,Iran War Live Updates: Hopes for Peace Deal Ri...,https://www.nytimes.com/live/2026/04/17/world/...
2,2026-04-18-01-03-00 +0000,nyt,Lebanon Cease-Fire and Hormuz ‘Opening’ Raise ...,https://www.nytimes.com/2026/04/17/us/strait-o...
3,2026-04-18-01-00-00 +0000,wsj,High earners are embracing thriftiness—unless ...,https://www.wsj.com/economy/skimp-on-yogurt-sp...
4,2026-04-18-01-00-00 +0000,wsj,"Skimp on Yogurt, Splurge on Skydiving: The Ris...",https://www.wsj.com/economy/skimp-on-yogurt-sp...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
48     trump     31
9       iran     30
273      new     22
19   lebanon     14
10       war     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-18-01-03-38 +0000,nyt,Iran War Live Updates: Hopes for Peace Deal Ri...,https://www.nytimes.com/live/2026/04/17/world/...,122
57,2026-04-17-21-50-49 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,99
307,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,96
56,2026-04-17-21-51-49 +0000,nyt,"Amid Conflicting Messages From Trump and Iran,...",https://www.nytimes.com/2026/04/17/world/middl...,94
298,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,122,2026-04-18-01-03-38 +0000,nyt,Iran War Live Updates: Hopes for Peace Deal Ri...,https://www.nytimes.com/live/2026/04/17/world/...
298,94,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...
205,67,2026-04-17-14-54-56 +0000,nyt,New York New Jersey Stadium? Why MetLife Is Ch...,https://www.nytimes.com/2026/04/17/nyregion/fi...
309,62,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
51,47,2026-04-17-22-19-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota said s...,https://www.wsj.com/politics/policy/ilhan-omar...
297,41,2026-04-17-07-39-00 +0000,wsj,"Todd Lyons, the acting director of ICE who ove...",https://www.wsj.com/politics/policy/ice-acting...
66,40,2026-04-17-21-41-01 +0000,bbc,Oil prices plunge as Iran says Strait of Hormu...,https://www.bbc.com/news/articles/ckg045z73z1o...
10,38,2026-04-18-00-33-49 +0000,nypost,Long Beach Grand Prix hits full throttle this ...,https://nypost.com/2026/04/17/us-news/long-bea...
170,37,2026-04-17-16-33-34 +0000,nypost,Anthropic CEO Dario Amodei set to meet White H...,https://nypost.com/2026/04/17/business/anthrop...
88,35,2026-04-17-20-51-57 +0000,nypost,Accused Charlie Kirk killer Tyler Robinson in ...,https://nypost.com/2026/04/17/us-news/accused-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)