## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-26-18-34-34 +0000,nyt,Ken Paxton has a history of winning primaries ...,https://www.nytimes.com/live/2026/05/26/us/tex...
1,2026-05-26-18-31-00 +0000,wsj,Mamdani Says These NYC Landlords Will Be Exemp...,https://www.wsj.com/real-estate/mamdani-says-t...
2,2026-05-26-18-30-02 +0000,startribune,Could St. Paul have July 4 fireworks for the f...,https://www.startribune.com/st-paul-fireworks-...
3,2026-05-26-18-28-00 +0000,wsj,Lawyer for Former JPMorgan Banker Resigns Ahea...,https://www.wsj.com/finance/lawyer-for-former-...
4,2026-05-26-18-26-37 +0000,nyt,"Ben Morea, Principal Provocateur of 1960s Anar...",https://www.nytimes.com/2026/05/26/us/ben-more...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2628/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
57     iran     35
74    trump     22
64  strikes     17
19    first     13
68     deal     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-05-26-18-17-13 +0000,nyt,Iran War Live Updates: U.S. Said to Observe Th...,https://www.nytimes.com/live/2026/05/26/world/...,104
174,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,100
166,2026-05-26-11-58-30 +0000,wapo,Iran threatens retaliation after U.S. strikes ...,https://www.washingtonpost.com/world/2026/05/2...,97
135,2026-05-26-13-51-48 +0000,nypost,Trump to hold rare cabinet meeting at Camp Dav...,https://nypost.com/2026/05/26/us-news/trump-to...,88
296,2026-05-25-19-07-57 +0000,wapo,"As new Iran deal faces sharp criticism, Trump ...",https://www.washingtonpost.com/world/2026/05/2...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,104,2026-05-26-18-17-13 +0000,nyt,Iran War Live Updates: U.S. Said to Observe Th...,https://www.nytimes.com/live/2026/05/26/world/...
174,65,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...
66,53,2026-05-26-16-37-20 +0000,nypost,Spencer Pratt reveals stunning West Coast dest...,https://nypost.com/2026/05/26/us-news/spencer-...
164,41,2026-05-26-12-00-00 +0000,nypost,Save Californians thousands — then fire up Sac...,https://nypost.com/2026/05/26/us-news/steve-hi...
57,39,2026-05-26-16-51-30 +0000,nypost,Ferrari’s new $640K electric car already a mas...,https://nypost.com/2026/05/26/business/ferrari...
281,35,2026-05-25-21-07-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
101,35,2026-05-26-15-09-11 +0000,nypost,Ex-JPMorgan banker Chirayu Rana hit with major...,https://nypost.com/2026/05/26/business/ex-jpmo...
270,33,2026-05-25-21-36-00 +0000,wsj,"Oil Prices Drop on Prospect of Iran Deal, but ...",https://www.wsj.com/finance/oil-prices-drop-on...
18,31,2026-05-26-18-00-09 +0000,cbc,Temperature records fall as Western Europe swe...,https://www.cbc.ca/news/world/western-europe-h...
109,31,2026-05-26-14-44-44 +0000,bbc,DR Congo seek World Cup ticket refunds after E...,https://www.bbc.com/sport/football/articles/c0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)