## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-00-15-17 +0000,nyt,Wall Street Is Going Gaga for SpaceX,https://www.nytimes.com/2026/06/04/business/wa...
1,2026-06-05-00-14-15 +0000,nyt,House Passes Ukraine Aid in Defiance of Republ...,https://www.nytimes.com/2026/06/04/us/politics...
2,2026-06-05-00-14-00 +0000,wsj,"JGBs Edge Higher, Tracking Gains in U.S. Treas...",https://www.wsj.com/finance/investing/jgbs-edg...
3,2026-06-05-00-09-17 +0000,nyt,Priest Who Said Aliens Were Demons Removed as ...,https://www.nytimes.com/2026/06/04/us/catholic...
4,2026-06-05-00-05-45 +0000,nypost,Anthropic calls for global AI slowdown after $...,https://nypost.com/2026/06/04/business/anthrop...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
98   trump     36
121    new     18
27      ai     15
281     up     13
524   iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
363,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...,97
32,2026-06-04-23-18-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...,91
200,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...,87
364,2026-06-04-01-18-09 +0000,bbc,Senate Republicans axe $1bn for Trump's new Wh...,https://www.bbc.com/news/articles/c0r2kxrvlgpo...,79
372,2026-06-04-00-42-08 +0000,nyt,"Massie, 3 Other House Republicans Broke From T...",https://www.nytimes.com/2026/06/03/us/politics...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
363,97,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...
203,78,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
134,60,2026-06-04-20-04-02 +0000,nypost,Hezbollah rejects ‘humiliating’ cease-fire dea...,https://nypost.com/2026/06/04/world-news/hezbo...
113,59,2026-06-04-20-51-46 +0000,nypost,Woman-hating Graham Platner twisted ex-girlfri...,https://nypost.com/2026/06/04/us-news/graham-p...
246,45,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...
268,43,2026-06-04-12-34-00 +0000,cbc,No handshake and no photo as Russia's Andreeva...,https://www.cbc.ca/sports/tennis/dabrowski-rou...
32,42,2026-06-04-23-18-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...
102,40,2026-06-04-21-01-54 +0000,latimes,Spencer Pratt claims L.A.'s homeless will move...,https://www.latimes.com/california/story/2026-...
18,38,2026-06-04-23-44-17 +0000,nypost,"Tech boss, Jamshid Ghomi, charged with sending...",https://nypost.com/2026/06/04/us-news/tech-bos...
200,38,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)