## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-20-16-56-40 +0000,nypost,Oil prices hit five-month high before reversin...,https://nypost.com/2026/10/20/business/oil-pri...
1,2026-10-20-16-48-19 +0000,cbc,Satellite images reveal Wainwright fire devast...,https://www.cbc.ca/news/canada/satteilte-image...
2,2026-10-20-16-47-10 +0000,nypost,"Vance, Trump to offer up to $30K bounty for ti...",https://nypost.com/2026/10/20/us-news/vance-tr...
3,2026-10-20-16-45-52 +0000,chitri,Prince Harry says he wants to work out relatio...,https://www.chicagotribune.com/2026/10/20/prin...
4,2026-10-20-16-44-00 +0000,wsj,"Ray-Ban Maker EssilorLuxottica’s Sales Rise, B...",https://www.wsj.com/business/earnings/ray-ban-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2382/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
19    trump     39
104     new     17
77       ai     12
108  market     12
399    year     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
288,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...,143
95,2026-10-20-13-48-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...,112
87,2026-10-20-14-06-00 +0000,wsj,Trump is planning to announce a new program th...,https://www.wsj.com/politics/policy/trump-to-o...,112
274,2026-10-19-21-49-41 +0000,nyt,DOJ Charges 28 California Residents With Votin...,https://www.nytimes.com/2026/10/19/us/politics...,86
160,2026-10-20-10-30-00 +0000,wsj,"Ex-officials from the Trump, Biden and Obama a...",https://www.wsj.com/politics/policy/u-s-risks-...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
288,143,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...
87,73,2026-10-20-14-06-00 +0000,wsj,Trump is planning to announce a new program th...,https://www.wsj.com/politics/policy/trump-to-o...
95,73,2026-10-20-13-48-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...
172,52,2026-10-20-10-00-00 +0000,nypost,"Kansas Dem Adam Hamilton, who made millions on...",https://nypost.com/2026/10/20/us-news/kansas-d...
123,47,2026-10-20-12-19-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
112,46,2026-10-20-12-48-52 +0000,nypost,Far-left French rioter on national security wa...,https://nypost.com/2026/10/20/world-news/far-l...
93,45,2026-10-20-13-49-27 +0000,nypost,Heartbroken parents of youngest Oregon school ...,https://nypost.com/2026/10/20/us-news/heartbro...
40,42,2026-10-20-15-58-57 +0000,bbc,"Swimmer, 65, killed in shark attack off South ...",https://www.bbc.co.uk/news/articles/cqx297pxg1...
274,40,2026-10-19-21-49-41 +0000,nyt,DOJ Charges 28 California Residents With Votin...,https://www.nytimes.com/2026/10/19/us/politics...
120,37,2026-10-20-12-34-57 +0000,nyt,UK to Send Fighter Jets to Help Defend Saudi A...,https://www.nytimes.com/2026/10/20/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)