## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-04-16-58-06 +0000,nyt,Iran War Live Updates: U.S. Searches for Missi...,https://www.nytimes.com/live/2026/04/04/world/...
1,2026-04-04-16-58-04 +0000,nyt,Missing Airman Raises Concerns That Iran Could...,https://www.nytimes.com/2026/04/04/world/middl...
2,2026-04-04-16-55-02 +0000,startribune,Iran calls on the public to find the 'enemy pi...,https://www.startribune.com/us-presses-search-...
3,2026-04-04-16-54-30 +0000,nypost,Artemis II astronauts are more than halfway to...,https://nypost.com/2026/04/04/world-news/artem...
4,2026-04-04-16-54-03 +0000,nypost,Artist fumes after tribute honoring slain Iryn...,https://nypost.com/2026/04/04/us-news/artist-f...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
7         trump     44
0          iran     30
1           war     15
123         new     11
141  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-04-16-58-06 +0000,nyt,Iran War Live Updates: U.S. Searches for Missi...,https://www.nytimes.com/live/2026/04/04/world/...,113
200,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...,113
139,2026-04-04-00-02-20 +0000,nyt,War With Iran Clarifies Trump’s Spending Prior...,https://www.nytimes.com/2026/04/02/us/politics...,108
82,2026-04-04-09-30-00 +0000,wsj,President Trump didn’t attack Iran to help the...,https://www.wsj.com/economy/the-iran-war-is-ma...,102
93,2026-04-04-09-01-43 +0000,nyt,"Trump Pledged a Quick End to the Iran War, but...",https://www.nytimes.com/2026/04/04/us/politics...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,113,2026-04-04-16-58-06 +0000,nyt,Iran War Live Updates: U.S. Searches for Missi...,https://www.nytimes.com/live/2026/04/04/world/...
208,44,2026-04-03-19-22-00 +0000,wsj,President Trump released a summary of his budg...,https://www.wsj.com/politics/policy/trump-budg...
207,40,2026-04-03-19-32-02 +0000,nypost,How US forces will use cover of darkness in da...,https://nypost.com/2026/04/03/world-news/time-...
138,37,2026-04-04-00-07-47 +0000,nyt,March Jobs Report Shows Stronger U.S. Market T...,https://www.nytimes.com/2026/04/03/business/ec...
142,32,2026-04-04-00-00-00 +0000,wsj,These AI Whiz Kids Dropped Out of College and ...,https://www.wsj.com/tech/ai/ai-college-dropout...
79,31,2026-04-04-10-00-00 +0000,latimes,House Democrats to hold California 'shadow hea...,https://www.latimes.com/politics/story/2026-04...
201,31,2026-04-03-20-02-00 +0000,wsj,Supreme Court Justice Samuel Alito was taken t...,https://www.wsj.com/politics/policy/supreme-co...
53,27,2026-04-04-12-53-53 +0000,nyt,"Houston Cheers on Artemis II Moon Mission, Rec...",https://www.nytimes.com/2026/04/04/us/artemis-...
48,27,2026-04-04-13-21-41 +0000,nypost,Ex-student of NJ teacher accused of sex with c...,https://nypost.com/2026/04/04/us-news/nj-teach...
102,27,2026-04-04-08-15-47 +0000,nypost,Three men charged over arson attack on Jewish ...,https://nypost.com/2026/04/04/world-news/uk-ch...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)