## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-28-11-26-00 +0000,wsj,Coca-Cola Profit Rises on Concentrate Sales Gr...,https://www.wsj.com/business/retail/coca-cola-...
1,2026-04-28-11-14-25 +0000,bbc,Mexican cartel leader found hiding in a ditch,https://www.bbc.com/news/articles/cj6p2r9gk8go...
2,2026-04-28-11-14-23 +0000,bbc,'It's bizarre': Californians grapple with reve...,https://www.bbc.com/news/articles/c392knk3w2jo...
3,2026-04-28-11-09-00 +0000,wsj,BYD’s Quarterly Profit Slides 55%,https://www.wsj.com/business/earnings/byds-qua...
4,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2355/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
28      trump     48
304      iran     22
286     court     17
157      king     14
748  shooting     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
15,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,171
126,2026-04-28-04-19-15 +0000,nypost,Jimmy Kimmel repeats ‘hateful’ joke about ‘exp...,https://nypost.com/2026/04/28/us-news/jimmy-ki...,121
53,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,117
233,2026-04-27-20-18-06 +0000,nyt,President and First Lady Melania Trump Demand ...,https://www.nytimes.com/2026/04/27/us/politics...,117
148,2026-04-28-02-07-55 +0000,nypost,Mentalist Oz Pearlman won’t appear on ‘Jimmy K...,https://nypost.com/2026/04/27/us-news/mentalis...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
15,171,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
266,68,2026-04-27-17-57-06 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
117,65,2026-04-28-05-33-17 +0000,bbc,In pictures: King Charles and Queen Camilla at...,https://www.bbc.com/news/articles/c86e6z26xdpo...
45,62,2026-04-28-10-00-00 +0000,latimes,Supreme Court will hear Trump's bid to end leg...,https://www.latimes.com/politics/story/2026-04...
242,59,2026-04-27-20-08-59 +0000,latimes,OpenAI CEO Sam Altman apologizes for not alert...,https://www.latimes.com/business/story/2026-04...
175,44,2026-04-27-23-26-32 +0000,nypost,"Taylor Swift files to trademark her voice, lik...",https://nypost.com/2026/04/27/business/taylor-...
268,43,2026-04-27-17-45-34 +0000,startribune,Renee Good’s widow asks feds to hand over vehi...,https://www.startribune.com/renee-goods-widow-...
241,40,2026-04-27-20-12-17 +0000,nyt,"Oil Rises, and Stocks Tick Higher, as Iran Mak...",https://www.nytimes.com/2026/04/26/business/oi...
265,40,2026-04-27-18-07-33 +0000,nypost,California’s billionaire tax gamble — insiders...,https://nypost.com/2026/04/27/business/billion...
158,40,2026-04-28-01-05-00 +0000,wsj,The Defense Department can temporarily require...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)