## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-22-11-45-38 +0000,bbc,Angry crowd sets Ebola hospital tents on fire ...,https://www.bbc.com/news/articles/cp8p2g8yp8do...
1,2026-05-22-11-43-00 +0000,wsj,BJ’s Wholesale Revenue Rises on Membership Growth,https://www.wsj.com/business/retail/bjs-wholes...
2,2026-05-22-11-41-23 +0000,bbc,An Indian bride dies. Rival claims of murder a...,https://www.bbc.com/news/articles/czd2q140my1o...
3,2026-05-22-11-40-51 +0000,nyt,What to Know About the Ebola Outbreak as Cases...,https://www.nytimes.com/2026/05/17/world/afric...
4,2026-05-22-11-39-14 +0000,bbc,"Nato chief welcomes US sending 5,000 troops to...",https://www.bbc.com/news/articles/cedpz9669deo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
100  trump     48
123    new     21
645   iran     17
3    ebola     15
483     he     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
338,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...,113
224,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...,108
178,2026-05-21-23-54-00 +0000,wsj,House Republican leaders yanked a planned vote...,https://www.wsj.com/politics/house-republicans...,107
18,2026-05-22-11-00-00 +0000,nypost,How Kevin Warsh will navigate his tricky new p...,https://nypost.com/2026/05/22/business/how-kev...,104
357,2026-05-21-15-36-20 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
338,113,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...
70,64,2026-05-22-09-30-00 +0000,wsj,Kevin Warsh is to be sworn in as Fed chair on ...,https://www.wsj.com/economy/central-banking/tr...
224,60,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...
128,59,2026-05-22-04-46-50 +0000,nypost,"New presidential poll shows Gavin Newsom, Kama...",https://nypost.com/2026/05/22/us-news/new-pres...
178,59,2026-05-21-23-54-00 +0000,wsj,House Republican leaders yanked a planned vote...,https://www.wsj.com/politics/house-republicans...
173,53,2026-05-22-00-04-00 +0000,wsj,Mortgage rates this week rose to the highest l...,https://www.wsj.com/economy/housing/mortgage-r...
77,49,2026-05-22-09-02-18 +0000,nyt,"With Gas Prices Through the Roof, Will Renting...",https://www.nytimes.com/2026/05/22/travel/elec...
31,49,2026-05-22-10-52-48 +0000,nypost,Feds dramatically drop charges against Illinoi...,https://nypost.com/2026/05/22/us-news/feds-dro...
91,46,2026-05-22-08-45-07 +0000,nypost,Ex-CDC chief Robert Redfield fears Ebola outbr...,https://nypost.com/2026/05/22/us-news/ex-cente...
339,45,2026-05-21-16-51-12 +0000,nyt,French Court Says Air France and Airbus Are Gu...,https://www.nytimes.com/2026/05/21/business/ai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)