## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-11-21-04-50 +0000,nyt,Trump’s Posts on Singing Somali Schoolchildren...,https://www.nytimes.com/2026/07/11/us/politics...
1,2026-07-11-20-51-48 +0000,nyt,White House Directed Patel to Oversee Investig...,https://www.nytimes.com/2026/07/11/us/politics...
2,2026-07-11-20-47-34 +0000,nypost,Manny Pacquiao takes over Floyd Mayweather’s f...,https://nypost.com/2026/07/11/us-news/pacquiao...
3,2026-07-11-20-30-51 +0000,nypost,CBS news anchor nearly loses life savings in L...,https://nypost.com/2026/07/11/us-news/cbs-news...
4,2026-07-11-20-28-17 +0000,nypost,Russia ballistic missile and drone onslaught k...,https://nypost.com/2026/07/11/world-news/russi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2710/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     32
228    new     22
115  world     14
116    cup     12
15   times     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,115
152,2026-07-11-04-00-00 +0000,wsj,A lack of defensive capabilities aboard Presid...,https://www.wsj.com/politics/national-security...,110
214,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...,109
56,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,107
58,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,115,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
214,56,2026-07-10-21-39-00 +0000,wsj,Apple accuses OpenAI of stealing trade secrets...,https://www.wsj.com/politics/policy/apple-accu...
63,52,2026-07-11-15-37-30 +0000,nypost,Fan collects beer from all 48 countries in Wor...,https://nypost.com/2026/07/11/sports/fan-colle...
121,47,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
107,38,2026-07-11-10-56-43 +0000,nypost,Iran’s Supreme Leader Mojtaba Khamenei vows re...,https://nypost.com/2026/07/11/world-news/irans...
47,34,2026-07-11-17-23-04 +0000,bbc,Ann Widdecombe attacked nearly 24 hours before...,https://www.bbc.co.uk/news/articles/cgjx912wxw...
20,32,2026-07-11-19-34-45 +0000,nyt,How Will Maine Democrats Replace Graham Platne...,https://www.nytimes.com/2026/07/11/us/politics...
148,32,2026-07-11-04-37-00 +0000,wsj,A landmark housing bill designed to address vo...,https://www.wsj.com/politics/policy/trump-says...
74,31,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...
225,30,2026-07-10-21-13-08 +0000,cbc,Dodgers star Shohei Ohtani to miss all-star ga...,https://www.cbc.ca/sports/baseball/mlb/los-ang...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)