## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-12-51-10 +0000,bbc,Huge crowds greet Pope in Paris ahead of open-...,https://www.bbc.co.uk/news/articles/cm4gjjwvvl...
1,2026-09-26-12-47-25 +0000,bbc,British national among six dead in building ex...,https://www.bbc.co.uk/news/articles/c6p3kk78l4...
2,2026-09-26-12-47-00 +0000,wsj,"U.S., China Agree to Trim Tariffs, Start AI Di...",https://www.wsj.com/world/china/u-s-china-agre...
3,2026-09-26-12-45-22 +0000,nyt,"As A.I. Makes Law Firms More Efficient, Client...",https://www.nytimes.com/2026/09/26/business/de...
4,2026-09-26-12-24-27 +0000,nypost,Original Rachel Dolezal wants to have dinner w...,https://nypost.com/2026/09/26/us-news/rachel-d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
135  trump     67
705  court     21
335    new     21
462     xi     19
484  house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
89,2026-09-26-01-50-38 +0000,nypost,Trump rejects Iran’s 7-day cease-fire proposal...,https://nypost.com/2026/09/25/us-news/trump-re...,219
84,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...,167
290,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...,156
265,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,148
248,2026-09-25-18-26-18 +0000,nypost,White House plays ‘Les Miserables’ hit censore...,https://nypost.com/2026/09/25/us-news/white-ho...,144

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
89,219,2026-09-26-01-50-38 +0000,nypost,Trump rejects Iran’s 7-day cease-fire proposal...,https://nypost.com/2026/09/25/us-news/trump-re...
290,89,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...
265,81,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...
91,70,2026-09-26-01-40-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
311,44,2026-09-25-15-49-16 +0000,chitri,Chicago City Council approves campaign ethics ...,https://www.chicagotribune.com/2026/09/25/chic...
80,43,2026-09-26-02-39-46 +0000,nypost,Wild moment cop drags woman out of California ...,https://nypost.com/2026/09/25/us-news/tulare-c...
59,40,2026-09-26-07-03-34 +0000,nypost,Ukraine’s Zelensky says he urged Trump to enli...,https://nypost.com/2026/09/26/world-news/ukrai...
110,38,2026-09-26-00-00-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota doesn’...,https://www.wsj.com/politics/ilhan-omar-is-the...
263,37,2026-09-25-17-49-46 +0000,latimes,Suspect bites off piece of police dog's ear du...,https://www.latimes.com/california/story/2026-...
318,35,2026-09-25-15-38-16 +0000,nyt,Fed Faces Prospect of Another Interest Rate In...,https://www.nytimes.com/2026/09/25/business/fe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)