## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-27-16-13-48 +0000,nypost,Domino’s manager earns title of World’s Fastes...,https://nypost.com/2026/06/27/us-news/dominos-...
1,2026-06-27-16-09-45 +0000,nyt,Venezuela Live Updates: Rescuers Work as Windo...,https://www.nytimes.com/live/2026/06/27/world/...
2,2026-06-27-16-09-06 +0000,nyt,"Riding Into 2028: On the Midterms Trail, Andy ...",https://www.nytimes.com/2026/06/27/us/politics...
3,2026-06-27-16-05-25 +0000,nyt,"Live Updates: Mideast Hostilities Flare, Testi...",https://www.nytimes.com/live/2026/06/27/world/...
4,2026-06-27-16-00-09 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2513/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
11    venezuela     22
278       trump     22
33         iran     19
4         world     15
42   california     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
293,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...,68
282,2026-06-26-18-03-32 +0000,bbc,Trump accuses Iran of ceasefire breach after S...,https://www.bbc.co.uk/news/articles/ckg54g0ry0...,67
139,2026-06-27-00-52-00 +0000,wsj,Venezuela’s Earthquakes Test Trump’s Bet on De...,https://www.wsj.com/world/americas/venezuelas-...,62
223,2026-06-26-20-35-00 +0000,cbc,U.S. strikes Iran in retaliation for attack on...,https://www.cbc.ca/news/world/trump-blames-ira...,61
42,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
293,68,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...
223,61,2026-06-26-20-35-00 +0000,cbc,U.S. strikes Iran in retaliation for attack on...,https://www.cbc.ca/news/world/trump-blames-ira...
42,60,2026-06-27-13-13-12 +0000,nyt,Two Earthquakes Hit Venezuela: What to Know Ab...,https://www.nytimes.com/article/venezuela-eart...
21,57,2026-06-27-14-50-48 +0000,nypost,World Cup criminals cheated desperate fans out...,https://nypost.com/2026/06/27/world-news/world...
137,51,2026-06-27-01-00-00 +0000,wsj,Jack Schlossberg looked like he could be a Ken...,https://www.wsj.com/politics/elections/jack-sc...
265,48,2026-06-26-18-39-42 +0000,bbc,Judge declares mistrial in case against man ac...,https://www.bbc.co.uk/news/articles/cx2w0k5zzr...
309,40,2026-06-26-16-26-28 +0000,nypost,Ex-’60 Minutes’ boss Bill Owens blasts Paramou...,https://nypost.com/2026/06/26/media/ex-60-minu...
189,35,2026-06-26-21-41-00 +0000,wsj,Millions of people who signed up for Affordabl...,https://www.wsj.com/politics/policy/millions-o...
299,32,2026-06-26-17-00-00 +0000,wsj,The search for a new leader of the Federal Res...,https://www.wsj.com/economy/central-banking/at...
221,31,2026-06-26-20-42-59 +0000,nypost,5 human heads found stuffed inside medical fre...,https://nypost.com/2026/06/26/world-news/5-hum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)