## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-15-19-02-22 +0000,nypost,Landlord Charles Cohen lands cafe at Decoratio...,https://nypost.com/2026/03/15/business/landlor...
1,2026-03-15-18-57-00 +0000,wsj,Opinion | Taking the U.S.-Israel Alliance’s St...,https://www.wsj.com/opinion/taking-the-u-s-isr...
2,2026-03-15-18-54-12 +0000,nypost,Restaurant Le Colonial returning to NYC’s midt...,https://nypost.com/2026/03/15/business/restaur...
3,2026-03-15-18-54-00 +0000,wsj,Opinion | The Kurds Could Help in Iran,https://www.wsj.com/opinion/the-kurds-could-he...
4,2026-03-15-18-53-00 +0000,wsj,Opinion | An Uncertain Future vs. Certain Nuke...,https://www.wsj.com/opinion/an-uncertain-futur...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
26     iran     37
41      war     28
51    trump     27
12   israel      9
310     new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...,108
168,2026-03-14-22-04-27 +0000,wapo,FCC chief threatens broadcasters as Trump crit...,https://www.washingtonpost.com/business/2026/0...,108
138,2026-03-15-01-37-45 +0000,nyt,Fund-raising Email Features Trump at Ritual fo...,https://www.nytimes.com/2026/03/14/us/politics...,107
151,2026-03-15-00-29-36 +0000,nypost,Trump says Iran wants to end the war – but ter...,https://nypost.com/2026/03/14/world-news/trump...,104
104,2026-03-15-10-00-00 +0000,latimes,Trump is searching for an endgame to the Iran war,https://www.latimes.com/politics/story/2026-03...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,108,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...
40,46,2026-03-15-17-06-25 +0000,nypost,Captain of Iranian women’s soccer team is late...,https://nypost.com/2026/03/15/world-news/capta...
48,36,2026-03-15-16-22-59 +0000,nypost,Shocking new details emerge after top LA pol c...,https://nypost.com/2026/03/15/us-news/new-deta...
12,35,2026-03-15-18-37-02 +0000,nyt,Energy Secretary Says ‘No Guarantees’ Oil Pric...,https://www.nytimes.com/2026/03/15/us/politics...
160,29,2026-03-14-22-50-40 +0000,nypost,6 troops killed in US military flight crash id...,https://nypost.com/2026/03/14/world-news/us-mi...
155,28,2026-03-15-00-00-00 +0000,wsj,The AI boom has sparked a frenzied real-estate...,https://www.wsj.com/economy/housing/san-franci...
108,27,2026-03-15-09-28-50 +0000,nypost,Iran threatens to ‘pursue and kill’ Netanyahu ...,https://nypost.com/2026/03/15/world-news/iran-...
178,27,2026-03-14-20-33-34 +0000,bbc,Trump urges UK and other nations to send warsh...,https://www.bbc.com/news/articles/cd039n9vj3vo...
75,27,2026-03-15-14-12-56 +0000,nypost,Maine Dem Senate hopeful Graham Platner done a...,https://nypost.com/2026/03/15/us-news/maine-de...
94,25,2026-03-15-10-38-22 +0000,bbc,Israeli forces kill Palestinian couple and two...,https://www.bbc.com/news/articles/cqxdndz75zvo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)