## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-09-04-06-37 +0000,nypost,Boat overturns off Liberty Island coast; woman...,https://nypost.com/2026/08/09/us-news/boat-ove...
1,2026-08-09-04-01-14 +0000,nyt,How a Drone ‘Hellscape’ Might Stop a Chinese I...,https://www.nytimes.com/2026/08/09/world/asia/...
2,2026-08-09-03-00-00 +0000,wsj,The Wild History of the Russian Online Retail ...,https://www.wsj.com/world/russia/the-wild-hist...
3,2026-08-09-02-59-59 +0000,nypost,Chaos as California city declares state of eme...,https://nypost.com/2026/08/08/us-news/cyberatt...
4,2026-08-09-02-44-42 +0000,nyt,Hunter Biden Says His Father’s Cancer Is Worse...,https://www.nytimes.com/2026/08/08/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2523/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
387    trump     14
434   senate     10
368     iran     10
633  blanche      7
674     todd      6

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
160,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...,60
96,2026-08-08-15-45-32 +0000,chitri,Todd Blanche is narrowly confirmed as Trump’s ...,https://www.chicagotribune.com/2026/08/08/todd...,53
159,2026-08-08-08-38-37 +0000,nypost,Senate confirms Todd Blanche as Trump’s attorn...,https://nypost.com/2026/08/08/us-news/todd-bla...,46
93,2026-08-08-15-56-39 +0000,bbc,Trump's ex-lawyer Todd Blanche narrowly confir...,https://www.bbc.co.uk/news/articles/cewr898jy8...,45
68,2026-08-08-18-56-45 +0000,nypost,Trump could consider taking out Pickaxe Mounta...,https://nypost.com/2026/08/08/us-news/irans-pi...,42

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
160,60,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...
62,41,2026-08-08-19-18-57 +0000,bbc,"Hormuz talks positive, Oman says, as Iran warn...",https://www.bbc.co.uk/news/articles/c934j5y2lq...
90,39,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
38,33,2026-08-08-22-30-37 +0000,nypost,Calif. woman admits to murdering fire captain ...,https://nypost.com/2026/08/08/us-news/wife-of-...
74,28,2026-08-08-18-06-25 +0000,bbc,Child among three killed in Russian missile at...,https://www.bbc.co.uk/news/articles/cz7dy8gq99...
15,27,2026-08-09-01-00-53 +0000,nypost,California housing crisis laid bare in shockin...,https://nypost.com/2026/08/08/us-news/californ...
21,22,2026-08-09-00-13-02 +0000,nypost,"NYC woman warns against getting painful, blist...",https://nypost.com/2026/08/08/us-news/margarit...
41,21,2026-08-08-22-01-54 +0000,bbc,Fast-moving Canada wildfire doubles in size fo...,https://www.bbc.co.uk/news/articles/cx25dkwk3e...
170,21,2026-08-08-05-29-18 +0000,nypost,Texas cop Chad Eberle fatally shot 3 people du...,https://nypost.com/2026/08/08/world-news/texas...
166,20,2026-08-08-08-00-00 +0000,cbc,'I woke up and I had lost the baby': Miscarria...,https://www.cbc.ca/news/world/gaza-miscarriage...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)