## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-12-13-16-09 +0000,nypost,Trump announces blockade of Strait of Hormuz,https://nypost.com/2026/04/12/us-news/trump-an...
1,2026-04-12-13-15-06 +0000,startribune,Trump threatens Strait of Hormuz blockade afte...,https://www.startribune.com/us-and-iran-end-ce...
2,2026-04-12-13-14-58 +0000,nyt,Iran War Live Updates: Top Iranian Negotiator ...,https://www.nytimes.com/live/2026/04/12/world/...
3,2026-04-12-13-06-07 +0000,nyt,"In Pakistan Talks, Iran Saw a U.S. Trying to D...",https://www.nytimes.com/2026/04/12/world/middl...
4,2026-04-12-13-00-00 +0000,missionlocal,14-Mission,https://missionlocal.org/2026/04/14-mission/

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
6        iran     35
8       talks     20
0       trump     16
338  swalwell     13
12        war     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-12-13-15-06 +0000,startribune,Trump threatens Strait of Hormuz blockade afte...,https://www.startribune.com/us-and-iran-end-ce...,107
2,2026-04-12-13-14-58 +0000,nyt,Iran War Live Updates: Top Iranian Negotiator ...,https://www.nytimes.com/live/2026/04/12/world/...,96
188,2026-04-11-14-22-31 +0000,nyt,Iran Has Been Consistent in War. Will It Be Co...,https://www.nytimes.com/2026/04/11/world/middl...,90
13,2026-04-12-12-21-03 +0000,nypost,Iran says no plans for further US peace talks ...,https://nypost.com/2026/04/12/world-news/iran-...,87
118,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,107,2026-04-12-13-15-06 +0000,startribune,Trump threatens Strait of Hormuz blockade afte...,https://www.startribune.com/us-and-iran-end-ce...
118,76,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
125,49,2026-04-11-23-00-00 +0000,wsj,"Before taking office, RFK Jr. promised to end ...",https://www.wsj.com/politics/policy/rfk-jr-raw...
2,41,2026-04-12-13-14-58 +0000,nyt,Iran War Live Updates: Top Iranian Negotiator ...,https://www.nytimes.com/live/2026/04/12/world/...
47,33,2026-04-12-09-30-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
17,32,2026-04-12-12-00-00 +0000,wsj,President Trump and his advisers have been con...,https://www.wsj.com/politics/policy/white-hous...
115,32,2026-04-11-23-42-55 +0000,nyt,"As Election Looms, Will Alito Retire, Giving T...",https://www.nytimes.com/2026/04/11/us/politics...
172,26,2026-04-11-17-25-51 +0000,nypost,Zohran Mamdani’s legal advisor boasts anti-Isr...,https://nypost.com/2026/04/11/us-news/mamdani-...
176,23,2026-04-11-16-02-08 +0000,nypost,Fla. GOP rep plans to file motion to expel Eri...,https://nypost.com/2026/04/11/us-news/florida-...
75,21,2026-04-12-05-52-11 +0000,nypost,"Ted Bundy stalked teen victim, posed as her bo...",https://nypost.com/2026/04/12/us-news/ted-bund...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)