## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-12-08-47 +0000,nypost,US military seizes sanctioned tanker transport...,https://nypost.com/2026/04/23/world-news/us-mi...
1,2026-04-23-12-04-31 +0000,nyt,$106 Billion Loan Reflects E.U.’s View That Pe...,https://www.nytimes.com/2026/04/23/world/europ...
2,2026-04-23-12-02-30 +0000,nyt,Iran War Live Updates: Reported Ship Seizures ...,https://www.nytimes.com/live/2026/04/23/world/...
3,2026-04-23-12-00-00 +0000,missionlocal,Has San Francisco made West SoMa into a crime ...,https://missionlocal.org/2026/04/san-francisco...
4,2026-04-23-12-00-00 +0000,startribune,Scoggins: Wild winger Matt Boldy shows his sta...,https://www.startribune.com/matt-boldy-minneso...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2613/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
15         iran     38
359       trump     28
117         new     24
16          war     23
429  california     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
142,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,126
204,2026-04-22-21-43-54 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...,120
351,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...,118
208,2026-04-22-21-33-05 +0000,wapo,Iran says it seized 2 ships in Strait of Hormu...,https://www.washingtonpost.com/world/2026/04/2...,115
373,2026-04-22-12-37-51 +0000,cbc,Iran seizes container ships in Strait of Hormu...,https://www.cbc.ca/news/world/livestory/iran-b...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
142,126,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
208,77,2026-04-22-21-33-05 +0000,wapo,Iran says it seized 2 ships in Strait of Hormu...,https://www.washingtonpost.com/world/2026/04/2...
191,77,2026-04-22-22-11-28 +0000,nyt,"Heidi O’Neill, Formerly of Nike, Will Be New L...",https://www.nytimes.com/2026/04/22/business/lu...
292,54,2026-04-22-18-07-17 +0000,nyt,California’s Governor Candidates to Meet in Fi...,https://www.nytimes.com/2026/04/22/us/californ...
372,52,2026-04-22-12-50-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
67,48,2026-04-23-09-53-35 +0000,nypost,Alabama high school basketball coach Paige Ada...,https://nypost.com/2026/04/23/us-news/alabama-...
309,41,2026-04-22-16-58-00 +0000,wsj,More than a year into President Trump’s immigr...,https://www.wsj.com/economy/jobs/immigration-c...
174,40,2026-04-22-23-07-43 +0000,nypost,Elon Musk says Tesla expenses will rise ‘subst...,https://nypost.com/2026/04/22/business/elon-mu...
145,39,2026-04-23-01-42-00 +0000,wsj,John Phelan has been fired as Navy secretary a...,https://www.wsj.com/politics/national-security...
332,39,2026-04-22-15-48-12 +0000,nyt,Attacks along the Israel-Lebanon border put a ...,https://www.nytimes.com/live/2026/04/22/world/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)