## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-22-17-24 +0000,nypost,Medical examiner breaks down excruciating caus...,https://nypost.com/2026/05/19/us-news/medical-...
1,2026-05-19-22-17-05 +0000,nypost,Summer comes early in NYC with blistering temp...,https://nypost.com/2026/05/19/us-news/summer-c...
2,2026-05-19-22-16-49 +0000,nypost,LA Council cuts new deal on Olympic wage after...,https://nypost.com/2026/05/19/us-news/la-counc...
3,2026-05-19-22-16-48 +0000,nypost,"Trump, Lawler to tout SALT tax break in Friday...",https://nypost.com/2026/05/19/us-news/trump-la...
4,2026-05-19-22-15-00 +0000,wsj,Toll Brothers Says Its Average Home Prices Bac...,https://www.wsj.com/business/earnings/homebuil...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2319/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35   trump     56
123   iran     25
28     new     21
414  first     15
221    san     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
42,2026-05-19-21-31-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...,137
13,2026-05-19-22-03-47 +0000,nyt,Senate Votes to Take Up Measure to Force Trump...,https://www.nytimes.com/2026/05/19/us/politics...,121
366,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,121
191,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...,116
16,2026-05-19-21-57-05 +0000,nyt,Trump Endorses Ken Paxton in Texas Senate Runo...,https://www.nytimes.com/2026/05/19/us/politics...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
42,137,2026-05-19-21-31-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/elections/trump-t...
93,75,2026-05-19-20-43-31 +0000,nypost,Spencer Pratt calls out Karen Bass amid wildfi...,https://nypost.com/2026/05/19/us-news/spencer-...
13,57,2026-05-19-22-03-47 +0000,nyt,Senate Votes to Take Up Measure to Force Trump...,https://www.nytimes.com/2026/05/19/us/politics...
29,57,2026-05-19-21-35-38 +0000,nypost,Shocking manifesto reveals teen shooters’ vile...,https://nypost.com/2026/05/19/us-news/manifest...
293,52,2026-05-19-11-01-00 +0000,wsj,The nearly $1.8 billion “anti-weaponization fu...,https://www.wsj.com/politics/how-trumps-1-776-...
125,48,2026-05-19-19-32-22 +0000,bbc,Ebola outbreak may be spreading faster than fi...,https://www.bbc.com/news/articles/ceqp11gn1l8o...
366,46,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
167,46,2026-05-19-18-03-38 +0000,latimes,Hilton and Becerra lead in a tightening race i...,https://www.latimes.com/california/story/2026-...
207,38,2026-05-19-15-41-14 +0000,nypost,Trump shows off ‘impenetrable’ White House bal...,https://nypost.com/2026/05/19/us-news/trump-sh...
191,35,2026-05-19-16-36-10 +0000,nypost,Trump makes long-awaited endorsement in Texas ...,https://nypost.com/2026/05/19/us-news/trump-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)