## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-06-02-46-59 +0000,nypost,Horde of teens pummel South Carolina cops brea...,https://nypost.com/2026/07/05/us-news/horde-of...
1,2026-07-06-02-19-25 +0000,bbc,Backlash after China bubble tea firm ordered t...,https://www.bbc.co.uk/news/articles/cwykk095yz...
2,2026-07-06-02-17-07 +0000,nypost,Semitruck spills 40K pounds of Frank’s RedHot ...,https://nypost.com/2026/07/05/us-news/semitruc...
3,2026-07-06-02-12-27 +0000,latimes,Jackie and Shadow fled during Big Bear firewor...,https://www.latimes.com/california/story/2026-...
4,2026-07-06-02-08-28 +0000,nyt,China Frees Pastor Detained in Crackdown on Re...,https://www.nytimes.com/2026/07/05/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
48     trump     19
8       july     12
473  funeral     12
510     iran     12
103    world     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
60,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...,82
188,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,73
199,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...,65
198,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,61
98,2026-07-05-18-20-53 +0000,nypost,Ex-Dem activist Calla Walsh attends Khamenei’s...,https://nypost.com/2026/07/05/world-news/calla...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
60,82,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...
188,73,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...
104,46,2026-07-05-17-52-11 +0000,latimes,"Woman killed, several injured in Fourth of Jul...",https://www.latimes.com/california/story/2026-...
199,40,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
159,35,2026-07-05-11-00-00 +0000,wsj,President Trump has flown on a new Air Force O...,https://www.wsj.com/politics/policy/trump-want...
166,27,2026-07-05-10-00-00 +0000,latimes,"Barabak: Happy Birthday, America! You've weath...",https://www.latimes.com/politics/story/2026-07...
134,27,2026-07-05-14-37-30 +0000,nypost,Pa. Gov. Josh Shapiro slams socialist NY Dem D...,https://nypost.com/2026/07/05/us-news/pa-gov-j...
138,27,2026-07-05-13-59-00 +0000,wsj,Germany before World War I provoked backlash b...,https://www.wsj.com/economy/trade/how-to-win-a...
29,23,2026-07-06-00-00-00 +0000,wsj,"On the California Coast, a Picture-Perfect Cit...",https://www.wsj.com/business/hospitality/on-th...
44,21,2026-07-05-22-36-43 +0000,nypost,"Michigan Rep. Mallory McMorrow, who trashed ru...",https://nypost.com/2026/07/05/us-news/mallory-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)