## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-21-13-11-57 +0000,nyt,Live Updates: BTS’s Comeback Show Was Heavy on...,https://www.nytimes.com/live/2026/03/21/world/...
1,2026-03-21-13-11-45 +0000,wapo,The Middle East celebrates Eid and Nowruz unde...,https://www.washingtonpost.com/world/2026/03/2...
2,2026-03-21-13-03-38 +0000,nyt,Iran War Live Updates: U.S. Lifts Sanctions on...,https://www.nytimes.com/live/2026/03/21/world/...
3,2026-03-21-13-03-36 +0000,nyt,Middle East War Leaves Hamas Balancing Allies ...,https://www.nytimes.com/2026/03/21/world/middl...
4,2026-03-21-13-00-00 +0000,missionlocal,Lonely leprechaun,https://missionlocal.org/2026/03/lonely-leprec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
34        trump     31
18         iran     30
17          war     22
330  california     12
22          oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-21-13-03-38 +0000,nyt,Iran War Live Updates: U.S. Lifts Sanctions on...,https://www.nytimes.com/live/2026/03/21/world/...,117
195,2026-03-20-20-27-24 +0000,nypost,"Trump vows no cease-fire with Iran, predicts S...",https://nypost.com/2026/03/20/world-news/trump...,99
240,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...,93
266,2026-03-20-16-56-35 +0000,nyt,Iran War Underscores the Diverging Aims of Tru...,https://www.nytimes.com/2026/03/20/world/europ...,87
58,2026-03-21-09-01-26 +0000,nyt,War in Iran Reveals Strait of Hormuz’s Weaknes...,https://www.nytimes.com/2026/03/21/business/ir...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,117,2026-03-21-13-03-38 +0000,nyt,Iran War Live Updates: U.S. Lifts Sanctions on...,https://www.nytimes.com/live/2026/03/21/world/...
240,93,2026-03-20-18-19-51 +0000,nypost,UK agrees to let US military use its bases for...,https://nypost.com/2026/03/20/world-news/uk-to...
129,52,2026-03-21-00-17-00 +0000,wsj,A federal judge on Friday blocked the Trump ad...,https://www.wsj.com/politics/the-pentagons-new...
101,45,2026-03-21-02-40-33 +0000,48hills,CBS workers in SF walk off the job as Bari Wei...,https://48hills.org/2026/03/cbs-workers-in-sf-...
175,44,2026-03-20-21-03-18 +0000,nypost,University of Alabama student James Gracey was...,https://nypost.com/2026/03/20/world-news/unive...
198,39,2026-03-20-20-16-26 +0000,nypost,‘Armageddon’ attack on Qatari plant could keep...,https://nypost.com/2026/03/20/business/armaged...
81,39,2026-03-21-06-55-46 +0000,nypost,California man who killed his girlfriend less ...,https://nypost.com/2026/03/21/us-news/californ...
123,37,2026-03-21-01-00-00 +0000,wsj,Some Democrats on Capitol Hill are discussing ...,https://www.wsj.com/politics/policy/chuck-schu...
50,35,2026-03-21-09-34-53 +0000,bbc,'BTS is everything for us': K-pop fans gather ...,https://www.bbc.com/news/videos/c9wqklg2rexo?a...
276,33,2026-03-20-16-30-54 +0000,nyt,"Educators, How Will You Teach Cesar Chavez’s S...",https://www.nytimes.com/2026/03/20/us/cesar-ch...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)