## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-21-05-08 +0000,nyt,"Rescue Effort for Russian Tanker Fails, in a N...",https://www.nytimes.com/2026/04/23/world/europ...
1,2026-04-23-21-03-29 +0000,nyt,Iran War Live Updates: Trump to Host Israeli a...,https://www.nytimes.com/live/2026/04/23/world/...
2,2026-04-23-21-03-00 +0000,wsj,"Investors’ Worries for Software’s Future, Midd...",https://www.wsj.com/finance/stocks/investors-w...
3,2026-04-23-21-02-19 +0000,nyt,Lebanese Journalist Killed in Israeli Strike W...,https://www.nytimes.com/2026/04/23/world/middl...
4,2026-04-23-20-59-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2327/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
13   trump     32
9     iran     24
5      new     21
10     war     17
200     up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
225,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...,102
1,2026-04-23-21-03-29 +0000,nyt,Iran War Live Updates: Trump to Host Israeli a...,https://www.nytimes.com/live/2026/04/23/world/...,98
320,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,95
311,2026-04-23-04-01-05 +0000,nyt,War in Iran Gives New Fuel to a Tax Debate in ...,https://www.nytimes.com/2026/04/23/world/asia/...,79
163,2026-04-23-16-02-26 +0000,wapo,Trump ally asked FIFA to have Italy replace Ir...,https://www.washingtonpost.com/world/2026/04/2...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
225,102,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...
320,71,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
361,65,2026-04-22-22-11-28 +0000,nyt,"Heidi O’Neill, Formerly of Nike, Will Be New L...",https://www.nytimes.com/2026/04/22/business/lu...
165,52,2026-04-23-15-57-53 +0000,nypost,Zohran Mamdani rips Warner Bros. Discovery’s P...,https://nypost.com/2026/04/23/business/zohran-...
224,47,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
86,43,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
348,41,2026-04-22-23-07-43 +0000,nypost,Elon Musk says Tesla expenses will rise ‘subst...,https://nypost.com/2026/04/22/business/elon-mu...
313,38,2026-04-23-02-54-06 +0000,nypost,Prediction market platform Kalshi suspends 3 c...,https://nypost.com/2026/04/22/us-news/predicti...
257,38,2026-04-23-11-09-00 +0000,wsj,There’s still one thing that unites us: Congre...,https://www.wsj.com/politics/policy/who-approv...
53,37,2026-04-23-19-30-00 +0000,cbc,"Fire truck heard 'stop, stop, stop' before dea...",https://www.cbc.ca/news/world/ntsb-laguardia-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)