## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-28-04-25-04 +0000,startribune,Israel says it faces first incoming missile fr...,https://www.startribune.com/israel-launches-ne...
1,2026-03-28-04-22-13 +0000,nyt,Iran War Live Updates: 12 U.S. Troops Injured ...,https://www.nytimes.com/live/2026/03/27/world/...
2,2026-03-28-04-20-47 +0000,nyt,"At CPAC, the ‘America First’ Crowd Ponders Giv...",https://www.nytimes.com/2026/03/27/us/politics...
3,2026-03-28-04-12-37 +0000,startribune,"Day 4 results: Goodhue, Minnehaha Academy win ...",https://www.startribune.com/minnesota-boys-bas...
4,2026-03-28-04-02-06 +0000,nyt,House Vote Sets Up Clash With the Senate on D....,https://www.nytimes.com/2026/03/27/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10    iran     42
6      war     34
73   trump     29
69     new     16
322   will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
255,2026-03-27-13-50-03 +0000,nypost,"Dow enters correction territory, oil jumps abo...",https://nypost.com/2026/03/27/business/dow-fal...,113
199,2026-03-27-16-43-10 +0000,latimes,"Iran war rages on heading into fifth week, as ...",https://www.latimes.com/world-nation/story/202...,112
84,2026-03-27-22-00-42 +0000,nypost,Trump considers renaming Strait of Hormuz afte...,https://nypost.com/2026/03/27/us-news/trump-co...,109
196,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...,105
296,2026-03-27-11-00-00 +0000,nypost,Kevin Warsh confirmation as new Fed chair ‘at ...,https://nypost.com/2026/03/27/business/kevin-w...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
255,113,2026-03-27-13-50-03 +0000,nypost,"Dow enters correction territory, oil jumps abo...",https://nypost.com/2026/03/27/business/dow-fal...
194,91,2026-03-27-17-00-00 +0000,wsj,About a year into the full-blown trade war bet...,https://www.wsj.com/economy/trade/how-trumps-t...
196,76,2026-03-27-16-50-49 +0000,nypost,House GOP rejects Senate-passed DHS funding bi...,https://nypost.com/2026/03/27/us-news/house-re...
57,49,2026-03-27-23-40-40 +0000,nypost,"Ten Americans wounded in Iranian missile, dron...",https://nypost.com/2026/03/27/us-news/ten-amer...
156,43,2026-03-27-18-33-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
160,41,2026-03-27-18-28-28 +0000,nypost,"Gang-rape victim Noelia Castillo, who died of ...",https://nypost.com/2026/03/27/world-news/gang-...
8,40,2026-03-28-03-51-00 +0000,wsj,President Trump signed an executive order to p...,https://www.wsj.com/politics/policy/house-gop-...
30,39,2026-03-28-01-13-37 +0000,nyt,Bank of America Pays $72.5 Million to Settle L...,https://www.nytimes.com/2026/03/27/business/ba...
230,38,2026-03-27-15-18-40 +0000,nypost,Austria plans to ban social media use for unde...,https://nypost.com/2026/03/27/world-news/austr...
73,35,2026-03-27-22-44-48 +0000,nypost,Desperate Rep. Eric Swalwell may have broken e...,https://nypost.com/2026/03/27/us-news/desperat...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)