## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-23-20-54-25 +0000,nyt,Two Former F.B.I. Officials Charged With False...,https://www.nytimes.com/2026/10/23/us/politics...
1,2026-10-23-20-49-36 +0000,nypost,Terrified drivers trapped in flash flood saved...,https://nypost.com/2026/10/23/us-news/4-people...
2,2026-10-23-20-49-09 +0000,nyt,A Simple Way to Benefit From Rising Rates: Buy...,https://www.nytimes.com/2026/10/23/business/in...
3,2026-10-23-20-47-16 +0000,nyt,Appeals Court Backs Trump on Constitutionality...,https://www.nytimes.com/2026/10/23/us/politics...
4,2026-10-23-20-47-00 +0000,wsj,Oil Futures Post Weekly Gains on Middle East E...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
28   trump     51
693     up     19
181    new     17
794     he     14
108   race     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
169,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...,118
340,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,118
285,2026-10-23-09-30-00 +0000,wsj,Capital Account: President Trump once called “...,https://www.wsj.com/economy/trade/how-tariffs-...,112
151,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,101
321,2026-10-23-04-00-06 +0000,nypost,Trump says it’s ‘not looking good’ for Ilhan O...,https://nypost.com/2026/10/23/us-news/trump-sa...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
169,118,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...
66,73,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...
182,67,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls o...,https://nypost.com/2026/10/23/business/oil-pri...
146,60,2026-10-23-16-09-49 +0000,nypost,Apple fanatics line up overnight for new folda...,https://nypost.com/2026/10/23/business/apple-f...
14,59,2026-10-23-20-33-00 +0000,wsj,The U.S. is expected to remove 50% tariffs on ...,https://www.wsj.com/politics/policy/trump-expe...
340,57,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
181,52,2026-10-23-14-52-42 +0000,nypost,Racist terrorist using military-grade weapon k...,https://nypost.com/2026/10/23/world-news/suspe...
397,48,2026-10-22-21-00-40 +0000,latimes,Judge limits election-related immigration stop...,https://www.latimes.com/politics/story/2026-10...
173,47,2026-10-23-15-06-51 +0000,chitri,Melania Trump helps forge a ceasefire deal in ...,https://www.chicagotribune.com/2026/10/23/mela...
243,40,2026-10-23-11-01-29 +0000,cbc,Netanyahu orders West Bank closure as Israeli ...,https://www.cbc.ca/news/world/israel-west-bank...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)