## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-11-01-13-55-03 +0000,nypost,Hochul slammed for cameo in Netflix doc on ‘Co...,https://nypost.com/2026/11/01/us-news/hochul-s...
1,2026-11-01-13-31-09 +0000,nyt,India’s Congress Party Holds Mass Protest in N...,https://www.nytimes.com/2026/10/31/world/asia/...
2,2026-11-01-13-24-16 +0000,nypost,Mass shooting at Halloween party near U. Delaw...,https://nypost.com/2026/11/01/us-news/mass-sho...
3,2026-11-01-13-11-37 +0000,bbc,Crypto firm Binance covers 90% of losses after...,https://www.bbc.co.uk/news/articles/ckpdg3ql41...
4,2026-11-01-13-00-13 +0000,nyt,Social Security Email Praising Trump May Viola...,https://www.nytimes.com/2026/11/01/us/election...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2672/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
41       trump     25
195   election     10
400         up      9
21   halloween      9
18         new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...,63
146,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...,61
102,2026-11-01-00-41-24 +0000,bbc,Judge dismisses Trump's lawsuit against Wall S...,https://www.bbc.co.uk/news/articles/cwr5yj2lj9...,58
137,2026-10-31-21-01-29 +0000,nyt,Judge Tosses Trump’s $10 Billion Suit Against ...,https://www.nytimes.com/2026/10/31/business/me...,58
134,2026-10-31-21-07-00 +0000,wsj,Judge Dismisses Trump’s Lawsuit Against Wall S...,https://www.wsj.com/us-news/law/judge-dismisse...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,63,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...
197,41,2026-10-31-14-00-00 +0000,wsj,"Polling data remains at issue after Brazil, Se...",https://www.wsj.com/politics/elections/predict...
59,38,2026-11-01-07-26-18 +0000,nypost,FBI visits ‘Decoy Dan’ Sullivan donors as feds...,https://nypost.com/2026/11/01/us-news/alaska-s...
146,36,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...
2,32,2026-11-01-13-24-16 +0000,nypost,Mass shooting at Halloween party near U. Delaw...,https://nypost.com/2026/11/01/us-news/mass-sho...
191,32,2026-10-31-14-33-38 +0000,nypost,El Sayed courted voters at mosques where speak...,https://nypost.com/2026/10/31/us-news/el-sayed...
169,25,2026-10-31-17-53-35 +0000,bbc,Ukrainian evacuees reunite with family after y...,https://www.bbc.co.uk/news/articles/cqx2818elr...
32,24,2026-11-01-10-30-00 +0000,wsj,It’s the most expensive election in history. T...,https://www.wsj.com/politics/elections/midterm...
118,24,2026-10-31-22-25-51 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
139,23,2026-10-31-20-44-33 +0000,nypost,"If Iran war erupts, Israel may be plotting ano...",https://nypost.com/2026/10/31/world-news/israe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)