## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-20-52-47 +0000,wapo,Trump administration asks Supreme Court to all...,https://www.washingtonpost.com/politics/2026/0...
1,2026-09-03-20-50-04 +0000,startribune,Maria Bartiromo out at Fox News after more tha...,https://www.startribune.com/fox-news-parts-way...
2,2026-09-03-20-48-43 +0000,nypost,How an undercover expose as a Playboy bunny la...,https://nypost.com/2026/09/03/us-news/how-a-gi...
3,2026-09-03-20-48-38 +0000,nyt,"Mortgage Rates Hit 6.71%, Their Highest Level ...",https://www.nytimes.com/2026/09/03/business/mo...
4,2026-09-03-20-48-09 +0000,nyt,"Norway Seizes Russian Ship, Testing Moscow in ...",https://www.nytimes.com/2026/09/03/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     41
408     new     21
58       up     17
227  clancy     17
146    iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
348,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,120
85,2026-09-03-18-34-16 +0000,nypost,Vance says no ‘security concern’ behind Trump ...,https://nypost.com/2026/09/03/us-news/vance-sa...,104
287,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,99
302,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...,99
20,2026-09-03-20-22-43 +0000,wapo,Vance says he doesn’t know when Iran conflict ...,https://www.washingtonpost.com/politics/2026/0...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
348,120,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...
20,91,2026-09-03-20-22-43 +0000,wapo,Vance says he doesn’t know when Iran conflict ...,https://www.washingtonpost.com/politics/2026/0...
292,71,2026-09-03-10-00-00 +0000,nypost,Dem NY House candidate Cait Conley ripped over...,https://nypost.com/2026/09/03/us-news/ny-dem-c...
52,59,2026-09-03-19-36-42 +0000,nypost,Lindsay Clancy’s lawyer drops courtroom bombsh...,https://nypost.com/2026/09/03/us-news/lindsay-...
119,53,2026-09-03-17-43-33 +0000,latimes,"Fox News cuts ties with Maria Bartiromo, weeks...",https://www.latimes.com/entertainment-arts/bus...
117,50,2026-09-03-17-46-46 +0000,nypost,"Dow jumps over 600 points, Treasury yields and...",https://nypost.com/2026/09/03/business/dow-jum...
361,49,2026-09-03-01-00-00 +0000,wsj,With conservative figures such as Steve Bannon...,https://www.wsj.com/politics/policy/bernie-aoc...
191,46,2026-09-03-15-30-22 +0000,nypost,Billionaire Leon Black sues House Oversight Co...,https://nypost.com/2026/09/03/us-news/billiona...
260,41,2026-09-03-11-26-18 +0000,latimes,"Gloria Steinem, charismatic feminist and co-fo...",https://www.latimes.com/world-nation/story/202...
204,39,2026-09-03-14-50-00 +0000,wsj,The Dutch central bank said it moved around 86...,https://www.wsj.com/economy/central-banking/ne...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)