## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-07-05-02 +0000,nypost,Rubio begins three-nation NATO tour in Iceland...,https://nypost.com/2026/10/06/world-news/rubio...
1,2026-10-06-07-03-35 +0000,bbc,Lego fraudster among last year's most high-pro...,https://www.bbc.co.uk/news/articles/cm86z9npj5...
2,2026-10-06-07-02-29 +0000,nyt,"India Cut 130 Million From Voter Roll, Fueling...",https://www.nytimes.com/2026/10/06/world/asia/...
3,2026-10-06-07-02-24 +0000,bbc,Trump says 'threat' led US to pull bombers fro...,https://www.bbc.co.uk/news/articles/cwj3413e5m...
4,2026-10-06-07-01-51 +0000,nyt,U.S. Rushes to Withdraw Bombers From U.K. Air ...,https://www.nytimes.com/2026/10/04/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
40        new     31
9       trump     29
513     house     20
331     court     16
259  election     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
144,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,173
90,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,119
215,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,102
376,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,93
241,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
144,173,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
90,119,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
241,90,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
113,72,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
389,53,2026-10-05-10-18-47 +0000,bbc,Spanish PM Sánchez calls early election after ...,https://www.bbc.co.uk/news/articles/cmdx39k49x...
59,52,2026-10-06-02-22-24 +0000,bbc,Fort Hood shooter to be executed by firing squ...,https://www.bbc.co.uk/news/articles/cq8ezkkkrp...
78,51,2026-10-06-01-30-00 +0000,nypost,Bay Area father leaves 3 young kids home alone...,https://nypost.com/2026/10/05/us-news/morgan-h...
211,43,2026-10-05-19-03-08 +0000,nypost,Sailors reportedly offered $25K per trip to mo...,https://nypost.com/2026/10/05/business/sailors...
382,41,2026-10-05-10-29-00 +0000,wsj,FBI Arrests Alleged Chinese Agent Accused of S...,https://www.wsj.com/world/china/fbi-arrests-al...
53,40,2026-10-06-02-46-42 +0000,nypost,Trump signs executive order mid-rally allowing...,https://nypost.com/2026/10/05/us-news/trump-si...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)