## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-16-10-28 +0000,nyt,"At the tall ships parade, a historic bell ring...",https://www.nytimes.com/live/2026/07/04/us/ame...
1,2026-07-04-16-03-25 +0000,nypost,Active duty Naval officer from Seattle thrille...,https://nypost.com/2026/07/04/us-news/active-d...
2,2026-07-04-16-01-10 +0000,nypost,Parade of Tall Ships cruises through New York ...,https://nypost.com/2026/07/04/us-news/parade-o...
3,2026-07-04-15-56-32 +0000,wapo,Celebrations for America’s 250th begin amid he...,https://www.washingtonpost.com/nation/2026/07/...
4,2026-07-04-15-46-41 +0000,nyt,"It’s heat dome 1, George Washington 0.",https://www.nytimes.com/live/2026/07/04/us/ame...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
64     trump     27
25        th     19
62      july     17
28   america     17
401    world     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,87
7,2026-07-04-15-41-47 +0000,nypost,JD Vance celebrates ‘250 years of America faci...,https://nypost.com/2026/07/04/us-news/jd-vance...,73
120,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,73
112,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...,72
10,2026-07-04-15-20-47 +0000,bbc,"Fireworks, flyovers and a 'really long' Trump ...",https://www.bbc.co.uk/news/articles/cp36l4e6v9...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,87,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
7,73,2026-07-04-15-41-47 +0000,nypost,JD Vance celebrates ‘250 years of America faci...,https://nypost.com/2026/07/04/us-news/jd-vance...
120,46,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...
112,41,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
57,39,2026-07-04-11-48-23 +0000,nyt,"For Cape Verde, There’s Victory in Their World...",https://www.nytimes.com/2026/07/04/world/afric...
167,35,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
78,32,2026-07-04-10-00-00 +0000,latimes,Want an AI-proof job? New research says you ma...,https://www.latimes.com/business/story/2026-07...
85,28,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...
51,26,2026-07-04-12-27-13 +0000,cbc,St. Petersburg oil terminal hit as Ukraine pre...,https://www.cbc.ca/news/world/st-petersburg-oi...
125,26,2026-07-04-02-00-00 +0000,wsj,Germany’s midsize “Mittelstand” companies once...,https://www.wsj.com/economy/china-is-devastati...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)