## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-07-08-35 +0000,bbc,"Greens can move Labour in the right direction,...",https://www.bbc.co.uk/news/articles/cmx239469k...
1,2026-10-03-07-06-15 +0000,nypost,Minneapolis councilman mocked after claiming s...,https://nypost.com/2026/10/03/us-news/minneapo...
2,2026-10-03-07-03-28 +0000,nypost,NY airport X-ray exposes dangerous weapon ille...,https://nypost.com/2026/10/03/us-news/ny-airpo...
3,2026-10-03-07-00-40 +0000,nyt,Student Protests Rattle France as Police Clash...,https://www.nytimes.com/2026/10/02/world/europ...
4,2026-10-03-06-56-19 +0000,bbc,"Tories pledge to build 50,000 new prison places",https://www.bbc.co.uk/news/articles/ck9qrqq53n...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2437/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
79      trump     39
53   flydubai     22
328       was     18
55      pilot     17
468    market     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
362,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...,128
363,2026-10-02-09-08-06 +0000,bbc,'I was not going to let others die' - pilot of...,https://www.bbc.co.uk/news/articles/c639m98gde...,116
152,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...,111
323,2026-10-02-11-20-46 +0000,chitri,‘I was fighting for my life’: Indian pilot hai...,https://www.chicagotribune.com/2026/10/02/indi...,108
353,2026-10-02-09-36-47 +0000,cbc,'I was fighting for my life': Indian pilot hai...,https://www.cbc.ca/news/world/flydubai-pilot-i...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
362,128,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...
152,111,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
252,68,2026-10-02-15-21-30 +0000,cbc,G7 nations agree to release 100 million barrel...,https://www.cbc.ca/news/business/g7-trump-dies...
240,67,2026-10-02-15-50-14 +0000,nyt,Soft Jobs Report Boosts Market Bets Fed Will S...,https://www.nytimes.com/2026/10/02/business/ec...
141,65,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
23,55,2026-10-03-03-48-51 +0000,nypost,Christa Pike thought her arm would ‘burst open...,https://nypost.com/2026/10/02/us-news/christa-...
32,49,2026-10-03-02-20-03 +0000,nypost,Gavin Newsom vetoes bill giving California hig...,https://nypost.com/2026/10/02/us-news/gavin-ne...
352,48,2026-10-02-09-58-00 +0000,wsj,Police score big bucks with little work in Tru...,https://www.wsj.com/politics/policy/democratic...
342,45,2026-10-02-10-00-00 +0000,latimes,"Hiltzik: Sure, use Meta's Muse bot to help wit...",https://www.latimes.com/business/story/2026-10...
311,44,2026-10-02-12-20-56 +0000,cbc,Cornell 7: Governor vows to change N.Y. rape l...,https://www.cbc.ca/news/world/cornell-investig...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)