## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-17-15-00 +0000,wsj,Keurig Dr Pepper First-Quarter Sales Rise on G...,https://www.wsj.com/business/earnings/keurig-d...
1,2026-04-23-17-12-05 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...
2,2026-04-23-17-11-33 +0000,missionlocal,S.F. Board of Supervisors is too deferential t...,https://missionlocal.org/2026/04/sf-mayor-boar...
3,2026-04-23-17-05-51 +0000,nyt,Afghans Who Helped U.S. Forces Say They’re Bei...,https://www.nytimes.com/2026/04/23/world/asia/...
4,2026-04-23-17-02-08 +0000,latimes,"Dementia patient beaten, set on fire and kille...",https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2609/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
14    trump     40
10     iran     36
142     new     27
11      war     25
21   hormuz     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-23-17-12-05 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...,163
146,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...,141
306,2026-04-22-21-43-55 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...,135
310,2026-04-22-21-33-05 +0000,wapo,Iran says it seized 2 ships in Strait of Hormu...,https://www.washingtonpost.com/world/2026/04/2...,123
249,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,163,2026-04-23-17-12-05 +0000,nyt,Iran War Live Updates: Trump Threatens Iranian...,https://www.nytimes.com/live/2026/04/23/world/...
296,85,2026-04-22-22-11-28 +0000,nyt,"Heidi O’Neill, Formerly of Nike, Will Be New L...",https://www.nytimes.com/2026/04/22/business/lu...
249,57,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
47,50,2026-04-23-16-19-39 +0000,nypost,Warner Bros. Discovery shareholders vote to ap...,https://nypost.com/2026/04/23/media/warner-bro...
304,50,2026-04-22-21-52-00 +0000,wsj,Here are the key takeaways after Health Secret...,https://www.wsj.com/politics/policy/lawmakers-...
282,49,2026-04-22-23-01-40 +0000,nypost,6 leading California gubernatorial candidates ...,https://nypost.com/2026/04/22/us-news/how-to-w...
145,47,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
6,39,2026-04-23-17-00-11 +0000,wapo,"Once accused of election fraud, former small-t...",https://www.washingtonpost.com/nation/2026/04/...
216,39,2026-04-23-08-12-48 +0000,nypost,"Senate passes $70B budget plan to fund ICE, Bo...",https://nypost.com/2026/04/23/us-news/senate-p...
73,38,2026-04-23-15-54-10 +0000,nypost,Tesla’s stock drops on Elon Musk’s $25B AI bet...,https://nypost.com/2026/04/23/business/teslas-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)