## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-12-55-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
1,2026-08-31-12-55-00 +0000,wsj,U.S. Natural Gas Futures Start Week Lower,https://www.wsj.com/finance/commodities-future...
2,2026-08-31-12-48-04 +0000,nyt,"More Mail Ballots Are Arriving Late This Year,...",https://www.nytimes.com/2026/08/31/us/politics...
3,2026-08-31-12-48-00 +0000,wsj,Courting Consumers at the U.S. Open,https://www.wsj.com/cmo-today/courting-consume...
4,2026-08-31-12-44-00 +0000,wsj,Long-Dated Treasury Yields Edge Up as 10-Year ...,https://www.wsj.com/finance/investing/u-s-trea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2513/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35   trump     18
40    iran     17
30      up     14
67   first     13
352  nepal     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...,79
5,2026-08-31-12-28-07 +0000,nypost,Trump calls for leaders of ‘failed nation’ Ira...,https://nypost.com/2026/08/31/world-news/trump...,70
0,2026-08-31-12-55-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...,60
228,2026-08-30-16-31-00 +0000,wsj,Opinion | Trump’s New Iran Sanctions Put China...,https://www.wsj.com/opinion/trumps-new-iran-sa...,60
221,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,79,2026-08-31-10-23-07 +0000,nypost,Trump posts AI-generated video of Iran’s Kharg...,https://nypost.com/2026/08/31/us-news/trump-po...
0,60,2026-08-31-12-55-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
4,51,2026-08-31-12-44-00 +0000,wsj,Long-Dated Treasury Yields Edge Up as 10-Year ...,https://www.wsj.com/finance/investing/u-s-trea...
152,50,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
98,40,2026-08-31-08-53-10 +0000,nypost,Death toll tops 900 in Nepal-Tibet flooding as...,https://nypost.com/2026/08/31/world-news/death...
221,38,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...
34,36,2026-08-31-10-55-00 +0000,wsj,The Texas Senate race is shaping up to be a co...,https://www.wsj.com/politics/ken-paxton-is-in-...
224,33,2026-08-30-16-35-53 +0000,nypost,Top US data companies supplying data to Chines...,https://nypost.com/2026/08/30/us-news/us-data-...
252,30,2026-08-30-14-16-40 +0000,chitri,"Iran’s leader calls for Muslim unity, NBC crew...",https://www.chicagotribune.com/2026/08/30/nbc-...
7,29,2026-08-31-12-20-57 +0000,nyt,Global Oil Price Rises to $90 a Barrel After U...,https://www.nytimes.com/2026/08/31/business/oi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)