## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-20-11-46-22 +0000,nypost,"1 killed, 7 hurt on Jersey Shore after driver,...",https://nypost.com/2026/09/20/us-news/1-killed...
1,2026-09-20-11-42-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
2,2026-09-20-11-22-21 +0000,bbc,Billionaire Man United owner loses moral high ...,https://www.bbc.co.uk/news/articles/cm0rexrwjj...
3,2026-09-20-11-21-34 +0000,bbc,Lib Dems vow to end 'computer says no' economy...,https://www.bbc.co.uk/news/articles/cqrk31k7pp...
4,2026-09-20-11-18-00 +0000,wsj,The Romanian Crime Rings Draining U.S. Welfare...,https://www.wsj.com/business/the-romanian-crim...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
105   trump     37
316      ai     14
122     new     11
461   house     10
86   attack     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...,96
175,2026-09-19-14-51-03 +0000,cbc,"CNN, MS NOW, Politico say journalists denied a...",https://www.cbc.ca/news/world/cnn-journalists-...,90
112,2026-09-19-21-41-39 +0000,wapo,"CNN, MS NOW, Politico say journalists blocked ...",https://www.washingtonpost.com/politics/2026/0...,85
135,2026-09-19-19-13-51 +0000,wapo,"Trump to form ‘AI Force,’ name AI czar but rej...",https://www.washingtonpost.com/politics/2026/0...,81
68,2026-09-20-02-57-28 +0000,nyt,"CNN, MS NOW and Politico Barred From White Hou...",https://www.nytimes.com/2026/09/19/business/me...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,96,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...
53,49,2026-09-20-06-25-15 +0000,nypost,Saudi Arabia confirms Yemen’s Houthi rebels tr...,https://nypost.com/2026/09/20/world-news/saudi...
135,44,2026-09-19-19-13-51 +0000,wapo,"Trump to form ‘AI Force,’ name AI czar but rej...",https://www.washingtonpost.com/politics/2026/0...
1,37,2026-09-20-11-42-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
90,33,2026-09-20-00-11-50 +0000,nypost,Michael Goodwin: Iran will be top of mind at t...,https://nypost.com/2026/09/19/us-news/un-week-...
56,32,2026-09-20-05-01-47 +0000,bbc,Watch: Fans react as Ed Sheeran speaks out ove...,https://www.bbc.co.uk/news/videos/ck980m0pr1e0...
63,32,2026-09-20-04-06-12 +0000,nypost,New Jersey mom charged with obstruction after ...,https://nypost.com/2026/09/20/us-news/nj-mom-j...
49,29,2026-09-20-07-20-44 +0000,nypost,"Ukraine fires over 1,000 drones at Russia in ‘...",https://nypost.com/2026/09/20/world-news/one-o...
111,28,2026-09-19-21-43-54 +0000,nypost,German synagogue fire arson suspect arrested a...,https://nypost.com/2026/09/19/world-news/arson...
141,26,2026-09-19-18-40-38 +0000,latimes,Newsom signs bills to shield California electi...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)