## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-16-23-17-46 +0000,bbc,Group planned to attack White House UFC event ...,https://www.bbc.com/news/articles/cqx10xlje1lo...
1,2026-06-16-23-15-53 +0000,nyt,Obama’s Nuclear Deal Looms Over Trump’s Iran N...,https://www.nytimes.com/2026/06/16/us/politics...
2,2026-06-16-23-15-00 +0000,wsj,Australian Predictive Healthcare Startup Raise...,https://www.wsj.com/pro/private-equity/austral...
3,2026-06-16-23-11-03 +0000,nyt,Iran War Live Updates: Trump Says He Hopes to ...,https://www.nytimes.com/live/2026/06/16/world/...
4,2026-06-16-23-10-24 +0000,nyt,Internal Emails Raise Questions About D.H.S. E...,https://www.nytimes.com/2026/06/16/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2549/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
15   trump     39
16    iran     32
68     new     24
13    deal     22
122  world     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...,128
3,2026-06-16-23-11-03 +0000,nyt,Iran War Live Updates: Trump Says He Hopes to ...,https://www.nytimes.com/live/2026/06/16/world/...,122
210,2026-06-16-14-52-36 +0000,nypost,Trump says he’ll read the text of Iran deal al...,https://nypost.com/2026/06/16/us-news/trump-sa...,120
312,2026-06-16-08-07-32 +0000,bbc,"Trump may release US-Iran deal before Friday, ...",https://www.bbc.com/news/articles/ce8mv6l6eezo...,117
208,2026-06-16-14-53-12 +0000,nypost,Trump says he ‘never cared’ about Iran regime ...,https://nypost.com/2026/06/16/us-news/trump-sa...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,128,2026-06-16-16-51-49 +0000,nypost,Trump will allow Iran to sell its oil under de...,https://nypost.com/2026/06/16/us-news/trump-wi...
174,78,2026-06-16-16-37-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
53,62,2026-06-16-21-46-00 +0000,wsj,"SpaceX overtakes Amazon by market cap, Iran wi...",https://www.wsj.com/politics/policy/spacex-now...
321,61,2026-06-16-06-38-00 +0000,wsj,The Bank of Japan raised interest rates to a 3...,https://www.wsj.com/economy/central-banking/ba...
350,61,2026-06-16-00-57-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
87,50,2026-06-16-20-59-31 +0000,cbc,Ghanaian midfielder Thomas Partey loses bid to...,https://www.cbc.ca/news/canada/ghana-partey-ca...
162,49,2026-06-16-17-14-32 +0000,nypost,Terrified woman backed out of bungee jump mome...,https://nypost.com/2026/06/16/world-news/woman...
270,45,2026-06-16-10-38-31 +0000,nypost,FBI arrests 5 people in connection with drone ...,https://nypost.com/2026/06/16/us-news/fbi-arre...
308,40,2026-06-16-09-00-00 +0000,wsj,The Liberty Justice Center won its biggest-eve...,https://www.wsj.com/politics/policy/how-a-cons...
294,40,2026-06-16-09-42-29 +0000,nypost,Macron tells Zelensky he had ‘difficult’ meeti...,https://nypost.com/2026/06/16/us-news/macron-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)