## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-12-19-00 +0000,wsj,Airbus to Get $3.42 Billion Loan From European...,https://www.wsj.com/world/europe/airbus-to-get...
1,2026-06-29-12-17-43 +0000,nyt,Platner Has Slight Edge Over Collins in Tight ...,https://www.nytimes.com/2026/06/29/us/politics...
2,2026-06-29-12-17-43 +0000,bbc,"Five dead following shooting in Stade, norther...",https://www.bbc.co.uk/news/articles/c17yzzw1vk...
3,2026-06-29-12-17-24 +0000,nyt,Mideast Live Updates: U.S. and Iran Set for Ne...,https://www.nytimes.com/live/2026/06/29/world/...
4,2026-06-29-12-17-23 +0000,nyt,Ships Pull Back Amid Heightened Risk From Iran...,https://www.nytimes.com/2026/06/29/business/ir...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
29        iran     13
201         he     10
146  venezuela      9
33       trump      9
117    burnham      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
228,2026-06-28-13-31-18 +0000,nypost,Iran must develop nuclear bomb to protect ‘pea...,https://nypost.com/2026/06/28/world-news/iran-...,43
157,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...,43
208,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...,41
196,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...,41
30,2026-06-29-11-04-00 +0000,wsj,Sen. Bernie Sanders of Vermont looks to have m...,https://www.wsj.com/politics/michigan-senate-p...,40

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
228,43,2026-06-28-13-31-18 +0000,nypost,Iran must develop nuclear bomb to protect ‘pea...,https://nypost.com/2026/06/28/world-news/iran-...
208,41,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...
196,41,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...
214,34,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
14,33,2026-06-29-11-57-21 +0000,nyt,"Andy Burnham, the UK’s Likely Next Prime Minis...",https://www.nytimes.com/2026/06/29/world/europ...
60,31,2026-06-29-10-00-00 +0000,startribune,Officials tried to protect a baby girl born at...,https://www.startribune.com/officials-tried-to...
89,31,2026-06-29-08-43-39 +0000,nypost,US-brokered peace agreement with Israel ‘will ...,https://nypost.com/2026/06/29/world-news/leban...
30,30,2026-06-29-11-04-00 +0000,wsj,Sen. Bernie Sanders of Vermont looks to have m...,https://www.wsj.com/politics/michigan-senate-p...
84,28,2026-06-29-09-00-00 +0000,wsj,"The University of California, Berkeley plans t...",https://www.wsj.com/us-news/education/nancy-pe...
71,27,2026-06-29-09-21-06 +0000,nyt,"In Venezuela, a Community Comes Together to Se...",https://www.nytimes.com/2026/06/28/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)