## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-07-06-26 +0000,nypost,"Trump says ‘massive’ oil, gas, mineral explora...",https://nypost.com/2026/10/14/business/trump-s...
1,2026-10-14-07-05-32 +0000,bbc,India's 'cockroach' leaders jailed after holdi...,https://www.bbc.co.uk/news/articles/c6q8n09l1n...
2,2026-10-14-07-02-50 +0000,bbc,Russia arrests Japanese journalist on spying c...,https://www.bbc.co.uk/news/articles/cwp9g1el7x...
3,2026-10-14-06-52-33 +0000,bbc,'Spray and pray': How AI job applications can ...,https://www.bbc.co.uk/news/articles/c623dnkn8p...
4,2026-10-14-06-42-00 +0000,wsj,BOE’s Pill ‘Skeptical’ Four Rate Rises Needed ...,https://www.wsj.com/world/uk/boes-pill-skeptic...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2355/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
0        trump     41
22          ai     21
548        new     17
499   kimberly     15
500  guilfoyle     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,158
321,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,134
291,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,123
142,2026-10-13-21-54-45 +0000,nypost,Trump personally prepped Katie Zacharia for fi...,https://nypost.com/2026/10/13/us-news/trump-pe...,118
276,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,158,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
85,100,2026-10-14-01-00-00 +0000,wsj,"Trying to save her job, Kimberly Guilfoyle cla...",https://www.wsj.com/politics/policy/kimberly-g...
60,77,2026-10-14-02-17-29 +0000,nypost,Six Flags’ ‘Goliath’ coaster rider who fell to...,https://nypost.com/2026/10/13/us-news/six-flag...
107,70,2026-10-13-23-21-01 +0000,nypost,Ilhan Omar’s husband spotted for first time si...,https://nypost.com/2026/10/13/us-news/ilhan-om...
57,62,2026-10-14-02-31-00 +0000,wsj,Georgia’s Democratic senator Jon Ossoff says h...,https://www.wsj.com/politics/elections/jon-oss...
291,58,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...
370,56,2026-10-13-11-12-24 +0000,chitri,Vatican says Pope Leo XIV has lung cancer and ...,https://www.chicagotribune.com/2026/10/13/pope...
168,55,2026-10-13-21-13-00 +0000,wsj,Kimberly Guilfoyle resigned as the U.S. ambass...,https://www.wsj.com/politics/policy/kimberly-g...
363,50,2026-10-13-11-48-06 +0000,nypost,Ukraine got no warning about latest Russian st...,https://nypost.com/2026/10/13/world-news/ukrai...
402,48,2026-10-13-09-38-54 +0000,bbc,UK growth forecast upgraded but higher energy ...,https://www.bbc.co.uk/news/articles/cmglw0r21z...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)