## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-20-22-03-26 +0000,bbc,Apple names new chief executive to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
1,2026-04-20-22-03-00 +0000,wsj,Opinion | The U.N. May Make Ocean Cruises More...,https://www.wsj.com/opinion/the-u-n-may-make-o...
2,2026-04-20-22-02-06 +0000,bbc,Are insider traders making millions from the I...,https://www.bbc.com/news/videos/cwyveyl4ez7o?a...
3,2026-04-20-22-01-27 +0000,nypost,Fired Adams staffer returns to City Hall with ...,https://nypost.com/2026/04/20/us-news/fired-ad...
4,2026-04-20-22-01-00 +0000,wsj,Apple Hardware Executive John Ternus to Become...,https://www.wsj.com/tech/apple-announces-ceo-j...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2503/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
16         iran     25
35        trump     21
2           new     19
17          war     12
102  california     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
255,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...,106
196,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...,105
226,2026-04-20-13-22-31 +0000,nypost,Trump tells The Post he’s willing to meet with...,https://nypost.com/2026/04/20/us-news/jd-vance...,96
5,2026-04-20-21-59-02 +0000,nyt,Iran War Live Updates: Tehran and Trump Send S...,https://www.nytimes.com/live/2026/04/20/world/...,83
141,2026-04-20-17-38-47 +0000,nypost,Dramatic video shows US Marines rappelling ont...,https://nypost.com/2026/04/20/world-news/drama...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
255,106,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...
196,80,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...
322,46,2026-04-19-23-07-52 +0000,bbc,'They told me he was dead': Children born near...,https://www.bbc.com/news/articles/c895k3537kgo...
20,44,2026-04-20-21-44-25 +0000,cbc,"Tim Cook stepping down as Apple CEO, handing r...",https://www.cbc.ca/news/business/tim-cook-step...
284,44,2026-04-20-09-00-07 +0000,wapo,Gas prices threaten GOP in race that could hel...,https://www.washingtonpost.com/business/2026/0...
35,41,2026-04-20-21-23-13 +0000,nypost,Labor Secretary Lori Chavez-DeRemer resigns fr...,https://nypost.com/2026/04/20/us-news/labor-se...
251,38,2026-04-20-10-58-00 +0000,wsj,There will be a lot of noise in the next few d...,https://www.wsj.com/politics/heres-what-to-kno...
86,38,2026-04-20-19-51-00 +0000,wsj,Senate Democrats plan to press Fed chair nomin...,https://www.wsj.com/economy/central-banking/ke...
171,38,2026-04-20-16-32-34 +0000,nypost,"FBI Director Kash Patel sues The Atlantic, rep...",https://nypost.com/2026/04/20/media/fbi-direct...
74,36,2026-04-20-20-19-57 +0000,bbc,Woman and child jumped off roof to escape dead...,https://www.bbc.com/news/articles/cj0v36vell4o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)