## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-02-54-13 +0000,startribune,Friday night rewind: Eden Prairie beats Wayzat...,https://www.startribune.com/minnesota-high-sch...
1,2026-10-24-02-52-16 +0000,nypost,"Autistic man, 33, dies after fight outside NYC...",https://nypost.com/2026/10/23/us-news/autistic...
2,2026-10-24-02-52-10 +0000,bbc,Tory activist in 'contract killing broker' cla...,https://www.bbc.co.uk/news/articles/c63r5779vy...
3,2026-10-24-02-35-37 +0000,nyt,Justice Dept. Demands That California Counties...,https://www.nytimes.com/2026/10/23/us/justice-...
4,2026-10-24-02-35-00 +0000,wsj,JetBlue Creditors Hire Advisers as Airline’s S...,https://www.wsj.com/pro/bankruptcy/jetblue-cre...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
46     trump     47
292       up     17
412       he     14
229      new     13
464  ukraine     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
64,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,164
225,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...,111
136,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,110
329,2026-10-23-09-30-00 +0000,wsj,Capital Account: President Trump once called “...,https://www.wsj.com/economy/trade/how-tariffs-...,106
207,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
64,164,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
225,64,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...
238,61,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls o...,https://nypost.com/2026/10/23/business/oil-pri...
23,60,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
301,55,2026-10-23-11-00-00 +0000,missionlocal,"Election ad fact-check: Will Props. D, E, and ...",https://missionlocal.org/2026/10/san-francisco...
22,49,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
294,41,2026-10-23-11-01-29 +0000,cbc,Netanyahu orders West Bank closure as Israeli ...,https://www.cbc.ca/news/world/israel-west-bank...
303,40,2026-10-23-10-58-00 +0000,wsj,A wave of retirements is going to wipe out ove...,https://www.wsj.com/politics/policy/congress-w...
57,39,2026-10-23-22-17-24 +0000,nypost,Deranged LA road-rage driver smashes woman’s c...,https://nypost.com/2026/10/23/us-news/violent-...
229,36,2026-10-23-15-06-51 +0000,chitri,Melania Trump helps forge a ceasefire deal in ...,https://www.chicagotribune.com/2026/10/23/mela...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)