## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-01-02-44-56 +0000,nypost,"Missing Republican Oklahoma Senate candidate, ...",https://nypost.com/2026/04/30/us-news/missing-...
1,2026-05-01-02-43-01 +0000,nyt,Decoding the King: Brits Hear Subtle Rebuke to...,https://www.nytimes.com/2026/04/30/world/europ...
2,2026-05-01-02-39-06 +0000,bbc,New footage shows how Trump dinner gunman char...,https://www.bbc.com/news/articles/c4g7rmrlm17o...
3,2026-05-01-02-35-27 +0000,startribune,Live from Game 6: Depleted Timberwolves surge ...,https://www.startribune.com/minnesota-timberwo...
4,2026-05-01-02-26-00 +0000,wsj,Gold Likely to Remain Under Pressure for a Bit,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
15   trump     47
156   iran     28
19     new     27
157    war     21
656  house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
122,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...,148
201,2026-04-30-18-05-26 +0000,bbc,Oil price hits highest since 2022 after report...,https://www.bbc.com/news/articles/cx21m88rd14o...,138
106,2026-04-30-21-46-00 +0000,wsj,President Trump said he would remove tariffs o...,https://www.wsj.com/economy/trade/trump-says-u...,113
235,2026-04-30-16-47-49 +0000,nypost,Fed’s preferred inflation gauge hits 3-year hi...,https://nypost.com/2026/04/30/business/feds-pr...,105
96,2026-04-30-22-03-00 +0000,wsj,Trump’s About to Defy Congress on the Iran War,https://www.wsj.com/finance/investing/trumps-a...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
122,148,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...
235,105,2026-04-30-16-47-49 +0000,nypost,Fed’s preferred inflation gauge hits 3-year hi...,https://nypost.com/2026/04/30/business/feds-pr...
162,77,2026-04-30-19-56-03 +0000,nyt,Supreme Court Voting Rights Ruling Could Fuel ...,https://www.nytimes.com/2026/04/30/us/politics...
18,74,2026-05-01-01-33-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
106,58,2026-04-30-21-46-00 +0000,wsj,President Trump said he would remove tariffs o...,https://www.wsj.com/economy/trade/trump-says-u...
260,56,2026-04-30-16-00-00 +0000,wsj,The Justice Department is launching a West Coa...,https://www.wsj.com/politics/policy/doj-launch...
49,49,2026-05-01-00-00-00 +0000,wsj,Republican leaders are pushing Southern states...,https://www.wsj.com/politics/policy/republican...
58,46,2026-04-30-23-42-57 +0000,latimes,Kiara Brokenbrough went viral for her $500 wed...,https://www.latimes.com/science/story/2026-04-...
28,43,2026-05-01-01-00-00 +0000,wsj,“This is a warning. We know you live right her...,https://www.wsj.com/politics/policy/immigratio...
355,42,2026-04-30-09-30-00 +0000,wsj,"If these were normal times, Jerome Powell woul...",https://www.wsj.com/economy/central-banking/wh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)