## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-09-23-04-07 +0000,nyt,Trump Again Hits Out at NATO Over Iran War,https://www.nytimes.com/2026/04/09/world/middl...
1,2026-04-09-23-03-27 +0000,nyt,Melania Trump Says She Was Not Associated With...,https://www.nytimes.com/2026/04/09/us/politics...
2,2026-04-09-23-02-45 +0000,nyt,How Trump’s Advisers Felt About Going to War W...,https://www.nytimes.com/video/us/politics/1000...
3,2026-04-09-23-00-00 +0000,wsj,"When Gas Prices Rise, They’re Hard to Bring Do...",https://www.wsj.com/finance/commodities-future...
4,2026-04-09-22-58-26 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2485/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4     iran     45
0    trump     44
5      war     27
96    fire     25
311  cease     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
189,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...,184
369,2026-04-09-01-38-00 +0000,wsj,President Trump’s declaration of “total victor...,https://www.wsj.com/politics/national-security...,183
275,2026-04-09-11-32-52 +0000,nypost,Israel wiped out Hezbollah chief’s top secreta...,https://nypost.com/2026/04/09/world-news/israe...,163
50,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,154
367,2026-04-09-01-51-08 +0000,nyt,Trump Finds Himself With Fragile Iran Cease-Fi...,https://www.nytimes.com/2026/04/08/us/politics...,154

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
189,184,2026-04-09-16-29-10 +0000,nypost,Trump warns ‘shootin’ starts’ if Iran fails to...,https://nypost.com/2026/04/09/us-news/trump-wa...
4,84,2026-04-09-22-58-26 +0000,nyt,Iran War Live Updates: Israel Agrees to Talks ...,https://www.nytimes.com/live/2026/04/09/world/...
105,84,2026-04-09-20-18-00 +0000,wsj,First lady Melania Trump denied having ties to...,https://www.wsj.com/politics/melania-trump-den...
127,61,2026-04-09-19-17-15 +0000,nypost,Meta rolls out new AI model in ‘fundamental sh...,https://nypost.com/2026/04/09/business/meta-ro...
36,55,2026-04-09-22-16-15 +0000,latimes,Man was shot at by ICE agents in Northern Cali...,https://www.latimes.com/california/story/2026-...
50,50,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
51,45,2026-04-09-21-53-20 +0000,cbc,Putin claims Russia will enact 32-hour ceasefi...,https://www.cbc.ca/news/world/ukraine-conflict...
30,42,2026-04-09-22-23-35 +0000,latimes,A sea turtle named Meatloaf is fighting to kee...,https://www.latimes.com/california/story/2026-...
101,38,2026-04-09-20-36-41 +0000,bbc,OpenAI pauses UK data centre deal over energy ...,https://www.bbc.com/news/articles/clyd032ej70o...
242,33,2026-04-09-13-54-13 +0000,cbc,K-pop supergroup BTS kick off world tour in So...,https://www.cbc.ca/news/entertainment/bts-worl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)