## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-21-02-23 +0000,nyt,Iran War Live Updates: U.S. Is Said to Have Se...,https://www.nytimes.com/live/2026/03/24/world/...
1,2026-03-24-21-02-05 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/24/world/...
2,2026-03-24-21-01-26 +0000,nypost,Alleged drunk driver extradited from Poland to...,https://nypost.com/2026/03/24/us-news/alleged-...
3,2026-03-24-21-00-00 +0000,nyt,United States Said to Have Sent Iran a Plan to...,https://www.nytimes.com/2026/03/24/world/middl...
4,2026-03-24-20-58-00 +0000,wsj,Israel Hits Russian-Iranian Weapons Smuggling ...,https://www.wsj.com/world/middle-east/israel-h...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2596/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     45
108  trump     36
1      war     26
290    new     17
34     oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
28,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,139
210,2026-03-24-13-17-18 +0000,nypost,Pete Hegseth was ‘the first’ to push for war w...,https://nypost.com/2026/03/24/us-news/pete-heg...,132
0,2026-03-24-21-02-23 +0000,nyt,Iran War Live Updates: U.S. Is Said to Have Se...,https://www.nytimes.com/live/2026/03/24/world/...,131
163,2026-03-24-15-34-19 +0000,nyt,Trump’s Threat to ‘Obliterate’ Iran’s Power St...,https://www.nytimes.com/2026/03/24/us/politics...,129
336,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
28,139,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...
190,82,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
297,62,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
33,60,2026-03-24-20-32-41 +0000,nypost,LaGuardia Airport crash investigators reveal c...,https://nypost.com/2026/03/24/us-news/laguardi...
86,42,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
3,40,2026-03-24-21-00-00 +0000,nyt,United States Said to Have Sent Iran a Plan to...,https://www.nytimes.com/2026/03/24/world/middl...
188,37,2026-03-24-14-44-28 +0000,nypost,UK will lead ‘Hormuz Coalition’ to reopen stra...,https://nypost.com/2026/03/24/world-news/iran-...
77,34,2026-03-24-19-05-33 +0000,nypost,Disgusting picture shows raw meat stacked up o...,https://nypost.com/2026/03/24/us-news/viral-ph...
326,33,2026-03-24-00-47-00 +0000,wsj,The Defense Department introduced new restrict...,https://www.wsj.com/politics/national-security...
45,32,2026-03-24-20-06-31 +0000,startribune,Twin Cities TSA agents talk about working with...,https://www.startribune.com/why-no-long-lines-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)