## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-07-14-15-26 +0000,nypost,Top House Democrat demands Goldman Sachs cut t...,https://nypost.com/2026/08/07/business/top-hou...
1,2026-08-07-14-07-38 +0000,nyt,Weak Jobs Report Does Not Eliminate Prospects ...,https://www.nytimes.com/2026/08/07/business/ec...
2,2026-08-07-14-07-11 +0000,cbc,Saudi Arabia expects imminent 2-pronged attack...,https://www.cbc.ca/news/world/saudi-arabia-ira...
3,2026-08-07-14-06-05 +0000,bbc,I was standing in front of my teacher when she...,https://www.bbc.co.uk/news/articles/c07rxz0303...
4,2026-08-07-14-03-55 +0000,bbc,Surprise fall in US jobs last month as slow su...,https://www.bbc.co.uk/news/articles/c20j5rle71...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
169  trump     39
179    new     27
106     up     15
16    jobs     12
854    out     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
216,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...,117
108,2026-08-07-10-00-00 +0000,wsj,A key Republican senator said she would oppose...,https://www.wsj.com/politics/policy/second-rep...,106
275,2026-08-06-20-46-15 +0000,nypost,Trump signs new executive order to ban ‘birth ...,https://nypost.com/2026/08/06/us-news/trump-si...,105
256,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...,101
240,2026-08-06-22-10-35 +0000,wapo,Trump tries new tack against birthright citize...,https://www.washingtonpost.com/politics/2026/0...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
216,117,2026-08-06-23-30-00 +0000,wsj,President Trump has ordered new probes into di...,https://www.wsj.com/politics/national-security...
256,101,2026-08-06-21-34-00 +0000,wsj,A GOP-controlled Senate committee’s party-line...,https://www.wsj.com/politics/policy/is-fauci-i...
189,63,2026-08-07-01-03-00 +0000,wsj,Rep. Max Miller is lending his re-election cam...,https://www.wsj.com/politics/elections/max-mil...
73,62,2026-08-07-11-16-00 +0000,wsj,It seems like political scandals are happening...,https://www.wsj.com/politics/policy/is-misbeha...
108,58,2026-08-07-10-00-00 +0000,wsj,A key Republican senator said she would oppose...,https://www.wsj.com/politics/policy/second-rep...
255,49,2026-08-06-21-34-00 +0000,wsj,"Trump targets birthright citizenship (again), ...",https://www.wsj.com/politics/policy/trump-trie...
8,48,2026-08-07-13-56-45 +0000,nypost,"Turkey, Pakistan, Saudi Arabia sign mutual def...",https://nypost.com/2026/08/07/world-news/turke...
48,42,2026-08-07-12-55-35 +0000,nypost,US lost 23K jobs in July in disappointing repo...,https://nypost.com/2026/08/07/business/us-lost...
371,41,2026-08-06-14-58-00 +0000,wsj,Democratic candidates on the far left are upen...,https://www.wsj.com/politics/elections/this-de...
330,38,2026-08-06-17-06-16 +0000,nypost,Small SoCal business fumes at ‘power’-hungry l...,https://nypost.com/2026/08/06/us-news/small-so...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)