## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-11-03-02-08 +0000,startribune,Live: Former Gophers running back tormenting M...,https://www.startribune.com/minnesota-purdue-s...
1,2026-10-11-02-56-14 +0000,wapo,DOJ investigating five TV networks over White ...,https://www.washingtonpost.com/business/2026/1...
2,2026-10-11-02-46-00 +0000,wsj,The Sleepy Insurance Product That Came to Powe...,https://www.wsj.com/finance/the-sleepy-insuran...
3,2026-10-11-02-40-52 +0000,nyt,Justice Dept. Is Investigating TV Networks Ove...,https://www.nytimes.com/2026/10/10/business/me...
4,2026-10-11-02-33-35 +0000,nyt,A Senator Facing Re-Election Settles a Bakery ...,https://www.nytimes.com/2026/10/10/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
26     trump     30
106      new     13
141   killed     12
161       he     11
105  ukraine     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
111,2026-10-10-17-35-33 +0000,chitri,Pres. Donald Trump says Ukraine should get a n...,https://www.chicagotribune.com/2026/10/10/trum...,93
76,2026-10-10-20-22-36 +0000,wapo,Trump says Ukraine should ‘get a new president...,https://www.washingtonpost.com/politics/2026/1...,83
12,2026-10-11-01-41-29 +0000,bbc,"'Time for Ukraine to get new president,' says ...",https://www.bbc.co.uk/news/articles/cqe8r5l7n9...,83
143,2026-10-10-12-56-05 +0000,cbc,"Trump says Ukraine should get a new president,...",https://www.cbc.ca/news/world/russia-strikes-u...,80
85,2026-10-10-19-28-55 +0000,nyt,"Rebuking Ukraine Over Oil Strikes, Trump Says ...",https://www.nytimes.com/2026/10/10/world/europ...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
111,93,2026-10-10-17-35-33 +0000,chitri,Pres. Donald Trump says Ukraine should get a n...,https://www.chicagotribune.com/2026/10/10/trum...
16,53,2026-10-11-01-08-07 +0000,wapo,"12 killed, hundreds injured in Saudi Arabia ai...",https://www.washingtonpost.com/world/2026/10/1...
102,50,2026-10-10-18-08-00 +0000,wsj,"Kimberly Guilfoyle, as America’s newly minted ...",https://www.wsj.com/politics/policy/at-davos-k...
20,44,2026-10-11-00-52-59 +0000,nypost,‘Tiger King’ star Carole Baskin tells Post tha...,https://nypost.com/2026/10/10/world-news/carol...
108,38,2026-10-10-17-44-26 +0000,bbc,US murderer Christa Pike discharged from hospi...,https://www.bbc.co.uk/news/articles/cmlyle97pq...
62,37,2026-10-10-21-15-00 +0000,wsj,California Gov. Gavin Newsom has long opposed ...,https://www.wsj.com/politics/newsom-backs-meas...
60,33,2026-10-10-21-20-01 +0000,bbc,Two children and pregnant woman among 8 shot d...,https://www.bbc.co.uk/news/articles/cmed3njg5d...
127,29,2026-10-10-15-00-00 +0000,wsj,While pushback against data centers is well-kn...,https://www.wsj.com/politics/elections/will-vo...
90,28,2026-10-10-18-59-47 +0000,latimes,Tropical Storm Rachel's surf drives out Long B...,https://www.latimes.com/california/story/2026-...
11,26,2026-10-11-01-48-31 +0000,nypost,Bodycam footage reveals police welfare check i...,https://nypost.com/2026/10/10/us-news/bodycam-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)