## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-16-05-44-00 +0000,wsj,"U.S. Treasury Yields Rise, Middle East Conflic...",https://www.wsj.com/finance/investing/jgbs-mix...
1,2026-07-16-05-39-00 +0000,wsj,"Publicis Raises Guidance, Citing New Business ...",https://www.wsj.com/business/earnings/publicis...
2,2026-07-16-05-35-30 +0000,missionlocal,"Not so quietly, Kiah Stokes leads defense for ...",https://missionlocal.org/2026/07/not-so-quietl...
3,2026-07-16-05-34-27 +0000,wapo,Europe’s cocaine highway leads to military-sty...,https://www.washingtonpost.com/world/2026/07/1...
4,2026-07-16-05-25-29 +0000,nyt,The Race for A.I. Data Centers Arrives in India,https://www.nytimes.com/video/world/1000000110...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
108  trump     44
84    iran     34
12     new     19
85     war     17
398  world     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
102,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...,149
21,2026-07-16-04-01-08 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...,124
173,2026-07-15-20-26-19 +0000,nypost,"Trump doesn’t rule out decimating IRGC, warns ...",https://nypost.com/2026/07/15/us-news/trump-do...,122
350,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...,120
228,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
102,149,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...
143,80,2026-07-15-21-27-00 +0000,wsj,The Air Force for the first time successfully ...,https://www.wsj.com/politics/national-security...
228,75,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...
293,61,2026-07-15-14-08-00 +0000,wsj,The economy has added jobs for four straight m...,https://www.wsj.com/economy/jobs/unemployment-...
105,55,2026-07-15-22-50-00 +0000,wsj,Homeland Security Secretary Markwayne Mullin a...,https://www.wsj.com/politics/policy/trump-was-...
155,51,2026-07-15-21-08-26 +0000,cbc,Argentina makes late comeback to secure World ...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
122,49,2026-07-15-22-03-47 +0000,bbc,Bangkok's bar fire is the city's latest deadly...,https://www.bbc.co.uk/news/articles/cd6e68n3jz...
75,42,2026-07-16-00-32-44 +0000,nypost,Mother of 16 ‘almost feral’ kids rescued from ...,https://nypost.com/2026/07/15/us-news/ohio-mot...
350,42,2026-07-15-10-53-04 +0000,nypost,US launches new round of strikes against Iran ...,https://nypost.com/2026/07/15/world-news/us-sa...
256,40,2026-07-15-16-11-00 +0000,wsj,The U.S. Mint is set to begin striking a dolla...,https://www.wsj.com/politics/policy/trump-doll...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)