## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-02-44-00 +0000,wsj,Singapore Dollar Weakens After U.S.-Iran Peace...,https://www.wsj.com/finance/investing/asian-cu...
1,2026-04-13-02-35-49 +0000,bbc,Congressman Eric Swalwell quits California gov...,https://www.bbc.com/news/articles/c74vwdpj7kdo...
2,2026-04-13-02-35-00 +0000,wsj,President Trump and his advisers have been con...,https://www.wsj.com/politics/policy/white-hous...
3,2026-04-13-02-35-00 +0000,wsj,White House Fields Warnings About Iran War’s E...,https://www.wsj.com/politics/policy/white-hous...
4,2026-04-13-02-32-57 +0000,48hills,Record Store Day 2026 brings a ‘1983’ treat,https://48hills.org/2026/04/record-store-day-2...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
3       iran     43
5      talks     26
19     trump     24
9   swalwell     19
8       eric     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
147,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...,160
177,2026-04-12-13-19-52 +0000,cbc,U.S. says Strait of Hormuz blockade will start...,https://www.cbc.ca/news/world/trump-strait-of-...,139
8,2026-04-13-02-12-00 +0000,wsj,"Oil Climbs as U.S.-Iran Peace Talks Fail, U.S....",https://www.wsj.com/finance/commodities-future...,138
9,2026-04-13-02-09-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,128
64,2026-04-12-22-38-11 +0000,wapo,Trump announces naval blockade of Iran after I...,https://www.washingtonpost.com/world/2026/04/1...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
147,160,2026-04-12-16-17-31 +0000,nyt,The Strait of Hormuz and Iran’s Uranium Stockp...,https://www.nytimes.com/2026/04/11/world/middl...
21,103,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
9,82,2026-04-13-02-09-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
105,50,2026-04-12-19-50-52 +0000,nypost,Hungary’s Viktor Orbán concedes defeat after ‘...,https://nypost.com/2026/04/12/world-news/hunga...
134,36,2026-04-12-17-47-00 +0000,wsj,Neither Iran nor China possess anything like A...,https://www.wsj.com/economy/global/kryptonite-...
67,33,2026-04-12-22-27-30 +0000,nyt,Oil Prices Surge Above $100 After Peace Talks ...,https://www.nytimes.com/2026/04/12/business/oi...
59,29,2026-04-12-23-04-10 +0000,nypost,NYC’s first city-owned grocery store under lef...,https://nypost.com/2026/04/12/us-news/nycs-fir...
109,28,2026-04-12-19-23-59 +0000,cbc,Irish PM announces fuel tax cuts amid days of ...,https://www.cbc.ca/news/world/ireland-gas-fuel...
222,27,2026-04-12-04-01-32 +0000,nyt,Many Polls Say Orban Will Lose. But He Has an ...,https://www.nytimes.com/2026/04/12/world/europ...
208,27,2026-04-12-09-00-00 +0000,wsj,Jeanine Pirro’s ability to manage a mercurial ...,https://www.wsj.com/politics/policy/judge-jean...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)