## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-22-18-54-36 +0000,chitri,Solar project at Trinity High School ties into...,https://www.chicagotribune.com/2026/10/22/sola...
1,2026-10-22-18-54-03 +0000,nypost,Steven Matz let faith guide him through the pe...,https://nypost.com/2026/10/22/sports/steven-ma...
2,2026-10-22-18-51-58 +0000,nyt,Employers Shift Rising Health Care Costs Onto ...,https://www.nytimes.com/2026/10/22/business/he...
3,2026-10-22-18-49-51 +0000,nyt,Hakeem Jeffries Launches Final Midterm Sprint ...,https://www.nytimes.com/2026/10/22/us/politics...
4,2026-10-22-18-48-40 +0000,nyt,"In the Wake of Riots, the French Authorities B...",https://www.nytimes.com/2026/10/22/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2353/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
174         new     26
110       trump     25
63   california     22
79           ai     18
176      senate     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
303,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...,105
200,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...,94
189,2026-10-22-11-53-48 +0000,chitri,Deportations climb under President Donald Trum...,https://www.chicagotribune.com/2026/10/22/depo...,94
324,2026-10-21-23-59-30 +0000,nypost,Mike Rogers says Abdul El-Sayed is a national ...,https://nypost.com/2026/10/21/us-news/rogers-a...,93
196,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
303,105,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...
200,94,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...
396,82,2026-10-21-20-41-37 +0000,nypost,Tesla surprises Wall Street with lower-than-ex...,https://nypost.com/2026/10/21/business/elon-mu...
210,69,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...
196,66,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...
53,63,2026-10-22-17-22-25 +0000,nypost,Doctor feared she was being drugged before est...,https://nypost.com/2026/10/22/us-news/doctor-f...
18,52,2026-10-22-18-26-56 +0000,bbc,Zuckerberg wins Meta deal to help him foot bil...,https://www.bbc.co.uk/news/articles/cky83vwnyg...
13,51,2026-10-22-18-34-00 +0000,wsj,Silver Futures Fall to Lowest This Year as Oil...,https://www.wsj.com/finance/commodities-future...
99,45,2026-10-22-16-08-52 +0000,cbc,Top court will hear appeal on ruling that foun...,https://www.cbc.ca/news/politics/supreme-court...
408,44,2026-10-21-19-58-06 +0000,bbc,Rosenberg: Russia agrees to Ukraine talks but ...,https://www.bbc.co.uk/news/articles/cm98zn5j89...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)