## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-00-11-31 +0000,bbc,Two boys pulled from Venezuela earthquake rubb...,https://www.bbc.co.uk/news/articles/cr47dvywvy...
1,2026-06-29-00-04-51 +0000,nyt,Pro-Transgender Candidate Is Chased From a Tra...,https://www.nytimes.com/2026/06/27/us/scott-wi...
2,2026-06-28-23-56-00 +0000,wsj,Oil Rises Amid Renewed Supply-Disruption Concerns,https://www.wsj.com/finance/commodities-future...
3,2026-06-28-23-52-30 +0000,nypost,Newborn found dead in porta-potty at Electric ...,https://nypost.com/2026/06/28/us-news/newborn-...
4,2026-06-28-23-46-00 +0000,wsj,"BIS Sees Peril for Economy, Financial System i...",https://www.wsj.com/economy/bis-sees-peril-for...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
109      trump     15
48        iran     13
3    venezuela      9
39          ai      8
162        new      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-06-28-02-37-00 +0000,wsj,Rep. Julia Letlow won a hard-fought GOP Senate...,https://www.wsj.com/politics/elections/louisia...,69
182,2026-06-28-00-53-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...,48
171,2026-06-28-02-14-29 +0000,nypost,Trump-backed Julia Letlow takes victory in Lou...,https://nypost.com/2026/06/27/us-news/louisian...,45
29,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...,44
151,2026-06-28-08-05-07 +0000,wapo,"U.S., Iran launch new strikes, testing fragile...",https://www.washingtonpost.com/world/2026/06/2...,42

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,69,2026-06-28-02-37-00 +0000,wsj,Rep. Julia Letlow won a hard-fought GOP Senate...,https://www.wsj.com/politics/elections/louisia...
29,44,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...
84,33,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...
26,32,2026-06-28-22-08-04 +0000,nypost,NYC faces extreme 100-degree temps this week —...,https://nypost.com/2026/06/28/us-news/nyc-heat...
102,32,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
11,31,2026-06-28-23-10-52 +0000,nyt,Venezuela Live Updates: Rescuers in ‘Critical ...,https://www.nytimes.com/live/2026/06/28/world/...
20,29,2026-06-28-22-39-51 +0000,nypost,Video shows crocodile that killed Puerto Valla...,https://nypost.com/2026/06/28/us-news/video-sh...
133,29,2026-06-28-10-08-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
122,29,2026-06-28-12-10-56 +0000,nypost,At least 2 dead after Ukraine drone assault se...,https://nypost.com/2026/06/28/world-news/at-le...
185,24,2026-06-28-00-32-07 +0000,bbc,Sort Your Life Out: The four most common clutt...,https://www.bbc.co.uk/news/articles/cvgd54yvjz...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)