## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-11-54-16 +0000,bbc,Voters in Brazil head to polls as Lula goes up...,https://www.bbc.co.uk/news/articles/cxp8g21j46...
1,2026-10-25-11-49-43 +0000,nyt,Introducing a New Way to Understand the Electi...,https://www.nytimes.com/2026/10/25/upshot/elec...
2,2026-10-25-11-49-08 +0000,bbc,Burnham open to 'honest discussion' on EU free...,https://www.bbc.co.uk/news/articles/c8e36kyk1q...
3,2026-10-25-11-38-09 +0000,nypost,Orthodox Jews flee NY for Florida amid rising ...,https://nypost.com/2026/10/25/us-news/orthodox...
4,2026-10-25-11-30-13 +0000,nypost,Protestors waving Palestinian flags storm Roma...,https://nypost.com/2026/10/25/world-news/prote...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2358/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
167     trump     21
14   election     16
11        new     13
252   ukraine     10
1      brazil      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
95,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,65
101,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...,63
128,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,63
105,2026-10-25-00-33-41 +0000,nypost,Obama rips Trump for tariffs and White House r...,https://nypost.com/2026/10/24/us-news/obama-ri...,59
85,2026-10-25-02-27-15 +0000,bbc,Obama attacks Trump as he campaigns for Democr...,https://www.bbc.co.uk/news/articles/cmj6jwe1j1...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
95,65,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...
114,56,2026-10-24-23-35-22 +0000,chitri,"Brazil’s Lula, Bolsonaro close arguments to vo...",https://www.chicagotribune.com/2026/10/24/braz...
162,50,2026-10-24-17-33-41 +0000,nypost,"Ukraine’s Starlink, Starshield back at full po...",https://nypost.com/2026/10/24/world-news/ukrai...
101,44,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
61,41,2026-10-25-06-43-22 +0000,nypost,Arson suspect arrested after fire engulfs Hitl...,https://nypost.com/2026/10/25/world-news/germa...
150,30,2026-10-24-19-37-35 +0000,bbc,Watch: BBC in Paris as police charge protester...,https://www.bbc.co.uk/news/videos/cm89zqw9lx1d...
53,27,2026-10-25-08-00-00 +0000,cbc,A ‘reset’ or ‘one and done’? First Nations and...,https://www.cbc.ca/news/politics/first-nations...
161,27,2026-10-24-17-45-17 +0000,nyt,Netanyahu Is Up for Re-election After Years of...,https://www.nytimes.com/2026/10/24/world/middl...
199,26,2026-10-24-12-41-36 +0000,nypost,Hero mom who died trying to save kids in Baham...,https://nypost.com/2026/10/24/world-news/mom-w...
187,25,2026-10-24-14-03-10 +0000,chitri,Halloween candy sales are off to a slow start ...,https://www.chicagotribune.com/2026/10/24/hall...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)