## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-11-14-43 +0000,bbc,From friendship bracelets to wedding rings: A ...,https://www.bbc.co.uk/news/articles/cqj19p112q...
1,2026-07-04-11-00-00 +0000,missionlocal,"The last days of Puddle Jumpers, one of the Mi...",https://missionlocal.org/2026/07/the-last-days...
2,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
3,2026-07-04-11-00-00 +0000,nypost,"A place of living history, the White House has...",https://nypost.com/2026/07/04/us-news/the-whit...
4,2026-07-04-11-00-00 +0000,nypost,A happy 250th birthday letter to America from ...,https://nypost.com/2026/07/04/us-news/a-happy-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
42    trump     26
39  america     13
59    world     13
36       th     13
70     iran     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
58,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...,78
216,2026-07-03-11-55-27 +0000,nypost,What to expect at Trump’s epic 4th of July ‘Sa...,https://nypost.com/2026/07/03/us-news/what-to-...,76
74,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,74
4,2026-07-04-11-00-00 +0000,nypost,A happy 250th birthday letter to America from ...,https://nypost.com/2026/07/04/us-news/a-happy-...,66
211,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
58,78,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
211,63,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
99,50,2026-07-04-00-00-00 +0000,wsj,Capital Account: The 250th anniversary of the ...,https://www.wsj.com/economy/american-instituti...
81,45,2026-07-04-01-55-12 +0000,nypost,"Tourists stumble upon Taylor Swift, Travis Kel...",https://nypost.com/2026/07/03/us-news/tourists...
39,44,2026-07-04-09-00-58 +0000,nyt,How Do You Celebrate America’s 250-Year Experi...,https://www.nytimes.com/2026/07/04/us/america-...
2,33,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
70,29,2026-07-04-03-09-37 +0000,bbc,Farewell Cape Verde - the underdogs the World ...,https://www.bbc.co.uk/sport/football/articles/...
125,29,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
26,28,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...
57,28,2026-07-04-05-25-47 +0000,nypost,Iranians call for revenge as crowd mourns late...,https://nypost.com/2026/07/04/us-news/iranians...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)