## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-23-51-00 +0000,wsj,U.S. Strikes Iranian Oil Tankers in Response t...,https://www.wsj.com/world/middle-east/iran-lau...
1,2026-09-08-23-46-59 +0000,nyt,"U.S. Hits 5 Iranian Oil Tankers, Citing Attemp...",https://www.nytimes.com/2026/09/08/world/middl...
2,2026-09-08-23-45-45 +0000,nyt,Dueling Court Rulings Leave Missouri’s Congres...,https://www.nytimes.com/2026/09/08/us/politics...
3,2026-09-08-23-42-35 +0000,bbc,US slaps import ban on Canadian alcohol and ot...,https://www.bbc.co.uk/news/articles/c99dm1000p...
4,2026-09-08-23-42-00 +0000,wsj,Supreme Court Denies Missouri Bid to Use Votin...,https://www.wsj.com/politics/policy/supreme-co...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2464/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     45
98     new     24
2      oil     21
72  canada     19
66   trade     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
59,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...,122
37,2026-09-08-22-37-33 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,119
395,2026-09-08-05-01-12 +0000,nypost,Canada slaps tit-for-tat tariffs on over $20B ...,https://nypost.com/2026/09/08/business/canadas...,112
62,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...,104
9,2026-09-08-23-27-11 +0000,nypost,"Trump bans import of Canadian alcohol, dairy a...",https://nypost.com/2026/09/08/us-news/trump-ba...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
59,122,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...
62,104,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
236,69,2026-09-08-15-25-05 +0000,nypost,Benjamin Netanyahu furiously disputes bombshel...,https://nypost.com/2026/09/08/world-news/benja...
137,61,2026-09-08-19-11-39 +0000,bbc,UK announces sanctions on West Bank settlement...,https://www.bbc.co.uk/news/articles/c4g7zen0vv...
227,55,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...
418,52,2026-09-08-00-26-55 +0000,nypost,House lawmaker sues to reverse Missouri Suprem...,https://nypost.com/2026/09/07/us-news/house-la...
150,45,2026-09-08-18-37-05 +0000,nypost,Bombardier stock sinks after Trump threatens t...,https://nypost.com/2026/09/08/business/bombard...
21,40,2026-09-08-23-10-00 +0000,nypost,At least 4 shot across NYC – including man kil...,https://nypost.com/2026/09/08/us-news/at-least...
31,39,2026-09-08-22-57-40 +0000,nypost,Radical California professors urge students to...,https://nypost.com/2026/09/08/us-news/californ...
148,36,2026-09-08-18-39-27 +0000,48hills,Fall Arts Preview: Grab a seat (or run for you...,https://48hills.org/2026/09/fall-arts-preview-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)