## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-19-13-57 +0000,nypost,Ex-NYC DOB supervisor took $75K in bribes to f...,https://nypost.com/2026/03/31/us-news/ex-nyc-d...
1,2026-03-31-19-09-10 +0000,nypost,Slain NYPD hero Jonathan Diller’s widow covers...,https://nypost.com/2026/03/31/us-news/nypd-her...
2,2026-03-31-19-08-46 +0000,nypost,ICE arrests ‘flamethrower’ illegal tackled an...,https://nypost.com/2026/03/31/us-news/ice-arre...
3,2026-03-31-19-07-20 +0000,nyt,Iran War Live Updates: B-52s Start Flying Miss...,https://www.nytimes.com/live/2026/03/31/world/...
4,2026-03-31-19-02-47 +0000,wapo,Gas hits $4 a gallon for first time since 2022...,https://www.washingtonpost.com/business/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
34     iran     54
95    trump     50
35      war     38
107     oil     18
225  prices     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
127,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...,191
43,2026-03-31-18-05-01 +0000,startribune,Trump lashes out at allies as Iran war and str...,https://www.startribune.com/us-attacks-iranian...,188
167,2026-03-31-13-02-00 +0000,nyt,Trump Faces a Decision on Whether to Start a G...,https://www.nytimes.com/2026/03/31/us/politics...,157
3,2026-03-31-19-07-20 +0000,nyt,Iran War Live Updates: B-52s Start Flying Miss...,https://www.nytimes.com/live/2026/03/31/world/...,157
102,2026-03-31-16-05-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,155

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
127,191,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...
141,71,2026-03-31-14-14-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
138,53,2026-03-31-14-26-52 +0000,nypost,"Supreme Court sides with Christian counselor, ...",https://nypost.com/2026/03/31/us-news/supreme-...
345,49,2026-03-30-20-46-00 +0000,wsj,"Trump warns of hitting Iran’s energy sites, ad...",https://www.wsj.com/economy/central-banking/tr...
221,46,2026-03-31-09-39-27 +0000,nypost,Gas prices rise above $4 a gallon for first ti...,https://nypost.com/2026/03/31/business/gas-pri...
191,44,2026-03-31-11-26-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
64,43,2026-03-31-17-30-05 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
243,39,2026-03-31-08-02-03 +0000,nypost,Iran strikes Kuwaiti oil tanker in drone attac...,https://nypost.com/2026/03/31/world-news/iran-...
248,36,2026-03-31-07-40-08 +0000,wsj,Stock Market Today: Nasdaq Leads Rally Built o...,https://www.wsj.com/livecoverage/stock-market-...
77,33,2026-03-31-16-54-54 +0000,latimes,Video shows man enter police vehicle before be...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)