## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-08-14-14-11 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
1,2026-06-08-14-14-00 +0000,wsj,Oil Trims Gains After Iran Says It Ended Attac...,https://www.wsj.com/world/middle-east/oil-clim...
2,2026-06-08-14-13-49 +0000,nypost,First-ever bear sighting in Japanese city trig...,https://nypost.com/2026/06/08/world-news/first...
3,2026-06-08-14-13-01 +0000,nypost,Gen Zer quits Goldman Sachs after clash over ‘...,https://nypost.com/2026/06/08/business/gen-zer...
4,2026-06-08-14-11-00 +0000,wsj,Opinion | Remember What They Did to Dean Phill...,https://www.wsj.com/opinion/remember-what-they...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2662/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
14     iran     24
16   israel     22
86    trump     21
261     new     14
94      war     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...,95
89,2026-06-08-10-04-21 +0000,nypost,Iran says it’s halting Israel attacks after Tr...,https://nypost.com/2026/06/08/us-news/trump-sa...,81
13,2026-06-08-14-00-03 +0000,startribune,"Israel and Iran trade strikes, threatening to ...",https://www.startribune.com/israel-says-it-has...,75
207,2026-06-07-20-19-53 +0000,nyt,Trump Defends Compensation Fund and Iran War i...,https://www.nytimes.com/2026/06/07/us/politics...,74
196,2026-06-07-21-10-44 +0000,nyt,Iran Fires Missiles at Israel for First Time S...,https://www.nytimes.com/2026/06/07/world/middl...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,95,2026-06-07-21-02-06 +0000,nypost,Trump insists Israel’s Netanyahu ‘won’t have a...,https://nypost.com/2026/06/07/us-news/trump-te...
138,66,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
190,45,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
169,44,2026-06-08-01-00-00 +0000,wsj,"Most rankings of companies look backward, meas...",https://www.wsj.com/economy/jobs/best-companie...
0,43,2026-06-08-14-14-11 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
245,39,2026-06-07-15-48-19 +0000,nypost,Trump storms off ‘Meet The Press’ interview af...,https://nypost.com/2026/06/07/us-news/trump-st...
250,38,2026-06-07-15-21-34 +0000,nypost,Bombshell LA mayor’s race projection changes e...,https://nypost.com/2026/06/07/us-news/la-mayor...
23,36,2026-06-08-13-47-47 +0000,nyt,Mexico City’s Airport Got a $500 Million Renov...,https://www.nytimes.com/2026/06/07/world/ameri...
139,35,2026-06-08-04-29-34 +0000,nypost,NYPD cop appears to slam Knicks fan’s head int...,https://nypost.com/2026/06/08/us-news/nypd-cop...
48,33,2026-06-08-12-15-14 +0000,nypost,Two dead as private jet crashes in Dominican R...,https://nypost.com/2026/06/08/world-news/priva...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)