## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-09-15-37 +0000,bbc,'We need working-class voices to enrich culture',https://www.bbc.com/news/articles/c80mvl9p40vo...
1,2026-05-17-09-04-10 +0000,nypost,At least 3 people killed in largest Ukrainian ...,https://nypost.com/2026/05/17/world-news/ukrai...
2,2026-05-17-09-02-18 +0000,nyt,"To Critics, Trump Remarks Reveal a Billionaire...",https://www.nytimes.com/2026/05/17/us/politics...
3,2026-05-17-09-02-12 +0000,nyt,"For Trump, Soaring Prices Test Voters’ Finance...",https://www.nytimes.com/2026/05/17/business/fo...
4,2026-05-17-09-02-06 +0000,nyt,"Trump Flexes Hold on G.O.P., Even as It Braces...",https://www.nytimes.com/2026/05/17/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2576/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
15        trump     35
7        killed     11
44        world     10
11       strike      9
424  eurovision      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
36,2026-05-17-04-57-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,95
49,2026-05-17-02-56-27 +0000,nypost,Republican Sen. Bill Cassidy — who voted to co...,https://nypost.com/2026/05/16/us-news/la-repub...,86
41,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...,83
18,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...,82
154,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
36,95,2026-05-17-04-57-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
41,48,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...
168,43,2026-05-16-14-29-20 +0000,nyt,Hamas’s Top Leader in Gaza Is Killed in Israel...,https://www.nytimes.com/2026/05/15/world/middl...
76,31,2026-05-17-00-40-23 +0000,latimes,The world's largest wildlife crossing and five...,https://www.latimes.com/california/story/2026-...
18,30,2026-05-17-09-00-00 +0000,wsj,"Thomas Massie, the seven-term GOP congressman ...",https://www.wsj.com/politics/elections/thomas-...
127,29,2026-05-16-19-52-53 +0000,nypost,Recovery operation for Italian divers killed i...,https://nypost.com/2026/05/16/world-news/recov...
114,29,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...
32,28,2026-05-17-06-48-51 +0000,nypost,Florida house sitter arrested weeks after alle...,https://nypost.com/2026/05/17/us-news/us-airma...
97,28,2026-05-16-23-10-22 +0000,nypost,Hochul pushed LIRR strike to pick up votes on ...,https://nypost.com/2026/05/16/us-news/hochul-p...
179,26,2026-05-16-12-18-02 +0000,cbc,"WHO declares deadly Ebola outbreak in Congo, U...",https://www.cbc.ca/news/world/congo-ebola-outb...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)