## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-16-36-55 +0000,nyt,They Shut the Golden Gate Bridge for 4 Hours. ...,https://www.nytimes.com/2026/06/05/us/gaza-pro...
1,2026-06-05-16-36-00 +0000,wsj,The Metric CFOs Struggle to Track: AI Usage,https://www.wsj.com/cfo-journal/the-metric-cfo...
2,2026-06-05-16-35-09 +0000,nyt,U.S. Job Market Pushes Past Shocks and Strains,https://www.nytimes.com/article/what-to-know-a...
3,2026-06-05-16-34-49 +0000,nyt,‘60 Minutes’ Stars Will Stay Because They Don’...,https://www.nytimes.com/2026/06/05/business/me...
4,2026-06-05-16-33-57 +0000,nypost,Maritime drone being used in Ukraine war explo...,https://nypost.com/2026/06/05/world-news/no-on...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2602/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
60        trump     34
353         new     18
176  california     15
15       market     15
6            up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
18,2026-06-05-16-20-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,94
370,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...,91
223,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...,80
136,2026-06-05-11-23-00 +0000,cbc,Senate passes bill for more ICE funding after ...,https://www.cbc.ca/news/world/us-senate-securi...,78
290,2026-06-04-21-36-37 +0000,latimes,"Chabria: No, Mr. Hilton, our elections are not...",https://www.latimes.com/california/story/2026-...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
18,94,2026-06-05-16-20-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
95,67,2026-06-05-13-47-48 +0000,nypost,"Graham Platner, Susan Collins tied in Maine Se...",https://nypost.com/2026/06/05/us-news/graham-p...
190,53,2026-06-05-08-49-12 +0000,nypost,Zelensky calls for face-to-face negotiations t...,https://nypost.com/2026/06/05/world-news/ukrai...
229,48,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
223,46,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...
122,42,2026-06-05-12-46-00 +0000,bbc,"Is there an AI stock market bubble, and is it ...",https://www.bbc.com/news/videos/c1m2mr7gr27o?a...
59,38,2026-06-05-15-19-52 +0000,nypost,"Iran declares support for Hezbollah, demands I...",https://nypost.com/2026/06/05/world-news/iran-...
187,37,2026-06-05-08-56-17 +0000,cbc,Chinese leader Xi Jinping to visit North Korea...,https://www.cbc.ca/news/world/xi-jinping-north...
366,36,2026-06-04-17-15-13 +0000,nyt,Supreme Court Finds S.E.C. Can Strip Wrongdoer...,https://www.nytimes.com/2026/06/04/us/politics...
321,36,2026-06-04-20-19-21 +0000,cbc,House committee asks U.S. DOJ to examine sexua...,https://www.cbc.ca/news/world/epstein-committe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)