## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-06-11-26-00 +0000,wsj,Kraft Heinz Sales Tick Up as Turnaround Effort...,https://www.wsj.com/business/earnings/kraft-he...
1,2026-05-06-11-25-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
2,2026-05-06-11-23-23 +0000,nypost,Twisted ‘human safari’ hunters competed to kil...,https://nypost.com/2026/05/06/world-news/twist...
3,2026-05-06-11-17-00 +0000,wsj,"Instacart Posts Higher Revenue, Says Customers...",https://www.wsj.com/business/retail/instacart-...
4,2026-05-06-11-16-26 +0000,nyt,"Trump Again Shifts U.S. Focus on Strait, Pausi...",https://www.nytimes.com/live/2026/05/05/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2478/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
36        trump     38
59         iran     27
73          new     22
273  california     16
39       strait     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
198,2026-05-05-22-35-56 +0000,nypost,Trump pauses Project Freedom rescue operation ...,https://nypost.com/2026/05/05/world-news/proje...,138
184,2026-05-05-23-10-33 +0000,nypost,Trump pauses ‘Project Freedom’ initiative in S...,https://nypost.com/2026/05/05/us-news/trump-pa...,121
227,2026-05-05-21-40-07 +0000,cbc,Trump pauses U.S. effort to guide vessels thro...,https://www.cbc.ca/news/world/rubio-hegseth-ir...,118
356,2026-05-05-15-04-00 +0000,wsj,President Trump escalated his public feud with...,https://www.wsj.com/politics/national-security...,113
168,2026-05-06-00-12-00 +0000,wsj,Trump Administration Sues New York Times Over ...,https://www.wsj.com/us-news/law/trump-administ...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
198,138,2026-05-05-22-35-56 +0000,nypost,Trump pauses Project Freedom rescue operation ...,https://nypost.com/2026/05/05/world-news/proje...
273,84,2026-05-05-20-05-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
89,74,2026-05-06-08-23-17 +0000,nypost,Baltimore bakery truck driver believed he was ...,https://nypost.com/2026/05/06/us-news/baltimor...
25,65,2026-05-06-10-43-49 +0000,bbc,Cruise passengers tell of life on board ship s...,https://www.bbc.com/news/articles/clype7ededzo...
6,57,2026-05-06-11-14-45 +0000,bbc,Oil prices drop and stock markets rise after r...,https://www.bbc.com/news/articles/c4g8zejyyr3o...
104,57,2026-05-06-06-46-38 +0000,latimes,"Top takeaways from fiery, at times ugly, Calif...",https://www.latimes.com/california/story/2026-...
230,56,2026-05-05-21-32-17 +0000,cbc,Prosecutors add assault charge to case against...,https://www.cbc.ca/news/world/assault-charge-w...
241,53,2026-05-05-21-13-00 +0000,wsj,"After pressure from Trump, the FDA OKs some fl...",https://www.wsj.com/politics/policy/after-trum...
102,42,2026-05-06-06-50-24 +0000,nypost,Russian attacks kill at least 27 before deadli...,https://nypost.com/2026/05/06/world-news/russi...
131,40,2026-05-06-03-52-55 +0000,nypost,Trump-backed candidates take out GOP incumbent...,https://nypost.com/2026/05/05/us-news/trump-ba...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)