## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-23-16-10-38 +0000,nypost,"Elderly woman, son killed in NYC blaze after n...",https://nypost.com/2026/05/23/us-news/elderly-...
1,2026-05-23-16-09-53 +0000,nypost,Gen Z drivers are car-azy behind the wheel: st...,https://nypost.com/2026/05/23/us-news/gen-z-dr...
2,2026-05-23-16-08-50 +0000,nypost,Bot busters: NYC Council bill would protect Ne...,https://nypost.com/2026/05/23/us-news/nyc-bill...
3,2026-05-23-16-08-11 +0000,startribune,Few Minnesota Dems backing Ken Martin as DNC b...,https://www.startribune.com/few-minnesota-dems...
4,2026-05-23-16-08-11 +0000,nypost,Khat user accuses NYC cops of illegal cavity s...,https://nypost.com/2026/05/23/us-news/khat-use...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2633/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
61      trump     41
25        new     14
435     ebola     13
58         he     12
75   chemical     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
27,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,128
256,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...,125
6,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...,107
220,2026-05-22-20-25-00 +0000,wsj,Tulsi Gabbard resigned as director of national...,https://www.wsj.com/politics/tulsi-gabbard-is-...,101
160,2026-05-22-23-06-58 +0000,nypost,Trump touts GOP backed-tax cuts for New Yorker...,https://nypost.com/2026/05/22/us-news/trump-to...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
27,128,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...
256,68,2026-05-22-18-08-00 +0000,wsj,"President Trump told his new Fed chair, Kevin ...",https://www.wsj.com/economy/central-banking/ke...
220,50,2026-05-22-20-25-00 +0000,wsj,Tulsi Gabbard resigned as director of national...,https://www.wsj.com/politics/tulsi-gabbard-is-...
281,45,2026-05-22-16-30-51 +0000,cbc,No Ebola cases in Canada and no new hantavirus...,https://www.cbc.ca/news/health/livestory/phac-...
37,44,2026-05-23-13-43-24 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
263,41,2026-05-22-17-43-00 +0000,wsj,Most green-card applicants will need to go abr...,https://www.wsj.com/politics/policy/trump-admi...
123,40,2026-05-23-02-37-57 +0000,cbc,"40,000 people under evacuation orders in Calif...",https://www.cbc.ca/news/world/california-chemi...
162,39,2026-05-22-23-04-00 +0000,wsj,Iran Mediators Race for Deal to Head Off Loomi...,https://www.wsj.com/world/middle-east/iran-med...
25,37,2026-05-23-15-00-47 +0000,nypost,Hakeem Jeffries’ re-election bid boosted by ‘s...,https://nypost.com/2026/05/23/us-news/hakeem-j...
247,35,2026-05-22-18-33-08 +0000,nypost,Putin accuses Ukraine of drone attack on stude...,https://nypost.com/2026/05/22/world-news/putin...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)