## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
1,2026-10-23-01-06-38 +0000,startribune,"Live: Wild face Flames, former teammate Jake M...",https://www.startribune.com/minnesota-wild-cal...
2,2026-10-23-01-04-45 +0000,nyt,What to Know About the Investigation Into Ilha...,https://www.nytimes.com/2026/10/22/us/ilhan-om...
3,2026-10-23-01-04-07 +0000,nyt,Pete Ricketts’s Wealth Puts Class at the Cente...,https://www.nytimes.com/2026/10/22/us/politics...
4,2026-10-23-01-00-00 +0000,wsj,I Took America’s Cheapest EV Into the Charging...,https://www.wsj.com/business/autos/chevy-bolt-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2719/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
1         trump     26
485         new     23
131  california     17
207          ai     15
460          up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,96
305,2026-10-22-11-53-48 +0000,chitri,Deportations climb under President Donald Trum...,https://www.chicagotribune.com/2026/10/22/depo...,91
314,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...,87
340,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...,82
321,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,96,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
340,82,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...
311,74,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...
236,71,2026-10-22-15-54-08 +0000,nypost,"Oil soars above $113, Nasdaq plummets in worst...",https://nypost.com/2026/10/22/business/oil-soa...
404,66,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...
65,51,2026-10-22-22-23-00 +0000,wsj,The Justice Department is examining allegation...,https://www.wsj.com/politics/policy/corey-lewa...
321,49,2026-10-22-11-00-00 +0000,wsj,Candidates are slugging it out all over the pl...,https://www.wsj.com/politics/as-vance-piles-on...
170,47,2026-10-22-19-00-13 +0000,nypost,Trump tells Elon Musk to lift any limits on St...,https://nypost.com/2026/10/22/us-news/trump-ca...
270,47,2026-10-22-13-58-13 +0000,nypost,Octogenarian Virginia Dem accused of running i...,https://nypost.com/2026/10/22/us-news/feds-ind...
9,44,2026-10-23-00-51-42 +0000,nypost,Meghan Markle’s estranged dad wanted ‘fresh st...,https://nypost.com/2026/10/22/us-news/meghan-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)