## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-13-45-55 +0000,nyt,Guyana Ferry Tragedy Exposes Political Rifts i...,https://www.nytimes.com/2026/07/27/world/ameri...
1,2026-07-27-13-45-03 +0000,startribune,Mediators see progress in efforts to halt Iran...,https://www.startribune.com/mediators-see-prog...
2,2026-07-27-13-37-00 +0000,wsj,Philip Morris Opens $1.2 Billion Manufacturing...,https://www.wsj.com/business/philip-morris-ope...
3,2026-07-27-13-33-20 +0000,nyt,Merz Criticizes Terrorism Laws After Deadly Be...,https://www.nytimes.com/2026/07/27/world/europ...
4,2026-07-27-13-32-18 +0000,nyt,Seattle Food Festival Shooting: What to Know,https://www.nytimes.com/2026/07/27/us/seattle-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2691/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14    iran     22
59   trump     21
34  berlin     12
36  attack     12
35   pride     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
236,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,75
254,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,70
127,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Oil Tumbles, Stocks Jump A...",https://www.wsj.com/livecoverage/stock-market-...,68
242,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...,66
207,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
236,75,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
242,66,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...
102,60,2026-07-27-09-20-57 +0000,nypost,TikTokker voiced concerns about Seattle Center...,https://nypost.com/2026/07/27/us-news/tiktokke...
127,47,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Oil Tumbles, Stocks Jump A...",https://www.wsj.com/livecoverage/stock-market-...
115,40,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
11,36,2026-07-27-13-22-41 +0000,nyt,New Heat Wave Could Intensify Wildfires in Fra...,https://www.nytimes.com/2026/07/27/world/europ...
36,31,2026-07-27-12-24-59 +0000,nypost,Dozens of Democrat-led states still taxing tip...,https://nypost.com/2026/07/27/us-news/dozens-o...
216,31,2026-07-26-18-22-19 +0000,nypost,Jeffries won’t rule out vote to abolish ICE if...,https://nypost.com/2026/07/26/us-news/jeffries...
186,28,2026-07-26-21-23-53 +0000,bbc,"Israeli settlers set fire to mosques, cars and...",https://www.bbc.co.uk/news/articles/cjrv77gl4d...
208,28,2026-07-26-19-07-31 +0000,nypost,Raging DNC boss Ken Martin threw phone at aide...,https://nypost.com/2026/07/26/us-news/raging-d...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)