## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-20-16-16-33 +0000,nypost,$166 billion in tariff refunds at stake in new...,https://nypost.com/2026/04/20/business/166-bil...
1,2026-04-20-16-13-59 +0000,wapo,Louisiana gunman had sought mental health trea...,https://www.washingtonpost.com/nation/2026/04/...
2,2026-04-20-16-12-09 +0000,nyt,Iran War Live Updates: Tehran and Washington P...,https://www.nytimes.com/live/2026/04/20/world/...
3,2026-04-20-16-11-18 +0000,nyt,California Woman Is Arrested at LAX and Accuse...,https://www.nytimes.com/2026/04/20/us/la-iran-...
4,2026-04-20-16-09-43 +0000,startribune,Friday’s storm scorecard: 10 confirmed tornado...,https://www.startribune.com/minnesotans-band-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2479/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18      iran     24
186    trump     20
4        new     13
409  iranian     12
25     talks     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
31,2026-04-20-15-23-45 +0000,nypost,Trump tells The Post he ‘won’t be rushed’ to e...,https://nypost.com/2026/04/20/us-news/trump-te...,95
87,2026-04-20-13-22-31 +0000,nypost,Trump tells The Post he’s willing to meet with...,https://nypost.com/2026/04/20/us-news/jd-vance...,93
232,2026-04-19-19-06-10 +0000,nypost,Iran refuses to join latest round of peace tal...,https://nypost.com/2026/04/19/world-news/iran-...,81
24,2026-04-20-15-37-29 +0000,nyt,Trump says he might go to Pakistan if an Iran ...,https://www.nytimes.com/live/2026/04/17/world/...,71
2,2026-04-20-16-12-09 +0000,nyt,Iran War Live Updates: Tehran and Washington P...,https://www.nytimes.com/live/2026/04/20/world/...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
31,95,2026-04-20-15-23-45 +0000,nypost,Trump tells The Post he ‘won’t be rushed’ to e...,https://nypost.com/2026/04/20/us-news/trump-te...
63,45,2026-04-20-14-16-52 +0000,nypost,"Stocks fall, oil surges after US seizes cargo ...",https://nypost.com/2026/04/20/business/stocks-...
225,39,2026-04-19-19-46-22 +0000,nypost,US Navy destroyer ‘blows a hole’ through Irani...,https://nypost.com/2026/04/19/world-news/us-na...
155,38,2026-04-20-09-00-07 +0000,wapo,Gas prices threaten GOP in race that could hel...,https://www.washingtonpost.com/business/2026/0...
198,37,2026-04-19-23-07-52 +0000,bbc,'They told me he was dead': Children born near...,https://www.bbc.com/news/articles/c895k3537kgo...
0,35,2026-04-20-16-16-33 +0000,nypost,$166 billion in tariff refunds at stake in new...,https://nypost.com/2026/04/20/business/166-bil...
119,34,2026-04-20-10-58-00 +0000,wsj,There will be a lot of noise in the next few d...,https://www.wsj.com/politics/heres-what-to-kno...
165,27,2026-04-20-07-15-48 +0000,nypost,Two US Embassy officials among four killed in ...,https://nypost.com/2026/04/20/world-news/two-u...
125,27,2026-04-20-10-30-00 +0000,nypost,One of last people to see Brian Hooker before ...,https://nypost.com/2026/04/20/world-news/last-...
224,27,2026-04-19-19-49-34 +0000,nypost,Chinese robot smashes human world record in ha...,https://nypost.com/2026/04/19/world-news/chine...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)