## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-05-46-09 +0000,bbc,"Blocked by censors, China's animal lovers take...",https://www.bbc.co.uk/news/articles/cqx7wd3x42...
1,2026-07-23-05-44-00 +0000,wsj,SpaceX Supplier STMicroelectronics Hikes AI Da...,https://www.wsj.com/business/earnings/spacex-s...
2,2026-07-23-05-44-00 +0000,wsj,Kuehne + Nagel Lifts Earnings Guidance Again o...,https://www.wsj.com/business/earnings/kuehne-n...
3,2026-07-23-05-40-00 +0000,wsj,Roche Backs Full-Year View as First-Half Sales...,https://www.wsj.com/health/pharma/roche-backs-...
4,2026-07-23-05-34-00 +0000,wsj,Nestle to Offload Half of Waters Business in J...,https://www.wsj.com/business/deals/nestle-to-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2360/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
98   trump     41
300    new     31
313   deal     26
91    iran     23
173  house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
393,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,133
310,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,128
12,2026-07-23-05-16-00 +0000,nyt,Iran War Live Updates: Iran Digs In After Late...,https://www.nytimes.com/live/2026/07/22/world/...,117
136,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,117
171,2026-07-22-20-43-49 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
393,133,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...
287,102,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
320,64,2026-07-22-14-14-00 +0000,wsj,"R. James Woolsey, CIA director in Clinton admi...",https://www.wsj.com/politics/national-security...
47,61,2026-07-23-02-00-00 +0000,wsj,Canada’s Mark Carney has tried the carrot and ...,https://www.wsj.com/world/americas/carney-has-...
334,55,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
35,49,2026-07-23-03-03-54 +0000,nypost,Twisted four-word message accused teen killer ...,https://nypost.com/2026/07/22/us-news/californ...
224,47,2026-07-22-18-26-49 +0000,nyt,"Daniel Siad, Model Scout Who Connected Women t...",https://www.nytimes.com/2026/07/22/world/europ...
128,46,2026-07-22-21-50-39 +0000,nyt,House Republicans Pass Stock Trading Bill Tied...,https://www.nytimes.com/2026/07/22/us/politics...
327,44,2026-07-22-13-36-11 +0000,nypost,OpenAI agent goes rogue in ‘unprecedented cybe...,https://nypost.com/2026/07/22/business/openai-...
347,44,2026-07-22-12-44-44 +0000,cbc,Austria turns Hitler's first home into police ...,https://www.cbc.ca/news/world/austria-hitler-h...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)