## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-15-08-51-39 +0000,bbc,State pension likely to rise by £488 a year in...,https://www.bbc.co.uk/news/articles/c2l8v7l0dj...
1,2026-09-15-08-50-32 +0000,nypost,Russian frigate fires flares towards Danish mi...,https://nypost.com/2026/09/15/world-news/russi...
2,2026-09-15-08-49-31 +0000,bbc,Trump says AI safety fears a 'hoax' as he reje...,https://www.bbc.co.uk/news/articles/cw980n0nd0...
3,2026-09-15-08-48-28 +0000,bbc,US confirms for first time it has deployed spa...,https://www.bbc.co.uk/news/articles/ck790xg41y...
4,2026-09-15-08-39-51 +0000,wsj,Stock Market Today: 10-Year Yield Forges Above 5%,https://www.wsj.com/livecoverage/stock-market-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2504/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14   trump     52
15      ai     33
46   court     17
212    new     17
3     year     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
319,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...,153
75,2026-09-15-01-04-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,151
74,2026-09-15-01-04-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,141
112,2026-09-14-22-56-44 +0000,bbc,Donald Trump Jr and Bettina Trump say Putin al...,https://www.bbc.co.uk/news/articles/cmqjkg121k...,141
79,2026-09-15-01-00-00 +0000,wsj,Fed leader Kevin Warsh is facing the fight Pre...,https://www.wsj.com/economy/central-banking/wa...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
319,153,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...
75,99,2026-09-15-01-04-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
198,65,2026-09-14-19-45-00 +0000,wsj,"U.S. 10-Year Yield Cools After Topping 5%, Ger...",https://www.wsj.com/economy/central-banking/u-...
200,58,2026-09-14-19-39-00 +0000,wsj,Oil Prices Rise as Saudi East-West Pipeline At...,https://www.wsj.com/business/energy-oil/oil-pr...
79,56,2026-09-15-01-00-00 +0000,wsj,Fed leader Kevin Warsh is facing the fight Pre...,https://www.wsj.com/economy/central-banking/wa...
377,53,2026-09-14-10-14-31 +0000,nypost,Russian drone hits train near Ukraine-Poland b...,https://nypost.com/2026/09/14/world-news/russi...
369,49,2026-09-14-11-04-00 +0000,wsj,"The price of gasoline—and, by proxy, the Iran ...",https://www.wsj.com/politics/policy/with-50-da...
125,49,2026-09-14-22-28-27 +0000,chitri,GOP Sen. Mitch McConnell returns to Senate for...,https://www.chicagotribune.com/2026/09/14/mitc...
192,47,2026-09-14-19-59-47 +0000,cbc,'Cool to be Canadian': Leaders optimistic thei...,https://www.cbc.ca/news/business/canada-invest...
41,47,2026-09-15-04-31-47 +0000,nypost,Ex-Dem insider exposes what Harris told top do...,https://nypost.com/2026/09/15/us-news/ex-dem-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)