## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-13-16-00 +0000,wsj,NATO’s Top Commander Lays Out Plan to Thwart a...,https://www.wsj.com/world/europe/natos-top-com...
1,2026-10-12-13-15-38 +0000,nyt,World’s Energy Order Tested Again as Iran War’...,https://www.nytimes.com/2026/10/12/business/mi...
2,2026-10-12-13-14-33 +0000,nypost,Applied Materials unveils $5B research facilit...,https://nypost.com/2026/10/12/business/applied...
3,2026-10-12-13-11-36 +0000,startribune,Rep. Ilhan Omar’s home searched by federal age...,https://www.startribune.com/rep-ilhan-omars-ho...
4,2026-10-12-13-11-00 +0000,wsj,Steris to Acquire Xodus Medical for $2.1 Billion,https://www.wsj.com/business/deals/steris-to-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
50     trump     37
47    russia     16
11    energy     15
85   ukraine     11
228      new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...,119
217,2026-10-11-18-10-58 +0000,chitri,Pres. Donald Trump says Russia and Ukraine rea...,https://www.chicagotribune.com/2026/10/11/trum...,102
247,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,101
184,2026-10-11-21-22-00 +0000,wsj,Trump Pushes Russia-Ukraine Energy Ceasefire a...,https://www.wsj.com/world/trump-declares-a-rus...,100
26,2026-10-12-11-47-59 +0000,nypost,Zelensky says Russia still striking energy fac...,https://nypost.com/2026/10/12/world-news/zelen...,99

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,119,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...
224,60,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
36,48,2026-10-12-11-14-24 +0000,nypost,Disturbing video shows moment Houthi terrorist...,https://nypost.com/2026/10/12/world-news/distu...
72,46,2026-10-12-10-00-00 +0000,nypost,AI safety ‘doomers’ pouring cash into Minnesot...,https://nypost.com/2026/10/12/business/ai-safe...
134,38,2026-10-12-05-13-45 +0000,nypost,2 victims of Pa. grandpa’s murder-suicide that...,https://nypost.com/2026/10/12/us-news/2-victim...
113,35,2026-10-12-07-58-00 +0000,wsj,Oil Prices Fall as Traders Weigh Russian Diese...,https://www.wsj.com/business/energy-oil/oil-pr...
165,33,2026-10-11-23-39-12 +0000,bbc,Robert Pattinson on new film Primetime and how...,https://www.bbc.co.uk/news/articles/cmn5d92423...
221,30,2026-10-11-17-47-18 +0000,cbc,Children among at least 139 dead after migrant...,https://www.cbc.ca/news/world/migrant-boat-cap...
73,29,2026-10-12-10-00-00 +0000,latimes,"Republican Steve Hilton leans on cheeky ads, v...",https://www.latimes.com/california/story/2026-...
123,27,2026-10-12-06-50-13 +0000,nypost,Minnesota homecoming shooting suspect walks fr...,https://nypost.com/2026/10/12/us-news/minnesot...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)