## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-04-06-08-52 +0000,nypost,‘Depraved’ illegal immigrant accused of murder...,https://nypost.com/2026/04/04/us-news/texas-il...
1,2026-04-04-05-56-00 +0000,nyt,What We Know About the F-15E Strike Eagle Shot...,https://www.nytimes.com/2026/04/03/world/middl...
2,2026-04-04-05-40-28 +0000,nypost,Florida handyman fined $345 for parking work t...,https://nypost.com/2026/04/04/us-news/florida-...
3,2026-04-04-05-30-36 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/04/world/...
4,2026-04-04-05-18-18 +0000,nyt,"Liamine Zeroual, Algerian President During Civ...",https://www.nytimes.com/2026/04/02/world/afric...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
59    trump     43
13     iran     34
28      war     21
338  report     13
337    jobs     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
120,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...,128
234,2026-04-03-11-28-34 +0000,bbc,When will the Iran war end? Tracing the Trump ...,https://www.bbc.com/news/articles/c4g4e6z9960o...,120
45,2026-04-04-00-02-20 +0000,nyt,War With Iran Clarifies Trump’s Spending Prior...,https://www.nytimes.com/2026/04/02/us/politics...,117
205,2026-04-03-14-28-47 +0000,latimes,2 U.S. aircraft downed as Iran war escalates; ...,https://www.latimes.com/world-nation/story/202...,106
168,2026-04-03-16-19-45 +0000,nypost,Trump briefed on downed US fighter jet in Iran,https://nypost.com/2026/04/03/us-news/trump-br...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
120,128,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...
261,81,2026-04-03-09-30-00 +0000,wsj,The March jobs report due Friday morning will ...,https://www.wsj.com/economy/jobs/march-jobs-re...
128,53,2026-04-03-19-22-00 +0000,wsj,President Trump released a summary of his budg...,https://www.wsj.com/politics/policy/trump-budg...
205,51,2026-04-03-14-28-47 +0000,latimes,2 U.S. aircraft downed as Iran war escalates; ...,https://www.latimes.com/world-nation/story/202...
246,41,2026-04-03-10-56-00 +0000,wsj,The near-term legal and political mess that is...,https://www.wsj.com/politics/chaos-over-bondis...
125,37,2026-04-03-19-45-08 +0000,latimes,Two fires break out in Southern California ami...,https://www.latimes.com/california/story/2026-...
64,31,2026-04-03-22-35-05 +0000,nyt,Ex-US Army Pilot Recalls Battle for Survival W...,https://www.nytimes.com/2026/04/03/world/middl...
106,29,2026-04-03-20-54-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/finance/investing/tech-med...
159,28,2026-04-03-16-47-39 +0000,nypost,French-owned container ship safely passes thro...,https://nypost.com/2026/04/03/world-news/frenc...
122,27,2026-04-03-20-00-30 +0000,nyt,No One at Waffle House Remembers FEMA Official...,https://www.nytimes.com/2026/04/03/us/fema-gre...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)