## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-26-22-16-37 +0000,nyt,How the Reflecting Pool Turned Green: Missing ...,https://www.nytimes.com/2026/06/26/us/politics...
1,2026-06-26-22-12-04 +0000,nyt,Pete Buttigieg Says He Was Separated From His ...,https://www.nytimes.com/2026/06/26/us/politics...
2,2026-06-26-22-10-24 +0000,nyt,What to Know About Problems at the Reflecting ...,https://www.nytimes.com/2026/06/26/us/politics...
3,2026-06-26-22-10-00 +0000,wsj,The WSJ Dollar Index Rises 0.56% This Week to ...,https://www.wsj.com/articles/asian-currencies-...
4,2026-06-26-22-09-17 +0000,nyt,Venezuela Live Updates: Trump’s Vow to ‘Run’ V...,https://www.nytimes.com/live/2026/06/26/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2497/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
17       trump     30
26   venezuela     24
217        new     21
46        iran     21
15      attack     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
177,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...,113
4,2026-06-26-22-09-17 +0000,nyt,Venezuela Live Updates: Trump’s Vow to ‘Run’ V...,https://www.nytimes.com/live/2026/06/26/world/...,94
155,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...,93
142,2026-06-26-18-03-32 +0000,bbc,Trump accuses Iran of ceasefire breach after S...,https://www.bbc.co.uk/news/articles/ckg54g0ry0...,91
356,2026-06-25-23-40-00 +0000,wsj,"Iran Attacks Cargo Ship, Testing Trump’s Deal ...",https://www.wsj.com/world/middle-east/iran-att...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
177,113,2026-06-26-16-15-31 +0000,nypost,Trump says Iran violated cease-fire agreement ...,https://nypost.com/2026/06/26/world-news/trump...
336,83,2026-06-26-01-08-00 +0000,wsj,California’s proposed billionaire tax will app...,https://www.wsj.com/politics/policy/california...
250,70,2026-06-26-11-25-52 +0000,nypost,Neighbors dig through Venezuela rubble in desp...,https://nypost.com/2026/06/26/world-news/neigh...
338,70,2026-06-26-01-00-00 +0000,wsj,New York City’s business elites are overhaulin...,https://www.wsj.com/politics/policy/wall-stree...
86,48,2026-06-26-19-55-03 +0000,nypost,Devastated dad reveals last time he spoke to h...,https://nypost.com/2026/06/26/us-news/devastat...
302,46,2026-06-26-08-11-08 +0000,nypost,Saudi doctor sentenced to life in prison for d...,https://nypost.com/2026/06/26/world-news/saudi...
147,46,2026-06-26-17-48-34 +0000,nyt,"John Bolton, Former Trump Adviser, Pleads Guil...",https://www.nytimes.com/2026/06/26/us/politics...
174,45,2026-06-26-16-26-28 +0000,nypost,Ex-’60 Minutes’ boss Bill Owens blasts Paramou...,https://nypost.com/2026/06/26/media/ex-60-minu...
162,36,2026-06-26-17-00-00 +0000,wsj,The search for a new leader of the Federal Res...,https://www.wsj.com/economy/central-banking/at...
155,36,2026-06-26-17-11-00 +0000,wsj,President Trump threatened to greatly increase...,https://www.wsj.com/politics/policy/trump-thre...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)