## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-20-02-16-49 +0000,bbc,Trump threatens 'tremendous economic consequen...,https://www.bbc.co.uk/news/articles/c2k7e83ynj...
1,2026-08-20-02-15-14 +0000,nyt,Prince Harry and Meghan Will Move Back to U.K....,https://www.nytimes.com/2026/08/19/world/europ...
2,2026-08-20-02-05-20 +0000,bbc,Giant whales move into Greenland waters as ice...,https://www.bbc.co.uk/news/articles/cq6dn9gj7e...
3,2026-08-20-02-00-00 +0000,wsj,Asia’s Businesses Struggle to Shake Off the Sw...,https://www.wsj.com/world/asia/asias-businesse...
4,2026-08-20-01-58-03 +0000,nyt,Harry and Meghan’s Break with Britain and Plan...,https://www.nytimes.com/2026/08/19/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2495/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     62
133      new     19
60   florida     17
222       up     15
8       iran     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
253,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...,128
213,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...,126
397,2026-08-19-03-35-00 +0000,wsj,President Trump said he would pause a 50% tari...,https://www.wsj.com/economy/trade/trump-pauses...,123
119,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...,123
164,2026-08-19-19-15-24 +0000,chitri,President Donald Trump picks Dr. Heidi Overton...,https://www.chicagotribune.com/2026/08/19/trum...,120

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
253,128,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
7,101,2026-08-20-01-54-00 +0000,wsj,Angie Nixon pulled off her upset in the Democr...,https://www.wsj.com/politics/elections/how-dem...
377,61,2026-08-19-08-10-01 +0000,wsj,"Stock Market News, Aug. 19, 2026: Bond Yields ...",https://www.wsj.com/livecoverage/stock-market-...
119,61,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
258,54,2026-08-19-15-33-32 +0000,bbc,Israel confirms soldiers fired at car in which...,https://www.bbc.co.uk/news/articles/crl7yjlpx2...
213,47,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...
128,44,2026-08-19-20-43-04 +0000,nypost,"Mark Zuckerberg’s Meta had ‘don’t ask, don’t t...",https://nypost.com/2026/08/19/business/mark-zu...
159,44,2026-08-19-19-45-34 +0000,nypost,Iran threatens to strike US bases in Europe if...,https://nypost.com/2026/08/19/world-news/iran-...
219,42,2026-08-19-17-07-33 +0000,nypost,Five Americans killed in fiery Kenya helicopte...,https://nypost.com/2026/08/19/world-news/ameri...
233,42,2026-08-19-16-34-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)