## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-16-15-12 +0000,nypost,Mystery as crypto millionaire’s elderly father...,https://nypost.com/2026/04/27/us-news/crypto-m...
1,2026-04-27-16-10-58 +0000,nypost,‘Award-winning special education teacher alleg...,https://nypost.com/2026/04/27/us-news/award-wi...
2,2026-04-27-16-09-58 +0000,nypost,"Slain NYPD Detective Jonathan Diller’s widow, ...",https://nypost.com/2026/04/27/us-news/slain-ny...
3,2026-04-27-16-09-41 +0000,nypost,Iran offers to reopen Strait of Hormuz — but w...,https://nypost.com/2026/04/27/us-news/iran-off...
4,2026-04-27-16-07-45 +0000,bbc,Oil prices rise as US-Iran peace talks stall,https://www.bbc.com/news/articles/c15d57pv925o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

              word  score
63           trump     31
88        shooting     20
87          dinner     17
34            iran     16
86  correspondents     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
189,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,140
40,2026-04-27-14-43-17 +0000,nypost,Melania Trump marks quiet birthday day after ‘...,https://nypost.com/2026/04/27/us-news/melania-...,113
228,2026-04-26-21-46-52 +0000,nypost,Witness describes the moment gunman Cole Allen...,https://nypost.com/2026/04/26/us-news/witness-...,108
221,2026-04-26-22-12-38 +0000,nypost,Trump and his allies insist Saturday’s WHCD sh...,https://nypost.com/2026/04/26/us-news/presiden...,94
148,2026-04-27-09-19-11 +0000,bbc,Trump says King will be 'very safe' during US ...,https://www.bbc.com/news/articles/c4gjger58jzo...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
189,140,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
213,73,2026-04-26-23-04-26 +0000,nypost,King Charles’s royal visit to Washington still...,https://nypost.com/2026/04/26/world-news/king-...
21,62,2026-04-27-15-46-18 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
53,52,2026-04-27-14-08-52 +0000,nyt,China Will Require Meta to Unwind Acquisition ...,https://www.nytimes.com/2026/04/27/business/ch...
136,45,2026-04-27-10-00-00 +0000,startribune,Minnesota 12-year-old is first in new trial of...,https://www.startribune.com/minnesota-12-year-...
146,43,2026-04-27-09-27-55 +0000,nypost,Elon Musk and OpenAI CEO Sam Altman head to co...,https://nypost.com/2026/04/27/business/elon-mu...
54,40,2026-04-27-14-01-30 +0000,nypost,Mass exodus fears as California billionaire ta...,https://nypost.com/2026/04/27/us-news/californ...
202,36,2026-04-27-00-15-40 +0000,nypost,Ex-President Barack Obama claims ‘we don’t hav...,https://nypost.com/2026/04/26/us-news/ex-presi...
44,34,2026-04-27-14-36-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
106,31,2026-04-27-11-09-52 +0000,nypost,Massachusetts acupuncturist accused of killing...,https://nypost.com/2026/04/27/us-news/massachu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)