## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-15-02-44-19 +0000,nypost,Biden’s refusal to drop out of 2024 election h...,https://nypost.com/2026/07/14/us-news/bidens-r...
1,2026-07-15-02-35-00 +0000,wsj,"Trump Reverses 20% Strait of Hormuz Toll, as U...",https://www.wsj.com/world/middle-east/trump-ir...
2,2026-07-15-02-22-45 +0000,nypost,"Met Museum, several elite NYC prep schools amo...",https://nypost.com/2026/07/14/us-news/met-muse...
3,2026-07-15-02-22-23 +0000,bbc,"China economic growth falls sharply, missing t...",https://www.bbc.co.uk/news/articles/cd959x4edy...
4,2026-07-15-02-16-46 +0000,latimes,A SoCal tow company accused of illegally selli...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
12    trump     37
19     iran     32
307     new     19
94      ice     18
15   hormuz     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
108,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...,155
257,2026-07-14-16-06-00 +0000,wsj,The Battle for Hormuz: Trump Shifts Into Dange...,https://www.wsj.com/world/middle-east/the-batt...,124
168,2026-07-14-20-07-29 +0000,nyt,Trump Drops Plan to Tax Ships in Strait of Hor...,https://www.nytimes.com/2026/07/14/world/middl...,120
57,2026-07-14-23-17-27 +0000,bbc,Trump retreat over Hormuz tolls suggests he is...,https://www.bbc.co.uk/news/articles/crele3r8j1...,120
1,2026-07-15-02-35-00 +0000,wsj,"Trump Reverses 20% Strait of Hormuz Toll, as U...",https://www.wsj.com/world/middle-east/trump-ir...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
108,155,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...
121,76,2026-07-14-21-19-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...
91,75,2026-07-14-22-13-00 +0000,wsj,The House passed legislation supported by Pres...,https://www.wsj.com/politics/policy/house-pass...
137,63,2026-07-14-21-01-48 +0000,latimes,Oil tanker captain didn't know he was hauling ...,https://www.latimes.com/california/story/2026-...
250,60,2026-07-14-16-39-12 +0000,latimes,ICE will suspend most vehicle stops in the wak...,https://www.latimes.com/world-nation/story/202...
366,58,2026-07-14-03-51-12 +0000,nyt,Paramount-Warner Bros. Merger Is Challenged in...,https://www.nytimes.com/2026/07/13/business/pa...
247,52,2026-07-14-16-40-54 +0000,nypost,"Iran claims attacks on Bahrain, Jordan, Strait...",https://nypost.com/2026/07/14/world-news/iran-...
8,42,2026-07-15-02-08-26 +0000,nypost,Another TV shake-up rocks NBC Sports Bay Area ...,https://nypost.com/2026/07/14/us-news/popular-...
75,34,2026-07-14-22-43-32 +0000,nyt,White House Cheers Inflation Data While Iran W...,https://www.nytimes.com/2026/07/14/business/ec...
24,32,2026-07-15-01-01-23 +0000,nyt,One Dead and Two Missing in San Francisco Bay ...,https://www.nytimes.com/2026/07/14/us/boat-fir...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)