## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-14-12-57-00 +0000,wsj,Consumer prices were up 3.7% in September from...,https://www.wsj.com/economy/cpi-inflation-repo...
1,2026-10-14-12-51-00 +0000,wsj,Broad Pickup in Prices Lifted Inflation to 3.7...,https://www.wsj.com/economy/cpi-inflation-repo...
2,2026-10-14-12-49-31 +0000,nyt,Russell Brand Labeled ‘Sexual Predator’ as Tri...,https://www.nytimes.com/2026/10/14/arts/russel...
3,2026-10-14-12-49-26 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/14/busine...
4,2026-10-14-12-48-17 +0000,nypost,Inflation heats up to 3.7% in September — more...,https://nypost.com/2026/10/14/business/inflati...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2360/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
58      trump     44
578        ai     20
88        new     19
3          up     15
541  kimberly     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,169
399,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,121
211,2026-10-14-01-00-00 +0000,wsj,"Trying to save her job, Kimberly Guilfoyle cla...",https://www.wsj.com/politics/policy/kimberly-g...,120
385,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,119
238,2026-10-13-22-49-21 +0000,nypost,Trump allies think Kimberly Guilfoyle’s ‘hope’...,https://nypost.com/2026/10/13/us-news/trump-al...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,169,2026-10-14-04-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
211,120,2026-10-14-01-00-00 +0000,wsj,"Trying to save her job, Kimberly Guilfoyle cla...",https://www.wsj.com/politics/policy/kimberly-g...
413,72,2026-10-13-15-06-27 +0000,chitri,Six Flags Great America roller coaster closed ...,https://www.chicagotribune.com/2026/10/13/six-...
63,70,2026-10-14-10-31-04 +0000,nypost,Russell Brand admits he’s ‘concerned’ at start...,https://nypost.com/2026/10/14/world-news/russe...
430,70,2026-10-13-14-00-00 +0000,wsj,Home sales in September rose for the first tim...,https://www.wsj.com/economy/housing/home-sales...
151,65,2026-10-14-07-22-00 +0000,wsj,Oil Prices Rise as Traders Weigh Saudi Aramco ...,https://www.wsj.com/business/energy-oil/oil-pr...
138,55,2026-10-14-08-00-00 +0000,cbc,Why Zelenskyy's claims that Ukraine drone atta...,https://www.cbc.ca/news/world/yankex-russia-uk...
203,53,2026-10-14-01-29-49 +0000,nypost,Ilhan Omar slams ‘ludicrous’ federal investiga...,https://nypost.com/2026/10/13/us-news/ilhan-om...
353,51,2026-10-13-18-10-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
35,48,2026-10-14-11-45-00 +0000,wsj,The Morning Risk Report: Bank of America to Pa...,https://www.wsj.com/risk-compliance-journal/th...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)