## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-12-57-36 +0000,nyt,Live Updates: France Deploys Vast Security For...,https://www.nytimes.com/live/2026/10/24/world/...
1,2026-10-24-12-54-30 +0000,nyt,"Attention, Passengers: High Airfares May Be He...",https://www.nytimes.com/2026/10/24/business/ai...
2,2026-10-24-12-51-26 +0000,nyt,What This Democrat’s Surge in Texas Says About...,https://www.nytimes.com/2026/10/24/magazine/gi...
3,2026-10-24-12-50-46 +0000,nyt,5 Takeaways From Our Investigation of Trump’s ...,https://www.nytimes.com/2026/10/24/climate/tak...
4,2026-10-24-12-48-05 +0000,nypost,Bullies planted fake shooting threat to smear ...,https://nypost.com/2026/10/24/us-news/florida-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2369/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
24      trump     44
64        new     16
85    ukraine     15
115  election     15
2      france     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
165,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,163
232,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,105
314,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...,101
299,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,91
120,2026-10-24-02-35-00 +0000,wsj,The Trump administration has asked a federal c...,https://www.wsj.com/politics/elections/justice...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
165,163,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
325,59,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls o...,https://nypost.com/2026/10/23/business/oil-pri...
132,57,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
314,57,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...
21,53,2026-10-24-11-21-50 +0000,nypost,NJ middle school teacher busted in prostitutio...,https://nypost.com/2026/10/24/us-news/nj-teach...
14,51,2026-10-24-12-00-00 +0000,nypost,Bombshell poll finds California voters say sta...,https://nypost.com/2026/10/24/us-news/xavier-b...
131,45,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
7,38,2026-10-24-12-32-42 +0000,cbc,France deploys thousands of police amid a new ...,https://www.cbc.ca/news/world/france-cost-of-l...
254,38,2026-10-23-17-58-18 +0000,nypost,Ohio Dem Amy Acton’s estranged mom left five-d...,https://nypost.com/2026/10/23/us-news/amy-acto...
292,36,2026-10-23-16-17-08 +0000,nypost,Dramatic moment Israeli soldiers kill 2 Hamas ...,https://nypost.com/2026/10/23/world-news/netan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)