## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-02-09-30-00 +0000,wsj,Workers Seeking Compensation for Injuries Face...,https://www.wsj.com/us-news/law/workers-seekin...
1,2026-08-02-09-30-00 +0000,wsj,America’s Lettuce Crisis Has Shoppers Ditching...,https://www.wsj.com/business/retail/farmers-ma...
2,2026-08-02-09-30-00 +0000,wsj,Five Things You Didn’t Know About the Nancy Gu...,https://www.wsj.com/us-news/five-things-you-di...
3,2026-08-02-09-10-51 +0000,bbc,Trump cancels Iran strikes subject to deal bei...,https://www.bbc.co.uk/news/articles/cjwx74qgld...
4,2026-08-02-09-01-54 +0000,nyt,Can Democratic Socialists Agree on Anything? T...,https://www.nytimes.com/2026/08/02/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2290/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
22        trump     24
197       spain     11
5           new     10
112       ceuta      9
371  california      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
97,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...,54
98,2026-08-01-21-28-51 +0000,chitri,Jeanine Pirro refutes President Donald Trump’s...,https://www.chicagotribune.com/2026/08/01/hear...,54
128,2026-08-01-17-16-51 +0000,bbc,Trump administration drops Reflecting Pool van...,https://www.bbc.co.uk/news/articles/cz05yx5dd7...,51
116,2026-08-01-19-30-50 +0000,nyt,Trump’s Polling Numbers Hit a New Low. Don’t E...,https://www.nytimes.com/2026/08/01/us/politics...,49
49,2026-08-02-02-34-48 +0000,nypost,Trump says Iran agreed to ‘perimeters’ of a pe...,https://nypost.com/2026/08/01/us-news/trump-sa...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
97,54,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...
170,41,2026-08-01-13-03-07 +0000,nypost,Spain installing containment fence between Mor...,https://nypost.com/2026/08/01/world-news/spain...
112,35,2026-08-01-19-59-09 +0000,nyt,"Nirmal Purja, Renowned Mountaineer, Is Found D...",https://www.nytimes.com/2026/08/01/world/asia/...
204,33,2026-08-01-09-57-10 +0000,nypost,FIFA officials plot mutiny to oust Gianni Infa...,https://nypost.com/2026/08/01/business/uefa-ha...
58,31,2026-08-02-01-00-00 +0000,wsj,High-profile donors have given little or no mo...,https://www.wsj.com/politics/elections/democra...
146,31,2026-08-01-16-00-00 +0000,wsj,A Tech Founder Wanted to Start a New Country. ...,https://www.wsj.com/tech/a-tech-founder-wanted...
30,27,2026-08-02-06-48-49 +0000,nypost,13 tourists killed in plane crash near Peru’s ...,https://nypost.com/2026/08/02/world-news/peru-...
50,25,2026-08-02-02-25-13 +0000,nypost,Fast-moving Feliz Fire wildfire explodes in No...,https://nypost.com/2026/08/01/us-news/fast-mov...
47,25,2026-08-02-03-04-00 +0000,wsj,"Three Dead, at Least Five Injured in Idaho Sho...",https://www.wsj.com/us-news/three-dead-at-leas...
80,24,2026-08-01-23-56-56 +0000,nypost,Saudi Arabia gearing up for major assault and ...,https://nypost.com/2026/08/01/world-news/saudi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)