## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
1,2026-06-09-07-56-00 +0000,wsj,Gold Edges Lower as Traders Await Clarity on M...,https://www.wsj.com/finance/commodities-future...
2,2026-06-09-07-54-00 +0000,wsj,"Oil Falls After Israel, Iran Halt Attacks That...",https://www.wsj.com/finance/commodities-future...
3,2026-06-09-07-53-00 +0000,wsj,"China’s Strength in Semiconductors, Rare Earth...",https://www.wsj.com/economy/trade/chinas-expor...
4,2026-06-09-07-48-40 +0000,nyt,Israel Halts Iran Strikes After Trump Claims P...,https://www.nytimes.com/live/2026/06/08/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
39    trump     31
23     iran     26
22   israel     20
6        up     17
138     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-06-09-07-48-40 +0000,nyt,Israel Halts Iran Strikes After Trump Claims P...,https://www.nytimes.com/live/2026/06/08/world/...,103
143,2026-06-08-20-28-25 +0000,nyt,Netanyahu Called Off Iran Strikes After Trump ...,https://www.nytimes.com/2026/06/08/us/politics...,87
271,2026-06-08-11-42-45 +0000,latimes,Trump tells Iran and Israel to stop 'shooting'...,https://www.latimes.com/world-nation/story/202...,87
146,2026-06-08-20-16-00 +0000,wsj,A federal judge invalidated the Trump administ...,https://www.wsj.com/politics/policy/judge-stri...,83
17,2026-06-09-06-33-11 +0000,bbc,Trump booed in New York as he becomes first US...,https://www.bbc.com/news/articles/czj89mz3mzzo...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,103,2026-06-09-07-48-40 +0000,nyt,Israel Halts Iran Strikes After Trump Claims P...,https://www.nytimes.com/live/2026/06/08/world/...
164,75,2026-06-08-19-11-20 +0000,nypost,Spencer Pratt issues bold rallying cry after N...,https://nypost.com/2026/06/08/us-news/spencer-...
0,61,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
146,52,2026-06-08-20-16-00 +0000,wsj,A federal judge invalidated the Trump administ...,https://www.wsj.com/politics/policy/judge-stri...
42,48,2026-06-09-02-00-00 +0000,wsj,Trump and his allies are escalating allegation...,https://www.wsj.com/politics/elections/trump-f...
25,47,2026-06-09-05-39-56 +0000,nypost,"Diehard Knicks fans unfazed by Game 3 loss, re...",https://nypost.com/2026/06/09/us-news/diehard-...
219,45,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
60,45,2026-06-09-00-16-29 +0000,nypost,Ex-Graham Platner campaign director says embat...,https://nypost.com/2026/06/08/us-news/ex-graha...
36,43,2026-06-09-02-54-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
178,34,2026-06-08-18-22-32 +0000,nypost,"Chicago, San Francisco, suburban DC school dis...",https://nypost.com/2026/06/08/us-news/chicago-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)