## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-07-17-32-11 +0000,nypost,New footage allegedly shows Tyler Robinson’s e...,https://nypost.com/2026/07/07/us-news/new-foot...
1,2026-07-07-17-29-42 +0000,nyt,Man Arrested for Painting ‘Pam the Bird’ Graff...,https://www.nytimes.com/2026/07/07/world/austr...
2,2026-07-07-17-29-34 +0000,bbc,Coco Gauff beats fellow American Pegula to rea...,https://www.bbc.co.uk/sport/tennis/articles/c0...
3,2026-07-07-17-28-00 +0000,wsj,Manhattan High-Rise at Risk of Partial Collaps...,https://www.wsj.com/real-estate/manhattan-high...
4,2026-07-07-17-27-44 +0000,nyt,Farage Resigns and Says He Will Run Again in S...,https://www.nytimes.com/live/2026/07/07/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
120    trump     36
72   platner     23
114    world     21
95    graham     19
41        he     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
117,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...,160
265,2026-07-06-22-30-20 +0000,nyt,Who Might Replace Graham Platner if He Drops O...,https://www.nytimes.com/2026/07/06/us/politics...,110
199,2026-07-07-07-33-42 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...,107
70,2026-07-07-15-27-46 +0000,nypost,Mayor Zohran Mamdani tells Maine’s Graham Plat...,https://nypost.com/2026/07/07/us-news/mayor-zo...,105
278,2026-07-06-21-46-12 +0000,nypost,Graham Platner bleeding support after rape all...,https://nypost.com/2026/07/06/us-news/rep-ro-k...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
117,160,2026-07-07-13-29-00 +0000,wsj,Democratic Party leaders and close allies urge...,https://www.wsj.com/politics/policy/graham-pla...
199,107,2026-07-07-07-33-42 +0000,nyt,Trump Wanted a U.S. Soccer Star to Play in the...,https://www.nytimes.com/2026/07/06/world/europ...
111,69,2026-07-07-13-47-57 +0000,nypost,Nigel Farage reveals he’s quitting parliament ...,https://nypost.com/2026/07/07/world-news/nigel...
97,67,2026-07-07-14-31-57 +0000,bbc,"Next PM needs to wake UK up to threat of war, ...",https://www.bbc.co.uk/news/articles/cddljy1y3n...
221,50,2026-07-07-03-39-42 +0000,nypost,Iran fires at least two missiles at commercial...,https://nypost.com/2026/07/06/world-news/iran-...
122,49,2026-07-07-13-21-21 +0000,cbc,French court opens door for Marine Le Pen to r...,https://www.cbc.ca/news/world/france-court-mar...
17,40,2026-07-07-17-09-19 +0000,bbc,Top Democrats press Maine Senate candidate to ...,https://www.bbc.co.uk/news/articles/cm2004nx8v...
145,39,2026-07-07-11-08-52 +0000,wapo,Foreign media were granted rare visas to cover...,https://www.washingtonpost.com/world/2026/07/0...
83,38,2026-07-07-15-00-00 +0000,latimes,35 indie movies and Disney's new animated film...,https://www.latimes.com/entertainment-arts/bus...
171,34,2026-07-07-09-30-00 +0000,nypost,Trump to warn NATO countries against using ‘fu...,https://nypost.com/2026/07/07/world-news/trump...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)