## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-23-08-31 +0000,bbc,"World Cup kicks off in Mexico with Shakira, vi...",https://www.bbc.com/news/articles/c2ly928xz8go...
1,2026-06-11-23-07-52 +0000,bbc,Why the economics makes this the craziest worl...,https://www.bbc.com/news/articles/cpv32417nlwo...
2,2026-06-11-23-04-57 +0000,nypost,Disability patients sue New York to stop docto...,https://nypost.com/2026/06/11/us-news/disabili...
3,2026-06-11-23-04-30 +0000,nyt,Melania Trump Unveils New Investment Accounts ...,https://www.nytimes.com/2026/06/11/us/politics...
4,2026-06-11-23-01-48 +0000,bbc,India's 'blue gold' starts a new drinks industry,https://www.bbc.com/news/articles/cdrpe4vly5mo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2684/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
23    trump     40
101    iran     34
0     world     26
158  spacex     19
1       cup     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
169,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...,135
34,2026-06-11-22-10-39 +0000,nyt,Iran War Live Updates: Trump Again Claims Deal...,https://www.nytimes.com/live/2026/06/11/world/...,132
62,2026-06-11-21-29-00 +0000,wsj,"Trump Cancels Iran Strikes, Says Peace Deal Co...",https://www.wsj.com/world/middle-east/trump-ir...,118
126,2026-06-11-19-09-47 +0000,nypost,Dow jumps 900 points after Trump calls off Ira...,https://nypost.com/2026/06/11/business/dow-jum...,114
40,2026-06-11-22-03-40 +0000,wapo,Trump says he has canceled plans to strike Ira...,https://www.washingtonpost.com/world/2026/06/1...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
169,135,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...
22,79,2026-06-11-22-22-58 +0000,nyt,"As World Cup Begins, Mexico City Becomes a Glo...",https://www.nytimes.com/2026/06/11/world/ameri...
110,56,2026-06-11-19-53-53 +0000,nypost,Elon Musk’s SpaceX prices record-breaking $75B...,https://nypost.com/2026/06/11/business/elon-mu...
292,54,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...
285,54,2026-06-11-11-58-14 +0000,bbc,Knicks fans go wild as New York team makes big...,https://www.bbc.com/news/articles/cr47lyzr4q9o...
7,52,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
26,50,2026-06-11-22-18-46 +0000,nypost,Bombshell evidence White House fraud squad fou...,https://nypost.com/2026/06/11/us-news/bombshel...
174,49,2026-06-11-17-34-06 +0000,nypost,Minnesota assassin Vance Boelter admits murder...,https://nypost.com/2026/06/11/us-news/minnesot...
85,45,2026-06-11-20-51-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/policy/showdown-b...
232,45,2026-06-11-14-58-00 +0000,wsj,The ECB became the first major central bank to...,https://www.wsj.com/economy/central-banking/ec...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)