## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-23-02-52-36 +0000,nypost,Fuming NJ mayor charges at resident during fie...,https://nypost.com/2026/10/22/us-news/fuming-n...
1,2026-10-23-02-52-05 +0000,nyt,Video by Left-Wing Group Claims Lindsey Graham...,https://www.nytimes.com/2026/10/22/us/politics...
2,2026-10-23-02-44-50 +0000,48hills,Juvenal knew: Seeing our current ‘orgy of gree...,https://48hills.org/2026/10/juvenal-knew-seein...
3,2026-10-23-02-43-43 +0000,startribune,Live: Wild offense sputtering as road trip con...,https://www.startribune.com/minnesota-wild-cal...
4,2026-10-23-02-33-20 +0000,48hills,"Education funding, from France to San Francisco",https://48hills.org/2026/10/education-funding-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2395/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
91        trump     30
54          new     22
97   california     19
374          ai     15
88           up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
23,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,99
314,2026-10-22-11-53-48 +0000,chitri,Deportations climb under President Donald Trum...,https://www.chicagotribune.com/2026/10/22/depo...,92
323,2026-10-22-11-09-32 +0000,chitri,Voters want the next Congress to focus on cost...,https://www.chicagotribune.com/2026/10/22/cong...,90
348,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...,83
20,2026-10-23-01-38-03 +0000,nypost,Trump administration raises stakes in bombshel...,https://nypost.com/2026/10/22/us-news/trump-do...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
23,99,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
348,83,2026-10-22-10-00-00 +0000,latimes,Hiltzik: The Arizona-Nevada-California water w...,https://www.latimes.com/business/story/2026-10...
320,72,2026-10-22-11-21-00 +0000,wsj,The Morning Risk Report: Meta Ordered to Pay $...,https://www.wsj.com/risk-compliance-journal/th...
249,69,2026-10-22-15-54-08 +0000,nypost,"Oil soars above $113, Nasdaq plummets in worst...",https://nypost.com/2026/10/22/business/oil-soa...
79,50,2026-10-22-22-23-00 +0000,wsj,The Justice Department is examining allegation...,https://www.wsj.com/politics/policy/corey-lewa...
161,48,2026-10-22-19-51-09 +0000,nypost,Elon Musk opens wallet to aid NY Rep. Mike Law...,https://nypost.com/2026/10/22/us-news/elon-mus...
48,42,2026-10-22-23-32-37 +0000,nypost,Why alleged GWB shooter was hit with lesser ch...,https://nypost.com/2026/10/22/us-news/why-alle...
303,42,2026-10-22-13-02-59 +0000,nyt,Covert Russian Group Targets James Talarico Wi...,https://www.nytimes.com/2026/10/22/us/texas-se...
264,40,2026-10-22-15-11-25 +0000,cbc,EU awards human rights prize to International ...,https://www.cbc.ca/news/world/eu-sakharov-priz...
149,40,2026-10-22-20-07-17 +0000,nypost,Ilhan Omar isn’t ‘Squad’ rep’s real name as fe...,https://nypost.com/2026/10/22/us-news/ilhan-om...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)