## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-13-06-10 +0000,nypost,5 black children treated like ‘slaves’ by adop...,https://nypost.com/2026/10/05/us-news/5-black-...
1,2026-10-05-13-01-01 +0000,nyt,Live Updates: Spain Calls Early Election After...,https://www.nytimes.com/live/2026/10/05/world/...
2,2026-10-05-13-00-05 +0000,nyt,"Karoline Leavitt, Trump’s ‘Machine Gun,’ Has a...",https://www.nytimes.com/2026/10/05/business/me...
3,2026-10-05-13-00-00 +0000,missionlocal,The slip,https://missionlocal.org/2026/10/the-slip/
4,2026-10-05-12-59-56 +0000,bbc,"Bombs preventing rescue of kidnapped youths, N...",https://www.bbc.co.uk/news/articles/c6gqw8jg7k...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2652/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
24        new     22
21      trump     19
15   election     19
13      calls     11
235        ai     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
275,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,75
263,2026-10-04-16-20-31 +0000,nypost,Trump reveals new AI czar — and gives him 120 ...,https://nypost.com/2026/10/04/us-news/trump-re...,70
164,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...,69
173,2026-10-05-01-40-31 +0000,cbc,Trump names U.S. intelligence chief Jay Clayto...,https://www.cbc.ca/news/world/jay-clayton-trum...,67
43,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
275,75,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
164,69,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...
229,54,2026-10-04-19-56-00 +0000,wsj,Americans are facing a multifront squeeze from...,https://www.wsj.com/politics/elections/energy-...
146,53,2026-10-05-06-45-01 +0000,nypost,"Former ‘Survivor’ star faces arrest, FBI probe...",https://nypost.com/2026/10/05/us-news/fbi-inve...
217,50,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...
28,45,2026-10-05-12-01-11 +0000,nypost,Christa Pike’s lawyer calls for death row sent...,https://nypost.com/2026/10/05/us-news/christa-...
33,40,2026-10-05-11-34-59 +0000,bbc,Flydubai co-pilot planned to crash plane into ...,https://www.bbc.co.uk/news/articles/cm3691y79x...
191,40,2026-10-04-23-23-39 +0000,nypost,"Boy, 15, arrested after being caught on video ...",https://nypost.com/2026/10/04/world-news/boy-1...
65,36,2026-10-05-10-21-41 +0000,nyt,Will Midterm Elections Complicate the Supreme ...,https://www.nytimes.com/video/us/1000000111847...
161,35,2026-10-05-03-22-37 +0000,nypost,High school runners stumble upon human remains...,https://nypost.com/2026/10/04/us-news/high-sch...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)