## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-18-25-07 +0000,nypost,Meta quietly added facial recognition to smart...,https://nypost.com/2026/06/05/business/meta-qu...
1,2026-06-05-18-23-00 +0000,wsj,"At Russia’s Davos, Putin Tells His Soldiers to...",https://www.wsj.com/world/russia/at-russias-da...
2,2026-06-05-18-22-34 +0000,nyt,Central Ohio Becomes Hub for Tech and Manufact...,https://www.nytimes.com/2026/06/05/business/oh...
3,2026-06-05-18-21-02 +0000,nypost,Historic California pier threatens to crumble ...,https://nypost.com/2026/06/05/us-news/historic...
4,2026-06-05-18-17-24 +0000,nypost,Trump must ‘accept the reality’ there is no I...,https://nypost.com/2026/06/05/world-news/jack-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
35        trump     33
98          new     18
25   california     15
69       market     15
185          up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
29,2026-06-05-17-31-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,96
37,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,94
50,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,86
243,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...,81
162,2026-06-05-11-23-00 +0000,cbc,Senate passes bill for more ICE funding after ...,https://www.cbc.ca/news/world/us-senate-securi...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
29,96,2026-06-05-17-31-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
127,65,2026-06-05-13-47-48 +0000,nypost,"Graham Platner, Susan Collins tied in Maine Se...",https://nypost.com/2026/06/05/us-news/graham-p...
28,53,2026-06-05-17-35-53 +0000,nypost,James Handy’s girlfriend breaks silence after ...,https://nypost.com/2026/06/05/us-news/james-ha...
249,52,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
6,50,2026-06-05-18-16-15 +0000,bbc,Putin says there is 'no point' meeting Zelensk...,https://www.bbc.com/news/articles/cpqpqx5qe40o...
23,43,2026-06-05-17-45-24 +0000,nypost,Karen Read sues police for dead ex-cop boyfrie...,https://nypost.com/2026/06/05/us-news/karen-re...
102,42,2026-06-05-15-19-52 +0000,nypost,"Iran declares support for Hezbollah, demands I...",https://nypost.com/2026/06/05/world-news/iran-...
243,40,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...
259,39,2026-06-05-00-05-45 +0000,nypost,Anthropic calls for global AI slowdown after $...,https://nypost.com/2026/06/04/business/anthrop...
208,37,2026-06-05-08-56-17 +0000,cbc,Chinese leader Xi Jinping to visit North Korea...,https://www.cbc.ca/news/world/xi-jinping-north...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)