## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-12-23-47-19 +0000,bbc,One dead and several hurt after roller coaster...,https://www.bbc.co.uk/news/articles/c6n4ejx8x1...
1,2026-10-12-23-44-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
2,2026-10-12-23-44-00 +0000,wsj,Ilhan Omar’s Home Is Searched by Federal Agents,https://www.wsj.com/politics/policy/ilhan-omar...
3,2026-10-12-23-42-39 +0000,nypost,Halloween goes to the extreme as Super Bowl of...,https://nypost.com/2026/10/12/us-news/californ...
4,2026-10-12-23-40-07 +0000,nyt,"In Grief, a Mother Asks Strangers to ‘Sit Here...",https://www.nytimes.com/2026/10/12/us/grieving...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2386/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
134    trump     42
430   russia     15
394   energy     14
78       new     12
267  ukraine     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
223,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...,120
218,2026-10-12-11-47-59 +0000,nypost,Zelensky says Russia still striking energy fac...,https://nypost.com/2026/10/12/world-news/zelen...,99
253,2026-10-12-09-48-16 +0000,cbc,Zelenskyy says Russia violating Trump's 'energ...,https://www.cbc.ca/news/world/zelenskyy-russia...,98
257,2026-10-12-09-21-38 +0000,wapo,Trump’s diesel deal with Russia shows how tied...,https://www.washingtonpost.com/politics/2026/1...,97
67,2026-10-12-21-20-51 +0000,bbc,Six Ukrainian energy sites hit by Russia since...,https://www.bbc.co.uk/news/articles/cvlyd4pdlw...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
223,120,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...
1,54,2026-10-12-23-44-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
132,54,2026-10-12-17-55-17 +0000,nypost,"Saudi Arabia faces new missile, drone strikes ...",https://nypost.com/2026/10/12/world-news/saudi...
100,47,2026-10-12-20-15-00 +0000,wsj,A federal judge overseeing litigation challeng...,https://www.wsj.com/politics/policy/judge-yell...
152,42,2026-10-12-16-56-43 +0000,nypost,French police detain 14-year-old suspected of ...,https://nypost.com/2026/10/12/world-news/frenc...
186,39,2026-10-12-14-58-48 +0000,chitri,Elon Musk quietly becomes biggest known donor ...,https://www.chicagotribune.com/2026/10/12/elon...
185,38,2026-10-12-15-00-56 +0000,chitri,Republican Trevor De Vries and Democrat Scott ...,https://www.chicagotribune.com/2026/10/12/de-v...
68,36,2026-10-12-21-19-00 +0000,wsj,Energy Stocks Rise as Global Conflicts Push Up...,https://www.wsj.com/finance/stocks/energy-stoc...
95,35,2026-10-12-20-25-49 +0000,nypost,‘RHONJ’ star Teresa Giudice spotted at White H...,https://nypost.com/2026/10/12/us-news/rhonjs-t...
227,34,2026-10-12-11-02-40 +0000,chitri,2 American economists win Nobel prize for over...,https://www.chicagotribune.com/2026/10/12/nobe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)