## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-03-19-17-42 +0000,nypost,Mamdani’s universal childcare plan will cost 5...,https://nypost.com/2026/08/03/us-news/mamdanis...
1,2026-08-03-19-16-37 +0000,nypost,Trump gives Iran ‘last chance’ to sign deal be...,https://nypost.com/2026/08/03/us-news/trump-gi...
2,2026-08-03-19-16-20 +0000,nypost,North Carolina couple found dead one day after...,https://nypost.com/2026/08/03/us-news/north-ca...
3,2026-08-03-19-15-09 +0000,nypost,Illegal migrant who sprayed lighter fluid on b...,https://nypost.com/2026/08/03/us-news/illegal-...
4,2026-08-03-19-12-46 +0000,nyt,"California Democrats Support Billionaire Tax, ...",https://www.nytimes.com/2026/08/03/us/californ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2567/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
8        trump     37
10        iran     23
56       talks     14
48  california     14
55         new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
260,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...,114
5,2026-08-03-19-10-03 +0000,startribune,New talks are 'last chance' for Iran to forge ...,https://www.startribune.com/iran-deja-vu-trump...,113
141,2026-08-03-13-38-30 +0000,chitri,President Donald Trump claims Iran talks will ...,https://www.chicagotribune.com/2026/08/03/trum...,110
130,2026-08-03-14-20-54 +0000,nypost,"Dow soars 500 points, oil slides over 5% after...",https://nypost.com/2026/08/03/business/dow-soa...,108
169,2026-08-03-11-20-12 +0000,nypost,Iran denies Trump claim new peace talks planne...,https://nypost.com/2026/08/03/world-news/iran-...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
260,114,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...
25,93,2026-08-03-18-33-00 +0000,wsj,Two holdout GOP senators who were blocking act...,https://www.wsj.com/politics/policy/blanche-fo...
97,62,2026-08-03-15-43-41 +0000,nypost,Susan Collins strikes bipartisan Senate deal t...,https://nypost.com/2026/08/03/us-news/senate-s...
35,47,2026-08-03-18-21-32 +0000,nypost,"In-N-Out employee, 23, killed in Idaho mass sh...",https://nypost.com/2026/08/03/us-news/in-n-out...
74,43,2026-08-03-16-56-02 +0000,nypost,Elon Musk’s SpaceX aims to shake off AI spendi...,https://nypost.com/2026/08/03/business/elon-mu...
57,42,2026-08-03-17-32-16 +0000,bbc,Welsh national social care service will not ar...,https://www.bbc.co.uk/news/articles/c8enyk27gd...
216,37,2026-08-03-07-58-14 +0000,wsj,"Stock Market Today: Stocks Rally, Oil Slides o...",https://www.wsj.com/livecoverage/stock-market-...
104,37,2026-08-03-15-28-00 +0000,wsj,"Sarah Trone Garriott, the Democratic nominee f...",https://www.wsj.com/politics/policy/inside-the...
237,36,2026-08-03-03-32-21 +0000,bbc,'My only son was shot standing up for justice'...,https://www.bbc.co.uk/news/articles/c5yvqk69en...
128,34,2026-08-03-14-21-17 +0000,nypost,"Ukraine drone crashes into Russian beach, kill...",https://nypost.com/2026/08/03/world-news/russi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)