## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-09-06-25 +0000,bbc,Funding set to double for plan to get rough sl...,https://www.bbc.co.uk/news/articles/c3n04yxn2y...
1,2026-10-26-09-04-47 +0000,bbc,Celebrations in Serbia after veteran ruler Vuč...,https://www.bbc.co.uk/news/articles/cw5yn3xlpr...
2,2026-10-26-09-03-34 +0000,nyt,Darline Graham Gets Help From the Data Center ...,https://www.nytimes.com/2026/10/26/us/politics...
3,2026-10-26-09-02-28 +0000,nyt,Who’s Winning the Race for Congress?,https://www.nytimes.com/2026/10/26/us/politics...
4,2026-10-26-09-02-15 +0000,nyt,What’s Riding on Anthropic Going Public? Nearl...,https://www.nytimes.com/2026/10/26/technology/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2582/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14     election     22
47        trump     21
198        lula     15
203      brazil     13
404  california     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,97
86,2026-10-26-00-51-25 +0000,nypost,"Trump critic Lula wins reelection in Brazil, s...",https://nypost.com/2026/10/25/world-news/trump...,71
103,2026-10-25-23-41-49 +0000,nyt,The presidential election in Brazil is a test ...,https://www.nytimes.com/live/2026/10/25/world/...,67
33,2026-10-26-07-07-26 +0000,nyt,What to Know About Brazil’s Election as Bolson...,https://www.nytimes.com/2026/10/25/world/ameri...,66
217,2026-10-25-11-17-03 +0000,bbc,What to know about Brazil's run-off as Lula an...,https://www.bbc.co.uk/news/articles/c6wyz0r2n0...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,97,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...
90,60,2026-10-26-00-30-06 +0000,chitri,President Donald Trump escalates anti-Muslim a...,https://www.chicagotribune.com/2026/10/25/trum...
78,56,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
182,44,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
217,33,2026-10-25-11-17-03 +0000,bbc,What to know about Brazil's run-off as Lula an...,https://www.bbc.co.uk/news/articles/c6wyz0r2n0...
67,31,2026-10-26-02-13-12 +0000,nypost,New twist in California beach mystery after se...,https://nypost.com/2026/10/25/us-news/dna-brea...
152,31,2026-10-25-19-34-12 +0000,nypost,"Thomas Markle’s home had trove of child porn, ...",https://nypost.com/2026/10/25/world-news/thoma...
111,27,2026-10-25-22-46-43 +0000,nypost,Mayor Mamdani and Gov. Hochul team up to bash ...,https://nypost.com/2026/10/25/us-news/mayor-ma...
87,26,2026-10-26-00-45-21 +0000,chitri,Iranians fear a possible return to all-out war...,https://www.chicagotribune.com/2026/10/25/iran...
149,25,2026-10-25-19-38-58 +0000,nypost,Venezuelan opposition leader María Corina Mach...,https://nypost.com/2026/10/25/world-news/venez...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)