## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-17-13-39 +0000,nypost,Dramatic new video shows moment NYPD tackles I...,https://nypost.com/2026/03/18/us-news/nypd-tac...
1,2026-03-18-17-13-28 +0000,bbc,Fly tippers face clearing up own rubbish as pu...,https://www.bbc.com/news/articles/c9dn770n1deo...
2,2026-03-18-17-13-00 +0000,wsj,How Waiving the Jones Act for Oil Tankers Woul...,https://www.wsj.com/business/energy-oil/how-wa...
3,2026-03-18-17-12-41 +0000,bbc,How high could UK petrol and diesel prices go?,https://www.bbc.com/news/articles/c20zgjzz0e4o...
4,2026-03-18-17-11-38 +0000,nypost,IDF strikes Hezbollah targets across Lebanon a...,https://nypost.com/2026/03/18/world-news/idf-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
76       iran     57
70      trump     45
73        war     34
169  illinois     19
160    israel     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
328,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,190
131,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...,190
179,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,177
280,2026-03-18-02-12-16 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,172
11,2026-03-18-17-07-09 +0000,nyt,Iran War Live Updates: Oil and Gas Prices Jump...,https://www.nytimes.com/live/2026/03/18/world/...,172

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
328,190,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...
276,103,2026-03-18-02-44-31 +0000,nypost,Lt. Gov. Juliana Stratton wins Illinois Senate...,https://nypost.com/2026/03/17/us-news/juliana-...
124,83,2026-03-18-14-35-35 +0000,nypost,Oil spikes after Iran says world’s largest gas...,https://nypost.com/2026/03/18/world-news/oil-s...
31,73,2026-03-18-16-57-14 +0000,nypost,Cesar Chavez’s closest ally reveals he raped h...,https://nypost.com/2026/03/18/us-news/cesar-ch...
338,65,2026-03-17-22-49-03 +0000,bbc,Iranian security chief Ali Larijani killed in ...,https://www.bbc.com/news/articles/c24deezq6meo...
28,57,2026-03-18-16-58-36 +0000,startribune,Minnesota house prices decline for first time ...,https://www.startribune.com/minnesota-house-pr...
367,55,2026-03-17-21-24-00 +0000,wsj,"Russia shares intel with Iran, the SAVE Americ...",https://www.wsj.com/politics/policy/russia-is-...
80,50,2026-03-18-16-00-00 +0000,wsj,"Sen. Markwayne Mullin (R., Okla.), President T...",https://www.wsj.com/politics/national-security...
206,44,2026-03-18-10-00-00 +0000,nypost,"Trump will ‘rebalance’ media, FCC boss Brendan...",https://nypost.com/2026/03/18/us-news/fcc-boss...
376,42,2026-03-17-20-58-14 +0000,nypost,Iran continues intense attacks on Middle East ...,https://nypost.com/2026/03/17/world-news/iran-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)