## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-11-15-51-30 +0000,nyt,Iran War Live Updates: Long-Term Energy Crisis...,https://www.nytimes.com/live/2026/05/11/world/...
1,2026-05-11-15-48-44 +0000,nyt,Oil Prices Rise as Prospects for U.S.-Iran Pea...,https://www.nytimes.com/2026/05/10/business/oi...
2,2026-05-11-15-47-25 +0000,48hills,Wavy Gravy is turning 90. Of course there’s a ...,https://48hills.org/2026/05/wavy-gravy-is-turn...
3,2026-05-11-15-45-08 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/11/world/...
4,2026-05-11-15-45-00 +0000,wsj,Why Companies Are Racing to Put Satellites in ...,https://www.wsj.com/tech/why-companies-are-rac...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
38        trump     31
0          iran     21
128  hantavirus     15
1           war     15
149         new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-05-11-14-27-49 +0000,bbc,Oil prices jump after Trump dismisses Iran pro...,https://www.bbc.com/news/articles/ckgp4ev4yg4o...,91
182,2026-05-11-01-55-13 +0000,bbc,Trump calls Iran response to US proposal to en...,https://www.bbc.com/news/articles/clypgz9e5pmo...,87
0,2026-05-11-15-51-30 +0000,nyt,Iran War Live Updates: Long-Term Energy Crisis...,https://www.nytimes.com/live/2026/05/11/world/...,73
190,2026-05-11-00-39-36 +0000,nyt,Trump and Netanyahu Say Iran War Is Not Over,https://www.nytimes.com/2026/05/10/us/politics...,69
237,2026-05-10-19-08-42 +0000,nypost,"Trump admin open to pausing gas tax, Energy se...",https://nypost.com/2026/05/10/us-news/trump-ad...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,91,2026-05-11-14-27-49 +0000,bbc,Oil prices jump after Trump dismisses Iran pro...,https://www.bbc.com/news/articles/ckgp4ev4yg4o...
240,52,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...
181,42,2026-05-11-02-00-00 +0000,wsj,Women are playing a bigger role in the America...,https://www.wsj.com/economy/jobs/jobs-men-empl...
128,37,2026-05-11-10-00-00 +0000,nypost,Inside Meta’s threat to exit New Mexico over k...,https://nypost.com/2026/05/11/business/inside-...
237,36,2026-05-10-19-08-42 +0000,nypost,"Trump admin open to pausing gas tax, Energy se...",https://nypost.com/2026/05/10/us-news/trump-ad...
46,34,2026-05-11-14-06-28 +0000,nypost,Student gets revenge on creepy school board me...,https://nypost.com/2026/05/11/us-news/student-...
230,34,2026-05-10-19-56-45 +0000,bbc,His father had just been buried. Then West Ban...,https://www.bbc.com/news/articles/cjrpnjpl39po...
133,29,2026-05-11-09-30-00 +0000,nypost,Families of Americans imprisoned in China have...,https://nypost.com/2026/05/11/us-news/family-o...
161,28,2026-05-11-07-53-53 +0000,bbc,BBC tests out England and Argentina's World Cu...,https://www.bbc.com/news/videos/clypw107dqzo?a...
215,27,2026-05-10-21-03-01 +0000,nypost,Remains of US soldier who fell off cliff in Mo...,https://nypost.com/2026/05/10/world-news/remai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)