## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-21-49-47 +0000,nyt,Israeli Allies Ban Trade With Settlements as U...,https://www.nytimes.com/2026/09/08/world/europ...
1,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
2,2026-09-08-21-48-31 +0000,nypost,Mamdani faces new lawsuit over NYC-run grocery...,https://nypost.com/2026/09/08/business/mamdani...
3,2026-09-08-21-47-48 +0000,nyt,Musk Targets Transgender Issues in Key Midterm...,https://www.nytimes.com/2026/09/08/us/politics...
4,2026-09-08-21-46-34 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2344/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
47   trump     43
26     new     24
11     oil     17
43  canada     16
3    trade     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-09-08-21-46-34 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,107
189,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...,98
357,2026-09-08-05-01-12 +0000,nypost,Canada slaps tit-for-tat tariffs on over $20B ...,https://nypost.com/2026/09/08/business/canadas...,92
274,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...,92
1,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,107,2026-09-08-21-46-34 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...
1,91,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
193,73,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...
189,55,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...
55,53,2026-09-08-20-49-16 +0000,nypost,Lindsay Clancy jury was ready to find her not ...,https://nypost.com/2026/09/08/us-news/lindsay-...
57,43,2026-09-08-20-46-58 +0000,nypost,California union threatens strike in war over ...,https://nypost.com/2026/09/08/us-news/californ...
345,42,2026-09-08-07-04-00 +0000,wsj,Australian Government to Allow Users to Opt ou...,https://www.wsj.com/economy/australian-govt-to...
195,42,2026-09-08-15-40-32 +0000,chitri,All 5 killed in Miami cargo jet crash were in ...,https://www.chicagotribune.com/2026/09/08/miam...
380,42,2026-09-08-00-26-55 +0000,nypost,House lawmaker sues to reverse Missouri Suprem...,https://nypost.com/2026/09/07/us-news/house-la...
21,37,2026-09-08-21-27-54 +0000,nyt,"Before Oct. 7 Attack, Netanyahu Was Warned, Re...",https://www.nytimes.com/2026/09/08/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)