## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-15-09-41-29 +0000,nyt,Trump Touts ‘Fantastic Trade Deals’ With China...,https://www.nytimes.com/2026/05/15/business/ec...
1,2026-05-15-09-37-38 +0000,nyt,Delivering Mail on Ukraine’s Front Line,https://www.nytimes.com/video/world/europe/100...
2,2026-05-15-09-33-45 +0000,nypost,Death toll in attack on Kyiv apartment buildin...,https://nypost.com/2026/05/15/world-news/death...
3,2026-05-15-09-30-00 +0000,wsj,The Blockbuster Cerebras IPO Is a Huge Bet on ...,https://www.wsj.com/opinion/the-blockbuster-ce...
4,2026-05-15-09-30-00 +0000,wsj,Live Q&A: Ask Me Your Questions About EVs,https://www.wsj.com/business/autos/live-q-a-as...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     57
5      china     32
41        xi     26
229      new     17
48   beijing     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...,155
67,2026-05-15-06-04-46 +0000,nypost,Extravagant Trump-Xi tea menu revealed — as th...,https://nypost.com/2026/05/15/us-news/extravag...,153
108,2026-05-15-01-30-15 +0000,nypost,Trump says China will ‘invest hundreds of bill...,https://nypost.com/2026/05/14/us-news/china-wi...,145
179,2026-05-14-21-36-36 +0000,nyt,Oil Prices Waver as Trump Meets China’s Xi to ...,https://www.nytimes.com/2026/05/14/business/oi...,144
23,2026-05-15-09-00-24 +0000,nypost,6 key takeaways from historic Trump-Xi China s...,https://nypost.com/2026/05/15/us-news/trump-xi...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,155,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...
99,67,2026-05-15-02-08-00 +0000,wsj,New York Governor Says Fewer Second Homes to P...,https://www.wsj.com/us-news/n-y-gov-hochul-say...
195,59,2026-05-14-21-04-21 +0000,nypost,Gavin Newsom speaks out on ex-aide’s guilty pl...,https://nypost.com/2026/05/14/us-news/gavin-ne...
262,49,2026-05-14-17-52-46 +0000,nyt,Iran Lets Chinese Ships Through Strait of Horm...,https://www.nytimes.com/live/2026/05/14/us/tru...
116,47,2026-05-15-01-00-00 +0000,wsj,The Southern Poverty Law Center built a fortun...,https://www.wsj.com/politics/policy/southern-p...
216,44,2026-05-14-20-23-32 +0000,nyt,"Cerebras, A.I. Chip Maker, Rises 89% in Market...",https://www.nytimes.com/2026/05/14/technology/...
228,42,2026-05-14-19-42-00 +0000,wsj,A Connecticut Republican quit the governor’s r...,https://www.wsj.com/politics/policy/improper-s...
213,36,2026-05-14-20-33-21 +0000,cbc,Cuba suffers partial grid failure hours after ...,https://www.cbc.ca/news/world/cuba-grid-partia...
251,34,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
151,33,2026-05-14-22-51-53 +0000,nyt,Supreme Court Allows Abortion Pill Access by M...,https://www.nytimes.com/2026/05/14/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)