## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-23-02-16-28 +0000,nypost,Apple cutting hundreds more jobs in shift towa...,https://nypost.com/2026/08/22/business/apple-c...
1,2026-08-23-02-00-00 +0000,wsj,This Ancient Temple Is Where China’s Young Peo...,https://www.wsj.com/world/china/this-ancient-t...
2,2026-08-23-01-37-25 +0000,latimes,Newsom signs bill shielding immigrant aid work...,https://www.latimes.com/california/story/2026-...
3,2026-08-23-01-34-15 +0000,bbc,Swedish sword attack victim was 17-year-old gi...,https://www.bbc.co.uk/news/articles/c8jnjp0lwl...
4,2026-08-23-01-25-39 +0000,nyt,Officials Investigating Postal Worker in Assau...,https://www.nytimes.com/2026/08/22/us/pasadena...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
155   trade     18
64    trump     16
140     new     15
177   talks     15
159  canada     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
67,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,133
171,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...,118
116,2026-08-22-13-21-09 +0000,chitri,US and Canada fall deeper into a trade war wit...,https://www.chicagotribune.com/2026/08/22/us-c...,92
58,2026-08-22-20-10-00 +0000,bbc,Carney calls Trump's fresh tariffs a 'miscalcu...,https://www.bbc.co.uk/news/articles/cx272np7vg...,75
76,2026-08-22-18-00-54 +0000,nyt,Carney Stands Up to Trump in U.S.-Canada Trade...,https://www.nytimes.com/2026/08/22/world/canad...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
67,133,2026-08-22-18-59-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
171,41,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
158,40,2026-08-22-09-00-00 +0000,wsj,President Trump is quietly making plans for an...,https://www.wsj.com/politics/policy/trump-new-...
89,32,2026-08-22-16-38-45 +0000,nypost,10 killed in Russian and Ukrainian attacks a d...,https://nypost.com/2026/08/22/world-news/10-ki...
24,31,2026-08-22-22-43-32 +0000,nypost,NBA hopeful who survived heart attack allowed ...,https://nypost.com/2026/08/22/us-news/nba-hope...
26,28,2026-08-22-22-36-03 +0000,nypost,New footage of El Chapo’s first hours in capti...,https://nypost.com/2026/08/22/world-news/new-v...
97,28,2026-08-22-16-00-00 +0000,wsj,"Ashley Hinson has never lost an election. Now,...",https://www.wsj.com/politics/elections/the-for...
49,27,2026-08-22-20-53-30 +0000,nypost,Former football standout identified as teen sh...,https://nypost.com/2026/08/22/us-news/victim-1...
104,25,2026-08-22-14-55-24 +0000,nyt,"Harry and Meghan See Their California Dreams, ...",https://www.nytimes.com/2026/08/22/us/meghan-h...
68,24,2026-08-22-18-31-32 +0000,cbc,Carney says trade deal became untenable when U...,https://www.cbc.ca/news/politics/mark-carney-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)