## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-04-03-56 +0000,nyt,State Department Bypasses Congress to Send Isr...,https://www.nytimes.com/2026/03/06/us/politics...
1,2026-03-07-04-03-18 +0000,nyt,Live Updates: New Wave of Airstrikes Batters T...,https://www.nytimes.com/live/2026/03/06/world/...
2,2026-03-07-03-58-44 +0000,nypost,Anti-Iranian regime protester pummeled at delu...,https://nypost.com/2026/03/06/us-news/anti-reg...
3,2026-03-07-03-55-28 +0000,nypost,Biden says ‘I’m a h— of a lot smarter than mos...,https://nypost.com/2026/03/06/us-news/biden-sa...
4,2026-03-07-03-50-06 +0000,missionlocal,‘Trying to be Mother Teresa:’ Tenderloin leade...,https://missionlocal.org/2026/03/sf-tenderloin...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
40    iran     65
102  trump     54
367   dies     27
184    war     23
8      new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
32,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,220
121,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,179
404,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...,175
117,2026-03-06-22-12-02 +0000,wapo,Trump demands ‘UNCONDITIONAL SURRENDER’ from I...,https://www.washingtonpost.com/national-securi...,169
94,2026-03-06-22-44-51 +0000,nyt,Trump Demands Iran’s ‘Unconditional Surrender’...,https://www.nytimes.com/2026/03/06/world/middl...,167

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
32,220,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
151,80,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
405,69,2026-03-06-05-05-00 +0000,wsj,"Rep. Tony Gonzales (R., Texas) said he wouldn’...",https://www.wsj.com/politics/elections/texas-t...
33,66,2026-03-07-02-00-00 +0000,wsj,Iran’s High-Risk Strategy for a No-Limits Midd...,https://www.wsj.com/world/middle-east/iran-def...
121,60,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...
106,49,2026-03-06-22-37-17 +0000,latimes,Honey is wrapping up her first course at San B...,https://www.latimes.com/california/story/2026-...
331,48,2026-03-06-13-49-00 +0000,wsj,The Justice Department said it released some E...,https://www.wsj.com/politics/policy/doj-says-e...
404,46,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...
279,45,2026-03-06-16-43-53 +0000,nyt,Analysis Suggests School Was Hit Amid U.S. Str...,https://www.nytimes.com/2026/03/05/world/middl...
50,40,2026-03-07-00-34-07 +0000,nyt,"Jeremy Larner, Who Wrote ‘The Candidate,’ a Po...",https://www.nytimes.com/2026/03/06/movies/jere...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)