## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-10-18-05-56 +0000,nypost,Travel blogger makes shocking discovery under ...,https://nypost.com/2026/03/10/world-news/trave...
1,2026-03-10-18-04-07 +0000,nyt,Winter Storm to Bring Ice and Snow to Ottawa a...,https://www.nytimes.com/2026/03/10/weather/ont...
2,2026-03-10-18-04-05 +0000,nypost,Why the Iran war may come down to the control ...,https://nypost.com/2026/03/10/us-news/why-the-...
3,2026-03-10-18-03-12 +0000,nyt,"Live Updates: Nearly 700,000 Flee Israeli Stri...",https://www.nytimes.com/live/2026/03/10/world/...
4,2026-03-10-18-02-12 +0000,bbc,Lammy urges Labour MPs to back jury trial cuts,https://www.bbc.com/news/articles/cpw0eg9q7kwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2488/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
16    iran     61
17     war     44
88   trump     41
176    oil     30
522    new     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
182,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...,215
250,2026-03-10-03-15-14 +0000,nyt,Trump Seeks to Calm Oil and Gas Markets but Sa...,https://www.nytimes.com/2026/03/09/us/politics...,211
248,2026-03-10-03-24-00 +0000,wsj,"Oil Retreats, Asia Equities Rebound After Trum...",https://www.wsj.com/finance/stocks/oil-retreat...,194
385,2026-03-09-18-53-40 +0000,nypost,US sends Cold War heavy-hitter B-52 bombers to...,https://nypost.com/2026/03/09/world-news/us-se...,190
247,2026-03-10-03-32-18 +0000,nyt,"Trump’s War in Iran, and Rising Gas Prices, Co...",https://www.nytimes.com/2026/03/09/us/politics...,184

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
182,215,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...
163,68,2026-03-10-11-24-12 +0000,nypost,Trump says he doesn’t think new Iran leader Mo...,https://nypost.com/2026/03/10/us-news/trump-sa...
151,55,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...
210,50,2026-03-10-09-16-08 +0000,nypost,Five members of Iranian women’s soccer team gr...,https://nypost.com/2026/03/10/world-news/austr...
158,44,2026-03-10-11-43-50 +0000,cbc,"Dozens of Haitian civilians killed by police, ...",https://www.cbc.ca/news/world/haiti-drones-hum...
194,43,2026-03-10-10-00-00 +0000,latimes,DTLA law firm co-founder faces California Stat...,https://www.latimes.com/california/story/2026-...
30,39,2026-03-10-17-14-44 +0000,nypost,Cops clear suspicious package near Gracie Mans...,https://nypost.com/2026/03/10/us-news/cops-pro...
331,38,2026-03-09-21-52-00 +0000,wsj,Lawrence Summers has lost his affiliation with...,https://www.wsj.com/us-news/education/national...
12,38,2026-03-10-17-46-41 +0000,nypost,World’s best restaurant on the brink as sponso...,https://nypost.com/2026/03/10/us-news/noma-on-...
159,33,2026-03-10-11-42-00 +0000,wsj,Saudi Arabia Pushes East-West Pipeline Toward ...,https://www.wsj.com/business/energy-oil/saudi-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)