## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-17-08-52-00 +0000,wsj,"Stocks Rally, Yields Fall as Lower Oil Boosts ...",https://www.wsj.com/finance/commodities-future...
1,2026-09-17-08-50-09 +0000,bbc,Mbappe says he 'stands with Ceuta' after T-shi...,https://www.bbc.co.uk/sport/football/articles/...
2,2026-09-17-08-49-00 +0000,wsj,U.S. Treasury Yields Fall as Market Regains Tr...,https://www.wsj.com/economy/central-banking/u-...
3,2026-09-17-08-47-43 +0000,wsj,Stock Market Today: Stock Futures Climb as Mar...,https://www.wsj.com/livecoverage/stock-market-...
4,2026-09-17-08-44-47 +0000,bbc,Stadium owner Robert Kraft says Ed Sheeran ask...,https://www.bbc.co.uk/news/articles/cmp3073x64...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
247     trump     39
17        fed     32
81       rate     18
215  interest     18
351       new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
159,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...,189
78,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...,152
77,2026-09-17-00-59-00 +0000,wapo,Trump says he told Fed chief to ‘do what you w...,https://www.washingtonpost.com/business/2026/0...,148
255,2026-09-16-18-02-32 +0000,nypost,Fed hikes interest rates for first time in thr...,https://nypost.com/2026/09/16/business/fed-hik...,136
102,2026-09-16-23-16-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
159,189,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...
208,88,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
158,77,2026-09-16-21-16-00 +0000,wsj,"The Fed raised rates, a top Democrat opposes a...",https://www.wsj.com/politics/policy/the-fed-is...
364,75,2026-09-16-11-25-05 +0000,chitri,US-Canada trade war further taxes small busine...,https://www.chicagotribune.com/2026/09/16/us-c...
102,62,2026-09-16-23-16-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...
218,51,2026-09-16-19-21-00 +0000,wsj,The Fed voted unanimously to raise rates for t...,https://www.wsj.com/economy/central-banking/fe...
78,45,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...
18,44,2026-09-17-07-51-31 +0000,nypost,NBC reporter Eliana Moreno’s brother calls out...,https://nypost.com/2026/09/17/us-news/nbc-repo...
194,42,2026-09-16-19-59-57 +0000,bbc,US House votes to hold billionaire Epstein ass...,https://www.bbc.co.uk/news/articles/c62l8g8qlr...
216,39,2026-09-16-19-22-01 +0000,cbc,Fencing goes up around Kennedy Center as activ...,https://www.cbc.ca/news/world/kennedy-center-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)