## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-24-04-12-29 +0000,startribune,Natasha Howard powers Lynx to 85-75 victory at...,https://www.startribune.com/natasha-howard-pow...
1,2026-05-24-04-02-10 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal I...,https://www.nytimes.com/live/2026/05/23/world/...
2,2026-05-24-04-01-15 +0000,nyt,The War-Driven Supply Shock Already Roiling Ma...,https://www.nytimes.com/2026/05/24/business/wh...
3,2026-05-24-04-01-15 +0000,nyt,Can Concrete Molds Revive Coral Reefs Ruined b...,https://www.nytimes.com/2026/05/24/world/asia/...
4,2026-05-24-03-59-51 +0000,bbc,Suspect killed after opening fire on Secret Se...,https://www.bbc.com/news/articles/cjwp82ye4y3o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2694/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
10        trump     26
6          iran     19
106    chemical     13
128  california     12
12         deal     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
114,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...,98
93,2026-05-23-18-09-12 +0000,nypost,Iran war agreement being ‘fine-tuned’ as Trump...,https://nypost.com/2026/05/23/world-news/iran-...,84
127,2026-05-23-14-44-00 +0000,wsj,"For more than a year, Republican senators had ...",https://www.wsj.com/politics/policy/trump-repu...,79
1,2026-05-24-04-02-10 +0000,nyt,Iran War Live Updates: Trump Says Peace Deal I...,https://www.nytimes.com/live/2026/05/23/world/...,78
24,2026-05-24-01-18-31 +0000,bbc,Trump says Iran deal 'largely negotiated' incl...,https://www.bbc.com/news/articles/crmp121z3z8o...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
114,98,2026-05-23-16-05-30 +0000,nypost,Trump says he’s a ‘solid 50/50’ on Iran as he ...,https://nypost.com/2026/05/23/us-news/trump-a-...
7,55,2026-05-24-03-30-01 +0000,startribune,Suspect dead after opening fire near White Hou...,https://www.startribune.com/law-enforcement-au...
65,43,2026-05-23-21-36-13 +0000,cbc,California governor declares state of emergenc...,https://www.cbc.ca/news/world/chemical-tank-ov...
71,39,2026-05-23-20-45-32 +0000,nyt,Xi Calls for All-Out Rescue After Coal Mine Ex...,https://www.nytimes.com/2026/05/23/world/asia/...
57,33,2026-05-23-22-14-35 +0000,nypost,Ukraine bracing for ‘significant air attack’ f...,https://nypost.com/2026/05/23/world-news/ukrai...
40,30,2026-05-23-23-48-58 +0000,nypost,Empty streets and packed shelters across Orang...,https://nypost.com/2026/05/23/us-news/empty-st...
144,30,2026-05-23-12-30-00 +0000,nypost,Husband recounts wife’s tragic scuba dive deat...,https://nypost.com/2026/05/23/world-news/husba...
27,28,2026-05-24-01-00-00 +0000,wsj,The Stock Market Has Never Been So Good When P...,https://www.wsj.com/economy/consumers/stock-ma...
149,27,2026-05-23-12-00-00 +0000,latimes,"Lopez: Spencer Pratt, please call me. You don'...",https://www.latimes.com/california/story/2026-...
22,25,2026-05-24-01-39-25 +0000,latimes,Explosion would cause significant damage aroun...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)