## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-19-21-09-34 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/19/world/...
1,2026-07-19-21-04-02 +0000,nypost,‘Skeletal remains’ found in Idaho river identi...,https://nypost.com/2026/07/19/us-news/skeletal...
2,2026-07-19-20-48-48 +0000,bbc,"Madonna, Justin Bieber, Shakira and BTS perfor...",https://www.bbc.co.uk/news/articles/clyxjl0wkl...
3,2026-07-19-20-44-26 +0000,nyt,Misery in the Epicenter of Cyclospora: ‘A Base...,https://www.nytimes.com/2026/07/19/us/cyclospo...
4,2026-07-19-20-42-26 +0000,nypost,Wyclef Jean suddenly pulls out of California S...,https://nypost.com/2026/07/19/us-news/wyclef-j...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2489/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19   world     20
20     cup     17
67    iran     16
74  killed     13
97     new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
188,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...,76
97,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...,75
32,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,74
8,2026-07-19-20-36-40 +0000,nyt,Iran War Live Updates: Another U.S. Service Me...,https://www.nytimes.com/live/2026/07/19/world/...,65
28,2026-07-19-19-25-24 +0000,chitri,Trump celebrates the World Cup as a US victory...,https://www.chicagotribune.com/2026/07/19/trum...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
188,76,2026-07-18-22-42-00 +0000,wsj,"Two U.S. Troops Were Killed, One Is Missing Af...",https://www.wsj.com/world/middle-east/two-u-s-...
97,75,2026-07-19-13-41-13 +0000,nyt,"Sánchez will attend the World Cup final, and s...",https://www.nytimes.com/live/2026/us/fifa-worl...
189,33,2026-07-18-22-36-14 +0000,nypost,"Furious Trump defends war, launches revenge at...",https://nypost.com/2026/07/18/us-news/trump-mo...
176,32,2026-07-19-00-00-00 +0000,wsj,He Ran a Strip Club. Now He Wants to Build Cal...,https://www.wsj.com/us-news/he-ran-a-strip-clu...
183,28,2026-07-18-23-29-48 +0000,chitri,Social media influencers Andrew and Tristian T...,https://www.chicagotribune.com/2026/07/18/tate...
66,26,2026-07-19-17-19-00 +0000,wsj,Boeing Needs to Shore Up Finances Before Launc...,https://www.wsj.com/business/airlines/boeing-n...
6,23,2026-07-19-20-39-36 +0000,nypost,Film group unearths early TV appearance of 198...,https://nypost.com/2026/07/19/us-news/film-gro...
9,22,2026-07-19-20-34-19 +0000,startribune,"Air quality alert in effect across Minnesota, ...",https://www.startribune.com/persistent-minneso...
39,22,2026-07-19-18-35-33 +0000,nypost,Chilling video shows Monaco bomb attack that n...,https://nypost.com/2026/07/19/world-news/video...
33,21,2026-07-19-19-07-22 +0000,nypost,CNN’s Van Jones warns far left: ‘STOP pooping ...,https://nypost.com/2026/07/19/us-news/cnns-van...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)