## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-08-30-24 +0000,bbc,Top South African police officer survives assa...,https://www.bbc.co.uk/news/articles/c9v2x700l8...
1,2026-06-29-08-29-53 +0000,nypost,American Airlines plane forced to abort takeof...,https://nypost.com/2026/06/29/us-news/american...
2,2026-06-29-08-28-48 +0000,nyt,Oil Prices Rise on Possible Deal to Suspend At...,https://www.nytimes.com/2026/06/29/business/oi...
3,2026-06-29-08-15-29 +0000,bbc,Pakistani strikes kill dozens in Afghanistan,https://www.bbc.co.uk/news/articles/cy8wygyed0...
4,2026-06-29-08-15-00 +0000,wsj,Gold Prices Fall as Market Focuses on Iran Pea...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
39        iran     11
531      trump     10
115  venezuela     10
208         ai      8
22         oil      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
87,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...,38
161,2026-06-28-13-31-18 +0000,nypost,Iran must develop nuclear bomb to protect ‘pea...,https://nypost.com/2026/06/28/world-news/iran-...,37
73,2026-06-28-23-09-14 +0000,nypost,GOP claims it will pick up NY House seats desp...,https://nypost.com/2026/06/28/us-news/gop-clai...,36
140,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...,34
135,2026-06-28-16-20-12 +0000,nypost,GOP governor in Ohio — where Trump claimed Hai...,https://nypost.com/2026/06/28/us-news/gop-ohio...,33

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
87,38,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...
140,34,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...
135,33,2026-06-28-16-20-12 +0000,nypost,GOP governor in Ohio — where Trump claimed Hai...,https://nypost.com/2026/06/28/us-news/gop-ohio...
176,31,2026-06-28-10-08-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
165,31,2026-06-28-12-10-56 +0000,nypost,At least 2 dead after Ukraine drone assault se...,https://nypost.com/2026/06/28/world-news/at-le...
146,30,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
129,29,2026-06-28-17-18-59 +0000,nypost,Slippery Mamdani won’t say whether he supports...,https://nypost.com/2026/06/28/us-news/mamdani-...
16,28,2026-06-29-07-51-05 +0000,bbc,Mum of newborn rescued from Venezuela rubble s...,https://www.bbc.co.uk/news/articles/clyw3rkj2p...
69,25,2026-06-28-23-33-42 +0000,nypost,NYPD commish stands with armed gay cops on sid...,https://nypost.com/2026/06/28/us-news/nypd-com...
80,25,2026-06-28-22-39-51 +0000,nypost,Video shows crocodile that killed Puerto Valla...,https://nypost.com/2026/06/28/us-news/video-sh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)