## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-07-45-13 +0000,bbc,Three dead after monster truck crashes into crowd,https://www.bbc.com/news/articles/czx2d54wwr4o...
1,2026-05-04-07-38-06 +0000,nyt,Canada Says Its Gold Is Traceable and Clean. S...,https://www.nytimes.com/2026/04/27/world/canad...
2,2026-05-04-07-30-39 +0000,nyt,Oil Prices Jump While Stock Futures Inch Up,https://www.nytimes.com/2026/05/03/business/oi...
3,2026-05-04-07-30-25 +0000,nyt,Tractor-Trailer and Light Post Damaged as Plan...,https://www.nytimes.com/2026/05/03/nyregion/ne...
4,2026-05-04-07-17-00 +0000,wsj,Treasury Yields Rise as Inflation Concerns Per...,https://www.wsj.com/articles/treasury-yields-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
36   trump     28
12     oil     12
47    iran     12
43  hormuz     11
53    will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,81
145,2026-05-03-16-49-30 +0000,cbc,Trump says operation will start Monday to help...,https://www.cbc.ca/news/world/cargo-ship-strai...,79
60,2026-05-04-00-12-00 +0000,wsj,Trump Says U.S. Will Guide Stranded Ships Thro...,https://www.wsj.com/world/middle-east/trump-sa...,78
117,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...,76
38,2026-05-04-02-10-15 +0000,nyt,Trump Says U.S. Will Help Stranded Ships Leave...,https://www.nytimes.com/2026/05/03/us/politics...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,81,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...
209,48,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
120,39,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
163,37,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...
65,30,2026-05-03-23-31-56 +0000,nypost,Federal Reserve official says Iran war limits ...,https://nypost.com/2026/05/03/business/federal...
18,30,2026-05-04-05-11-17 +0000,nypost,Jimmy Kimmel joked about ex-NYC Mayor Rudy Giu...,https://nypost.com/2026/05/04/us-news/jimmy-ki...
201,29,2026-05-03-09-13-54 +0000,bbc,Airlines can cancel flights in advance over fu...,https://www.bbc.com/news/articles/c794zd1vqn4o...
192,28,2026-05-03-10-00-00 +0000,latimes,"Barabak: Not too early, not too late. Here's t...",https://www.latimes.com/politics/story/2026-05...
93,26,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
135,24,2026-05-03-17-27-21 +0000,bbc,Two US service members reported missing in Mor...,https://www.bbc.com/news/articles/cn7prznmllko...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)