## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-18-14-22 +0000,nyt,What to Know About Elections in West Bengal an...,https://www.nytimes.com/2026/05/03/world/asia/...
1,2026-05-04-18-13-49 +0000,startribune,Live: Minnesota Senate voting on sweeping gun ...,https://www.startribune.com/live-minnesota-sen...
2,2026-05-04-18-11-01 +0000,wapo,School cellphone bans don’t affect test scores...,https://www.washingtonpost.com/education/2026/...
3,2026-05-04-18-09-29 +0000,nyt,Iran War Live Updates: Attacks in Gulf Threate...,https://www.nytimes.com/live/2026/05/04/world/...
4,2026-05-04-18-09-26 +0000,nyt,"Strikes in U.A.E., Oman and at Sea Strain Iran...",https://www.nytimes.com/2026/05/04/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2513/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
295   trump     24
26     iran     18
68   hormuz     12
67   strait     11
27      war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
152,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...,89
254,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...,85
236,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,80
155,2026-05-04-10-34-00 +0000,wsj,Trump Says U.S. Will Guide Stranded Ships Thro...,https://www.wsj.com/world/middle-east/trump-sa...,73
199,2026-05-04-02-10-15 +0000,nyt,Trump Says U.S. Will Help Stranded Ships Leave...,https://www.nytimes.com/2026/05/03/us/politics...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
152,89,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...
235,61,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
100,47,2026-05-04-15-10-57 +0000,nypost,Ex-NYC Mayor Rudy Giuliani remains hospitalize...,https://nypost.com/2026/05/04/us-news/ex-nyc-m...
147,47,2026-05-04-11-15-00 +0000,nypost,World Liberty Financial hits back at crypto bi...,https://nypost.com/2026/05/04/business/world-l...
257,37,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
25,36,2026-05-04-17-45-02 +0000,startribune,Supreme Court restores access to abortion pill...,https://www.startribune.com/supreme-court-rest...
6,36,2026-05-04-18-06-28 +0000,nypost,Judge apologizes to White House Correspondents...,https://nypost.com/2026/05/04/us-news/judge-ap...
54,29,2026-05-04-16-53-41 +0000,nypost,Possible cause revealed in ‘12- to 14-alarm’ w...,https://nypost.com/2026/05/04/us-news/possible...
172,28,2026-05-04-09-02-13 +0000,nypost,House Democrats add eight new battleground tar...,https://nypost.com/2026/05/04/us-news/house-de...
70,27,2026-05-04-16-24-50 +0000,bbc,Two killed and many injured after car driven i...,https://www.bbc.com/news/articles/ckgpzgxgz58o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)