## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-13-16-47-00 +0000,nyt,Celine Dion Begins Her Paris Comeback Concert Run,https://www.nytimes.com/2026/09/13/arts/music/...
1,2026-09-13-16-38-00 +0000,cbc,Will the U.S. midterm results affect Trump's t...,https://www.cbc.ca/news/politics/us-midterms-t...
2,2026-09-13-16-37-49 +0000,nyt,Obama Urges Democrats to Move A.I. Oversight t...,https://www.nytimes.com/2026/09/13/us/politics...
3,2026-09-13-16-36-39 +0000,nypost,Turkish Airlines flight ‘started to plummet’ a...,https://nypost.com/2026/09/13/world-news/turki...
4,2026-09-13-16-33-57 +0000,bbc,Russia struck train near Poland border shortly...,https://www.bbc.co.uk/news/articles/cy5zg41dkq...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2345/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
12       trump     23
143        new     12
68          ai     10
251       iran      9
59   wisconsin      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,76
26,2026-09-13-15-31-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...,70
42,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...,67
70,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...,56
7,2026-09-13-16-29-27 +0000,bbc,Trump downplays AI risks after dire expert war...,https://www.bbc.co.uk/news/articles/c7v48vp31m...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,76,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
26,63,2026-09-13-15-31-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
45,42,2026-09-13-13-55-08 +0000,nypost,Speaker Johnson says AI leaders must meet with...,https://nypost.com/2026/09/13/us-news/speaker-...
173,40,2026-09-12-20-51-49 +0000,nypost,Lindsay Clancy case eerily similar to bipolar ...,https://nypost.com/2026/09/12/us-news/lindsay-...
70,33,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...
73,31,2026-09-13-10-36-25 +0000,wapo,"Six dead, over 100 missing after Indonesian pa...",https://www.washingtonpost.com/world/2026/09/1...
205,28,2026-09-12-17-10-00 +0000,wsj,Larry Ellison Scraps Plan to Sell Up to $7.5 B...,https://www.wsj.com/business/larry-ellison-scr...
175,27,2026-09-12-20-41-12 +0000,nypost,"Iran joins Russia, China at BRICS conference c...",https://nypost.com/2026/09/12/us-news/iran-joi...
117,26,2026-09-13-08-00-00 +0000,cbc,Canada's oil windfall may yet wipe out its los...,https://www.cbc.ca/news/politics/canada-oil-pr...
3,24,2026-09-13-16-36-39 +0000,nypost,Turkish Airlines flight ‘started to plummet’ a...,https://nypost.com/2026/09/13/world-news/turki...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)