## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-05-41-00 +0000,wsj,Macro Backdrop Might Weigh on Two-Year U.S. Tr...,https://www.wsj.com/finance/macro-backdrop-mig...
1,2026-09-22-05-24-01 +0000,bbc,Rising fuel prices 'cost tow truck business £10k',https://www.bbc.co.uk/news/articles/cxp845vnpv...
2,2026-09-22-05-16-07 +0000,bbc,"Iran must stop arming Houthis in Yemen, G7 say...",https://www.bbc.co.uk/news/articles/cwm2qpmepm...
3,2026-09-22-05-05-41 +0000,bbc,Soaring fuel costs hit small businesses,https://www.bbc.co.uk/news/articles/c8qlwp7q96...
4,2026-09-22-05-04-56 +0000,bbc,Winter support planned for vulnerable residents,https://www.bbc.co.uk/news/articles/c3lyrpxeep...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
45   trump     51
48     new     21
476  house     19
370     ai     17
157  china     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
99,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...,145
163,2026-09-21-20-38-00 +0000,wsj,President Trump has discussed kicking journali...,https://www.wsj.com/politics/policy/trump-has-...,127
215,2026-09-21-18-31-17 +0000,nypost,Trump cuts ribbon on latest White House constr...,https://nypost.com/2026/09/21/us-news/trump-cu...,125
68,2026-09-22-00-16-06 +0000,bbc,"CNN, MS NOW and Politico file lawsuit against ...",https://www.bbc.co.uk/news/articles/cm0e32rwvr...,124
74,2026-09-22-00-00-00 +0000,wsj,When Bill Pulte examined the mortgages of Pres...,https://www.wsj.com/politics/policy/bill-pulte...,121

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
99,145,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...
228,86,2026-09-21-18-05-18 +0000,nypost,Illinois Gov. JB Pritzker says he’s lost 80 po...,https://nypost.com/2026/09/21/us-news/illinois...
294,75,2026-09-21-14-54-19 +0000,nypost,US pitches China on AI notification deal ahead...,https://nypost.com/2026/09/21/us-news/us-pitch...
170,69,2026-09-21-20-25-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
129,68,2026-09-21-21-34-32 +0000,bbc,"Paramount settles lawsuit with US states, clea...",https://www.bbc.co.uk/news/articles/cm4gjr1qep...
322,52,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
85,49,2026-09-21-23-26-57 +0000,chitri,Appeals court favors Trump-backed Missouri con...,https://www.chicagotribune.com/2026/09/21/trum...
116,48,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...
32,44,2026-09-22-02-15-15 +0000,nyt,Man Shot by ICE Agent Says His Car Was Struck ...,https://www.nytimes.com/2026/09/21/us/ice-shoo...
59,44,2026-09-22-00-45-00 +0000,nypost,California tech exec says she’s found 5 ‘Mr. R...,https://nypost.com/2026/09/21/us-news/brooke-l...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)