## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-03-02-48-04 +0000,wapo,"Kay Granger, first GOP woman from Texas to win...",https://www.washingtonpost.com/obituaries/2026...
1,2026-08-03-02-43-06 +0000,bbc,US and Japan jointly intervene to prop up yen ...,https://www.bbc.co.uk/news/articles/cglj1pr0wj...
2,2026-08-03-02-41-00 +0000,wsj,Politics May Be Behind Coordinated U.S.-Japan ...,https://www.wsj.com/finance/currencies/yen-wea...
3,2026-08-03-02-40-14 +0000,nyt,"20 Years After Its Own Outbreak, an Ugandan To...",https://www.nytimes.com/2026/07/26/world/afric...
4,2026-08-03-02-34-00 +0000,wsj,China Private Manufacturing Gauge Shows Weaker...,https://www.wsj.com/economy/china-private-manu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
211  trump     17
112   iran     15
43     new     14
275   deal     10
319     he      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
47,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...,71
143,2026-08-02-15-40-24 +0000,chitri,President Trump says he will order halt to Ira...,https://www.chicagotribune.com/2026/08/02/trum...,69
136,2026-08-02-16-00-00 +0000,wsj,Trump said he wants a Qatari-donated jet used ...,https://www.wsj.com/politics/national-security...,64
92,2026-08-02-19-02-00 +0000,wsj,"Sen. Bernie Moreno says his former son-in-law,...",https://www.wsj.com/politics/elections/domesti...,62
147,2026-08-02-15-27-49 +0000,nyt,"Trump Says He Canceled Strikes on Iran, Claimi...",https://www.nytimes.com/2026/08/02/world/middl...,61

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
47,71,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...
92,62,2026-08-02-19-02-00 +0000,wsj,"Sen. Bernie Moreno says his former son-in-law,...",https://www.wsj.com/politics/elections/domesti...
136,47,2026-08-02-16-00-00 +0000,wsj,Trump said he wants a Qatari-donated jet used ...,https://www.wsj.com/politics/national-security...
138,38,2026-08-02-15-50-59 +0000,bbc,At least 13 killed in Israeli strikes on Gaza ...,https://www.bbc.co.uk/news/articles/czjlvvkzj2...
38,36,2026-08-02-23-39-00 +0000,wsj,California Democrats endorse a proposed billio...,https://www.wsj.com/politics/policy/california...
205,35,2026-08-02-06-16-23 +0000,nypost,Socialist Spanish PM blasts Giorgia Meloni ove...,https://nypost.com/2026/08/02/world-news/spain...
197,31,2026-08-02-08-22-24 +0000,nypost,"Homemade bomb carried by woman kills 3, injure...",https://nypost.com/2026/08/02/world-news/russi...
142,30,2026-08-02-15-40-34 +0000,nypost,Horror moment 2 firefighting helicopters colli...,https://nypost.com/2026/08/02/world-news/horro...
78,28,2026-08-02-20-32-25 +0000,nyt,Canada’s WestJet Cancels Trips Amid Strike By ...,https://www.nytimes.com/2026/08/02/world/canad...
122,28,2026-08-02-17-00-00 +0000,wsj,Cori Bush is trying to overcome millions in sp...,https://www.wsj.com/politics/elections/cori-bu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)