## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-21-14-53-00 +0000,wsj,EBay to Cut 9% of Workforce in Latest Round of...,https://www.wsj.com/business/ebay-to-cut-9-of-...
1,2026-10-21-14-51-24 +0000,nyt,Alaska’s Journalists Join Forces to Cover the ...,https://www.nytimes.com/2026/10/21/business/me...
2,2026-10-21-14-50-05 +0000,bbc,Tory MP questions government advisor's positio...,https://www.bbc.co.uk/news/articles/cke8r0me3y...
3,2026-10-21-14-47-58 +0000,nypost,Neighbors race to save child dangling from 12t...,https://nypost.com/2026/10/21/world-news/neigh...
4,2026-10-21-14-47-00 +0000,wsj,President Trump said he is requiring companies...,https://www.wsj.com/politics/policy/trump-says...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2446/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
34        trump     46
60          new     25
117      russia     15
64   california     14
198     ukraine     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
91,2026-10-21-11-10-38 +0000,chitri,Russia releases detained American Stephen Hubb...,https://www.chicagotribune.com/2026/10/21/russ...,109
15,2026-10-21-14-27-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...,108
327,2026-10-20-19-40-00 +0000,wsj,Trump announced a new program that will pay pe...,https://www.wsj.com/politics/policy/trump-to-o...,107
362,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...,107
141,2026-10-21-09-03-22 +0000,nyt,Trump Approval Hits New Low Two Weeks Before M...,https://www.nytimes.com/2026/10/21/us/politics...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
91,109,2026-10-21-11-10-38 +0000,chitri,Russia releases detained American Stephen Hubb...,https://www.chicagotribune.com/2026/10/21/russ...
15,100,2026-10-21-14-27-00 +0000,wsj,New York Democrat Brad Lander said he was brie...,https://www.wsj.com/politics/congressional-can...
241,64,2026-10-20-22-42-43 +0000,nypost,SpaceX stock soars on blowout earnings that se...,https://nypost.com/2026/10/20/business/spacex-...
344,55,2026-10-20-19-01-56 +0000,cbc,No Canada-U.S. trade deal expected before Amer...,https://www.cbc.ca/news/politics/carney-trump-...
262,54,2026-10-20-21-57-00 +0000,wsj,National Democrats are making a million-dollar...,https://www.wsj.com/politics/elections/democra...
362,53,2026-10-20-17-38-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...
4,46,2026-10-21-14-47-00 +0000,wsj,President Trump said he is requiring companies...,https://www.wsj.com/politics/policy/trump-says...
236,45,2026-10-20-22-53-44 +0000,nypost,Elon Musk chose to throttle Ukraine’s access t...,https://nypost.com/2026/10/20/world-news/elon-...
311,44,2026-10-20-20-10-16 +0000,nypost,Woke French student mocked owners who lost sto...,https://nypost.com/2026/10/20/world-news/frenc...
113,43,2026-10-21-10-16-17 +0000,bbc,Inflation and government borrowing highest for...,https://www.bbc.co.uk/news/articles/c6gel2xv44...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)