## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-28-06-53-23 +0000,bbc,Israel elections: Arab parties could hold key ...,https://www.bbc.co.uk/news/articles/cjy561y4pl...
1,2026-10-28-06-51-00 +0000,wsj,"UBS Profit Climbs as Asia, Americas Growth Boo...",https://www.wsj.com/finance/banking/ubs-profit...
2,2026-10-28-06-47-00 +0000,wsj,Mercedes-Benz to Accelerate Efficiency Drive a...,https://www.wsj.com/business/mercedes-benz-to-...
3,2026-10-28-06-46-19 +0000,nyt,Rivals in Israel Election Strike Tone of Trium...,https://www.nytimes.com/live/2026/10/27/world/...
4,2026-10-28-06-43-14 +0000,nypost,"Great white shark thrashes, lunges at woman af...",https://nypost.com/2026/10/28/us-news/great-wh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2620/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
222     trump     31
28   election     30
0      israel     22
229       new     12
225      will     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
343,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...,101
32,2026-10-28-04-00-03 +0000,startribune,Exit polls suggest no clear winner in Israel's...,https://www.startribune.com/voters-in-israel-w...,99
177,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,98
42,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...,86
396,2026-10-27-08-25-46 +0000,nypost,Polls open in Israel for country’s first elect...,https://nypost.com/2026/10/27/world-news/elect...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
343,101,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...
42,86,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...
307,55,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
102,54,2026-10-27-23-40-43 +0000,nypost,Ex-FBI official weeps as she appears in court ...,https://nypost.com/2026/10/27/us-news/ex-fbi-o...
378,53,2026-10-27-10-00-00 +0000,wsj,Fed Chairman Kevin Warsh wants to stop preview...,https://www.wsj.com/economy/central-banking/ke...
389,51,2026-10-27-09-21-34 +0000,wsj,"Stock Market News, Oct. 27, 2026: Tech Stocks ...",https://www.wsj.com/livecoverage/stock-market-...
181,46,2026-10-27-20-00-31 +0000,nypost,White Bank of America exec claims he faced dis...,https://nypost.com/2026/10/27/business/white-b...
299,40,2026-10-27-14-18-59 +0000,nypost,Feds raid billionaire’s Beverly Hills mansion ...,https://nypost.com/2026/10/27/us-news/eric-swa...
0,39,2026-10-28-06-53-23 +0000,bbc,Israel elections: Arab parties could hold key ...,https://www.bbc.co.uk/news/articles/cjy561y4pl...
408,38,2026-10-27-06-59-20 +0000,nyt,Flurry of Diplomacy in Iran Amid Reports of U....,https://www.nytimes.com/2026/10/26/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)