## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-11-20-53-01 +0000,nyt,"In Maine Senate Race, Anxious Democrats Turn t...",https://www.nytimes.com/2026/10/11/us/politics...
1,2026-10-11-20-50-00 +0000,wsj,Opinion | Trump’s Diesel Insult to Lindsey Graham,https://www.wsj.com/opinion/trumps-diesel-insu...
2,2026-10-11-20-47-04 +0000,nypost,Three people shot in broad daylight in Los Ang...,https://nypost.com/2026/10/11/us-news/three-pe...
3,2026-10-11-20-46-00 +0000,wsj,Opinion | How to Make a Jihadist Martyr of Nid...,https://www.wsj.com/opinion/how-to-make-a-jiha...
4,2026-10-11-20-44-00 +0000,wsj,"Opinion | Democrats vs. Alaska, Again",https://www.wsj.com/opinion/alaska-anwr-drilli...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2339/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9      trump     31
295  airport     11
126    saudi     11
73    russia     11
72   ukraine     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
92,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...,82
91,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...,77
83,2026-10-11-14-39-06 +0000,nypost,"Russia, Ukraine reach energy cease-fire ‘effec...",https://nypost.com/2026/10/11/us-news/russia-u...,76
60,2026-10-11-17-09-00 +0000,wsj,Trump Pushes Russia-Ukraine Energy Ceasefire a...,https://www.wsj.com/world/trump-declares-a-rus...,72
72,2026-10-11-16-23-20 +0000,nypost,President Trump toys with renaming Atlantic an...,https://nypost.com/2026/10/11/us-news/presiden...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
92,82,2026-10-11-13-40-43 +0000,nypost,Trump warns US may hit Houthis after American ...,https://nypost.com/2026/10/11/us-news/presiden...
102,48,2026-10-11-12-15-59 +0000,chitri,Pope Leo XIV will undergo surgery to remove a ...,https://www.chicagotribune.com/2026/10/11/pope...
91,46,2026-10-11-13-51-39 +0000,cbc,Trump announces Russia-Ukraine 'energy ceasefi...,https://www.cbc.ca/news/world/kyiv-pushes-back...
191,44,2026-10-11-00-52-59 +0000,nypost,‘Tiger King’ star Carole Baskin tells Post tha...,https://nypost.com/2026/10/10/world-news/carol...
54,42,2026-10-11-17-39-00 +0000,wsj,The high price of oil as the midterms grow nea...,https://www.wsj.com/politics/policy/houthis-an...
50,34,2026-10-11-17-47-18 +0000,cbc,Children among at least 139 dead after migrant...,https://www.cbc.ca/news/world/migrant-boat-cap...
125,31,2026-10-11-10-00-14 +0000,chitri,A North Side race tests competing visions for ...,https://www.chicagotribune.com/2026/10/11/chic...
189,31,2026-10-11-01-08-07 +0000,wapo,"12 killed, hundreds injured in Saudi Arabia ai...",https://www.washingtonpost.com/world/2026/10/1...
22,29,2026-10-11-19-12-43 +0000,nypost,Horror as person dies after being pulled out t...,https://nypost.com/2026/10/11/us-news/horror-a...
98,28,2026-10-11-12-50-00 +0000,wsj,Justice Department Probes TV Networks Over Sus...,https://www.wsj.com/business/media/justice-dep...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)