## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-19-20-54 +0000,nypost,Unbelievable moment naked madman blasts flamet...,https://nypost.com/2026/08/27/us-news/unbeliev...
1,2026-08-27-19-18-31 +0000,nypost,Iran-Oman deal on Strait of Hormuz ‘doesn’t ma...,https://nypost.com/2026/08/27/us-news/iran-oma...
2,2026-08-27-19-18-16 +0000,nyt,"Live Updates: Rescuers Scour Remote Valleys, a...",https://www.nytimes.com/live/2026/08/27/world/...
3,2026-08-27-19-18-14 +0000,nypost,Trump admin set to target George Soros nonprof...,https://nypost.com/2026/08/27/business/trump-a...
4,2026-08-27-19-18-14 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/08/27/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2320/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
17        trump     52
87        nepal     26
68          new     19
216  california     18
64         lake     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
391,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...,138
67,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...,137
53,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...,135
26,2026-08-27-18-48-27 +0000,wapo,Trump signs order renaming Lake Ontario as Lak...,https://www.washingtonpost.com/politics/2026/0...,132
16,2026-08-27-19-00-07 +0000,startribune,Trump signs order renaming Lake Ontario as 'La...,https://www.startribune.com/trump-signs-order-...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
391,138,2026-08-26-20-59-13 +0000,nyt,Canadians Stand Their Ground Amid New Trump Ta...,https://www.nytimes.com/2026/08/26/world/canad...
53,83,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...
396,80,2026-08-26-20-53-00 +0000,wsj,"Hundreds Missing, 157 Dead, as Likely Ice-Rock...",https://www.wsj.com/world/asia/foreign-tourist...
145,65,2026-08-27-14-51-00 +0000,wsj,California has made it easier to file civil cl...,https://www.wsj.com/politics/policy/california...
59,60,2026-08-27-17-46-21 +0000,bbc,"Jury deliberating in trial of Lindsay Clancy, ...",https://www.bbc.co.uk/news/articles/c33keeyyv7...
352,59,2026-08-26-22-49-36 +0000,nyt,Meta to Pay Up to $17.1 Billion in Landmark Se...,https://www.nytimes.com/2026/08/26/technology/...
156,57,2026-08-27-14-29-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
361,49,2026-08-26-22-10-00 +0000,wsj,The surprise visit by the director of the Cent...,https://www.wsj.com/politics/policy/cia-chiefs...
258,49,2026-08-27-09-30-00 +0000,wsj,The selloff in U.S. Treasurys has captured glo...,https://www.wsj.com/economy/global/think-treas...
167,45,2026-08-27-14-11-08 +0000,nypost,"Ratko Mladic, ruthless ex-Bosnian Serb war cri...",https://nypost.com/2026/08/27/world-news/ratko...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)