## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-15-23-52-00 +0000,wsj,"Oil Prices, Fed on Bank Indonesia’s Radar Ahea...",https://www.wsj.com/world/asia/oil-prices-fed-...
1,2026-10-15-23-46-06 +0000,startribune,5 people believed dead following shooting at O...,https://www.startribune.com/police-respond-to-...
2,2026-10-15-23-43-34 +0000,nyt,"Katie Zacharia Admits Failing Bar, but Defends...",https://www.nytimes.com/2026/10/15/us/katie-za...
3,2026-10-15-23-41-04 +0000,nyt,Here’s what to know.,https://www.nytimes.com/live/2026/10/15/us/ben...
4,2026-10-15-23-41-02 +0000,nyt,Paxton Partied in Dubai With Fugitives Charged...,https://www.nytimes.com/2026/10/15/us/paxton-d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2601/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
53     trump     36
72       new     28
57   ukraine     21
473       ai     13
15    school     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
75,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...,181
244,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...,126
101,2026-10-15-20-46-18 +0000,chitri,Ukraine abandons truce and attacks Russian oil...,https://www.chicagotribune.com/2026/10/15/ukra...,111
127,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...,104
247,2026-10-15-14-25-16 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/15/us-news/new-whit...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
75,181,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...
127,104,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...
376,75,2026-10-15-03-25-00 +0000,wsj,Texas Democrat and Senate hopeful James Talari...,https://www.wsj.com/politics/elections/five-ta...
239,66,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...
244,53,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...
348,46,2026-10-15-08-46-43 +0000,cbc,"School roof collapses in Pakistan, killing at ...",https://www.cbc.ca/news/world/school-pakistan-...
248,43,2026-10-15-14-19-00 +0000,wsj,Florida’s Democratic Senate nominee Angie Nixo...,https://www.wsj.com/politics/elections/the-int...
390,42,2026-10-15-01-00-00 +0000,wsj,Money from Tether flowed to Bo Hines’s company...,https://www.wsj.com/politics/policy/crypto-law...
52,42,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
42,40,2026-10-15-22-17-23 +0000,nypost,NYC mom who told 911 she killed 5-year-old dau...,https://nypost.com/2026/10/15/us-news/francis-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)