## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-11-08-54-20 +0000,bbc,Five dead and dozens injured in coach crash in...,https://www.bbc.co.uk/news/articles/cx2z70xr0y...
1,2026-09-11-08-45-51 +0000,nypost,Ex-Venezuelan first lady Cilia Flores seeks re...,https://nypost.com/2026/09/11/us-news/venezuel...
2,2026-09-11-08-44-45 +0000,nypost,Georgia ‘twisted twin’ who killed mom with sis...,https://nypost.com/2026/09/11/us-news/georgia-...
3,2026-09-11-08-40-00 +0000,wsj,"Stock Futures Nudge Up, Yields Slip, But Marke...",https://www.wsj.com/finance/stocks/stock-futur...
4,2026-09-11-08-39-53 +0000,nypost,Trump list of US-designated ‘foreign terrorist...,https://nypost.com/2026/09/11/us-news/trump-li...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2320/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
42        trump     65
92   convention     27
119         new     26
101          ai     21
297         gop     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
70,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...,191
60,2026-09-11-02-51-48 +0000,nypost,Trump leads GOP midterm convention attendees i...,https://nypost.com/2026/09/10/us-news/trump-le...,155
203,2026-09-10-20-26-00 +0000,wsj,President Trump offered a pricey promise in hi...,https://www.wsj.com/politics/policy/5-000-chec...,151
42,2026-09-11-05-02-20 +0000,nypost,JD Vance steals 2028 show at GOP convention — ...,https://nypost.com/2026/09/11/us-news/jd-vance...,145
209,2026-09-10-20-20-53 +0000,wapo,"Democrats play up Trump investigations, Epstei...",https://www.washingtonpost.com/politics/2026/0...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
70,191,2026-09-11-02-09-57 +0000,nyt,"“Under Donald Trump’s leadership, we’ve create...",https://www.nytimes.com/live/2026/09/10/us/tru...
55,115,2026-09-11-03-21-00 +0000,wsj,JD Vance delivered a future-looking speech on ...,https://www.wsj.com/politics/elections/key-tak...
72,91,2026-09-11-02-08-00 +0000,wsj,"After years of inaction, Congress is suddenly ...",https://www.wsj.com/politics/policy/congress-i...
74,84,2026-09-11-02-05-07 +0000,nyt,“When Medicaid programs for homeless or expect...,https://www.nytimes.com/live/2026/09/10/us/tru...
348,67,2026-09-10-14-00-00 +0000,wsj,Home sales in August fell to their lowest leve...,https://www.wsj.com/economy/housing/home-sales...
80,50,2026-09-11-01-55-12 +0000,nyt,“Americans who were finishing school suddenly ...,https://www.nytimes.com/live/2026/09/10/us/tru...
254,49,2026-09-10-18-43-01 +0000,chitri,Jimmy Kimmel says interview with James Talaric...,https://www.chicagotribune.com/2026/09/10/jimm...
321,46,2026-09-10-16-00-20 +0000,nypost,Teen prison guard who had fling with killer is...,https://nypost.com/2026/09/10/world-news/saman...
274,46,2026-09-10-17-57-02 +0000,nyt,Supreme Court Again Blocks Republican-Backed M...,https://www.nytimes.com/2026/09/10/us/politics...
81,44,2026-09-11-01-55-05 +0000,nypost,Charlie Kirk supporters vow to ‘continue what ...,https://nypost.com/2026/09/10/us-news/charlie-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)