## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-07-12-00-25 +0000,nypost,Fox partners with Kalshi to add sponsored ‘cro...,https://nypost.com/2026/04/07/business/fox-par...
1,2026-04-07-11-56-35 +0000,bbc,One dead as train travelling 99mph collides wi...,https://www.bbc.com/news/articles/cq590egv9vzo...
2,2026-04-07-11-54-44 +0000,bbc,Greens promise rent controls and £1 bus fares ...,https://www.bbc.com/news/articles/cwydw8pk39ro...
3,2026-04-07-11-54-16 +0000,nyt,Iran War Live Updates: Trump’s Deadline Draws ...,https://www.nytimes.com/live/2026/04/07/world/...
4,2026-04-07-11-54-14 +0000,nyt,Trump Says Iran Proposal Isn’t Enough to Stop ...,https://www.nytimes.com/2026/04/06/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
30     trump     61
26      iran     53
27       war     26
31  deadline     23
97       new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-04-07-11-00-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...,232
3,2026-04-07-11-54-16 +0000,nyt,Iran War Live Updates: Trump’s Deadline Draws ...,https://www.nytimes.com/live/2026/04/07/world/...,178
185,2026-04-06-21-55-50 +0000,bbc,Trump threatens to take out Iran in 'one night...,https://www.bbc.com/news/articles/cqj8ep9w1pno...,177
208,2026-04-06-21-03-16 +0000,wapo,Trump threatens new rampage as Iran deal deadl...,https://www.washingtonpost.com/national-securi...,175
84,2026-04-07-08-59-53 +0000,cbc,Iran calls for human chains around power plant...,https://www.cbc.ca/news/world/trump-iran-war-i...,173

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,232,2026-04-07-11-00-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...
184,77,2026-04-06-22-02-35 +0000,nypost,Lefty ‘anti-war’ candidate Graham Platner once...,https://nypost.com/2026/04/06/us-news/anti-war...
162,55,2026-04-06-23-24-00 +0000,wsj,A new Goldman Sachs report analyzing past tech...,https://www.wsj.com/economy/jobs/ai-displaced-...
262,50,2026-04-06-17-24-15 +0000,nypost,Dramatic moment Israeli woman knocked to the g...,https://nypost.com/2026/04/06/world-news/video...
113,40,2026-04-07-05-09-42 +0000,nypost,Warship based out of San Diego will play criti...,https://nypost.com/2026/04/07/us-news/san-dieg...
296,40,2026-04-06-14-23-41 +0000,nypost,Supreme Court sets stage for DOJ to toss crimi...,https://nypost.com/2026/04/06/us-news/supreme-...
84,36,2026-04-07-08-59-53 +0000,cbc,Iran calls for human chains around power plant...,https://www.cbc.ca/news/world/trump-iran-war-i...
274,34,2026-04-06-16-29-51 +0000,nypost,"Trump, first lady Melania tell children of Ira...",https://nypost.com/2026/04/06/us-news/trump-fi...
90,34,2026-04-07-08-15-00 +0000,wsj,China Caps Rise in Fuel Prices as Middle East ...,https://www.wsj.com/finance/commodities-future...
269,32,2026-04-06-16-48-58 +0000,nypost,Disgraced GOP Rep. Tony Gonzales sent lewd tex...,https://nypost.com/2026/04/06/us-news/disgrace...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)