## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-04-01-12-46 +0000,nypost,IG report into ex-Labor Secretary Chavez-DeRem...,https://nypost.com/2026/09/03/us-news/ig-repor...
1,2026-09-04-01-10-44 +0000,cbc,Canadians should prepare for a 5 C hotter futu...,https://www.cbc.ca/news/politics/climate-chang...
2,2026-09-04-01-04-24 +0000,bbc,Volkswagen board approves plan to cut another ...,https://www.bbc.co.uk/news/articles/cx2z0kvy4n...
3,2026-09-04-01-00-00 +0000,wsj,Why Big Oil Is Wary of Trump’s Foray Into Vene...,https://www.wsj.com/business/energy-oil/why-bi...
4,2026-09-04-01-00-00 +0000,wsj,The Bahrain Grand Prix…in Malaysia? War Is Rui...,https://www.wsj.com/world/middle-east/the-bahr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2635/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
34    trump     52
75    court     18
77   clancy     18
562     new     18
217   house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
75,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...,151
425,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,144
366,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,121
134,2026-09-03-20-33-39 +0000,chitri,President Trump again appeals to Supreme Court...,https://www.chicagotribune.com/2026/09/03/trum...,119
88,2026-09-03-22-06-54 +0000,chitri,Missouri’s highest court blocks Trump-backed U...,https://www.chicagotribune.com/2026/09/03/miss...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
75,151,2026-09-03-22-26-00 +0000,wsj,The Trump administration asked the Supreme Cou...,https://www.wsj.com/politics/policy/trump-admi...
138,82,2026-09-03-20-22-43 +0000,wapo,Vance says he doesn’t know when Iran conflict ...,https://www.washingtonpost.com/politics/2026/0...
100,72,2026-09-03-21-45-00 +0000,wsj,The odds of an interest-rate hike are now a co...,https://www.wsj.com/politics/policy/fed-rate-w...
7,70,2026-09-04-00-55-45 +0000,bbc,Watch: Inside court as Lindsay Clancy's lawyer...,https://www.bbc.co.uk/news/videos/c36l7jwjg1no...
228,69,2026-09-03-17-01-00 +0000,wsj,Billionaire Leon Black won’t appear before the...,https://www.wsj.com/politics/policy/leon-black...
381,59,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...
213,52,2026-09-03-17-43-33 +0000,latimes,"Fox News cuts ties with Maria Bartiromo, weeks...",https://www.latimes.com/entertainment-arts/bus...
19,47,2026-09-04-00-34-00 +0000,wsj,Missouri’s Supreme Court ruled Thursday the st...,https://www.wsj.com/politics/policy/missouri-s...
242,44,2026-09-03-16-32-05 +0000,bbc,Nvidia strikes $12.9bn deal to buy AI platform...,https://www.bbc.co.uk/news/articles/cr4vnr5g1k...
237,43,2026-09-03-16-39-11 +0000,latimes,Trump targets private school tax-exempt status...,https://www.latimes.com/world-nation/story/202...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)