## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-19-16-43 +0000,nypost,2 young kids killed on doomed Sunday boat trip...,https://nypost.com/2026/07/21/us-news/2-kids-k...
1,2026-07-21-19-15-19 +0000,nyt,Senate Panel Advances Jay Clayton as Next Spy ...,https://www.nytimes.com/2026/07/21/us/politics...
2,2026-07-21-19-13-49 +0000,chitri,Aldermen sign ‘ICE Out’ pledge demanding offic...,https://www.chicagotribune.com/2026/07/21/chic...
3,2026-07-21-19-12-29 +0000,nyt,Netanyahu Ad Uses a Questionable Tactic Agains...,https://www.nytimes.com/2026/07/21/world/middl...
4,2026-07-21-19-12-00 +0000,wsj,Canada’s Carney Says Trump Agrees to Talks to ...,https://www.wsj.com/world/americas/canadas-car...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
43     trump     44
47       new     35
60      iran     30
146  burnham     22
319     will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
213,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...,125
400,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...,120
370,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,114
137,2026-07-21-15-40-27 +0000,nypost,"US, Mexico resume USMCA trade talks as Trump s...",https://nypost.com/2026/07/21/world-news/us-me...,110
4,2026-07-21-19-12-00 +0000,wsj,Canada’s Carney Says Trump Agrees to Talks to ...,https://www.wsj.com/world/americas/canadas-car...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
213,125,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...
93,104,2026-07-21-17-00-03 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
370,70,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
301,62,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
343,46,2026-07-20-22-54-32 +0000,nypost,Judge approves Anthropic’s $1.5B settlement of...,https://nypost.com/2026/07/20/business/anthrop...
37,44,2026-07-21-18-17-44 +0000,latimes,California wouldn't be the right place to laun...,https://www.latimes.com/business/story/2026-07...
400,41,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...
268,37,2026-07-21-09-08-00 +0000,wsj,SBI Funds Management Shares Rise After India’s...,https://www.wsj.com/finance/investing/sbi-fund...
108,37,2026-07-21-16-30-00 +0000,missionlocal,After a family was killed at a West Portal bus...,https://missionlocal.org/2026/07/san-francisco...
304,36,2026-07-21-02-16-05 +0000,bbc,'Anti-ICE' army veteran started fire outside M...,https://www.bbc.co.uk/news/articles/c1m1rr90dz...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)