## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-11-07-11-05 +0000,nypost,Iran’s missing Supreme Leader Mojtaba Khamenei...,https://nypost.com/2026/04/11/world-news/irans...
1,2026-04-11-07-02-04 +0000,nypost,Minnesota pilot’s wife Jennifer Lieber sentenc...,https://nypost.com/2026/04/11/us-news/minnesot...
2,2026-04-11-06-53-48 +0000,nyt,"Iranian Delegation Arrives at Peace Talks, Wit...",https://www.nytimes.com/live/2026/04/10/world/...
3,2026-04-11-06-50-24 +0000,nypost,Vance arrives in Pakistan for talks with Irani...,https://nypost.com/2026/04/11/us-news/jd-vance...
4,2026-04-11-06-27-09 +0000,nypost,DHS orders furloughed staff back to work as go...,https://nypost.com/2026/04/11/us-news/dhs-orde...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     56
231   trump     41
197     war     26
30    talks     22
783  prices     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
263,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,160
244,2026-04-10-15-28-35 +0000,nypost,Trump tells The Post he’s preparing military i...,https://nypost.com/2026/04/10/us-news/trump-te...,155
140,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...,148
44,2026-04-11-01-21-53 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,144
112,2026-04-10-21-33-14 +0000,nyt,Potential Democratic 2028 Candidates Condemn T...,https://www.nytimes.com/2026/04/10/us/politics...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
263,160,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...
27,98,2026-04-11-03-49-39 +0000,nypost,California Rep. Eric Swalwell slams sexual mis...,https://nypost.com/2026/04/10/us-news/californ...
140,92,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...
3,53,2026-04-11-06-50-24 +0000,nypost,Vance arrives in Pakistan for talks with Irani...,https://nypost.com/2026/04/11/us-news/jd-vance...
102,42,2026-04-10-21-54-09 +0000,cbc,Police arrest suspect after Molotov cocktail t...,https://www.cbc.ca/news/world/altman-home-molo...
230,39,2026-04-10-16-08-45 +0000,nypost,Kamala Harris said she ‘might’ run for preside...,https://nypost.com/2026/04/10/us-news/kamala-h...
68,37,2026-04-11-00-08-03 +0000,nypost,"Artemis II successfully splashes down, complet...",https://nypost.com/2026/04/10/us-news/artemis-...
73,35,2026-04-10-23-43-57 +0000,nypost,Nancy Pelosi told Eric Swalwell to drop out of...,https://nypost.com/2026/04/10/us-news/eric-swa...
177,34,2026-04-10-18-44-12 +0000,nypost,Israel continues to attack Lebanon ‘non-stop’ ...,https://nypost.com/2026/04/10/world-news/israe...
287,31,2026-04-10-10-36-34 +0000,nyt,Xi Meets Taiwan Opposition Leader for First Ti...,https://www.nytimes.com/2026/04/10/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)