## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-23-03-52 +0000,bbc,Trump signs order to limit childhood vaccines ...,https://www.bbc.co.uk/news/articles/ce3q5vl581...
1,2026-08-10-23-00-36 +0000,nypost,Famed California bars forced to boot draconian...,https://nypost.com/2026/08/10/us-news/san-fran...
2,2026-08-10-22-57-18 +0000,nyt,Man in Custody Over Bomb Threat at U.S. Consul...,https://www.nytimes.com/2026/08/10/world/ameri...
3,2026-08-10-22-56-05 +0000,nyt,Live Updates: Powerful 7.4 Earthquake Strikes ...,https://www.nytimes.com/live/2026/08/10/world/...
4,2026-08-10-22-56-02 +0000,nyt,Here Is Where Colombia’s Quake Hit Hardest,https://www.nytimes.com/2026/08/10/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2656/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     41
120    new     20
195   race     15
48    iran     14
110     ai     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
174,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...,105
327,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...,97
197,2026-08-10-15-18-28 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,94
344,2026-08-09-23-19-35 +0000,wapo,Trump picks longtime aide Will Scharf as new t...,https://www.washingtonpost.com/politics/2026/0...,92
145,2026-08-10-18-14-49 +0000,nypost,Iran’s ‘misery’ index hits record high — and a...,https://nypost.com/2026/08/10/world-news/irans...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
174,105,2026-08-10-16-57-19 +0000,nypost,Trump responds to Iran’s outlandish demands to...,https://nypost.com/2026/08/10/us-news/trump-re...
265,71,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...
327,56,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...
51,49,2026-08-10-21-41-28 +0000,nypost,DSA darling Francesca Hong doesn’t just want t...,https://nypost.com/2026/08/10/us-news/dsa-darl...
204,45,2026-08-10-14-55-02 +0000,nypost,Massive 7.4-magnitude earthquake strikes Colom...,https://nypost.com/2026/08/10/world-news/massi...
172,43,2026-08-10-16-59-59 +0000,nypost,OpenAI hits pause on new bot testing over ‘cri...,https://nypost.com/2026/08/10/business/openai-...
15,41,2026-08-10-22-30-01 +0000,startribune,Trump signs order calling for spacing out chil...,https://www.startribune.com/trump-to-sign-exec...
323,38,2026-08-10-02-35-07 +0000,nypost,Sudden death of California law student studyin...,https://nypost.com/2026/08/09/world-news/death...
170,38,2026-08-10-17-00-00 +0000,startribune,"In these Minnesota Senate seats, Tuesday’s pri...",https://www.startribune.com/mn-senate-races-el...
134,34,2026-08-10-18-49-02 +0000,nypost,Fauci privately warned of miscarriage risk lin...,https://nypost.com/2026/08/10/us-news/fauci-wa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)