## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-10-48-39 +0000,nyt,"Russia Bombards Kyiv Soon After Witkoff, Kushn...",https://www.nytimes.com/2026/09/08/world/europ...
1,2026-09-08-10-48-28 +0000,nyt,UK Set to Impose Sanctions on Israeli Settleme...,https://www.nytimes.com/2026/09/08/world/europ...
2,2026-09-08-10-46-00 +0000,wsj,Three Numbers That Show Just How Big China’s E...,https://www.wsj.com/economy/trade/three-number...
3,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
4,2026-09-08-10-41-42 +0000,cbc,Iran-backed Houthis attack Saudi oil facilitie...,https://www.cbc.ca/news/world/saudi-houthi-att...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
182    new     25
49   trump     20
328  plane     13
35     oil     11
45   trade     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...,121
268,2026-09-07-13-26-01 +0000,nyt,Trump Posts Map Suggesting New Mexico Be Renam...,https://www.nytimes.com/2026/09/07/us/politics...,87
112,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...,64
239,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...,63
197,2026-09-07-17-57-00 +0000,wapo,Trump suggests renaming New Mexico amid torren...,https://www.washingtonpost.com/politics/2026/0...,61

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,121,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
239,63,2026-09-07-15-14-00 +0000,wsj,Oil Extends Gains on Middle East Attacks; U.S....,https://www.wsj.com/finance/commodities-future...
42,55,2026-09-08-09-31-26 +0000,bbc,Five killed in Miami plane crash were in two v...,https://www.bbc.co.uk/news/articles/ce8e32n8ep...
242,43,2026-09-07-15-03-22 +0000,chitri,AfD party’s landslide win in eastern Germany t...,https://www.chicagotribune.com/2026/09/07/afd-...
87,41,2026-09-08-07-04-17 +0000,bbc,UK government expected to announce restriction...,https://www.bbc.co.uk/news/articles/c4grdjnle2...
20,40,2026-09-08-10-00-00 +0000,nypost,Pete Davidson was a kid when he lost his dad o...,https://nypost.com/2026/09/08/entertainment/pe...
3,35,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
236,32,2026-09-07-15-23-27 +0000,cbc,No talks scheduled as Canada's counter-tariffs...,https://www.cbc.ca/news/politics/no-talks-sche...
157,32,2026-09-07-21-59-12 +0000,nypost,Mainstream TV vague about airing first-ever GO...,https://nypost.com/2026/09/07/us-news/tv-netwo...
128,29,2026-09-08-01-47-07 +0000,nypost,Wild dashcam video shows crossing guard shield...,https://nypost.com/2026/09/07/us-news/wild-das...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)