## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-10-19-16-05 +0000,nyt,Britain’s Electorate Is ‘Splintering.’ Can Its...,https://www.nytimes.com/2026/05/09/world/europ...
1,2026-05-10-19-11-13 +0000,nypost,Ohio gov candidate Vivek Ramaswamy sounds alar...,https://nypost.com/2026/05/10/us-news/ohio-gov...
2,2026-05-10-19-09-51 +0000,nyt,"Fearing an All-Republican Governor’s Race, Dem...",https://www.nytimes.com/2026/05/10/us/californ...
3,2026-05-10-19-08-42 +0000,nypost,"Trump admin open to pausing gas tax, energy se...",https://nypost.com/2026/05/10/us-news/trump-ad...
4,2026-05-10-19-08-35 +0000,nyt,How Pope Leo Is Shaping the U.S. Church,https://www.nytimes.com/2026/05/10/us/pope-leo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2581/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
31        trump     13
69         iran     11
30   california      8
111        ship      8
108  hantavirus      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
79,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...,61
7,2026-05-10-18-51-29 +0000,nypost,Trump responds with warning after Iran refuses...,https://nypost.com/2026/05/10/us-news/trump-re...,60
10,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...,46
164,2026-05-09-22-22-08 +0000,nypost,Trump waits for answer from Iran on peace prop...,https://nypost.com/2026/05/09/world-news/trump...,43
134,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...,41

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
79,61,2026-05-10-13-12-05 +0000,nypost,Iran tests cease-fire yet again with drone str...,https://nypost.com/2026/05/10/world-news/iran-...
10,38,2026-05-10-18-47-00 +0000,nypost,British army drops paratroopers onto remote At...,https://nypost.com/2026/05/10/world-news/briti...
154,36,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
53,34,2026-05-10-15-32-42 +0000,nypost,Kristin Smart’s remains not found at house bel...,https://nypost.com/2026/05/10/us-news/kristin-...
2,32,2026-05-10-19-09-51 +0000,nyt,"Fearing an All-Republican Governor’s Race, Dem...",https://www.nytimes.com/2026/05/10/us/californ...
169,32,2026-05-09-21-21-22 +0000,nypost,Vladimir Putin suggests war in Ukraine is ‘com...,https://nypost.com/2026/05/09/world-news/vladi...
7,31,2026-05-10-18-51-29 +0000,nypost,Trump responds with warning after Iran refuses...,https://nypost.com/2026/05/10/us-news/trump-re...
96,28,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...
106,26,2026-05-10-10-06-32 +0000,nypost,NYPD captain’s transfer after viral rant bashi...,https://nypost.com/2026/05/10/us-news/nypd-cap...
102,23,2026-05-10-10-35-13 +0000,nyt,"Punch, the Lonely Monkey Who Drew Crowds to a ...",https://www.nytimes.com/2026/05/09/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)