## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-10-53-08 +0000,nypost,2 giant pandas set off to Atlanta zoo from Chi...,https://nypost.com/2026/09/27/us-news/atlanta-...
1,2026-09-27-10-53-06 +0000,startribune,Gophers upset Washington: Defense wreaks havoc...,https://www.startribune.com/minnesota-gophers-...
2,2026-09-27-10-49-24 +0000,nyt,"UK Deploys Bomb Squad Near R.A.F. Fairford, Ai...",https://www.nytimes.com/2026/09/27/world/europ...
3,2026-09-27-10-05-37 +0000,bbc,Burnham proposes NHS-style social care system ...,https://www.bbc.co.uk/news/articles/crwyzd3gv5...
4,2026-09-27-10-01-35 +0000,cbc,At least 27 people dead after two separate mas...,https://www.cbc.ca/news/world/south-africa-sho...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7    trump     30
247    new     14
219  house     10
91     war     10
41    mass      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-09-27-00-52-12 +0000,nypost,Trump’s new superintelligence czar: Here’s who...,https://nypost.com/2026/09/26/us-news/trumps-n...,80
162,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...,78
116,2026-09-26-19-16-14 +0000,bbc,White House bars CNN from travelling with Trum...,https://www.bbc.co.uk/news/articles/cxq633770y...,70
165,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...,65
163,2026-09-26-14-16-46 +0000,nyt,White House Blocks CNN From Covering Trump’s T...,https://www.nytimes.com/2026/09/25/business/me...,61

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,80,2026-09-27-00-52-12 +0000,nypost,Trump’s new superintelligence czar: Here’s who...,https://nypost.com/2026/09/26/us-news/trumps-n...
162,48,2026-09-26-14-17-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
160,43,2026-09-26-14-24-32 +0000,nypost,Russian attacks kill 4 across Ukraine days aft...,https://nypost.com/2026/09/26/world-news/russi...
164,39,2026-09-26-14-05-01 +0000,cbc,Hundreds of thousands turn out for Pope Leo al...,https://www.cbc.ca/news/world/pope-leo-parade-...
39,37,2026-09-27-08-09-32 +0000,nypost,Long Island swimmer vanishes in ocean off Fire...,https://nypost.com/2026/09/27/us-news/long-isl...
38,36,2026-09-27-08-13-12 +0000,nypost,UK police evacuate homes near air base used by...,https://nypost.com/2026/09/27/world-news/uk-po...
106,33,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
165,30,2026-09-26-14-00-00 +0000,wsj,The Supreme Court on Friday allowed the federa...,https://www.wsj.com/politics/policy/how-the-tr...
4,29,2026-09-27-10-01-35 +0000,cbc,At least 27 people dead after two separate mas...,https://www.cbc.ca/news/world/south-africa-sho...
30,29,2026-09-27-09-01-11 +0000,nyt,White House Claim of Finding $250 Billion in F...,https://www.nytimes.com/2026/09/27/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)