## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-11-04-25-12 +0000,nypost,"11 injured, 1 killed in multi-vehicle pileup i...",https://nypost.com/2026/03/11/us-news/11-injur...
1,2026-03-11-04-18-59 +0000,startribune,"Live: After quiet Tuesday, Vikings could jump ...",https://www.startribune.com/minnesota-vikings-...
2,2026-03-11-04-18-32 +0000,nypost,Mayor Karen Bass beefs up LAPD presence in DTL...,https://nypost.com/2026/03/11/us-news/karen-ba...
3,2026-03-11-04-17-34 +0000,nyt,New Iranian Leader Was Wounded Early in the Wa...,https://www.nytimes.com/2026/03/11/world/middl...
4,2026-03-11-04-14-40 +0000,bbc,Member of Iranian football delegation granted ...,https://www.bbc.com/news/articles/c93j2492d0do...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
78    iran     66
36     war     50
102    oil     31
87   trump     29
30     new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
33,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...,224
9,2026-03-11-03-53-31 +0000,nypost,California college groups back U.S. and Israel...,https://nypost.com/2026/03/10/us-news/californ...,207
55,2026-03-11-01-00-00 +0000,wsj,Trump’s suggestions that the war with Iran mig...,https://www.wsj.com/world/middle-east/trump-sa...,182
153,2026-03-10-20-23-00 +0000,wsj,"As Iran War Pushes Up Oil Prices, Putin Can Ba...",https://www.wsj.com/world/russia/as-iran-war-p...,180
332,2026-03-10-09-59-46 +0000,nyt,China Stockpiled More Oil Before War Broke Out...,https://www.nytimes.com/2026/03/10/business/ch...,170

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
33,224,2026-03-11-02-00-00 +0000,wsj,Iran is exporting more oil through the Strait ...,https://www.wsj.com/world/middle-east/irans-co...
3,67,2026-03-11-04-17-34 +0000,nyt,New Iranian Leader Was Wounded Early in the Wa...,https://www.nytimes.com/2026/03/11/world/middl...
143,66,2026-03-10-20-44-38 +0000,nyt,Democrats Sued to Find Out Whether Trump Will ...,https://www.nytimes.com/2026/03/10/us/politics...
104,53,2026-03-10-22-24-14 +0000,nypost,GOP gubernatorial hopeful Steve Hilton issues ...,https://nypost.com/2026/03/10/us-news/steve-hi...
344,45,2026-03-10-09-16-08 +0000,nypost,Five members of Iranian women’s soccer team gr...,https://nypost.com/2026/03/10/world-news/austr...
303,39,2026-03-10-11-43-50 +0000,cbc,"Dozens of Haitian civilians killed by police, ...",https://www.cbc.ca/news/world/haiti-drones-hum...
101,39,2026-03-10-22-31-00 +0000,wsj,OpenAI Faces Lawsuit Over Safety Protocols Ahe...,https://www.wsj.com/tech/openai-faces-lawsuit-...
210,38,2026-03-10-17-55-14 +0000,nypost,Diesel prices are rising even faster than gas ...,https://nypost.com/2026/03/10/business/diesel-...
63,34,2026-03-11-00-28-30 +0000,nypost,Georgia special election to fill House seat va...,https://nypost.com/2026/03/10/us-news/georgia-...
293,31,2026-03-10-12-54-18 +0000,latimes,Hegseth threatens 'most intense day of strikes...,https://www.latimes.com/world-nation/story/202...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)