## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-06-15-02-08 +0000,nypost,Nearly 80 people fall ill in suspected norovir...,https://nypost.com/2026/03/06/world-news/nearl...
1,2026-03-06-15-02-00 +0000,wsj,Switzerland to Buy Fewer U.S.-Made F-35 Fighte...,https://www.wsj.com/business/switzerland-to-bu...
2,2026-03-06-15-01-00 +0000,wsj,"The U.S. lost 92,000 jobs in February, the Lab...",https://www.wsj.com/economy/jobs/february-jobs...
3,2026-03-06-15-00-26 +0000,bbc,Emirates resumes some Dubai flights – what's t...,https://www.bbc.com/news/articles/c4ge52x4w37o...
4,2026-03-06-15-00-00 +0000,wsj,The Trillions of Dollars of U.S. Investment at...,https://www.wsj.com/business/the-trillions-of-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2533/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
70    iran     73
116  trump     57
538    war     32
230   noem     22
60     new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
175,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...,233
248,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...,205
271,2026-03-05-22-56-23 +0000,nypost,Trump kicks Tucker Carlson out of MAGA movemen...,https://nypost.com/2026/03/05/media/trump-kick...,198
16,2026-03-06-14-51-04 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...,186
237,2026-03-06-00-17-50 +0000,nypost,Trump demands pardon for Netanyahu – so Israel...,https://nypost.com/2026/03/05/world-news/trump...,178

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
175,233,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/who-is-mar...
379,149,2026-03-05-18-25-03 +0000,bbc,UK firms pull fixed energy deals as Iran war p...,https://www.bbc.com/news/articles/c3ewwej0p13o...
248,83,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...
174,77,2026-03-06-05-05-00 +0000,wsj,"Rep. Tony Gonzales (R., Texas) said he wouldn’...",https://www.wsj.com/politics/elections/texas-t...
327,61,2026-03-05-20-18-21 +0000,nypost,White House vows to ‘vigorously defend’ tariff...,https://nypost.com/2026/03/05/us-news/trumps-n...
16,56,2026-03-06-14-51-04 +0000,startribune,Trump rules out talks absent Iran's 'unconditi...,https://www.startribune.com/intense-israeli-st...
29,49,2026-03-06-14-31-43 +0000,wapo,"The U.S. labor market lost 92,000 jobs in Febr...",https://www.washingtonpost.com/business/2026/0...
117,46,2026-03-06-10-44-00 +0000,wsj,Length of Middle East Conflict to Determine Im...,https://www.wsj.com/economy/global/length-of-m...
22,45,2026-03-06-14-46-03 +0000,bbc,Oil price jumps after Qatar warns all Gulf pro...,https://www.bbc.com/news/articles/cy031ylgepro...
51,42,2026-03-06-13-49-00 +0000,wsj,The Justice Department said it released some E...,https://www.wsj.com/politics/policy/doj-says-e...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)