## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-21-17-01-08 +0000,nypost,"‘Real Housewives’ star Kim Zolciak’s son, 15, ...",https://nypost.com/2026/08/21/us-news/real-hou...
1,2026-08-21-16-48-47 +0000,startribune,Tribute band Hairball to replace Rod Stewart a...,https://www.startribune.com/minnesota-state-fa...
2,2026-08-21-16-48-34 +0000,chitri,The Drake Oak Brook hotel earns arboretum stat...,https://www.chicagotribune.com/2026/08/21/drak...
3,2026-08-21-16-48-03 +0000,nyt,Should You Invest in Bonds Right Now?,https://www.nytimes.com/2026/08/21/business/in...
4,2026-08-21-16-47-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2482/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
92        trump     39
58   california     22
43          new     17
73         iran     16
602          up     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
93,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...,102
65,2026-08-21-14-41-39 +0000,nyt,Iran Must Plan to Overcome U.S. Sanctions Afte...,https://www.nytimes.com/2026/08/21/world/middl...,98
260,2026-08-20-23-40-00 +0000,wsj,Michael Cohen interviewed President Trump for ...,https://www.wsj.com/politics/policy/trump-talk...,88
217,2026-08-21-02-58-51 +0000,nyt,The Message Behind Trump’s Threats of ‘Economi...,https://www.nytimes.com/2026/08/20/world/europ...,84
59,2026-08-21-14-48-14 +0000,nyt,Why China Thinks It Can Resist Trump’s Economi...,https://www.nytimes.com/2026/08/21/world/asia/...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
93,102,2026-08-21-13-39-20 +0000,chitri,President Donald Trump warns of ‘economic D-Da...,https://www.chicagotribune.com/2026/08/21/trum...
312,58,2026-08-20-21-07-04 +0000,nypost,Morgan Stanley picks Dallas for expansion outs...,https://nypost.com/2026/08/20/business/morgan-...
285,57,2026-08-20-22-13-32 +0000,nypost,University of Southern California and Loyola M...,https://nypost.com/2026/08/20/us-news/uscs-his...
320,51,2026-08-20-20-51-23 +0000,nypost,True scale of Meghan and Harry’s US political ...,https://nypost.com/2026/08/20/us-news/true-sca...
314,51,2026-08-20-21-03-30 +0000,bbc,FBI arrests woman over alleged plot to bomb Ne...,https://www.bbc.co.uk/news/articles/c5y615l2w4...
19,47,2026-08-21-16-26-25 +0000,nypost,Clancy’s ‘distorted mind’ convinced her she wa...,https://nypost.com/2026/08/21/us-news/lindsay-...
117,42,2026-08-21-11-55-00 +0000,wsj,"Nibe Industrier Shares Rise as Heat Pumps, Dat...",https://www.wsj.com/business/earnings/nibe-ind...
118,40,2026-08-21-11-51-03 +0000,cbc,Remains found of missing American mountain cli...,https://www.cbc.ca/news/world/pakistan-missing...
360,38,2026-08-20-18-55-14 +0000,bbc,"UK, France, Germany, Italy and Canada condemn ...",https://www.bbc.co.uk/news/articles/c998evlgz8...
381,35,2026-08-20-17-39-22 +0000,latimes,Eric Swalwell briefly detained as feds seize h...,https://www.latimes.com/politics/story/2026-08...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)