## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-06-21-03-16 +0000,wapo,Trump threatens new rampage as Iran deal deadl...,https://www.washingtonpost.com/national-securi...
1,2026-04-06-21-02-35 +0000,nyt,Elisabeth Waldo Dies at 107; Fused Indigenous ...,https://www.nytimes.com/2026/04/06/arts/music/...
2,2026-04-06-21-02-20 +0000,nypost,Easter egg hunt horror as kids stumble across ...,https://nypost.com/2026/04/06/us-news/easter-e...
3,2026-04-06-21-01-50 +0000,nypost,"Iranian strike kills 4 in Israel, others spare...",https://nypost.com/2026/04/06/world-news/irani...
4,2026-04-06-21-01-00 +0000,wsj,Medicare Insurer Payments to Rise 2.48% in 202...,https://www.wsj.com/health/healthcare/medicare...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2565/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     41
4     iran     36
80     war     14
2      new     13
257     up     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
152,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...,144
182,2026-04-06-07-34-00 +0000,wsj,"Oil Mixed, Government Bonds Fall as Trump Step...",https://www.wsj.com/finance/commodities-future...,116
10,2026-04-06-20-47-37 +0000,nyt,Iran War Live Updates: Trump Renews Threat of ...,https://www.nytimes.com/live/2026/04/06/world/...,115
108,2026-04-06-16-29-51 +0000,nypost,"Trump, first lady Melania tell children of Ira...",https://nypost.com/2026/04/06/us-news/trump-fi...,112
159,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-annual...,111

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
152,144,2026-04-06-11-03-00 +0000,wsj,President Trump told the WSJ that Iran has unt...,https://www.wsj.com/politics/trump-says-hes-ca...
159,75,2026-04-06-10-00-00 +0000,wsj,"JPMorgan Chase CEO Jamie Dimon, in his annual ...",https://www.wsj.com/finance/jamie-dimon-annual...
184,44,2026-04-06-07-21-36 +0000,wsj,"Stock Market Today: Stocks, Oil Edge Higher Ah...",https://www.wsj.com/livecoverage/stock-market-...
26,41,2026-04-06-20-17-55 +0000,nypost,New Nancy Guthrie ransom notes sent to TMZ cla...,https://nypost.com/2026/04/06/us-news/new-nanc...
40,35,2026-04-06-19-49-39 +0000,nypost,Horrific fire that killed two-year-old boy rev...,https://nypost.com/2026/04/06/us-news/fire-tha...
133,34,2026-04-06-14-23-41 +0000,nypost,Supreme Court sets stage for DOJ to toss crimi...,https://nypost.com/2026/04/06/us-news/supreme-...
108,33,2026-04-06-16-29-51 +0000,nypost,"Trump, first lady Melania tell children of Ira...",https://nypost.com/2026/04/06/us-news/trump-fi...
193,32,2026-04-06-04-15-59 +0000,nypost,American woman missing after husband says she ...,https://nypost.com/2026/04/06/world-news/ameri...
216,27,2026-04-05-22-34-00 +0000,wsj,"For nearly two days, injured and alone, a U.S....",https://www.wsj.com/politics/national-security...
5,26,2026-04-06-21-00-18 +0000,nypost,Son of Iran’s twisted PR chief found living li...,https://nypost.com/2026/04/06/us-news/son-of-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)