## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-20-58-57 +0000,nyt,Live Updates: Trump Says Strikes Killed Leader...,https://www.nytimes.com/live/2026/03/03/world/...
1,2026-03-03-20-58-03 +0000,wapo,"Colin Gray, father of accused Georgia school s...",https://www.washingtonpost.com/nation/2026/03/...
2,2026-03-03-20-57-24 +0000,nypost,Turkey says it’s working with all sides to end...,https://nypost.com/2026/03/03/world-news/turke...
3,2026-03-03-20-53-46 +0000,nyt,Israeli Plans Include Option of Going Deeper I...,https://www.nytimes.com/2026/03/03/world/middl...
4,2026-03-03-20-50-49 +0000,nyt,U.S. and Allies Encounter Iran’s Arsenal of Dr...,https://www.nytimes.com/2026/03/03/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
8       iran     91
2      trump     61
24       war     40
3    strikes     21
214      oil     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
330,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...,212
314,2026-03-03-02-36-25 +0000,nyt,Melania Trump Promotes ‘Peace Through Educatio...,https://www.nytimes.com/2026/03/02/us/politics...,206
371,2026-03-02-23-00-12 +0000,nyt,Trump Signals U.S. Is Prepared for a Long War ...,https://www.nytimes.com/2026/03/02/world/middl...,204
269,2026-03-03-09-57-15 +0000,bbc,Trump voters back him on Iran - but that could...,https://www.bbc.com/news/articles/cvg35401nrqo...,203
201,2026-03-03-13-41-43 +0000,bbc,Zelensky fears Trump's Iran war could hurt Ukr...,https://www.bbc.com/news/articles/clyv10dre79o...,202

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
330,212,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...
386,91,2026-03-02-22-16-16 +0000,cbc,All about the Strait of Hormuz and what's at s...,https://www.cbc.ca/news/world/strait-of-hormuz...
262,73,2026-03-03-10-30-00 +0000,wsj,"A tight, three-way race for a Texas Senate sea...",https://www.wsj.com/politics/elections/what-to...
353,57,2026-03-03-00-15-58 +0000,nypost,Supreme Court blocks California law that stopp...,https://nypost.com/2026/03/02/us-news/supreme-...
138,52,2026-03-03-17-29-49 +0000,nypost,Some Amazon services in Middle East go offline...,https://nypost.com/2026/03/03/business/amazon-...
146,50,2026-03-03-17-15-30 +0000,startribune,Gas prices jump 16 cents overnight in Minnesot...,https://www.startribune.com/us-iran-conflict-r...
338,45,2026-03-03-01-26-26 +0000,nyt,"Beyond a Trade War, China, Japan and Others in...",https://www.nytimes.com/2026/03/02/business/us...
193,43,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
342,41,2026-03-03-01-02-52 +0000,nypost,US Embassy in Saudi Arabia hit in suspected Ir...,https://nypost.com/2026/03/02/world-news/us-em...
347,38,2026-03-03-00-33-00 +0000,wsj,President Trump says he will attend the White ...,https://www.wsj.com/politics/policy/trump-to-a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)