## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-12-56-26 +0000,nyt,Former ‘60 Minutes’ Boss to Join Video Journal...,https://www.nytimes.com/2026/10/25/business/me...
1,2026-10-25-12-41-07 +0000,nyt,Introducing a New Way to Understand the Electi...,https://www.nytimes.com/2026/10/25/upshot/elec...
2,2026-10-25-12-36-48 +0000,nyt,Saudi Arabia Reopens Riyadh Airport After Week...,https://www.nytimes.com/2026/10/25/world/middl...
3,2026-10-25-12-33-20 +0000,nyt,"At Least 12 Injured, Including 6 Minors, in Sh...",https://www.nytimes.com/2026/10/25/us/tallahas...
4,2026-10-25-12-31-01 +0000,cbc,Israeli military conducts massive West Bank op...,https://www.cbc.ca/news/world/israel-west-bank...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2322/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
234     trump     20
12   election     16
9         new     13
187        he     10
310   ukraine      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
103,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,66
109,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...,63
136,2026-10-24-22-44-32 +0000,nypost,President Trump and first lady Melania Trump v...,https://nypost.com/2026/10/24/us-news/presiden...,62
94,2026-10-25-02-27-15 +0000,bbc,Obama attacks Trump as he campaigns for Democr...,https://www.bbc.co.uk/news/articles/cmj6jwe1j1...,59
113,2026-10-25-00-33-41 +0000,nypost,Obama rips Trump for tariffs and White House r...,https://nypost.com/2026/10/24/us-news/obama-ri...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
103,66,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...
122,56,2026-10-24-23-35-22 +0000,chitri,"Brazil’s Lula, Bolsonaro close arguments to vo...",https://www.chicagotribune.com/2026/10/24/braz...
170,46,2026-10-24-17-33-41 +0000,nypost,"Ukraine’s Starlink, Starshield back at full po...",https://nypost.com/2026/10/24/world-news/ukrai...
109,44,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
71,40,2026-10-25-06-43-22 +0000,nypost,Arson suspect arrested after fire engulfs Hitl...,https://nypost.com/2026/10/25/world-news/germa...
61,32,2026-10-25-08-00-00 +0000,cbc,Netanyahu 'fighting for his political life' in...,https://www.cbc.ca/news/world/netanyahu-israel...
158,31,2026-10-24-19-37-35 +0000,bbc,Watch: BBC in Paris as police charge protester...,https://www.bbc.co.uk/news/videos/cm89zqw9lx1d...
63,26,2026-10-25-08-00-00 +0000,cbc,A ‘reset’ or ‘one and done’? First Nations and...,https://www.cbc.ca/news/politics/first-nations...
4,26,2026-10-25-12-31-01 +0000,cbc,Israeli military conducts massive West Bank op...,https://www.cbc.ca/news/world/israel-west-bank...
22,25,2026-10-25-10-38-15 +0000,bbc,"More than 1,300 arrested as clashes follow ano...",https://www.bbc.co.uk/news/articles/c95ynd587y...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)