## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-04-32-07 +0000,bbc,Suited and booted: How Joseph Kabila went from...,https://www.bbc.co.uk/news/articles/cr3wv311dw...
1,2026-10-31-04-17-07 +0000,missionlocal,ICE vehicles parking in San Francisco-owned ga...,https://missionlocal.org/2026/10/ice-san-franc...
2,2026-10-31-04-15-26 +0000,nyt,El-Sayed Clashes With Former Primary Rival Who...,https://www.nytimes.com/2026/10/30/us/politics...
3,2026-10-31-04-12-04 +0000,nyt,"Liu Yandong, Rare Woman Among China’s Politica...",https://www.nytimes.com/2026/10/31/world/asia/...
4,2026-10-31-04-06-05 +0000,nypost,"Woman, 28, stabbed in neck while jogging in NY...",https://nypost.com/2026/10/31/us-news/woman-28...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2654/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
97        trump     27
101    election     26
54          new     19
184     binance     19
103  california     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
11,2026-10-31-03-30-57 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...,89
322,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to in-person voting for...,https://www.latimes.com/california/story/2026-...,89
192,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,83
296,2026-10-30-13-06-49 +0000,chitri,Chicago-born Pope Leo XIV casts ‘historic’ loc...,https://www.chicagotribune.com/2026/10/30/pope...,78
362,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...,77

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
11,89,2026-10-31-03-30-57 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...
187,69,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
375,69,2026-10-30-09-33-51 +0000,bbc,Crypto giant Binance hit by $6.3bn hack suspec...,https://www.bbc.co.uk/news/articles/cwg7xp8kx4...
321,64,2026-10-30-12-00-00 +0000,latimes,Your last-minute guide to L.A. County Superior...,https://www.latimes.com/california/story/2026-...
206,59,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
53,58,2026-10-31-00-29-58 +0000,bbc,Alaska Senate candidate denies knowing about a...,https://www.bbc.co.uk/news/articles/cmwyq2gg1y...
384,52,2026-10-30-09-01-01 +0000,nypost,"Canadian CEO, daughters shot and wife attacked...",https://nypost.com/2026/10/30/world-news/canad...
362,50,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...
140,43,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...
32,42,2026-10-31-01-45-41 +0000,nypost,Nithya Raman accused of breaking the law with ...,https://nypost.com/2026/10/30/us-news/nithya-r...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)