## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-12-30-00 +0000,nypost,Chris Brown avoids prison time for brawling at...,https://nypost.com/2026/10/26/world-news/chris...
1,2026-10-26-12-25-34 +0000,nypost,15-year-old busted for shooting at Florida A&M...,https://nypost.com/2026/10/26/us-news/15-year-...
2,2026-10-26-12-24-00 +0000,wsj,Auto & Transport Roundup: Market Talk,https://www.wsj.com/business/auto-transport-ro...
3,2026-10-26-12-20-41 +0000,bbc,Burnham leaves door open to referendum on EU f...,https://www.bbc.co.uk/news/articles/cx240dpzv0...
4,2026-10-26-12-19-00 +0000,wsj,Health Care Roundup: Market Talk,https://www.wsj.com/business/health-care-round...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2410/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
118       trump     25
194    election     24
47         lula     17
85       brazil     15
440  california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
136,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,104
169,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva declared winner of B...,https://www.chicagotribune.com/2026/10/25/braz...,86
151,2026-10-26-00-51-25 +0000,nypost,"Trump critic Lula wins reelection in Brazil, s...",https://nypost.com/2026/10/25/world-news/trump...,79
31,2026-10-26-11-06-00 +0000,wsj,The Morning Risk Report: Lula Wins Fourth Term...,https://www.wsj.com/risk-compliance-journal/th...,77
135,2026-10-26-02-13-00 +0000,wsj,Lula Wins Fourth Term in Brazil Election Upset,https://www.wsj.com/world/americas/lula-clings...,73

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
136,104,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...
144,60,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
155,54,2026-10-26-00-30-06 +0000,chitri,President Donald Trump escalates anti-Muslim a...,https://www.chicagotribune.com/2026/10/25/trum...
32,50,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
239,45,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
25,36,2026-10-26-11-17-19 +0000,chitri,Serbia’s Aleksandar Vucic concedes defeat to t...,https://www.chicagotribune.com/2026/10/26/serb...
149,35,2026-10-26-01-00-00 +0000,wsj,California’s proposed billionaire tax sparked ...,https://www.wsj.com/politics/california-billio...
1,31,2026-10-26-12-25-34 +0000,nypost,15-year-old busted for shooting at Florida A&M...,https://nypost.com/2026/10/26/us-news/15-year-...
152,29,2026-10-26-00-45-21 +0000,chitri,Iranians fear a possible return to all-out war...,https://www.chicagotribune.com/2026/10/25/iran...
200,27,2026-10-25-20-33-17 +0000,nyt,"As Brazil Prepares for Election Runoff, a Town...",https://www.nytimes.com/2026/10/23/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)