## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-10-14-05 +0000,nypost,House Dem lashes out at GOP efforts to probe f...,https://nypost.com/2026/06/11/us-news/house-de...
1,2026-06-11-10-11-29 +0000,nyt,Iran War Live Updates: U.S.-Iran Strikes Risk ...,https://www.nytimes.com/live/2026/06/11/world/...
2,2026-06-11-10-10-16 +0000,nyt,Life Inside an ICE Detention Facility,https://www.nytimes.com/video/us/politics/1000...
3,2026-06-11-10-10-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/finance/banking/financial-...
4,2026-06-11-10-07-25 +0000,bbc,US and Iran exchange strikes across Middle Eas...,https://www.bbc.com/news/articles/c4gyp9v0e93o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
217  trump     35
12    iran     31
19     new     27
94   world     25
95     cup     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
323,2026-06-10-15-00-57 +0000,cbc,How Donald Trump is making the FIFA World Cup ...,https://www.cbc.ca/news/politics/donald-trump-...,140
296,2026-06-10-16-25-02 +0000,nypost,Trump tells Post why he said ‘I love the infla...,https://nypost.com/2026/06/10/us-news/trump-br...,138
218,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...,135
172,2026-06-10-21-48-11 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,133
236,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...,132

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
323,140,2026-06-10-15-00-57 +0000,cbc,How Donald Trump is making the FIFA World Cup ...,https://www.cbc.ca/news/politics/donald-trump-...
236,87,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...
218,69,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...
193,64,2026-06-10-21-09-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...
147,54,2026-06-10-23-12-52 +0000,bbc,Canada proposes teen social media ban - with w...,https://www.bbc.com/news/articles/c872x47gnyjo...
146,51,2026-06-10-23-14-00 +0000,wsj,The race between Maine Republican Sen. Susan C...,https://www.wsj.com/politics/policy/these-wome...
112,43,2026-06-11-02-48-47 +0000,nypost,Federal prosecutors not seeking death penalty ...,https://nypost.com/2026/06/10/us-news/federal-...
319,37,2026-06-10-15-13-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
240,36,2026-06-10-19-20-28 +0000,startribune,ICE agent charged with assault during Operatio...,https://www.startribune.com/ice-agent-charged-...
364,36,2026-06-10-11-07-50 +0000,cbc,Family of victim urges Belfast knife attack no...,https://www.cbc.ca/news/world/knife-attack-bel...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)