## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-10-41-55 +0000,nyt,Russia’s Deadly Missile Attack on Kyiv Exploit...,https://www.nytimes.com/2026/08/05/world/europ...
1,2026-08-05-10-39-00 +0000,wsj,CVS Health Launches Eli Lilly GLP-1 Partnershi...,https://www.wsj.com/health/healthcare/cvs-heal...
2,2026-08-05-10-35-54 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/08/05/us/mic...
3,2026-08-05-10-32-00 +0000,wsj,Theme Parks and ‘Toy Story 5’ Boost Disney Res...,https://www.wsj.com/business/earnings/disney-e...
4,2026-08-05-10-31-36 +0000,bbc,Ex-MP urges Tories to block council candidate ...,https://www.bbc.co.uk/news/articles/c1l1q6167d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2654/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
155       trump     37
281    michigan     28
285     primary     24
282  democratic     23
126         new     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
97,2026-08-05-05-44-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...,153
319,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...,130
429,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...,124
159,2026-08-05-00-21-08 +0000,nyt,El-Sayed Leads Stevens in Michigan Democratic ...,https://www.nytimes.com/2026/08/04/us/election...,122
145,2026-08-05-01-06-38 +0000,nypost,Rep. Wesley Bell holds off ex-‘Squad’ member C...,https://nypost.com/2026/08/04/us-news/rep-wesl...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
97,153,2026-08-05-05-44-00 +0000,wsj,The Democratic Senate primary in Michigan—a fi...,https://www.wsj.com/politics/elections/michiga...
319,107,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
267,76,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
276,72,2026-08-04-20-18-00 +0000,wsj,"Stocks Rally, Oil Drops after Bessent Signals ...",https://www.wsj.com/finance/stocks/stocks-rall...
332,64,2026-08-04-17-48-13 +0000,nypost,Hour-by-hour Trump’s fly-by visit to LA: Where...,https://nypost.com/2026/08/04/us-news/what-tru...
272,60,2026-08-04-20-30-00 +0000,wsj,"What’s Next for Democrats? Join a real-time, ...",https://www.wsj.com/politics/elections/live-q-...
145,60,2026-08-05-01-06-38 +0000,nypost,Rep. Wesley Bell holds off ex-‘Squad’ member C...,https://nypost.com/2026/08/04/us-news/rep-wesl...
392,57,2026-08-04-14-44-50 +0000,chitri,"McDonald’s posts strong second quarter profit,...",https://www.chicagotribune.com/2026/08/04/mcdo...
168,53,2026-08-05-00-15-00 +0000,wsj,The Trump administration is revoking the visa ...,https://www.wsj.com/politics/policy/u-s-revoke...
214,51,2026-08-04-22-24-44 +0000,nypost,Chilling details emerge about heavily armed su...,https://nypost.com/2026/08/04/us-news/man-arre...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)