## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-12-18-52-24 +0000,nyt,Death Toll From Ferry Fire in the Philippines ...,https://www.nytimes.com/2026/09/12/world/asia/...
1,2026-09-12-18-50-02 +0000,nyt,Trump Says Irish Unification Would Be ‘Fantast...,https://www.nytimes.com/2026/09/12/world/europ...
2,2026-09-12-18-42-25 +0000,nypost,Attack that closed key Saudi pipeline blamed o...,https://nypost.com/2026/09/12/world-news/attac...
3,2026-09-12-18-35-54 +0000,chitri,Anthropic CEO calls for AI slowdown,https://www.chicagotribune.com/2026/09/12/anth...
4,2026-09-12-18-33-27 +0000,nyt,Saudi Oil Exports Face Heightened Threats Afte...,https://www.nytimes.com/2026/09/11/business/ir...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6    trump     32
28     oil     13
69     war     11
26      ai     11
203    new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
199,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...,87
82,2026-09-12-12-19-58 +0000,nypost,Trump claims Iran-backed Houthis don’t want to...,https://nypost.com/2026/09/12/us-news/trump-op...,77
190,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...,72
169,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...,71
123,2026-09-12-08-19-29 +0000,nypost,Trump arrives in Ireland to meet leaders befor...,https://nypost.com/2026/09/12/world-news/trump...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
199,87,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...
169,58,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...
173,51,2026-09-11-23-15-00 +0000,wsj,New Jersey Gov. Mikie Sherrill is facing the s...,https://www.wsj.com/politics/misconduct-inquir...
190,50,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...
179,40,2026-09-11-22-52-05 +0000,missionlocal,Meet the S.F. school board candidates: Do you ...,https://missionlocal.org/2026/09/san-francisco...
50,36,2026-09-12-15-31-42 +0000,nypost,NYC mom demands answers after teen daughter di...,https://nypost.com/2026/09/12/us-news/nyc-mom-...
204,36,2026-09-11-21-06-00 +0000,wsj,America marks a quarter-century since the Sept...,https://www.wsj.com/us-news/a-nation-remembers...
65,34,2026-09-12-14-26-02 +0000,nypost,Canada trade war jeopardizing key Senate battl...,https://nypost.com/2026/09/12/us-news/canada-t...
123,32,2026-09-12-08-19-29 +0000,nypost,Trump arrives in Ireland to meet leaders befor...,https://nypost.com/2026/09/12/world-news/trump...
238,29,2026-09-11-19-36-00 +0000,wsj,A CIA official who authorities said walked out...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)