## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-02-45-19 +0000,nyt,"Beneath King Charles’s Jokes and Decorum, Some...",https://www.nytimes.com/2026/04/28/us/politics...
1,2026-04-29-02-38-35 +0000,startribune,Live from Game 5: Wild lead Stars in white-knu...,https://www.startribune.com/live-from-game-5-w...
2,2026-04-29-02-37-33 +0000,nypost,Chilling video reveals moment hero cop is gunn...,https://nypost.com/2026/04/28/us-news/chilling...
3,2026-04-29-02-34-02 +0000,nypost,SoCal city memorializes Charlie Kirk following...,https://nypost.com/2026/04/28/us-news/charlie-...
4,2026-04-29-02-32-23 +0000,nypost,Ghirardelli recalling 13 drink mixes over poss...,https://nypost.com/2026/04/28/us-news/ghirarde...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2591/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     58
1       king     22
70      iran     22
2    charles     17
149      new     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
351,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...,192
11,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...,149
372,2026-04-28-10-00-00 +0000,latimes,Hiltzik: A crypto mogul's lawsuit against a Tr...,https://www.latimes.com/business/story/2026-04...,144
256,2026-04-28-16-27-08 +0000,nypost,President Trump gives first lady Melania a pla...,https://nypost.com/2026/04/28/us-news/presiden...,137
17,2026-04-29-01-22-32 +0000,bbc,In pictures: King joins Trump for White House ...,https://www.bbc.com/news/articles/c86e6z26xdpo...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
351,192,2026-04-28-10-53-00 +0000,wsj,Late-night host Jimmy Kimmel dismissed Preside...,https://www.wsj.com/business/media/jimmy-kimme...
305,114,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
11,85,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...
365,59,2026-04-28-10-00-00 +0000,latimes,Supreme Court will hear Trump's bid to end leg...,https://www.latimes.com/politics/story/2026-04...
215,52,2026-04-28-18-07-51 +0000,nypost,Ex-FBI Director James Comey indicted for threa...,https://nypost.com/2026/04/28/us-news/justice-...
294,48,2026-04-28-14-39-55 +0000,nypost,ISIS jihadist pleads guilty to plotting attack...,https://nypost.com/2026/04/28/world-news/isis-...
224,47,2026-04-28-17-49-27 +0000,nypost,Elon Musk slams OpenAI rival ahead of landmark...,https://nypost.com/2026/04/28/business/elon-mu...
346,42,2026-04-28-11-07-00 +0000,wsj,Melania and Donald Trump vs. Jimmy Kimmel revi...,https://www.wsj.com/politics/melania-and-donal...
9,41,2026-04-29-02-00-00 +0000,wsj,War has imposed a heavy cost on Iran’s economy...,https://www.wsj.com/world/middle-east/iranians...
299,38,2026-04-28-14-21-00 +0000,wsj,China’s Ban on Meta-Manus Deal Shows Strains i...,https://www.wsj.com/world/china/chinas-ban-on-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)