## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-10-24-54 +0000,bbc,Why has the UAE left Opec - and why does this ...,https://www.bbc.com/news/videos/cz92wdvwek8o?a...
1,2026-04-29-10-24-00 +0000,wsj,TotalEnergies Increases Shareholder Returns as...,https://www.wsj.com/business/earnings/totalene...
2,2026-04-29-10-16-00 +0000,wsj,Dollar Edges Up Ahead of Fed Decision,https://www.wsj.com/finance/currencies/austral...
3,2026-04-29-10-15-38 +0000,nyt,Internet Restrictions Spur Russians to Openly ...,https://www.nytimes.com/2026/04/28/world/europ...
4,2026-04-29-10-14-00 +0000,wsj,"U.S. Treasury Yields, Dollar Edge Up Ahead of ...",https://www.wsj.com/articles/energy-prices-key...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2608/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
52     trump     53
48      king     25
8       iran     25
49   charles     19
118      new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
109,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...,196
131,2026-04-29-01-49-53 +0000,nypost,King Charles III gifts president a bell from H...,https://nypost.com/2026/04/28/us-news/king-cha...,166
52,2026-04-29-09-00-00 +0000,wsj,In a bid to keep construction of the White Hou...,https://www.wsj.com/politics/national-security...,165
134,2026-04-29-01-22-32 +0000,bbc,In pictures: King joins Trump for White House ...,https://www.bbc.com/news/articles/c86e6z26xdpo...,133
417,2026-04-28-11-44-00 +0000,wsj,"Pushing past a third assassination attempt, th...",https://www.wsj.com/politics/policy/pushing-pa...,126

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
109,196,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...
386,125,2026-04-28-14-03-16 +0000,nypost,United Arab Emirates to leave OPEC on May 1 in...,https://nypost.com/2026/04/28/business/united-...
180,57,2026-04-28-22-05-30 +0000,nypost,Musk kicks off explosive OpenAI trial by slamm...,https://nypost.com/2026/04/28/business/musk-ki...
291,56,2026-04-28-18-37-44 +0000,nypost,Indian villager digs up sister’s corpse and ca...,https://nypost.com/2026/04/28/world-news/india...
272,53,2026-04-28-19-10-36 +0000,nypost,Trump’s State Dept. will include president’s f...,https://nypost.com/2026/04/28/us-news/trumps-s...
303,51,2026-04-28-18-07-51 +0000,nypost,Ex-FBI Director James Comey indicted for threa...,https://nypost.com/2026/04/28/us-news/justice-...
319,50,2026-04-28-17-16-12 +0000,nypost,FCC orders a review of ABC’s broadcast license...,https://nypost.com/2026/04/28/media/fcc-preps-...
129,47,2026-04-29-02-00-00 +0000,wsj,War has imposed a heavy cost on Iran’s economy...,https://www.wsj.com/world/middle-east/iranians...
284,41,2026-04-28-18-49-33 +0000,cbc,U.S. special forces soldier pleads not guilty ...,https://www.cbc.ca/news/world/polymarket-us-so...
380,40,2026-04-28-14-21-00 +0000,wsj,China’s Ban on Meta-Manus Deal Shows Strains i...,https://www.wsj.com/world/china/chinas-ban-on-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)