## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-22-15-00 +0000,wsj,Opinion | How Trump’s Tariffs Really ‘Work’,https://www.wsj.com/opinion/how-trumps-tariffs...
1,2026-07-09-22-11-52 +0000,nypost,DC National Guard shooter Rahmanullah Lakanwal...,https://nypost.com/2026/07/09/us-news/dc-natio...
2,2026-07-09-22-11-13 +0000,nyt,Gaza Aid Worker on His Way to Watch World Cup ...,https://www.nytimes.com/2026/07/09/world/middl...
3,2026-07-09-22-08-00 +0000,wsj,Opinion | Mike Waltz Takes Cuba to School,https://www.wsj.com/opinion/mike-waltz-takes-c...
4,2026-07-09-22-06-00 +0000,wsj,"Opinion | ‘Decoy’ Dan Sullivan, Back on the Ba...",https://www.wsj.com/opinion/decoy-dan-sullivan...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     31
80     iran     27
71   senate     22
67  platner     22
66   graham     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
305,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...,136
321,2026-07-09-00-16-02 +0000,nypost,Accused rapist Graham Platner finally announce...,https://nypost.com/2026/07/08/us-news/graham-p...,135
7,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...,135
11,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...,115
311,2026-07-09-01-13-44 +0000,nypost,Maine Democrats set convention to replace accu...,https://nypost.com/2026/07/08/us-news/maine-de...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
305,136,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...
11,108,2026-07-09-21-56-00 +0000,wsj,The U.S. was warned that Iran planned a new at...,https://www.wsj.com/politics/iran-planned-new-...
188,50,2026-07-09-14-11-32 +0000,nypost,New footage reveals destruction of Ayatollah K...,https://nypost.com/2026/07/09/world-news/ayato...
48,47,2026-07-09-21-01-35 +0000,bbc,Charlie Kirk murder suspect told roommate 'he ...,https://www.bbc.co.uk/news/articles/c621v466y9...
33,46,2026-07-09-21-11-24 +0000,nypost,Trump ditches extravagant Qatar-gifted Air For...,https://nypost.com/2026/07/09/world-news/trump...
7,40,2026-07-09-22-00-00 +0000,wsj,A chaotic scramble is under way for Democrats ...,https://www.wsj.com/politics/elections/the-cha...
176,40,2026-07-09-14-40-54 +0000,latimes,Dodgers scheduled to visit White House in late...,https://www.latimes.com/politics/story/2026-07...
95,37,2026-07-09-18-44-34 +0000,cbc,Canada takes issue with IOC loosening restrict...,https://www.cbc.ca/sports/olympics/canada-obje...
134,37,2026-07-09-16-50-00 +0000,wsj,U.S. Stocks Rise as Investors Pick AI Trade Ba...,https://www.wsj.com/finance/stocks/oil-steadie...
123,34,2026-07-09-17-29-54 +0000,nypost,Ex-Olympic canoeist David Hearn pleads not gui...,https://nypost.com/2026/07/09/us-news/ex-olymp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)