## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-17-53-35 +0000,bbc,Ukrainian evacuees reunite with family after y...,https://www.bbc.co.uk/news/articles/cqx2818elr...
1,2026-10-31-17-51-04 +0000,nyt,How Binance’s $6.3 Billion Hack Went Down,https://www.nytimes.com/2026/10/31/technology/...
2,2026-10-31-17-50-37 +0000,nypost,Michigan black leader rejects El-Sayed as ‘sna...,https://nypost.com/2026/10/31/us-news/michigan...
3,2026-10-31-17-44-33 +0000,nyt,One Dead in Halloween Store Shooting in Califo...,https://www.nytimes.com/2026/10/31/us/shooting...
4,2026-10-31-17-43-19 +0000,nyt,Live Updates: Hundreds of Thousands Join Anoth...,https://www.nytimes.com/live/2026/10/31/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2447/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
73        trump     24
32   california     15
8       binance     12
29    halloween     12
224    midterms     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
30,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...,70
261,2026-10-30-20-25-06 +0000,nyt,Appeals Court Again Rejects Trump Effort to Im...,https://www.nytimes.com/2026/10/30/us/politics...,64
242,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...,62
16,2026-10-31-16-59-13 +0000,nypost,New details emerge in shooting at Spirit Hallo...,https://nypost.com/2026/10/31/us-news/new-deta...,61
284,2026-10-30-19-16-28 +0000,latimes,9th Circuit again denies Trump administration ...,https://www.latimes.com/politics/story/2026-10...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
30,70,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...
286,55,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
21,52,2026-10-31-16-29-21 +0000,nypost,FBI deployed after shooting at Spirit Hallowee...,https://nypost.com/2026/10/31/us-news/fbi-depl...
55,47,2026-10-31-14-00-00 +0000,wsj,"Polling data remains at issue after Brazil, Se...",https://www.wsj.com/politics/elections/predict...
2,46,2026-10-31-17-50-37 +0000,nypost,Michigan black leader rejects El-Sayed as ‘sna...,https://nypost.com/2026/10/31/us-news/michigan...
75,44,2026-10-31-12-00-00 +0000,latimes,Your last-minute guide to L.A. city charter am...,https://www.latimes.com/california/story/2026-...
208,40,2026-10-30-21-48-01 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
200,40,2026-10-30-22-16-35 +0000,missionlocal,‘Head of the family’: Crocker Amazon hit-and-r...,https://missionlocal.org/2026/10/crocker-amazo...
123,39,2026-10-31-08-00-00 +0000,cbc,'No one is safe' as Ebola outbreak surges to m...,https://www.cbc.ca/news/health/africa-top-doct...
248,33,2026-10-30-20-52-45 +0000,chitri,Justice Department seeks to isolate Alaska bal...,https://www.chicagotribune.com/2026/10/30/fede...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)