## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-04-15-24 +0000,nyt,"Melat Kiros, a Left-Wing Insurgent, Ousts a 15...",https://www.nytimes.com/2026/07/01/us/politics...
1,2026-07-01-04-15-11 +0000,nypost,Socialist congressional candidate Melat Kiros ...,https://nypost.com/2026/07/01/us-news/socialis...
2,2026-07-01-04-12-57 +0000,nyt,Democratic Outsiders Keep Rolling: 5 Takeaways...,https://www.nytimes.com/2026/07/01/us/politics...
3,2026-07-01-04-12-00 +0000,wsj,"Melat Kiros, a 29-year-old Democratic socialis...",https://www.wsj.com/politics/elections/hickenl...
4,2026-07-01-04-01-06 +0000,nyt,Archaeologists Find Maya Monuments Off the Bea...,https://www.nytimes.com/2026/07/01/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
203       court     39
202     supreme     37
69        trump     36
291         new     17
340  birthright     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
288,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...,161
281,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,160
216,2026-06-30-18-01-23 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,154
205,2026-06-30-18-28-41 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,154
285,2026-06-30-14-41-59 +0000,cbc,U.S. Supreme Court denies Trump bid to end bir...,https://www.cbc.ca/news/world/us-scotus-ruling...,153

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
288,161,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...
107,54,2026-06-30-22-21-04 +0000,nypost,Gavin Newsom finally stumps up the cash to spe...,https://nypost.com/2026/06/30/us-news/gavin-ne...
67,51,2026-07-01-00-05-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
284,49,2026-06-30-14-43-47 +0000,nypost,Russia-linked Ukrainian oligarch injured in Mo...,https://nypost.com/2026/06/30/world-news/wife-...
163,46,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
85,45,2026-06-30-23-13-00 +0000,wsj,"Trump’s Friends Gave Him Tickets to World Cup,...",https://www.wsj.com/sports/trumps-friends-gave...
55,41,2026-07-01-00-29-08 +0000,nypost,New NYC law targets protesters near K-12 schoo...,https://nypost.com/2026/06/30/us-news/new-nyc-...
161,39,2026-06-30-20-22-00 +0000,wsj,"Stocks rise, the yen slides and a quiet Fed on...",https://www.wsj.com/finance/stocks/stocks-rise...
191,38,2026-06-30-19-18-30 +0000,nypost,Strait of Hormuz oil flowing back to pre-Iran ...,https://nypost.com/2026/06/30/us-news/strait-o...
261,36,2026-06-30-15-53-59 +0000,latimes,Supreme Court rules that states may ban trans ...,https://www.latimes.com/politics/story/2026-06...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)