## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-11-01-11-30-51 +0000,nypost,Moment RI cops gun down suspected sailboat ban...,https://nypost.com/2026/11/01/us-news/rhode-is...
1,2026-11-01-11-05-40 +0000,bbc,Laura Kuenssberg: Healey risks breaking minimu...,https://www.bbc.co.uk/news/articles/cv36926664...
2,2026-11-01-11-03-36 +0000,bbc,Shops looted as German cost of living protests...,https://www.bbc.co.uk/news/articles/cqj34gnd3n...
3,2026-11-01-11-00-14 +0000,chitri,"In the last stretch of school board races, a p...",https://www.chicagotribune.com/2026/11/01/chic...
4,2026-11-01-11-00-05 +0000,chitri,Gov. JB Pritzker spending millions in Texas an...,https://www.chicagotribune.com/2026/11/01/prit...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2649/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
53       trump     25
56    election     11
277         up     10
154       your     10
343  halloween      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
173,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...,66
135,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...,59
121,2026-10-31-21-22-42 +0000,nypost,Trump ask to set aside ‘Decoy Dan’ Alaska Sena...,https://nypost.com/2026/10/31/us-news/trump-as...,59
89,2026-11-01-00-41-24 +0000,bbc,Judge dismisses Trump's lawsuit against Wall S...,https://www.bbc.co.uk/news/articles/cwr5yj2lj9...,56
126,2026-10-31-21-01-29 +0000,nyt,Judge Tosses Trump’s $10 Billion Suit Against ...,https://www.nytimes.com/2026/10/31/business/me...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
173,66,2026-10-31-15-59-12 +0000,nypost,"US, Iran race to revive Qatar talks as Trump w...",https://nypost.com/2026/10/31/world-news/us-de...
195,44,2026-10-31-13-10-33 +0000,nypost,Abdul El-Sayed tells Rep. Haley Stevens to sta...,https://nypost.com/2026/10/31/us-news/abdul-el...
41,42,2026-11-01-07-26-18 +0000,nypost,FBI visits ‘Decoy Dan’ Sullivan donors as feds...,https://nypost.com/2026/11/01/us-news/alaska-s...
210,42,2026-10-31-12-00-00 +0000,latimes,Your last-minute guide to every L.A. city char...,https://www.latimes.com/california/story/2026-...
188,41,2026-10-31-14-00-00 +0000,wsj,"Polling data remains at issue after Brazil, Se...",https://www.wsj.com/politics/elections/predict...
135,34,2026-10-31-20-13-16 +0000,cbc,Judge throws out Trump suit against Wall Stree...,https://www.cbc.ca/news/world/trump-jeffrey-ep...
193,28,2026-10-31-13-30-00 +0000,nypost,LA voters criticize Karen Bass’ policies witho...,https://nypost.com/2026/10/31/us-news/la-voter...
152,24,2026-10-31-18-17-21 +0000,nypost,Major rescue operation sees evacuees reunite w...,https://nypost.com/2026/10/31/world-news/major...
158,24,2026-10-31-17-54-29 +0000,latimes,California Botox doctor used $45 million in Me...,https://www.latimes.com/california/story/2026-...
169,23,2026-10-31-16-22-42 +0000,nypost,Binance has already refunded 90% of the $6.3 b...,https://nypost.com/2026/10/31/world-news/binan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)