## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-09-31-56 +0000,bbc,Suspected gunman at Washington press dinner id...,https://www.bbc.com/news/articles/cr717nglye0o...
1,2026-04-27-09-30-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
2,2026-04-27-09-30-00 +0000,wsj,How Larry Ellison’s Wealth Differs From Other ...,https://www.wsj.com/finance/larry-ellison-net-...
3,2026-04-27-09-30-00 +0000,wsj,The AI Splurge Is Costing Big Tech Its Workforce,https://www.wsj.com/tech/ai/the-ai-splurge-is-...
4,2026-04-27-09-30-00 +0000,wsj,The $50 Movie Ticket Has Arrived,https://www.wsj.com/business/media/the-50-movi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

               word  score
66            trump     32
259        shooting     26
4            dinner     25
303  correspondents     17
262           white     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
73,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,170
225,2026-04-26-12-50-33 +0000,cbc,Trump says he 'wasn't worried' during correspo...,https://www.cbc.ca/news/world/livestory/white-...,138
129,2026-04-26-21-46-52 +0000,nypost,Witness describes the moment gunman Cole Allen...,https://nypost.com/2026/04/26/us-news/witness-...,132
201,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...,129
66,2026-04-27-04-24-19 +0000,bbc,Trump says he 'wasn't worried' during Washingt...,https://www.bbc.com/news/articles/c2d8dg57rzdo...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
73,170,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
107,83,2026-04-26-23-04-26 +0000,nypost,King Charles’s royal visit to Washington still...,https://nypost.com/2026/04/26/world-news/king-...
29,50,2026-04-27-08-38-37 +0000,bbc,Oil prices rise as US-Iran peace talks stall,https://www.bbc.com/news/articles/c15d57pv925o...
195,44,2026-04-26-16-47-42 +0000,nypost,WHCD shooting suspect Cole Allen mocked lack o...,https://nypost.com/2026/04/26/us-news/whcd-sho...
202,41,2026-04-26-16-18-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
1,38,2026-04-27-09-30-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
117,36,2026-04-26-22-25-15 +0000,nypost,Rodeo announcer has brutal prank played on him...,https://nypost.com/2026/04/26/us-news/rodeo-an...
78,32,2026-04-27-03-00-00 +0000,wsj,Keep DNA a state secret. No motorcade snubs. A...,https://www.wsj.com/politics/how-to-avoid-fist...
0,27,2026-04-27-09-31-56 +0000,bbc,Suspected gunman at Washington press dinner id...,https://www.bbc.com/news/articles/cr717nglye0o...
42,26,2026-04-27-07-56-56 +0000,nypost,Texas nurse Sarah Danh’s family shares health ...,https://nypost.com/2026/04/27/us-news/texas-nu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)