## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-19-22-42-44 +0000,nypost,Gavin Newsom signs bill to create new film and...,https://nypost.com/2026/09/19/us-news/gavin-ne...
1,2026-09-19-22-39-44 +0000,nyt,Trump Faced Loss After Loss. He Then Turned to...,https://www.nytimes.com/2026/09/19/us/politics...
2,2026-09-19-22-36-31 +0000,nyt,"The Most Handsome Melon in Mexico? Yes, It’s a...",https://www.nytimes.com/2026/09/19/world/ameri...
3,2026-09-19-22-32-11 +0000,nypost,NJ woman struck by car — while trying to help...,https://nypost.com/2026/09/19/us-news/nj-woman...
4,2026-09-19-22-28-40 +0000,nypost,Converse apologizes for shoe ads that critics ...,https://nypost.com/2026/09/19/us-news/converse...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
11        trump     48
128       house     16
57           ai     14
10   california     14
127       white     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
105,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...,123
96,2026-09-19-14-51-03 +0000,cbc,"CNN, MS NOW, Politico say journalists denied a...",https://www.cbc.ca/news/world/cnn-journalists-...,117
13,2026-09-19-21-41-39 +0000,wapo,"CNN, MS NOW, Politico say journalists blocked ...",https://www.washingtonpost.com/politics/2026/0...,115
199,2026-09-19-00-31-59 +0000,nyt,"Trump Says He Has Banned CNN, MS NOW and Polit...",https://www.nytimes.com/2026/09/18/business/me...,108
193,2026-09-19-01-07-46 +0000,wapo,"Trump says he’s banning CNN, MS NOW and Politi...",https://www.washingtonpost.com/business/2026/0...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
105,123,2026-09-19-13-46-18 +0000,chitri,"MS NOW, CNN and Politico say their journalists...",https://www.chicagotribune.com/2026/09/19/msno...
127,49,2026-09-19-11-32-48 +0000,nypost,Anthropic splashes out $40M in fight over AI r...,https://nypost.com/2026/09/19/us-news/anthropi...
0,47,2026-09-19-22-42-44 +0000,nypost,Gavin Newsom signs bill to create new film and...,https://nypost.com/2026/09/19/us-news/gavin-ne...
126,42,2026-09-19-11-36-55 +0000,bbc,Nato welcomes Greenland deal as Trump says it ...,https://www.bbc.co.uk/news/articles/c63d7lexyy...
16,36,2026-09-19-21-34-24 +0000,cbc,Saudi Arabia confirms Yemen's Houthi rebels tr...,https://www.cbc.ca/news/world/houthi-rebels-sa...
14,31,2026-09-19-21-40-55 +0000,nypost,Disturbing past of accused hit-and-run driver ...,https://nypost.com/2026/09/19/us-news/californ...
115,29,2026-09-19-12-14-43 +0000,nypost,"GOP control of House, Senate odds fade as Trum...",https://nypost.com/2026/09/19/us-news/republic...
209,27,2026-09-18-23-41-00 +0000,wsj,President Trump said the U.S. and Denmark reac...,https://www.wsj.com/politics/national-security...
41,26,2026-09-19-19-41-19 +0000,nypost,Tree limb that fell onto NYC hot dog vendor wa...,https://nypost.com/2026/09/19/us-news/tree-lim...
218,24,2026-09-18-23-03-00 +0000,wsj,"RFK Jr. received more than $250,000 worth of f...",https://www.wsj.com/politics/rfk-jr-got-free-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)