## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-15-16-55-04 +0000,bbc,Suspected sabotage causes major Netherlands ra...,https://www.bbc.co.uk/news/articles/c8ly49w9g1...
1,2026-09-15-16-54-19 +0000,nypost,NYC agrees to shell out $60M to property owner...,https://nypost.com/2026/09/15/us-news/nyc-agre...
2,2026-09-15-16-52-52 +0000,bbc,Villagers voting on independence over asylum p...,https://www.bbc.co.uk/news/articles/cw5ym35z15...
3,2026-09-15-16-52-50 +0000,nypost,Rep. Thomas Massie moves to impeach Pete Hegse...,https://nypost.com/2026/09/15/us-news/rep-thom...
4,2026-09-15-16-52-27 +0000,wapo,Nick Reiner will not face possibility of death...,https://www.washingtonpost.com/nation/2026/09/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
105  trump     51
454     ai     24
66     new     21
108  court     18
111   mail     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,162
245,2026-09-15-01-00-00 +0000,wsj,Fed leader Kevin Warsh is facing the fight Pre...,https://www.wsj.com/economy/central-banking/wa...,156
97,2026-09-15-13-54-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,146
239,2026-09-15-01-35-49 +0000,nyt,Supreme Court Justices Thomas and Alito Would ...,https://www.nytimes.com/2026/09/14/us/election...,139
258,2026-09-14-23-47-28 +0000,chitri,Supreme Court rejects President Trump’s mail b...,https://www.chicagotribune.com/2026/09/14/supr...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,162,2026-09-15-13-54-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
245,74,2026-09-15-01-00-00 +0000,wsj,Fed leader Kevin Warsh is facing the fight Pre...,https://www.wsj.com/economy/central-banking/wa...
345,65,2026-09-14-19-45-00 +0000,wsj,"U.S. 10-Year Yield Cools After Topping 5%, Ger...",https://www.wsj.com/economy/central-banking/u-...
3,55,2026-09-15-16-52-50 +0000,nypost,Rep. Thomas Massie moves to impeach Pete Hegse...,https://nypost.com/2026/09/15/us-news/rep-thom...
72,54,2026-09-15-14-40-06 +0000,nypost,Bill Gates warns no government in the world is...,https://nypost.com/2026/09/15/business/bill-ga...
380,53,2026-09-14-17-42-39 +0000,chitri,Donald Trump Jr.’s wedding celebration was par...,https://www.chicagotribune.com/2026/09/14/dona...
283,52,2026-09-14-22-28-27 +0000,chitri,GOP Sen. Mitch McConnell returns to Senate for...,https://www.chicagotribune.com/2026/09/14/mitc...
46,48,2026-09-15-15-37-00 +0000,wsj,Nick Reiner Won’t Face Death Penalty if Convic...,https://www.wsj.com/us-news/law/l-a-district-a...
220,47,2026-09-15-04-31-47 +0000,nypost,Ex-Dem insider exposes what Harris told top do...,https://nypost.com/2026/09/15/us-news/ex-dem-i...
161,42,2026-09-15-10-55-00 +0000,wsj,"Bo French, a candidate for Texas’ railroad com...",https://www.wsj.com/politics/policy/bo-frenchs...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)