## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-12-00-00-00 +0000,wsj,Drivers and delivery workers are adjusting sch...,https://www.wsj.com/business/hospitality/food-...
1,2026-04-11-23-57-21 +0000,eltecolote,San Francisco hosts first Dolores Huerta parad...,https://eltecolote.org/content/en/dolores-huer...
2,2026-04-11-23-53-19 +0000,wapo,Direct U.S.-Iran talks on ending war stretch w...,https://www.washingtonpost.com/world/2026/04/1...
3,2026-04-11-23-50-39 +0000,nyt,Push to Expel Swalwell Could Touch Off Chain R...,https://www.nytimes.com/2026/04/11/us/swalwell...
4,2026-04-11-23-42-55 +0000,nyt,"As Election Looms, Will Alito Retire, Giving T...",https://www.nytimes.com/2026/04/11/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
26      iran     34
37  swalwell     18
29       war     16
27     talks     16
51     trump     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
13,2026-04-11-23-08-23 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Mara...,https://www.nytimes.com/live/2026/04/11/world/...,116
8,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...,114
179,2026-04-11-03-49-39 +0000,nypost,California Rep. Eric Swalwell slams sexual mis...,https://nypost.com/2026/04/10/us-news/californ...,97
193,2026-04-11-01-21-53 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,92
115,2026-04-11-13-30-45 +0000,nypost,US Navy ships cross Strait of Hormuz for first...,https://nypost.com/2026/04/11/world-news/us-na...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
13,116,2026-04-11-23-08-23 +0000,nyt,Iran War Live Updates: U.S. and Iran Hold Mara...,https://www.nytimes.com/live/2026/04/11/world/...
8,114,2026-04-11-23-26-00 +0000,wsj,Powerful Democrats are calling for Rep. Eric S...,https://www.wsj.com/politics/elections/democra...
16,48,2026-04-11-23-00-00 +0000,wsj,"Before taking office, RFK Jr. promised to end ...",https://www.wsj.com/politics/policy/rfk-jr-raw...
23,42,2026-04-11-22-30-26 +0000,nypost,Trump threatens China with ‘big problems’ if t...,https://nypost.com/2026/04/11/world-news/trump...
112,35,2026-04-11-14-14-36 +0000,nypost,Iran threatens to attack US Navy ships enterin...,https://nypost.com/2026/04/11/world-news/iran-...
161,34,2026-04-11-08-00-00 +0000,cbc,Her daughter was killed by gunfire in Gaza sch...,https://www.cbc.ca/news/world/gaza-israel-hama...
95,30,2026-04-11-16-02-08 +0000,nypost,Fla. GOP rep plans to file motion to expel Eri...,https://nypost.com/2026/04/11/us-news/florida-...
168,28,2026-04-11-06-50-24 +0000,nypost,Vance arrives in Pakistan for talks with Irani...,https://nypost.com/2026/04/11/us-news/jd-vance...
85,28,2026-04-11-17-37-03 +0000,startribune,Reusse: Can you stand them? Here’s one way to ...,https://www.startribune.com/most-popular-minne...
4,26,2026-04-11-23-42-55 +0000,nyt,"As Election Looms, Will Alito Retire, Giving T...",https://www.nytimes.com/2026/04/11/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)