## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-28-06-11-04 +0000,nyt,Uganda Closes Border With Congo as Ebola Fears...,https://www.nytimes.com/2026/05/27/world/afric...
1,2026-05-28-06-10-33 +0000,bbc,Legal bid to block UK-backed French migrant de...,https://www.bbc.com/news/articles/cdxpdqvdyz7o...
2,2026-05-28-05-52-34 +0000,nypost,Michigan teen girl fights off repeat sex offen...,https://nypost.com/2026/05/28/us-news/michigan...
3,2026-05-28-05-41-41 +0000,nyt,U.S. Conducts New Strikes on Southern Iran,https://www.nytimes.com/live/2026/05/27/world/...
4,2026-05-28-05-37-59 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/28/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
99   trump     41
29     new     29
32    iran     24
446   deal     19
135  texas     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
279,2026-05-27-14-37-09 +0000,cbc,U.S. strikes Iran again after Trump denies rep...,https://www.cbc.ca/news/world/iran-war-day-89-...,112
75,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,104
61,2026-05-28-00-58-49 +0000,nyt,Trump Says He Feels No Political Pressure to M...,https://www.nytimes.com/2026/05/27/world/middl...,101
196,2026-05-27-18-54-00 +0000,wsj,President Trump said Wednesday that Iran was m...,https://www.wsj.com/politics/policy/trump-says...,99
327,2026-05-27-10-54-27 +0000,cbc,Trump's scandal-plagued pick wins Texas Senate...,https://www.cbc.ca/news/world/us-texas-republi...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
279,112,2026-05-27-14-37-09 +0000,cbc,U.S. strikes Iran again after Trump denies rep...,https://www.cbc.ca/news/world/iran-war-day-89-...
350,72,2026-05-27-09-03-41 +0000,nyt,Paxton’s Texas Victory Opens a New Front in th...,https://www.nytimes.com/2026/05/27/us/politics...
322,47,2026-05-27-11-03-03 +0000,nypost,Race against time to rescue villagers trapped ...,https://nypost.com/2026/05/27/world-news/race-...
131,44,2026-05-27-21-26-15 +0000,nypost,Steve Hilton says California should be world’s...,https://nypost.com/2026/05/27/us-news/steve-hi...
339,43,2026-05-27-10-00-00 +0000,latimes,'Monster who killed him': Matthew Perry's form...,https://www.latimes.com/california/story/2026-...
351,41,2026-05-27-09-03-26 +0000,nypost,Israel kills new Hamas military chief who was...,https://nypost.com/2026/05/27/world-news/israe...
50,37,2026-05-28-01-58-46 +0000,nypost,Priest allegedly used mentally ill tenant’s co...,https://nypost.com/2026/05/27/us-news/priest-a...
234,37,2026-05-27-17-00-23 +0000,nypost,‘60 Minutes’ journo Sharyn Alfonsi loses CBS N...,https://nypost.com/2026/05/27/media/60-minutes...
75,37,2026-05-27-23-59-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...
296,36,2026-05-27-13-14-50 +0000,bbc,How a rise in energy bills will affect you fro...,https://www.bbc.com/news/videos/c8xw2g7485zo?a...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)