## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-26-14-53-02 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/26/world/...
1,2026-05-26-14-47-55 +0000,nyt,SpaceX’s Unconventional Corporate Arrangements...,https://www.nytimes.com/2026/05/26/technology/...
2,2026-05-26-14-46-45 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...
3,2026-05-26-14-44-56 +0000,nyt,Iran Begins Lifting Monthslong Internet Blacko...,https://www.nytimes.com/2026/05/26/world/middl...
4,2026-05-26-14-44-44 +0000,bbc,DR Congo seek World Cup ticket refunds after E...,https://www.bbc.com/sport/football/articles/c0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2512/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
9       iran     40
158    trump     23
18   strikes     15
67      deal     14
87     first      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-05-26-14-46-45 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...,128
86,2026-05-26-11-58-30 +0000,wapo,Iran threatens retaliation after U.S. strikes ...,https://www.washingtonpost.com/world/2026/05/2...,102
102,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,100
43,2026-05-26-13-51-48 +0000,nypost,Trump to make rare trip to Camp David as Iran ...,https://nypost.com/2026/05/26/us-news/trump-to...,94
9,2026-05-26-14-35-37 +0000,nyt,Israel Steps Up Strikes in Lebanon as U.S. Pus...,https://www.nytimes.com/2026/05/26/world/middl...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,128,2026-05-26-14-46-45 +0000,nyt,Iran War Live Updates: Tensions Rise as Iran T...,https://www.nytimes.com/live/2026/05/26/world/...
102,60,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...
9,38,2026-05-26-14-35-37 +0000,nyt,Israel Steps Up Strikes in Lebanon as U.S. Pus...,https://www.nytimes.com/2026/05/26/world/middl...
10,33,2026-05-26-14-35-17 +0000,nypost,Iran’s soccer team will commute to World Cup g...,https://nypost.com/2026/05/26/world-news/irans...
157,32,2026-05-26-07-45-06 +0000,nypost,Carney warns Alberta independence vote from Ca...,https://nypost.com/2026/05/26/world-news/carne...
31,30,2026-05-26-14-04-51 +0000,bbc,White House gunman had previous run-ins with S...,https://www.bbc.com/news/articles/c1l22pg12mpo...
12,28,2026-05-26-14-34-34 +0000,nyt,"Ferrari Unveils Luce, Its First Fully Electric...",https://www.nytimes.com/2026/05/25/business/fe...
94,28,2026-05-26-11-12-35 +0000,nypost,Mango tycoon’s son quits fashion giant days af...,https://nypost.com/2026/05/26/world-news/mango...
185,27,2026-05-26-01-43-06 +0000,bbc,Threat of massive chemical tank explosion is '...,https://www.bbc.com/news/articles/cx2119er9glo...
160,27,2026-05-26-07-31-32 +0000,wsj,Stock Market Today: Tech Rally Leads Stocks Hi...,https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)