## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-18-22-55-05 +0000,nyt,"When to Expect Election Results in Alaska, Cal...",https://www.nytimes.com/2026/08/18/us/politics...
1,2026-08-18-22-54-18 +0000,nyt,ABC Sues Trump Administration Over F.C.C. Thre...,https://www.nytimes.com/2026/08/18/business/me...
2,2026-08-18-22-47-17 +0000,nypost,Popular Tahoe ski resorts announce opening dat...,https://nypost.com/2026/08/18/us-news/popular-...
3,2026-08-18-22-46-46 +0000,nypost,DSA councilmember clears way for homeless to p...,https://nypost.com/2026/08/18/us-news/progress...
4,2026-08-18-22-43-07 +0000,nypost,Millennials’ finances have improved since 5 ye...,https://nypost.com/2026/08/18/us-news/millenni...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2208/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     47
601     up     15
564   iran     14
132    new     13
240   bond     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
38,2026-08-18-21-32-00 +0000,wsj,Florida’s Tuesday primary offered a full slate...,https://www.wsj.com/politics/elections/florida...,118
219,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...,109
191,2026-08-18-16-25-18 +0000,chitri,President Donald Trump says US has no talks pl...,https://www.chicagotribune.com/2026/08/18/trum...,95
223,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...,94
227,2026-08-18-13-47-18 +0000,nypost,"Trump says Strait of Hormuz has been de-mined,...",https://nypost.com/2026/08/18/us-news/trump-sa...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
38,118,2026-08-18-21-32-00 +0000,wsj,Florida’s Tuesday primary offered a full slate...,https://www.wsj.com/politics/elections/florida...
312,63,2026-08-18-08-10-32 +0000,wsj,Stock Market Today: Tech Stocks Slide With Glo...,https://www.wsj.com/livecoverage/stock-market-...
219,62,2026-08-18-14-21-08 +0000,nypost,Trump posts map labeling Strait of Hormuz ‘new...,https://nypost.com/2026/08/18/us-news/trump-po...
63,50,2026-08-18-21-09-08 +0000,nypost,Minnesota AG sues Texas Gov. Greg Abbott in bi...,https://nypost.com/2026/08/18/us-news/minnesot...
5,46,2026-08-18-22-42-00 +0000,wsj,The U.S. Forest Service is aiming to open more...,https://www.wsj.com/us-news/climate-environmen...
224,45,2026-08-18-14-08-25 +0000,nypost,Arrest warrant issued then dropped for Jill St...,https://nypost.com/2026/08/18/us-news/warrant-...
28,43,2026-08-18-21-48-15 +0000,nypost,"RFK Jr.’s son, Conor Kennedy, put on Russian w...",https://nypost.com/2026/08/18/world-news/rfk-j...
101,40,2026-08-18-20-35-55 +0000,nypost,Justice Department moving to reopen criminal c...,https://nypost.com/2026/08/18/us-news/justice-...
37,40,2026-08-18-21-32-39 +0000,nypost,Tech terror as AI-generated bomb threat forces...,https://nypost.com/2026/08/18/us-news/ai-gener...
10,40,2026-08-18-22-28-42 +0000,nyt,Former Mother-in-Law Describes Lindsay Clancy’...,https://www.nytimes.com/2026/08/18/us/lindsay-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)