## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-00-14-28 +0000,bbc,What's in the US-Iran agreement that's now in ...,https://www.bbc.com/news/articles/cvgmqzr6p9mo...
1,2026-06-18-00-12-05 +0000,nypost,Families of two friends killed by freak wave o...,https://nypost.com/2026/06/17/us-news/two-cali...
2,2026-06-18-00-01-04 +0000,nyt,Live Updates: U.S. Details Agreement With Iran...,https://www.nytimes.com/live/2026/06/17/world/...
3,2026-06-18-00-00-31 +0000,nyt,"Warsh Makes His Case With Jargon, and a Pencha...",https://www.nytimes.com/2026/06/17/business/ec...
4,2026-06-18-00-00-00 +0000,wsj,Deal Gives Iran Chance to Turbocharge Its Oil ...,https://www.wsj.com/world/middle-east/deal-giv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2294/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19   trump     51
0     iran     42
28    deal     34
175    new     23
427    fed     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
92,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,200
160,2026-06-17-18-41-12 +0000,bbc,Fed holds US interest rates steady as uncertai...,https://www.bbc.com/news/articles/cdjkl78vd7lo...,181
210,2026-06-17-16-31-02 +0000,nypost,Trump says Iran laughed at ‘stupid son of a bi...,https://nypost.com/2026/06/17/us-news/trump-sa...,181
184,2026-06-17-17-44-50 +0000,nypost,Trump jokingly reveals whom he’ll blame if Ira...,https://nypost.com/2026/06/17/us-news/trump-jo...,165
6,2026-06-17-23-57-00 +0000,wsj,"Trump Defends Iran Deal, Says He Wants to Avoi...",https://www.wsj.com/world/trump-defends-iran-d...,155

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
92,200,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
371,125,2026-06-17-01-00-00 +0000,wsj,Kevin Warsh walks into his first meeting as Fe...,https://www.wsj.com/economy/central-banking/tr...
355,63,2026-06-17-03-31-00 +0000,wsj,Rep. Mike Collins won Georgia’s GOP primary ru...,https://www.wsj.com/politics/elections/trump-b...
359,55,2026-06-17-02-50-36 +0000,nypost,Bungee instructors who tossed student off 130-...,https://nypost.com/2026/06/16/world-news/bunge...
145,47,2026-06-17-19-14-00 +0000,wsj,President Trump tied together fights over poli...,https://www.wsj.com/politics/policy/trump-has-...
233,47,2026-06-17-15-17-08 +0000,nypost,Why Jeff Bezos predicts AI will create labor s...,https://nypost.com/2026/06/17/business/why-jef...
234,43,2026-06-17-15-14-55 +0000,nypost,Iranian tankers loaded with oil sail past US N...,https://nypost.com/2026/06/17/world-news/irani...
110,43,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
56,41,2026-06-17-22-01-31 +0000,nypost,World Cup fans furious they were bused to post...,https://nypost.com/2026/06/17/us-news/world-cu...
364,39,2026-06-17-02-00-00 +0000,wsj,Rep. Debbie Wasserman Schultz’s move to run in...,https://www.wsj.com/politics/elections/florida...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)