## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-23-08-49 +0000,nypost,"Ex-NY Gov. David Paterson rips Hochul, Dems fo...",https://nypost.com/2026/06/07/us-news/david-pa...
1,2026-06-07-23-06-53 +0000,nyt,Live Updates: Iran Fires Missiles at Israel fo...,https://www.nytimes.com/live/2026/06/07/world/...
2,2026-06-07-23-04-01 +0000,nyt,Search Continues for Gunmen Who Opened Fire at...,https://www.nytimes.com/2026/06/07/us/ohio-fes...
3,2026-06-07-23-00-04 +0000,bbc,How the High Street became a window on our pol...,https://www.bbc.com/news/articles/cq5p59286v5o...
4,2026-06-07-23-00-00 +0000,wsj,Vermont’s Most Bizarre Real-Estate Listing Is ...,https://www.wsj.com/us-news/vermonts-most-biza...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2336/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
250   trump     20
13     iran     16
16   israel     15
278   world     10
109     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-06-07-23-06-53 +0000,nyt,Live Updates: Iran Fires Missiles at Israel fo...,https://www.nytimes.com/live/2026/06/07/world/...,66
30,2026-06-07-21-10-43 +0000,nyt,Iran Fires Missiles at Israel for First Time S...,https://www.nytimes.com/2026/06/07/world/middl...,63
35,2026-06-07-21-02-06 +0000,nypost,Trump tells The Post ‘things are going well’ a...,https://nypost.com/2026/06/07/us-news/trump-te...,63
49,2026-06-07-20-19-52 +0000,nyt,Trump Defends Compensation Fund and Iran War i...,https://www.nytimes.com/2026/06/07/us/politics...,57
11,2026-06-07-22-12-16 +0000,wapo,Iran launches missiles at Israel for first tim...,https://www.washingtonpost.com/politics/2026/0...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,66,2026-06-07-23-06-53 +0000,nyt,Live Updates: Iran Fires Missiles at Israel fo...,https://www.nytimes.com/live/2026/06/07/world/...
100,56,2026-06-07-15-48-19 +0000,nypost,Trump storms off ‘Meet The Press’ interview af...,https://nypost.com/2026/06/07/us-news/trump-st...
190,55,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
68,35,2026-06-07-18-51-34 +0000,nypost,Long Island bishop using Knicks’ NBA Finals ru...,https://nypost.com/2026/06/07/us-news/long-isl...
22,34,2026-06-07-21-43-00 +0000,nypost,California voter fraud fight sparks all-out wa...,https://nypost.com/2026/06/07/us-news/californ...
106,32,2026-06-07-15-21-34 +0000,nypost,Bombshell LA mayor’s race projection changes e...,https://nypost.com/2026/06/07/us-news/la-mayor...
21,31,2026-06-07-21-43-44 +0000,nypost,McDonald’s employee in ICU after coworker alle...,https://nypost.com/2026/06/07/us-news/mcdonald...
114,29,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...
163,28,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
33,27,2026-06-07-21-04-25 +0000,nypost,Hero NYC cop who nabbed killer behind Post’s f...,https://nypost.com/2026/06/07/us-news/hero-nyc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)