## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-08-08-17-38 +0000,nypost,UK supermarket worker fired for tackling proli...,https://nypost.com/2026/05/08/world-news/super...
1,2026-05-08-08-15-55 +0000,nyt,Live Updates: Early U.K. Election Results Poin...,https://www.nytimes.com/live/2026/05/08/world/...
2,2026-05-08-08-14-00 +0000,wsj,Euro Little Moved by Trump Tariff Threats as I...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-05-08-08-13-16 +0000,bbc,John Curtice: Election results show politics i...,https://www.bbc.com/news/articles/ce8p4yn448vo...
4,2026-05-08-08-13-07 +0000,bbc,The companies making billions from the Iran war,https://www.bbc.com/news/articles/ce8pyyz5e0ro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
26        trump     46
29         iran     34
30          war     22
125  hantavirus     20
656        ship     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
225,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...,136
138,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...,134
125,2026-05-07-23-02-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,130
41,2026-05-08-05-57-08 +0000,bbc,Trump says US-Iran ceasefire still in place af...,https://www.bbc.com/news/articles/c626zyywxjno...,124
114,2026-05-07-23-51-58 +0000,nypost,Trump downplays US-Iran attacks as ‘love tap’ ...,https://nypost.com/2026/05/07/world-news/trump...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
225,136,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...
145,92,2026-05-07-22-08-00 +0000,wsj,The Centers for Disease Control and Prevention...,https://www.wsj.com/politics/policy/cdc-coordi...
125,74,2026-05-07-23-02-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
24,68,2026-05-08-07-04-24 +0000,bbc,Oil prices rise after US and Iran exchange fir...,https://www.bbc.com/news/articles/c86dp85g59xo...
193,50,2026-05-07-20-52-12 +0000,nypost,Argentina will start testing rats for hantavir...,https://nypost.com/2026/05/07/world-news/argen...
243,46,2026-05-07-18-37-27 +0000,nypost,White House lashes out at ‘Star Wars’ actor Ma...,https://nypost.com/2026/05/07/us-news/white-ho...
0,41,2026-05-08-08-17-38 +0000,nypost,UK supermarket worker fired for tackling proli...,https://nypost.com/2026/05/08/world-news/super...
66,41,2026-05-08-03-14-00 +0000,wsj,China Hands Suspended Death Sentences to Forme...,https://www.wsj.com/world/china/china-hands-su...
138,41,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...
304,39,2026-05-07-15-16-51 +0000,nypost,McDonald’s posts strong earnings — but viral C...,https://nypost.com/2026/05/07/business/mcdonal...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)