## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-22-02-46-11 +0000,nyt,Cuba Celebrates Raúl Castro After the U.S. Acc...,https://www.nytimes.com/2026/05/21/world/ameri...
1,2026-05-22-02-45-21 +0000,nyt,"San Diego Mosque Shooter So Alarmed Police, Th...",https://www.nytimes.com/2026/05/21/us/san-dieg...
2,2026-05-22-02-40-58 +0000,bbc,Alberta to hold referendum on whether to remai...,https://www.bbc.com/news/articles/cvgze8n5dxko...
3,2026-05-22-02-26-08 +0000,bbc,Elon Musk's SpaceX postpones Starship launch,https://www.bbc.com/news/articles/cy42w782ejvo...
4,2026-05-22-02-23-49 +0000,nyt,"In Jab at Trump, Mexico Targets Foreign Electi...",https://www.nytimes.com/2026/05/21/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
30   trump     45
167    new     17
235    was     16
105   iran     15
241     he     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
121,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...,116
247,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...,104
61,2026-05-21-23-54-00 +0000,wsj,House Republican leaders yanked a planned vote...,https://www.wsj.com/politics/house-republicans...,103
109,2026-05-21-21-59-00 +0000,latimes,GOP senators balk at Trump's $1.8-billion 'ant...,https://www.latimes.com/politics/story/2026-05...,99
351,2026-05-21-11-01-27 +0000,nypost,Queen Elizabeth was eager for Andrew to become...,https://nypost.com/2026/05/21/world-news/docum...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
121,116,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...
351,98,2026-05-21-11-01-27 +0000,nypost,Queen Elizabeth was eager for Andrew to become...,https://nypost.com/2026/05/21/world-news/docum...
61,58,2026-05-21-23-54-00 +0000,wsj,House Republican leaders yanked a planned vote...,https://www.wsj.com/politics/house-republicans...
322,57,2026-05-21-13-00-00 +0000,wsj,The Department of Health and Human Services ha...,https://www.wsj.com/politics/policy/hhs-launch...
397,52,2026-05-21-07-47-06 +0000,wsj,"Stock Market News, May 21, 2026: Dow Closes at...",https://www.wsj.com/livecoverage/stock-market-...
414,45,2026-05-21-03-01-15 +0000,bbc,US charges Cuba's Raúl Castro with murder over...,https://www.bbc.com/news/articles/c3r219yxl5eo...
56,44,2026-05-22-00-04-00 +0000,wsj,Mortgage rates this week rose to the highest l...,https://www.wsj.com/economy/housing/mortgage-r...
64,43,2026-05-21-23-40-44 +0000,nypost,Park Slope Food Coop under fire over anti-Jewi...,https://nypost.com/2026/05/21/us-news/park-slo...
29,42,2026-05-22-01-25-03 +0000,nypost,San Diego mosque shooter Caleb Vazquez’s famil...,https://nypost.com/2026/05/21/us-news/san-dieg...
218,42,2026-05-21-17-54-40 +0000,bbc,DR Congo cancels World Cup training camp over ...,https://www.bbc.com/news/articles/c8d80856q2go...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)