## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-09-51-06 +0000,bbc,Carney to push for closer ties at Canada-EU su...,https://www.bbc.co.uk/news/articles/cq8ezj7jyl...
1,2026-10-29-09-49-00 +0000,wsj,BBVA Shares Drop After Spain Business Misses E...,https://www.wsj.com/business/earnings/bbva-pos...
2,2026-10-29-09-47-00 +0000,wsj,Apple Squeezed These Chip Suppliers for Years....,https://www.wsj.com/world/apple-squeezed-these...
3,2026-10-29-09-47-00 +0000,wsj,A pre-midterms pause at the Fed was wise. Read...,https://www.wsj.com/economy/central-banking/ke...
4,2026-10-29-09-46-25 +0000,bbc,Hong Kong's leader apologises for deadly high-...,https://www.bbc.co.uk/news/articles/cr5yn9770p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2423/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
123    election     31
376       trump     25
139      israel     20
551  california     19
219        will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
194,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...,132
370,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...,106
342,2026-10-28-16-34-01 +0000,nyt,Netanyahu Didn’t Win Israel’s Election. But He...,https://www.nytimes.com/2026/10/28/world/middl...,98
191,2026-10-28-21-28-00 +0000,wsj,Flávio Bolsonaro landed in Miami after losing ...,https://www.wsj.com/world/americas/flavio-bols...,96
406,2026-10-28-12-38-03 +0000,nyt,Israel’s Election: When Will We Know Who Will ...,https://www.nytimes.com/2026/10/25/world/middl...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
194,132,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...
94,74,2026-10-29-04-44-00 +0000,wsj,"In a comeback attempt, Democrat Keisha Lance B...",https://www.wsj.com/politics/elections/the-ex-...
130,74,2026-10-29-01-12-00 +0000,wsj,Fed Chairman Kevin Warsh said higher rates are...,https://www.wsj.com/economy/central-banking/th...
389,73,2026-10-28-13-57-54 +0000,chitri,High-speed train collision kills at least 68 i...,https://www.chicagotribune.com/2026/10/28/high...
33,73,2026-10-29-09-01-00 +0000,wsj,Most Americans—including many Iranian American...,https://www.wsj.com/politics/elections/i-went-...
191,65,2026-10-28-21-28-00 +0000,wsj,Flávio Bolsonaro landed in Miami after losing ...,https://www.wsj.com/world/americas/flavio-bols...
406,63,2026-10-28-12-38-03 +0000,nyt,Israel’s Election: When Will We Know Who Will ...,https://www.nytimes.com/2026/10/25/world/middl...
370,60,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...
426,54,2026-10-28-10-47-00 +0000,wsj,Are Democrats drawing up a new map in the Sout...,https://www.wsj.com/politics/elections/are-dem...
216,50,2026-10-28-20-46-00 +0000,wsj,Minnesota prosecutors charged conservative act...,https://www.wsj.com/politics/elections/conserv...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)