## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-04-19-36-32 +0000,nypost,"Ukraine hits Russian ship, air defense systems...",https://nypost.com/2026/06/04/world-news/ukrai...
1,2026-06-04-19-35-36 +0000,nyt,Mideast Live Updates: Israel and Hezbollah Tra...,https://www.nytimes.com/live/2026/06/04/world/...
2,2026-06-04-19-32-00 +0000,wsj,"U.S. Natural Gas Futures Rise on Weather, Stor...",https://www.wsj.com/finance/commodities-future...
3,2026-06-04-19-28-06 +0000,bbc,John Bolton expected to plead guilty in classi...,https://www.bbc.com/news/articles/c2e2e71xyjzo...
4,2026-06-04-19-28-02 +0000,nypost,Gas tanker hauling stolen fuel explodes into f...,https://nypost.com/2026/06/04/world-news/wild-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
233  trump     39
19     new     20
898   iran     17
212     up     17
484    war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
320,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...,105
315,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,105
33,2026-06-04-18-20-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...,104
316,2026-06-03-21-43-00 +0000,wsj,Some GOP lawmakers are pushing to kill the adm...,https://www.wsj.com/politics/policy/fight-to-k...,96
273,2026-06-04-01-20-00 +0000,wsj,Trump Tells Aides He Won’t Resume All-Out War ...,https://www.wsj.com/world/middle-east/trump-ir...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
320,105,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
315,66,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...
85,60,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
335,52,2026-06-03-20-58-49 +0000,nypost,Ebola fears prompt Spanish city to cancel Cong...,https://nypost.com/2026/06/03/sports/ebola-fea...
1,51,2026-06-04-19-35-36 +0000,nyt,Mideast Live Updates: Israel and Hezbollah Tra...,https://www.nytimes.com/live/2026/06/04/world/...
316,48,2026-06-03-21-43-00 +0000,wsj,Some GOP lawmakers are pushing to kill the adm...,https://www.wsj.com/politics/policy/fight-to-k...
147,48,2026-06-04-13-52-17 +0000,nypost,Graham Platner gives flimsy excuse to Dem sena...,https://nypost.com/2026/06/04/us-news/graham-p...
279,44,2026-06-04-01-00-00 +0000,wsj,"Amaryllis Fox Kennedy, a former Trump administ...",https://www.wsj.com/politics/national-security...
186,44,2026-06-04-11-10-48 +0000,nypost,Dramatic footage shows Iranian drone’s deadly ...,https://nypost.com/2026/06/04/world-news/drama...
140,42,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)