## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-10-02-16 +0000,nyt,"Even Before Attack, Berlin’s Gay Community Fel...",https://www.nytimes.com/2026/07/27/world/europ...
1,2026-07-27-10-00-46 +0000,chitri,Low turnout trend continues in Cook County pro...,https://www.chicagotribune.com/2026/07/27/low-...
2,2026-07-27-10-00-17 +0000,chitri,"Thomas Nolan, longtime Springfield social serv...",https://www.chicagotribune.com/2026/07/27/thom...
3,2026-07-27-10-00-00 +0000,nypost,Why Kevin Warsh should think twice about hikin...,https://nypost.com/2026/07/27/business/why-kev...
4,2026-07-27-10-00-00 +0000,nypost,Elevator issues at NYC high-rise mean breakdow...,https://nypost.com/2026/07/27/us-news/elevator...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2626/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
35     iran     20
200   trump     19
3    berlin     11
371  killed     11
256      he     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,71
204,2026-07-26-13-57-39 +0000,nyt,Trump Holds Off on Major War Escalation Agains...,https://www.nytimes.com/2026/07/25/us/politics...,69
210,2026-07-26-12-49-15 +0000,nyt,U.S.-Iran War Pauses for 2nd Straight Day With...,https://www.nytimes.com/2026/07/26/world/middl...,68
192,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...,65
209,2026-07-26-13-00-01 +0000,cbc,Suspect in deadly Berlin Pride attack killed i...,https://www.cbc.ca/news/world/berlin-pride-att...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,71,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
192,65,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...
17,57,2026-07-27-09-20-57 +0000,nypost,TikTokker voiced concerns about Seattle Center...,https://nypost.com/2026/07/27/us-news/tiktokke...
37,37,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
53,33,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Oil Tumbles, Stock Futures...",https://www.wsj.com/livecoverage/stock-market-...
210,31,2026-07-26-12-49-15 +0000,nyt,U.S.-Iran War Pauses for 2nd Straight Day With...,https://www.nytimes.com/2026/07/26/world/middl...
166,30,2026-07-26-18-22-19 +0000,nypost,Jeffries won’t rule out vote to abolish ICE if...,https://nypost.com/2026/07/26/us-news/jeffries...
73,24,2026-07-27-05-24-03 +0000,nypost,Remains found by Florida kayakers in 2024 iden...,https://nypost.com/2026/07/27/us-news/remains-...
87,23,2026-07-27-02-35-57 +0000,nypost,United Cajun Navy said they’ve never spoken to...,https://nypost.com/2026/07/26/us-news/united-c...
48,23,2026-07-27-08-19-08 +0000,bbc,NHS 'will collapse' without social care reform...,https://www.bbc.co.uk/news/articles/cn0n5xpzlz...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)