## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-29-15-50-38 +0000,nypost,Big rig left dangling from California bridge a...,https://nypost.com/2026/08/29/us-news/big-rig-...
1,2026-08-29-15-43-21 +0000,nyt,"Search Continues for 2,400 Missing in Nepal Fl...",https://www.nytimes.com/2026/08/29/world/asia/...
2,2026-08-29-15-40-45 +0000,cbc,Iceland votes on whether to start EU membershi...,https://www.cbc.ca/news/world/iceland-vote-eu-...
3,2026-08-29-15-32-21 +0000,nyt,"Why Iceland and Others Might Want In, Not Out,...",https://www.nytimes.com/2026/08/29/world/europ...
4,2026-08-29-15-32-09 +0000,nypost,US families with relatives missing in the Nepa...,https://nypost.com/2026/08/29/world-news/us-fa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2522/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
24        trump     51
11        nepal     20
118         new     16
3    california     14
34        china     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
174,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...,122
227,2026-08-28-19-41-00 +0000,wsj,A West Point for Space? Trump Calls for New Ac...,https://www.wsj.com/politics/national-security...,99
291,2026-08-28-16-58-30 +0000,nypost,Trump’s new Canada tariffs could flush savings...,https://nypost.com/2026/08/28/business/trumps-...,97
290,2026-08-28-16-58-58 +0000,latimes,"California sues Trump administration, develope...",https://www.latimes.com/environment/story/2026...,93
109,2026-08-29-07-11-04 +0000,bbc,Ex-White House teleprompter operator ordered t...,https://www.bbc.co.uk/news/articles/c4gj2dl4x5...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
174,122,2026-08-28-21-55-23 +0000,chitri,President Trump said he saw a quick end to the...,https://www.chicagotribune.com/2026/08/28/trum...
179,80,2026-08-28-21-43-00 +0000,wsj,Fed Chairman Kevin Warsh spoke today and the o...,https://www.wsj.com/economy/warsh-speaks-and-r...
307,72,2026-08-28-15-56-16 +0000,wapo,At least 540 killed in floods; search on for h...,https://www.washingtonpost.com/world/2026/08/2...
226,51,2026-08-28-19-41-00 +0000,wsj,The U.S. will develop an academy to train pers...,https://www.wsj.com/politics/national-security...
31,46,2026-08-29-14-00-00 +0000,nypost,California college takes top spot in TIME’s ne...,https://nypost.com/2026/08/29/us-news/californ...
121,45,2026-08-29-02-15-00 +0000,wsj,The White House teleprompter operator under in...,https://www.wsj.com/politics/policy/white-hous...
244,44,2026-08-28-19-02-07 +0000,cbc,U.S. may seek win with Mexico in wake of colla...,https://www.cbc.ca/news/world/mexico-canada-us...
28,39,2026-08-29-14-13-01 +0000,nyt,"For LGBTQ Fans, Dolly Parton Inspired Their Wi...",https://www.nytimes.com/2026/08/29/us/dolly-pa...
176,38,2026-08-28-21-50-00 +0000,wsj,Media provocateur Milo Yiannopoulos has been d...,https://www.wsj.com/politics/policy/ice-has-de...
132,38,2026-08-29-01-00-00 +0000,wsj,The U.S. has rushed so many munitions to the M...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)