## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-20-55-24 +0000,nyt,What to Know About Lula’s Election Victory in ...,https://www.nytimes.com/2026/10/26/world/ameri...
1,2026-10-26-20-52-46 +0000,nypost,"Russia kills 2, injures 4 in missile strike on...",https://nypost.com/2026/10/26/world-news/russi...
2,2026-10-26-20-52-27 +0000,nypost,Unhinged NC state Senate candidate arrested af...,https://nypost.com/2026/10/26/us-news/unhinged...
3,2026-10-26-20-45-10 +0000,nyt,Election Surprises,https://www.nytimes.com/2026/10/26/world/brazi...
4,2026-10-26-20-41-43 +0000,bbc,Trump faces backlash after invoking 9/11 in ve...,https://www.bbc.co.uk/news/articles/c3rryxlkq5...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2584/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
28        trump     33
1      election     32
0          lula     20
3        brazil     16
175  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
303,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva mobilized millions t...,https://www.chicagotribune.com/2026/10/25/braz...,142
277,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,123
13,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,107
126,2026-10-26-15-57-12 +0000,nypost,"Brazil markets, currency reel from leftist Lui...",https://nypost.com/2026/10/26/business/brazil-...,96
206,2026-10-26-11-06-00 +0000,wsj,The Morning Risk Report: Lula Wins Fourth Term...,https://www.wsj.com/risk-compliance-journal/th...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
303,142,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva mobilized millions t...,https://www.chicagotribune.com/2026/10/25/braz...
110,67,2026-10-26-16-51-12 +0000,nypost,Pro-Abdul El-Sayed ad sparks fury with false c...,https://nypost.com/2026/10/26/us-news/pro-abdu...
207,59,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
194,52,2026-10-26-12-00-00 +0000,nypost,Inside California’s unlikely new boomtown wher...,https://nypost.com/2026/10/26/real-estate/fres...
180,51,2026-10-26-13-26-07 +0000,chitri,Anthropic files for potentially the biggest IP...,https://www.chicagotribune.com/2026/10/26/anth...
166,50,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...
284,44,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
204,39,2026-10-26-11-17-19 +0000,chitri,Serbia’s Aleksandar Vucic concedes defeat to t...,https://www.chicagotribune.com/2026/10/26/serb...
80,39,2026-10-26-18-28-40 +0000,nypost,"Yankees World Series champion Mark Teixeira, n...",https://nypost.com/2026/10/26/us-news/yankees-...
121,33,2026-10-26-16-26-22 +0000,nypost,"Maurene Comey, daughter of ex-FBI director, un...",https://nypost.com/2026/10/26/us-news/maurene-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)