## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-16-20-54-05 +0000,nyt,Bend Shooting Likely to Heighten Gun Debate in...,https://www.nytimes.com/2026/10/16/us/bend-sho...
1,2026-10-16-20-53-56 +0000,nypost,Blakeman hammers Hochul over dismal NY public ...,https://nypost.com/2026/10/16/us-news/bruce-bl...
2,2026-10-16-20-52-38 +0000,nyt,Why Bad News in the Bond Market May Be Good Ne...,https://www.nytimes.com/2026/10/16/business/bo...
3,2026-10-16-20-51-25 +0000,nyt,RFK Jr. Pledged to Advance Anti-Vaccine Group’...,https://www.nytimes.com/2026/10/16/us/politics...
4,2026-10-16-20-51-20 +0000,nypost,Man who drugged and raped dead NYC college stu...,https://nypost.com/2026/10/16/us-news/man-who-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2627/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
145   trump     30
15   school     22
182     new     18
6    oregon     15
133  senate     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
34,2026-10-16-19-51-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,119
271,2026-10-16-05-06-00 +0000,wsj,Sen. Susan Collins and Troy Jackson wrapped up...,https://www.wsj.com/politics/elections/five-ta...,101
23,2026-10-16-20-14-19 +0000,nyt,"Katie Zacharia, Trump’s New Press Secretary, I...",https://www.nytimes.com/2026/10/16/us/politics...,81
88,2026-10-16-18-14-05 +0000,nypost,Trump denies restricting Ukraine’s access to S...,https://nypost.com/2026/10/16/us-news/trump-de...,76
213,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
34,119,2026-10-16-19-51-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
298,69,2026-10-16-00-49-23 +0000,cbc,"3 children, 1 teacher dead after shooting at O...",https://www.cbc.ca/news/world/oregon-school-sh...
337,68,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
276,60,2026-10-16-04-41-00 +0000,wsj,Fed Chairman Kevin Warsh declined to endorse o...,https://www.wsj.com/economy/central-banking/wa...
291,58,2026-10-16-01-38-37 +0000,nypost,Hot-headed Troy Jackson tells Susan Collins to...,https://nypost.com/2026/10/15/us-news/anti-dat...
239,51,2026-10-16-09-52-53 +0000,nypost,Elon Musk’s three-word reaction after unveilin...,https://nypost.com/2026/10/16/business/elon-mu...
210,46,2026-10-16-10-59-00 +0000,wsj,The geography of U.S. politics might be changi...,https://www.wsj.com/politics/why-americas-poli...
213,45,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...
146,40,2026-10-16-14-34-39 +0000,cbc,"Israeli settlers attack Palestinians, American...",https://www.cbc.ca/news/world/israeli-settlers...
176,40,2026-10-16-13-04-00 +0000,wsj,"Canada Housing Starts Rise in September, Thoug...",https://www.wsj.com/economy/housing/canada-hou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)