## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-17-23-01-44 +0000,nypost,"Major pizza franchisee owner files bankruptcy,...",https://nypost.com/2026/03/17/us-news/this-maj...
1,2026-03-17-22-55-38 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/17/us/ill...
2,2026-03-17-22-54-59 +0000,nyt,"Oscars Viewership Slides 9%, Its First Drop Si...",https://www.nytimes.com/2026/03/17/business/me...
3,2026-03-17-22-53-53 +0000,nyt,Oil Begins Flowing Through California Pipeline...,https://www.nytimes.com/2026/03/16/us/santa-ba...
4,2026-03-17-22-53-44 +0000,nypost,Accused DUI driver in fiery SoCal wreck that k...,https://nypost.com/2026/03/17/us-news/dui-driv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2575/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
61    iran     56
25   trump     55
62     war     28
68     top     20
76  israel     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
102,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...,256
96,2026-03-17-20-17-30 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,203
8,2026-03-17-22-47-16 +0000,nyt,Iran War Live Updates: Iran Confirms Israeli S...,https://www.nytimes.com/live/2026/03/17/world/...,203
225,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,197
44,2026-03-17-21-48-08 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,189

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
102,256,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...
300,67,2026-03-17-09-52-59 +0000,nypost,Top Iran security official Ali Larijani killed...,https://nypost.com/2026/03/17/world-news/israe...
209,56,2026-03-17-15-07-00 +0000,wsj,President Trump has made tightening voter-elig...,https://www.wsj.com/politics/policy/what-is-sa...
123,51,2026-03-17-19-14-20 +0000,nyt,"Flight Prices Are Up Amid Soaring Fuel Costs, ...",https://www.nytimes.com/2026/03/17/business/ai...
199,51,2026-03-17-15-38-13 +0000,wapo,Trump has choked off Cuba’s oil supply. China ...,https://www.washingtonpost.com/world/2026/02/2...
184,47,2026-03-17-16-11-15 +0000,nypost,Trump’s fiery response to NATO allies over Str...,https://nypost.com/2026/03/17/us-news/trump-sl...
174,44,2026-03-17-16-52-40 +0000,nypost,Disney entertainment boss Dana Walden unveils ...,https://nypost.com/2026/03/17/business/disney-...
162,39,2026-03-17-17-31-07 +0000,nypost,Dem challenger in Texas House race starred in ...,https://nypost.com/2026/03/17/us-news/dem-chal...
166,36,2026-03-17-17-14-03 +0000,nypost,Iranian influencer celebrates death of of lead...,https://nypost.com/2026/03/17/world-news/celeb...
40,34,2026-03-17-21-51-50 +0000,latimes,Live Nation's Justice Department trial continu...,https://www.latimes.com/entertainment-arts/bus...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)