## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-04-16-00-00 +0000,wsj,"Inside Dodgers Owner Mark Walter’s Charity, a ...",https://www.wsj.com/business/inside-dodgers-ow...
1,2026-10-04-16-00-00 +0000,wsj,How Polymarket’s ‘Growth at All Costs’ Strateg...,https://www.wsj.com/finance/investing/how-poly...
2,2026-10-04-15-58-42 +0000,nypost,‘Tinder Swindler’ Simon Leviev launches scam-p...,https://nypost.com/2026/10/04/business/tinder-...
3,2026-10-04-15-51-24 +0000,bbc,"I'm a classic old school Conservative, says Ke...",https://www.bbc.co.uk/news/articles/cx7vp6d5pg...
4,2026-10-04-15-45-57 +0000,nyt,How Democrats Have Changed the Way They Talk A...,https://www.nytimes.com/2026/10/04/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
49      trump     25
72   flydubai     15
55        new     14
95     attack      8
166      kyiv      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,65
166,2026-10-03-22-20-25 +0000,chitri,Pres. Donald Trump urges calls to Arkansas Sen...,https://www.chicagotribune.com/2026/10/03/trum...,64
167,2026-10-03-22-18-41 +0000,chitri,Pres. Donald Trump rallies in Ohio to boost Jo...,https://www.chicagotribune.com/2026/10/03/trum...,60
210,2026-10-03-16-50-36 +0000,nypost,Trump gushes over blue-collar flydubai hero wh...,https://nypost.com/2026/10/03/us-news/trump-gu...,60
181,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,65,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
122,47,2026-10-04-03-15-01 +0000,nypost,Longtime aviation pal of stabbed flydubai pilo...,https://nypost.com/2026/10/03/world-news/longt...
218,39,2026-10-03-16-20-59 +0000,cbc,Tennessee prisons chief to resign after failed...,https://www.cbc.ca/news/world/tennessee-prison...
166,39,2026-10-03-22-20-25 +0000,chitri,Pres. Donald Trump urges calls to Arkansas Sen...,https://www.chicagotribune.com/2026/10/03/trum...
17,38,2026-10-04-14-38-01 +0000,chitri,US Marine arrested for alleged murder of a wom...,https://www.chicagotribune.com/2026/10/04/us-m...
56,38,2026-10-04-10-00-38 +0000,chitri,"Illinois Senate race: Republican Don Tracy, a ...",https://www.chicagotribune.com/2026/10/04/illi...
110,37,2026-10-04-05-33-22 +0000,nypost,Shooting near Baltimore youth football event l...,https://nypost.com/2026/10/04/us-news/shooting...
133,34,2026-10-04-01-35-10 +0000,nypost,Debris from vanished Boston-bound plane found ...,https://nypost.com/2026/10/03/world-news/debri...
60,32,2026-10-04-10-00-01 +0000,wapo,Should Big Oil pay for climate change? A Supre...,https://www.washingtonpost.com/politics/2026/1...
181,31,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)