## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-19-01-15-46 +0000,nyt,Trump Hits Campaign Trail as White House Turmo...,https://www.nytimes.com/2026/10/18/us/trump-mi...
1,2026-10-19-01-00-00 +0000,wsj,A Hedge-Fund Billionaire’s Two Bitter Wars—Aga...,https://www.wsj.com/finance/investing/two-sigm...
2,2026-10-19-01-00-00 +0000,wsj,What to Know About the Obscure Private Trust L...,https://www.wsj.com/tech/ai/anthropic-ipo-priv...
3,2026-10-19-00-58-44 +0000,48hills,The city’s a mess. The supes don’t want to que...,https://48hills.org/2026/10/the-citys-a-mess-t...
4,2026-10-19-00-50-31 +0000,startribune,Kirill Kaprizov makes Wild history with winnin...,https://www.startribune.com/minnesota-wild-col...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     30
76   russia     12
126     new     12
46     fire      9
214      he      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
26,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...,92
102,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...,79
103,2026-10-18-17-07-58 +0000,nypost,GOP Senate candidate Mike Rogers breaks with T...,https://nypost.com/2026/10/18/us-news/gop-sen-...,69
135,2026-10-18-14-30-49 +0000,nyt,Zelensky Says Trump Risks ‘Historic Mistake’ I...,https://www.nytimes.com/2026/10/18/world/europ...,65
46,2026-10-18-21-47-28 +0000,nypost,"Trump defends pausing Russian sanctions, says ...",https://nypost.com/2026/10/18/us-news/trump-de...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
26,92,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...
201,45,2026-10-18-02-00-00 +0000,wsj,Republicans across the most competitive House ...,https://www.wsj.com/politics/elections/republi...
68,44,2026-10-18-20-39-53 +0000,nypost,NYC nabe gets horde of brand new Citi Bikes go...,https://nypost.com/2026/10/18/us-news/nyc-nabe...
147,44,2026-10-18-12-12-36 +0000,nypost,Canadian military forced to parachute troops i...,https://nypost.com/2026/10/18/world-news/canad...
153,42,2026-10-18-11-27-23 +0000,nypost,Ukraine targets Putin’s hometown as it launche...,https://nypost.com/2026/10/18/world-news/blaze...
93,34,2026-10-18-18-25-56 +0000,nypost,Pope Leo says he will gradually resume duties ...,https://nypost.com/2026/10/18/world-news/pope-...
111,30,2026-10-18-16-29-22 +0000,nyt,The French City of Limoges Wasn’t Known for Un...,https://www.nytimes.com/2026/10/18/world/franc...
118,27,2026-10-18-16-00-00 +0000,wsj,"From firehouses to farms, Pennsylvania locals ...",https://www.wsj.com/politics/elections/pennsyl...
36,26,2026-10-18-22-46-58 +0000,nypost,Priest gave sermon on spontaneity of death jus...,https://nypost.com/2026/10/18/world-news/pries...
95,24,2026-10-18-17-45-09 +0000,chitri,Photographer attacked by settlers in the West ...,https://www.chicagotribune.com/2026/10/18/phot...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)