## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-02-43-31 +0000,nypost,Massive explosion at crude oil refinery rocks ...,https://nypost.com/2026/03/23/us-news/massive-...
1,2026-03-24-02-41-31 +0000,bbc,"Ultimatums, diplomacy and a trip to Graceland ...",https://www.bbc.com/news/articles/c895v5pq5p1o...
2,2026-03-24-02-41-00 +0000,wsj,Oil May Remain Above $100 in Near Term,https://www.wsj.com/finance/commodities-future...
3,2026-03-24-02-40-00 +0000,wsj,Asian Currencies Weaken Amid Cautious Mood,https://www.wsj.com/finance/currencies/asian-c...
4,2026-03-24-02-34-46 +0000,nypost,US Park Police officer shot in DC: cops,https://nypost.com/2026/03/23/us-news/us-park-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2668/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
16   trump     48
19    iran     45
66     war     25
197    new     16
3      oil     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-03-24-02-10-01 +0000,startribune,Trump says Iran is eager for a deal to end the...,https://www.startribune.com/iran-threatens-to-...,151
301,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,139
286,2026-03-23-13-16-13 +0000,nypost,"Dow rallies 600 points, oil tumbles below $100...",https://nypost.com/2026/03/23/business/dow-fut...,136
273,2026-03-23-14-08-41 +0000,nypost,Trump says ‘we don’t know’ if Iran’s new Supre...,https://nypost.com/2026/03/23/us-news/trump-sa...,135
158,2026-03-23-19-47-08 +0000,wapo,Trump says U.S. is postponing some strikes as ...,https://www.washingtonpost.com/politics/2026/0...,134

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,151,2026-03-24-02-10-01 +0000,startribune,Trump says Iran is eager for a deal to end the...,https://www.startribune.com/iran-threatens-to-...
228,90,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
17,60,2026-03-24-01-54-00 +0000,wsj,"Sen. Markwayne Mullin (R., Okla.) won confirma...",https://www.wsj.com/politics/policy/markwayne-...
117,56,2026-03-23-21-13-47 +0000,bbc,'Like the plane got cut in half': LaGuardia cr...,https://www.bbc.com/news/articles/c78rdze8zvjo...
301,46,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...
83,45,2026-03-23-22-50-50 +0000,nypost,Cops pull rifle from Lamborghini and woman is ...,https://nypost.com/2026/03/23/us-news/cops-pul...
75,44,2026-03-23-23-18-59 +0000,nyt,ICE Agents Fan Out at Airports Across the U.S....,https://www.nytimes.com/2026/03/23/us/ice-agen...
343,39,2026-03-23-07-52-41 +0000,cbc,Air traffic controller heard telling truck to ...,https://www.cbc.ca/news/world/air-canada-expre...
164,37,2026-03-23-19-22-00 +0000,wsj,Oil Futures Retreat On Middle East Conflict Se...,https://www.wsj.com/finance/commodities-future...
209,36,2026-03-23-17-12-46 +0000,nypost,OnlyFans star Sophie Rain mourns Leo Radvinsky...,https://nypost.com/2026/03/23/business/onlyfan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)