## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-10-22-55-25 +0000,nypost,‘Rankings are not the finish line’ says Fremon...,https://nypost.com/2026/03/10/us-news/rankings...
1,2026-03-10-22-52-32 +0000,nypost,"Lead investigator in Nancy Guthrie case, Sheri...",https://nypost.com/2026/03/10/us-news/nancy-gu...
2,2026-03-10-22-51-42 +0000,nyt,U.S. Showers Iran With Bombs in Most Intense S...,https://www.nytimes.com/2026/03/10/world/middl...
3,2026-03-10-22-51-00 +0000,wsj,Deleted Tweet From Energy Secretary Sends Oil ...,https://www.wsj.com/finance/stocks/deleted-twe...
4,2026-03-10-22-50-11 +0000,wapo,"Pentagon says about 140 troops wounded, 8 seve...",https://www.washingtonpost.com/national-securi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
29     iran     72
34      war     53
59    trump     39
41      oil     31
314  prices     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
266,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...,233
325,2026-03-10-03-15-14 +0000,nyt,Trump Seeks to Calm Oil and Gas Markets but Sa...,https://www.nytimes.com/2026/03/09/us/politics...,231
323,2026-03-10-03-24-00 +0000,wsj,"Oil Retreats, Asia Equities Rebound After Trum...",https://www.wsj.com/finance/stocks/oil-retreat...,212
241,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...,200
322,2026-03-10-03-32-18 +0000,nyt,"Trump’s War in Iran, and Rising Gas Prices, Co...",https://www.nytimes.com/2026/03/09/us/politics...,200

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
266,233,2026-03-10-10-08-00 +0000,wsj,"Oil, Gas Prices Retreat After Trump Says End o...",https://www.wsj.com/business/energy-oil/oil-ga...
241,68,2026-03-10-12-17-22 +0000,nypost,Hegseth predicts Tuesday will be ‘most intense...,https://nypost.com/2026/03/10/us-news/hegseth-...
292,52,2026-03-10-09-16-08 +0000,nypost,Five members of Iranian women’s soccer team gr...,https://nypost.com/2026/03/10/world-news/austr...
289,52,2026-03-10-09-30-00 +0000,wsj,New York’s New Superhero: The 37-Year-Old Woma...,https://www.wsj.com/us-news/new-york-trash-cza...
276,43,2026-03-10-10-00-00 +0000,latimes,DTLA law firm co-founder faces California Stat...,https://www.latimes.com/california/story/2026-...
375,41,2026-03-09-23-09-56 +0000,latimes,He was stabbed while charging his car. He died...,https://www.latimes.com/california/story/2026-...
93,38,2026-03-10-20-05-50 +0000,startribune,Walz seeks to shake up Minnesota’s human servi...,https://www.startribune.com/walz-seeks-to-shak...
265,37,2026-03-10-10-30-00 +0000,nypost,Why even Ayatollah Khamenei opposed his impote...,https://nypost.com/2026/03/10/world-news/ayato...
252,37,2026-03-10-11-27-55 +0000,bbc,Family of child injured in Canada school shoot...,https://www.bbc.com/news/articles/c309y25prnlo...
248,33,2026-03-10-11-43-50 +0000,cbc,"Dozens of Haitian civilians killed by police, ...",https://www.cbc.ca/news/world/haiti-drones-hum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)