## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-23-22-54-04 +0000,nypost,"Dad kills his young kids, then himself in tour...",https://nypost.com/2026/09/23/us-news/dad-kill...
1,2026-09-23-22-53-34 +0000,missionlocal,Meet the District 8 candidates: How will you f...,https://missionlocal.org/2026/09/sf-district-8...
2,2026-09-23-22-52-54 +0000,nypost,Karen Bass’ mysterious long-distance boyfriend...,https://nypost.com/2026/09/23/us-news/inside-l...
3,2026-09-23-22-50-19 +0000,nypost,Caltech astronomers capture incredible video o...,https://nypost.com/2026/09/23/us-news/caltech-...
4,2026-09-23-22-47-18 +0000,nypost,Ukraine war must end before AI is used on the ...,https://nypost.com/2026/09/23/world-news/curre...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2543/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     75
159    new     34
45      ai     19
199  house     18
200    ban     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
397,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...,177
403,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,160
211,2026-09-23-16-59-00 +0000,wsj,American oil executives thought they had won t...,https://www.wsj.com/business/energy-oil/trumps...,150
25,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,149
288,2026-09-23-13-53-50 +0000,nypost,China lays out ‘red lines’ for Trump-Xi meetin...,https://nypost.com/2026/09/23/us-news/china-la...,147

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
397,177,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...
225,93,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
74,75,2026-09-23-21-15-02 +0000,nyt,Iran’s president says his country will not giv...,https://www.nytimes.com/live/2026/09/23/world/...
288,72,2026-09-23-13-53-50 +0000,nypost,China lays out ‘red lines’ for Trump-Xi meetin...,https://nypost.com/2026/09/23/us-news/china-la...
334,59,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
169,55,2026-09-23-18-22-13 +0000,latimes,'Mayday! Mayday! Mayday!' Military training je...,https://www.latimes.com/california/story/2026-...
196,54,2026-09-23-17-37-43 +0000,nypost,Energy Secretary Chris Wright rejects outright...,https://nypost.com/2026/09/23/business/us-ener...
22,53,2026-09-23-22-24-25 +0000,nypost,Caleb Flynn’s ex-mistress reveals her new feel...,https://nypost.com/2026/09/23/us-news/caleb-fl...
261,48,2026-09-23-15-26-27 +0000,nyt,"In U.N. Speech, Zelensky Is Expected to Warn R...",https://www.nytimes.com/2026/09/23/world/europ...
205,46,2026-09-23-17-04-19 +0000,nypost,Trump’s Board of Peace announces $2.45B first-...,https://nypost.com/2026/09/23/us-news/trumps-b...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)