## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-21-20-33 +0000,nypost,Bruce Blakeman celebrates 100-year anniversary...,https://nypost.com/2026/07/22/us-news/bruce-bl...
1,2026-07-22-21-20-00 +0000,wsj,Opinion | Donors Make Democrats Crazy,https://www.wsj.com/opinion/donors-make-democr...
2,2026-07-22-21-19-02 +0000,nyt,House Passes Defense Bill Amid Iran War Divide,https://www.nytimes.com/2026/07/22/us/politics...
3,2026-07-22-21-19-00 +0000,wsj,Opinion | Will Democrats Disavow the DSA Platf...,https://www.wsj.com/opinion/will-democrats-dis...
4,2026-07-22-21-18-10 +0000,nyt,Louvre Gallery Reopens After Brazen Jewel Heist,https://www.nytimes.com/2026/07/22/france-louv...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2530/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
89   trump     50
57     new     29
19    iran     24
219   deal     21
20     war     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
12,2026-07-22-21-10-49 +0000,nyt,Iran War Live Updates: Iran Digs In After Late...,https://www.nytimes.com/live/2026/07/22/world/...,135
313,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,130
49,2026-07-22-20-36-21 +0000,chitri,House Republicans push $95 billion package for...,https://www.chicagotribune.com/2026/07/22/hous...,128
214,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,123
210,2026-07-22-14-55-17 +0000,nypost,Trump attends dignified transfer of 4 US troop...,https://nypost.com/2026/07/22/us-news/trump-at...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
12,135,2026-07-22-21-10-49 +0000,nyt,Iran War Live Updates: Iran Digs In After Late...,https://www.nytimes.com/live/2026/07/22/world/...
189,84,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
214,73,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
246,61,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
81,59,2026-07-22-19-25-31 +0000,nypost,Chilling video shows NYC dad calmly strolling ...,https://nypost.com/2026/07/22/us-news/chilling...
383,50,2026-07-22-00-01-00 +0000,wsj,Defense Secretary Pete Hegseth estimated the l...,https://www.wsj.com/politics/national-security...
152,47,2026-07-22-17-07-05 +0000,bbc,I travel four hours on a bus per day - the bus...,https://www.bbc.co.uk/news/articles/clyv4y3xdv...
240,45,2026-07-22-13-19-08 +0000,nypost,Trump vows to destroy one Iranian bridge or po...,https://nypost.com/2026/07/22/us-news/trump-vo...
155,42,2026-07-22-17-02-49 +0000,cbc,Independent autopsy of Black Mississippi teen ...,https://www.cbc.ca/news/world/autopsy-nolan-we...
400,41,2026-07-21-22-57-00 +0000,wsj,Zelensky Removes Ukraine’s Armed-Forces Chief ...,https://www.wsj.com/world/europe/zelensky-remo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)