## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-21-16-54-56 +0000,bbc,Merz vows to keep coalition together for Germa...,https://www.bbc.co.uk/news/articles/cqm27p8enw...
1,2026-09-21-16-54-00 +0000,wsj,Trump Looks to Sideline Canadian Potash With B...,https://www.wsj.com/economy/trade/trump-looks-...
2,2026-09-21-16-53-06 +0000,nyt,How Potential 2028 Presidential Candidates Are...,https://www.nytimes.com/2026/09/21/us/politics...
3,2026-09-21-16-51-56 +0000,nyt,ICE Agents Encountered Austin Man by Chance Be...,https://www.nytimes.com/2026/09/21/us/ice-shoo...
4,2026-09-21-16-51-39 +0000,nyt,"‘America, Who Hurt You?’ Review: Sarah Jones P...",https://www.nytimes.com/2026/09/21/theater/ame...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2335/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
7       trump     39
184       new     19
386  election     12
203     china     12
73      house     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
282,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,127
42,2026-09-21-15-58-53 +0000,bbc,"CNN, MS NOW and Politico file lawsuit against ...",https://www.bbc.co.uk/news/articles/cm0e32rwvr...,98
100,2026-09-21-13-36-06 +0000,cbc,"MS NOW, CNN and Politico sue Trump administrat...",https://www.cbc.ca/news/world/trump-white-hous...,96
74,2026-09-21-14-46-18 +0000,nyt,"CNN, MS NOW and Politico to Sue Trump Administ...",https://www.nytimes.com/2026/09/21/business/me...,93
118,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
282,127,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
145,68,2026-09-21-10-57-58 +0000,chitri,"CNN, MS NOW and Politico sue over denied White...",https://www.chicagotribune.com/2026/09/21/cnn-...
206,62,2026-09-21-05-52-57 +0000,bbc,Lindsay Clancy's ex-husband says he forgave he...,https://www.bbc.co.uk/news/articles/cq5yme200n...
48,52,2026-09-21-15-49-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
118,46,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
230,43,2026-09-21-01-00-00 +0000,wsj,Republicans are pumping money into Senate and ...,https://www.wsj.com/politics/elections/republi...
207,42,2026-09-21-05-50-56 +0000,bbc,US and China discuss AI safety plan ahead of T...,https://www.bbc.co.uk/news/articles/c8vgyzn2d3...
70,41,2026-09-21-14-52-19 +0000,nypost,Paramount reaches settlement with California’s...,https://nypost.com/2026/09/21/media/paramount-...
301,40,2026-09-20-17-48-26 +0000,cbc,Germany's Merz vows to press on with reforms d...,https://www.cbc.ca/news/world/friedrich-merz-g...
51,33,2026-09-21-15-45-20 +0000,nypost,"Woke NYT, 1619 Project scribe sent daughter as...",https://nypost.com/2026/09/21/us-news/woke-nyt...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)