## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-10-08-13-00 +0000,wsj,Europe Has Learned Silence Can Be Golden in Tr...,https://www.wsj.com/world/europe/europe-has-le...
1,2026-06-10-08-03-00 +0000,wsj,Oil Rises on Fresh U.S.-Iran Strikes While Tra...,https://www.wsj.com/finance/commodities-future...
2,2026-06-10-08-00-49 +0000,cbc,Canadian who stole $13M US in crypto bought La...,https://www.cbc.ca/news/world/trenton-johnston...
3,2026-06-10-08-00-00 +0000,cbc,Why some Mexicans feel this World Cup is 'not ...,https://www.cbc.ca/news/world/mexico-soccer-fi...
4,2026-06-10-08-00-00 +0000,cbc,The world has a mosquito problem. Here's how s...,https://www.cbc.ca/news/canada/manitoba/war-on...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2582/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
4         trump     32
13         iran     26
29        world     20
105       maine     20
187  california     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
350,2026-06-09-08-55-09 +0000,cbc,U.S. and Iran trade retaliatory strikes after ...,https://www.cbc.ca/news/world/strait-of-hormuz...,123
61,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...,117
353,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,111
114,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,110
238,2026-06-09-17-01-09 +0000,nypost,Trump claims Iran shooting down US helicopter ...,https://nypost.com/2026/06/09/us-news/iran-sho...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
350,123,2026-06-09-08-55-09 +0000,cbc,U.S. and Iran trade retaliatory strikes after ...,https://www.cbc.ca/news/world/strait-of-hormuz...
61,117,2026-06-10-01-50-00 +0000,wsj,Former Fox News Host Steve Hilton advanced to ...,https://www.wsj.com/politics/elections/republi...
114,78,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
39,78,2026-06-10-03-41-00 +0000,wsj,Democrats in Maine set aside the controversies...,https://www.wsj.com/politics/elections/maine-p...
40,78,2026-06-10-03-36-00 +0000,wsj,"Rep. Nancy Mace, a onetime rising star in the ...",https://www.wsj.com/politics/elections/nancy-m...
215,62,2026-06-09-18-06-40 +0000,latimes,SoFi Stadium workers union announces labor dea...,https://www.latimes.com/sports/soccer/story/20...
284,44,2026-06-09-14-35-13 +0000,nypost,US Navy uses cutting-edge new drone boat to re...,https://nypost.com/2026/06/09/us-news/us-navy-...
189,35,2026-06-09-19-27-36 +0000,nypost,Bitcoin sinks to $61K as Wall Street braces fo...,https://nypost.com/2026/06/09/business/bitcoin...
55,34,2026-06-10-02-29-57 +0000,nypost,Baby-faced killer Karmelo Anthony seen in firs...,https://nypost.com/2026/06/09/us-news/baby-fac...
203,33,2026-06-09-18-52-14 +0000,nypost,Air Canada pilot flew under the radar for 16 y...,https://nypost.com/2026/06/09/world-news/air-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)