## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-19-36-21 +0000,nyt,Iran War Live Updates: Vance Issues Blunt Warn...,https://www.nytimes.com/live/2026/06/18/world/...
1,2026-06-18-19-34-38 +0000,nyt,Colorado Governor Overruled His Own Clemency B...,https://www.nytimes.com/2026/06/18/us/politics...
2,2026-06-18-19-31-24 +0000,nyt,Large Waves Sweep Napping Beachgoers in Califo...,https://www.nytimes.com/2026/06/18/us/college-...
3,2026-06-18-19-30-29 +0000,nypost,Ex-Broadway dancer who fatally tossed old man ...,https://nypost.com/2026/06/18/us-news/ex-broad...
4,2026-06-18-19-30-16 +0000,cbc,Hegseth orders review of U.S. troops deployed ...,https://www.cbc.ca/news/politics/nato-us-hegse...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2664/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     53
12    deal     41
11   trump     37
110    new     19
316  warsh     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
346,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,207
191,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...,181
0,2026-06-18-19-36-21 +0000,nyt,Iran War Live Updates: Vance Issues Blunt Warn...,https://www.nytimes.com/live/2026/06/18/world/...,180
41,2026-06-18-18-25-12 +0000,nypost,Senate Armed Services chairman Roger Wicker ca...,https://nypost.com/2026/06/18/us-news/senate-a...,162
206,2026-06-18-10-40-51 +0000,nypost,At least 12 tankers pass through Strait of Hor...,https://nypost.com/2026/06/18/world-news/three...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
346,207,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
361,109,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
177,74,2026-06-18-12-53-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
149,63,2026-06-18-14-10-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
3,53,2026-06-18-19-30-29 +0000,nypost,Ex-Broadway dancer who fatally tossed old man ...,https://nypost.com/2026/06/18/us-news/ex-broad...
62,47,2026-06-18-17-37-44 +0000,cbc,Ivory Coast's Elye Wahi denied entry to Canada...,https://www.cbc.ca/sports/soccer/worldcup/ivor...
191,44,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...
110,42,2026-06-18-15-51-00 +0000,wsj,Supreme Court Rules Government Can’t Ban All D...,https://www.wsj.com/us-news/law/supreme-court-...
36,40,2026-06-18-18-33-57 +0000,nypost,Millionaire tech CEO’s teen son miraculously s...,https://nypost.com/2026/06/18/us-news/milliona...
196,38,2026-06-18-11-27-00 +0000,wsj,"Republicans are likely asking themselves, “Now...",https://www.wsj.com/politics/french-twist-trum...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)