## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-19-13-00-07 +0000,nyt,"For Israelis and Jews in the U.A.E., an Erodin...",https://www.nytimes.com/2026/10/19/world/middl...
1,2026-10-19-13-00-00 +0000,wsj,Mattel Names Peter Griffith Chief Financial Of...,https://www.wsj.com/business/c-suite/mattel-na...
2,2026-10-19-13-00-00 +0000,missionlocal,Best… poster… ever!,https://missionlocal.org/2026/10/best-poster-e...
3,2026-10-19-12-56-26 +0000,nyt,How Did Life Arise? Three Turning Points in Ea...,https://www.nytimes.com/2026/10/19/science/evo...
4,2026-10-19-12-55-13 +0000,nyt,France’s Far Right Seizes the Moment as Riotin...,https://www.nytimes.com/2026/10/19/france-far-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
54    trump     32
76   russia     16
49       up     10
57     fire     10
444     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
62,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...,107
183,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...,107
236,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...,93
237,2026-10-18-17-07-58 +0000,nypost,GOP Senate candidate Mike Rogers breaks with T...,https://nypost.com/2026/10/18/us-news/gop-sen-...,78
208,2026-10-18-20-46-42 +0000,nyt,Trump Offers Putin Economic Relief in Hopes Th...,https://www.nytimes.com/2026/10/17/business/tr...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
62,107,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...
236,61,2026-10-18-17-08-06 +0000,nypost,Trump’s Russia sanctions pause will pressure P...,https://nypost.com/2026/10/18/us-news/presiden...
154,50,2026-10-19-04-03-00 +0000,wsj,China’s economic growth picked up in the third...,https://www.wsj.com/economy/chinas-economy-exp...
100,44,2026-10-19-09-30-00 +0000,wsj,America’s home-buying market is a house divide...,https://www.wsj.com/economy/housing/americas-n...
244,38,2026-10-18-16-29-22 +0000,nyt,The French City of Limoges Wasn’t Known for Un...,https://www.nytimes.com/2026/10/18/world/franc...
239,38,2026-10-18-16-58-57 +0000,latimes,Southern California fires ease as Santa Ana wi...,https://www.latimes.com/environment/story/2026...
187,37,2026-10-18-22-46-58 +0000,nypost,Priest gave sermon on spontaneity of death jus...,https://nypost.com/2026/10/18/world-news/pries...
17,32,2026-10-19-12-19-36 +0000,nyt,Israeli Police Detain 10 Over Violent Settler ...,https://www.nytimes.com/2026/10/19/world/middl...
48,31,2026-10-19-11-10-06 +0000,nypost,Elon Musk vows to give SpaceX shares to every ...,https://nypost.com/2026/10/19/business/elon-mu...
193,29,2026-10-18-21-47-28 +0000,nypost,"Trump defends pausing Russian sanctions, says ...",https://nypost.com/2026/10/18/us-news/trump-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)