## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-08-20-59-01 +0000,nypost,GOP rallying around unknown salsa seller for M...,https://nypost.com/2026/08/08/us-news/unknown-...
1,2026-08-08-20-57-31 +0000,nyt,More Than 50 Decomposing Bodies Are Found in a...,https://www.nytimes.com/2026/08/07/us/decompos...
2,2026-08-08-20-51-36 +0000,nyt,Think It’s Cool to Wear Fancy Sneakers to Work...,https://www.nytimes.com/2026/08/08/business/de...
3,2026-08-08-20-47-03 +0000,nypost,NYPD chief lauds force for record drop in July...,https://nypost.com/2026/08/08/us-news/nyc-shoo...
4,2026-08-08-20-46-15 +0000,nypost,Retired NYPD chief drowns in his Long Island h...,https://nypost.com/2026/08/08/us-news/retired-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2690/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
134   trump     21
101  senate     12
171    iran     12
279      he      8
230     new      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,70
138,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...,70
72,2026-08-08-15-45-32 +0000,chitri,Todd Blanche is narrowly confirmed as Trump’s ...,https://www.chicagotribune.com/2026/08/08/todd...,62
159,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...,57
137,2026-08-08-08-38-37 +0000,nypost,Senate confirms Todd Blanche as Trump’s attorn...,https://nypost.com/2026/08/08/us-news/todd-bla...,56

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,70,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
159,57,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...
138,49,2026-08-08-08-34-00 +0000,wsj,The Senate narrowly confirmed Todd Blanche as ...,https://www.wsj.com/politics/policy/blanche-co...
32,41,2026-08-08-19-18-57 +0000,bbc,"Hormuz talks positive, Oman says, as Iran warn...",https://www.bbc.co.uk/news/articles/c934j5y2lq...
66,35,2026-08-08-16-03-18 +0000,chitri,Hunter Biden says his father’s prostate cancer...,https://www.chicagotribune.com/2026/08/08/joe-...
40,31,2026-08-08-18-56-11 +0000,nypost,Pro-cop activist who was ‘dead’ for 2 minutes ...,https://nypost.com/2026/08/08/us-news/scott-lo...
11,27,2026-08-08-20-28-49 +0000,nypost,Husband of NY Times writer behind ‘1619 Projec...,https://nypost.com/2026/08/08/us-news/nikole-h...
50,27,2026-08-08-17-58-42 +0000,bbc,US offers $1bn to Colombia on new right-wing p...,https://www.bbc.co.uk/news/articles/cy9wy3y0e5...
48,27,2026-08-08-18-06-25 +0000,bbc,Child among three killed in Russian missile at...,https://www.bbc.co.uk/news/articles/cz7dy8gq99...
144,26,2026-08-08-08-00-00 +0000,cbc,'I woke up and I had lost the baby': Miscarria...,https://www.cbc.ca/news/world/gaza-miscarriage...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)