## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-25-10-05-00 +0000,wsj,Euro Could Struggle to Recover Vs Dollar as En...,https://www.wsj.com/finance/currencies/asian-c...
1,2026-03-25-10-01-40 +0000,nyt,"Pentagon Orders 2,000 Airborne Troops to Middl...",https://www.nytimes.com/live/2026/03/24/world/...
2,2026-03-25-10-01-38 +0000,nyt,Oil Prices Tumble as Trump Shows Eagerness to ...,https://www.nytimes.com/2026/03/24/business/oi...
3,2026-03-25-10-00-00 +0000,nypost,New details about forgotten Long Island hero k...,https://nypost.com/2026/03/25/us-news/new-deta...
4,2026-03-25-10-00-00 +0000,nypost,Mike Waltz recalls chilling war story where he...,https://nypost.com/2026/03/25/us-news/mike-wal...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2640/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
20   iran     51
16  trump     40
38    war     28
14    oil     20
21    new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
231,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,159
5,2026-03-25-10-00-00 +0000,nypost,Trump has given Israel’s Netanyahu ‘the busine...,https://nypost.com/2026/03/25/us-news/trump-ha...,155
166,2026-03-24-22-35-03 +0000,nypost,US sends 15-point plan to end war with Iran as...,https://nypost.com/2026/03/24/world-news/us-se...,150
61,2026-03-25-07-52-17 +0000,bbc,Oil price falls as Trump talks up Iran peace n...,https://www.bbc.com/news/articles/c995xp4jxj2o...,144
243,2026-03-24-20-13-15 +0000,nyt,Oil Prices Rise After Iran Denies Talks With T...,https://www.nytimes.com/2026/03/24/business/oi...,136

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
231,159,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...
347,82,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
17,56,2026-03-25-09-40-00 +0000,wsj,Oil Falls Below $100 as Markets Greet Middle E...,https://www.wsj.com/finance/stocks/oil-falls-b...
185,56,2026-03-24-21-56-00 +0000,wsj,GOP senators have made an offer to Democrats t...,https://www.wsj.com/politics/policy/gop-senato...
145,46,2026-03-24-23-33-00 +0000,wsj,The Defense Department introduced new restrict...,https://www.wsj.com/politics/national-security...
268,44,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
345,44,2026-03-24-14-44-28 +0000,nypost,UK will lead ‘Hormuz Coalition’ to reopen stra...,https://nypost.com/2026/03/24/world-news/iran-...
154,43,2026-03-24-23-14-38 +0000,cbc,Air Canada CEO summoned to Ottawa over English...,https://www.cbc.ca/news/canada/air-canada-ceo-...
108,41,2026-03-25-02-40-23 +0000,nypost,Texas elementary school ‘dads club’ gifts Jeep...,https://nypost.com/2026/03/24/us-news/texas-el...
6,39,2026-03-25-09-59-06 +0000,nyt,T.S.A. Tipped Off ICE Agents Before Arrests at...,https://www.nytimes.com/2026/03/24/us/tsa-data...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)