## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-01-22-14 +0000,wapo,America’s 250th celebrations marked by severe ...,https://www.washingtonpost.com/nation/2026/07/...
1,2026-07-05-01-19-30 +0000,nyt,Nancy Pelosi’s Husband Could Face Charge Over ...,https://www.nytimes.com/2026/07/04/us/paul-pel...
2,2026-07-05-01-19-04 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/04/us/ame...
3,2026-07-05-01-18-14 +0000,nyt,These Runners Celebrate July 4 at the Mount Ma...,https://www.nytimes.com/live/2026/07/04/us/ame...
4,2026-07-05-01-04-48 +0000,nyt,Crowds Evacuated as Storms Menace Washington A...,https://www.nytimes.com/2026/07/04/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
32     trump     23
22      july     19
38   funeral     15
1         th     14
327     iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,102
11,2026-07-05-00-46-17 +0000,cbc,Evacuation ordered at National Mall as storms ...,https://www.cbc.ca/news/world/national-mall-ev...,80
109,2026-07-04-11-43-17 +0000,nyt,"Will Iran’s New Supreme Leader, Mojtaba Khamen...",https://www.nytimes.com/2026/07/04/world/middl...,79
6,2026-07-05-01-00-38 +0000,nyt,TV coverage of the Fourth of July will emphasi...,https://www.nytimes.com/live/2026/07/04/us/ame...,71
26,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,102,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
26,71,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
159,43,2026-07-04-04-50-06 +0000,bbc,Watch: Taylor Swift and Travis Kelce wed in NY...,https://www.bbc.co.uk/news/videos/cewqpdgqj0ko...
11,38,2026-07-05-00-46-17 +0000,cbc,Evacuation ordered at National Mall as storms ...,https://www.cbc.ca/news/world/national-mall-ev...
158,36,2026-07-04-05-25-47 +0000,nypost,Iranians chant ‘Death to America’ as crowds mo...,https://nypost.com/2026/07/04/us-news/iranians...
66,34,2026-07-04-17-57-13 +0000,nypost,New gold rush as massive mining operation look...,https://nypost.com/2026/07/04/business/new-gol...
30,28,2026-07-04-22-52-34 +0000,latimes,Paul Pelosi faces possible hit-and-run charge ...,https://www.latimes.com/california/story/2026-...
160,28,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
39,25,2026-07-04-22-07-33 +0000,nypost,"White supremacist group marches on Washington,...",https://nypost.com/2026/07/04/us-news/white-su...
134,24,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)