## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-02-23-15-39 +0000,nypost,Massive hawk miraculously survives 200 miles t...,https://nypost.com/2026/07/02/us-news/massive-...
1,2026-07-02-23-11-45 +0000,nyt,MAGA Base Stays Quiet After Trump Reports Bill...,https://www.nytimes.com/2026/07/02/us/politics...
2,2026-07-02-23-11-32 +0000,nypost,Young Hamptons revellers cough up big bucks fo...,https://nypost.com/2026/07/02/business/young-h...
3,2026-07-02-23-10-46 +0000,nypost,Man’s skeletonized body found wedged inside co...,https://nypost.com/2026/07/02/us-news/mans-ske...
4,2026-07-02-23-09-33 +0000,nypost,FBI infiltrated Gavin Newsom’s inner circle by...,https://nypost.com/2026/07/02/us-news/gavin-ne...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2566/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     40
236     new     14
24       up     13
337  russia     12
56   killed     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
260,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,92
317,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...,87
286,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...,82
331,2026-07-02-00-20-33 +0000,nypost,Ex-Trump adviser Kellogg says prez should brac...,https://nypost.com/2026/07/01/world-news/keith...,80
309,2026-07-02-03-11-06 +0000,nypost,Tucker Carlson says he’s starting a new politi...,https://nypost.com/2026/07/01/us-news/tucker-c...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
260,92,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...
191,61,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
129,50,2026-07-02-18-23-50 +0000,nyt,June Jobs Report Shows US Labor Market Making ...,https://www.nytimes.com/2026/07/02/business/ec...
263,47,2026-07-02-10-21-05 +0000,cbc,"Deadly, large-scale Russian attack shakes Kyiv...",https://www.cbc.ca/news/world/missile-drone-at...
13,46,2026-07-02-22-57-52 +0000,nypost,"Up-and-coming NYC drill rapper, dad of 3-year-...",https://nypost.com/2026/07/02/us-news/nyc-dril...
312,44,2026-07-02-03-00-00 +0000,wsj,Europe Learns It’s Hard to Start a Trade War W...,https://www.wsj.com/world/china/europe-learns-...
337,44,2026-07-01-23-43-03 +0000,latimes,SoCal boy was killed by massive tree branch at...,https://www.latimes.com/california/story/2026-...
42,40,2026-07-02-21-49-42 +0000,nypost,Massachusetts city orders curfew ahead of Cape...,https://nypost.com/2026/07/02/us-news/massachu...
300,37,2026-07-02-05-14-51 +0000,nypost,"Bodies of Florida beauty queen, boyfriend foun...",https://nypost.com/2026/07/02/world-news/flori...
210,37,2026-07-02-13-57-46 +0000,nypost,Michigan Dem Senate front-runner Dr. Abdul El-...,https://nypost.com/2026/07/02/us-news/michigan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)