## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-22-18-12 +0000,nypost,West Hollywood staple WeHo Bistro closed over ...,https://nypost.com/2026/06/12/us-news/west-hol...
1,2026-06-12-22-01-42 +0000,latimes,Paramount's $111-billion Warner Bros. acquisit...,https://www.latimes.com/entertainment-arts/bus...
2,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...
3,2026-06-12-21-59-38 +0000,nyt,"Despite Trump Claims, Spencer Pratt Seems to A...",https://www.nytimes.com/2026/06/12/us/election...
4,2026-06-12-21-57-45 +0000,bbc,Warner Bros $111bn sale to Paramount approved ...,https://www.bbc.com/news/articles/cjwgled9jxwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22  spacex     35
19   world     34
63     cup     25
27   trump     25
43    iran     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
172,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...,149
2,2026-06-12-22-00-52 +0000,bbc,Elon Musk becomes world's first trillionaire a...,https://www.bbc.com/news/articles/c4gypy3wwl7o...,147
55,2026-06-12-20-38-47 +0000,nyt,Elon Musk Becomes World’s First Trillionaire a...,https://www.nytimes.com/2026/06/12/technology/...,137
8,2026-06-12-21-54-23 +0000,nypost,World Cup chaos expected as travel plans for 5...,https://nypost.com/2026/06/12/us-news/world-cu...,118
297,2026-06-12-08-06-06 +0000,wsj,SpaceX Shares Close Up 19% in Historic Debut a...,https://www.wsj.com/livecoverage/spacex-ipo-st...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
172,149,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...
75,91,2026-06-12-20-14-32 +0000,nyt,"Oil Falls, Stocks Rise as Trump Signals Iran P...",https://www.nytimes.com/2026/06/11/business/oi...
8,74,2026-06-12-21-54-23 +0000,nypost,World Cup chaos expected as travel plans for 5...,https://nypost.com/2026/06/12/us-news/world-cu...
256,65,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...
343,60,2026-06-12-01-00-00 +0000,wsj,When Trump meets his counterparts at next week...,https://www.wsj.com/economy/global/the-global-...
250,48,2026-06-12-11-00-00 +0000,nypost,Texas Dem bragged about getting career crimina...,https://nypost.com/2026/06/12/us-news/texas-de...
296,42,2026-06-12-08-16-52 +0000,nypost,White House fires back at Ariana Grande after ...,https://nypost.com/2026/06/12/us-news/white-ho...
174,38,2026-06-12-15-45-28 +0000,cbc,Ex-South Korean president sentenced for sendin...,https://www.cbc.ca/news/world/south-korea-yoon...
145,37,2026-06-12-17-17-37 +0000,nypost,California accused of blocking federal voter r...,https://nypost.com/2026/06/12/us-news/californ...
355,35,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)