## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-19-05-36-36 +0000,bbc,Trump says he is banning CNN and Politico from...,https://www.bbc.co.uk/news/articles/c6e30580jq...
1,2026-09-19-05-32-51 +0000,nypost,Ed Sheeran set to return to stage for 1st time...,https://nypost.com/2026/09/19/us-news/ed-sheer...
2,2026-09-19-05-27-27 +0000,nypost,"Walmart customer, 77, beaten to death by paren...",https://nypost.com/2026/09/19/us-news/walmart-...
3,2026-09-19-05-07-52 +0000,nypost,Cuba hit with another blackout as millions acr...,https://nypost.com/2026/09/19/world-news/cuba-...
4,2026-09-19-04-56-01 +0000,nypost,Dramatic new ad blasts Nithya Raman’s stance o...,https://nypost.com/2026/09/19/us-news/nithya-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2578/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
0   trump     56
1      he     20
72     ai     19
6   house     18
42    new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
97,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...,169
102,2026-09-18-21-39-00 +0000,wsj,President Trump said that Donald Trump Jr. rei...,https://www.wsj.com/politics/trump-says-his-so...,159
86,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...,155
182,2026-09-18-18-56-47 +0000,nyt,Judge Who Struck Down Trump’s Compensation Fun...,https://www.nytimes.com/2026/09/18/us/politics...,149
162,2026-09-18-19-27-19 +0000,chitri,"Pres. Donald Trump says he is banning CNN, MSN...",https://www.chicagotribune.com/2026/09/18/trum...,131

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
97,169,2026-09-18-21-43-00 +0000,wsj,AI juggernaut Anthropic’s IPO is coming later ...,https://www.wsj.com/tech/ai/anthropics-ipo-wil...
321,71,2026-09-18-11-49-46 +0000,bbc,Lindsay Clancy holdout juror says he had no do...,https://www.bbc.co.uk/news/articles/c54g7jdmw0...
204,69,2026-09-18-17-51-00 +0000,wsj,A new Federal Reserve inquiry into the 2023 co...,https://www.wsj.com/economy/central-banking/ne...
86,50,2026-09-18-22-17-00 +0000,wsj,President Trump said on Friday he is banning C...,https://www.wsj.com/politics/policy/trump-says...
339,49,2026-09-18-10-54-02 +0000,nypost,Warren Buffett steps down as Berkshire chairma...,https://nypost.com/2026/09/18/business/berkshi...
377,47,2026-09-18-08-56-00 +0000,wsj,The Bank of Japan lifted its benchmark interes...,https://www.wsj.com/economy/central-banking/ba...
259,47,2026-09-18-15-15-22 +0000,nypost,Top soccer bosses demand slice of FIFA’s $6B p...,https://nypost.com/2026/09/18/business/top-soc...
163,46,2026-09-18-19-24-19 +0000,nyt,"Rejecting Trump, South Korean Leader Says He W...",https://www.nytimes.com/2026/09/18/world/asia/...
242,45,2026-09-18-15-59-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
116,42,2026-09-18-21-11-47 +0000,nypost,Trump claims Don Jr. paid back Russian oligarc...,https://nypost.com/2026/09/18/us-news/presiden...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)