## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-15-13-20-11 +0000,nypost,Kamala Harris torched for progressive wishlist...,https://nypost.com/2026/05/15/us-news/kamala-h...
1,2026-05-15-13-18-38 +0000,nyt,"Despite Tensions, China Greets Trump With Pomp...",https://www.nytimes.com/2026/05/15/world/asia/...
2,2026-05-15-13-17-40 +0000,nyt,Replacing a Royal Hand-Me-Down That Finally Fr...,https://www.nytimes.com/2026/05/15/arts/music/...
3,2026-05-15-13-15-56 +0000,nyt,"‘For Example, Putin’: How Xi Used a Private Ga...",https://www.nytimes.com/2026/05/15/world/asia/...
4,2026-05-15-13-15-05 +0000,startribune,Trump weighs Taiwan arms package after summit ...,https://www.startribune.com/trump-insists-us-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
11   trump     56
9    china     33
22      xi     27
207    new     18
306    out     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
111,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...,159
128,2026-05-15-06-04-46 +0000,nypost,Extravagant Trump-Xi tea menu revealed — as th...,https://nypost.com/2026/05/15/us-news/extravag...,152
161,2026-05-15-01-30-15 +0000,nypost,Trump says China will ‘invest hundreds of bill...,https://nypost.com/2026/05/14/us-news/china-wi...,150
226,2026-05-14-21-36-36 +0000,nyt,Oil Prices Waver as Trump Meets China’s Xi to ...,https://www.nytimes.com/2026/05/14/business/oi...,144
94,2026-05-15-09-00-24 +0000,nypost,6 key takeaways from historic Trump-Xi China s...,https://nypost.com/2026/05/15/us-news/trump-xi...,140

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
111,159,2026-05-15-07-43-59 +0000,nypost,Trump and Xi’s footing was a big ‘tell’ on how...,https://nypost.com/2026/05/15/us-news/trump-an...
294,63,2026-05-14-18-13-00 +0000,wsj,Pentagon leaders say they could start running ...,https://www.wsj.com/politics/national-security...
300,48,2026-05-14-17-52-46 +0000,nyt,Iran Lets Chinese Ships Through Strait of Horm...,https://www.nytimes.com/live/2026/05/14/us/tru...
59,42,2026-05-15-10-24-00 +0000,startribune,Wild offseason questions: Will a goalie be tra...,https://www.startribune.com/minnesota-wild-pos...
66,40,2026-05-15-10-00-00 +0000,nypost,Why the hottest tech IPO of the year matters f...,https://nypost.com/2026/05/15/business/why-the...
284,34,2026-05-14-18-45-57 +0000,nyt,"Who Is Wes Streeting, the Cabinet Minister Who...",https://www.nytimes.com/2026/05/14/world/europ...
113,34,2026-05-15-07-34-35 +0000,nypost,Supreme Court preserves access to widely used ...,https://nypost.com/2026/05/15/us-news/supreme-...
193,34,2026-05-14-23-12-03 +0000,nyt,U.S. Border Patrol Chief Resigns in Latest Hom...,https://www.nytimes.com/2026/05/14/us/politics...
143,33,2026-05-15-04-06-29 +0000,nyt,5 Key Moments During the California Governor D...,https://www.nytimes.com/2026/05/15/us/californ...
260,32,2026-05-14-20-18-23 +0000,nypost,Beverly Hills Hotel locked in brutal war with ...,https://nypost.com/2026/05/14/business/beverly...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)