## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-07-16-49 +0000,bbc,Annual UK borrowing falls by £20bn but Iran wa...,https://www.bbc.com/news/articles/ckge5291152o...
1,2026-04-23-07-07-00 +0000,wsj,Dollar Rises on Signs of Continued Iran War Te...,https://www.wsj.com/finance/currencies/asian-c...
2,2026-04-23-06-57-00 +0000,wsj,Philippine Central Bank Raises Rates as Mideas...,https://www.wsj.com/economy/central-banking/ph...
3,2026-04-23-06-51-00 +0000,wsj,Nestle Reports Drop in Sales Amid Strategic Ov...,https://www.wsj.com/business/nestle-reports-dr...
4,2026-04-23-06-48-00 +0000,wsj,"Eurozone Bond Yields Rise, Tracking U.S. Treas...",https://www.wsj.com/finance/investing/jgbs-con...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
5          iran     37
199       trump     33
6           war     24
65          new     23
135  california     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
138,2026-04-22-21-43-54 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...,126
60,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,121
336,2026-04-22-10-45-39 +0000,bbc,Oil prices fluctuate as Trump extends Iran war...,https://www.bbc.com/news/articles/c995dkl4dvvo...,121
298,2026-04-22-14-36-22 +0000,nypost,United Airlines says it will raise summer fare...,https://nypost.com/2026/04/22/business/united-...,116
367,2026-04-22-08-38-11 +0000,bbc,UK inflation rises after Iran war pushes up fu...,https://www.bbc.com/news/articles/cnv8l17r51ro...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
138,126,2026-04-22-21-43-54 +0000,nyt,How the War Powers Act Could Pressure Trump to...,https://www.nytimes.com/2026/04/22/us/politics...
123,76,2026-04-22-22-11-28 +0000,nyt,"Heidi O’Neill, Formerly of Nike, Will Be New L...",https://www.nytimes.com/2026/04/22/business/lu...
36,61,2026-04-23-04-46-09 +0000,nypost,California governor’s race debate shows why el...,https://nypost.com/2026/04/23/us-news/californ...
321,55,2026-04-22-12-50-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
76,48,2026-04-23-00-54-06 +0000,nyt,Iran Says It Seized Two Ships Near the Strait ...,https://www.nytimes.com/2026/04/22/world/middl...
199,48,2026-04-22-19-09-00 +0000,wsj,"Rep. David Scott, a Georgia Democrat who spent...",https://www.wsj.com/politics/david-scott-georg...
60,46,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
64,44,2026-04-23-01-42-00 +0000,wsj,John Phelan has been fired as Navy secretary a...,https://www.wsj.com/politics/national-security...
47,43,2026-04-23-02-57-59 +0000,latimes,"Santa Monica nonprofit official, wife found de...",https://www.latimes.com/california/story/2026-...
113,40,2026-04-22-22-29-00 +0000,wsj,Predictions marketplace Kalshi said it had fin...,https://www.wsj.com/politics/policy/prediction...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)