## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-04-18-15-13 +0000,nyt,JPMorgan Again Entangled in a Soccer Fiasco,https://www.nytimes.com/2026/08/04/world/europ...
1,2026-08-04-18-13-05 +0000,startribune,Breaking: Jury rules Medtronic owes $88M in fi...,https://www.startribune.com/jury-federal-bellw...
2,2026-08-04-18-08-33 +0000,nyt,More Than 170 Migrants Rescued From Burning Bo...,https://www.nytimes.com/2026/08/04/world/europ...
3,2026-08-04-18-07-24 +0000,chitri,"Hormel’s next CEO has dishwashing roots, and a...",https://www.chicagotribune.com/2026/08/04/horm...
4,2026-08-04-18-06-38 +0000,startribune,Opinion | Making daylight saving time permanen...,https://www.startribune.com/daylight-savings-d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2556/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
164   trump     42
74     iran     28
303     new     24
93   hormuz     15
215    deal     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
203,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,136
354,2026-08-03-19-16-37 +0000,nypost,Trump gives Iran ‘last chance’ to sign deal be...,https://nypost.com/2026/08/03/us-news/trump-gi...,135
303,2026-08-03-21-49-00 +0000,wsj,"Trump discusses Jeanine Pirro’s removal, Iran ...",https://www.wsj.com/politics/policy/trump-disc...,132
266,2026-08-04-01-19-29 +0000,nyt,An Emerging Deal Between Iran and Oman to Reop...,https://www.nytimes.com/2026/08/03/us/politics...,124
301,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
203,136,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...
176,84,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...
330,76,2026-08-03-20-40-00 +0000,wsj,Two holdout GOP senators who were blocking act...,https://www.wsj.com/politics/policy/blanche-fo...
344,62,2026-08-03-19-49-32 +0000,nypost,Trump says Jeanine Pirro ‘choked’ by tossing o...,https://nypost.com/2026/08/03/us-news/trump-sa...
233,53,2026-08-04-07-25-51 +0000,wsj,"Stock Market Today: Stocks Leap, Oil Slides Af...",https://www.wsj.com/livecoverage/stock-market-...
326,47,2026-08-03-20-50-22 +0000,nypost,"US manufacturing hits 4-year high, with AI bui...",https://nypost.com/2026/08/03/business/us-manu...
183,46,2026-08-04-10-59-00 +0000,wsj,President Trump told embattled Rep. Max Miller...,https://www.wsj.com/politics/elections/trump-w...
177,46,2026-08-04-11-05-47 +0000,nypost,"Iran, Oman near deal to reopen Strait of Hormu...",https://nypost.com/2026/08/04/us-news/iran-oma...
255,46,2026-08-04-02-38-00 +0000,nypost,Hasan Piker marvels at ‘white dude bros’ suppo...,https://nypost.com/2026/08/03/us-news/abdul-el...
276,41,2026-08-04-00-00-00 +0000,wsj,A little-used Fed backstop is being put to a u...,https://www.wsj.com/economy/central-banking/wh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)