## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-00-06-17 +0000,cbc,The U.S. says it's open. Iran says it's closed...,https://www.cbc.ca/news/world/strait-of-hormuz...
1,2026-06-22-00-03-17 +0000,nypost,Hunt for Justin Bieber lookalike who tried to ...,https://nypost.com/2026/06/21/us-news/hunt-for...
2,2026-06-22-00-00-00 +0000,wsj,The Biggest Risks Threatening This Highflying ...,https://www.wsj.com/finance/stocks/the-biggest...
3,2026-06-21-23-55-06 +0000,bbc,First round of direct US-Iran talks since deal...,https://www.bbc.com/news/articles/cwy0q41v1lzo...
4,2026-06-21-23-54-20 +0000,cbc,Trump-endorsed right-wing candidate leads in t...,https://www.cbc.ca/news/world/colombia-preside...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
1     iran     26
33   trump     22
26   talks     15
96   world     11
109     up      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
118,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...,98
63,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,97
23,2026-06-21-22-36-02 +0000,wapo,JD Vance holds peace talks with Iran as Trump ...,https://www.washingtonpost.com/world/2026/06/2...,89
157,2026-06-21-09-13-54 +0000,cbc,Trump threats shake up U.S.-Iran talks in Swit...,https://www.cbc.ca/news/world/jd-vance-switzer...,88
91,2026-06-21-17-04-26 +0000,nyt,As Vance Offers Iran ‘Outstretched Hand’ in Ta...,https://www.nytimes.com/2026/06/21/world/middl...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
118,98,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...
153,33,2026-06-21-09-45-57 +0000,bbc,Dutch royals enjoy two big results in one Worl...,https://www.bbc.com/sport/football/articles/c4...
38,29,2026-06-21-21-24-35 +0000,nypost,"Race against time in fight with 500,000-square...",https://nypost.com/2026/06/21/us-news/85m-poun...
63,28,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
84,25,2026-06-21-17-32-12 +0000,nypost,NYC voters are fed up with the Democratic Part...,https://nypost.com/2026/06/21/us-news/nyc-vote...
122,24,2026-06-21-13-41-12 +0000,nypost,Vance says US willing to ‘fundamentally transf...,https://nypost.com/2026/06/21/us-news/vance-sa...
167,23,2026-06-21-09-00-00 +0000,wsj,Jay Clayton has been a loyal ally and golf bud...,https://www.wsj.com/politics/policy/the-would-...
108,22,2026-06-21-15-46-09 +0000,nypost,Sore loser Texas Rep. Jasmine Crockett says sh...,https://nypost.com/2026/06/21/us-news/jasmine-...
96,22,2026-06-21-16-23-36 +0000,nyt,Keir Starmer Reflects on ‘Political Challenges...,https://www.nytimes.com/2026/06/21/world/europ...
80,22,2026-06-21-17-59-08 +0000,nypost,Christian cop suspended for asking questions a...,https://nypost.com/2026/06/21/world-news/chris...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)