## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-20-00-11-02 +0000,nyt,Amazon’s Movie Arm Abandons Film About OpenAI,https://www.nytimes.com/2026/06/19/business/me...
1,2026-06-20-00-00-00 +0000,wsj,California Gov. Gavin Newsom has turned a Just...,https://www.wsj.com/politics/policy/california...
2,2026-06-19-23-51-26 +0000,nyt,Oil Prices Rise as U.S.-Iran Deal Faces Tests,https://www.nytimes.com/2026/06/19/business/oi...
3,2026-06-19-23-50-47 +0000,nyt,Mideast Live Updates: Israel Commits to New Le...,https://www.nytimes.com/live/2026/06/19/world/...
4,2026-06-19-23-50-24 +0000,nyt,"A New Air Force One, via Qatar, Nears Its Firs...",https://www.nytimes.com/2026/06/19/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
19      iran     37
235    trump     25
20      deal     21
764  burnham     19
336    world     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
287,2026-06-19-02-51-00 +0000,wsj,Vance Slams Israeli Critics of Trump’s Deal Wi...,https://www.wsj.com/world/middle-east/vance-to...,100
280,2026-06-19-04-12-07 +0000,bbc,"In Trump's shadow, Vance becomes face of Iran ...",https://www.bbc.com/news/articles/cx23jr133lwo...,98
258,2026-06-19-08-00-00 +0000,cbc,Trump routinely trashes the Obama-era Iran nuc...,https://www.cbc.ca/news/world/trump-iran-deal-...,97
121,2026-06-19-16-37-27 +0000,nyt,Trump’s Iran Deal Is Off to a Chaotic Start,https://www.nytimes.com/2026/06/19/world/middl...,94
296,2026-06-19-02-10-00 +0000,wsj,The Pentagon needs $80 billion to cover costs ...,https://www.wsj.com/politics/national-security...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
287,100,2026-06-19-02-51-00 +0000,wsj,Vance Slams Israeli Critics of Trump’s Deal Wi...,https://www.wsj.com/world/middle-east/vance-to...
229,76,2026-06-19-09-54-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...
78,59,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...
114,57,2026-06-19-17-00-00 +0000,wsj,Warsh’s first test as Fed chairman will be rea...,https://www.wsj.com/economy/central-banking/fe...
296,57,2026-06-19-02-10-00 +0000,wsj,The Pentagon needs $80 billion to cover costs ...,https://www.wsj.com/politics/national-security...
299,51,2026-06-19-01-42-00 +0000,wsj,The architects of California’s proposed billio...,https://www.wsj.com/politics/policy/union-behi...
131,42,2026-06-19-15-46-59 +0000,nypost,Houston TV meteorologist whines she never won ...,https://nypost.com/2026/06/19/media/houston-tv...
93,41,2026-06-19-18-20-00 +0000,wsj,The Fed’s vice chair of supervision spoke at a...,https://www.wsj.com/economy/central-banking/to...
150,41,2026-06-19-14-53-52 +0000,bbc,Lebanon says Israeli strikes kill 47 as Israel...,https://www.bbc.com/news/articles/c23ymz1n9rmo...
270,36,2026-06-19-06-27-34 +0000,bbc,Andy Burnham's win means change at the top for...,https://www.bbc.com/news/articles/c4gy2r2wjm1o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)