## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-15-20-48-28 +0000,nypost,John Gotti’s grandson finally behind bars afte...,https://nypost.com/2026/08/15/us-news/john-got...
1,2026-08-15-20-48-05 +0000,nyt,$10 Million in Gold Found Buried Under Former ...,https://www.nytimes.com/2026/08/15/world/europ...
2,2026-08-15-20-32-33 +0000,bbc,Morocco detains dozens of migrants trying to c...,https://www.bbc.co.uk/news/articles/ckg44x2ey1...
3,2026-08-15-20-30-44 +0000,nypost,Here are the states where medical malpractice ...,https://nypost.com/2026/08/15/us-news/medical-...
4,2026-08-15-20-28-54 +0000,48hills,"Monét X Change: retired party girl, current co...",https://48hills.org/2026/08/monet-x-change-ret...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2439/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
228       trump     23
145  earthquake      8
405         new      8
386        dead      7
28        where      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
115,2026-08-15-09-38-51 +0000,nypost,"At least 38 dead, buildings toppled after magn...",https://nypost.com/2026/08/15/world-news/indon...,47
68,2026-08-15-15-44-40 +0000,nypost,Trump posts AI image of himself seizing Irania...,https://nypost.com/2026/08/15/us-news/trump-po...,45
26,2026-08-15-19-39-00 +0000,wsj,Trump Family’s World Liberty Financial Gets Pr...,https://www.wsj.com/finance/trump-familys-worl...,44
58,2026-08-15-17-25-48 +0000,chitri,US pulls last aircraft carrier in Asia as Trum...,https://www.chicagotribune.com/2026/08/15/us-p...,43
167,2026-08-14-23-30-43 +0000,chitri,"Amid latest Illinois storm damage, Gov. Pritzk...",https://www.chicagotribune.com/2026/08/14/illi...,43

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
115,47,2026-08-15-09-38-51 +0000,nypost,"At least 38 dead, buildings toppled after magn...",https://nypost.com/2026/08/15/world-news/indon...
68,45,2026-08-15-15-44-40 +0000,nypost,Trump posts AI image of himself seizing Irania...,https://nypost.com/2026/08/15/us-news/trump-po...
185,42,2026-08-14-22-22-00 +0000,wsj,"After reports of food shortages, broken toilet...",https://www.wsj.com/politics/national-security...
40,33,2026-08-15-18-52-26 +0000,nypost,Wisconsin Dem calls out party for abandoning r...,https://nypost.com/2026/08/15/us-news/dem-cand...
30,32,2026-08-15-19-26-49 +0000,nypost,Deranged Michigan gunman Chad Hickman who kill...,https://nypost.com/2026/08/15/us-news/chad-hic...
88,32,2026-08-15-12-00-00 +0000,nypost,‘Iran’s black widow’ faces multiple death sent...,https://nypost.com/2026/08/15/us-news/irans-bl...
12,26,2026-08-15-20-08-06 +0000,nypost,Acting Navy secretary salutes USS Abraham Linc...,https://nypost.com/2026/08/15/us-news/dire-rep...
188,26,2026-08-14-22-09-00 +0000,wsj,A son of former Mexican President Andrés Manue...,https://www.wsj.com/world/americas/u-s-cancels...
44,25,2026-08-15-18-27-45 +0000,nyt,Democrats Make South Carolina the First Contes...,https://www.nytimes.com/2026/08/15/us/politics...
187,25,2026-08-14-22-13-32 +0000,nypost,New York Mag fires Mamdani-loving writer Ross ...,https://nypost.com/2026/08/14/media/new-york-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)