## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-28-20-55-48 +0000,nyt,No Kings Protests Held Across the U.S.: Photos...,https://www.nytimes.com/2026/03/28/us/no-kings...
1,2026-03-28-20-55-02 +0000,startribune,Iran-backed Houthis enter the month-old war an...,https://www.startribune.com/israel-says-it-int...
2,2026-03-28-20-51-57 +0000,bbc,Iran-backed Houthis join war with attack again...,https://www.bbc.com/news/articles/cd6l5n8jv4yo...
3,2026-03-28-20-51-21 +0000,startribune,Live: Totino-Grace wins 3A crown; Hills-Beaver...,https://www.startribune.com/minnesota-boys-bas...
4,2026-03-28-20-50-02 +0000,nypost,Desperate California man breaks IN to jail to ...,https://nypost.com/2026/03/28/us-news/desperat...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
11     war     27
7     iran     25
97   trump     20
263   will     11
1    kings     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
57,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...,111
6,2026-03-28-20-49-30 +0000,nyt,Iran War Live Updates: U.S. Marines Arrive in ...,https://www.nytimes.com/live/2026/03/28/world/...,100
24,2026-03-28-20-02-09 +0000,wapo,Iran-backed Houthis in Yemen launch attack on ...,https://www.washingtonpost.com/world/2026/03/2...,89
2,2026-03-28-20-51-57 +0000,bbc,Iran-backed Houthis join war with attack again...,https://www.bbc.com/news/articles/cd6l5n8jv4yo...,85
69,2026-03-28-16-55-01 +0000,nyt,"In an Asymmetrical War, Iran Seeks an Edge Wit...",https://www.nytimes.com/2026/03/28/business/ir...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
57,111,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...
145,42,2026-03-28-03-51-00 +0000,wsj,President Trump signed an executive order to p...,https://www.wsj.com/politics/policy/house-gop-...
36,38,2026-03-28-19-47-50 +0000,nypost,Tiger Woods will be in for a ‘dogfight’ after ...,https://nypost.com/2026/03/28/us-news/tiger-wo...
24,37,2026-03-28-20-02-09 +0000,wapo,Iran-backed Houthis in Yemen launch attack on ...,https://www.washingtonpost.com/world/2026/03/2...
179,31,2026-03-27-23-58-00 +0000,wsj,Bank of America Agrees to Pay $72.5 Million to...,https://www.wsj.com/finance/banking/bank-of-am...
98,31,2026-03-28-13-06-30 +0000,nypost,Noa Argamani and Avinatan Or –the Israeli coup...,https://nypost.com/2026/03/28/world-news/israe...
150,29,2026-03-28-02-28-42 +0000,nyt,Iranian Strike on U.S. Base in Saudi Arabia In...,https://www.nytimes.com/2026/03/27/us/politics...
87,26,2026-03-28-14-53-53 +0000,nypost,NYC Mayor Zohran Mamdani’s new deputy for comm...,https://nypost.com/2026/03/28/us-news/mamdanis...
162,24,2026-03-28-00-54-37 +0000,bbc,'We're having a moment' - fear and denial in S...,https://www.bbc.com/news/articles/c86e3eglv2go...
190,23,2026-03-27-23-00-00 +0000,wsj,Society has always worried about protecting th...,https://www.wsj.com/politics/social-media-free...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)