## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-21-01-07 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...
1,2026-03-13-21-00-30 +0000,nyt,What We Know About Michigan Synagogue Attack o...,https://www.nytimes.com/2026/03/12/us/michigan...
2,2026-03-13-20-58-37 +0000,nypost,Kyrsten Sinema admits she had sex with her mar...,https://nypost.com/2026/03/13/us-news/kyrsten-...
3,2026-03-13-20-58-09 +0000,startribune,Live: NDSU commit Morgan Mathiowetz puts on a ...,https://www.startribune.com/mn-girls-basketbal...
4,2026-03-13-20-58-00 +0000,wsj,Auto & Transport Roundup: Market Talk,https://www.wsj.com/business/auto-transport-ro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2620/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
1     iran     60
3      war     41
6    trump     39
26     new     23
195    oil     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-13-21-01-07 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...,234
383,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,165
143,2026-03-13-16-17-58 +0000,nyt,Trump-Iran Timeline: Key Moments Leading Up to...,https://www.nytimes.com/2026/03/13/us/politics...,161
328,2026-03-13-01-32-01 +0000,nyt,Trump Removes Sanctions on Russia to Help Oil ...,https://www.nytimes.com/2026/03/12/us/politics...,160
123,2026-03-13-17-09-48 +0000,nypost,Trump says US seizing Kharg Island ‘not high o...,https://nypost.com/2026/03/13/us-news/trump-sa...,149

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,234,2026-03-13-21-01-07 +0000,nyt,Israel-Iran Conflict: Iran War Live Updates: T...,https://www.nytimes.com/live/2026/03/13/world/...
388,72,2026-03-12-21-04-34 +0000,nyt,New Iranian Leader Vows to Keep Global Oil Gat...,https://www.nytimes.com/2026/03/12/world/middl...
196,64,2026-03-13-14-12-13 +0000,cbc,Man in Michigan synagogue attack lost family m...,https://www.cbc.ca/news/canada/windsor/michiga...
175,49,2026-03-13-15-00-06 +0000,bbc,UK urges allies to keep up pressure on Russia ...,https://www.bbc.com/news/articles/cvg3yxd49xno...
262,46,2026-03-13-09-49-30 +0000,nypost,All 6 crew members killed as US Air Force refu...,https://nypost.com/2026/03/13/us-news/4-crew-m...
95,43,2026-03-13-17-58-01 +0000,latimes,"Six U.S. airmen die in crash; 2,500 Marines be...",https://www.latimes.com/politics/story/2026-03...
226,41,2026-03-13-11-47-09 +0000,bbc,'No-one will hire women' - India's top court r...,https://www.bbc.com/news/articles/c0436qkegdqo...
8,38,2026-03-13-20-52-00 +0000,wsj,"In a major victory for the Fed, a judge threw ...",https://www.wsj.com/economy/central-banking/ju...
258,36,2026-03-13-10-00-00 +0000,latimes,"Fuel, energy prices raise the pressure as Cali...",https://www.latimes.com/environment/story/2026...
174,36,2026-03-13-15-01-00 +0000,wsj,The Commerce Department said GDP grew at just ...,https://www.wsj.com/economy/consumers/economy-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)