## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-15-41-16 +0000,nyt,Even China’s A.I. Powerhouses Can’t Figure Out...,https://www.nytimes.com/2026/07/27/business/ch...
1,2026-07-27-15-40-46 +0000,nyt,Wildfires Live Updates: Spain and France Fight...,https://www.nytimes.com/live/2026/07/27/world/...
2,2026-07-27-15-40-14 +0000,wapo,Zelensky is first foreign leader to visit Burn...,https://www.washingtonpost.com/world/2026/07/2...
3,2026-07-27-15-39-54 +0000,bbc,Three dead and several injured in shooting at ...,https://www.bbc.co.uk/news/articles/c78gjyx4q2...
4,2026-07-27-15-37-32 +0000,nyt,Pentagon Changes How It Reports Casualties in ...,https://www.nytimes.com/2026/07/26/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2347/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
43        iran     23
205      trump     19
18         new     12
4          out     11
7    wildfires     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
265,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,74
209,2026-07-26-22-25-29 +0000,nypost,"Trump likes daily strikes on Iran, Sen. Kenned...",https://nypost.com/2026/07/26/world-news/trump...,67
43,2026-07-27-14-10-53 +0000,nypost,Netanyahu heads to DC after warning Trump need...,https://nypost.com/2026/07/27/us-news/netanyah...,63
236,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...,60
234,2026-07-26-19-30-00 +0000,wsj,Trump Pauses Iran Strikes as Officials Weigh D...,https://www.wsj.com/world/middle-east/trump-pa...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
265,74,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
236,60,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...
147,58,2026-07-27-09-20-57 +0000,nypost,TikTokker voiced concerns about Seattle Center...,https://nypost.com/2026/07/27/us-news/tiktokke...
1,52,2026-07-27-15-40-46 +0000,nyt,Wildfires Live Updates: Spain and France Fight...,https://www.nytimes.com/live/2026/07/27/world/...
157,44,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
114,38,2026-07-27-11-02-00 +0000,wsj,Chip Maker Soars 466% on Debut to Become No. 1...,https://www.wsj.com/tech/cxmts-strong-debut-bo...
223,36,2026-07-26-21-00-27 +0000,bbc,Badenoch says PM must rule out tax rises to fu...,https://www.bbc.co.uk/news/articles/c0jlzqe9z9...
237,32,2026-07-26-19-07-31 +0000,nypost,Raging DNC boss Ken Martin threw phone at aide...,https://nypost.com/2026/07/26/us-news/raging-d...
101,29,2026-07-27-11-30-00 +0000,nypost,NYC stores illegally selling THC drinks as off...,https://nypost.com/2026/07/27/us-news/nyc-stor...
217,27,2026-07-26-21-23-53 +0000,bbc,"Israeli settlers set fire to mosques, cars and...",https://www.bbc.co.uk/news/articles/cjrv77gl4d...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)