## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-16-12-03 +0000,nypost,Judge slaps down California MAGA county’s bid ...,https://nypost.com/2026/08/10/us-news/californ...
1,2026-08-10-16-10-59 +0000,bbc,"Deadly earthquake hits Colombia, causing build...",https://www.bbc.co.uk/news/articles/c20e360lx0...
2,2026-08-10-16-09-48 +0000,nyt,Live Updates: Powerful 7.4 Earthquake Strikes ...,https://www.nytimes.com/live/2026/08/10/world/...
3,2026-08-10-16-06-56 +0000,nyt,One Source of Paxton’s Wealth: A Cell Tower at...,https://www.nytimes.com/2026/08/10/us/paxton-c...
4,2026-08-10-16-03-16 +0000,nypost,Florida swimmer’s arm ripped off by alligator ...,https://nypost.com/2026/08/10/us-news/florida-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2515/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
61    trump     27
191    iran     11
416  senate     11
847    race      9
89    china      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
218,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...,85
219,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...,81
128,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...,68
25,2026-08-10-15-18-28 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,67
103,2026-08-10-11-10-00 +0000,wsj,The U.S. and Israeli militaries have pounded I...,https://www.wsj.com/politics/elections/why-is-...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
218,85,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...
128,68,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...
241,62,2026-08-09-19-53-25 +0000,nypost,Gavin Newsom confirms he’ll sit down with radi...,https://nypost.com/2026/08/09/us-news/gavin-ne...
103,53,2026-08-10-11-10-00 +0000,wsj,The U.S. and Israeli militaries have pounded I...,https://www.wsj.com/politics/elections/why-is-...
35,40,2026-08-10-14-52-12 +0000,nypost,Ex-Wisconsin Gov. Scott Walker warns Republica...,https://nypost.com/2026/08/10/us-news/ex-wisco...
4,36,2026-08-10-16-03-16 +0000,nypost,Florida swimmer’s arm ripped off by alligator ...,https://nypost.com/2026/08/10/us-news/florida-...
34,32,2026-08-10-14-55-02 +0000,nypost,Massive 7.4-magnitude earthquake strikes Colom...,https://nypost.com/2026/08/10/world-news/massi...
220,29,2026-08-09-22-07-40 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
107,27,2026-08-10-11-02-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
0,26,2026-08-10-16-12-03 +0000,nypost,Judge slaps down California MAGA county’s bid ...,https://nypost.com/2026/08/10/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)