## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-21-01-08 +0000,bbc,First UK government flight to leave Middle Eas...,https://www.bbc.com/news/articles/cy4wwd2jlypo...
1,2026-03-04-21-00-06 +0000,nyt,"After Pete Hegseth Cut Pentagon Funding, Harva...",https://www.nytimes.com/2026/03/04/us/hegseth-...
2,2026-03-04-20-59-53 +0000,nyt,U.S. Submarine Launches First Torpedo in Comba...,https://www.nytimes.com/2026/03/04/us/politics...
3,2026-03-04-20-59-32 +0000,nypost,Horrifying new details released after Lake Tah...,https://nypost.com/2026/03/04/us-news/horrifyi...
4,2026-03-04-20-57-50 +0000,bbc,How depleted stockpiles could affect the Iran ...,https://www.bbc.com/news/articles/cdxzzqe82d2o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2616/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
41       iran     76
23        war     37
82      trump     36
282     texas     33
42   conflict     26

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
167,2026-03-04-17-01-45 +0000,bbc,US Senate to vote on Trump's war powers as Ira...,https://www.bbc.com/news/articles/c5yjj28jjd0o...,199
156,2026-03-04-17-18-41 +0000,wapo,"From Hamas attack to U.S. war with Iran, viole...",https://www.washingtonpost.com/world/2026/03/0...,175
307,2026-03-04-09-58-00 +0000,wsj,Spain’s Sanchez Reiterates Opposition to Iran ...,https://www.wsj.com/world/europe/spains-sanche...,174
231,2026-03-04-14-06-31 +0000,nyt,"Spain’s Leader, Rejecting Iran War, Escalates ...",https://www.nytimes.com/2026/03/04/world/europ...,170
133,2026-03-04-17-49-43 +0000,nypost,US lawmakers to vote on war powers resolution ...,https://nypost.com/2026/03/04/world-news/us-la...,170

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
167,199,2026-03-04-17-01-45 +0000,bbc,US Senate to vote on Trump's war powers as Ira...,https://www.bbc.com/news/articles/c5yjj28jjd0o...
212,151,2026-03-04-15-10-00 +0000,wsj,Incumbent Sen. John Cornyn and Texas Attorney ...,https://www.wsj.com/politics/elections/john-co...
196,82,2026-03-04-15-55-00 +0000,wsj,GOP Rep. Dan Crenshaw became the first House i...,https://www.wsj.com/politics/elections/rep-dan...
326,68,2026-03-04-07-09-00 +0000,wsj,"Asian Equities Fall, Oil Rises Amid Ongoing Mi...",https://www.wsj.com/finance/stocks/asian-equit...
117,66,2026-03-04-18-19-00 +0000,wsj,Global authorities must step up their surveill...,https://www.wsj.com/economy/central-banking/re...
308,62,2026-03-04-09-46-35 +0000,nypost,Israel threatens Ayatollah Khamenei’s successo...,https://nypost.com/2026/03/04/world-news/iran-...
204,57,2026-03-04-15-39-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
134,52,2026-03-04-17-49-29 +0000,nypost,News Corp. strikes $50M-per-year AI licensing ...,https://nypost.com/2026/03/04/business/news-co...
8,50,2026-03-04-20-53-57 +0000,wapo,Live updates: NATO shoots down Iran’s missile ...,https://www.washingtonpost.com/world/2026/03/0...
3,49,2026-03-04-20-59-32 +0000,nypost,Horrifying new details released after Lake Tah...,https://nypost.com/2026/03/04/us-news/horrifyi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)