## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-28-12-40-40 +0000,nypost,Sick crooks filmed stealing jewlery from vict...,https://nypost.com/2026/08/28/world-news/sicko...
1,2026-08-28-12-35-15 +0000,chitri,"In AP interview, Attorney General Todd Blanche...",https://www.chicagotribune.com/2026/08/28/atto...
2,2026-08-28-12-34-56 +0000,chitri,Democrats and Republicans draw battle lines fo...,https://www.chicagotribune.com/2026/08/28/demo...
3,2026-08-28-12-27-38 +0000,wapo,Iceland eyes hookup with European Union after ...,https://www.washingtonpost.com/world/2026/08/2...
4,2026-08-28-12-26-00 +0000,wsj,PayPal Shares Dive Premarket on Report of Adve...,https://www.wsj.com/business/deals/paypal-shar...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
33   trump     53
6    nepal     33
66     new     31
184   lake     22
47     war     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
346,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...,145
340,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...,144
172,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...,144
238,2026-08-27-21-52-39 +0000,wapo,Trump signs order renaming Lake Ontario as Lak...,https://www.washingtonpost.com/politics/2026/0...,139
268,2026-08-27-21-04-00 +0000,wsj,Trump Signs Executive Order to Rename Lake Ont...,https://www.wsj.com/world/americas/trump-canad...,133

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
346,145,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...
183,102,2026-08-28-01-10-00 +0000,wsj,New York Attorney General Letitia James is sui...,https://www.wsj.com/politics/policy/new-york-s...
173,83,2026-08-28-02-00-00 +0000,wsj,The U.S.-Canada trade war. The war in Iran. Su...,https://www.wsj.com/economy/global/how-the-ai-...
412,77,2026-08-27-14-13-01 +0000,nyt,Rock Landslide and Glacial Collapse Likely Cau...,https://www.nytimes.com/2026/08/27/world/asia/...
269,74,2026-08-27-21-03-00 +0000,wsj,Federal investigators said the temporary reloc...,https://www.wsj.com/politics/policy/investigat...
90,57,2026-08-28-09-27-17 +0000,bbc,Norway's King Harald dies aged 89: A beloved m...,https://www.bbc.co.uk/news/articles/clykn5p517...
202,54,2026-08-27-23-50-00 +0000,wsj,California has made it easier to file civil cl...,https://www.wsj.com/politics/policy/california...
172,53,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...
405,52,2026-08-27-14-29-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
26,52,2026-08-28-11-30-00 +0000,nypost,Dolly Parton’s Dollywood theme park transforme...,https://nypost.com/2026/08/28/us-news/dolly-pa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)