## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-19-49-31 +0000,wapo,Rival pro-Israel group to spend millions to ta...,https://www.washingtonpost.com/politics/2026/0...
1,2026-09-10-19-49-00 +0000,wsj,"Defending Ukraine Is Getting More Expensive, a...",https://www.wsj.com/world/europe/defending-ukr...
2,2026-09-10-19-46-35 +0000,nypost,Convicted NYC terrorist’s mom runs for school ...,https://nypost.com/2026/09/10/world-news/convi...
3,2026-09-10-19-46-00 +0000,wsj,Tight Supply Worries Lift Oil As Middle East C...,https://www.wsj.com/finance/commodities-future...
4,2026-09-10-19-45-35 +0000,chitri,Homewood’s Dixie Highway viaduct now to close ...,https://www.chicagotribune.com/2026/09/10/home...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2643/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
59        trump     65
156         new     27
322  convention     20
355         war     18
67          gop     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
310,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...,176
139,2026-09-10-16-04-45 +0000,nyt,"Trump Floats $5,000 ‘Trump Dividend’ Checks if...",https://www.nytimes.com/2026/09/10/us/politics...,169
445,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,145
232,2026-09-10-10-55-00 +0000,wsj,There were scores of empty seats at the RNC co...,https://www.wsj.com/politics/if-trump-cant-fil...,145
303,2026-09-10-04-16-36 +0000,wapo,"Trump makes case for Iran war, promises $5,000...",https://www.washingtonpost.com/politics/2026/0...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
310,176,2026-09-10-03-26-00 +0000,wsj,Trump capped off Day One of the Republican Par...,https://www.wsj.com/politics/elections/five-ta...
445,80,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
439,75,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI-safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
174,70,2026-09-10-14-00-00 +0000,wsj,Home sales in August fell to their lowest leve...,https://www.wsj.com/economy/housing/home-sales...
329,65,2026-09-10-01-54-25 +0000,nyt,"“We gave you no tax on tips, no tax on overtim...",https://www.nytimes.com/live/2026/09/09/us/rnc...
341,64,2026-09-10-01-23-43 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
164,62,2026-09-10-14-44-00 +0000,wsj,"Saudi Oil Output Slumps as Iran War, Houthi Th...",https://www.wsj.com/business/energy-oil/opec-f...
267,61,2026-09-10-09-30-00 +0000,nypost,Charlie Kirk’s murder left a void that will ‘1...,https://nypost.com/2026/09/10/us-news/charlie-...
128,58,2026-09-10-16-31-30 +0000,bbc,Pilot warned Amazon cargo plane going too fast...,https://www.bbc.co.uk/news/articles/cj4jynv59d...
348,56,2026-09-10-01-00-00 +0000,wsj,The Fed’s next rate decision could hinge on Fr...,https://www.wsj.com/economy/central-banking/in...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)