## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-10-49-11 +0000,nyt,Mideast Fighting: Live Updates: New Wave of Ai...,https://www.nytimes.com/live/2026/03/07/world/...
1,2026-03-07-10-33-08 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/07/world/...
2,2026-03-07-10-30-00 +0000,wsj,Volkswagen Dealers Revolt Over Plan to Sell a ...,https://www.wsj.com/business/autos/volkswagen-...
3,2026-03-07-10-30-00 +0000,wsj,"For Some Influencers, Epstein Conspiracy Theor...",https://www.wsj.com/us-news/epstein-files-cons...
4,2026-03-07-10-30-00 +0000,wapo,Trump plans to revoke Biden tax rule that crac...,https://www.washingtonpost.com/business/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2628/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
47    iran     65
25   trump     60
373   dies     28
52     war     28
4      new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
93,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,224
172,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,178
21,2026-03-07-10-00-47 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,172
169,2026-03-06-22-12-02 +0000,wapo,Trump demands ‘UNCONDITIONAL SURRENDER’ from I...,https://www.washingtonpost.com/national-securi...,170
246,2026-03-06-18-27-47 +0000,nyt,Why a G.O.P. War Powers Hawk Was a No on Reini...,https://www.nytimes.com/2026/03/06/us/politics...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
93,224,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
201,82,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
109,68,2026-03-07-00-32-35 +0000,bbc,AI-generated Iran war videos surge as creators...,https://www.bbc.com/news/articles/ckg8wvz427vo...
158,54,2026-03-06-22-37-17 +0000,latimes,Honey is wrapping up her first course at San B...,https://www.latimes.com/california/story/2026-...
166,53,2026-03-06-22-17-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
56,50,2026-03-07-05-22-04 +0000,nypost,Coast Guard rescue swimmer Tyler Jaggers dies ...,https://nypost.com/2026/03/07/us-news/coast-gu...
12,49,2026-03-07-10-01-47 +0000,nyt,Russia Revels in a Sudden Reversal in Fortunes...,https://www.nytimes.com/2026/03/07/world/europ...
53,44,2026-03-07-06-01-03 +0000,nypost,Sen. John Kennedy reveals why Kristi Noem was ...,https://nypost.com/2026/03/07/us-news/kristi-n...
288,44,2026-03-06-17-03-32 +0000,nypost,Trump-tariff refund system will be ready in 45...,https://nypost.com/2026/03/06/business/trump-t...
271,41,2026-03-06-17-36-06 +0000,nypost,White House releases wild video montages pairi...,https://nypost.com/2026/03/06/us-news/white-ho...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)