## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-15-01-14-49 +0000,nypost,Taco Bell chooses new location for Irvine head...,https://nypost.com/2026/09/14/us-news/taco-bel...
1,2026-09-15-01-06-05 +0000,nyt,Supreme Court Blocks Trump Administration Plan...,https://www.nytimes.com/2026/09/14/us/politics...
2,2026-09-15-01-04-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...
3,2026-09-15-01-04-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
4,2026-09-15-01-00-00 +0000,wsj,Hedge Funds Are the Wild Card in the Turbulent...,https://www.wsj.com/finance/investing/bond-mar...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
10  trump     54
34     ai     27
3     new     17
97   year     13
8   court     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
344,2026-09-14-09-00-00 +0000,wapo,He’s called himself ‘Trump before Donald Trump...,https://www.washingtonpost.com/politics/2026/0...,155
265,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...,141
3,2026-09-15-01-04-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...,141
7,2026-09-15-01-00-00 +0000,wsj,Fed leader Kevin Warsh is facing the fight Pre...,https://www.wsj.com/economy/central-banking/wa...,136
2,2026-09-15-01-04-00 +0000,wsj,Supreme Court Blocks Trump’s New Mail Ballot R...,https://www.wsj.com/politics/policy/supreme-co...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
344,155,2026-09-14-09-00-00 +0000,wapo,He’s called himself ‘Trump before Donald Trump...,https://www.washingtonpost.com/politics/2026/0...
265,87,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...
3,87,2026-09-15-01-04-00 +0000,wsj,The Supreme Court blocked the Trump administra...,https://www.wsj.com/politics/policy/supreme-co...
348,59,2026-09-14-08-44-44 +0000,wsj,"Stock Market News, Sept. 14, 2026: 10-Year Tre...",https://www.wsj.com/livecoverage/stock-market-...
45,53,2026-09-14-23-00-48 +0000,nypost,Bill Maher warns California voters will ‘accep...,https://nypost.com/2026/09/14/us-news/bill-mah...
322,52,2026-09-14-10-14-31 +0000,nypost,Russian drone hits train near Ukraine-Poland b...,https://nypost.com/2026/09/14/world-news/russi...
314,51,2026-09-14-11-04-00 +0000,wsj,"The price of gasoline—and, by proxy, the Iran ...",https://www.wsj.com/politics/policy/with-50-da...
27,43,2026-09-14-23-48-00 +0000,wsj,Mitch McConnell returned to the Capitol after ...,https://www.wsj.com/politics/policy/sen-mitch-...
138,39,2026-09-14-19-59-47 +0000,cbc,'Cool to be Canadian': Leaders optimistic thei...,https://www.cbc.ca/news/business/canada-invest...
146,36,2026-09-14-19-39-00 +0000,wsj,Oil Prices Rise as Saudi East-West Pipeline At...,https://www.wsj.com/business/energy-oil/oil-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)