## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-12-22-48-08 +0000,nypost,Family of North Carolina couple who gunned dow...,https://nypost.com/2026/09/12/us-news/family-k...
1,2026-09-12-22-46-12 +0000,nyt,Trump Says Irish Unification Would Be ‘Fantast...,https://www.nytimes.com/2026/09/12/world/europ...
2,2026-09-12-22-40-33 +0000,nypost,Musician with ‘beautiful’ voice identified as ...,https://nypost.com/2026/09/12/us-news/man-foun...
3,2026-09-12-22-31-13 +0000,nypost,Ukraine and Russia clash in ‘first-ever’ drone...,https://nypost.com/2026/09/12/world-news/ukrai...
4,2026-09-12-22-30-49 +0000,startribune,Live: Mississippi State rolling past Gophers i...,https://www.startribune.com/minnesota-gophers-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2505/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     28
256    war     10
117   iran     10
53     new      8
351  saudi      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
47,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...,75
106,2026-09-12-12-19-58 +0000,nypost,Trump claims Iran-backed Houthis don’t want to...,https://nypost.com/2026/09/12/us-news/trump-op...,63
146,2026-09-12-08-19-29 +0000,nypost,Trump arrives in Ireland to meet leaders befor...,https://nypost.com/2026/09/12/world-news/trump...,63
93,2026-09-12-13-56-20 +0000,bbc,A united Ireland would be 'fantastic' says Tru...,https://www.bbc.co.uk/news/articles/cy0zvx15ry...,57
78,2026-09-12-16-02-54 +0000,chitri,President Donald Trump touches a nerve while i...,https://www.chicagotribune.com/2026/09/12/dona...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
47,75,2026-09-12-19-39-25 +0000,nypost,Trump says he would ‘love’ to see a united Ire...,https://nypost.com/2026/09/12/us-news/trump-sa...
191,53,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...
54,40,2026-09-12-18-42-25 +0000,nypost,Attack that closed key Saudi pipeline blamed o...,https://nypost.com/2026/09/12/world-news/attac...
76,36,2026-09-12-16-16-16 +0000,nypost,"8 killed, dozens wounded in Russian strikes on...",https://nypost.com/2026/09/12/world-news/8-kil...
21,31,2026-09-12-21-17-45 +0000,nypost,Two NJ Democrats demand direct reparations to ...,https://nypost.com/2026/09/12/us-news/two-nj-d...
91,31,2026-09-12-14-26-02 +0000,nypost,Canada trade war jeopardizing key Senate battl...,https://nypost.com/2026/09/12/us-news/canada-t...
31,30,2026-09-12-20-51-49 +0000,nypost,Lindsay Clancy case eerily similar to bipolar ...,https://nypost.com/2026/09/12/us-news/lindsay-...
37,25,2026-09-12-20-29-21 +0000,nypost,Police rush to Kamala Harris’ $8M Malibu mansi...,https://nypost.com/2026/09/12/us-news/police-r...
167,23,2026-09-12-02-22-04 +0000,nypost,Powerful union boss accused of shoving female...,https://nypost.com/2026/09/11/us-news/seiu-bos...
112,23,2026-09-12-11-00-00 +0000,missionlocal,"For years, one of S.F.’s oldest barbershops ha...",https://missionlocal.org/2026/09/sf-shears-bar...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)