## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-29-01-18-24 +0000,bbc,OpenAI scraps rollout of new model over safety...,https://www.bbc.co.uk/news/articles/cm5y5nynl7...
1,2026-09-29-01-12-52 +0000,bbc,Are Trump's US government funded ads illegal?,https://www.bbc.co.uk/news/videos/c6lymekx0rep...
2,2026-09-29-01-00-00 +0000,wsj,The ‘Colossal Headache’ of Building a Made-in-...,https://www.wsj.com/business/american-made-mon...
3,2026-09-29-01-00-00 +0000,wsj,RFK Jr.’s Push to Revamp American Food Runs In...,https://www.wsj.com/politics/policy/rfk-jr-s-p...
4,2026-09-29-01-00-00 +0000,wsj,Middle East Oil Exports Rebound as Iran’s Chok...,https://www.wsj.com/world/middle-east/middle-e...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2352/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     39
3        new     22
433       uk     14
218  billion     12
31       oil     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
82,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...,194
152,2026-09-28-19-37-09 +0000,chitri,President Trump announces a new $15B Iowa stee...,https://www.chicagotribune.com/2026/09/28/trum...,105
165,2026-09-28-19-15-55 +0000,wapo,Trump says new fuel economy rules will cut car...,https://www.washingtonpost.com/transportation/...,97
44,2026-09-28-22-46-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...,94
99,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
82,194,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...
246,67,2026-09-28-14-42-32 +0000,nypost,Five British nationals already out on bail aft...,https://nypost.com/2026/09/28/world-news/five-...
232,50,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
5,47,2026-09-29-01-00-00 +0000,wsj,Health Secretary Robert F. Kennedy Jr.’s push ...,https://www.wsj.com/politics/policy/rfk-jr-s-p...
38,45,2026-09-28-22-56-47 +0000,nypost,Slain New York Times exec was in vicious fight...,https://nypost.com/2026/09/28/us-news/slain-ny...
205,45,2026-09-28-17-10-56 +0000,nypost,Oil soars above $107 after Trump rejects Iran ...,https://nypost.com/2026/09/28/business/oil-soa...
60,44,2026-09-28-22-02-24 +0000,nypost,California city cracks top 3 in America’s best...,https://nypost.com/2026/09/28/lifestyle/5-cali...
213,44,2026-09-28-16-54-00 +0000,wsj,A Federal Reserve employee transferred potenti...,https://www.wsj.com/economy/central-banking/fe...
99,40,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...
273,37,2026-09-28-13-07-00 +0000,wsj,Ahead of the release of his book “This Cursed ...,https://www.wsj.com/world/how-evan-gershkovich...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)