## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-05-36-00 +0000,wsj,U.S. Treasury Yields Rise; Focus on Middle Eas...,https://www.wsj.com/finance/investing/jgb-futu...
1,2026-04-27-05-26-05 +0000,nyt,Muted Reaction as Oil and Stock Markets Reopen,https://www.nytimes.com/2026/04/26/business/oi...
2,2026-04-27-05-24-00 +0000,wsj,Oil Above $100 Signals Supply Stress,https://www.wsj.com/finance/commodities-future...
3,2026-04-27-05-16-07 +0000,bbc,'There's so much I want to give my daughter - ...,https://www.bbc.com/news/articles/cyv1rv1gr9mo...
4,2026-04-27-04-57-13 +0000,nyt,How a Trump Event Shooting Unfolded,https://www.nytimes.com/2026/04/26/world/trump...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2599/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

               word  score
26            trump     38
28         shooting     29
52           dinner     27
108  correspondents     20
106           white     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
15,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,184
165,2026-04-26-15-22-31 +0000,nypost,Trump recounts political unity after White Hou...,https://nypost.com/2026/04/26/us-news/trump-re...,175
91,2026-04-26-20-25-08 +0000,nyt,What We Know About the Shooting at the White H...,https://www.nytimes.com/2026/04/26/us/politics...,164
161,2026-04-26-15-38-13 +0000,nypost,Read White House Correspondents’ Dinner gunman...,https://nypost.com/2026/04/26/us-news/read-whc...,158
79,2026-04-26-21-46-52 +0000,nypost,Witness describes the moment gunman Cole Allen...,https://nypost.com/2026/04/26/us-news/witness-...,152

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
15,184,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
146,88,2026-04-26-16-47-42 +0000,nypost,WHCD shooting suspect Cole Allen mocked lack o...,https://nypost.com/2026/04/26/us-news/whcd-sho...
152,50,2026-04-26-16-20-00 +0000,wsj,The shooting outside Trump’s dinner with the p...,https://www.wsj.com/politics/policy/panic-at-t...
5,43,2026-04-27-04-55-34 +0000,bbc,'I don't want the children to see how worried ...,https://www.bbc.com/news/articles/ckg9q2g88nzo...
62,33,2026-04-26-22-25-15 +0000,nypost,Rodeo announcer has brutal prank played on him...,https://nypost.com/2026/04/26/us-news/rodeo-an...
94,31,2026-04-26-19-52-11 +0000,nyt,Shooting Prompts Discussions About King Charle...,https://www.nytimes.com/2026/04/26/us/politics...
21,30,2026-04-27-03-00-00 +0000,wsj,Keep DNA a state secret. No motorcade snubs. A...,https://www.wsj.com/politics/how-to-avoid-fist...
61,26,2026-04-26-22-27-09 +0000,nyt,"Israel and Hezbollah Trade Strikes in Lebanon,...",https://www.nytimes.com/2026/04/26/world/middl...
150,26,2026-04-26-16-32-00 +0000,wsj,Sen. Thom Tillis said he would support Kevin W...,https://www.wsj.com/politics/policy/tillis-dro...
151,26,2026-04-26-16-30-18 +0000,nypost,Gas station owner speaks for every Californian...,https://nypost.com/2026/04/26/us-news/gas-stat...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)