## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-13-17-10-31 +0000,nyt,Train Derails Near Town of Lewes in East Susse...,https://www.nytimes.com/2026/08/13/world/europ...
1,2026-08-13-17-08-53 +0000,nypost,Great white sharks circle swimmer off Californ...,https://nypost.com/2026/08/13/us-news/great-wh...
2,2026-08-13-17-07-00 +0000,wsj,Opinion | How to Lose Friends and Alienate Allies,https://www.wsj.com/opinion/how-to-lose-friend...
3,2026-08-13-17-06-00 +0000,wsj,Opinion | A Yale Prof Has Ideas About Your Kids,https://www.wsj.com/opinion/a-yale-prof-has-id...
4,2026-08-13-17-05-00 +0000,wsj,House Minority Leader Hakeem Jeffries on Thurs...,https://www.wsj.com/politics/policy/top-democr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
257    trump     30
15       new     14
26     house     13
8      white     13
260  against     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
349,2026-08-12-20-14-22 +0000,cbc,White House press secretary Karoline Leavitt t...,https://www.cbc.ca/news/world/karoline-leavitt...,107
295,2026-08-12-22-02-00 +0000,wsj,"White House press secretary Karoline Leavitt, ...",https://www.wsj.com/politics/policy/white-hous...,105
278,2026-08-12-22-58-45 +0000,bbc,Trump says White House press secretary Karolin...,https://www.bbc.co.uk/news/articles/cvglzrvyrz...,102
287,2026-08-12-22-28-48 +0000,nyt,"Karoline Leavitt, Trump’s White House Press Se...",https://www.nytimes.com/2026/08/12/us/politics...,96
328,2026-08-12-20-51-44 +0000,chitri,"White House press secretary Karoline Leavitt, ...",https://www.chicagotribune.com/2026/08/12/whit...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
349,107,2026-08-12-20-14-22 +0000,cbc,White House press secretary Karoline Leavitt t...,https://www.cbc.ca/news/world/karoline-leavitt...
343,54,2026-08-12-20-18-00 +0000,wsj,A former director at the Southern Poverty Law ...,https://www.wsj.com/politics/policy/former-sou...
203,51,2026-08-13-08-42-00 +0000,wsj,U.S. Army troops faced off against Ukrainian d...,https://www.wsj.com/politics/national-security...
175,49,2026-08-13-10-00-00 +0000,latimes,Becerra holds strong lead over Hilton in race ...,https://www.latimes.com/california/story/2026-...
71,43,2026-08-13-15-15-31 +0000,nypost,Minnesota Dem Peggy Flanagan boasts she could ...,https://nypost.com/2026/08/13/us-news/minnesot...
232,41,2026-08-13-02-25-00 +0000,wsj,Some U.S. officials thought the plan to evade ...,https://www.wsj.com/politics/national-security...
149,37,2026-08-13-11-03-00 +0000,wsj,"During campaign season, it isn’t popular to ta...",https://www.wsj.com/politics/policy/no-one-wan...
4,35,2026-08-13-17-05-00 +0000,wsj,House Minority Leader Hakeem Jeffries on Thurs...,https://www.wsj.com/politics/policy/top-democr...
367,35,2026-08-12-19-20-47 +0000,cbc,Indictment alleges Nick Reiner lay in wait bef...,https://www.cbc.ca/news/entertainment/indictme...
162,34,2026-08-13-10-39-02 +0000,bbc,Twitch users outraged as Amazon uses their con...,https://www.bbc.co.uk/news/articles/cp30pz8d09...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)