## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-06-30-51 +0000,bbc,Seven killed after drone hits bus in Russia-co...,https://www.bbc.com/news/articles/cp3peyykxd5o...
1,2026-06-03-06-21-10 +0000,nypost,Spencer Pratt lays out plan to defeat Mayor Ka...,https://nypost.com/2026/06/03/us-news/spencer-...
2,2026-06-03-06-18-00 +0000,wsj,Inditex Sales Accelerate Despite Tough Market ...,https://www.wsj.com/business/retail/inditex-sa...
3,2026-06-03-06-17-56 +0000,nyt,5 Things to Know About the Iowa Senate Candida...,https://www.nytimes.com/2026/06/02/us/politics...
4,2026-06-03-06-16-52 +0000,nypost,FBI charges 35 in West Virginia drug and firea...,https://nypost.com/2026/06/03/us-news/fbi-char...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
117       trump     37
222  california     28
84         race     22
119    governor     22
202         new     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
116,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,125
135,2026-06-03-00-00-03 +0000,nypost,Little talked about California election race t...,https://nypost.com/2026/06/02/us-news/why-cali...,122
13,2026-06-03-05-25-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...,117
32,2026-06-03-04-26-53 +0000,nypost,Trump’s pick for Iowa governor Randy Feenstra ...,https://nypost.com/2026/06/03/us-news/trump-pi...,116
54,2026-06-03-03-26-15 +0000,nypost,California governor’s race: Steve Hilton leads...,https://nypost.com/2026/06/02/us-news/californ...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
116,125,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
135,122,2026-06-03-00-00-03 +0000,nypost,Little talked about California election race t...,https://nypost.com/2026/06/02/us-news/why-cali...
113,72,2026-06-03-01-04-06 +0000,nypost,Rebecca Bennett wins Democratic primary for NJ...,https://nypost.com/2026/06/02/us-news/rebecca-...
39,56,2026-06-03-03-55-49 +0000,nypost,Spencer Pratt says he will fight Karen Bass in...,https://nypost.com/2026/06/02/us-news/karen-ba...
298,54,2026-06-02-15-58-23 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
81,49,2026-06-03-02-29-59 +0000,cbc,CBS News fires veteran journalist Scott Pelley...,https://www.cbc.ca/news/world/scott-pelley-fir...
94,47,2026-06-03-01-57-42 +0000,nypost,"Iowa Dem Josh Turek takes down lefty foe, teei...",https://nypost.com/2026/06/02/us-news/iowa-dem...
139,46,2026-06-02-23-59-00 +0000,wsj,The Trump administration is abandoning its $1....,https://www.wsj.com/politics/policy/gop-leader...
385,42,2026-06-02-09-00-00 +0000,wapo,As Russia fails to achieve war aims in Ukraine...,https://www.washingtonpost.com/world/2026/06/0...
381,39,2026-06-02-09-30-00 +0000,wsj,Berkshire Hathaway’s $6.8 billion deal to acqu...,https://www.wsj.com/economy/housing/berkshire-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)