## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-12-23-13-05 +0000,nyt,Waymo Is Fixing Its Entire Fleet to Avoid Floo...,https://www.nytimes.com/2026/05/12/us/waymo-re...
1,2026-05-12-23-11-15 +0000,nyt,Trump Administration Expected to Tap Longtime ...,https://www.nytimes.com/2026/05/12/us/politics...
2,2026-05-12-23-11-15 +0000,nypost,SoCal mayor who worked as secret agent for Chi...,https://nypost.com/2026/05/12/us-news/chinese-...
3,2026-05-12-23-09-39 +0000,nypost,Truly horrific video shows ranchers’ vile atta...,https://nypost.com/2026/05/12/us-news/californ...
4,2026-05-12-23-08-18 +0000,nypost,Sheriff accused of botching Nancy Guthrie case...,https://nypost.com/2026/05/12/us-news/nancy-gu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     37
50      iran     30
51       war     29
388  starmer     17
21     china     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
5,2026-05-12-23-01-57 +0000,nyt,Iran War Live Updates: Trump Says Iran Must Ma...,https://www.nytimes.com/live/2026/05/12/world/...,144
129,2026-05-12-19-30-07 +0000,nyt,Trump and Xi Enter China Summit Distracted by ...,https://www.nytimes.com/2026/05/12/us/politics...,129
33,2026-05-12-22-25-12 +0000,nyt,Trump Says Americans’ Economic Pain Is Not a C...,https://www.nytimes.com/2026/05/12/us/politics...,108
177,2026-05-12-17-31-00 +0000,wsj,Consumer prices rose 3.8% in April from a year...,https://www.wsj.com/economy/cpi-inflation-repo...,104
51,2026-05-12-21-59-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
5,144,2026-05-12-23-01-57 +0000,nyt,Iran War Live Updates: Trump Says Iran Must Ma...,https://www.nytimes.com/live/2026/05/12/world/...
51,66,2026-05-12-21-59-00 +0000,wsj,FDA Commissioner Marty Makary is leaving his r...,https://www.wsj.com/politics/policy/fda-commis...
42,62,2026-05-12-22-09-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
328,59,2026-05-12-08-55-33 +0000,cbc,British PM Starmer tells cabinet meeting he in...,https://www.cbc.ca/news/world/starmer-uk-resig...
145,55,2026-05-12-18-39-39 +0000,nypost,WHO warns that more hantavirus cases are likel...,https://nypost.com/2026/05/12/world-news/who-s...
2,48,2026-05-12-23-11-15 +0000,nypost,SoCal mayor who worked as secret agent for Chi...,https://nypost.com/2026/05/12/us-news/chinese-...
183,48,2026-05-12-17-20-00 +0000,wsj,OpenAI’s Sam Altman’s personal investments are...,https://www.wsj.com/tech/ai/sam-altmans-busine...
167,45,2026-05-12-17-41-56 +0000,nypost,California Democrats deploy risky strategy to ...,https://nypost.com/2026/05/12/us-news/californ...
376,44,2026-05-12-00-34-00 +0000,wsj,The Trump administration said it would delay a...,https://www.wsj.com/politics/policy/trump-clea...
375,42,2026-05-12-00-43-00 +0000,wsj,The new battleship to be named after Trump wil...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)