## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-01-22-42 +0000,nyt,Brazil Elections Head to Runoff Between Lula a...,https://www.nytimes.com/2026/10/04/world/ameri...
1,2026-10-05-01-22-21 +0000,wapo,Bolsonaro and Lula head to runoff: 5 takeaways...,https://www.washingtonpost.com/world/2026/10/0...
2,2026-10-05-01-17-44 +0000,48hills,Nobody who stuck with Manny Yekutiel has apolo...,https://48hills.org/2026/10/nobody-has-apologi...
3,2026-10-05-01-05-51 +0000,48hills,The big Congressional debate fail: Moderators ...,https://48hills.org/2026/10/the-big-congressio...
4,2026-10-05-01-00-00 +0000,wsj,Multiple Security Failures Allowed FlyDubai Pi...,https://www.wsj.com/world/middle-east/security...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
72      trump     17
210       new     14
9    election     11
50        oil     11
30   flydubai     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
66,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...,60
16,2026-10-05-00-27-06 +0000,bbc,Brazil election goes to run-off as right-wing ...,https://www.bbc.co.uk/news/articles/ck1l34ed59...,59
18,2026-10-05-00-26-14 +0000,cbc,"Lula, Bolsonaro head to run-off after neither ...",https://www.cbc.ca/news/world/lula-bolsonaro-b...,56
134,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,55
210,2026-10-04-05-00-00 +0000,cbc,"After Trump’s Venezuelan oil deal, those livin...",https://www.cbc.ca/news/world/lake-maracaibo-v...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
66,60,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...
16,59,2026-10-05-00-27-06 +0000,bbc,Brazil election goes to run-off as right-wing ...,https://www.bbc.co.uk/news/articles/ck1l34ed59...
210,54,2026-10-04-05-00-00 +0000,cbc,"After Trump’s Venezuelan oil deal, those livin...",https://www.cbc.ca/news/world/lake-maracaibo-v...
220,50,2026-10-04-02-14-00 +0000,wsj,A new White House task force will have 120 day...,https://www.wsj.com/tech/ai/new-ai-task-force-...
85,42,2026-10-04-19-56-00 +0000,wsj,Americans are facing a multifront squeeze from...,https://www.wsj.com/politics/elections/energy-...
49,36,2026-10-04-22-07-54 +0000,nypost,Russian drone slams into key Kyiv bridge durin...,https://nypost.com/2026/10/04/world-news/russi...
162,36,2026-10-04-10-49-14 +0000,wapo,"U.S. Marine accused of killing woman in Japan,...",https://www.washingtonpost.com/world/2026/10/0...
225,36,2026-10-04-01-35-10 +0000,nypost,Debris from vanished Boston-bound plane found ...,https://nypost.com/2026/10/03/world-news/debri...
165,34,2026-10-04-10-00-38 +0000,chitri,"Illinois Senate race: Republican Don Tracy, a ...",https://www.chicagotribune.com/2026/10/04/illi...
32,33,2026-10-04-23-20-51 +0000,nypost,Mom on hijacked flydubai flight with four youn...,https://nypost.com/2026/10/04/world-news/mom-o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)