## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-06-19-46-40 +0000,cbc,Amazon cargo plane goes up in smoke after over...,https://www.cbc.ca/news/world/amazon-cargo-pla...
1,2026-09-06-19-44-56 +0000,nyt,"Cargo Plane Crashes at Miami Airport, Striking...",https://www.nytimes.com/2026/09/06/us/plane-cr...
2,2026-09-06-19-38-02 +0000,nyt,Live Updates: Germany’s Far Right Has Big Lead...,https://www.nytimes.com/live/2026/09/06/world/...
3,2026-09-06-19-35-44 +0000,nypost,Mountain lion lurks in a tree on busy resident...,https://nypost.com/2026/09/06/us-news/mountain...
4,2026-09-06-19-35-00 +0000,chitri,German far-right party set for regional electi...,https://www.chicagotribune.com/2026/09/06/germ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2514/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
52     trump     21
54   ukraine     12
47     talks     11
186     iran     11
17     right     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-09-06-19-25-00 +0000,wsj,Trump Envoys Visit Ukraine in New Push for Pea...,https://www.wsj.com/world/europe/trump-envoys-...,73
31,2026-09-06-17-48-16 +0000,nypost,Mike Lawler recounts how he stood up to Trump ...,https://nypost.com/2026/09/06/us-news/mike-law...,57
141,2026-09-06-07-22-19 +0000,nypost,Trump’s MAGA super PAC pours $10M into Ken Pax...,https://nypost.com/2026/09/06/us-news/trumps-s...,55
71,2026-09-06-12-48-32 +0000,cbc,U.S. envoys Witkoff and Kushner hold talks in ...,https://www.cbc.ca/news/world/witkoff-kushner-...,54
180,2026-09-05-21-25-39 +0000,chitri,Putin meets with US envoys at the Kremlin for ...,https://www.chicagotribune.com/2026/09/05/puti...,54

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,73,2026-09-06-19-25-00 +0000,wsj,Trump Envoys Visit Ukraine in New Push for Pea...,https://www.wsj.com/world/europe/trump-envoys-...
2,46,2026-09-06-19-38-02 +0000,nyt,Live Updates: Germany’s Far Right Has Big Lead...,https://www.nytimes.com/live/2026/09/06/world/...
82,34,2026-09-06-11-59-56 +0000,nypost,Iran claims strike on unmanned US vessel in St...,https://nypost.com/2026/09/06/world-news/iran-...
53,33,2026-09-06-15-56-00 +0000,wsj,Retail investors hand control of stock portfol...,https://www.wsj.com/politics/policy/retail-inv...
61,30,2026-09-06-15-17-00 +0000,wsj,As President Trump’s approval rating hovers ne...,https://www.wsj.com/politics/in-trumps-second-...
150,30,2026-09-06-02-49-51 +0000,nyt,Putin Meets Witkoff and Kushner in Moscow to D...,https://www.nytimes.com/2026/09/05/world/europ...
32,29,2026-09-06-17-44-24 +0000,nypost,Trump asks Supreme Court to allow mail-in ball...,https://nypost.com/2026/09/06/us-news/trump-re...
172,29,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
16,28,2026-09-06-18-55-08 +0000,nypost,Devastated widow of triathlete found dead on S...,https://nypost.com/2026/09/06/us-news/devastat...
30,26,2026-09-06-17-58-47 +0000,nypost,Woman is third person to die in fireball plane...,https://nypost.com/2026/09/06/us-news/third-pe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)