## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-20-02-43-17 +0000,nypost,"Five people injured, two critically, after car...",https://nypost.com/2026/03/19/us-news/five-peo...
1,2026-03-20-02-34-55 +0000,nypost,‘Precarious’ situation as damaged shipping con...,https://nypost.com/2026/03/19/us-news/coast-gu...
2,2026-03-20-02-30-43 +0000,nypost,NYC first lady Rama Duwaji deletes old X accou...,https://nypost.com/2026/03/19/us-news/nyc-firs...
3,2026-03-20-02-30-00 +0000,wsj,Oil Prices Fall on Easing Supply-Disruption Co...,https://www.wsj.com/finance/commodities-future...
4,2026-03-20-02-21-51 +0000,nyt,Mortgage Rates Highest in Three Months as War ...,https://www.nytimes.com/2026/03/19/business/mo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2622/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
47     iran     52
53    trump     40
43      war     38
31      oil     18
110  energy     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
44,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...,180
84,2026-03-19-23-19-00 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...,179
149,2026-03-19-20-48-00 +0000,wsj,Trump’s Iran War Frays Ties With Allies as Oil...,https://www.wsj.com/world/trumps-iran-war-fray...,172
5,2026-03-20-02-19-13 +0000,nyt,Iran War Live Updates: As Attacks Shake Market...,https://www.nytimes.com/live/2026/03/19/world/...,156
227,2026-03-19-17-03-13 +0000,nyt,Iran War Narrows Fed’s Path to Rate Cuts as Tr...,https://www.nytimes.com/2026/03/19/business/fe...,151

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
44,180,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...
370,89,2026-03-19-08-36-23 +0000,cbc,Tehran intensifies attacks on Gulf energy faci...,https://www.cbc.ca/news/world/tehran-intensifi...
160,71,2026-03-19-20-30-00 +0000,latimes,California quickly moves to rename Cesar Chave...,https://www.latimes.com/california/story/2026-...
351,58,2026-03-19-09-20-00 +0000,wsj,Sweden’s Central Bank Holds Key Rate as Middle...,https://www.wsj.com/articles/swedens-central-b...
34,56,2026-03-20-01-00-00 +0000,wsj,A New York congressional race has a new X fact...,https://www.wsj.com/politics/policy/ai-lobbyin...
306,53,2026-03-19-12-13-34 +0000,nypost,Barcelona police found missing Alabama student...,https://nypost.com/2026/03/19/world-news/barce...
83,44,2026-03-19-23-23-00 +0000,wsj,A federal panel approved a commemorative gold ...,https://www.wsj.com/politics/policy/trump-gold...
247,44,2026-03-19-15-59-06 +0000,nyt,Father of a Palestinian woman killed with thre...,https://www.nytimes.com/live/2026/03/19/world/...
52,42,2026-03-20-00-24-03 +0000,nypost,Nonprofit touted by Gavin Newsom hung up on tr...,https://nypost.com/2026/03/19/us-news/trevor-p...
177,38,2026-03-19-19-59-14 +0000,cbc,"Canada, allies say they're ready to help secur...",https://www.cbc.ca/news/world/canada-joint-sta...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)