## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-01-00-00-38 +0000,nypost,Heartwarming moment dog is reunited with cryin...,https://nypost.com/2026/03/31/us-news/heartbre...
1,2026-04-01-00-00-06 +0000,startribune,"Trump lashes out at allies, says securing the ...",https://www.startribune.com/us-attacks-iranian...
2,2026-03-31-23-58-29 +0000,bbc,Judge temporarily halts construction of Trump'...,https://www.bbc.com/news/articles/c7056exw78xo...
3,2026-03-31-23-55-28 +0000,nypost,MS-13 suspects went human hunting during murde...,https://nypost.com/2026/03/31/us-news/alleged-...
4,2026-03-31-23-54-15 +0000,nyt,Iran War Live Updates: Days? Weeks? Trump Make...,https://www.nytimes.com/live/2026/03/31/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2641/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     56
36    iran     49
37     war     42
368    new     15
17   judge     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
4,2026-03-31-23-54-15 +0000,nyt,Iran War Live Updates: Days? Weeks? Trump Make...,https://www.nytimes.com/live/2026/03/31/world/...,215
234,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...,199
245,2026-03-31-14-15-31 +0000,latimes,Trump says he expects U.S. to end involvement ...,https://www.latimes.com/politics/story/2026-03...,179
114,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,178
211,2026-03-31-16-05-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,161

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
4,215,2026-03-31-23-54-15 +0000,nyt,Iran War Live Updates: Days? Weeks? Trump Make...,https://www.nytimes.com/live/2026/03/31/world/...
243,74,2026-03-31-14-26-52 +0000,nypost,"Supreme Court sides with Christian counselor, ...",https://nypost.com/2026/03/31/us-news/supreme-...
288,62,2026-03-31-11-26-00 +0000,wsj,President Trump released mock-up images of a g...,https://www.wsj.com/politics/elections/trump-r...
113,52,2026-03-31-20-32-12 +0000,wapo,Gas hits $4 a gallon for first time since 2022...,https://www.washingtonpost.com/business/2026/0...
78,51,2026-03-31-21-32-45 +0000,nypost,New scam asks for traffic or toll ticket payme...,https://nypost.com/2026/03/31/us-news/californ...
177,51,2026-03-31-17-51-30 +0000,nyt,Trump Lashes Out at Europe Over Strait of Horm...,https://www.nytimes.com/2026/03/31/world/middl...
120,46,2026-03-31-20-18-00 +0000,wsj,The Trump administration can’t end federal fun...,https://www.wsj.com/politics/policy/trumps-ord...
215,40,2026-03-31-15-46-18 +0000,nypost,Kristi Noem weighs in on report husband lives ...,https://nypost.com/2026/03/31/us-news/kristi-n...
88,36,2026-03-31-21-17-00 +0000,wsj,Stocks Cap March With ‘Hormuz Hope’ Rally on P...,https://www.wsj.com/finance/stocks/wall-street...
185,35,2026-03-31-17-30-05 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)