## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-21-19-28-17 +0000,nypost,Ghoulish parents blindfolded two young sons fo...,https://nypost.com/2026/05/21/world-news/two-f...
1,2026-05-21-19-26-10 +0000,nypost,Woman caught on camera removing Spencer Pratt ...,https://nypost.com/2026/05/21/us-news/woman-re...
2,2026-05-21-19-23-04 +0000,nypost,Victoria’s Secret brings sexy back with VSXY t...,https://nypost.com/2026/05/21/business/victori...
3,2026-05-21-19-21-58 +0000,nyt,Goldman Hits the Jackpot After Banks’ ‘Dogfigh...,https://www.nytimes.com/2026/05/21/business/sp...
4,2026-05-21-19-21-55 +0000,startribune,Live: Federal officials announce sweeping frau...,https://www.startribune.com/aimee-bock-sentenc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
58   trump     50
275    new     20
277  china     15
183  ebola     15
230     he     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
356,2026-05-20-22-44-00 +0000,wsj,President Trump’s settlement with the IRS come...,https://www.wsj.com/politics/policy/trump-fami...,146
100,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...,114
144,2026-05-21-15-36-19 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...,110
143,2026-05-21-15-44-38 +0000,nyt,Trump’s Government Moves to Spare an Unhappy T...,https://www.nytimes.com/2026/05/20/us/politics...,109
340,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
356,146,2026-05-20-22-44-00 +0000,wsj,President Trump’s settlement with the IRS come...,https://www.wsj.com/politics/policy/trump-fami...
241,87,2026-05-21-11-01-27 +0000,nypost,Queen Elizabeth was eager for Andrew to become...,https://nypost.com/2026/05/21/world-news/docum...
354,67,2026-05-20-22-47-55 +0000,nypost,Elon Musk’s SpaceX readies for Wall Street bla...,https://nypost.com/2026/05/20/business/elon-mu...
340,57,2026-05-21-00-05-00 +0000,nyt,Justice Dept. Charges Raúl Castro as Trump Esc...,https://www.nytimes.com/2026/05/20/us/raul-cas...
342,56,2026-05-20-23-51-15 +0000,nypost,Socialist Seattle Mayor Katie Wilson walks bac...,https://nypost.com/2026/05/20/us-news/seattles...
135,45,2026-05-21-16-00-00 +0000,wsj,Mortgage rates this week rose to the highest l...,https://www.wsj.com/economy/housing/mortgage-r...
290,45,2026-05-21-07-47-06 +0000,wsj,Stock Market Today: Stocks Perk Up Amid Hopes ...,https://www.wsj.com/livecoverage/stock-market-...
144,45,2026-05-21-15-36-19 +0000,nyt,Trump Again Says He Will Talk to Taiwan’s Lead...,https://www.nytimes.com/2026/05/21/world/asia/...
58,44,2026-05-21-17-54-40 +0000,bbc,DR Congo cancels World Cup training camp over ...,https://www.bbc.com/news/articles/c8d80856q2go...
31,38,2026-05-21-18-41-00 +0000,wsj,President Trump and the GOP-controlled Senate ...,https://www.wsj.com/politics/policy/trump-on-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)