## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-08-42-30 +0000,bbc,Second batch of Mandelson files to be publishe...,https://www.bbc.com/news/articles/c98r664g865o...
1,2026-06-01-08-38-58 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/06/01/world/...
2,2026-06-01-08-35-00 +0000,wsj,"U.S. Strikes Iranian Air Defenses, Drone Site ...",https://www.wsj.com/world/middle-east/u-s-stri...
3,2026-06-01-08-33-00 +0000,wsj,U.S. Stock Futures Rise Even as Oil Jumps on F...,https://www.wsj.com/finance/stocks/u-s-stock-f...
4,2026-06-01-08-31-00 +0000,wsj,USA Rare Earth Plans Roughly $200 Million Inve...,https://www.wsj.com/business/usa-rare-earth-pl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
121       trump     24
5          iran     16
319  california     12
197       china     10
408          he     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
20,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...,82
217,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...,67
61,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...,64
133,2026-05-31-19-50-13 +0000,nypost,Bitter California Republican feud turns toxic ...,https://nypost.com/2026/05/31/us-news/bitter-c...,61
192,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
20,82,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...
192,60,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...
186,46,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...
48,37,2026-06-01-03-15-56 +0000,nypost,California Dems’ huge dilemma over governor ra...,https://nypost.com/2026/05/31/us-news/californ...
149,34,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...
22,33,2026-06-01-06-55-09 +0000,nypost,New York corrections officer was on duty when ...,https://nypost.com/2026/06/01/us-news/new-york...
155,32,2026-05-31-16-34-09 +0000,nypost,NJ Gov. Sherrill claims victory on ICE detenti...,https://nypost.com/2026/05/31/us-news/nj-gov-s...
43,28,2026-06-01-04-05-00 +0000,wsj,China PMI Signals Manufacturing Held Up While ...,https://www.wsj.com/economy/china-private-fact...
104,27,2026-05-31-21-50-25 +0000,nypost,Loch Ness Monster hunters deploy underwater dr...,https://nypost.com/2026/05/31/world-news/loch-...
38,25,2026-06-01-04-48-53 +0000,nypost,Pro-Trump candidate pulls ahead in Colombia pr...,https://nypost.com/2026/06/01/world-news/pro-t...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)