## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-02-04-37-22 +0000,nypost,Massapequa football coach Kevin Shippos has bi...,https://nypost.com/2026/10/02/sports/massapequ...
1,2026-10-02-04-33-50 +0000,latimes,Bodies recovered in remote California desert l...,https://www.latimes.com/california/story/2026-...
2,2026-10-02-04-33-49 +0000,nyt,Investigators Seek to Establish Motive in FlyD...,https://www.nytimes.com/live/2026/10/01/world/...
3,2026-10-02-04-33-47 +0000,nyt,"Who Is Captain Smit Machchhar, the Pilot Haile...",https://www.nytimes.com/2026/10/01/world/asia/...
4,2026-10-02-04-21-31 +0000,bbc,Australia says platforms like Steam and Roblox...,https://www.bbc.co.uk/news/articles/cjvgygzzy6...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
87         trump     56
2075       guide     47
883         your     47
13    california     34
823         race     28

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
460,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,197
430,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,197
431,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,197
428,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,196
427,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,196

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
460,197,2026-10-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...
135,130,2026-10-01-21-36-00 +0000,wsj,Mortgage rates posted their largest increase i...,https://www.wsj.com/politics/policy/mortgage-r...
163,120,2026-10-01-20-46-06 +0000,nypost,Trump dumbfounded on why death row inmate Chri...,https://nypost.com/2026/10/01/us-news/trump-du...
29,82,2026-10-02-02-10-00 +0000,cbc,New York's governor removes district attorney ...,https://www.cbc.ca/news/world/ny-special-prose...
437,69,2026-10-01-10-00-00 +0000,latimes,Your guide to L.A. City Charter Amendment EE: ...,https://www.latimes.com/california/story/2026-...
239,65,2026-10-01-18-36-00 +0000,wsj,The top Democrats on the Senate and House fore...,https://www.wsj.com/politics/policy/lawmakers-...
237,62,2026-10-01-18-38-35 +0000,nypost,Trump sends third aircraft carrier to Middle E...,https://nypost.com/2026/10/01/us-news/trump-se...
66,60,2026-10-01-23-42-00 +0000,wsj,Fed Vice Chair Philip Jefferson said officials...,https://www.wsj.com/economy/central-banking/an...
312,50,2026-10-01-15-52-55 +0000,cbc,"Renee Good's family sues U.S. government, ICE ...",https://www.cbc.ca/news/world/renee-good-lawsu...
232,49,2026-10-01-18-58-33 +0000,nypost,Google’s AI push in schools fuels plunging tes...,https://nypost.com/2026/10/01/business/googles...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)