## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-23-00-59 +0000,nyt,"Iran Unable to Find Mines in Strait of Hormuz,...",https://www.nytimes.com/2026/04/10/us/politics...
1,2026-04-10-22-56-03 +0000,nyt,"Eliot Engel, a 16-Term Bronx Liberal in Congre...",https://www.nytimes.com/2026/04/10/nyregion/el...
2,2026-04-10-22-53-59 +0000,nyt,Iran War Live Updates: Iranian Delegation Arri...,https://www.nytimes.com/live/2026/04/10/world/...
3,2026-04-10-22-53-58 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/10/world/...
4,2026-04-10-22-52-29 +0000,nyt,University of Ottawa in Lockdown Amid ‘Violent...,https://www.nytimes.com/2026/04/10/world/canad...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     58
133   trump     44
13      war     28
20    talks     19
462  prices     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
218,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,168
196,2026-04-10-15-28-35 +0000,nypost,Trump tells The Post he’s preparing military i...,https://nypost.com/2026/04/10/us-news/trump-te...,154
84,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...,152
43,2026-04-10-21-44-17 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,148
328,2026-04-10-00-30-19 +0000,nyt,"Trump Attacks Tucker Carlson, Megyn Kelly Over...",https://www.nytimes.com/2026/04/09/us/politics...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
218,168,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...
84,94,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...
86,53,2026-04-10-20-18-31 +0000,nypost,White House warns staff against insider tradin...,https://nypost.com/2026/04/10/business/white-h...
65,48,2026-04-10-20-58-00 +0000,wsj,President Trump has repeatedly promised his to...,https://www.wsj.com/politics/policy/trump-prom...
241,47,2026-04-10-10-48-00 +0000,wsj,The fate of the U.S.-Iran cease-fire will be d...,https://www.wsj.com/politics/trump-sends-his-t...
132,42,2026-04-10-18-31-35 +0000,missionlocal,SFPD arrests young suspect who allegedly threw...,https://missionlocal.org/2026/04/sfpd-arson-su...
296,38,2026-04-10-06-29-00 +0000,wsj,Japan to Release Extra Oil Reserves Amid Middl...,https://www.wsj.com/economy/japan-to-release-e...
329,33,2026-04-10-00-23-18 +0000,bbc,India proposes new rules to regulate news and ...,https://www.bbc.com/news/articles/ce9mx2j3xlxo...
39,32,2026-04-10-21-50-02 +0000,startribune,Artemis II's grand moon finale is almost here ...,https://www.startribune.com/artemis-iis-grand-...
244,32,2026-04-10-10-36-34 +0000,nyt,Xi Meets Taiwan Opposition Leader for First Ti...,https://www.nytimes.com/2026/04/10/world/asia/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)