## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-14-22-14-05 +0000,nyt,G. Robert Blakey Dies at 90; Drafted the RICO ...,https://www.nytimes.com/2026/05/14/us/george-r...
1,2026-05-14-22-11-44 +0000,nypost,Over 200 Chicago-area alleged criminals with a...,https://nypost.com/2026/05/14/us-news/over-200...
2,2026-05-14-22-11-00 +0000,wsj,Supreme Court Maintains Widespread Access to A...,https://www.wsj.com/us-news/law/supreme-court-...
3,2026-05-14-22-11-00 +0000,wsj,LVMH Agrees to Sell Marc Jacobs,https://www.wsj.com/business/retail/lvmh-to-se...
4,2026-05-14-22-09-56 +0000,nypost,"Lawyers for Elon Musk, Sam Altman wind down Op...",https://nypost.com/2026/05/14/business/lawyers...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2514/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
111  trump     60
167  china     33
114     xi     23
90    iran     18
451    new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
166,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...,169
341,2026-05-14-04-40-36 +0000,nypost,Xi raises prospect of a future US-China war in...,https://nypost.com/2026/05/14/us-news/xi-raise...,150
174,2026-05-14-16-17-32 +0000,nypost,Xi Jinping said China ‘would love to be a help...,https://nypost.com/2026/05/14/us-news/xi-jinpi...,148
306,2026-05-14-09-12-03 +0000,nypost,"Trump, Xi agree Strait of Hormuz must stay ope...",https://nypost.com/2026/05/14/world-news/trump...,146
23,2026-05-14-21-36-35 +0000,nyt,Oil Prices Waver as Trump Meets China’s Xi to ...,https://www.nytimes.com/2026/05/14/business/oi...,142

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
166,169,2026-05-14-16-34-27 +0000,nypost,"Melania Trump stays home while her director, B...",https://nypost.com/2026/05/14/us-news/melania-...
306,86,2026-05-14-09-12-03 +0000,nypost,"Trump, Xi agree Strait of Hormuz must stay ope...",https://nypost.com/2026/05/14/world-news/trump...
94,66,2026-05-14-19-42-00 +0000,wsj,A Connecticut Republican quit the governor’s r...,https://www.wsj.com/politics/policy/improper-s...
294,56,2026-05-14-10-00-00 +0000,latimes,Hiltzik: Trump's 'weird war' on wind power wil...,https://www.latimes.com/business/story/2026-05...
48,53,2026-05-14-21-04-21 +0000,nypost,Gavin Newsom speaks out on ex-aide’s guilty pl...,https://nypost.com/2026/05/14/us-news/gavin-ne...
77,47,2026-05-14-20-23-31 +0000,nyt,"Cerebras, A.I. Chip Maker, Rises 89% in Market...",https://www.nytimes.com/2026/05/14/technology/...
363,41,2026-05-14-01-44-00 +0000,wsj,The Pentagon abruptly canceled deployment of a...,https://www.wsj.com/politics/national-security...
98,40,2026-05-14-19-33-24 +0000,nyt,Chinese News Media Cast Trump’s Visit as a Sig...,https://www.nytimes.com/2026/05/14/world/asia/...
121,37,2026-05-14-18-23-00 +0000,wsj,A bill that would create a pathway for crypto ...,https://www.wsj.com/politics/policy/crypto-ind...
38,37,2026-05-14-21-20-24 +0000,nypost,Video shows toddler escape rollover crash afte...,https://nypost.com/2026/05/14/us-news/video-sh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)