## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-03-21-46-00 +0000,wsj,"Opinion | Trump Talks, Iran Escalates",https://www.wsj.com/opinion/iran-cease-fire-is...
1,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...
2,2026-06-03-21-44-45 +0000,nypost,NYU student arrested in Nazi flag raising inci...,https://nypost.com/2026/06/03/us-news/nyu-stud...
3,2026-06-03-21-43-00 +0000,wsj,Some GOP lawmakers are pushing to kill the adm...,https://www.wsj.com/politics/policy/fight-to-k...
4,2026-06-03-21-41-21 +0000,nyt,House Advances New Sanctions on Russia and Aid...,https://www.nytimes.com/2026/06/03/us/house-ru...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     41
192  california     26
49          new     26
2          iran     24
283        race     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
23,2026-06-03-21-21-00 +0000,wsj,The GOP-led House voted to restrict President ...,https://www.wsj.com/politics/gop-led-house-vot...,166
10,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...,137
350,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...,135
157,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...,122
1,2026-06-03-21-45-00 +0000,wsj,"The House curtails Trump’s Iran war powers, bi...",https://www.wsj.com/politics/policy/house-vote...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
23,166,2026-06-03-21-21-00 +0000,wsj,The GOP-led House voted to restrict President ...,https://www.wsj.com/politics/gop-led-house-vot...
261,106,2026-06-03-09-17-07 +0000,bbc,Los Angeles Mayor Karen Bass advances to run-o...,https://www.bbc.com/news/articles/c74dp1yk51vo...
329,89,2026-06-03-02-29-59 +0000,cbc,CBS News fires veteran 60 Minutes corresponden...,https://www.cbc.ca/news/world/scott-pelley-fir...
157,63,2026-06-03-17-04-00 +0000,wsj,"Zach Lahn, a businessman and farmer, upset a c...",https://www.wsj.com/politics/elections/farmer-...
10,60,2026-06-03-21-31-00 +0000,wsj,Months after the Supreme Court struck down Pre...,https://www.wsj.com/economy/trade/what-to-know...
41,58,2026-06-03-21-02-00 +0000,wsj,In a private meeting with some Senate Democrat...,https://www.wsj.com/politics/policy/senators-p...
350,58,2026-06-03-01-00-00 +0000,wsj,"Bill Pulte, the new acting director of nationa...",https://www.wsj.com/politics/policy/why-the-pr...
156,57,2026-06-03-17-06-25 +0000,cbc,Ukrainian drones hit St. Petersburg oil termin...,https://www.cbc.ca/news/world/ukraine-drones-s...
89,53,2026-06-03-20-05-58 +0000,bbc,One killed and dozens injured in Iranian drone...,https://www.bbc.com/news/articles/c5yx135yg53o...
62,48,2026-06-03-20-39-38 +0000,nypost,Spencer Pratt’s ultra-exclusive election party...,https://nypost.com/2026/06/03/us-news/spencer-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)