## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-22-23-08-26 +0000,nyt,Iran War Live Updates: Reported Seizure of Shi...,https://www.nytimes.com/live/2026/04/22/world/...
1,2026-04-22-23-07-43 +0000,nypost,Elon Musk says Tesla expenses will rise ‘subst...,https://nypost.com/2026/04/22/business/elon-mu...
2,2026-04-22-23-04-39 +0000,bbc,How a pivot to hair accessories led to busines...,https://www.bbc.com/news/articles/c23992zv9rko...
3,2026-04-22-23-01-40 +0000,nypost,6 leading California gubernatorial candidates ...,https://nypost.com/2026/04/22/us-news/how-to-w...
4,2026-04-22-23-01-09 +0000,bbc,AI is flattening the jobs market for young peo...,https://www.bbc.com/news/articles/cvg07x4rejdo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
125       trump     41
0          iran     39
8           new     21
1           war     19
32   california     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
318,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...,155
363,2026-04-22-00-32-17 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,147
248,2026-04-22-13-18-40 +0000,nypost,Trump tells The Post news of fresh peace talks...,https://nypost.com/2026/04/22/us-news/trump-te...,133
278,2026-04-22-10-45-39 +0000,bbc,Oil prices fluctuate as Trump extends Iran war...,https://www.bbc.com/news/articles/c995dkl4dvvo...,128
58,2026-04-22-21-33-05 +0000,wapo,Iran says it seized 2 ships in Strait of Hormu...,https://www.washingtonpost.com/world/2026/04/2...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
318,155,2026-04-22-07-19-47 +0000,nypost,"Trump issues fresh Strait of Hormuz threat, sa...",https://nypost.com/2026/04/22/world-news/trump...
35,72,2026-04-22-22-11-28 +0000,nyt,"Heidi O’Neill, Formerly of Nike, Will Be New L...",https://www.nytimes.com/2026/04/22/business/lu...
69,67,2026-04-22-21-14-08 +0000,nypost,California’s oil lifeline goes to war with San...,https://nypost.com/2026/04/22/us-news/californ...
259,60,2026-04-22-12-50-00 +0000,wsj,Virginia voters approved a measure intended to...,https://www.wsj.com/politics/elections/virgini...
322,52,2026-04-22-06-26-31 +0000,nypost,Three vessels hit by Iranian fire in Strait of...,https://nypost.com/2026/04/22/world-news/iran-...
129,51,2026-04-22-19-09-00 +0000,wsj,"Rep. David Scott, a Georgia Democrat who spent...",https://www.wsj.com/politics/david-scott-georg...
288,47,2026-04-22-10-00-00 +0000,wapo,"Once accused of election fraud, former small-t...",https://www.washingtonpost.com/nation/2026/04/...
48,45,2026-04-22-21-52-00 +0000,wsj,Here are the key takeaways after Health Secret...,https://www.wsj.com/politics/policy/lawmakers-...
186,41,2026-04-22-16-58-00 +0000,wsj,More than a year into President Trump’s immigr...,https://www.wsj.com/economy/jobs/immigration-c...
309,38,2026-04-22-08-51-58 +0000,nypost,Mexico pyramid shooter Julio César Jasso plann...,https://nypost.com/2026/04/22/world-news/mexic...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)