## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-14-13-32 +0000,nyt,How the ‘Beautiful Game’ Is Deflecting America...,https://www.nytimes.com/2026/07/04/us/how-the-...
1,2026-07-04-14-10-04 +0000,startribune,Taylor Swift and Travis Kelce marry in front o...,https://www.startribune.com/a-fairytale-at-msg...
2,2026-07-04-14-07-31 +0000,bbc,Ukraine hits major oil terminal in Russia's St...,https://www.bbc.co.uk/news/articles/c8j2vmzxez...
3,2026-07-04-14-02-48 +0000,nyt,Storms Cause Power Outages for 1 Million in Mi...,https://www.nytimes.com/2026/07/04/us/storms-p...
4,2026-07-04-14-02-00 +0000,wsj,"Happy 250th, America! The Nation Celebrates a ...",https://www.wsj.com/us-news/happy-250th-americ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2586/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
97     trump     26
34        th     19
52      july     18
3    america     17
258    world     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
106,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,77
96,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...,75
44,2026-07-04-11-00-00 +0000,nypost,A happy 250th birthday letter to America from ...,https://nypost.com/2026/07/04/us-news/a-happy-...,75
29,2026-07-04-12-15-00 +0000,nypost,America’s most dangerous states to drive in du...,https://nypost.com/2026/07/04/us-news/americas...,74
100,2026-07-04-03-51-20 +0000,nypost,Trump rails against ‘mortal threat’ of communi...,https://nypost.com/2026/07/03/us-news/trump-ra...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
106,77,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...
29,74,2026-07-04-12-15-00 +0000,nypost,America’s most dangerous states to drive in du...,https://nypost.com/2026/07/04/us-news/americas...
37,61,2026-07-04-11-43-17 +0000,nyt,"Will Iran’s New Supreme Leader, Mojtaba Khamen...",https://www.nytimes.com/2026/07/04/world/middl...
96,44,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
36,40,2026-07-04-11-48-23 +0000,nyt,"For Cape Verde, There’s Victory in Their World...",https://www.nytimes.com/2026/07/04/world/afric...
22,31,2026-07-04-12-30-00 +0000,nypost,NYC’s major subway crime spikes in all borough...,https://nypost.com/2026/07/04/us-news/nycs-sub...
153,31,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
68,30,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...
42,30,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
24,28,2026-07-04-12-27-13 +0000,cbc,St. Petersburg oil terminal hit as Ukraine pre...,https://www.cbc.ca/news/world/st-petersburg-oi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)