## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-00-14-12 +0000,nypost,NYC boroughs declare official ‘OG Anunoby Day’...,https://nypost.com/2026/06/11/us-news/nyc-boro...
1,2026-06-12-00-13-37 +0000,nyt,Melania Trump Unveils New Investment Accounts ...,https://www.nytimes.com/2026/06/11/us/politics...
2,2026-06-12-00-05-27 +0000,nypost,Pair of ATVers rescue missing woman stuck in ‘...,https://nypost.com/2026/06/11/us-news/pair-of-...
3,2026-06-12-00-00-35 +0000,nyt,National Mall Grass Vandalized with ’86 47’ St...,https://www.nytimes.com/2026/06/11/us/national...
4,2026-06-12-00-00-00 +0000,wsj,How Texas Ranchers Are Fighting a Long-Eradica...,https://www.wsj.com/business/how-texas-rancher...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
15    trump     37
52     iran     34
77    world     28
78      cup     20
126  spacex     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...,126
6,2026-06-11-23-56-49 +0000,nyt,Iran War Live Updates: Trump Again Claims Deal...,https://www.nytimes.com/live/2026/06/11/world/...,125
13,2026-06-11-23-37-00 +0000,wsj,"Trump Cancels Iran Strikes, Says Peace Deal Co...",https://www.wsj.com/world/middle-east/trump-ir...,116
278,2026-06-11-12-46-03 +0000,nypost,Trump says US ‘will be taking Kharg Island’ oi...,https://nypost.com/2026/06/11/us-news/trump-sa...,109
137,2026-06-11-19-09-47 +0000,nypost,Dow jumps 900 points after Trump calls off Ira...,https://nypost.com/2026/06/11/business/dow-jum...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,126,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...
8,92,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...
16,60,2026-06-11-23-30-52 +0000,bbc,Elon Musk's SpaceX raises $75bn ahead of recor...,https://www.bbc.com/news/articles/cwy034q89j4o...
45,55,2026-06-11-22-21-02 +0000,nypost,How 3 million missing barrels of oil are keepi...,https://nypost.com/2026/06/11/world-news/how-3...
30,53,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
183,53,2026-06-11-17-34-06 +0000,nypost,Minnesota assassin Vance Boelter admits murder...,https://nypost.com/2026/06/11/us-news/minnesot...
247,47,2026-06-11-14-07-47 +0000,cbc,"As Canadians face high food prices, Carney lay...",https://www.cbc.ca/news/politics/food-security...
287,46,2026-06-11-11-58-14 +0000,bbc,Knicks fans go wild as New York team makes big...,https://www.bbc.com/news/articles/cr47lyzr4q9o...
98,43,2026-06-11-20-51-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/policy/showdown-b...
294,42,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)