## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-05-10-16-51 +0000,nypost,1 killed in attack on Crimea as Putin and Zele...,https://nypost.com/2026/07/05/world-news/crime...
1,2026-07-05-10-06-00 +0000,nyt,"America Marks Its 250th Birthday With Storms, ...",https://www.nytimes.com/2026/07/05/us/america-...
2,2026-07-05-10-00-00 +0000,latimes,"Barabak: Happy Birthday, America! You've weath...",https://www.latimes.com/politics/story/2026-07...
3,2026-07-05-10-00-00 +0000,latimes,Some beachgoers are creating living rooms with...,https://www.latimes.com/california/story/2026-...
4,2026-07-05-10-00-00 +0000,latimes,L.A. firefighters help rescue Venezuela quake ...,https://www.latimes.com/world-nation/story/202...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2317/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     27
11        th     21
190     july     21
52   funeral     15
201      new     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
144,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,104
91,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...,94
46,2026-07-05-04-55-52 +0000,nypost,Trump hails US as ‘light and the glory’ of the...,https://nypost.com/2026/07/05/us-news/trump-ha...,83
47,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...,81
36,2026-07-05-07-48-59 +0000,nypost,Three sons of Iran’s late Ayatollah Khamenei a...,https://nypost.com/2026/07/05/world-news/ayato...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
144,104,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
91,94,2026-07-04-23-18-35 +0000,nypost,"Putin, Zelensky among world leaders wishing US...",https://nypost.com/2026/07/04/world-news/putin...
124,37,2026-07-04-17-57-13 +0000,nypost,New gold rush as massive mining operation look...,https://nypost.com/2026/07/04/business/new-gol...
50,31,2026-07-05-04-05-29 +0000,nyt,The Brooklyn Bridge Briefly Catches Fire Durin...,https://www.nytimes.com/2026/07/04/nyregion/fi...
143,31,2026-07-04-15-41-47 +0000,nypost,JD Vance celebrates ‘250 years of America faci...,https://nypost.com/2026/07/04/us-news/jd-vance...
47,26,2026-07-05-04-35-00 +0000,wsj,The U.S. rang in its 250th birthday in the nat...,https://www.wsj.com/us-news/july-4-250-event-n...
7,23,2026-07-05-09-41-04 +0000,nypost,Fired NYC Council unpaid intern who demanded $...,https://nypost.com/2026/07/05/us-news/nyc-inte...
159,23,2026-07-04-12-27-13 +0000,cbc,St. Petersburg oil terminal hit as Ukraine pre...,https://www.cbc.ca/news/world/st-petersburg-oi...
120,21,2026-07-04-19-22-39 +0000,nypost,"Ex-MLB catcher hopes wife, daughter survived V...",https://nypost.com/2026/07/04/world-news/ex-ml...
167,21,2026-07-04-11-25-57 +0000,bbc,Pope urges Europe to do more for migrants as h...,https://www.bbc.co.uk/news/articles/c5yz83n7q5...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)