## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-14-52-05 +0000,nyt,Israel Cracks Down in West Bank City After Dea...,https://www.nytimes.com/2026/10/24/world/middl...
1,2026-10-24-14-50-53 +0000,nypost,Former Israeli military chief Gadi Eisenkot wh...,https://nypost.com/2026/10/24/world-news/forme...
2,2026-10-24-14-48-12 +0000,nyt,Live Updates: Protesters March in France Amid ...,https://www.nytimes.com/live/2026/10/24/world/...
3,2026-10-24-14-47-00 +0000,wsj,U.S. Evacuates Mideast Outposts After Suspecte...,https://www.wsj.com/world/middle-east/u-s-evac...
4,2026-10-24-14-45-30 +0000,bbc,Vanessa Trump says she is cancer-free six mont...,https://www.bbc.co.uk/news/articles/cm1dwzvn62...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2319/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
35      trump     38
108       new     17
56   election     16
22     france     13
195   ukraine     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
173,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,141
240,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,87
303,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,80
109,2026-10-24-07-17-44 +0000,bbc,White House says Melania Trump brokered truce ...,https://www.bbc.co.uk/news/articles/c6vgxkvl4w...,76
133,2026-10-24-02-15-51 +0000,nyt,Trump Officials Seek Block on Alaska Senate Ra...,https://www.nytimes.com/2026/10/23/us/politics...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
173,141,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
36,58,2026-10-24-12-32-42 +0000,cbc,France deploys thousands of police amid a new ...,https://www.cbc.ca/news/world/france-cost-of-l...
103,56,2026-10-24-08-00-00 +0000,cbc,Black Sea sailors thought a rescue boat was ra...,https://www.cbc.ca/news/world/black-sea-attack...
43,53,2026-10-24-12-00-00 +0000,nypost,Bombshell poll finds California voters say sta...,https://nypost.com/2026/10/24/us-news/xavier-b...
140,50,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
303,42,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...
47,42,2026-10-24-11-21-50 +0000,nypost,NJ middle school teacher busted in prostitutio...,https://nypost.com/2026/10/24/us-news/nj-teach...
235,40,2026-10-23-19-20-00 +0000,wsj,Gunman Kills One Near Paris in Suspected Attac...,https://www.wsj.com/world/europe/gunman-kills-...
204,40,2026-10-23-20-42-15 +0000,chitri,Wall Street loses ground under pressure from r...,https://www.chicagotribune.com/2026/10/23/wall...
262,38,2026-10-23-17-58-18 +0000,nypost,Ohio Dem Amy Acton’s estranged mom left five-d...,https://nypost.com/2026/10/23/us-news/amy-acto...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)