## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-23-05-57-00 +0000,wsj,U.S. Treasury Yields Fall as Oil Price Retreats,https://www.wsj.com/finance/investing/jgb-futu...
1,2026-06-23-05-48-14 +0000,nypost,85-year-old Florida man arrested for hitting 1...,https://nypost.com/2026/06/23/us-news/85-year-...
2,2026-06-23-05-41-54 +0000,nyt,Pakistan to Cut 18% Period Tax on Menstrual Pr...,https://www.nytimes.com/2026/06/22/world/asia/...
3,2026-06-23-05-39-17 +0000,bbc,US eases oil sanctions as Iran denies Vance cl...,https://www.bbc.com/news/articles/c3vy3nr63gxo...
4,2026-06-23-05-34-21 +0000,bbc,Tension 'likely' in new government - ex-chief,https://www.bbc.com/news/articles/cn0729ny7edo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2526/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
27       iran     29
81      trump     20
595   starmer     19
35        new     18
610  minister     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
81,2026-06-22-22-32-53 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...,94
254,2026-06-22-14-10-10 +0000,nypost,US waives Iran oil sanctions for two months in...,https://nypost.com/2026/06/22/world-news/us-wa...,83
321,2026-06-22-08-40-29 +0000,nypost,Emotional UK Prime Minister Keir Starmer resig...,https://nypost.com/2026/06/22/world-news/uk-pr...,79
67,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...,78
88,2026-06-22-21-51-37 +0000,bbc,What does Trump want from a new UK prime minis...,https://www.bbc.com/news/videos/c2kyz2eqxwvo?a...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
81,94,2026-06-22-22-32-53 +0000,nyt,Who Will Replace Keir Starmer as UK Prime Mini...,https://www.nytimes.com/2026/06/22/world/europ...
254,83,2026-06-22-14-10-10 +0000,nypost,US waives Iran oil sanctions for two months in...,https://nypost.com/2026/06/22/world-news/us-wa...
222,69,2026-06-22-15-30-00 +0000,wsj,The Supreme Court is about to decide four case...,https://www.wsj.com/politics/policy/the-suprem...
176,61,2026-06-22-17-38-00 +0000,wsj,Alan Greenspan’s legacy explained: how the Fed...,https://www.wsj.com/economy/central-banking/al...
296,49,2026-06-22-10-45-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
67,46,2026-06-22-23-30-00 +0000,wsj,The Trump administration stepped up the law- e...,https://www.wsj.com/politics/policy/trump-admi...
14,43,2026-06-23-03-55-00 +0000,bbc,Australia's coal and gas exports violate our h...,https://www.bbc.com/news/articles/cn8q5nx6jw6o...
20,41,2026-06-23-03-23-42 +0000,latimes,Shooting inside California library leaves 2 ad...,https://www.latimes.com/california/story/2026-...
121,36,2026-06-22-20-47-37 +0000,nyt,Vance Claims Progress in First Day of Iran Talks,https://www.nytimes.com/2026/06/22/world/middl...
279,34,2026-06-22-12-00-00 +0000,wsj,Chevron Strikes Power Deal With Microsoft for ...,https://www.wsj.com/business/energy-oil/chevro...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)