## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-24-10-08-40 +0000,bbc,"Nearly 90,000 told to evacuate as wildfire app...",https://www.bbc.co.uk/news/articles/c4gqlp0yzy...
1,2026-08-24-10-05-22 +0000,bbc,'Still scared to death': Thousands evacuate Ne...,https://www.bbc.co.uk/news/videos/cy0zr8lkr8lo...
2,2026-08-24-10-00-17 +0000,chitri,Most Cook County homeowners to see taxes rise ...,https://www.chicagotribune.com/2026/08/24/tax-...
3,2026-08-24-10-00-01 +0000,wapo,Democratic socialists’ biggest challenge? Thei...,https://www.washingtonpost.com/politics/2026/0...
4,2026-08-24-10-00-00 +0000,wsj,Nvidia’s Earnings Will Test Wall Street’s Fait...,https://www.wsj.com/articles/nvidias-earnings-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2671/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
123  trump     21
82   trade     14
83     war     12
252    new     12
158   iran     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
190,2026-08-23-13-22-13 +0000,nypost,Canadian PM Mark Carney claims country ‘at war...,https://nypost.com/2026/08/23/us-news/canadian...,71
166,2026-08-23-16-02-38 +0000,nypost,Iran’s top civilian leaders push for cutting a...,https://nypost.com/2026/08/23/us-news/irans-to...,67
199,2026-08-23-12-33-01 +0000,cbc,Trump says Canada 'wants the benefits' of bein...,https://www.cbc.ca/news/canada/trump-canada-tr...,60
138,2026-08-23-19-11-30 +0000,bbc,Trump says Canada wants 'benefits' of being US...,https://www.bbc.co.uk/news/articles/cx272np7vg...,59
10,2026-08-24-09-47-22 +0000,bbc,'Half my business will be gone' - Firms in Can...,https://www.bbc.co.uk/news/articles/cy0j0zz8l8...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
190,71,2026-08-23-13-22-13 +0000,nypost,Canadian PM Mark Carney claims country ‘at war...,https://nypost.com/2026/08/23/us-news/canadian...
91,45,2026-08-24-01-00-00 +0000,wsj,Kevin Warsh’s reluctance to signal where inter...,https://www.wsj.com/economy/central-banking/wa...
107,40,2026-08-23-22-58-50 +0000,nypost,Iran faces massive new triple-threat as Hormuz...,https://nypost.com/2026/08/23/world-news/iran-...
149,36,2026-08-23-18-11-55 +0000,nypost,Ex-Mayor Dan Sullivan backs Dan Sullivan to be...,https://nypost.com/2026/08/23/us-news/dan-sull...
158,30,2026-08-23-16-30-58 +0000,latimes,"Thousands evacuated, 6 hurt as Hawk fire grows...",https://www.latimes.com/california/story/2026-...
94,28,2026-08-24-00-34-00 +0000,wsj,Canada’s Carney Puts His ‘No Deal Is Better Th...,https://www.wsj.com/world/americas/canadas-car...
167,28,2026-08-23-16-01-28 +0000,nypost,Iranian-linked hackers shut down British power...,https://nypost.com/2026/08/23/world-news/irani...
202,26,2026-08-23-12-25-00 +0000,wsj,After weeks of marathon talks between U.S. and...,https://www.wsj.com/economy/trade/canada-annou...
6,25,2026-08-24-10-00-00 +0000,nypost,Chinatown leaders fire warning shot at Mamdani...,https://nypost.com/2026/08/24/us-news/chinatow...
4,25,2026-08-24-10-00-00 +0000,wsj,Nvidia’s Earnings Will Test Wall Street’s Fait...,https://www.wsj.com/articles/nvidias-earnings-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)