## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-30-14-19-49 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...
1,2026-03-30-14-19-47 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/30/world/...
2,2026-03-30-14-14-09 +0000,nypost,More than 100 teens arrested at wild spring br...,https://nypost.com/2026/03/30/us-news/more-tha...
3,2026-03-30-14-14-00 +0000,wsj,Air Canada CEO Rousseau to Exit After Bungled ...,https://www.wsj.com/articles/air-canada-ceo-mi...
4,2026-03-30-14-13-08 +0000,nypost,Despicable moment man rubs his genitals on wom...,https://nypost.com/2026/03/30/us-news/sexual-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2621/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
4     trump     35
0      iran     28
1       war     20
60      oil     15
206  killed     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-30-14-19-49 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...,120
156,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...,101
229,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...,97
120,2026-03-30-08-33-12 +0000,nypost,Trump says he could ‘take the oil in Iran’ as ...,https://nypost.com/2026/03/30/world-news/trump...,95
57,2026-03-30-11-57-14 +0000,nypost,Trump says deal will ‘probably’ be reached soo...,https://nypost.com/2026/03/30/us-news/trump-sa...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,120,2026-03-30-14-19-49 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/30/world/...
236,53,2026-03-29-14-35-49 +0000,nypost,Air Canada flight attendant who was ejected du...,https://nypost.com/2026/03/29/world-news/air-c...
229,49,2026-03-29-15-53-00 +0000,wsj,Iran warns the U.S. after a unit of U.S. Marin...,https://www.wsj.com/world/iran-warns-u-s-again...
117,47,2026-03-30-08-58-42 +0000,nypost,US allows Russian oil tanker to reach Cuba ami...,https://nypost.com/2026/03/30/world-news/us-al...
156,38,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...
131,35,2026-03-30-05-38-26 +0000,bbc,Fuel tax halved and free public transport offe...,https://www.bbc.com/news/articles/c937n0yxggeo...
24,31,2026-03-30-13-30-32 +0000,bbc,Latin Patriarch will have access to Jerusalem ...,https://www.bbc.com/news/articles/cvg0128z41eo...
106,30,2026-03-30-09-09-08 +0000,bbc,Three Lebanese journalists killed in Israeli s...,https://www.bbc.com/news/articles/cgme1j70294o...
115,28,2026-03-30-09-01-07 +0000,wapo,Israel targets Iran’s leaders with lethal expe...,https://www.washingtonpost.com/world/2026/03/3...
138,28,2026-03-30-04-12-22 +0000,nypost,Frontier passenger sparks panic with bomb thre...,https://nypost.com/2026/03/30/us-news/unruly-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)