## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-17-21-08-32 +0000,nyt,Miami Cubans Fear Trump Won’t Go Far Enough: ‘...,https://www.nytimes.com/2026/03/17/us/politics...
1,2026-03-17-21-06-31 +0000,cbc,IN PHOTOS | Celebrating St. Patrick's Day in C...,https://www.cbc.ca/news/world/st-patrick-s-day...
2,2026-03-17-21-05-07 +0000,nyt,Iran War Live Updates: Israel Says It Has Deal...,https://www.nytimes.com/live/2026/03/17/world/...
3,2026-03-17-21-04-03 +0000,nypost,Adorable elephant seal pup is found with huge ...,https://nypost.com/2026/03/17/us-news/seal-pup...
4,2026-03-17-21-03-51 +0000,wapo,U.S. tells all its embassies to ‘immediately’ ...,https://www.washingtonpost.com/national-securi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2742/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
3    trump     58
16    iran     52
17     war     31
20  israel     19
86     top     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
55,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...,249
42,2026-03-17-20-17-30 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,198
188,2026-03-17-14-09-35 +0000,cbc,Top U.S. counterterrorism official Joe Kent re...,https://www.cbc.ca/news/world/joe-kent-resigns...,193
137,2026-03-17-16-43-34 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,187
187,2026-03-17-14-11-41 +0000,latimes,'Cannot in good conscience': Trump's counterte...,https://www.latimes.com/world-nation/story/202...,160

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
55,249,2026-03-17-20-05-04 +0000,startribune,Top counterterrorism official Kent resigns ove...,https://www.startribune.com/top-counterterrori...
51,78,2026-03-17-20-08-51 +0000,bbc,Israel says it killed Iranian security chief A...,https://www.bbc.com/news/articles/c24deezq6meo...
172,55,2026-03-17-15-07-00 +0000,wsj,President Trump has made tightening voter-elig...,https://www.wsj.com/politics/policy/what-is-sa...
83,53,2026-03-17-19-14-20 +0000,nyt,"Flight Prices Are Up Amid Soaring Fuel Costs, ...",https://www.nytimes.com/2026/03/17/business/ai...
146,52,2026-03-17-16-11-15 +0000,nypost,Trump’s fiery response to NATO allies over Str...,https://nypost.com/2026/03/17/us-news/trump-sl...
161,52,2026-03-17-15-38-13 +0000,wapo,Trump has choked off Cuba’s oil supply. China ...,https://www.washingtonpost.com/world/2026/02/2...
331,44,2026-03-17-01-00-00 +0000,wsj,"For the fifth year running, Fed officials find...",https://www.wsj.com/economy/central-banking/fe...
122,41,2026-03-17-17-31-07 +0000,nypost,Dem challenger in Texas House race starred in ...,https://nypost.com/2026/03/17/us-news/dem-chal...
39,35,2026-03-17-20-22-50 +0000,nypost,"Monster who raped step-daughter, got her pregn...",https://nypost.com/2026/03/17/us-news/monster-...
230,32,2026-03-17-11-43-05 +0000,nypost,Rescue crews dig bodies out of the ruins of a ...,https://nypost.com/2026/03/17/world-news/rescu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)