## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-19-17-00-28 +0000,nypost,Microsoft exec’s widow faces man accused of pl...,https://nypost.com/2026/08/19/us-news/microsof...
1,2026-08-19-16-57-06 +0000,bbc,Behaviour guidelines for life in UK published ...,https://www.bbc.co.uk/news/articles/ceqe3y34e9...
2,2026-08-19-16-55-40 +0000,startribune,"Brown: Shaped by Iron Range roots, Amy Klobuch...",https://www.startribune.com/brown-shaped-by-ir...
3,2026-08-19-16-53-30 +0000,nyt,Rebel Ice Cream Files for Bankruptcy After Van...,https://www.nytimes.com/2026/08/19/business/re...
4,2026-08-19-16-52-20 +0000,nyt,Prosecutor Reduces Charges Against L.A.P.D. Wh...,https://www.nytimes.com/2026/08/19/us/lapd-off...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2391/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
225       trump     54
153     florida     35
159     primary     17
29          new     17
154  democratic     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
265,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...,149
233,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...,145
267,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...,142
275,2026-08-18-23-56-32 +0000,nyt,"Sydney Gruters, Wife of R.N.C. Chair, Wins Hou...",https://www.nytimes.com/2026/08/18/us/politics...,134
237,2026-08-19-02-58-35 +0000,nyt,Eric Barlow Wins Wyoming’s Republican Governor...,https://www.nytimes.com/2026/08/18/us/politics...,126

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
265,149,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...
263,91,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...
50,61,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
202,57,2026-08-19-08-10-01 +0000,wsj,Stock Market Today: Bond Yields Dive After Bes...,https://www.wsj.com/livecoverage/stock-market-...
55,55,2026-08-19-15-33-32 +0000,bbc,Israel confirms soldiers fired at car in which...,https://www.bbc.co.uk/news/articles/crl7yjlpx2...
248,51,2026-08-19-02-04-32 +0000,nyt,Cory Mills Loses Republican Primary Amid Assau...,https://www.nytimes.com/2026/08/18/us/politics...
138,45,2026-08-19-11-17-00 +0000,wsj,The Morning Risk Report: Pivotal Child Safety ...,https://www.wsj.com/risk-compliance-journal/th...
13,43,2026-08-19-16-34-44 +0000,nypost,Ex-Sen. Kyrsten Sinema reveals stunning moment...,https://nypost.com/2026/08/19/us-news/kyrsten-...
11,41,2026-08-19-16-38-37 +0000,nypost,China robot makers show off latest humanoids a...,https://nypost.com/2026/08/19/business/china-r...
395,39,2026-08-18-18-20-08 +0000,bbc,Global borrowing costs hit fresh highs over oi...,https://www.bbc.co.uk/news/articles/c1k1x1zdyw...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)