## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-28-13-00-18 +0000,nyt,Mideast Live Updates: U.S. and Iran Trade Atta...,https://www.nytimes.com/live/2026/06/28/world/...
1,2026-06-28-13-00-00 +0000,missionlocal,"Love, fate, destiny",https://missionlocal.org/2026/06/love-fate-des...
2,2026-06-28-12-51-59 +0000,bbc,Eleven killed after plane carrying skydivers c...,https://www.bbc.co.uk/news/articles/c5yz9yj9x7...
3,2026-06-28-12-49-46 +0000,nypost,Smiling sisters Cookie and Kitty charged with ...,https://nypost.com/2026/06/28/us-news/texas-si...
4,2026-06-28-12-47-36 +0000,nypost,"France records 1,000 excess deaths in record-b...",https://nypost.com/2026/06/28/world-news/franc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2487/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
43   venezuela     18
104      trump     14
277        new     14
3         iran     10
63        dead      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
74,2026-06-28-02-37-00 +0000,wsj,Rep. Julia Letlow won a hard-fought GOP Senate...,https://www.wsj.com/politics/elections/louisia...,60
129,2026-06-27-21-01-57 +0000,nypost,"Venezuela earthquake death toll tops 1,400 — w...",https://nypost.com/2026/06/27/world-news/venez...,56
164,2026-06-27-15-00-48 +0000,nypost,Miracle baby born on street beside earthquake ...,https://nypost.com/2026/06/27/world-news/mirac...,50
77,2026-06-28-02-14-29 +0000,nypost,Trump-backed Julia Letlow takes victory in Lou...,https://nypost.com/2026/06/27/us-news/louisian...,47
90,2026-06-28-00-53-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...,46

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
74,60,2026-06-28-02-37-00 +0000,wsj,Rep. Julia Letlow won a hard-fought GOP Senate...,https://www.wsj.com/politics/elections/louisia...
129,56,2026-06-27-21-01-57 +0000,nypost,"Venezuela earthquake death toll tops 1,400 — w...",https://nypost.com/2026/06/27/world-news/venez...
54,43,2026-06-28-07-53-00 +0000,wsj,"U.S., Iran Carry Out New Strikes, Testing Frag...",https://www.wsj.com/world/middle-east/mideast-...
27,28,2026-06-28-10-08-00 +0000,wsj,High interest rates and a chronic shortage of ...,https://www.wsj.com/economy/housing/how-to-sol...
90,28,2026-06-28-00-53-00 +0000,wsj,President Trump on Saturday announced that he ...,https://www.wsj.com/politics/policy/trump-taps...
165,28,2026-06-27-14-50-48 +0000,nypost,World Cup criminals cheated desperate fans out...,https://nypost.com/2026/06/27/world-news/world...
118,26,2026-06-27-21-39-15 +0000,bbc,Burnham will need a Moscow test as well as Mak...,https://www.bbc.co.uk/news/articles/cdxdwr0xk5...
117,25,2026-06-27-21-44-34 +0000,nypost,Hezbollah threatens to blow up Lebanon-Israel ...,https://nypost.com/2026/06/27/world-news/hezbo...
63,24,2026-06-28-04-12-18 +0000,nypost,4 dead amid flooding caused by heavy rains as ...,https://nypost.com/2026/06/28/us-news/kentucky...
123,24,2026-06-27-21-26-36 +0000,nypost,James Carville calls for formal Democratic par...,https://nypost.com/2026/06/27/media/james-carv...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)