## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-30-01-02-43 +0000,wapo,El-Sayed apologizes for March comments about M...,https://www.washingtonpost.com/politics/2026/0...
1,2026-08-30-01-00-00 +0000,wsj,Why Syracuse Can’t Attract the Students It Nee...,https://www.wsj.com/us-news/education/syracuse...
2,2026-08-30-00-59-15 +0000,nyt,A MAGA Uproar Ensued After a Bill Was Given a ...,https://www.nytimes.com/2026/08/29/us/stop-nic...
3,2026-08-30-00-36-32 +0000,nypost,"13 hostages, including 6 children, freed by Ha...",https://nypost.com/2026/08/29/world-news/13-ho...
4,2026-08-30-00-32-14 +0000,nypost,Horror as woman stabbed to death in wealthy Ca...,https://nypost.com/2026/08/29/us-news/horror-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2475/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
54        trump     27
37   california     12
203         new     11
145       nepal     10
60          oil     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...,67
27,2026-08-29-22-40-03 +0000,nypost,Florida rep deletes X post blasting Trump’s oi...,https://nypost.com/2026/08/29/us-news/maria-el...,57
26,2026-08-29-22-40-51 +0000,bbc,Trump hails 'historic' deal for US to control ...,https://www.bbc.co.uk/news/articles/cx2zlwe7qj...,56
99,2026-08-29-16-53-10 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...,56
183,2026-08-29-07-11-04 +0000,bbc,Ex-White House teleprompter operator ordered t...,https://www.bbc.co.uk/news/articles/c4gj2dl4x5...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,67,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...
103,38,2026-08-29-16-02-52 +0000,chitri,Nepal-China flood survivors reach safe areas a...,https://www.chicagotribune.com/2026/08/29/nepa...
161,35,2026-08-29-09-30-00 +0000,wsj,Scientists monitoring data from satellites and...,https://www.wsj.com/economy/global/the-stronge...
160,34,2026-08-29-10-00-00 +0000,latimes,California's new attempt to help struggling ne...,https://www.latimes.com/california/story/2026-...
121,32,2026-08-29-13-26-50 +0000,chitri,"Russian strike near Kyiv kills 37, in one of t...",https://www.chicagotribune.com/2026/08/29/russ...
91,31,2026-08-29-17-33-56 +0000,wapo,British far-right provocateur Milo Yiannopoulo...,https://www.washingtonpost.com/nation/2026/08/...
193,31,2026-08-29-02-15-00 +0000,wsj,The White House teleprompter operator under in...,https://www.wsj.com/politics/policy/white-hous...
197,27,2026-08-29-01-25-30 +0000,latimes,Missing man found dead just steps from Santa B...,https://www.latimes.com/california/story/2026-...
98,24,2026-08-29-16-56-24 +0000,nypost,Embattled NYC DSA leader Gustavo Gordillo blas...,https://nypost.com/2026/08/29/us-news/nyc-dsa-...
82,24,2026-08-29-18-20-32 +0000,nyt,"For LGBTQ Fans, Dolly Parton Inspired Their Wi...",https://www.nytimes.com/2026/08/29/us/dolly-pa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)