## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-16-58-23 +0000,startribune,"Trump's ambassador to Greece, Kimberly Guilfoy...",https://www.startribune.com/trump-ambassador-t...
1,2026-10-13-16-57-45 +0000,nypost,"Iran war could bring price hikes to banana, Am...",https://nypost.com/2026/10/13/business/iran-wa...
2,2026-10-13-16-49-03 +0000,nypost,Trump sends warning to ‘not nice’ Houthis afte...,https://nypost.com/2026/10/13/us-news/trump-se...
3,2026-10-13-16-47-19 +0000,nypost,Californians face power blackouts as utility w...,https://nypost.com/2026/10/13/us-news/22-calif...
4,2026-10-13-16-45-32 +0000,nyt,Russia Detains Japanese Journalist for Alleged...,https://www.nytimes.com/2026/10/13/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2612/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     46
236      he     18
39   russia     17
182     new     13
56     year     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
270,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,135
87,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,114
26,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,111
316,2026-10-12-21-20-51 +0000,bbc,Six Ukrainian energy sites hit by Russia since...,https://www.bbc.co.uk/news/articles/cvlyd4pdlw...,108
287,2026-10-12-22-55-42 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/12/us-news/new-whit...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
270,135,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...
44,68,2026-10-13-15-55-11 +0000,nypost,Six Flags shuts down iconic California roller ...,https://nypost.com/2026/10/13/us-news/six-flag...
265,61,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
46,60,2026-10-13-15-52-15 +0000,bbc,"MI5 chief warns of threats to UK from Russia, ...",https://www.bbc.co.uk/news/articles/c60rl5vwpk...
98,54,2026-10-13-13-26-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
131,51,2026-10-13-12-09-00 +0000,wsj,Oil Prices Fall as Traders Weigh Middle East R...,https://www.wsj.com/world/middle-east/oil-pric...
365,46,2026-10-12-17-55-17 +0000,nypost,"Saudi Arabia faces new missile, drone strikes ...",https://nypost.com/2026/10/12/world-news/saudi...
90,44,2026-10-13-14-00-00 +0000,wsj,Home sales in September rose for the first tim...,https://www.wsj.com/economy/housing/home-sales...
287,44,2026-10-12-22-55-42 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/12/us-news/new-whit...
159,42,2026-10-13-10-41-00 +0000,wsj,Medicare for All has become a defining policy ...,https://www.wsj.com/politics/policy/medicare-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)