## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-02-10-00-53 +0000,wapo,"As local politicians face threats, the cost of...",https://www.washingtonpost.com/nation/2026/05/...
1,2026-05-02-10-00-02 +0000,nyt,Most Canadians Support MAID. But the Issue of ...,https://www.nytimes.com/2026/05/02/world/canad...
2,2026-05-02-10-00-00 +0000,wsj,"News Quiz for May 2, 2026",https://www.wsj.com/business/media/news-quiz-f...
3,2026-05-02-09-55-07 +0000,wapo,Trump to downsize U.S. military presence in Ge...,https://www.washingtonpost.com/national-securi...
4,2026-05-02-09-50-13 +0000,nypost,Teen suspect in murder of 2 Kentucky bank empl...,https://nypost.com/2026/05/02/us-news/kentucky...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
20   trump     44
73    iran     34
57     war     25
421    new     14
106   will     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
135,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...,146
85,2026-05-02-00-41-43 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,137
282,2026-05-01-14-37-54 +0000,nypost,Trump not happy with Iran’s latest proposal to...,https://nypost.com/2026/05/01/us-news/iran-han...,129
127,2026-05-01-22-00-00 +0000,nyt,Trump Tells Congress Why He Doesn’t Need Its A...,https://www.nytimes.com/2026/05/01/us/politics...,128
72,2026-05-02-01-30-23 +0000,nypost,Trump administration pulling 5K troops out of ...,https://nypost.com/2026/05/01/world-news/trump...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
135,146,2026-05-01-21-44-00 +0000,wsj,"Trump says the Iran war is over, Spirit Airlin...",https://www.wsj.com/politics/policy/trump-says...
292,65,2026-05-01-13-54-56 +0000,nypost,Chirayu Rana — former JPMorgan banker at cente...,https://nypost.com/2026/05/01/business/chirayu...
309,56,2026-05-01-12-36-00 +0000,wsj,The Minneapolis Fed president wrote that heigh...,https://www.wsj.com/economy/central-banking/ri...
199,51,2026-05-01-19-21-00 +0000,wsj,Trump’s new Air Force One will arrive this sum...,https://www.wsj.com/politics/national-security...
99,44,2026-05-01-23-33-02 +0000,nypost,May Day protests ramp up in LA as agitators de...,https://nypost.com/2026/05/01/us-news/may-day-...
316,43,2026-05-01-12-09-18 +0000,nypost,Rep. Max Miller’s lawyers admit he lied about ...,https://nypost.com/2026/05/01/us-news/rep-max-...
205,40,2026-05-01-19-06-01 +0000,nypost,Nithya Raman whines about LA police union atta...,https://nypost.com/2026/05/01/us-news/nithya-r...
46,37,2026-05-02-04-56-32 +0000,nypost,Bill Maher drags Gavin Newsom for high-speed r...,https://nypost.com/2026/05/02/us-news/gavin-ne...
87,36,2026-05-02-00-21-30 +0000,missionlocal,"Gap’s CEO-to-worker pay is 1,690-to-1. Other f...",https://missionlocal.org/2026/05/sf-ceo-tax-pa...
24,34,2026-05-02-09-00-00 +0000,wapo,You could be losing thousands every time you c...,https://www.washingtonpost.com/business/2026/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)