## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-10-11-00-00 +0000,wsj,We Asked a Church Group to Weigh In on Trump. ...,https://www.wsj.com/us-news/we-asked-a-church-...
1,2026-05-10-11-00-00 +0000,missionlocal,Meet the Candidates: San Francisco’s District ...,https://missionlocal.org/2026/05/sf-election-d...
2,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...
3,2026-05-10-11-00-00 +0000,wsj,Allison Ellsworth’s Poppi Exit Made Her a Mega...,https://www.wsj.com/business/poppi-founder-all...
4,2026-05-10-11-00-00 +0000,wsj,The Factory Town Known as China’s Furniture Ca...,https://www.wsj.com/world/asia/the-factory-tow...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2664/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
136       world     10
114  hantavirus     10
101      labour     10
70         ship     10
69       cruise      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
52,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...,58
23,2026-05-10-09-48-12 +0000,nyt,Cruise Ship Linked to Hantavirus Outbreak Arri...,https://www.nytimes.com/2026/05/10/world/europ...,48
117,2026-05-09-20-03-22 +0000,nypost,Trump ready to ship US delegation to Moscow to...,https://nypost.com/2026/05/09/world-news/trump...,47
191,2026-05-09-12-00-00 +0000,nypost,‘Patient Zero’ in deadly hantavirus cruise shi...,https://nypost.com/2026/05/09/world-news/hanta...,47
84,2026-05-10-00-38-45 +0000,nyt,Passengers on Hantavirus Cruise Ship Will Dise...,https://www.nytimes.com/2026/05/09/world/afric...,47

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
52,58,2026-05-10-06-34-10 +0000,nypost,Hantavirus-ridden MV Hondius cruise ship ancho...,https://nypost.com/2026/05/10/world-news/hanta...
93,43,2026-05-09-23-10-03 +0000,nyt,A Scaled-Back Victory Day Parade Shows Putin’s...,https://www.nytimes.com/2026/05/09/world/europ...
17,34,2026-05-10-10-00-44 +0000,wapo,N.J. World Cup games will be in a county that ...,https://www.washingtonpost.com/nation/2026/05/...
104,33,2026-05-09-22-22-08 +0000,nypost,Trump waits for answer from Iran on peace prop...,https://nypost.com/2026/05/09/world-news/trump...
48,30,2026-05-10-07-41-36 +0000,nypost,Texas cold-case fugitive busted in Mexico as n...,https://nypost.com/2026/05/10/us-news/texas-fu...
169,30,2026-05-09-13-43-50 +0000,bbc,Labour MPs have put Starmer on notice after el...,https://www.bbc.com/news/articles/cx21e79qqlgo...
88,28,2026-05-10-00-00-00 +0000,wsj,Republicans are playing defense in Ohio and a ...,https://www.wsj.com/politics/elections/in-bid-...
136,27,2026-05-09-17-28-59 +0000,bbc,'We just hit somebody' - Frontier Airlines pla...,https://www.bbc.com/news/articles/c5y95782wyko...
140,26,2026-05-09-16-30-54 +0000,bbc,SNP leader John Swinney rules out Holyrood tal...,https://www.bbc.com/news/articles/cddpevvv97jo...
2,25,2026-05-10-11-00-00 +0000,wsj,China is increasingly dominating high-tech ind...,https://www.wsj.com/world/asia/the-factory-tow...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)