## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-03-11-03-09 +0000,nyt,The White House is readying a budget for the s...,https://www.nytimes.com/live/2026/04/03/busine...
1,2026-04-03-11-03-06 +0000,nyt,What to know about the report.,https://www.nytimes.com/live/2026/04/03/busine...
2,2026-04-03-11-00-46 +0000,bbc,"Burkina Faso must 'forget' about democracy, mi...",https://www.bbc.com/news/articles/cly0zp1xgz3o...
3,2026-04-03-11-00-33 +0000,nyt,"Biruté Galdikas, Champion of Endangered Orangu...",https://www.nytimes.com/2026/04/02/science/ear...
4,2026-04-03-11-00-00 +0000,nypost,The bizarre reason Hegseth’s right-hand man is...,https://nypost.com/2026/04/03/us-news/pete-heg...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2456/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
63     trump     64
43      iran     40
31       war     36
111  general     15
67     bondi     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
212,2026-04-02-20-20-20 +0000,nyt,Trump Says He’ll End the Iran War in Weeks. Wh...,https://www.nytimes.com/2026/04/02/us/politics...,168
161,2026-04-02-22-11-12 +0000,wapo,"As Trump doubles down on Iran war, markets shu...",https://www.washingtonpost.com/world/2026/04/0...,166
280,2026-04-02-16-18-14 +0000,latimes,"Trump speech on Iran war, recent remarks on oi...",https://www.latimes.com/politics/story/2026-04...,166
11,2026-04-03-10-16-02 +0000,nypost,Trump told Pam Bondi ‘I think it’s time’ day b...,https://nypost.com/2026/04/03/us-news/trump-to...,166
322,2026-04-02-13-41-27 +0000,bbc,'Be serious... don't speak every day': Macron ...,https://www.bbc.com/news/articles/cevk0e4ykwko...,157

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
212,168,2026-04-02-20-20-20 +0000,nyt,Trump Says He’ll End the Iran War in Weeks. Wh...,https://www.nytimes.com/2026/04/02/us/politics...
150,93,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...
11,78,2026-04-03-10-16-02 +0000,nypost,Trump told Pam Bondi ‘I think it’s time’ day b...,https://nypost.com/2026/04/03/us-news/trump-to...
25,58,2026-04-03-09-30-00 +0000,wsj,The March jobs report due Friday morning will ...,https://www.wsj.com/economy/jobs/what-were-loo...
276,51,2026-04-02-16-36-00 +0000,wsj,President Trump has used tariffs to remake U.S...,https://www.wsj.com/politics/policy/how-trump-...
80,46,2026-04-03-03-29-06 +0000,nyt,A Bid to Use Force to Open Strait of Hormuz Hi...,https://www.nytimes.com/2026/04/02/world/middl...
291,38,2026-04-02-15-49-43 +0000,nypost,Global airlines could go bankrupt as jet fuel ...,https://nypost.com/2026/04/02/business/global-...
6,38,2026-04-03-10-59-33 +0000,nyt,Iran War Live Updates: Drone Hits Kuwaiti Oil ...,https://www.nytimes.com/live/2026/04/03/world/...
103,36,2026-04-03-01-44-57 +0000,nypost,Ex-cop Kelsey Fitzsimmons shares graphic image...,https://nypost.com/2026/04/02/us-news/kelsey-f...
338,35,2026-04-02-12-40-00 +0000,wsj,Trump endorsed a two-part plan to quickly fund...,https://www.wsj.com/politics/policy/trump-lays...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)