## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-01-11-40 +0000,nyt,Amazon Cargo Jet Pilots Tried to Abort Landing...,https://www.nytimes.com/2026/09/09/us/politics...
1,2026-09-10-01-07-42 +0000,missionlocal,"The Frisc, nonprofit news site with strong hou...",https://missionlocal.org/2026/09/the-frisc-san...
2,2026-09-10-01-05-39 +0000,cbc,AI researchers 'earnestly believe' it could ki...,https://www.cbc.ca/news/business/anthropic-res...
3,2026-09-10-01-04-25 +0000,nyt,Fetterman’s Surprise GOP Convention Video Ange...,https://www.nytimes.com/2026/09/09/us/politics...
4,2026-09-10-01-00-00 +0000,wsj,They Lost Their Money to Scammers—and Now Batt...,https://www.wsj.com/finance/currencies/crypto-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2536/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
114       trump     63
46          new     27
32   convention     22
243     midterm     21
17           ai     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
145,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,143
371,2026-09-09-09-06-36 +0000,nyt,Will Trump’s Midterm Convention Help or Hurt R...,https://www.nytimes.com/2026/09/09/us/politics...,140
432,2026-09-09-01-29-17 +0000,nypost,GOP to rail against ‘socialist’ Dems at Dallas...,https://nypost.com/2026/09/08/us-news/gop-to-r...,138
43,2026-09-09-23-28-23 +0000,nyt,Why Trump’s Republican Midterm ‘Convention’ Is...,https://www.nytimes.com/2026/09/09/us/politics...,137
141,2026-09-09-20-29-49 +0000,nyt,Trump’s Midterm Pitch Clouded by Iran War and ...,https://www.nytimes.com/2026/09/09/business/ca...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
145,143,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
337,104,2026-09-09-10-42-00 +0000,wsj,The two-day GOP midterm convention kicks off W...,https://www.wsj.com/politics/elections/everyth...
301,75,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
138,73,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
305,63,2026-09-09-12-20-40 +0000,bbc,Petrol prices rise by 5p over a week as Iran w...,https://www.bbc.co.uk/news/articles/cj4jwlx77l...
219,58,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
173,49,2026-09-09-19-34-37 +0000,chitri,Tate brothers must stay locked up during their...,https://www.chicagotribune.com/2026/09/09/tate...
10,49,2026-09-10-00-47-04 +0000,chitri,A pilot of the Amazon cargo plane that careene...,https://www.chicagotribune.com/2026/09/09/amaz...
390,45,2026-09-09-08-00-00 +0000,cbc,Vietnamese firm targets Canadians with fake AI...,https://www.cbc.ca/news/canada/vietnam-canadia...
271,45,2026-09-09-14-45-00 +0000,wsj,Facing a three-way arms race with Russia and C...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)