## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-14-52-00 +0000,wsj,Opinion | No Helmet Technology Can Make Footba...,https://www.wsj.com/opinion/no-helmet-technolo...
1,2026-09-18-14-51-24 +0000,bbc,Ex-Labour deputy leader Tom Watson joins Palantir,https://www.bbc.co.uk/news/articles/cj62ed1d2p...
2,2026-09-18-14-51-05 +0000,nyt,German Art Institutions Prepare for a Fight as...,https://www.nytimes.com/2026/09/18/world/europ...
3,2026-09-18-14-50-32 +0000,nyt,U.S. Approves Visas for Iran’s U.N. Delegation,https://www.nytimes.com/2026/09/18/world/ameri...
4,2026-09-18-14-46-58 +0000,nypost,Emotional vigil held for NBC reporter and othe...,https://nypost.com/2026/09/18/us-news/emotiona...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
49   trump     32
199    new     24
273     ai     21
67   house     17
142  their     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
222,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,133
172,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...,102
324,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...,100
342,2026-09-17-17-47-52 +0000,nypost,White House issues explosive response to UN-ba...,https://nypost.com/2026/09/17/us-news/white-ho...,98
27,2026-09-18-14-03-00 +0000,wsj,A new Federal Reserve inquiry into the 2023 co...,https://www.wsj.com/economy/central-banking/ne...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
222,133,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...
362,77,2026-09-17-16-38-02 +0000,nypost,Pregnant newlywed found dead after Venice boat...,https://nypost.com/2026/09/17/world-news/pregn...
342,71,2026-09-17-17-47-52 +0000,nypost,White House issues explosive response to UN-ba...,https://nypost.com/2026/09/17/us-news/white-ho...
343,71,2026-09-17-17-46-14 +0000,nypost,"Chinese AI labs must accelerate development, s...",https://nypost.com/2026/09/17/business/chinese...
229,60,2026-09-17-23-24-31 +0000,nypost,New cat species identified for first time in 1...,https://nypost.com/2026/09/17/science/new-cat-...
327,55,2026-09-17-18-54-41 +0000,cbc,Judge orders Kennedy Center to give 30-day not...,https://www.cbc.ca/news/world/kennedy-center-t...
135,53,2026-09-18-09-59-52 +0000,wapo,"Their Gaza home was damaged, but they had nowh...",https://www.washingtonpost.com/world/2026/09/1...
270,51,2026-09-17-21-36-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...
282,47,2026-09-17-20-59-09 +0000,nypost,California AG Rob Bonta talks tough on Paramou...,https://nypost.com/2026/09/17/media/california...
172,43,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)