## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-02-21-45-07 +0000,nyt,Iran War Live Updates: Lebanon Peace Talks Res...,https://www.nytimes.com/live/2026/06/02/world/...
1,2026-06-02-21-45-05 +0000,nyt,Battling a Deadly Ebola Outbreak in Eastern Congo,https://www.nytimes.com/video/world/africa/100...
2,2026-06-02-21-45-05 +0000,nyt,MSC Ship Is Struck by Two Projectiles in Iraqi...,https://www.nytimes.com/2026/06/02/business/ms...
3,2026-06-02-21-40-22 +0000,nypost,MSG auctioning off 2 celebrity courtside seats...,https://nypost.com/2026/06/02/us-news/msg-auct...
4,2026-06-02-21-36-09 +0000,bbc,US military says it fired missile at Iran-boun...,https://www.bbc.com/news/articles/c5yx135yg53o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
43        trump     41
104  california     26
335         new     24
0          iran     18
115        will     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
66,2026-06-02-20-11-00 +0000,wsj,New York’s attorney general is leading a lawsu...,https://www.wsj.com/pro/sustainable-business/s...,124
320,2026-06-02-01-21-18 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...,109
143,2026-06-02-17-01-30 +0000,nypost,Trump will attend new White House Corresponden...,https://nypost.com/2026/06/02/us-news/white-ho...,107
47,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...,103
46,2026-06-02-20-51-00 +0000,wsj,The Trump administration is abandoning its $1....,https://www.wsj.com/politics/policy/gop-leader...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
66,124,2026-06-02-20-11-00 +0000,wsj,New York’s attorney general is leading a lawsu...,https://www.wsj.com/pro/sustainable-business/s...
274,77,2026-06-02-09-02-22 +0000,nyt,California Primary Elections: What to Watch in...,https://www.nytimes.com/2026/06/02/us/election...
0,72,2026-06-02-21-45-07 +0000,nyt,Iran War Live Updates: Lebanon Peace Talks Res...,https://www.nytimes.com/live/2026/06/02/world/...
47,62,2026-06-02-20-47-00 +0000,wsj,President Trump said he was appointing Bill Pu...,https://www.wsj.com/politics/policy/bill-pulte...
273,55,2026-06-02-09-30-00 +0000,wsj,Berkshire Hathaway’s $6.8 billion deal to acqu...,https://www.wsj.com/economy/housing/berkshire-...
174,50,2026-06-02-15-58-23 +0000,bbc,Two people shot dead amid Kenya protests again...,https://www.bbc.com/news/articles/cvgz7zny3pzo...
212,45,2026-06-02-14-16-45 +0000,nypost,Jill Biden claims White House docs ‘missed’ Jo...,https://nypost.com/2026/06/02/us-news/jill-bid...
9,38,2026-06-02-21-32-00 +0000,wsj,SpaceX’s roughly $1.75 trillion valuation (may...,https://www.wsj.com/politics/policy/spacexs-po...
204,34,2026-06-02-14-46-40 +0000,nypost,Activist short seller Andrew Left convicted of...,https://nypost.com/2026/06/02/business/activis...
323,33,2026-06-02-01-10-00 +0000,cbc,"At least 22 dead, dozens wounded as Russia lau...",https://www.cbc.ca/news/world/kyiv-attack-russ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)