## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-24-17-14-49 +0000,startribune,"In greater Minnesota, the data center boom is ...",https://www.startribune.com/greater-mn-data-ce...
1,2026-07-24-17-14-05 +0000,nypost,"Bahrain, Kuwait struck Iran following missile ...",https://nypost.com/2026/07/24/world-news/bahra...
2,2026-07-24-17-10-24 +0000,nyt,Iran War Live Updates: Netanyahu Says He Will ...,https://www.nytimes.com/live/2026/07/24/world/...
3,2026-07-24-17-08-24 +0000,nyt,Teen Charged in Georgia School Shooting Change...,https://www.nytimes.com/2026/07/24/us/colt-gra...
4,2026-07-24-17-03-46 +0000,nypost,"Bangladesh’s President Shahabuddin, 76, resign...",https://nypost.com/2026/07/24/world-news/bangl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
26   trump     50
50     new     42
11    iran     33
18     war     20
150    out     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-07-24-17-10-24 +0000,nyt,Iran War Live Updates: Netanyahu Says He Will ...,https://www.nytimes.com/live/2026/07/24/world/...,165
87,2026-07-24-14-52-00 +0000,wsj,"As the Iran war enters its fifth month, Presid...",https://www.wsj.com/politics/policy/trump-is-l...,146
227,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...,141
298,2026-07-23-22-08-32 +0000,chitri,"Next stop, Trump Station? Administration wants...",https://www.chicagotribune.com/2026/07/23/trum...,131
132,2026-07-24-13-41-20 +0000,nyt,Iran War and Trump’s Tariffs Threaten a Resili...,https://www.nytimes.com/2026/07/24/business/ir...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,165,2026-07-24-17-10-24 +0000,nyt,Iran War Live Updates: Netanyahu Says He Will ...,https://www.nytimes.com/live/2026/07/24/world/...
359,94,2026-07-23-19-49-29 +0000,nypost,Bill Ackman slams Mamdani policies as ‘very ba...,https://nypost.com/2026/07/23/business/bill-ac...
98,61,2026-07-24-14-34-52 +0000,nypost,16-year-old pleads guilty to all 55 counts in ...,https://nypost.com/2026/07/24/us-news/teenager...
377,58,2026-07-23-18-56-23 +0000,nypost,South Korean AI billionaire faces $1 billion d...,https://nypost.com/2026/07/23/business/south-k...
249,51,2026-07-24-02-00-00 +0000,wsj,Capital Account: When the Supreme Court struck...,https://www.wsj.com/politics/policy/trumps-tra...
312,47,2026-07-23-21-41-33 +0000,latimes,"War escalates, oil prices surge as Iran-backed...",https://www.latimes.com/politics/story/2026-07...
227,42,2026-07-24-08-22-00 +0000,wsj,The U.S. will impose tariffs ranging from 10% ...,https://www.wsj.com/economy/trade/trump-unveil...
83,39,2026-07-24-15-03-09 +0000,nypost,New home sales pick up in June — but higher mo...,https://nypost.com/2026/07/24/business/new-hom...
122,38,2026-07-24-14-02-26 +0000,bbc,Faisal Islam: The UK's Trump trade deal no lon...,https://www.bbc.co.uk/news/articles/c9v4ymwddw...
254,34,2026-07-24-01-40-38 +0000,nypost,US-made F-16 helps Ukraine take out Russian Su...,https://nypost.com/2026/07/23/world-news/ukrai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)