## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-03-19-03-45 +0000,bbc,Iran begins public mourning for Ayatollah kill...,https://www.bbc.co.uk/news/articles/cx2k4k7jqe...
1,2026-07-03-19-03-45 +0000,latimes,Police are searching for a mother and daughter...,https://www.latimes.com/california/story/2026-...
2,2026-07-03-19-01-14 +0000,nyt,"Once the Centerpiece of Celebration, a Faded D...",https://www.nytimes.com/2026/07/03/us/politics...
3,2026-07-03-19-00-40 +0000,bbc,Police criticise timing of decision on pubs st...,https://www.bbc.co.uk/news/articles/cd95v388k5...
4,2026-07-03-19-00-11 +0000,nypost,Racist Karen caught on camera abusing neighbor...,https://nypost.com/2026/07/03/us-news/video-sh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
79        trump     29
43          new     14
173          th     13
13   california     13
91         july     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
211,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...,96
186,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...,77
119,2026-07-03-11-55-27 +0000,nypost,What to expect at Trump’s epic 4th of July ‘Sa...,https://nypost.com/2026/07/03/us-news/what-to-...,77
189,2026-07-03-02-51-34 +0000,nypost,Secret Service member was Googling rooftop loc...,https://nypost.com/2026/07/02/us-news/secret-s...,74
279,2026-07-02-20-08-00 +0000,wsj,"What to know about ‘Trump Accounts,’ the new s...",https://www.wsj.com/personal-finance/trump-acc...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
211,96,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...
50,56,2026-07-03-16-27-36 +0000,nypost,Soupy heat dome means 4th of July fireworks wi...,https://nypost.com/2026/07/03/us-news/heat-dom...
114,56,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
5,46,2026-07-03-18-59-59 +0000,nypost,Beverly Hills cops get huge new pay raise — sp...,https://nypost.com/2026/07/03/us-news/beverly-...
189,45,2026-07-03-02-51-34 +0000,nypost,Secret Service member was Googling rooftop loc...,https://nypost.com/2026/07/02/us-news/secret-s...
131,40,2026-07-03-10-54-14 +0000,nypost,Monaco bomber who attacked Russia-linked oliga...,https://nypost.com/2026/07/03/world-news/monac...
12,39,2026-07-03-18-25-41 +0000,nypost,Heart-stopping video shows moment American fla...,https://nypost.com/2026/07/03/us-news/skydiver...
188,36,2026-07-03-03-26-16 +0000,nypost,Soccer fan who vanished while traveling to Wor...,https://nypost.com/2026/07/02/world-news/engli...
166,33,2026-07-03-08-23-35 +0000,nypost,Powerful Iranian Gen. Ahmad Vahidi emerges fro...,https://nypost.com/2026/07/03/world-news/irani...
186,33,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)