## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-06-07-09-57 +0000,bbc,"UK must obey international law over Iran, says...",https://www.bbc.com/news/videos/c4gjxenp09xo?a...
1,2026-03-06-07-08-13 +0000,nypost,From Michelin to moaning: Napa chef blasts aff...,https://nypost.com/2026/03/06/lifestyle/napa-m...
2,2026-03-06-06-38-00 +0000,wsj,Deutsche Lufthansa Posts In-Line Earnings On L...,https://www.wsj.com/business/earnings/deutsche...
3,2026-03-06-06-34-19 +0000,nyt,Israel Attacks Beirut and Tehran as Fighting i...,https://www.nytimes.com/live/2026/03/05/world/...
4,2026-03-06-06-33-45 +0000,nyt,3 Australians Were on U.S. Submarine that Sank...,https://www.nytimes.com/2026/03/06/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2583/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
5     iran     63
130  trump     53
67     war     35
134   noem     21
426    new     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
23,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/twho-is-ma...,213
118,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...,196
143,2026-03-05-22-56-23 +0000,nypost,Trump kicks Tucker Carlson out of MAGA movemen...,https://nypost.com/2026/03/05/media/trump-kick...,180
91,2026-03-06-00-59-42 +0000,nyt,House Turns Back Bid to Restrict Trump’s War P...,https://www.nytimes.com/2026/03/05/us/politics...,172
106,2026-03-06-00-17-50 +0000,nypost,Trump demands pardon for Netanyahu – so Israel...,https://nypost.com/2026/03/05/world-news/trump...,167

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
23,213,2026-03-06-05-05-00 +0000,wsj,President Trump’s pick to replace DHS Secretar...,https://www.wsj.com/politics/policy/twho-is-ma...
271,139,2026-03-05-18-25-03 +0000,bbc,UK firms pull fixed energy deals as Iran war p...,https://www.bbc.com/news/articles/c3ewwej0p13o...
22,97,2026-03-06-05-05-00 +0000,wsj,"Rep. Tony Gonzales (R., Texas) said he wouldn’...",https://www.wsj.com/politics/elections/texas-t...
118,84,2026-03-06-00-01-00 +0000,wsj,President Trump removed Kristi Noem as the sec...,https://www.wsj.com/politics/policy/trump-dhs-...
3,61,2026-03-06-06-34-19 +0000,nyt,Israel Attacks Beirut and Tehran as Fighting i...,https://www.nytimes.com/live/2026/03/05/world/...
131,60,2026-03-05-23-25-54 +0000,nyt,Analysis Suggests School Was Hit Amid U.S. Str...,https://www.nytimes.com/2026/03/05/world/middl...
213,60,2026-03-05-20-18-21 +0000,nypost,White House vows to ‘vigorously defend’ tariff...,https://nypost.com/2026/03/05/us-news/trumps-n...
148,44,2026-03-05-22-48-34 +0000,nypost,Pentagon labels Anthropic supply-chain risk da...,https://nypost.com/2026/03/05/business/pentago...
45,43,2026-03-06-03-43-09 +0000,48hills,"Airbnb, under pressure from labor, drops $120 ...",https://48hills.org/2026/03/airbnb-under-press...
215,42,2026-03-05-20-12-00 +0000,wsj,U.S. Has a Big Ask for China: Buy Less Oil fro...,https://www.wsj.com/world/china/u-s-has-a-big-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)