## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-09-19-17-55 +0000,nyt,"Sifting Through Venezuela Earthquakes’ Rubble,...",https://www.nytimes.com/2026/07/09/world/ameri...
1,2026-07-09-19-17-02 +0000,nypost,California mom goes ballistic after teen son’s...,https://nypost.com/2026/07/09/us-news/californ...
2,2026-07-09-19-16-25 +0000,nypost,NYC wants to hire $250K BQE fixer to save crum...,https://nypost.com/2026/07/09/us-news/nyc-want...
3,2026-07-09-19-13-23 +0000,nypost,NYC building tries to escape $35M verdict by s...,https://nypost.com/2026/07/09/us-news/nyc-buil...
4,2026-07-09-19-13-00 +0000,wsj,Charlie Kirk’s Accused Killer Wished ‘He Hadn’...,https://www.wsj.com/us-news/charlie-kirks-accu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
259       trump     40
82         iran     26
661     platner     21
662      senate     21
7    california     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
276,2026-07-09-00-16-02 +0000,nypost,Accused rapist Graham Platner finally announce...,https://nypost.com/2026/07/08/us-news/graham-p...,127
260,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...,127
268,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...,121
266,2026-07-09-01-13-44 +0000,nypost,Maine Democrats set convention to replace accu...,https://nypost.com/2026/07/08/us-news/maine-de...,107
118,2026-07-09-14-53-00 +0000,wsj,Political activists who recruited Graham Platn...,https://www.wsj.com/politics/elections/graham-...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
276,127,2026-07-09-00-16-02 +0000,nypost,Accused rapist Graham Platner finally announce...,https://nypost.com/2026/07/08/us-news/graham-p...
268,121,2026-07-09-01-00-00 +0000,wsj,"“To me, I think it’s over,” President Trump sa...",https://www.wsj.com/world/middle-east/inside-t...
199,52,2026-07-09-10-00-00 +0000,latimes,California soccer fans sue StubHub after it fa...,https://www.latimes.com/business/story/2026-07...
135,50,2026-07-09-14-11-32 +0000,nypost,New footage reveals destruction of Ayatollah K...,https://nypost.com/2026/07/09/world-news/ayato...
358,49,2026-07-08-19-26-00 +0000,wsj,Fed officials weighed rate hikes last month as...,https://www.wsj.com/economy/central-banking/fe...
260,41,2026-07-09-01-26-00 +0000,wsj,Democratic nominee Graham Platner said he woul...,https://www.wsj.com/politics/elections/graham-...
110,40,2026-07-09-15-21-17 +0000,bbc,"Ukraine strikes Russian ships near Crimea, esc...",https://www.bbc.co.uk/news/articles/c70yd1g67z...
92,38,2026-07-09-16-06-08 +0000,nypost,US existing home sales unexpectedly fall in Ju...,https://nypost.com/2026/07/09/business/us-exis...
236,36,2026-07-09-06-13-45 +0000,nypost,NY mom who recently moved to Ireland beaten to...,https://nypost.com/2026/07/09/world-news/ny-mo...
52,34,2026-07-09-17-29-54 +0000,nypost,Ex-Olympic canoeist David Hearn pleads not gui...,https://nypost.com/2026/07/09/us-news/ex-olymp...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)