## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-20-24-48 +0000,nyt,A Town in Quebec Is the First Governing Body t...,https://www.nytimes.com/2026/07/01/world/canad...
1,2026-07-01-20-22-00 +0000,wsj,"A big short gets bigger, General Mills rallies...",https://www.wsj.com/finance/investing/a-big-sh...
2,2026-07-01-20-22-00 +0000,wsj,A Big Short Gets Bigger,https://www.wsj.com/finance/investing/a-big-sh...
3,2026-07-01-20-19-56 +0000,nypost,Ohio motel fire kills 3 people trapped in room...,https://nypost.com/2026/07/01/us-news/ohio-mot...
4,2026-07-01-20-19-47 +0000,nyt,"Celebrating the World Cup, the English Ask: Wh...",https://www.nytimes.com/2026/07/01/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2324/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
63   trump     45
34   world     15
181    new     14
450   year     14
35     cup     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
164,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,111
335,2026-06-30-23-13-00 +0000,wsj,"Trump’s Friends Gave Him Tickets to World Cup,...",https://www.wsj.com/sports/trumps-friends-gave...,101
261,2026-07-01-09-00-00 +0000,nypost,Trump takes new Qatari jet for test flight to ...,https://nypost.com/2026/07/01/us-news/trump-ta...,94
136,2026-07-01-15-57-38 +0000,nyt,Trump Takes First Flight on New Air Force One ...,https://www.nytimes.com/2026/07/01/us/politics...,93
92,2026-07-01-17-27-05 +0000,nypost,Trump won’t renew USMCA deal with Canada and M...,https://nypost.com/2026/07/01/us-news/trump-wo...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
164,111,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
306,71,2026-07-01-02-00-00 +0000,wsj,The Supreme Court has wrapped up one of its mo...,https://www.wsj.com/politics/policy/how-suprem...
230,61,2026-07-01-10-49-02 +0000,nypost,Dog missing for month in Mexico found partying...,https://nypost.com/2026/07/01/world-news/dog-m...
63,43,2026-07-01-18-28-01 +0000,wapo,Fate of $2 trillion North American trade deal ...,https://www.washingtonpost.com/business/2026/0...
94,43,2026-07-01-17-25-54 +0000,nypost,1 airman missing after MH-60S Sea Hawk helicop...,https://nypost.com/2026/07/01/us-news/1-airman...
102,43,2026-07-01-17-12-00 +0000,wsj,Elizabeth Warren asked the Fed’s inspector gen...,https://www.wsj.com/economy/central-banking/wa...
125,42,2026-07-01-16-27-50 +0000,startribune,"A new Xcel rate plan could save you money, if ...",https://www.startribune.com/xcel-utility-mn-ti...
81,38,2026-07-01-17-58-05 +0000,nypost,"Kamala Harris reaches out to Mamdani, anti-Isr...",https://nypost.com/2026/07/01/us-news/kamala-h...
241,36,2026-07-01-10-00-00 +0000,latimes,"Gas giants use AI to raise prices, lawsuit say...",https://www.latimes.com/california/story/2026-...
194,34,2026-07-01-13-12-37 +0000,nypost,US-based ‘Amazon of South Korea’ forced to rec...,https://nypost.com/2026/07/01/business/us-base...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)