## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-30-16-56-56 +0000,nyt,Live Updates: Passengers Arrive in Israel Afte...,https://www.nytimes.com/live/2026/09/30/world/...
1,2026-09-30-16-56-04 +0000,nypost,Mamdani finally gets federal security clearanc...,https://nypost.com/2026/09/30/us-news/mamdani-...
2,2026-09-30-16-55-54 +0000,nyt,Congress Set to Leave Washington for the Midte...,https://www.nytimes.com/2026/09/30/us/politics...
3,2026-09-30-16-52-10 +0000,wapo,Pilot on Tel Aviv-bound flight tried to crash ...,https://www.washingtonpost.com/world/2026/09/3...
4,2026-09-30-16-50-52 +0000,nypost,Grim new details revealed in Cornell student’s...,https://nypost.com/2026/09/30/us-news/grim-new...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
18        trump     43
518          ai     24
35          new     22
154  california     16
139       court     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
336,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...,171
436,2026-09-29-17-27-33 +0000,chitri,President Trump says top tech firms have signe...,https://www.chicagotribune.com/2026/09/29/dona...,106
332,2026-09-29-21-55-00 +0000,cbc,Trump says top tech firms have signed accord t...,https://www.cbc.ca/news/world/ai-trump-agreeme...,101
414,2026-09-29-18-51-31 +0000,nypost,Trump calls for ‘tremendous self-regulation’ a...,https://nypost.com/2026/09/29/us-news/trump-ca...,95
156,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,93

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
336,171,2026-09-29-21-47-00 +0000,wsj,Defense Secretary Pete Hegseth will announce 2...,https://www.wsj.com/politics/national-security...
53,91,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...
275,75,2026-09-30-02-39-57 +0000,nypost,New UK Prime Minister Andy Burnham hints at Eu...,https://nypost.com/2026/09/29/world-news/new-u...
206,64,2026-09-30-10-00-00 +0000,latimes,"Hiltzik: No, AI bots won't extinguish humanity...",https://www.latimes.com/business/story/2026-09...
61,49,2026-09-30-15-19-42 +0000,nyt,"Court Pauses Execution of Christa Pike, Tennes...",https://www.nytimes.com/2026/09/30/us/christa-...
127,49,2026-09-30-13-30-00 +0000,nypost,California gas prices set for all-time record ...,https://nypost.com/2026/09/30/us-news/californ...
317,48,2026-09-29-23-00-00 +0000,wsj,He Was Rejected by Goldman Out of College. Now...,https://www.wsj.com/finance/investing/he-was-r...
318,47,2026-09-29-23-00-00 +0000,wsj,Americans in both parties back government-impo...,https://www.wsj.com/politics/policy/americans-...
110,42,2026-09-30-14-09-55 +0000,chitri,Republicans tee up bill on data centers for on...,https://www.chicagotribune.com/2026/09/30/repu...
349,40,2026-09-29-21-22-00 +0000,wsj,U.S. military expands drug war in Latin Americ...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)