## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-03-17-04-20 +0000,nyt,"In a Reversal, Doctors From Countries Under Tr...",https://www.nytimes.com/2026/05/03/us/trump-tr...
1,2026-05-03-17-04-06 +0000,nyt,Trump Says He Is Reviewing Iran’s Latest Offer...,https://www.nytimes.com/2026/05/02/us/politics...
2,2026-05-03-17-03-04 +0000,nyt,Fear and Vigilance Are Now Constant Companions...,https://www.nytimes.com/2026/05/03/us/jewish-a...
3,2026-05-03-16-58-26 +0000,wapo,Search underway for two U.S. soldiers missing ...,https://www.washingtonpost.com/nation/2026/05/...
4,2026-05-03-16-53-56 +0000,nypost,Iran attacks cargo ship in Strait of Hormuz,https://nypost.com/2026/05/03/world-news/iran-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
4       trump     18
105  airlines     11
11       iran     11
9          he      9
104    spirit      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...,66
28,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...,57
148,2026-05-02-23-03-03 +0000,bbc,Trump tells Congress ceasefire means he does n...,https://www.bbc.com/news/articles/c4g4xexy4w7o...,55
96,2026-05-03-09-00-00 +0000,wsj,Secret Service Director Sean Curran has earned...,https://www.wsj.com/politics/policy/he-rescued...,52
137,2026-05-03-00-34-18 +0000,nypost,Trump says he’s reviewing latest Iran proposal...,https://nypost.com/2026/05/02/world-news/trump...,50

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,66,2026-05-03-09-00-00 +0000,wsj,Jerome Powell didn’t want to remain on the Fed...,https://www.wsj.com/economy/central-banking/je...
5,44,2026-05-03-16-49-30 +0000,cbc,Cargo ship near Strait of Hormuz reports being...,https://www.cbc.ca/news/world/cargo-ship-strai...
42,44,2026-05-03-14-25-27 +0000,nypost,Former top Biden official all but admits admin...,https://nypost.com/2026/05/03/us-news/ex-biden...
125,43,2026-05-03-03-00-00 +0000,wsj,A mammoth economic stimulus passed last year i...,https://www.wsj.com/world/europe/germany-has-t...
167,31,2026-05-02-20-21-15 +0000,nypost,Zelensky warns of ‘unusual activity’ on Belaru...,https://nypost.com/2026/05/02/world-news/zelen...
128,29,2026-05-03-02-00-00 +0000,wsj,The U.S. is striving to dominate the drone evo...,https://www.wsj.com/politics/national-security...
33,25,2026-05-03-15-16-40 +0000,nypost,Haunting final texts emerge after CHP captain ...,https://nypost.com/2026/05/03/us-news/final-te...
43,25,2026-05-03-14-13-58 +0000,bbc,Two US service members reported missing in Mor...,https://www.bbc.com/news/articles/cn7prznmllko...
60,25,2026-05-03-12-06-34 +0000,bbc,In five charts: How UAE's exit could affect Op...,https://www.bbc.com/news/articles/c70vjpny0dno...
82,24,2026-05-03-09-36-15 +0000,nypost,Austrian police detain suspect in case of rat ...,https://nypost.com/2026/05/03/world-news/austr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)