## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-04-21-00-14 +0000,missionlocal,Meet the District 6 Candidate: What’s your No....,https://missionlocal.org/2026/08/meet-the-dist...
1,2026-08-04-20-14-54 +0000,chitri,"Dolton changes curfew to 9 p.m., adds penalty ...",https://www.chicagotribune.com/2026/08/04/dolt...
2,2026-08-04-20-14-00 +0000,wsj,SpaceX Revenue Rises 92% in Second Quarter,https://www.wsj.com/business/earnings/spacex-e...
3,2026-08-04-20-14-00 +0000,wsj,"Amgen Lifts Outlook on Strong Drug Sales, to E...",https://www.wsj.com/business/earnings/amgen-li...
4,2026-08-04-20-13-52 +0000,chitri,Gov. JB Pritzker signs protections against ins...,https://www.chicagotribune.com/2026/08/04/home...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
193   trump     36
279     new     24
159    iran     21
110    deal     16
109  hormuz     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
260,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...,121
321,2026-08-04-01-19-29 +0000,nyt,An Emerging Deal Between Iran and Oman to Reop...,https://www.nytimes.com/2026/08/03/us/politics...,112
89,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...,112
359,2026-08-03-21-49-00 +0000,wsj,"Trump discusses Jeanine Pirro’s removal, Iran ...",https://www.wsj.com/politics/policy/trump-disc...,109
357,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...,105

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
260,121,2026-08-04-10-00-00 +0000,nyt,The New Deal That Could Lock in Iran’s Control...,https://www.nytimes.com/2026/08/04/podcasts/th...
233,80,2026-08-04-11-09-00 +0000,wsj,The tension in the Democratic Party between th...,https://www.wsj.com/politics/elections/what-to...
169,65,2026-08-04-15-22-00 +0000,wsj,A divided Senate Judiciary Committee advanced ...,https://www.wsj.com/politics/policy/senate-jud...
89,53,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
220,50,2026-08-04-12-18-41 +0000,nypost,Ex-Trump White House press secretary seeks res...,https://nypost.com/2026/08/04/us-news/ex-trump...
357,48,2026-08-03-21-52-19 +0000,nypost,Trump lashes out at Big Oil for ‘making too mu...,https://nypost.com/2026/08/03/us-news/trump-la...
327,45,2026-08-04-00-25-00 +0000,wsj,"Trump has discussed ousting Jeanine Pirro, the...",https://www.wsj.com/politics/policy/trump-says...
234,45,2026-08-04-11-05-47 +0000,nypost,"Iran, Oman near deal to reopen Strait of Hormu...",https://nypost.com/2026/08/04/us-news/iran-oma...
313,41,2026-08-04-02-08-27 +0000,nypost,Ousted California GOP leader Heath Flora who ...,https://nypost.com/2026/08/03/us-news/ousted-c...
323,41,2026-08-04-01-00-00 +0000,wsj,From data centers to the massive increase in s...,https://www.wsj.com/economy/the-ai-boom-is-tra...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)