## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-19-26-05 +0000,nypost,US tariff refunds rush into company accounts a...,https://nypost.com/2026/06/29/business/us-tari...
1,2026-06-29-19-24-00 +0000,wsj,Japanese Authorities Seem Calm as Yen Hits Nea...,https://www.wsj.com/finance/currencies/most-as...
2,2026-06-29-19-23-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
3,2026-06-29-19-22-41 +0000,nyt,Newborn’s Body Is Found in a Portable Bathroom...,https://www.nytimes.com/2026/06/29/us/electric...
4,2026-06-29-19-20-30 +0000,nyt,Ethics Panel Tosses Misconduct Claims Against ...,https://www.nytimes.com/2026/06/29/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2482/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
102    court     34
101  supreme     31
27     trump     29
36       new     14
97      iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...,161
121,2026-06-29-16-19-32 +0000,nyt,Trump Renews Threat to Fire Fed Governor Lisa ...,https://www.nytimes.com/2026/06/29/us/politics...,140
135,2026-06-29-15-34-07 +0000,cbc,U.S. Supreme Court rules against Trump bid to ...,https://www.cbc.ca/news/world/us-scotus-ruling...,139
164,2026-06-29-14-19-39 +0000,nypost,Supreme Court blocks Trump bid to fire Fed gov...,https://nypost.com/2026/06/29/us-news/supreme-...,138
172,2026-06-29-13-46-31 +0000,latimes,Supreme Court refuses Trump's appeal of E. Jea...,https://www.latimes.com/politics/story/2026-06...,133

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,161,2026-06-29-17-38-00 +0000,wsj,Fedl governor Lisa Cook emerged as the victor ...,https://www.wsj.com/politics/policy/the-bigges...
47,61,2026-06-29-18-16-57 +0000,bbc,New 'No 10 North' plan will rebalance power in...,https://www.bbc.co.uk/news/articles/cx2jw5q5pd...
302,54,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...
76,46,2026-06-29-17-28-27 +0000,nypost,Costco receipt ties sicko to baby found dead i...,https://nypost.com/2026/06/29/us-news/californ...
169,43,2026-06-29-14-09-52 +0000,nypost,Trump must pony up $5M to E. Jean Carroll afte...,https://nypost.com/2026/06/29/us-news/supreme-...
258,38,2026-06-29-07-51-05 +0000,bbc,Mum rescued from Venezuela rubble with newborn...,https://www.bbc.co.uk/news/articles/clyw3rkj2p...
29,38,2026-06-29-18-36-13 +0000,nypost,"Mayor Zohran Mamdani, City Council deadlocked ...",https://nypost.com/2026/06/29/us-news/mayor-zo...
263,34,2026-06-29-07-18-14 +0000,bbc,South Korea football coach quits as president ...,https://www.bbc.co.uk/news/articles/cdx7jk0kq4...
157,34,2026-06-29-14-40-14 +0000,nyt,Supreme Court Upholds Grace Period to Count Ma...,https://www.nytimes.com/2026/06/29/us/politics...
2,32,2026-06-29-19-23-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)