## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-30-22-18-41 +0000,nyt,NPR Retracts Article That Mistakenly Said Just...,https://www.nytimes.com/2026/06/30/business/me...
1,2026-06-30-22-17-56 +0000,nypost,Missing woman linked to Philly horror house on...,https://nypost.com/2026/06/30/us-news/missing-...
2,2026-06-30-22-17-54 +0000,wapo,GOP rebellion over Trump’s elections overhaul ...,https://www.washingtonpost.com/business/2026/0...
3,2026-06-30-22-11-38 +0000,nyt,C.I.A. Reorganization Prioritizes Cyberoperations,https://www.nytimes.com/2026/06/30/us/politics...
4,2026-06-30-22-11-00 +0000,wsj,Wall Street’s Best Quarter in Six Years Will B...,https://www.wsj.com/finance/stocks/wall-street...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
113        court     35
112      supreme     32
26         trump     27
137          new     18
65   citizenship     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...,134
206,2026-06-30-14-36-30 +0000,nypost,Supreme Court strikes down Trump birthright ci...,https://nypost.com/2026/06/30/us-news/supreme-...,132
135,2026-06-30-18-01-22 +0000,nyt,"Supreme Court Upholds Birthright Citizenship, ...",https://www.nytimes.com/2026/06/30/us/politics...,131
81,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,130
122,2026-06-30-18-28-41 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,130

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,134,2026-06-30-14-48-28 +0000,latimes,Supreme Court rejects Trump's plan to limit bi...,https://www.latimes.com/politics/story/2026-06...
325,80,2026-06-30-00-11-00 +0000,wsj,A federal judge has permanently blocked the Tr...,https://www.wsj.com/politics/policy/judge-perm...
109,57,2026-06-30-19-15-00 +0000,wsj,A congressman who was absent from the Capitol ...,https://www.wsj.com/politics/elections/gop-law...
31,43,2026-06-30-21-32-23 +0000,nypost,US ally proposes teaming up with Iran to charg...,https://nypost.com/2026/06/30/world-news/us-al...
72,41,2026-06-30-20-22-00 +0000,wsj,"Stocks rise, the yen slides and a quiet Fed on...",https://www.wsj.com/finance/stocks/stocks-rise...
238,40,2026-06-30-12-47-52 +0000,bbc,Cape Verde will beat Argentina 1-0 in World Cu...,https://www.bbc.co.uk/news/articles/c4gyez6z34...
32,35,2026-06-30-21-30-52 +0000,bbc,Three-year-old rescued and taken to hospital s...,https://www.bbc.co.uk/news/articles/c1jykwk8n1...
5,34,2026-06-30-22-10-37 +0000,nypost,Bid to put noncitizen voting on LA’s November ...,https://nypost.com/2026/06/30/us-news/bid-to-p...
212,33,2026-06-30-14-28-11 +0000,nypost,Supreme Court lets GOP unlock massive war ches...,https://nypost.com/2026/06/30/us-news/supreme-...
336,33,2026-06-29-23-08-47 +0000,nyt,"Andy Burnham, the UK’s Likely Next Prime Minis...",https://www.nytimes.com/2026/06/29/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)