## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-15-02-57-59 +0000,nypost,New Hampshire woman trapped in urgent care cli...,https://nypost.com/2026/10/14/us-news/new-hamp...
1,2026-10-15-02-54-12 +0000,nypost,Hindu temple mass shooting thwarted after ‘soc...,https://nypost.com/2026/10/14/us-news/hindu-te...
2,2026-10-15-02-49-58 +0000,nypost,‘Made in California’ site selling homegrown pr...,https://nypost.com/2026/10/14/us-news/made-in-...
3,2026-10-15-02-49-29 +0000,nyt,Katie Zacharia Is Trump’s New Press Secretary....,https://www.nytimes.com/2026/10/14/us/politics...
4,2026-10-15-02-41-43 +0000,startribune,Live: Timberwolves do little to impress home c...,https://www.startribune.com/minnesota-timberwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2377/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
35       trump     40
373    ukraine     22
315  inflation     20
0          new     19
9           up     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
251,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...,157
241,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...,126
276,2026-10-14-15-25-31 +0000,nyt,Democrats Blame Trump After CPI Report Shows E...,https://www.nytimes.com/2026/10/14/business/ec...,125
315,2026-10-14-13-08-00 +0000,wsj,Katie Zacharia’s first briefing leaves some Tr...,https://www.wsj.com/politics/policy/trumps-new...,100
65,2026-10-14-23-06-56 +0000,nypost,Elon Musk points to Trump for Starshield throt...,https://nypost.com/2026/10/14/world-news/elon-...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
251,157,2026-10-14-16-14-00 +0000,wsj,The Trump administration must maintain White H...,https://www.wsj.com/us-news/law/trump-cant-rei...
241,126,2026-10-14-16-32-00 +0000,wsj,"Inflation picked up in September, with consume...",https://www.wsj.com/economy/cpi-inflation-repo...
76,75,2026-10-14-22-39-46 +0000,chitri,Chicago prays for native son Pope Leo XIV as h...,https://www.chicagotribune.com/2026/10/14/chic...
39,74,2026-10-15-00-28-22 +0000,nypost,Rep. Mike Lawler rips Cait Conley’s support of...,https://nypost.com/2026/10/14/us-news/rep-mike...
311,58,2026-10-14-13-11-17 +0000,bbc,Starlink restrictions in Ukraine war linked to...,https://www.bbc.co.uk/news/articles/cm2d6e62p4...
339,54,2026-10-14-11-45-00 +0000,wsj,The Morning Risk Report: Bank of America to Pa...,https://www.wsj.com/risk-compliance-journal/th...
315,52,2026-10-14-13-08-00 +0000,wsj,Katie Zacharia’s first briefing leaves some Tr...,https://www.wsj.com/politics/policy/trumps-new...
330,45,2026-10-14-12-26-13 +0000,bbc,Houthi missile hits Aramco building after Saud...,https://www.bbc.co.uk/news/articles/crx2d60y1p...
37,44,2026-10-15-00-29-48 +0000,nypost,America’s top party college rocked by sorority...,https://nypost.com/2026/10/14/us-news/inside-t...
56,41,2026-10-14-23-26-09 +0000,nypost,Anthropic revenue surges 45% to nearly $17B in...,https://nypost.com/2026/10/14/business/anthrop...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)