## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-07-16-54-03 +0000,startribune,Trump will join grieving families for the retu...,https://www.startribune.com/trump-will-join-gr...
1,2026-03-07-16-53-57 +0000,bbc,Iranian ambassador warns UK to be 'very carefu...,https://www.bbc.com/news/articles/cq6qp458zv1o...
2,2026-03-07-16-53-55 +0000,nyt,"Ian Huntley, Whose Murder of Schoolgirls Appal...",https://www.nytimes.com/2026/03/07/world/europ...
3,2026-03-07-16-50-45 +0000,nypost,Pedo’s sick trick to get to 6-year-old Girl Sc...,https://nypost.com/2026/03/07/us-news/pedos-si...
4,2026-03-07-16-44-08 +0000,nyt,Mideast Fighting: Live Updates: Trump Vows to ...,https://www.nytimes.com/live/2026/03/07/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2610/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
44    iran     57
0    trump     56
8      war     26
26    dies     20
194    new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
145,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...,200
219,2026-03-06-22-06-42 +0000,bbc,Trump wants to pick Iran's new leader - will a...,https://www.bbc.com/news/articles/c2k8339xn9jo...,163
70,2026-03-07-11-09-29 +0000,wapo,Trump team bashed Europe for a year. Now he wa...,https://www.washingtonpost.com/world/2026/03/0...,162
204,2026-03-06-22-39-00 +0000,wsj,"Trump wants Iran’s unconditional surrender, a ...",https://www.wsj.com/politics/policy/trump-want...,161
216,2026-03-06-22-12-02 +0000,wapo,Trump demands ‘UNCONDITIONAL SURRENDER’ from I...,https://www.washingtonpost.com/national-securi...,156

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
145,200,2026-03-07-02-04-06 +0000,bbc,Trump demands 'unconditional surrender' from I...,https://www.bbc.com/news/articles/c5yq82k1wk8o...
248,71,2026-03-06-20-37-00 +0000,wsj,A rough February jobs report exposed just how ...,https://www.wsj.com/economy/jobs/the-month-hea...
0,70,2026-03-07-16-54-03 +0000,startribune,Trump will join grieving families for the retu...,https://www.startribune.com/trump-will-join-gr...
213,54,2026-03-06-22-17-00 +0000,wsj,A federal prosecutor is looking to build crimi...,https://www.wsj.com/politics/national-security...
207,53,2026-03-06-22-35-00 +0000,wsj,How Robinhood’s New $695-a-Year Credit Card St...,https://www.wsj.com/finance/investing/how-robi...
89,43,2026-03-07-10-01-47 +0000,nyt,Russia Revels in a Sudden Reversal in Fortunes...,https://www.nytimes.com/2026/03/07/world/europ...
38,39,2026-03-07-14-09-46 +0000,nypost,MMA fighter let daughter starve to death in ho...,https://nypost.com/2026/03/07/us-news/mma-figh...
257,37,2026-03-06-20-06-24 +0000,nypost,SF mayor under fire for response to street att...,https://nypost.com/2026/03/06/us-news/san-fran...
117,36,2026-03-07-06-01-03 +0000,nypost,Sen. John Kennedy reveals why Kristi Noem was ...,https://nypost.com/2026/03/07/us-news/kristi-n...
142,34,2026-03-07-02-10-18 +0000,nypost,DOJ exploring possible charges against Cuban l...,https://nypost.com/2026/03/06/us-news/doj-expl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)