## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-17-18-56-15 +0000,nypost,Rep. Ilhan Omar’s apple cider vinegar assailan...,https://nypost.com/2026/09/17/us-news/rep-ilha...
1,2026-09-17-18-54-41 +0000,cbc,Judge orders Kennedy Center to give 30-day not...,https://www.cbc.ca/news/world/kennedy-center-t...
2,2026-09-17-18-54-13 +0000,nyt,U.S. Strike on Iranian School May Have Been Wa...,https://www.nytimes.com/2026/09/17/world/asia/...
3,2026-09-17-18-46-00 +0000,wsj,"Gold, Silver Futures Settle Higher",https://www.wsj.com/finance/commodities-future...
4,2026-09-17-18-34-23 +0000,nyt,"At Gettysburg, a Reporter Captured a Nation’s ...",https://www.nytimes.com/2026/09/17/us/gettysbu...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2385/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     50
113    fed     28
552  rates     23
69   house     19
243     ai     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
346,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...,203
285,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...,186
284,2026-09-17-00-59-00 +0000,wapo,Trump says he told Fed chief to ‘do what you w...,https://www.washingtonpost.com/business/2026/0...,153
198,2026-09-17-11-00-00 +0000,wsj,The trillion-dollar question: Did Fed Chairman...,https://www.wsj.com/politics/policy/the-trilli...,151
45,2026-09-17-17-16-13 +0000,nyt,Fed Chairman Warsh Escapes Trump’s Ire Over In...,https://www.nytimes.com/2026/09/17/business/tr...,134

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
346,203,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...
285,98,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...
27,93,2026-09-17-17-47-52 +0000,nypost,White House issues explosive response to UN-ba...,https://nypost.com/2026/09/17/us-news/white-ho...
201,70,2026-09-17-10-40-44 +0000,nypost,Mark Carney welcomes proposal for Canada to be...,https://nypost.com/2026/09/17/world-news/mark-...
345,68,2026-09-16-21-16-00 +0000,wsj,"The Fed raised rates, a top Democrat opposes a...",https://www.wsj.com/politics/policy/the-fed-is...
386,62,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
29,58,2026-09-17-17-46-14 +0000,nypost,"Chinese AI labs must accelerate development, s...",https://nypost.com/2026/09/17/business/chinese...
301,49,2026-09-16-23-16-00 +0000,wsj,The House passed legislation Wednesday that gi...,https://www.wsj.com/politics/policy/house-pass...
67,48,2026-09-17-16-38-02 +0000,nypost,Pregnant newlywed found dead after Venice boat...,https://nypost.com/2026/09/17/world-news/pregn...
6,44,2026-09-17-18-26-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)