## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-02-23-55-01 +0000,nypost,Heartbreaking Montana massacre obits reveal ‘p...,https://nypost.com/2026/09/02/us-news/heartbre...
1,2026-09-02-23-54-42 +0000,nypost,Ultra-exclusive Hamptons yacht club resumes fo...,https://nypost.com/2026/09/02/us-news/ultra-ex...
2,2026-09-02-23-53-38 +0000,nypost,"British gym teacher, 30, accused of having sex...",https://nypost.com/2026/09/02/world-news/briti...
3,2026-09-02-23-47-02 +0000,bbc,Rocky Horror star Tim Curry's cause of death r...,https://www.bbc.co.uk/news/articles/cy8z7wypzq...
4,2026-09-02-23-38-27 +0000,nyt,"In Small Iranian Town, a U.S. Attack Turns a W...",https://www.nytimes.com/2026/09/02/video/iran-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2435/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
62   trump     35
398   iran     22
128    new     20
331     up     15
709   lake     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
393,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...,93
110,2026-09-02-19-53-54 +0000,latimes,"Apple, Google rename Lake Ontario to Lake Amer...",https://www.latimes.com/business/story/2026-09...,87
108,2026-09-02-19-56-52 +0000,nyt,Trump Returns to a Familiar Playbook as the Wa...,https://www.nytimes.com/2026/09/02/us/politics...,85
392,2026-09-02-01-32-24 +0000,bbc,Apple Maps renames Lake Ontario as Lake Americ...,https://www.bbc.co.uk/news/articles/cddvyyz0e4...,84
409,2026-09-02-00-40-34 +0000,nyt,Map Apps Are Handling Trump’s Renaming of Lake...,https://www.nytimes.com/2026/09/01/us/lake-ont...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
393,93,2026-09-02-01-29-00 +0000,wsj,President Trump said he’s nominating Navy vete...,https://www.wsj.com/politics/national-security...
263,72,2026-09-02-12-55-00 +0000,wapo,"Watch Ontario, New York, residents sound off o...",https://www.washingtonpost.com/politics/2026/0...
386,69,2026-09-02-01-59-10 +0000,bbc,Charlie Kirk murder suspect pleads not guilty ...,https://www.bbc.co.uk/news/articles/cj4jn9q7ev...
284,66,2026-09-02-11-35-00 +0000,wsj,Massachusetts Sen. Ed Markey beat back a Democ...,https://www.wsj.com/politics/elections/sen-ed-...
288,64,2026-09-02-11-13-25 +0000,chitri,Iran fires on its Gulf neighbors after US mili...,https://www.chicagotribune.com/2026/09/02/iran...
117,53,2026-09-02-19-33-25 +0000,nypost,Bessent says Ukraine causing high gas prices: ...,https://nypost.com/2026/09/02/us-news/scott-be...
126,50,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
7,49,2026-09-02-23-36-49 +0000,bbc,Uber launches UK's first robotaxis with a driv...,https://www.bbc.co.uk/news/articles/ce9e838jzp...
128,47,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...
235,41,2026-09-02-14-40-20 +0000,bbc,Tiger Woods gets five-year driving ban after r...,https://www.bbc.co.uk/news/articles/c5y7xvpn5k...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)