## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-29-10-09-36 +0000,bbc,"British American Tobacco to cut 9,000 jobs",https://www.bbc.co.uk/news/articles/c3vyen243d...
1,2026-06-29-10-09-00 +0000,wsj,Comcast to Split Media and Tech Businesses Int...,https://www.wsj.com/business/media/comcast-to-...
2,2026-06-29-10-08-38 +0000,nyt,Mideast Live Updates: U.S. Reaches Deal With I...,https://www.nytimes.com/live/2026/06/29/world/...
3,2026-06-29-10-04-00 +0000,wsj,"Prosus Targets $5 Billion Buyback, More Acquis...",https://www.wsj.com/business/earnings/prosus-t...
4,2026-06-29-10-01-00 +0000,nypost,How digital price tags are spreading at retail...,https://nypost.com/2026/06/29/business/digital...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2611/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
18        iran     13
61   venezuela     10
44         nyc      8
162         he      8
297      world      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
124,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...,40
178,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...,40
198,2026-06-28-13-31-18 +0000,nypost,Iran must develop nuclear bomb to protect ‘pea...,https://nypost.com/2026/06/28/world-news/iran-...,39
47,2026-06-29-08-43-39 +0000,nypost,US-brokered peace agreement with Israel ‘will ...,https://nypost.com/2026/06/29/world-news/leban...,38
62,2026-06-29-07-51-05 +0000,bbc,Mum rescued from Venezuela rubble with newborn...,https://www.bbc.co.uk/news/articles/clyw3rkj2p...,37

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
124,40,2026-06-28-21-59-05 +0000,nypost,"How US turned up the heat on Iran with Hormuz,...",https://nypost.com/2026/06/28/world-news/how-u...
178,40,2026-06-28-15-56-03 +0000,nypost,"Stalker kills popular Colombian influencer, st...",https://nypost.com/2026/06/28/world-news/stalk...
62,37,2026-06-29-07-51-05 +0000,bbc,Mum rescued from Venezuela rubble with newborn...,https://www.bbc.co.uk/news/articles/clyw3rkj2p...
184,32,2026-06-28-15-24-29 +0000,nypost,Skydiving plane crashes after taking off in Fr...,https://nypost.com/2026/06/28/world-news/skydi...
202,31,2026-06-28-12-10-56 +0000,nypost,At least 2 dead after Ukraine drone assault se...,https://nypost.com/2026/06/28/world-news/at-le...
41,30,2026-06-29-09-00-00 +0000,wsj,"The University of California, Berkeley plans t...",https://www.wsj.com/us-news/education/nancy-pe...
172,30,2026-06-28-16-20-12 +0000,nypost,GOP governor in Ohio — where Trump claimed Hai...,https://nypost.com/2026/06/28/us-news/gop-ohio...
47,27,2026-06-29-08-43-39 +0000,nypost,US-brokered peace agreement with Israel ‘will ...,https://nypost.com/2026/06/29/world-news/leban...
151,27,2026-06-28-18-43-46 +0000,nypost,Bill Maher savages NYC radical Darializa Avila...,https://nypost.com/2026/06/28/us-news/bill-mah...
176,25,2026-06-28-16-00-00 +0000,wsj,Uncle Sam is slated to fork over more money th...,https://www.wsj.com/politics/policy/a-55-billi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)