## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-19-14-00 +0000,wsj,Trump Vents Growing Frustrations With Reflecti...,https://www.wsj.com/us-news/trump-vents-growin...
1,2026-06-21-19-11-30 +0000,nypost,NYC bill to ban horse carriages to be renamed ...,https://nypost.com/2026/06/21/us-news/nyc-bill...
2,2026-06-21-19-04-34 +0000,nyt,Hantavirus Quarantine Ends for 18 Americans Ex...,https://www.nytimes.com/2026/06/21/us/hantavir...
3,2026-06-21-19-00-00 +0000,cbc,Pierre Poilievre holds a press conference,https://www.cbc.ca/player/play/9.7243643?cmp=rss
4,2026-06-21-18-57-36 +0000,nyt,Strains Quickly Emerge on First Day of U.S.-Ir...,https://www.nytimes.com/live/2026/06/21/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
35    iran     25
0    trump     19
36   talks     15
127    new     11
120  world     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
27,2026-06-21-17-30-40 +0000,wapo,Trump threatens Iran over Hormuz as JD Vance h...,https://www.washingtonpost.com/world/2026/06/2...,88
113,2026-06-21-09-13-54 +0000,cbc,Trump threats shake up U.S.-Iran talks in Swit...,https://www.cbc.ca/news/world/jd-vance-switzer...,88
147,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...,83
36,2026-06-21-17-04-26 +0000,nyt,As Vance Offers Iran ‘Outstretched Hand’ in Ta...,https://www.nytimes.com/2026/06/21/world/middl...,76
72,2026-06-21-14-36-29 +0000,nypost,Trump breathes fire at Iran over Hormuz closur...,https://nypost.com/2026/06/21/world-news/trump...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
27,88,2026-06-21-17-30-40 +0000,wapo,Trump threatens Iran over Hormuz as JD Vance h...,https://www.washingtonpost.com/world/2026/06/2...
163,51,2026-06-20-22-11-17 +0000,nypost,Brazil soccer boss allegedly uses federation f...,https://nypost.com/2026/06/20/world-news/brazi...
66,29,2026-06-21-15-01-28 +0000,bbc,Ethiopia PM's party wins landslide as fears gr...,https://www.bbc.com/news/articles/cz750q5e3w3o...
160,29,2026-06-20-22-41-34 +0000,wapo,Cyclist arrested at Reflecting Pool is former ...,https://www.washingtonpost.com/nation/2026/06/...
5,26,2026-06-21-18-51-54 +0000,nypost,Freed Israeli hostage details horrific sexual ...,https://nypost.com/2026/06/21/world-news/freed...
45,25,2026-06-21-16-23-36 +0000,nyt,Keir Starmer Reflects on ‘Political Challenges...,https://www.nytimes.com/2026/06/21/world/europ...
50,25,2026-06-21-16-08-47 +0000,latimes,"How to deal with the smoke, health effects of ...",https://www.latimes.com/california/story/2026-...
35,21,2026-06-21-17-11-19 +0000,nypost,Long Island town renews controversial contract...,https://nypost.com/2026/06/21/us-news/islip-re...
51,21,2026-06-21-16-01-12 +0000,nypost,Gut punch for Sable Offshore as California cou...,https://nypost.com/2026/06/21/us-news/gut-punc...
68,20,2026-06-21-15-00-00 +0000,nypost,Bizarre twist as stunning decline in Bay Area ...,https://nypost.com/2026/06/21/us-news/oakland-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)