## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-29-21-10-30 +0000,nypost,Major California city takes drastic action to ...,https://nypost.com/2026/04/29/us-news/major-ca...
1,2026-04-29-21-09-42 +0000,nypost,Creep rapes 12-year-old girl inside NYC apartm...,https://nypost.com/2026/04/29/us-news/creep-ra...
2,2026-04-29-21-09-00 +0000,wsj,Opinion | You Can’t Trust ‘Climate Economics’,https://www.wsj.com/opinion/you-cant-trust-cli...
3,2026-04-29-21-09-00 +0000,wsj,Opinion | Reopening the Strait Is Now Job One ...,https://www.wsj.com/opinion/reopening-the-stra...
4,2026-04-29-21-08-51 +0000,nypost,Stanford University under federal investigatio...,https://nypost.com/2026/04/29/us-news/stanford...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2649/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
226    trump     39
84     court     31
83       new     22
32      iran     22
112  supreme     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
353,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...,183
324,2026-04-29-09-00-00 +0000,wsj,In a bid to keep construction of the White Hou...,https://www.wsj.com/politics/national-security...,148
143,2026-04-29-17-46-06 +0000,nyt,All Six Conservative Supreme Court Justices At...,https://www.nytimes.com/2026/04/29/us/politics...,136
236,2026-04-29-14-11-03 +0000,nypost,Supreme Court tosses Louisiana House map in ma...,https://nypost.com/2026/04/29/us-news/supreme-...,128
169,2026-04-29-16-28-37 +0000,nyt,Florida Lawmakers Were Debating New Congressio...,https://www.nytimes.com/2026/04/29/us/election...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
353,183,2026-04-29-04-15-00 +0000,wsj,"Business leaders, cabinet secretaries, Supreme...",https://www.wsj.com/politics/policy/jeff-bezos...
76,83,2026-04-29-19-43-00 +0000,wsj,The Fed held rates steady; but in a contentiou...,https://www.wsj.com/economy/central-banking/fe...
289,75,2026-04-29-10-46-00 +0000,wsj,War has imposed a heavy cost on Iran’s economy...,https://www.wsj.com/world/middle-east/iranians...
169,74,2026-04-29-16-28-37 +0000,nyt,Florida Lawmakers Were Debating New Congressio...,https://www.nytimes.com/2026/04/29/us/election...
28,66,2026-04-29-20-43-00 +0000,wsj,MGM Resorts Reports Lower First-Quarter Profit...,https://www.wsj.com/business/earnings/mgm-reso...
66,61,2026-04-29-19-59-00 +0000,wsj,The U.S. charged the governor of Mexico’s Sina...,https://www.wsj.com/world/americas/u-s-charges...
168,52,2026-04-29-16-30-04 +0000,nypost,Uber will let you book hotels in deal with Exp...,https://nypost.com/2026/04/29/business/uber-wi...
105,46,2026-04-29-18-55-00 +0000,wsj,Two California ballot initiatives funded in pa...,https://www.wsj.com/politics/policy/sergey-bri...
151,45,2026-04-29-17-19-26 +0000,nypost,Ex-FBI Director James Comey surrenders to feds...,https://nypost.com/2026/04/29/us-news/ex-fbi-d...
238,42,2026-04-29-14-09-31 +0000,nypost,WHCD suspect Cole Allen took smirking selfie w...,https://nypost.com/2026/04/29/us-news/whcd-sus...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)