## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-18-11-00-34 +0000,wapo,Bob Hall has died. The father of wheelchair ra...,https://www.washingtonpost.com/obituaries/2026...
1,2026-04-18-11-00-00 +0000,nypost,Queens Night Market is back —featuring a globa...,https://nypost.com/2026/04/18/lifestyle/queens...
2,2026-04-18-10-48-15 +0000,nypost,LA must pay $11.8M to man blinded by police pr...,https://nypost.com/2026/04/18/us-news/la-must-...
3,2026-04-18-10-42-01 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...
4,2026-04-18-10-41-59 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/18/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
28     iran     32
40    trump     25
128     new     19
36   strait     15
37   hormuz     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-04-18-10-42-01 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...,114
137,2026-04-17-21-50-49 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,105
52,2026-04-18-06-06-38 +0000,bbc,Oil prices plunge as Iran says Strait of Hormu...,https://www.bbc.com/news/articles/ckg045z73z1o...,97
193,2026-04-17-19-09-06 +0000,nyt,Oil Prices Fall Sharply After Iran Says Strait...,https://www.nytimes.com/2026/04/17/business/en...,90
91,2026-04-18-01-03-00 +0000,nyt,Lebanon Cease-Fire and Hormuz ‘Opening’ Raise ...,https://www.nytimes.com/2026/04/17/us/strait-o...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,114,2026-04-18-10-42-01 +0000,nyt,Iran War Live Updates: Iran’s Military Says It...,https://www.nytimes.com/live/2026/04/18/world/...
294,61,2026-04-17-13-30-00 +0000,nypost,Trump rips Mayor Mamdani for ‘destroying’ NYC ...,https://nypost.com/2026/04/17/us-news/trump-ri...
271,59,2026-04-17-14-54-56 +0000,nyt,New York New Jersey Stadium? Why MetLife Is Ch...,https://www.nytimes.com/2026/04/17/nyregion/fi...
127,50,2026-04-17-22-39-33 +0000,nyt,‘I Just Want to Be Back’: Thousands Rush South...,https://www.nytimes.com/2026/04/17/world/middl...
131,48,2026-04-17-22-19-00 +0000,wsj,Democratic Rep. Ilhan Omar of Minnesota said s...,https://www.wsj.com/politics/policy/ilhan-omar...
238,39,2026-04-17-16-33-34 +0000,nypost,Anthropic CEO Dario Amodei set to meet White H...,https://nypost.com/2026/04/17/business/anthrop...
201,39,2026-04-17-18-45-40 +0000,nyt,Lutnick Says Canada Trade Deal Needs to Be Rew...,https://www.nytimes.com/2026/04/17/world/canad...
169,39,2026-04-17-20-29-00 +0000,wsj,The DOJ is preparing to file an antitrust laws...,https://www.wsj.com/politics/policy/justice-de...
71,33,2026-04-18-02-32-59 +0000,nypost,Alec Baldwin to head back to court in LA as ci...,https://nypost.com/2026/04/17/us-news/alec-bal...
278,28,2026-04-17-14-27-26 +0000,nypost,Report of drone with ‘dangerous substances’ ne...,https://nypost.com/2026/04/17/world-news/uk-po...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)