## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-08-06-56-48 +0000,nypost,Washington police K-9 leaps into action after ...,https://nypost.com/2026/08/08/us-news/washingt...
1,2026-08-08-06-52-53 +0000,nypost,Kellogg to remove artificial dyes from cereals...,https://nypost.com/2026/08/08/business/kellogg...
2,2026-08-08-06-32-17 +0000,nypost,San Francisco dad questioned by park rangers f...,https://nypost.com/2026/08/08/us-news/san-fran...
3,2026-08-08-06-16-21 +0000,nypost,Jill Biden doubts she’ll see a woman president...,https://nypost.com/2026/08/08/us-news/jill-bid...
4,2026-08-08-06-12-56 +0000,bbc,Child among three killed in Russian missile at...,https://www.bbc.co.uk/news/articles/cz7dy8gq99...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3407/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
239   trump     41
260     new     22
27    court     20
689  market     14
763    jobs     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...,164
186,2026-08-07-17-15-00 +0000,wsj,A federal appeals court on Friday halted const...,https://www.wsj.com/politics/policy/white-hous...,147
111,2026-08-07-20-46-00 +0000,wsj,Trump revives effort to oust Fed governor Lisa...,https://www.wsj.com/politics/white-house-reviv...,117
120,2026-08-07-20-22-38 +0000,wapo,Trump says he’ll bring ballroom fight to Supre...,https://www.washingtonpost.com/politics/2026/0...,117
141,2026-08-07-19-25-36 +0000,wapo,Trump renews effort to fire Fed governor Lisa ...,https://www.washingtonpost.com/business/2026/0...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,164,2026-08-07-21-04-00 +0000,wsj,Fed governor Lisa Cook is back in Trump’s cros...,https://www.wsj.com/politics/policy/fed-govern...
229,69,2026-08-07-15-33-00 +0000,wsj,"The U.S. labor market shed jobs in July, an un...",https://www.wsj.com/economy/jobs/july-jobs-rep...
212,66,2026-08-07-16-03-00 +0000,wsj,A key senator said he would vote to confirm To...,https://www.wsj.com/politics/policy/second-rep...
288,65,2026-08-07-11-16-00 +0000,wsj,It seems like political scandals are happening...,https://www.wsj.com/politics/policy/is-misbeha...
24,64,2026-08-08-01-47-00 +0000,wsj,Defense Secretary Pete Hegseth revoked the sec...,https://www.wsj.com/politics/hegseth-strips-se...
107,57,2026-08-07-20-50-01 +0000,nypost,"Saudi Arabia, Turkey and Pakistan forge ‘attac...",https://nypost.com/2026/08/07/world-news/saudi...
110,50,2026-08-07-20-47-19 +0000,chitri,Senate passes sweeping Russia sanctions bill n...,https://www.chicagotribune.com/2026/08/07/sena...
154,41,2026-08-07-18-50-02 +0000,latimes,Meta ordered by New Mexico judge to pay $567 m...,https://www.latimes.com/business/story/2026-08...
25,37,2026-08-08-01-27-44 +0000,nypost,Father of missing Florida teen Sophia Cover be...,https://nypost.com/2026/08/07/us-news/heartbro...
191,36,2026-08-07-17-03-31 +0000,nypost,"Gavin Newsom rolls out $3,500 EV rebates for f...",https://nypost.com/2026/08/07/us-news/gavin-ne...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)