## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-02-35-07 +0000,nypost,Sudden death of California law student studyin...,https://nypost.com/2026/08/09/world-news/death...
1,2026-08-10-02-33-50 +0000,nypost,Passengers aboard doomed boat that flipped in ...,https://nypost.com/2026/08/09/us-news/passenge...
2,2026-08-10-02-13-48 +0000,nyt,Taylor Farms Voluntarily Recalls Fresh Jalapeñ...,https://www.nytimes.com/2026/08/09/business/ta...
3,2026-08-10-02-10-00 +0000,wsj,Asian Currencies Weaken Ahead of U.S. CPI Data,https://www.wsj.com/finance/currencies/asian-c...
4,2026-08-10-02-00-00 +0000,wsj,"In China, ‘Moles’ Are Leaking Official Secrets...",https://www.wsj.com/world/china/in-china-moles...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
65    trump     23
19      new      9
123    iran      9
183  senate      9
264      el      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
45,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...,78
50,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...,72
9,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...,60
40,2026-08-09-23-19-35 +0000,wapo,Trump picks longtime aide Will Scharf as new t...,https://www.washingtonpost.com/politics/2026/0...,60
141,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
45,78,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...
80,53,2026-08-09-19-53-25 +0000,nypost,Gavin Newsom confirms he’ll sit down with radi...,https://nypost.com/2026/08/09/us-news/gavin-ne...
141,37,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...
51,35,2026-08-09-22-10-00 +0000,wsj,Former President Joe Biden’s cancer has spread...,https://www.wsj.com/politics/hunter-bidens-com...
32,31,2026-08-10-00-00-00 +0000,wsj,The AI boom has pushed the bruising race for h...,https://www.wsj.com/real-estate/the-bruising-r...
9,28,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...
116,28,2026-08-09-15-51-04 +0000,nypost,Iran-backed Houthis attack Aramco refinery in ...,https://nypost.com/2026/08/09/world-news/iran-...
34,27,2026-08-09-23-47-30 +0000,bbc,You could be missing out on £150 off your ener...,https://www.bbc.co.uk/news/articles/czjlk8wx77...
152,26,2026-08-09-12-24-04 +0000,cbc,14-year-old accused in deadly school shooting ...,https://www.cbc.ca/news/world/accused-thai-sch...
46,24,2026-08-09-22-44-58 +0000,nypost,AG Letitia James steers $54M in taxpayer funds...,https://nypost.com/2026/08/09/us-news/ag-letit...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)