## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-23-13-18-00 +0000,wsj,Treasury Yields Rise as U.S. Job Market Remain...,https://www.wsj.com/finance/investing/jgbs-fal...
1,2026-07-23-13-17-24 +0000,wapo,Trump adds condition to nuclear deal with Saud...,https://www.washingtonpost.com/politics/2026/0...
2,2026-07-23-13-17-00 +0000,wsj,Tractor Supply Cuts Outlook Following Tough Qu...,https://www.wsj.com/business/earnings/tractor-...
3,2026-07-23-13-16-39 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/23/world/...
4,2026-07-23-13-15-01 +0000,nyt,Should Travelers Give Up on Summer in Western ...,https://www.nytimes.com/2026/07/23/travel/euro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     51
11      deal     30
63       new     25
191     iran     22
10   nuclear     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
419,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...,154
46,2026-07-23-12-23-41 +0000,nypost,Trump says Saudi Arabia nuclear deal ‘totally ...,https://nypost.com/2026/07/23/us-news/trump-sa...,147
262,2026-07-22-21-36-00 +0000,wsj,Trump Approves Landmark Nuclear Deal With Saud...,https://www.wsj.com/world/middle-east/trump-ap...,143
155,2026-07-23-07-13-36 +0000,nyt,How the Trump Administration’s Nuclear Deal Wi...,https://www.nytimes.com/2026/07/22/world/middl...,142
1,2026-07-23-13-17-24 +0000,wapo,Trump adds condition to nuclear deal with Saud...,https://www.washingtonpost.com/politics/2026/0...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
419,154,2026-07-22-14-46-02 +0000,nypost,Trump approves Saudi Arabia nuclear deal that ...,https://nypost.com/2026/07/22/world-news/trump...
402,87,2026-07-22-15-34-00 +0000,wsj,New York City Mayor Zohran Mamdani appointed L...,https://www.wsj.com/politics/in-surprise-move-...
427,71,2026-07-22-14-14-00 +0000,wsj,"R. James Woolsey, CIA director in Clinton admi...",https://www.wsj.com/politics/national-security...
203,61,2026-07-23-01-07-00 +0000,nypost,US carrying out new wave of Iran strikes as mi...,https://nypost.com/2026/07/22/world-news/us-ca...
141,54,2026-07-23-08-10-32 +0000,wsj,Stock Market Today: Oil Prices Hit $100 a Barr...,https://www.wsj.com/livecoverage/stock-market-...
47,50,2026-07-23-12-23-00 +0000,wsj,The European Central Bank held interest rates ...,https://www.wsj.com/economy/central-banking/re...
218,50,2026-07-22-23-55-25 +0000,latimes,D4vd's garage had signs of blood where girl's ...,https://www.latimes.com/california/story/2026-...
253,49,2026-07-22-21-55-29 +0000,nypost,Tesla profit disappoints as Elon Musk’s AI spe...,https://nypost.com/2026/07/22/business/tesla-p...
254,45,2026-07-22-21-50-39 +0000,nyt,House Republicans Pass Stock Trading Bill Tied...,https://www.nytimes.com/2026/07/22/us/politics...
139,41,2026-07-23-08-15-20 +0000,nypost,Long Island lunatic stabs beloved homeless man...,https://nypost.com/2026/07/23/us-news/long-isl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)