## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-27-09-09-36 +0000,bbc,Rationing power and diluting petrol - how Afri...,https://www.bbc.com/news/articles/cq8wkq1n9epo...
1,2026-03-27-09-05-16 +0000,bbc,Just Eat and Autotrader among firms investigat...,https://www.bbc.com/news/articles/cj37eeyz0epo...
2,2026-03-27-09-03-46 +0000,nyt,"Europeans Are Angry at Trump, but Often Forgiv...",https://www.nytimes.com/2026/03/27/world/europ...
3,2026-03-27-09-03-41 +0000,nyt,Where Might the Iran War Hit Your Wallet? Star...,https://www.nytimes.com/2026/03/27/dining/rasp...
4,2026-03-27-09-03-25 +0000,nyt,Resurgent Inflation Tests Faith in Fed’s Willi...,https://www.nytimes.com/2026/03/27/business/in...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
21  trump     57
8    iran     52
9     war     33
64    new     19
60   will     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
317,2026-03-26-16-18-00 +0000,wsj,President Trump has told associates in recent ...,https://www.wsj.com/politics/elections/trump-t...,206
21,2026-03-27-08-51-58 +0000,nyt,Iran War Live Updates: Trump Claims Progress i...,https://www.nytimes.com/live/2026/03/27/world/...,189
148,2026-03-26-23-45-00 +0000,wsj,The Trump administration is putting President ...,https://www.wsj.com/politics/policy/trumps-sig...,174
305,2026-03-26-16-54-14 +0000,latimes,"Trump projects confidence, claims Iran is 'beg...",https://www.latimes.com/world-nation/story/202...,164
116,2026-03-27-01-00-29 +0000,nyt,"As Markets Revolt in the Face of War, Trump Ex...",https://www.nytimes.com/2026/03/26/world/middl...,160

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
317,206,2026-03-26-16-18-00 +0000,wsj,President Trump has told associates in recent ...,https://www.wsj.com/politics/elections/trump-t...
353,64,2026-03-26-14-05-29 +0000,nypost,"Gang-rape victim, 25, whose suicide attempt le...",https://nypost.com/2026/03/26/world-news/gang-...
87,59,2026-03-27-03-33-00 +0000,wsj,President Trump said he would sign an executiv...,https://www.wsj.com/politics/policy/republican...
40,56,2026-03-27-08-00-00 +0000,cbc,"At historic low point, New Democrats descend o...",https://www.cbc.ca/news/politics/ndp-leadershi...
252,56,2026-03-26-18-52-16 +0000,nypost,Iran wants to charge ships for safe passage th...,https://nypost.com/2026/03/26/business/iran-wa...
28,53,2026-03-27-08-36-00 +0000,wsj,European Gas Prices on Track for Weekly Loss a...,https://www.wsj.com/articles/european-gas-pric...
140,50,2026-03-27-00-11-00 +0000,wsj,A U.S. federal judge on Thursday halted the Tr...,https://www.wsj.com/politics/policy/anthropic-...
370,44,2026-03-26-13-24-00 +0000,wsj,Lawmakers accused each other Wednesday of bein...,https://www.wsj.com/politics/policy/lawmakers-...
117,44,2026-03-27-01-00-00 +0000,wsj,Billions of dollars of sophisticated military ...,https://www.wsj.com/politics/national-security...
69,42,2026-03-27-05-18-00 +0000,nypost,"Florida CEO Davide Veglia killed, teen son hos...",https://nypost.com/2026/03/27/us-news/florida-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)