## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-21-10-35-13 +0000,nyt,Lebanese Troops Deploy in Israeli-Held Village...,https://www.nytimes.com/2026/07/21/world/middl...
1,2026-07-21-10-34-37 +0000,nyt,Two Young Brothers and Their Search for Venezu...,https://www.nytimes.com/2026/07/21/world/ameri...
2,2026-07-21-10-32-50 +0000,nypost,Treasury stopped nearly $100 million in taxpay...,https://nypost.com/2026/07/21/us-news/treasury...
3,2026-07-21-10-32-00 +0000,wsj,Chinese Destroyer’s Live-Fire Drill Draws Prot...,https://www.wsj.com/world/asia/chinese-destroy...
4,2026-07-21-10-31-06 +0000,bbc,UK borrowing falls in June but public finances...,https://www.bbc.co.uk/news/articles/cx2vd3qgjy...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2335/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7        new     39
153    trump     38
80      iran     30
57   burnham     30
515     will     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
80,2026-07-21-06-40-50 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...,138
7,2026-07-21-10-12-33 +0000,nyt,New UK Prime Minister Burnham Promises Hope an...,https://www.nytimes.com/2026/07/21/world/europ...,120
243,2026-07-20-19-51-00 +0000,wsj,The Trump administration sought phone records ...,https://www.wsj.com/politics/policy/doj-sought...,115
33,2026-07-21-09-39-56 +0000,nyt,UK’s New Prime Minister Burnham Orders Cut in ...,https://www.nytimes.com/2026/07/21/world/europ...,115
205,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
80,138,2026-07-21-06-40-50 +0000,nyt,"Andy Burnham, New UK Prime Minister, Names Joh...",https://www.nytimes.com/2026/07/20/business/an...
205,115,2026-07-20-21-20-18 +0000,nypost,Trump hits Canada with surprise 50% tariffs — ...,https://nypost.com/2026/07/20/us-news/trump-hi...
313,70,2026-07-20-17-07-50 +0000,nypost,Enraged Trump warns Iran each US soldier kille...,https://nypost.com/2026/07/20/us-news/enraged-...
107,69,2026-07-21-02-26-00 +0000,wsj,"Republican Sen. Darline Graham, the sister of ...",https://www.wsj.com/politics/elections/darline...
266,48,2026-07-20-18-59-07 +0000,nypost,California gas suffers another huge setback as...,https://nypost.com/2026/07/20/us-news/californ...
197,44,2026-07-20-21-38-40 +0000,startribune,"Dead mass shooting victim ID’d, one of 14 shot...",https://www.startribune.com/shooting-outside-m...
309,38,2026-07-20-17-16-29 +0000,chitri,Ex-Mexican drug lord Ismael ‘El Mayo’ Zambada ...,https://www.chicagotribune.com/2026/07/20/mexi...
363,37,2026-07-20-13-26-11 +0000,nypost,Trump says Canadian wildfires ‘poisoning our a...,https://nypost.com/2026/07/20/us-news/presiden...
143,36,2026-07-20-23-55-56 +0000,nypost,Family’s heroic dog fights off bear that charg...,https://nypost.com/2026/07/20/us-news/connecti...
220,35,2026-07-20-20-56-40 +0000,nypost,US doesn’t have enough missiles to protect tro...,https://nypost.com/2026/07/20/world-news/us-mi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)