## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-05-21-53-01 +0000,nypost,UK influencer’s penis enlargement injection pr...,https://nypost.com/2026/09/05/world-news/briti...
1,2026-09-05-21-49-32 +0000,chitri,Local libraries: Free internet could be hamper...,https://www.chicagotribune.com/2026/09/05/libr...
2,2026-09-05-21-46-53 +0000,nypost,Jamaican dancehall star wants justice for his ...,https://nypost.com/2026/09/05/us-news/jamaican...
3,2026-09-05-21-44-49 +0000,nypost,Accused murderer D4vd’s Hollywood Hills hideou...,https://nypost.com/2026/09/05/us-news/d4vds-ho...
4,2026-09-05-21-39-02 +0000,bbc,US envoys meet Putin in Moscow for Ukraine talks,https://www.bbc.co.uk/news/articles/cx2zqp46g8...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2321/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
131    trump     25
403      new     13
211  lindsay     10
212   clancy     10
87       war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
211,2026-09-04-22-58-11 +0000,latimes,Judge again halts Postal Service mail ballot p...,https://www.latimes.com/politics/story/2026-09...,68
78,2026-09-05-14-58-10 +0000,chitri,Missouri asks US Supreme Court to allow use of...,https://www.chicagotribune.com/2026/09/05/miss...,67
52,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...,67
20,2026-09-05-20-50-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,60
206,2026-09-04-23-10-01 +0000,nyt,Trump Says He Will Spend Some of His War Chest...,https://www.nytimes.com/2026/09/04/us/politics...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
211,68,2026-09-04-22-58-11 +0000,latimes,Judge again halts Postal Service mail ballot p...,https://www.latimes.com/politics/story/2026-09...
10,49,2026-09-05-21-25-39 +0000,chitri,Putin meets with US envoys at the Kremlin for ...,https://www.chicagotribune.com/2026/09/05/puti...
87,49,2026-09-05-14-03-43 +0000,chitri,US military hits 3 Iranian oil tankers after s...,https://www.chicagotribune.com/2026/09/05/us-m...
155,40,2026-09-05-07-20-18 +0000,nypost,UN endorses new world map showing Africa’s tru...,https://nypost.com/2026/09/05/world-news/afric...
131,40,2026-09-05-09-30-00 +0000,wsj,How do you view the major components of Americ...,https://www.wsj.com/politics/young-people-see-...
167,39,2026-09-05-03-25-58 +0000,bbc,What happens next after Lindsay Clancy's murde...,https://www.bbc.co.uk/news/articles/cj9x248npw...
47,36,2026-09-05-18-15-56 +0000,nyt,Nepal Floods Buried a House. The Woman Inside ...,https://www.nytimes.com/2026/09/05/world/asia/...
20,35,2026-09-05-20-50-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
199,30,2026-09-04-23-49-01 +0000,missionlocal,Mayor Lurie will indefinitely continue ‘90 day...,https://missionlocal.org/2026/09/mayor-lurie-w...
21,25,2026-09-05-20-46-57 +0000,nypost,California’s off-road paradise threatened as d...,https://nypost.com/2026/09/05/science/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)