## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-31-22-01-21 +0000,nypost,Trump signs executive order to tighten mail-in...,https://nypost.com/2026/03/31/us-news/trump-si...
1,2026-03-31-21-57-34 +0000,nypost,Apple discontinues well-known product after 20...,https://nypost.com/2026/03/31/business/apple-d...
2,2026-03-31-21-55-32 +0000,nyt,Iran War Live Updates: Iran’s Foreign Minister...,https://www.nytimes.com/live/2026/03/31/world/...
3,2026-03-31-21-54-00 +0000,wsj,Blue Owl Capital Closes New Asset-Backed Fund ...,https://www.wsj.com/finance/investing/blue-owl...
4,2026-03-31-21-51-54 +0000,nyt,Backdoor Funding of Homeland Security Agency C...,https://www.nytimes.com/2026/03/31/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2478/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     56
14    iran     51
15     war     39
107  judge     15
29     new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-03-31-21-55-32 +0000,nyt,Iran War Live Updates: Iran’s Foreign Minister...,https://www.nytimes.com/live/2026/03/31/world/...,212
195,2026-03-31-15-00-28 +0000,nypost,Trump tells Post war against Iran won’t last ‘...,https://nypost.com/2026/03/31/us-news/trump-te...,195
15,2026-03-31-21-40-07 +0000,startribune,Trump lashes out at allies as Iran war and str...,https://www.startribune.com/us-attacks-iranian...,184
66,2026-03-31-20-29-01 +0000,nypost,"Dow soars over 1,100 points as Trump sparks ho...",https://nypost.com/2026/03/31/business/dow-soa...,176
171,2026-03-31-16-05-20 +0000,wapo,Trump slams allies as Europeans show reluctanc...,https://www.washingtonpost.com/world/2026/03/3...,159

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,212,2026-03-31-21-55-32 +0000,nyt,Iran War Live Updates: Iran’s Foreign Minister...,https://www.nytimes.com/live/2026/03/31/world/...
72,66,2026-03-31-20-20-31 +0000,nypost,Trump’s $400M White House ballroom project hal...,https://nypost.com/2026/03/31/us-news/trumps-4...
205,62,2026-03-31-14-26-52 +0000,nypost,"Supreme Court sides with Christian counselor, ...",https://nypost.com/2026/03/31/us-news/supreme-...
208,59,2026-03-31-14-14-00 +0000,wsj,President Trump’s decision to allow a one-time...,https://www.wsj.com/world/a-russian-tanker-tes...
19,54,2026-03-31-21-34-47 +0000,nypost,Iran’s parliament approves plan to impose toll...,https://nypost.com/2026/03/31/world-news/iran-...
308,49,2026-03-31-07-40-08 +0000,wsj,Stock Market Today: Nasdaq Leads Rally Built o...,https://www.wsj.com/livecoverage/stock-market-...
144,47,2026-03-31-17-30-05 +0000,bbc,Palestinians convicted of lethal attacks face ...,https://www.bbc.com/news/articles/cp8dkd6lnjdo...
282,43,2026-03-31-09-39-27 +0000,nypost,Gas prices rise above $4 a gallon for first ti...,https://nypost.com/2026/03/31/business/gas-pri...
186,38,2026-03-31-15-16-42 +0000,nypost,Trump weighs in on Tiger Woods’ Florida rollov...,https://nypost.com/2026/03/31/sports/trump-on-...
303,36,2026-03-31-08-02-03 +0000,nypost,Iran strikes Kuwaiti oil tanker in drone attac...,https://nypost.com/2026/03/31/world-news/iran-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)