## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-09-18-54-32 +0000,nypost,Texas AG Ken Paxton announces giveaway of 7 mi...,https://nypost.com/2026/09/09/us-news/texas-ag...
1,2026-09-09-18-53-15 +0000,bbc,Two die at Moldovan border as Russia-Ukraine d...,https://www.bbc.co.uk/news/articles/cvgyvpxe3y...
2,2026-09-09-18-53-05 +0000,nyt,Trump’s Midterm Pitch Clouded by Iran War and ...,https://www.nytimes.com/2026/09/09/business/ca...
3,2026-09-09-18-53-01 +0000,nyt,Bond Market Rebuffs Treasury’s $6 Billion Plan...,https://www.nytimes.com/2026/09/09/business/ec...
4,2026-09-09-18-51-00 +0000,nyt,"William Anderson, Doctor and Civil Rights Lead...",https://www.nytimes.com/2026/09/09/us/william-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2325/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
18     trump     51
79       new     27
278      oil     23
19   midterm     16
23    canada     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
62,2026-09-09-17-09-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,128
369,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...,121
2,2026-09-09-18-53-05 +0000,nyt,Trump’s Midterm Pitch Clouded by Iran War and ...,https://www.nytimes.com/2026/09/09/business/ca...,116
285,2026-09-09-03-47-00 +0000,wsj,"President Trump gave cash gifts of $45,000 api...",https://www.wsj.com/politics/policy/trump-gift...,116
237,2026-09-09-09-06-36 +0000,nyt,Will Trump’s Midterm Convention Help or Hurt R...,https://www.nytimes.com/2026/09/09/us/politics...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
62,128,2026-09-09-17-09-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...
372,103,2026-09-08-21-49-00 +0000,wsj,The U.S. hit three Iranian oil tankers in resp...,https://www.wsj.com/politics/policy/u-s-launch...
160,84,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
333,80,2026-09-08-23-42-00 +0000,wsj,The Supreme Court rejected Missouri’s bid to u...,https://www.wsj.com/politics/policy/supreme-co...
53,62,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
369,59,2026-09-08-21-56-00 +0000,wapo,"As Canada’s tariffs take effect, Trump’s trade...",https://www.washingtonpost.com/business/2026/0...
331,54,2026-09-08-23-52-28 +0000,bbc,Chris Mason: Burnham looks to show he will go ...,https://www.bbc.co.uk/news/articles/c3v439n5xl...
200,49,2026-09-09-10-42-00 +0000,wsj,The two-day GOP midterm convention kicks off W...,https://www.wsj.com/politics/elections/everyth...
128,42,2026-09-09-14-42-00 +0000,wsj,Tax-break reversals on data centers underscore...,https://www.wsj.com/politics/policy/states-tha...
285,36,2026-09-09-03-47-00 +0000,wsj,"President Trump gave cash gifts of $45,000 api...",https://www.wsj.com/politics/policy/trump-gift...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)