## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-16-01-17-31 +0000,nypost,Mamdani slammed for ‘corrupting history’ about...,https://nypost.com/2026/05/15/us-news/mamdani-...
1,2026-05-16-01-14-48 +0000,nypost,Out-of-control NYC driver plows into group of ...,https://nypost.com/2026/05/15/us-news/out-of-c...
2,2026-05-16-01-14-16 +0000,nypost,Theo Von breaks silence after Joe Rogan expres...,https://nypost.com/2026/05/15/us-news/theo-von...
3,2026-05-16-01-14-12 +0000,nyt,Navy Aircraft Carrier to Complete Longest Depl...,https://www.nytimes.com/2026/05/15/us/uss-ford...
4,2026-05-16-01-00-00 +0000,wsj,With under six months to go before the midterm...,https://www.wsj.com/politics/elections/trump-r...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
45   trump     50
248  china     32
68     new     21
242     xi     20
260   iran     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
119,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...,129
30,2026-05-15-23-27-15 +0000,nypost,Trump: Xi ‘surprised’ by America’s AI advances...,https://nypost.com/2026/05/15/us-news/trump-xi...,125
76,2026-05-15-21-28-25 +0000,bbc,Trump warns Taiwan against declaring independe...,https://www.bbc.com/news/articles/ce8p61v7l68o...,123
282,2026-05-15-12-12-03 +0000,nyt,Nvidia’s Future in China Remains Unclear After...,https://www.nytimes.com/2026/05/15/business/nv...,119
177,2026-05-15-17-15-21 +0000,nyt,What to Watch at Trump and Xi’s U.S.-China Summit,https://www.nytimes.com/2026/05/13/business/ec...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
119,129,2026-05-15-20-10-44 +0000,nyt,Oil Prices Rise as Trump-Xi Summit Yields No C...,https://www.nytimes.com/2026/05/15/business/oi...
356,69,2026-05-15-02-08-00 +0000,wsj,New York Governor Says Fewer Second Homes to P...,https://www.wsj.com/us-news/n-y-gov-hochul-say...
75,69,2026-05-15-21-29-00 +0000,wsj,Elon Musk’s SpaceX aims to go public on June 1...,https://www.wsj.com/economy/central-banking/sp...
250,58,2026-05-15-14-00-00 +0000,nypost,Neighbors of SoCal mayor who worked as secret ...,https://nypost.com/2026/05/15/us-news/ex-mayor...
48,43,2026-05-15-22-22-52 +0000,nypost,Building jumper torpedoes onto awning of NYC b...,https://nypost.com/2026/05/15/us-news/building...
17,43,2026-05-16-00-07-13 +0000,nypost,Supreme Court rejects Virginia’s bid to restor...,https://nypost.com/2026/05/15/us-news/supreme-...
190,35,2026-05-15-16-37-30 +0000,nypost,Arizona school district accused of letting kid...,https://nypost.com/2026/05/15/us-news/arizona-...
50,35,2026-05-15-22-15-24 +0000,nyt,"Tina Peters, Colorado Election Denier, Will Be...",https://www.nytimes.com/2026/05/15/us/politics...
277,34,2026-05-15-12-53-57 +0000,bbc,Prisoner swap goes ahead as Kyiv mourns 24 kil...,https://www.bbc.com/news/articles/c5y049w8nqwo...
67,33,2026-05-15-21-44-06 +0000,nypost,Best student life experiences in America ranke...,https://nypost.com/2026/05/15/us-news/best-stu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)