## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-22-11-50-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
1,2026-09-22-11-48-23 +0000,bbc,Arteta agrees new deal with Premier League cha...,https://www.bbc.co.uk/sport/football/articles/...
2,2026-09-22-11-45-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
3,2026-09-22-11-44-34 +0000,bbc,British man missing after diving into Lake Com...,https://www.bbc.co.uk/news/articles/cx8d38djqm...
4,2026-09-22-11-41-39 +0000,bbc,What is the White House press pool and why is ...,https://www.bbc.co.uk/news/articles/c8dx5dy5rz...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
28        trump     58
7           new     28
24        house     19
221          ai     16
433  california     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
43,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...,170
207,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...,160
309,2026-09-21-18-31-17 +0000,nypost,Trump cuts ribbon on latest White House constr...,https://nypost.com/2026/09/21/us-news/trump-cu...,135
263,2026-09-21-20-38-00 +0000,wsj,President Trump has discussed kicking journali...,https://www.wsj.com/politics/policy/trump-has-...,134
224,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...,133

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
43,170,2026-09-22-10-52-00 +0000,wsj,Trump’s moves against the White House press po...,https://www.wsj.com/politics/trumps-second-ter...
207,102,2026-09-21-22-49-00 +0000,wsj,President Trump and New York City Mayor Zohran...,https://www.wsj.com/politics/policy/trump-and-...
382,79,2026-09-21-14-54-19 +0000,nypost,US pitches China on AI notification deal ahead...,https://nypost.com/2026/09/21/us-news/us-pitch...
14,65,2026-09-22-11-24-48 +0000,bbc,"Paramount settles lawsuit with US states, clea...",https://www.bbc.co.uk/news/articles/cm4gjr1qep...
269,60,2026-09-21-20-25-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
224,59,2026-09-21-22-11-00 +0000,wsj,The Trump administration is seeking to rebuild...,https://www.wsj.com/politics/policy/trump-prop...
407,50,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
313,48,2026-09-21-18-23-11 +0000,nypost,Major section of California’s $231B High-Speed...,https://nypost.com/2026/09/21/us-news/californ...
158,48,2026-09-22-02-15-16 +0000,nyt,Man Shot by ICE Agent Says His Car Was Struck ...,https://www.nytimes.com/2026/09/21/us/ice-shoo...
375,42,2026-09-21-15-36-00 +0000,wsj,"Illinois Gov. JB Pritzker, whose weight has be...",https://www.wsj.com/politics/policy/jb-pritzke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)