## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-19-16-42 +0000,nyt,Iran War Live Updates: Attacks in Gulf Threate...,https://www.nytimes.com/live/2026/05/04/world/...
1,2026-05-04-19-16-18 +0000,nypost,"Eric Swalwell sent X-rated videos, pervy messa...",https://nypost.com/2026/05/04/us-news/eric-swa...
2,2026-05-04-19-13-42 +0000,nyt,U.S. Shot Down Iranian Missiles and Drones Aim...,https://www.nytimes.com/2026/05/04/us/politics...
3,2026-05-04-19-12-44 +0000,nyt,3 Dead in Hantavirus Outbreak Aboard Cruise Sh...,https://www.nytimes.com/2026/05/03/well/cruise...
4,2026-05-04-19-11-29 +0000,nypost,Ex-JPMorgan banker Chirayu Rana pretended his ...,https://nypost.com/2026/05/04/business/ex-jpmo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2460/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
146   trump     21
0      iran     17
28   hormuz     12
27   strait     11
149     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
165,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...,84
245,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,75
209,2026-05-04-02-10-15 +0000,nyt,Trump Says U.S. Will Help Stranded Ships Leave...,https://www.nytimes.com/2026/05/03/us/politics...,70
168,2026-05-04-10-34-00 +0000,wsj,Trump Says U.S. Will Guide Stranded Ships Thro...,https://www.wsj.com/world/middle-east/trump-sa...,69
63,2026-05-04-17-16-46 +0000,nyt,Oil Jumps as Violence Flares After Trump’s Off...,https://www.nytimes.com/2026/05/03/business/oi...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
165,84,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...
244,55,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
161,43,2026-05-04-11-15-00 +0000,nypost,World Liberty Financial hits back at crypto bi...,https://nypost.com/2026/05/04/business/world-l...
32,38,2026-05-04-18-06-28 +0000,nypost,Judge apologizes to White House Correspondents...,https://nypost.com/2026/05/04/us-news/judge-ap...
227,33,2026-05-03-23-24-16 +0000,nypost,Ex-NYC Mayor Rudy Giuliani hospitalized in cri...,https://nypost.com/2026/05/03/us-news/ex-nyc-m...
19,31,2026-05-04-18-40-26 +0000,nypost,New Mexico’s proposed kids safety fixes for In...,https://nypost.com/2026/05/04/business/new-mex...
115,31,2026-05-04-15-22-38 +0000,nypost,Supreme Court restores access to abortion pill...,https://nypost.com/2026/05/04/us-news/supreme-...
187,31,2026-05-04-09-00-00 +0000,wapo,Poisonous black rain falls in Russia as Ukrain...,https://www.washingtonpost.com/world/2026/05/0...
76,29,2026-05-04-16-53-41 +0000,nypost,Possible cause revealed in ‘12- to 14-alarm’ w...,https://nypost.com/2026/05/04/us-news/possible...
181,27,2026-05-04-09-08-33 +0000,nyt,"With World Distracted by Iran War, Israeli Set...",https://www.nytimes.com/2026/05/04/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)