## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
1,2026-10-04-14-38-01 +0000,chitri,US Marine arrested for alleged murder of a wom...,https://www.chicagotribune.com/2026/10/04/us-m...
2,2026-10-04-14-37-14 +0000,nyt,Houthis Claim Attack on Aramco as Yemen Confli...,https://www.nytimes.com/2026/10/04/world/middl...
3,2026-10-04-14-26-20 +0000,wapo,Trump launches ‘Super Intelligence Force’ afte...,https://www.washingtonpost.com/politics/2026/1...
4,2026-10-04-14-17-00 +0000,wsj,FlyDubai Attack Adds New Risks to Dubai’s War-...,https://www.wsj.com/world/middle-east/flydubai...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2645/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
1       trump     20
33   flydubai     17
9         new     13
175     pilot      9
490       off      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
217,2026-10-03-14-52-27 +0000,nyt,FlyDubai Co-Pilot Used Crash Ax in ‘Terrorist’...,https://www.nytimes.com/2026/10/03/world/middl...,59
0,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...,58
198,2026-10-03-16-50-36 +0000,nypost,Trump gushes over blue-collar flydubai hero wh...,https://nypost.com/2026/10/03/us-news/trump-gu...,57
169,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...,56
111,2026-10-04-02-14-00 +0000,wsj,A new White House task force will have 120 day...,https://www.wsj.com/tech/ai/new-ai-task-force-...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
217,59,2026-10-03-14-52-27 +0000,nyt,FlyDubai Co-Pilot Used Crash Ax in ‘Terrorist’...,https://www.nytimes.com/2026/10/03/world/middl...
0,58,2026-10-04-14-41-21 +0000,chitri,President Trump names national intelligence di...,https://www.chicagotribune.com/2026/10/04/jay-...
206,44,2026-10-03-16-20-59 +0000,cbc,Tennessee prisons chief to resign after failed...,https://www.cbc.ca/news/world/tennessee-prison...
39,39,2026-10-04-10-00-38 +0000,chitri,"Illinois Senate race: Republican Don Tracy, a ...",https://www.chicagotribune.com/2026/10/04/illi...
118,36,2026-10-04-01-35-10 +0000,nypost,Debris from vanished Boston-bound plane found ...,https://nypost.com/2026/10/03/world-news/debri...
161,34,2026-10-03-21-11-50 +0000,nypost,Al Qaeda calls for copycats to target US citiz...,https://nypost.com/2026/10/03/world-news/al-qa...
105,33,2026-10-04-03-37-19 +0000,nypost,Georgia singer charged after allegedly slappin...,https://nypost.com/2026/10/03/us-news/georgia-...
151,32,2026-10-03-22-35-04 +0000,latimes,Victim of fatal Culver CityBus shooting was lo...,https://www.latimes.com/california/story/2026-...
169,30,2026-10-03-20-08-18 +0000,nypost,Iran’s terrifying new terror tactic may be tur...,https://nypost.com/2026/10/03/world-news/irans...
153,30,2026-10-03-22-25-01 +0000,nypost,"Streetwear giant Supreme — beloved by Bieber, ...",https://nypost.com/2026/10/03/us-news/trendy-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)