## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-23-16-08 +0000,nypost,"MSG rips ‘party pooper’ Mamdani, NYPD for stre...",https://nypost.com/2026/06/09/us-news/msg-rips...
1,2026-06-09-23-13-31 +0000,nyt,Doris Matsui Will Face Democratic Challenger i...,https://www.nytimes.com/2026/06/09/us/politics...
2,2026-06-09-23-12-21 +0000,nyt,Lawyers Barred for A.I.-Generated Citations to...,https://www.nytimes.com/2026/06/09/us/ai-lawye...
3,2026-06-09-23-09-31 +0000,nypost,Kalshi now requiring users to disclose employe...,https://nypost.com/2026/06/09/business/kalshi-...
4,2026-06-09-23-06-17 +0000,nypost,Sleazy foot fetish website owner hit with fede...,https://nypost.com/2026/06/09/us-news/sleazy-f...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2616/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
48   trump     30
47    iran     28
57   world     18
58     cup     16
315    new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
271,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,111
12,2026-06-09-23-01-36 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes o...,https://www.nytimes.com/live/2026/06/09/world/...,106
267,2026-06-09-08-55-09 +0000,cbc,U.S. launches strikes against Iran after Trump...,https://www.cbc.ca/news/world/strait-of-hormuz...,104
24,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...,101
5,2026-06-09-23-05-01 +0000,startribune,US strikes Iran after Trump blames Tehran for ...,https://www.startribune.com/trump-says-pilots-...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
271,111,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...
24,71,2026-06-09-22-36-00 +0000,wsj,Trump officials asked a government AI-testing ...,https://www.wsj.com/politics/policy/white-hous...
87,57,2026-06-09-20-39-00 +0000,wsj,Los Angeles Stadium Workers Reach Deal to Head...,https://www.wsj.com/business/los-angeles-stadi...
299,51,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...
276,45,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
269,39,2026-06-09-08-46-05 +0000,bbc,Trump booed in New York as he becomes first US...,https://www.bbc.com/news/articles/czj89mz3mzzo...
251,39,2026-06-09-10-10-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
12,38,2026-06-09-23-01-36 +0000,nyt,Iran War Live Updates: U.S. Launches Strikes o...,https://www.nytimes.com/live/2026/06/09/world/...
302,37,2026-06-09-01-09-50 +0000,cbc,Reality star Spencer Pratt out of L.A. mayor's...,https://www.cbc.ca/news/world/la-mayor-spencer...
11,34,2026-06-09-23-01-56 +0000,nypost,Wild West moment maniac fires on LAPD cops —in...,https://nypost.com/2026/06/09/us-news/wild-wes...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)