## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-02-22-15-00 +0000,nypost,Florida alligator victim Brittany Clark did ne...,https://nypost.com/2026/07/02/us-news/florida-...
1,2026-07-02-22-13-31 +0000,nypost,Kamikaze squirrel goes flying during ceremonia...,https://nypost.com/2026/07/02/us-news/kamikaze...
2,2026-07-02-22-10-44 +0000,nypost,Toxic smoke from warehouse blaze even worse fo...,https://nypost.com/2026/07/02/us-news/air-poll...
3,2026-07-02-22-08-55 +0000,nypost,Syrian president appoints Netflix star Rozina ...,https://nypost.com/2026/07/02/world-news/syria...
4,2026-07-02-22-08-45 +0000,nypost,Trump says he didn’t know about his crypto win...,https://nypost.com/2026/07/02/us-news/trump-sa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
46     trump     43
44       new     13
105   russia     12
21   america     12
72      heat     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
244,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,92
301,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...,90
270,2026-07-02-09-00-00 +0000,nypost,Sen. Elizabeth Warren calls out Trump for nomi...,https://nypost.com/2026/07/02/business/sen-eli...,84
315,2026-07-02-00-20-33 +0000,nypost,Ex-Trump adviser Kellogg says prez should brac...,https://nypost.com/2026/07/01/world-news/keith...,81
140,2026-07-02-16-37-26 +0000,nypost,Mamdani delivering ‘symbolic’ speech for Ameri...,https://nypost.com/2026/07/02/us-news/mamdani-...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
244,92,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...
175,65,2026-07-02-14-46-00 +0000,wsj,Court documents released in one of Anthropic’s...,https://www.wsj.com/politics/national-security...
113,48,2026-07-02-18-23-50 +0000,nyt,June Jobs Report Shows US Labor Market Making ...,https://www.nytimes.com/2026/07/02/business/ec...
247,46,2026-07-02-10-21-05 +0000,cbc,"Deadly, large-scale Russian attack shakes Kyiv...",https://www.cbc.ca/news/world/missile-drone-at...
323,43,2026-07-01-23-43-03 +0000,latimes,SoCal boy was killed by massive tree branch at...,https://www.latimes.com/california/story/2026-...
43,43,2026-07-02-21-09-52 +0000,nypost,Why online army of Taylor Swift megafans refus...,https://nypost.com/2026/07/02/lifestyle/is-tay...
296,43,2026-07-02-03-00-00 +0000,wsj,Europe Learns It’s Hard to Start a Trade War W...,https://www.wsj.com/world/china/europe-learns-...
14,39,2026-07-02-21-49-42 +0000,nypost,Massachusetts city orders curfew ahead of Cape...,https://nypost.com/2026/07/02/us-news/massachu...
301,37,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...
194,37,2026-07-02-13-57-46 +0000,nypost,Michigan Dem Senate front-runner Dr. Abdul El-...,https://nypost.com/2026/07/02/us-news/michigan...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)