## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-06-12-10-08 +0000,nyt,Khamenei’s funeral draws mourners from across ...,https://www.nytimes.com/live/2026/07/06/world/...
1,2026-07-06-12-09-05 +0000,bbc,ITV hits such as I'm a Celebrity to stay free ...,https://www.bbc.co.uk/news/articles/cx2wwgeg04...
2,2026-07-06-12-07-44 +0000,bbc,Huge crowds fill Tehran streets for Khamenei's...,https://www.bbc.co.uk/news/articles/cdejj44kl7...
3,2026-07-06-12-05-25 +0000,nyt,China Test Fires Long-Range Ballistic Missile ...,https://www.nytimes.com/2026/07/06/world/asia/...
4,2026-07-06-11-58-00 +0000,wsj,Ukraine’s Shortage of Patriot Missiles Leaves ...,https://www.wsj.com/world/europe/ukraines-shor...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
154    trump     21
160    world     14
5       iran     11
1    funeral     11
262   leader     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...,88
23,2026-07-06-11-00-00 +0000,wsj,When President Trump meets with Ukraine’s Volo...,https://www.wsj.com/politics/trump-to-meet-wit...,84
33,2026-07-06-10-39-24 +0000,nypost,Trump plans billions in arms sales as NATO sum...,https://nypost.com/2026/07/06/us-news/trump-pl...,63
80,2026-07-06-09-00-11 +0000,nyt,Emil Bove Defended Trump in Court. Then Trump ...,https://www.nytimes.com/2026/07/06/us/emil-bov...,60
199,2026-07-05-18-20-53 +0000,nypost,Ex-Dem activist Calla Walsh attends Khamenei’s...,https://nypost.com/2026/07/05/world-news/calla...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,88,2026-07-05-21-23-00 +0000,wsj,Did President Trump just save the U.S. men’s t...,https://www.wsj.com/politics/the-world-cup-the...
199,59,2026-07-05-18-20-53 +0000,nypost,Ex-Dem activist Calla Walsh attends Khamenei’s...,https://nypost.com/2026/07/05/world-news/calla...
60,40,2026-07-06-09-31-20 +0000,wapo,Deadly Russian strikes hit Ukraine’s capital a...,https://www.washingtonpost.com/world/2026/07/0...
90,38,2026-07-06-07-42-25 +0000,nypost,China test-launches a ballistic missile in a S...,https://nypost.com/2026/07/06/world-news/china...
205,37,2026-07-05-17-52-11 +0000,latimes,"Woman killed, several injured in Fourth of Jul...",https://www.latimes.com/california/story/2026-...
82,36,2026-07-06-08-44-41 +0000,nypost,Married Australian PM Anthony Albanese breaks ...,https://nypost.com/2026/07/06/world-news/marri...
165,34,2026-07-05-21-37-58 +0000,nypost,Netanyahu gov’t declares it will ignore Israel...,https://nypost.com/2026/07/05/world-news/netan...
83,33,2026-07-06-08-21-54 +0000,wsj,Stock Market Today: Stock Futures Rise Ahead o...,https://www.wsj.com/livecoverage/stock-market-...
18,29,2026-07-06-11-19-33 +0000,nypost,King Charles yanks invitation for Prince Harry...,https://nypost.com/2026/07/06/world-news/king-...
120,25,2026-07-06-02-46-59 +0000,nypost,Horde of teens pummel South Carolina cops brea...,https://nypost.com/2026/07/05/us-news/horde-of...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)