## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-18-16-02-10 +0000,nypost,Court deals blow to Seton Hall sex abuse survi...,https://nypost.com/2026/06/18/us-news/court-de...
1,2026-06-18-16-01-07 +0000,bbc,Gunmen attack Niger's biggest airport for seco...,https://www.bbc.com/news/articles/cdx7krkdqeno...
2,2026-06-18-15-59-16 +0000,nyt,Iran War Live Updates: Vance Defends Iran Deal...,https://www.nytimes.com/live/2026/06/18/world/...
3,2026-06-18-15-59-14 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/18/world/...
4,2026-06-18-15-56-34 +0000,bbc,Jury in Sir Jeffrey Donaldson sex abuse trial ...,https://www.bbc.com/news/articles/ce8m211729no...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
19    iran     52
254  trump     49
25    deal     40
210    fed     24
310    new     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
294,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...,223
118,2026-06-18-11-56-00 +0000,wsj,Oil Prices Fall to Lowest Since War Began Afte...,https://www.wsj.com/finance/commodities-future...,196
136,2026-06-18-10-40-51 +0000,nypost,At least 12 tankers pass through Strait of Hor...,https://nypost.com/2026/06/18/world-news/three...,176
37,2026-06-18-15-12-00 +0000,wsj,Trump’s Deal Sidesteps Key Reasons He Went to ...,https://www.wsj.com/world/middle-east/trumps-d...,172
2,2026-06-18-15-59-16 +0000,nyt,Iran War Live Updates: Vance Defends Iran Deal...,https://www.nytimes.com/live/2026/06/18/world/...,169

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
294,223,2026-06-17-21-11-09 +0000,nyt,"Trump Criticized Obama’s Iran Deal, but New De...",https://www.nytimes.com/2026/06/17/world/europ...
310,138,2026-06-17-20-38-00 +0000,wsj,"At Kevin Warsh’s first meeting as chairman, th...",https://www.wsj.com/economy/central-banking/fe...
100,83,2026-06-18-12-53-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
64,62,2026-06-18-14-10-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
171,54,2026-06-18-08-51-35 +0000,nypost,"Ukraine hits Moscow oil refinery, disrupting c...",https://nypost.com/2026/06/18/world-news/ukrai...
337,45,2026-06-17-19-14-00 +0000,wsj,President Trump tied together fights over poli...,https://www.wsj.com/politics/policy/trump-has-...
143,45,2026-06-18-10-00-00 +0000,latimes,Inside the FBI's battle to keep drones out of ...,https://www.latimes.com/california/story/2026-...
9,44,2026-06-18-15-51-00 +0000,wsj,Supreme Court Rules Government Can’t Ban All D...,https://www.wsj.com/us-news/law/supreme-court-...
377,42,2026-06-17-17-16-11 +0000,nypost,Bungee-jump employee took GoPro camera off stu...,https://nypost.com/2026/06/17/world-news/bunge...
312,36,2026-06-17-20-34-07 +0000,nypost,Jeff Bezos told Trump the Washington Post was ...,https://nypost.com/2026/06/17/us-news/jeff-bez...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)