## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-01-31-00 +0000,wsj,Asian Currencies Mostly Weaken Before U.S. non...,https://www.wsj.com/finance/currencies/u-s-job...
1,2026-06-05-01-30-57 +0000,nypost,"Update in LA mayor, California governor’s race...",https://nypost.com/2026/06/04/us-news/update-i...
2,2026-06-05-01-29-12 +0000,nypost,Louisiana babysitter arrested after toddler dr...,https://nypost.com/2026/06/04/us-news/louisian...
3,2026-06-05-01-26-28 +0000,bbc,"Giant hissing cockroaches among $200,000 worth...",https://www.bbc.com/news/articles/cjwpwv18910o...
4,2026-06-05-01-24-13 +0000,nypost,Supersonic jet that will fly you from LA to NY...,https://nypost.com/2026/06/04/us-news/nasa-exp...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
100       trump     34
298         new     16
227          ai     14
85           up     14
11   california     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-06-04-23-18-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...,91
211,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...,84
236,2026-06-04-15-22-16 +0000,nyt,"John Bolton, Ex-Trump Adviser, Reaches Deal to...",https://www.nytimes.com/2026/06/04/us/politics...,75
214,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...,75
99,2026-06-04-21-36-37 +0000,latimes,"Chabria: No, Mr. Hilton, our elections are not...",https://www.latimes.com/california/story/2026-...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,91,2026-06-04-23-18-00 +0000,wsj,An internal Republican fight over legislation ...,https://www.wsj.com/politics/policy/gop-senato...
214,61,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
15,61,2026-06-05-00-42-27 +0000,nypost,Graham Platner admits to sexting women ‘soon’ ...,https://nypost.com/2026/06/04/us-news/graham-p...
148,57,2026-06-04-20-04-02 +0000,nypost,Hezbollah rejects ‘humiliating’ cease-fire dea...,https://nypost.com/2026/06/04/world-news/hezbo...
8,52,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
116,47,2026-06-04-21-01-54 +0000,latimes,Spencer Pratt claims L.A.'s homeless will move...,https://www.latimes.com/california/story/2026-...
358,45,2026-06-04-04-01-06 +0000,nyt,"Amid War, Iran’s Soccer Leader Works to Get Hi...",https://www.nytimes.com/2026/06/04/world/middl...
257,42,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...
279,40,2026-06-04-12-34-00 +0000,cbc,No handshake and no photo as Russia's Andreeva...,https://www.cbc.ca/sports/tennis/dabrowski-rou...
39,37,2026-06-04-23-44-17 +0000,nypost,"Tech boss, Jamshid Ghomi, charged with sending...",https://nypost.com/2026/06/04/us-news/tech-bos...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)