## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-22-04-51-00 +0000,wsj,Fortescue Warns of Output Guidance Cut If Chin...,https://www.wsj.com/business/fortescue-warns-o...
1,2026-10-22-04-45-28 +0000,nyt,A Debt-Fueled “Doom Loop”,https://www.nytimes.com/2026/10/21/world/debt-...
2,2026-10-22-04-22-51 +0000,nyt,Protests in Indonesia Demand Action to Stop Ra...,https://www.nytimes.com/2026/10/22/world/asia/...
3,2026-10-22-04-22-16 +0000,48hills,OPINION: Why professional journalists are oppo...,https://48hills.org/2026/10/opinion-why-profes...
4,2026-10-22-04-12-26 +0000,bbc,Celebrity shark returns to South Korea canal a...,https://www.bbc.co.uk/news/articles/cr3wv99614...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2677/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
218       trump     27
51          new     26
149          ai     17
80       senate     14
228  california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
36,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...,98
206,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...,94
108,2026-10-21-22-12-19 +0000,nypost,Meta stock surges on strong earnings report; t...,https://nypost.com/2026/10/21/business/meta-st...,91
258,2026-10-21-16-48-37 +0000,nypost,Speculation — and anxiety — growing that Mark ...,https://nypost.com/2026/10/21/business/will-ma...,84
161,2026-10-21-20-41-37 +0000,nypost,Tesla surprises Wall Street with lower-than-ex...,https://nypost.com/2026/10/21/business/elon-mu...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
36,98,2026-10-22-01-51-00 +0000,wsj,Democrat Abdul El-Sayed and former GOP Rep. Mi...,https://www.wsj.com/politics/elections/abdul-e...
206,94,2026-10-21-19-00-00 +0000,wsj,The Trump administration wants to bulk up its ...,https://www.wsj.com/politics/policy/the-trump-...
108,91,2026-10-21-22-12-19 +0000,nypost,Meta stock surges on strong earnings report; t...,https://nypost.com/2026/10/21/business/meta-st...
195,65,2026-10-21-19-28-44 +0000,chitri,Pope Leo’s doctors say tests show he needs no ...,https://www.chicagotribune.com/2026/10/21/pope...
308,61,2026-10-21-14-05-18 +0000,chitri,Russia President Vladimir Putin agrees to resu...,https://www.chicagotribune.com/2026/10/21/russ...
88,60,2026-10-21-23-06-24 +0000,nyt,Tesla Profit Slumps as Elon Musk’s Car Company...,https://www.nytimes.com/2026/10/21/business/te...
147,58,2026-10-21-21-03-00 +0000,wsj,An ad featuring Amy Acton’s estranged mother a...,https://www.wsj.com/politics/elections/ohio-go...
42,49,2026-10-22-01-18-45 +0000,nypost,Ilhan Omar gives head-scratching response when...,https://nypost.com/2026/10/21/us-news/ilhan-om...
122,42,2026-10-21-21-37-00 +0000,wsj,Meta Ordered to Pay $25 Billion to New Mexico ...,https://www.wsj.com/tech/meta-ordered-to-pay-2...
56,40,2026-10-22-00-42-00 +0000,wsj,The American Israel Public Affairs Committee i...,https://www.wsj.com/politics/policy/aipac-says...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)