## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-23-16-03 +0000,nyt,Iran’s Soccer Team Allowed Into U.S. for World...,https://www.nytimes.com/2026/06/05/world/middl...
1,2026-06-05-23-00-34 +0000,nypost,Bandit escapes in Waymo in first-of-its-kind h...,https://nypost.com/2026/06/05/us-news/thief-wh...
2,2026-06-05-23-00-00 +0000,wsj,A Cheap DIY Solar Hack Is Catching On. Can It ...,https://www.wsj.com/business/energy-oil/plug-i...
3,2026-06-05-23-00-00 +0000,wsj,"Wait, Why Are Restaurants Now Charging $40 for...",https://www.wsj.com/arts-culture/food-cooking/...
4,2026-06-05-22-51-00 +0000,startribune,Live: United South Central vs. West Lutheran i...,https://www.startribune.com/mn-softball-state-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2471/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
79    trump     23
216  senate     14
312  market     13
221     new     12
97       up     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...,87
126,2026-06-05-17-13-18 +0000,nypost,Trump says he wants new acting intel chief Bil...,https://nypost.com/2026/06/05/us-news/trump-sa...,77
134,2026-06-05-16-45-46 +0000,nypost,Senate blows up renewal of key surveillance po...,https://nypost.com/2026/06/05/us-news/democrat...,75
204,2026-06-05-13-12-51 +0000,nyt,Graham Platner Denies Hurting Ex-Girlfriend an...,https://www.nytimes.com/2026/06/04/us/politics...,72
109,2026-06-05-18-17-24 +0000,nypost,Trump must ‘accept the reality’ there is no I...,https://nypost.com/2026/06/05/world-news/jack-...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,87,2026-06-05-19-06-00 +0000,wsj,"President Trump said he wants Bill Pulte, his ...",https://www.wsj.com/politics/national-security...
204,64,2026-06-05-13-12-51 +0000,nyt,Graham Platner Denies Hurting Ex-Girlfriend an...,https://www.nytimes.com/2026/06/04/us/politics...
38,54,2026-06-05-21-29-12 +0000,nypost,"Putin slams door on Zelensky meeting, saying t...",https://nypost.com/2026/06/05/world-news/vladi...
306,47,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
68,40,2026-06-05-20-21-38 +0000,nyt,Stocks Slide as Investors See Rates Rising Aft...,https://www.nytimes.com/2026/06/05/business/st...
173,38,2026-06-05-15-19-52 +0000,nypost,"Iran declares support for Hezbollah, demands I...",https://nypost.com/2026/06/05/world-news/iran-...
12,38,2026-06-05-22-32-21 +0000,nypost,"Taylor Swift, Travis Kelce wedding at MSG make...",https://nypost.com/2026/06/05/us-news/taylor-s...
185,37,2026-06-05-14-15-02 +0000,nyt,How the Job Market Is Leaving New Graduates Be...,https://www.nytimes.com/video/business/1000000...
271,35,2026-06-05-08-56-17 +0000,cbc,Chinese leader Xi Jinping to visit North Korea...,https://www.cbc.ca/news/world/xi-jinping-north...
5,30,2026-06-05-22-46-56 +0000,nypost,"Elon Musk outlines bold vision for SpaceX, goe...",https://nypost.com/2026/06/05/business/elon-mu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)