## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-28-16-55-01 +0000,nypost,Americans are using far less cash than a decad...,https://nypost.com/2026/08/28/us-news/american...
1,2026-08-28-16-53-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...
2,2026-08-28-16-53-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
3,2026-08-28-16-52-00 +0000,nypost,Costco now offering delivery for its most cher...,https://nypost.com/2026/08/28/business/costco-...
4,2026-08-28-16-49-46 +0000,nyt,Judge Excludes Key Confession in Sept. 11 Case,https://www.nytimes.com/2026/08/28/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2527/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
79   trump     53
72   nepal     32
139    new     30
840   lake     22
351    war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
408,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...,146
414,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...,146
249,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...,142
312,2026-08-27-21-52-39 +0000,wapo,Trump signs order renaming Lake Ontario as Lak...,https://www.washingtonpost.com/politics/2026/0...,140
188,2026-08-28-09-08-41 +0000,nyt,Trump Signs Executive Order to Rename Lake Ont...,https://www.nytimes.com/2026/08/27/us/politics...,135

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
408,146,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...
261,101,2026-08-28-01-10-00 +0000,wsj,New York Attorney General Letitia James is sui...,https://www.wsj.com/politics/policy/new-york-s...
250,87,2026-08-28-02-00-00 +0000,wsj,The U.S.-Canada trade war. The war in Iran. Su...,https://www.wsj.com/economy/global/how-the-ai-...
10,84,2026-08-28-16-36-31 +0000,nypost,California tech worker missing in Nepal after ...,https://nypost.com/2026/08/28/world-news/bay-a...
343,60,2026-08-27-21-03-00 +0000,wsj,Federal investigators said the temporary reloc...,https://www.wsj.com/politics/policy/investigat...
61,60,2026-08-28-14-46-43 +0000,nypost,Fed’s Kevin Warsh says there’s ‘work to do’ on...,https://nypost.com/2026/08/28/business/feds-ke...
249,59,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...
220,59,2026-08-28-07-26-00 +0000,nypost,Norway’s Crown Prince Haakon becomes king afte...,https://nypost.com/2026/08/28/world-news/norwa...
162,53,2026-08-28-10-09-00 +0000,wsj,"Tech firms are courting Democrats, the South f...",https://www.wsj.com/politics/policy/corporate-...
361,44,2026-08-27-20-31-00 +0000,wsj,Round Two in the legal effort to honor Preside...,https://www.wsj.com/politics/policy/kennedy-ce...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)