## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-07-11-00 +0000,wsj,Asian Markets Slump as Mideast Conflict Escalates,https://www.wsj.com/finance/stocks/asian-marke...
1,2026-03-23-07-05-11 +0000,nyt,Flights Grounded at LaGuardia Airport as New Y...,https://www.nytimes.com/2026/03/23/nyregion/la...
2,2026-03-23-07-02-57 +0000,bbc,Plane and ground vehicle collide at New York's...,https://www.bbc.com/news/articles/cy01g522ww4o...
3,2026-03-23-07-01-00 +0000,wsj,Renewed Geopolitical Risk Puts Yen Back in Int...,https://www.wsj.com/finance/currencies/renewed...
4,2026-03-23-06-57-00 +0000,wsj,LaGuardia Airport Closed Until Monday Evening ...,https://www.wsj.com/us-news/faa-issues-ground-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2609/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
36   trump     29
75    iran     21
74     war     13
152   will     11
10     new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
36,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...,102
33,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...,102
124,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,100
189,2026-03-22-10-06-06 +0000,wapo,Trump threatens to ‘obliterate’ Iran’s power p...,https://www.washingtonpost.com/world/2026/03/2...,80
186,2026-03-22-10-49-06 +0000,cbc,Trump says he will send ICE agents to U.S. air...,https://www.cbc.ca/news/world/trump-ice-us-air...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
36,102,2026-03-23-03-18-00 +0000,wsj,Iran said it would target critical infrastruct...,https://www.wsj.com/world/middle-east/trump-te...
33,73,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
166,44,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
204,41,2026-03-22-09-01-25 +0000,nyt,"Despite Spiking Oil Prices, There’s No Talk of...",https://www.nytimes.com/2026/03/22/us/texas-oi...
70,39,2026-03-22-23-49-25 +0000,nypost,California military families react as soldiers...,https://nypost.com/2026/03/22/us-news/socal-mi...
31,29,2026-03-23-03-34-34 +0000,nyt,Israel’s Missile Defense Under Scrutiny After ...,https://www.nytimes.com/2026/03/22/world/middl...
174,29,2026-03-22-14-00-00 +0000,wsj,Small truck drivers in the U.S. are feeling so...,https://www.wsj.com/economy/truckers-are-the-f...
178,28,2026-03-22-12-52-00 +0000,wsj,South Korean President Lee Jae Myung has nomin...,https://www.wsj.com/economy/central-banking/so...
4,26,2026-03-23-06-57-00 +0000,wsj,LaGuardia Airport Closed Until Monday Evening ...,https://www.wsj.com/us-news/faa-issues-ground-...
55,26,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)