## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-31-09-38-07 +0000,bbc,Sturgeon 'will not apologise for the crimes' o...,https://www.bbc.com/news/videos/c99ldk7jr3ro?a...
1,2026-05-31-09-35-52 +0000,bbc,Sturgeon tells BBC: I'm serving a sentence for...,https://www.bbc.com/news/articles/c2027k1ev3zo...
2,2026-05-31-09-30-00 +0000,wsj,Miami’s Wealthiest ZIP Code Is Fighting to Evi...,https://www.wsj.com/real-estate/miamis-wealthi...
3,2026-05-31-09-30-00 +0000,wsj,Golf Is Now Cooler and Younger. The Stock Mark...,https://www.wsj.com/business/retail/golf-is-no...
4,2026-05-31-09-30-00 +0000,wsj,Incoming Fed Chairman Kevin Warsh wants the ce...,https://www.wsj.com/economy/central-banking/ke...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3212/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
85   trump     20
223    out     11
136    new      8
160    war      7
64    city      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
151,2026-05-30-13-39-00 +0000,wsj,President Trump’s no-audits promise from his a...,https://www.wsj.com/politics/policy/a-controve...,60
95,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...,59
76,2026-05-30-23-21-00 +0000,wsj,After several musicians dropped out of the fes...,https://www.wsj.com/politics/policy/trump-name...,56
127,2026-05-30-16-56-12 +0000,nypost,"Trump considering giving ‘major’ speech, holdi...",https://nypost.com/2026/05/30/us-news/trump-co...,49
118,2026-05-30-17-40-47 +0000,bbc,Trump attacks artists dropping out of US Freed...,https://www.bbc.com/news/articles/cy02j1n87wlo...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
151,60,2026-05-30-13-39-00 +0000,wsj,President Trump’s no-audits promise from his a...,https://www.wsj.com/politics/policy/a-controve...
108,46,2026-05-30-19-16-00 +0000,wsj,The wife of Maine Democratic Senate candidate ...,https://www.wsj.com/politics/elections/graham-...
46,35,2026-05-31-02-39-00 +0000,wsj,China’s manufacturing activity stayed flat in ...,https://www.wsj.com/economy/china-manufacturin...
126,35,2026-05-30-17-00-00 +0000,nypost,Kelsey Grammer reveals his nasty nickname for ...,https://nypost.com/2026/05/30/us-news/kelsey-g...
76,32,2026-05-30-23-21-00 +0000,wsj,After several musicians dropped out of the fes...,https://www.wsj.com/politics/policy/trump-name...
119,31,2026-05-30-17-34-30 +0000,bbc,'No-one feels safe now': Residents of Romanian...,https://www.bbc.com/news/articles/cvgzyp93jq1o...
122,29,2026-05-30-17-20-00 +0000,wsj,Disclosure documents show Josh Gruenbaum was a...,https://www.wsj.com/politics/doge-official-dis...
51,27,2026-05-31-02-00-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...
132,24,2026-05-30-16-29-09 +0000,nypost,Ex-Pentagon official says new file batch prove...,https://nypost.com/2026/05/30/world-news/ex-pe...
4,22,2026-05-31-09-30-00 +0000,wsj,Incoming Fed Chairman Kevin Warsh wants the ce...,https://www.wsj.com/economy/central-banking/ke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)