## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-20-16-18-32 +0000,bbc,Police block thousands of 'cockroach' proteste...,https://www.bbc.co.uk/news/articles/cvg9w9dxd7...
1,2026-07-20-16-16-03 +0000,startribune,Two mass shootings in Minneapolis in less than...,https://www.startribune.com/shooting-outside-m...
2,2026-07-20-16-14-58 +0000,nypost,Coral reef presumed to be dead is rediscovered...,https://nypost.com/2026/07/20/world-news/coral...
3,2026-07-20-16-13-17 +0000,nyt,Houthis in Yemen Declare Red Sea Blockade on S...,https://www.nytimes.com/2026/07/20/world/middl...
4,2026-07-20-16-12-52 +0000,nyt,Hamas Names Khalil al-Hayya as Its New Leader,https://www.nytimes.com/2026/07/20/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2359/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
39       new     27
119     iran     26
377    world     26
378      cup     24
115  burnham     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
268,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...,109
266,2026-07-19-19-25-24 +0000,chitri,Donald Trump celebrates the World Cup as a US ...,https://www.chicagotribune.com/2026/07/19/trum...,103
241,2026-07-19-22-52-27 +0000,nypost,Trump hands out medals to World Cup champion S...,https://nypost.com/2026/07/19/sports/trump-and...,96
247,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...,92
222,2026-07-20-00-44-03 +0000,bbc,"Trump, Bieber and Shakira - a World Cup final ...",https://www.bbc.co.uk/sport/football/articles/...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
268,109,2026-07-19-19-15-42 +0000,nypost,Trump seen marveling at World Cup trophy as he...,https://nypost.com/2026/07/19/us-news/trump-fl...
122,83,2026-07-20-11-52-27 +0000,bbc,A very quick guide to new prime minister Andy ...,https://www.bbc.co.uk/news/articles/clyv9qe6wj...
88,67,2026-07-20-13-07-26 +0000,wapo,Pentagon names troops killed in Jordan as U.S....,https://www.washingtonpost.com/world/2026/07/2...
234,61,2026-07-19-23-25-00 +0000,wsj,"Usha Vance gave birth to a baby boy on Sunday,...",https://www.wsj.com/us-news/second-lady-usha-v...
181,49,2026-07-20-09-00-00 +0000,wsj,Many wealthy Texas Republicans can’t stomach t...,https://www.wsj.com/politics/elections/ken-pax...
54,49,2026-07-20-14-17-49 +0000,nypost,Armed loon sets off ‘incendiary device’ outsid...,https://nypost.com/2026/07/20/us-news/terroris...
247,38,2026-07-19-22-02-22 +0000,cbc,Torres fires Spain past Argentina in extra tim...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
144,38,2026-07-20-10-42-53 +0000,nypost,Trump says new Qatar-donated Air Force One to ...,https://nypost.com/2026/07/20/us-news/trump-sa...
11,33,2026-07-20-16-04-34 +0000,nypost,Jersey Mike’s aims to raise $1 billion in IPO ...,https://nypost.com/2026/07/20/business/jersey-...
78,29,2026-07-20-13-30-48 +0000,nypost,Texas Dem House hopeful creeped on women in Sp...,https://nypost.com/2026/07/20/us-news/texas-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)