## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-19-15-03 +0000,nyt,Iran War Live Updates: Trump Asserts Iran Want...,https://www.nytimes.com/live/2026/03/24/world/...
1,2026-03-24-19-14-22 +0000,nypost,Sickening discovery at remote vacation mansion...,https://nypost.com/2026/03/24/us-news/discover...
2,2026-03-24-19-14-06 +0000,nypost,Trump says Iran has agreed to no nuclear weapo...,https://nypost.com/2026/03/24/us-news/trump-sa...
3,2026-03-24-19-12-17 +0000,nyt,"Epic Games Lays Off Over 1,000 Employees, Citi...",https://www.nytimes.com/2026/03/24/business/ep...
4,2026-03-24-19-11-00 +0000,wsj,Edmond de Rothschild Offices Raided in Probe o...,https://www.wsj.com/world/europe/edmond-de-rot...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     46
4     trump     38
1       war     24
225  energy     14
6      deal     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-24-19-15-03 +0000,nyt,Iran War Live Updates: Trump Asserts Iran Want...,https://www.nytimes.com/live/2026/03/24/world/...,172
172,2026-03-24-13-17-18 +0000,nypost,Pete Hegseth was ‘the first’ to push for war w...,https://nypost.com/2026/03/24/us-news/pete-heg...,133
123,2026-03-24-15-34-19 +0000,nyt,Trump’s Threat to ‘Obliterate’ Iran’s Power St...,https://www.nytimes.com/2026/03/24/us/politics...,132
369,2026-03-23-19-47-08 +0000,wapo,Trump says U.S. is postponing some strikes as ...,https://www.washingtonpost.com/politics/2026/0...,125
304,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,172,2026-03-24-19-15-03 +0000,nyt,Iran War Live Updates: Trump Asserts Iran Want...,https://www.nytimes.com/live/2026/03/24/world/...
151,84,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
343,54,2026-03-23-21-13-47 +0000,bbc,'Like the plane got cut in half': LaGuardia cr...,https://www.bbc.com/news/articles/c78rdze8zvjo...
263,54,2026-03-24-03-18-00 +0000,wsj,Senators said they were closing in on a deal t...,https://www.wsj.com/politics/policy/trump-reje...
355,44,2026-03-23-20-43-02 +0000,nypost,Anti-communist dance troupe Shen Yun claims CC...,https://nypost.com/2026/03/23/world-news/shen-...
370,43,2026-03-23-19-44-00 +0000,wsj,The Supreme Court seems inclined to block stat...,https://www.wsj.com/politics/elections/supreme...
361,43,2026-03-23-20-21-51 +0000,bbc,Oil falls and shares rebound after Trump says ...,https://www.bbc.com/news/articles/czex56kwxxzo...
26,41,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
130,34,2026-03-24-15-28-13 +0000,cbc,"To stop long ballot protests, MP committee cal...",https://www.cbc.ca/news/politics/long-ballot-p...
320,33,2026-03-23-22-50-00 +0000,latimes,A SoCal mother was warned about dangers of por...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)