## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-19-43-26 +0000,nypost,Solvang takes fight to California over famous ...,https://nypost.com/2026/06/11/us-news/californ...
1,2026-06-11-19-42-00 +0000,wapo,"Minnesota lawmaker’s killer pleads guilty, avo...",https://www.washingtonpost.com/nation/2026/06/...
2,2026-06-11-19-40-29 +0000,nyt,Iran War Live Updates: Trump Retracts Latest T...,https://www.nytimes.com/live/2026/06/11/world/...
3,2026-06-11-19-40-05 +0000,nyt,"In a Trump-Endorsed Presidential Candidate, Co...",https://www.nytimes.com/2026/06/11/us/abelardo...
4,2026-06-11-19-39-39 +0000,nypost,Elderly NYC trans serial killer learns fate af...,https://nypost.com/2026/06/11/us-news/nyc-tran...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2514/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20     trump     39
16      iran     33
112    world     24
456      new     20
24   strikes     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
88,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...,131
331,2026-06-10-21-48-54 +0000,nypost,Trump warns Iran to make a deal or ‘we’ll bomb...,https://nypost.com/2026/06/10/us-news/us-launc...,128
333,2026-06-10-21-48-11 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,118
25,2026-06-11-19-09-47 +0000,nypost,Dow jumps nearly 800 points after Trump calls ...,https://nypost.com/2026/06/11/business/dow-jum...,117
311,2026-06-10-23-14-53 +0000,wapo,"U.S. launches new strikes on Iran, hours after...",https://www.washingtonpost.com/world/2026/06/1...,116

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
88,131,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post U...",https://nypost.com/2026/06/11/us-news/trump-ca...
251,74,2026-06-11-09-04-26 +0000,nyt,Why Mexico’s President Will Not Attend the Wor...,https://www.nytimes.com/2026/06/11/world/ameri...
19,60,2026-06-11-19-16-59 +0000,nypost,NYPD cop turned ‘vigilante’ charged after he w...,https://nypost.com/2026/06/11/us-news/nypd-cop...
355,56,2026-06-10-20-59-00 +0000,wsj,New Middle East Clashes and Inflation Fears Sp...,https://www.wsj.com/finance/stocks/global-stoc...
94,55,2026-06-11-17-34-06 +0000,nypost,Minnesota assassin Vance Boelter admits murder...,https://nypost.com/2026/06/11/us-news/minnesot...
219,51,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...
244,41,2026-06-11-10-00-00 +0000,latimes,SpaceX is poised to make history with record $...,https://www.latimes.com/business/story/2026-06...
44,40,2026-06-11-18-31-37 +0000,nypost,California woman found stuffed in a suitcase a...,https://nypost.com/2026/06/11/us-news/californ...
160,39,2026-06-11-14-58-00 +0000,wsj,The ECB became the first major central bank to...,https://www.wsj.com/economy/central-banking/ec...
349,35,2026-06-10-21-09-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)