## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-13-46-27 +0000,nypost,Lefty late-night TV hosts targeted Republicans...,https://nypost.com/2026/10/31/us-news/late-nig...
1,2026-10-31-13-45-34 +0000,bbc,Evacuees from Russia-occupied city where resid...,https://www.bbc.co.uk/news/articles/cqx2818elr...
2,2026-10-31-13-45-00 +0000,nypost,NYC madman arrested twice for attacking 4 wome...,https://nypost.com/2026/10/31/us-news/nyc-madm...
3,2026-10-31-13-42-45 +0000,nyt,Advocacy Groups Sue to Stop Trump Effort to Se...,https://www.nytimes.com/2026/10/31/us/election...
4,2026-10-31-13-34-18 +0000,nyt,Talarico Makes Final Election Pitch to Texans:...,https://www.nytimes.com/2026/10/31/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2399/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
40        trump     25
48     election     21
199  california     17
8        senate     13
172         new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
35,2026-10-31-11-21-14 +0000,nypost,Trump DOJ warns election officials of possible...,https://nypost.com/2026/10/31/us-news/trump-do...,83
104,2026-10-31-03-30-58 +0000,nyt,Judge Bars Trump Administration From Threateni...,https://www.nytimes.com/2026/10/30/us/election...,80
263,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,79
232,2026-10-30-20-25-06 +0000,nyt,Appeals Court Again Rejects Trump Effort to Im...,https://www.nytimes.com/2026/10/30/us/politics...,67
211,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...,64

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
35,83,2026-10-31-11-21-14 +0000,nypost,Trump DOJ warns election officials of possible...,https://nypost.com/2026/10/31/us-news/trump-do...
258,60,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
86,57,2026-10-31-07-14-40 +0000,nypost,"One dead, 6 injured in shooting inside Spirit ...",https://nypost.com/2026/10/31/us-news/californ...
318,51,2026-10-30-15-47-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
276,51,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
26,48,2026-10-31-12-00-00 +0000,latimes,Your last-minute guide to the L.A. city attorn...,https://www.latimes.com/california/story/2026-...
176,43,2026-10-30-21-48-01 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
168,40,2026-10-30-22-16-35 +0000,missionlocal,‘Head of the family’: Crocker Amazon hit-and-r...,https://missionlocal.org/2026/10/crocker-amazo...
270,37,2026-10-30-18-35-10 +0000,latimes,NTSB releases new details of deadly Yosemite N...,https://www.latimes.com/california/story/2026-...
129,36,2026-10-31-01-00-00 +0000,wsj,Polling showing Democrats are favored to make ...,https://www.wsj.com/politics/elections/republi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)