## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-22-14-43-26 +0000,nyt,‘They Protected You Guys’: Mourners Honor Hero...,https://www.nytimes.com/2026/05/21/us/san-dieg...
1,2026-05-22-14-43-23 +0000,bbc,Bank boss sorry after describing workers as 'l...,https://www.bbc.com/news/articles/c98rqld1j3yo...
2,2026-05-22-14-41-25 +0000,bbc,Rubio tries to reassure Nato allies over US tr...,https://www.bbc.com/news/articles/cedpz9669deo...
3,2026-05-22-14-41-16 +0000,nyt,What to Know About the Ebola Outbreak as Cases...,https://www.nytimes.com/2026/05/17/world/afric...
4,2026-05-22-14-39-00 +0000,wsj,Fed’s Waller: Inflation Risks Mean Fed Should ...,https://www.wsj.com/economy/central-banking/fe...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
149   trump     47
72      new     22
23    ebola     16
64     iran     16
43   police     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
366,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...,111
79,2026-05-22-11-00-00 +0000,nypost,How Kevin Warsh will navigate his tricky new p...,https://nypost.com/2026/05/22/business/how-kev...,104
214,2026-05-21-23-54-00 +0000,wsj,House Republican leaders yanked a planned vote...,https://www.wsj.com/politics/house-republicans...,102
258,2026-05-21-21-34-00 +0000,wsj,Trump and the GOP fight over his $1.8 billion ...,https://www.wsj.com/politics/policy/trump-and-...,101
113,2026-05-22-10-00-01 +0000,wapo,Trump offered White South Africans a new life....,https://www.washingtonpost.com/nation/2026/05/...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
366,111,2026-05-21-16-52-20 +0000,bbc,"Vanessa Trump, ex-wife of Donald Trump Jr, dia...",https://www.bbc.com/news/articles/c93xve8w4yyo...
197,60,2026-05-22-01-05-39 +0000,nypost,GOP calls off vote on Iran war resolution that...,https://nypost.com/2026/05/21/us-news/gop-call...
173,57,2026-05-22-04-46-50 +0000,nypost,"New presidential poll shows Gavin Newsom, Kama...",https://nypost.com/2026/05/22/us-news/new-pres...
92,57,2026-05-22-10-52-48 +0000,nypost,Feds dramatically drop charges against Illinoi...,https://nypost.com/2026/05/22/us-news/feds-dro...
361,50,2026-05-21-17-11-33 +0000,nypost,India-Africa summit postponed as Ebola outbrea...,https://nypost.com/2026/05/21/world-news/india...
210,49,2026-05-22-00-04-00 +0000,wsj,Mortgage rates this week rose to the highest l...,https://www.wsj.com/economy/housing/mortgage-r...
128,49,2026-05-22-09-30-00 +0000,wsj,Kevin Warsh is to be sworn in as Fed chair on ...,https://www.wsj.com/economy/central-banking/tr...
51,47,2026-05-22-12-47-28 +0000,nyt,"With Gas Prices Through the Roof, Will Renting...",https://www.nytimes.com/2026/05/22/travel/elec...
167,46,2026-05-22-06-53-44 +0000,nypost,Former Texas district attorney charged with fe...,https://nypost.com/2026/05/22/us-news/former-t...
316,45,2026-05-21-18-46-46 +0000,nypost,Don Lemon trashes ex-boss ahead of Colbert’s l...,https://nypost.com/2026/05/21/media/don-lemon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)