## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-21-01-19-15 +0000,nypost,Israel set to host Middle East’s largest pride...,https://nypost.com/2026/04/20/world-news/israe...
1,2026-04-21-01-14-36 +0000,nyt,Iran War Live Updates: Tehran and Trump Send S...,https://www.nytimes.com/live/2026/04/20/world/...
2,2026-04-21-01-14-05 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...
3,2026-04-21-01-08-24 +0000,nypost,Fallen-on-hard-times members club seeks new re...,https://nypost.com/2026/04/20/us-news/peek-ins...
4,2026-04-21-01-05-41 +0000,bbc,US singer D4vd pleads not guilty to murder in ...,https://www.bbc.com/news/articles/crr1v4gzkvlo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2589/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
7          iran     28
12        trump     25
27          new     23
8           war     14
441  california     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
284,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...,117
229,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...,116
2,2026-04-21-01-14-05 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,107
258,2026-04-20-13-22-31 +0000,nypost,Trump tells The Post he’s willing to meet with...,https://nypost.com/2026/04/20/us-news/jd-vance...,107
1,2026-04-21-01-14-36 +0000,nyt,Iran War Live Updates: Tehran and Trump Send S...,https://www.nytimes.com/live/2026/04/20/world/...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
284,117,2026-04-20-10-35-10 +0000,nypost,Iran says ‘no decision’ has been made about at...,https://nypost.com/2026/04/20/world-news/iran-...
6,89,2026-04-21-01-00-00 +0000,wsj,President Trump picked Kevin Warsh for Fed cha...,https://www.wsj.com/economy/central-banking/wa...
229,54,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...
314,45,2026-04-20-09-00-07 +0000,wapo,Gas prices threaten GOP in race that could hel...,https://www.washingtonpost.com/business/2026/0...
52,44,2026-04-20-22-35-04 +0000,startribune,Tim Cook will step down as Apple CEO and hand ...,https://www.startribune.com/tim-cook-will-step...
80,42,2026-04-20-21-26-51 +0000,nypost,Inside Elon Musk and Sam Altman’s battle to be...,https://nypost.com/2026/04/20/us-news/elon-mus...
207,38,2026-04-20-16-32-34 +0000,nypost,"FBI Director Kash Patel sues The Atlantic, rep...",https://nypost.com/2026/04/20/media/fbi-direct...
9,37,2026-04-21-00-53-48 +0000,wapo,Labor Secretary Lori Chavez-DeRemer will resig...,https://www.washingtonpost.com/business/2026/0...
108,36,2026-04-20-20-27-31 +0000,nypost,"1 tourist dead, 6 hurt when gunman opens fire ...",https://nypost.com/2026/04/20/world-news/shoot...
59,36,2026-04-20-22-16-55 +0000,wapo,Two teens killed after planned fight near Nort...,https://www.washingtonpost.com/nation/2026/04/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)