## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-30-21-10-06 +0000,bbc,"Ebola spread in DR Congo 'deeply alarming', MS...",https://www.bbc.com/news/articles/c99ldxykz4zo...
1,2026-05-30-21-02-00 +0000,wsj,SoftBank to Plow $52 Billion Into French Data ...,https://www.wsj.com/tech/ai/softbank-to-plow-5...
2,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...
3,2026-05-30-20-58-05 +0000,bbc,'It's like a decaying body': Australian farmer...,https://www.bbc.com/news/articles/c794g80lw74o...
4,2026-05-30-20-48-51 +0000,nyt,Loud Boom in Boston Area Puzzles Residents,https://www.nytimes.com/2026/05/30/us/boston-a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14        trump     35
371      health     10
349  california     10
316          he      8
378        anti      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...,108
196,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...,81
73,2026-05-30-15-06-01 +0000,bbc,Trump's doctor says he's in excellent health -...,https://www.bbc.com/news/articles/c9q39dx778zo...,76
97,2026-05-30-11-23-00 +0000,wsj,President Trump “remains in excellent physical...,https://www.wsj.com/politics/trump-remains-in-...,76
141,2026-05-30-06-43-02 +0000,nypost,White House releases doctor’s memo from Trump’...,https://nypost.com/2026/05/30/us-news/trump-in...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,108,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...
196,46,2026-05-29-23-00-00 +0000,wsj,President Trump’s top aides have discussed whe...,https://www.wsj.com/politics/policy/trumps-1-8...
26,39,2026-05-30-19-16-00 +0000,wsj,The wife of Maine Democratic Senate candidate ...,https://www.wsj.com/politics/elections/graham-...
97,39,2026-05-30-11-23-00 +0000,wsj,President Trump “remains in excellent physical...,https://www.wsj.com/politics/trump-remains-in-...
156,36,2026-05-30-02-56-23 +0000,nypost,"Fajitas, stir-fry, BBQ chicken – see the food...",https://nypost.com/2026/05/29/us-news/fajitas-...
48,33,2026-05-30-17-34-30 +0000,bbc,'No-one feels safe now': Residents of Romanian...,https://www.bbc.com/news/articles/cvgzyp93jq1o...
19,31,2026-05-30-19-44-40 +0000,nypost,Spencer Pratt blasts Karen Bass and Gavin News...,https://nypost.com/2026/05/30/us-news/spencer-...
61,31,2026-05-30-16-34-30 +0000,nyt,"As Trump Mulls Decision About Iran War Deal, a...",https://www.nytimes.com/2026/05/30/world/middl...
152,30,2026-05-30-03-10-00 +0000,wsj,The Trump administration recently announced a ...,https://www.wsj.com/politics/policy/green-card...
168,29,2026-05-30-01-12-03 +0000,latimes,Your last minute voter guide to the 2026 Calif...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)