## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-08-10-15-36 +0000,bbc,What do businesses want ahead of the election?,https://www.bbc.com/news/videos/ckgr4r9k2dqo?a...
1,2026-04-08-10-13-00 +0000,wsj,Health Care Roundup: Market Talk,https://www.wsj.com/business/health-care-round...
2,2026-04-08-10-10-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...
3,2026-04-08-10-08-51 +0000,nyt,Iran War Live Updates: Fragile Cease-Fire Take...,https://www.nytimes.com/live/2026/04/08/world/...
4,2026-04-08-10-04-58 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/08/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2594/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
12   iran     76
34  trump     68
13    war     25
18   fire     18
17  cease     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
85,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...,281
146,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...,277
157,2026-04-07-22-42-19 +0000,nypost,Strait of Hormuz to reopen after Trump announc...,https://nypost.com/2026/04/07/world-news/trump...,231
40,2026-04-08-08-38-12 +0000,nypost,Trump declares Iran cease-fire deal could lead...,https://nypost.com/2026/04/08/world-news/trump...,220
89,2026-04-08-03-30-55 +0000,bbc,Iran ceasefire deal gives Trump a way out of w...,https://www.bbc.com/news/articles/cwyvp55xrlro...,212

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
85,281,2026-04-08-03-58-00 +0000,wsj,Trump backed off a threat to wipe out the Iran...,https://www.wsj.com/world/middle-east/trump-ba...
291,70,2026-04-07-16-07-18 +0000,nypost,"Russia, China reject resolution to reopen Stra...",https://nypost.com/2026/04/07/us-news/russia-c...
105,62,2026-04-08-01-53-00 +0000,wsj,Republican Clayton Fuller won the special elec...,https://www.wsj.com/politics/elections/republi...
63,49,2026-04-08-06-39-05 +0000,nyt,"Despite High Oil Prices and Volatile Stocks, C...",https://www.nytimes.com/2026/04/07/business/co...
146,49,2026-04-07-23-26-00 +0000,wsj,"As Trump threatens a major escalation in Iran,...",https://www.wsj.com/politics/some-republicans-...
86,45,2026-04-08-03-54-35 +0000,nypost,California would fund lawyers for all illegal ...,https://nypost.com/2026/04/07/us-news/californ...
49,42,2026-04-08-07-55-36 +0000,nypost,Husband of missing American in Bahamas ‘previo...,https://nypost.com/2026/04/08/us-news/husband-...
264,41,2026-04-07-17-47-20 +0000,nypost,"The secret, never-before-used CIA tool that he...",https://nypost.com/2026/04/07/us-news/ghost-mu...
293,40,2026-04-07-16-01-00 +0000,wsj,The U.S. labor market bounced back last month ...,https://www.wsj.com/economy/jobs/why-more-peop...
311,38,2026-04-07-14-51-07 +0000,bbc,One gunman killed and two injured in shooting ...,https://www.bbc.com/news/articles/c3exp8j7yz4o...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)