## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-15-01-16-22 +0000,nypost,Tennessee tries to poach Paramount Skydance fr...,https://nypost.com/2026/07/14/us-news/tennesse...
1,2026-07-15-01-16-00 +0000,48hills,The Femcels: Barred from the US because their ...,https://48hills.org/2026/07/the-femcels-barred...
2,2026-07-15-01-10-48 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/14/world/...
3,2026-07-15-01-10-00 +0000,wsj,Asian Currencies May Be Aided by Weaker Dollar...,https://www.wsj.com/finance/currencies/asian-c...
4,2026-07-15-01-03-53 +0000,nypost,WGA filing lawsuit to block Paramount’s $81B W...,https://nypost.com/2026/07/14/business/wga-fil...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2571/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
128   trump     34
58     iran     28
94      new     20
43      ice     17
219  hormuz     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
81,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...,148
224,2026-07-14-16-06-00 +0000,wsj,The Battle for Hormuz: Trump Shifts Into Dange...,https://www.wsj.com/world/middle-east/the-batt...,115
136,2026-07-14-20-07-29 +0000,nyt,Trump Drops Plan to Tax Ships in Strait of Hor...,https://www.nytimes.com/2026/07/14/world/middl...,113
36,2026-07-14-23-17-27 +0000,bbc,Trump retreat over Hormuz tolls suggests he is...,https://www.bbc.co.uk/news/articles/crele3r8j1...,111
29,2026-07-14-23-41-00 +0000,wsj,"Trump Reverses 20% Strait of Hormuz Toll, as U...",https://www.wsj.com/world/middle-east/trump-ir...,108

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
81,148,2026-07-14-21-45-00 +0000,wsj,"Trump’s Iran blockade resumes, Kevin Warsh say...",https://www.wsj.com/politics/policy/u-s-reimpo...
91,73,2026-07-14-21-19-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...
68,66,2026-07-14-22-13-00 +0000,wsj,The House passed legislation supported by Pres...,https://www.wsj.com/politics/policy/house-pass...
106,65,2026-07-14-21-01-48 +0000,latimes,Oil tanker captain didn't know he was hauling ...,https://www.latimes.com/california/story/2026-...
217,60,2026-07-14-16-39-12 +0000,latimes,ICE will suspend most vehicle stops in the wak...,https://www.latimes.com/world-nation/story/202...
336,55,2026-07-14-03-51-12 +0000,nyt,Paramount-Warner Bros. Merger Is Challenged in...,https://www.nytimes.com/2026/07/13/business/pa...
214,53,2026-07-14-16-40-54 +0000,nypost,"Iran claims attacks on Bahrain, Jordan, Strait...",https://nypost.com/2026/07/14/world-news/iran-...
263,37,2026-07-14-13-40-13 +0000,nypost,JPMorgan Chase racks up biggest profit ever fo...,https://nypost.com/2026/07/14/business/jpmorga...
206,33,2026-07-14-17-00-17 +0000,nyt,"Ann Widdecombe Was Killed in ‘Targeted Attack,...",https://www.nytimes.com/2026/07/14/world/europ...
223,32,2026-07-14-16-06-59 +0000,nypost,Supreme Court Justice Amy Coney Barrett says h...,https://nypost.com/2026/07/14/us-news/amy-cone...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)