## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...
1,2026-07-04-02-21-25 +0000,nyt,Celebrating America’s 250th Anniversary Across...,https://www.nytimes.com/2026/07/03/us/july-4-2...
2,2026-07-04-02-16-25 +0000,nypost,Storm leaves 3 capsized boaters dead as police...,https://nypost.com/2026/07/03/us-news/storm-le...
3,2026-07-04-02-10-15 +0000,nyt,Air Force Detains Officer Who Called for Trump...,https://www.nytimes.com/2026/07/03/us/politics...
4,2026-07-04-02-06-23 +0000,nyt,Trump Pardons Violators of the Clean Air Act a...,https://www.nytimes.com/2026/07/03/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2588/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10   trump     23
15      th     13
62   world     11
254    was     11
63     cup     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
36,2026-07-03-23-43-00 +0000,wsj,President Trump will speak in front of Mount R...,https://www.wsj.com/us-news/donald-trump-mount...,78
66,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...,66
162,2026-07-03-11-55-27 +0000,nypost,What to expect at Trump’s epic 4th of July ‘Sa...,https://nypost.com/2026/07/03/us-news/what-to-...,65
0,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,64
229,2026-07-03-02-51-34 +0000,nypost,Secret Service member was Googling rooftop loc...,https://nypost.com/2026/07/02/us-news/secret-s...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
36,78,2026-07-03-23-43-00 +0000,wsj,President Trump will speak in front of Mount R...,https://www.wsj.com/us-news/donald-trump-mount...
32,49,2026-07-04-00-00-00 +0000,wsj,Capital Account: The 250th anniversary of the ...,https://www.wsj.com/economy/american-instituti...
157,48,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
66,43,2026-07-03-20-51-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
7,38,2026-07-04-01-55-12 +0000,nypost,"Tourists stumble upon Taylor Swift, Travis Kel...",https://nypost.com/2026/07/03/us-news/tourists...
117,38,2026-07-03-15-20-57 +0000,bbc,Ukrainian suspect hunted by police after Monac...,https://www.bbc.co.uk/news/articles/c4gy603z2q...
116,31,2026-07-03-15-31-54 +0000,nypost,Americans hit the road in record numbers for 4...,https://nypost.com/2026/07/03/business/america...
44,29,2026-07-03-22-59-21 +0000,nypost,Husband’s unbelievable decision after wife con...,https://nypost.com/2026/07/03/us-news/husbands...
106,27,2026-07-03-16-19-30 +0000,nypost,Woman loses savings to AI-powered romance scam...,https://nypost.com/2026/07/03/business/woman-l...
141,27,2026-07-03-13-29-04 +0000,nyt,Cape Verde Faces Argentina’s World Cup Juggern...,https://www.nytimes.com/2026/07/03/world/afric...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)