## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-19-02-48 +0000,chitri,Winnetka home sells for $8.9M in village’s hig...,https://www.chicagotribune.com/2026/10/26/elit...
1,2026-10-26-19-01-46 +0000,chitri,CPD unveils new policy on license plate reader...,https://www.chicagotribune.com/2026/10/26/cpd-...
2,2026-10-26-18-59-20 +0000,nypost,Brooklyn Grandmas take center stage at the 25t...,https://nypost.com/2026/10/26/lifestyle/babush...
3,2026-10-26-18-53-00 +0000,wsj,Tech Shares Rally After Anthropic Files for Hi...,https://www.wsj.com/finance/investing/stock-fu...
4,2026-10-26-18-49-53 +0000,startribune,Minnesota appeals court reinstates guilty verd...,https://www.startribune.com/minnesota-court-of...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2343/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
95   election     30
94      trump     30
193      lula     21
10        new     17
198    brazil     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
249,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...,123
276,2026-10-25-23-32-38 +0000,chitri,Luiz Inácio Lula da Silva declared winner of B...,https://www.chicagotribune.com/2026/10/25/braz...,101
79,2026-10-26-15-57-12 +0000,nypost,"Brazil markets, currency reel from leftist Lui...",https://nypost.com/2026/10/26/business/brazil-...,93
172,2026-10-26-11-06-00 +0000,wsj,The Morning Risk Report: Lula Wins Fourth Term...,https://www.wsj.com/risk-compliance-journal/th...,92
260,2026-10-26-00-51-25 +0000,nypost,"Trump critic Lula wins reelection in Brazil, s...",https://nypost.com/2026/10/25/world-news/trump...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
249,123,2026-10-26-02-13-00 +0000,wsj,President Luiz Inácio Lula da Silva clung to p...,https://www.wsj.com/world/americas/lula-clings...
264,68,2026-10-26-00-30-06 +0000,chitri,President Donald Trump escalates anti-Muslim a...,https://www.chicagotribune.com/2026/10/25/trum...
312,63,2026-10-25-19-38-58 +0000,nypost,Venezuelan opposition leader María Corina Mach...,https://nypost.com/2026/10/25/world-news/venez...
173,53,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
159,53,2026-10-26-12-00-00 +0000,nypost,Inside California’s unlikely new boomtown wher...,https://nypost.com/2026/10/26/real-estate/fres...
61,47,2026-10-26-16-51-12 +0000,nypost,Pro-Abdul El-Sayed ad sparks fury with false c...,https://nypost.com/2026/10/26/us-news/pro-abdu...
224,46,2026-10-26-08-24-19 +0000,wsj,Stock Market Today: Tech Shares Rally After An...,https://www.wsj.com/livecoverage/stock-market-...
215,42,2026-10-26-09-03-34 +0000,nyt,Darline Graham Gets Help From the Data Center ...,https://www.nytimes.com/2026/10/26/us/politics...
169,39,2026-10-26-11-17-19 +0000,chitri,Serbia’s Aleksandar Vucic concedes defeat to t...,https://www.chicagotribune.com/2026/10/26/serb...
126,32,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)