## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-18-46-58 +0000,startribune,Class 6A football state tournament brackets re...,https://www.startribune.com/minnesota-high-sch...
1,2026-10-24-18-35-49 +0000,nyt,France Protest Updates: Hundreds of Thousands ...,https://www.nytimes.com/live/2026/10/24/world/...
2,2026-10-24-18-35-47 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/10/24/world/...
3,2026-10-24-18-26-47 +0000,nypost,Horrifying fireball crash near LAX leaves 1 de...,https://nypost.com/2026/10/24/us-news/fiery-cr...
4,2026-10-24-18-24-42 +0000,nyt,"In U.S. Gas Talks With Kremlin, Hidden Financi...",https://www.nytimes.com/2026/10/23/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
42     trump     27
37  election     16
46       new     12
5     france     11
80   ukraine      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
195,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,95
5,2026-10-24-18-19-24 +0000,nyt,Alaska Election Gambit Shows Justice Dept. Has...,https://www.nytimes.com/2026/10/24/us/politics...,66
158,2026-10-24-01-12-02 +0000,chitri,President Trump at South Florida rally revives...,https://www.chicagotribune.com/2026/10/23/trum...,59
152,2026-10-24-02-35-00 +0000,wsj,The Trump administration has asked a federal c...,https://www.wsj.com/politics/elections/justice...,58
137,2026-10-24-07-17-44 +0000,bbc,White House says Melania Trump brokered truce ...,https://www.bbc.co.uk/news/articles/c6vgxkvl4w...,53

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
195,95,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
9,50,2026-10-24-17-45-16 +0000,nyt,Netanyahu Is Up for Re-election After Years of...,https://www.nytimes.com/2026/10/24/world/middl...
162,47,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
161,44,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
132,36,2026-10-24-08-00-00 +0000,cbc,Black Sea sailors thought a rescue boat was ra...,https://www.cbc.ca/news/world/black-sea-attack...
1,32,2026-10-24-18-35-49 +0000,nyt,France Protest Updates: Hundreds of Thousands ...,https://www.nytimes.com/live/2026/10/24/world/...
33,32,2026-10-24-16-27-25 +0000,nypost,NYC schools investigators had secret ammo stas...,https://nypost.com/2026/10/24/us-news/nyc-scho...
158,32,2026-10-24-01-12-02 +0000,chitri,President Trump at South Florida rally revives...,https://www.chicagotribune.com/2026/10/23/trum...
224,30,2026-10-23-20-42-15 +0000,chitri,Wall Street loses ground under pressure from r...,https://www.chicagotribune.com/2026/10/23/wall...
140,30,2026-10-24-06-21-06 +0000,nyt,Justice Dept. Demands That California Counties...,https://www.nytimes.com/2026/10/23/us/justice-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)