## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-14-12-08-00 +0000,wsj,Albertsons Swings to a Loss on Charge From Opi...,https://www.wsj.com/business/retail/albertsons...
1,2026-04-14-12-06-38 +0000,nyt,Iran War Live Updates: U.S. and Iran Trade Pro...,https://www.nytimes.com/live/2026/04/14/world/...
2,2026-04-14-12-03-46 +0000,nypost,Eric Swalwell victims reveal powerful reason w...,https://nypost.com/2026/04/14/us-news/eric-swa...
3,2026-04-14-12-02-00 +0000,wsj,BMW Group Vehicle Sales Fall on Weakness in Ch...,https://www.wsj.com/business/autos/bmw-group-v...
4,2026-04-14-12-00-00 +0000,missionlocal,More than 400 people in S.F. have sought to se...,https://missionlocal.org/2026/04/sf-ice-immigr...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2585/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
224     trump     53
6        iran     43
63   blockade     29
7         war     24
68     hormuz     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
196,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,175
305,2026-04-13-17-15-47 +0000,nyt,"To Open the Strait of Hormuz, Trump Wants to B...",https://www.nytimes.com/2026/04/13/world/middl...,170
371,2026-04-13-12-13-38 +0000,cbc,Trump warns Iran attack ships will be 'elimina...,https://www.cbc.ca/news/world/livestory/us-isr...,163
351,2026-04-13-14-31-56 +0000,nypost,"Dow jumps 300 points, oil below $100 after Tru...",https://nypost.com/2026/04/13/business/dow-fal...,147
141,2026-04-14-03-56-00 +0000,wsj,Trump’s Blockade on Iran in Strait Begins,https://www.wsj.com/world/middle-east/trumps-b...,146

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
196,175,2026-04-13-22-55-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...
309,108,2026-04-13-17-05-41 +0000,nypost,Here’s how the US blockade of Strait of Hormuz...,https://nypost.com/2026/04/13/world-news/how-w...
197,86,2026-04-13-22-55-00 +0000,wsj,Democratic Rep. Eric Swalwell of California an...,https://www.wsj.com/politics/house-removal-vot...
152,55,2026-04-14-02-32-24 +0000,nypost,Trump reveals why he deleted AI post of himsel...,https://nypost.com/2026/04/13/us-news/trump-re...
264,54,2026-04-13-19-56-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
260,51,2026-04-13-20-14-55 +0000,nyt,Oil Prices Are Pressured and Stocks Gain After...,https://www.nytimes.com/2026/04/12/business/oi...
150,50,2026-04-14-02-47-00 +0000,wsj,Canadian Prime Minister Mark Carney has secure...,https://www.wsj.com/world/americas/canadas-car...
86,48,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...
227,47,2026-04-13-21-28-14 +0000,bbc,Hungary's next PM would pick up if Putin calls...,https://www.bbc.com/news/articles/cd6lzezp4zvo...
116,39,2026-04-14-07-55-27 +0000,nypost,Arizona woman charged with murdering her newbo...,https://nypost.com/2026/04/14/us-news/arizona-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)