## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-26-01-13-00 +0000,wsj,"Venezuela’s Machado Returns Home, Challenging ...",https://www.wsj.com/world/americas/venezuelas-...
1,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
2,2026-10-26-01-12-21 +0000,nyt,Trump’s Election Attacks Enter New Pre-emptive...,https://www.nytimes.com/2026/10/25/us/politics...
3,2026-10-26-01-10-00 +0000,wsj,Lula Clings to Power in Brazil Election Upset,https://www.wsj.com/world/americas/lula-clings...
4,2026-10-26-01-08-42 +0000,nyt,Caryle Murphy Has Died. She Earned a Pulitzer ...,https://www.nytimes.com/2026/10/25/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2514/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
24     trump     24
25  election     18
35    brazil     12
28       new     12
32      lula     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
17,2026-10-26-00-30-30 +0000,cbc,Trump critic Lula narrowly wins re-election in...,https://www.cbc.ca/news/world/lula-brazil-reel...,79
9,2026-10-26-00-51-25 +0000,nypost,"Trump critic Lula wins reelection in Brazil, s...",https://nypost.com/2026/10/25/world-news/trump...,68
18,2026-10-26-00-30-06 +0000,chitri,President Donald Trump escalates anti-Muslim a...,https://www.chicagotribune.com/2026/10/25/trum...,65
226,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,64
1,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
17,79,2026-10-26-00-30-30 +0000,cbc,Trump critic Lula narrowly wins re-election in...,https://www.cbc.ca/news/world/lula-brazil-reel...
1,63,2026-10-26-01-13-00 +0000,wsj,Venezuelan opposition leader María Corina Mach...,https://www.wsj.com/world/americas/venezuelas-...
18,41,2026-10-26-00-30-06 +0000,chitri,President Donald Trump escalates anti-Muslim a...,https://www.chicagotribune.com/2026/10/25/trum...
226,40,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...
127,37,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
140,35,2026-10-25-15-20-17 +0000,nypost,Musk confirms SpaceX was behind thwarting of U...,https://nypost.com/2026/10/25/us-news/musk-con...
29,32,2026-10-25-23-44-34 +0000,bbc,Data centre debate heats up ahead of US midter...,https://www.bbc.co.uk/news/articles/cq2e9we7w2...
97,32,2026-10-25-19-34-12 +0000,nypost,"Thomas Markle’s home had trove of child porn, ...",https://nypost.com/2026/10/25/world-news/thoma...
7,30,2026-10-26-01-00-00 +0000,wsj,California’s proposed billionaire tax sparked ...,https://www.wsj.com/politics/california-billio...
11,28,2026-10-26-00-45-21 +0000,chitri,Iranians fear a possible return to all-out war...,https://www.chicagotribune.com/2026/10/25/iran...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)