## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-04-13-16-21 +0000,bbc,First government flight for UK nationals due t...,https://www.bbc.com/news/articles/cy4wwd2jlypo...
1,2026-03-04-13-14-30 +0000,wapo,Live updates: NATO condemns Iran after shootin...,https://www.washingtonpost.com/world/2026/03/0...
2,2026-03-04-13-14-30 +0000,wapo,Defense Secretary Pete Hegseth said the United...,https://www.washingtonpost.com
3,2026-03-04-13-13-08 +0000,bbc,Greek court upholds criminal organisation verd...,https://www.bbc.com/news/articles/c89kkykg39yo...
4,2026-03-04-13-12-00 +0000,wsj,Abercrombie & Fitch Forecasts Continued Growth...,https://www.wsj.com/business/retail/abercrombi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2527/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
13      iran     88
53     trump     44
171      war     34
109    texas     30
394  strikes     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
103,2026-03-04-09-58-00 +0000,wsj,Spain’s Sanchez Reiterates Opposition to Iran ...,https://www.wsj.com/world/europe/spains-sanche...,194
393,2026-03-03-17-47-44 +0000,nypost,Trump vows to ‘cut off all trade with Spain’: ...,https://nypost.com/2026/03/03/us-news/trump-vo...,192
325,2026-03-03-21-11-57 +0000,nypost,Rubio walks back claim Israel forced Trump’s t...,https://nypost.com/2026/03/03/us-news/rubio-wa...,191
27,2026-03-04-12-34-49 +0000,nyt,"Spain’s Leader, Rejecting Iran War, Escalates ...",https://www.nytimes.com/2026/03/04/world/europ...,189
25,2026-03-04-12-35-17 +0000,bbc,UK stock market calms but oil prices rise over...,https://www.bbc.com/news/articles/cwy884ekn0jo...,182

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
103,194,2026-03-04-09-58-00 +0000,wsj,Spain’s Sanchez Reiterates Opposition to Iran ...,https://www.wsj.com/world/europe/spains-sanche...
112,120,2026-03-04-08-44-00 +0000,wsj,"State Rep. James Talarico, a 36-year-old with ...",https://www.wsj.com/politics/elections/john-co...
301,91,2026-03-03-22-10-00 +0000,wsj,Middle East Conflict Circles the World’s Marke...,https://www.wsj.com/finance/stocks/middle-east...
123,73,2026-03-04-08-02-45 +0000,nypost,US hits nearly 2K Iranian targets in first 100...,https://nypost.com/2026/03/04/world-news/us-op...
172,62,2026-03-04-04-41-00 +0000,wsj,A House committee investigating the Jeffrey Ep...,https://www.wsj.com/politics/policy/house-comm...
398,56,2026-03-03-17-28-00 +0000,wsj,U.S. Troops Killed in Kuwait Had No Warning of...,https://www.wsj.com/world/middle-east/u-s-troo...
215,55,2026-03-04-01-10-05 +0000,nypost,Masked driver of car loaded with ammunition de...,https://nypost.com/2026/03/03/us-news/suspicio...
25,53,2026-03-04-12-35-17 +0000,bbc,UK stock market calms but oil prices rise over...,https://www.bbc.com/news/articles/cwy884ekn0jo...
104,53,2026-03-04-09-46-35 +0000,nypost,Israel threatens Ayatollah Khamenei’s successo...,https://nypost.com/2026/03/04/world-news/iran-...
306,49,2026-03-03-21-51-24 +0000,latimes,L.A. County leaders push new safety measures i...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)