## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-13-19-14-23 +0000,nyt,‘We Finally Have Democracy’: Hungarians Erupt ...,https://www.nytimes.com/2026/04/13/world/europ...
1,2026-04-13-19-10-51 +0000,nypost,US pitched Iran on 20-year uranium enrichment ...,https://nypost.com/2026/04/13/world-news/us-pi...
2,2026-04-13-19-10-28 +0000,bbc,US drivers head to Native American lands for c...,https://www.bbc.com/news/videos/c1krg1rzpmeo?a...
3,2026-04-13-19-08-54 +0000,nypost,Fury at California’s ‘insane’ mental health di...,https://nypost.com/2026/04/13/us-news/prosecut...
4,2026-04-13-19-08-46 +0000,nyt,Trump’s Explanation for an Image of Himself as...,https://www.nytimes.com/2026/04/13/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
33     trump     50
7       iran     41
61  blockade     27
54       war     20
63    hormuz     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
55,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...,179
230,2026-04-13-06-59-06 +0000,nypost,"Trump says Iran is ‘in very bad shape,’ doesn’...",https://nypost.com/2026/04/13/world-news/trump...,171
177,2026-04-13-11-35-14 +0000,nypost,Defiant Iran accuses US of ‘piracy’ over Strai...,https://nypost.com/2026/04/13/world-news/defia...,169
58,2026-04-13-17-20-00 +0000,wsj,President Trump lashed out at Pope Leo XIV fol...,https://www.wsj.com/politics/elections/trump-c...,165
258,2026-04-13-01-36-13 +0000,nypost,"Trump blasts Pope Leo as ‘weak on crime,’ says...",https://nypost.com/2026/04/12/us-news/trump-bl...,165

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
55,179,2026-04-13-17-25-07 +0000,nypost,Trump makes wild claim defending Jesus-like AI...,https://nypost.com/2026/04/13/us-news/trump-re...
64,104,2026-04-13-17-05-41 +0000,nypost,Here’s how the US blockade of Strait of Hormuz...,https://nypost.com/2026/04/13/world-news/how-w...
262,102,2026-04-13-01-25-00 +0000,wsj,Rep. Eric Swalwell said he was suspending his ...,https://www.wsj.com/politics/policy/democrats-...
119,57,2026-04-13-15-30-02 +0000,cbc,EU president calls Hungary election a 'victory...,https://www.cbc.ca/news/world/hungary-magyar-w...
109,51,2026-04-13-15-50-00 +0000,wsj,A new White House study concludes that DEI pol...,https://www.wsj.com/business/white-house-study...
13,48,2026-04-13-18-55-29 +0000,cbc,Judge throws out Trump's $10B US lawsuit again...,https://www.cbc.ca/news/world/trump-lawsuit-di...
185,35,2026-04-13-11-03-00 +0000,wsj,Two of the most recognizable people on the pla...,https://www.wsj.com/politics/the-showdown-betw...
27,34,2026-04-13-18-17-44 +0000,nypost,Iran doesn’t have ‘military means’ to keep up ...,https://nypost.com/2026/04/13/world-news/iran-...
45,31,2026-04-13-17-44-31 +0000,nypost,NY GOP gubernatorial candidate Bruce Blakeman ...,https://nypost.com/2026/04/13/us-news/ny-gop-g...
141,28,2026-04-13-14-20-58 +0000,cbc,Ghanaian Premier League player killed in suspe...,https://www.cbc.ca/sports/soccer/ghanaian-socc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)