## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-05-11-51-38 +0000,nypost,Rescuers in Nepal miraculously pull survivor f...,https://nypost.com/2026/09/05/world-news/chine...
1,2026-09-05-11-40-53 +0000,nypost,NYC DSA chapter moving into luxe new digs — as...,https://nypost.com/2026/09/05/us-news/nyc-dsa-...
2,2026-09-05-11-39-55 +0000,nyt,Iran’s State Media Says U.S. Missiles Hit Iran...,https://www.nytimes.com/2026/09/05/world/middl...
3,2026-09-05-11-22-15 +0000,nypost,First victim of 9/11 would be horrified by tod...,https://nypost.com/2026/09/05/us-news/the-firs...
4,2026-09-05-11-16-11 +0000,bbc,Reform promises to increase tax-free personal ...,https://www.bbc.co.uk/news/articles/cgk5g51xk5...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
80    trump     40
86   clancy     22
85  lindsay     20
14      new     17
81      war     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
224,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...,101
227,2026-09-04-19-09-01 +0000,nypost,"New York, New Jersey Hasidic leaders meet Trum...",https://nypost.com/2026/09/04/us-news/new-york...,96
324,2026-09-04-14-36-42 +0000,nypost,Trump threatens trade with dozens of countries...,https://nypost.com/2026/09/04/us-news/trump-de...,96
81,2026-09-05-02-33-31 +0000,chitri,Midterm mail ballots start to go out to voters...,https://www.chicagotribune.com/2026/09/04/midt...,87
320,2026-09-04-14-43-30 +0000,cbc,Judge declares mistrial in Lindsay Clancy’s mu...,https://www.cbc.ca/news/world/lindsay-clancy-t...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
224,101,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...
195,74,2026-09-04-20-33-00 +0000,wsj,Democrats criticized Sen. John Fetterman after...,https://www.wsj.com/politics/policy/democrats-...
102,63,2026-09-05-01-00-00 +0000,wsj,Workers across all sectors are switching jobs ...,https://www.wsj.com/economy/jobs/american-work...
259,61,2026-09-04-17-40-08 +0000,nyt,Iran War Helps to Drive U.S. Diesel Prices to ...,https://www.nytimes.com/2026/09/04/business/di...
28,58,2026-09-05-09-30-00 +0000,wsj,How do you view the major components of Americ...,https://www.wsj.com/politics/young-people-see-...
164,53,2026-09-04-21-09-00 +0000,wsj,The Supreme Court cleared the way for politica...,https://www.wsj.com/politics/policy/supreme-co...
326,48,2026-09-04-14-32-00 +0000,wsj,Two Men Pulled Alive From Tunnel Nine Days Aft...,https://www.wsj.com/world/asia/two-men-pulled-...
160,43,2026-09-04-21-18-00 +0000,wsj,U.S. Stocks Fall as Robust August Jobs Data Sp...,https://www.wsj.com/finance/investing/u-s-stoc...
114,41,2026-09-04-23-52-13 +0000,nyt,Judge Will Not Block Pentagon Move to Fire Sta...,https://www.nytimes.com/2026/09/04/us/politics...
363,37,2026-09-04-12-26-06 +0000,nypost,Three dead in Ukraine after overnight Russia a...,https://nypost.com/2026/09/04/world-news/three...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)