## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-01-07-28-59 +0000,nyt,After Tens of Thousands of Migrants Enter Span...,https://www.nytimes.com/live/2026/07/31/world/...
1,2026-08-01-07-28-20 +0000,nyt,Beijing Protests After New Zealand Minister In...,https://www.nytimes.com/2026/08/01/world/asia/...
2,2026-08-01-07-22-30 +0000,bbc,Race to rescue remaining climbers after deadly...,https://www.bbc.co.uk/news/articles/cddjz1r01l...
3,2026-08-01-07-21-46 +0000,bbc,"Russian strikes on Kyiv kill at least nine, Uk...",https://www.bbc.co.uk/news/articles/ce973yvk7p...
4,2026-08-01-07-14-41 +0000,nyt,"Russian Missiles Kill 9 in Kyiv, Hours After T...",https://www.nytimes.com/2026/08/01/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
34      trump     38
2    migrants     17
11        new     16
165      iran     16
221        up     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,97
238,2026-07-31-16-21-46 +0000,nypost,Trump orders more strikes on Iran after ‘losin...,https://nypost.com/2026/07/31/us-news/trump-pr...,90
335,2026-07-31-10-23-17 +0000,cbc,"Trump touts Gaza peace deal, though Hamas and ...",https://www.cbc.ca/news/world/hamas-israel-dis...,90
289,2026-07-31-13-29-17 +0000,chitri,President Donald Trump announces a deal for Ha...,https://www.chicagotribune.com/2026/07/31/trum...,89
105,2026-07-31-22-19-00 +0000,wsj,Trump Orders Fresh Attack Against Iran as War ...,https://www.wsj.com/world/middle-east/trump-so...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,97,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...
374,83,2026-07-31-08-02-28 +0000,nypost,At least 18 migrants dead as 49K breached bord...,https://nypost.com/2026/07/31/world-news/at-le...
304,73,2026-07-31-12-57-09 +0000,chitri,Senior FIFA executive says staff was deceived ...,https://www.chicagotribune.com/2026/07/31/fifa...
108,64,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...
122,62,2026-07-31-21-33-06 +0000,nypost,Jeanine Pirro drops Reflecting Pool vandalism ...,https://nypost.com/2026/07/31/us-news/jeanine-...
279,60,2026-07-31-14-19-00 +0000,wsj,Three Fed policymakers said stubborn inflation...,https://www.wsj.com/economy/central-banking/tw...
293,56,2026-07-31-13-20-45 +0000,nyt,Europe Is Caught Between Low Gas Reserves and ...,https://www.nytimes.com/2026/07/31/business/eu...
220,47,2026-07-31-17-20-50 +0000,nypost,California Gov. Gavin Newsom releases long-awa...,https://nypost.com/2026/07/31/us-news/gavin-ne...
52,43,2026-08-01-01-01-00 +0000,wsj,"In purple Michigan, Rep. Haley Stevens and Abd...",https://www.wsj.com/politics/elections/michiga...
360,42,2026-07-31-09-13-33 +0000,nypost,Pakistan rescuers find 4 bodies of the 10 clim...,https://nypost.com/2026/07/31/world-news/pakis...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)