## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-10-14-43 +0000,bbc,Starmer 'appalled' by case of boys spared jail...,https://www.bbc.com/news/articles/c332ljdkd81o...
1,2026-05-25-10-11-00 +0000,wsj,Pope Leo Compares AI Threat to Biblical ‘Tower...,https://www.wsj.com/world/pope-leo-ai-encyclic...
2,2026-05-25-10-08-21 +0000,nyt,"Pope Leo Warns of Risks From A.I. in 42,300-Wo...",https://www.nytimes.com/2026/05/25/world/europ...
3,2026-05-25-10-04-56 +0000,nyt,"U.S.-Iran Peace Deal Nearer, But Could Take Da...",https://www.nytimes.com/live/2026/05/24/world/...
4,2026-05-25-10-04-54 +0000,nyt,Oil Prices Fall Sharply on News of Possible Ir...,https://www.nytimes.com/2026/05/24/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2555/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
21   iran     30
23   deal     22
96  trump     19
22  peace      8
28    oil      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
184,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...,127
187,2026-05-24-11-14-00 +0000,wsj,Trump Says a Deal for Talks With Iran to End W...,https://www.wsj.com/world/middle-east/trump-an...,90
172,2026-05-24-14-33-01 +0000,nypost,Trump vows Iran can never have a nuke — and US...,https://nypost.com/2026/05/24/us-news/trump-vo...,88
145,2026-05-24-18-04-00 +0000,wsj,Trump Says He Is in No Rush for an Iran Deal T...,https://www.wsj.com/world/middle-east/middle-e...,86
176,2026-05-24-13-08-59 +0000,cbc,Details emerge about potential Iran deal as Tr...,https://www.cbc.ca/news/world/details-emerge-u...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
184,127,2026-05-24-11-57-13 +0000,nypost,Trump says Iran peace deal is near ‘finalizati...,https://nypost.com/2026/05/24/us-news/how-us-i...
68,32,2026-05-25-02-32-08 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
107,31,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
125,25,2026-05-24-21-02-08 +0000,bbc,She was told to marry in a country which bans ...,https://www.bbc.com/news/articles/ce3pgn48wnqo...
94,25,2026-05-24-23-28-15 +0000,nypost,Hero Purple Heart vet whom Graham Platner said...,https://nypost.com/2026/05/24/us-news/purple-h...
131,25,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
54,24,2026-05-25-04-45-13 +0000,bbc,Large-scale Russian attack on Ukraine leaves f...,https://www.bbc.com/news/articles/clyp6831yp5o...
126,24,2026-05-24-20-57-43 +0000,nypost,Texas Sen. Cornyn insists he can overcome Trum...,https://nypost.com/2026/05/24/us-news/cornyn-i...
79,23,2026-05-25-00-45-59 +0000,nypost,Accused California DUI driver’s stunning six-w...,https://nypost.com/2026/05/24/us-news/accused-...
163,23,2026-05-24-16-00-00 +0000,wsj,The hiring of teens for summer jobs is expecte...,https://www.wsj.com/economy/teen-summer-jobs-f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)