## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-14-33-40 +0000,nypost,Heartbroken families break down in tears over ...,https://nypost.com/2026/07/22/us-news/heartbro...
1,2026-07-22-14-33-35 +0000,nypost,Ukraine targets Russia’s top online retailer w...,https://nypost.com/2026/07/22/world-news/ukrai...
2,2026-07-22-14-30-00 +0000,bbc,Money Box,https://www.bbc.co.uk/sounds/play/m002z7bf?at_...
3,2026-07-22-14-22-41 +0000,nypost,Catastrophic flooding slams West Virginia — pr...,https://nypost.com/2026/07/22/us-news/state-of...
4,2026-07-22-14-22-32 +0000,nyt,Coveted U.S. Nuclear Deal is a Coup for Saudi ...,https://www.nytimes.com/2026/07/22/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2626/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
38   trump     58
119   iran     33
179    new     21
84     war     19
148   will     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
17,2026-07-22-14-03-05 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...,177
281,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,151
38,2026-07-22-13-28-00 +0000,wsj,"Trump Says U.S. Will Bomb Iran’s Power Plants,...",https://www.wsj.com/world/middle-east/trump-sa...,134
145,2026-07-22-09-46-00 +0000,wsj,Trump Approves Saudi Nuclear Deal as Iran Miss...,https://www.wsj.com/world/trump-approves-saudi...,134
172,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
17,177,2026-07-22-14-03-05 +0000,nyt,Iran War Live Updates: Trump Threatens Retalia...,https://www.nytimes.com/live/2026/07/22/world/...
281,99,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
172,67,2026-07-22-08-00-00 +0000,cbc,Trump's new tariffs on Canada could face a cou...,https://www.cbc.ca/news/world/trump-tariffs-ca...
47,66,2026-07-22-13-00-00 +0000,wsj,Two Democratic lawmakers want to curb tax brea...,https://www.wsj.com/politics/policy/whats-in-t...
386,49,2026-07-21-16-30-00 +0000,missionlocal,After a family was killed at a West Portal bus...,https://missionlocal.org/2026/07/san-francisco...
89,47,2026-07-22-11-55-36 +0000,nyt,Expected U.S.-Saudi Nuclear Deal Fuels Israeli...,https://www.nytimes.com/2026/07/22/world/middl...
190,45,2026-07-22-05-37-43 +0000,bbc,Zelensky sacks Ukraine's top army commander af...,https://www.bbc.co.uk/news/articles/cyvl35z391...
371,43,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
78,40,2026-07-22-12-13-56 +0000,cbc,NYC Mayor Mamdani calls Israel's Netanyahu a '...,https://www.cbc.ca/news/world/nyc-mamdani-vide...
93,40,2026-07-22-11-41-08 +0000,bbc,What does an Andy Burnham-led government mean ...,https://www.bbc.co.uk/news/articles/cp9ezldrkk...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)