## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-21-54-49 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...
1,2026-06-01-21-54-01 +0000,nyt,Taiwan Criticizes China’s Expulsion of New Yor...,https://www.nytimes.com/2026/06/01/world/asia/...
2,2026-06-01-21-52-00 +0000,wsj,Opinion | The High Stakes in Colombia’s Presid...,https://www.wsj.com/opinion/colombia-election-...
3,2026-06-01-21-51-00 +0000,wsj,Hegseth Blocks Eight Navy Senior Officer Promo...,https://www.wsj.com/politics/national-security...
4,2026-06-01-21-50-52 +0000,bbc,Bowen: Trump needs this war to end but Iran is...,https://www.bbc.com/news/articles/cedp3lee059o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     28
32    iran     22
449     ai     15
6      new     14
30     war     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
258,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...,107
196,2026-06-01-14-00-11 +0000,nypost,Trump claims ‘I really don’t care’ if ‘very bo...,https://nypost.com/2026/06/01/world-news/iran-...,96
0,2026-06-01-21-54-49 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...,85
25,2026-06-01-21-28-00 +0000,nyt,Iran War Live Updates: Israel and Iran Step Ba...,https://www.nytimes.com/live/2026/06/01/world/...,76
245,2026-06-01-09-27-47 +0000,cbc,Trump says talks with Iran continuing at 'rapi...,https://www.cbc.ca/news/world/iran-u-s-war-kuw...,71

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
258,107,2026-06-01-07-22-27 +0000,nypost,"Trump urges Democrats, ‘unpatriotic Republican...",https://nypost.com/2026/06/01/us-news/trump-ur...
160,59,2026-06-01-16-34-49 +0000,latimes,"AI company Anthropic files to list shares, hea...",https://www.latimes.com/business/story/2026-06...
221,54,2026-06-01-11-02-00 +0000,wsj,"If Democrats want to win the Senate, they like...",https://www.wsj.com/politics/graham-platner-sc...
0,51,2026-06-01-21-54-49 +0000,nyt,Trump Says Israel and Hezbollah Will Hold Off ...,https://www.nytimes.com/2026/06/01/world/middl...
275,46,2026-06-01-02-00-00 +0000,wsj,California Democrats head to a primary electio...,https://www.wsj.com/politics/elections/how-cal...
85,43,2026-06-01-19-49-13 +0000,nypost,‘Entourage’ creator records blistering video b...,https://nypost.com/2026/06/01/us-news/entourag...
207,43,2026-06-01-12-50-09 +0000,nypost,Hundreds protest outside Kenya’s Ebola quarant...,https://nypost.com/2026/06/01/world-news/hundr...
255,32,2026-06-01-08-18-41 +0000,nypost,"Iran shoots down US drone, attacks Kuwait — as...",https://nypost.com/2026/06/01/world-news/us-la...
122,32,2026-06-01-18-21-01 +0000,nypost,Oil prices jump after US and Iran exchange str...,https://nypost.com/2026/06/01/business/oil-pri...
126,32,2026-06-01-18-05-02 +0000,nypost,Walmart worker claims female boss bombarded hi...,https://nypost.com/2026/06/01/business/walmart...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)