## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-31-15-50-41 +0000,bbc,Ukrainian evacuees reunite with family after y...,https://www.bbc.co.uk/news/articles/cqx2818elr...
1,2026-10-31-15-46-42 +0000,nyt,Susan Collins Is Always Keeping Score,https://www.nytimes.com/2026/10/31/us/politics...
2,2026-10-31-15-46-19 +0000,chitri,Kamala Harris urges a ‘too big to rig’ turnout...,https://www.chicagotribune.com/2026/10/31/kama...
3,2026-10-31-15-43-44 +0000,nyt,F.D.A. Warns of Tractor Wheels Snack Bar Linke...,https://www.nytimes.com/2026/10/31/well/family...
4,2026-10-31-15-39-09 +0000,nypost,Notorious Greenwich Village homeless man Tiger...,https://nypost.com/2026/10/31/us-news/notoriou...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2661/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
23        trump     21
123  california     17
229    election     13
19     midterms     12
120   halloween     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
275,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...,65
245,2026-10-30-20-25-06 +0000,nyt,Appeals Court Again Rejects Trump Effort to Im...,https://www.nytimes.com/2026/10/30/us/politics...,64
270,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...,61
225,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...,59
268,2026-10-30-19-16-28 +0000,latimes,9th Circuit again denies Trump administration ...,https://www.latimes.com/politics/story/2026-10...,55

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
275,65,2026-10-30-18-58-07 +0000,nypost,Latest poll shows California governor candidat...,https://nypost.com/2026/10/30/us-news/xavier-b...
270,61,2026-10-30-19-06-27 +0000,cbc,"North American stocks sink, Wall Street suffer...",https://www.cbc.ca/news/business/tech-stocks-m...
225,59,2026-10-30-21-01-17 +0000,nypost,Freed Russian prisoner Stephen Hubbard tells T...,https://nypost.com/2026/10/30/us-news/freed-ru...
56,47,2026-10-31-12-00-00 +0000,latimes,Your last-minute guide to the L.A. city attorn...,https://www.latimes.com/california/story/2026-...
288,44,2026-10-30-18-04-03 +0000,chitri,Prime Minister Mark Carney expects to conclude...,https://www.chicagotribune.com/2026/10/30/pm-c...
178,42,2026-10-30-22-51-07 +0000,nypost,Ilhan Omar was so confused by marriage to ‘bro...,https://nypost.com/2026/10/30/us-news/ilhan-om...
169,40,2026-10-30-23-14-08 +0000,nypost,Feds ‘surge’ law enforcement to Alaska after ‘...,https://nypost.com/2026/10/30/us-news/feds-sur...
190,39,2026-10-30-21-48-01 +0000,nyt,Binance Lost Over $6 Billion in Crypto Hack. H...,https://www.nytimes.com/2026/10/30/business/bi...
30,38,2026-10-31-14-00-00 +0000,wsj,"Polling data remains at issue after Brazil, Se...",https://www.wsj.com/politics/elections/predict...
9,38,2026-10-31-15-19-25 +0000,nypost,UK PM Andy Burnham says he is ‘open’ to formal...,https://nypost.com/2026/10/31/world-news/uk-pm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)