## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-16-02-42-38 +0000,nyt,Iran War Live Updates: Trump Pressures NATO Al...,https://www.nytimes.com/live/2026/03/15/world/...
1,2026-03-16-02-40-56 +0000,bbc,Oscars 2026: Winners list in full,https://www.bbc.com/news/articles/c33jkvmzl4ko...
2,2026-03-16-02-40-08 +0000,startribune,"Jessie Buckley wins best actress Oscar, Michae...",https://www.startribune.com/sinners-and-one-ba...
3,2026-03-16-02-40-00 +0000,wsj,White House Tries to Build Coalition on Iran t...,https://www.wsj.com/politics/national-security...
4,2026-03-16-02-39-01 +0000,bbc,How did Oscar winner Kpop Demon Hunters win he...,https://www.bbc.com/news/articles/c4g4n1dyepdo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     30
1       war     26
4     trump     21
577  israel     10
11      oil     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-16-02-42-38 +0000,nyt,Iran War Live Updates: Trump Pressures NATO Al...,https://www.nytimes.com/live/2026/03/15/world/...,106
110,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic advisor reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...,95
24,2026-03-16-01-19-41 +0000,wapo,Trump backs FCC chief’s threat to broadcasters...,https://www.washingtonpost.com/business/2026/0...,93
56,2026-03-15-23-14-40 +0000,bbc,'A new norm': BBC visits Doha market starting ...,https://www.bbc.com/news/videos/cp32gez414yo?a...,84
168,2026-03-15-10-00-00 +0000,latimes,Trump is searching for an endgame to the Iran war,https://www.latimes.com/politics/story/2026-03...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,106,2026-03-16-02-42-38 +0000,nyt,Iran War Live Updates: Trump Pressures NATO Al...,https://www.nytimes.com/live/2026/03/15/world/...
122,42,2026-03-15-17-06-25 +0000,nypost,Captain of Iranian women’s soccer team is late...,https://nypost.com/2026/03/15/world-news/capta...
83,42,2026-03-15-21-09-33 +0000,cbc,Israel says Michigan synagogue attacker was br...,https://www.cbc.ca/news/world/michigan-synagog...
18,39,2026-03-16-01-41-30 +0000,nypost,California air chief hints she will cave on pl...,https://nypost.com/2026/03/15/us-news/californ...
147,30,2026-03-15-14-12-56 +0000,nypost,Maine Dem Senate hopeful Graham Platner done a...,https://nypost.com/2026/03/15/us-news/maine-de...
56,28,2026-03-15-23-14-40 +0000,bbc,'A new norm': BBC visits Doha market starting ...,https://www.bbc.com/news/videos/cp32gez414yo?a...
11,27,2026-03-16-02-24-37 +0000,bbc,Kpop Demon Hunters wins Oscars for best origin...,https://www.bbc.com/news/articles/cvg823zkx0go...
13,24,2026-03-16-02-10-06 +0000,startribune,Trump says that he's asked 'about 7' countries...,https://www.startribune.com/trump-urges-us-all...
163,23,2026-03-15-10-38-22 +0000,bbc,Israeli forces kill Palestinian couple and two...,https://www.bbc.com/news/articles/cqxdndz75zvo...
26,21,2026-03-16-01-13-30 +0000,bbc,"One-off £2,000 grant gives care leavers head s...",https://www.bbc.com/news/articles/cx24z8rvw1go...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)