## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-16-51-36 +0000,nypost,Footage shows deadly plane crash at San Diego ...,https://nypost.com/2026/09/08/us-news/footage-...
1,2026-09-08-16-51-13 +0000,nypost,Heart-stopping video shows hero supermarket ma...,https://nypost.com/2026/09/08/world-news/heart...
2,2026-09-08-16-50-36 +0000,nyt,Paxton Aide Turned Whistle-Blower Appears in A...,https://www.nytimes.com/2026/09/08/us/politics...
3,2026-09-08-16-50-30 +0000,nyt,Trump Media Launches MAGA-Friendly Investment ...,https://www.nytimes.com/2026/09/08/business/tr...
4,2026-09-08-16-50-25 +0000,nyt,A Hacking Tool Built With A.I. Can Breach Phon...,https://www.nytimes.com/2026/09/08/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2547/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
33   trump     31
68     new     23
147    oil     15
119  trade     15
3    plane     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
259,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...,78
25,2026-09-08-16-28-58 +0000,nyt,"Bombardier, a Canadian Jet Maker, Is One Targe...",https://www.nytimes.com/2026/09/08/business/bo...,76
242,2026-09-08-06-56-41 +0000,nyt,"Canada Imposes New Tariffs on U.S. Goods, as T...",https://www.nytimes.com/2026/09/08/business/ca...,75
162,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...,74
68,2026-09-08-15-16-34 +0000,nypost,"Trump, Putin speak after US envoys visit Mosco...",https://nypost.com/2026/09/08/us-news/trump-pu...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
259,78,2026-09-08-04-01-00 +0000,cbc,Canada's new tariffs: Are small businesses 'ca...,https://www.cbc.ca/news/business/new-canada-ta...
162,74,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...
212,55,2026-09-08-09-10-00 +0000,wsj,Oil Nears $100 a Barrel as Fresh Attacks on Sa...,https://www.wsj.com/world/middle-east/oil-near...
56,53,2026-09-08-15-40-32 +0000,chitri,All 5 killed in Miami cargo jet crash were in ...,https://www.chicagotribune.com/2026/09/08/miam...
70,50,2026-09-08-15-14-14 +0000,nyt,UK Imposes Sanctions on Israeli Settlements in...,https://www.nytimes.com/2026/09/08/world/europ...
174,42,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
120,41,2026-09-08-13-35-28 +0000,bbc,Renoir paintings worth millions stolen in Fren...,https://www.bbc.co.uk/news/articles/c70drp0pyw...
135,38,2026-09-08-12-39-24 +0000,nypost,Lindsay Clancy’s ex-husband Patrick rips ‘real...,https://nypost.com/2026/09/08/us-news/lindsay-...
289,35,2026-09-07-21-59-12 +0000,nypost,Mainstream TV vague about airing first-ever GO...,https://nypost.com/2026/09/07/us-news/tv-netwo...
324,34,2026-09-07-18-35-45 +0000,nyt,Germany’s ‘Firewall’ Against the Far Right Is ...,https://www.nytimes.com/2026/09/07/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)