## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-01-08-51-02 +0000,nypost,Rubio orders visiting Iranian UN delegation to...,https://nypost.com/2026/10/01/world-news/rubio...
1,2026-10-01-08-51-00 +0000,wsj,U.A.E. Opens Investigation Into FlyDubai Attack,https://www.wsj.com/world/middle-east/u-a-e-op...
2,2026-10-01-08-51-00 +0000,wsj,Swiss Inflation Rises to Two-Year High on Ener...,https://www.wsj.com/economy/swiss-inflation-ri...
3,2026-10-01-08-47-00 +0000,wsj,AI Stock Rally Checked by Relentless Treasury ...,https://www.wsj.com/finance/ai-stock-rally-che...
4,2026-10-01-08-39-28 +0000,bbc,Who is the 'hero' Indian pilot who was stabbed...,https://www.bbc.co.uk/news/articles/cje3r3z7g0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2534/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
125       trump     39
21           ai     26
296  california     23
11     flydubai     18
33       israel     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
179,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...,178
399,2026-09-30-12-19-49 +0000,nypost,Israel-bound plane co-pilot behind suspected t...,https://nypost.com/2026/09/30/world-news/israe...,146
57,2026-10-01-03-49-33 +0000,latimes,"Gas prices, AI data centers and Trump's long s...",https://www.latimes.com/california/story/2026-...,122
335,2026-09-30-15-32-56 +0000,nypost,Pilot of flydubai plane who fought off ‘terror...,https://nypost.com/2026/09/30/world-news/pilot...,114
77,2026-10-01-02-02-55 +0000,nypost,Netanyahu credits heroic Israeli plumber on fl...,https://nypost.com/2026/09/30/world-news/netan...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
179,178,2026-09-30-21-35-00 +0000,wsj,An Israel-bound plane made an emergency landin...,https://www.wsj.com/politics/policy/cockpit-st...
57,122,2026-10-01-03-49-33 +0000,latimes,"Gas prices, AI data centers and Trump's long s...",https://www.latimes.com/california/story/2026-...
77,113,2026-10-01-02-02-55 +0000,nypost,Netanyahu credits heroic Israeli plumber on fl...,https://nypost.com/2026/09/30/world-news/netan...
111,74,2026-10-01-00-12-00 +0000,wsj,OpenAI co-founder and President Greg Brockman ...,https://www.wsj.com/tech/ai/openai-president-b...
81,66,2026-10-01-01-55-25 +0000,latimes,$7.5-billion mini-NIH plan goes to California ...,https://www.latimes.com/california/story/2026-...
7,65,2026-10-01-08-28-00 +0000,wsj,"Long-Dated Treasury Yields Hit 24-Year Highs, ...",https://www.wsj.com/finance/long-dated-treasur...
260,49,2026-09-30-19-14-41 +0000,nypost,CEO of ‘hot girl’ insurance startup Corgi thre...,https://nypost.com/2026/09/30/business/ceo-of-...
297,48,2026-09-30-17-48-00 +0000,wsj,Senate Republicans made a late push to show vo...,https://www.wsj.com/politics/policy/senate-rep...
17,43,2026-10-01-07-46-00 +0000,wsj,Oil Rises as Supply Concerns Persist Despite M...,https://www.wsj.com/finance/commodities-future...
181,43,2026-09-30-21-31-42 +0000,nyt,UK Believes Iran Played a Part in RAF Fairford...,https://www.nytimes.com/2026/09/30/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)