## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-10-02-48-56 +0000,nyt,“He described himself as a person who hates Ch...,https://www.nytimes.com/live/2026/09/09/us/rnc...
1,2026-09-10-02-48-00 +0000,wsj,Trump Administration Proposes Eliminating Race...,https://www.wsj.com/us-news/trump-administrati...
2,2026-09-10-02-48-00 +0000,wsj,The Trump administration is proposing eliminat...,https://www.wsj.com/us-news/trump-administrati...
3,2026-09-10-02-44-43 +0000,nyt,How Fighting Fires Became an All-of-Europe Pro...,https://www.nytimes.com/2026/09/09/world/europ...
4,2026-09-10-02-39-33 +0000,nyt,Fighting Wildfire Haze With an Airplane and Lo...,https://www.nytimes.com/2026/09/09/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2532/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
6         trump     63
73          new     27
147  convention     21
146     midterm     20
236        iran     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
16,2026-09-10-01-56-03 +0000,nypost,Trump will pledge to slash ‘out-of-control cre...,https://nypost.com/2026/09/09/us-news/trump-wi...,147
167,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...,140
388,2026-09-09-09-06-36 +0000,nyt,Will Trump’s Midterm Convention Help or Hurt R...,https://www.nytimes.com/2026/09/09/us/politics...,138
71,2026-09-09-23-28-23 +0000,nyt,Why Trump’s Republican Midterm ‘Convention’ Is...,https://www.nytimes.com/2026/09/09/us/politics...,133
173,2026-09-09-20-20-01 +0000,nypost,"Trump claims oil, gas prices will fall ‘right ...",https://nypost.com/2026/09/09/business/trump-c...,133

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
16,147,2026-09-10-01-56-03 +0000,nypost,Trump will pledge to slash ‘out-of-control cre...,https://nypost.com/2026/09/09/us-news/trump-wi...
320,99,2026-09-09-12-56-00 +0000,wsj,Democratic Rep. Chris Pappas and Republican fo...,https://www.wsj.com/politics/elections/new-ham...
18,83,2026-09-10-01-54-25 +0000,nyt,"“We gave you no tax on tips, no tax on overtim...",https://www.nytimes.com/live/2026/09/09/us/rnc...
30,68,2026-09-10-01-23-42 +0000,nyt,“We have more money being spent from outside c...,https://www.nytimes.com/live/2026/09/09/us/rnc...
160,68,2026-09-09-20-37-38 +0000,missionlocal,California’s first AI safety law didn’t cover ...,https://missionlocal.org/2026/09/california-ai...
2,58,2026-09-10-02-48-00 +0000,wsj,The Trump administration is proposing eliminat...,https://www.wsj.com/us-news/trump-administrati...
323,56,2026-09-09-12-20-40 +0000,bbc,Petrol prices rise by 5p over a week as Iran w...,https://www.bbc.co.uk/news/articles/cj4jwlx77l...
41,54,2026-09-10-00-47-04 +0000,chitri,A pilot of the Amazon cargo plane that careene...,https://www.chicagotribune.com/2026/09/09/amaz...
240,54,2026-09-09-17-27-00 +0000,wsj,Huawei Technologies is finally going to trial ...,https://www.wsj.com/politics/national-security...
167,50,2026-09-09-20-27-00 +0000,wsj,"Steve Witkoff, Trump’s Middle East envoy, repo...",https://www.wsj.com/politics/policy/steve-witk...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)