## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-24-14-55-58 +0000,nypost,Holdout Lindsay Clancy juror’s attorney slams ...,https://nypost.com/2026/09/24/us-news/lindsay-...
1,2026-09-24-14-55-34 +0000,bbc,White House 'repeatedly violated' court order ...,https://www.bbc.co.uk/news/articles/cqe8ek7608...
2,2026-09-24-14-53-00 +0000,wsj,Trump Kicks Off White House Summit With China’...,https://www.wsj.com/world/china/trump-kicks-of...
3,2026-09-24-14-52-53 +0000,nyt,U.N. Live Updates: Abbas Criticizes Israeli At...,https://www.nytimes.com/live/2026/09/24/world/...
4,2026-09-24-14-52-45 +0000,nypost,Suspect in custody after stabbing at Polish ab...,https://nypost.com/2026/09/24/world-news/suspe...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2511/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
25   trump     80
320    new     30
30      xi     25
481     ai     21
16   house     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
52,2026-09-24-13-03-42 +0000,latimes,"CNN, MS NOW and Politico still shut out of Whi...",https://www.latimes.com/entertainment-arts/bus...,197
18,2026-09-24-14-27-00 +0000,wsj,A federal judge ordered President Trump to res...,https://www.wsj.com/politics/policy/judge-orde...,190
2,2026-09-24-14-53-00 +0000,wsj,Trump Kicks Off White House Summit With China’...,https://www.wsj.com/world/china/trump-kicks-of...,189
47,2026-09-24-13-16-35 +0000,wapo,"CNN, Politico, MS NOW journalists barred from ...",https://www.washingtonpost.com/business/2026/0...,184
101,2026-09-24-10-59-00 +0000,wsj,As President Trump and China’s Xi Jinping prep...,https://www.wsj.com/politics/policy/as-trump-a...,181

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
52,197,2026-09-24-13-03-42 +0000,latimes,"CNN, MS NOW and Politico still shut out of Whi...",https://www.latimes.com/entertainment-arts/bus...
228,107,2026-09-24-00-43-00 +0000,wsj,The last time Venezuelan leader Delcy Rodrígue...,https://www.wsj.com/world/americas/u-n-visit-s...
279,95,2026-09-23-22-01-17 +0000,bbc,Trump and Xi come face-to-face as US and China...,https://www.bbc.co.uk/news/articles/c6gqdgg8w5...
424,75,2026-09-23-17-04-19 +0000,nypost,Trump’s Board of Peace announces $2.45B first-...,https://nypost.com/2026/09/23/us-news/trumps-b...
441,66,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
83,53,2026-09-24-11-22-00 +0000,wsj,The Morning Risk Report: The Group Chat Where ...,https://www.wsj.com/risk-compliance-journal/th...
324,52,2026-09-23-20-45-00 +0000,wsj,Canada’s Carney Open to U.S. Trade Deal but Wo...,https://www.wsj.com/world/europe/canadas-carne...
133,47,2026-09-24-10-00-00 +0000,nypost,US military spending $500M on ‘war-ready’ lase...,https://nypost.com/2026/09/24/us-news/us-milit...
387,45,2026-09-23-18-24-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
225,45,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)