## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-11-17-55-02 +0000,nyt,Iran War Live Updates: Trump Retracts Latest T...,https://www.nytimes.com/live/2026/06/11/world/...
1,2026-06-11-17-55-00 +0000,wsj,SpaceX IPO Draws at Least $5 Billion Order Fro...,https://www.wsj.com/business/spacex-ipo-draws-...
2,2026-06-11-17-54-33 +0000,nyt,Scientist Charged With Conspiring to Smuggle M...,https://www.nytimes.com/2026/06/08/science/dut...
3,2026-06-11-17-51-29 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/11/world/...
4,2026-06-11-17-51-00 +0000,wsj,Oil Futures Fall As Trump Calls Off Planned Ir...,https://www.wsj.com/finance/commodities-future...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2487/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
4    trump     38
0     iran     33
63   world     26
164    new     25
161    cup     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
334,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...,143
12,2026-06-11-17-41-53 +0000,nypost,"Trump calls off Iran strikes, tells The Post t...",https://nypost.com/2026/06/11/us-news/trump-ca...,130
294,2026-06-10-21-48-11 +0000,nyt,Trump Shrugs Off High Prices Amid Iran War and...,https://www.nytimes.com/2026/06/10/business/ec...,129
27,2026-06-11-17-08-55 +0000,nyt,Oil Prices Fluctuate as Trump Issues New Threa...,https://www.nytimes.com/2026/06/10/business/oi...,127
349,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...,125

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
334,143,2026-06-10-20-07-00 +0000,nyt,Oil Rises on Trump’s Iran Threats and New Stri...,https://www.nytimes.com/2026/06/10/business/oi...
349,92,2026-06-10-19-31-00 +0000,wsj,Consumer prices continued to rise quickly in M...,https://www.wsj.com/economy/cpi-inflation-repo...
60,79,2026-06-11-16-24-55 +0000,nypost,Problem-plagued NJ Transit will use 600-person...,https://nypost.com/2026/06/11/us-news/nj-trans...
313,54,2026-06-10-21-09-00 +0000,wsj,Bill Gates told Congress that Jeffrey Epstein ...,https://www.wsj.com/politics/policy/bill-gates...
171,54,2026-06-11-11-19-51 +0000,nypost,Canada considering social media ban for kids u...,https://nypost.com/2026/06/11/world-news/canad...
19,47,2026-06-11-17-34-06 +0000,nypost,Minnesota assassin Vance Boelter admits murder...,https://nypost.com/2026/06/11/us-news/minnesot...
117,46,2026-06-11-14-13-32 +0000,bbc,SpaceX's stock market blast-off could be Musk'...,https://www.bbc.com/news/articles/cy8d9e4lzv1o...
36,37,2026-06-11-16-58-00 +0000,wsj,The House rejected the Trump-backed FISA spyin...,https://www.wsj.com/politics/policy/showdown-b...
78,34,2026-06-11-15-46-37 +0000,nypost,Funeral home stages wacky Knicks watch party —...,https://nypost.com/2026/06/11/lifestyle/inside...
292,34,2026-06-10-21-48-54 +0000,nypost,Trump warns Iran to make a deal or ‘we’ll bomb...,https://nypost.com/2026/06/10/us-news/us-launc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)