## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-16-02-44-43 +0000,nyt,Iran War Live Updates: U.S. and Iran Sign Prel...,https://www.nytimes.com/live/2026/06/15/world/...
1,2026-06-16-02-43-00 +0000,startribune,Minnesota shut out at James Beard Awards,https://www.startribune.com/minnesota-shut-out...
2,2026-06-16-02-35-50 +0000,latimes,Wild deer captured and kept in a dog crate for...,https://www.latimes.com/california/story/2026-...
3,2026-06-16-02-27-00 +0000,wsj,China Data Shows Unbalanced Economic Growth,https://www.wsj.com/economy/china-data-shows-u...
4,2026-06-16-02-21-11 +0000,latimes,Californian is infected with rare tick-borne i...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2577/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     61
6      deal     52
127   trump     52
152   world     19
541  hormuz     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
251,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...,247
173,2026-06-15-18-27-23 +0000,bbc,US and Iran agree deal to end war as Trump say...,https://www.bbc.com/news/articles/c39yvvy273ko...,228
184,2026-06-15-17-34-00 +0000,wsj,Trump Says Strait of Hormuz Will Be Fully Open...,https://www.wsj.com/world/middle-east/question...,227
17,2026-06-16-01-00-00 +0000,wsj,"In one weekend, President Trump veered from th...",https://www.wsj.com/world/middle-east/trump-ir...,222
237,2026-06-15-14-41-16 +0000,nypost,Why Strait of Hormuz still hasn’t reopened to ...,https://nypost.com/2026/06/15/world-news/why-s...,209

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
251,247,2026-06-15-13-53-15 +0000,nypost,Oil prices sink to lowest levels in months aft...,https://nypost.com/2026/06/15/business/oil-pri...
22,71,2026-06-16-00-57-00 +0000,wsj,California Gov. Gavin Newsom said that the Jus...,https://www.wsj.com/politics/policy/gavin-news...
10,57,2026-06-16-01-43-52 +0000,nypost,English teen gives hilarious live-TV response ...,https://nypost.com/2026/06/15/world-news/engli...
45,54,2026-06-15-23-29-08 +0000,cbc,Ghana takes Thomas Partey's World Cup entry fi...,https://www.cbc.ca/sports/soccer/worldcup/thom...
17,53,2026-06-16-01-00-00 +0000,wsj,"In one weekend, President Trump veered from th...",https://www.wsj.com/world/middle-east/trump-ir...
247,47,2026-06-15-14-17-00 +0000,wsj,"A rowdy, controversial evening of mixed-martia...",https://www.wsj.com/arts-culture/books/trump-u...
212,38,2026-06-15-16-22-54 +0000,startribune,Gas prices are dropping in Minnesota. It’s ‘ha...,https://www.startribune.com/gas-prices-are-dro...
85,38,2026-06-15-21-35-55 +0000,nypost,"Boy, 2, found dead in NYC home, hours before g...",https://nypost.com/2026/06/15/us-news/boy-2-fo...
27,37,2026-06-16-00-24-40 +0000,nypost,"Cancer survivor, music teacher and grandpa of ...",https://nypost.com/2026/06/15/us-news/several-...
118,34,2026-06-15-20-42-05 +0000,nypost,SpaceX shares jump 20% in first full day of tr...,https://nypost.com/2026/06/15/business/spacex-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)