## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-22-55-32 +0000,nyt,"Jeffrey Archer, Novelist Whose Real Life Rival...",https://www.nytimes.com/2026/10/05/books/jeffr...
1,2026-10-05-22-51-19 +0000,bbc,"I won't accept exclusion, says Polanski after ...",https://www.bbc.co.uk/news/articles/cjy56yxxwy...
2,2026-10-05-22-46-01 +0000,nyt,Chicago Woman Shot by Border Patrol Agent Sues...,https://www.nytimes.com/2026/10/05/us/marimar-...
3,2026-10-05-22-45-41 +0000,chitri,A lawsuit accuses Starbucks of mislabeling 8 ‘...,https://www.chicagotribune.com/2026/10/05/star...
4,2026-10-05-22-42-31 +0000,nyt,Biden-Era Memo on Covid and Schools Set Off Di...,https://www.nytimes.com/2026/10/05/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
260       new     28
55   election     21
203     house     20
51      trump     19
350     court     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
44,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,169
128,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,103
298,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,92
156,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,90
291,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
44,169,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
156,90,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
376,73,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...
266,68,2026-10-05-13-10-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
279,57,2026-10-05-12-17-25 +0000,wapo,"Spain’s Pedro Sánchez, main critic of Trump in...",https://www.washingtonpost.com/world/2026/10/0...
253,46,2026-10-05-14-10-00 +0000,nypost,White House rips ‘scumbag’ ex-special counsel ...,https://nypost.com/2026/10/05/us-news/white-ho...
40,39,2026-10-05-21-39-16 +0000,nypost,Meet Meta’s billionaire AI guru –a 29-year-old...,https://nypost.com/2026/10/05/business/meet-me...
304,38,2026-10-05-10-29-00 +0000,wsj,FBI Arrests Alleged Chinese Agent Accused of S...,https://www.wsj.com/world/china/fbi-arrests-al...
77,37,2026-10-05-20-41-47 +0000,nypost,‘American Idol’ alum Caleb Flynn sobs as he ma...,https://nypost.com/2026/10/05/us-news/american...
162,37,2026-10-05-17-36-21 +0000,nypost,Gulf oil exports top pre-war levels as Saudi-b...,https://nypost.com/2026/10/05/world-news/gulf-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)