## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-06-23-11-29 +0000,startribune,Royce Lewis returns to Twins after minor leagu...,https://www.startribune.com/royce-lewis-return...
1,2026-06-06-23-08-19 +0000,nyt,An Uncertain Win for Immigrants Seeking to Sta...,https://www.nytimes.com/2026/06/06/us/an-uncer...
2,2026-06-06-23-07-48 +0000,bbc,Multiple people shot near festival in Ohio wit...,https://www.bbc.com/news/articles/c4gyqzkgwn2o...
3,2026-06-06-23-03-31 +0000,nypost,Woman killed by FDNY truck that was rushing to...,https://nypost.com/2026/06/06/us-news/woman-ki...
4,2026-06-06-23-03-17 +0000,nypost,Inside the harrowing final moments of bank rob...,https://nypost.com/2026/06/06/us-news/inside-t...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2568/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
44        trump     17
59        world     14
60          cup     11
72         iran     11
195  california     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
97,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...,61
189,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...,61
171,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...,53
51,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,50
8,2026-06-06-22-38-36 +0000,bbc,Iran says staff blocked from entering US after...,https://www.bbc.com/news/articles/cy8286nqz87o...,46

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
97,61,2026-06-06-12-00-00 +0000,wsj,"Trump’s approval numbers have tumbled, hurt by...",https://www.wsj.com/politics/policy/as-trumps-...
171,53,2026-06-06-01-08-00 +0000,wsj,Former HHS Secretary Xavier Becerra advanced t...,https://www.wsj.com/politics/elections/democra...
189,44,2026-06-05-23-17-25 +0000,nypost,US shoots down Iranian drones launched toward ...,https://nypost.com/2026/06/05/us-news/us-shoot...
156,41,2026-06-06-03-01-39 +0000,latimes,SoFi Stadium workers vote to authorize strike ...,https://www.latimes.com/sports/soccer/story/20...
91,34,2026-06-06-12-27-17 +0000,cbc,"Palestinian baby killed, parents hurt in Israe...",https://www.cbc.ca/news/world/israeli-palestin...
126,30,2026-06-06-09-14-00 +0000,wsj,Mass Ukrainian Drone Strikes Target Russian Mi...,https://www.wsj.com/world/russia/mass-ukrainia...
164,28,2026-06-06-01-57-00 +0000,wsj,Steve Hilton mounts unlikely California govern...,https://www.wsj.com/politics/elections/the-bri...
85,27,2026-06-06-13-31-21 +0000,nypost,Pope Leo urges country to stop ‘fanning flames...,https://nypost.com/2026/06/06/world-news/pope-...
35,25,2026-06-06-19-59-13 +0000,nypost,‘Complete hypocrite:’ Mamdani-backed Congress ...,https://nypost.com/2026/06/06/us-news/complete...
40,25,2026-06-06-19-41-32 +0000,nypost,Victoria Gotti told Carmine Gotti Agnello’s gi...,https://nypost.com/2026/06/06/us-news/victoria...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)