## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-07-20-55-26 +0000,cbc,Liberals look to amend 31 laws at once in atte...,https://www.cbc.ca/news/politics/liberals-red-...
1,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
2,2026-10-07-20-54-00 +0000,startribune,Federal prosecutors accuse man of plotting att...,https://www.startribune.com/federal-terrorism-...
3,2026-10-07-20-53-49 +0000,nypost,Cyclist killed in Central Park dog mishap was ...,https://nypost.com/2026/10/07/us-news/cyclist-...
4,2026-10-07-20-53-00 +0000,wsj,U.S. Stocks Fall as Treasury Yields Test Multi...,https://www.wsj.com/finance/investing/u-s-stoc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2389/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
17     trump     45
74       new     18
110   plague     15
305  christa     15
306     pike     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
133,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...,127
1,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...,116
11,2026-10-07-20-50-19 +0000,nypost,Trump tamps down speculation Russia plague lab...,https://nypost.com/2026/10/07/us-news/trump-ta...,109
112,2026-10-07-18-27-40 +0000,bbc,Trump to speak to Putin about plague lab worke...,https://www.bbc.co.uk/news/articles/cqgm0vrl3x...,103
71,2026-10-07-19-42-35 +0000,cbc,'Canada is not our enemy': Michigan Republican...,https://www.cbc.ca/news/world/michigan-republi...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
133,127,2026-10-07-17-47-48 +0000,nypost,Trump celebrates all kids under 18 having a Tr...,https://nypost.com/2026/10/07/us-news/trump-ce...
392,77,2026-10-06-23-04-37 +0000,nypost,Russia accused of covering up plague outbreak ...,https://nypost.com/2026/10/06/world-news/russi...
1,71,2026-10-07-20-55-00 +0000,wsj,Michigan Senate Republican nominee Mike Rogers...,https://www.wsj.com/politics/elections/michiga...
433,65,2026-10-06-21-29-32 +0000,missionlocal,‘We need a jingle’: Will voters know the ‘Yes-...,https://missionlocal.org/2026/10/california-bi...
428,63,2026-10-06-21-32-09 +0000,cbc,Tennessee inmate Christa Pike awake and speaki...,https://www.cbc.ca/news/world/christa-pike-spe...
282,53,2026-10-07-10-00-00 +0000,nypost,‘Dumbest thing Democrats could do’ if they win...,https://nypost.com/2026/10/07/us-news/dumbest-...
119,53,2026-10-07-18-20-00 +0000,wsj,"What to know about Trump Accounts, the new sav...",https://www.wsj.com/personal-finance/trump-acc...
365,52,2026-10-07-01-57-14 +0000,nypost,"Troy Jackson trashes voter ID policy, relies o...",https://nypost.com/2026/10/06/us-news/troy-jac...
349,42,2026-10-07-04-32-54 +0000,latimes,Santa Monica man who was charged with kidnappi...,https://www.latimes.com/california/story/2026-...
29,42,2026-10-07-20-29-00 +0000,wsj,"In a speech framed by ancient Greek ruins, Sec...",https://www.wsj.com/politics/policy/rubio-turn...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)