## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-06-07-16-18 +0000,bbc,Charity 'feels the pinch' of higher energy prices,https://www.bbc.com/news/articles/c937909n152o...
1,2026-04-06-07-00-00 +0000,wsj,Comex Gold Futures Set to Resume Downside Move...,https://www.wsj.com/finance/commodities-future...
2,2026-04-06-06-35-54 +0000,nyt,Oil Rises Slightly After Trump’s Latest Threat...,https://www.nytimes.com/2026/04/06/business/oi...
3,2026-04-06-06-33-20 +0000,nypost,"US, Israeli airstrikes batter Iran as Trump’s ...",https://nypost.com/2026/04/06/world-news/us-is...
4,2026-04-06-06-15-20 +0000,bbc,'Positives' for tourism despite Iran war uncer...,https://www.bbc.com/news/articles/cly7ngpgz5xo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2487/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
21     iran     32
18    trump     29
42   easter     14
31      war     13
299  rescue     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
77,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...,116
143,2026-04-05-14-31-37 +0000,nypost,Trump heralds ‘Easter Miracle’ after daring re...,https://nypost.com/2026/04/05/us-news/trump-he...,109
108,2026-04-05-18-12-38 +0000,nypost,Trump gives Iran Tuesday evening deadline to o...,https://nypost.com/2026/04/05/us-news/trump-gi...,103
114,2026-04-05-17-19-53 +0000,nypost,Defiant Iran vows to escalate war after Trump’...,https://nypost.com/2026/04/05/world-news/defia...,102
151,2026-04-05-12-27-29 +0000,nypost,"Trump tells Iran ‘open the F—in’ Strait, you c...",https://nypost.com/2026/04/05/us-news/trump-ma...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
77,116,2026-04-05-21-20-00 +0000,wsj,President Trump threatened to destroy all of I...,https://www.wsj.com/world/trump-warns-in-journ...
125,48,2026-04-05-16-41-25 +0000,wapo,"On Easter, Pope Leo delivers commanding messag...",https://www.washingtonpost.com/world/2026/04/0...
148,45,2026-04-05-12-50-51 +0000,nypost,"How US used SEAL Team 6, a CIA ruse and death ...",https://nypost.com/2026/04/05/world-news/us-re...
169,38,2026-04-05-09-30-00 +0000,wsj,Central banks live in fear of their last mista...,https://www.wsj.com/economy/central-banking/pa...
26,31,2026-04-06-01-49-31 +0000,nypost,California’s fuel crisis hits terrifying new h...,https://nypost.com/2026/04/05/us-news/sky-high...
56,30,2026-04-05-22-34-00 +0000,wsj,"For nearly two days, injured and alone, a U.S....",https://www.wsj.com/politics/national-security...
55,26,2026-04-05-22-35-54 +0000,nyt,U.S. Rescues Missing Air Force Officer Whose F...,https://www.nytimes.com/2026/04/04/us/politics...
136,24,2026-04-05-15-33-59 +0000,nypost,Late-night shooting near the White House puts ...,https://nypost.com/2026/04/05/us-news/late-nig...
90,23,2026-04-05-20-18-50 +0000,nypost,GOP Senator John Kennedy claims modern Dems wo...,https://nypost.com/2026/04/05/us-news/gop-sena...
16,22,2026-04-06-03-39-38 +0000,nypost,"Easter egg hunt tragedy leaves young mother, h...",https://nypost.com/2026/04/05/world-news/easte...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)