## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-11-16-07-08 +0000,bbc,Anne Hathaway pokes fun at 'fake baby bump' th...,https://www.bbc.co.uk/news/articles/ce8ljew9rn...
1,2026-08-11-16-06-00 +0000,wsj,White House Asks Justice Department to Conside...,https://www.wsj.com/us-news/law/white-house-as...
2,2026-08-11-16-05-00 +0000,cbc,Rights groups sue Trump administration over IC...,https://www.cbc.ca/news/world/trump-icc-sancti...
3,2026-08-11-16-04-00 +0000,wsj,Nasdaq to Acquire LeveL Markets,https://www.wsj.com/finance/nasdaq-to-acquire-...
4,2026-08-11-16-03-07 +0000,nyt,3 Presidents Before Trump Who Obscured Their R...,https://www.nytimes.com/2026/08/11/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2736/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
21      trump     51
14        new     30
187  colombia     15
89         ai     14
139      iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
219,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,133
365,2026-08-10-17-53-59 +0000,chitri,President Donald Trump officials propose new s...,https://www.chicagotribune.com/2026/08/10/trum...,110
17,2026-08-11-15-45-01 +0000,startribune,Trump used elaborate ruse to fly out of Turkey...,https://www.startribune.com/trump-used-elabora...,107
222,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,105
31,2026-08-11-15-14-04 +0000,nypost,Video appears to show catering truck secretly ...,https://nypost.com/2026/08/11/us-news/video-ap...,103

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
219,133,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
87,94,2026-08-11-13-22-57 +0000,nypost,Middle school teacher first to be arrested und...,https://nypost.com/2026/08/11/us-news/middle-s...
238,69,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
123,68,2026-08-11-11-32-01 +0000,cbc,Syria's former president Bashar al-Assad sente...,https://www.cbc.ca/news/world/syria-assads-naj...
65,54,2026-08-11-14-08-35 +0000,nypost,NYC boat survivor held baby moments before she...,https://nypost.com/2026/08/11/us-news/nyc-boat...
279,49,2026-08-10-21-47-00 +0000,wsj,"Nvidia, Wall Street Firms Strike AI Financing ...",https://www.wsj.com/business/deals/nvidia-wall...
384,45,2026-08-10-16-37-03 +0000,nypost,Nearly 100-year-old church crumbles as deadly ...,https://nypost.com/2026/08/10/world-news/nearl...
55,43,2026-08-11-14-27-00 +0000,wsj,Food companies largely dodged a regulatory ham...,https://www.wsj.com/politics/policy/food-compa...
313,43,2026-08-10-20-34-56 +0000,nypost,Dem bigwigs rush to embrace El-Sayed in critic...,https://nypost.com/2026/08/10/us-news/dem-bigw...
70,42,2026-08-11-14-00-00 +0000,wsj,"Home sales fell in July, getting the summer of...",https://www.wsj.com/economy/housing/july-home-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)