## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-18-16-52-00 +0000,wsj,Oil Retreat Slows on Saudi Supply Concerns,https://www.wsj.com/business/energy-oil/oil-pr...
1,2026-09-18-16-49-40 +0000,chitri,Trump refers to Black man from racially offens...,https://www.chicagotribune.com/2026/09/18/trum...
2,2026-09-18-16-49-22 +0000,nypost,NYPD cracks 30-year-old rape case after stealt...,https://nypost.com/2026/09/18/us-news/nypd-svu...
3,2026-09-18-16-47-32 +0000,cbc,Supreme Court explains why it invalidated Libe...,https://www.cbc.ca/news/politics/terrebonne-su...
4,2026-09-18-16-45-00 +0000,wsj,Hundreds of Thousands Rally in Iran as War and...,https://www.wsj.com/world/middle-east/hundreds...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
6    trump     34
46     new     25
386     ai     21
95   house     19
37    iran     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
269,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...,131
369,2026-09-17-19-02-00 +0000,wsj,The New Offensive Raising Oil Prices and Compl...,https://www.wsj.com/world/middle-east/the-new-...,105
386,2026-09-17-17-47-52 +0000,nypost,White House issues explosive response to UN-ba...,https://nypost.com/2026/09/17/us-news/white-ho...,101
220,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...,98
279,2026-09-17-23-20-15 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-pu...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
269,131,2026-09-18-00-00-00 +0000,wsj,Trump responded mildly to this week’s Fed inte...,https://www.wsj.com/politics/policy/how-warsh-...
311,79,2026-09-17-21-41-19 +0000,bbc,US to allow Iran delegation to attend UN meeti...,https://www.bbc.co.uk/news/articles/c6n8m72r13...
387,74,2026-09-17-17-46-14 +0000,nypost,"Chinese AI labs must accelerate development, s...",https://nypost.com/2026/09/17/business/chinese...
146,70,2026-09-18-11-49-46 +0000,bbc,Lindsay Clancy holdout juror says he had no do...,https://www.bbc.co.uk/news/articles/c54g7jdmw0...
317,53,2026-09-17-21-36-00 +0000,wsj,"Republican Rep. Maria Elvira Salazar, who repr...",https://www.wsj.com/politics/elections/republi...
220,53,2026-09-18-08-00-00 +0000,cbc,Canada's top general is up for a senior NATO p...,https://www.cbc.ca/news/politics/nato-canada-u...
240,52,2026-09-18-04-16-27 +0000,latimes,SoCal family of 3 found dead in their home. Fa...,https://www.latimes.com/california/story/2026-...
36,45,2026-09-18-15-59-00 +0000,wsj,The balance of power in the Senate is on the l...,https://www.wsj.com/politics/elections/senate-...
26,39,2026-09-18-16-14-16 +0000,nypost,Haunting video catches evil glare from driver ...,https://nypost.com/2026/09/18/us-news/video-sh...
279,38,2026-09-17-23-20-15 +0000,nyt,Trump Wants Putin to End the War. He May Offer...,https://www.nytimes.com/2026/09/17/us/trump-pu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)