## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-14-10-09 +0000,nypost,North Carolina beauty queen controversially st...,https://nypost.com/2026/08/10/us-news/stripped...
1,2026-08-10-14-08-00 +0000,wsj,Oil Futures Rise On Iranian Demands for Hormuz...,https://www.wsj.com/finance/commodities-future...
2,2026-08-10-14-05-00 +0000,wsj,U.S. Natural Gas Futures Start Week With Rebound,https://www.wsj.com/articles/european-ttf-gas-...
3,2026-08-10-14-04-07 +0000,nyt,Minnesota’s Democratic Senate Primary Pits Ang...,https://www.nytimes.com/2026/08/10/us/politics...
4,2026-08-10-14-02-32 +0000,nyt,"How Small, Independent Newspapers Are Still Fi...",https://www.nytimes.com/2026/08/10/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2372/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
364   trump     22
115    iran     13
27   senate     13
508   china     10
205     new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
191,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...,80
192,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...,80
60,2026-08-10-11-10-00 +0000,wsj,The U.S. and Israeli militaries have pounded I...,https://www.wsj.com/politics/elections/why-is-...,69
51,2026-08-10-11-34-13 +0000,nyt,Iran Insists Strait of Hormuz Will Stay Closed...,https://www.nytimes.com/2026/08/10/world/middl...,67
92,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
191,80,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...
60,69,2026-08-10-11-10-00 +0000,wsj,The U.S. and Israeli militaries have pounded I...,https://www.wsj.com/politics/elections/why-is-...
214,62,2026-08-09-19-53-25 +0000,nypost,Gavin Newsom confirms he’ll sit down with radi...,https://nypost.com/2026/08/09/us-news/gavin-ne...
92,55,2026-08-10-10-02-00 +0000,wsj,The bruising race to rent in San Francisco goe...,https://www.wsj.com/politics/policy/behind-pri...
95,30,2026-08-10-10-00-00 +0000,wsj,Democrats in Minnesota are lashing out at fell...,https://www.wsj.com/politics/elections/democra...
40,29,2026-08-10-12-11-18 +0000,nypost,Mom allegedly made blood-chilling threat to ex...,https://nypost.com/2026/08/10/us-news/mom-alle...
219,29,2026-08-09-19-14-55 +0000,nypost,AOC pushes voters to assess what Francesca Hon...,https://nypost.com/2026/08/09/us-news/aoc-push...
19,28,2026-08-10-13-16-06 +0000,nyt,Ukraine Drone Attack on Industrial City in Rus...,https://www.nytimes.com/2026/08/10/world/europ...
193,28,2026-08-09-22-07-40 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...
64,27,2026-08-10-11-02-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)