## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-05-16-24-00 +0000,wsj,Financial Services Roundup: Market Talk,https://www.wsj.com/business/financial-service...
1,2026-08-05-16-22-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/business/tech-media-teleco...
2,2026-08-05-16-20-14 +0000,bbc,Left-wing political outsider wins Democratic S...,https://www.bbc.co.uk/news/articles/ckgdkpz07k...
3,2026-08-05-16-16-31 +0000,nypost,Gavin Newsom skewered by Los Angeles liberals ...,https://nypost.com/2026/08/05/us-news/pro-tran...
4,2026-08-05-16-13-05 +0000,nypost,Moment California cop shoots woman at traffic ...,https://nypost.com/2026/08/05/us-news/moment-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2323/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
16     michigan     38
325       trump     33
15      primary     33
13   democratic     26
14       senate     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-08-05-16-12-00 +0000,wsj,Progressive Abdul El-Sayed wins Michigan Democ...,https://www.wsj.com/politics/elections/michiga...,232
55,2026-08-05-15-03-22 +0000,cbc,Abdul El-Sayed wins Michigan's Democratic Sena...,https://www.cbc.ca/news/world/abdul-el-sayed-h...,200
96,2026-08-05-13-55-22 +0000,nyt,Abdul El-Sayed Wins Democratic Senate Primary ...,https://www.nytimes.com/2026/08/05/us/politics...,191
94,2026-08-05-13-57-05 +0000,nypost,Far-left Michigan Dem Abdul El-Sayed beats Rep...,https://nypost.com/2026/08/05/us-news/michigan...,188
45,2026-08-05-15-20-03 +0000,startribune,Abdul El-Sayed wins Michigan Senate primary in...,https://www.startribune.com/el-sayed-campaign-...,178

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,232,2026-08-05-16-12-00 +0000,wsj,Progressive Abdul El-Sayed wins Michigan Democ...,https://www.wsj.com/politics/elections/michiga...
404,107,2026-08-04-18-28-00 +0000,wsj,"Sen. Angela Alsobrooks (D., Md.) has been a to...",https://www.wsj.com/politics/policy/how-trumps...
79,94,2026-08-05-14-15-00 +0000,wsj,Rep. Chuck Edwards said he wouldn’t seek re-el...,https://www.wsj.com/politics/elections/embattl...
219,88,2026-08-05-07-53-56 +0000,wsj,"Stock Market Today: Dow Extends Rally, SpaceX ...",https://www.wsj.com/livecoverage/stock-market-...
54,78,2026-08-05-15-03-44 +0000,nypost,"Disney earnings boosted by ‘Toy Story 5’, them...",https://nypost.com/2026/08/05/business/disney-...
241,67,2026-08-05-03-44-30 +0000,bbc,Trump says Iran will be 'hit very hard' if Hor...,https://www.bbc.co.uk/news/articles/cpw9v0gnzx...
362,51,2026-08-04-20-42-12 +0000,nypost,SpaceX reports 92% revenue surge despite Wall ...,https://nypost.com/2026/08/04/business/spacex-...
285,50,2026-08-05-00-15-00 +0000,wsj,The Trump administration is revoking the visa ...,https://www.wsj.com/politics/policy/u-s-revoke...
38,47,2026-08-05-15-30-41 +0000,nyt,Record-Breaking Heat Wave in South Korea Leads...,https://www.nytimes.com/2026/08/05/world/asia/...
65,46,2026-08-05-14-43-00 +0000,wsj,Missouri residents overwhelmingly defeated a b...,https://www.wsj.com/politics/policy/missouri-v...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)