## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-11-40-26 +0000,wapo,Slain mosque security guard had warned teacher...,https://www.washingtonpost.com/nation/2026/05/...
1,2026-05-19-11-37-52 +0000,nyt,Middle East on Edge After Trump Says He Delaye...,https://www.nytimes.com/2026/05/19/world/middl...
2,2026-05-19-11-37-51 +0000,bbc,Anti-government demonstrators and police clash...,https://www.bbc.com/news/videos/cx21349w77go?a...
3,2026-05-19-11-36-49 +0000,bbc,Petrol hits highest price since start of Iran war,https://www.bbc.com/news/articles/cdep64555wzo...
4,2026-05-19-11-36-01 +0000,nyt,When Nationalism Beats Nationalism,https://www.nytimes.com/2026/05/18/world/welsh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2553/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
13  trump     43
47    new     24
17   iran     21
76  ebola     15
34    san     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
190,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,127
248,2026-05-18-19-35-00 +0000,cbc,Trump says he called off Tuesday Iran strike a...,https://www.cbc.ca/news/world/trump-iran-strik...,109
329,2026-05-18-14-32-21 +0000,nypost,Iran offers new 14-point peace proposal after ...,https://nypost.com/2026/05/18/us-news/iran-sub...,103
141,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,102
238,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
190,127,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
94,66,2026-05-19-07-08-06 +0000,nypost,Texas mother sobs in court after allegedly kil...,https://nypost.com/2026/05/19/us-news/texas-mo...
81,58,2026-05-19-08-32-21 +0000,nypost,Terrifying moment small children evacuated fro...,https://nypost.com/2026/05/19/us-news/terrifyi...
264,50,2026-05-18-18-34-46 +0000,cbc,American tests positive for Ebola virus amid o...,https://www.cbc.ca/news/health/american-tests-...
271,47,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
141,46,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...
49,44,2026-05-19-10-00-00 +0000,latimes,Forced treatment and jail: Spencer Pratt's ple...,https://www.latimes.com/california/story/2026-...
13,41,2026-05-19-11-01-00 +0000,wsj,The nearly $1.8 billion “anti-weaponization fu...,https://www.wsj.com/politics/how-trumps-1-776-...
281,37,2026-05-18-17-41-00 +0000,wsj,Justice Department Drops Criminal Case Against...,https://www.wsj.com/us-news/law/gautam-adani-f...
296,36,2026-05-18-16-40-26 +0000,nypost,Carl’s Jr. crushed by California’s high minimu...,https://nypost.com/2026/05/18/business/carls-j...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)