## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-04-54-32 +0000,bbc,Iran vows 'decisive response' to first US stri...,https://www.bbc.co.uk/news/articles/cx2z72x5z1...
1,2026-08-31-04-38-25 +0000,nyt,Melting Himalayas,https://www.nytimes.com/2026/08/30/world/nepal...
2,2026-08-31-04-30-29 +0000,wapo,"One person dead, about 15 more may be missing ...",https://www.washingtonpost.com/nation/2026/08/...
3,2026-08-31-04-25-17 +0000,latimes,Lawmakers send bills to Newsom shoring up ball...,https://www.latimes.com/california/story/2026-...
4,2026-08-31-04-23-19 +0000,nypost,Fox that may be infected with rabies is roamin...,https://nypost.com/2026/08/31/us-news/fox-that...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2535/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
224    trump     15
113      new     12
67       off     10
0       iran     10
13   missing     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
52,2026-08-30-23-05-36 +0000,nypost,"At least 8 dead, 18 missing after ferry carryi...",https://nypost.com/2026/08/30/world-news/at-le...,54
17,2026-08-31-02-46-36 +0000,nyt,One Dead and 15 Potentially Missing at Grand C...,https://www.nytimes.com/2026/08/30/us/grand-ca...,52
131,2026-08-30-16-31-00 +0000,wsj,Opinion | Trump’s New Iran Sanctions Put China...,https://www.wsj.com/opinion/trumps-new-iran-sa...,51
2,2026-08-31-04-30-29 +0000,wapo,"One person dead, about 15 more may be missing ...",https://www.washingtonpost.com/nation/2026/08/...,50
124,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,49

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
52,54,2026-08-30-23-05-36 +0000,nypost,"At least 8 dead, 18 missing after ferry carryi...",https://nypost.com/2026/08/30/world-news/at-le...
131,51,2026-08-30-16-31-00 +0000,wsj,Opinion | Trump’s New Iran Sanctions Put China...,https://www.wsj.com/opinion/trumps-new-iran-sa...
133,39,2026-08-30-16-14-00 +0000,wsj,"James Talarico, the Democratic candidate for S...",https://www.wsj.com/politics/policy/talarico-i...
124,34,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...
125,34,2026-08-30-16-48-13 +0000,bbc,Head teacher evacuated 900 children minutes be...,https://www.bbc.co.uk/news/articles/c5ymvdm552...
17,33,2026-08-31-02-46-36 +0000,nyt,One Dead and 15 Potentially Missing at Grand C...,https://www.nytimes.com/2026/08/30/us/grand-ca...
221,33,2026-08-30-06-03-30 +0000,nypost,Switzerland rave shooting leaves 22-year-old w...,https://nypost.com/2026/08/30/world-news/switz...
37,31,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
196,30,2026-08-30-09-30-00 +0000,wsj,Fed Chairman Kevin Warsh put to rest some conc...,https://www.wsj.com/economy/central-banking/wa...
166,27,2026-08-30-12-41-05 +0000,nypost,Clinton foundation seeks intern with ‘high lev...,https://nypost.com/2026/08/30/us-news/bill-and...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)