## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-05-07-32-34 +0000,nyt,Oil Prices Slide but Remain Elevated as Middle...,https://www.nytimes.com/2026/05/05/business/oi...
1,2026-05-05-07-31-00 +0000,wsj,Audi Sticks to Guidance But Warns of Impact Fr...,https://www.wsj.com/business/earnings/audi-sti...
2,2026-05-05-07-28-17 +0000,bbc,Starmer to host No 10 summit to tackle antisem...,https://www.bbc.com/news/articles/czd2l55d1e7o...
3,2026-05-05-07-28-00 +0000,wsj,EQT Raises Takeover Bid For Intertek Again,https://www.wsj.com/business/deals/eqt-raises-...
4,2026-05-05-07-25-59 +0000,nypost,Blast at fireworks factory in China kills 21: ...,https://nypost.com/2026/05/05/world-news/blast...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2370/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
289   trump     26
50     iran     22
110     war     14
58   hormuz     13
0       oil     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
75,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...,121
296,2026-05-04-10-43-08 +0000,nypost,Iran fires on US warship in Strait of Hormuz a...,https://nypost.com/2026/05/04/world-news/iran-...,97
78,2026-05-04-23-52-35 +0000,nypost,Trump is trying to force the Strait of Hormuz ...,https://nypost.com/2026/05/04/world-news/trump...,84
134,2026-05-04-21-33-45 +0000,nyt,China Seeks an Advantage With Both Trump and I...,https://www.nytimes.com/2026/05/03/us/politics...,77
7,2026-05-05-07-16-11 +0000,nypost,Iran warns US against ‘being dragged back into...,https://nypost.com/2026/05/05/world-news/iran-...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
75,121,2026-05-05-00-00-00 +0000,wsj,President Trump’s desire to end the Iran war i...,https://www.wsj.com/politics/national-security...
259,55,2026-05-04-14-41-39 +0000,nypost,MV Hondius cruise ship at center of suspected ...,https://nypost.com/2026/05/04/world-news/mv-ho...
137,53,2026-05-04-21-30-31 +0000,nypost,Ex-JPMorgan banker Chirayu Rana files wild new...,https://nypost.com/2026/05/04/business/ex-jpmo...
221,47,2026-05-04-17-23-00 +0000,wsj,Doris Fisher Was the Quiet Force Behind Gap Be...,https://www.wsj.com/style/fashion/doris-fisher...
318,42,2026-05-04-07-55-14 +0000,wsj,"Stock Market News, May 4, 2026: Oil Rises, Dow...",https://www.wsj.com/livecoverage/stock-market-...
253,41,2026-05-04-15-22-38 +0000,nypost,Supreme Court restores access to abortion pill...,https://nypost.com/2026/05/04/us-news/supreme-...
213,40,2026-05-04-17-52-47 +0000,nypost,Elon Musk pressured OpenAI’s Greg Brockman to ...,https://nypost.com/2026/05/04/business/elon-mu...
207,37,2026-05-04-18-06-28 +0000,nypost,Judge apologizes to White House Correspondents...,https://nypost.com/2026/05/04/us-news/judge-ap...
192,37,2026-05-04-19-09-14 +0000,bbc,Ukrainian drone hits upmarket Moscow high-rise...,https://www.bbc.com/news/articles/cwy234llx3vo...
42,32,2026-05-05-02-43-41 +0000,cbc,Explosion at a China fireworks factory kills a...,https://www.cbc.ca/news/world/china-fireworks-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)