## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-02-12-29-00 +0000,wsj,"U.S. Treasury Yields Rise, Dollar Falls Ahead ...",https://www.wsj.com/finance/currencies/yen-con...
1,2026-07-02-12-28-08 +0000,nyt,Live Updates: Russia Hammers Ukraine’s Capital...,https://www.nytimes.com/live/2026/07/02/world/...
2,2026-07-02-12-28-06 +0000,nyt,Russia’s Deadly Attack on Ukraine Reminds Euro...,https://www.nytimes.com/2026/07/02/world/europ...
3,2026-07-02-12-26-03 +0000,bbc,Car finance compensation payments delayed unti...,https://www.bbc.co.uk/news/articles/c2l9vvj097...
4,2026-07-02-12-23-14 +0000,bbc,"Labour failed to prepare for power, admits PM'...",https://www.bbc.co.uk/news/articles/ce8j2e38zz...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2563/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
114  trump     50
299  world     18
154   iran     16
77     new     15
27    year     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
145,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...,111
54,2026-07-02-10-35-14 +0000,wapo,"Trump-backed truce in Lebanon, key to Iran pea...",https://www.washingtonpost.com/world/2026/07/0...,111
344,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,109
192,2026-07-01-22-17-27 +0000,nypost,Inside the new Air Force One: Trump’s Qatari j...,https://nypost.com/2026/07/01/us-news/inside-t...,99
207,2026-07-01-21-33-43 +0000,nypost,Trump gets ‘fantastic’ advice from AI-powered ...,https://nypost.com/2026/07/01/us-news/trump-ge...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
145,111,2026-07-02-02-00-00 +0000,wsj,President Trump came to office promising an en...,https://www.wsj.com/politics/national-security...
20,62,2026-07-02-11-56-49 +0000,nypost,Family friend charged year after ‘nightmare’ i...,https://nypost.com/2026/07/02/us-news/family-f...
200,59,2026-07-01-21-47-23 +0000,nyt,4 People Die During World Cup Celebrations in ...,https://www.nytimes.com/2026/07/01/world/ameri...
301,55,2026-07-01-17-12-00 +0000,wsj,Elizabeth Warren asked the Fed’s inspector gen...,https://www.wsj.com/economy/central-banking/wa...
100,55,2026-07-02-08-15-56 +0000,wsj,Jobs Report Today: Labor Market Looks to Exten...,https://www.wsj.com/livecoverage/june-jobs-rep...
10,55,2026-07-02-12-17-01 +0000,nyt,Putin Retaliates With New Strikes After Ukrain...,https://www.nytimes.com/2026/07/02/world/europ...
206,47,2026-07-01-21-36-38 +0000,nypost,Trump honors ‘freakin’ wild life’ of Teddy Roo...,https://nypost.com/2026/07/01/us-news/trump-ho...
295,42,2026-07-01-17-24-00 +0000,wsj,We asked five experts across the political spe...,https://www.wsj.com/us-news/law/us-constitutio...
293,37,2026-07-01-17-27-05 +0000,nypost,Trump won’t renew USMCA deal with Canada and M...,https://nypost.com/2026/07/01/us-news/trump-wo...
120,37,2026-07-02-05-14-51 +0000,nypost,"Bodies of Florida beauty queen, boyfriend foun...",https://nypost.com/2026/07/02/world-news/flori...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)