## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-06-23-59 +0000,bbc,Huge blast kills dozens in rebel-held village ...,https://www.bbc.com/news/articles/cglp7p787njo...
1,2026-06-01-06-17-47 +0000,bbc,Iran and US report new wave of strikes in Gulf,https://www.bbc.com/news/articles/crlpy8n7pr6o...
2,2026-06-01-06-10-00 +0000,wsj,German 10-Year Bunds Seen a Buy Opportunity at...,https://www.wsj.com/finance/investing/jgbs-fal...
3,2026-06-01-06-00-37 +0000,nyt,Taiwan Criticizes China Over Expulsion of Time...,https://www.nytimes.com/2026/06/01/world/asia/...
4,2026-06-01-05-48-27 +0000,bbc,Nvidia announces new AI chip for personal comp...,https://www.bbc.com/news/articles/crmp9mppvzro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
87        trump     22
165  california     12
24        china     11
269          he     10
189      israel      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
197,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...,64
37,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...,60
174,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...,58
115,2026-05-31-19-50-13 +0000,nypost,Bitter California Republican feud turns toxic ...,https://nypost.com/2026/05/31/us-news/bitter-c...,56
12,2026-06-01-04-48-53 +0000,nypost,Pro-Trump candidate pulls ahead in Colombia pr...,https://nypost.com/2026/06/01/world-news/pro-t...,51

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
197,64,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...
169,46,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...
174,45,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...
131,36,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...
137,32,2026-05-31-16-34-09 +0000,nypost,NJ Gov. Sherrill claims victory on ICE detenti...,https://nypost.com/2026/05/31/us-news/nj-gov-s...
27,29,2026-06-01-02-47-39 +0000,nypost,Iran digs out underground missile sites during...,https://nypost.com/2026/05/31/world-news/iran-...
90,29,2026-05-31-21-27-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...
149,29,2026-05-31-16-00-00 +0000,wsj,"American capitalism is at a crossroads, facing...",https://www.wsj.com/economy/us-capitalism-econ...
18,28,2026-06-01-04-05-00 +0000,wsj,China PMI Signals Manufacturing Held Up While ...,https://www.wsj.com/economy/china-private-fact...
23,25,2026-06-01-03-15-56 +0000,nypost,California Dems’ huge dilemma over governor ra...,https://nypost.com/2026/05/31/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)