## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-19-16-48-51 +0000,nypost,Ted Cruz says the quiet part out loud as LA vo...,https://nypost.com/2026/05/19/us-news/ted-cruz...
1,2026-05-19-16-47-43 +0000,nypost,Va. teacher Abby Zwerner recounts first grader...,https://nypost.com/2026/05/19/us-news/virginia...
2,2026-05-19-16-44-28 +0000,nyt,Channel Islands Fire Started Accidentally by S...,https://www.nytimes.com/2026/05/18/us/santa-ro...
3,2026-05-19-16-43-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/trump-texas-senat...
4,2026-05-19-16-42-58 +0000,startribune,"Live: Vikings, Twin Cities will host 2028 NFL ...",https://www.startribune.com/minnesota-vikings-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2531/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
37   trump     49
129   iran     23
404    new     20
217     he     18
285  ebola     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
294,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...,137
345,2026-05-18-19-35-00 +0000,cbc,Trump says he called off Tuesday Iran strike a...,https://www.cbc.ca/news/world/trump-iran-strik...,123
254,2026-05-19-01-38-00 +0000,wsj,Republican Sen. Bill Cassidy says he has no re...,https://www.wsj.com/politics/policy/gop-senato...,118
3,2026-05-19-16-43-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/trump-texas-senat...,116
336,2026-05-18-20-20-29 +0000,bbc,Oil price slumps as Trump says he called off I...,https://www.bbc.com/news/articles/czx2ne2ryppo...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
294,137,2026-05-18-22-30-58 +0000,bbc,Trump says he called off new Iran attack at re...,https://www.bbc.com/news/articles/c7079e55zjro...
3,67,2026-05-19-16-43-00 +0000,wsj,President Trump on Tuesday endorsed Texas Atto...,https://www.wsj.com/politics/trump-texas-senat...
237,59,2026-05-19-03-03-33 +0000,nyt,"Before the San Diego Mosque Shooting, a Fearfu...",https://www.nytimes.com/2026/05/18/us/san-dieg...
367,52,2026-05-18-18-06-15 +0000,latimes,"Jury rejects Elon Musk's lawsuit, sides with O...",https://www.latimes.com/business/story/2026-05...
360,51,2026-05-18-18-34-46 +0000,cbc,American tests positive for Ebola virus amid o...,https://www.cbc.ca/news/health/american-tests-...
165,46,2026-05-19-11-01-00 +0000,wsj,The nearly $1.8 billion “anti-weaponization fu...,https://www.wsj.com/politics/how-trumps-1-776-...
337,45,2026-05-18-20-19-21 +0000,nyt,Oil Prices Climb and Bonds Falter as Iran War ...,https://www.nytimes.com/2026/05/18/business/oi...
191,44,2026-05-19-10-00-00 +0000,latimes,"For the first time, a warm winter just wiped o...",https://www.latimes.com/environment/story/2026...
188,42,2026-05-19-10-00-00 +0000,latimes,Forced treatment and jail: Spencer Pratt's ple...,https://www.latimes.com/california/story/2026-...
190,35,2026-05-19-10-00-00 +0000,latimes,Billionaire Tom Steyer's $192.4-million self-f...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)