## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-07-17-16-15 +0000,nypost,Two more California races called — and Republi...,https://nypost.com/2026/06/07/us-news/two-more...
1,2026-06-07-17-13-02 +0000,wapo,"With Leo and Bad Bunny touring Madrid, the big...",https://www.washingtonpost.com/world/2026/06/0...
2,2026-06-07-17-11-54 +0000,bbc,Armenia votes as Russia piles pressure on pro-...,https://www.bbc.com/news/articles/c3626n1epd5o...
3,2026-06-07-17-10-33 +0000,nyt,Lawsuit Aims to Stop U.F.C. Fights at White Ho...,https://www.nytimes.com/2026/06/07/us/politics...
4,2026-06-07-17-09-20 +0000,nypost,New Espaillat ad attacks Mamdani-backed foe fo...,https://nypost.com/2026/06/07/us-news/new-espa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
28   trump     13
261  world     11
64    iran     10
262    cup     10
30     new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
131,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...,59
169,2026-06-06-18-42-07 +0000,nypost,Iran’s World Cup soccer team leaves for Mexico...,https://nypost.com/2026/06/06/world-news/irans...,49
40,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...,43
48,2026-06-07-13-24-50 +0000,bbc,Iran's World Cup team lands in Mexico amid US ...,https://www.bbc.com/news/articles/c5yz3zdp3jqo...,42
91,2026-06-07-09-02-06 +0000,nyt,Trump Says Iran Has Made a ‘Big’ Nuclear Promi...,https://www.nytimes.com/2026/06/07/us/politics...,41

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
131,59,2026-06-06-23-45-42 +0000,nypost,Pope Leo backs team USA in the World Cup — as ...,https://nypost.com/2026/06/06/world-news/pope-...
40,43,2026-06-07-14-13-59 +0000,cbc,"Gunman kills one, wounds five in drive-by atta...",https://www.cbc.ca/news/world/gunman-attack-is...
91,41,2026-06-07-09-02-06 +0000,nyt,Trump Says Iran Has Made a ‘Big’ Nuclear Promi...,https://www.nytimes.com/2026/06/07/us/politics...
29,32,2026-06-07-15-21-34 +0000,nypost,Bombshell LA mayor’s race projection changes e...,https://nypost.com/2026/06/07/us-news/la-mayor...
99,32,2026-06-07-09-00-00 +0000,wsj,Rahm Emanuel’s long résumé would traditionally...,https://www.wsj.com/politics/elections/rahm-em...
149,27,2026-06-06-22-11-32 +0000,nypost,"Three Lebanese Army members, including general...",https://nypost.com/2026/06/06/world-news/three...
25,25,2026-06-07-15-37-00 +0000,wsj,"OPEC, Allies Pledge Oil-Output Hike Even as Mi...",https://www.wsj.com/business/energy-oil/opec-a...
109,24,2026-06-07-05-09-14 +0000,nypost,Long Island’s Robert Moses State Park ramping ...,https://nypost.com/2026/06/07/us-news/long-isl...
17,22,2026-06-07-16-03-48 +0000,nypost,Rep. Max Miller accused of violating restraini...,https://nypost.com/2026/06/07/us-news/rep-max-...
74,22,2026-06-07-10-00-00 +0000,latimes,'We're in survival mode': A year after ICE rai...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)