## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-05-23-00 +0000,wsj,Bank of Korea Nominee Seen Prioritizing Price ...,https://www.wsj.com/economy/central-banking/ba...
1,2026-04-15-05-23-00 +0000,wsj,Chip-Machine Supplier ASML Lifts Guidance on S...,https://www.wsj.com/business/earnings/chip-mac...
2,2026-04-15-05-21-26 +0000,startribune,"Byron Buxton’s hitting, Mick Abel’s pitching p...",https://www.startribune.com/twins-beat-red-sox...
3,2026-04-15-05-20-51 +0000,bbc,Chris Mason: Iran war means government's vicio...,https://www.bbc.com/news/articles/ce8ll6pyvdzo...
4,2026-04-15-05-20-46 +0000,startribune,Hunter Haight scores first NHL goal as Wild be...,https://www.startribune.com/minnesota-wild-bea...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2473/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
29       iran     38
174     trump     31
30        war     23
239       new     20
194  swalwell     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-04-15-04-57-43 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...,102
289,2026-04-14-13-53-29 +0000,nyt,Two Iran-Linked Ships Passed Through Strait of...,https://www.nytimes.com/2026/04/13/world/middl...,101
245,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...,99
301,2026-04-14-13-00-00 +0000,wapo,Iran war already taking a toll on the global e...,https://www.washingtonpost.com/business/2026/0...,97
319,2026-04-14-11-14-54 +0000,nypost,"US, Iran may resume war talks this week despit...",https://nypost.com/2026/04/14/world-news/us-ir...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,102,2026-04-15-04-57-43 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...
20,89,2026-04-15-03-37-00 +0000,wsj,Erica Schwartz is expected to be selected by t...,https://www.wsj.com/politics/policy/trump-admi...
33,74,2026-04-15-02-35-13 +0000,nypost,Special Victims Bureau will handle case of wom...,https://nypost.com/2026/04/14/us-news/la-speci...
37,71,2026-04-15-02-24-00 +0000,wsj,Prosecutors from U.S. Attorney Jeanine Pirro’s...,https://www.wsj.com/us-news/law/jeanine-pirros...
283,71,2026-04-14-14-21-40 +0000,nypost,US boasts no ships moved through Strait of Hor...,https://nypost.com/2026/04/14/world-news/iran-...
296,45,2026-04-14-13-03-00 +0000,wsj,A prolonged Middle East conflict could slash g...,https://www.wsj.com/economy/global/imf-warns-o...
39,45,2026-04-15-02-11-00 +0000,wsj,"Voters in South Hadley, Mass., rejected a stee...",https://www.wsj.com/us-news/massachusetts-town...
346,40,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...
42,38,2026-04-15-02-00-00 +0000,wsj,"So far, it is President Trump—and not Pope Leo...",https://www.wsj.com/politics/trump-pope-leo-ca...
262,38,2026-04-14-15-29-59 +0000,nypost,JPMorgan CEO Jamie Dimon urges Senate to vote ...,https://nypost.com/2026/04/14/business/jpmorga...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)