## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-02-20-59-08 +0000,nyt,Palestinian Brothers Killed as Settler Violenc...,https://www.nytimes.com/2026/03/02/world/middl...
1,2026-03-02-20-58-38 +0000,nyt,Georgia Jurors to Decide if Father’s Inaction ...,https://www.nytimes.com/2026/03/02/us/georgia-...
2,2026-03-02-20-58-37 +0000,nyt,"As Maduro and Khamenei Learned, It’s Harder Th...",https://www.nytimes.com/2026/03/02/us/politics...
3,2026-03-02-20-58-30 +0000,nyt,Live Updates: Trump Suggests Extended War on I...,https://www.nytimes.com/live/2026/03/02/world/...
4,2026-03-02-20-56-25 +0000,nyt,Macron Expands French Nuclear Arsenal and Vows...,https://www.nytimes.com/2026/03/02/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2527/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
30      iran     97
26     trump     43
29       war     28
43   strikes     25
60  conflict     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
34,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,283
303,2026-03-02-01-17-20 +0000,latimes,Thousands rally in Westwood as U.S.-Iran war e...,https://www.latimes.com/california/story/2026-...,234
248,2026-03-02-10-30-00 +0000,wsj,President Trump and his allies offered at leas...,https://www.wsj.com/politics/national-security...,209
186,2026-03-02-15-17-25 +0000,nypost,Trump won’t rule out sending US troops into Ir...,https://nypost.com/2026/03/02/us-news/trump-wo...,205
19,2026-03-02-20-32-01 +0000,startribune,War in the Mideast widens as Trump says strike...,https://www.startribune.com/war-widens-to-incl...,204

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
34,283,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
273,96,2026-03-02-07-45-00 +0000,wsj,Middle East Conflict Sparks Surge in Oil Prices,https://www.wsj.com/world/middle-east/middle-e...
150,76,2026-03-02-16-46-23 +0000,cbc,U.S. military leaders lay out timeline of atta...,https://www.cbc.ca/news/world/us-pentagon-iran...
321,68,2026-03-01-22-24-27 +0000,bbc,Nine dead in missile attack on Israel as Iran ...,https://www.bbc.com/news/articles/c363zkp1pgxo...
243,56,2026-03-02-10-30-00 +0000,wsj,Berkshire’s New CEO Lays Out How He Will Pick ...,https://www.wsj.com/finance/berkshires-new-ceo...
247,48,2026-03-02-10-30-00 +0000,wsj,The Texas Republican Senate primary is getting...,https://www.wsj.com/politics/elections/texas-p...
155,41,2026-03-02-16-34-18 +0000,wapo,Videos appear to show the moments U.S. fighter...,https://www.washingtonpost.com/investigations/...
246,36,2026-03-02-10-30-00 +0000,wsj,Think Tech Has Taken Over Your Portfolio? You ...,https://www.wsj.com/finance/investing/think-te...
248,34,2026-03-02-10-30-00 +0000,wsj,President Trump and his allies offered at leas...,https://www.wsj.com/politics/national-security...
5,34,2026-03-02-20-53-35 +0000,wapo,Live updates: Live updates: Trump says U.S.-Is...,https://www.washingtonpost.com/world/2026/03/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)