## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-28-10-55-00 +0000,wsj,Southern California Ports Face Strike Threat,https://www.wsj.com/logistics-report/southern-...
1,2026-10-28-10-50-59 +0000,nyt,Live Updates: At Least 10 Killed in Train Coll...,https://www.nytimes.com/live/2026/10/28/world/...
2,2026-10-28-10-50-00 +0000,wsj,Deutsche Bank Sees Goals on Track as Corporate...,https://www.wsj.com/business/earnings/deutsche...
3,2026-10-28-10-48-53 +0000,nyt,Jio’s Blockbuster I.P.O. Gives India’s Investo...,https://www.nytimes.com/2026/10/28/business/in...
4,2026-10-28-10-48-00 +0000,wsj,"The ‘Buy, Borrow and Die’ Wealth Strategy Gain...",https://www.wsj.com/finance/investing/the-buy-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2456/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
58   election     28
159     trump     28
54     israel     21
237      race     13
165       out     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
263,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,102
411,2026-10-27-11-04-05 +0000,chitri,Voters rebuke Netanyahu but exit polls suggest...,https://www.chicagotribune.com/2026/10/27/isra...,99
135,2026-10-28-04-00-03 +0000,startribune,Exit polls suggest no clear winner in Israel's...,https://www.startribune.com/voters-in-israel-w...,96
143,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...,86
75,2026-10-28-09-00-42 +0000,chitri,Today in Chicago History: Donald Trump watches...,https://www.chicagotribune.com/2026/10/28/octo...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
263,102,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...
143,86,2026-10-28-02-54-00 +0000,wsj,President Trump rallied in Texas Tuesday night...,https://www.wsj.com/politics/elections/trump-a...
84,60,2026-10-28-08-38-19 +0000,nypost,Cuban official accused of shoving US diplomat ...,https://nypost.com/2026/10/28/us-news/cuban-of...
93,59,2026-10-28-08-17-33 +0000,wsj,Stock Market Today: Tech Stocks Buoyant Ahead ...,https://www.wsj.com/livecoverage/fed-meeting-i...
34,54,2026-10-28-10-00-00 +0000,latimes,"Bass comes from behind, now in dead heat with ...",https://www.latimes.com/california/story/2026-...
33,50,2026-10-28-10-00-00 +0000,latimes,Your last-minute guide to California governor ...,https://www.latimes.com/california/story/2026-...
189,49,2026-10-27-23-40-43 +0000,nypost,Ex-FBI official weeps as she appears in court ...,https://nypost.com/2026/10/27/us-news/ex-fbi-o...
267,48,2026-10-27-20-00-31 +0000,nypost,White Bank of America exec claims he faced dis...,https://nypost.com/2026/10/27/business/white-b...
223,46,2026-10-27-21-40-20 +0000,chitri,Brazil’s Flávio Bolsonaro and family will get ...,https://www.chicagotribune.com/2026/10/27/braz...
179,44,2026-10-28-00-15-54 +0000,nyt,Justice Dept. Steps Up Moves on Comey and Othe...,https://www.nytimes.com/2026/10/27/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)