## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-03-12-00-00 +0000,nypost,LA is exterminating dogs at unprecedented rate...,https://nypost.com/2026/08/03/us-news/los-ange...
1,2026-08-03-11-51-52 +0000,nyt,Trump’s ‘Perimeter of a Deal’ Rallies the Market,https://www.nytimes.com/2026/08/03/business/de...
2,2026-08-03-11-49-48 +0000,bbc,Hundreds flee clashes in northern Ethiopia as ...,https://www.bbc.co.uk/news/articles/cdrv6r3xgy...
3,2026-08-03-11-49-41 +0000,bbc,"Almost £200,000 of fuel stolen from UK forecou...",https://www.bbc.co.uk/news/articles/cy8mrrlkjp...
4,2026-08-03-11-49-24 +0000,nyt,Singapore Bans Band Massive Attack for Display...,https://www.nytimes.com/2026/08/03/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
9   trump     28
30   iran     19
81    new     13
99    out     12
83  talks     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...,92
10,2026-08-03-11-20-12 +0000,nypost,Iran denies Trump claim new peace talks planne...,https://nypost.com/2026/08/03/world-news/iran-...,91
231,2026-08-02-15-40-24 +0000,chitri,President Trump says he will order halt to Ira...,https://www.chicagotribune.com/2026/08/02/trum...,88
41,2026-08-03-10-23-35 +0000,bbc,Iran denies Trump's claim that new talks will ...,https://www.bbc.co.uk/news/articles/c23579jzv0...,85
13,2026-08-03-11-15-44 +0000,chitri,Todd Blanche rescinds fund for Trump allies af...,https://www.chicagotribune.com/2026/08/03/todd...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,92,2026-08-02-23-03-53 +0000,nypost,Trump announces when new Iran talks to begin a...,https://nypost.com/2026/08/02/world-news/trump...
111,77,2026-08-03-05-16-00 +0000,wsj,Acting Attorney General Todd Blanche said he f...,https://www.wsj.com/politics/policy/blanche-fo...
181,63,2026-08-02-19-02-00 +0000,wsj,"Sen. Bernie Moreno says his former son-in-law,...",https://www.wsj.com/politics/elections/domesti...
224,40,2026-08-02-16-00-00 +0000,wsj,Trump said he wants a Qatari-donated jet used ...,https://www.wsj.com/politics/national-security...
45,38,2026-08-03-10-00-00 +0000,latimes,Will California voters 'orphaned' in top-two p...,https://www.latimes.com/politics/story/2026-08...
122,37,2026-08-03-03-32-21 +0000,bbc,'My only son was shot standing up for justice'...,https://www.bbc.co.uk/news/articles/c5yvqk69en...
226,36,2026-08-02-15-50-59 +0000,bbc,At least 13 killed in Israeli strikes on Gaza ...,https://www.bbc.co.uk/news/articles/czjlvvkzj2...
230,32,2026-08-02-15-40-34 +0000,nypost,Horror moment 2 firefighting helicopters colli...,https://nypost.com/2026/08/02/world-news/horro...
92,31,2026-08-03-07-58-14 +0000,wsj,Stock Market Today: Return to Diplomacy Brings...,https://www.wsj.com/livecoverage/stock-market-...
65,29,2026-08-03-09-30-00 +0000,nypost,Kurt Cobain’s widow Courtney Love asked for en...,https://nypost.com/2026/08/03/us-news/kurt-cob...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)