## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-30-14-52-25 +0000,chitri,USS Abraham Lincoln sails past Singapore on it...,https://www.chicagotribune.com/2026/08/30/uss-...
1,2026-08-30-14-49-15 +0000,nyt,"U.A.E. To Review Banque Misr, Targeted by Iran...",https://www.nytimes.com/2026/08/30/world/middl...
2,2026-08-30-14-47-46 +0000,chitri,Norwegians line up at churches for emotional m...,https://www.chicagotribune.com/2026/08/30/norw...
3,2026-08-30-14-45-05 +0000,bbc,Iceland votes against restarting EU membership...,https://www.bbc.co.uk/news/articles/c70le8ed1p...
4,2026-08-30-14-42-00 +0000,wsj,Opinion | The High Cost of Cheaper Steal,https://www.wsj.com/opinion/the-high-cost-of-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2401/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
123       trump     15
198         new     12
36        nepal      9
408  california      9
249      attack      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
154,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...,45
115,2026-08-30-04-01-02 +0000,bbc,Trump hails 'historic' deal to control 65 bill...,https://www.bbc.co.uk/news/articles/cx2zlwe7qj...,43
199,2026-08-29-16-53-11 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...,41
203,2026-08-29-16-02-52 +0000,chitri,Nepal-China flood survivors reach safe areas a...,https://www.chicagotribune.com/2026/08/29/nepa...,40
180,2026-08-29-18-35-56 +0000,chitri,Noncitizen voting claims animate President Tru...,https://www.chicagotribune.com/2026/08/29/nonc...,39

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
154,45,2026-08-29-21-28-52 +0000,cbc,Trump's Venezuelan oil deal: What we know and ...,https://www.cbc.ca/news/world/trump-venezuela-...
203,40,2026-08-29-16-02-52 +0000,chitri,Nepal-China flood survivors reach safe areas a...,https://www.chicagotribune.com/2026/08/29/nepa...
46,37,2026-08-30-11-00-00 +0000,startribune,He wants to open their 10-year marriage to new...,https://www.startribune.com/he-wants-to-open-t...
192,35,2026-08-29-17-33-56 +0000,wapo,British far-right provocateur Milo Yiannopoulo...,https://www.washingtonpost.com/nation/2026/08/...
32,30,2026-08-30-12-41-05 +0000,nypost,Clinton foundation seeks intern with ‘high lev...,https://nypost.com/2026/08/30/us-news/bill-and...
104,30,2026-08-30-06-03-30 +0000,nypost,Switzerland rave shooting leaves 22-year-old w...,https://nypost.com/2026/08/30/world-news/switz...
11,29,2026-08-30-14-16-40 +0000,chitri,"Iran’s leader calls for Muslim unity, NBC crew...",https://www.chicagotribune.com/2026/08/30/nbc-...
90,28,2026-08-30-09-00-00 +0000,wsj,Social Security’s looming insolvency is the co...,https://www.wsj.com/politics/policy/social-sec...
158,26,2026-08-29-21-11-33 +0000,latimes,Lopez: Gov. Newsom backs off from shameful gam...,https://www.latimes.com/california/story/2026-...
102,23,2026-08-30-06-23-31 +0000,nypost,North Carolina warns petting zoo visitors of r...,https://nypost.com/2026/08/30/us-news/north-ca...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)