## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-14-20-52-15 +0000,nyt,Iran War Live Updates: U.S. Tells Citizens to ...,https://www.nytimes.com/live/2026/03/14/world/...
1,2026-03-14-20-51-57 +0000,startribune,Live: Benilde-St. Margaret’s surges in second ...,https://www.startribune.com/mn-girls-basketbal...
2,2026-03-14-20-48-55 +0000,bbc,Three more Iran football team members change m...,https://www.bbc.com/news/articles/c98gz372683o...
3,2026-03-14-20-45-53 +0000,nypost,Zelensky frustrated by stalled talks since Ira...,https://nypost.com/2026/03/14/world-news/zelen...
4,2026-03-14-20-36-00 +0000,wsj,Why Did Trump Order an Attack on Iran’s Kharg ...,https://www.wsj.com/world/middle-east/why-did-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2481/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
37   trump     43
0     iran     37
1      war     28
168    oil     25
86     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
183,2026-03-14-00-57-55 +0000,latimes,Trump administration orders restart of oil dri...,https://www.latimes.com/california/story/2026-...,151
182,2026-03-14-01-00-00 +0000,wsj,Trump Knew the Risk of Iran Blocking the Strai...,https://www.wsj.com/politics/national-security...,134
179,2026-03-14-01-22-17 +0000,nyt,"U.S. Attacks Iran’s Kharg Island, a Key Port f...",https://www.nytimes.com/2026/03/13/world/middl...,129
65,2026-03-14-16-29-25 +0000,wapo,"Trump says U.S. struck Kharg Island, core of I...",https://www.washingtonpost.com/politics/2026/0...,126
53,2026-03-14-17-18-24 +0000,nypost,Lindsey Graham praises Trump’s ‘bold’ takeover...,https://nypost.com/2026/03/14/us-news/lindsey-...,124

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
183,151,2026-03-14-00-57-55 +0000,latimes,Trump administration orders restart of oil dri...,https://www.latimes.com/california/story/2026-...
53,44,2026-03-14-17-18-24 +0000,nypost,Lindsey Graham praises Trump’s ‘bold’ takeover...,https://nypost.com/2026/03/14/us-news/lindsey-...
214,43,2026-03-13-23-03-39 +0000,wapo,New dime to celebrate America’s birthday takes...,https://www.washingtonpost.com/business/2026/0...
239,42,2026-03-13-21-39-00 +0000,wsj,"In a major victory for the Fed, a judge threw ...",https://www.wsj.com/economy/central-banking/ju...
20,41,2026-03-14-19-40-45 +0000,cbc,"Carney, Norway PM push message of oil-market s...",https://www.cbc.ca/news/politics/carney-norway...
192,37,2026-03-14-00-29-00 +0000,wsj,Family of Michigan Synagogue Attacker Killed i...,https://www.wsj.com/us-news/family-of-michigan...
5,36,2026-03-14-20-33-43 +0000,nypost,Brutal moment ‘Access Hollywood’ staff told sh...,https://nypost.com/2026/03/14/us-news/brutal-m...
129,34,2026-03-14-09-30-00 +0000,wsj,A slew of data released Friday portrayed an ec...,https://www.wsj.com/economy/oil-shock-hits-an-...
105,31,2026-03-14-12-00-00 +0000,latimes,Lopez: My promise to you: AI didn't write this...,https://www.latimes.com/california/story/2026-...
175,31,2026-03-14-01-36-00 +0000,wsj,Watch the WSJ’s analysis of more than 100 vide...,https://www.wsj.com/politics/policy/video-game...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)