## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-13-22-49-25 +0000,nypost,"Alaskan boy, 15, who survived 62 hours at sea ...",https://nypost.com/2026/09/13/us-news/alaskan-...
1,2026-09-13-22-44-22 +0000,nypost,California moves to skewer Huntington Beach wi...,https://nypost.com/2026/09/13/us-news/californ...
2,2026-09-13-22-34-47 +0000,latimes,"California lawmakers urge criminal penalties, ...",https://www.latimes.com/california/story/2026-...
3,2026-09-13-22-34-35 +0000,startribune,"Live: Vikings QB Carson Wentz, in for injured ...",https://www.startribune.com/minnesota-vikings-...
4,2026-09-13-22-29-36 +0000,nyt,Oil Prices Jump on Energy Supply Worries,https://www.nytimes.com/2026/09/13/business/oi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2318/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     34
27      ai     16
200    new     13
164     he     12
78     out      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
50,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...,103
52,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...,96
43,2026-09-13-20-25-00 +0000,wsj,President Trump made a surprise trade announce...,https://www.wsj.com/economy/trade/trump-pledge...,92
78,2026-09-13-18-13-12 +0000,chitri,President Donald Trump downplays the need to c...,https://www.chicagotribune.com/2026/09/13/trum...,91
116,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
50,103,2026-09-13-19-47-00 +0000,wsj,Trump’s Irish weekend was supposed to center o...,https://www.wsj.com/politics/elections/for-tru...
27,73,2026-09-13-21-30-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
116,56,2026-09-13-14-22-44 +0000,nypost,Trump brushes off AI doom predictions as ‘thin...,https://nypost.com/2026/09/13/tech/trump-brush...
84,44,2026-09-13-17-41-22 +0000,chitri,President Donald Trump calls on Ukraine to hal...,https://www.chicagotribune.com/2026/09/13/trum...
154,40,2026-09-13-10-00-00 +0000,latimes,California prison towns grasp for new jobs aft...,https://www.latimes.com/california/story/2026-...
35,33,2026-09-13-21-05-45 +0000,nypost,War between SoFi Stadium and Inglewood takes d...,https://nypost.com/2026/09/13/business/war-bet...
144,32,2026-09-13-10-36-25 +0000,wapo,"Six dead, over 100 missing after Indonesian pa...",https://www.washingtonpost.com/world/2026/09/1...
142,31,2026-09-13-10-54-00 +0000,wsj,The latest spot for a Trump Tower is an ex-Sov...,https://www.wsj.com/economy/canada-seeks-eu-as...
52,29,2026-09-13-19-34-36 +0000,bbc,Trump says he will remove all Irish whiskey ta...,https://www.bbc.co.uk/news/articles/cx2z79n0ee...
47,27,2026-09-13-20-14-54 +0000,nypost,Young man and woman caught on video sitting on...,https://nypost.com/2026/09/13/us-news/young-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)