## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-24-22-58-46 +0000,nyt,New York Times Accuses Pentagon of Defying Cou...,https://www.nytimes.com/2026/03/24/business/me...
1,2026-03-24-22-58-18 +0000,nypost,"Mass. cop, husband accused of sexual abuse of ...",https://nypost.com/2026/03/24/us-news/mass-cop...
2,2026-03-24-22-56-40 +0000,startribune,"Live: Goodhue, Perham take Target Center court...",https://www.startribune.com/minnesota-boys-bas...
3,2026-03-24-22-54-45 +0000,nypost,California hospitality union makes outrageous ...,https://nypost.com/2026/03/24/us-news/californ...
4,2026-03-24-22-54-00 +0000,wsj,U.S. Senator Launches Inquiry Into Private Equ...,https://www.wsj.com/articles/u-s-senator-launc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2620/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
57    iran     51
136  trump     36
58     war     25
0      new     15
104   deal     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-03-24-22-49-54 +0000,nyt,Iran War Live Updates: U.S. Is Said to Have Se...,https://www.nytimes.com/live/2026/03/24/world/...,144
75,2026-03-24-21-11-12 +0000,wapo,Trump declares Iran war ‘won’ as Tehran denies...,https://www.washingtonpost.com/national-securi...,143
101,2026-03-24-20-41-20 +0000,nyt,High Oil and Gas Prices Could Outlast Trump’s ...,https://www.nytimes.com/2026/03/24/us/politics...,142
65,2026-03-24-21-26-30 +0000,nyt,Trump’s Threat to ‘Obliterate’ Iran’s Power St...,https://www.nytimes.com/2026/03/24/us/politics...,133
370,2026-03-24-00-14-14 +0000,nyt,"Trump Delays Threat to Iran, but War Negotiati...",https://www.nytimes.com/2026/03/23/us/politics...,127

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,144,2026-03-24-22-49-54 +0000,nyt,Iran War Live Updates: U.S. Is Said to Have Se...,https://www.nytimes.com/live/2026/03/24/world/...
118,89,2026-03-24-19-56-09 +0000,nypost,Markwayne Mullin sworn in as Trump’s new homel...,https://nypost.com/2026/03/24/us-news/markwayn...
48,69,2026-03-24-21-49-02 +0000,nypost,NTSB reveals excruciating final 3 minutes befo...,https://nypost.com/2026/03/24/us-news/excrucia...
43,48,2026-03-24-21-56-00 +0000,wsj,GOP senators have made an offer to Democrats t...,https://www.wsj.com/politics/policy/gop-senato...
232,48,2026-03-24-14-40-00 +0000,wsj,Oklahoma Republican Gov. Kevin Stitt selected ...,https://www.wsj.com/politics/policy/alan-armst...
143,45,2026-03-24-18-46-23 +0000,cbc,Israel's defence minister says military plans ...,https://www.cbc.ca/news/world/israel-army-leba...
361,44,2026-03-24-00-47-00 +0000,wsj,The Defense Department introduced new restrict...,https://www.wsj.com/politics/national-security...
136,44,2026-03-24-19-08-00 +0000,wsj,Oil Futures Regain Ground As Strikes Continue ...,https://www.wsj.com/finance/commodities-future...
265,39,2026-03-24-12-14-15 +0000,bbc,Australia and EU agree sweeping trade deal in ...,https://www.bbc.com/news/articles/cly6g6l6lq7o...
288,37,2026-03-24-10-00-00 +0000,latimes,"If SoCal hotels, stadiums host ICE agents, emp...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)