## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-19-11-00-21 +0000,bbc,Sacked Ukrainian defence minister calls for pr...,https://www.bbc.co.uk/news/articles/cdew8n9erl...
1,2026-08-19-10-52-00 +0000,wsj,U.S. Refiners Capitalize as Buyers Vie for Shr...,https://www.wsj.com/logistics-report/u-s-refin...
2,2026-08-19-10-51-00 +0000,wsj,The great bipartisan data center smackdown has...,https://www.wsj.com/politics/policy/the-great-...
3,2026-08-19-10-47-22 +0000,bbc,"Liberia agrees to accept 1,200 foreign deporte...",https://www.bbc.co.uk/news/articles/cpq8g22715...
4,2026-08-19-10-46-00 +0000,wsj,Estee Lauder Narrows Loss as Sales Climb,https://www.wsj.com/business/retail/estee-laud...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2440/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
87      trump     53
282   florida     37
280   primary     19
135       new     18
392  governor     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
122,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...,151
168,2026-08-19-00-20-49 +0000,nyt,Trump Ally Scott Singer Wins Republican Primar...,https://www.nytimes.com/2026/08/18/us/politics...,146
166,2026-08-19-00-25-07 +0000,nypost,DSA member Angie Nixon upsets Trump impeachmen...,https://nypost.com/2026/08/18/us-news/dsa-memb...,145
176,2026-08-18-23-56-32 +0000,nyt,"Sydney Gruters, Wife of R.N.C. Chair, Wins Hou...",https://www.nytimes.com/2026/08/18/us/politics...,133
164,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...,131

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
122,151,2026-08-19-03-12-00 +0000,wsj,"Rep. Byron Donalds, President Trump’s staunch ...",https://www.wsj.com/politics/elections/florida...
113,84,2026-08-19-03-39-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...
108,58,2026-08-19-03-56-35 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
266,55,2026-08-18-20-46-00 +0000,wsj,U.S. Tech Stocks Slip as Bond Yields Hit Decad...,https://www.wsj.com/finance/stocks/u-s-tech-st...
214,49,2026-08-18-21-48-15 +0000,nypost,"RFK Jr.’s son, Conor Kennedy, put on Russian w...",https://nypost.com/2026/08/18/world-news/rfk-j...
313,46,2026-08-18-18-28-42 +0000,nypost,Rep. Young Kim donates campaign contributions ...,https://nypost.com/2026/08/18/us-news/young-ki...
164,45,2026-08-19-00-33-29 +0000,chitri,US Rep Byron Donalds wins GOP nod for Florida ...,https://www.chicagotribune.com/2026/08/18/byro...
377,41,2026-08-18-14-09-20 +0000,nypost,Disney’s ABC sues FCC over Trump admin’s alleg...,https://nypost.com/2026/08/18/media/disneys-ab...
180,40,2026-08-18-23-32-16 +0000,nyt,Former Mother-in-Law Describes Lindsay Clancy’...,https://www.nytimes.com/2026/08/18/us/lindsay-...
259,39,2026-08-18-20-55-21 +0000,nypost,Amazon joins other tech giants in gobbling up ...,https://nypost.com/2026/08/18/business/amazon-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)