## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-23-16-58-13 +0000,nypost,Police officer who shot and killed 1-year-old ...,https://nypost.com/2026/10/23/us-news/police-o...
1,2026-10-23-16-57-25 +0000,nyt,Where Brazil’s Left Is Losing Voters,https://www.nytimes.com/video/world/americas/1...
2,2026-10-23-16-54-00 +0000,nypost,NYC lost 30K private sector jobs in just 2 mon...,https://nypost.com/2026/10/23/us-news/nyc-lost...
3,2026-10-23-16-53-45 +0000,bbc,Ex-Tory campaign chief and his wife receive su...,https://www.bbc.co.uk/news/articles/ck3r5798p4...
4,2026-10-23-16-50-04 +0000,startribune,2 ex-FBI officials charged with lying about in...,https://www.startribune.com/ex-fbi-official-wh...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2607/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
54        trump     45
72          new     22
291          up     18
487          he     16
68   california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
282,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...,108
216,2026-10-23-09-30-00 +0000,wsj,Capital Account: President Trump once called “...,https://www.wsj.com/economy/trade/how-tariffs-...,104
25,2026-10-23-16-27-00 +0000,wsj,The Trump administration has asked a federal c...,https://www.wsj.com/politics/elections/justice...,103
390,2026-10-22-19-00-13 +0000,nypost,Trump tells Elon Musk to lift any limits on St...,https://nypost.com/2026/10/22/us-news/trump-ca...,100
263,2026-10-23-04-00-06 +0000,nypost,Trump says it’s ‘not looking good’ for Ilhan O...,https://nypost.com/2026/10/23/us-news/trump-sa...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
282,108,2026-10-23-01-10-00 +0000,wsj,President Trump defended an attack ad against ...,https://www.wsj.com/politics/elections/trump-p...
59,78,2026-10-23-15-38-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...
209,73,2026-10-23-10-00-00 +0000,latimes,"He didn't think he'd ever be a lawyer. Now, he...",https://www.latimes.com/california/story/2026-...
89,67,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls 7...,https://nypost.com/2026/10/23/business/oil-pri...
402,63,2026-10-22-18-26-56 +0000,bbc,Zuckerberg wins Meta deal to help him foot bil...,https://www.bbc.co.uk/news/articles/cky83vwnyg...
40,59,2026-10-23-16-09-49 +0000,nypost,Apple fanatics line up overnight for new folda...,https://nypost.com/2026/10/23/business/apple-f...
390,55,2026-10-22-19-00-13 +0000,nypost,Trump tells Elon Musk to lift any limits on St...,https://nypost.com/2026/10/22/us-news/trump-ca...
25,53,2026-10-23-16-27-00 +0000,wsj,The Trump administration has asked a federal c...,https://www.wsj.com/politics/elections/justice...
348,46,2026-10-22-21-00-40 +0000,latimes,Judge limits election-related immigration stop...,https://www.latimes.com/politics/story/2026-10...
396,45,2026-10-22-18-41-58 +0000,nypost,Ex-White House staffer goes incognito as she’s...,https://nypost.com/2026/10/22/us-news/ex-white...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)