## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-27-23-09-00 +0000,nypost,"Middle schoolers laugh, smile at camera as bra...",https://nypost.com/2026/04/27/us-news/middle-s...
1,2026-04-27-23-04-42 +0000,nyt,"Iraq Taps Businessman, Ali al-Zaidi, to Form N...",https://www.nytimes.com/2026/04/27/world/middl...
2,2026-04-27-23-03-39 +0000,bbc,"'I had £20,000 stolen and had to fight a 13-mo...",https://www.bbc.com/news/articles/cpvxg1vzxzjo...
3,2026-04-27-23-03-10 +0000,bbc,Why Spotify has no button to filter out AI music,https://www.bbc.com/news/articles/cd7jpg4w181o...
4,2026-04-27-23-01-16 +0000,nyt,Pentagon Can Temporarily Require Escorts for J...,https://www.nytimes.com/2026/04/27/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2628/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
38      trump     40
40       iran     19
71   shooting     18
72       king     15
222     court     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
109,2026-04-27-19-43-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...,141
284,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...,119
185,2026-04-27-14-43-17 +0000,nypost,Melania Trump marks quiet birthday day after ‘...,https://nypost.com/2026/04/27/us-news/melania-...,112
8,2026-04-27-22-55-01 +0000,startribune,Man charged with attempted assassination of Tr...,https://www.startribune.com/washington-media-d...,107
11,2026-04-27-22-50-26 +0000,nyt,King Charles Visits Trump’s Washington After C...,https://www.nytimes.com/2026/04/27/us/politics...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
109,141,2026-04-27-19-43-00 +0000,wsj,President Trump is calling on Disney’s ABC to ...,https://www.wsj.com/business/media/jimmy-kimme...
284,76,2026-04-27-03-45-00 +0000,wsj,President Trump was excited to deliver a speec...,https://www.wsj.com/us-news/a-celebration-is-d...
251,72,2026-04-27-09-27-55 +0000,nypost,Elon Musk and OpenAI CEO Sam Altman head to co...,https://nypost.com/2026/04/27/business/elon-mu...
136,65,2026-04-27-17-57-06 +0000,nyt,Iran’s Foreign Minister Is in Russia for Talks...,https://www.nytimes.com/2026/04/27/world/europ...
11,54,2026-04-27-22-50-26 +0000,nyt,King Charles Visits Trump’s Washington After C...,https://www.nytimes.com/2026/04/27/us/politics...
194,50,2026-04-27-14-01-30 +0000,nypost,Mass exodus fears as California billionaire ta...,https://nypost.com/2026/04/27/us-news/californ...
188,46,2026-04-27-14-36-00 +0000,wsj,The Federal Reserve succession drama now comes...,https://www.wsj.com/economy/central-banking/fe...
182,40,2026-04-27-15-04-35 +0000,nypost,Gov. Ron DeSantis unveils proposed new Florida...,https://nypost.com/2026/04/27/us-news/gov-ron-...
31,36,2026-04-27-22-00-56 +0000,nyt,Carney to Launch Sovereign Wealth Fund to Dist...,https://www.nytimes.com/2026/04/27/world/canad...
12,34,2026-04-27-22-48-52 +0000,nypost,Investigators’ working theory for why WHCD sho...,https://nypost.com/2026/04/27/us-news/why-kash...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)