## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-29-07-45-41 +0000,bbc,Ticket prices set to rise by 15p as Heathrow a...,https://www.bbc.co.uk/news/articles/cdx8ke9gpn...
1,2026-07-29-07-43-00 +0000,wsj,Oil Surges After U.S.-Iran Tensions Reignite,https://www.wsj.com/finance/commodities-future...
2,2026-07-29-07-39-00 +0000,wsj,Dollar Could Fall if Fed Decision Dampens Rate...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-07-29-07-25-00 +0000,wsj,European Indexes Higher at Open as Earnings Dr...,https://www.wsj.com/finance/stocks/nikkei-rise...
4,2026-07-29-07-23-40 +0000,bbc,1975: The world's first shop for left-handers,https://www.bbc.co.uk/videos/cr47gvdk9n3o?at_m...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2300/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
357   trump     41
80      new     23
11     iran     19
452  graham     18
692      ai     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
163,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,131
371,2026-07-28-10-00-00 +0000,wsj,The key points of tension between Trump and RF...,https://www.wsj.com/politics/policy/the-key-po...,110
259,2026-07-28-17-39-53 +0000,nypost,Senate confirms Manhattan US Attorney Jay Clay...,https://nypost.com/2026/07/28/us-news/senate-c...,103
227,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,101
286,2026-07-28-16-31-19 +0000,chitri,Benjamin Netanyahu praises first meeting with ...,https://www.chicagotribune.com/2026/07/28/trum...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
163,131,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
90,72,2026-07-29-00-36-00 +0000,wsj,"With the Iran war continuing, Israeli Prime Mi...",https://www.wsj.com/world/middle-east/netanyah...
284,62,2026-07-28-16-32-23 +0000,nypost,Gavin Newsom responds to Ruby Rippey’s claims ...,https://nypost.com/2026/07/28/us-news/gavin-ne...
155,52,2026-07-28-21-41-00 +0000,wsj,The Trump administration plans to halt a Medic...,https://www.wsj.com/politics/policy/medicare-d...
24,49,2026-07-29-06-09-09 +0000,nypost,"Kansas high school teacher dragged out, arrest...",https://nypost.com/2026/07/29/us-news/kansas-h...
97,46,2026-07-29-00-24-16 +0000,nypost,California Dems target AI campaign ads after S...,https://nypost.com/2026/07/28/us-news/californ...
48,44,2026-07-29-03-42-53 +0000,bbc,Japan earthquake kills at least 13 as rescuers...,https://www.bbc.co.uk/news/articles/cgewg24qgn...
203,44,2026-07-28-20-07-09 +0000,cbc,15-year-old arrested in Seattle festival shoot...,https://www.cbc.ca/news/world/seattle-shooting...
83,43,2026-07-29-01-00-00 +0000,wsj,"By the time the Federal Reserve meets, Wall St...",https://www.wsj.com/economy/central-banking/wh...
49,40,2026-07-29-03-35-02 +0000,nypost,"Maniac accused of killing mom, sister before b...",https://nypost.com/2026/07/28/us-news/nyc-mani...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)