## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-27-23-00-04 +0000,startribune,Trump signs order renaming Lake Ontario as 'La...,https://www.startribune.com/trump-signs-order-...
1,2026-08-27-23-00-02 +0000,nypost,California made its own homeless problem worse...,https://nypost.com/2026/08/27/us-news/californ...
2,2026-08-27-23-00-01 +0000,chitri,Gary airport receives final grant for new tower,https://www.chicagotribune.com/2026/08/27/gary...
3,2026-08-27-22-58-56 +0000,nypost,Unhinged straphanger stabs MTA cleaner who sco...,https://nypost.com/2026/08/27/us-news/unhinged...
4,2026-08-27-22-54-28 +0000,bbc,What we know about deadly Nepal-Tibet floods,https://www.bbc.co.uk/news/articles/cd948kn02e...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
0        trump     49
39       nepal     27
22         new     20
8   california     19
3         lake     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
170,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...,136
163,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...,135
28,2026-08-27-21-52-39 +0000,wapo,Trump signs order renaming Lake Ontario as Lak...,https://www.washingtonpost.com/politics/2026/0...,131
0,2026-08-27-23-00-04 +0000,startribune,Trump signs order renaming Lake Ontario as 'La...,https://www.startribune.com/trump-signs-order-...,123
74,2026-08-27-21-04-00 +0000,wsj,Trump Signs Executive Order to Rename Lake Ont...,https://www.wsj.com/world/americas/trump-canad...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
170,136,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...
201,77,2026-08-27-16-13-39 +0000,bbc,Tracing the deadly path of the Nepal-Tibet fla...,https://www.bbc.co.uk/news/videos/cp80m87pez3o...
119,73,2026-08-27-19-58-00 +0000,wsj,New York Attorney General Letitia James is sui...,https://www.wsj.com/politics/policy/new-york-s...
248,65,2026-08-27-14-11-08 +0000,nypost,"Ratko Mladic, ruthless ex-Bosnian Serb war cri...",https://nypost.com/2026/08/27/world-news/ratko...
238,62,2026-08-27-14-29-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
229,59,2026-08-27-14-51-00 +0000,wsj,California has made it easier to file civil cl...,https://www.wsj.com/politics/policy/california...
75,56,2026-08-27-21-03-00 +0000,wsj,Federal investigators said the temporary reloc...,https://www.wsj.com/politics/policy/investigat...
333,47,2026-08-27-09-30-00 +0000,wsj,The selloff in U.S. Treasurys has captured glo...,https://www.wsj.com/economy/global/think-treas...
153,43,2026-08-27-18-13-52 +0000,bbc,"Key moments in trial of Lindsay Clancy, the mo...",https://www.bbc.co.uk/news/articles/cg7mlmg475...
193,42,2026-08-27-16-45-00 +0000,wsj,Fed Chairman Kevin Warsh takes the stage in Ja...,https://www.wsj.com/economy/central-banking/be...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)