## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-18-21-02-32 +0000,nyt,Fed Holds Rates Steady as War in Iran Upends t...,https://www.nytimes.com/2026/03/18/business/fe...
1,2026-03-18-21-01-00 +0000,wsj,Health Care Roundup: Market Talk,https://www.wsj.com/business/health-care-round...
2,2026-03-18-21-00-10 +0000,nyt,Strikes Deliver Another Blow to Iran’s Domesti...,https://www.nytimes.com/2026/03/18/world/middl...
3,2026-03-18-21-00-00 +0000,wsj,How Lego Became a Go-To Meme of the Propaganda...,https://www.wsj.com/world/lego-ai-propaganda-w...
4,2026-03-18-20-59-48 +0000,bbc,King praises 'living bridge' with Nigeria at g...,https://www.bbc.com/news/articles/cedzqqp9x2do...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
5        iran     59
4         war     37
148     trump     35
856  illinois     17
157    chavez     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
213,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...,179
395,2026-03-17-23-29-32 +0000,nyt,"Joe Kent, a Top Counterterrorism Official for ...",https://www.nytimes.com/2026/03/17/us/politics...,172
257,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,167
294,2026-03-18-09-02-19 +0000,nyt,Tulsi Gabbard and Top Intelligence Officials W...,https://www.nytimes.com/2026/03/18/us/politics...,160
353,2026-03-18-02-12-16 +0000,bbc,Top US counterterrorism official resigns over ...,https://www.bbc.com/news/articles/cg4g66r3z40o...,158

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
213,179,2026-03-18-14-16-56 +0000,nypost,Trump waives Jones Act to address soaring gas ...,https://nypost.com/2026/03/18/us-news/trump-wa...
349,91,2026-03-18-02-44-31 +0000,nypost,Lt. Gov. Juliana Stratton wins Illinois Senate...,https://nypost.com/2026/03/17/us-news/juliana-...
109,82,2026-03-18-18-09-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
69,59,2026-03-18-19-35-27 +0000,cbc,U.S. civil rights leader Dolores Huerta says C...,https://www.cbc.ca/news/world/cesar-chavez-all...
282,55,2026-03-18-10-00-00 +0000,nypost,"Trump will ‘rebalance’ media, FCC boss Brendan...",https://nypost.com/2026/03/18/us-news/fcc-boss...
374,54,2026-03-18-01-00-00 +0000,wsj,"The resignation of Joe Kent, the Trump adminis...",https://www.wsj.com/politics/national-security...
76,51,2026-03-18-19-29-00 +0000,wsj,An updated list shows House departures hitting...,https://www.wsj.com/politics/policy/why-a-reco...
92,48,2026-03-18-18-51-07 +0000,bbc,Five takeaways from Markwayne Mullin's Homelan...,https://www.bbc.com/news/articles/c2k8kp7d832o...
217,48,2026-03-18-14-00-00 +0000,wsj,He’s Leaving Citigroup to Be a CEO. Can He Lan...,https://www.wsj.com/finance/banking/hes-leavin...
258,48,2026-03-18-10-59-42 +0000,nypost,Israel says it assassinated Iranian intelligen...,https://nypost.com/2026/03/18/world-news/israe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)