## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-02-01-16-04 +0000,nyt,Iran War Live Updates: Trump Says Military Obj...,https://www.nytimes.com/live/2026/04/01/world/...
1,2026-04-02-01-10-04 +0000,startribune,Trump addresses nation on Iran war in first pr...,https://www.startribune.com/iran-hits-tanker-o...
2,2026-04-02-01-08-59 +0000,bbc,Alleged Bondi gunman loses court bid to suppre...,https://www.bbc.com/news/articles/c4glrnv3qlvo...
3,2026-04-02-01-03-14 +0000,nyt,U.S. Senators Press Taiwan to Raise Military S...,https://www.nytimes.com/2026/03/31/world/asia/...
4,2026-04-02-01-01-00 +0000,wsj,Asian Currencies Consolidate Ahead of Trump’s ...,https://www.wsj.com/finance/currencies/asian-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2573/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

            word  score
4          trump     63
0           iran     54
1            war     41
142   birthright     27
143  citizenship     25

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
115,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...,198
289,2026-04-01-10-00-00 +0000,latimes,"With Trump watching, Supreme Court justices so...",https://www.latimes.com/politics/story/2026-04...,186
1,2026-04-02-01-10-04 +0000,startribune,Trump addresses nation on Iran war in first pr...,https://www.startribune.com/iran-hits-tanker-o...,185
280,2026-04-01-10-42-57 +0000,bbc,Trump says he will attend birthright citizensh...,https://www.bbc.com/news/articles/c7vqny4e198o...,184
242,2026-04-01-13-50-51 +0000,latimes,Trump signals Iran war off-ramp while administ...,https://www.latimes.com/world-nation/story/202...,183

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
115,198,2026-04-01-20-13-34 +0000,nyt,Markets Extend Rally and Oil Prices Drop After...,https://www.nytimes.com/2026/04/01/business/st...
220,128,2026-04-01-14-51-47 +0000,nyt,Lawyer Arguing at Supreme Court to Save Birthr...,https://www.nytimes.com/2026/04/01/us/politics...
60,52,2026-04-01-22-37-03 +0000,nypost,Artemis II blasts off for moon mission in glor...,https://nypost.com/2026/04/01/us-news/artemis-...
204,47,2026-04-01-15-50-00 +0000,wsj,The drone having its moment in the Middle East...,https://www.wsj.com/politics/national-security...
333,44,2026-04-01-08-00-00 +0000,cbc,Trump administration launches new bid to attra...,https://www.cbc.ca/news/canada/calgary/bakx-ve...
359,43,2026-04-01-02-32-31 +0000,nyt,Trump Lashes Out at Europe Over Strait of Horm...,https://www.nytimes.com/2026/03/31/world/middl...
211,43,2026-04-01-15-16-14 +0000,nypost,Kristi Noem’s hometown pals in disbelief over ...,https://nypost.com/2026/04/01/us-news/kristi-n...
35,42,2026-04-01-23-29-00 +0000,wsj,Trump endorsed a two-part plan to quickly fund...,https://www.wsj.com/politics/policy/trump-lays...
334,38,2026-04-01-07-31-03 +0000,wsj,Stock Market Today: Dow Advances on Hopes for ...,https://www.wsj.com/livecoverage/stock-market-...
71,34,2026-04-01-22-05-00 +0000,wsj,The Trump administration has lifted sanctions ...,https://www.wsj.com/world/americas/u-s-lifts-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)