## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-17-15-54-07 +0000,nypost,"Glam influencer dragged from home, executed in...",https://nypost.com/2026/09/17/world-news/glam-...
1,2026-09-17-15-52-36 +0000,nyt,G.O.P. Representative Breaks With Trump in Ad:...,https://www.nytimes.com/2026/09/17/us/politics...
2,2026-09-17-15-51-06 +0000,nypost,Chris Harrison teases dating show return with ...,https://nypost.com/2026/09/17/media/chris-harr...
3,2026-09-17-15-51-00 +0000,wsj,Is Fuel-Export Ban Trump’s Last Option to Ease...,https://www.wsj.com/business/energy-oil/is-fue...
4,2026-09-17-15-42-39 +0000,bbc,Helen Jenner likely to take over as Reform Wal...,https://www.bbc.co.uk/news/articles/cqgk52xjd0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2354/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
12      trump     48
255       fed     34
260     rates     24
294  interest     21
189     house     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
302,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...,214
235,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...,182
234,2026-09-17-00-59-00 +0000,wapo,Trump says he told Fed chief to ‘do what you w...,https://www.washingtonpost.com/business/2026/0...,164
140,2026-09-17-11-00-00 +0000,wsj,The trillion-dollar question: Did Fed Chairman...,https://www.wsj.com/politics/policy/the-trilli...,158
379,2026-09-16-18-02-32 +0000,nypost,Fed hikes interest rates for first time in thr...,https://nypost.com/2026/09/16/business/fed-hik...,156

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
302,214,2026-09-16-21-15-02 +0000,nypost,Trump defends Fed chair Kevin Warsh after inte...,https://nypost.com/2026/09/16/us-news/trump-re...
235,94,2026-09-17-00-57-00 +0000,wsj,President Trump said he was standing by Federa...,https://www.wsj.com/economy/central-banking/tr...
345,81,2026-09-16-19-31-00 +0000,wsj,White House chief of staff Susie Wiles said We...,https://www.wsj.com/politics/policy/white-hous...
145,76,2026-09-17-10-40-44 +0000,nypost,Mark Carney welcomes proposal for Canada to be...,https://nypost.com/2026/09/17/world-news/mark-...
301,65,2026-09-16-21-16-00 +0000,wsj,"The Fed raised rates, a top Democrat opposes a...",https://www.wsj.com/politics/policy/the-fed-is...
67,56,2026-09-17-13-43-04 +0000,nyt,"As a New Oil Power, China Gains More Sway Over...",https://www.nytimes.com/2026/09/17/business/en...
43,56,2026-09-17-14-23-00 +0000,wsj,House lawmakers are heading home until after t...,https://www.wsj.com/politics/johnson-house-rep...
119,50,2026-09-17-11-38-27 +0000,cbc,UN mission finds 'grounds to believe' U.S. com...,https://www.cbc.ca/news/world/un-report-us-str...
349,45,2026-09-16-19-22-01 +0000,cbc,Fencing goes up around Kennedy Center as activ...,https://www.cbc.ca/news/world/kennedy-center-f...
207,40,2026-09-17-05-21-24 +0000,nypost,Trump expected to hold Iran talks with Gulf le...,https://nypost.com/2026/09/17/us-news/trump-ex...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)