## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-10-09-19 +0000,nypost,Ukraine’s ‘dead cities’ creating an unlikely e...,https://nypost.com/2026/03/09/world-news/ukrai...
1,2026-03-09-10-06-00 +0000,wsj,Hims & Hers Shares Double on Report of Wegovy ...,https://www.wsj.com/health/pharma/hims-hers-sh...
2,2026-03-09-10-05-28 +0000,nypost,Wannabe NYC rep Jack Schlossberg ramps up name...,https://nypost.com/2026/03/09/us-news/jack-sch...
3,2026-03-09-10-05-00 +0000,wsj,Trump Sons Back New Drone Company Targeting Pe...,https://www.wsj.com/politics/national-security...
4,2026-03-09-10-05-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2529/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
105    iran     41
30    trump     24
32      new     23
91      oil     19
110  leader     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
126,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...,133
137,2026-03-08-21-37-50 +0000,nypost,Ayatollah Ali Khamenei’s son Mojtaba Khamenei ...,https://nypost.com/2026/03/08/world-news/mojta...,128
132,2026-03-08-22-06-46 +0000,nyt,"Who Is Mojtaba Khamenei, Iran’s New Supreme Le...",https://www.nytimes.com/2026/03/08/world/middl...,118
124,2026-03-08-22-58-45 +0000,cbc,"What we know about Iran's new supreme leader, ...",https://www.cbc.ca/news/world/mojtaba-khamenei...,118
134,2026-03-08-21-51-48 +0000,bbc,"Who is Mojtaba Khamenei, Iran's new supreme le...",https://www.bbc.com/news/articles/c78xxg05w0zo...,118

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
126,133,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...
4,97,2026-03-09-10-05-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...
15,71,2026-03-09-09-30-00 +0000,wsj,The surge in oil and gasoline prices last week...,https://www.wsj.com/economy/central-banking/is...
194,47,2026-03-08-16-39-17 +0000,nypost,"Gas will be below $3 soon, Energy Secretary Wr...",https://nypost.com/2026/03/08/us-news/gas-will...
78,31,2026-03-09-03-56-54 +0000,wapo,Video appears to show U.S. Tomahawk hit naval ...,https://www.washingtonpost.com/investigations/...
136,31,2026-03-08-21-47-41 +0000,nypost,Gavin Newsom plans to use $19M of your cash to...,https://nypost.com/2026/03/08/us-news/gov-news...
43,27,2026-03-09-08-26-25 +0000,nypost,DHS slams Democrats for holding travelers ‘hos...,https://nypost.com/2026/03/09/us-news/departme...
139,26,2026-03-08-21-00-00 +0000,startribune,DVS wants you to pick the tune you like while ...,https://www.startribune.com/dvs-is-asking-you-...
167,24,2026-03-08-18-32-37 +0000,bbc,Explosion at US embassy in Oslo may have been ...,https://www.bbc.com/news/articles/c5yjegg892lo...
216,24,2026-03-08-12-11-40 +0000,nypost,"‘Toxic’ black rain pours down on Tehran, massi...",https://nypost.com/2026/03/08/world-news/black...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)