## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-14-06-32-46 +0000,bbc,"A bin, a Fox and a fish finger: The candidates...",https://www.bbc.co.uk/news/articles/crlw69p6ly...
1,2026-07-14-05-55-56 +0000,nyt,"Live Updates: U.S. Strikes Iran for 3rd Night,...",https://www.nytimes.com/live/2026/07/13/world/...
2,2026-07-14-05-50-00 +0000,wsj,U.S. Treasury Yields Rise as Oil Price Moves H...,https://www.wsj.com/finance/investing/jgbs-mix...
3,2026-07-14-05-43-00 +0000,wsj,Ericsson Cautions on Lower Profitability Due t...,https://www.wsj.com/business/earnings/ericsson...
4,2026-07-14-05-31-03 +0000,bbc,Pop-up free school uniform and prom dress stall,https://www.bbc.co.uk/news/articles/c8628n87w7...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2560/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
192    trump     32
10      iran     29
418   graham     26
464  lindsey     23
51     death     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...,172
304,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...,142
76,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...,142
247,2026-07-13-15-12-21 +0000,nypost,Sen. Lindsey Graham’s sister Darline reacts to...,https://nypost.com/2026/07/13/us-news/lindsey-...,134
108,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...,128

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,172,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...
108,96,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...
233,78,2026-07-13-16-10-10 +0000,nypost,California’s war on Paramount ramps up as stat...,https://nypost.com/2026/07/13/business/califor...
76,62,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...
304,57,2026-07-13-09-53-00 +0000,wsj,Sen. Lindsey Graham’s death adds to the challe...,https://www.wsj.com/politics/policy/what-linds...
18,53,2026-07-14-03-47-41 +0000,bbc,Death toll from Bangkok bar fire rises to 30 a...,https://www.bbc.co.uk/news/articles/clyxyzlp9p...
99,46,2026-07-13-22-05-25 +0000,nyt,"Sam Neill, New Zealand Actor Known for ‘Jurass...",https://www.nytimes.com/2026/07/13/movies/sam-...
208,42,2026-07-13-17-17-01 +0000,nypost,"Dow slides, oil rises to nearly $80 a barrel o...",https://nypost.com/2026/07/13/business/dow-sli...
242,42,2026-07-13-15-45-32 +0000,nypost,Suspect in murder of NY mom Jamey Carney had m...,https://nypost.com/2026/07/13/world-news/suspe...
41,37,2026-07-14-01-50-48 +0000,bbc,Colombian national killed by ICE agent during ...,https://www.bbc.co.uk/news/articles/c2ly580kxn...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)