## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-17-18-01-22 +0000,nyt,Starmer Fires Senior U.K. Civil Servant Over M...,https://www.nytimes.com/2026/04/17/world/europ...
1,2026-04-17-17-59-36 +0000,nyt,Reed Hastings Will Leave Netflix as Board Chai...,https://www.nytimes.com/2026/04/16/business/me...
2,2026-04-17-17-57-19 +0000,nyt,Iran War Live Updates: Tehran Declares Strait ...,https://www.nytimes.com/live/2026/04/17/world/...
3,2026-04-17-17-54-30 +0000,nyt,Europe Still Wants to Reopen the Strait of Hor...,https://www.nytimes.com/live/2026/04/17/world/...
4,2026-04-17-17-51-52 +0000,nyt,Trump Is Urged to Act on Iranian Site Feared I...,https://www.nytimes.com/2026/04/17/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2554/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     44
14    iran     37
15     war     20
79     new     19
124  house     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
2,2026-04-17-17-57-19 +0000,nyt,Iran War Live Updates: Tehran Declares Strait ...,https://www.nytimes.com/live/2026/04/17/world/...,138
217,2026-04-17-03-38-46 +0000,nyt,Trump Promotes ‘No Tax on Tips’ in Las Vegas a...,https://www.nytimes.com/2026/04/16/us/politics...,124
208,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...,124
338,2026-04-16-19-34-42 +0000,nyt,House Again Thwarts Challenge to Trump’s Autho...,https://www.nytimes.com/2026/04/16/us/politics...,123
65,2026-04-17-15-59-41 +0000,nyt,Strait of Hormuz Is Open During Cease-Fire in ...,https://www.nytimes.com/2026/04/17/world/middl...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
2,138,2026-04-17-17-57-19 +0000,nyt,Iran War Live Updates: Tehran Declares Strait ...,https://www.nytimes.com/live/2026/04/17/world/...
208,80,2026-04-17-07-14-38 +0000,nypost,Israel-Lebanon 10-day cease-fire begins after ...,https://nypost.com/2026/04/17/world-news/israe...
220,76,2026-04-17-02-37-00 +0000,wsj,A judge’s ruling halting construction on Presi...,https://www.wsj.com/politics/policy/trump-fume...
103,55,2026-04-17-14-54-56 +0000,nyt,New York New Jersey Stadium? Why MetLife Is Ch...,https://www.nytimes.com/2026/04/17/nyregion/fi...
315,52,2026-04-16-20-48-00 +0000,wsj,President Trump says he will nominate Dr. Eric...,https://www.wsj.com/politics/policy/trump-says...
51,51,2026-04-17-16-26-14 +0000,bbc,Oil prices plunge as Iran says Strait of Hormu...,https://www.bbc.com/news/articles/ckg045z73z1o...
364,42,2026-04-16-18-16-24 +0000,nypost,Europe could run out of jet fuel in 6 weeks — ...,https://nypost.com/2026/04/16/world-news/europ...
176,38,2026-04-17-10-00-00 +0000,latimes,Powerful California institutions backed Swalwe...,https://www.latimes.com/california/story/2026-...
207,38,2026-04-17-07-39-00 +0000,wsj,"Todd Lyons, the acting director of ICE who ove...",https://www.wsj.com/politics/policy/ice-acting...
164,38,2026-04-17-10-46-15 +0000,nypost,UK PM Keir Starmer under pressure to quit over...,https://nypost.com/2026/04/17/world-news/uk-pm...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)