## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-19-00-17 +0000,missionlocal,Endorsers flock to Gary McCoy following Manny ...,https://missionlocal.org/2026/10/sf-endorsemen...
1,2026-10-05-18-59-10 +0000,nypost,"California boy, 13, left in grim condition aft...",https://nypost.com/2026/10/05/us-news/socal-bo...
2,2026-10-05-18-52-19 +0000,wapo,Hundreds of French schools shut as students re...,https://www.washingtonpost.com/world/2026/10/0...
3,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...
4,2026-10-05-18-47-01 +0000,chitri,Lawyers for Chicago woman shot by Border Patro...,https://www.chicagotribune.com/2026/10/05/mari...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2540/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
38        new     27
58   election     22
250     house     18
63      trump     16
91         de     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,87
44,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,84
65,2026-10-05-17-21-49 +0000,nypost,‘Cornell 7’ frat bro who informed pals they co...,https://nypost.com/2026/10/05/us-news/cornell-...,79
229,2026-10-05-10-21-41 +0000,nyt,Will Midterm Elections Complicate the Supreme ...,https://www.nytimes.com/video/us/1000000111847...,78
217,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,87,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...
44,84,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
302,73,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...
158,63,2026-10-05-14-24-08 +0000,wapo,Former White House press secretary Karoline Le...,https://www.washingtonpost.com/business/2026/1...
348,56,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...
357,54,2026-10-04-19-56-00 +0000,wsj,Americans are facing a multifront squeeze from...,https://www.wsj.com/politics/elections/energy-...
39,52,2026-10-05-17-51-56 +0000,nypost,‘Cornell 7’ frat bro claims he was too wasted ...,https://nypost.com/2026/10/05/us-news/cornell-...
197,50,2026-10-05-12-17-25 +0000,wapo,"Spain’s Pedro Sánchez, main critic of Trump in...",https://www.washingtonpost.com/world/2026/10/0...
105,50,2026-10-05-15-59-57 +0000,nypost,"Florida high schooler killed, 40 injured in sc...",https://nypost.com/2026/10/05/us-news/florida-...
323,43,2026-10-04-23-23-39 +0000,nypost,"Boy, 15, arrested after being caught on video ...",https://nypost.com/2026/10/04/world-news/boy-1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)