## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-01-17-10-00 +0000,wsj,President Trump threatened to push for legisla...,https://www.wsj.com/politics/policy/trump-says...
1,2026-08-01-17-07-46 +0000,bbc,Call for 'full review' as pressure grows on In...,https://www.bbc.co.uk/sport/football/articles/...
2,2026-08-01-17-04-38 +0000,nypost,California concertgoer dies after festival bra...,https://nypost.com/2026/08/01/us-news/warped-t...
3,2026-08-01-17-01-03 +0000,nypost,Heartbreaking update in search for Netflix sta...,https://nypost.com/2026/08/01/world-news/netfl...
4,2026-08-01-16-57-25 +0000,nypost,NYPD detective shot in standoff says he wanted...,https://nypost.com/2026/08/01/us-news/shot-nyc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2372/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
1       trump     32
186     ceuta     15
150  migrants     13
95      spain     13
82       iran     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
267,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...,74
192,2026-07-31-22-19-00 +0000,wsj,Trump Orders Fresh Attack Against Iran as War ...,https://www.wsj.com/world/middle-east/trump-so...,67
195,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...,66
243,2026-07-31-20-24-55 +0000,nypost,"Trump backs $1.776B anti-weaponization fund, m...",https://nypost.com/2026/07/31/us-news/trump-st...,63
283,2026-07-31-18-16-45 +0000,nypost,Trump warns migrant ‘catastrophe’ in Spain wou...,https://nypost.com/2026/07/31/world-news/trump...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
267,74,2026-07-31-19-10-16 +0000,nyt,Trump’s Gaza Deal Sparks Questions on Whether ...,https://www.nytimes.com/2026/07/31/world/middl...
75,57,2026-08-01-12-04-46 +0000,bbc,Watch: Tens of thousands of migrants enter Spa...,https://www.bbc.co.uk/news/videos/cnvnml1pen6o...
209,57,2026-07-31-21-33-06 +0000,nypost,Jeanine Pirro drops Reflecting Pool vandalism ...,https://nypost.com/2026/07/31/us-news/jeanine-...
195,54,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...
207,54,2026-07-31-21-40-18 +0000,nypost,FIFA has scrapped $20B World Cup sell-off plan...,https://nypost.com/2026/07/31/business/fifa-ha...
50,44,2026-08-01-14-34-53 +0000,nyt,"Nirmal Purja, Renowned Mountaineer, Is Found D...",https://www.nytimes.com/2026/08/01/world/asia/...
213,40,2026-07-31-21-23-25 +0000,nypost,Fed-up Spaniards lash out at socialist prime m...,https://nypost.com/2026/07/31/world-news/fed-u...
130,33,2026-08-01-03-39-37 +0000,nypost,GOP gov hopeful Bruce Blakeman rips Mamdani ov...,https://nypost.com/2026/07/31/us-news/gop-gov-...
212,30,2026-07-31-21-24-57 +0000,nypost,Woke California college students force school ...,https://nypost.com/2026/07/31/us-news/ucsd-end...
0,28,2026-08-01-17-10-00 +0000,wsj,President Trump threatened to push for legisla...,https://www.wsj.com/politics/policy/trump-says...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)