## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-27-10-55-00 +0000,wsj,Centene Lifts 2026 Guidance Amid Medicare Cost...,https://www.wsj.com/business/earnings/centene-...
1,2026-10-27-10-55-00 +0000,wsj,Xi Wants to Play Peacemaker. Trump Has Other I...,https://www.wsj.com/world/china/xi-wants-to-pl...
2,2026-10-27-10-55-00 +0000,missionlocal,Restaurant review: The Old Clam House in Bayview,https://missionlocal.org/2026/10/restaurant-re...
3,2026-10-27-10-53-33 +0000,nypost,White House defends Trump after archbishop cal...,https://nypost.com/2026/10/27/us-news/white-ho...
4,2026-10-27-10-51-00 +0000,wsj,California’s billionaire-tax vote could offer ...,https://www.wsj.com/politics/policy/california...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
10       trump     37
149   election     26
200  anthropic     17
244        new     17
704     brazil     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
231,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...,109
276,2026-10-26-18-40-02 +0000,nyt,Trump’s Election Attacks Enter New Pre-emptive...,https://www.nytimes.com/2026/10/25/us/politics...,90
134,2026-10-27-02-07-13 +0000,nypost,Trump doubles down on Obama criticism as his v...,https://nypost.com/2026/10/26/us-news/trump-do...,85
152,2026-10-27-00-45-27 +0000,nyt,How Lula’s Social Media Campaign Helped Him Wi...,https://www.nytimes.com/2026/10/26/world/ameri...,85
323,2026-10-26-15-10-00 +0000,wsj,Allies worry Senate Majority Leader John Thune...,https://www.wsj.com/politics/elections/a-bruis...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
231,109,2026-10-26-20-27-40 +0000,nypost,Trump offers $1M for voter fraud reports 8 day...,https://nypost.com/2026/10/26/us-news/trump-of...
384,80,2026-10-26-11-04-00 +0000,wsj,Former President Barack Obama was back on the ...,https://www.wsj.com/politics/policy/obama-camp...
304,73,2026-10-26-16-51-12 +0000,nypost,Pro-Abdul El-Sayed ad sparks fury with false c...,https://nypost.com/2026/10/26/us-news/pro-abdu...
360,62,2026-10-26-13-26-07 +0000,chitri,Anthropic files for potentially the biggest IP...,https://www.chicagotribune.com/2026/10/26/anth...
188,55,2026-10-26-21-53-41 +0000,nypost,Ex-FBI Director James Comey facing new crimina...,https://nypost.com/2026/10/26/us-news/ex-fbi-d...
347,43,2026-10-26-14-13-00 +0000,wsj,Dozens of data-center projects have already be...,https://www.wsj.com/politics/elections/the-fou...
41,42,2026-10-27-10-00-00 +0000,wsj,Fed Chairman Kevin Warsh wants to stop preview...,https://www.wsj.com/economy/central-banking/ke...
163,41,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...
164,38,2026-10-26-23-45-35 +0000,nypost,Embattled Ilhan Omar tells lefty antisemitic s...,https://nypost.com/2026/10/26/us-news/ilhan-om...
127,37,2026-10-27-02-40-17 +0000,bbc,Jordan carries out deadly strike in Syria in r...,https://www.bbc.co.uk/news/articles/cq8ezg6dy6...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)