## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-26-11-47-55 +0000,nypost,Notorious NYC cannibal ‘Butcher of Tompkins Sq...,https://nypost.com/2026/09/26/us-news/notoriou...
1,2026-09-26-11-39-43 +0000,nyt,At Least 4 Dead After Explosion in Athens Tour...,https://www.nytimes.com/2026/09/25/world/europ...
2,2026-09-26-11-22-03 +0000,bbc,How long can Labour's feel-good factor last?,https://www.bbc.co.uk/news/articles/cwn8mn0rzk...
3,2026-09-26-11-00-00 +0000,nypost,Dolly Parton’s $450M estate is being decided —...,https://nypost.com/2026/09/26/entertainment/do...
4,2026-09-26-11-00-00 +0000,missionlocal,Leather bars have a bone to pick with Meta’s m...,https://missionlocal.org/2026/09/lgbtq-busines...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2552/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
189  trump     67
253    new     21
666  court     21
379     xi     19
402  house     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
80,2026-09-26-01-50-38 +0000,nypost,Trump rejects Iran’s 7-day cease-fire proposal...,https://nypost.com/2026/09/25/us-news/trump-re...,217
75,2026-09-26-02-27-24 +0000,nypost,CNN left off Air Force One for Trump’s trip to...,https://nypost.com/2026/09/25/us-news/cnn-left...,167
284,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...,155
259,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...,147
242,2026-09-25-18-26-18 +0000,nypost,White House plays ‘Les Miserables’ hit censore...,https://nypost.com/2026/09/25/us-news/white-ho...,145

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
80,217,2026-09-26-01-50-38 +0000,nypost,Trump rejects Iran’s 7-day cease-fire proposal...,https://nypost.com/2026/09/25/us-news/trump-re...
284,88,2026-09-25-16-36-14 +0000,nypost,Supreme Court lets Trump admin use federal dat...,https://nypost.com/2026/09/25/us-news/supreme-...
259,80,2026-09-25-17-42-00 +0000,wsj,President Trump hosted an elaborate state dinn...,https://www.wsj.com/politics/policy/trump-xi-d...
82,69,2026-09-26-01-40-00 +0000,wsj,CNN said it was pulled from a planned trip wit...,https://www.wsj.com/politics/policy/white-hous...
305,48,2026-09-25-15-49-16 +0000,chitri,Chicago City Council approves campaign ethics ...,https://www.chicagotribune.com/2026/09/25/chic...
71,43,2026-09-26-02-39-46 +0000,nypost,Wild moment cop drags woman out of California ...,https://nypost.com/2026/09/25/us-news/tulare-c...
257,43,2026-09-25-17-49-46 +0000,latimes,Suspect bites off piece of police dog's ear du...,https://www.latimes.com/california/story/2026-...
48,40,2026-09-26-07-03-34 +0000,nypost,Ukraine’s Zelensky says he urged Trump to enli...,https://nypost.com/2026/09/26/world-news/ukrai...
312,37,2026-09-25-15-38-16 +0000,nyt,Fed Faces Prospect of Another Interest Rate In...,https://www.nytimes.com/2026/09/25/business/fe...
334,36,2026-09-25-13-48-29 +0000,cbc,AI's 'paradise of machines' a threat to humani...,https://www.cbc.ca/news/world/pope-leo-ai-fran...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)