## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-06-48-00 +0000,wsj,Brent Crude Could Surge Toward $140/bbl in ‘Ac...,https://www.wsj.com/finance/commodities-future...
1,2026-03-09-06-42-54 +0000,nyt,"Oil Prices Spike Over $110 a Barrel, Highest S...",https://www.nytimes.com/2026/03/08/business/en...
2,2026-03-09-06-38-09 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/09/world/...
3,2026-03-09-06-32-00 +0000,wsj,A New Generation of Mall Rats Has Arrived,https://www.wsj.com/business/retail/gen-z-shop...
4,2026-03-09-06-32-00 +0000,wsj,Opinion | Abandoned Mines Can Become Data Centers,https://www.wsj.com/opinion/abandoned-mines-ca...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2606/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
44     iran     46
226   trump     24
45      war     17
18      new     16
121  leader     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...,136
95,2026-03-08-21-37-50 +0000,nypost,Ayatollah Ali Khamenei’s son Mojtaba Khamenei ...,https://nypost.com/2026/03/08/world-news/mojta...,131
171,2026-03-08-12-18-51 +0000,cbc,Iran names Khamenei's son Mojtaba as new supre...,https://www.cbc.ca/news/world/livestory/iran-i...,131
143,2026-03-08-17-06-53 +0000,latimes,Khamenei's son is selected as Iran's supreme l...,https://www.latimes.com/politics/story/2026-03...,118
90,2026-03-08-22-06-46 +0000,nyt,"Who Is Mojtaba Khamenei, Iran’s New Supreme Le...",https://www.nytimes.com/2026/03/08/world/middl...,115

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,136,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...
40,53,2026-03-09-02-23-23 +0000,nypost,California Republicans suggest Trump could ste...,https://nypost.com/2026/03/08/us-news/republic...
151,45,2026-03-08-16-39-17 +0000,nypost,"Gas will be below $3 soon, Energy Secretary Wr...",https://nypost.com/2026/03/08/us-news/gas-will...
167,36,2026-03-08-13-41-34 +0000,nypost,New Nepali party led by ex-rapper is set for l...,https://nypost.com/2026/03/08/world-news/new-n...
110,32,2026-03-08-19-34-44 +0000,nypost,Inside major sports business exec’s harrowing ...,https://nypost.com/2026/03/08/business/inside-...
63,28,2026-03-09-00-22-29 +0000,nypost,Bomb-making paraphernalia found in car near wh...,https://nypost.com/2026/03/08/us-news/bomb-mak...
142,28,2026-03-08-17-07-27 +0000,nypost,Furious Californians slam Gavin Newsom’s steal...,https://nypost.com/2026/03/08/us-news/californ...
73,27,2026-03-08-23-32-56 +0000,latimes,"Gate to Rihanna's home, an RV hit by bullets a...",https://www.latimes.com/california/story/2026-...
15,25,2026-03-09-05-07-36 +0000,nypost,US military tests on secret weapon bought from...,https://nypost.com/2026/03/09/us-news/us-milit...
190,23,2026-03-08-09-30-00 +0000,wsj,The economy has seen an ugly week with the Ira...,https://www.wsj.com/economy/why-the-oil-shock-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)