## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-20-55-48 +0000,nyt,"Pope Leo Has Lung Cancer, Vatican Says",https://www.nytimes.com/2026/10/13/world/europ...
1,2026-10-13-20-55-29 +0000,chitri,"To spur housing growth, Chicago must attack pr...",https://www.chicagotribune.com/2026/10/13/chic...
2,2026-10-13-20-55-04 +0000,startribune,Pope Leo XIV diagnosed with lung cancer after ...,https://www.startribune.com/pope-leo-xiv-is-se...
3,2026-10-13-20-53-00 +0000,wsj,Pope Leo Diagnosed with Lung Cancer After Surgery,https://www.wsj.com/world/pope-leo-diagnosed-w...
4,2026-10-13-20-51-51 +0000,nyt,Police Identify 42-Year Old Man Killed at Six ...,https://www.nytimes.com/2026/10/12/us/roller-c...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2614/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
374      trump     36
594         he     15
66         new     15
31    kimberly     14
32   guilfoyle     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
341,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,124
179,2026-10-13-14-06-53 +0000,nypost,Trump humiliatingly forces Kimberly Guilfoyle ...,https://nypost.com/2026/10/13/us-news/trump-as...,112
133,2026-10-13-16-19-00 +0000,wsj,Kimberly Guilfoyle resigned as U.S. ambassador...,https://www.wsj.com/politics/policy/kimberly-g...,102
150,2026-10-13-15-52-41 +0000,chitri,"Katie Zacharia, Trump’s new White House press ...",https://www.chicagotribune.com/2026/10/13/kati...,96
357,2026-10-12-22-55-42 +0000,nypost,New White House press secretary Katie Zacharia...,https://nypost.com/2026/10/12/us-news/new-whit...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
341,124,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...
231,65,2026-10-13-11-12-24 +0000,chitri,Vatican says Pope Leo XIV has lung cancer and ...,https://www.chicagotribune.com/2026/10/13/pope...
337,63,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
151,54,2026-10-13-15-52-15 +0000,bbc,"MI5 chief warns of threats to UK from Russia, ...",https://www.bbc.co.uk/news/articles/c60rl5vwpk...
198,52,2026-10-13-13-12-18 +0000,wapo,Six Flags shuts roller coasters at six parks a...,https://www.washingtonpost.com/business/2026/1...
91,50,2026-10-13-18-10-00 +0000,wsj,The big-donor group aligned with Senate Republ...,https://www.wsj.com/politics/elections/republi...
88,48,2026-10-13-18-20-27 +0000,nypost,House Dem pushes bill to abolish Homeland Secu...,https://nypost.com/2026/10/13/us-news/house-de...
181,43,2026-10-13-14-00-00 +0000,wsj,Home sales in September rose for the first tim...,https://www.wsj.com/economy/housing/home-sales...
238,43,2026-10-13-10-41-00 +0000,wsj,Medicare for All has become a defining policy ...,https://www.wsj.com/politics/policy/medicare-f...
223,40,2026-10-13-11-48-06 +0000,nypost,Ukraine got no warning about latest Russian st...,https://nypost.com/2026/10/13/world-news/ukrai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)