## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-23-11-47-30 +0000,nyt,Trump’s Diesel Dilemma,https://www.nytimes.com/2026/09/23/business/de...
1,2026-09-23-11-46-37 +0000,nyt,Trump Once Vowed to ‘Own’ Greenland. He Settle...,https://www.nytimes.com/2026/09/22/us/politics...
2,2026-09-23-11-45-46 +0000,wapo,"To answer far-right surge, Mamdani and Spain’s...",https://www.washingtonpost.com/world/2026/09/2...
3,2026-09-23-11-44-21 +0000,nypost,Bryan Kohberger didn’t understand what he was ...,https://nypost.com/2026/09/23/us-news/bryan-ko...
4,2026-09-23-11-42-52 +0000,bbc,Tigray forces seize main airport in northern E...,https://www.bbc.co.uk/news/articles/cry8zwwq21...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2461/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     91
103   iran     30
105    new     24
195   will     20
7       he     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
331,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...,211
144,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...,210
146,2026-09-23-01-57-25 +0000,nyt,Trump Threatens Annihilation in Iran in UN Spe...,https://www.nytimes.com/2026/09/22/us/politics...,196
230,2026-09-22-21-44-00 +0000,wsj,Delegates from Iran and Cuba walked out during...,https://www.wsj.com/politics/policy/trump-thre...,191
365,2026-09-22-16-56-04 +0000,nypost,Cuba and Iran delegations walk out of Trump’s ...,https://nypost.com/2026/09/22/us-news/cuba-and...,188

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
331,211,2026-09-22-18-19-13 +0000,nypost,Gulf states will urge Trump not to escalate Ir...,https://nypost.com/2026/09/22/world-news/gulf-...
138,89,2026-09-23-02-43-54 +0000,nypost,Trump has tense exchange with CNN’s Kaitlan Co...,https://nypost.com/2026/09/22/us-news/trump-ha...
103,82,2026-09-23-07-07-20 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
28,79,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
144,75,2026-09-23-02-24-00 +0000,wsj,President Trump labeled himself a man of peace...,https://www.wsj.com/politics/policy/trump-tell...
96,53,2026-09-23-08-00-00 +0000,cbc,Trump is hailing his new deal with Greenland a...,https://www.cbc.ca/news/world/trump-greenland-...
113,52,2026-09-23-05-51-57 +0000,nypost,Texas man charged with capital murder after 5-...,https://nypost.com/2026/09/23/us-news/texas-ma...
171,45,2026-09-23-00-00-00 +0000,wsj,HHS moved money from a minority health office ...,https://www.wsj.com/politics/policy/rfk-jr-hhs...
37,43,2026-09-23-10-18-00 +0000,wsj,Dollar Jumps to 8-Week High as Fed Rate-Hike B...,https://www.wsj.com/economy/central-banking/do...
97,43,2026-09-23-08-00-00 +0000,cbc,"'Nuclear' threat or market boom? Either way, A...",https://www.cbc.ca/news/world/donald-trump-xi-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)