## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-08-17-16-38 +0000,nypost,Nintendo hiking Switch 2 prices by hefty amoun...,https://nypost.com/2026/05/08/business/nintend...
1,2026-05-08-17-15-55 +0000,startribune,Sanford Health merging with North Memorial as ...,https://www.startribune.com/sanford-health-mer...
2,2026-05-08-17-14-41 +0000,nypost,Phony Christian missionary who preached ‘nudit...,https://nypost.com/2026/05/08/us-news/christia...
3,2026-05-08-17-13-14 +0000,nyt,Live Updates: U.K. Local Election Results Poin...,https://www.nytimes.com/live/2026/05/08/world/...
4,2026-05-08-17-13-12 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/08/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
50        trump     40
71         iran     28
81   hantavirus     19
147       court     18
120         new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,138
294,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...,130
366,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...,114
273,2026-05-07-23-51-58 +0000,nypost,Trump downplays US-Iran attacks as ‘love tap’ ...,https://nypost.com/2026/05/07/world-news/trump...,110
262,2026-05-08-00-39-56 +0000,wapo,Court rules against the tariff Trump enacted a...,https://www.washingtonpost.com/business/2026/0...,98

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,138,2026-05-08-15-43-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
131,93,2026-05-08-13-12-34 +0000,nyt,Shell Reports Nearly $7 Billion Profit After O...,https://www.nytimes.com/2026/05/07/business/sh...
300,79,2026-05-07-22-08-00 +0000,wsj,The Centers for Disease Control and Prevention...,https://www.wsj.com/politics/policy/cdc-coordi...
161,64,2026-05-08-11-43-45 +0000,nypost,UK PM Keir Starmer says he won’t resign after ...,https://nypost.com/2026/05/08/world-news/uk-pr...
343,46,2026-05-07-20-52-12 +0000,nypost,Argentina will start testing rats for hantavir...,https://nypost.com/2026/05/07/world-news/argen...
294,44,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...
96,42,2026-05-08-14-46-14 +0000,bbc,Reform election gains show historic shift in B...,https://www.bbc.com/news/articles/c0r255xlr59o...
273,42,2026-05-07-23-51-58 +0000,nypost,Trump downplays US-Iran attacks as ‘love tap’ ...,https://nypost.com/2026/05/07/world-news/trump...
35,39,2026-05-08-16-28-00 +0000,wsj,"The U.S. added 115,000 jobs in April, the Labo...",https://www.wsj.com/economy/jobs/april-jobs-re...
250,36,2026-05-08-01-34-04 +0000,latimes,California tech company Cloudflare to lay off ...,https://www.latimes.com/business/story/2026-05...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)