## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-04-21-09-23 +0000,nypost,"68% of NYC residents are proud to be American,...",https://nypost.com/2026/07/04/us-news/68-of-ny...
1,2026-07-04-21-07-00 +0000,wsj,Thousands of people were at the National Mall ...,https://www.wsj.com/politics/policy/july-4-250...
2,2026-07-04-21-04-59 +0000,nyt,"Democrats Clash With Trump, as Political Tensi...",https://www.nytimes.com/2026/07/04/us/politics...
3,2026-07-04-20-50-56 +0000,nypost,California fruit farmer reveals results of his...,https://nypost.com/2026/07/04/us-news/californ...
4,2026-07-04-20-44-42 +0000,nyt,Momentary Unity at a Funeral Masks Deep Divisi...,https://www.nytimes.com/2026/07/04/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2507/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
25     trump     26
22   america     17
109     july     17
29        th     16
43   funeral     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
60,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...,103
82,2026-07-04-11-43-17 +0000,nyt,"Will Iran’s New Supreme Leader, Mojtaba Khamen...",https://www.nytimes.com/2026/07/04/world/middl...,76
2,2026-07-04-21-04-59 +0000,nyt,"Democrats Clash With Trump, as Political Tensi...",https://www.nytimes.com/2026/07/04/us/politics...,69
143,2026-07-04-02-27-34 +0000,cbc,Trump promises 'really long' Fourth of July sp...,https://www.cbc.ca/player/play/9.7258442?cmp=rss,68
142,2026-07-04-02-41-24 +0000,nypost,White House spoofs Taylor Swift and Travis Kel...,https://nypost.com/2026/07/03/us-news/white-ho...,68

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
60,103,2026-07-04-15-40-31 +0000,nypost,Trump says Iran gets ‘week off’ for lengthy fu...,https://nypost.com/2026/07/04/world-news/trump...
25,64,2026-07-04-19-44-42 +0000,nypost,Sailing through history: My firsthand experien...,https://nypost.com/2026/07/04/us-news/ny-post-...
133,47,2026-07-04-04-50-06 +0000,bbc,Watch: Taylor Swift and Travis Kelce wed in NY...,https://www.bbc.co.uk/news/videos/cewqpdgqj0ko...
160,37,2026-07-04-00-00-00 +0000,wsj,Capital Account: The 250th anniversary of the ...,https://www.wsj.com/economy/american-instituti...
87,34,2026-07-04-11-00-00 +0000,latimes,July Fourth fireworks may bring 'hazardous' ai...,https://www.latimes.com/science/story/2026-07-...
1,33,2026-07-04-21-07-00 +0000,wsj,Thousands of people were at the National Mall ...,https://www.wsj.com/politics/policy/july-4-250...
134,29,2026-07-04-04-45-00 +0000,wsj,President Trump spoke in front of Mount Rushmo...,https://www.wsj.com/us-news/donald-trump-mount...
77,27,2026-07-04-12-17-22 +0000,nypost,New Thomas Jefferson statue shipped to White H...,https://nypost.com/2026/07/04/us-news/new-thom...
132,25,2026-07-04-05-25-47 +0000,nypost,Iranians chant ‘Death to America’ as crowds mo...,https://nypost.com/2026/07/04/us-news/iranians...
107,23,2026-07-04-09-30-00 +0000,wsj,Modern warfare is forcing a convergence betwee...,https://www.wsj.com/politics/national-security...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)