## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-11-19-12-54 +0000,bbc,Luigi Mangione murder trial to have anonymous ...,https://www.bbc.co.uk/news/articles/cgje05wd1v...
1,2026-08-11-19-12-21 +0000,nyt,University of Michigan Will Ease Up on Grades ...,https://www.nytimes.com/2026/08/11/us/universi...
2,2026-08-11-19-11-35 +0000,nyt,Ocasio-Cortez Opened Up About Freezing her Egg...,https://www.nytimes.com/2026/08/11/us/politics...
3,2026-08-11-19-11-05 +0000,startribune,Watching Minnesota sports has gotten complicat...,https://www.startribune.com/minnesota-sports-t...
4,2026-08-11-19-10-57 +0000,nypost,Mamdani blames his staff after NYPD denies NYC...,https://nypost.com/2026/08/11/us-news/zohran-m...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2336/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
68       trump     51
209        new     30
260         ai     16
66        iran     16
168  president     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
57,2026-08-11-17-14-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...,179
97,2026-08-11-16-13-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...,158
265,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...,132
268,2026-08-11-02-00-00 +0000,wsj,Iran’s Mysterious Ruler Signals a Hard Line on...,https://www.wsj.com/world/middle-east/irans-my...,107
124,2026-08-11-15-22-12 +0000,wapo,Trump’s secret Air Force One switch crosses a ...,https://www.washingtonpost.com/business/2026/0...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
57,179,2026-08-11-17-14-00 +0000,wsj,President Trump said he is reviewing whether h...,https://www.wsj.com/politics/trump-threatens-t...
265,81,2026-08-11-02-46-21 +0000,nypost,Trump snuck off Air Force One in catering truc...,https://nypost.com/2026/08/10/us-news/trump-sn...
284,65,2026-08-11-01-00-00 +0000,wsj,Democratic Socialist Francesca Hong’s Wisconsi...,https://www.wsj.com/politics/elections/democra...
226,58,2026-08-11-09-27-28 +0000,nypost,Ex-Syrian ruler Bashar al-Assad sentenced to d...,https://nypost.com/2026/08/11/world-news/ex-sy...
324,54,2026-08-10-21-47-00 +0000,wsj,"Nvidia, Wall Street Firms Strike AI Financing ...",https://www.wsj.com/business/deals/nvidia-wall...
97,45,2026-08-11-16-13-00 +0000,wsj,President Trump was secretly flown out of Turk...,https://www.wsj.com/politics/national-security...
286,43,2026-08-11-00-53-51 +0000,nypost,"NYC first lady Rama Duwaji traveling to Syria,...",https://nypost.com/2026/08/10/us-news/nyc-firs...
238,43,2026-08-11-08-55-26 +0000,cbc,Colombia quake death toll tops 200 as rescuers...,https://www.cbc.ca/news/world/colombia-earthqu...
149,41,2026-08-11-14-00-00 +0000,wsj,"Home sales fell in July, getting the summer of...",https://www.wsj.com/economy/housing/july-home-...
260,38,2026-08-11-04-19-38 +0000,nyt,"Jake Whisenant, Who Raced Up Yosemite’s El Cap...",https://www.nytimes.com/2026/08/11/us/jake-whi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)