## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-03-01-18-25 +0000,nypost,Judge temporarily blocks Trump administration ...,https://nypost.com/2026/10/02/us-news/judge-te...
1,2026-10-03-01-14-39 +0000,nyt,"Iran Jails Hard-Line Lawmaker, Exposing Deep R...",https://www.nytimes.com/2026/10/02/world/middl...
2,2026-10-03-01-13-43 +0000,startribune,"Live: Moorhead, Forest Lake extend leads; Holy...",https://www.startribune.com/minnesota-high-sch...
3,2026-10-03-01-00-00 +0000,wsj,The Sneaker Taking Over America Was Inspired b...,https://www.wsj.com/business/on-running-shoes-...
4,2026-10-03-01-00-00 +0000,wsj,David Ellison Won Warner Bros. Now he Has to M...,https://www.wsj.com/business/media/david-ellis...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2390/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
3       trump     36
47   flydubai     22
34        was     19
258       new     18
49      pilot     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
345,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...,131
346,2026-10-02-09-08-06 +0000,bbc,'I was not going to let others die' - pilot of...,https://www.bbc.co.uk/news/articles/c639m98gde...,116
336,2026-10-02-09-36-47 +0000,cbc,'I was fighting for my life': Indian pilot hai...,https://www.cbc.ca/news/world/flydubai-pilot-i...,112
303,2026-10-02-11-20-46 +0000,chitri,‘I was fighting for my life’: Indian pilot hai...,https://www.chicagotribune.com/2026/10/02/indi...,112
250,2026-10-02-14-22-23 +0000,nypost,Trump announces Europe will release ‘massive a...,https://nypost.com/2026/10/02/us-news/trump-an...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
345,131,2026-10-02-09-15-31 +0000,nypost,Flydubai pilot Smit Machchhar fought off co-pi...,https://nypost.com/2026/10/02/world-news/flydu...
250,112,2026-10-02-14-22-23 +0000,nypost,Trump announces Europe will release ‘massive a...,https://nypost.com/2026/10/02/us-news/trump-an...
392,78,2026-10-02-02-10-00 +0000,cbc,New York's governor removes district attorney ...,https://www.cbc.ca/news/world/ny-special-prose...
340,68,2026-10-02-09-30-00 +0000,wsj,Heard on the Street: High government debt is a...,https://www.wsj.com/finance/investing/high-gov...
307,68,2026-10-02-11-01-00 +0000,wsj,The WSJ built an AI tool to capture what the c...,https://www.wsj.com/politics/heres-what-our-ai...
115,61,2026-10-02-20-41-00 +0000,wsj,A deep-pocketed group boosting Senate Republic...,https://www.wsj.com/politics/elections/deep-po...
59,47,2026-10-02-22-11-41 +0000,nypost,Bari Weiss’ fate up in the air as Paramount pr...,https://nypost.com/2026/10/02/media/bari-weiss...
198,42,2026-10-02-16-41-45 +0000,nyt,"Black Unemployment Rose Sharply in September, ...",https://www.nytimes.com/2026/10/02/business/ec...
127,41,2026-10-02-20-24-00 +0000,wsj,President Trump is expected to name Director o...,https://www.wsj.com/politics/policy/trump-expe...
324,40,2026-10-02-10-00-00 +0000,latimes,"Hiltzik: Sure, use Meta's Muse bot to help wit...",https://www.latimes.com/business/story/2026-10...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)