## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-28-08-44-00 +0000,wsj,Gold Supported by U.S. Debt Worries,https://www.wsj.com/finance/commodities-future...
1,2026-08-28-08-39-35 +0000,nypost,Five Long Island ‘mole people’ seen crawling i...,https://nypost.com/2026/08/28/us-news/long-isl...
2,2026-08-28-08-39-00 +0000,wsj,U.S. Stock Futures Mixed Ahead of Fed Chair Wa...,https://www.wsj.com/finance/stocks/u-s-stock-f...
3,2026-08-28-08-33-46 +0000,wsj,Stock Market Today: Stock Futures Waver as Inv...,https://www.wsj.com/livecoverage/stock-market-...
4,2026-08-28-08-33-14 +0000,bbc,Nepal army rescues survivors from hydropower t...,https://www.bbc.co.uk/news/videos/cddv0rldqqlo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2525/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
57  trump     54
32  nepal     31
40    new     26
64   lake     21
49    war     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
262,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...,149
256,2026-08-27-17-58-49 +0000,chitri,President Donald Trump signs order renaming La...,https://www.chicagotribune.com/2026/08/27/trum...,147
145,2026-08-27-21-52-39 +0000,wapo,Trump signs order renaming Lake Ontario as Lak...,https://www.washingtonpost.com/politics/2026/0...,144
71,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...,143
125,2026-08-27-23-00-04 +0000,startribune,Trump signs order renaming Lake Ontario as 'La...,https://www.startribune.com/trump-signs-order-...,137

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
262,149,2026-08-27-17-32-27 +0000,nypost,Trump signs executive order renaming Lake Onta...,https://nypost.com/2026/08/27/us-news/trump-or...
46,104,2026-08-28-04-45-46 +0000,nypost,"Several New Yorkers, relatives among the 90 mi...",https://nypost.com/2026/08/28/us-news/several-...
72,78,2026-08-28-02-00-00 +0000,wsj,The U.S.-Canada trade war. The war in Iran. Su...,https://www.wsj.com/economy/global/how-the-ai-...
182,67,2026-08-27-21-03-00 +0000,wsj,Federal investigators said the temporary reloc...,https://www.wsj.com/politics/policy/investigat...
106,64,2026-08-27-23-50-00 +0000,wsj,California has made it easier to file civil cl...,https://www.wsj.com/politics/policy/california...
71,63,2026-08-28-02-14-00 +0000,wsj,The Trump administration for now can’t move fo...,https://www.wsj.com/politics/policy/judge-temp...
324,59,2026-08-27-14-29-00 +0000,wsj,Florida Gov. Ron DeSantis said the use of auto...,https://www.wsj.com/politics/policy/florida-go...
327,54,2026-08-27-14-21-18 +0000,nypost,"Yayoi Kusama, Japanese artist known for her po...",https://nypost.com/2026/08/27/world-news/yayoi...
284,47,2026-08-27-16-45-00 +0000,wsj,Fed Chairman Kevin Warsh takes the stage in Ja...,https://www.wsj.com/economy/central-banking/be...
264,45,2026-08-27-17-20-28 +0000,nypost,Josh Kushner may face subpoenas as UEFA weighs...,https://nypost.com/2026/08/27/business/josh-ku...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)