## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-25-13-51-50 +0000,nypost,Trump demands Arab countries join Abraham Acco...,https://nypost.com/2026/05/25/us-news/presiden...
1,2026-05-25-13-51-00 +0000,wsj,"Iran Talks Bog Down Over Nuclear Program, Sanc...",https://www.wsj.com/world/middle-east/iran-tal...
2,2026-05-25-13-49-57 +0000,nyt,Iran War Live Updates: Top Iranian Negotiators...,https://www.nytimes.com/live/2026/05/25/world/...
3,2026-05-25-13-49-56 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/25/world/...
4,2026-05-25-13-42-14 +0000,bbc,Education secretary to ask competition watchdo...,https://www.bbc.com/news/articles/c4g7d6ngjldo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2564/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
9     iran     30
10    deal     19
0    trump     19
40  prices      8
39     oil      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
203,2026-05-24-14-33-01 +0000,nypost,Trump vows Iran can never have a nuke — and US...,https://nypost.com/2026/05/24/us-news/trump-vo...,84
165,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...,83
178,2026-05-24-18-04-00 +0000,wsj,Trump Says He Is in No Rush for an Iran Deal T...,https://www.wsj.com/world/middle-east/middle-e...,83
2,2026-05-25-13-49-57 +0000,nyt,Iran War Live Updates: Top Iranian Negotiators...,https://www.nytimes.com/live/2026/05/25/world/...,80
0,2026-05-25-13-51-50 +0000,nypost,Trump demands Arab countries join Abraham Acco...,https://nypost.com/2026/05/25/us-news/presiden...,80

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
203,84,2026-05-24-14-33-01 +0000,nypost,Trump vows Iran can never have a nuke — and US...,https://nypost.com/2026/05/24/us-news/trump-vo...
111,35,2026-05-25-02-32-08 +0000,nyt,Gunman in Shooting Near White House Killed in ...,https://www.nytimes.com/2026/05/23/us/politics...
82,34,2026-05-25-08-45-00 +0000,wsj,Global Markets Gain and Oil Prices Retreat as ...,https://www.wsj.com/finance/commodities-future...
165,34,2026-05-24-20-05-50 +0000,nypost,"Trump admin declares ‘no dust, no dollars’ for...",https://nypost.com/2026/05/24/us-news/trump-ad...
145,32,2026-05-24-22-56-21 +0000,latimes,Potential crack found on Garden Grove chemical...,https://www.latimes.com/california/story/2026-...
45,31,2026-05-25-11-01-39 +0000,nypost,"Pope Leo calls for robust regulation of AI, po...",https://nypost.com/2026/05/25/world-news/pope-...
72,30,2026-05-25-09-01-55 +0000,nyt,He Name-Drops Ocasio-Cortez in His Bid for Con...,https://www.nytimes.com/2026/05/25/us/politics...
198,24,2026-05-24-15-45-00 +0000,wsj,Kyiv Suffers One of Ukraine War’s Heaviest Rus...,https://www.wsj.com/world/kyiv-suffers-one-of-...
35,22,2026-05-25-11-30-00 +0000,nypost,Floyd Mayweather sues notorious NYC money mana...,https://nypost.com/2026/05/25/us-news/floyd-ma...
155,22,2026-05-24-21-36-21 +0000,nypost,Cruise cabin door decorations spark fierce rea...,https://nypost.com/2026/05/24/lifestyle/cruise...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)