## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-27-10-15-14 +0000,bbc,Sturgeon defends 'no comment' police interview...,https://www.bbc.com/news/articles/cwy2kww2jzpo...
1,2026-05-27-10-09-00 +0000,wsj,"U.S. Treasury Yields Fall, Dollar Eases on Cau...",https://www.wsj.com/finance/currencies/dollar-...
2,2026-05-27-10-09-00 +0000,wsj,Israel Kills New Hamas Military Chief 11 Days ...,https://www.wsj.com/world/middle-east/israel-k...
3,2026-05-27-10-08-21 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/27/world/...
4,2026-05-27-10-00-00 +0000,nypost,Mamdani’s East Harlem grocery store site alrea...,https://nypost.com/2026/05/27/business/mamdani...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2355/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
55     trump     34
186     iran     32
153    texas     28
21       new     17
193  strikes     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
384,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,132
145,2026-05-27-01-02-25 +0000,nypost,Ken Paxton swamps John Cornyn in Texas GOP Sen...,https://nypost.com/2026/05/26/us-news/ken-paxt...,123
15,2026-05-27-10-00-00 +0000,wsj,President Trump and Democrats rarely find them...,https://www.wsj.com/politics/elections/trump-a...,116
20,2026-05-27-09-52-10 +0000,nyt,Iran War Updates: U.S. Saw Threats From Iran B...,https://www.nytimes.com/live/2026/05/26/world/...,98
211,2026-05-26-21-21-00 +0000,wsj,"Iran’s Dream Deal: Economic Relief, No Trump V...",https://www.wsj.com/business/energy-oil/irans-...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
384,132,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...
108,64,2026-05-27-03-35-00 +0000,wsj,State Attorney General Ken Paxton clinched the...,https://www.wsj.com/politics/elections/paxton-...
37,62,2026-05-27-09-03-26 +0000,nypost,Israel kills new Hamas military chief who was...,https://nypost.com/2026/05/27/world-news/israe...
159,58,2026-05-27-00-07-48 +0000,nypost,Supreme Court denies NFL’s bid to keep former ...,https://nypost.com/2026/05/26/us-news/supreme-...
316,55,2026-05-26-16-37-20 +0000,nypost,Spencer Pratt reveals stunning West Coast dest...,https://nypost.com/2026/05/26/us-news/spencer-...
243,51,2026-05-26-20-17-40 +0000,nyt,Canada Strikes Landmark Deal to Export Liquefi...,https://www.nytimes.com/2026/05/26/world/canad...
188,50,2026-05-26-22-18-28 +0000,nypost,Possible serial killer is latest horror to upe...,https://nypost.com/2026/05/26/world-news/possi...
359,46,2026-05-26-13-30-21 +0000,bbc,Russia ramps up threats against Ukraine. What ...,https://www.bbc.com/news/articles/c3v22ylzpqzo...
215,42,2026-05-26-21-13-12 +0000,nypost,"Starbucks sees sales drop, mass protests in So...",https://nypost.com/2026/05/26/world-news/starb...
117,41,2026-05-27-02-56-32 +0000,nyt,Christian Menefee Defeats Al Green in Texas De...,https://www.nytimes.com/2026/05/26/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)