## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-28-22-53-57 +0000,nypost,‘Die Hard’ actor reveals ‘last straw’ that dro...,https://nypost.com/2026/09/28/us-news/die-hard...
1,2026-09-28-22-50-05 +0000,nypost,Peperoncini jar allegedly containing dead mous...,https://nypost.com/2026/09/28/us-news/californ...
2,2026-09-28-22-49-23 +0000,nypost,OpenAI pulls plug on ‘untrustworthy’ new AI mo...,https://nypost.com/2026/09/28/tech/openai-pull...
3,2026-09-28-22-46-00 +0000,wsj,Trump Unveils $15 Billion Iowa Steel Project,https://www.wsj.com/politics/trump-to-unveil-p...
4,2026-09-28-22-46-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
32     trump     38
25       new     21
136       uk     14
428    china     12
34   billion     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
43,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...,197
118,2026-09-28-19-37-09 +0000,chitri,President Trump announces a new $15B Iowa stee...,https://www.chicagotribune.com/2026/09/28/trum...,102
60,2026-09-28-21-00-18 +0000,chitri,President Trump disputes his ambassador’s acco...,https://www.chicagotribune.com/2026/09/28/trum...,97
131,2026-09-28-19-15-55 +0000,wapo,Trump says new fuel economy rules will cut car...,https://www.washingtonpost.com/transportation/...,94
4,2026-09-28-22-46-00 +0000,wsj,President Trump announced a Minnesota company’...,https://www.wsj.com/politics/trump-to-unveil-p...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
43,197,2026-09-28-21-24-00 +0000,wsj,The FAA will delay approval of Boeing’s latest...,https://www.wsj.com/politics/policy/software-g...
230,63,2026-09-28-13-54-08 +0000,nypost,Farmer who foiled suspected Iran terror plot o...,https://nypost.com/2026/09/28/world-news/farme...
199,49,2026-09-28-15-44-00 +0000,wsj,One of FBI Director Kash Patel’s top deputies ...,https://www.wsj.com/politics/policy/a-top-kash...
20,44,2026-09-28-22-02-24 +0000,nypost,California city cracks top 3 in America’s best...,https://nypost.com/2026/09/28/lifestyle/5-cali...
47,44,2026-09-28-21-18-43 +0000,nypost,Cornell frat member ratted out bros in alleged...,https://nypost.com/2026/09/28/us-news/bombshel...
240,41,2026-09-28-13-07-00 +0000,wsj,Ahead of the release of his book “This Cursed ...,https://www.wsj.com/world/how-evan-gershkovich...
332,39,2026-09-28-03-44-18 +0000,latimes,Brokers gobble up tee times at public golf cou...,https://www.latimes.com/california/story/2026-...
293,38,2026-09-28-09-09-39 +0000,wsj,Stock Market Today: Treasury Yields Climb to F...,https://www.wsj.com/livecoverage/stock-market-...
180,38,2026-09-28-16-54-00 +0000,wsj,A Federal Reserve employee transferred potenti...,https://www.wsj.com/economy/central-banking/fe...
191,34,2026-09-28-16-18-57 +0000,cbc,SpaceX sends giant Starship into orbit for the...,https://www.cbc.ca/news/science/starship-fligh...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)