## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-16-19-00-23 +0000,bbc,Teen suspect in Virginia campus shooting found...,https://www.bbc.co.uk/news/articles/c0l5583903...
1,2026-08-16-18-58-58 +0000,nyt,Could El-Sayed Cost Democrats Michigan?,https://www.nytimes.com/2026/08/16/upshot/mich...
2,2026-08-16-18-56-01 +0000,48hills,Toro y Moi’s sweeping show at Bottom of the Hi...,https://48hills.org/2026/08/toro-y-mois-farewe...
3,2026-08-16-18-53-08 +0000,nypost,Arab allies join Trump in calling for Israel t...,https://nypost.com/2026/08/16/world-news/arab-...
4,2026-08-16-18-50-16 +0000,cbc,At least 2 people killed as firefighters battl...,https://www.cbc.ca/news/world/wildfires-greece...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2472/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
25    trump     15
247     new      8
105    iran      8
54      war      7
35   killed      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
59,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...,54
29,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...,41
16,2026-08-16-18-19-46 +0000,nypost,Harvard professor slammed for using AI to writ...,https://nypost.com/2026/08/16/media/harvard-pr...,36
179,2026-08-15-19-39-00 +0000,wsj,Trump Family’s World Liberty Financial Gets Pr...,https://www.wsj.com/finance/trump-familys-worl...,36
28,2026-08-16-17-39-39 +0000,nyt,"As Iran War Turns Into Economic Battle, a New ...",https://www.nytimes.com/2026/08/16/world/middl...,35

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
59,54,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...
29,41,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...
56,34,2026-08-16-15-19-52 +0000,nypost,Ex-Mamdani campaign staffer makes outrageous c...,https://nypost.com/2026/08/16/us-news/ex-mamda...
75,30,2026-08-16-13-35-56 +0000,nypost,Ukraine kills at least 6 people in Russia afte...,https://nypost.com/2026/08/16/world-news/ukrai...
173,29,2026-08-15-20-08-06 +0000,nypost,Acting Navy secretary salutes USS Abraham Linc...,https://nypost.com/2026/08/15/us-news/dire-rep...
137,28,2026-08-16-02-00-00 +0000,wsj,Central banks may be accidentally subsidizing ...,https://www.wsj.com/economy/central-banking/ce...
13,27,2026-08-16-18-23-50 +0000,nypost,GOP Rep. Mike Lawler eyes nuclear power plant ...,https://nypost.com/2026/08/16/us-news/gop-rep-...
96,26,2026-08-16-10-51-59 +0000,nypost,Four Renaissance paintings of ‘extraordinary v...,https://nypost.com/2026/08/16/world-news/anton...
135,25,2026-08-16-03-36-25 +0000,nypost,Groom-to-be found dead in hotel rubble after C...,https://nypost.com/2026/08/15/world-news/groom...
144,25,2026-08-16-00-44-05 +0000,nypost,California AG’s block of Paramount-Warner Bros...,https://nypost.com/2026/08/15/business/califor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)