## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-22-09-00-08 +0000,nyt,Missing From a Mass Wedding in India: Brides,https://www.nytimes.com/2026/08/22/world/asia/...
1,2026-08-22-09-00-00 +0000,wapo,She’s a Trump acolyte. He’s a ‘gringo Sandinis...,https://www.washingtonpost.com/world/2026/08/2...
2,2026-08-22-09-00-00 +0000,wsj,"Trump’s Other Ballroom: An 11,000-Square-Foot ...",https://www.wsj.com/politics/policy/trump-new-...
3,2026-08-22-08-48-26 +0000,nyt,Sun Screen,https://www.nytimes.com/2026/08/22/briefing/su...
4,2026-08-22-08-43-01 +0000,wapo,No deal reached in U.S.-Canada trade talks as ...,https://www.washingtonpost.com/business/2026/0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2396/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
6       trump     47
28      talks     13
214     court     13
26     canada     12
14   ballroom     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
65,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...,124
132,2026-08-21-20-47-00 +0000,wsj,The Supreme Court on Friday said President Tru...,https://www.wsj.com/politics/policy/trump-can-...,122
178,2026-08-21-18-37-08 +0000,nypost,Work on Trump White House ballroom can continu...,https://nypost.com/2026/08/21/us-news/work-on-...,122
105,2026-08-21-21-34-00 +0000,wsj,A dismissal of several high-ranking officials ...,https://www.wsj.com/politics/policy/upheaval-a...,110
49,2026-08-22-01-00-00 +0000,wsj,Democrats are readying multifront investigatio...,https://www.wsj.com/politics/policy/democrats-...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
65,124,2026-08-21-23-41-51 +0000,chitri,Supreme Court’s chief justice allows work on P...,https://www.chicagotribune.com/2026/08/21/supr...
17,93,2026-08-22-05-10-00 +0000,wsj,Trade talks between the U.S. and Canada broke ...,https://www.wsj.com/economy/trade/u-s-to-impos...
52,47,2026-08-22-00-46-00 +0000,wsj,President Trump made a personal pitch to South...,https://www.wsj.com/politics/elections/trump-m...
277,45,2026-08-21-11-19-54 +0000,chitri,A question looms over Harry’s return to the UK...,https://www.chicagotribune.com/2026/08/21/harr...
38,38,2026-08-22-02-17-02 +0000,nypost,Karmelo Anthony threatened to ‘shoot the schoo...,https://nypost.com/2026/08/21/us-news/karmelo-...
121,37,2026-08-21-21-07-00 +0000,wsj,Army Secretary Dan Driscoll is expected to ste...,https://www.wsj.com/politics/national-security...
181,36,2026-08-21-18-30-17 +0000,startribune,Four bodies found near Minneapolis waters in f...,https://www.startribune.com/four-bodies-found-...
26,34,2026-08-22-03-59-37 +0000,nypost,California Dem earning $207K taxpayer salary t...,https://nypost.com/2026/08/21/us-news/californ...
14,33,2026-08-22-05-33-59 +0000,nypost,Parents of Pennsylvania soccer player Karoline...,https://nypost.com/2026/08/22/us-news/pennwest...
241,33,2026-08-21-14-36-00 +0000,wsj,GM Faces Safety Probe Over Engine-Failure Conc...,https://www.wsj.com/business/autos/gm-faces-sa...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)