## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-04-11-22-02 +0000,nypost,"Three dead, more than a dozen injured in fire ...",https://nypost.com/2026/05/04/us-news/three-de...
1,2026-05-04-11-20-00 +0000,wsj,Oil Extends Gains on Protracted Hormuz Closure...,https://www.wsj.com/finance/commodities-future...
2,2026-05-04-11-18-00 +0000,wsj,Norwegian Cruise Line Cuts Outlook,https://www.wsj.com/business/earnings/norwegia...
3,2026-05-04-11-15-00 +0000,nypost,World Liberty Financial hits back at crypto bi...,https://nypost.com/2026/05/04/business/world-l...
4,2026-05-04-11-12-50 +0000,nyt,What to Know About the Suspected Hantavirus Ou...,https://www.nytimes.com/2026/05/04/world/hanta...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
53   trump     28
56    iran     17
11  hormuz     14
7      oil     12
62  strait     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
7,2026-05-04-11-00-31 +0000,nyt,Oil Jumps as Iran Resists Trump’s Offer to Hel...,https://www.nytimes.com/2026/05/03/business/oi...,103
13,2026-05-04-10-43-08 +0000,nypost,US denies Iran claim it hit warship in Strait ...,https://nypost.com/2026/05/04/world-news/iran-...,99
142,2026-05-03-21-12-16 +0000,nypost,Trump says US will guide stranded ships out of...,https://nypost.com/2026/05/03/world-news/trump...,87
164,2026-05-03-19-17-12 +0000,nypost,Iran makes outlandish new demands to reopen St...,https://nypost.com/2026/05/03/world-news/iran-...,84
191,2026-05-03-16-49-30 +0000,cbc,Trump says operation will start Monday to help...,https://www.cbc.ca/news/world/cargo-ship-strai...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
7,103,2026-05-04-11-00-31 +0000,nyt,Oil Jumps as Iran Resists Trump’s Offer to Hel...,https://www.nytimes.com/2026/05/03/business/oi...
9,45,2026-05-04-11-00-00 +0000,nypost,NYC Italian enclaves left out of the party as ...,https://nypost.com/2026/05/04/us-news/nyc-ital...
141,43,2026-05-03-21-14-10 +0000,nypost,"3 MV Hondius cruise ship passengers dead, anot...",https://nypost.com/2026/05/03/world-news/3-mv-...
167,37,2026-05-03-19-08-13 +0000,nypost,"Ukraine attacks Russian oil port, ‘shadow flee...",https://nypost.com/2026/05/03/world-news/ukrai...
208,34,2026-05-03-15-39-22 +0000,nypost,WHCD shooting suspect Cole Allen ‘thought he w...,https://nypost.com/2026/05/03/us-news/whcd-sus...
45,33,2026-05-04-09-02-13 +0000,nypost,House Democrats add eight new battleground tar...,https://nypost.com/2026/05/04/us-news/house-de...
99,31,2026-05-04-01-41-22 +0000,nypost,"United plane strikes light pole, tractor-trail...",https://nypost.com/2026/05/03/us-news/united-p...
114,28,2026-05-04-00-29-21 +0000,nypost,Two major California insurers plot massive rat...,https://nypost.com/2026/05/03/us-news/two-majo...
220,27,2026-05-03-14-25-27 +0000,nypost,Former top Biden official all but admits admin...,https://nypost.com/2026/05/03/us-news/ex-biden...
121,26,2026-05-03-23-24-16 +0000,nypost,Ex-NYC Mayor Rudy Giuliani hospitalized in cri...,https://nypost.com/2026/05/03/us-news/ex-nyc-m...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)