## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-21-17-51-56 +0000,nypost,Coroner provides official cause of death for N...,https://nypost.com/2026/09/21/us-news/eliana-m...
1,2026-09-21-17-51-44 +0000,cbc,"Converse apologizes, pulls ad that critics say...",https://www.cbc.ca/news/world/converse-ad-apol...
2,2026-09-21-17-51-32 +0000,nypost,"OpenAI, Anthropic held talks to ‘stress-test’ ...",https://nypost.com/2026/09/21/business/openai-...
3,2026-09-21-17-51-13 +0000,nypost,Trump will call out ‘ridiculous’ UN for claims...,https://nypost.com/2026/09/21/us-news/trump-wi...
4,2026-09-21-17-51-07 +0000,nyt,"Paramount to Settle States’ Lawsuit, Clearing ...",https://www.nytimes.com/2026/09/21/business/pa...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2359/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
32      trump     39
172       new     17
82      house     14
104     china     13
620  election     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
303,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,123
78,2026-09-21-15-58-53 +0000,bbc,"CNN, MS NOW and Politico file lawsuit against ...",https://www.bbc.co.uk/news/articles/cm0e32rwvr...,98
128,2026-09-21-13-36-06 +0000,cbc,"MS NOW, CNN and Politico sue Trump administrat...",https://www.cbc.ca/news/world/trump-white-hous...,93
108,2026-09-21-14-46-18 +0000,nyt,"CNN, MS NOW and Politico to Sue Trump Administ...",https://www.nytimes.com/2026/09/21/business/me...,89
91,2026-09-21-15-36-00 +0000,wsj,"Illinois Gov. JB Pritzker, whose weight has be...",https://www.wsj.com/politics/policy/jb-pritzke...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
303,123,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
228,64,2026-09-21-05-52-57 +0000,bbc,Lindsay Clancy's ex-husband says he forgave he...,https://www.bbc.co.uk/news/articles/cq5yme200n...
16,64,2026-09-21-17-36-52 +0000,bbc,"Paramount settles lawsuit with US states, help...",https://www.bbc.co.uk/news/articles/cm4gjr1qep...
168,59,2026-09-21-10-57-58 +0000,chitri,"CNN, MS NOW and Politico sue over denied White...",https://www.chicagotribune.com/2026/09/21/cnn-...
84,57,2026-09-21-15-49-00 +0000,wsj,Republican lawmakers are running out of time t...,https://www.wsj.com/politics/elections/republi...
145,47,2026-09-21-12-27-37 +0000,nypost,Trump says Russia ‘lost control of its Diesel ...,https://nypost.com/2026/09/21/us-news/trump-sa...
103,44,2026-09-21-14-54-19 +0000,nypost,US pitches China on AI notification deal ahead...,https://nypost.com/2026/09/21/us-news/us-pitch...
251,41,2026-09-21-01-00-00 +0000,wsj,Republicans are pumping money into Senate and ...,https://www.wsj.com/politics/elections/republi...
205,31,2026-09-21-09-00-00 +0000,wsj,How The Wall Street Journal is covering the 20...,https://www.wsj.com/politics/elections/how-wsj...
91,31,2026-09-21-15-36-00 +0000,wsj,"Illinois Gov. JB Pritzker, whose weight has be...",https://www.wsj.com/politics/policy/jb-pritzke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)