## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-27-16-51-49 +0000,startribune,Live: Lynx open playoffs against Liberty with ...,https://www.startribune.com/minnesota-lynx-new...
1,2026-09-27-16-46-17 +0000,nyt,"Giant Pandas, Icons of China’s Soft Diplomacy,...",https://www.nytimes.com/2026/09/27/us/panda-zo...
2,2026-09-27-16-35-41 +0000,bbc,Woman charged with stealing from patients and ...,https://www.bbc.co.uk/news/articles/c3ew9e5lg0...
3,2026-09-27-16-28-56 +0000,nypost,Nosy neighbor may have foiled possible Iran-li...,https://nypost.com/2026/09/27/world-news/nosy-...
4,2026-09-27-16-28-15 +0000,nypost,Hurricane Polo sends dangerous swells toward S...,https://nypost.com/2026/09/27/us-news/hurrican...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2574/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
72   trump     21
99     new     12
205    war     11
33    iran     10
36    base      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
19,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...,68
33,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...,65
34,2026-09-27-14-33-06 +0000,nypost,Iran ready for ‘doomsday war’ after Trump reje...,https://nypost.com/2026/09/27/us-news/iran-rea...,65
36,2026-09-27-14-12-58 +0000,nyt,Iran Seeks U.S. Clarification After Trump Reje...,https://www.nytimes.com/2026/09/27/world/middl...,52
152,2026-09-26-21-02-42 +0000,nyt,Trump Rejects Iran’s Cease-Fire Proposal to Re...,https://www.nytimes.com/2026/09/26/us/politics...,52

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
19,68,2026-09-27-15-49-32 +0000,nypost,Trump says terror suspects in possible Iran-li...,https://nypost.com/2026/09/27/world-news/trump...
46,51,2026-09-27-12-34-26 +0000,bbc,One dead as nor'easter storm pummels New York ...,https://www.bbc.co.uk/news/articles/ck1wxxzn5j...
33,47,2026-09-27-14-38-29 +0000,chitri,5 men arrested near air base used by US in Ira...,https://www.chicagotribune.com/2026/09/27/uk-p...
17,38,2026-09-27-15-56-15 +0000,nypost,‘Home-wrecker’ Sen. Kyrsten Sinema’s ex-bodygu...,https://nypost.com/2026/09/27/us-news/kyrsten-...
102,38,2026-09-27-06-47-34 +0000,nypost,"27 killed, dozens wounded in horror mass shoot...",https://nypost.com/2026/09/27/world-news/south...
35,32,2026-09-27-14-16-04 +0000,cbc,OpenAI pauses training of latest models after ...,https://www.cbc.ca/news/business/openai-pause-...
155,29,2026-09-26-20-44-36 +0000,nypost,Iran opens criminal probe against theater comp...,https://nypost.com/2026/09/26/world-news/irani...
12,27,2026-09-27-16-00-34 +0000,chitri,Tensions run high in Northern Ireland after co...,https://www.chicagotribune.com/2026/09/27/nort...
96,27,2026-09-27-08-09-32 +0000,nypost,Long Island swimmer vanishes in ocean off Fire...,https://nypost.com/2026/09/27/us-news/long-isl...
173,25,2026-09-26-17-45-31 +0000,nypost,Ukraine airdrops killer robots behind enemy li...,https://nypost.com/2026/09/26/world-news/ukrai...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)