## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-11-09-05-34 +0000,nyt,Iran War Live Updates: Vance Lands in Pakistan...,https://www.nytimes.com/live/2026/04/11/world/...
1,2026-04-11-09-02-24 +0000,nyt,Iran Tries to Grasp Economic Devastation of Wa...,https://www.nytimes.com/2026/04/11/world/middl...
2,2026-04-11-09-01-56 +0000,nyt,Looking for a College Scholarship on Social Me...,https://www.nytimes.com/2026/04/11/your-money/...
3,2026-04-11-09-00-44 +0000,nyt,‘Spring Clean’ Your Finances: How to Overhaul ...,https://www.nytimes.com/2026/04/11/business/fi...
4,2026-04-11-09-00-38 +0000,nyt,"No Doors, No Roof, No Worries: A Tiny Racecar ...",https://www.nytimes.com/2026/04/11/business/ca...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2572/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0      iran     54
351   trump     36
1       war     25
8     talks     21
859  prices     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-04-11-09-05-34 +0000,nyt,Iran War Live Updates: Vance Lands in Pakistan...,https://www.nytimes.com/live/2026/04/11/world/...,186
275,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,149
153,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...,142
61,2026-04-11-01-21-53 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,139
9,2026-04-11-08-55-05 +0000,nyt,Iran Has Been Consistent in War. Will It Be Co...,https://www.nytimes.com/2026/04/11/world/middl...,123

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,186,2026-04-11-09-05-34 +0000,nyt,Iran War Live Updates: Vance Lands in Pakistan...,https://www.nytimes.com/live/2026/04/11/world/...
44,96,2026-04-11-03-49-39 +0000,nypost,California Rep. Eric Swalwell slams sexual mis...,https://nypost.com/2026/04/10/us-news/californ...
135,69,2026-04-10-20-58-00 +0000,wsj,President Trump has repeatedly promised his to...,https://www.wsj.com/politics/policy/trump-prom...
153,63,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...
196,42,2026-04-10-18-31-35 +0000,missionlocal,SFPD arrests young suspect who allegedly threw...,https://missionlocal.org/2026/04/sfpd-arson-su...
296,42,2026-04-10-10-48-00 +0000,wsj,The fate of the U.S.-Iran cease-fire will be d...,https://www.wsj.com/politics/trump-sends-his-t...
26,40,2026-04-11-05-22-40 +0000,nypost,Arkansas woman jailed after refusing to return...,https://nypost.com/2026/04/11/us-news/arkansas...
258,39,2026-04-10-15-12-57 +0000,bbc,EU airline industry warns of fuel shortages if...,https://www.bbc.com/news/articles/c3w37ggp011o...
87,34,2026-04-10-23-43-57 +0000,nypost,Nancy Pelosi told Eric Swalwell to drop out of...,https://nypost.com/2026/04/10/us-news/eric-swa...
84,33,2026-04-11-00-08-03 +0000,nypost,"Artemis II successfully splashes down, complet...",https://nypost.com/2026/04/10/us-news/artemis-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)