## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-20-53-08 +0000,nyt,Trump’s Latest Makeover Target? Space Force Un...,https://www.nytimes.com/2026/09/08/style/trump...
1,2026-09-08-20-50-31 +0000,nypost,Hochul announces $70M for boosted synagogue se...,https://nypost.com/2026/09/08/us-news/hochul-a...
2,2026-09-08-20-49-16 +0000,nypost,Lindsay Clancy jury was ready to find her not ...,https://nypost.com/2026/09/08/us-news/lindsay-...
3,2026-09-08-20-46-58 +0000,nypost,California union threatens strike in war over ...,https://nypost.com/2026/09/08/us-news/californ...
4,2026-09-08-20-43-26 +0000,bbc,LIV players free to leave after bankruptcy pro...,https://www.bbc.co.uk/sport/golf/articles/ce8x...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
0     trump     42
137     new     23
84   canada     16
277   trade     15
56      oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
318,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,104
158,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...,94
235,2026-09-08-11-27-19 +0000,cbc,Bombardier shares dip after Trump threatens ac...,https://www.cbc.ca/news/livestory/canada-u-s-r...,92
97,2026-09-08-17-44-00 +0000,wsj,The Trump administration filed an emergency ap...,https://www.wsj.com/politics/policy/trump-offi...,87
244,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
318,104,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...
162,70,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...
289,56,2026-09-08-09-10-00 +0000,wsj,Oil Nears $100 a Barrel as Fresh Attacks on Sa...,https://www.wsj.com/world/middle-east/oil-near...
158,52,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...
2,51,2026-09-08-20-49-16 +0000,nypost,Lindsay Clancy jury was ready to find her not ...,https://nypost.com/2026/09/08/us-news/lindsay-...
97,45,2026-09-08-17-44-00 +0000,wsj,The Trump administration filed an emergency ap...,https://www.wsj.com/politics/policy/trump-offi...
51,41,2026-09-08-19-14-37 +0000,nypost,"Hate-filled maniac who stabbed Jewish, Asian m...",https://nypost.com/2026/09/08/us-news/hate-fil...
131,41,2026-09-08-16-38-03 +0000,bbc,Five killed in Miami plane crash were in two v...,https://www.bbc.co.uk/news/articles/ce8e32n8ep...
255,37,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
3,36,2026-09-08-20-46-58 +0000,nypost,California union threatens strike in war over ...,https://nypost.com/2026/09/08/us-news/californ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)