## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-11-29-09 +0000,nypost,Kentucky man ‘framed’ by cops in ‘satanic’ mur...,https://nypost.com/2026/05/07/us-news/kentucky...
1,2026-05-07-11-26-00 +0000,wsj,Planet Fitness Slashes 2026 Views After Weak S...,https://www.wsj.com/business/earnings/planet-f...
2,2026-05-07-11-25-00 +0000,wsj,McDonald’s Value Machine Is Generating Higher ...,https://www.wsj.com/business/hospitality/mcdon...
3,2026-05-07-11-18-40 +0000,bbc,Three women linked to Islamic State arrested i...,https://www.bbc.com/news/articles/czj2emlv2kjo...
4,2026-05-07-11-17-54 +0000,startribune,Downtown bars win better business amid Wild an...,https://www.startribune.com/downtown-minneapol...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2381/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
181       trump     28
255        iran     26
229         war     22
101         new     19
299  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
158,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,129
323,2026-05-06-16-11-44 +0000,bbc,Oil prices drop and stock markets rise after r...,https://www.bbc.com/news/articles/c4g8zejyyr3o...,103
340,2026-05-06-14-57-00 +0000,wsj,President Trump escalated his public feud with...,https://www.wsj.com/politics/national-security...,94
124,2026-05-07-04-06-33 +0000,bbc,Iran considering US proposal as Trump says war...,https://www.bbc.com/news/articles/cj0pq2q8221o...,91
255,2026-05-06-20-16-58 +0000,nyt,Oil Prices Fall on Hope U.S.-Iran War Turmoil ...,https://www.nytimes.com/2026/05/06/business/oi...,84

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
158,129,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
354,71,2026-05-06-14-16-51 +0000,wapo,Hantavirus-hit cruise ship to head to Canary I...,https://www.washingtonpost.com/health/2026/05/...
329,57,2026-05-06-15-28-00 +0000,wsj,The job market is starting to show glimmers of...,https://www.wsj.com/economy/jobs/jobs-payroll-...
164,55,2026-05-07-00-45-00 +0000,wsj,Commerce Secretary Howard Lutnick told a congr...,https://www.wsj.com/politics/policy/lutnick-sa...
305,52,2026-05-06-17-21-15 +0000,nypost,"Trump, Ric Flair, Atlanta Braves, media perso...",https://nypost.com/2026/05/06/media/trump-ric-...
325,48,2026-05-06-16-05-59 +0000,nypost,California governor candidate Chad Bianco caug...,https://nypost.com/2026/05/06/us-news/californ...
297,47,2026-05-06-17-38-42 +0000,nypost,Ex-JPMorgan banker Chirayu Rana was referred f...,https://nypost.com/2026/05/06/business/ex-jpmo...
129,46,2026-05-07-03-38-32 +0000,nypost,Texas shopping mall shooter allegedly killed 2...,https://nypost.com/2026/05/06/us-news/texas-sh...
58,44,2026-05-07-09-33-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
140,42,2026-05-07-02-24-48 +0000,latimes,"Bass, Raman and Pratt square off on Palisades ...",https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)