## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-17-33-00 +0000,wsj,Trump Says U.S. ‘Must’ Respond After Confirmin...,https://www.wsj.com/world/middle-east/apache-h...
1,2026-06-09-17-32-15 +0000,bbc,Trump says Iran shot down US helicopter and vo...,https://www.bbc.com/news/articles/cze9359gglyo...
2,2026-06-09-17-30-49 +0000,nypost,3.4-magnitude earthquake shakes portions of In...,https://nypost.com/2026/06/09/us-news/3-4-magn...
3,2026-06-09-17-30-36 +0000,nypost,Far-left progressive linked to Bernie Sanders ...,https://nypost.com/2026/06/09/us-news/bernie-s...
4,2026-06-09-17-30-02 +0000,nyt,"Man Arrested in ‘Brutal’ Stabbing in Belfast, ...",https://www.nytimes.com/2026/06/09/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2528/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     32
4          iran     30
264         new     18
337       world     12
25   california     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-06-09-17-28-55 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...,125
185,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...,122
20,2026-06-09-17-01-09 +0000,nypost,Trump vows to retaliate against Iran after rev...,https://nypost.com/2026/06/09/us-news/iran-sho...,111
18,2026-06-09-17-05-03 +0000,startribune,Trump says US 'must' respond after Iran downed...,https://www.startribune.com/trump-says-pilots-...,103
0,2026-06-09-17-33-00 +0000,wsj,Trump Says U.S. ‘Must’ Respond After Confirmin...,https://www.wsj.com/world/middle-east/apache-h...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,125,2026-06-09-17-28-55 +0000,nyt,Iran War Live Updates: Trump Says Iran Downed ...,https://www.nytimes.com/live/2026/06/09/world/...
223,66,2026-06-09-01-19-28 +0000,bbc,Spencer Pratt out of LA mayor race as left-win...,https://www.bbc.com/news/articles/cx219kxkj1jo...
165,59,2026-06-09-10-00-00 +0000,latimes,This new law could create a million new apartm...,https://www.latimes.com/business/story/2026-06...
190,53,2026-06-09-08-02-43 +0000,bbc,AI giants' race to raise funds heats up as Cha...,https://www.bbc.com/news/articles/cd958eqg1n5o...
185,50,2026-06-09-08-44-20 +0000,nypost,Two pilots rescued after US helicopter crashe...,https://nypost.com/2026/06/09/world-news/us-ar...
253,46,2026-06-08-22-47-33 +0000,cbc,Somali referee won't officiate in World Cup af...,https://www.cbc.ca/sports/soccer/worldcup/soma...
155,45,2026-06-09-10-10-00 +0000,wsj,The Pentagon on Monday updated its list of Chi...,https://www.wsj.com/politics/national-security...
218,43,2026-06-09-02-00-00 +0000,wsj,President Trump and his allies are escalating ...,https://www.wsj.com/politics/elections/trump-f...
88,39,2026-06-09-15-01-01 +0000,nypost,Inside the rowdy street-side Knicks watch part...,https://nypost.com/2026/06/09/lifestyle/inside...
233,38,2026-06-09-00-16-29 +0000,nypost,Ex-Graham Platner campaign director says embat...,https://nypost.com/2026/06/08/us-news/ex-graha...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)