## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-01-21-01-27 +0000,nypost,Mamdani slammed by Israeli president for blast...,https://nypost.com/2026/08/01/us-news/mamdani-...
1,2026-08-01-20-54-03 +0000,nyt,"Israel Bombards Gaza, Days After Trump Announc...",https://www.nytimes.com/2026/08/01/world/middl...
2,2026-08-01-20-51-42 +0000,nypost,Millions of Ukrainian books incinerated in Ru...,https://nypost.com/2026/08/01/world-news/milli...
3,2026-08-01-20-51-09 +0000,bbc,"Tourist plane crashes in Peru, killing 13",https://www.bbc.co.uk/news/articles/c70g132erl...
4,2026-08-01-20-46-06 +0000,nypost,Butchered NJ therapist’s close friend says ‘in...,https://nypost.com/2026/08/01/us-news/brooke-h...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2541/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
14        trump     23
85   california     12
292    migrants     11
66         iran     11
312     against     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
43,2026-08-01-17-41-39 +0000,nypost,Trump sternly rebukes Jeanine Pirro’s decision...,https://nypost.com/2026/08/01/us-news/trump-st...,73
233,2026-07-31-21-33-06 +0000,nypost,Jeanine Pirro drops Reflecting Pool vandalism ...,https://nypost.com/2026/07/31/us-news/jeanine-...,70
205,2026-07-31-22-58-15 +0000,chitri,Justice Department drops criminal case against...,https://www.chicagotribune.com/2026/07/31/crim...,63
219,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...,60
201,2026-07-31-23-02-17 +0000,cbc,U.S. Justice Department dismisses case against...,https://www.cbc.ca/news/world/us-doj-drops-ref...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
43,73,2026-08-01-17-41-39 +0000,nypost,Trump sternly rebukes Jeanine Pirro’s decision...,https://nypost.com/2026/08/01/us-news/trump-st...
219,60,2026-07-31-22-09-00 +0000,wsj,Former congressman George Santos will pay more...,https://www.wsj.com/politics/george-santos-set...
231,51,2026-07-31-21-40-18 +0000,nypost,FIFA has scrapped $20B World Cup sell-off plan...,https://nypost.com/2026/07/31/business/fifa-ha...
66,46,2026-08-01-16-08-45 +0000,cbc,Hunger and hostility cited by migrants as reas...,https://www.cbc.ca/news/world/ceuta-morocco-mi...
56,40,2026-08-01-16-50-51 +0000,cbc,"Nirmal Purja, 'inspirational' Nepali climber, ...",https://www.cbc.ca/news/world/nepal-climber-ni...
68,34,2026-08-01-16-00-00 +0000,wsj,A Tech Founder Wanted to Start a New Country. ...,https://www.wsj.com/tech/a-tech-founder-wanted...
205,34,2026-07-31-22-58-15 +0000,chitri,Justice Department drops criminal case against...,https://www.chicagotribune.com/2026/07/31/crim...
2,33,2026-08-01-20-51-42 +0000,nypost,Millions of Ukrainian books incinerated in Ru...,https://nypost.com/2026/08/01/world-news/milli...
236,32,2026-07-31-21-24-57 +0000,nypost,Woke California college students force school ...,https://nypost.com/2026/07/31/us-news/ucsd-end...
160,30,2026-08-01-03-00-00 +0000,wsj,Democratic socialist candidates are gaining mo...,https://www.wsj.com/politics/elections/democra...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)