## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-01-17-29-07 +0000,48hills,"Drama Masks: Send in the clowns, they’re alrea...",https://48hills.org/2026/07/drama-mask-stage-r...
1,2026-07-01-17-27-05 +0000,nypost,Trump won’t renew USMCA deal with Canada and M...,https://nypost.com/2026/07/01/us-news/trump-wo...
2,2026-07-01-17-26-23 +0000,nyt,"Washington, D.C., Is Full of Construction Zone...",https://www.nytimes.com/2026/07/01/us/politics...
3,2026-07-01-17-25-54 +0000,nypost,1 airman missing after MH-60S Sea Hawk helicop...,https://nypost.com/2026/07/01/us-news/1-airman...
4,2026-07-01-17-24-00 +0000,wsj,We asked five experts across the political spe...,https://www.wsj.com/us-news/law/us-constitutio...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2544/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
7      trump     46
234    court     21
500  supreme     20
255      new     18
74      year     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
99,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...,117
288,2026-06-30-23-15-01 +0000,nyt,Trump Says It’s ‘Too Bad’ Supreme Court Upheld...,https://www.nytimes.com/2026/06/30/us/politics...,115
349,2026-06-30-20-16-00 +0000,wsj,Supreme Court Rejects Trump’s Bid to Curtail B...,https://www.wsj.com/us-news/law/supreme-court-...,115
233,2026-07-01-05-32-26 +0000,bbc,US Supreme Court upholds birthright citizenshi...,https://www.bbc.co.uk/news/articles/cgmepnx1wz...,114
164,2026-07-01-11-10-00 +0000,wsj,Three places where this Supreme Court fenced T...,https://www.wsj.com/politics/three-places-wher...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
99,117,2026-07-01-14-44-00 +0000,wsj,President Trump’s forays into cryptocurrency d...,https://www.wsj.com/politics/policy/trump-made...
255,85,2026-07-01-02-00-00 +0000,wsj,The Supreme Court has wrapped up one of its mo...,https://www.wsj.com/politics/policy/how-suprem...
181,66,2026-07-01-10-00-01 +0000,nyt,3 People Die During World Cup Celebrations in ...,https://www.nytimes.com/2026/07/01/world/ameri...
346,57,2026-06-30-20-21-11 +0000,bbc,Will Starmer's plan for defence help UK hit Na...,https://www.bbc.co.uk/news/articles/cn07ey43xp...
211,49,2026-07-01-09-00-00 +0000,wapo,Fate of $2 trillion North American trade deal ...,https://www.washingtonpost.com/business/2026/0...
243,46,2026-07-01-04-15-11 +0000,nypost,Socialist congressional candidate Melat Kiros ...,https://nypost.com/2026/07/01/us-news/socialis...
195,46,2026-07-01-09-30-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
263,42,2026-07-01-01-00-00 +0000,wsj,Although the justices struck down an executive...,https://www.wsj.com/politics/policy/supreme-co...
14,40,2026-07-01-17-12-00 +0000,wsj,Elizabeth Warren asked the Fed’s inspector gen...,https://www.wsj.com/economy/central-banking/wa...
68,40,2026-07-01-15-54-01 +0000,nypost,Child sex offender drops outrageous claim afte...,https://nypost.com/2026/07/01/us-news/register...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)