## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-13-02-44-39 +0000,missionlocal,Resist,https://missionlocal.org/2026/03/resist/
1,2026-03-13-02-43-00 +0000,wapo,Trump administration allows for Russian oil sa...,https://www.washingtonpost.com/business/2026/0...
2,2026-03-13-02-30-19 +0000,nyt,Iran War Live Updates: U.S. Refueling Plane Cr...,https://www.nytimes.com/live/2026/03/12/world/...
3,2026-03-13-02-30-14 +0000,nyt,Oil Prices Barely Budge After Trump Lifts Russ...,https://www.nytimes.com/2026/03/12/business/oi...
4,2026-03-13-02-23-27 +0000,bbc,Netflix announces KPop Demon Hunters sequel,https://www.bbc.com/news/articles/c2k8wvzgqk7o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2617/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
10    iran     62
11     war     38
5      oil     34
1    trump     31
387    new     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
213,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...,192
125,2026-03-12-21-18-08 +0000,nypost,Iran used AI on newly released photo of Iran’s...,https://nypost.com/2026/03/12/us-news/iran-use...,167
259,2026-03-12-15-11-14 +0000,nypost,"Dow falls over 700 points, oil hits $100 as Ir...",https://nypost.com/2026/03/12/business/dow-fal...,157
275,2026-03-12-13-57-56 +0000,bbc,How Iran war laid bare the world's reliance on...,https://www.bbc.com/news/articles/c15x1y8d37vo...,156
7,2026-03-13-02-16-46 +0000,startribune,Trump Removes Sanctions on Russia to Help Oil ...,https://www.startribune.com/trump-removes-sanc...,155

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
213,192,2026-03-12-17-01-48 +0000,nypost,Trump might lift this obscure 100-year old law...,https://nypost.com/2026/03/12/us-news/trump-mi...
182,83,2026-03-12-18-26-46 +0000,nyt,"Mojtaba Khamenei, Iran’s New Supreme Leader, S...",https://www.nytimes.com/2026/03/12/world/middl...
187,73,2026-03-12-18-14-00 +0000,wsj,When Kash Patel said in one of his first video...,https://www.wsj.com/politics/policy/ufc-fighte...
200,48,2026-03-12-17-46-12 +0000,cbc,FBI investigating Detroit-area synagogue attac...,https://www.cbc.ca/news/world/detroit-synagogu...
44,47,2026-03-13-00-29-46 +0000,nypost,Old Dominion ROTC instructor killed by convict...,https://nypost.com/2026/03/12/us-news/old-domi...
198,43,2026-03-12-17-48-43 +0000,wapo,White House considers waiving shipping rules i...,https://www.washingtonpost.com/business/2026/0...
381,39,2026-03-12-05-00-05 +0000,nyt,Top-End Auction Sales Help Pull Global Art Mar...,https://www.nytimes.com/2026/03/12/arts/design...
271,39,2026-03-12-14-03-00 +0000,wsj,Sen. John Cornyn of Texas reversed himself and...,https://www.wsj.com/politics/policy/john-corny...
5,37,2026-03-13-02-20-37 +0000,nypost,Possible motive of Michigan maniac who plowed ...,https://nypost.com/2026/03/12/us-news/possible...
31,36,2026-03-13-01-19-53 +0000,nypost,"Two officers, PG&E worker shot in Northern Cal...",https://nypost.com/2026/03/12/us-news/two-offi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)