## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-24-07-01-08 +0000,nypost,Google illegally cut down 250K trees in Finlan...,https://nypost.com/2026/10/24/business/google-...
1,2026-10-24-06-47-09 +0000,nyt,Gadi Eisenkot Couldn’t Be More Unlike Netanyah...,https://www.nytimes.com/2026/10/23/world/middl...
2,2026-10-24-06-34-14 +0000,nypost,"Jury convicts man of rape, murder 14 years aft...",https://nypost.com/2026/10/24/us-news/north-ca...
3,2026-10-24-06-21-05 +0000,nyt,Justice Dept. Demands That California Counties...,https://www.nytimes.com/2026/10/23/us/justice-...
4,2026-10-24-06-19-46 +0000,bbc,France prepares for day of protest a week afte...,https://www.bbc.co.uk/news/articles/cj62yv5k0w...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2517/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
62      trump     44
464        up     15
130       new     14
18         he     14
98   election     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
86,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...,158
158,2026-10-23-19-04-00 +0000,wsj,The Justice Department charged two former FBI ...,https://www.wsj.com/politics/policy/former-fbi...,110
246,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...,109
346,2026-10-23-09-30-00 +0000,wsj,Capital Account: President Trump once called “...,https://www.wsj.com/economy/trade/how-tariffs-...,104
228,2026-10-23-16-02-00 +0000,wsj,Pocketbook issues top President Trump’s talkin...,https://www.wsj.com/politics/elections/trump-c...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
86,158,2026-10-23-21-50-00 +0000,wsj,The Trump administration moved to remove 50% t...,https://www.wsj.com/politics/policy/trump-to-c...
246,65,2026-10-23-15-15-32 +0000,chitri,President Donald Trump says he ordered the Jus...,https://www.chicagotribune.com/2026/10/23/trum...
48,61,2026-10-24-01-00-00 +0000,wsj,The world’s richest people have discovered a n...,https://www.wsj.com/economy/musk-trump-account...
259,56,2026-10-23-14-48-19 +0000,nypost,Oil prices hit five-month high and Dow falls o...,https://nypost.com/2026/10/23/business/oil-pri...
319,55,2026-10-23-11-00-00 +0000,missionlocal,"Election ad fact-check: Will Props. D, E, and ...",https://missionlocal.org/2026/10/san-francisco...
47,50,2026-10-24-01-00-00 +0000,wsj,Republican campaign operatives worry that a se...,https://www.wsj.com/politics/elections/midterm...
312,42,2026-10-23-11-01-29 +0000,cbc,Netanyahu orders West Bank closure as Israeli ...,https://www.cbc.ca/news/world/israel-west-bank...
44,38,2026-10-24-01-10-45 +0000,nypost,Amish woman uses weed whacker to scare off ill...,https://nypost.com/2026/10/23/us-news/amish-wo...
169,38,2026-10-23-18-44-39 +0000,chitri,Frankfort Fire Protection District asks voters...,https://www.chicagotribune.com/2026/10/23/fran...
321,36,2026-10-23-10-58-00 +0000,wsj,A wave of retirements is going to wipe out ove...,https://www.wsj.com/politics/policy/congress-w...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)