## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-05-14-55-39 +0000,nypost,Incest dad who raped teen daughter before baby...,https://nypost.com/2026/10/05/us-news/californ...
1,2026-10-05-14-54-51 +0000,nypost,Anthropic whistleblower Jacob Coxon to testify...,https://nypost.com/2026/10/05/business/anthrop...
2,2026-10-05-14-53-32 +0000,bbc,Artist 'taking legal advice' over Tories' use ...,https://www.bbc.co.uk/news/articles/cj62yg157p...
3,2026-10-05-14-52-56 +0000,nyt,5 Challenges David Ellison Faces as Warner Bro...,https://www.nytimes.com/2026/10/05/business/me...
4,2026-10-05-14-49-00 +0000,wsj,Russia Probes Death of Woman Who Worked at Ant...,https://www.wsj.com/world/russia-probes-death-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2498/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
128       new     23
72   election     20
144     house     17
84      trump     16
83     former     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
98,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...,74
210,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...,71
302,2026-10-04-16-20-31 +0000,nypost,Trump reveals new AI czar — and gives him 120 ...,https://nypost.com/2026/10/04/us-news/trump-re...,67
225,2026-10-05-00-34-02 +0000,chitri,The Latest: Brazil heads to runoff presidentia...,https://www.chicagotribune.com/2026/10/04/braz...,65
24,2026-10-05-14-24-08 +0000,wapo,Former White House press secretary Karoline Le...,https://www.washingtonpost.com/business/2026/1...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
98,74,2026-10-05-11-04-00 +0000,wsj,The Morning Risk Report: New AI Czar Unveils G...,https://www.wsj.com/risk-compliance-journal/th...
210,71,2026-10-05-02-42-00 +0000,wsj,"Flávio Bolsonaro Surges Past Lula, Setting Up ...",https://www.wsj.com/world/americas/flavio-bols...
270,55,2026-10-04-19-56-00 +0000,wsj,Americans are facing a multifront squeeze from...,https://www.wsj.com/politics/elections/energy-...
194,53,2026-10-05-06-45-01 +0000,nypost,"Former ‘Survivor’ star faces arrest, FBI probe...",https://nypost.com/2026/10/05/us-news/fbi-inve...
81,52,2026-10-05-12-17-25 +0000,wapo,"Spain’s Pedro Sánchez, main critic of Trump in...",https://www.washingtonpost.com/world/2026/10/0...
259,49,2026-10-04-21-17-29 +0000,chitri,US Air Force removes all bombers from British ...,https://www.chicagotribune.com/2026/10/04/us-a...
21,40,2026-10-05-14-30-31 +0000,bbc,Teenager's hand blown off during confrontation...,https://www.bbc.co.uk/news/articles/c9zrdmxp4v...
29,39,2026-10-05-14-19-09 +0000,nypost,Ukraine claims its attacks have taken out more...,https://nypost.com/2026/10/05/world-news/ukrai...
89,38,2026-10-05-11-34-59 +0000,bbc,Flydubai co-pilot planned to crash plane into ...,https://www.bbc.co.uk/news/articles/cm3691y79x...
37,37,2026-10-05-14-05-37 +0000,wapo,"Dennis Hastert, ex-House speaker whose sex abu...",https://www.washingtonpost.com/obituaries/2026...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)