## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-22-22-58-31 +0000,nyt,France Chose Thousands of New Mayors on Sunday...,https://www.nytimes.com/2026/03/22/world/europ...
1,2026-03-22-22-51-01 +0000,startribune,Enhanced role for immigration officers at US a...,https://www.startribune.com/enhanced-role-for-...
2,2026-03-22-22-49-04 +0000,nypost,California launches probe into price gouging a...,https://nypost.com/2026/03/22/us-news/socal-la...
3,2026-03-22-22-48-29 +0000,nyt,Israel Thought It Could Spur Rebellion Inside ...,https://www.nytimes.com/2026/03/22/us/politics...
4,2026-03-22-22-44-01 +0000,nyt,Iran War Live Updates: Tehran Is Defiant After...,https://www.nytimes.com/live/2026/03/22/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2638/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
40   trump     29
32    iran     23
35     war     14
3      new      9
146   will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
50,2026-03-22-20-01-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...,96
69,2026-03-22-18-52-03 +0000,nypost,Scott Bessent suggests Trump may ‘escalate to ...,https://nypost.com/2026/03/22/us-news/scott-be...,95
4,2026-03-22-22-44-01 +0000,nyt,Iran War Live Updates: Tehran Is Defiant After...,https://www.nytimes.com/live/2026/03/22/world/...,84
138,2026-03-22-10-06-06 +0000,wapo,Trump threatens to ‘obliterate’ Iran’s power p...,https://www.washingtonpost.com/world/2026/03/2...,80
79,2026-03-22-17-51-18 +0000,wapo,Joe Kent says he wants Trump to hear MAGA oppo...,https://www.washingtonpost.com/national-securi...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
50,96,2026-03-22-20-01-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
157,63,2026-03-22-09-00-50 +0000,wapo,"One gas station, two drivers and three fill-up...",https://www.washingtonpost.com/nation/2026/03/...
185,42,2026-03-22-00-47-52 +0000,nypost,Over 100 Israeli civilians wounded by new Ira...,https://nypost.com/2026/03/21/world-news/over-...
127,34,2026-03-22-12-52-00 +0000,wsj,South Korean President Lee Jae Myung has nomin...,https://www.wsj.com/economy/central-banking/so...
113,32,2026-03-22-14-48-00 +0000,wsj,Here’s a look at the three lawmakers seen as b...,https://www.wsj.com/politics/if-mike-johnson-g...
179,30,2026-03-22-01-04-57 +0000,bbc,"Robert Mueller, ex-FBI chief who led Trump-Rus...",https://www.bbc.com/news/articles/c8dlj6gv0q6o...
153,29,2026-03-22-09-01-25 +0000,nyt,"Despite Spiking Oil Prices, There’s No Talk of...",https://www.nytimes.com/2026/03/22/us/texas-oi...
52,28,2026-03-22-19-52-07 +0000,nypost,NYC first lady Rama Duwaji created artwork for...,https://nypost.com/2026/03/22/us-news/nyc-firs...
138,28,2026-03-22-10-06-06 +0000,wapo,Trump threatens to ‘obliterate’ Iran’s power p...,https://www.washingtonpost.com/world/2026/03/2...
150,25,2026-03-22-09-30-00 +0000,wsj,"Young people, who are just starting their care...",https://www.wsj.com/economy/jobs/ai-jobs-young...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)