## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-11-53-21 +0000,bbc,Ship sinks and crew missing after Black Sea dr...,https://www.bbc.co.uk/news/articles/c8ly0v5r60...
1,2026-10-06-11-51-26 +0000,bbc,Kenya confirms its first Ebola death as outbre...,https://www.bbc.co.uk/news/articles/cqzrd7v1j1...
2,2026-10-06-11-50-15 +0000,nyt,Why These 5 Methods Used in Executions Have St...,https://www.nytimes.com/2026/10/06/us/executio...
3,2026-10-06-11-49-37 +0000,nyt,How Alaska’s Fish Became a Defining Issue for ...,https://www.nytimes.com/2026/10/06/us/politics...
4,2026-10-06-11-49-28 +0000,bbc,Young Tories on if their party should do a dea...,https://www.bbc.co.uk/news/videos/c670p4n98d4n...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2333/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
191  trump     34
77     new     22
264     de     16
345   dies     16
649  house     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
249,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,166
203,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,128
336,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,95
79,2026-10-06-10-00-00 +0000,wsj,"Disney’s top lawyer, Horacio Gutiérrez, is tak...",https://www.wsj.com/business/media/disneys-top...,93
29,2026-10-06-11-13-27 +0000,bbc,California leaders hit back after Trump says I...,https://www.bbc.co.uk/news/articles/c6r7yn8pkn...,86

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
249,166,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
203,128,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
336,95,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
220,66,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
179,53,2026-10-06-02-22-24 +0000,bbc,Fort Hood shooter to be executed by firing squ...,https://www.bbc.co.uk/news/articles/cq8ezkkkrp...
152,48,2026-10-06-05-30-50 +0000,nypost,Concerns over possible Iranian drone attack pr...,https://nypost.com/2026/10/06/world-news/conce...
62,45,2026-10-06-10-09-00 +0000,wsj,Hackers Use Chinese AI Tool to Hit South Korea...,https://www.wsj.com/world/asia/hackers-use-chi...
302,42,2026-10-05-19-30-50 +0000,bbc,Spain PM pins hopes on housing crisis to help ...,https://www.bbc.co.uk/news/articles/ck5yn81qqd...
46,38,2026-10-06-10-48-00 +0000,wsj,Voters from the left and the right are finding...,https://www.wsj.com/politics/policy/from-left-...
81,37,2026-10-06-10-00-00 +0000,latimes,'Things got out of control': Video of alleged ...,https://www.latimes.com/california/story/2026-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)