## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-15-01-18-35 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...
1,2026-04-15-01-14-06 +0000,nypost,Family members of Sinaloa Cartel arrested as $...,https://nypost.com/2026/04/14/us-news/family-m...
2,2026-04-15-01-12-35 +0000,nypost,Eric Swalwell’s brother breaks silence on sexu...,https://nypost.com/2026/04/14/us-news/eric-swa...
3,2026-04-15-01-11-18 +0000,nyt,Swalwell’s Exit Injects ‘Chaos’ Into Californi...,https://www.nytimes.com/2026/04/14/us/californ...
4,2026-04-15-01-05-46 +0000,bbc,King will not meet Epstein survivors on US visit,https://www.bbc.com/news/articles/cvg44q1zdeno...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2616/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
0        iran     40
180     trump     31
1         war     22
20   swalwell     19
64        new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
227,2026-04-14-15-49-23 +0000,nypost,Trump tells The Post US-Iran talks ‘could be h...,https://nypost.com/2026/04/14/us-news/presiden...,106
0,2026-04-15-01-18-35 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...,104
258,2026-04-14-13-53-29 +0000,nyt,Two Iran-Linked Ships Passed Through Strait of...,https://www.nytimes.com/2026/04/13/world/middl...,103
212,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...,102
291,2026-04-14-11-14-54 +0000,nypost,"US, Iran may resume war talks this week despit...",https://nypost.com/2026/04/14/world-news/us-ir...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
227,106,2026-04-14-15-49-23 +0000,nypost,Trump tells The Post US-Iran talks ‘could be h...,https://nypost.com/2026/04/14/us-news/presiden...
93,75,2026-04-14-21-05-47 +0000,nypost,Millionaire who sheltered Eric Swalwell as sex...,https://nypost.com/2026/04/14/us-news/milliona...
349,68,2026-04-14-04-34-00 +0000,wsj,China’s export momentum slowed sharply in Marc...,https://www.wsj.com/economy/trade/china-export...
252,58,2026-04-14-14-21-40 +0000,nypost,US boasts no ships moved through Strait of Hor...,https://nypost.com/2026/04/14/world-news/iran-...
359,55,2026-04-14-02-47-00 +0000,wsj,Canadian Prime Minister Mark Carney has secure...,https://www.wsj.com/world/americas/canadas-car...
198,52,2026-04-14-16-48-00 +0000,wsj,"Lucid Secures $750 Million in New Funding, Nam...",https://www.wsj.com/business/entrepreneurship/...
158,49,2026-04-14-18-42-00 +0000,wsj,A disclosure from Fed chair nominee Kevin Wars...,https://www.wsj.com/finance/investing/fed-nomi...
34,42,2026-04-14-23-55-12 +0000,nypost,Ex-UCLA campus gynecologist learns fate as his...,https://nypost.com/2026/04/14/us-news/ex-ucla-...
14,41,2026-04-15-00-52-00 +0000,wsj,Maine lawmakers passed a ban on large data-cen...,https://www.wsj.com/politics/policy/maine-lawm...
63,39,2026-04-14-22-43-55 +0000,nypost,Female stranger randomly shoves 71-year-old to...,https://nypost.com/2026/04/14/us-news/female-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)