## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-19-09-04-33 +0000,nyt,How Japan’s Leader Sanae Takaichi Found Her Vo...,https://www.nytimes.com/2026/03/19/world/asia/...
1,2026-03-19-09-04-15 +0000,nyt,What to Know About State Laws on Ten Commandme...,https://www.nytimes.com/2026/03/19/us/ten-comm...
2,2026-03-19-09-03-33 +0000,nyt,Elon Musk Whips Up Frenzy Against John Thune O...,https://www.nytimes.com/2026/03/19/us/politics...
3,2026-03-19-09-02-44 +0000,nyt,She Killed a Family With Her Speeding Car. Is ...,https://www.nytimes.com/2026/03/19/us/san-fran...
4,2026-03-19-09-02-31 +0000,nyt,Useful Local Travel Apps to Download Before Yo...,https://www.nytimes.com/2026/03/19/travel/loca...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2484/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
61     iran     64
62      war     37
73    trump     34
624  chavez     25
623   cesar     23

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
189,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...,182
405,2026-03-18-11-00-00 +0000,wsj,"Damian Paletta, The Wall Street Journal’s Wash...",https://www.wsj.com/politics/answering-your-qu...,172
8,2026-03-19-09-01-39 +0000,nyt,Iran War Live Updates: Qatar Reports More Atta...,https://www.nytimes.com/live/2026/03/19/world/...,171
361,2026-03-18-14-35-35 +0000,nypost,Oil spikes after Iran says world’s largest gas...,https://nypost.com/2026/03/18/world-news/oil-s...,167
307,2026-03-18-17-00-21 +0000,nyt,Trump Renews Demand for Rate Cuts as Fed Grapp...,https://www.nytimes.com/live/2026/03/18/busine...,163

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
189,182,2026-03-18-21-30-42 +0000,nypost,Trump threatens to ‘massively blow up’ Iran ga...,https://nypost.com/2026/03/18/world-news/exten...
8,107,2026-03-19-09-01-39 +0000,nyt,Iran War Live Updates: Qatar Reports More Atta...,https://www.nytimes.com/live/2026/03/19/world/...
93,89,2026-03-19-02-02-49 +0000,nyt,"After Cesar Chavez Allegations, California Sex...",https://www.nytimes.com/2026/03/18/us/californ...
204,70,2026-03-18-21-06-00 +0000,wsj,The Fed left rates unchanged as an oil shock t...,https://www.wsj.com/economy/central-banking/fe...
108,60,2026-03-19-01-22-00 +0000,wsj,President Trump has spent months talking about...,https://www.wsj.com/economy/central-banking/tr...
62,57,2026-03-19-04-48-51 +0000,nypost,New details emerge about New Mexico US Air For...,https://nypost.com/2026/03/19/us-news/new-deta...
376,50,2026-03-18-13-51-07 +0000,cbc,Bank of Canada holds key interest rate at 2.25...,https://www.cbc.ca/news/business/bank-of-canad...
247,40,2026-03-18-19-35-27 +0000,cbc,U.S. civil rights leader Dolores Huerta says C...,https://www.cbc.ca/news/world/cesar-chavez-all...
400,40,2026-03-18-11-14-13 +0000,nypost,Iran killed elderly Israeli couple in ‘retalia...,https://nypost.com/2026/03/18/world-news/iran-...
316,37,2026-03-18-16-48-00 +0000,wsj,6 of the Best Wealth Management Firms: Well-Kn...,https://www.wsj.com/buyside/personal-finance/f...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)