## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-20-11-00-00 +0000,nypost,Here’s why Warner CEO David Zaslav may actuall...,https://nypost.com/2026/03/20/media/heres-why-...
1,2026-03-20-11-00-00 +0000,missionlocal,"Ed Siu, Chinatown’s ‘complaint guy,’ isn’t her...",https://missionlocal.org/2026/03/sf-chinatown-...
2,2026-03-20-10-59-00 +0000,wsj,Russia Central Bank Lowers Key Rate Despite Oi...,https://www.wsj.com/articles/russia-central-ba...
3,2026-03-20-10-59-00 +0000,wsj,The havoc Iran is wreaking on energy markets c...,https://www.wsj.com/politics/for-the-white-hou...
4,2026-03-20-10-57-38 +0000,bbc,Mexican teen dies while being held in US immig...,https://www.bbc.com/news/articles/cp84n0kn902o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
30     iran     49
92    trump     41
94      war     34
26      oil     21
135  prices     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
157,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...,180
243,2026-03-19-20-48-00 +0000,wsj,Trump’s Iran War Frays Ties With Allies as Oil...,https://www.wsj.com/world/trumps-iran-war-fray...,170
185,2026-03-19-23-19-00 +0000,bbc,Are US and Israel aligned on Iran war? Deciphe...,https://www.bbc.com/news/articles/c8x7leknlywo...,160
316,2026-03-19-17-03-13 +0000,nyt,Iran War Narrows Fed’s Path to Rate Cuts as Tr...,https://www.nytimes.com/2026/03/19/business/fe...,143
21,2026-03-20-10-08-23 +0000,nyt,Iran War Live Updates: Oil Prices Retreat and ...,https://www.nytimes.com/live/2026/03/20/world/...,136

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
157,180,2026-03-20-00-31-59 +0000,nyt,Trump Administration Faces Public Jitters as O...,https://www.nytimes.com/2026/03/19/world/middl...
254,70,2026-03-19-20-30-00 +0000,latimes,California quickly moves to rename Cesar Chave...,https://www.latimes.com/california/story/2026-...
151,60,2026-03-20-01-00-00 +0000,wsj,A New York congressional race has a new X fact...,https://www.wsj.com/politics/policy/ai-lobbyin...
182,51,2026-03-19-23-29-05 +0000,bbc,Stock markets rattled and energy prices soar a...,https://www.bbc.com/news/articles/c78x83lpgngo...
184,48,2026-03-19-23-23-00 +0000,wsj,A federal panel approved a commemorative gold ...,https://www.wsj.com/politics/policy/trump-gold...
118,47,2026-03-20-03-22-17 +0000,nypost,Japanese prime minister wishes ‘good looking’ ...,https://nypost.com/2026/03/19/us-news/japanese...
341,45,2026-03-19-15-38-16 +0000,bbc,Three Palestinian women killed in beauty salon...,https://www.bbc.com/news/articles/c0ljl23plpzo...
5,44,2026-03-20-10-55-24 +0000,nypost,University of Alabama student James Gracey see...,https://nypost.com/2026/03/20/world-news/unive...
229,43,2026-03-19-21-07-04 +0000,cbc,Trump to Japan's PM: 'Why didn’t you tell me a...,https://www.cbc.ca/player/play/9.7135276?cmp=rss
218,40,2026-03-19-21-33-00 +0000,wsj,"A capital rules win for banks, the $100 millio...",https://www.wsj.com/politics/policy/big-banks-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)