## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-26-20-29-57 +0000,nypost,Long Island driver killed in vicious crash tha...,https://nypost.com/2026/05/26/us-news/long-isl...
1,2026-05-26-20-29-22 +0000,nyt,Judge Lets Stand a Florida House Map That Coul...,https://www.nytimes.com/2026/05/26/us/florida-...
2,2026-05-26-20-29-15 +0000,nyt,The Wars in Ukraine and Iran Are More Alike Th...,https://www.nytimes.com/2026/05/26/world/middl...
3,2026-05-26-20-27-00 +0000,wsj,New Congressional Maps Blocked in Alabama and ...,https://www.wsj.com/us-news/law/alabama-plan-f...
4,2026-05-26-20-25-50 +0000,bbc,Nasa unveils next steps to build permanent Moo...,https://www.bbc.com/news/articles/c39228nxyr4o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
20      iran     34
124    trump     24
59   strikes     19
88      deal     14
110    first     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...,109
7,2026-05-26-20-19-12 +0000,nyt,Iran War Live Updates: U.S. Saw Threats From I...,https://www.nytimes.com/live/2026/05/26/world/...,104
206,2026-05-26-11-58-30 +0000,wapo,Iran threatens retaliation after U.S. strikes ...,https://www.washingtonpost.com/world/2026/05/2...,98
179,2026-05-26-13-51-48 +0000,nypost,Trump to hold rare cabinet meeting at Camp Dav...,https://nypost.com/2026/05/26/us-news/trump-to...,92
33,2026-05-26-19-46-30 +0000,nyt,Iran Threatens to Renew Strikes Against U.S. A...,https://www.nytimes.com/2026/05/26/world/middl...,87

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,109,2026-05-26-11-00-00 +0000,wsj,Here are three political story lines to watch ...,https://www.wsj.com/politics/three-big-politic...
33,53,2026-05-26-19-46-30 +0000,nyt,Iran Threatens to Renew Strikes Against U.S. A...,https://www.nytimes.com/2026/05/26/world/middl...
119,50,2026-05-26-16-37-20 +0000,nypost,Spencer Pratt reveals stunning West Coast dest...,https://nypost.com/2026/05/26/us-news/spencer-...
111,42,2026-05-26-16-51-30 +0000,nypost,Ferrari’s new $640K electric car already a mas...,https://nypost.com/2026/05/26/business/ferrari...
57,38,2026-05-26-19-10-27 +0000,nypost,Race against time to snare California dad who ...,https://nypost.com/2026/05/26/us-news/race-aga...
171,37,2026-05-26-14-04-51 +0000,bbc,White House gunman had previous run-ins with S...,https://www.bbc.com/news/articles/c1l22pg12mpo...
104,35,2026-05-26-17-14-00 +0000,wsj,Factory activity in Canada rose strongly last ...,https://www.wsj.com/economy/canada-factory-sal...
154,33,2026-05-26-14-44-44 +0000,bbc,DR Congo seek World Cup ticket refunds after E...,https://www.bbc.com/sport/football/articles/c0...
317,31,2026-05-25-21-07-00 +0000,wsj,Texas Sen. John Cornyn’s primary runoff agains...,https://www.wsj.com/politics/elections/texas-s...
131,31,2026-05-26-15-55-06 +0000,nyt,Israel Steps Up Lebanon Offensive as U.S. Push...,https://www.nytimes.com/2026/05/26/world/middl...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)