## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-31-08-53-10 +0000,nypost,Death toll tops 900 in Nepal-Tibet flooding as...,https://nypost.com/2026/08/31/world-news/death...
1,2026-08-31-08-50-00 +0000,wsj,U.S. Stock Futures Little Changed as Markets W...,https://www.wsj.com/finance/investing/u-s-stoc...
2,2026-08-31-08-39-58 +0000,nyt,Nepal Turns to Mass Burials as Thousands Remai...,https://www.nytimes.com/2026/08/30/world/asia/...
3,2026-08-31-08-34-25 +0000,bbc,US and Iran trade strikes for first time in weeks,https://www.bbc.co.uk/news/articles/cx2z72x5z1...
4,2026-08-31-08-30-26 +0000,chitri,Today in History: Princess Diana killed,https://www.chicagotribune.com/2026/08/31/toda...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2458/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
358    trump     15
149      new     13
3      nepal     12
9    missing     11
229      off     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
6,2026-08-31-08-17-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...,59
75,2026-08-30-23-05-36 +0000,nypost,"At least 8 dead, 18 missing after ferry carryi...",https://nypost.com/2026/08/30/world-news/at-le...,56
39,2026-08-31-02-46-36 +0000,nyt,One Dead and 15 Potentially Missing at Grand C...,https://www.nytimes.com/2026/08/30/us/grand-ca...,55
143,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,53
25,2026-08-31-04-30-29 +0000,wapo,"One person dead, about 15 more may be missing ...",https://www.washingtonpost.com/nation/2026/08/...,52

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
6,59,2026-08-31-08-17-25 +0000,bbc,One dead and more than a dozen missing after '...,https://www.bbc.co.uk/news/articles/clylkjyez1...
143,53,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...
60,43,2026-08-31-00-00-00 +0000,wsj,The young rent-stabilized tenants of New York ...,https://www.wsj.com/economy/housing/these-youn...
152,41,2026-08-30-16-14-00 +0000,wsj,"James Talarico, the Democratic candidate for S...",https://www.wsj.com/politics/policy/talarico-i...
216,40,2026-08-30-09-30-00 +0000,wsj,Fed Chairman Kevin Warsh put to rest some conc...,https://www.wsj.com/economy/central-banking/wa...
187,40,2026-08-30-12-22-38 +0000,cbc,At least 8 dead after ferry carrying nearly 27...,https://www.cbc.ca/news/world/ferry-capsize-cy...
0,37,2026-08-31-08-53-10 +0000,nypost,Death toll tops 900 in Nepal-Tibet flooding as...,https://nypost.com/2026/08/31/world-news/death...
176,32,2026-08-30-14-16-40 +0000,chitri,"Iran’s leader calls for Muslim unity, NBC crew...",https://www.chicagotribune.com/2026/08/30/nbc-...
86,27,2026-08-30-22-00-06 +0000,nypost,"California woman, 22, diagnosed with cancer af...",https://nypost.com/2026/08/30/us-news/californ...
158,27,2026-08-30-15-48-43 +0000,nypost,RNC chair claims Dem majority in Congress will...,https://nypost.com/2026/08/30/us-news/dem-majo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)