## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-31-19-12-00 +0000,nyt,Is This the Future of Air Travel?,https://www.nytimes.com/video/business/1000000...
1,2026-05-31-19-09-45 +0000,startribune,Uptown’s identity crisis is at the heart of it...,https://www.startribune.com/uptowns-identity-c...
2,2026-05-31-19-08-53 +0000,nyt,"Release of Tina Peters, Election Denier and Fo...",https://www.nytimes.com/2026/05/31/us/tina-pet...
3,2026-05-31-19-07-47 +0000,bbc,Brazil monitors two patients for possible Ebol...,https://www.bbc.com/news/articles/cy72z48zd7po...
4,2026-05-31-19-05-42 +0000,bbc,Dead whale towed ashore in Denmark ahead of au...,https://www.bbc.com/news/articles/cpwpl9vn0yqo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2358/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
45   trump     18
121    new      8
145     he      7
59     nyc      7
168    out      6

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
158,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...,56
85,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...,50
109,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...,47
144,2026-05-30-23-21-00 +0000,wsj,After several musicians dropped out of the fes...,https://www.wsj.com/politics/policy/trump-name...,43
80,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...,40

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
158,56,2026-05-30-20-59-39 +0000,nypost,Trump rages over fed judge who ordered his nam...,https://nypost.com/2026/05/30/us-news/trump-ra...
85,50,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...
80,40,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...
26,30,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...
153,30,2026-05-30-22-00-00 +0000,nypost,Spencer Pratt gets most support in these LA ne...,https://nypost.com/2026/05/30/us-news/spencer-...
124,30,2026-05-31-02-39-00 +0000,wsj,China’s manufacturing activity stayed flat in ...,https://www.wsj.com/economy/china-manufacturin...
8,26,2026-05-31-18-56-56 +0000,nypost,NYC murder-suicide victim begged neighbor for ...,https://nypost.com/2026/05/31/us-news/nyc-murd...
83,25,2026-05-31-13-45-48 +0000,cbc,Israeli army captures strategic castle in Leba...,https://www.cbc.ca/news/world/israel-captures-...
53,25,2026-05-31-16-00-00 +0000,wsj,"American capitalism is at a crossroads, facing...",https://www.wsj.com/economy/us-capitalism-econ...
144,25,2026-05-30-23-21-00 +0000,wsj,After several musicians dropped out of the fes...,https://www.wsj.com/politics/policy/trump-name...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)