## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-19-08-41-46 +0000,nyt,"Who Is Andy Burnham, the Man Who Could Be Brit...",https://www.nytimes.com/2026/06/18/world/europ...
1,2026-06-19-08-38-42 +0000,bbc,What is Burnham's path to becoming Labour lead...,https://www.bbc.com/news/articles/c3631k30xjlo...
2,2026-06-19-08-37-31 +0000,bbc,Warning over 'fragile' public finances as borr...,https://www.bbc.com/news/articles/cqx1e8nrwgvo...
3,2026-06-19-08-26-00 +0000,wsj,Dollar Rises to One-Year High on Increased Pro...,https://www.wsj.com/economy/central-banking/do...
4,2026-06-19-08-25-29 +0000,bbc,The moment Andy Burnham won Makerfield by-elec...,https://www.bbc.com/news/videos/c892p5vdl3eo?a...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2595/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
78    iran     50
81    deal     35
73   trump     29
264    war     17
115  world     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
207,2026-06-18-19-05-00 +0000,wsj,Trump’s Deal Sidesteps Key Reasons He Went to ...,https://www.wsj.com/world/middle-east/trumps-d...,149
84,2026-06-19-01-34-00 +0000,bbc,US lifts naval blockade as Iran's supreme lead...,https://www.bbc.com/news/articles/c8r2eejdd35o...,144
335,2026-06-18-10-40-51 +0000,nypost,At least 12 tankers pass through Strait of Hor...,https://nypost.com/2026/06/18/world-news/three...,138
13,2026-06-19-08-00-00 +0000,cbc,Trump routinely trashes the Obama-era Iran nuc...,https://www.cbc.ca/news/world/trump-iran-deal-...,138
221,2026-06-18-18-25-12 +0000,nypost,Senate Armed Services chairman Roger Wicker ca...,https://nypost.com/2026/06/18/us-news/senate-a...,138

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
207,149,2026-06-18-19-05-00 +0000,wsj,Trump’s Deal Sidesteps Key Reasons He Went to ...,https://www.wsj.com/world/middle-east/trumps-d...
80,66,2026-06-19-01-50-00 +0000,wsj,What started as a series of promotional interv...,https://www.wsj.com/politics/policy/jd-vances-...
187,62,2026-06-18-20-12-00 +0000,wsj,Defense Secretary Pete Hegseth ratcheted up pr...,https://www.wsj.com/politics/national-security...
82,61,2026-06-19-01-42-00 +0000,wsj,The architects of California’s proposed billio...,https://www.wsj.com/politics/policy/union-behi...
317,58,2026-06-18-12-53-00 +0000,wsj,The Bank of England left its key interest rate...,https://www.wsj.com/economy/central-banking/bo...
28,56,2026-06-19-07-04-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...
67,56,2026-06-19-02-47-22 +0000,latimes,Video: Shots fired near Koreatown World Cup wa...,https://www.latimes.com/california/story/2026-...
269,45,2026-06-18-15-51-00 +0000,wsj,Supreme Court Rules Government Can’t Ban All D...,https://www.wsj.com/us-news/law/supreme-court-...
361,42,2026-06-18-08-51-35 +0000,nypost,"Ukraine hits Moscow oil refinery, disrupting c...",https://nypost.com/2026/06/18/world-news/ukrai...
182,42,2026-06-18-20-28-40 +0000,nypost,Obama and Michelle take digs at Trump in 3-hou...,https://nypost.com/2026/06/18/us-news/obama-an...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)