## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-01-02-47-39 +0000,nypost,Iran digs out underground missile sites during...,https://nypost.com/2026/05/31/world-news/iran-...
1,2026-06-01-02-46-00 +0000,wsj,Dollar Likely to Stay Bid Near 160 Yen,https://www.wsj.com/finance/currencies/yen-con...
2,2026-06-01-02-39-35 +0000,nyt,Israel Captures Crusader Castle That Symbolize...,https://www.nytimes.com/2026/05/31/world/middl...
3,2026-06-01-02-33-12 +0000,nyt,Young Moviegoers Power ‘Backrooms’ to $82 Mill...,https://www.nytimes.com/2026/05/31/business/me...
4,2026-06-01-02-28-00 +0000,wsj,China Private Factory Activity Gauge Indicates...,https://www.wsj.com/economy/china-private-fact...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2443/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
124       trump     21
41   california     12
111          he     10
31        china      9
2           out      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
181,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...,63
157,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...,59
12,2026-06-01-01-58-23 +0000,nypost,California governor candidate Steve Hilton rev...,https://nypost.com/2026/05/31/us-news/californ...,55
96,2026-05-31-19-50-13 +0000,nypost,Bitter California Republican feud turns toxic ...,https://nypost.com/2026/05/31/us-news/bitter-c...,55
117,2026-05-31-16-57-08 +0000,nypost,Donald Trump’s damning five-word verdict on Ca...,https://nypost.com/2026/05/31/us-news/trumps-d...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
181,63,2026-05-31-09-01-06 +0000,nyt,He Was Satirized on British TV. Now He’s Trump...,https://www.nytimes.com/2026/05/31/us/steve-hi...
157,46,2026-05-31-12-32-58 +0000,nypost,Maine Dem candidate Graham Platner sends wife ...,https://nypost.com/2026/05/31/us-news/graham-p...
151,41,2026-05-31-14-15-12 +0000,nypost,Mamdani skips Israel Day Parade to instead tal...,https://nypost.com/2026/05/31/us-news/mamdani-...
112,39,2026-05-31-17-12-49 +0000,latimes,Your last-minute guide to the Los Angeles city...,https://www.latimes.com/california/story/2026-...
0,30,2026-06-01-02-47-39 +0000,nypost,Iran digs out underground missile sites during...,https://nypost.com/2026/05/31/world-news/iran-...
70,30,2026-05-31-21-27-00 +0000,wsj,The congressional recess is typically a coolin...,https://www.wsj.com/politics/policy/a-new-woun...
9,29,2026-06-01-02-12-56 +0000,nypost,Far-left influencer Hasan Piker defends pro-Ch...,https://nypost.com/2026/05/31/us-news/hasan-pi...
131,29,2026-05-31-16-00-00 +0000,wsj,"American capitalism is at a crossroads, facing...",https://www.wsj.com/economy/us-capitalism-econ...
10,25,2026-06-01-02-00-00 +0000,wsj,California Democrats head to a primary electio...,https://www.wsj.com/politics/elections/how-cal...
154,25,2026-05-31-13-45-48 +0000,cbc,Israeli army captures strategic castle in Leba...,https://www.cbc.ca/news/world/israel-captures-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)