## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-24-12-57-17 +0000,nyt,U.N. Live Updates: Abbas and Netanyahu to Deli...,https://www.nytimes.com/live/2026/09/24/world/...
1,2026-09-24-12-55-14 +0000,nyt,Ancient Wall Found in Paris Provides Clues to ...,https://www.nytimes.com/2026/09/23/world/europ...
2,2026-09-24-12-55-00 +0000,wsj,Bob Chapek Is So Not Over Getting Fired From D...,https://www.wsj.com/business/media/bob-chapek-...
3,2026-09-24-12-49-32 +0000,bbc,Ethiopia's army says it has repelled attacks i...,https://www.bbc.co.uk/news/articles/cqevwm09w4...
4,2026-09-24-12-47-00 +0000,wsj,"Leonardo, Fincantieri Get $4.2 Billion Destroy...",https://www.wsj.com/world/europe/leonardo-finc...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2429/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
43   trump     82
190    new     36
240     xi     25
235  china     22
251     ai     21

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
150,2026-09-24-07-03-29 +0000,nypost,"Judge blocks Trump’s White House ban on CNN, M...",https://nypost.com/2026/09/24/us-news/judge-bl...,187
53,2026-09-24-10-59-00 +0000,wsj,As President Trump and China’s Xi Jinping prep...,https://www.wsj.com/politics/policy/as-trump-a...,186
29,2026-09-24-11-42-00 +0000,wsj,A federal judge ordered President Trump to res...,https://www.wsj.com/politics/policy/judge-orde...,184
196,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...,182
247,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,182

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
150,187,2026-09-24-07-03-29 +0000,nypost,"Judge blocks Trump’s White House ban on CNN, M...",https://nypost.com/2026/09/24/us-news/judge-bl...
199,112,2026-09-24-00-43-00 +0000,wsj,The last time Venezuelan leader Delcy Rodrígue...,https://www.wsj.com/world/americas/u-n-visit-s...
196,100,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...
415,98,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
397,73,2026-09-23-17-04-19 +0000,nypost,Trump’s Board of Peace announces $2.45B first-...,https://nypost.com/2026/09/23/us-news/trumps-b...
460,59,2026-09-23-14-44-03 +0000,wapo,Another U.S. service member dies amid Iran war...,https://www.washingtonpost.com/politics/2026/0...
35,54,2026-09-24-11-22-00 +0000,wsj,The Morning Risk Report: The Group Chat Where ...,https://www.wsj.com/risk-compliance-journal/th...
192,53,2026-09-24-01-00-00 +0000,wsj,"The AI build-out is making history, dwarfing t...",https://www.wsj.com/economy/the-ai-build-out-i...
296,51,2026-09-23-20-45-00 +0000,wsj,Canada’s Carney Open to U.S. Trade Deal but Wo...,https://www.wsj.com/world/europe/canadas-carne...
43,45,2026-09-24-11-00-01 +0000,startribune,What you need to know about the saga involving...,https://www.startribune.com/what-you-need-to-k...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)