## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-19-23-01-48 +0000,nypost,1 dead after small plane crashes into Florida ...,https://nypost.com/2026/04/19/us-news/1-dead-i...
1,2026-04-19-23-00-00 +0000,wsj,A dispute between Defense Secretary Pete Hegse...,https://www.wsj.com/politics/national-security...
2,2026-04-19-22-58-05 +0000,nypost,Here are the wackiest mansions in LA – and the...,https://nypost.com/2026/04/19/us-news/inside-l...
3,2026-04-19-22-55-02 +0000,startribune,8 children between the ages of 1 and 12 are de...,https://www.startribune.com/8-children-between...
4,2026-04-19-22-54-51 +0000,bbc,"Eight children killed in Louisiana shooting, p...",https://www.bbc.com/news/articles/c0q9v1p2dd2o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2579/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
83   trump     27
42    iran     14
43     war     14
51     new     11
39  police     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
111,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...,89
167,2026-04-19-03-49-45 +0000,nypost,JD Vance ‘grateful’ to Pope Leo for easing ten...,https://nypost.com/2026/04/18/world-news/jd-va...,86
5,2026-04-19-22-54-28 +0000,nyt,Iran War Live Updates: U.S. Attacks Iranian Ca...,https://www.nytimes.com/live/2026/04/19/world/...,75
92,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...,75
174,2026-04-19-01-00-00 +0000,wsj,Behind Trump’s public bravado on the war in Ir...,https://www.wsj.com/politics/national-security...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
111,89,2026-04-19-12-17-29 +0000,nypost,"Iran War negotiations will resume this week, T...",https://nypost.com/2026/04/19/us-news/iran-war...
14,45,2026-04-19-22-05-56 +0000,nyt,8 Children Killed in Domestic Mass Shooting in...,https://www.nytimes.com/2026/04/19/us/shrevepo...
1,35,2026-04-19-23-00-00 +0000,wsj,A dispute between Defense Secretary Pete Hegse...,https://www.wsj.com/politics/national-security...
39,35,2026-04-19-20-54-46 +0000,nyt,U.S. Attacks Iranian Cargo Ship as Both Countr...,https://www.nytimes.com/2026/04/19/world/middl...
92,34,2026-04-19-15-54-00 +0000,wsj,Trump is grappling with his own fears about th...,https://www.wsj.com/politics/trumps-fears-on-t...
178,33,2026-04-19-00-00-00 +0000,wsj,Virginians face a ballot measure asking them w...,https://www.wsj.com/politics/elections/virgini...
26,26,2026-04-19-21-43-40 +0000,nypost,"Cops fire rubber bullets, tear gas to fend off...",https://nypost.com/2026/04/19/us-news/cops-fir...
167,26,2026-04-19-03-49-45 +0000,nypost,JD Vance ‘grateful’ to Pope Leo for easing ten...,https://nypost.com/2026/04/18/world-news/jd-va...
83,25,2026-04-19-16-49-51 +0000,nypost,"Japan’s Princess Mako, who gave up royal life ...",https://nypost.com/2026/04/19/world-news/japan...
36,22,2026-04-19-21-02-04 +0000,nypost,ICE issues furious six-word message to Califor...,https://nypost.com/2026/04/19/us-news/ice-issu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)