## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-27-21-51-46 +0000,nyt,Live Updates: Opposition Parties Ahead of Neta...,https://www.nytimes.com/live/2026/10/27/world/...
1,2026-10-27-21-51-16 +0000,startribune,Show stopper: Minnesota Opera postpones premie...,https://www.startribune.com/show-stopper-minne...
2,2026-10-27-21-49-35 +0000,nypost,California utility grid reliabilty faces quest...,https://nypost.com/2026/10/27/science/californ...
3,2026-10-27-21-49-04 +0000,nyt,"In Israel’s Election, It’s Nationalism vs. Fou...",https://www.nytimes.com/2026/10/27/world/middl...
4,2026-10-27-21-47-53 +0000,nypost,"Rapist Alexander brothers still face lawsuits,...",https://nypost.com/2026/10/27/us-news/plenty-o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2670/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
45       trump     34
30    election     33
29      israel     20
17         out     14
19  california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
72,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...,107
17,2026-10-27-21-35-10 +0000,startribune,Exit polls suggest a rebuke of Netanyahu but n...,https://www.startribune.com/voters-in-israel-w...,97
269,2026-10-27-11-04-05 +0000,chitri,"No clear winner in Israeli election, exit poll...",https://www.chicagotribune.com/2026/10/27/isra...,93
386,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...,86
325,2026-10-27-08-25-46 +0000,nypost,Polls open in Israel for country’s first elect...,https://nypost.com/2026/10/27/world-news/elect...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
72,107,2026-10-27-20-14-29 +0000,nypost,"Netanyahu loses seats, trails challenger Gadi ...",https://nypost.com/2026/10/27/world-news/netan...
386,86,2026-10-26-23-52-00 +0000,wsj,A U.S. court rejected a Trump administration r...,https://www.wsj.com/politics/policy/court-reje...
225,56,2026-10-27-14-03-00 +0000,wsj,Conservatives and liberals agree on some of th...,https://www.wsj.com/politics/policy/conservati...
396,48,2026-10-26-22-56-09 +0000,latimes,Former Bass opponent Rick Caruso now says he w...,https://www.latimes.com/california/story/2026-...
97,47,2026-10-27-19-39-42 +0000,nypost,Nithya Raman torches LAPD in yet another vicio...,https://nypost.com/2026/10/27/us-news/nithya-r...
338,46,2026-10-27-06-59-20 +0000,nyt,Flurry of Diplomacy in Iran Amid Reports of U....,https://www.nytimes.com/2026/10/26/world/middl...
317,46,2026-10-27-09-21-34 +0000,wsj,Stock Market Today: Tech Stocks Extend Gains A...,https://www.wsj.com/livecoverage/stock-market-...
376,43,2026-10-27-00-45-27 +0000,nyt,How Lula’s Social Media Campaign Helped Him Wi...,https://www.nytimes.com/2026/10/26/world/ameri...
79,42,2026-10-27-20-03-05 +0000,nyt,Justice Dept. Steps Up Moves on Comey and Othe...,https://www.nytimes.com/2026/10/27/us/politics...
56,42,2026-10-27-20-40-01 +0000,nypost,NYC judge rips Alexander brothers as ‘like Dr....,https://nypost.com/2026/10/27/us-news/nyc-judg...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)