## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-07-17-48-00 +0000,wsj,Trump’s Latest Target for a Name Change: New M...,https://www.wsj.com/politics/trumps-latest-tar...
1,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
2,2026-09-07-17-46-25 +0000,bbc,Investigators begin work on why cargo plane ov...,https://www.bbc.co.uk/news/articles/c0e3p1j7n3...
3,2026-09-07-17-37-41 +0000,nypost,Dramatic footage shows moment stunned cops fin...,https://nypost.com/2026/09/07/us-news/moment-c...
4,2026-09-07-17-36-34 +0000,nyt,What to Know About Cargo Plane That Overran It...,https://www.nytimes.com/2026/09/06/us/miami-pl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2569/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
5     new     21
0   trump     21
28  cargo     13
31  miami     13
29  plane     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...,106
95,2026-09-07-13-26-01 +0000,nyt,Trump Posts Map Suggesting New Mexico Be Renam...,https://www.nytimes.com/2026/09/07/us/politics...,82
234,2026-09-06-20-08-57 +0000,nypost,Trump posts map that renames New Mexico ‘New A...,https://nypost.com/2026/09/06/us-news/trump-po...,81
236,2026-09-06-19-46-40 +0000,cbc,At least 5 dead after Amazon cargo plane barre...,https://www.cbc.ca/news/world/amazon-cargo-pla...,73
238,2026-09-06-19-25-00 +0000,wsj,Trump Envoys Visit Ukraine in New Push for Pea...,https://www.wsj.com/world/europe/trump-envoys-...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,106,2026-09-07-17-48-00 +0000,wsj,Trump made a series of social-media posts over...,https://www.wsj.com/politics/trumps-latest-tar...
236,73,2026-09-06-19-46-40 +0000,cbc,At least 5 dead after Amazon cargo plane barre...,https://www.cbc.ca/news/world/amazon-cargo-pla...
59,62,2026-09-07-15-03-22 +0000,chitri,AfD party’s landslide win in eastern Germany t...,https://www.chicagotribune.com/2026/09/07/afd-...
55,62,2026-09-07-15-15-14 +0000,chitri,Fuel prices at record Labor Day high in US tha...,https://www.chicagotribune.com/2026/09/07/fuel...
38,36,2026-09-07-16-16-01 +0000,nypost,Ukraine strikes Russian oil refineries after K...,https://nypost.com/2026/09/07/world-news/ukrai...
177,32,2026-09-07-08-46-42 +0000,nypost,North Korea and Russia open their first road b...,https://nypost.com/2026/09/07/world-news/north...
233,32,2026-09-06-20-35-26 +0000,nypost,‘Vampire’ so feared she was locked in booby-tr...,https://nypost.com/2026/09/06/world-news/vampi...
32,29,2026-09-07-16-27-54 +0000,nypost,OpenAI hires Chuck Schumer’s daughter as Big T...,https://nypost.com/2026/09/07/business/openai-...
3,27,2026-09-07-17-37-41 +0000,nypost,Dramatic footage shows moment stunned cops fin...,https://nypost.com/2026/09/07/us-news/moment-c...
41,25,2026-09-07-16-03-07 +0000,nypost,Chilling video shows crocodile chomp handler’s...,https://nypost.com/2026/09/07/world-news/croco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)