## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-10-20-59-57 +0000,nyt,Iran War Live Updates: Iranian Delegation Arri...,https://www.nytimes.com/live/2026/04/10/world/...
1,2026-04-10-20-58-00 +0000,wsj,President Trump has repeatedly promised his to...,https://www.wsj.com/politics/policy/trump-prom...
2,2026-04-10-20-57-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
3,2026-04-10-20-52-40 +0000,latimes,Spencer Pratt's time in Santa Barbara County l...,https://www.latimes.com/california/story/2026-...
4,2026-04-10-20-51-33 +0000,bbc,Lebanon and Israel officials to meet in US on ...,https://www.bbc.com/news/articles/c93en5q2zl3o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2562/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0     iran     59
13   trump     45
1      war     31
8    talks     18
67  prices     18

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
344,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...,182
180,2026-04-10-13-32-35 +0000,wapo,Trump fumes as Iran retains choke hold on Stra...,https://www.washingtonpost.com/world/2026/04/1...,166
13,2026-04-10-20-35-16 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...,163
24,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...,161
157,2026-04-10-15-28-35 +0000,nypost,Trump tells The Post he’s preparing military i...,https://nypost.com/2026/04/10/us-news/trump-te...,159

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
344,182,2026-04-09-21-54-00 +0000,wsj,Just hours after President Trump announced a s...,https://www.wsj.com/politics/policy/white-hous...
13,104,2026-04-10-20-35-16 +0000,nyt,Israel and Lebanon Plan Talks in D.C. as War T...,https://www.nytimes.com/2026/04/10/world/middl...
24,68,2026-04-10-20-23-00 +0000,wsj,Consumer prices in March rose at their fastest...,https://www.wsj.com/economy/consumers/how-the-...
159,48,2026-04-10-15-12-57 +0000,bbc,EU airline industry warns of fuel shortages if...,https://www.bbc.com/news/articles/c3w37ggp011o...
320,45,2026-04-09-23-01-47 +0000,bbc,"Ceasefire or no ceasefire, the Middle East's r...",https://www.bbc.com/news/articles/cp3l4yk5rlgo...
289,42,2026-04-10-00-49-00 +0000,wsj,The Defense Department violated a court order ...,https://www.wsj.com/politics/national-security...
338,41,2026-04-09-22-16-15 +0000,latimes,Man was shot at by ICE agents in Northern Cali...,https://www.latimes.com/california/story/2026-...
295,39,2026-04-10-00-23-18 +0000,bbc,India proposes new rules to regulate news and ...,https://www.bbc.com/news/articles/ce9mx2j3xlxo...
189,37,2026-04-10-13-00-00 +0000,nypost,Far-left plot to seize control of the LAPD — a...,https://nypost.com/2026/04/10/us-news/far-left...
139,34,2026-04-10-16-10-45 +0000,nypost,CNN succession drama as CEO Mark Thompson taps...,https://nypost.com/2026/04/10/media/cnn-succes...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)