## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-27-14-45-50 +0000,nyt,Wildfires Live Updates: Spain and France Fight...,https://www.nytimes.com/live/2026/07/27/world/...
1,2026-07-27-14-42-40 +0000,nyt,Congress Budgeted Billions for Big Transit Pro...,https://www.nytimes.com/2026/07/27/upshot/tran...
2,2026-07-27-14-37-48 +0000,nypost,3 tourists kicked out of Bali for breaching vi...,https://nypost.com/2026/07/27/world-news/3-tou...
3,2026-07-27-14-37-35 +0000,nyt,How the Iran-Backed Houthis Cornered Saudi Ara...,https://www.nytimes.com/2026/07/27/world/middl...
4,2026-07-27-14-36-14 +0000,nypost,Moment teen illegally jumps off Sunset Cliffs ...,https://nypost.com/2026/07/27/us-news/teen-ill...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
28     iran     23
18    trump     21
216   pride     12
307  berlin     12
308  attack     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
257,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...,77
200,2026-07-26-22-25-29 +0000,nypost,"Trump likes daily strikes on Iran, Sen. Kenned...",https://nypost.com/2026/07/26/world-news/trump...,67
228,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...,66
153,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Oil Tumbles, Dow Gains Aft...",https://www.wsj.com/livecoverage/stock-market-...,66
263,2026-07-26-15-17-33 +0000,chitri,Suspect in deadly Berlin Pride attack is kille...,https://www.chicagotribune.com/2026/07/26/berl...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
257,77,2026-07-26-16-11-05 +0000,nyt,"Trump Seems Trapped by Iran War, Even as He Wi...",https://www.nytimes.com/2026/07/26/us/politics...
228,66,2026-07-26-19-21-26 +0000,bbc,Berlin Pride attack suspect shot and killed du...,https://www.bbc.co.uk/news/articles/c62eg899l9...
133,56,2026-07-27-09-20-57 +0000,nypost,TikTokker voiced concerns about Seattle Center...,https://nypost.com/2026/07/27/us-news/tiktokke...
0,53,2026-07-27-14-45-50 +0000,nyt,Wildfires Live Updates: Spain and France Fight...,https://www.nytimes.com/live/2026/07/27/world/...
153,45,2026-07-27-08-06-20 +0000,wsj,"Stock Market Today: Oil Tumbles, Dow Gains Aft...",https://www.wsj.com/livecoverage/stock-market-...
143,40,2026-07-27-09-00-00 +0000,wsj,Sen. Darline Graham is getting a crash course ...,https://www.wsj.com/politics/elections/darline...
237,34,2026-07-26-18-22-19 +0000,nypost,Jeffries won’t rule out vote to abolish ICE if...,https://nypost.com/2026/07/26/us-news/jeffries...
229,30,2026-07-26-19-07-31 +0000,nypost,Raging DNC boss Ken Martin threw phone at aide...,https://nypost.com/2026/07/26/us-news/raging-d...
262,30,2026-07-26-15-22-54 +0000,chitri,Hurricane Genevieve moves through the Pacific ...,https://www.chicagotribune.com/2026/07/26/hurr...
84,28,2026-07-27-11-30-00 +0000,nypost,NYC stores illegally selling THC drinks as off...,https://nypost.com/2026/07/27/us-news/nyc-stor...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)