## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-22-02-35-00 +0000,wsj,China Slaps Restrictions on Dozens of U.S. Com...,https://www.wsj.com/world/china/china-slaps-re...
1,2026-06-22-02-34-01 +0000,bbc,First round of US-Iran talks end with 'encoura...,https://www.bbc.com/news/articles/cwy0q41v1lzo...
2,2026-06-22-02-30-56 +0000,nyt,Mideast Live Updates: First Round of U.S.-Iran...,https://www.nytimes.com/live/2026/06/21/world/...
3,2026-06-22-02-29-16 +0000,nypost,Chef who fled communist country opens world’s ...,https://nypost.com/2026/06/21/lifestyle/chef-w...
4,2026-06-22-02-17-44 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/21/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
7     iran     28
177  trump     19
8    talks     14
22   world     13
195    new      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
88,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...,96
137,2026-06-21-14-36-29 +0000,nypost,Fed-up Trump threatens to ‘blow the s–t’ out o...,https://nypost.com/2026/06/21/world-news/trump...,95
51,2026-06-21-22-36-02 +0000,wapo,JD Vance holds peace talks with Iran as Trump ...,https://www.washingtonpost.com/world/2026/06/2...,89
175,2026-06-21-09-13-54 +0000,cbc,Trump threats shake up U.S.-Iran talks in Swit...,https://www.cbc.ca/news/world/jd-vance-switzer...,83
114,2026-06-21-17-04-26 +0000,nyt,As Vance Offers Iran ‘Outstretched Hand’ in Ta...,https://www.nytimes.com/2026/06/21/world/middl...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
88,96,2026-06-21-19-37-03 +0000,nypost,Sen. Lindsey Graham predicts Iran peace talks ...,https://nypost.com/2026/06/21/us-news/sen-lind...
57,39,2026-06-21-22-12-01 +0000,nypost,Mamdani and his alleged ‘Hamas slate’ of local...,https://nypost.com/2026/06/21/us-news/mamdani-...
9,32,2026-06-22-01-57-34 +0000,nypost,LA suffocates under ‘toxic’ smoke as massive w...,https://nypost.com/2026/06/21/us-news/los-ange...
53,26,2026-06-21-22-28-19 +0000,nypost,Gavin Newsom warned of mass exodus from Califo...,https://nypost.com/2026/06/21/us-news/gavin-ne...
141,24,2026-06-21-13-41-12 +0000,nypost,Vance says US willing to ‘fundamentally transf...,https://nypost.com/2026/06/21/us-news/vance-sa...
50,23,2026-06-21-22-43-07 +0000,nypost,Los Angeles’ Sunset Strip is now on struggle s...,https://nypost.com/2026/06/21/us-news/los-ange...
58,22,2026-06-21-22-09-15 +0000,nypost,Nashville becomes another pro-business hub poi...,https://nypost.com/2026/06/21/us-news/nashvill...
17,22,2026-06-22-01-37-00 +0000,wsj,Colombia Elects Hardline Populist Who Vows War...,https://www.wsj.com/world/americas/colombia-el...
128,22,2026-06-21-15-46-09 +0000,nypost,Sore loser Texas Rep. Jasmine Crockett says sh...,https://nypost.com/2026/06/21/us-news/jasmine-...
103,22,2026-06-21-17-59-08 +0000,nypost,Christian cop suspended for asking questions a...,https://nypost.com/2026/06/21/world-news/chris...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)