## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-14-21-01-58 +0000,nypost,Bone-chilling video captures rare hammerhead s...,https://nypost.com/2026/08/14/us-news/hammerhe...
1,2026-08-14-21-00-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/business/energy-utilities-...
2,2026-08-14-20-59-22 +0000,nyt,Trump Dismisses Reports About Dire Conditions ...,https://www.nytimes.com/2026/08/14/us/politics...
3,2026-08-14-20-59-00 +0000,wsj,What to Know About Luigi Mangione’s Double Jeo...,https://www.wsj.com/us-news/law/what-to-know-a...
4,2026-08-14-20-58-52 +0000,nypost,Warren Buffett’s Berkshire Hathaway boosts sta...,https://nypost.com/2026/08/14/business/warren-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2429/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
15      trump     39
106       new     18
174     court     16
543  election     13
24   mangione     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
305,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...,121
92,2026-08-14-17-50-46 +0000,chitri,President Donald Trump asks Supreme Court to l...,https://www.chicagotribune.com/2026/08/14/whit...,111
90,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...,96
44,2026-08-14-19-45-00 +0000,wsj,Trump downplays concerns about conditions on t...,https://www.wsj.com/politics/national-security...,94
105,2026-08-14-17-11-23 +0000,nyt,Trump Administration Asks Supreme Court to Gre...,https://www.nytimes.com/2026/08/14/us/politics...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
305,121,2026-08-14-00-00-00 +0000,wsj,Karoline Leavitt was President Trump’s willing...,https://www.wsj.com/politics/policy/karoline-l...
58,75,2026-08-14-19-09-01 +0000,nypost,Read Luigi Mangione’s full speech to the court...,https://nypost.com/2026/08/14/us-news/read-lui...
247,72,2026-08-14-09-41-00 +0000,wsj,A new report led by White House trade adviser ...,https://www.wsj.com/economy/trade/white-house-...
90,57,2026-08-14-17-52-07 +0000,nypost,Trump shrugs off concerns about conditions on ...,https://nypost.com/2026/08/14/us-news/trump-sh...
262,48,2026-08-14-08-51-39 +0000,cbc,Reform UK leader Nigel Farage beats Count Binf...,https://www.cbc.ca/news/world/uk-clacton-byele...
80,44,2026-08-14-18-14-02 +0000,wapo,"Retail sales tumble in July, their biggest dro...",https://www.washingtonpost.com/business/2026/0...
62,38,2026-08-14-19-04-23 +0000,nyt,DOJ Charges Kentucky Woman in World War II Mem...,https://www.nytimes.com/2026/08/14/us/politics...
299,37,2026-08-14-00-50-00 +0000,wsj,President Trump has directed the Navy to tear ...,https://www.wsj.com/us-news/trump-orders-navy-...
184,35,2026-08-14-13-00-00 +0000,wapo,American missionary kidnapped in Niger release...,https://www.washingtonpost.com/world/2026/08/1...
91,34,2026-08-14-17-51-28 +0000,latimes,An oil company wants to restart fracking off t...,https://www.latimes.com/environment/story/2026...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)