## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-29-05-18-35 +0000,nyt,No Kings Protests Held Across the U.S.: Photos...,https://www.nytimes.com/2026/03/28/us/no-kings...
1,2026-03-29-04-48-18 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/29/world/...
2,2026-03-29-04-28-13 +0000,nyt,"U.S. Marines Arrive in Middle East, as Houthis...",https://www.nytimes.com/live/2026/03/28/world/...
3,2026-03-29-04-28-07 +0000,nyt,Airstrikes batter a university and residential...,https://www.nytimes.com/live/2026/03/29/world/...
4,2026-03-29-04-11-27 +0000,bbc,No Kings protests across the US rally against ...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
25  trump     19
15    war     19
27   iran     17
0      no     14
1   kings     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
92,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...,103
91,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...,80
32,2026-03-29-00-15-00 +0000,wsj,Hundreds of thousands of demonstrators are tak...,https://www.wsj.com/us-news/crowds-gather-acro...,75
4,2026-03-29-04-11-27 +0000,bbc,No Kings protests across the US rally against ...,https://www.bbc.com/news/articles/cq8wy7g1gd1o...,73
72,2026-03-28-20-02-09 +0000,wapo,Iran-backed Houthis in Yemen launch attack on ...,https://www.washingtonpost.com/world/2026/03/2...,67

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
92,103,2026-03-28-18-34-16 +0000,cbc,Anger over Iran war adds fuel to anti-Trump 'N...,https://www.cbc.ca/news/world/no-kings-protest...
121,33,2026-03-28-14-53-53 +0000,nypost,NYC Mayor Zohran Mamdani’s new deputy for comm...,https://nypost.com/2026/03/28/us-news/mamdanis...
54,28,2026-03-28-23-00-00 +0000,wsj,President Trump’s tax cuts are delivering bigg...,https://www.wsj.com/politics/policy/trump-salt...
91,27,2026-03-28-18-49-00 +0000,latimes,'No Kings' protesters pack city streets across...,https://www.latimes.com/california/story/2026-...
131,27,2026-03-28-13-06-30 +0000,nypost,Noa Argamani and Avinatan Or –the Israeli coup...,https://nypost.com/2026/03/28/world-news/israe...
8,26,2026-03-29-03-47-09 +0000,nypost,"‘No Kings’ protests turn violent in Portland, ...",https://nypost.com/2026/03/28/us-news/no-kings...
33,26,2026-03-29-00-12-32 +0000,nypost,Tiger Woods’ girlfriend Vanessa Trump shares f...,https://nypost.com/2026/03/28/us-news/tiger-wo...
20,24,2026-03-29-01-40-32 +0000,nypost,Wild San Francisco street fight shows young pu...,https://nypost.com/2026/03/28/us-news/wild-san...
41,24,2026-03-29-00-00-00 +0000,wsj,Investigators searched the office of a FEMA co...,https://www.wsj.com/politics/national-security...
46,23,2026-03-28-23-37-16 +0000,nypost,JD Vance wins 2028 CPAC GOP presidential straw...,https://nypost.com/2026/03/28/us-news/rubio-cu...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)