## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-17-04-00-54 +0000,nyt,"Cassidy Loses Senate Primary in Louisiana, as ...",https://www.nytimes.com/2026/05/16/us/politics...
1,2026-05-17-03-55-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
2,2026-05-17-03-39-34 +0000,latimes,L.A. County health officials confirm fifth mea...,https://www.latimes.com/california/story/2026-...
3,2026-05-17-03-39-14 +0000,nyt,7 Republicans Voted to Convict Trump. Most Are...,https://www.nytimes.com/2026/05/16/us/politics...
4,2026-05-17-03-23-08 +0000,bbc,Trump-backed challenger defeats Republican sen...,https://www.bbc.com/news/articles/cx21d4pxq23o...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2561/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
5         trump     27
127      killed      9
224  california      8
421      strike      7
391       china      7

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-05-17-03-55-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...,79
5,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...,63
118,2026-05-16-15-59-19 +0000,wapo,Trump says top Islamic State leader was killed...,https://www.washingtonpost.com/world/2026/05/1...,62
13,2026-05-17-02-56-27 +0000,nypost,La. Republican Sen. Bill Cassidy fails to make...,https://nypost.com/2026/05/16/us-news/la-repub...,59
77,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...,58

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,79,2026-05-17-03-55-00 +0000,wsj,Sen. Bill Cassidy’s run for re-election was cu...,https://www.wsj.com/politics/elections/trump-n...
5,36,2026-05-17-03-23-00 +0000,wsj,The Senate parliamentarian has found that $1 b...,https://www.wsj.com/politics/policy/funding-ti...
91,35,2026-05-16-19-52-53 +0000,nypost,Recovery operation for Italian divers killed i...,https://nypost.com/2026/05/16/world-news/recov...
57,33,2026-05-16-23-10-22 +0000,nypost,Hochul pushed LIRR strike to pick up votes on ...,https://nypost.com/2026/05/16/us-news/hochul-p...
77,31,2026-05-16-21-25-16 +0000,nypost,Terror ‘commander’ worked through new Iran-bac...,https://nypost.com/2026/05/16/world-news/terro...
112,26,2026-05-16-16-42-27 +0000,nypost,Terror not ruled out as 8 injured after suspec...,https://nypost.com/2026/05/16/world-news/many-...
38,25,2026-05-17-00-40-23 +0000,latimes,The world's largest wildlife crossing and five...,https://www.latimes.com/california/story/2026-...
175,24,2026-05-16-05-53-41 +0000,bbc,Trump warns Taiwan against declaring independe...,https://www.bbc.com/news/articles/ce8p61v7l68o...
131,21,2026-05-16-15-00-00 +0000,wsj,Jim Clyburn’s seat is under threat as Republic...,https://www.wsj.com/politics/policy/redistrict...
66,21,2026-05-16-22-25-58 +0000,nypost,Veteran Maldivian diver alleges Italian scuba ...,https://nypost.com/2026/05/16/world-news/veter...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)