## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-03-16-19-30 +0000,nypost,Woman loses savings to AI-powered romance scam...,https://nypost.com/2026/07/03/business/woman-l...
1,2026-07-03-16-16-59 +0000,nypost,Desperate search for mother and daughter who w...,https://nypost.com/2026/07/03/us-news/desperat...
2,2026-07-03-16-16-33 +0000,nyt,Trump Intercedes to Push Robert Smullen Out of...,https://www.nytimes.com/2026/07/03/nyregion/tr...
3,2026-07-03-16-16-06 +0000,nyt,U.S. Officials Believed Israel Was Plotting to...,https://www.nytimes.com/2026/07/02/us/politics...
4,2026-07-03-16-13-14 +0000,bbc,'Start work at 11' - but will other bosses be ...,https://www.bbc.co.uk/news/articles/c8x27k180x...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2539/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
24        trump     32
34          was     12
215         new     11
133        iran     10
255  california     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
180,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...,106
158,2026-07-03-02-51-34 +0000,nypost,Secret Service member was Googling rooftop loc...,https://nypost.com/2026/07/02/us-news/secret-s...,78
155,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...,77
85,2026-07-03-11-55-27 +0000,nypost,What to expect at Trump’s epic 4th of July ‘Sa...,https://nypost.com/2026/07/03/us-news/what-to-...,71
277,2026-07-02-18-34-02 +0000,nypost,"The top 10 most un-American, no-show states at...",https://nypost.com/2026/07/02/us-news/the-top-...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
180,106,2026-07-03-00-00-00 +0000,wsj,Interior Secretary Doug Burgum is point man fo...,https://www.wsj.com/politics/policy/doug-burgu...
80,63,2026-07-03-12-03-21 +0000,nyt,"Iran Prepares to Bury Supreme Leader, Ayatolla...",https://www.nytimes.com/2026/07/02/world/middl...
18,46,2026-07-03-15-20-57 +0000,bbc,Ukrainian suspect hunted by police after Monac...,https://www.bbc.co.uk/news/articles/c4gy603z2q...
155,45,2026-07-03-04-01-00 +0000,wsj,"CQ Brown, the retired general forced out of hi...",https://www.wsj.com/politics/national-security...
17,41,2026-07-03-15-31-54 +0000,nypost,Americans hit the road in record numbers for 4...,https://nypost.com/2026/07/03/business/america...
84,38,2026-07-03-11-57-28 +0000,bbc,All we know about Taylor Swift's rumoured New ...,https://www.bbc.co.uk/news/articles/c70yj1749j...
176,36,2026-07-03-00-05-01 +0000,latimes,"California designates Bruce Lee Day, first suc...",https://www.latimes.com/california/story/2026-...
267,32,2026-07-02-19-17-09 +0000,nypost,Grieving Ukrainian mom crouches over dead son ...,https://nypost.com/2026/07/02/world-news/gut-w...
0,30,2026-07-03-16-19-30 +0000,nypost,Woman loses savings to AI-powered romance scam...,https://nypost.com/2026/07/03/business/woman-l...
273,30,2026-07-02-18-54-00 +0000,nyt,To Reduce Electrical Grid Strain Amid Heat Wav...,https://www.nytimes.com/2026/07/02/business/en...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)