## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-05-10-12-17 +0000,bbc,"UK in most dangerous period I've known, milita...",https://www.bbc.com/news/articles/c1m2mryg0k7o...
1,2026-06-05-10-09-00 +0000,wsj,GOP senators passed a $70 billion immigration-...,https://www.wsj.com/politics/policy/gop-senato...
2,2026-06-05-10-00-00 +0000,latimes,California voters are eager to know who won el...,https://www.latimes.com/california/story/2026-...
3,2026-06-05-10-00-00 +0000,latimes,Polluted rain runoff from big box parking lots...,https://www.latimes.com/environment/story/2026...
4,2026-06-05-10-00-00 +0000,latimes,L.A. city attorney likely to be first incumben...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2621/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
18    trump     34
72      new     17
188      up     14
132  market     13
393      ai     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
277,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...,87
1,2026-06-05-10-09-00 +0000,wsj,GOP senators passed a $70 billion immigration-...,https://www.wsj.com/politics/policy/gop-senato...,78
179,2026-06-04-21-36-37 +0000,latimes,"Chabria: No, Mr. Hilton, our elections are not...",https://www.latimes.com/california/story/2026-...,77
280,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...,77
106,2026-06-05-01-56-20 +0000,nypost,Trump reveals which performers will replace th...,https://nypost.com/2026/06/04/us-news/trump-re...,76

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
277,87,2026-06-04-16-57-00 +0000,wsj,Trump moves to make Todd Blanche attorney gene...,https://www.wsj.com/politics/policy/trump-says...
280,63,2026-06-04-16-38-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
118,61,2026-06-05-00-42-27 +0000,nypost,Graham Platner admits to sexting women ‘soon’ ...,https://nypost.com/2026/06/04/us-news/graham-p...
112,50,2026-06-05-01-00-00 +0000,wsj,California Democrats Gavin Newsom and Kamala H...,https://www.wsj.com/politics/elections/kamala-...
361,45,2026-06-04-10-29-35 +0000,cbc,Hezbollah rejects Lebanon ceasefire brokered b...,https://www.cbc.ca/news/world/israel-lebanon-c...
49,44,2026-06-05-08-27-21 +0000,wsj,Stock Market Today: Stock Futures Dip as Inves...,https://www.wsj.com/livecoverage/may-jobs-repo...
320,44,2026-06-04-14-21-17 +0000,nypost,Missing Mount Everest Sherpa guide found crawl...,https://nypost.com/2026/06/04/world-news/sherp...
20,44,2026-06-05-09-17-00 +0000,wsj,Eurozone Economy Shrank in First Quarter as Ir...,https://www.wsj.com/economy/eurozone-economy-s...
1,44,2026-06-05-10-09-00 +0000,wsj,GOP senators passed a $70 billion immigration-...,https://www.wsj.com/politics/policy/gop-senato...
340,40,2026-06-04-12-34-00 +0000,cbc,No handshake and no photo as Russia's Andreeva...,https://www.cbc.ca/sports/tennis/dabrowski-rou...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)