## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-24-07-05-12 +0000,nypost,NYC kitten rescue defends ‘NO F–KING MAGA’ ado...,https://nypost.com/2026/09/24/us-news/nyc-kitt...
1,2026-09-24-07-03-29 +0000,nypost,"Judge blocks Trump’s White House media ban, or...",https://nypost.com/2026/09/24/us-news/judge-bl...
2,2026-09-24-07-02-45 +0000,bbc,Teenagers to be offered new vocational GCSE su...,https://www.bbc.co.uk/news/articles/c6rerl41ev...
3,2026-09-24-06-54-00 +0000,wsj,Arnault Family Moves to Cement Control of LVMH...,https://www.wsj.com/business/retail/arnault-fa...
4,2026-09-24-06-47-40 +0000,nyt,Families Urge Trump to Press Xi to Free Americ...,https://www.nytimes.com/2026/09/24/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2313/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
14   trump     78
23     new     35
16   house     22
485     ai     21
39      xi     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
10,2026-09-24-06-39-44 +0000,wapo,Judge orders White House to restore access to ...,https://www.washingtonpost.com/business/2026/0...,172
12,2026-09-24-06-16-00 +0000,wsj,A federal judge ordered President Trump to res...,https://www.wsj.com/politics/policy/judge-orde...,172
349,2026-09-23-14-58-08 +0000,nyt,"White House Defends Trump’s Ban on CNN, MS NOW...",https://www.nytimes.com/2026/09/23/business/tr...,163
127,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,162
8,2026-09-24-06-45-16 +0000,nyt,"Court Blocks Trump’s White House Ban on CNN, M...",https://www.nytimes.com/2026/09/23/business/me...,162

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
10,172,2026-09-24-06-39-44 +0000,wapo,Judge orders White House to restore access to ...,https://www.washingtonpost.com/business/2026/0...
73,114,2026-09-24-00-43-00 +0000,wsj,The last time Venezuelan leader Delcy Rodrígue...,https://www.wsj.com/world/americas/u-n-visit-s...
305,98,2026-09-23-16-26-40 +0000,bbc,UK to fight Russian disinformation and push ne...,https://www.bbc.co.uk/news/articles/c6rerlq99w...
70,84,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...
286,67,2026-09-23-17-04-19 +0000,nypost,Trump’s Board of Peace announces $2.45B first-...,https://nypost.com/2026/09/23/us-news/trumps-b...
181,53,2026-09-23-20-45-00 +0000,wsj,Canada’s Carney Open to U.S. Trade Deal but Wo...,https://www.wsj.com/world/europe/canadas-carne...
413,52,2026-09-23-10-56-00 +0000,wsj,Kamala Harris was campaigning alongside Abdul ...,https://www.wsj.com/politics/policy/kamala-har...
354,51,2026-09-23-14-44-03 +0000,wapo,Another U.S. service member dies amid Iran war...,https://www.washingtonpost.com/politics/2026/0...
449,50,2026-09-23-08-54-54 +0000,wsj,"Stock Market News, Sept. 23, 2026: Treasury Se...",https://www.wsj.com/livecoverage/stock-market-...
64,50,2026-09-24-01-00-00 +0000,wsj,"The AI build-out is making history, dwarfing t...",https://www.wsj.com/economy/the-ai-build-out-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)