## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-25-14-21-14 +0000,nyt,Live Updates: Hundreds of Thousands Flee as Fi...,https://www.nytimes.com/live/2026/07/25/world/...
1,2026-07-25-14-21-01 +0000,nypost,Top 10 worst states for battling mosquitoes th...,https://nypost.com/2026/07/25/us-news/top-10-w...
2,2026-07-25-14-20-58 +0000,nyt,"Iran War Live Updates: U.S. Strikes Abate, Eve...",https://www.nytimes.com/live/2026/07/25/world/...
3,2026-07-25-14-20-57 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/07/25/world/...
4,2026-07-25-14-18-00 +0000,wsj,India’s Gen Z Protesters Wrest a Victory From ...,https://www.wsj.com/world/india/indias-gen-z-p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2978/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
22    trump     38
17     iran     24
164     new     24
18      war     12
825  market      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
178,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...,102
285,2026-07-24-15-39-28 +0000,chitri,President Trump addresses journalists at resch...,https://www.chicagotribune.com/2026/07/24/whit...,94
2,2026-07-25-14-20-58 +0000,nyt,"Iran War Live Updates: U.S. Strikes Abate, Eve...",https://www.nytimes.com/live/2026/07/25/world/...,91
77,2026-07-25-09-01-58 +0000,nyt,President Trump’s New Air Force One Poses Pote...,https://www.nytimes.com/video/us/1000000110477...,90
172,2026-07-24-21-41-12 +0000,nyt,Trump Meets With Top Advisers as He Weighs a M...,https://www.nytimes.com/2026/07/24/us/politics...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
178,102,2026-07-24-21-26-23 +0000,nyt,Trump’s Threatened New Front in Iran War Could...,https://www.nytimes.com/2026/07/24/us/politics...
170,56,2026-07-24-21-47-00 +0000,wsj,"Paramount pauses its Warner Bros. deal, warpla...",https://www.wsj.com/politics/policy/paramount-...
285,56,2026-07-24-15-39-28 +0000,chitri,President Trump addresses journalists at resch...,https://www.chicagotribune.com/2026/07/24/whit...
108,44,2026-07-25-02-00-00 +0000,wsj,Troy Jackson is poised to take Graham Platner’...,https://www.wsj.com/politics/elections/maine-s...
257,39,2026-07-24-17-30-54 +0000,nypost,"Miami dethrones NYC, Bay Area as America’s hot...",https://nypost.com/2026/07/24/business/miami-d...
268,38,2026-07-24-16-45-34 +0000,cbc,Deadly clash near West Bank village kills 4 Pa...,https://www.cbc.ca/news/world/israel-west-bank...
192,36,2026-07-24-20-49-00 +0000,wsj,The U.S. will consider applying additional tar...,https://www.wsj.com/economy/trade/trump-threat...
117,34,2026-07-25-00-59-00 +0000,wsj,A Democratic Party panel selected South Caroli...,https://www.wsj.com/politics/elections/democra...
62,33,2026-07-25-11-00-00 +0000,latimes,"Man who caused Park fire, one of the largest i...",https://www.latimes.com/california/story/2026-...
233,32,2026-07-24-18-28-27 +0000,nyt,Wildfires in France and Spain Drive Tens of Th...,https://www.nytimes.com/2026/07/24/world/europ...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)