## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-11-23-00-00 +0000,wsj,"Aspiring to Regional Domination, Iran Is Ready...",https://www.wsj.com/world/middle-east/https-ww...
1,2026-07-11-22-57-29 +0000,nypost,Iran’s IRGC navy says Strait of Hormuz is clos...,https://nypost.com/2026/07/11/world-news/iran-...
2,2026-07-11-22-38-23 +0000,nypost,Ohio to award $1M to assist 16 ‘almost feral’ ...,https://nypost.com/2026/07/11/us-news/ohio-to-...
3,2026-07-11-22-31-39 +0000,nypost,Ex-NJ GOP aide accused of staging slashing att...,https://nypost.com/2026/07/11/us-news/ex-nj-go...
4,2026-07-11-22-30-34 +0000,startribune,The latest: Twins take Georgia Tech catcher Va...,https://www.startribune.com/minnesota-twins-ml...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2641/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
124  trump     27
42     new     21
57   world     14
297    cup     12
134  times     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
54,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...,106
161,2026-07-11-04-00-00 +0000,wsj,A lack of defensive capabilities aboard Presid...,https://www.wsj.com/politics/national-security...,102
66,2026-07-11-16-39-40 +0000,cbc,Trump administration subpoenas New York Times ...,https://www.cbc.ca/news/world/trump-new-york-t...,99
68,2026-07-11-16-11-33 +0000,bbc,Trump administration subpoenas New York Times ...,https://www.bbc.co.uk/news/articles/cpd3g8q51g...,99
84,2026-07-11-13-52-54 +0000,nypost,Trump admin subpoenas NY Times reporters after...,https://nypost.com/2026/07/11/us-news/times-re...,91

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
54,106,2026-07-11-17-58-00 +0000,wsj,The Trump administration subpoenaed four New Y...,https://www.wsj.com/politics/policy/trump-admi...
81,48,2026-07-11-14-28-53 +0000,nyt,"Kansas City, the Smallest World Cup Host, Has ...",https://www.nytimes.com/2026/07/11/business/ka...
131,42,2026-07-11-09-30-00 +0000,wsj,Around 40% of voters in the 2024 election said...,https://www.wsj.com/economy/trump-voters-econo...
16,36,2026-07-11-21-23-38 +0000,nypost,Ro Khanna blew off offer to meet former Israel...,https://nypost.com/2026/07/11/world-news/ro-kh...
117,36,2026-07-11-10-56-43 +0000,nypost,Iran’s Supreme Leader Mojtaba Khamenei vows re...,https://nypost.com/2026/07/11/world-news/irans...
157,32,2026-07-11-04-37-00 +0000,wsj,A landmark housing bill designed to address vo...,https://www.wsj.com/politics/policy/trump-says...
58,31,2026-07-11-17-34-03 +0000,nypost,Lefty California Dem drops veiled threat to ID...,https://nypost.com/2026/07/11/us-news/californ...
59,31,2026-07-11-17-23-04 +0000,bbc,Ann Widdecombe attacked nearly 24 hours before...,https://www.bbc.co.uk/news/articles/cgjx912wxw...
136,29,2026-07-11-09-15-33 +0000,nypost,Mamdani says it’s time to ‘bring this chapter ...,https://nypost.com/2026/07/11/us-news/mamdani-...
187,28,2026-07-11-00-23-01 +0000,nypost,10 killed in Bahamas plane crash as frightenin...,https://nypost.com/2026/07/10/world-news/10-ki...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)