## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-10-09-05-05 +0000,bbc,Oil prices fall and stocks rise after Trump sa...,https://www.bbc.com/news/articles/cx2jxe382pwo...
1,2026-03-10-09-03-13 +0000,nyt,"As Iran War Spikes Gas Prices, Americans Strug...",https://www.nytimes.com/2026/03/10/us/gas-pric...
2,2026-03-10-09-03-00 +0000,wsj,Persimmon Leads FTSE 100 Gainers on Higher Rev...,https://www.wsj.com/business/earnings/persimmo...
3,2026-03-10-09-02-21 +0000,nyt,"After Global Economy Shudders, Trump Zigzags o...",https://www.nytimes.com/live/2026/03/09/world/...
4,2026-03-10-09-02-19 +0000,nyt,U.S. Tomahawk Hit Naval Base Beside Iranian Sc...,https://www.nytimes.com/2026/03/08/world/middl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2483/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
6    iran     69
7     war     49
5   trump     46
0     oil     32
94    new     27

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
0,2026-03-10-09-05-05 +0000,bbc,Oil prices fall and stocks rise after Trump sa...,https://www.bbc.com/news/articles/cx2jxe382pwo...,236
299,2026-03-09-15-50-17 +0000,nypost,Trump tells The Post there’s no reason to pani...,https://nypost.com/2026/03/09/us-news/trump-te...,222
311,2026-03-09-14-48-23 +0000,wapo,Iran rallies around new leader after 10 days o...,https://www.washingtonpost.com/world/2026/03/0...,217
75,2026-03-10-03-15-14 +0000,nyt,Trump Seeks to Calm Oil and Gas Markets but Sa...,https://www.nytimes.com/2026/03/09/us/politics...,217
88,2026-03-10-02-06-03 +0000,startribune,"Trump says Iran war could be over soon, but oi...",https://www.startribune.com/iran-names-former-...,214

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
0,236,2026-03-10-09-05-05 +0000,bbc,Oil prices fall and stocks rise after Trump sa...,https://www.bbc.com/news/articles/cx2jxe382pwo...
340,76,2026-03-09-12-21-00 +0000,wsj,Eric Trump and Donald Trump Jr. are backing Po...,https://www.wsj.com/politics/national-security...
268,48,2026-03-09-17-20-45 +0000,nypost,Trump urges Australia to grant asylum to Irani...,https://nypost.com/2026/03/09/world-news/trump...
237,48,2026-03-09-19-31-04 +0000,nypost,Trump will back taking out Khamenei’s impotent...,https://nypost.com/2026/03/09/world-news/trump...
304,42,2026-03-09-15-09-05 +0000,bbc,"US missile hit military base near Iran school,...",https://www.bbc.com/news/articles/cvg548lyjnyo...
279,42,2026-03-09-16-33-34 +0000,nypost,Ticketmaster parent Live Nation strikes deal w...,https://nypost.com/2026/03/09/business/ticketm...
347,42,2026-03-09-11-30-53 +0000,nypost,AI startup’s CEO threatened to call ex-NYC May...,https://nypost.com/2026/03/09/business/ai-star...
181,38,2026-03-09-21-52-00 +0000,wsj,Lawrence Summers has lost his affiliation with...,https://www.wsj.com/us-news/education/national...
271,37,2026-03-09-17-06-30 +0000,nyt,"Bernard Lafayette Jr., 85, Dies; Civil Rights ...",https://www.nytimes.com/2026/03/09/us/bernard-...
191,34,2026-03-09-21-37-51 +0000,cbc,What do you get when you win the U.K. Wife Car...,https://www.cbc.ca/radio/asithappens/uk-wife-c...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)