## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-09-02-42-00 +0000,wsj,Singapore Dollar Edges Higher Amid Mild Risk-O...,https://www.wsj.com/finance/currencies/buy-on-...
1,2026-06-09-02-25-13 +0000,latimes,"O.C. man downs 2 quarts of Jack Daniel's, shoo...",https://www.latimes.com/california/story/2026-...
2,2026-06-09-02-18-47 +0000,bbc,US adds BYD to list of firms with alleged Chin...,https://www.bbc.com/news/articles/c75y6e5p9reo...
3,2026-06-09-02-12-42 +0000,nyt,"As Screwworm Cases Mount, U.S. Officials Ramp ...",https://www.nytimes.com/2026/06/08/science/cat...
4,2026-06-09-02-10-03 +0000,startribune,Donald Trump booed by the crowd during the ant...,https://www.startribune.com/nyc-imposes-string...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_3218/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
33   trump     34
87    iran     27
85  israel     20
30      up     14
74     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
9,2026-06-09-01-59-15 +0000,nyt,Live Updates: Israel Halts Iran Strikes After ...,https://www.nytimes.com/live/2026/06/08/world/...,108
39,2026-06-08-23-50-59 +0000,bbc,Israel and Iran flare-up tests Trump's grip an...,https://www.bbc.com/news/articles/cp8lm75186lo...,103
197,2026-06-08-16-39-22 +0000,nypost,Netanyahu says Israel will ‘hold fire’ on Iran...,https://nypost.com/2026/06/08/us-news/netanyah...,99
257,2026-06-08-11-42-45 +0000,latimes,Trump tells Iran and Israel to stop 'shooting'...,https://www.latimes.com/world-nation/story/202...,92
124,2026-06-08-20-28-25 +0000,nyt,Netanyahu Called Off Iran Strikes After Trump ...,https://www.nytimes.com/2026/06/08/us/politics...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
9,108,2026-06-09-01-59-15 +0000,nyt,Live Updates: Israel Halts Iran Strikes After ...,https://www.nytimes.com/live/2026/06/08/world/...
145,85,2026-06-08-19-11-20 +0000,nypost,Spencer Pratt issues bold rallying cry after N...,https://nypost.com/2026/06/08/us-news/spencer-...
299,57,2026-06-08-04-32-00 +0000,wsj,Democratic candidate for U.S. Senate Graham Pl...,https://www.wsj.com/politics/elections/platner...
127,52,2026-06-08-20-16-00 +0000,wsj,A federal judge invalidated the Trump administ...,https://www.wsj.com/politics/policy/judge-stri...
205,48,2026-06-08-16-07-33 +0000,nypost,Xi and Kim express hopes for deeper ties betwe...,https://nypost.com/2026/06/08/world-news/xi-an...
248,47,2026-06-08-12-15-14 +0000,nypost,Two dead as private jet crashes in Dominican R...,https://nypost.com/2026/06/08/world-news/priva...
116,47,2026-06-08-20-54-29 +0000,bbc,Stock market jitters remain amid tech fears an...,https://www.bbc.com/news/articles/c78yd5g9qx0o...
7,47,2026-06-09-02-00-00 +0000,wsj,Trump and his allies are escalating allegation...,https://www.wsj.com/politics/elections/trump-f...
117,41,2026-06-08-20-50-00 +0000,wsj,Many primary races around the U.S. have turned...,https://www.wsj.com/politics/elections/midterm...
238,36,2026-06-08-13-47-47 +0000,nyt,Mexico City’s Airport Got a $500 Million Renov...,https://www.nytimes.com/2026/06/07/world/ameri...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)