## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-14-20-53-24 +0000,nyt,Trump Rejects Talk of A.I. Regulation and Call...,https://www.nytimes.com/2026/09/14/us/politics...
1,2026-09-14-20-47-52 +0000,wapo,"In onstage call with Nvidia CEO, Trump deems A...",https://www.washingtonpost.com/politics/2026/0...
2,2026-09-14-20-44-51 +0000,wapo,Rep. Jasmine Crockett honors Chris Brown at co...,https://www.washingtonpost.com/politics/2026/0...
3,2026-09-14-20-44-40 +0000,latimes,EPA scraps power plant emissions limits in swe...,https://www.latimes.com/environment/story/2026...
4,2026-09-14-20-43-41 +0000,nypost,California’s St. Helena claims it’s being ‘poi...,https://nypost.com/2026/09/14/us-news/napa-val...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2315/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
0    trump     42
11      ai     25
132    new     16
293     up     11
71    iran     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
186,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...,127
41,2026-09-14-19-55-02 +0000,startribune,"Trump calls AI risks a 'hoax,' says there is a...",https://www.startribune.com/trump-dismisses-ne...,123
269,2026-09-14-09-00-00 +0000,wapo,He’s called himself ‘Trump before Donald Trump...,https://www.washingtonpost.com/politics/2026/0...,113
329,2026-09-13-22-02-00 +0000,wsj,President Trump defended the administration’s ...,https://www.wsj.com/tech/ai/trump-defends-whit...,104
278,2026-09-14-08-00-00 +0000,cbc,"Amid Trump trade war, Canada's exports to Chin...",https://www.cbc.ca/news/canada/canada-china-tr...,89

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
186,127,2026-09-14-14-18-53 +0000,chitri,"President Trump calls AI risks a ‘hoax,’ says ...",https://www.chicagotribune.com/2026/09/14/dona...
236,65,2026-09-14-11-04-00 +0000,wsj,"The price of gasoline—and, by proxy, the Iran ...",https://www.wsj.com/politics/policy/with-50-da...
16,58,2026-09-14-20-26-22 +0000,nypost,Entry-level tech jobs in NYC plummet by nearly...,https://nypost.com/2026/09/14/us-news/entry-le...
336,56,2026-09-13-21-30-00 +0000,wsj,"The Republican nominee for Wisconsin governor,...",https://www.wsj.com/politics/policy/wisconsin-...
245,53,2026-09-14-10-14-31 +0000,nypost,Russian drone hits train near Ukraine-Poland b...,https://nypost.com/2026/09/14/world-news/russi...
95,51,2026-09-14-17-56-13 +0000,nypost,Macklemore blames Jewish NFL owner Robert Kraf...,https://nypost.com/2026/09/14/us-news/macklemo...
25,51,2026-09-14-20-09-28 +0000,nypost,US 10-year Treasury yield briefly surges past ...,https://nypost.com/2026/09/14/business/us-10-y...
90,38,2026-09-14-18-08-34 +0000,nypost,Tragic NYC duo killed in subway crash ID’d as ...,https://nypost.com/2026/09/14/us-news/tragic-n...
50,37,2026-09-14-19-39-00 +0000,wsj,Oil Prices Rise as Saudi East-West Pipeline At...,https://www.wsj.com/business/energy-oil/oil-pr...
195,35,2026-09-14-13-41-44 +0000,nypost,Ex-CNN anchor Brooke Baldwin reveals dad beat ...,https://nypost.com/2026/09/14/media/ex-cnn-anc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)