## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-03-19-03-01 +0000,nyt,Trump Immigration Sweeps Spawn Underground Saf...,https://www.nytimes.com/2026/03/03/us/trump-im...
1,2026-03-03-19-02-58 +0000,nypost,Thanks for the mammaries: NYC’s last Hooters g...,https://nypost.com/2026/03/03/us-news/nycs-las...
2,2026-03-03-19-02-48 +0000,nyt,Live Updates: Trump Says Strikes Killed Leader...,https://www.nytimes.com/live/2026/03/03/world/...
3,2026-03-03-19-00-19 +0000,nyt,"As Trump Bashes Spain on Military Spending, Ge...",https://www.nytimes.com/2026/03/03/us/politics...
4,2026-03-03-18-58-54 +0000,nyt,U.S. Attacks on Iran Test Fragile Truce With C...,https://www.nytimes.com/2026/03/03/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2639/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
24      iran     94
0      trump     64
84       war     43
19   strikes     26
277      oil     19

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
395,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...,328
290,2026-03-03-01-35-56 +0000,bbc,Melania Trump chairs UN Security Council meeti...,https://www.bbc.com/news/articles/cg5ng0l35q7o...,225
273,2026-03-03-02-36-25 +0000,nyt,Melania Trump Promotes ‘Peace Through Educatio...,https://www.nytimes.com/2026/03/02/us/politics...,216
391,2026-03-02-20-22-44 +0000,nypost,CBS Austin reporter brushes off directive to d...,https://nypost.com/2026/03/02/media/cbs-austin...,215
400,2026-03-02-19-47-40 +0000,nypost,UK Prime Minister Starmer hits back at Trump o...,https://nypost.com/2026/03/02/world-news/uk-pr...,213

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
395,328,2026-03-02-20-10-03 +0000,nyt,Iran’s Top Security Official Calls Trump’s War...,https://www.nytimes.com/2026/03/02/world/middl...
46,110,2026-03-03-18-05-48 +0000,wapo,"Live updates: Amid Iran strikes, three U.S. em...",https://www.washingtonpost.com/world/2026/03/0...
56,84,2026-03-03-17-48-08 +0000,bbc,Gas and oil prices soar and shares tumble on f...,https://www.bbc.com/news/articles/cr5lz0vgy52o...
145,66,2026-03-03-14-00-00 +0000,latimes,Struggling Democrats need to drop out of Calif...,https://www.latimes.com/california/story/2026-...
177,62,2026-03-03-12-02-00 +0000,wsj,The polls in Texas have been all over the map ...,https://www.wsj.com/politics/things-to-watch-f...
397,54,2026-03-02-20-02-51 +0000,nypost,US military blasts Iranian warship in new vide...,https://nypost.com/2026/03/02/world-news/us-mi...
379,45,2026-03-02-21-08-42 +0000,nypost,Epstein deposition videos show Bill Clinton sh...,https://nypost.com/2026/03/02/us-news/bill-and...
79,45,2026-03-03-17-23-35 +0000,nypost,Gym teacher accused of sex assault on student ...,https://nypost.com/2026/03/03/us-news/ris-accu...
314,42,2026-03-03-00-15-58 +0000,nypost,Supreme Court blocks California law that stopp...,https://nypost.com/2026/03/02/us-news/supreme-...
75,42,2026-03-03-17-28-00 +0000,wsj,U.S. Troops Killed in Kuwait Had No Warning of...,https://www.wsj.com/world/middle-east/u-s-troo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)