## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-20-22-40-00 +0000,wsj,ICE Agent Accused of Shooting Man in Texas,https://www.wsj.com/us-news/ice-agent-accused-...
1,2026-09-20-22-38-55 +0000,nypost,Palo Alto mall menace is zapped with Taser bef...,https://nypost.com/2026/09/20/us-news/palo-alt...
2,2026-09-20-22-36-13 +0000,nyt,Republican Who Runs South Dakota Elections Bac...,https://www.nytimes.com/2026/09/20/us/south-da...
3,2026-09-20-22-35-12 +0000,nyt,One Person Shot During Encounter With ICE in A...,https://www.nytimes.com/2026/09/20/us/ice-shoo...
4,2026-09-20-22-34-07 +0000,cbc,"ICE agent shot and wounded man in Austin, Texa...",https://www.cbc.ca/news/world/ice-shooting-aus...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2496/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
37    trump     27
186     new     14
324  drones     11
197      he     10
366    will      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
56,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...,105
116,2026-09-20-14-24-00 +0000,wsj,President Trump said on Sunday that his propos...,https://www.wsj.com/politics/national-security...,89
70,2026-09-20-18-29-32 +0000,chitri,President Donald Trump suggests his arch will ...,https://www.chicagotribune.com/2026/09/20/trum...,80
112,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...,74
123,2026-09-20-13-57-21 +0000,nypost,Trump says his Triumphal Arch in Washington wi...,https://nypost.com/2026/09/20/us-news/trump-sa...,72

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
56,105,2026-09-20-19-40-00 +0000,wsj,President Trump will meet New York City Mayor ...,https://www.wsj.com/politics/policy/trump-to-m...
96,51,2026-09-20-16-09-01 +0000,nypost,GOP’s Bruce Blakeman admits it’s ‘surreal’ his...,https://nypost.com/2026/09/20/us-news/bruce-bl...
112,47,2026-09-20-14-33-56 +0000,cbc,Trump says proposed triumphal arch near White ...,https://www.cbc.ca/news/world/trump-arch-drone...
183,40,2026-09-20-05-01-47 +0000,bbc,Watch: Fans react as Ed Sheeran speaks out ove...,https://www.bbc.co.uk/news/videos/ck980m0pr1e0...
44,37,2026-09-20-20-21-40 +0000,bbc,German Chancellor Merz calls state election a ...,https://www.bbc.co.uk/news/articles/cvwyz29n0n...
99,34,2026-09-20-15-59-00 +0000,wsj,"At the Kansas State Fair’s Senate debate, incu...",https://www.wsj.com/politics/elections/even-in...
177,32,2026-09-20-07-20-44 +0000,nypost,"Ukraine fires over 1,000 drones at Russia in ‘...",https://nypost.com/2026/09/20/world-news/one-o...
147,30,2026-09-20-10-00-00 +0000,wapo,She cheered a teen protest against ICE. Police...,https://www.washingtonpost.com/nation/2026/09/...
113,28,2026-09-20-14-30-07 +0000,nypost,Trump warns he’s close to Iran decision as Mid...,https://nypost.com/2026/09/20/us-news/trump-re...
133,26,2026-09-20-12-00-00 +0000,wsj,Joyce Beatty is the unlikely leader of the opp...,https://www.wsj.com/politics/elections/the-rus...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)