## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-17-04-03-52 +0000,bbc,"Actress Hayden Panettiere dies aged 36, US med...",https://www.bbc.co.uk/news/articles/cq5665zgg1...
1,2026-08-17-04-01-18 +0000,nyt,U.S. and Iran Blow Through Deadline to Agree t...,https://www.nytimes.com/2026/08/17/world/middl...
2,2026-08-17-04-01-15 +0000,nyt,"‘Posh George,’ the Convicted Fraudster in Nige...",https://www.nytimes.com/2026/08/17/world/europ...
3,2026-08-17-04-01-11 +0000,nyt,"As China Hunts for Scientific Talent, the US M...",https://www.nytimes.com/2026/08/17/business/ch...
4,2026-08-17-04-01-06 +0000,nyt,China Wants Its Data to Power the World’s A.I.,https://www.nytimes.com/2026/08/17/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2537/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
52      trump     26
7        iran     13
387       new     11
56   military     11
15        war     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
12,2026-08-17-02-25-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,95
8,2026-08-17-02-51-27 +0000,bbc,Trump says US to scale back South Korea milita...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,88
143,2026-08-16-15-00-00 +0000,wsj,​When President Trump said he was demolishing ...,https://www.wsj.com/politics/policy/trumps-bal...,84
34,2026-08-17-00-20-54 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,71
57,2026-08-16-21-57-01 +0000,nypost,Trump instructs Pentagon to reduce military ex...,https://nypost.com/2026/08/16/world-news/trump...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
12,95,2026-08-17-02-25-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
124,47,2026-08-16-17-11-19 +0000,nypost,Iranians set to face harsh prison sentences fo...,https://nypost.com/2026/08/16/world-news/irani...
31,37,2026-08-17-00-29-27 +0000,chitri,Ukraine launches one of its largest aerial att...,https://www.chicagotribune.com/2026/08/16/ukra...
10,33,2026-08-17-02-43-27 +0000,nyt,Iran Says Qatar Captured Its Pilots Months Ago...,https://www.nytimes.com/2026/08/15/world/middl...
121,32,2026-08-16-17-50-32 +0000,chitri,US envoy Kushner meets Hamas’ leader in push f...,https://www.chicagotribune.com/2026/08/16/kush...
17,28,2026-08-17-02-00-00 +0000,wsj,"With the Iowa State Fair in full swing, Republ...",https://www.wsj.com/politics/elections/rural-e...
113,27,2026-08-16-18-23-50 +0000,nypost,GOP Rep. Mike Lawler eyes nuclear power plant ...,https://nypost.com/2026/08/16/us-news/gop-rep-...
146,26,2026-08-16-14-45-19 +0000,nypost,Ex-Sen. Kyrsten Sinema details repeated sex wi...,https://nypost.com/2026/08/16/us-news/ex-sen-k...
88,26,2026-08-16-19-56-39 +0000,nypost,Gavin Newsom wildfire plan faces revolt over w...,https://nypost.com/2026/08/16/us-news/gavin-ne...
174,26,2026-08-16-10-51-59 +0000,nypost,Four Renaissance paintings of ‘extraordinary v...,https://nypost.com/2026/08/16/world-news/anton...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)