## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-30-20-51-35 +0000,nyt,Deportees Sent to Liberia Recount Harrowing De...,https://www.nytimes.com/2026/08/30/world/afric...
1,2026-08-30-20-39-07 +0000,nypost,Simi Valley residents erupt as rotting Boyle H...,https://nypost.com/2026/08/30/us-news/simi-val...
2,2026-08-30-20-36-43 +0000,nyt,When a Bear Cub Decides Your Boot Is an Appetizer,https://www.nytimes.com/2026/08/30/us/baby-bea...
3,2026-08-30-20-33-47 +0000,chitri,US forces strike Iranian rocket launchers on t...,https://www.chicagotribune.com/2026/08/30/us-s...
4,2026-08-30-20-32-43 +0000,cbc,Iran's Revolutionary Guard vows retaliation af...,https://www.cbc.ca/news/world/iran-larak-islan...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2314/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
69        trump     19
151         new     12
94          oil      9
163       nepal      9
123  california      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
69,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...,58
80,2026-08-30-16-13-37 +0000,nypost,Google swaps Lake Ontario maps to ‘Lake Americ...,https://nypost.com/2026/08/30/us-news/google-m...,56
34,2026-08-30-19-03-44 +0000,nypost,Prosecutor in NY AG Letitia James’ office says...,https://nypost.com/2026/08/30/us-news/prosecut...,53
76,2026-08-30-16-31-00 +0000,wsj,Opinion | Trump’s New Iran Sanctions Put China...,https://www.wsj.com/opinion/trumps-new-iran-sa...,52
91,2026-08-30-15-08-52 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...,48

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
69,58,2026-08-30-16-50-53 +0000,nyt,Google Maps Changes Lake Ontario to Lake Ameri...,https://www.nytimes.com/2026/08/30/world/canad...
126,37,2026-08-30-11-00-00 +0000,startribune,He wants to open their 10-year marriage to new...,https://www.startribune.com/he-wants-to-open-t...
79,37,2026-08-30-16-14-00 +0000,wsj,"James Talarico, the Democratic candidate for S...",https://www.wsj.com/politics/policy/talarico-i...
62,36,2026-08-30-17-11-07 +0000,nypost,El-Sayed finally apologizes for lamenting deat...,https://nypost.com/2026/08/30/us-news/el-sayed...
70,33,2026-08-30-16-48-13 +0000,bbc,Head teacher evacuated 900 children minutes be...,https://www.bbc.co.uk/news/articles/c5ymvdm552...
148,32,2026-08-30-09-30-00 +0000,wsj,Fed Chairman Kevin Warsh put to rest some conc...,https://www.wsj.com/economy/central-banking/wa...
174,31,2026-08-30-06-03-30 +0000,nypost,Switzerland rave shooting leaves 22-year-old w...,https://nypost.com/2026/08/30/world-news/switz...
104,30,2026-08-30-14-16-40 +0000,chitri,"Iran’s leader calls for Muslim unity, NBC crew...",https://www.chicagotribune.com/2026/08/30/nbc-...
91,29,2026-08-30-15-08-52 +0000,nyt,Trump Says U.S. Struck Deal for Control of Mor...,https://www.nytimes.com/2026/08/28/business/tr...
1,27,2026-08-30-20-39-07 +0000,nypost,Simi Valley residents erupt as rotting Boyle H...,https://nypost.com/2026/08/30/us-news/simi-val...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)