## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-19-18-58-19 +0000,chitri,Ford supplier cuts jobs in Michigan as some wo...,https://www.chicagotribune.com/2026/10/19/ford...
1,2026-10-19-18-54-52 +0000,nypost,Horror as California high school football staf...,https://nypost.com/2026/10/19/us-news/californ...
2,2026-10-19-18-54-34 +0000,nyt,"At Victoria’s Secret’s 2026 Fashion Show, an O...",https://www.nytimes.com/2026/10/19/style/victo...
3,2026-10-19-18-53-45 +0000,nypost,Iconic Paris tourist destination shuts visitor...,https://nypost.com/2026/10/19/world-news/iconi...
4,2026-10-19-18-49-17 +0000,nyt,Christiane Amanpour Says She Is Leaving CNN Af...,https://www.nytimes.com/2026/10/19/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2377/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
74    trump     24
148     new     15
548  russia     13
155      up     13
280  french     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
192,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...,98
281,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...,96
103,2026-10-19-15-31-08 +0000,nypost,Donald Trump signs executive order creating NI...,https://nypost.com/2026/10/19/us-news/donald-t...,68
128,2026-10-19-14-21-13 +0000,nyt,Will Trump’s Endorsement of Netanyahu Fire Up ...,https://www.nytimes.com/2026/10/19/world/middl...,66
257,2026-10-19-04-03-00 +0000,wsj,China’s economic growth picked up in the third...,https://www.wsj.com/economy/chinas-economy-exp...,65

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
192,98,2026-10-19-10-59-00 +0000,wsj,With two weeks to go until voters determine co...,https://www.wsj.com/politics/policy/after-a-we...
281,57,2026-10-18-23-19-00 +0000,wsj,President Trump’s surprise diesel deal with Ru...,https://www.wsj.com/politics/policy/trumps-ove...
257,52,2026-10-19-04-03-00 +0000,wsj,China’s economic growth picked up in the third...,https://www.wsj.com/economy/chinas-economy-exp...
71,50,2026-10-19-16-42-59 +0000,nypost,Christiane Amanpour to exit CNN amid staffer c...,https://nypost.com/2026/10/19/media/christiane...
142,49,2026-10-19-13-48-17 +0000,nyt,Carney Says Fire at Canadian Forces Base Wainw...,https://www.nytimes.com/2026/10/18/world/canad...
219,43,2026-10-19-09-30-00 +0000,wsj,America’s home-buying market is a house divide...,https://www.wsj.com/economy/housing/americas-n...
196,43,2026-10-19-10-34-18 +0000,bbc,Israeli police arrest 10 over settler attacks ...,https://www.bbc.co.uk/news/articles/cqn7323p0d...
125,40,2026-10-19-14-24-00 +0000,nypost,Rubio says Ukraine attacked ships carrying US-...,https://nypost.com/2026/10/19/us-news/rubio-sa...
46,38,2026-10-19-17-34-00 +0000,nypost,Alleged OpenAI spy frequently WhatsApp’ed Saud...,https://nypost.com/2026/10/19/business/alleged...
188,36,2026-10-19-11-00-00 +0000,nypost,Gaza teacher says she was threatened for refus...,https://nypost.com/2026/10/19/world-news/gaza-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)