## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-25-10-00-00 +0000,startribune,Brehm: Minneapolis needs to eliminate addictio...,https://www.startribune.com/brehm-minneapolis-...
1,2026-09-24-22-52-13 +0000,nyt,Mortgage Rates Hit 7% as Iran War Fallout Crus...,https://www.nytimes.com/2026/09/24/business/mo...
2,2026-09-24-22-49-37 +0000,wapo,I watched 24 hours of Trump TV. Buckle up.,https://www.washingtonpost.com/style/2026/09/2...
3,2026-09-24-22-49-31 +0000,wapo,Iran says it has given Trump administration ne...,https://www.washingtonpost.com/world/2026/09/2...
4,2026-09-24-22-49-04 +0000,nypost,LAX’s nightmare ‘people mover’ delayed again t...,https://nypost.com/2026/09/24/us-news/troubled...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2419/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
19  trump     87
25    new     33
47     xi     32
50  house     24
49  white     22

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-09-24-21-03-33 +0000,nypost,Trump charms Xi Jinping during White House sta...,https://nypost.com/2026/09/24/us-news/trump-pu...,218
54,2026-09-24-21-37-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...,217
264,2026-09-24-15-34-51 +0000,chitri,President Trump lays out the pomp for Presiden...,https://www.chicagotribune.com/2026/09/24/dona...,202
337,2026-09-24-10-59-00 +0000,wsj,As President Trump and China’s Xi Jinping prep...,https://www.wsj.com/politics/policy/as-trump-a...,192
297,2026-09-24-13-03-42 +0000,latimes,"CNN, MS NOW and Politico return to White House...",https://www.latimes.com/entertainment-arts/bus...,188

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,218,2026-09-24-21-03-33 +0000,nypost,Trump charms Xi Jinping during White House sta...,https://nypost.com/2026/09/24/us-news/trump-pu...
59,105,2026-09-24-21-30-00 +0000,wsj,The White House is pressing China about suspec...,https://www.wsj.com/politics/elections/trump-a...
250,100,2026-09-24-16-10-06 +0000,nyt,New Hampshire Senate Race: 5 Takeaways From a ...,https://www.nytimes.com/2026/09/24/us/politics...
436,77,2026-09-24-01-00-00 +0000,wsj,"The AI build-out is making history, dwarfing t...",https://www.wsj.com/economy/the-ai-build-out-i...
54,70,2026-09-24-21-37-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...
257,63,2026-09-24-16-00-00 +0000,wsj,Average 30-year mortgage rates hit 7.03% this ...,https://www.wsj.com/economy/housing/mortgage-r...
66,57,2026-09-24-21-21-47 +0000,bbc,Netanyahu defends Israeli military action as d...,https://www.bbc.co.uk/news/articles/c3y0z7kxle...
108,54,2026-09-24-20-25-59 +0000,chitri,Trump administration asks the Supreme Court to...,https://www.chicagotribune.com/2026/09/24/trum...
181,50,2026-09-24-18-31-54 +0000,latimes,California woman missing since 2007 found buri...,https://www.latimes.com/california/story/2026-...
407,50,2026-09-24-06-41-39 +0000,nypost,Abdul El-Sayed won’t say he stands against Ira...,https://nypost.com/2026/09/24/us-news/abdul-el...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)