## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-30-19-12-56 +0000,nypost,Eric Swalwell insists Chinese spy case ‘is clo...,https://nypost.com/2026/03/30/us-news/eric-swa...
1,2026-03-30-19-11-32 +0000,nyt,Celine Dion Announces Comeback Concerts in Paris,https://www.nytimes.com/2026/03/30/arts/music/...
2,2026-03-30-19-10-41 +0000,nypost,Lawmakers chill in casinos and with celebs dur...,https://nypost.com/2026/03/30/us-news/lawmaker...
3,2026-03-30-19-08-23 +0000,nyt,Iran War Live Updates: Trump Renews Threats Ag...,https://www.nytimes.com/live/2026/03/30/world/...
4,2026-03-30-19-07-07 +0000,nyt,Why Is the U.S. Allowing a Russian Oil Tanker ...,https://www.nytimes.com/2026/03/30/world/ameri...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2470/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
36   trump     33
32    iran     29
41     oil     20
33     war     17
314    new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
3,2026-03-30-19-08-23 +0000,nyt,Iran War Live Updates: Trump Renews Threats Ag...,https://www.nytimes.com/live/2026/03/30/world/...,124
133,2026-03-30-14-41-55 +0000,nypost,"Trump puts Iran on notice, reveals to The Post...",https://nypost.com/2026/03/30/us-news/trump-te...,119
215,2026-03-30-08-33-12 +0000,nypost,Trump says he could ‘take the oil in Iran’ as ...,https://nypost.com/2026/03/30/world-news/trump...,107
243,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...,102
174,2026-03-30-11-57-14 +0000,nypost,Trump says deal will ‘probably’ be reached soo...,https://nypost.com/2026/03/30/us-news/trump-sa...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
3,124,2026-03-30-19-08-23 +0000,nyt,Iran War Live Updates: Trump Renews Threats Ag...,https://www.nytimes.com/live/2026/03/30/world/...
69,49,2026-03-30-17-13-22 +0000,nypost,Out-of-control boat kills woman in Miami’s Bis...,https://nypost.com/2026/03/30/us-news/out-of-c...
247,42,2026-03-30-00-22-43 +0000,nyt,Israel’s military posted two images of Ali Cho...,https://www.nytimes.com/live/2026/03/29/world/...
212,39,2026-03-30-08-58-42 +0000,nypost,US allows Russian oil tanker to reach Cuba ami...,https://nypost.com/2026/03/30/world-news/us-al...
222,38,2026-03-30-05-38-26 +0000,bbc,Fuel tax halved and free public transport offe...,https://www.bbc.com/news/articles/c937n0yxggeo...
170,35,2026-03-30-12-30-58 +0000,cbc,Air Canada CEO Michael Rousseau to retire late...,https://www.cbc.ca/news/business/air-canada-ce...
120,34,2026-03-30-15-34-02 +0000,nypost,"Thieves snatch $10M worth of Renoir, Cézanne a...",https://nypost.com/2026/03/30/world-news/thiev...
127,34,2026-03-30-15-15-36 +0000,nyt,Analysis shows where a new U.S. missile hit an...,https://www.nytimes.com/live/2026/world/us-isr...
243,33,2026-03-30-01-09-00 +0000,wsj,President Trump is weighing a military operati...,https://www.wsj.com/politics/national-security...
24,29,2026-03-30-18-30-10 +0000,nypost,Record $1.1B evil oil heir ordered to pay step...,https://nypost.com/2026/03/30/us-news/record-1...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)