## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-08-52-28 +0000,bbc,MoD withheld information about nuclear test ve...,https://www.bbc.co.uk/news/articles/c3d787k9kp...
1,2026-09-03-08-49-00 +0000,wsj,Malaysia Central Bank Holds Rates as Growth St...,https://www.wsj.com/economy/central-banking/ma...
2,2026-09-03-08-45-04 +0000,bbc,Zack Polanski seeks to stand for by-election i...,https://www.bbc.co.uk/news/articles/cge41ee40v...
3,2026-09-03-08-39-00 +0000,wsj,"Bond Selloff Pauses, Stocks Tread Water as Tra...",https://www.wsj.com/finance/stocks/bond-sellof...
4,2026-09-03-08-38-00 +0000,wsj,Swiss Inflation Jumps on Higher Energy Prices,https://www.wsj.com/economy/global/swiss-infla...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2489/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
341  trump     29
168    new     18
147   iran     18
178     up     14
490     ai     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
63,2026-09-03-02-00-00 +0000,wsj,Why Trump’s Venezuela Oil Grab Is No Quick Fix...,https://www.wsj.com/business/energy-oil/why-tr...,76
198,2026-09-02-19-06-29 +0000,nypost,Oil giant Chevron confirms it will expand oper...,https://nypost.com/2026/09/02/business/oil-gia...,75
179,2026-09-02-19-56-53 +0000,nyt,Trump Returns to a Familiar Playbook as the Wa...,https://www.nytimes.com/2026/09/02/us/politics...,75
204,2026-09-02-18-58-00 +0000,wapo,El-Sayed blames Trump for global bond market s...,https://www.washingtonpost.com/politics/2026/0...,72
253,2026-09-02-16-56-01 +0000,nypost,MapQuest surges to No. 1 in App Store after Go...,https://nypost.com/2026/09/02/business/mapques...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
63,76,2026-09-03-02-00-00 +0000,wsj,Why Trump’s Venezuela Oil Grab Is No Quick Fix...,https://www.wsj.com/business/energy-oil/why-tr...
328,62,2026-09-02-12-55-00 +0000,wapo,"Watch Ontario, New York, residents sound off o...",https://www.washingtonpost.com/politics/2026/0...
353,52,2026-09-02-11-13-25 +0000,chitri,Iran fires on its Gulf neighbors after US mili...,https://www.chicagotribune.com/2026/09/02/iran...
5,49,2026-09-03-08-36-03 +0000,nypost,Florida man left with swollen face in mugshot ...,https://nypost.com/2026/09/03/us-news/florida-...
103,46,2026-09-02-23-36-49 +0000,bbc,Uber launches UK's first robotaxis with a driv...,https://www.bbc.co.uk/news/articles/ce9e838jzp...
321,45,2026-09-02-13-20-11 +0000,bbc,Faisal Islam: Why bond market wildfire is keep...,https://www.bbc.co.uk/news/articles/c0rez9zegj...
264,44,2026-09-02-16-22-36 +0000,nypost,Ex-pop star Gary Glitter pleads not guilty to ...,https://nypost.com/2026/09/02/world-news/forme...
73,43,2026-09-03-01-00-00 +0000,wsj,With conservative figures such as Steve Bannon...,https://www.wsj.com/politics/policy/bernie-aoc...
196,42,2026-09-02-19-11-13 +0000,cbc,Deadlocked jury in case of U.S. mother who kil...,https://www.cbc.ca/news/world/lindsay-clancy-j...
290,40,2026-09-02-15-28-53 +0000,nypost,"Teacher, students sue OpenAI over deadly Canad...",https://nypost.com/2026/09/02/business/teacher...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)