## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-06-15-50-30 +0000,nyt,Live Updates: Germany’s Far Right Eyes Breakth...,https://www.nytimes.com/live/2026/09/06/world/...
1,2026-09-06-15-43-44 +0000,chitri,US envoys Witkoff and Kushner hold talks in Uk...,https://www.chicagotribune.com/2026/09/06/witk...
2,2026-09-06-15-40-58 +0000,nypost,Hurricane Marie sparks mass flooding in Seal B...,https://nypost.com/2026/09/06/us-news/hurrican...
3,2026-09-06-15-32-27 +0000,bbc,US envoys hold talks with Zelensky in Kyiv aft...,https://www.bbc.co.uk/news/articles/c6248nvqy8...
4,2026-09-06-15-26-50 +0000,cbc,"Indonesia's Anak Krakatau volcano erupts, canc...",https://www.cbc.ca/news/world/indonesia-volcan...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2546/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
40     trump     20
14   ukraine     12
13     talks     11
233      new     10
9     envoys     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
176,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...,73
146,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...,59
1,2026-09-06-15-43-44 +0000,chitri,US envoys Witkoff and Kushner hold talks in Uk...,https://www.chicagotribune.com/2026/09/06/witk...,58
148,2026-09-05-22-29-37 +0000,wapo,"U.S. envoys meet Putin in Moscow, pressing Rus...",https://www.washingtonpost.com/world/2026/09/0...,58
110,2026-09-06-07-22-19 +0000,nypost,Trump’s MAGA super PAC pours $10M into Ken Pax...,https://nypost.com/2026/09/06/us-news/trumps-s...,57

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
176,73,2026-09-05-17-32-00 +0000,wsj,Putin Meets Trump Envoys as U.S. Pushes to Rev...,https://www.wsj.com/world/russia/putin-to-meet...
146,39,2026-09-05-22-35-00 +0000,wsj,Trump’s super PAC has entered the competitive ...,https://www.wsj.com/politics/elections/trump-a...
133,35,2026-09-06-00-08-44 +0000,nypost,Iran plotting new Oct. 7-style attack against ...,https://nypost.com/2026/09/05/world-news/iran-...
9,33,2026-09-06-15-17-00 +0000,wsj,As President Trump’s approval rating hovers ne...,https://www.wsj.com/business/retail/in-trumps-...
112,29,2026-09-06-06-20-08 +0000,nypost,"Ex-Team USA triathlete, NYC dad drowns while s...",https://nypost.com/2026/09/06/us-news/ex-team-...
137,28,2026-09-05-23-47-38 +0000,nyt,U.S. Strikes Three Iranian ‘Shadow Network’ Oi...,https://www.nytimes.com/2026/09/05/world/middl...
124,25,2026-09-06-02-30-00 +0000,nypost,California’s free ride means illegal migrants ...,https://nypost.com/2026/09/05/us-news/inside-c...
108,24,2026-09-06-07-58-55 +0000,nyt,Elections in Germany Could Produce First Far-R...,https://www.nytimes.com/2026/09/06/world/europ...
4,23,2026-09-06-15-26-50 +0000,cbc,"Indonesia's Anak Krakatau volcano erupts, canc...",https://www.cbc.ca/news/world/indonesia-volcan...
128,23,2026-09-06-01-54-29 +0000,bbc,Watch: Moment 64-year-old Nepali woman is foun...,https://www.bbc.co.uk/news/videos/c4gd24d1d0do...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)