## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-12-20-31-58 +0000,nypost,Massive underground detector aimed at understa...,https://nypost.com/2026/06/12/science/undergro...
1,2026-06-12-20-30-14 +0000,cbc,Ottawa moves to tighten ban on imports made wi...,https://www.cbc.ca/news/politics/forced-labour...
2,2026-06-12-20-29-22 +0000,nyt,"To Defeat Democrats, Texas Governor Embraces t...",https://www.nytimes.com/2026/06/12/us/greg-abb...
3,2026-06-12-20-28-52 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/06/12/busine...
4,2026-06-12-20-26-27 +0000,nypost,California McDonald’s boss breaks silence afte...,https://nypost.com/2026/06/12/us-news/californ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2466/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
87    world     36
65   spacex     33
88      cup     28
157   trump     26
105    iran     20

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
133,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...,139
107,2026-06-12-16-50-26 +0000,nyt,Elon Musk Becomes World’s First Trillionaire a...,https://www.nytimes.com/2026/06/12/technology/...,125
319,2026-06-12-00-49-15 +0000,nyt,Why Mexico’s President Will Not Attend the Wor...,https://www.nytimes.com/2026/06/11/world/ameri...,105
326,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...,104
173,2026-06-12-14-16-19 +0000,nypost,California Democrats slammed for bizarre World...,https://nypost.com/2026/06/12/us-news/californ...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
133,139,2026-06-12-15-55-59 +0000,nypost,Elon Musk becomes world’s first trillionaire a...,https://nypost.com/2026/06/12/business/spacex-...
224,95,2026-06-12-10-52-00 +0000,wsj,President Trump said he would nominate Jay Cla...,https://www.wsj.com/politics/elections/jay-cla...
326,68,2026-06-11-23-49-21 +0000,nypost,Violent protests erupt outside Mexico City sta...,https://nypost.com/2026/06/11/world-news/prote...
12,66,2026-06-12-20-21-05 +0000,nyt,Iran War Live Updates: Cease-Fire Deal Appears...,https://www.nytimes.com/live/2026/06/12/world/...
342,60,2026-06-11-22-59-00 +0000,wsj,"Tulsi Gabbard, the outgoing intelligence chief...",https://www.wsj.com/politics/national-security...
313,59,2026-06-12-01-00-00 +0000,wsj,When Trump meets his counterparts at next week...,https://www.wsj.com/economy/global/the-global-...
33,55,2026-06-12-19-57-16 +0000,bbc,UK vows to phase out Russian diesel and jet fu...,https://www.bbc.com/news/articles/ceqdl8xre7qo...
264,53,2026-06-12-08-16-52 +0000,nypost,White House fires back at Ariana Grande after ...,https://nypost.com/2026/06/12/us-news/white-ho...
161,41,2026-06-12-14-43-36 +0000,nypost,Florida Sen. Rick Scott urges DOJ probe amid C...,https://nypost.com/2026/06/12/us-news/florida-...
136,39,2026-06-12-15-45-28 +0000,cbc,Ex-South Korean president sentenced for sendin...,https://www.cbc.ca/news/world/south-korea-yoon...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)