## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-01-13-12-10 +0000,bbc,"Billions of meals at risk due to Iran war, say...",https://www.bbc.com/news/articles/cpwp50v4ye7o...
1,2026-05-01-13-12-06 +0000,nyt,"War in Iran Is Making the Hajj, the Muslim Pil...",https://www.nytimes.com/2026/05/01/world/asia/...
2,2026-05-01-13-05-00 +0000,wsj,6 of the Best Financial Advisor Companies: Wel...,https://www.wsj.com/buyside/personal-finance/f...
3,2026-05-01-13-05-00 +0000,wsj,Best High-Yield Savings Accounts for May 2026:...,https://www.wsj.com/buyside/personal-finance/b...
4,2026-05-01-13-02-33 +0000,nyt,Fed Officials Cite Inflation Concerns in Defen...,https://www.nytimes.com/2026/05/01/business/ec...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2542/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
637  trump     43
168   race     36
265   your     35
523  guide     33
65     new     32

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
84,2026-05-01-10-00-00 +0000,latimes,Your guide to the California state schools sup...,https://www.latimes.com/california/story/2026-...,181
86,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,177
99,2026-05-01-10-00-00 +0000,latimes,Your guide to the L.A. City Council District 1...,https://www.latimes.com/california/story/2026-...,168
107,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,167
93,2026-05-01-10-00-00 +0000,latimes,Your guide to the California Congressional Dis...,https://www.latimes.com/california/story/2026-...,166

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
84,181,2026-05-01-10-00-00 +0000,latimes,Your guide to the California state schools sup...,https://www.latimes.com/california/story/2026-...
297,145,2026-04-30-21-24-00 +0000,wsj,The House approved a long-delayed measure to f...,https://www.wsj.com/politics/policy/house-vote...
16,124,2026-05-01-12-36-00 +0000,wsj,The Minneapolis Fed president wrote that heigh...,https://www.wsj.com/economy/central-banking/ri...
322,73,2026-04-30-19-56-03 +0000,nyt,Supreme Court Voting Rights Ruling Could Fuel ...,https://www.nytimes.com/2026/04/30/us/politics...
99,64,2026-05-01-10-00-00 +0000,latimes,Your guide to the L.A. City Council District 1...,https://www.latimes.com/california/story/2026-...
191,56,2026-05-01-04-11-53 +0000,bbc,Myanmar ex-leader Aung San Suu Kyi moved to ho...,https://www.bbc.com/news/articles/cz72j8eex4eo...
279,56,2026-04-30-21-49-27 +0000,nypost,Prince Harry’s estrangement from the royal fam...,https://nypost.com/2026/04/30/opinion/prince-h...
215,55,2026-05-01-01-33-00 +0000,wsj,U.S. economic growth picked up in the first qu...,https://www.wsj.com/economy/central-banking/u-...
134,47,2026-05-01-09-32-19 +0000,nypost,"Acupuncturist mom had picture-perfect life, $1...",https://nypost.com/2026/05/01/us-news/acupunct...
235,46,2026-05-01-00-00-00 +0000,wsj,Republican leaders are pushing Southern states...,https://www.wsj.com/politics/policy/republican...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)