## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-25-23-49-35 +0000,nyt,Introducing a New Way to Understand the Electi...,https://www.nytimes.com/2026/10/25/upshot/elec...
1,2026-10-25-23-45-51 +0000,chitri,Lake Street Bridge work will extend closure of...,https://www.chicagotribune.com/2026/10/25/lake...
2,2026-10-25-23-41-52 +0000,nyt,Live Updates: Polls Close in Brazil as Preside...,https://www.nytimes.com/live/2026/10/25/world/...
3,2026-10-25-23-41-49 +0000,nyt,The presidential election in Brazil is a test ...,https://www.nytimes.com/live/2026/10/25/world/...
4,2026-10-25-23-35-31 +0000,nyt,How Obama and Trump Made their Cases in Duelin...,https://www.nytimes.com/2026/10/25/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2597/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
30      trump     25
4    election     17
1         new     12
262        he     11
60    machado      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
211,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...,70
44,2026-10-25-21-02-05 +0000,startribune,Trump escalates rhetoric against El-Sayed as h...,https://www.startribune.com/trumps-midterm-swi...,67
91,2026-10-25-18-42-12 +0000,nyt,Trump’s Election Attacks Enter New Pre-emptive...,https://www.nytimes.com/2026/10/25/us/politics...,62
37,2026-10-25-21-17-42 +0000,nyt,María Corina Machado on Venezuela’s Future and...,https://www.nytimes.com/2026/10/19/world/ameri...,61
204,2026-10-25-02-27-15 +0000,bbc,Obama attacks Trump as he campaigns for Democr...,https://www.bbc.co.uk/news/articles/cmj6jwe1j1...,60

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
211,70,2026-10-25-01-32-15 +0000,nypost,Trump blasts Ossoff as ‘far left extremist’ as...,https://nypost.com/2026/10/24/us-news/trump-bl...
75,57,2026-10-25-19-38-58 +0000,nypost,Venezuelan opposition leader María Corina Mach...,https://nypost.com/2026/10/25/world-news/venez...
215,47,2026-10-25-01-00-00 +0000,wsj,"Rep. Alexandria Ocasio-Cortez, aka AOC, has so...",https://www.wsj.com/politics/elections/ocasio-...
141,43,2026-10-25-12-31-01 +0000,cbc,Israeli military conducts massive West Bank op...,https://www.cbc.ca/news/world/israel-west-bank...
111,41,2026-10-25-17-06-00 +0000,wsj,Attorney General Todd Blanche on Sunday offere...,https://www.wsj.com/politics/elections/alaska-...
148,36,2026-10-25-11-17-03 +0000,bbc,What to know about Brazil's run-off as Lula an...,https://www.bbc.co.uk/news/articles/c6wyz0r2n0...
78,35,2026-10-25-19-34-12 +0000,nypost,"Thomas Markle’s home had trove of child porn, ...",https://nypost.com/2026/10/25/world-news/thoma...
125,35,2026-10-25-15-20-17 +0000,nypost,Musk confirms SpaceX was behind thwarting of U...,https://nypost.com/2026/10/25/us-news/musk-con...
126,31,2026-10-25-15-08-34 +0000,latimes,Mystery Ohio news site boosting Ramaswamy's Am...,https://www.latimes.com/california/story/2026-...
220,30,2026-10-25-00-23-14 +0000,nypost,NFL WAGs seen partying it up in riot-torn Pari...,https://nypost.com/2026/10/24/sports/nfl-wags-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)