## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-24-08-25-47 +0000,nypost,Prosecutors seek 30-year prison term for South...,https://nypost.com/2026/04/24/world-news/prose...
1,2026-04-24-08-23-36 +0000,bbc,South Korea police arrest man for posting AI p...,https://www.bbc.com/news/articles/c4gx1n0dl9no...
2,2026-04-24-08-22-00 +0000,wsj,Kuehne + Nagel Lifts Lower-End of Earnings Gui...,https://www.wsj.com/business/earnings/kuehne-n...
3,2026-04-24-08-17-42 +0000,wsj,"Stock-Market Today: Stock Futures Mixed, Oil G...",https://www.wsj.com/livecoverage/stock-market-...
4,2026-04-24-08-14-18 +0000,nypost,Pentagon email floats suspending Spain from NA...,https://nypost.com/2026/04/24/us-news/pentagon...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2539/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
45   trump     43
39    iran     28
42     war     23
257    new     16
401     up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
5,2026-04-24-08-09-44 +0000,nyt,Iran War Live Updates: Trump Says Lebanon Ceas...,https://www.nytimes.com/live/2026/04/24/world/...,125
26,2026-04-24-06-56-27 +0000,nypost,"Israel, Lebanon extend cease-fire as Trump see...",https://nypost.com/2026/04/24/world-news/israe...,122
152,2026-04-23-21-23-43 +0000,nypost,Trump threatens to ‘finish it up militarily’ i...,https://nypost.com/2026/04/23/us-news/trump-th...,104
283,2026-04-23-16-02-26 +0000,wapo,Trump ally asked FIFA to have Italy replace Ir...,https://www.washingtonpost.com/world/2026/04/2...,96
171,2026-04-23-20-45-51 +0000,bbc,US boards ship carrying Iran oil as Trump thre...,https://www.bbc.com/news/articles/cgldw5ekrjpo...,96

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
5,125,2026-04-24-08-09-44 +0000,nyt,Iran War Live Updates: Trump Says Lebanon Ceas...,https://www.nytimes.com/live/2026/04/24/world/...
376,59,2026-04-23-10-00-00 +0000,latimes,California's rail systems need more riders. Hi...,https://www.latimes.com/california/story/2026-...
387,52,2026-04-23-09-01-14 +0000,nypost,"Parents of boy, 13, who allegedly killed touri...",https://nypost.com/2026/04/23/world-news/paren...
284,52,2026-04-23-15-57-53 +0000,nypost,Zohran Mamdani rips Warner Bros. Discovery’s P...,https://nypost.com/2026/04/23/business/zohran-...
207,49,2026-04-23-19-04-00 +0000,wsj,Oil Futures Rise As Middle East Jitters Pick Up,https://www.wsj.com/finance/commodities-future...
336,44,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
217,43,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
122,42,2026-04-23-22-34-54 +0000,nypost,US special forces soldier used secret intel fo...,https://nypost.com/2026/04/23/us-news/us-speci...
365,40,2026-04-23-11-09-00 +0000,wsj,There’s still one thing that unites us: Congre...,https://www.wsj.com/politics/policy/who-approv...
248,37,2026-04-23-17-00-11 +0000,wapo,"Once accused of election fraud, former small-t...",https://www.washingtonpost.com/nation/2026/04/...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)