## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-21-16-23-36 +0000,nyt,Keir Starmer Reflects on ‘Political Challenges...,https://www.nytimes.com/2026/06/21/world/europ...
1,2026-06-21-16-19-55 +0000,nyt,Mideast Live Updates: New Round of U.S.-Iran T...,https://www.nytimes.com/live/2026/06/21/world/...
2,2026-06-21-16-19-00 +0000,wsj,Opinion | Victory Over Iran Is Still Possible,https://www.wsj.com/opinion/victory-over-iran-...
3,2026-06-21-16-13-56 +0000,48hills,More Hunters Point toxic clean-up mess: ‘surpr...,https://48hills.org/2026/06/more-hunters-point...
4,2026-06-21-16-11-32 +0000,nypost,Paul Kueker ID’d as beloved dad of 2 who tragi...,https://nypost.com/2026/06/21/us-news/paul-kue...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2558/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
13    iran     22
89   trump     16
14   talks     13
320  world     11
11     new     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
125,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...,78
32,2026-06-21-14-39-00 +0000,wsj,Trump Threatens to Strike Iran Over Hezbollah ...,https://www.wsj.com/world/middle-east/war-in-l...,69
33,2026-06-21-14-36-29 +0000,nypost,Trump threatens to destroy Iran over Strait of...,https://nypost.com/2026/06/21/world-news/trump...,67
140,2026-06-20-22-34-00 +0000,wsj,"Vance Heads to Peace Talks, After Iran Says It...",https://www.wsj.com/world/middle-east/fighting...,62
31,2026-06-21-14-41-02 +0000,bbc,US and Iran begin talks on initial peace deal ...,https://www.bbc.com/news/articles/cwy0q41v1lzo...,62

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
125,78,2026-06-21-00-15-38 +0000,nypost,Vance lands in Switzerland for talks on Iran p...,https://nypost.com/2026/06/20/world-news/vance...
142,48,2026-06-20-22-11-17 +0000,nypost,Brazil soccer boss allegedly uses federation f...,https://nypost.com/2026/06/20/world-news/brazi...
95,40,2026-06-21-09-00-00 +0000,wsj,Jay Clayton has been a loyal ally and golf bud...,https://www.wsj.com/politics/policy/the-would-...
170,30,2026-06-20-17-45-53 +0000,latimes,Newsom and L.A. declare state of emergency as ...,https://www.latimes.com/business/story/2026-06...
136,29,2026-06-20-23-07-46 +0000,nypost,UK Prime Minister Keir Starmer set to resign a...,https://nypost.com/2026/06/20/world-news/uk-pr...
139,28,2026-06-20-22-41-34 +0000,wapo,Cyclist arrested at Reflecting Pool is former ...,https://www.washingtonpost.com/nation/2026/06/...
77,26,2026-06-21-10-00-00 +0000,startribune,Tolkkinen: Just because Minnesotans don't like...,https://www.startribune.com/tolkkinen-just-bec...
36,22,2026-06-21-14-00-00 +0000,nypost,Jewish ex-staffer says California college’s ch...,https://nypost.com/2026/06/21/us-news/employee...
152,21,2026-06-20-20-18-32 +0000,nypost,"Conflict erupts in Lebanon between Israel, Hez...",https://nypost.com/2026/06/20/world-news/confl...
176,21,2026-06-20-17-25-21 +0000,nypost,Italian PM claps back at Trump for ‘senseless’...,https://nypost.com/2026/06/20/us-news/italian-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)