## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-10-56-36 +0000,bbc,'Ghost particles' from space telescope wins ph...,https://www.bbc.co.uk/news/articles/cq203mymlv...
1,2026-10-06-10-54-18 +0000,nypost,Trump attacks Democratic Senate candidate Anni...,https://nypost.com/2026/10/06/us-news/trump-at...
2,2026-10-06-10-54-11 +0000,nyt,FIFA Found Congo Player Ineligible but Let Him...,https://www.nytimes.com/2026/10/06/world/europ...
3,2026-10-06-10-52-52 +0000,nypost,Francis Halzen wins Nobel Prize in physics for...,https://nypost.com/2026/10/06/world-news/franc...
4,2026-10-06-10-52-00 +0000,bbc,Tories pledge £10bn for British anti-missile d...,https://www.bbc.co.uk/news/articles/cxvgdl5npl...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2375/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
7     trump     32
194     new     24
258     oil     16
1600     de     15
454   house     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
222,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,171
174,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,125
314,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,92
38,2026-10-06-10-00-00 +0000,wsj,"Disney’s top lawyer, Horacio Gutiérrez, is tak...",https://www.wsj.com/business/media/disneys-top...,86
290,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
222,171,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
174,125,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
314,92,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
191,64,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
148,49,2026-10-06-02-22-24 +0000,bbc,Fort Hood shooter to be executed by firing squ...,https://www.bbc.co.uk/news/articles/cq8ezkkkrp...
118,45,2026-10-06-05-30-50 +0000,nypost,Concerns over possible Iranian drone attack pr...,https://nypost.com/2026/10/06/world-news/conce...
23,45,2026-10-06-10-09-00 +0000,wsj,Hackers Use Chinese AI Tool to Hit South Korea...,https://www.wsj.com/world/asia/hackers-use-chi...
278,42,2026-10-05-19-30-50 +0000,bbc,Spain PM pins hopes on housing crisis to help ...,https://www.bbc.co.uk/news/articles/ck5yn81qqd...
286,39,2026-10-05-19-03-08 +0000,nypost,Sailors reportedly offered $25K per trip to mo...,https://nypost.com/2026/10/05/business/sailors...
425,38,2026-10-05-11-47-09 +0000,wapo,FBI says California woman spied for China on T...,https://www.washingtonpost.com/world/2026/10/0...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)