## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-10-07-16-12 +0000,bbc,Burnham brings forward ban on 'subscription tr...,https://www.bbc.co.uk/news/articles/cly5x9qlnv...
1,2026-08-10-07-05-09 +0000,nypost,Divers find 162-year-old Guinness in shipwreck...,https://nypost.com/2026/08/10/world-news/diver...
2,2026-08-10-06-56-00 +0000,wsj,Dollar Recovers Marginally From Losses After W...,https://www.wsj.com/finance/currencies/asian-c...
3,2026-08-10-06-50-00 +0000,wsj,Oil Rises Amid Growing Doubts That Strait of H...,https://www.wsj.com/finance/stocks/oil-rises-a...
4,2026-08-10-06-46-22 +0000,nyt,"Typhoon Dolphin Barrels Into China, Prompting ...",https://www.nytimes.com/2026/08/10/world/asia/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2545/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
285   trump     23
206  senate      9
68     plan      9
340    iran      9
36    china      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
74,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...,76
79,2026-08-09-22-18-15 +0000,nypost,Far-left Senate hopeful Abdul El-Sayed blasts ...,https://nypost.com/2026/08/09/us-news/abdul-el...,75
164,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...,61
40,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...,60
81,2026-08-09-22-07-40 +0000,wapo,Netanyahu rejects Trump-backed Gaza plan for H...,https://www.washingtonpost.com/world/2026/08/0...,59

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
74,76,2026-08-09-22-50-00 +0000,wsj,Will Scharf will become the new White House co...,https://www.wsj.com/politics/policy/trump-name...
104,55,2026-08-09-19-53-25 +0000,nypost,Gavin Newsom confirms he’ll sit down with radi...,https://nypost.com/2026/08/09/us-news/gavin-ne...
164,38,2026-08-09-13-17-47 +0000,nypost,Israel ‘rejects’ Trump’s 15-point peace plan f...,https://nypost.com/2026/08/09/world-news/israe...
80,36,2026-08-09-22-10-00 +0000,wsj,Former President Joe Biden’s cancer has spread...,https://www.wsj.com/politics/hunter-bidens-com...
61,31,2026-08-10-00-00-00 +0000,wsj,The AI boom has pushed the bruising race for h...,https://www.wsj.com/real-estate/the-bruising-r...
184,31,2026-08-09-11-00-00 +0000,wsj,Trump Thought Opening the Strait of Hormuz Was...,https://www.wsj.com/world/middle-east/trump-st...
63,30,2026-08-09-23-47-30 +0000,bbc,You could be missing out on £150 off your ener...,https://www.bbc.co.uk/news/articles/czjlk8wx77...
40,29,2026-08-10-01-00-00 +0000,wsj,Downbeat economic views pose a danger for Repu...,https://www.wsj.com/politics/elections/the-rep...
55,25,2026-08-10-00-32-06 +0000,nypost,Burger King dethrones struggling Wendy’s 6-yea...,https://nypost.com/2026/08/09/business/burger-...
111,25,2026-08-09-19-14-55 +0000,nypost,AOC pushes voters to assess what Francesca Hon...,https://nypost.com/2026/08/09/us-news/aoc-push...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)