## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-18-11-49-38 +0000,nyt,Egypt’s Defense Chiefs Pledge to Support Saudi...,https://www.nytimes.com/2026/10/18/world/middl...
1,2026-10-18-11-35-40 +0000,nypost,Air Force commando crashes to ground while rap...,https://nypost.com/2026/10/18/us-news/air-forc...
2,2026-10-18-11-27-23 +0000,nypost,Blaze at St Petersburg oil sites as Ukraine la...,https://nypost.com/2026/10/18/world-news/blaze...
3,2026-10-18-11-22-38 +0000,nyt,"O.J. Simpson, a Secret Informant and a Decades...",https://www.nytimes.com/2026/10/18/us/oj-simps...
4,2026-10-18-11-14-33 +0000,bbc,Polanski says he will not overturn Green Party...,https://www.bbc.co.uk/news/articles/cmn8w5v8yn...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2618/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
137       trump     24
34           he     12
27       russia     11
202  california     11
151    protests      9

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...,93
172,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...,84
127,2026-10-17-20-57-00 +0000,wsj,President Trump is halting implementation of m...,https://www.wsj.com/politics/policy/trump-waiv...,76
201,2026-10-17-12-27-41 +0000,cbc,Zelenskyy urges support for new U.S. sanctions...,https://www.cbc.ca/news/world/zelenskyy-trump-...,65
161,2026-10-17-17-33-48 +0000,chitri,President Donald Trump’s decision to waive Rus...,https://www.chicagotribune.com/2026/10/17/trum...,63

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,93,2026-10-17-19-53-00 +0000,wsj,"In August, Kansas GOP Sen. Roger Marshall said...",https://www.wsj.com/politics/elections/kansas-...
78,49,2026-10-18-02-00-00 +0000,wsj,Republicans across the most competitive House ...,https://www.wsj.com/politics/elections/republi...
175,47,2026-10-17-15-38-04 +0000,nypost,Pope Leo released from hospital 4 days after l...,https://nypost.com/2026/10/17/world-news/who-r...
172,42,2026-10-17-15-51-07 +0000,chitri,Ukrainian president urges support for new US s...,https://www.chicagotribune.com/2026/10/17/zele...
159,36,2026-10-17-17-51-27 +0000,latimes,'No Kings' protests mobilize across California...,https://www.latimes.com/california/story/2026-...
80,31,2026-10-18-01-58-57 +0000,nypost,French rioters set fire to historic Limoges To...,https://nypost.com/2026/10/17/world-news/limog...
53,30,2026-10-18-09-00-00 +0000,wsj,Hakeem Jeffries is closing in on the Speaker’s...,https://www.wsj.com/politics/elections/the-dem...
119,30,2026-10-17-21-54-20 +0000,nypost,Abdul El-Sayed slammed for ‘racist’ Columbia ...,https://nypost.com/2026/10/17/us-news/el-sayed...
131,29,2026-10-17-20-43-00 +0000,wsj,Masked Israeli Settlers Attack European Diplom...,https://www.wsj.com/world/middle-east/masked-i...
63,24,2026-10-18-08-00-00 +0000,cbc,Freeland believes her resignation led to bette...,https://www.cbc.ca/news/politics/freeland-resi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)