## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-21-17-13-18 +0000,nyt,Iran War Live Updates: Vance’s Trip to Peace T...,https://www.nytimes.com/live/2026/04/21/world/...
1,2026-04-21-17-12-16 +0000,nyt,Vance’s Trip to Islamabad on Hold as Iran Fail...,https://www.nytimes.com/live/2026/04/21/world/...
2,2026-04-21-17-08-00 +0000,wsj,Opinion | The Price Beijing Pays for Backing T...,https://www.wsj.com/opinion/the-price-beijing-...
3,2026-04-21-17-07-49 +0000,nypost,Mamdani faces outrage over response to viral p...,https://nypost.com/2026/04/21/us-news/mamdani-...
4,2026-04-21-17-06-17 +0000,nyt,"With Orban Out, the Pianist Andras Schiff Plan...",https://www.nytimes.com/2026/04/20/arts/music/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2519/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
141  trump     28
0     iran     27
1      war     17
179    new     17
47    year     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
252,2026-04-21-01-14-06 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,108
255,2026-04-21-01-00-00 +0000,wsj,President Trump picked Kevin Warsh for Fed cha...,https://www.wsj.com/economy/central-banking/wa...,94
215,2026-04-21-07-26-13 +0000,nypost,Iran ‘prepared to reveal new cards on the batt...,https://nypost.com/2026/04/21/world-news/iran-...,91
133,2026-04-21-13-14-14 +0000,nypost,Trump doesn’t want to extend Iran cease-fire —...,https://nypost.com/2026/04/21/us-news/trump-do...,82
51,2026-04-21-16-04-06 +0000,nyt,Facing Hard-Liners at Home and Bluster From Tr...,https://www.nytimes.com/2026/04/20/world/middl...,81

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
252,108,2026-04-21-01-14-06 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...
255,66,2026-04-21-01-00-00 +0000,wsj,President Trump picked Kevin Warsh for Fed cha...,https://www.wsj.com/economy/central-banking/wa...
224,64,2026-04-21-05-57-56 +0000,bbc,New era as Apple names new boss to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
277,50,2026-04-20-22-16-55 +0000,wapo,Two teens killed after planned fight near Nort...,https://www.washingtonpost.com/nation/2026/04/...
290,44,2026-04-20-21-23-13 +0000,nypost,Labor Secretary Lori Chavez-DeRemer resigns fr...,https://nypost.com/2026/04/20/us-news/labor-se...
145,42,2026-04-21-12-34-39 +0000,nypost,Chilling video shows moment Mexico pyramid sho...,https://nypost.com/2026/04/21/world-news/mexic...
288,41,2026-04-20-21-32-00 +0000,wsj,Singer D4vd Pleads Not Guilty in Murder of 14-...,https://www.wsj.com/us-news/singer-d4vd-charge...
42,40,2026-04-21-16-17-37 +0000,nyt,She Made Sure Her Baby Was Born an American. T...,https://www.nytimes.com/2026/04/17/us/politics...
244,39,2026-04-21-02-00-00 +0000,wsj,"Companies are getting hit up for money twice, ...",https://www.wsj.com/politics/policy/the-rival-...
304,38,2026-04-20-20-51-03 +0000,nypost,Powerful California official pocketed thousand...,https://nypost.com/2026/04/20/us-news/fiona-ma...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)