## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-03-21-00-08 +0000,nyt,"Iran War Live Updates: American Rescued, Searc...",https://www.nytimes.com/live/2026/04/03/world/...
1,2026-04-03-21-00-05 +0000,nyt,Six Senate Races to Watch as Democrats Grow Bu...,https://www.nytimes.com/2026/04/03/us/politics...
2,2026-04-03-21-00-00 +0000,nypost,Ex-WWE employee shares shocking new details in...,https://nypost.com/2026/04/03/business/ex-wwe-...
3,2026-04-03-20-59-48 +0000,bbc,"Cuba begins releasing more than 2,000 prisoner...",https://www.bbc.com/news/articles/cwy3r3w4zl8o...
4,2026-04-03-20-59-00 +0000,wsj,Energy & Utilities Roundup: Market Talk,https://www.wsj.com/articles/energy-utilities-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2587/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
131  trump     41
0     iran     37
1      war     25
272   jobs     13
10     jet     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
33,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...,140
286,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...,127
172,2026-04-03-11-28-34 +0000,bbc,When will the Iran war end? Tracing the Trump ...,https://www.bbc.com/news/articles/c4g4e6z9960o...,122
294,2026-04-02-22-11-12 +0000,wapo,"As Trump doubles down on Iran war, markets shu...",https://www.washingtonpost.com/world/2026/04/0...,119
276,2026-04-02-23-16-43 +0000,nyt,Macron Voices Europe’s Frustration With Trump’...,https://www.nytimes.com/2026/04/02/world/middl...,110

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
33,140,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...
203,86,2026-04-03-09-30-00 +0000,wsj,The March jobs report due Friday morning will ...,https://www.wsj.com/economy/jobs/march-jobs-re...
286,86,2026-04-02-22-46-00 +0000,wsj,Defense Secretary Pete Hegseth ousted the Army...,https://www.wsj.com/politics/national-security...
49,44,2026-04-03-19-22-00 +0000,wsj,President Trump released a summary of his budg...,https://www.wsj.com/politics/policy/trump-budg...
186,44,2026-04-03-10-56-00 +0000,wsj,The near-term legal and political mess that is...,https://www.wsj.com/politics/chaos-over-bondis...
38,39,2026-04-03-19-57-47 +0000,nypost,Second American fighter jet crashes in Persian...,https://nypost.com/2026/04/03/us-news/second-a...
14,36,2026-04-03-20-42-17 +0000,nypost,Meet Bill de Bogotá: Ex-NYC Mayor de Blasio vi...,https://nypost.com/2026/04/03/us-news/meet-bil...
240,35,2026-04-03-03-29-06 +0000,nyt,A Bid to Use Force to Open Strait of Hormuz Hi...,https://www.nytimes.com/2026/04/02/world/middl...
35,30,2026-04-03-20-02-00 +0000,wsj,Supreme Court Justice Samuel Alito was taken t...,https://www.wsj.com/politics/policy/supreme-co...
48,30,2026-04-03-19-22-20 +0000,nypost,Fate of California’s last nuclear power plant ...,https://nypost.com/2026/04/03/us-news/fate-of-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)