## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-16-13-15-46 +0000,nyt,Maps Show Where Wildfire Smoke Will Darken Ski...,https://www.nytimes.com/2026/07/16/weather/can...
1,2026-07-16-13-14-41 +0000,nypost,FCC Chair David Carr calls California-led chal...,https://nypost.com/2026/07/16/media/fcc-chair-...
2,2026-07-16-13-10-00 +0000,wsj,Treasury Yields Rise as U.S. Job Market Remain...,https://www.wsj.com/finance/jgbs-mixed-as-inve...
3,2026-07-16-13-08-28 +0000,bbc,Teenager accused of carrying out sabotage acti...,https://www.bbc.co.uk/news/articles/cp305dx493...
4,2026-07-16-13-08-14 +0000,bbc,Investigation into parking tickets for drivers...,https://www.bbc.co.uk/news/articles/cnvnyr75r4...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2521/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
234  trump     51
84    iran     33
262    new     20
272    war     17
5     will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
226,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...,160
286,2026-07-15-20-26-19 +0000,nypost,"Trump doesn’t rule out decimating IRGC, warns ...",https://nypost.com/2026/07/15/us-news/trump-do...,131
168,2026-07-16-04-01-08 +0000,nyt,"In Iran war, Trump Risks Another American ‘For...",https://www.nytimes.com/2026/07/16/world/middl...,128
234,2026-07-15-22-32-37 +0000,nyt,"At War With Iran Again, Trump Finds an Opponen...",https://www.nytimes.com/2026/07/14/us/politics...,122
335,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...,122

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
226,160,2026-07-15-23-00-37 +0000,nypost,JD Vance tells Joe Rogan Israel wants to keep ...,https://nypost.com/2026/07/15/us-news/vance-te...
263,86,2026-07-15-21-27-00 +0000,wsj,The Air Force for the first time successfully ...,https://www.wsj.com/politics/national-security...
335,71,2026-07-15-17-55-00 +0000,wsj,Todd Blanche tried to ease concerns over a set...,https://www.wsj.com/politics/policy/blanche-se...
393,65,2026-07-15-14-08-00 +0000,wsj,The economy has added jobs for four straight m...,https://www.wsj.com/economy/jobs/unemployment-...
370,52,2026-07-15-15-51-44 +0000,nypost,Intrusive way California will target billionai...,https://nypost.com/2026/07/15/us-news/intrusiv...
274,51,2026-07-15-21-08-26 +0000,cbc,Argentina makes late comeback to secure World ...,https://www.cbc.ca/sports/soccer/worldcup/fifa...
229,50,2026-07-15-22-50-00 +0000,wsj,Homeland Security Secretary Markwayne Mullin a...,https://www.wsj.com/politics/policy/trump-was-...
257,46,2026-07-15-21-34-00 +0000,wsj,More than 100 House Democrats voted for a fail...,https://www.wsj.com/politics/policy/many-democ...
153,43,2026-07-16-05-24-49 +0000,nyt,India Is Moving Fast to Build A.I. Data Center...,https://www.nytimes.com/2026/07/16/world/asia/...
167,38,2026-07-16-04-05-28 +0000,nypost,Katie Porter says she’s done with politics aft...,https://nypost.com/2026/07/16/us-news/katie-po...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)