## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-13-09-03-46 +0000,nyt,U.K. and Europe Recoil From Trump’s Diesel Dea...,https://www.nytimes.com/2026/10/13/world/europ...
1,2026-10-13-09-03-38 +0000,nyt,"The Oct. 7 Attack Changed Israel, but Not Its ...",https://www.nytimes.com/2026/10/13/world/middl...
2,2026-10-13-09-03-33 +0000,nyt,Chef Daniel Boulud’s 5 Favorite Places in Lyon...,https://www.nytimes.com/2026/10/13/travel/dani...
3,2026-10-13-09-03-18 +0000,nyt,Hillary Clinton Steps to the Podcast Mic as Mi...,https://www.nytimes.com/2026/10/13/business/me...
4,2026-10-13-09-02-20 +0000,nyt,How Climate Change Is Causing ‘the Gentrificat...,https://www.nytimes.com/2026/10/13/dining/seaf...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2373/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
2     trump     45
69      new     18
38   russia     17
61       he     16
265  energy     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
308,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...,121
109,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...,111
341,2026-10-12-09-21-38 +0000,wapo,Trump’s diesel deal with Russia shows how tied...,https://www.washingtonpost.com/politics/2026/1...,110
173,2026-10-12-21-03-00 +0000,wsj,Why Trump’s Diesel-Supply Deal With Russia Won...,https://www.wsj.com/business/energy-oil/why-tr...,105
303,2026-10-12-11-47-59 +0000,nypost,Zelensky says Russia still striking energy fac...,https://nypost.com/2026/10/12/world-news/zelen...,104

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
308,121,2026-10-12-11-11-05 +0000,chitri,Ukraine president says Russia strikes energy f...,https://www.chicagotribune.com/2026/10/12/ukra...
101,66,2026-10-13-01-00-00 +0000,wsj,More damaging revelations about Ken Paxton: A ...,https://www.wsj.com/politics/policy/ken-paxton...
109,61,2026-10-13-00-28-00 +0000,wsj,President Trump said he is “looking at” firing...,https://www.wsj.com/politics/policy/trump-says...
37,53,2026-10-13-07-35-00 +0000,wsj,Oil Prices Fall as Traders Weigh Middle East R...,https://www.wsj.com/world/middle-east/oil-pric...
115,49,2026-10-12-23-44-00 +0000,wsj,"Federal agents searched the Washington, D.C., ...",https://www.wsj.com/politics/policy/ilhan-omar...
324,47,2026-10-12-10-27-34 +0000,nypost,Family of Thai teen sex worker found stuffed ...,https://nypost.com/2026/10/12/world-news/famil...
307,42,2026-10-12-11-14-24 +0000,nypost,Disturbing video shows moment Houthi terrorist...,https://nypost.com/2026/10/12/world-news/distu...
312,39,2026-10-12-11-02-40 +0000,chitri,2 American economists win Nobel prize for over...,https://www.chicagotribune.com/2026/10/12/nobe...
269,36,2026-10-12-15-03-42 +0000,bbc,AI minister warns 'likely' UK's cyber defences...,https://www.bbc.co.uk/news/articles/cr78pe09y0...
325,36,2026-10-12-10-14-45 +0000,chitri,Attorney and former Robbins police chief compe...,https://www.chicagotribune.com/2026/10/12/atto...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)