## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-23-21-01-40 +0000,nypost,Year-round mosquitos are thriving in LA — and ...,https://nypost.com/2026/03/23/us-news/plan-to-...
1,2026-03-23-21-00-23 +0000,nypost,Alleged Iranian spies are already in the US an...,https://nypost.com/2026/03/23/world-news/alleg...
2,2026-03-23-20-58-26 +0000,nyt,"Iran War Live Updates: U.S., Iran and Israel S...",https://www.nytimes.com/live/2026/03/23/world/...
3,2026-03-23-20-58-24 +0000,nyt,"Catherine T. Nolan, State Assembly Powerhouse ...",https://www.nytimes.com/2026/03/23/nyregion/ca...
4,2026-03-23-20-57-57 +0000,nypost,Off-duty cop who was just served a restraining...,https://nypost.com/2026/03/23/us-news/off-duty...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2538/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
64   trump     41
15    iran     40
16     war     21
276    new     17
84     oil     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
8,2026-03-23-20-55-03 +0000,startribune,Trump says Iran is eager for a deal to end the...,https://www.startribune.com/iran-threatens-to-...,127
217,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...,126
201,2026-03-23-13-16-13 +0000,nypost,"Dow rallies 600 points, oil tumbles below $100...",https://nypost.com/2026/03/23/business/dow-fut...,123
187,2026-03-23-14-08-41 +0000,nypost,Trump says ‘we don’t know’ if Iran’s new Supre...,https://nypost.com/2026/03/23/us-news/trump-sa...,121
276,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...,119

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
8,127,2026-03-23-20-55-03 +0000,startribune,Trump says Iran is eager for a deal to end the...,https://www.startribune.com/iran-threatens-to-...
134,82,2026-03-23-16-26-19 +0000,latimes,Californians may need to mail ballots early as...,https://www.latimes.com/politics/story/2026-03...
276,72,2026-03-23-03-30-00 +0000,wsj,ICE officers will begin trying to ease bottlen...,https://www.wsj.com/politics/policy/trump-admi...
47,50,2026-03-23-19-38-35 +0000,nypost,Antoine Forest identified as one of the Air Ca...,https://nypost.com/2026/03/23/us-news/antoine-...
217,45,2026-03-23-11-23-43 +0000,nypost,"Trump delays strikes on Iran power, energy pla...",https://nypost.com/2026/03/23/us-news/trump-de...
288,38,2026-03-23-01-00-00 +0000,wsj,Kevin Warsh promised to overhaul the Federal R...,https://www.wsj.com/economy/central-banking/fe...
13,35,2026-03-23-20-43-02 +0000,nypost,Anti-communist dance troupe Shen Yun claims CC...,https://nypost.com/2026/03/23/world-news/shen-...
114,35,2026-03-23-17-12-46 +0000,nypost,OnlyFans star Sophie Rain mourns Leo Radvinsky...,https://nypost.com/2026/03/23/business/onlyfan...
80,35,2026-03-23-18-20-21 +0000,cbc,Colombian military cargo plane crashes near Pe...,https://www.cbc.ca/news/world/colombia-militar...
51,32,2026-03-23-19-30-21 +0000,nypost,Loyola student Sheridan Gorman’s mom makes sol...,https://nypost.com/2026/03/23/us-news/loyola-s...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)