## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-20-13-00-00 +0000,missionlocal,Dark shadows,https://missionlocal.org/2026/10/dark-shadows/
1,2026-10-20-13-00-00 +0000,missionlocal,Gig firm WorkWhile to pay $2.3 million to sett...,https://missionlocal.org/2026/10/san-francisco...
2,2026-10-20-12-59-23 +0000,nyt,France Protests Show Europe’s Shift Away From ...,https://www.nytimes.com/2026/10/20/world/europ...
3,2026-10-20-12-55-30 +0000,bbc,UK to deploy jets to defend Saudi Arabia from ...,https://www.bbc.co.uk/news/articles/ckr5yqe1r1...
4,2026-10-20-12-54-43 +0000,bbc,Burnham risks wrath of Commons Speaker for tal...,https://www.bbc.co.uk/news/articles/crvg6qjw6d...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2670/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
62    trump     33
396     new     16
551      up     14
37   french     13
43     fire     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
232,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...,148
9,2026-10-20-12-45-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...,93
86,2026-10-20-10-30-00 +0000,wsj,"Ex-officials from the Trump, Biden and Obama a...",https://www.wsj.com/politics/policy/u-s-risks-...,82
345,2026-10-19-15-31-08 +0000,nypost,Donald Trump signs executive order creating NI...,https://nypost.com/2026/10/19/us-news/donald-t...,76
218,2026-10-19-21-49-41 +0000,nyt,DOJ Charges 28 California Residents With Votin...,https://www.nytimes.com/2026/10/19/us/politics...,74

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
232,148,2026-10-19-21-27-00 +0000,wsj,President Trump said he was open to talking de...,https://www.wsj.com/politics/policy/trump-says...
9,60,2026-10-20-12-45-00 +0000,wsj,The Trump administration plans to hand out ano...,https://www.wsj.com/politics/policy/trump-plan...
100,52,2026-10-20-10-00-00 +0000,nypost,"Kansas Dem Adam Hamilton, who made millions on...",https://nypost.com/2026/10/20/us-news/kansas-d...
353,51,2026-10-19-14-27-56 +0000,nyt,The French City of Limoges Wasn’t Known for Un...,https://www.nytimes.com/2026/10/18/world/franc...
24,50,2026-10-20-12-19-00 +0000,wsj,"The campaign of Republican David Flippo, who f...",https://www.wsj.com/politics/elections/a-dead-...
330,48,2026-10-19-16-42-59 +0000,nypost,Christiane Amanpour to exit CNN amid staffer c...,https://nypost.com/2026/10/19/media/christiane...
138,47,2026-10-20-07-33-00 +0000,wsj,"U.K. Wage Growth Picks Up, Jobless Rate Falls ...",https://www.wsj.com/world/uk/u-k-wage-growth-p...
344,41,2026-10-19-15-44-00 +0000,wsj,Economists surveyed by The Wall Street Journal...,https://www.wsj.com/finance/see-what-71-econom...
23,38,2026-10-20-12-24-07 +0000,cbc,Death toll in Houthi attack on Yemeni governme...,https://www.cbc.ca/news/world/houthi-attack-ye...
287,38,2026-10-19-19-04-42 +0000,nypost,Supreme Court rejects bid by 9/11 mastermind K...,https://nypost.com/2026/10/19/us-news/supreme-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)