## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-07-23-11-35 +0000,bbc,Trump gives EU ultimatum deadline to approve t...,https://www.bbc.com/news/articles/cp3pyk4nw3lo...
1,2026-05-07-23-08-42 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/05/07/world/...
2,2026-05-07-23-08-40 +0000,nyt,U.S. Awaits Iran’s Response to Latest Peace Pr...,https://www.nytimes.com/live/2026/05/07/world/...
3,2026-05-07-23-07-00 +0000,wsj,How Citigroup Can Get to the Next Level,https://www.wsj.com/finance/banking/how-citigr...
4,2026-05-07-23-06-34 +0000,nyt,U.S. Strikes Iranian Targets; Iran Says It Ret...,https://www.nytimes.com/2026/05/07/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2671/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
0         trump     37
8          iran     31
9           war     25
167  hantavirus     22
169        ship     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
365,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...,138
142,2026-05-07-19-06-43 +0000,bbc,Marco Rubio meets Pope Leo amid tensions with ...,https://www.bbc.com/news/videos/cq8py99p2jzo?a...,130
31,2026-05-07-22-15-00 +0000,wsj,A trade court ruled against Trump’s global tar...,https://www.wsj.com/tech/court-strikes-down-tr...,121
7,2026-05-07-23-02-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...,121
1,2026-05-07-23-08-42 +0000,nyt,Iran War Live Updates: U.S. and Iran Exchange ...,https://www.nytimes.com/live/2026/05/07/world/...,114

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
365,138,2026-05-07-01-00-00 +0000,wsj,The airline industry is warning the Trump admi...,https://www.wsj.com/politics/policy/jet-fuel-p...
40,97,2026-05-07-22-08-00 +0000,wsj,The Centers for Disease Control and Prevention...,https://www.wsj.com/politics/policy/cdc-coordi...
7,73,2026-05-07-23-02-00 +0000,wsj,A federal trade court ruled President Trump di...,https://www.wsj.com/economy/trade/trade-court-...
370,54,2026-05-07-00-45-00 +0000,wsj,Commerce Secretary Howard Lutnick told a congr...,https://www.wsj.com/politics/policy/lutnick-sa...
308,53,2026-05-07-09-33-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
42,45,2026-05-07-22-06-55 +0000,nypost,US launches ‘self-defense’ strikes after Iran ...,https://nypost.com/2026/05/07/us-news/us-launc...
161,41,2026-05-07-18-37-27 +0000,nypost,White House lashes out at ‘Star Wars’ actor Ma...,https://nypost.com/2026/05/07/us-news/white-ho...
243,41,2026-05-07-14-16-02 +0000,nypost,UAE sneaked 4 oil tankers through Strait of Ho...,https://nypost.com/2026/05/07/world-news/uae-s...
236,40,2026-05-07-14-53-13 +0000,nypost,Ted Turner’s eerie CNN ‘doomsday video’ — only...,https://nypost.com/2026/05/07/media/ted-turner...
230,40,2026-05-07-15-09-42 +0000,nyt,Rubio Meets Pope Leo Amid Growing Tensions Bet...,https://www.nytimes.com/2026/05/07/us/politics...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)