## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-24-19-06-54 +0000,chitri,Will County Board OKs two delayed appointments...,https://www.chicagotribune.com/2026/08/24/will...
1,2026-08-24-19-06-49 +0000,nypost,California grocery chain closes multiple store...,https://nypost.com/2026/08/24/business/beloved...
2,2026-08-24-19-04-44 +0000,chitri,"Andy Zay, Indiana Gov. Mike Braun reach settle...",https://www.chicagotribune.com/2026/08/24/andy...
3,2026-08-24-19-04-16 +0000,nypost,How homebuyers are using AI-powered realtors t...,https://nypost.com/2026/08/24/business/how-hom...
4,2026-08-24-19-03-59 +0000,nypost,Fox News shakes up ‘The Five’ with new full-ti...,https://nypost.com/2026/08/24/media/fox-news-s...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2512/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
138       trump     32
57         iran     20
43          new     17
144      canada     13
10   california     11

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
39,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...,102
17,2026-08-24-18-37-48 +0000,nyt,"Trump Threatens New 50% Tariffs on Cars, Truck...",https://www.nytimes.com/2026/08/24/business/ec...,97
56,2026-08-24-17-27-14 +0000,nypost,Trump unleashes ‘Operation Economic Outcast’ a...,https://nypost.com/2026/08/24/world-news/trump...,90
66,2026-08-24-16-50-00 +0000,wsj,The Trump administration is proposing a new si...,https://www.wsj.com/politics/policy/government...,86
214,2026-08-24-08-49-48 +0000,nyt,Which Countries Could Be Hurt Most by Trump’s ...,https://www.nytimes.com/article/us-iran-econom...,75

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
39,102,2026-08-24-17-48-00 +0000,wsj,New tariffs have kicked in on U.S. imports fro...,https://www.wsj.com/economy/trade/whats-gettin...
56,90,2026-08-24-17-27-14 +0000,nypost,Trump unleashes ‘Operation Economic Outcast’ a...,https://nypost.com/2026/08/24/world-news/trump...
244,42,2026-08-24-01-00-00 +0000,wsj,Kevin Warsh’s reluctance to signal where inter...,https://www.wsj.com/economy/central-banking/wa...
127,41,2026-08-24-13-48-12 +0000,nypost,California calls off Paramount settlement meet...,https://nypost.com/2026/08/24/business/califor...
86,36,2026-08-24-15-44-58 +0000,nypost,Utter pandemonium as mass street brawl between...,https://nypost.com/2026/08/24/us-news/utter-pa...
213,36,2026-08-24-08-58-03 +0000,cbc,"Fast-moving wildfire threatens Reno, Nevada, f...",https://www.cbc.ca/news/world/wildfire-nevada-...
41,36,2026-08-24-17-47-04 +0000,nyt,UK Prime Minister Burnham Arrives in Ukraine a...,https://www.nytimes.com/2026/08/24/world/europ...
53,33,2026-08-24-17-30-51 +0000,nyt,Someone Was Impersonating Collien Fernandes On...,https://www.nytimes.com/2026/08/23/magazine/co...
81,33,2026-08-24-15-52-59 +0000,nypost,Washington Post ordered to rehire columnist Ka...,https://nypost.com/2026/08/24/media/washington...
220,31,2026-08-24-08-06-51 +0000,wsj,Stock Market Today: Oil Maintains Declines Aft...,https://www.wsj.com/livecoverage/stock-market-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)