## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-02-00-08-17 +0000,nyt,Shooting at In-and-Out Burger in Idaho Leaves ...,https://www.nytimes.com/2026/08/01/us/in-n-out...
1,2026-08-02-00-02-18 +0000,bbc,Three killed after bomb detonated at Moscow re...,https://www.bbc.co.uk/news/articles/c86n4ljxp6...
2,2026-08-01-23-58-03 +0000,nypost,Florida Evangelist booted from Alaska Airlines...,https://nypost.com/2026/08/01/us-news/florida-...
3,2026-08-01-23-57-32 +0000,startribune,Fever’s Sophie Cunningham brings transgender a...,https://www.startribune.com/minnesota-lynx-ind...
4,2026-08-01-23-56-56 +0000,nypost,Saudi Arabia gearing up for major assault and ...,https://nypost.com/2026/08/01/world-news/saudi...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2631/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
197       trump     18
86   california     11
287    migrants     10
114       spain     10
87          new     10

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
32,2026-08-01-21-28-51 +0000,chitri,Jeanine Pirro refutes President Donald Trump’s...,https://www.chicagotribune.com/2026/08/01/hear...,49
31,2026-08-01-21-58-00 +0000,wsj,Trump Team Feuds Over Whether Reflecting Pool ...,https://www.wsj.com/us-news/trump-team-feuds-o...,48
118,2026-08-01-13-03-07 +0000,nypost,Spain installing containment fence between Mor...,https://nypost.com/2026/08/01/world-news/spain...,45
89,2026-08-01-16-08-45 +0000,cbc,Hunger and hostility cited by migrants as reas...,https://www.cbc.ca/news/world/ceuta-morocco-mi...,45
57,2026-08-01-19-30-50 +0000,nyt,Trump’s Polling Numbers Hit a New Low. Don’t E...,https://www.nytimes.com/2026/08/01/us/politics...,44

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
32,49,2026-08-01-21-28-51 +0000,chitri,Jeanine Pirro refutes President Donald Trump’s...,https://www.chicagotribune.com/2026/08/01/hear...
89,45,2026-08-01-16-08-45 +0000,cbc,Hunger and hostility cited by migrants as reas...,https://www.cbc.ca/news/world/ceuta-morocco-mi...
201,43,2026-08-01-00-44-41 +0000,chitri,Gianni Infantino abandons plans to sell FIFA W...,https://www.chicagotribune.com/2026/07/31/fifa...
79,40,2026-08-01-16-50-51 +0000,cbc,"Nirmal Purja, 'inspirational' Nepali climber, ...",https://www.cbc.ca/news/world/nepal-climber-ni...
39,37,2026-08-01-21-10-49 +0000,nypost,Teen lifeguard reveals near-death battle to sa...,https://nypost.com/2026/08/01/us-news/rookie-l...
91,34,2026-08-01-16-00-00 +0000,wsj,A Tech Founder Wanted to Start a New Country. ...,https://www.wsj.com/tech/a-tech-founder-wanted...
195,30,2026-08-01-01-01-00 +0000,wsj,"In purple Michigan, Rep. Haley Stevens and Abd...",https://www.wsj.com/politics/elections/michiga...
206,27,2026-08-01-00-20-23 +0000,nypost,Russian OnlyFans model avoids prison in Vladim...,https://nypost.com/2026/07/31/world-news/russi...
167,27,2026-08-01-06-59-15 +0000,nypost,Russia hits Ukrainian capital with ballistic m...,https://nypost.com/2026/08/01/world-news/russi...
83,26,2026-08-01-16-28-20 +0000,nypost,GOP hopeful predicts Dems’ lefty ‘crazy train’...,https://nypost.com/2026/08/01/us-news/mike-rog...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)