## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-06-19-19-27 +0000,nyt,Howard Lutnick Is Grilled by Lawmakers Over Ep...,https://www.nytimes.com/2026/05/06/business/ec...
1,2026-05-06-19-17-59 +0000,nyt,Iran War Live Updates: Tehran Considers U.S. P...,https://www.nytimes.com/live/2026/05/06/world/...
2,2026-05-06-19-14-50 +0000,nypost,Mayhem as Ring camera psycho appears in court ...,https://nypost.com/2026/05/06/us-news/mayhem-a...
3,2026-05-06-19-14-22 +0000,nypost,Horrifying moment cops shoot beloved rottweile...,https://nypost.com/2026/05/06/us-news/horrifyi...
4,2026-05-06-19-14-09 +0000,nyt,A Look Inside the Case That Enshrined Politica...,https://www.nytimes.com/2026/05/06/us/politics...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2376/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
13        trump     39
6          iran     31
47          new     27
305  california     18
385    governor     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
346,2026-05-05-21-40-07 +0000,cbc,Trump pauses U.S. effort to guide vessels thro...,https://www.cbc.ca/news/world/rubio-hegseth-ir...,115
129,2026-05-06-14-57-00 +0000,wsj,President Trump escalated his public feud with...,https://www.wsj.com/politics/national-security...,113
302,2026-05-06-00-12-00 +0000,wsj,Trump Administration Sues New York Times Over ...,https://www.wsj.com/us-news/law/trump-administ...,112
316,2026-05-05-23-10-33 +0000,nypost,Trump pauses ‘Project Freedom’ initiative in S...,https://nypost.com/2026/05/05/us-news/trump-pa...,110
174,2026-05-06-12-14-10 +0000,nypost,Trump tells Post ‘too soon’ to prep for Iran p...,https://nypost.com/2026/05/06/us-news/trump-te...,107

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
346,115,2026-05-05-21-40-07 +0000,cbc,Trump pauses U.S. effort to guide vessels thro...,https://www.cbc.ca/news/world/rubio-hegseth-ir...
147,88,2026-05-06-14-16-51 +0000,wapo,Hantavirus-hit cruise ship to head to Canary I...,https://www.washingtonpost.com/health/2026/05/...
252,73,2026-05-06-06-46-38 +0000,latimes,"Top takeaways from fiery, at times ugly, Calif...",https://www.latimes.com/california/story/2026-...
376,54,2026-05-05-20-05-00 +0000,wsj,There is concern about how AI is affecting wor...,https://www.wsj.com/economy/jobs/layoffs-2026-...
357,53,2026-05-05-21-13-00 +0000,wsj,"After pressure from Trump, the FDA OKs some fl...",https://www.wsj.com/politics/policy/after-trum...
57,52,2026-05-06-17-38-42 +0000,nypost,Ex-JPMorgan banker Chirayu Rana was referred f...,https://nypost.com/2026/05/06/business/ex-jpmo...
349,48,2026-05-05-21-32-17 +0000,cbc,Prosecutors add assault charge to case against...,https://www.cbc.ca/news/world/assault-charge-w...
324,48,2026-05-05-22-48-22 +0000,nypost,Oil production won’t return to normal until af...,https://nypost.com/2026/05/05/world-news/oil-p...
113,47,2026-05-06-15-28-00 +0000,wsj,The job market is starting to show glimmers of...,https://www.wsj.com/economy/jobs/jobs-payroll-...
71,44,2026-05-06-17-21-15 +0000,nypost,"Trump, Ric Flair, Atlanta Braves, media perso...",https://nypost.com/2026/05/06/media/trump-ric-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)