## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-23-23-07-34 +0000,nypost,Iran reportedly drops more mines in Strait of ...,https://nypost.com/2026/04/23/world-news/iran-...
1,2026-04-23-23-04-30 +0000,wapo,Israel and Lebanon extend ceasefire for three ...,https://www.washingtonpost.com/national-securi...
2,2026-04-23-23-03-20 +0000,nypost,Ukraine pitches naming coveted Donbas section ...,https://nypost.com/2026/04/23/world-news/ukrai...
3,2026-04-23-23-01-09 +0000,nypost,Real New Yorkers furious over ‘microlooting’ w...,https://nypost.com/2026/04/23/us-news/real-new...
4,2026-04-23-22-59-00 +0000,wsj,U.S. authorities charged an Army soldier who t...,https://www.wsj.com/politics/policy/u-s-soldie...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2557/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
15   trump     39
0     iran     30
29     new     19
121    war     19
270     up     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
260,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...,122
11,2026-04-23-22-48-35 +0000,nyt,Iran War Live Updates: Trump Says Israel and L...,https://www.nytimes.com/live/2026/04/23/world/...,117
346,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...,103
58,2026-04-23-21-23-43 +0000,nypost,Trump threatens to ‘finish it up militarily’ i...,https://nypost.com/2026/04/23/us-news/trump-th...,102
79,2026-04-23-20-45-51 +0000,bbc,US boards ship carrying Iran oil as Trump thre...,https://www.bbc.com/news/articles/cgldw5ekrjpo...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
260,122,2026-04-23-13-06-10 +0000,nypost,Trump says he ordered Navy to ‘shoot and kill’...,https://nypost.com/2026/04/23/us-news/trump-sa...
346,73,2026-04-23-01-55-27 +0000,nypost,Lufthansa slashes 20K flights to save jet fuel...,https://nypost.com/2026/04/22/world-news/lufth...
61,58,2026-04-23-21-11-10 +0000,nypost,"NYC wigmaker who fatally mowed down mom, 2 dau...",https://nypost.com/2026/04/23/us-news/nyc-wigm...
195,55,2026-04-23-16-09-12 +0000,nypost,Lululemon shares dive on new CEO pick — as inv...,https://nypost.com/2026/04/23/business/lululem...
259,49,2026-04-23-13-09-00 +0000,wsj,The main outside group supporting Democrats’ e...,https://www.wsj.com/politics/elections/democra...
186,47,2026-04-23-16-19-39 +0000,nypost,Warner Bros. Discovery shareholders vote to ap...,https://nypost.com/2026/04/23/media/warner-bro...
291,39,2026-04-23-11-09-00 +0000,wsj,There’s still one thing that unites us: Congre...,https://www.wsj.com/politics/policy/who-approv...
163,39,2026-04-23-17-00-11 +0000,wapo,"Once accused of election fraud, former small-t...",https://www.washingtonpost.com/nation/2026/04/...
128,39,2026-04-23-18-35-00 +0000,wsj,The U.S. has burned through so many munitions ...,https://www.wsj.com/politics/national-security...
338,36,2026-04-23-04-25-30 +0000,bbc,Lebanon accuses Israel of targeting journalist...,https://www.bbc.com/news/articles/c5yvn036evlo...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)