## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-05-29-20-40-12 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/05/29/world/...
1,2026-05-29-20-35-46 +0000,nypost,"Cowboy hat wearing Rep. Frederica Wilson, 83, ...",https://nypost.com/2026/05/29/us-news/rep-fred...
2,2026-05-29-20-33-28 +0000,nyt,Bus Crash in Virginia Kills 5 and Injures More...,https://www.nytimes.com/2026/05/29/us/bus-cras...
3,2026-05-29-20-31-52 +0000,nypost,Trump’s top Wall Street cop shoots down Biden-...,https://nypost.com/2026/05/29/business/trumps-...
4,2026-05-29-20-31-26 +0000,nypost,Dilapidated FDNY firehouses plagued by huge le...,https://nypost.com/2026/05/29/us-news/rockaway...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2631/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
16       trump     37
1374       bee     20
42        iran     20
1373  spelling     18
223        new     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
276,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,139
279,2026-05-29-01-10-16 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,139
294,2026-05-29-00-11-26 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,139
253,2026-05-29-03-25-14 +0000,wapo,Live updates: Shrey Parikh wins Scripps Nation...,https://www.washingtonpost.com/dc-md-va/2026/0...,139
274,2026-05-29-01-47-48 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...,139

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
276,139,2026-05-29-01-29-56 +0000,wapo,Live updates: Scripps National Spelling Bee fi...,https://www.washingtonpost.com/dc-md-va/2026/0...
363,121,2026-05-28-21-04-00 +0000,wsj,The Trump administration has been holding talk...,https://www.wsj.com/politics/policy/putting-tr...
137,73,2026-05-29-15-18-42 +0000,nypost,Trump convenes Situation Room meeting for ‘fin...,https://nypost.com/2026/05/29/us-news/trump-sa...
32,63,2026-05-29-19-52-00 +0000,wsj,Democratic lawmakers said former AG Pam Bondi ...,https://www.wsj.com/politics/policy/pam-bondi-...
333,57,2026-05-28-22-05-54 +0000,nypost,Democrats enraged by Jill Biden’s book as ex-f...,https://nypost.com/2026/05/28/us-news/democrat...
159,50,2026-05-29-14-05-00 +0000,wsj,Dell shares soared in after-hours trading Thur...,https://www.wsj.com/tech/dell-stock-soars-on-d...
148,47,2026-05-29-14-39-43 +0000,nypost,Kenya court suspends US plan to establish Ebol...,https://nypost.com/2026/05/29/world-news/kenya...
174,46,2026-05-29-13-00-00 +0000,wsj,You Won the Battle on Investment Fees. You’re ...,https://www.wsj.com/finance/investing/you-won-...
144,42,2026-05-29-14-50-14 +0000,nypost,NATO vows to ‘defend every inch of Allied terr...,https://nypost.com/2026/05/29/world-news/nato-...
40,41,2026-05-29-19-38-29 +0000,nypost,‘Hell on wheel’s killer Mackenzie Shirilla fla...,https://nypost.com/2026/05/29/us-news/mackenzi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)