## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-20-01-10-56 +0000,nyt,Trump Threatens Economic Pain for Countries Th...,https://www.nytimes.com/2026/08/19/us/politics...
1,2026-08-20-01-09-58 +0000,nypost,LA mailman caught attacking beloved neighborho...,https://nypost.com/2026/08/19/us-news/pasadena...
2,2026-08-20-01-08-00 +0000,wsj,"Nikkei Rises 0.6%, Tracking Wall Street’s Gains",https://www.wsj.com/finance/stocks/nikkei-rise...
3,2026-08-20-01-03-08 +0000,nypost,Mob of looters wanted after ransacking same Ea...,https://nypost.com/2026/08/19/us-news/police-h...
4,2026-08-20-01-02-51 +0000,bbc,Trump threatens 'tremendous economic consequen...,https://www.bbc.co.uk/news/articles/c2k7e83ynj...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2463/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
0      trump     67
195      new     17
168  florida     16
74        up     15
6       iran     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
204,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...,132
245,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...,132
110,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...,131
71,2026-08-19-21-51-21 +0000,latimes,"Trump-backed candidates struggle, and other ta...",https://www.latimes.com/politics/story/2026-08...,128
155,2026-08-19-19-15-24 +0000,chitri,President Donald Trump picks Dr. Heidi Overton...,https://www.chicagotribune.com/2026/08/19/trum...,126

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
204,132,2026-08-19-17-20-41 +0000,nypost,Trump claims he told scandal-hit Florida Rep. ...,https://nypost.com/2026/08/19/us-news/trump-cl...
224,71,2026-08-19-16-34-00 +0000,wsj,Takeaways from elections in Florida: A Democra...,https://www.wsj.com/politics/elections/key-flo...
245,65,2026-08-19-15-47-31 +0000,bbc,Trump pauses new tariffs on Canada for three d...,https://www.bbc.co.uk/news/articles/cy9wz79ze2...
110,64,2026-08-19-20-54-00 +0000,wsj,President Trump has selected one of his top Wh...,https://www.wsj.com/politics/trump-taps-dr-hei...
369,62,2026-08-19-08-10-01 +0000,wsj,"Stock Market News, Aug. 19, 2026: Bond Yields ...",https://www.wsj.com/livecoverage/stock-market-...
250,55,2026-08-19-15-33-32 +0000,bbc,Israel confirms soldiers fired at car in which...,https://www.bbc.co.uk/news/articles/crl7yjlpx2...
171,46,2026-08-19-18-33-36 +0000,nypost,Data center backlash poised to play critical r...,https://nypost.com/2026/08/19/business/data-ce...
150,44,2026-08-19-19-45-34 +0000,nypost,Iran threatens to strike US bases in Europe if...,https://nypost.com/2026/08/19/world-news/iran-...
210,41,2026-08-19-17-07-33 +0000,nypost,Five Americans killed in fiery Kenya helicopte...,https://nypost.com/2026/08/19/world-news/ameri...
341,39,2026-08-19-10-00-00 +0000,latimes,Orange County investor accused of criminal fra...,https://www.latimes.com/business/story/2026-08...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)