## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-12-11-45-27 +0000,nypost,Missing newlywed Dominick Bianchi’s concerned ...,https://nypost.com/2026/09/12/us-news/missing-...
1,2026-09-12-11-27-44 +0000,bbc,A united Ireland would be 'fantastic' says Tru...,https://www.bbc.co.uk/news/articles/cy0zvx15ry...
2,2026-09-12-11-19-45 +0000,nypost,Anna Wintour’s Greenwich Village block overrun...,https://nypost.com/2026/09/12/us-news/anna-win...
3,2026-09-12-11-00-34 +0000,bbc,Saudi Arabia shuts key oil pipeline after dron...,https://www.bbc.co.uk/news/articles/c62m933465...
4,2026-09-12-11-00-00 +0000,missionlocal,"For years, one of San Francisco’s oldest barbe...",https://missionlocal.org/2026/09/sf-shears-bar...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2559/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
18       trump     39
38         oil     18
378       iran     14
229  inflation     14
97         war     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
102,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...,114
135,2026-09-11-21-19-00 +0000,wsj,"The Fed is poised to raise rates, a vital oil ...",https://www.wsj.com/economy/central-banking/th...,109
199,2026-09-11-18-19-00 +0000,wsj,"GOP Sen. Susan Collins, who faces a tough re-e...",https://www.wsj.com/politics/policy/embattled-...,93
200,2026-09-11-18-19-00 +0000,wsj,The annual inflation rate stalled out last mon...,https://www.wsj.com/economy/cpi-inflation-repo...,90
281,2026-09-11-14-57-30 +0000,nypost,Trump links Iran war to 9/11 in 25th anniversa...,https://nypost.com/2026/09/11/us-news/trump-li...,85

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
102,114,2026-09-12-00-00-00 +0000,wsj,"For most Americans, oil-fueled inflation shows...",https://www.wsj.com/economy/how-energy-is-driv...
199,93,2026-09-11-18-19-00 +0000,wsj,"GOP Sen. Susan Collins, who faces a tough re-e...",https://www.wsj.com/politics/policy/embattled-...
173,60,2026-09-11-19-37-00 +0000,wsj,Investors have all but concluded the Federal R...,https://www.wsj.com/economy/central-banking/th...
125,58,2026-09-11-21-36-06 +0000,nypost,Strikes set Saudi oil pipeline on fire as Iran...,https://nypost.com/2026/09/11/world-news/strik...
174,47,2026-09-11-19-36-00 +0000,wsj,A CIA official who authorities said walked out...,https://www.wsj.com/politics/national-security...
58,46,2026-09-12-04-03-16 +0000,nypost,Engineer with close ties to Fox News hosts sta...,https://nypost.com/2026/09/12/us-news/engineer...
236,44,2026-09-11-16-56-21 +0000,nypost,California’s most powerful union boss threaten...,https://nypost.com/2026/09/11/us-news/californ...
171,44,2026-09-11-19-44-58 +0000,bbc,Lightning Houthi advance in Yemen may bring da...,https://www.bbc.co.uk/news/articles/c3v4zgzr1k...
200,37,2026-09-11-18-19-00 +0000,wsj,The annual inflation rate stalled out last mon...,https://www.wsj.com/economy/cpi-inflation-repo...
113,36,2026-09-11-22-52-05 +0000,missionlocal,Meet the S.F. school board candidates: Do you ...,https://missionlocal.org/2026/09/san-francisco...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)