## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-04-07-07-51 +0000,nyt,Iran War Live Updates: U.S. Forces Search for ...,https://www.nytimes.com/live/2026/04/04/world/...
1,2026-04-04-06-49-48 +0000,nypost,"One killed, dozens hurt as Peru stadium event ...",https://nypost.com/2026/04/04/world-news/peru-...
2,2026-04-04-06-42-48 +0000,bbc,Artemis II crew now halfway to Moon as they ta...,https://www.bbc.com/news/articles/ce8jzr423p9o...
3,2026-04-04-06-38-38 +0000,nypost,KitKat launches stolen chocolate tracker after...,https://nypost.com/2026/04/04/world-news/kitka...
4,2026-04-04-06-34-56 +0000,bbc,Football rally in Peru leaves one dead and doz...,https://www.bbc.com/news/articles/ckgxyn3ljgjo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2458/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
109   trump     42
0      iran     34
1       war     20
377  report     13
376    jobs     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
124,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...,127
0,2026-04-04-07-07-51 +0000,nyt,Iran War Live Updates: U.S. Forces Search for ...,https://www.nytimes.com/live/2026/04/04/world/...,118
238,2026-04-03-11-28-34 +0000,bbc,When will the Iran war end? Tracing the Trump ...,https://www.bbc.com/news/articles/c4g4e6z9960o...,117
51,2026-04-04-00-02-20 +0000,nyt,War With Iran Clarifies Trump’s Spending Prior...,https://www.nytimes.com/2026/04/02/us/politics...,115
209,2026-04-03-14-28-47 +0000,latimes,2 U.S. aircraft downed as Iran war escalates; ...,https://www.latimes.com/world-nation/story/202...,106

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
124,127,2026-04-03-20-06-16 +0000,nypost,Trump says Iran peace talks won’t be derailed ...,https://nypost.com/2026/04/03/world-news/trump...
265,80,2026-04-03-09-30-00 +0000,wsj,The March jobs report due Friday morning will ...,https://www.wsj.com/economy/jobs/march-jobs-re...
209,52,2026-04-03-14-28-47 +0000,latimes,2 U.S. aircraft downed as Iran war escalates; ...,https://www.latimes.com/world-nation/story/202...
132,50,2026-04-03-19-22-00 +0000,wsj,President Trump released a summary of his budg...,https://www.wsj.com/politics/policy/trump-budg...
250,41,2026-04-03-10-56-00 +0000,wsj,The near-term legal and political mess that is...,https://www.wsj.com/politics/chaos-over-bondis...
129,39,2026-04-03-19-45-08 +0000,latimes,Two fires break out in Southern California ami...,https://www.latimes.com/california/story/2026-...
70,32,2026-04-03-22-35-05 +0000,nyt,Ex-US Army Pilot Recalls Battle for Survival W...,https://www.nytimes.com/2026/04/03/world/middl...
110,29,2026-04-03-20-54-00 +0000,wsj,"Tech, Media & Telecom Roundup: Market Talk",https://www.wsj.com/finance/investing/tech-med...
54,26,2026-04-04-00-00-00 +0000,wsj,These AI Whiz Kids Dropped Out of College and ...,https://www.wsj.com/tech/ai/ai-college-dropout...
163,25,2026-04-03-16-47-39 +0000,nypost,French-owned container ship safely passes thro...,https://nypost.com/2026/04/03/world-news/frenc...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)