## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-29-20-52-46 +0000,nypost,LIRR rider satisfaction takes a dip after MTA’...,https://nypost.com/2026/09/29/us-news/lirr-rid...
1,2026-09-29-20-52-18 +0000,nypost,"OpenAI, Google, Anthropic agree to attend AI h...",https://nypost.com/2026/09/29/us-news/openai-g...
2,2026-09-29-20-52-14 +0000,nyt,The Latin American Right’s Big Bet,https://www.nytimes.com/2026/09/29/world/latin...
3,2026-09-29-20-51-13 +0000,bbc,Would you pay for this robot to clean your house?,https://www.bbc.co.uk/news/videos/c6lyq52wx7dk...
4,2026-09-29-20-50-43 +0000,bbc,Former American Idol contestant and pastor fou...,https://www.bbc.co.uk/news/articles/c5rm9gv7n0...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2518/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
61     trump     40
85       new     24
15        ai     17
541  burnham     13
193      ban     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
153,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...,109
212,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...,91
123,2026-09-29-17-27-33 +0000,chitri,President Trump says top tech firms have signe...,https://www.chicagotribune.com/2026/09/29/dona...,86
80,2026-09-29-18-59-36 +0000,cbc,Trump trade adviser says Canada will 'pay even...,https://www.cbc.ca/news/politics/peter-navarro...,81
29,2026-09-29-20-24-18 +0000,bbc,Trump rules out joint US-China venture to deve...,https://www.bbc.co.uk/news/articles/cwly5lmvy3...,79

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
153,109,2026-09-29-16-27-00 +0000,wsj,The Trump administration used Homeland Securit...,https://www.wsj.com/politics/policy/homeland-s...
77,73,2026-09-29-19-10-00 +0000,wsj,New York Fed President John Williams said that...,https://www.wsj.com/economy/central-banking/ne...
126,64,2026-09-29-17-22-18 +0000,nyt,Prime Minister Andy Burnham Lays Out Plan to C...,https://www.nytimes.com/2026/09/29/world/europ...
266,57,2026-09-29-11-00-57 +0000,chitri,News organizations ask court to bar White Hous...,https://www.chicagotribune.com/2026/09/29/news...
323,51,2026-09-29-08-19-57 +0000,wsj,Stock Market Today: 10-Year Treasury Yield Pus...,https://www.wsj.com/livecoverage/stock-market-...
212,51,2026-09-29-13-52-17 +0000,nypost,Senate Republicans rip ‘dirtbag’ Jack Smith ov...,https://nypost.com/2026/09/29/us-news/jack-smi...
102,48,2026-09-29-18-14-48 +0000,chitri,Pete Hegseth says national security and milita...,https://www.chicagotribune.com/2026/09/29/pete...
391,46,2026-09-28-22-49-23 +0000,nypost,OpenAI pulls plug on ‘untrustworthy’ new AI mo...,https://nypost.com/2026/09/28/tech/openai-pull...
53,43,2026-09-29-19-48-42 +0000,nypost,Psycho South Carolina mom stabs her two kids o...,https://nypost.com/2026/09/29/us-news/psycho-s...
95,36,2026-09-29-18-45-00 +0000,cbc,British police say no explosives found in vehi...,https://www.cbc.ca/news/world/uk-us-base-foile...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)