## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-06-20-08-00-00 +0000,cbc,Canadian lawyers urge crackdown over Alabama p...,https://www.cbc.ca/news/politics/forced-labour...
1,2026-06-20-08-00-00 +0000,cbc,A legal challenge opens a new front in the deb...,https://www.cbc.ca/news/politics/climate-accou...
2,2026-06-20-08-00-00 +0000,cbc,U.S. claims about higher drug trafficking from...,https://www.cbc.ca/news/politics/us-canada-tru...
3,2026-06-20-07-24-27 +0000,nypost,3 hikers die of suspected heat-related illness...,https://nypost.com/2026/06/20/us-news/three-hi...
4,2026-06-20-07-10-37 +0000,nypost,Husband accused of killing wife on wedding nig...,https://nypost.com/2026/06/20/us-news/mexican-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2548/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
319   iran     23
56   trump     21
110  world     17
111    cup     16
11     new     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
106,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...,84
127,2026-06-19-17-52-27 +0000,latimes,Arellano: The joy of Mexico's World Cup soccer...,https://www.latimes.com/california/story/2026-...,69
227,2026-06-19-11-21-09 +0000,bbc,The US World Cup star who couldn't be an Ameri...,https://www.bbc.com/sport/football/articles/c2...,68
256,2026-06-19-09-54-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...,68
148,2026-06-19-16-37-27 +0000,nyt,Trump’s Iran Deal Is Off to a Chaotic Start,https://www.nytimes.com/2026/06/19/world/middl...,66

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
106,84,2026-06-19-19-06-59 +0000,nypost,"Trump shows off new Air Force One, thanks Qata...",https://nypost.com/2026/06/19/us-news/aging-ai...
256,68,2026-06-19-09-54-38 +0000,nyt,"Burnham Wins Makerfield By-Election, Clearing ...",https://www.nytimes.com/live/2026/06/19/world/...
71,58,2026-06-19-22-31-39 +0000,nyt,Lebanon Emerges as Weak Link in U.S.-Iran Deal...,https://www.nytimes.com/2026/06/19/world/middl...
141,56,2026-06-19-17-00-00 +0000,wsj,Warsh’s first test as Fed chairman will be rea...,https://www.wsj.com/economy/central-banking/fe...
120,44,2026-06-19-18-20-00 +0000,wsj,The Fed’s vice chair of supervision spoke at a...,https://www.wsj.com/economy/central-banking/to...
134,39,2026-06-19-17-36-40 +0000,nypost,Russia mistakenly strikes own refinery in Mosc...,https://nypost.com/2026/06/19/world-news/russi...
44,38,2026-06-20-00-49-47 +0000,nypost,"JJ Watt, American Airlines help rescue viral s...",https://nypost.com/2026/06/19/us-news/private-...
188,38,2026-06-19-14-25-47 +0000,nypost,Ken Griffin pushes NYC business leaders to ‘fi...,https://nypost.com/2026/06/19/business/ken-gri...
158,37,2026-06-19-15-46-59 +0000,nypost,Houston TV meteorologist whines she never won ...,https://nypost.com/2026/06/19/media/houston-tv...
130,32,2026-06-19-17-49-07 +0000,nypost,"DOJ’s civil rights chief slams Giants, MLB aft...",https://nypost.com/2026/06/19/us-news/harmeet-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)