## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-15-22-53-17 +0000,nypost,Lawler’s Dem opponent Cait Conley throws Hochu...,https://nypost.com/2026/10/15/us-news/lawlers-...
1,2026-10-15-22-49-24 +0000,nypost,Cait Conley finally denounces Mamdani’s Oct. 7...,https://nypost.com/2026/10/15/us-news/cait-con...
2,2026-10-15-22-47-08 +0000,nyt,Venezuela’s Opposition Leader Breaks With Trum...,https://www.nytimes.com/2026/10/15/world/ameri...
3,2026-10-15-22-47-05 +0000,nypost,Wheelchair-bound felon shoots 2 cops before SW...,https://nypost.com/2026/10/15/us-news/wheelcha...
4,2026-10-15-22-46-49 +0000,bbc,Letters with 'suspicious substances' sent to U...,https://www.bbc.co.uk/news/articles/cmq8n513x5...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2605/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
27        trump     37
204         new     27
128     ukraine     22
356          ai     15
340  california     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
59,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...,183
232,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...,130
85,2026-10-15-20-46-18 +0000,chitri,Ukraine abandons truce and attacks Russian oil...,https://www.chicagotribune.com/2026/10/15/ukra...,115
93,2026-10-15-20-35-57 +0000,nyt,Zelensky Says Ukraine Will Resume Russian Refi...,https://www.nytimes.com/2026/10/15/world/europ...,103
114,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...,102

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
59,183,2026-10-15-21-29-00 +0000,wsj,Ukraine resumed strikes on Russian refineries ...,https://www.wsj.com/politics/policy/ukraine-re...
114,102,2026-10-15-19-56-40 +0000,chitri,New White House press secretary Katie Zacharia...,https://www.chicagotribune.com/2026/10/15/kati...
365,73,2026-10-15-03-25-00 +0000,wsj,Texas Democrat and Senate hopeful James Talari...,https://www.wsj.com/politics/elections/five-ta...
227,66,2026-10-15-14-46-00 +0000,wsj,Economic damage from high energy prices and ri...,https://www.wsj.com/economy/global/ai-boom-shi...
232,55,2026-10-15-14-29-26 +0000,nypost,Volodymyr Zelensky openly defies Trump’s ban o...,https://nypost.com/2026/10/15/world-news/volod...
337,50,2026-10-15-08-46-43 +0000,cbc,"School roof collapses in Pakistan, killing at ...",https://www.cbc.ca/news/world/school-pakistan-...
236,46,2026-10-15-14-19-00 +0000,wsj,Florida’s Democratic Senate nominee Angie Nixo...,https://www.wsj.com/politics/elections/the-int...
36,42,2026-10-15-22-01-00 +0000,wsj,New York City Comptroller Mark Levine defended...,https://www.wsj.com/politics/new-york-city-com...
383,42,2026-10-15-00-28-58 +0000,nyt,"Inflation Data Shows Prices Are Up, Worrying R...",https://www.nytimes.com/2026/10/14/us/politics...
380,42,2026-10-15-01-00-00 +0000,wsj,Money from Tether flowed to Bo Hines’s company...,https://www.wsj.com/politics/policy/crypto-law...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)