## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-14-19-17-56 +0000,nyt,"Europe, Flexing Muscle in Ukraine, Is Still on...",https://www.nytimes.com/2026/07/14/world/europ...
1,2026-07-14-19-13-49 +0000,bbc,Strait of Hormuz remains a fault line as Iran ...,https://www.bbc.co.uk/news/articles/cwy0ydn033...
2,2026-07-14-19-11-37 +0000,bbc,Colombian national killed by ICE agent during ...,https://www.bbc.co.uk/news/articles/c2ly580kxn...
3,2026-07-14-19-05-35 +0000,nypost,Gavin Newsom’s return to work order hits major...,https://nypost.com/2026/07/14/us-news/legionna...
4,2026-07-14-19-03-15 +0000,nyt,U.S. and Iran Reignite War Over Strait of Hormuz,https://www.nytimes.com/live/2026/07/14/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2551/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
42    trump     39
5      iran     29
112     new     19
124  graham     17
334    will     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
260,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...,129
64,2026-07-14-17-15-00 +0000,wsj,A new bill that had been championed by the lat...,https://www.wsj.com/politics/policy/lindsey-gr...,128
173,2026-07-14-11-08-00 +0000,wsj,Will President Trump reimposing his “blockade”...,https://www.wsj.com/politics/for-whom-the-stra...,128
285,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...,118
102,2026-07-14-16-06-00 +0000,wsj,The Battle for Hormuz: Trump Shifts Into Dange...,https://www.wsj.com/world/middle-east/the-batt...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
260,129,2026-07-14-00-14-00 +0000,wsj,"President Trump is pushing Darline Graham, the...",https://www.wsj.com/politics/elections/lindsey...
97,94,2026-07-14-16-31-57 +0000,nyt,White House Cheers Inflation Data While Iran W...,https://www.nytimes.com/2026/07/14/business/ec...
173,85,2026-07-14-11-08-00 +0000,wsj,Will President Trump reimposing his “blockade”...,https://www.wsj.com/politics/for-whom-the-stra...
264,52,2026-07-14-00-00-00 +0000,wsj,"In Washington, Sen. Lindsey Graham was a power...",https://www.wsj.com/us-news/in-washington-he-w...
230,48,2026-07-14-03-51-12 +0000,nyt,Paramount-Warner Bros. Merger Is Challenged in...,https://www.nytimes.com/2026/07/13/business/pa...
254,45,2026-07-14-01-02-08 +0000,nyt,Lorenzo Salgado Araujo Chased the American Dre...,https://www.nytimes.com/2026/07/13/us/lorenzo-...
285,42,2026-07-13-21-48-00 +0000,wsj,The third consecutive night of U.S. strikes on...,https://www.wsj.com/politics/policy/third-cons...
101,37,2026-07-14-16-06-00 +0000,wsj,Chairman Kevin Warsh pledged to lawmakers that...,https://www.wsj.com/economy/central-banking/wa...
146,35,2026-07-14-13-40-13 +0000,nypost,JPMorgan Chase racks up biggest profit ever fo...,https://nypost.com/2026/07/14/business/jpmorga...
202,31,2026-07-14-09-47-59 +0000,nypost,Wife reveals how she saved husband’s life afte...,https://nypost.com/2026/07/14/world-news/wife-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)