## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-25-19-12-30 +0000,nypost,News of the World: What you missed this week i...,https://nypost.com/2026/04/25/world-news/news-...
1,2026-04-25-19-09-15 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...
2,2026-04-25-19-09-13 +0000,nyt,Trump Cancels Witkoff and Kushner’s Trip for I...,https://www.nytimes.com/2026/04/25/world/middl...
3,2026-04-25-19-07-20 +0000,startribune,"Live: Vikings select fullback Max Bredeson, co...",https://www.startribune.com/minnesota-vikings-...
4,2026-04-25-19-07-16 +0000,nypost,Influencer Klaudia Glam dies after rival creat...,https://nypost.com/2026/04/25/world-news/influ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2570/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
9    trump     22
5     iran     19
17   talks     12
6      war      9
113  house      8

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
1,2026-04-25-19-09-15 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...,93
16,2026-04-25-17-58-53 +0000,wapo,"Trump calls off Witkoff, Kushner trip to Pakis...",https://www.washingtonpost.com/world/2026/04/2...,80
38,2026-04-25-16-09-47 +0000,nypost,Trump cancels US delegation’s Pakistan trip as...,https://nypost.com/2026/04/25/world-news/trump...,73
2,2026-04-25-19-09-13 +0000,nyt,Trump Cancels Witkoff and Kushner’s Trip for I...,https://www.nytimes.com/2026/04/25/world/middl...,70
41,2026-04-25-15-59-39 +0000,cbc,Iran talks on hold as Tehran's top diplomat le...,https://www.cbc.ca/news/world/us-iran-pakistan...,70

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
1,93,2026-04-25-19-09-15 +0000,nyt,Iran War Live Updates: Trump Calls Off Witkoff...,https://www.nytimes.com/live/2026/04/25/world/...
183,47,2026-04-24-21-42-00 +0000,wsj,The Justice Department will end its Powell pro...,https://www.wsj.com/politics/policy/with-powel...
134,44,2026-04-25-01-00-00 +0000,wsj,The Trump administration has lobbied against l...,https://www.wsj.com/politics/policy/trump-repu...
20,40,2026-04-25-17-33-40 +0000,nypost,"Two police officers shot, one fatally, during ...",https://nypost.com/2026/04/25/us-news/two-poli...
159,38,2026-04-24-22-42-22 +0000,missionlocal,Oculto de la vista: la mitad de los arrestos l...,https://missionlocal.org/2026/04/oculto-de-la-...
157,36,2026-04-24-22-54-14 +0000,bbc,'My living nightmare' - Rob Reiner's son bares...,https://www.bbc.com/news/articles/c74v2enw8l7o...
116,28,2026-04-25-05-25-54 +0000,nypost,Florida Dem Sheila Cherfilus-McCormick filed f...,https://nypost.com/2026/04/25/us-news/florida-...
199,27,2026-04-24-21-02-58 +0000,nyt,Maine Governor Vetoes Bill That Would Have Pau...,https://www.nytimes.com/2026/04/24/us/maine-mo...
62,26,2026-04-25-13-54-53 +0000,cbc,Gunmen stage simultaneous attacks in and outsi...,https://www.cbc.ca/news/world/attacks-mali-cap...
50,26,2026-04-25-15-15-27 +0000,nypost,NYC high school dean allegedly ‘rubbed his gen...,https://nypost.com/2026/04/25/us-news/bronx-hi...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)