## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-17-04-50-42 +0000,nypost,NJ couple accused of killing 9-year-old daught...,https://nypost.com/2026/10/17/us-news/nj-coupl...
1,2026-10-17-04-01-20 +0000,nyt,Uncertainty Over Pope’s Health Fuels Familiar ...,https://www.nytimes.com/2026/10/17/world/europ...
2,2026-10-17-04-01-11 +0000,nyt,Japan’s ‘Dancing Salaryman’ Can’t Stop Grooving,https://www.nytimes.com/2026/10/17/world/asia/...
3,2026-10-17-04-00-00 +0000,nyt,Dancing Salaryman Pokes Fun at Japan’s Buttone...,https://www.nytimes.com/video/world/asia/10000...
4,2026-10-17-03-41-58 +0000,nypost,"GOP Sens. Ted Cruz, Susan Collins join growing...",https://nypost.com/2026/10/16/us-news/gop-sens...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2592/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
50    trump     39
119     new     21
79   school     20
237   house     13
39    white     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
37,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...,144
118,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...,123
17,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...,106
24,2026-10-17-02-20-27 +0000,nyt,"Katie Zacharia, Trump’s New Press Secretary, I...",https://www.nytimes.com/2026/10/16/us/politics...,95
179,2026-10-16-18-14-05 +0000,nypost,Trump denies restricting Ukraine’s access to S...,https://nypost.com/2026/10/16/us-news/trump-de...,90

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
37,144,2026-10-17-01-50-00 +0000,wsj,Katie Zacharia is out as White House press sec...,https://www.wsj.com/politics/policy/trump-give...
45,68,2026-10-17-01-12-39 +0000,nyt,Teacher Killed in Oregon School Shooting Was W...,https://www.nytimes.com/2026/10/16/us/bend-sch...
17,61,2026-10-17-02-42-46 +0000,chitri,President Trump puts new Russia sanctions that...,https://www.chicagotribune.com/2026/10/16/trum...
129,54,2026-10-16-20-35-28 +0000,nypost,AI stock sell-off ramps up over debt-fueled da...,https://nypost.com/2026/10/16/business/ai-stoc...
71,48,2026-10-16-23-48-38 +0000,nypost,Michele Tafoya schools Peggy Flanagan in Senat...,https://nypost.com/2026/10/16/us-news/michelle...
229,48,2026-10-16-14-34-39 +0000,cbc,"Israeli settlers attack Palestinians, American...",https://www.cbc.ca/news/world/israeli-settlers...
315,45,2026-10-16-09-52-53 +0000,nypost,Elon Musk’s three-word reaction after unveilin...,https://nypost.com/2026/10/16/business/elon-mu...
256,43,2026-10-16-13-04-00 +0000,wsj,"Canada Housing Starts Rise in September, Thoug...",https://www.wsj.com/economy/housing/canada-hou...
291,41,2026-10-16-10-46-40 +0000,nypost,Trump attacks Ukraine’s Zelensky after he says...,https://nypost.com/2026/10/16/us-news/trump-at...
118,38,2026-10-16-21-11-00 +0000,wsj,Trump told reporters that he gave Zacharia the...,https://www.wsj.com/politics/whats-news-newsle...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)