## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-08-17-20-59-27 +0000,nypost,NYC synagogue attack witness blasts New York T...,https://nypost.com/2026/08/17/media/nyc-synago...
1,2026-08-17-20-59-20 +0000,nyt,"Pauline Clayden, Dancer in a Seminal 1949 ‘Sle...",https://www.nytimes.com/2026/08/17/arts/dance/...
2,2026-08-17-20-58-00 +0000,wsj,Basic Materials Roundup: Market Talk,https://www.wsj.com/business/basic-materials-r...
3,2026-08-17-20-57-45 +0000,nypost,San Diego tourism hotspot could be shutdown af...,https://nypost.com/2026/08/17/us-news/san-dieg...
4,2026-08-17-20-55-00 +0000,wsj,Auto & Transport Roundup: Market Talk,https://www.wsj.com/business/auto-transport-ro...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2593/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
90   trump     44
96    iran     18
110    war     13
385  south     13
5      new     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
214,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...,136
76,2026-08-17-18-39-39 +0000,bbc,Trump says US to reduce military drills with S...,https://www.bbc.co.uk/news/articles/cx2lll7zvn...,124
80,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...,116
47,2026-08-17-19-50-01 +0000,startribune,Supreme Court again rebuffs Trump's push to to...,https://www.startribune.com/supreme-court-agai...,116
283,2026-08-17-00-20-54 +0000,wapo,Trump reduces military exercises with South Ko...,https://www.washingtonpost.com/politics/2026/0...,100

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
214,136,2026-08-17-10-13-00 +0000,wsj,President Trump said he would “substantially r...,https://www.wsj.com/politics/national-security...
80,72,2026-08-17-18-20-00 +0000,chitri,Supreme Court again rebuffs Trump’s push to to...,https://www.chicagotribune.com/2026/08/17/supr...
197,63,2026-08-17-11-03-00 +0000,wsj,One of the most sensitive stories in this near...,https://www.wsj.com/politics/pentagon-rotates-...
107,56,2026-08-17-16-41-56 +0000,nypost,FBI stumbled across Eric Swalwell’s affair wit...,https://nypost.com/2026/08/17/us-news/how-fbi-...
54,47,2026-08-17-19-34-57 +0000,nypost,Luigi Mangione’s NYC murder trial won’t start ...,https://nypost.com/2026/08/17/us-news/luigi-ma...
91,43,2026-08-17-17-47-48 +0000,chitri,How Chuck E. Cheese is reinventing itself for ...,https://www.chicagotribune.com/2026/08/17/chuc...
71,41,2026-08-17-18-53-12 +0000,nypost,DSA Florida House candidate appears to cut int...,https://nypost.com/2026/08/17/us-news/dsa-flor...
57,37,2026-08-17-19-25-05 +0000,bbc,Trump threatens to bomb US ally Oman if it 'ge...,https://www.bbc.co.uk/news/articles/cy5dzk0ryz...
66,32,2026-08-17-19-05-29 +0000,nypost,Nvidia provides $105B in financing toward Open...,https://nypost.com/2026/08/17/business/nvidia-...
273,31,2026-08-17-02-00-00 +0000,wsj,"With the Iowa State Fair in full swing, Republ...",https://www.wsj.com/politics/elections/rural-e...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)