## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-14-23-07-42 +0000,nyt,"How Peter Magyar Defeated Viktor Orban, a Form...",https://www.nytimes.com/2026/04/14/world/europ...
1,2026-04-14-23-04-44 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...
2,2026-04-14-23-04-00 +0000,wapo,Camp Mystic director breaks down under questio...,https://www.washingtonpost.com/nation/2026/04/...
3,2026-04-14-23-03-51 +0000,nyt,Surgeon Who Removed Wrong Organ From Patient I...,https://www.nytimes.com/2026/04/14/us/florida-...
4,2026-04-14-23-03-25 +0000,bbc,"Help to Buy mostly helped high earners, IFS says",https://www.bbc.com/news/articles/cy511kd5lkwo...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2656/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
61     trump     35
9       iran     35
10       war     19
42  swalwell     16
50       new     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
202,2026-04-14-15-49-23 +0000,nypost,Trump tells The Post US-Iran talks ‘could be h...,https://nypost.com/2026/04/14/us-news/presiden...,101
333,2026-04-14-03-56-00 +0000,wsj,Trump’s Blockade on Iran in Strait Begins,https://www.wsj.com/world/middle-east/trumps-b...,98
1,2026-04-14-23-04-44 +0000,nyt,Iran War Live Updates: U.S. Says Israel and Le...,https://www.nytimes.com/live/2026/04/14/world/...,94
187,2026-04-14-16-23-29 +0000,bbc,Oil prices continue to fall on hopes of new US...,https://www.bbc.com/news/articles/cjr9qrnp821o...,93
134,2026-04-14-18-35-38 +0000,wapo,"Trump says Iran talks may resume this week, bu...",https://www.washingtonpost.com/national-securi...,92

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
202,101,2026-04-14-15-49-23 +0000,nypost,Trump tells The Post US-Iran talks ‘could be h...,https://nypost.com/2026/04/14/us-news/presiden...
61,75,2026-04-14-21-05-47 +0000,nypost,Millionaire who sheltered Eric Swalwell as sex...,https://nypost.com/2026/04/14/us-news/milliona...
238,68,2026-04-14-13-50-22 +0000,nyt,Middle East War Will Slow Global Economic Grow...,https://www.nytimes.com/2026/04/14/business/ir...
337,58,2026-04-14-02-47-00 +0000,wsj,Canadian Prime Minister Mark Carney has secure...,https://www.wsj.com/world/americas/canadas-car...
40,57,2026-04-14-21-32-59 +0000,nypost,Camp Mystic chief sobs admitting he doesn’t kn...,https://nypost.com/2026/04/14/us-news/camp-mys...
230,53,2026-04-14-14-21-40 +0000,nypost,US boasts no ships moved through Strait of Hor...,https://nypost.com/2026/04/14/world-news/iran-...
298,48,2026-04-14-09-07-01 +0000,nypost,At least 16 injured in mass shooting at high s...,https://nypost.com/2026/04/14/world-news/at-le...
209,47,2026-04-14-15-29-59 +0000,nypost,JPMorgan CEO Jamie Dimon urges Senate to vote ...,https://nypost.com/2026/04/14/business/jpmorga...
347,38,2026-04-14-01-00-00 +0000,wsj,Trump’s post of an AI-generated image depictin...,https://www.wsj.com/politics/policy/trump-jesu...
142,37,2026-04-14-18-06-57 +0000,nypost,"Israel, Lebanon agree Hezbollah must go: ‘Unit...",https://nypost.com/2026/04/14/world-news/israe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)