## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-04-21-10-13-54 +0000,bbc,Japan loosens arms export rules in break from ...,https://www.bbc.com/news/articles/clyx4vlqy4vo...
1,2026-04-21-10-07-51 +0000,nyt,Iran War Live Updates: Uncertainty Surrounds U...,https://www.nytimes.com/live/2026/04/21/world/...
2,2026-04-21-10-03-18 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/04/21/world/...
3,2026-04-21-10-00-00 +0000,nypost,Opening statements in Harvey Weinstein’s third...,https://nypost.com/2026/04/21/us-news/opening-...
4,2026-04-21-10-00-00 +0000,latimes,'They did nothing.' L.A. girl's death raises q...,https://www.latimes.com/california/story/2026-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2580/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

     word  score
9    iran     28
78  trump     27
83    new     25
15  talks     14
10    war     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
304,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...,115
330,2026-04-20-13-22-31 +0000,nypost,Trump tells The Post he’s willing to meet with...,https://nypost.com/2026/04/20/us-news/jd-vance...,109
107,2026-04-21-01-14-06 +0000,nyt,Trump and Iran Face Off in Iran War Negotiations,https://www.nytimes.com/2026/04/20/us/politics...,106
1,2026-04-21-10-07-51 +0000,nyt,Iran War Live Updates: Uncertainty Surrounds U...,https://www.nytimes.com/live/2026/04/21/world/...,102
63,2026-04-21-07-26-13 +0000,nypost,Iran ‘prepared to reveal new cards on the batt...,https://nypost.com/2026/04/21/world-news/iran-...,101

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
304,115,2026-04-20-15-23-45 +0000,nypost,Trump tells Post he ‘will not be rushed’ to en...,https://nypost.com/2026/04/20/us-news/trump-te...
73,79,2026-04-21-05-57-56 +0000,bbc,New era as Apple names new boss to replace Tim...,https://www.bbc.com/news/articles/c1kr19lry18o...
55,70,2026-04-21-07-43-16 +0000,wsj,Stock Market Today: Stock Futures Tick Up; Kev...,https://www.wsj.com/livecoverage/kevin-warsh-f...
57,52,2026-04-21-07-39-39 +0000,nyt,Oil Prices Recede and Stocks Gain as Investors...,https://www.nytimes.com/2026/04/21/business/oi...
148,42,2026-04-20-22-16-55 +0000,wapo,Two teens killed after planned fight near Nort...,https://www.washingtonpost.com/nation/2026/04/...
164,40,2026-04-20-21-23-13 +0000,nypost,Labor Secretary Lori Chavez-DeRemer resigns fr...,https://nypost.com/2026/04/20/us-news/labor-se...
262,39,2026-04-20-17-11-43 +0000,cbc,Kenya's Korir successfully defends Boston Mara...,https://www.cbc.ca/sports/olympics/summer/athl...
281,38,2026-04-20-16-32-34 +0000,nypost,"FBI Director Kash Patel sues The Atlantic, rep...",https://nypost.com/2026/04/20/media/fbi-direct...
181,35,2026-04-20-20-51-03 +0000,nypost,Powerful California official pocketed thousand...,https://nypost.com/2026/04/20/us-news/fiona-ma...
314,33,2026-04-20-14-14-00 +0000,wsj,Seized Iranian-Flagged Ship Was Part of Fleet ...,https://www.wsj.com/world/middle-east/seized-i...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)