## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-06-01-16-27 +0000,nyt,Pastor Who Appeared on ‘American Idol’ Gets Li...,https://www.nytimes.com/2026/10/05/us/caleb-fl...
1,2026-10-06-01-11-48 +0000,bbc,"I won't accept exclusion, says Polanski after ...",https://www.bbc.co.uk/news/articles/cjy56yxxwy...
2,2026-10-06-01-09-25 +0000,nypost,Hooters shutters last location in Florida town...,https://nypost.com/2026/10/05/business/hooters...
3,2026-10-06-01-05-00 +0000,bbc,Yemeni military says it has 'secured' Red Sea ...,https://www.bbc.co.uk/news/articles/cw8rzd6lp0...
4,2026-10-06-01-04-26 +0000,nyt,A.I. hacking in Australia prompts a concern: C...,https://www.nytimes.com/live/2026/10/05/world/...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2604/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
57        new     27
133     trump     23
393     house     19
335  election     18
649     court     16

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
89,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...,168
165,2026-10-05-18-50-31 +0000,nypost,Supreme Court weighs whether to limit climate ...,https://nypost.com/2026/10/05/us-news/supreme-...,98
16,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...,98
329,2026-10-05-10-59-33 +0000,chitri,New Supreme Court term begins with cases on cl...,https://www.chicagotribune.com/2026/10/05/a-ne...,88
192,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...,88

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
89,168,2026-10-05-21-30-00 +0000,wsj,Supreme Court justices questioned the oil indu...,https://www.wsj.com/politics/policy/oil-indust...
16,98,2026-10-06-00-47-00 +0000,wsj,President Trump said he plans to pay for contr...,https://www.wsj.com/politics/policy/trump-says...
192,88,2026-10-05-17-49-10 +0000,missionlocal,Sunset Dunes se convierte en campo de batalla ...,https://missionlocal.org/2026/10/sunset-dunes-...
48,65,2026-10-05-23-01-01 +0000,chitri,"Dennis Hastert, the disgraced former US House ...",https://www.chicagotribune.com/2026/10/05/denn...
115,61,2026-10-05-20-42-19 +0000,bbc,Flávio Bolsonaro rides right-wing wave to win ...,https://www.bbc.co.uk/news/articles/cqj6je4jen...
351,42,2026-10-05-10-00-00 +0000,wsj,"Spanish Leader Calls for Elections, Riding Wav...",https://www.wsj.com/world/europe/spains-prime-...
44,37,2026-10-05-23-08-40 +0000,nypost,"More than 1K protesters descend on Cornell, de...",https://nypost.com/2026/10/05/us-news/proteste...
86,37,2026-10-05-21-39-16 +0000,nypost,Meet Meta’s billionaire AI guru –a 29-year-old...,https://nypost.com/2026/10/05/business/meet-me...
140,36,2026-10-05-20-00-00 +0000,wsj,The U.S. moved a dozen B-1 bomber aircraft fro...,https://www.wsj.com/politics/national-security...
389,36,2026-10-05-07-58-00 +0000,nypost,Ex Prince Andrew takes cops to court over Epst...,https://nypost.com/2026/10/05/world-news/ex-pr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)