## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-09-02-40-21 +0000,nyt,"Democrats Seize on Oil Topping $100 a Barrel, ...",https://www.nytimes.com/2026/03/08/world/middl...
1,2026-03-09-02-32-50 +0000,missionlocal,Photos: Chinese New Year’s Parade 2026.,https://missionlocal.org/2026/03/photos-chines...
2,2026-03-09-02-29-58 +0000,nypost,Why Gavin Newsom’s own gun laws complicate his...,https://nypost.com/2026/03/08/us-news/newsoms-...
3,2026-03-09-02-27-01 +0000,startribune,Iran names Mojtaba Khamenei to succeed his fat...,https://www.startribune.com/iranian-drone-dama...
4,2026-03-09-02-23-23 +0000,nypost,Republicans call for Trump to seize California...,https://nypost.com/2026/03/08/us-news/republic...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2659/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
24    iran     46
5    trump     27
59     war     19
10     new     17
31  leader     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
57,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...,133
160,2026-03-08-12-18-51 +0000,cbc,Iran names Khamenei's son Mojtaba as new supre...,https://www.cbc.ca/news/world/livestory/iran-i...,127
73,2026-03-08-21-37-50 +0000,nypost,Ayatollah Ali Khamenei’s son Mojtaba Khamenei ...,https://nypost.com/2026/03/08/world-news/mojta...,126
108,2026-03-08-18-15-33 +0000,nypost,Iran’s next supreme leader ‘is not going to la...,https://nypost.com/2026/03/08/world-news/irans...,116
66,2026-03-08-22-06-46 +0000,nyt,"Who Is Mojtaba Khamenei, Iran’s New Supreme Le...",https://www.nytimes.com/2026/03/08/world/middl...,113

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
57,133,2026-03-08-22-39-50 +0000,wapo,7th U.S. service member killed in war with Ira...,https://www.washingtonpost.com/world/2026/03/0...
4,60,2026-03-09-02-23-23 +0000,nypost,Republicans call for Trump to seize California...,https://nypost.com/2026/03/08/us-news/republic...
132,47,2026-03-08-16-39-17 +0000,nypost,"Gas will be below $3 soon, Energy Secretary Wr...",https://nypost.com/2026/03/08/us-news/gas-will...
156,40,2026-03-08-13-41-34 +0000,nypost,New Nepali party led by ex-rapper is set for l...,https://nypost.com/2026/03/08/world-news/new-n...
47,32,2026-03-08-23-32-56 +0000,latimes,Rihanna at home as Beverly Hills mansion is hi...,https://www.latimes.com/california/story/2026-...
212,31,2026-03-08-04-16-10 +0000,nypost,Gavin Newsom’s MLK-Gandhi ramble in Adam Fried...,https://nypost.com/2026/03/07/us-news/gavin-ne...
138,29,2026-03-08-16-14-47 +0000,nyt,Israeli Strikes on Fuel Depots Send Black Clou...,https://www.nytimes.com/2026/03/08/world/middl...
55,27,2026-03-08-22-55-43 +0000,nypost,Brady Bunch homeowner reveals her HBO exec hus...,https://nypost.com/2026/03/08/us-news/brady-bu...
34,26,2026-03-09-00-22-29 +0000,nypost,Bomb-making paraphernalia found in car near wh...,https://nypost.com/2026/03/08/us-news/bomb-mak...
28,24,2026-03-09-00-41-27 +0000,nyt,Oil Prices Surge Above $100 a Barrel for the F...,https://www.nytimes.com/2026/03/08/business/en...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)