## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-05-15-53-31 +0000,nypost,Former Michigan linebacker sues CBS for painti...,https://nypost.com/2026/09/05/us-news/ex-michi...
1,2026-09-05-15-50-00 +0000,wsj,U.S. Strikes Three Iranian Ships After Missile...,https://www.wsj.com/world/middle-east/u-s-stri...
2,2026-09-05-15-49-01 +0000,nypost,Heroic boat captain jumps in to save diver bei...,https://nypost.com/2026/09/05/us-news/heroic-b...
3,2026-09-05-15-48-09 +0000,nypost,Married couple and their young child found sho...,https://nypost.com/2026/09/05/us-news/married-...
4,2026-09-05-15-46-18 +0000,nypost,‘M*A*S*H’ star’s daughter unleashes legal chao...,https://nypost.com/2026/09/05/world-news/mash-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2550/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

        word  score
156    trump     37
554   clancy     18
553  lindsay     16
293      new     16
79       was     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
272,2026-09-04-19-09-01 +0000,nypost,"New York, New Jersey Hasidic leaders meet Trum...",https://nypost.com/2026/09/04/us-news/new-york...,93
269,2026-09-04-19-17-46 +0000,nypost,Trump delivers brutally honest verdict on Lind...,https://nypost.com/2026/09/04/us-news/trump-de...,89
180,2026-09-04-22-58-11 +0000,latimes,Judge again halts USPS mail ballot plan as Tru...,https://www.latimes.com/politics/story/2026-09...,85
40,2026-09-05-14-07-00 +0000,wsj,Putin to Meet Trump Envoys as U.S. Pushes to R...,https://www.wsj.com/world/russia/putin-to-meet...,80
232,2026-09-04-20-44-26 +0000,bbc,Watch: Inside court as judge declares a mistri...,https://www.bbc.co.uk/news/videos/c2l8z4rx5xro...,78

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
272,93,2026-09-04-19-09-01 +0000,nypost,"New York, New Jersey Hasidic leaders meet Trum...",https://nypost.com/2026/09/04/us-news/new-york...
232,78,2026-09-04-20-44-26 +0000,bbc,Watch: Inside court as judge declares a mistri...,https://www.bbc.co.uk/news/videos/c2l8z4rx5xro...
241,64,2026-09-04-20-33-00 +0000,wsj,Democrats criticized Sen. John Fetterman after...,https://www.wsj.com/politics/policy/democrats-...
153,57,2026-09-05-01-00-00 +0000,wsj,Workers across all sectors are switching jobs ...,https://www.wsj.com/economy/jobs/american-work...
41,49,2026-09-05-14-03-43 +0000,chitri,US military hits 3 Iranian oil tankers after s...,https://www.chicagotribune.com/2026/09/05/us-m...
93,47,2026-09-05-09-30-00 +0000,wsj,How do you view the major components of Americ...,https://www.wsj.com/politics/young-people-see-...
35,45,2026-09-05-14-19-51 +0000,wapo,"U.S. envoys to meet Putin in Moscow, pressing ...",https://www.washingtonpost.com/world/2026/09/0...
10,41,2026-09-05-15-29-45 +0000,nypost,Top West Indian cop hit the books to work her ...,https://nypost.com/2026/09/05/us-news/nypd-no-...
174,39,2026-09-04-23-10-01 +0000,nyt,Trump Says He Will Spend Some of His War Chest...,https://www.nytimes.com/2026/09/04/us/politics...
119,31,2026-09-05-07-20-18 +0000,nypost,UN endorses new world map showing Africa’s tru...,https://nypost.com/2026/09/05/world-news/afric...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)