## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-03-16-17-13-28 +0000,bbc,Car park firm NCP collapses with nearly 700 jo...,https://www.bbc.com/news/articles/c2e48zl4j7ko...
1,2026-03-16-17-13-14 +0000,nyt,Iran War Live Updates: Trump Criticizes Allies...,https://www.nytimes.com/live/2026/03/16/world/...
2,2026-03-16-17-13-05 +0000,nypost,Trump stuns Johnson by letting slip GOP rep’s ...,https://nypost.com/2026/03/16/us-news/trump-st...
3,2026-03-16-17-09-54 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/03/16/world/...
4,2026-03-16-17-02-26 +0000,nypost,Elderly couple killed when wrong-way driver to...,https://nypost.com/2026/03/16/us-news/elderly-...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2603/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
12    trump     39
8      iran     36
9       war     27
85   oscars     14
261     oil     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
263,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic adviser reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...,121
213,2026-03-16-01-19-41 +0000,wapo,Trump backs FCC chief’s threat to broadcasters...,https://www.washingtonpost.com/business/2026/0...,120
158,2026-03-16-08-52-15 +0000,nypost,Trump ‘thrilled’ by FCC chair Brendan Carr’s t...,https://nypost.com/2026/03/16/us-news/trump-th...,120
1,2026-03-16-17-13-14 +0000,nyt,Iran War Live Updates: Trump Criticizes Allies...,https://www.nytimes.com/live/2026/03/16/world/...,118
157,2026-03-16-08-58-17 +0000,cbc,U.S. allies wary of Trump's pleas for help in ...,https://www.cbc.ca/news/world/trump-may-delay-...,117

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
263,121,2026-03-15-18-48-46 +0000,nypost,Trump’s top economic adviser reveals massive p...,https://nypost.com/2026/03/15/us-news/trumps-t...
12,67,2026-03-16-16-53-00 +0000,wsj,President Trump said White House chief of staf...,https://www.wsj.com/politics/policy/susie-wile...
157,51,2026-03-16-08-58-17 +0000,cbc,U.S. allies wary of Trump's pleas for help in ...,https://www.cbc.ca/news/world/trump-may-delay-...
130,49,2026-03-16-10-58-00 +0000,wsj,The CIA turned to a former Chevron executive t...,https://www.wsj.com/politics/a-rare-peek-behin...
146,42,2026-03-16-09-29-01 +0000,bbc,Kpop Demon Hunters wins Oscars for best anima...,https://www.bbc.com/news/articles/cvg823zkx0go...
185,41,2026-03-16-05-14-45 +0000,bbc,'A new norm': BBC visits Doha market starting ...,https://www.bbc.com/news/videos/cp32gez414yo?a...
115,36,2026-03-16-11-49-14 +0000,nypost,Iranian drone strike takes out fuel tank at Du...,https://nypost.com/2026/03/16/world-news/irani...
66,32,2026-03-16-14-50-49 +0000,nypost,Gas prices reach highest level since October 2...,https://nypost.com/2026/03/16/business/gas-pri...
245,28,2026-03-15-21-09-33 +0000,cbc,Israel says Michigan synagogue attacker was br...,https://www.cbc.ca/news/world/michigan-synagog...
247,27,2026-03-15-20-33-20 +0000,nypost,Megyn Kelly hits rival pundit Mark Levin where...,https://nypost.com/2026/03/15/us-news/megyn-ke...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)