## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-30-07-36-07 +0000,nyt,China Threatens Retaliation as U.S. Moves to B...,https://www.nytimes.com/2026/07/30/business/ch...
1,2026-07-30-07-29-32 +0000,nypost,TSA finds Civil War-era cannonballs ‘the size ...,https://nypost.com/2026/07/30/us-news/tsa-find...
2,2026-07-30-07-29-00 +0000,wsj,Eurozone Bond Yields Track Treasury Yields Hig...,https://www.wsj.com/finance/investing/jgb-futu...
3,2026-07-30-07-27-19 +0000,bbc,Three children among eight dead in Russian str...,https://www.bbc.co.uk/news/articles/cy8mk59l5j...
4,2026-07-30-07-26-00 +0000,wsj,Sterling Falls Ahead of BOE Decision,https://www.wsj.com/finance/currencies/foreign...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2590/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
40   trump     31
134    new     24
80    iran     23
25     fed     17
10     war     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
94,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...,99
334,2026-07-29-12-46-38 +0000,nypost,Trump says US will ‘beat the f–king s–t’ out o...,https://nypost.com/2026/07/29/us-news/trump-sa...,96
205,2026-07-29-20-10-38 +0000,nypost,Trump and Netanyahu discussed ‘big three’ op...,https://nypost.com/2026/07/29/us-news/trump-an...,86
64,2026-07-30-02-28-38 +0000,nyt,"U.S. Strikes Iran Again, as Trump Encounters a...",https://www.nytimes.com/2026/07/29/us/trump-ir...,85
208,2026-07-29-19-56-01 +0000,wapo,Trump threatens to hit Iran ‘hard’ following m...,https://www.washingtonpost.com/national-securi...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
94,99,2026-07-30-00-06-00 +0000,wsj,The Pentagon bumped up its long-term Patriot m...,https://www.wsj.com/politics/national-security...
350,82,2026-07-29-11-06-00 +0000,wsj,"New York City Mayor Zohran Mamdani, not even e...",https://www.wsj.com/politics/mamdani-digs-back...
68,78,2026-07-30-02-10-00 +0000,wsj,A key committee vote to advance President Trum...,https://www.wsj.com/politics/policy/trumps-att...
182,73,2026-07-29-20-57-00 +0000,wsj,The Fed held interest rates steady on a 9-3 vo...,https://www.wsj.com/economy/central-banking/fe...
324,70,2026-07-29-13-01-38 +0000,nypost,Dr. Anthony Fauci repeatedly pleads the Fifth ...,https://nypost.com/2026/07/29/us-news/anthony-...
256,42,2026-07-29-17-15-25 +0000,cbc,"Ottawa plans to end 'Netflix tax,' replace wit...",https://www.cbc.ca/news/politics/cancon-online...
333,40,2026-07-29-12-50-05 +0000,chitri,US military launches strikes on Iranian target...,https://www.chicagotribune.com/2026/07/29/iran...
375,39,2026-07-29-10-00-00 +0000,latimes,California hopes to lure a new generation to e...,https://www.latimes.com/california/story/2026-...
138,36,2026-07-29-22-05-04 +0000,nypost,Hims & Hers sent users’ health data to social ...,https://nypost.com/2026/07/29/business/hims-he...
348,34,2026-07-29-11-17-17 +0000,cbc,Russia charges Telegram founder with aiding te...,https://www.cbc.ca/news/world/russia-telegram-...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)