## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-30-10-56-16 +0000,nypost,Creep wanted for attempting to rape 83-year-ol...,https://nypost.com/2026/10/30/us-news/creep-wa...
1,2026-10-30-10-52-07 +0000,bbc,Sir Ian McKellen leads tributes to 'beloved ac...,https://www.bbc.co.uk/news/articles/cm20v3029p...
2,2026-10-30-10-50-00 +0000,wsj,Bayer Shares Rise After Win in First Roundup T...,https://www.wsj.com/us-news/law/bayer-wins-fir...
3,2026-10-30-10-49-21 +0000,bbc,Streeting denies 'kicking can down the road' i...,https://www.bbc.co.uk/news/articles/cw62yrzxjn...
4,2026-10-30-10-44-00 +0000,wsj,BP Slashes Net Debt as Earnings Soar,https://www.wsj.com/business/earnings/bp-slash...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2719/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

           word  score
240       trump     34
198         new     28
219    election     26
638  california     16
682          up     14

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
158,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home hea...",https://www.wsj.com/politics/elections/how-ala...,146
417,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,97
30,2026-10-30-10-00-00 +0000,latimes,Becerra widens lead in governor's race as vote...,https://www.latimes.com/california/story/2026-...,96
271,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...,95
193,2026-10-29-22-51-00 +0000,chitri,President Trump lends support for Darline Grah...,https://www.chicagotribune.com/2026/10/29/trum...,94

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
158,146,2026-10-30-01-01-00 +0000,wsj,"In Alaska, high prices for diesel and home hea...",https://www.wsj.com/politics/elections/how-ala...
417,88,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...
323,80,2026-10-29-17-51-41 +0000,nypost,California High-Speed Rail Authority names new...,https://nypost.com/2026/10/29/us-news/gavin-ne...
450,59,2026-10-29-11-09-09 +0000,chitri,Prime Minister Benjamin Netanyahu’s party ampl...,https://www.chicagotribune.com/2026/10/29/isra...
453,58,2026-10-29-11-07-35 +0000,bbc,Audio reveals exchanges between Spain train op...,https://www.bbc.co.uk/news/articles/cmqxnl312v...
357,54,2026-10-29-16-26-00 +0000,wsj,U.S. economic growth picked up steam in the th...,https://www.wsj.com/economy/us-gdp-report-q3-2...
381,46,2026-10-29-15-05-15 +0000,bbc,DoorDash to buy Instacart in $17bn deal it say...,https://www.bbc.co.uk/news/articles/cm79pjg2l5...
329,45,2026-10-29-17-16-01 +0000,nypost,Wall Street con man used 87-year-old Obama don...,https://nypost.com/2026/10/29/business/wall-st...
419,42,2026-10-29-13-27-00 +0000,wsj,The European Central Bank left interest rates ...,https://www.wsj.com/economy/central-banking/ec...
271,39,2026-10-29-20-07-00 +0000,wsj,The Justice Department expanded its probe into...,https://www.wsj.com/politics/policy/justice-de...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)