## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-03-19-54-59 +0000,nypost,Moment hero fights off maniac using a spatula ...,https://nypost.com/2026/09/03/us-news/socal-in...
1,2026-09-03-19-52-36 +0000,nyt,Norway Seizes Russian Research Ship in the Hig...,https://www.nytimes.com/2026/09/03/world/europ...
2,2026-09-03-19-45-22 +0000,nyt,Here’s the latest.,https://www.nytimes.com/live/2026/09/03/us/lin...
3,2026-09-03-19-45-00 +0000,wsj,Many Litigants Try to Challenge Trump. Suing H...,https://www.wsj.com/us-news/law/many-litigants...
4,2026-09-03-19-43-00 +0000,wsj,Campbell’s Cuts 13% of Workforce in Effort to ...,https://www.wsj.com/business/earnings/campbell...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2527/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
22   trump     44
483    new     21
121     up     17
149   iran     15
186     no     13

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
320,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...,113
257,2026-09-03-10-00-00 +0000,latimes,Convicted Trump Media-linked fraudster funded ...,https://www.latimes.com/politics/story/2026-09...,107
45,2026-09-03-18-34-16 +0000,nypost,Vance says no ‘security concern’ behind Trump ...,https://nypost.com/2026/09/03/us-news/vance-sa...,102
270,2026-09-03-09-30-00 +0000,wsj,"Capital Account: Under his “Donroe” doctrine, ...",https://www.wsj.com/economy/trade/canada-doesn...,99
419,2026-09-02-19-56-53 +0000,nyt,Trump Returns to a Familiar Playbook as the Wa...,https://www.nytimes.com/2026/09/02/us/politics...,97

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
320,113,2026-09-03-02-09-29 +0000,chitri,Judge blocks President Trump’s new bid to curb...,https://www.chicagotribune.com/2026/09/02/trum...
259,74,2026-09-03-10-00-00 +0000,nypost,Dem NY House candidate Cait Conley ripped over...,https://nypost.com/2026/09/03/us-news/ny-dem-c...
20,62,2026-09-03-19-10-38 +0000,nypost,"Vance won’t call Iran fight a ‘war’, says Chin...",https://nypost.com/2026/09/03/us-news/vance-wo...
378,59,2026-09-02-22-14-20 +0000,latimes,Dolly Parton's Walk of Fame star scratched up ...,https://www.latimes.com/california/story/2026-...
45,52,2026-09-03-18-34-16 +0000,nypost,Vance says no ‘security concern’ behind Trump ...,https://nypost.com/2026/09/03/us-news/vance-sa...
330,51,2026-09-03-01-00-00 +0000,wsj,With conservative figures such as Steve Bannon...,https://www.wsj.com/politics/policy/bernie-aoc...
9,49,2026-09-03-19-36-42 +0000,nypost,Lindsay Clancy’s lawyer drops courtroom bombsh...,https://nypost.com/2026/09/03/us-news/lindsay-...
21,44,2026-09-03-19-09-00 +0000,wsj,Vice President JD Vance defended his friendshi...,https://www.wsj.com/politics/policy/vance-defe...
394,42,2026-09-02-20-51-44 +0000,nypost,Plane carrying DHS Secretary Markwayne Mullin ...,https://nypost.com/2026/09/02/us-news/plane-ca...
231,40,2026-09-03-11-26-18 +0000,latimes,"Gloria Steinem, charismatic feminist and co-fo...",https://www.latimes.com/world-nation/story/202...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)