## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-29-18-14-46 +0000,bbc,US interest rates held for fifth time in a row,https://www.bbc.co.uk/news/articles/cy07wgqjv0...
1,2026-07-29-18-13-44 +0000,chitri,The last Bennigan’s in Illinois is thriving in...,https://www.chicagotribune.com/2026/07/29/benn...
2,2026-07-29-18-10-00 +0000,wsj,Two New Jersey Men Accused of Supporting Islam...,https://www.wsj.com/us-news/two-new-jersey-men...
3,2026-07-29-18-09-08 +0000,nyt,What to know about the Fed’s decision.,https://www.nytimes.com/live/2026/07/29/busine...
4,2026-07-29-18-08-17 +0000,nyt,A U.S. Citizen Deleted His Phone’s Data. Now H...,https://www.nytimes.com/2026/07/28/us/duress-p...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2352/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

       word  score
200   trump     39
61     iran     23
12      new     23
76   senate     19
286  graham     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
353,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...,133
160,2026-07-29-12-46-38 +0000,nypost,Trump says US will ‘beat the f–king s–t’ out o...,https://nypost.com/2026/07/29/us-news/trump-sa...,104
402,2026-07-28-19-02-23 +0000,nypost,Trump gives out Lindsey Graham’s personal phon...,https://nypost.com/2026/07/28/us-news/trump-gi...,97
122,2026-07-29-14-48-05 +0000,nypost,"Dow slumps 700 points, oil jumps over 6% after...",https://nypost.com/2026/07/29/business/dow-slu...,97
220,2026-07-29-09-07-40 +0000,bbc,Trump's new spy chief Jay Clayton confirmed by...,https://www.bbc.co.uk/news/articles/c0rd1kl182...,95

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
353,133,2026-07-28-21-24-00 +0000,wsj,"President Trump, Vice President JD Vance and w...",https://www.wsj.com/politics/policy/president-...
183,93,2026-07-29-11-06-00 +0000,wsj,"New York City Mayor Zohran Mamdani, not even e...",https://www.wsj.com/politics/mamdani-digs-back...
291,72,2026-07-29-00-36-00 +0000,wsj,"With the Iran war continuing, Israeli Prime Mi...",https://www.wsj.com/world/middle-east/netanyah...
8,56,2026-07-29-18-01-00 +0000,wsj,The Fed held interest rates steady on a 9-3 vo...,https://www.wsj.com/economy/central-banking/fe...
150,51,2026-07-29-13-01-38 +0000,nypost,Dr. Anthony Fauci repeatedly pleads the Fifth ...,https://nypost.com/2026/07/29/us-news/anthony-...
244,47,2026-07-29-07-20-21 +0000,nypost,Russia charges Telegram founder Pavel Durov wi...,https://nypost.com/2026/07/29/world-news/teleg...
345,43,2026-07-28-21-41-00 +0000,wsj,The Trump administration plans to halt a Medic...,https://www.wsj.com/politics/policy/medicare-d...
383,41,2026-07-28-20-07-09 +0000,cbc,15-year-old arrested in Seattle festival shoot...,https://www.cbc.ca/news/world/seattle-shooting...
36,40,2026-07-29-17-14-20 +0000,chitri,President Donald Trump and DOJ ask Supreme Cou...,https://www.chicagotribune.com/2026/07/29/trum...
306,40,2026-07-28-23-33-05 +0000,nypost,"US, Saudi Arabia launch joint strikes on Iran’...",https://nypost.com/2026/07/28/us-news/iran-lau...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)