## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-25-10-00-00 +0000,startribune,Brehm: Minneapolis needs to eliminate addictio...,https://www.startribune.com/brehm-minneapolis-...
1,2026-09-24-20-53-03 +0000,nyt,U.N. Live Updates: Netanyahu Lashes Out at Cri...,https://www.nytimes.com/live/2026/09/24/world/...
2,2026-09-24-20-50-28 +0000,nyt,Massachusetts Is Investigating Gambling Compan...,https://www.nytimes.com/2026/09/24/business/ma...
3,2026-09-24-20-48-30 +0000,nyt,"Netanyahu, Addressing U.N., Denounces Israel’s...",https://www.nytimes.com/2026/09/24/world/middl...
4,2026-09-24-20-45-57 +0000,nyt,"White House Restores Access for CNN, MS NOW an...",https://www.nytimes.com/2026/09/24/business/me...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2279/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
54   trump     86
133    new     32
339     xi     30
340  china     22
614     ai     17

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
137,2026-09-24-17-51-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...,201
435,2026-09-23-22-01-17 +0000,bbc,Trump and Xi come face-to-face as US and China...,https://www.bbc.co.uk/news/articles/c6gqdgg8w5...,187
282,2026-09-24-10-59-00 +0000,wsj,As President Trump and China’s Xi Jinping prep...,https://www.wsj.com/politics/policy/as-trump-a...,183
432,2026-09-23-22-22-13 +0000,chitri,"China’s President Xi arrives in Washington, ki...",https://www.chicagotribune.com/2026/09/23/chin...,183
386,2026-09-24-00-44-44 +0000,nypost,Trump greets China’s Xi at airport in historic...,https://nypost.com/2026/09/23/us-news/trump-gr...,178

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
137,201,2026-09-24-17-51-00 +0000,wsj,The White House said it was restoring access t...,https://www.wsj.com/politics/policy/judge-orde...
435,101,2026-09-23-22-01-17 +0000,bbc,Trump and Xi come face-to-face as US and China...,https://www.bbc.co.uk/news/articles/c6gqdgg8w5...
191,88,2026-09-24-16-10-06 +0000,nyt,New Hampshire Senate Race: 5 Takeaways From a ...,https://www.nytimes.com/2026/09/24/us/politics...
352,66,2026-09-24-06-41-39 +0000,nypost,Abdul El-Sayed won’t say he stands against Ira...,https://nypost.com/2026/09/24/us-news/abdul-el...
100,56,2026-09-24-18-53-54 +0000,nypost,Netanyahu accuses Mamdani of making NYC unsafe...,https://nypost.com/2026/09/24/us-news/israeli-...
200,54,2026-09-24-16-00-00 +0000,wsj,Average 30-year mortgage rates hit 7.03% this ...,https://www.wsj.com/economy/housing/mortgage-r...
264,53,2026-09-24-11-36-59 +0000,nypost,Eight sailors in USS Abraham Lincoln strike gr...,https://nypost.com/2026/09/24/us-news/eight-sa...
114,50,2026-09-24-18-31-54 +0000,latimes,California woman missing since 2007 found buri...,https://www.latimes.com/california/story/2026-...
6,49,2026-09-24-20-45-06 +0000,nypost,South Carolina high school football star kille...,https://nypost.com/2026/09/24/us-news/south-ca...
253,45,2026-09-24-12-30-05 +0000,nyt,Mark Carney Interview: Canada’s Leader Lays Ou...,https://www.nytimes.com/2026/09/23/world/canad...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)