## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-07-22-02-46-23 +0000,nypost,School bus transporting students from Maryland...,https://nypost.com/2026/07/21/us-news/school-b...
1,2026-07-22-02-43-58 +0000,nyt,Trump Administration Is Said to Reach Broad Nu...,https://www.nytimes.com/2026/07/21/us/politics...
2,2026-07-22-02-37-17 +0000,nyt,"House Narrowly Passes Stopgap Spending Bill, b...",https://www.nytimes.com/2026/07/21/us/politics...
3,2026-07-22-02-36-58 +0000,wapo,Drone attack deaths show risk has shifted to t...,https://www.washingtonpost.com/national-securi...
4,2026-07-22-02-36-52 +0000,nyt,France Joins a Global Move Toward Restricting ...,https://www.nytimes.com/2026/07/21/world/europ...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2699/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

          word  score
8        trump     44
32        iran     36
92         new     26
73         war     18
83  california     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
104,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...,146
322,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...,136
39,2026-07-22-00-01-00 +0000,wsj,Defense Secretary Pete Hegseth estimated the l...,https://www.wsj.com/politics/national-security...,127
234,2026-07-21-16-22-24 +0000,nypost,Trump warns Iran of much greater destruction i...,https://nypost.com/2026/07/21/us-news/trump-wa...,115
359,2026-07-21-09-49-42 +0000,nyt,Trump Administration and Iran Officials Risk a...,https://www.nytimes.com/2026/07/20/world/middl...,112

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
104,146,2026-07-21-21-26-00 +0000,wsj,Pete Hegseth estimates the Iran war will cost ...,https://www.wsj.com/politics/policy/iran-war-t...
256,103,2026-07-21-15-40-27 +0000,nypost,"US, Mexico resume USMCA trade talks as Trump s...",https://nypost.com/2026/07/21/world-news/us-me...
34,55,2026-07-22-00-29-59 +0000,nypost,Fourth soldier believed to be killed in Iran a...,https://nypost.com/2026/07/21/us-news/fourth-s...
367,52,2026-07-21-09-15-55 +0000,bbc,AI minister role boosted but tech department a...,https://www.bbc.co.uk/news/articles/cz97x8k4zq...
262,48,2026-07-21-15-22-29 +0000,chitri,This year’s supersized World Cup had some thin...,https://www.chicagotribune.com/2026/07/21/worl...
265,47,2026-07-21-15-18-10 +0000,nypost,RFK Jr. halts Medicaid funds to California and...,https://nypost.com/2026/07/21/us-news/rfk-jr-y...
130,42,2026-07-21-20-45-37 +0000,cbc,Zelenskyy replaces head of Ukraine's army amid...,https://www.cbc.ca/news/world/zelenskyy-syrsky...
47,41,2026-07-21-23-56-56 +0000,nypost,Silicon Valley boss snared over 145mph horror ...,https://nypost.com/2026/07/21/us-news/silicon-...
209,41,2026-07-21-17-16-16 +0000,nypost,Chinese AI firms that rip off US models could ...,https://nypost.com/2026/07/21/business/chinese...
322,38,2026-07-21-12-17-55 +0000,nypost,Trump says US will hit Iran’s ‘Pickaxe Mountai...,https://nypost.com/2026/07/21/world-news/israe...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)