## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-10-29-13-54-32 +0000,nypost,Russian drone strike kills at least 14 on Ukra...,https://nypost.com/2026/10/29/world-news/russi...
1,2026-10-29-13-54-00 +0000,wsj,China’s Xi Demands More Loyalty as Purges Trim...,https://www.wsj.com/world/china/chinas-xi-dema...
2,2026-10-29-13-52-00 +0000,wsj,Nasdaq Slumps After Google Earnings Disappoint,https://www.wsj.com/finance/stocks/ai-stocks-f...
3,2026-10-29-13-50-00 +0000,wsj,U.S. economic growth picked up steam in the th...,https://www.wsj.com/economy/us-gdp-report-q3-2...
4,2026-10-29-13-49-20 +0000,bbc,US convicts Rwandan man who hid genocide role ...,https://www.bbc.co.uk/news/articles/cmkgq90yxg...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2650/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

         word  score
48   election     29
127     trump     25
138       fed     15
24         up     15
47     israel     15

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
295,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...,123
453,2026-10-28-15-01-00 +0000,wsj,"Last year, The Wall Street Journal brought tog...",https://www.wsj.com/politics/elections/these-g...,107
21,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...,106
426,2026-10-28-16-34-01 +0000,nyt,Netanyahu Didn’t Win Israel’s Election. But He...,https://www.nytimes.com/2026/10/28/world/middl...,88
229,2026-10-29-02-00-00 +0000,wsj,"In Texas, signs of Hispanic voters’ disillusio...",https://www.wsj.com/politics/elections/the-his...,83

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
295,123,2026-10-28-21-24-18 +0000,nypost,Trump calls for Alaska Dem candidate Mary Pelt...,https://nypost.com/2026/10/28/us-news/trump-ca...
238,78,2026-10-29-01-12-00 +0000,wsj,Fed Chairman Kevin Warsh said higher rates are...,https://www.wsj.com/economy/central-banking/th...
21,77,2026-10-29-13-28-00 +0000,wsj,America is getting an energy election twice ov...,https://www.wsj.com/politics/policy/your-guide...
211,66,2026-10-29-04-44-00 +0000,wsj,"In a comeback attempt, Democrat Keisha Lance B...",https://www.wsj.com/politics/elections/the-ex-...
25,64,2026-10-29-13-27-00 +0000,wsj,The European Central Bank left interest rates ...,https://www.wsj.com/economy/central-banking/ec...
435,59,2026-10-28-16-03-00 +0000,wsj,Spain’s Second High-Speed Train Crash This Yea...,https://www.wsj.com/world/europe/spain-high-sp...
267,57,2026-10-28-22-31-00 +0000,wsj,"How Weil Gotshal, One of Wall Street’s Most St...",https://www.wsj.com/business/how-weil-gotshal-...
249,52,2026-10-29-00-49-53 +0000,nypost,Haley Stevens’ fiancé will vote for Mike Roger...,https://nypost.com/2026/10/28/us-news/haley-st...
76,51,2026-10-29-12-00-00 +0000,nypost,California’s billionaire tax gets a brutal rea...,https://nypost.com/2026/10/29/us-news/predicti...
237,50,2026-10-29-01-14-01 +0000,bbc,Flávio Bolsonaro denies fleeing Brazil after l...,https://www.bbc.co.uk/news/articles/c6kglwe4lx...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)