## Load latest headlines

In [1]:
# ========== Bootstrap: ensure required Python packages are present =========
import importlib, subprocess, sys
from typing import Optional

def _ensure(pkg_name: str, import_name: Optional[str] = None):
    try:
        importlib.import_module(import_name or pkg_name)
    except ModuleNotFoundError:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pkg_name])
    finally:
        globals()[import_name or pkg_name] = importlib.import_module(import_name or pkg_name)

_ensure('pandas')
print('All dependencies ready.\n')

All dependencies ready.

In [2]:
from pathlib import Path
archive = Path('archive')
archive.mkdir(exist_ok=True)
import pandas as pd
latest = pd.read_csv('../headlines/latest.csv')
latest.head()

,pubdate,source,title,link
0,2026-09-08-18-51-58 +0000,bbc,Highest paid world leader to get $1m salary in...,https://www.bbc.co.uk/news/videos/c9dw05egq1qo...
1,2026-09-08-18-48-30 +0000,nypost,Students are rising up against Flock cameras: ...,https://nypost.com/2026/09/08/us-news/flock-ca...
2,2026-09-08-18-47-59 +0000,nypost,Rikers monitor blasts Mamdani’s jail boss for ...,https://nypost.com/2026/09/08/us-news/rikers-m...
3,2026-09-08-18-44-50 +0000,nyt,CCRCs Are Expanding Retirement Home Care to Se...,https://www.nytimes.com/2026/09/06/business/re...
4,2026-09-08-18-44-01 +0000,nypost,Thailand to deport French zoo owner who banned...,https://nypost.com/2026/09/08/world-news/thail...

## Calculate word frequencies

In [3]:
import re
from collections import Counter
from datetime import datetime

with open('exclude.txt') as f:
    stop_words = set(w.strip() for w in f if w.strip())
words = re.findall(r'[A-Za-z]+', ' '.join(latest['title']).lower())
filtered = [w for w in words if w not in stop_words and len(w) > 1]
counts = Counter(filtered)
score_df = (
    pd.DataFrame(counts.items(), columns=['word','score'])
    .sort_values('score', ascending=False)
)
score_df[['score','word']].to_csv('scores.csv', index=False)
timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')
score_df[['score','word']].to_csv(archive / f'scores-{timestamp}.csv', index=False)
score_df.head()

/tmp/ipykernel_2448/2220774760.py:15: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow().strftime('%Y-%m-%d-%H-00-00')

      word  score
80   trump     39
144    new     22
105  trade     15
204    oil     13
86     out     12

## Rank headlines by score

In [4]:
word_scores = dict(score_df[['word','score']].values)
latest['score'] = latest['title'].apply(
    lambda t: sum(
        word_scores.get(w.lower(), 0)
        for w in re.findall(r'[A-Za-z]+', t)
        if len(w) > 1
    )
)
ranked = latest.sort_values('score', ascending=False)
ranked[['score','pubdate','source','title','link']].to_csv('rank.csv', index=False)
ranked[['score','pubdate','source','title','link']].to_csv(archive / f'rank-{timestamp}.csv', index=False)
ranked.head()

,pubdate,source,title,link,score
284,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...,94
117,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...,90
121,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...,84
100,2026-09-08-16-28-58 +0000,nyt,Bombardier Shares Down as Trump’s Trade War Ta...,https://www.nytimes.com/2026/09/08/business/bo...,83
207,2026-09-08-11-03-00 +0000,wsj,"Jared Kushner, one of President Trump’s sons-i...",https://www.wsj.com/politics/policy/jared-kush...,82

## Select top headlines

In [5]:
with open('exclude_sources.txt') as f:
    excluded_sources = {
        line.strip()
        for line in f
        if line.strip() and not line.strip().startswith('#')
    }

top_count = 10
top_rows = []
working = word_scores.copy()
remaining = latest.copy()

while len(top_rows) < top_count and not remaining.empty:
    scored_remaining = remaining.assign(
        score=remaining['title'].apply(
            lambda t: sum(
                working.get(w.lower(), 0)
                for w in re.findall(r'[A-Za-z]+', t)
                if len(w) > 1
            )
        )
    )
    ranked_loop = scored_remaining.sort_values('score', ascending=False)

    if ranked_loop.empty:
        break

    top_story = ranked_loop.iloc[0]
    remaining = remaining.drop(top_story.name)

    if top_story['source'] in excluded_sources:
        continue

    words = set(re.findall(r'[A-Za-z]+', top_story['title'].lower()))
    for word in words:
        working.pop(word, None)

    top_rows.append(top_story[['score', 'pubdate', 'source', 'title', 'link']])

top_df = pd.DataFrame(top_rows)
top_df.to_csv('top.csv', index=False)
top_df.to_csv(archive / f'top-{timestamp}.csv', index=False)
top_df

,score,pubdate,source,title,link
284,94,2026-09-08-06-56-41 +0000,nyt,Canada Imposes New Tariffs on U.S. Goods After...,https://www.nytimes.com/2026/09/08/business/ca...
121,72,2026-09-08-15-50-06 +0000,nypost,"UK, France and Canada halt trade with Israeli ...",https://nypost.com/2026/09/08/us-news/uk-franc...
255,53,2026-09-08-09-10-00 +0000,wsj,Oil Nears $100 a Barrel as Fresh Attacks on Sa...,https://www.wsj.com/world/middle-east/oil-near...
117,51,2026-09-08-16-00-00 +0000,wsj,Smithsonian Secretary Lonnie Bunch III is reti...,https://www.wsj.com/arts-culture/fine-art/smit...
13,47,2026-09-08-18-33-27 +0000,nypost,Family of victims in 130mph LA crash storm out...,https://nypost.com/2026/09/08/us-news/family-o...
72,44,2026-09-08-17-07-04 +0000,nypost,NASCAR legend spills on grand plans for $400M ...,https://nypost.com/2026/09/08/lifestyle/nascar...
344,40,2026-09-07-20-11-43 +0000,cbc,Trump to Canadian plane maker Bombardier: You ...,https://www.cbc.ca/news/canada/trump-bombardie...
219,34,2026-09-08-10-46-00 +0000,wsj,Three numbers show how China’s extraordinary e...,https://www.wsj.com/economy/trade/three-number...
249,34,2026-09-08-09-32-59 +0000,nyt,French A.I. Start-Up Mistral Raises $3.5 Billi...,https://www.nytimes.com/2026/09/08/business/mi...
15,34,2026-09-08-18-29-10 +0000,nyt,Australian Social Media Users Could Get Power ...,https://www.nytimes.com/2026/09/08/world/austr...

## Create JSON version of top headlines

In [6]:
import pandas as pd
pd.read_csv('top.csv').to_json('top.json', orient='records', indent=2)